node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype" value { type: DT_FLOAT } }
  attr {
    key: "shape"
    value {
      shape {
        dim { size: 1 }
        dim { size: 2 }
        dim { size: 1 }
        dim { size: 2 }
      }
    }
  }
}
node {
  name: "my/customOp/000"
  op: "new_custom_op"
  input: "Placeholder"
  attr {
    key: "T"
    value { type: DT_FLOAT }
  }
  attr {
    key: "my_string"
    value { s: "Hello World" }
  }
  attr {
    key: "my_float"
    value { f: 0.001 }
  }
  attr {
    key: "my_int"
    value { i: 111 }
  }
  attr {
    key: "my_bool"
    value { b: false }
  }
}
node {
  name: "output/relu"
  op: "Relu"
  input: "my/customOp/000"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
