#!/bin/bash

import "build.configuration"

if [[ ! -d "${BUILD_PATH}" ]]; then
  echo "[ERROR] '${BUILD_PATH}' does not exist. Please run 'configure' first"
  exit 255
fi

cmake --build ${BUILD_PATH} -- "$@"
