#!/bin/bash

import "build.configuration"

if [[ ! -d "${BUILD_PATH}" ]]; then
  echo "[ERROR] '${BUILD_PATH}' does not exist. Please run 'configure' first"
  exit 255
fi

# Set parallel build
# TODO Use argument instead of environment variable
HOST_OS=${HOST_OS:-linux}
NPROCS=${NPROCS:-1}
ALL_PROC_BUILD=${ALL_PROC_BUILD:-1}

if [ "${ALL_PROC_BUILD}" == "1" ]; then
  # Get number of processors (linux only for now)
  if [ "${HOST_OS}" == "linux" ]; then
    NPROCS="$(grep -c ^processor /proc/cpuinfo)"
  fi
fi

cd ${BUILD_PATH}
make -j ${NPROCS} "$@"
