#!/bin/bash

import "build.configuration"

if [[ ! -d "${BUILD_PATH}" ]]; then
  echo "[ERROR] '${BUILD_PATH}' does not exist. Please run 'configure' first"
  exit 255
fi

# Set parallel build
# TODO Use argument instead of environment variable
HOST_OS=${HOST_OS:-linux}
NPROCS=${NPROCS:-1}

cd ${BUILD_PATH}
make -j ${NPROCS} "$@"
