#!/bin/bash

INVALID_EXIT=0

check_copyright() {
  DIRECTORIES_NOT_TO_BE_TESTED=$1
  CORRECT_COPYRIGHT="Copyright \(c\) [0-9\-]+ Samsung Electronics Co\., Ltd\. All Rights Reserved"

  FILES_TO_CHECK=$(git ls-files -c --exclude-standard)
  FILES_TO_CHECK_COPYRIGHTS=()
  for f in ${FILES_TO_CHECK[@]}; do
    # Manually ignore checking
    if [[ ${f} == +(*/NeuralNetworks.h|*/NeuralNetworksExtensions.h) ]]; then
      continue
    fi

    # File extension to check
    if [[ ${f} == +(*.h|*.hpp|*.cpp|*.cc|*.c|*.cl) ]]; then
      FILES_TO_CHECK_COPYRIGHTS+=("${f}")
    fi
  done

  for s in ${DIRECTORIES_NOT_TO_BE_TESTED[@]}; do
    FILES_TO_CHECK_COPYRIGHTS=(${FILES_TO_CHECK_COPYRIGHTS[*]/$s*/})
  done

  if [[ ${#FILES_TO_CHECK_COPYRIGHTS} -ne 0 ]]; then
    for f in ${FILES_TO_CHECK_COPYRIGHTS[@]}; do
      if ! grep -qE "$CORRECT_COPYRIGHT" $f; then
        CREATED_YEAR=$(git log --follow --format=%aD $f | tail -1 | awk '{print $4}')
        EXAMPLE_COPYRIGHT="Copyright (c) $CREATED_YEAR Samsung Electronics Co., Ltd. All Rights Reserved"
        echo "Copyright format of $f is incorrect: recommend \"$EXAMPLE_COPYRIGHT\""
        INVALID_EXIT=1
      fi
    done
  fi
}

DIRECTORIES_NOT_TO_BE_TESTED=()

for DIR_NOT_TO_BE_TESTED in $(git ls-files -co --exclude-standard '*/.FORMATDENY'); do
    DIRECTORIES_NOT_TO_BE_TESTED+=("$DIR_NOT_TO_BE_TESTED")
  DIRECTORIES_NOT_TO_BE_TESTED+=($(dirname "${DIR_NOT_TO_BE_TESTED}"))
done

check_copyright $DIRECTORIES_NOT_TO_BE_TESTED

if [[ $INVALID_EXIT -ne 0 ]]; then
    echo "[FAILED] Invalid copyright check exit."
    exit 1
fi
