#!/bin/bash
#
# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

Usage()
{
    echo "Usage: ./$0 [--install-path=Product/out]"
}

INSTALL_PATH=Product/out

for i in "$@"
do
    case $i in
        -h|--help|help)
            Usage
            exit 1
            ;;
        --install-path=*)
            INSTALL_PATH=${i#*=}
            ;;
        *)
            Usage
            exit 1
            ;;
    esac
    shift
done

# List of gtest binaries
GTEST_BINS=(
    unittest_standalone/nnfw_api_gtest
    unittest_standalone/test_compute
    unittest_standalone/test_onert
    unittest_standalone/test_onert_backend_cpu_common
    unittest_standalone/test_onert_frontend_nnapi
    unittest_standalone/tflite_test
)

# Collect test cases
echo "Install Path : '$INSTALL_PATH'"
TEST_LIST=
for GTEST_BIN in ${GTEST_BINS[@]}; do
    GTEST_PATH=$INSTALL_PATH/$GTEST_BIN
    echo "Collecting test cases from '$GTEST_PATH'"
    TESTS=$($GTEST_PATH --gtest_list_tests | grep '^  ')
    if [ "$?" -ne 0 ]; then
        echo "Error collecting test cases from '$GTEST_PATH'"
        exit 1;
    fi
    TEST_LIST=$TEST_LIST$TESTS
done

# Count stats
TOTAL_TCS=$(echo "$TEST_LIST" | wc -l)
TOTAL_NEG_TCS=$(echo "$TEST_LIST" | grep '^  neg_' | wc -l)
TOTAL_POS_TCS=$(echo "$TEST_LIST" | grep '^  neg_' -v | wc -l)

# Report stats
printf "TOTAL NUMBER OF TEST CASES          : %5d\n" $TOTAL_TCS
printf "TOTAL NUMBER OF POSTIVE TEST CASES  : %5d\n" $TOTAL_POS_TCS
printf "TOTAL NUMBER OF NEGATIVE TEST CASES : %5d\n" $TOTAL_NEG_TCS
