#!/bin/bash

import "docker.configuration"

DOCKER_RUN_OPTS+=" -u $(id -u):$(id -g)"

docker run $DOCKER_RUN_OPTS $DOCKER_ENV_VARS $DOCKER_VOLUMES $DOCKER_IMAGE_NAME "$@"
EXITCODE=$?

if [ $EXITCODE -ne 0 ]; then
  exit $EXITCODE
fi
