#!/bin/bash

import "docker.configuration"

docker run $DOCKER_RUN_OPTS $DOCKER_ENV_VARS $DOCKER_VOLUMES $DOCKER_IMAGE_NAME "$@"
EXITCODE=$?

docker_cleanup

if [ $EXITCODE -ne 0 ]; then
  exit $EXITCODE
fi
