ONE - On-device Neural Engine: compiler/circle-resizer/app/CircleResizer.cpp File Reference
CircleResizer.cpp File Reference
#include "ModelEditor.h"
#include "ShapeParser.h"
#include <arser/arser.h>
#include <vconone/vconone.h>
#include <iostream>
#include <memory>
#include <string>
Functions
int entry (const int argc, char **argv)
Function Documentation
entry()
int entry (const int argc, char ** argv)
Definition at line 48 of file CircleResizer.cpp.
{
  arser::Arser arser("circle-resizer provides capabilities to change inputs of the models");
  arser.add_argument("--input_path")
    .nargs(1)
    .type(arser::DataType::STR)
    .required(true)
    .help("Path to the input model (.circle)");
  arser.add_argument("--output_path")
    .nargs(1)
    .type(arser::DataType::STR)
    .required(true)
    .help("Path to the resized model (.circle)");
  arser.add_argument("--input_shapes")
    .nargs(1)
    .type(arser::DataType::STR)
    .required(true)
    .help("New inputs shapes in the comma separated format. An example for 2 inputs: [1,2],[3,4].");
  arser.add_argument("--version")
    .nargs(0)
    .required(false)
    .default_value(false)
    .help("Show version information and exit")
    .exit_with(print_version);
  try
  {
    arser.parse(argc, argv);
    const auto input_path = arser.get<std::string>("--input_path");
    auto circle_model = std::make_shared<CircleModel>(input_path);
    ModelEditor resizer(circle_model);
    std::cout << "Shapes of inputs before resizing:" << std::endl;
    list_shapes(circle_model->input_shapes());
    std::cout << "Shapes of outputs before resizing:" << std::endl;
    list_shapes(circle_model->output_shapes());
    const auto output_path = arser.get<std::string>("--output_path");
    const auto new_input_shapes_str = arser.get<std::string>("--input_shapes");
    resizer.resize_inputs(parse_shapes(new_input_shapes_str));
    std::cout << "Shapes of inputs after resizing:" << std::endl;
    list_shapes(circle_model->input_shapes());
    std::cout << "Shapes of outputs after resizing:" << std::endl;
    list_shapes(circle_model->output_shapes());
    circle_model->save(output_path);
    std::cout << "Resizing complete, the model saved to: " << output_path << std::endl;
  }
  catch (const std::runtime_error &err)
  {
    std::cerr << "Exception during resizing: " << err.what() << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
References circle_resizer::parse_shapes(), print_version(), and circle_resizer::ModelEditor::resize_inputs().