ONE - On-device Neural Engine: compiler/circle-interpreter/src/CircleInterpreter.cpp File Reference
CircleInterpreter.cpp File Reference
#include <arser/arser.h>
#include <luci/ImporterEx.h>
#include <luci_interpreter/Interpreter.h>
#include <vconone/vconone.h>
#include <cstdlib>
#include <fstream>
#include <vector>
#include <string>
Functions
int entry (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Definition at line 74 of file CircleInterpreter.cpp.
{
  arser::Arser arser("Interpreter driver for circle models");
  arser::Helper::add_version(arser, print_version);
  arser.add_argument("model_path").help("Circle model filepath");
  arser.add_argument("input_prefix")
    .help("Input data filepath for circle model. "
          "n-th input data is read from ${input_prefix}n, "
          "for example, Add.circle.input0, Add.circle.input1");
  arser.add_argument("output_prefix")
    .help("Output data filepath for circle model. "
          "Output data is written in ${output_file}n, "
          "for example, Add.circle.output0");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cout << err.what() << std::endl;
    std::cout << arser;
    return EXIT_FAILURE;
  }
  const auto filename = arser.get<std::string>("model_path");
  const auto input_prefix = arser.get<std::string>("input_prefix");
  const auto output_prefix = arser.get<std::string>("output_prefix");
  // Load model from the file
  luci::ImporterEx importer;
  std::unique_ptr<luci::Module> module = importer.importVerifyModule(filename);
  if (module == nullptr)
  {
    std::cerr << "ERROR: Failed to load '" << filename << "'" << std::endl;
    return EXIT_FAILURE;
  }
  // Create interpreter.
  luci_interpreter::Interpreter interpreter(module.get());
  // Set input.
  // Data for n'th input is read from ${input_prefix}n
  // (ex: Add.circle.input0, Add.circle.input1 ..)
  const auto input_nodes = loco::input_nodes(module->graph());
  for (int32_t i = 0; i < input_nodes.size(); i++)
  {
    const auto *input_node = loco::must_cast<const luci::CircleInput *>(input_nodes[i]);
    std::vector<char> input_data(getTensorSize(input_node));
    readDataFromFile(std::string(input_prefix) + std::to_string(i), input_data.data(),
                     input_data.size());
    interpreter.writeInputTensor(input_node, input_data.data(), input_data.size());
  }
  // Do inference.
  interpreter.interpret();
  // Get output.
  const auto output_nodes = loco::output_nodes(module->graph());
  for (int i = 0; i < module->graph()->outputs()->size(); i++)
  {
    const auto *output_node = loco::must_cast<const luci::CircleOutput *>(output_nodes[i]);
    std::vector<char> output_data(getTensorSize(output_node));
    interpreter.readOutputTensor(output_node, output_data.data(), output_data.size());
    // Output data is written in ${output_file}n
    // (ex: Add.circle.output0)
    writeDataToFile(std::string(output_prefix) + std::to_string(i), output_data.data(),
                    output_data.size());
  }
  return EXIT_SUCCESS;
}
References arser::Helper::add_version(), loco::input_nodes(), loco::output_nodes(), and print_version().