ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Concatenation.float.cpp File Reference
Concatenation.float.cpp File Reference
#include "Concatenation.float.h"
#include "internal/Array.h"
#include "internal/Matrix.h"
#include "internal/Fused.h"
Functions
template<FusedActivationFunctionType Ac, typename Scalar >
void Concatenation (int concat_dim, const Scalar *const *input_data, const Dims< 4 > *const *input_dims, int inputs_count, Scalar *output_data, const Dims< 4 > &output_dims)
bool concatenationFloat32 (const std::vector< const float * > &inputDataPtrs, const std::vector< Shape > &inputShapes, int32_t axis, float *outputData, const Shape &outputShape)
Function Documentation
Concatenation()
template<FusedActivationFunctionType Ac, typename Scalar > void Concatenation (int concat_dim, const Scalar *const * input_data, const Dims< 4 > *const * input_dims, int inputs_count, Scalar * output_data, const Dims< 4 > & output_dims)
Definition at line 27 of file Concatenation.float.cpp.
{
  DCHECK_GT(inputs_count, 1);
  int concat_size = 0;
  for (int i = 0; i < inputs_count; i++)
  {
    for (int j = 0; j < 4; j++)
    {
      if (j != concat_dim)
      {
        MatchingArraySize(*input_dims[i], j, output_dims, j);
      }
    }
    concat_size += ArraySize(*input_dims[i], concat_dim);
  }
  DCHECK_EQ(concat_size, ArraySize(output_dims, concat_dim));
  DCHECK(IsPackedWithoutStrides(output_dims));
  // for now we dont have a model with a Concatenation
  // with fused activation function.
  DCHECK(Ac == FusedActivationFunctionType::kNone);
  int outer_size = 1;
  for (int i = concat_dim + 1; i < 4; i++)
  {
    outer_size *= output_dims.sizes[i];
  }
  Scalar *output_ptr = output_data;
  for (int k = 0; k < outer_size; k++)
  {
    for (int i = 0; i < inputs_count; ++i)
    {
      const int copy_size = input_dims[i]->sizes[concat_dim] * input_dims[i]->strides[concat_dim];
      memcpy(output_ptr, input_data[i] + k * copy_size, copy_size * sizeof(Scalar));
      output_ptr += copy_size;
    }
  }
}
References ArraySize(), DCHECK, DCHECK_EQ, DCHECK_GT, IsPackedWithoutStrides(), kNone, MatchingArraySize(), Dims< N >::sizes, and Dims< N >::strides.
Referenced by tflite::reference_ops::DepthConcatenation(), and tflite::reference_ops::LstmCell().
concatenationFloat32()
bool concatenationFloat32 (const std::vector< const float * > & inputDataPtrs, const std::vector< Shape > & inputShapes, int32_t axis, float * outputData, const Shape & outputShape)
Definition at line 66 of file Concatenation.float.cpp.
{
  int num_inputs = inputShapes.size();
  std::vector<Dims<4> *> inputDimsPtr(num_inputs);
  std::vector<Dims<4>> inputDims(num_inputs);
  for (int i = 0; i < num_inputs; i++)
  {
    inputDims[i] = convertShapeToDims(inputShapes[i]);
    inputDimsPtr[i] = &inputDims[i];
  }
  Concatenation<FusedActivationFunctionType::kNone, float>(
      getNumberOfDimensions(outputShape) - axis - 1, inputDataPtrs.data(), inputDimsPtr.data(),
      num_inputs, outputData, convertShapeToDims(outputShape));
  return true;
}
References convertShapeToDims(), and getNumberOfDimensions().