ONE - On-device Neural Engine: compiler/nnc/unittests/acl_backend/DOMToText.cpp File Reference
DOMToText.cpp File Reference
#include <sstream>
#include <tuple>
#include "ArtifactModel.h"
#include "ArtifactGeneratorCppCode.h"
#include "ArtifactGeneratorCppDecl.h"
#include "AclArtifactUtilities.generated.h"
#include "gtest/gtest.h"
Typedefs
using AF = ArtifactFactory
Functions
TEST (acl_backend_dom_to_text, ArtifactLiteral)
TEST (acl_backend_dom_to_text, ArtifactId)
TEST (acl_backend_dom_to_text, ArtifactRef)
TEST (acl_backend_dom_to_text, ArtifactDeref)
TEST (acl_backend_dom_to_text, ArtifactFunctionCall)
TEST (acl_backend_dom_to_text, ArtifactUnaryExpr)
TEST (acl_backend_dom_to_text, ArtifactBinaryExpr)
TEST (acl_backend_dom_to_text, ArtifactIndex)
TEST (acl_backend_dom_to_text, ArtifactRet)
TEST (acl_backend_dom_to_text, ArtifactBreak)
TEST (acl_backend_dom_to_text, ArtifactCont)
TEST (acl_backend_dom_to_text, ArtifactVariable)
TEST (acl_backend_dom_to_text, ArtifactBlock)
TEST (acl_backend_dom_to_text, ArtifactForLoop)
TEST (acl_backend_dom_to_text, ArtifactIf)
TEST (acl_backend_dom_to_text, ArtifactFunction)
TEST (acl_backend_dom_to_text, ArtifactClassVariable)
TEST (acl_backend_dom_to_text, ArtifactClassFunction)
TEST (acl_backend_dom_to_text, ArtifactClass)
TEST (acl_backend_dom_to_text, ArtifactModule)
Typedef Documentation
AF
using AF = ArtifactFactory
Definition at line 37 of file DOMToText.cpp.
Function Documentation
TEST() [1/20]
TEST (acl_backend_dom_to_text , ArtifactBinaryExpr)
Definition at line 174 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *op1_name = "a";
  const char *op2_name = "b";
  shared_ptr<ArtifactId> op1 = AF::id(op1_name);
  shared_ptr<ArtifactId> op2 = AF::id(op2_name);
  pair<ArtifactBinOp, const char *> test_cases[] = {
    {ArtifactBinOp::eq, "a == b"},          {ArtifactBinOp::notEq, "a != b"},
    {ArtifactBinOp::less, "a < b"},         {ArtifactBinOp::lessOrEq, "a <= b"},
    {ArtifactBinOp::great, "a > b"},        {ArtifactBinOp::greatOrEq, "a >= b"},
    {ArtifactBinOp::assign, "a = b"},       {ArtifactBinOp::plus, "a + b"},
    {ArtifactBinOp::minus, "a - b"},        {ArtifactBinOp::mult, "a * b"},
    {ArtifactBinOp::div, "a / b"},          {ArtifactBinOp::plusAssign, "a += b"},
    {ArtifactBinOp::minusAssign, "a -= b"}, {ArtifactBinOp::multAssign, "a *= b"},
    {ArtifactBinOp::divAssign, "a /= b"}};
  for (auto test : test_cases)
  {
    auto op_type = test.first;
    auto ref_output = test.second;
    checkBinaryExpression(op_type, op1, op2, ref_output);
  }
}
References nnc::ArtifactFactory::id().
TEST() [2/20]
TEST (acl_backend_dom_to_text , ArtifactBlock)
Definition at line 259 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *var_name = "var";
  const char *lit_val = "123";
  shared_ptr<ArtifactExpr> id = AF::id(var_name);
  shared_ptr<ArtifactExpr> lit = AF::lit(lit_val);
  const list<shared_ptr<ArtifactExpr>> args{id, lit};
  shared_ptr<ArtifactFunctionCall> call = AF::call("foo", args);
  ArtifactBlock block;
  block.addStatement(call);
  block.accept(&code_gen);
  ASSERT_EQ(code_out.str(), " {\n  foo(var, 123);\n}\n");
}
References nnc::ArtifactBlock::accept(), nnc::ArtifactBlock::addStatement(), nnc::ArtifactFactory::call(), nnc::ArtifactFactory::id(), and nnc::ArtifactFactory::lit().
TEST() [3/20]
TEST (acl_backend_dom_to_text , ArtifactBreak)
Definition at line 225 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactBreak brk;
  brk.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "break");
}
References nnc::ArtifactBreak::accept().
TEST() [4/20]
TEST (acl_backend_dom_to_text , ArtifactClass)
Definition at line 434 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  ArtifactClass cls("Class");
  createClsFunction(cls, "public_foo", true);
  createClsFunction(cls, "private_bar", false);
  createClsVariable(cls, "visible", true);
  createClsVariable(cls, "invisible", false);
  // Test cpp file generation
  cls.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "Class::Class() : invisible(123) {\n}\n\n"
                            "void Class::public_foo(int a, int b) {\n}\n\n"
                            "void Class::private_bar(int a, int b) {\n}\n\n");
  // Test header file generation
  cls.accept(&decl_gen);
  ASSERT_EQ(decl_out.str(), "class Class {\npublic:\n  Class();\n"
                            "  void public_foo(int a, int b);"
                            "\n\nprivate:\n  void private_bar(int a, int b);\n\n"
                            "  int invisible;\n};\n");
}
References nnc::ArtifactClass::accept().
TEST() [5/20]
TEST (acl_backend_dom_to_text , ArtifactClassFunction)
Definition at line 371 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *ret_type = "int";
  const char *func_name = "foo";
  shared_ptr<ArtifactVariable> arg1 = AF::var("int", "a");
  shared_ptr<ArtifactVariable> arg2 = AF::var("bool", "b");
  list<shared_ptr<ArtifactVariable>> args{arg1, arg2};
  ArtifactClass cls("Class");
  // test public class variable
  shared_ptr<ArtifactClassFunction> cls_func_decl = cls.func(true, ret_type, func_name, args);
  cls_func_decl->accept(&code_gen);
  // FIXME do not print new line in this visitor
  ASSERT_EQ(code_out.str(), "int Class::foo(int a, bool b) {\n}\n\n");
  cls_func_decl->accept(&decl_gen);
  ASSERT_EQ(decl_out.str(), "int foo(int a, bool b);\n");
  decl_out.str("");
  code_out.str("");
  // test private class variable
  cls_func_decl = cls.func(false, ret_type, func_name, args);
  cls_func_decl->accept(&code_gen);
  // FIXME do not print new line in this visitor
  ASSERT_EQ(code_out.str(), "int Class::foo(int a, bool b) {\n}\n\n");
  cls_func_decl->accept(&decl_gen);
  ASSERT_EQ(decl_out.str(), "int foo(int a, bool b);\n");
}
References nnc::ArtifactClass::func(), and nnc::ArtifactFactory::var().
TEST() [6/20]
TEST (acl_backend_dom_to_text , ArtifactClassVariable)
Definition at line 346 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *var_type = "int";
  const char *var_name = "data";
  ArtifactClass cls("Class");
  shared_ptr<ArtifactLiteral> dim1 = AF::lit("2");
  shared_ptr<ArtifactLiteral> dim2 = AF::lit("3");
  list<shared_ptr<ArtifactExpr>> dims{dim1, dim2};
  list<shared_ptr<ArtifactExpr>> list_of_initializer{AF::lit("123")};
  ArtifactClassVariable var_decl(&cls, var_type, var_name, dims, list_of_initializer);
  var_decl.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "data(123)");
  var_decl.accept(&decl_gen);
  // fixme dimensions are not taken into account, remove ';'
  ASSERT_EQ(decl_out.str(), "int data;\n");
}
References nnc::ArtifactClassVariable::accept(), and nnc::ArtifactFactory::lit().
TEST() [7/20]
TEST (acl_backend_dom_to_text , ArtifactCont)
Definition at line 234 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactCont cont;
  cont.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "continue");
}
References nnc::ArtifactCont::accept().
TEST() [8/20]
TEST (acl_backend_dom_to_text , ArtifactDeref)
Definition at line 83 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *id_data = "some_id";
  shared_ptr<ArtifactId> id = AF::id(id_data);
  shared_ptr<ArtifactDeref> deref = AF::deref(id);
  deref->accept(&code_gen);
  deref->accept(&decl_gen);
  string ref_data = string("*") + id_data;
  ASSERT_EQ(code_out.str(), ref_data);
  ASSERT_EQ(decl_out.str(), ref_data);
}
References nnc::ArtifactFactory::deref(), and nnc::ArtifactFactory::id().
TEST() [9/20]
TEST (acl_backend_dom_to_text , ArtifactForLoop)
Definition at line 280 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *var_name = "i";
  const char *var_type = "int";
  shared_ptr<ArtifactVariable> iter = AF::var(var_type, var_name, {}, {AF::lit("0")});
  shared_ptr<ArtifactExpr> step =
    AF::bin(ArtifactBinOp::plusAssign, AF::id(var_name), AF::lit("1"));
  shared_ptr<ArtifactExpr> cond =
    AF::bin(ArtifactBinOp::lessOrEq, AF::id(var_name), AF::lit("123"));
  shared_ptr<ArtifactBinaryExpr> expr =
    AF::bin(ArtifactBinOp::plusAssign, AF::id("hello"), AF::id("world"));
  ArtifactForLoop loop(iter, cond, step);
  loop.getBlock()->addStatement(expr);
  loop.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "for(int i(0); i <= 123; i += 1) {\n  hello += world;\n}\n");
}
References nnc::ArtifactForLoop::accept(), nnc::ArtifactBlock::addStatement(), nnc::ArtifactFactory::bin(), nnc::ArtifactForLoop::getBlock(), nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), and nnc::ArtifactFactory::var().
TEST() [10/20]
TEST (acl_backend_dom_to_text , ArtifactFunction)
Definition at line 324 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *ret_type = "int";
  const char *func_name = "foo";
  shared_ptr<ArtifactVariable> arg1 = AF::var("int", "a");
  shared_ptr<ArtifactVariable> arg2 = AF::var("bool", "b");
  list<shared_ptr<ArtifactVariable>> args{arg1, arg2};
  // test public class variable
  ArtifactFunction func_decl(ret_type, func_name, args);
  func_decl.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "");
  func_decl.accept(&decl_gen);
  ASSERT_EQ(decl_out.str(), "int foo(int a, bool b);");
}
References nnc::ArtifactFunction::accept(), and nnc::ArtifactFactory::var().
TEST() [11/20]
TEST (acl_backend_dom_to_text , ArtifactFunctionCall)
Definition at line 110 of file DOMToText.cpp.
{
  const char *lit_data = "123";
  const char *id_data = "some_id";
  shared_ptr<ArtifactExpr> id = AF::id(id_data);
  shared_ptr<ArtifactExpr> lit = AF::lit(lit_data);
  const list<shared_ptr<ArtifactExpr>> args{id, lit};
  shared_ptr<ArtifactId> obj = AF::id("obj");
  using TestCase = tuple<ArtifactCallType, shared_ptr<ArtifactExpr>, const char *>;
  TestCase test_cases[] = {TestCase{ArtifactCallType::scope, nullptr, "foo(some_id, 123)"},
                           TestCase{ArtifactCallType::obj, obj, "obj.foo(some_id, 123)"},
                           TestCase{ArtifactCallType::ref, obj, "obj->foo(some_id, 123)"},
                           TestCase{ArtifactCallType::scope, obj, "obj::foo(some_id, 123)"}};
  for (const auto &test : test_cases)
  {
    ArtifactCallType call_type = get<0>(test);
    shared_ptr<ArtifactExpr> obj = get<1>(test);
    const char *ref_output = get<2>(test);
    checkCall(call_type, "foo", args, obj, ref_output);
  }
}
References nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), and nnc::obj.
TEST() [12/20]
TEST (acl_backend_dom_to_text , ArtifactId)
Definition at line 53 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *id_data = "some_id";
  shared_ptr<ArtifactId> id = AF::id(id_data);
  id->accept(&code_gen);
  id->accept(&decl_gen);
  ASSERT_EQ(code_out.str(), id_data);
  ASSERT_EQ(decl_out.str(), id_data);
}
References nnc::ArtifactFactory::id().
TEST() [13/20]
TEST (acl_backend_dom_to_text , ArtifactIf)
Definition at line 304 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *var_name = "i";
  shared_ptr<ArtifactExpr> cond =
    AF::bin(ArtifactBinOp::lessOrEq, AF::id(var_name), AF::lit("123"));
  shared_ptr<ArtifactBinaryExpr> expr =
    AF::bin(ArtifactBinOp::plusAssign, AF::id("hello"), AF::id("world"));
  ArtifactIf if_stmt(cond);
  if_stmt.getBlock()->addStatement(expr);
  if_stmt.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "if(i <= 123) {\n  hello += world;\n}\n");
}
References nnc::ArtifactIf::accept(), nnc::ArtifactBlock::addStatement(), nnc::ArtifactFactory::bin(), nnc::ArtifactIf::getBlock(), nnc::ArtifactFactory::id(), and nnc::ArtifactFactory::lit().
TEST() [14/20]
TEST (acl_backend_dom_to_text , ArtifactIndex)
Definition at line 201 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *arr_name = "a";
  const char *idx_name = "b";
  shared_ptr<ArtifactId> arr = AF::id(arr_name);
  shared_ptr<ArtifactId> idx = AF::id(idx_name);
  shared_ptr<ArtifactIndex> indexing = AF::ind(arr, idx);
  indexing->accept(&code_gen);
  ASSERT_EQ(code_out.str(), "a[b]");
}
References nnc::ArtifactFactory::id(), and nnc::ArtifactFactory::ind().
TEST() [15/20]
TEST (acl_backend_dom_to_text , ArtifactLiteral)
Definition at line 39 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *lit_data = "hello_world";
  shared_ptr<ArtifactLiteral> lit = AF::lit(lit_data);
  lit->accept(&code_gen);
  lit->accept(&decl_gen);
  ASSERT_EQ(code_out.str(), lit_data);
  ASSERT_EQ(decl_out.str(), lit_data);
}
References nnc::ArtifactFactory::lit().
TEST() [16/20]
TEST (acl_backend_dom_to_text , ArtifactModule)
Definition at line 464 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  ArtifactModule m("module");
  m.addHeaderInclude("foo.h");
  m.addHeaderSysInclude("vector");
  m.addSourceInclude("bar.h");
  m.addSourceSysInclude("list");
  shared_ptr<ArtifactClass> cls = m.createClass("Class");
  // test cpp file generation
  // We use snippet code to encode some common functions
  // This snippet is wrapped in prefix and postfix code
  const char *code_prefix = "#include \"module.h\"\n\n#include <list>\n\n#include \"bar.h\"\n\n";
  const char *code_suffix = "\nClass::Class() {\n}\n\n";
  string ref_data =
    string(code_prefix) + string(AclArtifactUtilities, sizeof(AclArtifactUtilities)) + code_suffix;
  m.accept(&code_gen);
  ASSERT_EQ(code_out.str(), ref_data);
  // test header code generation
  const char *ref_decl_data = "#include <vector>\n\n#include \"foo.h\"\n\nclass Class {\npublic:\n "
                              " Class();\n\nprivate:\n};\n";
  m.accept(&decl_gen);
  ASSERT_EQ(decl_out.str(), ref_decl_data);
}
References m.
TEST() [17/20]
TEST (acl_backend_dom_to_text , ArtifactRef)
Definition at line 67 of file DOMToText.cpp.
{
  stringstream code_out;
  stringstream decl_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  ArtifactGeneratorCppDecl decl_gen(decl_out);
  const char *id_data = "some_id";
  shared_ptr<ArtifactId> id = AF::id(id_data);
  shared_ptr<ArtifactRef> ref = AF::ref(id);
  ref->accept(&code_gen);
  ref->accept(&decl_gen);
  string ref_data = string("&") + id_data;
  ASSERT_EQ(code_out.str(), ref_data);
  ASSERT_EQ(decl_out.str(), ref_data);
}
References nnc::ArtifactFactory::id(), nnc::ref, and nnc::ArtifactFactory::ref().
TEST() [18/20]
TEST (acl_backend_dom_to_text , ArtifactRet)
Definition at line 214 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *result_name = "a";
  shared_ptr<ArtifactId> result = AF::id(result_name);
  ArtifactRet ret(result);
  ret.accept(&code_gen);
  ASSERT_EQ(code_out.str(), "return a");
}
References nnc::ArtifactRet::accept(), and nnc::ArtifactFactory::id().
TEST() [19/20]
TEST (acl_backend_dom_to_text , ArtifactUnaryExpr)
Definition at line 146 of file DOMToText.cpp.
{
  const char *var_name = "id";
  shared_ptr<ArtifactId> var = AF::id(var_name);
  pair<ArtifactUnOp, const char *> test_cases[] = {
    {ArtifactUnOp::preIncr, "++id"},   {ArtifactUnOp::preDecr, "--id"},
    {ArtifactUnOp::heapNew, "new id"}, {ArtifactUnOp::heapFree, "delete id"},
    {ArtifactUnOp::postIncr, "id++"},  {ArtifactUnOp::postDecr, "id--"}};
  for (auto test : test_cases)
  {
    auto op_type = test.first;
    auto ref_output = test.second;
    checkUnaryExpression(op_type, var, ref_output);
  }
}
References nnc::ArtifactFactory::id().
TEST() [20/20]
TEST (acl_backend_dom_to_text , ArtifactVariable)
Definition at line 243 of file DOMToText.cpp.
{
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
  const char *var_type = "int";
  const char *var_name = "data";
  shared_ptr<ArtifactLiteral> dim1 = AF::lit("2");
  shared_ptr<ArtifactLiteral> dim2 = AF::lit("3");
  list<shared_ptr<ArtifactExpr>> dims{dim1, dim2};
  list<shared_ptr<ArtifactExpr>> initializers{AF::lit("123")};
  shared_ptr<ArtifactVariable> var_decl = AF::var(var_type, var_name, dims, initializers);
  var_decl->accept(&code_gen);
  // TODO generate initializers in braces
  ASSERT_EQ(code_out.str(), "int data[2][3](123)");
}
References nnc::ArtifactFactory::lit(), and nnc::ArtifactFactory::var().