ONE - On-device Neural Engine: compiler/enco/core/src/Support/Debugging.cpp File Reference
Debugging.cpp File Reference
#include "Debugging.h"
#include <pp/LinearDocument.h>
#include <pp/MultiLineTextUtils.h>
#include <stack>
#include <iostream>
Macros
#define DEBUGGING_API_P(NAME, TYPE, VAR)
Functions
DEBUGGING_API_P (enco_dump_all_bags, coco::Module, m)
DEBUGGING_API_P (enco_dump_all_objects, coco::Module, m)
DEBUGGING_API_P (enco_dump_op, coco::Op, op)
DEBUGGING_API_P (enco_dump_op_tree, coco::Op, op)
DEBUGGING_API_P (enco_dump_all_ops, coco::Module, m)
DEBUGGING_API_P (enco_dump_all_instrs, coco::Module, m)
DEBUGGING_API_P (enco_dump_all_instrs_v, coco::Module, m)
DEBUGGING_API_P (enco_dump_instr, coco::Instr, ins)
DEBUGGING_API_P (enco_dump_block, coco::Block, blk)
Macro Definition Documentation
DEBUGGING_API_P
#define DEBUGGING_API_P (NAME, TYPE, VAR)
Value:
  static void _##NAME(const TYPE *);                             \
  void NAME(long p) { NAME(reinterpret_cast<const TYPE *>(p)); } \
  void NAME(const TYPE *p)                                       \
  {                                                              \
    if (p == nullptr)                                            \
    {                                                            \
      std::cout << "(nullptr)" << std::endl;                     \
    }                                                            \
    else                                                         \
    {                                                            \
      _##NAME(p);                                                \
    }                                                            \
  }                                                              \
  void _##NAME(const TYPE *VAR)
Definition at line 26 of file Debugging.cpp.
Function Documentation
DEBUGGING_API_P() [1/9]
DEBUGGING_API_P (enco_dump_all_bags , coco::Module , m)
Definition at line 102 of file Debugging.cpp.
{
  for (uint32_t n = 0; n < m->entity()->bag()->size(); ++n)
  {
    auto bag = m->entity()->bag()->at(n);
    assert(bag != nullptr);
    auto set = [bag](pp::LinearDocument &doc) { doc.append(describe(bag)); };
    auto desc = section("bag").build(set);
    std::cout << desc << std::endl;
  }
}
References pp::LinearDocument::append(), and m.
DEBUGGING_API_P() [2/9]
DEBUGGING_API_P (enco_dump_all_instrs , coco::Module , m)
Definition at line 475 of file Debugging.cpp.
{
  for (uint32_t n = 0; n < m->entity()->instr()->size(); ++n)
  {
    auto ins = m->entity()->instr()->at(n);
    assert(ins != nullptr);
    auto setter = [ins](pp::LinearDocument &doc) { doc.append(describe(ins)); };
    auto desc = section("instr").build(setter);
    std::cout << desc << std::endl;
  }
}
References pp::LinearDocument::append(), and m.
DEBUGGING_API_P() [3/9]
DEBUGGING_API_P (enco_dump_all_instrs_v , coco::Module , m)
Definition at line 489 of file Debugging.cpp.
{
  for (uint32_t n = 0; n < m->entity()->instr()->size(); ++n)
  {
    auto ins = m->entity()->instr()->at(n);
    assert(ins != nullptr);
    auto setter = [ins](pp::LinearDocument &doc) { doc.append(describe(ins, true)); };
    auto desc = section("instr").build(setter);
    std::cout << desc << std::endl;
  }
}
References pp::LinearDocument::append(), and m.
DEBUGGING_API_P() [4/9]
DEBUGGING_API_P (enco_dump_all_objects , coco::Module , m)
Definition at line 174 of file Debugging.cpp.
{
  for (uint32_t n = 0; n < m->entity()->object()->size(); ++n)
  {
    auto obj = m->entity()->object()->at(n);
    assert(obj != nullptr);
    auto set = [obj](pp::LinearDocument &doc) { doc.append(describe(obj)); };
    auto desc = section("object").build(set);
    std::cout << desc << std::endl;
  }
}
References pp::LinearDocument::append(), and m.
DEBUGGING_API_P() [5/9]
DEBUGGING_API_P (enco_dump_all_ops , coco::Module , m)
Definition at line 399 of file Debugging.cpp.
{
  SectionBuilder section_builder{"op"};
  for (uint32_t n = 0; n < m->entity()->op()->size(); ++n)
  {
    auto op = m->entity()->op()->at(n);
    assert(op != nullptr);
    auto desc = section("op").build([op](pp::LinearDocument &doc) { doc.append(describe(op)); });
    std::cout << desc << std::endl;
  }
}
References pp::LinearDocument::append(), and m.
DEBUGGING_API_P() [6/9]
DEBUGGING_API_P (enco_dump_block , coco::Block , blk)
Definition at line 533 of file Debugging.cpp.
{ std::cout << describe(blk) << std::endl; }
DEBUGGING_API_P() [7/9]
DEBUGGING_API_P (enco_dump_instr , coco::Instr , ins)
Definition at line 503 of file Debugging.cpp.
{
  auto setter = [ins](pp::LinearDocument &doc) { doc.append(describe(ins, true)); };
  auto desc = section("instr").build(setter);
  std::cout << desc << std::endl;
}
References pp::LinearDocument::append().
DEBUGGING_API_P() [8/9]
DEBUGGING_API_P (enco_dump_op , coco::Op , op)
Definition at line 385 of file Debugging.cpp.
{
  {
    std::cout << describe(op) << std::endl;
  }
}
DEBUGGING_API_P() [9/9]
DEBUGGING_API_P (enco_dump_op_tree , coco::Op , op)
Definition at line 392 of file Debugging.cpp.
{
  {
    std::cout << describe(OpTree(op)) << std::endl;
  }
}