ONE - On-device Neural Engine: compiler/luci-eval-driver/src/EvalDriver.cpp File Reference
EvalDriver.cpp File Reference
#include <luci/ImporterEx.h>
#include <luci_interpreter/Interpreter.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
Functions
int entry (int argc, char **argv)
Dump IR for given arguments.
Function Documentation
entry()
int entry (int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 65 of file EvalDriver.cpp.
{
  if (argc != 5)
  {
    std::cerr
      << "Usage: " << argv[0]
      << " <path/to/circle/model> <num_inputs> <path/to/input/prefix> <path/to/output/file>\n";
    return EXIT_FAILURE;
  }
  const char *filename = argv[1];
  const int32_t num_inputs = atoi(argv[2]);
  const char *input_prefix = argv[3];
  const char *output_file = argv[4];
  // Load model from the file
  luci::ImporterEx importer;
  std::unique_ptr<luci::Module> module = importer.importVerifyModule(filename);
  if (module == nullptr)
  {
    std::cerr << "ERROR: Failed to load '" << filename << "'" << std::endl;
    return EXIT_FAILURE;
  }
  // Create interpreter.
  luci_interpreter::Interpreter interpreter(module.get());
  // Set input.
  // Data for n'th input is read from ${input_prefix}n
  // (ex: Add.circle.input0, Add.circle.input1 ..)
  const auto input_nodes = loco::input_nodes(module->graph());
  assert(num_inputs == input_nodes.size());
  for (int32_t i = 0; i < num_inputs; i++)
  {
    const auto *input_node = loco::must_cast<const luci::CircleInput *>(input_nodes[i]);
    std::vector<char> input_data(getTensorSize(input_node));
    readDataFromFile(std::string(input_prefix) + std::to_string(i), input_data.data(),
                     input_data.size());
    interpreter.writeInputTensor(input_node, input_data.data(), input_data.size());
  }
  // Do inference.
  interpreter.interpret();
  // Get output.
  const auto output_nodes = loco::output_nodes(module->graph());
  for (int i = 0; i < module->graph()->outputs()->size(); i++)
  {
    const auto *output_node = loco::must_cast<const luci::CircleOutput *>(output_nodes[i]);
    std::vector<char> output_data(getTensorSize(output_node));
    interpreter.readOutputTensor(output_node, output_data.data(), output_data.size());
    // Output data is written in ${output_file}
    // (ex: Add.circle.output0)
    // Output shape is written in ${output_file}.shape
    // (ex: Add.circle.output0.shape)
    writeDataToFile(std::string(output_file) + std::to_string(i), output_data.data(),
                    output_data.size());
    // In case of Tensor output is Scalar value.
    // The output tensor with rank 0 is treated as a scalar with shape (1)
    if (output_node->rank() == 0)
    {
      writeDataToFile(std::string(output_file) + std::to_string(i) + ".shape", "1", 1);
    }
    else
    {
      auto shape_str = std::to_string(output_node->dim(0).value());
      for (int j = 1; j < output_node->rank(); j++)
      {
        shape_str += ",";
        shape_str += std::to_string(output_node->dim(j).value());
      }
      writeDataToFile(std::string(output_file) + std::to_string(i) + ".shape", shape_str.c_str(),
                      shape_str.size());
    }
  }
  return EXIT_SUCCESS;
}
References luci::ImporterEx::importVerifyModule(), loco::input_nodes(), and loco::output_nodes().