ONE - On-device Neural Engine: compiler/ann-ref/src/ops/FullyConnected.float.cpp File Reference
FullyConnected.float.cpp File Reference
#include "FullyConnected.float.h"
#include "Assert.h"
#include "internal/Matrix.h"
#include "internal/Fused.h"
#include "internal/GEMM.h"
#include "internal/ActivationUtils.h"
Macros
#define ANDROID_NN_FULLY_CONNECTED(activation)
Functions
template<FusedActivationFunctionType Ac>
void FullyConnected (const float *input_data, const Dims< 4 > &input_dims, const float *weights_data, const Dims< 4 > &weights_dims, const float *bias_data, const Dims< 4 > &bias_dims, float *output_data, const Dims< 4 > &output_dims)
bool fullyConnectedFloat32 (const float *inputData, const Shape &inputShape, const float *weightsData, const Shape &weightsShape, const float *biasData, const Shape &biasShape, int32_t activation, float *outputData, const Shape &outputShape)
Macro Definition Documentation
ANDROID_NN_FULLY_CONNECTED
#define ANDROID_NN_FULLY_CONNECTED (activation)
Value:
  FullyConnected<FusedActivationFunctionType::activation>(                                      \
      inputData, convertShapeToDims(inputShape), weightsData, convertShapeToDims(weightsShape), \
      biasData, convertShapeToDims(biasShape), outputData, convertShapeToDims(outputShape))
Function Documentation
FullyConnected()
template<FusedActivationFunctionType Ac> void FullyConnected (const float * input_data, const Dims< 4 > & input_dims, const float * weights_data, const Dims< 4 > & weights_dims, const float * bias_data, const Dims< 4 > & bias_dims, float * output_data, const Dims< 4 > & output_dims)
Definition at line 29 of file FullyConnected.float.cpp.
{
  // TODO(b/62193649): this convoluted shape computation (determining
  // input_rows from the weights_dims, then MapAsMatrixWithGivenNumberOfRows)
  // is because the current --variable_batch hack consists in overwriting the
  // 3rd dimension with the runtime batch size, as we don't keep track for each
  // array of which dimension is the batch dimension in it.
  // When that is fixed, this should become:
  // const auto input_matrix_map =
  //     MapAsMatrixWithFirstDimAsRows(input_data, input_dims);
  const int input_rows = ArraySize(weights_dims, 0);
  const auto input_matrix_map =
      MapAsMatrixWithGivenNumberOfRows(input_data, input_dims, input_rows);
  const auto filter_matrix_map = MapAsMatrixWithFirstDimAsRows(weights_data, weights_dims);
  auto output_matrix_map = MapAsMatrixWithFirstDimAsRows(output_data, output_dims);
  Gemm(filter_matrix_map.transpose(), input_matrix_map, &output_matrix_map);
  AddBiasAndEvalActivationFunction<Ac>(bias_data, bias_dims, output_data, output_dims);
}
References ArraySize(), Gemm(), MapAsMatrixWithFirstDimAsRows(), and MapAsMatrixWithGivenNumberOfRows().
Referenced by tflite::reference_ops::LstmCell(), dalgona::PostOperatorHook::visit(), and dalgona::PreOperatorHook::visit().
fullyConnectedFloat32()
bool fullyConnectedFloat32 (const float * inputData, const Shape & inputShape, const float * weightsData, const Shape & weightsShape, const float * biasData, const Shape & biasShape, int32_t activation, float * outputData, const Shape & outputShape)
Definition at line 51 of file FullyConnected.float.cpp.
{
#define ANDROID_NN_FULLY_CONNECTED(activation)                                                  \
  FullyConnected<FusedActivationFunctionType::activation>(                                      \
      inputData, convertShapeToDims(inputShape), weightsData, convertShapeToDims(weightsShape), \
      biasData, convertShapeToDims(biasShape), outputData, convertShapeToDims(outputShape))
  ANDROID_NN_MACRO_DISPATCH(ANDROID_NN_FULLY_CONNECTED)
#undef ANDROID_NN_FULLY_CONNECTED
  return true;
}
References ANDROID_NN_FULLY_CONNECTED, and ANDROID_NN_MACRO_DISPATCH.