ONE - On-device Neural Engine: compiler/nnc/unittests/acl_backend/MIRToDOM.cpp File Reference
MIRToDOM.cpp File Reference
#include <functional>
#include <vector>
#include "ArtifactModel.h"
#include "AclCppOpGenerator.h"
#include "mir/Graph.h"
#include "mir/ops/CappedReluOp.h"
#include "mir/ops/ConcatOp.h"
#include "mir/ops/ConstantOp.h"
#include "mir/ops/Conv2DOp.h"
#include "mir/ops/Deconv2DOp.h"
#include "mir/ops/DepthwiseConv2DOp.h"
#include "mir/ops/EluOp.h"
#include "mir/ops/FullyConnectedOp.h"
#include "mir/ops/InputOp.h"
#include "mir/ops/MaxPool2DOp.h"
#include "mir/ops/OutputOp.h"
#include "mir/ops/PadOp.h"
#include "mir/ops/ReduceMeanOp.h"
#include "mir/ops/ReluOp.h"
#include "mir/ops/ReshapeOp.h"
#include "mir/ops/SigmoidOp.h"
#include "mir/ops/SoftmaxOp.h"
#include "mir/ops/TanhOp.h"
#include "mir/ops/TransposeOp.h"
#include "gtest/gtest.h"
Functions
TEST (acl_backend_mir_to_dom, constant)
TEST (acl_backend_mir_to_dom, concat)
TEST (acl_backend_mir_to_dom, DISABLED_add)
TEST (acl_backend_mir_to_dom, DISABLED_mul)
TEST (acl_backend_mir_to_dom, DISABLED_max)
TEST (acl_backend_mir_to_dom, DISABLED_conv_transposed2d)
TEST (acl_backend_mir_to_dom, conv2d)
TEST (acl_backend_mir_to_dom, depthwise_conv)
TEST (acl_backend_mir_to_dom, fully_connected)
TEST (acl_backend_mir_to_dom, maxpool)
TEST (acl_backend_mir_to_dom, DISABLED_avgpool)
TEST (acl_backend_mir_to_dom, relu)
TEST (acl_backend_mir_to_dom, capped_relu)
TEST (acl_backend_mir_to_dom, sigmoid)
TEST (acl_backend_mir_to_dom, DISABLED_elu)
TEST (acl_backend_mir_to_dom, tanh)
TEST (acl_backend_mir_to_dom, DISABLED_reduce_mean)
TEST (acl_backend_mir_to_dom, softmax)
TEST (acl_backend_mir_to_dom, reshape)
TEST (acl_backend_mir_to_dom, DISABLED_pad)
TEST (acl_backend_mir_to_dom, transpose)
Function Documentation
TEST() [1/21]
TEST (acl_backend_mir_to_dom , capped_relu)
Definition at line 426 of file MIRToDOM.cpp.
{
  float cap = 6;
  OpConstructor op_generator = [cap](Graph &g, const std::vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::CappedReluOp>(inputs[0], cap);
  };
  testActivationOp(op_generator);
}
TEST() [2/21]
TEST (acl_backend_mir_to_dom , concat)
Definition at line 241 of file MIRToDOM.cpp.
{
  Graph g;
  OpConstructor op_generator = [](Graph &g, const vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::ConcatOp>(inputs, 3);
  };
  vector<Shape> input_shapes{{2, 3, 5, 1}, {2, 3, 5, 3}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [3/21]
TEST (acl_backend_mir_to_dom , constant)
Definition at line 220 of file MIRToDOM.cpp.
{
  Shape shape{3, 4};
  TensorVariant constant_data = createTensorVariant(shape);
  Graph g;
  OpConstructor op_generator = [&constant_data](Graph &g,
                                                const vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::ConstantOp>(constant_data);
  };
  fillGraph(g, op_generator, {});
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [4/21]
TEST (acl_backend_mir_to_dom , conv2d)
Definition at line 282 of file MIRToDOM.cpp.
{
  const int32_t channels = 3;
  mir::Shape kernel_shape{1, 3, 3, channels}; // output Channels, Height, Width, input Channels
  mir::TensorVariant kernel_tensor = createTensorVariant(kernel_shape);
  Graph g;
  OpConstructor op_generator =
    [kernel_tensor](mir::Graph &g, const std::vector<mir::Operation::Output *> &inputs) {
      auto kernel = g.create<mir::ops::ConstantOp>(kernel_tensor)->getOutput(0);
      return g.create<mir::ops::Conv2DOp>(inputs[0], kernel, mir::Conv2DOpAttributes());
    };
  vector<Shape> input_shapes{{1, 10, 10, channels}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [5/21]
TEST (acl_backend_mir_to_dom , depthwise_conv)
Definition at line 307 of file MIRToDOM.cpp.
{
  const int32_t channels = 3;
  mir::Shape kernel_shape{3, 3, channels, 1}; // Height, Width, Channels, Channel multiplier
  mir::TensorVariant kernel_tensor = createTensorVariant(kernel_shape);
  Graph g;
  OpConstructor op_generator =
    [kernel_tensor](mir::Graph &g, const std::vector<mir::Operation::Output *> &inputs) {
      Conv2DOpAttributes attributes;
      auto kernel = g.create<mir::ops::ConstantOp>(kernel_tensor)->getOutput(0);
      return g.create<mir::ops::DepthwiseConv2DOp>(inputs[0], kernel, attributes);
    };
  vector<Shape> input_shapes{{1, 10, 10, channels}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [6/21]
TEST (acl_backend_mir_to_dom , DISABLED_add)
Definition at line 262 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [7/21]
TEST (acl_backend_mir_to_dom , DISABLED_avgpool)
Definition at line 390 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [8/21]
TEST (acl_backend_mir_to_dom , DISABLED_conv_transposed2d)
Definition at line 277 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [9/21]
TEST (acl_backend_mir_to_dom , DISABLED_elu)
Definition at line 445 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [10/21]
TEST (acl_backend_mir_to_dom , DISABLED_max)
Definition at line 272 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [11/21]
TEST (acl_backend_mir_to_dom , DISABLED_mul)
Definition at line 267 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [12/21]
TEST (acl_backend_mir_to_dom , DISABLED_pad)
Definition at line 513 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [13/21]
TEST (acl_backend_mir_to_dom , DISABLED_reduce_mean)
Definition at line 459 of file MIRToDOM.cpp.
{
  // TODO
}
TEST() [14/21]
TEST (acl_backend_mir_to_dom , fully_connected)
Definition at line 336 of file MIRToDOM.cpp.
{
  const int32_t in_size = 13;
  const int32_t out_size = 7;
  Shape input_shape_data{1, in_size};
  Shape weights_shape{in_size, out_size};
  TensorVariant weights_tensor = createTensorVariant(weights_shape);
  Graph g;
  OpConstructor opGenerator = [weights_tensor](Graph &g,
                                               const vector<Operation::Output *> &inputs) {
    auto weights = g.create<mir::ops::ConstantOp>(weights_tensor)->getOutput(0);
    return g.create<mir::ops::FullyConnectedOp>(inputs[0], weights);
  };
  fillGraph(g, opGenerator, {input_shape_data});
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [15/21]
TEST (acl_backend_mir_to_dom , maxpool)
Definition at line 364 of file MIRToDOM.cpp.
{
  mir::MaxPool2DOpAttributes attributes;
  attributes.window = {3, 3};
  Graph g;
  OpConstructor op_generator = [&attributes](mir::Graph &g,
                                             const std::vector<mir::Operation::Output *> &inputs) {
    return g.create<mir::ops::MaxPool2DOp>(inputs[0], attributes);
  };
  vector<Shape> input_shapes{{1, 10, 10, 3}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), m, and mir::MaxPool2DOpAttributes::window.
TEST() [16/21]
TEST (acl_backend_mir_to_dom , relu)
Definition at line 417 of file MIRToDOM.cpp.
{
  OpConstructor op_generator = [](Graph &g, const std::vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::ReluOp>(inputs[0]);
  };
  testActivationOp(op_generator);
}
TEST() [17/21]
TEST (acl_backend_mir_to_dom , reshape)
Definition at line 485 of file MIRToDOM.cpp.
{
  Graph g;
  const int32_t h = 10;
  const int32_t w = 10;
  const int32_t c = 3;
  Shape input_shape{1, h, w, c};
  Shape output_shape{1, h * w * c};
  OpConstructor op_generator = [output_shape](Graph &g, const vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::ReshapeOp>(inputs[0], output_shape);
  };
  fillGraph(g, op_generator, {input_shape});
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [18/21]
TEST (acl_backend_mir_to_dom , sigmoid)
Definition at line 436 of file MIRToDOM.cpp.
{
  OpConstructor op_generator = [](Graph &g, const std::vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::SigmoidOp>(inputs[0]);
  };
  testActivationOp(op_generator);
}
TEST() [19/21]
TEST (acl_backend_mir_to_dom , softmax)
Definition at line 464 of file MIRToDOM.cpp.
{
  Graph g;
  OpConstructor op_generator = [](Graph &g, const vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::SoftmaxOp>(inputs[0], 3);
  };
  vector<Shape> input_shapes{{1, 1, 1, 3}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
  stringstream code_out;
  ArtifactGeneratorCppCode code_gen(code_out);
}
References nnc::AclCppOpGenerator::generate(), and m.
TEST() [20/21]
TEST (acl_backend_mir_to_dom , tanh)
Definition at line 450 of file MIRToDOM.cpp.
{
  OpConstructor op_generator = [](Graph &g, const std::vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::TanhOp>(inputs[0]);
  };
  testActivationOp(op_generator);
}
TEST() [21/21]
TEST (acl_backend_mir_to_dom , transpose)
Definition at line 518 of file MIRToDOM.cpp.
{
  const int32_t channels = 2;
  TensorVariant w = createTensorVariant({channels});
  vector<size_t> perm{0, 3, 1, 2};
  Graph g;
  OpConstructor op_generator = [&perm](Graph &g, const vector<Operation::Output *> &inputs) {
    return g.create<mir::ops::TransposeOp>(inputs[0], perm);
  };
  vector<Shape> input_shapes{{1, 10, 10, channels}};
  fillGraph(g, op_generator, input_shapes);
  stringstream params_out;
  AclCppOpGenerator dom_gen(artifactName, params_out);
  const ArtifactModule &m = dom_gen.generate(&g);
  checkDomStructure(m, {}, {});
}
References nnc::AclCppOpGenerator::generate(), and m.