ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Matrix.h File Reference
Matrix.h File Reference
#include "Dims.h"
#include "Eigen/Core"
Typedefs
template<typename Scalar >
using VectorMap = typename std::conditional< std::is_const< Scalar >::value, Eigen::Map< const Eigen::Matrix< typename std::remove_const< Scalar >::type, Eigen::Dynamic, 1 > >, Eigen::Map< Eigen::Matrix< Scalar, Eigen::Dynamic, 1 > > >::type
template<typename Scalar >
using MatrixMap = typename std::conditional< std::is_const< Scalar >::value, Eigen::Map< const Eigen::Matrix< typename std::remove_const< Scalar >::type, Eigen::Dynamic, Eigen::Dynamic > >, Eigen::Map< Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic > > >::type
template<typename Scalar >
using ArrayMap = typename std::conditional< std::is_const< Scalar >::value, Eigen::Map< const Eigen::Array< typename std::remove_const< Scalar >::type, Eigen::Dynamic, Eigen::Dynamic > >, Eigen::Map< Eigen::Array< Scalar, Eigen::Dynamic, Eigen::Dynamic > > >::type
Functions
template<typename Scalar , int N>
VectorMap< Scalar > MapAsVector (Scalar *data, const Dims< N > &dims)
template<typename Scalar , int N>
MatrixMap< Scalar > MapAsMatrixWithFirstDimAsRows (Scalar *data, const Dims< N > &dims)
template<typename Scalar , int N>
MatrixMap< Scalar > MapAsMatrixWithLastDimAsCols (Scalar *data, const Dims< N > &dims)
template<typename Scalar , int N>
ArrayMap< Scalar > MapAsArrayWithFirstDimAsRows (Scalar *data, const Dims< N > &dims)
template<typename Scalar , int N>
MatrixMap< Scalar > MapAsMatrixWithGivenNumberOfRows (Scalar *data, const Dims< N > &dims, int rows)
Typedef Documentation
ArrayMap
template<typename Scalar > using ArrayMap = typename std::conditional< std::is_const<Scalar>::value, Eigen::Map<const Eigen::Array<typename std::remove_const<Scalar>::type, Eigen::Dynamic, Eigen::Dynamic> >, Eigen::Map<Eigen::Array<Scalar, Eigen::Dynamic, Eigen::Dynamic> >>::type
Definition at line 86 of file Matrix.h.
MatrixMap
template<typename Scalar > using MatrixMap = typename std::conditional< std::is_const<Scalar>::value, Eigen::Map<const Eigen::Matrix<typename std::remove_const<Scalar>::type, Eigen::Dynamic, Eigen::Dynamic> >, Eigen::Map<Eigen::Matrix<Scalar, Eigen::Dynamic, Eigen::Dynamic> >>::type
Definition at line 52 of file Matrix.h.
VectorMap
template<typename Scalar > using VectorMap = typename std::conditional< std::is_const<Scalar>::value, Eigen::Map<const Eigen::Matrix<typename std::remove_const<Scalar>::type, Eigen::Dynamic, 1> >, Eigen::Map<Eigen::Matrix<Scalar, Eigen::Dynamic, 1> >>::type
Definition at line 35 of file Matrix.h.
Function Documentation
MapAsArrayWithFirstDimAsRows()
template<typename Scalar , int N> ArrayMap< Scalar > MapAsArrayWithFirstDimAsRows (Scalar * data, const Dims< N > & dims)
Definition at line 94 of file Matrix.h.
{
  const int rows = dims.sizes[0];
  int cols = 1;
  for (int d = 1; d < N; d++)
  {
    cols *= dims.sizes[d];
  }
  return ArrayMap<Scalar>(data, rows, cols);
}
References Dims< N >::sizes.
MapAsMatrixWithFirstDimAsRows()
template<typename Scalar , int N> MatrixMap< Scalar > MapAsMatrixWithFirstDimAsRows (Scalar * data, const Dims< N > & dims)
Definition at line 60 of file Matrix.h.
{
  const int rows = dims.sizes[0];
  int cols = 1;
  for (int d = 1; d < N; d++)
  {
    cols *= dims.sizes[d];
  }
  return MatrixMap<Scalar>(data, rows, cols);
}
References Dims< N >::sizes.
Referenced by AveragePool(), Conv(), FullyConnected(), MaxPool(), and Softmax().
MapAsMatrixWithGivenNumberOfRows()
template<typename Scalar , int N> MatrixMap< Scalar > MapAsMatrixWithGivenNumberOfRows (Scalar * data, const Dims< N > & dims, int rows)
Definition at line 110 of file Matrix.h.
{
  int cols = 1;
  bool matched_rows = false;
  for (int d = 0; d < N; d++)
  {
    cols *= dims.sizes[d];
    if (cols == rows)
    {
      matched_rows = true;
      cols = 1;
    }
  }
  DCHECK(matched_rows);
  return MatrixMap<Scalar>(data, rows, cols);
}
References DCHECK, and Dims< N >::sizes.
Referenced by FullyConnected().
MapAsMatrixWithLastDimAsCols()
template<typename Scalar , int N> MatrixMap< Scalar > MapAsMatrixWithLastDimAsCols (Scalar * data, const Dims< N > & dims)
Definition at line 73 of file Matrix.h.
{
  const int cols = dims.sizes[N - 1];
  int rows = 1;
  for (int d = 0; d < N - 1; d++)
  {
    rows *= dims.sizes[d];
  }
  return MatrixMap<Scalar>(data, rows, cols);
}
References Dims< N >::sizes.
Referenced by Conv().
MapAsVector()
template<typename Scalar , int N> VectorMap< Scalar > MapAsVector (Scalar * data, const Dims< N > & dims)
Definition at line 40 of file Matrix.h.
{
  const int size = RequiredBufferSizeForDims(dims);
  return VectorMap<Scalar>(data, size, 1);
}
References RequiredBufferSizeForDims().