ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/NDArray.h File Reference
NDArray.h File Reference
#include "Dims.h"
#include "Macro.h"
Data Structures
struct NdArrayDesc< N >
Functions
int SubscriptToIndex (const NdArrayDesc< 4 > &desc, int i0, int i1, int i2, int i3)
template<int N>
void NdArrayDescsForElementwiseBroadcast (const Dims< N > &input0_dims, const Dims< N > &input1_dims, NdArrayDesc< N > *desc0_out, NdArrayDesc< N > *desc1_out)
int NodeOffset (int b, int h, int w, int height, int width)
Function Documentation
NdArrayDescsForElementwiseBroadcast()
template<int N> void NdArrayDescsForElementwiseBroadcast (const Dims< N > & input0_dims, const Dims< N > & input1_dims, NdArrayDesc< N > * desc0_out, NdArrayDesc< N > * desc1_out) inline
Definition at line 89 of file NDArray.h.
{
  DCHECK(desc0_out != nullptr);
  DCHECK(desc1_out != nullptr);
  // Copy dims to desc.
  for (int i = 0; i < N; ++i)
  {
    desc0_out->extents[i] = input0_dims.sizes[i];
    desc0_out->strides[i] = input0_dims.strides[i];
    desc1_out->extents[i] = input1_dims.sizes[i];
    desc1_out->strides[i] = input1_dims.strides[i];
  }
  // Walk over each dimension. If the extents are equal do nothing.
  // Otherwise, set the desc with extent 1 to have extent equal to the other and
  // stride 0.
  for (int i = 0; i < N; ++i)
  {
    const int extent0 = ArraySize(input0_dims, i);
    const int extent1 = ArraySize(input1_dims, i);
    if (extent0 != extent1)
    {
      if (extent0 == 1)
      {
        desc0_out->strides[i] = 0;
        desc0_out->extents[i] = extent1;
      }
      else
      {
        DCHECK_EQ(extent1, 1);
        desc1_out->strides[i] = 0;
        desc1_out->extents[i] = extent0;
      }
    }
  }
}
References ArraySize(), DCHECK, DCHECK_EQ, NdArrayDesc< N >::extents, Dims< N >::sizes, Dims< N >::strides, and NdArrayDesc< N >::strides.
Referenced by BroadcastAdd(), BroadcastDiv(), BroadcastMul(), tflite::reference_ops::BroadcastPow4DSlow(), tflite::reference_ops::BroadcastSelect4DSlow(), and BroadcastSub().
NodeOffset()
int NodeOffset (int b, int h, int w, int height, int width) inline
Definition at line 128 of file NDArray.h.
{
  return (b * height + h) * width + w;
}
SubscriptToIndex()
int SubscriptToIndex (const NdArrayDesc< 4 > & desc, int i0, int i1, int i2, int i3) inline
Definition at line 54 of file NDArray.h.
{
  DCHECK(i0 >= 0 && i0 < desc.extents[0]);
  DCHECK(i1 >= 0 && i1 < desc.extents[1]);
  DCHECK(i2 >= 0 && i2 < desc.extents[2]);
  DCHECK(i3 >= 0 && i3 < desc.extents[3]);
  return i0 * desc.strides[0] + i1 * desc.strides[1] + i2 * desc.strides[2] + i3 * desc.strides[3];
}
References DCHECK, NdArrayDesc< N >::extents, and NdArrayDesc< N >::strides.
Referenced by luci_interpreter::kernels::BinaryOpBroadcastSlow(), BroadcastAdd(), BroadcastDiv(), BroadcastMul(), tflite::reference_ops::BroadcastPow4DSlow(), tflite::reference_ops::BroadcastSelect4DSlow(), and BroadcastSub().