ONE - On-device Neural Engine: runtime/libs/nnapi/include/NeuralNetworksShim.h File Reference
NeuralNetworksShim.h File Reference
#include "NeuralNetworksTypes.h"
#include "NeuralNetworksLoadHelpers.h"
Functions
int ANeuralNetworksMemory_createFromFd (size_t size, int protect, int fd, size_t offset, ANeuralNetworksMemory **memory)
void ANeuralNetworksMemory_free (ANeuralNetworksMemory *memory)
int ANeuralNetworksModel_create (ANeuralNetworksModel **model)
void ANeuralNetworksModel_free (ANeuralNetworksModel *model)
int ANeuralNetworksModel_finish (ANeuralNetworksModel *model)
int ANeuralNetworksModel_addOperand (ANeuralNetworksModel *model, const ANeuralNetworksOperandType *type)
int ANeuralNetworksModel_setOperandValue (ANeuralNetworksModel *model, int32_t index, const void *buffer, size_t length)
int ANeuralNetworksModel_setOperandSymmPerChannelQuantParams (ANeuralNetworksModel *model, int32_t index, const ANeuralNetworksSymmPerChannelQuantParams *channelQuant)
int ANeuralNetworksModel_setOperandValueFromMemory (ANeuralNetworksModel *model, int32_t index, const ANeuralNetworksMemory *memory, size_t offset, size_t length)
int ANeuralNetworksModel_addOperation (ANeuralNetworksModel *model, ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs)
int ANeuralNetworksModel_identifyInputsAndOutputs (ANeuralNetworksModel *model, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs)
int ANeuralNetworksModel_relaxComputationFloat32toFloat16 (ANeuralNetworksModel *model, bool allow)
int ANeuralNetworksCompilation_create (ANeuralNetworksModel *model, ANeuralNetworksCompilation **compilation)
void ANeuralNetworksCompilation_free (ANeuralNetworksCompilation *compilation)
int ANeuralNetworksCompilation_setPreference (ANeuralNetworksCompilation *compilation, int32_t preference)
int ANeuralNetworksCompilation_finish (ANeuralNetworksCompilation *compilation)
int ANeuralNetworksExecution_create (ANeuralNetworksCompilation *compilation, ANeuralNetworksExecution **execution)
void ANeuralNetworksExecution_free (ANeuralNetworksExecution *execution)
int ANeuralNetworksExecution_setInput (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const void *buffer, size_t length)
int ANeuralNetworksExecution_setInputFromMemory (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const ANeuralNetworksMemory *memory, size_t offset, size_t length)
int ANeuralNetworksExecution_setOutput (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, void *buffer, size_t length)
int ANeuralNetworksExecution_setOutputFromMemory (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const ANeuralNetworksMemory *memory, size_t offset, size_t length)
int ANeuralNetworksExecution_startCompute (ANeuralNetworksExecution *execution, ANeuralNetworksEvent **event)
int ANeuralNetworksEvent_wait (ANeuralNetworksEvent *event)
void ANeuralNetworksEvent_free (ANeuralNetworksEvent *event)
int ANeuralNetworks_getDeviceCount (uint32_t *numDevices)
int ANeuralNetworks_getDevice (uint32_t devIndex, ANeuralNetworksDevice **device)
int ANeuralNetworksDevice_getName (const ANeuralNetworksDevice *device, const char **name)
int ANeuralNetworksDevice_getVersion (const ANeuralNetworksDevice *device, const char **version)
int ANeuralNetworksDevice_getFeatureLevel (const ANeuralNetworksDevice *device, int64_t *featureLevel)
int ANeuralNetworksModel_getSupportedOperationsForDevices (const ANeuralNetworksModel *model, const ANeuralNetworksDevice *const *devices, uint32_t numDevices, bool *supportedOps)
int ANeuralNetworksCompilation_createForDevices (ANeuralNetworksModel *model, const ANeuralNetworksDevice *const *devices, uint32_t numDevices, ANeuralNetworksCompilation **compilation)
int ANeuralNetworksCompilation_setCaching (ANeuralNetworksCompilation *compilation, const char *cacheDir, const uint8_t *token)
int ANeuralNetworksExecution_compute (ANeuralNetworksExecution *execution)
int ANeuralNetworksExecution_getOutputOperandRank (ANeuralNetworksExecution *execution, int32_t index, uint32_t *rank)
int ANeuralNetworksExecution_getOutputOperandDimensions (ANeuralNetworksExecution *execution, int32_t index, uint32_t *dimensions)
int ANeuralNetworksBurst_create (ANeuralNetworksCompilation *compilation, ANeuralNetworksBurst **burst)
void ANeuralNetworksBurst_free (ANeuralNetworksBurst *burst)
int ANeuralNetworksExecution_burstCompute (ANeuralNetworksExecution *execution, ANeuralNetworksBurst *burst)
int ANeuralNetworksMemory_createFromAHardwareBuffer (const AHardwareBuffer *ahwb, ANeuralNetworksMemory **memory)
int ANeuralNetworksExecution_setMeasureTiming (ANeuralNetworksExecution *execution, bool measure)
int ANeuralNetworksExecution_getDuration (const ANeuralNetworksExecution *execution, int32_t durationCode, uint64_t *duration)
int ANeuralNetworksDevice_getExtensionSupport (const ANeuralNetworksDevice *device, const char *extensionName, bool *isExtensionSupported)
int ANeuralNetworksModel_getExtensionOperandType (ANeuralNetworksModel *model, const char *extensionName, uint16_t operandCodeWithinExtension, int32_t *type)
int ANeuralNetworksModel_getExtensionOperationType (ANeuralNetworksModel *model, const char *extensionName, uint16_t operationCodeWithinExtension, ANeuralNetworksOperationType *type)
int ANeuralNetworksModel_setOperandExtensionData (ANeuralNetworksModel *model, int32_t index, const void *data, size_t length)
Function Documentation
ANeuralNetworksDevice_getExtensionSupport()
int ANeuralNetworksDevice_getExtensionSupport (const ANeuralNetworksDevice * device, const char * extensionName, bool * isExtensionSupported) inline
Queries whether an extension is supported by the driver implementation of the specified device.
Parameters
device The representation of the specified device.
extension The extension name.
isExtensionSupported The boolean value indicating whether the extension is supported.
Returns
ANEURALNETWORKS_NO_ERROR if successful.
Available since API level 29.
Definition at line 1147 of file NeuralNetworksShim.h.
{
  LOAD_FUNCTION(ANeuralNetworksDevice_getExtensionSupport);
  EXECUTE_FUNCTION_RETURN(device, extensionName, isExtensionSupported);
}
References ANeuralNetworksDevice_getExtensionSupport(), EXECUTE_FUNCTION_RETURN, and LOAD_FUNCTION.
Referenced by ANeuralNetworksDevice_getExtensionSupport().
ANeuralNetworksModel_getExtensionOperandType()
int ANeuralNetworksModel_getExtensionOperandType (ANeuralNetworksModel * model, const char * extensionName, uint16_t operandCodeWithinExtension, int32_t * type) inline
Creates an operand type from an extension name and an extension operand code.
See ANeuralNetworksModel for information on multithreaded usage.
Available since API level 29.
Parameters
model The model to contain the operand.
extensionName The extension name.
operandCodeWithinExtension The extension operand code.
type The operand type.
Returns
ANEURALNETWORKS_NO_ERROR if successful.
Definition at line 1169 of file NeuralNetworksShim.h.
{
  LOAD_FUNCTION(ANeuralNetworksModel_getExtensionOperandType);
  EXECUTE_FUNCTION_RETURN(model, extensionName, operandCodeWithinExtension, type);
}
References ANeuralNetworksModel_getExtensionOperandType(), EXECUTE_FUNCTION_RETURN, and LOAD_FUNCTION.
Referenced by ANeuralNetworksModel_getExtensionOperandType().
ANeuralNetworksModel_getExtensionOperationType()
int ANeuralNetworksModel_getExtensionOperationType (ANeuralNetworksModel * model, const char * extensionName, uint16_t operationCodeWithinExtension, ANeuralNetworksOperationType * type) inline
Creates an operation type from an extension name and an extension operation code.
See ANeuralNetworksModel for information on multithreaded usage.
Available since API level 29.
Parameters
model The model to contain the operation.
extensionName The extension name.
operationCodeWithinExtension The extension operation code.
type The operation type.
Returns
ANEURALNETWORKS_NO_ERROR if successful.
Definition at line 1193 of file NeuralNetworksShim.h.
{
  LOAD_FUNCTION(ANeuralNetworksModel_getExtensionOperationType);
  EXECUTE_FUNCTION_RETURN(model, extensionName, operationCodeWithinExtension, type);
}
References ANeuralNetworksModel_getExtensionOperationType(), EXECUTE_FUNCTION_RETURN, and LOAD_FUNCTION.
Referenced by ANeuralNetworksModel_getExtensionOperationType().
ANeuralNetworksModel_setOperandExtensionData()
int ANeuralNetworksModel_setOperandExtensionData (ANeuralNetworksModel * model, int32_t index, const void * data, size_t length) inline
Sets extension operand parameters.
Available since API level 29.
Parameters
model The model to be modified.
index The index of the model operand we're setting.
data A pointer to the extension operand data. The data does not have to outlive the call to this function.
length The size in bytes of the data value.
Returns
ANEURALNETWORKS_NO_ERROR if successful.
Definition at line 1215 of file NeuralNetworksShim.h.
{
  LOAD_FUNCTION(ANeuralNetworksModel_setOperandExtensionData);
  EXECUTE_FUNCTION_RETURN(model, index, data, length);
}
References ANeuralNetworksModel_setOperandExtensionData(), EXECUTE_FUNCTION_RETURN, and LOAD_FUNCTION.
Referenced by ANeuralNetworksModel_setOperandExtensionData().