ONE - On-device Neural Engine: compiler/tflchef/core/src/OpUtils.h File Reference
OpUtils.h File Reference
This header declares various op_utils functions.
#include <tflchef.pb.h>
Functions
void check_custom_op_value (const tflchef::Operation &operation, const std::string &op_type)
Detailed Description
This header declares various op_utils functions.
Definition in file OpUtils.h.
Function Documentation
check_custom_op_value()
void check_custom_op_value (const tflchef::Operation & operation, const std::string & op_type)
Definition at line 21 of file OpUtils.cpp.
{
  if (operation.type() == "Custom")
  {
    assert(operation.custom_code() == op_type);
  }
}
Referenced by AddV2Chef::custom_value(), AllChef::custom_value(), BatchMatMulV2Chef::custom_value(), BroadcastToChef::custom_value(), ErfChef::custom_value(), MatMulChef::custom_value(), MatrixBandPartChef::custom_value(), and MaxPoolWithArgmaxChef::custom_value().