ONE - On-device Neural Engine: compiler/enco/frontend/caffe/src/PaddingUtils.cpp File Reference
PaddingUtils.cpp File Reference
#include "PaddingUtils.h"
#include <cassert>
Functions
RawPaddingBuilder build_raw_padding (void)
SpatialPaddingBuilder build_spatial_padding (uint32_t spatial_rank)
Function Documentation
build_raw_padding()
RawPaddingBuilder build_raw_padding (void)
RawPaddingBuilder is introduced to support the following code pattern:
auto raw_padding = build_raw_padding().with(conv_param); ...
Definition at line 86 of file PaddingUtils.cpp.
{ return RawPaddingBuilder{}; }
Referenced by PoolingSpec::horizontal_pad(), ConvolutionSpec::pad(), and PoolingSpec::vertical_pad().
build_spatial_padding()
SpatialPaddingBuilder build_spatial_padding (uint32_t spatial_rank)
SpatialPaddingBuilder is introduced to support the following code pattern:
auto raw_padding = build_raw_padding().with(conv_param); auto spatial_padding = build_spatial_padding(4).with(raw_padding);
Definition at line 128 of file PaddingUtils.cpp.
{
  return SpatialPaddingBuilder{spatial_rank};
}
References PaddingBase< Derived >::resize(), and PaddingBase< Derived >::value().
Referenced by PoolingSpec::horizontal_pad(), ConvolutionSpec::pad(), and PoolingSpec::vertical_pad().