ONE - On-device Neural Engine: compiler/luci/tester/src/ReadModule.h File Reference
ReadModule.h File Reference
#include <luci/Importer.h>
#include <foder/FileLoader.h>
#include <memory>
#include <string>
Functions
std::unique_ptr< luci::Module > ReadModule (std::string &input_path)
Function Documentation
ReadModule()
std::unique_ptr< luci::Module > ReadModule (std::string & input_path)
Definition at line 29 of file ReadModule.cpp.
{
  // Load model from the file
  foder::FileLoader file_loader{input_path};
  std::vector<char> model_data = file_loader.load();
  const circle::Model *circle_model = circle::GetModel(model_data.data());
  if (circle_model == nullptr)
  {
    std::cerr << "ERROR: Failed to load circle '" << input_path << "'" << std::endl;
    return nullptr;
  }
  luci::Importer importer;
  auto module = importer.importModule(circle_model);
  assert(module->size() > 0);
  for (size_t g = 0; g < module->size(); ++g)
  {
    auto graph = module->graph(g);
    if (graph == nullptr)
      return nullptr;
    {
      logo::Phase phase;
      phase.emplace_back(std::make_unique<luci::CircleShapeInferencePass>());
      phase.emplace_back(std::make_unique<luci::CircleTypeInferencePass>());
      logo::PhaseRunner<logo::PhaseStrategy::Saturate> phase_runner{graph};
      phase_runner.run(phase);
    }
    if (!luci::validate(graph))
      return nullptr;
  }
  return module;
}
References luci::Importer::importModule(), foder::FileLoader::load(), and luci::validate().
Referenced by entry().