ONE - On-device Neural Engine: compiler/safemain/SafeMain.cpp File Reference
SafeMain.cpp File Reference
#include <iostream>
#include <stdexcept>
Functions
int entry (int argc, char **argv)
Dump IR for given arguments.
int main (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 155 of file Driver.cpp.
{
  // Usage:
  //  [Command] --frontend [Frontend .so path] --frontend-arg ...
  std::unique_ptr<FrontendZone> frontend_zone;
  // Simple argument parser (based on map)
  std::map<std::string, std::function<void(const std::string &arg)>> argparse;
  argparse["--frontend"] = [&](const std::string &path) {
    frontend_zone = std::make_unique<FrontendZone>(path);
  };
  argparse["--frontend-arg"] = [&](const std::string &arg) { frontend_zone->append(arg); };
  if (argc < 2)
  {
    std::cerr << "Usage:" << std::endl;
    std::cerr << "[Command] --frontend [.so path]" << std::endl;
    std::cerr << "          --frontend-arg [argument] ..." << std::endl;
    return 255;
  }
  for (int n = 1; n < argc; n += 2)
  {
    const std::string tag{argv[n]};
    const std::string arg{argv[n + 1]};
    auto it = argparse.find(tag);
    if (it == argparse.end())
    {
      std::cerr << "Option '" << tag << "' is not supported" << std::endl;
      return 255;
    }
    it->second(arg);
  }
  assert(frontend_zone != nullptr);
  auto frontend = frontend_zone->factory()->make(frontend_zone->args());
  auto bundle = frontend->load();
  // dump
  dump(bundle.module());
  // todo : dump data
  return 0;
}
References fme_detect::EqualizePatternFinder::Context::_allow_dup_op, training_configure_tool::TrainData::acceptable_diff, onert_micro::ACCURACY, onert_micro::ADAM, add_switch(), arser::Helper::add_verbose(), arser::Helper::add_version(), luci::apply(), onert_micro::OMTrainingContext::batch_size, onert_micro::OMTrainingContext::beta, onert_micro::OMTrainingContext::beta_squares, luci::change_outputs(), circle_planner::ExecutionPlanner::change_planning_mode(), training_configure_tool::TrainData::circle_model_path, CLASSIFICATION_TASK, circle_planner::CMSISNN, cirops::DumpOption::codes, circle_planner::COMMON, circlechef::cook(), tflchef::cook(), circle_planner::ExecutionPlanner::create_json_allocation_file(), training_configure_tool::createResultFile(), onert_micro::CROSS_ENTROPY, onert_micro::CROSS_ENTROPY_METRICS, csv_tokenize(), luci::UserSettings::DisableValidation, minmax_embedder_test::H5Writer::dump(), dump(), luci::dynamic_batch_to_single_batch(), minmax_embedder::Embedder::embed(), entry(), entry_stream(), onert_micro::OMTrainingContext::epochs, onert_micro::OMTrainingContext::epsilon, fme_apply::FMEqualizer::equalize(), circle_eval_diff::CircleEvalDiff::evalDiff(), onert_micro::OMTrainingInterpreter::evaluateMetric(), partee::export_part_conn_ini(), partee::export_part_conn_json(), opselector::exportModule(), fme_detect::EqualizePatternFinder::find(), training_configure_tool::findBestSparseBackpropagationTensorsRanks(), training_configure_tool::findBestTrainableOpIndexes(), circlechef::generate_recipe(), tflchef::generate_recipe(), luci::GraphBuilderRegistry::get(), SolverOutput::get(), partee::get_filename_ext(), onert_micro::OMTrainingInterpreter::getInputSizeAt(), onert_micro::OMTrainingInterpreter::getOutputSizeAt(), mpqsolver::core::Quantizer::Context::granularity, handle_segfault(), handleAutoAlgorithm(), opselector::ID, luci::ImporterEx::importModule(), onert_micro::OMTrainingInterpreter::importTrainModel(), INFO, circle_eval_diff::CircleEvalDiff::init(), record_minmax::RecordMinMax::initialize(), training_configure_tool::TrainData::input_input_test_data_path, training_configure_tool::TrainData::input_input_train_data_path, loco::input_nodes(), training_configure_tool::TrainData::input_target_test_data_path, training_configure_tool::TrainData::input_target_train_data_path, mpqsolver::core::Quantizer::Context::input_type, luci::CircleExporter::invoke(), onert_micro::OMTrainingContext::learning_rate, circle_planner::LINUX, foder::FileLoader::load(), prunner::PModelsRunner::load_config(), prunner::PModelsRunner::load_inputs(), onert_micro::OMTrainingInterpreter::loadCheckpoint(), LOGGER, onert_micro::OMTrainingContext::loss, circle_planner::LUCI_INTERPRETER, onert_micro::MAE_METRICS, circle_planner::ExecutionPlanner::make_execution_plan(), partee::make_path(), circle_planner::MCU, training_configure_tool::TrainData::memory_above_restriction, training_configure_tool::TrainData::metrics_to_check_best_config, circledump::ModelEx::model, tfldump::ModelEx::model, MODEL_TYPE, onert_micro::MSE_METRICS, loco::must_cast(), luci::UserSettings::MuteWarnings, minmax_embedder_test::ModelSpec::n_inputs, opselector::NAME, luci::CircleNode::name(), cirops::DumpOption::names, onert_micro::OMTrainingContext::num_of_train_layers, training_configure_tool::TrainData::num_test_data_samples, training_configure_tool::TrainData::num_train_data_samples, circle_planner::ONERT_MICRO, luci::CircleOptimizer::optimize(), onert_micro::OMTrainingContext::optimizer, luci::CircleOptimizer::options(), luci::CircleQuantizer::options(), mpqsolver::core::Quantizer::Context::output_model_dtype, loco::output_nodes(), training_configure_tool::TrainData::output_tool_file_path, mpqsolver::core::Quantizer::Context::output_type, circle_resizer::parse_shapes(), print_exclusive_options(), print_version(), record_minmax::RecordMinMax::profileData(), record_minmax::RecordMinMax::profileDataInParallel(), luci::UserSettings::ProfilingDataGen, mpqsolver::pattern::Q8LayerNormWithQ16Variance, mpqsolver::pattern::Q8SoftmaxWithQ16SubExp, luci::CircleQuantizer::quantize(), circledump::ModelEx::rawdata, tfldump::ModelEx::rawdata, fme_apply::read(), partee::read(), read_layer_params(), read_layer_params_set(), readFile(), circle_resizer::ModelEditor::resize_inputs(), cirops::DumpOperators::run(), prunner::PModelsRunner::run(), mpqsolver::core::Quantizer::Context::save_min_max, prunner::PModelsRunner::save_outputs(), onert_micro::OMTrainingInterpreter::saveCheckpoint(), onert_micro::OMTrainingInterpreter::saveModel(), record_minmax::RecordMinMax::saveModel(), record_minmax::RecordMinMax::setDataSetFormat(), onert_micro::OMTrainingInterpreter::setInput(), record_minmax::RecordMinMax::setInputDataPath(), onert_micro::OMTrainingInterpreter::setTarget(), luci::UserSettings::settings(), luci::size(), luci_interpreter::source_without_constant_copying(), luci::CircleOptimizer::sparsify(), circle_planner::SPLIT, mpqsolver::core::Quantizer::Context::TF_style_maxpool, training_configure_tool::TrainConfigFileData::trainable_op_indexes_with_ranks, onert_micro::OMTrainingInterpreter::trainSingleStep(), luci::validate(), luci::validate_shape(), value_grpname(), training_configure_tool::TrainData::wof_file_path, fme_detect::write(), q_implant::QImplant::write(), circlechef::write_recipe(), and tflchef::write_recipe().
Referenced by souschef::Registry< T >::add(), ModelBuilder::addOperation(), onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::allocate(), nnkit::BackendPlugin::BackendPlugin(), record_minmax::DirectoryIterator::DirectoryIterator(), circle_eval_diff::DirectoryLoader::DirectoryLoader(), entry(), entry(), entry(), cli::FunctionCommand::FunctionCommand(), onert::compiler::HEScheduler::HEScheduler(), main(), nnkit::make_backend_plugin(), record_minmax::DirectoryIterator::next(), circledump::SourceTablePrinter::print(), and circledump::OpTablePrinter::print().
main()
int main (int argc, char ** argv)
Definition at line 37 of file SafeMain.cpp.
{
  // NOTE main does not catch internal exceptions for debug build to make it easy to
  //      check the stacktrace with a debugger
  return entry(argc, argv);
}
References entry().