ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Softmax.float.h File Reference
Softmax.float.h File Reference
#include "Shape.h"
#include <cstdint>
Functions
bool softmaxFloat32 (const float *inputData, const Shape &inputShape, const float beta, float *outputData, const Shape &outputShape)
Function Documentation
softmaxFloat32()
bool softmaxFloat32 (const float * inputData, const Shape & inputShape, const float beta, float * outputData, const Shape & outputShape)
Definition at line 46 of file Softmax.float.cpp.
{
  Dims<4> dim;
  if (getNumberOfDimensions(inputShape) == 2)
  {
    uint32_t batch_size = getSizeOfDimension(inputShape, 0);
    uint32_t input_size = getNumberOfElements(inputShape) / batch_size;
    Shape shapeIn4D;
    shapeIn4D.dimensions = {batch_size, 1, 1, input_size};
    dim = convertShapeToDims(shapeIn4D);
  }
  else if (getNumberOfDimensions(inputShape) == 4)
  {
    dim = convertShapeToDims(inputShape);
  }
  else
  {
    LOG(ERROR) << "only 2D and 4D tensors supported";
    return false;
  }
  Softmax(inputData, dim, beta, outputData, dim);
  return true;
}
References convertShapeToDims(), Shape::dimensions, getNumberOfDimensions(), getNumberOfElements(), getSizeOfDimension(), LOG, and Softmax().