ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Spatial.h File Reference
Spatial.h File Reference
#include <cstdint>
Functions
uint32_t computeOutSize (uint32_t imageSize, uint32_t filterSize, uint32_t stride, uint32_t paddingHead, uint32_t paddingTail)
Function Documentation
computeOutSize()
uint32_t computeOutSize (uint32_t imageSize, uint32_t filterSize, uint32_t stride, uint32_t paddingHead, uint32_t paddingTail) inline
Definition at line 23 of file Spatial.h.
{
  return (imageSize - filterSize + stride + paddingHead + paddingTail) / stride;
}
Referenced by convPrepare(), depthwiseConvPrepare(), and genericPoolingPrepare().