ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Sub.float.cpp File Reference
Sub.float.cpp File Reference
#include "Sub.float.h"
#include "internal/Array.h"
#include "internal/NDArray.h"
#include "internal/Matrix.h"
#include "internal/Fused.h"
#include "internal/ActivationUtils.h"
Macros
#define ANDROID_NN_NORMAL_SUB(activation)
#define ANDROID_NN_BROADCAST_SUB(activation)
Functions
template<FusedActivationFunctionType Ac>
void Sub (const float *input1_data, const Dims< 4 > &input1_dims, const float *input2_data, const Dims< 4 > &input2_dims, float *output_data, const Dims< 4 > &output_dims)
template<FusedActivationFunctionType Ac>
void BroadcastSub (const float *input1_data, const Dims< 4 > &input1_dims, const float *input2_data, const Dims< 4 > &input2_dims, float *output_data, const Dims< 4 > &output_dims)
bool subFloat32 (const float *in1, const Shape &shape1, const float *in2, const Shape &shape2, int32_t activation, float *out, const Shape &shapeOut)
Macro Definition Documentation
ANDROID_NN_BROADCAST_SUB
#define ANDROID_NN_BROADCAST_SUB (activation)
Value:
  BroadcastSub<FusedActivationFunctionType::activation>(                     \
      in1, convertShapeToDims(shape1), in2, convertShapeToDims(shape2), out, \
      convertShapeToDims(shapeOut))
ANDROID_NN_NORMAL_SUB
#define ANDROID_NN_NORMAL_SUB (activation)
Value:
  Sub<FusedActivationFunctionType::activation>(in1, convertShapeToDims(shape1),                \
                                                              in2, convertShapeToDims(shape2), \
                                                              out, convertShapeToDims(shapeOut))
Function Documentation
BroadcastSub()
template<FusedActivationFunctionType Ac> void BroadcastSub (const float * input1_data, const Dims< 4 > & input1_dims, const float * input2_data, const Dims< 4 > & input2_dims, float * output_data, const Dims< 4 > & output_dims)
Definition at line 60 of file Sub.float.cpp.
{
  NdArrayDesc<4> desc1;
  NdArrayDesc<4> desc2;
  NdArrayDescsForElementwiseBroadcast(input1_dims, input2_dims, &desc1, &desc2);
  // In Tensorflow, the dimensions are canonically named (batch_number, row,
  // col, channel), with extents (batches, height, width, depth), with the
  // trailing dimension changing most rapidly (channels has the smallest stride,
  // typically 1 element).
  //
  // In generated C code, we store arrays with the dimensions reversed. The
  // first dimension has smallest stride.
  //
  // We name our variables by their Tensorflow convention, but generate C code
  // nesting loops such that the innermost loop has the smallest stride for the
  // best cache behavior.
  for (int b = 0; b < ArraySize(output_dims, 3); ++b)
  {
    for (int y = 0; y < ArraySize(output_dims, 2); ++y)
    {
      for (int x = 0; x < ArraySize(output_dims, 1); ++x)
      {
        for (int c = 0; c < ArraySize(output_dims, 0); ++c)
        {
          output_data[Offset(output_dims, c, x, y, b)] =
              ActivationFunction<Ac>(input1_data[SubscriptToIndex(desc1, c, x, y, b)] -
                                     input2_data[SubscriptToIndex(desc2, c, x, y, b)]);
        }
      }
    }
  }
}
References ArraySize(), NdArrayDescsForElementwiseBroadcast(), Offset(), and SubscriptToIndex().
Sub()
template<FusedActivationFunctionType Ac> void Sub (const float * input1_data, const Dims< 4 > & input1_dims, const float * input2_data, const Dims< 4 > & input2_dims, float * output_data, const Dims< 4 > & output_dims)
Definition at line 28 of file Sub.float.cpp.
{
  MatchingArraySize(input1_dims, 3, input2_dims, 3, output_dims, 3);
  MatchingArraySize(input1_dims, 2, input2_dims, 2, output_dims, 2);
  MatchingArraySize(input1_dims, 1, input2_dims, 1, output_dims, 1);
  MatchingArraySize(input1_dims, 0, input2_dims, 0, output_dims, 0);
  DCHECK(IsPackedWithoutStrides(input1_dims));
  DCHECK(IsPackedWithoutStrides(input2_dims));
  DCHECK(IsPackedWithoutStrides(output_dims));
  int i = 0;
  const int size = input1_dims.sizes[3] * input1_dims.strides[3];
  for (; i < size; i++)
  {
    auto x = input1_data[i] - input2_data[i];
    output_data[i] = ActivationFunction<Ac>(x);
  }
}
References DCHECK, IsPackedWithoutStrides(), MatchingArraySize(), Dims< N >::sizes, and Dims< N >::strides.
Referenced by mir_onnx::registerSupportedOps().
subFloat32()
bool subFloat32 (const float * in1, const Shape & shape1, const float * in2, const Shape & shape2, int32_t activation, float * out, const Shape & shapeOut)
Definition at line 95 of file Sub.float.cpp.
{
  bool needBroadcast = !SameShape(shape1, shape2);
#define ANDROID_NN_NORMAL_SUB(activation)                                                      \
  Sub<FusedActivationFunctionType::activation>(in1, convertShapeToDims(shape1),                \
                                                              in2, convertShapeToDims(shape2), \
                                                              out, convertShapeToDims(shapeOut))
#define ANDROID_NN_BROADCAST_SUB(activation)                                 \
  BroadcastSub<FusedActivationFunctionType::activation>(                     \
      in1, convertShapeToDims(shape1), in2, convertShapeToDims(shape2), out, \
      convertShapeToDims(shapeOut))
  if (needBroadcast)
  {
    ANDROID_NN_MACRO_DISPATCH(ANDROID_NN_BROADCAST_SUB)
  }
  else
  {
    ANDROID_NN_MACRO_DISPATCH(ANDROID_NN_NORMAL_SUB)
  }
#undef ANDROID_NN_NORMAL_SUB
#undef ANDROID_NN_BROADCAST_SUB
  return true;
}
References ANDROID_NN_BROADCAST_SUB, ANDROID_NN_MACRO_DISPATCH, ANDROID_NN_NORMAL_SUB, and SameShape().