ONE - On-device Neural Engine: compiler/embedded-import-value-test/src/TestDriver.cpp File Reference
TestDriver.cpp File Reference
#include <luci_interpreter/GraphBuilderRegistry.h>
#include <luci_interpreter/Interpreter.h>
#include <luci/Importer.h>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <vector>
#include <string>
#include <random>
Functions
int entry (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 119 of file TestDriver.cpp.
{
  // check arguments
  if (argc != 3 || std::string(argv[1]) != "--model")
  {
    std::cerr << "Usage: " << argv[0] << " --model <path/to/model>" << std::endl;
    return EXIT_FAILURE;
  }
  // open file with model
  const auto model_file = std::string(argv[2]);
  std::ifstream fs(model_file, std::ifstream::binary);
  if (fs.fail())
  {
    std::cerr << "Cannot open model file \"" << model_file << "\"." << std::endl;
    return EXIT_FAILURE;
  }
  // create constant circle model
  const std::vector<char> model_buffer((std::istreambuf_iterator<char>(fs)),
                                       std::istreambuf_iterator<char>());
  const auto circle_model = circle::GetModel(model_buffer.data());
  // create random model's inputs
  std::vector<std::vector<uint8_t>> inputs_data;
  {
    // model inputs
    auto model = luci::Importer(nullptr).importModule(circle_model);
    const auto inputs = loco::input_nodes(model->graph());
    // create random data for each input
    for (const auto *input : inputs)
    {
      const auto input_node = loco::must_cast<const luci::CircleInput *>(input);
      inputs_data.emplace_back(random_data_for(input_node));
    }
  }
  // interpret given module
  const auto interpret_module_and_compute_output =
    [&](const std::unique_ptr<luci::Module> &module) {
      // create interpreter
      luci_interpreter::Interpreter interpreter(module.get());
      // model's input and output nodes
      const auto input_nodes = loco::input_nodes(module->graph());
      const auto output_nodes = loco::output_nodes(module->graph());
      // set inputs
      for (uint32_t i = 0; i < input_nodes.size(); ++i)
      {
        const auto input_node = loco::must_cast<const luci::CircleInput *>(input_nodes[i]);
        const auto &data = inputs_data.at(i);
        interpreter.writeInputTensor(input_node, data.data(), data.size());
      }
      // do inference
      interpreter.interpret();
      // read outputs
      std::vector<std::vector<uint8_t>> outputs_data;
      for (const auto *node : output_nodes)
      {
        const auto output_node = loco::must_cast<const luci::CircleOutput *>(node);
        // allocate output buffer
        outputs_data.emplace_back(tensor_size_of(output_node));
        auto &data = outputs_data.back();
        interpreter.readOutputTensor(output_node, data.data(), data.size());
      }
      return outputs_data;
    };
  // import with copying, execute and save
  std::vector<std::vector<uint8_t>> outputs_data_1;
  {
    const auto default_source = &luci::GraphBuilderRegistry::get();
    const auto module = luci::Importer(default_source).importModule(circle_model);
    if (not module)
    {
      std::cerr << "Fail to import model with constant copying." << std::endl;
      return EXIT_FAILURE;
    }
    outputs_data_1 = interpret_module_and_compute_output(module);
  }
  // import without copying, execute and save
  std::vector<std::vector<uint8_t>> outputs_data_2;
  {
    const auto optimized_source = luci_interpreter::source_without_constant_copying();
    const auto module = luci::Importer(optimized_source.get()).importModule(circle_model);
    if (not module)
    {
      std::cerr << "Fail to import model without constant copying." << std::endl;
      return EXIT_FAILURE;
    }
    outputs_data_2 = interpret_module_and_compute_output(module);
  }
  // check all tensors are equal
  assert(outputs_data_1.size() == outputs_data_2.size());
  for (uint32_t n = 0; n < outputs_data_1.size(); ++n)
  {
    const auto &output_1 = outputs_data_1.at(n);
    const auto &output_2 = outputs_data_2.at(n);
    assert(output_1.size() == output_2.size());
    for (uint32_t o = 0; o < output_1.size(); ++o)
    {
      if (output_1[o] != output_2[o])
      {
        std::cerr << "Values mismatch in model's output number " << n << std::endl;
        return EXIT_FAILURE;
      }
    }
  }
  std::cout << "[TEST PASSED]" << std::endl;
  return EXIT_SUCCESS;
}
References luci::GraphBuilderRegistry::get(), luci::Importer::importModule(), loco::input_nodes(), loco::output_nodes(), and luci_interpreter::source_without_constant_copying().