ONE - On-device Neural Engine: onert-micro/training-configure-tool/TrainingConfigureTool.cpp File Reference
TrainingConfigureTool.cpp File Reference
#include "include/SparseBackpropagationHandler.h"
#include "include/TensorRankSparseBackpropagationHandler.h"
#include "TrainingDriverHandler.h"
#include <iostream>
Functions
int entry (int argc, char **argv)
Dump IR for given arguments.
int main (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 24 of file TrainingConfigureTool.cpp.
{
  if (argc != 9 and argc != 10)
  {
    std::cerr << "Two variant of usage with and without wof file: " << argv[0]
              << " <path/to/circle/model> "
                 " optional(<path/to/wof/file>) <path/to/save/train/config/result> "
                 "<path/to/input/train_data> "
                 "<path/to/input/target_train_data> "
                 "<path/to/input/test_data> "
                 "<path/to/input/target_test_data>"
                 "num_of_train_smpl "
                 "num_of_test_smpl\n";
    return EXIT_FAILURE;
  }
  training_configure_tool::TrainData train_data;
  if (argc == 10)
  {
    train_data.circle_model_path = argv[1];
    train_data.wof_file_path = argv[2];
    train_data.output_tool_file_path = argv[3];
    train_data.input_input_train_data_path = argv[4];
    train_data.input_target_train_data_path = argv[5];
    train_data.input_input_test_data_path = argv[6];
    train_data.input_target_test_data_path = argv[7];
    train_data.num_train_data_samples = atoi(argv[8]);
    train_data.num_test_data_samples = atoi(argv[9]);
  }
  else if (argc == 9)
  {
    train_data.circle_model_path = argv[1];
    train_data.output_tool_file_path = argv[2];
    train_data.input_input_train_data_path = argv[3];
    train_data.input_target_train_data_path = argv[4];
    train_data.input_input_test_data_path = argv[5];
    train_data.input_target_test_data_path = argv[6];
    train_data.num_train_data_samples = atoi(argv[7]);
    train_data.num_test_data_samples = atoi(argv[8]);
  }
  else
  {
    throw std::runtime_error("Unknown commands number\n");
  }
  // Configure training mode
  onert_micro::OMConfig config;
  // Set user defined training settings
  const uint32_t training_epochs = 25;
  const float lambda = 0.001f;
  const uint32_t BATCH_SIZE = 64;
  const uint32_t num_train_layers = 0;
  const onert_micro::OMLoss loss = onert_micro::CROSS_ENTROPY;
  const onert_micro::OMTrainOptimizer train_optimizer = onert_micro::ADAM;
  const float beta = 0.9;
  const float beta_squares = 0.999;
  const float epsilon = 1e-07;
  config.train_mode = true;
  {
    onert_micro::OMTrainingContext train_context;
    train_context.batch_size = BATCH_SIZE;
    train_context.num_of_train_layers = num_train_layers;
    train_context.learning_rate = lambda;
    train_context.loss = loss;
    train_context.optimizer = train_optimizer;
    train_context.beta = beta;
    train_context.beta_squares = beta_squares;
    train_context.epsilon = epsilon;
    train_context.epochs = training_epochs;
    config.training_context = train_context;
  }
  train_data.metrics_to_check_best_config = onert_micro::CROSS_ENTROPY_METRICS;
  train_data.memory_above_restriction = 300000;
  train_data.acceptable_diff = 0.02;
  // Find sparse backpropagation best configure
  std::unordered_set<uint16_t> best_trainable_op_indexes;
  training_configure_tool::findBestTrainableOpIndexes(config, train_data,
                                                      best_trainable_op_indexes);
  // Find the best train tensors ranks
  training_configure_tool::TrainConfigFileData config_result;
  auto res = training_configure_tool::findBestSparseBackpropagationTensorsRanks(
    config, train_data, best_trainable_op_indexes, config_result.trainable_op_indexes_with_ranks);
  // Save result into file
  assert(!config_result.trainable_op_indexes_with_ranks.empty());
  training_configure_tool::createResultFile(config_result, train_data.output_tool_file_path);
  return EXIT_SUCCESS;
}
References training_configure_tool::TrainData::acceptable_diff, onert_micro::ADAM, onert_micro::OMTrainingContext::batch_size, onert_micro::OMTrainingContext::beta, onert_micro::OMTrainingContext::beta_squares, training_configure_tool::TrainData::circle_model_path, training_configure_tool::createResultFile(), onert_micro::CROSS_ENTROPY, onert_micro::CROSS_ENTROPY_METRICS, onert_micro::OMTrainingContext::epochs, onert_micro::OMTrainingContext::epsilon, training_configure_tool::findBestSparseBackpropagationTensorsRanks(), training_configure_tool::findBestTrainableOpIndexes(), training_configure_tool::TrainData::input_input_test_data_path, training_configure_tool::TrainData::input_input_train_data_path, training_configure_tool::TrainData::input_target_test_data_path, training_configure_tool::TrainData::input_target_train_data_path, onert_micro::OMTrainingContext::learning_rate, onert_micro::OMTrainingContext::loss, training_configure_tool::TrainData::memory_above_restriction, training_configure_tool::TrainData::metrics_to_check_best_config, onert_micro::OMTrainingContext::num_of_train_layers, training_configure_tool::TrainData::num_test_data_samples, training_configure_tool::TrainData::num_train_data_samples, onert_micro::OMTrainingContext::optimizer, training_configure_tool::TrainData::output_tool_file_path, training_configure_tool::TrainConfigFileData::trainable_op_indexes_with_ranks, and training_configure_tool::TrainData::wof_file_path.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 137 of file TrainingConfigureTool.cpp.
{
  // NOTE main does not catch internal exceptions for debug build to make it easy to
  //      check the stacktrace with a debugger
  return entry(argc, argv);
}
References entry().