ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/GEMM.h File Reference
GEMM.h File Reference
#include "Eigen/Core"
Functions
template<typename Lhs , typename Rhs , typename Result >
void Gemm (const Eigen::MatrixBase< Lhs > &lhs, const Eigen::MatrixBase< Rhs > &rhs, Eigen::MatrixBase< Result > *result)
Function Documentation
Gemm()
template<typename Lhs , typename Rhs , typename Result > void Gemm (const Eigen::MatrixBase< Lhs > & lhs, const Eigen::MatrixBase< Rhs > & rhs, Eigen::MatrixBase< Result > * result)
Definition at line 24 of file GEMM.h.
{
  if (rhs.cols() == 1)
  {
    result->col(0).noalias() = lhs * rhs.col(0);
  }
  else
  {
    result->noalias() = lhs * rhs;
  }
}
Referenced by Conv(), FullyConnected(), and mir_onnx::registerSupportedOps().