ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Pooling.h File Reference
Pooling.h File Reference
#include "Shape.h"
#include <cstdint>
Functions
bool genericPoolingPrepare (const Shape &input, int32_t padding_left, int32_t padding_right, int32_t padding_top, int32_t padding_bottom, int32_t stride_width, int32_t stride_height, int32_t filter_width, int32_t filter_height, Shape *output)
Function Documentation
genericPoolingPrepare()
bool genericPoolingPrepare (const Shape & input, int32_t padding_left, int32_t padding_right, int32_t padding_top, int32_t padding_bottom, int32_t stride_width, int32_t stride_height, int32_t filter_width, int32_t filter_height, Shape * output)
Definition at line 23 of file Pooling.cpp.
{
  ASSERT(getNumberOfDimensions(input) == 4);
  uint32_t batches = getSizeOfDimension(input, 0);
  uint32_t width = getSizeOfDimension(input, 2);
  uint32_t height = getSizeOfDimension(input, 1);
  uint32_t channels_out = getSizeOfDimension(input, 3);
  uint32_t outWidth =
      computeOutSize(width, filter_width, stride_width, padding_left, padding_right);
  uint32_t outHeight =
      computeOutSize(height, filter_height, stride_height, padding_top, padding_bottom);
  output->type = input.type;
  output->dimensions = {batches, outHeight, outWidth, channels_out};
  return true;
}
References ASSERT, computeOutSize(), getNumberOfDimensions(), and getSizeOfDimension().
Referenced by averagePoolPrepare(), and maxPoolPrepare().