ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Dims.h File Reference
Dims.h File Reference
#include "Shape.h"
#include "Macro.h"
Data Structures
struct Dims< N >
Functions
Dims< 4 > convertShapeToDims (const Shape &shape)
int Offset (const Dims< 4 > &dims, int i0, int i1, int i2, int i3)
template<int N>
int ArraySize (const Dims< N > &array, int index)
template<int N>
int FlatSize (const Dims< N > &dims)
int RequiredBufferSizeForDims (const Dims< 4 > &dims)
template<int N>
int MatchingFlatSize (const Dims< N > &dims, const Dims< N > &check_dims_0)
template<int N>
int MatchingFlatSize (const Dims< N > &dims, const Dims< N > &check_dims_0, const Dims< N > &check_dims_1)
template<int N>
int MatchingFlatSize (const Dims< N > &dims, const Dims< N > &check_dims_0, const Dims< N > &check_dims_1, const Dims< N > &check_dims_2)
template<int N>
int MatchingFlatSize (const Dims< N > &dims, const Dims< N > &check_dims_0, const Dims< N > &check_dims_1, const Dims< N > &check_dims_2, const Dims< N > &check_dims_3)
template<int N>
bool IsPackedWithoutStrides (const Dims< N > &dims)
Function Documentation
ArraySize()
template<int N> int ArraySize (const Dims< N > & array, int index)
Definition at line 76 of file Dims.h.
{
  DCHECK(index >= 0 && index < N);
  return array.sizes[index];
}
References DCHECK, and Dims< N >::sizes.
Referenced by AveragePool(), BroadcastAdd(), BroadcastDiv(), BroadcastMul(), BroadcastSub(), Concatenation(), Conv(), optimized_ops::DepthwiseConv(), FullyConnected(), Im2col(), MatchingArraySize(), MatchingFlatSize(), MaxPool(), and NdArrayDescsForElementwiseBroadcast().
convertShapeToDims()
Dims< 4 > convertShapeToDims (const Shape & shape) inline
Definition at line 31 of file Dims.h.
{
  Dims<4> dims;
  for (int i = 0; i < 4; i++)
  {
    dims.sizes[i] = 1;
  }
  if (shape.dimensions.size() == 1)
  {
    dims.sizes[0] = (int)getSizeOfDimension(shape, 0);
  }
  else
  {
    for (int i = 0; i < 4; i++)
    {
      int src = (int)shape.dimensions.size() - i - 1;
      if (src >= 0)
      {
        dims.sizes[i] = (int)getSizeOfDimension(shape, src);
      }
    }
  }
  dims.strides[0] = 1;
  for (int i = 1; i < 4; i++)
  {
    dims.strides[i] = dims.strides[i - 1] * dims.sizes[i - 1];
  }
  return dims;
}
References Shape::dimensions, getSizeOfDimension(), Dims< N >::sizes, and Dims< N >::strides.
Referenced by concatenationFloat32(), padGeneric(), and softmaxFloat32().
FlatSize()
template<int N> int FlatSize (const Dims< N > & dims) inline
Definition at line 83 of file Dims.h.
{
  int flat_size = 1;
  for (int i = 0; i < N; ++i)
  {
    flat_size *= dims.sizes[i];
  }
  return flat_size;
}
References Dims< N >::sizes.
Referenced by MatchingFlatSize().
IsPackedWithoutStrides()
template<int N> bool IsPackedWithoutStrides (const Dims< N > & dims)
Definition at line 155 of file Dims.h.
{
  int expected_stride = 1;
  for (int d = 0; d < N; d++)
  {
    if (dims.strides[d] != expected_stride)
      return false;
    expected_stride *= dims.sizes[d];
  }
  return true;
}
References Dims< N >::sizes, and Dims< N >::strides.
Referenced by Add(), Concatenation(), Div(), Im2col(), Mul(), and Sub().
MatchingFlatSize() [1/4]
template<int N> int MatchingFlatSize (const Dims< N > & dims, const Dims< N > & check_dims_0) inline
Definition at line 108 of file Dims.h.
{
  for (int i = 0; i < N; ++i)
  {
    DCHECK_EQ(ArraySize(dims, i), ArraySize(check_dims_0, i));
  }
  return FlatSize(dims);
}
References ArraySize(), DCHECK_EQ, and FlatSize().
Referenced by tflite::reference_ops::Dequantize(), onert::backend::cpu::ops::ElementwiseActivationLayer::EvalUsingLookupTable(), tflite::reference_ops::FakeQuant(), MatchingFlatSize(), tflite::reference_ops::Maximum(), tflite::reference_ops::Minimum(), tflite::reference_ops::Pow(), tflite::reference_ops::RankOneSelect(), tflite::reference_ops::Relu(), tflite::reference_ops::Relu1(), tflite::reference_ops::Relu6(), tflite::reference_ops::ReluX(), onert::backend::cpu::ops::QuantizeLayer::run(), and tflite::reference_ops::Select().
MatchingFlatSize() [2/4]
template<int N> int MatchingFlatSize (const Dims< N > & dims, const Dims< N > & check_dims_0, const Dims< N > & check_dims_1) inline
Definition at line 119 of file Dims.h.
{
  for (int i = 0; i < N; ++i)
  {
    DCHECK_EQ(ArraySize(dims, i), ArraySize(check_dims_0, i));
  }
  return MatchingFlatSize(dims, check_dims_1);
}
References ArraySize(), DCHECK_EQ, and MatchingFlatSize().
MatchingFlatSize() [3/4]
template<int N> int MatchingFlatSize (const Dims< N > & dims, const Dims< N > & check_dims_0, const Dims< N > & check_dims_1, const Dims< N > & check_dims_2) inline
Definition at line 131 of file Dims.h.
{
  for (int i = 0; i < N; ++i)
  {
    DCHECK_EQ(ArraySize(dims, i), ArraySize(check_dims_0, i));
  }
  return FlatSize(dims, check_dims_1, check_dims_2);
}
References ArraySize(), DCHECK_EQ, and FlatSize().
MatchingFlatSize() [4/4]
template<int N> int MatchingFlatSize (const Dims< N > & dims, const Dims< N > & check_dims_0, const Dims< N > & check_dims_1, const Dims< N > & check_dims_2, const Dims< N > & check_dims_3) inline
Definition at line 143 of file Dims.h.
{
  for (int i = 0; i < N; ++i)
  {
    DCHECK_EQ(ArraySize(dims, i), ArraySize(check_dims_0, i));
  }
  return FlatSize(dims, check_dims_1, check_dims_2, check_dims_3);
}
References ArraySize(), DCHECK_EQ, and FlatSize().
Offset()
int Offset (const Dims< 4 > & dims, int i0, int i1, int i2, int i3) inline
Definition at line 64 of file Dims.h.
{
  DCHECK(i0 >= 0 && i0 < dims.sizes[0]);
  DCHECK(i1 >= 0 && i1 < dims.sizes[1]);
  DCHECK(i2 >= 0 && i2 < dims.sizes[2]);
  DCHECK(i3 >= 0 && i3 < dims.sizes[3]);
  return i0 * dims.strides[0] + i1 * dims.strides[1] + i2 * dims.strides[2] + i3 * dims.strides[3];
}
References DCHECK, Dims< N >::sizes, and Dims< N >::strides.
Referenced by AveragePool(), BroadcastAdd(), BroadcastDiv(), BroadcastMul(), tflite::reference_ops::BroadcastPow4DSlow(), tflite::reference_ops::BroadcastSelect4DSlow(), BroadcastSub(), ExtractPatchIntoBufferColumn(), tflite::reference_ops::LstmCell(), MaxPool(), tflite::reference_ops::Slice(), and tflite::reference_ops::SparseToDense().
RequiredBufferSizeForDims()
int RequiredBufferSizeForDims (const Dims< 4 > & dims) inline
Definition at line 94 of file Dims.h.
{
  int max_offset = 0;
  for (int i = 0; i < 4; i++)
  {
    max_offset += (dims.sizes[i] - 1) * dims.strides[i];
  }
  return max_offset + 1;
}
References Dims< N >::sizes, and Dims< N >::strides.
Referenced by MapAsVector().