ONE - On-device Neural Engine: compiler/caffe2circle/src/caffe2circle.cpp File Reference
caffe2circle.cpp File Reference
#include <caffe_importer.h>
#include <mir2loco.h>
#include <exo/CircleExporter.h>
#include <cstdlib>
#include <iostream>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 24 of file caffe2circle.cpp.
{
  if (argc != 3)
  {
    std::cerr << "Usage: caffe2circle <path/to/caffe/model> <path/to/circle/model>\n";
    return EXIT_FAILURE;
  }
  const char *caffe_path = argv[1];
  const char *circle_path = argv[2];
  std::unique_ptr<mir::Graph> mir_graph = mir_caffe::importModelFromBinaryFile(caffe_path);
  std::unique_ptr<loco::Graph> loco_graph = mir2loco::Transformer().transform(mir_graph.get());
  exo::CircleExporter(loco_graph.get()).dumpToFile(circle_path);
  return EXIT_SUCCESS;
}
References exo::CircleExporter::dumpToFile(), mir_caffe::importModelFromBinaryFile(), and mir2loco::Transformer::transform().