ONE - On-device Neural Engine: compiler/enco/frontend/caffe/src/IRBuilder.h File Reference
IRBuilder.h File Reference
#include "coco/IR/Module.h"
#include <deque>
Data Structures
class OpBuilder
class InstrBuilder
Functions
OpBuilder op_builder (coco::Module *m)
OpBuilder op_builder (const std::unique_ptr< coco::Module > &m)
InstrBuilder instr_builder (coco::Module *m)
InstrBuilder instr_builder (const std::unique_ptr< coco::Module > &m)
Function Documentation
instr_builder() [1/2]
InstrBuilder instr_builder (coco::Module * m) inline
Definition at line 174 of file IRBuilder.h.
{ return InstrBuilder{m}; }
References m.
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::build_activation(), and instr_builder().
instr_builder() [2/2]
InstrBuilder instr_builder (const std::unique_ptr< coco::Module > & m) inline
Definition at line 175 of file IRBuilder.h.
{
  return instr_builder(m.get());
}
References instr_builder(), and m.
op_builder() [1/2]
OpBuilder op_builder (coco::Module * m) inline
Definition at line 144 of file IRBuilder.h.
{ return OpBuilder{m}; }
References m.
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::build_activation(), and op_builder().
op_builder() [2/2]
OpBuilder op_builder (const std::unique_ptr< coco::Module > & m) inline
Definition at line 145 of file IRBuilder.h.
{ return op_builder(m.get()); }
References m, and op_builder().