ONE - On-device Neural Engine: compiler/circle-input-names/src/circle-input-names.cpp File Reference
circle-input-names.cpp File Reference
#include <iostream>
#include <crew/PConfigJson.h>
#include <luci/CircleNodeSummaryBuilders.h>
#include <luci/IR/CircleNodes.lst>
Data Structures
struct is_VariadicArity< T >
struct is_VariadicArity< CircleConcatenation >
struct is_VariadicArity< CircleCustom >
struct is_VariadicArity< CirclePack >
struct is_VariadicArity< CircleAddN >
struct is_VariadicArity< CircleIf >
struct is_VariadicArity< CircleWhile >
struct is_VariadicOut< T >
struct is_VariadicOut< CircleCustom >
struct is_VariadicOut< CircleIf >
struct is_VariadicOut< CircleWhile >
class MockSymbolTable
Macros
#define CIRCLE_NODE(OPCODE, CLASS)
#define CIRCLE_NODE(OPCODE, CLASS)
#define CIRCLE_NODE(OP, CIRCLE_OP)
#define CIRCLE_VNODE(_1, _2)
Functions
template<typename CircleOp , typename std::enable_if_t< is_VariadicArity< CircleOp >::value &&is_VariadicOut< CircleOp >::value > * = nullptr>
auto CircleNodeCreator ()
void add_fused_actfn_option (CircleNode *node)
void add_padding_option (CircleNode *node)
void add_mode_option (CircleNode *node)
void fill_dummies_for_summary_creation (CircleNode *node)
locop::NodeSummary create_circle_node_summary (CircleNode *node)
void get_input_names_from_summary (CircleNode *node, locop::NodeSummary &s, crew::JsonExport &json_export)
int main (void)
Macro Definition Documentation
CIRCLE_NODE [1/3]
#define CIRCLE_NODE (OP, CIRCLE_OP)
Value:
  {                                                            \
    auto node = CircleNodeCreator<CIRCLE_OP>();                \
    fill_dummies_for_summary_creation(&node);                  \
    auto summary = create_circle_node_summary(&node);          \
    get_input_names_from_summary(&node, summary, json_export); \
  }
CIRCLE_NODE [2/3]
#define CIRCLE_NODE (OPCODE, CLASS)
Value:
  case luci::CircleOpcode::OPCODE:            \
  {                                           \
    auto node_ = dynamic_cast<CLASS *>(node); \
    node_->padding(Padding::SAME);            \
    break;                                    \
  }
CIRCLE_NODE [3/3]
#define CIRCLE_NODE (OPCODE, CLASS)
Value:
  case luci::CircleOpcode::OPCODE:            \
  {                                           \
    auto node_ = dynamic_cast<CLASS *>(node); \
    auto mode_ = node_->mode();               \
    node_->mode(decltype(mode_)(1));          \
    break;                                    \
  }
CIRCLE_VNODE
#define CIRCLE_VNODE (_1, _2)
Function Documentation
add_fused_actfn_option()
void add_fused_actfn_option (CircleNode * node)
Definition at line 66 of file circle-input-names.cpp.
{
  auto node_ = dynamic_cast<CircleNodeMixin<CircleNodeTrait::FusedActFunc> *>(node);
  if (node_)
  {
    node_->fusedActivationFunction(luci::FusedActFunc::RELU);
  }
}
References luci::RELU.
Referenced by fill_dummies_for_summary_creation().
add_mode_option()
void add_mode_option (CircleNode * node)
Definition at line 104 of file circle-input-names.cpp.
{
  switch (node->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS)            \
  case luci::CircleOpcode::OPCODE:            \
  {                                           \
    auto node_ = dynamic_cast<CLASS *>(node); \
    auto mode_ = node_->mode();               \
    node_->mode(decltype(mode_)(1));          \
    break;                                    \
  }
    CIRCLE_NODE(MIRROR_PAD, CircleMirrorPad)
    CIRCLE_NODE(ROPE, CircleRoPE)
#undef CIRCLE_NODE
    default:
    {
      break;
    }
  }
  return;
}
References CIRCLE_NODE, and luci::CircleNode::opcode().
Referenced by fill_dummies_for_summary_creation().
add_padding_option()
void add_padding_option (CircleNode * node)
Definition at line 77 of file circle-input-names.cpp.
{
  switch (node->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS)            \
  case luci::CircleOpcode::OPCODE:            \
  {                                           \
    auto node_ = dynamic_cast<CLASS *>(node); \
    node_->padding(Padding::SAME);            \
    break;                                    \
  }
    CIRCLE_NODE(AVERAGE_POOL_2D, CircleAveragePool2D)
    CIRCLE_NODE(CONV_2D, CircleConv2D)
    CIRCLE_NODE(DEPTHWISE_CONV_2D, CircleDepthwiseConv2D)
    CIRCLE_NODE(L2_POOL_2D, CircleL2Pool2D)
    CIRCLE_NODE(MAX_POOL_2D, CircleMaxPool2D)
    CIRCLE_NODE(TRANSPOSE_CONV, CircleTransposeConv)
#undef CIRCLE_NODE
    default:
    {
      break;
    }
  }
  return;
}
References AVERAGE_POOL_2D, CIRCLE_NODE, CONV_2D, DEPTHWISE_CONV_2D, L2_POOL_2D, MAX_POOL_2D, and luci::CircleNode::opcode().
Referenced by fill_dummies_for_summary_creation().
CircleNodeCreator()
template<typename CircleOp , typename std::enable_if_t< is_VariadicArity< CircleOp >::value &&is_VariadicOut< CircleOp >::value > * = nullptr> auto CircleNodeCreator ()
Definition at line 43 of file circle-input-names.cpp.
{
  return CircleOp(1, 1);
}
create_circle_node_summary()
locop::NodeSummary create_circle_node_summary (CircleNode * node)
Definition at line 142 of file circle-input-names.cpp.
{
  locop::NodeSummary s;
  MockSymbolTable tbl;
  CircleNodeSummaryBuilder builder;
  builder.build(node, &tbl, s);
  return s;
}
References luci::CircleNodeSummaryBuilder::build().
fill_dummies_for_summary_creation()
void fill_dummies_for_summary_creation (CircleNode * node)
Definition at line 128 of file circle-input-names.cpp.
{
  add_fused_actfn_option(node);
  add_padding_option(node);
  add_mode_option(node);
}
References add_fused_actfn_option(), add_mode_option(), and add_padding_option().
get_input_names_from_summary()
void get_input_names_from_summary (CircleNode * node, locop::NodeSummary & s, crew::JsonExport & json_export)
Definition at line 153 of file circle-input-names.cpp.
{
  std::vector<std::string> arg_names;
  for (int i = 0; i < node->arity(); i++)
  {
    auto args = s.args().at(i);
    // args : pair(name, value)
    arg_names.emplace_back(args.first);
  }
  // s.opname() : "Circle.Opname""
  auto opname = s.opname().substr(7);
  // "Opname" : ["arg1", "arg2",...],"
  json_export.key_val(opname, arg_names, true);
}
References loco::Node::arity(), and crew::JsonExport::key_val().
main()
int main (void)
Definition at line 170 of file circle-input-names.cpp.
{
  std::stringstream ss;
  crew::JsonExport json_export(ss);
  // "{"
  json_export.open_brace();
#define CIRCLE_NODE(OP, CIRCLE_OP)                             \
  {                                                            \
    auto node = CircleNodeCreator<CIRCLE_OP>();                \
    fill_dummies_for_summary_creation(&node);                  \
    auto summary = create_circle_node_summary(&node);          \
    get_input_names_from_summary(&node, summary, json_export); \
  }
#define CIRCLE_VNODE(_1, _2)
#include <luci/IR/CircleNodes.lst>
#undef CIRCLE_NODE
#undef CIRCLE_VNODE
  // Remove last comma from stringstream 'ss'
  ss.seekp(-2, std::ios_base::end) << '\n';
  // "}"
  json_export.close_brace(false);
  std::cout << ss.str();
  return 0;
}
References crew::JsonExport::close_brace(), and crew::JsonExport::open_brace().
Referenced by utils::safemain().