ONE - On-device Neural Engine: onert::backend::PortableTensorRegistryTemplate< T_Tensor > Class Template Reference
onert::backend::PortableTensorRegistryTemplate< T_Tensor > Class Template Reference
TensorRegistry template class for the convenience of backend implementations.
#include <ITensorRegistry.h>
Public Member Functions
ITensor * getITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native tensors.
IPortableTensor * getPortableTensor (const ir::OperandIndex &ind)
T_Tensor * getNativeTensor (const ir::OperandIndex &ind)
bool setMigrantTensor (const ir::OperandIndex &ind, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void setNativeTensor (const ir::OperandIndex &ind, std::unique_ptr< T_Tensor > &&tensor)
const ir::OperandIndexMap< std::unique_ptr< T_Tensor > > & native_tensors ()
const ir::OperandIndexMap< IPortableTensor * > & migrant_tensors ()
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Detailed Description
template<typename T_Tensor>
class onert::backend::PortableTensorRegistryTemplate< T_Tensor >
TensorRegistry template class for the convenience of backend implementations.
If a backend uses IPortableTensor , and there is no special reason to implement ITensorRegistry on your own, you may just use this default implementation.
Template Parameters
T_Tensor Tensor type. Must be a subclass of onert::backend::IPortableTensor .
Definition at line 82 of file ITensorRegistry.h.
Member Function Documentation
getITensor()
template<typename T_Tensor > ITensor * onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 85 of file ITensorRegistry.h.
  {
    static_assert(std::is_base_of<ITensor, T_Tensor>::value, "T_Tensor must derive from ITensor.");
    auto _migrant_tensor = _migrant.find(ind);
    if (_migrant_tensor != _migrant.end())
      return _migrant_tensor->second;
    return getNativeTensor(ind);
  }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeTensor().
getNativeITensor()
template<typename T_Tensor > ITensor * onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 94 of file ITensorRegistry.h.
{ return getNativeTensor(ind); }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeTensor().
getNativeTensor()
template<typename T_Tensor > T_Tensor * onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeTensor (const ir::OperandIndex & ind) inline
Definition at line 107 of file ITensorRegistry.h.
  {
    auto tensor = _native.find(ind);
    if (tensor != _native.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getITensor(), onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeITensor(), and onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getPortableTensor().
getPortableTensor()
template<typename T_Tensor > IPortableTensor * onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getPortableTensor (const ir::OperandIndex & ind) inline
Definition at line 96 of file ITensorRegistry.h.
  {
    auto _migrant_tensor = _migrant.find(ind);
    if (_migrant_tensor != _migrant.end())
    {
      if (_migrant_tensor->second)
        return _migrant_tensor->second;
    }
    return getNativeTensor(ind);
  }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeTensor().
migrant_tensors()
template<typename T_Tensor > const ir::OperandIndexMap< IPortableTensor * > & onert::backend::PortableTensorRegistryTemplate< T_Tensor >::migrant_tensors () inline
Definition at line 136 of file ITensorRegistry.h.
{ return _migrant; }
native_tensors()
template<typename T_Tensor > const ir::OperandIndexMap< std::unique_ptr< T_Tensor > > & onert::backend::PortableTensorRegistryTemplate< T_Tensor >::native_tensors () inline
Definition at line 134 of file ITensorRegistry.h.
{ return _native; }
setMigrantTensor()
template<typename T_Tensor > bool onert::backend::PortableTensorRegistryTemplate< T_Tensor >::setMigrantTensor (const ir::OperandIndex & , IPortableTensor *) inline override virtual
Set the Migrant Tensor which are from other backends.
Returns
true if supported
false if not supported
Reimplemented from onert::backend::ITensorRegistry.
Definition at line 115 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _native.find(ind);
    if (itr != _native.end())
      throw std::runtime_error{"Tried to set a migrant tensor but a native tensor already exists."};
    _migrant[ind] = tensor;
    return true;
  }
setNativeTensor()
template<typename T_Tensor > void onert::backend::PortableTensorRegistryTemplate< T_Tensor >::setNativeTensor (const ir::OperandIndex & ind, std::unique_ptr< T_Tensor > && tensor) inline
Definition at line 125 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _migrant.find(ind);
    if (itr != _migrant.end())
      throw std::runtime_error{"Tried to set a native tensor but a migrant tensor already exists."};
    _native[ind] = std::move(tensor);
  }
The documentation for this class was generated from the following file:
runtime/onert/core/include/backend/ITensorRegistry.h