ONE - On-device Neural Engine: onert::backend::builtin::kernel::CallLayer Class Reference
onert::backend::builtin::kernel::CallLayer Class Reference
#include <CallLayer.h>
Public Member Functions
CallLayer (const std::vector< backend::IPortableTensor * > input_tensors, const std::vector< backend::IPortableTensor * > output_tensors, const ir::SubgraphIndex &callee_subg_index, exec::IExecutors *executors, const ir::ModelIndex &model_index, const std::shared_ptr< ExternalContext > &external_context)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Detailed Description
Definition at line 28 of file CallLayer.h.
Constructor & Destructor Documentation
CallLayer()
onert::backend::builtin::kernel::CallLayer::CallLayer (const std::vector< backend::IPortableTensor * > input_tensors, const std::vector< backend::IPortableTensor * > output_tensors, const ir::SubgraphIndex & callee_subg_index, exec::IExecutors * executors, const ir::ModelIndex & model_index, const std::shared_ptr< ExternalContext > & external_context)
Definition at line 22 of file CallLayer.cc.
  : _input_tensors{input_tensors}, _output_tensors{output_tensors},
    _callee_subg_index{callee_subg_index}, _executors{executors}, _model_index{model_index},
    _external_context{external_context}
{
  // DO NOTHING
}
Member Function Documentation
run()
void onert::backend::builtin::kernel::CallLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 34 of file CallLayer.cc.
{
  exec::IExecutor *subg_exec = _executors->at(_model_index, _callee_subg_index);
  subg_exec->execute(_input_tensors, _output_tensors,
                     _executors->entryExecutor()->currentOptions());
}
References onert::exec::IExecutors::at(), onert::exec::IExecutor::currentOptions(), onert::exec::IExecutors::entryExecutor(), and onert::exec::IExecutor::execute().
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/kernel/CallLayer.h
runtime/onert/core/src/backend/builtin/kernel/CallLayer.cc