ONE - On-device Neural Engine: onert::api::python::NNFW_SESSION Class Reference
onert::api::python::NNFW_SESSION Class Reference
#include <nnfw_api_wrapper.h>
Public Member Functions
NNFW_SESSION (const char *package_file_path, const char *backends)
~NNFW_SESSION ()
void close_session ()
void set_input_tensorinfo (uint32_t index, const tensorinfo *tensor_info)
void prepare ()
void run ()
void run_async ()
void wait ()
template<typename T >
void set_input (uint32_t index, py::array_t< T > &buffer)
process input array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
template<typename T >
void set_output (uint32_t index, py::array_t< T > &buffer)
process output array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
uint32_t input_size ()
uint32_t output_size ()
void set_input_layout (uint32_t index, const char *layout)
void set_output_layout (uint32_t index, const char *layout)
tensorinfo input_tensorinfo (uint32_t index)
tensorinfo output_tensorinfo (uint32_t index)
py::array get_output (uint32_t index)
void set_prepare_config (NNFW_PREPARE_CONFIG config)
nnfw_train_info train_get_traininfo ()
void train_set_traininfo (const nnfw_train_info *info)
template<typename T >
void train_set_input (uint32_t index, py::array_t< T > &buffer)
template<typename T >
void train_set_expected (uint32_t index, py::array_t< T > &buffer)
template<typename T >
void train_set_output (uint32_t index, py::array_t< T > &buffer)
void train_prepare ()
void train (bool update_weights)
float train_get_loss (uint32_t index)
void train_export_circle (const py::str &path)
void train_import_checkpoint (const py::str &path)
void train_export_checkpoint (const py::str &path)
Detailed Description
Definition at line 124 of file nnfw_api_wrapper.h.
Constructor & Destructor Documentation
NNFW_SESSION()
onert::api::python::NNFW_SESSION::NNFW_SESSION (const char * package_file_path, const char * backends)
Definition at line 136 of file nnfw_api_wrapper.cc.
{
  this->session = nullptr;
  ensure_status(nnfw_create_session(&(this->session)));
  ensure_status(nnfw_load_model_from_file(this->session, package_file_path));
  ensure_status(nnfw_set_available_backends(this->session, backends));
}
References onert::api::python::ensure_status(), nnfw_create_session(), nnfw_load_model_from_file(), and nnfw_set_available_backends().
~NNFW_SESSION()
onert::api::python::NNFW_SESSION::~NNFW_SESSION ()
Definition at line 143 of file nnfw_api_wrapper.cc.
{
  if (session)
  {
    close_session();
  }
}
References close_session().
Member Function Documentation
close_session()
void onert::api::python::NNFW_SESSION::close_session ()
Definition at line 151 of file nnfw_api_wrapper.cc.
{
  ensure_status(nnfw_close_session(this->session));
  this->session = nullptr;
}
References onert::api::python::ensure_status(), and nnfw_close_session().
Referenced by ~NNFW_SESSION().
get_output()
py::array onert::api::python::NNFW_SESSION::get_output (uint32_t index)
Definition at line 225 of file nnfw_api_wrapper.cc.
{
  // First call into the C API
  nnfw_tensorinfo out_info = {};
  const void *out_buffer = nullptr;
  ensure_status(nnfw_get_output(session, index, &out_info, &out_buffer));
  // Convert nnfw_tensorinfo to our python-visible struct
  size_t num_elements = 1;
  std::vector<ssize_t> shape;
  shape.reserve(out_info.rank);
  for (int i = 0; i < out_info.rank; ++i)
  {
    shape.push_back(static_cast<ssize_t>(out_info.dims[i]));
    num_elements *= static_cast<size_t>(out_info.dims[i]);
  }
  // Wrap the raw buffer in a numpy array;
  auto np = py::module_::import("numpy");
  py::dtype dt = np.attr("dtype")(py::str(getStringType(out_info.dtype))).cast<py::dtype>();
  size_t itemsize = dt.attr("itemsize").cast<size_t>();
  py::array arr(dt, shape);
  std::memcpy(arr.mutable_data(), out_buffer, num_elements * itemsize);
  arr.attr("flags").attr("writeable") = false;
  return arr;
}
References nnfw_tensorinfo::dims, nnfw_tensorinfo::dtype, onert::api::python::ensure_status(), onert::api::python::getStringType(), nnfw_get_output(), and nnfw_tensorinfo::rank.
Referenced by onert::api::python::bind_nnfw_session().
input_size()
uint32_t onert::api::python::NNFW_SESSION::input_size ()
Definition at line 171 of file nnfw_api_wrapper.cc.
{
  uint32_t number;
  NNFW_STATUS status = nnfw_input_size(session, &number);
  ensure_status(status);
  return number;
}
References onert::api::python::ensure_status(), and nnfw_input_size().
Referenced by onert::api::python::bind_nnfw_session().
input_tensorinfo()
tensorinfo onert::api::python::NNFW_SESSION::input_tensorinfo (uint32_t index)
Definition at line 195 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo tensor_info = nnfw_tensorinfo();
  ensure_status(nnfw_input_tensorinfo(session, index, &tensor_info));
  tensorinfo ti;
  ti.dtype = getStringType(tensor_info.dtype);
  ti.rank = tensor_info.rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info.dims[i];
  }
  return ti;
}
References nnfw_tensorinfo::dims, onert::api::python::tensorinfo::dims, nnfw_tensorinfo::dtype, onert::api::python::tensorinfo::dtype, onert::api::python::ensure_status(), onert::api::python::getStringType(), nnfw_input_tensorinfo(), NNFW_MAX_RANK, nnfw_tensorinfo::rank, and onert::api::python::tensorinfo::rank.
Referenced by onert::api::python::bind_nnfw_session().
output_size()
uint32_t onert::api::python::NNFW_SESSION::output_size ()
Definition at line 178 of file nnfw_api_wrapper.cc.
{
  uint32_t number;
  NNFW_STATUS status = nnfw_output_size(session, &number);
  ensure_status(status);
  return number;
}
References onert::api::python::ensure_status(), and nnfw_output_size().
Referenced by onert::api::python::bind_nnfw_session().
output_tensorinfo()
tensorinfo onert::api::python::NNFW_SESSION::output_tensorinfo (uint32_t index)
Definition at line 208 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo tensor_info = nnfw_tensorinfo();
  ensure_status(nnfw_output_tensorinfo(session, index, &tensor_info));
  tensorinfo ti;
  ti.dtype = getStringType(tensor_info.dtype);
  ti.rank = tensor_info.rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info.dims[i];
  }
  return ti;
}
References nnfw_tensorinfo::dims, onert::api::python::tensorinfo::dims, nnfw_tensorinfo::dtype, onert::api::python::tensorinfo::dtype, onert::api::python::ensure_status(), onert::api::python::getStringType(), NNFW_MAX_RANK, nnfw_output_tensorinfo(), nnfw_tensorinfo::rank, and onert::api::python::tensorinfo::rank.
Referenced by onert::api::python::bind_nnfw_session().
prepare()
void onert::api::python::NNFW_SESSION::prepare ()
Definition at line 167 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_prepare(session)); }
References onert::api::python::ensure_status(), and nnfw_prepare().
Referenced by onert::api::python::bind_nnfw_session().
run()
void onert::api::python::NNFW_SESSION::run ()
Definition at line 168 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_run(session)); }
References onert::api::python::ensure_status(), and nnfw_run().
Referenced by onert::api::python::bind_nnfw_session().
run_async()
void onert::api::python::NNFW_SESSION::run_async ()
Definition at line 169 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_run_async(session)); }
References onert::api::python::ensure_status(), and nnfw_run_async().
Referenced by onert::api::python::bind_nnfw_session().
set_input()
template<typename T > void onert::api::python::NNFW_SESSION::set_input (uint32_t index, py::array_t< T > & buffer) inline
process input array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
Definition at line 143 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_input_tensorinfo(this->session, index, &tensor_info);
    NNFW_TYPE type = tensor_info.dtype;
    uint32_t input_elements = num_elems(&tensor_info);
    size_t length = sizeof(T) * input_elements;
    ensure_status(nnfw_set_input(session, index, type, buffer.request().ptr, length));
  }
References nnfw_tensorinfo::dtype, onert::api::python::ensure_status(), nnfw_input_tensorinfo(), nnfw_set_input(), and onert::api::python::num_elems().
set_input_layout()
void onert::api::python::NNFW_SESSION::set_input_layout (uint32_t index, const char * layout)
Definition at line 185 of file nnfw_api_wrapper.cc.
{
  NNFW_LAYOUT nnfw_layout = getLayout(layout);
  ensure_status(nnfw_set_input_layout(session, index, nnfw_layout));
}
References onert::api::python::ensure_status(), onert::api::python::getLayout(), and nnfw_set_input_layout().
Referenced by onert::api::python::bind_nnfw_session().
set_input_tensorinfo()
void onert::api::python::NNFW_SESSION::set_input_tensorinfo (uint32_t index, const tensorinfo * tensor_info)
Definition at line 156 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo ti;
  ti.dtype = getType(tensor_info->dtype);
  ti.rank = tensor_info->rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info->dims[i];
  }
  ensure_status(nnfw_set_input_tensorinfo(session, index, &ti));
}
References nnfw_tensorinfo::dims, onert::api::python::tensorinfo::dims, nnfw_tensorinfo::dtype, onert::api::python::tensorinfo::dtype, onert::api::python::ensure_status(), onert::api::python::getType(), NNFW_MAX_RANK, nnfw_set_input_tensorinfo(), nnfw_tensorinfo::rank, and onert::api::python::tensorinfo::rank.
Referenced by onert::api::python::bind_nnfw_session().
set_output()
template<typename T > void onert::api::python::NNFW_SESSION::set_output (uint32_t index, py::array_t< T > & buffer) inline
process output array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
Definition at line 157 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_output_tensorinfo(this->session, index, &tensor_info);
    NNFW_TYPE type = tensor_info.dtype;
    uint32_t output_elements = num_elems(&tensor_info);
    size_t length = sizeof(T) * output_elements;
    ensure_status(nnfw_set_output(session, index, type, buffer.request().ptr, length));
  }
References nnfw_tensorinfo::dtype, onert::api::python::ensure_status(), nnfw_output_tensorinfo(), nnfw_set_output(), and onert::api::python::num_elems().
set_output_layout()
void onert::api::python::NNFW_SESSION::set_output_layout (uint32_t index, const char * layout)
Definition at line 190 of file nnfw_api_wrapper.cc.
{
  NNFW_LAYOUT nnfw_layout = getLayout(layout);
  ensure_status(nnfw_set_output_layout(session, index, nnfw_layout));
}
References onert::api::python::ensure_status(), onert::api::python::getLayout(), and nnfw_set_output_layout().
Referenced by onert::api::python::bind_nnfw_session().
set_prepare_config()
void onert::api::python::NNFW_SESSION::set_prepare_config (NNFW_PREPARE_CONFIG config)
Definition at line 257 of file nnfw_api_wrapper.cc.
{
  ensure_status(nnfw_set_prepare_config(session, config, "true"));
}
References onert::api::python::ensure_status(), and nnfw_set_prepare_config().
train()
void onert::api::python::NNFW_SESSION::train (bool update_weights)
Definition at line 279 of file nnfw_api_wrapper.cc.
{
  ensure_status(nnfw_train(session, update_weights));
}
References onert::api::python::ensure_status(), and nnfw_train().
train_export_checkpoint()
void onert::api::python::NNFW_SESSION::train_export_checkpoint (const py::str & path)
Definition at line 303 of file nnfw_api_wrapper.cc.
{
  const char *c_str_path = path.cast<std::string>().c_str();
  ensure_status(nnfw_train_export_checkpoint(session, c_str_path));
}
References onert::api::python::ensure_status(), and nnfw_train_export_checkpoint().
train_export_circle()
void onert::api::python::NNFW_SESSION::train_export_circle (const py::str & path)
Definition at line 291 of file nnfw_api_wrapper.cc.
{
  const char *c_str_path = path.cast<std::string>().c_str();
  ensure_status(nnfw_train_export_circle(session, c_str_path));
}
References onert::api::python::ensure_status(), and nnfw_train_export_circle().
train_get_loss()
float onert::api::python::NNFW_SESSION::train_get_loss (uint32_t index)
Definition at line 284 of file nnfw_api_wrapper.cc.
{
  float loss = 0.f;
  ensure_status(nnfw_train_get_loss(session, index, &loss));
  return loss;
}
References onert::api::python::ensure_status(), and nnfw_train_get_loss().
train_get_traininfo()
nnfw_train_info onert::api::python::NNFW_SESSION::train_get_traininfo ()
Definition at line 265 of file nnfw_api_wrapper.cc.
{
  nnfw_train_info train_info = nnfw_train_info();
  ensure_status(nnfw_train_get_traininfo(session, &train_info));
  return train_info;
}
References onert::api::python::ensure_status(), and nnfw_train_get_traininfo().
train_import_checkpoint()
void onert::api::python::NNFW_SESSION::train_import_checkpoint (const py::str & path)
Definition at line 297 of file nnfw_api_wrapper.cc.
{
  const char *c_str_path = path.cast<std::string>().c_str();
  ensure_status(nnfw_train_import_checkpoint(session, c_str_path));
}
References onert::api::python::ensure_status(), and nnfw_train_import_checkpoint().
train_prepare()
void onert::api::python::NNFW_SESSION::train_prepare ()
Definition at line 277 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_train_prepare(session)); }
References onert::api::python::ensure_status(), and nnfw_train_prepare().
train_set_expected()
template<typename T > void onert::api::python::NNFW_SESSION::train_set_expected (uint32_t index, py::array_t< T > & buffer) inline
Definition at line 204 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_output_tensorinfo(this->session, index, &tensor_info);
    py::buffer_info buf_info = buffer.request();
    const auto buf_shape = buf_info.shape;
    assert(tensor_info.rank == static_cast<int32_t>(buf_shape.size()) && buf_shape.size() > 0);
    tensor_info.dims[0] = static_cast<int32_t>(buf_shape.at(0));
    ensure_status(
      nnfw_train_set_expected(this->session, index, buffer.request().ptr, &tensor_info));
  }
References nnfw_tensorinfo::dims, onert::api::python::ensure_status(), nnfw_output_tensorinfo(), nnfw_train_set_expected(), and nnfw_tensorinfo::rank.
train_set_input()
template<typename T > void onert::api::python::NNFW_SESSION::train_set_input (uint32_t index, py::array_t< T > & buffer) inline
Definition at line 192 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_input_tensorinfo(this->session, index, &tensor_info);
    py::buffer_info buf_info = buffer.request();
    const auto buf_shape = buf_info.shape;
    assert(tensor_info.rank == static_cast<int32_t>(buf_shape.size()) && buf_shape.size() > 0);
    tensor_info.dims[0] = static_cast<int32_t>(buf_shape.at(0));
    ensure_status(nnfw_train_set_input(this->session, index, buffer.request().ptr, &tensor_info));
  }
References nnfw_tensorinfo::dims, onert::api::python::ensure_status(), nnfw_input_tensorinfo(), nnfw_train_set_input(), and nnfw_tensorinfo::rank.
train_set_output()
template<typename T > void onert::api::python::NNFW_SESSION::train_set_output (uint32_t index, py::array_t< T > & buffer) inline
Definition at line 217 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_output_tensorinfo(this->session, index, &tensor_info);
    NNFW_TYPE type = tensor_info.dtype;
    uint32_t output_elements = num_elems(&tensor_info);
    size_t length = sizeof(T) * output_elements;
    ensure_status(nnfw_train_set_output(session, index, type, buffer.request().ptr, length));
  }
References nnfw_tensorinfo::dtype, onert::api::python::ensure_status(), nnfw_output_tensorinfo(), nnfw_train_set_output(), and onert::api::python::num_elems().
train_set_traininfo()
void onert::api::python::NNFW_SESSION::train_set_traininfo (const nnfw_train_info * info)
Definition at line 272 of file nnfw_api_wrapper.cc.
{
  ensure_status(nnfw_train_set_traininfo(session, info));
}
References onert::api::python::ensure_status(), info, and nnfw_train_set_traininfo().
wait()
void onert::api::python::NNFW_SESSION::wait ()
Definition at line 170 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_await(session)); }
References onert::api::python::ensure_status(), and nnfw_await().
Referenced by onert::api::python::bind_nnfw_session().
The documentation for this class was generated from the following files:
runtime/onert/api/python/include/nnfw_api_wrapper.h
runtime/onert/api/python/src/wrapper/nnfw_api_wrapper.cc