ONE - On-device Neural Engine: onert::api::APIConverter Class Reference
onert::api::APIConverter Class Reference
Static Public Member Functions
static nnfw_operand convertOperand (void *alloc, const TypeInfo &type)
static nnfw_tensorinfo convertType (const TypeInfo &type)
Detailed Description
Definition at line 26 of file CustomKernel.cc.
Member Function Documentation
convertOperand()
static nnfw_operand onert::api::APIConverter::convertOperand (void * alloc, const TypeInfo & type) inline static
Definition at line 29 of file CustomKernel.cc.
  {
    nnfw_operand api_operand;
    api_operand.allocation = alloc;
    api_operand.type = convertType(type);
    return api_operand;
  }
References nnfw_operand::allocation, convertType(), and nnfw_operand::type.
Referenced by onert::api::CustomKernel::run().
convertType()
static nnfw_tensorinfo onert::api::APIConverter::convertType (const TypeInfo & type) inline static
Definition at line 37 of file CustomKernel.cc.
  {
    nnfw_tensorinfo api_type;
    api_type.rank = type.shape.rank();
    assert(type.shape.rank() <= 6);
    std::copy(type.shape.dims().begin(), type.shape.dims().end(), std::begin(api_type.dims));
    switch (type.dtype)
    {
      case ir::DataType::FLOAT32:
        api_type.dtype = NNFW_TYPE_TENSOR_FLOAT32;
        break;
      case ir::DataType::INT32:
        api_type.dtype = NNFW_TYPE_TENSOR_INT32;
        break;
      case ir::DataType::QUANT_UINT8_ASYMM:
        api_type.dtype = NNFW_TYPE_TENSOR_QUANT8_ASYMM;
        break;
      case ir::DataType::BOOL8:
        api_type.dtype = NNFW_TYPE_TENSOR_BOOL;
        break;
      default:
        throw std::runtime_error("Unsupported tensor datatype");
    }
    return api_type;
  }
References nnfw_tensorinfo::dims, nnfw_tensorinfo::dtype, NNFW_TYPE_TENSOR_BOOL, NNFW_TYPE_TENSOR_FLOAT32, NNFW_TYPE_TENSOR_INT32, NNFW_TYPE_TENSOR_QUANT8_ASYMM, and nnfw_tensorinfo::rank.
Referenced by convertOperand().
The documentation for this class was generated from the following file:
runtime/onert/api/src/CustomKernel.cc