ONE - On-device Neural Engine: flatbuffers::Allocator Class Reference
flatbuffers::Allocator Class Reference abstract
#include <flatbuffers.h>
Public Member Functions
virtual ~Allocator ()
virtual uint8_t * allocate (size_t size)=0
virtual void deallocate (uint8_t *p, size_t size)=0
virtual uint8_t * reallocate_downward (uint8_t *old_p, size_t old_size, size_t new_size, size_t in_use_back, size_t in_use_front)
Protected Member Functions
void memcpy_downward (uint8_t *old_p, size_t old_size, uint8_t *new_p, size_t new_size, size_t in_use_back, size_t in_use_front)
Detailed Description
Definition at line 677 of file flatbuffers.h.
Constructor & Destructor Documentation
~Allocator()
virtual flatbuffers::Allocator::~Allocator () inline virtual
Definition at line 680 of file flatbuffers.h.
{}
Member Function Documentation
allocate()
virtual uint8_t * flatbuffers::Allocator::allocate (size_t size) pure virtual
Implemented in flatbuffers::DefaultAllocator, and flatbuffers::grpc::SliceAllocator.
Referenced by flatbuffers::Allocate(), and reallocate_downward().
deallocate()
virtual void flatbuffers::Allocator::deallocate (uint8_t * p, size_t size) pure virtual
Implemented in flatbuffers::grpc::SliceAllocator, and flatbuffers::DefaultAllocator.
Referenced by flatbuffers::Deallocate(), and reallocate_downward().
memcpy_downward()
void flatbuffers::Allocator::memcpy_downward (uint8_t * old_p, size_t old_size, uint8_t * new_p, size_t new_size, size_t in_use_back, size_t in_use_front) inline protected
Definition at line 708 of file flatbuffers.h.
  {
    memcpy(new_p + new_size - in_use_back, old_p + old_size - in_use_back, in_use_back);
    memcpy(new_p, old_p, in_use_front);
  }
Referenced by reallocate_downward(), and flatbuffers::grpc::SliceAllocator::reallocate_downward().
reallocate_downward()
virtual uint8_t * flatbuffers::Allocator::reallocate_downward (uint8_t * old_p, size_t old_size, size_t new_size, size_t in_use_back, size_t in_use_front) inline virtual
Reimplemented in flatbuffers::grpc::SliceAllocator.
Definition at line 693 of file flatbuffers.h.
  {
    FLATBUFFERS_ASSERT(new_size > old_size); // vector_downward only grows
    uint8_t *new_p = allocate(new_size);
    memcpy_downward(old_p, old_size, new_p, new_size, in_use_back, in_use_front);
    deallocate(old_p, old_size);
    return new_p;
  }
References allocate(), deallocate(), FLATBUFFERS_ASSERT, and memcpy_downward().
Referenced by flatbuffers::ReallocateDownward().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flatbuffers.h