ONE - On-device Neural Engine: luci_interpreter::kernels::LocalResponseNormalization Class Reference
luci_interpreter::kernels::LocalResponseNormalization Class Reference
#include <LocalResponseNormalization.h>
Public Member Functions
LocalResponseNormalization (const Tensor *input, Tensor *output, const LocalResponseNormalizationParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
LocalResponseNormalization (const Tensor *input, Tensor *output, const LocalResponseNormalizationParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< LocalResponseNormalizationParams >
const LocalResponseNormalizationParams & params () const
const LocalResponseNormalizationParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< LocalResponseNormalizationParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const LocalResponseNormalizationParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const LocalResponseNormalizationParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< LocalResponseNormalizationParams >
const LocalResponseNormalizationParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file LocalResponseNormalization.h.
Constructor & Destructor Documentation
LocalResponseNormalization() [1/2]
luci_interpreter::kernels::LocalResponseNormalization::LocalResponseNormalization (const Tensor * input, Tensor * output, const LocalResponseNormalizationParams & params)
Definition at line 31 of file LocalResponseNormalization.cpp.
  : KernelWithParams<LocalResponseNormalizationParams>({input}, {output}, params)
{
}
References input().
LocalResponseNormalization() [2/2]
luci_interpreter::kernels::LocalResponseNormalization::LocalResponseNormalization (const Tensor * input, Tensor * output, const LocalResponseNormalizationParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::LocalResponseNormalization::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file LocalResponseNormalization.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() == 4);
  LUCI_INTERPRETER_CHECK(output()->element_type() == DataType::FLOAT32);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::LocalResponseNormalization::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::LocalResponseNormalization::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 45 of file LocalResponseNormalization.cpp.
{
  switch (output()->element_type())
  {
    case DataType::FLOAT32:
      tflite::LocalResponseNormalizationParams op_params;
      op_params.range = params().radius;
      op_params.bias = params().bias;
      op_params.alpha = params().alpha;
      op_params.beta = params().beta;
      luci_interpreter_pal::LocalResponseNormalization(
        op_params, getTensorShape(input()), getTensorData<float>(input()), getTensorShape(output()),
        getTensorData<float>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::LocalResponseNormalizationParams::alpha, luci_interpreter::LocalResponseNormalizationParams::beta, luci_interpreter::LocalResponseNormalizationParams::bias, luci_interpreter::kernels::getTensorShape(), input(), output(), luci_interpreter::KernelWithParams< LocalResponseNormalizationParams >::params(), and luci_interpreter::LocalResponseNormalizationParams::radius.
execute() [2/2]
void luci_interpreter::kernels::LocalResponseNormalization::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::LocalResponseNormalization::input () const inline
Definition at line 34 of file LocalResponseNormalization.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and LocalResponseNormalization().
input() [2/2]
const Tensor * luci_interpreter::kernels::LocalResponseNormalization::input () const inline
Definition at line 34 of file LocalResponseNormalization.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::LocalResponseNormalization::output () const inline
Definition at line 35 of file LocalResponseNormalization.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::LocalResponseNormalization::output () const inline
Definition at line 35 of file LocalResponseNormalization.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/LocalResponseNormalization.h
onert-micro/luci-interpreter/src/kernels/LocalResponseNormalization.h
compiler/luci-interpreter/src/kernels/LocalResponseNormalization.cpp
onert-micro/luci-interpreter/src/kernels/LocalResponseNormalization.cpp