ONE - On-device Neural Engine: coco::Module Class Reference
coco::Module Class Reference abstract
Top-level element of coco IR which represents a neural network.
#include <Module.h>
Public Member Functions
Module ()=default
Module (const Module &)=delete
Module (Module &&)=delete
virtual ~Module ()=default
virtual EntityManager * entity (void)=0
virtual const EntityManager * entity (void) const =0
virtual BlockList * block (void)=0
virtual const BlockList * block (void) const =0
virtual InputList * input (void)=0
virtual const InputList * input (void) const =0
virtual OutputList * output (void)=0
virtual const OutputList * output (void) const =0
Static Public Member Functions
static std::unique_ptr< Module > create (void)
Detailed Description
Top-level element of coco IR which represents a neural network.
Definition at line 33 of file Module.h.
Constructor & Destructor Documentation
Module() [1/3]
coco::Module::Module () default
Module() [2/3]
coco::Module::Module (const Module &) delete
Module() [3/3]
coco::Module::Module (Module &&) delete
~Module()
virtual coco::Module::~Module () virtual default
Member Function Documentation
block() [1/2]
virtual const BlockList * coco::Module::block (void) const pure virtual
block() [2/2]
virtual BlockList * coco::Module::block (void) pure virtual
Referenced by dump(), Frontend::load(), and enco::validate_output_shape().
create()
std::unique_ptr< Module > coco::Module::create (void) static
Definition at line 127 of file Module.cpp.
{
  auto m = make_unique<::ModuleImpl>();
  auto mgr = make_unique<::EntityManagerImpl>();
  {
    mgr->_bag = make_unique<coco::BagManager>(m.get());
    mgr->_object = make_unique<coco::ObjectManager>(m.get());
    mgr->_op = make_unique<coco::OpManager>(m.get());
    mgr->_instr = make_unique<coco::InstrManager>(m.get());
    mgr->_block = make_unique<coco::BlockManager>(m.get());
    mgr->_input = make_unique<coco::InputManager>(m.get());
    mgr->_output = make_unique<coco::OutputManager>(m.get());
  }
  m->_entity = std::move(mgr);
  m->_block = make_unique<coco::BlockList>(m.get());
  m->_input = make_unique<coco::InputList>();
  m->_output = make_unique<coco::OutputList>();
  return m;
}
References m.
Referenced by Frontend::load().
entity() [1/2]
virtual const EntityManager * coco::Module::entity (void) const pure virtual
entity() [2/2]
virtual EntityManager * coco::Module::entity (void) pure virtual
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), InstrBuilder::copy(), dump(), InstrBuilder::eval(), OpBuilder::load(), and Frontend::load().
input() [1/2]
virtual const InputList * coco::Module::input (void) const pure virtual
input() [2/2]
virtual InputList * coco::Module::input (void) pure virtual
Referenced by caffeimport::InputBuilder::build(), and dump().
output() [1/2]
virtual const OutputList * coco::Module::output (void) const pure virtual
output() [2/2]
virtual OutputList * coco::Module::output (void) pure virtual
Referenced by dump(), and Frontend::load().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Module.h
compiler/coco/core/src/IR/Module.cpp