ONE - On-device Neural Engine: nnkit::support::caffe::TensorContext< DType > Class Template Reference
nnkit::support::caffe::TensorContext< DType > Class Template Reference final
#include <TensorContext.h>
Public Member Functions
TensorContext (BlobContext< DType > &blobs)
uint32_t size (void) const override
std::string name (uint32_t n) const override
nncc::core::ADT::tensor::Shape shape (uint32_t n) const override
bool isFloatTensor (uint32_t n) const override
void getMutableFloatTensor (uint32_t n, const TensorContext::TypedAccessor< float > &f) override
void getConstFloatTensor (uint32_t n, const TensorContext::TypedReader< float > &f) const override
Public Member Functions inherited from nnkit::TensorContext
virtual ~TensorContext ()=default
virtual uint32_t size (void) const =0
virtual std::string name (uint32_t n) const =0
virtual nncc::core::ADT::tensor::Shape shape (uint32_t n) const =0
virtual bool isFloatTensor (uint32_t n) const
virtual void getMutableFloatTensor (uint32_t n, const TypedAccessor< float > &cb)
virtual void getConstFloatTensor (uint32_t n, const TypedReader< float > &cb) const
virtual bool isS32Tensor (uint32_t n) const
virtual void getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > &cb)
virtual void getConstS32Tensor (uint32_t n, const TypedReader< int32_t > &cb) const
Additional Inherited Members
Public Types inherited from nnkit::TensorContext
template<typename T >
using TypedReader = std::function< void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader< T > &)>
template<typename T >
using TypedAccessor = std::function< void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor< T > &)>
Detailed Description
template<typename DType>
class nnkit::support::caffe::TensorContext< DType >
Definition at line 37 of file TensorContext.h.
Constructor & Destructor Documentation
TensorContext()
template<typename DType > nnkit::support::caffe::TensorContext< DType >::TensorContext (BlobContext< DType > & blobs) inline
Definition at line 40 of file TensorContext.h.
                                           : _blobs(blobs)
  {
    // DO NOTHING
  }
Member Function Documentation
getConstFloatTensor()
template<typename DType > void nnkit::support::caffe::TensorContext< DType >::getConstFloatTensor (uint32_t n, const TensorContext< DType >::TypedReader< float > & f) const inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 90 of file TensorContext.h.
  {
    if (!std::is_same<DType, float>::value)
    {
      throw std::runtime_error{"type mismatch"};
    }
    using nncc::core::ADT::tensor::LexicalLayout;
    using nncc::core::ADT::tensor::make_overlay;
    auto base = _blobs.region(n);
    auto view = make_overlay<float, LexicalLayout>(shape(n), base);
    f(*this, n, view);
  }
References nncc::core::ADT::tensor::make_overlay(), and nnkit::support::caffe::TensorContext< DType >::shape().
getMutableFloatTensor()
template<typename DType > void nnkit::support::caffe::TensorContext< DType >::getMutableFloatTensor (uint32_t n, const TensorContext< DType >::TypedAccessor< float > & f) inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 74 of file TensorContext.h.
  {
    if (!std::is_same<DType, float>::value)
    {
      throw std::runtime_error{"type mismatch"};
    }
    using nncc::core::ADT::tensor::LexicalLayout;
    using nncc::core::ADT::tensor::make_overlay;
    auto base = _blobs.region(n);
    auto view = make_overlay<float, LexicalLayout>(shape(n), base);
    f(*this, n, view);
  }
References nncc::core::ADT::tensor::make_overlay(), and nnkit::support::caffe::TensorContext< DType >::shape().
isFloatTensor()
template<typename DType > bool nnkit::support::caffe::TensorContext< DType >::isFloatTensor (uint32_t n) const inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 72 of file TensorContext.h.
{ return std::is_same<DType, float>::value; }
name()
template<typename DType > std::string nnkit::support::caffe::TensorContext< DType >::name (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 64 of file TensorContext.h.
{ return _blobs.name(n); }
shape()
template<typename DType > nncc::core::ADT::tensor::Shape nnkit::support::caffe::TensorContext< DType >::shape (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 66 of file TensorContext.h.
  {
    return shapeOf(*_blobs.blob(n));
  }
Referenced by nnkit::support::caffe::TensorContext< DType >::getConstFloatTensor(), and nnkit::support::caffe::TensorContext< DType >::getMutableFloatTensor().
size()
template<typename DType > uint32_t nnkit::support::caffe::TensorContext< DType >::size (void) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 62 of file TensorContext.h.
{ return _blobs.size(); }
The documentation for this class was generated from the following file:
compiler/nnkit-caffe/support/include/nnkit/support/caffe/TensorContext.h