ONE - On-device Neural Engine: NNAPIConvert Class Reference
NNAPIConvert Class Reference
#include <NNAPIConvert.h>
Static Public Member Functions
static onert::ir::DataType getDataType (OperandCode type)
Convert data type from NNAPI to internal data type.
static onert::ir::TypeInfo getTypeInfo (const ANeuralNetworksOperandType *type)
Convert operand type info from NNAPI to interanl operand type info.
static onert::ir::Shape getShape (const ANeuralNetworksOperandType *type)
Convert operand shape info from NNAPI to internal operand shape.
static size_t calculateSizeFromType (const ANeuralNetworksOperandType *type)
Calcaulate operand size from NNAPI type.
static onert::ir::Activation getFusedActivation (FuseCode act)
Convert NNAPI FuseCode to internal activation type.
static onert::ir::PaddingType getPaddingType (PaddingCode type)
Convert NNAPI PaddingCode to internal padding type.
Detailed Description
Definition at line 32 of file NNAPIConvert.h.
Member Function Documentation
calculateSizeFromType()
size_t NNAPIConvert::calculateSizeFromType (const ANeuralNetworksOperandType * type) static
Calcaulate operand size from NNAPI type.
Parameters
[in] type NNAPI's operand type
Returns
Operand size
Definition at line 71 of file NNAPIConvert.cc.
{
  auto shape = getShape(type);
  auto data_type = getDataType((OperandCode)(type->type));
  return shape.num_elements() * sizeOfDataType(data_type);
}
References getDataType(), getShape(), and onert::ir::sizeOfDataType().
Referenced by ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
getDataType()
DataType NNAPIConvert::getDataType (OperandCode type) static
Convert data type from NNAPI to internal data type.
Parameters
[in] type NNAPI's data type
Returns
onert's internal data type
Definition at line 23 of file NNAPIConvert.cc.
{
  switch (type)
  {
    case ANEURALNETWORKS_FLOAT32:
    case ANEURALNETWORKS_TENSOR_FLOAT32:
      return DataType::FLOAT32;
    case ANEURALNETWORKS_INT32:
    case ANEURALNETWORKS_TENSOR_INT32:
      return DataType::INT32;
    case ANEURALNETWORKS_UINT32:
      return DataType::UINT32;
    case ANEURALNETWORKS_TENSOR_QUANT8_ASYMM:
      return DataType::QUANT_UINT8_ASYMM;
    case ANEURALNETWORKS_TENSOR_QUANT8_SYMM:
      return DataType::QUANT_INT8_SYMM;
    case ANEURALNETWORKS_BOOL:
    case ANEURALNETWORKS_TENSOR_BOOL8:
      return DataType::BOOL8;
    case ANEURALNETWORKS_TENSOR_FLOAT16:
    case ANEURALNETWORKS_FLOAT16:
      return DataType::FLOAT16;
    case ANEURALNETWORKS_TENSOR_QUANT8_SYMM_PER_CHANNEL:
      return DataType::QUANT_INT8_SYMM_PER_CHANNEL;
    case ANEURALNETWORKS_TENSOR_QUANT8_ASYMM_SIGNED:
      return DataType::QUANT_INT8_ASYMM;
    default:
      throw std::runtime_error("Unsupported type");
  }
}
References ANEURALNETWORKS_BOOL, ANEURALNETWORKS_FLOAT16, ANEURALNETWORKS_FLOAT32, ANEURALNETWORKS_INT32, ANEURALNETWORKS_TENSOR_BOOL8, ANEURALNETWORKS_TENSOR_FLOAT16, ANEURALNETWORKS_TENSOR_FLOAT32, ANEURALNETWORKS_TENSOR_INT32, ANEURALNETWORKS_TENSOR_QUANT8_ASYMM, ANEURALNETWORKS_TENSOR_QUANT8_ASYMM_SIGNED, ANEURALNETWORKS_TENSOR_QUANT8_SYMM, ANEURALNETWORKS_TENSOR_QUANT8_SYMM_PER_CHANNEL, and ANEURALNETWORKS_UINT32.
Referenced by calculateSizeFromType(), and getTypeInfo().
getFusedActivation()
Activation NNAPIConvert::getFusedActivation (FuseCode act) static
Convert NNAPI FuseCode to internal activation type.
Parameters
[in] act NNAPI's FuseCode type
Returns
onert's internal activation type
Definition at line 79 of file NNAPIConvert.cc.
{
  switch (act)
  {
    case ANEURALNETWORKS_FUSED_NONE:
      return Activation::NONE;
    case ANEURALNETWORKS_FUSED_RELU:
      return Activation::RELU;
    case ANEURALNETWORKS_FUSED_RELU1:
      return Activation::RELU1;
    case ANEURALNETWORKS_FUSED_RELU6:
      return Activation::RELU6;
    default:
      throw std::runtime_error("Unsupported activation type");
  }
}
References ANEURALNETWORKS_FUSED_NONE, ANEURALNETWORKS_FUSED_RELU, ANEURALNETWORKS_FUSED_RELU1, and ANEURALNETWORKS_FUSED_RELU6.
getPaddingType()
PaddingType NNAPIConvert::getPaddingType (PaddingCode type) static
Convert NNAPI PaddingCode to internal padding type.
Parameters
[in] type NNAPI's PaddingCode type
Returns
onert's internal padding type
Definition at line 96 of file NNAPIConvert.cc.
{
  switch (type)
  {
    case ANEURALNETWORKS_PADDING_SAME:
      return PaddingType::SAME;
    case ANEURALNETWORKS_PADDING_VALID:
      return PaddingType::VALID;
    default:
      throw std::runtime_error("Unsupported type");
  }
}
References ANEURALNETWORKS_PADDING_SAME, and ANEURALNETWORKS_PADDING_VALID.
getShape()
Shape NNAPIConvert::getShape (const ANeuralNetworksOperandType * type) static
Convert operand shape info from NNAPI to internal operand shape.
Parameters
[in] type NNAPI's operand type
Returns
onert's internal operand shape
Definition at line 59 of file NNAPIConvert.cc.
{
  Shape shape(type->dimensionCount);
  for (uint32_t axis = 0; axis < type->dimensionCount; ++axis)
  {
    shape.dim(axis) = type->dimensions[axis];
  }
  return shape;
}
Referenced by ANeuralNetworksModel::addOperand(), calculateSizeFromType(), ANeuralNetworksExecution::compareShape(), ANeuralNetworksExecution::setInput(), ANeuralNetworksExecution::setOptionalInput(), and ANeuralNetworksExecution::setOutput().
getTypeInfo()
TypeInfo NNAPIConvert::getTypeInfo (const ANeuralNetworksOperandType * type) static
Convert operand type info from NNAPI to interanl operand type info.
Parameters
[in] type NNAPI's operand type
Returns
onert's internal operand type info
Definition at line 54 of file NNAPIConvert.cc.
{
  return TypeInfo(getDataType((OperandCode)(type->type)), type->scale, type->zeroPoint);
}
References getDataType().
Referenced by ANeuralNetworksModel::addOperand(), and ANeuralNetworksExecution::compareDataType().
The documentation for this class was generated from the following files:
runtime/onert/frontend/nnapi/wrapper/NNAPIConvert.h
runtime/onert/frontend/nnapi/wrapper/NNAPIConvert.cc