ONE - On-device Neural Engine: onert::ir::LayoutSet Class Reference
onert::ir::LayoutSet Class Reference
#include <LayoutSet.h>
Public Member Functions
LayoutSet ()=default
LayoutSet (std::initializer_list< Layout > layouts)
void add (const Layout &layout)
void remove (const Layout &layout)
uint32_t size () const
bool contains (const Layout &layout) const
LayoutSet operator| (const LayoutSet &other) const
LayoutSet operator& (const LayoutSet &other) const
LayoutSet operator- (const LayoutSet &other) const
std::unordered_set< Layout >::const_iterator begin () const
std::unordered_set< Layout >::const_iterator end () const
Detailed Description
Definition at line 30 of file LayoutSet.h.
Constructor & Destructor Documentation
LayoutSet() [1/2]
onert::ir::LayoutSet::LayoutSet () default
LayoutSet() [2/2]
onert::ir::LayoutSet::LayoutSet (std::initializer_list< Layout > layouts)
Definition at line 24 of file LayoutSet.cc.
{
  for (auto layout : layouts)
  {
    _set.insert(layout);
  }
}
Member Function Documentation
add()
void onert::ir::LayoutSet::add (const Layout & layout) inline
Definition at line 37 of file LayoutSet.h.
{ _set.insert(layout); }
Referenced by operator&(), and operator|().
begin()
std::unordered_set< Layout >::const_iterator onert::ir::LayoutSet::begin () const inline
Definition at line 48 of file LayoutSet.h.
{ return _set.begin(); }
contains()
bool onert::ir::LayoutSet::contains (const Layout & layout) const inline
Definition at line 40 of file LayoutSet.h.
{ return _set.find(layout) != _set.end(); }
Referenced by operator&().
end()
std::unordered_set< Layout >::const_iterator onert::ir::LayoutSet::end () const inline
Definition at line 49 of file LayoutSet.h.
{ return _set.end(); }
operator&()
LayoutSet onert::ir::LayoutSet::operator& (const LayoutSet & other) const
Definition at line 42 of file LayoutSet.cc.
{
  LayoutSet ret;
  for (auto layout : other)
  {
    if (contains(layout))
    {
      ret.add(layout);
    }
  }
  return ret;
}
References add(), and contains().
operator-()
LayoutSet onert::ir::LayoutSet::operator- (const LayoutSet & other) const
Definition at line 55 of file LayoutSet.cc.
{
  auto ret = *this;
  for (auto layout : other)
  {
    ret.remove(layout);
  }
  return ret;
}
References remove().
operator|()
LayoutSet onert::ir::LayoutSet::operator| (const LayoutSet & other) const
Definition at line 32 of file LayoutSet.cc.
{
  auto ret = *this;
  for (auto layout : other)
  {
    ret.add(layout);
  }
  return ret;
}
References add().
remove()
void onert::ir::LayoutSet::remove (const Layout & layout) inline
Definition at line 38 of file LayoutSet.h.
{ _set.erase(layout); }
Referenced by operator-().
size()
uint32_t onert::ir::LayoutSet::size () const inline
Definition at line 39 of file LayoutSet.h.
{ return static_cast<uint32_t>(_set.size()); }
The documentation for this class was generated from the following files:
runtime/onert/core/src/ir/LayoutSet.h
runtime/onert/core/src/ir/LayoutSet.cc