ONE - On-device Neural Engine: hermes::Message Class Reference
hermes::Message Class Reference final
Message with metadata.
#include <Message.h>
Public Member Functions
Message ()=default
void text (std::unique_ptr< MessageText > &&text)
void text (std::unique_ptr< MessageText > &&text, SeverityCategory severity)
const MessageText * text (void) const
SeverityCategory get_severity (void) const
Detailed Description
Message with metadata.
TODO Add "Timestamp" field TODO Support extensible "attribute" annotation
Definition at line 55 of file Message.h.
Constructor & Destructor Documentation
Message()
hermes::Message::Message () default
Member Function Documentation
get_severity()
SeverityCategory hermes::Message::get_severity (void) const inline
Definition at line 68 of file Message.h.
{ return _severity; }
text() [1/3]
void hermes::Message::text (std::unique_ptr< MessageText > && text) inline
Definition at line 61 of file Message.h.
{ _text = std::move(text); }
References text().
text() [2/3]
void hermes::Message::text (std::unique_ptr< MessageText > && text, SeverityCategory severity) inline
Definition at line 62 of file Message.h.
  {
    _text = std::move(text);
    _severity = severity;
  }
References text().
text() [3/3]
const MessageText * hermes::Message::text (void) const inline
Definition at line 67 of file Message.h.
{ return _text.get(); }
Referenced by text().
The documentation for this class was generated from the following file:
compiler/hermes/include/hermes/core/Message.h