ONE - On-device Neural Engine: onert::ir::OperandIndexSequence Class Reference
onert::ir::OperandIndexSequence Class Reference
#include <OperandIndexSequence.h>
Public Member Functions
OperandIndexSequence (void)=default
OperandIndexSequence (std::initializer_list< OperandIndex > list)
OperandIndexSequence (std::initializer_list< int32_t > list)
OperandIndexSequence (std::initializer_list< uint32_t > list)
void append (const OperandIndex &index)
void append (const OperandIndexSequence &l)
uint32_t size () const
const OperandIndex & at (IOIndex set_index) const
const OperandIndex & at (uint32_t index) const
bool contains (const OperandIndex &index) const
void replace (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence operator| (ir::Remove filter) const
bool operator== (const OperandIndexSequence &other) const
OperandIndexSequence operator+ (const OperandIndexSequence &other) const
std::vector< OperandIndex >::const_iterator begin (void) const
std::vector< OperandIndex >::const_iterator end (void) const
std::vector< OperandIndex >::iterator begin (void)
std::vector< OperandIndex >::iterator end (void)
Friends
std::ostream & operator<< (std::ostream &o, const OperandIndexSequence &operand_seq)
Detailed Description
Definition at line 34 of file OperandIndexSequence.h.
Constructor & Destructor Documentation
OperandIndexSequence() [1/4]
onert::ir::OperandIndexSequence::OperandIndexSequence (void) default
OperandIndexSequence() [2/4]
onert::ir::OperandIndexSequence::OperandIndexSequence (std::initializer_list< OperandIndex > list)
Definition at line 25 of file OperandIndexSequence.cc.
                                                                                 : _vec(list)
{
  // DO NOTHING
}
OperandIndexSequence() [3/4]
onert::ir::OperandIndexSequence::OperandIndexSequence (std::initializer_list< int32_t > list)
Definition at line 30 of file OperandIndexSequence.cc.
{
  for (auto &&val : list)
  {
    _vec.emplace_back(static_cast<uint32_t>(val));
  }
}
OperandIndexSequence() [4/4]
onert::ir::OperandIndexSequence::OperandIndexSequence (std::initializer_list< uint32_t > list)
Definition at line 38 of file OperandIndexSequence.cc.
{
  for (auto &&val : list)
  {
    _vec.emplace_back(val);
  }
}
Member Function Documentation
append() [1/2]
void onert::ir::OperandIndexSequence::append (const OperandIndex & index) inline
Definition at line 43 of file OperandIndexSequence.h.
{ _vec.emplace_back(index); }
Referenced by onert::ir::Graph::addInput(), onert::ir::Graph::addOutput(), onert::loader::BaseLoader< LoaderDomain >::loadOperationIO(), operator+(), operator|(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), and onert::backend::basic::planTensors().
append() [2/2]
void onert::ir::OperandIndexSequence::append (const OperandIndexSequence & l) inline
Definition at line 44 of file OperandIndexSequence.h.
{ _vec.insert(_vec.end(), l.begin(), l.end()); }
at() [1/2]
const OperandIndex & onert::ir::OperandIndexSequence::at (IOIndex set_index) const inline
Definition at line 48 of file OperandIndexSequence.h.
{ return _vec.at(set_index.value()); }
References onert::util::Index< T, DummyTag >::value().
Referenced by onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), onert::backend::cpu::findSharedMemoryOperandIndexes(), onert::backend::acl_common::kernelGenFullyConnected(), onert::backend::acl_common::kernelGenLSTM(), onert::compiler::train::pass::LossInsertionPass::run(), onert::compiler::pass::PermutationIOPass::run(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_common::AclConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::acl_common::AclSubTensorAnalyzer::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::acl_neon::ConstantInitializer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), and onert::ir::train::UseDefGenerator::visit().
at() [2/2]
const OperandIndex & onert::ir::OperandIndexSequence::at (uint32_t index) const inline
Definition at line 49 of file OperandIndexSequence.h.
{ return _vec.at(index); }
begin() [1/2]
std::vector< OperandIndex >::iterator onert::ir::OperandIndexSequence::begin (void) inline
Definition at line 84 of file OperandIndexSequence.h.
{ return _vec.begin(); }
begin() [2/2]
std::vector< OperandIndex >::const_iterator onert::ir::OperandIndexSequence::begin (void) const inline
Definition at line 82 of file OperandIndexSequence.h.
{ return _vec.begin(); }
contains()
bool onert::ir::OperandIndexSequence::contains (const OperandIndex & index) const
Definition at line 46 of file OperandIndexSequence.cc.
{
  return std::find(_vec.begin(), _vec.end(), index) != _vec.end();
}
Referenced by onert::compiler::pass::ConstantOutputPass::callback(), onert::exec::DataflowExecutor::DataflowExecutor(), operator|(), onert::compiler::pass::OddOutputPass::run(), and onert::backend::acl_common::AclSubTensorAnalyzer::visit().
end() [1/2]
std::vector< OperandIndex >::iterator onert::ir::OperandIndexSequence::end (void) inline
Definition at line 85 of file OperandIndexSequence.h.
{ return _vec.end(); }
end() [2/2]
std::vector< OperandIndex >::const_iterator onert::ir::OperandIndexSequence::end (void) const inline
Definition at line 83 of file OperandIndexSequence.h.
{ return _vec.end(); }
operator+()
OperandIndexSequence onert::ir::OperandIndexSequence::operator+ (const OperandIndexSequence & other) const
Definition at line 61 of file OperandIndexSequence.cc.
{
  OperandIndexSequence ret = *this;
  ret.append(other);
  return ret;
}
References append().
operator==()
bool onert::ir::OperandIndexSequence::operator== (const OperandIndexSequence & other) const
Definition at line 56 of file OperandIndexSequence.cc.
{
  return _vec == other._vec;
}
operator|()
OperandIndexSequence onert::ir::OperandIndexSequence::operator| (ir::Remove filter) const inline
Definition at line 52 of file OperandIndexSequence.h.
  {
    switch (filter)
    {
      case ir::Remove::DUPLICATED:
      {
        ir::OperandIndexSequence seq;
        for (const auto &ind : _vec)
          if (!seq.contains(ind))
            seq.append(ind);
        return seq;
      }
      case ir::Remove::UNDEFINED:
      {
        ir::OperandIndexSequence seq;
        for (const auto &ind : _vec)
          if (!ind.undefined())
            seq.append(ind);
        return seq;
      }
    }
    return *this;
  }
References append(), contains(), onert::ir::DUPLICATED, and onert::ir::UNDEFINED.
replace()
void onert::ir::OperandIndexSequence::replace (const OperandIndex & from, const OperandIndex & to)
Definition at line 51 of file OperandIndexSequence.cc.
{
  std::replace(_vec.begin(), _vec.end(), from, to);
}
Referenced by onert::ir::Operation::replaceInputs(), onert::ir::Operation::replaceOutputs(), and onert::compiler::pass::OddOutputPass::run().
size()
uint32_t onert::ir::OperandIndexSequence::size () const inline
Definition at line 47 of file OperandIndexSequence.h.
{ return static_cast<uint32_t>(_vec.size()); }
Referenced by onert::ir::Graph::addInput(), onert::ir::Graph::addOutput(), onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), onert::exec::ExecutorBase::execute(), onert::backend::cpu::findSharedMemoryOperandIndexes(), onert::compiler::train::pass::LossInsertionPass::run(), onert::ir::Operation::setInputs(), onert::ir::Operation::setOutputs(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), and onert::ir::OperationValidator::visit().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & o, const OperandIndexSequence & operand_seq) friend
Definition at line 68 of file OperandIndexSequence.cc.
{
  std::string delimeter;
  for (const auto &ind : operand_seq._vec)
  {
    o << delimeter << ind;
    delimeter = ',';
  }
  return o;
}
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/OperandIndexSequence.h
runtime/onert/core/src/ir/OperandIndexSequence.cc