ONE - On-device Neural Engine: coco::FeatureLayouts::BHWC Class Reference
coco::FeatureLayouts::BHWC Class Reference
BHWC Feature Layout.
#include <FeatureLayouts.h>
Public Member Functions
const FeatureLayout::ID * id (void) const override
const FeatureShape & shape (void) const override
coco::ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override
Public Member Functions inherited from coco::FeatureLayout
virtual ~FeatureLayout ()=default
virtual const ID * id (void) const =0
virtual const FeatureShape & shape (void) const =0
uint32_t batch (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
virtual ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const FeatureLayout::ID * uid (void)
static std::unique_ptr< BHWC > create (const nncc::core::ADT::feature::Shape &shape)
static std::unique_ptr< BHWC > create (const FeatureShape &shape)
Detailed Description
BHWC Feature Layout.
Definition at line 61 of file FeatureLayouts.h.
Member Function Documentation
at()
ElemID coco::FeatureLayouts::BHWC::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::FeatureLayout.
Definition at line 79 of file FeatureLayouts.cpp.
{
  static HWCLayout l;
  uint32_t offset = 0;
  offset += b * num_elements(_shape);
  offset += l.offset(_shape, ch, row, col);
  return ElemID{offset};
}
References nncc::core::ADT::feature::num_elements(), and offset().
create() [1/2]
std::unique_ptr< BHWC > coco::FeatureLayouts::BHWC::create (const FeatureShape & shape) static
Definition at line 96 of file FeatureLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<BHWC>{new BHWC{shape}};
}
References shape().
create() [2/2]
std::unique_ptr< BHWC > coco::FeatureLayouts::BHWC::create (const nncc::core::ADT::feature::Shape & shape) static
Definition at line 90 of file FeatureLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<BHWC>{new BHWC{FeatureShape{shape}}};
}
References shape().
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::build_activation().
id()
const FeatureLayout::ID * coco::FeatureLayouts::BHWC::id (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 71 of file FeatureLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
shape()
const FeatureShape & coco::FeatureLayouts::BHWC::shape (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 73 of file FeatureLayouts.h.
{ return _shape; }
Referenced by create().
uid()
const FeatureLayout::ID * coco::FeatureLayouts::BHWC::uid (void) static
Definition at line 70 of file FeatureLayouts.cpp.
{
  struct LayoutID final : public FeatureLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id(), and enco::reduce_identical_object().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/FeatureLayouts.h
compiler/coco/core/src/IR/FeatureLayouts.cpp