ONE - On-device Neural Engine: loco::Permutation< Domain::Feature > Class Reference
loco::Permutation< Domain::Feature > Class Reference
Mapping between Feature/Tensor Axis.
#include <PermutingCodec.h>
Public Member Functions
Permutation ()=default
bool mapped (const FeatureAxis &axis_f) const
Return whether a tensor axis is specified for a given feature axis.
TensorAxis axis (const FeatureAxis &axis_f) const
Get the tensor axis corresponding to a given feature axis.
TensorAxis & axis (const FeatureAxis &axis_f)
Set the tensor axis corresponding to a given feature axis.
TensorAxis operator[] (const FeatureAxis &axis_f) const
TensorAxis & operator[] (const FeatureAxis &axis_f)
Detailed Description
Mapping between Feature/Tensor Axis.
Definition at line 44 of file PermutingCodec.h.
Constructor & Destructor Documentation
Permutation()
loco::Permutation< Domain::Feature >::Permutation () default
Member Function Documentation
axis() [1/2]
uint32_t & loco::Permutation< Domain::Feature >::axis (const FeatureAxis & axis_f)
Set the tensor axis corresponding to a given feature axis.
Definition at line 100 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid feature axis");
  return _map[axis_f];
}
References loco::valid().
axis() [2/2]
uint32_t loco::Permutation< Domain::Feature >::axis (const FeatureAxis & axis_f) const
Get the tensor axis corresponding to a given feature axis.
This method works correclty only when feature axis is mapped before.
Definition at line 93 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid feature axis");
  assert(mapped(axis_f) && "unmapped feature axis");
  return _map.at(axis_f);
}
References loco::valid().
mapped()
bool loco::Permutation< Domain::Feature >::mapped (const FeatureAxis & axis_f) const
Return whether a tensor axis is specified for a given feature axis.
This method does not validate the corresponding value.
Definition at line 87 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid feature axis");
  return _map.find(axis_f) != _map.end();
}
References loco::valid().
operator[]() [1/2]
TensorAxis & loco::Permutation< Domain::Feature >::operator[] (const FeatureAxis & axis_f) inline
Definition at line 70 of file PermutingCodec.h.
{ return axis(axis_f); }
operator[]() [2/2]
TensorAxis loco::Permutation< Domain::Feature >::operator[] (const FeatureAxis & axis_f) const inline
Definition at line 69 of file PermutingCodec.h.
{ return axis(axis_f); }
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp