ONE - On-device Neural Engine: loco::Pull Class Reference
loco::Pull Class Reference final
Create a value from user data.
#include <Nodes.h>
Public Member Functions
Pull ()=default
void index (const GraphInputIndex &index)
GraphInputIndex index (void) const
Get associated input index.
bool indexed (void) const
Check whether index is initialized.
void dtype (const DataType &d)
DataType dtype (void) const
Public Member Functions inherited from loco::CanonicalNodeDef< CanonicalOpcode::Pull, FixedArity< 0 >::Mixin, With< NodeTrait::TensorShape >::Mixin >
virtual ~CanonicalNodeDef ()=default
uint32_t opnum (void) const final
CanonicalOpcode opcode (void) const final
Public Member Functions inherited from loco::CanonicalNode
virtual ~CanonicalNode ()=default
const Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CanonicalOpcode opcode (void) const =0
template<typename T >
T accept (CanonicalNodeVisitorBase< T > *) const
template<typename T >
T accept (CanonicalNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Create a value from user data.
Definition at line 93 of file Nodes.h.
Constructor & Destructor Documentation
Pull()
loco::Pull::Pull () default
Member Function Documentation
dtype() [1/2]
void loco::Pull::dtype (const DataType & d)
Definition at line 129 of file Nodes.cpp.
{
  // ASSUMPTION: "dtype" is never invalidated!
  assert(dt != loco::DataType::Unknown);
  // ASSUMPTION
  //
  // It is possible to update index multiple times, but only with the same value!
  if (indexed())
  {
    assert(dtype_assignable(graph()->inputs()->at(_index)->dtype(), dt));
    graph()->inputs()->at(_index)->dtype(dt);
    return;
  }
  // Use local cache
  _dtype = dt;
}
References loco::ObjectPool< T >::at(), loco::Mixin< Trait::DataTyped >::dtype(), dtype(), loco::Node::graph(), indexed(), and loco::Graph::inputs().
dtype() [2/2]
DataType loco::Pull::dtype (void) const
Definition at line 147 of file Nodes.cpp.
{
  if (graph() != nullptr and _index >= 0)
  {
    assert(_dtype == DataType::Unknown);
    return graph()->inputs()->at(_index)->dtype();
  }
  else
  {
    return _dtype;
  }
}
References loco::ObjectPool< T >::at(), loco::Mixin< Trait::DataTyped >::dtype(), loco::Node::graph(), and loco::Graph::inputs().
Referenced by dtype(), and index().
index() [1/2]
void loco::Pull::index (const GraphInputIndex & index)
Definition at line 90 of file Nodes.cpp.
{
  // ASSUMPTION
  //
  // It is possible to update index multiple times, but only with the same value!
  assert(!indexed() or _index == index);
  if (indexed())
  {
    assert(_index == index);
    return;
  }
  // Push internally stores "GraphInputIndex" as int64_t
  _index = static_cast<int64_t>(index);
  // ASSUMPTION: The return value of graph() never changes!
  if (graph() != nullptr && _dtype != loco::DataType::Unknown)
  {
    // Update Graph-level input only if it is not yet specified
    if (graph()->inputs()->at(_index)->dtype() == DataType::Unknown)
    {
      graph()->inputs()->at(_index)->dtype(_dtype);
    }
    assert(graph()->inputs()->at(_index)->dtype() == _dtype);
    graph()->inputs()->at(_index)->dtype(_dtype);
    // Reset the locally cached data
    _dtype = DataType::Unknown;
  }
}
References loco::ObjectPool< T >::at(), loco::Mixin< Trait::DataTyped >::dtype(), dtype(), loco::Node::graph(), index(), indexed(), and loco::Graph::inputs().
Referenced by GraphTestcase< GraphCode::AvgPool2D >::GraphTestcase(), GraphTestcase< GraphCode::MaxPool2D >::GraphTestcase(), GraphTestcase< GraphCode::TensorConcat >::GraphTestcase(), GraphTestcase< GraphCode::TensorTranspose >::GraphTestcase(), loco::link(), and InputLayer::operator()().
index() [2/2]
GraphInputIndex loco::Pull::index (void) const
Get associated input index.
The behavior of this method is undefined when "index" is not set before.
NOTE This method intentionally returns "GraphInputIndex" instead of "const GraphInputIndex &" not to expose the internal implementation details.
Definition at line 122 of file Nodes.cpp.
{
  assert(_index >= std::numeric_limits<GraphInputIndex>::min());
  assert(_index <= std::numeric_limits<GraphInputIndex>::max());
  return static_cast<GraphInputIndex>(_index);
}
Referenced by index().
indexed()
bool loco::Pull::indexed (void) const inline
Check whether index is initialized.
NOTE "indexed" method does not validate whether index is in a valid range
Definition at line 118 of file Nodes.h.
{ return _index != -1; }
Referenced by dtype(), and index().
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/Nodes.h
compiler/loco/src/IR/Nodes.cpp