ONE - On-device Neural Engine: coco::Object Class Reference
coco::Object Class Reference
Base interface on all typed NN values.
#include <Object.h>
Data Structures
struct Consumer
struct Producer
Public Types
enum class Kind { Unknown , Feature , Kernel }
using ConsumerSet = std::set< Consumer * >
Public Member Functions
Object ()
virtual ~Object ()=default
virtual Kind kind (void) const
coco::Bag * bag (void) const
void bag (coco::Bag *bag)
virtual FeatureObject * asFeature (void)
virtual const FeatureObject * asFeature (void) const
virtual KernelObject * asKernel (void)
virtual const KernelObject * asKernel (void) const
Def * def (void) const
const UseSet * uses (void) const
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Friends
class Def
class Use
Detailed Description
Base interface on all typed NN values.
Definition at line 37 of file Object.h.
Member Typedef Documentation
ConsumerSet
using coco::Object::ConsumerSet = std::set<Consumer *>
Definition at line 62 of file Object.h.
Member Enumeration Documentation
Kind
enum class coco::Object::Kind strong
Enumerator
Unknown
Feature
Kernel
Definition at line 44 of file Object.h.
  {
    Unknown,
    Feature,
    Kernel,
  };
Constructor & Destructor Documentation
Object()
coco::Object::Object ()
Definition at line 27 of file Object.cpp.
{
  // Register self to Dep
  _dep.object(this);
}
References coco::Dep::object().
~Object()
virtual coco::Object::~Object () virtual default
Member Function Documentation
asFeature() [1/2]
virtual FeatureObject * coco::Object::asFeature (void) inline virtual
Reimplemented in coco::FeatureObject.
Definition at line 78 of file Object.h.
{ return nullptr; }
Referenced by coco::cast(), dump(), coco::isa< FeatureObject >(), and coco::safe_cast().
asFeature() [2/2]
virtual const FeatureObject * coco::Object::asFeature (void) const inline virtual
Reimplemented in coco::FeatureObject.
Definition at line 79 of file Object.h.
{ return nullptr; }
asKernel() [1/2]
virtual KernelObject * coco::Object::asKernel (void) inline virtual
Reimplemented in coco::KernelObject.
Definition at line 81 of file Object.h.
{ return nullptr; }
Referenced by coco::cast(), dump(), coco::isa< KernelObject >(), and coco::safe_cast().
asKernel() [2/2]
virtual const KernelObject * coco::Object::asKernel (void) const inline virtual
Reimplemented in coco::KernelObject.
Definition at line 82 of file Object.h.
{ return nullptr; }
bag() [1/2]
void coco::Object::bag (coco::Bag * bag) inline
Definition at line 75 of file Object.h.
{ _dep.bag(bag); }
References coco::Dep::bag(), and bag().
bag() [2/2]
coco::Bag * coco::Object::bag (void) const inline
Definition at line 74 of file Object.h.
{ return _dep.bag(); }
References coco::Dep::bag().
Referenced by bag(), caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), and tflimport::SubGraphBuilder::build().
def()
Def * coco::Object::def (void) const
Definition at line 33 of file Object.cpp.
{ return _def; }
Referenced by coco::ObjectManager::destroy(), and coco::Def::value().
kind()
virtual Kind coco::Object::kind (void) const inline virtual
Reimplemented in coco::FeatureObject, and coco::KernelObject.
Definition at line 71 of file Object.h.
{ return Kind::Unknown; }
References Unknown.
uses()
const UseSet * coco::Object::uses (void) const
Definition at line 52 of file Object.cpp.
{ return &_uses; }
Referenced by coco::ObjectManager::destroy(), and enco::subst().
Friends And Related Function Documentation
Def
friend class Def friend
Definition at line 40 of file Object.h.
Use
friend class Use friend
Definition at line 41 of file Object.h.
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Object.h
compiler/coco/core/src/IR/Object.cpp