ONE - On-device Neural Engine: nnfw::misc::tensor::Comparator Class Reference
nnfw::misc::tensor::Comparator Class Reference
Class to compare two tensors (expected and obtained to compare)
#include <Comparator.h>
Data Structures
struct Observer
Struct to observe comparison results.
Public Member Functions
Comparator (const std::function< bool(float lhs, float rhs)> &fn)
Construct a new Comparator object.
std::vector< Diff< float > > compare (const Shape &shape, const Reader< float > &expected, const Reader< float > &obtained, Observer *observer=nullptr) const
Compare two tensors.
Detailed Description
Class to compare two tensors (expected and obtained to compare)
Definition at line 45 of file Comparator.h.
Constructor & Destructor Documentation
Comparator()
nnfw::misc::tensor::Comparator::Comparator (const std::function< bool(float lhs, float rhs)> & fn) inline
Construct a new Comparator object.
Parameters
[in] fn Function that compares two float values
Definition at line 52 of file Comparator.h.
                                                                : _compare_fn{fn}
  {
    // DO NOTHING
  }
Member Function Documentation
compare()
std::vector< Diff< float > > nnfw::misc::tensor::Comparator::compare (const Shape & shape, const Reader< float > & expected, const Reader< float > & obtained, Observer * observer = nullptr) const
Compare two tensors.
Parameters
[in] shape Shape of two tensors
[in] expected Reader<float> object that accesses expected tensor
[in] obtained Reader<float> object that accesses obtained tensor
[in] observer Observer notified of expected value and obtained value at every index
Returns
std::vector<Diff<float>> containing information of failed comparison
Definition at line 29 of file Comparator.cpp.
{
  std::vector<Diff<float>> res;
  zip(shape, expected, obtained) <<
    [&](const Index &index, float expected_value, float obtained_value) {
      if (!_compare_fn(expected_value, obtained_value))
      {
        res.emplace_back(index, expected_value, obtained_value);
      }
      // Update max_diff_index, if necessary
      if (observer != nullptr)
      {
        observer->notify(index, expected_value, obtained_value);
      }
    };
  return res;
}
References nnfw::misc::tensor::Comparator::Observer::notify(), and nnfw::misc::tensor::zip().
Referenced by TfLiteInterpMatchApp::compareSingleTensorView().
The documentation for this class was generated from the following files:
runtime/libs/misc/include/misc/tensor/Comparator.h
runtime/libs/misc/src/tensor/Comparator.cpp