ONE - On-device Neural Engine: onert::backend::cpu::ops::EinsumLayer Class Reference
onert::backend::cpu::ops::EinsumLayer Class Reference
#include <EinsumLayer.h>
Public Member Functions
EinsumLayer ()
~EinsumLayer ()
void einsumFloat32 ()
void configure (const std::vector< const IPortableTensor * > &inputs, std::string equation, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 44 of file EinsumLayer.h.
Constructor & Destructor Documentation
EinsumLayer()
onert::backend::cpu::ops::EinsumLayer::EinsumLayer ()
Definition at line 30 of file EinsumLayer.cc.
  : _inputs(), _output(nullptr), _equation(), _einsum_kernel(new nnfw::cker::Einsum())
{
  // DO NOTHING
}
~EinsumLayer()
onert::backend::cpu::ops::EinsumLayer::~EinsumLayer () default
Member Function Documentation
configure()
void onert::backend::cpu::ops::EinsumLayer::configure (const std::vector< const IPortableTensor * > & inputs, std::string equation, IPortableTensor * output)
Definition at line 69 of file EinsumLayer.cc.
{
  assert(inputs.size() > 0);
  assert(output != nullptr);
  _inputs = inputs;
  _equation = equation;
  _output = output;
}
einsumFloat32()
void onert::backend::cpu::ops::EinsumLayer::einsumFloat32 ()
Definition at line 38 of file EinsumLayer.cc.
{
  uint32_t num_inputs = _inputs.size();
  nnfw::cker::Einsum &kernel = *_einsum_kernel;
  kernel.prepare(_equation);
  std::vector<nnfw::cker::Shape> inputShapes;
  std::vector<const float *> inputFloatPtrs;
  for (uint32_t i = 0; i < num_inputs; i++)
  {
    inputShapes.emplace_back(getShape(_inputs[i]));
    inputFloatPtrs.emplace_back(getBuffer<float>(_inputs[i]));
  }
  kernel(_equation, inputShapes, inputFloatPtrs, getShape(_output), getBuffer<float>(_output));
}
References onert::backend::cpu::ops::getShape(), and nnfw::cker::Einsum::prepare().
Referenced by run().
run()
void onert::backend::cpu::ops::EinsumLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 57 of file EinsumLayer.cc.
{
  if (_output->data_type() == OperandType::FLOAT32)
  {
    einsumFloat32();
  }
  else
  {
    throw std::runtime_error{"Einsum: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), and einsumFloat32().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/EinsumLayer.h
runtime/onert/backend/cpu/ops/EinsumLayer.cc