ONE - On-device Neural Engine: coco::Block Class Reference
coco::Block Class Reference final
A unit of (grouped) instructions.
#include <Block.h>
Public Member Functions
Block ()
Block (const Block &)=delete
Block (Block &&)=delete
~Block ()
InstrList * instr (void)
const InstrList * instr (void) const
const BlockIndex & index (void) const
Public Member Functions inherited from coco::DLinkedList< Child, Parent >::Node
Node ()
virtual ~Node ()
Parent * parent (void) const
Child * prev (void) const
Child * next (void) const
void insertBefore (Node *next)
void insertAfter (Node *prev)
void detach (void)
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Friends
void DLinkedList (Module *, Block *)
void DLinkedList (Module *, Block *)
Detailed Description
A unit of (grouped) instructions.
Block allows backend to manage a set of instructions as one unit, which is useful for H/W that has a restriction on code size
Definition at line 39 of file Block.h.
Constructor & Destructor Documentation
Block() [1/3]
coco::Block::Block () inline
Definition at line 46 of file Block.h.
          : _instr{this}
  {
    // DO NOTHING
  }
Block() [2/3]
coco::Block::Block (const Block &) delete
Block() [3/3]
coco::Block::Block (Block &&) delete
~Block()
coco::Block::~Block () inline
Definition at line 56 of file Block.h.
  {
    if (parent())
    {
      detach();
    }
  }
References coco::DLinkedList< Child, Parent >::Node::detach(), and coco::DLinkedList< Child, Parent >::Node::parent().
Member Function Documentation
index()
const BlockIndex & coco::Block::index (void) const inline
Definition at line 69 of file Block.h.
{ return _index; }
Referenced by dump(), coco::DLinkedList< Child, Parent >::joined(), and coco::DLinkedList< Child, Parent >::leaving().
instr() [1/2]
InstrList * coco::Block::instr (void) inline
Definition at line 65 of file Block.h.
{ return &_instr; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::build_activation(), enco::HostBlockCompiler::compile(), and dump().
instr() [2/2]
const InstrList * coco::Block::instr (void) const inline
Definition at line 66 of file Block.h.
{ return &_instr; }
Friends And Related Function Documentation
DLinkedList [1/2]
void DLinkedList (Module * , Block *) friend
DLinkedList [2/2]
void DLinkedList (Module * , Block *) friend
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/IR/Block.h