ONE - On-device Neural Engine: onert::backend::acl_common::AclSubTensorAnalyzer Class Reference
onert::backend::acl_common::AclSubTensorAnalyzer Class Reference
Class to analyze tensor subsumption.
#include <AclSubTensorAnalyzer.h>
Public Member Functions
AclSubTensorAnalyzer (const ir::Graph &graph)
Construct a new SubTensorAnalyzer object.
void setLayout (ir::Layout layout)
void setUsePadding ()
void visit (const ir::operation::Concat &node) override
std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > && releaseParentMap ()
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Detailed Description
Class to analyze tensor subsumption.
Definition at line 35 of file AclSubTensorAnalyzer.h.
Constructor & Destructor Documentation
AclSubTensorAnalyzer()
onert::backend::acl_common::AclSubTensorAnalyzer::AclSubTensorAnalyzer (const ir::Graph & graph) inline
Construct a new SubTensorAnalyzer object.
Parameters
[in] ctx Graph operand set
Definition at line 42 of file AclSubTensorAnalyzer.h.
                                             : _graph{graph}
  {
    // DO NOTHING
  }
Member Function Documentation
releaseParentMap()
std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > && onert::backend::acl_common::AclSubTensorAnalyzer::releaseParentMap () inline
Definition at line 105 of file AclSubTensorAnalyzer.h.
  {
    return std::move(_parent_map);
  }
setLayout()
void onert::backend::acl_common::AclSubTensorAnalyzer::setLayout (ir::Layout layout) inline
Definition at line 48 of file AclSubTensorAnalyzer.h.
{ _current_op_layout = layout; }
setUsePadding()
void onert::backend::acl_common::AclSubTensorAnalyzer::setUsePadding () inline
Definition at line 50 of file AclSubTensorAnalyzer.h.
{ usePadding = true; }
visit()
void onert::backend::acl_common::AclSubTensorAnalyzer::visit (const ir::operation::Concat & node) inline override
NOTE Not support below cases.
concat's input is a constant.
concat's input is a input of model.
concat's input already becomes a subtensor of another concat.
Definition at line 52 of file AclSubTensorAnalyzer.h.
  {
    //  If operator is concat, fill subsumption info
    int32_t axis_raw = node.param().axis;
    const auto &output_index = node.getOutputs().at(0);
    const auto &inputs = node.getInputs();
    int32_t axis_point = 0;
    const auto rank = _graph.operands().at(output_index).shape().rank();
    int32_t axis = axis_raw < 0 ? (axis_raw + rank) : axis_raw;
    assert(rank > axis);
    // Concat elimination when axis is last dimension is not supported
    // https://github.com/Samsung/ONE/issues/4407
    // TODO Enable if backend don't use padding
    if ((axis == rank - 1) && usePadding)
      return;
    for (const auto &ind : inputs)
    {
      if (_graph.operands().at(ind).isConstant() || _graph.getInputs().contains(ind) ||
          _parent_map.find(ind) != _parent_map.end())
      {
        return;
      }
    }
    for (const auto &input_index : inputs)
    {
      auto input_shape = _graph.operands().at(input_index).shape();
      assert(rank == input_shape.rank());
      ir::Coordinates coordinate_info{};
      for (int i = 0; i < rank; i++)
      {
        coordinate_info.set(i, 0);
      }
      coordinate_info.set(axis, axis_point);
      _parent_map.emplace(input_index,
                          cl_common::ParentInfo{output_index, _current_op_layout, coordinate_info});
      axis_point += input_shape.dim(axis);
    }
  }
References onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::Concat::Param::axis, onert::ir::OperandIndexSequence::contains(), onert::ir::Operation::getInputs(), onert::ir::Graph::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Graph::operands(), onert::ir::operation::Concat::param(), and onert::ir::Coordinates::set().
The documentation for this class was generated from the following file:
runtime/onert/backend/acl_common/AclSubTensorAnalyzer.h