ONE - On-device Neural Engine: nnc::Serializer Class Reference
nnc::Serializer Class Reference
Serializer of network parameters for soft backend.
#include <SBSerializer.h>
Public Member Functions
void visit (mir::ops::AbsOp &op) override
void visit (mir::ops::AddOp &op) override
void visit (mir::ops::AvgPool2DOp &op) override
void visit (mir::ops::BroadcastOp &op) override
void visit (mir::ops::CappedReluOp &op) override
void visit (mir::ops::ConcatOp &op) override
void visit (mir::ops::ConstantOp &op) override
void visit (mir::ops::Conv2DOp &op) override
void visit (mir::ops::DeConv2DOp &op) override
void visit (mir::ops::DepthwiseConv2DOp &op) override
void visit (mir::ops::DivOp &op) override
void visit (mir::ops::EluOp &op) override
void visit (mir::ops::FullyConnectedOp &op) override
void visit (mir::ops::GatherOp &op) override
void visit (mir::ops::InputOp &op) override
void visit (mir::ops::LeakyReluOp &op) override
void visit (mir::ops::MaxOp &op) override
void visit (mir::ops::MaxPool2DOp &op) override
void visit (mir::ops::MulOp &op) override
void visit (mir::ops::OutputOp &op) override
void visit (mir::ops::PadOp &op) override
void visit (mir::ops::ReduceMeanOp &op) override
void visit (mir::ops::ReluOp &op) override
void visit (mir::ops::ReshapeOp &op) override
void visit (mir::ops::ResizeOp &op) override
void visit (mir::ops::SigmoidOp &op) override
void visit (mir::ops::SliceOp &op) override
void visit (mir::ops::SoftmaxOp &op) override
void visit (mir::ops::SqrtOp &op) override
void visit (mir::ops::SqueezeOp &op) override
void visit (mir::ops::SubOp &op) override
void visit (mir::ops::TanhOp &op) override
void visit (mir::ops::TransposeOp &op) override
void serialize (std::vector< std::unique_ptr< sir::Action > > &inference_sequence)
const std::vector< char > & getBuffer () const
uint32_t getFormatVersion () const
uint32_t getModelHash () const
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Protected Member Functions
void visit_fallback (mir::Operation &op) override
virtual void visit_fallback (Operation &)
Detailed Description
Serializer of network parameters for soft backend.
Serializer class responsible for serialization of given computational graph parameters and binding of inference operations to this data. It owns buffer that contains serialized data. To serialize data serialize method should be called with sequence from ModelAnalyzer object To gather this vector use getBuffer method. Objects of this class are one-off and not designed to serialize more than one IR
Definition at line 41 of file SBSerializer.h.
Member Function Documentation
getBuffer()
const std::vector< char > & nnc::Serializer::getBuffer () const inline
Definition at line 80 of file SBSerializer.h.
{ return _buffer; }
getFormatVersion()
uint32_t nnc::Serializer::getFormatVersion () const inline
Definition at line 82 of file SBSerializer.h.
{ return _formatVersion; }
getModelHash()
uint32_t nnc::Serializer::getModelHash () const inline
Definition at line 84 of file SBSerializer.h.
{ return _modelHash; }
serialize()
void nnc::Serializer::serialize (std::vector< std::unique_ptr< sir::Action > > & inference_sequence)
Definition at line 355 of file SBSerializer.cpp.
{
  for (unique_ptr<sir::Action> &action : inference_sequence)
  {
    if (action->type != sir::Action::Type::callFunction)
      continue;
    _curOp = dynamic_cast<sir::CallFunction *>(action.get());
    _curOp->mirOp->accept(this);
  }
}
References mir::Operation::accept(), nnc::sir::Action::callFunction, and nnc::sir::CallFunction::mirOp.
Referenced by nnc::CPPCodeGenerator::run().
visit() [1/33]
void nnc::Serializer::visit (mir::ops::AbsOp & op) override
Definition at line 371 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // no parameters to dump
}
References nnc::sir::CallFunction::paramStartOffset.
visit() [2/33]
void nnc::Serializer::visit (mir::ops::AddOp & op) override
Definition at line 377 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Op type is known at codegen Time
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [3/33]
void nnc::Serializer::visit (mir::ops::AvgPool2DOp & op) override
Definition at line 170 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize window shape
  serializeShape(Shape(op.getWindowSize()));
  // serialize strindes
  serializeStrides(op.getStrides());
  // serialize pads
  int32_t number_of_pads = 2; // windowShape.rank();
  serializePads(op, number_of_pads);
  serializeT<int32_t>(op.getIncludePad());
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::ops::AvgPool2DOp::getIncludePad(), mir::Operation::getOutputShape(), mir::ops::AvgPool2DOp::getStrides(), mir::ops::AvgPool2DOp::getWindowSize(), and nnc::sir::CallFunction::paramStartOffset.
visit() [4/33]
void nnc::Serializer::visit (mir::ops::BroadcastOp & op) override
Definition at line 205 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [5/33]
void nnc::Serializer::visit (mir::ops::CappedReluOp & op) override
Definition at line 211 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeT<float>(op.getCap());
}
References mir::ops::CappedReluOp::getCap(), and nnc::sir::CallFunction::paramStartOffset.
visit() [6/33]
void nnc::Serializer::visit (mir::ops::ConcatOp & op) override
Definition at line 129 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // axis number should fit into one byte
  assert(op.getAxis() <= MAX_DIMS);
  serializeT<int32_t>(op.getAxis());
  serializeShape(op.getOutputShape(0));
}
References mir::ops::ConcatOp::getAxis(), mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [7/33]
void nnc::Serializer::visit (mir::ops::ConstantOp & op) override
Definition at line 222 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeTensor(op.getValue());
}
References mir::ops::ConstantOp::getValue(), and nnc::sir::CallFunction::paramStartOffset.
visit() [8/33]
void nnc::Serializer::visit (mir::ops::Conv2DOp & op) override
Definition at line 138 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize strides
  serializeStrides(op.getStrides());
  // serialize pads
  int32_t padsRank = 2; // op.getInputShape(0).rank();
  serializePads(op, padsRank);
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), mir::ops::Conv2DOp::getStrides(), and nnc::sir::CallFunction::paramStartOffset.
visit() [9/33]
void nnc::Serializer::visit (mir::ops::DeConv2DOp & op) override
Definition at line 260 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize strides
  serializeStrides(op.getStrides());
  // serialize pads
  int32_t number_of_pads = 2; // op.getInputShape(0).rank();
  serializePads(op, number_of_pads);
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), mir::ops::DeConv2DOp::getStrides(), and nnc::sir::CallFunction::paramStartOffset.
visit() [10/33]
void nnc::Serializer::visit (mir::ops::DepthwiseConv2DOp & op) override
Definition at line 150 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize strides
  serializeStrides(op.getStrides());
  // serialize pads
  int32_t padsRank = 2; // kernel.getShape().rank();
  serializePads(op, padsRank);
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), mir::ops::DepthwiseConv2DOp::getStrides(), and nnc::sir::CallFunction::paramStartOffset.
visit() [11/33]
void nnc::Serializer::visit (mir::ops::DivOp & op) override
Definition at line 384 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Op type is known at codegen Time
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [12/33]
void nnc::Serializer::visit (mir::ops::EluOp & op) override
Definition at line 254 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeT<float>(op.getAlpha());
}
References mir::ops::EluOp::getAlpha(), and nnc::sir::CallFunction::paramStartOffset.
visit() [13/33]
void nnc::Serializer::visit (mir::ops::FullyConnectedOp & op) override
Definition at line 199 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [14/33]
void nnc::Serializer::visit (mir::ops::GatherOp & op) override
Definition at line 337 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize parameters
  serializeT<int32_t>(op.getAxis());
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::ops::GatherOp::getAxis(), mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [15/33]
void nnc::Serializer::visit (mir::ops::InputOp & op) override
Definition at line 217 of file SBSerializer.cpp.
{
  // no parameters to dump
}
visit() [16/33]
void nnc::Serializer::visit (mir::ops::LeakyReluOp & op) override
Definition at line 348 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeT<float>(op.getAlpha());
  serializeShape(op.getOutputShape(0));
}
References mir::ops::LeakyReluOp::getAlpha(), mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [17/33]
void nnc::Serializer::visit (mir::ops::MaxOp & op) override
Definition at line 391 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Op type is known at codegen Time
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [18/33]
void nnc::Serializer::visit (mir::ops::MaxPool2DOp & op) override
Definition at line 185 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize window shape
  serializeShape(Shape(op.getWindowSize()));
  // serialize strindes
  serializeStrides(op.getStrides());
  // serialize pads
  int32_t number_of_pads = 2; // windowShape.rank();
  serializePads(op, number_of_pads);
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), mir::ops::MaxPool2DOp::getStrides(), mir::ops::MaxPool2DOp::getWindowSize(), and nnc::sir::CallFunction::paramStartOffset.
visit() [19/33]
void nnc::Serializer::visit (mir::ops::MulOp & op) override
Definition at line 398 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Op type is known at codegen Time
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [20/33]
void nnc::Serializer::visit (mir::ops::OutputOp & op) override
Definition at line 366 of file SBSerializer.cpp.
{
  // no parameters to dump
}
visit() [21/33]
void nnc::Serializer::visit (mir::ops::PadOp & op) override
Definition at line 278 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serialize paddings
  const int num_dims = op.getInputShape(0).rank();
  // serialize output shape
  serializeShape(op.getOutputShape(0));
  // serialize num dimensions
  serializeT<int32_t>(num_dims);
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  for (int i = 0; i < num_dims; i++)
  {
    serializeT<int32_t>(padding_before[num_dims - 1 - i]);
    serializeT<int32_t>(padding_after[num_dims - 1 - i]);
  }
  // FIXME Make use of padding value.
  assert(op.getPaddingValue() == 0.0f);
}
References mir::Operation::getInputShape(), mir::Operation::getOutputShape(), mir::ops::PadOp::getPaddingAfter(), mir::ops::PadOp::getPaddingBefore(), mir::ops::PadOp::getPaddingValue(), nnc::sir::CallFunction::paramStartOffset, and mir::Shape::rank().
visit() [22/33]
void nnc::Serializer::visit (mir::ops::ReduceMeanOp & op) override
Definition at line 316 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(Shape(op.getReductionDims())); // reuse shape serialization
  serializeT<int32_t>(op.getKeepDims());
  serializeShape(op.getOutputShape(0));
}
References mir::ops::ReduceOp::getKeepDims(), mir::Operation::getOutputShape(), mir::ops::ReduceOp::getReductionDims(), and nnc::sir::CallFunction::paramStartOffset.
visit() [23/33]
void nnc::Serializer::visit (mir::ops::ReluOp & op) override
Definition at line 228 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // no parameters to dump
}
References nnc::sir::CallFunction::paramStartOffset.
visit() [24/33]
void nnc::Serializer::visit (mir::ops::ReshapeOp & op) override
Definition at line 234 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [25/33]
void nnc::Serializer::visit (mir::ops::ResizeOp & op) override
Definition at line 309 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Result shape is the same as Output shape
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [26/33]
void nnc::Serializer::visit (mir::ops::SigmoidOp & op) override
Definition at line 346 of file SBSerializer.cpp.
{ _curOp->paramStartOffset = _buffer.size(); }
References nnc::sir::CallFunction::paramStartOffset.
visit() [27/33]
void nnc::Serializer::visit (mir::ops::SliceOp & op) override
Definition at line 240 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(op.getStarts());
  serializeShape(op.getSizes());
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), mir::ops::SliceOp::getSizes(), mir::ops::SliceOp::getStarts(), and nnc::sir::CallFunction::paramStartOffset.
visit() [28/33]
void nnc::Serializer::visit (mir::ops::SoftmaxOp & op) override
Definition at line 162 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // axis number should fit into one byte
  assert(op.getAxis() <= MAX_DIMS);
  serializeT<int32_t>(op.getAxis());
}
References mir::ops::SoftmaxOp::getAxis(), and nnc::sir::CallFunction::paramStartOffset.
visit() [29/33]
void nnc::Serializer::visit (mir::ops::SqrtOp & op) override
Definition at line 303 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // no parameters to dump
}
References nnc::sir::CallFunction::paramStartOffset.
visit() [30/33]
void nnc::Serializer::visit (mir::ops::SqueezeOp & op) override
Definition at line 272 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [31/33]
void nnc::Serializer::visit (mir::ops::SubOp & op) override
Definition at line 405 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // Op type is known at codegen Time
  serializeShape(op.getOutputShape(0));
}
References mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit() [32/33]
void nnc::Serializer::visit (mir::ops::TanhOp & op) override
Definition at line 248 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // no parameters to dump
}
References nnc::sir::CallFunction::paramStartOffset.
visit() [33/33]
void nnc::Serializer::visit (mir::ops::TransposeOp & op) override
Definition at line 324 of file SBSerializer.cpp.
{
  _curOp->paramStartOffset = _buffer.size();
  // serializer parameters
  auto &axis_order = op.getAxisOrder();
  serializeT(static_cast<int32_t>(axis_order.size()));
  for (auto &axis : axis_order)
    serializeT(static_cast<int32_t>(axis));
  // serialize output shape
  serializeShape(op.getOutputShape(0));
}
References mir::ops::TransposeOp::getAxisOrder(), mir::Operation::getOutputShape(), and nnc::sir::CallFunction::paramStartOffset.
visit_fallback()
void nnc::Serializer::visit_fallback (mir::Operation & op) override protected virtual
Reimplemented from mir::Visitor.
Definition at line 412 of file SBSerializer.cpp.
{ throw std::runtime_error("NYI operation"); }
The documentation for this class was generated from the following files:
compiler/nnc/backends/soft_backend/SBSerializer.h
compiler/nnc/backends/soft_backend/SBSerializer.cpp