ONE - On-device Neural Engine: luci::CloneNode Class Reference
luci::CloneNode Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNode (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleBCQFullyConnected *) final
luci::CircleNode * visit (const luci::CircleBCQGather *) final
luci::CircleNode * visit (const luci::CircleInstanceNorm *) final
luci::CircleNode * visit (const luci::CircleCustomOut *) final
luci::CircleNode * visit (const luci::CircleIfOut *) final
luci::CircleNode * visit (const luci::CircleNonMaxSuppressionV4Out *) final
luci::CircleNode * visit (const luci::CircleNonMaxSuppressionV5Out *) final
luci::CircleNode * visit (const luci::CircleOutputDummy *) final
luci::CircleNode * visit (const luci::CircleOutputExclude *) final
luci::CircleNode * visit (const luci::CircleSplitOut *) final
luci::CircleNode * visit (const luci::CircleSplitVOut *) final
luci::CircleNode * visit (const luci::CircleTopKV2Out *) final
luci::CircleNode * visit (const luci::CircleUniqueOut *) final
luci::CircleNode * visit (const luci::CircleUnpackOut *) final
luci::CircleNode * visit (const luci::CircleVariable *) final
luci::CircleNode * visit (const luci::CircleWhileOut *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 246 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNode()
luci::CloneNode::CloneNode (loco::Graph * graph) inline
Definition at line 249 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleBCQFullyConnected * node) final
Definition at line 22 of file CircleBCQFullyConnected.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleBCQFullyConnected>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->weights_hidden_size(node->weights_hidden_size());
  }
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), loco::Graph::nodes(), luci::UNDEFINED, and luci::CircleBCQFullyConnected::weights_hidden_size().
visit() [2/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleBCQGather * node) final
Definition at line 22 of file CircleBCQGather.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleBCQGather>();
  if (cloned != nullptr)
  {
    cloned->axis(node->axis());
    cloned->input_hidden_size(node->input_hidden_size());
  }
  return cloned;
}
References _graph, luci::CircleBCQGather::axis(), loco::NodePool::create(), luci::CircleBCQGather::input_hidden_size(), and loco::Graph::nodes().
visit() [3/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleCustomOut * node) final
Definition at line 22 of file CircleCustomOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleCustomOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleCustomOut::index(), and loco::Graph::nodes().
visit() [4/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleIfOut * node) final
Definition at line 96 of file CircleIfOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleIfOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleIfOut::index(), and loco::Graph::nodes().
visit() [5/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleInstanceNorm * node) final
Definition at line 22 of file CircleInstanceNorm.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleInstanceNorm>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->epsilon(node->epsilon());
  }
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleInstanceNorm::epsilon(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), loco::Graph::nodes(), and luci::UNDEFINED.
visit() [6/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleNode *) final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 22 of file CircleCloneNode.cpp.
{
#define CNVISIT_GRP(GRP)              \
  {                                   \
    CloneNodeLet<CN::GRP> cn(_graph); \
    auto cloned = node->accept(&cn);  \
    if (cloned != nullptr)            \
      return cloned;                  \
  }
  CNVISIT_GRP(ABC);
  CNVISIT_GRP(DEF);
  CNVISIT_GRP(GHIJ);
  CNVISIT_GRP(KLMN);
  CNVISIT_GRP(OPQR);
  CNVISIT_GRP(STUV);
  CNVISIT_GRP(WXYZ);
#undef CNVISIT_GRP
  return nullptr;
}
References luci::ABC, CNVISIT_GRP, luci::DEF, luci::GHIJ, luci::KLMN, luci::OPQR, luci::STUV, and luci::WXYZ.
visit() [7/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleNonMaxSuppressionV4Out * node) final
Definition at line 22 of file CircleNonMaxSuppressionV4Out.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleNonMaxSuppressionV4Out>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleNonMaxSuppressionV4Out::index(), and loco::Graph::nodes().
visit() [8/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleNonMaxSuppressionV5Out * node) final
Definition at line 22 of file CircleNonMaxSuppressionV5Out.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleNonMaxSuppressionV5Out>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleNonMaxSuppressionV5Out::index(), and loco::Graph::nodes().
visit() [9/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleOutputDummy *) final
Definition at line 22 of file CircleOutputDummy.cpp.
{
  return _graph->nodes()->create<luci::CircleOutputDummy>();
}
References _graph, loco::NodePool::create(), and loco::Graph::nodes().
visit() [10/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleOutputExclude *) final
Definition at line 22 of file CircleOutputExclude.cpp.
{
  return _graph->nodes()->create<luci::CircleOutputExclude>();
}
References _graph, loco::NodePool::create(), and loco::Graph::nodes().
visit() [11/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleSplitOut * node) final
Definition at line 22 of file CircleSplitOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSplitOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleSplitOut::index(), and loco::Graph::nodes().
visit() [12/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleSplitVOut * node) final
Definition at line 22 of file CircleSplitVOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSplitVOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleSplitVOut::index(), and loco::Graph::nodes().
visit() [13/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleTopKV2Out * node) final
Definition at line 22 of file CircleTopKV2Out.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleTopKV2Out>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleTopKV2Out::index(), and loco::Graph::nodes().
visit() [14/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleUniqueOut * node) final
Definition at line 22 of file CircleUniqueOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleUniqueOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleUniqueOut::index(), and loco::Graph::nodes().
visit() [15/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleUnpackOut * node) final
Definition at line 22 of file CircleUnpackOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleUnpackOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleUnpackOut::index(), and loco::Graph::nodes().
visit() [16/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleVariable *) final
Definition at line 22 of file CircleVariable.cpp.
{
  return _graph->nodes()->create<luci::CircleVariable>();
}
References _graph, loco::NodePool::create(), and loco::Graph::nodes().
visit() [17/17]
luci::CircleNode * luci::CloneNode::visit (const luci::CircleWhileOut * node) final
Definition at line 22 of file CircleWhileOut.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleWhileOut>();
  if (cloned != nullptr)
    cloned->index(node->index());
  return cloned;
}
References _graph, loco::NodePool::create(), luci::CircleWhileOut::index(), and loco::Graph::nodes().
Field Documentation
_graph
loco::Graph* luci::CloneNode::_graph = nullptr protected
Definition at line 283 of file CircleCloneNode.h.
Referenced by visit().
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/CircleCloneNode.cpp
compiler/luci/service/src/Nodes/CircleBCQFullyConnected.cpp
compiler/luci/service/src/Nodes/CircleBCQGather.cpp
compiler/luci/service/src/Nodes/CircleCustomOut.cpp
compiler/luci/service/src/Nodes/CircleIfOut.cpp
compiler/luci/service/src/Nodes/CircleInstanceNorm.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV4Out.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV5Out.cpp
compiler/luci/service/src/Nodes/CircleOutputDummy.cpp
compiler/luci/service/src/Nodes/CircleOutputExclude.cpp
compiler/luci/service/src/Nodes/CircleSplitOut.cpp
compiler/luci/service/src/Nodes/CircleSplitVOut.cpp
compiler/luci/service/src/Nodes/CircleTopKV2Out.cpp
compiler/luci/service/src/Nodes/CircleUniqueOut.cpp
compiler/luci/service/src/Nodes/CircleUnpackOut.cpp
compiler/luci/service/src/Nodes/CircleVariable.cpp
compiler/luci/service/src/Nodes/CircleWhileOut.cpp