ONE - On-device Neural Engine: moco::BiasAddGraphBuilder Class Reference
moco::BiasAddGraphBuilder Class Reference
#include <BiasAdd.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const final
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const final
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 25 of file BiasAdd.h.
Member Function Documentation
build()
void moco::BiasAddGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const final virtual
Implements moco::GraphBuilder.
Definition at line 96 of file BiasAdd.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  // tensorflow data_format: one of NHWC or NCHW.
  auto data_layout = plier::tf::get_string_attr(node, "data_format");
  auto tf_bias_add = graph->nodes()->create<TFBiasAdd>();
  tf_bias_add->name(node.name());
  tf_bias_add->data_layout(data_layout);
  // To set the input node of encode_node with biasAdd_name
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, tf_bias_add);
  std::vector<TensorName> input_names;
  input_names.push_back(TensorName(node.input(0)));
  input_names.push_back(TensorName(node.input(1)));
  auto update = std::make_unique<TFBiasAddGraphUpdate>(tf_bias_add, input_names);
  updates->enroll(std::move(update));
}
References moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), plier::tf::get_string_attr(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::GraphBuilderContext::tensor_names(), moco::update(), and moco::GraphBuilderContext::updates().
validate()
bool moco::BiasAddGraphBuilder::validate (const tensorflow::NodeDef & node) const final virtual
Implements moco::GraphBuilder.
Definition at line 69 of file BiasAdd.cpp.
{
  if (node.input_size() != 2)
    return false;
  // note: even though "data_format" is not entered when a model is written,
  //       TF seems to generate "data_format" field into a pb file
  if (!plier::tf::has_attrs(node, {"T", "data_format"}))
    return false;
  // TODO add type check
  // type of input and bias should be same (except using quantization)
  // Note In case of TF.nn.bias_add,
  // "value may have any number of dimensions." ...
  // but "data_format: A string. 'NHWC' and 'NCHW' are supported."
  // Not sure if value should be 4-D tensor. Let's skip this check for now.
  auto data_layout = plier::tf::get_string_attr(node, "data_format");
  if (!(data_layout == "NHWC" || data_layout == "NCHW"))
  {
    throw oops::UserExn("BiasAdd Unsupported data_format", node.name());
  }
  return true;
}
References plier::tf::get_string_attr(), and plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/BiasAdd.h
compiler/moco/import/src/Nodes/BiasAdd.cpp