ONE - On-device Neural Engine: exo::FeatureBiasAddConverter Class Reference
exo::FeatureBiasAddConverter Class Reference
#include <FeatureBiasAddConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::FeatureBiasAdd *origin) final
Converts loco::FeatureBiasAdd to locoex::TFLAdd.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::FeatureBiasAdd >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::FeatureBiasAdd *node)=0
Detailed Description
Definition at line 27 of file FeatureBiasAddConverter.h.
Member Function Documentation
convert()
bool exo::FeatureBiasAddConverter::convert (loco::FeatureBiasAdd * origin) final virtual
Converts loco::FeatureBiasAdd to locoex::TFLAdd.
Before: Foo —+ | loco::FeatureBiasAdd - FeatureDecode - ... | Bar - BiasEncode –+
After:
         Foo - loco::FeatureDecode --+           loco::FeatureBiasAdd
                                     |(x)
                                     TFLAdd -- loco::FeatureEncode - FeatureDecode - ...
                                     |(y)
Bar - BiasEncode - loco::BiasDecode –+
Implements exo::CanonicalNodeConverter< loco::FeatureBiasAdd >.
Definition at line 59 of file FeatureBiasAddConverter.cpp.
{
  auto *graph = origin->graph();
  auto tfl_add = graph->nodes()->create<locoex::TFLAdd>();
  // handling input x
  assert(loco::shape_get(origin->value()).domain() == loco::Domain::Feature);
  auto fea_dec = make_feature_decode<FeatureLayout::NHWC>(origin->value());
  tfl_add->x(fea_dec);
  // handling input y
  auto bias_dec = graph->nodes()->create<loco::BiasDecode>();
  assert(bias_dec != nullptr);
  bias_dec->input(origin->bias());
  tfl_add->y(bias_dec);
  // fused activation function
  init_fused_act_func(tfl_add);
  // handling output
  auto fea_enc = make_feature_encode<FeatureLayout::NHWC>(tfl_add);
  loco::replace(origin).with(fea_enc);
  origin->value(nullptr);
  return true;
}
References loco::BiasAdd< Domain::Feature >::bias(), loco::NodeShape::domain(), loco::Feature, loco::Node::graph(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), loco::replace(), loco::shape_get(), loco::BiasAdd< Domain::Feature >::value(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::FeatureBiasAddConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::FeatureBiasAdd >.
Definition at line 30 of file FeatureBiasAddConverter.h.
{ return "exo::TFLAddConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/FeatureBiasAddConverter.h
compiler/exo/src/Conversion/FeatureBiasAddConverter.cpp