ONE - On-device Neural Engine: luci_interpreter::TestMemoryManager Class Reference
luci_interpreter::TestMemoryManager Class Reference
#include <TestMemoryManager.h>
Public Member Functions
void allocate_memory (luci_interpreter::Tensor &tensor) final
void release_memory (luci_interpreter::Tensor &tensor) final
~TestMemoryManager () override
void allocate_memory (luci_interpreter::Tensor &tensor) final
void release_memory (luci_interpreter::Tensor &tensor) final
~TestMemoryManager () override
Public Member Functions inherited from luci_interpreter::IMemoryManager
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
bool is_allocate_input () const
void is_allocate_input (bool allocate_input)
virtual void allocate_input_buf ()=0
virtual void allocate_output_buf ()=0
virtual void allocate_computing_buf ()=0
virtual void release_computing_buf ()=0
virtual void release_input_buf ()=0
virtual void release_output_buf ()=0
virtual void allocate_memory_for_input (luci_interpreter::Tensor &tensor)=0
virtual void allocate_memory_for_output (luci_interpreter::Tensor &tensor)=0
Additional Inherited Members
Protected Attributes inherited from luci_interpreter::IMemoryManager
bool _is_allocate_input = true
Detailed Description
Definition at line 27 of file TestMemoryManager.h.
Constructor & Destructor Documentation
~TestMemoryManager() [1/2]
luci_interpreter::TestMemoryManager::~TestMemoryManager () inline override
Definition at line 33 of file TestMemoryManager.h.
  {
    for (auto allocation : allocations)
    {
      delete[] allocation;
    }
  }
~TestMemoryManager() [2/2]
luci_interpreter::TestMemoryManager::~TestMemoryManager () inline override
Definition at line 33 of file TestMemoryManager.h.
  {
    for (auto allocation : allocations)
    {
      delete[] allocation;
    }
  }
Member Function Documentation
allocate_memory() [1/2]
void luci_interpreter::TestMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 22 of file TestMemoryManager.cpp.
{
  if (!tensor.is_allocatable())
  {
    return;
  }
  if (tensor.is_data_allocated())
  {
    release_memory(tensor);
  }
  const auto element_size = getDataTypeSize(tensor.element_type());
  const auto num_elements = tensor.shape().num_elements();
  auto *data = new uint8_t[num_elements * element_size];
  allocations.push_back(data);
  tensor.set_data_buffer(data);
}
References luci_interpreter::getDataTypeSize(), and release_memory().
allocate_memory() [2/2]
void luci_interpreter::TestMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
release_memory() [1/2]
void luci_interpreter::TestMemoryManager::release_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 40 of file TestMemoryManager.cpp.
{
  tensor.set_data_buffer(nullptr);
}
Referenced by allocate_memory().
release_memory() [2/2]
void luci_interpreter::TestMemoryManager::release_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/TestMemoryManager.h
onert-micro/luci-interpreter/src/memory_managers/TestMemoryManager.h
compiler/luci-interpreter/src/TestMemoryManager.cpp
onert-micro/luci-interpreter/src/memory_managers/TestMemoryManager.cpp