ONE - On-device Neural Engine: moco::TFAvgPool Class Reference
moco::TFAvgPool Class Reference final
#include <TFAvgPool.h>
Public Member Functions
TFAvgPool ()=default
Node * value (void) const
void value (Node *node)
const TFDataLayout & data_layout (void) const
void data_layout (const TFDataLayout &data_layout)
const TFPadding & padding (void) const
void padding (const TFPadding &padding)
const std::vector< int64_t > & ksize (void) const
void ksize (const std::vector< int64_t > &ksize)
const std::vector< int64_t > & strides (void) const
void strides (const std::vector< int64_t > &strides)
Public Member Functions inherited from moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::AvgPool >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >
loco::Use * at (unsigned n) const
Detailed Description
Note
TFAvgPool corresponds to the following GraphDef
Definition at line 70 of file TFAvgPool.h.
Constructor & Destructor Documentation
TFAvgPool()
moco::TFAvgPool::TFAvgPool () default
Member Function Documentation
data_layout() [1/2]
void moco::TFAvgPool::data_layout (const TFDataLayout & data_layout) inline
Definition at line 81 of file TFAvgPool.h.
{ _data_layout = data_layout; }
References data_layout().
Referenced by data_layout().
data_layout() [2/2]
const TFDataLayout & moco::TFAvgPool::data_layout (void) const inline
Definition at line 80 of file TFAvgPool.h.
{ return _data_layout; }
ksize() [1/2]
void moco::TFAvgPool::ksize (const std::vector< int64_t > & ksize) inline
Definition at line 87 of file TFAvgPool.h.
{ _ksize = ksize; }
References ksize().
Referenced by ksize().
ksize() [2/2]
const std::vector< int64_t > & moco::TFAvgPool::ksize (void) const inline
Definition at line 86 of file TFAvgPool.h.
{ return _ksize; }
padding() [1/2]
void moco::TFAvgPool::padding (const TFPadding & padding) inline
Definition at line 84 of file TFAvgPool.h.
{ _padding = padding; }
References padding().
Referenced by padding().
padding() [2/2]
const TFPadding & moco::TFAvgPool::padding (void) const inline
Definition at line 83 of file TFAvgPool.h.
{ return _padding; }
strides() [1/2]
void moco::TFAvgPool::strides (const std::vector< int64_t > & strides) inline
Definition at line 90 of file TFAvgPool.h.
{ _strides = strides; }
References strides().
Referenced by strides().
strides() [2/2]
const std::vector< int64_t > & moco::TFAvgPool::strides (void) const inline
Definition at line 89 of file TFAvgPool.h.
{ return _strides; }
value() [1/2]
void moco::TFAvgPool::value (Node * node) inline
Definition at line 77 of file TFAvgPool.h.
{ return at(0)->node(node); }
References moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >::at(), and loco::Use::node().
value() [2/2]
Node * moco::TFAvgPool::value (void) const inline
Definition at line 76 of file TFAvgPool.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFAvgPool.h