ONE - On-device Neural Engine: luci_interpreter::kernels::Relu Class Reference
luci_interpreter::kernels::Relu Class Reference
#include <Relu.h>
Public Member Functions
Relu (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Relu (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file Relu.h.
Constructor & Destructor Documentation
Relu() [1/2]
luci_interpreter::kernels::Relu::Relu (const Tensor * input, Tensor * output)
Definition at line 30 of file Relu.cpp.
: Kernel({input}, {output}) {}
References input().
Relu() [2/2]
luci_interpreter::kernels::Relu::Relu (const Tensor * input, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Relu::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 32 of file Relu.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  if (input()->element_type() == DataType::S16)
  {
    LUCI_INTERPRETER_CHECK(input()->zero_point() == 0 && output()->zero_point() == 0);
  }
  if (input()->element_type() == DataType::U8 || input()->element_type() == DataType::S16)
  {
    double multiplier = input()->scale() / output()->scale();
    quantizeMultiplier(multiplier, &_output_multiplier, &_output_shift);
  }
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::kernels::quantizeMultiplier(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::scale().
configure() [2/2]
void luci_interpreter::kernels::Relu::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Relu::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 48 of file Relu.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    case DataType::S16:
      evalQuantizedS16();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Relu::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Relu::input () const inline
Definition at line 32 of file Relu.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Relu().
input() [2/2]
const Tensor * luci_interpreter::kernels::Relu::input () const inline
Definition at line 32 of file Relu.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Relu::output () const inline
Definition at line 33 of file Relu.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Relu::output () const inline
Definition at line 33 of file Relu.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Relu.h
onert-micro/luci-interpreter/src/kernels/Relu.h
compiler/luci-interpreter/src/kernels/Relu.cpp
onert-micro/luci-interpreter/src/kernels/Relu.cpp