ONE - On-device Neural Engine: fme_apply::FusePreShiftPass Class Reference
fme_apply::FusePreShiftPass Class Reference
Pass to fuse CircleCustom(PreShift) to succeeding Ops.
#include <FusePreShiftPass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to fuse CircleCustom(PreShift) to succeeding Ops.
BEFORE
 [Node]
   |
[PreShift] | [Op]
AFTER
 [Node]
   |
 [Op']
Definition at line 45 of file FusePreShiftPass.h.
Member Function Documentation
name()
virtual const char * fme_apply::FusePreShiftPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 48 of file FusePreShiftPass.h.
{ return "fme::FusePreShiftPass"; }
run()
bool fme_apply::FusePreShiftPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 62 of file FusePreShiftPass.cpp.
{
  bool changed = false;
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    FusePreShift fps;
    auto cnode = loco::must_cast<luci::CircleNode *>(node);
    if (cnode->accept(&fps))
      changed = true;
  }
  return changed;
}
References loco::output_nodes(), and loco::postorder_traversal().
Referenced by package.infer.session::inference().
The documentation for this class was generated from the following files:
compiler/fme-apply/src/pass/FusePreShiftPass.h
compiler/fme-apply/src/pass/FusePreShiftPass.cpp