ONE - On-device Neural Engine: mir::TensorVariant Class Reference
mir::TensorVariant Class Reference
#include <TensorVariant.h>
Public Member Functions
TensorVariant (const TensorType &type)
TensorVariant (const TensorType &type, const void *data)
TensorVariant (DataType element_type, const Shape &shape)
TensorVariant (DataType element_type, const Shape &shape, const void *data)
TensorVariant (const TensorVariant &t_old, const Shape &shape)
Construct a TensorVariant from t_old that has strides with 0 where dim = 1 Used for broadcasting.
virtual ~TensorVariant ()=default
char * at (const Index &idx) const
char * atOffset (int32_t offset) const
size_t getOffset (const Index &idx) const
const TensorType & getType () const
DataType getElementType () const
const Shape & getShape () const
DataType getDataType () const
size_t getElementSize () const
Detailed Description
Definition at line 32 of file TensorVariant.h.
Constructor & Destructor Documentation
TensorVariant() [1/5]
mir::TensorVariant::TensorVariant (const TensorType & type) explicit
Definition at line 23 of file TensorVariant.cpp.
                                                   : _type(type), _strides(type.getShape().rank())
{
  _element_size = getDataTypeSize(getElementType());
  std::size_t data_size = getShape().numElements() * _element_size;
  _data.reset(new char[data_size], std::default_delete<char[]>());
  int stride = 1;
  for (int d = getShape().rank() - 1; d >= 0; --d)
  {
    _strides[d] = stride;
    stride *= getShape().dim(d);
  }
}
References mir::Shape::dim(), mir::getDataTypeSize(), getElementType(), getShape(), and mir::Shape::numElements().
TensorVariant() [2/5]
mir::TensorVariant::TensorVariant (const TensorType & type, const void * data)
Definition at line 42 of file TensorVariant.cpp.
                                                                     : TensorVariant(type)
{
  std::size_t data_size = getShape().numElements() * _element_size;
  std::memcpy(_data.get(), data, data_size);
}
References getShape(), and mir::Shape::numElements().
TensorVariant() [3/5]
mir::TensorVariant::TensorVariant (DataType element_type, const Shape & shape)
Definition at line 37 of file TensorVariant.cpp.
  : TensorVariant(TensorType(element_type, shape))
{
}
TensorVariant() [4/5]
mir::TensorVariant::TensorVariant (DataType element_type, const Shape & shape, const void * data)
Definition at line 48 of file TensorVariant.cpp.
  : TensorVariant(TensorType(element_type, shape), data)
{
}
TensorVariant() [5/5]
mir::TensorVariant::TensorVariant (const TensorVariant & t_old, const Shape & shape)
Construct a TensorVariant from t_old that has strides with 0 where dim = 1 Used for broadcasting.
Parameters
t_old TensorVariant to use as base
shape shape to broadcast to
Definition at line 59 of file TensorVariant.cpp.
  : _type(t_old.getType().getElementType(), shape), _data(t_old._data),
    _strides(static_cast<size_t>(shape.rank())), _element_size(t_old._element_size)
{
  int axis_old = t_old.getShape().rank() - 1;
  for (int d = shape.rank() - 1; d >= 0; d--)
  {
    if (axis_old == -1)
      break;
    if (t_old.getShape().dim(axis_old) != 1)
      _strides[d] = t_old._strides[axis_old];
    axis_old--;
  }
}
References mir::Shape::dim(), getShape(), and mir::Shape::rank().
~TensorVariant()
virtual mir::TensorVariant::~TensorVariant () virtual default
Member Function Documentation
at()
char * mir::TensorVariant::at (const Index & idx) const inline
Definition at line 49 of file TensorVariant.h.
{ return _data.get() + getOffset(idx) * _element_size; }
References getOffset().
Referenced by mir::Tensor< T >::at(), mir::Tensor< T >::getRegion(), mir_interpreter::FullyConnectedImpl< T >::run(), TEST(), mir::transposeTensor(), and mir2loco::Transformer::visit().
atOffset()
char * mir::TensorVariant::atOffset (int32_t offset) const inline
Definition at line 51 of file TensorVariant.h.
  {
    assert(offset >= 0 && offset < getShape().numElements());
    return _data.get() + offset * _element_size;
  }
References getShape(), and offset().
Referenced by mir::Tensor< T >::atOffset(), mir_interpreter::erase(), mir_interpreter::HardSwishImpl< T >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), mir_interpreter::Conv2DImpl< T >::run(), and mir_interpreter::DeConv2DImpl< T >::run().
getDataType()
DataType mir::TensorVariant::getDataType () const inline
Definition at line 72 of file TensorVariant.h.
{ return _type.getElementType(); }
References mir::TensorType::getElementType().
getElementSize()
size_t mir::TensorVariant::getElementSize () const inline
Definition at line 74 of file TensorVariant.h.
{ return _element_size; }
Referenced by TEST().
getElementType()
DataType mir::TensorVariant::getElementType () const inline
Definition at line 68 of file TensorVariant.h.
{ return _type.getElementType(); }
References mir::TensorType::getElementType().
Referenced by mir_interpreter::Add(), mir_onnx::constantToShape(), mir_interpreter::Conv2D(), mir_interpreter::Div(), mir_interpreter::ELU(), mir_interpreter::Equal(), mir_interpreter::Fill(), mir_interpreter::FullyConnected(), mir_interpreter::Greater(), mir_interpreter::LeakyReLU(), mir_interpreter::Less(), mir_interpreter::Max(), mir_interpreter::Mul(), mir_interpreter::GatherByT< T >::run(), mir_interpreter::Sub(), and TensorVariant().
getOffset()
size_t mir::TensorVariant::getOffset (const Index & idx) const inline
Definition at line 57 of file TensorVariant.h.
  {
    assert(idx.rank() == getShape().rank());
    std::size_t offset = 0;
    for (int i = 0; i < getShape().rank(); ++i)
      offset += idx.at(i) * _strides[i];
    return offset;
  }
References mir::Index::at(), getShape(), offset(), mir::Index::rank(), and mir::Shape::rank().
Referenced by at(), and TEST().
getShape()
const Shape & mir::TensorVariant::getShape () const inline
Definition at line 69 of file TensorVariant.h.
{ return _type.getShape(); }
References mir::TensorType::getShape().
Referenced by atOffset(), mir_interpreter::erase(), getOffset(), mir::Tensor< T >::getShape(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::SliceImpl< T >::run(), mir_interpreter::ELUImpl< T >::run(), mir_interpreter::LeakyReLUImpl< T >::run(), mir_interpreter::CappedReLUImpl< T >::run(), mir_interpreter::CappedReLUImpl< uint8_t >::run(), mir_interpreter::SoftmaxImpl< T >::run(), mir_interpreter::AbsImpl< T >::run(), mir_interpreter::ReLUImpl< T >::run(), mir_interpreter::SigmoidImpl< T >::run(), mir_interpreter::SqrtImpl< T >::run(), mir_interpreter::TanhImpl< T >::run(), mir_interpreter::TransposeImpl< T >::run(), mir_interpreter::FullyConnectedImpl< T >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), mir_interpreter::GatherImpl< T, IndicesT >::run(), mir_interpreter::Conv2DImpl< T >::run(), mir_interpreter::Conv2DImpl< uint8_t >::run(), mir_interpreter::DeConv2DImpl< T >::run(), mir_interpreter::AddImpl< T >::run(), mir_interpreter::AddImpl< uint8_t >::run(), mir_interpreter::DivImpl< T >::run(), mir_interpreter::EqualImpl< T >::run(), mir_interpreter::GreaterImpl< T >::run(), mir_interpreter::LessImpl< T >::run(), mir_interpreter::MaxImpl< T >::run(), mir_interpreter::MulImpl< T >::run(), mir_interpreter::SubImpl< T >::run(), mir_interpreter::FillImpl< T >::run(), TensorVariant(), TEST(), and nnc::AclCppOpGenerator::visit().
getType()
const TensorType & mir::TensorVariant::getType () const inline
Definition at line 66 of file TensorVariant.h.
{ return _type; }
Referenced by mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::CappedReLUImpl< uint8_t >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), mir_interpreter::Conv2DImpl< uint8_t >::run(), and mir_interpreter::AddImpl< uint8_t >::run().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/TensorVariant.h
compiler/mir/src/TensorVariant.cpp