ONE - On-device Neural Engine: ConvolutionSpec Class Reference
ConvolutionSpec Class Reference
#include <ConvolutionSpec.h>
Public Member Functions
ConvolutionSpec (const ::caffe::ConvolutionParameter &param)
uint32_t ifm_rank (void) const
uint32_t ifm_dim (uint32_t axis) const
uint32_t group (void) const
uint32_t channel_axis (void) const
uint32_t num_batch_axes (void) const
uint32_t num_spatial_axes (void) const
uint32_t pad (uint32_t spatial_axis) const
uint32_t stride (uint32_t spatial_axis) const
uint32_t ker_dim (uint32_t spatial_axis) const
const nncc::core::ADT::tensor::Shape & ifm_shape (void) const
void ifm_shape (const nncc::core::ADT::tensor::Shape &shape)
uint32_t ker_count (void) const
nncc::core::ADT::tensor::Shape ker_shape (void) const
nncc::core::ADT::tensor::Shape ofm_shape (void) const
Detailed Description
Definition at line 24 of file ConvolutionSpec.h.
Constructor & Destructor Documentation
ConvolutionSpec()
ConvolutionSpec::ConvolutionSpec (const ::caffe::ConvolutionParameter & param)
Definition at line 23 of file ConvolutionSpec.cpp.
                                                                       : _param(param)
{
  // NOTE Dilation is not supported, yet
  // TODO Support dilation
  assert(param.dilation().size() == 0);
}
Member Function Documentation
channel_axis()
uint32_t ConvolutionSpec::channel_axis (void) const
Definition at line 32 of file ConvolutionSpec.cpp.
{
  return query_on(ifm_shape()).axis(axis_specifier(_param.axis()));
}
References ShapeQuery::axis(), axis_specifier(), ifm_shape(), and query_on().
Referenced by ker_shape(), num_batch_axes(), and num_spatial_axes().
group()
uint32_t ConvolutionSpec::group (void) const
Definition at line 30 of file ConvolutionSpec.cpp.
{ return _param.group(); }
Referenced by ker_shape().
ifm_dim()
uint32_t ConvolutionSpec::ifm_dim (uint32_t axis) const inline
Definition at line 31 of file ConvolutionSpec.h.
{ return _ifm_shape.dim(axis); }
References nncc::core::ADT::tensor::Shape::dim().
Referenced by ker_shape(), and ofm_shape().
ifm_rank()
uint32_t ConvolutionSpec::ifm_rank (void) const inline
Definition at line 30 of file ConvolutionSpec.h.
{ return _ifm_shape.rank(); }
References nncc::core::ADT::tensor::Shape::rank().
Referenced by num_spatial_axes().
ifm_shape() [1/2]
void ConvolutionSpec::ifm_shape (const nncc::core::ADT::tensor::Shape & shape) inline
Definition at line 46 of file ConvolutionSpec.h.
{ _ifm_shape = shape; }
ifm_shape() [2/2]
const nncc::core::ADT::tensor::Shape & ConvolutionSpec::ifm_shape (void) const inline
Definition at line 45 of file ConvolutionSpec.h.
{ return _ifm_shape; }
Referenced by caffeimport::ConvolutionBuilder::build(), and channel_axis().
ker_count()
uint32_t ConvolutionSpec::ker_count (void) const inline
Definition at line 49 of file ConvolutionSpec.h.
{ return _param.num_output(); }
Referenced by ker_shape(), and ofm_shape().
ker_dim()
uint32_t ConvolutionSpec::ker_dim (uint32_t spatial_axis) const
Definition at line 70 of file ConvolutionSpec.cpp.
{
  assert(spatial_axis < num_spatial_axes());
  if (_param.kernel_size().size() == 0)
  {
    if (_param.has_kernel_h() && (spatial_axis == 0))
    {
      assert(num_spatial_axes() == 2);
      return _param.kernel_h();
    }
    if (_param.has_kernel_w() && (spatial_axis == 1))
    {
      assert(num_spatial_axes() == 2);
      return _param.kernel_w();
    }
    return 0;
  }
  assert(!_param.has_kernel_h());
  assert(!_param.has_kernel_w());
  if (_param.kernel_size().size() == 1)
  {
    return _param.kernel_size(0);
  }
  else
  {
    assert(_param.kernel_size().size() == num_spatial_axes());
    return _param.kernel_size(spatial_axis);
  }
}
References num_spatial_axes().
Referenced by ker_shape(), and ofm_shape().
ker_shape()
nncc::core::ADT::tensor::Shape ConvolutionSpec::ker_shape (void) const
Definition at line 103 of file ConvolutionSpec.cpp.
{
  nncc::core::ADT::tensor::Shape res;
  res.resize(2 + num_spatial_axes());
  res.dim(0) = ker_count();
  assert(ifm_dim(channel_axis()) % group() == 0);
  res.dim(1) = ifm_dim(channel_axis()) / group();
  for (uint32_t axis = 0; axis < num_spatial_axes(); ++axis)
  {
    res.dim(2 + axis) = ker_dim(axis);
  }
  return res;
}
References channel_axis(), nncc::core::ADT::tensor::Shape::dim(), group(), ifm_dim(), ker_count(), ker_dim(), num_spatial_axes(), and nncc::core::ADT::tensor::Shape::resize().
num_batch_axes()
uint32_t ConvolutionSpec::num_batch_axes (void) const inline
Definition at line 37 of file ConvolutionSpec.h.
{ return channel_axis(); }
References channel_axis().
Referenced by ofm_shape().
num_spatial_axes()
uint32_t ConvolutionSpec::num_spatial_axes (void) const inline
Definition at line 38 of file ConvolutionSpec.h.
{ return ifm_rank() - channel_axis() - 1; }
References channel_axis(), and ifm_rank().
Referenced by ker_dim(), ker_shape(), ofm_shape(), pad(), and stride().
ofm_shape()
nncc::core::ADT::tensor::Shape ConvolutionSpec::ofm_shape (void) const
Definition at line 120 of file ConvolutionSpec.cpp.
{
  nncc::core::ADT::tensor::Shape res;
  res.resize(num_batch_axes() + 1 + num_spatial_axes());
  for (uint32_t axis = 0; axis < num_batch_axes(); ++axis)
  {
    res.dim(axis) = ifm_dim(axis);
  }
  res.dim(num_batch_axes()) = ker_count();
  for (uint32_t spatial_axis = 0; spatial_axis < num_spatial_axes(); ++spatial_axis)
  {
    const uint32_t full_axis = num_batch_axes() + 1 + spatial_axis;
    uint32_t dim = 0;
    dim += ifm_dim(full_axis) - ker_dim(spatial_axis) + 2 * pad(spatial_axis);
    dim /= stride(spatial_axis);
    dim += 1;
    res.dim(full_axis) = dim;
  }
  return res;
}
References nncc::core::ADT::tensor::Shape::dim(), ifm_dim(), ker_count(), ker_dim(), num_batch_axes(), num_spatial_axes(), pad(), nncc::core::ADT::tensor::Shape::resize(), and stride().
pad()
uint32_t ConvolutionSpec::pad (uint32_t spatial_axis) const
Definition at line 37 of file ConvolutionSpec.cpp.
{
  assert(spatial_axis < num_spatial_axes());
  auto raw_padding = build_raw_padding().with(_param);
  auto spatial_padding = build_spatial_padding(num_spatial_axes()).with(raw_padding);
  return spatial_padding.value(spatial_axis);
}
References build_raw_padding(), build_spatial_padding(), num_spatial_axes(), PaddingBase< Derived >::value(), RawPaddingBuilder::with(), and SpatialPaddingBuilder::with().
Referenced by ofm_shape().
stride()
uint32_t ConvolutionSpec::stride (uint32_t spatial_axis) const
Definition at line 47 of file ConvolutionSpec.cpp.
{
  assert(spatial_axis < num_spatial_axes());
  // TODO Support stride_h/stride_w parameters
  assert(!_param.has_stride_h());
  assert(!_param.has_stride_w());
  if (_param.stride().size() == 0)
  {
    // NOTE default stride is 1
    return 1;
  }
  if (_param.stride().size() == 1)
  {
    return _param.stride(0);
  }
  assert(_param.stride().size() == num_spatial_axes());
  return _param.stride(spatial_axis);
}
References num_spatial_axes().
Referenced by ofm_shape().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/ConvolutionSpec.h
compiler/enco/frontend/caffe/src/ConvolutionSpec.cpp