ONE - On-device Neural Engine: mir::Graph Class Reference
mir::Graph Class Reference
#include <Graph.h>
Public Member Functions
Graph ()=default
virtual ~Graph ()
template<typename T , typename... Args>
Operation * create (Args &&... args)
Operation * copyOpWithInputs (Operation *old_op, const std::vector< Operation::Output * > &inputs)
Copies old_op with new inputs and registers it into graph.
void accept (IVisitor *visitor)
std::unordered_set< Operation * > getNodes () const
Returns all graph nodes.
std::vector< ops::InputOp * > getInputs () const
Returns all graph input nodes.
std::vector< ops::OutputOp * > getOutputs () const
Returns all graph output nodes.
void removeNode (Operation *op)
remove node from graph, along with its links in other nodes
void replaceNode (Operation *op, Operation *with)
Subsitude node in graph with another keeping all edges.
Detailed Description
Definition at line 34 of file Graph.h.
Constructor & Destructor Documentation
Graph()
mir::Graph::Graph () explicit default
~Graph()
mir::Graph::~Graph () virtual
Definition at line 92 of file Graph.cpp.
{
  for (auto &node : _ops)
  {
    delete node;
  }
}
Member Function Documentation
accept()
void mir::Graph::accept (IVisitor * visitor)
Definition at line 84 of file Graph.cpp.
{
  for (Operation *node : getSortedNodes(this))
  {
    node->accept(visitor);
  }
}
References mir::getSortedNodes().
Referenced by mir2loco::Transformer::transform().
copyOpWithInputs()
Operation * mir::Graph::copyOpWithInputs (Operation * old_op, const std::vector< Operation::Output * > & inputs) inline
Copies old_op with new inputs and registers it into graph.
Definition at line 52 of file Graph.h.
  {
    assert(inputs.size() == old_op->getNumInputs());
    auto op = old_op->copyWithInputs(inputs);
    op->setId(_last_node_id++);
    registerOp(op);
    return op;
  }
References mir::Operation::copyWithInputs(), mir::Operation::getNumInputs(), and mir::Operation::setId().
create()
template<typename T , typename... Args> Operation * mir::Graph::create (Args &&... args) inline
Definition at line 41 of file Graph.h.
  {
    auto op = new T(std::forward<Args>(args)...);
    op->setId(_last_node_id++);
    registerOp(op);
    return op;
  }
getInputs()
std::vector< ops::InputOp * > mir::Graph::getInputs () const inline
Returns all graph input nodes.
Returns
vector containing all graph input nodes
Definition at line 73 of file Graph.h.
{ return _inputs; }
getNodes()
std::unordered_set< Operation * > mir::Graph::getNodes () const inline
Returns all graph nodes.
Returns
vector containing all graph nodes
Definition at line 67 of file Graph.h.
{ return _ops; }
Referenced by mir::GraphPatternMatcher::matchEdge(), mir::GraphPatternMatcher::matchUpBush(), and nnc::DataFormatSwitcher::run().
getOutputs()
std::vector< ops::OutputOp * > mir::Graph::getOutputs () const inline
Returns all graph output nodes.
Returns
vector containing all graph output nodes
Definition at line 79 of file Graph.h.
{ return _outputs; }
removeNode()
void mir::Graph::removeNode (Operation * op)
remove node from graph, along with its links in other nodes
Parameters
op node to be removed
Definition at line 117 of file Graph.cpp.
{
#ifndef NDEBUG
  for (const auto &output : op->getOutputs())
  {
    assert(output.getUses().empty() && "Trying to remove a node that has uses.");
  }
#endif
  for (std::size_t i = 0; i < op->getNumInputs(); ++i)
  {
    op->getInput(i)->removeUse(Operation::Use(op, i));
  }
  if (op->getType() == Operation::Type::input)
    _inputs.erase(
      std::remove(_inputs.begin(), _inputs.end(), op)); // NOLINT(bugprone-inaccurate-erase)
  if (op->getType() == Operation::Type::output)
    _outputs.erase(
      std::remove(_outputs.begin(), _outputs.end(), op)); // NOLINT(bugprone-inaccurate-erase)
  _ops.erase(op);
  delete op;
}
References mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutputs(), mir::Operation::getType(), and mir::Operation::Output::removeUse().
Referenced by replaceNode().
replaceNode()
void mir::Graph::replaceNode (Operation * op, Operation * with)
Subsitude node in graph with another keeping all edges.
Parameters
op Node to subsitude
with Node to place instead
Definition at line 111 of file Graph.cpp.
{
  replaceUsages(op, with);
  removeNode(op);
}
References removeNode().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/Graph.h
compiler/mir/src/Graph.cpp