ONE - On-device Neural Engine: arm_compute::CLMultiplyScaleFactorKernel Class Reference
arm_compute::CLMultiplyScaleFactorKernel Class Reference
#include <CLMultiplyScaleFactorKernel.h>
Public Member Functions
CLMultiplyScaleFactorKernel ()
CLMultiplyScaleFactorKernel (const CLMultiplyScaleFactorKernel &)=delete
CLMultiplyScaleFactorKernel & operator= (const CLMultiplyScaleFactorKernel &)=delete
CLMultiplyScaleFactorKernel (CLMultiplyScaleFactorKernel &&)=default
CLMultiplyScaleFactorKernel & operator= (CLMultiplyScaleFactorKernel &&)=default
~CLMultiplyScaleFactorKernel ()=default
void configure (const ICLTensor *input, const ICLTensor *scale_factor, ICLTensor *output, float multiplier=1.f)
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *scale_factor, const ITensorInfo *output)
Detailed Description
Interface to multiply scale factor kernel.
Definition at line 51 of file CLMultiplyScaleFactorKernel.h.
Constructor & Destructor Documentation
CLMultiplyScaleFactorKernel() [1/3]
CLMultiplyScaleFactorKernel::CLMultiplyScaleFactorKernel ()
Default constructor
Definition at line 105 of file CLMultiplyScaleFactorKernel.cpp.
  : _input(nullptr), _scale_factor(nullptr), _output(nullptr), _multiplier(1.f)
{
}
CLMultiplyScaleFactorKernel() [2/3]
arm_compute::CLMultiplyScaleFactorKernel::CLMultiplyScaleFactorKernel (const CLMultiplyScaleFactorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMultiplyScaleFactorKernel() [3/3]
arm_compute::CLMultiplyScaleFactorKernel::CLMultiplyScaleFactorKernel (CLMultiplyScaleFactorKernel &&) default
Default Move Constructor.
~CLMultiplyScaleFactorKernel()
arm_compute::CLMultiplyScaleFactorKernel::~CLMultiplyScaleFactorKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void CLMultiplyScaleFactorKernel::configure (const ICLTensor * input, const ICLTensor * scale_factor, ICLTensor * output, float multiplier = 1.f)
Set input, output tensors.
Parameters
[in/out] input Source tensor. Data type supported: S32.
[in] scale_factor Scale tensor. Data type supported: F16/F32.
[out] output Destination tensor. Data type supported: Same as scale_factor.
[in] multiplier Additional scale value.
Definition at line 110 of file CLMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), scale_factor->info(), output->info()));
  _input = input;
  _scale_factor = scale_factor;
  _output = output;
  _multiplier = multiplier;
  const int vec_size_x = 16 / output->info()->element_size();
  const int output_width_x = output->info()->tensor_shape().x();
  const bool multi_access_x = (output_width_x / vec_size_x > 0);
  // Create and update the window (if needed)
  Window win = calculate_max_window(*output->info());
  if (multi_access_x)
  {
    win.set(
      Window::DimX,
      Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(), vec_size_x), vec_size_x));
  }
  ICLKernel::configure_internal(win);
  // Create kernel
  CLBuildOptions build_opts;
  build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(output->info()->data_type()));
  build_opts.add_option_if(
    multi_access_x, "-DLAST_ACCESSED_X=" +
                      support::cpp11::to_string(std::max<int>(output_width_x - vec_size_x, 0)));
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("multiply_scale_factor", build_opts.options()));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
Referenced by arm_compute::CLFullyConnectedHybridLayer::configure().
operator=() [1/2]
CLMultiplyScaleFactorKernel & arm_compute::CLMultiplyScaleFactorKernel::operator= (CLMultiplyScaleFactorKernel &&) default
Default move assignment operator
operator=() [2/2]
CLMultiplyScaleFactorKernel & arm_compute::CLMultiplyScaleFactorKernel::operator= (const CLMultiplyScaleFactorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void CLMultiplyScaleFactorKernel::run (const Window & window, cl::CommandQueue & queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Returns
N/A
N/A
Definition at line 158 of file CLMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
  Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
  Window slice = window_collapsed.first_slice_window_2D();
  // Set scale_factor window
  Window win_scale = calculate_max_window(*_scale_factor->info(), Steps());
  do
  {
    unsigned int idx = 0;
    add_2D_tensor_argument(idx, _input, slice);
    add_1D_tensor_argument(idx, _scale_factor, win_scale);
    add_2D_tensor_argument(idx, _output, slice);
    _kernel.setArg<float>(idx++, _multiplier);
    enqueue(queue, *this, slice, lws_hint());
  } while (window_collapsed.slide_window_slice_2D(slice));
}
validate()
Status CLMultiplyScaleFactorKernel::validate (const ITensorInfo * input, const ITensorInfo * scale_factor, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLMultiplyScaleFactorKernel
Parameters
[in] input Input tensor info. Data types supported: S32.
[in] scale_factor Scale tensor. Data type supported: F16/F32.
[in] output Output tensor info. Data types supported: Same as scale_factor.
[in] multiplier Additional scale value.
Returns
a status
Definition at line 148 of file CLMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, scale_factor, output));
  ARM_COMPUTE_RETURN_ON_ERROR(
    std::get<0>(validate_and_configure_window(input->clone().get(), output->clone().get())));
  return Status{};
}
Referenced by arm_compute::CLFullyConnectedHybridLayer::validate(), and ~CLMultiplyScaleFactorKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLMultiplyScaleFactorKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLMultiplyScaleFactorKernel.cpp