ONE - On-device Neural Engine: nncc::core::ADT::feature::Shape Class Reference
nncc::core::ADT::feature::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape (uint32_t depth, uint32_t height, uint32_t width)
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
Detailed Description
Definition at line 34 of file Shape.h.
Constructor & Destructor Documentation
Shape()
nncc::core::ADT::feature::Shape::Shape (uint32_t depth, uint32_t height, uint32_t width) inline
Definition at line 37 of file Shape.h.
    : _depth{depth}, _height{height}, _width{width}
  {
    // DO NOTHING
  }
Member Function Documentation
depth()
uint32_t nncc::core::ADT::feature::Shape::depth (void) const inline
Definition at line 44 of file Shape.h.
{ return _depth; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), coco::FeatureLayouts::BC::at(), nnop::conv(), coco::FeatureLayout::depth(), nncc::core::ADT::feature::num_elements(), and coco::FeatureLayouts::Generic::reorder().
height()
uint32_t nncc::core::ADT::feature::Shape::height (void) const inline
Definition at line 45 of file Shape.h.
{ return _height; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnop::conv(), dump(), coco::FeatureLayout::height(), nncc::core::ADT::feature::num_elements(), and coco::FeatureLayouts::Generic::reorder().
width()
uint32_t nncc::core::ADT::feature::Shape::width (void) const inline
Definition at line 46 of file Shape.h.
{ return _width; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnop::conv(), nncc::core::ADT::feature::num_elements(), coco::FeatureLayouts::Generic::reorder(), and coco::FeatureLayout::width().
The documentation for this class was generated from the following file:
compiler/angkor/include/nncc/core/ADT/feature/Shape.h