ONE - On-device Neural Engine: TfLiteInterpMatchApp Class Reference
TfLiteInterpMatchApp Class Reference
Class to define TfLite interpreter match application.
#include <Diff.h>
Public Member Functions
TfLiteInterpMatchApp (const nnfw::misc::tensor::Comparator &comparator)
Construct a new TfLiteInterpMatchApp object with Comparator.
int & verbose (void)
Get reference verbose for debugging information.
bool run (TfLiteInterpreter &expected, TfLiteInterpreter &obtained) const
Run two interpreter and return the output matching.
template<typename T >
bool compareSingleTensorView (const nnfw::tflite::TensorView< T > &expected, const nnfw::tflite::TensorView< T > &obtained, int id) const
Compare two TensorView values and return the match result.
template<>
bool compareSingleTensorView (const nnfw::tflite::TensorView< float > &expected, const nnfw::tflite::TensorView< float > &obtained, int id) const
Detailed Description
Class to define TfLite interpreter match application.
Definition at line 42 of file Diff.h.
Constructor & Destructor Documentation
TfLiteInterpMatchApp()
TfLiteInterpMatchApp::TfLiteInterpMatchApp (const nnfw::misc::tensor::Comparator & comparator) inline
Construct a new TfLiteInterpMatchApp object with Comparator.
Parameters
[in] comparator Comparator object for tensor comparation
Definition at line 49 of file Diff.h.
    : _verbose{false}, _comparator(comparator)
  {
    // DO NOTHING
  }
Member Function Documentation
compareSingleTensorView() [1/2]
template<> bool TfLiteInterpMatchApp::compareSingleTensorView (const nnfw::tflite::TensorView< float > & expected, const nnfw::tflite::TensorView< float > & obtained, int id) const
Definition at line 125 of file Diff.cpp.
{
  DiffSummary summary;
  assert(expected.shape() == obtained.shape());
  auto diffs = _comparator.compare(expected.shape(), expected, obtained, &summary);
  // TODO Unify summary generation code
  if (diffs.size() == 0)
  {
    std::cout << "  Tensor #" << id << ": MATCHED" << std::endl;
  }
  else
  {
    std::cout << "  Tensor #" << id << ": UNMATCHED" << std::endl;
    std::cout << "    " << diffs.size() << " diffs are detected" << std::endl;
  }
  // Print out max_diff
  if (summary.max_abs_diff_value > 0)
  {
    std::cout << "    Max absolute diff at ["
              << nnfw::misc::tensor::IndexFormatter(summary.max_abs_diff_index) << "]" << std::endl;
    std::cout << "       expected: " << summary.max_abs_diff_expected << std::endl;
    std::cout << "       obtained: " << summary.max_abs_diff_obtained << std::endl;
    std::cout << "       absolute diff: " << summary.max_abs_diff_value << std::endl;
  }
  if (summary.max_rel_diff_value > 0)
  {
    const auto tolerance_level = summary.max_rel_diff_value / FLT_EPSILON;
    std::cout << "    Max relative diff at ["
              << nnfw::misc::tensor::IndexFormatter(summary.max_rel_diff_index) << "]" << std::endl;
    std::cout << "       expected: " << summary.max_rel_diff_expected << std::endl;
    std::cout << "       obtained: " << summary.max_rel_diff_obtained << std::endl;
    std::cout << "       relative diff: " << summary.max_rel_diff_value << std::endl;
    std::cout << "         (tolerance level = " << tolerance_level << ")" << std::endl;
  }
  if (diffs.size() > 0)
  {
    if (_verbose != 0)
    {
      std::cout << "    ---- Details ---" << std::endl;
      for (const auto &diff : diffs)
      {
        const auto absolute_diff = std::fabs(diff.expected - diff.obtained);
        const auto relative_diff = nnfw::misc::fp32::relative_diff(diff.expected, diff.obtained);
        const auto tolerance_level = relative_diff / FLT_EPSILON;
        std::cout << "    Diff at [" << nnfw::misc::tensor::IndexFormatter(diff.index) << "]"
                  << std::endl;
        std::cout << "      expected: " << diff.expected << std::endl;
        std::cout << "      obtained: " << diff.obtained << std::endl;
        std::cout << "      absolute diff: " << absolute_diff << std::endl;
        std::cout << "      relative diff: " << relative_diff << std::endl;
        std::cout << "         (tolerance level = " << tolerance_level << ")" << std::endl;
      }
    }
    return false;
  }
  return true;
}
References nnfw::misc::tensor::Comparator::compare(), DiffSummary::max_abs_diff_expected, DiffSummary::max_abs_diff_index, DiffSummary::max_abs_diff_obtained, DiffSummary::max_abs_diff_value, DiffSummary::max_rel_diff_expected, DiffSummary::max_rel_diff_index, DiffSummary::max_rel_diff_obtained, DiffSummary::max_rel_diff_value, nnfw::misc::fp32::relative_diff(), and nnfw::tflite::TensorView< T >::shape().
compareSingleTensorView() [2/2]
template<typename T > bool TfLiteInterpMatchApp::compareSingleTensorView (const nnfw::tflite::TensorView< T > & expected, const nnfw::tflite::TensorView< T > & obtained, int id) const
Compare two TensorView values and return the match result.
Parameters
[in] expected TensorView object to read expected values
[in] obtained TensorView object to read obtained values
[in] id Tensor ID value used for debug message
Returns
true if two TensorView values are same, otherwise false
Definition at line 80 of file Diff.cpp.
{
  std::vector<nnfw::misc::tensor::Diff<T>> diffs;
  assert(expected.shape() == obtained.shape());
  using nnfw::misc::tensor::Index;
  using nnfw::misc::tensor::zip;
  zip(expected.shape(), expected, obtained)
    << [&](const Index &index, T expected_value, T obtained_value) {
         if (expected_value != obtained_value)
         {
           diffs.emplace_back(index, expected_value, obtained_value);
         }
       };
  // TODO Unify summary generation code
  if (diffs.size() == 0)
  {
    std::cout << "  Tensor #" << id << ": MATCHED" << std::endl;
  }
  else
  {
    std::cout << "  Tensor #" << id << ": UNMATCHED" << std::endl;
    std::cout << "    " << diffs.size() << " diffs are detected" << std::endl;
  }
  if (diffs.size() > 0 && _verbose != 0)
  {
    std::cout << "    ---- Details ---" << std::endl;
    for (const auto &diff : diffs)
    {
      std::cout << "    Diff at [" << nnfw::misc::tensor::IndexFormatter(diff.index) << "]"
                << std::endl;
      std::cout << "      expected: " << diff.expected << std::endl;
      std::cout << "      obtained: " << diff.obtained << std::endl;
    }
  }
  return diffs.size() == 0;
}
References nnfw::tflite::TensorView< T >::shape(), and nnfw::misc::tensor::zip().
Referenced by run().
run()
bool TfLiteInterpMatchApp::run (TfLiteInterpreter & expected, TfLiteInterpreter & obtained) const
Run two interpreter and return the output matching.
Parameters
[in] expected Interpreter object of expected
[in] obtained Interpreter object of obtained
Returns
true if two Interpreter results are same, otherwise false
Definition at line 195 of file Diff.cpp.
{
  auto output_count = TfLiteInterpreterGetOutputTensorCount(&expected);
  assert(output_count == TfLiteInterpreterGetOutputTensorCount(&obtained));
  bool all_matched = true;
  using Comparator = std::function<bool(int32_t, const TfLiteTensor *, const TfLiteTensor *)>;
  std::map<TfLiteType, Comparator> comparators;
  comparators[kTfLiteUInt8] = [this](int32_t id, const TfLiteTensor *expected_tensor,
                                     const TfLiteTensor *obtained_tensor) {
    const auto expected_view = nnfw::tflite::TensorView<uint8_t>::make(expected_tensor);
    const auto obtained_view = nnfw::tflite::TensorView<uint8_t>::make(obtained_tensor);
    return compareSingleTensorView(expected_view, obtained_view, id);
  };
  comparators[kTfLiteInt32] = [this](int32_t id, const TfLiteTensor *expected_tensor,
                                     const TfLiteTensor *obtained_tensor) {
    const auto expected_view = nnfw::tflite::TensorView<int32_t>::make(expected_tensor);
    const auto obtained_view = nnfw::tflite::TensorView<int32_t>::make(obtained_tensor);
    return compareSingleTensorView(expected_view, obtained_view, id);
  };
  comparators[kTfLiteFloat32] = [this](int32_t id, const TfLiteTensor *expected_tensor,
                                       const TfLiteTensor *obtained_tensor) {
    const auto expected_view = nnfw::tflite::TensorView<float>::make(expected_tensor);
    const auto obtained_view = nnfw::tflite::TensorView<float>::make(obtained_tensor);
    return compareSingleTensorView(expected_view, obtained_view, id);
  };
  comparators[kTfLiteBool] = [this](int32_t id, const TfLiteTensor *expected_tensor,
                                    const TfLiteTensor *obtained_tensor) {
    const auto expected_view = nnfw::tflite::TensorView<bool>::make(expected_tensor);
    const auto obtained_view = nnfw::tflite::TensorView<bool>::make(obtained_tensor);
    return compareSingleTensorView(expected_view, obtained_view, id);
  };
  for (int32_t idx = 0; idx < output_count; idx++)
  {
    auto const expected_tensor = TfLiteInterpreterGetOutputTensor(&expected, idx);
    auto const obtained_tensor = TfLiteInterpreterGetOutputTensor(&obtained, idx);
    auto const tensor_type = TfLiteTensorType(expected_tensor);
    assert(tensor_type == TfLiteTensorType(obtained_tensor));
    auto it = comparators.find(tensor_type);
    if (it == comparators.end())
    {
      throw std::runtime_error{"Not supported output type"};
    }
    const auto &comparator = it->second;
    if (!comparator(idx, expected_tensor, obtained_tensor))
    {
      all_matched = false;
    }
  }
  return all_matched;
}
References compareSingleTensorView(), and nnfw::tflite::TensorView< T >::make().
verbose()
int & TfLiteInterpMatchApp::verbose (void) inline
Get reference verbose for debugging information.
Returns
Reference of verbose value
Definition at line 60 of file Diff.h.
{ return _verbose; }
The documentation for this class was generated from the following files:
runtime/libs/tflite/include/tflite/Diff.h
runtime/libs/tflite/src/Diff.cpp