ONE - On-device Neural Engine: onert::backend::cpu::ExternalContext Class Reference
onert::backend::cpu::ExternalContext Class Reference
#include <ExternalContext.h>
Public Member Functions
ExternalContext ()
void setMaxNumThreads (int max_num_threads)
int32_t maxNumThreads () const
ruy::Context * ruy_context () const
Detailed Description
Definition at line 28 of file ExternalContext.h.
Constructor & Destructor Documentation
ExternalContext()
onert::backend::cpu::ExternalContext::ExternalContext ()
Definition at line 62 of file ExternalContext.cc.
                                 : _ruy_context(new ruy::Context)
{
  setMaxNumThreads(onert::util::getConfigInt(onert::util::config::NUM_THREADS));
}
References onert::util::getConfigInt(), and setMaxNumThreads().
Member Function Documentation
maxNumThreads()
int32_t onert::backend::cpu::ExternalContext::maxNumThreads () const inline
Definition at line 36 of file ExternalContext.h.
{ return _max_num_threads; }
ruy_context()
ruy::Context * onert::backend::cpu::ExternalContext::ruy_context () const inline
Definition at line 38 of file ExternalContext.h.
{ return _ruy_context.get(); }
setMaxNumThreads()
void onert::backend::cpu::ExternalContext::setMaxNumThreads (int max_num_threads)
Definition at line 67 of file ExternalContext.cc.
{
  _max_num_threads = max_num_threads > -1 ? max_num_threads : countPhysicalCores();
  _ruy_context->set_max_num_threads(_max_num_threads);
}
Referenced by ExternalContext().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ExternalContext.h
runtime/onert/backend/cpu/ExternalContext.cc