ONE - On-device Neural Engine: benchmark::MemoryPoller Class Reference
benchmark::MemoryPoller Class Reference
#include <MemoryPoller.h>
Public Member Functions
MemoryPoller (std::chrono::milliseconds duration=std::chrono::milliseconds(5), bool gpu_poll=false)
virtual ~MemoryPoller ()
bool start (PhaseEnum phase)
bool end (PhaseEnum phase)
const std::unordered_map< PhaseEnum, uint32_t > & getRssMap () const
const std::unordered_map< PhaseEnum, uint32_t > & getHwmMap () const
const std::unordered_map< PhaseEnum, uint32_t > & getPssMap () const
Detailed Description
Definition at line 38 of file MemoryPoller.h.
Constructor & Destructor Documentation
MemoryPoller()
benchmark::MemoryPoller::MemoryPoller (std::chrono::milliseconds duration = std::chrono::milliseconds(5), bool gpu_poll = false)
Definition at line 29 of file MemoryPoller.cpp.
  : _duration(duration), _run(false), _term(false), _gpu_poll(gpu_poll)
{
  if (prepareMemoryPolling() == false)
    throw std::runtime_error("failed to prepare memory pooling");
  _thread = std::thread{&MemoryPoller::process, this};
}
~MemoryPoller()
virtual benchmark::MemoryPoller::~MemoryPoller () inline virtual
Definition at line 44 of file MemoryPoller.h.
  {
    _term = true;
    _cond_var_started.notify_all();
    _thread.join();
  }
Member Function Documentation
end()
bool benchmark::MemoryPoller::end (PhaseEnum phase)
Definition at line 59 of file MemoryPoller.cpp.
{
  if (std::find(_phases.begin(), _phases.end(), phase) == _phases.end())
  {
    std::cerr << getPhaseString(phase) << " is not started..." << std::endl;
    return false;
  }
  uint32_t mem = 0;
  bool stop = false;
  {
    std::lock_guard<std::mutex> lock(_mutex);
    _phases.remove(phase);
    stop = (_phases.size() == 0);
  }
  mem = getVmRSS();
  if (_gpu_poll)
  {
    mem += getGpuMemory(_process_name);
  }
  if (mem > _rss_map[phase])
    _rss_map[phase] = mem;
  mem = getVmHWM();
  if (_gpu_poll)
  {
    mem += getGpuMemory(_process_name);
  }
  _hwm_map[phase] = mem;
  mem = getPssSum();
  if (mem > _pss_map[phase])
    _pss_map[phase] = mem;
  if (stop)
  {
    _run = false;
    _cond_var_started.notify_all();
  }
  return true;
}
References benchmark::getGpuMemory(), benchmark::getPhaseString(), benchmark::getPssSum(), benchmark::getVmHWM(), and benchmark::getVmRSS().
getHwmMap()
const std::unordered_map< PhaseEnum, uint32_t > & benchmark::MemoryPoller::getHwmMap () const inline
Definition at line 54 of file MemoryPoller.h.
{ return _hwm_map; }
getPssMap()
const std::unordered_map< PhaseEnum, uint32_t > & benchmark::MemoryPoller::getPssMap () const inline
Definition at line 55 of file MemoryPoller.h.
{ return _pss_map; }
getRssMap()
const std::unordered_map< PhaseEnum, uint32_t > & benchmark::MemoryPoller::getRssMap () const inline
Definition at line 53 of file MemoryPoller.h.
{ return _rss_map; }
start()
bool benchmark::MemoryPoller::start (PhaseEnum phase)
Definition at line 38 of file MemoryPoller.cpp.
{
  if (std::find(_phases.begin(), _phases.end(), phase) != _phases.end())
  {
    std::cerr << getPhaseString(phase) << " is already processing/processed..." << std::endl;
    return false;
  }
  {
    std::lock_guard<std::mutex> lock(_mutex);
    _phases.emplace_back(phase);
    _rss_map[phase] = 0;
    _hwm_map[phase] = 0;
    _pss_map[phase] = 0;
  }
  _run = true;
  _cond_var_started.notify_all();
  return true;
}
References benchmark::getPhaseString().
The documentation for this class was generated from the following files:
runtime/libs/benchmark/include/benchmark/MemoryPoller.h
runtime/libs/benchmark/src/MemoryPoller.cpp