ONE - On-device Neural Engine: onert::ir::OperandInfo Class Reference
onert::ir::OperandInfo Class Reference
Class to save tensor's shape and type.
#include <OperandInfo.h>
Public Member Functions
OperandInfo ()=delete
Construct a new OperandInfo object (deleted)
OperandInfo (const Shape &shape, const TypeInfo &typeInfo, MemAllocType alloc_type, bool is_const=false, bool is_variable=false)
Construct a new OperandInfo object.
OperandInfo (const OperandInfo &origin)=default
Construct a new OperandInfo object.
const Shape & shape () const
Return tensor shape.
Shape & shape ()
Return mutable tensor shape.
void shape (const ir::Shape &new_shape)
set shape
const TypeInfo & typeInfo () const
Return tensor data type info.
void type (const DataType type)
Set tensor data type.
size_t total_size () const
Return size of tensor (bytes)
MemAllocType memAllocType () const
void setAsConstant ()
void setAsNonConst ()
bool isConstant () const
void setAsVariable ()
bool isVariable () const
bool isDynamic () const
void setDynamic ()
Static Public Member Functions
static OperandInfo createStaticInfo (const Shape &shape, const TypeInfo &typeInfo)
Create a static OperandInfo object.
Detailed Description
Class to save tensor's shape and type.
Definition at line 54 of file OperandInfo.h.
Constructor & Destructor Documentation
OperandInfo() [1/3]
onert::ir::OperandInfo::OperandInfo () delete
Construct a new OperandInfo object (deleted)
Referenced by createStaticInfo().
OperandInfo() [2/3]
onert::ir::OperandInfo::OperandInfo (const Shape & shape, const TypeInfo & typeInfo, MemAllocType alloc_type, bool is_const = false, bool is_variable = false) inline
Construct a new OperandInfo object.
Parameters
[in] shape Tensor shape
[in] typeInfo Tensor data type
[in] alloc_type When the thesor needs memory allocation
Definition at line 68 of file OperandInfo.h.
    : _shape(shape), _typeInfo(typeInfo), _alloc_type(alloc_type), _const(is_const),
      _variable(is_variable)
  {
    // DO NOTHING
  }
OperandInfo() [3/3]
onert::ir::OperandInfo::OperandInfo (const OperandInfo & origin) default
Construct a new OperandInfo object.
Parameters
[in] origin info for copy
Member Function Documentation
createStaticInfo()
static OperandInfo onert::ir::OperandInfo::createStaticInfo (const Shape & shape, const TypeInfo & typeInfo) inline static
Create a static OperandInfo object.
Definition at line 84 of file OperandInfo.h.
  {
    return OperandInfo(shape, typeInfo, MemAllocType::STATIC);
  }
References OperandInfo(), shape(), onert::ir::STATIC, and typeInfo().
Referenced by onert::interp::concat::prepareConcat(), onert::interp::conv2d::prepareConv2D(), onert::interp::fc::prepareFC(), onert::interp::pool2d::preparePool2D(), onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::registerTensorInfo(), onert::exec::Execution::setInput(), and onert::exec::Execution::setOutput().
isConstant()
bool onert::ir::OperandInfo::isConstant () const inline
Definition at line 122 of file OperandInfo.h.
  {
    // Impossible case: constant and dynamic operand
    assert(!(isDynamic() && _const));
    return _const;
  }
References isDynamic().
Referenced by onert::backend::basic::ExternalTensor::ExternalTensor(), onert::backend::basic::Tensor::is_constant(), and onert::ir::Operand::isConstant().
isDynamic()
bool onert::ir::OperandInfo::isDynamic () const inline
Definition at line 136 of file OperandInfo.h.
{ return _alloc_type == MemAllocType::DYNAMIC; }
References onert::ir::DYNAMIC.
Referenced by onert::compiler::StaticShapeInferer::dump(), onert::backend::basic::ExternalTensor::ExternalTensor(), onert::backend::basic::Tensor::is_dynamic(), onert::backend::builtin::IOTensor::is_dynamic(), isConstant(), and setAsVariable().
isVariable()
bool onert::ir::OperandInfo::isVariable () const inline
Definition at line 135 of file OperandInfo.h.
{ return _variable; }
memAllocType()
MemAllocType onert::ir::OperandInfo::memAllocType () const inline
Definition at line 119 of file OperandInfo.h.
{ return _alloc_type; }
setAsConstant()
void onert::ir::OperandInfo::setAsConstant () inline
Definition at line 120 of file OperandInfo.h.
{ _const = true; }
Referenced by onert::ir::Operand::data().
setAsNonConst()
void onert::ir::OperandInfo::setAsNonConst () inline
Definition at line 121 of file OperandInfo.h.
{ _const = false; }
setAsVariable()
void onert::ir::OperandInfo::setAsVariable () inline
Definition at line 128 of file OperandInfo.h.
  {
    // Impossible case: constant or dynamic operand
    // The variable operand with buffer is not supported yet
    assert(!(isDynamic() || _const));
    _variable = true;
  }
References isDynamic().
setDynamic()
void onert::ir::OperandInfo::setDynamic () inline
Definition at line 137 of file OperandInfo.h.
{ _alloc_type = MemAllocType::DYNAMIC; }
References onert::ir::DYNAMIC.
Referenced by onert::backend::basic::Tensor::set_dynamic().
shape() [1/3]
Shape & onert::ir::OperandInfo::shape () inline
Return mutable tensor shape.
Returns
Tensor shape
Definition at line 99 of file OperandInfo.h.
{ return _shape; }
shape() [2/3]
const Shape & onert::ir::OperandInfo::shape () const inline
Return tensor shape.
Returns
Tensor shape
Definition at line 94 of file OperandInfo.h.
{ return _shape; }
Referenced by onert::backend::builtin::IOTensor::applyShape(), createStaticInfo(), onert::compiler::StaticShapeInferer::dump(), onert::backend::basic::Tensor::getShape(), onert::backend::builtin::UserTensor::getShape(), onert::interp::ROTensor::getShape(), onert::interp::Tensor::getShape(), onert::interp::conv2d::invoke(), onert::interp::fc::invoke(), onert::interp::instancenorm::invoke(), onert::interp::concat::invoke(), onert::interp::pool2d::invokePool2DOps(), onert::interp::ROTensor::num_elements(), onert::interp::Tensor::num_elements(), onert::backend::basic::Tensor::setShape(), onert::backend::builtin::UserTensor::setShape(), onert::backend::builtin::IOTensor::setShape(), onert::backend::builtin::IOTensor::setShapeOfIPortableTensor(), and onert::ir::Operand::shape().
shape() [3/3]
void onert::ir::OperandInfo::shape (const ir::Shape & new_shape) inline
set shape
Definition at line 103 of file OperandInfo.h.
{ _shape = new_shape; }
total_size()
size_t onert::ir::OperandInfo::total_size () const inline
Return size of tensor (bytes)
Returns
Tensor size
Definition at line 117 of file OperandInfo.h.
{ return _shape.num_elements() * sizeOfDataType(_typeInfo.type()); }
References onert::ir::sizeOfDataType(), and onert::ir::TypeInfo::type().
Referenced by onert::backend::basic::Tensor::total_size(), onert::interp::ROTensor::total_size(), and onert::interp::Tensor::total_size().
type()
void onert::ir::OperandInfo::type (const DataType type) inline
Set tensor data type.
Definition at line 112 of file OperandInfo.h.
{ _typeInfo.type(type); }
References onert::ir::TypeInfo::type(), and type().
Referenced by OptionBuilder.OptionBuilder::build(), onert::ir::Operand::type(), and type().
typeInfo()
const TypeInfo & onert::ir::OperandInfo::typeInfo () const inline
Return tensor data type info.
Returns
Tensor data type
Definition at line 108 of file OperandInfo.h.
{ return _typeInfo; }
Referenced by createStaticInfo(), onert::backend::IPortableTensor::data_scale(), onert::interp::ROTensor::data_scale(), onert::interp::Tensor::data_scale(), onert::backend::IPortableTensor::data_scales(), onert::interp::ROTensor::data_scales(), onert::interp::Tensor::data_scales(), onert::backend::basic::Tensor::data_type(), onert::backend::builtin::UserTensor::data_type(), onert::interp::ROTensor::data_type(), onert::interp::Tensor::data_type(), onert::backend::IPortableTensor::data_zero_point(), onert::interp::ROTensor::data_zero_point(), onert::interp::Tensor::data_zero_point(), onert::backend::IPortableTensor::data_zero_points(), onert::interp::ROTensor::data_zero_points(), onert::interp::Tensor::data_zero_points(), onert::backend::basic::Tensor::sparsity(), and onert::ir::Operand::typeInfo().
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/OperandInfo.h