ONE - On-device Neural Engine: loco::Node Class Reference
loco::Node Class Reference abstract
Logical unit of computation.
#include <Node.h>
Public Member Functions
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Friends
class Use
class Subst< SubstQualifier::Default >
class NodePool
std::set< Node * > succs (const Node *node)
Enumerate all the successors of a given node.
Detailed Description
Logical unit of computation.
Definition at line 53 of file Node.h.
Constructor & Destructor Documentation
Node() [1/3]
loco::Node::Node () default
Node() [2/3]
loco::Node::Node (const Node &) delete
Node() [3/3]
loco::Node::Node (Node &&) delete
~Node()
loco::Node::~Node () virtual
Definition at line 25 of file Node.cpp.
{
  // To detect dangling references
  assert(_uses.size() == 0);
}
Member Function Documentation
arg()
virtual Node * loco::Node::arg (uint32_t N) const pure virtual
Access N-th argument node.
Implemented in locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::ADD > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >, locoex::FixedArityNode< 0, TFLNodeImpl< TFLOpcode::CONST > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::CONV_2D > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::DEPTHWISE_CONV_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::DIV > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MAXIMUM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::RESHAPE > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RSQRT > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::SQRT > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SQUARED_DIFFERENCE > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SUB > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::TRANSPOSE_CONV > >, locoex::VariadicArityNode< COpNode >, locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ABS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ADD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MIN > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::AVERAGE_POOL_2D > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::BCQ_GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::BATCH_MATMUL > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::BATCH_TO_SPACE_ND > >, luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEBIDIRECTIONAL_SEQUENCE_LSTM_OUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CAST > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CEIL > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLECONST > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::COS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLECUSTOMOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DENSIFY > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEPTH_TO_SPACE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEQUANTIZE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::DIV > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::EXP > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EXPAND_DIMS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FAKE_QUANT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FILL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FLOOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_DIV > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_MOD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::FULLY_CONNECTED > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEIFOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEINPUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_POOL_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LEAKY_RELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG_SOFTMAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_AND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGICAL_NOT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_OR > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGISTIC > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MATRIX_DIAG > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MATRIX_SET_DIAG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MAXIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MEAN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MINIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MIRROR_PAD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MUL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::NEG > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V4 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV4OUT > >, luci::FixedArityNode< 6, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V5 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV5OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::NOT_EQUAL > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::ONE_HOT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTDUMMY > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTEXCLUDE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PRELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PAD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::PADV2 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::POW > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::QUANTIZE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::RANGE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RANK > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_ANY > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MIN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_PROD > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU6 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU_N1_TO_1 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESHAPE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_BILINEAR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_SEQUENCE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ROUND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RSQRT > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::SVDF > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SCATTER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SEGMENT_SUM > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SHAPE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SIN > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SLICE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SOFTMAX > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPACE_TO_BATCH_ND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SPACE_TO_DEPTH > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::SPARSE_TO_DENSE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SPLIT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITOUT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPLIT_V > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITVOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQRT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUARE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SQUARED_DIFFERENCE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUEEZE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::STRIDED_SLICE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUB > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::TANH > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TILE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TOPK_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLETOPKV2OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TRANSPOSE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >, luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNIQUE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNIQUEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNPACK > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNPACKOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEVARIABLE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::WHERE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEWHILEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ZEROS_LIKE > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CUSTOM > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::IF > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::PACK > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Add > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::BiasAdd > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Const > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::DepthwiseConv2dNative > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::FakeQuantWithMinMaxVars > >, moco::FixedArityNode< 5, TFNodeImpl< TFOpcode::FusedBatchNorm > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Identity > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::MaxPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Maximum > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mean > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mul > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Pad > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Placeholder > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::TFPush > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::RealDiv > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu6 > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Reshape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Rsqrt > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Softmax > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Sqrt > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Squeeze > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::StopGradient > >, moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Sub > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Tanh > >, moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >, and moco::VariadicArityNode< TFNodeImpl< TFOpcode::Pack > >.
Referenced by luci::CircleNodeSummaryBuilder::build(), locop::GenericNodeSummaryBuilder::build(), luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::group_has_type(), dalgona::inputsPyArray(), luci::DeadNodeQueryServiceImpl::isDeadNode(), loco::preds(), and luci::OperationExporterRule::visit().
arity()
virtual uint32_t loco::Node::arity (void) const pure virtual
Return the number of arguments.
Implemented in locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::ADD > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >, locoex::FixedArityNode< 0, TFLNodeImpl< TFLOpcode::CONST > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::CONV_2D > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::DEPTHWISE_CONV_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::DIV > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MAXIMUM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::RESHAPE > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RSQRT > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::SQRT > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SQUARED_DIFFERENCE > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SUB > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::TRANSPOSE_CONV > >, locoex::VariadicArityNode< COpNode >, locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ABS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ADD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MIN > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::AVERAGE_POOL_2D > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::BCQ_GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::BATCH_MATMUL > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::BATCH_TO_SPACE_ND > >, luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEBIDIRECTIONAL_SEQUENCE_LSTM_OUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CAST > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CEIL > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLECONST > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::COS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLECUSTOMOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DENSIFY > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEPTH_TO_SPACE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEQUANTIZE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::DIV > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::EXP > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EXPAND_DIMS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FAKE_QUANT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FILL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FLOOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_DIV > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_MOD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::FULLY_CONNECTED > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEIFOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEINPUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_POOL_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LEAKY_RELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG_SOFTMAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_AND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGICAL_NOT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_OR > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGISTIC > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MATRIX_DIAG > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MATRIX_SET_DIAG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MAXIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MEAN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MINIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MIRROR_PAD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MUL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::NEG > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V4 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV4OUT > >, luci::FixedArityNode< 6, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V5 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV5OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::NOT_EQUAL > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::ONE_HOT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTDUMMY > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTEXCLUDE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PRELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PAD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::PADV2 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::POW > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::QUANTIZE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::RANGE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RANK > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_ANY > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MIN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_PROD > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU6 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU_N1_TO_1 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESHAPE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_BILINEAR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_SEQUENCE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ROUND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RSQRT > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::SVDF > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SCATTER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SEGMENT_SUM > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SHAPE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SIN > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SLICE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SOFTMAX > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPACE_TO_BATCH_ND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SPACE_TO_DEPTH > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::SPARSE_TO_DENSE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SPLIT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITOUT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPLIT_V > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITVOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQRT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUARE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SQUARED_DIFFERENCE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUEEZE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::STRIDED_SLICE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUB > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::TANH > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TILE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TOPK_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLETOPKV2OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TRANSPOSE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >, luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNIQUE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNIQUEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNPACK > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNPACKOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEVARIABLE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::WHERE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEWHILEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ZEROS_LIKE > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CUSTOM > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::IF > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::PACK > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Add > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::BiasAdd > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Const > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::DepthwiseConv2dNative > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::FakeQuantWithMinMaxVars > >, moco::FixedArityNode< 5, TFNodeImpl< TFOpcode::FusedBatchNorm > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Identity > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::MaxPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Maximum > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mean > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mul > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Pad > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Placeholder > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::TFPush > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::RealDiv > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu6 > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Reshape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Rsqrt > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Softmax > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Sqrt > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Squeeze > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::StopGradient > >, moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Sub > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Tanh > >, moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >, and moco::VariadicArityNode< TFNodeImpl< TFOpcode::Pack > >.
Referenced by luci::CircleNodeSummaryBuilder::build(), locop::GenericNodeSummaryBuilder::build(), luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::group_has_type(), dalgona::inputsPyArray(), luci::DeadNodeQueryServiceImpl::isDeadNode(), loco::preds(), and luci::OperationExporterRule::visit().
dialect()
virtual const Dialect * loco::Node::dialect (void) const pure virtual
Return "Dialect" identifier that this node belongs to.
dialect() SHOULD return a valid pointer.
Implemented in locoex::CircleNode, locoex::TFLNode, loco::CanonicalNode, locoex::COpNode, luci::CircleNode, and moco::TFNode.
Referenced by luci::CircleNodeSummaryBuilder::build(), locop::CanonicalNodeSummaryBuilder::build(), locop::GenericNodeSummaryBuilder::build(), locoex::COpNodeSummaryBuilder::build(), moco::TFShapeInferenceRule::infer(), loco::CanonicalShapeInferenceRule::infer(), locoex::CircleTypeInferenceRule::infer(), locoex::TFLTypeInferenceRule::infer(), locoex::COpTypeInferenceRule::infer(), luci::CircleTypeInferenceRule::infer(), moco::TFTypeInferenceRule::infer(), locoex::CircleShapeInferenceRule::infer(), locoex::TFLShapeInferenceRule::infer(), locoex::COpShapeInferenceRule::infer(), luci::CircleShapeInferenceRule::infer(), loco::CanonicalTypeInferenceRule::infer(), loco::MultiDialectTypeInferenceRule::infer(), loco::MultiDialectShapeInferenceRule::infer(), exo::FuseReluPass::run(), logo::SimplifyDomainConversionPass::run(), loco::ShapeInferenceSession::to(), and loco::TypeInferenceSession::to().
drop()
virtual void loco::Node::drop (void) pure virtual
Drop all the reference of arguments.
arg(n) SHOULD return nullptr for every valid n after drop() call.
Implemented in locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::ADD > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >, locoex::FixedArityNode< 0, TFLNodeImpl< TFLOpcode::CONST > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::CONV_2D > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::DEPTHWISE_CONV_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::DIV > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MAXIMUM > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::RESHAPE > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RSQRT > >, locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::SQRT > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SQUARED_DIFFERENCE > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::SUB > >, locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >, locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::TRANSPOSE_CONV > >, locoex::VariadicArityNode< COpNode >, locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ABS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ADD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::ARG_MIN > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::AVERAGE_POOL_2D > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::BCQ_GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::BATCH_MATMUL > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::BATCH_TO_SPACE_ND > >, luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEBIDIRECTIONAL_SEQUENCE_LSTM_OUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CAST > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CEIL > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLECONST > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::COS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLECUSTOMOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DENSIFY > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEPTH_TO_SPACE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::DEQUANTIZE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::DIV > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::EXP > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::EXPAND_DIMS > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FAKE_QUANT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FILL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::FLOOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_DIV > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::FLOOR_MOD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::FULLY_CONNECTED > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GATHER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::GREATER_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEIFOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEINPUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::L2_POOL_2D > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LEAKY_RELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LESS_EQUAL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOG_SOFTMAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_AND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGICAL_NOT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::LOGICAL_OR > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOGISTIC > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MATRIX_DIAG > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MATRIX_SET_DIAG > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MAXIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MEAN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MINIMUM > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MIRROR_PAD > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::MUL > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::NEG > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V4 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV4OUT > >, luci::FixedArityNode< 6, CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V5 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV5OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::NOT_EQUAL > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::ONE_HOT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTDUMMY > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTEXCLUDE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PRELU > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::PAD > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::PADV2 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::POW > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::QUANTIZE > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::RANGE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RANK > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_ANY > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MAX > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_MIN > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REDUCE_PROD > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU6 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RELU_N1_TO_1 > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESHAPE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_BILINEAR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_SEQUENCE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::REVERSE_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ROUND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::RSQRT > >, luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::SVDF > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SCATTER_ND > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SEGMENT_SUM > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SELECT_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SHAPE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SIN > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SLICE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SOFTMAX > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPACE_TO_BATCH_ND > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SPACE_TO_DEPTH > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::SPARSE_TO_DENSE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SPLIT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITOUT > >, luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::SPLIT_V > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLESPLITVOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQRT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUARE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SQUARED_DIFFERENCE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::SQUEEZE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::STRIDED_SLICE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUB > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::SUM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::TANH > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TILE > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TOPK_V2 > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLETOPKV2OUT > >, luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::TRANSPOSE > >, luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >, luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNIQUE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNIQUEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::UNPACK > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEUNPACKOUT > >, luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLEVARIABLE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::WHERE > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEWHILEOUT > >, luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::ZEROS_LIKE > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CUSTOM > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::IF > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::PACK > >, luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Add > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::AvgPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::BiasAdd > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Const > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::DepthwiseConv2dNative > >, moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::FakeQuantWithMinMaxVars > >, moco::FixedArityNode< 5, TFNodeImpl< TFOpcode::FusedBatchNorm > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Identity > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::MaxPool > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Maximum > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mean > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Mul > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Pad > >, moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Placeholder > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::TFPush > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::RealDiv > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Relu6 > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Reshape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Rsqrt > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Softmax > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Sqrt > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Squeeze > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::StopGradient > >, moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >, moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Sub > >, moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Tanh > >, moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >, and moco::VariadicArityNode< TFNodeImpl< TFOpcode::Pack > >.
Referenced by luci::fuse_activation_function(), and loco::NodePool::~NodePool().
graph() [1/2]
Graph * loco::Node::graph (void) inline
Definition at line 70 of file Node.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), luci::clone(), exo::AvgPool2DConverter::convert(), exo::ConstGenConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MatMulConverter::convert(), exo::MaxPool2DConverter::convert(), exo::TensorConcatConverter::convert(), exo::TensorTransposeConverter::convert(), exo::TransposedConv2DConverter::convert(), loco::Pull::dtype(), loco::Pull::index(), luci::DeadNodeQueryServiceImpl::isDeadNode(), exo::make_dw_filter_decode(), exo::make_feature_decode(), exo::make_feature_encode(), exo::make_filter_decode(), exo::make_filter_encode(), exo::make_matrix_decode(), exo::make_matrix_encode(), locoex::set_new_shape(), TopologicalSortHelper.TopologicalSortHelper::sort_util(), moco::tf::ConcatV2Canonicalizer::transform(), moco::tf::ConstCanonicalizer::transform(), moco::tf::Conv2DBackpropInputCanonicalizer::transform(), moco::tf::DepthwiseConv2dNativeCanonicalizer::transform(), moco::tf::IdentityCanonicalizer::transform(), moco::tf::MaxPoolCanonicalizer::transform(), moco::tf::PadCanonicalizer::transform(), moco::tf::PlaceholderCanonicalizer::transform(), moco::tf::TFPushCanonicalizer::transform(), moco::tf::ReluCanonicalizer::transform(), moco::tf::Relu6Canonicalizer::transform(), moco::tf::ReshapeCanonicalizer::transform(), moco::tf::RsqrtCanonicalizer::transform(), moco::tf::SoftmaxCanonicalizer::transform(), moco::tf::SqrtCanonicalizer::transform(), moco::tf::SqueezeCanonicalizer::transform(), moco::tf::StopGradientCanonicalizer::transform(), moco::tf::TanhCanonicalizer::transform(), moco::tf::AvgPoolCanonicalizer::transform(), moco::tf::BiasAddCanonicalizer::transform(), and moco::tf::Conv2DCanonicalizer::transform().
graph() [2/2]
const Graph * loco::Node::graph (void) const inline
Definition at line 71 of file Node.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
opnum()
virtual uint32_t loco::Node::opnum (void) const pure virtual
Implemented in locoex::CircleNodeImpl< Code >, locoex::CircleNodeImpl< CircleOpcode::INSTANCE_NORM >, locoex::TFLNodeImpl< Code >, locoex::TFLNodeImpl< TFLOpcode::ADD >, locoex::TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D >, locoex::TFLNodeImpl< TFLOpcode::CONCATENATION >, locoex::TFLNodeImpl< TFLOpcode::CONST >, locoex::TFLNodeImpl< TFLOpcode::CONV_2D >, locoex::TFLNodeImpl< TFLOpcode::DEPTHWISE_CONV_2D >, locoex::TFLNodeImpl< TFLOpcode::DIV >, locoex::TFLNodeImpl< TFLOpcode::FULLY_CONNECTED >, locoex::TFLNodeImpl< TFLOpcode::MAX_POOL_2D >, locoex::TFLNodeImpl< TFLOpcode::MAXIMUM >, locoex::TFLNodeImpl< TFLOpcode::MEAN >, locoex::TFLNodeImpl< TFLOpcode::MUL >, locoex::TFLNodeImpl< TFLOpcode::RELU >, locoex::TFLNodeImpl< TFLOpcode::RELU6 >, locoex::TFLNodeImpl< TFLOpcode::RESHAPE >, locoex::TFLNodeImpl< TFLOpcode::RSQRT >, locoex::TFLNodeImpl< TFLOpcode::SQRT >, locoex::TFLNodeImpl< TFLOpcode::SQUARED_DIFFERENCE >, locoex::TFLNodeImpl< TFLOpcode::SUB >, locoex::TFLNodeImpl< TFLOpcode::TRANSPOSE >, locoex::TFLNodeImpl< TFLOpcode::TRANSPOSE_CONV >, loco::CanonicalNodeDef< Code, Mixins >, loco::CanonicalNodeDef< CanonicalOpcode::AvgPool2D, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FeatureBiasAdd, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorBiasAdd, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::BiasDecode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::BiasEncode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::ConstGen, FixedArity< 0 >::Mixin, With< NodeTrait::DataType >::Mixin, With< NodeTrait::TensorShape >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::Conv2D, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::DepthwiseConv2D, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::DepthwiseFilterDecode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::DepthwiseFilterEncode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseAdd, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseDiv, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseMax, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseMul, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseSqrt, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::EltwiseSub, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FeatureDecode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FeatureEncode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FilterDecode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FilterEncode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::Forward, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::MatMul, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::MatrixDecode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::MatrixEncode, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::MaxPool2D, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::Pull, FixedArity< 0 >::Mixin, With< NodeTrait::TensorShape >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::Push, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::ReLU, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::ReLU6, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::FixedReshape, FixedArity< 1 >::Mixin, With< NodeTrait::TensorShape >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorSoftmax, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::Tanh, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorBroadcast, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorConcat, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorConstantPad, FixedArity< 2 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorReduce, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TensorTranspose, FixedArity< 1 >::Mixin >, loco::CanonicalNodeDef< CanonicalOpcode::TransposedConv2D, FixedArity< 2 >::Mixin >, locoex::COpNode, luci::CircleNodeImpl< Code >, luci::CircleNodeImpl< CircleOpcode::ABS >, luci::CircleNodeImpl< CircleOpcode::ADD >, luci::CircleNodeImpl< CircleOpcode::ADD_N >, luci::CircleNodeImpl< CircleOpcode::ARG_MAX >, luci::CircleNodeImpl< CircleOpcode::ARG_MIN >, luci::CircleNodeImpl< CircleOpcode::AVERAGE_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED >, luci::CircleNodeImpl< CircleOpcode::BCQ_GATHER >, luci::CircleNodeImpl< CircleOpcode::BATCH_MATMUL >, luci::CircleNodeImpl< CircleOpcode::BATCH_TO_SPACE_ND >, luci::CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM >, luci::CircleNodeImpl< CircleOpcode::CIRCLEBIDIRECTIONAL_SEQUENCE_LSTM_OUT >, luci::CircleNodeImpl< CircleOpcode::CAST >, luci::CircleNodeImpl< CircleOpcode::CEIL >, luci::CircleNodeImpl< CircleOpcode::CONCATENATION >, luci::CircleNodeImpl< CircleOpcode::CIRCLECONST >, luci::CircleNodeImpl< CircleOpcode::CONV_2D >, luci::CircleNodeImpl< CircleOpcode::COS >, luci::CircleNodeImpl< CircleOpcode::CUSTOM >, luci::CircleNodeImpl< CircleOpcode::CIRCLECUSTOMOUT >, luci::CircleNodeImpl< CircleOpcode::DENSIFY >, luci::CircleNodeImpl< CircleOpcode::DEPTH_TO_SPACE >, luci::CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D >, luci::CircleNodeImpl< CircleOpcode::DEQUANTIZE >, luci::CircleNodeImpl< CircleOpcode::DIV >, luci::CircleNodeImpl< CircleOpcode::ELU >, luci::CircleNodeImpl< CircleOpcode::EQUAL >, luci::CircleNodeImpl< CircleOpcode::EXP >, luci::CircleNodeImpl< CircleOpcode::EXPAND_DIMS >, luci::CircleNodeImpl< CircleOpcode::FAKE_QUANT >, luci::CircleNodeImpl< CircleOpcode::FILL >, luci::CircleNodeImpl< CircleOpcode::FLOOR >, luci::CircleNodeImpl< CircleOpcode::FLOOR_DIV >, luci::CircleNodeImpl< CircleOpcode::FLOOR_MOD >, luci::CircleNodeImpl< CircleOpcode::FULLY_CONNECTED >, luci::CircleNodeImpl< CircleOpcode::GATHER >, luci::CircleNodeImpl< CircleOpcode::GATHER_ND >, luci::CircleNodeImpl< CircleOpcode::GREATER >, luci::CircleNodeImpl< CircleOpcode::GREATER_EQUAL >, luci::CircleNodeImpl< CircleOpcode::IF >, luci::CircleNodeImpl< CircleOpcode::CIRCLEIFOUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEINPUT >, luci::CircleNodeImpl< CircleOpcode::L2_NORMALIZATION >, luci::CircleNodeImpl< CircleOpcode::L2_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::LEAKY_RELU >, luci::CircleNodeImpl< CircleOpcode::LESS >, luci::CircleNodeImpl< CircleOpcode::LESS_EQUAL >, luci::CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION >, luci::CircleNodeImpl< CircleOpcode::LOG >, luci::CircleNodeImpl< CircleOpcode::LOG_SOFTMAX >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_AND >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_NOT >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_OR >, luci::CircleNodeImpl< CircleOpcode::LOGISTIC >, luci::CircleNodeImpl< CircleOpcode::MATRIX_DIAG >, luci::CircleNodeImpl< CircleOpcode::MATRIX_SET_DIAG >, luci::CircleNodeImpl< CircleOpcode::MAX_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::MAXIMUM >, luci::CircleNodeImpl< CircleOpcode::MEAN >, luci::CircleNodeImpl< CircleOpcode::MINIMUM >, luci::CircleNodeImpl< CircleOpcode::MIRROR_PAD >, luci::CircleNodeImpl< CircleOpcode::MUL >, luci::CircleNodeImpl< CircleOpcode::NEG >, luci::CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V4 >, luci::CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV4OUT >, luci::CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V5 >, luci::CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV5OUT >, luci::CircleNodeImpl< CircleOpcode::NOT_EQUAL >, luci::CircleNodeImpl< CircleOpcode::ONE_HOT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTDUMMY >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTEXCLUDE >, luci::CircleNodeImpl< CircleOpcode::PRELU >, luci::CircleNodeImpl< CircleOpcode::PACK >, luci::CircleNodeImpl< CircleOpcode::PAD >, luci::CircleNodeImpl< CircleOpcode::PADV2 >, luci::CircleNodeImpl< CircleOpcode::POW >, luci::CircleNodeImpl< CircleOpcode::QUANTIZE >, luci::CircleNodeImpl< CircleOpcode::RANGE >, luci::CircleNodeImpl< CircleOpcode::RANK >, luci::CircleNodeImpl< CircleOpcode::REDUCE_ANY >, luci::CircleNodeImpl< CircleOpcode::REDUCE_MAX >, luci::CircleNodeImpl< CircleOpcode::REDUCE_MIN >, luci::CircleNodeImpl< CircleOpcode::REDUCE_PROD >, luci::CircleNodeImpl< CircleOpcode::RELU >, luci::CircleNodeImpl< CircleOpcode::RELU6 >, luci::CircleNodeImpl< CircleOpcode::RELU_N1_TO_1 >, luci::CircleNodeImpl< CircleOpcode::RESHAPE >, luci::CircleNodeImpl< CircleOpcode::RESIZE_BILINEAR >, luci::CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR >, luci::CircleNodeImpl< CircleOpcode::REVERSE_SEQUENCE >, luci::CircleNodeImpl< CircleOpcode::REVERSE_V2 >, luci::CircleNodeImpl< CircleOpcode::ROUND >, luci::CircleNodeImpl< CircleOpcode::RSQRT >, luci::CircleNodeImpl< CircleOpcode::SVDF >, luci::CircleNodeImpl< CircleOpcode::SCATTER_ND >, luci::CircleNodeImpl< CircleOpcode::SEGMENT_SUM >, luci::CircleNodeImpl< CircleOpcode::SELECT >, luci::CircleNodeImpl< CircleOpcode::SELECT_V2 >, luci::CircleNodeImpl< CircleOpcode::SHAPE >, luci::CircleNodeImpl< CircleOpcode::SIN >, luci::CircleNodeImpl< CircleOpcode::SLICE >, luci::CircleNodeImpl< CircleOpcode::SOFTMAX >, luci::CircleNodeImpl< CircleOpcode::SPACE_TO_BATCH_ND >, luci::CircleNodeImpl< CircleOpcode::SPACE_TO_DEPTH >, luci::CircleNodeImpl< CircleOpcode::SPARSE_TO_DENSE >, luci::CircleNodeImpl< CircleOpcode::SPLIT >, luci::CircleNodeImpl< CircleOpcode::CIRCLESPLITOUT >, luci::CircleNodeImpl< CircleOpcode::SPLIT_V >, luci::CircleNodeImpl< CircleOpcode::CIRCLESPLITVOUT >, luci::CircleNodeImpl< CircleOpcode::SQRT >, luci::CircleNodeImpl< CircleOpcode::SQUARE >, luci::CircleNodeImpl< CircleOpcode::SQUARED_DIFFERENCE >, luci::CircleNodeImpl< CircleOpcode::SQUEEZE >, luci::CircleNodeImpl< CircleOpcode::STRIDED_SLICE >, luci::CircleNodeImpl< CircleOpcode::SUB >, luci::CircleNodeImpl< CircleOpcode::SUM >, luci::CircleNodeImpl< CircleOpcode::TANH >, luci::CircleNodeImpl< CircleOpcode::TILE >, luci::CircleNodeImpl< CircleOpcode::TOPK_V2 >, luci::CircleNodeImpl< CircleOpcode::CIRCLETOPKV2OUT >, luci::CircleNodeImpl< CircleOpcode::TRANSPOSE >, luci::CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV >, luci::CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM >, luci::CircleNodeImpl< CircleOpcode::UNIQUE >, luci::CircleNodeImpl< CircleOpcode::CIRCLEUNIQUEOUT >, luci::CircleNodeImpl< CircleOpcode::UNPACK >, luci::CircleNodeImpl< CircleOpcode::CIRCLEUNPACKOUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEVARIABLE >, luci::CircleNodeImpl< CircleOpcode::WHERE >, luci::CircleNodeImpl< CircleOpcode::WHILE >, luci::CircleNodeImpl< CircleOpcode::CIRCLEWHILEOUT >, luci::CircleNodeImpl< CircleOpcode::ZEROS_LIKE >, moco::TFNodeImpl< Code >, moco::TFNodeImpl< TFOpcode::Add >, moco::TFNodeImpl< TFOpcode::AvgPool >, moco::TFNodeImpl< TFOpcode::BiasAdd >, moco::TFNodeImpl< TFOpcode::ConcatV2 >, moco::TFNodeImpl< TFOpcode::Const >, moco::TFNodeImpl< TFOpcode::Conv2D >, moco::TFNodeImpl< TFOpcode::Conv2DBackpropInput >, moco::TFNodeImpl< TFOpcode::DepthwiseConv2dNative >, moco::TFNodeImpl< TFOpcode::FakeQuantWithMinMaxVars >, moco::TFNodeImpl< TFOpcode::FusedBatchNorm >, moco::TFNodeImpl< TFOpcode::Identity >, moco::TFNodeImpl< TFOpcode::MaxPool >, moco::TFNodeImpl< TFOpcode::Maximum >, moco::TFNodeImpl< TFOpcode::Mean >, moco::TFNodeImpl< TFOpcode::Mul >, moco::TFNodeImpl< TFOpcode::Pack >, moco::TFNodeImpl< TFOpcode::Pad >, moco::TFNodeImpl< TFOpcode::Placeholder >, moco::TFNodeImpl< TFOpcode::TFPush >, moco::TFNodeImpl< TFOpcode::RealDiv >, moco::TFNodeImpl< TFOpcode::Relu >, moco::TFNodeImpl< TFOpcode::Relu6 >, moco::TFNodeImpl< TFOpcode::Reshape >, moco::TFNodeImpl< TFOpcode::Rsqrt >, moco::TFNodeImpl< TFOpcode::Shape >, moco::TFNodeImpl< TFOpcode::Softmax >, moco::TFNodeImpl< TFOpcode::Sqrt >, moco::TFNodeImpl< TFOpcode::SquaredDifference >, moco::TFNodeImpl< TFOpcode::Squeeze >, moco::TFNodeImpl< TFOpcode::StopGradient >, moco::TFNodeImpl< TFOpcode::StridedSlice >, moco::TFNodeImpl< TFOpcode::Sub >, and moco::TFNodeImpl< TFOpcode::Tanh >.
Referenced by locop::GenericNodeSummaryBuilder::build().
Friends And Related Function Documentation
NodePool
friend class NodePool friend
Definition at line 58 of file Node.h.
Subst< SubstQualifier::Default >
friend class Subst< SubstQualifier::Default > friend
Definition at line 56 of file Node.h.
succs
std::set< Node * > succs (const Node * node) friend
Enumerate all the successors of a given node.
Definition at line 46 of file Node.cpp.
{
  std::set<Node *> res;
  for (auto use : node->_uses)
  {
    auto user = use->user();
    assert(user != nullptr);
    res.insert(user);
  }
  return res;
}
Use
friend class Use friend
Definition at line 56 of file Node.h.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/Node.h
compiler/loco/src/IR/Node.cpp