ONE - On-device Neural Engine: moco::UpdateQueue Class Reference
moco::UpdateQueue Class Reference final
Class to store GraphUpdate objects.
#include <GraphBuilderContext.h>
Public Types
using Queue = std::vector< std::unique_ptr< GraphUpdate > >
Public Member Functions
void enroll (std::unique_ptr< GraphUpdate > &&update)
Registers GraphUpdate objects.
const Queue & queue () const
Detailed Description
Class to store GraphUpdate objects.
Definition at line 96 of file GraphBuilderContext.h.
Member Typedef Documentation
Queue
using moco::UpdateQueue::Queue = std::vector<std::unique_ptr<GraphUpdate> >
Definition at line 105 of file GraphBuilderContext.h.
Member Function Documentation
enroll()
void moco::UpdateQueue::enroll (std::unique_ptr< GraphUpdate > && update)
Registers GraphUpdate objects.
Definition at line 75 of file GraphBuilderContext.cpp.
{
  _queue.push_back(std::move(update));
}
References moco::update().
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::tf::COpCallGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::ReshapeGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), and moco::TanhGraphBuilder::build().
queue()
const Queue & moco::UpdateQueue::queue () const inline
Definition at line 107 of file GraphBuilderContext.h.
{ return _queue; }
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/GraphBuilderContext.h
compiler/moco/import/src/GraphBuilderContext.cpp