ONE - On-device Neural Engine: moco::onnx::Identity_V1 Class Reference
moco::onnx::Identity_V1 Class Reference
GraphBuilder for Identity(since version 1) node.
#include <Identity.h>
Public Member Functions
bool validate (const ::onnx::NodeProto &) const
void build (const ::onnx::NodeProto &, GraphBuilderContext *) const
Detailed Description
GraphBuilder for Identity(since version 1) node.
Definition at line 29 of file Identity.h.
Member Function Documentation
build()
void moco::onnx::Identity_V1::build (const ::onnx::NodeProto & node, GraphBuilderContext * context) const
Definition at line 28 of file Identity_V1.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *nodes = context->nodes();
  SymbolTable *input_names = context->input_names();
  // Create a "Forward" node for Identity
  auto forward_node = graph->nodes()->create<loco::Forward>();
  nodes->enroll(node.name(), forward_node);
  nodes->enroll(node.output(0), forward_node);
  // Record all inputs to forward_node
  for (int i = 0; i < node.input_size(); ++i)
  {
    const auto &input_name = node.input(i);
    input_names->list(forward_node, input_name);
  }
}
References moco::onnx::SymbolTable::enroll(), moco::onnx::GraphBuilderContext::graph(), moco::onnx::GraphBuilderContext::input_names(), moco::onnx::SymbolTable::list(), and moco::onnx::GraphBuilderContext::nodes().
Referenced by moco::onnx::IdentityGraphBuilder::build().
validate()
bool moco::onnx::Identity_V1::validate (const ::onnx::NodeProto &) const
Definition at line 26 of file Identity_V1.cpp.
{ return true; }
Referenced by moco::onnx::IdentityGraphBuilder::validate().
The documentation for this class was generated from the following files:
compiler/oneco/src/Op/Identity.h
compiler/oneco/src/Op/Identity_V1.cpp