ONE - On-device Neural Engine: onert::backend::cpu::ops::PowLayer Class Reference
onert::backend::cpu::ops::PowLayer Class Reference
#include <PowLayer.h>
Public Member Functions
PowLayer ()
void powFloat32 ()
void configure (const IPortableTensor *lhs, const IPortableTensor *rhs, const ir::Activation activation, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 34 of file PowLayer.h.
Constructor & Destructor Documentation
PowLayer()
onert::backend::cpu::ops::PowLayer::PowLayer () inline
Definition at line 37 of file PowLayer.h.
             : _lhs(nullptr), _rhs(nullptr), _output(nullptr)
  {
    // DO NOTHING
  }
Member Function Documentation
configure()
void onert::backend::cpu::ops::PowLayer::configure (const IPortableTensor * lhs, const IPortableTensor * rhs, const ir::Activation activation, IPortableTensor * output)
Definition at line 51 of file PowLayer.cc.
{
  _lhs = lhs;
  _rhs = rhs;
  _activation = activation;
  _output = output;
}
powFloat32()
void onert::backend::cpu::ops::PowLayer::powFloat32 ()
Definition at line 31 of file PowLayer.cc.
{
  float output_activation_min = 0, output_activation_max = 0;
  CalculateActivationRange(_activation, &output_activation_min, &output_activation_max);
  nnfw::cker::BinaryArithmeticOpParam op_params;
  op_params.float_activation_max = output_activation_max;
  op_params.float_activation_min = output_activation_min;
  if (!HaveSameShapes(_lhs, _rhs))
  {
    nnfw::cker::BroadcastBinaryArithmeticOp<nnfw::cker::BinaryArithmeticOpType::POW>(
      op_params, getShape(_lhs), getBuffer<float>(_lhs), getShape(_rhs), getBuffer<float>(_rhs),
      getShape(_output), getBuffer<float>(_output));
    return;
  }
  nnfw::cker::powImpl(getShape(_lhs), getBuffer<float>(_lhs), getShape(_rhs),
                      getBuffer<float>(_rhs), getShape(_output), getBuffer<float>(_output));
}
References onert::util::CalculateActivationRange(), nnfw::cker::BinaryArithmeticOpParam::float_activation_max, nnfw::cker::BinaryArithmeticOpParam::float_activation_min, onert::backend::cpu::ops::getShape(), onert::backend::cpu::ops::HaveSameShapes(), and nnfw::cker::powImpl().
Referenced by run().
run()
void onert::backend::cpu::ops::PowLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 60 of file PowLayer.cc.
{
  if (_output->data_type() == OperandType::FLOAT32)
    powFloat32();
  else
    throw std::runtime_error{"Pow: unsupportted data type"};
}
References onert::backend::ITensor::data_type(), and powFloat32().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/PowLayer.h
runtime/onert/backend/cpu/ops/PowLayer.cc