ONE - On-device Neural Engine: onert::backend::basic::Tensor Class Reference
onert::backend::basic::Tensor Class Reference
#include <Tensor.h>
Public Member Functions
Tensor ()=delete
virtual ~Tensor ()
Tensor (const ir::OperandInfo &info, const ir::Layout layout, DynamicMemoryManager *dynamic_mem_mgr)
void setBuffer (uint8_t *buffer)
Set the Buffer object. This method is called for static and non-const tensor.
void setBuffer (const std::shared_ptr< Allocator > &alloc)
Set the Buffer object. This method is called for dynamic or const tensor.
void deallocBuffer () override
Reset the buffer and deallocate the allocation if it is managed by itself.
uint8_t * buffer () const override
size_t total_size () const override
Get dimension by index.
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_constant () const override
Return true if the tensor is constant.
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
bool applyShape (const ir::Shape &new_shape) override
Set the shape to shape and possibly re-allocate the buffer.
const ir::Sparsity * sparsity () const override
virtual void increase_ref ()
virtual void decrease_ref ()
virtual void reset_ref ()
Reset reference count to zero and release data.
virtual int32_t num_references ()
void setShape (const ir::Shape &new_shape) override
Set the shape of tenser to new_shape.
ir::Shape getShape () const override
Get ir::Shape of tensor.
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Protected Attributes
ir::Layout _layout
uint8_t * _buffer
int32_t _num_references
DynamicMemoryManager * _dynamic_mem_mgr
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Definition at line 35 of file Tensor.h.
Constructor & Destructor Documentation
Tensor() [1/2]
onert::backend::basic::Tensor::Tensor () delete
~Tensor()
Tensor::~Tensor () virtual
Definition at line 29 of file Tensor.cc.
{}
Tensor() [2/2]
onert::backend::basic::Tensor::Tensor (const ir::OperandInfo & info, const ir::Layout layout, DynamicMemoryManager * dynamic_mem_mgr) inline
Definition at line 42 of file Tensor.h.
    : IPortableTensor(info), _layout(layout), _buffer(nullptr), _num_references(0),
      _dynamic_mem_mgr(dynamic_mem_mgr), _allocator(nullptr)
  {
    // DO NOTHING
  }
Member Function Documentation
applyShape()
bool Tensor::applyShape (const ir::Shape &) override virtual
Set the shape to shape and possibly re-allocate the buffer.
If a tensor is dynamic tensor and previously allocated memory exists, it will be deallocated. If a tensor is static tensor (with previously allocated memory by StaticTensorManager), buffer() will be overwriten
Parameters
shape tensor's new shape. While allocating memory for this new_shape, tensor's shape is set to new_shape
Returns
true If applying shape is successful
false If not applying shape is not supported (it throws for other errors)
Reimplemented from onert::backend::ITensor.
Definition at line 48 of file Tensor.cc.
{
  bool previously_dynamic = is_dynamic();
  auto allocTensorMem = [&]() {
    auto capacity = total_size();
    auto alloc = _dynamic_mem_mgr->allocate(this, capacity);
    setBuffer(alloc);
  };
  if (!previously_dynamic || buffer() == nullptr)
  {
    // Always set shape - when buffer with same size was already allocated, shape could differ
    setShape(new_shape);
    set_dynamic();
    allocTensorMem();
  }
  else
  {
    auto previous_size = total_size();
    auto new_size = new_shape.num_elements() * ir::sizeOfDataType(data_type());
    if (previous_size != new_size)
    {
      _dynamic_mem_mgr->deallocate(this);
      setShape(new_shape);
      set_dynamic();
      allocTensorMem();
    }
    else
    { // when buffer with same size was already allocated, shape could differ
      setShape(new_shape);
    }
  }
  return true;
}
References _dynamic_mem_mgr, onert::backend::basic::DynamicMemoryManager::allocate(), buffer(), data_type(), onert::backend::basic::DynamicMemoryManager::deallocate(), is_dynamic(), set_dynamic(), setBuffer(), setShape(), onert::ir::sizeOfDataType(), and total_size().
buffer()
uint8_t * onert::backend::basic::Tensor::buffer () const inline override virtual
Implements onert::backend::ITensor.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 73 of file Tensor.h.
{ return _buffer; }
References _buffer.
Referenced by applyShape(), and setBuffer().
calcOffset()
size_t Tensor::calcOffset (const ir::Coordinates & coords) const override virtual
Implements onert::backend::ITensor.
Definition at line 31 of file Tensor.cc.
{
  auto shape = getShape();
  size_t rank = shape.rank();
  rank = rank == 0 ? 1 : rank;
  size_t offset = 0;
  for (size_t i = 0; i < rank; ++i)
  {
    auto dim = shape.rank() == 0 ? 1 : shape.dim(i);
    offset = offset * dim + coords[i];
  }
  offset *= sizeOfDataType(data_type());
  return offset;
}
References coords, data_type(), getShape(), and offset().
data_type()
ir::DataType onert::backend::basic::Tensor::data_type () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 87 of file Tensor.h.
{ return _info.typeInfo().type(); }
References onert::backend::IPortableTensor::_info, onert::ir::TypeInfo::type(), and onert::ir::OperandInfo::typeInfo().
Referenced by applyShape(), and calcOffset().
deallocBuffer()
void Tensor::deallocBuffer () override virtual
Reset the buffer and deallocate the allocation if it is managed by itself.
Reimplemented from onert::backend::ITensor.
Definition at line 87 of file Tensor.cc.
{
  if (_allocator)
  {
    _buffer = nullptr;
    _allocator.reset();
    if (_dynamic_mem_mgr)
    {
      _dynamic_mem_mgr->deallocate(this);
    }
  }
}
References _buffer, _dynamic_mem_mgr, and onert::backend::basic::DynamicMemoryManager::deallocate().
decrease_ref()
virtual void onert::backend::basic::Tensor::decrease_ref () inline virtual
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 103 of file Tensor.h.
  {
    assert(_buffer != nullptr || _allocator != nullptr);
    assert(_num_references > 0);
    --_num_references;
    // constant tensor and dynamic tensor has _allocator
    if (_num_references == 0)
    {
      if (_buffer != nullptr)
        _buffer = nullptr;
      if (_allocator != nullptr)
      {
        _allocator->release();
        _allocator = nullptr;
      }
    }
  }
References _buffer, and _num_references.
getShape()
ir::Shape Tensor::getShape () const override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 85 of file Tensor.cc.
{ return _info.shape(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::shape().
Referenced by calcOffset().
increase_ref()
virtual void onert::backend::basic::Tensor::increase_ref () inline virtual
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 94 of file Tensor.h.
  {
    assert(is_dynamic() ||
           // when not dynamic
           (_buffer != nullptr));
    ++_num_references;
  }
References _buffer, _num_references, and is_dynamic().
is_constant()
bool onert::backend::basic::Tensor::is_constant () const inline override virtual
Return true if the tensor is constant.
Reimplemented from onert::backend::ITensor.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 88 of file Tensor.h.
{ return _info.isConstant(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::isConstant().
is_dynamic()
bool onert::backend::basic::Tensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 89 of file Tensor.h.
{ return _info.isDynamic(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::isDynamic().
Referenced by applyShape(), and increase_ref().
layout()
ir::Layout onert::backend::basic::Tensor::layout () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 86 of file Tensor.h.
{ return _layout; }
References _layout.
num_references()
virtual int32_t onert::backend::basic::Tensor::num_references () inline virtual
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 140 of file Tensor.h.
{ return _num_references; }
References _num_references.
reset_ref()
virtual void onert::backend::basic::Tensor::reset_ref () inline virtual
Reset reference count to zero and release data.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 124 of file Tensor.h.
  {
    assert(_buffer != nullptr || _allocator != nullptr);
    assert(_num_references > 0);
    _num_references = 0;
    // Only constant tensor has allocator pointer
    if (_buffer != nullptr)
      _buffer = nullptr;
    else
    {
      _allocator->release();
      _allocator = nullptr;
    }
  }
References _buffer, and _num_references.
set_dynamic()
void onert::backend::basic::Tensor::set_dynamic () inline override virtual
set this tensor dynamic
Reimplemented from onert::backend::ITensor.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 90 of file Tensor.h.
{ _info.setDynamic(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::setDynamic().
Referenced by applyShape().
setBuffer() [1/2]
void onert::backend::basic::Tensor::setBuffer (const std::shared_ptr< Allocator > & alloc) inline
Set the Buffer object. This method is called for dynamic or const tensor.
Definition at line 61 of file Tensor.h.
  {
    _allocator = alloc;
    _buffer = alloc->base();
  }
References _buffer.
setBuffer() [2/2]
void onert::backend::basic::Tensor::setBuffer (uint8_t * buffer) inline
Set the Buffer object. This method is called for static and non-const tensor.
Definition at line 56 of file Tensor.h.
{ _buffer = buffer; }
References _buffer, and buffer().
Referenced by applyShape().
setShape()
void Tensor::setShape (const ir::Shape & new_shape) override virtual
Set the shape of tenser to new_shape.
Note
Higer dimension will be placed on front.
Reimplemented from onert::backend::ITensor.
Reimplemented in onert::backend::basic::ExternalTensor.
Definition at line 46 of file Tensor.cc.
{ _info.shape(new_shape); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::shape().
Referenced by applyShape().
sparsity()
const ir::Sparsity * onert::backend::basic::Tensor::sparsity () const inline override virtual
Reimplemented from onert::backend::IPortableTensor.
Definition at line 92 of file Tensor.h.
{ return _info.typeInfo().sparsity(); }
References onert::backend::IPortableTensor::_info, onert::ir::TypeInfo::sparsity(), and onert::ir::OperandInfo::typeInfo().
total_size()
size_t onert::backend::basic::Tensor::total_size () const inline override virtual
Get dimension by index.
Parameters
index Index to get diemension
Returns
size_t Dimension at index
Note
N : dimension(0) H : dimension(1) W : dimension(2) C : dimension(3)
Implements onert::backend::ITensor.
Definition at line 84 of file Tensor.h.
{ return _info.total_size(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::total_size().
Referenced by applyShape().
Field Documentation
_buffer
uint8_t* onert::backend::basic::Tensor::_buffer protected
Definition at line 147 of file Tensor.h.
Referenced by buffer(), onert::backend::basic::ExternalTensor::buffer(), deallocBuffer(), decrease_ref(), onert::backend::basic::ExternalTensor::decrease_ref(), increase_ref(), reset_ref(), onert::backend::basic::ExternalTensor::reset_ref(), setBuffer(), and onert::backend::basic::ExternalTensor::setData().
_dynamic_mem_mgr
DynamicMemoryManager* onert::backend::basic::Tensor::_dynamic_mem_mgr protected
Definition at line 149 of file Tensor.h.
Referenced by applyShape(), and deallocBuffer().
_layout
ir::Layout onert::backend::basic::Tensor::_layout protected
Definition at line 146 of file Tensor.h.
Referenced by onert::backend::basic::ExternalTensor::ExternalTensor(), and layout().
_num_references
int32_t onert::backend::basic::Tensor::_num_references protected
Definition at line 148 of file Tensor.h.
Referenced by decrease_ref(), onert::backend::basic::ExternalTensor::decrease_ref(), increase_ref(), onert::backend::basic::ExternalTensor::increase_ref(), num_references(), onert::backend::basic::ExternalTensor::num_references(), reset_ref(), and onert::backend::basic::ExternalTensor::reset_ref().
The documentation for this class was generated from the following files:
runtime/onert/core/include/backend/basic/Tensor.h
runtime/onert/core/src/backend/basic/Tensor.cc