ONE - On-device Neural Engine: locoex::Stride Class Reference
locoex::Stride Class Reference final
#include <TFLNodes.h>
Public Member Functions
Stride ()
int32_t w () const
void w (int32_t w)
int32_t h () const
void h (int32_t h)
Detailed Description
Definition at line 60 of file TFLNodes.h.
Constructor & Destructor Documentation
Stride()
locoex::Stride::Stride () inline
Definition at line 63 of file TFLNodes.h.
: _w(1), _h(1) {}
Member Function Documentation
h() [1/2]
int32_t locoex::Stride::h () const inline
Definition at line 68 of file TFLNodes.h.
{ return _h; }
h() [2/2]
void locoex::Stride::h (int32_t h) inline
Definition at line 69 of file TFLNodes.h.
{ _h = h; }
References h().
Referenced by h().
w() [1/2]
int32_t locoex::Stride::w () const inline
Definition at line 65 of file TFLNodes.h.
{ return _w; }
Referenced by exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), and exo::TransposedConv2DConverter::convert().
w() [2/2]
void locoex::Stride::w (int32_t w) inline
Definition at line 66 of file TFLNodes.h.
{ _w = w; }
References w().
Referenced by w().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h