ONE - On-device Neural Engine: onert::backend::gpu_cl::TensorManager Class Reference
onert::backend::gpu_cl::TensorManager Class Reference
#include <TensorManager.h>
Public Member Functions
TensorManager (MemoryManager *const_mgr, MemoryManager *nonconst_mgr)
virtual ~TensorManager ()=default
void allocateConsts (void)
void allocateNonconsts (void)
void deallocateConsts (void)
void deallocateNonconsts (void)
void buildTensor (const ir::OperandIndex &ind, const ir::OperandInfo &info, TensorType type)
ir::OperandIndex addTensor (const ir::Shape &shape)
std::shared_ptr< operand::ICLTensor > findTensorAsParent (const ir::OperandIndex &ind)
void startLifetime (const ir::OperandIndex &ind)
void finishLifetime (const ir::OperandIndex &ind)
std::shared_ptr< operand::ICLTensor > at (const ir::OperandIndex &ind)
ir::OperandIndexMap< std::shared_ptr< operand::CLTensor > > & constTensors (void)
ir::OperandIndexMap< std::shared_ptr< operand::CLTensor > > & nonconstTensors (void)
void iterate (const std::function< void(const ir::OperandIndex &)> &fn)
void tryDeallocConstants (void)
Detailed Description
Definition at line 37 of file TensorManager.h.
Constructor & Destructor Documentation
TensorManager()
onert::backend::gpu_cl::TensorManager::TensorManager (MemoryManager * const_mgr, MemoryManager * nonconst_mgr)
Definition at line 30 of file TensorManager.cc.
  : _const_mgr{const_mgr}, _nonconst_mgr{nonconst_mgr}
{
  // DO NOTHING
}
~TensorManager()
virtual onert::backend::gpu_cl::TensorManager::~TensorManager () virtual default
Member Function Documentation
addTensor()
ir::OperandIndex onert::backend::gpu_cl::TensorManager::addTensor (const ir::Shape & shape)
Definition at line 60 of file TensorManager.cc.
{
  auto ind = _nonconst_mgr->addTensor(shape);
  _ind_to_mgr.insert({ind, *_nonconst_mgr});
  return ind;
}
Referenced by onert::backend::gpu_cl::TensorRegistry::addNewClTensor().
allocateConsts()
void onert::backend::gpu_cl::TensorManager::allocateConsts (void)
Definition at line 36 of file TensorManager.cc.
{ _const_mgr->allocate(); }
allocateNonconsts()
void onert::backend::gpu_cl::TensorManager::allocateNonconsts (void)
Definition at line 38 of file TensorManager.cc.
{ _nonconst_mgr->allocate(); }
at()
std::shared_ptr< operand::ICLTensor > onert::backend::gpu_cl::TensorManager::at (const ir::OperandIndex & ind)
Definition at line 80 of file TensorManager.cc.
{
  if (_ind_to_mgr.find(ind) == _ind_to_mgr.end())
    return nullptr;
  auto &tensors = _ind_to_mgr.at(ind).tensors();
  if (tensors.find(ind) != tensors.end())
  {
    return tensors.at(ind);
  }
  return nullptr;
}
Referenced by onert::backend::gpu_cl::TensorRegistry::getClTensor(), and onert::backend::gpu_cl::TensorRegistry::getITensor().
buildTensor()
void onert::backend::gpu_cl::TensorManager::buildTensor (const ir::OperandIndex & ind, const ir::OperandInfo & info, TensorType type)
Definition at line 44 of file TensorManager.cc.
{
  assert(_ind_to_mgr.find(ind) == _ind_to_mgr.end());
  if (info.isConstant())
  {
    _const_mgr->buildTensor(ind, info, type);
    _ind_to_mgr.insert({ind, *_const_mgr});
  }
  else
  {
    _nonconst_mgr->buildTensor(ind, info, type);
    _ind_to_mgr.insert({ind, *_nonconst_mgr});
  }
}
References info.
constTensors()
ir::OperandIndexMap< std::shared_ptr< operand::CLTensor > > & onert::backend::gpu_cl::TensorManager::constTensors (void)
Definition at line 94 of file TensorManager.cc.
{
  return _const_mgr->tensors();
}
deallocateConsts()
void onert::backend::gpu_cl::TensorManager::deallocateConsts (void)
Definition at line 40 of file TensorManager.cc.
{ _const_mgr->deallocate(); }
deallocateNonconsts()
void onert::backend::gpu_cl::TensorManager::deallocateNonconsts (void)
Definition at line 42 of file TensorManager.cc.
{ _nonconst_mgr->deallocate(); }
findTensorAsParent()
std::shared_ptr< operand::ICLTensor > onert::backend::gpu_cl::TensorManager::findTensorAsParent (const ir::OperandIndex & ind)
finishLifetime()
void onert::backend::gpu_cl::TensorManager::finishLifetime (const ir::OperandIndex & ind)
Definition at line 74 of file TensorManager.cc.
{
  assert(_ind_to_mgr.find(ind) != _ind_to_mgr.end());
  _ind_to_mgr.at(ind).finishLifetime(ind);
}
iterate()
void onert::backend::gpu_cl::TensorManager::iterate (const std::function< void(const ir::OperandIndex &)> & fn)
Definition at line 104 of file TensorManager.cc.
{
  for (auto it : _nonconst_mgr->tensors())
    fn(it.first);
  for (auto it : _const_mgr->tensors())
    fn(it.first);
}
nonconstTensors()
ir::OperandIndexMap< std::shared_ptr< operand::CLTensor > > & onert::backend::gpu_cl::TensorManager::nonconstTensors (void)
Definition at line 99 of file TensorManager.cc.
{
  return _nonconst_mgr->tensors();
}
startLifetime()
void onert::backend::gpu_cl::TensorManager::startLifetime (const ir::OperandIndex & ind)
Definition at line 68 of file TensorManager.cc.
{
  assert(_ind_to_mgr.find(ind) != _ind_to_mgr.end());
  _ind_to_mgr.at(ind).startLifetime(ind);
}
tryDeallocConstants()
void onert::backend::gpu_cl::TensorManager::tryDeallocConstants (void)
Definition at line 113 of file TensorManager.cc.
{
  // NYI
}
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/TensorManager.h
runtime/onert/backend/gpu_cl/TensorManager.cc