ONE - On-device Neural Engine: luci_interpreter::kernels::Split Class Reference
luci_interpreter::kernels::Split Class Reference
#include <Split.h>
Public Member Functions
Split (const Tensor *axis, const Tensor *input, std::vector< Tensor * > outputs)
const Tensor * axis () const
const Tensor * input () const
Tensor * output (int index) const
void configure () override
void execute () const override
Split (const Tensor *axis, const Tensor *input, std::vector< Tensor * > outputs)
const Tensor * axis () const
const Tensor * input () const
Tensor * output (int index) const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Split.h.
Constructor & Destructor Documentation
Split() [1/2]
luci_interpreter::kernels::Split::Split (const Tensor * axis, const Tensor * input, std::vector< Tensor * > outputs)
Definition at line 28 of file Split.cpp.
  : Kernel({axis, input}, std::move(outputs))
{
}
References axis(), and input().
Split() [2/2]
luci_interpreter::kernels::Split::Split (const Tensor * axis, const Tensor * input, std::vector< Tensor * > outputs)
Member Function Documentation
axis() [1/2]
const Tensor * luci_interpreter::kernels::Split::axis () const inline
Definition at line 33 of file Split.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Split().
axis() [2/2]
const Tensor * luci_interpreter::kernels::Split::axis () const inline
Definition at line 33 of file Split.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::Split::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 33 of file Split.cpp.
{
  assert(axis()->shape().num_elements() == 1);
  _axis_value = getTensorData<int32_t>(axis())[0];
  if (_axis_value < 0)
    _axis_value += input()->shape().num_dims();
  assert(_axis_value >= 0 && _axis_value < input()->shape().num_dims());
  const int32_t input_size = input()->shape().dim(_axis_value);
  assert(input_size % _outputs.size() == 0);
  const int32_t slice_size = input_size / _outputs.size();
  Shape output_shape = input()->shape();
  output_shape.dim(_axis_value) = slice_size;
  for (Tensor *output : _outputs)
  {
    output->resize(output_shape);
  }
}
References luci_interpreter::Kernel::_outputs, axis(), luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Split::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Split::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 53 of file Split.cpp.
{
  tflite::SplitParams params{};
  params.num_split = _outputs.size();
  params.axis = _axis_value;
#define TF_LITE_SPLIT(scalar)                                                                    \
  {                                                                                              \
    VectorOfTensors<scalar, false> all_outputs(_outputs);                                        \
    luci_interpreter_pal::Split(params, getTensorShape(input()), getTensorData<scalar>(input()), \
                                all_outputs.shapes(), all_outputs.data());                       \
  }
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      TF_LITE_SPLIT(float);
      break;
    case DataType::U8:
      TF_LITE_SPLIT(uint8_t);
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
#undef TF_LITE_SPLIT
}
References luci_interpreter::Kernel::_outputs, input(), and TF_LITE_SPLIT.
execute() [2/2]
void luci_interpreter::kernels::Split::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Split::input () const inline
Definition at line 34 of file Split.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Split().
input() [2/2]
const Tensor * luci_interpreter::kernels::Split::input () const inline
Definition at line 34 of file Split.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Split::output (int index) const inline
Definition at line 35 of file Split.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Split::output (int index) const inline
Definition at line 35 of file Split.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Split.h
onert-micro/luci-interpreter/src/kernels/Split.h
compiler/luci-interpreter/src/kernels/Split.cpp
onert-micro/luci-interpreter/src/kernels/Split.cpp