ONE - On-device Neural Engine: coco::BagManager Class Reference
coco::BagManager Class Reference final
#include <BagManager.h>
Public Member Functions
BagManager (Module *m=nullptr)
Bag * create (uint32_t size)
void destroy (Bag *b)
Destroy (= deallocate) a Bag entity.
Public Member Functions inherited from coco::PtrManager< Bag >
uint32_t size (void) const
Return the number of managed objects.
Bag * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Bag >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Bag > release (Bag *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 28 of file BagManager.h.
Constructor & Destructor Documentation
BagManager()
coco::BagManager::BagManager (Module * m = nullptr) inline
Definition at line 31 of file BagManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
Member Function Documentation
create()
Bag * coco::BagManager::create (uint32_t size)
Definition at line 24 of file BagManager.cpp.
{
  auto bag = std::make_unique<Bag>(size);
  modulize(bag.get());
  return take(std::move(bag));
}
References coco::EntityBuilder::modulize(), coco::PtrManager< Bag >::size(), and coco::PtrManager< Bag >::take().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
destroy()
void coco::BagManager::destroy (Bag * b)
Destroy (= deallocate) a Bag entity.
NOTE A Bag SHOULD BE detached from IR before destruction
Definition at line 31 of file BagManager.cpp.
{ release(b); }
References coco::PtrManager< Bag >::release().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/BagManager.h
compiler/coco/core/src/IR/BagManager.cpp