ONE - On-device Neural Engine: ModelBuilder Class Reference
ModelBuilder Class Reference
#include <ModelBuilder.h>
Public Member Functions
virtual ~ModelBuilder ()=default
int addOperand (const ANeuralNetworksOperandType &type)
int setOperandValue (uint32_t index, const void *buffer, size_t length)
int setOperandValueFromMemory (uint32_t index, const Memory *memory, uint32_t offset, size_t length)
int addOperation (OperationType type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs)
int identifyInputsAndOutputs (uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs)
int finish ()
bool isFinished () const
int createCompilation (CompilationBuilder **compilation)
void publish (Model *model) const
uint32_t operandCount () const
uint32_t operationCount () const
uint32_t inputCount () const
uint32_t getInputOperandIndex (uint32_t i) const
const Operand & getInputOperand (uint32_t i) const
uint32_t outputCount () const
uint32_t getOutputOperandIndex (uint32_t i) const
const Operand & getOutputOperand (uint32_t i) const
const Operand & getOperand (uint32_t index) const
const Operation & getOperation (uint32_t index) const
const MemoryTracker & getMemories () const
const std::vector< Operation > & getOperations () const
Detailed Description
Definition at line 33 of file ModelBuilder.h.
Constructor & Destructor Documentation
~ModelBuilder()
virtual ModelBuilder::~ModelBuilder () virtual default
Member Function Documentation
addOperand()
int ModelBuilder::addOperand (const ANeuralNetworksOperandType & type)
Definition at line 83 of file ModelBuilder.cpp.
{
  if (badState("addOperand"))
  {
    return ANEURALNETWORKS_BAD_STATE;
  }
  int n = validateOperandType(type, "ANeuralNetworksModel_addOperand", true);
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  size_t idx = mOperands.size();
  if (idx >= MAX_NUMBER_OF_OPERANDS)
  {
    LOG(ERROR) << "ANeuralNetworksModel_addOperand exceed max operands";
    return ANEURALNETWORKS_BAD_DATA;
  }
  mOperands.resize(idx + 1);
  auto &operand = mOperands[idx];
  operand.type = static_cast<OperandType>(type.type);
  setFromIntList(&operand.dimensions, type.dimensionCount, type.dimensions);
  operand.numberOfConsumers = 0;
  operand.scale = type.scale;
  operand.zeroPoint = type.zeroPoint;
  operand.lifetime = OperandLifeTime::TEMPORARY_VARIABLE;
  operand.location = {.poolIndex = 0, .offset = 0, .length = 0};
  return ANEURALNETWORKS_NO_ERROR;
}
References ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, LOG, MAX_NUMBER_OF_OPERANDS, and validateOperandType().
addOperation()
int ModelBuilder::addOperation (OperationType type, uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs)
Definition at line 214 of file ModelBuilder.cpp.
{
  if (badState("addOperation"))
  {
    return ANEURALNETWORKS_BAD_STATE;
  }
  if (!validateOperationType(type))
  {
    LOG(ERROR) << "ANeuralNetworksModel_addOperation invalid operations type "
               << static_cast<uint32_t>(type);
    return ANEURALNETWORKS_BAD_DATA;
  }
  int n = validateOperandList(inputCount, inputs, operandCount(),
                              "ANeuralNetworksModel_addOperation inputs");
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  n = validateOperandList(outputCount, outputs, operandCount(),
                          "ANeuralNetworksModel_addOperation outputs");
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  uint32_t operationIndex = operationCount();
  if (operationIndex >= MAX_NUMBER_OF_OPERATIONS)
  {
    LOG(ERROR) << "ANeuralNetworksModel_addOperation exceed max operations";
    return ANEURALNETWORKS_BAD_DATA;
  }
  mOperations.resize(operationIndex + 1);
  auto &entry = mOperations[operationIndex];
  entry.type = type;
  setFromIntList(&entry.inputs, inputCount, inputs);
  setFromIntList(&entry.outputs, outputCount, outputs);
  for (uint32_t i : entry.inputs)
  {
    mOperands[i].numberOfConsumers++;
    // TODO mOperands[i].consumers.push_back(operationIndex);
  }
  return ANEURALNETWORKS_NO_ERROR;
}
References ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, entry(), inputCount(), LOG, MAX_NUMBER_OF_OPERATIONS, operandCount(), operationCount(), outputCount(), validateOperandList(), and validateOperationType().
createCompilation()
int ModelBuilder::createCompilation (CompilationBuilder ** compilation)
Definition at line 322 of file ModelBuilder.cpp.
{
  if (!mCompletedModel || mInvalidModel)
  {
    LOG(ERROR) << "ANeuralNetworksCompilation_create passed an unfinished model";
    *compilation = nullptr;
    return ANEURALNETWORKS_BAD_STATE;
  }
  *compilation = new CompilationBuilder(this);
  return (*compilation ? ANEURALNETWORKS_NO_ERROR : ANEURALNETWORKS_OUT_OF_MEMORY);
}
References ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, ANEURALNETWORKS_OUT_OF_MEMORY, and LOG.
finish()
int ModelBuilder::finish ()
Definition at line 334 of file ModelBuilder.cpp.
{
  if (mCompletedModel)
  {
    LOG(ERROR) << "ANeuralNetworksModel_finish called more than once";
    return ANEURALNETWORKS_BAD_STATE;
  }
  if (mInvalidModel)
  {
    LOG(ERROR) << "ANeuralNetworksModel_finish called on an invalid model";
    return ANEURALNETWORKS_BAD_STATE;
  }
  int n = copyLargeValuesToMemory();
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  Model modelForValidation;
  publish(&modelForValidation);
  if (!validateModel(modelForValidation))
  {
    LOG(ERROR) << "ANeuralNetworksModel_finish called on invalid model";
    mInvalidModel = true;
    return ANEURALNETWORKS_BAD_DATA;
  }
  // We sort the operations so that they will be in the appropriate
  // order for a single-threaded, op at a time execution.
  // TODO: we don't need this if we always run the partitioner.
  sortIntoRunOrder();
  mCompletedModel = true;
  return ANEURALNETWORKS_NO_ERROR;
}
References ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, LOG, publish(), and validateModel().
getInputOperand()
const Operand & ModelBuilder::getInputOperand (uint32_t i) const inline
Definition at line 80 of file ModelBuilder.h.
{ return mOperands[getInputOperandIndex(i)]; }
References getInputOperandIndex().
Referenced by ExecutionBuilder::setInput(), and ExecutionBuilder::setInputFromMemory().
getInputOperandIndex()
uint32_t ModelBuilder::getInputOperandIndex (uint32_t i) const inline
Definition at line 79 of file ModelBuilder.h.
{ return mInputIndexes[i]; }
Referenced by getInputOperand().
getMemories()
const MemoryTracker & ModelBuilder::getMemories () const inline
Definition at line 92 of file ModelBuilder.h.
{ return mMemories; }
getOperand()
const Operand & ModelBuilder::getOperand (uint32_t index) const inline
Definition at line 88 of file ModelBuilder.h.
{ return mOperands[index]; }
getOperation()
const Operation & ModelBuilder::getOperation (uint32_t index) const inline
Definition at line 89 of file ModelBuilder.h.
{ return mOperations[index]; }
getOperations()
const std::vector< Operation > & ModelBuilder::getOperations () const inline
Definition at line 93 of file ModelBuilder.h.
{ return mOperations; }
getOutputOperand()
const Operand & ModelBuilder::getOutputOperand (uint32_t i) const inline
Definition at line 85 of file ModelBuilder.h.
{ return mOperands[getOutputOperandIndex(i)]; }
References getOutputOperandIndex().
Referenced by ExecutionBuilder::setOutput(), and ExecutionBuilder::setOutputFromMemory().
getOutputOperandIndex()
uint32_t ModelBuilder::getOutputOperandIndex (uint32_t i) const inline
Definition at line 84 of file ModelBuilder.h.
{ return mOutputIndexes[i]; }
Referenced by getOutputOperand().
identifyInputsAndOutputs()
int ModelBuilder::identifyInputsAndOutputs (uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs)
Definition at line 262 of file ModelBuilder.cpp.
{
  if (badState("identifyInputsAndOutputs"))
  {
    return ANEURALNETWORKS_BAD_STATE;
  }
  int n = validateOperandList(inputCount, inputs, operandCount(),
                              "ANeuralNetworksModel_identifyInputsAndOutputs inputs");
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  n = validateOperandList(outputCount, outputs, operandCount(),
                          "ANeuralNetworksModel_identifyInputsAndOutputs outputs");
  if (n != ANEURALNETWORKS_NO_ERROR)
  {
    return n;
  }
  // Makes a copy of the index list, validates the arguments, and changes
  // the lifetime info of the corresponding operand.
  auto setArguments = [&](std::vector<uint32_t> *indexVector, uint32_t indexCount,
                          const uint32_t *indexList, OperandLifeTime lifetime) -> bool {
    indexVector->resize(indexCount);
    for (uint32_t i = 0; i < indexCount; i++)
    {
      const uint32_t operandIndex = indexList[i];
      if (operandIndex >= mOperands.size())
      {
        LOG(ERROR) << "ANeuralNetworksModel_identifyInputsAndOutputs Can't set input or output "
                      "to be "
                   << operandIndex << " as this exceeds the numbe of operands " << mOperands.size();
        return false;
      }
      (*indexVector)[i] = operandIndex;
      Operand &operand = mOperands[operandIndex];
      if (operand.lifetime != OperandLifeTime::TEMPORARY_VARIABLE)
      {
        LOG(ERROR) << "ANeuralNetworksModel_identifyInputsAndOutputs Can't set operand "
                   << operandIndex
                   << " to be an input or output.  Check that it's not a constant or "
                      "already an input or output";
        return false;
      }
      operand.lifetime = lifetime;
    }
    return true;
  };
  if (!setArguments(&mInputIndexes, inputCount, inputs, OperandLifeTime::MODEL_INPUT) ||
      !setArguments(&mOutputIndexes, outputCount, outputs, OperandLifeTime::MODEL_OUTPUT))
  {
    return ANEURALNETWORKS_BAD_DATA;
  }
  return ANEURALNETWORKS_NO_ERROR;
}
References ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, inputCount(), Operand::lifetime, LOG, operandCount(), outputCount(), and validateOperandList().
inputCount()
uint32_t ModelBuilder::inputCount () const inline
Definition at line 78 of file ModelBuilder.h.
{ return static_cast<uint32_t>(mInputIndexes.size()); }
Referenced by addOperation(), and identifyInputsAndOutputs().
isFinished()
bool ModelBuilder::isFinished () const inline
Definition at line 57 of file ModelBuilder.h.
{ return mCompletedModel; }
operandCount()
uint32_t ModelBuilder::operandCount () const inline
Definition at line 66 of file ModelBuilder.h.
  {
    // We don't allow more than uint32_t worth of operands
    return static_cast<uint32_t>(mOperands.size());
  }
Referenced by addOperation(), identifyInputsAndOutputs(), setOperandValue(), and setOperandValueFromMemory().
operationCount()
uint32_t ModelBuilder::operationCount () const inline
Definition at line 71 of file ModelBuilder.h.
  {
    // We don't allow more than uint32_t worth of operations
    return static_cast<uint32_t>(mOperations.size());
  }
Referenced by addOperation().
outputCount()
uint32_t ModelBuilder::outputCount () const inline
Definition at line 83 of file ModelBuilder.h.
{ return static_cast<uint32_t>(mOutputIndexes.size()); }
Referenced by addOperation(), and identifyInputsAndOutputs().
publish()
void ModelBuilder::publish (Model * model) const
Definition at line 425 of file ModelBuilder.cpp.
{
  model->operands = mOperands;
  model->operations = mOperations;
  model->inputIndexes = mInputIndexes;
  model->outputIndexes = mOutputIndexes;
  model->operandValues = mSmallOperandValues;
  uint32_t count = mMemories.size();
  model->pools.resize(count);
  for (uint32_t i = 0; i < count; i++)
  {
    uint8_t *buffer;
    mMemories[i]->getPointer(&buffer);
    model->pools[i] = buffer;
  }
}
References MemoryTracker::size().
Referenced by finish(), and ExecutionBuilder::startCompute().
setOperandValue()
int ModelBuilder::setOperandValue (uint32_t index, const void * buffer, size_t length)
Definition at line 113 of file ModelBuilder.cpp.
{
  if (badState("setOperandValue"))
  {
    return ANEURALNETWORKS_BAD_STATE;
  }
  VLOG(MODEL) << __func__ << " for operand " << index << " size " << length;
  if (index >= operandCount())
  {
    LOG(ERROR) << "ANeuralNetworksModel_setOperandValue setting operand " << index << " of "
               << operandCount();
    return ANEURALNETWORKS_BAD_DATA;
  }
  Operand &operand = mOperands[index];
  if (buffer == nullptr)
  {
    if (length)
    {
      LOG(ERROR) << "ANeuralNetworksModel_setOperandValue buffer is nullptr but length is "
                    "not 0";
      return ANEURALNETWORKS_BAD_DATA;
    }
    operand.lifetime = OperandLifeTime::NO_VALUE;
    // The location is unused and is set to zeros.
    operand.location = {.poolIndex = 0, .offset = 0, .length = 0};
  }
  else
  {
    if (length > 0xFFFFFFFF)
    {
      LOG(ERROR) << "ANeuralNetworksModel_setOperandValue value length of " << length
                 << " exceeds max size";
      return ANEURALNETWORKS_BAD_DATA;
    }
    uint32_t valueLength = static_cast<uint32_t>(length);
    uint32_t neededLength = sizeOfData(operand.type, operand.dimensions);
    if (neededLength != valueLength)
    {
      LOG(ERROR) << "ANeuralNetworksModel_setOperandValue setting " << valueLength
                 << " bytes when needing " << neededLength;
      return ANEURALNETWORKS_BAD_DATA;
    }
    if (valueLength <= ANEURALNETWORKS_MAX_SIZE_OF_IMMEDIATELY_COPIED_VALUES)
    {
      uint32_t existingSize = static_cast<uint32_t>(mSmallOperandValues.size());
      uint32_t extraBytes = alignBytesNeeded(existingSize, valueLength);
      mSmallOperandValues.resize(existingSize + extraBytes + valueLength);
      operand.lifetime = OperandLifeTime::CONSTANT_COPY;
      operand.location = {
          .poolIndex = 0, .offset = existingSize + extraBytes, .length = neededLength};
      memcpy(&mSmallOperandValues[operand.location.offset], buffer, valueLength);
      VLOG(MODEL) << "Copied small value to offset " << operand.location.offset;
    }
    else
    {
      VLOG(MODEL) << "Saving large value";
      operand.lifetime = OperandLifeTime::CONSTANT_REFERENCE;
      // The values for poolIndex and offset will be set when the model is finished.
      operand.location = {.poolIndex = 0, .offset = 0, .length = valueLength};
      // We keep track of the buffers. We'll allocate the shared memory only
      // once we know the total size, to avoid needless copies.
      mLargeOperandValues.push_back(LargeValue{.operandIndex = index, .buffer = buffer});
    }
  }
  return ANEURALNETWORKS_NO_ERROR;
}
References alignBytesNeeded(), ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_MAX_SIZE_OF_IMMEDIATELY_COPIED_VALUES, ANEURALNETWORKS_NO_ERROR, Operand::dimensions, Operand::lifetime, Operand::location, LOG, DataLocation::offset, operandCount(), DataLocation::poolIndex, sizeOfData(), Operand::type, and VLOG.
setOperandValueFromMemory()
int ModelBuilder::setOperandValueFromMemory (uint32_t index, const Memory * memory, uint32_t offset, size_t length)
Definition at line 181 of file ModelBuilder.cpp.
{
  VLOG(MODEL) << __func__ << " for operand " << index << " offset " << offset << " size " << length;
  if (badState("setOperandValueFromMemory"))
  {
    return ANEURALNETWORKS_BAD_STATE;
  }
  if (index >= operandCount())
  {
    LOG(ERROR) << "ANeuralNetworksModel_setOperandValueFromMemory setting operand " << index
               << " of " << operandCount();
    return ANEURALNETWORKS_BAD_DATA;
  }
  Operand &operand = mOperands[index];
  uint32_t neededLength = sizeOfData(operand.type, operand.dimensions);
  if (neededLength != length)
  {
    LOG(ERROR) << "ANeuralNetworksModel_setOperandValueFromMemory setting " << length
               << " bytes when needing " << neededLength;
    return ANEURALNETWORKS_BAD_DATA;
  }
  if (!memory->validateSize(offset, length))
  {
    return ANEURALNETWORKS_BAD_DATA;
  }
  // TODO validate does not exceed length of memory
  operand.lifetime = OperandLifeTime::CONSTANT_REFERENCE;
  operand.location = {.poolIndex = mMemories.add(memory), .offset = offset, .length = neededLength};
  return ANEURALNETWORKS_NO_ERROR;
}
References MemoryTracker::add(), ANEURALNETWORKS_BAD_DATA, ANEURALNETWORKS_BAD_STATE, ANEURALNETWORKS_NO_ERROR, Operand::dimensions, Operand::lifetime, Operand::location, LOG, offset(), operandCount(), DataLocation::poolIndex, sizeOfData(), Operand::type, Memory::validateSize(), and VLOG.
The documentation for this class was generated from the following files:
compiler/ann-ref/src/ModelBuilder.h
compiler/ann-ref/src/ModelBuilder.cpp