ONE - On-device Neural Engine: mir::GraphPatternMatcher Class Reference
mir::GraphPatternMatcher Class Reference
#include <GraphPatternMatcher.h>
Public Types
using Predicate = bool(const Operation *)
Public Member Functions
GraphPatternMatcher (Graph *g)
std::vector< std::pair< Operation *, Operation * > > matchEdge (Predicate p1, Predicate p2)
Match an edge with 2 predicates for ends of the edge.
std::vector< std::pair< std::vector< Operation * >, Operation * > > matchUpBush (Predicate p1, Predicate p2)
Match a two level tree where the bottommost node has multiple previous nodes.
Detailed Description
Definition at line 27 of file GraphPatternMatcher.h.
Member Typedef Documentation
Predicate
using mir::GraphPatternMatcher::Predicate = bool(const Operation *)
Definition at line 30 of file GraphPatternMatcher.h.
Constructor & Destructor Documentation
GraphPatternMatcher()
mir::GraphPatternMatcher::GraphPatternMatcher (Graph * g) inline explicit
Definition at line 31 of file GraphPatternMatcher.h.
: _g(g){};
Member Function Documentation
matchEdge()
std::vector< std::pair< Operation *, Operation * > > mir::GraphPatternMatcher::matchEdge (GraphPatternMatcher::Predicate p1, GraphPatternMatcher::Predicate p2)
Match an edge with 2 predicates for ends of the edge.
Parameters
pattern
Returns
Vector of topmost ops of all matches; empty if no mathces are found
Definition at line 26 of file GraphPatternMatcher.cpp.
{
  std::vector<std::pair<Operation *, Operation *>> matches;
  for (auto *start : _g->getNodes())
  {
    if (p1(start))
    {
      for (auto &out : start->getOutputs())
      {
        for (auto use : out.getUses())
        {
          Operation *end = use.getNode();
          if (p2(end))
          {
            matches.emplace_back(std::make_pair(start, end));
            break;
          }
        }
      }
    }
  }
  return matches;
}
References mir::Graph::getNodes().
Referenced by nnc::CombineTransposes::run(), nnc::ConstantFoldTranspose::run(), nnc::SinkRelu::run(), and nnc::SinkTranspose::run().
matchUpBush()
std::vector< std::pair< std::vector< Operation * >, Operation * > > mir::GraphPatternMatcher::matchUpBush (Predicate p1, Predicate p2)
Match a two level tree where the bottommost node has multiple previous nodes.
Parameters
p1 Predicate for top node
p2 Predicate for bottom node
Returns
Vector of pairs : all matches; empty if no matches are found
Definition at line 52 of file GraphPatternMatcher.cpp.
{
  std::vector<std::pair<std::vector<Operation *>, Operation *>> matches;
  for (auto *root : _g->getNodes())
  {
    if (p2(root))
    {
      const auto &inputs = root->getInputs();
      if (std::all_of(inputs.begin(), inputs.end(),
                      [p1](const Operation::Output *input) { return p1(input->getNode()); }))
      {
        std::vector<Operation *> tops;
        tops.reserve(inputs.size());
        for (Operation::Output *pr : inputs)
        {
          tops.emplace_back(pr->getNode());
        }
        matches.emplace_back(std::make_pair(tops, root));
      }
    }
  }
  return matches;
}
References mir::Graph::getNodes().
Referenced by nnc::SinkRelu::run(), and nnc::SinkTranspose::run().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/GraphPatternMatcher.h
compiler/mir/src/GraphPatternMatcher.cpp