ONE - On-device Neural Engine: loco::PermutingEncoder< Domain::Matrix > Class Reference
loco::PermutingEncoder< Domain::Matrix > Class Reference final
Permutation-based Tensor-to-Matrix converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingEncoder ()=default
PermutingEncoder (const Permutation< Domain::Matrix > &perm)
bool valid (void) const
MatrixShape shape (const TensorShape &tensor_shape) const override
TensorIndex value (const MatrixIndex &index) const override
const Permutation< Domain::Matrix > * perm (void) const
Permutation< Domain::Matrix > * perm (void)
void perm (const Permutation< Domain::Matrix > &p)
Public Member Functions inherited from loco::MatrixEncoder
virtual ~MatrixEncoder ()=default
virtual MatrixShape shape (const TensorShape &shape) const =0
virtual TensorIndex value (const MatrixIndex &index) const =0
Detailed Description
Permutation-based Tensor-to-Matrix converter.
Definition at line 362 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingEncoder() [1/2]
loco::PermutingEncoder< Domain::Matrix >::PermutingEncoder () default
PermutingEncoder() [2/2]
loco::PermutingEncoder< Domain::Matrix >::PermutingEncoder (const Permutation< Domain::Matrix > & perm) inline
Definition at line 368 of file PermutingCodec.h.
                                                          : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingEncoder< Domain::Matrix >::perm (const Permutation< Domain::Matrix > & p) inline
Definition at line 383 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Matrix > * loco::PermutingEncoder< Domain::Matrix >::perm (void) inline
Definition at line 382 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Matrix > * loco::PermutingEncoder< Domain::Matrix >::perm (void) const inline
Definition at line 381 of file PermutingCodec.h.
{ return &_perm; }
shape()
MatrixShape loco::PermutingEncoder< Domain::Matrix >::shape (const TensorShape & tensor_shape) const override virtual
Implements loco::MatrixEncoder.
Definition at line 570 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  MatrixShape out;
  out.height() = in.dim(_perm[MatrixAxis::Height]);
  out.width() = in.dim(_perm[MatrixAxis::Width]);
  return out;
}
References loco::TensorShape::dim(), loco::Height, loco::MatrixShape::height(), loco::valid(), loco::Width, and loco::MatrixShape::width().
valid()
bool loco::PermutingEncoder< Domain::Matrix >::valid (void) const
Definition at line 596 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
TensorIndex loco::PermutingEncoder< Domain::Matrix >::value (const MatrixIndex & index) const override virtual
Implements loco::MatrixEncoder.
Definition at line 582 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorIndex out;
  out.resize(2);
  out.at(_perm[MatrixAxis::Height]) = in.row();
  out.at(_perm[MatrixAxis::Width]) = in.column();
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::MatrixIndex::column(), loco::Height, nncc::core::ADT::tensor::Index::resize(), loco::MatrixIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp