ONE - On-device Neural Engine: loco::TensorIndex Class Reference
loco::TensorIndex Class Reference
#include <TensorIndex.h>
Public Member Functions
TensorIndex ()
uint32_t rank (void) const
TensorIndex & resize (uint32_t size)
uint32_t & at (uint32_t axis)
uint32_t at (uint32_t axis) const
Detailed Description
Definition at line 27 of file TensorIndex.h.
Constructor & Destructor Documentation
TensorIndex()
loco::TensorIndex::TensorIndex () default
Member Function Documentation
at() [1/2]
uint32_t & loco::TensorIndex::at (uint32_t axis)
Definition at line 32 of file TensorIndex.cpp.
{ return _indices.at(axis); }
Referenced by locomotiv::as_loco_index(), loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), loco::PermutingEncoder< Domain::Feature >::value(), loco::PermutingEncoder< Domain::Filter >::value(), loco::PermutingEncoder< Domain::Matrix >::value(), loco::PermutingDecoder< Domain::Feature >::value(), loco::PermutingDecoder< Domain::Filter >::value(), loco::PermutingDecoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::Matrix >::value().
at() [2/2]
uint32_t loco::TensorIndex::at (uint32_t axis) const
Definition at line 34 of file TensorIndex.cpp.
{ return _indices.at(axis); }
rank()
uint32_t loco::TensorIndex::rank (void) const
Definition at line 24 of file TensorIndex.cpp.
{ return _indices.size(); }
Referenced by loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
resize()
TensorIndex & loco::TensorIndex::resize (uint32_t size)
Definition at line 26 of file TensorIndex.cpp.
{
  _indices.resize(size);
  return *this;
}
References size.
Referenced by locomotiv::as_loco_index(), loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), loco::PermutingEncoder< Domain::Feature >::value(), loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingEncoder< Domain::Matrix >::value().
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/TensorIndex.h
compiler/loco/src/IR/TensorIndex.cpp