ONE - On-device Neural Engine: nncc::core::ADT::tensor::IndexEnumerator Class Reference
nncc::core::ADT::tensor::IndexEnumerator Class Reference
#include <IndexEnumerator.h>
Public Member Functions
IndexEnumerator (const Shape &shape)
IndexEnumerator (IndexEnumerator &&)=delete
IndexEnumerator (const IndexEnumerator &)=delete
bool valid (void) const
const Index & current (void) const
void advance (void)
Detailed Description
Definition at line 32 of file IndexEnumerator.h.
Constructor & Destructor Documentation
IndexEnumerator() [1/3]
nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator (const Shape & shape) explicit
Definition at line 39 of file IndexEnumerator.cpp.
                                                   : _shape{shape}, _cursor(0)
{
  const uint32_t rank = _shape.rank();
  // Initialize _index
  _index.resize(rank);
  for (uint32_t axis = 0; axis < rank; ++axis)
  {
    _index.at(axis) = 0;
  }
  // Initialize _cursor
  for (_cursor = 0; _cursor < rank; ++_cursor)
  {
    const auto axis = axis_of(_shape, _cursor);
    if (_index.at(axis) < _shape.dim(axis))
    {
      break;
    }
  }
}
References nncc::core::ADT::tensor::Index::at(), axis_of(), nncc::core::ADT::tensor::Shape::dim(), nncc::core::ADT::tensor::Shape::rank(), and nncc::core::ADT::tensor::Index::resize().
IndexEnumerator() [2/3]
nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator (IndexEnumerator &&) delete
IndexEnumerator() [3/3]
nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator (const IndexEnumerator &) delete
Member Function Documentation
advance()
void nncc::core::ADT::tensor::IndexEnumerator::advance (void)
Definition at line 62 of file IndexEnumerator.cpp.
{
  const uint32_t rank = _shape.rank();
  // Find axis to be updated
  while (_cursor < rank)
  {
    const auto axis = axis_of(_shape, _cursor);
    if ((_index.at(axis)) + 1 < _shape.dim(axis))
    {
      break;
    }
    ++_cursor;
  }
  if (_cursor == rank)
  {
    return;
  }
  // Update index
  _index.at(axis_of(_shape, _cursor)) += 1;
  for (uint32_t pos = 0; pos < _cursor; ++pos)
  {
    const auto axis = axis_of(_shape, pos);
    _index.at(axis) = 0;
  }
  // Reset cursor
  _cursor = 0;
}
References nncc::core::ADT::tensor::Index::at(), axis_of(), nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::rank().
current()
const Index & nncc::core::ADT::tensor::IndexEnumerator::current (void) const inline
Definition at line 45 of file IndexEnumerator.h.
{ return _index; }
valid()
bool nncc::core::ADT::tensor::IndexEnumerator::valid (void) const inline
Definition at line 42 of file IndexEnumerator.h.
{ return _cursor < _shape.rank(); }
References nncc::core::ADT::tensor::Shape::rank().
Referenced by enco::lower_concat(), and ShowAction::run().
The documentation for this class was generated from the following files:
compiler/angkor/include/nncc/core/ADT/tensor/IndexEnumerator.h
compiler/angkor/src/ADT/tensor/IndexEnumerator.cpp