ONE - On-device Neural Engine: onert::compiler::pass::ConstantOutputPass Class Reference
onert::compiler::pass::ConstantOutputPass Class Reference
Pass to specially handle constant model outputs.
#include <ConstantOutputPass.h>
Public Member Functions
std::string id () final
void callback (const ir::OperandIndex &i, ir::Operand &o) final
Public Member Functions inherited from onert::compiler::pass::OperandPass
virtual ~OperandPass ()=default
std::string id () override=0
void run () override final
virtual void callback (const ir::OperandIndex &i, ir::Operand &o)=0
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Pass to specially handle constant model outputs.
As an output buffer is given right before an execution but constant initialization is done at prepare phase, the current runtime structure cannot handle when an output is constant. To resolve this problem, this pass inserts a Permute layer with a const input and make the model output tensor to be its output.
e.g.)
((Const Output))
becomes
(Const) -> [Permute] -> ((Output))
Note that this is a mandatory pass for Graph.
Definition at line 47 of file ConstantOutputPass.h.
Member Function Documentation
callback()
void onert::compiler::pass::ConstantOutputPass::callback (const ir::OperandIndex & i, ir::Operand & o) final virtual
Implements onert::compiler::pass::OperandPass.
Definition at line 30 of file ConstantOutputPass.cc.
{
  if (!_graph.getOutputs().contains(ind) || !obj.isConstant())
    return;
  auto permute_input_ind = _graph.addOperand(obj.shape(), obj.typeInfo());
  auto &permute_input_obj = _graph.operands().at(permute_input_ind);
  // Move the const data
  permute_input_obj.data(obj.shareData());
  obj.releaseData();
  obj.info().setAsNonConst();
  using ir::operation::Permute;
  auto permute_obj = std::make_unique<Permute>(permute_input_ind, ind, Permute::Type::COPY);
  auto permute_ind = _graph.operations().push(std::move(permute_obj));
  permute_input_obj.insertUse(permute_ind);
  obj.setDef(permute_ind);
  // Make the operations that uses this operand to use the generated operand
  auto orig_uses = obj.getUses();
  for (auto use : orig_uses)
  {
    permute_input_obj.insertUse(use);
    obj.removeUse(use);
    _graph.operations().at(use).replaceInputs(ind, permute_input_ind);
  }
  VERBOSE(ConstantOutputPass) << "Permute Op inserted for a constant ouput, node index : "
                              << permute_ind << std::endl;
  VERBOSE(ConstantOutputPass) << "  - Input (inserted) Operand : " << permute_input_ind
                              << std::endl;
  VERBOSE(ConstantOutputPass) << "  - Output(original) Operand : " << ind << std::endl;
}
References onert::compiler::pass::Pass::_graph, onert::ir::Graph::addOperand(), onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::contains(), onert::ir::Graph::getOutputs(), onert::ir::Graph::operands(), onert::ir::Graph::operations(), onert::util::ObjectManager< Index, Object >::push(), and VERBOSE.
id()
std::string onert::compiler::pass::ConstantOutputPass::id () inline final virtual
Implements onert::compiler::pass::OperandPass.
Definition at line 53 of file ConstantOutputPass.h.
{ return "ConstantOutputPass"; }
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/ConstantOutputPass.h
runtime/onert/core/src/compiler/pass/ConstantOutputPass.cc