ONE - On-device Neural Engine: onert::backend::cpu::ops::ReduceLayer Class Reference
onert::backend::cpu::ops::ReduceLayer Class Reference
#include <ReduceLayer.h>
Public Member Functions
ReduceLayer ()
~ReduceLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *axes, IPortableTensor *output, ReduceType reduceType, bool keep_dims)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 55 of file ReduceLayer.h.
Constructor & Destructor Documentation
ReduceLayer()
onert::backend::cpu::ops::ReduceLayer::ReduceLayer ()
Definition at line 160 of file ReduceLayer.cc.
  : _input(nullptr), _axes(nullptr), _output(nullptr), _reduce_kernel(new nnfw::cker::Reduce()),
    _kernel(), _reduceType(ReduceType::kInvalid)
{
  // DO NOTHING
}
~ReduceLayer()
onert::backend::cpu::ops::ReduceLayer::~ReduceLayer () default
Member Function Documentation
configure()
void onert::backend::cpu::ops::ReduceLayer::configure (const IPortableTensor * input, const IPortableTensor * axes, IPortableTensor * output, ReduceType reduceType, bool keep_dims)
Definition at line 169 of file ReduceLayer.cc.
{
  _input = input;
  _axes = axes;
  _output = output;
  _reduceType = reduceType;
  switch (_reduceType)
  {
    case ReduceType::kSum:
      if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
      {
        _kernel = std::bind(&evalSumQuantized, std::placeholders::_1, std::placeholders::_2,
                            std::placeholders::_3, keep_dims, *_reduce_kernel);
        return;
      }
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kSum);
      break;
    case ReduceType::kProd:
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kProd);
      break;
    case ReduceType::kMax:
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kMax);
      break;
    case ReduceType::kMin:
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kMin);
      break;
    case ReduceType::kAny:
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kAny);
      break;
    case ReduceType::kAll:
      _kernel = generateKernelGeneric(_input, keep_dims, *_reduce_kernel, ReduceType::kAll);
      break;
    default:
      throw std::runtime_error{"Reduce: Unsupported reduce type"};
  }
}
References onert::backend::ITensor::data_type(), onert::backend::cpu::ops::kAll, onert::backend::cpu::ops::kAny, onert::backend::cpu::ops::kMax, onert::backend::cpu::ops::kMin, onert::backend::cpu::ops::kProd, and onert::backend::cpu::ops::kSum.
run()
void onert::backend::cpu::ops::ReduceLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 208 of file ReduceLayer.cc.
{
  const auto axes = getReducerAxes(_axes);
#ifdef USE_NEON
  int32_t rank = _input->getShape().rank();
  if (_input->data_type() == ir::DataType::FLOAT32 && _reduceType == ReduceType::kSum &&
      axes.size() == 1 && (axes[0] == -1 || axes[0] == rank - 1))
  {
    OptimizedReduceSum(getBuffer<float>(_input), getShape(_input), getBuffer<float>(_output));
    return;
  }
#endif // NEON
  _kernel(_input, _output, axes);
}
References onert::backend::ITensor::data_type(), onert::backend::cpu::ops::getReducerAxes(), onert::backend::ITensor::getShape(), onert::backend::cpu::ops::getShape(), and onert::backend::cpu::ops::kSum.
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ReduceLayer.h
runtime/onert/backend/cpu/ops/ReduceLayer.cc