ONE - On-device Neural Engine: loco::FilterIndex Class Reference
loco::FilterIndex Class Reference final
Filter Index.
#include <FilterIndex.h>
Public Member Functions
FilterIndex ()=default
const uint32_t & nth (void) const
uint32_t & nth (void)
const uint32_t & channel (void) const
uint32_t & channel (void)
const uint32_t & row (void) const
uint32_t & row (void)
const uint32_t & column (void) const
uint32_t & column (void)
Detailed Description
Filter Index.
Filter Index indicates an "element" in a given (convolutional) filter.
Let us assume that there is a filter K where KS denotes its shape (of FilterShape type).
Then, any valid filter index I satisfies the following invariants:
0 <= I.nth() < KS.count()
0 <= I.channel() < KS.depth()
0 <= I.row() < KS.height()
0 <= I.column() < KS.width()
Definition at line 38 of file FilterIndex.h.
Constructor & Destructor Documentation
FilterIndex()
loco::FilterIndex::FilterIndex () default
Member Function Documentation
channel() [1/2]
uint32_t & loco::FilterIndex::channel (void) inline
Definition at line 48 of file FilterIndex.h.
{ return _channel; }
channel() [2/2]
const uint32_t & loco::FilterIndex::channel (void) const inline
Definition at line 47 of file FilterIndex.h.
{ return _channel; }
Referenced by loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingDecoder< Domain::Filter >::value().
column() [1/2]
uint32_t & loco::FilterIndex::column (void) inline
Definition at line 54 of file FilterIndex.h.
{ return _column; }
column() [2/2]
const uint32_t & loco::FilterIndex::column (void) const inline
Definition at line 53 of file FilterIndex.h.
{ return _column; }
Referenced by loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingDecoder< Domain::Filter >::value().
nth() [1/2]
uint32_t & loco::FilterIndex::nth (void) inline
Definition at line 45 of file FilterIndex.h.
{ return _nth; }
nth() [2/2]
const uint32_t & loco::FilterIndex::nth (void) const inline
Definition at line 44 of file FilterIndex.h.
{ return _nth; }
Referenced by loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingDecoder< Domain::Filter >::value().
row() [1/2]
uint32_t & loco::FilterIndex::row (void) inline
Definition at line 51 of file FilterIndex.h.
{ return _row; }
row() [2/2]
const uint32_t & loco::FilterIndex::row (void) const inline
Definition at line 50 of file FilterIndex.h.
{ return _row; }
Referenced by loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingDecoder< Domain::Filter >::value().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/FilterIndex.h