ONE - On-device Neural Engine: onert::backend::BackendContext Class Reference
onert::backend::BackendContext Class Reference abstract
#include <BackendContext.h>
Public Member Functions
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~BackendContext ()=default
const Backend * backend () const
const ir::Graph * graph () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
const ContextData & data () const
virtual ITensorRegistry * genTensors ()=0
virtual FunctionMap genKernels ()=0
Data Fields
std::shared_ptr< ITensorRegistry > tensor_registry
Protected Attributes
const Backend * _backend {nullptr}
ContextData _data
Detailed Description
Definition at line 54 of file BackendContext.h.
Constructor & Destructor Documentation
BackendContext()
onert::backend::BackendContext::BackendContext (const Backend * backend, ContextData && data, std::shared_ptr< ITensorRegistry > tensor_registry = nullptr) inline
Definition at line 57 of file BackendContext.h.
    : _backend{backend}, _data{std::move(data)}, tensor_registry{tensor_registry}
  {
  }
~BackendContext()
virtual onert::backend::BackendContext::~BackendContext () virtual default
Member Function Documentation
backend()
const Backend * onert::backend::BackendContext::backend () const inline
Definition at line 65 of file BackendContext.h.
{ return _backend; }
References _backend.
data()
const ContextData & onert::backend::BackendContext::data () const inline
Definition at line 69 of file BackendContext.h.
{ return _data; }
References _data.
external_operands()
const util::Set< ir::OperandIndex > & onert::backend::BackendContext::external_operands () const inline
Definition at line 67 of file BackendContext.h.
{ return _data.external_operands; }
References _data, and onert::backend::ContextData::external_operands.
Referenced by onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), and onert::backend::basic::initConsts().
genKernels()
virtual FunctionMap onert::backend::BackendContext::genKernels () pure virtual
Implemented in onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >, onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >, onert::backend::cpu::BackendContext, onert::backend::gpu_cl::BackendContext, onert::backend::ruy::BackendContext, onert::backend::trix::BackendContext, onert::backend::xnnpack::BackendContext, and onert::backend::builtin::BackendContext.
genTensors()
virtual ITensorRegistry * onert::backend::BackendContext::genTensors () pure virtual
Implemented in onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >, onert::backend::cpu::BackendContext, onert::backend::gpu_cl::BackendContext, onert::backend::ruy::BackendContext, onert::backend::trix::BackendContext, onert::backend::xnnpack::BackendContext, and onert::backend::builtin::BackendContext.
graph()
const ir::Graph * onert::backend::BackendContext::graph () const inline
Definition at line 66 of file BackendContext.h.
{ return _data.graph.get(); }
References _data, and onert::backend::ContextData::graph.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::backend::builtin::BackendContext::genKernels(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::initConsts(), onert::backend::basic::initConsts(), onert::backend::acl_cl::Optimizer::optimize(), onert::backend::acl_neon::Optimizer::optimize(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
operand_layouts()
const ir::OperandIndexMap< ir::Layout > & onert::backend::BackendContext::operand_layouts () const inline
Definition at line 68 of file BackendContext.h.
{ return _data.operand_layouts; }
References _data, and onert::backend::ContextData::operand_layouts.
Referenced by onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), and onert::backend::gpu_cl::BackendContext::genTensors().
Field Documentation
_backend
const Backend* onert::backend::BackendContext::_backend {nullptr} protected
Definition at line 75 of file BackendContext.h.
Referenced by backend().
_data
ContextData onert::backend::BackendContext::_data protected
Definition at line 76 of file BackendContext.h.
Referenced by data(), external_operands(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::genKernels(), onert::backend::cpu::BackendContext::genKernels(), onert::backend::gpu_cl::BackendContext::genKernels(), onert::backend::ruy::BackendContext::genKernels(), onert::backend::trix::BackendContext::genKernels(), onert::backend::xnnpack::BackendContext::genKernels(), onert::backend::builtin::BackendContext::genKernels(), graph(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::initConsts(), operand_layouts(), and onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors().
tensor_registry
std::shared_ptr<ITensorRegistry> onert::backend::BackendContext::tensor_registry
Definition at line 79 of file BackendContext.h.
Referenced by onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), and onert::backend::basic::initConsts().
The documentation for this class was generated from the following file:
runtime/onert/core/include/backend/BackendContext.h