ONE - On-device Neural Engine: onert::exec::LinearExecutor Class Reference
onert::exec::LinearExecutor Class Reference final
Class to handle execution phase. Simple run the sequence of operations that is sorted in topological order.
#include <LinearExecutor.h>
Public Member Functions
LinearExecutor (std::unique_ptr< compiler::LoweredGraph > lowered_graph, backend::BackendContexts &&backend_contexts, const compiler::TensorRegistries &tensor_regs, compiler::CodeMap &&code_map, const std::vector< ir::OperationIndex > &order, const util::TracingCtx *tracing_ctx)
Construct a new LinearExecutor object.
void executeImpl (void) override
Public Member Functions inherited from onert::exec::ExecutorBase
ExecutorBase (std::unique_ptr< compiler::LoweredGraph > &&lowered_graph, backend::BackendContexts &&backend_contexts, const compiler::TensorRegistries &tensor_regs, const util::TracingCtx *tracing_ctx)
Construct a new ExecutorBase object.
virtual ~ExecutorBase ()=default
const ir::Graph & graph () const final
Returns graph object.
void execute (const IODescription &desc) final
Execute with user-given input/output description (for primary subgraph)
void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs) override
Execute with given input/output tensors.
void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > > ranks) final
Set an ordering on operations.
virtual void executeImpl (void)=0
void addObserver (std::unique_ptr< IExecutionObserver > ref)
const std::vector< backend::builtin::IOTensor * > & getInputTensors () const override
Get input tensor objects.
const std::vector< backend::builtin::IOTensor * > & getOutputTensors () const override
Get output tensor objects.
Public Member Functions inherited from onert::exec::IExecutor
IExecutor ()=default
Construct a new IExecutor object.
virtual ~IExecutor ()=default
Destroy the IExecutor object.
virtual const ir::Graph & graph () const =0
Returns graph object.
virtual void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >)=0
Set an ordering on operations.
virtual void execute (const IODescription &desc)=0
Execute with user-given input/output description (for primary subgraph)
virtual void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs)=0
Execute with given input/output tensors.
virtual const std::vector< backend::builtin::IOTensor * > & getInputTensors () const =0
Get input tensor objects.
virtual const std::vector< backend::builtin::IOTensor * > & getOutputTensors () const =0
Get output tensor objects.
Additional Inherited Members
Protected Member Functions inherited from onert::exec::ExecutorBase
bool hasDynamicInput ()
Returns true if any input tensor is dynamic; false if all are static tensors.
Protected Attributes inherited from onert::exec::ExecutorBase
ExecutionObservee _subject
std::shared_ptr< ir::OperationIndexMap< int64_t > > _indexed_ranks
std::unique_ptr< compiler::LoweredGraph > _lowered_graph
backend::BackendContexts _backend_contexts
const ir::Graph & _graph
std::vector< backend::builtin::IOTensor * > _input_tensors
std::vector< backend::builtin::IOTensor * > _output_tensors
std::mutex _mutex
const util::TracingCtx * _tracing_ctx
Detailed Description
Class to handle execution phase. Simple run the sequence of operations that is sorted in topological order.
Definition at line 40 of file LinearExecutor.h.
Constructor & Destructor Documentation
LinearExecutor()
onert::exec::LinearExecutor::LinearExecutor (std::unique_ptr< compiler::LoweredGraph > lowered_graph, backend::BackendContexts && backend_contexts, const compiler::TensorRegistries & tensor_regs, compiler::CodeMap && code_map, const std::vector< ir::OperationIndex > & order, const util::TracingCtx * tracing_ctx) inline
Construct a new LinearExecutor object.
Parameters
lowered_graph LoweredGraph object
tensor_builders Tensor builders that are currently used
code_map ir::Operation and its code map
Definition at line 49 of file LinearExecutor.h.
    : ExecutorBase{std::move(lowered_graph), std::move(backend_contexts), tensor_regs, tracing_ctx}
  {
    for (auto index : order)
    {
      _code.emplace_back(std::move(code_map.at(index)));
    }
  }
Member Function Documentation
executeImpl()
void onert::exec::LinearExecutor::executeImpl (void) override virtual
Implements onert::exec::ExecutorBase.
Definition at line 27 of file LinearExecutor.cc.
{
  if (_tracing_ctx)
  {
    auto profiling_subg_index = _tracing_ctx->getSubgraphIndex(&_graph);
    _subject.notifySubgraphBegin(profiling_subg_index);
    for (auto &&code : _code)
    {
      const auto backend = code.lower_info->backend();
// TODO : Move ruy profiler into ExecutionObserver
#ifdef RUY_PROFILER
      ruy::profiler::ScopeLabel label(code.op->name());
#endif
      _subject.notifyJobBegin(this, profiling_subg_index, code.op_ind, backend);
      auto &fn_seq = code.fn_seq;
      fn_seq->initRunning();
      bool handle_dynamic_tensor =
        _lowered_graph->getHasDynamicTensor(code.op_ind) || hasDynamicInput();
      fn_seq->enableDynamicShapeInferer(handle_dynamic_tensor);
      fn_seq->run();
      _subject.notifyJobEnd(this, profiling_subg_index, code.op_ind, backend);
    }
    _subject.notifySubgraphEnd(profiling_subg_index);
  }
  else
  {
    for (auto &&code : _code)
    {
// TODO : Move ruy profiler into ExecutionObserver
#ifdef RUY_PROFILER
      ruy::profiler::ScopeLabel label(code.op->name());
#endif
      auto &fn_seq = code.fn_seq;
      fn_seq->initRunning();
      bool handle_dynamic_tensor =
        _lowered_graph->getHasDynamicTensor(code.op_ind) || hasDynamicInput();
      fn_seq->enableDynamicShapeInferer(handle_dynamic_tensor);
      fn_seq->run();
    }
  }
}
References onert::exec::ExecutorBase::_graph, onert::exec::ExecutorBase::_lowered_graph, onert::exec::ExecutorBase::_subject, onert::exec::ExecutorBase::_tracing_ctx, onert::util::TracingCtx::getSubgraphIndex(), onert::exec::ExecutorBase::hasDynamicInput(), onert::exec::ExecutionObservee::notifyJobBegin(), onert::exec::ExecutionObservee::notifyJobEnd(), onert::exec::ExecutionObservee::notifySubgraphBegin(), and onert::exec::ExecutionObservee::notifySubgraphEnd().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/LinearExecutor.h
runtime/onert/core/src/exec/LinearExecutor.cc