ONE - On-device Neural Engine: loco::FilterShape Class Reference
loco::FilterShape Class Reference final
Filter Shape.
#include <FilterShape.h>
Public Member Functions
FilterShape ()=default
const Dimension & count (void) const
Dimension & count (void)
const Dimension & depth (void) const
Dimension & depth (void)
const Dimension & height (void) const
Dimension & height (void)
const Dimension & width (void) const
Dimension & width (void)
Detailed Description
Filter Shape.
This class describes the shape of filter, which is an input of 2D convolutional operations (e.g. Convolution).
count() refers to the number of 3D weight in a filter depth() refers to the depth of 3D weights height() refers to the height of 3D weights width() refers to the width of 3D weights
NOTE
The definition of FilterShape is almost same as that of FeatureShape, but loco distinguishes FeatureShape and FilterShape in class-level in order to prevent potential errors by type check.
Definition at line 42 of file FilterShape.h.
Constructor & Destructor Documentation
FilterShape()
loco::FilterShape::FilterShape () default
Member Function Documentation
count() [1/2]
Dimension & loco::FilterShape::count (void) inline
Definition at line 49 of file FilterShape.h.
{ return _count; }
count() [2/2]
const Dimension & loco::FilterShape::count (void) const inline
Definition at line 48 of file FilterShape.h.
{ return _count; }
Referenced by loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), and exo::to_shape_description().
depth() [1/2]
Dimension & loco::FilterShape::depth (void) inline
Definition at line 52 of file FilterShape.h.
{ return _depth; }
depth() [2/2]
const Dimension & loco::FilterShape::depth (void) const inline
Definition at line 51 of file FilterShape.h.
{ return _depth; }
Referenced by loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), and exo::to_shape_description().
height() [1/2]
Dimension & loco::FilterShape::height (void) inline
Definition at line 55 of file FilterShape.h.
{ return _height; }
height() [2/2]
const Dimension & loco::FilterShape::height (void) const inline
Definition at line 54 of file FilterShape.h.
{ return _height; }
Referenced by loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), and exo::to_shape_description().
width() [1/2]
Dimension & loco::FilterShape::width (void) inline
Definition at line 58 of file FilterShape.h.
{ return _width; }
width() [2/2]
const Dimension & loco::FilterShape::width (void) const inline
Definition at line 57 of file FilterShape.h.
{ return _width; }
Referenced by loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), and exo::to_shape_description().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/FilterShape.h