ONE - On-device Neural Engine: luci::ConstantFoldingAddTestGraph Class Reference
luci::ConstantFoldingAddTestGraph Class Reference
#include <PassTestGraphs.h>
Protected Member Functions
ConstantFoldingAddTestGraph (std::vector< uint32_t > input_shape, loco::DataType input_dtype)
void init () override
luci::CircleConst * getFoldedPattern () override
Protected Attributes
luci::CircleAdd * _add = nullptr
Protected Attributes inherited from luci::ConstantFoldingTestGraph
loco::Graph _g
luci::CircleInput * _input = nullptr
luci::CircleOutput * _output = nullptr
Additional Inherited Members
Public Member Functions inherited from luci::ConstantFoldingTestGraph
ConstantFoldingTestGraph (std::vector< uint32_t > input_shape, loco::DataType input_dtype)
virtual void init ()=0
virtual ~ConstantFoldingTestGraph ()=default
virtual loco::Node * createFoldedPattern ()=0
virtual luci::CircleConst * getFoldedPattern ()=0
loco::Graph * graph ()
Detailed Description
ConstantFoldingTestAddGraph is ConstantFoldingTestGraph whose Connector is Add.
Definition at line 107 of file PassTestGraphs.h.
Constructor & Destructor Documentation
ConstantFoldingAddTestGraph()
luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph (std::vector< uint32_t > input_shape, loco::DataType input_dtype) inline protected
Definition at line 110 of file PassTestGraphs.h.
    : ConstantFoldingTestGraph(input_shape, input_dtype)
  {
    _add = _g.nodes()->create<luci::CircleAdd>();
    _add->dtype(input_dtype);
    _add->rank(input_shape.size());
    for (int i = 0; i < input_shape.size(); i++)
      _add->dim(i).set(input_shape[i]);
    _add->x(_input);
    _output->from(_add);
    _add->name("add");
  }
References _add, luci::ConstantFoldingTestGraph::_g, luci::ConstantFoldingTestGraph::_input, luci::ConstantFoldingTestGraph::_output, loco::NodePool::create(), luci::CircleOutput::from(), luci::CircleNode::name(), loco::Graph::nodes(), and luci::CircleAdd::x().
Member Function Documentation
getFoldedPattern()
luci::CircleConst * luci::ConstantFoldingAddTestGraph::getFoldedPattern () inline override protected virtual
Implements luci::ConstantFoldingTestGraph.
Definition at line 131 of file PassTestGraphs.h.
  {
    return dynamic_cast<luci::CircleConst *>(_add->y());
  }
References _add, and luci::CircleAdd::y().
init()
void luci::ConstantFoldingAddTestGraph::init () inline override protected virtual
Implements luci::ConstantFoldingTestGraph.
Definition at line 128 of file PassTestGraphs.h.
{ _add->y(createFoldedPattern()); }
References _add, luci::ConstantFoldingTestGraph::createFoldedPattern(), and luci::CircleAdd::y().
Field Documentation
_add
luci::CircleAdd* luci::ConstantFoldingAddTestGraph::_add = nullptr protected
Definition at line 137 of file PassTestGraphs.h.
Referenced by ConstantFoldingAddTestGraph(), getFoldedPattern(), and init().
The documentation for this class was generated from the following file:
compiler/luci/pass/src/PassTestGraphs.h