ONE - On-device Neural Engine: luci::test::TestGraph Class Reference
luci::test::TestGraph Class Reference
#include <TestGraph.h>
Public Member Functions
TestGraph ()
loco::Graph * graph ()
template<class T >
T * append ()
Creates node with NO arg and appends it to graph.
template<class T >
T * append (luci::CircleNode *arg1)
Creates op T (arity=1) with arg1 as an input and appends it to graph.
template<class T >
T * append (luci::CircleNode *arg1, luci::CircleNode *arg2)
Creates op T (arity=2) with arg1, arg2 as inputs and appends it to graph.
template<class T >
T * append (luci::CircleNode *arg1, luci::CircleNode *arg2, luci::CircleNode *arg3)
Creates op T (arity=3) with arg1, arg2, arg3 as inputs and appends it to graph.
void complete ()
void complete (luci::CircleNode *last_node)
Data Fields
std::unique_ptr< loco::Graph > g
luci::CircleInput * input_node = nullptr
luci::CircleOutput * output_node = nullptr
Detailed Description
Definition at line 34 of file TestGraph.h.
Constructor & Destructor Documentation
TestGraph()
luci::test::TestGraph::TestGraph () inline
Definition at line 41 of file TestGraph.h.
  {
    g = loco::make_graph();
    input_node = g->nodes()->create<luci::CircleInput>();
    output_node = g->nodes()->create<luci::CircleOutput>();
    auto input = g->inputs()->create();
    {
      input->name("input");
      luci::link(input, input_node);
    }
    auto output = g->outputs()->create();
    {
      output->name("output");
      luci::link(output, output_node);
    }
    _next_input = input_node;
  }
References g, input_node, luci::link(), loco::make_graph(), and output_node.
Member Function Documentation
append() [1/4]
template<class T > T * luci::test::TestGraph::append () inline
Creates node with NO arg and appends it to graph.
Definition at line 66 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    _next_input = node;
    return node;
  }
References g.
append() [2/4]
template<class T > T * luci::test::TestGraph::append (luci::CircleNode * arg1) inline
Creates op T (arity=1) with arg1 as an input and appends it to graph.
Definition at line 75 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1);
    _next_input = node;
    return node;
  }
References g.
append() [3/4]
template<class T > T * luci::test::TestGraph::append (luci::CircleNode * arg1, luci::CircleNode * arg2) inline
Creates op T (arity=2) with arg1, arg2 as inputs and appends it to graph.
Definition at line 85 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1, arg2);
    _next_input = node;
    return node;
  }
References g.
append() [4/4]
template<class T > T * luci::test::TestGraph::append (luci::CircleNode * arg1, luci::CircleNode * arg2, luci::CircleNode * arg3) inline
Creates op T (arity=3) with arg1, arg2, arg3 as inputs and appends it to graph.
Definition at line 96 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1, arg2, arg3);
    _next_input = node;
    return node;
  }
References g.
complete() [1/2]
void luci::test::TestGraph::complete () inline
Definition at line 106 of file TestGraph.h.
{ output_node->from(_next_input); }
References luci::CircleOutput::from(), and output_node.
complete() [2/2]
void luci::test::TestGraph::complete (luci::CircleNode * last_node) inline
Definition at line 108 of file TestGraph.h.
{ output_node->from(last_node); }
References luci::CircleOutput::from(), and output_node.
graph()
loco::Graph * luci::test::TestGraph::graph () inline
Definition at line 63 of file TestGraph.h.
{ return g.get(); }
References g.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
g
std::unique_ptr<loco::Graph> luci::test::TestGraph::g
Definition at line 37 of file TestGraph.h.
Referenced by append(), graph(), and TestGraph().
input_node
luci::CircleInput* luci::test::TestGraph::input_node = nullptr
Definition at line 38 of file TestGraph.h.
Referenced by TestGraph().
output_node
luci::CircleOutput* luci::test::TestGraph::output_node = nullptr
Definition at line 39 of file TestGraph.h.
Referenced by complete(), and TestGraph().
The documentation for this class was generated from the following file:
compiler/luci/service/src/TestGraph.h