ONE - On-device Neural Engine: nnkit::support::onnx::Allocator Class Reference
nnkit::support::onnx::Allocator Class Reference final
#include <Allocator.h>
Public Member Functions
Allocator (void)
~Allocator (void)
void * Alloc (size_t size)
void Free (void *p)
const OrtAllocatorInfo * Info (void) const
void LeakCheck (void)
Allocator (const Allocator &)=delete
Allocator & operator= (const Allocator &)=delete
Detailed Description
Definition at line 31 of file Allocator.h.
Constructor & Destructor Documentation
Allocator() [1/2]
nnkit::support::onnx::Allocator::Allocator (void)
Definition at line 29 of file Allocator.cpp.
{
  OrtAllocator::version = ORT_API_VERSION;
  OrtAllocator::Alloc = [](OrtAllocator *this_, size_t size) {
    return static_cast<Allocator *>(this_)->Alloc(size);
  };
  OrtAllocator::Free = [](OrtAllocator *this_, void *p) {
    static_cast<Allocator *>(this_)->Free(p);
  };
  OrtAllocator::Info = [](const OrtAllocator *this_) {
    return static_cast<const Allocator *>(this_)->Info();
  };
  Status status;
  status = OrtCreateCpuAllocatorInfo(OrtDeviceAllocator, OrtMemTypeDefault, &_cpu_allocator_info);
  status.throwOnError();
}
References Alloc(), Free(), Info(), and nnkit::support::onnx::Status::throwOnError().
~Allocator()
nnkit::support::onnx::Allocator::~Allocator (void)
Definition at line 47 of file Allocator.cpp.
{ OrtReleaseAllocatorInfo(_cpu_allocator_info); }
Allocator() [2/2]
nnkit::support::onnx::Allocator::Allocator (const Allocator &) delete
Member Function Documentation
Alloc()
void * nnkit::support::onnx::Allocator::Alloc (size_t size)
Definition at line 49 of file Allocator.cpp.
{
  // NOTE The extra_len is added to check resource leak.
  //
  //      This Alloc function will allocate the given size with extra_len.
  //      The first extra_len will save the allocated memory size and
  //      the user will use address from the allocated memory plus extra_len.
  //      The size value that saved in extra_len is used to Free function
  //      to check resource leak. The size value uses in _memory_inuse.
  constexpr size_t extra_len = sizeof(size_t);
  _memory_inuse.fetch_add(size += extra_len);
  void *p = ::malloc(size);
  *(size_t *)p = size;
  return (char *)p + extra_len;
}
Referenced by Allocator().
Free()
void nnkit::support::onnx::Allocator::Free (void * p)
Definition at line 65 of file Allocator.cpp.
{
  constexpr size_t extra_len = sizeof(size_t);
  if (!p)
    return;
  p = (char *)p - extra_len;
  size_t len = *(size_t *)p;
  _memory_inuse.fetch_sub(len);
  return ::free(p);
}
Referenced by Allocator().
Info()
const OrtAllocatorInfo * nnkit::support::onnx::Allocator::Info (void) const
Definition at line 76 of file Allocator.cpp.
{ return _cpu_allocator_info; }
Referenced by Allocator().
LeakCheck()
void nnkit::support::onnx::Allocator::LeakCheck (void)
Definition at line 78 of file Allocator.cpp.
{
  if (_memory_inuse.load())
  {
    throw std::runtime_error{"memory leak!!!"};
  }
}
operator=()
Allocator & nnkit::support::onnx::Allocator::operator= (const Allocator &) delete
The documentation for this class was generated from the following files:
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/Allocator.h
compiler/nnkit-onnxrt/support/src/Allocator.cpp