ONE - On-device Neural Engine: loco::FeatureShape Class Reference
loco::FeatureShape Class Reference final
Feature Map Shape.
#include <FeatureShape.h>
Public Member Functions
FeatureShape ()=default
const Dimension & count (void) const
Dimension & count (void)
const Dimension & depth (void) const
Dimension & depth (void)
const Dimension & height (void) const
Dimension & height (void)
const Dimension & width (void) const
Dimension & width (void)
Detailed Description
Feature Map Shape.
This class describes the shape of feature maps, which serves as the input/output of 2D convolutional operations (e.g. Convolution).
Each feature map is a collection of 3D features conceptually. Each feature has depth, height, width.
count() refers to the number of features in a feature map depth() refers to the depth of features in a given feature map height() refers to the height of features in a given feature map width() refers to the width of features in a given feature map
Definition at line 39 of file FeatureShape.h.
Constructor & Destructor Documentation
FeatureShape()
loco::FeatureShape::FeatureShape () default
Member Function Documentation
count() [1/2]
Dimension & loco::FeatureShape::count (void) inline
Definition at line 46 of file FeatureShape.h.
{ return _count; }
count() [2/2]
const Dimension & loco::FeatureShape::count (void) const inline
Definition at line 45 of file FeatureShape.h.
{ return _count; }
Referenced by moco::as_tensor_shape(), loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), and exo::to_shape_description().
depth() [1/2]
Dimension & loco::FeatureShape::depth (void) inline
Definition at line 49 of file FeatureShape.h.
{ return _depth; }
depth() [2/2]
const Dimension & loco::FeatureShape::depth (void) const inline
Definition at line 48 of file FeatureShape.h.
{ return _depth; }
Referenced by moco::as_tensor_shape(), loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), and exo::to_shape_description().
height() [1/2]
Dimension & loco::FeatureShape::height (void) inline
Definition at line 52 of file FeatureShape.h.
{ return _height; }
height() [2/2]
const Dimension & loco::FeatureShape::height (void) const inline
Definition at line 51 of file FeatureShape.h.
{ return _height; }
Referenced by moco::as_tensor_shape(), moco::make_plane_shape(), loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), exo::to_shape_description(), and moco::FeatureShapeUpdater::with().
width() [1/2]
Dimension & loco::FeatureShape::width (void) inline
Definition at line 55 of file FeatureShape.h.
{ return _width; }
width() [2/2]
const Dimension & loco::FeatureShape::width (void) const inline
Definition at line 54 of file FeatureShape.h.
{ return _width; }
Referenced by moco::as_tensor_shape(), moco::make_plane_shape(), loco::operator<<(), loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), exo::to_shape_description(), and moco::FeatureShapeUpdater::with().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/FeatureShape.h