ONE - On-device Neural Engine: locoex::TFLMul Class Reference
locoex::TFLMul Class Reference final
MUL in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
loco::Node * x (void) const
void x (loco::Node *node)
loco::Node * y (void) const
void y (loco::Node *node)
Public Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::MUL >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >
TFLNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >
loco::Use * at (unsigned n) const
Detailed Description
MUL in TensorFlow Lite.
Definition at line 373 of file TFLNodes.h.
Member Function Documentation
x() [1/2]
void locoex::TFLMul::x (loco::Node * node) inline
Definition at line 378 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >::at(), and loco::Use::node().
x() [2/2]
loco::Node * locoex::TFLMul::x (void) const inline
Definition at line 377 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >::at(), and loco::Use::node().
y() [1/2]
void locoex::TFLMul::y (loco::Node * node) inline
Definition at line 381 of file TFLNodes.h.
{ at(1)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >::at(), and loco::Use::node().
y() [2/2]
loco::Node * locoex::TFLMul::y (void) const inline
Definition at line 380 of file TFLNodes.h.
{ return at(1)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MUL > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h