ONE - On-device Neural Engine: moco::TensorPackEnumerator Class Reference
moco::TensorPackEnumerator Class Reference
#include <TensorPackEnumerator.h>
Public Member Functions
TensorPackEnumerator ()=default
void shape (const loco::TensorShape &si, const loco::TensorShape &so)
void axis (uint32_t axis)
void start (void)
bool valid (void)
void advance (void)
uint32_t inp_num (void) const
uint32_t inp_element (void) const
uint32_t out_element (void) const
Detailed Description
Definition at line 29 of file TensorPackEnumerator.h.
Constructor & Destructor Documentation
TensorPackEnumerator()
moco::TensorPackEnumerator::TensorPackEnumerator () default
Member Function Documentation
advance()
void moco::TensorPackEnumerator::advance (void)
Definition at line 88 of file TensorPackEnumerator.cpp.
{
  uint32_t r = _rank_out - 1;
  increment(r);
  // from _cursor_out, set _cursor_inp and _num
  for (int32_t r = 0, s = 0; r < _rank_out; ++r)
  {
    if (r == _axis)
    {
      _num_inp = _cursor_out.at(r);
    }
    else
    {
      _cursor_inp.at(s) = _cursor_out.at(r);
      s++;
    }
  }
}
axis()
void moco::TensorPackEnumerator::axis (uint32_t axis) inline
Definition at line 36 of file TensorPackEnumerator.h.
{ _axis = axis; }
References axis().
Referenced by axis().
inp_element()
uint32_t moco::TensorPackEnumerator::inp_element (void) const
Definition at line 110 of file TensorPackEnumerator.cpp.
{
  uint32_t rank = _rank_out - 1;
  uint32_t element = 0;
  for (uint32_t r = 0; r < rank; ++r)
  {
    uint32_t dim = _boundary_inp.at(r);
    element = element * dim + _cursor_inp.at(r);
  }
  return element;
}
inp_num()
uint32_t moco::TensorPackEnumerator::inp_num (void) const
Definition at line 108 of file TensorPackEnumerator.cpp.
{ return _num_inp; }
out_element()
uint32_t moco::TensorPackEnumerator::out_element (void) const
Definition at line 122 of file TensorPackEnumerator.cpp.
{
  uint32_t rank = _rank_out;
  uint32_t element = 0;
  for (uint32_t r = 0; r < rank; ++r)
  {
    uint32_t dim = _boundary_out.at(r);
    element = element * dim + _cursor_out.at(r);
  }
  return element;
}
shape()
void moco::TensorPackEnumerator::shape (const loco::TensorShape & si, const loco::TensorShape & so)
Definition at line 24 of file TensorPackEnumerator.cpp.
{
  _shape_inp = si;
  _shape_out = so;
  assert(_shape_inp.rank() + 1 == _shape_out.rank());
  _rank_out = _shape_out.rank();
}
References loco::TensorShape::rank().
start()
void moco::TensorPackEnumerator::start (void)
Definition at line 52 of file TensorPackEnumerator.cpp.
{
  uint32_t rank = _rank_out;
  _cursor_out.resize(rank);
  _boundary_out.resize(rank);
  for (uint32_t r = 0; r < rank; ++r)
  {
    _cursor_out.at(r) = 0;
    _boundary_out.at(r) = _shape_out.dim(r).value();
  }
  rank = _rank_out - 1;
  _cursor_inp.resize(rank);
  _boundary_inp.resize(rank);
  for (uint32_t r = 0; r < rank; ++r)
  {
    _cursor_inp.at(r) = 0;
    _boundary_inp.at(r) = _shape_inp.dim(r).value();
  }
  _num_inp = 0;
}
References loco::TensorShape::dim(), and loco::Dimension::value().
valid()
bool moco::TensorPackEnumerator::valid (void)
Definition at line 75 of file TensorPackEnumerator.cpp.
{
  uint32_t rank = _rank_out;
  for (uint32_t r = 0; r < rank; ++r)
  {
    if (_cursor_out.at(r) >= _boundary_out.at(r))
    {
      return false;
    }
  }
  return true;
}
The documentation for this class was generated from the following files:
compiler/moco/pass/src/TensorPackEnumerator.h
compiler/moco/pass/src/TensorPackEnumerator.cpp