ONE - On-device Neural Engine: kbenchmark::operation::Convolution Class Reference
kbenchmark::operation::Convolution Class Reference final
#include <Convolution.h>
Public Member Functions
Convolution ()=default
nonius::parameters params (int layer_num, OperationInfo &info) override
Public Member Functions inherited from kbenchmark::Operation
Operation ()=default
Detailed Description
Definition at line 28 of file Convolution.h.
Constructor & Destructor Documentation
Convolution()
kbenchmark::operation::Convolution::Convolution () default
Member Function Documentation
params()
nonius::parameters kbenchmark::operation::Convolution::params (int layer_num, OperationInfo & info) inline override virtual
Implements kbenchmark::Operation.
Definition at line 33 of file Convolution.h.
  {
    nonius::parameters params;
    params.insert({"LAYER", nonius::param{layer_num}});
    params.insert({"BATCH", nonius::param{1}});
    auto _input = get_key_dims({"input"}, info);
    params.insert({"IFM_C", nonius::param{_input[3]}});
    params.insert({"IFM_H", nonius::param{_input[1]}});
    params.insert({"IFM_W", nonius::param{_input[2]}});
    auto _output0 = get_key_dims({"output0"}, info);
    params.insert({"OFM_C", nonius::param{_output0[3]}});
    params.insert({"OFM_H", nonius::param{_output0[1]}});
    params.insert({"OFM_W", nonius::param{_output0[2]}});
    auto _weights = get_key_dims({"weights"}, info);
    params.insert({"KER_H", nonius::param{_weights[1]}});
    params.insert({"KER_W", nonius::param{_weights[2]}});
    auto _stride_h = get_key_int({"stride_h"}, info);
    auto _stride_w = get_key_int({"stride_w"}, info);
    params.insert({"STRIDE_H", nonius::param{_stride_h}});
    params.insert({"STRIDE_W", nonius::param{_stride_w}});
    auto _pad = get_key_string({"padding"}, info);
    params.insert({"PADDING", nonius::param{_pad}});
    auto _act = get_key_string({"fused_act"}, info);
    params.insert({"FUSED_ACT", nonius::param{_act}});
    return params;
  }
References kbenchmark::get_key_dims(), kbenchmark::get_key_int(), kbenchmark::get_key_string(), info, and params().
Referenced by params().
The documentation for this class was generated from the following file:
runtime/tools/kbenchmark/operations/Convolution.h