ONE - On-device Neural Engine: onert::backend::cpu::ops::ReshapeLayer Class Reference
onert::backend::cpu::ops::ReshapeLayer Class Reference
#include <ReshapeLayer.h>
Public Member Functions
ReshapeLayer ()
void reshapeGeneric ()
void configure (const IPortableTensor *input, const IPortableTensor *shape, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file ReshapeLayer.h.
Constructor & Destructor Documentation
ReshapeLayer()
onert::backend::cpu::ops::ReshapeLayer::ReshapeLayer ()
Definition at line 28 of file ReshapeLayer.cc.
                           : _input(nullptr), _shape(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::ReshapeLayer::configure (const IPortableTensor * input, const IPortableTensor * shape, IPortableTensor * output)
Definition at line 39 of file ReshapeLayer.cc.
{
  _input = input;
  /* note : shape is optional. If not provided from model, _shape is nullptr. */
  _shape = shape;
  _output = output;
}
reshapeGeneric()
void onert::backend::cpu::ops::ReshapeLayer::reshapeGeneric ()
Definition at line 33 of file ReshapeLayer.cc.
{
  size_t count = _input->total_size();
  memcpy(_output->buffer(), _input->buffer(), count);
}
References onert::backend::ITensor::buffer(), and onert::backend::ITensor::total_size().
Referenced by run().
run()
void onert::backend::cpu::ops::ReshapeLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 48 of file ReshapeLayer.cc.
{ reshapeGeneric(); }
References reshapeGeneric().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ReshapeLayer.h
runtime/onert/backend/cpu/ops/ReshapeLayer.cc