ONE - On-device Neural Engine: onert::backend::acl_common::AclConstantInitializer Class Reference
onert::backend::acl_common::AclConstantInitializer Class Reference
#include <AclConstantInitializer.h>
Public Types
using Initializer = std::function< void(const ir::Operand &, backend::ITensor &)>
Public Member Functions
void run ()
AclConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void registerDefaultInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerCopyInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerPermuteInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void setLayout (ir::Layout layout)
bool exist (const ir::OperandIndex &ind)
void visit (const ir::operation::BatchToSpaceND &) override
void visit (const ir::operation::Conv2D &) override
void visit (const ir::operation::DepthwiseConv2D &) override
void visit (const ir::operation::FullyConnected &) override
void visit (const ir::operation::LSTM &) override
void visit (const ir::operation::RNN &) override
void visit (const ir::operation::TransposeConv &) override
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Protected Member Functions
void copyInputInitialize (const ir::Operation &node, uint32_t index)
void permuteInputInitialize (const ir::Operation &node, uint32_t index)
Protected Attributes
const ir::Operands & _operands
std::shared_ptr< ITensorRegistry > _tensor_reg
std::unordered_map< ir::OperandIndex, Initializer > _init_map
ir::Layout _current_layout
Detailed Description
Definition at line 173 of file AclConstantInitializer.h.
Member Typedef Documentation
Initializer
using onert::backend::acl_common::AclConstantInitializer::Initializer = std::function<void(const ir::Operand &, backend::ITensor &)>
Definition at line 198 of file AclConstantInitializer.h.
Constructor & Destructor Documentation
AclConstantInitializer()
onert::backend::acl_common::AclConstantInitializer::AclConstantInitializer (const ir::Operands & operands, const std::shared_ptr< ITensorRegistry > & tensor_reg)
Definition at line 26 of file AclConstantInitializer.cc.
  : _operands{operands}, _tensor_reg{tensor_reg}, _current_layout{ir::Layout::UNKNOWN}
{
  // DO NOTHING
}
Member Function Documentation
copyInputInitialize()
void onert::backend::acl_common::AclConstantInitializer::copyInputInitialize (const ir::Operation & node, uint32_t index) protected
Definition at line 33 of file AclConstantInitializer.cc.
{
  assert(node.getInputs().size() > index);
  const auto &input_index = node.getInputs().at(index);
  if (input_index.valid())
  {
    const auto &input_obj = _operands.at(input_index);
    registerCopyInitializer(input_index, input_obj);
  }
}
References _operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), registerCopyInitializer(), and onert::ir::OperandIndexSequence::size().
Referenced by visit(), and onert::backend::acl_cl::ConstantInitializer::visit().
exist()
bool onert::backend::acl_common::AclConstantInitializer::exist (const ir::OperandIndex & ind) inline
Definition at line 210 of file AclConstantInitializer.h.
{ return _init_map.find(ind) != _init_map.end(); }
References _init_map.
permuteInputInitialize()
void onert::backend::acl_common::AclConstantInitializer::permuteInputInitialize (const ir::Operation & node, uint32_t index) protected
Definition at line 45 of file AclConstantInitializer.cc.
{
  assert(node.getInputs().size() > index);
  const auto &input_index = node.getInputs().at(index);
  const auto &input_obj = _operands.at(input_index);
  registerPermuteInitializer(input_index, input_obj);
}
References _operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), registerPermuteInitializer(), and onert::ir::OperandIndexSequence::size().
Referenced by visit().
registerCopyInitializer()
void onert::backend::acl_common::AclConstantInitializer::registerCopyInitializer (const ir::OperandIndex & index, const ir::Operand & obj)
Definition at line 132 of file AclConstantInitializer.cc.
{
  // For only CONSTANTS
  // TODO Add to check if tensor has been allocated
  if (!obj.isConstant())
    return;
  const auto type = obj.typeInfo().type();
  using ir::DataType;
  switch (type)
  {
    case DataType::FLOAT32:
      _init_map[index] = copyInit<float>;
      break;
    case DataType::INT32:
      _init_map[index] = copyInit<int32_t>;
      break;
    case DataType::UINT32:
      _init_map[index] = copyInit<uint32_t>;
      break;
    case DataType::BOOL8:
    case DataType::QUANT_UINT8_ASYMM:
      _init_map[index] = copyInit<uint8_t>;
      break;
    case DataType::QUANT_INT8_SYMM:
    case DataType::QUANT_INT8_ASYMM:
      _init_map[index] = copyInit<int8_t>;
      break;
    case DataType::FLOAT16:
      _init_map[index] = copyInit<float16>;
      break;
    case DataType::INT64:
      _init_map[index] = copyInit<int64_t>;
      break;
    default:
      throw std::runtime_error("Not supported, yet");
      break;
  }
}
References _init_map.
Referenced by copyInputInitialize().
registerDefaultInitializer()
void onert::backend::acl_common::AclConstantInitializer::registerDefaultInitializer (const ir::OperandIndex & index, const ir::Operand & obj) inline
Definition at line 201 of file AclConstantInitializer.h.
  {
    registerPermuteInitializer(index, obj);
  }
References registerPermuteInitializer().
registerPermuteInitializer()
void onert::backend::acl_common::AclConstantInitializer::registerPermuteInitializer (const ir::OperandIndex & index, const ir::Operand & obj)
Definition at line 174 of file AclConstantInitializer.cc.
{
  // For only CONSTANTS
  // TODO Add to check if tensor has been allocated
  if (!obj.isConstant())
    return;
  const auto type = obj.typeInfo().type();
  using ir::DataType;
  using namespace std::placeholders;
  switch (type)
  {
    case DataType::FLOAT32:
      _init_map[index] = std::bind(permuteInit<float>, _1, _2, _current_layout);
      break;
    case DataType::INT32:
      _init_map[index] = std::bind(permuteInit<int32_t>, _1, _2, _current_layout);
      break;
    case DataType::UINT32:
      _init_map[index] = std::bind(permuteInit<uint32_t>, _1, _2, _current_layout);
      break;
    case DataType::BOOL8:
    case DataType::QUANT_UINT8_ASYMM:
      _init_map[index] = std::bind(permuteInit<uint8_t>, _1, _2, _current_layout);
      break;
    case DataType::QUANT_INT8_SYMM:
    case DataType::QUANT_INT8_ASYMM:
      _init_map[index] = std::bind(permuteInit<int8_t>, _1, _2, _current_layout);
      break;
    case DataType::FLOAT16:
      _init_map[index] = std::bind(permuteInit<float16>, _1, _2, _current_layout);
      break;
    case DataType::INT64:
      _init_map[index] = std::bind(permuteInit<int64_t>, _1, _2, _current_layout);
      break;
    default:
      throw std::runtime_error("Not supported, yet");
      break;
  }
}
References _current_layout, and _init_map.
Referenced by permuteInputInitialize(), and registerDefaultInitializer().
run()
void onert::backend::acl_common::AclConstantInitializer::run () inline
Definition at line 176 of file AclConstantInitializer.h.
  {
    assert(_tensor_reg);
    for (const auto &it : _init_map)
    {
      const auto &ind = it.first;
      const auto &fn = it.second;
      const auto &model_obj = _operands.at(ind);
      auto tensor_obj = _tensor_reg->getNativeITensor(ind);
      assert(tensor_obj != nullptr);
      fn(model_obj, *tensor_obj);
      VERBOSE(FillOperandData) << "Fill data for operand " << ind << std::endl;
    }
    _init_map.clear();
  }
References _init_map, _operands, _tensor_reg, onert::util::ObjectManager< Index, Object >::at(), and VERBOSE.
setLayout()
void onert::backend::acl_common::AclConstantInitializer::setLayout (ir::Layout layout) inline
Definition at line 209 of file AclConstantInitializer.h.
{ _current_layout = layout; }
References _current_layout.
visit() [1/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::BatchToSpaceND & node) override
Definition at line 54 of file AclConstantInitializer.cc.
{
  const auto &block_size_index = node.getInputs().at(ir::operation::BatchToSpaceND::BLOCK_SIZE);
  const auto &block_size_obj = _operands.at(block_size_index);
  if (block_size_obj.isConstant())
  {
    _init_map[block_size_index] = [](const ir::Operand &model_obj, backend::ITensor &obj) {
      assert(model_obj.data());
      const auto &shape = model_obj.shape();
      const auto base = reinterpret_cast<const int32_t *>(model_obj.data()->base());
      assert(model_obj.shape().rank() == 1);
      obj.access([&](ITensor &tensor) {
        for (size_t i = 0; i < shape.num_elements(); ++i)
        {
          const int32_t value = base[shape.num_elements() - i - 1];
          int32_t *into = reinterpret_cast<int32_t *>(tensor.buffer() +
                                                      tensor.calcOffset({static_cast<int32_t>(i)}));
          *into = value;
        }
      });
    };
  }
}
References _init_map, _operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::BatchToSpaceND::BLOCK_SIZE, onert::ir::Operand::data(), onert::ir::Operation::getInputs(), and onert::ir::Operand::shape().
visit() [2/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::Conv2D & node) override
Definition at line 79 of file AclConstantInitializer.cc.
{
  permuteInputInitialize(node, ir::operation::Conv2D::KERNEL);
  copyInputInitialize(node, ir::operation::Conv2D::BIAS);
}
References onert::ir::operation::Conv2D::BIAS, copyInputInitialize(), onert::ir::operation::Conv2D::KERNEL, and permuteInputInitialize().
visit() [3/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::DepthwiseConv2D & node) override
Definition at line 85 of file AclConstantInitializer.cc.
{
  permuteInputInitialize(node, ir::operation::DepthwiseConv2D::KERNEL);
  copyInputInitialize(node, ir::operation::DepthwiseConv2D::BIAS);
}
References onert::ir::operation::DepthwiseConv2D::BIAS, copyInputInitialize(), onert::ir::operation::DepthwiseConv2D::KERNEL, and permuteInputInitialize().
visit() [4/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::FullyConnected & node) override
Definition at line 91 of file AclConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::FullyConnected::WEIGHT);
  copyInputInitialize(node, ir::operation::FullyConnected::BIAS);
}
References onert::ir::operation::FullyConnected::BIAS, copyInputInitialize(), and onert::ir::operation::FullyConnected::WEIGHT.
visit() [5/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::LSTM & node) override
Definition at line 97 of file AclConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::LSTM::INPUT_TO_INPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::INPUT_TO_FORGET_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::INPUT_TO_CELL_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::INPUT_TO_OUTPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::RECURRENT_TO_INPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::RECURRENT_TO_FORGET_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::RECURRENT_TO_CELL_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::RECURRENT_TO_OUTPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::CELL_TO_INPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::CELL_TO_FORGET_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::CELL_TO_OUTPUT_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::INPUT_GATE_BIAS);
  copyInputInitialize(node, ir::operation::LSTM::FORGET_GATE_BIAS);
  copyInputInitialize(node, ir::operation::LSTM::OUTPUT_GATE_BIAS);
  copyInputInitialize(node, ir::operation::LSTM::PROJECTION_WEIGHTS);
  copyInputInitialize(node, ir::operation::LSTM::PROJECTION_BIAS);
}
References onert::ir::operation::LSTM::CELL_TO_FORGET_WEIGHTS, onert::ir::operation::LSTM::CELL_TO_INPUT_WEIGHTS, onert::ir::operation::LSTM::CELL_TO_OUTPUT_WEIGHTS, copyInputInitialize(), onert::ir::operation::LSTM::FORGET_GATE_BIAS, onert::ir::operation::LSTM::INPUT_GATE_BIAS, onert::ir::operation::LSTM::INPUT_TO_CELL_WEIGHTS, onert::ir::operation::LSTM::INPUT_TO_FORGET_WEIGHTS, onert::ir::operation::LSTM::INPUT_TO_INPUT_WEIGHTS, onert::ir::operation::LSTM::INPUT_TO_OUTPUT_WEIGHTS, onert::ir::operation::LSTM::OUTPUT_GATE_BIAS, onert::ir::operation::LSTM::PROJECTION_BIAS, onert::ir::operation::LSTM::PROJECTION_WEIGHTS, onert::ir::operation::LSTM::RECURRENT_TO_CELL_WEIGHTS, onert::ir::operation::LSTM::RECURRENT_TO_FORGET_WEIGHTS, onert::ir::operation::LSTM::RECURRENT_TO_INPUT_WEIGHTS, and onert::ir::operation::LSTM::RECURRENT_TO_OUTPUT_WEIGHTS.
visit() [6/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::RNN & node) override
Definition at line 117 of file AclConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::RNN::WEIGHTS);
  copyInputInitialize(node, ir::operation::RNN::RECURRENT_WEIGHTS);
  copyInputInitialize(node, ir::operation::RNN::BIAS);
}
References onert::ir::operation::RNN::BIAS, copyInputInitialize(), onert::ir::operation::RNN::RECURRENT_WEIGHTS, and onert::ir::operation::RNN::WEIGHTS.
visit() [7/7]
void onert::backend::acl_common::AclConstantInitializer::visit (const ir::operation::TransposeConv & node) override
Definition at line 124 of file AclConstantInitializer.cc.
{
  permuteInputInitialize(node, ir::operation::TransposeConv::KERNEL);
}
References onert::ir::operation::TransposeConv::KERNEL, and permuteInputInitialize().
Field Documentation
_current_layout
ir::Layout onert::backend::acl_common::AclConstantInitializer::_current_layout protected
Definition at line 229 of file AclConstantInitializer.h.
Referenced by registerPermuteInitializer(), setLayout(), and onert::backend::acl_cl::ConstantInitializer::visit().
_init_map
std::unordered_map<ir::OperandIndex, Initializer> onert::backend::acl_common::AclConstantInitializer::_init_map protected
Definition at line 228 of file AclConstantInitializer.h.
Referenced by exist(), registerCopyInitializer(), registerPermuteInitializer(), run(), visit(), onert::backend::acl_cl::ConstantInitializer::visit(), and onert::backend::acl_neon::ConstantInitializer::visit().
_operands
const ir::Operands& onert::backend::acl_common::AclConstantInitializer::_operands protected
Definition at line 226 of file AclConstantInitializer.h.
Referenced by copyInputInitialize(), permuteInputInitialize(), run(), visit(), onert::backend::acl_cl::ConstantInitializer::visit(), and onert::backend::acl_neon::ConstantInitializer::visit().
_tensor_reg
std::shared_ptr<ITensorRegistry> onert::backend::acl_common::AclConstantInitializer::_tensor_reg protected
Definition at line 227 of file AclConstantInitializer.h.
Referenced by run(), and onert::backend::acl_cl::ConstantInitializer::visit().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_common/AclConstantInitializer.h
runtime/onert/backend/acl_common/AclConstantInitializer.cc