ONE - On-device Neural Engine: GraphTestcase< GraphCode::MaxPool2D > Class Reference
GraphTestcase< GraphCode::MaxPool2D > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::Pull * pull_node = nullptr
loco::FeatureEncode * encode_node = nullptr
loco::MaxPool2D * maxpool2d_node = nullptr
loco::FeatureDecode * decode_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 341 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::MaxPool2D >::GraphTestcase () inline
Definition at line 344 of file GraphTestcase.h.
  {
    using namespace loco;
    // Create a sample network
    _graph = make_graph();
    // Create Graph Input/Output
    auto graph_input = _graph->inputs()->create();
    auto graph_output = _graph->outputs()->create();
    graph_input->name("input");
    graph_output->name("output");
    // Create and connect nodes
    pull_node = _graph->nodes()->create<Pull>();
    pull_node->index(0);
    encode_node = _graph->nodes()->create<FeatureEncode>();
    encode_node->input(pull_node);
    maxpool2d_node = _graph->nodes()->create<MaxPool2D>();
    maxpool2d_node->ifm(encode_node);
    decode_node = _graph->nodes()->create<FeatureDecode>();
    decode_node->input(maxpool2d_node);
    push_node = _graph->nodes()->create<loco::Push>();
    push_node->index(0);
    push_node->from(decode_node);
    // Create a link between input/output and corresponding nodes
    loco::link(graph_input, pull_node);
    loco::link(graph_output, push_node);
  }
References loco::Push::from(), loco::MaxPool2D::ifm(), loco::Pull::index(), loco::Push::index(), loco::FeatureEncode::input(), loco::FeatureDecode::input(), and loco::link().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::MaxPool2D >::graph () inline
Definition at line 381 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
decode_node
loco::FeatureDecode* GraphTestcase< GraphCode::MaxPool2D >::decode_node = nullptr
Definition at line 386 of file GraphTestcase.h.
encode_node
loco::FeatureEncode* GraphTestcase< GraphCode::MaxPool2D >::encode_node = nullptr
Definition at line 384 of file GraphTestcase.h.
maxpool2d_node
loco::MaxPool2D* GraphTestcase< GraphCode::MaxPool2D >::maxpool2d_node = nullptr
Definition at line 385 of file GraphTestcase.h.
pull_node
loco::Pull* GraphTestcase< GraphCode::MaxPool2D >::pull_node = nullptr
Definition at line 383 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::MaxPool2D >::push_node = nullptr
Definition at line 387 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h