ONE - On-device Neural Engine: arm_compute::CLPadLayerKernelEx Class Reference
arm_compute::CLPadLayerKernelEx Class Reference
#include <CLPadLayerKernelEx.h>
Public Member Functions
CLPadLayerKernelEx ()
CLPadLayerKernelEx (const CLPadLayerKernelEx &)=delete
CLPadLayerKernelEx & operator= (const CLPadLayerKernelEx &)=delete
CLPadLayerKernelEx (CLPadLayerKernelEx &&)=default
CLPadLayerKernelEx & operator= (CLPadLayerKernelEx &&)=default
~CLPadLayerKernelEx ()=default
void configure (const ICLTensor *input, ICLTensor *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
void configure (const CLCompileContext &compile_context, const ICLTensor *input, ICLTensor *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
Detailed Description
Interface for the PadLayer function.
Definition at line 51 of file CLPadLayerKernelEx.h.
Constructor & Destructor Documentation
CLPadLayerKernelEx() [1/3]
arm_compute::CLPadLayerKernelEx::CLPadLayerKernelEx ()
Default constructor
Definition at line 126 of file CLPadLayerKernelEx.cpp.
  : _input(nullptr), _output(nullptr), _input_start_x(0), _input_start_y(0), _4d_enabled(false)
{
}
CLPadLayerKernelEx() [2/3]
arm_compute::CLPadLayerKernelEx::CLPadLayerKernelEx (const CLPadLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPadLayerKernelEx() [3/3]
arm_compute::CLPadLayerKernelEx::CLPadLayerKernelEx (CLPadLayerKernelEx &&) default
Allow instances of this class to be moved
~CLPadLayerKernelEx()
arm_compute::CLPadLayerKernelEx::~CLPadLayerKernelEx () default
Default destructor
References validate().
Member Function Documentation
configure() [1/2]
void arm_compute::CLPadLayerKernelEx::configure (const CLCompileContext & compile_context, const ICLTensor * input, ICLTensor * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT)
Set the input and output tensor.
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 139 of file CLPadLayerKernelEx.cpp.
{
  ARM_COMPUTE_UNUSED(compile_context);
  // Perform validation step
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), output->info(), padding, constant_value, mode));
  _input = input;
  _output = output;
  _4d_enabled = (mode == PaddingMode::CONSTANT) && (padding.size() > 3);
  // Configure window
  unsigned int vec_size;
  auto win_config = validate_and_configure_window(input->info(), output->info(), padding,
                                                  constant_value, mode, vec_size);
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  ICLKernel::configure_internal(win_config.second);
  // Set build options
  std::string kernel_name = "pad_layer_";
  const DataType &data_type = input->info()->data_type();
  const unsigned int input_width = input->info()->dimension(0);
  const unsigned int input_height = input->info()->dimension(1);
  const unsigned int input_depth = input->info()->dimension(2);
  const unsigned int pad_x_before = padding.at(0).first;
  const unsigned int pad_y_before = padding.size() > 1 ? padding.at(1).first : 0;
  const unsigned int pad_z_before = padding.size() > 2 ? padding.at(2).first : 0;
  const unsigned int pad_right_start = input_width + pad_x_before;
  _input_start_x = mode == PaddingMode::CONSTANT ? -(pad_x_before % vec_size) : 0;
  _input_start_y = (mode == PaddingMode::CONSTANT && padding.size() > 1) ? -padding.at(1).first : 0;
  CLBuildOptions build_opts;
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
  build_opts.add_option("-DSELECT_DT=" + get_cl_select_type_from_data_type(data_type));
  build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size));
  build_opts.add_option("-DPAD_X_BEFORE=" + support::cpp11::to_string(pad_x_before));
  build_opts.add_option("-DSRC_WIDTH=" + support::cpp11::to_string(input_width));
  if (padding.size() > 1)
  {
    build_opts.add_option("-DPAD_Y_BEFORE=" + support::cpp11::to_string(pad_y_before));
    build_opts.add_option("-DSRC_HEIGHT=" + support::cpp11::to_string(input_height));
    if (padding.size() > 2)
    {
      build_opts.add_option("-DPAD_Z_BEFORE=" + support::cpp11::to_string(pad_z_before));
      build_opts.add_option("-DSRC_DEPTH=" + support::cpp11::to_string(input_depth));
    }
  }
  switch (mode)
  {
    case PaddingMode::CONSTANT:
    {
      kernel_name += "constant";
      build_opts.add_option("-DCONST_VAL=" + string_from_pixel_value(constant_value, data_type));
      build_opts.add_option_if(pad_x_before >= vec_size,
                               "-DNUM_THREADS_TO_SKIP_X=" +
                                 support::cpp11::to_string(pad_x_before / vec_size));
      if (_4d_enabled)
      {
        build_opts.add_option("-DPAD_W_BEFORE=" + support::cpp11::to_string(padding.at(3).first));
        build_opts.add_option("-DSRC_BATCH=" +
                              support::cpp11::to_string(input->info()->dimension(3)));
      }
      break;
    }
    case PaddingMode::SYMMETRIC:
    case PaddingMode::REFLECT:
    {
      kernel_name += "symmetric_reflect";
      const auto is_reflect = static_cast<unsigned int>(mode == PaddingMode::REFLECT);
      const unsigned int pad_x_before_remainder = pad_x_before % vec_size;
      const unsigned int pad_x_after_remainder = pad_right_start % vec_size;
      const unsigned int after_pad_fact_x = (2 * input_width + pad_x_before) - is_reflect;
      const unsigned int output_last_x =
        ceil_to_multiple(pad_right_start + padding.at(0).second, vec_size);
      build_opts.add_option("-DIS_REFLECT=" + support::cpp11::to_string(is_reflect));
      build_opts.add_option("-DPAD_X_BEFORE_REMAINDER=" +
                            support::cpp11::to_string(pad_x_before_remainder));
      build_opts.add_option("-DPAD_X_AFTER_REMAINDER=" +
                            support::cpp11::to_string(pad_x_after_remainder));
      build_opts.add_option(
        "-DPAD_X_BEFORE_REMAINDER_REFL=" +
        support::cpp11::to_string((pad_x_before_remainder + is_reflect) % vec_size));
      build_opts.add_option(
        "-DPAD_X_AFTER_REMAINDER_REFL=" +
        support::cpp11::to_string((pad_x_after_remainder - is_reflect) % vec_size));
      build_opts.add_option("-DAFTER_PAD_FACT_X=" + support::cpp11::to_string(after_pad_fact_x));
      build_opts.add_option_if(after_pad_fact_x < output_last_x,
                               "-DAFTER_PAD_REM=" +
                                 support::cpp11::to_string(after_pad_fact_x % vec_size));
      break;
    }
    default:
      ARM_COMPUTE_ERROR("Padding mode not supported.");
  }
  // Create kernel
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel(kernel_name, build_opts.options()));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
configure() [2/2]
void arm_compute::CLPadLayerKernelEx::configure (const ICLTensor * input, ICLTensor * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT)
Set the input and output tensor.
Parameters
[in] input Source tensor. Data types supported: U8, S8, QASYMM8, QASYMM8_SIGNED, U16, S16, U32, S32, F16, F32.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 131 of file CLPadLayerKernelEx.cpp.
{
  configure(CLKernelLibrary::get().get_compile_context(), input, output, padding, constant_value,
            mode);
}
References configure().
Referenced by configure().
operator=() [1/2]
CLPadLayerKernelEx & arm_compute::CLPadLayerKernelEx::operator= (CLPadLayerKernelEx &&) default
Allow instances of this class to be moved
operator=() [2/2]
CLPadLayerKernelEx & arm_compute::CLPadLayerKernelEx::operator= (const CLPadLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLPadLayerKernelEx::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 267 of file CLPadLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
  Window win_in = window;
  win_in.adjust(Window::DimX, _input_start_x, true);
  win_in.adjust(Window::DimY, _input_start_y, true);
  Window slice_out = window.first_slice_window_3D();
  Window slice_in = win_in.first_slice_window_3D();
  unsigned int batch = 0;
  do
  {
    unsigned int idx = 0;
    add_3D_tensor_argument(idx, _input, slice_in);
    add_3D_tensor_argument(idx, _output, slice_out);
    if (_4d_enabled)
    {
      add_argument<unsigned int>(idx, batch++);
    }
    enqueue(queue, *this, slice_out, lws_hint());
  } while (window.slide_window_slice_3D(slice_out) && win_in.slide_window_slice_3D(slice_in));
}
validate()
Status arm_compute::CLPadLayerKernelEx::validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT) static
Static function to check if given info will lead to a valid configuration of CLPadLayerKernelEx
Parameters
[in] input Source tensor info. Data types supported: U8, S8, QASYMM8, QASYMM8_SIGNED, U16, S16, U32, S32, F16, F32.
[in] output Output tensor info. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 253 of file CLPadLayerKernelEx.cpp.
{
  unsigned int vec_size;
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, padding, constant_value, mode));
  ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                            output->clone().get(), padding,
                                                            constant_value, mode, vec_size)
                                .first);
  return Status{};
}
Referenced by arm_compute::CLPadLayerEx::validate(), and ~CLPadLayerKernelEx().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLPadLayerKernelEx.h
compute/ARMComputeEx/src/core/CL/kernels/CLPadLayerKernelEx.cpp