ONE - On-device Neural Engine: onert::backend::train::ExtraTensorIndex Class Reference
onert::backend::train::ExtraTensorIndex Class Reference
#include <ExtraTensorIndex.h>
Public Member Functions
ExtraTensorIndex (const ir::OperationIndex &op_index, uint32_t sub_index)
const ir::OperationIndex & op_index () const
uint32_t sub_index () const
bool operator== (const ExtraTensorIndex &other) const
bool operator!= (const ExtraTensorIndex &other) const
Detailed Description
Definition at line 31 of file ExtraTensorIndex.h.
Constructor & Destructor Documentation
ExtraTensorIndex()
onert::backend::train::ExtraTensorIndex::ExtraTensorIndex (const ir::OperationIndex & op_index, uint32_t sub_index) inline
Definition at line 34 of file ExtraTensorIndex.h.
    : _op_index{op_index}, _sub_index{sub_index}
  {
    assert(op_index.valid());
  }
References op_index(), and onert::util::Index< T, DummyTag >::valid().
Member Function Documentation
op_index()
const ir::OperationIndex & onert::backend::train::ExtraTensorIndex::op_index () const inline
Definition at line 41 of file ExtraTensorIndex.h.
{ return _op_index; }
Referenced by ExtraTensorIndex(), onert::backend::train::operator<<(), and operator==().
operator!=()
bool onert::backend::train::ExtraTensorIndex::operator!= (const ExtraTensorIndex & other) const inline
Definition at line 48 of file ExtraTensorIndex.h.
{ return !(*this == other); }
operator==()
bool onert::backend::train::ExtraTensorIndex::operator== (const ExtraTensorIndex & other) const inline
Definition at line 44 of file ExtraTensorIndex.h.
  {
    return _op_index == other.op_index() && _sub_index == other.sub_index();
  }
References op_index(), and sub_index().
sub_index()
uint32_t onert::backend::train::ExtraTensorIndex::sub_index () const inline
Definition at line 42 of file ExtraTensorIndex.h.
{ return _sub_index; }
Referenced by onert::backend::train::operator<<(), and operator==().
The documentation for this class was generated from the following file:
runtime/onert/backend/train/ExtraTensorIndex.h