ONE - On-device Neural Engine: luci::CloneNodeLet< CN::OPQR > Class Reference
luci::CloneNodeLet< CN::OPQR > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleOneHot *) final
luci::CircleNode * visit (const luci::CirclePack *) final
luci::CircleNode * visit (const luci::CirclePad *) final
luci::CircleNode * visit (const luci::CirclePadV2 *) final
luci::CircleNode * visit (const luci::CirclePow *) final
luci::CircleNode * visit (const luci::CirclePRelu *) final
luci::CircleNode * visit (const luci::CircleQuantize *) final
luci::CircleNode * visit (const luci::CircleRange *) final
luci::CircleNode * visit (const luci::CircleRank *) final
luci::CircleNode * visit (const luci::CircleReduceAny *) final
luci::CircleNode * visit (const luci::CircleReduceMax *) final
luci::CircleNode * visit (const luci::CircleReduceMin *) final
luci::CircleNode * visit (const luci::CircleReduceProd *) final
luci::CircleNode * visit (const luci::CircleRelu *) final
luci::CircleNode * visit (const luci::CircleRelu6 *) final
luci::CircleNode * visit (const luci::CircleReluN1To1 *) final
luci::CircleNode * visit (const luci::CircleReshape *) final
luci::CircleNode * visit (const luci::CircleResizeBilinear *) final
luci::CircleNode * visit (const luci::CircleResizeNearestNeighbor *) final
luci::CircleNode * visit (const luci::CircleReverseSequence *) final
luci::CircleNode * visit (const luci::CircleReverseV2 *) final
luci::CircleNode * visit (const luci::CircleRound *) final
luci::CircleNode * visit (const luci::CircleRsqrt *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 152 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::OPQR >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 155 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 182 of file CircleCloneNode.h.
{ return nullptr; }
visit() [2/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleOneHot * node) final
Definition at line 22 of file CircleOneHot.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleOneHot>();
  if (cloned != nullptr)
    cloned->axis(node->axis());
  return cloned;
}
References luci::CircleOneHot::axis().
visit() [3/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CirclePack * node) final
Definition at line 22 of file CirclePack.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CirclePack>(node->values_count());
  if (cloned != nullptr)
    cloned->axis(node->axis());
  return cloned;
}
References luci::CirclePack::axis(), and luci::CirclePack::values_count().
visit() [4/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CirclePad *) final
Definition at line 22 of file CirclePad.cpp.
{
  return _graph->nodes()->create<luci::CirclePad>();
}
visit() [5/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CirclePadV2 *) final
Definition at line 22 of file CirclePadV2.cpp.
{
  return _graph->nodes()->create<luci::CirclePadV2>();
}
visit() [6/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CirclePow *) final
Definition at line 22 of file CirclePow.cpp.
{
  return _graph->nodes()->create<luci::CirclePow>();
}
visit() [7/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CirclePRelu *) final
Definition at line 22 of file CirclePRelu.cpp.
{
  return _graph->nodes()->create<luci::CirclePRelu>();
}
visit() [8/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleQuantize *) final
Definition at line 22 of file CircleQuantize.cpp.
{
  return _graph->nodes()->create<luci::CircleQuantize>();
}
visit() [9/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRange *) final
Definition at line 22 of file CircleRange.cpp.
{
  return _graph->nodes()->create<luci::CircleRange>();
}
visit() [10/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRank *) final
Definition at line 22 of file CircleRank.cpp.
{
  return _graph->nodes()->create<luci::CircleRank>();
}
visit() [11/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReduceAny * node) final
Definition at line 22 of file CircleReduceAny.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReduceAny>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleReduceAny::keep_dims().
visit() [12/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReduceMax * node) final
Definition at line 22 of file CircleReduceMax.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReduceMax>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleReduceMax::keep_dims().
visit() [13/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReduceMin * node) final
Definition at line 22 of file CircleReduceMin.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReduceMin>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleReduceMin::keep_dims().
visit() [14/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReduceProd * node) final
Definition at line 22 of file CircleReduceProd.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReduceProd>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleReduceProd::keep_dims().
visit() [15/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRelu *) final
Definition at line 22 of file CircleRelu.cpp.
{
  return _graph->nodes()->create<luci::CircleRelu>();
}
visit() [16/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRelu6 *) final
Definition at line 22 of file CircleRelu6.cpp.
{
  return _graph->nodes()->create<luci::CircleRelu6>();
}
visit() [17/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReluN1To1 *) final
Definition at line 22 of file CircleReluN1To1.cpp.
{
  return _graph->nodes()->create<luci::CircleReluN1To1>();
}
visit() [18/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReshape * node) final
Definition at line 22 of file CircleReshape.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReshape>();
  if (cloned != nullptr)
  {
    uint32_t rank = node->newShape()->rank();
    cloned->newShape()->rank(rank);
    for (uint32_t r = 0; r < rank; ++r)
    {
      cloned->newShape()->dim(r) = node->newShape()->dim(r);
    }
  }
  return cloned;
}
References luci::CircleReshape::Shape::dim(), luci::CircleReshape::newShape(), and luci::CircleReshape::Shape::rank().
visit() [19/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleResizeBilinear * node) final
Definition at line 22 of file CircleResizeBilinear.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleResizeBilinear>();
  if (cloned != nullptr)
  {
    cloned->align_corners(node->align_corners());
    cloned->half_pixel_centers(node->half_pixel_centers());
  }
  return cloned;
}
References luci::CircleResizeBilinear::align_corners(), and luci::CircleResizeBilinear::half_pixel_centers().
visit() [20/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleResizeNearestNeighbor * node) final
Definition at line 22 of file CircleResizeNearestNeighbor.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleResizeNearestNeighbor>();
  if (cloned != nullptr)
    cloned->align_corners(node->align_corners());
  return cloned;
}
References luci::CircleResizeNearestNeighbor::align_corners().
visit() [21/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReverseSequence * node) final
Definition at line 22 of file CircleReverseSequence.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleReverseSequence>();
  if (cloned != nullptr)
  {
    cloned->seq_axis(node->seq_axis());
    cloned->batch_axis(node->batch_axis());
  }
  return cloned;
}
References luci::CircleReverseSequence::batch_axis(), and luci::CircleReverseSequence::seq_axis().
visit() [22/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleReverseV2 *) final
Definition at line 22 of file CircleReverseV2.cpp.
{
  return _graph->nodes()->create<luci::CircleReverseV2>();
}
visit() [23/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRound *) final
Definition at line 22 of file CircleRound.cpp.
{
  return _graph->nodes()->create<luci::CircleRound>();
}
visit() [24/24]
luci::CircleNode * luci::CloneNodeLet< CN::OPQR >::visit (const luci::CircleRsqrt *) final
Definition at line 22 of file CircleRsqrt.cpp.
{
  return _graph->nodes()->create<luci::CircleRsqrt>();
}
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::OPQR >::_graph = nullptr protected
Definition at line 185 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleOneHot.cpp
compiler/luci/service/src/Nodes/CirclePack.cpp
compiler/luci/service/src/Nodes/CirclePad.cpp
compiler/luci/service/src/Nodes/CirclePadV2.cpp
compiler/luci/service/src/Nodes/CirclePow.cpp
compiler/luci/service/src/Nodes/CirclePRelu.cpp
compiler/luci/service/src/Nodes/CircleQuantize.cpp
compiler/luci/service/src/Nodes/CircleRange.cpp
compiler/luci/service/src/Nodes/CircleRank.cpp
compiler/luci/service/src/Nodes/CircleReduceAny.cpp
compiler/luci/service/src/Nodes/CircleReduceMax.cpp
compiler/luci/service/src/Nodes/CircleReduceMin.cpp
compiler/luci/service/src/Nodes/CircleReduceProd.cpp
compiler/luci/service/src/Nodes/CircleRelu.cpp
compiler/luci/service/src/Nodes/CircleRelu6.cpp
compiler/luci/service/src/Nodes/CircleReluN1To1.cpp
compiler/luci/service/src/Nodes/CircleReshape.cpp
compiler/luci/service/src/Nodes/CircleResizeBilinear.cpp
compiler/luci/service/src/Nodes/CircleResizeNearestNeighbor.cpp
compiler/luci/service/src/Nodes/CircleReverseSequence.cpp
compiler/luci/service/src/Nodes/CircleReverseV2.cpp
compiler/luci/service/src/Nodes/CircleRound.cpp
compiler/luci/service/src/Nodes/CircleRsqrt.cpp