ONE - On-device Neural Engine: onert::backend::cpu::ops::BroadcastToLayer Class Reference
onert::backend::cpu::ops::BroadcastToLayer Class Reference
#include <BroadcastToLayer.h>
Public Member Functions
BroadcastToLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *shape, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 34 of file BroadcastToLayer.h.
Constructor & Destructor Documentation
BroadcastToLayer()
onert::backend::cpu::ops::BroadcastToLayer::BroadcastToLayer ()
Definition at line 30 of file BroadcastToLayer.cc.
                                   : _input(nullptr), _shape(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::BroadcastToLayer::configure (const IPortableTensor * input, const IPortableTensor * shape, IPortableTensor * output)
Definition at line 35 of file BroadcastToLayer.cc.
{
  _input = input;
  _shape = shape;
  _output = output;
}
run()
void onert::backend::cpu::ops::BroadcastToLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 43 of file BroadcastToLayer.cc.
{
  // NOTE : It was implemented follows tf.broadcast_to operation works and
  //        Api Document(https://www.tensorflow.org/api_docs/python/tf/broadcast_to)
  switch (_output->data_type())
  {
    // ToDo : It need to support INT8 and UINT8 also when will be applied quantization.
    case OperandType::FLOAT32:
      nnfw::cker::BroadcastTo<float>(getShape(_input), reinterpret_cast<float *>(_input->buffer()),
                                     getShape(_output), getBuffer<float>(_output));
      break;
    case OperandType::INT32:
      nnfw::cker::BroadcastTo<int32_t>(getShape(_input),
                                       reinterpret_cast<int32_t *>(_input->buffer()),
                                       getShape(_output), getBuffer<int32_t>(_output));
      break;
    case OperandType::UINT32:
      nnfw::cker::BroadcastTo<uint32_t>(getShape(_input),
                                        reinterpret_cast<uint32_t *>(_input->buffer()),
                                        getShape(_output), getBuffer<uint32_t>(_output));
      break;
    default:
      throw std::runtime_error{"BroadcastToLayer: unsupported data type"};
  }
}
References onert::backend::ITensor::buffer(), onert::backend::ITensor::data_type(), and onert::backend::cpu::ops::getShape().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/BroadcastToLayer.h
runtime/onert/backend/cpu/ops/BroadcastToLayer.cc