ONE - On-device Neural Engine: InstrBuilder Class Reference
InstrBuilder Class Reference
#include <IRBuilder.h>
Public Member Functions
InstrBuilder (coco::Module *module)
coco::Eval * eval (coco::Object *out, coco::Op *op) const
Create "Eval" instruction with a given "Object" and "Op".
InstrBuilder (coco::Module *module)
coco::Eval * eval (coco::Object *out, coco::Op *op) const
Create "Eval" instruction with a given "Object" and "Op".
coco::Copy * copy (coco::Object *into, coco::Object *from) const
Create "Copy" instruction with given two "Object".
Detailed Description
Definition at line 147 of file IRBuilder.h.
Constructor & Destructor Documentation
InstrBuilder() [1/2]
InstrBuilder::InstrBuilder (coco::Module * module) inline
Definition at line 150 of file IRBuilder.h.
                                   : _module{module}
  {
    // NOTE _module SHOULD be valid
    assert(_module != nullptr);
  }
InstrBuilder() [2/2]
InstrBuilder::InstrBuilder (coco::Module * module) inline
Definition at line 136 of file IRBuilder.h.
                                   : _module{module}
  {
    // NOTE _module SHOULD be valid
    assert(_module != nullptr);
  }
Member Function Documentation
copy()
coco::Copy * InstrBuilder::copy (coco::Object * into, coco::Object * from) const inline
Create "Copy" instruction with given two "Object".
Note
"copy(into, from)" will create "%into <- Copy(%from)" instruction
Definition at line 161 of file IRBuilder.h.
  {
    auto ins = _module->entity()->instr()->create<coco::Copy>();
    ins->from(from);
    ins->into(into);
    return ins;
  }
References coco::InstrManager::create(), coco::Module::entity(), coco::Copy::from(), and coco::EntityManager::instr().
Referenced by tflimport::ConcatenationGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::build_activation().
eval() [1/2]
coco::Eval * InstrBuilder::eval (coco::Object * out, coco::Op * op) const inline
Create "Eval" instruction with a given "Object" and "Op".
Note
"eval(out, op)" will create "%out <- Eval(op)" instruction
Definition at line 162 of file IRBuilder.h.
  {
    auto ins = _module->entity()->instr()->create<coco::Eval>();
    ins->op(op);
    ins->out(out);
    return ins;
  }
References coco::InstrManager::create(), coco::Module::entity(), coco::EntityManager::instr(), and coco::Eval::op().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::build_activation().
eval() [2/2]
coco::Eval * InstrBuilder::eval (coco::Object * out, coco::Op * op) const inline
Create "Eval" instruction with a given "Object" and "Op".
Note
"eval(out, op)" will create "%out <- Eval(op)" instruction
Definition at line 148 of file IRBuilder.h.
  {
    auto ins = _module->entity()->instr()->create<coco::Eval>();
    ins->op(op);
    ins->out(out);
    return ins;
  }
References coco::InstrManager::create(), coco::Module::entity(), coco::EntityManager::instr(), and coco::Eval::op().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/IRBuilder.h
compiler/enco/frontend/tflite/src/IRBuilder.h