ONE - On-device Neural Engine: luci::CircleAddN Class Reference
luci::CircleAddN Class Reference final
ADD_N in Circle.
#include <CircleAddN.h>
Public Member Functions
CircleAddN (uint32_t arity)
Node * inputs (uint32_t index) const
void inputs (uint32_t index, Node *node)
Public Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::ADD_N >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >
loco::Use * at (uint32_t n) const
Detailed Description
ADD_N in Circle.
Definition at line 31 of file CircleAddN.h.
Constructor & Destructor Documentation
CircleAddN()
luci::CircleAddN::CircleAddN (uint32_t arity) inline
Definition at line 34 of file CircleAddN.h.
                             : VariadicArityNode<CircleNodeImpl<CircleOpcode::ADD_N>>(arity)
  {
    assert(arity >= 1);
  }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >::arity().
Member Function Documentation
inputs() [1/2]
Node * luci::CircleAddN::inputs (uint32_t index) const inline
Definition at line 40 of file CircleAddN.h.
{ return at(index)->node(); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >::at(), and loco::Use::node().
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
inputs() [2/2]
void luci::CircleAddN::inputs (uint32_t index, Node * node) inline
Definition at line 41 of file CircleAddN.h.
{ at(index)->node(node); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::ADD_N > >::at(), and loco::Use::node().
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleAddN.h