ONE - On-device Neural Engine: mir_interpreter::MIRInterpreter Class Reference
mir_interpreter::MIRInterpreter Class Reference
#include <MirInterpreter.h>
Public Member Functions
MIRInterpreter ()=default
~MIRInterpreter () override=default
void setTensor (const mir::Operation::Output *output, mir::TensorVariant tensor)
Set tensor to the interpreter environment.
const mir::TensorVariant & getTensor (const mir::Operation::Output *) const
Get tensor from the interpreter environment.
void visit (mir::ops::AddOp &op) override
void visit (mir::ops::AbsOp &op) override
void visit (mir::ops::AvgPool2DOp &op) override
void visit (mir::ops::CappedReluOp &op) override
void visit (mir::ops::ConcatOp &op) override
void visit (mir::ops::ConstantOp &op) override
void visit (mir::ops::Conv2DOp &op) override
void visit (mir::ops::DeConv2DOp &op) override
void visit (mir::ops::DepthwiseConv2DOp &op) override
void visit (mir::ops::DequantizeOp &op) override
void visit (mir::ops::DivOp &op) override
void visit (mir::ops::EluOp &op) override
void visit (mir::ops::EqualOp &op) override
void visit (mir::ops::FullyConnectedOp &op) override
void visit (mir::ops::GatherOp &op) override
void visit (mir::ops::GreaterOp &op) override
void visit (mir::ops::HardSwishOp &op) override
void visit (mir::ops::InputOp &op) override
void visit (mir::ops::LeakyReluOp &op) override
void visit (mir::ops::LessOp &op) override
void visit (mir::ops::MaxOp &op) override
void visit (mir::ops::MaxPool2DOp &op) override
void visit (mir::ops::MulOp &op) override
void visit (mir::ops::OutputOp &op) override
void visit (mir::ops::PadOp &op) override
void visit (mir::ops::QuantizeOp &op) override
void visit (mir::ops::ReduceMeanOp &op) override
void visit (mir::ops::ReluOp &op) override
void visit (mir::ops::ReshapeOp &op) override
void visit (mir::ops::ResizeOp &op) override
void visit (mir::ops::SigmoidOp &op) override
void visit (mir::ops::SliceOp &op) override
void visit (mir::ops::SoftmaxOp &op) override
void visit (mir::ops::SqrtOp &op) override
void visit (mir::ops::SqueezeOp &op) override
void visit (mir::ops::SubOp &op) override
void visit (mir::ops::TanhOp &op) override
void visit (mir::ops::TransposeOp &op) override
void visit (mir::ops::BroadcastOp &op) override
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Protected Member Functions
void visit_fallback (mir::Operation &op) override
virtual void visit_fallback (Operation &)
Detailed Description
Definition at line 29 of file MirInterpreter.h.
Constructor & Destructor Documentation
MIRInterpreter()
mir_interpreter::MIRInterpreter::MIRInterpreter () explicit default
~MIRInterpreter()
mir_interpreter::MIRInterpreter::~MIRInterpreter () override default
Member Function Documentation
getTensor()
const TensorVariant & mir_interpreter::MIRInterpreter::getTensor (const mir::Operation::Output *) const
Get tensor from the interpreter environment.
Definition at line 88 of file MirInterpreter.cpp.
{
  const auto it = _tensors.find(output);
  if (it == _tensors.end())
  {
    const std::string &name = output->getName();
    throw std::runtime_error("Can't find data for tensor \"" + name + "\".");
  }
  return it->second;
}
setTensor()
void mir_interpreter::MIRInterpreter::setTensor (const mir::Operation::Output * output, mir::TensorVariant tensor)
Set tensor to the interpreter environment.
Definition at line 67 of file MirInterpreter.cpp.
{
  const auto result = _tensors.emplace(output, std::move(tensor));
  if (!result.second)
  {
    const std::string &name = output->getName();
    throw std::runtime_error("Attempt to overwrite data for tensor \"" + name + "\".");
  }
}
Referenced by visit().
visit() [1/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::AbsOp & op) override
Definition at line 404 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Abs(inputs[0], outputs[0]);
}
References mir_interpreter::Abs().
visit() [2/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::AddOp & op) override
Definition at line 327 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Add(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Add().
visit() [3/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::AvgPool2DOp & op) override
Definition at line 126 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  AvgPool2D(op, inputs[0], outputs[0]);
}
References AvgPool2D.
visit() [4/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::BroadcastOp & op) override
Definition at line 411 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  outputs[0].get() = TensorVariant{inputs[0], op.getOutputShape(0)};
}
References mir::Operation::getOutputShape().
visit() [5/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::CappedReluOp & op) override
Definition at line 202 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  CappedReLU(args[0], op.getCap(), results[0]);
}
References mir_interpreter::CappedReLU(), and mir::ops::CappedReluOp::getCap().
visit() [6/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ConcatOp & op) override
Definition at line 135 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Concat(inputs, op.getAxis(), outputs[0]);
}
References mir_interpreter::Concat(), and mir::ops::ConcatOp::getAxis().
visit() [7/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ConstantOp & op) override
Definition at line 133 of file MirInterpreter.cpp.
{ setTensor(op.getOutput(0), op.getValue()); }
References mir::Operation::getOutput(), mir::ops::ConstantOp::getValue(), and setTensor().
visit() [8/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::Conv2DOp & op) override
Definition at line 142 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  const mir::TensorVariant *bias = nullptr;
  if (inputs.size() > 2)
  {
    bias = &(inputs[2].get());
  }
  Conv2D(inputs[0], inputs[1], op.getAttributes(), outputs[0], bias);
}
References mir_interpreter::Conv2D(), and mir::ops::Conv2DOp::getAttributes().
visit() [9/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::DeConv2DOp & op) override
Definition at line 236 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  DeConv2D(inputs[0], inputs[1], op.getAttributes(), outputs[0]);
}
References mir_interpreter::DeConv2D(), and mir::ops::DeConv2DOp::getAttributes().
visit() [10/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::DepthwiseConv2DOp & op) override
Definition at line 209 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  const mir::TensorVariant *bias = nullptr;
  if (inputs.size() > 2)
  {
    bias = &inputs[3].get();
  }
  DepthwiseConv2D(op, inputs[0], inputs[1], outputs[0], bias);
}
References DepthwiseConv2D.
visit() [11/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::DequantizeOp & op) override
Definition at line 362 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Dequantize(inputs[0], outputs[0]);
}
References mir_interpreter::Dequantize().
visit() [12/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::DivOp & op) override
Definition at line 334 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Div(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Div().
visit() [13/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::EluOp & op) override
Definition at line 243 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  ELU(args[0], op.getAlpha(), results[0]);
}
References mir_interpreter::ELU(), and mir::ops::EluOp::getAlpha().
visit() [14/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::EqualOp & op) override
Definition at line 397 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Equal(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Equal().
visit() [15/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::FullyConnectedOp & op) override
Definition at line 190 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  const mir::TensorVariant *bias = nullptr;
  if (inputs.size() > 2)
  {
    bias = &(inputs[3].get());
  }
  FullyConnected(inputs[0], inputs[1], op, outputs[0], bias);
}
References mir_interpreter::FullyConnected().
visit() [16/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::GatherOp & op) override
Definition at line 308 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Gather(inputs[0], inputs[1], op, outputs[0]);
}
References mir_interpreter::Gather().
visit() [17/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::GreaterOp & op) override
Definition at line 383 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Greater(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Greater().
visit() [18/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::HardSwishOp & op) override
Definition at line 376 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  HardSwish(inputs[0], outputs[0]);
}
References mir_interpreter::HardSwish().
visit() [19/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::InputOp & op) override
Definition at line 121 of file MirInterpreter.cpp.
{
  assert(_tensors.find(op.getOutput(0)) != _tensors.end());
}
References mir::Operation::getOutput().
visit() [20/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::LeakyReluOp & op) override
Definition at line 315 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  LeakyReLU(args[0], op.getAlpha(), results[0]);
}
References mir::ops::LeakyReluOp::getAlpha(), and mir_interpreter::LeakyReLU().
visit() [21/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::LessOp & op) override
Definition at line 390 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Less(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Less().
visit() [22/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::MaxOp & op) override
Definition at line 341 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Max(inputs[0], inputs[1], outputs[0]);
}
References Max.
visit() [23/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::MaxPool2DOp & op) override
Definition at line 154 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  MaxPool2D(inputs[0], op, outputs[0]);
}
References MaxPool2D.
visit() [24/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::MulOp & op) override
Definition at line 348 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Mul(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Mul().
visit() [25/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::OutputOp & op) override
Definition at line 322 of file MirInterpreter.cpp.
{
  assert(_tensors.find(op.getInput(0)) != _tensors.end());
}
References mir::Operation::getInput().
visit() [26/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::PadOp & op) override
Definition at line 258 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Pad(inputs[0], op, outputs[0]);
}
References mir_interpreter::Pad().
visit() [27/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::QuantizeOp & op) override
Definition at line 369 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Quantize(inputs[0], outputs[0]);
}
References mir_interpreter::Quantize().
visit() [28/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ReduceMeanOp & op) override
Definition at line 294 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  ReduceMean(inputs[0], op, outputs[0]);
}
References mir_interpreter::ReduceMean().
visit() [29/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ReluOp & op) override
Definition at line 168 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  ReLU(args[0], results[0]);
}
References mir_interpreter::ReLU().
visit() [30/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ReshapeOp & op) override
Definition at line 161 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Reshape(inputs[0], outputs[0]);
}
References mir_interpreter::Reshape().
visit() [31/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::ResizeOp & op) override
Definition at line 272 of file MirInterpreter.cpp.
{
  // TODO support types other than float32
  auto inputs = getInputTensors(op);
  assert(inputs[0].get().getElementType() == mir::DataType::FLOAT32);
  auto outputs = allocateOutputTensors(op);
  Tensor<float> input(inputs[0]);
  assert(op.getMode() == ops::ResizeOp::ResizeMethod::nearestNeighbor);
  auto scales = op.getScales();
  Fill(outputs[0], [&scales, &input](const Index &id) {
    Index in_idx;
    in_idx.resize(4);
    for (int i = 0; i < input.getShape().rank(); i++)
    {
      in_idx.at(i) = static_cast<int>(floorf(id.at(i) / scales[i]));
    }
    return input.at(in_idx);
  });
}
References mir::Index::at(), mir_interpreter::Fill(), mir::ops::ResizeOp::getMode(), mir::ops::ResizeOp::getScales(), and mir::Index::resize().
visit() [32/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SigmoidOp & op) override
Definition at line 175 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  Sigmoid(args[0], results[0]);
}
References mir_interpreter::Sigmoid().
visit() [33/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SliceOp & op) override
Definition at line 221 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto input = inputs[0];
  auto outputs = allocateOutputTensors(op);
  Slice(input, op.getStarts(), outputs[0]);
}
References mir::ops::SliceOp::getStarts(), and mir_interpreter::Slice().
visit() [34/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SoftmaxOp & op) override
Definition at line 182 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  assert(inputs.size() == 1);
  auto outputs = allocateOutputTensors(op);
  Softmax(inputs[0], op.getAxis(), outputs[0]);
}
References mir::ops::SoftmaxOp::getAxis(), and mir_interpreter::Softmax().
visit() [35/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SqrtOp & op) override
Definition at line 265 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  Sqrt(args[0], results[0]);
}
References mir_interpreter::Sqrt().
visit() [36/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SqueezeOp & op) override
Definition at line 250 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  // Squeeze is just a special case of reshape.
  Reshape(inputs[0], outputs[0]);
}
References mir_interpreter::Reshape().
visit() [37/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::SubOp & op) override
Definition at line 355 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Sub(inputs[0], inputs[1], outputs[0]);
}
References mir_interpreter::Sub().
visit() [38/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::TanhOp & op) override
Definition at line 229 of file MirInterpreter.cpp.
{
  auto args = getInputTensors(op);
  auto results = allocateOutputTensors(op);
  Tanh(args[0], results[0]);
}
References mir_interpreter::Tanh().
visit() [39/39]
void mir_interpreter::MIRInterpreter::visit (mir::ops::TransposeOp & op) override
Definition at line 301 of file MirInterpreter.cpp.
{
  auto inputs = getInputTensors(op);
  auto outputs = allocateOutputTensors(op);
  Transpose(inputs[0], op, outputs[0]);
}
References mir_interpreter::Transpose().
visit_fallback()
void mir_interpreter::MIRInterpreter::visit_fallback (mir::Operation & op) override protected virtual
Reimplemented from mir::Visitor.
Definition at line 418 of file MirInterpreter.cpp.
{ throw std::runtime_error("NYI operation"); }
The documentation for this class was generated from the following files:
compiler/mir-interpreter/include/MirInterpreter.h
compiler/mir-interpreter/src/MirInterpreter.cpp