ONE - On-device Neural Engine: loco::Padding2D Class Reference
loco::Padding2D Class Reference final
#include <Padding2D.h>
Public Member Functions
Padding2D ()
Padding2D (uint32_t top, uint32_t bottom, uint32_t left, uint32_t right)
uint32_t top (void) const
void top (uint32_t value)
uint32_t bottom (void) const
void bottom (uint32_t value)
uint32_t left (void) const
void left (uint32_t value)
uint32_t right (void) const
void right (uint32_t value)
Detailed Description
Definition at line 25 of file Padding2D.h.
Constructor & Destructor Documentation
Padding2D() [1/2]
loco::Padding2D::Padding2D () inline
Definition at line 28 of file Padding2D.h.
              : _top{0}, _bottom{0}, _left{0}, _right{0}
  {
    // DO NOTHING
  }
Padding2D() [2/2]
loco::Padding2D::Padding2D (uint32_t top, uint32_t bottom, uint32_t left, uint32_t right) inline
Definition at line 34 of file Padding2D.h.
    : _top{top}, _bottom{bottom}, _left{left}, _right{right}
  {
    // DO NOTHING
  }
Member Function Documentation
bottom() [1/2]
void loco::Padding2D::bottom (uint32_t value) inline
Definition at line 46 of file Padding2D.h.
{ _bottom = value; }
bottom() [2/2]
uint32_t loco::Padding2D::bottom (void) const inline
Definition at line 45 of file Padding2D.h.
{ return _bottom; }
Referenced by exo::circle_detail::getOpPadding(), exo::tflite_detail::getOpPadding(), luci::getOpPadding(), moco::Padding2DInference::operator()(), and loco::operator<<().
left() [1/2]
void loco::Padding2D::left (uint32_t value) inline
Definition at line 50 of file Padding2D.h.
{ _left = value; }
left() [2/2]
uint32_t loco::Padding2D::left (void) const inline
Definition at line 49 of file Padding2D.h.
{ return _left; }
Referenced by exo::circle_detail::getOpPadding(), exo::tflite_detail::getOpPadding(), luci::getOpPadding(), moco::Padding2DInference::operator()(), and loco::operator<<().
right() [1/2]
void loco::Padding2D::right (uint32_t value) inline
Definition at line 54 of file Padding2D.h.
{ _right = value; }
right() [2/2]
uint32_t loco::Padding2D::right (void) const inline
Definition at line 53 of file Padding2D.h.
{ return _right; }
Referenced by exo::circle_detail::getOpPadding(), exo::tflite_detail::getOpPadding(), luci::getOpPadding(), moco::Padding2DInference::operator()(), and loco::operator<<().
top() [1/2]
void loco::Padding2D::top (uint32_t value) inline
Definition at line 42 of file Padding2D.h.
{ _top = value; }
top() [2/2]
uint32_t loco::Padding2D::top (void) const inline
Definition at line 41 of file Padding2D.h.
{ return _top; }
Referenced by exo::circle_detail::getOpPadding(), exo::tflite_detail::getOpPadding(), luci::getOpPadding(), moco::Padding2DInference::operator()(), and loco::operator<<().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Padding2D.h