ONE - On-device Neural Engine: luci::CircleDialect Class Reference
luci::CircleDialect Class Reference final
A singleton for Circle Dialect.
#include <CircleDialect.h>
Public Member Functions
CircleDialect (const CircleDialect &)=delete
CircleDialect (CircleDialect &&)=delete
Public Member Functions inherited from loco::Dialect
virtual ~Dialect ()=default
template<typename ConcreteService >
ConcreteService * service (void) const
Static Public Member Functions
static loco::Dialect * get (void)
Additional Inherited Members
Protected Member Functions inherited from loco::Dialect
template<typename ConcreteService >
void service (std::unique_ptr< ConcreteService > &&s)
Detailed Description
A singleton for Circle Dialect.
Definition at line 28 of file CircleDialect.h.
Constructor & Destructor Documentation
CircleDialect() [1/2]
luci::CircleDialect::CircleDialect (const CircleDialect &) delete
CircleDialect() [2/2]
luci::CircleDialect::CircleDialect (CircleDialect &&) delete
Member Function Documentation
get()
loco::Dialect * luci::CircleDialect::get (void) static
Definition at line 82 of file CircleDialect.cpp.
{
  static CircleDialect d;
  return &d;
}
Referenced by luci::CircleNodeSummaryBuilder::build(), luci::CircleNode::dialect(), luci::CircleTypeInferenceRule::infer(), luci::CircleShapeInferenceRule::infer(), luci::CircleShapeInferenceRule::recognize(), and luci::CircleTypeInferenceRule::recognize().
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/CircleDialect.h
compiler/luci/lang/src/CircleDialect.cpp