ONE - On-device Neural Engine: luci::CircleLocalResponseNormalization Class Reference
luci::CircleLocalResponseNormalization Class Reference final
LOCAL_RESPONSE_NORMALIZATION in Circle.
#include <CircleLocalResponseNormalization.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
int32_t radius (void) const
void radius (int32_t radius)
float bias (void) const
void bias (float bias)
float alpha (void) const
void alpha (float alpha)
float beta (void) const
void beta (float beta)
Public Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >
loco::Use * at (uint32_t n) const
Detailed Description
LOCAL_RESPONSE_NORMALIZATION in Circle.
Definition at line 31 of file CircleLocalResponseNormalization.h.
Member Function Documentation
alpha() [1/2]
void luci::CircleLocalResponseNormalization::alpha (float alpha) inline
Definition at line 46 of file CircleLocalResponseNormalization.h.
{ _alpha = alpha; }
References alpha().
Referenced by alpha().
alpha() [2/2]
float luci::CircleLocalResponseNormalization::alpha (void) const inline
Definition at line 45 of file CircleLocalResponseNormalization.h.
{ return _alpha; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
beta() [1/2]
void luci::CircleLocalResponseNormalization::beta (float beta) inline
Definition at line 49 of file CircleLocalResponseNormalization.h.
{ _beta = beta; }
References beta().
Referenced by beta().
beta() [2/2]
float luci::CircleLocalResponseNormalization::beta (void) const inline
Definition at line 48 of file CircleLocalResponseNormalization.h.
{ return _beta; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
bias() [1/2]
void luci::CircleLocalResponseNormalization::bias (float bias) inline
Definition at line 43 of file CircleLocalResponseNormalization.h.
{ _bias = bias; }
References bias().
Referenced by bias().
bias() [2/2]
float luci::CircleLocalResponseNormalization::bias (void) const inline
Definition at line 42 of file CircleLocalResponseNormalization.h.
{ return _bias; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
input() [1/2]
void luci::CircleLocalResponseNormalization::input (loco::Node * node) inline
Definition at line 36 of file CircleLocalResponseNormalization.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleLocalResponseNormalization::input (void) const inline
Definition at line 35 of file CircleLocalResponseNormalization.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION > >::at(), and loco::Use::node().
radius() [1/2]
void luci::CircleLocalResponseNormalization::radius (int32_t radius) inline
Definition at line 40 of file CircleLocalResponseNormalization.h.
{ _radius = radius; }
References radius().
Referenced by radius().
radius() [2/2]
int32_t luci::CircleLocalResponseNormalization::radius (void) const inline
Definition at line 39 of file CircleLocalResponseNormalization.h.
{ return _radius; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleLocalResponseNormalization.h