ONE - On-device Neural Engine: nnsuite::conv::RandomModel Class Reference
nnsuite::conv::RandomModel Class Reference final
#include <RandomModel.h>
Public Member Functions
RandomModel (int32_t seed)
const nncc::core::ADT::feature::Shape & ifm_shape (void) const override
const std::string & ifm_name (void) const override
const nncc::core::ADT::feature::Shape & ofm_shape (void) const override
const std::string & ofm_name (void) const override
const nncc::core::ADT::kernel::Shape & ker_shape (void) const override
const nncc::core::ADT::kernel::Reader< float > & ker_data (void) const override
Public Member Functions inherited from nnsuite::conv::Model
virtual ~Model ()=default
virtual const nncc::core::ADT::feature::Shape & ifm_shape (void) const =0
virtual const std::string & ifm_name (void) const =0
virtual const nncc::core::ADT::feature::Shape & ofm_shape (void) const =0
virtual const std::string & ofm_name (void) const =0
virtual const nncc::core::ADT::kernel::Shape & ker_shape (void) const =0
virtual const nncc::core::ADT::kernel::Reader< float > & ker_data (void) const =0
Detailed Description
Definition at line 31 of file RandomModel.h.
Constructor & Destructor Documentation
RandomModel()
nnsuite::conv::RandomModel::RandomModel (int32_t seed) explicit
Definition at line 30 of file RandomModel.cpp.
  : _ifm_shape{1, 8, 8}, _ifm_name{"ifm"}, _ofm_name{"ofm"}, _ofm_shape{2, 6, 6},
    _ker_buffer{kernel::Shape{2, 1, 3, 3}, kernel::NCHWLayout{}}
{
  std::default_random_engine gen{static_cast<uint32_t>(seed)};
  std::normal_distribution<float> dist{0.0f, 1.0f};
  const uint32_t N = _ker_buffer.shape().count();
  const uint32_t C = _ker_buffer.shape().depth();
  const uint32_t H = _ker_buffer.shape().height();
  const uint32_t W = _ker_buffer.shape().width();
  for (uint32_t n = 0; n < N; ++n)
  {
    for (uint32_t ch = 0; ch < C; ++ch)
    {
      for (uint32_t row = 0; row < H; ++row)
      {
        for (uint32_t col = 0; col < W; ++col)
        {
          _ker_buffer.at(n, ch, row, col) = dist(gen);
        }
      }
    }
  }
}
References nncc::core::ADT::kernel::Buffer< T >::at(), nncc::core::ADT::kernel::Shape::count(), nncc::core::ADT::kernel::Shape::depth(), nncc::core::ADT::kernel::Shape::height(), nncc::core::ADT::kernel::Buffer< T >::shape(), and nncc::core::ADT::kernel::Shape::width().
Member Function Documentation
ifm_name()
const std::string & nnsuite::conv::RandomModel::ifm_name (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 38 of file RandomModel.h.
{ return _ifm_name; }
ifm_shape()
const nncc::core::ADT::feature::Shape & nnsuite::conv::RandomModel::ifm_shape (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 37 of file RandomModel.h.
{ return _ifm_shape; }
ker_data()
const nncc::core::ADT::kernel::Reader< float > & nnsuite::conv::RandomModel::ker_data (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 50 of file RandomModel.h.
  {
    return _ker_buffer;
  }
ker_shape()
const nncc::core::ADT::kernel::Shape & nnsuite::conv::RandomModel::ker_shape (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 45 of file RandomModel.h.
  {
    return _ker_buffer.shape();
  }
References nncc::core::ADT::kernel::Buffer< T >::shape().
ofm_name()
const std::string & nnsuite::conv::RandomModel::ofm_name (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 42 of file RandomModel.h.
{ return _ofm_name; }
ofm_shape()
const nncc::core::ADT::feature::Shape & nnsuite::conv::RandomModel::ofm_shape (void) const inline override virtual
Implements nnsuite::conv::Model.
Definition at line 41 of file RandomModel.h.
{ return _ofm_shape; }
The documentation for this class was generated from the following files:
compiler/nnsuite/conv/model/include/nnsuite/conv/RandomModel.h
compiler/nnsuite/conv/model/src/RandomModel.cpp