ONE - On-device Neural Engine: loco::AvgPool2D Class Reference
loco::AvgPool2D Class Reference final
2D Average Pooling
#include <Nodes.h>
Public Types
enum class Convention { Unknown , Full , Valid }
Public Member Functions
Node * ifm (void) const
void ifm (Node *node)
Convention convention (void) const
void convention (const Convention &convention)
const Padding2D * pad (void) const
Padding2D * pad (void)
const Window< 2 > * window (void) const
Window< 2 > * window (void)
const Stride< 2 > * stride (void) const
Stride< 2 > * stride (void)
Public Member Functions inherited from loco::CanonicalNodeDef< CanonicalOpcode::AvgPool2D, FixedArity< 1 >::Mixin >
virtual ~CanonicalNodeDef ()=default
uint32_t opnum (void) const final
CanonicalOpcode opcode (void) const final
Public Member Functions inherited from loco::CanonicalNode
virtual ~CanonicalNode ()=default
const Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CanonicalOpcode opcode (void) const =0
template<typename T >
T accept (CanonicalNodeVisitorBase< T > *) const
template<typename T >
T accept (CanonicalNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
2D Average Pooling
Note
Follows MaxPool2D (TODO: describe difference)
Definition at line 336 of file Nodes.h.
Member Enumeration Documentation
Convention
enum class loco::AvgPool2D::Convention strong
Enumerator
Unknown
Full
Valid
Definition at line 339 of file Nodes.h.
  {
    Unknown,
    // Use the number of elements in each receptive field as a divisor
    Full,
    // Use the number of valid (non-padding) elements in each receptive field as a divisor
    Valid
  };
Member Function Documentation
convention() [1/2]
void loco::AvgPool2D::convention (const Convention & convention) inline
Definition at line 354 of file Nodes.h.
{ _convention = convention; }
References convention().
Referenced by convention().
convention() [2/2]
Convention loco::AvgPool2D::convention (void) const inline
Definition at line 353 of file Nodes.h.
{ return _convention; }
ifm() [1/2]
void loco::AvgPool2D::ifm (Node * node) inline
Definition at line 350 of file Nodes.h.
{ at(0)->node(node); }
ifm() [2/2]
Node * loco::AvgPool2D::ifm (void) const inline
Definition at line 349 of file Nodes.h.
{ return at(0)->node(); }
Referenced by exo::AvgPool2DConverter::convert(), GraphTestcase< GraphCode::AvgPool2D >::GraphTestcase(), and mir2loco::Transformer::visit().
pad() [1/2]
Padding2D * loco::AvgPool2D::pad (void) inline
Definition at line 358 of file Nodes.h.
{ return &_pad; }
pad() [2/2]
const Padding2D * loco::AvgPool2D::pad (void) const inline
Definition at line 357 of file Nodes.h.
{ return &_pad; }
Referenced by exo::AvgPool2DConverter::convert().
stride() [1/2]
Stride< 2 > * loco::AvgPool2D::stride (void) inline
Definition at line 366 of file Nodes.h.
{ return &_stride; }
stride() [2/2]
const Stride< 2 > * loco::AvgPool2D::stride (void) const inline
Definition at line 365 of file Nodes.h.
{ return &_stride; }
Referenced by exo::AvgPool2DConverter::convert().
window() [1/2]
Window< 2 > * loco::AvgPool2D::window (void) inline
Definition at line 362 of file Nodes.h.
{ return &_window; }
window() [2/2]
const Window< 2 > * loco::AvgPool2D::window (void) const inline
Definition at line 361 of file Nodes.h.
{ return &_window; }
Referenced by exo::AvgPool2DConverter::convert().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Nodes.h