ONE - On-device Neural Engine: circle_eval_diff::TopKMatchPrinter Class Reference
circle_eval_diff::TopKMatchPrinter Class Reference
#include <MetricPrinter.h>
Public Member Functions
TopKMatchPrinter (uint32_t k)
void init (const luci::Module *first, const luci::Module *second)
void accumulate (const std::vector< std::shared_ptr< Tensor > > &first, const std::vector< std::shared_ptr< Tensor > > &second)
void dump (std::ostream &os) const
Public Member Functions inherited from circle_eval_diff::MetricPrinter
virtual ~MetricPrinter ()=default
virtual void init (const luci::Module *, const luci::Module *)
virtual void accumulate (const std::vector< std::shared_ptr< Tensor > > &first, const std::vector< std::shared_ptr< Tensor > > &second)=0
virtual void dump (std::ostream &os) const =0
Detailed Description
Definition at line 185 of file MetricPrinter.h.
Constructor & Destructor Documentation
TopKMatchPrinter()
circle_eval_diff::TopKMatchPrinter::TopKMatchPrinter (uint32_t k) inline
Definition at line 188 of file MetricPrinter.h.
: _k(k) {}
Member Function Documentation
accumulate()
void circle_eval_diff::TopKMatchPrinter::accumulate (const std::vector< std::shared_ptr< Tensor > > & first, const std::vector< std::shared_ptr< Tensor > > & second) virtual
Implements circle_eval_diff::MetricPrinter.
Definition at line 520 of file MetricPrinter.cpp.
{
  assert(first.size() == second.size());        // FIX_CALLER_UNLESS
  assert(first.size() == _intermediate.size()); // FIX_CALLER_UNLESS
  for (uint32_t output_idx = 0; output_idx < _intermediate.size(); output_idx++)
  {
    if (in_skip_list(output_idx))
      continue;
    const auto first_output = first[output_idx];
    const auto second_output = second[output_idx];
    // Cast data to fp32 for ease of computation
    const auto fp32_first_output = fp32(first_output);
    const auto fp32_second_output = fp32(second_output);
    accum_topk_accuracy(output_idx, fp32_first_output, fp32_second_output);
  }
  _num_data++;
}
dump()
void circle_eval_diff::TopKMatchPrinter::dump (std::ostream & os) const virtual
Implements circle_eval_diff::MetricPrinter.
Definition at line 544 of file MetricPrinter.cpp.
{
  os << "Ratio of Matched Indices between Top-" << _k << " results of the models" << std::endl;
  for (uint32_t output_idx = 0; output_idx < _intermediate.size(); output_idx++)
  {
    if (in_skip_list(output_idx))
      continue;
    const auto name = _output_names.at(output_idx);
    const auto sum_of_topk_accuracy = _intermediate.at(output_idx);
    // Compute TopKMatch
    float mean_topk = sum_of_topk_accuracy / _num_data;
    os << "Mean Top-" << _k << " match ratio for " << name << " is " << mean_topk << std::endl;
  }
}
init()
void circle_eval_diff::TopKMatchPrinter::init (const luci::Module * first, const luci::Module * second) virtual
Reimplemented from circle_eval_diff::MetricPrinter.
Definition at line 404 of file MetricPrinter.cpp.
{
  THROW_UNLESS(first != nullptr, "Invalid module.");
  THROW_UNLESS(second != nullptr, "Invalid module.");
  const auto first_output = loco::output_nodes(first->graph());
  const auto second_output = loco::output_nodes(second->graph());
  assert(first_output.size() == second_output.size()); // FIX_CALLER_UNLESS
  for (uint32_t i = 0; i < first_output.size(); i++)
  {
    const auto first_node = loco::must_cast<luci::CircleOutput *>(first_output[i]);
    const auto second_node = loco::must_cast<luci::CircleOutput *>(second_output[i]);
    // Create places to store intermediate results
    _intermediate.emplace_back(0.0);
    // Save output names for logging
    _output_names.emplace_back(first_node->name());
    // If num_elems of an output is less than k,
    // the output index is added to the skip list
    if (num_elems(first_node) < _k)
    {
      std::cout << "Top-" << _k << "metric for " << first_node->name()
                << " is ignored, because it has elements less than " << _k << std::endl;
      _skip_output.emplace_back(i);
    }
  }
}
References luci::Module::graph(), num_elems(), loco::output_nodes(), and THROW_UNLESS.
The documentation for this class was generated from the following files:
compiler/circle-eval-diff/src/MetricPrinter.h
compiler/circle-eval-diff/src/MetricPrinter.cpp