ONE - On-device Neural Engine: luci_interpreter::kernels::While Class Reference
luci_interpreter::kernels::While Class Reference
#include <While.h>
Public Member Functions
While (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, RuntimeGraph *cond_graph, RuntimeGraph *body_graph)
const Tensor * input (int index) const
Tensor * output (int index) const
void configure () override
void execute () const override
While (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, RuntimeGraph *cond_graph, RuntimeGraph *body_graph)
const Tensor * input (int index) const
Tensor * output (int index) const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file While.h.
Constructor & Destructor Documentation
While() [1/2]
luci_interpreter::kernels::While::While (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, RuntimeGraph * cond_graph, RuntimeGraph * body_graph)
Definition at line 61 of file While.cpp.
  : Kernel(std::move(inputs), std::move(outputs)), _cond_graph(cond_graph), _body_graph(body_graph)
{
}
While() [2/2]
luci_interpreter::kernels::While::While (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, RuntimeGraph * cond_graph, RuntimeGraph * body_graph)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::While::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 67 of file While.cpp.
{
  LUCI_INTERPRETER_CHECK(_body_graph->getInputTensors().size() == getInputTensors().size());
  LUCI_INTERPRETER_CHECK(_body_graph->getOutputTensors().size() == getOutputTensors().size());
  LUCI_INTERPRETER_CHECK(_body_graph->getOutputTensors().size() == getInputTensors().size());
  LUCI_INTERPRETER_CHECK(_cond_graph->getInputTensors().size() == getInputTensors().size());
  const auto &cond_outputs = _cond_graph->getOutputTensors();
  LUCI_INTERPRETER_CHECK(cond_outputs.size() == 1)
  LUCI_INTERPRETER_CHECK(cond_outputs[0]->element_type() == DataType::BOOL);
}
References luci_interpreter::Kernel::getInputTensors(), luci_interpreter::RuntimeGraph::getInputTensors(), luci_interpreter::Kernel::getOutputTensors(), luci_interpreter::RuntimeGraph::getOutputTensors(), LUCI_INTERPRETER_CHECK, and luci_interpreter::size().
configure() [2/2]
void luci_interpreter::kernels::While::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::While::execute () const override virtual
Note
Dynamic shape such as {1, 0, 8} may fail in tensor->data()
Implements luci_interpreter::Kernel.
Definition at line 83 of file While.cpp.
{
  const auto &cond_inputs = _cond_graph->getInputTensors();
  const auto &cond_outputs = _cond_graph->getOutputTensors();
  configureTensorsAllocations(cond_inputs, _cond_graph);
  copy(getInputTensors(), cond_inputs);
  const auto &body_inputs = _body_graph->getInputTensors();
  const auto &body_outputs = _body_graph->getOutputTensors();
  configureTensorsAllocations(body_inputs, _body_graph);
  while (true)
  {
    _cond_graph->execute();
    bool cond_value = cond_outputs[0]->data<bool>()[0];
    if (!cond_value)
      break;
    copy(cond_inputs, body_inputs);
    _body_graph->execute();
    copy(body_outputs, cond_inputs);
  }
  copy(cond_inputs, getOutputTensors());
}
References luci_interpreter::RuntimeGraph::execute(), luci_interpreter::Kernel::getInputTensors(), luci_interpreter::RuntimeGraph::getInputTensors(), luci_interpreter::Kernel::getOutputTensors(), and luci_interpreter::RuntimeGraph::getOutputTensors().
execute() [2/2]
void luci_interpreter::kernels::While::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::While::input (int index) const inline
Definition at line 34 of file While.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
input() [2/2]
const Tensor * luci_interpreter::kernels::While::input (int index) const inline
Definition at line 34 of file While.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::While::output (int index) const inline
Definition at line 35 of file While.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
output() [2/2]
Tensor * luci_interpreter::kernels::While::output (int index) const inline
Definition at line 35 of file While.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/While.h
onert-micro/luci-interpreter/src/kernels/While.h
compiler/luci-interpreter/src/kernels/While.cpp
onert-micro/luci-interpreter/src/kernels/While.cpp