ONE - On-device Neural Engine: flexbuffers::Blob Class Reference
flexbuffers::Blob Class Reference
#include <flexbuffers.h>
Public Member Functions
Blob (const uint8_t *data_buf, uint8_t byte_width)
bool IsTheEmptyBlob () const
const uint8_t * data () const
Public Member Functions inherited from flexbuffers::Sized
Sized (const uint8_t *data, uint8_t byte_width)
Sized (const uint8_t *data, uint8_t byte_width, size_t sz)
size_t size () const
size_t read_size () const
Public Member Functions inherited from flexbuffers::Object
Object (const uint8_t *data, uint8_t byte_width)
Static Public Member Functions
static Blob EmptyBlob ()
Additional Inherited Members
Protected Attributes inherited from flexbuffers::Sized
size_t size_
Protected Attributes inherited from flexbuffers::Object
const uint8_t * data_
uint8_t byte_width_
Detailed Description
Definition at line 263 of file flexbuffers.h.
Constructor & Destructor Documentation
Blob()
flexbuffers::Blob::Blob (const uint8_t * data_buf, uint8_t byte_width) inline
Definition at line 266 of file flexbuffers.h.
: Sized(data_buf, byte_width) {}
Member Function Documentation
data()
const uint8_t * flexbuffers::Blob::data () const inline
Definition at line 274 of file flexbuffers.h.
{ return data_; }
References flexbuffers::Object::data_.
EmptyBlob()
static Blob flexbuffers::Blob::EmptyBlob () inline static
Definition at line 268 of file flexbuffers.h.
  {
    static const uint8_t empty_blob[] = {0 /*len*/};
    return Blob(empty_blob + 1, 1);
  }
Referenced by flexbuffers::Reference::AsBlob(), and IsTheEmptyBlob().
IsTheEmptyBlob()
bool flexbuffers::Blob::IsTheEmptyBlob () const inline
Definition at line 273 of file flexbuffers.h.
{ return data_ == EmptyBlob().data_; }
References flexbuffers::Object::data_, and EmptyBlob().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h