ONE - On-device Neural Engine: nnc::AclCppOpGenerator Class Reference
nnc::AclCppOpGenerator Class Reference
Implements the visitor for the model IR which generates the DOM description translated to C++ source/header files by the ACL soft backend code generators.
#include <AclCppOpGenerator.h>
Public Member Functions
AclCppOpGenerator (const std::string &name, std::ostream &par_out)
const ArtifactModule & generate (mir::Graph *g)
The main interface function to the class. Convers the model IR to the DOM.
void visit (mir::ops::AddOp &op) override
Implementations of the MIR visitors.
void visit (mir::ops::AvgPool2DOp &op) override
void visit (mir::ops::CappedReluOp &op) override
void visit (mir::ops::ConcatOp &op) override
void visit (mir::ops::ConstantOp &op) override
void visit (mir::ops::Conv2DOp &op) override
void visit (mir::ops::DeConv2DOp &op) override
void visit (mir::ops::DepthwiseConv2DOp &op) override
void visit (mir::ops::DivOp &op) override
void visit (mir::ops::EluOp &op) override
void visit (mir::ops::FullyConnectedOp &op) override
void visit (mir::ops::GatherOp &op) override
void visit (mir::ops::InputOp &op) override
void visit (mir::ops::LeakyReluOp &op) override
void visit (mir::ops::MaxOp &op) override
void visit (mir::ops::MaxPool2DOp &op) override
void visit (mir::ops::MulOp &op) override
void visit (mir::ops::OutputOp &op) override
void visit (mir::ops::PadOp &op) override
void visit (mir::ops::ReluOp &op) override
void visit (mir::ops::ReshapeOp &op) override
void visit (mir::ops::ResizeOp &op) override
void visit (mir::ops::SigmoidOp &op) override
void visit (mir::ops::SliceOp &op) override
void visit (mir::ops::SoftmaxOp &op) override
void visit (mir::ops::SqrtOp &op) override
void visit (mir::ops::SqueezeOp &op) override
void visit (mir::ops::SubOp &op) override
void visit (mir::ops::TanhOp &op) override
void visit (mir::ops::TransposeOp &op) override
template<typename Op >
shared_ptr< ArtifactVariable > genPadStrideInfo (const Op &op, const string &prefix, ArtifactBlock *block)
template<typename Op >
void genConvolution (Op &op, const string &acl_func_name, const string &suffix)
template<typename T >
std::shared_ptr< ArtifactId > genVectorInitializedVar (ArtifactBlock *block, const string &type, const string &name, const vector< T > &init)
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Protected Member Functions
void visit_fallback (mir::Operation &op) override
virtual void visit_fallback (Operation &)
Detailed Description
Implements the visitor for the model IR which generates the DOM description translated to C++ source/header files by the ACL soft backend code generators.
Definition at line 37 of file AclCppOpGenerator.h.
Constructor & Destructor Documentation
AclCppOpGenerator()
nnc::AclCppOpGenerator::AclCppOpGenerator (const std::string & name, std::ostream & par_out)
Definition at line 35 of file AclCppOpGenerator.cpp.
  : _parOut(par_out), _module(name), _constrBlock(nullptr), _infBlock(nullptr),
    _clScheduler(AF::id("arm_compute::CLScheduler"))
{
}
Member Function Documentation
genConvolution()
template<typename Op > void nnc::AclCppOpGenerator::genConvolution (Op & op, const string & acl_func_name, const string & suffix)
Definition at line 494 of file AclCppOpGenerator.cpp.
{
  const auto *ir_input = op.getInput(0);
  const auto *ir_weights = op.getInput(1);
  const auto *ir_output = op.getOutput(0);
  auto ir_weights_op = dynamic_cast<const ops::ConstantOp *>(ir_weights->getNode());
  if (ir_weights_op == nullptr)
    throw AclCppException("Unsupported operation type");
  auto ir_weights_tensor = ir_weights_op->getValue();
  if (op.getType() == Operation::Type::conv2D)
  {
    // [Co, Hk, Wk, Ci] -> [Co, Ci, Hk, Wk].
    ir_weights_tensor = transposeTensor<0, 3, 1, 2>(ir_weights_tensor);
  }
  else
  {
    ir_weights_tensor = transposeTensor<3, 2, 0, 1>(ir_weights_tensor);
  }
  const Shape &ir_weights_shape = ir_weights_tensor.getShape();
  // get output tensor name that is used as base for other names
  const string output_tensor_name = tensorName(ir_output);
  // Get the identifier of the input tensor in the DOM.
  auto input = AF::id(tensorName(ir_input));
  // Generate auxiliary tensor to hold transposed input of convolution in NCHW format
  shared_ptr<ArtifactId> transposed_input =
    genTransposeMIRtoACL(output_tensor_name + "_transposed_input", ir_input->getShape(), input);
  // Create the transposed output tensor in the DOM.
  const string transposed_output_name = output_tensor_name + "_transposed_output";
  Shape transposed_output_shape = transposeShape<0, 3, 1, 2>(ir_output->getShape());
  shared_ptr<ArtifactId> transposed_output =
    genTensor(transposed_output_name, transposed_output_shape);
  string operation_name = output_tensor_name + suffix;
  // Generate a tensor for weights (kernel) in the DOM.
  auto weights = genTensor(operation_name + "_weights", ir_weights_shape);
  // Create a local variable of type PadStrideInfo in the artifact constructor:
  // PadStrideInfo pad_stride_info(stride_x, stride_y, pad_x, pad_y);
  auto pad_stride_info_var = genPadStrideInfo(op, operation_name, _constrBlock);
  auto pad_stride_info = pad_stride_info_var->use();
  // The parameter for the conv_layer.config(&in, &weights, nullptr, &out, pad_stride_info)
  // function call.
  list<shared_ptr<ArtifactExpr>> config_params{AF::ref(transposed_input), AF::ref(weights),
                                               AF::lit("nullptr"), AF::ref(transposed_output),
                                               pad_stride_info};
  // Add to additional parameters for deconvolution.
  if (op.getType() == Operation::Type::deConv2D)
  {
    config_params.push_back(AF::lit("0"));
    config_params.push_back(AF::lit("0"));
  }
  // Create the convolution (/depthwise convolution/deconvolution) layer class instance.
  shared_ptr<ArtifactId> layer = genLayer(acl_func_name, operation_name, config_params);
  addToPersistentTensors(weights);
  // Save the IR weights tensor to later read this in the artifact.
  serializeTensor(weights, ir_weights_tensor);
  genTensorAllocation(_infBlock, transposed_output);
  genLayerExecution(layer);
  // Generate auxiliar tensor to hold transposed output of convolution in NHWC format
  shared_ptr<ArtifactId> output =
    genTransposeACLtoMIR(output_tensor_name, transposed_output_shape, transposed_output);
  genTensorDeallocation(_infBlock, transposed_input);
  genTensorDeallocation(_infBlock, transposed_output);
}
References nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), and nnc::ArtifactFactory::ref().
generate()
const ArtifactModule & nnc::AclCppOpGenerator::generate (mir::Graph * g)
The main interface function to the class. Convers the model IR to the DOM.
Parameters
g - pointer the model IR graph.
Returns
- reference to the top-level DOM entity.
Definition at line 41 of file AclCppOpGenerator.cpp.
{
  // Including headers.
  _module.addHeaderSysInclude("fstream");
  _module.addHeaderInclude("arm_compute/core/Types.h");
  _module.addHeaderInclude("arm_compute/runtime/CL/CLFunctions.h");
  _module.addHeaderInclude("arm_compute/runtime/CL/CLScheduler.h");
  _module.addHeaderInclude("arm_compute/runtime/CL/CLBufferAllocator.h");
  _module.addHeaderInclude("arm_compute/runtime/BlobLifetimeManager.h");
  _module.addHeaderInclude("arm_compute/runtime/PoolManager.h");
  _module.addHeaderInclude("arm_compute/runtime/MemoryManagerOnDemand.h");
  // The general structure creation.
  _artifactClass = _module.createClass(_module.name());
  _constrBlock = _artifactClass->getConstrBlock();
  _inferenceFunction = _artifactClass->func(true, "void", "Inference");
  _infBlock = _inferenceFunction->getBlock();
  // Input parameter stream preparation.
  _parInVar = _artifactClass->var(false, "std::ifstream", "_parIn");
  _parIn = _parInVar->use();
  string par_file_name = _module.name() + ".par";
  _constrBlock->call(
    "open",
    {AF::lit("\"" + par_file_name + "\""), AF::lit("std::ios_base::in | std::ios_base::binary")},
    _parIn);
  auto file_fail = _constrBlock->ifCond(AF::call("fail", {}, _parIn));
  auto file_fail_block = file_fail->getBlock();
  file_fail_block->addStatement(
    AF::lit("throw std::string(\"Failed to open file: " + par_file_name + " for reading\")"));
  // Traverse the computational graph.
  g->accept(this);
  // Generate all the deferred entities.
  genNamed(g);
  genPersistentTensorAllocations();
  genDeserializations();
  genFillings();
  // Make sure all the OpenCL jobs are done executing:
  _infBlock->call("sync", {}, AF::call("get", {}, _clScheduler, ArtifactCallType::scope));
  return _module;
}
References nnc::ArtifactModule::addHeaderInclude(), nnc::ArtifactModule::addHeaderSysInclude(), nnc::ArtifactBlock::call(), nnc::ArtifactFactory::call(), nnc::ArtifactModule::createClass(), nnc::ArtifactBlock::ifCond(), nnc::ArtifactFactory::lit(), nnc::ArtifactModule::name(), and nnc::scope.
Referenced by nnc::AclCppCodeGenerator::run(), and TEST().
genPadStrideInfo()
template<typename Op > shared_ptr< ArtifactVariable > nnc::AclCppOpGenerator::genPadStrideInfo (const Op & op, const string & prefix, ArtifactBlock * block)
Definition at line 203 of file AclCppOpGenerator.cpp.
{
  using AF = ArtifactFactory;
  const Shape strides(op.getStrides());
  assert(strides.rank() == 2);
  auto &padding_before = op.getPaddingBefore();
  auto &padding_after = op.getPaddingAfter();
  string type_name = "arm_compute::PadStrideInfo";
  string var_name = prefix + "_pad_stride_info";
  list<std::shared_ptr<ArtifactExpr>> var_init_params = {
    AF::lit(to_string(strides.dim(1))),
    AF::lit(to_string(strides.dim(0))),
    AF::lit(to_string(padding_before.at(1))),
    AF::lit(to_string(padding_after.at(1))),
    AF::lit(to_string(padding_before.at(0))),
    AF::lit(to_string(padding_after.at(0))),
    AF::lit("arm_compute::DimensionRoundingType::FLOOR")};
  auto pad_stride_info_var = block->var(type_name, var_name, {}, var_init_params);
  return pad_stride_info_var;
}
References mir::Shape::dim(), nnc::ArtifactFactory::lit(), mir::Shape::rank(), and nnc::ArtifactBlock::var().
genVectorInitializedVar()
template<typename T > std::shared_ptr< ArtifactId > nnc::AclCppOpGenerator::genVectorInitializedVar (ArtifactBlock * block, const string & type, const string & name, const vector< T > & init)
Definition at line 715 of file AclCppOpGenerator.cpp.
{
  list<shared_ptr<ArtifactExpr>> dims;
  for (const auto &v : init)
    dims.push_back(AF::lit(to_string(v)));
  auto shape_var = block->var(type, name, {}, dims);
  auto shape_id = shape_var->use();
  return shape_id;
}
References nnc::ArtifactFactory::lit(), and nnc::ArtifactBlock::var().
visit() [1/30]
void nnc::AclCppOpGenerator::visit (mir::ops::AddOp & op) override
Implementations of the MIR visitors.
Parameters
op
Definition at line 958 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 2);
  const auto *ir_lhs = op.getInput(0);
  const auto *ir_rhs = op.getInput(1);
  const auto *ir_output = op.getOutput(0);
  // Create the output tensor in the DOM and obtain its identifier.
  auto out = genTensor(ir_output);
  addToPersistentTensors(out);
  // Get the identifiers of the input tensors in the DOM.
  auto lhs = AF::id(tensorName(ir_lhs));
  auto rhs = AF::id(tensorName(ir_rhs));
  genAddition(out->name() + "_" + "addition", 0, ir_rhs->getShape(), lhs, rhs, out);
}
References mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), and nnc::ArtifactFactory::id().
visit() [2/30]
void nnc::AclCppOpGenerator::visit (mir::ops::AvgPool2DOp & op) override
Definition at line 253 of file AclCppOpGenerator.cpp.
{
  genPooling(op, "arm_compute::PoolingType::AVG", !op.getIncludePad());
}
References mir::ops::AvgPool2DOp::getIncludePad().
visit() [3/30]
void nnc::AclCppOpGenerator::visit (mir::ops::CappedReluOp & op) override
Definition at line 301 of file AclCppOpGenerator.cpp.
{
  genActivation(op, "LU_BOUNDED_RELU", op.getCap());
}
References mir::ops::CappedReluOp::getCap().
visit() [4/30]
void nnc::AclCppOpGenerator::visit (mir::ops::ConcatOp & op) override
Definition at line 87 of file AclCppOpGenerator.cpp.
{
  const auto &ir_inputs = op.getInputs();
  const auto *ir_output = op.getOutput(0);
  static const char *axis_names[] = {
    "arm_compute::DataLayoutDimension::BATCHES", "arm_compute::DataLayoutDimension::CHANNEL",
    "arm_compute::DataLayoutDimension::HEIGHT", "arm_compute::DataLayoutDimension::WIDTH"};
  int axis = op.getAxis();
  assert(axis >= 0 && axis < static_cast<int>(sizeof(axis_names) / sizeof(axis_names[0])) &&
         "axis outside this range is not supported in ACL");
  const char *axis_name = axis_names[axis];
  auto out = genTensor(ir_output);
  auto prefix = out->name() + "_concatenate_layer";
  auto inputs_var = _constrBlock->var("std::vector<arm_compute::ICLTensor*>", prefix + "_inputs");
  auto inputs = inputs_var->use();
  for (const Operation::Output *ir_input : ir_inputs)
    _constrBlock->call("push_back", {AF::ref(AF::id(tensorName(ir_input)))}, inputs);
  auto layer =
    genLayer("arm_compute::CLConcatenateLayer", prefix, {inputs, AF::ref(out), AF::lit(axis_name)});
  addToPersistentTensors(out);
  genLayerExecution(layer);
}
References nnc::ArtifactBlock::call(), mir::ops::ConcatOp::getAxis(), mir::Operation::getInputs(), mir::Operation::getOutput(), nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), nnc::ArtifactFactory::ref(), and nnc::ArtifactBlock::var().
visit() [5/30]
void nnc::AclCppOpGenerator::visit (mir::ops::ConstantOp & op) override
Definition at line 338 of file AclCppOpGenerator.cpp.
{
  if (shouldSerializeConstant(op))
  {
    TensorVariant data = op.getValue();
    shared_ptr<ArtifactId> out = genTensor(op.getOutput(0));
    addToPersistentTensors(out);
    serializeTensor(out, data);
  }
}
References mir::Operation::getOutput(), and mir::ops::ConstantOp::getValue().
visit() [6/30]
void nnc::AclCppOpGenerator::visit (mir::ops::Conv2DOp & op) override
Definition at line 116 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumGroups() == 1);
  genConvolution(op, "arm_compute::CLConvolutionLayer", "_convolution_layer");
}
References mir::ops::Conv2DOp::getNumGroups().
visit() [7/30]
void nnc::AclCppOpGenerator::visit (mir::ops::DeConv2DOp & op) override
Definition at line 392 of file AclCppOpGenerator.cpp.
{
  genConvolution(op, "arm_compute::CLDeconvolutionLayer", "_deconvolution_layer");
}
visit() [8/30]
void nnc::AclCppOpGenerator::visit (mir::ops::DepthwiseConv2DOp & op) override
Definition at line 122 of file AclCppOpGenerator.cpp.
{
  genConvolution(op, "arm_compute::CLDepthwiseConvolutionLayer", "_depthwise_convolution_layer");
}
visit() [9/30]
void nnc::AclCppOpGenerator::visit (mir::ops::DivOp & op) override
Definition at line 976 of file AclCppOpGenerator.cpp.
{ throw AclCppException("NYI"); }
visit() [10/30]
void nnc::AclCppOpGenerator::visit (mir::ops::EluOp & op) override
Definition at line 397 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("EluOp not supported by the ACL library yet.");
}
visit() [11/30]
void nnc::AclCppOpGenerator::visit (mir::ops::FullyConnectedOp & op) override
Definition at line 264 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 2);
  const auto *ir_input = op.getInput(0);
  const auto *ir_weights = op.getInput(1);
  const auto *ir_output = op.getOutput(0);
  auto ir_weights_op = dynamic_cast<const mir::ops::ConstantOp *>(ir_weights->getNode());
  if (ir_weights_op == nullptr)
    throw AclCppException("Unsupported operation type");
  const TensorVariant ir_weights_tensor = transposeTensor<1, 0>(ir_weights_op->getValue());
  const Shape &ir_weights_shape = ir_weights_tensor.getShape();
  // Get the input node tensor id in the DOM.
  auto in = AF::id(tensorName(ir_input));
  // Create the output tensor in the DOM.
  if (ir_output->getShape().rank() != 2)
    throw AclCppException("Unsupported number of dimensions in fc layer");
  auto out = genTensor(ir_output);
  string operation_name = out->name() + "_fully_connected_layer";
  // Create the weights tensor in the DOM and use its id.
  auto weights = genTensor(operation_name + "_weights", ir_weights_shape);
  // Instantiate the CLFullyConnectedLayer object.
  auto layer = genLayer("arm_compute::CLFullyConnectedLayer", operation_name,
                        {AF::ref(in), AF::ref(weights), AF::lit("nullptr"), AF::ref(out)});
  addToPersistentTensors(weights);
  // Serialize the weights tensor and generate the function to deserialize it in the artifact.
  serializeTensor(weights, ir_weights_tensor);
  addToPersistentTensors(out);
  genLayerExecution(layer);
}
References mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), mir::TensorVariant::getShape(), nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), and nnc::ArtifactFactory::ref().
visit() [12/30]
void nnc::AclCppOpGenerator::visit (mir::ops::GatherOp & op) override
Definition at line 941 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("Unimplemented operation: GatherOp");
}
visit() [13/30]
void nnc::AclCppOpGenerator::visit (mir::ops::InputOp & op) override
Definition at line 306 of file AclCppOpGenerator.cpp.
{
  shared_ptr<ArtifactId> tensor;
  tensor = genTensor(op.getOutput(0));
  addToPersistentTensors(tensor);
}
References mir::Operation::getOutput().
visit() [14/30]
void nnc::AclCppOpGenerator::visit (mir::ops::LeakyReluOp & op) override
Definition at line 948 of file AclCppOpGenerator.cpp.
{
  genActivation(op, "LEAKY_RELU", op.getAlpha());
}
References mir::ops::LeakyReluOp::getAlpha().
visit() [15/30]
void nnc::AclCppOpGenerator::visit (mir::ops::MaxOp & op) override
Definition at line 978 of file AclCppOpGenerator.cpp.
{ throw AclCppException("NYI"); }
visit() [16/30]
void nnc::AclCppOpGenerator::visit (mir::ops::MaxPool2DOp & op) override
Definition at line 258 of file AclCppOpGenerator.cpp.
{
  // The value of 'exclude_padding' does not really matter for MAX pooling.
  genPooling(op, "arm_compute::PoolingType::MAX", false);
}
visit() [17/30]
void nnc::AclCppOpGenerator::visit (mir::ops::MulOp & op) override
Definition at line 980 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 2);
  const auto *ir_lhs = op.getInput(0);
  const auto *ir_rhs = op.getInput(1);
  const auto *ir_output = op.getOutput(0);
  // Create the output tensor in the DOM and obtain its identifier.
  auto out = genTensor(ir_output);
  addToPersistentTensors(out);
  // Get the identifiers of the input tensors in the DOM.
  auto lhs = AF::id(tensorName(ir_lhs));
  auto rhs = AF::id(tensorName(ir_rhs));
  genMultiplication(out->name() + "_" + "multiplication", 0, ir_rhs->getShape(), lhs, rhs, out);
}
References mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), and nnc::ArtifactFactory::id().
visit() [18/30]
void nnc::AclCppOpGenerator::visit (mir::ops::OutputOp & op) override
Definition at line 953 of file AclCppOpGenerator.cpp.
{
  // No-op.
}
visit() [19/30]
void nnc::AclCppOpGenerator::visit (mir::ops::PadOp & op) override
Definition at line 402 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 1);
  const auto *ir_input = op.getInput(0);
  const auto *ir_output = op.getOutput(0);
  // Get the id of the input tensor.
  auto input = AF::id(tensorName(ir_input));
  // Create the output tensor in the DOM
  auto out = genTensor(ir_output);
  addToPersistentTensors(out);
  // Generate PadLayer params
  auto prefix = out->name() + "_pad_layer";
  auto pad_list_decl = _constrBlock->var("arm_compute::PaddingList", prefix + "_pads");
  auto pad_list = pad_list_decl->use();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  for (int i = 0; i < ir_input->getShape().rank(); ++i)
  {
    auto pad_var = _constrBlock->var(
      "arm_compute::PaddingInfo", prefix + "_pad_" + to_string(i), {},
      {AF::lit(to_string(padding_before[i])), AF::lit(to_string(padding_after[i]))});
    auto pad = pad_var->use();
    _constrBlock->call("push_back", {pad}, pad_list);
  }
  // Generate PadLayer
  // FIXME Set up the `constant_value` parameter.
  assert(op.getPaddingValue() == 0.0f);
  auto layer =
    genLayer("arm_compute::CLPadLayer", prefix, {AF::ref(input), AF::ref(out), pad_list});
  genLayerExecution(layer);
}
References nnc::ArtifactBlock::call(), mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), mir::ops::PadOp::getPaddingAfter(), mir::ops::PadOp::getPaddingBefore(), mir::ops::PadOp::getPaddingValue(), nnc::ArtifactFactory::id(), nnc::ArtifactFactory::lit(), nnc::ArtifactFactory::ref(), and nnc::ArtifactBlock::var().
visit() [20/30]
void nnc::AclCppOpGenerator::visit (mir::ops::ReluOp & op) override
Definition at line 349 of file AclCppOpGenerator.cpp.
{ genActivation(op, "RELU"); }
visit() [21/30]
void nnc::AclCppOpGenerator::visit (mir::ops::ReshapeOp & op) override
Definition at line 351 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 1);
  const auto *ir_input = op.getInput(0);
  const auto *ir_output = op.getOutput(0);
  // Get the id of the input tensor in the generated artifact.
  auto in = AF::id(tensorName(ir_input));
  // Create the output tensor in the DOM and return its id.
  const Shape &out_shape = ir_output->getShape();
  // This check confirms that we can "safely" reshape data
  // The only safe configuration of output shape is (1...1, N, 1 ... 1)
  bool found_non_one = false;
  for (int32_t i = 0; i < out_shape.rank(); ++i)
  {
    if (out_shape.dim(i) != 1)
    {
      if (found_non_one)
        throw AclCppException("Unsupported result of reshape");
      found_non_one = true;
    }
  }
  shared_ptr<ArtifactId> out = genTensor(ir_output);
  // Create an instance of the CLReshapeLayer class as a member of the artifact class.
  auto layer = genLayer("arm_compute::CLReshapeLayer", out->name() + "_reshape_layer",
                        {AF::ref(in), AF::ref(out)});
  addToPersistentTensors(out);
  genLayerExecution(layer);
}
References mir::Shape::dim(), mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), nnc::ArtifactFactory::id(), and mir::Shape::rank().
visit() [22/30]
void nnc::AclCppOpGenerator::visit (mir::ops::ResizeOp & op) override
Definition at line 877 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("Unimplemented operation: Resize");
}
visit() [23/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SigmoidOp & op) override
Definition at line 946 of file AclCppOpGenerator.cpp.
{ genActivation(op, "LOGISTIC"); }
visit() [24/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SliceOp & op) override
Definition at line 385 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("Unimplemented operation: SliceOp");
}
visit() [25/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SoftmaxOp & op) override
Definition at line 127 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 1);
  const auto *ir_input = op.getInput(0);
  const auto *ir_output = op.getOutput(0);
  auto in = AF::id(tensorName(ir_input));
  int rank = ir_output->getShape().rank();
  // CLPermute does not support all kinds of permutations now.
  // rank can be more than 2 in our models, so we can not use CLTranspose.
  // This means we can support tensors with no more then one axis > 1.
  int axis = op.getAxis();
  assert(axis == rank - 1);
  int nof_long_axes = 0;
  for (int i = 0; i < rank; ++i)
  {
    if (ir_output->getShape().dim(i) > 1)
      ++nof_long_axes;
  }
  // TODO: Consider how to support Softmax on more general inputs.
  if (nof_long_axes > 1)
    throw AclCppException("Unsupported Softmax operation with several dimensions greater than 1");
  // Create the output tensor.
  shared_ptr<ArtifactId> output = genTensor(ir_output);
  auto layer_name_prefix = output->name();
  if (axis == 0)
  {
    // Simple version: do not need pre and post reshapes.
    // Apply the softmax operation.
    auto sm = genLayer("arm_compute::CLSoftmaxLayer", layer_name_prefix + "_softmax_layer",
                       {AF::ref(in), AF::ref(output)});
    addToPersistentTensors(output);
    genLayerExecution(sm);
  }
  else
  {
    // TODO refactor this code, it works only with 1 batch
    // Need to reshape before the Softmax application and after it.
    // Then we need two tensors for intermediate results. This is because we do a couple of
    // auxiliary
    // reshapes: one to transform the input tensor to a unidimensional tensor and the second to
    // transorm the result of the softmax operation back to the original form.
    Shape sm_shape(ir_output->getShape());
    std::swap(sm_shape.dim(axis), sm_shape.dim(-1));
    auto tmp = genTensor(layer_name_prefix + "_tmp", sm_shape);
    auto tmp2 = genTensor(layer_name_prefix + "_tmp2", sm_shape);
    // Do the input permutation.
    auto transp1 = genLayer("arm_compute::CLReshapeLayer", layer_name_prefix + "_transp_layer1",
                            {AF::ref(in), AF::ref(tmp)});
    addToPersistentTensors(tmp);
    genLayerExecution(transp1);
    // Apply the softmax operaion.
    auto sm = genLayer("arm_compute::CLSoftmaxLayer", layer_name_prefix + "_softmax_layer",
                       {AF::ref(tmp), AF::ref(tmp2)});
    addToPersistentTensors(tmp2);
    genLayerExecution(sm);
    // Reshape the output to the original form.
    auto transp2 = genLayer("arm_compute::CLReshapeLayer", layer_name_prefix + "_transp_layer2",
                            {AF::ref(tmp2), AF::ref(output)});
    addToPersistentTensors(output);
    genLayerExecution(transp2);
  }
}
References mir::Shape::dim(), mir::ops::SoftmaxOp::getAxis(), mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), nnc::ArtifactFactory::id(), and nnc::ArtifactFactory::ref().
visit() [26/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SqrtOp & op) override
Definition at line 834 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("Unimplemented operation: Sqrt");
}
visit() [27/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SqueezeOp & op) override
Definition at line 829 of file AclCppOpGenerator.cpp.
{
  throw AclCppException("Unimplemented operation: Squeeze");
}
visit() [28/30]
void nnc::AclCppOpGenerator::visit (mir::ops::SubOp & op) override
Definition at line 998 of file AclCppOpGenerator.cpp.
{ throw AclCppException("NYI"); }
visit() [29/30]
void nnc::AclCppOpGenerator::visit (mir::ops::TanhOp & op) override
Definition at line 390 of file AclCppOpGenerator.cpp.
{ genActivation(op, "TANH"); }
visit() [30/30]
void nnc::AclCppOpGenerator::visit (mir::ops::TransposeOp & op) override
Definition at line 921 of file AclCppOpGenerator.cpp.
{
  assert(op.getNumInputs() == 1);
  const auto *ir_input = op.getInput(0);
  const auto *ir_output = op.getOutput(0);
  // Get the input node tensor id in the DOM.
  shared_ptr<ArtifactId> input = AF::id(tensorName(ir_input));
  const vector<size_t> &mir_axis_order = op.getAxisOrder();
  // Create the output tensor in the DOM.
  if (ir_output->getShape().rank() != 4)
    throw AclCppException("Unsupported number of dimensions in transpose operation");
  // TODO replace transpose shape
  shared_ptr<ArtifactId> output = genTensor(ir_output);
  // Actual generation of operation and related stuff
  genTranspose(input, output, mir_axis_order, false);
}
References mir::ops::TransposeOp::getAxisOrder(), mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), and nnc::ArtifactFactory::id().
visit_fallback()
void nnc::AclCppOpGenerator::visit_fallback (mir::Operation & op) override protected virtual
Reimplemented from mir::Visitor.
Definition at line 1000 of file AclCppOpGenerator.cpp.
{ throw AclCppException("NYI"); }
The documentation for this class was generated from the following files:
compiler/nnc/backends/acl_soft_backend/AclCppOpGenerator.h
compiler/nnc/backends/acl_soft_backend/AclCppOpGenerator.cpp