ONE - On-device Neural Engine: tflinspect::Reader Class Reference
tflinspect::Reader Class Reference
Loads TF lite file and provides helpers to access attributes.
#include <Reader.h>
Public Member Functions
Reader (const tflite::Model *model)
Reader ()=delete
const std::vector< const tflite::OperatorCode * > & opcodes ()
const TFliteBuffers_t * buffers ()
const TFliteTensors_t * tensors ()
const TFliteOperators_t * operators ()
const std::vector< int32_t > & inputs () const
const std::vector< int32_t > & outputs () const
uint32_t num_subgraph () const
size_t buffer_info (uint32_t buf_idx, const uint8_t **buff_data)
tflite::BuiltinOperator builtin_code (const tflite::Operator *op) const
std::string opcode_name (const tflite::Operator *op) const
bool select_subgraph (uint32_t subgraph)
Detailed Description
Loads TF lite file and provides helpers to access attributes.
Definition at line 42 of file Reader.h.
Constructor & Destructor Documentation
Reader() [1/2]
tflinspect::Reader::Reader (const tflite::Model * model)
Definition at line 28 of file Reader.cpp.
{
  _subgraphs = model->subgraphs();
  _buffers = model->buffers();
  auto opcodes = model->operator_codes();
  for (const ::tflite::OperatorCode *opcode : *opcodes)
  {
    _op_codes.push_back(opcode);
  }
}
References opcodes().
Reader() [2/2]
tflinspect::Reader::Reader () delete
Member Function Documentation
buffer_info()
size_t tflinspect::Reader::buffer_info (uint32_t buf_idx, const uint8_t ** buff_data)
Definition at line 40 of file Reader.cpp.
{
  if (buff_data != nullptr)
  {
    *buff_data = nullptr;
  }
  if (buf_idx == 0)
    return 0;
  if (auto *buffer = (*_buffers)[buf_idx])
  {
    if (auto *array = buffer->data())
    {
      if (size_t size = array->size())
      {
        if (buff_data != nullptr)
        {
          *buff_data = reinterpret_cast<const uint8_t *>(array->data());
        }
        return size;
      }
    }
  }
  return 0;
}
buffers()
const TFliteBuffers_t * tflinspect::Reader::buffers () inline
Definition at line 57 of file Reader.h.
{ return _buffers; }
builtin_code()
tflite::BuiltinOperator tflinspect::Reader::builtin_code (const tflite::Operator * op) const
Definition at line 68 of file Reader.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  return mio::tflite::builtin_code_neutral(opcode);
}
References mio::tflite::builtin_code_neutral().
Referenced by tflinspect::DumpConv2DWeight::run().
inputs()
const std::vector< int32_t > & tflinspect::Reader::inputs () const inline
Definition at line 60 of file Reader.h.
{ return _inputs; }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
num_subgraph()
uint32_t tflinspect::Reader::num_subgraph () const inline
Definition at line 63 of file Reader.h.
{ return _subgraphs->Length(); }
Referenced by tflinspect::DumpOperators::run(), tflinspect::DumpConv2DWeight::run(), and tflinspect::DumpOperatorVersion::run().
opcode_name()
std::string tflinspect::Reader::opcode_name (const tflite::Operator * op) const
Definition at line 77 of file Reader.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  if (!mio::tflite::is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  return mio::tflite::opcode_name(opcode);
}
References mio::tflite::is_valid(), and mio::tflite::opcode_name().
Referenced by tflinspect::DumpOperators::run(), tflinspect::DumpConv2DWeight::run(), and tflinspect::DumpOperatorVersion::run().
opcodes()
const std::vector< const tflite::OperatorCode * > & tflinspect::Reader::opcodes () inline
Definition at line 56 of file Reader.h.
{ return _op_codes; }
Referenced by Reader(), and tflinspect::DumpOperatorVersion::run().
operators()
const TFliteOperators_t * tflinspect::Reader::operators () inline
Definition at line 59 of file Reader.h.
{ return _operators; }
Referenced by tflinspect::DumpOperators::run(), tflinspect::DumpConv2DWeight::run(), and tflinspect::DumpOperatorVersion::run().
outputs()
const std::vector< int32_t > & tflinspect::Reader::outputs () const inline
Definition at line 61 of file Reader.h.
{ return _outputs; }
Referenced by validate_onnx2circle.OnnxRunner::get_outputs().
select_subgraph()
bool tflinspect::Reader::select_subgraph (uint32_t subgraph)
Definition at line 93 of file Reader.cpp.
{
  _tensors = nullptr;
  _operators = nullptr;
  _inputs.clear();
  _outputs.clear();
  if (_subgraphs->Length() <= sgindex)
  {
    assert(false);
    return false;
  }
  const tflite::SubGraph *subgraph = (*_subgraphs)[sgindex];
  _tensors = subgraph->tensors();
  _operators = subgraph->operators();
  _inputs = as_index_vector(subgraph->inputs());
  _outputs = as_index_vector(subgraph->outputs());
  return true;
}
References tflinspect::as_index_vector().
Referenced by tflinspect::DumpOperators::run(), tflinspect::DumpConv2DWeight::run(), and tflinspect::DumpOperatorVersion::run().
tensors()
const TFliteTensors_t * tflinspect::Reader::tensors () inline
Definition at line 58 of file Reader.h.
{ return _tensors; }
The documentation for this class was generated from the following files:
compiler/tfl-inspect/src/Reader.h
compiler/tfl-inspect/src/Reader.cpp