ONE - On-device Neural Engine: moco::DepthwiseConv2dNativeGraphBuilder Class Reference
moco::DepthwiseConv2dNativeGraphBuilder Class Reference final
GraphBuilder for DepthwiseConv2dNative node.
#include <DepthwiseConv2dNative.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for DepthwiseConv2dNative node.
Definition at line 28 of file DepthwiseConv2dNative.h.
Member Function Documentation
build()
void moco::DepthwiseConv2dNativeGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 110 of file DepthwiseConv2dNative.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  auto depthwiseconv2d_native_node = graph->nodes()->create<TFDepthwiseConv2dNative>();
  depthwiseconv2d_native_node->name(node.name());
  // read attributes
  auto data_layout = get_string_attr(node, "data_format");
  depthwiseconv2d_native_node->data_layout(data_layout);
  auto tf_strides = get_list_attr(node, "strides");
  auto strides = as_int64_list(tf_strides);
  depthwiseconv2d_native_node->strides(strides);
  auto padding = moco::str_toupper(get_string_attr(node, "padding"));
  depthwiseconv2d_native_node->padding(padding);
  // save the name for graph link updates
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, depthwiseconv2d_native_node);
  std::vector<TensorName> input_names;
  input_names.push_back(TensorName(node.input(0))); // input
  input_names.push_back(TensorName(node.input(1))); // kernel
  // Record ifm inputs to featureEncode_node
  auto tfdepthwiseconv2dnative_update =
    std::make_unique<TFDepthwiseConv2dNativeGraphUpdate>(depthwiseconv2d_native_node, input_names);
  updates->enroll(std::move(tfdepthwiseconv2dnative_update));
}
References plier::tf::as_int64_list(), moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), plier::tf::get_list_attr(), plier::tf::get_string_attr(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::str_toupper(), moco::GraphBuilderContext::tensor_names(), and moco::GraphBuilderContext::updates().
validate()
bool moco::DepthwiseConv2dNativeGraphBuilder::validate (const tensorflow::NodeDef & node) const override virtual
Implements moco::GraphBuilder.
Definition at line 71 of file DepthwiseConv2dNative.cpp.
{
  if (node.input_size() != 2)
    return false;
  // note: even though "data_format" and "dilations" are not entered when a model is written,
  //       TF seems to generate those field into a pb file.
  if (!has_attrs(node, {"T", "data_format", "dilations", "padding", "strides"}))
    return false;
  auto data_layout = plier::tf::get_string_attr(node, "data_format");
  if (!(data_layout == "NHWC" || data_layout == "NCHW"))
  {
    throw oops::UserExn("DepthwiseConv2dNative Unsupported data_format", node.name());
  }
  auto padding = moco::str_toupper(get_string_attr(node, "padding"));
  if (!(padding == "VALID" || padding == "SAME"))
    return false;
  auto tf_strides = get_list_attr(node, "strides");
  auto strides = as_int64_list(tf_strides);
  if (!(strides.size() == 4))
  {
    throw oops::UserExn("DepthwiseConv2dNative strides requires rank 4", node.name());
  }
  auto stride_n = strides.at(0);
  auto stride_h = strides.at(1);
  auto stride_w = strides.at(2);
  auto stride_c = strides.at(3);
  if (!(stride_n == 1 && stride_c == 1) || !(stride_h == stride_w))
  {
    // TODO this message may need to be refined
    throw oops::UserExn("DepthwiseConv2dNative strides requires N=C=1, H=W", node.name());
  }
  return true;
}
References plier::tf::as_int64_list(), plier::tf::get_list_attr(), plier::tf::get_string_attr(), plier::tf::has_attrs(), and moco::str_toupper().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/DepthwiseConv2dNative.h
compiler/moco/import/src/Nodes/DepthwiseConv2dNative.cpp