ONE - On-device Neural Engine: flexbuffers::TypedVector Class Reference
flexbuffers::TypedVector Class Reference
#include <flexbuffers.h>
Public Member Functions
TypedVector (const uint8_t *data, uint8_t byte_width, Type element_type)
Reference operator[] (size_t i) const
bool IsTheEmptyVector () const
Type ElementType ()
Public Member Functions inherited from flexbuffers::Sized
Sized (const uint8_t *data, uint8_t byte_width)
Sized (const uint8_t *data, uint8_t byte_width, size_t sz)
size_t size () const
size_t read_size () const
Public Member Functions inherited from flexbuffers::Object
Object (const uint8_t *data, uint8_t byte_width)
Static Public Member Functions
static TypedVector EmptyTypedVector ()
Data Fields
friend Reference
Additional Inherited Members
Protected Attributes inherited from flexbuffers::Sized
size_t size_
Protected Attributes inherited from flexbuffers::Object
const uint8_t * data_
uint8_t byte_width_
Detailed Description
Definition at line 292 of file flexbuffers.h.
Constructor & Destructor Documentation
TypedVector()
flexbuffers::TypedVector::TypedVector (const uint8_t * data, uint8_t byte_width, Type element_type) inline
Definition at line 295 of file flexbuffers.h.
    : Sized(data, byte_width), type_(element_type)
  {
  }
Member Function Documentation
ElementType()
Type flexbuffers::TypedVector::ElementType () inline
Definition at line 309 of file flexbuffers.h.
{ return type_; }
EmptyTypedVector()
static TypedVector flexbuffers::TypedVector::EmptyTypedVector () inline static
Definition at line 302 of file flexbuffers.h.
  {
    static const uint8_t empty_typed_vector[] = {0 /*len*/};
    return TypedVector(empty_typed_vector + 1, 1, FBT_INT);
  }
References flexbuffers::FBT_INT.
Referenced by flexbuffers::Reference::AsTypedVector(), and IsTheEmptyVector().
IsTheEmptyVector()
bool flexbuffers::TypedVector::IsTheEmptyVector () const inline
Definition at line 307 of file flexbuffers.h.
{ return data_ == TypedVector::EmptyTypedVector().data_; }
References flexbuffers::Object::data_, and EmptyTypedVector().
operator[]()
Reference flexbuffers::TypedVector::operator[] (size_t i) const inline
Definition at line 952 of file flexbuffers.h.
{
  auto len = size();
  if (i >= len)
    return Reference(nullptr, 1, NullPackedType());
  auto elem = data_ + i * byte_width_;
  return Reference(elem, byte_width_, 1, type_);
}
References flexbuffers::Object::byte_width_, flexbuffers::Object::data_, flexbuffers::NullPackedType(), Reference, and flexbuffers::Sized::size().
Field Documentation
Reference
friend flexbuffers::TypedVector::Reference
Definition at line 311 of file flexbuffers.h.
Referenced by operator[]().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h