ONE - On-device Neural Engine: onert::compiler::PermuteFactor Class Reference
onert::compiler::PermuteFactor Class Reference
Class that has factors of permutation.
#include <PermuteFactor.h>
Public Member Functions
PermuteFactor (const backend::Backend *backend, ir::Layout layout)
Construct PermuteFactor object.
PermuteFactor (const PermuteFactor &f)
Construct PermuteFactor object by copy semantics.
PermuteFactor (PermuteFactor &&)=default
Construct PermuteFactor object by move semantics.
const backend::Backend * backend () const
Get backend.
ir::Layout layout () const
Get layout.
bool operator== (const PermuteFactor &other) const
operator overloading function for ==
bool operator!= (const PermuteFactor &other) const
operator overloading function for !=
Detailed Description
Class that has factors of permutation.
Definition at line 46 of file PermuteFactor.h.
Constructor & Destructor Documentation
PermuteFactor() [1/3]
onert::compiler::PermuteFactor::PermuteFactor (const backend::Backend * backend, ir::Layout layout) inline
Construct PermuteFactor object.
Parameters
backend The backend factor
layout The layout factor
Definition at line 54 of file PermuteFactor.h.
    : _backend{backend}, _layout{layout}
  {
    // DO NOTHING
  }
PermuteFactor() [2/3]
onert::compiler::PermuteFactor::PermuteFactor (const PermuteFactor & f) inline
Construct PermuteFactor object by copy semantics.
Definition at line 62 of file PermuteFactor.h.
                                        : _backend{f._backend}, _layout{f._layout}
  {
    // DO NOTHING
  }
PermuteFactor() [3/3]
onert::compiler::PermuteFactor::PermuteFactor (PermuteFactor &&) default
Construct PermuteFactor object by move semantics.
Member Function Documentation
backend()
const backend::Backend * onert::compiler::PermuteFactor::backend () const inline
Get backend.
Returns
Backend factor
Definition at line 77 of file PermuteFactor.h.
{ return _backend; }
Referenced by onert::compiler::OperationLowerInfo::backend(), and operator==().
layout()
ir::Layout onert::compiler::PermuteFactor::layout () const inline
Get layout.
Returns
Layout factor
Definition at line 83 of file PermuteFactor.h.
{ return _layout; }
Referenced by onert::compiler::OperationLowerInfo::layout(), and operator==().
operator!=()
bool onert::compiler::PermuteFactor::operator!= (const PermuteFactor & other) const inline
operator overloading function for !=
Returns
Whether two PermuteFactor are differenct
Definition at line 100 of file PermuteFactor.h.
{ return !(*this == other); }
operator==()
bool onert::compiler::PermuteFactor::operator== (const PermuteFactor & other) const inline
operator overloading function for ==
Returns
Whether two PermuteFactor are the same
Definition at line 91 of file PermuteFactor.h.
  {
    return _backend == other.backend() && _layout == other.layout();
  }
References backend(), and layout().
The documentation for this class was generated from the following file:
runtime/onert/core/include/compiler/PermuteFactor.h