ONE - On-device Neural Engine: moco::SqrtGraphBuilder Class Reference
moco::SqrtGraphBuilder Class Reference final
GraphBuilder for Sqrt node.
#include <Sqrt.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Sqrt node.
Definition at line 28 of file Sqrt.h.
Member Function Documentation
build()
void moco::SqrtGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 61 of file Sqrt.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  // creating TF dialect Sqrt node
  auto tf_sqrt = graph->nodes()->create<TFSqrt>();
  tf_sqrt->name(node.name());
  // register string-name to node
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, tf_sqrt);
  // Queue node input update
  auto tf_sqrt_update = std::make_unique<TFSqrtGraphUpdate>(tf_sqrt, TensorName(node.input(0)));
  updates->enroll(std::move(tf_sqrt_update));
}
References moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::GraphBuilderContext::tensor_names(), and moco::GraphBuilderContext::updates().
validate()
bool moco::SqrtGraphBuilder::validate (const tensorflow::NodeDef & node) const override virtual
Implements moco::GraphBuilder.
Definition at line 56 of file Sqrt.cpp.
{
  return node.input_size() == 1;
}
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Sqrt.h
compiler/moco/import/src/Nodes/Sqrt.cpp