ONE - On-device Neural Engine: onert::exec::train::TrainableExecutors Class Reference
onert::exec::train::TrainableExecutors Class Reference
Class to gather executor set for trainable model NN package.
#include <TrainableExecutors.h>
Public Member Functions
TrainableExecutors (void)=default
Construct a new TrainableExecutors object.
TrainableExecutors (const TrainableExecutors &)=delete
TrainableExecutors (TrainableExecutors &&)=default
~TrainableExecutors ()=default
Destroy the TrainableExecutors object.
TrainableExecutors & operator= (const TrainableExecutors &)=delete
TrainableExecutors & operator= (TrainableExecutors &&)=default
void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec) override
Insert executor in executor set.
TrainableExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const override
Return executor of index.
TrainableExecutor * entryExecutor () const
uint32_t inputSize () const override
Return executor set's number of input.
uint32_t outputSize () const override
Return executor set's number of output.
const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const override
Return NN package input tensor info.
const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const override
Return NN package output tensor info.
void execute (const IODescription &desc) override
Execute NN package executor set.
void train (const IODescription &desc, uint32_t training_step)
Train.
Public Member Functions inherited from onert::exec::IExecutors
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
Insert executor in executor set.
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
Return executor of index.
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
Return executor set's number of input.
virtual uint32_t outputSize () const =0
Return executor set's number of output.
virtual const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const =0
Return NN package input tensor info.
virtual const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const =0
Return NN package output tensor info.
virtual void execute (const IODescription &desc)=0
Execute NN package executor set.
Detailed Description
Class to gather executor set for trainable model NN package.
Definition at line 34 of file TrainableExecutors.h.
Constructor & Destructor Documentation
TrainableExecutors() [1/3]
onert::exec::train::TrainableExecutors::TrainableExecutors (void) default
Construct a new TrainableExecutors object.
TrainableExecutors() [2/3]
onert::exec::train::TrainableExecutors::TrainableExecutors (const TrainableExecutors &) delete
TrainableExecutors() [3/3]
onert::exec::train::TrainableExecutors::TrainableExecutors (TrainableExecutors &&) default
~TrainableExecutors()
onert::exec::train::TrainableExecutors::~TrainableExecutors () default
Destroy the TrainableExecutors object.
Member Function Documentation
at()
TrainableExecutor * onert::exec::train::TrainableExecutors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const override virtual
Return executor of index.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
Returns
Executor
Implements onert::exec::IExecutors.
Definition at line 38 of file TrainableExecutors.cc.
{
  return _executors.at(subg_index).get();
}
Referenced by entryExecutor().
emplace()
void onert::exec::train::TrainableExecutors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) override virtual
Insert executor in executor set.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
[in] exec Executor to insert
Implements onert::exec::IExecutors.
Definition at line 30 of file TrainableExecutors.cc.
{
  std::unique_ptr<TrainableExecutor> t_exec{
    nnfw::misc::polymorphic_downcast<TrainableExecutor *>(exec.release())};
  _executors.emplace(subg_index, std::move(t_exec));
}
entryExecutor()
TrainableExecutor * onert::exec::train::TrainableExecutors::entryExecutor () const inline
Definition at line 60 of file TrainableExecutors.h.
{ return at(ir::ModelIndex{0}, ir::SubgraphIndex{0}); }
References at().
Referenced by execute(), inputInfo(), inputSize(), outputInfo(), outputSize(), and train().
execute()
void onert::exec::train::TrainableExecutors::execute (const IODescription & desc) override virtual
Execute NN package executor set.
Parameters
[in] desc Input and output buffer description
Implements onert::exec::IExecutors.
Definition at line 61 of file TrainableExecutors.cc.
{
  if (_executors.size() > 1)
    throw std::runtime_error("TrainableExecutors does not support multiple executors yet");
  entryExecutor()->forward(desc, false);
  // TODO Support multple executors
}
References entryExecutor(), and onert::exec::train::TrainableExecutor::forward().
inputInfo()
const ir::OperandInfo & onert::exec::train::TrainableExecutors::inputInfo (const ir::IOIndex & index) const override virtual
Return NN package input tensor info.
Parameters
[in] index Input index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 51 of file TrainableExecutors.cc.
{
  return entryExecutor()->getInputTensors().at(index.value())->orig_info();
}
References entryExecutor(), and onert::exec::train::TrainableExecutor::getInputTensors().
inputSize()
uint32_t onert::exec::train::TrainableExecutors::inputSize () const override virtual
Return executor set's number of input.
Returns
Number of input
Implements onert::exec::IExecutors.
Definition at line 44 of file TrainableExecutors.cc.
{ return entryExecutor()->getInputTensors().size(); }
References entryExecutor(), and onert::exec::train::TrainableExecutor::getInputTensors().
operator=() [1/2]
TrainableExecutors & onert::exec::train::TrainableExecutors::operator= (const TrainableExecutors &) delete
operator=() [2/2]
TrainableExecutors & onert::exec::train::TrainableExecutors::operator= (TrainableExecutors &&) default
outputInfo()
const ir::OperandInfo & onert::exec::train::TrainableExecutors::outputInfo (const ir::IOIndex & index) const override virtual
Return NN package output tensor info.
Parameters
[in] index Output index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 56 of file TrainableExecutors.cc.
{
  return entryExecutor()->getOutputTensors().at(index.value())->orig_info();
}
References entryExecutor(), and onert::exec::train::TrainableExecutor::getOutputTensors().
outputSize()
uint32_t onert::exec::train::TrainableExecutors::outputSize () const override virtual
Return executor set's number of output.
Returns
Number of output
Implements onert::exec::IExecutors.
Definition at line 46 of file TrainableExecutors.cc.
{
  return entryExecutor()->getOutputTensors().size();
}
References entryExecutor(), and onert::exec::train::TrainableExecutor::getOutputTensors().
train()
void onert::exec::train::TrainableExecutors::train (const IODescription & desc, uint32_t training_step)
Train.
Parameters
desc IO information
training_step The number of iterations of an training process. In other words, the number of gradient update.
Definition at line 70 of file TrainableExecutors.cc.
{
  if (_executors.size() > 1)
    throw std::runtime_error("TrainableExecutors does not support multiple executors yet");
  entryExecutor()->forward(desc, true);
  entryExecutor()->backward(desc, training_step);
  // TODO Support multple executors
}
References onert::exec::train::TrainableExecutor::backward(), entryExecutor(), and onert::exec::train::TrainableExecutor::forward().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/train/TrainableExecutors.h
runtime/onert/core/src/exec/train/TrainableExecutors.cc