ONE - On-device Neural Engine: onert::backend::cpu::ops::SelectLayer Class Reference
onert::backend::cpu::ops::SelectLayer Class Reference
#include <SelectLayer.h>
Public Member Functions
SelectLayer ()
void configure (const IPortableTensor *cond, const IPortableTensor *input_true, const IPortableTensor *input_false, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file SelectLayer.h.
Constructor & Destructor Documentation
SelectLayer()
onert::backend::cpu::ops::SelectLayer::SelectLayer ()
Definition at line 32 of file SelectLayer.cc.
  : _cond(nullptr), _input_true(nullptr), _input_false(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::SelectLayer::configure (const IPortableTensor * cond, const IPortableTensor * input_true, const IPortableTensor * input_false, IPortableTensor * output)
Definition at line 38 of file SelectLayer.cc.
{
  _cond = cond;
  _input_true = input_true;
  _input_false = input_false;
  _output = output;
}
run()
void onert::backend::cpu::ops::SelectLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 47 of file SelectLayer.cc.
{
#define KERNEL_SELECT(type, op)                                                     \
  nnfw::cker::op(getShape(_cond), getBuffer<uint8_t>(_cond), getShape(_input_true), \
                 getBuffer<type>(_input_true), getShape(_input_false),              \
                 getBuffer<type>(_input_false), getShape(_output), getBuffer<type>(_output));
#define KERNEL_SWITCH(type, op)                                  \
  switch (type)                                                  \
  {                                                              \
    break;                                                       \
    case OperandType::FLOAT32:                                   \
      KERNEL_SELECT(float, op);                                  \
      break;                                                     \
    default:                                                     \
      throw std::runtime_error{"Select: unsupported data type"}; \
  }
  auto input_type = _input_true->data_type();
  bool require_broadcast =
    !HaveSameShapes(_input_true, _cond) || !HaveSameShapes(_input_false, _cond);
  bool rank_one_select = ((_input_true->getShape().rank() == 1) && !require_broadcast);
  if (rank_one_select)
  {
    KERNEL_SWITCH(input_type, RankOneSelect);
  }
  else if (require_broadcast)
  {
    KERNEL_SWITCH(input_type, BroadcastSelect4DSlow);
  }
  else
  {
    KERNEL_SWITCH(input_type, Select);
  }
}
References onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), onert::backend::cpu::ops::HaveSameShapes(), and KERNEL_SWITCH.
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/SelectLayer.h
runtime/onert/backend/cpu/ops/SelectLayer.cc