ONE - On-device Neural Engine: coco::KernelObject Class Reference
coco::KernelObject Class Reference final
Convolution Kernel (in CNN) values.
#include <KernelObject.h>
Public Member Functions
KernelObject ()=default
KernelObject (const nncc::core::ADT::kernel::Shape &shape)
virtual ~KernelObject ()
Object::Kind kind (void) const override
KernelObject * asKernel (void) override
const KernelObject * asKernel (void) const override
const nncc::core::ADT::kernel::Shape & shape (void) const
ElemID at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const
const KernelLayout * layout (void) const
void layout (std::unique_ptr< KernelLayout > &&l)
Public Member Functions inherited from coco::Object
Object ()
virtual ~Object ()=default
virtual Kind kind (void) const
coco::Bag * bag (void) const
void bag (coco::Bag *bag)
virtual FeatureObject * asFeature (void)
virtual const FeatureObject * asFeature (void) const
virtual KernelObject * asKernel (void)
virtual const KernelObject * asKernel (void) const
Def * def (void) const
const UseSet * uses (void) const
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Additional Inherited Members
Public Types inherited from coco::Object
enum class Kind { Unknown , Feature , Kernel }
using ConsumerSet = std::set< Consumer * >
Detailed Description
Convolution Kernel (in CNN) values.
Definition at line 33 of file KernelObject.h.
Constructor & Destructor Documentation
KernelObject() [1/2]
coco::KernelObject::KernelObject () default
KernelObject() [2/2]
coco::KernelObject::KernelObject (const nncc::core::ADT::kernel::Shape & shape) explicit
Definition at line 25 of file KernelObject.cpp.
{
  _layout = KernelLayouts::Generic::create(shape);
}
References coco::KernelLayouts::Generic::create(), and shape().
~KernelObject()
coco::KernelObject::~KernelObject () virtual
Definition at line 30 of file KernelObject.cpp.
{
  // DO NOTHING
}
Member Function Documentation
asKernel() [1/2]
const KernelObject * coco::KernelObject::asKernel (void) const inline override virtual
Reimplemented from coco::Object.
Definition at line 47 of file KernelObject.h.
{ return this; }
asKernel() [2/2]
KernelObject * coco::KernelObject::asKernel (void) inline override virtual
Reimplemented from coco::Object.
Definition at line 46 of file KernelObject.h.
{ return this; }
at()
ElemID coco::KernelObject::at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const
Definition at line 37 of file KernelObject.cpp.
{
  return _layout->at(n, ch, row, col);
}
kind()
Object::Kind coco::KernelObject::kind (void) const inline override virtual
Reimplemented from coco::Object.
Definition at line 43 of file KernelObject.h.
{ return Object::Kind::Kernel; }
layout() [1/2]
void coco::KernelObject::layout (std::unique_ptr< KernelLayout > && l) inline
Definition at line 57 of file KernelObject.h.
{ _layout = std::move(l); }
layout() [2/2]
const KernelLayout * coco::KernelObject::layout (void) const inline
Definition at line 56 of file KernelObject.h.
{ return _layout.get(); }
shape()
const nncc::core::ADT::kernel::Shape & coco::KernelObject::shape (void) const
Definition at line 35 of file KernelObject.cpp.
{ return _layout->shape(); }
Referenced by dump(), and KernelObject().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/KernelObject.h
compiler/coco/core/src/IR/KernelObject.cpp