ONE - On-device Neural Engine: luci_interpreter::kernels::ResizeBilinear Class Reference
luci_interpreter::kernels::ResizeBilinear Class Reference
#include <ResizeBilinear.h>
Public Member Functions
ResizeBilinear (const Tensor *input, const Tensor *shape, Tensor *output, const ResizeBilinearParams &params)
const Tensor * input () const
const Tensor * size () const
Tensor * output () const
void configure () override
void execute () const override
ResizeBilinear (const Tensor *input, const Tensor *shape, Tensor *output, const ResizeBilinearParams &params)
const Tensor * input () const
const Tensor * size () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< ResizeBilinearParams >
const ResizeBilinearParams & params () const
const ResizeBilinearParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< ResizeBilinearParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ResizeBilinearParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ResizeBilinearParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< ResizeBilinearParams >
const ResizeBilinearParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file ResizeBilinear.h.
Constructor & Destructor Documentation
ResizeBilinear() [1/2]
luci_interpreter::kernels::ResizeBilinear::ResizeBilinear (const Tensor * input, const Tensor * shape, Tensor * output, const ResizeBilinearParams & params)
Definition at line 29 of file ResizeBilinear.cpp.
  : KernelWithParams<ResizeBilinearParams>({input, size}, {output}, params)
{
}
References input(), and size().
ResizeBilinear() [2/2]
luci_interpreter::kernels::ResizeBilinear::ResizeBilinear (const Tensor * input, const Tensor * shape, Tensor * output, const ResizeBilinearParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::ResizeBilinear::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 35 of file ResizeBilinear.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() == 4);
  LUCI_INTERPRETER_CHECK(size()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(size()->element_type() == DataType::S32);
  if (params().half_pixel_centers && params().align_corners)
    throw std::runtime_error("If half_pixel_centers is True, align_corners must be False.");
  LUCI_INTERPRETER_CHECK(size()->shape().dim(0) == 2);
  Shape output_shape(4);
  output_shape.dim(0) = input()->shape().dim(0);
  output_shape.dim(1) = getTensorData<int32_t>(size())[0];
  output_shape.dim(2) = getTensorData<int32_t>(size())[1];
  output_shape.dim(3) = input()->shape().dim(3);
  output()->resize(output_shape);
}
References luci_interpreter::Shape::dim(), input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::KernelWithParams< ResizeBilinearParams >::params(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), and size().
configure() [2/2]
void luci_interpreter::kernels::ResizeBilinear::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::ResizeBilinear::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 51 of file ResizeBilinear.cpp.
{
  tflite::ResizeBilinearParams op_params{};
  op_params.align_corners = params().align_corners;
  op_params.half_pixel_centers = params().half_pixel_centers;
  switch (output()->element_type())
  {
    case DataType::FLOAT32:
      luci_interpreter_pal::ResizeBilinear(
        op_params, getTensorShape(input()), getTensorData<float>(input()), getTensorShape(size()),
        getTensorData<int32_t>(size()), getTensorShape(output()), getTensorData<float>(output()));
      break;
    case DataType::U8:
      luci_interpreter_pal::ResizeBilinear(
        op_params, getTensorShape(input()), getTensorData<uint8_t>(input()), getTensorShape(size()),
        getTensorData<int32_t>(size()), getTensorShape(output()), getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::ResizeBilinearParams::align_corners, luci_interpreter::kernels::getTensorShape(), luci_interpreter::ResizeBilinearParams::half_pixel_centers, input(), output(), luci_interpreter::KernelWithParams< ResizeBilinearParams >::params(), and size().
execute() [2/2]
void luci_interpreter::kernels::ResizeBilinear::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::ResizeBilinear::input () const inline
Definition at line 34 of file ResizeBilinear.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ResizeBilinear().
input() [2/2]
const Tensor * luci_interpreter::kernels::ResizeBilinear::input () const inline
Definition at line 34 of file ResizeBilinear.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::ResizeBilinear::output () const inline
Definition at line 36 of file ResizeBilinear.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::ResizeBilinear::output () const inline
Definition at line 36 of file ResizeBilinear.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
size() [1/2]
const Tensor * luci_interpreter::kernels::ResizeBilinear::size () const inline
Definition at line 35 of file ResizeBilinear.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ResizeBilinear().
size() [2/2]
const Tensor * luci_interpreter::kernels::ResizeBilinear::size () const inline
Definition at line 35 of file ResizeBilinear.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/ResizeBilinear.h
onert-micro/luci-interpreter/src/kernels/ResizeBilinear.h
compiler/luci-interpreter/src/kernels/ResizeBilinear.cpp
onert-micro/luci-interpreter/src/kernels/ResizeBilinear.cpp