ONE - On-device Neural Engine: coco::Dep Class Reference
coco::Dep Class Reference final
A Dep represents the edge between a Bag and its dependent Object.
#include <Dep.h>
Public Member Functions
Dep ()=default
Dep (const Dep &)=delete
Dep (Dep &&)=delete
~Dep ()
Bag * bag (void) const
void bag (Bag *)
Object * object (void) const
void object (Object *object)
Detailed Description
A Dep represents the edge between a Bag and its dependent Object.
WARNING A Dep will update dependent Object set (stored BagInfo) only when users properly initialize object and link values.
Definition at line 32 of file Dep.h.
Constructor & Destructor Documentation
Dep() [1/3]
coco::Dep::Dep () default
Dep() [2/3]
coco::Dep::Dep (const Dep &) delete
Dep() [3/3]
coco::Dep::Dep (Dep &&) delete
~Dep()
coco::Dep::~Dep ()
Definition at line 25 of file Dep.cpp.
{ bag(nullptr); }
References bag().
Member Function Documentation
bag() [1/2]
void coco::Dep::bag (Bag * bag)
Definition at line 27 of file Dep.cpp.
{
  if (_bag != nullptr)
  {
    // Remove bag <-> dep link
    assert(_bag->deps()->find(this) != _bag->deps()->end());
    _bag->mutable_deps()->erase(this);
    // Reset _bag
    _bag = nullptr;
  }
  assert(_bag == nullptr);
  if (bag != nullptr)
  {
    // Set _bag
    _bag = bag;
    // Create bag <-> dep link
    _bag->mutable_deps()->insert(this);
  }
  assert(_bag == bag);
}
References bag(), and coco::Bag::deps().
bag() [2/2]
Bag * coco::Dep::bag (void) const inline
Definition at line 45 of file Dep.h.
{ return _bag; }
Referenced by bag(), coco::Object::bag(), and ~Dep().
object() [1/2]
void coco::Dep::object (Object * object) inline
Definition at line 50 of file Dep.h.
{ _object = object; }
References object().
Referenced by object().
object() [2/2]
Object * coco::Dep::object (void) const inline
Definition at line 49 of file Dep.h.
{ return _object; }
Referenced by coco::Object::Object().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Dep.h
compiler/coco/core/src/IR/Dep.cpp