ONE - On-device Neural Engine: onert::backend::cpu::ops::L2NormLayer Class Reference
onert::backend::cpu::ops::L2NormLayer Class Reference
#include <L2NormLayer.h>
Public Member Functions
L2NormLayer ()
void configure (const IPortableTensor *_input, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 32 of file L2NormLayer.h.
Constructor & Destructor Documentation
L2NormLayer()
onert::backend::cpu::ops::L2NormLayer::L2NormLayer () inline
Definition at line 35 of file L2NormLayer.h.
                : _input(nullptr), _output(nullptr)
  {
    // Nothing
  }
Member Function Documentation
configure()
void onert::backend::cpu::ops::L2NormLayer::configure (const IPortableTensor * _input, IPortableTensor * output)
Definition at line 33 of file L2NormLayer.cc.
{
  assert(input != nullptr);
  assert(output != nullptr);
  _input = input;
  _output = output;
}
run()
void onert::backend::cpu::ops::L2NormLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 42 of file L2NormLayer.cc.
{
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
      nnfw::cker::L2NormalizeFloat32(getShape(_input), getBuffer<float>(_input), getShape(_output),
                                     getBuffer<float>(_output));
      break;
    case OperandType::QUANT_UINT8_ASYMM:
    {
      nnfw::cker::L2NormParams params;
      assert(_input->data_zero_point() == 128);
      params.input_zero_point = _input->data_zero_point();
      nnfw::cker::L2NormalizeQuant8(params, getShape(_input), getBuffer<uint8_t>(_input),
                                    getShape(_output), getBuffer<uint8_t>(_output));
    }
    break;
    default:
      throw std::runtime_error{"L2Norm: Unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::cpu::ops::getShape(), nnfw::cker::L2NormParams::input_zero_point, nnfw::cker::L2NormalizeFloat32(), and nnfw::cker::L2NormalizeQuant8().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/L2NormLayer.h
runtime/onert/backend/cpu/ops/L2NormLayer.cc