ONE - On-device Neural Engine: onert::compiler::pass::ConstantInsertionPass Class Reference
onert::compiler::pass::ConstantInsertionPass Class Reference
#include <ConstantInsertionPass.h>
Public Member Functions
std::string id () final
Returns string id for this pass. Same with class name.
void callback (const ir::OperationIndex &index, ir::Operation &node) final
Be called for all nodes of graph.
LoweredOperationPass (LoweredGraph &lowered_graph)
Public Member Functions inherited from onert::compiler::pass::LoweredOperationPass
LoweredOperationPass (LoweredGraph &lowered_graph)
virtual ~LoweredOperationPass ()=default
std::string id () override=0
Returns string id for this pass. Same with class name.
void callback (const ir::OperationIndex &i, ir::Operation &o) override=0
Be called for all nodes of graph.
Public Member Functions inherited from onert::compiler::pass::OperationPass
virtual ~OperationPass ()=default
std::string id () override=0
Returns string id for this pass. Same with class name.
virtual void callback (const ir::OperationIndex &index, ir::Operation &node)=0
Be called for all nodes of graph.
void run () final
Run the pass.
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::LoweredOperationPass
LoweredGraph & _lowered_graph
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Definition at line 33 of file ConstantInsertionPass.h.
Member Function Documentation
callback()
void onert::compiler::pass::ConstantInsertionPass::callback (const ir::OperationIndex & index, ir::Operation & node) final virtual
Be called for all nodes of graph.
Parameters
index is the index of a node in graph
node is the node in graph
Implements onert::compiler::pass::LoweredOperationPass.
Definition at line 31 of file ConstantInsertionPass.cc.
{
  const auto op_lower_info = _lowered_graph.lower_info().operation.getRawPtr(node_index);
  const auto backend = op_lower_info->backend();
  const auto layout = op_lower_info->layout();
  const auto factor = PermuteFactor{backend, layout};
  for (const auto input : node.getInputs() | ir::Remove::DUPLICATED | ir::Remove::UNDEFINED)
  {
    auto &object = _graph.operands().at(input);
    if (object.isConstant())
    {
      const auto key = ReplaceKey{input, factor};
      if (_replace_operands_map.count(key) == 0)
      {
        ir::Operand new_object(object);
        new_object.clearDefUse();
        const auto new_index = _graph.operands().emplace(new_object);
        _replace_operands_map[key] = new_index;
      }
      const auto replaced_input = _replace_operands_map[key];
      // Update the same inputs of a node at once because inputs of an operation have the same
      // PermuteFactor
      node.replaceInputs(input, replaced_input);
      // Update operand
      auto &replaced_object = _graph.operands().at(replaced_input);
      replaced_object.insertUse(node_index);
      VERBOSE(ConstInsertPass) << "New operand " << replaced_input << " added(copy of " << input
                               << ") for " << factor << std::endl;
      // Remove this node from uses of origin operand
      // Constant operand has no def.
      assert(!object.getDef().valid());
      object.removeUse(node_index);
      // Remove origin operand
      if (object.getUses().size() == 0)
      {
        _graph.removeOperand(input);
        VERBOSE(ConstInsertPass) << "Original operand " << input << " removed - no uses"
                                 << std::endl;
      }
    }
  }
  // Now this runtime does not support the node making output as constant
  for (const auto &output : node.getOutputs() | ir::Remove::DUPLICATED | ir::Remove::UNDEFINED)
  {
    UNUSED_RELEASE(output);
    assert(!_graph.operands().at(output).isConstant());
  }
}
References onert::compiler::pass::Pass::_graph, onert::compiler::pass::LoweredOperationPass::_lowered_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::Operand::clearDefUse(), onert::ir::DUPLICATED, onert::util::ObjectManager< Index, Object >::emplace(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::compiler::LoweredGraph::lower_info(), onert::ir::Graph::operands(), onert::compiler::GraphLowerInfo::operation, onert::ir::Graph::removeOperand(), onert::ir::Operation::replaceInputs(), onert::ir::UNDEFINED, UNUSED_RELEASE, and VERBOSE.
id()
std::string onert::compiler::pass::ConstantInsertionPass::id () inline final virtual
Returns string id for this pass. Same with class name.
Returns
string id
Implements onert::compiler::pass::LoweredOperationPass.
Definition at line 39 of file ConstantInsertionPass.h.
{ return "ConstantInsertionPass"; }
LoweredOperationPass()
onert::compiler::pass::LoweredOperationPass::LoweredOperationPass (LoweredGraph & lowered_graph) inline
Definition at line 33 of file LoweredOperationPass.h.
    : OperationPass{lowered_graph.graph()}, _lowered_graph{lowered_graph}
  {
    // DO NOTHING
  }
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/ConstantInsertionPass.h
runtime/onert/core/src/compiler/pass/ConstantInsertionPass.cc