ONE - On-device Neural Engine: arm_compute::CLReduceOperationKernel Class Reference
arm_compute::CLReduceOperationKernel Class Reference
Class to define interface for the reduce operation kernel.
#include <CLReduceOperationKernel.h>
Public Member Functions
CLReduceOperationKernel ()
Default constructor.
CLReduceOperationKernel (const CLReduceOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReduceOperationKernel & operator= (const CLReduceOperationKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReduceOperationKernel (CLReduceOperationKernel &&)=default
Allow instances of this class to be moved.
CLReduceOperationKernel & operator= (CLReduceOperationKernel &&)=default
Allow instances of this class to be moved.
~CLReduceOperationKernel ()=default
Default destructor.
void configure (const ICLTensor *input, ICLTensor *output, const uint32_t axis, ReductionOperation op)
Set the input and output tensors.
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const uint32_t axis, ReductionOperation op)
Static function to check if given info will lead to a valid configuration of CLReduceOperationKernel.
Detailed Description
Class to define interface for the reduce operation kernel.
Definition at line 60 of file CLReduceOperationKernel.h.
Constructor & Destructor Documentation
CLReduceOperationKernel() [1/3]
CLReduceOperationKernel::CLReduceOperationKernel ()
Default constructor.
Definition at line 101 of file CLReduceOperationKernel.cpp.
: _input(nullptr), _output(nullptr), _axis() {}
CLReduceOperationKernel() [2/3]
arm_compute::CLReduceOperationKernel::CLReduceOperationKernel (const CLReduceOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLReduceOperationKernel() [3/3]
arm_compute::CLReduceOperationKernel::CLReduceOperationKernel (CLReduceOperationKernel &&) default
Allow instances of this class to be moved.
~CLReduceOperationKernel()
arm_compute::CLReduceOperationKernel::~CLReduceOperationKernel () default
Default destructor.
References validate().
Member Function Documentation
configure()
void CLReduceOperationKernel::configure (const ICLTensor * input, ICLTensor * output, const uint32_t axis, ReductionOperation op)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: U8/S32/F32.
[out] output Destination tensor. Data types supported: Same as input. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce.
[in] op Reduce operation to perform.
Returns
N/A
Definition at line 103 of file CLReduceOperationKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info(), axis, op));
  _input = input;
  _output = output;
  _axis = axis;
  std::unique_ptr<ITensorInfo> output_info = output->info()->clone();
  output_info->set_tensor_shape(inferOutputShape(input->info()->tensor_shape(), axis));
  // Construct kernel name
  std::string kernel_name;
  int op_code = 0;
  if (op == ReductionOperation::MAX)
  {
    kernel_name = "reduce_min_max";
    op_code = 1;
  }
  else if (op == ReductionOperation::MIN)
  {
    kernel_name = "reduce_min_max";
    op_code = 2;
  }
  else if (op == ReductionOperation::SUM)
  {
    kernel_name = "reduce_sum_mean";
    op_code = 3;
  }
  else if (op == ReductionOperation::MEAN_SUM)
  {
    kernel_name = "reduce_sum_mean";
    op_code = 4;
  }
  else
    throw std::runtime_error("Operation not supported, yet");
  // Set kernel build options
  std::set<std::string> build_opts;
  build_opts.emplace("-DDATA_TYPE=" + get_cl_type_from_data_type(output_info->data_type()));
  build_opts.emplace("-DDEPTH_OUT=" + support::cpp11::to_string(output_info->dimension(2)));
  build_opts.emplace("-DOP_CODE=" + support::cpp11::to_string(op_code));
  // Create kernel
  _kernel =
    static_cast<cl::Kernel>(CLKernelLibraryEx::get().create_kernel(kernel_name, build_opts));
  // Configure  kernel window
  Window win = calculate_max_window(*output_info, Steps());
  Coordinates coord;
  coord.set_num_dimensions(output_info->num_dimensions());
  output->info()->set_valid_region(ValidRegion(coord, output_info->tensor_shape()));
  ICLKernel::configure_internal(win);
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
operator=() [1/2]
CLReduceOperationKernel & arm_compute::CLReduceOperationKernel::operator= (CLReduceOperationKernel &&) default
Allow instances of this class to be moved.
operator=() [2/2]
CLReduceOperationKernel & arm_compute::CLReduceOperationKernel::operator= (const CLReduceOperationKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void CLReduceOperationKernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 172 of file CLReduceOperationKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
  const TensorShape &shape_in = _input->info()->tensor_shape();
  unsigned int idx = 2 * num_arguments_per_4D_tensor(); // Skip the input and output parameters
  _kernel.setArg<cl_int>(idx++, _axis);
  _kernel.setArg<cl_int>(idx++, shape_in[_axis]);
  // Support dimensions up to 4
  Window slice_out = window.collapse(ICLKernel::window(), 2, 4);
  // Setup input slice
  Window slice_in(slice_out);
  slice_in.set(Window::DimX, Window::Dimension(0, 0, 0));
  slice_in.set(Window::DimY, Window::Dimension(0, 0, 0));
  slice_in.set(Window::DimZ, Window::Dimension(0, 0, 0));
  slice_in.set(3, Window::Dimension(0, 0, 0));
  // Copy output's shape in order to use for recovering at end of this method
  // TODO Remove changing and recovering output's shape if it is guaranteed that the axis positions
  // of input and output are the same
  const TensorShape shape_out = _output->info()->tensor_shape();
  _output->info()->set_tensor_shape(inferOutputShape(shape_in, _axis));
  idx = 0;
  add_4D_tensor_argument(idx, _input, slice_in);
  add_4D_tensor_argument(idx, _output, slice_out);
  enqueue(queue, *this, slice_out, lws_hint());
  // Recover output's shape of output tensor
  _output->info()->set_tensor_shape(shape_out);
}
validate()
Status CLReduceOperationKernel::validate (const ITensorInfo * input, const ITensorInfo * output, const uint32_t axis, ReductionOperation op) static
Static function to check if given info will lead to a valid configuration of CLReduceOperationKernel.
Parameters
[in] input Source tensor info. Data types supported: U8/S32/F32.
[in] output Destination tensor info. Data types supported: Same as input. Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce.
[in] op Reduce operation to perform.
Returns
a status
Definition at line 163 of file CLReduceOperationKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, axis, op));
  return Status{};
}
Referenced by arm_compute::CLReduceOperation::validate(), and ~CLReduceOperationKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLReduceOperationKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLReduceOperationKernel.cpp