ONE - On-device Neural Engine: nnkit::support::moco::tf::OutputTensorContext Class Reference
nnkit::support::moco::tf::OutputTensorContext Class Reference final
Class for the context of output tensors.
#include <OutputTensorContext.h>
Public Member Functions
OutputTensorContext (const ParsedTensors &parsed_tensors, locomotiv::Session *sess)
OutputTensorContext (const OutputTensorContext &)=delete
OutputTensorContext (OutputTensorContext &&)=delete
void getMutableFloatTensor (uint32_t n, const nnkit::TensorContext::TypedAccessor< float > &f) override
void getConstFloatTensor (uint32_t n, const nnkit::TensorContext::TypedReader< float > &f) const override
Public Member Functions inherited from nnkit::support::moco::tf::TensorContext
TensorContext (const ParsedTensors &tensors)
TensorContext (const TensorContext &)=delete
TensorContext (TensorContext &&)=delete
uint32_t size (void) const override
std::string name (uint32_t n) const override
nncc::core::ADT::tensor::Shape shape (uint32_t n) const override
bool isFloatTensor (uint32_t n) const override
virtual void getMutableFloatTensor (uint32_t n, const nnkit::TensorContext::TypedAccessor< float > &f)=0
virtual void getConstFloatTensor (uint32_t n, const nnkit::TensorContext::TypedReader< float > &f) const =0
Public Member Functions inherited from nnkit::TensorContext
virtual ~TensorContext ()=default
virtual uint32_t size (void) const =0
virtual std::string name (uint32_t n) const =0
virtual nncc::core::ADT::tensor::Shape shape (uint32_t n) const =0
virtual bool isFloatTensor (uint32_t n) const
virtual void getMutableFloatTensor (uint32_t n, const TypedAccessor< float > &cb)
virtual void getConstFloatTensor (uint32_t n, const TypedReader< float > &cb) const
virtual bool isS32Tensor (uint32_t n) const
virtual void getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > &cb)
virtual void getConstS32Tensor (uint32_t n, const TypedReader< int32_t > &cb) const
Additional Inherited Members
Public Types inherited from nnkit::TensorContext
template<typename T >
using TypedReader = std::function< void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader< T > &)>
template<typename T >
using TypedAccessor = std::function< void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor< T > &)>
Detailed Description
Class for the context of output tensors.
Definition at line 42 of file OutputTensorContext.h.
Constructor & Destructor Documentation
OutputTensorContext() [1/3]
nnkit::support::moco::tf::OutputTensorContext::OutputTensorContext (const ParsedTensors & parsed_tensors, locomotiv::Session * sess) inline
Definition at line 45 of file OutputTensorContext.h.
    : TensorContext(parsed_tensors), _sess(sess)
  { /* empty */
  }
OutputTensorContext() [2/3]
nnkit::support::moco::tf::OutputTensorContext::OutputTensorContext (const OutputTensorContext &) delete
OutputTensorContext() [3/3]
nnkit::support::moco::tf::OutputTensorContext::OutputTensorContext (OutputTensorContext &&) delete
Member Function Documentation
getConstFloatTensor()
void nnkit::support::moco::tf::OutputTensorContext::getConstFloatTensor (uint32_t n, const nnkit::TensorContext::TypedReader< float > & f) const override virtual
Implements nnkit::support::moco::tf::TensorContext.
Definition at line 32 of file OutputTensorContext.cpp.
{ // for output
  using nncc::core::ADT::tensor::LexicalLayout;
  using nncc::core::ADT::tensor::make_overlay;
  auto *buf = const_cast<float *>(_sess->get_output(n)->as_f32_bufptr()->base());
  auto overlay = make_overlay<float, LexicalLayout>(shape(n), buf);
  f(*this, n, overlay);
}
References locomotiv::NodeData::as_f32_bufptr(), locomotiv::Session::get_output(), nncc::core::ADT::tensor::make_overlay(), and nnkit::support::moco::tf::TensorContext::shape().
getMutableFloatTensor()
void nnkit::support::moco::tf::OutputTensorContext::getMutableFloatTensor (uint32_t n, const nnkit::TensorContext::TypedAccessor< float > & f) inline override virtual
Implements nnkit::support::moco::tf::TensorContext.
Definition at line 54 of file OutputTensorContext.h.
  {
    throw std::runtime_error("This method is for input and should not be called");
  }
The documentation for this class was generated from the following files:
compiler/nnkit-mocotf/support/src/OutputTensorContext.h
compiler/nnkit-mocotf/support/src/OutputTensorContext.cpp