ONE - On-device Neural Engine: nest::Schedule Class Reference
nest::Schedule Class Reference final
#include <Schedule.h>
Public Member Functions
Schedule (const Module &)
const VarContext & var (void) const
const DomainContext & domain (void) const
const Block & block (void) const
const Ret & ret (void) const
Var at (const Level &) const
Level level (const Var &) const
Detailed Description
Definition at line 28 of file Schedule.h.
Constructor & Destructor Documentation
Schedule()
nest::Schedule::Schedule (const Module & module) explicit
Definition at line 25 of file Schedule.cpp.
                                       : _module{module}
{
  // NOTE This implementation assumes that VarContext sequentially assigns VarID
  for (uint32_t n = 0; n < _module.var().count(); ++n)
  {
    _level.emplace_back(VarID{n});
  }
  assert(_level.size() == _module.var().count());
}
References nest::VarContext::count(), and nest::Module::var().
Member Function Documentation
at()
Var nest::Schedule::at (const Level & lv) const
Definition at line 36 of file Schedule.cpp.
{ return Var{_level.at(lv.value())}; }
References nest::Level::value().
block()
const Block & nest::Schedule::block (void) const inline
Definition at line 36 of file Schedule.h.
{ return _module.block(); }
References nest::Module::block().
domain()
const DomainContext & nest::Schedule::domain (void) const inline
Definition at line 35 of file Schedule.h.
{ return _module.domain(); }
References nest::Module::domain().
level()
Level nest::Schedule::level (const Var & var) const
Definition at line 38 of file Schedule.cpp.
{
  for (uint32_t lv = 0; lv < _level.size(); ++lv)
  {
    if (_level.at(lv) == var.id())
    {
      return Level{lv};
    }
  }
  throw std::invalid_argument{"var"};
}
References var().
ret()
const Ret & nest::Schedule::ret (void) const inline
Definition at line 37 of file Schedule.h.
{ return _module.ret(); }
References nest::Module::ret().
var()
const VarContext & nest::Schedule::var (void) const inline
Definition at line 34 of file Schedule.h.
{ return _module.var(); }
References nest::Module::var().
Referenced by level().
The documentation for this class was generated from the following files:
compiler/nest/core/include/nest/Schedule.h
compiler/nest/core/src/Schedule.cpp