ONE - On-device Neural Engine: luci::CloneNodeLet< CN::GHIJ > Class Reference
luci::CloneNodeLet< CN::GHIJ > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleGather *) final
luci::CircleNode * visit (const luci::CircleGatherNd *) final
luci::CircleNode * visit (const luci::CircleGreater *) final
luci::CircleNode * visit (const luci::CircleGreaterEqual *) final
luci::CircleNode * visit (const luci::CircleIf *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 97 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::GHIJ >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 100 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleGather * node) final
Definition at line 22 of file CircleGather.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleGather>();
  if (cloned != nullptr)
    cloned->axis(node->axis());
  return cloned;
}
References luci::CircleGather::axis().
visit() [2/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleGatherNd *) final
Definition at line 22 of file CircleGatherNd.cpp.
{
  return _graph->nodes()->create<luci::CircleGatherNd>();
}
visit() [3/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleGreater *) final
Definition at line 22 of file CircleGreater.cpp.
{
  return _graph->nodes()->create<luci::CircleGreater>();
}
visit() [4/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleGreaterEqual *) final
Definition at line 22 of file CircleGreaterEqual.cpp.
{
  return _graph->nodes()->create<luci::CircleGreaterEqual>();
}
visit() [5/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleIf * node) final
Definition at line 22 of file CircleIf.cpp.
{
  auto ic = node->input_count();
  auto oc = node->output_count();
  return _graph->nodes()->create<luci::CircleIf>(ic, oc);
}
References luci::CircleIf::input_count(), and luci::CircleIf::output_count().
visit() [6/6]
luci::CircleNode * luci::CloneNodeLet< CN::GHIJ >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 109 of file CircleCloneNode.h.
{ return nullptr; }
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::GHIJ >::_graph = nullptr protected
Definition at line 112 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleGather.cpp
compiler/luci/service/src/Nodes/CircleGatherNd.cpp
compiler/luci/service/src/Nodes/CircleGreater.cpp
compiler/luci/service/src/Nodes/CircleGreaterEqual.cpp
compiler/luci/service/src/Nodes/CircleIf.cpp