ONE - On-device Neural Engine: onert::backend::gpu_cl::ClConstantInitializer Class Reference
onert::backend::gpu_cl::ClConstantInitializer Class Reference
#include <ClConstantInitializer.h>
Public Types
using Initializer = std::function< void(const ir::Operand &, backend::ITensor &)>
Public Member Functions
void run ()
ClConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void registerDefaultInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerCopyInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerPermuteInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void setLayout (ir::Layout layout)
bool exist (const ir::OperandIndex &ind)
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Protected Member Functions
void copyInputInitialize (const ir::Operation &node, uint32_t index)
void permuteInputInitialize (const ir::Operation &node, uint32_t index)
Protected Attributes
const ir::Operands & _operands
std::shared_ptr< ITensorRegistry > _tensor_reg
std::unordered_map< ir::OperandIndex, Initializer > _init_map
ir::Layout _current_layout
Detailed Description
Definition at line 83 of file ClConstantInitializer.h.
Member Typedef Documentation
Initializer
using onert::backend::gpu_cl::ClConstantInitializer::Initializer = std::function<void(const ir::Operand &, backend::ITensor &)>
Definition at line 108 of file ClConstantInitializer.h.
Constructor & Destructor Documentation
ClConstantInitializer()
onert::backend::gpu_cl::ClConstantInitializer::ClConstantInitializer (const ir::Operands & operands, const std::shared_ptr< ITensorRegistry > & tensor_reg)
Definition at line 26 of file ClConstantInitializer.cc.
  : _operands{operands}, _tensor_reg{tensor_reg}, _current_layout{ir::Layout::UNKNOWN}
{
  // DO NOTHING
}
Member Function Documentation
copyInputInitialize()
void onert::backend::gpu_cl::ClConstantInitializer::copyInputInitialize (const ir::Operation & node, uint32_t index) protected
Definition at line 33 of file ClConstantInitializer.cc.
{
  assert(node.getInputs().size() > index);
  const auto &input_index = node.getInputs().at(index);
  if (input_index.valid())
  {
    const auto &input_obj = _operands.at(input_index);
    registerCopyInitializer(input_index, input_obj);
  }
}
References _operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), registerCopyInitializer(), and onert::ir::OperandIndexSequence::size().
exist()
bool onert::backend::gpu_cl::ClConstantInitializer::exist (const ir::OperandIndex & ind) inline
Definition at line 120 of file ClConstantInitializer.h.
{ return _init_map.find(ind) != _init_map.end(); }
permuteInputInitialize()
void onert::backend::gpu_cl::ClConstantInitializer::permuteInputInitialize (const ir::Operation & node, uint32_t index) protected
Definition at line 45 of file ClConstantInitializer.cc.
{
  assert(node.getInputs().size() > index);
  const auto &input_index = node.getInputs().at(index);
  const auto &input_obj = _operands.at(input_index);
  registerPermuteInitializer(input_index, input_obj);
}
References _operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), registerPermuteInitializer(), and onert::ir::OperandIndexSequence::size().
registerCopyInitializer()
void onert::backend::gpu_cl::ClConstantInitializer::registerCopyInitializer (const ir::OperandIndex & index, const ir::Operand & obj)
Definition at line 57 of file ClConstantInitializer.cc.
{
  // For only CONSTANTS
  // TODO Add to check if tensor has been allocated
  if (!obj.isConstant())
    return;
  const auto type = obj.typeInfo().type();
  using ir::DataType;
  switch (type)
  {
    case DataType::FLOAT32:
      _init_map[index] = copyInit<float>;
      break;
    default:
      throw std::runtime_error("Not supported, yet");
      break;
  }
}
References _init_map.
Referenced by copyInputInitialize().
registerDefaultInitializer()
void onert::backend::gpu_cl::ClConstantInitializer::registerDefaultInitializer (const ir::OperandIndex & index, const ir::Operand & obj) inline
Definition at line 111 of file ClConstantInitializer.h.
  {
    registerPermuteInitializer(index, obj);
  }
registerPermuteInitializer()
void onert::backend::gpu_cl::ClConstantInitializer::registerPermuteInitializer (const ir::OperandIndex & index, const ir::Operand & obj)
Definition at line 79 of file ClConstantInitializer.cc.
{
  // For only CONSTANTS
  // TODO Add to check if tensor has been allocated
  if (!obj.isConstant())
    return;
  const auto type = obj.typeInfo().type();
  using ir::DataType;
  using namespace std::placeholders;
  switch (type)
  {
    case DataType::FLOAT32:
      _init_map[index] = std::bind(permuteInit<float>, _1, _2, _current_layout);
      break;
    case DataType::INT32:
      _init_map[index] = std::bind(permuteInit<int32_t>, _1, _2, _current_layout);
      break;
    default:
      throw std::runtime_error("Not supported, yet");
      break;
  }
}
References _current_layout, and _init_map.
Referenced by permuteInputInitialize().
run()
void onert::backend::gpu_cl::ClConstantInitializer::run () inline
Definition at line 86 of file ClConstantInitializer.h.
  {
    assert(_tensor_reg);
    for (const auto &it : _init_map)
    {
      const auto &ind = it.first;
      const auto &fn = it.second;
      const auto &model_obj = _operands.at(ind);
      auto tensor_obj = _tensor_reg->getNativeITensor(ind);
      assert(tensor_obj != nullptr);
      fn(model_obj, *tensor_obj);
      VERBOSE(FillOperandData) << "Fill data for operand " << ind << std::endl;
    }
    _init_map.clear();
  }
References VERBOSE.
setLayout()
void onert::backend::gpu_cl::ClConstantInitializer::setLayout (ir::Layout layout) inline
Definition at line 119 of file ClConstantInitializer.h.
{ _current_layout = layout; }
Field Documentation
_current_layout
ir::Layout onert::backend::gpu_cl::ClConstantInitializer::_current_layout protected
Definition at line 131 of file ClConstantInitializer.h.
Referenced by registerPermuteInitializer().
_init_map
std::unordered_map<ir::OperandIndex, Initializer> onert::backend::gpu_cl::ClConstantInitializer::_init_map protected
Definition at line 130 of file ClConstantInitializer.h.
Referenced by registerCopyInitializer(), and registerPermuteInitializer().
_operands
const ir::Operands& onert::backend::gpu_cl::ClConstantInitializer::_operands protected
Definition at line 128 of file ClConstantInitializer.h.
Referenced by copyInputInitialize(), and permuteInputInitialize().
_tensor_reg
std::shared_ptr<ITensorRegistry> onert::backend::gpu_cl::ClConstantInitializer::_tensor_reg protected
Definition at line 129 of file ClConstantInitializer.h.
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/ClConstantInitializer.h
runtime/onert/backend/gpu_cl/ClConstantInitializer.cc