ONE - On-device Neural Engine: GraphTestcase< GraphCode::FixedReshape > Class Reference
GraphTestcase< GraphCode::FixedReshape > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::Pull * pull_node = nullptr
loco::FixedReshape * reshape_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 445 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::FixedReshape >::GraphTestcase () inline
Definition at line 448 of file GraphTestcase.h.
  {
    _graph = loco::make_graph();
    auto graph_builder = make_graph_builder(_graph.get());
    pull_node = graph_builder->push<InputLayer>()->name("input")->node();
    reshape_node = graph_builder->push<FixedReshapeLayer>()->node();
    push_node = graph_builder->push<OutputLayer>()->name("output")->node();
  }
References loco::make_graph().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::FixedReshape >::graph () inline
Definition at line 460 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
pull_node
loco::Pull* GraphTestcase< GraphCode::FixedReshape >::pull_node = nullptr
Definition at line 462 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::FixedReshape >::push_node = nullptr
Definition at line 464 of file GraphTestcase.h.
reshape_node
loco::FixedReshape* GraphTestcase< GraphCode::FixedReshape >::reshape_node = nullptr
Definition at line 463 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h