ONE - On-device Neural Engine: moco::TFConv2D Class Reference
moco::TFConv2D Class Reference final
#include <TFConv2D.h>
Public Member Functions
loco::Node * input (void) const
void input (Node *node)
loco::Node * filter (void) const
void filter (Node *node)
const TFPadding & padding (void) const
void padding (const TFPadding &padding)
const TFDataLayout & data_layout (void) const
void data_layout (const TFDataLayout &data_layout)
const std::vector< int64_t > & strides (void) const
void strides (const std::vector< int64_t > &strides)
Public Member Functions inherited from moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::Conv2D >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >
loco::Use * at (unsigned n) const
Detailed Description
Definition at line 27 of file TFConv2D.h.
Member Function Documentation
data_layout() [1/2]
void moco::TFConv2D::data_layout (const TFDataLayout & data_layout) inline
Definition at line 41 of file TFConv2D.h.
{ _data_layout = data_layout; }
References data_layout().
Referenced by data_layout().
data_layout() [2/2]
const TFDataLayout & moco::TFConv2D::data_layout (void) const inline
Definition at line 40 of file TFConv2D.h.
{ return _data_layout; }
filter() [1/2]
void moco::TFConv2D::filter (Node * node) inline
Definition at line 34 of file TFConv2D.h.
{ at(1)->node(node); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >::at(), and loco::Use::node().
filter() [2/2]
loco::Node * moco::TFConv2D::filter (void) const inline
Definition at line 33 of file TFConv2D.h.
{ return at(1)->node(); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >::at(), and loco::Use::node().
input() [1/2]
void moco::TFConv2D::input (Node * node) inline
Definition at line 31 of file TFConv2D.h.
{ at(0)->node(node); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * moco::TFConv2D::input (void) const inline
Definition at line 30 of file TFConv2D.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::Conv2D > >::at(), and loco::Use::node().
padding() [1/2]
void moco::TFConv2D::padding (const TFPadding & padding) inline
Definition at line 38 of file TFConv2D.h.
{ _padding = padding; }
References padding().
Referenced by padding().
padding() [2/2]
const TFPadding & moco::TFConv2D::padding (void) const inline
Definition at line 37 of file TFConv2D.h.
{ return _padding; }
strides() [1/2]
void moco::TFConv2D::strides (const std::vector< int64_t > & strides) inline
Definition at line 44 of file TFConv2D.h.
{ _strides = strides; }
References strides().
Referenced by strides().
strides() [2/2]
const std::vector< int64_t > & moco::TFConv2D::strides (void) const inline
Definition at line 43 of file TFConv2D.h.
{ return _strides; }
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFConv2D.h