ONE - On-device Neural Engine: arm_compute::NEQuantizationSymmetricKernel Class Reference
arm_compute::NEQuantizationSymmetricKernel Class Reference
#include <NEQuantizationSymmetricKernel.h>
Public Member Functions
const char * name () const override
NEQuantizationSymmetricKernel ()
NEQuantizationSymmetricKernel (const NEQuantizationSymmetricKernel &)=delete
NEQuantizationSymmetricKernel & operator= (const NEQuantizationSymmetricKernel &)=delete
NEQuantizationSymmetricKernel (NEQuantizationSymmetricKernel &&)=default
NEQuantizationSymmetricKernel & operator= (NEQuantizationSymmetricKernel &&)=default
~NEQuantizationSymmetricKernel ()=default
void configure (const ITensor *input, ITensor *output, ITensor *scale_factor)
void run (const Window &window, const ThreadInfo &info) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *scale_factor)
Detailed Description
Interface for the dequantization layer kernel.
Definition at line 51 of file NEQuantizationSymmetricKernel.h.
Constructor & Destructor Documentation
NEQuantizationSymmetricKernel() [1/3]
NEQuantizationSymmetricKernel::NEQuantizationSymmetricKernel ()
Default constructor
Definition at line 130 of file NEQuantizationSymmetricKernel.cpp.
  : _input(nullptr), _output(nullptr), _scale_factor(nullptr)
{
}
NEQuantizationSymmetricKernel() [2/3]
arm_compute::NEQuantizationSymmetricKernel::NEQuantizationSymmetricKernel (const NEQuantizationSymmetricKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEQuantizationSymmetricKernel() [3/3]
arm_compute::NEQuantizationSymmetricKernel::NEQuantizationSymmetricKernel (NEQuantizationSymmetricKernel &&) default
Default Move Constructor.
~NEQuantizationSymmetricKernel()
arm_compute::NEQuantizationSymmetricKernel::~NEQuantizationSymmetricKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void NEQuantizationSymmetricKernel::configure (const ITensor * input, ITensor * output, ITensor * scale_factor)
Set input, output tensors.
Parameters
[in] input Source tensor. Data type supported: F16/F32.
[out] output Destination tensor with the same dimensions of input. Data type supported: S8.
[out] scale_factor Scale tensor of output. Data type supported: Same as input.
Definition at line 135 of file NEQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), output->info(), scale_factor->info()));
  _input = input;
  _output = output;
  _scale_factor = scale_factor;
  // Configure kernel window
  Window win_config = calculate_max_window(*input->info(), Steps());
  Coordinates coord;
  coord.set_num_dimensions(output->info()->num_dimensions());
  output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
  INEKernel::configure(win_config);
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::configure().
name()
const char * arm_compute::NEQuantizationSymmetricKernel::name () const inline override
Definition at line 54 of file NEQuantizationSymmetricKernel.h.
{ return "NEQuantizationSymmetricKernel"; }
operator=() [1/2]
NEQuantizationSymmetricKernel & arm_compute::NEQuantizationSymmetricKernel::operator= (const NEQuantizationSymmetricKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEQuantizationSymmetricKernel & arm_compute::NEQuantizationSymmetricKernel::operator= (NEQuantizationSymmetricKernel &&) default
Default move assignment operator
run()
void NEQuantizationSymmetricKernel::run (const Window & window, const ThreadInfo & info) override
Definition at line 220 of file NEQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_UNUSED(info);
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
  switch (_input->info()->data_type())
  {
    case DataType::F32:
      NEQuantizationSymmetricKernel::quantize<float>(window);
      break;
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
    case DataType::F16:
      NEQuantizationSymmetricKernel::quantize<float16_t>(window);
      break;
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
    default:
      ARM_COMPUTE_ERROR("Unsupported data type.");
  }
}
References info.
validate()
Status NEQuantizationSymmetricKernel::validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * scale_factor) static
Static function to check if given info will lead to a valid configuration of NEQuantizationSymmetricKernel
Parameters
[in] input Input tensor info. Data types supported: F16/F32.
[in] output Output tensor info. Data types supported: S8.
[out] scale_factor Scale tensor of output. Data type supported: Same as input.
Returns
a status
Definition at line 156 of file NEQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, scale_factor));
  return Status{};
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::validate(), and ~NEQuantizationSymmetricKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEQuantizationSymmetricKernel.h
compute/ARMComputeEx/src/core/NEON/kernels/NEQuantizationSymmetricKernel.cpp