ONE - On-device Neural Engine: onert::backend::cpu::ops::MeanLayer Class Reference
onert::backend::cpu::ops::MeanLayer Class Reference
#include <ReduceLayer.h>
Public Member Functions
MeanLayer ()
void MeanFloat32 ()
void MeanQuant8 ()
void configure (const IPortableTensor *input, const IPortableTensor *axes, IPortableTensor *output, bool keep_dims)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Protected Attributes
const IPortableTensor * _input
const IPortableTensor * _axes
IPortableTensor * _output
bool _keep_dims
Detailed Description
Definition at line 71 of file ReduceLayer.h.
Constructor & Destructor Documentation
MeanLayer()
onert::backend::cpu::ops::MeanLayer::MeanLayer ()
Definition at line 279 of file ReduceLayer.cc.
                     : _input(nullptr), _axes(nullptr), _output(nullptr), _keep_dims(false)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::MeanLayer::configure (const IPortableTensor * input, const IPortableTensor * axes, IPortableTensor * output, bool keep_dims)
Definition at line 311 of file ReduceLayer.cc.
{
  _input = input;
  _axes = axes;
  _output = output;
  _keep_dims = keep_dims;
  if (_input->data_type() != OperandType::FLOAT32 &&
      _input->data_type() != OperandType::QUANT_UINT8_ASYMM)
    throw std::runtime_error{"Mean: unsupported data type"};
}
References _axes, _input, _keep_dims, _output, and onert::backend::IPortableTensor::data_type().
MeanFloat32()
void onert::backend::cpu::ops::MeanLayer::MeanFloat32 ()
Definition at line 284 of file ReduceLayer.cc.
{
  const auto inputShape = getShape(_input);
  const auto axisVec = getReducerAxes(_axes);
  bool axis_is_1_and_2 =
    _keep_dims && inputShape.DimensionsCount() == 4 && axisVec.size() == 2 &&
    ((axisVec[0] == 1 && axisVec[1] == 2) || (axisVec[0] == 2 && axisVec[1] == 1));
  if (axis_is_1_and_2)
  {
    nnfw::cker::MeanAxis1And2(inputShape, getBuffer<float>(_input), getShape(_output),
                              getBuffer<float>(_output));
  }
  else
  {
    nnfw::cker::Mean(inputShape, getBuffer<float>(_input), getShape(_output),
                     getBuffer<float>(_output), axisVec);
  }
}
References _axes, _input, _keep_dims, _output, onert::backend::cpu::ops::getReducerAxes(), onert::backend::cpu::ops::getShape(), nnfw::cker::Mean(), and nnfw::cker::MeanAxis1And2().
Referenced by run().
MeanQuant8()
void onert::backend::cpu::ops::MeanLayer::MeanQuant8 ()
Definition at line 304 of file ReduceLayer.cc.
{
  nnfw::cker::MeanQ8Asymm(getShape(_input), getBuffer<uint8_t>(_input), _input->data_scale(),
                          _input->data_zero_point(), getShape(_output), getBuffer<uint8_t>(_output),
                          _output->data_scale(), _output->data_zero_point(), getReducerAxes(_axes));
}
References _axes, _input, _output, onert::backend::IPortableTensor::data_scale(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::cpu::ops::getReducerAxes(), onert::backend::cpu::ops::getShape(), and nnfw::cker::MeanQ8Asymm().
Referenced by run().
run()
void onert::backend::cpu::ops::MeanLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 324 of file ReduceLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    MeanFloat32();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    MeanQuant8();
  }
  else
  {
    throw std::runtime_error{"Mean: unsupported data type"};
  }
}
References _input, onert::backend::IPortableTensor::data_type(), MeanFloat32(), and MeanQuant8().
Referenced by onert::backend::train::ops::MeanLayer::forward().
Field Documentation
_axes
const IPortableTensor* onert::backend::cpu::ops::MeanLayer::_axes protected
Definition at line 88 of file ReduceLayer.h.
Referenced by onert::backend::train::ops::MeanLayer::backward(), configure(), MeanFloat32(), and MeanQuant8().
_input
const IPortableTensor* onert::backend::cpu::ops::MeanLayer::_input protected
Definition at line 87 of file ReduceLayer.h.
Referenced by onert::backend::train::ops::MeanLayer::backward(), configure(), MeanFloat32(), MeanQuant8(), and run().
_keep_dims
bool onert::backend::cpu::ops::MeanLayer::_keep_dims protected
Definition at line 90 of file ReduceLayer.h.
Referenced by onert::backend::train::ops::MeanLayer::backward(), configure(), and MeanFloat32().
_output
IPortableTensor* onert::backend::cpu::ops::MeanLayer::_output protected
Definition at line 89 of file ReduceLayer.h.
Referenced by configure(), MeanFloat32(), and MeanQuant8().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ReduceLayer.h
runtime/onert/backend/cpu/ops/ReduceLayer.cc