ONE - On-device Neural Engine: coco::AvgPool2D Class Reference
coco::AvgPool2D Class Reference final
2D Average Pooling
#include <Ops.h>
Public Types
enum class Divisor { Unknown , Static , PaddingExcluded }
Public Member Functions
AvgPool2D ()=default
AvgPool2D (const AvgPool2D &)=delete
AvgPool2D (AvgPool2D &&)=delete
AvgPool2D * asAvgPool2D (void) override
const AvgPool2D * asAvgPool2D (void) const override
Divisor divisor (void) const
void divisor (const Divisor &divisor)
Window2D * window (void)
const Window2D * window (void) const
Padding2D * pad (void)
const Padding2D * pad (void) const
Stride2D * stride (void)
const Stride2D * stride (void) const
Public Member Functions inherited from coco::UnaryOp
UnaryOp ()
UnaryOp (const UnaryOp &)=delete
UnaryOp (UnaryOp &&)=delete
virtual ~UnaryOp ()=default
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const final
Return a set of object(s) used during execution.
Op * arg (void) const
void arg (Op *arg)
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Detailed Description
2D Average Pooling
Definition at line 175 of file Ops.h.
Member Enumeration Documentation
Divisor
enum class coco::AvgPool2D::Divisor strong
Enumerator
Unknown
Static
PaddingExcluded
Definition at line 178 of file Ops.h.
  {
    Unknown,
    // Use the number of elements in each receptive field as a divisor
    Static,
    // Use the number of valid (non-padding) elements in each receptive field as a divisor
    PaddingExcluded
  };
Constructor & Destructor Documentation
AvgPool2D() [1/3]
coco::AvgPool2D::AvgPool2D () explicit default
AvgPool2D() [2/3]
coco::AvgPool2D::AvgPool2D (const AvgPool2D &) delete
AvgPool2D() [3/3]
coco::AvgPool2D::AvgPool2D (AvgPool2D &&) delete
Member Function Documentation
asAvgPool2D() [1/2]
const AvgPool2D * coco::AvgPool2D::asAvgPool2D (void) const inline override
Definition at line 196 of file Ops.h.
{ return this; }
asAvgPool2D() [2/2]
AvgPool2D * coco::AvgPool2D::asAvgPool2D (void) inline override
Definition at line 195 of file Ops.h.
{ return this; }
divisor() [1/2]
void coco::AvgPool2D::divisor (const Divisor & divisor) inline
Definition at line 200 of file Ops.h.
{ _divisor = divisor; }
References divisor().
Referenced by divisor().
divisor() [2/2]
Divisor coco::AvgPool2D::divisor (void) const inline
Definition at line 199 of file Ops.h.
{ return _divisor; }
Referenced by tflimport::AvgPool2DGraphBuilder::build().
pad() [1/2]
Padding2D * coco::AvgPool2D::pad (void) inline
Definition at line 207 of file Ops.h.
{ return &_pad; }
pad() [2/2]
const Padding2D * coco::AvgPool2D::pad (void) const inline
Definition at line 208 of file Ops.h.
{ return &_pad; }
stride() [1/2]
Stride2D * coco::AvgPool2D::stride (void) inline
Definition at line 211 of file Ops.h.
{ return &_stride; }
stride() [2/2]
const Stride2D * coco::AvgPool2D::stride (void) const inline
Definition at line 212 of file Ops.h.
{ return &_stride; }
window() [1/2]
Window2D * coco::AvgPool2D::window (void) inline
Definition at line 203 of file Ops.h.
{ return &_window; }
window() [2/2]
const Window2D * coco::AvgPool2D::window (void) const inline
Definition at line 204 of file Ops.h.
{ return &_window; }
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/IR/Ops.h