ONE - On-device Neural Engine: moco::GraphBuilderContext Class Reference
moco::GraphBuilderContext Class Reference
Class to store context to build loco graph IR from TensorFlow.
#include <GraphBuilderContext.h>
Public Member Functions
GraphBuilderContext (loco::Graph *g, NodeDefTable *nodedef, SymbolTable *tensor_names, UpdateQueue *updates)
GraphBuilderContext (const GraphBuilderContext &)=delete
GraphBuilderContext (GraphBuilderContext &&)=delete
loco::Graph * graph ()
NodeDefTable * nodedef ()
SymbolTable * tensor_names ()
UpdateQueue * updates ()
Detailed Description
Class to store context to build loco graph IR from TensorFlow.
Definition at line 116 of file GraphBuilderContext.h.
Constructor & Destructor Documentation
GraphBuilderContext() [1/3]
moco::GraphBuilderContext::GraphBuilderContext (loco::Graph * g, NodeDefTable * nodedef, SymbolTable * tensor_names, UpdateQueue * updates) inline
Definition at line 119 of file GraphBuilderContext.h.
    : _g(g), _nodedef(nodedef), _tensor_names(tensor_names), _updates(updates)
  {
    // DO NOTHING
  }
GraphBuilderContext() [2/3]
moco::GraphBuilderContext::GraphBuilderContext (const GraphBuilderContext &) delete
GraphBuilderContext() [3/3]
moco::GraphBuilderContext::GraphBuilderContext (GraphBuilderContext &&) delete
Member Function Documentation
graph()
loco::Graph * moco::GraphBuilderContext::graph () inline
Definition at line 130 of file GraphBuilderContext.h.
{ return _g; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::ConcatV2GraphBuilder::build(), moco::ConstGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::PackGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::tf::COpCallGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::ReshapeGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), moco::TanhGraphBuilder::build(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
nodedef()
NodeDefTable * moco::GraphBuilderContext::nodedef () inline
Definition at line 131 of file GraphBuilderContext.h.
{ return _nodedef; }
tensor_names()
SymbolTable * moco::GraphBuilderContext::tensor_names () inline
Definition at line 132 of file GraphBuilderContext.h.
{ return _tensor_names; }
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::ConcatV2GraphBuilder::build(), moco::ConstGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::PackGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::tf::COpCallGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::ReshapeGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), and moco::TanhGraphBuilder::build().
updates()
UpdateQueue * moco::GraphBuilderContext::updates () inline
Definition at line 133 of file GraphBuilderContext.h.
{ return _updates; }
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::ConcatV2GraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::PackGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::tf::COpCallGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::ReshapeGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), and moco::TanhGraphBuilder::build().
The documentation for this class was generated from the following file:
compiler/moco/import/include/moco/Import/GraphBuilderContext.h