ONE - On-device Neural Engine: locoex::Filter Class Reference
locoex::Filter Class Reference final
#include <TFLNodes.h>
Public Member Functions
Filter ()
int32_t w () const
void w (int32_t w)
int32_t h () const
void h (int32_t h)
Detailed Description
Definition at line 44 of file TFLNodes.h.
Constructor & Destructor Documentation
Filter()
locoex::Filter::Filter () inline
Definition at line 47 of file TFLNodes.h.
: _w(1), _h(1) {}
Member Function Documentation
h() [1/2]
int32_t locoex::Filter::h () const inline
Definition at line 52 of file TFLNodes.h.
{ return _h; }
h() [2/2]
void locoex::Filter::h (int32_t h) inline
Definition at line 53 of file TFLNodes.h.
{ _h = h; }
References h().
Referenced by h().
w() [1/2]
int32_t locoex::Filter::w () const inline
Definition at line 49 of file TFLNodes.h.
{ return _w; }
w() [2/2]
void locoex::Filter::w (int32_t w) inline
Definition at line 50 of file TFLNodes.h.
{ _w = w; }
References w().
Referenced by w().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h