ONE - On-device Neural Engine: luci_interpreter::kernels::GreaterEqual Class Reference
luci_interpreter::kernels::GreaterEqual Class Reference
#include <GreaterEqual.h>
Public Member Functions
GreaterEqual (const Tensor *x, const Tensor *y, Tensor *output)
const Tensor * x () const
const Tensor * y () const
Tensor * output () const
void configure () override
void execute () const override
GreaterEqual (const Tensor *x, const Tensor *y, Tensor *output)
const Tensor * x () const
const Tensor * y () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file GreaterEqual.h.
Constructor & Destructor Documentation
GreaterEqual() [1/2]
luci_interpreter::kernels::GreaterEqual::GreaterEqual (const Tensor * x, const Tensor * y, Tensor * output)
Definition at line 30 of file GreaterEqual.cpp.
  : Kernel({x, y}, {output})
{
}
References x(), and y().
GreaterEqual() [2/2]
luci_interpreter::kernels::GreaterEqual::GreaterEqual (const Tensor * x, const Tensor * y, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::GreaterEqual::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 35 of file GreaterEqual.cpp.
{
  LUCI_INTERPRETER_CHECK(x()->element_type() == y()->element_type());
  LUCI_INTERPRETER_CHECK(output()->element_type() == DataType::BOOL);
  if (x()->element_type() == DataType::U8)
  {
    quantizeMultiplierSmallerThanOneExp(x()->scale(), &_x_multiplier, &_x_shift);
    quantizeMultiplierSmallerThanOneExp(y()->scale(), &_y_multiplier, &_y_shift);
  }
  output()->resize(calculateShapeForBroadcast(x()->shape(), y()->shape()));
}
References luci_interpreter::kernels::calculateShapeForBroadcast(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::kernels::quantizeMultiplierSmallerThanOneExp(), luci_interpreter::Tensor::resize(), x(), and y().
configure() [2/2]
void luci_interpreter::kernels::GreaterEqual::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::GreaterEqual::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 48 of file GreaterEqual.cpp.
{
  switch (x()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::S64:
      evalInteger<int64_t>();
      break;
    case DataType::S32:
      evalInteger<int32_t>();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References x().
execute() [2/2]
void luci_interpreter::kernels::GreaterEqual::execute () const override virtual
Implements luci_interpreter::Kernel.
output() [1/2]
Tensor * luci_interpreter::kernels::GreaterEqual::output () const inline
Definition at line 34 of file GreaterEqual.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::GreaterEqual::output () const inline
Definition at line 34 of file GreaterEqual.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
x() [1/2]
const Tensor * luci_interpreter::kernels::GreaterEqual::x () const inline
Definition at line 32 of file GreaterEqual.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and GreaterEqual().
x() [2/2]
const Tensor * luci_interpreter::kernels::GreaterEqual::x () const inline
Definition at line 32 of file GreaterEqual.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
y() [1/2]
const Tensor * luci_interpreter::kernels::GreaterEqual::y () const inline
Definition at line 33 of file GreaterEqual.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and GreaterEqual().
y() [2/2]
const Tensor * luci_interpreter::kernels::GreaterEqual::y () const inline
Definition at line 33 of file GreaterEqual.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/GreaterEqual.h
onert-micro/luci-interpreter/src/kernels/GreaterEqual.h
compiler/luci-interpreter/src/kernels/GreaterEqual.cpp
onert-micro/luci-interpreter/src/kernels/GreaterEqual.cpp