ONE - On-device Neural Engine: luci::Module Class Reference
luci::Module Class Reference final
Collection of 'loco::Graph's.
#include <Module.h>
Public Member Functions
Module ()=default
Module (const Module &)=delete
Module (Module &&)=delete
~Module ()=default
size_t size (void) const
void add (std::unique_ptr< loco::Graph > &&g)
loco::Graph * graph (void) const
provide main graph
loco::Graph * graph (size_t idx) const
provide graph with an index
void source_table (const std::map< uint32_t, std::string > &table)
const std::map< uint32_t, std::string > & source_table (void) const
Detailed Description
Collection of 'loco::Graph's.
Definition at line 32 of file Module.h.
Constructor & Destructor Documentation
Module() [1/3]
luci::Module::Module () default
Module() [2/3]
luci::Module::Module (const Module &) delete
Module() [3/3]
luci::Module::Module (Module &&) delete
~Module()
luci::Module::~Module () default
Member Function Documentation
add()
void luci::Module::add (std::unique_ptr< loco::Graph > && g)
Definition at line 24 of file Module.cpp.
{
  if (g.get() == nullptr)
    throw std::invalid_argument("Module: Graph cannot be null");
  _graphs.emplace_back(std::move(g));
}
graph() [1/2]
loco::Graph * luci::Module::graph (size_t idx) const
provide graph with an index
Note
graph(0) is interpreted as a main graph
Definition at line 38 of file Module.cpp.
{
  auto &graph = _graphs.at(idx);
  return graph.get();
}
References graph().
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
graph() [2/2]
loco::Graph * luci::Module::graph (void) const
provide main graph
Definition at line 32 of file Module.cpp.
{
  auto &graph = _graphs.at(0);
  return graph.get();
}
References graph().
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), partee::export_part_conn_ini(), partee::export_part_conn_json(), graph(), circle_eval_diff::MAEPrinter::init(), circle_eval_diff::MSEPrinter::init(), circle_eval_diff::MAPEPrinter::init(), circle_eval_diff::MPEIRPrinter::init(), circle_eval_diff::TopKMatchPrinter::init(), luci_interpreter::ModuleLoader::load(), luci::produce_pgroups(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
size()
size_t luci::Module::size (void) const inline
Definition at line 44 of file Module.h.
{ return _graphs.size(); }
Referenced by luci_interpreter::ModuleLoader::load(), luci::ModuleProgressReporter::notify(), opselector::OpSelector::OpSelector(), and opselector::OpSelector::select_by().
source_table() [1/2]
void luci::Module::source_table (const std::map< uint32_t, std::string > & table) inline
Definition at line 64 of file Module.h.
{ _source_table = table; }
source_table() [2/2]
const std::map< uint32_t, std::string > & luci::Module::source_table (void) const inline
Definition at line 66 of file Module.h.
{ return _source_table; }
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/Module.h
compiler/luci/lang/src/Module.cpp