ONE - On-device Neural Engine: luci::CircleImportMetadata Class Reference
luci::CircleImportMetadata Class Reference
#include <CircleImportMetadata.h>
Public Member Functions
CircleImportMetadata ()=delete
CircleImportMetadata (const luci::CircleReader &reader)
const OriginTable origin_table (void)
Create origin table using _source_table and _op_table in CircleImportMetadata.
const std::map< uint32_t, std::string > & source_table (void) const
const luci::ExecutionPlanTable & execution_plan_table (void) const
Detailed Description
Definition at line 34 of file CircleImportMetadata.h.
Constructor & Destructor Documentation
CircleImportMetadata() [1/2]
luci::CircleImportMetadata::CircleImportMetadata () delete
CircleImportMetadata() [2/2]
luci::CircleImportMetadata::CircleImportMetadata (const luci::CircleReader & reader)
Definition at line 203 of file CircleImportMetadata.cpp.
{
  const auto metadata = reader.metadata();
  for (uint32_t i = 0; i < metadata.size(); ++i)
  {
    const auto *meta = metadata[i];
    assert(meta != nullptr);
    assert(meta->buffer() < reader.buffers().size());
    assert(reader.buffers()[meta->buffer()] != nullptr);
    const auto buffer = luci::wrap(reader.buffers()[meta->buffer()]->data());
    assert(meta->name() != nullptr);
    if (meta->name()->str().compare("ONE_op_table") == 0)
      _op_table = decoded_op_table(buffer);
    else if (meta->name()->str().compare("ONE_source_table") == 0)
      _source_table = decoded_source_table(buffer);
    else if (meta->name()->str().compare("ONE_execution_plan_table") == 0)
      _execution_plan_table = decoded_execution_plan(buffer);
  }
}
References luci::CircleReader::buffers(), luci::VectorWrapper< T >::data(), luci::CircleReader::metadata(), luci::VectorWrapper< T >::size(), and luci::wrap().
Member Function Documentation
execution_plan_table()
const luci::ExecutionPlanTable & luci::CircleImportMetadata::execution_plan_table (void) const inline
Definition at line 51 of file CircleImportMetadata.h.
{ return _execution_plan_table; }
origin_table()
const OriginTable luci::CircleImportMetadata::origin_table (void)
Create origin table using _source_table and _op_table in CircleImportMetadata.
Note
For creating origin table, both _op_table and _source_table should exist. If one of them does not exist, empty table is returned.
Definition at line 225 of file CircleImportMetadata.cpp.
{
  OriginTable origin_table;
  if (_op_table.size() > 0 && _source_table.size() > 0)
  {
    for (auto &kv : _op_table)
    {
      const auto node_id = kv.first;
      const auto &source_ids = kv.second;
      std::vector<std::shared_ptr<CircleNodeOrigin>> origins;
      for (auto source_id : source_ids)
      {
        const auto source_name = _source_table.at(source_id);
        origins.push_back(single_origin(source_id, source_name));
      }
      auto origin = composite_origin(origins);
      origin_table.emplace(node_id, origin);
    }
  }
  return origin_table;
}
References luci::composite_origin(), origin_table(), and luci::single_origin().
Referenced by origin_table().
source_table()
const std::map< uint32_t, std::string > & luci::CircleImportMetadata::source_table (void) const inline
Definition at line 49 of file CircleImportMetadata.h.
{ return _source_table; }
The documentation for this class was generated from the following files:
compiler/luci/import/src/CircleImportMetadata.h
compiler/luci/import/src/CircleImportMetadata.cpp