ONE - On-device Neural Engine: onert::compiler::LoweredGraph Class Reference
onert::compiler::LoweredGraph Class Reference
Class that contains lowering information on graph. In addition, after lowering, operands in graph will be set to "dynamic" if the shape of output of an operation cannot be decided at compilation time.
#include <LoweredGraph.h>
Public Member Functions
LoweredGraph (const ir::Graph &graph, const compiler::CompilerOptions &options)
ir::Graph & graph () override
const ir::Graph & graph () const override
const compiler::GraphLowerInfo & lower_info () const override
compiler::GraphLowerInfo & lower_info () override
std::shared_ptr< ir::OperationIndexMap< int64_t > > indexed_ranks ()
void setHasDynamicTensor (ir::OperationIndex ind, bool val)
bool getHasDynamicTensor (ir::OperationIndex ind) const
Public Member Functions inherited from onert::compiler::ILoweredGraph
virtual ~ILoweredGraph ()=default
virtual ir::Graph & graph ()=0
virtual const ir::Graph & graph () const =0
virtual const compiler::GraphLowerInfo & lower_info () const =0
virtual compiler::GraphLowerInfo & lower_info ()=0
Detailed Description
Class that contains lowering information on graph. In addition, after lowering, operands in graph will be set to "dynamic" if the shape of output of an operation cannot be decided at compilation time.
Definition at line 36 of file LoweredGraph.h.
Constructor & Destructor Documentation
LoweredGraph()
onert::compiler::LoweredGraph::LoweredGraph (const ir::Graph & graph, const compiler::CompilerOptions & options)
Definition at line 42 of file LoweredGraph.cc.
                                                                               : _graph{graph}
{
  lowerGraph(options);
}
Member Function Documentation
getHasDynamicTensor()
bool onert::compiler::LoweredGraph::getHasDynamicTensor (ir::OperationIndex ind) const inline
Definition at line 51 of file LoweredGraph.h.
  {
    auto itr = _has_dynamic_tensor_map.find(ind);
    return (itr == _has_dynamic_tensor_map.end()) ? false : itr->second;
  }
graph() [1/2]
const ir::Graph & onert::compiler::LoweredGraph::graph () const inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 42 of file LoweredGraph.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
graph() [2/2]
ir::Graph & onert::compiler::LoweredGraph::graph () inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 41 of file LoweredGraph.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::compiler::StaticShapeInferer::dump(), onert::dumper::dot::DotDumper::dump(), onert::dumper::text::dumpLoweredGraph(), onert::compiler::StaticShapeInferer::infer(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
indexed_ranks()
std::shared_ptr< ir::OperationIndexMap< int64_t > > onert::compiler::LoweredGraph::indexed_ranks () inline
Definition at line 45 of file LoweredGraph.h.
{ return _indexed_ranks; }
lower_info() [1/2]
const compiler::GraphLowerInfo & onert::compiler::LoweredGraph::lower_info () const inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 43 of file LoweredGraph.h.
{ return _lower_info_map; }
lower_info() [2/2]
compiler::GraphLowerInfo & onert::compiler::LoweredGraph::lower_info () inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 44 of file LoweredGraph.h.
{ return _lower_info_map; }
setHasDynamicTensor()
void onert::compiler::LoweredGraph::setHasDynamicTensor (ir::OperationIndex ind, bool val) inline
Definition at line 47 of file LoweredGraph.h.
  {
    _has_dynamic_tensor_map.emplace(ind, val);
  }
Referenced by onert::compiler::StaticShapeInferer::infer().
The documentation for this class was generated from the following files:
runtime/onert/core/include/compiler/LoweredGraph.h
runtime/onert/core/src/compiler/LoweredGraph.cc