ONE - On-device Neural Engine: mpqsolver::core::Dumper Class Reference
mpqsolver::core::Dumper Class Reference final
#include <Dumper.h>
Public Member Functions
Dumper ()=default
Dumper (const std::string &dir_path)
void set_model_path (const std::string &model_path)
sets model path for further usage
void dump_MPQ_configuration (const LayerParams &layers, const std::string &def_dtype, int step) const
dumps mpq configuration
void dump_final_MPQ (const LayerParams &layers, const std::string &def_dtype) const
dumps final mpq configuration
void dump_quantized (luci::Module *module, uint32_t step) const
dumps quantized module
void prepare_for_error_dumping () const
create file for error dumping
void dump_Q8_error (float error) const
append error of Q8 quantization
void dump_Q16_error (float error) const
append error of Q16 quantization
void dump_MPQ_error (float error, uint32_t step) const
append error of mpq quantization
void dump_MPQ_error (float error) const
dump final error
Detailed Description
Definition at line 33 of file Dumper.h.
Constructor & Destructor Documentation
Dumper() [1/2]
mpqsolver::core::Dumper::Dumper () default
Dumper() [2/2]
Dumper::Dumper (const std::string & dir_path)
Definition at line 41 of file Dumper.cpp.
: _dir_path(dir_path) {}
Member Function Documentation
dump_final_MPQ()
void Dumper::dump_final_MPQ (const LayerParams & layers, const std::string & def_dtype) const
dumps final mpq configuration
Parameters
layers specific quantization parameters
def_dtype default quantization data type
Definition at line 90 of file Dumper.cpp.
{
  prepare_directory(_dir_path);
  std::string path = _dir_path + "/FinalConfiguration" + ".mpq.json";
  dump_MPQ_configuration(layers, def_dtype, path);
}
References dump_MPQ_configuration().
Referenced by mpqsolver::core::DumpingHooks::on_end_solver().
dump_MPQ_configuration()
void Dumper::dump_MPQ_configuration (const LayerParams & layers, const std::string & def_dtype, int step) const
dumps mpq configuration
Parameters
layers specific quantization parameters
def_dtype default quantization data type
step id of mpq configuration
Definition at line 82 of file Dumper.cpp.
{
  prepare_directory(_dir_path);
  std::string path = _dir_path + "/Configuration_" + std::to_string(step) + ".mpq.json";
  dump_MPQ_configuration(layers, def_dtype, path);
}
References dump_MPQ_configuration().
Referenced by dump_final_MPQ(), dump_MPQ_configuration(), and mpqsolver::core::DumpingHooks::on_end_iteration().
dump_MPQ_error() [1/2]
void Dumper::dump_MPQ_error (float error) const
dump final error
Parameters
error final error of quantization
Definition at line 156 of file Dumper.cpp.
{
  std::string path = get_error_path();
  dump_error(error, "FINAL", path);
}
dump_MPQ_error() [2/2]
void Dumper::dump_MPQ_error (float error, uint32_t step) const
append error of mpq quantization
Parameters
error error of quantization
step id of error
Definition at line 150 of file Dumper.cpp.
{
  std::string path = get_error_path();
  dump_error(error, std::to_string(step), path);
}
Referenced by mpqsolver::core::DumpingHooks::on_end_iteration(), and mpqsolver::core::DumpingHooks::on_end_solver().
dump_Q16_error()
void Dumper::dump_Q16_error (float error) const
append error of Q16 quantization
Definition at line 144 of file Dumper.cpp.
{
  std::string path = get_error_path();
  dump_error(error, "Q16", path);
}
Referenced by mpqsolver::core::DumpingHooks::on_begin_solver().
dump_Q8_error()
void Dumper::dump_Q8_error (float error) const
append error of Q8 quantization
Definition at line 138 of file Dumper.cpp.
{
  std::string path = get_error_path();
  dump_error(error, "Q8", path);
}
Referenced by mpqsolver::core::DumpingHooks::on_begin_solver().
dump_quantized()
void Dumper::dump_quantized (luci::Module * module, uint32_t step) const
dumps quantized module
Parameters
layers specific quantization parameters
step id of quantized module
Definition at line 115 of file Dumper.cpp.
{
  std::string path = _dir_path + "/quantized_" + std::to_string(step) + ".mpq.circle";
  save_circle(module, path);
}
Referenced by mpqsolver::core::DumpingHooks::on_quantized().
prepare_for_error_dumping()
void Dumper::prepare_for_error_dumping () const
create file for error dumping
Definition at line 129 of file Dumper.cpp.
{
  prepare_directory(_dir_path);
  std::string path = get_error_path();
  std::ofstream file;
  file.open(path); // create empty
  file.close();
}
Referenced by mpqsolver::core::DumpingHooks::on_begin_solver().
set_model_path()
void Dumper::set_model_path (const std::string & model_path)
sets model path for further usage
Definition at line 43 of file Dumper.cpp.
{ _model_path = model_path; }
Referenced by mpqsolver::core::DumpingHooks::on_begin_solver().
The documentation for this class was generated from the following files:
compiler/circle-mpqsolver/src/core/Dumper.h
compiler/circle-mpqsolver/src/core/Dumper.cpp