ONE - On-device Neural Engine: loco::PermutingDecoder< Domain::Filter > Class Reference
loco::PermutingDecoder< Domain::Filter > Class Reference final
Permutation-based Filter-to-Tensor converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingDecoder ()=default
PermutingDecoder (const Permutation< Domain::Filter > &perm)
bool valid (void) const
TensorShape shape (const FilterShape &tensor_shape) const override
FilterIndex value (const TensorIndex &index) const override
const Permutation< Domain::Filter > * perm (void) const
Permutation< Domain::Filter > * perm (void)
void perm (const Permutation< Domain::Filter > &p)
Public Member Functions inherited from loco::FilterDecoder
virtual ~FilterDecoder ()=default
virtual TensorShape shape (const FilterShape &shape) const =0
virtual FilterIndex value (const TensorIndex &index) const =0
Detailed Description
Permutation-based Filter-to-Tensor converter.
Definition at line 202 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingDecoder() [1/2]
loco::PermutingDecoder< Domain::Filter >::PermutingDecoder () default
PermutingDecoder() [2/2]
loco::PermutingDecoder< Domain::Filter >::PermutingDecoder (const Permutation< Domain::Filter > & perm) inline explicit
Definition at line 208 of file PermutingCodec.h.
                                                                   : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingDecoder< Domain::Filter >::perm (const Permutation< Domain::Filter > & p) inline
Definition at line 223 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Filter > * loco::PermutingDecoder< Domain::Filter >::perm (void) inline
Definition at line 222 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Filter > * loco::PermutingDecoder< Domain::Filter >::perm (void) const inline
Definition at line 221 of file PermutingCodec.h.
{ return &_perm; }
shape()
TensorShape loco::PermutingDecoder< Domain::Filter >::shape (const FilterShape & tensor_shape) const override virtual
Implements loco::FilterDecoder.
Definition at line 308 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorShape out;
  out.rank(4);
  out.dim(_perm[FilterAxis::Count]) = in.count();
  out.dim(_perm[FilterAxis::Depth]) = in.depth();
  out.dim(_perm[FilterAxis::Height]) = in.height();
  out.dim(_perm[FilterAxis::Width]) = in.width();
  return out;
}
References loco::Count, loco::FilterShape::count(), loco::Depth, loco::FilterShape::depth(), loco::TensorShape::dim(), loco::Height, loco::FilterShape::height(), loco::TensorShape::rank(), loco::valid(), loco::Width, and loco::FilterShape::width().
valid()
bool loco::PermutingDecoder< Domain::Filter >::valid (void) const
Definition at line 337 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
FilterIndex loco::PermutingDecoder< Domain::Filter >::value (const TensorIndex & index) const override virtual
Implements loco::FilterDecoder.
Definition at line 323 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  FilterIndex out;
  out.nth() = in.at(_perm[FilterAxis::Count]);
  out.channel() = in.at(_perm[FilterAxis::Depth]);
  out.row() = in.at(_perm[FilterAxis::Height]);
  out.column() = in.at(_perm[FilterAxis::Width]);
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::FilterIndex::channel(), loco::FilterIndex::column(), loco::Count, loco::Depth, loco::Height, loco::FilterIndex::nth(), loco::FilterIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp