ONE - On-device Neural Engine: luci::CircleDepthwiseConv2D Class Reference
luci::CircleDepthwiseConv2D Class Reference final
DEPTHWISE_CONV_2D in Circle.
#include <CircleDepthwiseConv2D.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * filter (void) const
void filter (loco::Node *node)
loco::Node * bias (void) const override
void bias (loco::Node *node) override
get the input for bias.
Padding padding () const
void padding (Padding padding)
const Stride * stride (void) const
Stride * stride (void)
int32_t depthMultiplier (void) const
void depthMultiplier (int32_t arg)
const Dilation * dilation (void) const
Dilation * dilation (void)
Public Member Functions inherited from luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::Bias >
CircleNodeMixin ()=default
virtual loco::Node * bias (void) const =0
virtual void bias (loco::Node *node)=0
get the input for bias.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >
loco::Use * at (uint32_t n) const
Detailed Description
DEPTHWISE_CONV_2D in Circle.
Definition at line 36 of file CircleDepthwiseConv2D.h.
Member Function Documentation
bias() [1/2]
void luci::CircleDepthwiseConv2D::bias (loco::Node * node) inline override virtual
get the input for bias.
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 49 of file CircleDepthwiseConv2D.h.
{ at(2)->node(node); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
bias() [2/2]
loco::Node * luci::CircleDepthwiseConv2D::bias (void) const inline override virtual
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 48 of file CircleDepthwiseConv2D.h.
{ return at(2)->node(); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
depthMultiplier() [1/2]
void luci::CircleDepthwiseConv2D::depthMultiplier (int32_t arg) inline
Definition at line 59 of file CircleDepthwiseConv2D.h.
{ _depth_multiplier = arg; }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::arg().
depthMultiplier() [2/2]
int32_t luci::CircleDepthwiseConv2D::depthMultiplier (void) const inline
Definition at line 58 of file CircleDepthwiseConv2D.h.
{ return _depth_multiplier; }
Referenced by luci::CloneNodeLet< CN::DEF >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
dilation() [1/2]
Dilation * luci::CircleDepthwiseConv2D::dilation (void) inline
Definition at line 62 of file CircleDepthwiseConv2D.h.
{ return &_dilation; }
dilation() [2/2]
const Dilation * luci::CircleDepthwiseConv2D::dilation (void) const inline
Definition at line 61 of file CircleDepthwiseConv2D.h.
{ return &_dilation; }
Referenced by luci::CloneNodeLet< CN::DEF >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
filter() [1/2]
void luci::CircleDepthwiseConv2D::filter (loco::Node * node) inline
Definition at line 46 of file CircleDepthwiseConv2D.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
filter() [2/2]
loco::Node * luci::CircleDepthwiseConv2D::filter (void) const inline
Definition at line 45 of file CircleDepthwiseConv2D.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
input() [1/2]
void luci::CircleDepthwiseConv2D::input (loco::Node * node) inline
Definition at line 43 of file CircleDepthwiseConv2D.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleDepthwiseConv2D::input (void) const inline
Definition at line 42 of file CircleDepthwiseConv2D.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D > >::at(), and loco::Use::node().
padding() [1/2]
Padding luci::CircleDepthwiseConv2D::padding () const inline
Definition at line 52 of file CircleDepthwiseConv2D.h.
{ return _padding; }
Referenced by luci::CloneNodeLet< CN::DEF >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
padding() [2/2]
void luci::CircleDepthwiseConv2D::padding (Padding padding) inline
Definition at line 53 of file CircleDepthwiseConv2D.h.
{ _padding = padding; }
References padding().
Referenced by padding().
stride() [1/2]
Stride * luci::CircleDepthwiseConv2D::stride (void) inline
Definition at line 56 of file CircleDepthwiseConv2D.h.
{ return &_stride; }
stride() [2/2]
const Stride * luci::CircleDepthwiseConv2D::stride (void) const inline
Definition at line 55 of file CircleDepthwiseConv2D.h.
{ return &_stride; }
Referenced by luci::CloneNodeLet< CN::DEF >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleDepthwiseConv2D.h