ONE - On-device Neural Engine: onert::ir::operation::SpaceToDepth Class Reference
onert::ir::operation::SpaceToDepth Class Reference
#include <SpaceToDepth.h>
Data Structures
struct Param
Public Types
enum Input { INPUT = 0 }
Public Member Functions
SpaceToDepth (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, const Param &param)
void accept (OperationVisitor &v) const override
OpCode opcode () const final
const Param & param () const
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
void replaceInputs (const OperandIndex &from, const OperandIndex &to)
void replaceOutputs (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const
const OperandIndexSequence & getOutputs () const
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Detailed Description
Definition at line 31 of file SpaceToDepth.h.
Member Enumeration Documentation
Input
enum onert::ir::operation::SpaceToDepth::Input
Enumerator
INPUT
Definition at line 34 of file SpaceToDepth.h.
  {
    INPUT = 0
  };
Constructor & Destructor Documentation
SpaceToDepth()
onert::ir::operation::SpaceToDepth::SpaceToDepth (const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, const Param & param)
Definition at line 29 of file SpaceToDepth.cc.
  : Operation{OperandConstraint::createExact(1u), inputs, outputs}, _param{param}
{
}
Member Function Documentation
accept()
void onert::ir::operation::SpaceToDepth::accept (OperationVisitor & v) const override virtual
Implements onert::ir::Operation.
Definition at line 27 of file SpaceToDepth.cc.
{ v.visit(*this); }
opcode()
OpCode onert::ir::operation::SpaceToDepth::opcode () const inline final virtual
Implements onert::ir::Operation.
Definition at line 50 of file SpaceToDepth.h.
{ return OpCode::SpaceToDepth; }
param()
const Param & onert::ir::operation::SpaceToDepth::param () const inline
Definition at line 53 of file SpaceToDepth.h.
{ return _param; }
Referenced by onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), and onert::ir::OperationValidator::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/operation/SpaceToDepth.h
runtime/onert/core/src/ir/operation/SpaceToDepth.cc