ONE - On-device Neural Engine: luci::Filter Class Reference
luci::Filter Class Reference final
#include <AttrFilter.h>
Public Member Functions
Filter ()
uint32_t w () const
void w (uint32_t w)
void w (int32_t w)
uint32_t h () const
void h (uint32_t h)
void h (int32_t h)
Detailed Description
Definition at line 25 of file AttrFilter.h.
Constructor & Destructor Documentation
Filter()
luci::Filter::Filter () inline
Definition at line 28 of file AttrFilter.h.
: _w(1), _h(1) {}
Member Function Documentation
h() [1/3]
uint32_t luci::Filter::h () const inline
Definition at line 34 of file AttrFilter.h.
{ return _h; }
Referenced by h(), luci::CloneNodeLet< CN::ABC >::visit(), luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
h() [2/3]
void luci::Filter::h (int32_t h)
Definition at line 30 of file AttrFilter.cpp.
{
  assert(h >= 0);
  _h = static_cast<uint32_t>(h);
}
References h().
h() [3/3]
void luci::Filter::h (uint32_t h) inline
Definition at line 35 of file AttrFilter.h.
{ _h = h; }
References h().
Referenced by h().
w() [1/3]
uint32_t luci::Filter::w () const inline
Definition at line 30 of file AttrFilter.h.
{ return _w; }
Referenced by luci::CloneNodeLet< CN::ABC >::visit(), luci::CloneNodeLet< CN::KLMN >::visit(), luci::BuiltinOptionsExtractor::visit(), and w().
w() [2/3]
void luci::Filter::w (int32_t w)
Definition at line 24 of file AttrFilter.cpp.
{
  assert(w >= 0);
  _w = static_cast<uint32_t>(w);
}
References w().
w() [3/3]
void luci::Filter::w (uint32_t w) inline
Definition at line 31 of file AttrFilter.h.
{ _w = w; }
References w().
Referenced by w().
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/AttrFilter.h
compiler/luci/lang/src/AttrFilter.cpp