ONE - On-device Neural Engine: logo::PhaseRunnerMixinObservable Class Reference
logo::PhaseRunnerMixinObservable Class Reference
#include <Phase.h>
Public Member Functions
PhaseRunnerMixinObservable ()=default
virtual ~PhaseRunnerMixinObservable ()=default
void attach (PhaseEventListener *listener)
void notifyPhaseBegin (void) const
void notifyPhaseEnd (void) const
void notifyPassBegin (Pass *pass) const
void notifyPassEnd (Pass *pass, bool changed) const
Detailed Description
Definition at line 89 of file Phase.h.
Constructor & Destructor Documentation
PhaseRunnerMixinObservable()
logo::PhaseRunnerMixinObservable::PhaseRunnerMixinObservable () default
~PhaseRunnerMixinObservable()
virtual logo::PhaseRunnerMixinObservable::~PhaseRunnerMixinObservable () virtual default
Member Function Documentation
attach()
void logo::PhaseRunnerMixinObservable::attach (PhaseEventListener * listener) inline
Definition at line 98 of file Phase.h.
{ _listener = listener; }
notifyPassBegin()
void logo::PhaseRunnerMixinObservable::notifyPassBegin (Pass * pass) const inline
Definition at line 121 of file Phase.h.
  {
    if (_listener)
    {
      PhaseEventInfo<PhaseEvent::PassBegin> info;
      info.pass(pass);
      _listener->notify(&info);
    }
  }
References info, and logo::PhaseEventListener::notify().
notifyPassEnd()
void logo::PhaseRunnerMixinObservable::notifyPassEnd (Pass * pass, bool changed) const inline
Definition at line 133 of file Phase.h.
  {
    if (_listener)
    {
      PhaseEventInfo<PhaseEvent::PassEnd> info;
      info.pass(pass);
      info.changed(changed);
      _listener->notify(&info);
    }
  }
References info, and logo::PhaseEventListener::notify().
notifyPhaseBegin()
void logo::PhaseRunnerMixinObservable::notifyPhaseBegin (void) const inline
Definition at line 101 of file Phase.h.
  {
    if (_listener)
    {
      PhaseEventInfo<PhaseEvent::PhaseBegin> info;
      _listener->notify(&info);
    }
  }
References info, and logo::PhaseEventListener::notify().
notifyPhaseEnd()
void logo::PhaseRunnerMixinObservable::notifyPhaseEnd (void) const inline
Definition at line 111 of file Phase.h.
  {
    if (_listener)
    {
      PhaseEventInfo<PhaseEvent::PhaseEnd> info;
      _listener->notify(&info);
    }
  }
References info, and logo::PhaseEventListener::notify().
The documentation for this class was generated from the following file:
compiler/logo-core/include/logo/Phase.h