ONE - On-device Neural Engine: onert::backend::builtin::IOTensor Class Reference
onert::backend::builtin::IOTensor Class Reference
Tensor object that indirects to the tensor it is pointing to.
#include <IOTensor.h>
Public Member Functions
IOTensor (const ir::OperandInfo &info, ir::Layout layout)
~IOTensor ()
void setTensor (IPortableTensor *tensor)
void setUserTensor (uint8_t *buffer, size_t size)
ir::OperandInfo orig_info () const
ir::Layout orig_layout () const
uint8_t * buffer () const override
size_t total_size () const override
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
ir::Shape getShape () const override
Get ir::Shape of tensor.
void setShape (const ir::Shape &shape) override
Set the shape of tenser to new_shape.
bool is_constant () const override
Return true if the tensor is constant.
bool applyShape (const ir::Shape &shape) override
Set the shape to shape and possibly re-allocate the buffer.
void setShapeOfIPortableTensor (const ir::Shape &shape)
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Tensor object that indirects to the tensor it is pointing to.
A model I/O tensor could be two types.
UserTensor, if it is the primary graph
Any other derivative of IPortableTensor from another backend, otherwise
To support these, this object indirects everything to the actual tensor pointer. Exceptionally if it is UserTensor, this class creates and manages it.
Definition at line 41 of file IOTensor.h.
Constructor & Destructor Documentation
IOTensor()
onert::backend::builtin::IOTensor::IOTensor (const ir::OperandInfo & info, ir::Layout layout)
Definition at line 32 of file IOTensor.cc.
  : IPortableTensor{info}, _orig_info{info}, _orig_layout{layout}
{
  setUserTensor(nullptr, 0);
}
References setUserTensor().
~IOTensor()
onert::backend::builtin::IOTensor::~IOTensor ()
Definition at line 30 of file IOTensor.cc.
{}
Member Function Documentation
applyShape()
bool onert::backend::builtin::IOTensor::applyShape (const ir::Shape &) inline override virtual
Set the shape to shape and possibly re-allocate the buffer.
If a tensor is dynamic tensor and previously allocated memory exists, it will be deallocated. If a tensor is static tensor (with previously allocated memory by StaticTensorManager), buffer() will be overwriten
Parameters
shape tensor's new shape. While allocating memory for this new_shape, tensor's shape is set to new_shape
Returns
true If applying shape is successful
false If not applying shape is not supported (it throws for other errors)
Reimplemented from onert::backend::ITensor.
Definition at line 75 of file IOTensor.h.
  {
    // Workaround for IPortableTensor holds _info as its member
    _info.shape(shape);
    return _tensor->applyShape(shape);
  }
References onert::backend::IPortableTensor::_info, onert::backend::ITensor::applyShape(), and onert::ir::OperandInfo::shape().
buffer()
uint8_t * onert::backend::builtin::IOTensor::buffer () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 54 of file IOTensor.h.
{ return _tensor->buffer(); }
References onert::backend::ITensor::buffer().
Referenced by setUserTensor().
calcOffset()
size_t onert::backend::builtin::IOTensor::calcOffset (const ir::Coordinates & coords) const inline override virtual
Implements onert::backend::ITensor.
Definition at line 56 of file IOTensor.h.
  {
    return _tensor->calcOffset(coords);
  }
References onert::backend::ITensor::calcOffset(), and coords.
data_type()
ir::DataType onert::backend::builtin::IOTensor::data_type () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 61 of file IOTensor.h.
{ return _tensor->data_type(); }
References onert::backend::ITensor::data_type().
getShape()
ir::Shape onert::backend::builtin::IOTensor::getShape () const inline override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 67 of file IOTensor.h.
{ return _tensor->getShape(); }
References onert::backend::ITensor::getShape().
is_constant()
bool onert::backend::builtin::IOTensor::is_constant () const inline override virtual
Return true if the tensor is constant.
Reimplemented from onert::backend::ITensor.
Definition at line 74 of file IOTensor.h.
{ return _tensor->is_constant(); }
References onert::backend::ITensor::is_constant().
is_dynamic()
bool onert::backend::builtin::IOTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 62 of file IOTensor.h.
  {
    return _is_dynamic || _orig_info.isDynamic() || (_tensor && _tensor->is_dynamic());
  }
References onert::backend::ITensor::is_dynamic(), and onert::ir::OperandInfo::isDynamic().
layout()
ir::Layout onert::backend::builtin::IOTensor::layout () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 60 of file IOTensor.h.
{ return _tensor->layout(); }
References onert::backend::ITensor::layout().
orig_info()
ir::OperandInfo onert::backend::builtin::IOTensor::orig_info () const inline
Definition at line 50 of file IOTensor.h.
{ return _orig_info; }
orig_layout()
ir::Layout onert::backend::builtin::IOTensor::orig_layout () const inline
Definition at line 51 of file IOTensor.h.
{ return _orig_layout; }
set_dynamic()
void onert::backend::builtin::IOTensor::set_dynamic () inline override virtual
set this tensor dynamic
Reimplemented from onert::backend::ITensor.
Definition at line 66 of file IOTensor.h.
{ _is_dynamic = true; }
setShape()
void onert::backend::builtin::IOTensor::setShape (const ir::Shape & new_shape) inline override virtual
Set the shape of tenser to new_shape.
Note
Higer dimension will be placed on front.
Reimplemented from onert::backend::ITensor.
Definition at line 68 of file IOTensor.h.
  {
    // Workaround for IPortableTensor holds _info as its member
    _info.shape(shape);
    _tensor->setShape(shape);
  }
References onert::backend::IPortableTensor::_info, onert::backend::ITensor::setShape(), and onert::ir::OperandInfo::shape().
setShapeOfIPortableTensor()
void onert::backend::builtin::IOTensor::setShapeOfIPortableTensor (const ir::Shape & shape) inline
Definition at line 83 of file IOTensor.h.
{ _info.shape(shape); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::shape().
setTensor()
void onert::backend::builtin::IOTensor::setTensor (IPortableTensor * tensor)
Definition at line 38 of file IOTensor.cc.
{
  assert(tensor);
  assert(tensor != this);
  // TODO Handle when layout was changed
  assert(tensor->layout() == _orig_layout); // Changing layout is not considered yet
  _user_tensor.reset();
  _tensor = tensor;
}
setUserTensor()
void onert::backend::builtin::IOTensor::setUserTensor (uint8_t * buffer, size_t size)
Definition at line 48 of file IOTensor.cc.
{
  _user_tensor = std::make_unique<UserTensor>(_orig_info, _orig_layout, buffer, size);
  _tensor = _user_tensor.get();
}
References buffer().
Referenced by IOTensor().
total_size()
size_t onert::backend::builtin::IOTensor::total_size () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 55 of file IOTensor.h.
{ return _tensor->total_size(); }
References onert::backend::ITensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/IOTensor.h
runtime/onert/core/src/backend/builtin/IOTensor.cc