ONE - On-device Neural Engine: luci_interpreter::kernels::L2Pool2D Class Reference
luci_interpreter::kernels::L2Pool2D Class Reference
#include <L2Pool2D.h>
Public Member Functions
L2Pool2D (const Tensor *input, Tensor *output, const Pool2DParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
L2Pool2D (const Tensor *input, Tensor *output, const Pool2DParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< Pool2DParams >
const Pool2DParams & params () const
const Pool2DParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< Pool2DParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const Pool2DParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const Pool2DParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< Pool2DParams >
const Pool2DParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 30 of file L2Pool2D.h.
Constructor & Destructor Documentation
L2Pool2D() [1/2]
luci_interpreter::kernels::L2Pool2D::L2Pool2D (const Tensor * input, Tensor * output, const Pool2DParams & params)
Definition at line 32 of file L2Pool2D.cpp.
  : KernelWithParams<Pool2DParams>({input}, {output}, params)
{
}
References input().
L2Pool2D() [2/2]
luci_interpreter::kernels::L2Pool2D::L2Pool2D (const Tensor * input, Tensor * output, const Pool2DParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::L2Pool2D::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file L2Pool2D.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() == 4);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  int batches = input()->shape().dim(0);
  int height = input()->shape().dim(1);
  int width = input()->shape().dim(2);
  int channels_out = input()->shape().dim(3);
  // Matching GetWindowedOutputSize in TensorFlow.
  auto padding = params().padding;
  int out_width, out_height;
  out_width = computeOutputSize(padding, width, params().filter_width, params().stride_width, 1);
  out_height =
    computeOutputSize(padding, height, params().filter_height, params().stride_height, 1);
  _padding_width =
    computePadding(params().stride_width, 1, width, params().filter_width, out_width);
  _padding_height =
    computePadding(params().stride_height, 1, height, params().filter_height, out_height);
  LUCI_INTERPRETER_CHECK(input()->element_type() == DataType::FLOAT32);
  output()->resize({batches, out_height, out_width, channels_out});
}
References luci_interpreter::kernels::computeOutputSize(), luci_interpreter::kernels::computePadding(), luci_interpreter::Shape::dim(), input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::Pool2DParams::padding, luci_interpreter::KernelWithParams< Pool2DParams >::params(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::L2Pool2D::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::L2Pool2D::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 62 of file L2Pool2D.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      float activation_min, activation_max;
      calculateActivationRange(params().activation, &activation_min, &activation_max);
      tflite::PoolParams op_params;
      op_params.stride_height = params().stride_height;
      op_params.stride_width = params().stride_width;
      op_params.filter_height = params().filter_height;
      op_params.filter_width = params().filter_width;
      op_params.padding_values.height = _padding_height;
      op_params.padding_values.width = _padding_width;
      op_params.float_activation_min = activation_min;
      op_params.float_activation_max = activation_max;
      luci_interpreter_pal::L2Pool(op_params, getTensorShape(input()),
                                   getTensorData<float>(input()), getTensorShape(output()),
                                   getTensorData<float>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::kernels::calculateActivationRange(), luci_interpreter::Pool2DParams::filter_height, luci_interpreter::Pool2DParams::filter_width, luci_interpreter::kernels::getTensorShape(), input(), output(), luci_interpreter::KernelWithParams< Pool2DParams >::params(), luci_interpreter::Pool2DParams::stride_height, and luci_interpreter::Pool2DParams::stride_width.
execute() [2/2]
void luci_interpreter::kernels::L2Pool2D::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::L2Pool2D::input () const inline
Definition at line 35 of file L2Pool2D.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and L2Pool2D().
input() [2/2]
const Tensor * luci_interpreter::kernels::L2Pool2D::input () const inline
Definition at line 35 of file L2Pool2D.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::L2Pool2D::output () const inline
Definition at line 36 of file L2Pool2D.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::L2Pool2D::output () const inline
Definition at line 36 of file L2Pool2D.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/L2Pool2D.h
onert-micro/luci-interpreter/src/kernels/L2Pool2D.h
compiler/luci-interpreter/src/kernels/L2Pool2D.cpp
onert-micro/luci-interpreter/src/kernels/L2Pool2D.cpp