ONE - On-device Neural Engine: luci_interpreter::RuntimeGraph Class Reference
luci_interpreter::RuntimeGraph Class Reference
#include <RuntimeGraph.h>
Data Structures
class TensorAllocPlan
Public Member Functions
RuntimeGraph (RuntimeModule *owning_module, IMemoryManager *memory_manager)
~RuntimeGraph ()
Tensor * addTensor (std::unique_ptr< Tensor > &&tensor)
void setInputTensors (const std::vector< Tensor * > &input_tensors)
void setOutputTensors (const std::vector< Tensor * > &output_tensors)
void configureAllocations (Tensor *tensor)
const std::vector< Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
void addKernel (std::unique_ptr< Kernel > &&kernel)
void execute () const
RuntimeGraph ()=delete
RuntimeGraph (SimpleMemoryManager *memory_manager, CircleReader *circle_reader, RuntimeModule *runtime_module, uint32_t subgraph_index)
~RuntimeGraph ()
Tensor * addTensor (const circle::Tensor *raw_tensor, std::unique_ptr< Tensor > &&tensor)
const circle::Tensor * getCircleTensorByIndex (int32_t index)
void makeInplaceOperation (const circle::Tensor *src_tensor, const circle::Tensor *dst_tensor)
uint8_t * getDataByTensor (const circle::Tensor *raw_tensor)
uint8_t * getConstDataByTensor (const circle::Tensor *raw_tensor)
uint8_t * configureGraphInput (int32_t input_index)
void configureGraphInput (int32_t input_index, uint8_t *data)
int32_t getInputDataSizeByIndex (int32_t input_index)
int32_t getOutputDataSizeByIndex (int32_t output_index)
int32_t getNumOfInputTensors ()
int32_t getNumOfOutputTensors ()
const circle::Tensor * getInputTensorByIndex (int32_t input_index)
const circle::Tensor * getOutputTensorByIndex (int32_t input_index)
uint8_t * getOutputDataByIndex (int32_t output_index)
void addInplaceOpIndex (const circle::Operator *op)
void execute ()
void configure (bool dealloc_input)
void invalidate ()
bool isValid () const
void selectOwnSubgraph ()
void resetOutputTensorsData ()
void clearTensors ()
void setDataToTensor (const circle::Tensor *tensor, uint8_t *data)
void resetTensorData (uint8_t *new_data, const circle::Tensor *tensor)
RuntimeModule * getRuntimeModule ()
bool is_inplace_op (const circle::Operator *op)
void addDynamicShapeTensor (const circle::Tensor *tensor, luci_interpreter::RuntimeShape &&shapes)
luci_interpreter::RuntimeShape * getDynamicShapeTensor (const circle::Tensor *tensor)
void removeDynamicShapeTensor (const circle::Tensor *tensor)
Friends
class TensorAllocPlan
Detailed Description
Definition at line 32 of file RuntimeGraph.h.
Constructor & Destructor Documentation
RuntimeGraph() [1/3]
luci_interpreter::RuntimeGraph::RuntimeGraph (RuntimeModule * owning_module, IMemoryManager * memory_manager) explicit
Definition at line 103 of file RuntimeGraph.cpp.
  : _owning_module(owning_module), _memory_manager(memory_manager),
    _tensor_alloc_plan(std::make_unique<TensorAllocPlan>(memory_manager))
{
}
~RuntimeGraph() [1/2]
luci_interpreter::RuntimeGraph::~RuntimeGraph ()
Definition at line 109 of file RuntimeGraph.cpp.
{
  for (auto &tensor : _tensors)
  {
    if (tensor->is_data_allocated())
      _memory_manager->release_memory(*tensor);
  }
}
References luci_interpreter::IMemoryManager::release_memory().
RuntimeGraph() [2/3]
luci_interpreter::RuntimeGraph::RuntimeGraph () delete
RuntimeGraph() [3/3]
luci_interpreter::RuntimeGraph::RuntimeGraph (SimpleMemoryManager * memory_manager, CircleReader * circle_reader, RuntimeModule * runtime_module, uint32_t subgraph_index) explicit
Definition at line 27 of file RuntimeGraph.cpp.
  : _memory_manager(memory_manager),
    _tensor_to_data(std::unordered_map<const circle::Tensor *, uint8_t *>{}),
    _runtime_module(runtime_module), _reader(circle_reader),
    _inplace_op_indexes(std::unordered_set<const circle::Operator *>{}),
    _subgraph_index(subgraph_index)
{
}
~RuntimeGraph() [2/2]
luci_interpreter::RuntimeGraph::~RuntimeGraph ()
Member Function Documentation
addDynamicShapeTensor()
void luci_interpreter::RuntimeGraph::addDynamicShapeTensor (const circle::Tensor * tensor, luci_interpreter::RuntimeShape && shapes)
Definition at line 144 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  _dynamic_tensor_shapes[tensor] = std::move(shapes);
}
Referenced by luci_interpreter::execute_kernel_CircleReshape(), and luci_interpreter::execute_kernel_CircleSlice().
addInplaceOpIndex()
void luci_interpreter::RuntimeGraph::addInplaceOpIndex (const circle::Operator * op) inline
Definition at line 94 of file RuntimeGraph.h.
{ _inplace_op_indexes.insert(op); }
Referenced by luci_interpreter::GraphLoader::checkInplaceOps().
addKernel()
void luci_interpreter::RuntimeGraph::addKernel (std::unique_ptr< Kernel > && kernel)
Definition at line 144 of file RuntimeGraph.cpp.
{
  assert(kernel != nullptr);
  _kernels.push_back(std::move(kernel));
  _tensor_alloc_plan->invalidate();
}
Referenced by luci_interpreter::GraphLoader::loadOperators().
addTensor() [1/2]
Tensor * luci_interpreter::RuntimeGraph::addTensor (const circle::Tensor * raw_tensor, std::unique_ptr< Tensor > && tensor)
addTensor() [2/2]
Tensor * luci_interpreter::RuntimeGraph::addTensor (std::unique_ptr< Tensor > && tensor)
Definition at line 118 of file RuntimeGraph.cpp.
{
  assert(tensor != nullptr);
  _tensors.push_back(std::move(tensor));
  return _tensors.back().get();
}
Referenced by luci_interpreter::build_kernel_CircleAveragePool2D(), luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleConv2D(), luci_interpreter::build_kernel_CircleDepthwiseConv2D(), luci_interpreter::build_kernel_CircleMean(), luci_interpreter::build_kernel_CircleReduceMax(), luci_interpreter::build_kernel_CircleReduceProd(), luci_interpreter::build_kernel_CircleSum(), luci_interpreter::build_kernel_CircleSVDF(), luci_interpreter::build_kernel_CircleTransposeConv(), luci_interpreter::build_kernel_CircleUnidirectionalSequenceLSTM(), and luci_interpreter::GraphLoader::loadTensors().
clearTensors()
void luci_interpreter::RuntimeGraph::clearTensors ()
Definition at line 363 of file RuntimeGraph.cpp.
{ _tensor_to_data.clear(); }
configure()
void luci_interpreter::RuntimeGraph::configure (bool dealloc_input)
Definition at line 428 of file RuntimeGraph.cpp.
{
  selectOwnSubgraph();
  for (uint32_t i = 0; i < _reader->operators().size(); ++i)
  {
    const auto op = _reader->operators().at(i);
    assert(op != nullptr);
    const auto opcode = _reader->builtin_code(op);
    kernel_configure.configure_kernel(op, opcode, this);
  }
  if (not _is_valid)
    buildAllocDeallocPlan(dealloc_input);
  _is_valid = true;
}
References luci::VectorWrapper< T >::at(), luci::CircleReader::builtin_code(), luci_interpreter::KernelConfigureRegistry::configure_kernel(), luci_interpreter::kernel_configure, luci::CircleReader::operators(), selectOwnSubgraph(), and size.
Referenced by execute(), and luci_interpreter::ModuleLoader::load().
configureAllocations()
void luci_interpreter::RuntimeGraph::configureAllocations (Tensor * tensor)
Definition at line 139 of file RuntimeGraph.cpp.
{
  _memory_manager->allocate_memory(*tensor);
}
References luci_interpreter::IMemoryManager::allocate_memory().
configureGraphInput() [1/2]
uint8_t * luci_interpreter::RuntimeGraph::configureGraphInput (int32_t input_index)
Definition at line 245 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->inputs()[input_index];
  assert(tensor_index != -1);
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  auto *data = _memory_manager->allocate_memory(tensor);
  configureGraphInput(input_index, data);
  return data;
}
References luci_interpreter::IMemoryManager::allocate_memory(), configureGraphInput(), flatbuffers::data(), luci::CircleReader::inputs(), and luci::CircleReader::tensors().
Referenced by configureGraphInput().
configureGraphInput() [2/2]
void luci_interpreter::RuntimeGraph::configureGraphInput (int32_t input_index, uint8_t * data)
Definition at line 260 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  resetOutputTensorsData();
  const auto tensor_index = _reader->inputs()[input_index];
  assert(tensor_index != -1);
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  if (_tensor_to_data.find(tensor) != _tensor_to_data.end())
  {
    auto *data_prev = _tensor_to_data.at(tensor);
    if (data_prev != data)
      _memory_manager->release_memory(data_prev);
  }
  _tensor_to_data[tensor] = data;
}
References flatbuffers::data(), luci::CircleReader::inputs(), luci_interpreter::IMemoryManager::release_memory(), resetOutputTensorsData(), and luci::CircleReader::tensors().
execute() [1/2]
void luci_interpreter::RuntimeGraph::execute ()
Definition at line 453 of file RuntimeGraph.cpp.
{
  selectOwnSubgraph();
  if (not _is_valid)
    configure(true);
  const auto operators_size = _reader->operators().size();
  const auto operators = _reader->operators();
  for (uint32_t i = 0; i < operators_size; ++i)
  {
    const auto op = operators.at(i);
    assert(op != nullptr);
    const auto opcode = _reader->builtin_code(op);
    allocate(i);
    kernel_executor.execute_kernel(op, opcode, this);
    deallocate(i);
  }
#ifdef ENABLE_TRAINING
  if (_number_of_last_trainable_layers > 0)
  {
    const auto graph_output = _reader->outputs();
    assert(graph_output.size() == 1);
    const auto output_tensor = _reader->tensors()[graph_output[0]];
    uint8_t *output_data = _tensor_to_data.at(output_tensor);
    _gradient_calc_storage->saveDataToTensor(output_tensor, output_data);
    _tensor_to_data.erase(output_tensor);
  }
#endif // ENABLE_TRAINING
}
References luci::VectorWrapper< T >::at(), luci::CircleReader::builtin_code(), configure(), luci_interpreter::KernelExecuteRegistry::execute_kernel(), luci_interpreter::kernel_executor, luci::CircleReader::operators(), luci::CircleReader::outputs(), selectOwnSubgraph(), luci::VectorWrapper< T >::size(), and luci::CircleReader::tensors().
execute() [2/2]
void luci_interpreter::RuntimeGraph::execute () const
Definition at line 151 of file RuntimeGraph.cpp.
{
  if (!_tensor_alloc_plan->isValid())
    _tensor_alloc_plan->build(*this);
  EventNotifier *event_notifier = _owning_module->getEventNotifier();
  // Notify the observers that the input tensors have changed.
  if (event_notifier != nullptr)
  {
    for (const Tensor *input_tensor : getInputTensors())
    {
      if (input_tensor->is_observable())
        event_notifier->postTensorWrite(input_tensor);
    }
  }
  for (size_t index = 0; index < _kernels.size(); ++index)
  {
    const auto &kernel = _kernels[index];
    if (event_notifier != nullptr)
    {
      event_notifier->preOperatorExecute(kernel.get());
    }
    // TODO The `configure` method should only be called if the outputs of an operator need to be
    //  resized.
    kernel->configure();
    // Preallocate outputs in advance instead of relying on automatic allocation
    _tensor_alloc_plan->allocate(index);
    kernel->execute();
    if (event_notifier != nullptr)
    {
      event_notifier->postOperatorExecute(kernel.get());
    }
    for (const Tensor *tensor : kernel->getOutputTensors())
    {
      if (event_notifier != nullptr && tensor->is_observable())
      {
        event_notifier->postTensorWrite(tensor);
      }
    }
    _tensor_alloc_plan->deallocate(index);
  }
}
References luci_interpreter::RuntimeModule::getEventNotifier(), getInputTensors(), luci_interpreter::EventNotifier::postOperatorExecute(), luci_interpreter::EventNotifier::postTensorWrite(), and luci_interpreter::EventNotifier::preOperatorExecute().
Referenced by luci_interpreter::RuntimeModule::execute(), and luci_interpreter::kernels::While::execute().
getCircleTensorByIndex()
const circle::Tensor * luci_interpreter::RuntimeGraph::getCircleTensorByIndex (int32_t index)
Definition at line 417 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  if (index < 0)
    return nullptr;
  const auto raw_tensor = _reader->tensors()[index];
  return raw_tensor;
}
References luci::CircleReader::tensors().
Referenced by luci_interpreter::configure_kernel_CircleAbs(), luci_interpreter::configure_kernel_CircleAddN(), luci_interpreter::configure_kernel_CircleAveragePool2D(), luci_interpreter::configure_kernel_CircleConcatenation(), luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::configure_kernel_CircleExpandDims(), luci_interpreter::configure_kernel_CircleFloor(), luci_interpreter::configure_kernel_CircleFullyConnected(), luci_interpreter::configure_kernel_CircleLogistic(), luci_interpreter::configure_kernel_CircleMaxPool2D(), luci_interpreter::configure_kernel_CircleNeg(), luci_interpreter::configure_kernel_CirclePadCommon(), luci_interpreter::configure_kernel_CircleResizeBilinear(), luci_interpreter::configure_kernel_CircleSelectV2(), luci_interpreter::configure_kernel_CircleSplit(), luci_interpreter::configure_kernel_CircleSplitV(), luci_interpreter::configure_kernel_CircleTransposeConv(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleAddN(), luci_interpreter::execute_kernel_CircleAveragePool2D(), luci_interpreter::execute_kernel_CircleConcatenation(), luci_interpreter::execute_kernel_CircleConv2D(), luci_interpreter::execute_kernel_CircleDepthwiseConv2D(), luci_interpreter::execute_kernel_CircleExpandDims(), luci_interpreter::execute_kernel_CircleFloor(), luci_interpreter::execute_kernel_CircleFullyConnected(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleMaxPool2D(), luci_interpreter::execute_kernel_CircleNeg(), luci_interpreter::execute_kernel_CirclePack(), luci_interpreter::execute_kernel_CirclePadCommon(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleResizeBilinear(), luci_interpreter::execute_kernel_CircleSelectV2(), luci_interpreter::execute_kernel_CircleSplit(), luci_interpreter::execute_kernel_CircleSplitV(), luci_interpreter::execute_kernel_CircleTransposeConv(), luci_interpreter::execute_kernel_CircleUnidirectionalSequenceLSTM(), luci_interpreter::lstm::LSTMStruct::LSTMStruct(), luci_interpreter::kernels::MISOKernel::MISOKernel(), luci_interpreter::kernels::SISOKernel::SISOKernel(), luci_interpreter::splitImpl(), and luci_interpreter::kernels::TISOKernel::TISOKernel().
getConstDataByTensor()
uint8_t * luci_interpreter::RuntimeGraph::getConstDataByTensor (const circle::Tensor * raw_tensor)
Definition at line 391 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  if (raw_tensor == nullptr)
    return nullptr;
#ifdef ENABLE_TRAINING
  assert(_number_of_last_trainable_layers == 0 or
         _storage != nullptr && "Storage should not be null here");
  if (_storage != nullptr)
  {
    uint8_t *result = nullptr;
    _storage->getTrainWeightDataByTensor(raw_tensor, &result);
    if (result != nullptr)
      return result;
  }
#endif // ENABLE_TRAINING
  auto const &buffer = wrap(_reader->buffers()[raw_tensor->buffer()]->data());
  return const_cast<uint8_t *>(buffer.data());
}
References luci::CircleReader::buffers(), luci::VectorWrapper< T >::data(), and luci::wrap().
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate(), luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::configure_kernel_CircleExpandDims(), luci_interpreter::configure_kernel_CircleMean(), luci_interpreter::configure_kernel_CirclePadCommon(), luci_interpreter::configure_kernel_CircleReduceMax(), luci_interpreter::configure_kernel_CircleSplitV(), luci_interpreter::configure_kernel_CircleSum(), luci_interpreter::configure_kernel_CircleTranspose(), luci_interpreter::configure_kernel_CircleTransposeConv(), luci_interpreter::execute_kernel_CircleBatchToSpaceND(), luci_interpreter::execute_kernel_CircleGatherND(), luci_interpreter::execute_kernel_CircleLogicalAnd(), luci_interpreter::execute_kernel_CircleLogicalNot(), luci_interpreter::execute_kernel_CircleLogicalOr(), luci_interpreter::execute_kernel_CirclePadCommon(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleResizeBilinear(), luci_interpreter::execute_kernel_CircleSlice(), luci_interpreter::execute_kernel_CircleSpaceToBatchND(), luci_interpreter::execute_kernel_CircleSplit(), luci_interpreter::execute_kernel_CircleSplitV(), luci_interpreter::execute_kernel_CircleStridedSlice(), luci_interpreter::kernels::TISOKernel::readData(), and luci_interpreter::kernels::TISOKernel::readInplaceData().
getDataByTensor()
uint8_t * luci_interpreter::RuntimeGraph::getDataByTensor (const circle::Tensor * raw_tensor)
Definition at line 348 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  if (raw_tensor == nullptr)
    return nullptr;
  if (_tensor_to_data.find(raw_tensor) == _tensor_to_data.end())
  {
    return nullptr;
  }
  return _tensor_to_data.at(raw_tensor);
}
Referenced by luci_interpreter::evalInteger(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleAveragePool2D(), luci_interpreter::execute_kernel_CircleBatchToSpaceND(), luci_interpreter::execute_kernel_CircleBroadcastTo(), luci_interpreter::execute_kernel_CircleCast(), luci_interpreter::execute_kernel_CircleCeil(), luci_interpreter::execute_kernel_CircleCos(), luci_interpreter::execute_kernel_CircleDepthToSpace(), luci_interpreter::execute_kernel_CircleDequantize(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleExpandDims(), luci_interpreter::execute_kernel_CircleFloor(), luci_interpreter::execute_kernel_CircleFloorDiv(), luci_interpreter::execute_kernel_CircleFloorMod(), luci_interpreter::execute_kernel_CircleGatherND(), luci_interpreter::execute_kernel_CircleL2Normalize(), luci_interpreter::execute_kernel_CircleL2Pool2D(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLog(), luci_interpreter::execute_kernel_CircleLogicalAnd(), luci_interpreter::execute_kernel_CircleLogicalNot(), luci_interpreter::execute_kernel_CircleLogicalOr(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleLogSoftmax(), luci_interpreter::execute_kernel_CircleMaximum(), luci_interpreter::execute_kernel_CircleMaxPool2D(), luci_interpreter::execute_kernel_CircleMinimum(), luci_interpreter::execute_kernel_CircleNeg(), luci_interpreter::execute_kernel_CirclePack(), luci_interpreter::execute_kernel_CirclePadCommon(), luci_interpreter::execute_kernel_CircleQuantize(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleResizeBilinear(), luci_interpreter::execute_kernel_CircleRound(), luci_interpreter::execute_kernel_CircleRsqrt(), luci_interpreter::execute_kernel_CircleShape(), luci_interpreter::execute_kernel_CircleSin(), luci_interpreter::execute_kernel_CircleSlice(), luci_interpreter::execute_kernel_CircleSpaceToBatchND(), luci_interpreter::execute_kernel_CircleSpaceToDepth(), luci_interpreter::execute_kernel_CircleSplit(), luci_interpreter::execute_kernel_CircleSplitV(), luci_interpreter::execute_kernel_CircleSqrt(), luci_interpreter::execute_kernel_CircleSquare(), luci_interpreter::execute_kernel_CircleSquaredDifference(), luci_interpreter::execute_kernel_CircleStridedSlice(), luci_interpreter::execute_kernel_CircleTanh(), luci_interpreter::execute_kernel_CircleZerosLike(), luci_interpreter_pal::lstm_internal::lstmStep(), luci_interpreter::kernels::TISOKernel::readData(), luci_interpreter::kernels::TISOKernel::readInplaceData(), and luci_interpreter::splitImpl().
getDynamicShapeTensor()
luci_interpreter::RuntimeShape * luci_interpreter::RuntimeGraph::getDynamicShapeTensor (const circle::Tensor * tensor)
Definition at line 151 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  auto it = _dynamic_tensor_shapes.find(tensor);
  return it == _dynamic_tensor_shapes.end() ? nullptr : &_dynamic_tensor_shapes[tensor];
}
Referenced by luci_interpreter::kernels::getTensorDims(), and luci_interpreter::kernels::getTensorRuntimeShape().
getInputDataSizeByIndex()
int32_t luci_interpreter::RuntimeGraph::getInputDataSizeByIndex (int32_t input_index)
Definition at line 279 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->inputs()[input_index];
  assert(tensor_index != -1);
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  return Tensor::num_elements(tensor) * size(Tensor::element_type(tensor));
}
References luci::CircleReader::inputs(), size, and luci::CircleReader::tensors().
getInputTensorByIndex()
const circle::Tensor * luci_interpreter::RuntimeGraph::getInputTensorByIndex (int32_t input_index)
Definition at line 302 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->inputs()[input_index];
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  return tensor;
}
References luci::CircleReader::inputs(), and luci::CircleReader::tensors().
getInputTensors()
const std::vector< Tensor * > & luci_interpreter::RuntimeGraph::getInputTensors () const inline
Definition at line 49 of file RuntimeGraph.h.
{ return _input_tensors; }
Referenced by luci_interpreter::kernels::While::configure(), execute(), luci_interpreter::kernels::If::execute(), luci_interpreter::kernels::While::execute(), and luci_interpreter::RuntimeModule::getInputTensors().
getNumOfInputTensors()
int32_t luci_interpreter::RuntimeGraph::getNumOfInputTensors ()
Definition at line 290 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  return _reader->inputs().size();
}
References luci::CircleReader::inputs().
getNumOfOutputTensors()
int32_t luci_interpreter::RuntimeGraph::getNumOfOutputTensors ()
Definition at line 296 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  return _reader->outputs().size();
}
References luci::CircleReader::outputs().
getOutputDataByIndex()
uint8_t * luci_interpreter::RuntimeGraph::getOutputDataByIndex (int32_t output_index)
Definition at line 334 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->outputs()[output_index];
  assert(tensor_index != -1);
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  assert(_tensor_to_data.find(tensor) != _tensor_to_data.end());
  return _tensor_to_data[tensor];
}
References luci::CircleReader::outputs(), and luci::CircleReader::tensors().
getOutputDataSizeByIndex()
int32_t luci_interpreter::RuntimeGraph::getOutputDataSizeByIndex (int32_t output_index)
Definition at line 322 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->outputs()[output_index];
  assert(tensor_index != -1);
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  return Tensor::num_elements(tensor) * size(Tensor::element_type(tensor));
}
References luci::CircleReader::outputs(), size, and luci::CircleReader::tensors().
getOutputTensorByIndex()
const circle::Tensor * luci_interpreter::RuntimeGraph::getOutputTensorByIndex (int32_t input_index)
Definition at line 312 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto tensor_index = _reader->outputs()[input_index];
  const auto tensor = _reader->tensors()[tensor_index];
  assert(tensor != nullptr);
  return tensor;
}
References luci::CircleReader::outputs(), and luci::CircleReader::tensors().
getOutputTensors()
const std::vector< Tensor * > & luci_interpreter::RuntimeGraph::getOutputTensors () const inline
Definition at line 50 of file RuntimeGraph.h.
{ return _output_tensors; }
Referenced by luci_interpreter::kernels::While::configure(), luci_interpreter::kernels::While::execute(), and luci_interpreter::RuntimeModule::getOutputTensors().
getRuntimeModule()
RuntimeModule * luci_interpreter::RuntimeGraph::getRuntimeModule () inline
Definition at line 111 of file RuntimeGraph.h.
{ return _runtime_module; };
Referenced by luci_interpreter::configure_kernel_CircleWhile(), and luci_interpreter::execute_kernel_CircleWhile().
invalidate()
void luci_interpreter::RuntimeGraph::invalidate () inline
Definition at line 99 of file RuntimeGraph.h.
{ _is_valid = false; }
Referenced by luci_interpreter::RuntimeGraph::TensorAllocPlan::build().
is_inplace_op()
bool luci_interpreter::RuntimeGraph::is_inplace_op (const circle::Operator * op) inline
Definition at line 113 of file RuntimeGraph.h.
  {
    return _inplace_op_indexes.find(op) != _inplace_op_indexes.end();
  }
Referenced by luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleAdd(), luci_interpreter::execute_kernel_CircleCeil(), luci_interpreter::execute_kernel_CircleCos(), luci_interpreter::execute_kernel_CircleDiv(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleExpandDims(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLog(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleMul(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleRound(), luci_interpreter::execute_kernel_CircleRsqrt(), luci_interpreter::execute_kernel_CircleSin(), luci_interpreter::execute_kernel_CircleSqrt(), luci_interpreter::execute_kernel_CircleSquare(), luci_interpreter::execute_kernel_CircleSub(), luci_interpreter::execute_kernel_CircleTanh(), luci_interpreter::execute_kernel_CircleUnidirectionalSequenceLSTM(), luci_interpreter::execute_kernel_CircleWhile(), and luci_interpreter::execute_kernel_CircleZerosLike().
isValid()
bool luci_interpreter::RuntimeGraph::isValid () const inline
Definition at line 100 of file RuntimeGraph.h.
{ return _is_valid; }
makeInplaceOperation()
void luci_interpreter::RuntimeGraph::makeInplaceOperation (const circle::Tensor * src_tensor, const circle::Tensor * dst_tensor)
Definition at line 365 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  assert(removing_tensor != nullptr);
  auto src_it = _tensor_to_data.find(removing_tensor);
  if (src_it == _tensor_to_data.end())
    return;
  auto *data = _tensor_to_data[removing_tensor];
  _tensor_to_data.erase(src_it);
  if (dst_tensor == nullptr)
  {
    delete[] data;
    return;
  }
  assert(_tensor_to_data.find(dst_tensor) == _tensor_to_data.end() &&
         "Failed makeInplaceOperation");
  _tensor_to_data[dst_tensor] = data;
}
References flatbuffers::data().
Referenced by luci_interpreter::kernels::evalTISOInplaceKernel(), luci_interpreter::kernels::evalTISOInplaceQuantizedKernel(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleCeil(), luci_interpreter::execute_kernel_CircleCos(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleExpandDims(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLog(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleRound(), luci_interpreter::execute_kernel_CircleRsqrt(), luci_interpreter::execute_kernel_CircleSin(), luci_interpreter::execute_kernel_CircleSqrt(), luci_interpreter::execute_kernel_CircleSquare(), luci_interpreter::execute_kernel_CircleTanh(), and luci_interpreter::execute_kernel_CircleZerosLike().
removeDynamicShapeTensor()
void luci_interpreter::RuntimeGraph::removeDynamicShapeTensor (const circle::Tensor * tensor)
Definition at line 159 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  auto it = _dynamic_tensor_shapes.find(tensor);
  assert(it != _dynamic_tensor_shapes.end());
  _dynamic_tensor_shapes.erase(it);
}
resetOutputTensorsData()
void luci_interpreter::RuntimeGraph::resetOutputTensorsData ()
Definition at line 220 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  const auto graph_inputs = _reader->inputs();
  for (int i = 0; i < _reader->outputs().size(); ++i)
  {
    const auto tensor_index = _reader->outputs()[i];
    assert(tensor_index != -1);
    if (std::find(graph_inputs.begin(), graph_inputs.end(), tensor_index) != graph_inputs.end())
      return;
    const auto tensor = _reader->tensors()[tensor_index];
    assert(tensor != nullptr);
    auto tensor_it = _tensor_to_data.find(tensor);
    if (tensor_it != _tensor_to_data.end())
    {
      auto *data = _tensor_to_data.at(tensor);
      _memory_manager->release_memory(data);
      _tensor_to_data.erase(tensor_it);
    }
  }
}
References flatbuffers::data(), luci::CircleReader::inputs(), luci::CircleReader::outputs(), luci_interpreter::IMemoryManager::release_memory(), size, and luci::CircleReader::tensors().
Referenced by configureGraphInput().
resetTensorData()
void luci_interpreter::RuntimeGraph::resetTensorData (uint8_t * new_data, const circle::Tensor * tensor)
Definition at line 207 of file RuntimeGraph.cpp.
{
  assert(_reader->get_current_subgraph_index() == _subgraph_index);
  auto tensor_it = _tensor_to_data.find(tensor);
  if (tensor_it != _tensor_to_data.end())
  {
    auto *data = _tensor_to_data.at(tensor);
    _memory_manager->release_memory(data);
  }
  _tensor_to_data[tensor] = new_data;
}
References flatbuffers::data(), and luci_interpreter::IMemoryManager::release_memory().
Referenced by luci_interpreter::execute_kernel_CircleReshape(), and luci_interpreter::execute_kernel_CircleSlice().
selectOwnSubgraph()
void luci_interpreter::RuntimeGraph::selectOwnSubgraph () inline
Definition at line 102 of file RuntimeGraph.h.
{ _reader->select_subgraph(_subgraph_index); };
Referenced by configure(), and execute().
setDataToTensor()
void luci_interpreter::RuntimeGraph::setDataToTensor (const circle::Tensor * tensor, uint8_t * data)
Definition at line 448 of file RuntimeGraph.cpp.
{
  _tensor_to_data[tensor] = data;
}
References flatbuffers::data().
setInputTensors()
void luci_interpreter::RuntimeGraph::setInputTensors (const std::vector< Tensor * > & input_tensors)
Definition at line 125 of file RuntimeGraph.cpp.
{
  assert(std::all_of(input_tensors.cbegin(), input_tensors.cend(),
                     [](Tensor *tensor) { return tensor != nullptr; }));
  _input_tensors = input_tensors;
}
Referenced by luci_interpreter::GraphLoader::initInputOutputTensors().
setOutputTensors()
void luci_interpreter::RuntimeGraph::setOutputTensors (const std::vector< Tensor * > & output_tensors)
Definition at line 132 of file RuntimeGraph.cpp.
{
  assert(std::all_of(output_tensors.cbegin(), output_tensors.cend(),
                     [](Tensor *tensor) { return tensor != nullptr; }));
  _output_tensors = output_tensors;
}
Referenced by luci_interpreter::GraphLoader::initInputOutputTensors().
Friends And Related Function Documentation
TensorAllocPlan
friend class TensorAllocPlan friend
Definition at line 36 of file RuntimeGraph.h.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/core/RuntimeGraph.h
onert-micro/luci-interpreter/src/core/RuntimeGraph.h
compiler/luci-interpreter/src/core/RuntimeGraph.cpp
onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp