ONE - On-device Neural Engine: onert::backend::cpu::ops::BinaryArithmeticLayer Class Reference
onert::backend::cpu::ops::BinaryArithmeticLayer Class Reference
#include <BinaryArithmeticLayer.h>
Public Member Functions
BinaryArithmeticLayer ()
void configure (const IPortableTensor *lhs, const IPortableTensor *rhs, IPortableTensor *output, const ir::Activation activation, const ArithmeticType arithmetic_type)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Protected Attributes
const IPortableTensor * _lhs
const IPortableTensor * _rhs
IPortableTensor * _output
std::function< void(const IPortableTensor *, const IPortableTensor *, IPortableTensor *)> _kernel
Detailed Description
Definition at line 42 of file BinaryArithmeticLayer.h.
Constructor & Destructor Documentation
BinaryArithmeticLayer()
onert::backend::cpu::ops::BinaryArithmeticLayer::BinaryArithmeticLayer () inline
Definition at line 45 of file BinaryArithmeticLayer.h.
                          : _lhs(nullptr), _rhs(nullptr), _output(nullptr)
  {
    // DO NOTHING
  }
Member Function Documentation
configure()
void onert::backend::cpu::ops::BinaryArithmeticLayer::configure (const IPortableTensor * lhs, const IPortableTensor * rhs, IPortableTensor * output, const ir::Activation activation, const ArithmeticType arithmetic_type)
Definition at line 177 of file BinaryArithmeticLayer.cc.
{
  assert(lhs != nullptr);
  assert(rhs != nullptr);
  assert(output != nullptr);
  _lhs = lhs;
  _rhs = rhs;
  _output = output;
  nnfw::cker::BinaryArithmeticOpParam op_params;
  switch (arithmetic_type)
  {
    case ArithmeticType::kAdd:
      if (_lhs->data_type() == OperandType::QUANT_UINT8_ASYMM)
      {
        setAddOrSubQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::ADD, uint8_t>(_lhs, _rhs, _output, op_params);
      }
      else if (_lhs->data_type() == OperandType::QUANT_INT8_ASYMM)
      {
        setAddOrSubQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::ADD, int8_t>(_lhs, _rhs, _output, op_params);
      }
      else
      {
        _kernel = generateKernelGeneric<nnfw::cker::BinaryArithmeticOpType::ADD>(
          _lhs, _rhs, _output, activation, op_params);
      }
      break;
    case ArithmeticType::kSub:
      if (_lhs->data_type() == OperandType::QUANT_UINT8_ASYMM)
      {
        setAddOrSubQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        op_params.input2_multiplier *= -1;
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::SUB, uint8_t>(_lhs, _rhs, _output, op_params);
      }
      else if (_lhs->data_type() == OperandType::QUANT_INT8_ASYMM)
      {
        setAddOrSubQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        op_params.input2_multiplier *= -1;
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::SUB, int8_t>(_lhs, _rhs, _output, op_params);
      }
      else
      {
        _kernel = generateKernelGeneric<nnfw::cker::BinaryArithmeticOpType::SUB>(
          _lhs, _rhs, _output, activation, op_params);
      }
      break;
    case ArithmeticType::kMul:
      if (_lhs->data_type() == OperandType::QUANT_UINT8_ASYMM)
      {
        nnfw::cker::BinaryArithmeticOpParam op_params;
        setMulQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::MUL, uint8_t>(_lhs, _rhs, _output, op_params);
      }
      else if (_lhs->data_type() == OperandType::QUANT_INT8_ASYMM)
      {
        nnfw::cker::BinaryArithmeticOpParam op_params;
        setMulQuant8Params(_lhs, _rhs, _output, activation, &op_params);
        _kernel =
          Eval<nnfw::cker::BinaryArithmeticOpType::MUL, int8_t>(_lhs, _rhs, _output, op_params);
      }
      else
      {
        _kernel = generateKernelGeneric<nnfw::cker::BinaryArithmeticOpType::MUL>(
          _lhs, _rhs, _output, activation, op_params);
      }
      break;
    case ArithmeticType::kDiv:
      if (_lhs->data_type() == OperandType::QUANT_UINT8_ASYMM)
      {
        throw std::runtime_error{
          "BinaryArithmetic(Div): Div operation does not support quantization"};
      }
      else if (_lhs->data_type() == OperandType::INT32)
      {
        throw std::runtime_error{"BinaryArithmetic(Div): Unsupported data type"};
      }
      else
      {
        _kernel = generateKernelGeneric<nnfw::cker::BinaryArithmeticOpType::DIV>(
          _lhs, _rhs, _output, activation, op_params);
      }
      break;
    default:
      throw std::runtime_error{"BinaryArithmetic: Unsupported BinaryArithmetic type"};
  }
}
References _kernel, _lhs, _output, _rhs, onert::backend::ITensor::data_type(), nnfw::cker::BinaryArithmeticOpParam::input2_multiplier, onert::backend::cpu::ops::kAdd, onert::backend::cpu::ops::kDiv, onert::backend::cpu::ops::kMul, and onert::backend::cpu::ops::kSub.
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::configure().
run()
void onert::backend::cpu::ops::BinaryArithmeticLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 276 of file BinaryArithmeticLayer.cc.
{ _kernel(_lhs, _rhs, _output); }
References _kernel, _lhs, _output, and _rhs.
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::forward(), and package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
Field Documentation
_kernel
std::function<void(const IPortableTensor *, const IPortableTensor *, IPortableTensor *)> onert::backend::cpu::ops::BinaryArithmeticLayer::_kernel protected
Definition at line 61 of file BinaryArithmeticLayer.h.
Referenced by configure(), and run().
_lhs
const IPortableTensor* onert::backend::cpu::ops::BinaryArithmeticLayer::_lhs protected
Definition at line 57 of file BinaryArithmeticLayer.h.
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::backward(), configure(), and run().
_output
IPortableTensor* onert::backend::cpu::ops::BinaryArithmeticLayer::_output protected
Definition at line 59 of file BinaryArithmeticLayer.h.
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::backward(), configure(), and run().
_rhs
const IPortableTensor* onert::backend::cpu::ops::BinaryArithmeticLayer::_rhs protected
Definition at line 58 of file BinaryArithmeticLayer.h.
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::backward(), configure(), and run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.h
runtime/onert/backend/cpu/ops/BinaryArithmeticLayer.cc