ONE - On-device Neural Engine: nnfw::cker::Conv Class Reference
nnfw::cker::Conv Class Reference
#include <Conv.h>
Public Member Functions
Conv ()
void prepareF32 (const Shape &filter_shape, const float *filter_data, PaddingType padding_type, bool &is_replaced_weights, uint32_t dilationWidthFactor, uint32_t dilationHeightFactor)
void prepareQ8uPerTensor (const Shape &input_shape, const Shape &kernel_shape, const Shape &output_shape, uint32_t stride_width, uint32_t stride_height, uint32_t dilation_width_factor, uint32_t dilation_height_factor)
void operator() (const ConvParams &params, const Shape &input_shape, const float *input_data, const Shape &filter_shape, const float *filter_data, const Shape &bias_shape, const float *bias_data, const Shape &output_shape, float *output_data)
void operator() (const ConvParams &params, const Shape &input_shape, const uint8_t *input_data, const Shape &filter_shape, const uint8_t *filter_data, const Shape &bias_shape, const int32_t *bias_data, const Shape &output_shape, uint8_t *output_data)
void operator() (const ConvParams &params, const Shape &input_shape, const uint8_t *input_data, const Shape &filter_shape, const uint8_t *filter_data, const int32_t *filter_zero_point, const Shape &bias_shape, const int32_t *bias_data, const Shape &output_shape, uint8_t *output_data)
void operator() (const ConvParams &params, const Shape &input_shape, const int8_t *input_data, const Shape &filter_shape, const int8_t *filter_data, const Shape &bias_shape, const int32_t *bias_data, const Shape &output_shape, int8_t *output_data)
std::vector< int32_t > & per_channel_output_multiplier ()
std::vector< int > & per_channel_output_shift ()
Detailed Description
Definition at line 55 of file Conv.h.
Constructor & Destructor Documentation
Conv()
nnfw::cker::Conv::Conv () inline
Definition at line 58 of file Conv.h.
: _modified_filter_data(), _im2col_shape(4), _need_im2col(false), _prepared(false) {}
Member Function Documentation
operator()() [1/4]
void nnfw::cker::Conv::operator() (const ConvParams & params, const Shape & input_shape, const float * input_data, const Shape & filter_shape, const float * filter_data, const Shape & bias_shape, const float * bias_data, const Shape & output_shape, float * output_data) inline
Definition at line 86 of file Conv.h.
  {
    if (usableMultiThreaded(params.padding_type, params.dilation_width_factor,
                            params.dilation_height_factor))
    {
      bool transposed_in_execution = false;
      if (!_prepared)
      {
        // This means that filter is not constant
        // TODO Apply optimized kernel if multithreaded kernel is slower than optimized kernel by
        // transposing filter data
        transposeFilter(filter_shape, filter_data, transposed_in_execution);
      }
      multithreaded::Conv(params, input_shape, input_data, filter_shape, &_modified_filter_data[0],
                          bias_shape, bias_data, output_shape, output_data);
    }
    else
    {
      // TODO Support optimized kernel
      reference::Conv(params, input_shape, input_data, filter_shape, filter_data, bias_shape,
                      bias_data, output_shape, output_data);
    }
  }
References nnfw::cker::multithreaded::Conv(), nnfw::cker::reference::Conv(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, and nnfw::cker::ConvParams::padding_type.
operator()() [2/4]
void nnfw::cker::Conv::operator() (const ConvParams & params, const Shape & input_shape, const int8_t * input_data, const Shape & filter_shape, const int8_t * filter_data, const Shape & bias_shape, const int32_t * bias_data, const Shape & output_shape, int8_t * output_data) inline
Definition at line 152 of file Conv.h.
  {
    reference::Conv<int8_t, false>(params, _per_channel_output_multiplier.data(),
                                   _per_channel_output_shift.data(), input_shape, input_data,
                                   filter_shape, filter_data, nullptr /* filter_zero_point */,
                                   bias_shape, bias_data, output_shape, output_data);
  }
operator()() [3/4]
void nnfw::cker::Conv::operator() (const ConvParams & params, const Shape & input_shape, const uint8_t * input_data, const Shape & filter_shape, const uint8_t * filter_data, const int32_t * filter_zero_point, const Shape & bias_shape, const int32_t * bias_data, const Shape & output_shape, uint8_t * output_data) inline
Definition at line 141 of file Conv.h.
  {
    reference::Conv<uint8_t, true>(params, _per_channel_output_multiplier.data(),
                                   _per_channel_output_shift.data(), input_shape, input_data,
                                   filter_shape, filter_data, filter_zero_point, bias_shape,
                                   bias_data, output_shape, output_data);
  }
operator()() [4/4]
void nnfw::cker::Conv::operator() (const ConvParams & params, const Shape & input_shape, const uint8_t * input_data, const Shape & filter_shape, const uint8_t * filter_data, const Shape & bias_shape, const int32_t * bias_data, const Shape & output_shape, uint8_t * output_data) inline
Definition at line 112 of file Conv.h.
  {
    if (!_prepared)
    {
      // This means that input or output are dynamic or filter is not constant
      IsRequiredIm2col(input_shape, filter_shape, output_shape, params.stride_width,
                       params.stride_height, params.dilation_width_factor,
                       params.dilation_height_factor);
    }
    int im2col_size = _need_im2col ? _im2col_shape.FlatSize() : 1;
    // Use heap if size is larger than 8MB
    if (im2col_size > 8 * 1024 * 1024)
    {
      std::unique_ptr<uint8_t[]> im2col_data = std::make_unique<uint8_t[]>(im2col_size);
      optimized::Conv(params, input_shape, input_data, filter_shape, filter_data, bias_shape,
                      bias_data, output_shape, output_data, _im2col_shape, im2col_data.get());
    }
    else
    {
      uint8_t im2col_data[im2col_size];
      optimized::Conv(params, input_shape, input_data, filter_shape, filter_data, bias_shape,
                      bias_data, output_shape, output_data, _im2col_shape, im2col_data);
    }
  }
References nnfw::cker::optimized::Conv(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, nnfw::cker::Shape::FlatSize(), nnfw::cker::ConvParams::stride_height, and nnfw::cker::ConvParams::stride_width.
per_channel_output_multiplier()
std::vector< int32_t > & nnfw::cker::Conv::per_channel_output_multiplier () inline
Definition at line 161 of file Conv.h.
{ return _per_channel_output_multiplier; }
Referenced by onert::backend::cpu::ops::ConvolutionLayer::prepare().
per_channel_output_shift()
std::vector< int > & nnfw::cker::Conv::per_channel_output_shift () inline
Definition at line 162 of file Conv.h.
{ return _per_channel_output_shift; }
Referenced by onert::backend::cpu::ops::ConvolutionLayer::prepare().
prepareF32()
void nnfw::cker::Conv::prepareF32 (const Shape & filter_shape, const float * filter_data, PaddingType padding_type, bool & is_replaced_weights, uint32_t dilationWidthFactor, uint32_t dilationHeightFactor) inline
Definition at line 60 of file Conv.h.
  {
    if (!_prepared)
    {
      if (usableMultiThreaded(padding_type, dilationWidthFactor, dilationHeightFactor))
      {
        transposeFilter(filter_shape, filter_data, is_replaced_weights);
      }
      _prepared = true;
    }
  }
Referenced by onert::backend::cpu::ops::ConvolutionLayer::prepare().
prepareQ8uPerTensor()
void nnfw::cker::Conv::prepareQ8uPerTensor (const Shape & input_shape, const Shape & kernel_shape, const Shape & output_shape, uint32_t stride_width, uint32_t stride_height, uint32_t dilation_width_factor, uint32_t dilation_height_factor) inline
Definition at line 74 of file Conv.h.
  {
    if (!_prepared)
    {
      IsRequiredIm2col(input_shape, kernel_shape, output_shape, stride_width, stride_height,
                       dilation_width_factor, dilation_height_factor);
      _prepared = true;
    }
  }
Referenced by onert::backend::cpu::ops::ConvolutionLayer::prepare().
The documentation for this class was generated from the following file:
compute/cker/include/cker/operation/Conv.h