ONE - On-device Neural Engine: EventWriter Class Reference
EventWriter Class Reference
#include <EventWriter.h>
Public Types
enum class WriteFormat { CHROME_TRACING , SNPE_BENCHMARK , MD_TABLE }
Public Member Functions
void startToUse ()
Call this when observer which use EventWriter starts.
void readyToFlush (std::unique_ptr< EventRecorder > &&recorder)
Call this when observer which use EventWriter finishes. After multiple observers calls this method, the reference count will eventually be 0. Then, EventWriter will write profiling result file.
Static Public Member Functions
static EventWriter * get (const std::string &filename)
Retuens a singleton object.
Detailed Description
Definition at line 80 of file EventWriter.h.
Member Enumeration Documentation
WriteFormat
enum class EventWriter::WriteFormat strong
Enumerator
CHROME_TRACING
SNPE_BENCHMARK
MD_TABLE
Definition at line 83 of file EventWriter.h.
  {
    CHROME_TRACING,
    SNPE_BENCHMARK,
    MD_TABLE,
  };
Member Function Documentation
get()
static EventWriter * EventWriter::get (const std::string & filename) inline static
Retuens a singleton object.
Definition at line 93 of file EventWriter.h.
  {
    std::unique_lock<std::mutex> lock{_mutex};
    static EventWriter singleton(filename);
    return &singleton;
  }
Referenced by onert::exec::TracingObserver::TracingObserver().
readyToFlush()
void EventWriter::readyToFlush (std::unique_ptr< EventRecorder > && recorder)
Call this when observer which use EventWriter finishes. After multiple observers calls this method, the reference count will eventually be 0. Then, EventWriter will write profiling result file.
Definition at line 24 of file EventWriter.cc.
{
  {
    std::unique_lock<std::mutex> lock{_mutex};
    _recorders.emplace_back(std::move(recorder));
    if (--_ref_count > 0)
      return;
  }
  // The caller of this method is the last instance that uses EventWriter.
  // Let's write log files.
  // Note. According to an internal issue, let snpe json as just file name not '.snpe.json'
  flush(WriteFormat::SNPE_BENCHMARK);
  flush(WriteFormat::CHROME_TRACING);
  flush(WriteFormat::MD_TABLE);
}
References CHROME_TRACING, MD_TABLE, and SNPE_BENCHMARK.
Referenced by onert::exec::TracingObserver::~TracingObserver().
startToUse()
void EventWriter::startToUse () inline
Call this when observer which use EventWriter starts.
Definition at line 104 of file EventWriter.h.
  {
    std::unique_lock<std::mutex> lock{_mutex};
    _ref_count++;
  }
Referenced by onert::exec::TracingObserver::TracingObserver().
The documentation for this class was generated from the following files:
runtime/onert/core/src/util/EventWriter.h
runtime/onert/core/src/util/EventWriter.cc