ONE - On-device Neural Engine: npud::core::Server Class Reference
npud::core::Server Class Reference
#include <Server.h>
Public Member Functions
Server (const Server &)=delete
Server & operator= (const Server &)=delete
void run (void)
void stop (void)
bool isRunning ()
bool isServiceReady ()
const Core & core (void)
Static Public Member Functions
static Server & instance (void)
Detailed Description
Definition at line 33 of file Server.h.
Constructor & Destructor Documentation
Server()
npud::core::Server::Server (const Server &) delete
Member Function Documentation
core()
const Core & npud::core::Server::core (void) inline
Definition at line 51 of file Server.h.
{ return *_core.get(); }
Referenced by npud::core::DBus::on_handle_context_create(), npud::core::DBus::on_handle_context_destroy(), npud::core::DBus::on_handle_device_get_available_list(), npud::core::DBus::on_handle_network_create(), npud::core::DBus::on_handle_network_destroy(), npud::core::DBus::on_handle_request_create(), and npud::core::DBus::on_handle_request_destroy().
instance()
static Server & npud::core::Server::instance (void) inline static
Definition at line 45 of file Server.h.
  {
    static Server server;
    return server;
  }
Referenced by npud::core::Signal::handleSignal(), main(), npud::core::DBus::on_bus_acquired(), npud::core::DBus::on_handle_context_create(), npud::core::DBus::on_handle_context_destroy(), npud::core::DBus::on_handle_device_get_available_list(), npud::core::DBus::on_handle_network_create(), npud::core::DBus::on_handle_network_destroy(), npud::core::DBus::on_handle_request_create(), npud::core::DBus::on_handle_request_destroy(), and npud::core::DBus::on_name_lost().
isRunning()
bool npud::core::Server::isRunning () inline
Definition at line 42 of file Server.h.
{ return _isRunning.load(); }
isServiceReady()
bool npud::core::Server::isServiceReady ()
Definition at line 35 of file Server.cc.
{
  if (!_isRunning.load())
  {
    VERBOSE(Server) << "Server is not started." << std::endl;
    return false;
  }
  if (!_dbus->isReady())
  {
    VERBOSE(Server) << "DBus service is not ready." << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
operator=()
Server & npud::core::Server::operator= (const Server &) delete
run()
void npud::core::Server::run (void)
Definition at line 52 of file Server.cc.
{
  VERBOSE(Server) << "Starting Server\n";
  if (_isRunning.exchange(true))
  {
    return;
  }
  _core->init();
  g_main_loop_run(_mainloop.get());
}
References VERBOSE.
stop()
void npud::core::Server::stop (void)
Definition at line 66 of file Server.cc.
{
  VERBOSE(Server) << "Stop Server\n";
  if (!_isRunning.load())
  {
    return;
  }
  while (!g_main_loop_is_running(_mainloop.get()))
  {
    std::this_thread::yield();
  }
  _core->deinit();
  g_main_loop_quit(_mainloop.get());
  _isRunning = false;
}
References VERBOSE.
Referenced by npud::core::Signal::handleSignal(), npud::core::DBus::on_bus_acquired(), and npud::core::DBus::on_name_lost().
The documentation for this class was generated from the following files:
runtime/service/npud/core/Server.h
runtime/service/npud/core/Server.cc