ONE - On-device Neural Engine: onert::odc::QuantizerLoader Class Reference
onert::odc::QuantizerLoader Class Reference
Class to manage loading and unloading of dynamic library containing implementation of IQuantizer interface.
#include <QuantizerLoader.h>
Public Types
using dlhandle_destroy_t = std::function< void(void *)>
Typedef for function pointer to destroy loaded library handle.
using factory_t = IQuantizer *(*)()
Typedef for function pointer to create instance of IQuantizer.
using quantizer_destory_t = void(*)(IQuantizer *)
Typedef for function pointer to destroy instance of IQuantizer.
Public Member Functions
int32_t loadLibrary ()
Load dynamic library containing implementation of IQuantizer.
int32_t unloadLibrary ()
Unload dynamic library containing implementation of IQuantizer.
IQuantizer * get () const
Get instance of IQuantizer created through factory method.
Static Public Member Functions
static QuantizerLoader & instance ()
Get singleton instance of QuantizerLoader.
Detailed Description
Class to manage loading and unloading of dynamic library containing implementation of IQuantizer interface.
Definition at line 34 of file QuantizerLoader.h.
Member Typedef Documentation
dlhandle_destroy_t
using onert::odc::QuantizerLoader::dlhandle_destroy_t = std::function<void(void *)>
Typedef for function pointer to destroy loaded library handle.
Definition at line 40 of file QuantizerLoader.h.
factory_t
using onert::odc::QuantizerLoader::factory_t = IQuantizer *(*)()
Typedef for function pointer to create instance of IQuantizer.
Definition at line 44 of file QuantizerLoader.h.
quantizer_destory_t
using onert::odc::QuantizerLoader::quantizer_destory_t = void (*)(IQuantizer *)
Typedef for function pointer to destroy instance of IQuantizer.
Definition at line 48 of file QuantizerLoader.h.
Member Function Documentation
get()
IQuantizer * onert::odc::QuantizerLoader::get () const inline
Get instance of IQuantizer created through factory method.
Returns
Pointer to instance of IQuantizer
Definition at line 78 of file QuantizerLoader.h.
{ return _quantizer.get(); }
Referenced by loadLibrary(), and unloadLibrary().
instance()
QuantizerLoader & onert::odc::QuantizerLoader::instance () static
Get singleton instance of QuantizerLoader.
Returns
Reference to singleton instance of QuantizerLoader
Definition at line 35 of file QuantizerLoader.cc.
{
  static QuantizerLoader singleton;
  return singleton;
}
loadLibrary()
int32_t onert::odc::QuantizerLoader::loadLibrary ()
Load dynamic library containing implementation of IQuantizer.
Returns
0 if success, otherwise errno value
Definition at line 41 of file QuantizerLoader.cc.
{
  if (get() != nullptr)
    return 0;
  const std::string quantize_so = std::string("libonert_odc") + SHARED_LIB_EXT;
  void *handle = dlopen(quantize_so.c_str(), RTLD_LAZY | RTLD_LOCAL);
  auto dlerror_msg = dlerror();
  if (handle == nullptr)
  {
    std::cerr << "Failed to load " << quantize_so << std::endl;
    std::cerr << dlerror_msg << std::endl;
    return 1;
  }
  {
    const char *factory_name = "create_quantizer";
    auto factory = (factory_t)dlsym(handle, factory_name);
    dlerror_msg = dlerror();
    if (factory == nullptr)
    {
      std::cerr << "QuantizerLoader: unable to find function " << factory_name << dlerror_msg
                << std::endl;
      dlclose(handle);
      return 1;
    }
    auto destroyer = (quantizer_destory_t)dlsym(handle, "destroy_quantizer");
    _quantizer = std::unique_ptr<IQuantizer, quantizer_destory_t>(factory(), destroyer);
    if (_quantizer == nullptr)
    {
      std::cerr << "QuantizerLoader: unable to create quantizer" << std::endl;
      return 1;
    }
  }
  // Save quantize library handle (avoid warning by handle lost without dlclose())
  // clang-format off
  _dlhandle = std::unique_ptr<void, dlhandle_destroy_t>{handle, [filename = quantize_so](void *h) {
    if (dlclose(h) != 0)
      std::cerr << "Failed to unload backend " << filename << std::endl;
  }};
  // clang-format on
  return 0;
}
References get().
unloadLibrary()
int32_t onert::odc::QuantizerLoader::unloadLibrary ()
Unload dynamic library containing implementation of IQuantizer.
Returns
0 if success, otherwise errno value
Definition at line 91 of file QuantizerLoader.cc.
{
  if (get() == nullptr)
    return 0;
  _quantizer.reset(nullptr);
  _dlhandle.reset(nullptr);
  return 0;
}
References get().
The documentation for this class was generated from the following files:
runtime/onert/core/src/odc/QuantizerLoader.h
runtime/onert/core/src/odc/QuantizerLoader.cc