ONE - On-device Neural Engine: onert::backend::xnnpack::ops::FullyConnectedLayer Class Reference
onert::backend::xnnpack::ops::FullyConnectedLayer Class Reference
#include <FullyConnectedLayer.h>
Public Member Functions
FullyConnectedLayer (const std::shared_ptr< ExternalContext > external_context)
void configure (const IPortableTensor *input, const IPortableTensor *_kernel, const IPortableTensor *bias, ir::Activation activation, IPortableTensor *output)
void run () override
bool create () override
bool setup () override
Public Member Functions inherited from onert::backend::xnnpack::ops::Layer
Layer (const std::shared_ptr< ExternalContext > external_context)
~Layer ()
void prepare () override
virtual bool create ()=0
virtual bool setup ()=0
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::xnnpack::ops::Layer
xnn_operator_t _kernel_op
bool _create
bool _setup
const std::shared_ptr< ExternalContext > _external_context
Detailed Description
Definition at line 33 of file FullyConnectedLayer.h.
Constructor & Destructor Documentation
FullyConnectedLayer()
onert::backend::xnnpack::ops::FullyConnectedLayer::FullyConnectedLayer (const std::shared_ptr< ExternalContext > external_context)
Definition at line 30 of file FullyConnectedLayer.cc.
  : Layer(external_context), _input(nullptr), _kernel(nullptr), _bias(nullptr), _output(nullptr),
    _activation(ir::Activation::NONE)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::xnnpack::ops::FullyConnectedLayer::configure (const IPortableTensor * input, const IPortableTensor * _kernel, const IPortableTensor * bias, ir::Activation activation, IPortableTensor * output)
Definition at line 37 of file FullyConnectedLayer.cc.
{
  _input = input;
  _kernel = weights;
  _bias = bias;
  _activation = activation;
  _output = output;
  // TODO Support not nhwc layer
  assert(_input->layout() == ir::Layout::NHWC);
  assert(_activation == ir::Activation::NONE || _activation == ir::Activation::RELU ||
         _activation == ir::Activation::RELU1 || _activation == ir::Activation::RELU6);
}
References onert::backend::ITensor::layout(), onert::ir::NHWC, onert::ir::NONE, onert::ir::RELU, onert::ir::RELU1, and onert::ir::RELU6.
create()
bool onert::backend::xnnpack::ops::FullyConnectedLayer::create () override virtual
Implements onert::backend::xnnpack::ops::Layer.
Definition at line 77 of file FullyConnectedLayer.cc.
{
  float output_activation_min = 0.f, output_activation_max = 0.f;
  CalculateActivationRange<float>(_activation, &output_activation_min, &output_activation_max);
  const auto &kernel_shape = _kernel->getShape();
  assert(kernel_shape.rank() == 2);
  uint32_t output_channels = kernel_shape.dim(0);
  uint32_t input_channels = kernel_shape.dim(1);
  const auto &input_shape = _input->getShape();
  const auto &output_shape = _output->getShape();
  uint32_t flag = 0;
  if (input_shape.rank() != output_shape.rank())
  {
    flag |= XNN_FLAG_TENSORFLOW_RESHAPE_2D;
    assert(input_shape.num_elements() % input_channels == 0);
  }
  else
  {
    assert(static_cast<uint32_t>(input_shape.dim(input_shape.rank() - 1)) == input_channels);
  }
  assert(_kernel && _kernel->buffer());
  const float *kernel_buffer = reinterpret_cast<const float *>(_kernel->buffer());
  const float *bias_buffer = (_bias) ? reinterpret_cast<const float *>(_bias->buffer()) : nullptr;
  enum xnn_status status = xnn_create_fully_connected_nc_f32(
    input_channels, output_channels, input_channels /* input stride */,
    output_channels /* output stride */, kernel_buffer, bias_buffer, output_activation_min,
    output_activation_max, flag, &_kernel_op);
  if (status != xnn_status_success)
  {
    throw std::runtime_error{"failed to create FP32 FullyConnected operator"};
  }
  assert(_kernel_op != nullptr);
  return true;
}
References onert::backend::xnnpack::ops::Layer::_kernel_op, onert::backend::ITensor::buffer(), and onert::backend::ITensor::getShape().
run()
void onert::backend::xnnpack::ops::FullyConnectedLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 54 of file FullyConnectedLayer.cc.
{
  assert(_external_context && _external_context->getThreadPool());
  if (!_setup)
  {
    _setup = setup();
    assert(_setup);
  }
  if (_input->data_type() == OperandType::FLOAT32)
  {
    enum xnn_status status = xnn_run_operator(_kernel_op, _external_context->getThreadPool());
    if (status != xnn_status_success)
    {
      throw std::runtime_error{"failed to run FP32 FullyConnected operator"};
    }
  }
  else
  {
    throw std::runtime_error{"XNNPACK FC: unsupported data type"};
  }
}
References onert::backend::xnnpack::ops::Layer::_external_context, onert::backend::xnnpack::ops::Layer::_kernel_op, onert::backend::xnnpack::ops::Layer::_setup, onert::backend::ITensor::data_type(), and setup().
setup()
bool onert::backend::xnnpack::ops::FullyConnectedLayer::setup () override virtual
Implements onert::backend::xnnpack::ops::Layer.
Definition at line 116 of file FullyConnectedLayer.cc.
{
  if (_input->buffer() == nullptr || _output->buffer() == nullptr)
  {
    // it could be models's input or output
    return false;
  }
  uint32_t batch_size = _input->getShape().num_elements() / _kernel->getShape().dim(1);
  enum xnn_status status = xnn_setup_fully_connected_nc_f32(
    _kernel_op, batch_size, reinterpret_cast<const float *>(_input->buffer()),
    reinterpret_cast<float *>(_output->buffer()), _external_context->getThreadPool());
  if (status != xnn_status_success)
  {
    throw std::runtime_error{"failed to create FP32 FullyConnected operator"};
  }
  return true;
}
References onert::backend::xnnpack::ops::Layer::_external_context, onert::backend::xnnpack::ops::Layer::_kernel_op, onert::backend::ITensor::buffer(), and onert::backend::ITensor::getShape().
Referenced by run().
The documentation for this class was generated from the following files:
runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.h
runtime/onert/backend/xnnpack/ops/FullyConnectedLayer.cc