ONE - On-device Neural Engine: loco::PermutingEncoder< Domain::Feature > Class Reference
loco::PermutingEncoder< Domain::Feature > Class Reference final
#include <PermutingCodec.h>
Public Member Functions
PermutingEncoder ()=default
PermutingEncoder (const Permutation< Domain::Feature > &perm)
bool valid (void) const
FeatureShape shape (const TensorShape &tensor_shape) const override
TensorIndex value (const FeatureIndex &index) const override
std::unique_ptr< FeatureEncoder > clone (void) const override
const Permutation< Domain::Feature > * perm (void) const
Permutation< Domain::Feature > * perm (void)
void perm (const Permutation< Domain::Feature > &p)
Public Member Functions inherited from loco::FeatureEncoder
virtual ~FeatureEncoder ()=default
virtual FeatureShape shape (const TensorShape &shape) const =0
virtual TensorIndex value (const FeatureIndex &index) const =0
virtual std::unique_ptr< FeatureEncoder > clone (void) const =0
Detailed Description
Definition at line 76 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingEncoder() [1/2]
loco::PermutingEncoder< Domain::Feature >::PermutingEncoder () default
PermutingEncoder() [2/2]
loco::PermutingEncoder< Domain::Feature >::PermutingEncoder (const Permutation< Domain::Feature > & perm) inline
Definition at line 82 of file PermutingCodec.h.
                                                           : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
clone()
std::unique_ptr< FeatureEncoder > loco::PermutingEncoder< Domain::Feature >::clone (void) const override virtual
Implements loco::FeatureEncoder.
Definition at line 139 of file PermutingCodec.cpp.
{
  return std::make_unique<PermutingEncoder<Domain::Feature>>(_perm);
}
perm() [1/3]
void loco::PermutingEncoder< Domain::Feature >::perm (const Permutation< Domain::Feature > & p) inline
Definition at line 99 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Feature > * loco::PermutingEncoder< Domain::Feature >::perm (void) inline
Definition at line 98 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Feature > * loco::PermutingEncoder< Domain::Feature >::perm (void) const inline
Definition at line 97 of file PermutingCodec.h.
{ return &_perm; }
shape()
FeatureShape loco::PermutingEncoder< Domain::Feature >::shape (const TensorShape & tensor_shape) const override virtual
Implements loco::FeatureEncoder.
Definition at line 109 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  FeatureShape out;
  out.count() = in.dim(_perm[FeatureAxis::Count]);
  out.depth() = in.dim(_perm[FeatureAxis::Depth]);
  out.height() = in.dim(_perm[FeatureAxis::Height]);
  out.width() = in.dim(_perm[FeatureAxis::Width]);
  return out;
}
References loco::Count, loco::FeatureShape::count(), loco::Depth, loco::FeatureShape::depth(), loco::TensorShape::dim(), loco::Height, loco::FeatureShape::height(), loco::valid(), loco::Width, and loco::FeatureShape::width().
valid()
bool loco::PermutingEncoder< Domain::Feature >::valid (void) const
Definition at line 144 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
TensorIndex loco::PermutingEncoder< Domain::Feature >::value (const FeatureIndex & index) const override virtual
Implements loco::FeatureEncoder.
Definition at line 123 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorIndex out;
  out.resize(4);
  out.at(_perm[FeatureAxis::Count]) = in.batch();
  out.at(_perm[FeatureAxis::Depth]) = in.channel();
  out.at(_perm[FeatureAxis::Height]) = in.row();
  out.at(_perm[FeatureAxis::Width]) = in.column();
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::FeatureIndex::batch(), loco::FeatureIndex::channel(), loco::FeatureIndex::column(), loco::Count, loco::Depth, loco::Height, nncc::core::ADT::tensor::Index::resize(), loco::FeatureIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp