ONE - On-device Neural Engine: arm_compute::NEBinaryLogicalOperationKernel Class Reference
arm_compute::NEBinaryLogicalOperationKernel Class Reference
#include <NEBinaryLogicalOperationKernel.h>
Public Member Functions
const char * name () const override
NEBinaryLogicalOperationKernel ()=default
~NEBinaryLogicalOperationKernel ()=default
void configure (BinaryLogicalOperation op, const ITensor *input1, const ITensor *input2, ITensor *output)
Static Public Member Functions
static Status validate (BinaryLogicalOperation op, const ITensorInfo *input1, const ITensorInfo *input2, const ITensorInfo *output)
Static Protected Member Functions
static Status validate_arguments (const ITensorInfo &input1, const ITensorInfo &input2, const ITensorInfo &output)
Protected Attributes
std::function< void(const ITensor *input1, const ITensor *input2, ITensor *output, const Window &window)> _function
Detailed Description
Definition at line 51 of file NEBinaryLogicalOperationKernel.h.
Constructor & Destructor Documentation
NEBinaryLogicalOperationKernel()
arm_compute::NEBinaryLogicalOperationKernel::NEBinaryLogicalOperationKernel () default
~NEBinaryLogicalOperationKernel()
arm_compute::NEBinaryLogicalOperationKernel::~NEBinaryLogicalOperationKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void arm_compute::NEBinaryLogicalOperationKernel::configure (BinaryLogicalOperation op, const ITensor * input1, const ITensor * input2, ITensor * output)
Static function to check if given info will lead to a valid configuration of NEBinaryLogicalOperationKernel
Parameters
[in] op Binary logical operation to be executed.
[in] input1 First tensor input. Data types supported: QASYMM8/U8.
[in] input2 Second tensor input. Data types supported: Same as input1.
[in] output Output tensor. Data types supported: Same as input1.
Definition at line 195 of file NEBinaryLogicalOperationKernel.cpp.
{
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(*input1->info(), *input2->info(), *output->info()));
  configure_common(input1->info(), input2->info(), output->info());
  switch (op)
  {
    case BinaryLogicalOperation::AND:
      _function = configure_logic_func<BinaryLogicalOperation::AND>(input1, input2, output);
      break;
    case BinaryLogicalOperation::OR:
      _function = configure_logic_func<BinaryLogicalOperation::OR>(input1, input2, output);
      break;
    default:
      ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
  }
}
References _function, arm_compute::AND, arm_compute::OR, and validate_arguments().
name()
const char * arm_compute::NEBinaryLogicalOperationKernel::name () const inline override
Definition at line 54 of file NEBinaryLogicalOperationKernel.h.
{ return "NEBinaryLogicalOperationKernel"; }
validate()
Status arm_compute::NEBinaryLogicalOperationKernel::validate (BinaryLogicalOperation op, const ITensorInfo * input1, const ITensorInfo * input2, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of NEBinaryLogicalOperationKernel
Parameters
[in] op Binary logical operation to be executed.
[in] input1 First tensor input info. Data types supported: QASYMM8/U8.
[in] input2 Second tensor input info. Data types supported: Same as input1.
[in] output Output tensor info. Data types supported: Same as input1.
Returns
a Status
Definition at line 244 of file NEBinaryLogicalOperationKernel.cpp.
{
  ARM_COMPUTE_UNUSED(op);
  ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input1, input2, output);
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(*input1, *input2, *output));
  return Status{};
}
References validate_arguments().
Referenced by arm_compute::NEBinaryLogicalOperationStatic< op >::validate(), arm_compute::NEBinaryLogicalOperation::validate(), and ~NEBinaryLogicalOperationKernel().
validate_arguments()
Status arm_compute::NEBinaryLogicalOperationKernel::validate_arguments (const ITensorInfo & input1, const ITensorInfo & input2, const ITensorInfo & output) static protected
Definition at line 213 of file NEBinaryLogicalOperationKernel.cpp.
{
  // Validate in case of configured output
  if (output.total_size() > 0)
  {
    ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&output, 1, DataType::U8,
                                                         DataType::QASYMM8);
  }
  ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&input1, 1, DataType::U8, DataType::QASYMM8);
  ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(&input2, 1, DataType::U8, DataType::QASYMM8);
  ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(&input1, &input2);
  const TensorShape out_shape =
    TensorShape::broadcast_shape(input1.tensor_shape(), input2.tensor_shape());
  ARM_COMPUTE_RETURN_ERROR_ON_MSG(out_shape.total_size() == 0,
                                  "Inputs are not broadcast compatible");
  // Validate in case of configured output
  if (output.total_size() > 0)
  {
    ARM_COMPUTE_RETURN_ERROR_ON_MSG(
      detail::have_different_dimensions(out_shape, output.tensor_shape(), 0),
      "Wrong shape for output");
  }
  return Status{};
}
Referenced by configure(), and validate().
Field Documentation
_function
std::function<void(const ITensor *input1, const ITensor *input2, ITensor *output, const Window &window)> arm_compute::NEBinaryLogicalOperationKernel::_function protected
Definition at line 91 of file NEBinaryLogicalOperationKernel.h.
Referenced by configure().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEBinaryLogicalOperationKernel.h
compute/ARMComputeEx/src/core/NEON/kernels/NEBinaryLogicalOperationKernel.cpp