ONE - On-device Neural Engine: onert::backend::basic::DynamicMemoryManager Class Reference
onert::backend::basic::DynamicMemoryManager Class Reference
#include <MemoryManager.h>
Public Member Functions
DynamicMemoryManager ()=default
virtual ~DynamicMemoryManager ()=default
std::shared_ptr< Allocator > allocate (const ITensor *tensor, uint32_t capacity)
void deallocate (const ITensor *tensor)
void deallocate (void)
Detailed Description
Definition at line 57 of file MemoryManager.h.
Constructor & Destructor Documentation
DynamicMemoryManager()
onert::backend::basic::DynamicMemoryManager::DynamicMemoryManager () default
~DynamicMemoryManager()
virtual onert::backend::basic::DynamicMemoryManager::~DynamicMemoryManager () virtual default
Member Function Documentation
allocate()
std::shared_ptr< basic::Allocator > onert::backend::basic::DynamicMemoryManager::allocate (const ITensor * tensor, uint32_t capacity)
Definition at line 74 of file MemoryManager.cc.
{
  auto find = _mem_alloc_map.find(tensor);
  if (find != _mem_alloc_map.end())
    throw std::runtime_error("Cannot allocate memory for a tensor. It was already allocated.");
  _mem_alloc_map[tensor] = std::make_shared<basic::Allocator>(capacity);
  return _mem_alloc_map[tensor];
}
Referenced by onert::backend::basic::Tensor::applyShape(), and onert::backend::builtin::kernel::WhileLayer::run().
deallocate() [1/2]
void onert::backend::basic::DynamicMemoryManager::deallocate (const ITensor * tensor)
Definition at line 85 of file MemoryManager.cc.
{
  auto find = _mem_alloc_map.find(tensor);
  if (find == _mem_alloc_map.end())
    throw std::runtime_error("Cannot find Allocator for the requested index");
  find->second->release();    // explicitly erase memory
  _mem_alloc_map.erase(find); // remove tensor and alloc
}
Referenced by onert::backend::basic::Tensor::applyShape(), onert::backend::basic::Tensor::deallocBuffer(), and onert::backend::builtin::kernel::WhileLayer::run().
deallocate() [2/2]
void onert::backend::basic::DynamicMemoryManager::deallocate (void)
Definition at line 95 of file MemoryManager.cc.
{
  for (auto &mem_alloc : _mem_alloc_map)
  {
    // Release memory buffer of mem_alloc
    mem_alloc.second->release();
  }
  _mem_alloc_map.clear();
}
The documentation for this class was generated from the following files:
runtime/onert/core/include/backend/basic/MemoryManager.h
runtime/onert/core/src/backend/basic/MemoryManager.cc