ONE - On-device Neural Engine: onert::backend::gpu_cl::TensorRegistry Class Reference
onert::backend::gpu_cl::TensorRegistry Class Reference
Tensor registry class for gpu-cl backends.
#include <TensorRegistry.h>
Public Member Functions
TensorRegistry (TensorManager *tensor_mgr)
ITensor * getITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native tensors.
auto getClTensor (const ir::OperandIndex &ind)
ir::OperandIndex addNewClTensor (const ir::Shape &shape)
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Detailed Description
Tensor registry class for gpu-cl backends.
This is implemented as a wrapper of TensorManager.
Definition at line 36 of file TensorRegistry.h.
Constructor & Destructor Documentation
TensorRegistry()
onert::backend::gpu_cl::TensorRegistry::TensorRegistry (TensorManager * tensor_mgr) inline
Definition at line 39 of file TensorRegistry.h.
: _tensor_mgr{tensor_mgr} {}
Member Function Documentation
addNewClTensor()
ir::OperandIndex onert::backend::gpu_cl::TensorRegistry::addNewClTensor (const ir::Shape & shape) inline
Definition at line 47 of file TensorRegistry.h.
{ return _tensor_mgr->addTensor(shape); }
References onert::backend::gpu_cl::TensorManager::addTensor().
getClTensor()
auto onert::backend::gpu_cl::TensorRegistry::getClTensor (const ir::OperandIndex & ind) inline
Definition at line 45 of file TensorRegistry.h.
{ return _tensor_mgr->at(ind).get(); }
References onert::backend::gpu_cl::TensorManager::at().
getITensor()
ITensor * onert::backend::gpu_cl::TensorRegistry::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 41 of file TensorRegistry.h.
{ return _tensor_mgr->at(ind).get(); }
References onert::backend::gpu_cl::TensorManager::at().
Referenced by getNativeITensor().
getNativeITensor()
ITensor * onert::backend::gpu_cl::TensorRegistry::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 43 of file TensorRegistry.h.
{ return getITensor(ind); }
References getITensor().
The documentation for this class was generated from the following file:
runtime/onert/backend/gpu_cl/TensorRegistry.h