ONE - On-device Neural Engine: luci_interpreter::kernels::Select Class Reference
luci_interpreter::kernels::Select Class Reference
#include <Select.h>
Public Member Functions
Select (const Tensor *cond, const Tensor *t, const Tensor *e, Tensor *output)
const Tensor * condition () const
const Tensor * t () const
const Tensor * e () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file Select.h.
Constructor & Destructor Documentation
Select()
luci_interpreter::kernels::Select::Select (const Tensor * cond, const Tensor * t, const Tensor * e, Tensor * output)
Definition at line 33 of file Select.cpp.
  : Kernel({condition, t, e}, {output})
{
  // NOTE _requires_broadcast is for SelectV2
  _requires_broadcast = false;
  _has_low_rank_input_condition = false;
}
References condition(), e(), and t().
Member Function Documentation
condition()
const Tensor * luci_interpreter::kernels::Select::condition () const inline
Definition at line 33 of file Select.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Select().
configure()
void luci_interpreter::kernels::Select::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 41 of file Select.cpp.
{
  LUCI_INTERPRETER_CHECK(condition()->element_type() == DataType::BOOL);
  LUCI_INTERPRETER_CHECK(t()->element_type() == e()->element_type());
  LUCI_INTERPRETER_CHECK(t()->element_type() == output()->element_type());
  auto cond_shape = condition()->shape();
  auto cond_num_dims = cond_shape.num_dims();
  auto t_shape = t()->shape();
  bool is_input_condition_scalar = cond_num_dims == 0;
  bool has_rank_one_input_condition = cond_num_dims == 1 && cond_shape.dim(0) == t_shape.dim(0);
  _has_low_rank_input_condition = is_input_condition_scalar || has_rank_one_input_condition;
  output()->resize(calculateShapeForBroadcast(t()->shape(), e()->shape()));
}
References luci_interpreter::kernels::calculateShapeForBroadcast(), condition(), luci_interpreter::Shape::dim(), e(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), and t().
e()
const Tensor * luci_interpreter::kernels::Select::e () const inline
Definition at line 35 of file Select.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Select().
execute()
void luci_interpreter::kernels::Select::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 59 of file Select.cpp.
{
  switch (t()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Select: unsupported type.");
  }
}
References t().
output()
Tensor * luci_interpreter::kernels::Select::output () const inline
Definition at line 36 of file Select.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
t()
const Tensor * luci_interpreter::kernels::Select::t () const inline
Definition at line 34 of file Select.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Select().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Select.h
compiler/luci-interpreter/src/kernels/Select.cpp