ONE - On-device Neural Engine: onert::ir::train::TrainableOperation Class Reference
onert::ir::train::TrainableOperation Class Reference
#include <TrainableOperation.h>
Public Member Functions
virtual ~TrainableOperation ()=default
void disableWeightsUpdate () final
void enableWeightsUpdate () final
virtual bool isWeightsUpdateEnabled () const final
void enableBackward () final
virtual bool isRequiredForBackward () const final
Public Member Functions inherited from onert::ir::train::ITrainableOperation
virtual ~ITrainableOperation ()=default
virtual std::unique_ptr< ITrainableOperation > clone () const =0
virtual void accept (OperationVisitor &v) const override=0
virtual void accept (TrainableOperationVisitor &v) const =0
virtual bool hasTrainableParameter () const =0
Public Member Functions inherited from onert::ir::IOperation
virtual ~IOperation ()=default
virtual std::string name () const
virtual OpCode opcode () const =0
virtual void replaceInputs (const OperandIndex &from, const OperandIndex &to)=0
virtual void replaceOutputs (const OperandIndex &from, const OperandIndex &to)=0
virtual const OperandIndexSequence & getInputs () const =0
virtual const OperandIndexSequence & getOutputs () const =0
Detailed Description
Definition at line 29 of file TrainableOperation.h.
Constructor & Destructor Documentation
~TrainableOperation()
virtual onert::ir::train::TrainableOperation::~TrainableOperation () virtual default
Member Function Documentation
disableWeightsUpdate()
void onert::ir::train::TrainableOperation::disableWeightsUpdate () inline final virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 35 of file TrainableOperation.h.
{ _trainable = false; }
enableBackward()
void onert::ir::train::TrainableOperation::enableBackward () inline final virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 41 of file TrainableOperation.h.
{ _required_for_backward = true; }
enableWeightsUpdate()
void onert::ir::train::TrainableOperation::enableWeightsUpdate () inline final virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 37 of file TrainableOperation.h.
{ _trainable = true; }
isRequiredForBackward()
virtual bool onert::ir::train::TrainableOperation::isRequiredForBackward () const inline final virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 42 of file TrainableOperation.h.
{ return _required_for_backward; }
Referenced by onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), and onert::backend::train::KernelGenerator::visit().
isWeightsUpdateEnabled()
virtual bool onert::ir::train::TrainableOperation::isWeightsUpdateEnabled () const inline final virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 39 of file TrainableOperation.h.
{ return _trainable; }
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/train/TrainableOperation.h