ONE - On-device Neural Engine: circle_eval_diff::CircleEvalDiff Class Reference
circle_eval_diff::CircleEvalDiff Class Reference final
#include <CircleEvalDiff.h>
Data Structures
struct Context
Public Member Functions
CircleEvalDiff (std::unique_ptr< Context > &&ctx)
~CircleEvalDiff ()
void init ()
void evalDiff (void) const
Detailed Description
Definition at line 47 of file CircleEvalDiff.h.
Constructor & Destructor Documentation
CircleEvalDiff()
circle_eval_diff::CircleEvalDiff::CircleEvalDiff (std::unique_ptr< Context > && ctx)
Definition at line 158 of file CircleEvalDiff.cpp.
                                                           : _ctx(std::move(ctx))
{
  // DO NOTHING
}
~CircleEvalDiff()
circle_eval_diff::CircleEvalDiff::~CircleEvalDiff () default
Member Function Documentation
evalDiff()
void circle_eval_diff::CircleEvalDiff::evalDiff (void) const
Definition at line 217 of file CircleEvalDiff.cpp.
{
  auto first_input_loader = circle_eval_diff::makeDataLoader(
    _ctx->first_input_data_path, _ctx->input_format, ::inputs_of(_first_module.get()));
  auto second_input_loader = circle_eval_diff::makeDataLoader(
    _ctx->second_input_data_path, _ctx->input_format, ::inputs_of(_second_module.get()));
  for (uint32_t data_idx = 0; data_idx < first_input_loader->size(); data_idx++)
  {
    std::cout << "Evaluating " << data_idx << "'th data" << std::endl;
    auto first_data = first_input_loader->get(data_idx);
    auto second_data = second_input_loader->get(data_idx);
    auto first_output = interpret(_first_module.get(), first_data);
    auto second_output = interpret(_second_module.get(), second_data);
    for (auto &metric : _metrics)
    {
      metric->accumulate(first_output, second_output);
    }
    if (_ctx.get()->output_prefix.empty())
      continue;
    for (uint32_t i = 0; i < first_output.size(); i++)
    {
      auto out = first_output[i];
      writeDataToFile(_ctx.get()->output_prefix + "." + std::to_string(data_idx) + ".first.output" +
                        std::to_string(i),
                      (char *)(out->buffer()), out->byte_size());
    }
    for (uint32_t i = 0; i < second_output.size(); i++)
    {
      auto out = second_output[i];
      writeDataToFile(_ctx.get()->output_prefix + "." + std::to_string(data_idx) +
                        ".second.output" + std::to_string(i),
                      (char *)(out->buffer()), out->byte_size());
    }
  }
  for (auto &metric : _metrics)
  {
    std::cout << metric.get() << std::endl;
  }
}
References circle_eval_diff::interpret(), and circle_eval_diff::makeDataLoader().
Referenced by entry().
init()
void circle_eval_diff::CircleEvalDiff::init ()
Definition at line 165 of file CircleEvalDiff.cpp.
{
  _first_module = import(_ctx->first_model_path);
  _second_module = import(_ctx->second_model_path);
  // Check modules have the same output signature (dtype/shape)
  // Exception will be thrown if they have different signature
  checkOutputs(_first_module.get(), _second_module.get());
  // Set metric
  std::unique_ptr<MetricPrinter> metric;
  for (auto metric : _ctx->metric)
  {
    switch (metric)
    {
      case Metric::MAE:
      {
        _metrics.emplace_back(std::make_unique<MAEPrinter>());
        break;
      }
      case Metric::MAPE:
      {
        _metrics.emplace_back(std::make_unique<MAPEPrinter>());
        break;
      }
      case Metric::MPEIR:
      {
        _metrics.emplace_back(std::make_unique<MPEIRPrinter>());
        break;
      }
      case Metric::MTOP1:
      {
        _metrics.emplace_back(std::make_unique<TopKMatchPrinter>(1));
        break;
      }
      case Metric::MTOP5:
      {
        _metrics.emplace_back(std::make_unique<TopKMatchPrinter>(5));
        break;
      }
      case Metric::MSE:
      {
        _metrics.emplace_back(std::make_unique<MSEPrinter>());
        break;
      }
      default:
        throw std::runtime_error("Unsupported metric.");
    }
    _metrics.back()->init(_first_module.get(), _second_module.get());
  }
}
References circle_eval_diff::MAE, circle_eval_diff::MAPE, circle_eval_diff::MPEIR, circle_eval_diff::MSE, circle_eval_diff::MTOP1, and circle_eval_diff::MTOP5.
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/circle-eval-diff/include/CircleEvalDiff.h
compiler/circle-eval-diff/src/CircleEvalDiff.cpp