ONE - On-device Neural Engine: onert::interp::ITensor Class Reference
onert::interp::ITensor Class Reference abstract
Interface to handle Tensor in interpreter.
#include <Tensor.h>
Public Member Functions
virtual ~ITensor ()=default
virtual uint8_t * buffer () const =0
virtual std::shared_ptr< const Buffer > shareBuffer () const =0
Return shared pointer for buffer.
virtual const uint8_t * bufferRO () const =0
Return read-only buffer pointer.
virtual std::shared_ptr< const ir::Data > shareData () const =0
Return shared pointer for data.
virtual void setBuffer (std::shared_ptr< const Buffer > buffer)=0
Set internal/external buffer.
virtual void setData (std::shared_ptr< const ir::Data > data)=0
Set data reference (including constant, input)
virtual void releaseData ()=0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual bool has_padding () const =0
virtual ir::DataType data_type () const =0
Return data type of tensor.
virtual const ir::OperandInfo & tensorInfo () const =0
Return TensorInfo.
virtual uint64_t num_elements () const =0
Return number of elements.
void access (const std::function< void(backend::ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Detailed Description
Interface to handle Tensor in interpreter.
Definition at line 38 of file Tensor.h.
Constructor & Destructor Documentation
~ITensor()
virtual onert::interp::ITensor::~ITensor () virtual default
Reimplemented from onert::backend::ITensor.
Member Function Documentation
access()
void onert::interp::ITensor::access (const std::function< void(backend::ITensor &tensor)> & fn) final
Definition at line 26 of file Tensor.cc.
{ fn(*this); }
buffer()
virtual uint8_t * onert::interp::ITensor::buffer () const pure virtual
Implements onert::backend::ITensor.
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::interp::conv2d::invoke(), onert::interp::fc::invoke(), and onert::interp::concat::invoke().
bufferRO()
virtual const uint8_t * onert::interp::ITensor::bufferRO () const pure virtual
Return read-only buffer pointer.
Returns
Read-only buffer pointer
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::interp::conv2d::invoke(), onert::interp::fc::invoke(), and onert::interp::instancenorm::invoke().
calcOffset()
virtual size_t onert::interp::ITensor::calcOffset (const ir::Coordinates & coords) const pure virtual
Implements onert::backend::ITensor.
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
data_type()
virtual ir::DataType onert::interp::ITensor::data_type () const pure virtual
Return data type of tensor.
Returns
Data type of tensor
Implements onert::backend::ITensor.
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::interp::concat::invokeConcat(), onert::interp::conv2d::invokeConv2D(), onert::interp::fc::invokeFC(), onert::interp::instancenorm::invokeInstanceNorm(), and onert::interp::concat::prepareConcat().
has_padding()
virtual bool onert::interp::ITensor::has_padding () const pure virtual
Implements onert::backend::ITensor.
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
num_elements()
virtual uint64_t onert::interp::ITensor::num_elements () const pure virtual
Return number of elements.
Returns
Number of elements
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
releaseData()
virtual void onert::interp::ITensor::releaseData () pure virtual
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
setBuffer()
virtual void onert::interp::ITensor::setBuffer (std::shared_ptr< const Buffer > buffer) pure virtual
Set internal/external buffer.
Parameters
[in] buffer Buffer pointer
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
setData()
virtual void onert::interp::ITensor::setData (std::shared_ptr< const ir::Data > data) pure virtual
Set data reference (including constant, input)
Parameters
[in] data Data pointer
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
shareBuffer()
virtual std::shared_ptr< const Buffer > onert::interp::ITensor::shareBuffer () const pure virtual
Return shared pointer for buffer.
Returns
Buffer shared pointer
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
shareData()
virtual std::shared_ptr< const ir::Data > onert::interp::ITensor::shareData () const pure virtual
Return shared pointer for data.
Returns
Data shared pointer
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
tensorInfo()
virtual const ir::OperandInfo & onert::interp::ITensor::tensorInfo () const pure virtual
Return TensorInfo.
Returns
TensorInfo
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::interp::conv2d::invoke(), onert::interp::fc::invoke(), onert::interp::instancenorm::invoke(), onert::interp::concat::invoke(), and onert::interp::pool2d::invokePool2DOps().
total_size()
virtual size_t onert::interp::ITensor::total_size () const pure virtual
Implements onert::backend::ITensor.
Implemented in onert::interp::ROTensor, and onert::interp::Tensor.
The documentation for this class was generated from the following files:
runtime/onert/core/src/interp/Tensor.h
runtime/onert/core/src/interp/Tensor.cc