ONE - On-device Neural Engine: circle_planner::ExecutionPlanner Class Reference
circle_planner::ExecutionPlanner Class Reference
#include <ExecutionPlanner.h>
Public Member Functions
ExecutionPlanner ()=delete
ExecutionPlanner (loco::Graph *graph)
ExecutionPlanner (loco::Graph *graph, TargetPlatform target_platform, RuntimeType runtime_type, AllocatingMode allocating_mode)
void make_execution_plan ()
void change_planning_mode (bool is_allocate_consts, bool is_allocate_inputs, bool is_allocate_scratchpads)
void create_json_allocation_file (const std::string &json_path)
Detailed Description
Definition at line 64 of file ExecutionPlanner.h.
Constructor & Destructor Documentation
ExecutionPlanner() [1/3]
circle_planner::ExecutionPlanner::ExecutionPlanner () delete
ExecutionPlanner() [2/3]
circle_planner::ExecutionPlanner::ExecutionPlanner (loco::Graph * graph) inline explicit
Definition at line 68 of file ExecutionPlanner.h.
                                              : _graph(graph)
  {
    _scratchpad_helper = std::make_unique<ScratchpadHelperLinux>();
  }
ExecutionPlanner() [3/3]
circle_planner::ExecutionPlanner::ExecutionPlanner (loco::Graph * graph, TargetPlatform target_platform, RuntimeType runtime_type, AllocatingMode allocating_mode) inline explicit
Definition at line 73 of file ExecutionPlanner.h.
    : _graph(graph), _runtime_type(runtime_type), _allocating_mode(allocating_mode)
  {
    switch (target_platform.platform_type)
    {
      case LINUX:
        _scratchpad_helper = std::make_unique<ScratchpadHelperLinux>();
        break;
      case MCU:
        _scratchpad_helper = std::make_unique<ScratchpadHelperMCU>();
        break;
      case CMSISNN:
        _scratchpad_helper = std::make_unique<ScratchpadHelperCMSISNN>(target_platform.use_dsp);
        break;
      default:
        assert(false && "Use unsupported platform");
    }
  };
References circle_planner::CMSISNN, circle_planner::LINUX, circle_planner::MCU, circle_planner::TargetPlatform::platform_type, and circle_planner::TargetPlatform::use_dsp.
Member Function Documentation
change_planning_mode()
void circle_planner::ExecutionPlanner::change_planning_mode (bool is_allocate_consts, bool is_allocate_inputs, bool is_allocate_scratchpads) inline
Definition at line 102 of file ExecutionPlanner.h.
  {
    _is_allocate_consts = is_allocate_consts;
    _is_allocate_inputs = is_allocate_inputs;
    _is_allocate_scratchpads = is_allocate_scratchpads;
  };
Referenced by entry().
create_json_allocation_file()
void circle_planner::ExecutionPlanner::create_json_allocation_file (const std::string & json_path)
Definition at line 279 of file ExecutionPlanner.cpp.
{
  Json::Value main_tree;
  Json::Value segments_node;
  Json::Value allocations_node;
  uint32_t alive_till_max = 0;
  // Find max dealloc value to assign to nodes with node_not_assigned value
  for (const auto elem : _dealloc_node)
  {
    if (alive_till_max < elem and elem != node_not_assigned)
      alive_till_max = elem;
  }
  for (auto &alloc_node_inform : _alloc_node_inform_vector)
  {
    const auto node_num = alloc_node_inform.node_num;
    const auto circle_node = loco::must_cast<luci::CircleNode *>(_ordered_nodes[node_num]);
    create_allocation_node(allocations_node, alloc_node_inform, alive_till_max, circle_node);
  }
  // Create segment part
  Json::Value segment_node;
  segment_node["name"] = "Segment1";
  segment_node["allocations"] = allocations_node;
  segments_node.append(segment_node);
  main_tree["schema_version"] = 1;
  main_tree["segments"] = segments_node;
  Json::StreamWriterBuilder builder;
  const std::unique_ptr<Json::StreamWriter> writer(builder.newStreamWriter());
  // Write to json file
  std::ofstream out;
  out.open(json_path);
  if (out.is_open())
  {
    writer->write(main_tree, &out);
  }
}
Referenced by entry().
make_execution_plan()
void circle_planner::ExecutionPlanner::make_execution_plan ()
Definition at line 261 of file ExecutionPlanner.cpp.
{
  switch (_runtime_type)
  {
    case ONERT_MICRO:
      make_execution_plan_onert_micro_base();
      break;
    case LUCI_INTERPRETER:
      make_execution_plan_luci_interpreter();
      break;
    default:
      throw std::runtime_error("Unsupported runtime platform\n");
  }
  auto settings = luci::UserSettings::settings();
  settings->set(luci::UserSettings::Key::ExecutionPlanGen, true);
}
References luci::UserSettings::ExecutionPlanGen, circle_planner::LUCI_INTERPRETER, circle_planner::ONERT_MICRO, and luci::UserSettings::settings().
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/circle-execution-plan/src/ExecutionPlanner.h
compiler/circle-execution-plan/src/ExecutionPlanner.cpp