ONE - On-device Neural Engine: nnc::ArtifactForLoop Class Reference
nnc::ArtifactForLoop Class Reference
Represents for loops.
#include <ArtifactModel.h>
Public Member Functions
ArtifactForLoop (std::shared_ptr< ArtifactVariable > init=nullptr, std::shared_ptr< ArtifactExpr > cond=nullptr, std::shared_ptr< ArtifactExpr > iter=nullptr)
bool isBlock () const override
If this entity represents something containing a block of instructions.
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
std::shared_ptr< ArtifactVariable > getInit () const
std::shared_ptr< ArtifactExpr > getCond () const
std::shared_ptr< ArtifactExpr > getIter () const
const ArtifactBlock * getBlock () const
ArtifactBlock * getBlock ()
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents for loops.
Definition at line 466 of file ArtifactModel.h.
Constructor & Destructor Documentation
ArtifactForLoop()
nnc::ArtifactForLoop::ArtifactForLoop (std::shared_ptr< ArtifactVariable > init = nullptr, std::shared_ptr< ArtifactExpr > cond = nullptr, std::shared_ptr< ArtifactExpr > iter = nullptr) inline explicit
Definition at line 469 of file ArtifactModel.h.
    : _init(std::move(init)), _cond(std::move(cond)), _iter(std::move(iter))
  {
  }
Member Function Documentation
accept()
void nnc::ArtifactForLoop::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Definition at line 478 of file ArtifactModel.h.
{ g->visit(this); }
Referenced by TEST().
getBlock() [1/2]
ArtifactBlock * nnc::ArtifactForLoop::getBlock () inline
Definition at line 484 of file ArtifactModel.h.
{ return &_body; }
getBlock() [2/2]
const ArtifactBlock * nnc::ArtifactForLoop::getBlock () const inline
Definition at line 483 of file ArtifactModel.h.
{ return &_body; }
Referenced by TEST(), and nnc::ArtifactGeneratorCppCode::visit().
getCond()
std::shared_ptr< ArtifactExpr > nnc::ArtifactForLoop::getCond () const inline
Definition at line 481 of file ArtifactModel.h.
{ return _cond; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
getInit()
std::shared_ptr< ArtifactVariable > nnc::ArtifactForLoop::getInit () const inline
Definition at line 480 of file ArtifactModel.h.
{ return _init; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
getIter()
std::shared_ptr< ArtifactExpr > nnc::ArtifactForLoop::getIter () const inline
Definition at line 482 of file ArtifactModel.h.
{ return _iter; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
isBlock()
bool nnc::ArtifactForLoop::isBlock () const inline override virtual
If this entity represents something containing a block of instructions.
Reimplemented from nnc::ArtifactEntity.
Definition at line 476 of file ArtifactModel.h.
{ return true; }
The documentation for this class was generated from the following file:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h