ONE - On-device Neural Engine: flexbuffers::FLATBUFFERS_FINAL_CLASS Class Reference
flexbuffers::FLATBUFFERS_FINAL_CLASS Class Reference
#include <flexbuffers.h>
Data Structures
struct Value
Public Member Functions
Builder (size_t initial_size=256, BuilderFlag flags=BUILDER_FLAG_SHARE_KEYS)
const std::vector< uint8_t > & GetBuffer () const
Get the serialized buffer (after you call Finish()).
size_t GetSize () const
void Clear ()
void Null ()
void Null (const char *key)
void Int (int64_t i)
void Int (const char *key, int64_t i)
void UInt (uint64_t u)
void UInt (const char *key, uint64_t u)
void Float (float f)
void Float (const char *key, float f)
void Double (double f)
void Double (const char *key, double d)
void Bool (bool b)
void Bool (const char *key, bool b)
void IndirectInt (int64_t i)
void IndirectInt (const char *key, int64_t i)
void IndirectUInt (uint64_t u)
void IndirectUInt (const char *key, uint64_t u)
void IndirectFloat (float f)
void IndirectFloat (const char *key, float f)
void IndirectDouble (double f)
void IndirectDouble (const char *key, double d)
size_t Key (const char *str, size_t len)
size_t Key (const char *str)
size_t Key (const std::string &str)
size_t String (const char *str, size_t len)
size_t String (const char *str)
size_t String (const std::string &str)
void String (const flexbuffers::String &str)
void String (const char *key, const char *str)
void String (const char *key, const std::string &str)
void String (const char *key, const flexbuffers::String &str)
size_t Blob (const void *data, size_t len)
size_t Blob (const std::vector< uint8_t > &v)
size_t StartVector ()
size_t StartVector (const char *key)
size_t StartMap ()
size_t StartMap (const char *key)
size_t EndVector (size_t start, bool typed, bool fixed)
size_t EndMap (size_t start)
bool HasDuplicateKeys () const
template<typename F >
size_t Vector (F f)
template<typename F , typename T >
size_t Vector (F f, T &state)
template<typename F >
size_t Vector (const char *key, F f)
template<typename F , typename T >
size_t Vector (const char *key, F f, T &state)
template<typename T >
void Vector (const T *elems, size_t len)
template<typename T >
void Vector (const char *key, const T *elems, size_t len)
template<typename T >
void Vector (const std::vector< T > &vec)
template<typename F >
size_t TypedVector (F f)
template<typename F , typename T >
size_t TypedVector (F f, T &state)
template<typename F >
size_t TypedVector (const char *key, F f)
template<typename F , typename T >
size_t TypedVector (const char *key, F f, T &state)
template<typename T >
size_t FixedTypedVector (const T *elems, size_t len)
template<typename T >
size_t FixedTypedVector (const char *key, const T *elems, size_t len)
template<typename F >
size_t Map (F f)
template<typename F , typename T >
size_t Map (F f, T &state)
template<typename F >
size_t Map (const char *key, F f)
template<typename F , typename T >
size_t Map (const char *key, F f, T &state)
template<typename T >
void Map (const std::map< std::string, T > &map)
Value LastValue ()
void ReuseValue (Value v)
void ReuseValue (const char *key, Value v)
void Add (int8_t i)
void Add (int16_t i)
void Add (int32_t i)
void Add (int64_t i)
void Add (uint8_t u)
void Add (uint16_t u)
void Add (uint32_t u)
void Add (uint64_t u)
void Add (float f)
void Add (double d)
void Add (bool b)
void Add (const char *str)
void Add (const std::string &str)
void Add (const flexbuffers::String &str)
template<typename T >
void Add (const std::vector< T > &vec)
template<typename T >
void Add (const char *key, const T &t)
template<typename T >
void Add (const std::map< std::string, T > &map)
template<typename T >
void operator+= (const T &t)
void ForceMinimumBitWidth (BitWidth bw=BIT_WIDTH_8)
void Finish ()
Detailed Description
Definition at line 1043 of file flexbuffers.h.
Member Function Documentation
Add() [1/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (bool b) inline
Definition at line 1473 of file flexbuffers.h.
{ Bool(b); }
Add() [2/17]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const char * key, const T & t) inline
Definition at line 1480 of file flexbuffers.h.
  {
    Key(key);
    Add(t);
  }
References Add().
Add() [3/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const char * str) inline
Definition at line 1474 of file flexbuffers.h.
{ String(str); }
Add() [4/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const flexbuffers::String & str) inline
Definition at line 1476 of file flexbuffers.h.
{ String(str); }
Add() [5/17]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const std::map< std::string, T > & map) inline
Definition at line 1486 of file flexbuffers.h.
{ Map(map); }
Add() [6/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const std::string & str) inline
Definition at line 1475 of file flexbuffers.h.
{ String(str); }
Add() [7/17]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (const std::vector< T > & vec) inline
Definition at line 1478 of file flexbuffers.h.
{ Vector(vec); }
Add() [8/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (double d) inline
Definition at line 1472 of file flexbuffers.h.
{ Double(d); }
Add() [9/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (float f) inline
Definition at line 1471 of file flexbuffers.h.
{ Float(f); }
Add() [10/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (int16_t i) inline
Definition at line 1464 of file flexbuffers.h.
{ Int(i); }
Add() [11/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (int32_t i) inline
Definition at line 1465 of file flexbuffers.h.
{ Int(i); }
Add() [12/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (int64_t i) inline
Definition at line 1466 of file flexbuffers.h.
{ Int(i); }
Add() [13/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (int8_t i) inline
Definition at line 1463 of file flexbuffers.h.
{ Int(i); }
Add() [14/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (uint16_t u) inline
Definition at line 1468 of file flexbuffers.h.
{ UInt(u); }
Add() [15/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (uint32_t u) inline
Definition at line 1469 of file flexbuffers.h.
{ UInt(u); }
Add() [16/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (uint64_t u) inline
Definition at line 1470 of file flexbuffers.h.
{ UInt(u); }
Add() [17/17]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Add (uint8_t u) inline
Definition at line 1467 of file flexbuffers.h.
{ UInt(u); }
Blob() [1/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Blob (const std::vector< uint8_t > & v) inline
Definition at line 1226 of file flexbuffers.h.
  {
    return CreateBlob(flatbuffers::vector_data(v), v.size(), 0, FBT_BLOB);
  }
References flexbuffers::FBT_BLOB, and flatbuffers::vector_data().
Blob() [2/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Blob (const void * data, size_t len) inline
Definition at line 1225 of file flexbuffers.h.
{ return CreateBlob(data, len, 0, FBT_BLOB); }
References flexbuffers::FBT_BLOB.
Bool() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Bool (bool b) inline
Definition at line 1121 of file flexbuffers.h.
{ stack_.push_back(Value(b)); }
Bool() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Bool (const char * key, bool b) inline
Definition at line 1122 of file flexbuffers.h.
  {
    Key(key);
    Bool(b);
  }
Builder()
flexbuffers::FLATBUFFERS_FINAL_CLASS::Builder (size_t initial_size = 256, BuilderFlag flags = BUILDER_FLAG_SHARE_KEYS) inline
Definition at line 1046 of file flexbuffers.h.
    : buf_(initial_size), finished_(false), has_duplicate_keys_(false), flags_(flags),
      force_min_bit_width_(BIT_WIDTH_8), key_pool(KeyOffsetCompare(buf_)),
      string_pool(StringOffsetCompare(buf_))
  {
    buf_.clear();
  }
References flexbuffers::BIT_WIDTH_8.
Clear()
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Clear () inline
Definition at line 1071 of file flexbuffers.h.
  {
    buf_.clear();
    stack_.clear();
    finished_ = false;
    // flags_ remains as-is;
    force_min_bit_width_ = BIT_WIDTH_8;
    key_pool.clear();
    string_pool.clear();
  }
References flexbuffers::BIT_WIDTH_8.
Double() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Double (const char * key, double d) inline
Definition at line 1115 of file flexbuffers.h.
  {
    Key(key);
    Double(d);
  }
Double() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Double (double f) inline
Definition at line 1114 of file flexbuffers.h.
{ stack_.push_back(Value(f)); }
EndMap()
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::EndMap (size_t start) inline
Definition at line 1259 of file flexbuffers.h.
  {
    // We should have interleaved keys and values on the stack.
    // Make sure it is an even number:
    auto len = stack_.size() - start;
    FLATBUFFERS_ASSERT(!(len & 1));
    len /= 2;
    // Make sure keys are all strings:
    for (auto key = start; key < stack_.size(); key += 2)
    {
      FLATBUFFERS_ASSERT(stack_[key].type_ == FBT_KEY);
    }
    // Now sort values, so later we can do a binary search lookup.
    // We want to sort 2 array elements at a time.
    struct TwoValue
    {
      Value key;
      Value val;
    };
    // TODO(wvo): strict aliasing?
    // TODO(wvo): allow the caller to indicate the data is already sorted
    // for maximum efficiency? With an assert to check sortedness to make sure
    // we're not breaking binary search.
    // Or, we can track if the map is sorted as keys are added which would be
    // be quite cheap (cheaper than checking it here), so we can skip this
    // step automatically when appliccable, and encourage people to write in
    // sorted fashion.
    // std::sort is typically already a lot faster on sorted data though.
    auto dict = reinterpret_cast<TwoValue *>(flatbuffers::vector_data(stack_) + start);
    std::sort(dict, dict + len, [&](const TwoValue &a, const TwoValue &b) -> bool {
      auto as = reinterpret_cast<const char *>(flatbuffers::vector_data(buf_) + a.key.u_);
      auto bs = reinterpret_cast<const char *>(flatbuffers::vector_data(buf_) + b.key.u_);
      auto comp = strcmp(as, bs);
      // We want to disallow duplicate keys, since this results in a
      // map where values cannot be found.
      // But we can't assert here (since we don't want to fail on
      // random JSON input) or have an error mechanism.
      // Instead, we set has_duplicate_keys_ in the builder to
      // signal this.
      // TODO: Have to check for pointer equality, as some sort
      // implementation apparently call this function with the same
      // element?? Why?
      if (!comp && &a != &b)
        has_duplicate_keys_ = true;
      return comp < 0;
    });
    // First create a vector out of all keys.
    // TODO(wvo): if kBuilderFlagShareKeyVectors is true, see if we can share
    // the first vector.
    auto keys = CreateVector(start, len, 2, true, false);
    auto vec = CreateVector(start + 1, len, 2, false, false, &keys);
    // Remove temp elements and return map.
    stack_.resize(start);
    stack_.push_back(vec);
    return static_cast<size_t>(vec.u_);
  }
References flexbuffers::FBT_KEY, FLATBUFFERS_ASSERT, and flatbuffers::vector_data().
EndVector()
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::EndVector (size_t start, bool typed, bool fixed) inline
Definition at line 1250 of file flexbuffers.h.
  {
    auto vec = CreateVector(start, stack_.size() - start, 1, typed, fixed);
    // Remove temp elements and return vector.
    stack_.resize(start);
    stack_.push_back(vec);
    return static_cast<size_t>(vec.u_);
  }
Finish()
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Finish () inline
Definition at line 1496 of file flexbuffers.h.
  {
    // If you hit this assert, you likely have objects that were never included
    // in a parent. You need to have exactly one root to finish a buffer.
    // Check your Start/End calls are matched, and all objects are inside
    // some other object.
    FLATBUFFERS_ASSERT(stack_.size() == 1);
    // Write root value.
    auto byte_width = Align(stack_[0].ElemWidth(buf_.size(), 0));
    WriteAny(stack_[0], byte_width);
    // Write root type.
    Write(stack_[0].StoredPackedType(), 1);
    // Write root size. Normally determined by parent, but root has no parent :)
    Write(byte_width, 1);
    finished_ = true;
  }
References FLATBUFFERS_ASSERT.
FixedTypedVector() [1/2]
template<typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::FixedTypedVector (const char * key, const T * elems, size_t len) inline
Definition at line 1405 of file flexbuffers.h.
  {
    Key(key);
    return FixedTypedVector(elems, len);
  }
FixedTypedVector() [2/2]
template<typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::FixedTypedVector (const T * elems, size_t len) inline
Definition at line 1395 of file flexbuffers.h.
  {
    // We only support a few fixed vector lengths. Anything bigger use a
    // regular typed vector.
    FLATBUFFERS_ASSERT(len >= 2 && len <= 4);
    // And only scalar values.
    static_assert(flatbuffers::is_scalar<T>::value, "Unrelated types");
    return ScalarVector(elems, len, true);
  }
References FLATBUFFERS_ASSERT.
Float() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Float (const char * key, float f) inline
Definition at line 1108 of file flexbuffers.h.
  {
    Key(key);
    Float(f);
  }
Float() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Float (float f) inline
Definition at line 1107 of file flexbuffers.h.
{ stack_.push_back(Value(f)); }
ForceMinimumBitWidth()
void flexbuffers::FLATBUFFERS_FINAL_CLASS::ForceMinimumBitWidth (BitWidth bw = BIT_WIDTH_8) inline
Definition at line 1494 of file flexbuffers.h.
{ force_min_bit_width_ = bw; }
GetBuffer()
const std::vector< uint8_t > & flexbuffers::FLATBUFFERS_FINAL_CLASS::GetBuffer () const inline
Get the serialized buffer (after you call Finish()).
Returns
Returns a vector owned by this class.
Definition at line 1061 of file flexbuffers.h.
  {
    Finished();
    return buf_;
  }
GetSize()
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::GetSize () const inline
Definition at line 1068 of file flexbuffers.h.
{ return buf_.size(); }
HasDuplicateKeys()
bool flexbuffers::FLATBUFFERS_FINAL_CLASS::HasDuplicateKeys () const inline
Definition at line 1318 of file flexbuffers.h.
{ return has_duplicate_keys_; }
IndirectDouble() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectDouble (const char * key, double d) inline
Definition at line 1150 of file flexbuffers.h.
  {
    Key(key);
    IndirectDouble(d);
  }
IndirectDouble() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectDouble (double f) inline
Definition at line 1149 of file flexbuffers.h.
{ PushIndirect(f, FBT_INDIRECT_FLOAT, WidthF(f)); }
References flexbuffers::FBT_INDIRECT_FLOAT, and flexbuffers::WidthF().
IndirectFloat() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectFloat (const char * key, float f) inline
Definition at line 1143 of file flexbuffers.h.
  {
    Key(key);
    IndirectFloat(f);
  }
IndirectFloat() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectFloat (float f) inline
Definition at line 1142 of file flexbuffers.h.
{ PushIndirect(f, FBT_INDIRECT_FLOAT, BIT_WIDTH_32); }
References flexbuffers::BIT_WIDTH_32, and flexbuffers::FBT_INDIRECT_FLOAT.
IndirectInt() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectInt (const char * key, int64_t i) inline
Definition at line 1129 of file flexbuffers.h.
  {
    Key(key);
    IndirectInt(i);
  }
IndirectInt() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectInt (int64_t i) inline
Definition at line 1128 of file flexbuffers.h.
{ PushIndirect(i, FBT_INDIRECT_INT, WidthI(i)); }
References flexbuffers::FBT_INDIRECT_INT, and flexbuffers::WidthI().
IndirectUInt() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectUInt (const char * key, uint64_t u) inline
Definition at line 1136 of file flexbuffers.h.
  {
    Key(key);
    IndirectUInt(u);
  }
IndirectUInt() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::IndirectUInt (uint64_t u) inline
Definition at line 1135 of file flexbuffers.h.
{ PushIndirect(u, FBT_INDIRECT_UINT, WidthU(u)); }
References flexbuffers::FBT_INDIRECT_UINT, and flexbuffers::WidthU().
Int() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Int (const char * key, int64_t i) inline
Definition at line 1094 of file flexbuffers.h.
  {
    Key(key);
    Int(i);
  }
Int() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Int (int64_t i) inline
Definition at line 1093 of file flexbuffers.h.
{ stack_.push_back(Value(i, FBT_INT, WidthI(i))); }
References flexbuffers::FBT_INT, and flexbuffers::WidthI().
Key() [1/3]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Key (const char * str) inline
Definition at line 1179 of file flexbuffers.h.
{ return Key(str, strlen(str)); }
References Key().
Referenced by Key().
Key() [2/3]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Key (const char * str, size_t len) inline
Definition at line 1156 of file flexbuffers.h.
  {
    auto sloc = buf_.size();
    WriteBytes(str, len + 1);
    if (flags_ & BUILDER_FLAG_SHARE_KEYS)
    {
      auto it = key_pool.find(sloc);
      if (it != key_pool.end())
      {
        // Already in the buffer. Remove key we just serialized, and use
        // existing offset instead.
        buf_.resize(sloc);
        sloc = *it;
      }
      else
      {
        key_pool.insert(sloc);
      }
    }
    stack_.push_back(Value(static_cast<uint64_t>(sloc), FBT_KEY, BIT_WIDTH_8));
    return sloc;
  }
References flexbuffers::BIT_WIDTH_8, flexbuffers::BUILDER_FLAG_SHARE_KEYS, and flexbuffers::FBT_KEY.
Key() [3/3]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Key (const std::string & str) inline
Definition at line 1180 of file flexbuffers.h.
{ return Key(str.c_str(), str.size()); }
References Key().
Referenced by Key().
LastValue()
Value flexbuffers::FLATBUFFERS_FINAL_CLASS::LastValue () inline
Definition at line 1454 of file flexbuffers.h.
{ return stack_.back(); }
Map() [1/5]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Map (const char * key, F f) inline
Definition at line 1423 of file flexbuffers.h.
  {
    auto start = StartMap(key);
    f();
    return EndMap(start);
  }
Map() [2/5]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Map (const char * key, F f, T & state) inline
Definition at line 1429 of file flexbuffers.h.
  {
    auto start = StartMap(key);
    f(state);
    return EndMap(start);
  }
Map() [3/5]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Map (const std::map< std::string, T > & map) inline
Definition at line 1435 of file flexbuffers.h.
  {
    auto start = StartMap();
    for (auto it = map.begin(); it != map.end(); ++it)
      Add(it->first.c_str(), it->second);
    EndMap(start);
  }
References Add().
Map() [4/5]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Map (F f) inline
Definition at line 1411 of file flexbuffers.h.
  {
    auto start = StartMap();
    f();
    return EndMap(start);
  }
Map() [5/5]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Map (F f, T & state) inline
Definition at line 1417 of file flexbuffers.h.
  {
    auto start = StartMap();
    f(state);
    return EndMap(start);
  }
Null() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Null () inline
Definition at line 1086 of file flexbuffers.h.
{ stack_.push_back(Value()); }
Null() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::Null (const char * key) inline
Definition at line 1087 of file flexbuffers.h.
  {
    Key(key);
    Null();
  }
operator+=()
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::operator+= (const T & t) inline
Definition at line 1488 of file flexbuffers.h.
{ Add(t); }
References Add().
ReuseValue() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::ReuseValue (const char * key, Value v) inline
Definition at line 1456 of file flexbuffers.h.
  {
    Key(key);
    ReuseValue(v);
  }
ReuseValue() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::ReuseValue (Value v) inline
Definition at line 1455 of file flexbuffers.h.
{ stack_.push_back(v); }
StartMap() [1/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::StartMap () inline
Definition at line 1241 of file flexbuffers.h.
{ return stack_.size(); }
StartMap() [2/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::StartMap (const char * key) inline
Definition at line 1242 of file flexbuffers.h.
  {
    Key(key);
    return stack_.size();
  }
StartVector() [1/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::StartVector () inline
Definition at line 1235 of file flexbuffers.h.
{ return stack_.size(); }
StartVector() [2/2]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::StartVector (const char * key) inline
Definition at line 1236 of file flexbuffers.h.
  {
    Key(key);
    return stack_.size();
  }
String() [1/7]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const char * key, const char * str) inline
Definition at line 1209 of file flexbuffers.h.
  {
    Key(key);
    String(str);
  }
String() [2/7]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const char * key, const flexbuffers::String & str) inline
Definition at line 1219 of file flexbuffers.h.
  {
    Key(key);
    String(str);
  }
String() [3/7]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const char * key, const std::string & str) inline
Definition at line 1214 of file flexbuffers.h.
  {
    Key(key);
    String(str);
  }
String() [4/7]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const char * str) inline
Definition at line 1205 of file flexbuffers.h.
{ return String(str, strlen(str)); }
References String().
Referenced by String().
String() [5/7]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const char * str, size_t len) inline
Definition at line 1182 of file flexbuffers.h.
  {
    auto reset_to = buf_.size();
    auto sloc = CreateBlob(str, len, 1, FBT_STRING);
    if (flags_ & BUILDER_FLAG_SHARE_STRINGS)
    {
      StringOffset so(sloc, len);
      auto it = string_pool.find(so);
      if (it != string_pool.end())
      {
        // Already in the buffer. Remove string we just serialized, and use
        // existing offset instead.
        buf_.resize(reset_to);
        sloc = it->first;
        stack_.back().u_ = sloc;
      }
      else
      {
        string_pool.insert(so);
      }
    }
    return sloc;
  }
References flexbuffers::BUILDER_FLAG_SHARE_STRINGS, and flexbuffers::FBT_STRING.
String() [6/7]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const flexbuffers::String & str) inline
Definition at line 1207 of file flexbuffers.h.
{ String(str.c_str(), str.length()); }
References String().
Referenced by String().
String() [7/7]
size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::String (const std::string & str) inline
Definition at line 1206 of file flexbuffers.h.
{ return String(str.c_str(), str.size()); }
References String().
Referenced by String().
TypedVector() [1/4]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::TypedVector (const char * key, F f) inline
Definition at line 1382 of file flexbuffers.h.
  {
    auto start = StartVector(key);
    f();
    return EndVector(start, true, false);
  }
TypedVector() [2/4]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::TypedVector (const char * key, F f, T & state) inline
Definition at line 1388 of file flexbuffers.h.
  {
    auto start = StartVector(key);
    f(state);
    return EndVector(start, true, false);
  }
TypedVector() [3/4]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::TypedVector (F f) inline
Definition at line 1370 of file flexbuffers.h.
  {
    auto start = StartVector();
    f();
    return EndVector(start, true, false);
  }
TypedVector() [4/4]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::TypedVector (F f, T & state) inline
Definition at line 1376 of file flexbuffers.h.
  {
    auto start = StartVector();
    f(state);
    return EndVector(start, true, false);
  }
UInt() [1/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::UInt (const char * key, uint64_t u) inline
Definition at line 1101 of file flexbuffers.h.
  {
    Key(key);
    UInt(u);
  }
UInt() [2/2]
void flexbuffers::FLATBUFFERS_FINAL_CLASS::UInt (uint64_t u) inline
Definition at line 1100 of file flexbuffers.h.
{ stack_.push_back(Value(u, FBT_UINT, WidthU(u))); }
References flexbuffers::FBT_UINT, and flexbuffers::WidthU().
Vector() [1/7]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (const char * key, const T * elems, size_t len) inline
Definition at line 1360 of file flexbuffers.h.
  {
    Key(key);
    Vector(elems, len);
  }
Vector() [2/7]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (const char * key, F f) inline
Definition at line 1332 of file flexbuffers.h.
  {
    auto start = StartVector(key);
    f();
    return EndVector(start, false, false);
  }
Vector() [3/7]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (const char * key, F f, T & state) inline
Definition at line 1338 of file flexbuffers.h.
  {
    auto start = StartVector(key);
    f(state);
    return EndVector(start, false, false);
  }
Vector() [4/7]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (const std::vector< T > & vec) inline
Definition at line 1365 of file flexbuffers.h.
  {
    Vector(flatbuffers::vector_data(vec), vec.size());
  }
References flatbuffers::vector_data().
Vector() [5/7]
template<typename T > void flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (const T * elems, size_t len) inline
Definition at line 1345 of file flexbuffers.h.
  {
    if (flatbuffers::is_scalar<T>::value)
    {
      // This path should be a lot quicker and use less space.
      ScalarVector(elems, len, false);
    }
    else
    {
      auto start = StartVector();
      for (size_t i = 0; i < len; i++)
        Add(elems[i]);
      EndVector(start, false, false);
    }
  }
References Add().
Vector() [6/7]
template<typename F > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (F f) inline
Definition at line 1320 of file flexbuffers.h.
  {
    auto start = StartVector();
    f();
    return EndVector(start, false, false);
  }
Vector() [7/7]
template<typename F , typename T > size_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Vector (F f, T & state) inline
Definition at line 1326 of file flexbuffers.h.
  {
    auto start = StartVector();
    f(state);
    return EndVector(start, false, false);
  }
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h