ONE - On-device Neural Engine: FeatureDecodeLayer::Return Class Reference
FeatureDecodeLayer::Return Class Reference
#include <GraphBuilder.h>
Public Member Functions
Return (loco::FeatureDecode *node)
Return * perm (const loco::Permutation< loco::Domain::Feature > &perm)
loco::FeatureDecode * node (void)
Detailed Description
Definition at line 309 of file GraphBuilder.h.
Constructor & Destructor Documentation
Return()
FeatureDecodeLayer::Return::Return (loco::FeatureDecode * node) inline
Definition at line 312 of file GraphBuilder.h.
                                    : _node{node}
    {
      // DO NOTHING
    }
Member Function Documentation
node()
loco::FeatureDecode * FeatureDecodeLayer::Return::node (void) inline
Definition at line 326 of file GraphBuilder.h.
{ return _node; }
perm()
Return * FeatureDecodeLayer::Return::perm (const loco::Permutation< loco::Domain::Feature > & perm) inline
Definition at line 318 of file GraphBuilder.h.
    {
      using namespace loco;
      _node->decoder(std::make_unique<PermutingDecoder<Domain::Feature>>(perm));
      return this;
    }
References loco::FeatureDecode::decoder(), and perm().
Referenced by perm().
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h