ONE - On-device Neural Engine: onert::backend::train::ops::DepthwiseConvolutionLayer Class Reference
onert::backend::train::ops::DepthwiseConvolutionLayer Class Reference
#include <DepthwiseConvolutionLayer.h>
Public Member Functions
DepthwiseConvolutionLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *kernel, const IPortableTensor *bias, IPortableTensor *output, IPortableTensor *back_prop_input, IPortableTensor *grad_weights, IPortableTensor *grad_bias, const IPortableTensor *back_prop_output, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t multiplier, const uint32_t dilationWidth, const uint32_t dilationHeight, const ir::Activation activation, const std::shared_ptr< ExternalContext > &external_context)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
Public Member Functions inherited from onert::backend::cpu::ops::DepthwiseConvolutionLayer
DepthwiseConvolutionLayer ()=default
void convFloat32 ()
void convQ8uPerTensor ()
void convQ8uPerChannel ()
void convQ8i ()
void convQ8iHybridPerChannel ()
void configure (const IPortableTensor *input, const IPortableTensor *kernel, const IPortableTensor *bias, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideW, const uint32_t strideH, const uint32_t multiplier, const uint32_t dilationWidth, const uint32_t dilationHeight, const ir::Activation activation, IPortableTensor *output, const std::shared_ptr< ExternalContext > &external_context)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::DepthwiseConvolutionLayer
const IPortableTensor * _input {nullptr}
const IPortableTensor * _kernel {nullptr}
const IPortableTensor * _bias {nullptr}
IPortableTensor * _output {nullptr}
uint32_t _paddingLeft {0}
uint32_t _paddingTop {0}
uint32_t _paddingRight {0}
uint32_t _paddingBottom {0}
uint32_t _strideWidth {0}
uint32_t _strideHeight {0}
uint32_t _multiplier {0}
uint32_t _dilationWidth {1}
uint32_t _dilationHeight {1}
ir::Activation _activation {ir::Activation::NONE}
Detailed Description
Definition at line 37 of file DepthwiseConvolutionLayer.h.
Constructor & Destructor Documentation
DepthwiseConvolutionLayer()
onert::backend::train::ops::DepthwiseConvolutionLayer::DepthwiseConvolutionLayer ()
Definition at line 32 of file DepthwiseConvolutionLayer.cc.
  : cpu::ops::DepthwiseConvolutionLayer(), _grad_weights{nullptr}, _grad_bias{nullptr},
    _back_prop_input{nullptr}, _back_prop_output{nullptr}, _act_back_prop_output{nullptr},
    _use_padded_filter{false}, _padded_filter{nullptr}, _filter_buffers{nullptr},
    _filter_dim_buffers{nullptr},
    _dconv_kernel{std::make_unique<nnfw::cker::train::DepthwiseConv>()}
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::DepthwiseConvolutionLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 117 of file DepthwiseConvolutionLayer.cc.
{
  const auto data_type = _back_prop_output->data_type();
  assert(data_type == _input->data_type());
  switch (data_type)
  {
    case OperandType::FLOAT32:
    {
      assert(data_type == _grad_bias->data_type());
      backwardFloat32();
      break;
    }
    default:
      throw std::runtime_error{"train DepthwiseConvolutionLayer: unsupported data type"};
  }
}
References onert::backend::cpu::ops::DepthwiseConvolutionLayer::_input, and onert::backend::ITensor::data_type().
configure()
void onert::backend::train::ops::DepthwiseConvolutionLayer::configure (const IPortableTensor * input, const IPortableTensor * kernel, const IPortableTensor * bias, IPortableTensor * output, IPortableTensor * back_prop_input, IPortableTensor * grad_weights, IPortableTensor * grad_bias, const IPortableTensor * back_prop_output, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t multiplier, const uint32_t dilationWidth, const uint32_t dilationHeight, const ir::Activation activation, const std::shared_ptr< ExternalContext > & external_context)
Definition at line 42 of file DepthwiseConvolutionLayer.cc.
{
  cpu::ops::DepthwiseConvolutionLayer::configure(
    input, kernel, bias, paddingLeft, paddingRight, paddingTop, paddingBottom, strideWidth,
    strideHeight, multiplier, dilationWidth, dilationHeight, activation, output, external_context);
  _back_prop_input = back_prop_input;
  _back_prop_output = back_prop_output;
  _grad_weights = grad_weights;
  _grad_bias = grad_bias;
  if (activation != ir::Activation::NONE)
  {
    _act_back_prop_output =
      std::make_unique<BackPropTensor>(_back_prop_output->get_info(), _back_prop_output->layout());
    _act_back_prop_output->setBuffer(
      std::make_shared<basic::Allocator>(_act_back_prop_output->total_size()));
  }
  const int64_t k_packet_size = [&]() {
    const auto data_type = _back_prop_output->data_type();
    switch (data_type)
    {
      case OperandType::FLOAT32:
      {
        return _dconv_kernel->kPacketSize<float>();
      }
      default:
        throw std::runtime_error("train DepthwiseConvolutionLayer: unsupported data type");
    }
  }();
  const auto incoming_shape = getShape(_back_prop_output);
  const auto filter_shape = getShape(_kernel);
  const int batch = incoming_shape.Dims(0);
  const int out_depth = incoming_shape.Dims(3);
  const int filter_rows = filter_shape.Dims(1);
  const int filter_cols = filter_shape.Dims(2);
  const int filter_spatial_size = filter_rows * filter_cols;
  const int padded_filter_inner_dim_size =
    ((out_depth + k_packet_size - 1) / k_packet_size) * k_packet_size;
  _use_padded_filter = (out_depth % k_packet_size) == 0 ? false : true;
  // prepare padded_filter buffer for cker
  auto padded_filter_info = ir::OperandInfo(_kernel->get_info());
  padded_filter_info.shape({batch, filter_spatial_size, padded_filter_inner_dim_size});
  _padded_filter = std::make_unique<Tensor>(padded_filter_info, _kernel->layout());
  _padded_filter->setBuffer(std::make_shared<basic::Allocator>(_padded_filter->total_size()));
  // prepare out_bprop and in_bprop buffer for cker
  const int thread_count = _dconv_kernel->getThreadCount();
  auto filter_buffers_info = ir::OperandInfo(_kernel->get_info());
  filter_buffers_info.shape({thread_count, filter_spatial_size, padded_filter_inner_dim_size});
  _filter_buffers = std::make_unique<Tensor>(filter_buffers_info, _kernel->layout());
  _filter_buffers->setBuffer(std::make_shared<basic::Allocator>(_filter_buffers->total_size()));
  auto filter_dim_buffers_info = ir::OperandInfo(_back_prop_input->get_info());
  filter_dim_buffers_info.shape({thread_count, padded_filter_inner_dim_size});
  _filter_dim_buffers =
    std::make_unique<Tensor>(filter_dim_buffers_info, _back_prop_input->layout());
  _filter_dim_buffers->setBuffer(
    std::make_shared<basic::Allocator>(_filter_dim_buffers->total_size()));
}
References onert::backend::cpu::ops::DepthwiseConvolutionLayer::_kernel, onert::backend::cpu::ops::DepthwiseConvolutionLayer::configure(), onert::backend::ITensor::data_type(), onert::backend::IPortableTensor::get_info(), onert::backend::ITensor::layout(), and onert::ir::NONE.
forward()
void onert::backend::train::ops::DepthwiseConvolutionLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 115 of file DepthwiseConvolutionLayer.cc.
{ cpu::ops::DepthwiseConvolutionLayer::run(); }
References onert::backend::cpu::ops::DepthwiseConvolutionLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.h
runtime/onert/backend/train/ops/DepthwiseConvolutionLayer.cc