ONE - On-device Neural Engine: moco::tf::COpCallGraphBuilder Class Reference
moco::tf::COpCallGraphBuilder Class Reference final
GraphBuilder for COpCall node.
#include <COpCall.h>
Public Member Functions
COpCallGraphBuilder (const ModelSignature *signature)
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for COpCall node.
Definition at line 32 of file COpCall.h.
Constructor & Destructor Documentation
COpCallGraphBuilder()
moco::tf::COpCallGraphBuilder::COpCallGraphBuilder (const ModelSignature * signature) inline
Definition at line 35 of file COpCall.h.
                                                       : _signature(signature)
  { /* empty */
  }
Member Function Documentation
build()
void moco::tf::COpCallGraphBuilder::build (const tensorflow::NodeDef & tf_node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 69 of file COpCall.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  // Create a "COpCall" node for CustomOp and set attributes
  auto call_node = graph->nodes()->create<locoex::COpCall>(tf_node.input_size());
  {
    call_node->op(tf_node.op());
    call_node->name(tf_node.name());
    call_node->dtype(_signature->dtype(tf_node.name()));
    auto shape = _signature->shape(tf_node.name());
    call_node->rank(shape->rank());
    for (int d = 0; d < shape->rank(); d++)
      call_node->dim(d) = shape->dim(d);
    for (auto iter = tf_node.attr().begin(); iter != tf_node.attr().end(); iter++)
    {
      auto name = iter->first;
      auto val = iter->second;
      if (val.value_case() == tensorflow::AttrValue::kF)
      {
        call_node->attr(name, std::make_unique<locoex::COpAttrFloat>(val.f()));
      }
      else if (val.value_case() == tensorflow::AttrValue::kI)
      {
        call_node->attr(name, std::make_unique<locoex::COpAttrInt>(val.i()));
      }
      // TODO define more types
      else
      {
        throw oops::UserExn("Unsupported attribute type", tf_node.name());
      }
    }
  }
  // register this node with its name
  TensorName output_name(tf_node.name(), 0);
  tensor_names->enroll(output_name, call_node);
  // Queue node input update
  std::vector<TensorName> input_names;
  for (int i = 0; i < tf_node.input_size(); ++i)
  {
    input_names.emplace_back(TensorName(tf_node.input(i)));
  }
  auto update = std::make_unique<COpCallGraphUpdate>(call_node, input_names);
  updates->enroll(std::move(update));
}
References moco::ModelSignature::dtype(), moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), moco::GraphBuilderContext::graph(), locoex::COpCall::op(), moco::ModelSignature::shape(), moco::GraphBuilderContext::tensor_names(), moco::update(), and moco::GraphBuilderContext::updates().
validate()
bool moco::tf::COpCallGraphBuilder::validate (const tensorflow::NodeDef & tf_node) const override virtual
Implements moco::GraphBuilder.
Definition at line 67 of file COpCall.cpp.
{ return true; }
The documentation for this class was generated from the following files:
compiler/moco-tf/src/Op/COpCall.h
compiler/moco-tf/src/Op/COpCall.cpp