ONE - On-device Neural Engine: coco::MaxPool2D Class Reference
coco::MaxPool2D Class Reference final
2D Max Pooling
#include <Ops.h>
Public Member Functions
MaxPool2D ()=default
MaxPool2D (const MaxPool2D &)=delete
MaxPool2D (MaxPool2D &&)=delete
MaxPool2D * asMaxPool2D (void) override
const MaxPool2D * asMaxPool2D (void) const override
Window2D * window (void)
const Window2D * window (void) const
Stride2D * stride (void)
const Stride2D * stride (void) const
Padding2D * pad (void)
const Padding2D * pad (void) const
Public Member Functions inherited from coco::UnaryOp
UnaryOp ()
UnaryOp (const UnaryOp &)=delete
UnaryOp (UnaryOp &&)=delete
virtual ~UnaryOp ()=default
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const final
Return a set of object(s) used during execution.
Op * arg (void) const
void arg (Op *arg)
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Detailed Description
2D Max Pooling
Definition at line 141 of file Ops.h.
Constructor & Destructor Documentation
MaxPool2D() [1/3]
coco::MaxPool2D::MaxPool2D () explicit default
MaxPool2D() [2/3]
coco::MaxPool2D::MaxPool2D (const MaxPool2D &) delete
MaxPool2D() [3/3]
coco::MaxPool2D::MaxPool2D (MaxPool2D &&) delete
Member Function Documentation
asMaxPool2D() [1/2]
const MaxPool2D * coco::MaxPool2D::asMaxPool2D (void) const inline override
Definition at line 152 of file Ops.h.
{ return this; }
asMaxPool2D() [2/2]
MaxPool2D * coco::MaxPool2D::asMaxPool2D (void) inline override
Definition at line 151 of file Ops.h.
{ return this; }
pad() [1/2]
Padding2D * coco::MaxPool2D::pad (void) inline
Definition at line 163 of file Ops.h.
{ return &_pad; }
Referenced by tflimport::MaxPool2DGraphBuilder::build().
pad() [2/2]
const Padding2D * coco::MaxPool2D::pad (void) const inline
Definition at line 164 of file Ops.h.
{ return &_pad; }
stride() [1/2]
Stride2D * coco::MaxPool2D::stride (void) inline
Definition at line 159 of file Ops.h.
{ return &_stride; }
Referenced by tflimport::MaxPool2DGraphBuilder::build().
stride() [2/2]
const Stride2D * coco::MaxPool2D::stride (void) const inline
Definition at line 160 of file Ops.h.
{ return &_stride; }
window() [1/2]
Window2D * coco::MaxPool2D::window (void) inline
Definition at line 155 of file Ops.h.
{ return &_window; }
Referenced by tflimport::MaxPool2DGraphBuilder::build().
window() [2/2]
const Window2D * coco::MaxPool2D::window (void) const inline
Definition at line 156 of file Ops.h.
{ return &_window; }
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/IR/Ops.h