ONE - On-device Neural Engine: arser::Argument Class Reference
arser::Argument Class Reference
#include <arser.h>
Public Member Functions
Argument (const std::string &arg_name)
Argument (const std::string &short_name, const std::string &long_name)
Argument (const std::string &short_name, const std::string &long_name, const std::vector< std::string > &names)
Argument & nargs (uint32_t num)
Argument & type (DataType type)
Argument & required (void)
Argument & required (bool value)
Argument & accumulated (void)
Argument & accumulated (bool value)
Argument & help (std::string help_message)
Argument & exit_with (const std::function< void(void)> &func)
template<typename T >
Argument & default_value (const T value)
template<typename T , typename... Ts>
Argument & default_value (const T value, const Ts... values)
Friends
class Arser
std::ostream & operator<< (std::ostream &, const Arser &)
Detailed Description
Argument ├── positional argument └── optioanl argument [ dash at the beginning of the string ] ├── long option [ two or more dashes ] └── short option [ one dash ]
Argument has two types - positional argument, optional argument.
The way to distinguish the two types is whether there is a dash('-') at the beginning of the string.
And, optional argument has two types as well - long option, short option, which is distinguished by the number of dash.
Definition at line 167 of file arser.h.
Constructor & Destructor Documentation
Argument() [1/3]
arser::Argument::Argument (const std::string & arg_name) inline explicit
Definition at line 170 of file arser.h.
: _long_name{arg_name}, _names{arg_name} {}
Argument() [2/3]
arser::Argument::Argument (const std::string & short_name, const std::string & long_name) inline explicit
Definition at line 171 of file arser.h.
    : _short_name{short_name}, _long_name{long_name}, _names{short_name, long_name}
  {
  }
Argument() [3/3]
arser::Argument::Argument (const std::string & short_name, const std::string & long_name, const std::vector< std::string > & names) inline explicit
Definition at line 175 of file arser.h.
    : _short_name{short_name}, _long_name{long_name}, _names{names}
  {
    // 'names' must have 'short_name' and 'long_name'.
    auto it = std::find(names.begin(), names.end(), short_name);
    assert(it != names.end());
    it = std::find(names.begin(), names.end(), long_name);
    assert(it != names.end());
    // for avoiding unused warning.
    (void)it;
  }
Member Function Documentation
accumulated() [1/2]
Argument & arser::Argument::accumulated (bool value) inline
Definition at line 247 of file arser.h.
  {
    _is_accumulated = value;
    return *this;
  }
accumulated() [2/2]
Argument & arser::Argument::accumulated (void) inline
Definition at line 241 of file arser.h.
  {
    _is_accumulated = true;
    return *this;
  }
default_value() [1/2]
template<typename T > Argument & arser::Argument::default_value (const T value) inline
Definition at line 265 of file arser.h.
  {
    if ((_nargs <= 1 && TypeName<T>::Get() == _type) ||
        (_nargs > 1 && TypeName<std::vector<T>>::Get() == _type))
      _values.emplace_back(internal::to_string(value));
    else
    {
      throw std::runtime_error("Type mismatch. "
                               "You called default_value() method with a type different "
                               "from the one you specified. "
                               "Please check the type of what you specified in "
                               "add_argument() method.");
    }
    return *this;
  }
References arser::internal::to_string().
Referenced by default_value().
default_value() [2/2]
template<typename T , typename... Ts> Argument & arser::Argument::default_value (const T value, const Ts... values) inline
Definition at line 281 of file arser.h.
  {
    if ((_nargs <= 1 && TypeName<T>::Get() == _type) ||
        (_nargs > 1 && TypeName<std::vector<T>>::Get() == _type))
    {
      _values.emplace_back(internal::to_string(value));
      default_value(values...);
    }
    else
    {
      throw std::runtime_error("Type mismatch. "
                               "You called default_value() method with a type different "
                               "from the one you specified. "
                               "Please check the type of what you specified in "
                               "add_argument() method.");
    }
    return *this;
  }
References default_value(), and arser::internal::to_string().
exit_with()
Argument & arser::Argument::exit_with (const std::function< void(void)> & func) inline
Definition at line 259 of file arser.h.
  {
    _func = func;
    return *this;
  }
help()
Argument & arser::Argument::help (std::string help_message) inline
Definition at line 253 of file arser.h.
  {
    _help_message = help_message;
    return *this;
  }
nargs()
Argument & arser::Argument::nargs (uint32_t num) inline
Definition at line 188 of file arser.h.
  {
    if (num == 0)
    {
      _type = "bool";
    }
    _nargs = num;
    return *this;
  }
required() [1/2]
Argument & arser::Argument::required (bool value) inline
Definition at line 235 of file arser.h.
  {
    _is_required = value;
    return *this;
  }
required() [2/2]
Argument & arser::Argument::required (void) inline
Definition at line 229 of file arser.h.
  {
    _is_required = true;
    return *this;
  }
type()
Argument & arser::Argument::type (DataType type) inline
Definition at line 198 of file arser.h.
  {
    switch (type)
    {
      case DataType::INT32:
        _type = "int";
        break;
      case DataType::INT32_VEC:
        _type = "vector<int>";
        break;
      case DataType::FLOAT:
        _type = "float";
        break;
      case DataType::FLOAT_VEC:
        _type = "vector<float>";
        break;
      case DataType::BOOL:
        _type = "bool";
        break;
      case DataType::STR:
        _type = "string";
        break;
      case DataType::STR_VEC:
        _type = "vector<string>";
        break;
      default:
        throw std::runtime_error("NYI DataType");
    }
    return *this;
  }
References type().
Referenced by OptionBuilder.OptionBuilder::build(), and type().
Friends And Related Function Documentation
Arser
friend class Arser friend
Definition at line 315 of file arser.h.
operator<<
std::ostream & operator<< (std::ostream & , const Arser &) friend
The documentation for this class was generated from the following file:
compiler/arser/include/arser/arser.h