ONE - On-device Neural Engine: pp::IndentedStringBuilder Class Reference
pp::IndentedStringBuilder Class Reference
#include <IndentedStringBuilder.h>
Public Member Functions
IndentedStringBuilder ()
void increase (void)
void decrease (void)
std::string build (const std::string &content)
template<typename... Args>
std::string build (const Args &... args)
Detailed Description
Definition at line 25 of file IndentedStringBuilder.h.
Constructor & Destructor Documentation
IndentedStringBuilder()
pp::IndentedStringBuilder::IndentedStringBuilder () inline
Definition at line 28 of file IndentedStringBuilder.h.
                          : _level{0}
  {
    // DO NOTHING
  }
Member Function Documentation
build() [1/2]
template<typename... Args> std::string pp::IndentedStringBuilder::build (const Args &... args) inline
Definition at line 41 of file IndentedStringBuilder.h.
  {
    return build(fmt(args...));
  }
References build().
build() [2/2]
std::string pp::IndentedStringBuilder::build (const std::string & content)
Definition at line 37 of file IndentedStringBuilder.cpp.
{
  assert(std::find(content.begin(), content.end(), '\n') == content.end());
  const char c = ' ';
  const size_t space_per_indent_level = 2;
  const size_t space_count = space_per_indent_level * _level;
  return std::string(space_count, c) + content;
}
Referenced by pp::LinearDocument::append(), and build().
decrease()
void pp::IndentedStringBuilder::decrease (void)
Definition at line 31 of file IndentedStringBuilder.cpp.
{
  assert(_level > 0);
  --_level;
}
Referenced by pp::LinearDocument::unindent().
increase()
void pp::IndentedStringBuilder::increase (void)
Definition at line 25 of file IndentedStringBuilder.cpp.
{
  // TODO Check overflow
  ++_level;
}
Referenced by pp::LinearDocument::indent().
The documentation for this class was generated from the following files:
compiler/pp/include/pp/IndentedStringBuilder.h
compiler/pp/src/IndentedStringBuilder.cpp