ONE - On-device Neural Engine: luci_interpreter::kernels::Sin Class Reference
luci_interpreter::kernels::Sin Class Reference
#include <Sin.h>
Public Member Functions
Sin (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file Sin.h.
Constructor & Destructor Documentation
Sin()
luci_interpreter::kernels::Sin::Sin (const Tensor * input, Tensor * output)
Definition at line 43 of file Sin.cpp.
: Kernel({input}, {output}) {}
References input().
Member Function Documentation
configure()
void luci_interpreter::kernels::Sin::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 45 of file Sin.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == DataType::FLOAT32);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
execute()
void luci_interpreter::kernels::Sin::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 52 of file Sin.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("luci-intp Sin Unsupported type.");
  }
}
References input().
input()
const Tensor * luci_interpreter::kernels::Sin::input () const inline
Definition at line 33 of file Sin.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Sin().
output()
Tensor * luci_interpreter::kernels::Sin::output () const inline
Definition at line 34 of file Sin.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Sin.h
compiler/luci-interpreter/src/kernels/Sin.cpp