ONE - On-device Neural Engine: arm_compute::NEInstanceNormalizationLayerKernelEx Class Reference
arm_compute::NEInstanceNormalizationLayerKernelEx Class Reference
#include <NEInstanceNormalizationLayerKernelEx.h>
Public Member Functions
const char * name () const override
NEInstanceNormalizationLayerKernelEx ()
NEInstanceNormalizationLayerKernelEx (const NEInstanceNormalizationLayerKernelEx &)=delete
NEInstanceNormalizationLayerKernelEx & operator= (const NEInstanceNormalizationLayerKernelEx &)=delete
NEInstanceNormalizationLayerKernelEx (NEInstanceNormalizationLayerKernelEx &&)=default
NEInstanceNormalizationLayerKernelEx & operator= (NEInstanceNormalizationLayerKernelEx &&)=default
~NEInstanceNormalizationLayerKernelEx ()=default
void configure (ITensor *input, ITensor *output, ITensor *gamma=nullptr, ITensor *beta=nullptr, float epsilon=1e-12f)
void run (const Window &window, const ThreadInfo &info) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *gamma=nullptr, const ITensorInfo *beta=nullptr, float epsilon=1e-12f)
Detailed Description
Interface for performing an instance normalization
Definition at line 51 of file NEInstanceNormalizationLayerKernelEx.h.
Constructor & Destructor Documentation
NEInstanceNormalizationLayerKernelEx() [1/3]
arm_compute::NEInstanceNormalizationLayerKernelEx::NEInstanceNormalizationLayerKernelEx ()
Default constructor
Definition at line 241 of file NEInstanceNormalizationLayerKernelEx.cpp.
  : _func(nullptr), _input(nullptr), _output(nullptr), _gamma(nullptr), _beta(nullptr),
    _epsilon(1e-12)
{
}
NEInstanceNormalizationLayerKernelEx() [2/3]
arm_compute::NEInstanceNormalizationLayerKernelEx::NEInstanceNormalizationLayerKernelEx (const NEInstanceNormalizationLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEInstanceNormalizationLayerKernelEx() [3/3]
arm_compute::NEInstanceNormalizationLayerKernelEx::NEInstanceNormalizationLayerKernelEx (NEInstanceNormalizationLayerKernelEx &&) default
Allow instances of this class to be moved
~NEInstanceNormalizationLayerKernelEx()
arm_compute::NEInstanceNormalizationLayerKernelEx::~NEInstanceNormalizationLayerKernelEx () default
Default destructor
References validate().
Member Function Documentation
configure()
void arm_compute::NEInstanceNormalizationLayerKernelEx::configure (ITensor * input, ITensor * output, ITensor * gamma = nullptr, ITensor * beta = nullptr, float epsilon = 1e-12f)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. Data types supported: F16/F32. Data layout supported: NCHW In case of output tensor = nullptr this tensor will store the result of the normalization.
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Definition at line 247 of file NEInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input);
  _input = input;
  _output = output == nullptr ? input : output;
  _gamma = gamma;
  _beta = beta;
  _epsilon = epsilon;
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(_input->info(), _output->info(), gamma->info(), beta->info(), epsilon));
  if (_input->info()->data_type() == DataType::F32)
  {
    _func = &instance_normalization_nchw<float>;
  }
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
  else if (_input->info()->data_type() == DataType::F16)
  {
    _func = &instance_normalization_nchw<float16_t>;
  }
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
  else
  {
    ARM_COMPUTE_ERROR("Unsupported data type");
  }
  // Configure kernel window
  auto win_config = validate_and_configure_window(_input->info(), _output->info());
  ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
  INEKernel::configure(std::get<1>(win_config));
}
Referenced by arm_compute::NEInstanceNormalizationLayerEx::configure().
name()
const char * arm_compute::NEInstanceNormalizationLayerKernelEx::name () const inline override
Definition at line 54 of file NEInstanceNormalizationLayerKernelEx.h.
{ return "NEInstanceNormalizationLayerKernelEx"; }
operator=() [1/2]
NEInstanceNormalizationLayerKernelEx & arm_compute::NEInstanceNormalizationLayerKernelEx::operator= (const NEInstanceNormalizationLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEInstanceNormalizationLayerKernelEx & arm_compute::NEInstanceNormalizationLayerKernelEx::operator= (NEInstanceNormalizationLayerKernelEx &&) default
Allow instances of this class to be moved
run()
void arm_compute::NEInstanceNormalizationLayerKernelEx::run (const Window & window, const ThreadInfo & info) override
Definition at line 294 of file NEInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_UNUSED(info);
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
  (*_func)(_input, _output, _gamma, _beta, _epsilon, window);
}
References info.
validate()
Status arm_compute::NEInstanceNormalizationLayerKernelEx::validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * gamma = nullptr, const ITensorInfo * beta = nullptr, float epsilon = 1e-12f) static
Static function to check if given info will lead to a valid configuration of NEInstanceNormalizationLayer.
Parameters
[in] input Source tensor info. Data types supported: F16/F32. Data layout supported: NCHW
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale scalar value applied to the normalized tensor. Defaults to 1.0
[in] beta (Optional) The offset scalar value applied to the normalized tensor. Defaults to 0.0
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Returns
a status
Definition at line 283 of file NEInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, gamma, beta, epsilon));
  ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(
    input->clone().get(), (output == nullptr ? input->clone().get() : output->clone().get()))));
  return Status{};
}
Referenced by arm_compute::NEInstanceNormalizationLayerEx::validate(), and ~NEInstanceNormalizationLayerKernelEx().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEInstanceNormalizationLayerKernelEx.h
compute/ARMComputeEx/src/core/NEON/kernels/NEInstanceNormalizationLayerKernelEx.cpp