ONE - On-device Neural Engine: onert::ir::Operand Class Reference
onert::ir::Operand Class Reference
#include <Operand.h>
Public Member Functions
Operand (const Shape &shape, const TypeInfo &type)
Operand (const Operand &)=default
const Shape & shape (void) const
const TypeInfo & typeInfo (void) const
const OperandInfo & info (void) const
OperandInfo & info (void)
size_t operandSize (void) const
const OperationIndexSet & getUses () const
OperationIndex getDef () const
void insertUse (const OperationIndex &idx)
void removeUse (const OperationIndex &idx)
void setDef (const OperationIndex &idx)
void unsetDef ()
void clearDefUse ()
void type (const DataType type)
void data (std::shared_ptr< Data > &&data)
const Data * data (void) const
void releaseData (void)
std::shared_ptr< Data > shareData (void) const
bool isConstant (void) const
Get true if Operand is const, otherwise false a.
template<typename T , typename... Args>
void data (Args &&... args)
template<typename T >
T asScalar (void) const
template<typename T >
std::vector< T > asVector () const
Detailed Description
Definition at line 35 of file Operand.h.
Constructor & Destructor Documentation
Operand() [1/2]
onert::ir::Operand::Operand (const Shape & shape, const TypeInfo & type) inline explicit
Definition at line 38 of file Operand.h.
    : _info{shape, type, MemAllocType::STATIC}
  {
    // DO NOTHING
  }
Operand() [2/2]
onert::ir::Operand::Operand (const Operand &) explicit default
Member Function Documentation
asScalar()
template<typename T > T onert::ir::Operand::asScalar (void) const inline
Definition at line 88 of file Operand.h.
  {
    assert((shape().rank() == 0) || ((shape().rank() == 1) && (shape().dim(0) == 1)));
    assert(_data != nullptr);
    assert((_data->base() != nullptr) && (_data->size() == sizeof(T)));
    return *(reinterpret_cast<const T *>(_data->base()));
  }
References shape().
Referenced by onert::backend::acl_common::asPixelValue().
asVector()
template<typename T > std::vector< T > onert::ir::Operand::asVector () const inline
Definition at line 97 of file Operand.h.
  {
    assert(_data != nullptr);
    assert(_data->size() % sizeof(T) == 0);
    const auto *base = reinterpret_cast<const T *>(_data->base());
    const std::size_t size = _data->size() / sizeof(T);
    return std::vector<T>(base, base + size);
  }
clearDefUse()
void Operand::clearDefUse ()
Definition at line 49 of file Operand.cc.
{
  unsetDef();
  _uses.clear();
}
References onert::ir::OperationIndexSet::clear(), and unsetDef().
Referenced by onert::compiler::pass::ConstantInsertionPass::callback().
data() [1/3]
template<typename T , typename... Args> void onert::ir::Operand::data (Args &&... args) inline
Definition at line 82 of file Operand.h.
  {
    data(std::make_unique<T>(std::forward<Args>(args)...));
  }
References data().
data() [2/3]
void onert::ir::Operand::data (std::shared_ptr< Data > && data) inline
Definition at line 64 of file Operand.h.
  {
    _data = std::move(data);
    _info.setAsConstant();
  }
References data(), and onert::ir::OperandInfo::setAsConstant().
Referenced by onert::backend::acl_common::asSet(), onert::backend::acl_common::initReverseOrder(), onert::backend::acl_common::AclConstantInitializer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), and onert::backend::acl_neon::ConstantInitializer::visit().
data() [3/3]
const Data * onert::ir::Operand::data (void) const inline
Definition at line 69 of file Operand.h.
{ return _data.get(); }
Referenced by data().
getDef()
OperationIndex onert::ir::Operand::getDef () const inline
Definition at line 53 of file Operand.h.
{ return _def; }
getUses()
const OperationIndexSet & onert::ir::Operand::getUses () const inline
Definition at line 52 of file Operand.h.
{ return _uses; }
info() [1/2]
OperandInfo & onert::ir::Operand::info (void) inline
Definition at line 49 of file Operand.h.
{ return _info; }
info() [2/2]
const OperandInfo & onert::ir::Operand::info (void) const inline
Definition at line 48 of file Operand.h.
{ return _info; }
Referenced by onert::compiler::StaticShapeInferer::dump().
insertUse()
void Operand::insertUse (const OperationIndex & idx)
Definition at line 41 of file Operand.cc.
{ _uses.insert(idx); }
References onert::ir::OperationIndexSet::insert().
isConstant()
bool onert::ir::Operand::isConstant (void) const inline
Get true if Operand is const, otherwise false a.
Returns
true if Operand is const, otherwise false
Definition at line 79 of file Operand.h.
{ return _info.isConstant(); }
References onert::ir::OperandInfo::isConstant().
Referenced by onert::backend::acl_common::asPixelValue(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::initConsts(), and onert::backend::basic::initConsts().
operandSize()
size_t Operand::operandSize (void) const
Definition at line 24 of file Operand.cc.
{
  const uint32_t ranks = shape().rank();
  int32_t elements = 1;
  for (uint32_t rank = 0; rank < ranks; rank++)
  {
    elements *= shape().dim(rank);
  }
  DataType type = typeInfo().type();
  size_t element_size = sizeOfDataType(type);
  // Value of type is matched with OperandCode enum in NeuralNetworks.h
  return element_size * elements;
}
References shape(), onert::ir::sizeOfDataType(), onert::ir::TypeInfo::type(), type(), and typeInfo().
releaseData()
void onert::ir::Operand::releaseData (void) inline
Definition at line 71 of file Operand.h.
{ _data.reset(); }
removeUse()
void Operand::removeUse (const OperationIndex & idx)
Definition at line 43 of file Operand.cc.
{ _uses.remove(idx); }
References onert::ir::OperationIndexSet::remove().
setDef()
void Operand::setDef (const OperationIndex & idx)
Definition at line 45 of file Operand.cc.
{ _def = idx; }
shape()
const Shape & onert::ir::Operand::shape (void) const inline
Definition at line 46 of file Operand.h.
{ return _info.shape(); }
References onert::ir::OperandInfo::shape().
Referenced by onert::backend::acl_common::asPixelValue(), asScalar(), onert::backend::acl_common::asSet(), onert::backend::acl_common::initReverseOrder(), operandSize(), onert::backend::acl_common::AclConstantInitializer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), and onert::backend::acl_neon::ConstantInitializer::visit().
shareData()
std::shared_ptr< Data > onert::ir::Operand::shareData (void) const inline
Definition at line 73 of file Operand.h.
{ return _data; }
Referenced by onert::backend::basic::initConsts().
type()
void onert::ir::Operand::type (const DataType type) inline
Definition at line 61 of file Operand.h.
{ _info.type(type); };
References type(), and onert::ir::OperandInfo::type().
Referenced by OptionBuilder.OptionBuilder::build(), operandSize(), and type().
typeInfo()
const TypeInfo & onert::ir::Operand::typeInfo (void) const inline
Definition at line 47 of file Operand.h.
{ return _info.typeInfo(); }
References onert::ir::OperandInfo::typeInfo().
Referenced by onert::backend::acl_common::asPixelValue(), onert::backend::acl_common::asSet(), and operandSize().
unsetDef()
void Operand::unsetDef ()
Definition at line 47 of file Operand.cc.
{ _def = OperationIndex{}; }
Referenced by clearDefUse().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/Operand.h
runtime/onert/core/src/ir/Operand.cc