ONE - On-device Neural Engine: mir::ops::SqueezeOp Class Reference
mir::ops::SqueezeOp Class Reference
#include <SqueezeOp.h>
Public Member Functions
SqueezeOp (Output *arg, const std::vector< std::int32_t > &dims_to_squeeze)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
void inferOutputTypes ()
int32_t getNumSqueezeDims () const
const std::vector< int32_t > & getDimsToSqueeze () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 28 of file SqueezeOp.h.
Constructor & Destructor Documentation
SqueezeOp()
mir::ops::SqueezeOp::SqueezeOp (Output * arg, const std::vector< std::int32_t > & dims_to_squeeze) inline
Definition at line 31 of file SqueezeOp.h.
    : Operation(Type::squeeze, {arg}), _dims_to_squeeze(dims_to_squeeze)
  {
    // Infer output shape.
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::SqueezeOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 38 of file SqueezeOp.h.
  {
    return new SqueezeOp(inputs[0], _dims_to_squeeze);
  }
getDimsToSqueeze()
const std::vector< int32_t > & mir::ops::SqueezeOp::getDimsToSqueeze () const inline
Definition at line 47 of file SqueezeOp.h.
{ return _dims_to_squeeze; }
Referenced by inferOutputTypes(), and mir::DotNodeBuilder::visit().
getNumSqueezeDims()
int32_t mir::ops::SqueezeOp::getNumSqueezeDims () const inline
Definition at line 45 of file SqueezeOp.h.
{ return static_cast<int32_t>(_dims_to_squeeze.size()); }
Referenced by inferOutputTypes().
inferOutputTypes()
void mir::ops::SqueezeOp::inferOutputTypes ()
Definition at line 24 of file SqueezeOp.cpp.
{
  assert(getNumInputs() == 1);
  const auto &input_shape = getInputShape(0);
  auto dt = getInput(0)->getElementType();
  int32_t input_rank = input_shape.rank();
  std::vector<int32_t> dims_to_squeeze;
  if (getNumSqueezeDims() == 0)
  {
    for (int32_t i = 0; i < input_rank; ++i)
    {
      if (input_shape.dim(i) == 1)
      {
        dims_to_squeeze.push_back(i);
      }
    }
  }
  else
  {
    dims_to_squeeze = getDimsToSqueeze();
    sort(dims_to_squeeze.begin(), dims_to_squeeze.end());
    dims_to_squeeze.erase(unique(dims_to_squeeze.begin(), dims_to_squeeze.end()),
                          dims_to_squeeze.end());
  }
  if (dims_to_squeeze.size() == static_cast<size_t>(input_rank))
  {
    // Input shape have 1s in all dimensions, output shape is (1,)
    setOutputType(0, {dt, Shape{1}});
    return;
  }
  int32_t output_rank = 0;
  size_t squeezing_idx = 0;
  Shape output_shape(input_rank - dims_to_squeeze.size());
  for (int32_t i = 0; i < input_rank; ++i)
  {
    if (squeezing_idx < dims_to_squeeze.size() && i == dims_to_squeeze[squeezing_idx])
    {
      if (input_shape.dim(i) != 1)
        throw std::invalid_argument("All squeezed dimensions should have size 1");
      squeezing_idx++;
    }
    else
    {
      output_shape.dim(output_rank++) = input_shape.dim(i);
    }
  }
  setOutputType(0, {dt, output_shape});
}
References getDimsToSqueeze(), mir::Operation::Output::getElementType(), mir::Operation::getInput(), mir::Operation::getInputShape(), mir::Operation::getNumInputs(), getNumSqueezeDims(), and mir::Operation::setOutputType().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/SqueezeOp.h
compiler/mir/src/ops/SqueezeOp.cpp