ONE - On-device Neural Engine: flatbuffers::Array< T, length > Class Template Reference
flatbuffers::Array< T, length > Class Template Reference
#include <flatbuffers.h>
Public Types
typedef uint16_t size_type
typedef IndirectHelper< IndirectHelperType >::return_type return_type
typedef VectorIterator< T, return_type > const_iterator
typedef VectorReverseIterator< const_iterator > const_reverse_iterator
Public Member Functions
FLATBUFFERS_CONSTEXPR uint16_t size () const
return_type Get (uoffset_t i) const
return_type operator[] (uoffset_t i) const
template<typename E >
E GetEnum (uoffset_t i) const
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
flatbuffers::conditional< scalar_tag::value, void, T * >::type GetMutablePointer (uoffset_t i) const
void Mutate (uoffset_t i, const T &val)
const uint8_t * Data () const
uint8_t * Data ()
const T * data () const
T * data ()
void CopyFromSpan (flatbuffers::span< const T, length > src)
Protected Member Functions
void MutateImpl (flatbuffers::integral_constant< bool, true >, uoffset_t i, const T &val)
void MutateImpl (flatbuffers::integral_constant< bool, false >, uoffset_t i, const T &val)
void CopyFromSpanImpl (flatbuffers::integral_constant< bool, true >, flatbuffers::span< const T, length > src)
void CopyFromSpanImpl (flatbuffers::integral_constant< bool, false >, flatbuffers::span< const T, length > src)
Array ()
Protected Attributes
uint8_t data_ [length *sizeof(T)]
Detailed Description
template<typename T, uint16_t length>
class flatbuffers::Array< T, length >
Definition at line 451 of file flatbuffers.h.
Member Typedef Documentation
const_iterator
template<typename T , uint16_t length> typedef VectorIterator<T, return_type> flatbuffers::Array< T, length >::const_iterator
Definition at line 461 of file flatbuffers.h.
const_reverse_iterator
template<typename T , uint16_t length> typedef VectorReverseIterator<const_iterator> flatbuffers::Array< T, length >::const_reverse_iterator
Definition at line 462 of file flatbuffers.h.
return_type
template<typename T , uint16_t length> typedef IndirectHelper<IndirectHelperType>::return_type flatbuffers::Array< T, length >::return_type
Definition at line 460 of file flatbuffers.h.
size_type
template<typename T , uint16_t length> typedef uint16_t flatbuffers::Array< T, length >::size_type
Definition at line 459 of file flatbuffers.h.
Constructor & Destructor Documentation
Array()
template<typename T , uint16_t length> flatbuffers::Array< T, length >::Array () protected
Member Function Documentation
begin()
template<typename T , uint16_t length> const_iterator flatbuffers::Array< T, length >::begin () const inline
Definition at line 479 of file flatbuffers.h.
{ return const_iterator(Data(), 0); }
References flatbuffers::Array< T, length >::Data().
Referenced by flatbuffers::Array< T, length >::cbegin(), and flatbuffers::Array< T, length >::rend().
cbegin()
template<typename T , uint16_t length> const_iterator flatbuffers::Array< T, length >::cbegin () const inline
Definition at line 485 of file flatbuffers.h.
{ return begin(); }
References flatbuffers::Array< T, length >::begin().
cend()
template<typename T , uint16_t length> const_iterator flatbuffers::Array< T, length >::cend () const inline
Definition at line 486 of file flatbuffers.h.
{ return end(); }
References flatbuffers::Array< T, length >::end().
CopyFromSpan()
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::CopyFromSpan (flatbuffers::span< const T, length > src) inline
Definition at line 517 of file flatbuffers.h.
  {
    const auto p1 = reinterpret_cast<const uint8_t *>(src.data());
    const auto p2 = Data();
    FLATBUFFERS_ASSERT(!(p1 >= p2 && p1 < (p2 + length)) && !(p2 >= p1 && p2 < (p1 + length)));
    (void)p1;
    (void)p2;
    CopyFromSpanImpl(flatbuffers::integral_constant < bool,
                     !scalar_tag::value || sizeof(T) == 1 || FLATBUFFERS_LITTLEENDIAN > (), src);
  }
References flatbuffers::Array< T, length >::CopyFromSpanImpl(), flatbuffers::Array< T, length >::Data(), and FLATBUFFERS_ASSERT.
CopyFromSpanImpl() [1/2]
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::CopyFromSpanImpl (flatbuffers::integral_constant< bool, false > , flatbuffers::span< const T, length > src) inline protected
Definition at line 551 of file flatbuffers.h.
  {
    for (size_type k = 0; k < length; k++)
    {
      Mutate(k, src[k]);
    }
  }
References flatbuffers::Array< T, length >::Mutate().
CopyFromSpanImpl() [2/2]
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::CopyFromSpanImpl (flatbuffers::integral_constant< bool, true > , flatbuffers::span< const T, length > src) inline protected
Definition at line 541 of file flatbuffers.h.
  {
    // Use std::memcpy() instead of std::copy() to avoid preformance degradation
    // due to aliasing if T is char or unsigned char.
    // The size is known at compile time, so memcpy would be inlined.
    std::memcpy(data(), src.data(), length * sizeof(T));
  }
References flatbuffers::Array< T, length >::data().
Referenced by flatbuffers::Array< T, length >::CopyFromSpan().
crbegin()
template<typename T , uint16_t length> const_reverse_iterator flatbuffers::Array< T, length >::crbegin () const inline
Definition at line 488 of file flatbuffers.h.
{ return rbegin(); }
References flatbuffers::Array< T, length >::rbegin().
crend()
template<typename T , uint16_t length> const_reverse_iterator flatbuffers::Array< T, length >::crend () const inline
Definition at line 489 of file flatbuffers.h.
{ return rend(); }
References flatbuffers::Array< T, length >::rend().
Data() [1/2]
template<typename T , uint16_t length> uint8_t * flatbuffers::Array< T, length >::Data () inline
Definition at line 509 of file flatbuffers.h.
{ return data_; }
References flatbuffers::Array< T, length >::data_.
data() [1/2]
template<typename T , uint16_t length> T * flatbuffers::Array< T, length >::data () inline
Definition at line 513 of file flatbuffers.h.
{ return reinterpret_cast<T *>(Data()); }
References flatbuffers::Array< T, length >::Data().
Data() [2/2]
template<typename T , uint16_t length> const uint8_t * flatbuffers::Array< T, length >::Data () const inline
Definition at line 507 of file flatbuffers.h.
{ return data_; }
References flatbuffers::Array< T, length >::data_.
Referenced by flatbuffers::Array< T, length >::begin(), flatbuffers::Array< T, length >::CopyFromSpan(), flatbuffers::Array< T, length >::data(), flatbuffers::Array< T, length >::data(), flatbuffers::Array< T, length >::end(), and flatbuffers::Array< T, length >::Get().
data() [2/2]
template<typename T , uint16_t length> const T * flatbuffers::Array< T, length >::data () const inline
Definition at line 512 of file flatbuffers.h.
{ return reinterpret_cast<const T *>(Data()); }
References flatbuffers::Array< T, length >::Data().
Referenced by flatbuffers::Array< T, length >::CopyFromSpanImpl(), flatbuffers::Array< T, length >::GetMutablePointer(), and flatbuffers::Array< T, length >::MutateImpl().
end()
template<typename T , uint16_t length> const_iterator flatbuffers::Array< T, length >::end () const inline
Definition at line 480 of file flatbuffers.h.
{ return const_iterator(Data(), size()); }
References flatbuffers::Array< T, length >::Data(), and flatbuffers::Array< T, length >::size().
Referenced by flatbuffers::Array< T, length >::cend(), and flatbuffers::Array< T, length >::rbegin().
Get()
template<typename T , uint16_t length> return_type flatbuffers::Array< T, length >::Get (uoffset_t i) const inline
Definition at line 466 of file flatbuffers.h.
  {
    FLATBUFFERS_ASSERT(i < size());
    return IndirectHelper<IndirectHelperType>::Read(Data(), i);
  }
References flatbuffers::Array< T, length >::Data(), FLATBUFFERS_ASSERT, flatbuffers::IndirectHelper< T >::Read(), and flatbuffers::Array< T, length >::size().
Referenced by flatbuffers::Array< T, length >::GetEnum(), and flatbuffers::Array< T, length >::operator[]().
GetEnum()
template<typename T , uint16_t length> template<typename E > E flatbuffers::Array< T, length >::GetEnum (uoffset_t i) const inline
Definition at line 477 of file flatbuffers.h.
{ return static_cast<E>(Get(i)); }
References flatbuffers::Array< T, length >::Get().
GetMutablePointer()
template<typename T , uint16_t length> flatbuffers::conditional< scalar_tag::value, void, T * >::type flatbuffers::Array< T, length >::GetMutablePointer (uoffset_t i) const inline
Definition at line 497 of file flatbuffers.h.
  {
    FLATBUFFERS_ASSERT(i < size());
    return const_cast<T *>(&data()[i]);
  }
References flatbuffers::Array< T, length >::data(), FLATBUFFERS_ASSERT, and flatbuffers::Array< T, length >::size().
Referenced by flatbuffers::Array< T, length >::MutateImpl().
Mutate()
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::Mutate (uoffset_t i, const T & val) inline
Definition at line 504 of file flatbuffers.h.
{ MutateImpl(scalar_tag(), i, val); }
References flatbuffers::Array< T, length >::MutateImpl().
Referenced by flatbuffers::Array< T, length >::CopyFromSpanImpl().
MutateImpl() [1/2]
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::MutateImpl (flatbuffers::integral_constant< bool, false > , uoffset_t i, const T & val) inline protected
Definition at line 536 of file flatbuffers.h.
  {
    *(GetMutablePointer(i)) = val;
  }
References flatbuffers::Array< T, length >::GetMutablePointer().
MutateImpl() [2/2]
template<typename T , uint16_t length> void flatbuffers::Array< T, length >::MutateImpl (flatbuffers::integral_constant< bool, true > , uoffset_t i, const T & val) inline protected
Definition at line 530 of file flatbuffers.h.
  {
    FLATBUFFERS_ASSERT(i < size());
    WriteScalar(data() + i, val);
  }
References flatbuffers::Array< T, length >::data(), FLATBUFFERS_ASSERT, and flatbuffers::Array< T, length >::size().
Referenced by flatbuffers::Array< T, length >::Mutate().
operator[]()
template<typename T , uint16_t length> return_type flatbuffers::Array< T, length >::operator[] (uoffset_t i) const inline
Definition at line 472 of file flatbuffers.h.
{ return Get(i); }
References flatbuffers::Array< T, length >::Get().
rbegin()
template<typename T , uint16_t length> const_reverse_iterator flatbuffers::Array< T, length >::rbegin () const inline
Definition at line 482 of file flatbuffers.h.
{ return const_reverse_iterator(end()); }
References flatbuffers::Array< T, length >::end().
Referenced by flatbuffers::Array< T, length >::crbegin().
rend()
template<typename T , uint16_t length> const_reverse_iterator flatbuffers::Array< T, length >::rend () const inline
Definition at line 483 of file flatbuffers.h.
{ return const_reverse_iterator(begin()); }
References flatbuffers::Array< T, length >::begin().
Referenced by flatbuffers::Array< T, length >::crend().
size()
template<typename T , uint16_t length> FLATBUFFERS_CONSTEXPR uint16_t flatbuffers::Array< T, length >::size () const inline
Definition at line 464 of file flatbuffers.h.
{ return length; }
Referenced by flatbuffers::Array< T, length >::end(), flatbuffers::Array< T, length >::Get(), flatbuffers::Array< T, length >::GetMutablePointer(), and flatbuffers::Array< T, length >::MutateImpl().
Field Documentation
data_
template<typename T , uint16_t length> uint8_t flatbuffers::Array< T, length >::data_[length *sizeof(T)] protected
Definition at line 571 of file flatbuffers.h.
Referenced by flatbuffers::Array< T, length >::Data(), flatbuffers::Array< T, length >::Data(), and flatbuffers::Array< Offset< T >, length >::Data().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flatbuffers.h