ONE - On-device Neural Engine: nnfw::misc::tensor::NonIncreasingStride Class Reference
nnfw::misc::tensor::NonIncreasingStride Class Reference
Class to represent strides where stride[N-1] >= stride[N] holds for all N < rank.
#include <NonIncreasingStride.h>
Public Member Functions
void init (const Shape &shape)
Initialize the stride data using Shape.
uint32_t at (uint32_t axis) const
Get an stride value for specific axis.
uint32_t offset (const Index &index) const
Get the 1-D offset of specified index for n-D tensor.
Detailed Description
Class to represent strides where stride[N-1] >= stride[N] holds for all N < rank.
Definition at line 40 of file NonIncreasingStride.h.
Member Function Documentation
at()
uint32_t nnfw::misc::tensor::NonIncreasingStride::at (uint32_t axis) const inline
Get an stride value for specific axis.
Parameters
[in] axis Axis of stride
Returns
The value of stride
Definition at line 70 of file NonIncreasingStride.h.
{ return _stride.at(axis); }
Referenced by nnfw::misc::tensor::Object< T >::Object().
init()
void nnfw::misc::tensor::NonIncreasingStride::init (const Shape & shape) inline
Initialize the stride data using Shape.
Parameters
[in] shape to build stride info
Returns
N/A
Definition at line 48 of file NonIncreasingStride.h.
  {
    _stride.resize(shape.rank());
    // Scalar
    if (shape.rank() == 0)
      return;
    _stride.at(shape.rank() - 1) = 1;
    for (uint32_t axis = shape.rank() - 1; axis > 0; --axis)
    {
      _stride.at(axis - 1) = _stride.at(axis) * shape.dim(axis);
    }
  }
References nnfw::misc::tensor::Shape::dim(), and nnfw::misc::tensor::Shape::rank().
Referenced by nnfw::misc::tensor::Object< T >::Object(), and nnfw::tflite::TensorView< T >::TensorView().
offset()
uint32_t nnfw::misc::tensor::NonIncreasingStride::offset (const Index & index) const
Get the 1-D offset of specified index for n-D tensor.
Parameters
index Index object
Returns
1-D offset of index
Definition at line 28 of file NonIncreasingStride.cpp.
{
  const size_t rank = _stride.size();
  assert(index.rank() == rank);
  uint32_t offset = 0;
  for (size_t axis = 0; axis < rank; ++axis)
  {
    offset += _stride.at(axis) * index.at(axis);
  }
  return offset;
}
References offset().
Referenced by nnfw::misc::tensor::Object< T >::at(), nnfw::tflite::TensorView< T >::at(), nnfw::misc::tensor::Object< T >::Object(), and offset().
The documentation for this class was generated from the following files:
runtime/libs/misc/include/misc/tensor/NonIncreasingStride.h
runtime/libs/misc/src/tensor/NonIncreasingStride.cpp