ONE - On-device Neural Engine: luci::BuiltinOptionsExtractor Class Reference
luci::BuiltinOptionsExtractor Class Reference final
#include <CircleBuiltinTypesExtractor.h>
Public Member Functions
BuiltinOptionsExtractor (flatbuffers::FlatBufferBuilder &builder)
flatbuffers::Offset< void > visit (luci::CircleAbs *)
flatbuffers::Offset< void > visit (luci::CircleAdd *node)
flatbuffers::Offset< void > visit (luci::CircleAddN *)
flatbuffers::Offset< void > visit (luci::CircleArgMax *node)
flatbuffers::Offset< void > visit (luci::CircleArgMin *node)
flatbuffers::Offset< void > visit (luci::CircleAveragePool2D *node)
flatbuffers::Offset< void > visit (luci::CircleBatchMatMul *node)
flatbuffers::Offset< void > visit (luci::CircleBatchToSpaceND *)
flatbuffers::Offset< void > visit (luci::CircleBidirectionalSequenceLSTM *node)
flatbuffers::Offset< void > visit (luci::CircleBroadcastTo *)
flatbuffers::Offset< void > visit (luci::CircleCast *node)
flatbuffers::Offset< void > visit (luci::CircleCeil *)
flatbuffers::Offset< void > visit (luci::CircleConcatenation *node)
flatbuffers::Offset< void > visit (luci::CircleConv2D *node)
flatbuffers::Offset< void > visit (luci::CircleCos *)
flatbuffers::Offset< void > visit (luci::CircleCumSum *node)
flatbuffers::Offset< void > visit (luci::CircleCustom *)
flatbuffers::Offset< void > visit (luci::CircleDensify *)
flatbuffers::Offset< void > visit (luci::CircleDepthToSpace *node)
flatbuffers::Offset< void > visit (luci::CircleDepthwiseConv2D *node)
flatbuffers::Offset< void > visit (luci::CircleDequantize *)
flatbuffers::Offset< void > visit (luci::CircleDiv *node)
flatbuffers::Offset< void > visit (luci::CircleElu *)
flatbuffers::Offset< void > visit (luci::CircleEqual *)
flatbuffers::Offset< void > visit (luci::CircleExp *)
flatbuffers::Offset< void > visit (luci::CircleExpandDims *)
flatbuffers::Offset< void > visit (luci::CircleFakeQuant *node)
flatbuffers::Offset< void > visit (luci::CircleFill *)
flatbuffers::Offset< void > visit (luci::CircleFloor *)
flatbuffers::Offset< void > visit (luci::CircleFloorDiv *)
flatbuffers::Offset< void > visit (luci::CircleFloorMod *)
flatbuffers::Offset< void > visit (luci::CircleFullyConnected *node)
flatbuffers::Offset< void > visit (luci::CircleGather *node)
flatbuffers::Offset< void > visit (luci::CircleGatherNd *)
flatbuffers::Offset< void > visit (luci::CircleGelu *node)
flatbuffers::Offset< void > visit (luci::CircleGreater *)
flatbuffers::Offset< void > visit (luci::CircleGreaterEqual *)
flatbuffers::Offset< void > visit (luci::CircleHardSwish *)
flatbuffers::Offset< void > visit (luci::CircleIf *node)
flatbuffers::Offset< void > visit (luci::CircleL2Normalize *node)
flatbuffers::Offset< void > visit (luci::CircleL2Pool2D *node)
flatbuffers::Offset< void > visit (luci::CircleLeakyRelu *node)
flatbuffers::Offset< void > visit (luci::CircleLess *)
flatbuffers::Offset< void > visit (luci::CircleLessEqual *)
flatbuffers::Offset< void > visit (luci::CircleLocalResponseNormalization *node)
flatbuffers::Offset< void > visit (luci::CircleLog *)
flatbuffers::Offset< void > visit (luci::CircleLogicalAnd *)
flatbuffers::Offset< void > visit (luci::CircleLogicalNot *)
flatbuffers::Offset< void > visit (luci::CircleLogicalOr *)
flatbuffers::Offset< void > visit (luci::CircleLogistic *)
flatbuffers::Offset< void > visit (luci::CircleLogSoftmax *)
flatbuffers::Offset< void > visit (luci::CircleMatrixDiag *)
flatbuffers::Offset< void > visit (luci::CircleMatrixSetDiag *)
flatbuffers::Offset< void > visit (luci::CircleMaximum *)
flatbuffers::Offset< void > visit (luci::CircleMaxPool2D *node)
flatbuffers::Offset< void > visit (luci::CircleMean *node)
flatbuffers::Offset< void > visit (luci::CircleMinimum *)
flatbuffers::Offset< void > visit (luci::CircleMirrorPad *node)
flatbuffers::Offset< void > visit (luci::CircleMul *node)
flatbuffers::Offset< void > visit (luci::CircleNeg *)
flatbuffers::Offset< void > visit (luci::CircleNonMaxSuppressionV4 *)
flatbuffers::Offset< void > visit (luci::CircleNonMaxSuppressionV5 *)
flatbuffers::Offset< void > visit (luci::CircleNotEqual *)
flatbuffers::Offset< void > visit (luci::CircleOneHot *node)
flatbuffers::Offset< void > visit (luci::CirclePack *node)
flatbuffers::Offset< void > visit (luci::CirclePad *)
flatbuffers::Offset< void > visit (luci::CirclePadV2 *)
flatbuffers::Offset< void > visit (luci::CirclePow *)
flatbuffers::Offset< void > visit (luci::CirclePRelu *)
flatbuffers::Offset< void > visit (luci::CircleQuantize *)
flatbuffers::Offset< void > visit (luci::CircleRange *)
flatbuffers::Offset< void > visit (luci::CircleRank *)
flatbuffers::Offset< void > visit (luci::CircleReduceAny *node)
flatbuffers::Offset< void > visit (luci::CircleReduceMax *node)
flatbuffers::Offset< void > visit (luci::CircleReduceMin *node)
flatbuffers::Offset< void > visit (luci::CircleReduceProd *node)
flatbuffers::Offset< void > visit (luci::CircleRelu *)
flatbuffers::Offset< void > visit (luci::CircleRelu6 *)
flatbuffers::Offset< void > visit (luci::CircleReluN1To1 *)
flatbuffers::Offset< void > visit (luci::CircleReshape *node)
flatbuffers::Offset< void > visit (luci::CircleResizeBilinear *node)
flatbuffers::Offset< void > visit (luci::CircleResizeNearestNeighbor *node)
flatbuffers::Offset< void > visit (luci::CircleReverseSequence *node)
flatbuffers::Offset< void > visit (luci::CircleReverseV2 *)
flatbuffers::Offset< void > visit (luci::CircleRound *)
flatbuffers::Offset< void > visit (luci::CircleRsqrt *)
flatbuffers::Offset< void > visit (luci::CircleScatterNd *)
flatbuffers::Offset< void > visit (luci::CircleSegmentSum *)
flatbuffers::Offset< void > visit (luci::CircleSelect *)
flatbuffers::Offset< void > visit (luci::CircleSelectV2 *)
flatbuffers::Offset< void > visit (luci::CircleShape *node)
flatbuffers::Offset< void > visit (luci::CircleSin *)
flatbuffers::Offset< void > visit (luci::CircleSlice *)
flatbuffers::Offset< void > visit (luci::CircleSoftmax *node)
flatbuffers::Offset< void > visit (luci::CircleSpaceToBatchND *)
flatbuffers::Offset< void > visit (luci::CircleSpaceToDepth *node)
flatbuffers::Offset< void > visit (luci::CircleSparseToDense *node)
flatbuffers::Offset< void > visit (luci::CircleSplit *node)
flatbuffers::Offset< void > visit (luci::CircleSplitV *node)
flatbuffers::Offset< void > visit (luci::CircleSqrt *)
flatbuffers::Offset< void > visit (luci::CircleSquare *)
flatbuffers::Offset< void > visit (luci::CircleSquaredDifference *)
flatbuffers::Offset< void > visit (luci::CircleSqueeze *node)
flatbuffers::Offset< void > visit (luci::CircleStridedSlice *node)
flatbuffers::Offset< void > visit (luci::CircleSub *node)
flatbuffers::Offset< void > visit (luci::CircleSum *node)
flatbuffers::Offset< void > visit (luci::CircleSVDF *node)
flatbuffers::Offset< void > visit (luci::CircleTanh *)
flatbuffers::Offset< void > visit (luci::CircleTile *)
flatbuffers::Offset< void > visit (luci::CircleTopKV2 *)
flatbuffers::Offset< void > visit (luci::CircleTranspose *)
flatbuffers::Offset< void > visit (luci::CircleTransposeConv *node)
flatbuffers::Offset< void > visit (luci::CircleUnidirectionalSequenceLSTM *node)
flatbuffers::Offset< void > visit (luci::CircleUnique *node)
flatbuffers::Offset< void > visit (luci::CircleUnpack *node)
flatbuffers::Offset< void > visit (luci::CircleWhere *)
flatbuffers::Offset< void > visit (luci::CircleWhile *node)
flatbuffers::Offset< void > visit (luci::CircleZerosLike *)
flatbuffers::Offset< void > visit (luci::CircleBCQFullyConnected *node)
flatbuffers::Offset< void > visit (luci::CircleBCQGather *node)
flatbuffers::Offset< void > visit (luci::CircleGRU *node)
flatbuffers::Offset< void > visit (luci::CircleInstanceNorm *node)
Public Member Functions inherited from luci::CircleNodeMutableVisitor< flatbuffers::Offset< void > >
virtual ~CircleNodeMutableVisitor ()=default
virtual flatbuffers::Offset< void > visit (CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeMutableVisitorBase< T >
virtual ~CircleNodeMutableVisitorBase ()=default
Protected Attributes
flatbuffers::FlatBufferBuilder & _builder
Detailed Description
Definition at line 33 of file CircleBuiltinTypesExtractor.h.
Constructor & Destructor Documentation
BuiltinOptionsExtractor()
luci::BuiltinOptionsExtractor::BuiltinOptionsExtractor (flatbuffers::FlatBufferBuilder & builder) inline
Definition at line 37 of file CircleBuiltinTypesExtractor.h.
                                                                 : _builder{builder}
  {
    // DO NOTHING
  }
Member Function Documentation
visit() [1/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleAbs *) inline
Definition at line 43 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateAbsOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [2/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleAdd * node) inline
Definition at line 47 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateAddOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [3/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleAddN *) inline
Definition at line 52 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateAddNOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [4/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleArgMax * node) inline
Definition at line 56 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateArgMaxOptions(_builder, luci::to_circle_tensortype(node->output_type()))
      .Union();
  }
References _builder, luci::CircleArgMax::output_type(), luci::to_circle_tensortype(), and flatbuffers::Offset< T >::Union().
visit() [5/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleArgMin * node) inline
Definition at line 61 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateArgMinOptions(_builder, luci::to_circle_tensortype(node->output_type()))
      .Union();
  }
References _builder, luci::CircleArgMin::output_type(), luci::to_circle_tensortype(), and flatbuffers::Offset< T >::Union().
visit() [6/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleAveragePool2D * node) inline
Definition at line 66 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePool2DOptions(_builder, getOpPadding(node->padding()), node->stride()->w(),
                                       node->stride()->h(), node->filter()->w(),
                                       node->filter()->h(),
                                       to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleAveragePool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Filter::h(), luci::Stride::h(), luci::CircleAveragePool2D::padding(), luci::CircleAveragePool2D::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), luci::Filter::w(), and luci::Stride::w().
visit() [7/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBatchMatMul * node) inline
Definition at line 74 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateBatchMatMulOptions(_builder, node->adj_x(), node->adj_y()).Union();
  }
References _builder, luci::CircleBatchMatMul::adj_x(), luci::CircleBatchMatMul::adj_y(), and flatbuffers::Offset< T >::Union().
visit() [8/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBatchToSpaceND *) inline
Definition at line 78 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateBatchToSpaceNDOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [9/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBCQFullyConnected * node) inline
Definition at line 526 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateBCQFullyConnectedOptions(
             _builder, node->weights_hidden_size(),
             to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), and luci::CircleBCQFullyConnected::weights_hidden_size().
visit() [10/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBCQGather * node) inline
Definition at line 533 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateBCQGatherOptions(_builder, node->input_hidden_size(), node->axis())
      .Union();
  }
References _builder, luci::CircleBCQGather::axis(), luci::CircleBCQGather::input_hidden_size(), and flatbuffers::Offset< T >::Union().
visit() [11/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBidirectionalSequenceLSTM * node) inline
Definition at line 82 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateBidirectionalSequenceLSTMOptions(
             _builder, to_circle_actfunc(node->fusedActivationFunction()), node->cell_clip(),
             node->proj_clip(), node->merge_outputs(), node->time_major(),
             node->asymmetric_quantize_inputs())
      .Union();
  }
References _builder, luci::CircleBidirectionalSequenceLSTM::asymmetric_quantize_inputs(), luci::CircleBidirectionalSequenceLSTM::cell_clip(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleBidirectionalSequenceLSTM::merge_outputs(), luci::CircleBidirectionalSequenceLSTM::proj_clip(), luci::CircleBidirectionalSequenceLSTM::time_major(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [12/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleBroadcastTo *) inline
Definition at line 90 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [13/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleCast * node) inline
Definition at line 91 of file CircleBuiltinTypesExtractor.h.
  {
    if (node->out_data_type() == loco::DataType::Unknown)
      return _no_option;
    else
      return circle::CreateCastOptions(_builder, luci::to_circle_tensortype(node->in_data_type()),
                                       luci::to_circle_tensortype(node->out_data_type()))
        .Union();
  }
References _builder, luci::CircleCast::in_data_type(), luci::CircleCast::out_data_type(), luci::to_circle_tensortype(), and flatbuffers::Offset< T >::Union().
visit() [14/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleCeil *) inline
Definition at line 100 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [15/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleConcatenation * node) inline
Definition at line 101 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateConcatenationOptions(_builder, node->axis(),
                                              to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleConcatenation::axis(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [16/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleConv2D * node) inline
Definition at line 109 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateConv2DOptions(_builder, getOpPadding(node->padding()), node->stride()->w(),
                                       node->stride()->h(),
                                       to_circle_actfunc(node->fusedActivationFunction()),
                                       node->dilation()->w(), node->dilation()->h())
      .Union();
  }
References _builder, luci::CircleConv2D::dilation(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Dilation::h(), luci::Stride::h(), luci::CircleConv2D::padding(), luci::CircleConv2D::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), luci::Dilation::w(), and luci::Stride::w().
visit() [17/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleCos *) inline
Definition at line 117 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateCosOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [18/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleCumSum * node) inline
Definition at line 121 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateCumsumOptions(_builder, node->exclusive(), node->reverse()).Union();
  }
References _builder, luci::CircleCumSum::exclusive(), luci::CircleCumSum::reverse(), and flatbuffers::Offset< T >::Union().
visit() [19/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleCustom *) inline
Definition at line 125 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [20/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleDensify *) inline
Definition at line 126 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateDensifyOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [21/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleDepthToSpace * node) inline
Definition at line 130 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateDepthToSpaceOptions(_builder, node->block_size()).Union();
  }
References _builder, luci::CircleDepthToSpace::block_size(), and flatbuffers::Offset< T >::Union().
visit() [22/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleDepthwiseConv2D * node) inline
Definition at line 134 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateDepthwiseConv2DOptions(
             _builder, getOpPadding(node->padding()), node->stride()->w(), node->stride()->h(),
             node->depthMultiplier(), to_circle_actfunc(node->fusedActivationFunction()),
             node->dilation()->w(), node->dilation()->h())
      .Union();
  }
References _builder, luci::CircleDepthwiseConv2D::depthMultiplier(), luci::CircleDepthwiseConv2D::dilation(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Dilation::h(), luci::Stride::h(), luci::CircleDepthwiseConv2D::padding(), luci::CircleDepthwiseConv2D::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), luci::Dilation::w(), and luci::Stride::w().
visit() [23/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleDequantize *) inline
Definition at line 142 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [24/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleDiv * node) inline
Definition at line 143 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateDivOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [25/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleElu *) inline
Definition at line 148 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [26/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleEqual *) inline
Definition at line 149 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateEqualOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [27/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleExp *) inline
Definition at line 153 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateExpOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [28/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleExpandDims *) inline
Definition at line 157 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateExpandDimsOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [29/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFakeQuant * node) inline
Definition at line 161 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateFakeQuantOptions(_builder, node->min(), node->max(), node->num_bits(),
                                          node->narrow_range())
      .Union();
  }
References _builder, luci::CircleFakeQuant::max(), luci::CircleFakeQuant::min(), luci::CircleFakeQuant::narrow_range(), luci::CircleFakeQuant::num_bits(), and flatbuffers::Offset< T >::Union().
visit() [30/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFill *) inline
Definition at line 167 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateFillOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [31/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFloor *) inline
Definition at line 171 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [32/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFloorDiv *) inline
Definition at line 172 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateFloorDivOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [33/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFloorMod *) inline
Definition at line 176 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateFloorModOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [34/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleFullyConnected * node) inline
Definition at line 180 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateFullyConnectedOptions(
             _builder, to_circle_actfunc(node->fusedActivationFunction()),
             to_circle_weightsformat(node->weights_format()), node->keep_num_dims())
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleFullyConnected::keep_num_dims(), luci::to_circle_actfunc(), luci::to_circle_weightsformat(), flatbuffers::Offset< T >::Union(), and luci::CircleFullyConnected::weights_format().
visit() [35/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGather * node) inline
Definition at line 187 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGatherOptions(_builder, node->axis()).Union();
  }
References _builder, luci::CircleGather::axis(), and flatbuffers::Offset< T >::Union().
visit() [36/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGatherNd *) inline
Definition at line 191 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGatherNdOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [37/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGelu * node) inline
Definition at line 195 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGeluOptions(_builder, node->approximate()).Union();
  }
References _builder, luci::CircleGelu::approximate(), and flatbuffers::Offset< T >::Union().
visit() [38/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGreater *) inline
Definition at line 199 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGreaterOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [39/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGreaterEqual *) inline
Definition at line 203 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGreaterEqualOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [40/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleGRU * node) inline
Definition at line 538 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateGRUOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()),
                                    node->returnSequences(), node->timeMajor())
      .Union();
  }
References _builder, luci::CircleGRU::fusedActivationFunction(), luci::CircleGRU::returnSequences(), luci::CircleGRU::timeMajor(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [41/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleHardSwish *) inline
Definition at line 207 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [42/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleIf * node) inline
Definition at line 208 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateIfOptions(_builder, node->then_branch(), node->else_branch()).Union();
  }
References _builder, luci::CircleIf::else_branch(), luci::CircleIf::then_branch(), and flatbuffers::Offset< T >::Union().
visit() [43/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleInstanceNorm * node) inline
Definition at line 544 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateInstanceNormOptions(_builder, node->epsilon(),
                                             to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleInstanceNorm::epsilon(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [44/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleL2Normalize * node) inline
Definition at line 212 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateL2NormOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [45/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleL2Pool2D * node) inline
Definition at line 217 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePool2DOptions(_builder, getOpPadding(node->padding()), node->stride()->w(),
                                       node->stride()->h(), node->filter()->w(),
                                       node->filter()->h(),
                                       to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleL2Pool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Filter::h(), luci::Stride::h(), luci::CircleL2Pool2D::padding(), luci::CircleL2Pool2D::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), luci::Filter::w(), and luci::Stride::w().
visit() [46/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLeakyRelu * node) inline
Definition at line 225 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLeakyReluOptions(_builder, node->alpha()).Union();
  }
References _builder, luci::CircleLeakyRelu::alpha(), and flatbuffers::Offset< T >::Union().
visit() [47/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLess *) inline
Definition at line 229 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLessOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [48/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLessEqual *) inline
Definition at line 233 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLessEqualOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [49/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLocalResponseNormalization * node) inline
Definition at line 237 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLocalResponseNormalizationOptions(_builder, node->radius(), node->bias(),
                                                           node->alpha(), node->beta())
      .Union();
  }
References _builder, luci::CircleLocalResponseNormalization::alpha(), luci::CircleLocalResponseNormalization::beta(), luci::CircleLocalResponseNormalization::bias(), luci::CircleLocalResponseNormalization::radius(), and flatbuffers::Offset< T >::Union().
visit() [50/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLog *) inline
Definition at line 243 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [51/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLogicalAnd *) inline
Definition at line 244 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLogicalAndOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [52/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLogicalNot *) inline
Definition at line 248 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLogicalNotOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [53/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLogicalOr *) inline
Definition at line 252 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLogicalOrOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [54/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLogistic *) inline
Definition at line 256 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [55/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleLogSoftmax *) inline
Definition at line 257 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateLogSoftmaxOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [56/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMatrixDiag *) inline
Definition at line 261 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMatrixDiagOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [57/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMatrixSetDiag *) inline
Definition at line 265 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMatrixSetDiagOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [58/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMaximum *) inline
Definition at line 269 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMaximumMinimumOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [59/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMaxPool2D * node) inline
Definition at line 273 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePool2DOptions(_builder, getOpPadding(node->padding()), node->stride()->w(),
                                       node->stride()->h(), node->filter()->w(),
                                       node->filter()->h(),
                                       to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleMaxPool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Filter::h(), luci::Stride::h(), luci::CircleMaxPool2D::padding(), luci::CircleMaxPool2D::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), luci::Filter::w(), and luci::Stride::w().
visit() [60/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMean * node) inline
Definition at line 281 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleMean::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [61/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMinimum *) inline
Definition at line 285 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMaximumMinimumOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [62/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMirrorPad * node) inline
Definition at line 289 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMirrorPadOptions(_builder, to_circle_mirrorpadmode(node->mode())).Union();
  }
References _builder, luci::CircleMirrorPad::mode(), luci::to_circle_mirrorpadmode(), and flatbuffers::Offset< T >::Union().
visit() [63/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleMul * node) inline
Definition at line 293 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateMulOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [64/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleNeg *) inline
Definition at line 298 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateNegOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [65/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleNonMaxSuppressionV4 *) inline
Definition at line 302 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateNonMaxSuppressionV4Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [66/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleNonMaxSuppressionV5 *) inline
Definition at line 306 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateNonMaxSuppressionV5Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [67/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleNotEqual *) inline
Definition at line 310 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateNotEqualOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [68/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleOneHot * node) inline
Definition at line 314 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateOneHotOptions(_builder, node->axis()).Union();
  }
References _builder, luci::CircleOneHot::axis(), and flatbuffers::Offset< T >::Union().
visit() [69/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CirclePack * node) inline
Definition at line 318 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePackOptions(_builder, node->values_count(), node->axis()).Union();
  }
References _builder, luci::CirclePack::axis(), flatbuffers::Offset< T >::Union(), and luci::CirclePack::values_count().
visit() [70/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CirclePad *) inline
Definition at line 322 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePadOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [71/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CirclePadV2 *) inline
Definition at line 326 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePadV2Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [72/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CirclePow *) inline
Definition at line 330 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreatePowOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [73/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CirclePRelu *) inline
Definition at line 334 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [74/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleQuantize *) inline
Definition at line 335 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [75/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRange *) inline
Definition at line 336 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateRangeOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [76/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRank *) inline
Definition at line 340 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateRankOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [77/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReduceAny * node) inline
Definition at line 344 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleReduceAny::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [78/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReduceMax * node) inline
Definition at line 348 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleReduceMax::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [79/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReduceMin * node) inline
Definition at line 352 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleReduceMin::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [80/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReduceProd * node) inline
Definition at line 356 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleReduceProd::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [81/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRelu *) inline
Definition at line 360 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [82/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRelu6 *) inline
Definition at line 361 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [83/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReluN1To1 *) inline
Definition at line 362 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [84/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReshape * node) inline
Definition at line 363 of file CircleBuiltinTypesExtractor.h.
  {
    auto new_shape = _builder.CreateVector<int32_t>(
      node->newShape()->rank(), [node](size_t i) { return node->newShape()->dim(i); });
    return circle::CreateReshapeOptions(_builder, new_shape).Union();
  }
References _builder, flatbuffers::FlatBufferBuilder::CreateVector(), luci::CircleReshape::Shape::dim(), luci::CircleReshape::newShape(), and luci::CircleReshape::Shape::rank().
visit() [85/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleResizeBilinear * node) inline
Definition at line 369 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateResizeBilinearOptions(_builder, node->align_corners(),
                                               node->half_pixel_centers())
      .Union();
  }
References _builder, luci::CircleResizeBilinear::align_corners(), luci::CircleResizeBilinear::half_pixel_centers(), and flatbuffers::Offset< T >::Union().
visit() [86/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleResizeNearestNeighbor * node) inline
Definition at line 375 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateResizeNearestNeighborOptions(_builder, node->align_corners()).Union();
  }
References _builder, luci::CircleResizeNearestNeighbor::align_corners(), and flatbuffers::Offset< T >::Union().
visit() [87/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReverseSequence * node) inline
Definition at line 379 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReverseSequenceOptions(_builder, node->seq_axis(), node->batch_axis())
      .Union();
  }
References _builder, luci::CircleReverseSequence::batch_axis(), luci::CircleReverseSequence::seq_axis(), and flatbuffers::Offset< T >::Union().
visit() [88/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleReverseV2 *) inline
Definition at line 384 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReverseV2Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [89/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRound *) inline
Definition at line 388 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [90/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleRsqrt *) inline
Definition at line 389 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [91/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleScatterNd *) inline
Definition at line 390 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateScatterNdOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [92/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSegmentSum *) inline
Definition at line 394 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSegmentSumOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [93/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSelect *) inline
Definition at line 398 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSelectOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [94/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSelectV2 *) inline
Definition at line 402 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSelectV2Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [95/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleShape * node) inline
Definition at line 406 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateShapeOptions(_builder, luci::to_circle_tensortype(node->out_type()))
      .Union();
  }
References _builder, luci::CircleShape::out_type(), luci::to_circle_tensortype(), and flatbuffers::Offset< T >::Union().
visit() [96/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSin *) inline
Definition at line 411 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [97/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSlice *) inline
Definition at line 412 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSliceOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [98/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSoftmax * node) inline
Definition at line 416 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSoftmaxOptions(_builder, node->beta()).Union();
  }
References _builder, luci::CircleSoftmax::beta(), and flatbuffers::Offset< T >::Union().
visit() [99/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSpaceToBatchND *) inline
Definition at line 420 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSpaceToBatchNDOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [100/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSpaceToDepth * node) inline
Definition at line 424 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSpaceToDepthOptions(_builder, node->block_size()).Union();
  }
References _builder, luci::CircleSpaceToDepth::block_size(), and flatbuffers::Offset< T >::Union().
visit() [101/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSparseToDense * node) inline
Definition at line 428 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSparseToDenseOptions(_builder, node->validate_indices()).Union();
  }
References _builder, flatbuffers::Offset< T >::Union(), and luci::CircleSparseToDense::validate_indices().
visit() [102/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSplit * node) inline
Definition at line 432 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSplitOptions(_builder, node->num_split()).Union();
  }
References _builder, luci::CircleSplit::num_split(), and flatbuffers::Offset< T >::Union().
visit() [103/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSplitV * node) inline
Definition at line 436 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSplitVOptions(_builder, node->num_split()).Union();
  }
References _builder, luci::CircleSplitV::num_split(), and flatbuffers::Offset< T >::Union().
visit() [104/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSqrt *) inline
Definition at line 440 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [105/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSquare *) inline
Definition at line 441 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSquareOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [106/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSquaredDifference *) inline
Definition at line 445 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSquaredDifferenceOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [107/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSqueeze * node) inline
Definition at line 449 of file CircleBuiltinTypesExtractor.h.
  {
    auto squeeze_dims = _builder.CreateVector<int32_t>(node->squeeze_dims());
    return circle::CreateSqueezeOptions(_builder, squeeze_dims).Union();
  }
References _builder, flatbuffers::FlatBufferBuilder::CreateVector(), and luci::CircleSqueeze::squeeze_dims().
visit() [108/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleStridedSlice * node) inline
Definition at line 454 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateStridedSliceOptions(_builder, node->begin_mask(), node->end_mask(),
                                             node->ellipsis_mask(), node->new_axis_mask(),
                                             node->shrink_axis_mask())
      .Union();
  }
References _builder, luci::CircleStridedSlice::begin_mask(), luci::CircleStridedSlice::ellipsis_mask(), luci::CircleStridedSlice::end_mask(), luci::CircleStridedSlice::new_axis_mask(), luci::CircleStridedSlice::shrink_axis_mask(), and flatbuffers::Offset< T >::Union().
visit() [109/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSub * node) inline
Definition at line 461 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSubOptions(_builder, to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [110/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSum * node) inline
Definition at line 466 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateReducerOptions(_builder, node->keep_dims()).Union();
  }
References _builder, luci::CircleSum::keep_dims(), and flatbuffers::Offset< T >::Union().
visit() [111/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleSVDF * node) inline
Definition at line 470 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateSVDFOptions(_builder, node->svdf_rank(),
                                     to_circle_actfunc(node->fusedActivationFunction()),
                                     node->asymmetric_quantize_inputs())
      .Union();
  }
References _builder, luci::CircleSVDF::asymmetric_quantize_inputs(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleSVDF::svdf_rank(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [112/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleTanh *) inline
Definition at line 477 of file CircleBuiltinTypesExtractor.h.
{ return _no_option; }
visit() [113/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleTile *) inline
Definition at line 478 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateTileOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [114/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleTopKV2 *) inline
Definition at line 482 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateTopKV2Options(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [115/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleTranspose *) inline
Definition at line 486 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateTransposeOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [116/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleTransposeConv * node) inline
Definition at line 490 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateTransposeConvOptions(_builder, getOpPadding(node->padding()),
                                              node->stride()->w(), node->stride()->h(),
                                              to_circle_actfunc(node->fusedActivationFunction()))
      .Union();
  }
References _builder, luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::getOpPadding(), luci::Stride::h(), luci::CircleTransposeConv::padding(), luci::CircleTransposeConv::stride(), luci::to_circle_actfunc(), flatbuffers::Offset< T >::Union(), and luci::Stride::w().
visit() [117/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleUnidirectionalSequenceLSTM * node) inline
Definition at line 497 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateUnidirectionalSequenceLSTMOptions(
             _builder, to_circle_actfunc(node->fusedActivationFunction()), node->cell_clip(),
             node->proj_clip(), node->time_major(), node->asymmetric_quantize_inputs())
      .Union();
  }
References _builder, luci::CircleUnidirectionalSequenceLSTM::asymmetric_quantize_inputs(), luci::CircleUnidirectionalSequenceLSTM::cell_clip(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleUnidirectionalSequenceLSTM::proj_clip(), luci::CircleUnidirectionalSequenceLSTM::time_major(), luci::to_circle_actfunc(), and flatbuffers::Offset< T >::Union().
visit() [118/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleUnique * node) inline
Definition at line 504 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateUniqueOptions(_builder, luci::to_circle_tensortype(node->idx_out_type()))
      .Union();
  }
References _builder, luci::CircleUnique::idx_out_type(), luci::to_circle_tensortype(), and flatbuffers::Offset< T >::Union().
visit() [119/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleUnpack * node) inline
Definition at line 509 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateUnpackOptions(_builder, node->num(), node->axis()).Union();
  }
References _builder, luci::CircleUnpack::axis(), luci::CircleUnpack::num(), and flatbuffers::Offset< T >::Union().
visit() [120/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleWhere *) inline
Definition at line 513 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateWhereOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
visit() [121/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleWhile * node) inline
Definition at line 517 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateWhileOptions(_builder, node->cond_branch(), node->body_branch()).Union();
  }
References _builder, luci::CircleWhile::body_branch(), luci::CircleWhile::cond_branch(), and flatbuffers::Offset< T >::Union().
visit() [122/122]
flatbuffers::Offset< void > luci::BuiltinOptionsExtractor::visit (luci::CircleZerosLike *) inline
Definition at line 521 of file CircleBuiltinTypesExtractor.h.
  {
    return circle::CreateZerosLikeOptions(_builder).Union();
  }
References _builder, and flatbuffers::Offset< T >::Union().
Field Documentation
_builder
flatbuffers::FlatBufferBuilder& luci::BuiltinOptionsExtractor::_builder protected
Definition at line 552 of file CircleBuiltinTypesExtractor.h.
Referenced by visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), visit(), and visit().
The documentation for this class was generated from the following file:
compiler/luci/export/src/CircleBuiltinTypesExtractor.h