ONE - On-device Neural Engine: locoex::COpDialect Class Reference
locoex::COpDialect Class Reference final
A singleton for locoex custom op Dialect.
#include <COpDialect.h>
Public Member Functions
COpDialect (const Dialect &)=delete
COpDialect (Dialect &&)=delete
Public Member Functions inherited from loco::Dialect
virtual ~Dialect ()=default
template<typename ConcreteService >
ConcreteService * service (void) const
Static Public Member Functions
static loco::Dialect * get (void)
Additional Inherited Members
Protected Member Functions inherited from loco::Dialect
template<typename ConcreteService >
void service (std::unique_ptr< ConcreteService > &&s)
Detailed Description
A singleton for locoex custom op Dialect.
Definition at line 28 of file COpDialect.h.
Constructor & Destructor Documentation
COpDialect() [1/2]
locoex::COpDialect::COpDialect (const Dialect &) delete
COpDialect() [2/2]
locoex::COpDialect::COpDialect (Dialect &&) delete
Member Function Documentation
get()
loco::Dialect * locoex::COpDialect::get (void) static
Definition at line 22 of file COpDialect.cpp.
{
  static COpDialect d;
  return &d;
}
Referenced by locoex::COpNodeSummaryBuilder::build(), locoex::COpNode::dialect(), locoex::COpTypeInferenceRule::infer(), locoex::COpShapeInferenceRule::infer(), locoex::COpShapeInferenceRule::recognize(), locoex::COpTypeInferenceRule::recognize(), exo::ShapeInferencePass::run(), exo::TypeInferencePass::run(), moco::tf::ShapeInferencePass::run(), and moco::tf::TypeInferencePass::run().
The documentation for this class was generated from the following files:
compiler/locoex-customop/include/locoex/COpDialect.h
compiler/locoex-customop/src/COpDialect.cpp