ONE - On-device Neural Engine: luci_interpreter::kernels::Gather Class Reference
luci_interpreter::kernels::Gather Class Reference
#include <Gather.h>
Public Member Functions
Gather (const Tensor *params, const Tensor *indices, Tensor *output, const GatherParams &gparams)
const Tensor * params () const
const Tensor * indices () const
Tensor * output () const
void configure () override
void execute () const override
Gather (const Tensor *params, const Tensor *indices, Tensor *output, const GatherParams &gparams)
const Tensor * params () const
const Tensor * indices () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< GatherParams >
const GatherParams & params () const
const GatherParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< GatherParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const GatherParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const GatherParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< GatherParams >
const GatherParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Gather.h.
Constructor & Destructor Documentation
Gather() [1/2]
luci_interpreter::kernels::Gather::Gather (const Tensor * params, const Tensor * indices, Tensor * output, const GatherParams & gparams)
Definition at line 31 of file Gather.cpp.
  : KernelWithParams<GatherParams>({params, indices}, {output}, gparams)
{
}
References indices(), and params().
Gather() [2/2]
luci_interpreter::kernels::Gather::Gather (const Tensor * params, const Tensor * indices, Tensor * output, const GatherParams & gparams)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Gather::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file Gather.cpp.
{
  if (params()->element_type() == DataType::FLOAT32)
  {
    LUCI_INTERPRETER_CHECK(output()->element_type() == DataType::FLOAT32);
  }
  else
  {
    throw std::runtime_error("Unsupported type.");
  }
  LUCI_INTERPRETER_CHECK(indices()->element_type() == DataType::S32 ||
                         indices()->element_type() == DataType::S64);
  // refer tensorflow/lite/kernels/gather.cc
  const Shape &params_shape = params()->shape();
  const Shape &indices_shape = indices()->shape();
  int axis = _params.axis;
  if (axis < 0)
  {
    axis += params_shape.num_dims();
  }
  LUCI_INTERPRETER_CHECK(0 <= axis && axis < params_shape.num_dims());
  int batch_dims = _params.batch_dims;
  // batch_dims should be in range: [-rank(indices), rank(indices)].
  // Negative batch_dims is added with rank of positions.
  if (batch_dims < 0)
  {
    batch_dims += indices_shape.num_dims();
  }
  LUCI_INTERPRETER_CHECK(batch_dims <= axis);
  LUCI_INTERPRETER_CHECK(0 <= batch_dims && batch_dims < params_shape.num_dims());
  LUCI_INTERPRETER_CHECK(batch_dims <= indices_shape.num_dims());
  for (int i = 0; i < batch_dims; ++i)
  {
    LUCI_INTERPRETER_CHECK(params_shape.dim(i) == indices_shape.dim(i));
  }
  const int num_dimensions = params_shape.num_dims() + indices_shape.num_dims() - 1 - batch_dims;
  Shape output_shape(num_dimensions);
  int output_index = 0;
  for (int i = 0; i < axis; ++i)
  {
    output_shape.dim(output_index++) = params_shape.dim(i);
  }
  for (int i = batch_dims; i < indices_shape.num_dims(); ++i)
  {
    output_shape.dim(output_index++) = indices_shape.dim(i);
  }
  for (int i = axis + 1; i < params_shape.num_dims(); ++i)
  {
    output_shape.dim(output_index++) = params_shape.dim(i);
  }
  output()->resize(output_shape);
}
References luci_interpreter::KernelWithParams< GatherParams >::_params, luci_interpreter::GatherParams::axis, luci_interpreter::GatherParams::batch_dims, luci_interpreter::Shape::dim(), indices(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), params(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Gather::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Gather::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 97 of file Gather.cpp.
{
  switch (params()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References params().
execute() [2/2]
void luci_interpreter::kernels::Gather::execute () const override virtual
Implements luci_interpreter::Kernel.
indices() [1/2]
const Tensor * luci_interpreter::kernels::Gather::indices () const inline
Definition at line 34 of file Gather.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Gather().
indices() [2/2]
const Tensor * luci_interpreter::kernels::Gather::indices () const inline
Definition at line 34 of file Gather.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Gather::output () const inline
Definition at line 35 of file Gather.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Gather::output () const inline
Definition at line 35 of file Gather.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
params() [1/2]
const Tensor * luci_interpreter::kernels::Gather::params () const inline
Definition at line 33 of file Gather.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Gather().
params() [2/2]
const Tensor * luci_interpreter::kernels::Gather::params () const inline
Definition at line 33 of file Gather.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Gather.h
onert-micro/luci-interpreter/src/kernels/Gather.h
compiler/luci-interpreter/src/kernels/Gather.cpp
onert-micro/luci-interpreter/src/kernels/Gather.cpp