ONE - On-device Neural Engine: loco::Graph Class Reference
loco::Graph Class Reference final
A neural network graph.
#include <Graph.h>
Data Structures
struct InputContext
GraphInput Pool.
struct OutputContext
GraphOutput Pool.
struct SimpleFactoryObjectPool
Object Pool with Simple Factory Method.
Public Types
using NodeContext = NodePool
Node Pool.
Public Member Functions
Graph ()
Graph (const Graph &)=delete
Graph (Graph &&)=delete
~Graph ()=default
NodeContext * nodes (void)
const NodeContext * nodes (void) const
InputContext * inputs (void)
const InputContext * inputs (void) const
OutputContext * outputs (void)
const OutputContext * outputs (void) const
Public Member Functions inherited from loco::NamedEntity
const std::string & name (void) const
void name (const std::string &name)
Detailed Description
A neural network graph.
Definition at line 160 of file Graph.h.
Member Typedef Documentation
NodeContext
using loco::Graph::NodeContext = NodePool
Node Pool.
This alias confines the impact of changes to loco internals.
TODO Remove this alias
Definition at line 170 of file Graph.h.
Constructor & Destructor Documentation
Graph() [1/3]
loco::Graph::Graph () inline
Definition at line 205 of file Graph.h.
  {
    // Associate "NodeContext" and the current "Graph"
    _node_ctx.graph(this);
  }
Graph() [2/3]
loco::Graph::Graph (const Graph &) delete
Graph() [3/3]
loco::Graph::Graph (Graph &&) delete
~Graph()
loco::Graph::~Graph () default
Member Function Documentation
inputs() [1/2]
InputContext * loco::Graph::inputs (void) inline
Definition at line 220 of file Graph.h.
{ return &_input_ctx; }
Referenced by luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), loco::Pull::dtype(), validate_onnx2circle.OnnxRunner::feed_random_inputs(), loco::Pull::index(), locomotiv::Session::input_size(), and InputLayer::operator()().
inputs() [2/2]
const InputContext * loco::Graph::inputs (void) const inline
Definition at line 221 of file Graph.h.
{ return &_input_ctx; }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
nodes() [1/2]
NodeContext * loco::Graph::nodes (void) inline
Definition at line 218 of file Graph.h.
{ return &_node_ctx; }
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), exo::TensorConcatConverter::convert(), luci_interpreter::GraphLoader::loadTensors(), InputLayer::operator()(), OutputLayer::operator()(), ReLULayer::operator()(), ConstGenLayer::operator()(), FeatureEncodeLayer::operator()(), FeatureDecodeLayer::operator()(), FilterEncodeLayer::operator()(), DepthwiseFilterEncodeLayer::operator()(), DepthwiseConv2DLayer::operator()(), TransposedConv2DLayer::operator()(), FixedReshapeLayer::operator()(), TensorBroadcastLayer::operator()(), luci::FuseBCQPass::run(), locoex::set_new_shape(), luci::CloneNode::visit(), and locomotiv::Session::~Session().
nodes() [2/2]
const NodeContext * loco::Graph::nodes (void) const inline
Definition at line 219 of file Graph.h.
{ return &_node_ctx; }
outputs() [1/2]
OutputContext * loco::Graph::outputs (void) inline
Definition at line 222 of file Graph.h.
{ return &_output_ctx; }
Referenced by luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), validate_onnx2circle.OnnxRunner::get_outputs(), and OutputLayer::operator()().
outputs() [2/2]
const OutputContext * loco::Graph::outputs (void) const inline
Definition at line 223 of file Graph.h.
{ return &_output_ctx; }
Referenced by validate_onnx2circle.OnnxRunner::get_outputs().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Graph.h