ONE - On-device Neural Engine: loco::NodeShape Class Reference
loco::NodeShape Class Reference final
#include <NodeShape.h>
Public Member Functions
NodeShape ()=default
NodeShape (const BiasShape &shape)
NodeShape (const DepthwiseFilterShape &shape)
NodeShape (const FeatureShape &shape)
NodeShape (const FilterShape &shape)
NodeShape (const MatrixShape &shape)
NodeShape (const TensorShape &shape)
const Domain & domain (void) const
void set (const BiasShape &)
void set (const DepthwiseFilterShape &)
void set (const FeatureShape &)
void set (const FilterShape &)
void set (const MatrixShape &)
void set (const TensorShape &)
template<typename ShapeType >
ShapeType as (void) const
template<>
BiasShape as (void) const
template<>
DepthwiseFilterShape as (void) const
template<>
FeatureShape as (void) const
template<>
FilterShape as (void) const
template<>
MatrixShape as (void) const
template<>
TensorShape as (void) const
Detailed Description
Definition at line 34 of file NodeShape.h.
Constructor & Destructor Documentation
NodeShape() [1/7]
loco::NodeShape::NodeShape () default
NodeShape() [2/7]
loco::NodeShape::NodeShape (const BiasShape & shape) inline
Definition at line 40 of file NodeShape.h.
{ set(shape); }
References set().
NodeShape() [3/7]
loco::NodeShape::NodeShape (const DepthwiseFilterShape & shape) inline
Definition at line 41 of file NodeShape.h.
{ set(shape); }
References set().
NodeShape() [4/7]
loco::NodeShape::NodeShape (const FeatureShape & shape) inline
Definition at line 42 of file NodeShape.h.
{ set(shape); }
References set().
NodeShape() [5/7]
loco::NodeShape::NodeShape (const FilterShape & shape) inline
Definition at line 43 of file NodeShape.h.
{ set(shape); }
References set().
NodeShape() [6/7]
loco::NodeShape::NodeShape (const MatrixShape & shape) inline
Definition at line 44 of file NodeShape.h.
{ set(shape); }
References set().
NodeShape() [7/7]
loco::NodeShape::NodeShape (const TensorShape & shape) inline
Definition at line 45 of file NodeShape.h.
{ set(shape); }
References set().
Member Function Documentation
as() [1/7]
template<typename ShapeType > ShapeType loco::NodeShape::as (void) const
Referenced by moco::as_feature_shape(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MatMulConverter::convert(), exo::TensorTransposeConverter::convert(), exo::TransposedConv2DConverter::convert(), luci::CircleShapeInferenceRule::infer(), luci::infer_output_shape(), loco::operator==(), exo::to_shape_description(), luci::to_shape_description(), and luci::sinf::Algorithm::visit().
as() [2/7]
template<> BiasShape loco::NodeShape::as (void) const
Definition at line 36 of file NodeShape.cpp.
{
  assert(_domain == Domain::Bias);
  BiasShape res;
  res.length() = _dims.at(0);
  return res;
}
References loco::Bias, and loco::BiasShape::length().
as() [3/7]
template<> DepthwiseFilterShape loco::NodeShape::as (void) const
Definition at line 66 of file NodeShape.cpp.
{
  assert(_domain == Domain::DepthwiseFilter);
  DepthwiseFilterShape res;
  res.multiplier() = _dims.at(0);
  res.depth() = _dims.at(1);
  res.height() = _dims.at(2);
  res.width() = _dims.at(3);
  return res;
}
References loco::DepthwiseFilterShape::depth(), loco::DepthwiseFilter, loco::DepthwiseFilterShape::height(), loco::DepthwiseFilterShape::multiplier(), and loco::DepthwiseFilterShape::width().
as() [4/7]
template<> FeatureShape loco::NodeShape::as (void) const
Definition at line 99 of file NodeShape.cpp.
{
  assert(_domain == Domain::Feature);
  FeatureShape res;
  res.count() = _dims.at(0);
  res.depth() = _dims.at(1);
  res.height() = _dims.at(2);
  res.width() = _dims.at(3);
  return res;
}
References loco::FeatureShape::count(), loco::FeatureShape::depth(), loco::Feature, loco::FeatureShape::height(), and loco::FeatureShape::width().
as() [5/7]
template<> FilterShape loco::NodeShape::as (void) const
Definition at line 132 of file NodeShape.cpp.
{
  assert(_domain == Domain::Filter);
  FilterShape res;
  res.count() = _dims.at(0);
  res.depth() = _dims.at(1);
  res.height() = _dims.at(2);
  res.width() = _dims.at(3);
  return res;
}
References loco::FilterShape::count(), loco::FilterShape::depth(), loco::Filter, loco::FilterShape::height(), and loco::FilterShape::width().
as() [6/7]
template<> MatrixShape loco::NodeShape::as (void) const
Definition at line 163 of file NodeShape.cpp.
{
  assert(_domain == Domain::Matrix);
  MatrixShape res;
  res.height() = _dims.at(0);
  res.width() = _dims.at(1);
  return res;
}
References loco::MatrixShape::height(), loco::Matrix, and loco::MatrixShape::width().
as() [7/7]
template<> TensorShape loco::NodeShape::as (void) const
Definition at line 194 of file NodeShape.cpp.
{
  assert(_domain == Domain::Tensor);
  TensorShape res;
  res.rank(_dims.size());
  for (uint32_t axis = 0; axis < _dims.size(); ++axis)
  {
    res.dim(axis) = _dims.at(axis);
  }
  return res;
}
References loco::TensorShape::dim(), loco::TensorShape::rank(), and loco::Tensor.
domain()
const Domain & loco::NodeShape::domain (void) const inline
Definition at line 48 of file NodeShape.h.
{ return _domain; }
Referenced by moco::as_feature_shape(), exo::FeatureBiasAddConverter::convert(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), locoex::COpShapeInferenceRule::infer(), moco::node_shape(), loco::operator==(), exo::to_shape_description(), and luci::to_shape_description().
set() [1/6]
void loco::NodeShape::set (const BiasShape & shape)
Definition at line 28 of file NodeShape.cpp.
{
  _domain = Domain::Bias;
  _dims.resize(1);
  _dims.at(0) = shape.length();
}
References loco::Bias, and loco::BiasShape::length().
Referenced by locoex::COpShapeInferenceRule::infer(), NodeShape(), NodeShape(), NodeShape(), NodeShape(), NodeShape(), and NodeShape().
set() [2/6]
void loco::NodeShape::set (const DepthwiseFilterShape & shape)
Definition at line 55 of file NodeShape.cpp.
{
  _domain = Domain::DepthwiseFilter;
  _dims.resize(4);
  _dims.at(0) = shape.multiplier();
  _dims.at(1) = shape.depth();
  _dims.at(2) = shape.height();
  _dims.at(3) = shape.width();
}
References loco::DepthwiseFilterShape::depth(), loco::DepthwiseFilter, loco::DepthwiseFilterShape::height(), loco::DepthwiseFilterShape::multiplier(), and loco::DepthwiseFilterShape::width().
set() [3/6]
void loco::NodeShape::set (const FeatureShape & shape)
Definition at line 88 of file NodeShape.cpp.
{
  _domain = Domain::Feature;
  _dims.resize(4);
  _dims.at(0) = shape.count();
  _dims.at(1) = shape.depth();
  _dims.at(2) = shape.height();
  _dims.at(3) = shape.width();
}
References loco::FeatureShape::count(), loco::FeatureShape::depth(), loco::Feature, loco::FeatureShape::height(), and loco::FeatureShape::width().
set() [4/6]
void loco::NodeShape::set (const FilterShape & shape)
Definition at line 121 of file NodeShape.cpp.
{
  _domain = Domain::Filter;
  _dims.resize(4);
  _dims.at(0) = shape.count();
  _dims.at(1) = shape.depth();
  _dims.at(2) = shape.height();
  _dims.at(3) = shape.width();
}
References loco::FilterShape::count(), loco::FilterShape::depth(), loco::Filter, loco::FilterShape::height(), and loco::FilterShape::width().
set() [5/6]
void loco::NodeShape::set (const MatrixShape & shape)
Definition at line 154 of file NodeShape.cpp.
{
  _domain = Domain::Matrix;
  _dims.resize(2);
  _dims.at(0) = shape.height();
  _dims.at(1) = shape.width();
}
References loco::MatrixShape::height(), loco::Matrix, and loco::MatrixShape::width().
set() [6/6]
void loco::NodeShape::set (const TensorShape & shape)
Definition at line 183 of file NodeShape.cpp.
{
  _domain = Domain::Tensor;
  _dims.resize(shape.rank());
  for (uint32_t axis = 0; axis < shape.rank(); ++axis)
  {
    _dims.at(axis) = shape.dim(axis);
  }
}
References loco::TensorShape::dim(), loco::TensorShape::rank(), and loco::Tensor.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/NodeShape.h
compiler/loco/src/IR/NodeShape.cpp