ONE - On-device Neural Engine: exo::Logger Class Reference
exo::Logger Class Reference final
Logger Implementation.
#include <Log.h>
Public Member Functions
Logger (hermes::Context *ctx)
~Logger ()
Public Member Functions inherited from hermes::Source
bool check (const Severity &s) const
Check whether a message with a given severity is acceptable or not.
virtual void reload (const Config *)
Update Source with a given configuration.
std::unique_ptr< MessageBuffer > buffer (const Severity &) const
Additional Inherited Members
Public Types inherited from hermes::Source
using Setting = SourceSetting
Protected Member Functions inherited from hermes::Source
Source ()
virtual ~Source ()
void activate (Registry *, MessageBus *)
void deactivate (void)
Setting & setting (void)
Detailed Description
Logger Implementation.
Definition at line 30 of file Log.h.
Constructor & Destructor Documentation
Logger()
exo::Logger::Logger (hermes::Context * ctx)
Definition at line 48 of file Log.cpp.
{ activate(ctx->sources(), ctx->bus()); }
References hermes::Source::activate(), hermes::Context::bus(), and hermes::Context::sources().
~Logger()
exo::Logger::~Logger ()
Definition at line 49 of file Log.cpp.
{ deactivate(); }
References hermes::Source::deactivate().
The documentation for this class was generated from the following files:
compiler/exo/src/Log.h
compiler/exo/src/Log.cpp