ONE - On-device Neural Engine: record_minmax::DirectoryIterator Class Reference
record_minmax::DirectoryIterator Class Reference final
#include <DirectoryIterator.h>
Public Member Functions
DirectoryIterator (const std::string &dir_path, luci::Module *module)
bool hasNext () const override
std::vector< DataBuffer > next () override
bool check_type_shape () const override
~DirectoryIterator ()
Public Member Functions inherited from record_minmax::DataSetIterator
virtual ~DataSetIterator ()=default
Detailed Description
Definition at line 33 of file DirectoryIterator.h.
Constructor & Destructor Documentation
DirectoryIterator()
record_minmax::DirectoryIterator::DirectoryIterator (const std::string & dir_path, luci::Module * module)
Definition at line 32 of file DirectoryIterator.cpp.
  : _dir_path(dir_path)
{
  _dir = opendir(dir_path.c_str());
  if (not _dir)
    throw std::runtime_error("Cannot open directory. Please check \"" + _dir_path +
                             "\" is a directory.\n");
  dirent *entry = nullptr;
  while ((entry = readdir(_dir)))
  {
    if (entry->d_type != DT_REG)
      continue;
    _entries.emplace_back(entry);
  }
  auto input_nodes = loco::input_nodes(module->graph());
  for (auto input_node : input_nodes)
  {
    const auto cnode = loco::must_cast<const luci::CircleInput *>(input_node);
    _input_nodes.emplace_back(cnode);
  }
}
References entry(), loco::input_nodes(), and loco::must_cast().
~DirectoryIterator()
record_minmax::DirectoryIterator::~DirectoryIterator ()
Definition at line 57 of file DirectoryIterator.cpp.
{
  if (_dir)
    closedir(_dir);
};
Member Function Documentation
check_type_shape()
bool record_minmax::DirectoryIterator::check_type_shape () const override virtual
Implements record_minmax::DataSetIterator.
Definition at line 106 of file DirectoryIterator.cpp.
{ return false; }
hasNext()
bool record_minmax::DirectoryIterator::hasNext () const override virtual
Implements record_minmax::DataSetIterator.
Definition at line 63 of file DirectoryIterator.cpp.
{ return _curr_idx < _entries.size(); }
next()
std::vector< DataBuffer > record_minmax::DirectoryIterator::next () override virtual
Implements record_minmax::DataSetIterator.
Definition at line 65 of file DirectoryIterator.cpp.
{
  auto entry = _entries.at(_curr_idx++);
  assert(entry); // FIX_ME_UNLESS
  // Get total input size
  uint32_t total_input_size = 0;
  for (auto input : _input_nodes)
  {
    const auto *input_node = loco::must_cast<const luci::CircleInput *>(input);
    total_input_size += getTensorSize(input_node);
  }
  const std::string filename = entry->d_name;
  // Read data from file to buffer
  // Assumption: For a multi-input model, the binary file should have inputs concatenated in the
  // same order with the input index.
  std::vector<char> input_data(total_input_size);
  readDataFromFile(_dir_path + "/" + filename, input_data, total_input_size);
  std::vector<DataBuffer> res;
  uint32_t offset = 0;
  for (auto input_node : _input_nodes)
  {
    DataBuffer buf;
    const auto input_size = getTensorSize(input_node);
    buf.data.resize(input_size);
    memcpy(buf.data.data(), input_data.data() + offset, input_size);
    offset += input_size;
    res.emplace_back(buf);
  }
  return res;
}
References entry(), record_minmax::getTensorSize(), loco::must_cast(), offset(), and record_minmax::readDataFromFile().
The documentation for this class was generated from the following files:
compiler/record-minmax/include/DirectoryIterator.h
compiler/record-minmax/src/DirectoryIterator.cpp