ONE - On-device Neural Engine: arm_compute::CLGEMMMatrixAccumulateBiasesKernel Class Reference
arm_compute::CLGEMMMatrixAccumulateBiasesKernel Class Reference
#include <CLGEMMMatrixAccumulateBiasesKernel.h>
Public Member Functions
CLGEMMMatrixAccumulateBiasesKernel ()
CLGEMMMatrixAccumulateBiasesKernel (const CLGEMMMatrixAccumulateBiasesKernel &)=delete
CLGEMMMatrixAccumulateBiasesKernel & operator= (const CLGEMMMatrixAccumulateBiasesKernel &)=delete
CLGEMMMatrixAccumulateBiasesKernel (CLGEMMMatrixAccumulateBiasesKernel &&)=default
CLGEMMMatrixAccumulateBiasesKernel & operator= (CLGEMMMatrixAccumulateBiasesKernel &&)=default
void configure (ICLTensor *accum, const ICLTensor *biases)
void configure (const CLCompileContext &compile_context, ICLTensor *accum, const ICLTensor *biases)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *accum, const ITensorInfo *biases, GPUTarget gpu_target)
Detailed Description
Interface to add a bias to each row of the input tensor
Definition at line 51 of file CLGEMMMatrixAccumulateBiasesKernel.h.
Constructor & Destructor Documentation
CLGEMMMatrixAccumulateBiasesKernel() [1/3]
CLGEMMMatrixAccumulateBiasesKernel::CLGEMMMatrixAccumulateBiasesKernel ()
Default constructor
Definition at line 97 of file CLGEMMMatrixAccumulateBiasesKernel.cpp.
  : _accum(nullptr), _biases(nullptr)
{
}
CLGEMMMatrixAccumulateBiasesKernel() [2/3]
arm_compute::CLGEMMMatrixAccumulateBiasesKernel::CLGEMMMatrixAccumulateBiasesKernel (const CLGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLGEMMMatrixAccumulateBiasesKernel() [3/3]
arm_compute::CLGEMMMatrixAccumulateBiasesKernel::CLGEMMMatrixAccumulateBiasesKernel (CLGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved
Member Function Documentation
configure() [1/2]
void CLGEMMMatrixAccumulateBiasesKernel::configure (const CLCompileContext & compile_context, ICLTensor * accum, const ICLTensor * biases)
Set the accumulate buffer and the biases of the kernel.
Parameters
[in] compile_context The compile context to be used.
[in,out] accum The accumulate tensor to convert. Data types supported: F16/F32
[in] biases The shared biases tensor to append. It must be 1D tensor. Data types supported: Same as input
Definition at line 107 of file CLGEMMMatrixAccumulateBiasesKernel.cpp.
{
  ARM_COMPUTE_UNUSED(compile_context);
  // Perform validate step
  ARM_COMPUTE_ERROR_ON_NULLPTR(accum, biases);
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(accum->info(), biases->info()));
  _biases = biases;
  _accum = accum;
  // Get the target gpu
  GPUTarget gpu_target = get_target();
  unsigned int vector_size = 0;
  // Configure kernel window
  auto win_config =
    validate_and_configure_window(accum->info(), biases->info(), gpu_target, vector_size);
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  ICLKernel::configure_internal(win_config.second);
  // Add build options
  CLBuildOptions build_opts;
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(accum->info()->data_type()));
  build_opts.add_option("-DVECTOR_SIZE=" + support::cpp11::to_string(vector_size));
  // Create kernel
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("gemm_accumulate_biases", build_opts.options()));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
configure() [2/2]
void CLGEMMMatrixAccumulateBiasesKernel::configure (ICLTensor * accum, const ICLTensor * biases)
Set the accumulate buffer and the biases of the kernel.
Parameters
[in,out] accum The accumulate tensor to convert. Data types supported: F16/F32
[in] biases The shared biases tensor to append. It must be 1D tensor. Data types supported: Same as input
Definition at line 102 of file CLGEMMMatrixAccumulateBiasesKernel.cpp.
{
  configure(CLKernelLibrary::get().get_compile_context(), accum, biases);
}
References configure().
Referenced by arm_compute::CLFullyConnectedHybridLayer::configure(), and configure().
operator=() [1/2]
CLGEMMMatrixAccumulateBiasesKernel & arm_compute::CLGEMMMatrixAccumulateBiasesKernel::operator= (CLGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved
References validate().
operator=() [2/2]
CLGEMMMatrixAccumulateBiasesKernel & arm_compute::CLGEMMMatrixAccumulateBiasesKernel::operator= (const CLGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void CLGEMMMatrixAccumulateBiasesKernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 151 of file CLGEMMMatrixAccumulateBiasesKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_MISMATCHING_WINDOWS(ICLKernel::window(), window);
  Window accum_slice = window.first_slice_window_2D();
  Window biases_slice(accum_slice);
  biases_slice.set(Window::DimY, Window::Dimension(0, 1, 1));
  // Run kernel
  do
  {
    // Set arguments
    unsigned int idx = 0;
    add_2D_tensor_argument(idx, _accum, accum_slice);
    add_1D_tensor_argument(idx, _biases, biases_slice);
    enqueue(queue, *this, accum_slice, lws_hint());
  } while (window.slide_window_slice_2D(accum_slice));
}
validate()
Status CLGEMMMatrixAccumulateBiasesKernel::validate (const ITensorInfo * accum, const ITensorInfo * biases, GPUTarget gpu_target) static
Static function to check if given info will lead to a valid configuration of CLGEMMMatrixAccumulateBiasesKernel
Parameters
[in] accum The accumulate tensor to convert. Data types supported: F16/F32
[in] biases The shared biases tensor to append. It must be 1D tensor. Data types supported: Same as input
[in] gpu_target GPU target
Returns
a status
Definition at line 138 of file CLGEMMMatrixAccumulateBiasesKernel.cpp.
{
  unsigned int num_elems_processed_per_iteration = 0;
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(accum, biases));
  ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(accum->clone().get(),
                                                            biases->clone().get(), gpu_target,
                                                            num_elems_processed_per_iteration)
                                .first);
  return Status{};
}
Referenced by operator=(), and arm_compute::CLFullyConnectedHybridLayer::validate().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLGEMMMatrixAccumulateBiasesKernel.h
compute/ARMComputeEx/src/runtime/CL/functions/CLGEMMMatrixAccumulateBiasesKernel.cpp