ONE - On-device Neural Engine: mir::DotNodeBuilder Class Reference
mir::DotNodeBuilder Class Reference
#include <DotNodeBuilder.h>
Public Member Functions
DotNodeBuilder (const Operation &op)
void visit (ops::AvgPool2DOp &op) override
void visit (ops::CappedReluOp &op) override
void visit (ops::ConcatOp &op) override
void visit (ops::Conv2DOp &op) override
void visit (ops::DeConv2DOp &op) override
void visit (ops::DepthwiseConv2DOp &op) override
void visit (ops::EluOp &op) override
void visit (ops::GatherOp &op) override
void visit (ops::LeakyReluOp &op) override
void visit (ops::MaxPool2DOp &op) override
void visit (ops::PadOp &op) override
void visit (ops::ReduceMeanOp &op) override
void visit (ops::ResizeOp &op) override
void visit (ops::SliceOp &op) override
void visit (ops::SoftmaxOp &op) override
void visit (ops::SqueezeOp &op) override
void visit (ops::TransposeOp &op) override
void addAttribute (std::string name, std::string val)
DotNode getDotNode () const
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Additional Inherited Members
Protected Member Functions inherited from mir::Visitor
virtual void visit_fallback (Operation &)
Detailed Description
Definition at line 31 of file DotNodeBuilder.h.
Constructor & Destructor Documentation
DotNodeBuilder()
mir::DotNodeBuilder::DotNodeBuilder (const Operation & op) explicit
Definition at line 38 of file DotNodeBuilder.cpp.
{
  _type_name = getTypeName(op.getType());
  _id = op.getId();
  for (std::size_t i = 0; i < op.getNumInputs(); ++i)
  {
    _in_shapes.push_back(toString(op.getInputShape(i)));
  }
  for (std::size_t i = 0; i < op.getNumOutputs(); ++i)
  {
    _out_shapes.push_back(toString(op.getOutputShape(i)));
  }
  // Get attributes.
  const_cast<Operation &>(op).accept(this);
}
References mir::Operation::getId(), mir::Operation::getInputShape(), mir::Operation::getNumInputs(), mir::Operation::getNumOutputs(), mir::Operation::getOutputShape(), mir::Operation::getType(), mir::getTypeName(), and mir::toString().
Member Function Documentation
addAttribute()
void mir::DotNodeBuilder::addAttribute (std::string name, std::string val)
Definition at line 164 of file DotNodeBuilder.cpp.
{
  this->_attributes.emplace_back(std::move(name), std::move(val));
}
Referenced by visit().
getDotNode()
DotNode mir::DotNodeBuilder::getDotNode () const inline
Definition at line 56 of file DotNodeBuilder.h.
{ return {_id, getLabel()}; }
Referenced by mir::dumpGraph().
visit() [1/17]
void mir::DotNodeBuilder::visit (ops::AvgPool2DOp & op) override
Definition at line 57 of file DotNodeBuilder.cpp.
{
  addAttribute("Window size", toString(op.getWindowSize()));
  addAttribute("Strides", toString(op.getStrides()));
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Include pad", std::to_string(op.getIncludePad()));
}
References addAttribute(), mir::ops::AvgPool2DOp::getIncludePad(), mir::ops::AvgPool2DOp::getPaddingAfter(), mir::ops::AvgPool2DOp::getPaddingBefore(), mir::ops::AvgPool2DOp::getStrides(), mir::ops::AvgPool2DOp::getWindowSize(), and mir::toString().
visit() [2/17]
void mir::DotNodeBuilder::visit (ops::CappedReluOp & op) override
Definition at line 66 of file DotNodeBuilder.cpp.
{
  addAttribute("Cap", std::to_string(op.getCap()));
}
References addAttribute(), and mir::ops::CappedReluOp::getCap().
visit() [3/17]
void mir::DotNodeBuilder::visit (ops::ConcatOp & op) override
Definition at line 71 of file DotNodeBuilder.cpp.
{
  addAttribute("Axis", std::to_string(op.getAxis()));
}
References addAttribute(), and mir::ops::ConcatOp::getAxis().
visit() [4/17]
void mir::DotNodeBuilder::visit (ops::Conv2DOp & op) override
Definition at line 76 of file DotNodeBuilder.cpp.
{
  addAttribute("Strides", toString(op.getStrides()));
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Num groups", std::to_string(op.getNumGroups()));
  addAttribute("Data format", toString(op.getDataFormat()));
}
References addAttribute(), mir::ops::Conv2DOp::getDataFormat(), mir::ops::Conv2DOp::getNumGroups(), mir::ops::Conv2DOp::getPaddingAfter(), mir::ops::Conv2DOp::getPaddingBefore(), mir::ops::Conv2DOp::getStrides(), and mir::toString().
visit() [5/17]
void mir::DotNodeBuilder::visit (ops::DeConv2DOp & op) override
Definition at line 113 of file DotNodeBuilder.cpp.
{
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Strides", toString(op.getStrides()));
  addAttribute("Data format", toString(op.getDataFormat()));
}
References addAttribute(), mir::ops::DeConv2DOp::getDataFormat(), mir::ops::DeConv2DOp::getPaddingAfter(), mir::ops::DeConv2DOp::getPaddingBefore(), mir::ops::DeConv2DOp::getStrides(), and mir::toString().
visit() [6/17]
void mir::DotNodeBuilder::visit (ops::DepthwiseConv2DOp & op) override
Definition at line 85 of file DotNodeBuilder.cpp.
{
  addAttribute("Strides", toString(op.getStrides()));
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Data format", toString(op.getDataFormat()));
}
References addAttribute(), mir::ops::DepthwiseConv2DOp::getDataFormat(), mir::ops::DepthwiseConv2DOp::getPaddingAfter(), mir::ops::DepthwiseConv2DOp::getPaddingBefore(), mir::ops::DepthwiseConv2DOp::getStrides(), and mir::toString().
visit() [7/17]
void mir::DotNodeBuilder::visit (ops::EluOp & op) override
Definition at line 121 of file DotNodeBuilder.cpp.
{ addAttribute("Alpha", std::to_string(op.getAlpha())); }
References addAttribute(), and mir::ops::EluOp::getAlpha().
visit() [8/17]
void mir::DotNodeBuilder::visit (ops::GatherOp & op) override
Definition at line 154 of file DotNodeBuilder.cpp.
{
  addAttribute("Axis", std::to_string(op.getAxis()));
}
References addAttribute(), and mir::ops::GatherOp::getAxis().
visit() [9/17]
void mir::DotNodeBuilder::visit (ops::LeakyReluOp & op) override
Definition at line 159 of file DotNodeBuilder.cpp.
{
  addAttribute("Alpha", std::to_string(op.getAlpha()));
}
References addAttribute(), and mir::ops::LeakyReluOp::getAlpha().
visit() [10/17]
void mir::DotNodeBuilder::visit (ops::MaxPool2DOp & op) override
Definition at line 93 of file DotNodeBuilder.cpp.
{
  addAttribute("Window size", toString(op.getWindowSize()));
  addAttribute("Strides", toString(op.getStrides()));
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Data format", toString(op.getDataFormat()));
}
References addAttribute(), mir::ops::MaxPool2DOp::getDataFormat(), mir::ops::MaxPool2DOp::getPaddingAfter(), mir::ops::MaxPool2DOp::getPaddingBefore(), mir::ops::MaxPool2DOp::getStrides(), mir::ops::MaxPool2DOp::getWindowSize(), and mir::toString().
visit() [11/17]
void mir::DotNodeBuilder::visit (ops::PadOp & op) override
Definition at line 128 of file DotNodeBuilder.cpp.
{
  addAttribute("Padding before", toString(op.getPaddingBefore()));
  addAttribute("Padding after", toString(op.getPaddingAfter()));
  addAttribute("Padding value", std::to_string(op.getPaddingValue()));
}
References mir::ops::PadOp::getPaddingAfter(), mir::ops::PadOp::getPaddingBefore(), mir::ops::PadOp::getPaddingValue(), and mir::toString().
visit() [12/17]
void mir::DotNodeBuilder::visit (ops::ReduceMeanOp & op) override
Definition at line 135 of file DotNodeBuilder.cpp.
{
  addAttribute("Reduction dims", toString(op.getReductionDims()));
  addAttribute("Keep dims", std::to_string(op.getKeepDims()));
}
References addAttribute(), mir::ops::ReduceOp::getKeepDims(), mir::ops::ReduceOp::getReductionDims(), and mir::toString().
visit() [13/17]
void mir::DotNodeBuilder::visit (ops::ResizeOp & op) override
Definition at line 141 of file DotNodeBuilder.cpp.
{
  assert(op.getMode() == ops::ResizeOp::ResizeMethod::nearestNeighbor);
  (void)op;
  addAttribute("Interpolation mode", "nearestNeighbor");
}
References addAttribute(), mir::ops::ResizeOp::getMode(), and mir::ops::ResizeOp::nearestNeighbor.
visit() [14/17]
void mir::DotNodeBuilder::visit (ops::SliceOp & op) override
Definition at line 107 of file DotNodeBuilder.cpp.
{
  addAttribute("Starts", toString(op.getStarts()));
  addAttribute("Sizes", toString(op.getSizes()));
}
References addAttribute(), mir::ops::SliceOp::getSizes(), mir::ops::SliceOp::getStarts(), and mir::toString().
visit() [15/17]
void mir::DotNodeBuilder::visit (ops::SoftmaxOp & op) override
Definition at line 102 of file DotNodeBuilder.cpp.
{
  addAttribute("Axis", std::to_string(op.getAxis()));
}
References addAttribute(), and mir::ops::SoftmaxOp::getAxis().
visit() [16/17]
void mir::DotNodeBuilder::visit (ops::SqueezeOp & op) override
Definition at line 123 of file DotNodeBuilder.cpp.
{
  addAttribute("Dims to squeeze", toString(op.getDimsToSqueeze()));
}
References addAttribute(), mir::ops::SqueezeOp::getDimsToSqueeze(), and mir::toString().
visit() [17/17]
void mir::DotNodeBuilder::visit (ops::TransposeOp & op) override
Definition at line 149 of file DotNodeBuilder.cpp.
{
  addAttribute("Axis order", toString(op.getAxisOrder()));
}
References addAttribute(), mir::ops::TransposeOp::getAxisOrder(), and mir::toString().
The documentation for this class was generated from the following files:
compiler/mir/src/DotNodeBuilder.h
compiler/mir/src/DotNodeBuilder.cpp