ONE - On-device Neural Engine: loco::Window< 2 > Class Reference
loco::Window< 2 > Class Reference final
2D Receptive Field Shape
#include <Window.h>
Public Member Functions
uint32_t vertical (void) const
void vertical (uint32_t value)
uint32_t horizontal (void) const
void horizontal (uint32_t value)
Detailed Description
2D Receptive Field Shape
Definition at line 35 of file Window.h.
Member Function Documentation
horizontal() [1/2]
void loco::Window< 2 >::horizontal (uint32_t value) inline
Definition at line 43 of file Window.h.
{ _horizontal = value; }
horizontal() [2/2]
uint32_t loco::Window< 2 >::horizontal (void) const inline
Definition at line 42 of file Window.h.
{ return _horizontal; }
Referenced by exo::AvgPool2DConverter::convert(), exo::MaxPool2DConverter::convert(), and moco::PlaneInference::fill().
vertical() [1/2]
void loco::Window< 2 >::vertical (uint32_t value) inline
Definition at line 39 of file Window.h.
{ _vertical = value; }
vertical() [2/2]
uint32_t loco::Window< 2 >::vertical (void) const inline
Definition at line 38 of file Window.h.
{ return _vertical; }
Referenced by exo::AvgPool2DConverter::convert(), exo::MaxPool2DConverter::convert(), and moco::PlaneInference::fill().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Window.h