ONE - On-device Neural Engine: coco::PtrList< T > Class Template Reference
coco::PtrList< T > Class Template Reference
#include <PtrList.h>
Public Member Functions
PtrList ()=default
PtrList (const PtrList &)=delete
PtrList (PtrList &&)=delete
virtual ~PtrList ()=default
uint32_t size (void) const
T * at (uint32_t n) const
void insert (T *ptr)
Detailed Description
template<typename T>
class coco::PtrList< T >
Definition at line 27 of file PtrList.h.
Constructor & Destructor Documentation
PtrList() [1/3]
template<typename T > coco::PtrList< T >::PtrList () default
PtrList() [2/3]
template<typename T > coco::PtrList< T >::PtrList (const PtrList< T > &) delete
PtrList() [3/3]
template<typename T > coco::PtrList< T >::PtrList (PtrList< T > &&) delete
~PtrList()
template<typename T > virtual coco::PtrList< T >::~PtrList () virtual default
Member Function Documentation
at()
template<typename T > T * coco::PtrList< T >::at (uint32_t n) const inline
Definition at line 43 of file PtrList.h.
{ return _ptrs.at(n); }
Referenced by dump().
insert()
template<typename T > void coco::PtrList< T >::insert (T * ptr) inline
Definition at line 46 of file PtrList.h.
{ _ptrs.emplace_back(ptr); }
Referenced by caffeimport::InputBuilder::build(), and Frontend::load().
size()
template<typename T > uint32_t coco::PtrList< T >::size (void) const inline
Definition at line 40 of file PtrList.h.
{ return _ptrs.size(); }
Referenced by dump().
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/ADT/PtrList.h