ONE - On-device Neural Engine: luci::ImporterEx Class Reference
luci::ImporterEx Class Reference final
#include <ImporterEx.h>
Public Member Functions
ImporterEx ()
ImporterEx (const std::function< void(const std::exception &)> &error_handler)
ImporterEx (const GraphBuilderSource *source)
std::unique_ptr< Module > importVerifyModule (const std::string &input_path) const
std::unique_ptr< Module > importModule (const std::vector< char > &model_data) const
Detailed Description
Definition at line 35 of file ImporterEx.h.
Constructor & Destructor Documentation
ImporterEx() [1/3]
luci::ImporterEx::ImporterEx ()
Definition at line 37 of file ImporterEx.cpp.
  : _error_handler{[](const std::exception &e) { std::cerr << e.what() << std::endl; }}
{
}
ImporterEx() [2/3]
luci::ImporterEx::ImporterEx (const std::function< void(const std::exception &)> & error_handler)
Definition at line 42 of file ImporterEx.cpp.
  : _error_handler{error_handler}
{
  if (!error_handler)
  {
    throw std::runtime_error{"The error handler passed to ImporterEx is invalid"};
  }
}
References luci::must_cast().
ImporterEx() [3/3]
luci::ImporterEx::ImporterEx (const GraphBuilderSource * source) explicit
Definition at line 51 of file ImporterEx.cpp.
: ImporterEx{} { _source = source; }
Member Function Documentation
importModule()
std::unique_ptr< Module > luci::ImporterEx::importModule (const std::vector< char > & model_data) const
Definition at line 85 of file ImporterEx.cpp.
{
  auto data_data = reinterpret_cast<const uint8_t *>(model_data.data());
  auto data_size = model_data.size();
  Importer importer(_source);
  return importer.importModule(data_data, data_size);
}
References luci::must_cast().
Referenced by entry().
importVerifyModule()
std::unique_ptr< Module > luci::ImporterEx::importVerifyModule (const std::string & input_path) const
Definition at line 53 of file ImporterEx.cpp.
{
  foder::FileLoader file_loader{input_path};
  std::vector<char> model_data;
  try
  {
    model_data = file_loader.load();
  }
  catch (const std::runtime_error &err)
  {
    _error_handler(err);
    return nullptr;
  }
  auto data_data = reinterpret_cast<uint8_t *>(model_data.data());
  auto data_size = model_data.size();
  if (data_size < FLATBUFFERS_SIZE_MAX)
  {
    flatbuffers::Verifier verifier{data_data, data_size};
    if (!circle::VerifyModelBuffer(verifier))
    {
      _error_handler(std::runtime_error{"ERROR: Invalid input file '" + input_path + "'"});
      return nullptr;
    }
  }
  Importer importer(_source);
  return importer.importModule(data_data, data_size);
}
References FLATBUFFERS_SIZE_MAX, and luci::must_cast().
Referenced by mpqsolver::core::H5FileDataProvider::H5FileDataProvider(), dalgona::Dalgona::initialize(), and record_minmax::RecordMinMax::initialize().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/ImporterEx.h
compiler/luci/import/src/ImporterEx.cpp