ONE - On-device Neural Engine: onert::backend::train::ops::LossMeanSquaredErrorLayer Class Reference
onert::backend::train::ops::LossMeanSquaredErrorLayer Class Reference
#include <LossMeanSquaredErrorLayer.h>
Public Member Functions
LossMeanSquaredErrorLayer ()=default
void configure (const IPortableTensor *y_pred, const IPortableTensor *y_true, IPortableTensor *output, IPortableTensor *back_prop_y_pred)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::backend::train::ops::LossLayer
LossLayer ()
void configure (const IPortableTensor *y_pred, const IPortableTensor *y_true, IPortableTensor *output, IPortableTensor *back_prop_y_pred)
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
virtual void forward (bool training)=0
virtual void backward ()=0
Additional Inherited Members
Protected Attributes inherited from onert::backend::train::ops::LossLayer
const IPortableTensor * _y_pred
const IPortableTensor * _y_true
IPortableTensor * _output
IPortableTensor * _back_prop_y_pred
Detailed Description
Definition at line 31 of file LossMeanSquaredErrorLayer.h.
Constructor & Destructor Documentation
LossMeanSquaredErrorLayer()
onert::backend::train::ops::LossMeanSquaredErrorLayer::LossMeanSquaredErrorLayer () default
Member Function Documentation
backward()
void onert::backend::train::ops::LossMeanSquaredErrorLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 52 of file LossMeanSquaredErrorLayer.cc.
{
  if (_y_pred->data_type() == OperandType::FLOAT32)
  {
    nnfw::cker::train::MSEGrad(getShape(_y_pred), getBuffer<float>(_y_pred), getShape(_y_true),
                               getBuffer<float>(_y_true), getShape(_back_prop_y_pred),
                               getBuffer<float>(_back_prop_y_pred));
  }
  else
  {
    throw std::runtime_error("LossMeanSquaredErrorLayer: unsupported data type");
  }
}
References onert::backend::train::ops::LossLayer::_back_prop_y_pred, onert::backend::train::ops::LossLayer::_y_pred, onert::backend::train::ops::LossLayer::_y_true, onert::backend::ITensor::data_type(), and nnfw::cker::train::MSEGrad().
configure()
void onert::backend::train::ops::LossMeanSquaredErrorLayer::configure (const IPortableTensor * y_pred, const IPortableTensor * y_true, IPortableTensor * output, IPortableTensor * back_prop_y_pred)
Definition at line 31 of file LossMeanSquaredErrorLayer.cc.
{
  LossLayer::configure(y_pred, y_true, output, back_prop_y_pred);
}
References onert::backend::train::ops::LossLayer::configure().
forward()
void onert::backend::train::ops::LossMeanSquaredErrorLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 38 of file LossMeanSquaredErrorLayer.cc.
{
  // TODO Implement this
  if (_y_pred->data_type() == OperandType::FLOAT32)
  {
    nnfw::cker::train::MSE(getShape(_y_pred), getBuffer<float>(_y_pred), getShape(_y_true),
                           getBuffer<float>(_y_true), getShape(_output), getBuffer<float>(_output));
  }
  else
  {
    throw std::runtime_error("LossMeanSquaredErrorLayer: unsupported data type");
  }
}
References onert::backend::train::ops::LossLayer::_output, onert::backend::train::ops::LossLayer::_y_pred, onert::backend::train::ops::LossLayer::_y_true, onert::backend::ITensor::data_type(), and nnfw::cker::train::MSE().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.h
runtime/onert/backend/train/ops/LossMeanSquaredErrorLayer.cc