ONE - On-device Neural Engine: nnc::CombineTransposes Class Reference
nnc::CombineTransposes Class Reference
This pass combines sequential transposes and removes identity transposes if the combination results in an identity permutation.
#include <CombineTransposes.h>
Public Member Functions
PassData run (PassData data) override
run compiler pass
std::string getName () override
Public Member Functions inherited from nnc::Pass
virtual PassData run (PassData data)=0
run compiler pass
virtual void cleanup ()
clean compiler pass data
virtual ~Pass ()=default
virtual std::string getName ()
Detailed Description
This pass combines sequential transposes and removes identity transposes if the combination results in an identity permutation.
Definition at line 30 of file CombineTransposes.h.
Member Function Documentation
getName()
std::string nnc::CombineTransposes::getName () inline override virtual
Reimplemented from nnc::Pass.
Definition at line 35 of file CombineTransposes.h.
{ return "opt_combine_transposes"; };
run()
nnc::PassData nnc::CombineTransposes::run (PassData data) override virtual
run compiler pass
Parameters
data - data that pass is taken
Returns
data that can be passed to the next pass
Exceptions
PassException object if errors occured
Implements nnc::Pass.
Definition at line 52 of file CombineTransposes.cpp.
{
  auto g = static_cast<Graph *>(data);
  assert(g);
  GraphPatternMatcher matcher(g);
  auto is_tr = [](const Operation *op1) { return op1->getType() == Operation::Type::transpose; };
  std::vector<std::pair<Operation *, Operation *>> matches = matcher.matchEdge(is_tr, is_tr);
  std::unordered_set<Operation *> deleted_nodes;
  while (!matches.empty())
  {
    for (std::pair<Operation *, Operation *> match : matches)
    {
      if (deleted_nodes.find(match.first) != deleted_nodes.end())
      {
        break;
      };
      auto *top_transpose = dynamic_cast<mir::ops::TransposeOp *>(match.first);
      if (deleted_nodes.find(match.second) != deleted_nodes.end())
      {
        break;
      };
      auto *bottom_transpose = dynamic_cast<mir::ops::TransposeOp *>(match.second);
      auto combined_axis_order =
        combineAxisOrders(top_transpose->getAxisOrder(), bottom_transpose->getAxisOrder());
      if (!isIdentityTranspose(combined_axis_order))
      {
        auto new_tr_op =
          g->create<mir::ops::TransposeOp>(top_transpose->getInput(0), combined_axis_order);
        g->replaceNode(bottom_transpose, new_tr_op);
      }
      else
      {
        // Connect top input to all outputs of bottom
        Operation *top = top_transpose->getInput(0)->getNode();
        g->replaceNode(bottom_transpose, top);
      }
      deleted_nodes.emplace(bottom_transpose);
      if (top_transpose->getOutput(0)->getUses().empty())
      {
        g->removeNode(top_transpose);
        deleted_nodes.emplace(top_transpose);
      }
    }
    matches = matcher.matchEdge(is_tr, is_tr);
  };
  return g;
}
References nnc::combineAxisOrders(), mir::Operation::getInput(), mir::Operation::Output::getNode(), and mir::GraphPatternMatcher::matchEdge().
The documentation for this class was generated from the following files:
compiler/nnc/include/passes/optimizations/CombineTransposes.h
compiler/nnc/passes/optimizations/CombineTransposes.cpp