ONE - On-device Neural Engine: nncc::core::ADT::tensor::Index Class Reference
nncc::core::ADT::tensor::Index Class Reference
#include <Index.h>
Public Member Functions
Index ()=default
Index (std::initializer_list< uint32_t > &&l)
uint32_t rank (void) const
Index & resize (uint32_t size)
Index & fill (uint32_t index)
uint32_t & at (uint32_t axis)
uint32_t at (uint32_t axis) const
Detailed Description
Definition at line 33 of file Index.h.
Constructor & Destructor Documentation
Index() [1/2]
nncc::core::ADT::tensor::Index::Index () default
Index() [2/2]
nncc::core::ADT::tensor::Index::Index (std::initializer_list< uint32_t > && l)
Definition at line 31 of file Index.cpp.
                                              : _indices{l}
{
  // DO NOTHING
}
Member Function Documentation
at() [1/2]
uint32_t & nncc::core::ADT::tensor::Index::at (uint32_t axis)
Definition at line 49 of file Index.cpp.
{ return _indices.at(axis); }
Referenced by nncc::core::ADT::tensor::IndexEnumerator::advance(), nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator(), enco::lower_concat(), nncc::core::ADT::tensor::operator+(), nncc::core::ADT::tensor::operator==(), loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), loco::PermutingEncoder< Domain::Feature >::value(), loco::PermutingEncoder< Domain::Filter >::value(), loco::PermutingEncoder< Domain::Matrix >::value(), loco::PermutingDecoder< Domain::Feature >::value(), loco::PermutingDecoder< Domain::Filter >::value(), loco::PermutingDecoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::Matrix >::value().
at() [2/2]
uint32_t nncc::core::ADT::tensor::Index::at (uint32_t axis) const
Definition at line 50 of file Index.cpp.
{ return _indices.at(axis); }
fill()
Index & nncc::core::ADT::tensor::Index::fill (uint32_t index)
Definition at line 43 of file Index.cpp.
{
  std::fill(_indices.begin(), _indices.end(), index);
  return (*this);
}
rank()
uint32_t nncc::core::ADT::tensor::Index::rank (void) const
Definition at line 36 of file Index.cpp.
{ return _indices.size(); }
Referenced by nncc::core::ADT::tensor::operator+(), nncc::core::ADT::tensor::operator==(), and loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
resize()
Index & nncc::core::ADT::tensor::Index::resize (uint32_t size)
Definition at line 37 of file Index.cpp.
{
  _indices.resize(size);
  return *this;
}
Referenced by nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::tensor::operator+(), loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), loco::PermutingEncoder< Domain::Feature >::value(), loco::PermutingEncoder< Domain::Filter >::value(), and loco::PermutingEncoder< Domain::Matrix >::value().
The documentation for this class was generated from the following files:
compiler/angkor/include/nncc/core/ADT/tensor/Index.h
compiler/angkor/src/ADT/tensor/Index.cpp