ONE - On-device Neural Engine: hermes::EnvConfig< EnvFormat::BooleanNumber > Class Reference
hermes::EnvConfig< EnvFormat::BooleanNumber > Class Reference
#include <EnvConfig.h>
Public Member Functions
EnvConfig (const EnvName &name)
virtual ~EnvConfig ()=default
void configure (const Source *, SourceSetting &) const final
Public Member Functions inherited from hermes::Config
virtual ~Config ()=default
virtual void configure (const Source *, SourceSetting &) const =0
Detailed Description
Definition at line 38 of file EnvConfig.h.
Constructor & Destructor Documentation
EnvConfig()
hermes::EnvConfig< EnvFormat::BooleanNumber >::EnvConfig (const EnvName & name)
Definition at line 24 of file EnvConfig.cpp.
{
  auto s = std::getenv(name.c_str());
  _enabled = (pepper::safe_strcast<int>(s, 0 /* DISABLE BY DEFAULT */) != 0);
}
References pepper::safe_strcast< int >().
~EnvConfig()
virtual hermes::EnvConfig< EnvFormat::BooleanNumber >::~EnvConfig () virtual default
Member Function Documentation
configure()
void hermes::EnvConfig< EnvFormat::BooleanNumber >::configure (const Source * , SourceSetting & setting) const final virtual
Implements hermes::Config.
Definition at line 30 of file EnvConfig.cpp.
{
  if (_enabled)
  {
    // Enable all the sources
    setting.accept_all();
  }
  else
  {
    // Disable all the sources
    setting.reject_all();
  }
}
References hermes::SourceSetting::accept_all(), and hermes::SourceSetting::reject_all().
The documentation for this class was generated from the following files:
compiler/hermes-std/include/hermes/EnvConfig.h
compiler/hermes-std/src/EnvConfig.cpp