ONE - On-device Neural Engine: luci_interpreter::kernels::Fill Class Reference
luci_interpreter::kernels::Fill Class Reference
#include <Fill.h>
Public Member Functions
Fill (const Tensor *dims, const Tensor *value, Tensor *output)
const Tensor * dims () const
const Tensor * value () const
Tensor * output () const
void configure () override
void execute () const override
Fill (const Tensor *dims, const Tensor *value, Tensor *output)
const Tensor * dims () const
const Tensor * value () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Fill.h.
Constructor & Destructor Documentation
Fill() [1/2]
luci_interpreter::kernels::Fill::Fill (const Tensor * dims, const Tensor * value, Tensor * output)
Definition at line 26 of file Fill.cpp.
  : Kernel({dims, value}, {output})
{
}
References dims(), and value().
Fill() [2/2]
luci_interpreter::kernels::Fill::Fill (const Tensor * dims, const Tensor * value, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Fill::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 48 of file Fill.cpp.
{
  const auto dims_shape = dims()->shape();
  const auto value_shape = value()->shape();
  // Make sure the 1st input tensor is 1-D
  LUCI_INTERPRETER_CHECK(dims_shape.num_dims() == 1);
  // Make sure the 1st input tensor is int32 or int64
  LUCI_INTERPRETER_CHECK(dims()->element_type() == DataType::S32 or
                         dims()->element_type() == DataType::S64);
  // Make sure the 2nd input tensor is a scalar
  LUCI_INTERPRETER_CHECK(value_shape.num_dims() == 0)
  // Check zero point and scale for S16 and S8
  if (value()->element_type() == loco::DataType::S16 or
      value()->element_type() == loco::DataType::S8)
  {
    LUCI_INTERPRETER_CHECK(value()->scale() == output()->scale());
    LUCI_INTERPRETER_CHECK(value()->zero_point() == output()->zero_point());
    if (value()->element_type() == loco::DataType::S16)
      LUCI_INTERPRETER_CHECK(value()->zero_point() == 0);
  }
  // Resize output
  switch (dims()->element_type())
  {
    case DataType::S32:
      configureShape<int32_t>();
      break;
    case DataType::S64:
      configureShape<int64_t>();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References dims(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::Tensor::shape(), and value().
configure() [2/2]
void luci_interpreter::kernels::Fill::configure () override virtual
Implements luci_interpreter::Kernel.
dims() [1/2]
const Tensor * luci_interpreter::kernels::Fill::dims () const inline
Definition at line 33 of file Fill.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Fill().
dims() [2/2]
const Tensor * luci_interpreter::kernels::Fill::dims () const inline
Definition at line 33 of file Fill.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
execute() [1/2]
void luci_interpreter::kernels::Fill::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 87 of file Fill.cpp.
{
  switch (output()->element_type())
  {
    case DataType::S8:
      tflite::reference_ops::Fill(getTensorShape(value()), getTensorData<int8_t>(value()),
                                  getTensorShape(output()), getTensorData<int8_t>(output()));
      break;
    case DataType::S16:
      tflite::reference_ops::Fill(getTensorShape(value()), getTensorData<int16_t>(value()),
                                  getTensorShape(output()), getTensorData<int16_t>(output()));
      break;
    case DataType::S32:
      tflite::reference_ops::Fill(getTensorShape(value()), getTensorData<int32_t>(value()),
                                  getTensorShape(output()), getTensorData<int32_t>(output()));
      break;
    case DataType::S64:
      tflite::reference_ops::Fill(getTensorShape(value()), getTensorData<int64_t>(value()),
                                  getTensorShape(output()), getTensorData<int64_t>(output()));
      break;
    case DataType::FLOAT32:
      tflite::reference_ops::Fill(getTensorShape(value()), getTensorData<float>(value()),
                                  getTensorShape(output()), getTensorData<float>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::kernels::getTensorShape(), output(), and value().
execute() [2/2]
void luci_interpreter::kernels::Fill::execute () const override virtual
Implements luci_interpreter::Kernel.
output() [1/2]
Tensor * luci_interpreter::kernels::Fill::output () const inline
Definition at line 35 of file Fill.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Fill::output () const inline
Definition at line 35 of file Fill.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
value() [1/2]
const Tensor * luci_interpreter::kernels::Fill::value () const inline
Definition at line 34 of file Fill.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Fill().
value() [2/2]
const Tensor * luci_interpreter::kernels::Fill::value () const inline
Definition at line 34 of file Fill.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Fill.h
onert-micro/luci-interpreter/src/kernels/Fill.h
compiler/luci-interpreter/src/kernels/Fill.cpp
onert-micro/luci-interpreter/src/kernels/Fill.cpp