ONE - On-device Neural Engine: luci::GraphBuilder Class Reference
luci::GraphBuilder Class Reference abstract
Base of general single output graph builder(e.g., Conv2DGraphBuilder)
#include <GraphBuilder.h>
Public Member Functions
virtual ~GraphBuilder ()=default
bool validate (const ValidateArgs &args, size_t input_cnt) const
CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const final
Public Member Functions inherited from luci::GraphBuilderBase
virtual bool validate (const ValidateArgs &) const =0
virtual CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const =0
virtual ~GraphBuilderBase ()=default
Detailed Description
Base of general single output graph builder(e.g., Conv2DGraphBuilder)
Definition at line 31 of file GraphBuilder.h.
Constructor & Destructor Documentation
~GraphBuilder()
virtual luci::GraphBuilder::~GraphBuilder () virtual default
Member Function Documentation
build()
CircleNode * GraphBuilder::build (const circle::OperatorT & op, GraphBuilderContext * context) const final virtual
Implements luci::GraphBuilderBase.
Definition at line 24 of file GraphBuilder.cpp.
{
  LOGGER(l);
  assert(context != nullptr);
  const std::vector<int32_t> &inputs = op.inputs;
  const std::vector<int32_t> &outputs = op.outputs;
  const auto tensors = context->reader()->tensors();
  const auto opcodes = context->reader()->opcodes();
  assert(!tensors.null());
  std::vector<CircleNode *> input_nodes;
  for (const int32_t input_tensor_index : inputs)
  {
    if (input_tensor_index >= 0)
    {
      auto input = context->nodefinder()->node(input_tensor_index);
      if (input == nullptr)
        INFO(l) << "[luci] Warning: input node is null " << input_tensor_index << std::endl;
      input_nodes.push_back(input);
    }
    else
    {
      // If there is no tensor, insert CircleOutputExclude.
      auto *node = context->graph()->nodes()->create<luci::CircleOutputExclude>();
      input_nodes.push_back(node);
    }
  }
  CircleNode *node = build_node(op, input_nodes, context->graph());
  // Set up node parameters.
  assert(outputs.size() == 1);
  {
    const auto output_tensor = tensors[outputs[0]];
    assert(output_tensor != nullptr);
    copy_tensor_attributes(output_tensor, node);
    // mark shape_status
    if (output_tensor->shape() == nullptr)
      node->shape_status(ShapeStatus::NOSHAPE);
    else
      node->shape_status(ShapeStatus::VALID);
    // mark operator version
    assert(opcodes[op.opcode_index] != nullptr);
    node->op_version(opcodes[op.opcode_index]->version());
  }
  // Register node's only output.
  assert(outputs.size() == 1);
  {
    context->nodefinder()->enroll(outputs[0], node);
  }
  return node;
}
References luci::copy_tensor_attributes(), loco::NodePool::create(), luci::IndexNodeFinder::enroll(), luci::GraphBuilderContext::graph(), INFO, LOGGER, luci::IndexNodeFinder::node(), luci::GraphBuilderContext::nodefinder(), loco::Graph::nodes(), luci::NOSHAPE, luci::CircleNode::op_version(), luci::CircleReader::opcodes(), luci::GraphBuilderContext::reader(), luci::CircleNode::shape_status(), luci::CircleReader::tensors(), and luci::VALID.
validate()
bool luci::GraphBuilder::validate (const ValidateArgs & args, size_t input_cnt) const inline
Definition at line 37 of file GraphBuilder.h.
  {
    return (args.op.inputs.size() == input_cnt && args.op.outputs.size() == 1);
  }
Referenced by luci::CircleAbsGraphBuilder::validate(), luci::CircleAddGraphBuilder::validate(), luci::CircleArgMaxGraphBuilder::validate(), luci::CircleArgMinGraphBuilder::validate(), luci::CircleAveragePool2DGraphBuilder::validate(), luci::CircleBatchMatMulGraphBuilder::validate(), luci::CircleBCQFullyConnectedGraphBuilder::validate(), luci::CircleBCQGatherGraphBuilder::validate(), luci::CircleCastGraphBuilder::validate(), luci::CircleCeilGraphBuilder::validate(), luci::CircleConv2DGraphBuilder::validate(), luci::CircleCosGraphBuilder::validate(), luci::CircleDensifyGraphBuilder::validate(), luci::CircleDepthToSpaceGraphBuilder::validate(), luci::CircleDequantizeGraphBuilder::validate(), luci::CircleEluGraphBuilder::validate(), luci::CircleEqualGraphBuilder::validate(), luci::CircleExpGraphBuilder::validate(), luci::CircleExpandDimsGraphBuilder::validate(), luci::CircleFakeQuantGraphBuilder::validate(), luci::CircleFillGraphBuilder::validate(), luci::CircleFloorGraphBuilder::validate(), luci::CircleFloorDivGraphBuilder::validate(), luci::CircleFloorModGraphBuilder::validate(), luci::CircleFullyConnectedGraphBuilder::validate(), luci::CircleGatherGraphBuilder::validate(), luci::CircleGatherNdGraphBuilder::validate(), luci::CircleGreaterGraphBuilder::validate(), luci::CircleGreaterEqualGraphBuilder::validate(), luci::CircleInstanceNormGraphBuilder::validate(), luci::CircleL2NormalizeGraphBuilder::validate(), luci::CircleL2Pool2DGraphBuilder::validate(), luci::CircleLeakyReluGraphBuilder::validate(), luci::CircleLessGraphBuilder::validate(), luci::CircleLessEqualGraphBuilder::validate(), luci::CircleLocalResponseNormalizationGraphBuilder::validate(), luci::CircleLogGraphBuilder::validate(), luci::CircleLogicalAndGraphBuilder::validate(), luci::CircleLogicalNotGraphBuilder::validate(), luci::CircleLogicalOrGraphBuilder::validate(), luci::CircleLogisticGraphBuilder::validate(), luci::CircleLogSoftmaxGraphBuilder::validate(), luci::CircleMatrixDiagGraphBuilder::validate(), luci::CircleMatrixSetDiagGraphBuilder::validate(), luci::CircleMaxPool2DGraphBuilder::validate(), luci::CircleMeanGraphBuilder::validate(), luci::CircleMirrorPadGraphBuilder::validate(), luci::CircleMulGraphBuilder::validate(), luci::CircleNegGraphBuilder::validate(), luci::CircleNotEqualGraphBuilder::validate(), luci::CircleOneHotGraphBuilder::validate(), luci::CirclePadGraphBuilder::validate(), luci::CirclePadV2GraphBuilder::validate(), luci::CirclePowGraphBuilder::validate(), luci::CirclePReluGraphBuilder::validate(), luci::CircleQuantizeGraphBuilder::validate(), luci::CircleRangeGraphBuilder::validate(), luci::CircleRankGraphBuilder::validate(), luci::CircleReduceAnyGraphBuilder::validate(), luci::CircleReduceProdGraphBuilder::validate(), luci::CircleReluGraphBuilder::validate(), luci::CircleRelu6GraphBuilder::validate(), luci::CircleReluN1To1GraphBuilder::validate(), luci::CircleResizeBilinearGraphBuilder::validate(), luci::CircleResizeNearestNeighborGraphBuilder::validate(), luci::CircleReverseSequenceGraphBuilder::validate(), luci::CircleReverseV2GraphBuilder::validate(), luci::CircleRoundGraphBuilder::validate(), luci::CircleRsqrtGraphBuilder::validate(), luci::CircleScatterNdGraphBuilder::validate(), luci::CircleSegmentSumGraphBuilder::validate(), luci::CircleSelectGraphBuilder::validate(), luci::CircleSelectV2GraphBuilder::validate(), luci::CircleShapeGraphBuilder::validate(), luci::CircleSinGraphBuilder::validate(), luci::CircleSliceGraphBuilder::validate(), luci::CircleSoftmaxGraphBuilder::validate(), luci::CircleSpaceToDepthGraphBuilder::validate(), luci::CircleSparseToDenseGraphBuilder::validate(), luci::CircleSqrtGraphBuilder::validate(), luci::CircleSquareGraphBuilder::validate(), luci::CircleSquaredDifferenceGraphBuilder::validate(), luci::CircleSqueezeGraphBuilder::validate(), luci::CircleStridedSliceGraphBuilder::validate(), luci::CircleSubGraphBuilder::validate(), luci::CircleSumGraphBuilder::validate(), luci::CircleTanhGraphBuilder::validate(), luci::CircleTileGraphBuilder::validate(), luci::CircleTransposeGraphBuilder::validate(), luci::CircleUnidirectionalSequenceLSTMGraphBuilder::validate(), luci::CircleWhereGraphBuilder::validate(), and luci::CircleZerosLikeGraphBuilder::validate().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Import/GraphBuilder.h
compiler/luci/import/src/GraphBuilder.cpp