ONE - On-device Neural Engine: coco::KernelLayouts::Generic Class Reference
coco::KernelLayouts::Generic Class Reference final
Generic Kernel Layout.
#include <KernelLayouts.h>
Public Member Functions
const KernelLayout::ID * id (void) const override
Return the identifier of each layout.
const nncc::core::ADT::kernel::Shape & shape (void) const override
ElemID & at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col)
ElemID at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const override
void reorder (const nncc::core::ADT::kernel::Layout &l)
template<typename LayoutImpl >
void reorder (void)
Public Member Functions inherited from coco::KernelLayout
virtual ~KernelLayout ()=default
virtual const ID * id (void) const =0
Return the identifier of each layout.
virtual const nncc::core::ADT::kernel::Shape & shape (void) const =0
virtual ElemID at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const KernelLayout::ID * uid (void)
static std::unique_ptr< Generic > create (const nncc::core::ADT::kernel::Shape &shape)
Detailed Description
Generic Kernel Layout.
Definition at line 87 of file KernelLayouts.h.
Member Function Documentation
at() [1/2]
ElemID & coco::KernelLayouts::Generic::at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col)
Definition at line 122 of file KernelLayouts.cpp.
{
  return _content.at(l.offset(_shape, n, ch, row, col));
}
Referenced by reorder().
at() [2/2]
ElemID coco::KernelLayouts::Generic::at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::KernelLayout.
Definition at line 127 of file KernelLayouts.cpp.
{
  return _content.at(l.offset(_shape, n, ch, row, col));
}
create()
std::unique_ptr< Generic > coco::KernelLayouts::Generic::create (const nncc::core::ADT::kernel::Shape & shape) static
Definition at line 149 of file KernelLayouts.cpp.
{
  return std::unique_ptr<Generic>{new Generic{shape}};
}
References shape().
Referenced by coco::KernelObject::KernelObject().
id()
const KernelLayout::ID * coco::KernelLayouts::Generic::id (void) const inline override virtual
Return the identifier of each layout.
REQUIRED
Given l1 and l2 of KernelLayout * type, typeid(*l1) == typeif(*l2) SHOULD hold if l1->id() == l2->id() holds.
Implements coco::KernelLayout.
Definition at line 94 of file KernelLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
reorder() [1/2]
void coco::KernelLayouts::Generic::reorder (const nncc::core::ADT::kernel::Layout & l)
Definition at line 132 of file KernelLayouts.cpp.
{
  for (uint32_t n = 0; n < shape().count(); ++n)
  {
    for (uint32_t ch = 0; ch < shape().depth(); ++ch)
    {
      for (uint32_t row = 0; row < shape().height(); ++row)
      {
        for (uint32_t col = 0; col < shape().width(); ++col)
        {
          at(n, ch, row, col) = ElemID{l.offset(shape(), n, ch, row, col)};
        }
      }
    }
  }
}
References at(), nncc::core::ADT::kernel::Shape::count(), nncc::core::ADT::kernel::Shape::depth(), nncc::core::ADT::kernel::Shape::height(), shape(), and nncc::core::ADT::kernel::Shape::width().
reorder() [2/2]
template<typename LayoutImpl > void coco::KernelLayouts::Generic::reorder (void) inline
Definition at line 102 of file KernelLayouts.h.
{ reorder(LayoutImpl{}); }
References reorder().
Referenced by reorder().
shape()
const nncc::core::ADT::kernel::Shape & coco::KernelLayouts::Generic::shape (void) const inline override virtual
Implements coco::KernelLayout.
Definition at line 96 of file KernelLayouts.h.
{ return _shape; }
Referenced by create(), and reorder().
uid()
const KernelLayout::ID * coco::KernelLayouts::Generic::uid (void) static
Definition at line 113 of file KernelLayouts.cpp.
{
  struct LayoutID final : public KernelLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/KernelLayouts.h
compiler/coco/core/src/IR/KernelLayouts.cpp