ONE - On-device Neural Engine: nnc::ArtifactGeneratorCppDecl Class Reference
nnc::ArtifactGeneratorCppDecl Class Reference
The ACL C++ artifact header file producer.
#include <ArtifactGeneratorCppDecl.h>
Public Member Functions
ArtifactGeneratorCppDecl (std::ostream &out)
void visit (const ArtifactLiteral *node) override
void visit (const ArtifactId *node) override
void visit (const ArtifactRef *node) override
void visit (const ArtifactDeref *node) override
void visit (const ArtifactVariable *node) override
void visit (const ArtifactFunctionCall *node) override
void visit (const ArtifactUnaryExpr *node) override
void visit (const ArtifactBinaryExpr *node) override
void visit (const ArtifactIndex *node) override
void visit (const ArtifactRet *node) override
void visit (const ArtifactBreak *node) override
void visit (const ArtifactCont *node) override
void visit (const ArtifactBlock *node) override
void visit (const ArtifactForLoop *node) override
void visit (const ArtifactIf *node) override
void visit (const ArtifactFunction *node) override
void visit (const ArtifactClass *node) override
void visit (const ArtifactClassVariable *node) override
void visit (const ArtifactClassFunction *node) override
void visit (const ArtifactModule *node) override
Public Member Functions inherited from nnc::IArtifactGenerator
virtual ~IArtifactGenerator ()=default
virtual void visit (const ArtifactLiteral *node)=0
virtual void visit (const ArtifactId *node)=0
virtual void visit (const ArtifactRef *node)=0
virtual void visit (const ArtifactDeref *node)=0
virtual void visit (const ArtifactVariable *node)=0
virtual void visit (const ArtifactFunctionCall *node)=0
virtual void visit (const ArtifactUnaryExpr *node)=0
virtual void visit (const ArtifactBinaryExpr *node)=0
virtual void visit (const ArtifactIndex *node)=0
virtual void visit (const ArtifactRet *node)=0
virtual void visit (const ArtifactBreak *node)=0
virtual void visit (const ArtifactCont *node)=0
virtual void visit (const ArtifactBlock *node)=0
virtual void visit (const ArtifactForLoop *node)=0
virtual void visit (const ArtifactIf *node)=0
virtual void visit (const ArtifactFunction *node)=0
virtual void visit (const ArtifactClass *node)=0
virtual void visit (const ArtifactClassVariable *node)=0
virtual void visit (const ArtifactClassFunction *node)=0
virtual void visit (const ArtifactModule *node)=0
Detailed Description
The ACL C++ artifact header file producer.
Definition at line 31 of file ArtifactGeneratorCppDecl.h.
Constructor & Destructor Documentation
ArtifactGeneratorCppDecl()
nnc::ArtifactGeneratorCppDecl::ArtifactGeneratorCppDecl (std::ostream & out) explicit
Definition at line 27 of file ArtifactGeneratorCppDecl.cpp.
: _out(out) {}
Member Function Documentation
visit() [1/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactBinaryExpr * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 54 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [2/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactBlock * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 64 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [3/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactBreak * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 60 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [4/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactClass * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 88 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << "class " << node->name() << " {" << endl;
  _out << "public:" << endl;
  ++_ind;
  // Generate a public default constructor here.
  _out << _ind << node->name() << "();" << endl;
  // Then generate the other stuff.
  for (const auto &e : node->publicFunctions())
  {
    _out << _ind;
    e->accept(this);
  }
  _out << endl << "private:" << endl;
  for (const auto &e : node->privateFunctions())
  {
    _out << _ind;
    e->accept(this);
  }
  if (!node->privateFunctions().empty())
    _out << endl;
  // TODO add public variables
  for (const auto &e : node->privateVariables())
  {
    _out << _ind;
    e->accept(this);
  }
  --_ind;
  _out << "};" << endl;
}
References nnc::ArtifactNamed::name(), nnc::ArtifactClass::privateFunctions(), nnc::ArtifactClass::privateVariables(), and nnc::ArtifactClass::publicFunctions().
visit() [5/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactClassFunction * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 133 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << node->getRetTypeName();
  if (!node->getRetTypeName().empty())
    _out << " ";
  _out << node->name() << "(";
  bool add_comma = false;
  for (const auto &p : node->getParameters())
  {
    if (add_comma)
      _out << ", ";
    p->accept(this);
    add_comma = true;
  }
  _out << ");" << endl;
}
References nnc::ArtifactFunction::getParameters(), nnc::ArtifactFunction::getRetTypeName(), and nnc::ArtifactNamed::name().
visit() [6/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactClassVariable * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 128 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << node->typeName() << " " << node->name() << ";" << endl;
}
References nnc::ArtifactNamed::name(), and nnc::ArtifactVariable::typeName().
visit() [7/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactCont * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 62 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [8/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactDeref * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 39 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << "*";
  node->obj()->accept(this);
}
References nnc::ArtifactDeref::obj().
visit() [9/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactForLoop * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 66 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [10/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactFunction * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 70 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << node->getRetTypeName() << " " << node->name() << "(";
  bool add_comma = false;
  for (const auto &par : node->getParameters())
  {
    if (add_comma)
      _out << ", ";
    par->accept(this);
    add_comma = true;
  }
  _out << ");";
}
References nnc::ArtifactFunction::getParameters(), nnc::ArtifactFunction::getRetTypeName(), and nnc::ArtifactNamed::name().
visit() [11/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactFunctionCall * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 50 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [12/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactId * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 31 of file ArtifactGeneratorCppDecl.cpp.
{ _out << node->name(); }
References nnc::ArtifactId::name().
visit() [13/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactIf * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 68 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [14/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactIndex * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 56 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [15/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactLiteral * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 29 of file ArtifactGeneratorCppDecl.cpp.
{ _out << node->getValue(); }
References nnc::ArtifactLiteral::getValue().
visit() [16/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactModule * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 155 of file ArtifactGeneratorCppDecl.cpp.
{
  for (const auto &i : node->headerSysIncludes())
    _out << "#include <" << i << ">" << endl;
  if (!node->headerSysIncludes().empty())
    _out << endl;
  for (const auto &i : node->headerIncludes())
    _out << "#include \"" << i << "\"" << endl;
  if (!node->headerIncludes().empty())
    _out << endl;
  for (const auto &e : node->entities())
    e->accept(this);
}
References nnc::ArtifactModule::entities(), nnc::ArtifactModule::headerIncludes(), and nnc::ArtifactModule::headerSysIncludes().
visit() [17/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactRef * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 33 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << "&";
  node->obj()->accept(this);
}
References nnc::ArtifactRef::obj().
visit() [18/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactRet * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 58 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [19/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactUnaryExpr * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 52 of file ArtifactGeneratorCppDecl.cpp.
{}
visit() [20/20]
void nnc::ArtifactGeneratorCppDecl::visit (const ArtifactVariable * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 45 of file ArtifactGeneratorCppDecl.cpp.
{
  _out << node->typeName() << " " << node->name();
}
References nnc::ArtifactNamed::name(), and nnc::ArtifactVariable::typeName().
The documentation for this class was generated from the following files:
compiler/nnc/backends/acl_soft_backend/ArtifactGeneratorCppDecl.h
compiler/nnc/backends/acl_soft_backend/ArtifactGeneratorCppDecl.cpp