ONE - On-device Neural Engine: onert::util::ObjectManager< Index, Object > Class Template Reference
onert::util::ObjectManager< Index, Object > Class Template Reference
Class that owns objects and maps them with indices as a handle for them.
#include <ObjectManager.h>
Public Member Functions
ObjectManager ()
template<class... Args>
Index emplace (Args &&... args)
Create an object with args and put it in the container with a newly assigned Index.
Index push (std::unique_ptr< Object > &&object, Index index)
Put the object in the container with given index.
Index push (std::unique_ptr< Object > &&object)
Put the object in the container with a newly assigned index.
Index set (Index index, std::unique_ptr< Object > &&object)
Set the object in the container with given index.
void remove (const Index &index)
Remove the object that is associated with the given index.
const Object & at (const Index &index) const
Get the object that is associated with the given index.
Object & at (const Index &index)
Get the object that is associated with the given index.
const Object * getRawPtr (const Index &index) const
Get the object that is associated with the given index.
Object * getRawPtr (const Index &index)
Get the object that is associated with the given index.
bool exist (const Index &index) const
Get the object that is associated with the given index.
size_t size () const
Return the number of objects that the manager contains.
void iterate (const std::function< void(const Index &, const Object &)> &fn) const
Iterate over the container with given function.
void iterate (const std::function< void(const Index &, Object &)> &fn)
Iterate over the container with given function.
Protected Attributes
std::unordered_map< Index, std::unique_ptr< Object > > _objects
uint32_t _next_index
Detailed Description
template<typename Index, typename Object>
class onert::util::ObjectManager< Index, Object >
Class that owns objects and maps them with indices as a handle for them.
Definition at line 37 of file ObjectManager.h.
Constructor & Destructor Documentation
ObjectManager()
template<typename Index , typename Object > onert::util::ObjectManager< Index, Object >::ObjectManager () inline
Definition at line 40 of file ObjectManager.h.
: _next_index{0u} {}
Member Function Documentation
at() [1/2]
template<typename Index , typename Object > Object & onert::util::ObjectManager< Index, Object >::at (const Index & index) inline
Get the object that is associated with the given index.
If such object does not exist, it will throw std::out_of_range
Parameters
[in] index Index of the object to be returned
Returns
Object
Definition at line 130 of file ObjectManager.h.
{ return *(_objects.at(index)); }
References onert::util::ObjectManager< Index, Object >::_objects.
at() [2/2]
template<typename Index , typename Object > const Object & onert::util::ObjectManager< Index, Object >::at (const Index & index) const inline
Get the object that is associated with the given index.
If such object does not exist, it will throw std::out_of_range
Parameters
[in] index Index of the object to be returned
Returns
Object
Definition at line 121 of file ObjectManager.h.
{ return *(_objects.at(index)); }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::exec::DataflowExecutor::calculateRank(), onert::compiler::pass::ConstantOutputPass::callback(), onert::compiler::pass::PermutationInsertionPass::callback(), onert::compiler::pass::ConstantInsertionPass::callback(), onert::compiler::pass::ConstantLoweringPass::callback(), onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), onert::backend::gpu_cl::ClConstantInitializer::copyInputInitialize(), onert::interp::OperationExecutor::execute(), onert::backend::acl_cl::KernelGenerator::generate(), onert::backend::acl_neon::KernelGenerator::generate(), onert::backend::gpu_cl::KernelGenerator::generate(), onert::backend::ruy::KernelGenerator::generate(), onert::backend::builtin::KernelGenerator::generate(), onert::backend::trix::KernelGenerator::generate(), onert::exec::TracingObserver::handleJobBegin(), onert::exec::ProfileObserver::handleJobEnd(), onert::exec::TracingObserver::handleJobEnd(), onert::compiler::StaticShapeInferer::infer(), onert::exec::SingleModelExecutors::inputInfo(), onert::backend::acl_common::kernelGenFullyConnected(), onert::backend::acl_common::kernelGenLSTM(), onert::backend::acl_common::kernelGenPool2D(), onert::base_loader::BaseLoader< LoaderDomain >::loadOperand(), onert::exec::SingleModelExecutors::outputInfo(), onert::backend::acl_common::AclConstantInitializer::permuteInputInitialize(), onert::backend::gpu_cl::ClConstantInitializer::permuteInputInitialize(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), onert::interp::conv2d::prepareConv2D(), onert::interp::pool2d::preparePool2D(), onert::backend::gpu_cl::TensorBuilder::registerTensorInfo(), onert::backend::acl_common::AclConstantInitializer::run(), onert::compiler::pass::OddOutputPass::run(), onert::ir::Graph::setOperandValue(), onert::ir::Graph::topolSortOperations(), onert::backend::acl_common::AclConstantInitializer::visit(), onert::backend::acl_common::AclSubTensorAnalyzer::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), onert::backend::acl_neon::ConstantInitializer::visit(), and onert::ir::OperationValidator::visit().
emplace()
template<typename Index , typename Object > template<class... Args> Index onert::util::ObjectManager< Index, Object >::emplace (Args &&... args) inline
Create an object with args and put it in the container with a newly assigned Index.
Parameters
[in] args Arguments for creating Operand object
Returns
Created index that is associated to the object if successful, Undefined index otherwise
Definition at line 49 of file ObjectManager.h.
  {
    auto index = generateIndex();
    if (!index.valid())
      return index;
    _objects.emplace(index, std::make_unique<Object>(std::forward<Args>(args)...));
    return index;
  }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::ir::Graph::addOperand(), and onert::compiler::pass::ConstantInsertionPass::callback().
exist()
template<typename Index , typename Object > bool onert::util::ObjectManager< Index, Object >::exist (const Index & index) const inline
Get the object that is associated with the given index.
Parameters
[in] index Index of the object to be returned
Returns
true if such entry exists otherwise false
Definition at line 169 of file ObjectManager.h.
  {
    auto it = _objects.find(index);
    return it != _objects.end();
  }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::ir::Graph::setOperandValue().
getRawPtr() [1/2]
template<typename Index , typename Object > Object * onert::util::ObjectManager< Index, Object >::getRawPtr (const Index & index) inline
Get the object that is associated with the given index.
If such object does not exist, it will return nullptr
Parameters
[in] index Index of the object to be returned
Returns
Object The found object
Definition at line 158 of file ObjectManager.h.
  {
    return const_cast<Object *>(
      const_cast<const ObjectManager<Index, Object> *>(this)->getRawPtr(index));
  }
References onert::util::ObjectManager< Index, Object >::getRawPtr().
getRawPtr() [2/2]
template<typename Index , typename Object > const Object * onert::util::ObjectManager< Index, Object >::getRawPtr (const Index & index) const inline
Get the object that is associated with the given index.
If such object does not exist, it will return nullptr
Parameters
[in] index Index of the object to be returned
Returns
Object
Definition at line 139 of file ObjectManager.h.
  {
    auto itr = _objects.find(index);
    if (itr == _objects.end())
      return nullptr;
    else
    {
      assert(itr->second != nullptr);
      return itr->second.get();
    }
  }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::util::ObjectManager< Index, Object >::getRawPtr().
iterate() [1/2]
template<typename Index , typename Object > void onert::util::ObjectManager< Index, Object >::iterate (const std::function< void(const Index &, const Object &)> & fn) const inline
Iterate over the container with given function.
Parameters
[in] fn Function to be run for every container entry
Returns
N/A
Definition at line 186 of file ObjectManager.h.
  {
    for (const auto &e : _objects)
    {
      fn(e.first, *e.second);
    }
  }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::compiler::StaticShapeInferer::dump(), onert::interp::InterpExecutor::execute(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::backend::basic::initConsts(), onert::compiler::ShapeValidator::operator()(), onert::ir::OperationValidator::operator()(), onert::backend::acl_cl::Optimizer::optimize(), onert::backend::acl_neon::Optimizer::optimize(), onert::compiler::pass::OperationPass::run(), onert::compiler::pass::UnusedOperandEliminationPass::run(), onert::compiler::pass::OperandPass::run(), onert::compiler::HEScheduler::schedule(), and onert::ir::Graph::topolSortOperations().
iterate() [2/2]
template<typename Index , typename Object > void onert::util::ObjectManager< Index, Object >::iterate (const std::function< void(const Index &, Object &)> & fn) inline
Iterate over the container with given function.
Parameters
[in] fn Function to be run for every container entry
Returns
N/A
Definition at line 199 of file ObjectManager.h.
  {
    // TODO Remove this workaround
    // This implementation is a workaround in case of adding operands while iteration
    std::list<Index> l;
    for (auto &e : _objects)
    {
      l.push_back(e.first);
    }
    for (auto &index : l)
    {
      fn(index, *_objects[index]);
    }
  }
References onert::util::ObjectManager< Index, Object >::_objects.
push() [1/2]
template<typename Index , typename Object > Index onert::util::ObjectManager< Index, Object >::push (std::unique_ptr< Object > && object) inline
Put the object in the container with a newly assigned index.
It fails when it cannot generate a valid index.
Parameters
[in] object Object to be pushed
Returns
The newly assigned index if successful, an Undefined index otherwise
Definition at line 82 of file ObjectManager.h.
  {
    auto gen_index = generateIndex();
    if (gen_index.valid())
      _objects.emplace(gen_index, std::move(object));
    return gen_index;
  }
References onert::util::ObjectManager< Index, Object >::_objects.
push() [2/2]
template<typename Index , typename Object > Index onert::util::ObjectManager< Index, Object >::push (std::unique_ptr< Object > && object, Index index) inline
Put the object in the container with given index.
It fails when the given index is already taken or index is Undefined.
Parameters
[in] object Object to be pushed
[in] index Index associated with the object
Returns
index if successful, an Undefined index otherwise
Definition at line 67 of file ObjectManager.h.
  {
    auto gen_index = tryIndex(index);
    if (gen_index.valid())
      _objects.emplace(gen_index, std::move(object));
    return gen_index;
  }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::ir::Graph::addOperand(), onert::ir::Graph::addOperation(), and onert::compiler::pass::ConstantOutputPass::callback().
remove()
template<typename Index , typename Object > void onert::util::ObjectManager< Index, Object >::remove (const Index & index) inline
Remove the object that is associated with the given index.
Parameters
[in] index Index of the object to be removed
Returns
N/A
Definition at line 111 of file ObjectManager.h.
{ _objects.erase(index); }
References onert::util::ObjectManager< Index, Object >::_objects.
Referenced by onert::ir::Graph::removeOperand().
set()
template<typename Index , typename Object > Index onert::util::ObjectManager< Index, Object >::set (Index index, std::unique_ptr< Object > && object) inline
Set the object in the container with given index.
If the index is Undefined, it will fail. If the index is already taken, it will overwrite the content.
Parameters
[in] object Object to be pushed
[in] index Index associated with the object
Returns
index if successful, an Undefined index otherwise
Definition at line 99 of file ObjectManager.h.
  {
    if (index.valid())
      _objects[index] = std::move(object);
    return index;
  }
References onert::util::ObjectManager< Index, Object >::_objects.
size()
template<typename Index , typename Object > size_t onert::util::ObjectManager< Index, Object >::size () const inline
Return the number of objects that the manager contains.
Returns
size_t Number of objects
Definition at line 179 of file ObjectManager.h.
{ return _objects.size(); }
References onert::util::ObjectManager< Index, Object >::_objects.
Field Documentation
_next_index
template<typename Index , typename Object > uint32_t onert::util::ObjectManager< Index, Object >::_next_index protected
Definition at line 249 of file ObjectManager.h.
_objects
template<typename Index , typename Object > std::unordered_map<Index, std::unique_ptr<Object> > onert::util::ObjectManager< Index, Object >::_objects protected
Definition at line 248 of file ObjectManager.h.
Referenced by onert::util::ObjectManager< Index, Object >::at(), onert::util::ObjectManager< Index, Object >::emplace(), onert::util::ObjectManager< Index, Object >::exist(), onert::util::ObjectManager< Index, Object >::getRawPtr(), onert::util::ObjectManager< Index, Object >::iterate(), onert::util::ObjectManager< Index, Object >::push(), onert::util::ObjectManager< Index, Object >::remove(), onert::util::ObjectManager< Index, Object >::set(), and onert::util::ObjectManager< Index, Object >::size().
The documentation for this class was generated from the following file:
runtime/onert/core/include/util/ObjectManager.h