ONE - On-device Neural Engine: luci_interpreter::KernelBuilder Class Reference
luci_interpreter::KernelBuilder Class Reference
#include <KernelBuilder.h>
Public Member Functions
KernelBuilder (const std::unordered_map< const loco::Graph *, RuntimeGraph * > &graph_to_runtime_graph, const std::unordered_map< const loco::Node *, Tensor * > &node_to_tensor)
~KernelBuilder ()
std::unique_ptr< Kernel > build (const luci::CircleNode *node)
KernelBuilder (IBaseRuntimeGraph *runtime_graph, CircleReader *circle_reader)
~KernelBuilder ()
std::unique_ptr< Kernel > build (std::vector< const Tensor * > &&inputs, std::vector< Tensor * > &&output, const circle::BuiltinOperator opcode, const int32_t op_index)
CircleReader * get_circle_reader ()
IBaseRuntimeGraph * get_runtime_graph ()
Public Member Functions inherited from luci_interpreter::KernelBuilderHelper
KernelBuilderHelper (const std::unordered_map< const loco::Graph *, RuntimeGraph * > &graph_to_runtime_graph, const std::unordered_map< const loco::Node *, Tensor * > &node_to_tensor)
const Tensor * getInputTensor (const loco::Node *node) const
const Tensor * getOptionalInputTensor (const loco::Node *node) const
Tensor * getOutputTensor (const loco::Node *node) const
std::vector< Tensor * > getOutputTensors (const std::vector< const loco::Node * > &nodes) const
RuntimeGraph * getRuntimeGraph (const loco::Graph *graph) const
const std::unordered_map< const loco::Graph *, RuntimeGraph * > & graph_to_runtime_graph () const
const std::unordered_map< const loco::Node *, Tensor * > & node_to_tensor () const
Detailed Description
Definition at line 35 of file KernelBuilder.h.
Constructor & Destructor Documentation
KernelBuilder() [1/2]
luci_interpreter::KernelBuilder::KernelBuilder (const std::unordered_map< const loco::Graph *, RuntimeGraph * > & graph_to_runtime_graph, const std::unordered_map< const loco::Node *, Tensor * > & node_to_tensor)
Definition at line 107 of file KernelBuilder.cpp.
  : KernelBuilderHelper(graph_to_runtime_graph, node_to_tensor)
{
  _builder_registry = std::make_unique<KernelBuilderRegistry>();
}
~KernelBuilder() [1/2]
luci_interpreter::KernelBuilder::~KernelBuilder ()
Definition at line 115 of file KernelBuilder.cpp.
{
  // Need to define in this CPP to hide KernelBuilderRegistry internals.
  // This destructor deletes _builder_registry
}
KernelBuilder() [2/2]
luci_interpreter::KernelBuilder::KernelBuilder (IBaseRuntimeGraph * runtime_graph, CircleReader * circle_reader)
Definition at line 76 of file KernelBuilder.cpp.
  : _runtime_graph(runtime_graph), _circle_reader(circle_reader)
{
  _builder_registry = std::make_unique<KernelBuilderRegistry>();
}
~KernelBuilder() [2/2]
luci_interpreter::KernelBuilder::~KernelBuilder ()
Member Function Documentation
build() [1/2]
std::unique_ptr< Kernel > luci_interpreter::KernelBuilder::build (const luci::CircleNode * node)
Definition at line 121 of file KernelBuilder.cpp.
{
  auto specific_builder = _builder_registry->get_kernel_builder_func(node->opcode());
  if (specific_builder != nullptr)
    return specific_builder(node, *this);
  std::string msg = "Unsupported operator: ";
  msg += toString(node->opcode()) + " in " + std::string(node->name());
  throw std::invalid_argument(msg.c_str());
}
References luci::CircleNode::name(), and luci::CircleNode::opcode().
Referenced by luci_interpreter::GraphLoader::loadOperators().
build() [2/2]
std::unique_ptr< Kernel > luci_interpreter::KernelBuilder::build (std::vector< const Tensor * > && inputs, std::vector< Tensor * > && output, const circle::BuiltinOperator opcode, const int32_t op_index)
Definition at line 88 of file KernelBuilder.cpp.
{
  auto specific_builder = _builder_registry->get_kernel_builder_func(opcode);
  if (specific_builder != nullptr)
    return specific_builder(std::move(inputs), std::move(outputs), op_index, *this);
  assert(false && "Unsupported operator");
}
get_circle_reader()
CircleReader * luci_interpreter::KernelBuilder::get_circle_reader () inline
Definition at line 44 of file KernelBuilder.h.
{ return _circle_reader; }
Referenced by luci_interpreter::build_kernel_CircleAdd(), luci_interpreter::build_kernel_CircleArgMax(), luci_interpreter::build_kernel_CircleAveragePool2D(), luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleConcatenation(), luci_interpreter::build_kernel_CircleConv2D(), luci_interpreter::build_kernel_CircleDepthToSpace(), luci_interpreter::build_kernel_CircleDepthwiseConv2D(), luci_interpreter::build_kernel_CircleDiv(), luci_interpreter::build_kernel_CircleFullyConnected(), luci_interpreter::build_kernel_CircleGather(), luci_interpreter::build_kernel_CircleInstanceNorm(), luci_interpreter::build_kernel_CircleL2Normalize(), luci_interpreter::build_kernel_CircleL2Pool2D(), luci_interpreter::build_kernel_CircleLeakyRelu(), luci_interpreter::build_kernel_CircleLocalResponseNormalization(), luci_interpreter::build_kernel_CircleMaxPool2D(), luci_interpreter::build_kernel_CircleMean(), luci_interpreter::build_kernel_CircleMirrorPad(), luci_interpreter::build_kernel_CircleMul(), luci_interpreter::build_kernel_CircleOneHot(), luci_interpreter::build_kernel_CirclePack(), luci_interpreter::build_kernel_CircleResizeBilinear(), luci_interpreter::build_kernel_CircleResizeNearestNeighbor(), luci_interpreter::build_kernel_CircleShape(), luci_interpreter::build_kernel_CircleSoftmax(), luci_interpreter::build_kernel_CircleSpaceToDepth(), luci_interpreter::build_kernel_CircleSqueeze(), luci_interpreter::build_kernel_CircleStridedSlice(), luci_interpreter::build_kernel_CircleSub(), luci_interpreter::build_kernel_CircleSVDF(), luci_interpreter::build_kernel_CircleTransposeConv(), and luci_interpreter::build_kernel_CircleUnpack().
get_runtime_graph()
IBaseRuntimeGraph * luci_interpreter::KernelBuilder::get_runtime_graph () inline
Definition at line 46 of file KernelBuilder.h.
{ return _runtime_graph; }
Referenced by luci_interpreter::build_kernel_CircleAveragePool2D(), luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleConv2D(), luci_interpreter::build_kernel_CircleDepthwiseConv2D(), luci_interpreter::build_kernel_CircleMean(), luci_interpreter::build_kernel_CircleSVDF(), and luci_interpreter::build_kernel_CircleTransposeConv().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/loader/KernelBuilder.h
onert-micro/luci-interpreter/src/loader/KernelBuilder.h
compiler/luci-interpreter/src/loader/KernelBuilder.cpp
onert-micro/luci-interpreter/src/loader/KernelBuilder.cpp