ONE - On-device Neural Engine: luci_interpreter::kernels::Div Class Reference
luci_interpreter::kernels::Div Class Reference
#include <Div.h>
Public Member Functions
Div (const Tensor *input1, const Tensor *input2, Tensor *output, const DivParams &params)
const Tensor * input1 () const
const Tensor * input2 () const
Tensor * output () const
void configure () override
void execute () const override
Div (const Tensor *input1, const Tensor *input2, Tensor *output, const DivParams &params)
const Tensor * input1 () const
const Tensor * input2 () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< DivParams >
const DivParams & params () const
const DivParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< DivParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const DivParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const DivParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< DivParams >
const DivParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Div.h.
Constructor & Destructor Documentation
Div() [1/2]
luci_interpreter::kernels::Div::Div (const Tensor * input1, const Tensor * input2, Tensor * output, const DivParams & params)
Definition at line 29 of file Div.cpp.
  : KernelWithParams<DivParams>({input1, input2}, {output}, params)
{
}
References input1(), and input2().
Div() [2/2]
luci_interpreter::kernels::Div::Div (const Tensor * input1, const Tensor * input2, Tensor * output, const DivParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Div::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 34 of file Div.cpp.
{
  LUCI_INTERPRETER_CHECK(input1()->element_type() == input2()->element_type());
  LUCI_INTERPRETER_CHECK(input1()->element_type() == output()->element_type());
  output()->resize(calculateShapeForBroadcast(input1()->shape(), input2()->shape()));
}
References luci_interpreter::kernels::calculateShapeForBroadcast(), input1(), input2(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::Div::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Div::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 42 of file Div.cpp.
{
  switch (input1()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::S64:
      evalInteger<int64_t>();
      break;
    case DataType::S32:
      evalInteger<int32_t>();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input1().
execute() [2/2]
void luci_interpreter::kernels::Div::execute () const override virtual
Implements luci_interpreter::Kernel.
input1() [1/2]
const Tensor * luci_interpreter::kernels::Div::input1 () const inline
Definition at line 33 of file Div.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), Div(), and execute().
input1() [2/2]
const Tensor * luci_interpreter::kernels::Div::input1 () const inline
Definition at line 33 of file Div.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
input2() [1/2]
const Tensor * luci_interpreter::kernels::Div::input2 () const inline
Definition at line 34 of file Div.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Div().
input2() [2/2]
const Tensor * luci_interpreter::kernels::Div::input2 () const inline
Definition at line 34 of file Div.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Div::output () const inline
Definition at line 35 of file Div.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Div::output () const inline
Definition at line 35 of file Div.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Div.h
onert-micro/luci-interpreter/src/kernels/Div.h
compiler/luci-interpreter/src/kernels/Div.cpp
onert-micro/luci-interpreter/src/kernels/Div.cpp