ONE - On-device Neural Engine: luci_interpreter::kernels::AveragePool2D Class Reference
luci_interpreter::kernels::AveragePool2D Class Reference
#include <AveragePool2D.h>
Public Member Functions
AveragePool2D (const Tensor *input, Tensor *output, Tensor *scratchpad, const Pool2DParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
AveragePool2D (const Tensor *input, Tensor *output, Tensor *scratchpad, const Pool2DParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< Pool2DParams >
const Pool2DParams & params () const
const Pool2DParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< Pool2DParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const Pool2DParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const Pool2DParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< Pool2DParams >
const Pool2DParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file AveragePool2D.h.
Constructor & Destructor Documentation
AveragePool2D() [1/2]
luci_interpreter::kernels::AveragePool2D::AveragePool2D (const Tensor * input, Tensor * output, Tensor * scratchpad, const Pool2DParams & params)
Definition at line 31 of file AveragePool2D.cpp.
  : KernelWithParams<Pool2DParams>({input}, {output, scratchpad}, params)
{
}
References input().
AveragePool2D() [2/2]
luci_interpreter::kernels::AveragePool2D::AveragePool2D (const Tensor * input, Tensor * output, Tensor * scratchpad, const Pool2DParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::AveragePool2D::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file AveragePool2D.cpp.
{
  if (input()->element_type() != output()->element_type())
  {
    throw std::runtime_error("Input Tensor and Output Tensor Type must be same");
  }
  if (input()->shape().num_dims() != 4)
  {
    throw std::runtime_error("Input Tensor Shape must be 4-D");
  }
  const Shape &input_shape = input()->shape();
  const int32_t batches = input_shape.dim(0);
  const int32_t input_height = input_shape.dim(1);
  const int32_t input_width = input_shape.dim(2);
  const int32_t depth = input_shape.dim(3);
  const int32_t output_height =
    computeOutputSize(_params.padding, input_height, _params.filter_height, _params.stride_height);
  const int32_t output_width =
    computeOutputSize(_params.padding, input_width, _params.filter_width, _params.stride_width);
  _padding_height =
    computePadding(_params.stride_height, 1, input_height, _params.filter_height, output_height);
  _padding_width =
    computePadding(_params.stride_width, 1, input_width, _params.filter_width, output_width);
  if (input()->element_type() == DataType::U8)
  {
    LUCI_INTERPRETER_CHECK(std::abs(output()->scale() - input()->scale()) <= 1.0e-6);
    LUCI_INTERPRETER_CHECK(output()->zero_point() == input()->zero_point());
  }
  else if (input()->element_type() == DataType::S16)
  {
    LUCI_INTERPRETER_CHECK(std::abs(output()->scale() - input()->scale()) <= 1.0e-6);
    LUCI_INTERPRETER_CHECK(input()->zero_point() == 0 && output()->zero_point() == 0);
  }
  else if (input()->element_type() == DataType::S8)
  {
    LUCI_INTERPRETER_CHECK(std::abs(output()->scale() - input()->scale()) <= 1.0e-6);
    LUCI_INTERPRETER_CHECK(output()->zero_point() == input()->zero_point());
  }
  output()->resize({batches, output_height, output_width, depth});
  auto scratchpad = getOutputTensors()[1];
  luci_interpreter_pal::SetupScratchpadTensor(scratchpad, input()->element_type(),
                                              getTensorShape(input()), getTensorShape(output()));
}
References luci_interpreter::KernelWithParams< Pool2DParams >::_params, luci_interpreter::kernels::computeOutputSize(), luci_interpreter::kernels::computePadding(), luci_interpreter::Shape::dim(), luci_interpreter::Pool2DParams::filter_height, luci_interpreter::Pool2DParams::filter_width, luci_interpreter::Kernel::getOutputTensors(), luci_interpreter::kernels::getTensorShape(), input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::Pool2DParams::padding, luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), luci_interpreter::Pool2DParams::stride_height, and luci_interpreter::Pool2DParams::stride_width.
configure() [2/2]
void luci_interpreter::kernels::AveragePool2D::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::AveragePool2D::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 85 of file AveragePool2D.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    case DataType::S16:
      evalSInt16();
      break;
    case DataType::S8:
      evalSInt8();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::AveragePool2D::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::AveragePool2D::input () const inline
Definition at line 34 of file AveragePool2D.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by AveragePool2D(), configure(), and execute().
input() [2/2]
const Tensor * luci_interpreter::kernels::AveragePool2D::input () const inline
Definition at line 34 of file AveragePool2D.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::AveragePool2D::output () const inline
Definition at line 35 of file AveragePool2D.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::AveragePool2D::output () const inline
Definition at line 35 of file AveragePool2D.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/AveragePool2D.h
onert-micro/luci-interpreter/src/kernels/AveragePool2D.h
compiler/luci-interpreter/src/kernels/AveragePool2D.cpp
onert-micro/luci-interpreter/src/kernels/AveragePool2D.cpp