ONE - On-device Neural Engine: exo::test::TestGraph Class Reference
exo::test::TestGraph Class Reference
#include <TestGraph.h>
Public Member Functions
TestGraph ()
loco::Graph * graph ()
template<class T >
T * append ()
Creates node with NO arg and appends it to graph.
template<class T >
T * append (loco::Node *arg1)
Creates op T (arity=1) with arg1 as an input and appends it to graph.
template<class T >
T * append (loco::Node *arg1, loco::Node *arg2)
Creates op T (arity=2) with arg1, arg2 as inputs and appends it to graph.
template<class T >
T * append (loco::Node *arg1, loco::Node *arg2, loco::Node *arg3)
Creates op T (arity=3) with arg1, arg2, arg3 as inputs and appends it to graph.
void complete ()
void complete (loco::Node *last_node)
Data Fields
std::unique_ptr< loco::Graph > g
loco::Pull * pull
loco::Push * push
Detailed Description
Definition at line 33 of file TestGraph.h.
Constructor & Destructor Documentation
TestGraph()
exo::test::TestGraph::TestGraph () inline
Definition at line 40 of file TestGraph.h.
  {
    g = loco::make_graph();
    pull = g->nodes()->create<loco::Pull>();
    push = g->nodes()->create<loco::Push>();
    auto input = g->inputs()->create();
    {
      input->name("input");
      loco::link(input, pull);
    }
    auto output = g->outputs()->create();
    {
      output->name("output");
      loco::link(output, push);
    }
    _next_input = pull;
  }
References g, loco::link(), loco::make_graph(), pull, and push.
Member Function Documentation
append() [1/4]
template<class T > T * exo::test::TestGraph::append () inline
Creates node with NO arg and appends it to graph.
Definition at line 65 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    _next_input = node;
    return node;
  }
References g.
append() [2/4]
template<class T > T * exo::test::TestGraph::append (loco::Node * arg1) inline
Creates op T (arity=1) with arg1 as an input and appends it to graph.
Definition at line 74 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1);
    _next_input = node;
    return node;
  }
References g.
append() [3/4]
template<class T > T * exo::test::TestGraph::append (loco::Node * arg1, loco::Node * arg2) inline
Creates op T (arity=2) with arg1, arg2 as inputs and appends it to graph.
Definition at line 84 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1, arg2);
    _next_input = node;
    return node;
  }
References g.
append() [4/4]
template<class T > T * exo::test::TestGraph::append (loco::Node * arg1, loco::Node * arg2, loco::Node * arg3) inline
Creates op T (arity=3) with arg1, arg2, arg3 as inputs and appends it to graph.
Definition at line 94 of file TestGraph.h.
  {
    auto node = g->nodes()->create<T>();
    setInput(node, arg1, arg2, arg3);
    _next_input = node;
    return node;
  }
References g.
complete() [1/2]
void exo::test::TestGraph::complete () inline
Definition at line 104 of file TestGraph.h.
{ push->from(_next_input); }
References loco::Push::from(), and push.
complete() [2/2]
void exo::test::TestGraph::complete (loco::Node * last_node) inline
Definition at line 106 of file TestGraph.h.
{ push->from(last_node); }
References loco::Push::from(), and push.
graph()
loco::Graph * exo::test::TestGraph::graph () inline
Definition at line 62 of file TestGraph.h.
{ return g.get(); }
References g.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
g
std::unique_ptr<loco::Graph> exo::test::TestGraph::g
Definition at line 36 of file TestGraph.h.
Referenced by append(), graph(), and TestGraph().
pull
loco::Pull* exo::test::TestGraph::pull
Definition at line 37 of file TestGraph.h.
Referenced by TestGraph().
push
loco::Push* exo::test::TestGraph::push
Definition at line 38 of file TestGraph.h.
Referenced by complete(), and TestGraph().
The documentation for this class was generated from the following file:
compiler/exo/src/TestGraph.h