ONE - On-device Neural Engine: circletensordump::DumpTensors Class Reference
circletensordump::DumpTensors Class Reference final
#include <Dump.h>
Public Member Functions
DumpTensors ()=default
void run (std::ostream &os, const circle::Model *model, const std::string &) override
Public Member Functions inherited from circletensordump::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const circle::Model *model, const std::string &output_path={})=0
Detailed Description
Definition at line 37 of file Dump.h.
Constructor & Destructor Documentation
DumpTensors()
circletensordump::DumpTensors::DumpTensors () default
Member Function Documentation
run()
void circletensordump::DumpTensors::run (std::ostream & os, const circle::Model * model, const std::string &) override virtual
Implements circletensordump::DumpInterface.
Definition at line 104 of file Dump.cpp.
{
  mio::circle::Reader reader(model);
  uint32_t num_subgraph = reader.num_subgraph();
  auto buffers = reader.buffers();
  for (uint32_t subgraph_idx = 0; subgraph_idx < num_subgraph; subgraph_idx++)
  {
    reader.select_subgraph(subgraph_idx);
    auto tensors = reader.tensors();
    for (const auto &tensor : *tensors)
    {
      const auto tensor_name = tensor->name();
      std::string tensor_name_str = tensor_name ? tensor_name->str() : "no_name";
      os << std::string(70, '-') << std::endl;
      os << "[" << tensor_name_str << "]" << std::endl;
      auto buff_idx = tensor->buffer();
      auto buff_data_ptr = reader.buffers()->Get(buff_idx)->data();
      auto quant_param = tensor->quantization();
      std::string print_format = (!buff_data_ptr && !quant_param) ? "└──" : "├──";
      // shape
      auto shape = tensor->shape();
      os << " " + print_format + " shape : (";
      ::print_comma_sepearted(os, shape);
      os << ")" << std::endl;
      // quantization paramters
      if (quant_param)
      {
        std::string print_format1 = buff_data_ptr ? "├──" : "└──";
        std::string print_format2 = buff_data_ptr ? "│" : " ";
        os << " " + print_format1 + " quantization" << std::endl;
        auto min = quant_param->min();
        auto max = quant_param->max();
        auto scale = quant_param->scale();
        auto zero_point = quant_param->zero_point();
        auto quantized_dimension = quant_param->quantized_dimension();
        os << " " + print_format2 + "   ├── min        : ";
        ::print_comma_sepearted(os, min);
        os << std::endl;
        os << " " + print_format2 + "   ├── max        : ";
        ::print_comma_sepearted(os, max);
        os << std::endl;
        os << " " + print_format2 + "   ├── scale      : ";
        ::print_comma_sepearted(os, scale);
        os << std::endl;
        os << " " + print_format2 + "   ├── zero_point : ";
        ::print_comma_sepearted(os, zero_point);
        os << std::endl;
        os << " " + print_format2 + "   └── quantized_dimension : " << quantized_dimension;
        os << std::endl;
      }
      // buffer
      print_buffer(os, buff_idx, buff_data_ptr, tensor->type());
      os << std::endl;
    }
  }
}
References mio::circle::Reader::buffers(), mio::circle::Reader::num_subgraph(), mio::circle::Reader::select_subgraph(), and mio::circle::Reader::tensors().
The documentation for this class was generated from the following files:
compiler/circle-tensordump/src/Dump.h
compiler/circle-tensordump/src/Dump.cpp