ONE - On-device Neural Engine: onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor > Class Template Reference
onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor > Class Template Reference
#include <AclTensorBuilder.h>
Public Types
using T_AclTensorManager = AclTensorManager< T_ITensor, T_Tensor, T_SubTensor >
using UsesType = cl_common::UsesType
Public Member Functions
AclTensorBuilder (const ir::Operands &operands, T_AclTensorManager *tensor_mgr)
void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout)
Register tensor information to allocate on ACL-CL backend.
void notifyFirstUse (const ir::OperandIndex &)
void notifyLastUse (const ir::OperandIndex &)
bool isRegistered (const ir::OperandIndex &) const
void prepare (void)
void allocate ()
void postFunctionPrepare ()
T_AclTensorManager * acl_tensor_manager (void)
void setUsesCount (const ir::OperandIndex &index, size_t num_uses)
void parent_map (std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > &&parent_map)
bool areSubTensorsOf (const ir::OperandIndex &parent, const ir::OperandIndexSequence &seq)
bool isSubTensorOf (const ir::OperandIndex &parent, const ir::OperandIndex &child)
Check child tensor is allocated as subtensor of parent tensor.
Detailed Description
template<typename T_ITensor, typename T_Tensor, typename T_SubTensor>
class onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >
Definition at line 42 of file AclTensorBuilder.h.
Member Typedef Documentation
T_AclTensorManager
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > using onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::T_AclTensorManager = AclTensorManager<T_ITensor, T_Tensor, T_SubTensor>
Definition at line 45 of file AclTensorBuilder.h.
UsesType
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > using onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::UsesType = cl_common::UsesType
Definition at line 47 of file AclTensorBuilder.h.
Constructor & Destructor Documentation
AclTensorBuilder()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::AclTensorBuilder (const ir::Operands & operands, T_AclTensorManager * tensor_mgr)
Definition at line 131 of file AclTensorBuilder.h.
  : _operands{operands}, _tensor_mgr{tensor_mgr}
{
  assert(_tensor_mgr);
}
Member Function Documentation
acl_tensor_manager()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > T_AclTensorManager * onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::acl_tensor_manager (void) inline
Definition at line 69 of file AclTensorBuilder.h.
{ return _tensor_mgr.get(); }
allocate()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::allocate (void)
Definition at line 217 of file AclTensorBuilder.h.
{
  auto lifetime_map = cl_common::createLifetimeMap(_lifetime_seq, _parent_map);
  for (auto &entry : lifetime_map)
  {
    auto &use = entry.second;
    auto use_type = use.first;
    auto use_index = use.second;
    assert(use_index.valid());
    if (use_type == UsesType::FIRST)
      _tensor_mgr->startLifetime(use_index);
    else
      _tensor_mgr->finishLifetime(use_index);
  }
  _tensor_mgr->allocateConsts();
  // TODO Since `_parent_map` is filled for all Concat nodes even if the node this backend uses
  //      After refactoring BackendContext we can uncomment this
  // assert(_tensor_info_map.size() ==
  //       _tensor_mgr->nonconstTensors().size() + num of constants of _tensor_info_map +
  //       _parent_map.size());
  _tensor_mgr->allocateNonconsts();
  _tensor_mgr->allocateInternalBufferManager();
}
References onert::backend::cl_common::createLifetimeMap(), and entry().
areSubTensorsOf()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > bool onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::areSubTensorsOf (const ir::OperandIndex & parent, const ir::OperandIndexSequence & seq)
Definition at line 343 of file AclTensorBuilder.h.
{
  for (auto &cand : seq)
  {
    if (!isSubTensorOf(parent, cand))
    {
      return false;
    }
  }
  return true;
}
isRegistered()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > bool onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::isRegistered (const ir::OperandIndex & ind) const
Definition at line 204 of file AclTensorBuilder.h.
{
  return _tensor_info_map.find(ind) != _tensor_info_map.end();
}
isSubTensorOf()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > bool onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::isSubTensorOf (const ir::OperandIndex & parent, const ir::OperandIndex & child)
Check child tensor is allocated as subtensor of parent tensor.
Parameters
[in] parent Index of parent
[in] child Index of child
Returns
true if child is allocated as subtensor of parent, otherwise false
Definition at line 357 of file AclTensorBuilder.h.
{
  auto itr = _parent_map.find(child);
  if (itr == _parent_map.end())
  {
    return false;
  }
  return itr->second.parent == parent;
}
notifyFirstUse()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::notifyFirstUse (const ir::OperandIndex & ind)
Definition at line 192 of file AclTensorBuilder.h.
{
  _lifetime_seq.emplace_back(UsesType::FIRST, ind);
}
notifyLastUse()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::notifyLastUse (const ir::OperandIndex & ind)
Definition at line 198 of file AclTensorBuilder.h.
{
  _lifetime_seq.emplace_back(UsesType::LAST, ind);
}
parent_map()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::parent_map (std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > && parent_map) inline
Definition at line 78 of file AclTensorBuilder.h.
  {
    _parent_map = std::move(parent_map);
  }
References onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::parent_map().
Referenced by onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::parent_map().
postFunctionPrepare()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::postFunctionPrepare (void)
Definition at line 246 of file AclTensorBuilder.h.
{
  _tensor_mgr->tryDeallocConstants();
}
prepare()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::prepare (void)
Definition at line 211 of file AclTensorBuilder.h.
{
  buildTensors();
}
registerTensorInfo()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::registerTensorInfo (const ir::OperandIndex & ind, const ir::OperandInfo & info, ir::Layout backend_layout)
Register tensor information to allocate on ACL-CL backend.
Parameters
[in] ind Operand index
[in] info Tensor information
[in] layout Tensor data layout
Definition at line 139 of file AclTensorBuilder.h.
{
  assert(_tensor_mgr->constTensors().size() == 0);
  assert(_tensor_mgr->nonconstTensors().size() == 0);
  _uses_count_map[ind] = _operands.at(ind).getUses().size();
  if (_parent_map.count(ind) == 0)
  {
    // Normal Tensors
    _tensor_info_map.emplace(ind, info);
    _tensor_layout_map.insert({ind, backend_layout});
  }
  else
  {
    // SubTensors
    assert(!info.isConstant() && "Subtensors of constants are not supported yet.");
    // Update offset info and emplace
    auto &parent_info = _parent_map[ind];
    const auto &obj = _operands.at(ind);
    auto parent_index = parent_info.parent;
    auto &offset = parent_info.coordinates;
    auto frontend_layout = parent_info.frontend_layout;
    assert(obj.shape().rank() <= ir::Shape::kMaxRank);
    auto shape = obj.shape();
    if (_operands.at(parent_index).shape().rank() >= 4 && frontend_layout == ir::Layout::NHWC &&
        backend_layout == ir::Layout::NCHW)
    {
      // Permutation changing layout beyond 4-D is not supported yet
      const auto parent_rank = _operands.at(parent_index).shape().rank();
      assert(parent_rank == 4);
      shape.extendRank(parent_rank);
      offset = {offset[0], offset[3], offset[1], offset[2]};
    }
    else if (_operands.at(parent_index).shape().rank() >= 4 &&
             frontend_layout == ir::Layout::NCHW && backend_layout == ir::Layout::NHWC)
    {
      // Permutation changing layout beyond 4-D is not supported yet
      const auto parent_rank = _operands.at(parent_index).shape().rank();
      assert(parent_rank == 4);
      shape.extendRank(parent_rank);
      offset = {offset[0], offset[2], offset[3], offset[1]};
    }
    auto new_shape = permuteShape(shape, frontend_layout, backend_layout);
    auto oi = ir::OperandInfo::createStaticInfo(new_shape, obj.typeInfo());
    _tensor_info_map.emplace(ind, oi);
  }
}
References onert::ir::OperandInfo::createStaticInfo(), info, onert::ir::NCHW, onert::ir::NHWC, and offset().
setUsesCount()
template<typename T_ITensor , typename T_Tensor , typename T_SubTensor > void onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::setUsesCount (const ir::OperandIndex & index, size_t num_uses) inline
Definition at line 71 of file AclTensorBuilder.h.
  {
    assert(_uses_count_map.find(index) != _uses_count_map.end() ? _uses_count_map[index] == num_uses
                                                                : true);
    _uses_count_map[index] = num_uses;
  }
The documentation for this class was generated from the following file:
runtime/onert/backend/acl_common/AclTensorBuilder.h