ONE - On-device Neural Engine: onert::interp::ROTensor Class Reference
onert::interp::ROTensor Class Reference final
Class to handle tensor in interpreter as read-only.
#include <Tensor.h>
Public Member Functions
ROTensor ()=delete
ROTensor (const ir::OperandInfo &info)
uint8_t * buffer () const override
std::shared_ptr< const Buffer > shareBuffer () const override
Return shared pointer for buffer.
const uint8_t * bufferRO () const override
Return read-only buffer pointer.
std::shared_ptr< const ir::Data > shareData () const override
Return shared pointer for data.
void setBuffer (std::shared_ptr< const Buffer > buffer) override
Set internal/external buffer.
void setData (std::shared_ptr< const ir::Data > data) override
Set data reference (including constant, input)
void releaseData () override
size_t total_size () const override
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
bool has_padding () const override
ir::DataType data_type () const override
Return data type of tensor.
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
const ir::OperandInfo & tensorInfo () const override
Return TensorInfo.
uint64_t num_elements () const override
Return number of elements.
ir::Shape getShape () const override
Get ir::Shape of tensor.
Public Member Functions inherited from onert::interp::ITensor
virtual ~ITensor ()=default
virtual uint8_t * buffer () const =0
virtual std::shared_ptr< const Buffer > shareBuffer () const =0
Return shared pointer for buffer.
virtual const uint8_t * bufferRO () const =0
Return read-only buffer pointer.
virtual std::shared_ptr< const ir::Data > shareData () const =0
Return shared pointer for data.
virtual void setBuffer (std::shared_ptr< const Buffer > buffer)=0
Set internal/external buffer.
virtual void setData (std::shared_ptr< const ir::Data > data)=0
Set data reference (including constant, input)
virtual void releaseData ()=0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual bool has_padding () const =0
virtual ir::DataType data_type () const =0
Return data type of tensor.
virtual const ir::OperandInfo & tensorInfo () const =0
Return TensorInfo.
virtual uint64_t num_elements () const =0
Return number of elements.
void access (const std::function< void(backend::ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Detailed Description
Class to handle tensor in interpreter as read-only.
Definition at line 97 of file Tensor.h.
Constructor & Destructor Documentation
ROTensor() [1/2]
onert::interp::ROTensor::ROTensor () delete
ROTensor() [2/2]
onert::interp::ROTensor::ROTensor (const ir::OperandInfo & info) inline
Definition at line 101 of file Tensor.h.
                                      : _info(info)
  {
    // DO NOTHING
  }
Member Function Documentation
buffer()
uint8_t * onert::interp::ROTensor::buffer () const inline override virtual
Implements onert::interp::ITensor.
Definition at line 107 of file Tensor.h.
{ throw std::runtime_error{"Read only tensor"}; }
Referenced by setBuffer().
bufferRO()
const uint8_t * onert::interp::ROTensor::bufferRO () const inline override virtual
Return read-only buffer pointer.
Returns
Read-only buffer pointer
Implements onert::interp::ITensor.
Definition at line 112 of file Tensor.h.
{ return _data->base(); }
calcOffset()
size_t onert::interp::ROTensor::calcOffset (const ir::Coordinates & coords) const override virtual
Implements onert::interp::ITensor.
Definition at line 28 of file Tensor.cc.
{
  NO_USE(coords);
  throw std::runtime_error("offset_element_in_bytes is not supported for cpu::Tensor now.");
}
References coords, and NO_USE.
data_scale()
float onert::interp::ROTensor::data_scale () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 124 of file Tensor.h.
{ return _info.typeInfo().scale(); }
References onert::ir::TypeInfo::scale(), and onert::ir::OperandInfo::typeInfo().
data_scales()
const std::vector< float > & onert::interp::ROTensor::data_scales () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 126 of file Tensor.h.
{ return _info.typeInfo().scales(); }
References onert::ir::TypeInfo::scales(), and onert::ir::OperandInfo::typeInfo().
data_type()
ir::DataType onert::interp::ROTensor::data_type () const inline override virtual
Return data type of tensor.
Returns
Data type of tensor
Implements onert::interp::ITensor.
Definition at line 123 of file Tensor.h.
{ return _info.typeInfo().type(); }
References onert::ir::TypeInfo::type(), and onert::ir::OperandInfo::typeInfo().
data_zero_point()
int32_t onert::interp::ROTensor::data_zero_point () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 125 of file Tensor.h.
{ return _info.typeInfo().zero_point(); }
References onert::ir::OperandInfo::typeInfo(), and onert::ir::TypeInfo::zero_point().
data_zero_points()
const std::vector< int32_t > & onert::interp::ROTensor::data_zero_points () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 127 of file Tensor.h.
  {
    return _info.typeInfo().zero_points();
  }
References onert::ir::OperandInfo::typeInfo(), and onert::ir::TypeInfo::zero_points().
getShape()
ir::Shape onert::interp::ROTensor::getShape () const override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 54 of file Tensor.cc.
{ return _info.shape(); }
References onert::ir::OperandInfo::shape().
has_padding()
bool onert::interp::ROTensor::has_padding () const inline override virtual
Implements onert::interp::ITensor.
Definition at line 122 of file Tensor.h.
{ return false; }
is_dynamic()
bool onert::interp::ROTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 121 of file Tensor.h.
{ return false; }
layout()
ir::Layout onert::interp::ROTensor::layout () const override virtual
Implements onert::backend::ITensor.
Definition at line 40 of file Tensor.cc.
{
  // TODO Changes to return frontend layout
  return ir::Layout::NHWC;
}
References onert::ir::NHWC.
num_elements()
uint64_t onert::interp::ROTensor::num_elements () const inline override virtual
Return number of elements.
Returns
Number of elements
Implements onert::interp::ITensor.
Definition at line 132 of file Tensor.h.
{ return _info.shape().num_elements(); };
References onert::ir::OperandInfo::shape().
releaseData()
void onert::interp::ROTensor::releaseData () inline override virtual
Implements onert::interp::ITensor.
Definition at line 116 of file Tensor.h.
{ _data = nullptr; }
setBuffer()
void onert::interp::ROTensor::setBuffer (std::shared_ptr< const Buffer > buffer) inline override virtual
Set internal/external buffer.
Parameters
[in] buffer Buffer pointer
Implements onert::interp::ITensor.
Definition at line 114 of file Tensor.h.
{ _data = buffer; }
References buffer().
setData()
void onert::interp::ROTensor::setData (std::shared_ptr< const ir::Data > data) inline override virtual
Set data reference (including constant, input)
Parameters
[in] data Data pointer
Implements onert::interp::ITensor.
Definition at line 115 of file Tensor.h.
{ _data = data; }
shareBuffer()
std::shared_ptr< const Buffer > onert::interp::ROTensor::shareBuffer () const inline override virtual
Return shared pointer for buffer.
Returns
Buffer shared pointer
Implements onert::interp::ITensor.
Definition at line 108 of file Tensor.h.
  {
    throw std::runtime_error{"Read only tensor"};
  }
shareData()
std::shared_ptr< const ir::Data > onert::interp::ROTensor::shareData () const inline override virtual
Return shared pointer for data.
Returns
Data shared pointer
Implements onert::interp::ITensor.
Definition at line 113 of file Tensor.h.
{ return _data; }
tensorInfo()
const ir::OperandInfo & onert::interp::ROTensor::tensorInfo () const inline override virtual
Return TensorInfo.
Returns
TensorInfo
Implements onert::interp::ITensor.
Definition at line 131 of file Tensor.h.
{ return _info; }
total_size()
size_t onert::interp::ROTensor::total_size () const inline override virtual
Implements onert::interp::ITensor.
Definition at line 118 of file Tensor.h.
{ return _info.total_size(); }
References onert::ir::OperandInfo::total_size().
The documentation for this class was generated from the following files:
runtime/onert/core/src/interp/Tensor.h
runtime/onert/core/src/interp/Tensor.cc