ONE - On-device Neural Engine: loco::Subst< SubstQualifier::Default > Class Reference
loco::Subst< SubstQualifier::Default > Class Reference
A helper for below "replace" helper.
#include <Node.h>
Public Member Functions
void with (Node *into) const
Friends
Subst< SubstQualifier::Default > replace (Node *node)
Detailed Description
A helper for below "replace" helper.
Definition at line 129 of file Node.h.
Member Function Documentation
with()
void loco::Subst< SubstQualifier::Default >::with (Node * into) const
Definition at line 66 of file Node.cpp.
{
  if (_from == into)
  {
    return;
  }
  auto *uses = &(_from->_uses);
  while (!uses->empty())
  {
    auto use = *(uses->begin());
    use->node(into);
  }
}
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert(), exo::AvgPool2DConverter::convert(), exo::ConstGenConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MatMulConverter::convert(), exo::MaxPool2DConverter::convert(), exo::TensorConcatConverter::convert(), exo::TensorTransposeConverter::convert(), exo::TransposedConv2DConverter::convert(), luci::fuse_activation_function(), luci::fuse_add_with_conv(), luci::fuse_mul_with_conv(), luci::fuse_sub_with_conv(), logo::ReorderDecodePass< loco::TensorBiasAdd >::run(), logo::ReorderDecodePass< loco::ReLU >::run(), logo::RemoveForwardNodePass::run(), logo::SimplifyDomainConversionPass::run(), luci::FoldDequantizePass::run(), moco::RemoveTFIdentityNode::run(), exo::MergeConcatNodesPass::run(), logo::ResolveRedundantReshapePass::run(), and luci::swap_mul_add().
Friends And Related Function Documentation
replace
Subst< SubstQualifier::Default > replace (Node * node) friend
Definition at line 82 of file Node.cpp.
{
  // Let's create Subst<SubstQualifier::Default>!
  return Subst<SubstQualifier::Default>{node};
}
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/Node.h
compiler/loco/src/IR/Node.cpp