ONE - On-device Neural Engine: nest::VarID Class Reference
nest::VarID Class Reference
#include <VarID.h>
Public Member Functions
VarID ()
VarID (uint32_t value)
VarID (const VarID &vid)
uint32_t value (void) const
Detailed Description
Definition at line 25 of file VarID.h.
Constructor & Destructor Documentation
VarID() [1/3]
nest::VarID::VarID ()
Definition at line 22 of file VarID.cpp.
             : _value{0xffffffff}
{
  // DO NOTHING
}
VarID() [2/3]
nest::VarID::VarID (uint32_t value) inline explicit
Definition at line 31 of file VarID.h.
                                 : _value{value}
  {
    // DO NOTHING
  }
VarID() [3/3]
nest::VarID::VarID (const VarID & vid) inline
Definition at line 37 of file VarID.h.
                          : _value{vid._value}
  {
    // DO NOTHING
  }
Member Function Documentation
value()
uint32_t nest::VarID::value (void) const inline
Definition at line 43 of file VarID.h.
{ return _value; }
Referenced by nest::VarContext::bound(), nest::operator<(), and nest::operator==().
The documentation for this class was generated from the following files:
compiler/nest/core/include/nest/VarID.h
compiler/nest/core/src/VarID.cpp