ONE - On-device Neural Engine: luci_interpreter::Tensor Class Reference
luci_interpreter::Tensor Class Reference
#include <Tensor.h>
Public Member Functions
Tensor (DataType element_type, Shape shape, AffineQuantization quantization, std::string name)
DataType element_type () const
const Shape & shape () const
float scale () const
int32_t zero_point () const
const std::vector< float > & scales () const
const std::vector< int32_t > & zero_points () const
int32_t quantized_dimension () const
template<typename T >
const T * data () const
template<typename T >
T * data ()
const std::string & name () const
void readData (void *data_ptr, size_t data_size) const
void writeData (const void *data_ptr, size_t data_size)
void resize (const Shape &new_shape)
void set_data_buffer (uint8_t *buffer)
bool is_observable () const
void set_observable (bool value)
bool is_allocatable () const
void set_allocatable (bool value)
bool is_data_allocated () const
int32_t get_offset () const
void set_offset (int32_t offset)
Static Public Member Functions
static float scale (const circle::Tensor *circle_tensor)
static int32_t zero_point (const circle::Tensor *circle_tensor)
static const std::vector< float > scales (const circle::Tensor *circle_tensor)
static const std::vector< int32_t > zero_points (const circle::Tensor *circle_tensor)
static int32_t quantized_dimension (const circle::Tensor *circle_tensor)
static bool is_constant_tensor (const luci_interpreter::CircleReader *reader, const circle::Tensor *circle_tensor)
static DataType element_type (const circle::Tensor *circle_tensor)
static VectorWrapper< int32_t > tensor_shape (const circle::Tensor *circle_tensor)
static int num_dims (const circle::Tensor *circle_tensor)
static int32_t dim (const circle::Tensor *circle_tensor, int i)
static int32_t num_elements (const circle::Tensor *circle_tensor)
Detailed Description
Definition at line 100 of file Tensor.h.
Constructor & Destructor Documentation
Tensor()
Tensor::Tensor (DataType element_type, Shape shape, AffineQuantization quantization, std::string name)
Definition at line 25 of file Tensor.cpp.
  : _element_type(element_type), _shape(std::move(shape)), _quantization(std::move(quantization)),
    _name(std::move(name)), _data_allocated(false)
{
}
Member Function Documentation
data() [1/2]
template<typename T > T * luci_interpreter::Tensor::data () inline
Definition at line 134 of file Tensor.h.
  {
    static_assert(std::is_same<uint8_t, char>::value or
                  std::is_same<uint8_t, unsigned char>::value);
    return reinterpret_cast<T *>(_data);
  }
data() [2/2]
template<typename T > const T * luci_interpreter::Tensor::data () const inline
Definition at line 127 of file Tensor.h.
  {
    static_assert(std::is_same<uint8_t, char>::value or
                  std::is_same<uint8_t, unsigned char>::value);
    return reinterpret_cast<const T *>(_data);
  }
Referenced by luci_interpreter::kernels::BatchToSpaceND::configure(), luci_interpreter::kernels::SpaceToBatchND::configure(), luci_interpreter::kernels::ExpandDims::execute(), luci_interpreter::kernels::If::execute(), luci_interpreter::kernels::Reshape::execute(), luci_interpreter::kernels::Squeeze::execute(), and luci_interpreter::kernels::MirrorPadImpl().
dim()
static int32_t luci_interpreter::Tensor::dim (const circle::Tensor * circle_tensor, int i) inline static
Definition at line 225 of file Tensor.h.
  {
    // TODO check removing of wrap
    assert(i >= 0);
    auto const const_dims = wrap(circle_tensor->shape());
    assert(i < const_dims.size());
    return const_dims[i];
  }
References luci::wrap().
Referenced by num_elements().
element_type() [1/2]
DataType luci_interpreter::Tensor::element_type () const inline
Definition at line 105 of file Tensor.h.
{ return _element_type; }
Referenced by luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleSVDF(), luci_interpreter::build_kernel_CircleTransposeConv(), luci_interpreter::build_kernel_CircleUnidirectionalSequenceLSTM(), luci_interpreter::kernels::Concatenation::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Unpack::configure(), readData(), luci_interpreter::kernels::TransposeRowsColumns(), and writeData().
element_type() [2/2]
static DataType luci_interpreter::Tensor::element_type (const circle::Tensor * circle_tensor) inline static
Definition at line 208 of file Tensor.h.
  {
    return luci_datatype(circle_tensor->type());
  }
References luci::luci_datatype().
get_offset()
int32_t luci_interpreter::Tensor::get_offset () const inline
Definition at line 172 of file Tensor.h.
{ return _offset; }
is_allocatable()
bool luci_interpreter::Tensor::is_allocatable () const inline
Definition at line 166 of file Tensor.h.
{ return _is_allocatable; }
is_constant_tensor()
static bool luci_interpreter::Tensor::is_constant_tensor (const luci_interpreter::CircleReader * reader, const circle::Tensor * circle_tensor) inline static
Definition at line 202 of file Tensor.h.
  {
    return reader->buffers()[circle_tensor->buffer()]->data() != nullptr;
  }
References luci::CircleReader::buffers(), and luci::VectorWrapper< T >::data().
is_data_allocated()
bool luci_interpreter::Tensor::is_data_allocated () const inline
Definition at line 170 of file Tensor.h.
{ return _data_allocated; }
is_observable()
bool luci_interpreter::Tensor::is_observable () const inline
Definition at line 162 of file Tensor.h.
{ return _is_observable; }
name()
const std::string & luci_interpreter::Tensor::name () const inline
Definition at line 141 of file Tensor.h.
{ return _name; }
num_dims()
static int luci_interpreter::Tensor::num_dims (const circle::Tensor * circle_tensor) inline static
Definition at line 218 of file Tensor.h.
  {
    // TODO check removing of wrap
    auto const const_dims = wrap(circle_tensor->shape());
    return const_dims.size();
  }
References luci::wrap().
num_elements()
static int32_t luci_interpreter::Tensor::num_elements (const circle::Tensor * circle_tensor) inline static
Definition at line 235 of file Tensor.h.
  {
    int32_t result = 1;
    auto const const_dims = wrap(circle_tensor->shape());
    for (const int32_t dim : const_dims)
    {
      result *= dim;
    }
    return result;
  }
References dim(), and luci::wrap().
Referenced by readData(), and writeData().
quantized_dimension() [1/2]
int32_t luci_interpreter::Tensor::quantized_dimension () const inline
Definition at line 125 of file Tensor.h.
{ return _quantization.quantized_dimension; }
References luci_interpreter::AffineQuantization::quantized_dimension.
quantized_dimension() [2/2]
static int32_t luci_interpreter::Tensor::quantized_dimension (const circle::Tensor * circle_tensor) inline static
Definition at line 190 of file Tensor.h.
  {
    const auto *quant_params = circle_tensor->quantization();
    if (quant_params == nullptr)
    {
      assert(false && "There is no quantization params");
      return 0;
    }
    return quant_params->quantized_dimension();
  }
readData()
void Tensor::readData (void * data_ptr, size_t data_size) const
Definition at line 32 of file Tensor.cpp.
{
  const size_t element_size = getDataTypeSize(element_type());
  const int32_t num_elements = shape().num_elements();
  if (data_size != num_elements * element_size)
  {
    throw std::invalid_argument("Invalid data size.");
  }
  assert(data_ptr != nullptr);
  std::memcpy(data_ptr, data<void>(), data_size);
}
References element_type(), luci_interpreter::getDataTypeSize(), luci_interpreter::Shape::num_elements(), num_elements(), and shape().
resize()
void Tensor::resize (const Shape & new_shape)
Definition at line 56 of file Tensor.cpp.
{ _shape = new_shape; }
Referenced by luci_interpreter::kernels::Abs::configure(), luci_interpreter::kernels::Add::configure(), luci_interpreter::kernels::ArgMax::configure(), luci_interpreter::kernels::AveragePool2D::configure(), luci_interpreter::kernels::BatchMatMul::configure(), luci_interpreter::kernels::BatchToSpaceND::configure(), luci_interpreter::kernels::BroadcastTo::configure(), luci_interpreter::kernels::Cast::configure(), luci_interpreter::kernels::Concatenation::configure(), luci_interpreter::kernels::Conv2D::configure(), luci_interpreter::kernels::Cos::configure(), luci_interpreter::kernels::CumSum::configure(), luci_interpreter::kernels::DepthToSpace::configure(), luci_interpreter::kernels::DepthwiseConv2D::configure(), luci_interpreter::kernels::Dequantize::configure(), luci_interpreter::kernels::Div::configure(), luci_interpreter::kernels::Elu::configure(), luci_interpreter::kernels::Equal::configure(), luci_interpreter::kernels::Exp::configure(), luci_interpreter::kernels::ExpandDims::configure(), luci_interpreter::kernels::Floor::configure(), luci_interpreter::kernels::FloorDiv::configure(), luci_interpreter::kernels::FloorMod::configure(), luci_interpreter::kernels::FullyConnected::configure(), luci_interpreter::kernels::Gather::configure(), luci_interpreter::kernels::Gelu::configure(), luci_interpreter::kernels::Greater::configure(), luci_interpreter::kernels::GreaterEqual::configure(), luci_interpreter::kernels::HardSwish::configure(), luci_interpreter::kernels::InstanceNorm::configure(), luci_interpreter::kernels::L2Normalize::configure(), luci_interpreter::kernels::L2Pool2D::configure(), luci_interpreter::kernels::LeakyRelu::configure(), luci_interpreter::kernels::Less::configure(), luci_interpreter::kernels::LessEqual::configure(), luci_interpreter::kernels::LocalResponseNormalization::configure(), luci_interpreter::kernels::Log::configure(), luci_interpreter::kernels::LogicalAnd::configure(), luci_interpreter::kernels::LogicalNot::configure(), luci_interpreter::kernels::LogicalOr::configure(), luci_interpreter::kernels::Logistic::configure(), luci_interpreter::kernels::LogSoftmax::configure(), luci_interpreter::kernels::Maximum::configure(), luci_interpreter::kernels::MaxPool2D::configure(), luci_interpreter::kernels::Mean::configure(), luci_interpreter::kernels::Minimum::configure(), luci_interpreter::kernels::MirrorPad::configure(), luci_interpreter::kernels::Mul::configure(), luci_interpreter::kernels::Neg::configure(), luci_interpreter::kernels::NotEqual::configure(), luci_interpreter::kernels::OneHot::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Pad::configure(), luci_interpreter::kernels::PadV2::configure(), luci_interpreter::kernels::Pow::configure(), luci_interpreter::kernels::PRelu::configure(), luci_interpreter::kernels::Quantize::configure(), luci_interpreter::kernels::ReduceMax::configure(), luci_interpreter::kernels::ReduceProd::configure(), luci_interpreter::kernels::Relu::configure(), luci_interpreter::kernels::Relu6::configure(), luci_interpreter::kernels::Reshape::configure(), luci_interpreter::kernels::ResizeBilinear::configure(), luci_interpreter::kernels::ResizeNearestNeighbor::configure(), luci_interpreter::kernels::ReverseV2::configure(), luci_interpreter::kernels::Rsqrt::configure(), luci_interpreter::kernels::Select::configure(), luci_interpreter::kernels::ShapeKernel::configure(), luci_interpreter::kernels::Sin::configure(), luci_interpreter::kernels::Slice::configure(), luci_interpreter::kernels::Softmax::configure(), luci_interpreter::kernels::SpaceToBatchND::configure(), luci_interpreter::kernels::SpaceToDepth::configure(), luci_interpreter::kernels::Split::configure(), luci_interpreter::kernels::Sqrt::configure(), luci_interpreter::kernels::Square::configure(), luci_interpreter::kernels::SquaredDifference::configure(), luci_interpreter::kernels::Squeeze::configure(), luci_interpreter::kernels::StridedSlice::configure(), luci_interpreter::kernels::Sub::configure(), luci_interpreter::kernels::Sum::configure(), luci_interpreter::kernels::SVDF::configure(), luci_interpreter::kernels::Tanh::configure(), luci_interpreter::kernels::Tile::configure(), luci_interpreter::kernels::Transpose::configure(), luci_interpreter::kernels::TransposeConv::configure(), luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure(), luci_interpreter::kernels::Unpack::configure(), and luci_interpreter::kernels::If::execute().
scale() [1/2]
float luci_interpreter::Tensor::scale () const inline
Definition at line 109 of file Tensor.h.
  {
    assert(_quantization.scale.size() == 1);
    return _quantization.scale[0];
  }
References luci_interpreter::AffineQuantization::scale.
Referenced by luci_interpreter::kernels::LeakyRelu::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::PRelu::configure(), luci_interpreter::kernels::Relu::configure(), luci_interpreter::kernels::Relu6::configure(), luci_interpreter::kernels::Dequantize::execute(), and luci_interpreter::kernels::Quantize::execute().
scale() [2/2]
static float luci_interpreter::Tensor::scale (const circle::Tensor * circle_tensor) inline static
Definition at line 137 of file Tensor.h.
  {
    const auto *quant_params = circle_tensor->quantization();
    if (quant_params == nullptr)
    {
      assert(false && "There is no quantization params");
      return 0;
    }
    return *quant_params->scale()->cbegin();
  }
scales() [1/2]
const std::vector< float > & luci_interpreter::Tensor::scales () const inline
Definition at line 121 of file Tensor.h.
{ return _quantization.scale; }
References luci_interpreter::AffineQuantization::scale.
Referenced by scales().
scales() [2/2]
static const std::vector< float > luci_interpreter::Tensor::scales (const circle::Tensor * circle_tensor) inline static
Definition at line 161 of file Tensor.h.
  {
    const auto *quant_params = circle_tensor->quantization();
    if (quant_params == nullptr)
    {
      assert(false && "There is no quantization params");
      return {};
    }
    assert(quant_params->scale() != nullptr);
    std::vector<float> scales(quant_params->scale()->cbegin(), quant_params->scale()->cend());
    return scales;
  }
References scales().
set_allocatable()
void luci_interpreter::Tensor::set_allocatable (bool value) inline
Definition at line 168 of file Tensor.h.
{ _is_allocatable = value; }
set_data_buffer()
void luci_interpreter::Tensor::set_data_buffer (uint8_t * buffer) inline
Definition at line 149 of file Tensor.h.
  {
    if (buffer == nullptr)
    {
      _data_allocated = false;
    }
    else
    {
      _data_allocated = true;
    }
    _data = buffer;
  }
set_observable()
void luci_interpreter::Tensor::set_observable (bool value) inline
Definition at line 164 of file Tensor.h.
{ _is_observable = value; }
Referenced by luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleConv2D(), luci_interpreter::build_kernel_CircleMean(), luci_interpreter::build_kernel_CircleReduceMax(), luci_interpreter::build_kernel_CircleReduceProd(), luci_interpreter::build_kernel_CircleSum(), luci_interpreter::build_kernel_CircleSVDF(), and luci_interpreter::build_kernel_CircleUnidirectionalSequenceLSTM().
set_offset()
void luci_interpreter::Tensor::set_offset (int32_t offset) inline
Definition at line 174 of file Tensor.h.
{ _offset = offset; }
References offset().
shape()
const Shape & luci_interpreter::Tensor::shape () const inline
Definition at line 107 of file Tensor.h.
{ return _shape; }
Referenced by luci_interpreter::kernels::ArgMax::configure(), luci_interpreter::kernels::AveragePool2D::configure(), luci_interpreter::kernels::BatchToSpaceND::configure(), luci_interpreter::kernels::BroadcastTo::configure(), luci_interpreter::kernels::Cast::configure(), luci_interpreter::kernels::Concatenation::configure(), luci_interpreter::kernels::Conv2D::configure(), luci_interpreter::kernels::DepthToSpace::configure(), luci_interpreter::kernels::DepthwiseConv2D::configure(), luci_interpreter::kernels::ExpandDims::configure(), luci_interpreter::kernels::Fill::configure(), luci_interpreter::kernels::FullyConnected::configure(), luci_interpreter::kernels::Gather::configure(), luci_interpreter::kernels::L2Pool2D::configure(), luci_interpreter::kernels::MaxPool2D::configure(), luci_interpreter::kernels::Mean::configure(), luci_interpreter::kernels::MirrorPad::configure(), luci_interpreter::kernels::OneHot::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Pad::configure(), luci_interpreter::kernels::PadV2::configure(), luci_interpreter::kernels::PRelu::configure(), luci_interpreter::kernels::ReduceMax::configure(), luci_interpreter::kernels::ReduceProd::configure(), luci_interpreter::kernels::ResizeBilinear::configure(), luci_interpreter::kernels::ResizeNearestNeighbor::configure(), luci_interpreter::kernels::Select::configure(), luci_interpreter::kernels::ShapeKernel::configure(), luci_interpreter::kernels::SpaceToBatchND::configure(), luci_interpreter::kernels::SpaceToDepth::configure(), luci_interpreter::kernels::Split::configure(), luci_interpreter::kernels::SplitV::configure(), luci_interpreter::kernels::Squeeze::configure(), luci_interpreter::kernels::StridedSlice::configure(), luci_interpreter::kernels::Sum::configure(), luci_interpreter::kernels::SVDF::configure(), luci_interpreter::kernels::Tile::configure(), luci_interpreter::kernels::Transpose::configure(), luci_interpreter::kernels::TransposeConv::configure(), luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure(), luci_interpreter::kernels::Unpack::configure(), luci_interpreter_pal::eval_integer_8x8_16_lstm(), luci_interpreter::kernels::lstm::EvalFloat(), luci_interpreter::kernels::ExpandDims::execute(), luci_interpreter::kernels::If::execute(), luci_interpreter::kernels::Pad::execute(), luci_interpreter::kernels::PadV2::execute(), luci_interpreter::kernels::Reshape::execute(), luci_interpreter::kernels::StridedSlice::execute(), luci_interpreter::kernels::Transpose::execute(), readData(), and writeData().
tensor_shape()
static VectorWrapper< int32_t > luci_interpreter::Tensor::tensor_shape (const circle::Tensor * circle_tensor) inline static
Definition at line 213 of file Tensor.h.
  {
    return wrap(circle_tensor->shape());
  }
References luci::wrap().
writeData()
void Tensor::writeData (const void * data_ptr, size_t data_size)
Definition at line 44 of file Tensor.cpp.
{
  const size_t element_size = getDataTypeSize(element_type());
  const int32_t num_elements = shape().num_elements();
  if (data_size != num_elements * element_size)
  {
    throw std::invalid_argument("Invalid data size.");
  }
  assert(data_ptr != nullptr);
  std::memcpy(data<void>(), data_ptr, data_size);
}
References element_type(), luci_interpreter::getDataTypeSize(), luci_interpreter::Shape::num_elements(), num_elements(), and shape().
zero_point() [1/2]
int32_t luci_interpreter::Tensor::zero_point () const inline
Definition at line 115 of file Tensor.h.
  {
    assert(_quantization.zero_point.size() == 1);
    return _quantization.zero_point[0];
  }
References luci_interpreter::AffineQuantization::zero_point.
Referenced by luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Dequantize::execute(), luci_interpreter::kernels::Pad::execute(), luci_interpreter::kernels::Quantize::execute(), and luci_interpreter::kernels::SpaceToBatchND::execute().
zero_point() [2/2]
static int32_t luci_interpreter::Tensor::zero_point (const circle::Tensor * circle_tensor) inline static
Definition at line 149 of file Tensor.h.
  {
    const auto *quant_params = circle_tensor->quantization();
    if (quant_params == nullptr)
    {
      assert(false && "There is no quantization params");
      return 0;
    }
    return *quant_params->zero_point()->cbegin();
  }
zero_points() [1/2]
const std::vector< int32_t > & luci_interpreter::Tensor::zero_points () const inline
Definition at line 123 of file Tensor.h.
{ return _quantization.zero_point; }
References luci_interpreter::AffineQuantization::zero_point.
Referenced by luci_interpreter::kernels::PRelu::configure(), and zero_points().
zero_points() [2/2]
static const std::vector< int32_t > luci_interpreter::Tensor::zero_points (const circle::Tensor * circle_tensor) inline static
Definition at line 175 of file Tensor.h.
  {
    const auto *quant_params = circle_tensor->quantization();
    if (quant_params == nullptr)
    {
      assert(false && "There is no quantization params");
      return {};
    }
    assert(quant_params->zero_point() != nullptr);
    std::vector<int32_t> zero_points(quant_params->zero_point()->cbegin(),
                                     quant_params->zero_point()->cend());
    return zero_points;
  }
References zero_points().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
onert-micro/luci-interpreter/include/luci_interpreter/core/Tensor.h
compiler/luci-interpreter/src/core/Tensor.cpp