ONE - On-device Neural Engine: locoex::TFLAveragePool2D Class Reference
locoex::TFLAveragePool2D Class Reference final
AVERAGE_POOL_2D in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
TFLAveragePool2D ()
loco::Node * value (void) const
void value (loco::Node *node)
Padding padding () const
void padding (Padding padding)
const Filter * filter (void) const
Filter * filter (void)
const Stride * stride (void) const
Stride * stride (void)
Public Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFLOpcode opcode (void) const =0
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >
TFLNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >
loco::Use * at (unsigned n) const
Detailed Description
AVERAGE_POOL_2D in TensorFlow Lite.
Definition at line 128 of file TFLNodes.h.
Constructor & Destructor Documentation
TFLAveragePool2D()
locoex::TFLAveragePool2D::TFLAveragePool2D () inline
Definition at line 132 of file TFLNodes.h.
                     : _padding(Padding::UNDEFINED)
  { /* empty */
  }
Member Function Documentation
filter() [1/2]
Filter * locoex::TFLAveragePool2D::filter (void) inline
Definition at line 144 of file TFLNodes.h.
{ return &_filter; }
filter() [2/2]
const Filter * locoex::TFLAveragePool2D::filter (void) const inline
Definition at line 143 of file TFLNodes.h.
{ return &_filter; }
padding() [1/2]
Padding locoex::TFLAveragePool2D::padding () const inline
Definition at line 140 of file TFLNodes.h.
{ return _padding; }
padding() [2/2]
void locoex::TFLAveragePool2D::padding (Padding padding) inline
Definition at line 141 of file TFLNodes.h.
{ _padding = padding; }
References padding().
Referenced by padding().
stride() [1/2]
Stride * locoex::TFLAveragePool2D::stride (void) inline
Definition at line 147 of file TFLNodes.h.
{ return &_stride; }
stride() [2/2]
const Stride * locoex::TFLAveragePool2D::stride (void) const inline
Definition at line 146 of file TFLNodes.h.
{ return &_stride; }
value() [1/2]
void locoex::TFLAveragePool2D::value (loco::Node * node) inline
Definition at line 138 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >::at(), and loco::Use::node().
value() [2/2]
loco::Node * locoex::TFLAveragePool2D::value (void) const inline
Definition at line 137 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D > >::at(), and loco::Use::node().
Referenced by exo::AvgPool2DConverter::convert().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h