ONE - On-device Neural Engine: luci::CircleBidirectionalSequenceLSTM Class Reference
luci::CircleBidirectionalSequenceLSTM Class Reference final
BIDIRECTIONAL_SEQUENCE_LSTM in Circle.
#include <CircleBidirectionalSequenceLSTM.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * fw_input_to_input_weights (void) const
void fw_input_to_input_weights (loco::Node *node)
loco::Node * fw_input_to_forget_weights (void) const
void fw_input_to_forget_weights (loco::Node *node)
loco::Node * fw_input_to_cell_weights (void) const
void fw_input_to_cell_weights (loco::Node *node)
loco::Node * fw_input_to_output_weights (void) const
void fw_input_to_output_weights (loco::Node *node)
loco::Node * fw_recurrent_to_input_weights (void) const
void fw_recurrent_to_input_weights (loco::Node *node)
loco::Node * fw_recurrent_to_forget_weights (void) const
void fw_recurrent_to_forget_weights (loco::Node *node)
loco::Node * fw_recurrent_to_cell_weights (void) const
void fw_recurrent_to_cell_weights (loco::Node *node)
loco::Node * fw_recurrent_to_output_weights (void) const
void fw_recurrent_to_output_weights (loco::Node *node)
loco::Node * fw_cell_to_input_weights (void) const
void fw_cell_to_input_weights (loco::Node *node)
loco::Node * fw_cell_to_forget_weights (void) const
void fw_cell_to_forget_weights (loco::Node *node)
loco::Node * fw_cell_to_output_weights (void) const
void fw_cell_to_output_weights (loco::Node *node)
loco::Node * fw_input_gate_bias (void) const
void fw_input_gate_bias (loco::Node *node)
loco::Node * fw_forget_gate_bias (void) const
void fw_forget_gate_bias (loco::Node *node)
loco::Node * fw_cell_gate_bias (void) const
void fw_cell_gate_bias (loco::Node *node)
loco::Node * fw_output_gate_bias (void) const
void fw_output_gate_bias (loco::Node *node)
loco::Node * fw_projection_weights (void) const
void fw_projection_weights (loco::Node *node)
loco::Node * fw_projection_bias (void) const
void fw_projection_bias (loco::Node *node)
loco::Node * bw_input_to_input_weights (void) const
void bw_input_to_input_weights (loco::Node *node)
loco::Node * bw_input_to_forget_weights (void) const
void bw_input_to_forget_weights (loco::Node *node)
loco::Node * bw_input_to_cell_weights (void) const
void bw_input_to_cell_weights (loco::Node *node)
loco::Node * bw_input_to_output_weights (void) const
void bw_input_to_output_weights (loco::Node *node)
loco::Node * bw_recurrent_to_input_weights (void) const
void bw_recurrent_to_input_weights (loco::Node *node)
loco::Node * bw_recurrent_to_forget_weights (void) const
void bw_recurrent_to_forget_weights (loco::Node *node)
loco::Node * bw_recurrent_to_cell_weights (void) const
void bw_recurrent_to_cell_weights (loco::Node *node)
loco::Node * bw_recurrent_to_output_weights (void) const
void bw_recurrent_to_output_weights (loco::Node *node)
loco::Node * bw_cell_to_input_weights (void) const
void bw_cell_to_input_weights (loco::Node *node)
loco::Node * bw_cell_to_forget_weights (void) const
void bw_cell_to_forget_weights (loco::Node *node)
loco::Node * bw_cell_to_output_weights (void) const
void bw_cell_to_output_weights (loco::Node *node)
loco::Node * bw_input_gate_bias (void) const
void bw_input_gate_bias (loco::Node *node)
loco::Node * bw_forget_gate_bias (void) const
void bw_forget_gate_bias (loco::Node *node)
loco::Node * bw_cell_gate_bias (void) const
void bw_cell_gate_bias (loco::Node *node)
loco::Node * bw_output_gate_bias (void) const
void bw_output_gate_bias (loco::Node *node)
loco::Node * bw_projection_weights (void) const
void bw_projection_weights (loco::Node *node)
loco::Node * bw_projection_bias (void) const
void bw_projection_bias (loco::Node *node)
loco::Node * fw_activation_state (void) const
void fw_activation_state (loco::Node *node)
loco::Node * fw_cell_state (void) const
void fw_cell_state (loco::Node *node)
loco::Node * bw_activation_state (void) const
void bw_activation_state (loco::Node *node)
loco::Node * bw_cell_state (void) const
void bw_cell_state (loco::Node *node)
loco::Node * auxillary_input (void) const
void auxillary_input (loco::Node *node)
loco::Node * fw_auxillary_input_to_input_weights (void) const
void fw_auxillary_input_to_input_weights (loco::Node *node)
loco::Node * fw_auxillary_input_to_forget_weights (void) const
void fw_auxillary_input_to_forget_weights (loco::Node *node)
loco::Node * fw_auxillary_input_to_cell_weights (void) const
void fw_auxillary_input_to_cell_weights (loco::Node *node)
loco::Node * fw_auxillary_input_to_output_weights (void) const
void fw_auxillary_input_to_output_weights (loco::Node *node)
loco::Node * bw_auxillary_input_to_input_weights (void) const
void bw_auxillary_input_to_input_weights (loco::Node *node)
loco::Node * bw_auxillary_input_to_forget_weights (void) const
void bw_auxillary_input_to_forget_weights (loco::Node *node)
loco::Node * bw_auxillary_input_to_cell_weights (void) const
void bw_auxillary_input_to_cell_weights (loco::Node *node)
loco::Node * bw_auxillary_input_to_output_weights (void) const
void bw_auxillary_input_to_output_weights (loco::Node *node)
float cell_clip (void) const
void cell_clip (float cell_clip)
float proj_clip (void) const
void proj_clip (float proj_clip)
bool merge_outputs (void) const
void merge_outputs (bool merge_outputs)
bool time_major (void) const
void time_major (bool time_major)
bool asymmetric_quantize_inputs (void) const
void asymmetric_quantize_inputs (bool asymmetric_quantize_inputs)
Public Member Functions inherited from luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >
loco::Use * at (uint32_t n) const
Detailed Description
BIDIRECTIONAL_SEQUENCE_LSTM in Circle.
Definition at line 32 of file CircleBidirectionalSequenceLSTM.h.
Member Function Documentation
asymmetric_quantize_inputs() [1/2]
void luci::CircleBidirectionalSequenceLSTM::asymmetric_quantize_inputs (bool asymmetric_quantize_inputs) inline
Definition at line 157 of file CircleBidirectionalSequenceLSTM.h.
  {
    _asymmetric_quantize_inputs = asymmetric_quantize_inputs;
  }
References asymmetric_quantize_inputs().
asymmetric_quantize_inputs() [2/2]
bool luci::CircleBidirectionalSequenceLSTM::asymmetric_quantize_inputs (void) const inline
Definition at line 156 of file CircleBidirectionalSequenceLSTM.h.
{ return _asymmetric_quantize_inputs; }
Referenced by asymmetric_quantize_inputs(), and luci::BuiltinOptionsExtractor::visit().
auxillary_input() [1/2]
void luci::CircleBidirectionalSequenceLSTM::auxillary_input (loco::Node * node) inline
Definition at line 129 of file CircleBidirectionalSequenceLSTM.h.
{ at(39)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
auxillary_input() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::auxillary_input (void) const inline
Definition at line 128 of file CircleBidirectionalSequenceLSTM.h.
{ return at(39)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_activation_state() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_activation_state (loco::Node * node) inline
Definition at line 124 of file CircleBidirectionalSequenceLSTM.h.
{ at(37)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_activation_state() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_activation_state (void) const inline
Definition at line 123 of file CircleBidirectionalSequenceLSTM.h.
{ return at(37)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_cell_weights (loco::Node * node) inline
Definition at line 143 of file CircleBidirectionalSequenceLSTM.h.
{ at(46)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_cell_weights (void) const inline
Definition at line 142 of file CircleBidirectionalSequenceLSTM.h.
{ return at(46)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_forget_weights (loco::Node * node) inline
Definition at line 141 of file CircleBidirectionalSequenceLSTM.h.
{ at(45)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_forget_weights (void) const inline
Definition at line 140 of file CircleBidirectionalSequenceLSTM.h.
{ return at(45)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_input_weights (loco::Node * node) inline
Definition at line 139 of file CircleBidirectionalSequenceLSTM.h.
{ at(44)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_input_weights (void) const inline
Definition at line 138 of file CircleBidirectionalSequenceLSTM.h.
{ return at(44)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_output_weights (loco::Node * node) inline
Definition at line 145 of file CircleBidirectionalSequenceLSTM.h.
{ at(47)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_auxillary_input_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_output_weights (void) const inline
Definition at line 144 of file CircleBidirectionalSequenceLSTM.h.
{ return at(47)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_cell_gate_bias (loco::Node * node) inline
Definition at line 109 of file CircleBidirectionalSequenceLSTM.h.
{ at(31)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_cell_gate_bias (void) const inline
Definition at line 108 of file CircleBidirectionalSequenceLSTM.h.
{ return at(31)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_state() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_cell_state (loco::Node * node) inline
Definition at line 126 of file CircleBidirectionalSequenceLSTM.h.
{ at(38)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_state() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_cell_state (void) const inline
Definition at line 125 of file CircleBidirectionalSequenceLSTM.h.
{ return at(38)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_cell_to_forget_weights (loco::Node * node) inline
Definition at line 100 of file CircleBidirectionalSequenceLSTM.h.
{ at(27)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_cell_to_forget_weights (void) const inline
Definition at line 99 of file CircleBidirectionalSequenceLSTM.h.
{ return at(27)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_cell_to_input_weights (loco::Node * node) inline
Definition at line 98 of file CircleBidirectionalSequenceLSTM.h.
{ at(26)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_cell_to_input_weights (void) const inline
Definition at line 97 of file CircleBidirectionalSequenceLSTM.h.
{ return at(26)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_cell_to_output_weights (loco::Node * node) inline
Definition at line 102 of file CircleBidirectionalSequenceLSTM.h.
{ at(28)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_cell_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_cell_to_output_weights (void) const inline
Definition at line 101 of file CircleBidirectionalSequenceLSTM.h.
{ return at(28)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_forget_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_forget_gate_bias (loco::Node * node) inline
Definition at line 107 of file CircleBidirectionalSequenceLSTM.h.
{ at(30)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_forget_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_forget_gate_bias (void) const inline
Definition at line 106 of file CircleBidirectionalSequenceLSTM.h.
{ return at(30)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_input_gate_bias (loco::Node * node) inline
Definition at line 105 of file CircleBidirectionalSequenceLSTM.h.
{ at(29)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_input_gate_bias (void) const inline
Definition at line 104 of file CircleBidirectionalSequenceLSTM.h.
{ return at(29)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_input_to_cell_weights (loco::Node * node) inline
Definition at line 84 of file CircleBidirectionalSequenceLSTM.h.
{ at(20)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_input_to_cell_weights (void) const inline
Definition at line 83 of file CircleBidirectionalSequenceLSTM.h.
{ return at(20)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_input_to_forget_weights (loco::Node * node) inline
Definition at line 82 of file CircleBidirectionalSequenceLSTM.h.
{ at(19)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_input_to_forget_weights (void) const inline
Definition at line 81 of file CircleBidirectionalSequenceLSTM.h.
{ return at(19)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_input_to_input_weights (loco::Node * node) inline
Definition at line 80 of file CircleBidirectionalSequenceLSTM.h.
{ at(18)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_input_to_input_weights (void) const inline
Definition at line 79 of file CircleBidirectionalSequenceLSTM.h.
{ return at(18)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_input_to_output_weights (loco::Node * node) inline
Definition at line 86 of file CircleBidirectionalSequenceLSTM.h.
{ at(21)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_input_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_input_to_output_weights (void) const inline
Definition at line 85 of file CircleBidirectionalSequenceLSTM.h.
{ return at(21)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_output_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_output_gate_bias (loco::Node * node) inline
Definition at line 111 of file CircleBidirectionalSequenceLSTM.h.
{ at(32)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_output_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_output_gate_bias (void) const inline
Definition at line 110 of file CircleBidirectionalSequenceLSTM.h.
{ return at(32)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_projection_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_projection_bias (loco::Node * node) inline
Definition at line 116 of file CircleBidirectionalSequenceLSTM.h.
{ at(34)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_projection_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_projection_bias (void) const inline
Definition at line 115 of file CircleBidirectionalSequenceLSTM.h.
{ return at(34)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_projection_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_projection_weights (loco::Node * node) inline
Definition at line 114 of file CircleBidirectionalSequenceLSTM.h.
{ at(33)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_projection_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_projection_weights (void) const inline
Definition at line 113 of file CircleBidirectionalSequenceLSTM.h.
{ return at(33)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_cell_weights (loco::Node * node) inline
Definition at line 93 of file CircleBidirectionalSequenceLSTM.h.
{ at(24)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_cell_weights (void) const inline
Definition at line 92 of file CircleBidirectionalSequenceLSTM.h.
{ return at(24)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_forget_weights (loco::Node * node) inline
Definition at line 91 of file CircleBidirectionalSequenceLSTM.h.
{ at(23)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_forget_weights (void) const inline
Definition at line 90 of file CircleBidirectionalSequenceLSTM.h.
{ return at(23)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_input_weights (loco::Node * node) inline
Definition at line 89 of file CircleBidirectionalSequenceLSTM.h.
{ at(22)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_input_weights (void) const inline
Definition at line 88 of file CircleBidirectionalSequenceLSTM.h.
{ return at(22)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_output_weights (loco::Node * node) inline
Definition at line 95 of file CircleBidirectionalSequenceLSTM.h.
{ at(25)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
bw_recurrent_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_output_weights (void) const inline
Definition at line 94 of file CircleBidirectionalSequenceLSTM.h.
{ return at(25)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_clip() [1/2]
void luci::CircleBidirectionalSequenceLSTM::cell_clip (float cell_clip) inline
Definition at line 149 of file CircleBidirectionalSequenceLSTM.h.
{ _cell_clip = cell_clip; }
References cell_clip().
Referenced by cell_clip().
cell_clip() [2/2]
float luci::CircleBidirectionalSequenceLSTM::cell_clip (void) const inline
Definition at line 148 of file CircleBidirectionalSequenceLSTM.h.
{ return _cell_clip; }
Referenced by luci::BuiltinOptionsExtractor::visit().
fw_activation_state() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_activation_state (loco::Node * node) inline
Definition at line 119 of file CircleBidirectionalSequenceLSTM.h.
{ at(35)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_activation_state() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_activation_state (void) const inline
Definition at line 118 of file CircleBidirectionalSequenceLSTM.h.
{ return at(35)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_cell_weights (loco::Node * node) inline
Definition at line 135 of file CircleBidirectionalSequenceLSTM.h.
{ at(42)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_cell_weights (void) const inline
Definition at line 134 of file CircleBidirectionalSequenceLSTM.h.
{ return at(42)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_forget_weights (loco::Node * node) inline
Definition at line 133 of file CircleBidirectionalSequenceLSTM.h.
{ at(41)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_forget_weights (void) const inline
Definition at line 132 of file CircleBidirectionalSequenceLSTM.h.
{ return at(41)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_input_weights (loco::Node * node) inline
Definition at line 131 of file CircleBidirectionalSequenceLSTM.h.
{ at(40)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_input_weights (void) const inline
Definition at line 130 of file CircleBidirectionalSequenceLSTM.h.
{ return at(40)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_output_weights (loco::Node * node) inline
Definition at line 137 of file CircleBidirectionalSequenceLSTM.h.
{ at(43)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_auxillary_input_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_output_weights (void) const inline
Definition at line 136 of file CircleBidirectionalSequenceLSTM.h.
{ return at(43)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_cell_gate_bias (loco::Node * node) inline
Definition at line 70 of file CircleBidirectionalSequenceLSTM.h.
{ at(14)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_cell_gate_bias (void) const inline
Definition at line 69 of file CircleBidirectionalSequenceLSTM.h.
{ return at(14)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_state() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_cell_state (loco::Node * node) inline
Definition at line 121 of file CircleBidirectionalSequenceLSTM.h.
{ at(36)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_state() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_cell_state (void) const inline
Definition at line 120 of file CircleBidirectionalSequenceLSTM.h.
{ return at(36)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_cell_to_forget_weights (loco::Node * node) inline
Definition at line 61 of file CircleBidirectionalSequenceLSTM.h.
{ at(10)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_cell_to_forget_weights (void) const inline
Definition at line 60 of file CircleBidirectionalSequenceLSTM.h.
{ return at(10)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_cell_to_input_weights (loco::Node * node) inline
Definition at line 59 of file CircleBidirectionalSequenceLSTM.h.
{ at(9)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_cell_to_input_weights (void) const inline
Definition at line 58 of file CircleBidirectionalSequenceLSTM.h.
{ return at(9)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_cell_to_output_weights (loco::Node * node) inline
Definition at line 63 of file CircleBidirectionalSequenceLSTM.h.
{ at(11)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_cell_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_cell_to_output_weights (void) const inline
Definition at line 62 of file CircleBidirectionalSequenceLSTM.h.
{ return at(11)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_forget_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_forget_gate_bias (loco::Node * node) inline
Definition at line 68 of file CircleBidirectionalSequenceLSTM.h.
{ at(13)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_forget_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_forget_gate_bias (void) const inline
Definition at line 67 of file CircleBidirectionalSequenceLSTM.h.
{ return at(13)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_input_gate_bias (loco::Node * node) inline
Definition at line 66 of file CircleBidirectionalSequenceLSTM.h.
{ at(12)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_input_gate_bias (void) const inline
Definition at line 65 of file CircleBidirectionalSequenceLSTM.h.
{ return at(12)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_input_to_cell_weights (loco::Node * node) inline
Definition at line 45 of file CircleBidirectionalSequenceLSTM.h.
{ at(3)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_input_to_cell_weights (void) const inline
Definition at line 44 of file CircleBidirectionalSequenceLSTM.h.
{ return at(3)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_input_to_forget_weights (loco::Node * node) inline
Definition at line 43 of file CircleBidirectionalSequenceLSTM.h.
{ at(2)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_input_to_forget_weights (void) const inline
Definition at line 42 of file CircleBidirectionalSequenceLSTM.h.
{ return at(2)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_input_to_input_weights (loco::Node * node) inline
Definition at line 41 of file CircleBidirectionalSequenceLSTM.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_input_to_input_weights (void) const inline
Definition at line 40 of file CircleBidirectionalSequenceLSTM.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_input_to_output_weights (loco::Node * node) inline
Definition at line 47 of file CircleBidirectionalSequenceLSTM.h.
{ at(4)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_input_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_input_to_output_weights (void) const inline
Definition at line 46 of file CircleBidirectionalSequenceLSTM.h.
{ return at(4)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_output_gate_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_output_gate_bias (loco::Node * node) inline
Definition at line 72 of file CircleBidirectionalSequenceLSTM.h.
{ at(15)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_output_gate_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_output_gate_bias (void) const inline
Definition at line 71 of file CircleBidirectionalSequenceLSTM.h.
{ return at(15)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_projection_bias() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_projection_bias (loco::Node * node) inline
Definition at line 77 of file CircleBidirectionalSequenceLSTM.h.
{ at(17)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_projection_bias() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_projection_bias (void) const inline
Definition at line 76 of file CircleBidirectionalSequenceLSTM.h.
{ return at(17)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_projection_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_projection_weights (loco::Node * node) inline
Definition at line 75 of file CircleBidirectionalSequenceLSTM.h.
{ at(16)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_projection_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_projection_weights (void) const inline
Definition at line 74 of file CircleBidirectionalSequenceLSTM.h.
{ return at(16)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_cell_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_cell_weights (loco::Node * node) inline
Definition at line 54 of file CircleBidirectionalSequenceLSTM.h.
{ at(7)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_cell_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_cell_weights (void) const inline
Definition at line 53 of file CircleBidirectionalSequenceLSTM.h.
{ return at(7)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_forget_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_forget_weights (loco::Node * node) inline
Definition at line 52 of file CircleBidirectionalSequenceLSTM.h.
{ at(6)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_forget_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_forget_weights (void) const inline
Definition at line 51 of file CircleBidirectionalSequenceLSTM.h.
{ return at(6)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_input_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_input_weights (loco::Node * node) inline
Definition at line 50 of file CircleBidirectionalSequenceLSTM.h.
{ at(5)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_input_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_input_weights (void) const inline
Definition at line 49 of file CircleBidirectionalSequenceLSTM.h.
{ return at(5)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_output_weights() [1/2]
void luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_output_weights (loco::Node * node) inline
Definition at line 56 of file CircleBidirectionalSequenceLSTM.h.
{ at(8)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
fw_recurrent_to_output_weights() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_output_weights (void) const inline
Definition at line 55 of file CircleBidirectionalSequenceLSTM.h.
{ return at(8)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input() [1/2]
void luci::CircleBidirectionalSequenceLSTM::input (loco::Node * node) inline
Definition at line 38 of file CircleBidirectionalSequenceLSTM.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleBidirectionalSequenceLSTM::input (void) const inline
Definition at line 37 of file CircleBidirectionalSequenceLSTM.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 48, CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
merge_outputs() [1/2]
void luci::CircleBidirectionalSequenceLSTM::merge_outputs (bool merge_outputs) inline
Definition at line 153 of file CircleBidirectionalSequenceLSTM.h.
{ _merge_outputs = merge_outputs; }
References merge_outputs().
Referenced by merge_outputs().
merge_outputs() [2/2]
bool luci::CircleBidirectionalSequenceLSTM::merge_outputs (void) const inline
Definition at line 152 of file CircleBidirectionalSequenceLSTM.h.
{ return _merge_outputs; }
Referenced by luci::BuiltinOptionsExtractor::visit().
proj_clip() [1/2]
void luci::CircleBidirectionalSequenceLSTM::proj_clip (float proj_clip) inline
Definition at line 151 of file CircleBidirectionalSequenceLSTM.h.
{ _proj_clip = proj_clip; }
References proj_clip().
Referenced by proj_clip().
proj_clip() [2/2]
float luci::CircleBidirectionalSequenceLSTM::proj_clip (void) const inline
Definition at line 150 of file CircleBidirectionalSequenceLSTM.h.
{ return _proj_clip; }
Referenced by luci::BuiltinOptionsExtractor::visit().
time_major() [1/2]
void luci::CircleBidirectionalSequenceLSTM::time_major (bool time_major) inline
Definition at line 155 of file CircleBidirectionalSequenceLSTM.h.
{ _time_major = time_major; }
References time_major().
Referenced by time_major().
time_major() [2/2]
bool luci::CircleBidirectionalSequenceLSTM::time_major (void) const inline
Definition at line 154 of file CircleBidirectionalSequenceLSTM.h.
{ return _time_major; }
Referenced by luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleBidirectionalSequenceLSTM.h