ONE - On-device Neural Engine: luci_interpreter::SimpleMemoryManager Class Reference
luci_interpreter::SimpleMemoryManager Class Reference
#include <SimpleMemoryManager.h>
Public Member Functions
void allocate_memory (luci_interpreter::Tensor &tensor) final
void release_memory (luci_interpreter::Tensor &tensor) final
void allocate_memory (luci_interpreter::Tensor &tensor) final
void release_memory (luci_interpreter::Tensor &tensor) final
void allocate_input_buf () final
void allocate_output_buf () final
void allocate_computing_buf () final
void release_computing_buf () final
void release_input_buf () final
void release_output_buf () final
void allocate_memory_for_input (luci_interpreter::Tensor &tensor) final
void allocate_memory_for_output (luci_interpreter::Tensor &tensor) final
Public Member Functions inherited from luci_interpreter::IMemoryManager
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
bool is_allocate_input () const
void is_allocate_input (bool allocate_input)
virtual void allocate_input_buf ()=0
virtual void allocate_output_buf ()=0
virtual void allocate_computing_buf ()=0
virtual void release_computing_buf ()=0
virtual void release_input_buf ()=0
virtual void release_output_buf ()=0
virtual void allocate_memory_for_input (luci_interpreter::Tensor &tensor)=0
virtual void allocate_memory_for_output (luci_interpreter::Tensor &tensor)=0
Additional Inherited Members
Protected Attributes inherited from luci_interpreter::IMemoryManager
bool _is_allocate_input = true
Detailed Description
Definition at line 25 of file SimpleMemoryManager.h.
Member Function Documentation
allocate_computing_buf()
void luci_interpreter::SimpleMemoryManager::allocate_computing_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 39 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
allocate_input_buf()
void luci_interpreter::SimpleMemoryManager::allocate_input_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 31 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
allocate_memory() [1/2]
void luci_interpreter::SimpleMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 22 of file SimpleMemoryManager.cpp.
{
  if (!tensor.is_allocatable())
  {
    return;
  }
  if (tensor.is_data_allocated())
  {
    release_memory(tensor);
  }
  const auto element_size = getDataTypeSize(tensor.element_type());
  const auto num_elements = tensor.shape().num_elements();
  auto *data = new uint8_t[num_elements * element_size];
  tensor.set_data_buffer(data);
}
References luci_interpreter::getDataTypeSize(), and release_memory().
allocate_memory() [2/2]
void luci_interpreter::SimpleMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
allocate_memory_for_input()
void luci_interpreter::SimpleMemoryManager::allocate_memory_for_input (luci_interpreter::Tensor & tensor) inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 55 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
allocate_memory_for_output()
void luci_interpreter::SimpleMemoryManager::allocate_memory_for_output (luci_interpreter::Tensor & tensor) inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 59 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
allocate_output_buf()
void luci_interpreter::SimpleMemoryManager::allocate_output_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 35 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
release_computing_buf()
void luci_interpreter::SimpleMemoryManager::release_computing_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 43 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
release_input_buf()
void luci_interpreter::SimpleMemoryManager::release_input_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 47 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
release_memory() [1/2]
void luci_interpreter::SimpleMemoryManager::release_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 39 of file SimpleMemoryManager.cpp.
{
  if (!tensor.is_data_allocated())
  {
    tensor.set_data_buffer(nullptr);
    return;
  }
  auto data = tensor.data<uint8_t>();
  delete[] data;
  tensor.set_data_buffer(nullptr);
}
Referenced by allocate_memory().
release_memory() [2/2]
void luci_interpreter::SimpleMemoryManager::release_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
release_output_buf()
void luci_interpreter::SimpleMemoryManager::release_output_buf () inline final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 51 of file SimpleMemoryManager.h.
  {
    assert(false && "Method can be used only for static memory manager");
  }
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/SimpleMemoryManager.h
onert-micro/luci-interpreter/src/memory_managers/SimpleMemoryManager.h
compiler/luci-interpreter/src/SimpleMemoryManager.cpp
onert-micro/luci-interpreter/src/memory_managers/SimpleMemoryManager.cpp