ONE - On-device Neural Engine: onert::dumper::dot::DotDumper Class Reference
onert::dumper::dot::DotDumper Class Reference
#include <DotDumper.h>
Public Types
enum Level { OFF = 0 , ALL_BUT_CONSTANTS = 1 , ALL = 2 }
Public Member Functions
DotDumper (Level level)
void dump (const ir::Graph &graph, const std::string &tag)
Dump graph information to dot file as tag name if "GRAPH_DOT_DUMP" is set.
void dump (const compiler::LoweredGraph &lowered_graph, const std::string &tag)
Dump lowered graph information to dot file as tag name if "GRAPH_DOT_DUMP" is set.
Detailed Description
Definition at line 30 of file DotDumper.h.
Member Enumeration Documentation
Level
enum onert::dumper::dot::DotDumper::Level
Enumerator
OFF
ALL_BUT_CONSTANTS
ALL
Definition at line 33 of file DotDumper.h.
  {
    OFF = 0,               //< Do not dump
    ALL_BUT_CONSTANTS = 1, //< Emit all operations and operands but constants
    ALL = 2                //< Emit all operations and operands
  };
Constructor & Destructor Documentation
DotDumper()
onert::dumper::dot::DotDumper::DotDumper (Level level) inline
Definition at line 41 of file DotDumper.h.
: _level{level} {}
Member Function Documentation
dump() [1/2]
void onert::dumper::dot::DotDumper::dump (const compiler::LoweredGraph & lowered_graph, const std::string & tag)
Dump lowered graph information to dot file as tag name if "GRAPH_DOT_DUMP" is set.
Parameters
[in] graph The graph that would be used to get operations and operands
[in] tag The name of dot file that would be created
Returns
N/A
Definition at line 216 of file DotDumper.cc.
{
  if (_level == Level::OFF)
  {
    return;
  }
  auto dot_operands = generate_dot_operands(lowered_graph.graph(), _level);
  auto dot_operations = generate_dot_operations(lowered_graph.graph(), dot_operands);
  update_lower_info(lowered_graph, &dot_operands);
  update_lower_info(lowered_graph, &dot_operations);
  dump_to_file(dot_operands, dot_operations, tag);
}
References onert::compiler::LoweredGraph::graph().
dump() [2/2]
void onert::dumper::dot::DotDumper::dump (const ir::Graph & graph, const std::string & tag)
Dump graph information to dot file as tag name if "GRAPH_DOT_DUMP" is set.
Parameters
[in] graph The graph that would be used to get operations and operands
[in] tag The name of dot file that would be created
Returns
N/A
Definition at line 204 of file DotDumper.cc.
{
  if (_level == Level::OFF)
  {
    return;
  }
  const auto dot_operands = generate_dot_operands(graph, _level);
  const auto dot_operations = generate_dot_operations(graph, dot_operands);
  dump_to_file(dot_operands, dot_operations, tag);
}
Referenced by onert::compiler::Compiler::compile(), and onert::compiler::MultiModelCompiler::compile().
The documentation for this class was generated from the following files:
runtime/onert/core/src/dumper/dot/DotDumper.h
runtime/onert/core/src/dumper/dot/DotDumper.cc