ONE - On-device Neural Engine: nnfw::cker::TopContainer< T, Tidx > Class Template Reference
nnfw::cker::TopContainer< T, Tidx > Class Template Reference
#include <TopKV2.h>
Public Member Functions
TopContainer ()=delete
TopContainer (uint32_t k, uint32_t row_size)
void start_collecting (const T *values)
void push (Tidx a)
const std::vector< Tidx > & sorted_result ()
Detailed Description
template<typename T, typename Tidx>
class nnfw::cker::TopContainer< T, Tidx >
Definition at line 26 of file TopKV2.h.
Constructor & Destructor Documentation
TopContainer() [1/2]
template<typename T , typename Tidx > nnfw::cker::TopContainer< T, Tidx >::TopContainer () delete
TopContainer() [2/2]
template<typename T , typename Tidx > nnfw::cker::TopContainer< T, Tidx >::TopContainer (uint32_t k, uint32_t row_size) inline
Definition at line 30 of file TopKV2.h.
                                              : k_(k)
  {
    container_.reserve(std::min(k, row_size) + 1);
  }
Member Function Documentation
push()
template<typename T , typename Tidx > void nnfw::cker::TopContainer< T, Tidx >::push (Tidx a) inline
Definition at line 42 of file TopKV2.h.
  {
    auto comparator = [this](Tidx a, Tidx b) { return compare_fun(a, b); };
    if (!is_heap_)
    {
      container_.push_back(a);
      if (container_.size() == k_ + 1)
      {
        std::make_heap(container_.begin(), container_.end(), comparator);
        std::pop_heap(container_.begin(), container_.end(), comparator);
        container_.pop_back();
        is_heap_ = true;
      }
    }
    else if (comparator(a, container_.front()))
    {
      // Due to how we defined comparator / compare_fun, container_.front()
      // contains the index of the smallest of the top-k elements seen so far.
      //
      // If control reaches this point, we know that the current index a
      // corresponds to an element which is bigger than the smallest of the
      // top-k elements seen so far.  Hence, we have to update the indices of
      // the top-k elements, by removing the index of the smallest top-k
      // element, adding a, and making sure container_[0:k] is still a heap.
      std::pop_heap(container_.begin(), container_.end(), comparator);
      container_.back() = a;
      std::push_heap(container_.begin(), container_.end(), comparator);
    }
  }
Referenced by nnfw::cker::TopKV2().
sorted_result()
template<typename T , typename Tidx > const std::vector< Tidx > & nnfw::cker::TopContainer< T, Tidx >::sorted_result () inline
Definition at line 72 of file TopKV2.h.
  {
    auto comparator = [this](Tidx a, Tidx b) { return compare_fun(a, b); };
    if (!is_heap_)
    {
      // Note: due to the way we defined compare_fun (see comments for that
      // function) std::sort puts the indices from container_ in decreasing
      // order of the corresponding elements.
      std::sort(container_.begin(), container_.end(), comparator);
    }
    else
    {
      std::sort_heap(container_.begin(), container_.end(), comparator);
    }
    return container_;
  }
Referenced by nnfw::cker::TopKV2().
start_collecting()
template<typename T , typename Tidx > void nnfw::cker::TopContainer< T, Tidx >::start_collecting (const T * values) inline
Definition at line 35 of file TopKV2.h.
  {
    values_ = values;
    container_.clear();
    is_heap_ = false;
  }
Referenced by nnfw::cker::TopKV2().
The documentation for this class was generated from the following file:
runtime/compute/cker/include/cker/operation/TopKV2.h