ONE - On-device Neural Engine: minmax_embedder_test::H5Writer Class Reference
minmax_embedder_test::H5Writer Class Reference
#include <H5Writer.h>
Public Member Functions
H5Writer (const ModelSpec &md_spec, const std::string &filepath)
void dump ()
Detailed Description
Definition at line 42 of file H5Writer.h.
Constructor & Destructor Documentation
H5Writer()
minmax_embedder_test::H5Writer::H5Writer (const ModelSpec & md_spec, const std::string & filepath)
Definition at line 45 of file H5Writer.cpp.
  : _md_spec{md_spec}, _filepath{filepath}
{
}
Member Function Documentation
dump()
void minmax_embedder_test::H5Writer::dump ()
Definition at line 50 of file H5Writer.cpp.
{
  // NOTE: H5Writer
  H5::H5File h5file{_filepath, H5F_ACC_CREAT | H5F_ACC_RDWR};
  auto root_grp = h5file.openGroup("/");
  ensureGroup(root_grp, h5_value_grpname);
  auto val_grp = h5file.openGroup(h5_value_grpname);
  // NOTE: Writer
  uint32_t num_run = to_u32(val_grp.getNumObjs());
  auto run_grp = val_grp.createGroup(("run_") + std::to_string(num_run));
  // Assumption: single subgraph
  auto model_grp = ensureGroup(run_grp, std::string("model_") + "0");
  hsize_t dims[] = {2};
  H5::DataSpace dspace(1, dims); // rank=1, dim(0)=2, {min, max}
  DataGen gen;
  // dump input minmax
  for (uint32_t i = 0; i < _md_spec.n_inputs; ++i)
  {
    const auto subg_idx = 0;
    auto subg_grp = ensureGroup(model_grp, std::string("subg_") + std::to_string(subg_idx).c_str());
    auto input_dset = subg_grp.createDataSet(std::string("input_") + std::to_string(i),
                                             H5::PredType::IEEE_F32BE, dspace);
    auto minmax = gen(num_run, i);
    input_dset.write(gen(num_run, i).data(), H5::PredType::NATIVE_FLOAT);
  }
  // dump op minmax
  for (uint32_t op = 0; op < _md_spec.n_ops; ++op)
  {
    const auto subg_idx = 0;
    auto subg_grp = ensureGroup(model_grp, std::string("subg_") + std::to_string(subg_idx).c_str());
    auto op_dset = subg_grp.createDataSet(std::string("op_") + std::to_string(op),
                                          H5::PredType::IEEE_F32BE, dspace);
    op_dset.write(gen(num_run, op).data(), H5::PredType::NATIVE_FLOAT);
  }
}
References minmax_embedder_test::ensureGroup(), minmax_embedder_test::ModelSpec::n_inputs, minmax_embedder_test::ModelSpec::n_ops, and minmax_embedder_test::to_u32().
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/minmax-embedder-value-test/gen/src/H5Writer.h
compiler/minmax-embedder-value-test/gen/src/H5Writer.cpp