ONE - On-device Neural Engine: nnc::ArtifactFunctionCall Class Reference
nnc::ArtifactFunctionCall Class Reference
Represents a function call.
#include <ArtifactModel.h>
Public Member Functions
ArtifactFunctionCall (std::string func_name, std::list< std::shared_ptr< ArtifactExpr > > param_list, std::shared_ptr< ArtifactExpr > on=nullptr, ArtifactCallType call_type=ArtifactCallType::obj)
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
const std::string & funcName () const
const std::list< std::shared_ptr< ArtifactExpr > > & paramList () const
std::shared_ptr< ArtifactExpr > on () const
ArtifactCallType callType () const
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents a function call.
Definition at line 169 of file ArtifactModel.h.
Constructor & Destructor Documentation
ArtifactFunctionCall()
nnc::ArtifactFunctionCall::ArtifactFunctionCall (std::string func_name, std::list< std::shared_ptr< ArtifactExpr > > param_list, std::shared_ptr< ArtifactExpr > on = nullptr, ArtifactCallType call_type = ArtifactCallType::obj)
Definition at line 25 of file ArtifactModel.cpp.
  : _funcName(std::move(func_name)), _callType(call_type), _on(std::move(on)),
    _paramList(std::move(param_list))
{
}
Member Function Documentation
accept()
void nnc::ArtifactFunctionCall::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Definition at line 176 of file ArtifactModel.h.
{ g->visit(this); }
callType()
ArtifactCallType nnc::ArtifactFunctionCall::callType () const inline
Definition at line 181 of file ArtifactModel.h.
{ return _callType; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
funcName()
const std::string & nnc::ArtifactFunctionCall::funcName () const inline
Definition at line 178 of file ArtifactModel.h.
{ return _funcName; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
on()
std::shared_ptr< ArtifactExpr > nnc::ArtifactFunctionCall::on () const inline
Definition at line 180 of file ArtifactModel.h.
{ return _on; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
paramList()
const std::list< std::shared_ptr< ArtifactExpr > > & nnc::ArtifactFunctionCall::paramList () const inline
Definition at line 179 of file ArtifactModel.h.
{ return _paramList; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
The documentation for this class was generated from the following files:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h
compiler/nnc/backends/acl_soft_backend/ArtifactModel.cpp