ONE - On-device Neural Engine: arm_compute::NEGEMMMatrixAccumulateBiasesKernel Class Reference
arm_compute::NEGEMMMatrixAccumulateBiasesKernel Class Reference
#include <NEGEMMMatrixAccumulateBiasesKernel.h>
Public Member Functions
const char * name () const override
NEGEMMMatrixAccumulateBiasesKernel ()
NEGEMMMatrixAccumulateBiasesKernel (const NEGEMMMatrixAccumulateBiasesKernel &)=delete
NEGEMMMatrixAccumulateBiasesKernel & operator= (const NEGEMMMatrixAccumulateBiasesKernel &)=delete
NEGEMMMatrixAccumulateBiasesKernel (NEGEMMMatrixAccumulateBiasesKernel &&)=default
NEGEMMMatrixAccumulateBiasesKernel & operator= (NEGEMMMatrixAccumulateBiasesKernel &&)=default
~NEGEMMMatrixAccumulateBiasesKernel ()=default
void configure (ITensor *accum, const ITensor *biases)
void run (const Window &window, const ThreadInfo &info) override
Static Public Member Functions
static Status validate (const ITensorInfo *accum, const ITensorInfo *biases)
Detailed Description
NEON kernel to add a bias to each row of the input tensor
Definition at line 49 of file NEGEMMMatrixAccumulateBiasesKernel.h.
Constructor & Destructor Documentation
NEGEMMMatrixAccumulateBiasesKernel() [1/3]
NEGEMMMatrixAccumulateBiasesKernel::NEGEMMMatrixAccumulateBiasesKernel ()
Default constructor
Definition at line 104 of file NEGEMMMatrixAccumulateBiasesKernel.cpp.
  : _accum(nullptr), _biases(nullptr)
{
}
NEGEMMMatrixAccumulateBiasesKernel() [2/3]
arm_compute::NEGEMMMatrixAccumulateBiasesKernel::NEGEMMMatrixAccumulateBiasesKernel (const NEGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEGEMMMatrixAccumulateBiasesKernel() [3/3]
arm_compute::NEGEMMMatrixAccumulateBiasesKernel::NEGEMMMatrixAccumulateBiasesKernel (NEGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved
~NEGEMMMatrixAccumulateBiasesKernel()
arm_compute::NEGEMMMatrixAccumulateBiasesKernel::~NEGEMMMatrixAccumulateBiasesKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void NEGEMMMatrixAccumulateBiasesKernel::configure (ITensor * accum, const ITensor * biases)
Set the accumulate buffer and the biases of the kernel.
Parameters
[in,out] accum The accumulate tensor to convert. Data type supported: F32
[in] biases The shared biases tensor to append. It must be 1D Tensor. Data type supported: Same as input
Definition at line 109 of file NEGEMMMatrixAccumulateBiasesKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(accum, biases);
  // Perform validate step
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(accum->info(), biases->info()));
  _biases = biases;
  _accum = accum;
  // Configure kernel window
  auto win_config = validate_and_configure_window(accum->info(), biases->info());
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  INEKernel::configure(win_config.second);
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::configure(), and arm_compute::NEFullyConnectedLayerEx::configure().
name()
const char * arm_compute::NEGEMMMatrixAccumulateBiasesKernel::name () const inline override
Definition at line 52 of file NEGEMMMatrixAccumulateBiasesKernel.h.
{ return "NEGEMMMatrixAccumulateBiasesKernel"; }
operator=() [1/2]
NEGEMMMatrixAccumulateBiasesKernel & arm_compute::NEGEMMMatrixAccumulateBiasesKernel::operator= (const NEGEMMMatrixAccumulateBiasesKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEGEMMMatrixAccumulateBiasesKernel & arm_compute::NEGEMMMatrixAccumulateBiasesKernel::operator= (NEGEMMMatrixAccumulateBiasesKernel &&) default
Allow instances of this class to be moved
run()
void NEGEMMMatrixAccumulateBiasesKernel::run (const Window & window, const ThreadInfo & info) override
Definition at line 136 of file NEGEMMMatrixAccumulateBiasesKernel.cpp.
{
  std::lock_guard<std::mutex> lock_guard(m);
  ARM_COMPUTE_UNUSED(info);
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
  Window win_biases;
  win_biases.set(Window::DimX,
                 Window::Dimension(window.x().start(), window.x().end(), window.x().step()));
  win_biases.set(Window::DimY, Window::Dimension(0, 1, 1));
  Iterator in0_out(_accum, window);
  Iterator in1(_biases, win_biases);
  switch (_accum->info()->data_type())
  {
    case DataType::F32:
    {
      execute_window_loop(
        window,
        [&](const Coordinates &) {
          const float32x4x4_t accum = vld4q_f32(reinterpret_cast<const float *>(in0_out.ptr()));
          const float32x4x4_t biases = vld4q_f32(reinterpret_cast<const float *>(in1.ptr()));
          const float32x4x4_t res = {
            {vaddq_f32(accum.val[0], biases.val[0]), vaddq_f32(accum.val[1], biases.val[1]),
             vaddq_f32(accum.val[2], biases.val[2]), vaddq_f32(accum.val[3], biases.val[3])}};
          vst4q_f32(reinterpret_cast<float *>(in0_out.ptr()), res);
        },
        in0_out, in1);
      break;
    }
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
    case DataType::F16:
    {
      execute_window_loop(
        window,
        [&](const Coordinates &) {
          const float16x8x2_t accum = vld2q_f16(reinterpret_cast<const float16_t *>(in0_out.ptr()));
          const float16x8x2_t biases = vld2q_f16(reinterpret_cast<const float16_t *>(in1.ptr()));
          const float16x8x2_t res = {
            {vaddq_f16(accum.val[0], biases.val[0]), vaddq_f16(accum.val[1], biases.val[1])}};
          vst2q_f16(reinterpret_cast<float16_t *>(in0_out.ptr()), res);
        },
        in0_out, in1);
      break;
    }
#endif /* __ARM_FEATURE_FP16_VECTOR_ARITHMETIC */
    default:
      ARM_COMPUTE_ERROR("Data type not supported");
      break;
  }
}
References info, and m.
validate()
Status NEGEMMMatrixAccumulateBiasesKernel::validate (const ITensorInfo * accum, const ITensorInfo * biases) static
Static function to check if given info will lead to a valid configuration of NEGEMMMatrixAccumulateBiasesKernel
Parameters
[in] accum The accumulate tensor to convert. Data type supported: F32
[in] biases The shared biases tensor to append. It must be 1D Tensor. Data type supported: Same as input
Returns
a status
Definition at line 125 of file NEGEMMMatrixAccumulateBiasesKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(accum, biases));
  ARM_COMPUTE_RETURN_ON_ERROR(
    validate_and_configure_window(accum->clone().get(), biases->clone().get()).first);
  return Status{};
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::validate(), arm_compute::NEFullyConnectedLayerEx::validate(), and ~NEGEMMMatrixAccumulateBiasesKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEGEMMMatrixAccumulateBiasesKernel.h
compute/ARMComputeEx/src/core/NEON/kernels/NEGEMMMatrixAccumulateBiasesKernel.cpp