ONE - On-device Neural Engine: record_hessian::HessianObserver Class Reference
record_hessian::HessianObserver Class Reference
#include <HessianObserver.h>
Public Member Functions
HessianObserver ()=default
void postTensorWrite (const luci::CircleNode *node, const luci_interpreter::Tensor *tensor) override
std::unique_ptr< HessianMap > hessianData ()
Public Member Functions inherited from luci_interpreter::ExecutionObserver
virtual ~ExecutionObserver ()
virtual void preOperatorExecute (const luci::CircleNode *node)
virtual void postOperatorExecute (const luci::CircleNode *node)
Detailed Description
Definition at line 30 of file HessianObserver.h.
Constructor & Destructor Documentation
HessianObserver()
record_hessian::HessianObserver::HessianObserver () default
Member Function Documentation
hessianData()
std::unique_ptr< HessianMap > record_hessian::HessianObserver::hessianData () inline
Definition at line 38 of file HessianObserver.h.
{ return _hessian_computer.getMap(); }
References record_hessian::HessianComputer::getMap().
postTensorWrite()
void record_hessian::HessianObserver::postTensorWrite (const luci::CircleNode * node, const luci_interpreter::Tensor * tensor) override virtual
Reimplemented from luci_interpreter::ExecutionObserver.
Definition at line 22 of file HessianObserver.cpp.
{
  assert(node != nullptr);
  assert(tensor != nullptr);
  auto node_outputs = loco::succs(node);
  for (auto node_output : node_outputs)
  {
    auto cur_node = dynamic_cast<luci::CircleNode *>(node_output);
    if (cur_node == nullptr)
    {
      throw std::runtime_error("Record Hessian: node output shouldn't be null.");
    }
    // TODO : ADD TCONV/DepthCONV cases
    if (cur_node->opcode() == luci::CircleOpcode::FULLY_CONNECTED ||
        cur_node->opcode() == luci::CircleOpcode::CONV_2D)
    {
      _hessian_computer.recordHessian(cur_node, tensor);
    }
  }
}
References record_hessian::HessianComputer::recordHessian(), and loco::succs().
The documentation for this class was generated from the following files:
compiler/record-hessian/include/record-hessian/HessianObserver.h
compiler/record-hessian/src/HessianObserver.cpp