ONE - On-device Neural Engine: onert::backend::cpu::ops::ResizeBilinearLayer Class Reference
onert::backend::cpu::ops::ResizeBilinearLayer Class Reference
#include <ResizeBilinearLayer.h>
Public Member Functions
ResizeBilinearLayer ()
void configure (const IPortableTensor *input1, IPortableTensor *output, const IPortableTensor *size, bool align_corners, bool half_pixel_centers)
void configure (const IPortableTensor *input, IPortableTensor *output, int32_t output_height, int32_t output_width, bool align_corners, bool half_pixel_centers)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file ResizeBilinearLayer.h.
Constructor & Destructor Documentation
ResizeBilinearLayer()
onert::backend::cpu::ops::ResizeBilinearLayer::ResizeBilinearLayer ()
Definition at line 30 of file ResizeBilinearLayer.cc.
  : _input(nullptr), _output(nullptr), _size(nullptr), _output_height(0), _output_width(0),
    _align_corners(false), _half_pixel_centers(false)
{
  // DO NOTHING
}
Member Function Documentation
configure() [1/2]
void onert::backend::cpu::ops::ResizeBilinearLayer::configure (const IPortableTensor * input, IPortableTensor * output, int32_t output_height, int32_t output_width, bool align_corners, bool half_pixel_centers)
Definition at line 49 of file ResizeBilinearLayer.cc.
{
  assert(_size == nullptr);
  if (output_height < 0)
  {
    throw std::runtime_error{"ResizeBilinear: size value must be positive value, output_height = " +
                             std::to_string(output_height)};
  }
  if (output_width < 0)
  {
    throw std::runtime_error{"ResizeBilinear: size value must be positive value, output_width = " +
                             std::to_string(output_width)};
  }
  _input = input;
  _output = output;
  _output_height = output_height;
  _output_width = output_width;
  _align_corners = align_corners;
  _half_pixel_centers = half_pixel_centers;
}
configure() [2/2]
void onert::backend::cpu::ops::ResizeBilinearLayer::configure (const IPortableTensor * input1, IPortableTensor * output, const IPortableTensor * size, bool align_corners, bool half_pixel_centers)
Definition at line 37 of file ResizeBilinearLayer.cc.
{
  assert(!size->is_constant());
  _input = input;
  _output = output;
  _size = size;
  _align_corners = align_corners;
  _half_pixel_centers = half_pixel_centers;
}
run()
void onert::backend::cpu::ops::ResizeBilinearLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 72 of file ResizeBilinearLayer.cc.
{
  nnfw::cker::ResizeBilinearParams params;
  if (_size == nullptr)
  {
    params.output_height = _output_height;
    params.output_width = _output_width;
  }
  else
  {
    const auto size_buf = getBuffer<int32_t>(_size);
    params.output_height = size_buf[0];
    params.output_width = size_buf[1];
  }
  params.align_corners = _align_corners;
  params.half_pixel_centers = _half_pixel_centers;
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
      nnfw::cker::ResizeBilinear(params, getShape(_input), getBuffer<float>(_input),
                                 getShape(_output), getBuffer<float>(_output));
      break;
    case OperandType::QUANT_UINT8_ASYMM:
      nnfw::cker::ResizeBilinear(params, getShape(_input), getBuffer<uint8_t>(_input),
                                 getShape(_output), getBuffer<uint8_t>(_output));
      break;
    case OperandType::QUANT_INT8_ASYMM:
      nnfw::cker::ResizeBilinear(params, getShape(_input), getBuffer<int8_t>(_input),
                                 getShape(_output), getBuffer<int8_t>(_output));
      break;
    case OperandType::UINT8:
    case OperandType::BOOL8:
    case OperandType::FLOAT16:
    case OperandType::INT32:
    case OperandType::INT64:
    case OperandType::QUANT_INT8_SYMM:
      std::runtime_error("ResizeBilinear NYI");
      break;
    default:
      std::runtime_error("ResizeBilinear unsupported data type");
  }
}
References nnfw::cker::ResizeBilinearParams::align_corners, onert::backend::ITensor::data_type(), onert::backend::cpu::ops::getShape(), nnfw::cker::ResizeBilinearParams::half_pixel_centers, nnfw::cker::ResizeBilinearParams::output_height, nnfw::cker::ResizeBilinearParams::output_width, and nnfw::cker::ResizeBilinear().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ResizeBilinearLayer.h
runtime/onert/backend/cpu/ops/ResizeBilinearLayer.cc