ONE - On-device Neural Engine: onert::backend::acl_cl::Config Class Reference
onert::backend::acl_cl::Config Class Reference
#include <Config.h>
Public Member Functions
std::string id () override
Returns ID of the backend.
bool initialize () override
Initialize the backend. This is called as soon as the backend is loaded.
bool supportPermutation () override
ir::Layout supportLayout (const ir::Operation &node, ir::Layout frontend_layout) override
Returns supported layout for the given node and frontend_layout.
bool supportDynamicTensor () override
bool supportFP16 () override
void sync () const override
The function that is called after each Operation run on profiling mode. This may be useful for profiling GPU-based or special computing units.
std::unique_ptr< util::ITimer > timer () override
Returns Timer object for this backend. For some computing units, it may need its own Timer implementation.
Public Member Functions inherited from onert::backend::IConfig
virtual ~IConfig ()=default
virtual std::string id ()=0
Returns ID of the backend.
virtual bool initialize ()=0
Initialize the backend. This is called as soon as the backend is loaded.
virtual ir::Layout supportLayout (const ir::Operation &node, ir::Layout frontend_layout)=0
Returns supported layout for the given node and frontend_layout.
virtual void sync () const
The function that is called after each Operation run on profiling mode. This may be useful for profiling GPU-based or special computing units.
virtual std::unique_ptr< util::ITimer > timer ()
Returns Timer object for this backend. For some computing units, it may need its own Timer implementation.
virtual bool supportPermutation ()=0
virtual bool supportDynamicTensor ()=0
virtual bool supportFP16 ()=0
Detailed Description
Definition at line 32 of file Config.h.
Member Function Documentation
id()
std::string onert::backend::acl_cl::Config::id () inline override virtual
Returns ID of the backend.
Returns
std::string ID of this backend
Implements onert::backend::IConfig.
Definition at line 35 of file Config.h.
{ return "acl_cl"; }
initialize()
bool onert::backend::acl_cl::Config::initialize () override virtual
Initialize the backend. This is called as soon as the backend is loaded.
Returns
true Initialization succeeded
false Initialization failed, so it cannot use this backend
Implements onert::backend::IConfig.
Definition at line 35 of file Config.cc.
{
  if (!arm_compute::opencl_is_available())
  {
    return false;
  }
  arm_compute::CLScheduler::get().default_init();
  // NOTE CLKernelLibraryEx must use the same context as CLScheduler
  // It did not check whether another device is available.
  arm_compute::CLKernelLibraryEx::get().init(
    "./cl_kernels/", arm_compute::CLScheduler::get().context(), cl::Device::getDefault());
  return true;
}
References arm_compute::CLKernelLibraryEx::get(), and arm_compute::CLKernelLibraryEx::init().
supportDynamicTensor()
bool onert::backend::acl_cl::Config::supportDynamicTensor () inline override virtual
Implements onert::backend::IConfig.
Definition at line 39 of file Config.h.
{ return false; }
supportFP16()
bool onert::backend::acl_cl::Config::supportFP16 () inline override virtual
Implements onert::backend::IConfig.
Definition at line 40 of file Config.h.
{ return true; }
supportLayout()
ir::Layout onert::backend::acl_cl::Config::supportLayout (const ir::Operation & node, ir::Layout frontend_layout) override virtual
Returns supported layout for the given node and frontend_layout.
Parameters
node Operation
frontend_layout The layout defined in the model
Returns
ir::Layout The layout that the backend kernel actually uses
Implements onert::backend::IConfig.
Definition at line 50 of file Config.cc.
{
  const std::string acl_layout_str = util::getConfigString(util::config::ACL_LAYOUT);
  if (acl_layout_str == "NHWC")
  {
    return ir::Layout::NHWC;
  }
  else if (acl_layout_str == "NCHW")
  {
    return ir::Layout::NCHW;
  }
  return frontend_layout;
}
References onert::util::getConfigString(), onert::ir::NCHW, and onert::ir::NHWC.
supportPermutation()
bool onert::backend::acl_cl::Config::supportPermutation () inline override virtual
Implements onert::backend::IConfig.
Definition at line 37 of file Config.h.
{ return true; }
sync()
void onert::backend::acl_cl::Config::sync () const inline override virtual
The function that is called after each Operation run on profiling mode. This may be useful for profiling GPU-based or special computing units.
Reimplemented from onert::backend::IConfig.
Definition at line 41 of file Config.h.
{ arm_compute::CLScheduler::get().sync(); }
timer()
std::unique_ptr< util::ITimer > onert::backend::acl_cl::Config::timer () inline override virtual
Returns Timer object for this backend. For some computing units, it may need its own Timer implementation.
Returns
std::unique_ptr<util::ITimer> Timer object for this backend
Reimplemented from onert::backend::IConfig.
Definition at line 43 of file Config.h.
{ return std::make_unique<CLTimer>(); }
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/Config.h
runtime/onert/backend/acl_cl/Config.cc