ONE - On-device Neural Engine: luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc > Class Reference
luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc > Class Reference
#include <CircleNodeMixins.h>
Public Member Functions
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Detailed Description
Definition at line 39 of file CircleNodeMixins.h.
Constructor & Destructor Documentation
CircleNodeMixin()
luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::CircleNodeMixin () default
Member Function Documentation
fusedActivationFunction() [1/2]
FusedActFunc luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction () const inline
Definition at line 45 of file CircleNodeMixins.h.
{ return _fused_act_fun; }
Referenced by luci::CloneNodeLet< CN::ABC >::visit(), luci::CloneNode::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), luci::CloneNodeLet< CN::DEF >::visit(), luci::CloneNodeLet< CN::KLMN >::visit(), luci::CloneNodeLet< CN::STUV >::visit(), and luci::BuiltinOptionsExtractor::visit().
fusedActivationFunction() [2/2]
void luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction (FusedActFunc fused_act_fun) inline
Definition at line 46 of file CircleNodeMixins.h.
{ _fused_act_fun = fused_act_fun; }
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/CircleNodeMixins.h