ONE - On-device Neural Engine: luci::CircleMaxPool2D Class Reference
luci::CircleMaxPool2D Class Reference final
MAX_POOL_2D in Circle.
#include <CircleMaxPool2D.h>
Public Member Functions
loco::Node * value (void) const
void value (loco::Node *node)
Padding padding () const
void padding (Padding padding)
const Filter * filter (void) const
Filter * filter (void)
const Stride * stride (void) const
Stride * stride (void)
Public Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::MAX_POOL_2D >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >
loco::Use * at (uint32_t n) const
Detailed Description
MAX_POOL_2D in Circle.
Definition at line 35 of file CircleMaxPool2D.h.
Member Function Documentation
filter() [1/2]
Filter * luci::CircleMaxPool2D::filter (void) inline
Definition at line 47 of file CircleMaxPool2D.h.
{ return &_filter; }
filter() [2/2]
const Filter * luci::CircleMaxPool2D::filter (void) const inline
Definition at line 46 of file CircleMaxPool2D.h.
{ return &_filter; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
padding() [1/2]
Padding luci::CircleMaxPool2D::padding () const inline
Definition at line 43 of file CircleMaxPool2D.h.
{ return _padding; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
padding() [2/2]
void luci::CircleMaxPool2D::padding (Padding padding) inline
Definition at line 44 of file CircleMaxPool2D.h.
{ _padding = padding; }
References padding().
Referenced by padding().
stride() [1/2]
Stride * luci::CircleMaxPool2D::stride (void) inline
Definition at line 50 of file CircleMaxPool2D.h.
{ return &_stride; }
stride() [2/2]
const Stride * luci::CircleMaxPool2D::stride (void) const inline
Definition at line 49 of file CircleMaxPool2D.h.
{ return &_stride; }
Referenced by luci::CloneNodeLet< CN::KLMN >::visit(), and luci::BuiltinOptionsExtractor::visit().
value() [1/2]
void luci::CircleMaxPool2D::value (loco::Node * node) inline
Definition at line 40 of file CircleMaxPool2D.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >::at(), and loco::Use::node().
value() [2/2]
loco::Node * luci::CircleMaxPool2D::value (void) const inline
Definition at line 39 of file CircleMaxPool2D.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::MAX_POOL_2D > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleMaxPool2D.h