ONE - On-device Neural Engine: luci_interpreter::kernels::SISOKernel Class Reference
luci_interpreter::kernels::SISOKernel Class Reference
#include <SISOKernel.h>
Public Member Functions
SISOKernel (const circle::Operator *cur_op, BaseRuntimeGraph *runtime_graph)
const circle::Tensor * input () const
const circle::Tensor * output () const
Detailed Description
Definition at line 28 of file SISOKernel.h.
Constructor & Destructor Documentation
SISOKernel()
luci_interpreter::kernels::SISOKernel::SISOKernel (const circle::Operator * cur_op, BaseRuntimeGraph * runtime_graph) inline
Definition at line 31 of file SISOKernel.h.
  {
    const auto input_index = cur_op->inputs()->operator[](0);
    const auto output_index = cur_op->outputs()->operator[](0);
    assert(input_index != -1);
    assert(output_index != -1);
    _input_tensor = runtime_graph->getCircleTensorByIndex(input_index);
    _output_tensor = runtime_graph->getCircleTensorByIndex(output_index);
    assert(_input_tensor != nullptr);
    assert(_output_tensor != nullptr);
  }
References luci_interpreter::RuntimeGraph::getCircleTensorByIndex().
Member Function Documentation
input()
const circle::Tensor * luci_interpreter::kernels::SISOKernel::input () const inline
Definition at line 46 of file SISOKernel.h.
{ return _input_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleAbs(), luci_interpreter::configure_kernel_CircleCast(), luci_interpreter::configure_kernel_CircleCeil(), luci_interpreter::configure_kernel_CircleCos(), luci_interpreter::configure_kernel_CircleDepthToSpace(), luci_interpreter::configure_kernel_CircleDequantize(), luci_interpreter::configure_kernel_CircleElu(), luci_interpreter::configure_kernel_CircleExp(), luci_interpreter::configure_kernel_CircleL2Normalize(), luci_interpreter::configure_kernel_CircleLeakyRelu(), luci_interpreter::configure_kernel_CircleLog(), luci_interpreter::configure_kernel_CircleLogicalNot(), luci_interpreter::configure_kernel_CircleLogistic(), luci_interpreter::configure_kernel_CircleLogSoftmax(), luci_interpreter::configure_kernel_CirclePool2DCommon(), luci_interpreter::configure_kernel_CircleQuantize(), luci_interpreter::configure_kernel_CircleRelu(), luci_interpreter::configure_kernel_CircleRelu6(), luci_interpreter::configure_kernel_CircleRound(), luci_interpreter::configure_kernel_CircleRsqrt(), luci_interpreter::configure_kernel_CircleSin(), luci_interpreter::configure_kernel_CircleSoftmax(), luci_interpreter::configure_kernel_CircleSpaceToDepth(), luci_interpreter::configure_kernel_CircleSqrt(), luci_interpreter::configure_kernel_CircleSquare(), luci_interpreter::configure_kernel_CircleSqueeze(), luci_interpreter::configure_kernel_CircleTanh(), luci_interpreter::configure_kernel_CircleZerosLike(), luci_interpreter::createPoolParams(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleAveragePool2D(), luci_interpreter::execute_kernel_CircleCast(), luci_interpreter::execute_kernel_CircleCeil(), luci_interpreter::execute_kernel_CircleCos(), luci_interpreter::execute_kernel_CircleDepthToSpace(), luci_interpreter::execute_kernel_CircleDequantize(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleL2Normalize(), luci_interpreter::execute_kernel_CircleL2Pool2D(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLog(), luci_interpreter::execute_kernel_CircleLogicalNot(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleLogSoftmax(), luci_interpreter::execute_kernel_CircleMaxPool2D(), luci_interpreter::execute_kernel_CircleQuantize(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleRound(), luci_interpreter::execute_kernel_CircleRsqrt(), luci_interpreter::execute_kernel_CircleShape(), luci_interpreter::execute_kernel_CircleSin(), luci_interpreter::execute_kernel_CircleSoftmax(), luci_interpreter::execute_kernel_CircleSpaceToDepth(), luci_interpreter::execute_kernel_CircleSqrt(), luci_interpreter::execute_kernel_CircleSquare(), luci_interpreter::execute_kernel_CircleSqueeze(), luci_interpreter::execute_kernel_CircleTanh(), and luci_interpreter::execute_kernel_CircleZerosLike().
output()
const circle::Tensor * luci_interpreter::kernels::SISOKernel::output () const inline
Definition at line 47 of file SISOKernel.h.
{ return _output_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleAbs(), luci_interpreter::configure_kernel_CircleCast(), luci_interpreter::configure_kernel_CircleCeil(), luci_interpreter::configure_kernel_CircleCos(), luci_interpreter::configure_kernel_CircleDepthToSpace(), luci_interpreter::configure_kernel_CircleDequantize(), luci_interpreter::configure_kernel_CircleElu(), luci_interpreter::configure_kernel_CircleExp(), luci_interpreter::configure_kernel_CircleL2Normalize(), luci_interpreter::configure_kernel_CircleLeakyRelu(), luci_interpreter::configure_kernel_CircleLog(), luci_interpreter::configure_kernel_CircleLogicalNot(), luci_interpreter::configure_kernel_CircleLogistic(), luci_interpreter::configure_kernel_CircleLogSoftmax(), luci_interpreter::configure_kernel_CirclePool2DCommon(), luci_interpreter::configure_kernel_CircleQuantize(), luci_interpreter::configure_kernel_CircleRelu(), luci_interpreter::configure_kernel_CircleRelu6(), luci_interpreter::configure_kernel_CircleRound(), luci_interpreter::configure_kernel_CircleRsqrt(), luci_interpreter::configure_kernel_CircleShape(), luci_interpreter::configure_kernel_CircleSin(), luci_interpreter::configure_kernel_CircleSoftmax(), luci_interpreter::configure_kernel_CircleSpaceToDepth(), luci_interpreter::configure_kernel_CircleSqrt(), luci_interpreter::configure_kernel_CircleSquare(), luci_interpreter::configure_kernel_CircleSqueeze(), luci_interpreter::configure_kernel_CircleTanh(), luci_interpreter::configure_kernel_CircleZerosLike(), luci_interpreter::createPoolParams(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleAveragePool2D(), luci_interpreter::execute_kernel_CircleCast(), luci_interpreter::execute_kernel_CircleCeil(), luci_interpreter::execute_kernel_CircleCos(), luci_interpreter::execute_kernel_CircleDepthToSpace(), luci_interpreter::execute_kernel_CircleDequantize(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleL2Normalize(), luci_interpreter::execute_kernel_CircleL2Pool2D(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLog(), luci_interpreter::execute_kernel_CircleLogicalNot(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleLogSoftmax(), luci_interpreter::execute_kernel_CircleMaxPool2D(), luci_interpreter::execute_kernel_CircleQuantize(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleRound(), luci_interpreter::execute_kernel_CircleRsqrt(), luci_interpreter::execute_kernel_CircleShape(), luci_interpreter::execute_kernel_CircleSin(), luci_interpreter::execute_kernel_CircleSoftmax(), luci_interpreter::execute_kernel_CircleSpaceToDepth(), luci_interpreter::execute_kernel_CircleSqrt(), luci_interpreter::execute_kernel_CircleSquare(), luci_interpreter::execute_kernel_CircleSqueeze(), luci_interpreter::execute_kernel_CircleTanh(), and luci_interpreter::execute_kernel_CircleZerosLike().
The documentation for this class was generated from the following file:
onert-micro/luci-interpreter/src/kernels/SISOKernel.h