ONE - On-device Neural Engine: circle_eval_diff::MAPEPrinter Class Reference
circle_eval_diff::MAPEPrinter Class Reference final
#include <MetricPrinter.h>
Public Member Functions
void init (const luci::Module *first, const luci::Module *second)
void accumulate (const std::vector< std::shared_ptr< Tensor > > &first, const std::vector< std::shared_ptr< Tensor > > &second)
void dump (std::ostream &os) const
Public Member Functions inherited from circle_eval_diff::MetricPrinter
virtual ~MetricPrinter ()=default
virtual void init (const luci::Module *, const luci::Module *)
virtual void accumulate (const std::vector< std::shared_ptr< Tensor > > &first, const std::vector< std::shared_ptr< Tensor > > &second)=0
virtual void dump (std::ostream &os) const =0
Detailed Description
Definition at line 111 of file MetricPrinter.h.
Member Function Documentation
accumulate()
void circle_eval_diff::MAPEPrinter::accumulate (const std::vector< std::shared_ptr< Tensor > > & first, const std::vector< std::shared_ptr< Tensor > > & second) virtual
Implements circle_eval_diff::MetricPrinter.
Definition at line 254 of file MetricPrinter.cpp.
{
  assert(first.size() == second.size());        // FIX_CALLER_UNLESS
  assert(first.size() == _intermediate.size()); // FIX_CALLER_UNLESS
  for (uint32_t output_idx = 0; output_idx < _intermediate.size(); output_idx++)
  {
    const auto first_output = first[output_idx];
    const auto second_output = second[output_idx];
    // Cast data to fp32 and then compute absolute error
    const auto fp32_first_output = fp32(first_output);
    const auto fp32_second_output = fp32(second_output);
    accum_mean_absolute_error(output_idx, fp32_first_output, fp32_second_output);
  }
  _num_data++;
}
dump()
void circle_eval_diff::MAPEPrinter::dump (std::ostream & os) const virtual
Implements circle_eval_diff::MetricPrinter.
Definition at line 275 of file MetricPrinter.cpp.
{
  os << "Mean Absolute Percentage Error (MAPE)" << std::endl;
  for (uint32_t output_idx = 0; output_idx < _intermediate.size(); output_idx++)
  {
    const auto name = _output_names.at(output_idx);
    const auto &inter = _intermediate.at(output_idx);
    assert(inter.dtype() == loco::DataType::FLOAT32); // FIX_ME_UNLESS
    const auto elem_count = inter.size<loco::DataType::FLOAT32>();
    // Compute MAPE
    float mape = 0.0;
    for (uint32_t elem_idx = 0; elem_idx < elem_count; elem_idx++)
      mape += inter.at<loco::DataType::FLOAT32>(elem_idx);
    mape = mape / elem_count;
    mape = mape / _num_data;
    mape *= 100.0;
    os << "MAPE for " << name << " is " << mape << "%" << std::endl;
  }
}
init()
void circle_eval_diff::MAPEPrinter::init (const luci::Module * first, const luci::Module * second) virtual
Reimplemented from circle_eval_diff::MetricPrinter.
Definition at line 196 of file MetricPrinter.cpp.
{
  THROW_UNLESS(first != nullptr, "Invalid module.");
  THROW_UNLESS(second != nullptr, "Invalid module.");
  const auto first_output = loco::output_nodes(first->graph());
  const auto second_output = loco::output_nodes(second->graph());
  assert(first_output.size() == second_output.size()); // FIX_CALLER_UNLESS
  for (uint32_t i = 0; i < first_output.size(); i++)
  {
    const auto first_node = loco::must_cast<luci::CircleNode *>(first_output[i]);
    const auto second_node = loco::must_cast<luci::CircleNode *>(second_output[i]);
    // Create tensors to store intermediate results
    _intermediate.emplace_back();
    _intermediate.at(i).dtype(loco::DataType::FLOAT32);
    // NOTE Use both first_node and second_node to avoid release build break
    _intermediate.at(i).rank(first_node->rank());
    uint32_t num_elems = 1;
    for (uint32_t j = 0; j < second_node->rank(); j++)
    {
      _intermediate.at(i).dim(j) = second_node->dim(j);
      num_elems *= second_node->dim(j).value();
    }
    _intermediate.at(i).size<loco::DataType::FLOAT32>(num_elems);
    // Check the buffer is initilized with zero
    for (uint32_t j = 0; j < num_elems; j++)
      assert(_intermediate.at(i).at<loco::DataType::FLOAT32>(j) == 0.0);
    // Save output names for logging
    _output_names.emplace_back(first_node->name());
  }
}
References luci::Module::graph(), num_elems(), loco::output_nodes(), and THROW_UNLESS.
The documentation for this class was generated from the following files:
compiler/circle-eval-diff/src/MetricPrinter.h
compiler/circle-eval-diff/src/MetricPrinter.cpp