ONE - On-device Neural Engine: nncc::core::ADT::tensor::Shape Class Reference
nncc::core::ADT::tensor::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape ()=default
Shape (std::initializer_list< uint32_t > &&l)
uint32_t rank (void) const
Shape & resize (uint32_t size)
uint32_t & dim (uint32_t axis)
uint32_t dim (uint32_t axis) const
Shape & squeeze (void)
Detailed Description
Definition at line 33 of file Shape.h.
Constructor & Destructor Documentation
Shape() [1/2]
nncc::core::ADT::tensor::Shape::Shape () default
Shape() [2/2]
Shape::Shape (std::initializer_list< uint32_t > && l)
Definition at line 30 of file Shape.cpp.
                                              : _dims{l}
{
  // DO NOTHING
}
Member Function Documentation
dim() [1/2]
uint32_t & Shape::dim (uint32_t axis)
Definition at line 42 of file Shape.cpp.
{ return _dims.at(axis); }
Referenced by nncc::core::ADT::tensor::IndexEnumerator::advance(), morph::as_dims(), morph::caffe::as_feature_shape(), morph::nnapi::as_feature_shape(), morph::tflite::as_feature_shape(), morph::caffe::as_kernel_shape(), morph::nnapi::as_kernel_shape(), morph::tflite::as_kernel_shape(), caffeimport::as_tensor_shape(), tflimport::as_tensor_shape(), morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnkit::support::tf::Backend::Backend(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::conv2D_padding(), plier::tf::copy_shape(), tflimport::depthwiseConv2D_padding(), tflimport::get_padding(), nnkit::support::tf::Runner::getTensorShapeFromGraphDef(), ConvolutionSpec::ifm_dim(), nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator(), ConvolutionSpec::ker_shape(), nncc::core::ADT::tensor::num_elements(), ConvolutionSpec::ofm_shape(), PoolingSpec::ofm_shape(), nncc::core::ADT::tensor::operator==(), nnkit::support::tftestinfo::ParsedTensor::ParsedTensor(), nnkit::support::onnx::TensorContext::shape(), and nnkit::support::tflite::tensor_shape().
dim() [2/2]
uint32_t Shape::dim (uint32_t axis) const
Definition at line 43 of file Shape.cpp.
{ return _dims.at(axis); }
rank()
uint32_t Shape::rank (void) const
Definition at line 35 of file Shape.cpp.
{ return _dims.size(); }
Referenced by nncc::core::ADT::tensor::IndexEnumerator::advance(), morph::as_dims(), morph::caffe::as_feature_shape(), morph::nnapi::as_feature_shape(), morph::tflite::as_feature_shape(), morph::caffe::as_kernel_shape(), morph::nnapi::as_kernel_shape(), morph::tflite::as_kernel_shape(), ShapeQuery::axis(), axis_of(), nnkit::support::tf::Backend::Backend(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::get_padding(), ConvolutionSpec::ifm_rank(), nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::tensor::num_elements(), PoolingSpec::ofm_shape(), nncc::core::ADT::tensor::operator==(), HD5ExportAction::run(), and nncc::core::ADT::tensor::IndexEnumerator::valid().
resize()
Shape & Shape::resize (uint32_t size)
Definition at line 36 of file Shape.cpp.
{
  _dims.resize(size);
  return *this;
}
Referenced by caffeimport::as_tensor_shape(), tflimport::as_tensor_shape(), morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), plier::tf::copy_shape(), nnkit::support::tf::Runner::getTensorShapeFromGraphDef(), ConvolutionSpec::ker_shape(), ConvolutionSpec::ofm_shape(), PoolingSpec::ofm_shape(), nnkit::support::tftestinfo::ParsedTensor::ParsedTensor(), nnkit::support::onnx::TensorContext::shape(), and nnkit::support::tflite::tensor_shape().
squeeze()
Shape & Shape::squeeze (void)
Definition at line 45 of file Shape.cpp.
{
  _dims.erase(std::remove(_dims.begin(), _dims.end(), 1), _dims.end());
  return *this;
}
Referenced by nncc::core::ADT::tensor::squeeze().
The documentation for this class was generated from the following files:
compiler/angkor/include/nncc/core/ADT/tensor/Shape.h
compiler/angkor/src/ADT/tensor/Shape.cpp