ONE - On-device Neural Engine: onert::ir::TypeInfo Class Reference
onert::ir::TypeInfo Class Reference
#include <TypeInfo.h>
Public Member Functions
TypeInfo ()=delete
TypeInfo (DataType type)
TypeInfo (DataType type, float scale, int32_t zero_point)
DataType type () const
float scale () const
const std::vector< float > & scales () const
int32_t zero_point () const
const std::vector< int32_t > & zero_points () const
const ir::Sparsity * sparsity () const
void quantization (float scale, int32_t zero_point)
void quantization (std::vector< float > &&scales, std::vector< int32_t > &&zero_points)
void sparsity (std::shared_ptr< ir::Sparsity > sparsity)
void type (const DataType type)
Detailed Description
Definition at line 39 of file TypeInfo.h.
Constructor & Destructor Documentation
TypeInfo() [1/3]
onert::ir::TypeInfo::TypeInfo () delete
TypeInfo() [2/3]
onert::ir::TypeInfo::TypeInfo (DataType type) inline explicit
Definition at line 44 of file TypeInfo.h.
: _type{type}, _sparsity{nullptr} {}
TypeInfo() [3/3]
onert::ir::TypeInfo::TypeInfo (DataType type, float scale, int32_t zero_point) inline
Definition at line 46 of file TypeInfo.h.
                                                           : _type{type}, _sparsity{nullptr}
  {
    quantization(scale, zero_point);
  }
References quantization(), scale(), and zero_point().
Member Function Documentation
quantization() [1/2]
void onert::ir::TypeInfo::quantization (float scale, int32_t zero_point) inline
Definition at line 62 of file TypeInfo.h.
  {
    _quant.scales.resize(1);
    _quant.scales[0] = scale;
    _quant.zero_points.resize(1);
    _quant.zero_points[0] = zero_point;
  }
References scale(), onert::ir::Quantization::scales, zero_point(), and onert::ir::Quantization::zero_points.
Referenced by onert::base_loader::BaseLoader< LoaderDomain >::loadQuantization(), and TypeInfo().
quantization() [2/2]
void onert::ir::TypeInfo::quantization (std::vector< float > && scales, std::vector< int32_t > && zero_points) inline
Definition at line 69 of file TypeInfo.h.
  {
    _quant.scales = scales;
    _quant.zero_points = zero_points;
  }
References onert::ir::Quantization::scales, scales(), onert::ir::Quantization::zero_points, and zero_points().
scale()
float onert::ir::TypeInfo::scale () const inline
Definition at line 53 of file TypeInfo.h.
{ return _quant.scales[0]; }
References onert::ir::Quantization::scales.
Referenced by onert::backend::acl_common::asTensorInfo(), onert::backend::IPortableTensor::data_scale(), onert::interp::ROTensor::data_scale(), onert::interp::Tensor::data_scale(), onert::ir::operator==(), quantization(), and TypeInfo().
scales()
const std::vector< float > & onert::ir::TypeInfo::scales () const inline
Definition at line 54 of file TypeInfo.h.
{ return _quant.scales; }
References onert::ir::Quantization::scales.
Referenced by onert::backend::IPortableTensor::data_scales(), onert::interp::ROTensor::data_scales(), onert::interp::Tensor::data_scales(), and quantization().
sparsity() [1/2]
const ir::Sparsity * onert::ir::TypeInfo::sparsity () const inline
Definition at line 61 of file TypeInfo.h.
{ return _sparsity.get(); }
Referenced by onert::base_loader::BaseLoader< LoaderDomain >::loadSparsity(), and onert::backend::basic::Tensor::sparsity().
sparsity() [2/2]
void onert::ir::TypeInfo::sparsity (std::shared_ptr< ir::Sparsity > sparsity) inline
Definition at line 74 of file TypeInfo.h.
{ _sparsity = sparsity; }
References sparsity().
Referenced by sparsity().
type() [1/2]
DataType onert::ir::TypeInfo::type () const inline
Definition at line 52 of file TypeInfo.h.
{ return _type; }
Referenced by onert::backend::acl_common::asPixelValue(), onert::backend::acl_common::asSet(), onert::backend::acl_common::asTensorInfo(), OptionBuilder.OptionBuilder::build(), onert::backend::basic::Tensor::data_type(), onert::backend::builtin::UserTensor::data_type(), onert::interp::ROTensor::data_type(), onert::interp::Tensor::data_type(), onert::ir::Operand::operandSize(), onert::ir::operator==(), onert::ir::OperandInfo::total_size(), and onert::ir::OperandInfo::type().
type() [2/2]
void onert::ir::TypeInfo::type (const DataType type) inline
Definition at line 77 of file TypeInfo.h.
{ _type = type; }
References type().
Referenced by OptionBuilder.OptionBuilder::build(), and type().
zero_point()
int32_t onert::ir::TypeInfo::zero_point () const inline
Definition at line 55 of file TypeInfo.h.
  {
    assert(_quant.zero_points.size() == 1);
    return _quant.zero_points[0];
  }
References onert::ir::Quantization::zero_points.
Referenced by onert::backend::acl_common::asTensorInfo(), onert::backend::IPortableTensor::data_zero_point(), onert::interp::ROTensor::data_zero_point(), onert::interp::Tensor::data_zero_point(), onert::ir::operator==(), quantization(), and TypeInfo().
zero_points()
const std::vector< int32_t > & onert::ir::TypeInfo::zero_points () const inline
Definition at line 60 of file TypeInfo.h.
{ return _quant.zero_points; }
References onert::ir::Quantization::zero_points.
Referenced by onert::backend::IPortableTensor::data_zero_points(), onert::interp::ROTensor::data_zero_points(), onert::interp::Tensor::data_zero_points(), and quantization().
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/TypeInfo.h