ONE - On-device Neural Engine: onert::interp::ExecEnv Class Reference
onert::interp::ExecEnv Class Reference
Class to gather interpreter execution environment Each interpreter instance own execution environment.
#include <ExecEnv.h>
Public Member Functions
ExecEnv (void)=delete
Construct a new Exec Env object (deleted)
ExecEnv (const ir::Graph &graph)
Construct a new ExecEnv object.
const ir::Graph & graph (void) const
Return graph to execute.
void assignTensor (const ir::OperandIndex index, std::shared_ptr< ITensor > tensor)
Assign tensor to environment which have allocated or assigned buffer.
const ITensor * tensorAt (const ir::OperandIndex index, bool can_optional=false) const
Return tensor pointer in environment.
bool contains (const ir::OperandIndex index) const
Check environment contains tensor.
void allocateIfNeeded (const ir::OperandIndex index, const ir::OperandInfo &info)
Allocate tensor using operand info.
void allocateAndShareIfNeeded (const ir::OperandIndex index, const ir::OperandInfo &info, const ir::OperandIndex index_to_share)
Allocate read-only tensor and share data with other tensor.
void freeIfAllocated (const ir::OperandIndex index)
Free buffer if allocated by allocateIfNeed.
void assignExternalBuffer (const ir::OperandIndex index, std::shared_ptr< ExternalBuffer > buffer)
Assign ExternalBuffer into external buffer map.
Detailed Description
Class to gather interpreter execution environment Each interpreter instance own execution environment.
Definition at line 38 of file ExecEnv.h.
Constructor & Destructor Documentation
ExecEnv() [1/2]
onert::interp::ExecEnv::ExecEnv (void) delete
Construct a new Exec Env object (deleted)
ExecEnv() [2/2]
onert::interp::ExecEnv::ExecEnv (const ir::Graph & graph) inline explicit
Construct a new ExecEnv object.
Parameters
[in] graph Graph to execute by interpreter
Definition at line 49 of file ExecEnv.h.
                                         : _graph(graph)
  {
    // DO NOTHING
  }
Member Function Documentation
allocateAndShareIfNeeded()
void onert::interp::ExecEnv::allocateAndShareIfNeeded (const ir::OperandIndex index, const ir::OperandInfo & info, const ir::OperandIndex index_to_share) inline
Allocate read-only tensor and share data with other tensor.
Parameters
[in] index Tensor index
[in] info Operand info
[in] index_to_share Tensor index that have data to share
Definition at line 140 of file ExecEnv.h.
  {
    if (!contains(index_to_share))
    {
      throw std::runtime_error{"Cannot find tensor to share data"};
    }
    // already allocated
    if (contains(index))
    {
      return;
    }
    if (isExtBuffer(index))
    {
      auto tensor = std::make_shared<Tensor>(info);
      tensor->setBuffer(_external_buffers.at(index));
      assignTensor(index, tensor);
    }
    else
    {
      auto tensor = std::make_shared<ROTensor>(info);
      tensor->setData(tensorAt(index_to_share)->shareData());
      assignTensor(index, tensor);
      _buffers.insert(index);
    }
  }
References assignTensor(), contains(), info, and tensorAt().
allocateIfNeeded()
void onert::interp::ExecEnv::allocateIfNeeded (const ir::OperandIndex index, const ir::OperandInfo & info) inline
Allocate tensor using operand info.
Parameters
[in] index Tensor index
[in] info Operand info
Note
If already allocated, just return @TODO More smart allocation policy
Definition at line 111 of file ExecEnv.h.
  {
    // already allocated, or constant
    if (contains(index))
    {
      return;
    }
    // Buffer from external (ex. model output)
    auto tensor = std::make_shared<Tensor>(info);
    if (isExtBuffer(index))
    {
      tensor->setBuffer(_external_buffers.at(index));
      assignTensor(index, tensor);
      return;
    }
    tensor->setBuffer(std::make_shared<InternalBuffer>(tensor->total_size()));
    assignTensor(index, tensor);
    _buffers.insert(index);
  }
References assignTensor(), contains(), and info.
Referenced by onert::interp::concat::prepareConcat(), onert::interp::conv2d::prepareConv2D(), onert::interp::fc::prepareFC(), onert::interp::instancenorm::prepareInstanceNorm(), and onert::interp::pool2d::preparePool2D().
assignExternalBuffer()
void onert::interp::ExecEnv::assignExternalBuffer (const ir::OperandIndex index, std::shared_ptr< ExternalBuffer > buffer) inline
Assign ExternalBuffer into external buffer map.
Parameters
[in] index Tensor index
[in] buffer External buffer
Definition at line 187 of file ExecEnv.h.
  {
    _external_buffers.emplace(index, buffer);
  }
assignTensor()
void onert::interp::ExecEnv::assignTensor (const ir::OperandIndex index, std::shared_ptr< ITensor > tensor) inline
Assign tensor to environment which have allocated or assigned buffer.
Parameters
[in] index Tensor index
[in] tensor Tensor
Definition at line 65 of file ExecEnv.h.
  {
    assert(tensor->bufferRO() != nullptr);
    _tensors.emplace(index, tensor);
  }
Referenced by allocateAndShareIfNeeded(), and allocateIfNeeded().
contains()
bool onert::interp::ExecEnv::contains (const ir::OperandIndex index) const inline
Check environment contains tensor.
Parameters
[in] index Tensor index
Returns
true if environment contain tensor, otherwise false
Definition at line 99 of file ExecEnv.h.
  {
    return (_tensors.find(index) != _tensors.end());
  }
Referenced by allocateAndShareIfNeeded(), and allocateIfNeeded().
freeIfAllocated()
void onert::interp::ExecEnv::freeIfAllocated (const ir::OperandIndex index) inline
Free buffer if allocated by allocateIfNeed.
Parameters
[in] index Tensor index
Note
If allocated by outside, just return
Definition at line 174 of file ExecEnv.h.
  {
    if (_buffers.find(index) != _buffers.end())
    {
      _tensors.at(index)->releaseData();
    }
  }
graph()
const ir::Graph & onert::interp::ExecEnv::graph (void) const inline
Return graph to execute.
Returns
Graph
Definition at line 59 of file ExecEnv.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::interp::OperationExecutor::execute(), onert::interp::conv2d::prepareConv2D(), onert::interp::pool2d::preparePool2D(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
tensorAt()
const ITensor * onert::interp::ExecEnv::tensorAt (const ir::OperandIndex index, bool can_optional = false) const inline
Return tensor pointer in environment.
Parameters
[in] index Tensor index can_optional True if tensor can be optional input, otherwise false
Returns
Tensor pointer
Definition at line 77 of file ExecEnv.h.
  {
    if (_tensors.find(index) == _tensors.end())
    {
      // It may optional input,
      // otherwise input is not set by runtime user
      if (can_optional)
      {
        return nullptr;
      }
      throw std::runtime_error{"ExecEnv: Input is not set"};
    }
    return _tensors.at(index).get();
  }
Referenced by allocateAndShareIfNeeded(), onert::interp::concat::invokeConcat(), onert::interp::conv2d::invokeConv2D(), onert::interp::fc::invokeFC(), onert::interp::instancenorm::invokeInstanceNorm(), onert::interp::pool2d::invokePool2DOps(), onert::interp::concat::prepareConcat(), onert::interp::conv2d::prepareConv2D(), onert::interp::fc::prepareFC(), onert::interp::instancenorm::prepareInstanceNorm(), and onert::interp::pool2d::preparePool2D().
The documentation for this class was generated from the following file:
runtime/onert/core/src/interp/ExecEnv.h