ONE - On-device Neural Engine: onert_micro::core::OMRuntimeModule Class Reference
onert_micro::core::OMRuntimeModule Class Reference
#include <OMRuntimeModule.h>
Public Member Functions
OMRuntimeModule ()=default
OMRuntimeModule (const OMRuntimeModule &)=delete
OMRuntimeModule (OMRuntimeModule &&)=delete
OMRuntimeModule & operator= (const OMRuntimeModule &)=delete
OMRuntimeModule && operator= (const OMRuntimeModule &&)=delete
~OMRuntimeModule ()=default
OMStatus importModel (const char *model_ptr, const OMConfig &config)
OMStatus run (const OMConfig &config)
OMStatus reset ()
uint32_t getNumberOfInputs ()
uint32_t getNumberOfOutputs ()
uint32_t getInputSizeAt (uint32_t position)
uint32_t getOutputSizeAt (uint32_t position)
void * getInputDataAt (uint32_t position)
void * getOutputDataAt (uint32_t position)
OMStatus getRuntimeGraphAt (uint32_t pos, OMRuntimeGraph **runtime_graph)
OMStatus allocateInputs ()
Protected Attributes
std::vector< OMRuntimeGraph > _graphs
Detailed Description
Definition at line 32 of file OMRuntimeModule.h.
Constructor & Destructor Documentation
OMRuntimeModule() [1/3]
onert_micro::core::OMRuntimeModule::OMRuntimeModule () default
OMRuntimeModule() [2/3]
onert_micro::core::OMRuntimeModule::OMRuntimeModule (const OMRuntimeModule &) delete
OMRuntimeModule() [3/3]
onert_micro::core::OMRuntimeModule::OMRuntimeModule (OMRuntimeModule &&) delete
~OMRuntimeModule()
onert_micro::core::OMRuntimeModule::~OMRuntimeModule () default
Member Function Documentation
allocateInputs()
OMStatus OMRuntimeModule::allocateInputs ()
Definition at line 143 of file OMRuntimeModule.cpp.
{
  assert(_graphs.size() > 0);
  if (_graphs.size() == 0)
    return ModelNotImport;
  return _graphs.at(0).allocateGraphInputs();
}
References _graphs, and onert_micro::ModelNotImport.
Referenced by onert_micro::OMInterpreter::allocateInputs(), and onert_micro::OMTrainingInterpreter::allocateInputs().
getInputDataAt()
void * OMRuntimeModule::getInputDataAt (uint32_t position)
Definition at line 41 of file OMRuntimeModule.cpp.
{
  return _graphs.at(0).getInputDataAt(position);
}
References _graphs.
Referenced by onert_micro::OMInterpreter::getInputDataAt(), and onert_micro::OMTrainingInterpreter::getInputDataAt().
getInputSizeAt()
uint32_t OMRuntimeModule::getInputSizeAt (uint32_t position)
Definition at line 31 of file OMRuntimeModule.cpp.
{
  return _graphs.at(0).getInputSizeAt(position);
}
References _graphs.
Referenced by onert_micro::OMInterpreter::getInputSizeAt(), and onert_micro::OMTrainingInterpreter::getInputSizeAt().
getNumberOfInputs()
uint32_t OMRuntimeModule::getNumberOfInputs ()
Definition at line 27 of file OMRuntimeModule.cpp.
{ return _graphs.at(0).getNumberOfInputs(); }
References _graphs.
Referenced by onert_micro::OMInterpreter::getNumberOfInputs().
getNumberOfOutputs()
uint32_t OMRuntimeModule::getNumberOfOutputs ()
Definition at line 29 of file OMRuntimeModule.cpp.
{ return _graphs.at(0).getNumberOfOutputs(); }
References _graphs.
Referenced by onert_micro::OMInterpreter::getNumberOfOutputs().
getOutputDataAt()
void * OMRuntimeModule::getOutputDataAt (uint32_t position)
Definition at line 46 of file OMRuntimeModule.cpp.
{
  return _graphs.at(0).getOutputDataAt(position);
}
References _graphs.
Referenced by onert_micro::OMInterpreter::getOutputDataAt(), and onert_micro::OMTrainingInterpreter::getOutputDataAt().
getOutputSizeAt()
uint32_t OMRuntimeModule::getOutputSizeAt (uint32_t position)
Definition at line 36 of file OMRuntimeModule.cpp.
{
  return _graphs.at(0).getOutputSizeAt(position);
}
References _graphs.
Referenced by onert_micro::OMInterpreter::getOutputSizeAt(), and onert_micro::OMTrainingInterpreter::getOutputSizeAt().
getRuntimeGraphAt()
OMStatus OMRuntimeModule::getRuntimeGraphAt (uint32_t pos, OMRuntimeGraph ** runtime_graph)
Definition at line 189 of file OMRuntimeModule.cpp.
{
  if (pos >= _graphs.size())
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  *runtime_graph = &_graphs.at(pos);
  return Ok;
}
References _graphs, onert_micro::Ok, OM_LOG_AND_RETURN, and onert_micro::UnknownError.
Referenced by onert_micro::import::configure_kernel_CircleWhile(), and onert_micro::execute::execute_kernel_CircleWhile().
importModel()
OMStatus OMRuntimeModule::importModel (const char * model_ptr, const OMConfig & config)
Definition at line 51 of file OMRuntimeModule.cpp.
{
  assert(model_ptr != nullptr && "Model ptr shouldn't be nullptr");
  if (model_ptr == nullptr)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  // 1 - parse reader
  // 2 - load default graph
  // 3 - optimize it until can
  // 4 - AllocDeallocPlan creation
  // 5 - KernelConfigure
  // 6 - Allocate inputs
  OMStatus status;
  // First - parse reader
  uint32_t num_subgraph = 0;
  {
    reader::OMCircleReader reader;
    status = reader.parse(model_ptr);
    if (status != Ok)
      return status;
    num_subgraph = reader.num_subgraph();
  }
  assert(num_subgraph >= 1);
  if (num_subgraph == 0)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  _graphs.resize(num_subgraph);
  for (uint32_t i = 0; i < num_subgraph; ++i)
  {
    // Second - load default graph
    OMRuntimeGraph &graph = _graphs.at(i);
    OMRuntimeContext &runtime_context = graph.getRuntimeContext();
    OMRuntimeStorage &runtime_storage = graph.getRuntimeStorage();
    memory::OMRuntimeAllocator &runtime_allocator = graph.getRuntimeAllocator();
    runtime_context.setModel(model_ptr, i);
    // Parse and validate WOF file if it is exist
    // WARNING: setWofFile method of RuntimeContext should follow after setModel.
    if (config.wof_ptr != nullptr)
      runtime_context.setWofFile(config.wof_ptr);
    // Parse and validate Train Config File if it is exists
    // WARNING: setTrainConfigFile method of RuntimeContext should follow after setModel.
    if (config.train_mode and config.training_context.training_config_info_data != nullptr)
      runtime_context.setTrainConfigFile(config.training_context.training_config_info_data);
    // Third - optimize it until can
    status = optimize::OMOptimizer::optimize(runtime_storage, runtime_context, config);
    if (status != Ok)
      return status;
    // 4 - AllocDeallocPlan creation
    if (not config.train_mode)
    {
      // Non trainable mode
      status = import::OMExecutionPlanCreator::createExecutionPlan(runtime_storage, runtime_context,
                                                                   runtime_allocator, config);
    }
    else
    {
      // Trainable mode
      status = import::OMExecutionPlanCreator::createForwardExecutionPlan(
        runtime_storage, runtime_context, runtime_allocator, config);
    }
    if (status != Ok)
      return status;
  }
  for (uint32_t i = 0; i < num_subgraph; ++i)
  {
    // Second - load default graph
    OMRuntimeGraph &graph = _graphs.at(i);
    OMRuntimeContext &runtime_context = graph.getRuntimeContext();
    OMRuntimeStorage &runtime_storage = graph.getRuntimeStorage();
    memory::OMRuntimeAllocator &runtime_allocator = graph.getRuntimeAllocator();
    // 5 - KernelConfigure
    import::OMConfigureArgs configure_args = {runtime_storage, runtime_context, 0, config, *this};
    status = import::OMKernelConfiguration::configureKernels(configure_args);
    if (status != Ok)
      return status;
  }
  // Done!
  return Ok;
}
References _graphs, onert_micro::import::OMKernelConfiguration::configureKernels(), onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), onert_micro::core::reader::OMCircleReader::num_subgraph(), onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::optimize::OMOptimizer::optimize(), onert_micro::core::reader::OMCircleReader::parse(), onert_micro::core::OMRuntimeContext::setModel(), onert_micro::core::OMRuntimeContext::setTrainConfigFile(), onert_micro::core::OMRuntimeContext::setWofFile(), and onert_micro::UnknownError.
Referenced by onert_micro::OMInterpreter::importModel(), and onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
operator=() [1/2]
OMRuntimeModule && onert_micro::core::OMRuntimeModule::operator= (const OMRuntimeModule &&) delete
operator=() [2/2]
OMRuntimeModule & onert_micro::core::OMRuntimeModule::operator= (const OMRuntimeModule &) delete
reset()
OMStatus OMRuntimeModule::reset ()
Definition at line 174 of file OMRuntimeModule.cpp.
{
  OMStatus status = Ok;
  if (_graphs.empty())
    return ModelNotImport;
  for (auto &graph : _graphs)
  {
    graph.reset();
  }
  return status;
}
References _graphs, onert_micro::ModelNotImport, and onert_micro::Ok.
Referenced by onert_micro::OMInterpreter::reset().
run()
OMStatus OMRuntimeModule::run (const OMConfig & config)
Definition at line 151 of file OMRuntimeModule.cpp.
{
  OMStatus status = Ok;
  if (_graphs.empty())
    return ModelNotImport;
  core::OMRuntimeGraph &main_graph = _graphs.at(0);
  execute::OMExecuteArgs execute_args = {main_graph.getRuntimeStorage(),
                                         main_graph.getRuntimeContext(),
                                         0,
                                         *this,
                                         config.training_context.num_of_train_layers,
                                         config.train_mode};
  status = execute::OMKernelExecute::runForward(execute_args, main_graph.getRuntimeAllocator());
  if (status != Ok)
    return status;
  return status;
}
References _graphs, onert_micro::core::OMRuntimeGraph::getRuntimeAllocator(), onert_micro::core::OMRuntimeGraph::getRuntimeContext(), onert_micro::core::OMRuntimeGraph::getRuntimeStorage(), onert_micro::ModelNotImport, onert_micro::Ok, and onert_micro::execute::OMKernelExecute::runForward().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), onert_micro::OMInterpreter::run(), onert_micro::OMTrainingInterpreter::run(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
Field Documentation
_graphs
std::vector<OMRuntimeGraph> onert_micro::core::OMRuntimeModule::_graphs protected
Definition at line 35 of file OMRuntimeModule.h.
Referenced by allocateInputs(), onert_micro::core::OMTrainingRuntimeModule::createCheckpointFile(), onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), getInputDataAt(), getInputSizeAt(), getNumberOfInputs(), getNumberOfOutputs(), getOutputDataAt(), getOutputSizeAt(), getRuntimeGraphAt(), importModel(), onert_micro::core::OMTrainingRuntimeModule::importTrainModel(), onert_micro::core::OMTrainingRuntimeModule::loadCheckpointData(), reset(), onert_micro::core::OMTrainingRuntimeModule::reset(), run(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/OMRuntimeModule.h
onert-micro/onert-micro/src/core/OMRuntimeModule.cpp