ONE - On-device Neural Engine: ann::Operand Class Reference
ann::Operand Class Reference
#include <Operand.h>
Public Member Functions
virtual ~Operand ()=default
DType dtype (void) const
void dtype (const DType &dtype)
const Weight * weight (void) const
void weight (const Weight *weight)
Detailed Description
Definition at line 28 of file Operand.h.
Constructor & Destructor Documentation
~Operand()
virtual ann::Operand::~Operand () virtual default
Member Function Documentation
dtype() [1/2]
void ann::Operand::dtype (const DType & dtype) inline
Definition at line 35 of file Operand.h.
{ _dtype = dtype; }
References dtype().
Referenced by dtype().
dtype() [2/2]
DType ann::Operand::dtype (void) const inline
Definition at line 34 of file Operand.h.
{ return _dtype; }
weight() [1/2]
void ann::Operand::weight (const Weight * weight) inline
Definition at line 38 of file Operand.h.
{ _weight = weight; }
References weight().
Referenced by weight().
weight() [2/2]
const Weight * ann::Operand::weight (void) const inline
Definition at line 37 of file Operand.h.
{ return _weight; }
The documentation for this class was generated from the following file:
compiler/enco/core/src/ANN/IR/Operand.h