ONE - On-device Neural Engine: caffeimport::ScaleBuilder Class Reference
caffeimport::ScaleBuilder Class Reference final
#include <Scale.h>
Public Member Functions
void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const override
Public Member Functions inherited from caffeimport::GraphBuilder
virtual void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 27 of file Scale.h.
Member Function Documentation
build()
void caffeimport::ScaleBuilder::build (const ::caffe::LayerParameter & layer, GraphBuilderContext * context) const override virtual
Implements caffeimport::GraphBuilder.
Definition at line 32 of file Scale.cpp.
{
  coco::Module *module = context->module();
  coco::Data *data = context->data();
  coco::Block *blk = context->block();
  std::map<std::string, tensor::Shape> &shape_ctx = context->shape_ctx();
  std::map<std::string, coco::Bag *> &bag_ctx = context->bag_ctx();
  WeightContext &weight_ctx = context->weight_ctx();
  // TODO Support Scale layer with 2 bottoms
  assert(layer.bottom().size() == 1);
  assert(layer.top().size() == 1);
  assert(layer.has_scale_param());
  const auto &param = layer.scale_param();
  assert(param.axis() == 1);
  assert(!param.has_num_axes());
  assert(weight_ctx.blob_count(layer.name()) >= 1);
  // NOTE The shape of "Scale" output is same as that of its input
  // NOTE The current implementation assumes that input/output is of feature type
  // TODO Support generic tensor arguments
  auto shape = shape_ctx.at(layer.bottom(0));
  coco::Bag *last_bag = bag_ctx.at(layer.bottom(0));
  // Create channel-wise multiplication
  {
    auto in_bag = last_bag;
    auto in_obj = module->entity()->object()->create<coco::FeatureObject>();
    in_obj->bag(in_bag);
    in_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(shape)));
    auto factor_bag = module->entity()->bag()->create(num_elements(shape));
    auto factor_obj = module->entity()->object()->create<coco::FeatureObject>();
    factor_obj->bag(factor_bag);
    factor_obj->layout(coco::FeatureLayouts::BC::create(as_feature_shape(shape)));
    auto out_bag = module->entity()->bag()->create(num_elements(shape));
    auto out_obj = module->entity()->object()->create<coco::FeatureObject>();
    out_obj->bag(out_bag);
    out_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(shape)));
    auto mul_op = op_builder(module).load(factor_obj).load(in_obj).mul().pop();
    auto mul_ins = instr_builder(module).eval(out_obj, mul_op);
    blk->instr()->append(mul_ins);
    // Fill "factor" data
    {
      data->f32()->allocate(factor_bag);
      auto span = data->f32()->weight(factor_bag);
      auto blob = weight_ctx.blob_get(layer.name(), 0);
      for (uint32_t ch = 0; ch < factor_obj->shape().depth(); ++ch)
      {
        span[ch] = blob->data(ch);
      }
    }
    // Update "last_bag"
    last_bag = out_bag;
  }
  assert(last_bag != nullptr);
  // Create bias addition (as channel-wise addition)
  if (param.bias_term())
  {
    assert(weight_ctx.blob_count(layer.name()) >= 2);
    auto in_bag = last_bag; /* Use the output of the last computation as an input */
    auto in_obj = module->entity()->object()->create<coco::FeatureObject>();
    in_obj->bag(in_bag);
    in_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(shape)));
    auto bias_bag = module->entity()->bag()->create(num_elements(shape));
    auto bias_obj = module->entity()->object()->create<coco::FeatureObject>();
    bias_obj->bag(bias_bag);
    bias_obj->layout(coco::FeatureLayouts::BC::create(as_feature_shape(shape)));
    auto out_bag = module->entity()->bag()->create(num_elements(shape));
    auto out_obj = module->entity()->object()->create<coco::FeatureObject>();
    out_obj->bag(out_bag);
    out_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(shape)));
    auto add_op = op_builder(module).load(bias_obj).load(in_obj).add().pop();
    auto add_ins = instr_builder(module).eval(out_obj, add_op);
    blk->instr()->append(add_ins);
    // Fill bias data
    {
      data->f32()->allocate(bias_bag);
      auto bias_span = data->f32()->weight(bias_bag);
      auto bias_blob = weight_ctx.blob_get(layer.name(), 1);
      for (uint32_t ch = 0; ch < bias_obj->shape().depth(); ++ch)
      {
        bias_span[ch] = bias_blob->data(ch);
      }
    }
    // Update "last_bag"
    last_bag = out_bag;
  }
  // Update bag and shape context
  {
    const auto &out_name = layer.top(0);
    const auto &out_bag = last_bag;
    const auto &out_shape = shape;
    bag_ctx[out_name] = out_bag;
    shape_ctx[out_name] = out_shape;
  }
}
References OpBuilder::add(), coco::DLinkedList< Child, Parent >::Head::append(), morph::caffe::as_feature_shape(), coco::Object::bag(), coco::EntityManager::bag(), caffeimport::GraphBuilderContext::bag_ctx(), caffeimport::WeightContext::blob_count(), caffeimport::WeightContext::blob_get(), caffeimport::GraphBuilderContext::block(), coco::FeatureLayouts::BCHW::create(), coco::FeatureLayouts::BC::create(), coco::BagManager::create(), coco::ObjectManager::create(), caffeimport::GraphBuilderContext::data(), coco::Module::entity(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), OpBuilder::load(), caffeimport::GraphBuilderContext::module(), OpBuilder::mul(), coco::EntityManager::object(), op_builder(), OpBuilder::pop(), caffeimport::GraphBuilderContext::shape_ctx(), and caffeimport::GraphBuilderContext::weight_ctx().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/Layer/Scale.h
compiler/enco/frontend/caffe/src/Layer/Scale.cpp