ONE - On-device Neural Engine: mir_interpreter::AvgPool2DImpl< T > Class Template Reference
mir_interpreter::AvgPool2DImpl< T > Class Template Reference
Static Public Member Functions
static void run (const mir::ops::AvgPool2DOp &op, const mir::TensorVariant &input_var, mir::TensorVariant &output)
Detailed Description
template<typename T>
class mir_interpreter::AvgPool2DImpl< T >
Definition at line 29 of file AvgPool2D.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::AvgPool2DImpl< T >::run (const mir::ops::AvgPool2DOp & op, const mir::TensorVariant & input_var, mir::TensorVariant & output) static
Definition at line 37 of file AvgPool2D.cpp.
{
  const auto &input_shape = op.getInputShape(0);
  const auto &output_shape = op.getOutputShape(0);
  const auto &window_size = op.getWindowSize();
  const auto &strides = op.getStrides();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  (void)padding_after;
  constexpr int num_spatial_dims = 2;
  assert(input_var.getShape().rank() == 4);
  assert(window_size.size() == num_spatial_dims);
  assert(strides.size() == num_spatial_dims);
  assert(padding_before.size() == num_spatial_dims);
  assert(padding_after.size() == num_spatial_dims);
  Tensor<T> res_accessor(output);
  Tensor<T> input(input_var);
  ShapeRange in_range(input_shape);
  Index in_index(input_shape.rank());
  for (const auto &out_index : ShapeRange(output_shape))
  {
    T result = 0;
    size_t num_elements = 0;
    // Assuming NHWC format.
    in_index.at(0) = out_index.at(0);
    in_index.at(3) = out_index.at(3);
    for (const auto &window_index : ShapeRange(Shape(window_size)))
    {
      // Assuming NHWC format.
      for (int i = 0; i < num_spatial_dims; ++i)
        in_index.at(1 + i) =
          out_index.at(1 + i) * strides[i] + window_index.at(i) - padding_before[i];
      if (in_range.contains(in_index))
      {
        num_elements++;
        result += input.at(in_index);
      }
      else if (op.getIncludePad())
      {
        num_elements++;
      }
    }
    result /= num_elements;
    res_accessor.at(out_index) = result;
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::ShapeRange::contains(), mir::ops::AvgPool2DOp::getIncludePad(), mir::Operation::getInputShape(), mir::Operation::getOutputShape(), mir::ops::AvgPool2DOp::getPaddingAfter(), mir::ops::AvgPool2DOp::getPaddingBefore(), mir::TensorVariant::getShape(), mir::ops::AvgPool2DOp::getStrides(), mir::ops::AvgPool2DOp::getWindowSize(), and mir::Shape::rank().
The documentation for this class was generated from the following file:
compiler/mir-interpreter/src/ops/AvgPool2D.cpp