ONE - On-device Neural Engine: hermes::SourceSetting Class Reference
hermes::SourceSetting Class Reference final
#include <SourceSetting.h>
Public Member Functions
SourceSetting ()
void reject_all (void)
void accept_all (void)
Filter filter (const SeverityCategory &cat)
Limit limit (const SeverityCategory &cat) const
Detailed Description
Definition at line 58 of file SourceSetting.h.
Constructor & Destructor Documentation
SourceSetting()
hermes::SourceSetting::SourceSetting () inline
Definition at line 61 of file SourceSetting.h.
  {
    // Reject all the messages by default
    reject_all();
  }
References reject_all().
Member Function Documentation
accept_all()
void hermes::SourceSetting::accept_all (void) inline
Definition at line 77 of file SourceSetting.h.
  {
    filter(FATAL).accept_all();
    filter(ERROR).accept_all();
    filter(WARN).accept_all();
    filter(INFO).accept_all();
    filter(VERBOSE).accept_all();
  }
References hermes::Filter::accept_all(), hermes::ERROR, hermes::FATAL, filter(), hermes::INFO, hermes::VERBOSE, and hermes::WARN.
Referenced by circlechef::LoggerConfig::configure(), exo::LoggerConfig::configure(), moco::LoggerConfig::configure(), tflchef::LoggerConfig::configure(), and hermes::EnvConfig< EnvFormat::BooleanNumber >::configure().
filter()
Filter hermes::SourceSetting::filter (const SeverityCategory & cat) inline
Definition at line 86 of file SourceSetting.h.
  {
    return _ulimits.data() + static_cast<uint32_t>(cat);
  }
Referenced by accept_all(), luci::LoggerConfig::configure(), and reject_all().
limit()
Limit hermes::SourceSetting::limit (const SeverityCategory & cat) const inline
Definition at line 91 of file SourceSetting.h.
  {
    return _ulimits.data() + static_cast<uint32_t>(cat);
  }
Referenced by hermes::Source::check().
reject_all()
void hermes::SourceSetting::reject_all (void) inline
Definition at line 68 of file SourceSetting.h.
  {
    filter(FATAL).reject_all();
    filter(ERROR).reject_all();
    filter(WARN).reject_all();
    filter(INFO).reject_all();
    filter(VERBOSE).reject_all();
  }
References hermes::ERROR, hermes::FATAL, filter(), hermes::INFO, hermes::Filter::reject_all(), hermes::VERBOSE, and hermes::WARN.
Referenced by circlechef::LoggerConfig::configure(), exo::LoggerConfig::configure(), luci::LoggerConfig::configure(), moco::LoggerConfig::configure(), tflchef::LoggerConfig::configure(), hermes::EnvConfig< EnvFormat::BooleanNumber >::configure(), and SourceSetting().
The documentation for this class was generated from the following file:
compiler/hermes/include/hermes/core/SourceSetting.h