ONE - On-device Neural Engine: onert::ir::operation::LSTM Class Reference
onert::ir::operation::LSTM Class Reference
#include <LSTM.h>
Data Structures
struct Param
Public Types
enum Input {
INPUT = 0 , INPUT_TO_INPUT_WEIGHTS = 1 , INPUT_TO_FORGET_WEIGHTS = 2 , INPUT_TO_CELL_WEIGHTS = 3 ,
INPUT_TO_OUTPUT_WEIGHTS = 4 , RECURRENT_TO_INPUT_WEIGHTS = 5 , RECURRENT_TO_FORGET_WEIGHTS = 6 , RECURRENT_TO_CELL_WEIGHTS = 7 ,
RECURRENT_TO_OUTPUT_WEIGHTS = 8 , CELL_TO_INPUT_WEIGHTS = 9 , CELL_TO_FORGET_WEIGHTS = 10 , CELL_TO_OUTPUT_WEIGHTS = 11 ,
INPUT_GATE_BIAS = 12 , FORGET_GATE_BIAS = 13 , CELL_BIAS = 14 , OUTPUT_GATE_BIAS = 15 ,
PROJECTION_WEIGHTS = 16 , PROJECTION_BIAS = 17 , OUTPUT_STATE_IN = 18 , CELL_STATE_IN = 19 ,
INPUT_LAYER_NORMALIZATION_WEIGHTS = 20 , FORGET_LAYER_NORMALIZATION_WEIGHTS = 21 , CELL_LAYER_NORMALIZATION_WEIGHTS = 22 , OUTPUT_LAYER_NORMALIZATION_WEIGHTS = 23
}
enum Output { SCRATCH_BUFFER = 0 , OUTPUT_STATE_OUT = 1 , CELL_STATE_OUT = 2 , OUTPUT = 3 }
Public Member Functions
LSTM (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, const Param &param)
void accept (OperationVisitor &v) const override
std::string name () const override
OpCode opcode () const final
const Param & param () const
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
void replaceInputs (const OperandIndex &from, const OperandIndex &to)
void replaceOutputs (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const
const OperandIndexSequence & getOutputs () const
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Detailed Description
Definition at line 30 of file LSTM.h.
Member Enumeration Documentation
Input
enum onert::ir::operation::LSTM::Input
Enumerator
INPUT
INPUT_TO_INPUT_WEIGHTS
INPUT_TO_FORGET_WEIGHTS
INPUT_TO_CELL_WEIGHTS
INPUT_TO_OUTPUT_WEIGHTS
RECURRENT_TO_INPUT_WEIGHTS
RECURRENT_TO_FORGET_WEIGHTS
RECURRENT_TO_CELL_WEIGHTS
RECURRENT_TO_OUTPUT_WEIGHTS
CELL_TO_INPUT_WEIGHTS
CELL_TO_FORGET_WEIGHTS
CELL_TO_OUTPUT_WEIGHTS
INPUT_GATE_BIAS
FORGET_GATE_BIAS
CELL_BIAS
OUTPUT_GATE_BIAS
PROJECTION_WEIGHTS
PROJECTION_BIAS
OUTPUT_STATE_IN
CELL_STATE_IN
INPUT_LAYER_NORMALIZATION_WEIGHTS
FORGET_LAYER_NORMALIZATION_WEIGHTS
CELL_LAYER_NORMALIZATION_WEIGHTS
OUTPUT_LAYER_NORMALIZATION_WEIGHTS
Definition at line 33 of file LSTM.h.
  {
    INPUT = 0,
    INPUT_TO_INPUT_WEIGHTS = 1,
    INPUT_TO_FORGET_WEIGHTS = 2,
    INPUT_TO_CELL_WEIGHTS = 3,
    INPUT_TO_OUTPUT_WEIGHTS = 4,
    RECURRENT_TO_INPUT_WEIGHTS = 5,
    RECURRENT_TO_FORGET_WEIGHTS = 6,
    RECURRENT_TO_CELL_WEIGHTS = 7,
    RECURRENT_TO_OUTPUT_WEIGHTS = 8,
    CELL_TO_INPUT_WEIGHTS = 9,
    CELL_TO_FORGET_WEIGHTS = 10,
    CELL_TO_OUTPUT_WEIGHTS = 11,
    INPUT_GATE_BIAS = 12,
    FORGET_GATE_BIAS = 13,
    CELL_BIAS = 14,
    OUTPUT_GATE_BIAS = 15,
    PROJECTION_WEIGHTS = 16,
    PROJECTION_BIAS = 17,
    OUTPUT_STATE_IN = 18,
    CELL_STATE_IN = 19,
    INPUT_LAYER_NORMALIZATION_WEIGHTS = 20,
    FORGET_LAYER_NORMALIZATION_WEIGHTS = 21,
    CELL_LAYER_NORMALIZATION_WEIGHTS = 22,
    OUTPUT_LAYER_NORMALIZATION_WEIGHTS = 23,
  };
Output
enum onert::ir::operation::LSTM::Output
Enumerator
SCRATCH_BUFFER
OUTPUT_STATE_OUT
CELL_STATE_OUT
OUTPUT
Definition at line 61 of file LSTM.h.
  {
    SCRATCH_BUFFER = 0,
    OUTPUT_STATE_OUT = 1,
    CELL_STATE_OUT = 2,
    OUTPUT = 3
  };
Constructor & Destructor Documentation
LSTM()
onert::ir::operation::LSTM::LSTM (const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, const Param & param)
Definition at line 29 of file LSTM.cc.
  : Operation{OperandConstraint::createInRange(20u, 24u), inputs, outputs}, _param{param}
{
}
Member Function Documentation
accept()
void onert::ir::operation::LSTM::accept (OperationVisitor & v) const override virtual
Implements onert::ir::Operation.
Definition at line 27 of file LSTM.cc.
{ v.visit(*this); }
name()
std::string onert::ir::operation::LSTM::name () const override virtual
Reimplemented from onert::ir::Operation.
Definition at line 35 of file LSTM.cc.
{
  if (getOutputs().at(Output::SCRATCH_BUFFER).undefined())
    return std::string{"UnidirectionalSequenceLSTM"};
  else
    return Operation::name();
}
References onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and SCRATCH_BUFFER.
Referenced by onert::ir::OperationDumper::visit().
opcode()
OpCode onert::ir::operation::LSTM::opcode () const inline final virtual
Implements onert::ir::Operation.
Definition at line 83 of file LSTM.h.
{ return OpCode::LSTM; }
param()
const Param & onert::ir::operation::LSTM::param () const inline
Definition at line 86 of file LSTM.h.
{ return _param; }
Referenced by onert::backend::acl_common::kernelGenLSTM(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), and onert::exec::DynamicShapeInferer::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/operation/LSTM.h
runtime/onert/core/src/ir/operation/LSTM.cc