ONE - On-device Neural Engine: coco::FeatureObject Class Reference
coco::FeatureObject Class Reference final
FeatureMap values (used in CNN)
#include <FeatureObject.h>
Public Member Functions
FeatureObject ()=default
~FeatureObject ()
Object::Kind kind (void) const override
FeatureObject * asFeature (void) override
const FeatureObject * asFeature (void) const override
const FeatureShape & shape (void) const
const FeatureLayout * layout (void) const
void layout (std::unique_ptr< FeatureLayout > &&l)
Public Member Functions inherited from coco::Object
Object ()
virtual ~Object ()=default
virtual Kind kind (void) const
coco::Bag * bag (void) const
void bag (coco::Bag *bag)
virtual FeatureObject * asFeature (void)
virtual const FeatureObject * asFeature (void) const
virtual KernelObject * asKernel (void)
virtual const KernelObject * asKernel (void) const
Def * def (void) const
const UseSet * uses (void) const
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Additional Inherited Members
Public Types inherited from coco::Object
enum class Kind { Unknown , Feature , Kernel }
using ConsumerSet = std::set< Consumer * >
Detailed Description
FeatureMap values (used in CNN)
Definition at line 35 of file FeatureObject.h.
Constructor & Destructor Documentation
FeatureObject()
coco::FeatureObject::FeatureObject () default
~FeatureObject()
coco::FeatureObject::~FeatureObject ()
Definition at line 24 of file FeatureObject.cpp.
{
  // DO NOTHING
}
Member Function Documentation
asFeature() [1/2]
const FeatureObject * coco::FeatureObject::asFeature (void) const inline override virtual
Reimplemented from coco::Object.
Definition at line 48 of file FeatureObject.h.
{ return this; }
asFeature() [2/2]
FeatureObject * coco::FeatureObject::asFeature (void) inline override virtual
Reimplemented from coco::Object.
Definition at line 47 of file FeatureObject.h.
{ return this; }
Referenced by tflimport::build_activation(), and enco::unify_feature().
kind()
Object::Kind coco::FeatureObject::kind (void) const inline override virtual
Reimplemented from coco::Object.
Definition at line 44 of file FeatureObject.h.
{ return Object::Kind::Feature; }
layout() [1/2]
void coco::FeatureObject::layout (std::unique_ptr< FeatureLayout > && l) inline
Definition at line 55 of file FeatureObject.h.
{ _layout = std::move(l); }
layout() [2/2]
const FeatureLayout * coco::FeatureObject::layout (void) const inline
Definition at line 54 of file FeatureObject.h.
{ return _layout.get(); }
Referenced by caffeimport::ConcatBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), and tflimport::SubGraphBuilder::build().
shape()
const FeatureShape & coco::FeatureObject::shape (void) const
Definition at line 29 of file FeatureObject.cpp.
{ return _layout->shape(); }
Referenced by tflimport::build_activation(), and dump().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/FeatureObject.h
compiler/coco/core/src/IR/FeatureObject.cpp