ONE - On-device Neural Engine: coco::InputManager Class Reference
coco::InputManager Class Reference final
#include <InputManager.h>
Public Member Functions
InputManager (Module *m=nullptr)
Input * create (const nncc::core::ADT::tensor::Shape &)
Public Member Functions inherited from coco::PtrManager< Input >
uint32_t size (void) const
Return the number of managed objects.
Input * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Input >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Input > release (Input *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 28 of file InputManager.h.
Constructor & Destructor Documentation
InputManager()
coco::InputManager::InputManager (Module * m = nullptr) inline
Definition at line 31 of file InputManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
Member Function Documentation
create()
Input * coco::InputManager::create (const nncc::core::ADT::tensor::Shape & shape)
Definition at line 24 of file InputManager.cpp.
{
  auto input = std::make_unique<Input>(shape);
  modulize(input.get());
  return take(std::move(input));
}
References coco::EntityBuilder::modulize(), and coco::PtrManager< Input >::take().
Referenced by caffeimport::InputBuilder::build().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/InputManager.h
compiler/coco/core/src/IR/InputManager.cpp