ONE - On-device Neural Engine: luci_interpreter::BuddyMemoryManager Class Reference
luci_interpreter::BuddyMemoryManager Class Reference
#include <BuddyMemoryManager.h>
Public Member Functions
BuddyMemoryManager (uint8_t *memory_start, int32_t memSize)
void allocate_memory (luci_interpreter::Tensor &tensor) final
void release_memory (luci_interpreter::Tensor &tensor) final
Public Member Functions inherited from luci_interpreter::IMemoryManager
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
Detailed Description
Definition at line 24 of file BuddyMemoryManager.h.
Constructor & Destructor Documentation
BuddyMemoryManager()
luci_interpreter::BuddyMemoryManager::BuddyMemoryManager (uint8_t * memory_start, int32_t memSize)
Definition at line 22 of file BuddyMemoryManager.cpp.
{
  int32_t p = lowerLog2(memSize);
  // We assume that the requested size of memory does not exceed 4 GB
  assert(p < 32);
  memSize = 1 << p;
  _start_block = reinterpret_cast<Block *>(memory_start);
  _start_block->size = memSize - sizeof(Block);
  _start_block->is_free = true;
  _start_block->self = _start_block;
  _num_blocks = 0;
  _size = _start_block->size;
  for (auto &_free_block : _free_blocks)
    _free_block = nullptr;
  addToBlocks(_start_block, p);
}
Member Function Documentation
allocate_memory()
void luci_interpreter::BuddyMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 43 of file BuddyMemoryManager.cpp.
{
  const size_t element_size = getDataTypeSize(tensor.element_type());
  const int32_t num_elements = tensor.shape().num_elements();
  auto size = num_elements * element_size;
  auto footprint = size + sizeof(Block);
  auto l = (footprint & (footprint - 1)) == 0
             ? lowerLog2(footprint)
             : lowerLog2(footprint) + 1; // check footprint is pow_of_2
  while (l < 32 && !_free_blocks[l])
    l++;
  if (l >= 32)
  {
    throw std::runtime_error{"Memory limit exceeded"};
  }
  Block *tmp;
  tmp = _free_blocks[l];
  removeFromBlocks(tmp, l);
  while ((tmp->size + sizeof(Block)) / 2 >= size + sizeof(Block))
  {
    divideBlock(tmp, l);
    l--;
  }
  tmp->is_free = false;
  tmp->self = tmp;
  _num_blocks++;
  auto *data = (uint8_t *)(tmp + 1);
  tensor.set_data_buffer(data);
}
References flatbuffers::data(), luci_interpreter::getDataTypeSize(), and size.
release_memory()
void luci_interpreter::BuddyMemoryManager::release_memory (luci_interpreter::Tensor & tensor) final virtual
Implements luci_interpreter::IMemoryManager.
Definition at line 79 of file BuddyMemoryManager.cpp.
{
  auto data = tensor.data<void>();
  auto *tmp = (Block *)((uint8_t *)data - sizeof(Block));
  assert(tmp->self == tmp);
  tmp->is_free = true;
  addToBlocks(tmp, lowerLog2(tmp->size + sizeof(Block)));
  while (tmp)
    if (tmp->size == _size)
      break;
    else
      tmp = mergeBlock(tmp);
  _num_blocks--;
  tensor.set_data_buffer(nullptr);
}
References flatbuffers::data().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/BuddyMemoryManager.h
compiler/luci-interpreter/src/BuddyMemoryManager.cpp