ONE - On-device Neural Engine: luci_interpreter::kernels::SplitV Class Reference
luci_interpreter::kernels::SplitV Class Reference
#include <SplitV.h>
Public Member Functions
SplitV (const Tensor *input, const Tensor *size_splits, const Tensor *axis, std::vector< Tensor * > outputs)
const Tensor * input () const
const Tensor * size_splits () const
const Tensor * axis () const
Tensor * output (int index) const
void configure () override
void execute () const override
SplitV (const Tensor *input, const Tensor *size_splits, const Tensor *axis, std::vector< Tensor * > outputs)
const Tensor * input () const
const Tensor * size_splits () const
const Tensor * axis () const
Tensor * output (int index) const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file SplitV.h.
Constructor & Destructor Documentation
SplitV() [1/2]
luci_interpreter::kernels::SplitV::SplitV (const Tensor * input, const Tensor * size_splits, const Tensor * axis, std::vector< Tensor * > outputs)
Definition at line 28 of file SplitV.cpp.
  : Kernel({input, size_splits, axis}, std::move(outputs))
{
}
References axis(), input(), and size_splits().
SplitV() [2/2]
luci_interpreter::kernels::SplitV::SplitV (const Tensor * input, const Tensor * size_splits, const Tensor * axis, std::vector< Tensor * > outputs)
Member Function Documentation
axis() [1/2]
const Tensor * luci_interpreter::kernels::SplitV::axis () const inline
Definition at line 36 of file SplitV.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SplitV().
axis() [2/2]
const Tensor * luci_interpreter::kernels::SplitV::axis () const inline
Definition at line 36 of file SplitV.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::SplitV::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 34 of file SplitV.cpp.
{
  assert(axis()->shape().num_elements() == 1);
  _axis_value = getTensorData<int32_t>(axis())[0];
  if (_axis_value < 0)
    _axis_value += input()->shape().num_dims();
  assert(_axis_value >= 0 && _axis_value < input()->shape().num_dims());
  auto num_split = static_cast<int32_t>(_outputs.size());
  auto sizes_data = getTensorData<int32_t>(size_splits());
  assert(size_splits()->shape().num_dims() == 1);
  int32_t sum = 0;
  const auto num_dims_size_spits = size_splits()->shape().dim(0);
  int32_t count_neg_dim = 0;
  for (int32_t i = 0; i < num_dims_size_spits - 1; ++i)
  {
    if (sizes_data[i] != -1)
    {
      sum += sizes_data[i];
    }
    else
    {
      count_neg_dim++;
    }
  }
  assert(count_neg_dim < 2);
  assert(size_splits()->shape().num_elements() == num_split);
  auto output_shape = input()->shape();
  for (int32_t i = 0; i < num_split; ++i)
  {
    if (sizes_data[i] == -1)
    {
      output_shape.dim(_axis_value) = input()->shape().dim(_axis_value) - sum;
    }
    else
    {
      output_shape.dim(_axis_value) = sizes_data[i];
    }
    _outputs[i]->resize(output_shape);
  }
}
References luci_interpreter::Kernel::_outputs, axis(), luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), luci_interpreter::Tensor::shape(), and size_splits().
configure() [2/2]
void luci_interpreter::kernels::SplitV::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::SplitV::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 80 of file SplitV.cpp.
{
  tflite::SplitParams params{};
  params.num_split = _outputs.size();
  params.axis = _axis_value;
#define TF_LITE_SPLIT(scalar)                                                                     \
  {                                                                                               \
    VectorOfTensors<scalar, false> all_outputs(_outputs);                                         \
    tflite::optimized_ops::Split(params, getTensorShape(input()), getTensorData<scalar>(input()), \
                                 all_outputs.shapes(), all_outputs.data());                       \
  }
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      TF_LITE_SPLIT(float);
      break;
    case DataType::U8:
      TF_LITE_SPLIT(uint8_t);
      break;
    case DataType::S16:
      TF_LITE_SPLIT(int16_t);
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
#undef TF_LITE_SPLIT
}
References luci_interpreter::Kernel::_outputs, input(), and TF_LITE_SPLIT.
execute() [2/2]
void luci_interpreter::kernels::SplitV::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::SplitV::input () const inline
Definition at line 34 of file SplitV.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SplitV().
input() [2/2]
const Tensor * luci_interpreter::kernels::SplitV::input () const inline
Definition at line 34 of file SplitV.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::SplitV::output (int index) const inline
Definition at line 37 of file SplitV.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
output() [2/2]
Tensor * luci_interpreter::kernels::SplitV::output (int index) const inline
Definition at line 37 of file SplitV.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
size_splits() [1/2]
const Tensor * luci_interpreter::kernels::SplitV::size_splits () const inline
Definition at line 35 of file SplitV.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SplitV().
size_splits() [2/2]
const Tensor * luci_interpreter::kernels::SplitV::size_splits () const inline
Definition at line 35 of file SplitV.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/SplitV.h
onert-micro/luci-interpreter/src/kernels/SplitV.h
compiler/luci-interpreter/src/kernels/SplitV.cpp
onert-micro/luci-interpreter/src/kernels/SplitV.cpp