ONE - On-device Neural Engine: moco::SymbolTable Class Reference
moco::SymbolTable Class Reference
Class to store and query loco::Node* with string name key.
#include <GraphBuilderContext.h>
Public Member Functions
void enroll (const TensorName &tensor_name, loco::Node *node)
Registers a name with corresponding loco::Node *.
loco::Node * node (const TensorName &tensor_name) const
Queries enrolled(registered) with name and return node if found Will throw runtime_error if not found.
Detailed Description
Class to store and query loco::Node* with string name key.
Definition at line 59 of file GraphBuilderContext.h.
Member Function Documentation
enroll()
void moco::SymbolTable::enroll (const TensorName & tensor_name, loco::Node * node)
Registers a name with corresponding loco::Node *.
Definition at line 51 of file GraphBuilderContext.cpp.
{
  MapNameNode_t::iterator iter = _table.find(tensor_name);
  if (iter != _table.end())
  {
    throw oops::UserExn("Duplicate node name in GraphDef", tensor_name.name());
  }
  _table[tensor_name] = node;
}
References node().
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::ConcatV2GraphBuilder::build(), moco::ConstGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::PackGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::tf::COpCallGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::ReshapeGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), and moco::TanhGraphBuilder::build().
node()
loco::Node * moco::SymbolTable::node (const TensorName & tensor_name) const
Queries enrolled(registered) with name and return node if found Will throw runtime_error if not found.
Definition at line 63 of file GraphBuilderContext.cpp.
{
  MapNameNode_t::const_iterator iter = _table.find(tensor_name);
  if (iter == _table.end())
  {
    throw oops::UserExn("Cannot find node with name in GraphDef", tensor_name.name());
  }
  return iter->second;
}
Referenced by enroll().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/GraphBuilderContext.h
compiler/moco/import/src/GraphBuilderContext.cpp