ONE - On-device Neural Engine: luci::ModuleProgressReporter Class Reference
luci::ModuleProgressReporter Class Reference
#include <ProgressReporter.h>
Public Member Functions
ModuleProgressReporter (luci::Module *module, logo::PhaseStrategy strategy)
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > *) override
luci::Module * module (void) const
logo::PhaseStrategy strategy (void) const
Public Member Functions inherited from logo::PhaseEventListener
virtual ~PhaseEventListener ()=default
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseEnd > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassEnd > *)
Detailed Description
Definition at line 53 of file ProgressReporter.h.
Constructor & Destructor Documentation
ModuleProgressReporter()
luci::ModuleProgressReporter::ModuleProgressReporter (luci::Module * module, logo::PhaseStrategy strategy) inline
Definition at line 56 of file ProgressReporter.h.
    : _module{module}, _strategy{strategy}
  {
    // DO NOTHING
  }
Member Function Documentation
module()
luci::Module * luci::ModuleProgressReporter::module (void) const inline
Definition at line 69 of file ProgressReporter.h.
{ return _module; }
Referenced by notify().
notify() [1/4]
void luci::ModuleProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > * info) override
Definition at line 105 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "--------------------------------------------------------------";
  INFO(prime) << "Before " << logo::pass_name(info->pass());
}
References INFO, info, LOGGER, and logo::pass_name().
notify() [2/4]
void luci::ModuleProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > * info) override
Definition at line 113 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "After " << logo::pass_name(info->pass())
              << " (changed: " << to_char(info->changed()) << ")";
  for (size_t g = 0; g < module()->size(); ++g)
  {
    INFO(prime) << "graphs #" << g;
    INFO(prime) << luci::fmt(module()->graph(g));
  }
}
References luci::fmt(), INFO, info, LOGGER, module(), logo::pass_name(), and luci::Module::size().
notify() [3/4]
void luci::ModuleProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
Definition at line 84 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "==============================================================";
  INFO(prime) << "ModulePhaseRunner<" << to_str(strategy()) << ">";
  INFO(prime) << "Initial graphs";
  for (size_t g = 0; g < module()->size(); ++g)
  {
    INFO(prime) << "graphs #" << g;
    INFO(prime) << luci::fmt(module()->graph(g));
  }
}
References luci::fmt(), INFO, LOGGER, module(), luci::Module::size(), and strategy().
notify() [4/4]
void luci::ModuleProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
Definition at line 98 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "ModulePhaseRunner<" << to_str(strategy()) << "> - done";
}
References INFO, LOGGER, and strategy().
strategy()
logo::PhaseStrategy luci::ModuleProgressReporter::strategy (void) const inline
Definition at line 70 of file ProgressReporter.h.
{ return _strategy; }
Referenced by notify().
The documentation for this class was generated from the following files:
compiler/luci/pass/src/ProgressReporter.h
compiler/luci/pass/src/ProgressReporter.cpp