ONE - On-device Neural Engine: circleinspect::DumpOperators Class Reference
circleinspect::DumpOperators Class Reference final
#include <Dump.h>
Public Member Functions
DumpOperators ()=default
void run (std::ostream &os, const circle::Model *model)
Public Member Functions inherited from circleinspect::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const circle::Model *model)=0
Detailed Description
Definition at line 36 of file Dump.h.
Constructor & Destructor Documentation
DumpOperators()
circleinspect::DumpOperators::DumpOperators () default
Member Function Documentation
run()
void circleinspect::DumpOperators::run (std::ostream & os, const circle::Model * model) virtual
Implements circleinspect::DumpInterface.
Definition at line 27 of file Dump.cpp.
{
  mio::circle::Reader reader(model);
  const uint32_t subgraph_size = reader.num_subgraph();
  for (uint32_t g = 0; g < subgraph_size; g++)
  {
    reader.select_subgraph(g);
    auto ops = reader.operators();
    // dump operators
    for (uint32_t i = 0; i < ops->Length(); ++i)
    {
      const auto op = ops->Get(i);
      auto op_name = reader.opcode_name(op);
      os << op_name << std::endl;
    }
  }
}
References mio::circle::Reader::num_subgraph(), mio::circle::Reader::opcode_name(), mio::circle::Reader::operators(), and mio::circle::Reader::select_subgraph().
The documentation for this class was generated from the following files:
compiler/circle-inspect/src/Dump.h
compiler/circle-inspect/src/Dump.cpp