ONE - On-device Neural Engine: luci_interpreter::RuntimeShape Class Reference
luci_interpreter::RuntimeShape Class Reference
#include <Tensor.h>
Public Member Functions
RuntimeShape (const RuntimeShape &other)
int flatSize () const
int32_t * dimsData ()
const int32_t * dimsData () const
RuntimeShape ()
RuntimeShape (int dimensions_count)
RuntimeShape (int dimensions_count, const int32_t *dims_data)
RuntimeShape (int new_shape_size, const RuntimeShape &shape, int pad_value)
RuntimeShape (int shape_size, int32_t value)
bool operator== (const RuntimeShape &comp) const
int32_t dimensionsCount () const
int32_t dims (int i) const
void setDim (int i, int32_t val)
void resize (int dimensions_count)
Static Public Member Functions
static RuntimeShape extendedShape (int new_shape_size, const RuntimeShape &shape)
Detailed Description
Definition at line 35 of file Tensor.h.
Constructor & Destructor Documentation
RuntimeShape() [1/6]
luci_interpreter::RuntimeShape::RuntimeShape (const RuntimeShape & other) inline
Definition at line 38 of file Tensor.h.
                                          : _size(other.dimensionsCount())
  {
    std::memcpy(dimsData(), other.dimsData(), sizeof(int32_t) * _size);
  }
References dimsData().
RuntimeShape() [2/6]
luci_interpreter::RuntimeShape::RuntimeShape () inline
Definition at line 59 of file Tensor.h.
: _size(0) {}
Referenced by extendedShape().
RuntimeShape() [3/6]
luci_interpreter::RuntimeShape::RuntimeShape (int dimensions_count) inline explicit
Definition at line 61 of file Tensor.h.
                                              : _size(dimensions_count)
  {
    assert(dimensions_count <= kMaxSmallSize);
    assert(dimensions_count >= 0);
  }
RuntimeShape() [4/6]
luci_interpreter::RuntimeShape::RuntimeShape (int dimensions_count, const int32_t * dims_data) inline
Definition at line 67 of file Tensor.h.
                                                               : _size(0)
  {
    resize(dimensions_count);
    int32_t *dst_dims = dimsData();
    std::memcpy(dst_dims, dims_data, dimensions_count * sizeof(int32_t));
  }
References dimsData(), and resize().
RuntimeShape() [5/6]
luci_interpreter::RuntimeShape::RuntimeShape (int new_shape_size, const RuntimeShape & shape, int pad_value) inline
Definition at line 74 of file Tensor.h.
                                                                             : _size(0)
  {
    resize(new_shape_size);
    const int size_increase = new_shape_size - shape.dimensionsCount();
    for (int i = 0; i < size_increase; ++i)
    {
      setDim(i, pad_value);
    }
    std::memcpy(dimsData() + size_increase, shape.dimsData(),
                sizeof(int32_t) * shape.dimensionsCount());
  }
References dimensionsCount(), dimsData(), resize(), and setDim().
RuntimeShape() [6/6]
luci_interpreter::RuntimeShape::RuntimeShape (int shape_size, int32_t value) inline
Definition at line 86 of file Tensor.h.
                                              : _size(0)
  {
    resize(shape_size);
    for (int i = 0; i < shape_size; ++i)
    {
      setDim(i, value);
    }
  }
References resize(), and setDim().
Member Function Documentation
dimensionsCount()
int32_t luci_interpreter::RuntimeShape::dimensionsCount () const inline
Definition at line 106 of file Tensor.h.
{ return _size; }
Referenced by luci_interpreter_pal::ArgMinMax(), luci_interpreter_pal::Concatenation(), luci_interpreter_pal::Negate(), luci_interpreter_pal::Offset(), luci_interpreter_pal::ProcessBroadcastShapes(), RuntimeShape(), luci_interpreter_pal::Softmax(), and luci_interpreter_pal::TransposeImpl().
dims()
int32_t luci_interpreter::RuntimeShape::dims (int i) const inline
Definition at line 108 of file Tensor.h.
  {
    assert(i <= _size);
    assert(i >= 0);
    return _dims[i];
  }
Referenced by luci_interpreter_pal::ArgMinMax(), luci_interpreter_pal::AveragePool(), luci_interpreter_pal::BroadcastAdd4DSlow(), luci_interpreter_pal::BroadcastDiv4DSlow(), luci_interpreter_pal::BroadcastMul4DSlow(), luci_interpreter_pal::BroadcastSub4DSlow(), luci_interpreter_pal::Concatenation(), luci_interpreter_pal::copyDimsToDesc(), luci_interpreter::kernels::getTensorDims(), luci_interpreter_pal::MatchingDim(), luci_interpreter_pal::MaxPool(), luci_interpreter_pal::Negate(), luci_interpreter_pal::Softmax(), and luci_interpreter_pal::StridedSlice().
dimsData() [1/2]
int32_t * luci_interpreter::RuntimeShape::dimsData () inline
Definition at line 56 of file Tensor.h.
{ return _dims; }
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate(), flatSize(), luci_interpreter_pal::Offset(), operator==(), and RuntimeShape().
dimsData() [2/2]
const int32_t * luci_interpreter::RuntimeShape::dimsData () const inline
Definition at line 57 of file Tensor.h.
{ return _dims; }
extendedShape()
static RuntimeShape luci_interpreter::RuntimeShape::extendedShape (int new_shape_size, const RuntimeShape & shape) inline static
Definition at line 95 of file Tensor.h.
  {
    return RuntimeShape(new_shape_size, shape, 1);
  }
References RuntimeShape().
Referenced by luci_interpreter_pal::BroadcastAdd4DSlow(), luci_interpreter_pal::BroadcastDiv4DSlow(), luci_interpreter_pal::BroadcastMul4DSlow(), luci_interpreter_pal::BroadcastSub4DSlow(), luci_interpreter_pal::NdArrayDescsForElementwiseBroadcast(), luci_interpreter_pal::Pad(), luci_interpreter_pal::ProcessBroadcastShapes(), luci_interpreter_pal::StridedSlice(), and luci_interpreter_pal::TransposeImpl().
flatSize()
int luci_interpreter::RuntimeShape::flatSize () const inline
Definition at line 45 of file Tensor.h.
  {
    int buffer_size = 1;
    const int *dims_data = reinterpret_cast<const int *>(dimsData());
    for (int i = 0; i < _size; i++)
    {
      buffer_size *= dims_data[i];
    }
    return buffer_size;
  }
References dimsData().
Referenced by luci_interpreter_pal::BroadcastDiv4DSlow(), luci_interpreter_pal::BroadcastMul4DSlow(), luci_interpreter::evalInteger(), luci_interpreter::execute_kernel_CircleAbs(), luci_interpreter::execute_kernel_CircleElu(), luci_interpreter::execute_kernel_CircleExp(), luci_interpreter::execute_kernel_CircleLeakyRelu(), luci_interpreter::execute_kernel_CircleLogistic(), luci_interpreter::execute_kernel_CircleRelu(), luci_interpreter::execute_kernel_CircleRelu6(), luci_interpreter::execute_kernel_CircleTanh(), luci_interpreter_pal::lstm_internal::lstmStep(), luci_interpreter_pal::lstm_internal::mul(), luci_interpreter_pal::Negate(), luci_interpreter_pal::ProcessBroadcastShapes(), luci_interpreter_pal::lstm_internal::sigmoid(), and luci_interpreter_pal::lstm_internal::tanh().
operator==()
bool luci_interpreter::RuntimeShape::operator== (const RuntimeShape & comp) const inline
Definition at line 100 of file Tensor.h.
  {
    return this->_size == comp._size &&
           std::memcmp(dimsData(), comp.dimsData(), _size * sizeof(int32_t)) == 0;
  }
References dimsData().
resize()
void luci_interpreter::RuntimeShape::resize (int dimensions_count) inline
Definition at line 121 of file Tensor.h.
  {
    assert(dimensions_count <= kMaxSmallSize);
    assert(dimensions_count >= 0);
    _size = dimensions_count;
  }
Referenced by mir_onnx::convertConvV1(), luci_interpreter::kernels::getTensorRuntimeShape(), RuntimeShape(), and nnkit::support::moco::tf::Backend::setInputOutputFromGraph().
setDim()
void luci_interpreter::RuntimeShape::setDim (int i, int32_t val) inline
Definition at line 114 of file Tensor.h.
  {
    assert(i <= _size);
    assert(i >= 0);
    _dims[i] = val;
  }
Referenced by luci_interpreter::kernels::calculateShapeForBroadcast(), luci_interpreter::execute_kernel_CircleReshape(), luci_interpreter::execute_kernel_CircleSlice(), luci_interpreter::kernels::getTensorRuntimeShape(), luci_interpreter::kernels::getTensorShape(), and RuntimeShape().
The documentation for this class was generated from the following file:
onert-micro/luci-interpreter/include/luci_interpreter/core/Tensor.h