ONE - On-device Neural Engine: onert::compiler::train::StaticBackwardShapeInferer Class Reference
onert::compiler::train::StaticBackwardShapeInferer Class Reference
Class to infer shape before running kernels. It does the following:
#include <StaticBackwardShapeInferer.h>
Public Member Functions
StaticBackwardShapeInferer (compiler::train::LoweredTrainableGraph *lowered_subg)
void infer (void)
Infer shape of operands belonging to ops and set the output shape. If output shape cannot be known without running op, mark it so that it can be allocated when running kernel.
void dump ()
Public Member Functions inherited from onert::ir::train::TrainableOperationVisitor
virtual ~TrainableOperationVisitor ()=default
Detailed Description
Class to infer shape before running kernels. It does the following:
re-calculate and set output shape at compile time (before running kernels)
if calculation cannot be done at compile time, mark the outputs to be dynamic, meaning shapes of outputs will be calculated during running kernels
Definition at line 41 of file StaticBackwardShapeInferer.h.
Constructor & Destructor Documentation
StaticBackwardShapeInferer()
onert::compiler::train::StaticBackwardShapeInferer::StaticBackwardShapeInferer (compiler::train::LoweredTrainableGraph * lowered_subg) inline
Definition at line 44 of file StaticBackwardShapeInferer.h.
    : _lowered_subg{lowered_subg}
  {
  }
Member Function Documentation
dump()
void onert::compiler::train::StaticBackwardShapeInferer::dump ()
Definition at line 55 of file StaticBackwardShapeInferer.cc.
{
  // TODO dump
}
infer()
void onert::compiler::train::StaticBackwardShapeInferer::infer (void)
Infer shape of operands belonging to ops and set the output shape. If output shape cannot be known without running op, mark it so that it can be allocated when running kernel.
Definition at line 33 of file StaticBackwardShapeInferer.cc.
{
  // It is not determined to iterate in reverse order.
  auto sorted_ops = _lowered_subg->graph().topolSortOperations();
  for (auto it = sorted_ops.rbegin(); it != sorted_ops.rend(); ++it)
  {
    const auto op_idx = *it;
    const auto &op = _lowered_subg->trainable_graph().operation(op_idx);
    if (checkDynamicInput(op))
    {
      std::stringstream msg;
      msg << "StaticBackwardShapeInferer does not support dynamic shape yet, ";
      msg << op.name() << "(op index: " << op_idx << ") has dynamic shape.";
      throw std::runtime_error(msg.str());
    }
    checkOutput(op);
    op.accept(*this);
  }
}
References onert::compiler::train::LoweredTrainableGraph::graph(), onert::ir::IOperation::name(), onert::ir::train::TrainableGraph::operation(), onert::ir::Graph::topolSortOperations(), and onert::compiler::train::LoweredTrainableGraph::trainable_graph().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.h
runtime/onert/core/src/compiler/train/StaticBackwardShapeInferer.cc