ONE - On-device Neural Engine: luci_interpreter::kernels::MISOKernel Class Reference
luci_interpreter::kernels::MISOKernel Class Reference
#include <MISOKernel.h>
Public Member Functions
MISOKernel (const circle::Operator *cur_op, BaseRuntimeGraph *runtime_graph)
const circle::Tensor * input1 () const
const circle::Tensor * input2 () const
const circle::Tensor * input3 () const
const circle::Tensor * input4 () const
const circle::Tensor * output () const
Detailed Description
Definition at line 28 of file MISOKernel.h.
Constructor & Destructor Documentation
MISOKernel()
luci_interpreter::kernels::MISOKernel::MISOKernel (const circle::Operator * cur_op, BaseRuntimeGraph * runtime_graph) inline
Definition at line 31 of file MISOKernel.h.
  {
    const auto input1_index = cur_op->inputs()->operator[](0);
    const auto input2_index = cur_op->inputs()->operator[](1);
    const auto input3_index = cur_op->inputs()->operator[](2);
    const auto input4_index =
      cur_op->inputs()->size() == 4 ? cur_op->inputs()->operator[](3) : -1; // optional
    const auto output_index = cur_op->outputs()->operator[](0);
    assert(input1_index != -1);
    assert(input2_index != -1);
    assert(input3_index != -1);
    assert(output_index != -1);
    _input1_tensor = runtime_graph->getCircleTensorByIndex(input1_index);
    _input2_tensor = runtime_graph->getCircleTensorByIndex(input2_index);
    _input3_tensor = runtime_graph->getCircleTensorByIndex(input3_index);
    _output_tensor = runtime_graph->getCircleTensorByIndex(output_index);
    // optional
    if (input4_index != -1)
      _input4_tensor = runtime_graph->getCircleTensorByIndex(input4_index);
    else
      _input4_tensor = nullptr;
    assert(_input1_tensor != nullptr);
    assert(_input2_tensor != nullptr);
    assert(_input3_tensor != nullptr);
    assert(_output_tensor != nullptr);
  }
References luci_interpreter::RuntimeGraph::getCircleTensorByIndex().
Member Function Documentation
input1()
const circle::Tensor * luci_interpreter::kernels::MISOKernel::input1 () const inline
Definition at line 64 of file MISOKernel.h.
{ return _input1_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleSlice(), luci_interpreter::configure_kernel_CircleStridedSlice(), luci_interpreter::execute_kernel_CircleSlice(), and luci_interpreter::execute_kernel_CircleStridedSlice().
input2()
const circle::Tensor * luci_interpreter::kernels::MISOKernel::input2 () const inline
Definition at line 65 of file MISOKernel.h.
{ return _input2_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleSlice(), luci_interpreter::configure_kernel_CircleStridedSlice(), luci_interpreter::execute_kernel_CircleSlice(), and luci_interpreter::execute_kernel_CircleStridedSlice().
input3()
const circle::Tensor * luci_interpreter::kernels::MISOKernel::input3 () const inline
Definition at line 66 of file MISOKernel.h.
{ return _input3_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleSlice(), luci_interpreter::configure_kernel_CircleStridedSlice(), luci_interpreter::execute_kernel_CircleSlice(), and luci_interpreter::execute_kernel_CircleStridedSlice().
input4()
const circle::Tensor * luci_interpreter::kernels::MISOKernel::input4 () const inline
Definition at line 68 of file MISOKernel.h.
  {
    assert(_input4_tensor != nullptr);
    return _input4_tensor;
  }
Referenced by luci_interpreter::configure_kernel_CircleStridedSlice(), and luci_interpreter::execute_kernel_CircleStridedSlice().
output()
const circle::Tensor * luci_interpreter::kernels::MISOKernel::output () const inline
Definition at line 74 of file MISOKernel.h.
{ return _output_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleSlice(), luci_interpreter::configure_kernel_CircleStridedSlice(), luci_interpreter::execute_kernel_CircleSlice(), and luci_interpreter::execute_kernel_CircleStridedSlice().
The documentation for this class was generated from the following file:
onert-micro/luci-interpreter/src/kernels/MISOKernel.h