ONE - On-device Neural Engine: circle_eval_diff::DirectoryLoader Class Reference
circle_eval_diff::DirectoryLoader Class Reference final
#include <InputDataLoader.h>
Public Member Functions
DirectoryLoader (const std::string &dir_path, const std::vector< loco::Node * > &input_nodes)
uint32_t size (void) const final
Data get (uint32_t data_idx) const final
Public Member Functions inherited from circle_eval_diff::InputDataLoader
virtual ~InputDataLoader ()=default
virtual uint32_t size (void) const =0
virtual Data get (uint32_t data_idx) const =0
Additional Inherited Members
Public Types inherited from circle_eval_diff::InputDataLoader
using Data = std::vector< Tensor >
Detailed Description
Definition at line 78 of file InputDataLoader.h.
Constructor & Destructor Documentation
DirectoryLoader()
circle_eval_diff::DirectoryLoader::DirectoryLoader (const std::string & dir_path, const std::vector< loco::Node * > & input_nodes)
Definition at line 155 of file InputDataLoader.cpp.
  : _input_nodes{input_nodes}
{
  DIR *dir = opendir(dir_path.c_str());
  if (not dir)
  {
    throw std::runtime_error("Cannot open directory \"" + dir_path + "\".");
  }
  struct dirent *entry = nullptr;
  const auto input_total_bytes = getTotalByteSizeOf(input_nodes);
  while (entry = readdir(dir))
  {
    // Skip if the entry is not a regular file
    if (entry->d_type != DT_REG)
      continue;
    _data_paths.push_back(dir_path + "/" + entry->d_name);
  }
  closedir(dir);
}
References circle_eval_diff::DIR, entry(), and circle_eval_diff::getTotalByteSizeOf().
Member Function Documentation
get()
InputDataLoader::Data circle_eval_diff::DirectoryLoader::get (uint32_t data_idx) const final virtual
Implements circle_eval_diff::InputDataLoader.
Definition at line 181 of file InputDataLoader.cpp.
{
  // Read raw data
  const auto input_total_bytes = getTotalByteSizeOf(_input_nodes);
  std::vector<char> input_data(input_total_bytes);
  const auto raw_data_path = _data_paths.at(data_idx);
  std::ifstream fs(raw_data_path, std::ifstream::binary);
  if (fs.fail())
  {
    throw std::runtime_error("Cannot open file \"" + raw_data_path + "\".");
  }
  if (fs.read(input_data.data(), input_total_bytes).fail())
  {
    throw std::runtime_error("Failed to read raw data from file \"" + raw_data_path + "\".");
  }
  // Make Tensor from raw data
  auto input_data_cur = input_data.data();
  Data data;
  data.resize(_input_nodes.size());
  std::vector<size_t> input_bytes = getEachByteSizeOf(_input_nodes);
  for (uint32_t index = 0; index < _input_nodes.size(); index++)
  {
    const auto input_node = loco::must_cast<const luci::CircleInput *>(_input_nodes.at(index));
    auto &tensor = data.at(index);
    tensor = *createEmptyTensor(input_node).get();
    auto buffer = tensor.buffer();
    std::memcpy(buffer, input_data_cur, input_bytes.at(index));
    input_data_cur += input_bytes.at(index);
  }
  return data;
}
References circle_eval_diff::createEmptyTensor(), circle_eval_diff::getEachByteSizeOf(), and circle_eval_diff::getTotalByteSizeOf().
size()
uint32_t circle_eval_diff::DirectoryLoader::size (void) const final virtual
Implements circle_eval_diff::InputDataLoader.
Definition at line 179 of file InputDataLoader.cpp.
{ return _data_paths.size(); }
The documentation for this class was generated from the following files:
compiler/circle-eval-diff/src/InputDataLoader.h
compiler/circle-eval-diff/src/InputDataLoader.cpp