ONE - On-device Neural Engine: luci::CircleReader Class Reference
luci::CircleReader Class Reference
Loads Circle file and provides helpers to access attributes.
#include <CircleReader.h>
Public Member Functions
CircleReader ()=default
CircleOperatorCodes opcodes () const
CircleBuffers buffers () const
CircleTensors tensors () const
CircleOperators operators () const
VectorWrapper< int32_t > inputs () const
VectorWrapper< int32_t > outputs () const
std::string name () const
CircleMetadataSet metadata () const
uint32_t num_subgraph () const
circle::BuiltinOperator builtin_code (const circle::Operator *op) const
std::string opcode_name (const circle::Operator *op) const
bool parse (const circle::Model *model)
bool parse (const circle::Model *model, const uint8_t *data, const size_t size)
bool select_subgraph (uint32_t subgraph)
const uint8_t * file_data (uint64_t offset) const
size_t file_size (void) const
Detailed Description
Loads Circle file and provides helpers to access attributes.
Definition at line 92 of file CircleReader.h.
Constructor & Destructor Documentation
CircleReader()
luci::CircleReader::CircleReader () default
Member Function Documentation
buffers()
CircleBuffers luci::CircleReader::buffers () const inline
Definition at line 106 of file CircleReader.h.
{ return wrap(_model->buffers()); }
References luci::wrap().
Referenced by luci::CircleImportMetadata::CircleImportMetadata(), luci_interpreter::RuntimeGraph::getConstDataByTensor(), and luci_interpreter::Tensor::is_constant_tensor().
builtin_code()
circle::BuiltinOperator luci_interpreter::CircleReader::builtin_code (const circle::Operator * op) const
Definition at line 349 of file CircleReader.cpp.
{
  assert(op != nullptr);
  const auto op_codes = opcodes();
  uint32_t index = op->opcode_index();
  assert(index < op_codes.size());
  const auto opcode = op_codes[index];
  assert(opcode != nullptr);
  return mio::circle::builtin_code_neutral(opcode);
}
References mio::circle::builtin_code_neutral(), luci::must_cast(), and opcodes().
Referenced by luci_interpreter::GraphLoader::checkInplaceOps(), luci_interpreter::RuntimeGraph::configure(), luci_interpreter::RuntimeGraph::execute(), and run().
file_data()
const uint8_t * luci::CircleReader::file_data (uint64_t offset) const
Definition at line 419 of file CircleReader.cpp.
{
  assert(_file_data);
  assert(offset < _file_size);
  return (_file_data == nullptr) ? nullptr : _file_data + offset;
}
References luci::must_cast(), and offset().
file_size()
size_t luci::CircleReader::file_size (void) const inline
Definition at line 127 of file CircleReader.h.
{ return _file_size; }
inputs()
VectorWrapper< int32_t > luci::CircleReader::inputs () const inline
Definition at line 109 of file CircleReader.h.
{ return wrap(_current_subgraph->inputs()); }
References luci::wrap().
Referenced by onert.experimental.train.dataloader.DataLoader::__init__(), luci_interpreter::RuntimeGraph::configureGraphInput(), luci_interpreter::RuntimeGraph::configureGraphInput(), validate_onnx2circle.OnnxRunner::feed_random_inputs(), luci_interpreter::RuntimeGraph::getInputDataSizeByIndex(), luci_interpreter::RuntimeGraph::getInputTensorByIndex(), luci_interpreter::RuntimeGraph::getNumOfInputTensors(), luci_interpreter::RuntimeGraph::resetOutputTensorsData(), onert.common.basesession.BaseSession::set_inputs(), and onert.experimental.train.dataloader.DataLoader::split().
metadata()
CircleMetadataSet luci::CircleReader::metadata () const inline
Definition at line 112 of file CircleReader.h.
{ return wrap(_model->metadata()); }
References luci::wrap().
Referenced by luci::CircleImportMetadata::CircleImportMetadata().
name()
std::string luci::CircleReader::name () const inline
Definition at line 111 of file CircleReader.h.
{ return fb_string2std_string(_current_subgraph->name()); }
References luci::fb_string2std_string().
num_subgraph()
uint32_t luci::CircleReader::num_subgraph () const inline
Definition at line 114 of file CircleReader.h.
{ return wrap(_model->subgraphs()).size(); }
References luci::wrap().
Referenced by luci_interpreter::ModuleLoader::load(), run(), and select_subgraph().
opcode_name()
std::string luci::CircleReader::opcode_name (const circle::Operator * op) const
Definition at line 362 of file CircleReader.cpp.
{
  assert(op != nullptr);
  const auto op_codes = opcodes();
  uint32_t index = op->opcode_index();
  assert(index < op_codes.size());
  const auto opcode = op_codes[index];
  return mio::circle::opcode_name(opcode);
}
References luci::must_cast(), mio::circle::opcode_name(), and opcodes().
opcodes()
CircleOperatorCodes luci::CircleReader::opcodes () const inline
Definition at line 105 of file CircleReader.h.
{ return wrap(_model->operator_codes()); }
References luci::wrap().
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::CircleWhileGraphBuilder::build(), builtin_code(), and opcode_name().
operators()
CircleOperators luci::CircleReader::operators () const inline
Definition at line 108 of file CircleReader.h.
{ return wrap(_current_subgraph->operators()); }
References luci::wrap().
Referenced by luci_interpreter::GraphLoader::checkInplaceOps(), luci_interpreter::RuntimeGraph::configure(), luci_interpreter::RuntimeGraph::execute(), and run().
outputs()
VectorWrapper< int32_t > luci::CircleReader::outputs () const inline
Definition at line 110 of file CircleReader.h.
{ return wrap(_current_subgraph->outputs()); }
References luci::wrap().
Referenced by onert.common.basesession.BaseSession::_set_outputs(), luci_interpreter::GraphLoader::checkInplaceOps(), luci_interpreter::RuntimeGraph::execute(), validate_onnx2circle.OnnxRunner::get_outputs(), luci_interpreter::RuntimeGraph::getNumOfOutputTensors(), luci_interpreter::RuntimeGraph::getOutputDataByIndex(), luci_interpreter::RuntimeGraph::getOutputDataSizeByIndex(), luci_interpreter::RuntimeGraph::getOutputTensorByIndex(), and luci_interpreter::RuntimeGraph::resetOutputTensorsData().
parse() [1/2]
bool luci_interpreter::CircleReader::parse (const circle::Model * model)
Definition at line 374 of file CircleReader.cpp.
{
  assert(model != nullptr);
  // for direct pointer access
  _model = model;
  return true;
}
Referenced by luci_interpreter::ModuleLoader::load(), and run().
parse() [2/2]
bool luci::CircleReader::parse (const circle::Model * model, const uint8_t * data, const size_t size)
Definition at line 384 of file CircleReader.cpp.
{
  assert(model != nullptr);
  assert(data != nullptr);
  assert(size > 0);
  // for direct pointer access
  _model = model;
  _file_data = data;
  _file_size = size;
  return true;
}
References flatbuffers::data(), and size.
select_subgraph()
bool luci_interpreter::CircleReader::select_subgraph (uint32_t subgraph)
Definition at line 399 of file CircleReader.cpp.
{
  if (num_subgraph() <= sgindex)
  {
    assert(false);
    return false;
  }
  // for direct pointer access
  auto subgraphs = _model->subgraphs();
  assert(subgraphs != nullptr);
  _current_subgraph = subgraphs->Get(sgindex);
  assert(_current_subgraph != nullptr);
  return true;
}
References luci::must_cast(), and num_subgraph().
Referenced by luci_interpreter::ModuleLoader::load(), run(), and luci_interpreter::RuntimeModule::selectSubgraph().
tensors()
CircleTensors luci::CircleReader::tensors () const inline
Definition at line 107 of file CircleReader.h.
{ return wrap(_current_subgraph->tensors()); }
References luci::wrap().
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::CircleWhileGraphBuilder::build(), luci_interpreter::CircleReferencingConstNodeBuilder::build(), luci::CircleConstNodeBuilder::build(), luci_interpreter::GraphLoader::checkInplaceOps(), luci_interpreter::RuntimeGraph::configureGraphInput(), luci_interpreter::RuntimeGraph::configureGraphInput(), luci::create_circlevariable(), luci_interpreter::RuntimeGraph::execute(), luci_interpreter::RuntimeGraph::getCircleTensorByIndex(), luci_interpreter::RuntimeGraph::getInputDataSizeByIndex(), luci_interpreter::RuntimeGraph::getInputTensorByIndex(), luci_interpreter::RuntimeGraph::getOutputDataByIndex(), luci_interpreter::RuntimeGraph::getOutputDataSizeByIndex(), luci_interpreter::RuntimeGraph::getOutputTensorByIndex(), and luci_interpreter::RuntimeGraph::resetOutputTensorsData().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Import/CircleReader.h
compiler/luci/import/src/CircleReader.cpp
onert-micro/luci-interpreter/src/core/reader/CircleMicroReader.cpp