ONE - On-device Neural Engine: mir::Index Class Reference
mir::Index Class Reference
#include <Index.h>
Public Member Functions
Index ()=default
Index (std::initializer_list< int32_t > &&l) noexcept
Index (size_t rank)
int32_t rank () const
Index & resize (int32_t size)
resize index to given dimension number
Index & fill (int32_t index)
fill all axis with index
int32_t & at (int32_t axis)
return position on given axis
int32_t at (int32_t axis) const
return position on given axis
Detailed Description
Definition at line 31 of file Index.h.
Constructor & Destructor Documentation
Index() [1/3]
mir::Index::Index () default
Index() [2/3]
mir::Index::Index (std::initializer_list< int32_t > && l) inline noexcept
Definition at line 36 of file Index.h.
                                                   : _indices(std::move(l))
  {
    // DO NOTHING
  }
Index() [3/3]
mir::Index::Index (size_t rank) inline explicit
Definition at line 41 of file Index.h.
: _indices(rank) {}
Member Function Documentation
at() [1/2]
int32_t & mir::Index::at (int32_t axis) inline
return position on given axis
Parameters
axis index of axis to get index on. If axis is negative returns axis from the last
Returns
Definition at line 64 of file Index.h.
{ return _indices[wrap_index(axis, _indices.size())]; }
References adt::small_vector< T, Capacity >::size(), and mir::wrap_index().
Referenced by mir::ShapeRange::contains(), mir::TensorVariant::getOffset(), mir::Tensor< T >::getRegion(), mir::ShapeIter::operator++(), mir::operator<<(), mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::SoftmaxImpl< T >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::TransposeImpl< T >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), mir_interpreter::ReduceMeanImpl< T >::run(), mir_interpreter::FullyConnectedImpl< T >::run(), and mir_interpreter::MIRInterpreter::visit().
at() [2/2]
int32_t mir::Index::at (int32_t axis) const inline
return position on given axis
Parameters
axis index of axis to get index on. If axis is negative returns axis from the last
Returns
Definition at line 71 of file Index.h.
{ return _indices[wrap_index(axis, _indices.size())]; }
References adt::small_vector< T, Capacity >::size(), and mir::wrap_index().
fill()
Index & mir::Index::fill (int32_t index)
fill all axis with index
Returns
*this
Definition at line 30 of file Index.cpp.
{
  std::fill(std::begin(_indices), std::end(_indices), index);
  return (*this);
}
rank()
int32_t mir::Index::rank () const inline
Definition at line 43 of file Index.h.
{ return static_cast<int32_t>(_indices.size()); }
References adt::small_vector< T, Capacity >::size().
Referenced by mir::ShapeRange::contains(), mir::TensorVariant::getOffset(), mir::ShapeIter::operator!=(), mir::operator<<(), and mir_interpreter::shift().
resize()
Index & mir::Index::resize (int32_t size)
resize index to given dimension number
Parameters
size new number of dimensions
Returns
*this
Warning
if new size is greater than old, new dimensions are undefined
Definition at line 24 of file Index.cpp.
{
  _indices.resize(size);
  return *this;
}
References adt::small_vector< T, Capacity >::resize().
Referenced by mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::TransposeImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), and mir_interpreter::MIRInterpreter::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/Index.h
compiler/mir/src/Index.cpp