ONE - On-device Neural Engine: luci::CircleBCQFullyConnected Class Reference
luci::CircleBCQFullyConnected Class Reference final
BCQ_FULLY_CONNECTED in Circle.
#include <CircleBCQFullyConnected.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * weights_scales (void) const
void weights_scales (loco::Node *node)
loco::Node * weights_binary (void) const
void weights_binary (loco::Node *node)
loco::Node * bias (void) const override
void bias (loco::Node *node) override
get the input for bias.
loco::Node * weights_clusters (void) const
void weights_clusters (loco::Node *node)
int32_t weights_hidden_size (void) const
void weights_hidden_size (int32_t weights_hidden_size)
Public Member Functions inherited from luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::Bias >
CircleNodeMixin ()=default
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >
loco::Use * at (uint32_t n) const
Detailed Description
BCQ_FULLY_CONNECTED in Circle.
Definition at line 32 of file CircleBCQFullyConnected.h.
Member Function Documentation
bias() [1/2]
void luci::CircleBCQFullyConnected::bias (loco::Node * node) inline override virtual
get the input for bias.
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 48 of file CircleBCQFullyConnected.h.
{ at(3)->node(node); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
bias() [2/2]
loco::Node * luci::CircleBCQFullyConnected::bias (void) const inline override virtual
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 47 of file CircleBCQFullyConnected.h.
{ return at(3)->node(); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
input() [1/2]
void luci::CircleBCQFullyConnected::input (loco::Node * node) inline
Definition at line 39 of file CircleBCQFullyConnected.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleBCQFullyConnected::input (void) const inline
Definition at line 38 of file CircleBCQFullyConnected.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_binary() [1/2]
void luci::CircleBCQFullyConnected::weights_binary (loco::Node * node) inline
Definition at line 45 of file CircleBCQFullyConnected.h.
{ at(2)->node(node); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_binary() [2/2]
loco::Node * luci::CircleBCQFullyConnected::weights_binary (void) const inline
Definition at line 44 of file CircleBCQFullyConnected.h.
{ return at(2)->node(); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_clusters() [1/2]
void luci::CircleBCQFullyConnected::weights_clusters (loco::Node * node) inline
Definition at line 51 of file CircleBCQFullyConnected.h.
{ at(4)->node(node); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_clusters() [2/2]
loco::Node * luci::CircleBCQFullyConnected::weights_clusters (void) const inline
Definition at line 50 of file CircleBCQFullyConnected.h.
{ return at(4)->node(); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_hidden_size() [1/2]
void luci::CircleBCQFullyConnected::weights_hidden_size (int32_t weights_hidden_size) inline
Definition at line 55 of file CircleBCQFullyConnected.h.
  {
    _weights_hidden_size = weights_hidden_size;
  }
References weights_hidden_size().
weights_hidden_size() [2/2]
int32_t luci::CircleBCQFullyConnected::weights_hidden_size (void) const inline
Definition at line 54 of file CircleBCQFullyConnected.h.
{ return _weights_hidden_size; }
Referenced by luci::CloneNode::visit(), luci::BuiltinOptionsExtractor::visit(), and weights_hidden_size().
weights_scales() [1/2]
void luci::CircleBCQFullyConnected::weights_scales (loco::Node * node) inline
Definition at line 42 of file CircleBCQFullyConnected.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
weights_scales() [2/2]
loco::Node * luci::CircleBCQFullyConnected::weights_scales (void) const inline
Definition at line 41 of file CircleBCQFullyConnected.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 5, CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleBCQFullyConnected.h