ONE - On-device Neural Engine: luci::CommonSubExpressionEliminationPass Class Reference
luci::CommonSubExpressionEliminationPass Class Reference
Pass to perform CSE (Common Sub-expression Elimination)
#include <CommonSubExpressionEliminationPass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to perform CSE (Common Sub-expression Elimination)
Definition at line 28 of file CommonSubExpressionEliminationPass.h.
Member Function Documentation
name()
virtual const char * luci::CommonSubExpressionEliminationPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 31 of file CommonSubExpressionEliminationPass.h.
{ return "luci::CommonSubExpressionEliminationPass"; }
run()
bool luci::CommonSubExpressionEliminationPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 52 of file CommonSubExpressionEliminationPass.cpp.
{
  // Build cache
  ExpressionCache cache;
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto cnode = loco::must_cast<luci::CircleNode *>(node);
    // Skip virtual Ops
    // Why? virtual Ops do not perform actual computations
    // NOTE Fix this if the assumption is not true
    if (virtual_op(cnode->opcode()))
      continue;
    // Build expression
    auto expr = Expression::build(cnode);
    // Invalid (NYI) expression
    if (expr.op == nullptr)
      continue;
    // Cache hit
    if (auto saved_node = cache.get(expr))
    {
      loco::replace(cnode).with(saved_node);
      changed = true;
    }
    // Cache miss
    else
    {
      cache.put(expr, cnode);
    }
  }
  return changed;
}
References loco::active_nodes(), luci::pass::Expression::build(), luci::pass::ExpressionCache::get(), loco::output_nodes(), luci::pass::ExpressionCache::put(), loco::replace(), and loco::Subst< SubstQualifier::Default >::with().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/CommonSubExpressionEliminationPass.h
compiler/luci/pass/src/CommonSubExpressionEliminationPass.cpp