ONE - On-device Neural Engine: luci::CircleOptimizer Class Reference
luci::CircleOptimizer Class Reference final
#include <CircleOptimizer.h>
Data Structures
struct Options
Public Member Functions
Options * options (void)
void optimize (luci::Module *) const
void optimize (loco::Graph *) const
void sparsify (loco::Graph *) const
Detailed Description
Definition at line 30 of file CircleOptimizer.h.
Member Function Documentation
optimize() [1/2]
void luci::CircleOptimizer::optimize (loco::Graph * g) const
Definition at line 266 of file CircleOptimizer.cpp.
{
  canonicalize(g);
  logo::Phase phase;
  // Conversion from NCHW to NHWC is done first to avoid interference with other optimizations.
  if (_options->query(Options::Algorithm::ConvertNCHWToNHWC))
  {
    bool preserve_input =
      _options->param(Options::AlgorithmParameters::NCHW_to_NHWC_input_shape) != "true";
    bool preserve_output =
      _options->param(Options::AlgorithmParameters::NCHW_to_NHWC_output_shape) != "true";
    bool fuse_fc = _options->query(Options::Algorithm::FuseAddWithFullyConnected);
    bool fuse_gelu = _options->query(Options::Algorithm::FuseGelu);
    convert_nchw_to_nhwc(g, preserve_input, preserve_output, fuse_fc, fuse_gelu);
  }
  /* TRANSFORM DECLARATION BEGIN */
  phase.emplace_back(std::make_unique<logo::RemoveDeadNodeWithQueryPass>());
  // Following passes are needed everytime when other passes create new node or modify some nodes.
  phase.emplace_back(std::make_unique<luci::CircleShapeInferencePass>());
  phase.emplace_back(std::make_unique<luci::CircleTypeInferencePass>());
  // Forward Reshape/Transpose is done after
  // 1. SubstituteXXXToReshape
  // 2. RemoveRedundantReshape/Transpose
  // See https://github.com/Samsung/ONE/pull/10596 for more details
  if (_options->query(Options::Algorithm::SubstituteExpandDimsToReshape))
  {
    phase.emplace_back(std::make_unique<luci::SubstituteExpandDimsToReshapePass>());
  }
  if (_options->query(Options::Algorithm::SubstitutePackToReshape))
  {
    phase.emplace_back(std::make_unique<luci::SubstitutePackToReshapePass>());
  }
  if (_options->query(Options::Algorithm::SubstituteSqueezeToReshape))
  {
    phase.emplace_back(std::make_unique<luci::SubstituteSqueezeToReshapePass>());
  }
  if (_options->query(Options::Algorithm::SubstituteStridedSliceToReshape))
  {
    phase.emplace_back(std::make_unique<luci::SubstituteStridedSliceToReshapePass>());
  }
  if (_options->query(Options::Algorithm::SubstituteTransposeToReshape))
  {
    phase.emplace_back(std::make_unique<luci::SubstituteTransposeToReshapePass>());
  }
  if (_options->query(Options::Algorithm::RemoveRedundantReshape))
  {
    phase.emplace_back(std::make_unique<luci::RemoveRedundantReshapePass>());
  }
  if (_options->query(Options::Algorithm::RemoveRedundantTranspose))
  {
    phase.emplace_back(std::make_unique<luci::RemoveRedundantTransposePass>());
  }
  // clang-format off
  std::map<Options::Algorithm, std::unique_ptr<logo::Pass> (*)(void)> option_to_pass;
  option_to_pass[Options::Algorithm::CommonSubExpressionElimination] = &createPassInstance<luci::CommonSubExpressionEliminationPass>;
  option_to_pass[Options::Algorithm::ResolveCustomOpAdd] = &createPassInstance<luci::ResolveCustomOpAddPass>;
  option_to_pass[Options::Algorithm::ResolveCustomOpBatchMatMul] = &createPassInstance<luci::ResolveCustomOpBatchMatMulPass>;
  option_to_pass[Options::Algorithm::ResolveCustomOpMatMul] = &createPassInstance<luci::ResolveCustomOpMatMulPass>;
  option_to_pass[Options::Algorithm::ResolveFormerCustomOp] = &createPassInstance<luci::ResolveFormerCustomOpPass>;
  option_to_pass[Options::Algorithm::FuseMeanWithMean] = &createPassInstance<luci::FuseMeanWithMeanPass>;
  option_to_pass[Options::Algorithm::FuseMulWithConv] = &createPassInstance<luci::FuseMulWithConvPass>;
  option_to_pass[Options::Algorithm::FuseMulWithDiv] = &createPassInstance<luci::FuseMulWithDivPass>;
  option_to_pass[Options::Algorithm::FuseMulWithFullyConnected] = &createPassInstance<luci::FuseMulWithFullyConnectedPass>;
  option_to_pass[Options::Algorithm::FuseMulWithRmsNorm] = &createPassInstance<luci::FuseMulWithRmsNormPass>;
  option_to_pass[Options::Algorithm::ResolveCustomOpMaxPoolWithArgmax] = &createPassInstance<luci::ResolveCustomOpMaxPoolWithArgmaxPass>;
  option_to_pass[Options::Algorithm::ResolveCustomOpSplitV] = &createPassInstance<luci::ResolveCustomOpSplitVPass>;
  option_to_pass[Options::Algorithm::FuseInstanceNorm] = &createPassInstance<luci::FuseInstanceNormPass>;
  option_to_pass[Options::Algorithm::FuseBatchNormWithConv] = &createPassInstance<luci::FuseBatchNormWithConvPass>;
  option_to_pass[Options::Algorithm::FuseBatchNormWithDwConv] = &createPassInstance<luci::FuseBatchNormWithDwConvPass>;
  option_to_pass[Options::Algorithm::FuseBatchNormWithTConv] = &createPassInstance<luci::FuseBatchNormWithTConvPass>;
  option_to_pass[Options::Algorithm::FuseSliceWithTConv] = &createPassInstance<luci::FuseSliceWithTConvPass>;
  option_to_pass[Options::Algorithm::FuseAddToFullyConnectedBias] = &createPassInstance<luci::FuseAddToFullyConnectedBiasPass>;
  option_to_pass[Options::Algorithm::FuseAddWithConv] = &createPassInstance<luci::FuseAddWithConvPass>;
  option_to_pass[Options::Algorithm::FuseAddWithFullyConnected] = &createPassInstance<luci::FuseAddWithFullyConnectedPass>;
  option_to_pass[Options::Algorithm::FuseAddWithTConv] = &createPassInstance<luci::FuseAddWithTConvPass>;
  option_to_pass[Options::Algorithm::FuseActivationFunction] = &createPassInstance<luci::FuseActivationFunctionPass>;
  option_to_pass[Options::Algorithm::FuseMulToFullyConnectedWeights] = &createPassInstance<luci::FuseMulToFullyConnectedWeightsPass>;
  option_to_pass[Options::Algorithm::FusePRelu] = &createPassInstance<luci::FusePReluPass>;
  option_to_pass[Options::Algorithm::FuseGelu] = &createPassInstance<luci::FuseGeluPass>;
  option_to_pass[Options::Algorithm::FuseRsqrt] = &createPassInstance<luci::FuseRsqrtPass>;
  option_to_pass[Options::Algorithm::FuseHorizontalFullyConnected] = &createPassInstance<luci::FuseHorizontalFullyConnectedPass>;
  option_to_pass[Options::Algorithm::FuseTransposeWithMean] = &createPassInstance<luci::FuseTransposeWithMeanPass>;
  option_to_pass[Options::Algorithm::FuseRmsNorm] = &createPassInstance<luci::FuseRmsNormPass>;
  option_to_pass[Options::Algorithm::FuseRoPE] = &createPassInstance<luci::FuseRoPEPass>;
  option_to_pass[Options::Algorithm::FoldAddV2] = &createPassInstance<luci::FoldAddV2Pass>;
  option_to_pass[Options::Algorithm::FoldCast] = &createPassInstance<luci::FoldCastPass>;
  option_to_pass[Options::Algorithm::FoldDensify] = &createPassInstance<luci::FoldDensifyPass>;
  option_to_pass[Options::Algorithm::FoldDepthwiseConv2D] = &createPassInstance<luci::FoldDepthwiseConv2DPass>;
  option_to_pass[Options::Algorithm::FoldDequantize] = &createPassInstance<luci::FoldDequantizePass>;
  option_to_pass[Options::Algorithm::FoldFullyConnected] = &createPassInstance<luci::FoldFullyConnectedPass>;
  option_to_pass[Options::Algorithm::FoldGather] = &createPassInstance<luci::FoldGatherPass>;
  option_to_pass[Options::Algorithm::FoldMul] = &createPassInstance<luci::FoldMulPass>;
  option_to_pass[Options::Algorithm::FoldReshape] = &createPassInstance<luci::FoldReshapePass>;
  option_to_pass[Options::Algorithm::FoldShape] = &createPassInstance<luci::FoldShapePass>;
  option_to_pass[Options::Algorithm::FoldSparseToDense] = &createPassInstance<luci::FoldSparseToDensePass>;
  option_to_pass[Options::Algorithm::FoldSqueeze] = &createPassInstance<luci::FoldSqueezePass>;
  option_to_pass[Options::Algorithm::FusePreActivationBatchNorm] = &createPassInstance<luci::FusePreActivationBatchNormPass>;
  option_to_pass[Options::Algorithm::MakeBatchNormGammaPositive] = &createPassInstance<luci::MakeBatchNormGammaPositivePass>;
  option_to_pass[Options::Algorithm::ShuffleWeightTo16x1Float32] = &createPassInstance<luci::ShuffleWeightTo16x1Float32Pass>;
  option_to_pass[Options::Algorithm::ExpandBroadcastConst] = &createPassInstance<luci::ExpandBroadcastConstPass>;
  option_to_pass[Options::Algorithm::RemoveDuplicateConst] = &createPassInstance<luci::RemoveDuplicateConstPass>;
  option_to_pass[Options::Algorithm::RemoveFakeQuant] = &createPassInstance<luci::RemoveFakeQuantPass>;
  option_to_pass[Options::Algorithm::RemoveGatherGuard] = &createPassInstance<luci::RemoveGatherGuardPass>;
  option_to_pass[Options::Algorithm::RemoveQDQForMixedPrecisionOp] = &createPassInstance<luci::RemoveQDQForMixedPrecisionOpPass>;
  option_to_pass[Options::Algorithm::RemoveQuantDequantSeq] = &createPassInstance<luci::RemoveQuantDequantSeqPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryAdd] = &createPassInstance<luci::RemoveUnnecessaryAddPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryCast] = &createPassInstance<luci::RemoveUnnecessaryCastPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryDiv] = &createPassInstance<luci::RemoveUnnecessaryDivPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryMul] = &createPassInstance<luci::RemoveUnnecessaryMulPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessarySlice] = &createPassInstance<luci::RemoveUnnecessarySlicePass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryStridedSlice] = &createPassInstance<luci::RemoveUnnecessaryStridedSlicePass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessarySplit] = &createPassInstance<luci::RemoveUnnecessarySplitPass>;
  option_to_pass[Options::Algorithm::RemoveUnnecessaryTranspose] = &createPassInstance<luci::RemoveUnnecessaryTransposeNetPass>;
  option_to_pass[Options::Algorithm::RemoveRedundantQuantize] = &createPassInstance<luci::RemoveRedundantQuantizePass>;
  option_to_pass[Options::Algorithm::ReplaceNonConstFCWithBatchMatMul] = &createPassInstance<luci::ReplaceNonConstFCWithBatchMatMulPass>;
  option_to_pass[Options::Algorithm::ReplaceMulAddWithDepthwiseConv] = &createPassInstance<luci::ReplaceMulAddWithDepthwiseConvPass>;
  option_to_pass[Options::Algorithm::ReplaceSubWithAdd] = &createPassInstance<luci::ReplaceSubWithAddPass>;
  option_to_pass[Options::Algorithm::ReplaceWithFCGeluFC] = &createPassInstance<luci::ReplaceWithFCGeluFCPass>;
  option_to_pass[Options::Algorithm::SubstitutePadV2ToPad] = &createPassInstance<luci::SubstitutePadV2ToPadPass>;
  option_to_pass[Options::Algorithm::SubstituteSplitVToSplit] = &createPassInstance<luci::SubstituteSplitVToSplitPass>;
  option_to_pass[Options::Algorithm::TransformMinMaxToRelu6Pass] = &createPassInstance<luci::TransformMinMaxToRelu6Pass>;
  option_to_pass[Options::Algorithm::TransformMinReluToRelu6Pass] = &createPassInstance<luci::TransformMinReluToRelu6Pass>;
  option_to_pass[Options::Algorithm::TransformSqrtDivToRsqrtMul] = &createPassInstance<luci::TransformSqrtDivToRsqrtMulPass>;
  option_to_pass[Options::Algorithm::DecomposeHardSwishPass] = &createPassInstance<luci::DecomposeHardSwishPass>;
  option_to_pass[Options::Algorithm::DecomposeSoftmaxPass] = &createPassInstance<luci::DecomposeSoftmaxPass>;
  option_to_pass[Options::Algorithm::UnrollUnidirSeqLSTM] = &createPassInstance<luci::UnrollUnidirectionalSequenceLSTMPass>;
  // NOTE Experimental options; these will be removed someday
  //      Add experimental options here
  option_to_pass[Options::Algorithm::XpSepActFromTransposeConv] = &createPassInstance<luci::XpSepActFromTransposeConvPass>;
  option_to_pass[Options::Algorithm::ForwardReshapeToUnaryOp] = &createPassInstance<luci::ForwardReshapeToUnaryOpPass>;
  option_to_pass[Options::Algorithm::ForwardTransposeOp] = &createPassInstance<luci::ForwardTransposeOpPass>;
  // clang-format on
  for (auto const &m : option_to_pass)
  {
    if (_options->query(m.first))
    {
      phase.emplace_back(m.second());
    }
  }
  // TODO Extend `option_to_pass` to be able to instantiate two or more pass objects.
  if (_options->query(Options::Algorithm::RemoveUnnecessaryReshape))
  {
    phase.emplace_back(std::make_unique<luci::RemoveUnnecessaryReshapePass>());
    phase.emplace_back(std::make_unique<luci::RemoveUnnecessaryReshapeNetPass>());
  }
  /* TRANSFORM DECLARATION END */
  ProgressReporter prog(g, logo::PhaseStrategy::Restart);
  logo::PhaseRunner<logo::PhaseStrategy::Restart> phase_runner{g};
  phase_runner.attach(&prog);
  phase_runner.run(phase);
}
References luci::CircleOptimizer::Options::CommonSubExpressionElimination, luci::CircleOptimizer::Options::ConvertNCHWToNHWC, luci::CircleOptimizer::Options::DecomposeHardSwishPass, luci::CircleOptimizer::Options::DecomposeSoftmaxPass, luci::CircleOptimizer::Options::ExpandBroadcastConst, luci::CircleOptimizer::Options::FoldAddV2, luci::CircleOptimizer::Options::FoldCast, luci::CircleOptimizer::Options::FoldDensify, luci::CircleOptimizer::Options::FoldDepthwiseConv2D, luci::CircleOptimizer::Options::FoldDequantize, luci::CircleOptimizer::Options::FoldFullyConnected, luci::CircleOptimizer::Options::FoldGather, luci::CircleOptimizer::Options::FoldMul, luci::CircleOptimizer::Options::FoldReshape, luci::CircleOptimizer::Options::FoldShape, luci::CircleOptimizer::Options::FoldSparseToDense, luci::CircleOptimizer::Options::FoldSqueeze, luci::CircleOptimizer::Options::ForwardReshapeToUnaryOp, luci::CircleOptimizer::Options::ForwardTransposeOp, luci::CircleOptimizer::Options::FuseActivationFunction, luci::CircleOptimizer::Options::FuseAddToFullyConnectedBias, luci::CircleOptimizer::Options::FuseAddWithConv, luci::CircleOptimizer::Options::FuseAddWithFullyConnected, luci::CircleOptimizer::Options::FuseAddWithTConv, luci::CircleOptimizer::Options::FuseBatchNormWithConv, luci::CircleOptimizer::Options::FuseBatchNormWithDwConv, luci::CircleOptimizer::Options::FuseBatchNormWithTConv, luci::CircleOptimizer::Options::FuseGelu, luci::CircleOptimizer::Options::FuseHorizontalFullyConnected, luci::CircleOptimizer::Options::FuseInstanceNorm, luci::CircleOptimizer::Options::FuseMeanWithMean, luci::CircleOptimizer::Options::FuseMulToFullyConnectedWeights, luci::CircleOptimizer::Options::FuseMulWithConv, luci::CircleOptimizer::Options::FuseMulWithDiv, luci::CircleOptimizer::Options::FuseMulWithFullyConnected, luci::CircleOptimizer::Options::FuseMulWithRmsNorm, luci::CircleOptimizer::Options::FusePreActivationBatchNorm, luci::CircleOptimizer::Options::FusePRelu, luci::CircleOptimizer::Options::FuseRmsNorm, luci::CircleOptimizer::Options::FuseRoPE, luci::CircleOptimizer::Options::FuseRsqrt, luci::CircleOptimizer::Options::FuseSliceWithTConv, luci::CircleOptimizer::Options::FuseTransposeWithMean, m, luci::CircleOptimizer::Options::MakeBatchNormGammaPositive, luci::must_cast(), luci::CircleOptimizer::Options::RemoveDuplicateConst, luci::CircleOptimizer::Options::RemoveFakeQuant, luci::CircleOptimizer::Options::RemoveGatherGuard, luci::CircleOptimizer::Options::RemoveQDQForMixedPrecisionOp, luci::CircleOptimizer::Options::RemoveQuantDequantSeq, luci::CircleOptimizer::Options::RemoveRedundantQuantize, luci::CircleOptimizer::Options::RemoveRedundantReshape, luci::CircleOptimizer::Options::RemoveRedundantTranspose, luci::CircleOptimizer::Options::RemoveUnnecessaryAdd, luci::CircleOptimizer::Options::RemoveUnnecessaryCast, luci::CircleOptimizer::Options::RemoveUnnecessaryDiv, luci::CircleOptimizer::Options::RemoveUnnecessaryMul, luci::CircleOptimizer::Options::RemoveUnnecessaryReshape, luci::CircleOptimizer::Options::RemoveUnnecessarySlice, luci::CircleOptimizer::Options::RemoveUnnecessarySplit, luci::CircleOptimizer::Options::RemoveUnnecessaryStridedSlice, luci::CircleOptimizer::Options::RemoveUnnecessaryTranspose, luci::CircleOptimizer::Options::ReplaceMulAddWithDepthwiseConv, luci::CircleOptimizer::Options::ReplaceNonConstFCWithBatchMatMul, luci::CircleOptimizer::Options::ReplaceSubWithAdd, luci::CircleOptimizer::Options::ReplaceWithFCGeluFC, luci::CircleOptimizer::Options::ResolveCustomOpAdd, luci::CircleOptimizer::Options::ResolveCustomOpBatchMatMul, luci::CircleOptimizer::Options::ResolveCustomOpMatMul, luci::CircleOptimizer::Options::ResolveCustomOpMaxPoolWithArgmax, luci::CircleOptimizer::Options::ResolveCustomOpSplitV, luci::CircleOptimizer::Options::ResolveFormerCustomOp, logo::Restart, luci::CircleOptimizer::Options::ShuffleWeightTo16x1Float32, luci::CircleOptimizer::Options::SubstituteExpandDimsToReshape, luci::CircleOptimizer::Options::SubstitutePackToReshape, luci::CircleOptimizer::Options::SubstitutePadV2ToPad, luci::CircleOptimizer::Options::SubstituteSplitVToSplit, luci::CircleOptimizer::Options::SubstituteSqueezeToReshape, luci::CircleOptimizer::Options::SubstituteStridedSliceToReshape, luci::CircleOptimizer::Options::SubstituteTransposeToReshape, luci::CircleOptimizer::Options::TransformMinMaxToRelu6Pass, luci::CircleOptimizer::Options::TransformMinReluToRelu6Pass, luci::CircleOptimizer::Options::TransformSqrtDivToRsqrtMul, luci::CircleOptimizer::Options::UnrollUnidirSeqLSTM, and luci::CircleOptimizer::Options::XpSepActFromTransposeConv.
optimize() [2/2]
void luci::CircleOptimizer::optimize (luci::Module * m) const
Definition at line 242 of file CircleOptimizer.cpp.
{
  luci::Phase phase;
  // Following passes are needed everytime when other passes create new node or modify some nodes.
  phase.emplace_back(std::make_unique<luci::CircleShapeInferencePass>());
  phase.emplace_back(std::make_unique<luci::CircleTypeInferencePass>());
  if (_options->query(Options::Algorithm::FuseBCQ))
  {
    phase.emplace_back(std::make_unique<FuseBCQPass>());
  }
  ModuleProgressReporter prog(m, logo::PhaseStrategy::Restart);
  PhaseRunner<logo::PhaseStrategy::Restart> phase_runner{m};
  phase_runner.attach(&prog);
  phase_runner.run(phase);
}
References luci::CircleOptimizer::Options::FuseBCQ, m, luci::must_cast(), and logo::Restart.
Referenced by entry().
options()
CircleOptimizer::Options * luci::CircleOptimizer::options (void)
Definition at line 217 of file CircleOptimizer.cpp.
{
  if (_options == nullptr)
  {
    _options = std::make_unique<OptimizeOptionsImpl>();
  }
  return _options.get();
}
Referenced by entry().
sparsify()
void luci::CircleOptimizer::sparsify (loco::Graph * g) const
Definition at line 431 of file CircleOptimizer.cpp.
{
  if (_options->query(Options::Algorithm::SparsifyTensorPass))
  {
    std::string tensor_name = _options->param(Options::AlgorithmParameters::Sparsify_tensor_name);
    std::string str_tarversal_order =
      _options->param(Options::AlgorithmParameters::Sparsify_traversal_order);
    std::string str_format = _options->param(Options::AlgorithmParameters::Sparsify_format);
    std::string str_block_size = _options->param(Options::AlgorithmParameters::Sparsify_block_size);
    std::string str_block_map = _options->param(Options::AlgorithmParameters::Sparsify_block_map);
    // traversal order
    std::vector<int32_t> traversal_order = pepper::csv_to_vector<int32_t>(str_tarversal_order);
    // format
    std::vector<DimensionType> format;
    std::istringstream is(str_format);
    for (char c; is >> c;)
    {
      assert(c != ',');
      if (c == 'd')
        format.push_back(DimensionType::DENSE);
      else if (c == 's')
        format.push_back(DimensionType::SPARSE_CSR);
      if (is.peek() == ',')
        is.ignore();
    }
    // block size
    std::vector<int32_t> block_size = pepper::csv_to_vector<int32_t>(str_block_size);
    // block map
    std::vector<int32_t> block_map = pepper::csv_to_vector<int32_t>(str_block_map);
    luci::SparsifyTensorPass sparsifier{tensor_name, traversal_order, format, block_size,
                                        block_map};
    sparsifier.run(g);
  }
}
References luci::DENSE, luci::must_cast(), luci::SparsifyTensorPass::run(), luci::SPARSE_CSR, luci::CircleOptimizer::Options::SparsifyTensorPass, and luci::tensor_name().
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/CircleOptimizer.h
compiler/luci/pass/src/CircleOptimizer.cpp