ONE - On-device Neural Engine: mir::ops::ResizeOp Class Reference
mir::ops::ResizeOp Class Reference
Resize operation scales are such that output = input * scale for each dimension and the number of dimensions matches.
#include <ResizeOp.h>
Public Types
enum class ResizeMethod { nearestNeighbor }
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Public Member Functions
ResizeOp (Output *arg, ResizeMethod mode, const std::vector< float > &scales)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
ResizeOp (Output *arg, ResizeMethod mode, const Shape &output_shape)
ResizeMethod getMode () const
const std::vector< float > & getScales () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Resize operation scales are such that output = input * scale for each dimension and the number of dimensions matches.
Definition at line 34 of file ResizeOp.h.
Member Enumeration Documentation
ResizeMethod
enum class mir::ops::ResizeOp::ResizeMethod strong
Enumerator
nearestNeighbor
Definition at line 37 of file ResizeOp.h.
  {
    nearestNeighbor, // TODO: BICUBIC and BILINEAR
  };
Constructor & Destructor Documentation
ResizeOp() [1/2]
mir::ops::ResizeOp::ResizeOp (Output * arg, ResizeMethod mode, const std::vector< float > & scales) inline
Definition at line 42 of file ResizeOp.h.
    : Operation(Type::resizeIm, {arg}), _mode(mode), _scales(scales)
  {
    // Infer output shape based on given scales.
    auto &input_shape = getInputShape(0);
    assert(input_shape.rank() == 4 && _scales.size() == 4);
    Shape output_shape(input_shape.rank());
    for (int32_t i = 0; i < input_shape.rank(); ++i)
    {
      output_shape.dim(i) = static_cast<int32_t>(lroundf(_scales.at(i) * input_shape.dim(i)));
    }
    setOutputType(0, {getInput(0)->getElementType(), output_shape});
  }
ResizeOp() [2/2]
mir::ops::ResizeOp::ResizeOp (Output * arg, ResizeMethod mode, const Shape & output_shape) inline
Definition at line 63 of file ResizeOp.h.
    : Operation(Type::resizeIm, {arg}), _mode(mode)
  {
    // Calculate scales based on given shape.
    auto &input_shape = getInputShape(0);
    assert(input_shape.rank() == 4 && output_shape.rank() == 4);
    setOutputType(0, {getInput(0)->getElementType(), output_shape});
    _scales = {1.0f, static_cast<float>(output_shape.dim(1)) / input_shape.dim(1),
               static_cast<float>(output_shape.dim(2)) / input_shape.dim(2), 1.0f};
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::ResizeOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 58 of file ResizeOp.h.
  {
    return new ResizeOp(inputs[0], _mode, getOutputShape(0));
  }
References mir::Operation::getOutputShape().
getMode()
ResizeMethod mir::ops::ResizeOp::getMode () const inline
Returns
The resize mode
Definition at line 75 of file ResizeOp.h.
{ return _mode; }
Referenced by mir_interpreter::MIRInterpreter::visit(), nnc::ModelAnalyzer::visit(), and mir::DotNodeBuilder::visit().
getScales()
const std::vector< float > & mir::ops::ResizeOp::getScales () const inline
Definition at line 77 of file ResizeOp.h.
{ return _scales; }
Referenced by mir_interpreter::MIRInterpreter::visit().
The documentation for this class was generated from the following file:
compiler/mir/include/mir/ops/ResizeOp.h