ONE - On-device Neural Engine: ANNConv2D Class Reference
ANNConv2D Class Reference
2D Convolution through Andoird NN API
#include <IR.h>
Public Member Functions
ANNConv2D ()
coco::Instr * loc (void) override
coco::Object * ofm (void) const
void ofm (coco::Object *o)
coco::Object * ifm (void) const
void ifm (coco::Object *o)
coco::Object * ker (void) const
void ker (coco::Object *o)
coco::Object * bias (void) const
void bias (coco::Object *o)
coco::Padding2D * pad (void)
const coco::Padding2D * pad (void) const
coco::Stride2D * stride (void)
const coco::Stride2D * stride (void) const
Public Member Functions inherited from coco::Instr
Instr ()=default
Instr (const Instr &)=delete
Instr (Instr &&)=delete
virtual ~Instr ()
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
const InstrIndex & index (void) const
Public Member Functions inherited from coco::DLinkedList< Child, Parent >::Node
Node ()
virtual ~Node ()
Parent * parent (void) const
Child * prev (void) const
Child * next (void) const
void insertBefore (Node *next)
void insertAfter (Node *prev)
void detach (void)
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Public Member Functions inherited from coco::Object::Producer
virtual ~Producer ()=default
Public Member Functions inherited from coco::Bag::Updater
virtual ~Updater ()=default
Public Member Functions inherited from coco::Locatable
virtual ~Locatable ()=default
virtual Instr * loc (void)=0
Public Member Functions inherited from coco::Object::Consumer
virtual ~Consumer ()=default
Public Member Functions inherited from coco::Bag::Reader
virtual ~Reader ()=default
Detailed Description
2D Convolution through Andoird NN API
TODO Support FusedActivation
Definition at line 27 of file IR.h.
Constructor & Destructor Documentation
ANNConv2D()
ANNConv2D::ANNConv2D () inline
Definition at line 30 of file IR.h.
              : _ofm{this}, _ifm{this}, _ker{this}, _bias{this}
  {
    // DO NOTHING
  }
Member Function Documentation
bias() [1/2]
void ANNConv2D::bias (coco::Object * o) inline
Definition at line 54 of file IR.h.
{ _bias.value(o); }
References coco::Use::value().
bias() [2/2]
coco::Object * ANNConv2D::bias (void) const inline
Currently, this "bias" is a Feature object with channel-wise layout
NOTE This design is subject to change
Definition at line 53 of file IR.h.
{ return _bias.value(); }
References coco::Use::value().
ifm() [1/2]
void ANNConv2D::ifm (coco::Object * o) inline
Definition at line 43 of file IR.h.
{ _ifm.value(o); }
References coco::Use::value().
ifm() [2/2]
coco::Object * ANNConv2D::ifm (void) const inline
Definition at line 42 of file IR.h.
{ return _ifm.value(); }
References coco::Use::value().
ker() [1/2]
void ANNConv2D::ker (coco::Object * o) inline
Definition at line 46 of file IR.h.
{ _ker.value(o); }
References coco::Use::value().
ker() [2/2]
coco::Object * ANNConv2D::ker (void) const inline
Definition at line 45 of file IR.h.
{ return _ker.value(); }
References coco::Use::value().
loc()
coco::Instr * ANNConv2D::loc (void) inline override virtual
Implements coco::Locatable.
Definition at line 36 of file IR.h.
{ return this; }
ofm() [1/2]
void ANNConv2D::ofm (coco::Object * o) inline
Definition at line 40 of file IR.h.
{ _ofm.value(o); }
References coco::Def::value().
ofm() [2/2]
coco::Object * ANNConv2D::ofm (void) const inline
Definition at line 39 of file IR.h.
{ return _ofm.value(); }
References coco::Def::value().
pad() [1/2]
coco::Padding2D * ANNConv2D::pad (void) inline
Definition at line 57 of file IR.h.
{ return &_pad; }
pad() [2/2]
const coco::Padding2D * ANNConv2D::pad (void) const inline
Definition at line 58 of file IR.h.
{ return &_pad; }
stride() [1/2]
coco::Stride2D * ANNConv2D::stride (void) inline
Definition at line 60 of file IR.h.
{ return &_stride; }
stride() [2/2]
const coco::Stride2D * ANNConv2D::stride (void) const inline
Definition at line 61 of file IR.h.
{ return &_stride; }
The documentation for this class was generated from the following file:
compiler/enco/core/src/coex/IR.h