ONE - On-device Neural Engine: luci_interpreter::CircleReferencingConstNodeBuilder Class Reference
luci_interpreter::CircleReferencingConstNodeBuilder Class Reference
Builder creates CircleCustom node with pointer to constants data from Tensor with buffer.
#include <CircleReferencingConst.h>
Public Member Functions
CircleNode * build (TensorIndex tensor_index, GraphBuilderContext *ctx) const final
CircleNode * build (TensorIndex tensor_index, GraphBuilderContext *ctx) const final
Public Member Functions inherited from luci::TypedNodeBuilder< NodeBuilderType::BUFFER >
NodeBuilderType builder_type () const final
virtual CircleNode * build (TensorIndex tensor_idx, GraphBuilderContext *context) const =0
virtual NodeBuilderType builder_type () const =0
Detailed Description
Builder creates CircleCustom node with pointer to constants data from Tensor with buffer.
Definition at line 31 of file CircleReferencingConst.h.
Member Function Documentation
build() [1/2]
CircleNode * luci_interpreter::CircleReferencingConstNodeBuilder::build (TensorIndex tensor_index, GraphBuilderContext * ctx) const final virtual
Implements luci::NodeBuilderBase.
Definition at line 37 of file CircleReferencingConst.cpp.
{
  assert(tensor_index >= 0);
  const auto graph = context->graph();
  const auto reader = context->reader();
  const auto tensors = reader->tensors();
  auto const const_tensor = tensors[tensor_index];
  assert(const_tensor != nullptr);
  if (const_tensor->is_variable())
  {
    // Create CircleVariable for variable
    return nullptr;
  }
  auto const buffer = wrap(reader->buffers()[const_tensor->buffer()]->data());
  auto const const_dims = wrap(const_tensor->shape()); // in NHWC
  if (const_dims.empty() && buffer.empty())
  {
    // unknown shape tensor and scalar tensor
    return nullptr;
  }
  // if tensor_index is used as output to some other operator, this is not a constant
  auto tensoroutputs = context->tensoroutputs();
  if (tensoroutputs->find(tensor_index))
  {
    // other operator output tensor
    return nullptr;
  }
  uint32_t num_elements = 1;
  for (uint32_t r = 0; r < const_dims.size(); ++r)
  {
    num_elements = num_elements * const_dims[r];
  }
  if (buffer.empty() && num_elements > 0)
  {
    // normal empty tensor
    return nullptr;
  }
  // create CircleReferencingConst
  auto custom_node = graph->nodes()->create<CircleCustom>(0, 1);
  {
    custom_node->custom_code("CircleReferencingConst");
    copy_tensor_attributes(const_tensor, custom_node);
    custom_node->shape_status(luci::ShapeStatus::VALID);
    // custom options stores size of buffer and pointer's value to buffer's data
    {
      std::vector<uint8_t> custom_options(sizeof(ConstDataReference));
      {
        auto &const_data_ref = *reinterpret_cast<ConstDataReference *>(custom_options.data());
        const_data_ref = {buffer.data(), buffer.size()};
      }
      custom_node->custom_options(custom_options);
    }
  }
  // Output of CircleCustom node presented with CircleConstNode
  auto out_node = graph->nodes()->create<CircleCustomOut>();
  {
    out_node->index(0);
    out_node->input(custom_node);
    copy_tensor_attributes(const_tensor, out_node);
    out_node->shape_status(luci::ShapeStatus::VALID);
  }
  return out_node;
}
References luci::copy_tensor_attributes(), luci::CircleCustom::custom_code(), luci::GraphBuilderContext::graph(), luci::CircleCustomOut::index(), luci::GraphBuilderContext::reader(), luci::GraphBuilderContext::tensoroutputs(), luci::CircleReader::tensors(), luci::VALID, and luci::wrap().
build() [2/2]
CircleNode * luci_interpreter::CircleReferencingConstNodeBuilder::build (TensorIndex tensor_index, GraphBuilderContext * ctx) const final virtual
Implements luci::NodeBuilderBase.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/import/Nodes/CircleReferencingConst.h
onert-micro/luci-interpreter/src/import/Nodes/CircleReferencingConst.h
compiler/luci-interpreter/src/import/Nodes/CircleReferencingConst.cpp
onert-micro/luci-interpreter/src/import/Nodes/CircleReferencingConst.cpp