ONE - On-device Neural Engine: onert_micro::core::OMDataContext< T, Mixins > Class Template Reference
onert_micro::core::OMDataContext< T, Mixins > Class Template Reference
#include <OMRuntimeData.h>
Public Member Functions
template<class RuntimeKernel >
OMDataContext (RuntimeKernel &rt_kernel)
virtual ~OMDataContext ()=default
auto & Input ()
auto & Output ()
Protected Attributes
OMInputContext< T > _in_ctx
OMOutputContext< T > _out_ctx
Detailed Description
template<class T, class ... Mixins>
class onert_micro::core::OMDataContext< T, Mixins >
Definition at line 132 of file OMRuntimeData.h.
Constructor & Destructor Documentation
OMDataContext()
template<class T , class ... Mixins> template<class RuntimeKernel > onert_micro::core::OMDataContext< T, Mixins >::OMDataContext (RuntimeKernel & rt_kernel) inline explicit
Definition at line 140 of file OMRuntimeData.h.
    : Mixins(rt_kernel)...
    , _in_ctx(rt_kernel)
    , _out_ctx(rt_kernel)
  {}
~OMDataContext()
template<class T , class ... Mixins> virtual onert_micro::core::OMDataContext< T, Mixins >::~OMDataContext () virtual default
Member Function Documentation
Input()
template<class T , class ... Mixins> auto & onert_micro::core::OMDataContext< T, Mixins >::Input () inline
Definition at line 149 of file OMRuntimeData.h.
  {
    return _in_ctx;
  }
References onert_micro::core::OMDataContext< T, Mixins >::_in_ctx.
Referenced by onert_micro::execute::pal::Reduce(), and onert_micro::execute::pal::ReduceGeneric().
Output()
template<class T , class ... Mixins> auto & onert_micro::core::OMDataContext< T, Mixins >::Output () inline
Definition at line 154 of file OMRuntimeData.h.
  {
    return _out_ctx;
  }
References onert_micro::core::OMDataContext< T, Mixins >::_out_ctx.
Referenced by onert_micro::execute::pal::Reduce(), and onert_micro::execute::pal::ReduceGeneric().
Field Documentation
_in_ctx
template<class T , class ... Mixins> OMInputContext<T> onert_micro::core::OMDataContext< T, Mixins >::_in_ctx protected
Definition at line 135 of file OMRuntimeData.h.
Referenced by onert_micro::core::OMDataContext< T, Mixins >::Input().
_out_ctx
template<class T , class ... Mixins> OMOutputContext<T> onert_micro::core::OMDataContext< T, Mixins >::_out_ctx protected
Definition at line 136 of file OMRuntimeData.h.
Referenced by onert_micro::core::OMDataContext< T, Mixins >::Output().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMRuntimeData.h