var classluci__interpreter_1_1test__kernel_1_1_neg_test_data_invalid_size_shape_dimensions_float_resize_bilinear_kernel =
[
    [ "NegTestDataInvalidSizeShapeDimensionsFloatResizeBilinearKernel", "classluci__interpreter_1_1test__kernel_1_1_neg_test_data_invalid_size_shape_dimensions_float_resize_bilinear_kernel.html#a6858a8b754b59e8dd0a27406b0f2c263", null ],
    [ "~NegTestDataInvalidSizeShapeDimensionsFloatResizeBilinearKernel", "classluci__interpreter_1_1test__kernel_1_1_neg_test_data_invalid_size_shape_dimensions_float_resize_bilinear_kernel.html#aae222d59336a5aa80d361ad123eb8cb4", null ],
    [ "get_model_ptr", "classluci__interpreter_1_1test__kernel_1_1_neg_test_data_invalid_size_shape_dimensions_float_resize_bilinear_kernel.html#a8f3cf0c4c36fadd7868fb65f4a1f226e", null ],
    [ "_test_kernel_model_circle", "classluci__interpreter_1_1test__kernel_1_1_neg_test_data_invalid_size_shape_dimensions_float_resize_bilinear_kernel.html#a6f4bb3daf1582cab91cca54f5b6ec000", null ]
];