ONE - On-device Neural Engine: ndarray::Shape Class Reference
ndarray::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape (size_t rank) noexcept
Shape (std::initializer_list< size_t > list) noexcept
size_t dim (int i) const noexcept
size_t & dim (int i) noexcept
size_t element_count () const noexcept
size_t rank () const noexcept
Detailed Description
Definition at line 29 of file Shape.h.
Constructor & Destructor Documentation
Shape() [1/2]
ndarray::Shape::Shape (size_t rank) inline explicit noexcept
Definition at line 34 of file Shape.h.
                                       : _dims{}, _rank(rank)
  {
    std::fill(_dims.begin(), _dims.end(), 0);
  }
Shape() [2/2]
ndarray::Shape::Shape (std::initializer_list< size_t > list) inline noexcept
Definition at line 39 of file Shape.h.
                                                   : _dims{}, _rank(list.size())
  {
    std::copy(list.begin(), list.end(), _dims.begin());
  }
Member Function Documentation
dim() [1/2]
size_t ndarray::Shape::dim (int i) const inline noexcept
Definition at line 44 of file Shape.h.
{ return _dims.at(i); }
Referenced by element_count(), gather_array(), ndarray::Array< T >::slice(), and onert::backend::cpu::ops::toArray().
dim() [2/2]
size_t & ndarray::Shape::dim (int i) inline noexcept
Definition at line 46 of file Shape.h.
{ return _dims.at(i); }
element_count()
size_t ndarray::Shape::element_count () const inline noexcept
Definition at line 48 of file Shape.h.
  {
    uint32_t res = 1;
    for (size_t i = 0; i < rank(); ++i)
      res *= dim(i);
    assert(res <= 0xffffffff);
    return res;
  }
References dim(), and rank().
Referenced by ndarray::array_cast(), and ndarray::Array< T >::flat().
rank()
size_t ndarray::Shape::rank () const inline noexcept
Definition at line 57 of file Shape.h.
{ return _rank; }
Referenced by element_count(), gather_array(), and ndarray::Array< T >::slice().
The documentation for this class was generated from the following file:
runtime/libs/ndarray/include/ndarray/Shape.h