ONE - On-device Neural Engine: locoex::TFLMean Class Reference
locoex::TFLMean Class Reference final
#include <TFLNodes.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * reduction_indices (void) const
void reduction_indices (loco::Node *node)
bool keep_dims (void) const
void keep_dims (bool keep_dims)
Public Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::MEAN >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >
loco::Use * at (unsigned n) const
Detailed Description
Definition at line 353 of file TFLNodes.h.
Member Function Documentation
input() [1/2]
void locoex::TFLMean::input (loco::Node * node) inline
Definition at line 357 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * locoex::TFLMean::input (void) const inline
Definition at line 356 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >::at(), and loco::Use::node().
keep_dims() [1/2]
void locoex::TFLMean::keep_dims (bool keep_dims) inline
Definition at line 364 of file TFLNodes.h.
{ _keep_dims = keep_dims; }
References keep_dims().
Referenced by keep_dims().
keep_dims() [2/2]
bool locoex::TFLMean::keep_dims (void) const inline
Definition at line 363 of file TFLNodes.h.
{ return _keep_dims; }
reduction_indices() [1/2]
void locoex::TFLMean::reduction_indices (loco::Node * node) inline
Definition at line 360 of file TFLNodes.h.
{ at(1)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >::at(), and loco::Use::node().
reduction_indices() [2/2]
loco::Node * locoex::TFLMean::reduction_indices (void) const inline
Definition at line 359 of file TFLNodes.h.
{ return at(1)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::MEAN > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h