ONE - On-device Neural Engine: moco::GraphBuilderRegistry Class Reference
moco::GraphBuilderRegistry Class Reference final
Class to return graph builder for TF nodes.
#include <GraphBuilderRegistry.h>
Public Member Functions
GraphBuilderRegistry ()
GraphBuilderRegistry (const GraphBuilderSource *parent)
const GraphBuilder * lookup (const std::string &op) const final
Returns registered GraphBuilder pointer for operator or nullptr if not registered.
void add (const std::string op, std::unique_ptr< GraphBuilder > &&builder)
Public Member Functions inherited from moco::GraphBuilderSource
virtual ~GraphBuilderSource ()=default
virtual const GraphBuilder * lookup (const std::string &op) const =0
Returns registered GraphBuilder pointer for operator (nullptr if not present)
Static Public Member Functions
static GraphBuilderRegistry & get ()
Detailed Description
Class to return graph builder for TF nodes.
Definition at line 42 of file GraphBuilderRegistry.h.
Constructor & Destructor Documentation
GraphBuilderRegistry() [1/2]
moco::GraphBuilderRegistry::GraphBuilderRegistry ()
Definition at line 25 of file GraphBuilderRegistry.cpp.
{
  add("Add", std::make_unique<AddGraphBuilder>());
  add("AvgPool", std::make_unique<AvgPoolGraphBuilder>());
  add("BiasAdd", std::make_unique<BiasAddGraphBuilder>());
  add("ConcatV2", std::make_unique<ConcatV2GraphBuilder>());
  add("Const", std::make_unique<ConstGraphBuilder>());
  add("Conv2D", std::make_unique<Conv2DGraphBuilder>());
  add("Conv2DBackpropInput", std::make_unique<Conv2DBackpropInputGraphBuilder>());
  add("DepthwiseConv2dNative", std::make_unique<DepthwiseConv2dNativeGraphBuilder>());
  add("FakeQuantWithMinMaxVars", std::make_unique<FakeQuantWithMinMaxVarsGraphBuilder>());
  add("FusedBatchNorm", std::make_unique<FusedBatchNormGraphBuilder>());
  add("Identity", std::make_unique<IdentityGraphBuilder>());
  add("Maximum", std::make_unique<MaximumGraphBuilder>());
  add("MaxPool", std::make_unique<MaxPoolGraphBuilder>());
  add("Mean", std::make_unique<MeanGraphBuilder>());
  add("Mul", std::make_unique<MulGraphBuilder>());
  add("Pack", std::make_unique<PackGraphBuilder>());
  add("Pad", std::make_unique<PadGraphBuilder>());
  add("Placeholder", std::make_unique<PlaceholderGraphBuilder>());
  add("RealDiv", std::make_unique<RealDivGraphBuilder>());
  add("Relu", std::make_unique<ReluGraphBuilder>());
  add("Relu6", std::make_unique<Relu6GraphBuilder>());
  add("Reshape", std::make_unique<ReshapeGraphBuilder>());
  add("Rsqrt", std::make_unique<RsqrtGraphBuilder>());
  add("Shape", std::make_unique<ShapeGraphBuilder>());
  add("Softmax", std::make_unique<SoftmaxGraphBuilder>());
  add("Sqrt", std::make_unique<SqrtGraphBuilder>());
  add("SquaredDifference", std::make_unique<SquaredDifferenceGraphBuilder>());
  add("Squeeze", std::make_unique<SqueezeGraphBuilder>());
  add("StopGradient", std::make_unique<StopGradientGraphBuilder>());
  add("StridedSlice", std::make_unique<StridedSliceGraphBuilder>());
  add("Sub", std::make_unique<SubGraphBuilder>());
  add("Tanh", std::make_unique<TanhGraphBuilder>());
  // Virtual node like `TFPush` need not to be added here
}
References add().
GraphBuilderRegistry() [2/2]
moco::GraphBuilderRegistry::GraphBuilderRegistry (const GraphBuilderSource * parent) inline
Definition at line 48 of file GraphBuilderRegistry.h.
                                                         : _parent{parent}
  {
    // DO NOTHING
  }
Member Function Documentation
add()
void moco::GraphBuilderRegistry::add (const std::string op, std::unique_ptr< GraphBuilder > && builder) inline
Definition at line 73 of file GraphBuilderRegistry.h.
  {
    _builder_map[op] = std::move(builder);
  }
Referenced by GraphBuilderRegistry().
get()
static GraphBuilderRegistry & moco::GraphBuilderRegistry::get () inline static
Definition at line 66 of file GraphBuilderRegistry.h.
  {
    static GraphBuilderRegistry me;
    return me;
  }
Referenced by moco::Importer::import().
lookup()
const GraphBuilder * moco::GraphBuilderRegistry::lookup (const std::string & op) const inline final virtual
Returns registered GraphBuilder pointer for operator or nullptr if not registered.
Implements moco::GraphBuilderSource.
Definition at line 58 of file GraphBuilderRegistry.h.
  {
    if (_builder_map.find(op) == _builder_map.end())
      return (_parent == nullptr) ? nullptr : _parent->lookup(op);
    return _builder_map.at(op).get();
  }
References moco::GraphBuilderSource::lookup().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/GraphBuilderRegistry.h
compiler/moco/import/src/GraphBuilderRegistry.cpp