ONE - On-device Neural Engine: nncc::core::ADT::kernel::IndexEnumerator Class Reference
nncc::core::ADT::kernel::IndexEnumerator Class Reference
#include <IndexEnumerator.h>
Public Member Functions
IndexEnumerator (const Shape &shape)
IndexEnumerator (IndexEnumerator &&)=delete
IndexEnumerator (const IndexEnumerator &)=delete
bool valid (void) const
uint32_t count (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
void advance (void)
Detailed Description
Definition at line 31 of file IndexEnumerator.h.
Constructor & Destructor Documentation
IndexEnumerator() [1/3]
nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator (const Shape & shape) explicit
Definition at line 31 of file IndexEnumerator.cpp.
                                                   : _cursor(0)
{
  _max[0] = shape.width();
  _max[1] = shape.height();
  _max[2] = shape.depth();
  _max[3] = shape.count();
  std::fill(_cur, _cur + 4, 0);
  // NOTE Null dimension should NOT exist
  assert(std::find(_max, _max + 4, 0) == (_max + 4));
}
References nncc::core::ADT::kernel::Shape::count(), nncc::core::ADT::kernel::Shape::depth(), nncc::core::ADT::kernel::Shape::height(), and nncc::core::ADT::kernel::Shape::width().
IndexEnumerator() [2/3]
nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator (IndexEnumerator &&) delete
IndexEnumerator() [3/3]
nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator (const IndexEnumerator &) delete
Member Function Documentation
advance()
void nncc::core::ADT::kernel::IndexEnumerator::advance (void)
Definition at line 51 of file IndexEnumerator.cpp.
{
  while (_cursor < 4)
  {
    if (_cur[_cursor] + 1 < _max[_cursor])
    {
      break;
    }
    ++_cursor;
  }
  if (_cursor == 4)
  {
    return;
  }
  // Increment index
  _cur[_cursor] += 1;
  // Reset indices for lower dimensions
  for (uint32_t head = 0; head < _cursor; ++head)
  {
    _cur[head] = 0;
  }
  // Reset cursor
  _cursor = 0;
}
References head().
count()
uint32_t nncc::core::ADT::kernel::IndexEnumerator::count (void) const
Definition at line 46 of file IndexEnumerator.cpp.
{ return _cur[3]; }
depth()
uint32_t nncc::core::ADT::kernel::IndexEnumerator::depth (void) const
Definition at line 47 of file IndexEnumerator.cpp.
{ return _cur[2]; }
height()
uint32_t nncc::core::ADT::kernel::IndexEnumerator::height (void) const
Definition at line 48 of file IndexEnumerator.cpp.
{ return _cur[1]; }
valid()
bool nncc::core::ADT::kernel::IndexEnumerator::valid (void) const
Definition at line 44 of file IndexEnumerator.cpp.
{ return _cursor < 4; }
width()
uint32_t nncc::core::ADT::kernel::IndexEnumerator::width (void) const
Definition at line 49 of file IndexEnumerator.cpp.
{ return _cur[0]; }
The documentation for this class was generated from the following files:
compiler/angkor/include/nncc/core/ADT/kernel/IndexEnumerator.h
compiler/angkor/src/ADT/kernel/IndexEnumerator.cpp