ONE - On-device Neural Engine: HD5ExportAction Class Reference
HD5ExportAction Class Reference final
Public Member Functions
HD5ExportAction (const std::string &path)
void run (TensorContext &ctx) override
Public Member Functions inherited from nnkit::Action
virtual ~Action ()=default
virtual void run (TensorContext &ctx)=0
Detailed Description
Definition at line 28 of file Export.cpp.
Constructor & Destructor Documentation
HD5ExportAction()
HD5ExportAction::HD5ExportAction (const std::string & path) inline
Definition at line 31 of file Export.cpp.
                                         : _file{path, H5F_ACC_TRUNC}
  {
    _value_grp = _file.createGroup(value_grpname());
    _name_grp = _file.createGroup(name_grpname());
  }
References name_grpname(), and value_grpname().
Member Function Documentation
run()
void HD5ExportAction::run (TensorContext & ctx) inline override virtual
Implements nnkit::Action.
Definition at line 38 of file Export.cpp.
  {
    for (uint32_t n = 0; n < ctx.size(); ++n)
    {
      using nncc::core::ADT::tensor::Reader;
      // TODO Support other data types
      auto fn = [this](const TensorContext &ctx, uint32_t n, const Reader<float> &t) {
        const auto name = ctx.name(n);
        const auto shape = ctx.shape(n);
        const auto rank = shape.rank();
        hsize_t dims[rank];
        for (uint32_t axis = 0; axis < rank; ++axis)
        {
          dims[axis] = shape.dim(axis);
        }
        H5::DataSpace dataspace(rank, dims);
        auto dataset =
          _value_grp.createDataSet(value_filename(n), H5::PredType::IEEE_F32BE, dataspace);
        float *data = new float[nncc::core::ADT::tensor::num_elements(shape)];
        using nncc::core::ADT::tensor::Index;
        using nncc::core::ADT::tensor::IndexEnumerator;
        using nncc::core::ADT::tensor::LexicalLayout;
        LexicalLayout layout{};
        for (IndexEnumerator e{shape}; e.valid(); e.advance())
        {
          auto i = e.current();
          data[layout.offset(shape, i)] = t.at(i);
        }
        dataset.write(data, H5::PredType::NATIVE_FLOAT);
        delete[] data;
        // Record name
        {
          H5::DataSpace name_dataspace(H5S_SCALAR);
          H5::StrType name_datatype(H5::PredType::C_S1, name.size());
          auto name_attr =
            _name_grp.createAttribute(value_filename(n), name_datatype, name_dataspace);
          name_attr.write(name_datatype, name);
        }
      };
      ctx.getConstFloatTensor(n, fn);
    }
  }
References nnkit::TensorContext::getConstFloatTensor(), nnkit::TensorContext::name(), nncc::core::ADT::tensor::num_elements(), nncc::core::ADT::tensor::Shape::rank(), nnkit::TensorContext::shape(), nnkit::TensorContext::size(), and value_filename().
The documentation for this class was generated from the following file:
compiler/nnkit/actions/HDF5/Export.cpp