ONE - On-device Neural Engine: hermes::Source Class Reference
hermes::Source Class Reference
Message Source.
#include <Source.h>
Data Structures
struct Registry
Public Types
using Setting = SourceSetting
Public Member Functions
bool check (const Severity &s) const
Check whether a message with a given severity is acceptable or not.
virtual void reload (const Config *)
Update Source with a given configuration.
std::unique_ptr< MessageBuffer > buffer (const Severity &) const
Protected Member Functions
Source ()
virtual ~Source ()
void activate (Registry *, MessageBus *)
void deactivate (void)
Setting & setting (void)
Detailed Description
Message Source.
"Source" is the actual interface for users. "Source" accepts log messages from client.
Definition at line 34 of file Source.h.
Member Typedef Documentation
Setting
using hermes::Source::Setting = SourceSetting
Definition at line 48 of file Source.h.
Constructor & Destructor Documentation
Source()
hermes::Source::Source () protected
Definition at line 25 of file Source.cpp.
{
  assert(_reg == nullptr);
  assert(_bus == nullptr);
}
~Source()
hermes::Source::~Source () protected virtual
Definition at line 31 of file Source.cpp.
{
  assert(_bus == nullptr);
  assert(_reg == nullptr);
}
Member Function Documentation
activate()
void hermes::Source::activate (Registry * reg, MessageBus * bus) protected
Definition at line 37 of file Source.cpp.
{
  assert((_reg == nullptr) && (_bus == nullptr));
  _reg = reg;
  _bus = bus;
  _reg->attach(this);
  assert((_bus != nullptr) && (_reg != nullptr));
}
References hermes::Source::Registry::attach().
Referenced by circlechef::Logger::Logger(), exo::Logger::Logger(), luci::Logger::Logger(), moco::Logger::Logger(), and tflchef::Logger::Logger().
buffer()
std::unique_ptr< MessageBuffer > hermes::Source::buffer (const Severity & severity) const
Definition at line 63 of file Source.cpp.
{
  return std::make_unique<MessageBuffer>(_bus, severity.category());
}
References hermes::Severity::category().
check()
bool hermes::Source::check (const Severity & s) const inline
Check whether a message with a given severity is acceptable or not.
NOTE This routine is performance critical as app always invokes this routine (even when logging is disabled).
Definition at line 70 of file Source.h.
  {
    return static_cast<int32_t>(s.level()) < _setting.limit(s.category()).level();
  }
References hermes::SourceSetting::limit().
deactivate()
void hermes::Source::deactivate (void) protected
Definition at line 49 of file Source.cpp.
{
  assert((_bus != nullptr) && (_reg != nullptr));
  _reg->detach(this);
  _bus = nullptr;
  _reg = nullptr;
  assert((_reg == nullptr) && (_bus == nullptr));
}
References hermes::Source::Registry::detach().
Referenced by circlechef::Logger::~Logger(), exo::Logger::~Logger(), luci::Logger::~Logger(), moco::Logger::~Logger(), and tflchef::Logger::~Logger().
reload()
void hermes::Source::reload (const Config * c) virtual
Update Source with a given configuration.
WARNING Do NOT invoke this manually.
TODO Remove virtual after migration
Definition at line 61 of file Source.cpp.
{ c->configure(this, _setting); }
References hermes::Config::configure().
setting()
Setting & hermes::Source::setting (void) inline protected
Definition at line 60 of file Source.h.
{ return _setting; }
The documentation for this class was generated from the following files:
compiler/hermes/include/hermes/core/Source.h
compiler/hermes/src/core/Source.cpp