ONE - On-device Neural Engine: luci::CircleNodeExecutionPlan Class Reference
luci::CircleNodeExecutionPlan Class Reference
#include <CircleNodeExecutionPlan.h>
Public Member Functions
CircleNodeExecutionPlan ()=delete
CircleNodeExecutionPlan (uint32_t order_in_plan, std::vector< uint32_t > offsets)
uint32_t order_in_plan (void) const
void order_in_plan (const uint32_t &order_in_plan)
std::vector< uint32_t > offsets (void) const
void offsets (const std::vector< uint32_t > &offsets)
Detailed Description
Definition at line 27 of file CircleNodeExecutionPlan.h.
Constructor & Destructor Documentation
CircleNodeExecutionPlan() [1/2]
luci::CircleNodeExecutionPlan::CircleNodeExecutionPlan () delete
CircleNodeExecutionPlan() [2/2]
luci::CircleNodeExecutionPlan::CircleNodeExecutionPlan (uint32_t order_in_plan, std::vector< uint32_t > offsets) inline
Definition at line 32 of file CircleNodeExecutionPlan.h.
  {
    _order_in_plan = order_in_plan;
    _offsets = std::move(offsets);
  }
References offsets(), and order_in_plan().
Member Function Documentation
offsets() [1/2]
void luci::CircleNodeExecutionPlan::offsets (const std::vector< uint32_t > & offsets) inline
Definition at line 42 of file CircleNodeExecutionPlan.h.
{ _offsets = offsets; }
References offsets().
Referenced by offsets().
offsets() [2/2]
std::vector< uint32_t > luci::CircleNodeExecutionPlan::offsets (void) const inline
Definition at line 41 of file CircleNodeExecutionPlan.h.
{ return _offsets; }
Referenced by CircleNodeExecutionPlan().
order_in_plan() [1/2]
void luci::CircleNodeExecutionPlan::order_in_plan (const uint32_t & order_in_plan) inline
Definition at line 39 of file CircleNodeExecutionPlan.h.
{ _order_in_plan = order_in_plan; }
References order_in_plan().
Referenced by order_in_plan().
order_in_plan() [2/2]
uint32_t luci::CircleNodeExecutionPlan::order_in_plan (void) const inline
Definition at line 38 of file CircleNodeExecutionPlan.h.
{ return _order_in_plan; }
Referenced by CircleNodeExecutionPlan(), and luci_interpreter::GraphLoader::loadOperators().
The documentation for this class was generated from the following file:
compiler/luci/plan/include/luci/Plan/CircleNodeExecutionPlan.h