ONE - On-device Neural Engine: onert::backend::acl_cl::ConstantInitializer Class Reference
onert::backend::acl_cl::ConstantInitializer Class Reference
#include <ConstantInitializer.h>
Public Member Functions
ConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void visit (const ir::operation::EmbeddingLookup &) final
void visit (const ir::operation::Gather &) final
void visit (const ir::operation::HashtableLookup &) final
void visit (const ir::operation::SpaceToBatchND &) final
void visit (const ir::operation::Reverse &) final
Public Member Functions inherited from onert::backend::acl_common::AclConstantInitializer
void run ()
AclConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void registerDefaultInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerCopyInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerPermuteInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void setLayout (ir::Layout layout)
bool exist (const ir::OperandIndex &ind)
void visit (const ir::operation::BatchToSpaceND &) override
void visit (const ir::operation::Conv2D &) override
void visit (const ir::operation::DepthwiseConv2D &) override
void visit (const ir::operation::FullyConnected &) override
void visit (const ir::operation::LSTM &) override
void visit (const ir::operation::RNN &) override
void visit (const ir::operation::TransposeConv &) override
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Public Types inherited from onert::backend::acl_common::AclConstantInitializer
using Initializer = std::function< void(const ir::Operand &, backend::ITensor &)>
Protected Member Functions inherited from onert::backend::acl_common::AclConstantInitializer
void copyInputInitialize (const ir::Operation &node, uint32_t index)
void permuteInputInitialize (const ir::Operation &node, uint32_t index)
Protected Attributes inherited from onert::backend::acl_common::AclConstantInitializer
const ir::Operands & _operands
std::shared_ptr< ITensorRegistry > _tensor_reg
std::unordered_map< ir::OperandIndex, Initializer > _init_map
ir::Layout _current_layout
Detailed Description
Definition at line 29 of file ConstantInitializer.h.
Constructor & Destructor Documentation
ConstantInitializer()
onert::backend::acl_cl::ConstantInitializer::ConstantInitializer (const ir::Operands & operands, const std::shared_ptr< ITensorRegistry > & tensor_reg)
Definition at line 31 of file ConstantInitializer.cc.
  : acl_common::AclConstantInitializer{operands, tensor_reg}
{
  // DO NOTHING
}
Member Function Documentation
visit() [1/5]
void onert::backend::acl_cl::ConstantInitializer::visit (const ir::operation::EmbeddingLookup & node) final
Definition at line 38 of file ConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::EmbeddingLookup::LOOKUPS);
}
References onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), and onert::ir::operation::EmbeddingLookup::LOOKUPS.
visit() [2/5]
void onert::backend::acl_cl::ConstantInitializer::visit (const ir::operation::Gather & node) final
Definition at line 43 of file ConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::Gather::INDICES);
}
References onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), and onert::ir::operation::Gather::INDICES.
visit() [3/5]
void onert::backend::acl_cl::ConstantInitializer::visit (const ir::operation::HashtableLookup & node) final
Definition at line 48 of file ConstantInitializer.cc.
{
  copyInputInitialize(node, ir::operation::HashtableLookup::LOOKUPS);
  copyInputInitialize(node, ir::operation::HashtableLookup::KEYS);
}
References onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), onert::ir::operation::HashtableLookup::KEYS, and onert::ir::operation::HashtableLookup::LOOKUPS.
visit() [4/5]
void onert::backend::acl_cl::ConstantInitializer::visit (const ir::operation::Reverse & node) final
Definition at line 90 of file ConstantInitializer.cc.
{
  const auto &output_index = node.getOutputs().at(0);
  const auto &input_index = node.getInputs().at(ir::operation::Reverse::Input::INPUT);
  const auto &input_obj = _operands.at(input_index);
  const auto &axis_index = node.getInputs().at(ir::operation::Reverse::Input::AXIS);
  const auto &axis_obj = _operands.at(axis_index);
  const auto ifm_rank = input_obj.shape().rank();
  const auto frontend_layout = this->_current_layout;
  auto output_tensor = this->_tensor_reg->getITensor(output_index);
  const auto backend_layout = output_tensor->layout();
  if (axis_obj.isConstant())
  {
    _init_map[axis_index] = [ifm_rank, frontend_layout, backend_layout](const ir::Operand &operand,
                                                                        backend::ITensor &obj) {
      assert(operand.data());
      const auto axis_value = *(reinterpret_cast<const int32_t *>(operand.data()->base()));
      int32_t axis_tmp = axis_value;
      if (axis_tmp < 0)
      {
        axis_tmp = axis_tmp + ifm_rank;
      }
      auto axis =
        acl_common::ToARMComputeAxis(ifm_rank, axis_tmp, frontend_layout, backend_layout).value();
      obj.access([&](ITensor &tensor) {
        int32_t *into = reinterpret_cast<int32_t *>(tensor.buffer());
        *into = (int32_t)axis;
      });
    };
  }
}
References onert::backend::acl_common::AclConstantInitializer::_current_layout, onert::backend::acl_common::AclConstantInitializer::_init_map, onert::backend::acl_common::AclConstantInitializer::_operands, onert::backend::acl_common::AclConstantInitializer::_tensor_reg, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::Reverse::AXIS, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Reverse::INPUT, onert::backend::acl_common::ToARMComputeAxis(), and onert::backend::acl_common::ARMComputeAxis::value().
visit() [5/5]
void onert::backend::acl_cl::ConstantInitializer::visit (const ir::operation::SpaceToBatchND & node) final
Definition at line 54 of file ConstantInitializer.cc.
{
  const auto &block_size_index = node.getInputs().at(ir::operation::SpaceToBatchND::BLOCK_SIZE);
  const auto &block_size_obj = _operands.at(block_size_index);
  if (block_size_obj.isConstant())
  {
    _init_map[block_size_index] = acl_common::initReverseOrder<int32_t>;
  }
  const auto &paddings_index = node.getInputs().at(ir::operation::SpaceToBatchND::PADDINGS);
  const auto &paddings_obj = _operands.at(paddings_index);
  if (paddings_obj.isConstant())
  {
    _init_map[paddings_index] = [](const ir::Operand &model_obj, backend::ITensor &obj) {
      assert(model_obj.data());
      const auto &shape = model_obj.shape();
      const auto base = reinterpret_cast<const int32_t *>(model_obj.data()->base());
      assert(model_obj.shape().rank() == 2);
      assert(obj.getShape().dim(0) == 2);
      obj.access([&](ITensor &tensor) {
        for (auto i = 0; i < shape.dim(0); ++i)
        {
          for (auto j = 0; j < shape.dim(1); ++j)
          {
            const int32_t value = base[i * 2 + j];
            int32_t *into = reinterpret_cast<int32_t *>(
              tensor.buffer() + tensor.calcOffset({shape.dim(0) - i - 1, j}));
            *into = value;
          }
        }
      });
    };
  }
}
References onert::backend::acl_common::AclConstantInitializer::_init_map, onert::backend::acl_common::AclConstantInitializer::_operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::SpaceToBatchND::BLOCK_SIZE, onert::ir::Operand::data(), onert::ir::Operation::getInputs(), onert::ir::operation::SpaceToBatchND::PADDINGS, and onert::ir::Operand::shape().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/ConstantInitializer.h
runtime/onert/backend/acl_cl/ConstantInitializer.cc