ONE - On-device Neural Engine: luci_interpreter::kernels::GRU Class Reference
luci_interpreter::kernels::GRU Class Reference
#include <GRU.h>
Public Member Functions
GRU (const Tensor *input, const Tensor *hidden_hidden, const Tensor *hidden_hidden_bias, const Tensor *hidden_input, const Tensor *hidden_input_bias, const Tensor *state, Tensor *output, const GRUParams &params)
const Tensor * input () const
const Tensor * hidden_hidden () const
const Tensor * hidden_hidden_bias () const
const Tensor * hidden_input () const
const Tensor * hidden_input_bias () const
const Tensor * state () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< GRUParams >
const GRUParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< GRUParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const GRUParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< GRUParams >
const GRUParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file GRU.h.
Constructor & Destructor Documentation
GRU()
luci_interpreter::kernels::GRU::GRU (const Tensor * input, const Tensor * hidden_hidden, const Tensor * hidden_hidden_bias, const Tensor * hidden_input, const Tensor * hidden_input_bias, const Tensor * state, Tensor * output, const GRUParams & params)
Definition at line 28 of file GRU.cpp.
  : KernelWithParams<GRUParams>(
      {input, hidden_hidden, hidden_hidden_bias, hidden_input, hidden_input_bias, state}, {output},
      params)
{
}
References hidden_hidden(), hidden_hidden_bias(), hidden_input(), hidden_input_bias(), input(), and state().
Member Function Documentation
configure()
void luci_interpreter::kernels::GRU::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file GRU.cpp.
{
  auto hidden_hidden_shape = getTensorShape(hidden_hidden());
  auto hidden_input_shape = getTensorShape(hidden_input());
  LUCI_INTERPRETER_CHECK(hidden_hidden_shape.Dims(0) == hidden_input_shape.Dims(0));
  output()->resize(state()->shape());
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
}
References luci_interpreter::kernels::getTensorShape(), hidden_hidden(), hidden_input(), input(), LUCI_INTERPRETER_CHECK, luci::must_cast(), output(), luci_interpreter::Tensor::resize(), and state().
execute()
void luci_interpreter::kernels::GRU::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 48 of file GRU.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("luci-GRU Unsupported data type.");
  }
}
References input().
hidden_hidden()
const Tensor * luci_interpreter::kernels::GRU::hidden_hidden () const inline
Definition at line 36 of file GRU.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and GRU().
hidden_hidden_bias()
const Tensor * luci_interpreter::kernels::GRU::hidden_hidden_bias () const inline
Definition at line 37 of file GRU.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by GRU().
hidden_input()
const Tensor * luci_interpreter::kernels::GRU::hidden_input () const inline
Definition at line 38 of file GRU.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and GRU().
hidden_input_bias()
const Tensor * luci_interpreter::kernels::GRU::hidden_input_bias () const inline
Definition at line 39 of file GRU.h.
{ return _inputs[4]; }
References luci_interpreter::Kernel::_inputs.
Referenced by GRU().
input()
const Tensor * luci_interpreter::kernels::GRU::input () const inline
Definition at line 35 of file GRU.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and GRU().
output()
Tensor * luci_interpreter::kernels::GRU::output () const inline
Definition at line 41 of file GRU.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
state()
const Tensor * luci_interpreter::kernels::GRU::state () const inline
Definition at line 40 of file GRU.h.
{ return _inputs[5]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and GRU().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/GRU.h
compiler/luci-interpreter/src/kernels/GRU.cpp