ONE - On-device Neural Engine: caffeimport::WeightContext Class Reference
caffeimport::WeightContext Class Reference
#include <Context.h>
Public Member Functions
WeightContext (::caffe::NetParameter *caffemodel)
int blob_count (const LayerName &name)
::caffe::BlobProto * blob_get (const LayerName &name, uint32_t n)
Detailed Description
Definition at line 38 of file Context.h.
Constructor & Destructor Documentation
WeightContext()
caffeimport::WeightContext::WeightContext (::caffe::NetParameter * caffemodel) inline
Definition at line 41 of file Context.h.
                                               : _caffemodel(caffemodel)
  {
    for (uint32_t n = 0; n < _caffemodel->layer_size(); ++n)
    {
      auto layer = _caffemodel->mutable_layer(n);
      if (layer->has_name())
      {
        _data[layer->name()] = layer;
      }
    }
  }
Member Function Documentation
blob_count()
int caffeimport::WeightContext::blob_count (const LayerName & name) inline
Definition at line 55 of file Context.h.
  {
    if (_data.find(name) != _data.end())
      return _data.at(name)->blobs_size();
    assert(false);
    return 0;
  }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), and caffeimport::ScaleBuilder::build().
blob_get()
::caffe::BlobProto * caffeimport::WeightContext::blob_get (const LayerName & name, uint32_t n) inline
Definition at line 64 of file Context.h.
  {
    if (_data.find(name) != _data.end())
      return _data.at(name)->mutable_blobs(n);
    assert(false);
    return nullptr;
  };
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), and caffeimport::ScaleBuilder::build().
The documentation for this class was generated from the following file:
compiler/enco/frontend/caffe/src/Context.h