ONE - On-device Neural Engine: onert::backend::cpu::ops::StatelessRandomUniformLayer Class Reference
onert::backend::cpu::ops::StatelessRandomUniformLayer Class Reference
#include <StatelessRandomUniformLayer.h>
Public Member Functions
StatelessRandomUniformLayer ()
void configure (const IPortableTensor *shape, const IPortableTensor *seed, IPortableTensor *output)
void StatelessRandomUniformFloat32 ()
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 34 of file StatelessRandomUniformLayer.h.
Constructor & Destructor Documentation
StatelessRandomUniformLayer()
onert::backend::cpu::ops::StatelessRandomUniformLayer::StatelessRandomUniformLayer ()
Definition at line 30 of file StatelessRandomUniformLayer.cc.
  : _shape(nullptr), _seed(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::StatelessRandomUniformLayer::configure (const IPortableTensor * shape, const IPortableTensor * seed, IPortableTensor * output)
Definition at line 36 of file StatelessRandomUniformLayer.cc.
{
  _shape = shape;
  _seed = seed;
  _output = output;
}
run()
void onert::backend::cpu::ops::StatelessRandomUniformLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 51 of file StatelessRandomUniformLayer.cc.
{
  switch (_output->data_type())
  {
    // ToDo : It need to support INT8 and UINT8 also when will be applied quantization.
    case OperandType::FLOAT32:
      StatelessRandomUniformFloat32();
      break;
    default:
      throw std::runtime_error{"StatelessRandomUniformLayer: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), and StatelessRandomUniformFloat32().
StatelessRandomUniformFloat32()
void onert::backend::cpu::ops::StatelessRandomUniformLayer::StatelessRandomUniformFloat32 ()
Definition at line 44 of file StatelessRandomUniformLayer.cc.
{
  nnfw::cker::StatelessRandomUniform(getShape(_shape), getBuffer<int32_t>(_shape), getShape(_seed),
                                     getBuffer<int32_t>(_seed), getShape(_output),
                                     getBuffer<float>(_output));
}
References onert::backend::cpu::ops::getShape(), and nnfw::cker::StatelessRandomUniform().
Referenced by run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/StatelessRandomUniformLayer.h
runtime/onert/backend/cpu/ops/StatelessRandomUniformLayer.cc