ONE - On-device Neural Engine: mir_caffe2::Caffe2OpCreator Class Reference
mir_caffe2::Caffe2OpCreator Class Reference
#include <caffe2_op_creator.h>
Public Member Functions
Caffe2OpCreator (mir::Graph *g)
std::vector< mir::Operation::Output * > convertConstant (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertAdd (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertAveragePool (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertConv (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertConcat (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertDropout (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertFC (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertMaxPool (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertMul (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertRelu (const std::vector< mir::Operation::Output * > &inputs)
std::vector< mir::Operation::Output * > convertResizeNearest (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertSigmoid (const std::vector< mir::Operation::Output * > &inputs)
std::vector< mir::Operation::Output * > convertSoftmax (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertSpatialBN (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertSum (const std::vector< mir::Operation::Output * > &inputs)
std::vector< mir::Operation::Output * > convertClip (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
std::vector< mir::Operation::Output * > convertReshape (const std::vector< mir::Operation::Output * > &inputs, const ::caffe2::OperatorDef &op)
Detailed Description
Definition at line 38 of file caffe2_op_creator.h.
Constructor & Destructor Documentation
Caffe2OpCreator()
mir_caffe2::Caffe2OpCreator::Caffe2OpCreator (mir::Graph * g) inline explicit
Definition at line 41 of file caffe2_op_creator.h.
: _graph(g) {}
Member Function Documentation
convertAdd()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertAdd (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 261 of file caffe2_op_creator.cpp.
{
  assert(inputs.size() == 2);
  auto lhs = inputs[0];
  auto rhs = inputs[1];
  if (getSingleArgument(op, "broadcast", 0) != 0)
  {
    // FIXME This only works when 'axis' == 1 and the second input is 1-D.
    rhs = createOp<ops::ReshapeOp>(rhs, Shape{1, rhs->getShape().dim(0), 1, 1})->getOutput(0);
    auto result = createOp<ops::AddOp>(lhs, rhs)->getOutput(0);
    return {result};
  }
  auto result = createOp<ops::AddOp>(lhs, rhs)->getOutput(0);
  return {result};
}
References mir_caffe2::getSingleArgument().
convertAveragePool()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertAveragePool (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 281 of file caffe2_op_creator.cpp.
{
  checkConvLikeOp(op);
  assert(inputs.size() == 1);
  auto input = inputs[0];
  AvgPool2DOpAttributes attributes;
  std::tie(attributes.padding_before, attributes.padding_after) = getPadding(op);
  attributes.window = getWindowSize(op, inputs);
  attributes.strides = getStrides(op);
  attributes.include_pad = false;
  attributes.data_format = DataFormat::NCHW;
  auto result = createOp<ops::AvgPool2DOp>(input, attributes)->getOutput(0);
  return {result};
}
References mir::AvgPool2DOpAttributes::data_format, mir::AvgPool2DOpAttributes::include_pad, mir::AvgPool2DOpAttributes::padding_after, mir::AvgPool2DOpAttributes::padding_before, mir::AvgPool2DOpAttributes::strides, and mir::AvgPool2DOpAttributes::window.
convertClip()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertClip (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 509 of file caffe2_op_creator.cpp.
{
  float max = getSingleArgument(op, "max", float(0));
  float min = getSingleArgument(op, "min", float(0));
  if (min != 0.0f)
    throw std::runtime_error("Clip: min != 0 is not supported.");
  if (max <= min)
    throw std::runtime_error("Clip: max <= min is not supported.");
  auto cap_relu = createOp<ops::CappedReluOp>(inputs[0], max);
  return {cap_relu->getOutput(0)};
}
References mir_caffe2::getSingleArgument().
convertConcat()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertConcat (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 325 of file caffe2_op_creator.cpp.
{
  checkLayout(op);
  // `1` corresponds to the default (channels) axis.
  int axis = getSingleArgument(op, "axis", 1);
  auto result = createOp<ops::ConcatOp>(inputs, axis);
  return {result->getOutput(0)};
}
References mir_caffe2::getSingleArgument().
convertConstant()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertConstant (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 250 of file caffe2_op_creator.cpp.
{
  // Constant may not contain any data if it is a fake input.
  if (!hasArgument(op.arg(), "values"))
    return {};
  return {createOp<ops::ConstantOp>(createTensor(op))->getOutput(0)};
}
References mir_caffe2::hasArgument().
convertConv()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertConv (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 300 of file caffe2_op_creator.cpp.
{
  // dilation order: h w (not used)
  mir::Conv2DOpAttributes attributes;
  attributes.strides = getStrides(op);
  std::tie(attributes.padding_before, attributes.padding_after) = getPadding(op);
  attributes.num_groups = getSingleArgument(op, "group", 1);
  attributes.data_format = DataFormat::NCHW;
  std::vector<std::size_t> perm{0, 2, 3, 1}; // OIHW -> OHWI
  auto kernel = createOp<ops::TransposeOp>(inputs[1], perm)->getOutput(0);
  auto result = createOp<ops::Conv2DOp>(inputs[0], kernel, attributes)->getOutput(0);
  if (op.input_size() > 2)
  {
    auto bias = inputs[2];
    bias = createOp<ops::ReshapeOp>(bias, Shape{1, bias->getShape().dim(0), 1, 1})->getOutput(0);
    result = createOp<ops::AddOp>(result, bias)->getOutput(0);
  }
  return {result};
}
References mir::Conv2DOpAttributes::data_format, mir_caffe2::getSingleArgument(), mir::Conv2DOpAttributes::num_groups, mir::Conv2DOpAttributes::padding_after, mir::Conv2DOpAttributes::padding_before, and mir::Conv2DOpAttributes::strides.
convertDropout()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertDropout (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 337 of file caffe2_op_creator.cpp.
{
  // This is a no-op in inference mode.
  return {inputs[0]};
}
convertFC()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertFC (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 345 of file caffe2_op_creator.cpp.
{
  for (auto &s : {"axis", "axis_w", "float16_compute"})
    if (hasArgument(op.arg(), s))
      throw std::runtime_error(std::string("FC: only default '") + s + "' value is supported");
  const auto &input_shape = inputs[0]->getShape();
  // Transform input into 2-D tensor by flattening axes
  Shape shape{input_shape.dim(0), input_shape.numElements() / input_shape.dim(0)};
  auto reshape = createOp<ops::ReshapeOp>(inputs[0], shape)->getOutput(0);
  auto weights =
    createOp<ops::TransposeOp>(inputs[1], std::vector<std::size_t>{1, 0})->getOutput(0);
  auto result = createOp<ops::FullyConnectedOp>(reshape, weights)->getOutput(0);
  result = createOp<ops::AddOp>(result, inputs[2])->getOutput(0);
  return {result};
}
References mir::Shape::dim(), mir_caffe2::hasArgument(), and mir_caffe2::reshape.
convertMaxPool()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertMaxPool (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 366 of file caffe2_op_creator.cpp.
{
  checkConvLikeOp(op);
  assert(inputs.size() == 1);
  auto input = inputs[0];
  MaxPool2DOpAttributes attributes;
  std::tie(attributes.padding_before, attributes.padding_after) = getPadding(op);
  attributes.window = getWindowSize(op, inputs);
  attributes.strides = getStrides(op);
  attributes.data_format = DataFormat::NCHW;
  auto result = createOp<ops::MaxPool2DOp>(input, attributes)->getOutput(0);
  return {result};
}
References mir::MaxPool2DOpAttributes::data_format, mir::MaxPool2DOpAttributes::padding_after, mir::MaxPool2DOpAttributes::padding_before, mir::MaxPool2DOpAttributes::strides, and mir::MaxPool2DOpAttributes::window.
convertMul()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertMul (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 384 of file caffe2_op_creator.cpp.
{
  assert(inputs.size() == 2);
  auto lhs = inputs[0];
  auto rhs = inputs[1];
  if (getSingleArgument(op, "broadcast", 0) != 0)
  {
    // FIXME This only works when `axis` == 1 and the second input is 1-D.
    rhs = createOp<ops::ReshapeOp>(rhs, Shape{1, rhs->getShape().dim(0), 1, 1})->getOutput(0);
    auto result = createOp<ops::MulOp>(lhs, rhs)->getOutput(0);
    return {result};
  }
  auto result = createOp<ops::MulOp>(lhs, rhs)->getOutput(0);
  return {result};
}
References mir_caffe2::getSingleArgument().
convertRelu()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertRelu (const std::vector< mir::Operation::Output * > & inputs)
Definition at line 404 of file caffe2_op_creator.cpp.
{
  auto relu = createOp<ops::ReluOp>(inputs[0]);
  return {relu->getOutput(0)};
}
References mir_caffe2::relu.
convertReshape()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertReshape (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 526 of file caffe2_op_creator.cpp.
{
  auto shape_op = dynamic_cast<mir::ops::ConstantOp *>(inputs[1]->getNode());
  if (shape_op == nullptr)
    throw std::runtime_error("Reshape: non-constant shape is not supported yet.");
  const auto &shape_tensor = shape_op->getValue();
  Tensor<int64_t> out_shape_tensor(shape_tensor);
  ShapeRange range(out_shape_tensor.getShape());
  std::vector<int32_t> shape_vec;
  for (const auto &index : range)
  {
    shape_vec.push_back(static_cast<int32_t>(out_shape_tensor.at(index)));
  }
  Shape out_shape(shape_vec);
  auto reshape = createOp<ops::ReshapeOp>(inputs[0], out_shape);
  return {reshape->getOutput(0)};
}
References mir::Tensor< T >::at(), mir::Tensor< T >::getShape(), and mir_caffe2::reshape.
convertResizeNearest()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertResizeNearest (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 411 of file caffe2_op_creator.cpp.
{
  std::vector<float> scales(4);
  assert(inputs[0]->getShape().rank() == 4 && "only 4d tensors is supported");
  // Assuming NCHW format.
  scales[0] = 1.0f;
  scales[1] = 1.0f;
  scales[2] = getSingleArgument(op, "height_scale", 1.0f);
  scales[3] = getSingleArgument(op, "width_scale", 1.0f);
  auto result =
    createOp<ops::ResizeOp>(inputs[0], ops::ResizeOp::ResizeMethod::nearestNeighbor, scales)
      ->getOutput(0);
  return {result};
}
References mir_caffe2::getSingleArgument().
convertSigmoid()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertSigmoid (const std::vector< mir::Operation::Output * > & inputs)
Definition at line 428 of file caffe2_op_creator.cpp.
{
  auto result = createOp<ops::SigmoidOp>(inputs[0]);
  return {result->getOutput(0)};
}
convertSoftmax()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertSoftmax (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 435 of file caffe2_op_creator.cpp.
{
  int axis = getSingleArgument(op, "axis", 1);
  auto softmax = createOp<ops::SoftmaxOp>(inputs[0], axis);
  return {softmax->getOutput(0)};
}
References mir_caffe2::getSingleArgument(), and mir_caffe2::softmax.
convertSpatialBN()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertSpatialBN (const std::vector< mir::Operation::Output * > & inputs, const ::caffe2::OperatorDef & op)
Definition at line 444 of file caffe2_op_creator.cpp.
{
  checkLayout(op);
  // Sanity checks
  if (op.input_size() != 5)
    throw std::runtime_error(
      "SpatialBN must have exactly 5 inputs ('sums' and 'sumsq' are not supported yet)");
  if (getSingleArgument(op, "is_test", 1) != 1)
    throw std::runtime_error("SpatialBN: only test mode supported");
  // overall_res = (X - mean) / sqrt(var + epsilon) * scale + bias
  auto scale_op = dynamic_cast<mir::ops::ConstantOp *>(inputs[1]->getNode());
  auto bias_op = dynamic_cast<mir::ops::ConstantOp *>(inputs[2]->getNode());
  auto mean_op = dynamic_cast<mir::ops::ConstantOp *>(inputs[3]->getNode());
  auto var_op = dynamic_cast<mir::ops::ConstantOp *>(inputs[4]->getNode());
  if (scale_op == nullptr || bias_op == nullptr || mean_op == nullptr || var_op == nullptr)
    throw std::runtime_error(
      "SpatialBN: non-constant 'scale', 'bias', 'mean' and 'var' inputs are not supported yet.");
  const auto &scale_tensor = scale_op->getValue();
  const auto &bias_tensor = bias_op->getValue();
  const auto &mean_tensor = mean_op->getValue();
  const auto &var_tensor = var_op->getValue();
  float eps = getSingleArgument(op, "epsilon", 1e-5f);
  // res1 = X - mean
  Tensor<float> bias_data(mean_tensor);
  for (auto &idx : ShapeRange(bias_data.getShape()))
    bias_data.at(idx) *= -1;
  auto mean = createOp<ops::ConstantOp>(mean_tensor)->getOutput(0);
  mean = createOp<ops::ReshapeOp>(mean, Shape{1, mean->getShape().dim(0), 1, 1})->getOutput(0);
  auto result = createOp<ops::AddOp>(inputs[0], mean)->getOutput(0);
  // res2 = res1 * scale / (var + epsilon)
  Tensor<float> multiplier(scale_tensor);
  for (auto &idx : ShapeRange(scale_tensor.getShape()))
    multiplier.at(idx) /= std::sqrt(*reinterpret_cast<float *>(var_tensor.at(idx)) + eps);
  auto scale = createOp<ops::ConstantOp>(scale_tensor)->getOutput(0);
  scale = createOp<ops::ReshapeOp>(scale, Shape{1, scale->getShape().dim(0), 1, 1})->getOutput(0);
  result = createOp<ops::MulOp>(result, scale)->getOutput(0);
  // overall_res = res2 + bias
  auto bias = createOp<ops::ConstantOp>(bias_tensor)->getOutput(0);
  bias = createOp<ops::ReshapeOp>(bias, Shape{1, bias->getShape().dim(0), 1, 1})->getOutput(0);
  result = createOp<ops::AddOp>(result, bias)->getOutput(0);
  return {result};
}
References mir::Tensor< T >::at(), mir::Tensor< T >::getShape(), and mir_caffe2::getSingleArgument().
convertSum()
std::vector< mir::Operation::Output * > mir_caffe2::Caffe2OpCreator::convertSum (const std::vector< mir::Operation::Output * > & inputs)
Definition at line 498 of file caffe2_op_creator.cpp.
{
  auto result = createOp<ops::AddOp>(inputs[0], inputs[1])->getOutput(0);
  for (int i = 2; i < static_cast<int>(inputs.size()); ++i)
  {
    result = createOp<ops::AddOp>(result, inputs[i])->getOutput(0);
  }
  return {result};
}
The documentation for this class was generated from the following files:
compiler/mir/src/mir_caffe2_importer/caffe2_op_creator.h
compiler/mir/src/mir_caffe2_importer/caffe2_op_creator.cpp