ONE - On-device Neural Engine: onert::backend::builtin::ExternalContext Class Reference
onert::backend::builtin::ExternalContext Class Reference
#include <ExternalContext.h>
Public Member Functions
ExternalContext ()
void setMaxNumThreads (int max_num_threads)
ruy::Context * ruy_context () const
Detailed Description
Definition at line 37 of file ExternalContext.h.
Constructor & Destructor Documentation
ExternalContext()
onert::backend::builtin::ExternalContext::ExternalContext () inline
Definition at line 43 of file ExternalContext.h.
                    : _ruy_context(std::make_unique<ruy::Context>())
  {
    setMaxNumThreads(onert::util::getConfigInt(onert::util::config::RUY_THREADS));
    initPerThreadState();
  }
References onert::util::getConfigInt(), and setMaxNumThreads().
Member Function Documentation
ruy_context()
ruy::Context * onert::backend::builtin::ExternalContext::ruy_context () const inline
Definition at line 56 of file ExternalContext.h.
{ return _ruy_context.get(); }
setMaxNumThreads()
void onert::backend::builtin::ExternalContext::setMaxNumThreads (int max_num_threads) inline
Definition at line 49 of file ExternalContext.h.
  {
    const int target_num_threads =
      max_num_threads > -1 ? max_num_threads : kDefaultNumThreadpoolThreads;
    _ruy_context->set_max_num_threads(target_num_threads);
  }
References kDefaultNumThreadpoolThreads.
Referenced by ExternalContext().
The documentation for this class was generated from the following file:
runtime/onert/core/src/backend/builtin/ExternalContext.h