ONE - On-device Neural Engine: loco::Dimension Class Reference
loco::Dimension Class Reference final
The value of one dimension in a tensor shape.
#include <Dimension.h>
Public Member Functions
Dimension ()=default
Construct an "unknown" dimension.
Dimension (uint32_t value)
Construct a "known" dimension.
bool known (void) const
Return whether the value is known (or not)
uint32_t value (void) const
Return the value.
void set (uint32_t value)
void unset (void)
Detailed Description
The value of one dimension in a tensor shape.
Note
The value may be unknown
Definition at line 29 of file Dimension.h.
Constructor & Destructor Documentation
Dimension() [1/2]
loco::Dimension::Dimension () default
Construct an "unknown" dimension.
Dimension() [2/2]
loco::Dimension::Dimension (uint32_t value) inline
Construct a "known" dimension.
Definition at line 43 of file Dimension.h.
{ set(value); }
References set(), and value().
Member Function Documentation
known()
bool loco::Dimension::known (void) const inline
Return whether the value is known (or not)
Definition at line 47 of file Dimension.h.
{ return _kind == Kind::Known; }
Referenced by loco::element_count(), loco::operator<<(), loco::operator==(), exo::to_shape_description(), and luci::to_shape_description().
set()
void loco::Dimension::set (uint32_t value) inline
Definition at line 53 of file Dimension.h.
  {
    _kind = Kind::Known;
    _value = value;
  }
References value().
Referenced by Dimension(), and luci::get_channel_dim_index().
unset()
void loco::Dimension::unset (void) inline
Definition at line 59 of file Dimension.h.
  {
    _kind = Kind::Unknown;
    _value = 0;
  }
Referenced by moco::tensor_shape().
value()
uint32_t loco::Dimension::value (void) const inline
Return the value.
Note
This value is meaningful only for known dimension
Definition at line 51 of file Dimension.h.
{ return _value; }
Referenced by luci::cal_offset(), Dimension(), loco::element_count(), moco::PlaneInference::fill(), moco::PlaneInference::infer(), moco::Padding2DInference::operator()(), loco::operator<<(), loco::operator==(), set(), moco::TensorPackEnumerator::start(), exo::to_shape_description(), luci::to_shape_description(), moco::valid_shape_for_constfold_binary_op(), and moco::window_of().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Dimension.h