ONE - On-device Neural Engine: luci::CircleOutput Class Reference
luci::CircleOutput Class Reference final
CircleNode for Output of the Graph.
#include <CircleOutput.h>
Public Member Functions
void index (const loco::GraphOutputIndex &index)
loco::GraphOutputIndex index (void) const
bool indexed (void) const
loco::Node * from (void) const
void from (loco::Node *node)
Public Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >
loco::Use * at (uint32_t n) const
Detailed Description
CircleNode for Output of the Graph.
Note
This will not be exported as a specific op
Definition at line 34 of file CircleOutput.h.
Member Function Documentation
from() [1/2]
void luci::CircleOutput::from (loco::Node * node) inline
Definition at line 44 of file CircleOutput.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >::at(), and loco::Use::node().
from() [2/2]
loco::Node * luci::CircleOutput::from (void) const inline
Definition at line 43 of file CircleOutput.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 1, CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT > >::at(), and loco::Use::node().
Referenced by luci::test::TestGraph::complete(), luci::test::TestGraph::complete(), luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), and luci::FuseBCQPass::run().
index() [1/2]
void luci::CircleOutput::index (const loco::GraphOutputIndex & index)
Definition at line 25 of file CircleOutput.cpp.
{
  // CircleOutput internally stores "GraphOutputIndex" as int64_t
  _index = static_cast<int64_t>(index);
}
References index().
Referenced by luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), circle_eval_diff::interpret(), luci::link(), luci_interpreter::Interpreter::readOutputTensor(), and luci::FuseBCQPass::run().
index() [2/2]
loco::GraphOutputIndex luci::CircleOutput::index (void) const
Definition at line 31 of file CircleOutput.cpp.
{
  assert(_index >= std::numeric_limits<loco::GraphOutputIndex>::min());
  assert(_index <= std::numeric_limits<loco::GraphOutputIndex>::max());
  return static_cast<loco::GraphOutputIndex>(_index);
}
Referenced by index().
indexed()
bool luci::CircleOutput::indexed (void) const inline
Definition at line 40 of file CircleOutput.h.
{ return _index != -1; }
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/Nodes/CircleOutput.h
compiler/luci/lang/src/Nodes/CircleOutput.cpp