ONE - On-device Neural Engine: mir::ops::PadOp Class Reference
mir::ops::PadOp Class Reference
#include <PadOp.h>
Public Member Functions
PadOp (Output *arg, const PadOpAttributes &attributes)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
const std::vector< std::int32_t > & getPaddingBefore () const
const std::vector< std::int32_t > & getPaddingAfter () const
float getPaddingValue () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 28 of file PadOp.h.
Constructor & Destructor Documentation
PadOp()
mir::ops::PadOp::PadOp (Output * arg, const PadOpAttributes & attributes) inline
Definition at line 31 of file PadOp.h.
    : Operation(Type::pad, {arg}), _attributes(attributes)
  {
    assert(_attributes.padding_before.size() == _attributes.padding_after.size());
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::PadOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 38 of file PadOp.h.
  {
    return new PadOp(inputs[0], _attributes);
  }
getPaddingAfter()
const std::vector< std::int32_t > & mir::ops::PadOp::getPaddingAfter () const inline
Definition at line 45 of file PadOp.h.
{ return _attributes.padding_after; }
References mir::PadOpAttributes::padding_after.
Referenced by mir_interpreter::PadImpl< T >::run(), nnc::AclCppOpGenerator::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
getPaddingBefore()
const std::vector< std::int32_t > & mir::ops::PadOp::getPaddingBefore () const inline
Definition at line 43 of file PadOp.h.
{ return _attributes.padding_before; }
References mir::PadOpAttributes::padding_before.
Referenced by mir_interpreter::PadImpl< T >::run(), nnc::AclCppOpGenerator::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
getPaddingValue()
float mir::ops::PadOp::getPaddingValue () const inline
Definition at line 47 of file PadOp.h.
{ return _attributes.padding_value; }
References mir::PadOpAttributes::padding_value.
Referenced by mir_interpreter::PadImpl< T >::run(), nnc::AclCppOpGenerator::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/PadOp.h
compiler/mir/src/ops/PadOp.cpp