ONE - On-device Neural Engine: onert::dumper::h5::MinMaxDumper Class Reference
onert::dumper::h5::MinMaxDumper Class Reference
#include <MinMaxDumper.h>
Public Member Functions
MinMaxDumper (const std::string &filepath)
void dump (const exec::IOMinMaxMap &in_minmax, const exec::OpMinMaxMap &op_minmax) const
Dump input minmax map.
Detailed Description
Definition at line 58 of file MinMaxDumper.h.
Constructor & Destructor Documentation
MinMaxDumper()
onert::dumper::h5::MinMaxDumper::MinMaxDumper (const std::string & filepath)
Definition at line 48 of file MinMaxDumper.cc.
                                                    : Dumper(filepath)
{
  auto root_grp = _file.openGroup("/");
  ensureGroup(root_grp, h5_value_grpname);
}
References onert::dumper::h5::Dumper::_file, and onert::dumper::h5::ensureGroup().
Member Function Documentation
dump()
void onert::dumper::h5::MinMaxDumper::dump (const exec::IOMinMaxMap & in_minmax, const exec::OpMinMaxMap & op_minmax) const
Dump input minmax map.
Parameters
[in] in_minmax input minmax map
[in] op_minmax op minmax map
Definition at line 54 of file MinMaxDumper.cc.
{
  auto val_grp = _file.openGroup(h5_value_grpname);
  auto num_run = val_grp.getNumObjs();
  auto run_grp = val_grp.createGroup(std::string("run_") + std::to_string(num_run));
  auto model_grp = ensureGroup(run_grp, std::string("model_") + "0");
  hsize_t dims[] = {2};
  H5::DataSpace dspace(1, dims); // rank=1, dim(0)=2, {min, max}
  for (auto &&e : input_minmax)
  {
    // key = {subg_idx, io_idx} = e.first
    const auto subg_idx = e.first.first.value();
    const auto io_idx = e.first.second.value();
    auto subg_grp = ensureGroup(model_grp, std::string("subg_") + std::to_string(subg_idx));
    auto input_dset = subg_grp.createDataSet(std::string("input_") + std::to_string(io_idx),
                                             H5::PredType::IEEE_F32BE, dspace);
    input_dset.write(e.second.data, H5::PredType::NATIVE_FLOAT);
  }
  for (auto &&e : op_minmax)
  {
    // key = {subg_idx, op_idx} = e.first
    const auto subg_idx = e.first.first.value();
    const auto op_idx = e.first.second.value();
    auto subg_grp = ensureGroup(model_grp, std::string("subg_") + std::to_string(subg_idx));
    auto op_dset = subg_grp.createDataSet(std::string("op_") + std::to_string(op_idx),
                                          H5::PredType::IEEE_F32BE, dspace);
    op_dset.write(e.second.data, H5::PredType::NATIVE_FLOAT);
  }
}
References onert::dumper::h5::Dumper::_file, and onert::dumper::h5::ensureGroup().
Referenced by onert::exec::MinMaxRecorder::handleSubgraphEnd().
The documentation for this class was generated from the following files:
runtime/onert/core/src/dumper/h5/MinMaxDumper.h
runtime/onert/core/src/dumper/h5/MinMaxDumper.cc