ONE - On-device Neural Engine: moco::ConcatV2GraphBuilder Class Reference
moco::ConcatV2GraphBuilder Class Reference
#include <Concat.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const final
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const final
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 25 of file Concat.h.
Member Function Documentation
build()
void moco::ConcatV2GraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const final virtual
Implements moco::GraphBuilder.
Definition at line 80 of file Concat.cpp.
{
  assert(context != nullptr);
  auto graph = context->graph();
  auto tensor_names = context->tensor_names();
  auto updates = context->updates();
  const int num_inputs = node.input_size() - 1;
  std::vector<TensorName> input_names;
  auto concat_node = graph->nodes()->create<TFConcatV2>(num_inputs);
  concat_node->name(node.name());
  for (int ni = 0; ni < num_inputs; ++ni)
  {
    input_names.push_back(TensorName(node.input(ni)));
  }
  // last one is the axis
  input_names.push_back(TensorName(node.input(num_inputs)));
  // register string-name to the last node as output of concat(s)
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, concat_node);
  auto update = std::make_unique<TFConcatV2GraphUpdate>(concat_node, input_names);
  updates->enroll(std::move(update));
}
References moco::SymbolTable::enroll(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::GraphBuilderContext::tensor_names(), moco::update(), and moco::GraphBuilderContext::updates().
validate()
bool moco::ConcatV2GraphBuilder::validate (const tensorflow::NodeDef & node) const final virtual
Implements moco::GraphBuilder.
Definition at line 70 of file Concat.cpp.
{
  if (!plier::tf::has_attrs(node, {"T", "N", "Tidx"}))
    return false;
  // Concat node SHOULD have 3 or more inputs, that is 2 + axis
  const int num_inputs = node.input_size() - 1;
  return (num_inputs >= 2) && (num_inputs == plier::tf::get_int_attr(node, "N"));
}
References plier::tf::get_int_attr(), and plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Concat.h
compiler/moco/import/src/Nodes/Concat.cpp