ONE - On-device Neural Engine: locoex::TFLMaxPool2D Class Reference
locoex::TFLMaxPool2D Class Reference final
MAX_POOL_2D in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
TFLMaxPool2D ()
loco::Node * value (void) const
void value (loco::Node *node)
Padding padding () const
void padding (Padding padding)
const Filter * filter (void) const
Filter * filter (void)
const Stride * stride (void) const
Stride * stride (void)
Public Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::MAX_POOL_2D >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >
TFLNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >
loco::Use * at (unsigned n) const
Detailed Description
MAX_POOL_2D in TensorFlow Lite.
Definition at line 326 of file TFLNodes.h.
Constructor & Destructor Documentation
TFLMaxPool2D()
locoex::TFLMaxPool2D::TFLMaxPool2D () inline
Definition at line 330 of file TFLNodes.h.
                 : _padding(Padding::UNDEFINED)
  { /* empty */
  }
Member Function Documentation
filter() [1/2]
Filter * locoex::TFLMaxPool2D::filter (void) inline
Definition at line 342 of file TFLNodes.h.
{ return &_filter; }
filter() [2/2]
const Filter * locoex::TFLMaxPool2D::filter (void) const inline
Definition at line 341 of file TFLNodes.h.
{ return &_filter; }
padding() [1/2]
Padding locoex::TFLMaxPool2D::padding () const inline
Definition at line 338 of file TFLNodes.h.
{ return _padding; }
padding() [2/2]
void locoex::TFLMaxPool2D::padding (Padding padding) inline
Definition at line 339 of file TFLNodes.h.
{ _padding = padding; }
References padding().
Referenced by padding().
stride() [1/2]
Stride * locoex::TFLMaxPool2D::stride (void) inline
Definition at line 345 of file TFLNodes.h.
{ return &_stride; }
stride() [2/2]
const Stride * locoex::TFLMaxPool2D::stride (void) const inline
Definition at line 344 of file TFLNodes.h.
{ return &_stride; }
value() [1/2]
void locoex::TFLMaxPool2D::value (loco::Node * node) inline
Definition at line 336 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >::at(), and loco::Use::node().
value() [2/2]
loco::Node * locoex::TFLMaxPool2D::value (void) const inline
Definition at line 335 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::MAX_POOL_2D > >::at(), and loco::Use::node().
Referenced by exo::MaxPool2DConverter::convert().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h