ONE - On-device Neural Engine: moco::SoftmaxGraphBuilder Class Reference
moco::SoftmaxGraphBuilder Class Reference final
GraphBuilder for Softmax node.
#include <Softmax.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Softmax node.
Definition at line 28 of file Softmax.h.
Member Function Documentation
build()
void moco::SoftmaxGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 68 of file Softmax.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  // creating TF dialect Softmax node
  auto tf_softmax = graph->nodes()->create<TFSoftmax>();
  tf_softmax->name(node.name());
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, tf_softmax);
  auto update = std::make_unique<SoftmaxGraphUpdate>(tf_softmax, TensorName(node.input(0)));
  updates->enroll(std::move(update));
}
References moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::GraphBuilderContext::tensor_names(), moco::update(), and moco::GraphBuilderContext::updates().
validate()
bool moco::SoftmaxGraphBuilder::validate (const tensorflow::NodeDef & node) const override virtual
Implements moco::GraphBuilder.
Definition at line 60 of file Softmax.cpp.
{
  if (node.input_size() != 1)
    return false;
  return plier::tf::has_attrs(node, {"T"});
}
References plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Softmax.h
compiler/moco/import/src/Nodes/Softmax.cpp