ONE - On-device Neural Engine: flexbuffers::String Class Reference
flexbuffers::String Class Reference
#include <flexbuffers.h>
Public Member Functions
String (const uint8_t *data, uint8_t byte_width)
String (const uint8_t *data, uint8_t byte_width, size_t sz)
size_t length () const
const char * c_str () const
std::string str () const
bool IsTheEmptyString () const
Public Member Functions inherited from flexbuffers::Sized
Sized (const uint8_t *data, uint8_t byte_width)
Sized (const uint8_t *data, uint8_t byte_width, size_t sz)
size_t size () const
size_t read_size () const
Public Member Functions inherited from flexbuffers::Object
Object (const uint8_t *data, uint8_t byte_width)
Static Public Member Functions
static String EmptyString ()
Additional Inherited Members
Protected Attributes inherited from flexbuffers::Sized
size_t size_
Protected Attributes inherited from flexbuffers::Object
const uint8_t * data_
uint8_t byte_width_
Detailed Description
Definition at line 243 of file flexbuffers.h.
Constructor & Destructor Documentation
String() [1/2]
flexbuffers::String::String (const uint8_t * data, uint8_t byte_width) inline
Definition at line 247 of file flexbuffers.h.
: Sized(data, byte_width) {}
String() [2/2]
flexbuffers::String::String (const uint8_t * data, uint8_t byte_width, size_t sz) inline
Definition at line 249 of file flexbuffers.h.
: Sized(data, byte_width, sz) {}
Member Function Documentation
c_str()
const char * flexbuffers::String::c_str () const inline
Definition at line 252 of file flexbuffers.h.
{ return reinterpret_cast<const char *>(data_); }
References flexbuffers::Object::data_.
Referenced by str().
EmptyString()
static String flexbuffers::String::EmptyString () inline static
Definition at line 255 of file flexbuffers.h.
  {
    static const char *empty_string = "";
    return String(reinterpret_cast<const uint8_t *>(empty_string), 1, 0);
  }
Referenced by flexbuffers::Reference::AsString(), and IsTheEmptyString().
IsTheEmptyString()
bool flexbuffers::String::IsTheEmptyString () const inline
Definition at line 260 of file flexbuffers.h.
{ return data_ == EmptyString().data_; }
References flexbuffers::Object::data_, and EmptyString().
length()
size_t flexbuffers::String::length () const inline
Definition at line 251 of file flexbuffers.h.
{ return size(); }
References flexbuffers::Sized::size().
str()
std::string flexbuffers::String::str () const inline
Definition at line 253 of file flexbuffers.h.
{ return std::string(c_str(), size()); }
References c_str(), and flexbuffers::Sized::size().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h