ONE - On-device Neural Engine: nest::DomainContext Class Reference
nest::DomainContext Class Reference
#include <DomainContext.h>
Public Member Functions
uint32_t count (void) const
Domain make (std::initializer_list< uint32_t > dims)
const DomainInfo & info (const Domain &) const
Detailed Description
Definition at line 28 of file DomainContext.h.
Member Function Documentation
count()
uint32_t nest::DomainContext::count (void) const
Definition at line 22 of file DomainContext.cpp.
{ return _info.size(); }
Referenced by make().
info()
const DomainInfo & nest::DomainContext::info (const Domain & dom) const
Definition at line 33 of file DomainContext.cpp.
{
  return _info.at(dom.id().value());
}
References nest::Domain::id(), and nest::DomainID::value().
make()
Domain nest::DomainContext::make (std::initializer_list< uint32_t > dims)
Definition at line 24 of file DomainContext.cpp.
{
  const DomainID domain_id{count()};
  _info.emplace_back(dims);
  return Domain{domain_id};
}
References count().
The documentation for this class was generated from the following files:
compiler/nest/core/include/nest/DomainContext.h
compiler/nest/core/src/DomainContext.cpp