ONE - On-device Neural Engine: fme_detect::EqualizePatternFinder Class Reference
fme_detect::EqualizePatternFinder Class Reference final
#include <EqualizePatternFinder.h>
Data Structures
struct Context
Public Member Functions
EqualizePatternFinder (const Context &ctx)
std::vector< EqualizePattern > find (loco::Graph *) const
Detailed Description
Definition at line 30 of file EqualizePatternFinder.h.
Constructor & Destructor Documentation
EqualizePatternFinder()
fme_detect::EqualizePatternFinder::EqualizePatternFinder (const Context & ctx) inline
Definition at line 39 of file EqualizePatternFinder.h.
: _ctx(ctx) {}
Member Function Documentation
find()
std::vector< EqualizePattern > fme_detect::EqualizePatternFinder::find (loco::Graph * g) const
Definition at line 267 of file EqualizePatternFinder.cpp.
{
  if (g == nullptr)
    throw std::invalid_argument("g");
  std::vector<EqualizePattern> res;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    const auto cnode = loco::must_cast<luci::CircleNode *>(node);
    if (not _ctx._allow_dup_op)
    {
      // We create new Ops (front, back) for each matched pattern, so duplicate
      // Ops can be created. This condition prevents pattern matching for a node
      // (front) with multiple successors (backs) to avoid duplicate computation.
      // TODO Duplicate Ops can be removed if all (pred-succ) pairs are matched
      // as the same pattern. For example, if (pred-succ1) is ScaleOnly and
      // (pred-succ2) is ScaleOnly, pred does not need to be duplicated.
      if (loco::succs(cnode).size() != 1)
        continue;
    }
    ::match(cnode, res);
  }
  return res;
}
References fme_detect::EqualizePatternFinder::Context::_allow_dup_op, loco::active_nodes(), loco::must_cast(), loco::output_nodes(), size, and loco::succs().
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/fme-detect/src/EqualizePatternFinder.h
compiler/fme-detect/src/EqualizePatternFinder.cpp