ONE - On-device Neural Engine: onert::ir::train::TrainableGraph Class Reference
onert::ir::train::TrainableGraph Class Reference
#include <TrainableGraph.h>
Public Member Functions
TrainableGraph ()
Construct a new Trainable Graph object.
TrainableGraph (const TrainableGraph &tgraph)
TrainableGraph (const Graph &graph)
~TrainableGraph ()=default
OperandIndex addOperand (const Shape &shape, const TypeInfo &type)
OperandIndex addOperand (OperandIndex index, std::unique_ptr< Operand > &&operand)
Add an operand to the graph with the given index and object.
OperationIndex addOperation (std::unique_ptr< ITrainableOperation > &&operation)
Add a new trainable operation to the graph.
OperationIndex replaceOperation (OperationIndex index, std::unique_ptr< ITrainableOperation > &&operation)
Replace a trainable operation which the graph already has.
OperandIndex addDerivative (OperandIndex index, std::unique_ptr< Operand > &&derivative)
Add a derivative to the graph with the given index and object.
void changeShape (const OperandIndex &ind, const ir::Shape &new_shape) override
void changeDerivativeShape (const OperandIndex &ind, const ir::Shape &new_shape)
void addInput (const OperandIndex &ind, const std::string &name="")
void addOutput (const OperandIndex &ind, const std::string &name="")
void addLoss (const OperandIndex &loss_ind, const IOIndex &pred_io_ind)
void verify () const
void removeOperand (const OperandIndex &ind)
void setLayout (Layout layout)
void setInputs (OperandIndexSequence inputs, std::unordered_map< std::string, IOIndex > name_to_input)
void setOutputs (OperandIndexSequence outputs, std::unordered_map< std::string, IOIndex > name_to_output)
const OperandIndexSequence & getInputs () const override
const OperandIndexSequence & getOutputs () const override
IOIndex getInputIndex (const std::string &name) const override
IOIndex getOutputIndex (const std::string &name) const override
const Operands & operands () const override
Operands & operands ()
const Operations & operations () const override
const Operands & derivatives () const
OperandIndex getLossIndex (const IOIndex &pred_io_ind) const
Layout layout () const
const Graph & graph () const
const ITrainableOperation & operation (OperationIndex index) const
std::vector< ir::OperationIndex > topolSortOperations () const
Public Member Functions inherited from onert::ir::IGraph
virtual ~IGraph ()=default
virtual const OperandIndexSequence & getInputs () const =0
virtual const OperandIndexSequence & getOutputs () const =0
virtual IOIndex getInputIndex (const std::string &name) const =0
virtual IOIndex getOutputIndex (const std::string &name) const =0
virtual const Operands & operands () const =0
virtual const Operations & operations () const =0
virtual void changeShape (const OperandIndex &index, const ir::Shape &new_shape)=0
Detailed Description
Definition at line 33 of file TrainableGraph.h.
Constructor & Destructor Documentation
TrainableGraph() [1/3]
onert::ir::train::TrainableGraph::TrainableGraph () explicit
Construct a new Trainable Graph object.
Parameters
graph
Definition at line 30 of file TrainableGraph.cc.
: _graph{} {}
TrainableGraph() [2/3]
onert::ir::train::TrainableGraph::TrainableGraph (const TrainableGraph & tgraph) explicit
Definition at line 32 of file TrainableGraph.cc.
  : _graph{tgraph._graph}, _derivatives{tgraph._derivatives}, _losses{tgraph._losses}
{
  tgraph.operations().iterate(
    [&](const onert::ir::OperationIndex &index, const onert::ir::IOperation &op) {
      replaceOperation(index, dynamic_cast<const ITrainableOperation &>(op).clone());
    });
}
References onert::ir::clone(), onert::util::ObjectManager< Index, Object >::iterate(), operations(), and replaceOperation().
TrainableGraph() [3/3]
onert::ir::train::TrainableGraph::TrainableGraph (const Graph & graph) explicit
Definition at line 41 of file TrainableGraph.cc.
: _graph{graph} {}
~TrainableGraph()
onert::ir::train::TrainableGraph::~TrainableGraph () default
Member Function Documentation
addDerivative()
OperandIndex onert::ir::train::TrainableGraph::addDerivative (OperandIndex index, std::unique_ptr< Operand > && derivative)
Add a derivative to the graph with the given index and object.
If the given index is available, it succeeds. And derivative is moved which invalidates the caller's pointer. If the given index is already taken, it fails. And derivative will not be moved so the caller's pointer will be still valid.
Parameters
[in] index Index to be added
[in] derivative Derivative operand to be added
Returns
OperandIndex index if successful, UNDEFINED otherwise
Definition at line 64 of file TrainableGraph.cc.
{
  return _derivatives.push(std::move(derivative), index);
}
References onert::util::ObjectManager< Index, Object >::push().
addInput()
void onert::ir::train::TrainableGraph::addInput (const OperandIndex & ind, const std::string & name = "")
Definition at line 91 of file TrainableGraph.cc.
{
  _graph.addInput(ind, name);
}
References onert::ir::Graph::addInput().
Referenced by onert::compiler::train::pass::LossInsertionPass::run().
addLoss()
void onert::ir::train::TrainableGraph::addLoss (const OperandIndex & loss_ind, const IOIndex & pred_io_ind)
Definition at line 132 of file TrainableGraph.cc.
{
  _losses.emplace(pred_ioind, loss_ind);
}
Referenced by onert::compiler::train::pass::LossInsertionPass::run().
addOperand() [1/2]
OperandIndex onert::ir::train::TrainableGraph::addOperand (const Shape & shape, const TypeInfo & type)
Definition at line 43 of file TrainableGraph.cc.
{
  return _graph.addOperand(shape, type);
}
References onert::ir::Graph::addOperand().
Referenced by onert::compiler::train::pass::LossInsertionPass::run().
addOperand() [2/2]
OperandIndex onert::ir::train::TrainableGraph::addOperand (OperandIndex index, std::unique_ptr< Operand > && operand)
Add an operand to the graph with the given index and object.
If the given index is available, it succeeds. And operand is moved which invalidates the caller's pointer. If the given index is already taken, it fails. And operand will not be moved so the caller's pointer will be still valid.
Parameters
[in] index Index to be added
[in] operand Operand to be added
Returns
OperandIndex index if successful, UNDEFINED otherwise
Definition at line 48 of file TrainableGraph.cc.
{
  return _graph.addOperand(index, std::move(operand));
}
References onert::ir::Graph::addOperand().
addOperation()
OperationIndex onert::ir::train::TrainableGraph::addOperation (std::unique_ptr< ITrainableOperation > && operation)
Add a new trainable operation to the graph.
If the given operation has at least one invalid operand index, it fails. And operation will not be moved so the caller's pointer will be still valid.
Parameters
operation Operation to be added
Returns
OperationIndex index if successful, UNDEFINED otherwise
Definition at line 53 of file TrainableGraph.cc.
{
  return _graph.addOperation(std::move(operation));
}
References onert::ir::Graph::addOperation(), and operation().
Referenced by onert::compiler::train::pass::LossInsertionPass::run().
addOutput()
void onert::ir::train::TrainableGraph::addOutput (const OperandIndex & ind, const std::string & name = "")
Definition at line 96 of file TrainableGraph.cc.
{
  _graph.addOutput(ind, name);
}
References onert::ir::Graph::addOutput().
changeDerivativeShape()
void onert::ir::train::TrainableGraph::changeDerivativeShape (const OperandIndex & ind, const ir::Shape & new_shape)
Definition at line 85 of file TrainableGraph.cc.
{
  assert(_derivatives.exist(index));
  _derivatives.at(index).info().shape(new_shape);
}
References onert::util::ObjectManager< Index, Object >::at(), and onert::util::ObjectManager< Index, Object >::exist().
changeShape()
void onert::ir::train::TrainableGraph::changeShape (const OperandIndex & ind, const ir::Shape & new_shape) override virtual
Implements onert::ir::IGraph.
Definition at line 80 of file TrainableGraph.cc.
{
  _graph.changeShape(index, new_shape);
}
References onert::ir::Graph::changeShape().
derivatives()
const Operands & onert::ir::train::TrainableGraph::derivatives () const inline
Definition at line 122 of file TrainableGraph.h.
{ return _derivatives; }
getInputIndex()
IOIndex onert::ir::train::TrainableGraph::getInputIndex (const std::string & name) const override virtual
Implements onert::ir::IGraph.
Definition at line 70 of file TrainableGraph.cc.
{
  return _graph.getInputIndex(name);
}
References onert::ir::Graph::getInputIndex().
getInputs()
const OperandIndexSequence & onert::ir::train::TrainableGraph::getInputs () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 115 of file TrainableGraph.h.
{ return _graph.getInputs(); }
References onert::ir::Graph::getInputs().
Referenced by onert::exec::train::TrainableExecutor::TrainableExecutor().
getLossIndex()
OperandIndex onert::ir::train::TrainableGraph::getLossIndex (const IOIndex & pred_io_ind) const
Definition at line 137 of file TrainableGraph.cc.
{
  auto itr = _losses.find(pred_ioind);
  return (itr == _losses.end()) ? OperandIndex{} : itr->second;
}
Referenced by onert::exec::train::TrainableExecutor::getLoss().
getOutputIndex()
IOIndex onert::ir::train::TrainableGraph::getOutputIndex (const std::string & name) const override virtual
Implements onert::ir::IGraph.
Definition at line 75 of file TrainableGraph.cc.
{
  return _graph.getOutputIndex(name);
}
References onert::ir::Graph::getOutputIndex().
getOutputs()
const OperandIndexSequence & onert::ir::train::TrainableGraph::getOutputs () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 116 of file TrainableGraph.h.
{ return _graph.getOutputs(); }
References onert::ir::Graph::getOutputs().
Referenced by onert::compiler::train::pass::LossInsertionPass::run(), and onert::exec::train::TrainableExecutor::TrainableExecutor().
graph()
const Graph & onert::ir::train::TrainableGraph::graph () const inline
Definition at line 125 of file TrainableGraph.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::exec::train::TrainableExecutor::graph(), onert::compiler::train::LoweredTrainableGraph::graph(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
layout()
Layout onert::ir::train::TrainableGraph::layout () const inline
Definition at line 124 of file TrainableGraph.h.
{ return _graph.layout(); }
References onert::ir::Graph::layout().
Referenced by onert::backend::train::BackendContext::genTrainingTensors(), and setLayout().
operands() [1/2]
Operands & onert::ir::train::TrainableGraph::operands () inline
Definition at line 120 of file TrainableGraph.h.
{ return _graph.operands(); } // TODO Remove this non-const accessor
References onert::ir::Graph::operands().
operands() [2/2]
const Operands & onert::ir::train::TrainableGraph::operands () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 119 of file TrainableGraph.h.
{ return _graph.operands(); }
References onert::ir::Graph::operands().
Referenced by onert::backend::train::BackendContext::genKernels(), onert::backend::builtin::train::BackendContext::genKernels(), onert::backend::train::BackendContext::genTrainingTensors(), and onert::compiler::train::pass::LossInsertionPass::run().
operation()
const ITrainableOperation & onert::ir::train::TrainableGraph::operation (OperationIndex index) const
Definition at line 121 of file TrainableGraph.cc.
{
  // NOTE Virtual inherited objects cannot be static_casted.
  return dynamic_cast<const ITrainableOperation &>(_graph.operations().at(index));
}
References onert::util::ObjectManager< Index, Object >::at(), and onert::ir::Graph::operations().
Referenced by addOperation(), onert::backend::builtin::train::KernelGenerator::generate(), onert::backend::train::KernelGenerator::generate(), onert::compiler::train::StaticDerivativeShapeInferer::infer(), and replaceOperation().
operations()
const Operations & onert::ir::train::TrainableGraph::operations () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 121 of file TrainableGraph.h.
{ return _graph.operations(); }
References onert::ir::Graph::operations().
Referenced by TrainableGraph(), and verify().
removeOperand()
void onert::ir::train::TrainableGraph::removeOperand (const OperandIndex & ind)
Definition at line 117 of file TrainableGraph.cc.
{ _graph.removeOperand(ind); }
References onert::ir::Graph::removeOperand().
replaceOperation()
OperationIndex onert::ir::train::TrainableGraph::replaceOperation (OperationIndex index, std::unique_ptr< ITrainableOperation > && operation)
Replace a trainable operation which the graph already has.
If the given index is available, it succeeds. And operation is moved which invalidates the caller's pointer. If the given operation has at least one invalid operand index, it fails. And operation will not be moved so the caller's pointer will be still valid.
No information in the graph is changed except for replacing an operation.
Parameters
operation Operation to be added
Returns
OperationIndex index if successful, UNDEFINED otherwise
Definition at line 58 of file TrainableGraph.cc.
{
  return _graph.replaceOperation(index, std::move(operation));
}
References operation(), and onert::ir::Graph::replaceOperation().
Referenced by TrainableGraph().
setInputs()
void onert::ir::train::TrainableGraph::setInputs (OperandIndexSequence inputs, std::unordered_map< std::string, IOIndex > name_to_input)
setLayout()
void onert::ir::train::TrainableGraph::setLayout (Layout layout)
Definition at line 119 of file TrainableGraph.cc.
{ _graph.setLayout(layout); }
References layout(), and onert::ir::Graph::setLayout().
setOutputs()
void onert::ir::train::TrainableGraph::setOutputs (OperandIndexSequence outputs, std::unordered_map< std::string, IOIndex > name_to_output)
topolSortOperations()
std::vector< ir::OperationIndex > onert::ir::train::TrainableGraph::topolSortOperations () const
Definition at line 127 of file TrainableGraph.cc.
{
  return _graph.topolSortOperations();
}
References onert::ir::Graph::topolSortOperations().
verify()
void onert::ir::train::TrainableGraph::verify (void) const
Definition at line 101 of file TrainableGraph.cc.
{
  _graph.verify();
  operations().iterate([](const onert::ir::OperationIndex &, const onert::ir::IOperation &op) {
    try
    {
      UNUSED_RELEASE(dynamic_cast<const onert::ir::train::ITrainableOperation &>(op));
    }
    catch (const std::bad_cast &)
    {
      std::runtime_error("TrainableGraph: " + op.name() + " is not a trainable operation");
    }
  });
}
References onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::IOperation::name(), operations(), UNUSED_RELEASE, and onert::ir::Graph::verify().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/train/TrainableGraph.h
runtime/onert/core/src/ir/train/TrainableGraph.cc