ONE - On-device Neural Engine: onert::backend::builtin::train::BackendContext Class Reference
onert::backend::builtin::train::BackendContext Class Reference
#include <BackendContext.h>
Public Member Functions
BackendContext (const backend::train::ITrainableBackend *backend, std::unique_ptr< backend::train::TrainableContextData > &&data, std::shared_ptr< backend::train::ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< TensorBuilder > tensor_builder=nullptr, std::shared_ptr< KernelGenerator > kernel_gen=nullptr)
backend::ITensorRegistry * genTensors () override
backend::train::ITensorRegistry * genTrainingTensors () override
backend::train::FunctionMap genKernels () override
std::shared_ptr< ExternalContext > external_context ()
Public Member Functions inherited from onert::backend::train::TrainableBackendContext
TrainableBackendContext (const ITrainableBackend *backend, std::unique_ptr< TrainableContextData > &&tdata, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~TrainableBackendContext ()=default
const ir::train::TrainableGraph * trainable_graph () const
const TrainableContextData * data () const
const ITrainableBackend * backend () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
std::shared_ptr< ITensorRegistry > tensor_registry ()
Data Fields
std::shared_ptr< KernelGenerator > kernel_gen
Additional Inherited Members
Protected Attributes inherited from onert::backend::train::TrainableBackendContext
std::unique_ptr< TrainableContextData > _tdata
std::shared_ptr< ITensorRegistry > _tensor_registry
Detailed Description
Definition at line 35 of file BackendContext.h.
Constructor & Destructor Documentation
BackendContext()
onert::backend::builtin::train::BackendContext::BackendContext (const backend::train::ITrainableBackend * backend, std::unique_ptr< backend::train::TrainableContextData > && data, std::shared_ptr< backend::train::ITensorRegistry > tensor_registry = nullptr, std::shared_ptr< TensorBuilder > tensor_builder = nullptr, std::shared_ptr< KernelGenerator > kernel_gen = nullptr) inline
Definition at line 38 of file BackendContext.h.
    : backend::train::TrainableBackendContext(backend, std::move(data), tensor_registry),
      kernel_gen{kernel_gen}, _external_context(new ExternalContext),
      _tensor_builder{tensor_builder}
  {
  }
Member Function Documentation
external_context()
std::shared_ptr< ExternalContext > onert::backend::builtin::train::BackendContext::external_context () inline
Definition at line 55 of file BackendContext.h.
{ return _external_context; }
genKernels()
backend::train::FunctionMap onert::backend::builtin::train::BackendContext::genKernels () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 46 of file BackendContext.cc.
{
  backend::train::FunctionMap ret;
  for (auto &&op_ind : _tdata->op_order)
  {
    auto tn_seq = kernel_gen->generate(op_ind);
    ret.emplace_back(op_ind, std::move(tn_seq));
  }
  trainable_graph()->operands().iterate(
    [&](const ir::OperandIndex &ind, const ir::Operand &operand) {
      if (!external_operands().contains(ind) && operand.isConstant())
      {
        throw std::runtime_error(
          "BackendContext: builtin backend does not support updatable weights yet");
      }
    });
  // TODO Enable prepare()
  // for (auto &&it : ret)
  // {
  //   auto &fn_seq = it.second;
  //   fn_seq->iterate([&](exec::IFunction &ifunc) { ifunc.prepare(); });
  // }
  return ret;
}
References onert::backend::train::TrainableBackendContext::_tdata, onert::backend::train::TrainableBackendContext::external_operands(), onert::ir::Operand::isConstant(), onert::util::ObjectManager< Index, Object >::iterate(), kernel_gen, onert::ir::train::TrainableGraph::operands(), and onert::backend::train::TrainableBackendContext::trainable_graph().
genTensors()
backend::ITensorRegistry * onert::backend::builtin::train::BackendContext::genTensors () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 31 of file BackendContext.cc.
{
  // For now, there is no need to generate tensors for forwarding.
  // builtin train backend handles 3 operators: `Permute`, `IF`, `WHILE`.
  // `Permute`: Tensor generation is not required.
  // `IF`, `WHILE`: Not supported yet
  return tensor_registry().get();
}
References onert::backend::train::TrainableBackendContext::tensor_registry().
genTrainingTensors()
backend::train::ITensorRegistry * onert::backend::builtin::train::BackendContext::genTrainingTensors () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 40 of file BackendContext.cc.
{
  // For now, there is no need to generate tensors for backwarding.
  return tensor_registry().get();
}
References onert::backend::train::TrainableBackendContext::tensor_registry().
Field Documentation
kernel_gen
std::shared_ptr<KernelGenerator> onert::backend::builtin::train::BackendContext::kernel_gen
Definition at line 59 of file BackendContext.h.
Referenced by genKernels().
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/train/BackendContext.h
runtime/onert/core/src/backend/builtin/train/BackendContext.cc