ONE - On-device Neural Engine: tflinspect::DumpConv2DWeight Class Reference
tflinspect::DumpConv2DWeight Class Reference final
#include <Dump.h>
Public Member Functions
DumpConv2DWeight ()=default
void run (std::ostream &os, const tflite::Model *model)
Public Member Functions inherited from tflinspect::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const tflite::Model *model)=0
Detailed Description
Definition at line 45 of file Dump.h.
Constructor & Destructor Documentation
DumpConv2DWeight()
tflinspect::DumpConv2DWeight::DumpConv2DWeight () default
Member Function Documentation
run()
void tflinspect::DumpConv2DWeight::run (std::ostream & os, const tflite::Model * model) virtual
Implements tflinspect::DumpInterface.
Definition at line 96 of file Dump.cpp.
{
  tflinspect::Reader reader(model);
  const uint32_t subgraph_size = reader.num_subgraph();
  for (uint32_t g = 0; g < subgraph_size; g++)
  {
    reader.select_subgraph(g);
    auto ops = reader.operators();
    // dump Conv2D, DepthwiseConv2D and its weight input operator
    for (uint32_t i = 0; i < ops->Length(); ++i)
    {
      const auto op = ops->Get(i);
      auto bc = reader.builtin_code(op);
      if (bc == tflite::BuiltinOperator_CONV_2D || bc == tflite::BuiltinOperator_DEPTHWISE_CONV_2D)
      {
        const std::vector<int32_t> &inputs = tflinspect::as_index_vector(op->inputs());
        if (inputs.size() < 2)
        {
          throw std::runtime_error("Operator has invalid input");
        }
        auto weight_input = inputs[1]; // Tensor ID of weight input
        const auto op_weight = operator_match_output(reader, weight_input);
        const auto buffer_size = tensor_buffer_size(reader, weight_input);
        std::string weight_op_name = "?";
        if (op_weight == nullptr && buffer_size > 0)
        {
          weight_op_name = "CONST";
        }
        else if (op_weight != nullptr)
        {
          weight_op_name = reader.opcode_name(op_weight);
        }
        auto op_name = reader.opcode_name(op);
        os << op_name << "," << weight_op_name << std::endl;
      }
    }
  }
}
References tflinspect::as_index_vector(), tflinspect::Reader::builtin_code(), tflinspect::Reader::num_subgraph(), tflinspect::Reader::opcode_name(), tflinspect::Reader::operators(), and tflinspect::Reader::select_subgraph().
The documentation for this class was generated from the following files:
compiler/tfl-inspect/src/Dump.h
compiler/tfl-inspect/src/Dump.cpp