ONE - On-device Neural Engine: coco::BinaryOp Class Reference
coco::BinaryOp Class Reference
Op with two arguments.
#include <Op.h>
Public Member Functions
BinaryOp ()
BinaryOp (const BinaryOp &)=delete
BinaryOp (BinaryOp &&)=delete
virtual ~BinaryOp ()=default
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const final
Return a set of object(s) used during execution.
Op * left (void) const
void left (Op *op)
Op * right (void) const
void right (Op *op)
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Detailed Description
Op with two arguments.
Definition at line 213 of file Op.h.
Constructor & Destructor Documentation
BinaryOp() [1/3]
coco::BinaryOp::BinaryOp () explicit
Definition at line 100 of file Op.cpp.
                   : _left{this}, _right{this}
{
  // DO NOTHING
}
BinaryOp() [2/3]
coco::BinaryOp::BinaryOp (const BinaryOp &) delete
BinaryOp() [3/3]
coco::BinaryOp::BinaryOp (BinaryOp &&) delete
~BinaryOp()
virtual coco::BinaryOp::~BinaryOp () virtual default
Member Function Documentation
arg()
Op * coco::BinaryOp::arg (uint32_t n) const final virtual
Return N-th argument.
Note
The behavior of arg(n) is defined only when n < artiy()
Implements coco::Op.
Definition at line 111 of file Op.cpp.
{
  assert(n < arity());
  return (n == 0) ? left() : right();
}
References arity(), left(), and right().
arity()
uint32_t coco::BinaryOp::arity (void) const final virtual
Return the number of arguments (# of child Ops)
Implements coco::Op.
Definition at line 105 of file Op.cpp.
{
  // There are two arguments
  return 2;
}
Referenced by arg().
left() [1/2]
void coco::BinaryOp::left (Op * op) inline
Definition at line 233 of file Op.h.
{ _left.child(op); }
References coco::Part::child().
left() [2/2]
Op * coco::BinaryOp::left (void) const inline
Definition at line 232 of file Op.h.
{ return _left.child(); }
References coco::Part::child().
Referenced by arg(), tflimport::DivGraphBuilder::build(), tflimport::SubGraphBuilder::build(), uses(), and OpPrinter::visit().
right() [1/2]
void coco::BinaryOp::right (Op * op) inline
Definition at line 237 of file Op.h.
{ _right.child(op); }
References coco::Part::child().
right() [2/2]
Op * coco::BinaryOp::right (void) const inline
Definition at line 236 of file Op.h.
{ return _right.child(); }
References coco::Part::child().
Referenced by arg(), uses(), and OpPrinter::visit().
uses()
std::set< Object * > coco::BinaryOp::uses (void) const final virtual
Return a set of object(s) used during execution.
NOTE There is no 'def' method as Op is not allowed to define a new object
Implements coco::Op.
Definition at line 118 of file Op.cpp.
{
  std::set<Object *> res;
  if (auto l = left())
  {
    for (auto obj : l->uses())
    {
      res.insert(obj);
    }
  }
  if (auto r = right())
  {
    for (auto obj : r->uses())
    {
      res.insert(obj);
    }
  }
  return res;
}
References left(), and right().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Op.h
compiler/coco/core/src/IR/Op.cpp