ONE - On-device Neural Engine: onert::backend::train::optimizer::SGD Class Reference
onert::backend::train::optimizer::SGD Class Reference
SGD optimizer.
#include <SGD.h>
Data Structures
struct Property
Public Types
using UpdateFactors = exec::train::optimizer::UpdateFactors
Public Member Functions
SGD ()
SGD (const Property &props)
SGD (double lr)
SGD (const Property &props, double lr)
std::string name () const override
Get the name of optimizer.
double getLearningRate (uint32_t iteration=0) const override
Get the Learning Rate.
virtual uint32_t getVarCount () const override
Get the number of optimizer variables s.
void applyGradient (const UpdateFactors &factors) const override
Apply gradient to a trainable tensor.
Public Member Functions inherited from onert::exec::train::optimizer::Optimizer
virtual ~Optimizer ()=default
Detailed Description
SGD optimizer.
Definition at line 35 of file SGD.h.
Member Typedef Documentation
UpdateFactors
using onert::backend::train::optimizer::SGD::UpdateFactors = exec::train::optimizer::UpdateFactors
Definition at line 38 of file SGD.h.
Constructor & Destructor Documentation
SGD() [1/4]
onert::backend::train::optimizer::SGD::SGD () inline explicit
Definition at line 48 of file SGD.h.
: _props{}, _learning_rate{0.01} {}
SGD() [2/4]
onert::backend::train::optimizer::SGD::SGD (const Property & props) inline explicit
Definition at line 49 of file SGD.h.
: _props{props}, _learning_rate{0.01} {}
SGD() [3/4]
onert::backend::train::optimizer::SGD::SGD (double lr) inline explicit
Definition at line 50 of file SGD.h.
: _props{}, _learning_rate{lr} {}
SGD() [4/4]
onert::backend::train::optimizer::SGD::SGD (const Property & props, double lr) inline explicit
Definition at line 51 of file SGD.h.
: _props{props}, _learning_rate{lr} {}
Member Function Documentation
applyGradient()
void onert::backend::train::optimizer::SGD::applyGradient (const UpdateFactors & factors) const override virtual
Apply gradient to a trainable tensor.
Parameters
factors UpdateFactors to be used for applying gradient to a trainable tensor
Implements onert::exec::train::optimizer::Optimizer.
Definition at line 38 of file SGD.cc.
{
  const auto lr = getLearningRate(std::get<size_t>(factors));
  const auto &grad_tensor = std::get<const backend::IPortableTensor &>(factors);
  auto &trainable_tensor = std::get<backend::train::ITrainableTensor &>(factors);
  assert(trainable_tensor.data_type() == grad_tensor.data_type());
  if (trainable_tensor.getShape() != grad_tensor.getShape())
  {
    throw std::runtime_error("SGD: Invalid gradient tensor");
  }
  switch (grad_tensor.data_type())
  {
    case ir::DataType::FLOAT32:
      nnfw::cker::train::GradientDescent(
        ops::getShape(&trainable_tensor), ops::getBuffer<float>(&trainable_tensor),
        ops::getShape(&grad_tensor), ops::getBuffer<float>(&grad_tensor), lr);
      break;
    default:
      throw std::runtime_error("SGD: Not supported data type");
  }
}
References getLearningRate(), and nnfw::cker::train::GradientDescent().
getLearningRate()
double onert::backend::train::optimizer::SGD::getLearningRate (uint32_t iteration = 0) const override virtual
Get the Learning Rate.
Parameters
iteration The number of training steps
Returns
Learning rate
Implements onert::exec::train::optimizer::Optimizer.
Definition at line 32 of file SGD.cc.
{
  // TODO Use iteration, momentum, and nesterov
  return _learning_rate;
}
Referenced by applyGradient().
getVarCount()
virtual uint32_t onert::backend::train::optimizer::SGD::getVarCount () const inline override virtual
Get the number of optimizer variables s.
Returns
The number of optimizer variables
Implements onert::exec::train::optimizer::Optimizer.
Definition at line 74 of file SGD.h.
{ return 0; };
name()
std::string onert::backend::train::optimizer::SGD::name () const inline override virtual
Get the name of optimizer.
Returns
The name of optimizer
Reimplemented from onert::exec::train::optimizer::Optimizer.
Definition at line 59 of file SGD.h.
{ return std::string{"SGD"}; }
The documentation for this class was generated from the following files:
runtime/onert/backend/train/optimizer/SGD.h
runtime/onert/backend/train/optimizer/SGD.cc