ONE - On-device Neural Engine: onert::exec::Execution Class Reference
onert::exec::Execution Class Reference
Class to define execution instance to collect input/output information for inference and prepare executor run (TODO)
#include <Execution.h>
Public Member Functions
Execution (const std::shared_ptr< IExecutors > &executors)
Construct a new Execution object.
const ir::Graph & primary_subgraph () const
Returns primary graph object.
void changeInputShape (const ir::IOIndex &index, const ir::Shape &new_shape)
Change input shape.
void setInput (const ir::IOIndex &index, const void *buffer, size_t length)
Set input data's information.
void setInput (const ir::IOIndex &index, const ir::Shape &shape, const void *buffer, size_t length)
Set input data's information, especially to specify unknown dimensions on model build time.
void setOutput (const ir::IOIndex &index, void *buffer, size_t length)
Set output data's information.
void setOutput (const ir::IOIndex &index, const ir::Shape &shape, void *buffer, size_t length)
Set output data's information, especially to specify unknown dimensions on model build time.
void setInputLayout (const ir::IOIndex &index, ir::Layout layout)
Set input data's data format.
void setOutputLayout (const ir::IOIndex &index, ir::Layout layout)
Set output data's data format.
void setInputType (const ir::IOIndex &index, const ir::TypeInfo &typeInfo)
Set input type information.
void setOutputType (const ir::IOIndex &index, const ir::TypeInfo &typeInfo)
Set output type information.
void execute ()
Execution.
void startExecute (void)
Start asynchronous execution.
void waitFinish (void)
Return when execution is finished.
bool isFinished (void) const
Check execution is finished.
void train (uint32_t training_step)
Train.
float getLoss (const ir::IOIndex &ind)
Get loss.
void iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> &fn) const
Iterate trainable tensors.
ir::Shape getInputShape (ir::IOIndex ind) const
ir::Shape getOutputShape (ir::IOIndex ind) const
size_t getInputTotalSize (ir::IOIndex ind) const
size_t getOutputTotalSize (ir::IOIndex ind) const
Detailed Description
Class to define execution instance to collect input/output information for inference and prepare executor run (TODO)
Definition at line 42 of file Execution.h.
Constructor & Destructor Documentation
Execution()
onert::exec::Execution::Execution (const std::shared_ptr< IExecutors > & executors)
Construct a new Execution object.
Parameters
[in] executor Model executor
Definition at line 28 of file Execution.cc.
                                                               : _executors{executors}
{
  assert(executors != nullptr);
  assert(executors->entryExecutor() != nullptr);
  // Initialize I/O description
  _io_desc.inputs.resize(_executors->inputSize());
  for (uint32_t i = 0; i < _executors->inputSize(); ++i)
    _io_desc.inputs.at(i) = std::make_unique<InputDesc>(_executors->inputInfo(ir::IOIndex(i)));
  _io_desc.outputs.resize(_executors->outputSize());
  for (uint32_t i = 0; i < _executors->outputSize(); ++i)
    _io_desc.outputs.at(i) = std::make_unique<OutputDesc>(_executors->outputInfo(ir::IOIndex(i)));
  _io_desc.updated = false;
}
References onert::exec::IODescription::inputs, onert::exec::IODescription::outputs, and onert::exec::IODescription::updated.
Member Function Documentation
changeInputShape()
void onert::exec::Execution::changeInputShape (const ir::IOIndex & index, const ir::Shape & new_shape)
Change input shape.
Parameters
[in] index Input index
[in] new_shape shape to change
Definition at line 44 of file Execution.cc.
{
  // This will be used later to set input tensor dynamic
  // Note that 'compiled' model will not be updated with new_shape
  // but new_shape will change model input shape while 'running' the model
  auto &input_desc = _io_desc.inputs.at(index.value());
  if (new_shape != input_desc->info.shape())
  {
    input_desc->info.shape(new_shape);
    _io_desc.updated = true;
    VERBOSE(Execution) << "Model input shape will be changed at the start of execute()"
                       << "(index: " << index << ")" << std::endl;
  }
}
References onert::exec::IODescription::inputs, onert::exec::IODescription::updated, and VERBOSE.
Referenced by setInput().
execute()
void onert::exec::Execution::execute ()
Execution.
Note
It should be called after setting input and output buffer
Definition at line 129 of file Execution.cc.
{
  VERBOSE(Execution) << "Start execution" << std::endl;
  _executors->execute(_io_desc);
  finished = true;
  VERBOSE(Execution) << "Execution finished" << std::endl;
}
References VERBOSE.
Referenced by startExecute().
getInputShape()
ir::Shape onert::exec::Execution::getInputShape (ir::IOIndex ind) const
Definition at line 191 of file Execution.cc.
{
  return _io_desc.inputs.at(ind.value())->info.shape();
}
References onert::exec::IODescription::inputs, and onert::util::Index< T, DummyTag >::value().
getInputTotalSize()
size_t onert::exec::Execution::getInputTotalSize (ir::IOIndex ind) const
Definition at line 207 of file Execution.cc.
{
  // TODO Support dynamic shape
  return _io_desc.inputs.at(ind.value())->info.total_size();
}
References onert::exec::IODescription::inputs, and onert::util::Index< T, DummyTag >::value().
getLoss()
float onert::exec::Execution::getLoss (const ir::IOIndex & ind)
Get loss.
Note
It should be called after training
Parameters
[in] ind Output index
Returns
float Loss value
Definition at line 168 of file Execution.cc.
{
  auto execs = dynamic_cast<exec::train::TrainableExecutors *>(_executors.get());
  if (!execs)
  {
    throw std::runtime_error{"Supported only TrainableExecutors"};
  }
  return execs->getLoss(ind);
}
References onert::exec::train::TrainableExecutors::getLoss().
getOutputShape()
ir::Shape onert::exec::Execution::getOutputShape (ir::IOIndex ind) const
Definition at line 202 of file Execution.cc.
{
  return _io_desc.outputs.at(ind.value())->info.shape();
}
References onert::exec::IODescription::outputs, and onert::util::Index< T, DummyTag >::value().
getOutputTotalSize()
size_t onert::exec::Execution::getOutputTotalSize (ir::IOIndex ind) const
Definition at line 213 of file Execution.cc.
{
  return _io_desc.outputs.at(ind.value())->info.total_size();
}
References onert::exec::IODescription::outputs, and onert::util::Index< T, DummyTag >::value().
isFinished()
bool onert::exec::Execution::isFinished (void) const
Check execution is finished.
Returns
true if execution is finished, otherwise false
Definition at line 154 of file Execution.cc.
{ return finished; }
iterateTrainableTensors()
void onert::exec::Execution::iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> & fn) const
Iterate trainable tensors.
Note
It should be called after training
Parameters
[in] fn function to be called with OperandIndex and a pointer to ITrainableTensor
Definition at line 179 of file Execution.cc.
{
  auto execs = dynamic_cast<exec::train::TrainableExecutors *>(_executors.get());
  if (!execs)
  {
    throw std::runtime_error{"Supported only TrainableExecutors"};
  }
  execs->iterateTrainableTensors(fn);
}
References onert::exec::train::TrainableExecutors::iterateTrainableTensors().
primary_subgraph()
const ir::Graph & onert::exec::Execution::primary_subgraph () const inline
Returns primary graph object.
Returns
Graph object
Definition at line 57 of file Execution.h.
{ return entryExecutor()->graph(); }
References onert::exec::IExecutor::graph().
setInput() [1/2]
void onert::exec::Execution::setInput (const ir::IOIndex & index, const ir::Shape & shape, const void * buffer, size_t length)
Set input data's information, especially to specify unknown dimensions on model build time.
Parameters
[in] index Input index
[in] shape Input data's shape
[in] buffer Input data's buffer pointer
[in] length Input data's length
Definition at line 78 of file Execution.cc.
{
  changeInputShape(index, shape);
  setInput(index, buffer, length);
}
References changeInputShape(), and setInput().
Referenced by setInput().
setInput() [2/2]
void onert::exec::Execution::setInput (const ir::IOIndex & index, const void * buffer, size_t length)
Set input data's information.
Parameters
[in] index Input index
[in] buffer Input data's buffer pointer
[in] length Input data's length
Definition at line 61 of file Execution.cc.
{
  // TODO handle when (!buffer && length != 0) : setting the input as an optional tensor
  // check if size enough for input is passed
  // if input_shape_sig is set, input_shape_sig overrides shape in info
  // note: input_shape_sig contains shape passed by nnfw_set_input_tensorinfo()
  auto &input_desc = _io_desc.inputs.at(index.value());
  if (length < input_desc->info.total_size())
  {
    throw std::runtime_error{"Too small length"};
  }
  input_desc->buffer = buffer;
  input_desc->size = length;
}
References info, and onert::exec::IODescription::inputs.
setInputLayout()
void onert::exec::Execution::setInputLayout (const ir::IOIndex & index, ir::Layout layout)
Set input data's data format.
Parameters
[in] index Input index
[in] layout Input data's data format
Definition at line 107 of file Execution.cc.
{
  _io_desc.inputs.at(index.value())->layout = layout;
}
References onert::exec::IODescription::inputs.
setInputType()
void onert::exec::Execution::setInputType (const ir::IOIndex & index, const ir::TypeInfo & typeInfo)
Set input type information.
Parameters
[in] index Input index
[in] typeInfo Input type information
Definition at line 117 of file Execution.cc.
{
  _io_desc.inputs.at(index.value())->info.typeInfo(typeInfo);
  _io_desc.updated = true;
}
References onert::exec::IODescription::inputs, and onert::exec::IODescription::updated.
setOutput() [1/2]
void onert::exec::Execution::setOutput (const ir::IOIndex & index, const ir::Shape & shape, void * buffer, size_t length)
Set output data's information, especially to specify unknown dimensions on model build time.
Parameters
[in] index Output index
[in] shape Output data's shape
[in] buffer Output data's buffer pointer
[in] length Output data's length
Definition at line 98 of file Execution.cc.
{
  auto &output_desc = _io_desc.outputs.at(index.value());
  output_desc->info.shape(shape);
  setOutput(index, buffer, length);
}
References onert::exec::IODescription::outputs, and setOutput().
setOutput() [2/2]
void onert::exec::Execution::setOutput (const ir::IOIndex & index, void * buffer, size_t length)
Set output data's information.
Parameters
[in] index Output index
[in] buffer Output data's buffer pointer
[in] length Output data's length
Definition at line 85 of file Execution.cc.
{
  auto &output_desc = _io_desc.outputs.at(index.value());
  // Check lenght when output shape is valid
  if (!_io_desc.updated && length < output_desc->info.total_size())
  {
    throw std::runtime_error{"Too small length"};
  }
  output_desc->buffer = buffer;
  output_desc->size = length;
}
References info, onert::exec::IODescription::outputs, and onert::exec::IODescription::updated.
Referenced by setOutput().
setOutputLayout()
void onert::exec::Execution::setOutputLayout (const ir::IOIndex & index, ir::Layout layout)
Set output data's data format.
Parameters
[in] index Output index
[in] layout Output data's data format
Definition at line 112 of file Execution.cc.
{
  _io_desc.outputs.at(index.value())->layout = layout;
}
References onert::exec::IODescription::outputs.
setOutputType()
void onert::exec::Execution::setOutputType (const ir::IOIndex & index, const ir::TypeInfo & typeInfo)
Set output type information.
Parameters
[in] index Output index
[in] typeInfo Output type information
Definition at line 123 of file Execution.cc.
{
  _io_desc.outputs.at(index.value())->info.typeInfo(typeInfo);
  _io_desc.updated = true;
}
References onert::exec::IODescription::outputs, and onert::exec::IODescription::updated.
startExecute()
void onert::exec::Execution::startExecute (void)
Start asynchronous execution.
Note
It returns after execution thread is started It should be called after setting input and output buffer
Definition at line 139 of file Execution.cc.
{
  VERBOSE(Execution) << "Create asynchronous execution thread" << std::endl;
  _exec_thread = std::make_unique<std::thread>(&Execution::execute, this);
}
References execute(), and VERBOSE.
train()
void onert::exec::Execution::train (uint32_t training_step)
Train.
Note
It should be called after setting input and output buffer
Parameters
training_step The number of iterations of the training process. In other words, the number of gradient update.
Definition at line 156 of file Execution.cc.
{
  auto execs = dynamic_cast<exec::train::TrainableExecutors *>(_executors.get());
  if (!execs)
  {
    throw std::runtime_error{"Supported only TrainableExecutors"};
  }
  execs->train(_io_desc, training_step);
  finished = true;
}
References onert::exec::train::TrainableExecutors::train().
waitFinish()
void onert::exec::Execution::waitFinish (void)
Return when execution is finished.
Note
It waits until execution is finished
Definition at line 146 of file Execution.cc.
{
  VERBOSE(Execution) << "Wait to finish execution" << std::endl;
  _exec_thread->join();
  finished = true;
}
References VERBOSE.
The documentation for this class was generated from the following files:
runtime/onert/core/include/exec/Execution.h
runtime/onert/core/src/exec/Execution.cc