ONE - On-device Neural Engine: onert::compiler::pass::OperandPass Class Reference
onert::compiler::pass::OperandPass Class Reference abstract
#include <OperandPass.h>
Public Member Functions
virtual ~OperandPass ()=default
std::string id () override=0
void run () override final
virtual void callback (const ir::OperandIndex &i, ir::Operand &o)=0
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Definition at line 38 of file OperandPass.h.
Constructor & Destructor Documentation
~OperandPass()
virtual onert::compiler::pass::OperandPass::~OperandPass () virtual default
Member Function Documentation
callback()
virtual void onert::compiler::pass::OperandPass::callback (const ir::OperandIndex & i, ir::Operand & o) pure virtual
Implemented in onert::compiler::pass::ConstantOutputPass, onert::compiler::pass::LoweredOperandPass, and onert::compiler::pass::PermutationInsertionPass.
Referenced by run().
id()
std::string onert::compiler::pass::OperandPass::id () override pure virtual
Implements onert::compiler::pass::Pass.
Implemented in onert::compiler::pass::ConstantOutputPass, onert::compiler::pass::PermutationInsertionPass, and onert::compiler::pass::LoweredOperandPass.
Pass()
onert::compiler::pass::Pass::Pass (ir::Graph & graph) inline
Definition at line 40 of file Pass.h.
: _graph{graph} {}
run()
void onert::compiler::pass::OperandPass::run () final override virtual
Implements onert::compiler::pass::Pass.
Definition at line 28 of file OperandPass.cc.
{
  _graph.operands().iterate(
    [&](const ir::OperandIndex &index, ir::Operand &object) { callback(index, object); });
}
References onert::compiler::pass::Pass::_graph, callback(), onert::util::ObjectManager< Index, Object >::iterate(), and onert::ir::Graph::operands().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/OperandPass.h
runtime/onert/core/src/compiler/pass/OperandPass.cc