ONE - On-device Neural Engine: luci::CircleShapeInferencePass Class Reference
luci::CircleShapeInferencePass Class Reference
Pass to infer shape of circle nodes.
#include <CircleShapeInferencePass.h>
Public Member Functions
virtual const char * name (void) const
bool run (luci::Module *m)
bool run (loco::Graph *graph)
Run the pass.
virtual bool run (luci::Module *)=0
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to infer shape of circle nodes.
Definition at line 30 of file CircleShapeInferencePass.h.
Member Function Documentation
name()
virtual const char * luci::CircleShapeInferencePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 33 of file CircleShapeInferencePass.h.
{ return "luci::CircleShapeInferencePass"; }
run() [1/2]
bool luci::CircleShapeInferencePass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 66 of file CircleShapeInferencePass.cpp.
{
  luci::sinf::Rule shape_infer_rule;
  bool changed = false;
  for (auto node : inference_candidates(g))
  {
    loco::TensorShape shape;
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    if (shape_infer_rule.infer(circle_node, shape) && !is_same_shape(circle_node, shape))
    {
      circle_node->rank(shape.rank());
      for (uint32_t i = 0; i < shape.rank(); ++i)
        circle_node->dim(i) = shape.dim(i);
      circle_node->shape_status(luci::ShapeStatus::VALID);
      changed = true;
    }
  }
  return changed;
}
References loco::TensorShape::dim(), luci::sinf::Rule::infer(), luci::inference_candidates(), loco::TensorShape::rank(), and luci::VALID.
run() [2/2]
bool luci::CircleShapeInferencePass::run (luci::Module * m) virtual
Implements luci::Pass.
Definition at line 53 of file CircleShapeInferencePass.cpp.
{
  bool changed = false;
  for (size_t g = 0; g < m->size(); ++g)
  {
    if (run(m->graph(g)))
      changed = true;
  }
  return changed;
}
References m, and run().
Referenced by run().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/CircleShapeInferencePass.h
compiler/luci/pass/src/CircleShapeInferencePass.cpp