ONE - On-device Neural Engine: onert::backend::train::LayerScopeTensorIndex Class Reference
onert::backend::train::LayerScopeTensorIndex Class Reference
#include <LayerScopeTensorIndex.h>
Public Member Functions
LayerScopeTensorIndex (const ir::OperationIndex &op_index, uint32_t sub_index)
const ir::OperationIndex & op_index () const
uint32_t sub_index () const
bool operator== (const LayerScopeTensorIndex &other) const
bool operator!= (const LayerScopeTensorIndex &other) const
Detailed Description
Definition at line 27 of file LayerScopeTensorIndex.h.
Constructor & Destructor Documentation
LayerScopeTensorIndex()
onert::backend::train::LayerScopeTensorIndex::LayerScopeTensorIndex (const ir::OperationIndex & op_index, uint32_t sub_index) inline
Definition at line 30 of file LayerScopeTensorIndex.h.
    : _op_index{op_index}, _sub_index{sub_index}
  {
    assert(op_index.valid());
  }
References op_index(), and onert::util::Index< T, DummyTag >::valid().
Member Function Documentation
op_index()
const ir::OperationIndex & onert::backend::train::LayerScopeTensorIndex::op_index () const inline
Definition at line 37 of file LayerScopeTensorIndex.h.
{ return _op_index; }
Referenced by LayerScopeTensorIndex(), onert::backend::train::operator<<(), and operator==().
operator!=()
bool onert::backend::train::LayerScopeTensorIndex::operator!= (const LayerScopeTensorIndex & other) const inline
Definition at line 44 of file LayerScopeTensorIndex.h.
{ return !(*this == other); }
operator==()
bool onert::backend::train::LayerScopeTensorIndex::operator== (const LayerScopeTensorIndex & other) const inline
Definition at line 40 of file LayerScopeTensorIndex.h.
  {
    return _op_index == other.op_index() && _sub_index == other.sub_index();
  }
References op_index(), and sub_index().
sub_index()
uint32_t onert::backend::train::LayerScopeTensorIndex::sub_index () const inline
Definition at line 38 of file LayerScopeTensorIndex.h.
{ return _sub_index; }
Referenced by onert::backend::train::operator<<(), and operator==().
The documentation for this class was generated from the following file:
runtime/onert/backend/train/LayerScopeTensorIndex.h