ONE - On-device Neural Engine: enco::SubnetStructBuilder Class Reference
enco::SubnetStructBuilder Class Reference
#include <Subnet.h>
Public Member Functions
std::unique_ptr< SubnetStruct > build (const ANNBinder *binder) const
void expr (const ann::Operand *oper, const std::string &base, const std::string &size)
Detailed Description
Definition at line 47 of file Subnet.h.
Member Function Documentation
build()
std::unique_ptr< SubnetStruct > enco::SubnetStructBuilder::build (const ANNBinder * binder) const
Definition at line 320 of file Subnet.cpp.
{
  auto res = make_unique<SubnetStructImpl>();
  auto mname = res->model();
  auto cname = res->compilation();
  res->def()->append("ANeuralNetworksModel *", mname, ";");
  res->def()->append("ANeuralNetworksCompilation *", cname, ";");
  res->ctor()->append("ANeuralNetworksModel_create(&", mname, ");");
  res->dtor()->append("ANeuralNetworksModel_free(", mname, ");");
  binder->module()->operand()->each([&](const ann::OperandID &id, const ann::Operand *info) {
    // TODO Remove dynamic cast
    if (auto scalar = dynamic_cast<const ann::ScalarOperand *>(info))
    {
      res->ctor() << ScalarOperandDecl{mname, scalar->dtype()};
    }
    else if (auto tensor = dynamic_cast<const ann::TensorOperand *>(info))
    {
      res->ctor() << TensorOperandDecl{mname, tensor->dtype(), tensor->shape()};
    }
    else
    {
      throw std::runtime_error{"Unsupported"};
    }
    if (_weighted.find(info) != _weighted.end())
    {
      const auto &base_exp = _base_exprs.at(info);
      const auto &size_exp = _size_exprs.at(info);
      res->ctor() << WeightDecl{mname, id, base_exp, size_exp};
    }
  });
  for (unsigned n = 0; n < binder->module()->operation()->count(); ++n)
  {
    auto op = binder->module()->operation()->at(n);
    res->ctor() << OperationDecl{mname, op};
  }
  // Emit ANeuralNetworksModel_identifyInputsAndOutputs call
  res->ctor() << ArgumentDecl{mname, binder};
  // Emit ANeuralNetworksModel_finish call
  res->ctor()->append("ANeuralNetworksModel_finish(", mname, ");");
  // Create compilation
  res->ctor()->append("ANeuralNetworksCompilation_create(", mname, ", &", cname, ");");
  res->dtor()->append("ANeuralNetworksCompilation_free(", cname, ");");
  // Finalize compilation
  res->ctor()->append("ANeuralNetworksCompilation_finish(", cname, ");");
  return res;
}
References ann::OperandInventory::each(), info, ANNBinder::module(), and ann::Module::operand().
Referenced by enco::CppCode::dump().
expr()
void enco::SubnetStructBuilder::expr (const ann::Operand * oper, const std::string & base, const std::string & size) inline
Definition at line 53 of file Subnet.h.
  {
    _weighted.insert(oper);
    _base_exprs[oper] = base;
    _size_exprs[oper] = size;
  }
Referenced by enco::CppCode::dump().
The documentation for this class was generated from the following files:
compiler/enco/core/src/CppGen/Subnet.h
compiler/enco/core/src/CppGen/Subnet.cpp