ONE - On-device Neural Engine: onert::backend::gpu_cl::operand::ICLTensor Class Reference
onert::backend::gpu_cl::operand::ICLTensor Class Reference abstract
#include <ICLTensor.h>
Public Member Functions
ICLTensor ()=default
ICLTensor (const ICLTensor &)=delete
ICLTensor & operator= (const ICLTensor &)=delete
ICLTensor (ICLTensor &&)=default
ICLTensor & operator= (ICLTensor &&)=default
ICLTensor (size_t rank, TensorType type, tflite::gpu::BHWC shape, tflite::gpu::TensorDescriptor desc)
uint8_t * buffer () const final
size_t total_size () const final
size_t calcOffset (const ir::Coordinates &) const final
ir::Layout layout () const final
ir::DataType data_type () const final
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
ir::Shape getShape () const override
Get ir::Shape of tensor.
bool has_padding () const override
void access (const std::function< void(ITensor &tensor)> &fn) final
bool needMemoryMap () const final
void enqueueWriteBuffer (const void *ptr, bool blocking=true) final
void enqueueReadBuffer (void *ptr, bool blocking=true) final
void writeConvertInit (tflite::gpu::TensorObjectConverterBuilder *converter_builder, std::shared_ptr< tflite::gpu::cl::Environment > environment)
void readConvertInit (tflite::gpu::TensorObjectConverterBuilder *converter_builder, std::shared_ptr< tflite::gpu::cl::Environment > environment)
TensorType get_type ()
TensorType set_type (TensorType type)
const TensorInfo get_info ()
virtual const tflite::gpu::cl::Tensor * handle () const =0
virtual tflite::gpu::cl::Tensor * handle ()=0
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Protected Attributes
size_t _rank
TensorType _type
TensorInfo _info
tflite::gpu::cl::CLMemory _cl_memory
std::shared_ptr< tflite::gpu::cl::Environment > _environment
std::unique_ptr< tflite::gpu::TensorObjectConverter > _converter_to
std::unique_ptr< tflite::gpu::TensorObjectConverter > _converter_from
Detailed Description
Definition at line 46 of file ICLTensor.h.
Constructor & Destructor Documentation
ICLTensor() [1/4]
onert::backend::gpu_cl::operand::ICLTensor::ICLTensor () default
ICLTensor() [2/4]
onert::backend::gpu_cl::operand::ICLTensor::ICLTensor (const ICLTensor &) delete
ICLTensor() [3/4]
onert::backend::gpu_cl::operand::ICLTensor::ICLTensor (ICLTensor &&) default
ICLTensor() [4/4]
onert::backend::gpu_cl::operand::ICLTensor::ICLTensor (size_t rank, TensorType type, tflite::gpu::BHWC shape, tflite::gpu::TensorDescriptor desc) inline
Definition at line 55 of file ICLTensor.h.
    : _rank{rank}, _type(type), _info{shape, desc}
  {
  }
Member Function Documentation
access()
void onert::backend::gpu_cl::operand::ICLTensor::access (const std::function< void(ITensor &tensor)> & fn) final virtual
Implements onert::backend::ITensor.
Definition at line 38 of file ICLTensor.cc.
{
  if (total_size() == 0)
    return;
  fn(*this);
}
References total_size().
buffer()
uint8_t * onert::backend::gpu_cl::operand::ICLTensor::buffer () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 62 of file ICLTensor.h.
{ return reinterpret_cast<uint8_t *>(handle()->GetMemoryPtr()); }
References handle().
calcOffset()
size_t onert::backend::gpu_cl::operand::ICLTensor::calcOffset (const ir::Coordinates &) const inline final virtual
Implements onert::backend::ITensor.
Definition at line 64 of file ICLTensor.h.
  {
    throw std::runtime_error("ICLTensor::calcOffset() is not supported.");
  }
data_scale()
float onert::backend::gpu_cl::operand::ICLTensor::data_scale () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 70 of file ICLTensor.h.
  {
    throw std::runtime_error("ICLTensor::data_scale() is not supported.");
  }
data_scales()
const std::vector< float > & onert::backend::gpu_cl::operand::ICLTensor::data_scales () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 78 of file ICLTensor.h.
  {
    throw std::runtime_error("ICLTensor::data_scales() is not supported.");
  }
data_type()
ir::DataType onert::backend::gpu_cl::operand::ICLTensor::data_type () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 69 of file ICLTensor.h.
{ return ir::DataType::FLOAT32; }
data_zero_point()
int32_t onert::backend::gpu_cl::operand::ICLTensor::data_zero_point () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 74 of file ICLTensor.h.
  {
    throw std::runtime_error("ICLTensor::data_zero_point() is not supported.");
  }
data_zero_points()
const std::vector< int32_t > & onert::backend::gpu_cl::operand::ICLTensor::data_zero_points () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 82 of file ICLTensor.h.
  {
    throw std::runtime_error("ICLTensor::data_zero_points() is not supported.");
  }
enqueueReadBuffer()
void onert::backend::gpu_cl::operand::ICLTensor::enqueueReadBuffer (void * ptr, bool blocking = true) final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 178 of file ICLTensor.cc.
{
  TensorObject input_obj;
  if (handle()->GetStorageType() == TensorStorageType::BUFFER)
  {
    input_obj = OpenClBuffer{handle()->GetMemoryPtr()};
  }
  else if (handle()->GetStorageType() == TensorStorageType::IMAGE_BUFFER)
  {
    input_obj = OpenClBuffer{handle()->GetMemoryPtrForWriting()};
  }
  else
  {
    input_obj = OpenClTexture{handle()->GetMemoryPtr()};
  }
  TensorObject permute_obj;
  if (ToObjectType(handle()->GetStorageType()) == ObjectType::OPENCL_TEXTURE)
  {
    permute_obj = OpenClTexture{_cl_memory.memory()};
  }
  else
  {
    permute_obj = OpenClBuffer{_cl_memory.memory()};
  }
  TensorObject output_obj =
    MakeCpuMemory(absl::MakeSpan(static_cast<float *>(ptr), _info._shape.DimensionsProduct()));
  if (!_converter_from->Convert(input_obj, permute_obj).ok())
  {
    throw std::runtime_error("Failed to change layout");
  }
  if (!_converter_to->Convert(permute_obj, output_obj).ok())
  {
    throw std::runtime_error("Failed to read cl buffer");
  }
  if (blocking && !_environment->queue()->WaitForCompletion().ok())
  {
    throw std::runtime_error("Failed to WaitForCompletion");
  }
}
References _cl_memory, _converter_from, _converter_to, _environment, _info, onert::backend::gpu_cl::operand::TensorInfo::_shape, and handle().
enqueueWriteBuffer()
void onert::backend::gpu_cl::operand::ICLTensor::enqueueWriteBuffer (const void * ptr, bool blocking = true) final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 132 of file ICLTensor.cc.
{
  TensorObject input_obj = MakeReadableCpuMemory(
    absl::MakeSpan(static_cast<const float *>(ptr), _info._shape.DimensionsProduct()));
  TensorObject output_obj;
  TensorObject permute_obj;
  if (ToObjectType(handle()->GetStorageType()) == ObjectType::OPENCL_TEXTURE)
  {
    permute_obj = OpenClTexture{_cl_memory.memory()};
  }
  else
  {
    permute_obj = OpenClBuffer{_cl_memory.memory()};
  }
  if (handle()->GetStorageType() == TensorStorageType::BUFFER)
  {
    output_obj = OpenClBuffer{handle()->GetMemoryPtr()};
  }
  else if (handle()->GetStorageType() == TensorStorageType::IMAGE_BUFFER)
  {
    output_obj = OpenClBuffer{handle()->GetMemoryPtrForWriting()};
  }
  else
  {
    output_obj = OpenClTexture{handle()->GetMemoryPtr()};
  }
  if (!_converter_to->Convert(input_obj, permute_obj).ok())
  {
    throw std::runtime_error("Failed to write cl buffer from cpu memory");
  }
  if (blocking && !_environment->queue()->WaitForCompletion().ok())
  {
    throw std::runtime_error("Failed to WaitForCompletion");
  }
  if (!_converter_from->Convert(permute_obj, output_obj).ok())
  {
    throw std::runtime_error("Failed to change layout");
  }
}
References _cl_memory, _converter_from, _converter_to, _environment, _info, onert::backend::gpu_cl::operand::TensorInfo::_shape, and handle().
get_info()
const TensorInfo onert::backend::gpu_cl::operand::ICLTensor::get_info () inline
Definition at line 118 of file ICLTensor.h.
{ return _info; }
References _info.
get_type()
TensorType onert::backend::gpu_cl::operand::ICLTensor::get_type () inline
Definition at line 116 of file ICLTensor.h.
{ return _type; }
References _type.
getShape()
ir::Shape onert::backend::gpu_cl::operand::ICLTensor::getShape () const inline override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 87 of file ICLTensor.h.
  {
    tflite::gpu::BHWC shape = _info._shape;
    switch (_rank)
    {
      case 1:
        return ir::Shape{shape.b};
      case 2:
        return ir::Shape{shape.b, shape.c};
      case 3:
        return ir::Shape{shape.b, shape.w, shape.c};
      case 4:
        return ir::Shape{shape.b, shape.h, shape.w, shape.c};
      default:
        break;
    }
    return ir::Shape{};
  }
References _info, _rank, and onert::backend::gpu_cl::operand::TensorInfo::_shape.
handle() [1/2]
virtual const tflite::gpu::cl::Tensor * onert::backend::gpu_cl::operand::ICLTensor::handle () const pure virtual
Implemented in onert::backend::gpu_cl::operand::CLTensor.
Referenced by buffer(), enqueueReadBuffer(), enqueueWriteBuffer(), readConvertInit(), and writeConvertInit().
handle() [2/2]
virtual tflite::gpu::cl::Tensor * onert::backend::gpu_cl::operand::ICLTensor::handle () pure virtual
Implemented in onert::backend::gpu_cl::operand::CLTensor.
has_padding()
bool onert::backend::gpu_cl::operand::ICLTensor::has_padding () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 105 of file ICLTensor.h.
{ return false; }
is_dynamic()
bool onert::backend::gpu_cl::operand::ICLTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 86 of file ICLTensor.h.
{ return false; }
layout()
ir::Layout onert::backend::gpu_cl::operand::ICLTensor::layout () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 68 of file ICLTensor.h.
{ return ir::Layout::NHWC; }
References onert::ir::NHWC.
needMemoryMap()
bool onert::backend::gpu_cl::operand::ICLTensor::needMemoryMap () const inline final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 107 of file ICLTensor.h.
{ return true; }
operator=() [1/2]
ICLTensor & onert::backend::gpu_cl::operand::ICLTensor::operator= (const ICLTensor &) delete
operator=() [2/2]
ICLTensor & onert::backend::gpu_cl::operand::ICLTensor::operator= (ICLTensor &&) default
readConvertInit()
void onert::backend::gpu_cl::operand::ICLTensor::readConvertInit (tflite::gpu::TensorObjectConverterBuilder * converter_builder, std::shared_ptr< tflite::gpu::cl::Environment > environment)
Definition at line 89 of file ICLTensor.cc.
{
  _environment = environment;
  TensorObjectDef input_def;
  input_def.dimensions.b = handle()->Batch();
  input_def.dimensions.h = handle()->Height();
  input_def.dimensions.w = handle()->Width();
  input_def.dimensions.c = handle()->Channels();
  input_def.object_def.data_layout = ToDataLayout(handle()->GetStorageType());
  input_def.object_def.data_type = handle()->GetDataType();
  input_def.object_def.object_type = ToObjectType(handle()->GetStorageType());
  input_def.object_def.user_provided = false;
  TensorObjectDef permute_def = input_def;
  permute_def.object_def.data_layout = DataLayout::BHWC;
  permute_def.object_def.data_type = DataType::FLOAT32;
  permute_def.object_def.user_provided = true;
  auto dims = permute_def.dimensions;
  const BHWC shape(dims.b, dims.h, dims.w, dims.c);
  const TensorDescriptor desc{
    permute_def.object_def.data_type,
    ToTensorStorageType(permute_def.object_def.object_type, permute_def.object_def.data_layout),
    Layout::BHWC};
  if (!AllocateTensorMemory(_environment->context(), shape, desc, &_cl_memory).ok())
  {
    throw std::runtime_error("Failed to AllocateTensorMemory");
  }
  TensorObjectDef output_def = permute_def;
  output_def.object_def.object_type = ObjectType::CPU_MEMORY;
  if (!converter_builder->MakeConverter(input_def, permute_def, &_converter_from).ok())
  {
    throw std::runtime_error("Failed to make converter_from");
  }
  if (!converter_builder->MakeConverter(permute_def, output_def, &_converter_to).ok())
  {
    throw std::runtime_error("Failed to make converter_to");
  }
}
References _cl_memory, _converter_from, _converter_to, _environment, and handle().
set_type()
TensorType onert::backend::gpu_cl::operand::ICLTensor::set_type (TensorType type) inline
Definition at line 117 of file ICLTensor.h.
{ return _type = type; }
References _type.
total_size()
size_t onert::backend::gpu_cl::operand::ICLTensor::total_size () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 63 of file ICLTensor.h.
{ return _info._shape.DimensionsProduct() * sizeof(float); }
References _info, and onert::backend::gpu_cl::operand::TensorInfo::_shape.
Referenced by access().
writeConvertInit()
void onert::backend::gpu_cl::operand::ICLTensor::writeConvertInit (tflite::gpu::TensorObjectConverterBuilder * converter_builder, std::shared_ptr< tflite::gpu::cl::Environment > environment)
Definition at line 46 of file ICLTensor.cc.
{
  _environment = environment;
  TensorObjectDef input_def;
  input_def.dimensions.b = handle()->Batch();
  input_def.dimensions.h = handle()->Height();
  input_def.dimensions.w = handle()->Width();
  input_def.dimensions.c = handle()->Channels();
  input_def.object_def.data_layout = DataLayout::BHWC;
  input_def.object_def.data_type = DataType::FLOAT32;
  input_def.object_def.object_type = ObjectType::CPU_MEMORY;
  input_def.object_def.user_provided = true;
  TensorObjectDef permute_def = input_def;
  permute_def.object_def.object_type = ToObjectType(handle()->GetStorageType());
  auto dims = permute_def.dimensions;
  const BHWC shape(dims.b, dims.h, dims.w, dims.c);
  const TensorDescriptor desc{
    permute_def.object_def.data_type,
    ToTensorStorageType(permute_def.object_def.object_type, permute_def.object_def.data_layout),
    Layout::BHWC};
  if (!AllocateTensorMemory(_environment->context(), shape, desc, &_cl_memory).ok())
  {
    throw std::runtime_error("Failed to AllocateTensorMemory");
  }
  TensorObjectDef output_def = permute_def;
  output_def.object_def.data_layout = ToDataLayout(handle()->GetStorageType());
  output_def.object_def.data_type = handle()->GetDataType();
  input_def.object_def.user_provided = false;
  if (!converter_builder->MakeConverter(input_def, permute_def, &_converter_to).ok())
  {
    throw std::runtime_error("Failed to make converter_to");
  }
  if (!converter_builder->MakeConverter(permute_def, output_def, &_converter_from).ok())
  {
    throw std::runtime_error("Failed to make converter_from");
  }
}
References _cl_memory, _converter_from, _converter_to, _environment, and handle().
Field Documentation
_cl_memory
tflite::gpu::cl::CLMemory onert::backend::gpu_cl::operand::ICLTensor::_cl_memory protected
Definition at line 129 of file ICLTensor.h.
Referenced by enqueueReadBuffer(), enqueueWriteBuffer(), readConvertInit(), and writeConvertInit().
_converter_from
std::unique_ptr<tflite::gpu::TensorObjectConverter> onert::backend::gpu_cl::operand::ICLTensor::_converter_from protected
Definition at line 132 of file ICLTensor.h.
Referenced by enqueueReadBuffer(), enqueueWriteBuffer(), readConvertInit(), and writeConvertInit().
_converter_to
std::unique_ptr<tflite::gpu::TensorObjectConverter> onert::backend::gpu_cl::operand::ICLTensor::_converter_to protected
Definition at line 131 of file ICLTensor.h.
Referenced by enqueueReadBuffer(), enqueueWriteBuffer(), readConvertInit(), and writeConvertInit().
_environment
std::shared_ptr<tflite::gpu::cl::Environment> onert::backend::gpu_cl::operand::ICLTensor::_environment protected
Definition at line 130 of file ICLTensor.h.
Referenced by enqueueReadBuffer(), enqueueWriteBuffer(), readConvertInit(), and writeConvertInit().
_info
TensorInfo onert::backend::gpu_cl::operand::ICLTensor::_info protected
Definition at line 128 of file ICLTensor.h.
Referenced by enqueueReadBuffer(), enqueueWriteBuffer(), get_info(), getShape(), and total_size().
_rank
size_t onert::backend::gpu_cl::operand::ICLTensor::_rank protected
Definition at line 126 of file ICLTensor.h.
Referenced by getShape().
_type
TensorType onert::backend::gpu_cl::operand::ICLTensor::_type protected
Definition at line 127 of file ICLTensor.h.
Referenced by get_type(), and set_type().
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/operand/ICLTensor.h
runtime/onert/backend/gpu_cl/operand/ICLTensor.cc