ONE - On-device Neural Engine: nnc::ArtifactGeneratorCppCode Class Reference
nnc::ArtifactGeneratorCppCode Class Reference
The ACL C++ artifact source code producer.
#include <ArtifactGeneratorCppCode.h>
Public Member Functions
ArtifactGeneratorCppCode (std::ostream &out)
void visit (const ArtifactLiteral *node) override
void visit (const ArtifactId *node) override
void visit (const ArtifactRef *node) override
void visit (const ArtifactDeref *node) override
void visit (const ArtifactVariable *node) override
void visit (const ArtifactFunctionCall *node) override
void visit (const ArtifactUnaryExpr *node) override
void visit (const ArtifactBinaryExpr *node) override
void visit (const ArtifactIndex *node) override
void visit (const ArtifactRet *node) override
void visit (const ArtifactBreak *node) override
void visit (const ArtifactCont *node) override
void visit (const ArtifactBlock *node) override
void visit (const ArtifactForLoop *node) override
void visit (const ArtifactIf *node) override
void visit (const ArtifactFunction *node) override
void visit (const ArtifactClass *node) override
void visit (const ArtifactClassVariable *node) override
void visit (const ArtifactClassFunction *node) override
void visit (const ArtifactModule *node) override
Public Member Functions inherited from nnc::IArtifactGenerator
virtual ~IArtifactGenerator ()=default
virtual void visit (const ArtifactLiteral *node)=0
virtual void visit (const ArtifactId *node)=0
virtual void visit (const ArtifactRef *node)=0
virtual void visit (const ArtifactDeref *node)=0
virtual void visit (const ArtifactVariable *node)=0
virtual void visit (const ArtifactFunctionCall *node)=0
virtual void visit (const ArtifactUnaryExpr *node)=0
virtual void visit (const ArtifactBinaryExpr *node)=0
virtual void visit (const ArtifactIndex *node)=0
virtual void visit (const ArtifactRet *node)=0
virtual void visit (const ArtifactBreak *node)=0
virtual void visit (const ArtifactCont *node)=0
virtual void visit (const ArtifactBlock *node)=0
virtual void visit (const ArtifactForLoop *node)=0
virtual void visit (const ArtifactIf *node)=0
virtual void visit (const ArtifactFunction *node)=0
virtual void visit (const ArtifactClass *node)=0
virtual void visit (const ArtifactClassVariable *node)=0
virtual void visit (const ArtifactClassFunction *node)=0
virtual void visit (const ArtifactModule *node)=0
Detailed Description
The ACL C++ artifact source code producer.
Definition at line 31 of file ArtifactGeneratorCppCode.h.
Constructor & Destructor Documentation
ArtifactGeneratorCppCode()
nnc::ArtifactGeneratorCppCode::ArtifactGeneratorCppCode (std::ostream & out) explicit
Definition at line 29 of file ArtifactGeneratorCppCode.cpp.
: _out(out) {}
Member Function Documentation
visit() [1/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactBinaryExpr * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 119 of file ArtifactGeneratorCppCode.cpp.
{
  static const char *bin_op_str[] = {"==", "!=", "<", "<=", ">",  ">=", "=", "+",
                                     "-",  "*",  "/", "+=", "-=", "*=", "/="};
  node->getLeft()->accept(this);
  _out << " " << bin_op_str[static_cast<int>(node->getOp())] << " ";
  node->getRight()->accept(this);
}
References nnc::ArtifactBinaryExpr::getLeft(), nnc::ArtifactBinaryExpr::getOp(), and nnc::ArtifactBinaryExpr::getRight().
visit() [2/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactBlock * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 146 of file ArtifactGeneratorCppCode.cpp.
{
  _out << " {" << endl;
  ++_ind;
  for (const auto &st : node->getStatements())
  {
    _out << _ind;
    st->accept(this);
    if (!st->isBlock())
      _out << ";" << endl;
  }
  --_ind;
  _out << _ind << "}" << endl;
}
References nnc::ArtifactBlock::getStatements().
visit() [3/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactBreak * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 142 of file ArtifactGeneratorCppCode.cpp.
{ _out << "break"; }
visit() [4/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactClass * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 204 of file ArtifactGeneratorCppCode.cpp.
{
  // Generate a public default constructor here.
  _out << node->name() << "::" << node->name() << "()";
  if (!node->privateVariables().empty())
  {
    _out << " : ";
    bool add_delim = false;
    for (const auto &v : node->privateVariables())
    {
      if (add_delim)
        _out << ",\n";
      v->accept(this);
      add_delim = true;
    }
  }
  // TODO add constructors of public variables
  node->getConstrBlock()->accept(this);
  _out << endl;
  // Then generate the other stuff.
  for (const auto &e : node->publicFunctions())
    e->accept(this);
  for (const auto &e : node->privateFunctions())
    e->accept(this);
}
References nnc::ArtifactBlock::accept(), nnc::ArtifactClass::getConstrBlock(), nnc::ArtifactNamed::name(), nnc::ArtifactClass::privateFunctions(), nnc::ArtifactClass::privateVariables(), and nnc::ArtifactClass::publicFunctions().
visit() [5/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactClassFunction * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 255 of file ArtifactGeneratorCppCode.cpp.
{
  _out << node->getRetTypeName();
  if (!node->getRetTypeName().empty())
    _out << " ";
  _out << node->owner()->name() << "::" << node->name() << "(";
  bool add_comma = false;
  for (const auto &p : node->getParameters())
  {
    if (add_comma)
      _out << ", ";
    p->accept(this);
    add_comma = true;
  }
  _out << ")";
  node->getBlock()->accept(this);
  _out << endl;
}
References nnc::ArtifactBlock::accept(), nnc::ArtifactFunction::getBlock(), nnc::ArtifactFunction::getParameters(), nnc::ArtifactFunction::getRetTypeName(), nnc::ArtifactNamed::name(), and nnc::ArtifactClassMember::owner().
visit() [6/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactClassVariable * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 238 of file ArtifactGeneratorCppCode.cpp.
{
  _out << node->name() << "(";
  bool add_comma = false;
  for (const auto &i : node->getInitializers())
  {
    if (add_comma)
      _out << ", ";
    i->accept(this);
    add_comma = true;
  }
  _out << ")";
}
References nnc::ArtifactVariable::getInitializers(), and nnc::ArtifactNamed::name().
visit() [7/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactCont * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 144 of file ArtifactGeneratorCppCode.cpp.
{ _out << "continue"; }
visit() [8/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactDeref * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 41 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "*";
  node->obj()->accept(this);
}
References nnc::ArtifactDeref::obj().
visit() [9/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactForLoop * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 164 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "for(";
  if (node->getInit())
    node->getInit()->accept(this);
  _out << "; ";
  if (node->getCond())
    node->getCond()->accept(this);
  _out << "; ";
  if (node->getIter())
    node->getIter()->accept(this);
  _out << ")";
  node->getBlock()->accept(this);
}
References nnc::ArtifactBlock::accept(), nnc::ArtifactForLoop::getBlock(), nnc::ArtifactForLoop::getCond(), nnc::ArtifactForLoop::getInit(), and nnc::ArtifactForLoop::getIter().
visit() [10/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactFunction * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 199 of file ArtifactGeneratorCppCode.cpp.
{
  // TODO implement this function
}
visit() [11/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactFunctionCall * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 76 of file ArtifactGeneratorCppCode.cpp.
{
  static const char *call_type_str[] = {".", "->", "::"};
  if (node->on())
  {
    node->on()->accept(this);
    _out << call_type_str[static_cast<int>(node->callType())];
  }
  _out << node->funcName();
  _out << "(";
  bool add_comma = false;
  for (const auto &par : node->paramList())
  {
    if (add_comma)
      _out << ", ";
    par->accept(this);
    add_comma = true;
  }
  _out << ")";
}
References nnc::ArtifactFunctionCall::callType(), nnc::ArtifactFunctionCall::funcName(), nnc::ArtifactFunctionCall::on(), and nnc::ArtifactFunctionCall::paramList().
visit() [12/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactId * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 33 of file ArtifactGeneratorCppCode.cpp.
{ _out << node->name(); }
References nnc::ArtifactId::name().
visit() [13/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactIf * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 185 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "if(";
  node->getCond()->accept(this);
  _out << ")";
  node->getBlock()->accept(this);
  if (!node->getElseBlock()->getStatements().empty())
  {
    _out << _ind << "else";
    node->getElseBlock()->accept(this);
  }
}
References nnc::ArtifactBlock::accept(), nnc::ArtifactIf::getBlock(), nnc::ArtifactIf::getCond(), nnc::ArtifactIf::getElseBlock(), and nnc::ArtifactBlock::getStatements().
visit() [14/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactIndex * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 128 of file ArtifactGeneratorCppCode.cpp.
{
  node->getExpr()->accept(this);
  _out << "[";
  node->getInd()->accept(this);
  _out << "]";
}
References nnc::ArtifactIndex::getExpr(), and nnc::ArtifactIndex::getInd().
visit() [15/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactLiteral * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 31 of file ArtifactGeneratorCppCode.cpp.
{ _out << node->getValue(); }
References nnc::ArtifactLiteral::getValue().
visit() [16/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactModule * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 279 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "#include \"" << node->name() << ".h\"" << endl << endl;
  for (const auto &i : node->sourceSysIncludes())
    _out << "#include <" << i << ">" << endl;
  if (!node->sourceSysIncludes().empty())
    _out << endl;
  for (const auto &i : node->sourceIncludes())
    _out << "#include \"" << i << "\"" << endl;
  if (!node->sourceIncludes().empty())
    _out << endl;
  _out.write(AclArtifactUtilities, sizeof(AclArtifactUtilities));
  _out << endl;
  for (const auto &e : node->entities())
    e->accept(this);
}
References nnc::ArtifactModule::entities(), nnc::ArtifactModule::name(), nnc::ArtifactModule::sourceIncludes(), and nnc::ArtifactModule::sourceSysIncludes().
visit() [17/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactRef * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 35 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "&";
  node->obj()->accept(this);
}
References nnc::ArtifactRef::obj().
visit() [18/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactRet * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 136 of file ArtifactGeneratorCppCode.cpp.
{
  _out << "return ";
  node->expr()->accept(this);
}
References nnc::ArtifactRet::expr().
visit() [19/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactUnaryExpr * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 102 of file ArtifactGeneratorCppCode.cpp.
{
  // The trailing space is intended in new and delete!
  static const char *un_op_str[] = {"++", "--", "new ", "delete ", "++", "--"};
  if (node->getOp() < ArtifactUnOp::postIncr)
  {
    _out << un_op_str[static_cast<int>(node->getOp())];
    node->getExpr()->accept(this);
  }
  else
  {
    node->getExpr()->accept(this);
    _out << un_op_str[static_cast<int>(node->getOp())];
  }
}
References nnc::ArtifactUnaryExpr::getExpr(), nnc::ArtifactUnaryExpr::getOp(), and nnc::postIncr.
visit() [20/20]
void nnc::ArtifactGeneratorCppCode::visit (const ArtifactVariable * node) override virtual
Implements nnc::IArtifactGenerator.
Definition at line 47 of file ArtifactGeneratorCppCode.cpp.
{
  _out << node->typeName() << " " << node->name();
  for (const auto &d : node->getDimensions())
  {
    _out << "[";
    d->accept(this);
    _out << "]";
  }
  if (!node->getInitializers().empty())
  {
    _out << "(";
    bool add_comma = false;
    for (const auto &i : node->getInitializers())
    {
      if (add_comma)
        _out << ", ";
      i->accept(this);
      add_comma = true;
    }
    _out << ")";
  }
}
References nnc::ArtifactVariable::getDimensions(), nnc::ArtifactVariable::getInitializers(), nnc::ArtifactNamed::name(), and nnc::ArtifactVariable::typeName().
The documentation for this class was generated from the following files:
compiler/nnc/backends/acl_soft_backend/ArtifactGeneratorCppCode.h
compiler/nnc/backends/acl_soft_backend/ArtifactGeneratorCppCode.cpp