ONE - On-device Neural Engine: luci_interpreter::kernels::DownsamplingConv2DKernel Class Reference
luci_interpreter::kernels::DownsamplingConv2DKernel Class Reference
#include <ConvolutionCommon.h>
Public Member Functions
DownsamplingConv2DKernel ()=delete
DownsamplingConv2DKernel (const circle::Operator *cur_op, BaseRuntimeGraph *runtime_graph)
const circle::Tensor * input () const
const circle::Tensor * filter () const
const circle::Tensor * bias () const
const circle::Tensor * output () const
BaseRuntimeGraph * runtime_graph () const
Detailed Description
Definition at line 38 of file ConvolutionCommon.h.
Constructor & Destructor Documentation
DownsamplingConv2DKernel() [1/2]
luci_interpreter::kernels::DownsamplingConv2DKernel::DownsamplingConv2DKernel () delete
DownsamplingConv2DKernel() [2/2]
luci_interpreter::kernels::DownsamplingConv2DKernel::DownsamplingConv2DKernel (const circle::Operator * cur_op, BaseRuntimeGraph * runtime_graph) inline explicit
Definition at line 43 of file ConvolutionCommon.h.
    : _runtime_graph(runtime_graph)
  {
    const auto input_index = cur_op->inputs()->operator[](0);
    const auto filter_index = cur_op->inputs()->operator[](1);
    const auto bias_index = cur_op->inputs()->operator[](2);
    const auto output_index = cur_op->outputs()->operator[](0);
    assert(input_index != -1);
    assert(filter_index != -1);
    assert(output_index != -1);
    _input_tensor = _runtime_graph->getCircleTensorByIndex(input_index);
    _filter_tensor = _runtime_graph->getCircleTensorByIndex(filter_index);
    _bias_tensor = _runtime_graph->getCircleTensorByIndex(bias_index);
    _output_tensor = _runtime_graph->getCircleTensorByIndex(output_index);
    assert(_input_tensor != nullptr);
    assert(_filter_tensor != nullptr);
  }
References luci_interpreter::RuntimeGraph::getCircleTensorByIndex().
Member Function Documentation
bias()
const circle::Tensor * luci_interpreter::kernels::DownsamplingConv2DKernel::bias () const inline
Definition at line 66 of file ConvolutionCommon.h.
{ return _bias_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::execute_kernel_CircleConv2D(), and luci_interpreter::execute_kernel_CircleDepthwiseConv2D().
filter()
const circle::Tensor * luci_interpreter::kernels::DownsamplingConv2DKernel::filter () const inline
Definition at line 65 of file ConvolutionCommon.h.
{ return _filter_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::execute_kernel_CircleConv2D(), and luci_interpreter::execute_kernel_CircleDepthwiseConv2D().
input()
const circle::Tensor * luci_interpreter::kernels::DownsamplingConv2DKernel::input () const inline
Definition at line 64 of file ConvolutionCommon.h.
{ return _input_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::execute_kernel_CircleConv2D(), and luci_interpreter::execute_kernel_CircleDepthwiseConv2D().
output()
const circle::Tensor * luci_interpreter::kernels::DownsamplingConv2DKernel::output () const inline
Definition at line 67 of file ConvolutionCommon.h.
{ return _output_tensor; }
Referenced by luci_interpreter::configure_kernel_CircleConv2D(), luci_interpreter::configure_kernel_CircleDepthwiseConv2D(), luci_interpreter::execute_kernel_CircleConv2D(), and luci_interpreter::execute_kernel_CircleDepthwiseConv2D().
runtime_graph()
BaseRuntimeGraph * luci_interpreter::kernels::DownsamplingConv2DKernel::runtime_graph () const inline
Definition at line 69 of file ConvolutionCommon.h.
{ return _runtime_graph; }
The documentation for this class was generated from the following file:
onert-micro/luci-interpreter/src/kernels/ConvolutionCommon.h