ONE - On-device Neural Engine: exo::TensorTransposeConverter Class Reference
exo::TensorTransposeConverter Class Reference
Convert loco::TensorTranspose to locoex::TFLTranspose.
#include <TensorTransposeConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::TensorTranspose *origin) final
Converts loco::TensorTranspose to locoex::TFLTranspose.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::TensorTranspose >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::TensorTranspose *node)=0
Detailed Description
Convert loco::TensorTranspose to locoex::TFLTranspose.
Definition at line 30 of file TensorTransposeConverter.h.
Member Function Documentation
convert()
bool exo::TensorTransposeConverter::convert (loco::TensorTranspose * origin) final virtual
Converts loco::TensorTranspose to locoex::TFLTranspose.
Implements exo::CanonicalNodeConverter< loco::TensorTranspose >.
Definition at line 58 of file TensorTransposeConverter.cpp.
{
  auto *graph = origin->graph();
  auto tfl_transpose = graph->nodes()->create<locoex::TFLTranspose>();
  {
    // validation
    {
      assert(origin->input() != nullptr);
      auto input_rank = loco::shape_get(origin->input()).as<loco::TensorShape>().rank();
      if (input_rank != origin->perm()->size())
        INTERNAL_EXN_V("perm size should be same with input rank",
                       oops::to_uint32(origin->perm()->size()));
      validate_perm(origin);
    }
    tfl_transpose->a(origin->input());
    // perm : set TFLConst
    auto perm_const = graph->nodes()->create<locoex::TFLConst>();
    {
      perm_const->dtype(loco::DataType::S32);
      perm_const->rank(1);
      perm_const->dim(0) = origin->perm()->size();
      perm_const->size<loco::DataType::S32>(origin->perm()->size());
      // add perm values into perm TFLConst
      for (loco::TensorAxis x = 0; x < origin->perm()->size(); x++)
      {
        perm_const->at<loco::DataType::S32>(x) = origin->perm()->axis(x);
      }
    }
    tfl_transpose->perm(perm_const);
  }
  // replace canonical node
  loco::replace(origin).with(tfl_transpose);
  origin->input(nullptr);
  return true;
}
References loco::NodeShape::as(), loco::TensorTranspose::Perm::axis(), loco::Node::graph(), loco::TensorTranspose::input(), INTERNAL_EXN_V, loco::TensorTranspose::perm(), loco::replace(), loco::shape_get(), loco::TensorTranspose::Perm::size(), oops::to_uint32(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::TensorTransposeConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::TensorTranspose >.
Definition at line 33 of file TensorTransposeConverter.h.
{ return "exo::TensorTransposeConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/TensorTransposeConverter.h
compiler/exo/src/Conversion/TensorTransposeConverter.cpp