ONE - On-device Neural Engine: onert::compiler::train::TrainingInfo Class Reference
onert::compiler::train::TrainingInfo Class Reference
#include <TrainingInfo.h>
Public Member Functions
TrainingInfo ()
TrainingInfo (const TrainingInfo &obj)=default
TrainingInfo (TrainingInfo &&)=default
TrainingInfo & operator= (const TrainingInfo &)=default
TrainingInfo & operator= (TrainingInfo &&)=default
~TrainingInfo ()=default
uint32_t batchSize () const
void setBatchSize (const uint32_t batch_size)
const ir::train::LossInfo & lossInfo () const
void setLossInfo (const ir::train::LossInfo &loss_info)
const ir::train::OptimizerInfo & optimizerInfo () const
void setOptimizerInfo (const ir::train::OptimizerInfo &optimizer_info)
Detailed Description
Definition at line 33 of file TrainingInfo.h.
Constructor & Destructor Documentation
TrainingInfo() [1/3]
onert::compiler::train::TrainingInfo::TrainingInfo () inline
Definition at line 36 of file TrainingInfo.h.
{}
TrainingInfo() [2/3]
onert::compiler::train::TrainingInfo::TrainingInfo (const TrainingInfo & obj) default
TrainingInfo() [3/3]
onert::compiler::train::TrainingInfo::TrainingInfo (TrainingInfo &&) default
~TrainingInfo()
onert::compiler::train::TrainingInfo::~TrainingInfo () default
Member Function Documentation
batchSize()
uint32_t onert::compiler::train::TrainingInfo::batchSize () const inline
Definition at line 43 of file TrainingInfo.h.
{ return _batch_size; }
Referenced by onert::compiler::train::TrainingCompiler::compile().
lossInfo()
const ir::train::LossInfo & onert::compiler::train::TrainingInfo::lossInfo () const inline
Definition at line 45 of file TrainingInfo.h.
{ return _loss_info; }
Referenced by onert::compiler::train::pass::LossInsertionPass::run().
operator=() [1/2]
TrainingInfo & onert::compiler::train::TrainingInfo::operator= (const TrainingInfo &) default
operator=() [2/2]
TrainingInfo & onert::compiler::train::TrainingInfo::operator= (TrainingInfo &&) default
optimizerInfo()
const ir::train::OptimizerInfo & onert::compiler::train::TrainingInfo::optimizerInfo () const inline
Definition at line 54 of file TrainingInfo.h.
{ return _optimizer_info; }
setBatchSize()
void onert::compiler::train::TrainingInfo::setBatchSize (const uint32_t batch_size) inline
Definition at line 44 of file TrainingInfo.h.
{ _batch_size = batch_size; }
Referenced by nnfw_session::train_prepare().
setLossInfo()
void onert::compiler::train::TrainingInfo::setLossInfo (const ir::train::LossInfo & loss_info) inline
Definition at line 46 of file TrainingInfo.h.
  {
    _loss_info = loss_info;
    // If the reduction type is not specified, it uses SumOverBatchSize.
    if (_loss_info.reduction_type == ir::train::LossReductionType::Invalid)
      _loss_info.reduction_type = ir::train::LossReductionType::SumOverBatchSize;
  }
References onert::ir::train::Invalid, onert::ir::train::LossInfo::reduction_type, and onert::ir::train::SumOverBatchSize.
Referenced by nnfw_session::train_prepare().
setOptimizerInfo()
void onert::compiler::train::TrainingInfo::setOptimizerInfo (const ir::train::OptimizerInfo & optimizer_info) inline
Definition at line 55 of file TrainingInfo.h.
  {
    _optimizer_info = optimizer_info;
  }
Referenced by nnfw_session::train_prepare().
The documentation for this class was generated from the following file:
runtime/onert/core/include/compiler/train/TrainingInfo.h