ONE - On-device Neural Engine: onert::backend::gpu_cl::TensorBuilder Class Reference
onert::backend::gpu_cl::TensorBuilder Class Reference
#include <TensorBuilder.h>
Public Member Functions
TensorBuilder (const ir::Operands &operands, TensorManager *tensor_mgr)
void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout, TensorType type)
Register tensor information to allocate on ACL-CL backend.
void notifyFirstUse (const ir::OperandIndex &)
void notifyLastUse (const ir::OperandIndex &)
bool isRegistered (const ir::OperandIndex &) const
void prepare ()
void allocate ()
void postFunctionPrepare ()
TensorManager * cl_tensor_manager (void)
void setUsesCount (const ir::OperandIndex &index, size_t num_uses)
void parent_map (std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > &&parent_map)
bool areSubTensorsOf (const ir::OperandIndex &parent, const ir::OperandIndexSequence &seq)
bool isSubTensorOf (const ir::OperandIndex &parent, const ir::OperandIndex &child)
Check child tensor is allocated as subtensor of parent tensor.
Detailed Description
Definition at line 34 of file TensorBuilder.h.
Constructor & Destructor Documentation
TensorBuilder()
onert::backend::gpu_cl::TensorBuilder::TensorBuilder (const ir::Operands & operands, TensorManager * tensor_mgr)
Definition at line 47 of file TensorBuilder.cc.
  : _operands{operands}, _tensor_mgr{tensor_mgr}
{
  assert(_tensor_mgr);
}
Member Function Documentation
allocate()
void onert::backend::gpu_cl::TensorBuilder::allocate (void)
Definition at line 84 of file TensorBuilder.cc.
{
  auto lifetime_map = cl_common::createLifetimeMap(_lifetime_seq, _parent_map);
  for (auto &entry : lifetime_map)
  {
    auto &use = entry.second;
    auto use_type = use.first;
    auto use_index = use.second;
    assert(use_index.valid());
    if (use_type == UsesType::FIRST)
      _tensor_mgr->startLifetime(use_index);
    else
      _tensor_mgr->finishLifetime(use_index);
  }
  _tensor_mgr->allocateConsts();
  // TODO Since `_parent_map` is filled for all Concat nodes even if the node this backend uses
  //      After refactoring BackendContext we can uncomment this
  // assert(_tensor_info_map.size() ==
  //       _tensor_mgr->nonconstTensors().size() + num of constants of _tensor_info_map +
  //       _parent_map.size());
  _tensor_mgr->allocateNonconsts();
}
References onert::backend::cl_common::createLifetimeMap(), and entry().
areSubTensorsOf()
bool onert::backend::gpu_cl::TensorBuilder::areSubTensorsOf (const ir::OperandIndex & parent, const ir::OperandIndexSequence & seq)
cl_tensor_manager()
TensorManager * onert::backend::gpu_cl::TensorBuilder::cl_tensor_manager (void) inline
Definition at line 57 of file TensorBuilder.h.
{ return _tensor_mgr.get(); }
isRegistered()
bool onert::backend::gpu_cl::TensorBuilder::isRegistered (const ir::OperandIndex & ind) const
Definition at line 77 of file TensorBuilder.cc.
{
  return _tensor_info_map.find(ind) != _tensor_info_map.end();
}
isSubTensorOf()
bool onert::backend::gpu_cl::TensorBuilder::isSubTensorOf (const ir::OperandIndex & parent, const ir::OperandIndex & child)
Check child tensor is allocated as subtensor of parent tensor.
Parameters
[in] parent Index of parent
[in] child Index of child
Returns
true if child is allocated as subtensor of parent, otherwise false
notifyFirstUse()
void onert::backend::gpu_cl::TensorBuilder::notifyFirstUse (const ir::OperandIndex & ind)
Definition at line 67 of file TensorBuilder.cc.
{
  _lifetime_seq.emplace_back(UsesType::FIRST, ind);
}
notifyLastUse()
void onert::backend::gpu_cl::TensorBuilder::notifyLastUse (const ir::OperandIndex & ind)
Definition at line 72 of file TensorBuilder.cc.
{
  _lifetime_seq.emplace_back(UsesType::LAST, ind);
}
parent_map()
void onert::backend::gpu_cl::TensorBuilder::parent_map (std::unordered_map< ir::OperandIndex, cl_common::ParentInfo > && parent_map) inline
Definition at line 66 of file TensorBuilder.h.
  {
    _parent_map = std::move(parent_map);
  }
References parent_map().
Referenced by parent_map().
postFunctionPrepare()
void onert::backend::gpu_cl::TensorBuilder::postFunctionPrepare (void)
Definition at line 110 of file TensorBuilder.cc.
{ _tensor_mgr->tryDeallocConstants(); }
prepare()
void onert::backend::gpu_cl::TensorBuilder::prepare (void)
Definition at line 82 of file TensorBuilder.cc.
{ buildTensors(); }
registerTensorInfo()
void onert::backend::gpu_cl::TensorBuilder::registerTensorInfo (const ir::OperandIndex & ind, const ir::OperandInfo & info, ir::Layout backend_layout, TensorType type)
Register tensor information to allocate on ACL-CL backend.
Parameters
[in] ind Operand index
[in] info Tensor information
[in] layout Tensor data layout
Definition at line 53 of file TensorBuilder.cc.
{
  assert(_tensor_mgr->constTensors().size() == 0);
  assert(_tensor_mgr->nonconstTensors().size() == 0);
  _uses_count_map[ind] = _operands.at(ind).getUses().size();
  _tensor_info_map.emplace(ind, info);
  _tensor_type_map.emplace(ind, type);
  _tensor_layout_map.insert({ind, backend_layout});
}
References onert::util::ObjectManager< Index, Object >::at(), and info.
setUsesCount()
void onert::backend::gpu_cl::TensorBuilder::setUsesCount (const ir::OperandIndex & index, size_t num_uses) inline
Definition at line 59 of file TensorBuilder.h.
  {
    assert(_uses_count_map.find(index) != _uses_count_map.end() ? _uses_count_map[index] == num_uses
                                                                : true);
    _uses_count_map[index] = num_uses;
  }
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/TensorBuilder.h
runtime/onert/backend/gpu_cl/TensorBuilder.cc