ONE - On-device Neural Engine: caffeimport::EltwiseBuilder Class Reference
caffeimport::EltwiseBuilder Class Reference final
#include <Eltwise.h>
Public Member Functions
void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const override
Public Member Functions inherited from caffeimport::GraphBuilder
virtual void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 27 of file Eltwise.h.
Member Function Documentation
build()
void caffeimport::EltwiseBuilder::build (const ::caffe::LayerParameter & layer, GraphBuilderContext * context) const override virtual
Implements caffeimport::GraphBuilder.
Definition at line 33 of file Eltwise.cpp.
{
  coco::Module *module = context->module();
  coco::Block *blk = context->block();
  std::map<std::string, tensor::Shape> &shape_ctx = context->shape_ctx();
  std::map<std::string, coco::Bag *> &bag_ctx = context->bag_ctx();
  using coco::FeatureLayouts::BCHW;
  assert(layer.bottom().size() > 1);
  assert(layer.top().size() == 1);
  assert(layer.has_eltwise_param());
  const auto &param = layer.eltwise_param();
  using ::caffe::EltwiseParameter_EltwiseOp;
  using ::caffe::EltwiseParameter_EltwiseOp_SUM;
  using ::caffe::EltwiseParameter_EltwiseOp_PROD;
  using Reducer = std::function<coco::Op *(coco::Op * lhs, coco::Op * rhs)>;
  using ReducerRegistry = std::map<EltwiseParameter_EltwiseOp, Reducer>;
  ReducerRegistry registry;
  // MAX are not supported, yet
  registry[EltwiseParameter_EltwiseOp_SUM] = [](coco::Op *lhs, coco::Op *rhs) -> coco::Op * {
    if (lhs == nullptr)
    {
      assert(rhs != nullptr);
      return rhs;
    }
    assert(lhs != nullptr && rhs != nullptr);
    assert(lhs->module() == rhs->module());
    assert(lhs->module() != nullptr);
    auto m = lhs->module();
    return op_builder(m).push(rhs).push(lhs).add().pop();
  };
  registry[EltwiseParameter_EltwiseOp_PROD] = [](coco::Op *lhs, coco::Op *rhs) -> coco::Op * {
    if (lhs == nullptr)
    {
      assert(rhs != nullptr);
      return rhs;
    }
    assert(lhs != nullptr && rhs != nullptr);
    assert(lhs->module() == rhs->module());
    assert(lhs->module() != nullptr);
    auto m = lhs->module();
    return op_builder(m).push(rhs).push(lhs).mul().pop();
  };
  // coeff is not supported, yet
  assert(!param.coeff().size());
  // Decide appropriate reduce function
  auto reduce = registry.at(param.operation());
  coco::Op *op = nullptr;
  for (const auto &ifm_name : layer.bottom())
  {
    auto ifm_shape = shape_ctx.at(ifm_name);
    // NOTE The current implementation does not work in general
    auto ifm_bag = bag_ctx.at(ifm_name);
    auto ifm_obj = module->entity()->object()->create<coco::FeatureObject>();
    ifm_obj->bag(ifm_bag);
    ifm_obj->layout(BCHW::create(as_feature_shape(ifm_shape)));
    auto load = op_builder(module).load(ifm_obj).pop();
    op = reduce(op, load);
  }
  assert(op != nullptr);
  const auto ofm_name = layer.top(0);
  const auto ofm_shape = shape_ctx.at(layer.bottom(0));
  auto ofm_bag = module->entity()->bag()->create(num_elements(ofm_shape));
  auto ofm_obj = module->entity()->object()->create<coco::FeatureObject>();
  ofm_obj->bag(ofm_bag);
  ofm_obj->layout(BCHW::create(as_feature_shape(ofm_shape)));
  // Create "Eval" instruction
  auto eval = instr_builder(module).eval(ofm_obj, op);
  // Append the instruction to the block
  blk->instr()->append(eval);
  // Update bag and shape context
  bag_ctx[ofm_name] = ofm_bag;
  shape_ctx[ofm_name] = ofm_shape;
}
References OpBuilder::add(), coco::DLinkedList< Child, Parent >::Head::append(), morph::caffe::as_feature_shape(), coco::Object::bag(), coco::EntityManager::bag(), caffeimport::GraphBuilderContext::bag_ctx(), caffeimport::GraphBuilderContext::block(), coco::BagManager::create(), coco::ObjectManager::create(), coco::Module::entity(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), OpBuilder::load(), m, caffeimport::GraphBuilderContext::module(), OpBuilder::mul(), coco::EntityManager::object(), op_builder(), OpBuilder::pop(), OpBuilder::push(), and caffeimport::GraphBuilderContext::shape_ctx().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/Layer/Eltwise.h
compiler/enco/frontend/caffe/src/Layer/Eltwise.cpp