ONE - On-device Neural Engine: tflimport::TflOpCodeContext Class Reference
tflimport::TflOpCodeContext Class Reference
Class that holds operator codes and related methods.
#include <Context.h>
Public Member Functions
TflOpCodeContext (const flatbuffers::Vector< flatbuffers::Offset< tflite::OperatorCode > > *opcodes)
tflite::BuiltinOperator builtin_code (const tflite::Operator *op) const
Returns BuiltinOperator value of the operator.
std::string opcode_name (const tflite::Operator *op) const
Returns human readable name of the operator code of the operator.
Static Public Member Functions
static bool is_valid (const tflite::OperatorCode *opcode)
static bool is_custom (const tflite::OperatorCode *opcode)
Detailed Description
Class that holds operator codes and related methods.
Definition at line 56 of file Context.h.
Constructor & Destructor Documentation
TflOpCodeContext()
tflimport::TflOpCodeContext::TflOpCodeContext (const flatbuffers::Vector< flatbuffers::Offset< tflite::OperatorCode > > * opcodes)
Definition at line 50 of file Context.cpp.
{
  for (const tflite::OperatorCode *opcode : *opcodes)
  {
    _opcodes.push_back(opcode);
  }
}
Member Function Documentation
builtin_code()
tflite::BuiltinOperator tflimport::TflOpCodeContext::builtin_code (const tflite::Operator * op) const
Returns BuiltinOperator value of the operator.
Definition at line 59 of file Context.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _opcodes.size());
  const tflite::OperatorCode *opcode = _opcodes.at(index);
  return opcode->builtin_code();
}
is_custom()
bool tflimport::TflOpCodeContext::is_custom (const tflite::OperatorCode * opcode) static
Definition at line 98 of file Context.cpp.
{
  tflite::BuiltinOperator code = opcode->builtin_code();
  return (code == tflite::BuiltinOperator_CUSTOM);
}
Referenced by opcode_name().
is_valid()
bool tflimport::TflOpCodeContext::is_valid (const tflite::OperatorCode * opcode) static
Definition at line 92 of file Context.cpp.
{
  tflite::BuiltinOperator code = opcode->builtin_code();
  return (tflite::BuiltinOperator_MIN <= code && code <= tflite::BuiltinOperator_MAX);
}
Referenced by opcode_name().
opcode_name()
std::string tflimport::TflOpCodeContext::opcode_name (const tflite::Operator * op) const
Returns human readable name of the operator code of the operator.
Note
TF lite InterpreterBuilder sets an error state and returns error code for invalid opcode. Here we just return human readable message as this method returns a name for the operator code.
Definition at line 67 of file Context.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _opcodes.size());
  const tflite::OperatorCode *opcode = _opcodes.at(index);
  if (!is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  if (is_custom(opcode))
  {
    if (!opcode->custom_code())
      return "(invalid custom)";
    return opcode->custom_code()->c_str();
  }
  tflite::BuiltinOperator code = opcode->builtin_code();
  return EnumNameBuiltinOperator(code);
}
References is_custom(), and is_valid().
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Context.h
compiler/enco/frontend/tflite/src/Context.cpp