ONE - On-device Neural Engine: GraphTestcase< GraphCode::Relu > Class Reference
GraphTestcase< GraphCode::Relu > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::Pull * pull_node = nullptr
loco::ReLU * relu_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 144 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::Relu >::GraphTestcase () inline
Definition at line 147 of file GraphTestcase.h.
  {
    // Create a sample network
    _graph = loco::make_graph();
    auto graph_builder = make_graph_builder(_graph.get());
    pull_node = graph_builder->push<InputLayer>()->name("input")->node();
    relu_node = graph_builder->push<ReLULayer>()->node();
    push_node = graph_builder->push<OutputLayer>()->name("output")->node();
  }
References loco::make_graph().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::Relu >::graph () inline
Definition at line 160 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
pull_node
loco::Pull* GraphTestcase< GraphCode::Relu >::pull_node = nullptr
Definition at line 162 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::Relu >::push_node = nullptr
Definition at line 164 of file GraphTestcase.h.
relu_node
loco::ReLU* GraphTestcase< GraphCode::Relu >::relu_node = nullptr
Definition at line 163 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h