ONE - On-device Neural Engine: moco::onnx::GraphBuilderContext Class Reference
moco::onnx::GraphBuilderContext Class Reference
Class to store context to build IR from onnx.
#include <GraphBuilderContext.h>
Public Member Functions
GraphBuilderContext (loco::Graph *g, SymbolTable *nodes, SymbolTable *input_names)
GraphBuilderContext (const GraphBuilderContext &)=delete
GraphBuilderContext (GraphBuilderContext &&)=delete
loco::Graph * graph ()
SymbolTable * nodes ()
SymbolTable * input_names ()
Detailed Description
Class to store context to build IR from onnx.
Definition at line 74 of file GraphBuilderContext.h.
Constructor & Destructor Documentation
GraphBuilderContext() [1/3]
moco::onnx::GraphBuilderContext::GraphBuilderContext (loco::Graph * g, SymbolTable * nodes, SymbolTable * input_names) inline
Definition at line 77 of file GraphBuilderContext.h.
    : _g(g), _nodes(nodes), _input_names(input_names)
  {
    // DO NOTHING
  }
GraphBuilderContext() [2/3]
moco::onnx::GraphBuilderContext::GraphBuilderContext (const GraphBuilderContext &) delete
GraphBuilderContext() [3/3]
moco::onnx::GraphBuilderContext::GraphBuilderContext (GraphBuilderContext &&) delete
Member Function Documentation
graph()
loco::Graph * moco::onnx::GraphBuilderContext::graph () inline
Definition at line 87 of file GraphBuilderContext.h.
{ return _g; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), moco::onnx::Constant_V1::build(), moco::onnx::Constant_V9::build(), moco::onnx::Identity_V1::build(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
input_names()
SymbolTable * moco::onnx::GraphBuilderContext::input_names () inline
Definition at line 89 of file GraphBuilderContext.h.
{ return _input_names; }
Referenced by moco::onnx::Identity_V1::build().
nodes()
SymbolTable * moco::onnx::GraphBuilderContext::nodes () inline
Definition at line 88 of file GraphBuilderContext.h.
{ return _nodes; }
Referenced by moco::onnx::Constant_V1::build(), moco::onnx::Constant_V9::build(), and moco::onnx::Identity_V1::build().
The documentation for this class was generated from the following file:
compiler/oneco/src/GraphBuilderContext.h