ONE - On-device Neural Engine: circlechef::CircleImport Class Reference
circlechef::CircleImport Class Reference
Loads TF lite file and provides helpers to access attributes.
#include <CircleImport.h>
Public Member Functions
CircleImport (const circle::Model *model)
CircleImport ()=delete
bool select_sub_graph (uint32_t subgraph)
const CircleBuffers_t * buffers ()
const CircleTensors_t * tensors ()
const CircleOperators_t * operators ()
const std::vector< int32_t > & inputs () const
const std::vector< int32_t > & outputs () const
uint32_t num_subgraph () const
circle::BuiltinOperator builtin_code (const circle::Operator *op) const
std::string opcode_name (const circle::Operator *op) const
size_t buffer_info (const circle::Tensor *tensor, const uint8_t **buff_data)
Public Member Functions inherited from souschef::TensorFiller
virtual ~TensorFiller ()=default
void set_tensor_filler (uint32_t tensor_index)
This will record the tensor by index, if it needs filler option, such as kernel, bias.
void set_tensor_filler (uint32_t tensor_index, std::vector< int32_t > &expvalues)
This will store int32 filler values such as reshape information for the tensor.
void set_tensor_filler (uint32_t tensor_index, std::vector< float > &expvalues)
bool get_tensor_filler (uint32_t tensor_index)
This will return true if the tensor by index, needs a filler option.
bool get_tensor_filler (uint32_t tensor_index, std::vector< int32_t > &expvalues)
This will return true if the tensor by index, needs a int array filler option.
bool get_tensor_filler (uint32_t tensor_index, std::vector< float > &expvalues)
Detailed Description
Loads TF lite file and provides helpers to access attributes.
Definition at line 40 of file CircleImport.h.
Constructor & Destructor Documentation
CircleImport() [1/2]
circlechef::CircleImport::CircleImport (const circle::Model * model)
Definition at line 28 of file CircleImport.cpp.
{
  _subgraphs = model->subgraphs();
  _buffers = model->buffers();
  auto opcodes = model->operator_codes();
  for (const ::circle::OperatorCode *opcode : *opcodes)
  {
    _op_codes.push_back(opcode);
  }
}
CircleImport() [2/2]
circlechef::CircleImport::CircleImport () delete
Member Function Documentation
buffer_info()
size_t circlechef::CircleImport::buffer_info (const circle::Tensor * tensor, const uint8_t ** buff_data)
Definition at line 98 of file CircleImport.cpp.
{
  *buff_data = nullptr;
  if (tensor->buffer() == 0)
    return 0;
  if (auto *buffer = (*_buffers)[tensor->buffer()])
  {
    if (auto *array = buffer->data())
    {
      if (size_t size = array->size())
      {
        *buff_data = reinterpret_cast<const uint8_t *>(array->data());
        return size;
      }
    }
  }
  return 0;
}
buffers()
const CircleBuffers_t * circlechef::CircleImport::buffers () inline
Definition at line 51 of file CircleImport.h.
{ return _buffers; }
Referenced by circlechef::generate_recipe().
builtin_code()
circle::BuiltinOperator circlechef::CircleImport::builtin_code (const circle::Operator * op) const
Definition at line 64 of file CircleImport.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const circle::OperatorCode *opcode = _op_codes.at(index);
  return mio::circle::builtin_code_neutral(opcode);
}
References mio::circle::builtin_code_neutral().
Referenced by circlechef::generate_recipe().
inputs()
const std::vector< int32_t > & circlechef::CircleImport::inputs () const inline
Definition at line 54 of file CircleImport.h.
{ return _inputs; }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs(), and circlechef::generate_recipe().
num_subgraph()
uint32_t circlechef::CircleImport::num_subgraph () const inline
Definition at line 57 of file CircleImport.h.
{ return _subgraphs->Length(); }
Referenced by circlechef::generate_recipe().
opcode_name()
std::string circlechef::CircleImport::opcode_name (const circle::Operator * op) const
Definition at line 73 of file CircleImport.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const circle::OperatorCode *opcode = _op_codes.at(index);
  if (!mio::circle::is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  if (mio::circle::is_custom(opcode))
  {
    if (!opcode->custom_code())
      return "(invalid custom)";
    return opcode->custom_code()->c_str();
  }
  circle::BuiltinOperator code = opcode->builtin_code();
  return EnumNameBuiltinOperator(code);
}
References mio::circle::is_custom(), and mio::circle::is_valid().
Referenced by circlechef::generate_recipe().
operators()
const CircleOperators_t * circlechef::CircleImport::operators () inline
Definition at line 53 of file CircleImport.h.
{ return _operators; }
Referenced by circlechef::generate_recipe().
outputs()
const std::vector< int32_t > & circlechef::CircleImport::outputs () const inline
Definition at line 55 of file CircleImport.h.
{ return _outputs; }
Referenced by circlechef::generate_recipe(), and validate_onnx2circle.OnnxRunner::get_outputs().
select_sub_graph()
bool circlechef::CircleImport::select_sub_graph (uint32_t subgraph)
Definition at line 40 of file CircleImport.cpp.
{
  _tensors = nullptr;
  _operators = nullptr;
  _inputs.clear();
  _outputs.clear();
  if (_subgraphs->Length() <= sgindex)
  {
    assert(false);
    return false;
  }
  const circle::SubGraph *subgraph = (*_subgraphs)[sgindex];
  _tensors = subgraph->tensors();
  _operators = subgraph->operators();
  _inputs = as_index_vector(subgraph->inputs());
  _outputs = as_index_vector(subgraph->outputs());
  return true;
}
References circlechef::as_index_vector().
Referenced by circlechef::generate_recipe().
tensors()
const CircleTensors_t * circlechef::CircleImport::tensors () inline
Definition at line 52 of file CircleImport.h.
{ return _tensors; }
Referenced by circlechef::generate_recipe().
The documentation for this class was generated from the following files:
compiler/circlechef/circle/src/CircleImport.h
compiler/circlechef/circle/src/CircleImport.cpp