ONE - On-device Neural Engine: moco::onnx::Constant_V1 Class Reference
moco::onnx::Constant_V1 Class Reference
GraphBuilder for Constant(since version 1) node.
#include <Constant.h>
Public Member Functions
bool validate (const ::onnx::NodeProto &) const
void build (const ::onnx::NodeProto &, GraphBuilderContext *) const
Detailed Description
GraphBuilder for Constant(since version 1) node.
Definition at line 29 of file Constant.h.
Member Function Documentation
build()
void moco::onnx::Constant_V1::build (const ::onnx::NodeProto & node, GraphBuilderContext * context) const
Definition at line 39 of file Constant_V1.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *nodes = context->nodes();
  // Create a "ConstGen" node for Constant
  auto const_node = graph->nodes()->create<loco::ConstGen>();
  auto tensor_attribute = node.attribute().Get(0).t();
  const_node->dtype(as_loco_datatype(tensor_attribute.data_type()));
  const_node->rank(tensor_attribute.dims_size());
  // TODO Support other data types
  assert(const_node->dtype() == loco::DataType::FLOAT32);
  const_node->size<loco::DataType::FLOAT32>(tensor_attribute.float_data_size());
  for (uint32_t i = 0; i < const_node->rank(); ++i)
  {
    const_node->dim(i) = tensor_attribute.dims(i);
  }
  // TODO Support other data types
  for (int i = 0; i < tensor_attribute.float_data_size(); ++i)
  {
    const_node->at<loco::DataType::FLOAT32>(i) = tensor_attribute.float_data(i);
  }
  nodes->enroll(node.name(), const_node);
  nodes->enroll(node.output(0), const_node);
}
References moco::onnx::as_loco_datatype(), loco::ConstGen::at(), moco::onnx::SymbolTable::enroll(), moco::onnx::GraphBuilderContext::graph(), and moco::onnx::GraphBuilderContext::nodes().
Referenced by moco::onnx::ConstantGraphBuilder::build().
validate()
bool moco::onnx::Constant_V1::validate (const ::onnx::NodeProto & node) const
Definition at line 27 of file Constant_V1.cpp.
{
  if (node.attribute_size() == 0 || !node.attribute(0).has_t())
    return false;
  auto type = moco::onnx::tensor_dtype_as_string(node.attribute(0).t().data_type());
  if (type.compare("FLOAT16") != 0 && type.compare("FLOAT") != 0 && type.compare("DOUBLE") != 0)
    return false;
  return true;
}
References moco::onnx::tensor_dtype_as_string().
Referenced by moco::onnx::ConstantGraphBuilder::validate().
The documentation for this class was generated from the following files:
compiler/oneco/src/Op/Constant.h
compiler/oneco/src/Op/Constant_V1.cpp