ONE - On-device Neural Engine: luci::QuantizeWeightsPass Class Reference
luci::QuantizeWeightsPass Class Reference
Pass to quantize weights.
#include <QuantizeWeightsPass.h>
Data Structures
struct Context
Public Member Functions
QuantizeWeightsPass (std::unique_ptr< Context > &&ctx)
QuantizeWeightsPass (loco::DataType input_model_dtype, loco::DataType output_model_dtype, QuantizationGranularity granularity)
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to quantize weights.
Definition at line 32 of file QuantizeWeightsPass.h.
Constructor & Destructor Documentation
QuantizeWeightsPass() [1/2]
luci::QuantizeWeightsPass::QuantizeWeightsPass (std::unique_ptr< Context > && ctx) inline
Definition at line 43 of file QuantizeWeightsPass.h.
                                                    : _ctx{std::move(ctx)}
  {
    // DO NOTHING
  }
QuantizeWeightsPass() [2/2]
luci::QuantizeWeightsPass::QuantizeWeightsPass (loco::DataType input_model_dtype, loco::DataType output_model_dtype, QuantizationGranularity granularity) inline
Definition at line 49 of file QuantizeWeightsPass.h.
  {
    _ctx = std::make_unique<Context>();
    {
      _ctx->input_model_dtype = input_model_dtype;
      _ctx->output_model_dtype = output_model_dtype;
      _ctx->granularity = granularity;
    }
  }
Member Function Documentation
name()
virtual const char * luci::QuantizeWeightsPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 59 of file QuantizeWeightsPass.h.
{ return "luci::QuantizeWeightsPass"; }
run()
bool luci::QuantizeWeightsPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 26 of file QuantizeWeightsPass.cpp.
{
  LOGGER(l);
  INFO(l) << "QuantizeWeightsPass Start" << std::endl;
  if (_ctx->input_model_dtype != loco::DataType::FLOAT32)
    throw std::runtime_error("Weights-only quantization supports float32 input only");
  // Quantize weights
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    QuantizeWeightsOnly qw(_ctx->input_model_dtype, _ctx->output_model_dtype, _ctx->granularity);
    circle_node->accept(&qw);
  }
  INFO(l) << "QuantizeWeightsPass End" << std::endl;
  return false; // one time run
}
References loco::active_nodes(), INFO, LOGGER, and loco::output_nodes().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference(), and luci::CircleQuantizer::quantize().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/QuantizeWeightsPass.h
compiler/luci/pass/src/QuantizeWeightsPass.cpp