ONE - On-device Neural Engine: luci_interpreter::kernels::ExpandDims Class Reference
luci_interpreter::kernels::ExpandDims Class Reference
#include <ExpandDims.h>
Public Member Functions
ExpandDims (const Tensor *input, const Tensor *axis, Tensor *output)
const Tensor * input () const
const Tensor * axis () const
Tensor * output () const
void configure () override
void execute () const override
ExpandDims (const Tensor *input, const Tensor *axis, Tensor *output)
const Tensor * input () const
const Tensor * axis () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file ExpandDims.h.
Constructor & Destructor Documentation
ExpandDims() [1/2]
luci_interpreter::kernels::ExpandDims::ExpandDims (const Tensor * input, const Tensor * axis, Tensor * output)
Definition at line 25 of file ExpandDims.cpp.
  : Kernel({input, axis}, {output})
{
}
References axis(), and input().
ExpandDims() [2/2]
luci_interpreter::kernels::ExpandDims::ExpandDims (const Tensor * input, const Tensor * axis, Tensor * output)
Member Function Documentation
axis() [1/2]
const Tensor * luci_interpreter::kernels::ExpandDims::axis () const inline
Definition at line 34 of file ExpandDims.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and ExpandDims().
axis() [2/2]
const Tensor * luci_interpreter::kernels::ExpandDims::axis () const inline
Definition at line 34 of file ExpandDims.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::ExpandDims::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 30 of file ExpandDims.cpp.
{
  int32_t axis_value;
  switch (axis()->element_type())
  {
    case loco::DataType::S32:
      axis_value = *getTensorData<int32_t>(axis());
      break;
    case loco::DataType::S64:
      axis_value = static_cast<int32_t>(*getTensorData<int64_t>(axis()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
  const auto input_shape = input()->shape();
  if (axis_value < 0)
  {
    axis_value += input_shape.num_dims() + 1;
  }
  LUCI_INTERPRETER_CHECK(axis_value <= input_shape.num_dims() and axis_value >= 0);
  Shape output_shape(input_shape.num_dims() + 1);
  for (int32_t i = 0; i < output_shape.num_dims(); ++i)
  {
    if (i < axis_value)
    {
      output_shape.dim(i) = input_shape.dim(i);
    }
    else if (i == axis_value)
    {
      output_shape.dim(i) = 1;
    }
    else
    {
      LUCI_INTERPRETER_CHECK(i >= 1);
      output_shape.dim(i) = input_shape.dim(i - 1);
    }
  }
  output()->resize(output_shape);
}
References axis(), input(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::ExpandDims::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::ExpandDims::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 76 of file ExpandDims.cpp.
{
  // Just copy input to output
  const auto *input_data = input()->data<void>();
  auto *output_data = output()->data<void>();
  const size_t element_size = getDataTypeSize(input()->element_type());
  const int32_t num_elements = input()->shape().num_elements();
  std::memcpy(output_data, input_data, num_elements * element_size);
}
References luci_interpreter::Tensor::data(), luci_interpreter::getDataTypeSize(), input(), luci_interpreter::Shape::num_elements(), output(), and luci_interpreter::Tensor::shape().
execute() [2/2]
void luci_interpreter::kernels::ExpandDims::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::ExpandDims::input () const inline
Definition at line 33 of file ExpandDims.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ExpandDims().
input() [2/2]
const Tensor * luci_interpreter::kernels::ExpandDims::input () const inline
Definition at line 33 of file ExpandDims.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::ExpandDims::output () const inline
Definition at line 35 of file ExpandDims.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::ExpandDims::output () const inline
Definition at line 35 of file ExpandDims.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/ExpandDims.h
onert-micro/luci-interpreter/src/kernels/ExpandDims.h
compiler/luci-interpreter/src/kernels/ExpandDims.cpp
onert-micro/luci-interpreter/src/kernels/ExpandDims.cpp