ONE - On-device Neural Engine: onert::backend::train::BackendContext Class Reference
onert::backend::train::BackendContext Class Reference
#include <BackendContext.h>
Public Member Functions
BackendContext (const ITrainableBackend *backend, std::unique_ptr< TrainableContextData > &&tdata, std::shared_ptr< backend::train::ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< TensorBuilder > tensor_builder=nullptr, std::unique_ptr< exec::train::optimizer::Optimizer > optimizer=nullptr, std::shared_ptr< KernelGenerator > kernel_gen=nullptr)
BackendContext (const BackendContext &)=delete
~BackendContext ()=default
BackendContext & operator= (const BackendContext &)=delete
backend::ITensorRegistry * genTensors () override
backend::train::ITensorRegistry * genTrainingTensors () override
FunctionMap genKernels () override
std::shared_ptr< ExternalContext > external_context ()
const exec::train::optimizer::Optimizer * optimizer () const
Public Member Functions inherited from onert::backend::train::TrainableBackendContext
TrainableBackendContext (const ITrainableBackend *backend, std::unique_ptr< TrainableContextData > &&tdata, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~TrainableBackendContext ()=default
const ir::train::TrainableGraph * trainable_graph () const
const TrainableContextData * data () const
const ITrainableBackend * backend () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
std::shared_ptr< ITensorRegistry > tensor_registry ()
Data Fields
std::shared_ptr< KernelGenerator > kernel_gen
Additional Inherited Members
Protected Attributes inherited from onert::backend::train::TrainableBackendContext
std::unique_ptr< TrainableContextData > _tdata
std::shared_ptr< ITensorRegistry > _tensor_registry
Detailed Description
Definition at line 51 of file BackendContext.h.
Constructor & Destructor Documentation
BackendContext() [1/2]
onert::backend::train::BackendContext::BackendContext (const ITrainableBackend * backend, std::unique_ptr< TrainableContextData > && tdata, std::shared_ptr< backend::train::ITensorRegistry > tensor_registry = nullptr, std::shared_ptr< TensorBuilder > tensor_builder = nullptr, std::unique_ptr< exec::train::optimizer::Optimizer > optimizer = nullptr, std::shared_ptr< KernelGenerator > kernel_gen = nullptr) inline
Definition at line 54 of file BackendContext.h.
    : onert::backend::train::TrainableBackendContext(backend, std::move(tdata), tensor_registry),
      kernel_gen{kernel_gen}, _external_context(new ExternalContext),
      _tensor_builder{tensor_builder}, _optimizer{std::move(optimizer)}
  {
  }
BackendContext() [2/2]
onert::backend::train::BackendContext::BackendContext (const BackendContext &) delete
~BackendContext()
onert::backend::train::BackendContext::~BackendContext () default
Member Function Documentation
external_context()
std::shared_ptr< ExternalContext > onert::backend::train::BackendContext::external_context () inline
Definition at line 77 of file BackendContext.h.
{ return _external_context; }
genKernels()
FunctionMap onert::backend::train::BackendContext::genKernels () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 111 of file BackendContext.cc.
{
  auto ret = generateFunctionMap();
  // Initialize TrainableTensors
  trainable_graph()->operands().iterate(
    [&](const ir::OperandIndex &ind, const ir::Operand &operand) {
      if (external_operands().contains(ind) || !operand.isConstant())
        return;
      auto tensor = tensor_registry()->getNativeITensor(ind);
      assert(tensor != nullptr);
      VERBOSE(FillOperandData) << "Fill data for " << ind << std::endl;
      auto data = operand.shareData();
      assert(data && data->base());
      auto trainable_tensor = dynamic_cast<TrainableTensor *>(tensor);
      if (trainable_tensor == nullptr)
        throw std::runtime_error{"This tensor is not trainable tensor"};
      trainable_tensor->fillBuffer(data);
    });
  // NOTE For memory optimization, we want to free some operand data
  const_cast<ir::train::TrainableGraph &>(*_tdata->tgraph)
    .operands()
    .iterate([&](const ir::OperandIndex &, ir::Operand &obj) { obj.releaseData(); });
  // TODO Enable
  // for (auto &&it : ret)
  // {
  //   auto &fn_seq = it.second;
  //   fn_seq->iterate([&](exec::IFunction &ifunc) { ifunc.prepare(); });
  // }
  return ret;
}
References onert::backend::train::TrainableBackendContext::_tdata, onert::backend::train::TrainableBackendContext::data(), onert::backend::train::TrainableBackendContext::external_operands(), onert::backend::basic::train::TrainableTensor::fillBuffer(), onert::ir::Operand::isConstant(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::train::TrainableGraph::operands(), onert::ir::Operand::shareData(), onert::backend::train::TrainableBackendContext::tensor_registry(), onert::backend::train::TrainableBackendContext::trainable_graph(), and VERBOSE.
genTensors()
backend::ITensorRegistry * onert::backend::train::BackendContext::genTensors () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 78 of file BackendContext.cc.
{
  return basic::train::genTensors(*this, _tensor_builder);
}
References onert::backend::basic::train::genTensors().
genTrainingTensors()
backend::train::ITensorRegistry * onert::backend::train::BackendContext::genTrainingTensors () override virtual
Implements onert::backend::train::TrainableBackendContext.
Definition at line 83 of file BackendContext.cc.
{
  const ir::train::TrainableGraph &tgraph = *trainable_graph();
  auto tensor_builder = _tensor_builder;
  tgraph.operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &obj) {
    if (external_operands().contains(ind))
      return;
    // NOTE Assuming there is no layout changes (Always assume NHWC or UNKNOWN)
    assert(tgraph.layout() != ir::Layout::NCHW);
    // TODO Different shape of back propagation tensor
    ir::OperandInfo backend_info{obj.shape(), obj.typeInfo(), obj.info().memAllocType(),
                                 obj.isConstant()};
    tensor_builder->registerBackwardTensorInfo(ind, backend_info, ir::Layout::NHWC);
  });
  // TODO Plan tensor builds to reduce peak memory usage
  tgraph.operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &) {
    if (tensor_builder->isRegisteredBackward(ind))
      tensor_builder->notifyBackwardFirstUse(ind);
  });
  tensor_builder->allocateBackward();
  return _tensor_registry.get();
}
References onert::backend::train::TrainableBackendContext::_tensor_registry, onert::backend::train::TrainableBackendContext::external_operands(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::train::TrainableGraph::layout(), onert::ir::NCHW, onert::ir::NHWC, onert::ir::train::TrainableGraph::operands(), and onert::backend::train::TrainableBackendContext::trainable_graph().
operator=()
BackendContext & onert::backend::train::BackendContext::operator= (const BackendContext &) delete
optimizer()
const exec::train::optimizer::Optimizer * onert::backend::train::BackendContext::optimizer () const inline
Definition at line 79 of file BackendContext.h.
{ return _optimizer.get(); }
Field Documentation
kernel_gen
std::shared_ptr<KernelGenerator> onert::backend::train::BackendContext::kernel_gen
Definition at line 86 of file BackendContext.h.
The documentation for this class was generated from the following files:
runtime/onert/backend/train/BackendContext.h
runtime/onert/backend/train/BackendContext.cc