ONE - On-device Neural Engine: onert::ir::OperationValidator Class Reference
onert::ir::OperationValidator Class Reference
#include <OperationValidator.h>
Public Member Functions
OperationValidator (void)=delete
OperationValidator (const Graph &graph)
void operator() ()
void visit (const operation::AddN &node) override
void visit (const operation::ArgMinMax &node) override
void visit (const operation::Attention &node) override
void visit (const operation::BatchMatMul &node) override
void visit (const operation::BatchToSpaceND &node) override
void visit (const operation::BinaryArithmetic &node) override
void visit (const operation::BroadcastTo &node) override
void visit (const operation::Comparison &node) override
void visit (const operation::Concat &node) override
void visit (const operation::Conv2D &node) override
void visit (const operation::DepthToSpace &node) override
void visit (const operation::DepthwiseConv2D &node) override
void visit (const operation::DetectionPostProcess &node) override
void visit (const operation::DynamicUpdateSlice &node) override
void visit (const operation::ElementwiseActivation &node) override
void visit (const operation::ElementwiseBinary &node) override
void visit (const operation::ElementwiseUnary &node) override
void visit (const operation::EmbeddingLookup &node) override
void visit (const operation::ExpandDims &node) override
void visit (const operation::Fill &node) override
void visit (const operation::Gather &node) override
void visit (const operation::HashtableLookup &node) override
void visit (const operation::Pack &node) override
void visit (const operation::Pad &node) override
void visit (const operation::Rank &node) override
void visit (const operation::ResizeBilinear &node) override
void visit (const operation::Reverse &node) override
void visit (const operation::RoPE &node) override
void visit (const operation::Select &node) override
void visit (const operation::Shape &node) override
void visit (const operation::Slice &node) override
void visit (const operation::Softmax &node) override
void visit (const operation::SpaceToBatchND &node) override
void visit (const operation::SpaceToDepth &node) override
void visit (const operation::Split &node) override
void visit (const operation::SquaredDifference &node) override
void visit (const operation::StatelessRandomUniform &node) override
void visit (const operation::StridedSlice &node) override
void visit (const operation::TopKV2 &node) override
void visit (const operation::Transpose &node) override
void visit (const operation::TransposeConv &node) override
void visit (const operation::Unpack &node) override
void visit (const operation::While &node) override
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Detailed Description
Definition at line 33 of file OperationValidator.h.
Constructor & Destructor Documentation
OperationValidator() [1/2]
onert::ir::OperationValidator::OperationValidator (void) delete
OperationValidator() [2/2]
onert::ir::OperationValidator::OperationValidator (const Graph & graph)
Definition at line 32 of file OperationValidator.cc.
  : _operations{graph.operations()}, _operands{graph.operands()}
{
}
Member Function Documentation
operator()()
void onert::ir::OperationValidator::operator() ()
Definition at line 37 of file OperationValidator.cc.
{
  _operations.iterate([&](const OperationIndex &, const IOperation &node) { node.accept(*this); });
}
References onert::ir::IOperation::accept(), and onert::util::ObjectManager< Index, Object >::iterate().
visit() [1/43]
void onert::ir::OperationValidator::visit (const operation::AddN & node) override
Definition at line 86 of file OperationValidator.cc.
{
  const auto output_index(node.getOutputs().at(0));
  int size = node.getInputs().size();
  for (int i = 0; i < size; i++)
  {
    const auto input_index(node.getInputs().at(i));
    OP_REQUIRES(isValidType(input_index, {DataType::FLOAT32, DataType::INT32}));
    OP_REQUIRES(isSameType(input_index, output_index));
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), OP_REQUIRES, onert::ir::OperandIndexSequence::size(), and size.
visit() [2/43]
void onert::ir::OperationValidator::visit (const operation::ArgMinMax & node) override
Definition at line 99 of file OperationValidator.cc.
{
  const auto input_index(node.getInputs().at(operation::ArgMinMax::Input::INPUT));
  const auto axis_index(node.getInputs().at(operation::ArgMinMax::Input::AXIS));
  const auto output_index(node.getOutputs().at(0));
  const auto output_type = node.param().output_type;
  OP_REQUIRES(isValidType(input_index, {DataType::FLOAT32, DataType::INT32, DataType::UINT8,
                                        DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
  OP_REQUIRES(isValidType(axis_index, {DataType::INT32, DataType::INT64}));
  OP_REQUIRES(isValidType(output_index, {DataType::INT32, DataType::INT64}));
  OP_REQUIRES(isValidType(output_index, output_type));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::ArgMinMax::AXIS, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ArgMinMax::INPUT, OP_REQUIRES, onert::ir::operation::ArgMinMax::Param::output_type, and onert::ir::operation::ArgMinMax::param().
visit() [3/43]
void onert::ir::OperationValidator::visit (const operation::Attention & node) override
Definition at line 113 of file OperationValidator.cc.
{
  const auto input_idx = node.getInputs().at(operation::Attention::Input::INPUT);
  const auto &input_shape = _operands.at(input_idx).shape();
  // Check if input's seq_len is 1
  // Assuming input shape is [batch_size, seq_len, embedding_dim]
  OP_REQUIRES(input_shape.rank() == 3);
  OP_REQUIRES(input_shape.dim(1) == 1);
  const auto cos_idx = node.getInputs().at(operation::Attention::Input::COS);
  const auto sin_idx = node.getInputs().at(operation::Attention::Input::SIN);
  const auto &cos_shape = _operands.at(cos_idx).shape();
  const auto &sin_shape = _operands.at(sin_idx).shape();
  // Check _cos and _sin shapes
  // Assuming shape is [batch_size, seq_len, d_head]
  // batch_size = 1, seq_len = 1
  OP_REQUIRES(cos_shape.rank() == 3);
  OP_REQUIRES(cos_shape.dim(0) == 1); // batch_size
  OP_REQUIRES(cos_shape.dim(1) == 1); // seq_len
  OP_REQUIRES(sin_shape.rank() == 3);
  OP_REQUIRES(sin_shape.dim(0) == 1); // batch_size
  OP_REQUIRES(sin_shape.dim(1) == 1); // seq_len
  const auto pos_idx = node.getInputs().at(operation::Attention::Input::POS);
  const auto &pos_shape = _operands.at(pos_idx).shape();
  // Check pos tensor type and shape
  OP_REQUIRES(isValidType(pos_idx, DataType::INT64));
  OP_REQUIRES(pos_shape.rank() == 1);
  OP_REQUIRES(pos_shape.dim(0) == 1);
}
References onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::Attention::COS, onert::ir::Operation::getInputs(), onert::ir::operation::Attention::INPUT, OP_REQUIRES, onert::ir::operation::Attention::POS, and onert::ir::operation::Attention::SIN.
visit() [4/43]
void onert::ir::OperationValidator::visit (const operation::BatchMatMul & node) override
Definition at line 148 of file OperationValidator.cc.
{
  const auto lhs_index(node.getInputs().at(operation::BatchMatMul::Input::LHS));
  const auto rhs_index(node.getInputs().at(operation::BatchMatMul::Input::RHS));
  const auto output_index(node.getOutputs().at(0));
  // RHS can be constant, but LHS is not constant
  // If one of inputs is constant, it must be RHS
  // If two inputs are constant, BatchMatMul is optimized into constant by compiler
  OP_REQUIRES(!isConstant(lhs_index));
  // Allow hybrid quantization (lhs: float / rhs: qint8 / out: float)
  OP_REQUIRES(isValidType(
    lhs_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
  OP_REQUIRES(isSameType(lhs_index, rhs_index) ||
              ((operandType(lhs_index) == DataType::FLOAT32) &&
               (operandType(rhs_index) == DataType::QUANT_INT8_ASYMM)));
  OP_REQUIRES(isSameType(lhs_index, output_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::BatchMatMul::LHS, OP_REQUIRES, and onert::ir::operation::BatchMatMul::RHS.
visit() [5/43]
void onert::ir::OperationValidator::visit (const operation::BatchToSpaceND & node) override
Definition at line 168 of file OperationValidator.cc.
{
  const auto input_index{node.getInputs().at(operation::BatchToSpaceND::Input::INPUT)};
  const auto output_index{node.getOutputs().at(0)};
  OP_REQUIRES(isSameType(input_index, output_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::BatchToSpaceND::INPUT, and OP_REQUIRES.
visit() [6/43]
void onert::ir::OperationValidator::visit (const operation::BinaryArithmetic & node) override
Definition at line 176 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto lhs_index{node.getInputs().at(operation::BinaryArithmetic::Input::LHS)};
  const auto rhs_index{node.getInputs().at(operation::BinaryArithmetic::Input::RHS)};
  OP_REQUIRES(isSameType(lhs_index, rhs_index));
  OP_REQUIRES(isSameType(lhs_index, output_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::BinaryArithmetic::LHS, OP_REQUIRES, and onert::ir::operation::BinaryArithmetic::RHS.
visit() [7/43]
void onert::ir::OperationValidator::visit (const operation::BroadcastTo & node) override
Definition at line 186 of file OperationValidator.cc.
{
  const auto input_index(node.getInputs().at(operation::BroadcastTo::Input::INPUT));
  const auto shape_index(node.getInputs().at(operation::BroadcastTo::Input::SHAPE));
  const auto output_index(node.getOutputs().at(0));
  OP_REQUIRES(isSameType(input_index, output_index));
  OP_REQUIRES(isValidType(shape_index, {DataType::INT32, DataType::INT64}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::BroadcastTo::INPUT, OP_REQUIRES, and onert::ir::operation::BroadcastTo::SHAPE.
visit() [8/43]
void onert::ir::OperationValidator::visit (const operation::Comparison & node) override
Definition at line 196 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto lhs_index{node.getInputs().at(operation::Comparison::Input::INPUT0)};
  const auto rhs_index{node.getInputs().at(operation::Comparison::Input::INPUT1)};
  OP_REQUIRES(isSameType(lhs_index, rhs_index));
  OP_REQUIRES(isValidType(output_index, DataType::BOOL8));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Comparison::INPUT0, onert::ir::operation::Comparison::INPUT1, and OP_REQUIRES.
visit() [9/43]
void onert::ir::OperationValidator::visit (const operation::Concat & node) override
Definition at line 207 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  for (auto &&input_index : node.getInputs())
  {
    OP_REQUIRES(isSameType(input_index, output_index));
    // Int8 and Int16 quantization requires same scale and zero point
    if (isValidType(output_index, DataType::QUANT_INT8_ASYMM) ||
        isValidType(output_index, DataType::QUANT_INT16_SYMM))
    {
      OP_REQUIRES(isSameQuantParam(input_index, output_index));
    }
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and OP_REQUIRES.
visit() [10/43]
void onert::ir::OperationValidator::visit (const operation::Conv2D & node) override
Definition at line 224 of file OperationValidator.cc.
{
  const auto input_index{node.getInputs().at(operation::Conv2D::Input::INPUT)};
  const auto kernel_index{node.getInputs().at(operation::Conv2D::Input::KERNEL)};
  const auto output_index{node.getOutputs().at(0)};
  uint32_t stride_horizontal = node.param().stride.horizontal;
  uint32_t stride_vertical = node.param().stride.vertical;
  uint32_t dilation_width = node.param().dilation.width_factor;
  uint32_t dilation_height = node.param().dilation.height_factor;
  OP_REQUIRES((stride_horizontal > 0) && (stride_vertical > 0));
  OP_REQUIRES((dilation_width > 0) && (dilation_height > 0));
  OP_REQUIRES(isSameType(input_index, output_index));
  if (isConstant(kernel_index) && operandType(kernel_index) == DataType::QUANT_INT8_ASYMM)
  {
    for (const auto zeropoint : _operands.at(kernel_index).typeInfo().zero_points())
      OP_REQUIRES(zeropoint == 0);
  }
}
References onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::Conv2D::Param::dilation, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Dilation::height_factor, onert::ir::Stride::horizontal, onert::ir::operation::Conv2D::INPUT, onert::ir::operation::Conv2D::KERNEL, OP_REQUIRES, onert::ir::operation::Conv2D::param(), onert::ir::operation::Conv2D::Param::stride, onert::ir::Stride::vertical, and onert::ir::Dilation::width_factor.
visit() [11/43]
void onert::ir::OperationValidator::visit (const operation::DepthToSpace & node) override
Definition at line 246 of file OperationValidator.cc.
{
  const auto input_index{node.getInputs().at(operation::DepthToSpace::Input::INPUT)};
  const auto output_index{node.getOutputs().at(0)};
  int32_t block_size = node.param().block_size;
  OP_REQUIRES(isValidType(input_index, {DataType::FLOAT32, DataType::INT32, DataType::INT64,
                                        DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
  OP_REQUIRES(isSameType(input_index, output_index));
  OP_REQUIRES(block_size > 0);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::DepthToSpace::Param::block_size, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::DepthToSpace::INPUT, OP_REQUIRES, and onert::ir::operation::DepthToSpace::param().
visit() [12/43]
void onert::ir::OperationValidator::visit (const operation::DepthwiseConv2D & node) override
Definition at line 260 of file OperationValidator.cc.
{
  const auto input_index{node.getInputs().at(operation::DepthwiseConv2D::Input::INPUT)};
  const auto kernel_index{node.getInputs().at(operation::DepthwiseConv2D::Input::KERNEL)};
  const auto output_index{node.getOutputs().at(0)};
  uint32_t stride_horizontal = node.param().stride.horizontal;
  uint32_t stride_vertical = node.param().stride.vertical;
  uint32_t dilation_width = node.param().dilation.width_factor;
  uint32_t dilation_height = node.param().dilation.height_factor;
  OP_REQUIRES((stride_horizontal > 0) && (stride_vertical > 0));
  OP_REQUIRES((dilation_width > 0) && (dilation_height > 0));
  OP_REQUIRES(isSameType(input_index, output_index));
  if (isConstant(kernel_index) && operandType(kernel_index) == DataType::QUANT_INT8_ASYMM)
  {
    for (const auto zeropoint : _operands.at(kernel_index).typeInfo().zero_points())
      OP_REQUIRES(zeropoint == 0);
  }
}
References onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::DepthwiseConv2D::Param::dilation, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Dilation::height_factor, onert::ir::Stride::horizontal, onert::ir::operation::DepthwiseConv2D::INPUT, onert::ir::operation::DepthwiseConv2D::KERNEL, OP_REQUIRES, onert::ir::operation::DepthwiseConv2D::param(), onert::ir::operation::DepthwiseConv2D::Param::stride, onert::ir::Stride::vertical, and onert::ir::Dilation::width_factor.
visit() [13/43]
void onert::ir::OperationValidator::visit (const operation::DetectionPostProcess & node) override
Definition at line 282 of file OperationValidator.cc.
{
  const auto &param = node.param();
  // FIXME: number of classes should be 1 for now.
  OP_REQUIRES(param.num_classes == 1);
}
References OP_REQUIRES, and onert::ir::operation::DetectionPostProcess::param().
visit() [14/43]
void onert::ir::OperationValidator::visit (const operation::DynamicUpdateSlice & node) override
Definition at line 290 of file OperationValidator.cc.
{
  const auto operand_index{node.getInputs().at(operation::DynamicUpdateSlice::Input::OPERAND)};
  const auto update_index{node.getInputs().at(operation::DynamicUpdateSlice::Input::UPDATE)};
  const auto indices_index{node.getInputs().at(operation::DynamicUpdateSlice::Input::INDICES)};
  const auto output_index{node.getOutputs().at(0)};
  OP_REQUIRES(isSameType(operand_index, update_index));
  OP_REQUIRES(isSameType(operand_index, output_index));
  OP_REQUIRES(operandType(indices_index) == DataType::INT32 ||
              operandType(indices_index) == DataType::INT64);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::DynamicUpdateSlice::INDICES, OP_REQUIRES, onert::ir::operation::DynamicUpdateSlice::OPERAND, and onert::ir::operation::DynamicUpdateSlice::UPDATE.
visit() [15/43]
void onert::ir::OperationValidator::visit (const operation::ElementwiseActivation & node) override
Definition at line 303 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(0)};
  // Check if I/O types match
  OP_REQUIRES(isSameType(output_index, input_index));
  switch (node.param().op_type)
  {
    case operation::ElementwiseActivation::Type::ELU:
    case operation::ElementwiseActivation::Type::GELU:
      OP_REQUIRES(isValidType(input_index, DataType::FLOAT32));
      break;
    case operation::ElementwiseActivation::Type::LEAKY_RELU:
      OP_REQUIRES(
        isValidType(input_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM,
                                  DataType::QUANT_INT8_ASYMM, DataType::QUANT_INT16_SYMM}));
      break;
    case operation::ElementwiseActivation::Type::LOGISTIC:
      OP_REQUIRES(
        isValidType(input_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM,
                                  DataType::QUANT_INT8_ASYMM, DataType::QUANT_INT16_SYMM}));
      break;
    case operation::ElementwiseActivation::Type::RELU:
      OP_REQUIRES(isValidType(
        input_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
      break;
    case operation::ElementwiseActivation::Type::TANH:
      OP_REQUIRES(
        isValidType(input_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM,
                                  DataType::QUANT_INT8_ASYMM, DataType::QUANT_INT16_SYMM}));
      break;
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::ElementwiseActivation::ELU, onert::ir::operation::ElementwiseActivation::GELU, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ElementwiseActivation::LEAKY_RELU, onert::ir::operation::ElementwiseActivation::LOGISTIC, OP_REQUIRES, onert::ir::operation::ElementwiseActivation::Param::op_type, onert::ir::operation::ElementwiseActivation::param(), onert::ir::operation::ElementwiseActivation::RELU, and onert::ir::operation::ElementwiseActivation::TANH.
visit() [16/43]
void onert::ir::OperationValidator::visit (const operation::ElementwiseBinary & node) override
Definition at line 339 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto lhs_index{node.getInputs().at(operation::ElementwiseBinary::Input::LHS)};
  const auto rhs_index{node.getInputs().at(operation::ElementwiseBinary::Input::RHS)};
  OP_REQUIRES(isSameType(lhs_index, rhs_index));
  OP_REQUIRES(isSameType(lhs_index, output_index));
  const auto op_type = node.param().op_type;
  if (op_type == operation::ElementwiseBinary::ElementwiseBinaryType::LOGICAL_AND ||
      op_type == operation::ElementwiseBinary::ElementwiseBinaryType::LOGICAL_OR)
  {
    OP_REQUIRES(isValidType(lhs_index, DataType::BOOL8));
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ElementwiseBinary::LHS, onert::ir::operation::ElementwiseBinary::LOGICAL_AND, onert::ir::operation::ElementwiseBinary::LOGICAL_OR, OP_REQUIRES, onert::ir::operation::ElementwiseBinary::Param::op_type, onert::ir::operation::ElementwiseBinary::param(), and onert::ir::operation::ElementwiseBinary::RHS.
visit() [17/43]
void onert::ir::OperationValidator::visit (const operation::ElementwiseUnary & node) override
Definition at line 356 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::ElementwiseUnary::Input::INPUT)};
  // Check if I/O types match
  if (node.param().op_type == operation::ElementwiseUnary::Type::DEQUANTIZE)
  {
    // NNAPI allow QUANT_INT8_SYMM type input
    OP_REQUIRES(isValidType(input_index, {DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_SYMM,
                                          DataType::QUANT_INT8_ASYMM, DataType::QUANT_INT16_SYMM}));
    OP_REQUIRES(isValidType(output_index, DataType::FLOAT32));
  }
  else if (node.param().op_type == operation::ElementwiseUnary::Type::QUANTIZE)
  {
    OP_REQUIRES(isValidType(
      input_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
    OP_REQUIRES(isValidType(output_index, {DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM,
                                           DataType::QUANT_INT16_SYMM}));
  }
  else if (node.param().op_type == operation::ElementwiseUnary::Type::FLOOR)
  {
    OP_REQUIRES(isValidType(input_index, DataType::FLOAT32));
    OP_REQUIRES(isSameType(output_index, input_index));
  }
  else if (node.param().op_type != operation::ElementwiseUnary::Type::CAST)
  {
    OP_REQUIRES(isSameType(output_index, input_index));
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::ElementwiseUnary::CAST, onert::ir::operation::ElementwiseUnary::DEQUANTIZE, onert::ir::operation::ElementwiseUnary::FLOOR, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ElementwiseUnary::INPUT, OP_REQUIRES, onert::ir::operation::ElementwiseUnary::Param::op_type, onert::ir::operation::ElementwiseUnary::param(), and onert::ir::operation::ElementwiseUnary::QUANTIZE.
visit() [18/43]
void onert::ir::OperationValidator::visit (const operation::EmbeddingLookup & node) override
Definition at line 387 of file OperationValidator.cc.
{
  const auto lookups_index{node.getInputs().at(operation::EmbeddingLookup::Input::LOOKUPS)};
  const auto values_index{node.getInputs().at(operation::EmbeddingLookup::Input::VALUES)};
  const auto output_index{node.getOutputs().at(0)};
  OP_REQUIRES(isValidType(lookups_index, DataType::INT32));
  // TFLite: Allow hybrid type - value table & output
  // NNAPI: Require same value table and output type
  OP_REQUIRES(
    isSameType(values_index, output_index) ||
    (isValidType(output_index, DataType::FLOAT32) &&
     (isValidType(values_index, {DataType::QUANT_INT8_ASYMM, DataType::QUANT_INT8_SYMM}))));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::EmbeddingLookup::LOOKUPS, OP_REQUIRES, and onert::ir::operation::EmbeddingLookup::VALUES.
visit() [19/43]
void onert::ir::OperationValidator::visit (const operation::ExpandDims & node) override
Definition at line 403 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::ExpandDims::Input::INPUT)};
  const auto axis_index{node.getInputs().at(operation::ExpandDims::Input::AXIS)};
  OP_REQUIRES(isSameType(output_index, input_index));
  OP_REQUIRES(isValidType(axis_index, {DataType::INT32, DataType::INT64}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::ExpandDims::AXIS, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ExpandDims::INPUT, and OP_REQUIRES.
visit() [20/43]
void onert::ir::OperationValidator::visit (const operation::Fill & node) override
Definition at line 413 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Fill::Input::SHAPE)};
  const auto value_index{node.getInputs().at(operation::Fill::Input::VALUE)};
  OP_REQUIRES(isSameType(output_index, value_index));
  OP_REQUIRES(isValidType(input_index, {DataType::INT32, DataType::INT64}));
  OP_REQUIRES(isValidType(output_index,
                          {DataType::FLOAT32, DataType::INT32, DataType::INT64, DataType::BOOL8}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), OP_REQUIRES, onert::ir::operation::Fill::SHAPE, and onert::ir::operation::Fill::VALUE.
visit() [21/43]
void onert::ir::OperationValidator::visit (const operation::Gather & node) override
Definition at line 425 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Gather::INPUT)};
  const auto indices_index{node.getInputs().at(operation::Gather::INDICES)};
  const auto input_type = operandType(input_index);
  if (input_type == DataType::QUANT_GGML_Q4_0 || input_type == DataType::QUANT_GGML_Q8_0)
    OP_REQUIRES(isValidType(output_index, {DataType::FLOAT32}));
  else
    OP_REQUIRES(isSameType(output_index, input_index));
  OP_REQUIRES(isValidType(indices_index, {DataType::INT32, DataType::INT64}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Gather::INDICES, onert::ir::operation::Gather::INPUT, and OP_REQUIRES.
visit() [22/43]
void onert::ir::OperationValidator::visit (const operation::HashtableLookup & node) override
Definition at line 440 of file OperationValidator.cc.
{
  const auto hits_index{node.getOutputs().at(operation::HashtableLookup::Output::HITS)};
  const auto lookups_index{node.getInputs().at(operation::HashtableLookup::Input::LOOKUPS)};
  const auto keys_index{node.getInputs().at(operation::HashtableLookup::Input::KEYS)};
  OP_REQUIRES(isValidType(lookups_index, DataType::INT32));
  OP_REQUIRES(isValidType(keys_index, DataType::INT32));
  OP_REQUIRES(isValidType(hits_index, DataType::QUANT_UINT8_ASYMM));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::HashtableLookup::HITS, onert::ir::operation::HashtableLookup::KEYS, onert::ir::operation::HashtableLookup::LOOKUPS, and OP_REQUIRES.
visit() [23/43]
void onert::ir::OperationValidator::visit (const operation::Pack & node) override
Definition at line 451 of file OperationValidator.cc.
{
  const auto num{node.param().num};
  OP_REQUIRES(num == static_cast<int32_t>(node.getInputs().size()));
}
References onert::ir::Operation::getInputs(), onert::ir::operation::Pack::Param::num, OP_REQUIRES, onert::ir::operation::Pack::param(), and onert::ir::OperandIndexSequence::size().
visit() [24/43]
void onert::ir::OperationValidator::visit (const operation::Pad & node) override
Definition at line 458 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Pad::Input::INPUT)};
  const auto pad_index{node.getInputs().at(operation::Pad::Input::PAD)};
  bool isQuantType =
    isValidType(output_index, {DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM});
  bool isPadV2 = node.getInputs().size() == 3 ? true : false;
  OP_REQUIRES(isValidType(pad_index, DataType::INT32));
  OP_REQUIRES(isSameType(input_index, output_index));
  if (isQuantType)
    OP_REQUIRES(isSameQuantParam(input_index, output_index));
  if (isPadV2)
  {
    const auto value_index{node.getInputs().at(operation::Pad::Input::VALUE)};
    const bool cond_same = isSameType(input_index, value_index);
    const bool cond_same_quant = (!isQuantType || isSameQuantParam(input_index, value_index));
    const auto input_t = operandType(input_index);
    const auto value_t = operandType(value_index);
    // NNAPI accepts this case. scale and zeroPoint are assumed to be the same as in input0.
    const bool cond_quant8 =
      ((input_t == DataType::QUANT_UINT8_ASYMM || input_t == DataType::QUANT_INT8_ASYMM) &&
       value_t == DataType::INT32);
    OP_REQUIRES((cond_same && cond_same_quant) || cond_quant8);
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Pad::INPUT, OP_REQUIRES, onert::ir::operation::Pad::PAD, onert::ir::OperandIndexSequence::size(), and onert::ir::operation::Pad::VALUE.
visit() [25/43]
void onert::ir::OperationValidator::visit (const operation::Rank & node) override
Definition at line 488 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  OP_REQUIRES(isValidType(output_index, DataType::INT32));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getOutputs(), and OP_REQUIRES.
visit() [26/43]
void onert::ir::OperationValidator::visit (const operation::ResizeBilinear & node) override
Definition at line 495 of file OperationValidator.cc.
{
  auto align_corners = node.param().align_corners;
  auto half_pixel_centers = node.param().half_pixel_centers;
  OP_REQUIRES(!align_corners || !half_pixel_centers);
}
References onert::ir::operation::ResizeBilinear::Param::align_corners, onert::ir::operation::ResizeBilinear::Param::half_pixel_centers, OP_REQUIRES, and onert::ir::operation::ResizeBilinear::param().
visit() [27/43]
void onert::ir::OperationValidator::visit (const operation::Reverse & node) override
Definition at line 503 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Reverse::Input::INPUT)};
  const auto axis_index{node.getInputs().at(operation::Reverse::Input::AXIS)};
  OP_REQUIRES(isValidType(axis_index, DataType::INT32));
  OP_REQUIRES(isSameType(output_index, input_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::Reverse::AXIS, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Reverse::INPUT, and OP_REQUIRES.
visit() [28/43]
void onert::ir::OperationValidator::visit (const operation::RoPE & node) override
Definition at line 513 of file OperationValidator.cc.
{
  const auto input_index{node.getInputs().at(operation::RoPE::Input::INPUT)};
  const auto sin_index{node.getInputs().at(operation::RoPE::Input::SIN_TABLE)};
  const auto cos_index{node.getInputs().at(operation::RoPE::Input::COS_TABLE)};
  const auto output_index{node.getOutputs().at(operation::RoPE::Output::OUTPUT)};
  OP_REQUIRES(isValidType(input_index, DataType::FLOAT32));
  OP_REQUIRES(isValidType(sin_index, DataType::FLOAT32));
  OP_REQUIRES(isValidType(cos_index, DataType::FLOAT32));
  OP_REQUIRES(isSameType(input_index, output_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::RoPE::COS_TABLE, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::RoPE::INPUT, OP_REQUIRES, onert::ir::operation::RoPE::OUTPUT, and onert::ir::operation::RoPE::SIN_TABLE.
visit() [29/43]
void onert::ir::OperationValidator::visit (const operation::Select & node) override
Definition at line 526 of file OperationValidator.cc.
{
  const auto condition_index{node.getInputs().at(operation::Select::Input::CONDITION)};
  const auto input_true_index{node.getInputs().at(operation::Select::Input::INPUT_TRUE)};
  const auto input_false_index{node.getInputs().at(operation::Select::Input::INPUT_FALSE)};
  OP_REQUIRES(isValidType(condition_index, DataType::BOOL8));
  OP_REQUIRES(isSameType(input_true_index, input_false_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::Select::CONDITION, onert::ir::Operation::getInputs(), onert::ir::operation::Select::INPUT_FALSE, onert::ir::operation::Select::INPUT_TRUE, and OP_REQUIRES.
visit() [30/43]
void onert::ir::OperationValidator::visit (const operation::Shape & node) override
Definition at line 536 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  OP_REQUIRES(isValidType(output_index, {DataType::UINT32, DataType::INT32, DataType::INT64}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getOutputs(), and OP_REQUIRES.
visit() [31/43]
void onert::ir::OperationValidator::visit (const operation::Slice & node) override
Definition at line 543 of file OperationValidator.cc.
{
  const auto begins_index{node.getInputs().at(operation::Slice::BEGINS)};
  const auto sizes_index{node.getInputs().at(operation::Slice::SIZES)};
  OP_REQUIRES(isValidType(begins_index, {DataType::INT32, DataType::INT64}));
  OP_REQUIRES(isSameType(begins_index, sizes_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::Slice::BEGINS, onert::ir::Operation::getInputs(), OP_REQUIRES, and onert::ir::operation::Slice::SIZES.
visit() [32/43]
void onert::ir::OperationValidator::visit (const operation::Softmax & node) override
Definition at line 552 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Softmax::INPUT)};
  OP_REQUIRES(isSameType(input_index, output_index));
  OP_REQUIRES(isValidType(
    output_index, {DataType::FLOAT32, DataType::QUANT_UINT8_ASYMM, DataType::QUANT_INT8_ASYMM}));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Softmax::INPUT, and OP_REQUIRES.
visit() [33/43]
void onert::ir::OperationValidator::visit (const operation::SpaceToBatchND & node) override
Definition at line 562 of file OperationValidator.cc.
{
  const auto block_size_index{node.getInputs().at(operation::SpaceToBatchND::Input::BLOCK_SIZE)};
  const auto paddings_index{node.getInputs().at(operation::SpaceToBatchND::Input::PADDINGS)};
  // Non-constant block_size and padding is not implemented yet
  OP_REQUIRES(isConstant(block_size_index));
  OP_REQUIRES(isConstant(paddings_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::SpaceToBatchND::BLOCK_SIZE, onert::ir::Operation::getInputs(), OP_REQUIRES, and onert::ir::operation::SpaceToBatchND::PADDINGS.
visit() [34/43]
void onert::ir::OperationValidator::visit (const operation::SpaceToDepth & node) override
Definition at line 572 of file OperationValidator.cc.
{
  const auto block_size = node.param().block_size;
  OP_REQUIRES(block_size >= 1);
}
References onert::ir::operation::SpaceToDepth::Param::block_size, OP_REQUIRES, and onert::ir::operation::SpaceToDepth::param().
visit() [35/43]
void onert::ir::OperationValidator::visit (const operation::Split & node) override
Definition at line 578 of file OperationValidator.cc.
{
  const auto num_splits = node.param().num_splits;
  OP_REQUIRES(num_splits > 0 && num_splits <= 0xFFFF);
  OP_REQUIRES(node.getOutputs().size() == static_cast<uint32_t>(num_splits));
}
References onert::ir::Operation::getOutputs(), onert::ir::operation::Split::Param::num_splits, OP_REQUIRES, onert::ir::operation::Split::param(), and onert::ir::OperandIndexSequence::size().
visit() [36/43]
void onert::ir::OperationValidator::visit (const operation::SquaredDifference & node) override
Definition at line 586 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto lhs_index{node.getInputs().at(operation::SquaredDifference::Input::LHS)};
  const auto rhs_index{node.getInputs().at(operation::SquaredDifference::Input::RHS)};
  OP_REQUIRES(isSameType(output_index, lhs_index));
  OP_REQUIRES(isSameType(lhs_index, rhs_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::SquaredDifference::LHS, OP_REQUIRES, and onert::ir::operation::SquaredDifference::RHS.
visit() [37/43]
void onert::ir::OperationValidator::visit (const operation::StatelessRandomUniform & node) override
Definition at line 596 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto shape_index{node.getInputs().at(operation::StatelessRandomUniform::Input::SHAPE)};
  const auto seed_index{node.getInputs().at(operation::StatelessRandomUniform::Input::SEED)};
  OP_REQUIRES(isValidType(output_index, DataType::FLOAT32));
  OP_REQUIRES(isValidType(shape_index, DataType::INT32));
  OP_REQUIRES(isValidType(seed_index, DataType::INT32));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), OP_REQUIRES, onert::ir::operation::StatelessRandomUniform::SEED, and onert::ir::operation::StatelessRandomUniform::SHAPE.
visit() [38/43]
void onert::ir::OperationValidator::visit (const operation::StridedSlice & node) override
Definition at line 607 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::StridedSlice::Input::INPUT)};
  OP_REQUIRES(isSameType(output_index, input_index));
  if (isValidType(output_index, DataType::QUANT_INT16_SYMM))
  {
    OP_REQUIRES(isSameQuantParam(input_index, output_index));
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::StridedSlice::INPUT, and OP_REQUIRES.
visit() [39/43]
void onert::ir::OperationValidator::visit (const operation::TopKV2 & node) override
Definition at line 620 of file OperationValidator.cc.
{
  const auto output_value_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::TopKV2::Input::INPUT)};
  OP_REQUIRES(isSameType(output_value_index, input_index));
  OP_REQUIRES(node.param().k >= 0);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::TopKV2::INPUT, onert::ir::operation::TopKV2::Param::k, OP_REQUIRES, and onert::ir::operation::TopKV2::param().
visit() [40/43]
void onert::ir::OperationValidator::visit (const operation::Transpose & node) override
Definition at line 629 of file OperationValidator.cc.
{
  const auto output_index{node.getOutputs().at(0)};
  const auto input_index{node.getInputs().at(operation::Transpose::Input::INPUT)};
  OP_REQUIRES(isSameType(output_index, input_index));
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Transpose::INPUT, and OP_REQUIRES.
visit() [41/43]
void onert::ir::OperationValidator::visit (const operation::TransposeConv & node) override
Definition at line 637 of file OperationValidator.cc.
{
  OP_REQUIRES((node.param().padding.type == PaddingType::SAME) ||
              (node.param().padding.type == PaddingType::VALID));
}
References OP_REQUIRES, onert::ir::operation::TransposeConv::Param::padding, onert::ir::operation::TransposeConv::param(), onert::ir::SAME, onert::ir::Padding::type, and onert::ir::VALID.
visit() [42/43]
void onert::ir::OperationValidator::visit (const operation::Unpack & node) override
Definition at line 643 of file OperationValidator.cc.
{
  const auto num{node.param().num};
  OP_REQUIRES(num == static_cast<int32_t>(node.getOutputs().size()));
}
References onert::ir::Operation::getOutputs(), onert::ir::operation::Unpack::Param::num, OP_REQUIRES, onert::ir::operation::Unpack::param(), and onert::ir::OperandIndexSequence::size().
visit() [43/43]
void onert::ir::OperationValidator::visit (const operation::While & node) override
Definition at line 649 of file OperationValidator.cc.
{
  OP_REQUIRES(node.getInputs().size() == node.getOutputs().size());
}
References onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), OP_REQUIRES, and onert::ir::OperandIndexSequence::size().
The documentation for this class was generated from the following files:
runtime/onert/core/src/ir/OperationValidator.h
runtime/onert/core/src/ir/OperationValidator.cc