ONE - On-device Neural Engine: fme_apply::FMEqualizer Class Reference
fme_apply::FMEqualizer Class Reference final
#include <FMEqualizer.h>
Public Member Functions
void equalize (loco::Graph *g, std::vector< EqualizePattern > &p)
Detailed Description
Definition at line 27 of file FMEqualizer.h.
Member Function Documentation
equalize()
void fme_apply::FMEqualizer::equalize (loco::Graph * g, std::vector< EqualizePattern > & p)
Definition at line 63 of file FMEqualizer.cpp.
{
  THROW_UNLESS(g != nullptr, "Invalid argument g");
  // Check the patterns are valid on the graph
  check_patterns_valid(g, p);
  // Insert Scale/Shift based on patterns
  InsertScaleShift issp(p);
  issp.run(g);
  logo::Phase phase;
  // Default passes
  phase.emplace_back(std::make_unique<logo::RemoveDeadNodeWithQueryPass>());
  phase.emplace_back(std::make_unique<luci::CircleShapeInferencePass>());
  phase.emplace_back(std::make_unique<luci::CircleTypeInferencePass>());
  // Fuse Pre/Post Scale
  phase.emplace_back(std::make_unique<fme_apply::FusePreScalePass>());
  phase.emplace_back(std::make_unique<fme_apply::FusePostScalePass>());
  ProgressReporter prog(g, logo::PhaseStrategy::Saturate);
  logo::PhaseRunner<logo::PhaseStrategy::Saturate> phase_runner{g};
  phase_runner.attach(&prog);
  phase_runner.run(phase);
  // Check if all Scale/Shift nodes are removed
  check_no_scale(g);
}
References fme_apply::check_patterns_valid(), p, fme_apply::InsertScaleShift::run(), logo::Saturate, and THROW_UNLESS.
Referenced by entry().
The documentation for this class was generated from the following files:
compiler/fme-apply/src/FMEqualizer.h
compiler/fme-apply/src/FMEqualizer.cpp