ONE - On-device Neural Engine: coco::FeatureLayouts::BC Class Reference
coco::FeatureLayouts::BC Class Reference
BC (Channel-wise Channel-major) Feature Layout.
#include <FeatureLayouts.h>
Public Member Functions
const FeatureLayout::ID * id (void) const override
const FeatureShape & shape (void) const override
coco::ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override
Public Member Functions inherited from coco::FeatureLayout
virtual ~FeatureLayout ()=default
virtual const ID * id (void) const =0
virtual const FeatureShape & shape (void) const =0
uint32_t batch (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
virtual ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const FeatureLayout::ID * uid (void)
static std::unique_ptr< BC > create (const nncc::core::ADT::feature::Shape &shape)
Detailed Description
BC (Channel-wise Channel-major) Feature Layout.
A layout is said to be channel-wise if the following holds:
For each pair of valid feature index I and J, at(I) == at(J) if batch(I) == batch(J) and channel(I) == channel(J)
A layout is said to be channel-major if the followings hold:
For each pair of valid feature index I and J, at(I) + 1 == at(J) if batch(I) == batch(J) and channel(I) + 1 == channel(J)
For each pair of valid feature index I and J, at(I) + 1 == at(J) if batch(I) + 1 == batch(J), channel(I) == depth - 1, and channel(J) == 0
Definition at line 101 of file FeatureLayouts.h.
Member Function Documentation
at()
ElemID coco::FeatureLayouts::BC::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::FeatureLayout.
Definition at line 123 of file FeatureLayouts.cpp.
{
  assert(b < shape().batch());
  uint32_t offset = 0;
  offset += b * _shape.depth();
  offset += ch;
  return ElemID{offset};
}
References coco::FeatureLayout::batch(), nncc::core::ADT::feature::Shape::depth(), offset(), and shape().
create()
std::unique_ptr< BC > coco::FeatureLayouts::BC::create (const nncc::core::ADT::feature::Shape & shape) static
Definition at line 135 of file FeatureLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<BC>{new BC{FeatureShape{shape}}};
}
References shape().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::Conv2DGraphBuilder::build(), and tflimport::DepthwiseConv2DGraphBuilder::build().
id()
const FeatureLayout::ID * coco::FeatureLayouts::BC::id (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 111 of file FeatureLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
shape()
const FeatureShape & coco::FeatureLayouts::BC::shape (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 113 of file FeatureLayouts.h.
{ return _shape; }
Referenced by at(), and create().
uid()
const FeatureLayout::ID * coco::FeatureLayouts::BC::uid (void) static
Definition at line 113 of file FeatureLayouts.cpp.
{
  struct LayoutID final : public FeatureLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/FeatureLayouts.h
compiler/coco/core/src/IR/FeatureLayouts.cpp