ONE - On-device Neural Engine: flexbuffers::Map Class Reference
flexbuffers::Map Class Reference
#include <flexbuffers.h>
Public Member Functions
Map (const uint8_t *data, uint8_t byte_width)
Reference operator[] (const char *key) const
Reference operator[] (const std::string &key) const
Vector Values () const
TypedVector Keys () const
bool IsTheEmptyMap () const
Public Member Functions inherited from flexbuffers::Vector
Vector (const uint8_t *data, uint8_t byte_width)
Reference operator[] (size_t i) const
bool IsTheEmptyVector () const
Public Member Functions inherited from flexbuffers::Sized
Sized (const uint8_t *data, uint8_t byte_width)
Sized (const uint8_t *data, uint8_t byte_width, size_t sz)
size_t size () const
size_t read_size () const
Public Member Functions inherited from flexbuffers::Object
Object (const uint8_t *data, uint8_t byte_width)
Static Public Member Functions
static Map EmptyMap ()
Static Public Member Functions inherited from flexbuffers::Vector
static Vector EmptyVector ()
Additional Inherited Members
Protected Attributes inherited from flexbuffers::Sized
size_t size_
Protected Attributes inherited from flexbuffers::Object
const uint8_t * data_
uint8_t byte_width_
Detailed Description
Definition at line 347 of file flexbuffers.h.
Constructor & Destructor Documentation
Map()
flexbuffers::Map::Map (const uint8_t * data, uint8_t byte_width) inline
Definition at line 350 of file flexbuffers.h.
: Vector(data, byte_width) {}
Member Function Documentation
EmptyMap()
static Map flexbuffers::Map::EmptyMap () inline static
Definition at line 366 of file flexbuffers.h.
  {
    static const uint8_t empty_map[] = {
      0 /*keys_len*/, 0 /*keys_offset*/, 1 /*keys_width*/, 0 /*len*/
    };
    return Map(empty_map + 4, 1);
  }
Referenced by flexbuffers::Reference::AsMap(), and IsTheEmptyMap().
IsTheEmptyMap()
bool flexbuffers::Map::IsTheEmptyMap () const inline
Definition at line 374 of file flexbuffers.h.
{ return data_ == EmptyMap().data_; }
References flexbuffers::Object::data_, and EmptyMap().
Keys()
TypedVector flexbuffers::Map::Keys () const inline
Definition at line 357 of file flexbuffers.h.
  {
    const size_t num_prefixed_fields = 3;
    auto keys_offset = data_ - byte_width_ * num_prefixed_fields;
    return TypedVector(Indirect(keys_offset, byte_width_),
                       static_cast<uint8_t>(ReadUInt64(keys_offset + byte_width_, byte_width_)),
                       FBT_KEY);
  }
References flexbuffers::Object::byte_width_, flexbuffers::Object::data_, flexbuffers::FBT_KEY, flexbuffers::Indirect(), and flexbuffers::ReadUInt64().
Referenced by operator[](), circledump::CustomOpPrinter::options(), and tfldump::CustomOpPrinter::options().
operator[]() [1/2]
Reference flexbuffers::Map::operator[] (const char * key) const inline
Definition at line 977 of file flexbuffers.h.
{
  auto keys = Keys();
  // We can't pass keys.byte_width_ to the comparison function, so we have
  // to pick the right one ahead of time.
  int (*comp)(const void *, const void *) = nullptr;
  switch (keys.byte_width_)
  {
    case 1:
      comp = KeyCompare<uint8_t>;
      break;
    case 2:
      comp = KeyCompare<uint16_t>;
      break;
    case 4:
      comp = KeyCompare<uint32_t>;
      break;
    case 8:
      comp = KeyCompare<uint64_t>;
      break;
  }
  auto res = std::bsearch(key, keys.data_, keys.size(), keys.byte_width_, comp);
  if (!res)
    return Reference(nullptr, 1, NullPackedType());
  auto i = (reinterpret_cast<uint8_t *>(res) - keys.data_) / keys.byte_width_;
  return (*static_cast<const Vector *>(this))[i];
}
References Keys(), and flexbuffers::NullPackedType().
operator[]() [2/2]
Reference flexbuffers::Map::operator[] (const std::string & key) const inline
Definition at line 1005 of file flexbuffers.h.
{ return (*this)[key.c_str()]; }
Values()
Vector flexbuffers::Map::Values () const inline
Definition at line 355 of file flexbuffers.h.
{ return Vector(data_, byte_width_); }
References flexbuffers::Object::byte_width_, and flexbuffers::Object::data_.
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h