ONE - On-device Neural Engine: onert::exec::ExecutionObservee Class Reference
onert::exec::ExecutionObservee Class Reference
Class that.
#include <ExecutionObservee.h>
Public Member Functions
ExecutionObservee (const ExecObservers &observers, const ExecutionOptions &options)
Register enabled observers.
void notifySubgraphBegin (std::pair< ir::ModelIndex, ir::SubgraphIndex > ind) const
void notifySubgraphEnd (std::pair< ir::ModelIndex, ir::SubgraphIndex > ind) const
void notifyJobBegin (IExecutor *executor, std::pair< ir::ModelIndex, ir::SubgraphIndex > subg_ind, ir::OperationIndex op_ind, const backend::Backend *backend) const
void notifyJobEnd (IExecutor *executor, std::pair< ir::ModelIndex, ir::SubgraphIndex > subg_ind, ir::OperationIndex op_ind, const backend::Backend *backend) const
bool isEmpty () const
Detailed Description
Class that.
Definition at line 33 of file ExecutionObservee.h.
Constructor & Destructor Documentation
ExecutionObservee()
onert::exec::ExecutionObservee::ExecutionObservee (const ExecObservers & observers, const ExecutionOptions & options)
Register enabled observers.
Parameters
observer Observers generated by compiler
Definition at line 22 of file ExecutionObservee.cc.
{
  // TODO Use execution option
  if (options.dump_minmax)
  {
    auto observer = observers.get(ObserverType::MINMAX_DUMP);
    if (!observer)
      throw std::runtime_error{"MinMaxRecorder is only supported on LinearExecutor, single model"};
    _observers.emplace_back(observer);
  }
  if (options.trace)
  {
    auto observer = observers.get(ObserverType::TRACING);
    if (!observer)
      throw std::runtime_error{"Cannot find TracingObserver"};
    _observers.emplace_back(observer);
  }
  if (options.profile)
  {
    auto observer = observers.get(ObserverType::PROFILE);
    if (!observer)
      throw std::runtime_error{
        "Profiling is only supported on DataflowExecutor with heterogenous scheduler"};
    _observers.emplace_back(observer);
  }
}
References onert::exec::ExecObservers::get(), onert::exec::MINMAX_DUMP, onert::exec::PROFILE, and onert::exec::TRACING.
Member Function Documentation
isEmpty()
bool onert::exec::ExecutionObservee::isEmpty () const inline
Definition at line 48 of file ExecutionObservee.h.
{ return _observers.size() == 0; }
Referenced by onert::exec::LinearExecutor::executeImpl().
notifyJobBegin()
void onert::exec::ExecutionObservee::notifyJobBegin (IExecutor * executor, std::pair< ir::ModelIndex, ir::SubgraphIndex > subg_ind, ir::OperationIndex op_ind, const backend::Backend * backend) const
Definition at line 71 of file ExecutionObservee.cc.
{
  for (auto &&o : _observers)
  {
    o->handleJobBegin(executor, subg_ind, op_ind, backend);
  }
}
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::LinearExecutor::executeImpl(), and onert::exec::ParallelExecutor::executeImpl().
notifyJobEnd()
void onert::exec::ExecutionObservee::notifyJobEnd (IExecutor * executor, std::pair< ir::ModelIndex, ir::SubgraphIndex > subg_ind, ir::OperationIndex op_ind, const backend::Backend * backend) const
Definition at line 82 of file ExecutionObservee.cc.
{
  for (auto &&o : _observers)
  {
    o->handleJobEnd(executor, subg_ind, op_ind, backend);
  }
}
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::LinearExecutor::executeImpl(), and onert::exec::ParallelExecutor::executeImpl().
notifySubgraphBegin()
void onert::exec::ExecutionObservee::notifySubgraphBegin (std::pair< ir::ModelIndex, ir::SubgraphIndex > ind) const
Definition at line 55 of file ExecutionObservee.cc.
{
  for (auto &&o : _observers)
  {
    o->handleSubgraphBegin(ind);
  }
}
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::LinearExecutor::executeImpl(), and onert::exec::ParallelExecutor::executeImpl().
notifySubgraphEnd()
void onert::exec::ExecutionObservee::notifySubgraphEnd (std::pair< ir::ModelIndex, ir::SubgraphIndex > ind) const
Definition at line 63 of file ExecutionObservee.cc.
{
  for (auto &&o : _observers)
  {
    o->handleSubgraphEnd(ind);
  }
}
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::LinearExecutor::executeImpl(), and onert::exec::ParallelExecutor::executeImpl().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/ExecutionObservee.h
runtime/onert/core/src/exec/ExecutionObservee.cc