ONE - On-device Neural Engine: nnkit::support::onnx::Status Class Reference
nnkit::support::onnx::Status Class Reference
#include <Status.h>
Public Member Functions
Status ()
Status (OrtStatus *status)
~Status ()
Status & operator= (OrtStatus *status)
bool isError (void)
void throwOnError (void)
Detailed Description
Definition at line 32 of file Status.h.
Constructor & Destructor Documentation
Status() [1/2]
nnkit::support::onnx::Status::Status () inline
Definition at line 35 of file Status.h.
           : _status(nullptr)
  {
    // DO NOTHING
  }
Status() [2/2]
nnkit::support::onnx::Status::Status (OrtStatus * status) inline
Definition at line 40 of file Status.h.
                            : _status(status)
  {
    // DO NOTHING
  }
~Status()
nnkit::support::onnx::Status::~Status () inline
Definition at line 45 of file Status.h.
  {
    if (_status)
    {
      OrtReleaseStatus(_status);
    }
  }
Member Function Documentation
isError()
bool nnkit::support::onnx::Status::isError (void) inline
Definition at line 63 of file Status.h.
{ return (_status != nullptr); }
Referenced by nnkit::support::onnx::Runner::Runner().
operator=()
Status & nnkit::support::onnx::Status::operator= (OrtStatus * status) inline
Definition at line 53 of file Status.h.
  {
    if (_status)
    {
      OrtReleaseStatus(_status);
    }
    _status = status;
    return *this;
  }
throwOnError()
void nnkit::support::onnx::Status::throwOnError (void) inline
Definition at line 65 of file Status.h.
  {
    if (_status)
    {
      const char *msg = OrtGetErrorMessage(_status);
      std::string err{msg};
      OrtReleaseStatus(_status);
      throw std::runtime_error{err};
    }
  }
Referenced by nnkit::support::onnx::Allocator::Allocator(), nnkit::support::onnx::TensorContext::getConstFloatTensor(), nnkit::support::onnx::TensorContext::getMutableFloatTensor(), nnkit::support::onnx::Runner::prepareInputs(), nnkit::support::onnx::Runner::prepareOutputs(), nnkit::support::onnx::Runner::run(), and nnkit::support::onnx::TensorSet::set().
The documentation for this class was generated from the following file:
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/Status.h