ONE - On-device Neural Engine: nest::VarContext Class Reference
nest::VarContext Class Reference
#include <VarContext.h>
Public Member Functions
uint32_t count (void) const
Var make (void)
Bound & bound (const Var &)
const Bound & bound (const Var &) const
Detailed Description
Definition at line 28 of file VarContext.h.
Member Function Documentation
bound() [1/2]
Bound & nest::VarContext::bound (const Var & var)
Definition at line 33 of file VarContext.cpp.
{ return _bound.at(var.id().value()); }
References nest::Var::id(), and nest::VarID::value().
bound() [2/2]
const Bound & nest::VarContext::bound (const Var & var) const
Definition at line 34 of file VarContext.cpp.
{ return _bound.at(var.id().value()); }
References nest::Var::id(), and nest::VarID::value().
count()
uint32_t nest::VarContext::count (void) const
Definition at line 22 of file VarContext.cpp.
{ return _bound.size(); }
Referenced by make(), and nest::Schedule::Schedule().
make()
Var nest::VarContext::make (void)
Definition at line 24 of file VarContext.cpp.
{
  const VarID vid{count()};
  _bound.emplace_back(0, 0);
  return Var{vid};
}
References count().
The documentation for this class was generated from the following files:
compiler/nest/core/include/nest/VarContext.h
compiler/nest/core/src/VarContext.cpp