ONE - On-device Neural Engine: fme_apply::FusePostShiftPass Class Reference
fme_apply::FusePostShiftPass Class Reference
Pass to fuse CircleCustom(PostShift) to preceding Ops.
#include <FusePostShiftPass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to fuse CircleCustom(PostShift) to preceding Ops.
BEFORE
        [Node1]
          |
         [Op]
        /    \
[PostShift] [Node2]
AFTER
  [Node1]
   /  \
[Op'] [Op] | [Node2]
NOTE Op' is clone of Op with updated bias.
Definition at line 48 of file FusePostShiftPass.h.
Member Function Documentation
name()
virtual const char * fme_apply::FusePostShiftPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 51 of file FusePostShiftPass.h.
{ return "fme::FusePostShiftPass"; }
run()
bool fme_apply::FusePostShiftPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 225 of file FusePostShiftPass.cpp.
{
  bool changed = false;
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    FusePostShift fps;
    auto cnode = loco::must_cast<luci::CircleNode *>(node);
    if (cnode->accept(&fps))
      changed = true;
  }
  return changed;
}
References loco::output_nodes(), and loco::postorder_traversal().
Referenced by package.libnnfw_api_pybind.nnfw_session::inference().
The documentation for this class was generated from the following files:
compiler/fme-apply/src/pass/FusePostShiftPass.h
compiler/fme-apply/src/pass/FusePostShiftPass.cpp