ONE - On-device Neural Engine: onert::backend::cpu::ops::SplitVLayer Class Reference
onert::backend::cpu::ops::SplitVLayer Class Reference
#include <SplitVLayer.h>
Public Member Functions
SplitVLayer ()
template<typename T >
void splitV (void)
void configure (const IPortableTensor *input, const IPortableTensor *size_splits, const IPortableTensor *size_dim, uint16_t num_splits, std::vector< IPortableTensor * > &outputs)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file SplitVLayer.h.
Constructor & Destructor Documentation
SplitVLayer()
onert::backend::cpu::ops::SplitVLayer::SplitVLayer ()
Definition at line 32 of file SplitVLayer.cc.
  : _input(nullptr), _size_splits(nullptr), _split_dim(nullptr), _num_splits(0), _outputs()
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::SplitVLayer::configure (const IPortableTensor * input, const IPortableTensor * size_splits, const IPortableTensor * size_dim, uint16_t num_splits, std::vector< IPortableTensor * > & outputs)
Definition at line 59 of file SplitVLayer.cc.
{
  assert(input != nullptr);
  _num_splits = num_splits;
  _size_splits = size_splits;
  _input = input;
  _split_dim = split_dim;
  _outputs = outputs;
}
run()
void onert::backend::cpu::ops::SplitVLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 72 of file SplitVLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    splitV<float>();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    splitV<uint8_t>();
  }
  else if (_input->data_type() == OperandType::INT32)
  {
    splitV<int32_t>();
  }
  else if (_input->data_type() == OperandType::INT64)
  {
    splitV<int64_t>();
  }
  else
  {
    throw std::runtime_error{"SplitV: unsupported input type"};
  }
}
References onert::backend::ITensor::data_type().
splitV()
template<typename T > void onert::backend::cpu::ops::SplitVLayer::splitV (void)
Definition at line 38 of file SplitVLayer.cc.
{
  nnfw::cker::SplitVParams op_params;
  op_params.axis = *getBuffer<int32_t>(_split_dim);
  op_params.num_split = _num_splits;
  std::vector<T *> outputPtrs;
  std::vector<nnfw::cker::Shape> outshape;
  for (const auto output : _outputs)
  {
    assert(output->total_size() == sizeOfData(output->data_type(), output->getShape().dims()));
    outputPtrs.emplace_back(getBuffer<T>(output));
    outshape.emplace_back(getShape(output));
  }
  assert(_input->total_size() == sizeOfData(_input->data_type(), _input->getShape().dims()));
  nnfw::cker::SplitV<T>(op_params, getShape(_input), getBuffer<T>(_input), outshape,
                        outputPtrs.data());
}
References nnfw::cker::SplitVParams::axis, onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), onert::backend::cpu::ops::getShape(), nnfw::cker::SplitVParams::num_split, onert::backend::cpu::ops::sizeOfData(), and onert::backend::ITensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/SplitVLayer.h
runtime/onert/backend/cpu/ops/SplitVLayer.cc