ONE - On-device Neural Engine: onert::compiler::train::pass::TrainableConstantInsertionPass Class Reference
onert::compiler::train::pass::TrainableConstantInsertionPass Class Reference
#include <TrainableConstantInsertionPass.h>
Public Member Functions
std::string id () final
Returns string id for this pass. Same with class name.
void callback (const ir::OperationIndex &index, ir::IOperation &node) final
Be called for all nodes of graph.
Public Member Functions inherited from onert::compiler::pass::LoweredOperationPass
LoweredOperationPass (ILoweredGraph &lowered_graph)
virtual ~LoweredOperationPass ()=default
Public Member Functions inherited from onert::compiler::pass::OperationPass
virtual ~OperationPass ()=default
void run () final
Run the pass.
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
Public Member Functions inherited from onert::compiler::pass::IPass
virtual ~IPass ()=default
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::LoweredOperationPass
ILoweredGraph & _lowered_graph
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Definition at line 27 of file TrainableConstantInsertionPass.h.
Member Function Documentation
callback()
void onert::compiler::train::pass::TrainableConstantInsertionPass::callback (const ir::OperationIndex & index, ir::IOperation & node) final virtual
Be called for all nodes of graph.
Parameters
index is the index of a node in graph
node is the node in graph
Implements onert::compiler::pass::LoweredOperationPass.
Definition at line 25 of file TrainableConstantInsertionPass.cc.
{
  for (const auto &input : node.getUsedInputSet())
  {
    auto &object = _graph.operands().at(input);
    // Skip if the operand is not constant or not shared constant
    if (!object.isConstant() || object.getUses().size() < 2)
      continue;
    // Insert new operands for shared constant except for the current node.
    const auto uses(object.getUses());
    for (const auto &use_index : uses)
    {
      if (use_index == node_index)
        continue;
      // NOTE The PermuteFactor(backend) of the current node and the use node may be different.
      //      But there is no problem because both nodes' constant operand will have
      //      only one use node.
      const auto new_index = insertNewOperand(object);
      updateUseDef(input, new_index, use_index);
    }
    // The input of the current node will have one use as the current node
    assert(object.getUses().size() == 1 && object.getUses().contains(node_index));
  }
}
References onert::compiler::pass::Pass::_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::IOperation::getUsedInputSet(), onert::ir::Graph::operands(), and size.
id()
std::string onert::compiler::train::pass::TrainableConstantInsertionPass::id () inline final virtual
Returns string id for this pass. Same with class name.
Returns
string id
Implements onert::compiler::pass::LoweredOperationPass.
Definition at line 33 of file TrainableConstantInsertionPass.h.
{ return "TrainableConstantInsertionPass"; }
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.h
runtime/onert/core/src/compiler/train/pass/TrainableConstantInsertionPass.cc