ONE - On-device Neural Engine: luci_interpreter::IMemoryManager Class Reference
luci_interpreter::IMemoryManager Class Reference abstract
#include <MemoryManager.h>
Public Member Functions
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
virtual void allocate_memory (luci_interpreter::Tensor &tensor)=0
virtual void release_memory (luci_interpreter::Tensor &tensor)=0
virtual ~IMemoryManager ()=default
bool is_allocate_input () const
void is_allocate_input (bool allocate_input)
virtual void allocate_input_buf ()=0
virtual void allocate_output_buf ()=0
virtual void allocate_computing_buf ()=0
virtual void release_computing_buf ()=0
virtual void release_input_buf ()=0
virtual void release_output_buf ()=0
virtual void allocate_memory_for_input (luci_interpreter::Tensor &tensor)=0
virtual void allocate_memory_for_output (luci_interpreter::Tensor &tensor)=0
Protected Attributes
bool _is_allocate_input = true
Detailed Description
Definition at line 26 of file MemoryManager.h.
Constructor & Destructor Documentation
~IMemoryManager() [1/2]
virtual luci_interpreter::IMemoryManager::~IMemoryManager () virtual default
~IMemoryManager() [2/2]
virtual luci_interpreter::IMemoryManager::~IMemoryManager () virtual default
Member Function Documentation
allocate_computing_buf()
virtual void luci_interpreter::IMemoryManager::allocate_computing_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::configure().
allocate_input_buf()
virtual void luci_interpreter::IMemoryManager::allocate_input_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::GraphLoader::initInputTensors().
allocate_memory() [1/2]
virtual void luci_interpreter::IMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, luci_interpreter::TestMemoryManager, luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, and luci_interpreter::TestMemoryManager.
Referenced by luci_interpreter::RuntimeGraph::TensorAllocPlan::allocate(), luci_interpreter::StaticRuntimeGraph::configure(), luci_interpreter::RuntimeGraph::configureAllocations(), luci_interpreter::IBaseRuntimeGraph::configureAllocations(), luci_interpreter::GraphLoader::initInputOutputTensors(), luci_interpreter::GraphLoader::initInputTensors(), luci_interpreter::GraphLoader::loadTensors(), and luci_interpreter::kernels::testing::makeInputTensor().
allocate_memory() [2/2]
virtual void luci_interpreter::IMemoryManager::allocate_memory (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, luci_interpreter::TestMemoryManager, luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, and luci_interpreter::TestMemoryManager.
allocate_memory_for_input()
virtual void luci_interpreter::IMemoryManager::allocate_memory_for_input (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::GraphLoader::loadOperators().
allocate_memory_for_output()
virtual void luci_interpreter::IMemoryManager::allocate_memory_for_output (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::configure().
allocate_output_buf()
virtual void luci_interpreter::IMemoryManager::allocate_output_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::configure().
is_allocate_input() [1/2]
bool luci_interpreter::IMemoryManager::is_allocate_input () const inline
Definition at line 34 of file MemoryManager.h.
{ return _is_allocate_input; }
References _is_allocate_input.
Referenced by luci_interpreter::GraphLoader::initInputTensors().
is_allocate_input() [2/2]
void luci_interpreter::IMemoryManager::is_allocate_input (bool allocate_input) inline
Definition at line 35 of file MemoryManager.h.
{ _is_allocate_input = allocate_input; }
References _is_allocate_input.
release_computing_buf()
virtual void luci_interpreter::IMemoryManager::release_computing_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::execute(), and luci_interpreter::StaticRuntimeGraph::~StaticRuntimeGraph().
release_input_buf()
virtual void luci_interpreter::IMemoryManager::release_input_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::~StaticRuntimeGraph().
release_memory() [1/2]
virtual void luci_interpreter::IMemoryManager::release_memory (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, luci_interpreter::TestMemoryManager, luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, and luci_interpreter::TestMemoryManager.
Referenced by luci_interpreter::RuntimeGraph::TensorAllocPlan::deallocate(), and luci_interpreter::RuntimeGraph::~RuntimeGraph().
release_memory() [2/2]
virtual void luci_interpreter::IMemoryManager::release_memory (luci_interpreter::Tensor & tensor) pure virtual
Implemented in luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, luci_interpreter::TestMemoryManager, luci_interpreter::BuddyMemoryManager, luci_interpreter::SimpleMemoryManager, luci_interpreter::StaticMemoryManager, and luci_interpreter::TestMemoryManager.
release_output_buf()
virtual void luci_interpreter::IMemoryManager::release_output_buf () pure virtual
Implemented in luci_interpreter::SimpleMemoryManager, and luci_interpreter::StaticMemoryManager.
Referenced by luci_interpreter::StaticRuntimeGraph::~StaticRuntimeGraph().
Field Documentation
_is_allocate_input
bool luci_interpreter::IMemoryManager::_is_allocate_input = true protected
Definition at line 62 of file MemoryManager.h.
Referenced by luci_interpreter::StaticMemoryManager::allocate_input_buf(), and is_allocate_input().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/MemoryManager.h
onert-micro/luci-interpreter/src/memory_managers/MemoryManager.h