ONE - On-device Neural Engine: onert::backend::xnnpack::BackendContext Class Reference
onert::backend::xnnpack::BackendContext Class Reference
#include <BackendContext.h>
Public Member Functions
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< TensorBuilder > tensor_builder=nullptr, std::shared_ptr< KernelGenerator > kernel_gen=nullptr)
ITensorRegistry * genTensors () override
FunctionMap genKernels () override
std::shared_ptr< ExternalContext > external_context ()
Public Member Functions inherited from onert::backend::BackendContext
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~BackendContext ()=default
const Backend * backend () const
const ir::Graph * graph () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
const ContextData & data () const
virtual ITensorRegistry * genTensors ()=0
virtual FunctionMap genKernels ()=0
Data Fields
std::shared_ptr< TensorBuilder > tensor_builder
std::shared_ptr< KernelGenerator > kernel_gen
Data Fields inherited from onert::backend::BackendContext
std::shared_ptr< ITensorRegistry > tensor_registry
Additional Inherited Members
Protected Attributes inherited from onert::backend::BackendContext
const Backend * _backend {nullptr}
ContextData _data
Detailed Description
Definition at line 35 of file BackendContext.h.
Constructor & Destructor Documentation
BackendContext()
onert::backend::xnnpack::BackendContext::BackendContext (const Backend * backend, ContextData && data, std::shared_ptr< ITensorRegistry > tensor_registry = nullptr, std::shared_ptr< TensorBuilder > tensor_builder = nullptr, std::shared_ptr< KernelGenerator > kernel_gen = nullptr) inline
Definition at line 38 of file BackendContext.h.
    : onert::backend::BackendContext(backend, std::move(data), tensor_registry),
      tensor_builder{tensor_builder}, kernel_gen{kernel_gen}, _external_context(nullptr)
  {
    int num_threads = util::getConfigInt(util::config::XNNPACK_THREADS);
    if (num_threads < 1)
      num_threads = kDefaultNumThreadpoolThreads; // default num of threads
    _external_context.reset(new ExternalContext(static_cast<size_t>(num_threads)));
  }
References onert::util::getConfigInt(), and kDefaultNumThreadpoolThreads.
Member Function Documentation
external_context()
std::shared_ptr< ExternalContext > onert::backend::xnnpack::BackendContext::external_context () inline
Definition at line 54 of file BackendContext.h.
{ return _external_context; }
genKernels()
FunctionMap onert::backend::xnnpack::BackendContext::genKernels () override virtual
Implements onert::backend::BackendContext.
Definition at line 36 of file BackendContext.cc.
{
  FunctionMap ret;
  for (auto op_ind : _data.op_order)
  {
    auto fn_seq = kernel_gen->generate(op_ind);
    ret.emplace_back(op_ind, std::move(fn_seq));
  }
  basic::initConsts(*this);
  // NOTE For memory optimization, we want to free some operand data
  const_cast<ir::Graph &>(*_data.graph)
    .operands()
    .iterate([&](const ir::OperandIndex &, ir::Operand &obj) { obj.releaseData(); });
  for (auto &it : ret)
  {
    auto &fn_seq = it.second;
    fn_seq->iterate([&](exec::IFunction &ifunc) { ifunc.prepare(); });
  }
  return ret;
}
References onert::backend::BackendContext::_data, onert::backend::ContextData::graph, onert::backend::basic::initConsts(), kernel_gen, onert::backend::ContextData::op_order, and onert::exec::IFunction::prepare().
genTensors()
ITensorRegistry * onert::backend::xnnpack::BackendContext::genTensors () override virtual
Implements onert::backend::BackendContext.
Definition at line 34 of file BackendContext.cc.
{ return basic::genTensors(*this); }
References onert::backend::basic::genTensors().
Field Documentation
kernel_gen
std::shared_ptr<KernelGenerator> onert::backend::xnnpack::BackendContext::kernel_gen
Definition at line 59 of file BackendContext.h.
Referenced by genKernels().
tensor_builder
std::shared_ptr<TensorBuilder> onert::backend::xnnpack::BackendContext::tensor_builder
Definition at line 58 of file BackendContext.h.
The documentation for this class was generated from the following files:
runtime/onert/backend/xnnpack/BackendContext.h
runtime/onert/backend/xnnpack/BackendContext.cc