ONE - On-device Neural Engine: loco::DepthwiseFilterIndex Class Reference
loco::DepthwiseFilterIndex Class Reference final
DepthwiseFilter Index.
#include <DepthwiseFilterIndex.h>
Public Member Functions
DepthwiseFilterIndex ()=default
const uint32_t & channel (void) const
uint32_t & channel (void)
const uint32_t & nth (void) const
uint32_t & nth (void)
const uint32_t & row (void) const
uint32_t & row (void)
const uint32_t & column (void) const
uint32_t & column (void)
Detailed Description
DepthwiseFilter Index.
DepthwiseFilter Index indicates an "element" in a given Depthwise convolution filter.
Assume there is a filter K where KS denotes its shape (of DepthwiseFilterShape type).
Then, any valid filter index I satisfies the following invariants:
0 <= I.channel() < KS.depth()
0 <= I.nth() < KS.multiplier()
0 <= I.row() < KS.height()
0 <= I.column() < KS.width()
Definition at line 38 of file DepthwiseFilterIndex.h.
Constructor & Destructor Documentation
DepthwiseFilterIndex()
loco::DepthwiseFilterIndex::DepthwiseFilterIndex () default
Member Function Documentation
channel() [1/2]
uint32_t & loco::DepthwiseFilterIndex::channel (void) inline
Definition at line 45 of file DepthwiseFilterIndex.h.
{ return _channel; }
channel() [2/2]
const uint32_t & loco::DepthwiseFilterIndex::channel (void) const inline
Definition at line 44 of file DepthwiseFilterIndex.h.
{ return _channel; }
Referenced by loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
column() [1/2]
uint32_t & loco::DepthwiseFilterIndex::column (void) inline
Definition at line 54 of file DepthwiseFilterIndex.h.
{ return _column; }
column() [2/2]
const uint32_t & loco::DepthwiseFilterIndex::column (void) const inline
Definition at line 53 of file DepthwiseFilterIndex.h.
{ return _column; }
Referenced by loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
nth() [1/2]
uint32_t & loco::DepthwiseFilterIndex::nth (void) inline
Definition at line 48 of file DepthwiseFilterIndex.h.
{ return _nth; }
nth() [2/2]
const uint32_t & loco::DepthwiseFilterIndex::nth (void) const inline
Definition at line 47 of file DepthwiseFilterIndex.h.
{ return _nth; }
Referenced by loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
row() [1/2]
uint32_t & loco::DepthwiseFilterIndex::row (void) inline
Definition at line 51 of file DepthwiseFilterIndex.h.
{ return _row; }
row() [2/2]
const uint32_t & loco::DepthwiseFilterIndex::row (void) const inline
Definition at line 50 of file DepthwiseFilterIndex.h.
{ return _row; }
Referenced by loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::DepthwiseFilter >::value().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/DepthwiseFilterIndex.h