ONE - On-device Neural Engine: luci_interpreter::kernels::Concatenation Class Reference
luci_interpreter::kernels::Concatenation Class Reference
#include <Concatenation.h>
Public Member Functions
Concatenation (std::vector< const Tensor * > inputs, Tensor *output, const ConcatenationParams &params)
const Tensor * input (int index) const
Tensor * output () const
void configure () override
void execute () const override
Concatenation (std::vector< const Tensor * > inputs, Tensor *output, const ConcatenationParams &params)
const Tensor * input (int index) const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< ConcatenationParams >
const ConcatenationParams & params () const
const ConcatenationParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< ConcatenationParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ConcatenationParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ConcatenationParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< ConcatenationParams >
const ConcatenationParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Concatenation.h.
Constructor & Destructor Documentation
Concatenation() [1/2]
luci_interpreter::kernels::Concatenation::Concatenation (std::vector< const Tensor * > inputs, Tensor * output, const ConcatenationParams & params)
Definition at line 30 of file Concatenation.cpp.
  : KernelWithParams<ConcatenationParams>(std::move(inputs), {output}, params)
{
}
References output().
Concatenation() [2/2]
luci_interpreter::kernels::Concatenation::Concatenation (std::vector< const Tensor * > inputs, Tensor * output, const ConcatenationParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Concatenation::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 36 of file Concatenation.cpp.
{
  const int num_inputs = _inputs.size();
  LUCI_INTERPRETER_CHECK(num_inputs > 0);
  const Tensor *t0 = _inputs[0];
  // TODO: Support concat with fused activation function
  LUCI_INTERPRETER_CHECK(params().activation == luci::FusedActFunc::NONE);
  int axis = _params.axis;
  if (axis < 0)
    axis += t0->shape().num_dims();
  LUCI_INTERPRETER_CHECK(axis >= 0 && axis < t0->shape().num_dims());
  int32_t sum_axis = t0->shape().dim(axis);
  for (int i = 1; i < num_inputs; ++i)
  {
    const Tensor *tensor = _inputs[i];
    LUCI_INTERPRETER_CHECK(tensor->element_type() == t0->element_type());
    LUCI_INTERPRETER_CHECK(tensor->shape().num_dims() == t0->shape().num_dims());
    for (int d = 0; d < t0->shape().num_dims(); ++d)
    {
      if (d == axis)
      {
        sum_axis += tensor->shape().dim(axis);
      }
      else
      {
        LUCI_INTERPRETER_CHECK(tensor->shape().dim(d) == t0->shape().dim(d));
      }
    }
  }
  Shape output_shape = t0->shape();
  output_shape.dim(axis) = sum_axis;
  // If input tensors are INT8 type then quantization parameters of all input tensors and the output
  // should be the same
  for (auto current_tensor : _inputs)
  {
    if (current_tensor->element_type() == DataType::S8)
    {
      LUCI_INTERPRETER_CHECK(current_tensor->quantized_dimension() ==
                             output()->quantized_dimension());
      LUCI_INTERPRETER_CHECK(current_tensor->zero_points().size() ==
                             current_tensor->scales().size());
      LUCI_INTERPRETER_CHECK(current_tensor->zero_points() == output()->zero_points());
      LUCI_INTERPRETER_CHECK(current_tensor->scales() == output()->scales());
    }
  }
  output()->resize(output_shape);
}
References luci_interpreter::Kernel::_inputs, luci_interpreter::KernelWithParams< ConcatenationParams >::_params, luci_interpreter::ConcatenationParams::axis, luci_interpreter::Shape::dim(), luci_interpreter::Tensor::element_type(), LUCI_INTERPRETER_CHECK, luci::NONE, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< ConcatenationParams >::params(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Concatenation::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Concatenation::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 90 of file Concatenation.cpp.
{
  switch (_inputs[0]->element_type())
  {
    case DataType::FLOAT32:
      evalGeneric<float>();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    case DataType::S8:
      evalGeneric<int8_t>();
      break;
    case DataType::S32:
      evalGeneric<int32_t>();
      break;
    case DataType::S64:
      evalGeneric<int64_t>();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::Kernel::_inputs.
execute() [2/2]
void luci_interpreter::kernels::Concatenation::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Concatenation::input (int index) const inline
Definition at line 34 of file Concatenation.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
input() [2/2]
const Tensor * luci_interpreter::kernels::Concatenation::input (int index) const inline
Definition at line 34 of file Concatenation.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Concatenation::output () const inline
Definition at line 35 of file Concatenation.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by Concatenation(), and configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Concatenation::output () const inline
Definition at line 35 of file Concatenation.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Concatenation.h
onert-micro/luci-interpreter/src/kernels/Concatenation.h
compiler/luci-interpreter/src/kernels/Concatenation.cpp
onert-micro/luci-interpreter/src/kernels/Concatenation.cpp