ONE - On-device Neural Engine: onert::backend::trix::ops::BulkPipelineManager Class Reference
onert::backend::trix::ops::BulkPipelineManager Class Reference
#include <BulkPipelineManager.h>
Data Structures
struct PipelineConfig
Public Member Functions
BulkPipelineManager (const PipelineConfig &config)
~BulkPipelineManager ()
BulkPipelineManager (const BulkPipelineManager &)=delete
BulkPipelineManager & operator= (const BulkPipelineManager &)=delete
bool initialize ()
void shutdown ()
bool isInitialized () const
void execute (const std::vector< const IPortableTensor * > &inputs, std::vector< IPortableTensor * > &outputs)
Detailed Description
Definition at line 33 of file BulkPipelineManager.h.
Constructor & Destructor Documentation
BulkPipelineManager() [1/2]
onert::backend::trix::ops::BulkPipelineManager::BulkPipelineManager (const PipelineConfig & config) explicit
Definition at line 28 of file BulkPipelineManager.cc.
                                                                     : _config(config)
{
  // DO NOTHING
}
~BulkPipelineManager()
onert::backend::trix::ops::BulkPipelineManager::~BulkPipelineManager ()
Definition at line 33 of file BulkPipelineManager.cc.
{ shutdown(); }
References shutdown().
BulkPipelineManager() [2/2]
onert::backend::trix::ops::BulkPipelineManager::BulkPipelineManager (const BulkPipelineManager &) delete
Member Function Documentation
execute()
void onert::backend::trix::ops::BulkPipelineManager::execute (const std::vector< const IPortableTensor * > & inputs, std::vector< IPortableTensor * > & outputs)
Definition at line 85 of file BulkPipelineManager.cc.
{
  if (!_initialized.load())
  {
    throw std::runtime_error("Pipeline is not initialized");
  }
  if (_models.empty())
  {
    throw std::runtime_error("No models in pipeline");
  }
  _executing = true;
  try
  {
    auto current_inputs = inputs;
    auto current_outputs = outputs;
    for (size_t i = 0; i < _models.size(); ++i)
    {
      auto &model = _models[i];
      if (!model || !model->isPrepared())
      {
        throw std::runtime_error("Model at index " + std::to_string(i) + " is not prepared");
      }
      // Wait for buffer ready before execution
      model->waitForBufferReady();
      // Execute model
      model->run(current_inputs, current_outputs);
      // The input of the next model is the output of the current model
      if (i < _models.size() - 1)
      {
        current_inputs.clear();
        for (const auto &output : current_outputs)
        {
          current_inputs.push_back(const_cast<IPortableTensor *>(output));
        }
      }
    }
  }
  catch (...)
  {
    _executing = false;
    throw;
  }
  _executing = false;
}
initialize()
bool onert::backend::trix::ops::BulkPipelineManager::initialize ()
Definition at line 35 of file BulkPipelineManager.cc.
{
  if (_initialized.load())
  {
    // Already initialized
    return true;
  }
  try
  {
    createModels();
    prepareModels();
    _initialized = true;
    return true;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Failed to initialize pipeline: " + std::string(e.what()) << std::endl;
    shutdown();
    return false;
  }
}
References shutdown().
isInitialized()
bool onert::backend::trix::ops::BulkPipelineManager::isInitialized () const inline
Definition at line 52 of file BulkPipelineManager.h.
{ return _initialized; }
operator=()
BulkPipelineManager & onert::backend::trix::ops::BulkPipelineManager::operator= (const BulkPipelineManager &) delete
shutdown()
void onert::backend::trix::ops::BulkPipelineManager::shutdown ()
Definition at line 59 of file BulkPipelineManager.cc.
{
  if (!_initialized.load())
  {
    return;
  }
  _initialized = false;
  // Wait until all executions are finished
  while (_executing.load())
  {
    std::this_thread::sleep_for(std::chrono::milliseconds(1));
  }
  // Release models and clear buffer pool
  for (auto &model : _models)
  {
    if (model)
    {
      model->release();
    }
  }
  _models.clear();
}
Referenced by initialize(), and ~BulkPipelineManager().
The documentation for this class was generated from the following files:
runtime/onert/backend/trix/ops/BulkPipelineManager.h
runtime/onert/backend/trix/ops/BulkPipelineManager.cc