ONE - On-device Neural Engine: locoex::COpCall Class Reference
locoex::COpCall Class Reference final
Class to calls custom operation.
#include <COpCall.h>
Public Member Functions
COpCall (unsigned arity)
void op (const std::string &op)
const std::string & op ()
void name (const std::string &name)
const std::string & name ()
void input (uint32_t nth, loco::Node *node)
loco::Node * input (uint32_t nth) const
void attr (const std::string &attr_name, std::unique_ptr< COpAttrData > &&attr_data)
Store [attr_name, attr_data].
template<COpAttrType AT>
const AttrTypeTrait< AT >::Type * attr (const std::string &attr_name) const
Retrieve attr_data stored with attr_name.
std::vector< std::string > attr_names () const
get all the names of attr
Public Member Functions inherited from locoex::VariadicArityNode< COpNode >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::COpNode
virtual ~COpNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
uint32_t opnum (void) const final
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from locoex::VariadicArityNode< COpNode >
loco::Use * at (uint32_t n) const
Detailed Description
Class to calls custom operation.
Definition at line 35 of file COpCall.h.
Constructor & Destructor Documentation
COpCall()
locoex::COpCall::COpCall (unsigned arity) inline
Definition at line 40 of file COpCall.h.
: VariadicArityNode<COpNode>(arity) {}
Member Function Documentation
attr() [1/2]
template<COpAttrType AT> const AttrTypeTrait< AT >::Type * locoex::COpCall::attr (const std::string & attr_name) const
Retrieve attr_data stored with attr_name.
Definition at line 25 of file COpCall.cpp.
{
  COpAttrData *attr_data;
  auto found = _attrs.find(attr_name);
  if (found != _attrs.end())
  {
    attr_data = found->second.get();
    return dynamic_cast<const typename AttrTypeTrait<AT>::Type *>(attr_data);
  }
  else
    throw std::runtime_error("Cannot find requested attr");
}
attr() [2/2]
void locoex::COpCall::attr (const std::string & attr_name, std::unique_ptr< COpAttrData > && attr_data)
Store [attr_name, attr_data].
Definition at line 38 of file COpCall.cpp.
{
  if (_attrs.find(attr_name) == _attrs.end())
    _attrs[attr_name] = std::move(attr_data);
  else
    throw std::runtime_error("Attr already inserted");
}
attr_names()
std::vector< std::string > locoex::COpCall::attr_names () const
get all the names of attr
Definition at line 46 of file COpCall.cpp.
{
  std::vector<std::string> attr_names;
  for (auto it = _attrs.cbegin(); it != _attrs.cend(); ++it)
  {
    attr_names.emplace_back(it->first);
  }
  return attr_names;
}
References attr_names().
Referenced by attr_names().
input() [1/2]
loco::Node * locoex::COpCall::input (uint32_t nth) const inline
Definition at line 50 of file COpCall.h.
{ return at(nth)->node(); }
References locoex::VariadicArityNode< COpNode >::at(), and loco::Use::node().
input() [2/2]
void locoex::COpCall::input (uint32_t nth, loco::Node * node) inline
Definition at line 49 of file COpCall.h.
{ at(nth)->node(node); }
References locoex::VariadicArityNode< COpNode >::at(), and loco::Use::node().
name() [1/2]
const std::string & locoex::COpCall::name () inline
Definition at line 47 of file COpCall.h.
{ return _name; }
Referenced by name().
name() [2/2]
void locoex::COpCall::name (const std::string & name) inline
Definition at line 46 of file COpCall.h.
{ _name.assign(name); }
References name().
op() [1/2]
const std::string & locoex::COpCall::op () inline
Definition at line 44 of file COpCall.h.
{ return _op; }
Referenced by op().
op() [2/2]
void locoex::COpCall::op (const std::string & op) inline
Definition at line 43 of file COpCall.h.
{ _op.assign(op); }
References op().
Referenced by moco::tf::COpCallGraphBuilder::build().
The documentation for this class was generated from the following files:
compiler/locoex-customop/include/locoex/COpCall.h
compiler/locoex-customop/src/COpCall.cpp