ONE - On-device Neural Engine: nnkit::support::tf::TensorDataMap Class Reference
nnkit::support::tf::TensorDataMap Class Reference
Class to map parsed tensor and memory for tensor values. For parsed tensor, this memory is used to fill input or output values of graph.
#include <TensorDataMap.h>
Public Member Functions
TensorDataMap ()
uint8_t * allocate (const ParsedTensor *parsed_tensor)
uint8_t * data (const ParsedTensor *parsed_tensor)
Detailed Description
Class to map parsed tensor and memory for tensor values. For parsed tensor, this memory is used to fill input or output values of graph.
Definition at line 41 of file TensorDataMap.h.
Constructor & Destructor Documentation
TensorDataMap()
nnkit::support::tf::TensorDataMap::TensorDataMap () inline
Definition at line 44 of file TensorDataMap.h.
  { /* empty */
  }
Member Function Documentation
allocate()
uint8_t * nnkit::support::tf::TensorDataMap::allocate (const ParsedTensor * parsed_tensor) inline
Definition at line 48 of file TensorDataMap.h.
  {
    auto it = _data_map.find(parsed_tensor);
    if (it != _data_map.end())
      throw std::runtime_error("Already allocated");
    int bytes = 0;
    if (parsed_tensor->isFloatTensor())
      bytes = sizeof(float);
    else
      throw std::runtime_error("Unsupported or wrong data type");
    uint64_t size = num_elements(parsed_tensor->shape()) * bytes;
    _data_map[parsed_tensor] = std::move(std::unique_ptr<uint8_t[]>(new uint8_t[size]));
    return _data_map[parsed_tensor].get();
  }
References nnkit::support::tftestinfo::ParsedTensor::isFloatTensor(), and nnkit::support::tftestinfo::ParsedTensor::shape().
Referenced by nnkit::support::tf::Backend::prepare(), and nnkit::support::tf::Backend::run().
data()
uint8_t * nnkit::support::tf::TensorDataMap::data (const ParsedTensor * parsed_tensor) inline
Definition at line 66 of file TensorDataMap.h.
  {
    auto it = _data_map.find(parsed_tensor);
    if (it == _data_map.end())
      throw std::runtime_error("Cannot find parsed tensor");
    return it->second.get();
  }
Referenced by nnkit::support::tf::TensorContext::getConstFloatTensor(), nnkit::support::tf::TensorContext::getMutableFloatTensor(), and nnkit::support::tf::Runner::prepareInputs().
The documentation for this class was generated from the following file:
compiler/nnkit-tf/support/include/nnkit/support/tf/TensorDataMap.h