ONE - On-device Neural Engine: exo::InputHandler< CanonicalT, TFLT > Class Template Reference
exo::InputHandler< CanonicalT, TFLT > Class Template Reference abstract
Handles input(s) while converting a canonical node to TFL node(s). This class informs DomainConverter how to handle inputs of a specific canonical node.
#include <GraphBlock.h>
Public Member Functions
virtual void handover (CanonicalT *origin, TFLT *replacer)=0
Assign origin's inputs to replacer's inputs. (This is called when origin belongs in Tensor domain.)
virtual std::vector< loco::Node * > getInputsToConvert (CanonicalT *origin)=0
Returns the list of inputs that needs to have FeatureDecode as its input. (This is called when origin belongs in Feature domain.)
virtual void set (TFLT *replacer, std::vector< loco::Node * > &new_inputs)=0
Set the inputs of replacer to new_inputs.
virtual void nullify (CanonicalT *origin)=0
Set the inputs to nullptr.
Detailed Description
template<class CanonicalT, class TFLT>
class exo::InputHandler< CanonicalT, TFLT >
Handles input(s) while converting a canonical node to TFL node(s). This class informs DomainConverter how to handle inputs of a specific canonical node.
Definition at line 109 of file GraphBlock.h.
Member Function Documentation
getInputsToConvert()
template<class CanonicalT , class TFLT > virtual std::vector< loco::Node * > exo::InputHandler< CanonicalT, TFLT >::getInputsToConvert (CanonicalT * origin) pure virtual
Returns the list of inputs that needs to have FeatureDecode as its input. (This is called when origin belongs in Feature domain.)
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert().
handover()
template<class CanonicalT , class TFLT > virtual void exo::InputHandler< CanonicalT, TFLT >::handover (CanonicalT * origin, TFLT * replacer) pure virtual
Assign origin's inputs to replacer's inputs. (This is called when origin belongs in Tensor domain.)
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert().
nullify()
template<class CanonicalT , class TFLT > virtual void exo::InputHandler< CanonicalT, TFLT >::nullify (CanonicalT * origin) pure virtual
Set the inputs to nullptr.
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert().
set()
template<class CanonicalT , class TFLT > virtual void exo::InputHandler< CanonicalT, TFLT >::set (TFLT * replacer, std::vector< loco::Node * > & new_inputs) pure virtual
Set the inputs of replacer to new_inputs.
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert().
The documentation for this class was generated from the following file:
compiler/exo/src/GraphBlock.h