ONE - On-device Neural Engine: loco::PermutingDecoder< Domain::DepthwiseFilter > Class Reference
loco::PermutingDecoder< Domain::DepthwiseFilter > Class Reference final
Permutation-based DepthwiseFilter-to-Tensor converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingDecoder ()=default
PermutingDecoder (const Permutation< Domain::DepthwiseFilter > &perm)
bool valid (void) const
TensorShape shape (const DepthwiseFilterShape &shape) const override
DepthwiseFilterIndex value (const TensorIndex &index) const override
const Permutation< Domain::DepthwiseFilter > * perm (void) const
Permutation< Domain::DepthwiseFilter > * perm (void)
void perm (const Permutation< Domain::DepthwiseFilter > &p)
Public Member Functions inherited from loco::DepthwiseFilterDecoder
virtual ~DepthwiseFilterDecoder ()=default
virtual TensorShape shape (const DepthwiseFilterShape &shape) const =0
virtual DepthwiseFilterIndex value (const TensorIndex &index) const =0
Detailed Description
Permutation-based DepthwiseFilter-to-Tensor converter.
Definition at line 297 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingDecoder() [1/2]
loco::PermutingDecoder< Domain::DepthwiseFilter >::PermutingDecoder () default
PermutingDecoder() [2/2]
loco::PermutingDecoder< Domain::DepthwiseFilter >::PermutingDecoder (const Permutation< Domain::DepthwiseFilter > & perm) inline
Definition at line 303 of file PermutingCodec.h.
                                                                   : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingDecoder< Domain::DepthwiseFilter >::perm (const Permutation< Domain::DepthwiseFilter > & p) inline
Definition at line 318 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::DepthwiseFilter > * loco::PermutingDecoder< Domain::DepthwiseFilter >::perm (void) inline
Definition at line 317 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::DepthwiseFilter > * loco::PermutingDecoder< Domain::DepthwiseFilter >::perm (void) const inline
Definition at line 316 of file PermutingCodec.h.
{ return &_perm; }
shape()
TensorShape loco::PermutingDecoder< Domain::DepthwiseFilter >::shape (const DepthwiseFilterShape & shape) const override virtual
Implements loco::DepthwiseFilterDecoder.
Definition at line 461 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorShape out;
  out.rank(4);
  out.dim(_perm[DepthwiseFilterAxis::Depth]) = in.depth();
  out.dim(_perm[DepthwiseFilterAxis::Multiplier]) = in.multiplier();
  out.dim(_perm[DepthwiseFilterAxis::Height]) = in.height();
  out.dim(_perm[DepthwiseFilterAxis::Width]) = in.width();
  return out;
}
References loco::Depth, loco::DepthwiseFilterShape::depth(), loco::TensorShape::dim(), loco::Height, loco::DepthwiseFilterShape::height(), loco::Multiplier, loco::DepthwiseFilterShape::multiplier(), loco::TensorShape::rank(), loco::valid(), loco::Width, and loco::DepthwiseFilterShape::width().
valid()
bool loco::PermutingDecoder< Domain::DepthwiseFilter >::valid (void) const
Definition at line 491 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
DepthwiseFilterIndex loco::PermutingDecoder< Domain::DepthwiseFilter >::value (const TensorIndex & index) const override virtual
Implements loco::DepthwiseFilterDecoder.
Definition at line 476 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  assert(in.rank() == 4);
  DepthwiseFilterIndex out;
  out.channel() = in.at(_perm[DepthwiseFilterAxis::Depth]);
  out.nth() = in.at(_perm[DepthwiseFilterAxis::Multiplier]);
  out.row() = in.at(_perm[DepthwiseFilterAxis::Height]);
  out.column() = in.at(_perm[DepthwiseFilterAxis::Width]);
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::DepthwiseFilterIndex::channel(), loco::DepthwiseFilterIndex::column(), loco::Depth, loco::Height, loco::Multiplier, loco::DepthwiseFilterIndex::nth(), nncc::core::ADT::tensor::Index::rank(), loco::DepthwiseFilterIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp