ONE - On-device Neural Engine: luci::ForceQuantParamPass Class Reference
luci::ForceQuantParamPass Class Reference
Pass to write quantparam (scale, zerop) to the specified tensors.
#include <ForceQuantParamPass.h>
Public Types
using TensorVector = std::vector< std::string >
using ScaleVector = std::vector< float >
using ZPVector = std::vector< int64_t >
Public Member Functions
ForceQuantParamPass (TensorVector &tensors, ScaleVector &scales, ZPVector &zerops)
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to write quantparam (scale, zerop) to the specified tensors.
Definition at line 30 of file ForceQuantParamPass.h.
Member Typedef Documentation
ScaleVector
using luci::ForceQuantParamPass::ScaleVector = std::vector<float>
Definition at line 34 of file ForceQuantParamPass.h.
TensorVector
using luci::ForceQuantParamPass::TensorVector = std::vector<std::string>
Definition at line 33 of file ForceQuantParamPass.h.
ZPVector
using luci::ForceQuantParamPass::ZPVector = std::vector<int64_t>
Definition at line 35 of file ForceQuantParamPass.h.
Constructor & Destructor Documentation
ForceQuantParamPass()
luci::ForceQuantParamPass::ForceQuantParamPass (TensorVector & tensors, ScaleVector & scales, ZPVector & zerops) inline
Definition at line 38 of file ForceQuantParamPass.h.
    : _tensors{tensors}, _scales{scales}, _zerops{zerops}
  {
    // DO NOTHING
  }
Member Function Documentation
name()
virtual const char * luci::ForceQuantParamPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 43 of file ForceQuantParamPass.h.
{ return "luci::ForceQuantParamPass"; }
Referenced by run().
run()
bool luci::ForceQuantParamPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 41 of file ForceQuantParamPass.cpp.
{
  LOGGER(l);
  INFO(l) << "ForceQuantParamPass Start" << std::endl;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto const cnode = loco::must_cast<CircleNode *>(node);
    auto const name = cnode->name();
    auto target = std::find(_tensors.begin(), _tensors.end(), name);
    if (target == _tensors.end())
      continue;
    auto index = target - _tensors.begin();
    auto scale = _scales[index];
    auto zp = _zerops[index];
    set_qparam(cnode, scale, zp);
    _tensors.erase(_tensors.begin() + index);
    _scales.erase(_scales.begin() + index);
    _zerops.erase(_zerops.begin() + index);
  }
  if (_tensors.size() > 0)
  {
    std::string msg;
    for (auto const &t : _tensors)
      msg += "Tensor does not exist: " + t + ".\n";
    msg += "Please check tensor name.\n";
    throw std::runtime_error(msg);
  }
  INFO(l) << "ForceQuantParamPass End" << std::endl;
  return false; // one time run
}
References loco::active_nodes(), INFO, LOGGER, name(), and loco::output_nodes().
Referenced by luci::CircleQuantizer::quantize().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/ForceQuantParamPass.h
compiler/luci/pass/src/ForceQuantParamPass.cpp