ONE - On-device Neural Engine: nnfw::cker::BCast Class Reference
nnfw::cker::BCast Class Reference
#include <BCast.h>
Public Types
typedef std::vector< int32_t > Vec
Public Types inherited from nnfw::cker::BCastList< 2 >
typedef std::vector< int32_t > Vec
Public Member Functions
BCast (const Vec &x, const Vec &y, const bool fewer_dims_optimization=true, const bool return_flattened_batch_indices=false)
~BCast ()
const Vec & x_reshape () const
const Vec & x_bcast () const
const Vec & y_reshape () const
const Vec & y_bcast () const
const Vec & result_shape () const
const Vec & output_shape () const
const Vec & grad_x_reduce_idx () const
const Vec & grad_y_reduce_idx () const
const std::vector< int32_t > & x_batch_indices () const
const std::vector< int32_t > & y_batch_indices () const
Public Member Functions inherited from nnfw::cker::BCastList< 2 >
BCastList (const Vec(&x)[N], const bool fewer_dims_optimization=true, const bool return_flattened_batch_indices=false)
~BCastList ()
bool IsValid () const
bool IsBroadcastingRequired () const
const Vec & reshape (int i) const
const Vec & bcast (int i) const
const Vec & result_shape () const
const Vec & output_shape () const
const Vec & grad_reduce_idx (int i) const
int32_t output_batch_size () const
const std::vector< int32_t > & batch_indices (int i) const
Static Public Member Functions
template<typename IndexType , int NDIMS>
static Eigen::array< IndexType, NDIMS > ToIndexArrayType (const BCast::Vec &vec)
template<int NDIMS>
static Eigen::array< Eigen::DenseIndex, NDIMS > ToIndexArray (const BCast::Vec &vec)
static Vec FromShape (const Shape &shape)
static Shape ToShape (const BCastList::Vec &vec)
Additional Inherited Members
Static Protected Member Functions inherited from nnfw::cker::BCastList< 2 >
static void Reverse (Vec *shape)
Protected Attributes inherited from nnfw::cker::BCastList< 2 >
bool valid_
bool broadcasting_required_
Vec reshape_ [N]
Vec bcast_ [N]
Vec result_
Vec output_
Vec grad_reduce_idx_ [N]
int32_t output_batch_size_
std::vector< int32_t > batch_indices_ [N]
Detailed Description
Definition at line 381 of file BCast.h.
Member Typedef Documentation
Vec
typedef std::vector<int32_t> nnfw::cker::BCast::Vec
Definition at line 392 of file BCast.h.
Constructor & Destructor Documentation
BCast()
nnfw::cker::BCast::BCast (const Vec & x, const Vec & y, const bool fewer_dims_optimization = true, const bool return_flattened_batch_indices = false) inline
Definition at line 394 of file BCast.h.
    : BCastList<2>({x, y}, fewer_dims_optimization, return_flattened_batch_indices)
  {
  }
~BCast()
nnfw::cker::BCast::~BCast () inline
Definition at line 400 of file BCast.h.
{}
Member Function Documentation
FromShape()
static Vec nnfw::cker::BCast::FromShape (const Shape & shape) inline static
Definition at line 444 of file BCast.h.
  {
    const int N = shape.DimensionsCount();
    BCastList::Vec ret(N);
    for (int i = 0; i < N; ++i)
    {
      ret[i] = shape.Dims(i);
    }
    return ret;
  }
References nnfw::cker::Shape::DimensionsCount(), and nnfw::cker::Shape::Dims().
Referenced by nnfw::cker::BroadcastTo().
grad_x_reduce_idx()
const Vec & nnfw::cker::BCast::grad_x_reduce_idx () const inline
Definition at line 411 of file BCast.h.
{ return grad_reduce_idx_[0]; }
References nnfw::cker::BCastList< 2 >::grad_reduce_idx_.
grad_y_reduce_idx()
const Vec & nnfw::cker::BCast::grad_y_reduce_idx () const inline
Definition at line 412 of file BCast.h.
{ return grad_reduce_idx_[1]; }
References nnfw::cker::BCastList< 2 >::grad_reduce_idx_.
output_shape()
const Vec & nnfw::cker::BCast::output_shape () const inline
Definition at line 410 of file BCast.h.
{ return output_; }
References nnfw::cker::BCastList< 2 >::output_.
Referenced by nnfw::cker::BroadcastTo().
result_shape()
const Vec & nnfw::cker::BCast::result_shape () const inline
Definition at line 409 of file BCast.h.
{ return result_; }
References nnfw::cker::BCastList< 2 >::result_.
Referenced by nnfw::cker::functor::BroadcastTo< Device, T >::ReshapeAndBCast().
ToIndexArray()
template<int NDIMS> static Eigen::array< Eigen::DenseIndex, NDIMS > nnfw::cker::BCast::ToIndexArray (const BCast::Vec & vec) inline static
Definition at line 438 of file BCast.h.
  {
    return ToIndexArrayType<Eigen::DenseIndex, NDIMS>(vec);
  }
ToIndexArrayType()
template<typename IndexType , int NDIMS> static Eigen::array< IndexType, NDIMS > nnfw::cker::BCast::ToIndexArrayType (const BCast::Vec & vec) inline static
Definition at line 428 of file BCast.h.
  {
    assert(vec.size() == NDIMS);
    Eigen::array<IndexType, NDIMS> ret;
    for (int i = 0; i < NDIMS; ++i)
      ret[i] = vec[i];
    return ret;
  }
ToShape()
static Shape nnfw::cker::BCast::ToShape (const BCastList::Vec & vec) inline static
Definition at line 455 of file BCast.h.
  {
    const int N = vec.size();
    Shape shape(N);
    for (int i = 0; i < N; ++i)
    {
      shape.SetDim(i, vec[i]);
    }
    return shape;
  }
References nnfw::cker::Shape::SetDim().
Referenced by nnfw::cker::BroadcastTo().
x_batch_indices()
const std::vector< int32_t > & nnfw::cker::BCast::x_batch_indices () const inline
Definition at line 420 of file BCast.h.
{ return batch_indices_[0]; }
References nnfw::cker::BCastList< 2 >::batch_indices_.
x_bcast()
const Vec & nnfw::cker::BCast::x_bcast () const inline
Definition at line 406 of file BCast.h.
{ return bcast_[0]; }
References nnfw::cker::BCastList< 2 >::bcast_.
Referenced by nnfw::cker::functor::BroadcastTo< Device, T >::ReshapeAndBCast().
x_reshape()
const Vec & nnfw::cker::BCast::x_reshape () const inline
Definition at line 405 of file BCast.h.
{ return reshape_[0]; }
References nnfw::cker::BCastList< 2 >::reshape_.
Referenced by nnfw::cker::functor::BroadcastTo< Device, T >::ReshapeAndBCast().
y_batch_indices()
const std::vector< int32_t > & nnfw::cker::BCast::y_batch_indices () const inline
Definition at line 425 of file BCast.h.
{ return batch_indices_[1]; }
References nnfw::cker::BCastList< 2 >::batch_indices_.
y_bcast()
const Vec & nnfw::cker::BCast::y_bcast () const inline
Definition at line 408 of file BCast.h.
{ return bcast_[1]; }
References nnfw::cker::BCastList< 2 >::bcast_.
y_reshape()
const Vec & nnfw::cker::BCast::y_reshape () const inline
Definition at line 407 of file BCast.h.
{ return reshape_[1]; }
References nnfw::cker::BCastList< 2 >::reshape_.
Referenced by nnfw::cker::functor::BroadcastTo< Device, T >::operator()().
The documentation for this class was generated from the following file:
compute/cker/include/cker/operation/Helper/BCast.h