ONE - On-device Neural Engine: arm_compute::CLEmbeddingLookupKernel Class Reference
arm_compute::CLEmbeddingLookupKernel Class Reference
Class to perform EmbeddingLookup operation with opencl kernel.
#include <CLEmbeddingLookupKernel.h>
Public Member Functions
CLEmbeddingLookupKernel ()
Construct a CLEmbeddingLookupKernel object.
CLEmbeddingLookupKernel (const CLEmbeddingLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLEmbeddingLookupKernel & operator= (const CLEmbeddingLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLEmbeddingLookupKernel (CLEmbeddingLookupKernel &&)=default
Construct a CLEmbeddingLookupKernel object by using default move constructor.
CLEmbeddingLookupKernel & operator= (CLEmbeddingLookupKernel &&)=default
Move assignment operator.
~CLEmbeddingLookupKernel ()=default
Destruct this object.
void configure (const ICLTensor *input, ICLTensor *output, const ICLTensor *lookups)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *lookups)
Static function to check if given info will lead to a valid configuration of CLEmbeddingLookupKernel.
Detailed Description
Class to perform EmbeddingLookup operation with opencl kernel.
Definition at line 59 of file CLEmbeddingLookupKernel.h.
Constructor & Destructor Documentation
CLEmbeddingLookupKernel() [1/3]
CLEmbeddingLookupKernel::CLEmbeddingLookupKernel ()
Construct a CLEmbeddingLookupKernel object.
Definition at line 73 of file CLEmbeddingLookupKernel.cpp.
  : _input(nullptr), _output(nullptr), _lookups(nullptr)
{
}
CLEmbeddingLookupKernel() [2/3]
arm_compute::CLEmbeddingLookupKernel::CLEmbeddingLookupKernel (const CLEmbeddingLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLEmbeddingLookupKernel() [3/3]
arm_compute::CLEmbeddingLookupKernel::CLEmbeddingLookupKernel (CLEmbeddingLookupKernel &&) default
Construct a CLEmbeddingLookupKernel object by using default move constructor.
Parameters
[in] CLEmbeddingLookupKernel object to move
~CLEmbeddingLookupKernel()
arm_compute::CLEmbeddingLookupKernel::~CLEmbeddingLookupKernel () default
Destruct this object.
References validate().
Member Function Documentation
configure()
void CLEmbeddingLookupKernel::configure (const ICLTensor * input, ICLTensor * output, const ICLTensor * lookups)
Set the input and output of the kernel.
Parameters
[in] input Source tensor. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[out] output Destination tensor. Data type supported: Same as input
[in] lookups Lookups are 1D tensor that values are indices into the first dimension of input. Data types supported: S32.
Returns
N/A
Definition at line 94 of file CLEmbeddingLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_THROW_ON(validate(input->info(), output->info(), lookups->info()));
  _input = input;
  _output = output;
  _lookups = lookups;
  // Set kernel build options
  std::stringstream kernel_name;
  std::set<std::string> build_opts;
  kernel_name << "embedding_lookup";
  build_opts.emplace("-DDEPTH_OUT=" + support::cpp11::to_string(output->info()->dimension(2)));
  build_opts.emplace("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.emplace("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
  build_opts.emplace("-DNUM_DIMS=" + support::cpp11::to_string(_input->info()->num_dimensions()));
  // Create kernel
  _kernel =
    static_cast<cl::Kernel>(CLKernelLibraryEx::get().create_kernel(kernel_name.str(), build_opts));
  // Configure kernel window
  auto win_config = validate_and_configure_window(input->info(), output->info());
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  ICLKernel::configure_internal(win_config.second);
}
References arm_compute::CLKernelLibraryEx::create_kernel(), arm_compute::CLKernelLibraryEx::get(), and validate().
operator=() [1/2]
CLEmbeddingLookupKernel & arm_compute::CLEmbeddingLookupKernel::operator= (CLEmbeddingLookupKernel &&) default
Move assignment operator.
Parameters
[in] CLEmbeddingLookupKernel object to move
operator=() [2/2]
CLEmbeddingLookupKernel & arm_compute::CLEmbeddingLookupKernel::operator= (const CLEmbeddingLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void CLEmbeddingLookupKernel::run (const Window & window, cl::CommandQueue & queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Returns
N/A
N/A
Definition at line 123 of file CLEmbeddingLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  Window slice_in = window.first_slice_window_4D().collapse(ICLKernel::window(), 2, 4);
  Window win_lookup;
  win_lookup.set(Window::DimX, Window::Dimension(0, 0, 0));
  do
  {
    unsigned int idx = 0;
    add_4D_tensor_argument(idx, _input, slice_in);
    add_4D_tensor_argument(idx, _output, slice_in);
    add_1D_tensor_argument(idx, _lookups, win_lookup);
    enqueue(queue, *this, slice_in);
  } while (window.slide_window_slice_4D(slice_in) && window.slide_window_slice_1D(win_lookup));
}
validate()
Status CLEmbeddingLookupKernel::validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * lookups) static
Static function to check if given info will lead to a valid configuration of CLEmbeddingLookupKernel.
Parameters
[in] input The input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] output The output tensor info, Data types supported: same as input1.
[in] lookups Lookups info. Data types supported: S32.
Returns
a status
Definition at line 78 of file CLEmbeddingLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, lookups);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(
    input, 1, DataType::U8, DataType::S8, DataType::QASYMM8, DataType::U16, DataType::S16,
    DataType::U32, DataType::S32, DataType::F16, DataType::F32);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lookups, 1, DataType::S32);
  ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
  ARM_COMPUTE_ERROR_ON(input->num_dimensions() < 2 && input->num_dimensions() > 4);
  ARM_COMPUTE_ERROR_ON(lookups->num_dimensions() > 1);
  return Status{};
}
Referenced by configure(), and ~CLEmbeddingLookupKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLEmbeddingLookupKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLEmbeddingLookupKernel.cpp