ONE - On-device Neural Engine: luci::CircleConst Class Reference
luci::CircleConst Class Reference final
Class to build tensor data.
#include <CircleConst.h>
Public Member Functions
template<loco::DataType DT>
uint32_t size (void) const
template<loco::DataType DT>
void size (uint32_t size)
template<loco::DataType DT>
const loco::DataTypeImpl< DT >::Type & at (uint32_t n) const
template<loco::DataType DT>
loco::DataTypeImpl< DT >::Type & at (uint32_t n)
template<loco::DataType DT>
const loco::DataTypeImpl< DT >::Type & scalar (void) const
template<loco::DataType DT>
loco::DataTypeImpl< DT >::Type & scalar (void)
Public Member Functions inherited from luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLECONST > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::CIRCLECONST >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 0, CircleNodeImpl< CircleOpcode::CIRCLECONST > >
loco::Use * at (uint32_t n) const
Detailed Description
Class to build tensor data.
Note
This will not be exported as a specific op
Definition at line 34 of file CircleConst.h.
Member Function Documentation
at() [1/2]
template<loco::DataType DT> loco::DataTypeImpl< DT >::Type & luci::CircleConst::at (uint32_t n)
Definition at line 45 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  assert(n < size<DT>());
  return *(reinterpret_cast<typename loco::DataTypeImpl<DT>::Type *>(_data.data()) + n);
}
at() [2/2]
template<loco::DataType DT> const loco::DataTypeImpl< DT >::Type & luci::CircleConst::at (uint32_t n) const
Definition at line 38 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  assert(n < size<DT>());
  return *(reinterpret_cast<const typename loco::DataTypeImpl<DT>::Type *>(_data.data()) + n);
}
Referenced by luci::asymmetric_wquant_with_minmax_per_layer(), luci::quant_const(), luci::FuseBCQPass::run(), luci::SparsifyTensorPass::sparsify_tensor(), luci::swap_mul_add(), and luci::symmetric_wquant_with_minmax_per_layer().
scalar() [1/2]
template<loco::DataType DT> loco::DataTypeImpl< DT >::Type & luci::CircleConst::scalar (void)
Definition at line 59 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  return *(reinterpret_cast<typename loco::DataTypeImpl<DT>::Type *>(_data.data()));
}
scalar() [2/2]
template<loco::DataType DT> const loco::DataTypeImpl< DT >::Type & luci::CircleConst::scalar (void) const
Definition at line 53 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  return *(reinterpret_cast<const typename loco::DataTypeImpl<DT>::Type *>(_data.data()));
}
size() [1/2]
template<loco::DataType DT> void luci::CircleConst::size (uint32_t size)
Definition at line 31 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  _data.resize(l * sizeof(typename loco::DataTypeImpl<DT>::Type));
}
size() [2/2]
template<loco::DataType DT> uint32_t luci::CircleConst::size (void) const
Definition at line 24 of file CircleConst.cpp.
{
  assert(dtype() == DT);
  assert(_data.size() % sizeof(typename loco::DataTypeImpl<DT>::Type) == 0);
  return _data.size() / sizeof(typename loco::DataTypeImpl<DT>::Type);
}
Referenced by luci::asymmetric_wquant_with_minmax_per_layer(), is_1D_float32_const(), luci::quant_const(), luci::FuseBCQPass::run(), luci::SparsifyTensorPass::sparsify_tensor(), luci::swap_mul_add(), and luci::symmetric_wquant_with_minmax_per_layer().
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/Nodes/CircleConst.h
compiler/luci/lang/src/Nodes/CircleConst.cpp