ONE - On-device Neural Engine: luci::CircleExporter Class Reference
luci::CircleExporter Class Reference
#include <CircleExporter.h>
Data Structures
struct Contract
Public Member Functions
CircleExporter ()
bool invoke (Contract *) const
Detailed Description
Definition at line 29 of file CircleExporter.h.
Constructor & Destructor Documentation
CircleExporter()
luci::CircleExporter::CircleExporter () explicit
Definition at line 32 of file CircleExporter.cpp.
{
  // NOTHING TO DO
}
Member Function Documentation
invoke()
bool luci::CircleExporter::invoke (Contract * contract) const
Definition at line 37 of file CircleExporter.cpp.
{
  auto module = contract->module();
  if (module != nullptr)
  {
    CircleExporterImpl impl(module);
    const char *ptr = impl.getBufferPointer();
    const size_t size = impl.getBufferSize();
    // we just send one time
    return contract->store(ptr, size);
  }
  auto graph = contract->graph();
  if (graph == nullptr)
    return false;
  CircleExporterImpl impl(graph);
  const char *ptr = impl.getBufferPointer();
  const size_t size = impl.getBufferSize();
  // we just send one time
  return contract->store(ptr, size);
}
References luci::CircleExporterImpl::getBufferPointer(), luci::CircleExporterImpl::getBufferSize(), luci::CircleExporter::Contract::graph(), luci::CircleExporter::Contract::module(), and luci::CircleExporter::Contract::store().
Referenced by entry(), opselector::exportModule(), and record_minmax::RecordMinMax::saveModel().
The documentation for this class was generated from the following files:
compiler/luci/export/include/luci/CircleExporter.h
compiler/luci/export/src/CircleExporter.cpp