ONE - On-device Neural Engine: npud::core::Core Class Reference
npud::core::Core Class Reference
#include <Core.h>
Public Member Functions
Core () noexcept
~Core () noexcept=default
Core (const Core &)=delete
Core & operator= (const Core &)=delete
void init ()
void deinit ()
int getAvailableDeviceList (std::vector< std::string > &list) const
int createContext (int deviceId, int priority, ContextID *contextId) const
int destroyContext (ContextID contextId) const
int createNetwork (ContextID contextId, const std::string &modelPath, ModelID *modelId) const
int destroyNetwork (ContextID contextId, ModelID modelId) const
int createRequest (ContextID contextId, ModelID modelId, RequestID *requestId) const
int destroyRequest (ContextID contextId, RequestID requestId) const
Detailed Description
Definition at line 33 of file Core.h.
Constructor & Destructor Documentation
Core() [1/2]
npud::core::Core::Core () noexcept
Definition at line 25 of file Core.cc.
  : _devManager(std::make_unique<DevManager>()), _contextManager(std::make_unique<ContextManager>())
{
}
~Core()
npud::core::Core::~Core () default noexcept
Core() [2/2]
npud::core::Core::Core (const Core &) delete
Member Function Documentation
createContext()
int npud::core::Core::createContext (int deviceId, int priority, ContextID * contextId) const
Definition at line 36 of file Core.cc.
{
  VERBOSE(Core) << "createContext with " << deviceId << ", " << priority << std::endl;
  NpuContext *npuContext;
  int ret = _devManager->createContext(deviceId, priority, &npuContext);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Fail to create dev context" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  ContextID _contextId;
  _contextManager->newContext(npuContext, &_contextId);
  *contextId = _contextId;
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_context_create().
createNetwork()
int npud::core::Core::createNetwork (ContextID contextId, const std::string & modelPath, ModelID * modelId) const
Definition at line 76 of file Core.cc.
{
  VERBOSE(Core) << "createNetwork with " << contextId << ", " << modelPath << std::endl;
  NpuContext *npuContext = _contextManager->getNpuContext(contextId);
  if (!npuContext)
  {
    VERBOSE(Core) << "Invalid context id" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  ModelID id;
  int ret = _devManager->registerModel(npuContext, modelPath, &id);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Failed to register model: " << ret << std::endl;
    return 1;
  }
  *modelId = id;
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_network_create().
createRequest()
int npud::core::Core::createRequest (ContextID contextId, ModelID modelId, RequestID * requestId) const
Definition at line 121 of file Core.cc.
{
  VERBOSE(Core) << "createRequest with " << contextId << ", " << modelId << std::endl;
  NpuContext *npuContext = _contextManager->getNpuContext(contextId);
  if (!npuContext)
  {
    VERBOSE(Core) << "Invalid context id" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  RequestID id;
  int ret = _devManager->createRequest(npuContext, modelId, &id);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Failed to create request of model: " << ret << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  *requestId = id;
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_request_create().
deinit()
void npud::core::Core::deinit ()
Definition at line 32 of file Core.cc.
{ _devManager->releaseModules(); }
destroyContext()
int npud::core::Core::destroyContext (ContextID contextId) const
Definition at line 54 of file Core.cc.
{
  VERBOSE(Core) << "destroyContext with " << contextId << std::endl;
  NpuContext *npuContext = _contextManager->getNpuContext(contextId);
  if (!npuContext)
  {
    VERBOSE(Core) << "Invalid context id" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  int ret = _devManager->destroyContext(npuContext);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Failed to destroy npu context: " << ret << std::endl;
    return 1;
  }
  _contextManager->deleteContext(contextId);
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_context_destroy().
destroyNetwork()
int npud::core::Core::destroyNetwork (ContextID contextId, ModelID modelId) const
Definition at line 99 of file Core.cc.
{
  VERBOSE(Core) << "destroyNetwork with " << contextId << std::endl;
  NpuContext *npuContext = _contextManager->getNpuContext(contextId);
  if (!npuContext)
  {
    VERBOSE(Core) << "Invalid context id" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  int ret = _devManager->unregisterModel(npuContext, modelId);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Failed to unregister model: " << ret << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_network_destroy().
destroyRequest()
int npud::core::Core::destroyRequest (ContextID contextId, RequestID requestId) const
Definition at line 145 of file Core.cc.
{
  VERBOSE(Core) << "destroyRequest with " << contextId << ", " << requestId << std::endl;
  NpuContext *npuContext = _contextManager->getNpuContext(contextId);
  if (!npuContext)
  {
    VERBOSE(Core) << "Invalid context id" << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  int ret = _devManager->destroyRequest(npuContext, requestId);
  if (ret != NPU_STATUS_SUCCESS)
  {
    VERBOSE(Core) << "Failed to destroy request: " << ret << std::endl;
    // TODO Define CoreStatus
    return 1;
  }
  return 0;
}
References npud::core::NPU_STATUS_SUCCESS, and VERBOSE.
Referenced by npud::core::DBus::on_handle_request_destroy().
getAvailableDeviceList()
int npud::core::Core::getAvailableDeviceList (std::vector< std::string > & list) const
Definition at line 34 of file Core.cc.
{ return 0; }
Referenced by npud::core::DBus::on_handle_device_get_available_list().
init()
void npud::core::Core::init ()
Definition at line 30 of file Core.cc.
{ _devManager->loadModules(); }
operator=()
Core & npud::core::Core::operator= (const Core &) delete
The documentation for this class was generated from the following files:
runtime/service/npud/core/Core.h
runtime/service/npud/core/Core.cc