ONE - On-device Neural Engine: luci_interpreter::kernels::Slice Class Reference
luci_interpreter::kernels::Slice Class Reference
#include <Slice.h>
Public Member Functions
Slice (const Tensor *input, const Tensor *begin, const Tensor *size, Tensor *output)
const Tensor * input () const
const Tensor * begin () const
const Tensor * size () const
Tensor * output () const
void configure () override
void execute () const override
Slice (const Tensor *input, const Tensor *begin, const Tensor *size, Tensor *output)
const Tensor * input () const
const Tensor * begin () const
const Tensor * size () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file Slice.h.
Constructor & Destructor Documentation
Slice() [1/2]
luci_interpreter::kernels::Slice::Slice (const Tensor * input, const Tensor * begin, const Tensor * size, Tensor * output)
Definition at line 31 of file Slice.cpp.
  : Kernel({input, begin, size}, {output})
{
}
References begin(), input(), and size().
Slice() [2/2]
luci_interpreter::kernels::Slice::Slice (const Tensor * input, const Tensor * begin, const Tensor * size, Tensor * output)
Member Function Documentation
begin() [1/2]
const Tensor * luci_interpreter::kernels::Slice::begin () const inline
Definition at line 33 of file Slice.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Slice().
begin() [2/2]
const Tensor * luci_interpreter::kernels::Slice::begin () const inline
Definition at line 33 of file Slice.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::Slice::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 74 of file Slice.cpp.
{
  assert(input()->element_type() == output()->element_type());
  assert(begin()->element_type() == DataType::S32 || begin()->element_type() == DataType::S64);
  assert(size()->element_type() == DataType::S32 || size()->element_type() == DataType::S64);
  assert(begin()->shape().num_dims() == 1);
  assert(size()->shape().num_dims() == 1);
  assert(input()->shape().num_dims() <= max_dim);
  if (begin()->element_type() == DataType::S32)
  {
    output()->resize(calculateOutputShape<int32_t>(input(), begin(), size()));
  }
  else if (begin()->element_type() == DataType::S64)
  {
    output()->resize(calculateOutputShape<int64_t>(input(), begin(), size()));
  }
  else
  {
    throw std::runtime_error("Unsupported type.");
  }
}
References begin(), input(), luci_interpreter::kernels::max_dim, output(), luci_interpreter::Tensor::resize(), and size().
configure() [2/2]
void luci_interpreter::kernels::Slice::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Slice::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 97 of file Slice.cpp.
{
  std::vector<int> begins;
  begins.reserve(max_dim);
  std::vector<int> sizes;
  sizes.reserve(max_dim);
  if (begin()->element_type() == DataType::S32)
  {
    getBeginAndSizeVectors<int32_t>(input()->shape().num_dims(), begin(), size(), &begins, &sizes);
  }
  else if (begin()->element_type() == DataType::S64)
  {
    getBeginAndSizeVectors<int64_t>(input()->shape().num_dims(), begin(), size(), &begins, &sizes);
  }
  else
  {
    throw std::runtime_error("Unsupported begin type.");
  }
  for (int i = input()->shape().num_dims(); i < max_dim; ++i)
  {
    begins.push_back(0);
    sizes.push_back(1);
  }
  assert(begins.size() == 4);
  assert(sizes.size() == 4);
  tflite::SliceParams op_params{};
  op_params.begin_count = 4;
  op_params.size_count = 4;
  for (int i = 0; i < 4; i++)
  {
    op_params.begin[i] = begins[3 - i];
    op_params.size[i] = sizes[3 - i];
  }
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      luci_interpreter_pal::Slice(op_params, getTensorShape(input()), getTensorData<float>(input()),
                                  getTensorShape(output()), getTensorData<float>(output()));
      break;
    case DataType::U8:
      luci_interpreter_pal::Slice(op_params, getTensorShape(input()),
                                  getTensorData<uint8_t>(input()), getTensorShape(output()),
                                  getTensorData<uint8_t>(output()));
      break;
    case DataType::S8:
      luci_interpreter_pal::Slice(op_params, getTensorShape(input()),
                                  getTensorData<int8_t>(input()), getTensorShape(output()),
                                  getTensorData<int8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported input type.");
  }
}
References begin(), luci_interpreter::kernels::getTensorShape(), input(), luci_interpreter::kernels::max_dim, output(), and size().
execute() [2/2]
void luci_interpreter::kernels::Slice::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Slice::input () const inline
Definition at line 32 of file Slice.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Slice().
input() [2/2]
const Tensor * luci_interpreter::kernels::Slice::input () const inline
Definition at line 32 of file Slice.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Slice::output () const inline
Definition at line 35 of file Slice.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Slice::output () const inline
Definition at line 35 of file Slice.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
size() [1/2]
const Tensor * luci_interpreter::kernels::Slice::size () const inline
Definition at line 34 of file Slice.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Slice().
size() [2/2]
const Tensor * luci_interpreter::kernels::Slice::size () const inline
Definition at line 34 of file Slice.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Slice.h
onert-micro/luci-interpreter/src/kernels/Slice.h
compiler/luci-interpreter/src/kernels/Slice.cpp
onert-micro/luci-interpreter/src/kernels/Slice.cpp