ONE - On-device Neural Engine: onert::compiler::CompilerFactory Class Reference
onert::compiler::CompilerFactory Class Reference
#include <CompilerFactory.h>
Public Member Functions
std::unique_ptr< ICompiler > create (std::unique_ptr< ir::NNPkg > nnpkg, CompilerOptions *copts, const ir::train::TrainingInfo *training_info=nullptr)
Create ICompiler instance. Ownership of nnpkg is moved to ICompiler instance.
Static Public Member Functions
static CompilerFactory & get ()
Detailed Description
Definition at line 29 of file CompilerFactory.h.
Member Function Documentation
create()
std::unique_ptr< ICompiler > onert::compiler::CompilerFactory::create (std::unique_ptr< ir::NNPkg > nnpkg, CompilerOptions * copts, const ir::train::TrainingInfo * training_info = nullptr)
Create ICompiler instance. Ownership of nnpkg is moved to ICompiler instance.
Compiler is designed on assumption that caller will not use nnpkg after calling this function. So ownership of nnpkg is moved to ICompiler instance to handle memory overhead of nnpkg. If caller want to maintain nnpkg after calling this function, caller should clone nnpkg before calling this function.
Parameters
[in] nnpkg Package to compile
[in] copts Compiler options
[in] training_info Training info if it is a training model, otherwise nullptr
Returns
ICompiler instance pointer which owns nnpkg
Definition at line 31 of file CompilerFactory.cc.
{
  // Returing compiler for training
  if (training_info)
    return std::make_unique<train::TrainingCompiler>(std::move(nnpkg), copts, *training_info);
  // Returing compiler for inference
  return std::make_unique<Compiler>(std::move(nnpkg), copts);
}
Referenced by onert::api::Session::prepare(), and onert::api::Session::train_prepare().
get()
CompilerFactory & onert::compiler::CompilerFactory::get () static
Definition at line 25 of file CompilerFactory.cc.
{
  static CompilerFactory singleton;
  return singleton;
}
Referenced by onert::api::Session::prepare(), and onert::api::Session::train_prepare().
The documentation for this class was generated from the following files:
runtime/onert/core/include/compiler/CompilerFactory.h
runtime/onert/core/src/compiler/CompilerFactory.cc