ONE - On-device Neural Engine: onert::backend::basic::train::TrainableTensor Class Reference
onert::backend::basic::train::TrainableTensor Class Reference
#include <TrainableTensor.h>
Public Member Functions
TrainableTensor ()=delete
virtual ~TrainableTensor ()=default
TrainableTensor (const ir::OperandInfo &info, const ir::Layout layout)
void setBuffer (uint8_t *buffer)
Set the Buffer object. This method is called for static and non-const tensor.
uint8_t * buffer () const override
size_t total_size () const override
Get dimension by index.
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_constant () const override
Return true if the tensor is constant.
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
ir::Shape getShape () const override
Get ir::Shape of tensor.
const ir::OperandInfo & get_info ()
std::vector< ITensor * > optVars () override
Get optimizer variables of this trainable tensor.
void appendOptVar (std::unique_ptr< Tensor > opt_var)
void fillBuffer (const std::shared_ptr< ir::Data > &data)
Public Member Functions inherited from onert::backend::train::ITrainableTensor
virtual ~ITrainableTensor ()=default
IPortableTensor (const ir::OperandInfo &info)
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Protected Attributes
Tensor _tensor
std::vector< std::unique_ptr< Tensor > > _opt_vars
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Definition at line 33 of file TrainableTensor.h.
Constructor & Destructor Documentation
TrainableTensor() [1/2]
onert::backend::basic::train::TrainableTensor::TrainableTensor () delete
~TrainableTensor()
virtual onert::backend::basic::train::TrainableTensor::~TrainableTensor () virtual default
TrainableTensor() [2/2]
onert::backend::basic::train::TrainableTensor::TrainableTensor (const ir::OperandInfo & info, const ir::Layout layout) inline
Definition at line 40 of file TrainableTensor.h.
    : ITrainableTensor{info}, _tensor{info, layout, nullptr}, _opt_vars{}
  {
    // DO NOTHING
  }
Member Function Documentation
appendOptVar()
void onert::backend::basic::train::TrainableTensor::appendOptVar (std::unique_ptr< Tensor > opt_var) inline
Definition at line 78 of file TrainableTensor.h.
{ _opt_vars.emplace_back(std::move(opt_var)); }
References _opt_vars.
buffer()
uint8_t * onert::backend::basic::train::TrainableTensor::buffer () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 53 of file TrainableTensor.h.
{ return _tensor.buffer(); }
References _tensor, and onert::backend::basic::Tensor::buffer().
Referenced by fillBuffer(), and setBuffer().
calcOffset()
size_t onert::backend::basic::train::TrainableTensor::calcOffset (const ir::Coordinates & coords) const inline override virtual
Implements onert::backend::ITensor.
Definition at line 65 of file TrainableTensor.h.
  {
    return _tensor.calcOffset(coords);
  }
References _tensor, onert::backend::basic::Tensor::calcOffset(), and coords.
data_type()
ir::DataType onert::backend::basic::train::TrainableTensor::data_type () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 70 of file TrainableTensor.h.
{ return _tensor.data_type(); }
References _tensor, and onert::backend::basic::Tensor::data_type().
fillBuffer()
void onert::backend::basic::train::TrainableTensor::fillBuffer (const std::shared_ptr< ir::Data > & data)
Definition at line 38 of file TrainableTensor.cc.
{
  auto *buffer = _tensor.buffer();
  assert(buffer);
  assert(total_size() == data->size());
  std::memcpy(buffer, data->base(), data->size());
}
References _tensor, onert::backend::basic::Tensor::buffer(), buffer(), and total_size().
Referenced by onert::backend::train::BackendContext::genKernels().
get_info()
const ir::OperandInfo & onert::backend::basic::train::TrainableTensor::get_info () inline
Definition at line 74 of file TrainableTensor.h.
{ return _tensor.get_info(); }
References _tensor, and onert::backend::IPortableTensor::get_info().
getShape()
ir::Shape onert::backend::basic::train::TrainableTensor::getShape () const inline override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 73 of file TrainableTensor.h.
{ return _tensor.getShape(); };
References _tensor, and onert::backend::basic::Tensor::getShape().
is_constant()
bool onert::backend::basic::train::TrainableTensor::is_constant () const inline override virtual
Return true if the tensor is constant.
Reimplemented from onert::backend::ITensor.
Definition at line 71 of file TrainableTensor.h.
{ return _tensor.is_constant(); }
References _tensor, and onert::backend::basic::Tensor::is_constant().
is_dynamic()
bool onert::backend::basic::train::TrainableTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 72 of file TrainableTensor.h.
{ return _tensor.is_dynamic(); }
References _tensor, and onert::backend::basic::Tensor::is_dynamic().
layout()
ir::Layout onert::backend::basic::train::TrainableTensor::layout () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 69 of file TrainableTensor.h.
{ return _tensor.layout(); }
References _tensor, and onert::backend::basic::Tensor::layout().
optVars()
std::vector< ITensor * > onert::backend::basic::train::TrainableTensor::optVars () override virtual
Get optimizer variables of this trainable tensor.
Returns
Optimizer variables
Implements onert::backend::train::ITrainableTensor.
Definition at line 28 of file TrainableTensor.cc.
{
  std::vector<ITensor *> ret;
  for (auto &&e : _opt_vars)
  {
    ret.emplace_back(e.get());
  }
  return ret;
}
References _opt_vars.
setBuffer()
void onert::backend::basic::train::TrainableTensor::setBuffer (uint8_t * buffer) inline
Set the Buffer object. This method is called for static and non-const tensor.
Definition at line 50 of file TrainableTensor.h.
{ _tensor.setBuffer(buffer); }
References _tensor, buffer(), and onert::backend::basic::Tensor::setBuffer().
total_size()
size_t onert::backend::basic::train::TrainableTensor::total_size () const inline override virtual
Get dimension by index.
Parameters
index Index to get diemension
Returns
size_t Dimension at index
Note
N : dimension(0) H : dimension(1) W : dimension(2) C : dimension(3)
Implements onert::backend::ITensor.
Definition at line 64 of file TrainableTensor.h.
{ return _tensor.total_size(); }
References _tensor, and onert::backend::basic::Tensor::total_size().
Referenced by fillBuffer().
Field Documentation
_opt_vars
std::vector<std::unique_ptr<Tensor> > onert::backend::basic::train::TrainableTensor::_opt_vars protected
Definition at line 90 of file TrainableTensor.h.
Referenced by appendOptVar(), and optVars().
_tensor
Tensor onert::backend::basic::train::TrainableTensor::_tensor protected
Definition at line 89 of file TrainableTensor.h.
Referenced by buffer(), calcOffset(), data_type(), fillBuffer(), get_info(), getShape(), is_constant(), is_dynamic(), layout(), setBuffer(), and total_size().
The documentation for this class was generated from the following files:
runtime/onert/core/include/backend/basic/train/TrainableTensor.h
runtime/onert/core/src/backend/basic/train/TrainableTensor.cc