ONE - On-device Neural Engine: arm_compute::CLMemsetKernel Class Reference
arm_compute::CLMemsetKernel Class Reference
#include <CLMemsetKernel.h>
Public Member Functions
CLMemsetKernel ()
CLMemsetKernel (const CLMemsetKernel &)=delete
CLMemsetKernel & operator= (const CLMemsetKernel &)=delete
CLMemsetKernel (CLMemsetKernel &&)=default
CLMemsetKernel & operator= (CLMemsetKernel &&)=default
~CLMemsetKernel ()=default
void configure (ICLTensor *tensor, const PixelValue &constant_value, Window *window=nullptr)
void configure (const CLCompileContext &compile_context, ICLTensor *tensor, const PixelValue &constant_value, Window *window=nullptr)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *tensor, const PixelValue &constant_value, Window *window=nullptr)
Detailed Description
Interface for filling the planes of a tensor
Definition at line 52 of file CLMemsetKernel.h.
Constructor & Destructor Documentation
CLMemsetKernel() [1/3]
arm_compute::CLMemsetKernel::CLMemsetKernel ()
Default constructor
Definition at line 52 of file CLMemsetKernel.cpp.
: ICLKernel(), _tensor(nullptr), _full_window() {}
CLMemsetKernel() [2/3]
arm_compute::CLMemsetKernel::CLMemsetKernel (const CLMemsetKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLMemsetKernel() [3/3]
arm_compute::CLMemsetKernel::CLMemsetKernel (CLMemsetKernel &&) default
Allow instances of this class to be moved
~CLMemsetKernel()
arm_compute::CLMemsetKernel::~CLMemsetKernel () default
Default destructor
References validate().
Member Function Documentation
configure() [1/2]
void arm_compute::CLMemsetKernel::configure (const CLCompileContext & compile_context, ICLTensor * tensor, const PixelValue & constant_value, Window * window = nullptr)
Initialise the kernel's tensor and filling value
Parameters
[in] compile_context The compile context to be used.
[in,out] tensor Input tensor to fill. Supported data types: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Definition at line 59 of file CLMemsetKernel.cpp.
{
  ARM_COMPUTE_UNUSED(compile_context);
  ARM_COMPUTE_ERROR_ON_NULLPTR(tensor);
  ARM_COMPUTE_ERROR_THROW_ON(validate(tensor->info(), constant_value, window));
  _tensor = tensor;
  const DataType data_type = tensor->info()->data_type();
  const int vec_size_x = 16 / tensor->info()->element_size();
  // Create and update the window (if needed)
  _full_window = calculate_max_window(*tensor->info());
  Window win = _full_window;
  if (window != nullptr)
  {
    ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(win, *window);
    win = *window;
  }
  const int output_width_x = win.num_iterations(0);
  const bool multi_access_x = output_width_x >= vec_size_x;
  const bool remainder_x = output_width_x % vec_size_x > 0;
  if (multi_access_x)
  {
    win.set(
      Window::DimX,
      Window::Dimension(win.x().start(), ceil_to_multiple(win.x().end(), vec_size_x), vec_size_x));
  }
  ICLKernel::configure_internal(win);
  // Create kernel
  CLBuildOptions build_opts;
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(data_type));
  build_opts.add_option("-DCONSTANT_VALUE=" + string_from_pixel_value(constant_value, data_type));
  build_opts.add_option_if(multi_access_x, "-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
  build_opts.add_option_if(multi_access_x && remainder_x,
                           "-DLAST_ACCESSED_X=" + support::cpp11::to_string(
                                                    std::max<int>(output_width_x - vec_size_x, 0)));
  _kernel =
    static_cast<cl::Kernel>(CLKernelLibraryEx::get().create_kernel("memset", build_opts.options()));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), arm_compute::CLKernelLibraryEx::get(), and validate().
configure() [2/2]
void arm_compute::CLMemsetKernel::configure (ICLTensor * tensor, const PixelValue & constant_value, Window * window = nullptr)
Initialise the kernel's tensor and filling value
Parameters
[in,out] tensor Input tensor to fill. Supported data types: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Definition at line 54 of file CLMemsetKernel.cpp.
{
  configure(CLKernelLibrary::get().get_compile_context(), tensor, constant_value, window);
}
References configure().
Referenced by arm_compute::CLOneHot::configure(), and configure().
operator=() [1/2]
CLMemsetKernel & arm_compute::CLMemsetKernel::operator= (CLMemsetKernel &&) default
Allow instances of this class to be moved
operator=() [2/2]
CLMemsetKernel & arm_compute::CLMemsetKernel::operator= (const CLMemsetKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLMemsetKernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 117 of file CLMemsetKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
  // Collapse all the batches on the third
  Window collapsed = window.collapse_if_possible(_full_window, Window::DimZ);
  Window slice = collapsed.first_slice_window_3D();
  do
  {
    unsigned int idx = 0;
    add_3D_tensor_argument(idx, _tensor, slice);
    enqueue(queue, *this, slice, lws_hint());
  } while (collapsed.slide_window_slice_3D(slice));
}
validate()
Status arm_compute::CLMemsetKernel::validate (const ITensorInfo * tensor, const PixelValue & constant_value, Window * window = nullptr) static
Static function to check if given info will lead to a valid configuration of CLMemsetKernel
Parameters
[in] tensor Source tensor info. Data types supported: All.
[in] constant_value The value used to fill the planes of the tensor
[in] window Window to be used in case setting only part of a tensor. Default is nullptr.
Returns
a status
Definition at line 105 of file CLMemsetKernel.cpp.
{
  ARM_COMPUTE_UNUSED(tensor);
  ARM_COMPUTE_UNUSED(constant_value);
  if (window != nullptr)
  {
    ARM_COMPUTE_RETURN_ERROR_ON(window->x().step() != 1);
  }
  return Status{};
}
Referenced by configure(), and ~CLMemsetKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLMemsetKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLMemsetKernel.cpp