ONE - On-device Neural Engine: exo::Conv2DConverter Class Reference
exo::Conv2DConverter Class Reference
Convert loco::Conv2D to locoex::TFLConv2D.
#include <Conv2DConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::Conv2D *origin) final
Converts loco::Conv2D to locoex::TFLConv2D.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::Conv2D >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::Conv2D *node)=0
Detailed Description
Convert loco::Conv2D to locoex::TFLConv2D.
Definition at line 30 of file Conv2DConverter.h.
Member Function Documentation
convert()
bool exo::Conv2DConverter::convert (loco::Conv2D * origin) final virtual
Converts loco::Conv2D to locoex::TFLConv2D.
Note
Because TFLConv2D accepts input and filter of loco::Domain::Tensor, loco::FeatureDecode and loco::FilterDecode will be inserted as an inputs to meet domain invariant. Please refer to the comment in AvgPool2DConvert.
Implements exo::CanonicalNodeConverter< loco::Conv2D >.
Definition at line 37 of file Conv2DConverter.cpp.
{
  auto *graph = origin->graph();
  assert(origin->ifm());
  assert(origin->ker());
  auto tfl_conv2d = graph->nodes()->create<locoex::TFLConv2D>();
  {
    tfl_conv2d->stride()->w(origin->stride()->horizontal());
    tfl_conv2d->stride()->h(origin->stride()->vertical());
    auto pad = origin->pad();
    if (pad->bottom() == 0 && pad->top() == 0 && pad->left() == 0 && pad->right() == 0)
      tfl_conv2d->padding(locoex::Padding::VALID);
    else
      // TODO This is necessary, but not sufficient condition. More rigorous check required
      tfl_conv2d->padding(locoex::Padding::SAME);
    tfl_conv2d->fusedActivationFunction(locoex::FusedActFunc::NONE);
  }
  // let's create a new graph connection with tfl_conv2d
  {
    // input
    auto feature_dec = make_feature_decode<FeatureLayout::NHWC>(origin->ifm());
    tfl_conv2d->input(feature_dec);
    // filter
    auto filter_dec = make_filter_decode<FilterLayout::OHWI>(origin->ker());
    tfl_conv2d->filter(filter_dec);
    // bias
    auto zero_const = graph->nodes()->create<locoex::TFLConst>();
    {
      assert(loco::shape_known(origin));
      assert(loco::dtype_known(origin) && loco::dtype_get(origin) == loco::DataType::FLOAT32);
      auto output_depth = loco::shape_get(origin->ker()).as<loco::FilterShape>().count();
      zero_const->dtype(loco::DataType::FLOAT32);
      zero_const->rank(1);
      zero_const->dim(0) = output_depth;
      zero_const->size<loco::DataType::FLOAT32>(output_depth.value());
      for (uint32_t x = 0; x < output_depth.value(); x++)
        zero_const->at<loco::DataType::FLOAT32>(x) = 0.0;
    }
    tfl_conv2d->bias(zero_const);
    // output
    auto feature_enc = make_feature_encode<FeatureLayout::NHWC>(tfl_conv2d);
    // replace canonical node
    loco::replace(origin).with(feature_enc);
    origin->ifm(nullptr);
  }
  return true;
}
References loco::NodeShape::as(), loco::dtype_get(), loco::dtype_known(), loco::Node::graph(), loco::Stride< 2 >::horizontal(), loco::Conv2D::ifm(), loco::Conv2D::ker(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), exo::make_filter_decode< FilterLayout::OHWI >(), locoex::NONE, loco::Conv2D::pad(), loco::replace(), locoex::SAME, loco::shape_get(), loco::shape_known(), locoex::TFLConv2D::stride(), loco::Conv2D::stride(), locoex::VALID, loco::Stride< 2 >::vertical(), locoex::Stride::w(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::Conv2DConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::Conv2D >.
Definition at line 33 of file Conv2DConverter.h.
{ return "exo::Conv2DConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/Conv2DConverter.h
compiler/exo/src/Conversion/Conv2DConverter.cpp