ONE - On-device Neural Engine: mir::ops::DepthwiseConv2DOp Class Reference
mir::ops::DepthwiseConv2DOp Class Reference
#include <DepthwiseConv2DOp.h>
Public Member Functions
DepthwiseConv2DOp (Output *input, Output *kernel, const Conv2DOpAttributes &attributes)
DepthwiseConv2DOp (Output *input, Output *kernel, Output *bias, const Conv2DOpAttributes &attributes)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
const std::vector< std::int32_t > & getStrides () const
const std::vector< std::int32_t > & getPaddingBefore () const
const std::vector< std::int32_t > & getPaddingAfter () const
DataFormat getDataFormat () const
const Conv2DOpAttributes & getAttributes () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 29 of file DepthwiseConv2DOp.h.
Constructor & Destructor Documentation
DepthwiseConv2DOp() [1/2]
mir::ops::DepthwiseConv2DOp::DepthwiseConv2DOp (Output * input, Output * kernel, const Conv2DOpAttributes & attributes) inline
Definition at line 32 of file DepthwiseConv2DOp.h.
    : Operation(Type::depthwiseConv, {input, kernel}), _attributes(attributes)
  {
    inferOutputTypes();
  }
DepthwiseConv2DOp() [2/2]
mir::ops::DepthwiseConv2DOp::DepthwiseConv2DOp (Output * input, Output * kernel, Output * bias, const Conv2DOpAttributes & attributes) inline
Definition at line 38 of file DepthwiseConv2DOp.h.
    : Operation(Type::depthwiseConv, {input, kernel, bias}), _attributes(attributes)
  {
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::DepthwiseConv2DOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 45 of file DepthwiseConv2DOp.h.
  {
    if (inputs.size() == 2)
      return new DepthwiseConv2DOp(inputs[0], inputs[1], _attributes);
    else
      return new DepthwiseConv2DOp(inputs[0], inputs[1], inputs[2], _attributes);
  }
getAttributes()
const Conv2DOpAttributes & mir::ops::DepthwiseConv2DOp::getAttributes () const inline
Definition at line 61 of file DepthwiseConv2DOp.h.
{ return _attributes; }
getDataFormat()
DataFormat mir::ops::DepthwiseConv2DOp::getDataFormat () const inline
Definition at line 59 of file DepthwiseConv2DOp.h.
{ return _attributes.data_format; }
References mir::Conv2DOpAttributes::data_format.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getPaddingAfter()
const std::vector< std::int32_t > & mir::ops::DepthwiseConv2DOp::getPaddingAfter () const inline
Definition at line 57 of file DepthwiseConv2DOp.h.
{ return _attributes.padding_after; }
References mir::Conv2DOpAttributes::padding_after.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getPaddingBefore()
const std::vector< std::int32_t > & mir::ops::DepthwiseConv2DOp::getPaddingBefore () const inline
Definition at line 55 of file DepthwiseConv2DOp.h.
{ return _attributes.padding_before; }
References mir::Conv2DOpAttributes::padding_before.
Referenced by mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getStrides()
const std::vector< std::int32_t > & mir::ops::DepthwiseConv2DOp::getStrides () const inline
Definition at line 53 of file DepthwiseConv2DOp.h.
{ return _attributes.strides; }
References mir::Conv2DOpAttributes::strides.
Referenced by mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir2loco::Transformer::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/DepthwiseConv2DOp.h
compiler/mir/src/ops/DepthwiseConv2DOp.cpp