ONE - On-device Neural Engine: onert::compiler::ExecutorFactory Class Reference
onert::compiler::ExecutorFactory Class Reference
#include <ExecutorFactory.h>
Public Member Functions
exec::IExecutor * create (std::unique_ptr< compiler::LoweredGraph > lowered_graph, const std::shared_ptr< exec::IExecutors > &executors, const ExecutorFactoryArgs &args)
exec::IExecutor * create (std::unique_ptr< compiler::train::LoweredTrainableGraph > lowered_graph, const std::shared_ptr< exec::IExecutors > &executors, const ExecutorFactoryArgs &args, const ir::train::TrainingInfo &training_info)
Static Public Member Functions
static ExecutorFactory & get ()
Detailed Description
Definition at line 46 of file ExecutorFactory.h.
Member Function Documentation
create() [1/2]
exec::IExecutor * onert::compiler::ExecutorFactory::create (std::unique_ptr< compiler::LoweredGraph > lowered_graph, const std::shared_ptr< exec::IExecutors > & executors, const ExecutorFactoryArgs & args)
Definition at line 312 of file ExecutorFactory.cc.
{
  assert(args.options != nullptr);
  return _map.at(args.options->executor)(std::move(lowered_graph), executors, args);
}
Referenced by onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), and onert::compiler::train::TrainingCompiler::compile().
create() [2/2]
exec::IExecutor * onert::compiler::ExecutorFactory::create (std::unique_ptr< compiler::train::LoweredTrainableGraph > lowered_graph, const std::shared_ptr< exec::IExecutors > & executors, const ExecutorFactoryArgs & args, const ir::train::TrainingInfo & training_info)
Definition at line 608 of file ExecutorFactory.cc.
{
  assert(args.options != nullptr);
  if (args.options->executor != "Linear")
    throw std::runtime_error("ExecutorFactory: TrainableExecutor supports only 'Linear' now");
  return createTrainableExecutor(std::move(lowered_graph), executors, args, training_info);
}
get()
ExecutorFactory & onert::compiler::ExecutorFactory::get () static
Definition at line 297 of file ExecutorFactory.cc.
{
  static ExecutorFactory singleton;
  return singleton;
}
Referenced by onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), and onert::compiler::train::TrainingCompiler::compile().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/ExecutorFactory.h
runtime/onert/core/src/compiler/ExecutorFactory.cc