ONE - On-device Neural Engine: onert::backend::cpu::ops::ConvolutionLayer Class Reference
onert::backend::cpu::ops::ConvolutionLayer Class Reference
#include <ConvolutionLayer.h>
Public Member Functions
ConvolutionLayer ()
~ConvolutionLayer ()
void convFloat32 ()
void convQ8uPerTensor ()
void convQ8uPerChannel ()
void convQ8i ()
void configure (const IPortableTensor *input, const IPortableTensor *kernel, const IPortableTensor *bias, ir::PaddingType _paddingType, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t dilationWidthFactor, const uint32_t dilationHeightFactor, const ir::Activation activation, IPortableTensor *output)
void run () override
void prepare () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 44 of file ConvolutionLayer.h.
Constructor & Destructor Documentation
ConvolutionLayer()
onert::backend::cpu::ops::ConvolutionLayer::ConvolutionLayer ()
Definition at line 32 of file ConvolutionLayer.cc.
  : _input(nullptr), _kernel(nullptr), _bias(nullptr), _output(nullptr),
    _paddingType(ir::PaddingType::EXPLICIT), _paddingLeft(0), _paddingTop(0), _paddingRight(0),
    _paddingBottom(0), _strideWidth(0), _strideHeight(0), _dilationWidthFactor(1),
    _dilationHeightFactor(1), _activation(ir::Activation::NONE),
    _conv_kernel(new nnfw::cker::Conv()), _prepare(false)
{
  // DO NOTHING
}
~ConvolutionLayer()
onert::backend::cpu::ops::ConvolutionLayer::~ConvolutionLayer () default
Member Function Documentation
configure()
void onert::backend::cpu::ops::ConvolutionLayer::configure (const IPortableTensor * input, const IPortableTensor * kernel, const IPortableTensor * bias, ir::PaddingType _paddingType, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t dilationWidthFactor, const uint32_t dilationHeightFactor, const ir::Activation activation, IPortableTensor * output)
Definition at line 154 of file ConvolutionLayer.cc.
{
  _input = input;
  _kernel = kernel;
  _bias = bias;
  _paddingType = paddingType;
  _paddingLeft = paddingLeft;
  _paddingRight = paddingRight;
  _paddingTop = paddingTop;
  _paddingBottom = paddingBottom;
  _strideWidth = strideWidth;
  _strideHeight = strideHeight;
  _dilationWidthFactor = dilationWidthFactor;
  _dilationHeightFactor = dilationHeightFactor;
  _activation = activation;
  _output = output;
}
convFloat32()
void onert::backend::cpu::ops::ConvolutionLayer::convFloat32 ()
Definition at line 44 of file ConvolutionLayer.cc.
{
  float output_activation_min = 0, output_activation_max = 0;
  CalculateActivationRange(_activation, &output_activation_min, &output_activation_max);
  nnfw::cker::ConvParams op_params;
  op_params.padding_type = getPaddingType(_paddingType);
  op_params.padding_values.width = _paddingLeft;
  op_params.padding_values.height = _paddingTop;
  op_params.stride_width = _strideWidth;
  op_params.stride_height = _strideHeight;
  op_params.dilation_width_factor = _dilationWidthFactor;
  op_params.dilation_height_factor = _dilationHeightFactor;
  op_params.float_activation_min = output_activation_min;
  op_params.float_activation_max = output_activation_max;
  nnfw::cker::Conv &kernel = *_conv_kernel;
  kernel(op_params, getShape(_input), getBuffer<float>(_input), getShape(_kernel),
         getBuffer<float>(_kernel), getShape(_bias), getBuffer<float>(_bias), getShape(_output),
         getBuffer<float>(_output));
}
References onert::util::CalculateActivationRange(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, nnfw::cker::ConvParams::float_activation_max, nnfw::cker::ConvParams::float_activation_min, onert::backend::cpu::ops::getPaddingType(), onert::backend::cpu::ops::getShape(), nnfw::cker::PaddingValues::height, nnfw::cker::ConvParams::padding_type, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
Referenced by run().
convQ8i()
void onert::backend::cpu::ops::ConvolutionLayer::convQ8i ()
Definition at line 128 of file ConvolutionLayer.cc.
{
  int32_t output_activation_min = 0;
  int32_t output_activation_max = 0;
  CalculateActivationRangeQuantized(_activation, _output, &output_activation_min,
                                    &output_activation_max);
  nnfw::cker::ConvParams op_params;
  op_params.input_offset = -_input->data_zero_point();
  op_params.output_offset = _output->data_zero_point();
  op_params.stride_height = _strideHeight;
  op_params.stride_width = _strideWidth;
  op_params.dilation_height_factor = _dilationHeightFactor;
  op_params.dilation_width_factor = _dilationWidthFactor;
  op_params.padding_values.height = _paddingTop;
  op_params.padding_values.width = _paddingLeft;
  op_params.quantized_activation_min = output_activation_min;
  op_params.quantized_activation_max = output_activation_max;
  nnfw::cker::Conv &kernel = *_conv_kernel;
  kernel(op_params, getShape(_input), reinterpret_cast<const int8_t *>(_input->buffer()),
         getShape(_kernel), reinterpret_cast<const int8_t *>(_kernel->buffer()), getShape(_bias),
         reinterpret_cast<const int32_t *>(_bias->buffer()), getShape(_output),
         reinterpret_cast<int8_t *>(_output->buffer()));
}
References onert::backend::ITensor::buffer(), onert::backend::cpu::ops::CalculateActivationRangeQuantized(), onert::backend::IPortableTensor::data_zero_point(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, onert::backend::cpu::ops::getShape(), nnfw::cker::PaddingValues::height, nnfw::cker::ConvParams::input_offset, nnfw::cker::ConvParams::output_offset, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::quantized_activation_max, nnfw::cker::ConvParams::quantized_activation_min, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
Referenced by run().
convQ8uPerChannel()
void onert::backend::cpu::ops::ConvolutionLayer::convQ8uPerChannel ()
Definition at line 102 of file ConvolutionLayer.cc.
{
  nnfw::cker::ConvParams op_params;
  op_params.padding_values.width = _paddingLeft;
  op_params.padding_values.height = _paddingTop;
  op_params.stride_width = _strideWidth;
  op_params.stride_height = _strideHeight;
  op_params.dilation_width_factor = _dilationWidthFactor;
  op_params.dilation_height_factor = _dilationHeightFactor;
  op_params.input_offset = -_input->data_zero_point();
  op_params.output_offset = _output->data_zero_point();
  int32_t output_activation_min = 0;
  int32_t output_activation_max = 0;
  CalculateActivationRangeQuantized(_activation, _output, &output_activation_min,
                                    &output_activation_max);
  op_params.quantized_activation_min = output_activation_min;
  op_params.quantized_activation_max = output_activation_max;
  // NOTE: The following fields of ConvParams are not used:
  // padding_type, weights_offset, output_{multiplier,shift}, float_activation_{min,max}
  nnfw::cker::Conv &kernel = *_conv_kernel;
  kernel(op_params, getShape(_input), getBuffer<uint8_t>(_input), getShape(_kernel),
         getBuffer<uint8_t>(_kernel), _kernel->data_zero_points().data(), getShape(_bias),
         getBuffer<int32_t>(_bias), getShape(_output), getBuffer<uint8_t>(_output));
}
References onert::backend::cpu::ops::CalculateActivationRangeQuantized(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::IPortableTensor::data_zero_points(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, onert::backend::cpu::ops::getShape(), nnfw::cker::PaddingValues::height, nnfw::cker::ConvParams::input_offset, nnfw::cker::ConvParams::output_offset, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::quantized_activation_max, nnfw::cker::ConvParams::quantized_activation_min, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
Referenced by run().
convQ8uPerTensor()
void onert::backend::cpu::ops::ConvolutionLayer::convQ8uPerTensor ()
Definition at line 66 of file ConvolutionLayer.cc.
{
  int32_t output_activation_min = 0;
  int32_t output_activation_max = 0;
  CalculateActivationRangeQuantized(_activation, _output, &output_activation_min,
                                    &output_activation_max);
  double real_multiplier = 0.0;
  int32_t output_multiplier = 0;
  int32_t output_shift = 0;
  GetQuantizedConvolutionMultiplier(_input, _kernel, _bias, _output, &real_multiplier);
  QuantizeMultiplier(real_multiplier, &output_multiplier, &output_shift);
  nnfw::cker::ConvParams op_params;
  op_params.stride_width = _strideWidth;
  op_params.stride_height = _strideHeight;
  op_params.dilation_width_factor = _dilationWidthFactor;
  op_params.dilation_height_factor = _dilationHeightFactor;
  op_params.padding_type = getPaddingType(_paddingType);
  op_params.padding_values.width = _paddingLeft;
  op_params.padding_values.height = _paddingTop;
  op_params.input_offset = -_input->data_zero_point();
  op_params.weights_offset = -_kernel->data_zero_point();
  op_params.output_offset = _output->data_zero_point();
  op_params.output_multiplier = output_multiplier;
  op_params.output_shift = output_shift;
  op_params.quantized_activation_min = output_activation_min;
  op_params.quantized_activation_max = output_activation_max;
  op_params.is_replaced_weights = true;
  nnfw::cker::Conv &kernel = *_conv_kernel;
  kernel(op_params, getShape(_input), getBuffer<uint8_t>(_input), getShape(_kernel),
         getBuffer<uint8_t>(_kernel), getShape(_bias), getBuffer<int32_t>(_bias), getShape(_output),
         getBuffer<uint8_t>(_output));
}
References onert::backend::cpu::ops::CalculateActivationRangeQuantized(), onert::backend::IPortableTensor::data_zero_point(), nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, onert::backend::cpu::ops::getPaddingType(), onert::backend::cpu::ops::GetQuantizedConvolutionMultiplier(), onert::backend::cpu::ops::getShape(), nnfw::cker::PaddingValues::height, nnfw::cker::ConvParams::input_offset, nnfw::cker::ConvParams::is_replaced_weights, nnfw::cker::ConvParams::output_multiplier, nnfw::cker::ConvParams::output_offset, nnfw::cker::ConvParams::output_shift, nnfw::cker::ConvParams::padding_type, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::quantized_activation_max, nnfw::cker::ConvParams::quantized_activation_min, onert::backend::cpu::ops::QuantizeMultiplier(), nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, nnfw::cker::ConvParams::weights_offset, and nnfw::cker::PaddingValues::width.
Referenced by run().
prepare()
void onert::backend::cpu::ops::ConvolutionLayer::prepare () override virtual
Reimplemented from onert::exec::IFunction.
Definition at line 234 of file ConvolutionLayer.cc.
{
  if (_prepare)
    return;
  nnfw::cker::Conv &kernel = *_conv_kernel;
  if (_input->data_type() == OperandType::FLOAT32 && _kernel->is_constant())
  {
    bool is_transposed = false;
    kernel.prepareF32(getShape(_kernel), getBuffer<float>(_kernel), getPaddingType(_paddingType),
                      is_transposed, _dilationWidthFactor, _dilationHeightFactor);
    // Decrease reference of _kernel(weights) only when _kernel is constant
    if (is_transposed)
    {
      auto kernel_tensor = dynamic_cast<const Tensor *>(_kernel);
      if (kernel_tensor)
        // TODO Remove const_cast
        const_cast<Tensor *>(kernel_tensor)->decrease_ref();
    }
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM && _kernel->is_constant() &&
           !_input->is_dynamic() && !_output->is_dynamic())
  {
    const bool per_channel_quantized = _kernel->data_scales().size() > 1;
    if (per_channel_quantized)
    {
      GetQuantizedConvolutionMultipliersAndShifts(
        _input->data_scale(), _output->data_scale(), _kernel->data_scales().data(),
        _kernel->data_scales().size(), getShape(_kernel).Dims(0),
        kernel.per_channel_output_multiplier(), kernel.per_channel_output_shift());
    }
    else
    {
      kernel.prepareQ8uPerTensor(getShape(_input), getShape(_kernel), getShape(_output),
                                 _strideWidth, _strideHeight, _dilationWidthFactor,
                                 _dilationHeightFactor);
    }
  }
  else if (_input->data_type() == OperandType::QUANT_INT8_ASYMM)
  {
    if (_kernel->is_constant() && !_input->is_dynamic() && !_output->is_dynamic())
    {
      GetQuantizedConvolutionMultipliersAndShifts(
        _input->data_scale(), _output->data_scale(), _kernel->data_scales().data(),
        _kernel->data_scales().size(), getShape(_kernel).Dims(0),
        kernel.per_channel_output_multiplier(), kernel.per_channel_output_shift());
    }
    else
    {
      throw std::runtime_error{"Conv2D: Int8 dynamic weight is not supported"};
    }
  }
  _prepare = true;
}
References onert::backend::IPortableTensor::data_scale(), onert::backend::IPortableTensor::data_scales(), onert::backend::ITensor::data_type(), onert::backend::cpu::ops::getPaddingType(), onert::backend::cpu::ops::GetQuantizedConvolutionMultipliersAndShifts(), onert::backend::cpu::ops::getShape(), onert::backend::ITensor::is_constant(), onert::backend::ITensor::is_dynamic(), nnfw::cker::Conv::per_channel_output_multiplier(), nnfw::cker::Conv::per_channel_output_shift(), nnfw::cker::Conv::prepareF32(), and nnfw::cker::Conv::prepareQ8uPerTensor().
Referenced by run().
run()
void onert::backend::cpu::ops::ConvolutionLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 179 of file ConvolutionLayer.cc.
{
  prepare();
  if (_input->is_dynamic() || _kernel->is_dynamic())
  {
    const auto ifm_shape = _input->getShape().asFeature(_input->layout());
    const auto ofm_shape = _output->getShape().asFeature(_input->layout());
    // Kernel format is [depth_out, kernel_height, kernel_width, depth_in].
    const auto ker_shape = _kernel->getShape();
    const auto ker_height = ker_shape.dim(1);
    const auto ker_width = ker_shape.dim(2);
    ir::Stride stride;
    stride.vertical = _strideWidth;
    stride.horizontal = _strideWidth;
    ir::Padding param_padding;
    param_padding.type = _paddingType;
    param_padding.param.left = _paddingLeft;
    param_padding.param.right = _paddingRight;
    param_padding.param.top = _paddingTop;
    param_padding.param.bottom = _paddingBottom;
    const auto padding =
      ir::calculatePadding(param_padding, ifm_shape, ofm_shape, stride, ker_width, ker_height,
                           _dilationWidthFactor, _dilationHeightFactor);
    _paddingLeft = padding.left;
    _paddingRight = padding.right;
    _paddingTop = padding.top;
    _paddingBottom = padding.bottom;
  }
  if (_input->data_type() == OperandType::FLOAT32)
  {
    convFloat32();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    const bool per_channel_quantized = _kernel->data_scales().size() > 1;
    if (per_channel_quantized)
      convQ8uPerChannel();
    else
      convQ8uPerTensor();
  }
  else if (_input->data_type() == OperandType::QUANT_INT8_ASYMM)
  {
    convQ8i();
  }
  else
  {
    throw std::runtime_error{"Conv: unsupported data type"};
  }
}
References onert::ir::ExplicitPadding::bottom, onert::ir::calculatePadding(), convFloat32(), convQ8i(), convQ8uPerChannel(), convQ8uPerTensor(), onert::backend::IPortableTensor::data_scales(), onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), onert::ir::Stride::horizontal, onert::backend::ITensor::is_dynamic(), onert::backend::ITensor::layout(), onert::ir::ExplicitPadding::left, onert::ir::Padding::param, prepare(), onert::ir::ExplicitPadding::right, onert::ir::ExplicitPadding::top, onert::ir::Padding::type, and onert::ir::Stride::vertical.
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ConvolutionLayer.h
runtime/onert/backend/cpu/ops/ConvolutionLayer.cc