ONE - On-device Neural Engine: RawPaddingBuilder Class Reference
RawPaddingBuilder Class Reference
Construct a raw padding from each Layer parameter.
#include <PaddingUtils.h>
Public Member Functions
RawPadding with (const ::caffe::ConvolutionParameter &) const
RawPadding with (const ::caffe::PoolingParameter &) const
Friends
RawPaddingBuilder build_raw_padding (void)
Detailed Description
Construct a raw padding from each Layer parameter.
Note
This class is an auxiliary class for build_raw_padding function below
Definition at line 29 of file PaddingUtils.h.
Member Function Documentation
with() [1/2]
RawPadding RawPaddingBuilder::with (const ::caffe::ConvolutionParameter & param) const
Definition at line 24 of file PaddingUtils.cpp.
{
  RawPadding res;
  if (param.has_pad_h() || param.has_pad_w())
  {
    assert(param.pad().size() == 0);
    assert(param.has_pad_h() && param.has_pad_w());
    res.resize(2);
    res.value(0) = param.pad_h();
    res.value(1) = param.pad_w();
  }
  else
  {
    // NOTE pad and pad_h/pad_w cannot be specified at the same time
    //
    // Reference: BaseConvolutionLayer<Dtype>::LayerSetUp in base_conv_layer.cpp
    assert(!param.has_pad_h() && !param.has_pad_w());
    uint32_t rank = param.pad().size();
    res.resize(rank);
    for (uint32_t axis = 0; axis < rank; ++axis)
    {
      res.value(axis) = param.pad(axis);
    }
  }
  return res;
}
Referenced by PoolingSpec::horizontal_pad(), ConvolutionSpec::pad(), and PoolingSpec::vertical_pad().
with() [2/2]
RawPadding RawPaddingBuilder::with (const ::caffe::PoolingParameter & param) const
Definition at line 56 of file PaddingUtils.cpp.
{
  RawPadding res;
  if (param.has_pad_h() || param.has_pad_w())
  {
    assert(!param.has_pad());
    assert(param.has_pad_h() && param.has_pad_w());
    res.resize(2);
    res.value(0) = param.pad_h();
    res.value(1) = param.pad_w();
  }
  else
  {
    // NOTE pad and pad_h/pad_w cannot be specified at the same time
    //
    // Reference: PoolingLayer<Dtype>::LayerSetUp in pooling_layer.cpp
    assert(!param.has_pad_h() && !param.has_pad_w());
    if (param.has_pad())
    {
      res.resize(1);
      res.value(0) = param.pad();
    }
  }
  return res;
}
Friends And Related Function Documentation
build_raw_padding
RawPaddingBuilder build_raw_padding (void) friend
RawPaddingBuilder is introduced to support the following code pattern:
auto raw_padding = build_raw_padding().with(conv_param); ...
Definition at line 86 of file PaddingUtils.cpp.
{ return RawPaddingBuilder{}; }
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/PaddingUtils.h
compiler/enco/frontend/caffe/src/PaddingUtils.cpp