ONE - On-device Neural Engine: nnc::ArtifactVariable Class Reference
nnc::ArtifactVariable Class Reference
Represents a variable.
#include <ArtifactModel.h>
Public Member Functions
ArtifactVariable (std::string type_name, std::string var_name, std::list< std::shared_ptr< ArtifactExpr > > dimensions={}, std::list< std::shared_ptr< ArtifactExpr > > initializers={})
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
const std::string & typeName () const
const std::list< std::shared_ptr< ArtifactExpr > > & getDimensions () const
const std::list< std::shared_ptr< ArtifactExpr > > & getInitializers () const
std::shared_ptr< ArtifactId > use ()
Public Member Functions inherited from nnc::ArtifactNamed
ArtifactNamed (std::string name)
const std::string & name () const
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents a variable.
Definition at line 325 of file ArtifactModel.h.
Constructor & Destructor Documentation
ArtifactVariable()
nnc::ArtifactVariable::ArtifactVariable (std::string type_name, std::string var_name, std::list< std::shared_ptr< ArtifactExpr > > dimensions = {}, std::list< std::shared_ptr< ArtifactExpr > > initializers = {}) inline
Definition at line 328 of file ArtifactModel.h.
                                                                     {},
                   std::list<std::shared_ptr<ArtifactExpr>> initializers = {})
    : _typeName(std::move(type_name)), _dimensions(std::move(dimensions)),
      _initializers(std::move(initializers)), ArtifactNamed(std::move(var_name))
  {
  }
Member Function Documentation
accept()
void nnc::ArtifactVariable::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Reimplemented in nnc::ArtifactClassVariable.
Definition at line 336 of file ArtifactModel.h.
{ g->visit(this); }
getDimensions()
const std::list< std::shared_ptr< ArtifactExpr > > & nnc::ArtifactVariable::getDimensions () const inline
Definition at line 339 of file ArtifactModel.h.
{ return _dimensions; };
Referenced by nnc::ArtifactGeneratorCppCode::visit().
getInitializers()
const std::list< std::shared_ptr< ArtifactExpr > > & nnc::ArtifactVariable::getInitializers () const inline
Definition at line 340 of file ArtifactModel.h.
{ return _initializers; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
typeName()
const std::string & nnc::ArtifactVariable::typeName () const inline
Definition at line 338 of file ArtifactModel.h.
{ return _typeName; }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
use()
std::shared_ptr< ArtifactId > nnc::ArtifactVariable::use () inline
Definition at line 341 of file ArtifactModel.h.
{ return std::make_shared<ArtifactId>(this); }
The documentation for this class was generated from the following file:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h