ONE - On-device Neural Engine: luci::CircleNodeSummaryBuilder Class Reference
luci::CircleNodeSummaryBuilder Class Reference
#include <CircleNodeSummaryBuilder.h>
Public Member Functions
bool build (const loco::Node *node, const locop::SymbolTable *tbl, locop::NodeSummary &s)
Detailed Description
Definition at line 31 of file CircleNodeSummaryBuilder.h.
Member Function Documentation
build()
bool luci::CircleNodeSummaryBuilder::build (const loco::Node * node, const locop::SymbolTable * tbl, locop::NodeSummary & s)
Definition at line 52 of file CircleNodeSummaryBuilder.cpp.
{
  if (node->dialect() != luci::CircleDialect::get())
    return false;
  auto ptr_to_str = [](const void *ptr) {
    std::stringstream ss;
    ss << ptr;
    return ss.str();
  };
  auto shape_to_str = [](const luci::CircleNode *node) {
    std::stringstream ss;
    ss << "<";
    for (uint32_t i = 0; i < node->rank(); ++i)
    {
      if (i)
        ss << ",";
      ss << (node->dim(i).known() ? node->dim(i).value() : -1);
    }
    ss << ">";
    return ss.str();
  };
  auto circle_node = loco::must_cast<const luci::CircleNode *>(node);
  if (const auto builder = create_builder(circle_node))
  {
    if (!builder->validate(circle_node))
    {
      s.state(locop::NodeDesc::State::Invalid);
      return false;
    }
    auto input_names = builder->get_input_names(circle_node);
    assert(node->arity() == input_names.size());
    for (uint32_t i = 0; i < node->arity(); ++i)
      s.args().append(input_names.at(i), tbl->lookup(node->arg(i)));
    builder->build_attributes(circle_node, s);
    builder->update_status(s);
    s.opname(circle_opname(circle_node->opcode()));
    s.comments().append("[" + circle_node->name() + " " + shape_to_str(circle_node) +
                        "] = " + ptr_to_str(node));
    return true;
  }
  else
  {
    // When SummaryBuilder is not implemented, return false
    return false;
  }
}
References loco::Node::arg(), loco::Node::arity(), loco::Node::dialect(), luci::CircleDialect::get(), locop::NodeDesc::Invalid, loco::must_cast(), and luci::must_cast().
Referenced by create_circle_node_summary().
The documentation for this class was generated from the following files:
compiler/luci/logex/include/luci/CircleNodeSummaryBuilder.h
compiler/luci/logex/src/CircleNodeSummaryBuilder.cpp