ONE - On-device Neural Engine: coco::Conv2D Class Reference
coco::Conv2D Class Reference
2D Convolution over 3D Feature Map with 4D kernel
#include <Ops.h>
Public Member Functions
Conv2D ()
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const override
Return a set of object(s) used during execution.
Conv2D * asConv2D (void) override
const Conv2D * asConv2D (void) const override
Instr * loc (void) override
Op * arg (void) const
void arg (Op *arg)
KernelObject * ker (void) const
void ker (KernelObject *ker)
uint32_t group (void) const
Divide an input and kernel (= convolution filter) into G independent groups.
void group (uint32_t g)
Padding2D * pad (void)
const Padding2D * pad (void) const
Stride2D * stride (void)
const Stride2D * stride (void) const
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Public Member Functions inherited from coco::Object::Consumer
virtual ~Consumer ()=default
Public Member Functions inherited from coco::Bag::Reader
virtual ~Reader ()=default
Public Member Functions inherited from coco::Locatable
virtual ~Locatable ()=default
virtual Instr * loc (void)=0
Detailed Description
2D Convolution over 3D Feature Map with 4D kernel
NOTE IFM and OFM are implicit. Only 4D kernel is explicit in this class TODO Decide source code layout policy and extract this class if necessary
Definition at line 73 of file Ops.h.
Constructor & Destructor Documentation
Conv2D()
coco::Conv2D::Conv2D () explicit
Definition at line 24 of file Conv2D.cpp.
               : _ker{this}, _arg{this}
{
  // DO NOTHING
}
Member Function Documentation
arg() [1/3]
void coco::Conv2D::arg (Op * arg) inline
Definition at line 96 of file Ops.h.
{ _arg.child(arg); }
References arg(), and coco::Part::child().
arg() [2/3]
Op * coco::Conv2D::arg (uint32_t n) const final virtual
Return N-th argument.
Note
The behavior of arg(n) is defined only when n < artiy()
Implements coco::Op.
Referenced by enco::output_shape(), and OpPrinter::visit().
arg() [3/3]
Op * coco::Conv2D::arg (void) const inline
Definition at line 95 of file Ops.h.
{ return _arg.child(); }
References coco::Part::child().
Referenced by arg(), and uses().
arity()
uint32_t coco::Conv2D::arity (void) const final virtual
Return the number of arguments (# of child Ops)
Implements coco::Op.
Definition at line 29 of file Conv2D.cpp.
{
  // Conv2D has one argument (IFM)
  // NOTE This design is subject to change
  return 1;
}
asConv2D() [1/2]
const Conv2D * coco::Conv2D::asConv2D (void) const inline override
Definition at line 86 of file Ops.h.
{ return this; }
asConv2D() [2/2]
Conv2D * coco::Conv2D::asConv2D (void) inline override
Definition at line 85 of file Ops.h.
{ return this; }
group() [1/2]
void coco::Conv2D::group (uint32_t g) inline
Definition at line 117 of file Ops.h.
{ _group = g; }
group() [2/2]
uint32_t coco::Conv2D::group (void) const inline
Divide an input and kernel (= convolution filter) into G independent groups.
Given an input of shape(Ic, Ih, Iw), a kernel of shape(Kn, Kc, Kh, Kw), and group G, Conv2D is identical to G independent convolutions over G inputs of shape(Ic / G, Ih, Iw) and a kernel of shape(Kn / G, Kc, Kh, Kw) followed by concatenation.
REQUIRED
"Ic" SHOULD BE a multiple of "G"
"Kc" SHOULD BE identical to "Ic /G"
NOTE Depthwise convolution is a special case of group convolution where Ic == G.
Definition at line 116 of file Ops.h.
{ return _group; }
Referenced by caffeimport::ConvolutionBuilder::build().
ker() [1/2]
void coco::Conv2D::ker (KernelObject * ker)
Definition at line 62 of file Conv2D.cpp.
{ _ker.value(ker); }
References ker(), and coco::Use::value().
ker() [2/2]
KernelObject * coco::Conv2D::ker (void) const
Definition at line 64 of file Conv2D.cpp.
{
  if (auto obj = _ker.value())
  {
    assert(obj->asKernel() != nullptr);
    return obj->asKernel();
  }
  return nullptr;
}
References coco::Use::value().
Referenced by tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), ker(), enco::output_shape(), uses(), and OpPrinter::visit().
loc()
Instr * coco::Conv2D::loc (void) inline override virtual
Implements coco::Locatable.
Definition at line 89 of file Ops.h.
{ return parent(); }
References coco::Op::parent().
pad() [1/2]
Padding2D * coco::Conv2D::pad (void) inline
Definition at line 120 of file Ops.h.
{ return &_pad; }
Referenced by enco::output_shape(), and OpPrinter::visit().
pad() [2/2]
const Padding2D * coco::Conv2D::pad (void) const inline
Definition at line 121 of file Ops.h.
{ return &_pad; }
stride() [1/2]
Stride2D * coco::Conv2D::stride (void) inline
Definition at line 124 of file Ops.h.
{ return &_stride; }
Referenced by enco::output_shape(), and OpPrinter::visit().
stride() [2/2]
const Stride2D * coco::Conv2D::stride (void) const inline
Definition at line 125 of file Ops.h.
{ return &_stride; }
uses()
std::set< Object * > coco::Conv2D::uses (void) const override virtual
Return a set of object(s) used during execution.
NOTE There is no 'def' method as Op is not allowed to define a new object
Implements coco::Op.
Definition at line 42 of file Conv2D.cpp.
{
  std::set<Object *> res;
  if (ker())
  {
    res.insert(ker());
  }
  if (auto ifm = arg())
  {
    for (auto obj : ifm->uses())
    {
      res.insert(obj);
    }
  }
  return res;
}
References arg(), and ker().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Ops.h
compiler/coco/core/src/IR/Conv2D.cpp