ONE - On-device Neural Engine: record_hessian::HessianComputer Class Reference
record_hessian::HessianComputer Class Reference
#include <HessianComputer.h>
Public Member Functions
void recordHessian (const luci::CircleNode *node, const luci_interpreter::Tensor *input_tensor)
std::unique_ptr< HessianMap > getMap ()
Detailed Description
Definition at line 38 of file HessianComputer.h.
Member Function Documentation
getMap()
std::unique_ptr< HessianMap > record_hessian::HessianComputer::getMap ()
Definition at line 202 of file HessianComputer.cpp.
{
  auto hessian_map = std::make_unique<HessianMap>();
  for (auto item : _hessian_map)
  {
    auto &vec = (*hessian_map)[item.first];
    vec = item.second.hessian;
  }
  return hessian_map;
}
Referenced by record_hessian::HessianObserver::hessianData().
recordHessian()
void record_hessian::HessianComputer::recordHessian (const luci::CircleNode * node, const luci_interpreter::Tensor * input_tensor)
Definition at line 178 of file HessianComputer.cpp.
{
  if (node == nullptr || input_tensor == nullptr)
    throw std::invalid_argument("RecordHessian: node or input_tensor is null.");
  if (input_tensor->element_type() != luci_interpreter::DataType::FLOAT32)
    throw std::runtime_error("RecordHessian: Unsupported dtype: only FLOAT32 is supported.");
  _input_tensor = input_tensor;
  switch (node->opcode())
  {
    case luci::CircleOpcode::FULLY_CONNECTED:
      recordHessianForFullyConnected(node);
      break;
    case luci::CircleOpcode::CONV_2D:
      recordHessianForConv2D(node);
      break;
    default:
      throw std::runtime_error("RecordHessian: " + node->name() + " is unsupported op.");
  }
}
References luci_interpreter::Tensor::element_type(), luci::CircleNode::name(), and luci::CircleNode::opcode().
Referenced by record_hessian::HessianObserver::postTensorWrite().
The documentation for this class was generated from the following files:
compiler/record-hessian/include/record-hessian/HessianComputer.h
compiler/record-hessian/src/HessianComputer.cpp