ONE - On-device Neural Engine: arm_compute::CLInstanceNormalizationLayerKernelEx Class Reference
arm_compute::CLInstanceNormalizationLayerKernelEx Class Reference
#include <CLInstanceNormalizationLayerKernelEx.h>
Public Member Functions
CLInstanceNormalizationLayerKernelEx ()
CLInstanceNormalizationLayerKernelEx (const CLInstanceNormalizationLayerKernelEx &)=delete
CLInstanceNormalizationLayerKernelEx & operator= (const CLInstanceNormalizationLayerKernelEx &)=delete
CLInstanceNormalizationLayerKernelEx (CLInstanceNormalizationLayerKernelEx &&)=default
CLInstanceNormalizationLayerKernelEx & operator= (CLInstanceNormalizationLayerKernelEx &&)=default
~CLInstanceNormalizationLayerKernelEx ()=default
void configure (ICLTensor *input, ICLTensor *output, ICLTensor *gamma=nullptr, ICLTensor *beta=nullptr, float epsilon=1e-12f)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *gamma=nullptr, const ITensorInfo *beta=nullptr, float epsilon=1e-12f)
Detailed Description
Interface for performing an instance normalization
Definition at line 51 of file CLInstanceNormalizationLayerKernelEx.h.
Constructor & Destructor Documentation
CLInstanceNormalizationLayerKernelEx() [1/3]
arm_compute::CLInstanceNormalizationLayerKernelEx::CLInstanceNormalizationLayerKernelEx ()
Constructor
Definition at line 100 of file CLInstanceNormalizationLayerKernelEx.cpp.
  : _input(nullptr), _output(nullptr), _gamma(nullptr), _beta(nullptr), _epsilon(1e-12),
    _run_in_place(false)
{
}
CLInstanceNormalizationLayerKernelEx() [2/3]
arm_compute::CLInstanceNormalizationLayerKernelEx::CLInstanceNormalizationLayerKernelEx (const CLInstanceNormalizationLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLInstanceNormalizationLayerKernelEx() [3/3]
arm_compute::CLInstanceNormalizationLayerKernelEx::CLInstanceNormalizationLayerKernelEx (CLInstanceNormalizationLayerKernelEx &&) default
Default Move Constructor.
~CLInstanceNormalizationLayerKernelEx()
arm_compute::CLInstanceNormalizationLayerKernelEx::~CLInstanceNormalizationLayerKernelEx () default
Default destructor
References validate().
Member Function Documentation
configure()
void arm_compute::CLInstanceNormalizationLayerKernelEx::configure (ICLTensor * input, ICLTensor * output, ICLTensor * gamma = nullptr, ICLTensor * beta = nullptr, float epsilon = 1e-12f)
Set the input and output tensors.
Parameters
[in,out] input Source tensor. Data types supported: F16/F32. Data layout supported: NCHW
[out] output Destination tensor. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale tensor applied to the normalized tensor. Defaults to nullptr
[in] beta (Optional) The offset tensor applied to the normalized tensor. Defaults to nullptr
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Definition at line 106 of file CLInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input);
  _input = input;
  _output = output == nullptr ? input : output;
  _gamma = gamma;
  _beta = beta;
  _epsilon = epsilon;
  _run_in_place = (output == nullptr) || (output == input);
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(_input->info(), _output->info(),
                                                gamma ? gamma->info() : nullptr,
                                                beta ? beta->info() : nullptr, epsilon));
  const unsigned int num_elems_processed_per_iteration = 16 / input->info()->element_size();
  CLBuildOptions build_opts;
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.add_option("-DVEC_SIZE=" +
                        support::cpp11::to_string(num_elems_processed_per_iteration));
  build_opts.add_option("-DDIM_X=" + support::cpp11::to_string(input->info()->dimension(0)));
  build_opts.add_option("-DDIM_Y=" + support::cpp11::to_string(input->info()->dimension(1)));
  build_opts.add_option("-DDIM_Z=" + support::cpp11::to_string(input->info()->dimension(2)));
  build_opts.add_option("-DEPSILON=" + float_to_string_with_full_precision(epsilon));
  build_opts.add_option_if(gamma, "-DGAMMA");
  build_opts.add_option_if(beta, "-DBETA");
  build_opts.add_option_if(_run_in_place, "-DIN_PLACE");
  build_opts.add_option_if(_input->info()->data_layout() == DataLayout::NHWC, "-DNHWC");
  // Create kernel
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("instance_normalization_ex", build_opts.options()));
  // Configure kernel window
  auto win_config = validate_and_configure_window(_input->info(), _output->info());
  ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
  ICLKernel::configure_internal(std::get<1>(win_config));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
operator=() [1/2]
CLInstanceNormalizationLayerKernelEx & arm_compute::CLInstanceNormalizationLayerKernelEx::operator= (CLInstanceNormalizationLayerKernelEx &&) default
Default move assignment operator
operator=() [2/2]
CLInstanceNormalizationLayerKernelEx & arm_compute::CLInstanceNormalizationLayerKernelEx::operator= (const CLInstanceNormalizationLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLInstanceNormalizationLayerKernelEx::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 158 of file CLInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  Window collapsed_window = window.collapse(window, Window::DimZ);
  // We will process the planes together
  if (_input->info()->data_layout() == DataLayout::NCHW)
  {
    collapsed_window.set(Window::DimX, Window::Dimension(0, 1, 1));
    collapsed_window.set(Window::DimY, Window::Dimension(0, 1, 1));
  }
  else
  {
    collapsed_window.set(Window::DimY, Window::Dimension(0, 1, 1));
    collapsed_window.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(3), 1));
  }
  Window vec_window;
  vec_window.set(Window::DimX, Window::Dimension(0, 0, 0));
  unsigned int idx = 0;
  add_4D_tensor_argument(idx, _input, collapsed_window);
  if (!_run_in_place)
  {
    add_4D_tensor_argument(idx, _output, collapsed_window);
  }
  if (_gamma)
  {
    add_1D_tensor_argument(idx, _gamma, vec_window);
  }
  if (_beta)
  {
    add_1D_tensor_argument(idx, _beta, vec_window);
  }
  enqueue(queue, *this, collapsed_window, lws_hint());
}
validate()
Status arm_compute::CLInstanceNormalizationLayerKernelEx::validate (const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * gamma = nullptr, const ITensorInfo * beta = nullptr, float epsilon = 1e-12f) static
Static function to check if given info will lead to a valid configuration of CLInstanceNormalizationLayerEx.
Parameters
[in] input Source tensor info. In case of output tensor = nullptr this tensor will store the result of the normalization. Data types supported: F16/F32. Data layout supported: NHWC, NCHW
[in] output Destination tensor info. Data types and data layouts supported: same as input.
[in] gamma (Optional) The scale tensor applied to the normalized tensor. Defaults to nullptr
[in] beta (Optional) The offset tensor applied to the normalized tensor. Defaults to nullptr
[in] epsilon (Optional) Lower bound value for the normalization. Defaults to 1e-12
Returns
a status
Definition at line 147 of file CLInstanceNormalizationLayerKernelEx.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output, gamma, beta, epsilon));
  ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(
    input->clone().get(), (output == nullptr ? input->clone().get() : output->clone().get()))));
  return Status{};
}
Referenced by arm_compute::CLInstanceNormalizationLayerEx::validate(), and ~CLInstanceNormalizationLayerKernelEx().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLInstanceNormalizationLayerKernelEx.h
compute/ARMComputeEx/src/core/CL/kernels/CLInstanceNormalizationLayerKernelEx.cpp