ONE - On-device Neural Engine: onert_micro::core::OMTensorContext< T, TensorData > Class Template Reference
onert_micro::core::OMTensorContext< T, TensorData > Class Template Reference
#include <OMRuntimeData.h>
Public Member Functions
OMTensorContext (TensorData &&data, const circle::Tensor *tensor)
TensorData & Data ()
const TensorData & Data () const
const circle::Tensor * Tensor () const noexcept
const OMRuntimeShape & Shape () const noexcept
const int32_t * Dims () const
size_t DimLength (size_t idx) const
bool HasZeroSizeDims () const
size_t DimsCount () const
size_t ElementsCount () const
bool IsScalar () const noexcept
Protected Attributes
TensorData _data
const circle::Tensor * _tensor
OMRuntimeShape _shape
Detailed Description
template<typename T, class TensorData>
class onert_micro::core::OMTensorContext< T, TensorData >
Definition at line 30 of file OMRuntimeData.h.
Constructor & Destructor Documentation
OMTensorContext()
template<typename T , class TensorData > onert_micro::core::OMTensorContext< T, TensorData >::OMTensorContext (TensorData && data, const circle::Tensor * tensor) inline
Definition at line 38 of file OMRuntimeData.h.
    : _data(std::move(data))
    , _tensor(tensor)
    , _shape(tensor)
  {
    assert(_tensor != nullptr);
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_tensor.
Member Function Documentation
Data() [1/2]
template<typename T , class TensorData > TensorData & onert_micro::core::OMTensorContext< T, TensorData >::Data () inline
Definition at line 47 of file OMRuntimeData.h.
  {
    return _data;
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_data.
Data() [2/2]
template<typename T , class TensorData > const TensorData & onert_micro::core::OMTensorContext< T, TensorData >::Data () const inline
Definition at line 52 of file OMRuntimeData.h.
  {
    return _data;
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_data.
DimLength()
template<typename T , class TensorData > size_t onert_micro::core::OMTensorContext< T, TensorData >::DimLength (size_t idx) const inline
Definition at line 72 of file OMRuntimeData.h.
  {
    auto result = _shape.dims(idx);
    assert(result >= 0);
    return static_cast<size_t>(result);
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::dims().
Dims()
template<typename T , class TensorData > const int32_t * onert_micro::core::OMTensorContext< T, TensorData >::Dims () const inline
Definition at line 67 of file OMRuntimeData.h.
  {
    return _shape.dimsData();
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::dimsData().
DimsCount()
template<typename T , class TensorData > size_t onert_micro::core::OMTensorContext< T, TensorData >::DimsCount () const inline
Definition at line 85 of file OMRuntimeData.h.
  {
    return _shape.dimensionsCount();
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::dimensionsCount().
ElementsCount()
template<typename T , class TensorData > size_t onert_micro::core::OMTensorContext< T, TensorData >::ElementsCount () const inline
Definition at line 90 of file OMRuntimeData.h.
  {
    return _shape.flatSize();
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::flatSize().
HasZeroSizeDims()
template<typename T , class TensorData > bool onert_micro::core::OMTensorContext< T, TensorData >::HasZeroSizeDims () const inline
Definition at line 80 of file OMRuntimeData.h.
  {
    return _shape.hasZeroSizeDims();
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::hasZeroSizeDims().
IsScalar()
template<typename T , class TensorData > bool onert_micro::core::OMTensorContext< T, TensorData >::IsScalar () const inline noexcept
Definition at line 95 of file OMRuntimeData.h.
  {
    return _shape.isScalar();
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape, and onert_micro::core::OMRuntimeShape::isScalar().
Shape()
template<typename T , class TensorData > const OMRuntimeShape & onert_micro::core::OMTensorContext< T, TensorData >::Shape () const inline noexcept
Definition at line 62 of file OMRuntimeData.h.
  {
    return _shape;
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_shape.
Tensor()
template<typename T , class TensorData > const circle::Tensor * onert_micro::core::OMTensorContext< T, TensorData >::Tensor () const inline noexcept
Definition at line 57 of file OMRuntimeData.h.
  {
    return _tensor;
  }
References onert_micro::core::OMTensorContext< T, TensorData >::_tensor.
Field Documentation
_data
template<typename T , class TensorData > TensorData onert_micro::core::OMTensorContext< T, TensorData >::_data protected
Definition at line 33 of file OMRuntimeData.h.
Referenced by onert_micro::core::OMTensorContext< T, TensorData >::Data(), and onert_micro::core::OMTensorContext< T, TensorData >::Data().
_shape
template<typename T , class TensorData > OMRuntimeShape onert_micro::core::OMTensorContext< T, TensorData >::_shape protected
Definition at line 35 of file OMRuntimeData.h.
Referenced by onert_micro::core::OMTensorContext< T, TensorData >::DimLength(), onert_micro::core::OMTensorContext< T, TensorData >::Dims(), onert_micro::core::OMTensorContext< T, TensorData >::DimsCount(), onert_micro::core::OMTensorContext< T, TensorData >::ElementsCount(), onert_micro::core::OMTensorContext< T, TensorData >::HasZeroSizeDims(), onert_micro::core::OMTensorContext< T, TensorData >::IsScalar(), and onert_micro::core::OMTensorContext< T, TensorData >::Shape().
_tensor
template<typename T , class TensorData > const circle::Tensor* onert_micro::core::OMTensorContext< T, TensorData >::_tensor protected
Definition at line 34 of file OMRuntimeData.h.
Referenced by onert_micro::core::OMTensorContext< T, TensorData >::OMTensorContext(), and onert_micro::core::OMTensorContext< T, TensorData >::Tensor().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMRuntimeData.h