ONE - On-device Neural Engine: onert::backend::cpu::ops::MatrixBandPartLayer Class Reference
onert::backend::cpu::ops::MatrixBandPartLayer Class Reference
#include <MatrixBandPartLayer.h>
Public Member Functions
MatrixBandPartLayer ()
void matrixBandPartFloat32 ()
void matrixBandPartQuant8 ()
void configure (const IPortableTensor *input, const IPortableTensor *num_lower_diag, const IPortableTensor *num_upper_diag, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file MatrixBandPartLayer.h.
Constructor & Destructor Documentation
MatrixBandPartLayer()
onert::backend::cpu::ops::MatrixBandPartLayer::MatrixBandPartLayer ()
Definition at line 32 of file MatrixBandPartLayer.cc.
  : _input(nullptr), _num_lower_diag(nullptr), _num_upper_diag(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::MatrixBandPartLayer::configure (const IPortableTensor * input, const IPortableTensor * num_lower_diag, const IPortableTensor * num_upper_diag, IPortableTensor * output)
Definition at line 56 of file MatrixBandPartLayer.cc.
{
  _input = input;
  _num_lower_diag = num_lower_diag;
  _num_upper_diag = num_upper_diag;
  _output = output;
}
matrixBandPartFloat32()
void onert::backend::cpu::ops::MatrixBandPartLayer::matrixBandPartFloat32 ()
Definition at line 38 of file MatrixBandPartLayer.cc.
{
  if (_num_lower_diag->data_type() == OperandType::INT64)
  {
    nnfw::cker::MatrixBandPart<int64_t>(
      *getBuffer<int64_t>(_num_lower_diag), *getBuffer<int64_t>(_num_upper_diag), getShape(_input),
      getBuffer<float>(_input), getShape(_output), getBuffer<float>(_output));
  }
  else
  {
    nnfw::cker::MatrixBandPart<int32_t>(
      *getBuffer<int32_t>(_num_lower_diag), *getBuffer<int32_t>(_num_upper_diag), getShape(_input),
      getBuffer<float>(_input), getShape(_output), getBuffer<float>(_output));
  }
}
References onert::backend::ITensor::data_type(), and onert::backend::cpu::ops::getShape().
Referenced by run().
matrixBandPartQuant8()
void onert::backend::cpu::ops::MatrixBandPartLayer::matrixBandPartQuant8 ()
Definition at line 54 of file MatrixBandPartLayer.cc.
{ throw std::runtime_error{"NYI"}; }
Referenced by run().
run()
void onert::backend::cpu::ops::MatrixBandPartLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 66 of file MatrixBandPartLayer.cc.
{
  if (_num_lower_diag->data_type() != _num_upper_diag->data_type())
  {
    throw std::runtime_error{"MatrixBandpart: num_lower and num_upper must have the same type"};
  }
  if (_input->data_type() == OperandType::FLOAT32)
  {
    matrixBandPartFloat32();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    matrixBandPartQuant8();
  }
  else
  {
    throw std::runtime_error{"MatrixBandpart: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), matrixBandPartFloat32(), and matrixBandPartQuant8().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/MatrixBandPartLayer.h
runtime/onert/backend/cpu/ops/MatrixBandPartLayer.cc