ONE - On-device Neural Engine: locop::FormattedGraphImpl< Formatter::LinearV1 > Class Reference
locop::FormattedGraphImpl< Formatter::LinearV1 > Class Reference final
#include <FormattedGraph.h>
Public Member Functions
FormattedGraphImpl (loco::Graph *graph)
void dump (std::ostream &os) const final
FormattedGraphImpl< Formatter::LinearV1 > & with (std::unique_ptr< NodeSummaryBuilderFactory > &&f)
Public Member Functions inherited from locop::FormattedGraph
virtual ~FormattedGraph ()=default
virtual void dump (std::ostream &os) const =0
Detailed Description
Definition at line 53 of file FormattedGraph.h.
Constructor & Destructor Documentation
FormattedGraphImpl()
locop::FormattedGraphImpl< Formatter::LinearV1 >::FormattedGraphImpl (loco::Graph * graph) inline
Definition at line 56 of file FormattedGraph.h.
: _graph{graph} {}
Member Function Documentation
dump()
void locop::FormattedGraphImpl< Formatter::LinearV1 >::dump (std::ostream & os) const final virtual
Implements locop::FormattedGraph.
Definition at line 214 of file FormattedGraph.cpp.
{
  struct SymbolTableImpl final : public SymbolTable
  {
    std::string lookup(const loco::Node *node) const final
    {
      if (node == nullptr)
      {
        return "(null)";
      }
      return _content.at(node);
    }
    std::map<const loco::Node *, std::string> _content;
  };
  SymbolTableImpl symbols;
  auto symbol = [&symbols](const loco::Node *node) { return symbols.lookup(node); };
  for (uint32_t n = 0; n < _graph->nodes()->size(); ++n)
  {
    symbols._content[_graph->nodes()->at(n)] = pp::fmt("%", n);
  }
  // Find the disjoint node clusters
  //
  // TODO Move this implementation into loco Algorithms.h
  std::map<loco::Node *, loco::Node *> parents;
  for (auto node : loco::all_nodes(_graph))
  {
    parents[node] = nullptr;
  }
  for (auto node : loco::all_nodes(_graph))
  {
    for (uint32_t n = 0; n < node->arity(); ++n)
    {
      if (auto arg = node->arg(n))
      {
        parents[arg] = node;
      }
    }
  }
  auto find = [&parents](loco::Node *node) {
    loco::Node *cur = node;
    while (parents.at(cur) != nullptr)
    {
      cur = parents.at(cur);
    }
    return cur;
  };
  std::set<loco::Node *> roots;
  for (auto node : loco::all_nodes(_graph))
  {
    roots.insert(find(node));
  }
  std::map<loco::Node *, std::set<loco::Node *>> clusters;
  // Create clusters
  for (auto root : roots)
  {
    clusters[root] = std::set<loco::Node *>{};
  }
  for (auto node : loco::all_nodes(_graph))
  {
    clusters.at(find(node)).insert(node);
  }
  std::unique_ptr<locop::NodeSummaryBuilder> node_summary_builder;
  if (_factory)
  {
    // Use User-defined NodeSummaryBuilder if NodeSummaryBuilderFactory is present
    node_summary_builder = _factory->create(&symbols);
  }
  else
  {
    // Use Built-in NodeSummaryBuilder otherwise
    node_summary_builder = std::make_unique<GenericNodeSummaryBuilder>(&symbols);
  }
  // Print Graph Input(s)
  for (uint32_t n = 0; n < _graph->inputs()->size(); ++n)
  {
    auto input = _graph->inputs()->at(n);
    std::string name = input->name();
    std::string shape = "?";
    if (input->shape() != nullptr)
    {
      shape = pp::fmt(formatted_tensor_shape(input->shape()));
    }
    // TODO Print dtype
    os << pp::fmt("In #", n, " { name: ", name, ", shape: ", shape, " }") << std::endl;
  }
  // Print Graph Output(s)
  for (uint32_t n = 0; n < _graph->outputs()->size(); ++n)
  {
    auto output = _graph->outputs()->at(n);
    std::string name = output->name();
    std::string shape = "?";
    if (output->shape() != nullptr)
    {
      shape = pp::fmt(formatted_tensor_shape(output->shape()));
    }
    // TODO Print dtype
    os << pp::fmt("Out #", n, " { name: ", name, ", shape: ", shape, " }") << std::endl;
  }
  if (_graph->inputs()->size() + _graph->outputs()->size() != 0)
  {
    os << std::endl;
  }
  for (auto it = clusters.begin(); it != clusters.end(); ++it)
  {
    std::vector<loco::Node *> cluster_outputs;
    for (auto node : it->second)
    {
      // NOTE This is inefficient but anyway working :)
      if (loco::succs(node).empty())
      {
        cluster_outputs.emplace_back(node);
      }
    }
    for (auto node : loco::postorder_traversal(cluster_outputs))
    {
      locop::NodeSummary node_summary;
      // Build a node summary
      if (!node_summary_builder->build(node, node_summary))
      {
        throw std::runtime_error{"Fail to build a node summary"};
      }
      for (uint32_t n = 0; n < node_summary.comments().count(); ++n)
      {
        os << "; " << node_summary.comments().at(n) << std::endl;
      }
      os << symbol(node);
      if (loco::shape_known(node))
      {
        auto node_shape = loco::shape_get(node);
        os << " : " << str(node_shape.domain());
        os << "<";
        os << str(node_shape);
        os << ", ";
        // Show DataType
        os << (loco::dtype_known(node) ? str(loco::dtype_get(node)) : std::string{"?"});
        os << ">";
      }
      os << " = " << node_summary << std::endl;
    }
    os << std::endl;
  }
}
References loco::all_nodes(), locop::NodeDesc::Comments::at(), locop::NodeDesc::comments(), loco::NodeShape::domain(), loco::dtype_get(), loco::dtype_known(), loco::postorder_traversal(), loco::shape_get(), loco::shape_known(), and loco::succs().
with()
FormattedGraphImpl< Formatter::LinearV1 > & locop::FormattedGraphImpl< Formatter::LinearV1 >::with (std::unique_ptr< NodeSummaryBuilderFactory > && f) inline
Definition at line 62 of file FormattedGraph.h.
  {
    _factory = std::move(f);
    return (*this);
  }
The documentation for this class was generated from the following files:
compiler/locop/include/locop/FormattedGraph.h
compiler/locop/src/FormattedGraph.cpp