ONE - On-device Neural Engine: moco::Padding2DInference Class Reference
moco::Padding2DInference Class Reference final
#include <TFShapeInferenceHelper.h>
Public Member Functions
loco::Padding2D operator() (const PlaneShape &in)
Public Member Functions inherited from moco::PlaneInference
PlaneShape operator() (const PlaneShape &in)
void padding (const TFPadding &value)
void window (const loco::Window< 2 > value)
void stride (const loco::Stride< 2 > value)
Additional Inherited Members
Protected Member Functions inherited from moco::PlaneInference
void fill (Parameters &p, const PlaneShape &in)
PlaneShape infer (const Parameters &p, const PlaneShape &)
Detailed Description
Definition at line 177 of file TFShapeInferenceHelper.h.
Member Function Documentation
operator()()
loco::Padding2D moco::Padding2DInference::operator() (const PlaneShape & in) inline
Definition at line 180 of file TFShapeInferenceHelper.h.
  {
    Parameters p;
    fill(p, in);
    auto output = infer(p, in);
    int64_t i_height = (int64_t)(output.height.value() - 1) * (int64_t)p.stride.height.value() +
                       (int64_t)p.effective_window.height.value() - (int64_t)p.input.height.value();
    int64_t i_width = (int64_t)(output.width.value() - 1) * (int64_t)p.stride.width.value() +
                      (int64_t)p.effective_window.width.value() - (int64_t)p.input.width.value();
    uint32_t pad_height = i_height >= 0 ? (uint32_t)i_height : 0U;
    uint32_t pad_width = i_width >= 0 ? (uint32_t)i_width : 0U;
    loco::Padding2D padding2d;
    padding2d.top(pad_height / 2);
    padding2d.bottom(pad_height - padding2d.top());
    padding2d.left(pad_width / 2);
    padding2d.right(pad_width - padding2d.left());
    return padding2d;
  }
References loco::Padding2D::bottom(), moco::PlaneInference::Parameters::effective_window, moco::PlaneInference::fill(), moco::PlaneShape::height, moco::PlaneInference::infer(), moco::PlaneInference::Parameters::input, loco::Padding2D::left(), loco::Padding2D::right(), moco::PlaneInference::Parameters::stride, loco::Padding2D::top(), loco::Dimension::value(), and moco::PlaneShape::width.
The documentation for this class was generated from the following file:
compiler/moco/support/include/moco/Support/TFShapeInferenceHelper.h