ONE - On-device Neural Engine: loco::FeatureIndex Class Reference
loco::FeatureIndex Class Reference final
Feature Index.
#include <FeatureIndex.h>
Public Member Functions
FeatureIndex ()=default
const uint32_t & batch (void) const
uint32_t & batch (void)
const uint32_t & channel (void) const
uint32_t & channel (void)
const uint32_t & row (void) const
uint32_t & row (void)
const uint32_t & column (void) const
uint32_t & column (void)
Detailed Description
Feature Index.
Feature Index indicates an "element" in a given feature map.
Let us assume that there is a feature map F and S denotes its shape (of FeatureShape type).
Then, any valid feature index I satisfies the following invariants:
0 <= I.batch() < S.count()
0 <= I.channel() < S.depth()
0 <= I.row() < S.height()
0 <= I.column() < S.width()
Definition at line 38 of file FeatureIndex.h.
Constructor & Destructor Documentation
FeatureIndex()
loco::FeatureIndex::FeatureIndex () default
Member Function Documentation
batch() [1/2]
uint32_t & loco::FeatureIndex::batch (void) inline
Definition at line 45 of file FeatureIndex.h.
{ return _batch; }
batch() [2/2]
const uint32_t & loco::FeatureIndex::batch (void) const inline
Definition at line 44 of file FeatureIndex.h.
{ return _batch; }
Referenced by loco::PermutingEncoder< Domain::Feature >::value(), and loco::PermutingDecoder< Domain::Feature >::value().
channel() [1/2]
uint32_t & loco::FeatureIndex::channel (void) inline
Definition at line 48 of file FeatureIndex.h.
{ return _channel; }
channel() [2/2]
const uint32_t & loco::FeatureIndex::channel (void) const inline
Definition at line 47 of file FeatureIndex.h.
{ return _channel; }
Referenced by loco::PermutingEncoder< Domain::Feature >::value(), and loco::PermutingDecoder< Domain::Feature >::value().
column() [1/2]
uint32_t & loco::FeatureIndex::column (void) inline
Definition at line 54 of file FeatureIndex.h.
{ return _column; }
column() [2/2]
const uint32_t & loco::FeatureIndex::column (void) const inline
Definition at line 53 of file FeatureIndex.h.
{ return _column; }
Referenced by loco::PermutingEncoder< Domain::Feature >::value(), and loco::PermutingDecoder< Domain::Feature >::value().
row() [1/2]
uint32_t & loco::FeatureIndex::row (void) inline
Definition at line 51 of file FeatureIndex.h.
{ return _row; }
row() [2/2]
const uint32_t & loco::FeatureIndex::row (void) const inline
Definition at line 50 of file FeatureIndex.h.
{ return _row; }
Referenced by loco::PermutingEncoder< Domain::Feature >::value(), and loco::PermutingDecoder< Domain::Feature >::value().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/FeatureIndex.h