ONE - On-device Neural Engine: onert::backend::cpu::ops::BatchMatMulLayer Class Reference
onert::backend::cpu::ops::BatchMatMulLayer Class Reference
#include <BatchMatMulLayer.h>
Public Member Functions
BatchMatMulLayer ()
~BatchMatMulLayer ()
void batchMatMulFloat32 ()
void configure (const IPortableTensor *lhs, const IPortableTensor *rhs, bool adj_x, bool adj_y, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 42 of file BatchMatMulLayer.h.
Constructor & Destructor Documentation
BatchMatMulLayer()
onert::backend::cpu::ops::BatchMatMulLayer::BatchMatMulLayer ()
Definition at line 30 of file BatchMatMulLayer.cc.
  : _lhs(nullptr), _rhs(nullptr), _output(nullptr), _adj_x(false), _adj_y(false),
    _kernel(new nnfw::cker::BatchMatMul())
{
  // DO NOTHING
}
~BatchMatMulLayer()
onert::backend::cpu::ops::BatchMatMulLayer::~BatchMatMulLayer () default
Member Function Documentation
batchMatMulFloat32()
void onert::backend::cpu::ops::BatchMatMulLayer::batchMatMulFloat32 ()
Definition at line 39 of file BatchMatMulLayer.cc.
{
  nnfw::cker::BatchMatMul &batchmatmul_kernel = *_kernel;
  nnfw::cker::Shape lhs_shape = getShape(_lhs);
  nnfw::cker::Shape rhs_shape = getShape(_rhs);
  nnfw::cker::Shape output_shape = getShape(_output);
  // TODO implement for constant input
  batchmatmul_kernel.prepare(lhs_shape, rhs_shape, _adj_x, _adj_y);
  batchmatmul_kernel(lhs_shape, getBuffer<float>(_lhs), rhs_shape, getBuffer<float>(_rhs), _adj_x,
                     _adj_y, output_shape, getBuffer<float>(_output));
}
References onert::backend::cpu::ops::getShape(), and nnfw::cker::BatchMatMul::prepare().
Referenced by run().
configure()
void onert::backend::cpu::ops::BatchMatMulLayer::configure (const IPortableTensor * lhs, const IPortableTensor * rhs, bool adj_x, bool adj_y, IPortableTensor * output)
Definition at line 53 of file BatchMatMulLayer.cc.
{
  assert(lhs != nullptr);
  assert(rhs != nullptr);
  assert(output != nullptr);
  _lhs = lhs;
  _rhs = rhs;
  _adj_x = adj_x;
  _adj_y = adj_y;
  _output = output;
}
run()
void onert::backend::cpu::ops::BatchMatMulLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 67 of file BatchMatMulLayer.cc.
{
  if ((_lhs->data_type() == OperandType::FLOAT32) && (_rhs->data_type() == OperandType::FLOAT32))
  {
    batchMatMulFloat32();
  }
  else
  {
    throw std::runtime_error{"BatchMatMul: unsupported data type"};
  }
}
References batchMatMulFloat32(), and onert::backend::ITensor::data_type().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/BatchMatMulLayer.h
runtime/onert/backend/cpu/ops/BatchMatMulLayer.cc