ONE - On-device Neural Engine: onert::backend::acl_cl::KernelGenerator Class Reference
onert::backend::acl_cl::KernelGenerator Class Reference
#include <KernelGenerator.h>
Public Member Functions
KernelGenerator (const ir::Graph &graph, const std::shared_ptr< TensorBuilder > &tensor_builder, const std::shared_ptr< acl_common::AclTensorRegistry< TensorManager > > &_tensor_reg)
std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind) override
Public Member Functions inherited from onert::backend::basic::KernelGeneratorBase
virtual ~KernelGeneratorBase ()=default
KernelGeneratorBase (const ir::Graph &graph)
virtual std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind)=0
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Protected Member Functions inherited from onert::backend::basic::KernelGeneratorBase
std::unique_ptr< exec::IFunction > releaseFunction ()
Protected Attributes inherited from onert::backend::basic::KernelGeneratorBase
const ir::Graph & _graph
std::unique_ptr< exec::IFunction > _return_fn
Detailed Description
Definition at line 33 of file KernelGenerator.h.
Constructor & Destructor Documentation
KernelGenerator()
onert::backend::acl_cl::KernelGenerator::KernelGenerator (const ir::Graph & graph, const std::shared_ptr< TensorBuilder > & tensor_builder, const std::shared_ptr< acl_common::AclTensorRegistry< TensorManager > > & _tensor_reg)
Definition at line 47 of file KernelGenerator.cc.
  : basic::KernelGeneratorBase{graph}, _ctx(graph.operands()),
    _operations_ctx(graph.operations()), _current_layout{graph.layout()},
    _tensor_builder(tensor_builder), _tensor_reg(tensor_reg)
{
  // DO NOTHING
}
Member Function Documentation
generate()
std::unique_ptr< exec::FunctionSequence > onert::backend::acl_cl::KernelGenerator::generate (ir::OperationIndex ind) override virtual
Implements onert::backend::basic::KernelGeneratorBase.
Definition at line 57 of file KernelGenerator.cc.
{
  auto ret = std::make_unique<exec::FunctionSequence>();
  ret->enableDynamicShapeInferer(false);
  const auto &op = _graph.operations().at(ind);
  op.accept(*this);
  ret->append(releaseFunction());
  return ret;
}
References onert::backend::basic::KernelGeneratorBase::_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::Graph::operations(), and onert::backend::basic::KernelGeneratorBase::releaseFunction().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/KernelGenerator.h
runtime/onert/backend/acl_cl/KernelGenerator.cc