ONE - On-device Neural Engine: nnc::ArtifactBlock Class Reference
nnc::ArtifactBlock Class Reference
Represents a block of instructions.
#include <ArtifactModel.h>
Public Member Functions
bool isBlock () const override
If this entity represents something containing a block of instructions.
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
void addStatement (const std::shared_ptr< ArtifactEntity > &statement)
const std::list< std::shared_ptr< ArtifactEntity > > & getStatements () const
std::shared_ptr< ArtifactVariable > var (const std::string &type_name, const std::string &var_name, const std::list< std::shared_ptr< ArtifactExpr > > &dimensions={}, const std::list< std::shared_ptr< ArtifactExpr > > &initializers={})
Creates a new variable and place it to the block.
std::shared_ptr< ArtifactFunctionCall > call (const std::string &func_name, const std::list< std::shared_ptr< ArtifactExpr > > &param_list, std::shared_ptr< ArtifactExpr > call_on=nullptr, ArtifactCallType call_type=ArtifactCallType::obj)
Creates a function call.
std::shared_ptr< ArtifactRet > ret (std::shared_ptr< ArtifactExpr > expr)
Creates a return from function statement.
std::shared_ptr< ArtifactBreak > brk ()
Creates a break from a loop instruction.
std::shared_ptr< ArtifactCont > cont ()
Creates a continue in a loop instruction.
std::shared_ptr< ArtifactForLoop > forLoop (std::shared_ptr< ArtifactVariable > init=nullptr, std::shared_ptr< ArtifactExpr > cond=nullptr, std::shared_ptr< ArtifactExpr > iter=nullptr)
Creates a for loop instruction.
std::shared_ptr< ArtifactIf > ifCond (std::shared_ptr< ArtifactExpr > cond)
Creates an 'if' blocks.
std::shared_ptr< ArtifactUnaryExpr > un (ArtifactUnOp op, std::shared_ptr< ArtifactExpr > expr)
Creates an unary operation expression.
std::shared_ptr< ArtifactBinaryExpr > bin (ArtifactBinOp op, std::shared_ptr< ArtifactExpr > left, std::shared_ptr< ArtifactExpr > right)
Creates a binary operation expression.
std::shared_ptr< ArtifactUnaryExpr > heapNew (std::shared_ptr< ArtifactExpr > expr)
Creates a heap new operation expression.
std::shared_ptr< ArtifactUnaryExpr > heapFree (std::shared_ptr< ArtifactExpr > expr)
Creates a heap free operation expression.
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents a block of instructions.
Definition at line 352 of file ArtifactModel.h.
Member Function Documentation
accept()
void nnc::ArtifactBlock::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Definition at line 357 of file ArtifactModel.h.
{ g->visit(this); }
Referenced by TEST(), and nnc::ArtifactGeneratorCppCode::visit().
addStatement()
void nnc::ArtifactBlock::addStatement (const std::shared_ptr< ArtifactEntity > & statement) inline
Definition at line 359 of file ArtifactModel.h.
  {
    _statements.push_back(statement);
  }
Referenced by TEST().
bin()
shared_ptr< ArtifactBinaryExpr > nnc::ArtifactBlock::bin (ArtifactBinOp op, std::shared_ptr< ArtifactExpr > left, std::shared_ptr< ArtifactExpr > right)
Creates a binary operation expression.
Parameters
op
left
right
Returns
Definition at line 97 of file ArtifactModel.cpp.
{
  auto bin = make_shared<ArtifactBinaryExpr>(op, left, right);
  _statements.push_back(bin);
  return bin;
}
References bin().
Referenced by bin().
brk()
shared_ptr< ArtifactBreak > nnc::ArtifactBlock::brk ()
Creates a break from a loop instruction.
Returns
Definition at line 60 of file ArtifactModel.cpp.
{
  auto brk = make_shared<ArtifactBreak>();
  _statements.push_back(brk);
  return brk;
}
References brk().
Referenced by brk().
call()
shared_ptr< ArtifactFunctionCall > nnc::ArtifactBlock::call (const std::string & func_name, const std::list< std::shared_ptr< ArtifactExpr > > & param_list, std::shared_ptr< ArtifactExpr > call_on = nullptr, ArtifactCallType call_type = ArtifactCallType::obj)
Creates a function call.
Parameters
func_name - the function name.
param_list - the parameters which are used for the call.
call_on - optional object on which the function is called (if it is a member function).
call_type - (for member functions only) call through: '.', '->', or '::'.
Returns
Definition at line 45 of file ArtifactModel.cpp.
{
  auto func_call = make_shared<ArtifactFunctionCall>(func_name, param_list, call_on, call_type);
  _statements.push_back(func_call);
  return func_call;
}
Referenced by nnc::AclCppOpGenerator::generate(), and nnc::AclCppOpGenerator::visit().
cont()
shared_ptr< ArtifactCont > nnc::ArtifactBlock::cont ()
Creates a continue in a loop instruction.
Returns
Definition at line 67 of file ArtifactModel.cpp.
{
  auto cont = make_shared<ArtifactCont>();
  _statements.push_back(cont);
  return cont;
}
References cont().
Referenced by cont().
forLoop()
shared_ptr< ArtifactForLoop > nnc::ArtifactBlock::forLoop (std::shared_ptr< ArtifactVariable > init = nullptr, std::shared_ptr< ArtifactExpr > cond = nullptr, std::shared_ptr< ArtifactExpr > iter = nullptr)
Creates a for loop instruction.
Parameters
init - initialize for loop.
cond - condition to check for stay looping.
iter - change when transiting to the next iteration.
Returns
Definition at line 74 of file ArtifactModel.cpp.
{
  auto loop = make_shared<ArtifactForLoop>(init, cond, iter);
  _statements.push_back(loop);
  return loop;
}
getStatements()
const std::list< std::shared_ptr< ArtifactEntity > > & nnc::ArtifactBlock::getStatements () const inline
Definition at line 364 of file ArtifactModel.h.
{ return _statements; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
heapFree()
shared_ptr< ArtifactUnaryExpr > nnc::ArtifactBlock::heapFree (std::shared_ptr< ArtifactExpr > expr)
Creates a heap free operation expression.
Parameters
expr
Returns
Definition at line 112 of file ArtifactModel.cpp.
{
  auto heap_del = make_shared<ArtifactUnaryExpr>(ArtifactUnOp::heapFree, expr);
  _statements.push_back(heap_del);
  return heap_del;
}
References nnc::heapFree.
heapNew()
shared_ptr< ArtifactUnaryExpr > nnc::ArtifactBlock::heapNew (std::shared_ptr< ArtifactExpr > expr)
Creates a heap new operation expression.
Parameters
expr
Returns
Definition at line 105 of file ArtifactModel.cpp.
{
  auto heap_new = make_shared<ArtifactUnaryExpr>(ArtifactUnOp::heapNew, expr);
  _statements.push_back(heap_new);
  return heap_new;
}
References nnc::heapNew.
ifCond()
shared_ptr< ArtifactIf > nnc::ArtifactBlock::ifCond (std::shared_ptr< ArtifactExpr > cond)
Creates an 'if' blocks.
Parameters
cond - condition expression
Returns
Definition at line 83 of file ArtifactModel.cpp.
{
  auto ifb = make_shared<ArtifactIf>(cond);
  _statements.push_back(ifb);
  return ifb;
}
Referenced by nnc::AclCppOpGenerator::generate().
isBlock()
bool nnc::ArtifactBlock::isBlock () const inline override virtual
If this entity represents something containing a block of instructions.
Reimplemented from nnc::ArtifactEntity.
Definition at line 355 of file ArtifactModel.h.
{ return true; }
ret()
shared_ptr< ArtifactRet > nnc::ArtifactBlock::ret (std::shared_ptr< ArtifactExpr > expr)
Creates a return from function statement.
Parameters
expr - value to return in generated code.
Returns
Definition at line 53 of file ArtifactModel.cpp.
{
  auto ret = make_shared<ArtifactRet>(expr);
  _statements.push_back(ret);
  return ret;
}
References ret().
Referenced by ret().
un()
shared_ptr< ArtifactUnaryExpr > nnc::ArtifactBlock::un (ArtifactUnOp op, std::shared_ptr< ArtifactExpr > expr)
Creates an unary operation expression.
Parameters
op
expr
Returns
Definition at line 90 of file ArtifactModel.cpp.
{
  auto un = make_shared<ArtifactUnaryExpr>(op, expr);
  _statements.push_back(un);
  return un;
}
References un().
Referenced by un().
var()
shared_ptr< ArtifactVariable > nnc::ArtifactBlock::var (const std::string & type_name, const std::string & var_name, const std::list< std::shared_ptr< ArtifactExpr > > & dimensions = {}, const std::list< std::shared_ptr< ArtifactExpr > > & initializers = {})
Creates a new variable and place it to the block.
Parameters
type_name - the variable type name.
var_name - the varibale name.
dimensions - optional dimensions, if the declared variable is an array.
initializers - optional arguments of the object constructor.
Returns
- the newly created variable.
Definition at line 35 of file ArtifactModel.cpp.
{
  auto var = make_shared<ArtifactVariable>(type_name, var_name, dimensions, initializers);
  _statements.push_back(var);
  return var;
}
References var().
Referenced by nnc::AclCppOpGenerator::genPadStrideInfo(), nnc::AclCppOpGenerator::genVectorInitializedVar(), var(), and nnc::AclCppOpGenerator::visit().
The documentation for this class was generated from the following files:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h
compiler/nnc/backends/acl_soft_backend/ArtifactModel.cpp