ONE - On-device Neural Engine: nnkit::support::onnx::TensorSet Class Reference
nnkit::support::onnx::TensorSet Class Reference final
#include <TensorSet.h>
Public Member Functions
TensorSet (Allocator *allocator, size_t nums)
~TensorSet (void)
void set (size_t index, const std::string &name, ONNXTensorElementDataType type, const std::vector< size_t > &dims)
size_t size (void)
const char * name (size_t index)
const std::vector< std::string > & names (void)
ONNXTensorElementDataType type (size_t index)
const std::vector< size_t > & dim (size_t index)
const OrtValue * tensor (size_t index)
const std::vector< OrtValue * > & tensors (void)
OrtValue * mutable_tensor (size_t index)
std::vector< OrtValue * > mutable_tensors (void)
Detailed Description
Definition at line 36 of file TensorSet.h.
Constructor & Destructor Documentation
TensorSet()
nnkit::support::onnx::TensorSet::TensorSet (Allocator * allocator, size_t nums) inline
Definition at line 39 of file TensorSet.h.
    : _allocator(allocator), _names(nums), _types(nums), _dims(nums), _tensors(nums, nullptr)
  {
    // DO NOTHING
  }
~TensorSet()
nnkit::support::onnx::TensorSet::~TensorSet (void) inline
Definition at line 45 of file TensorSet.h.
  {
    for (auto it : _tensors)
    {
      OrtReleaseValue(it);
    }
  }
Member Function Documentation
dim()
const std::vector< size_t > & nnkit::support::onnx::TensorSet::dim (size_t index) inline
Definition at line 76 of file TensorSet.h.
{ return _dims[index]; }
Referenced by nnkit::support::onnx::TensorContext::shape().
mutable_tensor()
OrtValue * nnkit::support::onnx::TensorSet::mutable_tensor (size_t index) inline
Definition at line 81 of file TensorSet.h.
{ return _tensors[index]; }
Referenced by nnkit::support::onnx::TensorContext::getConstFloatTensor(), and nnkit::support::onnx::TensorContext::getMutableFloatTensor().
mutable_tensors()
std::vector< OrtValue * > nnkit::support::onnx::TensorSet::mutable_tensors (void) inline
Definition at line 82 of file TensorSet.h.
{ return _tensors; }
name()
const char * nnkit::support::onnx::TensorSet::name (size_t index) inline
Definition at line 71 of file TensorSet.h.
{ return _names[index].c_str(); }
Referenced by nnkit::support::onnx::TensorContext::name(), and set().
names()
const std::vector< std::string > & nnkit::support::onnx::TensorSet::names (void) inline
Definition at line 72 of file TensorSet.h.
{ return _names; }
set()
void nnkit::support::onnx::TensorSet::set (size_t index, const std::string & name, ONNXTensorElementDataType type, const std::vector< size_t > & dims) inline
Definition at line 53 of file TensorSet.h.
  {
    _names[index] = name;
    _types[index] = type;
    _dims[index] = dims;
    Status status;
    status =
      OrtCreateTensorAsOrtValue(_allocator, dims.data(), dims.size(), type, &_tensors[index]);
    status.throwOnError();
    assert(OrtIsTensor(_tensors[index]));
  }
References name(), nnkit::support::onnx::Status::throwOnError(), and type().
size()
size_t nnkit::support::onnx::TensorSet::size (void) inline
Definition at line 69 of file TensorSet.h.
{ return _names.size(); }
Referenced by nnkit::support::onnx::TensorContext::size().
tensor()
const OrtValue * nnkit::support::onnx::TensorSet::tensor (size_t index) inline
Definition at line 78 of file TensorSet.h.
{ return _tensors[index]; }
tensors()
const std::vector< OrtValue * > & nnkit::support::onnx::TensorSet::tensors (void) inline
Definition at line 79 of file TensorSet.h.
{ return _tensors; }
type()
ONNXTensorElementDataType nnkit::support::onnx::TensorSet::type (size_t index) inline
Definition at line 74 of file TensorSet.h.
{ return _types[index]; }
Referenced by OptionBuilder.OptionBuilder::build(), nnkit::support::onnx::TensorContext::getConstFloatTensor(), nnkit::support::onnx::TensorContext::getMutableFloatTensor(), nnkit::support::onnx::TensorContext::isFloatTensor(), and set().
The documentation for this class was generated from the following file:
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/TensorSet.h