ONE - On-device Neural Engine: onert::util::Index< T, DummyTag > Class Template Reference
onert::util::Index< T, DummyTag > Class Template Reference
A wrapper class for unsigned integral Index NOTE : Max value of the underlying type is used as the invalid value.
#include <Index.h>
Public Member Functions
Index (void)
Construct a new Index object.
Index (const T o)
Construct a new Index object with a value in the underlying type.
Index (const Index &o)=default
Copy Constructor.
Index & operator= (const T o)
Assign a value in the underlying time.
Index & operator= (const Index &o)=default
Copy assignment operator.
bool operator== (T o) const
Equality operator.
bool operator== (const Index &o) const
Equality operator.
bool operator!= (T o) const
Inquality operator.
bool operator!= (const Index &o) const
Inquality operator.
Index operator++ (int)
Post increment operator.
bool valid () const
Check whether the value is valid or not.
bool undefined () const
Check whether the value is undefined.
T value () const
Return underlying value.
Static Public Member Functions
static T max ()
Return max index value.
Detailed Description
template<typename T, typename DummyTag>
class onert::util::Index< T, DummyTag >
A wrapper class for unsigned integral Index NOTE : Max value of the underlying type is used as the invalid value.
Template Parameters
T Underlying type. Must be unsigned integral type otherwise its behavior is undefined.
DummyTag Dummy type to distinguish types with a same underlying type. Using an opaque type is recommended.
Definition at line 38 of file Index.h.
Constructor & Destructor Documentation
Index() [1/3]
template<typename T , typename DummyTag > onert::util::Index< T, DummyTag >::Index (void) inline explicit
Construct a new Index object.
Definition at line 47 of file Index.h.
: _index{UNDEFINED} {}
Index() [2/3]
template<typename T , typename DummyTag > onert::util::Index< T, DummyTag >::Index (const T o) inline explicit
Construct a new Index object with a value in the underlying type.
Parameters
o Value in the underlying type
Definition at line 53 of file Index.h.
: _index{o} {}
Index() [3/3]
template<typename T , typename DummyTag > onert::util::Index< T, DummyTag >::Index (const Index< T, DummyTag > & o) default
Copy Constructor.
Parameters
o Object to be copied
Member Function Documentation
max()
template<typename T , typename DummyTag > static T onert::util::Index< T, DummyTag >::max () inline static
Return max index value.
Returns
Maximum valid index value
Definition at line 146 of file Index.h.
{ return UNDEFINED - 1; }
operator!=() [1/2]
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::operator!= (const Index< T, DummyTag > & o) const inline
Inquality operator.
Parameters
o The other object to compare
Returns
true if underlying value is different, false otherwise
Definition at line 108 of file Index.h.
{ return !(*this == o); }
operator!=() [2/2]
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::operator!= (T o) const inline
Inquality operator.
Parameters
o The other value in the underlying type to compare
Returns
true if underlying value is different, false otherwise
Definition at line 101 of file Index.h.
{ return !(*this == o); }
operator++()
template<typename T , typename DummyTag > Index onert::util::Index< T, DummyTag >::operator++ (int) inline
Post increment operator.
Returns
Index Index before increment
Definition at line 115 of file Index.h.
  {
    Index temp = *this;
    _index++;
    return temp;
  }
operator=() [1/2]
template<typename T , typename DummyTag > Index & onert::util::Index< T, DummyTag >::operator= (const Index< T, DummyTag > & o) default
Copy assignment operator.
Parameters
o Object to be copied
Returns
Index& Reference of this pointer
operator=() [2/2]
template<typename T , typename DummyTag > Index & onert::util::Index< T, DummyTag >::operator= (const T o) inline
Assign a value in the underlying time.
Parameters
o Value in the underlying type
Returns
Index& Reference of this pointer
Definition at line 67 of file Index.h.
  {
    _index = o;
    return *this;
  }
operator==() [1/2]
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::operator== (const Index< T, DummyTag > & o) const inline
Equality operator.
Parameters
o The other object to compare
Returns
true if underlying value is the same, false otherwise
Definition at line 94 of file Index.h.
{ return _index == o._index; }
operator==() [2/2]
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::operator== (T o) const inline
Equality operator.
Parameters
o The other value in the underlying type to compare
Returns
true if underlying value is the same, false otherwise
Definition at line 87 of file Index.h.
{ return _index == o; }
undefined()
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::undefined () const inline
Check whether the value is undefined.
Returns
true if undefined, false otherwise
Definition at line 133 of file Index.h.
{ return _index == UNDEFINED; }
valid()
template<typename T , typename DummyTag > bool onert::util::Index< T, DummyTag >::valid () const inline
Check whether the value is valid or not.
Returns
true if valid, false otherwise
Definition at line 127 of file Index.h.
{ return _index != UNDEFINED; }
Referenced by onert::backend::cl_common::createLifetimeMap().
value()
template<typename T , typename DummyTag > T onert::util::Index< T, DummyTag >::value () const inline
Return underlying value.
Returns
T Underlying value
Definition at line 139 of file Index.h.
{ return _index; }
Referenced by onert::ir::OperandIndexSequence::at(), onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), onert::exec::Executors::execute(), onert::exec::Execution::getOutputShape(), onert::exec::TracingObserver::handleJobBegin(), onert::exec::TracingObserver::handleJobEnd(), onert::exec::TracingObserver::handleSubgraphBegin(), onert::exec::TracingObserver::handleSubgraphEnd(), onert::backend::basic::FirstFitPlanner::release(), and onert::ir::OperationDumper::visit().
The documentation for this class was generated from the following file:
runtime/onert/core/include/util/Index.h