ONE - On-device Neural Engine: arm_compute::CLHashtableLookupKernel Class Reference
arm_compute::CLHashtableLookupKernel Class Reference
Class to perform HashtableLookup operation with opencl kernel.
#include <CLHashtableLookupKernel.h>
Public Member Functions
CLHashtableLookupKernel ()
Construct a CLHashtableLookupKernel object.
CLHashtableLookupKernel (const CLHashtableLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHashtableLookupKernel & operator= (const CLHashtableLookupKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHashtableLookupKernel (CLHashtableLookupKernel &&)=default
Construct a CLHashtableLookupKernel object by using default move constructor.
CLHashtableLookupKernel & operator= (CLHashtableLookupKernel &&)=default
Move assignment operator.
~CLHashtableLookupKernel ()=default
Destruct this object.
void configure (const ICLTensor *lookups, const ICLTensor *keys, const ICLTensor *input, ICLTensor *output, ICLTensor *hits)
Set the input and output of the kernel.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Static Public Member Functions
static Status validate (const ITensorInfo *lookups, const ITensorInfo *keys, const ITensorInfo *input, const ITensorInfo *output, const ITensorInfo *hits)
Static function to check if given info will lead to a valid configuration of CLHashtableLookupKernel.
Detailed Description
Class to perform HashtableLookup operation with opencl kernel.
Definition at line 60 of file CLHashtableLookupKernel.h.
Constructor & Destructor Documentation
CLHashtableLookupKernel() [1/3]
CLHashtableLookupKernel::CLHashtableLookupKernel ()
Construct a CLHashtableLookupKernel object.
Definition at line 71 of file CLHashtableLookupKernel.cpp.
{
  // DO NOTHING
}
CLHashtableLookupKernel() [2/3]
arm_compute::CLHashtableLookupKernel::CLHashtableLookupKernel (const CLHashtableLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLHashtableLookupKernel() [3/3]
arm_compute::CLHashtableLookupKernel::CLHashtableLookupKernel (CLHashtableLookupKernel &&) default
Construct a CLHashtableLookupKernel object by using default move constructor.
Parameters
[in] CLHashtableLookupKernel object to move
~CLHashtableLookupKernel()
arm_compute::CLHashtableLookupKernel::~CLHashtableLookupKernel () default
Destruct this object.
References validate().
Member Function Documentation
configure()
void CLHashtableLookupKernel::configure (const ICLTensor * lookups, const ICLTensor * keys, const ICLTensor * input, ICLTensor * output, ICLTensor * hits)
Set the input and output of the kernel.
Parameters
[in] lookups Lookups 1D tensor that values are indices into the first dimension of input.
[in] keys Keys 1D tensor. keys and input pair represent a map. Data types supported: S32
[in] input Source tensor. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[out] output Destination tensor. Data types and data layouts supported: Same as input.
[out] hits Hits 1D tensor. A boolean tensor that indicates whether the lookup hits (True) or not (False). Data types supported: U8/QASYMM8
Returns
N/A
Definition at line 102 of file CLHashtableLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_THROW_ON(
    validate(lookups->info(), keys->info(), input->info(), output->info(), hits->info()));
  _lookups = lookups;
  _keys = keys;
  _input = input;
  _output = output;
  _hits = hits;
  // Make _lookup_indices tensor
  _lookup_indices = std::make_unique<CLTensor>();
  _lookup_indices->allocator()->init(
    TensorInfo(lookups->info()->tensor_shape(), lookups->info()->num_channels(), DataType::S32));
  _lookup_indices->allocator()->allocate();
  // Set kernel build options
  std::stringstream kernel_name;
  std::set<std::string> build_opts;
  kernel_name << "hashtable_lookup";
  build_opts.emplace("-DDEPTH_OUT=" + support::cpp11::to_string(output->info()->dimension(2)));
  build_opts.emplace("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.emplace("-DVEC_SIZE=" + support::cpp11::to_string(num_elems_processed_per_iteration));
  build_opts.emplace("-DNUM_DIMS=" + support::cpp11::to_string(_input->info()->num_dimensions()));
  // Create kernel
  _kernel =
    static_cast<cl::Kernel>(CLKernelLibraryEx::get().create_kernel(kernel_name.str(), build_opts));
  // Configure kernel window
  auto win_config = validate_and_configure_window(input->info(), output->info());
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  ICLKernel::configure_internal(win_config.second);
}
References arm_compute::CLKernelLibraryEx::create_kernel(), arm_compute::CLKernelLibraryEx::get(), and validate().
operator=() [1/2]
CLHashtableLookupKernel & arm_compute::CLHashtableLookupKernel::operator= (CLHashtableLookupKernel &&) default
Move assignment operator.
Parameters
[in] CLHashtableLookupKernel object to move
operator=() [2/2]
CLHashtableLookupKernel & arm_compute::CLHashtableLookupKernel::operator= (const CLHashtableLookupKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void CLHashtableLookupKernel::run (const Window & window, cl::CommandQueue & queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Returns
N/A
N/A
Definition at line 140 of file CLHashtableLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  const_cast<ICLTensor *>(_lookups)->map(queue);
  const_cast<ICLTensor *>(_keys)->map(queue);
  _hits->map(queue);
  _lookup_indices->map(queue);
  // Set values of hits
  const int32_t *lookups_buf =
    reinterpret_cast<int32_t *>(const_cast<ICLTensor *>(_lookups)->buffer());
  const int32_t *keys_buf = reinterpret_cast<int32_t *>(const_cast<ICLTensor *>(_keys)->buffer());
  uint8_t *hits_buf = reinterpret_cast<uint8_t *>(_hits->buffer());
  int32_t *lookup_indices_buf = reinterpret_cast<int32_t *>(_lookup_indices->buffer());
  std::map<int32_t, size_t> key_map;
  const size_t keys_num = _keys->info()->dimension(0);
  for (size_t key_index = 0; key_index < keys_num; key_index++)
  {
    key_map[keys_buf[key_index]] = key_index;
  }
  const size_t lookups_num = _lookups->info()->dimension(0);
  for (size_t i = 0; i < lookups_num; ++i)
  {
    const auto lookup_value = lookups_buf[i];
    const auto it = key_map.find(lookup_value);
    if (it != key_map.end())
    {
#if defined(ARM_COMPUTE_DEBUG_ENABLED)
      if (it->second >= lookups_num)
        ARM_COMPUTE_ERROR("HashTable Lookup: index out of bounds.");
#endif // defined(ARM_COMPUTE_DEBUG_ENABLED)
      lookup_indices_buf[i] = static_cast<int32_t>(it->second);
      hits_buf[i] = static_cast<uint8_t>(1);
    }
    else
    {
      lookup_indices_buf[i] = -1;
      hits_buf[i] = static_cast<uint8_t>(0);
    }
  }
  const_cast<ICLTensor *>(_lookups)->unmap(queue);
  const_cast<ICLTensor *>(_keys)->unmap(queue);
  _hits->unmap(queue);
  _lookup_indices->unmap(queue);
  Window win = window.collapse(ICLKernel::window(), 2, 4);
  Window win_lookup;
  win_lookup.set(Window::DimX, Window::Dimension(0, 0, 0));
  do
  {
    unsigned int idx = 0;
    add_4D_tensor_argument(idx, _input, win);
    add_4D_tensor_argument(idx, _output, win);
    add_1D_tensor_argument(idx, _lookup_indices.get(), win_lookup);
    enqueue(queue, *this, win);
  } while (window.slide_window_slice_4D(win) && window.slide_window_slice_1D(win_lookup));
}
validate()
Status CLHashtableLookupKernel::validate (const ITensorInfo * lookups, const ITensorInfo * keys, const ITensorInfo * input, const ITensorInfo * output, const ITensorInfo * hits) static
Static function to check if given info will lead to a valid configuration of CLHashtableLookupKernel.
Parameters
[in] lookups The lookups tensor info. Data types supported: S32.
[in] keys The keys tensor info. keys and input pair represent a map. Data types supported: S32
[in] input The input tensor info. Data types supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[out] output The output tensor. Data types and data layouts supported: Same as input.
[out] hits The hits tensor info. A boolean tensor that indicates whether the lookup hits (True) or not (False). Data types supported: U8/QASYMM8
Returns
a status
Definition at line 76 of file CLHashtableLookupKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(lookups, keys, input, output, hits);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(
    input, 1, DataType::U8, DataType::S8, DataType::QASYMM8, DataType::U16, DataType::S16,
    DataType::U32, DataType::S32, DataType::F16, DataType::F32);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(lookups, 1, DataType::S32);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(keys, 1, DataType::S32);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(hits, 1, DataType::U8, DataType::QASYMM8);
  ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
  ARM_COMPUTE_RETURN_ERROR_ON_MSG(output->tensor_shape().total_size() == 0,
                                  "Output's shape was not set");
  ARM_COMPUTE_ERROR_ON(lookups->dimension(0) != hits->dimension(0) ||
                       output->dimension(output->num_dimensions() - 1) != lookups->dimension(0));
  ARM_COMPUTE_ERROR_ON(input->num_dimensions() < 2 && input->num_dimensions() > 4);
  ARM_COMPUTE_ERROR_ON(lookups->num_dimensions() > 1);
  ARM_COMPUTE_ERROR_ON(keys->num_dimensions() > 1);
  ARM_COMPUTE_ERROR_ON(hits->num_dimensions() > 1);
  return Status{};
}
Referenced by configure(), and ~CLHashtableLookupKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLHashtableLookupKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLHashtableLookupKernel.cpp