ONE - On-device Neural Engine: flexbuffers::FixedTypedVector Class Reference
flexbuffers::FixedTypedVector Class Reference
#include <flexbuffers.h>
Public Member Functions
FixedTypedVector (const uint8_t *data, uint8_t byte_width, Type element_type, uint8_t len)
Reference operator[] (size_t i) const
bool IsTheEmptyFixedTypedVector () const
Type ElementType ()
uint8_t size ()
Public Member Functions inherited from flexbuffers::Object
Object (const uint8_t *data, uint8_t byte_width)
Static Public Member Functions
static FixedTypedVector EmptyFixedTypedVector ()
Additional Inherited Members
Protected Attributes inherited from flexbuffers::Object
const uint8_t * data_
uint8_t byte_width_
Detailed Description
Definition at line 319 of file flexbuffers.h.
Constructor & Destructor Documentation
FixedTypedVector()
flexbuffers::FixedTypedVector::FixedTypedVector (const uint8_t * data, uint8_t byte_width, Type element_type, uint8_t len) inline
Definition at line 322 of file flexbuffers.h.
    : Object(data, byte_width), type_(element_type), len_(len)
  {
  }
Member Function Documentation
ElementType()
Type flexbuffers::FixedTypedVector::ElementType () inline
Definition at line 339 of file flexbuffers.h.
{ return type_; }
EmptyFixedTypedVector()
static FixedTypedVector flexbuffers::FixedTypedVector::EmptyFixedTypedVector () inline static
Definition at line 329 of file flexbuffers.h.
  {
    static const uint8_t fixed_empty_vector[] = {0 /* unused */};
    return FixedTypedVector(fixed_empty_vector, 1, FBT_INT, 0);
  }
References flexbuffers::FBT_INT.
Referenced by flexbuffers::Reference::AsFixedTypedVector(), and IsTheEmptyFixedTypedVector().
IsTheEmptyFixedTypedVector()
bool flexbuffers::FixedTypedVector::IsTheEmptyFixedTypedVector () const inline
Definition at line 334 of file flexbuffers.h.
  {
    return data_ == FixedTypedVector::EmptyFixedTypedVector().data_;
  }
References flexbuffers::Object::data_, and EmptyFixedTypedVector().
operator[]()
Reference flexbuffers::FixedTypedVector::operator[] (size_t i) const inline
Definition at line 961 of file flexbuffers.h.
{
  if (i >= len_)
    return Reference(nullptr, 1, NullPackedType());
  auto elem = data_ + i * byte_width_;
  return Reference(elem, byte_width_, 1, type_);
}
References flexbuffers::Object::byte_width_, flexbuffers::Object::data_, and flexbuffers::NullPackedType().
size()
uint8_t flexbuffers::FixedTypedVector::size () inline
Definition at line 340 of file flexbuffers.h.
{ return len_; }
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h