ONE - On-device Neural Engine: coco::Load Class Reference
coco::Load Class Reference final
Load an Object.
#include <Ops.h>
Public Member Functions
Load ()
Load (const Load &)=delete
Load (Load &&)=delete
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const override
Return a set of object(s) used during execution.
Load * asLoad (void) override
const Load * asLoad (void) const override
Instr * loc (void) override
void object (Object *o)
Object * object (void) const
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Public Member Functions inherited from coco::Object::Consumer
virtual ~Consumer ()=default
Public Member Functions inherited from coco::Bag::Reader
virtual ~Reader ()=default
Public Member Functions inherited from coco::Locatable
virtual ~Locatable ()=default
virtual Instr * loc (void)=0
Detailed Description
Load an Object.
Definition at line 37 of file Ops.h.
Constructor & Destructor Documentation
Load() [1/3]
coco::Load::Load () explicit
Definition at line 24 of file Load.cpp.
           : _obj{this}
{
  // DO NOTHING
}
Load() [2/3]
coco::Load::Load (const Load &) delete
Load() [3/3]
coco::Load::Load (Load &&) delete
Member Function Documentation
arg()
Op * coco::Load::arg (uint32_t n) const final virtual
Return N-th argument.
Note
The behavior of arg(n) is defined only when n < artiy()
Implements coco::Op.
Definition at line 35 of file Load.cpp.
{
  assert(!"Load has no argument");
  return nullptr;
}
arity()
uint32_t coco::Load::arity (void) const final virtual
Return the number of arguments (# of child Ops)
Implements coco::Op.
Definition at line 29 of file Load.cpp.
{
  // Load has no child Op
  return 0;
}
asLoad() [1/2]
const Load * coco::Load::asLoad (void) const inline override
Definition at line 54 of file Ops.h.
{ return this; }
asLoad() [2/2]
Load * coco::Load::asLoad (void) inline override
Definition at line 53 of file Ops.h.
{ return this; }
loc()
Instr * coco::Load::loc (void) inline override virtual
Implements coco::Locatable.
Definition at line 57 of file Ops.h.
{ return parent(); }
References coco::Op::parent().
object() [1/2]
void coco::Load::object (Object * o) inline
Definition at line 60 of file Ops.h.
{ _obj.value(o); }
References coco::Use::value().
Referenced by OpBuilder::load(), and OpPrinter::visit().
object() [2/2]
Object * coco::Load::object (void) const inline
Definition at line 61 of file Ops.h.
{ return _obj.value(); }
References coco::Use::value().
uses()
std::set< Object * > coco::Load::uses (void) const override virtual
Return a set of object(s) used during execution.
NOTE There is no 'def' method as Op is not allowed to define a new object
Implements coco::Op.
Definition at line 41 of file Load.cpp.
{
  std::set<Object *> res;
  if (auto obj = object())
  {
    res.insert(obj);
  }
  return res;
}
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Ops.h
compiler/coco/core/src/IR/Load.cpp