ONE - On-device Neural Engine: onert::odc::CodegenLoader Class Reference
onert::odc::CodegenLoader Class Reference
Class to manage loading and unloading of dynamic library containing implementation of ICodegen interface.
#include <CodegenLoader.h>
Public Types
using dlhandle_destroy_t = std::function< void(void *)>
Typedef for function pointer to destroy loaded library handle.
using factory_t = ICodegen *(*)()
Typedef for function pointer to create instance of ICodegen.
using codegen_destory_t = void(*)(ICodegen *)
Typedef for function pointer to destroy instance of ICodegen.
Public Member Functions
CodegenLoader (CodegenLoader const &)=delete
CodegenLoader & operator= (CodegenLoader const &)=delete
void loadLibrary (const char *target)
Load dynamic library containing implementation of ICodegen.
void unloadLibrary ()
Unload dynamic library containing implementation of ICodegen.
const ICodegen * get () const
Get instance of ICodegen created through factory method.
Static Public Member Functions
static CodegenLoader & instance ()
Get singleton instance of CodegenLoader.
Detailed Description
Class to manage loading and unloading of dynamic library containing implementation of ICodegen interface.
Definition at line 34 of file CodegenLoader.h.
Member Typedef Documentation
codegen_destory_t
using onert::odc::CodegenLoader::codegen_destory_t = void (*)(ICodegen *)
Typedef for function pointer to destroy instance of ICodegen.
Definition at line 48 of file CodegenLoader.h.
dlhandle_destroy_t
using onert::odc::CodegenLoader::dlhandle_destroy_t = std::function<void(void *)>
Typedef for function pointer to destroy loaded library handle.
Definition at line 40 of file CodegenLoader.h.
factory_t
using onert::odc::CodegenLoader::factory_t = ICodegen *(*)()
Typedef for function pointer to create instance of ICodegen.
Definition at line 44 of file CodegenLoader.h.
Constructor & Destructor Documentation
CodegenLoader()
onert::odc::CodegenLoader::CodegenLoader (CodegenLoader const &) delete
Member Function Documentation
get()
const ICodegen * onert::odc::CodegenLoader::get () const inline
Get instance of ICodegen created through factory method.
Returns
Pointer to instance of ICodegen
Definition at line 85 of file CodegenLoader.h.
{ return _codegen.get(); }
Referenced by loadLibrary(), and unloadLibrary().
instance()
CodegenLoader & onert::odc::CodegenLoader::instance () static
Get singleton instance of CodegenLoader.
Returns
Reference to singleton instance of CodegenLoader
Definition at line 35 of file CodegenLoader.cc.
{
  static CodegenLoader singleton;
  return singleton;
}
Referenced by onert::odc::CodegenManager::codegen().
loadLibrary()
void onert::odc::CodegenLoader::loadLibrary (const char * target)
Load dynamic library containing implementation of ICodegen.
Parameters
[in] target Target backend name This target string will be used to find a backend library. The name of target backend library should follow the following rules: 'lib' + {backend extension} + '-gen' + {lib extension} And the target string should be a name except 'lib' and {lib extension}. For example, if the backend extension is 'aaa', the backend library name should be 'libaaa-gen.so', and the target string should be 'aaa-gen'.
Definition at line 41 of file CodegenLoader.cc.
{
  if (get() != nullptr)
    return;
  const std::string codegen_so = "lib" + std::string{target} + SHARED_LIB_EXT;
  void *handle = dlopen(codegen_so.c_str(), RTLD_LAZY | RTLD_LOCAL);
  if (handle == nullptr)
  {
    throw std::runtime_error("CodegenLoader: " + std::string{dlerror()});
  }
  const auto factory = (factory_t)dlsym(handle, "create_codegen");
  if (factory == nullptr)
  {
    const std::string dlerror_msg = dlerror();
    dlclose(handle);
    throw std::runtime_error("CodegenLoader: " + dlerror_msg);
  }
  const auto destroyer = (codegen_destory_t)dlsym(handle, "destroy_codegen");
  _codegen = std::unique_ptr<ICodegen, codegen_destory_t>(factory(), destroyer);
  if (_codegen == nullptr)
  {
    dlclose(handle);
    throw std::runtime_error("CodegenLoader: unable to create codegen");
  }
  // Save backend handle (avoid warning by handle lost without dlclose())
  _dlhandle = std::unique_ptr<void, dlhandle_destroy_t>{
    handle, [filename = codegen_so](void *h) {
      if (dlclose(h))
        throw std::runtime_error("CodegenLoader: Failed to unload backend " + filename);
    }};
}
References get().
operator=()
CodegenLoader & onert::odc::CodegenLoader::operator= (CodegenLoader const &) delete
unloadLibrary()
void onert::odc::CodegenLoader::unloadLibrary ()
Unload dynamic library containing implementation of ICodegen.
Definition at line 77 of file CodegenLoader.cc.
{
  if (get() == nullptr)
    return;
  _codegen.reset(nullptr);
  _dlhandle.reset(nullptr);
}
References get().
The documentation for this class was generated from the following files:
runtime/onert/core/src/odc/CodegenLoader.h
runtime/onert/core/src/odc/CodegenLoader.cc