ONE - On-device Neural Engine: moco::Conv2DBackpropInputGraphBuilder Class Reference
moco::Conv2DBackpropInputGraphBuilder Class Reference final
GraphBuilder for Conv2DBackpropInput node.
#include <Conv2DBackpropInput.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Conv2DBackpropInput node.
Definition at line 28 of file Conv2DBackpropInput.h.
Member Function Documentation
build()
void moco::Conv2DBackpropInputGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 99 of file Conv2DBackpropInput.cpp.
{
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  UpdateQueue *updates = context->updates();
  // name of loco nodes
  std::string conv2d_backprop_name = node.name();
  auto conv2d_backprop = graph->nodes()->create<TFConv2DBackpropInput>();
  conv2d_backprop->name(node.name());
  // read attributes
  auto data_layout = plier::tf::get_string_attr(node, "data_format");
  assert(data_layout == "NHWC" || data_layout == "NCHW");
  conv2d_backprop->data_layout(data_layout);
  auto tf_strides = plier::tf::get_list_attr(node, "strides");
  auto strides = plier::tf::as_int64_list(tf_strides);
  conv2d_backprop->strides(strides);
  auto padding = moco::str_toupper(plier::tf::get_string_attr(node, "padding"));
  assert(padding == "VALID" || padding == "SAME");
  conv2d_backprop->padding(padding);
  // save the name for graph link updates
  TensorName output_name(conv2d_backprop_name, 0);
  tensor_names->enroll(output_name, conv2d_backprop);
  std::vector<TensorName> input_names;
  input_names.push_back(TensorName(node.input(0))); // input_sizes
  input_names.push_back(TensorName(node.input(1))); // filter
  input_names.push_back(TensorName(node.input(2))); // out_backprop
  // update
  auto conv2d_backprop_update =
    std::make_unique<Conv2DBackpropInputGraphUpdate>(conv2d_backprop, input_names);
  updates->enroll(std::move(conv2d_backprop_update));
}
References plier::tf::as_int64_list(), moco::SymbolTable::enroll(), moco::UpdateQueue::enroll(), plier::tf::get_list_attr(), plier::tf::get_string_attr(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::str_toupper(), moco::GraphBuilderContext::tensor_names(), and moco::GraphBuilderContext::updates().
validate()
bool moco::Conv2DBackpropInputGraphBuilder::validate (const tensorflow::NodeDef & node) const override virtual
Implements moco::GraphBuilder.
Definition at line 72 of file Conv2DBackpropInput.cpp.
{
  if (node.input_size() != 3)
    return false;
  if (!plier::tf::has_attrs(node, {"T", "data_format", "padding", "strides"}))
    return false;
  auto data_layout = plier::tf::get_string_attr(node, "data_format");
  if (!(data_layout == "NHWC" || data_layout == "NCHW"))
  {
    throw oops::UserExn("Conv2DBackprop Unsupported data_format", node.name());
  }
  // dilation attribute is not fully supported
  if (plier::tf::has_attr(node, "dilations"))
  {
    // TODO Support non-default dilations
    auto dilation = plier::tf::get_list_attr(node, "dilations").i();
    if (!std::all_of(dilation.begin(), dilation.end(), [](std::int64_t dil) { return dil == 1; }))
      return false;
  }
  // Else, dilations are automatically set to default [1,1,1,1] which we assumes now
  return true;
}
References plier::tf::get_list_attr(), plier::tf::get_string_attr(), plier::tf::has_attr(), and plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Conv2DBackpropInput.h
compiler/moco/import/src/Nodes/Conv2DBackpropInput.cpp