ONE - On-device Neural Engine: onert::backend::acl_cl::Optimizer Class Reference
onert::backend::acl_cl::Optimizer Class Reference
#include <Optimizer.h>
Public Member Functions
Optimizer (BackendContext *context)
void optimize ()
Detailed Description
Definition at line 30 of file Optimizer.h.
Constructor & Destructor Documentation
Optimizer()
onert::backend::acl_cl::Optimizer::Optimizer (BackendContext * context)
Definition at line 33 of file Optimizer.cc.
  : _context{context}, _tensor_builder{
                         std::dynamic_pointer_cast<TensorBuilder>(context->tensor_builder)}
{
  assert(context);
}
Member Function Documentation
optimize()
void onert::backend::acl_cl::Optimizer::optimize ()
Definition at line 40 of file Optimizer.cc.
{
  // Concat elimination (build subtensor info)
  {
    acl_common::AclSubTensorAnalyzer sa{*_context->graph()};
    sa.setUsePadding();
    _context->graph()->operations().iterate(
      [&](const ir::OperationIndex &, const ir::Operation &op) {
        sa.setLayout(_context->graph()->layout());
        op.accept(sa);
      });
    _tensor_builder->parent_map(sa.releaseParentMap());
  }
}
References onert::ir::Operation::accept(), onert::backend::BackendContext::graph(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::Graph::layout(), and onert::ir::Graph::operations().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/Optimizer.h
runtime/onert/backend/acl_cl/Optimizer.cc