ONE - On-device Neural Engine: locoex::TFLRelu6 Class Reference
locoex::TFLRelu6 Class Reference final
#include <TFLNodes.h>
Public Member Functions
TFLRelu6 ()=default
loco::Node * features (void) const
void features (loco::Node *node)
Public Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::RELU6 >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFLOpcode opcode (void) const =0
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >
loco::Use * at (unsigned n) const
Detailed Description
Definition at line 394 of file TFLNodes.h.
Constructor & Destructor Documentation
TFLRelu6()
locoex::TFLRelu6::TFLRelu6 () default
Member Function Documentation
features() [1/2]
void locoex::TFLRelu6::features (loco::Node * node) inline
Definition at line 401 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >::at(), and loco::Use::node().
features() [2/2]
loco::Node * locoex::TFLRelu6::features (void) const inline
Definition at line 400 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 1, TFLNodeImpl< TFLOpcode::RELU6 > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h