ONE - On-device Neural Engine: onert::backend::cpu::ops::SqDiffLayer Class Reference
onert::backend::cpu::ops::SqDiffLayer Class Reference
#include <SquaredDiffLayer.h>
Public Member Functions
SqDiffLayer ()
void SqDiffFloat32 ()
void configure (const IPortableTensor *input1, const IPortableTensor *input2, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file SquaredDiffLayer.h.
Constructor & Destructor Documentation
SqDiffLayer()
onert::backend::cpu::ops::SqDiffLayer::SqDiffLayer ()
Definition at line 32 of file SquaredDiffLayer.cc.
                         : _input1(nullptr), _input2(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::SqDiffLayer::configure (const IPortableTensor * input1, const IPortableTensor * input2, IPortableTensor * output)
Definition at line 43 of file SquaredDiffLayer.cc.
{
  _input1 = input1;
  _input2 = input2;
  _output = output;
}
run()
void onert::backend::cpu::ops::SqDiffLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 51 of file SquaredDiffLayer.cc.
{
  if (_input1->data_type() == OperandType::FLOAT32)
  {
    SqDiffFloat32();
  }
  else
  {
    throw std::runtime_error{"SquaredDiff: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), and SqDiffFloat32().
SqDiffFloat32()
void onert::backend::cpu::ops::SqDiffLayer::SqDiffFloat32 ()
Definition at line 37 of file SquaredDiffLayer.cc.
{
  nnfw::cker::SqDiff(getShape(_input1), getBuffer<float>(_input1), getShape(_input2),
                     getBuffer<float>(_input2), getShape(_output), getBuffer<float>(_output));
}
References onert::backend::cpu::ops::getShape(), and nnfw::cker::SqDiff().
Referenced by run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/SquaredDiffLayer.h
runtime/onert/backend/cpu/ops/SquaredDiffLayer.cc