ONE - On-device Neural Engine: nnkit::support::tftestinfo::ParsedTensor Class Reference
nnkit::support::tftestinfo::ParsedTensor Class Reference final
Class to store tensor information parsed from test.info file under moco/test/tf.
#include <ParsedTensor.h>
Public Types
enum class Kind { Input , Output }
Public Member Functions
ParsedTensor ()=delete
ParsedTensor (const Kind kind, const std::string &name, const DataType &dtype, const std::vector< int32_t > &shape)
~ParsedTensor ()
Kind kind () const
const std::string & name ()
const nncc::core::ADT::tensor::Shape & shape () const
nncc::core::ADT::tensor::Shape & mutable_shape ()
const DataType & dtype () const
std::string nodeName () const
Get the name of node that has this tensor. E.g., if the name of this tensor is "MyOp:0", this method returns "MyOp".
int tensorIndex () const
Get the index from the tensor name. E.g., if the name of this tensor is "MyOp:12", this method returns 12.
bool isFloatTensor () const
bool hasShape () const
Detailed Description
Class to store tensor information parsed from test.info file under moco/test/tf.
Definition at line 47 of file ParsedTensor.h.
Member Enumeration Documentation
Kind
enum class nnkit::support::tftestinfo::ParsedTensor::Kind strong
Enumerator
Input
Output
Definition at line 50 of file ParsedTensor.h.
  {
    Input,
    Output
  };
Constructor & Destructor Documentation
ParsedTensor() [1/2]
nnkit::support::tftestinfo::ParsedTensor::ParsedTensor () delete
ParsedTensor() [2/2]
nnkit::support::tftestinfo::ParsedTensor::ParsedTensor (const Kind kind, const std::string & name, const DataType & dtype, const std::vector< int32_t > & shape) inline
Definition at line 58 of file ParsedTensor.h.
    : _kind(kind), _dtype(dtype)
  {
    _tensor_name.assign(name);
    _shape.resize(shape.size());
    for (int rank = 0; rank < shape.size(); rank++)
      _shape.dim(rank) = shape.at(rank);
  }
References nncc::core::ADT::tensor::Shape::dim(), name(), nncc::core::ADT::tensor::Shape::resize(), and shape().
~ParsedTensor()
nnkit::support::tftestinfo::ParsedTensor::~ParsedTensor () inline
Definition at line 69 of file ParsedTensor.h.
  { /* empty */
  }
Member Function Documentation
dtype()
const DataType & nnkit::support::tftestinfo::ParsedTensor::dtype () const inline
Definition at line 83 of file ParsedTensor.h.
{ return _dtype; }
hasShape()
bool nnkit::support::tftestinfo::ParsedTensor::hasShape () const inline
Definition at line 108 of file ParsedTensor.h.
{ return _has_shape; }
isFloatTensor()
bool nnkit::support::tftestinfo::ParsedTensor::isFloatTensor () const inline
Definition at line 107 of file ParsedTensor.h.
{ return _dtype == DataType::FLOAT32; }
Referenced by nnkit::support::tf::TensorDataMap::allocate().
kind()
Kind nnkit::support::tftestinfo::ParsedTensor::kind () const inline
Definition at line 74 of file ParsedTensor.h.
{ return _kind; }
mutable_shape()
nncc::core::ADT::tensor::Shape & nnkit::support::tftestinfo::ParsedTensor::mutable_shape () inline
Definition at line 81 of file ParsedTensor.h.
{ return _shape; }
name()
const std::string & nnkit::support::tftestinfo::ParsedTensor::name () inline
Definition at line 76 of file ParsedTensor.h.
{ return _tensor_name; }
Referenced by ParsedTensor().
nodeName()
std::string nnkit::support::tftestinfo::ParsedTensor::nodeName () const inline
Get the name of node that has this tensor. E.g., if the name of this tensor is "MyOp:0", this method returns "MyOp".
Definition at line 89 of file ParsedTensor.h.
{ return _tensor_name.substr(0, _tensor_name.find(":")); }
shape()
const nncc::core::ADT::tensor::Shape & nnkit::support::tftestinfo::ParsedTensor::shape () const inline
Definition at line 78 of file ParsedTensor.h.
{ return _shape; }
Referenced by nnkit::support::tf::TensorDataMap::allocate(), and ParsedTensor().
tensorIndex()
int nnkit::support::tftestinfo::ParsedTensor::tensorIndex () const inline
Get the index from the tensor name. E.g., if the name of this tensor is "MyOp:12", this method returns 12.
Definition at line 95 of file ParsedTensor.h.
  {
    int separator = _tensor_name.find(":");
    // sanity check
    if (separator == std::string::npos)
      throw oops::UserExn("Tensor name  in wrong format", "name", _tensor_name);
    return std::stoi(_tensor_name.substr(separator + 1, _tensor_name.length() - separator - 1));
  }
The documentation for this class was generated from the following file:
compiler/tfinfo/include/nnkit/support/tftestinfo/ParsedTensor.h