ONE - On-device Neural Engine: onert::backend::builtin::train::TensorRegistry Class Reference
onert::backend::builtin::train::TensorRegistry Class Reference
#include <TensorRegistry.h>
Public Member Functions
TensorRegistry ()
ITensor * getITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native tensors.
IPortableTensor * getPortableTensor (const ir::OperandIndex &index)
IOTensor * getNativeIOTensor (const ir::OperandIndex &index)
ITensor * getBackPropITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for back propatation.
ITensor * getGradientITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for gradient.
BackPropTensor * getBackPropTensor (const ir::OperandIndex &index)
bool setMigrantTensor (const ir::OperandIndex &index, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> &) const override
void setBackPropTensor (const ir::OperandIndex &index, std::unique_ptr< BackPropTensor > tensor)
void setGradientTensor (const ir::OperandIndex &index, std::unique_ptr< GradientTensor > tensor)
void setNativeIOTensor (ir::OperandIndex index, std::unique_ptr< IOTensor > &&tensor)
const ir::OperandIndexMap< std::unique_ptr< IOTensor > > & native_io_tensors ()
std::shared_ptr< BaseTensorRegistry > base_reg ()
Public Member Functions inherited from onert::backend::train::ITensorRegistry
virtual ITensor * getBackPropITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for back propatation.
virtual ITensor * getGradientITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for gradient.
virtual void iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const train::ITrainableTensor *)> &) const =0
Iterate ITrainableTensors with fn.
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Detailed Description
Definition at line 39 of file TensorRegistry.h.
Constructor & Destructor Documentation
TensorRegistry()
onert::backend::builtin::train::TensorRegistry::TensorRegistry () inline
Definition at line 42 of file TensorRegistry.h.
: _base_reg{new BaseTensorRegistry} {}
Member Function Documentation
base_reg()
std::shared_ptr< BaseTensorRegistry > onert::backend::builtin::train::TensorRegistry::base_reg () inline
Definition at line 128 of file TensorRegistry.h.
{ return _base_reg; }
getBackPropITensor()
ITensor * onert::backend::builtin::train::TensorRegistry::getBackPropITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor for back propatation.
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::train::ITensorRegistry.
Definition at line 76 of file TensorRegistry.h.
  {
    return _base_reg->getBackPropTensor(index);
  }
getBackPropTensor()
BackPropTensor * onert::backend::builtin::train::TensorRegistry::getBackPropTensor (const ir::OperandIndex & index) inline
Definition at line 86 of file TensorRegistry.h.
  {
    return _base_reg->getBackPropTensor(index);
  }
getGradientITensor()
ITensor * onert::backend::builtin::train::TensorRegistry::getGradientITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor for gradient.
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::train::ITensorRegistry.
Definition at line 81 of file TensorRegistry.h.
  {
    return _base_reg->getGradientTensor(index);
  }
getITensor()
ITensor * onert::backend::builtin::train::TensorRegistry::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 44 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getITensor(index);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(index);
  }
References getNativeIOTensor().
Referenced by setMigrantTensor(), and setNativeIOTensor().
getNativeIOTensor()
IOTensor * onert::backend::builtin::train::TensorRegistry::getNativeIOTensor (const ir::OperandIndex & index) inline
Definition at line 68 of file TensorRegistry.h.
  {
    auto tensor = _native_io_tensors.find(index);
    if (tensor != _native_io_tensors.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by getITensor(), getNativeITensor(), and getPortableTensor().
getNativeITensor()
ITensor * onert::backend::builtin::train::TensorRegistry::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 52 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getNativeITensor(index);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(index);
  }
References getNativeIOTensor().
getPortableTensor()
IPortableTensor * onert::backend::builtin::train::TensorRegistry::getPortableTensor (const ir::OperandIndex & index) inline
Definition at line 60 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getPortableTensor(index);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(index);
  }
References getNativeIOTensor().
iterateTrainableTensors()
void onert::backend::builtin::train::TensorRegistry::iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> &) const inline override
Definition at line 99 of file TensorRegistry.h.
  {
    // DO NOTHING
    // Builtin tensor registry does not have trainable tensor.
  }
native_io_tensors()
const ir::OperandIndexMap< std::unique_ptr< IOTensor > > & onert::backend::builtin::train::TensorRegistry::native_io_tensors () inline
Definition at line 124 of file TensorRegistry.h.
  {
    return _native_io_tensors;
  }
setBackPropTensor()
void onert::backend::builtin::train::TensorRegistry::setBackPropTensor (const ir::OperandIndex & index, std::unique_ptr< BackPropTensor > tensor) inline
Definition at line 107 of file TensorRegistry.h.
  {
    _base_reg->setBackPropTensor(index, std::move(tensor));
  }
setGradientTensor()
void onert::backend::builtin::train::TensorRegistry::setGradientTensor (const ir::OperandIndex & index, std::unique_ptr< GradientTensor > tensor) inline
Definition at line 112 of file TensorRegistry.h.
  {
    _base_reg->setGradientTensor(index, std::move(tensor));
  }
setMigrantTensor()
bool onert::backend::builtin::train::TensorRegistry::setMigrantTensor (const ir::OperandIndex & , IPortableTensor *) inline override virtual
Set the Migrant Tensor which are from other backends.
Returns
true if supported
false if not supported
Reimplemented from onert::backend::ITensorRegistry.
Definition at line 91 of file TensorRegistry.h.
  {
    assert(tensor);
    assert(!getITensor(index)); // For the index, tensor is not registered yet
    _base_reg->setMigrantTensor(index, tensor);
    return true;
  }
References getITensor().
setNativeIOTensor()
void onert::backend::builtin::train::TensorRegistry::setNativeIOTensor (ir::OperandIndex index, std::unique_ptr< IOTensor > && tensor) inline
Definition at line 117 of file TensorRegistry.h.
  {
    assert(tensor);
    assert(!getITensor(index)); // For the index, tensor is not registered yet
    _native_io_tensors[index] = std::move(tensor);
  }
References getITensor().
The documentation for this class was generated from the following file:
runtime/onert/core/src/backend/builtin/train/TensorRegistry.h