ONE - On-device Neural Engine: onert::ir::OperationIndexSet Class Reference
onert::ir::OperationIndexSet Class Reference
#include <OperationIndexSet.h>
Public Member Functions
OperationIndexSet (void)=default
OperationIndexSet (std::initializer_list< OperationIndex > list)
void insert (const OperationIndex &index)
void clear (void)
void remove (const OperationIndex &index)
uint32_t size () const
bool contains (const OperationIndex &index) const
std::unordered_set< OperationIndex >::iterator begin (void)
std::unordered_set< OperationIndex >::iterator end (void)
std::unordered_set< OperationIndex >::const_iterator begin (void) const
std::unordered_set< OperationIndex >::const_iterator end (void) const
Detailed Description
Definition at line 32 of file OperationIndexSet.h.
Constructor & Destructor Documentation
OperationIndexSet() [1/2]
onert::ir::OperationIndexSet::OperationIndexSet (void) default
OperationIndexSet() [2/2]
onert::ir::OperationIndexSet::OperationIndexSet (std::initializer_list< OperationIndex > list)
Definition at line 26 of file OperationIndexSet.cc.
                                                                             : _set(list)
{
  // DO NOTHING
}
Member Function Documentation
begin() [1/2]
std::unordered_set< OperationIndex >::iterator onert::ir::OperationIndexSet::begin (void) inline
Definition at line 53 of file OperationIndexSet.h.
{ return _set.begin(); }
begin() [2/2]
std::unordered_set< OperationIndex >::const_iterator onert::ir::OperationIndexSet::begin (void) const inline
Definition at line 55 of file OperationIndexSet.h.
{ return _set.begin(); }
clear()
void onert::ir::OperationIndexSet::clear (void) inline
Definition at line 40 of file OperationIndexSet.h.
{ _set.clear(); }
Referenced by onert::ir::Operand::clearDefUse().
contains()
bool onert::ir::OperationIndexSet::contains (const OperationIndex & index) const
Definition at line 31 of file OperationIndexSet.cc.
{
  return std::find(_set.begin(), _set.end(), index) != _set.end();
}
end() [1/2]
std::unordered_set< OperationIndex >::iterator onert::ir::OperationIndexSet::end (void) inline
Definition at line 54 of file OperationIndexSet.h.
{ return _set.end(); }
end() [2/2]
std::unordered_set< OperationIndex >::const_iterator onert::ir::OperationIndexSet::end (void) const inline
Definition at line 56 of file OperationIndexSet.h.
{ return _set.end(); }
insert()
void onert::ir::OperationIndexSet::insert (const OperationIndex & index) inline
Definition at line 39 of file OperationIndexSet.h.
{ _set.insert(index); }
Referenced by onert::ir::Operand::insertUse().
remove()
void onert::ir::OperationIndexSet::remove (const OperationIndex & index) inline
Definition at line 41 of file OperationIndexSet.h.
  {
    auto itr = std::find(_set.begin(), _set.end(), index);
    assert(itr != _set.end());
    _set.erase(itr);
  }
Referenced by onert::ir::Operand::removeUse().
size()
uint32_t onert::ir::OperationIndexSet::size () const inline
Definition at line 49 of file OperationIndexSet.h.
{ return static_cast<uint32_t>(_set.size()); }
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/OperationIndexSet.h
runtime/onert/core/src/ir/OperationIndexSet.cc