ONE - On-device Neural Engine: nnfw::rt::optimized_ops::TopContainer< T > Class Template Reference
nnfw::rt::optimized_ops::TopContainer< T > Class Template Reference
class to define TopK operation
#include <topk_v2.h>
Public Member Functions
TopContainer ()=delete
Prevent default constructor of of this class.
TopContainer (int32 k, int32 row_size)
Constructor with params.
TopContainer (const TopContainer &)=delete
Prevent instances of this class from being copied (As this class contains pointers)
TopContainer & operator= (const TopContainer &)=delete
void start_collecting (const T *values)
Start collecting.
void push (int32 a)
Push a value to be compared for topk.
const std::vector< int32 > & sorted_result ()
Get sorted result from pushed values.
Detailed Description
template<typename T>
class nnfw::rt::optimized_ops::TopContainer< T >
class to define TopK operation
Note
The follwing codes are impemented and modified while referring to TFLite topk_v2.cc file. TopK_v2 of NN Runtime supports TENSOR_FLOAT32, TENSOR_QUANT8_ASYMM, TENSOR_INT32 other than TFLite. (TFLite additionaly supports kTfLiteInt64.)
The class that collects top indexes of k values. Based on template tensorflow::gtl::TopN<> but, for optimization, it re-uses the same container.
Definition at line 46 of file topk_v2.h.
Constructor & Destructor Documentation
TopContainer() [1/3]
template<typename T > nnfw::rt::optimized_ops::TopContainer< T >::TopContainer () delete
Prevent default constructor of of this class.
TopContainer() [2/3]
template<typename T > nnfw::rt::optimized_ops::TopContainer< T >::TopContainer (int32 k, int32 row_size) inline
Constructor with params.
Parameters
[in] row_size Size of row in data
[in] k The top k predictions
Definition at line 58 of file topk_v2.h.
                                        : k_(k), container_(), values_(nullptr)
  {
    container_.reserve(std::min(k, row_size) + 1);
  }
TopContainer() [3/3]
template<typename T > nnfw::rt::optimized_ops::TopContainer< T >::TopContainer (const TopContainer< T > &) delete
Prevent instances of this class from being copied (As this class contains pointers)
Parameters
[in] topContainer To copy
Member Function Documentation
operator=()
template<typename T > TopContainer & nnfw::rt::optimized_ops::TopContainer< T >::operator= (const TopContainer< T > &) delete
push()
template<typename T > void nnfw::rt::optimized_ops::TopContainer< T >::push (int32 a) inline
Push a value to be compared for topk.
Parameters
[in] a A value to compare
Returns
N/A
Definition at line 91 of file topk_v2.h.
  {
    auto comparator = [this](int32 a, int32 b) { return compare_fun(a, b); };
    if (container_.size() <= (size_t)k_)
    {
      container_.push_back(a);
      if (container_.size() == (size_t)(k_ + 1))
      {
        std::make_heap(container_.begin(), container_.end(), comparator);
        std::pop_heap(container_.begin(), container_.end(), comparator);
      }
    }
    else if (comparator(a, container_.front()))
    {
      container_.back() = a;
      std::push_heap(container_.begin(), container_.end(), comparator);
      std::pop_heap(container_.begin(), container_.end(), comparator);
    }
  }
Referenced by nnfw::rt::optimized_ops::TopK().
sorted_result()
template<typename T > const std::vector< int32 > & nnfw::rt::optimized_ops::TopContainer< T >::sorted_result () inline
Get sorted result from pushed values.
Returns
Reference of vector with sorted values
Definition at line 115 of file topk_v2.h.
  {
    auto comparator = [this](int32 a, int32 b) { return compare_fun(a, b); };
    if (container_.size() <= (size_t)(k_))
    {
      std::sort(container_.begin(), container_.end(), comparator);
    }
    else
    {
      std::sort_heap(container_.begin(), container_.end() - 1, comparator);
      container_.resize(k_);
    }
    return container_;
  }
Referenced by nnfw::rt::optimized_ops::TopK().
start_collecting()
template<typename T > void nnfw::rt::optimized_ops::TopContainer< T >::start_collecting (const T * values) inline
Start collecting.
Parameters
[in] values To set as values
Returns
N/A
Definition at line 80 of file topk_v2.h.
  {
    values_ = values;
    container_.clear();
  }
Referenced by nnfw::rt::optimized_ops::TopK().
The documentation for this class was generated from the following file:
compute/ARMComputeEx/src/runtime/topk_v2.h