ONE - On-device Neural Engine: flatbuffers::VectorOfAny Class Reference
flatbuffers::VectorOfAny Class Reference
#include <flatbuffers.h>
Public Member Functions
uoffset_t size () const
const uint8_t * Data () const
uint8_t * Data ()
Protected Member Functions
VectorOfAny ()
Protected Attributes
uoffset_t length_
Detailed Description
Definition at line 411 of file flatbuffers.h.
Constructor & Destructor Documentation
VectorOfAny()
flatbuffers::VectorOfAny::VectorOfAny () protected
Member Function Documentation
Data() [1/2]
uint8_t * flatbuffers::VectorOfAny::Data () inline
Definition at line 417 of file flatbuffers.h.
{ return reinterpret_cast<uint8_t *>(&length_ + 1); }
References length_.
Data() [2/2]
const uint8_t * flatbuffers::VectorOfAny::Data () const inline
Definition at line 416 of file flatbuffers.h.
{ return reinterpret_cast<const uint8_t *>(&length_ + 1); }
References length_.
Referenced by flatbuffers::GetAnyVectorElemAddressOf(), flatbuffers::GetAnyVectorElemF(), flatbuffers::GetAnyVectorElemI(), flatbuffers::GetAnyVectorElemPointer(), flatbuffers::GetAnyVectorElemS(), flatbuffers::SetAnyVectorElemF(), flatbuffers::SetAnyVectorElemI(), and flatbuffers::SetAnyVectorElemS().
size()
uoffset_t flatbuffers::VectorOfAny::size () const inline
Definition at line 414 of file flatbuffers.h.
{ return EndianScalar(length_); }
References length_.
Field Documentation
length_
uoffset_t flatbuffers::VectorOfAny::length_ protected
Definition at line 422 of file flatbuffers.h.
Referenced by Data(), and size().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flatbuffers.h