ONE - On-device Neural Engine: luci_interpreter::Shape Class Reference
luci_interpreter::Shape Class Reference
#include <Tensor.h>
Public Member Functions
Shape (int rank)
Shape (std::initializer_list< int32_t > dims)
int num_dims () const
int32_t dim (int i) const
int32_t & dim (int i)
int32_t num_elements () const
bool operator== (const Shape &other) const
bool operator!= (const Shape &other) const
Shape (int rank)
Shape (std::initializer_list< int32_t > dims)
int num_dims () const
int32_t dim (int i) const
int32_t & dim (int i)
int32_t num_elements () const
bool operator== (const Shape &other) const
bool operator!= (const Shape &other) const
Detailed Description
Definition at line 32 of file Tensor.h.
Constructor & Destructor Documentation
Shape() [1/4]
luci_interpreter::Shape::Shape (int rank) inline explicit
Definition at line 35 of file Tensor.h.
: _dims(rank, 0) {}
Shape() [2/4]
luci_interpreter::Shape::Shape (std::initializer_list< int32_t > dims) inline
Definition at line 37 of file Tensor.h.
: _dims(dims.begin(), dims.end()) {}
Shape() [3/4]
luci_interpreter::Shape::Shape (int rank) inline explicit
Definition at line 35 of file Tensor.h.
: _dims(rank, 0) {}
Shape() [4/4]
luci_interpreter::Shape::Shape (std::initializer_list< int32_t > dims) inline
Definition at line 37 of file Tensor.h.
: _dims(dims.begin(), dims.end()) {}
Member Function Documentation
dim() [1/4]
int32_t & luci_interpreter::Shape::dim (int i) inline
Definition at line 47 of file Tensor.h.
  {
    assert(i >= 0 && i < static_cast<int>(_dims.size()));
    return _dims[i];
  }
dim() [2/4]
int32_t & luci_interpreter::Shape::dim (int i) inline
Definition at line 47 of file Tensor.h.
  {
    assert(i >= 0 && i < static_cast<int>(_dims.size()));
    return _dims[i];
  }
dim() [3/4]
int32_t luci_interpreter::Shape::dim (int i) const inline
Definition at line 41 of file Tensor.h.
  {
    assert(i >= 0 && i < static_cast<int>(_dims.size()));
    return _dims[i];
  }
Referenced by luci_interpreter::kernels::calcOffset(), luci_interpreter::kernels::calculateShapeForBroadcast(), luci_interpreter::kernels::ArgMax::configure(), luci_interpreter::kernels::AveragePool2D::configure(), luci_interpreter::kernels::BatchToSpaceND::configure(), luci_interpreter::kernels::Concatenation::configure(), luci_interpreter::kernels::Conv2D::configure(), luci_interpreter::kernels::DepthToSpace::configure(), luci_interpreter::kernels::DepthwiseConv2D::configure(), luci_interpreter::kernels::FullyConnected::configure(), luci_interpreter::kernels::Gather::configure(), luci_interpreter::kernels::L2Pool2D::configure(), luci_interpreter::kernels::MaxPool2D::configure(), luci_interpreter::kernels::MirrorPad::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Pad::configure(), luci_interpreter::kernels::PadV2::configure(), luci_interpreter::kernels::ResizeBilinear::configure(), luci_interpreter::kernels::ResizeNearestNeighbor::configure(), luci_interpreter::kernels::SpaceToBatchND::configure(), luci_interpreter::kernels::SpaceToDepth::configure(), luci_interpreter::kernels::Split::configure(), luci_interpreter::kernels::SplitV::configure(), luci_interpreter::kernels::Squeeze::configure(), luci_interpreter::kernels::SVDF::configure(), luci_interpreter::kernels::Transpose::configure(), luci_interpreter::kernels::TransposeConv::configure(), luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure(), luci_interpreter::kernels::Unpack::configure(), luci_interpreter::kernels::testing::dequantizeTensorData(), luci_interpreter::kernels::lstm::EvalFloat(), luci_interpreter::kernels::Transpose::execute(), luci_interpreter::kernels::getTensorShape(), luci_interpreter::GraphLoader::initInputTensors(), luci_interpreter::GraphLoader::loadOperators(), luci_interpreter::GraphLoader::loadTensors(), luci_interpreter::kernels::testing::makeInputTensor(), and num_elements().
dim() [4/4]
int32_t luci_interpreter::Shape::dim (int i) const inline
Definition at line 41 of file Tensor.h.
  {
    assert(i >= 0 && i < static_cast<int>(_dims.size()));
    return _dims[i];
  }
num_dims() [1/2]
int luci_interpreter::Shape::num_dims () const inline
Definition at line 39 of file Tensor.h.
{ return _dims.size(); }
Referenced by luci_interpreter::kernels::calculateShapeForBroadcast(), luci_interpreter::kernels::ArgMax::configure(), luci_interpreter::kernels::BatchToSpaceND::configure(), luci_interpreter::kernels::Concatenation::configure(), luci_interpreter::kernels::Conv2D::configure(), luci_interpreter::kernels::DepthwiseConv2D::configure(), luci_interpreter::kernels::ExpandDims::configure(), luci_interpreter::kernels::FullyConnected::configure(), luci_interpreter::kernels::Gather::configure(), luci_interpreter::kernels::Mean::configure(), luci_interpreter::kernels::MirrorPad::configure(), luci_interpreter::kernels::OneHot::configure(), luci_interpreter::kernels::Pack::configure(), luci_interpreter::kernels::Pad::configure(), luci_interpreter::kernels::PadV2::configure(), luci_interpreter::kernels::PRelu::configure(), luci_interpreter::kernels::ReduceMax::configure(), luci_interpreter::kernels::ReduceProd::configure(), luci_interpreter::kernels::SpaceToBatchND::configure(), luci_interpreter::kernels::Split::configure(), luci_interpreter::kernels::SplitV::configure(), luci_interpreter::kernels::Squeeze::configure(), luci_interpreter::kernels::StridedSlice::configure(), luci_interpreter::kernels::SVDF::configure(), luci_interpreter::kernels::Transpose::configure(), luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure(), luci_interpreter::kernels::Unpack::configure(), luci_interpreter::kernels::testing::dequantizeTensorData(), luci_interpreter::kernels::lstm::EvalFloat(), luci_interpreter::kernels::Pad::execute(), luci_interpreter::kernels::PadV2::execute(), luci_interpreter::kernels::StridedSlice::execute(), luci_interpreter::kernels::getTensorShape(), and luci_interpreter::kernels::testing::makeInputTensor().
num_dims() [2/2]
int luci_interpreter::Shape::num_dims () const inline
Definition at line 39 of file Tensor.h.
{ return _dims.size(); }
num_elements() [1/2]
int32_t luci_interpreter::Shape::num_elements () const inline
Definition at line 53 of file Tensor.h.
  {
    int32_t result = 1;
    for (const int32_t dim : _dims)
    {
      result *= dim;
    }
    return result;
  }
References dim().
Referenced by luci_interpreter::kernels::FullyConnected::configure(), luci_interpreter::kernels::Mean::configure(), luci_interpreter::kernels::ReduceMax::configure(), luci_interpreter::kernels::ReduceProd::configure(), luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure(), luci_interpreter::kernels::testing::dequantizeTensorData(), luci_interpreter::kernels::ExpandDims::execute(), luci_interpreter::kernels::If::execute(), luci_interpreter::kernels::Reshape::execute(), luci_interpreter::kernels::testing::makeInputTensor(), luci_interpreter::Tensor::readData(), and luci_interpreter::Tensor::writeData().
num_elements() [2/2]
int32_t luci_interpreter::Shape::num_elements () const inline
Definition at line 53 of file Tensor.h.
  {
    int32_t result = 1;
    for (const int32_t dim : _dims)
    {
      result *= dim;
    }
    return result;
  }
References dim().
operator!=() [1/2]
bool luci_interpreter::Shape::operator!= (const Shape & other) const inline
Definition at line 65 of file Tensor.h.
{ return !operator==(other); }
References operator==().
operator!=() [2/2]
bool luci_interpreter::Shape::operator!= (const Shape & other) const inline
Definition at line 65 of file Tensor.h.
{ return !operator==(other); }
References operator==().
operator==() [1/2]
bool luci_interpreter::Shape::operator== (const Shape & other) const inline
Definition at line 63 of file Tensor.h.
{ return _dims == other._dims; }
Referenced by operator!=().
operator==() [2/2]
bool luci_interpreter::Shape::operator== (const Shape & other) const inline
Definition at line 63 of file Tensor.h.
{ return _dims == other._dims; }
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/core/Tensor.h
onert-micro/luci-interpreter/include/luci_interpreter/core/Tensor.h