ONE - On-device Neural Engine: exo::ShapeInferencePass Class Reference
exo::ShapeInferencePass Class Reference
Pass to infer shape of nodes.
#include <ShapeInferencePass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to infer shape of nodes.
Definition at line 29 of file ShapeInferencePass.h.
Member Function Documentation
name()
virtual const char * exo::ShapeInferencePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 32 of file ShapeInferencePass.h.
{ return "exo::ShapeInferencePass"; }
run()
bool exo::ShapeInferencePass::run (loco::Graph * g) virtual
Note
Currently, TFL and Circle backend share this inference. However, TFL backend does not require rule for Circle dialect. TODO Make dedicated inference pass for Circle Dialect.
Implements logo::Pass.
Definition at line 42 of file ShapeInferencePass.cpp.
{
  loco::CanonicalShapeInferenceRule canonical_rule;
  locoex::TFLShapeInferenceRule tfl_rule;
  locoex::CircleShapeInferenceRule circle_rule;
  locoex::COpShapeInferenceRule cop_rule;
  loco::MultiDialectShapeInferenceRule rules;
  rules.bind(loco::CanonicalDialect::get(), &canonical_rule)
    .bind(locoex::TFLDialect::get(), &tfl_rule)
    .bind(locoex::CircleDialect::get(), &circle_rule)
    .bind(locoex::COpDialect::get(), &cop_rule);
  return loco::apply(&rules).to(g);
}
References loco::apply(), loco::MultiDialectShapeInferenceRule::bind(), locoex::CircleDialect::get(), locoex::TFLDialect::get(), loco::CanonicalDialect::get(), locoex::COpDialect::get(), and loco::ShapeInferenceSession::to().
The documentation for this class was generated from the following files:
compiler/exo/src/Pass/ShapeInferencePass.h
compiler/exo/src/Pass/ShapeInferencePass.cpp