ONE - On-device Neural Engine: NNFW_SESSION Class Reference
NNFW_SESSION Class Reference
#include <nnfw_api_wrapper.h>
Public Member Functions
NNFW_SESSION (const char *package_file_path, const char *backends)
NNFW_SESSION (const char *package_file_path, const char *op, const char *backend)
~NNFW_SESSION ()
void close_session ()
void set_input_tensorinfo (uint32_t index, const tensorinfo *tensor_info)
void run ()
void run_async ()
void await ()
template<typename T >
void set_input (uint32_t index, py::array_t< T > &buffer)
process input array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
template<typename T >
void set_output (uint32_t index, py::array_t< T > &buffer)
process output array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
uint32_t input_size ()
uint32_t output_size ()
void set_input_layout (uint32_t index, const char *layout)
void set_output_layout (uint32_t index, const char *layout)
tensorinfo input_tensorinfo (uint32_t index)
tensorinfo output_tensorinfo (uint32_t index)
Detailed Description
Definition at line 112 of file nnfw_api_wrapper.h.
Constructor & Destructor Documentation
NNFW_SESSION() [1/2]
NNFW_SESSION::NNFW_SESSION (const char * package_file_path, const char * backends)
Definition at line 158 of file nnfw_api_wrapper.cc.
{
  this->session = nullptr;
  ensure_status(nnfw_create_session(&(this->session)));
  ensure_status(nnfw_load_model_from_file(this->session, package_file_path));
  ensure_status(nnfw_set_available_backends(this->session, backends));
  ensure_status(nnfw_prepare(this->session));
}
References ensure_status(), nnfw_create_session(), nnfw_load_model_from_file(), nnfw_prepare(), and nnfw_set_available_backends().
NNFW_SESSION() [2/2]
NNFW_SESSION::NNFW_SESSION (const char * package_file_path, const char * op, const char * backend)
Definition at line 166 of file nnfw_api_wrapper.cc.
{
  this->session = nullptr;
  ensure_status(nnfw_create_session(&(this->session)));
  ensure_status(nnfw_load_model_from_file(this->session, package_file_path));
  ensure_status(nnfw_set_op_backend(this->session, op, backend));
  ensure_status(nnfw_prepare(this->session));
}
References ensure_status(), nnfw_create_session(), nnfw_load_model_from_file(), nnfw_prepare(), and nnfw_set_op_backend().
~NNFW_SESSION()
NNFW_SESSION::~NNFW_SESSION ()
Definition at line 174 of file nnfw_api_wrapper.cc.
{
  if (session)
  {
    close_session();
  }
}
References close_session().
Member Function Documentation
await()
void NNFW_SESSION::await ()
Definition at line 200 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_await(session)); }
References ensure_status(), and nnfw_await().
Referenced by PYBIND11_MODULE().
close_session()
void NNFW_SESSION::close_session ()
Definition at line 182 of file nnfw_api_wrapper.cc.
{
  ensure_status(nnfw_close_session(this->session));
  this->session = nullptr;
}
References ensure_status(), and nnfw_close_session().
Referenced by ~NNFW_SESSION().
input_size()
uint32_t NNFW_SESSION::input_size ()
Definition at line 201 of file nnfw_api_wrapper.cc.
{
  uint32_t number;
  NNFW_STATUS status = nnfw_input_size(session, &number);
  ensure_status(status);
  return number;
}
References ensure_status(), and nnfw_input_size().
Referenced by PYBIND11_MODULE().
input_tensorinfo()
tensorinfo NNFW_SESSION::input_tensorinfo (uint32_t index)
Definition at line 225 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo tensor_info = nnfw_tensorinfo();
  ensure_status(nnfw_input_tensorinfo(session, index, &tensor_info));
  tensorinfo ti;
  ti.dtype = getStringType(tensor_info.dtype);
  ti.rank = tensor_info.rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info.dims[i];
  }
  return ti;
}
References nnfw_tensorinfo::dims, tensorinfo::dims, nnfw_tensorinfo::dtype, tensorinfo::dtype, ensure_status(), getStringType(), nnfw_input_tensorinfo(), NNFW_MAX_RANK, nnfw_tensorinfo::rank, and tensorinfo::rank.
Referenced by PYBIND11_MODULE(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_inputs().
output_size()
uint32_t NNFW_SESSION::output_size ()
Definition at line 208 of file nnfw_api_wrapper.cc.
{
  uint32_t number;
  NNFW_STATUS status = nnfw_output_size(session, &number);
  ensure_status(status);
  return number;
}
References ensure_status(), and nnfw_output_size().
Referenced by PYBIND11_MODULE().
output_tensorinfo()
tensorinfo NNFW_SESSION::output_tensorinfo (uint32_t index)
Definition at line 238 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo tensor_info = nnfw_tensorinfo();
  ensure_status(nnfw_output_tensorinfo(session, index, &tensor_info));
  tensorinfo ti;
  ti.dtype = getStringType(tensor_info.dtype);
  ti.rank = tensor_info.rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info.dims[i];
  }
  return ti;
}
References nnfw_tensorinfo::dims, tensorinfo::dims, nnfw_tensorinfo::dtype, tensorinfo::dtype, ensure_status(), getStringType(), NNFW_MAX_RANK, nnfw_output_tensorinfo(), nnfw_tensorinfo::rank, and tensorinfo::rank.
Referenced by PYBIND11_MODULE(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_outputs().
run()
void NNFW_SESSION::run ()
Definition at line 198 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_run(session)); }
References ensure_status(), and nnfw_run().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference(), and PYBIND11_MODULE().
run_async()
void NNFW_SESSION::run_async ()
Definition at line 199 of file nnfw_api_wrapper.cc.
{ ensure_status(nnfw_run_async(session)); }
References ensure_status(), and nnfw_run_async().
Referenced by PYBIND11_MODULE().
set_input()
template<typename T > void NNFW_SESSION::set_input (uint32_t index, py::array_t< T > & buffer) inline
process input array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
Definition at line 131 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_input_tensorinfo(this->session, index, &tensor_info);
    NNFW_TYPE type = tensor_info.dtype;
    uint32_t input_elements = num_elems(&tensor_info);
    size_t length = sizeof(T) * input_elements;
    ensure_status(nnfw_set_input(session, index, type, buffer.request().ptr, length));
  }
References nnfw_tensorinfo::dtype, ensure_status(), nnfw_input_tensorinfo(), nnfw_set_input(), and num_elems().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::set_inputs().
set_input_layout()
void NNFW_SESSION::set_input_layout (uint32_t index, const char * layout)
Definition at line 215 of file nnfw_api_wrapper.cc.
{
  NNFW_LAYOUT nnfw_layout = getLayout(layout);
  ensure_status(nnfw_set_input_layout(session, index, nnfw_layout));
}
References ensure_status(), getLayout(), and nnfw_set_input_layout().
Referenced by PYBIND11_MODULE().
set_input_tensorinfo()
void NNFW_SESSION::set_input_tensorinfo (uint32_t index, const tensorinfo * tensor_info)
Definition at line 187 of file nnfw_api_wrapper.cc.
{
  nnfw_tensorinfo ti;
  ti.dtype = getType(tensor_info->dtype);
  ti.rank = tensor_info->rank;
  for (int i = 0; i < NNFW_MAX_RANK; i++)
  {
    ti.dims[i] = tensor_info->dims[i];
  }
  ensure_status(nnfw_set_input_tensorinfo(session, index, &ti));
}
References nnfw_tensorinfo::dims, tensorinfo::dims, nnfw_tensorinfo::dtype, tensorinfo::dtype, ensure_status(), getType(), NNFW_MAX_RANK, nnfw_set_input_tensorinfo(), nnfw_tensorinfo::rank, and tensorinfo::rank.
Referenced by PYBIND11_MODULE().
set_output()
template<typename T > void NNFW_SESSION::set_output (uint32_t index, py::array_t< T > & buffer) inline
process output array according to data type of numpy array sent by Python (int, float, uint8_t, bool, int64_t, int8_t, int16_t)
Definition at line 145 of file nnfw_api_wrapper.h.
  {
    nnfw_tensorinfo tensor_info;
    nnfw_output_tensorinfo(this->session, index, &tensor_info);
    NNFW_TYPE type = tensor_info.dtype;
    uint32_t output_elements = num_elems(&tensor_info);
    size_t length = sizeof(T) * output_elements;
    ensure_status(nnfw_set_output(session, index, type, buffer.request().ptr, length));
  }
References nnfw_tensorinfo::dtype, ensure_status(), nnfw_output_tensorinfo(), nnfw_set_output(), and num_elems().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::set_outputs().
set_output_layout()
void NNFW_SESSION::set_output_layout (uint32_t index, const char * layout)
Definition at line 220 of file nnfw_api_wrapper.cc.
{
  NNFW_LAYOUT nnfw_layout = getLayout(layout);
  ensure_status(nnfw_set_output_layout(session, index, nnfw_layout));
}
References ensure_status(), getLayout(), and nnfw_set_output_layout().
Referenced by PYBIND11_MODULE().
The documentation for this class was generated from the following files:
runtime/onert/api/python/include/nnfw_api_wrapper.h
runtime/onert/api/python/src/nnfw_api_wrapper.cc