ONE - On-device Neural Engine: RandomDataGenerator.RandomDataGenerator Class Reference
RandomDataGenerator.RandomDataGenerator Class Reference
Public Member Functions
def __init__ (self, shape)
def gen (self, dtype)
Data Fields
shape
Detailed Description
Definition at line 22 of file RandomDataGenerator.py.
Constructor & Destructor Documentation
__init__()
def RandomDataGenerator.RandomDataGenerator.__init__ (self, shape)
Definition at line 23 of file RandomDataGenerator.py.
    def __init__(self, shape):
        self.shape = shape
Member Function Documentation
gen()
def RandomDataGenerator.RandomDataGenerator.gen (self, dtype)
Definition at line 38 of file RandomDataGenerator.py.
    def gen(self, dtype):
        gen_book = dict()
        gen_book[TensorType.UINT8] = self._gen_uint8
        gen_book[TensorType.INT16] = self._gen_int16
        gen_book[TensorType.FLOAT32] = self._gen_float32
        return gen_book.get(dtype, self._unsupported_types)()
References RandomDataGenerator.RandomDataGenerator._gen_float32(), RandomDataGenerator.RandomDataGenerator._gen_int16(), RandomDataGenerator.RandomDataGenerator._gen_uint8(), and RandomDataGenerator.RandomDataGenerator._unsupported_types().
Field Documentation
shape
RandomDataGenerator.RandomDataGenerator.shape
Definition at line 24 of file RandomDataGenerator.py.
The documentation for this class was generated from the following file:
compiler/dalgona-test/RandomDataGenerator.py