ONE - On-device Neural Engine: moco::PlaneInference Class Reference
moco::PlaneInference Class Reference
#include <TFShapeInferenceHelper.h>
Data Structures
struct Parameters
Public Member Functions
PlaneShape operator() (const PlaneShape &in)
void padding (const TFPadding &value)
void window (const loco::Window< 2 > value)
void stride (const loco::Stride< 2 > value)
Protected Member Functions
void fill (Parameters &p, const PlaneShape &in)
PlaneShape infer (const Parameters &p, const PlaneShape &)
Detailed Description
Definition at line 100 of file TFShapeInferenceHelper.h.
Member Function Documentation
fill()
void moco::PlaneInference::fill (Parameters & p, const PlaneShape & in) inline protected
Definition at line 113 of file TFShapeInferenceHelper.h.
  {
    p.input.height = in.height;
    p.input.width = in.width;
    p.stride.height = _stride.vertical();
    p.stride.width = _stride.horizontal();
    p.window.height = _window.vertical();
    p.window.width = _window.horizontal();
    // TODO support dilation
    p.dilation.height = 1;
    p.dilation.width = 1;
    p.effective_window.height = p.dilation.height.value() * (p.window.height.value() - 1) + 1;
    p.effective_window.width = p.dilation.width.value() * (p.window.width.value() - 1) + 1;
  }
References moco::PlaneInference::Parameters::dilation, moco::PlaneInference::Parameters::effective_window, moco::PlaneShape::height, loco::Stride< 2 >::horizontal(), loco::Window< 2 >::horizontal(), moco::PlaneInference::Parameters::input, moco::PlaneInference::Parameters::stride, loco::Dimension::value(), loco::Stride< 2 >::vertical(), loco::Window< 2 >::vertical(), moco::PlaneShape::width, and moco::PlaneInference::Parameters::window.
Referenced by operator()(), and moco::Padding2DInference::operator()().
infer()
PlaneShape moco::PlaneInference::infer (const Parameters & p, const PlaneShape &) inline protected
Definition at line 132 of file TFShapeInferenceHelper.h.
  {
    PlaneShape res;
    if (_padding == "VALID")
    {
      res.height =
        (p.input.height.value() + p.stride.height.value() - p.effective_window.height.value()) /
        p.stride.height.value();
      res.width =
        (p.input.width.value() + p.stride.width.value() - p.effective_window.width.value()) /
        p.stride.width.value();
    }
    else if (_padding == "SAME")
    {
      res.height = (p.input.height.value() + p.stride.height.value() - 1) / p.stride.height.value();
      res.width = (p.input.width.value() + p.stride.width.value() - 1) / p.stride.width.value();
    }
    else
      assert(false);
    return res;
  }
References moco::PlaneInference::Parameters::effective_window, moco::PlaneShape::height, moco::PlaneInference::Parameters::input, moco::PlaneInference::Parameters::stride, loco::Dimension::value(), and moco::PlaneShape::width.
Referenced by operator()(), and moco::Padding2DInference::operator()().
operator()()
PlaneShape moco::PlaneInference::operator() (const PlaneShape & in) inline
Definition at line 157 of file TFShapeInferenceHelper.h.
  {
    Parameters p;
    fill(p, in);
    return infer(p, in);
  }
References fill(), and infer().
padding()
void moco::PlaneInference::padding (const TFPadding & value) inline
Definition at line 167 of file TFShapeInferenceHelper.h.
{ _padding = value; }
stride()
void moco::PlaneInference::stride (const loco::Stride< 2 > value) inline
Definition at line 169 of file TFShapeInferenceHelper.h.
{ _stride = value; }
window()
void moco::PlaneInference::window (const loco::Window< 2 > value) inline
Definition at line 168 of file TFShapeInferenceHelper.h.
{ _window = value; }
The documentation for this class was generated from the following file:
compiler/moco/support/include/moco/Support/TFShapeInferenceHelper.h