ONE - On-device Neural Engine: tfkit::IOConfiguration Class Reference
tfkit::IOConfiguration Class Reference
#include <Support.hpp>
Public Member Functions
std::istream * in () const
std::ostream * out () const
void in (std::unique_ptr< std::istream > &&in)
void out (std::unique_ptr< std::ostream > &&out)
Detailed Description
Definition at line 56 of file Support.hpp.
Member Function Documentation
in() [1/2]
std::istream * tfkit::IOConfiguration::in () const inline
Definition at line 59 of file Support.hpp.
{ return _in ? _in.get() : &std::cin; }
Referenced by in().
in() [2/2]
void tfkit::IOConfiguration::in (std::unique_ptr< std::istream > && in) inline
Definition at line 63 of file Support.hpp.
{ _in = std::move(in); }
References in().
out() [1/2]
std::ostream * tfkit::IOConfiguration::out () const inline
Definition at line 60 of file Support.hpp.
{ return _out ? _out.get() : &std::cout; }
Referenced by out().
out() [2/2]
void tfkit::IOConfiguration::out (std::unique_ptr< std::ostream > && out) inline
Definition at line 64 of file Support.hpp.
{ _out = std::move(out); }
References out().
The documentation for this class was generated from the following file:
compiler/tfkit/src/Support.hpp