ONE - On-device Neural Engine: onert::ir::OperationDumper Class Reference
onert::ir::OperationDumper Class Reference
#include <OperationDumper.h>
Public Member Functions
OperationDumper (const std::string &start_msg)
void visit (const operation::ArgMinMax &) override
void visit (const operation::BatchToSpaceND &node) override
void visit (const operation::BCQFullyConnected &node) override
void visit (const operation::BinaryArithmetic &node) override
void visit (const operation::BroadcastTo &) override
void visit (const operation::Comparison &) override
void visit (const operation::Concat &node) override
void visit (const operation::Conv2D &node) override
void visit (const operation::ConvertFp16ToFp32 &node) override
void visit (const operation::ConvertFp32ToFp16 &node) override
void visit (const operation::DepthToSpace &) override
void visit (const operation::DepthwiseConv2D &node) override
void visit (const operation::ElementwiseActivation &) override
void visit (const operation::ElementwiseBinary &) override
void visit (const operation::ElementwiseUnary &) override
void visit (const operation::EmbeddingLookup &) override
void visit (const operation::ExpandDims &) override
void visit (const operation::Fill &) override
void visit (const operation::FullyConnected &node) override
void visit (const operation::Gather &) override
void visit (const operation::HashtableLookup &) override
void visit (const operation::InstanceNorm &) override
void visit (const operation::L2Normalization &) override
void visit (const operation::LocalResponseNormalization &) override
void visit (const operation::LSTM &) override
void visit (const operation::Pack &) override
void visit (const operation::Pad &) override
void visit (const operation::Permute &node) override
void visit (const operation::Pool2D &node) override
void visit (const operation::Pow &node) override
void visit (const operation::PReLU &) override
void visit (const operation::Range &) override
void visit (const operation::Rank &) override
void visit (const operation::Reduce &) override
void visit (const operation::Reshape &node) override
void visit (const operation::ResizeBilinear &) override
void visit (const operation::ResizeNearestNeighbor &) override
void visit (const operation::Reverse &) override
void visit (const operation::RNN &) override
void visit (const operation::Select &node) override
void visit (const operation::Shape &node) override
void visit (const operation::Softmax &node) override
void visit (const operation::SpaceToBatchND &) override
void visit (const operation::SpaceToDepth &) override
void visit (const operation::Split &) override
void visit (const operation::SquaredDifference &) override
void visit (const operation::Squeeze &) override
void visit (const operation::Slice &) override
void visit (const operation::StridedSlice &) override
void visit (const operation::StatelessRandomUniform &) override
void visit (const operation::Tile &) override
void visit (const operation::TopKV2 &) override
void visit (const operation::TransposeConv &) override
void visit (const operation::Transpose &) override
void visit (const operation::Unpack &) override
void visit (const operation::OneHot &) override
void visit (const operation::If &) override
void visit (const operation::While &) override
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Detailed Description
Definition at line 28 of file OperationDumper.h.
Constructor & Destructor Documentation
OperationDumper()
onert::ir::OperationDumper::OperationDumper (const std::string & start_msg)
Definition at line 60 of file OperationDumper.cc.
{
  VERBOSE(LIR) << start_msg << std::endl;
}
References VERBOSE.
Member Function Documentation
visit() [1/58]
void onert::ir::OperationDumper::visit (const operation::ArgMinMax & node) override
Definition at line 65 of file OperationDumper.cc.
{
  std::string min_max = node.param().is_arg_max ? "(Max)" : "(Min)";
  VERBOSE(LIR) << "* " << node.name() << min_max << std::endl;
  VERBOSE(LIR) << "  - Inputs : Input(" << node.getInputs().at(ArgMinMax::INPUT) << ") Axis("
               << node.getInputs().at(ArgMinMax::AXIS) << ") " << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::ArgMinMax::AXIS, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::ArgMinMax::INPUT, onert::ir::operation::ArgMinMax::Param::is_arg_max, onert::ir::Operation::name(), onert::ir::operation::ArgMinMax::param(), and VERBOSE.
visit() [2/58]
void onert::ir::OperationDumper::visit (const operation::BatchToSpaceND & node) override
Definition at line 74 of file OperationDumper.cc.
{
  std::string block_size =
    "BlockSize(" + std::to_string(node.getInputs().at(BatchToSpaceND::Input::BLOCK_SIZE).value()) +
    ")";
  dumpOpGeneric(node, block_size);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [3/58]
void onert::ir::OperationDumper::visit (const operation::BCQFullyConnected & node) override
Definition at line 82 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : IFM(" << node.getInputs().at(BCQFullyConnected::Input::INPUT)
               << ") WeightsBinary("
               << node.getInputs().at(BCQFullyConnected::Input::WEIGHTS_BINARY)
               << ") WeightsScales("
               << node.getInputs().at(BCQFullyConnected::Input::WEIGHTS_SCALES)
               << ") WeightsClusters("
               << node.getInputs().at(BCQFullyConnected::Input::WEIGHTS_CLUSTERS) << ") Bias("
               << node.getInputs().at(BCQFullyConnected::Input::BIAS) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : OFM(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and VERBOSE.
visit() [4/58]
void onert::ir::OperationDumper::visit (const operation::BinaryArithmetic & node) override
Definition at line 96 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [5/58]
void onert::ir::OperationDumper::visit (const operation::BroadcastTo & node) override
Definition at line 98 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [6/58]
void onert::ir::OperationDumper::visit (const operation::Comparison & node) override
Definition at line 100 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [7/58]
void onert::ir::OperationDumper::visit (const operation::Concat & node) override
Definition at line 102 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [8/58]
void onert::ir::OperationDumper::visit (const operation::Conv2D & node) override
Definition at line 104 of file OperationDumper.cc.
{
  std::string padding_type =
    node.param().padding.type == PaddingType::EXPLICIT ? "Explicit" : "Implicit";
  dumpConvOp(node, padding_type);
}
References onert::ir::EXPLICIT, onert::ir::operation::Conv2D::Param::padding, onert::ir::operation::Conv2D::param(), and onert::ir::Padding::type.
visit() [9/58]
void onert::ir::OperationDumper::visit (const operation::ConvertFp16ToFp32 & node) override
Definition at line 111 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [10/58]
void onert::ir::OperationDumper::visit (const operation::ConvertFp32ToFp16 & node) override
Definition at line 113 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [11/58]
void onert::ir::OperationDumper::visit (const operation::DepthToSpace & node) override
Definition at line 115 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [12/58]
void onert::ir::OperationDumper::visit (const operation::DepthwiseConv2D & node) override
Definition at line 117 of file OperationDumper.cc.
{
  std::string padding_type =
    node.param().padding.type == PaddingType::EXPLICIT ? "Explicit" : "Implicit";
  dumpConvOp(node, padding_type);
}
References onert::ir::EXPLICIT, onert::ir::operation::DepthwiseConv2D::Param::padding, onert::ir::operation::DepthwiseConv2D::param(), and onert::ir::Padding::type.
visit() [13/58]
void onert::ir::OperationDumper::visit (const operation::ElementwiseActivation & node) override
Definition at line 124 of file OperationDumper.cc.
{
  std::string params;
  if (node.param().op_type == ElementwiseActivation::Type::RELU)
  {
    params = " lower value(" + std::to_string(node.param().alpha) + ") upper value(" +
             std::to_string(node.param().beta) + ")";
  }
  else if (node.param().op_type == ElementwiseActivation::Type::LEAKY_RELU)
  {
    params = " alpha value(" + std::to_string(node.param().alpha) + ")";
  }
  dumpOpGeneric(node, params);
}
References onert::ir::operation::ElementwiseActivation::Param::alpha, onert::ir::operation::ElementwiseActivation::Param::beta, onert::ir::operation::ElementwiseActivation::Param::op_type, and onert::ir::operation::ElementwiseActivation::param().
visit() [14/58]
void onert::ir::OperationDumper::visit (const operation::ElementwiseBinary & node) override
Definition at line 139 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [15/58]
void onert::ir::OperationDumper::visit (const operation::ElementwiseUnary & node) override
Definition at line 141 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [16/58]
void onert::ir::OperationDumper::visit (const operation::EmbeddingLookup & node) override
Definition at line 143 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : Lookups(" << node.getInputs().at(EmbeddingLookup::Input::LOOKUPS)
               << ") VALUES(" << node.getInputs().at(EmbeddingLookup::Input::VALUES) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and VERBOSE.
visit() [17/58]
void onert::ir::OperationDumper::visit (const operation::ExpandDims & node) override
Definition at line 152 of file OperationDumper.cc.
{
  std::string axis =
    "AXIS(" + std::to_string(node.getInputs().at(ExpandDims::Input::AXIS).value()) + ")";
  dumpUnaryInputOp(node, axis);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [18/58]
void onert::ir::OperationDumper::visit (const operation::Fill & node) override
Definition at line 159 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : Shape(" << node.getInputs().at(Fill::Input::SHAPE) << ") Value("
               << node.getInputs().at(Fill::Input::VALUE) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and VERBOSE.
visit() [19/58]
void onert::ir::OperationDumper::visit (const operation::FullyConnected & node) override
Definition at line 167 of file OperationDumper.cc.
{
  std::string inputs =
    "Weight(" + std::to_string(node.getInputs().at(FullyConnected::Input::WEIGHT).value()) +
    ") Bias(" + std::to_string(node.getInputs().at(FullyConnected::Input::BIAS).value()) + ")";
  dumpUnaryInputOp(node, inputs);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [20/58]
void onert::ir::OperationDumper::visit (const operation::Gather & node) override
Definition at line 175 of file OperationDumper.cc.
{
  std::string indices =
    "Indices(" + std::to_string(node.getInputs().at(Gather::Input::INDICES).value()) + ")";
  dumpUnaryInputOp(node, indices);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [21/58]
void onert::ir::OperationDumper::visit (const operation::HashtableLookup & node) override
Definition at line 182 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* HashTableLookup" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Lookups(" << node.getInputs().at(HashtableLookup::Input::LOOKUPS)
               << ") Keys(" << node.getInputs().at(HashtableLookup::Input::KEYS) << ") Values("
               << node.getInputs().at(HashtableLookup::Input::VALUES) << ")" << std::endl;
  VERBOSE(LIR) << "  - Outputs : Output(" << node.getInputs().at(HashtableLookup::Output::OUTPUT)
               << ") Hits(" << node.getInputs().at(HashtableLookup::Output::HITS) << ")"
               << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and VERBOSE.
visit() [22/58]
void onert::ir::OperationDumper::visit (const operation::If & node) override
Definition at line 437 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : "
               << "Then subgraph (" << node.param().then_subg_index << ") Else subgraph ("
               << node.param().else_subg_index << ") Inputs(" << node.getInputs() << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Outputs(" << node.getOutputs() << ")" << std::endl;
}
References onert::ir::operation::If::Param::else_subg_index, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), onert::ir::operation::If::param(), onert::ir::operation::If::Param::then_subg_index, and VERBOSE.
visit() [23/58]
void onert::ir::OperationDumper::visit (const operation::InstanceNorm & node) override
Definition at line 193 of file OperationDumper.cc.
{
  std::string inputs =
    "Gamma(" + std::to_string(node.getInputs().at(InstanceNorm::Input::GAMMA).value()) + ") Beta(" +
    std::to_string(node.getInputs().at(InstanceNorm::Input::BETA).value()) + ")";
  dumpUnaryInputOp(node, inputs);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [24/58]
void onert::ir::OperationDumper::visit (const operation::L2Normalization & node) override
Definition at line 201 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [25/58]
void onert::ir::OperationDumper::visit (const operation::LocalResponseNormalization & node) override
Definition at line 203 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [26/58]
void onert::ir::OperationDumper::visit (const operation::LSTM & node) override
Definition at line 205 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR)
    << "  - Inputs : Input(" << node.getInputs().at(LSTM::Input::INPUT)
    << ") Input To Input Weights(" << node.getInputs().at(LSTM::Input::INPUT_TO_INPUT_WEIGHTS)
    << ") Input To Forget Weights(" << node.getInputs().at(LSTM::Input::INPUT_TO_FORGET_WEIGHTS)
    << ") Input To Cell Weights(" << node.getInputs().at(LSTM::Input::INPUT_TO_CELL_WEIGHTS)
    << ") Input To Output Weights(" << node.getInputs().at(LSTM::Input::INPUT_TO_OUTPUT_WEIGHTS)
    << ") Recurrent To Input Weights("
    << node.getInputs().at(LSTM::Input::RECURRENT_TO_INPUT_WEIGHTS)
    << ") Recurrent To Forget Weights("
    << node.getInputs().at(LSTM::Input::RECURRENT_TO_FORGET_WEIGHTS)
    << ") Recurrent To Cell Weights(" << node.getInputs().at(LSTM::Input::RECURRENT_TO_CELL_WEIGHTS)
    << ") Recurrent To Output Weights("
    << node.getInputs().at(LSTM::Input::RECURRENT_TO_OUTPUT_WEIGHTS) << ") Cell To Input Weights("
    << node.getInputs().at(LSTM::Input::CELL_TO_INPUT_WEIGHTS) << ") Cell To Forget Weights("
    << node.getInputs().at(LSTM::Input::CELL_TO_FORGET_WEIGHTS) << ") Cell To OUTPUT Weights("
    << node.getInputs().at(LSTM::Input::CELL_TO_OUTPUT_WEIGHTS) << ") Input Gate Bias("
    << node.getInputs().at(LSTM::Input::INPUT_GATE_BIAS) << ") Forget Gate Bias("
    << node.getInputs().at(LSTM::Input::FORGET_GATE_BIAS) << ") Cell Bias("
    << node.getInputs().at(LSTM::Input::CELL_BIAS) << ") Output Gate Bias("
    << node.getInputs().at(LSTM::Input::OUTPUT_GATE_BIAS) << ") Projection Weights("
    << node.getInputs().at(LSTM::Input::PROJECTION_WEIGHTS) << ") Projection Bias("
    << node.getInputs().at(LSTM::Input::PROJECTION_BIAS) << ") Output State In("
    << node.getInputs().at(LSTM::Input::OUTPUT_STATE_IN) << ") Cell State In("
    << node.getInputs().at(LSTM::Input::CELL_STATE_IN);
  if (node.getInputs().size() == 24)
  {
    VERBOSE(LIR) << ") Input Layer Normalization Weights("
                 << node.getInputs().at(LSTM::Input::INPUT_LAYER_NORMALIZATION_WEIGHTS)
                 << ") Forget Layer Normalization Weights("
                 << node.getInputs().at(LSTM::Input::FORGET_LAYER_NORMALIZATION_WEIGHTS)
                 << ") Cell Layer Normalization Weights("
                 << node.getInputs().at(LSTM::Input::CELL_LAYER_NORMALIZATION_WEIGHTS)
                 << ") Ouput Layer Normalization Weights("
                 << node.getInputs().at(LSTM::Input::OUTPUT_LAYER_NORMALIZATION_WEIGHTS);
  }
  VERBOSE(LIR) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : Scratch Buffer("
               << node.getOutputs().at(LSTM::Output::SCRATCH_BUFFER) << ") Output State Out("
               << node.getOutputs().at(LSTM::Output::OUTPUT_STATE_OUT) << ") Cell State Out("
               << node.getOutputs().at(LSTM::Output::CELL_STATE_OUT) << ") Output("
               << node.getOutputs().at(LSTM::Output::OUTPUT) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::LSTM::name(), onert::ir::OperandIndexSequence::size(), and VERBOSE.
visit() [27/58]
void onert::ir::OperationDumper::visit (const operation::OneHot & node) override
Definition at line 429 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : "
               << "Indices(" << node.getInputs().at(OneHot::Input::INDICES) << ") " << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and VERBOSE.
visit() [28/58]
void onert::ir::OperationDumper::visit (const operation::Pack & node) override
Definition at line 251 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [29/58]
void onert::ir::OperationDumper::visit (const operation::Pad & node) override
Definition at line 253 of file OperationDumper.cc.
{
  std::string pad = "Pad(" + std::to_string(node.getInputs().at(Pad::Input::PAD).value()) + ")";
  dumpUnaryInputOp(node, pad);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [30/58]
void onert::ir::OperationDumper::visit (const operation::Permute & node) override
Definition at line 259 of file OperationDumper.cc.
{
  std::string permute_type = "Unknown";
  switch (node.getPermuteType())
  {
    case Permute::Type::COPY:
      permute_type = "Copy";
      break;
    case Permute::Type::NHWC_TO_NCHW:
      permute_type = "NHWC to NCHW";
      break;
    case Permute::Type::NCHW_TO_NHWC:
      permute_type = "NCHW to NHWC";
      break;
  }
  VERBOSE(LIR) << "* Permute(" + permute_type + ")" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Input(" << node.getInputs().at(0) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Permute::getPermuteType(), and VERBOSE.
visit() [31/58]
void onert::ir::OperationDumper::visit (const operation::Pool2D & node) override
Definition at line 280 of file OperationDumper.cc.
{
  std::string padding_type =
    node.param().padding.type == PaddingType::EXPLICIT ? "Explicit" : "Implicit";
  VERBOSE(LIR) << "* " << node.name() << "(" << padding_type << ")" << std::endl;
  VERBOSE(LIR) << "  - Inputs : IFM(" << node.getInputs().at(Pool2D::Input::INPUT) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : OFM(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::EXPLICIT, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::Pool2D::name(), onert::ir::operation::Pool2D::Param::padding, onert::ir::operation::Pool2D::param(), onert::ir::Padding::type, and VERBOSE.
visit() [32/58]
void onert::ir::OperationDumper::visit (const operation::Pow & node) override
Definition at line 290 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [33/58]
void onert::ir::OperationDumper::visit (const operation::PReLU & node) override
Definition at line 292 of file OperationDumper.cc.
{
  std::string alpha =
    "Alpha(" + std::to_string(node.getInputs().at(PReLU::Input::ALPHA).value()) + ")";
  dumpOpGeneric(node, alpha);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [34/58]
void onert::ir::OperationDumper::visit (const operation::Range & node) override
Definition at line 337 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* Range" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Start(" << node.getInputs().at(Range::Input::START) << ")"
               << " Limit(" << node.getInputs().at(Range::Input::LIMIT) << ")"
               << " Delta(" << node.getInputs().at(Range::Input::DELTA) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and VERBOSE.
visit() [35/58]
void onert::ir::OperationDumper::visit (const operation::Rank & node) override
Definition at line 299 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [36/58]
void onert::ir::OperationDumper::visit (const operation::Reduce & node) override
Definition at line 301 of file OperationDumper.cc.
{ dumpUnaryInputOp(node); }
visit() [37/58]
void onert::ir::OperationDumper::visit (const operation::Reshape & node) override
Definition at line 303 of file OperationDumper.cc.
{
  // optional param
  std::string shape =
    node.getInputs().size() == 2
      ? "Shape(" + std::to_string(node.getInputs().at(Reshape::Input::SHAPE).value()) + ")"
      : "Shape(not provided)";
  dumpUnaryInputOp(node, shape);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::OperandIndexSequence::size(), and onert::util::Index< T, DummyTag >::value().
visit() [38/58]
void onert::ir::OperationDumper::visit (const operation::ResizeBilinear & node) override
Definition at line 313 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [39/58]
void onert::ir::OperationDumper::visit (const operation::ResizeNearestNeighbor & node) override
Definition at line 315 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [40/58]
void onert::ir::OperationDumper::visit (const operation::Reverse & node) override
Definition at line 317 of file OperationDumper.cc.
{
  std::string axis =
    "Axis(" + std::to_string(node.getInputs().at(Reverse::Input::AXIS).value()) + ")";
  dumpUnaryInputOp(node, axis);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [41/58]
void onert::ir::OperationDumper::visit (const operation::RNN & node) override
Definition at line 324 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* RNN" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Input(" << node.getInputs().at(RNN::Input::INPUT) << ") Weights("
               << node.getInputs().at(RNN::Input::WEIGHTS) << ") Recurrent Weights("
               << node.getInputs().at(RNN::Input::RECURRENT_WEIGHTS) << ") Bias("
               << node.getInputs().at(RNN::Input::BIAS) << ") Hidden State("
               << node.getInputs().at(RNN::Input::HIDDEN_STATE_IN) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(RNN::Output::OUTPUT)
               << ") Hidden State(" << node.getInputs().at(RNN::Output::HIDDEN_STATE_OUT) << ")"
               << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and VERBOSE.
visit() [42/58]
void onert::ir::OperationDumper::visit (const operation::Select & node) override
Definition at line 346 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* Select" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Condition(" << node.getInputs().at(Select::Input::CONDITION) << ")"
               << " Input_X(" << node.getInputs().at(Select::Input::INPUT_TRUE) << ")"
               << " Input_Y(" << node.getInputs().at(Select::Input::INPUT_FALSE) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and VERBOSE.
visit() [43/58]
void onert::ir::OperationDumper::visit (const operation::Shape & node) override
Definition at line 356 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [44/58]
void onert::ir::OperationDumper::visit (const operation::Slice & node) override
Definition at line 386 of file OperationDumper.cc.
{ dumpUnaryInputOp(node); }
visit() [45/58]
void onert::ir::OperationDumper::visit (const operation::Softmax & node) override
Definition at line 358 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [46/58]
void onert::ir::OperationDumper::visit (const operation::SpaceToBatchND & node) override
Definition at line 360 of file OperationDumper.cc.
{
  std::string inputs =
    "BlockSize(" + std::to_string(node.getInputs().at(SpaceToBatchND::Input::BLOCK_SIZE).value()) +
    ") Paddings(" + std::to_string(node.getInputs().at(SpaceToBatchND::Input::PADDINGS).value()) +
    ")";
  dumpUnaryInputOp(node, inputs);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [47/58]
void onert::ir::OperationDumper::visit (const operation::SpaceToDepth & node) override
Definition at line 369 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [48/58]
void onert::ir::OperationDumper::visit (const operation::Split & node) override
Definition at line 371 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [49/58]
void onert::ir::OperationDumper::visit (const operation::SquaredDifference & node) override
Definition at line 373 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [50/58]
void onert::ir::OperationDumper::visit (const operation::Squeeze & node) override
Definition at line 384 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [51/58]
void onert::ir::OperationDumper::visit (const operation::StatelessRandomUniform & node) override
Definition at line 375 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* StatelessRandomUniform" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Shape(" << node.getInputs().at(StatelessRandomUniform::Input::SHAPE)
               << " Seed(" << node.getInputs().at(StatelessRandomUniform::Input::SEED) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Output(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and VERBOSE.
visit() [52/58]
void onert::ir::OperationDumper::visit (const operation::StridedSlice & node) override
Definition at line 388 of file OperationDumper.cc.
{ dumpUnaryInputOp(node); }
visit() [53/58]
void onert::ir::OperationDumper::visit (const operation::Tile & node) override
Definition at line 390 of file OperationDumper.cc.
{
  std::string multiples =
    "Multiples(" + std::to_string(node.getInputs().at(Tile::Input::MULTIPLES).value()) + ")";
  dumpUnaryInputOp(node, multiples);
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), and onert::util::Index< T, DummyTag >::value().
visit() [54/58]
void onert::ir::OperationDumper::visit (const operation::TopKV2 & node) override
Definition at line 397 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* TopKV2" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Input(" << node.getInputs().at(TopKV2::Input::INPUT) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Outputs : Values(" << node.getOutputs().at(TopKV2::Output::OUTPUT_VALUES)
               << ") Indices(" << node.getOutputs().at(TopKV2::Output::OUTPUT_INDICES) << ")"
               << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), and VERBOSE.
visit() [55/58]
void onert::ir::OperationDumper::visit (const operation::Transpose & node) override
Definition at line 419 of file OperationDumper.cc.
{ dumpOpGeneric(node); }
visit() [56/58]
void onert::ir::OperationDumper::visit (const operation::TransposeConv & node) override
Definition at line 407 of file OperationDumper.cc.
{
  std::string padding_type =
    node.param().padding.type == PaddingType::EXPLICIT ? "Explicit" : "Implicit";
  VERBOSE(LIR) << "* TransposeConv(" << padding_type << ")" << std::endl;
  VERBOSE(LIR) << "  - Inputs : Output Shape("
               << node.getInputs().at(TransposeConv::Input::OUTPUT_SHAPE) << ") KERNEL("
               << node.getInputs().at(TransposeConv::Input::KERNEL) << ") IFM("
               << node.getInputs().at(TransposeConv::Input::INPUT) << ")" << std::endl;
  VERBOSE(LIR) << "  - Output : OFM(" << node.getOutputs().at(0) << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::EXPLICIT, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::TransposeConv::Param::padding, onert::ir::operation::TransposeConv::param(), onert::ir::Padding::type, and VERBOSE.
visit() [57/58]
void onert::ir::OperationDumper::visit (const operation::Unpack & node) override
Definition at line 421 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : Input(" << node.getInputs().at(Unpack::Input::INPUT) << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Outputs(" << node.getOutputs() << ")" << std::endl;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), and VERBOSE.
visit() [58/58]
void onert::ir::OperationDumper::visit (const operation::While & node) override
Definition at line 447 of file OperationDumper.cc.
{
  VERBOSE(LIR) << "* " << node.name() << std::endl;
  VERBOSE(LIR) << "  - Inputs : "
               << "Cond subgraph (" << node.param().cond_subg_index << ") Body subgraph ("
               << node.param().body_subg_index << ") Inputs(" << node.getInputs() << ")"
               << std::endl;
  VERBOSE(LIR) << "  - Output : Outputs(" << node.getOutputs() << ")" << std::endl;
}
References onert::ir::operation::While::Param::body_subg_index, onert::ir::operation::While::Param::cond_subg_index, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::Operation::name(), onert::ir::operation::While::param(), and VERBOSE.
The documentation for this class was generated from the following files:
runtime/onert/core/src/ir/OperationDumper.h
runtime/onert/core/src/ir/OperationDumper.cc