ONE - On-device Neural Engine: luci::OperationExporterRule Class Reference
luci::OperationExporterRule Class Reference final
#include <CircleOperationExporterRule.h>
Public Member Functions
OperationExporterRule (ExportContext &ctx)
void visit (luci::CircleNode *node) final
Default fallback.
void visit (luci::CircleConst *) final
void visit (luci::CircleInput *) final
void visit (luci::CircleOutput *) final
void visit (luci::CircleOutputDummy *) final
void visit (luci::CircleOutputExclude *) final
void visit (luci::CircleBidirectionalSequenceLSTMOut *) final
void visit (luci::CircleCustomOut *) final
void visit (luci::CircleIfOut *) final
void visit (luci::CircleNonMaxSuppressionV4Out *) final
void visit (luci::CircleNonMaxSuppressionV5Out *) final
void visit (luci::CircleSplitOut *) final
void visit (luci::CircleSplitVOut *) final
void visit (luci::CircleTopKV2Out *) final
void visit (luci::CircleUniqueOut *) final
void visit (luci::CircleUnpackOut *) final
void visit (luci::CircleVariable *) final
void visit (luci::CircleWhileOut *) final
Public Member Functions inherited from luci::CircleNodeMutableVisitor< void >
virtual ~CircleNodeMutableVisitor ()=default
virtual void visit (CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeMutableVisitorBase< T >
virtual ~CircleNodeMutableVisitorBase ()=default
Protected Attributes
ExportContext & _ctx
Detailed Description
Definition at line 36 of file CircleOperationExporterRule.h.
Constructor & Destructor Documentation
OperationExporterRule()
luci::OperationExporterRule::OperationExporterRule (ExportContext & ctx) inline
Definition at line 39 of file CircleOperationExporterRule.h.
                                            : _ctx{ctx}
  {
    // DO NOTHING
  }
Member Function Documentation
visit() [1/18]
void luci::OperationExporterRule::visit (luci::CircleBidirectionalSequenceLSTMOut *) inline final
Definition at line 57 of file CircleOperationExporterRule.h.
{}
visit() [2/18]
void luci::OperationExporterRule::visit (luci::CircleConst *) inline final
Definition at line 49 of file CircleOperationExporterRule.h.
{/* skip, everything is done in exportOpDefinedTensors */};
visit() [3/18]
void luci::OperationExporterRule::visit (luci::CircleCustomOut *) inline final
Definition at line 58 of file CircleOperationExporterRule.h.
{}
visit() [4/18]
void luci::OperationExporterRule::visit (luci::CircleIfOut *) inline final
Definition at line 59 of file CircleOperationExporterRule.h.
{}
visit() [5/18]
void luci::OperationExporterRule::visit (luci::CircleInput *) inline final
Definition at line 52 of file CircleOperationExporterRule.h.
{}
visit() [6/18]
void luci::OperationExporterRule::visit (luci::CircleNode *) final virtual
Default fallback.
Reimplemented from luci::CircleNodeMutableVisitor< void >.
Definition at line 250 of file CircleOperationExporterRule.cpp.
{
  auto op_idx = _ctx.md.registerBuiltinOpcode(circle_builtin_operator(node),
                                              circle_custom_code(node), node->op_version());
  std::vector<int32_t> inputs_vec;
  for (uint32_t i = 0; i < node->arity(); ++i)
    inputs_vec.push_back(luci::get_tensor_index(node->arg(i)));
  auto inputs = _ctx.builder.CreateVector(inputs_vec);
  OutputVectorExtractor outputs_vec_extractor;
  auto outputs_vec = node->accept(&outputs_vec_extractor);
  auto outputs = _ctx.builder.CreateVector(outputs_vec);
  auto builtin_options = circle_builtin_options(node);
  luci::BuiltinOptionsExtractor builtin_options_extractor(_ctx.builder);
  auto options_offset = node->accept(&builtin_options_extractor);
  // If node is not CircleCustom, null offset(0) is returned
  auto custom_options = circle_custom_options(_ctx.builder, node);
  auto op_offset = circle::CreateOperator(_ctx.builder, op_idx, inputs, outputs, builtin_options,
                                          options_offset, custom_options);
  _ctx.gd._operators.push_back(op_offset);
}
References _ctx, luci::SerializedGraphData::_operators, luci::CircleNode::accept(), loco::Node::arg(), loco::Node::arity(), luci::ExportContext::builder, luci::circle_builtin_operator(), luci::circle_builtin_options(), luci::circle_custom_code(), luci::circle_custom_options(), luci::ExportContext::gd, luci::get_tensor_index(), luci::ExportContext::md, luci::CircleNode::op_version(), and luci::SerializedModelData::registerBuiltinOpcode().
visit() [7/18]
void luci::OperationExporterRule::visit (luci::CircleNonMaxSuppressionV4Out *) inline final
Definition at line 60 of file CircleOperationExporterRule.h.
{}
visit() [8/18]
void luci::OperationExporterRule::visit (luci::CircleNonMaxSuppressionV5Out *) inline final
Definition at line 61 of file CircleOperationExporterRule.h.
{}
visit() [9/18]
void luci::OperationExporterRule::visit (luci::CircleOutput *) inline final
Definition at line 53 of file CircleOperationExporterRule.h.
{}
visit() [10/18]
void luci::OperationExporterRule::visit (luci::CircleOutputDummy *) inline final
Definition at line 54 of file CircleOperationExporterRule.h.
{}
visit() [11/18]
void luci::OperationExporterRule::visit (luci::CircleOutputExclude *) inline final
Definition at line 55 of file CircleOperationExporterRule.h.
{}
visit() [12/18]
void luci::OperationExporterRule::visit (luci::CircleSplitOut *) inline final
Definition at line 62 of file CircleOperationExporterRule.h.
{}
visit() [13/18]
void luci::OperationExporterRule::visit (luci::CircleSplitVOut *) inline final
Definition at line 63 of file CircleOperationExporterRule.h.
{}
visit() [14/18]
void luci::OperationExporterRule::visit (luci::CircleTopKV2Out *) inline final
Definition at line 64 of file CircleOperationExporterRule.h.
{}
visit() [15/18]
void luci::OperationExporterRule::visit (luci::CircleUniqueOut *) inline final
Definition at line 65 of file CircleOperationExporterRule.h.
{}
visit() [16/18]
void luci::OperationExporterRule::visit (luci::CircleUnpackOut *) inline final
Definition at line 66 of file CircleOperationExporterRule.h.
{}
visit() [17/18]
void luci::OperationExporterRule::visit (luci::CircleVariable *) inline final
Definition at line 67 of file CircleOperationExporterRule.h.
{}
visit() [18/18]
void luci::OperationExporterRule::visit (luci::CircleWhileOut *) inline final
Definition at line 68 of file CircleOperationExporterRule.h.
{}
Field Documentation
_ctx
ExportContext& luci::OperationExporterRule::_ctx protected
Definition at line 71 of file CircleOperationExporterRule.h.
Referenced by visit().
The documentation for this class was generated from the following files:
compiler/luci/export/src/CircleOperationExporterRule.h
compiler/luci/export/src/CircleOperationExporterRule.cpp