ONE - On-device Neural Engine: luci::Array4DIndex Class Reference
luci::Array4DIndex Class Reference final
Index class for 4D tensor to calculate linear index from multi-dimensional indices.
#include <ArrayIndex.h>
Public Member Functions
Array4DIndex (uint32_t d0, uint32_t d1, uint32_t d2, uint32_t d3)
uint32_t operator() (uint32_t i0, uint32_t i1, uint32_t i2, uint32_t i3) const
Calculate linear index from multi-dimensional indices.
uint32_t size (void) const
Get total number of elements in the tensor.
uint32_t stride (uint32_t axis) const
Get stride of the given axis.
Detailed Description
Index class for 4D tensor to calculate linear index from multi-dimensional indices.
Definition at line 26 of file ArrayIndex.h.
Constructor & Destructor Documentation
Array4DIndex()
luci::Array4DIndex::Array4DIndex (uint32_t d0, uint32_t d1, uint32_t d2, uint32_t d3)
Definition at line 29 of file ArrayIndex.cpp.
  : _dim{D0, D1, D2, D3}
{
  _strides[3] = 1;
  _strides[2] = D3;
  _strides[1] = D3 * D2;
  _strides[0] = D3 * D2 * D1;
  for (int i = 0; i < 4; ++i)
  {
    THROW_UNLESS(_strides[i] > 0);
  }
}
References luci::must_cast(), and THROW_UNLESS.
Member Function Documentation
operator()()
uint32_t luci::Array4DIndex::operator() (uint32_t i0, uint32_t i1, uint32_t i2, uint32_t i3) const
Calculate linear index from multi-dimensional indices.
Definition at line 43 of file ArrayIndex.cpp.
{
  THROW_UNLESS(i0 < _dim[0] && i1 < _dim[1] && i2 < _dim[2] && i3 < _dim[3]);
  return i0 * _strides[0] + i1 * _strides[1] + i2 * _strides[2] + i3 * _strides[3];
}
References luci::must_cast(), and THROW_UNLESS.
size()
uint32_t luci::Array4DIndex::size (void) const
Get total number of elements in the tensor.
Definition at line 50 of file ArrayIndex.cpp.
{
  for (int i = 0; i < 4; ++i)
  {
    THROW_UNLESS(_dim[i] > 0);
  }
  return _dim[0] * _dim[1] * _dim[2] * _dim[3];
}
References luci::must_cast(), and THROW_UNLESS.
stride()
uint32_t luci::Array4DIndex::stride (uint32_t axis) const
Get stride of the given axis.
Definition at line 61 of file ArrayIndex.cpp.
{ return _strides[axis]; }
The documentation for this class was generated from the following files:
compiler/luci/pass/src/helpers/ArrayIndex.h
compiler/luci/pass/src/helpers/ArrayIndex.cpp