ONE - On-device Neural Engine: onert::backend::builtin::KernelGenerator Class Reference
onert::backend::builtin::KernelGenerator Class Reference
#include <KernelGenerator.h>
Public Member Functions
KernelGenerator (const ir::Graph &graph, DynamicTensorManager *dyn_tensor_manager, const std::shared_ptr< TensorRegistry > &tensor_reg, const std::shared_ptr< ExternalContext > &external_context)
void setTensorRegistries (const compiler::TensorRegistries &tensor_registries)
void setExecutors (const std::shared_ptr< exec::IExecutors > &executors)
void setModelIndex (const ir::ModelIndex &index)
std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind) override
Public Member Functions inherited from onert::backend::basic::KernelGeneratorBase
virtual ~KernelGeneratorBase ()=default
KernelGeneratorBase (const ir::Graph &graph)
virtual std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind)=0
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Protected Member Functions inherited from onert::backend::basic::KernelGeneratorBase
std::unique_ptr< exec::IFunction > releaseFunction ()
Protected Attributes inherited from onert::backend::basic::KernelGeneratorBase
const ir::Graph & _graph
std::unique_ptr< exec::IFunction > _return_fn
Detailed Description
Definition at line 36 of file KernelGenerator.h.
Constructor & Destructor Documentation
KernelGenerator()
onert::backend::builtin::KernelGenerator::KernelGenerator (const ir::Graph & graph, DynamicTensorManager * dyn_tensor_manager, const std::shared_ptr< TensorRegistry > & tensor_reg, const std::shared_ptr< ExternalContext > & external_context)
Definition at line 32 of file KernelGenerator.cc.
  : basic::KernelGeneratorBase{graph}, _dyn_tensor_manager{dyn_tensor_manager},
    _tensor_reg{tensor_reg}, _tensor_registries{}, _executors{nullptr}, _model_index{},
    _external_context{external_context}
{
  UNUSED_RELEASE(_graph);
  UNUSED_RELEASE(_tensor_registries);
  UNUSED_RELEASE(_executors);
}
References onert::backend::basic::KernelGeneratorBase::_graph, and UNUSED_RELEASE.
Member Function Documentation
generate()
std::unique_ptr< exec::FunctionSequence > onert::backend::builtin::KernelGenerator::generate (ir::OperationIndex ind) override virtual
Implements onert::backend::basic::KernelGeneratorBase.
Definition at line 44 of file KernelGenerator.cc.
{
  assert(_dyn_tensor_manager);
  assert(_tensor_reg);
  auto ret = std::make_unique<exec::FunctionSequence>();
  // Prepare to handle dynamic tensors later
  auto dyn_ctx = std::make_shared<exec::FunctionSequence::DynamicTensorCtx>();
  {
    dyn_ctx->op = &_graph.operations().at(ind);
    dyn_ctx->dynamic_shape_inferer =
      std::make_unique<exec::DynamicShapeInferer>(_graph.operands(), _tensor_reg);
  }
  ret->dynamic_tensor_ctx(dyn_ctx);
  auto &op = _graph.operations().at(ind);
  op.accept(*this);
  assert(_return_fn); // _return_fn must have been generated
  ret->append(std::move(_return_fn));
  return ret;
}
References onert::backend::basic::KernelGeneratorBase::_graph, onert::backend::basic::KernelGeneratorBase::_return_fn, onert::util::ObjectManager< Index, Object >::at(), onert::ir::Graph::operands(), and onert::ir::Graph::operations().
setExecutors()
void onert::backend::builtin::KernelGenerator::setExecutors (const std::shared_ptr< exec::IExecutors > & executors) inline
Definition at line 47 of file KernelGenerator.h.
  {
    // FIXME Using shared_ptr's raw pointer!
    _executors = executors.get();
  }
setModelIndex()
void onert::backend::builtin::KernelGenerator::setModelIndex (const ir::ModelIndex & index) inline
Definition at line 53 of file KernelGenerator.h.
{ _model_index = index; }
setTensorRegistries()
void onert::backend::builtin::KernelGenerator::setTensorRegistries (const compiler::TensorRegistries & tensor_registries) inline
Definition at line 43 of file KernelGenerator.h.
  {
    _tensor_registries = tensor_registries;
  }
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/KernelGenerator.h
runtime/onert/core/src/backend/builtin/KernelGenerator.cc