ONE - On-device Neural Engine: onert_micro::core::memory::OMRuntimeAllocator Class Reference
onert_micro::core::memory::OMRuntimeAllocator Class Reference
#include <OMRuntimeAllocator.h>
Public Member Functions
OMRuntimeAllocator ()=default
OMRuntimeAllocator (const OMRuntimeAllocator &)=delete
OMRuntimeAllocator & operator= (const OMRuntimeAllocator &)=delete
OMRuntimeAllocator && operator= (const OMRuntimeAllocator &&)=delete
OMRuntimeAllocator (OMRuntimeAllocator &&)=default
~OMRuntimeAllocator ()=default
std::vector< std::vector< uint16_t > > & getAllocPlan ()
std::vector< std::vector< uint16_t > > & getDeallocPlan ()
OMStatus allocateGraphInputs (OMRuntimeContext *context, OMRuntimeStorage *storage)
OMStatus clearAllTensorsData (OMRuntimeContext *context, OMRuntimeStorage *storage)
OMStatus allocate (size_t kernel_index, OMRuntimeContext *context, OMRuntimeStorage *storage)
OMStatus deallocate (size_t kernel_index, OMRuntimeStorage *storage)
Detailed Description
Definition at line 34 of file OMRuntimeAllocator.h.
Constructor & Destructor Documentation
OMRuntimeAllocator() [1/3]
onert_micro::core::memory::OMRuntimeAllocator::OMRuntimeAllocator () default
OMRuntimeAllocator() [2/3]
onert_micro::core::memory::OMRuntimeAllocator::OMRuntimeAllocator (const OMRuntimeAllocator &) delete
OMRuntimeAllocator() [3/3]
onert_micro::core::memory::OMRuntimeAllocator::OMRuntimeAllocator (OMRuntimeAllocator &&) default
~OMRuntimeAllocator()
onert_micro::core::memory::OMRuntimeAllocator::~OMRuntimeAllocator () default
Member Function Documentation
allocate()
OMStatus OMRuntimeAllocator::allocate (size_t kernel_index, OMRuntimeContext * context, OMRuntimeStorage * storage)
Definition at line 57 of file OMRuntimeAllocator.cpp.
{
  assert(kernel_index < _alloc_plan.size() && "Wrong kernel index");
  if (kernel_index >= _alloc_plan.size())
    return UnknownError;
  const std::vector<uint16_t> &current_allocate_plan = _alloc_plan[kernel_index];
  for (const uint16_t tensor_index : current_allocate_plan)
  {
    const circle::Tensor *tensor = context->getTensorByIndex(tensor_index);
    const OMRuntimeShape tensor_shape(tensor);
    int32_t num_elements = tensor_shape.flatSize();
#ifndef DIS_DYN_SHAPES
    int32_t dynamic_tensor_size = storage->getDynamicRuntimeShape(tensor_index).flatSize();
    if (dynamic_tensor_size != 0)
      num_elements = dynamic_tensor_size;
#endif // DIS_DYN_SHAPES
    assert(num_elements >= 0 && "Num elements should be greater zero");
    if (num_elements < 0)
      return UnknownError;
    const auto casted_num_elements = static_cast<uint32_t>(num_elements);
    const auto type_size =
      static_cast<uint32_t>(getOMDataTypeSize(onertMicroDatatype(tensor->type())));
    if (casted_num_elements > std::numeric_limits<uint32_t>::max() / type_size)
    {
      return FailedCheckCondition;
    }
    // allocate data
    uint8_t *allocated_data = nullptr;
    assert(storage->getDataByTensorIndex(&allocated_data, tensor_index) == Ok &&
           allocated_data == nullptr && "Double allocate, memory leak");
    OMStatus status =
      OMMemoryManager::allocateMemory(casted_num_elements * type_size, &allocated_data);
    if (status != Ok)
      return status;
    storage->saveDataToTensorIndex(allocated_data, tensor_index);
  }
  return Ok;
}
References onert_micro::core::memory::OMMemoryManager::allocateMemory(), onert_micro::FailedCheckCondition, onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::core::OMRuntimeStorage::getDynamicRuntimeShape(), onert_micro::core::getOMDataTypeSize(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::Ok, onert_micro::core::onertMicroDatatype(), onert_micro::core::OMRuntimeStorage::saveDataToTensorIndex(), and onert_micro::UnknownError.
allocateGraphInputs()
OMStatus OMRuntimeAllocator::allocateGraphInputs (OMRuntimeContext * context, OMRuntimeStorage * storage)
Definition at line 177 of file OMRuntimeAllocator.cpp.
{
  OMStatus status = Ok;
  const auto &graph_inputs = context->getCircleInputs();
  for (uint32_t i = 0; i < graph_inputs->size(); ++i)
  {
    auto tensor_index = graph_inputs->operator[](i);
    const circle::Tensor *tensor = context->getTensorByIndex(tensor_index);
    const OMRuntimeShape tensor_shape(tensor);
    int32_t num_elements = tensor_shape.flatSize();
    assert(num_elements >= 0 && "Num elements should be positive");
    if (num_elements < 0)
      return UnknownError;
    const auto casted_num_elements = static_cast<uint32_t>(num_elements);
    const auto type_size =
      static_cast<uint32_t>(getOMDataTypeSize(onertMicroDatatype(tensor->type())));
    uint8_t *allocated_data = nullptr;
    // First clear if already allocated
    status = storage->getDataByTensorIndex(&allocated_data, tensor_index);
#ifdef OM_MEMORY_ESTIMATE
#ifndef DIS_DYN_SHAPES
    int32_t dynamic_tensor_size = storage->getDynamicRuntimeShape(tensor_index).flatSize();
    if (dynamic_tensor_size != 0)
      num_elements = dynamic_tensor_size;
#endif // DIS_DYN_SHAPES
    auto tensor_size = num_elements * sizeof(OMDataType(tensor->type()));
    OMMemoryManager::deallocateMemory(tensor_size, allocated_data);
#else
    OMMemoryManager::deallocateMemory(allocated_data);
#endif // OM_MEMORY_ESTIMATE
    // Then Allocate
    status = OMMemoryManager::allocateMemory(casted_num_elements * type_size, &allocated_data);
    if (status != Ok)
      return status;
    storage->saveDataToTensorIndex(allocated_data, tensor_index);
  }
  return status;
}
References onert_micro::core::memory::OMMemoryManager::allocateMemory(), onert_micro::core::memory::OMMemoryManager::deallocateMemory(), onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeContext::getCircleInputs(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::core::OMRuntimeStorage::getDynamicRuntimeShape(), onert_micro::core::getOMDataTypeSize(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::Ok, onert_micro::core::onertMicroDatatype(), onert_micro::core::OMRuntimeStorage::saveDataToTensorIndex(), and onert_micro::UnknownError.
Referenced by onert_micro::core::OMRuntimeGraph::allocateGraphInputs(), and onert_micro::core::OMRuntimeGraph::getInputDataAt().
clearAllTensorsData()
OMStatus OMRuntimeAllocator::clearAllTensorsData (OMRuntimeContext * context, OMRuntimeStorage * storage)
Definition at line 26 of file OMRuntimeAllocator.cpp.
{
  auto &tensor_index_to_data = storage->getTensorIndexToData();
  for (auto &cur_tensor_index_data : tensor_index_to_data)
  {
    uint8_t *allocated_data = cur_tensor_index_data.second;
#ifdef OM_MEMORY_ESTIMATE
    auto tensor_index = cur_tensor_index_data.first;
    auto tensor = context->getTensorByIndex(tensor_index);
    auto num_elements = OMRuntimeShape(tensor).flatSize();
#ifndef DIS_DYN_SHAPES
    int32_t dynamic_tensor_size = storage->getDynamicRuntimeShape(tensor_index).flatSize();
    if (dynamic_tensor_size != 0)
      num_elements = dynamic_tensor_size;
#endif // DIS_DYN_SHAPES
    auto tensor_size = num_elements * sizeof(OMDataType(tensor->type()));
    OMMemoryManager::deallocateMemory(tensor_size, allocated_data);
#else
    OMMemoryManager::deallocateMemory(allocated_data);
#endif // OM_MEMORY_ESTIMATE
  }
  return Ok;
}
References onert_micro::core::memory::OMMemoryManager::deallocateMemory(), onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeStorage::getDynamicRuntimeShape(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::core::OMRuntimeStorage::getTensorIndexToData(), and onert_micro::Ok.
Referenced by onert_micro::core::OMRuntimeGraph::reset().
deallocate()
OMStatus OMRuntimeAllocator::deallocate (size_t kernel_index, OMRuntimeStorage * storage)
Definition at line 148 of file OMRuntimeAllocator.cpp.
{
  assert(kernel_index < _alloc_plan.size() && "Wrong kernel index");
  if (kernel_index >= _alloc_plan.size())
    return UnknownError;
  const std::vector<uint16_t> &current_deallocate_plan = _dealloc_plan[kernel_index];
  for (const uint16_t tensor_index : current_deallocate_plan)
  {
    uint8_t *allocated_data = nullptr;
    OMStatus status = storage->getDataByTensorIndex(&allocated_data, tensor_index);
    assert(status == Ok); // note that status always 0
    // To continue deallocate due to current tensor is not saved in storage
    if (allocated_data == nullptr)
      continue;
    status = OMMemoryManager::deallocateMemory(allocated_data);
    assert(status == Ok); // note that status always 0
    status = storage->removeTensorFromTensorIndexToData(tensor_index);
    if (status != Ok)
      return status;
  }
  return Ok;
}
References onert_micro::core::memory::OMMemoryManager::deallocateMemory(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::Ok, onert_micro::core::OMRuntimeStorage::removeTensorFromTensorIndexToData(), and onert_micro::UnknownError.
getAllocPlan()
std::vector< std::vector< uint16_t > > & onert_micro::core::memory::OMRuntimeAllocator::getAllocPlan () inline
Definition at line 48 of file OMRuntimeAllocator.h.
{ return _alloc_plan; }
getDeallocPlan()
std::vector< std::vector< uint16_t > > & onert_micro::core::memory::OMRuntimeAllocator::getDeallocPlan () inline
Definition at line 50 of file OMRuntimeAllocator.h.
{ return _dealloc_plan; }
operator=() [1/2]
OMRuntimeAllocator && onert_micro::core::memory::OMRuntimeAllocator::operator= (const OMRuntimeAllocator &&) delete
operator=() [2/2]
OMRuntimeAllocator & onert_micro::core::memory::OMRuntimeAllocator::operator= (const OMRuntimeAllocator &) delete
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/memory/OMRuntimeAllocator.h
onert-micro/onert-micro/src/core/memory/OMRuntimeAllocator.cpp