ONE - On-device Neural Engine: mir::ops::MaxPool2DOp Class Reference
mir::ops::MaxPool2DOp Class Reference
#include <MaxPool2DOp.h>
Public Member Functions
MaxPool2DOp (Output *arg, const MaxPool2DOpAttributes &attributes)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
const std::vector< std::int32_t > & getWindowSize () const
const std::vector< std::int32_t > & getStrides () const
const std::vector< std::int32_t > & getPaddingBefore () const
const std::vector< std::int32_t > & getPaddingAfter () const
DataFormat getDataFormat () const
const MaxPool2DOpAttributes & getAttributes () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 31 of file MaxPool2DOp.h.
Constructor & Destructor Documentation
MaxPool2DOp()
mir::ops::MaxPool2DOp::MaxPool2DOp (Output * arg, const MaxPool2DOpAttributes & attributes) inline
Definition at line 34 of file MaxPool2DOp.h.
    : Operation(Type::maxPool2D, {arg}), _attributes(attributes)
  {
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::MaxPool2DOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 40 of file MaxPool2DOp.h.
  {
    return new MaxPool2DOp(inputs[0], _attributes);
  };
getAttributes()
const MaxPool2DOpAttributes & mir::ops::MaxPool2DOp::getAttributes () const inline
Definition at line 55 of file MaxPool2DOp.h.
{ return _attributes; }
getDataFormat()
DataFormat mir::ops::MaxPool2DOp::getDataFormat () const inline
Definition at line 53 of file MaxPool2DOp.h.
{ return _attributes.data_format; }
References mir::MaxPool2DOpAttributes::data_format.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getPaddingAfter()
const std::vector< std::int32_t > & mir::ops::MaxPool2DOp::getPaddingAfter () const inline
Definition at line 51 of file MaxPool2DOp.h.
{ return _attributes.padding_after; }
References mir::MaxPool2DOpAttributes::padding_after.
Referenced by mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getPaddingBefore()
const std::vector< std::int32_t > & mir::ops::MaxPool2DOp::getPaddingBefore () const inline
Definition at line 49 of file MaxPool2DOp.h.
{ return _attributes.padding_before; }
References mir::MaxPool2DOpAttributes::padding_before.
Referenced by mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getStrides()
const std::vector< std::int32_t > & mir::ops::MaxPool2DOp::getStrides () const inline
Definition at line 47 of file MaxPool2DOp.h.
{ return _attributes.strides; }
References mir::MaxPool2DOpAttributes::strides.
Referenced by mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir2loco::Transformer::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
getWindowSize()
const std::vector< std::int32_t > & mir::ops::MaxPool2DOp::getWindowSize () const inline
Definition at line 45 of file MaxPool2DOp.h.
{ return _attributes.window; }
References mir::MaxPool2DOpAttributes::window.
Referenced by mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir2loco::Transformer::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/MaxPool2DOp.h
compiler/mir/src/ops/MaxPool2DOp.cpp