ONE - On-device Neural Engine: coco::ConcatF Class Reference
coco::ConcatF Class Reference final
Concatenate two feature maps.
#include <Ops.h>
Public Types
enum class Axis {
Unknown = 0 , Batch = 1 , Depth = 2 , Height = 3 ,
Width = 4
}
Public Member Functions
ConcatF ()=default
ConcatF (const ConcatF &)=delete
ConcatF (ConcatF &&)=delete
ConcatF * asConcatF (void) override
const ConcatF * asConcatF (void) const override
const Axis & axis (void) const
void axis (const Axis &axis)
Public Member Functions inherited from coco::BinaryOp
BinaryOp ()
BinaryOp (const BinaryOp &)=delete
BinaryOp (BinaryOp &&)=delete
virtual ~BinaryOp ()=default
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const final
Return a set of object(s) used during execution.
Op * left (void) const
void left (Op *op)
Op * right (void) const
void right (Op *op)
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Detailed Description
Concatenate two feature maps.
ConcatF(L, R) requires
Definition at line 362 of file Ops.h.
Member Enumeration Documentation
Axis
enum class coco::ConcatF::Axis strong
Enumerator
Unknown
Batch
Depth
Height
Width
Definition at line 365 of file Ops.h.
  {
    Unknown = 0,
    Batch = 1,
    Depth = 2,
    Height = 3,
    Width = 4,
  };
Constructor & Destructor Documentation
ConcatF() [1/3]
coco::ConcatF::ConcatF () explicit default
ConcatF() [2/3]
coco::ConcatF::ConcatF (const ConcatF &) delete
ConcatF() [3/3]
coco::ConcatF::ConcatF (ConcatF &&) delete
Member Function Documentation
asConcatF() [1/2]
const ConcatF * coco::ConcatF::asConcatF (void) const inline override
Definition at line 383 of file Ops.h.
{ return this; }
asConcatF() [2/2]
ConcatF * coco::ConcatF::asConcatF (void) inline override
Definition at line 382 of file Ops.h.
{ return this; }
axis() [1/2]
void coco::ConcatF::axis (const Axis & axis) inline
Definition at line 387 of file Ops.h.
{ _axis = axis; }
References axis().
Referenced by axis().
axis() [2/2]
const Axis & coco::ConcatF::axis (void) const inline
Definition at line 386 of file Ops.h.
{ return _axis; }
Referenced by caffeimport::ConcatBuilder::build(), and tflimport::ConcatenationGraphBuilder::build().
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/IR/Ops.h