ONE - On-device Neural Engine: luci::CircleInstanceNorm Class Reference
luci::CircleInstanceNorm Class Reference final
INSTANCE_NORM in Circle.
#include <CircleInstanceNorm.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * gamma (void) const
void gamma (loco::Node *node)
loco::Node * beta (void) const
void beta (loco::Node *node)
float epsilon () const
void epsilon (float epsilon)
Public Member Functions inherited from luci::FixedArityNode< N, Base >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< N, Base >
loco::Use * at (uint32_t n) const
Detailed Description
INSTANCE_NORM in Circle.
Definition at line 32 of file CircleInstanceNorm.h.
Member Function Documentation
beta() [1/2]
void luci::CircleInstanceNorm::beta (loco::Node * node) inline
Definition at line 45 of file CircleInstanceNorm.h.
{ at(2)->node(node); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
beta() [2/2]
loco::Node * luci::CircleInstanceNorm::beta (void) const inline
Definition at line 44 of file CircleInstanceNorm.h.
{ return at(2)->node(); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
epsilon() [1/2]
float luci::CircleInstanceNorm::epsilon () const inline
Definition at line 48 of file CircleInstanceNorm.h.
{ return _epsilon; }
Referenced by luci::CloneNode::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
epsilon() [2/2]
void luci::CircleInstanceNorm::epsilon (float epsilon) inline
Definition at line 49 of file CircleInstanceNorm.h.
{ _epsilon = epsilon; }
References epsilon().
Referenced by epsilon().
gamma() [1/2]
void luci::CircleInstanceNorm::gamma (loco::Node * node) inline
Definition at line 42 of file CircleInstanceNorm.h.
{ at(1)->node(node); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
gamma() [2/2]
loco::Node * luci::CircleInstanceNorm::gamma (void) const inline
Definition at line 41 of file CircleInstanceNorm.h.
{ return at(1)->node(); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
input() [1/2]
void luci::CircleInstanceNorm::input (loco::Node * node) inline
Definition at line 39 of file CircleInstanceNorm.h.
{ at(0)->node(node); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleInstanceNorm::input (void) const inline
Note
Currently only support FLOAT32 as input node
Definition at line 38 of file CircleInstanceNorm.h.
{ return at(0)->node(); }
References luci::FixedArityNode< N, Base >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleInstanceNorm.h