ONE - On-device Neural Engine: onert::backend::cpu::ops::PoolLayer Class Reference
onert::backend::cpu::ops::PoolLayer Class Reference
#include <PoolLayer.h>
Public Member Functions
PoolLayer ()
void configure (const IPortableTensor *input, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t kernelWidth, const uint32_t kernelHeight, const ir::Activation activation, IPortableTensor *output, const PoolType op_type)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Protected Attributes
const IPortableTensor * _input
IPortableTensor * _output
Detailed Description
Definition at line 41 of file PoolLayer.h.
Constructor & Destructor Documentation
PoolLayer()
onert::backend::cpu::ops::PoolLayer::PoolLayer ()
Definition at line 70 of file PoolLayer.cc.
                     : _input(nullptr), _output(nullptr), _kernel()
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::PoolLayer::configure (const IPortableTensor * input, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t kernelWidth, const uint32_t kernelHeight, const ir::Activation activation, IPortableTensor * output, const PoolType op_type)
Definition at line 88 of file PoolLayer.cc.
{
  assert(input != nullptr);
  assert(output != nullptr);
  _input = input;
  _output = output;
  POOLING_PARAMETERS
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
    {
      float output_activation_min = 0;
      float output_activation_max = 0;
      CalculateActivationRange<float>(activation, &output_activation_min, &output_activation_max);
      op_params.float_activation_min = output_activation_min;
      op_params.float_activation_max = output_activation_max;
      _kernel = generateKernelGeneric<float>(op_params, op_type);
      break;
    }
    case OperandType::QUANT_UINT8_ASYMM:
    {
      int32_t output_activation_min = 0;
      int32_t output_activation_max = 0;
      CalculateActivationRangeQuantized(activation, _output, &output_activation_min,
                                        &output_activation_max);
      op_params.quantized_activation_min = output_activation_min;
      op_params.quantized_activation_max = output_activation_max;
      _kernel = generateKernelGeneric<uint8_t>(op_params, op_type);
      break;
    }
    case OperandType::QUANT_INT8_ASYMM:
    {
      int32_t output_activation_min = 0;
      int32_t output_activation_max = 0;
      CalculateActivationRangeQuantized(activation, _output, &output_activation_min,
                                        &output_activation_max);
      op_params.quantized_activation_min = output_activation_min;
      op_params.quantized_activation_max = output_activation_max;
      _kernel = generateKernelGeneric<int8_t>(op_params, op_type);
      break;
    }
    default:
      throw std::runtime_error{"Pool: unsupported data type"};
  }
}
References _input, _output, onert::backend::cpu::ops::CalculateActivationRangeQuantized(), onert::backend::ITensor::data_type(), and POOLING_PARAMETERS.
Referenced by onert::backend::train::ops::PoolLayer::configure().
run()
void onert::backend::cpu::ops::PoolLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 142 of file PoolLayer.cc.
{ _kernel(_input, _output); }
References _input, and _output.
Referenced by onert::backend::train::ops::PoolLayer::forward(), and package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
Field Documentation
_input
const IPortableTensor* onert::backend::cpu::ops::PoolLayer::_input protected
Definition at line 57 of file PoolLayer.h.
Referenced by configure(), onert::backend::train::ops::PoolLayer::configure(), onert::backend::train::ops::PoolLayer::forward(), and run().
_output
IPortableTensor* onert::backend::cpu::ops::PoolLayer::_output protected
Definition at line 58 of file PoolLayer.h.
Referenced by configure(), onert::backend::train::ops::PoolLayer::configure(), onert::backend::train::ops::PoolLayer::forward(), and run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/PoolLayer.h
runtime/onert/backend/cpu/ops/PoolLayer.cc