ONE - On-device Neural Engine: luci::RequantizePass Class Reference
luci::RequantizePass Class Reference
Pass to quantize weights.
#include <RequantizePass.h>
Public Member Functions
RequantizePass (loco::DataType input_dtype, loco::DataType output_dtype)
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to quantize weights.
Definition at line 32 of file RequantizePass.h.
Constructor & Destructor Documentation
RequantizePass()
luci::RequantizePass::RequantizePass (loco::DataType input_dtype, loco::DataType output_dtype) inline
Definition at line 35 of file RequantizePass.h.
    : _input_dtype{input_dtype}, _output_dtype{output_dtype}
  {
    // DO NOTHING
  }
Member Function Documentation
name()
virtual const char * luci::RequantizePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 40 of file RequantizePass.h.
{ return "luci::RequantizePass"; }
run()
bool luci::RequantizePass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 205 of file RequantizePass.cpp.
{
  LOGGER(l);
  INFO(l) << "RequantizePass Start" << std::endl;
  // Requantize non-const (activations)
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    RequantizeNonConst rqnc(_input_dtype, _output_dtype);
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    circle_node->accept(&rqnc);
  }
  // Requantize const (including weights, constants)
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    RequantizeConst rqc(_input_dtype, _output_dtype);
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    circle_node->accept(&rqc);
  }
  // Update output dtype
  auto graph_outputs = g->outputs();
  for (auto node : loco::output_nodes(g))
  {
    auto circle_node = loco::must_cast<luci::CircleOutput *>(node);
    if (static_cast<luci::CircleNode *>(circle_node->from())->dtype() == _output_dtype)
    {
      circle_node->dtype(_output_dtype);
      auto graph_output = graph_outputs->at(circle_node->index());
      graph_output->dtype(_output_dtype);
    }
  }
  INFO(l) << "RequantizePass End" << std::endl;
  return false; // one time run
}
References loco::active_nodes(), INFO, LOGGER, and loco::output_nodes().
Referenced by luci::CircleQuantizer::quantize().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/RequantizePass.h
compiler/luci/pass/src/RequantizePass.cpp