ONE - On-device Neural Engine: arm_compute::NEGatherKernelEx Class Reference
arm_compute::NEGatherKernelEx Class Reference
#include <NEGatherKernelEx.h>
Public Member Functions
NEGatherKernelEx ()
NEGatherKernelEx (const NEGatherKernelEx &)=delete
NEGatherKernelEx & operator= (const NEGatherKernelEx &)=delete
NEGatherKernelEx (NEGatherKernelEx &&)=default
NEGatherKernelEx & operator= (NEGatherKernelEx &&)=default
~NEGatherKernelEx ()=default
const char * name () const override
void configure (const ITensor *input, const ITensor *indices, ITensor *output, int axis=0)
void run (const Window &window, const ThreadInfo &info) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, int axis)
Detailed Description
Kernel to perform other operation on NEON
Definition at line 52 of file NEGatherKernelEx.h.
Constructor & Destructor Documentation
NEGatherKernelEx() [1/3]
arm_compute::NEGatherKernelEx::NEGatherKernelEx ()
Default constructor.
Definition at line 76 of file NEGatherKernelEx.cpp.
  : _input{}, _indices{}, _axis{}, _indices_rank{}, _output{}, _func{}
{
}
NEGatherKernelEx() [2/3]
arm_compute::NEGatherKernelEx::NEGatherKernelEx (const NEGatherKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers).
NEGatherKernelEx() [3/3]
arm_compute::NEGatherKernelEx::NEGatherKernelEx (NEGatherKernelEx &&) default
Allow instances of this class to be moved.
~NEGatherKernelEx()
arm_compute::NEGatherKernelEx::~NEGatherKernelEx () default
Default detructor
Member Function Documentation
configure()
void arm_compute::NEGatherKernelEx::configure (const ITensor * input, const ITensor * indices, ITensor * output, int axis = 0)
Initialise the kernel's inputs and outputs
Parameters
[in] input Source tensor. Supported tensor rank: up to 4. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] indices Indices tensor. Supported tensor rank: up to 3. Must be one of the following type: U32/S32. Each value Must be in range [0, input.shape[axis])
[out] output Destination tensor. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Definition at line 167 of file NEGatherKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, indices);
  ARM_COMPUTE_ERROR_ON(indices->info()->num_dimensions() > 3);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(indices, 1, DataType::U32, DataType::S32);
  ARM_COMPUTE_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(
    input, 1, DataType::U8, DataType::S8, DataType::QASYMM8, DataType::U16, DataType::S16,
    DataType::U32, DataType::S32, DataType::F16, DataType::F32);
  _input = input;
  _indices = indices;
  _output = output;
  _axis = axis;
  _indices_rank = indices->info()->num_dimensions();
  if (_axis < 0)
  {
    _axis += input->info()->num_dimensions();
  }
  ARM_COMPUTE_ERROR_ON(0 > _axis || _axis >= static_cast<int32_t>(input->info()->num_dimensions()));
  if (0 == _axis)
  {
    switch (_indices->info()->data_type())
    {
      case DataType::U32:
        _func = &NEGatherKernelEx::gather_0_axis<uint32_t>;
        break;
      case DataType::S32:
        _func = &NEGatherKernelEx::gather_0_axis<int32_t>;
        break;
      default:
        ARM_COMPUTE_ERROR("Not supported");
        break;
    }
  }
  else
  {
    switch (_indices->info()->data_type())
    {
      case DataType::U32:
        _func = &NEGatherKernelEx::gather_n_axis<uint32_t>;
        break;
      case DataType::S32:
        _func = &NEGatherKernelEx::gather_n_axis<int32_t>;
        break;
      default:
        ARM_COMPUTE_ERROR("Not supported");
        break;
    }
  }
  // Output auto initialization if not yet initialized
  TensorShape output_shape = arm_compute::misc::shape_calculator::compute_gather_shape_ex(
    input->info()->tensor_shape(), indices->info()->tensor_shape(), _axis);
  auto_init_if_empty(*output->info(), output_shape, 1, input->info()->data_type());
  // Create window
  Window win = calculate_max_window(*output->info(), Steps());
  output->info()->set_valid_region(ValidRegion(Coordinates(), output->info()->tensor_shape()));
  INEKernel::configure(win);
}
References arm_compute::misc::shape_calculator::compute_gather_shape_ex().
name()
const char * arm_compute::NEGatherKernelEx::name () const inline override
Name of the kernel
Returns
Kernel name
Definition at line 72 of file NEGatherKernelEx.h.
{ return "NEGatherKernelEx"; }
operator=() [1/2]
NEGatherKernelEx & arm_compute::NEGatherKernelEx::operator= (const NEGatherKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers).
operator=() [2/2]
NEGatherKernelEx & arm_compute::NEGatherKernelEx::operator= (NEGatherKernelEx &&) default
Allow instances of this class to be moved.
run()
void arm_compute::NEGatherKernelEx::run (const Window & window, const ThreadInfo & info) override
Definition at line 264 of file NEGatherKernelEx.cpp.
{
  ARM_COMPUTE_UNUSED(info);
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON(_func == nullptr);
  (this->*_func)(window, info);
}
References info.
validate()
Status arm_compute::NEGatherKernelEx::validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, int axis) static
Static function to check if given info will lead to a valid configuration of NEGatherKernelEx
Parameters
[in] input Source tensor info. Supported tensor rank: up to 4. Data type supported: U8/S8/QASYMM8/U16/S16/U32/S32/F16/F32
[in] indices Indices tensor info. Supported tensor rank: up to 3. Must be one of the following type: U32/S32. Each value Must be in range [0, input.shape[axis])
[in] output Destination tensor info. Data type supported: Same as input
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Returns
a status
Definition at line 231 of file NEGatherKernelEx.cpp.
{
  ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, indices, output);
  ARM_COMPUTE_RETURN_ERROR_ON(indices->num_dimensions() > 3);
  ARM_COMPUTE_RETURN_ERROR_ON(input->num_dimensions() > 4);
  ARM_COMPUTE_ERROR_ON(input->num_dimensions() + indices->num_dimensions() - 1 > 4);
  if (axis < 0)
  {
    axis += input->num_dimensions();
  }
  ARM_COMPUTE_RETURN_ERROR_ON(0 > axis || axis >= static_cast<int32_t>(input->num_dimensions()));
  ARM_COMPUTE_RETURN_ERROR_ON_CPU_F16_UNSUPPORTED(input);
  ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(
    input, 1, DataType::U8, DataType::S8, DataType::QASYMM8, DataType::U16, DataType::S16,
    DataType::U32, DataType::S32, DataType::F16, DataType::F32);
  if (output->total_size() != 0)
  {
    ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(input, output);
    ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_QUANTIZATION_INFO(input, output);
    TensorShape output_shape = arm_compute::misc::shape_calculator::compute_gather_shape_ex(
      input->tensor_shape(), indices->tensor_shape(), axis);
    ARM_COMPUTE_RETURN_ERROR_ON(output_shape.total_size() != output->tensor_shape().total_size());
  }
  ARM_COMPUTE_RETURN_ERROR_ON_DATA_TYPE_CHANNEL_NOT_IN(indices, 1, DataType::U32, DataType::S32);
  return Status{};
}
References arm_compute::misc::shape_calculator::compute_gather_shape_ex().
Referenced by arm_compute::NEGatherEx::validate().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEGatherKernelEx.h
compute/ARMComputeEx/src/core/NEON/kernels/NEGatherKernelEx.cpp