ONE - On-device Neural Engine: onert::backend::cpu::ops::PadLayer Class Reference
onert::backend::cpu::ops::PadLayer Class Reference
#include <PadLayer.h>
Public Member Functions
PadLayer ()
template<typename T >
void padImpl (const T *constant_value_data)
void configure (const IPortableTensor *input, const IPortableTensor *pad, const IPortableTensor *value, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Protected Attributes
const IPortableTensor * _input
const IPortableTensor * _pad
const IPortableTensor * _value
IPortableTensor * _output
ConstDataPtr _constantValueData
Detailed Description
Definition at line 36 of file PadLayer.h.
Constructor & Destructor Documentation
PadLayer()
onert::backend::cpu::ops::PadLayer::PadLayer ()
Definition at line 30 of file PadLayer.cc.
  : _input(nullptr), _pad(nullptr), _value(nullptr), _output(nullptr), _constantValueData()
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::PadLayer::configure (const IPortableTensor * input, const IPortableTensor * pad, const IPortableTensor * value, IPortableTensor * output)
Definition at line 46 of file PadLayer.cc.
{
  _input = input;
  _pad = pad;
  _value = value;
  _output = output;
}
References _input, _output, _pad, and _value.
Referenced by onert::backend::train::ops::PadLayer::configure().
padImpl()
template<typename T > void onert::backend::cpu::ops::PadLayer::padImpl (const T * constant_value_data)
Definition at line 36 of file PadLayer.cc.
{
  assert(_pad->data_type() == onert::ir::DataType::INT32);
  assert(_pad->buffer());
  const auto pad_data = reinterpret_cast<const int32_t *>(_pad->buffer());
  auto pad_rank = _pad->getShape().dim(0);
  nnfw::cker::Pad<T>(pad_data, pad_rank, getShape(_input), getBuffer<T>(_input), getShape(_output),
                     getBuffer<T>(_output), constant_value_data);
}
References _input, _output, _pad, onert::backend::ITensor::buffer(), onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), and onert::backend::cpu::ops::getShape().
run()
void onert::backend::cpu::ops::PadLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 55 of file PadLayer.cc.
{
  if (_value != nullptr) // isPadV2
  {
    assert(_value->buffer());
    _constantValueData.v = reinterpret_cast<const void *>(_value->buffer());
  }
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
      padImpl<float>(_constantValueData.f);
      break;
    case OperandType::QUANT_UINT8_ASYMM:
      if (_constantValueData.u8 == nullptr)
      {
        uint8_t pad_value = static_cast<uint8_t>(_output->data_zero_point());
        padImpl<uint8_t>(&pad_value);
      }
      else
      {
        padImpl<uint8_t>(_constantValueData.u8);
      }
      break;
    case OperandType::QUANT_INT8_ASYMM:
      if (_constantValueData.i8 == nullptr)
      {
        int8_t pad_value = static_cast<int8_t>(_output->data_zero_point());
        padImpl<int8_t>(&pad_value);
      }
      else
      {
        padImpl<int8_t>(_constantValueData.i8);
      }
      break;
    default:
      throw std::runtime_error{"Pad: unsupported data type"};
  }
}
References _constantValueData, _input, _output, _value, onert::backend::ITensor::buffer(), onert::backend::ITensor::data_type(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::cpu::ops::ConstDataPtr::f, onert::backend::cpu::ops::ConstDataPtr::i8, onert::backend::cpu::ops::ConstDataPtr::u8, and onert::backend::cpu::ops::ConstDataPtr::v.
Referenced by onert::backend::train::ops::PadLayer::forward(), and package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
Field Documentation
_constantValueData
ConstDataPtr onert::backend::cpu::ops::PadLayer::_constantValueData protected
Definition at line 54 of file PadLayer.h.
Referenced by run().
_input
const IPortableTensor* onert::backend::cpu::ops::PadLayer::_input protected
Definition at line 50 of file PadLayer.h.
Referenced by configure(), padImpl(), and run().
_output
IPortableTensor* onert::backend::cpu::ops::PadLayer::_output protected
Definition at line 53 of file PadLayer.h.
Referenced by configure(), padImpl(), and run().
_pad
const IPortableTensor* onert::backend::cpu::ops::PadLayer::_pad protected
Definition at line 51 of file PadLayer.h.
Referenced by configure(), onert::backend::train::ops::PadLayer::depad(), and padImpl().
_value
const IPortableTensor* onert::backend::cpu::ops::PadLayer::_value protected
Definition at line 52 of file PadLayer.h.
Referenced by configure(), and run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/PadLayer.h
runtime/onert/backend/cpu/ops/PadLayer.cc