ONE - On-device Neural Engine: nnc::ConstantFoldTranspose Class Reference
nnc::ConstantFoldTranspose Class Reference
#include <ConstantFoldTranspose.h>
Public Member Functions
PassData run (PassData data) override
run compiler pass
std::string getName () override
Public Member Functions inherited from nnc::Pass
virtual PassData run (PassData data)=0
run compiler pass
virtual void cleanup ()
clean compiler pass data
virtual ~Pass ()=default
virtual std::string getName ()
Detailed Description
Definition at line 25 of file ConstantFoldTranspose.h.
Member Function Documentation
getName()
std::string nnc::ConstantFoldTranspose::getName () inline override virtual
Reimplemented from nnc::Pass.
Definition at line 30 of file ConstantFoldTranspose.h.
  {
    static const std::string name("opt_constant_fold_transpose");
    return name;
  };
run()
PassData ConstantFoldTranspose::run (PassData data) override virtual
run compiler pass
Parameters
data - data that pass is taken
Returns
data that can be passed to the next pass
Exceptions
PassException object if errors occured
Implements nnc::Pass.
Definition at line 52 of file ConstantFoldTranspose.cpp.
{
  auto graph = static_cast<Graph *>(data);
  GraphPatternMatcher matcher(graph);
  auto is_constant = [](const Operation *op) { return op->getType() == Operation::Type::constant; };
  auto is_transpose = [](const Operation *op) {
    return op->getType() == Operation::Type::transpose;
  };
  auto matches = matcher.matchEdge(is_constant, is_transpose);
  while (!matches.empty())
  {
    for (const auto &match : matches)
    {
      auto constant_op = dynamic_cast<ops::ConstantOp *>(match.first);
      auto transpose_op = dynamic_cast<ops::TransposeOp *>(match.second);
      const auto elem_type = constant_op->getValue().getElementType();
      const auto &out_shape = transpose_op->getOutputShape(0);
      TensorType res_type(elem_type, out_shape);
      if (constant_op->getOutput(0)->getType().isQuantized())
        res_type.setQuantization(constant_op->getOutput(0)->getType().getQuantization());
      TensorVariant res(res_type);
      transpose(constant_op->getValue(), res, transpose_op->getAxisOrder());
      auto new_op = graph->create<ops::ConstantOp>(res);
      graph->replaceNode(transpose_op, new_op);
      opt_util::removeNodeIfUnused(graph, constant_op);
    }
    matches = matcher.matchEdge(is_constant, is_transpose);
  }
  return graph;
}
References mir::Operation::getOutputShape(), mir::GraphPatternMatcher::matchEdge(), nnc::opt_util::removeNodeIfUnused(), and mir::TensorType::setQuantization().
The documentation for this class was generated from the following files:
compiler/nnc/include/passes/optimizations/ConstantFoldTranspose.h
compiler/nnc/passes/optimizations/ConstantFoldTranspose.cpp