ONE - On-device Neural Engine: onert::compiler::pass::OddOutputPass Class Reference
onert::compiler::pass::OddOutputPass Class Reference
Pass to specially handle odd outputs in a subgraph.
#include <OddOutputPass.h>
Public Member Functions
std::string id () final
void run () override
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Pass to specially handle odd outputs in a subgraph.
Runtime Graph IR requires every input or output must have distinct tensor index, this is onert's restriction. However we allow duplication of indices in the models(or API). So we should transform the graph after model-loading.
This is necessary since our API lets users to set different buffers for each input and output so it is unavoidable that we must copy the value at runtime.
Note that this is a mandatory pass for Graph.
Case 1 : An operand which is a model output and a model input
Create an operand and insert a Permute(copy) op between them. And change the output to be the newly generated operand.
e.g.)
((#0 Input0 and also Output0))
becomes
((#0 Input0)) -> [#0 Permute] -> ((#1 Output0))
Case 2 : Two or more duplicated outputs
Do the same with Case 1, but between two outputs of the same tensor index.
e.g.)
((#0 Input0)) -> [#0 Some Operation] -> ((#1 Output0 and also Output1))
becomes
((#0 Input0)) -> [#0 Some Operation] -> ((#1 Output0)) [#1 Permute] -> ((#2 Output1))
Definition at line 70 of file OddOutputPass.h.
Member Function Documentation
id()
std::string onert::compiler::pass::OddOutputPass::id () inline final virtual
Implements onert::compiler::pass::Pass.
Definition at line 76 of file OddOutputPass.h.
{ return "OddOutputPass"; }
Pass()
onert::compiler::pass::Pass::Pass (ir::Graph & graph) inline
Definition at line 40 of file Pass.h.
: _graph{graph} {}
run()
void onert::compiler::pass::OddOutputPass::run () override virtual
Implements onert::compiler::pass::Pass.
Definition at line 31 of file OddOutputPass.cc.
{
  auto &outputs = _graph.getOutputs();
  VERBOSE(OddOutputPass) << "Case 1 : An operand which is a model output and a model input"
                         << std::endl;
  for (auto &ind : outputs)
  {
    if (_graph.getInputs().contains(ind))
    {
      auto permute_output_ind = insertPermute(ind);
      // Update the output to be newly added operand
      _graph.getOutputs().replace(ind, permute_output_ind);
    }
  }
  VERBOSE(OddOutputPass) << "Case 2 : Two or more duplicated outputs" << std::endl;
  std::unordered_set<ir::OperandIndex> occurence;
  for (auto &ind : outputs)
  {
    auto &obj = _graph.operands().at(ind);
    if (occurence.count(ind) == 0)
    {
      occurence.insert(ind);
      continue;
    }
    // Panic when it is const, it must have been handled earlier in another pass
    UNUSED_RELEASE(obj);
    assert(!obj.isConstant());
    auto permute_output_ind = insertPermute(ind);
    ind = permute_output_ind; // Replace output index to fix output duplication
  }
}
References onert::compiler::pass::Pass::_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::contains(), onert::ir::Graph::getInputs(), onert::ir::Graph::getOutputs(), onert::ir::Graph::operands(), onert::ir::OperandIndexSequence::replace(), UNUSED_RELEASE, and VERBOSE.
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/OddOutputPass.h
runtime/onert/core/src/compiler/pass/OddOutputPass.cc