ONE - On-device Neural Engine: GraphBuilder::Stack Class Reference
GraphBuilder::Stack Class Reference final
#include <GraphBuilder.h>
Public Member Functions
Stack ()=default
loco::Node * top (void) const
loco::Node * pop (void)
void push (loco::Node *node)
Detailed Description
Definition at line 41 of file GraphBuilder.h.
Constructor & Destructor Documentation
Stack()
GraphBuilder::Stack::Stack () default
Member Function Documentation
pop()
loco::Node * GraphBuilder::Stack::pop (void) inline
Definition at line 50 of file GraphBuilder.h.
    {
      auto ret = top();
      _content.pop();
      return ret;
    }
References top().
Referenced by OutputLayer::operator()(), ReLULayer::operator()(), FeatureEncodeLayer::operator()(), FeatureDecodeLayer::operator()(), FilterEncodeLayer::operator()(), DepthwiseFilterEncodeLayer::operator()(), DepthwiseConv2DLayer::operator()(), TransposedConv2DLayer::operator()(), FixedReshapeLayer::operator()(), TensorBroadcastLayer::operator()(), and GraphBuilder::pop().
push()
void GraphBuilder::Stack::push (loco::Node * node) inline
Definition at line 58 of file GraphBuilder.h.
{ _content.push(node); }
Referenced by InputLayer::operator()(), OutputLayer::operator()(), ReLULayer::operator()(), ConstGenLayer::operator()(), FeatureEncodeLayer::operator()(), FeatureDecodeLayer::operator()(), FilterEncodeLayer::operator()(), DepthwiseFilterEncodeLayer::operator()(), DepthwiseConv2DLayer::operator()(), TransposedConv2DLayer::operator()(), FixedReshapeLayer::operator()(), and TensorBroadcastLayer::operator()().
top()
loco::Node * GraphBuilder::Stack::top (void) const inline
Definition at line 47 of file GraphBuilder.h.
{ return _content.top(); }
Referenced by pop().
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h