ONE - On-device Neural Engine: onert::ir::Operation Class Reference
onert::ir::Operation Class Reference
#include <Operation.h>
Public Member Functions
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
void replaceInputs (const OperandIndex &from, const OperandIndex &to) override
void replaceOutputs (const OperandIndex &from, const OperandIndex &to) override
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const override
OperandIndexSequence getUsedInputSet () const override
const OperandIndexSequence & getOutputs () const override
OperandIndexSequence getUsedOutputSet () const override
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Public Member Functions inherited from onert::ir::IOperation
virtual ~IOperation ()=default
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
Detailed Description
Definition at line 31 of file Operation.h.
Constructor & Destructor Documentation
Operation() [1/4]
Operation::Operation (OperandConstraint input_constr, const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, OperandConstraint output_constr = OperandConstraint::createAny())
Definition at line 24 of file Operation.cc.
  : _input_constr{input_constr}, _output_constr{output_constr}
{
  setInputs(inputs);
  setOutputs(outputs);
}
References setInputs(), and setOutputs().
Operation() [2/4]
Operation::Operation (OperandConstraint input_constr, OperandConstraint output_constr = OperandConstraint::createAny()) explicit
Definition at line 32 of file Operation.cc.
  : _input_constr{input_constr}, _output_constr{output_constr}
{
}
Operation() [3/4]
onert::ir::Operation::Operation (const Operation &) default
Operation() [4/4]
onert::ir::Operation::Operation (Operation &&) default
~Operation()
Operation::~Operation () virtual default
Member Function Documentation
getInputs() [1/2]
OperandIndexSequence & onert::ir::Operation::getInputs () inline
Definition at line 51 of file Operation.h.
{ return _inputs; }
Referenced by onert::backend::acl_common::AclConstantInitializer::copyInputInitialize(), onert::backend::acl_common::kernelGenFullyConnected(), onert::backend::acl_common::kernelGenLSTM(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_common::AclConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::acl_common::AclSubTensorAnalyzer::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::acl_cl::ConstantInitializer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::acl_neon::ConstantInitializer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), and onert::ir::train::UseDefGenerator::visit().
getInputs() [2/2]
const OperandIndexSequence & onert::ir::Operation::getInputs () const inline override virtual
Implements onert::ir::IOperation.
Definition at line 52 of file Operation.h.
{ return _inputs; }
getOutputs()
const OperandIndexSequence & onert::ir::Operation::getOutputs () const inline override virtual
Implements onert::ir::IOperation.
Definition at line 54 of file Operation.h.
{ return _outputs; }
Referenced by onert::backend::acl_common::kernelGenFullyConnected(), onert::backend::acl_common::kernelGenLSTM(), onert::ir::operation::LSTM::name(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::acl_common::AclSubTensorAnalyzer::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::compiler::ShapeValidator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::backend::train::KernelGenerator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::OperationDumper::visit(), onert::ir::OperationValidator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), and onert::ir::train::UseDefGenerator::visit().
getUsedInputSet()
OperandIndexSequence Operation::getUsedInputSet () const override virtual
Implements onert::ir::IOperation.
Definition at line 53 of file Operation.cc.
{
  return _inputs | ir::Remove::UNDEFINED | ir::Remove::DUPLICATED;
}
References onert::ir::DUPLICATED, and onert::ir::UNDEFINED.
Referenced by onert::ir::train::UseDefGenerator::visit(), onert::ir::train::UseDefGenerator::visit(), and onert::ir::train::UseDefGenerator::visit().
getUsedOutputSet()
OperandIndexSequence Operation::getUsedOutputSet () const override virtual
Implements onert::ir::IOperation.
Definition at line 58 of file Operation.cc.
{
  return _outputs | ir::Remove::UNDEFINED | ir::Remove::DUPLICATED;
}
References onert::ir::DUPLICATED, and onert::ir::UNDEFINED.
operator=() [1/2]
Operation & onert::ir::Operation::operator= (const Operation &) default
operator=() [2/2]
Operation & onert::ir::Operation::operator= (Operation &&) default
replaceInputs()
void Operation::replaceInputs (const OperandIndex & from, const OperandIndex & to) override virtual
Implements onert::ir::IOperation.
Definition at line 63 of file Operation.cc.
{
  _inputs.replace(from, to);
}
References onert::ir::OperandIndexSequence::replace().
replaceOutputs()
void Operation::replaceOutputs (const OperandIndex & from, const OperandIndex & to) override virtual
Implements onert::ir::IOperation.
Definition at line 68 of file Operation.cc.
{
  _outputs.replace(from, to);
}
References onert::ir::OperandIndexSequence::replace().
setInputs()
void Operation::setInputs (const OperandIndexSequence & indexes)
Definition at line 39 of file Operation.cc.
{
  if (!_input_constr.check(indexes.size()))
    throw std::runtime_error{"Invalid number of input tensors for this operation."};
  _inputs = indexes;
}
References onert::ir::OperandConstraint::check(), and onert::ir::OperandIndexSequence::size().
Referenced by Operation(), onert::ir::operation::Permute::Permute(), and onert_test::ir::SimpleMock::SimpleMock().
setOutputs()
void Operation::setOutputs (const OperandIndexSequence & indexes)
Definition at line 46 of file Operation.cc.
{
  if (!_output_constr.check(indexes.size()))
    throw std::runtime_error{"Invalid number of output tensors for this operation."};
  _outputs = indexes;
}
References onert::ir::OperandConstraint::check(), and onert::ir::OperandIndexSequence::size().
Referenced by Operation(), onert::ir::operation::Permute::Permute(), and onert_test::ir::SimpleMock::SimpleMock().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/Operation.h
runtime/onert/core/src/ir/Operation.cc