ONE - On-device Neural Engine: caffeimport::InputBuilder Class Reference
caffeimport::InputBuilder Class Reference final
#include <Input.h>
Public Member Functions
void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const override
Public Member Functions inherited from caffeimport::GraphBuilder
virtual void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 27 of file Input.h.
Member Function Documentation
build()
void caffeimport::InputBuilder::build (const ::caffe::LayerParameter & layer, GraphBuilderContext * context) const override virtual
Implements caffeimport::GraphBuilder.
Definition at line 32 of file Input.cpp.
{
  coco::Module *module = context->module();
  std::map<std::string, tensor::Shape> &shape_ctx = context->shape_ctx();
  std::map<std::string, coco::Bag *> &bag_ctx = context->bag_ctx();
  assert(layer.has_input_param());
  const auto &param = layer.input_param();
  for (uint32_t n = 0; n < layer.top_size(); ++n)
  {
    const auto &name = layer.top(n);
    const auto shape = as_tensor_shape(param.shape(n));
    auto bag = module->entity()->bag()->create(num_elements(shape));
    auto input = module->entity()->input()->create(shape);
    input->bag(bag);
    input->name(name);
    input->reorder<LexicalLayout>();
    module->input()->insert(input);
    bag_ctx[name] = bag;
    shape_ctx[name] = shape;
  }
}
References caffeimport::as_tensor_shape(), coco::EntityManager::bag(), caffeimport::GraphBuilderContext::bag_ctx(), coco::InputManager::create(), coco::BagManager::create(), coco::Module::entity(), coco::EntityManager::input(), coco::Module::input(), coco::PtrList< T >::insert(), caffeimport::GraphBuilderContext::module(), and caffeimport::GraphBuilderContext::shape_ctx().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/Layer/Input.h
compiler/enco/frontend/caffe/src/Layer/Input.cpp