ONE - On-device Neural Engine: coco::UnaryOp Class Reference
coco::UnaryOp Class Reference
Op with a single argument.
#include <Op.h>
Public Member Functions
UnaryOp ()
UnaryOp (const UnaryOp &)=delete
UnaryOp (UnaryOp &&)=delete
virtual ~UnaryOp ()=default
uint32_t arity (void) const final
Return the number of arguments (# of child Ops)
Op * arg (uint32_t n) const final
Return N-th argument.
std::set< Object * > uses (void) const final
Return a set of object(s) used during execution.
Op * arg (void) const
void arg (Op *arg)
Public Member Functions inherited from coco::Op
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Detailed Description
Op with a single argument.
Definition at line 183 of file Op.h.
Constructor & Destructor Documentation
UnaryOp() [1/3]
coco::UnaryOp::UnaryOp () explicit
Definition at line 65 of file Op.cpp.
                 : _arg{this}
{
  // DO NOTHING
}
UnaryOp() [2/3]
coco::UnaryOp::UnaryOp (const UnaryOp &) delete
UnaryOp() [3/3]
coco::UnaryOp::UnaryOp (UnaryOp &&) delete
~UnaryOp()
virtual coco::UnaryOp::~UnaryOp () virtual default
Member Function Documentation
arg() [1/3]
void coco::UnaryOp::arg (Op * arg) inline
Definition at line 203 of file Op.h.
{ _arg.child(arg); }
References arg(), and coco::Part::child().
arg() [2/3]
Op * coco::UnaryOp::arg (uint32_t n) const final virtual
Return N-th argument.
Note
The behavior of arg(n) is defined only when n < artiy()
Implements coco::Op.
Referenced by caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::build_activation(), and OpPrinter::visit().
arg() [3/3]
Op * coco::UnaryOp::arg (void) const inline
Definition at line 202 of file Op.h.
{ return _arg.child(); }
References coco::Part::child().
Referenced by arg(), and uses().
arity()
uint32_t coco::UnaryOp::arity (void) const final virtual
Return the number of arguments (# of child Ops)
Implements coco::Op.
Definition at line 70 of file Op.cpp.
{
  // There is only one argument
  return 1;
}
uses()
std::set< Object * > coco::UnaryOp::uses (void) const final virtual
Return a set of object(s) used during execution.
NOTE There is no 'def' method as Op is not allowed to define a new object
Implements coco::Op.
Definition at line 82 of file Op.cpp.
{
  std::set<Object *> res;
  if (auto ifm = arg())
  {
    for (auto obj : ifm->uses())
    {
      res.insert(obj);
    }
  }
  return res;
}
References arg().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Op.h
compiler/coco/core/src/IR/Op.cpp