ONE - On-device Neural Engine: luci_interpreter::kernels::CumSum Class Reference
luci_interpreter::kernels::CumSum Class Reference
#include <CumSum.h>
Public Member Functions
CumSum (const Tensor *input, const Tensor *axis, Tensor *output, const CumSumParams &params)
const Tensor * input () const
const Tensor * axis () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< CumSumParams >
const CumSumParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< CumSumParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const CumSumParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< CumSumParams >
const CumSumParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 30 of file CumSum.h.
Constructor & Destructor Documentation
CumSum()
luci_interpreter::kernels::CumSum::CumSum (const Tensor * input, const Tensor * axis, Tensor * output, const CumSumParams & params)
Definition at line 28 of file CumSum.cpp.
  : KernelWithParams<CumSumParams>({input, axis}, {output}, params)
{
}
References axis(), and input().
Member Function Documentation
axis()
const Tensor * luci_interpreter::kernels::CumSum::axis () const inline
Definition at line 36 of file CumSum.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), CumSum(), and execute().
configure()
void luci_interpreter::kernels::CumSum::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 33 of file CumSum.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() >= 1);
  LUCI_INTERPRETER_CHECK(axis()->element_type() == DataType::S32);
  LUCI_INTERPRETER_CHECK(axis()->shape().num_dims() == 0);
  output()->resize(input()->shape());
}
References axis(), input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
execute()
void luci_interpreter::kernels::CumSum::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 44 of file CumSum.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      tflite::optimized_ops::CumSum(getTensorData<float>(input()), getTensorShape(input()),
                                    *getTensorData<int32_t>(axis()), params().exclusive,
                                    params().reverse, getTensorData<float>(output()));
      break;
    default:
      throw std::runtime_error("luci-intp CumSum Unsupported type.");
  }
}
References axis(), luci_interpreter::kernels::getTensorShape(), input(), output(), and luci_interpreter::KernelWithParams< CumSumParams >::params().
input()
const Tensor * luci_interpreter::kernels::CumSum::input () const inline
Definition at line 35 of file CumSum.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), CumSum(), and execute().
output()
Tensor * luci_interpreter::kernels::CumSum::output () const inline
Definition at line 37 of file CumSum.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/CumSum.h
compiler/luci-interpreter/src/kernels/CumSum.cpp