ONE - On-device Neural Engine: moco::TFStridedSlice Class Reference
moco::TFStridedSlice Class Reference final
#include <TFStridedSlice.h>
Public Member Functions
TFStridedSlice ()=default
Node * input (void) const
void input (Node *node)
Node * begin (void) const
void begin (Node *node)
Node * end (void) const
void end (Node *node)
Node * strides (void) const
void strides (Node *node)
int32_t begin_mask (void) const
void begin_mask (int32_t begin_mask)
int32_t end_mask (void) const
void end_mask (int32_t end_mask)
int32_t ellipsis_mask (void) const
void ellipsis_mask (int32_t ellipsis_mask)
int32_t new_axis_mask (void) const
void new_axis_mask (int32_t new_axis_mask)
int32_t shrink_axis_mask (void) const
void shrink_axis_mask (int32_t shrink_axis_mask)
Public Member Functions inherited from moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::StridedSlice >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >
loco::Use * at (unsigned n) const
Detailed Description
Note
TFStridedSlice corresponds to the following GraphDef
Definition at line 79 of file TFStridedSlice.h.
Constructor & Destructor Documentation
TFStridedSlice()
moco::TFStridedSlice::TFStridedSlice () default
Member Function Documentation
begin() [1/2]
void moco::TFStridedSlice::begin (Node * node) inline
Definition at line 89 of file TFStridedSlice.h.
{ at(1)->node(node); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
begin() [2/2]
Node * moco::TFStridedSlice::begin (void) const inline
Definition at line 88 of file TFStridedSlice.h.
{ return at(1)->node(); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
begin_mask() [1/2]
void moco::TFStridedSlice::begin_mask (int32_t begin_mask) inline
Definition at line 99 of file TFStridedSlice.h.
{ _begin_mask = begin_mask; }
References begin_mask().
Referenced by begin_mask().
begin_mask() [2/2]
int32_t moco::TFStridedSlice::begin_mask (void) const inline
Definition at line 98 of file TFStridedSlice.h.
{ return _begin_mask; }
ellipsis_mask() [1/2]
void moco::TFStridedSlice::ellipsis_mask (int32_t ellipsis_mask) inline
Definition at line 105 of file TFStridedSlice.h.
{ _ellipsis_mask = ellipsis_mask; }
References ellipsis_mask().
Referenced by ellipsis_mask().
ellipsis_mask() [2/2]
int32_t moco::TFStridedSlice::ellipsis_mask (void) const inline
Definition at line 104 of file TFStridedSlice.h.
{ return _ellipsis_mask; }
end() [1/2]
void moco::TFStridedSlice::end (Node * node) inline
Definition at line 92 of file TFStridedSlice.h.
{ at(2)->node(node); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
end() [2/2]
Node * moco::TFStridedSlice::end (void) const inline
Definition at line 91 of file TFStridedSlice.h.
{ return at(2)->node(); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
end_mask() [1/2]
void moco::TFStridedSlice::end_mask (int32_t end_mask) inline
Definition at line 102 of file TFStridedSlice.h.
{ _end_mask = end_mask; }
References end_mask().
Referenced by end_mask().
end_mask() [2/2]
int32_t moco::TFStridedSlice::end_mask (void) const inline
Definition at line 101 of file TFStridedSlice.h.
{ return _end_mask; }
input() [1/2]
void moco::TFStridedSlice::input (Node * node) inline
Definition at line 86 of file TFStridedSlice.h.
{ at(0)->node(node); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
input() [2/2]
Node * moco::TFStridedSlice::input (void) const inline
Definition at line 85 of file TFStridedSlice.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
new_axis_mask() [1/2]
void moco::TFStridedSlice::new_axis_mask (int32_t new_axis_mask) inline
Definition at line 108 of file TFStridedSlice.h.
{ _new_axis_mask = new_axis_mask; }
References new_axis_mask().
Referenced by new_axis_mask().
new_axis_mask() [2/2]
int32_t moco::TFStridedSlice::new_axis_mask (void) const inline
Definition at line 107 of file TFStridedSlice.h.
{ return _new_axis_mask; }
shrink_axis_mask() [1/2]
void moco::TFStridedSlice::shrink_axis_mask (int32_t shrink_axis_mask) inline
Definition at line 111 of file TFStridedSlice.h.
{ _shrink_axis_mask = shrink_axis_mask; }
References shrink_axis_mask().
Referenced by shrink_axis_mask().
shrink_axis_mask() [2/2]
int32_t moco::TFStridedSlice::shrink_axis_mask (void) const inline
Definition at line 110 of file TFStridedSlice.h.
{ return _shrink_axis_mask; }
strides() [1/2]
void moco::TFStridedSlice::strides (Node * node) inline
Definition at line 95 of file TFStridedSlice.h.
{ at(3)->node(node); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
strides() [2/2]
Node * moco::TFStridedSlice::strides (void) const inline
Definition at line 94 of file TFStridedSlice.h.
{ return at(3)->node(); }
References moco::FixedArityNode< 4, TFNodeImpl< TFOpcode::StridedSlice > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFStridedSlice.h