ONE - On-device Neural Engine: onert_micro::core::train::OMTrainingStorage Class Reference
onert_micro::core::train::OMTrainingStorage Class Reference
#include <OMTrainingStorage.h>
Public Member Functions
OMTrainingStorage ()=default
OMTrainingStorage (const OMTrainingStorage &)=delete
OMTrainingStorage (OMTrainingStorage &&)=delete
OMTrainingStorage & operator= (const OMTrainingStorage &)=delete
OMTrainingStorage && operator= (const OMTrainingStorage &&)=delete
~OMTrainingStorage ()=default
void setInputData (uint8_t *data, uint32_t input_index)
void setTargetData (uint8_t *data, uint32_t target_index)
void addTrainRank (uint16_t tensor_index, core::OpTrainableRankType train_rank)
std::unordered_map< uint16_t, core::OpTrainableRankType > & getTensorIndexToRankTypeTable ()
OMStatus setOptimizer (const OMConfig &config)
onert_micro::train::optimizers::SGD * getSGD ()
onert_micro::train::optimizers::Adam * getAdam ()
uint8_t * getInputData (uint32_t input_index)
uint8_t * getTargetData (uint32_t target_index)
void reset ()
Detailed Description
Definition at line 38 of file OMTrainingStorage.h.
Constructor & Destructor Documentation
OMTrainingStorage() [1/3]
onert_micro::core::train::OMTrainingStorage::OMTrainingStorage () default
OMTrainingStorage() [2/3]
onert_micro::core::train::OMTrainingStorage::OMTrainingStorage (const OMTrainingStorage &) delete
OMTrainingStorage() [3/3]
onert_micro::core::train::OMTrainingStorage::OMTrainingStorage (OMTrainingStorage &&) delete
~OMTrainingStorage()
onert_micro::core::train::OMTrainingStorage::~OMTrainingStorage () default
Member Function Documentation
addTrainRank()
void onert_micro::core::train::OMTrainingStorage::addTrainRank (uint16_t tensor_index, core::OpTrainableRankType train_rank) inline
Definition at line 76 of file OMTrainingStorage.h.
  {
    _tensor_index_to_train_rank[tensor_index] = train_rank;
  }
Referenced by onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig().
getAdam()
onert_micro::train::optimizers::Adam * onert_micro::core::train::OMTrainingStorage::getAdam () inline
Definition at line 94 of file OMTrainingStorage.h.
{ return _adam_optimizer.get(); }
Referenced by onert_micro::core::train::OMTrainingHandler::updateOptimizerState(), and onert_micro::core::train::OMTrainingHandler::updateWeights().
getInputData()
uint8_t * onert_micro::core::train::OMTrainingStorage::getInputData (uint32_t input_index) inline
Definition at line 97 of file OMTrainingStorage.h.
{ return _input_index_to_input_data[input_index]; }
Referenced by onert_micro::core::train::OMTrainingHandler::getInputData().
getSGD()
onert_micro::train::optimizers::SGD * onert_micro::core::train::OMTrainingStorage::getSGD () inline
Definition at line 91 of file OMTrainingStorage.h.
{ return _sgd_optimizer.get(); }
Referenced by onert_micro::core::train::OMTrainingHandler::updateOptimizerState(), and onert_micro::core::train::OMTrainingHandler::updateWeights().
getTargetData()
uint8_t * onert_micro::core::train::OMTrainingStorage::getTargetData (uint32_t target_index) inline
Definition at line 99 of file OMTrainingStorage.h.
  {
    return _target_index_to_target_data[target_index];
  }
Referenced by onert_micro::core::train::OMTrainingHandler::evaluateMetric(), onert_micro::core::train::OMTrainingHandler::getTargetData(), and onert_micro::core::train::OMTrainingHandler::handleError().
getTensorIndexToRankTypeTable()
std::unordered_map< uint16_t, core::OpTrainableRankType > & onert_micro::core::train::OMTrainingStorage::getTensorIndexToRankTypeTable () inline
Definition at line 81 of file OMTrainingStorage.h.
  {
    return _tensor_index_to_train_rank;
  }
Referenced by onert_micro::core::train::OMTrainingHandler::updateWeights().
operator=() [1/2]
OMTrainingStorage && onert_micro::core::train::OMTrainingStorage::operator= (const OMTrainingStorage &&) delete
operator=() [2/2]
OMTrainingStorage & onert_micro::core::train::OMTrainingStorage::operator= (const OMTrainingStorage &) delete
reset()
void OMTrainingStorage::reset ()
Definition at line 53 of file OMTrainingStorage.cpp.
{
  if (_sgd_optimizer)
    _sgd_optimizer->reset();
  if (_adam_optimizer)
    _adam_optimizer->fullReset();
  _target_index_to_target_data.clear();
  _input_index_to_input_data.clear();
}
Referenced by onert_micro::core::train::OMTrainingHandler::reset().
setInputData()
void onert_micro::core::train::OMTrainingStorage::setInputData (uint8_t * data, uint32_t input_index) inline
Definition at line 66 of file OMTrainingStorage.h.
  {
    _input_index_to_input_data[input_index] = data;
  }
Referenced by onert_micro::core::train::OMTrainingHandler::setInputData().
setOptimizer()
OMStatus OMTrainingStorage::setOptimizer (const OMConfig & config)
Definition at line 25 of file OMTrainingStorage.cpp.
{
  switch (config.training_context.optimizer)
  {
    case SGD:
    {
      if (_sgd_optimizer != nullptr)
      {
        OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
      }
      _sgd_optimizer = std::make_unique<optimizers::SGD>();
      break;
    }
    case ADAM:
    {
      if (_adam_optimizer != nullptr)
      {
        OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
      }
      _adam_optimizer = std::make_unique<optimizers::Adam>();
      break;
    }
    default:
      assert(false && "Unsupported Optimizer type");
  }
  return Ok;
}
References onert_micro::ADAM, onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::SGD, and onert_micro::UnknownError.
Referenced by onert_micro::core::train::OMTrainingHandler::setOptimizer().
setTargetData()
void onert_micro::core::train::OMTrainingStorage::setTargetData (uint8_t * data, uint32_t target_index) inline
Definition at line 71 of file OMTrainingStorage.h.
  {
    _target_index_to_target_data[target_index] = data;
  }
Referenced by onert_micro::core::train::OMTrainingHandler::setTargetData().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/train/OMTrainingStorage.h
onert-micro/onert-micro/src/core/train/OMTrainingStorage.cpp