ONE - On-device Neural Engine: mir::TensorType Class Reference
mir::TensorType Class Reference final
#include <TensorType.h>
Public Member Functions
TensorType ()=default
TensorType (DataType element_type, const Shape &shape)
TensorType (DataType element_type, const Shape &shape, const AffineQuantization &quant)
DataType getElementType () const
const Shape & getShape () const
const AffineQuantization & getQuantization () const
void setQuantization (const AffineQuantization &quant)
bool isQuantized () const
Detailed Description
Definition at line 27 of file TensorType.h.
Constructor & Destructor Documentation
TensorType() [1/3]
mir::TensorType::TensorType () default
TensorType() [2/3]
mir::TensorType::TensorType (DataType element_type, const Shape & shape) inline
Definition at line 32 of file TensorType.h.
                                                        : _element_type(element_type), _shape(shape)
  {
  }
TensorType() [3/3]
mir::TensorType::TensorType (DataType element_type, const Shape & shape, const AffineQuantization & quant) inline
Definition at line 36 of file TensorType.h.
    : _element_type(element_type), _shape(shape), _quantization(quant)
  {
  }
Member Function Documentation
getElementType()
DataType mir::TensorType::getElementType () const inline
Definition at line 41 of file TensorType.h.
{ return _element_type; }
Referenced by mir_interpreter::Dequantize(), mir::TensorVariant::getDataType(), mir::Operation::Output::getElementType(), mir::TensorVariant::getElementType(), and mir::Operation::Output::setShape().
getQuantization()
const AffineQuantization & mir::TensorType::getQuantization () const inline
Definition at line 45 of file TensorType.h.
{ return _quantization; }
Referenced by mir_interpreter::Dequantize(), and mir_interpreter::CappedReLUImpl< uint8_t >::run().
getShape()
const Shape & mir::TensorType::getShape () const inline
Definition at line 43 of file TensorType.h.
{ return _shape; }
Referenced by mir::Operation::Output::getShape(), and mir::TensorVariant::getShape().
isQuantized()
bool mir::TensorType::isQuantized () const inline
Definition at line 47 of file TensorType.h.
{ return !_quantization.empty(); }
References mir::AffineQuantization::empty().
Referenced by mir_interpreter::Dequantize().
setQuantization()
void mir::TensorType::setQuantization (const AffineQuantization & quant) inline
Definition at line 46 of file TensorType.h.
{ _quantization = quant; }
Referenced by nnc::ConstantFoldTranspose::run(), and mir::transposeTensor().
The documentation for this class was generated from the following file:
compiler/mir/include/mir/TensorType.h