ONE - On-device Neural Engine: onert::backend::train::ops::FullyConnectedLayer Class Reference
onert::backend::train::ops::FullyConnectedLayer Class Reference
#include <FullyConnectedLayer.h>
Public Member Functions
FullyConnectedLayer ()
~FullyConnectedLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *weights, const IPortableTensor *bias, IPortableTensor *output, IPortableTensor *deriv_input, IPortableTensor *grad_weights, IPortableTensor *grad_bias, const IPortableTensor *deriv_output, ir::Activation activation, ir::FullyConnectedWeightsFormat weights_format, const std::shared_ptr< train::ExternalContext > &external_context)
void forward (bool training) override
void backward (uint32_t training_step) override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
virtual void forward (bool training)=0
virtual void backward (uint32_t training_step)=0
Public Member Functions inherited from onert::backend::cpu::ops::FullyConnectedLayer
FullyConnectedLayer ()
~FullyConnectedLayer ()
void fullyConnectedFloat32 ()
void fullyConnectedQuant8 ()
void fullyConnectedHybrid ()
void fullyConnectedSparseWeight ()
void fullyConnected16x1Float32 ()
void configure (const IPortableTensor *input, const IPortableTensor *weights, const IPortableTensor *bias, ir::Activation activation, ir::FullyConnectedWeightsFormat weights_format, IPortableTensor *output, const std::shared_ptr< ExternalContext > &external_context)
void run () override
void prepare () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::FullyConnectedLayer
const IPortableTensor * _input
const IPortableTensor * _weights
const IPortableTensor * _bias
IPortableTensor * _output
ir::Activation _activation
std::unique_ptr< nnfw::cker::FCTempArena > _temp_arena
std::shared_ptr< ExternalContext > _external_context
bool _is_hybrid: 1
bool _is_shuffled16x1float32: 1
Detailed Description
Definition at line 35 of file FullyConnectedLayer.h.
Constructor & Destructor Documentation
FullyConnectedLayer()
onert::backend::train::ops::FullyConnectedLayer::FullyConnectedLayer ()
Definition at line 35 of file FullyConnectedLayer.cc.
  : cpu::ops::FullyConnectedLayer{}, _grad_weights{nullptr}, _grad_bias{nullptr},
    _deriv_input{nullptr}, _deriv_output{nullptr}, _transposed_weights{nullptr},
    _transposed_input{nullptr}, _transposed_deriv_output{nullptr}, _act_deriv_output{nullptr}
{
  // DO NOTHING
}
~FullyConnectedLayer()
onert::backend::train::ops::FullyConnectedLayer::~FullyConnectedLayer () default
Member Function Documentation
backward()
void onert::backend::train::ops::FullyConnectedLayer::backward (uint32_t training_step) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 92 of file FullyConnectedLayer.cc.
{
  const auto data_type = _deriv_output->data_type();
  assert(data_type == _input->data_type());
  switch (data_type)
  {
    case OperandType::FLOAT32:
    {
      assert(data_type == _grad_weights->data_type());
      assert(data_type == _grad_bias->data_type());
      backwardFloat32();
      break;
    }
    default:
      throw std::runtime_error{"train FullyConnectedLayer: unsupported data type"};
  }
}
References onert::backend::cpu::ops::FullyConnectedLayer::_input, and onert::backend::ITensor::data_type().
configure()
void onert::backend::train::ops::FullyConnectedLayer::configure (const IPortableTensor * input, const IPortableTensor * weights, const IPortableTensor * bias, IPortableTensor * output, IPortableTensor * deriv_input, IPortableTensor * grad_weights, IPortableTensor * grad_bias, const IPortableTensor * deriv_output, ir::Activation activation, ir::FullyConnectedWeightsFormat weights_format, const std::shared_ptr< train::ExternalContext > & external_context)
Definition at line 45 of file FullyConnectedLayer.cc.
{
  cpu::ops::FullyConnectedLayer::configure(input, weights, bias, activation, weights_format, output,
                                           external_context);
  _deriv_input = deriv_input;
  _grad_weights = grad_weights;
  _grad_bias = grad_bias;
  _deriv_output = deriv_output;
  if (weights_format != ir::FullyConnectedWeightsFormat::Default)
    throw std::runtime_error{
      "train FullyConnectedLayer: Weight formats other than default are not supported."};
  if (input->get_info().shape().rank() != 2 || weights->get_info().shape().rank() != 2 ||
      output->get_info().shape().rank() != 2 || deriv_input->get_info().shape().rank() != 2 ||
      grad_weights->get_info().shape().rank() != 2 || deriv_output->get_info().shape().rank() != 2)
    throw std::runtime_error{
      "train FullyConnectedLayer: Input other ranks than 2 are not supported."};
  _transposed_weights = std::make_unique<Tensor>(weights->get_info(), weights->layout());
  _transposed_weights->setBuffer(std::make_shared<basic::Allocator>(weights->total_size()));
  _transposed_input = std::make_unique<Tensor>(input->get_info(), input->layout());
  _transposed_input->setBuffer(std::make_shared<basic::Allocator>(input->total_size()));
  _transposed_deriv_output =
    std::make_unique<Tensor>(deriv_output->get_info(), deriv_output->layout());
  _transposed_deriv_output->setBuffer(
    std::make_shared<basic::Allocator>(deriv_output->total_size()));
  if (activation != ir::Activation::NONE)
  {
    _act_deriv_output =
      std::make_unique<Tensor>(_deriv_output->get_info(), _deriv_output->layout());
    _act_deriv_output->setBuffer(std::make_shared<basic::Allocator>(_deriv_output->total_size()));
  }
}
References onert::backend::cpu::ops::FullyConnectedLayer::configure(), onert::ir::Default, onert::backend::IPortableTensor::get_info(), onert::backend::ITensor::layout(), onert::ir::NONE, onert::ir::OperandInfo::shape(), and onert::backend::ITensor::total_size().
forward()
void onert::backend::train::ops::FullyConnectedLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 90 of file FullyConnectedLayer.cc.
{ cpu::ops::FullyConnectedLayer::run(); }
References onert::backend::cpu::ops::FullyConnectedLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/FullyConnectedLayer.h
runtime/onert/backend/train/ops/FullyConnectedLayer.cc