ONE - On-device Neural Engine: coco::Stride2D Class Reference
coco::Stride2D Class Reference
#include <Stride2D.h>
Public Member Functions
Stride2D ()
Stride2D (uint32_t vertical, uint32_t horizontal)
uint32_t vertical (void) const
Stride2D & vertical (uint32_t value)
uint32_t horizontal (void) const
Stride2D & horizontal (uint32_t value)
Detailed Description
Definition at line 25 of file Stride2D.h.
Constructor & Destructor Documentation
Stride2D() [1/2]
coco::Stride2D::Stride2D () inline
Definition at line 28 of file Stride2D.h.
             : _vertical{1}, _horizontal{1}
  {
    // DO NOTHING
  }
Stride2D() [2/2]
coco::Stride2D::Stride2D (uint32_t vertical, uint32_t horizontal) inline
Definition at line 34 of file Stride2D.h.
                                                   : _vertical{vertical}, _horizontal{horizontal}
  {
    // DO NOTHING
  }
Member Function Documentation
horizontal() [1/2]
Stride2D & coco::Stride2D::horizontal (uint32_t value)
Definition at line 28 of file Stride2D.cpp.
{
  _horizontal = value;
  return (*this);
}
horizontal() [2/2]
uint32_t coco::Stride2D::horizontal (void) const inline
Definition at line 44 of file Stride2D.h.
{ return _horizontal; }
Referenced by tflimport::MaxPool2DGraphBuilder::build(), and OpPrinter::visit().
vertical() [1/2]
Stride2D & coco::Stride2D::vertical (uint32_t value)
Definition at line 22 of file Stride2D.cpp.
{
  _vertical = value;
  return (*this);
}
vertical() [2/2]
uint32_t coco::Stride2D::vertical (void) const inline
Definition at line 40 of file Stride2D.h.
{ return _vertical; }
Referenced by tflimport::MaxPool2DGraphBuilder::build(), and OpPrinter::visit().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Stride2D.h
compiler/coco/core/src/IR/Stride2D.cpp