ONE - On-device Neural Engine: coco::EntityBuilder Class Reference
coco::EntityBuilder Class Reference
A base class for IR entity builders.
#include <EntityBuilder.h>
Public Member Functions
virtual ~EntityBuilder ()=default
Protected Member Functions
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
A base class for IR entity builders.
NOTE Only EntityBuilder is allowed to update module field of each Entity
Definition at line 31 of file EntityBuilder.h.
Constructor & Destructor Documentation
~EntityBuilder()
virtual coco::EntityBuilder::~EntityBuilder () virtual default
Member Function Documentation
module() [1/2]
void coco::EntityBuilder::module (Module * m) inline protected
Definition at line 39 of file EntityBuilder.h.
{ _module = m; }
References m.
module() [2/2]
Module * coco::EntityBuilder::module (void) const inline protected
Definition at line 37 of file EntityBuilder.h.
{ return _module; }
Referenced by coco::BagManager::BagManager(), coco::BlockManager::BlockManager(), coco::InputManager::InputManager(), coco::InstrManager::InstrManager(), coco::ObjectManager::ObjectManager(), coco::OpManager::OpManager(), and coco::OutputManager::OutputManager().
modulize()
void coco::EntityBuilder::modulize (Entity * entity) const inline protected
Definition at line 40 of file EntityBuilder.h.
{ entity->module(_module); }
References coco::Entity::module().
Referenced by coco::InputManager::create(), coco::OutputManager::create(), coco::BagManager::create(), coco::BlockManager::create(), coco::InstrManager::create(), and coco::ObjectManager::create().
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/IR/EntityBuilder.h