ONE - On-device Neural Engine: coco::FeatureLayouts::Generic Class Reference
coco::FeatureLayouts::Generic Class Reference final
Generic Feature Layout.
#include <FeatureLayouts.h>
Public Member Functions
const FeatureLayout::ID * id (void) const override
const FeatureShape & shape (void) const override
ElemID & at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col)
ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override
void reorder (const nncc::core::ADT::feature::Layout &l)
Public Member Functions inherited from coco::FeatureLayout
virtual ~FeatureLayout ()=default
virtual const ID * id (void) const =0
virtual const FeatureShape & shape (void) const =0
uint32_t batch (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
virtual ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const FeatureLayout::ID * uid (void)
static std::unique_ptr< Generic > create (const nncc::core::ADT::feature::Shape &shape)
Detailed Description
Generic Feature Layout.
Definition at line 127 of file FeatureLayouts.h.
Member Function Documentation
at() [1/2]
ElemID & coco::FeatureLayouts::Generic::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col)
Definition at line 178 of file FeatureLayouts.cpp.
{
  return _content.at(offset(b, ch, row, col));
}
Referenced by reorder().
at() [2/2]
ElemID coco::FeatureLayouts::Generic::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::FeatureLayout.
Definition at line 183 of file FeatureLayouts.cpp.
{
  return _content.at(offset(b, ch, row, col));
}
create()
std::unique_ptr< Generic > coco::FeatureLayouts::Generic::create (const nncc::core::ADT::feature::Shape & shape) static
Definition at line 204 of file FeatureLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<Generic>{new Generic{shape}};
}
References shape().
id()
const FeatureLayout::ID * coco::FeatureLayouts::Generic::id (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 134 of file FeatureLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
reorder()
void coco::FeatureLayouts::Generic::reorder (const nncc::core::ADT::feature::Layout & l)
Definition at line 188 of file FeatureLayouts.cpp.
{
  assert(shape().batch() == 1);
  for (uint32_t ch = 0; ch < shape().depth(); ++ch)
  {
    for (uint32_t row = 0; row < shape().height(); ++row)
    {
      for (uint32_t col = 0; col < shape().width(); ++col)
      {
        at(0, ch, row, col) = ElemID{l.offset(shape(), ch, row, col)};
      }
    }
  }
}
References at(), coco::FeatureLayout::batch(), nncc::core::ADT::feature::Shape::depth(), nncc::core::ADT::feature::Shape::height(), shape(), and nncc::core::ADT::feature::Shape::width().
shape()
const FeatureShape & coco::FeatureLayouts::Generic::shape (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 136 of file FeatureLayouts.h.
{ return _shape; }
Referenced by create(), and reorder().
uid()
const FeatureLayout::ID * coco::FeatureLayouts::Generic::uid (void) static
Definition at line 157 of file FeatureLayouts.cpp.
{
  struct LayoutID final : public FeatureLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/FeatureLayouts.h
compiler/coco/core/src/IR/FeatureLayouts.cpp