ONE - On-device Neural Engine: record_minmax::HDF5Iterator Class Reference
record_minmax::HDF5Iterator Class Reference final
#include <HDF5Iterator.h>
Public Member Functions
HDF5Iterator (const std::string &file_path, luci::Module *module)
bool hasNext () const override
std::vector< DataBuffer > next () override
bool check_type_shape () const override
Public Member Functions inherited from record_minmax::DataSetIterator
virtual ~DataSetIterator ()=default
Detailed Description
Definition at line 33 of file HDF5Iterator.h.
Constructor & Destructor Documentation
HDF5Iterator()
record_minmax::HDF5Iterator::HDF5Iterator (const std::string & file_path, luci::Module * module)
Definition at line 29 of file HDF5Iterator.cpp.
  : _importer(file_path)
{
  try
  {
    _importer.importGroup("value");
    _is_raw_data = _importer.isRawData();
    _num_data = _importer.numData();
  }
  catch (const H5::Exception &e)
  {
    H5::Exception::printErrorStack();
    throw std::runtime_error("HDF5 error occurred during initialization.");
  }
  auto input_nodes = loco::input_nodes(module->graph());
  for (auto input_node : input_nodes)
  {
    const auto cnode = loco::must_cast<const luci::CircleInput *>(input_node);
    _input_nodes.emplace_back(cnode);
  }
}
References dio::hdf5::HDF5Importer::importGroup(), loco::input_nodes(), dio::hdf5::HDF5Importer::isRawData(), loco::must_cast(), and dio::hdf5::HDF5Importer::numData().
Member Function Documentation
check_type_shape()
bool record_minmax::HDF5Iterator::check_type_shape () const override virtual
Implements record_minmax::DataSetIterator.
Definition at line 94 of file HDF5Iterator.cpp.
{
  // If it's raw data, we don't need to check type and shape
  return not _is_raw_data;
}
Referenced by next().
hasNext()
bool record_minmax::HDF5Iterator::hasNext () const override virtual
Implements record_minmax::DataSetIterator.
Definition at line 54 of file HDF5Iterator.cpp.
{ return _curr_idx < _num_data; }
next()
std::vector< DataBuffer > record_minmax::HDF5Iterator::next () override virtual
Implements record_minmax::DataSetIterator.
Definition at line 56 of file HDF5Iterator.cpp.
{
  std::vector<DataBuffer> res;
  try
  {
    for (int32_t input_idx = 0; input_idx < _importer.numInputs(_curr_idx); input_idx++)
    {
      DataBuffer buf;
      const auto input_node = _input_nodes.at(input_idx);
      const auto input_size = getTensorSize(input_node);
      buf.data.resize(input_size);
      if (check_type_shape())
      {
        _importer.readTensor(_curr_idx, input_idx, &buf.dtype, &buf.shape, buf.data.data(),
                             input_size);
      }
      else
      {
        _importer.readTensor(_curr_idx, input_idx, buf.data.data(), input_size);
      }
      res.emplace_back(buf);
    }
  }
  catch (const H5::Exception &e)
  {
    H5::Exception::printErrorStack();
    throw std::runtime_error("HDF5 error occurred during iteration.");
  }
  _curr_idx++; // move to the next index
  return res;
}
References check_type_shape(), record_minmax::getTensorSize(), dio::hdf5::HDF5Importer::numInputs(), and dio::hdf5::HDF5Importer::readTensor().
The documentation for this class was generated from the following files:
compiler/record-minmax/include/HDF5Iterator.h
compiler/record-minmax/src/HDF5Iterator.cpp