ONE - On-device Neural Engine: loco::DepthwiseFilterEncode Class Reference
loco::DepthwiseFilterEncode Class Reference final
Create a depthwise filter from a tensor.
#include <Nodes.h>
Public Member Functions
Node * input (void) const
void input (Node *node)
DepthwiseFilterEncoder * encoder (void) const
void encoder (std::unique_ptr< DepthwiseFilterEncoder > &&enc)
Public Member Functions inherited from loco::CanonicalNodeDef< CanonicalOpcode::DepthwiseFilterEncode, FixedArity< 1 >::Mixin >
virtual ~CanonicalNodeDef ()=default
uint32_t opnum (void) const final
CanonicalOpcode opcode (void) const final
Public Member Functions inherited from loco::CanonicalNode
virtual ~CanonicalNode ()=default
const Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CanonicalOpcode opcode (void) const =0
template<typename T >
T accept (CanonicalNodeVisitorBase< T > *) const
template<typename T >
T accept (CanonicalNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Create a depthwise filter from a tensor.
Definition at line 454 of file Nodes.h.
Member Function Documentation
encoder() [1/2]
void loco::DepthwiseFilterEncode::encoder (std::unique_ptr< DepthwiseFilterEncoder > && enc) inline
Definition at line 463 of file Nodes.h.
{ _enc = std::move(enc); }
encoder() [2/2]
DepthwiseFilterEncoder * loco::DepthwiseFilterEncode::encoder (void) const inline
Definition at line 462 of file Nodes.h.
{ return _enc.get(); }
Referenced by DepthwiseFilterEncodeLayer::Return::perm().
input() [1/2]
void loco::DepthwiseFilterEncode::input (Node * node) inline
Definition at line 459 of file Nodes.h.
{ at(0)->node(node); }
input() [2/2]
Node * loco::DepthwiseFilterEncode::input (void) const inline
Definition at line 458 of file Nodes.h.
{ return at(0)->node(); }
Referenced by DepthwiseFilterEncodeLayer::operator()(), and mir2loco::Transformer::visit().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Nodes.h