ONE - On-device Neural Engine: nnc::ArtifactFunction Class Reference
nnc::ArtifactFunction Class Reference
Represents a function.
#include <ArtifactModel.h>
Public Member Functions
ArtifactFunction (std::string ret_type_name, const std::string &func_name, std::list< std::shared_ptr< ArtifactVariable > > params={})
Constructs a function object.
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
const std::list< std::shared_ptr< ArtifactVariable > > & getParameters () const
const std::string & getRetTypeName () const
const ArtifactBlock * getBlock () const
ArtifactBlock * getBlock ()
Public Member Functions inherited from nnc::ArtifactNamed
ArtifactNamed (std::string name)
const std::string & name () const
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents a function.
Definition at line 519 of file ArtifactModel.h.
Constructor & Destructor Documentation
ArtifactFunction()
nnc::ArtifactFunction::ArtifactFunction (std::string ret_type_name, const std::string & func_name, std::list< std::shared_ptr< ArtifactVariable > > params = {}) inline
Constructs a function object.
Parameters
ret_type_name - the name of the returned type
func_name - the function name.
params - the parameter list.
Definition at line 528 of file ArtifactModel.h.
                                                                     {})
    : ArtifactNamed(func_name), _params(std::move(params)), _retTypeName(std::move(ret_type_name))
  {
  }
Member Function Documentation
accept()
void nnc::ArtifactFunction::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Reimplemented in nnc::ArtifactClassFunction.
Definition at line 534 of file ArtifactModel.h.
{ g->visit(this); }
Referenced by TEST().
getBlock() [1/2]
ArtifactBlock * nnc::ArtifactFunction::getBlock () inline
Definition at line 539 of file ArtifactModel.h.
{ return &_body; }
getBlock() [2/2]
const ArtifactBlock * nnc::ArtifactFunction::getBlock () const inline
Definition at line 538 of file ArtifactModel.h.
{ return &_body; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
getParameters()
const std::list< std::shared_ptr< ArtifactVariable > > & nnc::ArtifactFunction::getParameters () const inline
Definition at line 536 of file ArtifactModel.h.
{ return _params; }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
getRetTypeName()
const std::string & nnc::ArtifactFunction::getRetTypeName () const inline
Definition at line 537 of file ArtifactModel.h.
{ return _retTypeName; }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
The documentation for this class was generated from the following file:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h