ONE - On-device Neural Engine: luci_interpreter::kernels::InstanceNorm Class Reference
luci_interpreter::kernels::InstanceNorm Class Reference
#include <InstanceNorm.h>
Public Member Functions
InstanceNorm (const Tensor *input, const Tensor *gamma, const Tensor *beta, Tensor *output, const InstanceNormParams &params)
const Tensor * input () const
const Tensor * gamma () const
const Tensor * beta () const
Tensor * output () const
void configure () override
void execute () const override
InstanceNorm (const Tensor *input, const Tensor *gamma, const Tensor *beta, Tensor *output, const InstanceNormParams &params)
const Tensor * input () const
const Tensor * gamma () const
const Tensor * beta () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< InstanceNormParams >
const InstanceNormParams & params () const
const InstanceNormParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< InstanceNormParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const InstanceNormParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const InstanceNormParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< InstanceNormParams >
const InstanceNormParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file InstanceNorm.h.
Constructor & Destructor Documentation
InstanceNorm() [1/2]
luci_interpreter::kernels::InstanceNorm::InstanceNorm (const Tensor * input, const Tensor * gamma, const Tensor * beta, Tensor * output, const InstanceNormParams & params)
Definition at line 29 of file InstanceNorm.cpp.
  : KernelWithParams<InstanceNormParams>({input, gamma, beta}, {output}, params)
{
}
References beta(), gamma(), and input().
InstanceNorm() [2/2]
luci_interpreter::kernels::InstanceNorm::InstanceNorm (const Tensor * input, const Tensor * gamma, const Tensor * beta, Tensor * output, const InstanceNormParams & params)
Member Function Documentation
beta() [1/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::beta () const inline
Definition at line 36 of file InstanceNorm.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and InstanceNorm().
beta() [2/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::beta () const inline
Definition at line 36 of file InstanceNorm.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::InstanceNorm::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 35 of file InstanceNorm.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() == 4);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(gamma()->element_type() == input()->element_type());
  LUCI_INTERPRETER_CHECK(gamma()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(gamma()->shape().dim(0) == input()->shape().dim(3) ||
                         gamma()->shape().dim(0) == 1);
  LUCI_INTERPRETER_CHECK(beta()->element_type() == input()->element_type());
  LUCI_INTERPRETER_CHECK(beta()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(beta()->shape().dim(0) == input()->shape().dim(3) ||
                         beta()->shape().dim(0) == 1);
  output()->resize(input()->shape());
}
References beta(), gamma(), input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::InstanceNorm::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::InstanceNorm::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 50 of file InstanceNorm.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::InstanceNorm::execute () const override virtual
Implements luci_interpreter::Kernel.
gamma() [1/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::gamma () const inline
Definition at line 35 of file InstanceNorm.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and InstanceNorm().
gamma() [2/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::gamma () const inline
Definition at line 35 of file InstanceNorm.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
input() [1/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::input () const inline
Definition at line 34 of file InstanceNorm.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and InstanceNorm().
input() [2/2]
const Tensor * luci_interpreter::kernels::InstanceNorm::input () const inline
Definition at line 34 of file InstanceNorm.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::InstanceNorm::output () const inline
Definition at line 37 of file InstanceNorm.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::InstanceNorm::output () const inline
Definition at line 37 of file InstanceNorm.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/InstanceNorm.h
onert-micro/luci-interpreter/src/kernels/InstanceNorm.h
compiler/luci-interpreter/src/kernels/InstanceNorm.cpp
onert-micro/luci-interpreter/src/kernels/InstanceNorm.cpp