ONE - On-device Neural Engine: coco::Part Class Reference
coco::Part Class Reference final
A Part represents the edge between a child Op and its parent Op.
#include <Part.h>
Public Member Functions
Part (Op *parent)
~Part ()
Op * child (void) const
void child (Op *c)
Op * parent (void) const
Detailed Description
A Part represents the edge between a child Op and its parent Op.
Definition at line 28 of file Part.h.
Constructor & Destructor Documentation
Part()
coco::Part::Part (Op * parent) inline
Definition at line 31 of file Part.h.
                   : _parent{parent}
  {
    // DO NOTHING
  }
~Part()
coco::Part::~Part () inline
Definition at line 37 of file Part.h.
{ child(nullptr); }
References child().
Member Function Documentation
child() [1/2]
void coco::Part::child (Op * c)
Definition at line 25 of file Part.cpp.
{
  if (_child != nullptr)
  {
    assert(_child->_part == this);
    _child->_part = nullptr;
    _child = nullptr;
  }
  assert(_child == nullptr);
  if (c != nullptr)
  {
    assert(c->_part == nullptr);
    assert(c->_step == nullptr);
    _child = c;
    _child->_part = this;
  }
}
child() [2/2]
Op * coco::Part::child (void) const inline
Definition at line 40 of file Part.h.
{ return _child; }
Referenced by coco::UnaryOp::arg(), coco::Conv2D::arg(), coco::BinaryOp::left(), coco::BinaryOp::right(), and ~Part().
parent()
Op * coco::Part::parent (void) const inline
Definition at line 44 of file Part.h.
{ return _parent; }
Referenced by coco::Op::parent(), and coco::Op::up().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Part.h
compiler/coco/core/src/IR/Part.cpp