ONE - On-device Neural Engine: kbenchmark::operation::TransposeConv Class Reference
kbenchmark::operation::TransposeConv Class Reference final
#include <TransposeConv.h>
Public Member Functions
TransposeConv ()=default
nonius::parameters params (int layer_num, OperationInfo &info) override
Public Member Functions inherited from kbenchmark::Operation
Operation ()=default
Detailed Description
Definition at line 28 of file TransposeConv.h.
Constructor & Destructor Documentation
TransposeConv()
kbenchmark::operation::TransposeConv::TransposeConv () default
Member Function Documentation
params()
nonius::parameters kbenchmark::operation::TransposeConv::params (int layer_num, OperationInfo & info) inline override virtual
Implements kbenchmark::Operation.
Definition at line 33 of file TransposeConv.h.
  {
    nonius::parameters params;
    params.insert({"LAYER", nonius::param{layer_num}});
    params.insert({"BATCH", nonius::param{1}});
    // TODO The output_shape will be used in Dynamic tensor case
    auto _output_shape = get_key_dims({"input0"}, info);
    auto _weights = get_key_dims({"input1"}, info);
    params.insert({"KER_H", nonius::param{_weights[1]}});
    params.insert({"KER_W", nonius::param{_weights[2]}});
    auto _input = get_key_dims({"input2"}, info);
    params.insert({"IFM_H", nonius::param{_input[1]}});
    params.insert({"IFM_W", nonius::param{_input[2]}});
    params.insert({"IFM_C", nonius::param{_input[3]}});
    auto _output = get_key_dims({"output0"}, info);
    params.insert({"OFM_H", nonius::param{_output[1]}});
    params.insert({"OFM_W", nonius::param{_output[2]}});
    params.insert({"OFM_C", nonius::param{_output[3]}});
    auto _stride_h = get_key_int({"stride_h"}, info);
    auto _stride_w = get_key_int({"stride_w"}, info);
    params.insert({"STRIDE_H", nonius::param{_stride_h}});
    params.insert({"STRIDE_W", nonius::param{_stride_w}});
    auto _pad = get_key_string({"padding"}, info);
    params.insert({"PADDING", nonius::param{_pad}});
    return params;
  }
References _output_shape, kbenchmark::get_key_dims(), kbenchmark::get_key_int(), kbenchmark::get_key_string(), info, and params().
Referenced by params().
The documentation for this class was generated from the following file:
runtime/tools/kbenchmark/operations/TransposeConv.h