ONE - On-device Neural Engine: luci_interpreter::ModuleLoader Class Reference
luci_interpreter::ModuleLoader Class Reference
#include <ModuleLoader.h>
Public Member Functions
ModuleLoader (const luci::Module *module, RuntimeModule *runtime_module, RuntimeToIR &runtime_to_ir, std::unordered_map< const loco::Node *, Tensor * > &node_to_tensor, IMemoryManager *memory_manager)
void load ()
ModuleLoader (const char *model_data_raw, RuntimeModule *runtime_module, IMemoryManager *memory_manager)
void load (bool use_static_memory_manager)
Detailed Description
Definition at line 31 of file ModuleLoader.h.
Constructor & Destructor Documentation
ModuleLoader() [1/2]
luci_interpreter::ModuleLoader::ModuleLoader (const luci::Module * module, RuntimeModule * runtime_module, RuntimeToIR & runtime_to_ir, std::unordered_map< const loco::Node *, Tensor * > & node_to_tensor, IMemoryManager * memory_manager)
Definition at line 24 of file ModuleLoader.cpp.
  : _module(module), _runtime_module(runtime_module), _runtime_to_ir(runtime_to_ir),
    _node_to_tensor(node_to_tensor), _memory_manager(memory_manager)
{
}
ModuleLoader() [2/2]
luci_interpreter::ModuleLoader::ModuleLoader (const char * model_data_raw, RuntimeModule * runtime_module, IMemoryManager * memory_manager)
Definition at line 23 of file ModuleLoader.cpp.
  : _model_data_raw(model_data_raw), _runtime_module(runtime_module),
    _memory_manager(memory_manager), _index_to_tensor(std::unordered_map<int32_t, Tensor *>{})
{
}
Member Function Documentation
load() [1/2]
void luci_interpreter::ModuleLoader::load ()
Definition at line 33 of file ModuleLoader.cpp.
{
  // Runtime graphs have to be created in advance, because they will be needed during the loading
  // process for control flow nodes.
  for (size_t i = 0; i < _module->size(); ++i)
  {
    _graph_to_runtime_graph.emplace(_module->graph(i), _runtime_module->addGraph(_memory_manager));
  }
  for (size_t i = 0; i < _module->size(); ++i)
  {
    const loco::Graph *graph = _module->graph(i);
    RuntimeGraph *runtime_graph = _graph_to_runtime_graph.at(graph);
    GraphLoader loader(graph, runtime_graph, _runtime_to_ir, _graph_to_runtime_graph,
                       _node_to_tensor, _memory_manager);
    loader.loadTensors();
    loader.initInputOutputTensors();
    loader.loadOperators();
  }
}
References luci_interpreter::RuntimeModule::addGraph(), luci::Module::graph(), luci_interpreter::GraphLoader::initInputOutputTensors(), luci_interpreter::GraphLoader::loadOperators(), luci_interpreter::GraphLoader::loadTensors(), and luci::Module::size().
Referenced by luci_interpreter::Interpreter::Interpreter().
load() [2/2]
void luci_interpreter::ModuleLoader::load (bool use_static_memory_manager)
Definition at line 30 of file ModuleLoader.cpp.
{
  const circle::Model *model = circle::GetModel(_model_data_raw);
  CircleReader reader;
  if (!reader.parse(model))
    assert(false && "Error during parse");
  for (size_t i = 0; i < reader.num_subgraph(); ++i)
  {
    _runtime_graphs.emplace_back(
      _runtime_module->addGraph(_memory_manager, use_static_memory_manager));
  }
  for (size_t i = 0; i < reader.num_subgraph(); ++i)
  {
    if (!reader.select_subgraph(i))
      assert(false && "Error during select subgraph");
    IBaseRuntimeGraph *runtime_graph = _runtime_graphs.at(i);
    GraphLoader loader(&reader, runtime_graph, _memory_manager, &_index_to_tensor);
    loader.initInputTensors(use_static_memory_manager);
    loader.loadTensors(use_static_memory_manager);
    loader.loadOperators(use_static_memory_manager);
  }
  // For Dynamic Memory manager we build memory allocate/deallocate plan and then configure kernels.
  // For Static Memory manager we only configure kernels.
  if (not use_static_memory_manager)
  {
    // Dynamic memory manager case
    for (size_t i = 0; i < reader.num_subgraph(); ++i)
    {
      IBaseRuntimeGraph *runtime_graph = _runtime_graphs.at(i);
      runtime_graph->configure();
    }
  }
  else
  {
    // Static memory manager case
    for (size_t i = 0; i < reader.num_subgraph(); ++i)
    {
      _runtime_graphs.at(i)->configure_kernels();
    }
  }
}
References luci_interpreter::RuntimeModule::addGraph(), luci_interpreter::IBaseRuntimeGraph::configure(), luci_interpreter::GraphLoader::initInputTensors(), luci_interpreter::GraphLoader::loadOperators(), luci_interpreter::GraphLoader::loadTensors(), luci::CircleReader::num_subgraph(), luci::CircleReader::parse(), and luci::CircleReader::select_subgraph().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/loader/ModuleLoader.h
onert-micro/luci-interpreter/src/loader/ModuleLoader.h
compiler/luci-interpreter/src/loader/ModuleLoader.cpp
onert-micro/luci-interpreter/src/loader/ModuleLoader.cpp