ONE - On-device Neural Engine: coco::Shuffle Class Reference
coco::Shuffle Class Reference final
Generic element transfer.
#include <Instrs.h>
Public Member Functions
Shuffle ()
Shuffle * asShuffle (void) override
const Shuffle * asShuffle (void) const override
Instr * loc (void) override
Bag * from (void) const
void from (Bag *bag)
Bag * into (void) const
void into (Bag *)
uint32_t size (void) const
Return the number of Element-wise transfers.
std::set< ElemID > range (void) const
Return a set of elements in the destination bag that Shuffle will update.
bool defined (const ElemID &dst) const
Return true if a given elem is updated after execution.
const ElemID & at (const ElemID &dst) const
void insert (const ElemID &from, const ElemID &into)
Public Member Functions inherited from coco::Instr
Instr ()=default
Instr (const Instr &)=delete
Instr (Instr &&)=delete
virtual ~Instr ()
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
const InstrIndex & index (void) const
Public Member Functions inherited from coco::DLinkedList< Child, Parent >::Node
Node ()
virtual ~Node ()
Parent * parent (void) const
Child * prev (void) const
Child * next (void) const
void insertBefore (Node *next)
void insertAfter (Node *prev)
void detach (void)
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Public Member Functions inherited from coco::Bag::Reader
virtual ~Reader ()=default
Public Member Functions inherited from coco::Locatable
virtual ~Locatable ()=default
virtual Instr * loc (void)=0
Public Member Functions inherited from coco::Bag::Updater
virtual ~Updater ()=default
Detailed Description
Generic element transfer.
Definition at line 115 of file Instrs.h.
Constructor & Destructor Documentation
Shuffle()
coco::Shuffle::Shuffle () inline
Definition at line 118 of file Instrs.h.
            : _from{this}, _into{this}
  {
    // DO NOTHING
  }
Member Function Documentation
asShuffle() [1/2]
const Shuffle * coco::Shuffle::asShuffle (void) const inline override
Definition at line 125 of file Instrs.h.
{ return this; }
asShuffle() [2/2]
Shuffle * coco::Shuffle::asShuffle (void) inline override
Definition at line 124 of file Instrs.h.
{ return this; }
Referenced by enco::hoist_object().
at()
const ElemID & coco::Shuffle::at (const ElemID & dst) const inline
Let M be the return of at(N). This means that N-th element in the destination bag will be filled with the value of M-th element in the source bag.
NOTE at(n) may be undefined on partial shuffle
Definition at line 160 of file Instrs.h.
{ return _content.at(dst); }
Referenced by enco::hoist_object().
defined()
bool coco::Shuffle::defined (const ElemID & dst) const inline
Return true if a given elem is updated after execution.
Definition at line 151 of file Instrs.h.
{ return _content.find(dst) != _content.end(); }
from() [1/2]
void coco::Shuffle::from (Bag * bag)
Definition at line 38 of file Shuffle.cpp.
{ _from.bag(b); }
References coco::Read::bag().
from() [2/2]
Bag * coco::Shuffle::from (void) const inline
Definition at line 131 of file Instrs.h.
{ return _from.bag(); }
References coco::Read::bag().
Referenced by enco::generate_bypass_shuffle(), enco::hoist_object(), insert(), enco::lower_copy(), and InstrPrinter::visit().
insert()
void coco::Shuffle::insert (const ElemID & from, const ElemID & into)
Definition at line 36 of file Shuffle.cpp.
{ _content[into] = from; }
References from(), and into().
into() [1/2]
void coco::Shuffle::into (Bag * b)
Definition at line 39 of file Shuffle.cpp.
{ _into.bag(b); }
References coco::Update::bag().
into() [2/2]
Bag * coco::Shuffle::into (void) const inline
Definition at line 135 of file Instrs.h.
{ return _into.bag(); }
References coco::Update::bag().
Referenced by enco::hoist_object(), insert(), and InstrPrinter::visit().
loc()
Instr * coco::Shuffle::loc (void) inline override virtual
Implements coco::Locatable.
Definition at line 128 of file Instrs.h.
{ return this; }
range()
std::set< ElemID > coco::Shuffle::range (void) const
Return a set of elements in the destination bag that Shuffle will update.
Definition at line 24 of file Shuffle.cpp.
{
  std::set<ElemID> res;
  for (auto it = _content.begin(); it != _content.end(); ++it)
  {
    res.insert(it->first);
  }
  return res;
}
size()
uint32_t coco::Shuffle::size (void) const
Return the number of Element-wise transfers.
NOTE size() SHOULD BE identical to range().size()
Definition at line 22 of file Shuffle.cpp.
{ return _content.size(); }
Referenced by tflimport::ReshapeGraphBuilder::build().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Instrs.h
compiler/coco/core/src/IR/Shuffle.cpp