ONE - On-device Neural Engine: SimpleGraph Class Reference
SimpleGraph Class Reference abstract
#include <TestHelper.h>
Public Member Functions
SimpleGraph ()
void init ()
virtual ~SimpleGraph ()=default
void transfer_to (luci::Module *module)
Data Fields
std::unique_ptr< loco::Graph > _g
luci::CircleInput * _input = nullptr
luci::CircleOutput * _output = nullptr
uint32_t _channel_size = 16
uint32_t _width = 4
uint32_t _height = 4
Protected Member Functions
virtual loco::Node * insertGraphBody (loco::Node *input)=0
virtual void initInput (loco::Node *input)
Detailed Description
Definition at line 23 of file TestHelper.h.
Constructor & Destructor Documentation
SimpleGraph()
SimpleGraph::SimpleGraph () inline
Definition at line 26 of file TestHelper.h.
: _g(loco::make_graph()) {}
~SimpleGraph()
virtual SimpleGraph::~SimpleGraph () virtual default
Member Function Documentation
init()
void SimpleGraph::init () inline
Definition at line 29 of file TestHelper.h.
  {
    _input = _g->nodes()->create<luci::CircleInput>();
    _output = _g->nodes()->create<luci::CircleOutput>();
    _input->name("input");
    _output->name("output");
    auto graph_input = _g->inputs()->create();
    _input->index(graph_input->index());
    auto graph_output = _g->outputs()->create();
    _output->index(graph_output->index());
    graph_input->dtype(loco::DataType::FLOAT32);
    _input->dtype(loco::DataType::FLOAT32);
    _output->dtype(loco::DataType::FLOAT32);
    graph_output->dtype(loco::DataType::FLOAT32);
    graph_input->shape({1, _channel_size, _width, _height});
    _input->shape({1, _channel_size, _width, _height});
    _output->shape({1, _channel_size, _width, _height});
    graph_output->shape({1, _channel_size, _width, _height});
    auto graph_body = insertGraphBody(_input);
    _output->from(graph_body);
    initInput(_input);
  }
References _channel_size, _g, _height, _input, _output, _width, luci::CircleOutput::from(), luci::CircleInput::index(), luci::CircleOutput::index(), initInput(), insertGraphBody(), and luci::CircleNode::name().
initInput()
virtual void SimpleGraph::initInput (loco::Node * input) inline protected virtual
Definition at line 68 of file TestHelper.h.
{};
Referenced by init().
insertGraphBody()
virtual loco::Node * SimpleGraph::insertGraphBody (loco::Node * input) protected pure virtual
Referenced by init().
transfer_to()
void SimpleGraph::transfer_to (luci::Module * module) inline
Definition at line 58 of file TestHelper.h.
  {
    // WARNING: after g is transfered, _graph_inputs, _inputs
    //          and _graph_outputs, _outputs in TestOsGraphlet will be invalid.
    //          arrays are not cleared as this is just helpers to unit tests
    module->add(std::move(_g));
  }
References _g.
Field Documentation
_channel_size
uint32_t SimpleGraph::_channel_size = 16
Definition at line 74 of file TestHelper.h.
Referenced by init().
_g
std::unique_ptr<loco::Graph> SimpleGraph::_g
Definition at line 71 of file TestHelper.h.
Referenced by init(), and transfer_to().
_height
uint32_t SimpleGraph::_height = 4
Definition at line 76 of file TestHelper.h.
Referenced by init().
_input
luci::CircleInput* SimpleGraph::_input = nullptr
Definition at line 72 of file TestHelper.h.
Referenced by init().
_output
luci::CircleOutput* SimpleGraph::_output = nullptr
Definition at line 73 of file TestHelper.h.
Referenced by init().
_width
uint32_t SimpleGraph::_width = 4
Definition at line 75 of file TestHelper.h.
Referenced by init().
The documentation for this class was generated from the following file:
compiler/circle-mpqsolver/src/bisection/TestHelper.h