ONE - On-device Neural Engine: onert::ir::operation::Conv2D Class Reference
onert::ir::operation::Conv2D Class Reference
#include <Conv2D.h>
Data Structures
struct Param
Public Types
enum Input { INPUT = 0 , KERNEL , BIAS }
Public Member Functions
Conv2D (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, const Param &param)
void accept (OperationVisitor &v) const override
OpCode opcode () const final
const Param & param () const
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
void replaceInputs (const OperandIndex &from, const OperandIndex &to)
void replaceOutputs (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const
const OperandIndexSequence & getOutputs () const
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Detailed Description
Definition at line 33 of file Conv2D.h.
Member Enumeration Documentation
Input
enum onert::ir::operation::Conv2D::Input
Enumerator
INPUT
KERNEL
BIAS
Definition at line 36 of file Conv2D.h.
  {
    INPUT = 0,
    KERNEL,
    BIAS
  };
Constructor & Destructor Documentation
Conv2D()
onert::ir::operation::Conv2D::Conv2D (const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, const Param & param)
Definition at line 29 of file Conv2D.cc.
  : Operation{OperandConstraint::createExact(3u), inputs, outputs}, _param{param}
{
}
Member Function Documentation
accept()
void onert::ir::operation::Conv2D::accept (OperationVisitor & v) const override virtual
Implements onert::ir::Operation.
Definition at line 27 of file Conv2D.cc.
{ v.visit(*this); }
opcode()
OpCode onert::ir::operation::Conv2D::opcode () const inline final virtual
Implements onert::ir::Operation.
Definition at line 57 of file Conv2D.h.
{ return OpCode::Conv2D; }
param()
const Param & onert::ir::operation::Conv2D::param () const inline
Definition at line 60 of file Conv2D.h.
{ return _param; }
Referenced by onert::backend::cpu::KernelGenerator::visit(), onert::exec::DynamicShapeInferer::visit(), onert::ir::OperationDumper::visit(), and onert::ir::OperationValidator::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/operation/Conv2D.h
runtime/onert/core/src/ir/operation/Conv2D.cc