ONE - On-device Neural Engine: onert::ir::NNPkg Class Reference
onert::ir::NNPkg Class Reference
#include <NNPkg.h>
Public Member Functions
NNPkg ()=default
NNPkg (const NNPkg &obj)=default
NNPkg (NNPkg &&)=default
NNPkg & operator= (const NNPkg &)=default
NNPkg & operator= (NNPkg &&)=default
~NNPkg ()=default
NNPkg (std::shared_ptr< Model > model)
std::shared_ptr< Model > primary_model () const
void push (ModelIndex index, const std::shared_ptr< Model > &model)
Put model at index.
size_t model_count () const
Get the count of model.
const std::shared_ptr< Model > & model (const ModelIndex &index) const
Get model at index.
std::shared_ptr< Model > & model (const ModelIndex &index)
Get model at index.
const IODesc & input (const ir::IOIndex &index) const
Get pkg_input at index.
IODesc & input (const ir::IOIndex &index)
Get pkg_input at index.
void addInput (const IODesc &input)
Add input at the end.
const IODesc & output (const ir::IOIndex &index) const
Get pkg_output at index.
IODesc & output (const ir::IOIndex &index)
Get pkg_output at index.
void addOutput (const IODesc &output)
Add output at the end.
void addEdge (const IODesc &from, const IODesc &to)
Add edge between models at the end.
const ModelEdges & model_edges ()
Get model edge set.
void verify (void)
Verify NNPkg.
uint32_t inputSize () const
Get model input size.
uint32_t inputSize (SubgraphIndex subg_index) const
uint32_t outputSize () const
Get model output size.
uint32_t outputSize (SubgraphIndex subg_index) const
const OperandInfo & inputInfo (const ir::IOIndex &index) const
Get model input info.
const OperandInfo & inputInfo (SubgraphIndex subg_index, uint32_t index) const
const OperandInfo & outputInfo (const ir::IOIndex &index) const
Get model output info.
const OperandInfo & outputInfo (SubgraphIndex subg_index, uint32_t index) const
void changeInputShape (const ir::IOIndex &index, const ir::Shape &new_shape)
void changeInputShape (SubgraphIndex subg_index, uint32_t index, const ir::Shape &new_shape)
void replaceModel (std::shared_ptr< Model > model)
Replace model.
Detailed Description
Definition at line 83 of file NNPkg.h.
Constructor & Destructor Documentation
NNPkg() [1/4]
onert::ir::NNPkg::NNPkg () default
NNPkg() [2/4]
onert::ir::NNPkg::NNPkg (const NNPkg & obj) default
NNPkg() [3/4]
onert::ir::NNPkg::NNPkg (NNPkg &&) default
~NNPkg()
onert::ir::NNPkg::~NNPkg () default
NNPkg() [4/4]
onert::ir::NNPkg::NNPkg (std::shared_ptr< Model > model) inline
Definition at line 93 of file NNPkg.h.
  {
    _models[ModelIndex{0}] = model;
    // Fill pkg_inputs and pkg_outputs with primary model's inputs and outputs
    for (uint32_t i = 0; i < model->primary_subgraph()->getInputs().size(); i++)
      _edges.pkg_inputs.emplace_back(0, 0, IOIndex{i});
    for (uint32_t i = 0; i < model->primary_subgraph()->getOutputs().size(); i++)
      _edges.pkg_outputs.emplace_back(0, 0, IOIndex{i});
  }
References model(), onert::ir::ModelEdges::pkg_inputs, onert::ir::ModelEdges::pkg_outputs, and size.
Member Function Documentation
addEdge()
void onert::ir::NNPkg::addEdge (const IODesc & from, const IODesc & to) inline
Add edge between models at the end.
Parameters
[in] from from IODesc
[in] to to IODesc
Definition at line 183 of file NNPkg.h.
{ _edges.edges.insert(ModelEdge{from, to}); }
References onert::ir::ModelEdges::edges.
addInput()
void onert::ir::NNPkg::addInput (const IODesc & input) inline
Add input at the end.
Parameters
[in] input Input IODesc to be pushed
Definition at line 154 of file NNPkg.h.
{ _edges.pkg_inputs.push_back(input); }
References input(), and onert::ir::ModelEdges::pkg_inputs.
addOutput()
void onert::ir::NNPkg::addOutput (const IODesc & output) inline
Add output at the end.
Parameters
[in] output Output IODesc to be pushed
Definition at line 175 of file NNPkg.h.
{ _edges.pkg_outputs.push_back(output); }
References output(), and onert::ir::ModelEdges::pkg_outputs.
changeInputShape() [1/2]
void onert::ir::NNPkg::changeInputShape (const ir::IOIndex & index, const ir::Shape & new_shape) inline
Definition at line 310 of file NNPkg.h.
  {
    if (_models.size() == 1)
    {
      auto graph = primary_model()->primary_subgraph();
      auto const operand_index = graph->getInputs().at(index);
      graph->changeShape(operand_index, new_shape);
      return;
    }
    auto const &desc = input(index);
    auto graph = model(std::get<ModelIndex>(desc))->primary_subgraph();
    auto const operand_index = graph->getInputs().at(std::get<IOIndex>(desc).value());
    graph->changeShape(operand_index, new_shape);
  }
References input(), model(), and primary_model().
changeInputShape() [2/2]
void onert::ir::NNPkg::changeInputShape (SubgraphIndex subg_index, uint32_t index, const ir::Shape & new_shape) inline
Definition at line 326 of file NNPkg.h.
  {
    // signature entry is supported for single model only
    assert(_models.size() == 1);
    auto graph = primary_model()->at(subg_index);
    auto const operand_index = graph->getInputs().at(index);
    graph->changeShape(operand_index, new_shape);
    return;
  }
References primary_model().
input() [1/2]
IODesc & onert::ir::NNPkg::input (const ir::IOIndex & index) inline
Get pkg_input at index.
Parameters
[in] index Index of pkg_input to be returned
Returns
IODesc at index
Definition at line 148 of file NNPkg.h.
{ return _edges.pkg_inputs[index.value()]; }
References onert::ir::ModelEdges::pkg_inputs.
input() [2/2]
const IODesc & onert::ir::NNPkg::input (const ir::IOIndex & index) const inline
Get pkg_input at index.
Parameters
[in] index Index of pkg_input to be returned
Returns
IODesc at index
Definition at line 141 of file NNPkg.h.
{ return _edges.pkg_inputs[index.value()]; }
References onert::ir::ModelEdges::pkg_inputs.
Referenced by addInput(), changeInputShape(), and inputInfo().
inputInfo() [1/2]
const OperandInfo & onert::ir::NNPkg::inputInfo (const ir::IOIndex & index) const inline
Get model input info.
Definition at line 256 of file NNPkg.h.
  {
    if (_models.size() == 1)
    {
      auto const graph = primary_model()->primary_subgraph();
      auto const operand_index = graph->getInputs().at(index);
      return graph->operands().at(operand_index).info();
    }
    auto const &desc = input(index);
    auto const graph = model(std::get<ModelIndex>(desc))->primary_subgraph();
    auto const operand_index = graph->getInputs().at(std::get<IOIndex>(desc).value());
    return graph->operands().at(operand_index).info();
  }
References input(), model(), and primary_model().
inputInfo() [2/2]
const OperandInfo & onert::ir::NNPkg::inputInfo (SubgraphIndex subg_index, uint32_t index) const inline
Definition at line 271 of file NNPkg.h.
  {
    // signature entry is supported for single model only
    assert(_models.size() == 1);
    auto const graph = primary_model()->at(subg_index);
    auto const operand_index = graph->getInputs().at(index);
    return graph->operands().at(operand_index).info();
  }
References primary_model().
inputSize() [1/2]
uint32_t onert::ir::NNPkg::inputSize () const inline
Get model input size.
Definition at line 224 of file NNPkg.h.
  {
    return _models.size() == 1 ? primary_model()->primary_subgraph()->getInputs().size()
                               : _edges.pkg_inputs.size();
  }
References onert::ir::ModelEdges::pkg_inputs, and primary_model().
inputSize() [2/2]
uint32_t onert::ir::NNPkg::inputSize (SubgraphIndex subg_index) const inline
Definition at line 230 of file NNPkg.h.
  {
    // signature entry is supported for single model only
    assert(_models.size() == 1);
    return primary_model()->at(subg_index)->getInputs().size();
  }
References primary_model().
model() [1/2]
std::shared_ptr< Model > & onert::ir::NNPkg::model (const ModelIndex & index) inline
Get model at index.
Parameters
[in] index Index of the model to be returned
Returns
Model at index
Definition at line 133 of file NNPkg.h.
{ return _models.at(index); }
model() [2/2]
const std::shared_ptr< Model > & onert::ir::NNPkg::model (const ModelIndex & index) const inline
Get model at index.
Parameters
[in] index Index of the model to be returned
Returns
Model at index
Definition at line 126 of file NNPkg.h.
{ return _models.at(index); }
Referenced by changeInputShape(), inputInfo(), NNPkg(), outputInfo(), push(), and replaceModel().
model_count()
size_t onert::ir::NNPkg::model_count () const inline
Get the count of model.
Returns
the count of models
Definition at line 118 of file NNPkg.h.
{ return _models.size(); }
model_edges()
const ModelEdges & onert::ir::NNPkg::model_edges () inline
Get model edge set.
Returns
Edge set reference
Definition at line 188 of file NNPkg.h.
{ return _edges; }
operator=() [1/2]
NNPkg & onert::ir::NNPkg::operator= (const NNPkg &) default
operator=() [2/2]
NNPkg & onert::ir::NNPkg::operator= (NNPkg &&) default
output() [1/2]
IODesc & onert::ir::NNPkg::output (const ir::IOIndex & index) inline
Get pkg_output at index.
Parameters
[in] index Index of pkg_output to be returned
Returns
IODesc at index
Definition at line 169 of file NNPkg.h.
{ return _edges.pkg_outputs[index.value()]; }
References onert::ir::ModelEdges::pkg_outputs.
output() [2/2]
const IODesc & onert::ir::NNPkg::output (const ir::IOIndex & index) const inline
Get pkg_output at index.
Parameters
[in] index Index of pkg_output to be returned
Returns
IODesc at index
Definition at line 162 of file NNPkg.h.
{ return _edges.pkg_outputs[index.value()]; }
References onert::ir::ModelEdges::pkg_outputs.
Referenced by addOutput(), and outputInfo().
outputInfo() [1/2]
const OperandInfo & onert::ir::NNPkg::outputInfo (const ir::IOIndex & index) const inline
Get model output info.
Definition at line 284 of file NNPkg.h.
  {
    if (_models.size() == 1)
    {
      auto const graph = primary_model()->primary_subgraph();
      auto const operand_index = graph->getOutputs().at(index);
      return graph->operands().at(operand_index).info();
    }
    auto const &desc = output(index);
    auto const graph = model(std::get<ModelIndex>(desc))->primary_subgraph();
    auto const operand_index = graph->getOutputs().at(std::get<IOIndex>(desc).value());
    return graph->operands().at(operand_index).info();
  }
References model(), output(), and primary_model().
outputInfo() [2/2]
const OperandInfo & onert::ir::NNPkg::outputInfo (SubgraphIndex subg_index, uint32_t index) const inline
Definition at line 299 of file NNPkg.h.
  {
    // signature entry is supported for single model only
    assert(_models.size() == 1);
    auto const graph = primary_model()->at(subg_index);
    auto const operand_index = graph->getOutputs().at(index);
    return graph->operands().at(operand_index).info();
  }
References primary_model().
outputSize() [1/2]
uint32_t onert::ir::NNPkg::outputSize () const inline
Get model output size.
Definition at line 240 of file NNPkg.h.
  {
    return _models.size() == 1 ? primary_model()->primary_subgraph()->getOutputs().size()
                               : _edges.pkg_outputs.size();
  }
References onert::ir::ModelEdges::pkg_outputs, and primary_model().
outputSize() [2/2]
uint32_t onert::ir::NNPkg::outputSize (SubgraphIndex subg_index) const inline
Definition at line 246 of file NNPkg.h.
  {
    // signature entry is supported for single model only
    assert(_models.size() == 1);
    return primary_model()->at(subg_index)->getOutputs().size();
  }
References primary_model().
primary_model()
std::shared_ptr< Model > onert::ir::NNPkg::primary_model () const inline
Definition at line 103 of file NNPkg.h.
{ return _models.at(onert::ir::ModelIndex{0}); }
Referenced by changeInputShape(), changeInputShape(), inputInfo(), inputInfo(), inputSize(), inputSize(), outputInfo(), outputInfo(), outputSize(), and outputSize().
push()
void onert::ir::NNPkg::push (ModelIndex index, const std::shared_ptr< Model > & model) inline
Put model at index.
Parameters
[in] model Model to be pushed
[in] index Index where Model is to be pushed
Definition at line 111 of file NNPkg.h.
{ _models[index] = model; }
References model().
replaceModel()
void onert::ir::NNPkg::replaceModel (std::shared_ptr< Model > model) inline
Replace model.
Parameters
[in] model Model to be replaced
TODO: Support multiple models
Definition at line 344 of file NNPkg.h.
{ _models[ModelIndex{0}] = model; }
References model().
verify()
void onert::ir::NNPkg::verify (void) inline
Verify NNPkg.
Definition at line 194 of file NNPkg.h.
  {
    // Verify edges information
    //
    // Only duplicates of nnpkg output and Edge `from` are possible.
    // | Whether duplicates are possible   | Edge `to` | Edge `from` |
    // | nnpkg input  (input of subgraph)  | X (*1)    | X (*2)      |
    // | nnpkg output (output of subgraph) | X (*2)    | O           |
    // *1. The subjects who determine values of each buffer are different.
    //    - nnpkg input : user input
    //    - Edge `to`   : output of another subgraph
    // *2. `IOIndex` of inputs and outputs of subgraph is distinct.
    //
    for (const auto &edge : _edges.edges)
    {
      if (std::find(_edges.pkg_inputs.begin(), _edges.pkg_inputs.end(), edge.to) !=
          _edges.pkg_inputs.end())
      {
        throw std::runtime_error{
          "Invalid edge information. NNPkg inputs and Edge `to` cannot be duplicated"};
      }
    }
  }
References onert::ir::ModelEdges::edges, and onert::ir::ModelEdges::pkg_inputs.
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/NNPkg.h