ONE - On-device Neural Engine: onert::util::Set< Element > Class Template Reference
onert::util::Set< Element > Class Template Reference
Class for set of custom element &.
#include <Set.h>
Public Member Functions
Set ()=default
Construct default Set object.
Set (const Set< Element > &)=default
Construct Set object by copy semantics.
Set (Set< Element > &&)=default
Construct move Set object by move semantics.
void add (const Element &e)
Add a given element to the set.
void remove (const Element &e)
remove a given element from the set
uint32_t size () const
Get size of the set.
bool empty () const
Get whether the set is empty.
bool contains (const Element &e) const
Get whether a given element exists in the set.
const Element & getOnlyElement () const
Get first element of the set.
Set< Element > operator| (const Set< Element > &other) const
operator overloading function for |
Set< Element > operator& (const Set< Element > &other) const
operator overloading function for &
Set< Element > operator- (const Set< Element > &other) const
operator overloading function for -
std::unordered_set< Element >::const_iterator begin () const
begin() of const_iterator for this class
std::unordered_set< Element >::const_iterator end () const
end() of const_iterator for this class
Detailed Description
template<typename Element>
class onert::util::Set< Element >
Class for set of custom element &.
Template Parameters
Element Key type of Set
Definition at line 38 of file Set.h.
Constructor & Destructor Documentation
Set() [1/3]
template<typename Element > onert::util::Set< Element >::Set () default
Construct default Set object.
Set() [2/3]
template<typename Element > onert::util::Set< Element >::Set (const Set< Element > &) default
Construct Set object by copy semantics.
Set() [3/3]
template<typename Element > onert::util::Set< Element >::Set (Set< Element > &&) default
Construct move Set object by move semantics.
Member Function Documentation
add()
template<typename Element > void onert::util::Set< Element >::add (const Element & e) inline
Add a given element to the set.
Parameters
e Element added
Definition at line 60 of file Set.h.
{ _set.insert(e); }
Referenced by onert::compiler::OperandLowerInfo::addDefPermuteFactor(), onert::compiler::OperandLowerInfo::addUsePermuteFactor(), onert::exec::ParallelExecutor::executeImpl(), onert::util::Set< Element >::operator&(), onert::compiler::pass::UnusedOperandEliminationPass::run(), and onert::ir::Graph::topolSortOperations().
begin()
template<typename Element > std::unordered_set< Element >::const_iterator onert::util::Set< Element >::begin () const inline
begin() of const_iterator for this class
Returns
The first iterator of the set
Definition at line 151 of file Set.h.
{ return _set.begin(); }
contains()
template<typename Element > bool onert::util::Set< Element >::contains (const Element & e) const inline
Get whether a given element exists in the set.
Parameters
e A given element
Returns
Whether a given element exists in the set
Definition at line 86 of file Set.h.
{ return _set.find(e) != _set.end(); }
Referenced by onert::util::Set< Element >::operator&(), onert::compiler::pass::UnusedOperandEliminationPass::run(), and onert::ir::Graph::topolSortOperations().
empty()
template<typename Element > bool onert::util::Set< Element >::empty () const inline
Get whether the set is empty.
Returns
Whether the set is empty
Definition at line 78 of file Set.h.
{ return _set.empty(); }
Referenced by onert::exec::ParallelScheduler::ParallelScheduler(), and onert::ir::Graph::topolSortOperations().
end()
template<typename Element > std::unordered_set< Element >::const_iterator onert::util::Set< Element >::end () const inline
end() of const_iterator for this class
Returns
The last iterator of the set
Definition at line 157 of file Set.h.
{ return _set.end(); }
getOnlyElement()
template<typename Element > const Element & onert::util::Set< Element >::getOnlyElement () const inline
Get first element of the set.
Returns
first element of the set
Definition at line 92 of file Set.h.
  {
    assert(_set.size() == 1u);
    return *_set.begin();
  }
operator&()
template<typename Element > Set< Element > onert::util::Set< Element >::operator& (const Set< Element > & other) const inline
operator overloading function for &
Returns
A set of elements that overlap in two sets
Definition at line 118 of file Set.h.
  {
    Set<Element> ret;
    for (auto e : other)
    {
      if (contains(e))
      {
        ret.add(e);
      }
    }
    return ret;
  }
References onert::util::Set< Element >::add(), and onert::util::Set< Element >::contains().
operator-()
template<typename Element > Set< Element > onert::util::Set< Element >::operator- (const Set< Element > & other) const inline
operator overloading function for -
Returns
A set of subtracted from another set
Definition at line 135 of file Set.h.
  {
    auto ret = *this;
    for (auto e : other)
    {
      ret.remove(e);
    }
    return ret;
  }
operator|()
template<typename Element > Set< Element > onert::util::Set< Element >::operator| (const Set< Element > & other) const inline
operator overloading function for |
Returns
A set with two sets combined
Definition at line 104 of file Set.h.
  {
    auto ret = *this;
    for (auto e : other)
    {
      ret.add(e);
    }
    return ret;
  }
remove()
template<typename Element > void onert::util::Set< Element >::remove (const Element & e) inline
remove a given element from the set
Parameters
e Element removed
Definition at line 66 of file Set.h.
{ _set.erase(e); }
Referenced by onert::compiler::OperandLowerInfo::removeDefPermuteFactor(), onert::compiler::OperandLowerInfo::removeUsePermuteFactor(), and onert::ir::Graph::topolSortOperations().
size()
template<typename Element > uint32_t onert::util::Set< Element >::size () const inline
Get size of the set.
Returns
The size of the set
Definition at line 72 of file Set.h.
{ return static_cast<uint32_t>(_set.size()); }
The documentation for this class was generated from the following file:
runtime/onert/core/include/util/Set.h