ONE - On-device Neural Engine: loco::Permutation< Domain::DepthwiseFilter > Class Reference
loco::Permutation< Domain::DepthwiseFilter > Class Reference
Mapping between DepthwiseFilter/Tensor Axis.
#include <PermutingCodec.h>
Public Member Functions
Permutation ()=default
bool mapped (const DepthwiseFilterAxis &axis_f) const
Return whether a given depthwise filter axis has a corresponding tensor axis.
const TensorAxis & axis (const DepthwiseFilterAxis &axis_f) const
Get the tensor axis corresponding to a given depthwise filter axis.
TensorAxis & axis (const DepthwiseFilterAxis &axis_f)
Set the tensor axis corresponding to a given depthwise filter axis.
TensorAxis operator[] (const DepthwiseFilterAxis &axis_f) const
TensorAxis & operator[] (const DepthwiseFilterAxis &axis_f)
Detailed Description
Mapping between DepthwiseFilter/Tensor Axis.
Definition at line 232 of file PermutingCodec.h.
Constructor & Destructor Documentation
Permutation()
loco::Permutation< Domain::DepthwiseFilter >::Permutation () default
Member Function Documentation
axis() [1/2]
uint32_t & loco::Permutation< Domain::DepthwiseFilter >::axis (const DepthwiseFilterAxis & axis_f)
Set the tensor axis corresponding to a given depthwise filter axis.
Definition at line 417 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid depthwise filter axis");
  return _map[axis_f];
}
References loco::valid().
axis() [2/2]
const uint32_t & loco::Permutation< Domain::DepthwiseFilter >::axis (const DepthwiseFilterAxis & axis_f) const
Get the tensor axis corresponding to a given depthwise filter axis.
This method works correctly only for mapped depthwise filter axes.
Definition at line 410 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid depthwise filter axis");
  assert(mapped(axis_f) && "unmapped depthwise filter axis");
  return _map.at(axis_f);
}
References loco::valid().
mapped()
bool loco::Permutation< Domain::DepthwiseFilter >::mapped (const DepthwiseFilterAxis & axis_f) const
Return whether a given depthwise filter axis has a corresponding tensor axis.
This method does not validate the corresponding value.
Definition at line 404 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid depthwise filter axis");
  return _map.find(axis_f) != _map.end();
}
References loco::valid().
operator[]() [1/2]
TensorAxis & loco::Permutation< Domain::DepthwiseFilter >::operator[] (const DepthwiseFilterAxis & axis_f) inline
Definition at line 258 of file PermutingCodec.h.
{ return axis(axis_f); }
operator[]() [2/2]
TensorAxis loco::Permutation< Domain::DepthwiseFilter >::operator[] (const DepthwiseFilterAxis & axis_f) const inline
Definition at line 257 of file PermutingCodec.h.
{ return axis(axis_f); }
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp