ONE - On-device Neural Engine: luci::CloneNodeLet< CN::KLMN > Class Reference
luci::CloneNodeLet< CN::KLMN > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleL2Normalize *) final
luci::CircleNode * visit (const luci::CircleL2Pool2D *) final
luci::CircleNode * visit (const luci::CircleLeakyRelu *) final
luci::CircleNode * visit (const luci::CircleLess *) final
luci::CircleNode * visit (const luci::CircleLessEqual *) final
luci::CircleNode * visit (const luci::CircleLocalResponseNormalization *) final
luci::CircleNode * visit (const luci::CircleLog *) final
luci::CircleNode * visit (const luci::CircleLogicalAnd *) final
luci::CircleNode * visit (const luci::CircleLogicalNot *) final
luci::CircleNode * visit (const luci::CircleLogicalOr *) final
luci::CircleNode * visit (const luci::CircleLogistic *) final
luci::CircleNode * visit (const luci::CircleLogSoftmax *) final
luci::CircleNode * visit (const luci::CircleMatrixDiag *) final
luci::CircleNode * visit (const luci::CircleMatrixSetDiag *) final
luci::CircleNode * visit (const luci::CircleMaximum *) final
luci::CircleNode * visit (const luci::CircleMaxPool2D *) final
luci::CircleNode * visit (const luci::CircleMean *) final
luci::CircleNode * visit (const luci::CircleMinimum *) final
luci::CircleNode * visit (const luci::CircleMirrorPad *) final
luci::CircleNode * visit (const luci::CircleMul *) final
luci::CircleNode * visit (const luci::CircleNeg *) final
luci::CircleNode * visit (const luci::CircleNonMaxSuppressionV4 *) final
luci::CircleNode * visit (const luci::CircleNonMaxSuppressionV5 *) final
luci::CircleNode * visit (const luci::CircleNotEqual *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 115 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::KLMN >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 118 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleL2Normalize * node) final
Definition at line 22 of file CircleL2Normalize.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleL2Normalize>();
  if (cloned != nullptr)
    cloned->fusedActivationFunction(node->fusedActivationFunction());
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), and luci::UNDEFINED.
visit() [2/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleL2Pool2D * node) final
Definition at line 22 of file CircleL2Pool2D.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleL2Pool2D>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->padding(node->padding());
    cloned->filter()->h(node->filter()->h());
    cloned->filter()->w(node->filter()->w());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
  }
  return cloned;
}
References luci::CircleL2Pool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::Filter::h(), luci::Stride::h(), luci::CircleL2Pool2D::padding(), luci::CircleL2Pool2D::stride(), luci::UNDEFINED, luci::Filter::w(), and luci::Stride::w().
visit() [3/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLeakyRelu * node) final
Definition at line 22 of file CircleLeakyRelu.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleLeakyRelu>();
  if (cloned != nullptr)
    cloned->alpha(node->alpha());
  return cloned;
}
References luci::CircleLeakyRelu::alpha().
visit() [4/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLess *) final
Definition at line 22 of file CircleLess.cpp.
{
  return _graph->nodes()->create<luci::CircleLess>();
}
visit() [5/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLessEqual *) final
Definition at line 22 of file CircleLessEqual.cpp.
{
  return _graph->nodes()->create<luci::CircleLessEqual>();
}
visit() [6/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLocalResponseNormalization * node) final
Definition at line 22 of file CircleLocalResponseNormalization.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleLocalResponseNormalization>();
  if (cloned != nullptr)
  {
    cloned->radius(node->radius());
    cloned->bias(node->bias());
    cloned->alpha(node->alpha());
    cloned->beta(node->beta());
  }
  return cloned;
}
References luci::CircleLocalResponseNormalization::alpha(), luci::CircleLocalResponseNormalization::beta(), luci::CircleLocalResponseNormalization::bias(), and luci::CircleLocalResponseNormalization::radius().
visit() [7/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLog *) final
Definition at line 22 of file CircleLog.cpp.
{
  return _graph->nodes()->create<luci::CircleLog>();
}
visit() [8/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLogicalAnd *) final
Definition at line 22 of file CircleLogicalAnd.cpp.
{
  return _graph->nodes()->create<luci::CircleLogicalAnd>();
}
visit() [9/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLogicalNot *) final
Definition at line 22 of file CircleLogicalNot.cpp.
{
  return _graph->nodes()->create<luci::CircleLogicalNot>();
}
visit() [10/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLogicalOr *) final
Definition at line 22 of file CircleLogicalOr.cpp.
{
  return _graph->nodes()->create<luci::CircleLogicalOr>();
}
visit() [11/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLogistic *) final
Definition at line 22 of file CircleLogistic.cpp.
{
  return _graph->nodes()->create<luci::CircleLogistic>();
}
visit() [12/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleLogSoftmax *) final
Definition at line 22 of file CircleLogSoftmax.cpp.
{
  return _graph->nodes()->create<luci::CircleLogSoftmax>();
}
visit() [13/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMatrixDiag *) final
Definition at line 22 of file CircleMatrixDiag.cpp.
{
  return _graph->nodes()->create<luci::CircleMatrixDiag>();
}
visit() [14/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMatrixSetDiag *) final
Definition at line 22 of file CircleMatrixSetDiag.cpp.
{
  return _graph->nodes()->create<luci::CircleMatrixSetDiag>();
}
visit() [15/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMaximum *) final
Definition at line 22 of file CircleMaximum.cpp.
{
  return _graph->nodes()->create<luci::CircleMaximum>();
}
visit() [16/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMaxPool2D * node) final
Definition at line 22 of file CircleMaxPool2D.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleMaxPool2D>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->padding(node->padding());
    cloned->filter()->h(node->filter()->h());
    cloned->filter()->w(node->filter()->w());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
  }
  return cloned;
}
References luci::CircleMaxPool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::Filter::h(), luci::Stride::h(), luci::CircleMaxPool2D::padding(), luci::CircleMaxPool2D::stride(), luci::UNDEFINED, luci::Filter::w(), and luci::Stride::w().
visit() [17/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMean * node) final
Definition at line 22 of file CircleMean.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleMean>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleMean::keep_dims().
visit() [18/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMinimum *) final
Definition at line 22 of file CircleMinimum.cpp.
{
  return _graph->nodes()->create<luci::CircleMinimum>();
}
visit() [19/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMirrorPad * node) final
Definition at line 22 of file CircleMirrorPad.cpp.
{
  if (node->mode() == luci::MirrorPadMode::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleMirrorPad>();
  if (cloned != nullptr)
    cloned->mode(node->mode());
  return cloned;
}
References luci::CircleMirrorPad::mode(), and luci::UNDEFINED.
visit() [20/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleMul * node) final
Definition at line 22 of file CircleMul.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleMul>();
  if (cloned != nullptr)
    cloned->fusedActivationFunction(node->fusedActivationFunction());
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), and luci::UNDEFINED.
visit() [21/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleNeg *) final
Definition at line 22 of file CircleNeg.cpp.
{
  return _graph->nodes()->create<luci::CircleNeg>();
}
visit() [22/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 146 of file CircleCloneNode.h.
{ return nullptr; }
visit() [23/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleNonMaxSuppressionV4 *) final
Definition at line 22 of file CircleNonMaxSuppressionV4.cpp.
{
  return _graph->nodes()->create<luci::CircleNonMaxSuppressionV4>();
}
visit() [24/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleNonMaxSuppressionV5 *) final
Definition at line 22 of file CircleNonMaxSuppressionV5.cpp.
{
  return _graph->nodes()->create<luci::CircleNonMaxSuppressionV5>();
}
visit() [25/25]
luci::CircleNode * luci::CloneNodeLet< CN::KLMN >::visit (const luci::CircleNotEqual *) final
Definition at line 22 of file CircleNotEqual.cpp.
{
  return _graph->nodes()->create<luci::CircleNotEqual>();
}
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::KLMN >::_graph = nullptr protected
Definition at line 149 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleL2Normalize.cpp
compiler/luci/service/src/Nodes/CircleL2Pool2D.cpp
compiler/luci/service/src/Nodes/CircleLeakyRelu.cpp
compiler/luci/service/src/Nodes/CircleLess.cpp
compiler/luci/service/src/Nodes/CircleLessEqual.cpp
compiler/luci/service/src/Nodes/CircleLocalResponseNormalization.cpp
compiler/luci/service/src/Nodes/CircleLog.cpp
compiler/luci/service/src/Nodes/CircleLogicalAnd.cpp
compiler/luci/service/src/Nodes/CircleLogicalNot.cpp
compiler/luci/service/src/Nodes/CircleLogicalOr.cpp
compiler/luci/service/src/Nodes/CircleLogistic.cpp
compiler/luci/service/src/Nodes/CircleLogSoftmax.cpp
compiler/luci/service/src/Nodes/CircleMatrixDiag.cpp
compiler/luci/service/src/Nodes/CircleMatrixSetDiag.cpp
compiler/luci/service/src/Nodes/CircleMaximum.cpp
compiler/luci/service/src/Nodes/CircleMaxPool2D.cpp
compiler/luci/service/src/Nodes/CircleMean.cpp
compiler/luci/service/src/Nodes/CircleMinimum.cpp
compiler/luci/service/src/Nodes/CircleMirrorPad.cpp
compiler/luci/service/src/Nodes/CircleMul.cpp
compiler/luci/service/src/Nodes/CircleNeg.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV4.cpp
compiler/luci/service/src/Nodes/CircleNonMaxSuppressionV5.cpp
compiler/luci/service/src/Nodes/CircleNotEqual.cpp