ONE - On-device Neural Engine: moco::FuseBinaryIntoPreceding Class Reference
moco::FuseBinaryIntoPreceding Class Reference
Fuse TFAdd, TFMul to preceding TFConv2D or TFDepthWiseConv2D.
#include <FuseBinaryIntoPreceding.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *graph) override
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Fuse TFAdd, TFMul to preceding TFConv2D or TFDepthWiseConv2D.
Definition at line 30 of file FuseBinaryIntoPreceding.h.
Member Function Documentation
name()
const char * moco::FuseBinaryIntoPreceding::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 33 of file FuseBinaryIntoPreceding.h.
{ return "FuseBinaryIntoPreceding"; }
run()
bool moco::FuseBinaryIntoPreceding::run (loco::Graph * graph) override virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 500 of file FuseBinaryIntoPreceding.cpp.
{
  bool changed = false;
  auto active_nodes = loco::active_nodes(loco::output_nodes(graph));
  for (auto node : active_nodes)
  {
    if (node->dialect() == moco::TFDialect::get())
    {
      {
        auto tf_node = dynamic_cast<moco::TFMul *>(node);
        if (tf_node != nullptr)
        {
          if (fuse_to_preceding(graph, tf_node))
            changed = true;
        }
      }
      {
        // TODO support Div
      }
      {
        auto tf_node = dynamic_cast<moco::TFAdd *>(node);
        if (tf_node != nullptr)
        {
          if (fuse_to_preceding(graph, tf_node))
            changed = true;
        }
      }
      {
        // TODO support Sub
      }
    }
  }
  return changed;
}
References loco::active_nodes(), moco::TFNode::dialect(), moco::TFDialect::get(), and loco::output_nodes().
The documentation for this class was generated from the following files:
compiler/moco/pass/include/moco/Pass/Passes/FuseBinaryIntoPreceding.h
compiler/moco/pass/src/Passes/FuseBinaryIntoPreceding.cpp