ONE - On-device Neural Engine: luci_interpreter::IBaseRuntimeGraph Class Reference
luci_interpreter::IBaseRuntimeGraph Class Reference abstract
#include <RuntimeGraph.h>
Public Member Functions
IBaseRuntimeGraph (IMemoryManager *memory_manager)
virtual ~IBaseRuntimeGraph ()=default
Tensor * addTensor (std::unique_ptr< Tensor > &&tensor)
AffineQuantization * addAffineQuantization (std::unique_ptr< AffineQuantization > &&quantization)
void addIntermediateTensorAffineQuantization (AffineQuantization *intermediate_tensor)
void addInputTensor (Tensor *input_tensor)
void addOutputTensor (Tensor *output_tensor)
void configureAllocations (Tensor *tensor)
const std::vector< AffineQuantization * > & getIntermediateAffineQuantizations () const
const std::vector< Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
void addKernel (std::unique_ptr< Kernel > &&kernel)
virtual void execute ()=0
virtual void configure ()=0
virtual void configure_kernels ()=0
void invalidate ()
bool isValid () const
Protected Attributes
IMemoryManager * _memory_manager
std::vector< std::unique_ptr< Tensor > > _tensors
std::vector< std::unique_ptr< AffineQuantization > > _affine_quantizations
std::vector< Tensor * > _input_tensors
std::vector< AffineQuantization * > _intermediate_tensors_affine_quantizations
std::vector< Tensor * > _output_tensors
bool _is_valid = false
std::vector< std::unique_ptr< Kernel > > _kernels
Detailed Description
Definition at line 32 of file RuntimeGraph.h.
Constructor & Destructor Documentation
IBaseRuntimeGraph()
luci_interpreter::IBaseRuntimeGraph::IBaseRuntimeGraph (IMemoryManager * memory_manager) explicit
Definition at line 27 of file RuntimeGraph.cpp.
  : _memory_manager(memory_manager)
{
}
~IBaseRuntimeGraph()
virtual luci_interpreter::IBaseRuntimeGraph::~IBaseRuntimeGraph () virtual default
Member Function Documentation
addAffineQuantization()
AffineQuantization * luci_interpreter::IBaseRuntimeGraph::addAffineQuantization (std::unique_ptr< AffineQuantization > && quantization)
Definition at line 40 of file RuntimeGraph.cpp.
{
  assert(quantization != nullptr);
  _affine_quantizations.push_back(std::move(quantization));
  return _affine_quantizations.back().get();
}
References _affine_quantizations.
Referenced by luci_interpreter::GraphLoader::initInputTensors(), luci_interpreter::GraphLoader::loadOperators(), and luci_interpreter::GraphLoader::loadTensors().
addInputTensor()
void luci_interpreter::IBaseRuntimeGraph::addInputTensor (Tensor * input_tensor)
Definition at line 47 of file RuntimeGraph.cpp.
{
  _input_tensors.push_back(input_tensor);
}
References _input_tensors.
Referenced by luci_interpreter::GraphLoader::initInputTensors().
addIntermediateTensorAffineQuantization()
void luci_interpreter::IBaseRuntimeGraph::addIntermediateTensorAffineQuantization (AffineQuantization * intermediate_tensor)
Definition at line 52 of file RuntimeGraph.cpp.
{
  _intermediate_tensors_affine_quantizations.push_back(intermediate_tensor_affine_quant);
}
References _intermediate_tensors_affine_quantizations.
Referenced by luci_interpreter::GraphLoader::loadTensors().
addKernel()
void luci_interpreter::IBaseRuntimeGraph::addKernel (std::unique_ptr< Kernel > && kernel)
Definition at line 68 of file RuntimeGraph.cpp.
{
  assert(kernel != nullptr);
  _kernels.push_back(std::move(kernel));
  _is_valid = false;
}
References _is_valid, and _kernels.
addOutputTensor()
void luci_interpreter::IBaseRuntimeGraph::addOutputTensor (Tensor * output_tensor)
Definition at line 58 of file RuntimeGraph.cpp.
{
  _output_tensors.push_back(output_tensor);
}
References _output_tensors.
Referenced by luci_interpreter::GraphLoader::loadOperators().
addTensor()
Tensor * luci_interpreter::IBaseRuntimeGraph::addTensor (std::unique_ptr< Tensor > && tensor)
Definition at line 32 of file RuntimeGraph.cpp.
{
  assert(tensor != nullptr);
  _tensors.push_back(std::move(tensor));
  return _tensors.back().get();
}
References _tensors.
Referenced by luci_interpreter::build_kernel_CircleAveragePool2D(), luci_interpreter::build_kernel_CircleBatchMatMul(), luci_interpreter::build_kernel_CircleConv2D(), luci_interpreter::build_kernel_CircleDepthwiseConv2D(), luci_interpreter::build_kernel_CircleMean(), luci_interpreter::build_kernel_CircleSVDF(), luci_interpreter::build_kernel_CircleTransposeConv(), and luci_interpreter::build_kernel_CircleUnidirectionalSequenceLSTM().
configure()
virtual void luci_interpreter::IBaseRuntimeGraph::configure () pure virtual
Implemented in luci_interpreter::RuntimeGraph, and luci_interpreter::StaticRuntimeGraph.
Referenced by luci_interpreter::ModuleLoader::load().
configure_kernels()
virtual void luci_interpreter::IBaseRuntimeGraph::configure_kernels () pure virtual
Implemented in luci_interpreter::RuntimeGraph, and luci_interpreter::StaticRuntimeGraph.
configureAllocations()
void luci_interpreter::IBaseRuntimeGraph::configureAllocations (Tensor * tensor)
Definition at line 63 of file RuntimeGraph.cpp.
{
  _memory_manager->allocate_memory(*tensor);
}
References _memory_manager, and luci_interpreter::IMemoryManager::allocate_memory().
execute()
virtual void luci_interpreter::IBaseRuntimeGraph::execute () pure virtual
Implemented in luci_interpreter::RuntimeGraph, and luci_interpreter::StaticRuntimeGraph.
getInputTensors()
const std::vector< Tensor * > & luci_interpreter::IBaseRuntimeGraph::getInputTensors () const inline
Definition at line 51 of file RuntimeGraph.h.
{ return _input_tensors; }
References _input_tensors.
getIntermediateAffineQuantizations()
const std::vector< AffineQuantization * > & luci_interpreter::IBaseRuntimeGraph::getIntermediateAffineQuantizations () const inline
Definition at line 47 of file RuntimeGraph.h.
  {
    return _intermediate_tensors_affine_quantizations;
  }
References _intermediate_tensors_affine_quantizations.
getOutputTensors()
const std::vector< Tensor * > & luci_interpreter::IBaseRuntimeGraph::getOutputTensors () const inline
Definition at line 52 of file RuntimeGraph.h.
{ return _output_tensors; }
References _output_tensors.
invalidate()
void luci_interpreter::IBaseRuntimeGraph::invalidate () inline
Definition at line 61 of file RuntimeGraph.h.
{ _is_valid = false; }
References _is_valid.
Referenced by luci_interpreter::RuntimeGraph::TensorAllocPlan::build().
isValid()
bool luci_interpreter::IBaseRuntimeGraph::isValid () const inline
Definition at line 62 of file RuntimeGraph.h.
{ return _is_valid; }
References _is_valid.
Field Documentation
_affine_quantizations
std::vector<std::unique_ptr<AffineQuantization> > luci_interpreter::IBaseRuntimeGraph::_affine_quantizations protected
Definition at line 67 of file RuntimeGraph.h.
Referenced by addAffineQuantization().
_input_tensors
std::vector<Tensor *> luci_interpreter::IBaseRuntimeGraph::_input_tensors protected
Definition at line 68 of file RuntimeGraph.h.
Referenced by addInputTensor(), and getInputTensors().
_intermediate_tensors_affine_quantizations
std::vector<AffineQuantization *> luci_interpreter::IBaseRuntimeGraph::_intermediate_tensors_affine_quantizations protected
Definition at line 69 of file RuntimeGraph.h.
Referenced by addIntermediateTensorAffineQuantization(), and getIntermediateAffineQuantizations().
_is_valid
bool luci_interpreter::IBaseRuntimeGraph::_is_valid = false protected
Definition at line 72 of file RuntimeGraph.h.
Referenced by addKernel(), luci_interpreter::RuntimeGraph::configure(), luci_interpreter::StaticRuntimeGraph::configure(), luci_interpreter::RuntimeGraph::execute(), luci_interpreter::StaticRuntimeGraph::execute(), invalidate(), and isValid().
_kernels
std::vector<std::unique_ptr<Kernel> > luci_interpreter::IBaseRuntimeGraph::_kernels protected
Definition at line 75 of file RuntimeGraph.h.
Referenced by addKernel(), luci_interpreter::StaticRuntimeGraph::configure(), luci_interpreter::StaticRuntimeGraph::configure_kernels(), and luci_interpreter::StaticRuntimeGraph::execute().
_memory_manager
IMemoryManager* luci_interpreter::IBaseRuntimeGraph::_memory_manager protected
Definition at line 65 of file RuntimeGraph.h.
Referenced by luci_interpreter::StaticRuntimeGraph::configure(), configureAllocations(), luci_interpreter::StaticRuntimeGraph::execute(), and luci_interpreter::StaticRuntimeGraph::~StaticRuntimeGraph().
_output_tensors
std::vector<Tensor *> luci_interpreter::IBaseRuntimeGraph::_output_tensors protected
Definition at line 70 of file RuntimeGraph.h.
Referenced by addOutputTensor(), luci_interpreter::StaticRuntimeGraph::configure(), and getOutputTensors().
_tensors
std::vector<std::unique_ptr<Tensor> > luci_interpreter::IBaseRuntimeGraph::_tensors protected
Definition at line 66 of file RuntimeGraph.h.
Referenced by addTensor().
The documentation for this class was generated from the following files:
onert-micro/luci-interpreter/src/core/RuntimeGraph.h
onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp