ONE - On-device Neural Engine: mio::circle::Reader Class Reference
mio::circle::Reader Class Reference
Loads Circle file and provides helpers to access attributes.
#include <Reader.h>
Public Member Functions
Reader (const ::circle::Model *model)
Reader ()=delete
uint32_t version () const
const std::vector< const ::circle::OperatorCode * > & opcodes ()
const CircleBuffers_t * buffers ()
const CircleTensors_t * tensors ()
const CircleOperators_t * operators ()
const std::vector< int32_t > & inputs () const
const std::vector< int32_t > & outputs () const
const ::circle::DataFormat & data_format () const
const CircleMetadata_t * metadata () const
const CircleSignatureDef_t * signature_defs () const
uint32_t num_subgraph () const
size_t buffer_info (uint32_t buf_idx, const uint8_t **buff_data)
::circle::BuiltinOperator builtin_code (const ::circle::Operator *op) const
std::string opcode_name (const ::circle::Operator *op) const
std::vector< int32_t > outputs (const ::circle::Operator *op) const
std::string tensor_name (const ::circle::Tensor *tensor) const
std::string tensor_dtype (const ::circle::Tensor *tensor) const
bool select_subgraph (uint32_t subgraph)
const std::string & subgraph_name (void) const
uint32_t subgraph_index (void) const
Detailed Description
Loads Circle file and provides helpers to access attributes.
Definition at line 38 of file Reader.h.
Constructor & Destructor Documentation
Reader() [1/2]
mio::circle::Reader::Reader (const ::circle::Model * model)
Definition at line 28 of file Reader.cpp.
{
  if (model == nullptr)
  {
    throw std::runtime_error("Invalid model");
  }
  _version = model->version();
  _subgraphs = model->subgraphs();
  _buffers = model->buffers();
  _metadata = model->metadata();
  _signature_defs = model->signature_defs();
  auto opcodes = model->operator_codes();
  for (const ::circle::OperatorCode *opcode : *opcodes)
  {
    _op_codes.push_back(opcode);
  }
}
References opcodes().
Reader() [2/2]
mio::circle::Reader::Reader () delete
Member Function Documentation
buffer_info()
size_t mio::circle::Reader::buffer_info (uint32_t buf_idx, const uint8_t ** buff_data)
Definition at line 48 of file Reader.cpp.
{
  if (buff_data != nullptr)
  {
    *buff_data = nullptr;
  }
  if (buf_idx == 0)
    return 0;
  if (auto *buffer = (*_buffers)[buf_idx])
  {
    if (auto *array = buffer->data())
    {
      if (size_t size = array->size())
      {
        if (buff_data != nullptr)
        {
          *buff_data = reinterpret_cast<const uint8_t *>(array->data());
        }
        return size;
      }
    }
  }
  return 0;
}
Referenced by circledump::dump_model(), and circleinspect::DumpConstants::run().
buffers()
const CircleBuffers_t * mio::circle::Reader::buffers () inline
Definition at line 57 of file Reader.h.
{ return _buffers; }
Referenced by circledump::dump_model(), circletensordump::DumpTensors::run(), and circletensordump::DumpTensorsToHdf5::run().
builtin_code()
circle::BuiltinOperator mio::circle::Reader::builtin_code (const ::circle::Operator * op) const
Definition at line 76 of file Reader.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const ::circle::OperatorCode *opcode = _op_codes.at(index);
  return mio::circle::builtin_code_neutral(opcode);
}
References mio::circle::builtin_code_neutral().
Referenced by circledump::dump_sub_graph(), and circleinspect::DumpConv2DWeight::run().
data_format()
const ::circle::DataFormat & mio::circle::Reader::data_format () const inline
Definition at line 62 of file Reader.h.
{ return _data_format; }
Referenced by circledump::dump_sub_graph().
inputs()
const std::vector< int32_t > & mio::circle::Reader::inputs () const inline
Definition at line 60 of file Reader.h.
{ return _inputs; }
Referenced by circledump::dump_sub_graph(), and validate_onnx2circle.OnnxRunner::feed_random_inputs().
metadata()
const CircleMetadata_t * mio::circle::Reader::metadata () const inline
Definition at line 63 of file Reader.h.
{ return _metadata; }
Referenced by circledump::dump_model().
num_subgraph()
uint32_t mio::circle::Reader::num_subgraph () const inline
Definition at line 66 of file Reader.h.
{ return _subgraphs->Length(); }
Referenced by circledump::dump_model(), circleinspect::DumpOperators::run(), circleinspect::DumpConv2DWeight::run(), circleinspect::DumpOperatorVersion::run(), circleinspect::DumpTensorDType::run(), circleinspect::DumpConstants::run(), cirops::DumpOperators::run(), circletensordump::DumpTensors::run(), and circletensordump::DumpTensorsToHdf5::run().
opcode_name()
std::string mio::circle::Reader::opcode_name (const ::circle::Operator * op) const
Definition at line 85 of file Reader.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const ::circle::OperatorCode *opcode = _op_codes.at(index);
  if (!mio::circle::is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  return mio::circle::opcode_name(opcode);
}
References mio::circle::is_valid(), and mio::circle::opcode_name().
Referenced by circledump::dump_sub_graph(), circleinspect::DumpOperators::run(), circleinspect::DumpConv2DWeight::run(), and circleinspect::DumpOperatorVersion::run().
opcodes()
const std::vector< const ::circle::OperatorCode * > & mio::circle::Reader::opcodes () inline
Definition at line 56 of file Reader.h.
{ return _op_codes; }
Referenced by circledump::dump_model(), Reader(), and circleinspect::DumpOperatorVersion::run().
operators()
const CircleOperators_t * mio::circle::Reader::operators () inline
Definition at line 59 of file Reader.h.
{ return _operators; }
Referenced by circledump::dump_sub_graph(), circleinspect::DumpOperators::run(), circleinspect::DumpConv2DWeight::run(), and circleinspect::DumpOperatorVersion::run().
outputs() [1/2]
const std::vector< int32_t > & mio::circle::Reader::outputs () const inline
Definition at line 61 of file Reader.h.
{ return _outputs; }
Referenced by circledump::dump_sub_graph(), and validate_onnx2circle.OnnxRunner::get_outputs().
outputs() [2/2]
std::vector< int32_t > mio::circle::Reader::outputs (const ::circle::Operator * op) const
Definition at line 101 of file Reader.cpp.
{
  return as_index_vector(op->outputs());
}
References mio::circle::as_index_vector().
Referenced by validate_onnx2circle.OnnxRunner::get_outputs().
select_subgraph()
bool mio::circle::Reader::select_subgraph (uint32_t subgraph)
Definition at line 116 of file Reader.cpp.
{
  _subgraph_index = sgindex;
  _tensors = nullptr;
  _operators = nullptr;
  _inputs.clear();
  _outputs.clear();
  if (_subgraphs->Length() <= sgindex)
  {
    assert(false);
    return false;
  }
  const ::circle::SubGraph *subgraph = (*_subgraphs)[sgindex];
  auto name = subgraph->name();
  _subgraph_name = name ? name->c_str() : "(noname)";
  _tensors = subgraph->tensors();
  _operators = subgraph->operators();
  _data_format = subgraph->data_format();
  _inputs = as_index_vector(subgraph->inputs());
  _outputs = as_index_vector(subgraph->outputs());
  return true;
}
References mio::circle::as_index_vector().
Referenced by circledump::dump_model(), circleinspect::DumpOperators::run(), circleinspect::DumpConv2DWeight::run(), circleinspect::DumpOperatorVersion::run(), circleinspect::DumpTensorDType::run(), circleinspect::DumpConstants::run(), cirops::DumpOperators::run(), circletensordump::DumpTensors::run(), and circletensordump::DumpTensorsToHdf5::run().
signature_defs()
const CircleSignatureDef_t * mio::circle::Reader::signature_defs () const inline
Definition at line 64 of file Reader.h.
{ return _signature_defs; }
Referenced by circledump::dump_model().
subgraph_index()
uint32_t mio::circle::Reader::subgraph_index (void) const inline
Definition at line 78 of file Reader.h.
{ return _subgraph_index; }
Referenced by circledump::dump_sub_graph().
subgraph_name()
const std::string & mio::circle::Reader::subgraph_name (void) const inline
Definition at line 77 of file Reader.h.
{ return _subgraph_name; }
Referenced by circledump::dump_model().
tensor_dtype()
std::string mio::circle::Reader::tensor_dtype (const ::circle::Tensor * tensor) const
Definition at line 111 of file Reader.cpp.
{
  return mio::circle::tensor_type(tensor);
}
References mio::circle::tensor_type().
Referenced by circleinspect::DumpTensorDType::run().
tensor_name()
std::string mio::circle::Reader::tensor_name (const ::circle::Tensor * tensor) const
Definition at line 106 of file Reader.cpp.
{
  return mio::circle::tensor_name(tensor);
}
References mio::circle::tensor_name().
Referenced by circleinspect::DumpTensorDType::run(), and circleinspect::DumpConstants::run().
tensors()
const CircleTensors_t * mio::circle::Reader::tensors () inline
Definition at line 58 of file Reader.h.
{ return _tensors; }
Referenced by circledump::dump_sub_graph(), circleinspect::DumpTensorDType::run(), circleinspect::DumpConstants::run(), circletensordump::DumpTensors::run(), and circletensordump::DumpTensorsToHdf5::run().
version()
uint32_t mio::circle::Reader::version () const inline
Definition at line 54 of file Reader.h.
{ return _version; }
Referenced by circledump::dump_model().
The documentation for this class was generated from the following files:
compiler/mio-circle04/include/mio_circle/Reader.h
compiler/mio-circle04/src/Reader.cpp