ONE - On-device Neural Engine: luci_interpreter::kernels::ArgMax Class Reference
luci_interpreter::kernels::ArgMax Class Reference
#include <ArgMax.h>
Public Member Functions
ArgMax (const Tensor *input, const Tensor *axis, Tensor *output, const ArgMaxParams &params)
const Tensor * input () const
const Tensor * axis () const
Tensor * output () const
void configure () override
void execute () const override
ArgMax (const Tensor *input, const Tensor *axis, Tensor *output, const ArgMaxParams &params)
const Tensor * input () const
const Tensor * axis () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< ArgMaxParams >
const ArgMaxParams & params () const
const ArgMaxParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< ArgMaxParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ArgMaxParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ArgMaxParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< ArgMaxParams >
const ArgMaxParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file ArgMax.h.
Constructor & Destructor Documentation
ArgMax() [1/2]
luci_interpreter::kernels::ArgMax::ArgMax (const Tensor * input, const Tensor * axis, Tensor * output, const ArgMaxParams & params)
Definition at line 26 of file ArgMax.cpp.
  : KernelWithParams<ArgMaxParams>({input, axis}, {output}, params)
{
}
References axis(), and input().
ArgMax() [2/2]
luci_interpreter::kernels::ArgMax::ArgMax (const Tensor * input, const Tensor * axis, Tensor * output, const ArgMaxParams & params)
Member Function Documentation
axis() [1/2]
const Tensor * luci_interpreter::kernels::ArgMax::axis () const inline
Definition at line 34 of file ArgMax.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by ArgMax(), configure(), and execute().
axis() [2/2]
const Tensor * luci_interpreter::kernels::ArgMax::axis () const inline
Definition at line 34 of file ArgMax.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::ArgMax::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 31 of file ArgMax.cpp.
{
  assert(axis()->element_type() == DataType::S32 || axis()->element_type() == DataType::S64);
  assert(input()->shape().num_dims() >= 1);
  const Shape &input_shape = input()->shape();
  const int num_dims = input_shape.num_dims();
  Shape output_shape(num_dims - 1);
  // If axis value is negative, then update by adding input_shape's num_dims.
  // If updated value also negative, then assert.
  assert(axis()->shape().num_elements() == 1);
  int axis_value = getTensorData<int32_t>(axis())[0];
  if (axis_value < 0)
    axis_value = axis_value + num_dims;
  assert(axis_value >= 0);
  int j = 0;
  for (int i = 0; i < num_dims; i++)
  {
    if (i == axis_value)
      continue;
    output_shape.dim(j++) = input_shape.dim(i);
  }
  assert(output()->element_type() == _params.output_type);
  output()->resize(output_shape);
}
References luci_interpreter::KernelWithParams< ArgMaxParams >::_params, axis(), luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::ArgMaxParams::output_type, luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::ArgMax::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::ArgMax::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 60 of file ArgMax.cpp.
{
#define TF_LITE_ARG_MAX(data_type, axis_type, output_type)                                    \
  luci_interpreter_pal::ArgMinMax(getTensorShape(input()), getTensorData<data_type>(input()), \
                                  getTensorData<axis_type>(axis()), getTensorShape(output()), \
                                  getTensorData<output_type>(output()), std::greater<data_type>())
  if (axis()->element_type() == DataType::S32)
  {
    switch (_params.output_type)
    {
      case DataType::S32:
        switch (input()->element_type())
        {
          case DataType::FLOAT32:
            TF_LITE_ARG_MAX(float, int32_t, int32_t);
            break;
          case DataType::U8:
            TF_LITE_ARG_MAX(uint8_t, int32_t, int32_t);
            break;
          default:
            throw std::runtime_error("Unsupported input type.");
        }
        break;
      case DataType::S64:
        switch (input()->element_type())
        {
          case DataType::FLOAT32:
            TF_LITE_ARG_MAX(float, int32_t, int64_t);
            break;
          case DataType::U8:
            TF_LITE_ARG_MAX(uint8_t, int32_t, int64_t);
            break;
          default:
            throw std::runtime_error("Unsupported input type.");
        }
        break;
      default:
        throw std::runtime_error("Unsupported output type.");
    }
  }
  else
  {
    switch (_params.output_type)
    {
      case DataType::S32:
        switch (input()->element_type())
        {
          case DataType::FLOAT32:
            TF_LITE_ARG_MAX(float, int64_t, int32_t);
            break;
          case DataType::U8:
            TF_LITE_ARG_MAX(uint8_t, int64_t, int32_t);
            break;
          default:
            throw std::runtime_error("Unsupported input type.");
        }
        break;
      case DataType::S64:
        switch (input()->element_type())
        {
          case DataType::FLOAT32:
            TF_LITE_ARG_MAX(float, int64_t, int64_t);
            break;
          case DataType::U8:
            TF_LITE_ARG_MAX(uint8_t, int64_t, int64_t);
            break;
          default:
            throw std::runtime_error("Unsupported input type.");
        }
        break;
      default:
        throw std::runtime_error("Unsupported output type.");
    }
  }
#undef TF_LITE_ARG_MAX
}
References luci_interpreter::KernelWithParams< ArgMaxParams >::_params, axis(), input(), luci_interpreter::ArgMaxParams::output_type, and TF_LITE_ARG_MAX.
execute() [2/2]
void luci_interpreter::kernels::ArgMax::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::ArgMax::input () const inline
Definition at line 33 of file ArgMax.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by ArgMax(), configure(), and execute().
input() [2/2]
const Tensor * luci_interpreter::kernels::ArgMax::input () const inline
Definition at line 33 of file ArgMax.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::ArgMax::output () const inline
Definition at line 35 of file ArgMax.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::ArgMax::output () const inline
Definition at line 35 of file ArgMax.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/ArgMax.h
onert-micro/luci-interpreter/src/kernels/ArgMax.h
compiler/luci-interpreter/src/kernels/ArgMax.cpp
onert-micro/luci-interpreter/src/kernels/ArgMax.cpp