ONE - On-device Neural Engine: onert::compiler::pass::UnusedOperandEliminationPass Class Reference
onert::compiler::pass::UnusedOperandEliminationPass Class Reference
A pass to eliminate unused operands from the graph.
#include <UnusedOperandEliminationPass.h>
Public Member Functions
std::string id () override
void run () final
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
A pass to eliminate unused operands from the graph.
Remove operands that are not used by any operations, except Graph inputs/outputs.
Definition at line 40 of file UnusedOperandEliminationPass.h.
Member Function Documentation
id()
std::string onert::compiler::pass::UnusedOperandEliminationPass::id () inline override virtual
Implements onert::compiler::pass::Pass.
Definition at line 46 of file UnusedOperandEliminationPass.h.
{ return "UnusedOperandEliminationPass"; }
Pass()
onert::compiler::pass::Pass::Pass (ir::Graph & graph) inline
Definition at line 40 of file Pass.h.
: _graph{graph} {}
run()
void onert::compiler::pass::UnusedOperandEliminationPass::run () final virtual
Implements onert::compiler::pass::Pass.
Definition at line 36 of file UnusedOperandEliminationPass.cc.
{
  util::Set<ir::OperandIndex> used;
  _graph.operations().iterate([&](const ir::OperationIndex &, const ir::Operation &node) {
    for (auto ind : (node.getInputs() + node.getOutputs()) | ir::Remove::UNDEFINED)
    {
      used.add(ind);
    }
  });
  // Graph's inputs/outputs are always considered as used
  for (auto ind : (_graph.getInputs() + _graph.getOutputs()) | ir::Remove::UNDEFINED)
  {
    used.add(ind);
  }
  _graph.operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &) {
    if (!used.contains(ind))
    {
      VERBOSE() << "Remove unused operand " << ind << std::endl;
      _graph.operands().remove(ind);
    }
  });
}
References onert::compiler::pass::Pass::_graph, onert::util::Set< Element >::add(), onert::util::Set< Element >::contains(), onert::ir::Operation::getInputs(), onert::ir::Graph::getInputs(), onert::ir::Graph::getOutputs(), onert::ir::Operation::getOutputs(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::Graph::operands(), onert::ir::Graph::operations(), and onert::ir::UNDEFINED.
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.h
runtime/onert/core/src/compiler/pass/UnusedOperandEliminationPass.cc