ONE - On-device Neural Engine: locoex::TFLTranspose Class Reference
locoex::TFLTranspose Class Reference final
TRANSPOSE in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
TFLTranspose ()=default
loco::Node * a (void) const
Get the input node to transpose.
void a (loco::Node *node)
Set the input node to transpose.
loco::Node * perm (void) const
void perm (loco::Node *node)
Public Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::TRANSPOSE >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >
loco::Use * at (unsigned n) const
Detailed Description
TRANSPOSE in TensorFlow Lite.
Definition at line 505 of file TFLNodes.h.
Constructor & Destructor Documentation
TFLTranspose()
locoex::TFLTranspose::TFLTranspose () default
Member Function Documentation
a() [1/2]
void locoex::TFLTranspose::a (loco::Node * node) inline
Set the input node to transpose.
Definition at line 515 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >::at(), and loco::Use::node().
a() [2/2]
loco::Node * locoex::TFLTranspose::a (void) const inline
Get the input node to transpose.
Definition at line 512 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >::at(), and loco::Use::node().
perm() [1/2]
void locoex::TFLTranspose::perm (loco::Node * node) inline
Definition at line 518 of file TFLNodes.h.
{ at(1)->node(node); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >::at(), and loco::Use::node().
perm() [2/2]
loco::Node * locoex::TFLTranspose::perm (void) const inline
Definition at line 517 of file TFLNodes.h.
{ return at(1)->node(); }
References locoex::FixedArityNode< 2, TFLNodeImpl< TFLOpcode::TRANSPOSE > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h