ONE - On-device Neural Engine: moco::TFConcatV2 Class Reference
moco::TFConcatV2 Class Reference final
#include <TFConcatV2.h>
Public Member Functions
TFConcatV2 (uint32_t arity)
uint32_t num_values (void) const
Node * values (uint32_t index) const
void values (uint32_t index, Node *node)
Node * axis (void) const
void axis (Node *node)
Public Member Functions inherited from moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::ConcatV2 >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >
loco::Use * at (uint32_t n) const
Detailed Description
Note
TFConcatV2 corresponds to the following GraphDef
Definition at line 55 of file TFConcatV2.h.
Constructor & Destructor Documentation
TFConcatV2()
moco::TFConcatV2::TFConcatV2 (uint32_t arity) inline
Definition at line 58 of file TFConcatV2.h.
                             : VariadicArityNode<TFNodeImpl<TFOpcode::ConcatV2>>(arity + 1)
  {
    // we add +1 for axis of VariadicArityNode ctor
    // at least one value is required
    assert(arity >= 1);
  }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::arity().
Member Function Documentation
axis() [1/2]
void moco::TFConcatV2::axis (Node * node) inline
Definition at line 85 of file TFConcatV2.h.
{ at(num_values())->node(node); }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::at(), loco::Use::node(), and num_values().
axis() [2/2]
Node * moco::TFConcatV2::axis (void) const inline
Definition at line 84 of file TFConcatV2.h.
{ return at(num_values())->node(); }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::at(), loco::Use::node(), and num_values().
num_values()
uint32_t moco::TFConcatV2::num_values (void) const inline
Definition at line 66 of file TFConcatV2.h.
  {
    // last one is for axis
    return arity() - 1;
  }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::arity().
Referenced by axis(), and values().
values() [1/2]
Node * moco::TFConcatV2::values (uint32_t index) const inline
Definition at line 73 of file TFConcatV2.h.
  {
    assert(index < num_values());
    return at(index)->node();
  }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::at(), moco::index(), loco::Use::node(), and num_values().
values() [2/2]
void moco::TFConcatV2::values (uint32_t index, Node * node) inline
Definition at line 78 of file TFConcatV2.h.
  {
    assert(index < num_values());
    at(index)->node(node);
  }
References moco::VariadicArityNode< TFNodeImpl< TFOpcode::ConcatV2 > >::at(), moco::index(), loco::Use::node(), and num_values().
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFConcatV2.h