ONE - On-device Neural Engine: luci::CloneNodeLet< CN::DEF > Class Reference
luci::CloneNodeLet< CN::DEF > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleDensify *) final
luci::CircleNode * visit (const luci::CircleDepthToSpace *) final
luci::CircleNode * visit (const luci::CircleDepthwiseConv2D *) final
luci::CircleNode * visit (const luci::CircleDequantize *) final
luci::CircleNode * visit (const luci::CircleDiv *) final
luci::CircleNode * visit (const luci::CircleElu *) final
luci::CircleNode * visit (const luci::CircleEqual *) final
luci::CircleNode * visit (const luci::CircleExp *) final
luci::CircleNode * visit (const luci::CircleExpandDims *) final
luci::CircleNode * visit (const luci::CircleFakeQuant *) final
luci::CircleNode * visit (const luci::CircleFill *) final
luci::CircleNode * visit (const luci::CircleFloor *) final
luci::CircleNode * visit (const luci::CircleFloorDiv *) final
luci::CircleNode * visit (const luci::CircleFloorMod *) final
luci::CircleNode * visit (const luci::CircleFullyConnected *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 69 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::DEF >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 72 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleDensify *) final
Definition at line 22 of file CircleDensify.cpp.
{
  return _graph->nodes()->create<luci::CircleDensify>();
}
visit() [2/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleDepthToSpace * node) final
Definition at line 22 of file CircleDepthToSpace.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleDepthToSpace>();
  if (cloned != nullptr)
    cloned->block_size(node->block_size());
  return cloned;
}
References luci::CircleDepthToSpace::block_size().
visit() [3/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleDepthwiseConv2D * node) final
Definition at line 22 of file CircleDepthwiseConv2D.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleDepthwiseConv2D>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->padding(node->padding());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
    cloned->depthMultiplier(node->depthMultiplier());
    cloned->dilation()->h(node->dilation()->h());
    cloned->dilation()->w(node->dilation()->w());
  }
  return cloned;
}
References luci::CircleDepthwiseConv2D::depthMultiplier(), luci::CircleDepthwiseConv2D::dilation(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::Dilation::h(), luci::Stride::h(), luci::CircleDepthwiseConv2D::padding(), luci::CircleDepthwiseConv2D::stride(), luci::UNDEFINED, luci::Dilation::w(), and luci::Stride::w().
visit() [4/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleDequantize *) final
Definition at line 22 of file CircleDequantize.cpp.
{
  return _graph->nodes()->create<luci::CircleDequantize>();
}
visit() [5/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleDiv * node) final
Definition at line 22 of file CircleDiv.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleDiv>();
  if (cloned != nullptr)
    cloned->fusedActivationFunction(node->fusedActivationFunction());
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), and luci::UNDEFINED.
visit() [6/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleElu *) final
Definition at line 22 of file CircleElu.cpp.
{
  return _graph->nodes()->create<luci::CircleElu>();
}
visit() [7/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleEqual *) final
Definition at line 22 of file CircleEqual.cpp.
{
  return _graph->nodes()->create<luci::CircleEqual>();
}
visit() [8/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleExp *) final
Definition at line 22 of file CircleExp.cpp.
{
  return _graph->nodes()->create<luci::CircleExp>();
}
visit() [9/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleExpandDims *) final
Definition at line 22 of file CircleExpandDims.cpp.
{
  return _graph->nodes()->create<luci::CircleExpandDims>();
}
visit() [10/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFakeQuant * node) final
Definition at line 22 of file CircleFakeQuant.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleFakeQuant>();
  if (cloned != nullptr)
  {
    cloned->min(node->min());
    cloned->max(node->max());
    cloned->num_bits(node->num_bits());
    cloned->narrow_range(node->narrow_range());
  }
  return cloned;
}
References luci::CircleFakeQuant::max(), luci::CircleFakeQuant::min(), luci::CircleFakeQuant::narrow_range(), and luci::CircleFakeQuant::num_bits().
visit() [11/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFill *) final
Definition at line 22 of file CircleFill.cpp.
{
  return _graph->nodes()->create<luci::CircleFill>();
}
visit() [12/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFloor *) final
Definition at line 22 of file CircleFloor.cpp.
{
  return _graph->nodes()->create<luci::CircleFloor>();
}
visit() [13/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFloorDiv *) final
Definition at line 22 of file CircleFloorDiv.cpp.
{
  return _graph->nodes()->create<luci::CircleFloorDiv>();
}
visit() [14/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFloorMod *) final
Definition at line 22 of file CircleFloorMod.cpp.
{
  return _graph->nodes()->create<luci::CircleFloorMod>();
}
visit() [15/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleFullyConnected * node) final
Definition at line 22 of file CircleFullyConnected.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->weights_format() == luci::CircleFullyConnected::WeightsFormat::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleFullyConnected>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->weights_format(node->weights_format());
  }
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::UNDEFINED, luci::CircleFullyConnected::UNDEFINED, and luci::CircleFullyConnected::weights_format().
visit() [16/16]
luci::CircleNode * luci::CloneNodeLet< CN::DEF >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 91 of file CircleCloneNode.h.
{ return nullptr; }
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::DEF >::_graph = nullptr protected
Definition at line 94 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleDensify.cpp
compiler/luci/service/src/Nodes/CircleDepthToSpace.cpp
compiler/luci/service/src/Nodes/CircleDepthwiseConv2D.cpp
compiler/luci/service/src/Nodes/CircleDequantize.cpp
compiler/luci/service/src/Nodes/CircleDiv.cpp
compiler/luci/service/src/Nodes/CircleElu.cpp
compiler/luci/service/src/Nodes/CircleEqual.cpp
compiler/luci/service/src/Nodes/CircleExp.cpp
compiler/luci/service/src/Nodes/CircleExpandDims.cpp
compiler/luci/service/src/Nodes/CircleFakeQuant.cpp
compiler/luci/service/src/Nodes/CircleFill.cpp
compiler/luci/service/src/Nodes/CircleFloor.cpp
compiler/luci/service/src/Nodes/CircleFloorDiv.cpp
compiler/luci/service/src/Nodes/CircleFloorMod.cpp
compiler/luci/service/src/Nodes/CircleFullyConnected.cpp