ONE - On-device Neural Engine: onert_micro::core::OMQuantizationData< T > Class Template Reference
onert_micro::core::OMQuantizationData< T > Class Template Reference
#include <OMQuantizationData.h>
Public Types
enum QuantizationType { CWQ , LWQ }
Public Member Functions
OMQuantizationData (T *data, const circle::Tensor *tensor)
const flatbuffers::Vector< float > & Scales () const
const flatbuffers::Vector< int64_t > & ZeroPoint () const
int64_t ZeroPointAt (size_t idx) const
float ScaleAt (size_t idx) const
float Dequantize (T qvalue)
T Quantize (float value)
float DataAt (size_t idx)
void SetDataAt (size_t idx, float value)
Detailed Description
template<typename T>
class onert_micro::core::OMQuantizationData< T >
Definition at line 34 of file OMQuantizationData.h.
Member Enumeration Documentation
QuantizationType
template<typename T > enum onert_micro::core::OMQuantizationData::QuantizationType
Enumerator
CWQ
LWQ
Definition at line 37 of file OMQuantizationData.h.
  {
    CWQ,
    LWQ
  };
Constructor & Destructor Documentation
OMQuantizationData()
template<typename T > onert_micro::core::OMQuantizationData< T >::OMQuantizationData (T * data, const circle::Tensor * tensor) inline
Definition at line 49 of file OMQuantizationData.h.
    : _data(data)
  {
    assert(data != nullptr);
    assert(tensor != nullptr);
    assert(tensor->quantization() != nullptr);
    _params = tensor->quantization();
    if (Scales().Length() > 1)
    {
      _type = CWQ;
    }
  }
References onert_micro::core::OMQuantizationData< T >::CWQ, and onert_micro::core::OMQuantizationData< T >::Scales().
Member Function Documentation
DataAt()
template<typename T > float onert_micro::core::OMQuantizationData< T >::DataAt (size_t idx) inline
Definition at line 101 of file OMQuantizationData.h.
  {
    return Dequantize(_data[idx]);
  }
References onert_micro::core::OMQuantizationData< T >::Dequantize().
Dequantize()
template<typename T > float onert_micro::core::OMQuantizationData< T >::Dequantize (T qvalue) inline
Definition at line 87 of file OMQuantizationData.h.
  {
    float result = (qvalue - ZeroPointAt(0)) * ScaleAt(0);
    return result;
  }
References onert_micro::core::OMQuantizationData< T >::ScaleAt(), and onert_micro::core::OMQuantizationData< T >::ZeroPointAt().
Referenced by onert_micro::core::OMQuantizationData< T >::DataAt().
Quantize()
template<typename T > T onert_micro::core::OMQuantizationData< T >::Quantize (float value) inline
Definition at line 93 of file OMQuantizationData.h.
  {
    float fvalue = value / ScaleAt(0) + ZeroPointAt(0);
    T qvalue = Clamp(std::round(fvalue));
    return qvalue;
  }
References onert_micro::core::OMQuantizationData< T >::ScaleAt(), and onert_micro::core::OMQuantizationData< T >::ZeroPointAt().
Referenced by onert_micro::core::OMQuantizationData< T >::SetDataAt().
ScaleAt()
template<typename T > float onert_micro::core::OMQuantizationData< T >::ScaleAt (size_t idx) const inline
Definition at line 81 of file OMQuantizationData.h.
  {
    return Scales()[idx];
  }
References onert_micro::core::OMQuantizationData< T >::Scales().
Referenced by onert_micro::core::OMQuantizationData< T >::Dequantize(), and onert_micro::core::OMQuantizationData< T >::Quantize().
Scales()
template<typename T > const flatbuffers::Vector< float > & onert_micro::core::OMQuantizationData< T >::Scales () const inline
Definition at line 65 of file OMQuantizationData.h.
  {
    return *(_params->scale());
  }
Referenced by onert_micro::core::OMQuantizationData< T >::OMQuantizationData(), and onert_micro::core::OMQuantizationData< T >::ScaleAt().
SetDataAt()
template<typename T > void onert_micro::core::OMQuantizationData< T >::SetDataAt (size_t idx, float value) inline
Definition at line 106 of file OMQuantizationData.h.
  {
    _data[idx] = Quantize(value);
  }
References onert_micro::core::OMQuantizationData< T >::Quantize().
ZeroPoint()
template<typename T > const flatbuffers::Vector< int64_t > & onert_micro::core::OMQuantizationData< T >::ZeroPoint () const inline
Definition at line 70 of file OMQuantizationData.h.
  {
    return *(_params->zero_point());
  }
Referenced by onert_micro::core::OMQuantizationData< T >::ZeroPointAt().
ZeroPointAt()
template<typename T > int64_t onert_micro::core::OMQuantizationData< T >::ZeroPointAt (size_t idx) const inline
Definition at line 76 of file OMQuantizationData.h.
  {
    return ZeroPoint()[idx];
  }
References onert_micro::core::OMQuantizationData< T >::ZeroPoint().
Referenced by onert_micro::core::OMQuantizationData< T >::Dequantize(), and onert_micro::core::OMQuantizationData< T >::Quantize().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMQuantizationData.h