ONE - On-device Neural Engine: luci::CopyQuantParamPass Class Reference
luci::CopyQuantParamPass Class Reference
Pass to copy quantparam (scale, zerop) of a tensor to another tensor.
#include <CopyQuantParamPass.h>
Public Types
using TensorVector = std::vector< std::string >
Public Member Functions
CopyQuantParamPass (TensorVector &src_tensors, TensorVector &dst_tensors)
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to copy quantparam (scale, zerop) of a tensor to another tensor.
Definition at line 30 of file CopyQuantParamPass.h.
Member Typedef Documentation
TensorVector
using luci::CopyQuantParamPass::TensorVector = std::vector<std::string>
Definition at line 33 of file CopyQuantParamPass.h.
Constructor & Destructor Documentation
CopyQuantParamPass()
luci::CopyQuantParamPass::CopyQuantParamPass (TensorVector & src_tensors, TensorVector & dst_tensors) inline
Definition at line 36 of file CopyQuantParamPass.h.
    : _src_tensors{src_tensors}, _dst_tensors{dst_tensors}
  {
    // DO NOTHING
  }
Member Function Documentation
name()
virtual const char * luci::CopyQuantParamPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 41 of file CopyQuantParamPass.h.
{ return "luci::CopyQuantParamPass"; }
Referenced by run().
run()
bool luci::CopyQuantParamPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 35 of file CopyQuantParamPass.cpp.
{
  LOGGER(l);
  INFO(l) << "CopyQuantParamPass Start" << std::endl;
  if (_src_tensors.size() != _dst_tensors.size())
    throw std::runtime_error("The numbers of Source/Destination tensors do not match.");
  // Return src/dst CircleNodes
  auto get_src_dst = [&g](std::string src, std::string dst) {
    SrcDst src_dst;
    for (auto node : loco::active_nodes(loco::output_nodes(g)))
    {
      auto const cnode = loco::must_cast<CircleNode *>(node);
      auto const name = cnode->name();
      if (name == src)
        src_dst.src = cnode;
      if (name == dst)
        src_dst.dst = cnode;
    }
    return src_dst;
  };
  for (uint32_t i = 0; i < _src_tensors.size(); i++)
  {
    auto src = _src_tensors[i];
    auto dst = _dst_tensors[i];
    auto nodes = get_src_dst(src, dst);
    if (not nodes.src)
      throw std::runtime_error("The tensor named " + src + " does not exist.");
    if (not nodes.dst)
      throw std::runtime_error("The tensor named " + dst + " does not exist.");
    copy_quantparam(nodes.src, nodes.dst);
    INFO(l) << "Quantparam of " << src << " is copied to " << dst << std::endl;
  }
  INFO(l) << "CopyQuantParamPass End" << std::endl;
  return false; // one time run
}
References loco::active_nodes(), luci::copy_quantparam(), INFO, LOGGER, name(), and loco::output_nodes().
Referenced by luci::CircleQuantizer::quantize().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/CopyQuantParamPass.h
compiler/luci/pass/src/CopyQuantParamPass.cpp