ONE - On-device Neural Engine: luci::ConstantFoldingTestGraph Class Reference
luci::ConstantFoldingTestGraph Class Reference abstract
#include <PassTestGraphs.h>
Public Member Functions
ConstantFoldingTestGraph (std::vector< uint32_t > input_shape, loco::DataType input_dtype)
virtual void init ()=0
virtual ~ConstantFoldingTestGraph ()=default
virtual loco::Node * createFoldedPattern ()=0
virtual luci::CircleConst * getFoldedPattern ()=0
loco::Graph * graph ()
Protected Attributes
loco::Graph _g
luci::CircleInput * _input = nullptr
luci::CircleOutput * _output = nullptr
Detailed Description
ConstantFoldingTestGraph is a base class for testing constant folding passes. It creates Input and Output in the below graph. Child classes must implement Connector and Folded pattern.
[Input]   [Folded pattern] (Implemented by child class)
     \    /
   [Connector] (Implemented by child class)
        |
     [Output]
Connector should satisfy the below conditions
Input type == Output type == Folded pattern type
Input shape == Output shape == Folded pattern shape
For example, Add, Mul, Sub, .. can be a Connector
Definition at line 44 of file PassTestGraphs.h.
Constructor & Destructor Documentation
ConstantFoldingTestGraph()
luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph (std::vector< uint32_t > input_shape, loco::DataType input_dtype) inline
Definition at line 47 of file PassTestGraphs.h.
  {
    _input = _g.nodes()->create<luci::CircleInput>();
    _output = _g.nodes()->create<luci::CircleOutput>();
    auto graph_input = _g.inputs()->create();
    _input->index(graph_input->index());
    auto graph_output = _g.outputs()->create();
    _output->index(graph_output->index());
    graph_input->dtype(input_dtype);
    graph_output->dtype(input_dtype);
    _input->dtype(input_dtype);
    _output->dtype(input_dtype);
    auto input_tensor_shape = std::make_unique<loco::TensorShape>();
    input_tensor_shape->rank(input_shape.size());
    for (int i = 0; i < input_shape.size(); i++)
      input_tensor_shape->dim(i).set(input_shape[i]);
    graph_input->shape(std::move(input_tensor_shape));
    auto output_tensor_shape = std::make_unique<loco::TensorShape>();
    output_tensor_shape->rank(input_shape.size());
    for (int i = 0; i < input_shape.size(); i++)
      output_tensor_shape->dim(i).set(input_shape[i]);
    graph_output->shape(std::move(output_tensor_shape));
    _input->rank(input_shape.size());
    for (int i = 0; i < input_shape.size(); i++)
      _input->dim(i).set(input_shape[i]);
    _output->rank(input_shape.size());
    for (int i = 0; i < input_shape.size(); i++)
      _output->dim(i).set(input_shape[i]);
    _input->name("input");
    _output->name("output");
  }
References _g, _input, _output, loco::NodePool::create(), loco::Graph::InputContext::create(), loco::Graph::OutputContext::create(), luci::CircleInput::index(), luci::CircleOutput::index(), loco::Graph::inputs(), luci::CircleNode::name(), loco::Graph::nodes(), and loco::Graph::outputs().
~ConstantFoldingTestGraph()
virtual luci::ConstantFoldingTestGraph::~ConstantFoldingTestGraph () virtual default
Member Function Documentation
createFoldedPattern()
virtual loco::Node * luci::ConstantFoldingTestGraph::createFoldedPattern () pure virtual
Referenced by luci::ConstantFoldingAddTestGraph::init().
getFoldedPattern()
virtual luci::CircleConst * luci::ConstantFoldingTestGraph::getFoldedPattern () pure virtual
Implemented in luci::ConstantFoldingAddTestGraph.
graph()
loco::Graph * luci::ConstantFoldingTestGraph::graph () inline
Definition at line 94 of file PassTestGraphs.h.
{ return &_g; }
References _g.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
init()
virtual void luci::ConstantFoldingTestGraph::init () pure virtual
Implemented in luci::ConstantFoldingAddTestGraph.
Field Documentation
_g
loco::Graph luci::ConstantFoldingTestGraph::_g protected
Definition at line 98 of file PassTestGraphs.h.
Referenced by luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), ConstantFoldingTestGraph(), and graph().
_input
luci::CircleInput* luci::ConstantFoldingTestGraph::_input = nullptr protected
Definition at line 99 of file PassTestGraphs.h.
Referenced by luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), and ConstantFoldingTestGraph().
_output
luci::CircleOutput* luci::ConstantFoldingTestGraph::_output = nullptr protected
Definition at line 100 of file PassTestGraphs.h.
Referenced by luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), and ConstantFoldingTestGraph().
The documentation for this class was generated from the following file:
compiler/luci/pass/src/PassTestGraphs.h