ONE - On-device Neural Engine: nnkit::support::onnx::TensorContext Class Reference
nnkit::support::onnx::TensorContext Class Reference final
#include <TensorContext.h>
Public Member Functions
TensorContext (TensorSet &tensors)
uint32_t size (void) const override
std::string name (uint32_t n) const override
nncc::core::ADT::tensor::Shape shape (uint32_t n) const override
bool isFloatTensor (uint32_t n) const override
void getMutableFloatTensor (uint32_t n, const TensorContext::TypedAccessor< float > &f) override
void getConstFloatTensor (uint32_t n, const TensorContext::TypedReader< float > &f) const override
Public Member Functions inherited from nnkit::TensorContext
virtual ~TensorContext ()=default
virtual uint32_t size (void) const =0
virtual std::string name (uint32_t n) const =0
virtual nncc::core::ADT::tensor::Shape shape (uint32_t n) const =0
virtual bool isFloatTensor (uint32_t n) const
virtual void getMutableFloatTensor (uint32_t n, const TypedAccessor< float > &cb)
virtual void getConstFloatTensor (uint32_t n, const TypedReader< float > &cb) const
virtual bool isS32Tensor (uint32_t n) const
virtual void getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > &cb)
virtual void getConstS32Tensor (uint32_t n, const TypedReader< int32_t > &cb) const
Additional Inherited Members
Public Types inherited from nnkit::TensorContext
template<typename T >
using TypedReader = std::function< void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader< T > &)>
template<typename T >
using TypedAccessor = std::function< void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor< T > &)>
Detailed Description
Definition at line 34 of file TensorContext.h.
Constructor & Destructor Documentation
TensorContext()
nnkit::support::onnx::TensorContext::TensorContext (TensorSet & tensors) inline
Definition at line 37 of file TensorContext.h.
                                    : _tensors(tensors)
  {
    // DO NOTHING
  }
Member Function Documentation
getConstFloatTensor()
void nnkit::support::onnx::TensorContext::getConstFloatTensor (uint32_t n, const TensorContext::TypedReader< float > & f) const inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 87 of file TensorContext.h.
  {
    if (_tensors.type(n) != ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT)
    {
      throw std::runtime_error{"type mismatch"};
    }
    using nncc::core::ADT::tensor::LexicalLayout;
    using nncc::core::ADT::tensor::make_overlay;
    Status status;
    OrtValue *base = _tensors.mutable_tensor(n);
    float *data;
    status = OrtGetTensorMutableData(base, (void **)&data);
    status.throwOnError();
    auto overlay = make_overlay<float, LexicalLayout>(shape(n), data);
    f(*this, n, overlay);
  }
References nncc::core::ADT::tensor::make_overlay(), nnkit::support::onnx::TensorSet::mutable_tensor(), shape(), nnkit::support::onnx::Status::throwOnError(), and nnkit::support::onnx::TensorSet::type().
getMutableFloatTensor()
void nnkit::support::onnx::TensorContext::getMutableFloatTensor (uint32_t n, const TensorContext::TypedAccessor< float > & f) inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 64 of file TensorContext.h.
  {
    if (_tensors.type(n) != ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT)
    {
      throw std::runtime_error{"type mismatch"};
    }
    using nncc::core::ADT::tensor::LexicalLayout;
    using nncc::core::ADT::tensor::make_overlay;
    Status status;
    OrtValue *base = _tensors.mutable_tensor(n);
    float *data;
    status = OrtGetTensorMutableData(base, (void **)&data);
    status.throwOnError();
    auto overlay = make_overlay<float, LexicalLayout>(shape(n), data);
    f(*this, n, overlay);
  }
References nncc::core::ADT::tensor::make_overlay(), nnkit::support::onnx::TensorSet::mutable_tensor(), shape(), nnkit::support::onnx::Status::throwOnError(), and nnkit::support::onnx::TensorSet::type().
isFloatTensor()
bool nnkit::support::onnx::TensorContext::isFloatTensor (uint32_t n) const inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 59 of file TensorContext.h.
  {
    return (_tensors.type(n) == ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT);
  }
References nnkit::support::onnx::TensorSet::type().
name()
std::string nnkit::support::onnx::TensorContext::name (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 44 of file TensorContext.h.
{ return std::string{_tensors.name(n)}; }
References nnkit::support::onnx::TensorSet::name().
shape()
nncc::core::ADT::tensor::Shape nnkit::support::onnx::TensorContext::shape (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 46 of file TensorContext.h.
  {
    const std::vector<size_t> &dims = _tensors.dim(n);
    nncc::core::ADT::tensor::Shape shape;
    shape.resize(dims.size());
    for (size_t i = 0; i < dims.size(); ++i)
    {
      shape.dim(i) = dims[i];
    }
    return shape;
  }
References nnkit::support::onnx::TensorSet::dim(), nncc::core::ADT::tensor::Shape::dim(), nncc::core::ADT::tensor::Shape::resize(), and shape().
Referenced by getConstFloatTensor(), getMutableFloatTensor(), and shape().
size()
uint32_t nnkit::support::onnx::TensorContext::size (void) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 42 of file TensorContext.h.
{ return _tensors.size(); }
References nnkit::support::onnx::TensorSet::size().
The documentation for this class was generated from the following file:
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/TensorContext.h