ONE - On-device Neural Engine: onert_micro::core::IOTensorData< T > Class Template Reference
onert_micro::core::IOTensorData< T > Class Template Reference
#include <OMCustomTensorData.h>
Public Member Functions
IOTensorData (T *data, const circle::Tensor *tensor)
template<typename U = T>
EnableIfNotQuantized< U, U > ValueAt (size_t idx) const
template<typename U = T>
EnableIfQuantized< U, float > ValueAt (size_t idx) const
template<typename U = T>
EnableIfNotQuantized< U, void > SetValueAt (size_t idx, T value)
template<typename U = T>
EnableIfQuantized< U, void > SetValueAt (size_t idx, float value)
Public Member Functions inherited from onert_micro::core::OMTensorData< T >
OMTensorData (T *data, const circle::Tensor *tensor)
size_t Size () const noexcept
bool IsNull () const noexcept
EnableIfNotConst< R, R > At (size_t idx)
T At (size_t idx) const
EnableIfNotConst< R, void > SetAt (size_t idx, R value)
virtual T * Get () noexcept
virtual const T * Get () const noexcept
Additional Inherited Members
Protected Member Functions inherited from onert_micro::core::OMTensorData< T >
virtual bool CheckIndex (size_t idx) const
Protected Attributes inherited from onert_micro::core::OMTensorData< T >
T * _data
size_t _size
Detailed Description
template<typename T>
class onert_micro::core::IOTensorData< T >
Definition at line 37 of file OMCustomTensorData.h.
Constructor & Destructor Documentation
IOTensorData()
template<typename T > onert_micro::core::IOTensorData< T >::IOTensorData (T * data, const circle::Tensor * tensor) inline
Definition at line 46 of file OMCustomTensorData.h.
    : OMTensorData<T>(data, tensor)
  {
    if (IsQuantized<T>)
    {
      _quant = std::make_unique<QuantData>(this->_data, tensor);
    }
  }
References onert_micro::core::OMTensorData< T >::_data.
Member Function Documentation
SetValueAt() [1/2]
template<typename T > template<typename U = T> EnableIfQuantized< U, void > onert_micro::core::IOTensorData< T >::SetValueAt (size_t idx, float value) inline
Definition at line 77 of file OMCustomTensorData.h.
  {
    this->CheckIndex(idx);
    _quant->SetDataAt(idx, value);
  }
References onert_micro::core::OMTensorData< T >::CheckIndex().
SetValueAt() [2/2]
template<typename T > template<typename U = T> EnableIfNotQuantized< U, void > onert_micro::core::IOTensorData< T >::SetValueAt (size_t idx, T value) inline
Definition at line 71 of file OMCustomTensorData.h.
  {
    this->SetAt(idx, value);
  }
References onert_micro::core::OMTensorData< T >::SetAt().
ValueAt() [1/2]
template<typename T > template<typename U = T> EnableIfNotQuantized< U, U > onert_micro::core::IOTensorData< T >::ValueAt (size_t idx) const inline
Definition at line 57 of file OMCustomTensorData.h.
  {
    return this->At(idx);
  }
References onert_micro::core::OMTensorData< T >::At().
ValueAt() [2/2]
template<typename T > template<typename U = T> EnableIfQuantized< U, float > onert_micro::core::IOTensorData< T >::ValueAt (size_t idx) const inline
Definition at line 63 of file OMCustomTensorData.h.
  {
    this->CheckIndex(idx);
    return _quant->DataAt(idx);
  }
References onert_micro::core::OMTensorData< T >::CheckIndex().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMCustomTensorData.h