ONE - On-device Neural Engine: mpqsolver::core::H5FileDataProvider Class Reference
mpqsolver::core::H5FileDataProvider Class Reference final
#include <DataProvider.h>
Public Member Functions
H5FileDataProvider (const std::string &h5file, const std::string &module_path)
size_t numSamples () const override
uint32_t numInputs (uint32_t sample) const override
void getSampleInput (uint32_t sample, uint32_t input, InputData &data) const override
Public Member Functions inherited from mpqsolver::core::DataProvider
virtual ~DataProvider ()=default
Detailed Description
Definition at line 53 of file DataProvider.h.
Constructor & Destructor Documentation
H5FileDataProvider()
H5FileDataProvider::H5FileDataProvider (const std::string & h5file, const std::string & module_path)
Definition at line 52 of file DataProvider.cpp.
  : _importer(h5file)
{
  _importer.importGroup("value");
  _is_raw_data = _importer.isRawData();
  luci::ImporterEx importerex;
  _module = importerex.importVerifyModule(module_path);
  if (_module.get() != nullptr)
  {
    _input_nodes = loco::input_nodes(_module.get()->graph());
  }
}
References dio::hdf5::HDF5Importer::importGroup(), luci::ImporterEx::importVerifyModule(), loco::input_nodes(), and dio::hdf5::HDF5Importer::isRawData().
Member Function Documentation
getSampleInput()
void H5FileDataProvider::getSampleInput (uint32_t sample, uint32_t input, InputData & data) const override virtual
Implements mpqsolver::core::DataProvider.
Definition at line 73 of file DataProvider.cpp.
{
  if (_is_raw_data)
  {
    _importer.readTensor(sample, input, data.data().data(), data.data().size());
  }
  else
  {
    loco::DataType dtype;
    Shape shape;
    _importer.readTensor(sample, input, &dtype, &shape, data.data().data(), data.data().size());
    // Check the type and the shape of the input data is valid
    auto input_node = loco::must_cast<luci::CircleNode *>(_input_nodes.at(input));
    verifyTypeShape(input_node, dtype, shape);
  }
}
References dio::hdf5::HDF5Importer::readTensor().
numInputs()
uint32_t H5FileDataProvider::numInputs (uint32_t sample) const override virtual
Implements mpqsolver::core::DataProvider.
Definition at line 68 of file DataProvider.cpp.
{
  return static_cast<uint32_t>(_importer.numInputs(sample));
}
References dio::hdf5::HDF5Importer::numInputs().
numSamples()
size_t H5FileDataProvider::numSamples () const override virtual
Implements mpqsolver::core::DataProvider.
Definition at line 66 of file DataProvider.cpp.
{ return _importer.numData(); }
References dio::hdf5::HDF5Importer::numData().
The documentation for this class was generated from the following files:
compiler/circle-mpqsolver/src/core/DataProvider.h
compiler/circle-mpqsolver/src/core/DataProvider.cpp