ONE - On-device Neural Engine: logo::ResolveRedundantReshapePass Class Reference
logo::ResolveRedundantReshapePass Class Reference final
Remove redundant canonical FixedReshape.
#include <ResolveRedundantReshapePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *graph) override
Bypass redundant FixedReshape.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Remove redundant canonical FixedReshape.
Note
To effectively run this transform, canonical shape inference should be done ahead
Definition at line 33 of file ResolveRedundantReshapePass.h.
Member Function Documentation
name()
const char * logo::ResolveRedundantReshapePass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 36 of file ResolveRedundantReshapePass.h.
{ return "ResolveRedundantReshapePass"; }
run()
bool logo::ResolveRedundantReshapePass::run (loco::Graph * graph) override virtual
Bypass redundant FixedReshape.
Before:
In --— FixedReshape --— [Out]*
After:
In ---------------------— [Out]* \ ---— FixedReshape
Implements logo::Pass.
Definition at line 82 of file ResolveRedundantReshapePass.cpp.
{
  bool changed = false;
  for (auto node : loco::postorder_traversal(loco::output_nodes(graph)))
  {
    if (auto reshape = dynamic_cast<loco::FixedReshape *>(node))
    {
      if (shape_inference_done(reshape))
      {
        if (is_redundant_reshape(reshape))
        {
          replace(reshape).with(reshape->input());
          changed = true;
        }
      }
    }
  }
  return changed;
}
References loco::output_nodes(), loco::postorder_traversal(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this class was generated from the following files:
compiler/logo/include/logo/ResolveRedundantReshapePass.h
compiler/logo/src/Passes/ResolveRedundantReshapePass.cpp