ONE - On-device Neural Engine: onert::backend::cpu::ops::SplitLayer Class Reference
onert::backend::cpu::ops::SplitLayer Class Reference
#include <SplitLayer.h>
Public Member Functions
SplitLayer ()
template<typename T >
void split (void)
void configure (const IPortableTensor *input, const IPortableTensor *axis, uint16_t num_splits, std::vector< IPortableTensor * > &outputs)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Detailed Description
Definition at line 27 of file SplitLayer.h.
Constructor & Destructor Documentation
SplitLayer()
onert::backend::cpu::ops::SplitLayer::SplitLayer ()
Definition at line 57 of file SplitLayer.cc.
                       : _input(nullptr), _axis(nullptr), _num_splits(0), _outputs()
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::SplitLayer::configure (const IPortableTensor * input, const IPortableTensor * axis, uint16_t num_splits, std::vector< IPortableTensor * > & outputs)
Definition at line 90 of file SplitLayer.cc.
{
  assert(input != nullptr);
  _num_splits = num_splits;
  _input = input;
  _axis = axis;
  _outputs = outputs;
}
run()
void onert::backend::cpu::ops::SplitLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 101 of file SplitLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    split<float>();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    split<uint8_t>();
  }
  else if (_input->data_type() == OperandType::INT32)
  {
    split<int32_t>();
  }
  else if (_input->data_type() == OperandType::INT64)
  {
    split<int64_t>();
  }
  else
  {
    throw std::runtime_error{"Split: unsupported input type"};
  }
}
References onert::backend::IPortableTensor::data_type().
split()
template<typename T > void onert::backend::cpu::ops::SplitLayer::split (void)
Definition at line 62 of file SplitLayer.cc.
{
  nnfw::cker::SplitParams op_params;
  if (_axis->total_size() != sizeof(int32_t))
  {
    throw std::runtime_error("ArgMinMax: wrong shape of axis");
  }
  auto axis = *getBuffer<int32_t>(_axis);
  if (axis < 0)
  {
    axis += _input->getShape().rank();
  }
  op_params.axis = axis;
  op_params.num_split = _num_splits;
  std::vector<T *> outputPtrs;
  for (const auto output : _outputs)
  {
    assert(output->total_size() == sizeOfData(output->data_type(), output->getShape().dims()));
    outputPtrs.emplace_back(getBuffer<T>(output));
  }
  assert(_input->total_size() == sizeOfData(_input->data_type(), _input->getShape().dims()));
  nnfw::cker::Split<T>(op_params, getShape(_input), getBuffer<T>(_input), getShape(_outputs[0]),
                       outputPtrs.data());
}
References nnfw::cker::SplitParams::axis, onert::backend::IPortableTensor::data_type(), onert::backend::IPortableTensor::getShape(), onert::backend::cpu::ops::getShape(), nnfw::cker::SplitParams::num_split, onert::backend::cpu::ops::sizeOfData(), and onert::backend::IPortableTensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/SplitLayer.h
runtime/onert/backend/cpu/ops/SplitLayer.cc