ONE - On-device Neural Engine: onert::backend::Backend Class Reference
onert::backend::Backend Class Reference abstract
#include <Backend.h>
Public Member Functions
virtual ~Backend ()=default
virtual std::shared_ptr< onert::backend::IConfig > config () const =0
virtual std::unique_ptr< BackendContext > newContext (ContextData &&) const =0
virtual std::unique_ptr< ValidatorBase > validator (const ir::Graph &graph) const
Detailed Description
Definition at line 35 of file Backend.h.
Constructor & Destructor Documentation
~Backend()
virtual onert::backend::Backend::~Backend () virtual default
Member Function Documentation
config()
virtual std::shared_ptr< onert::backend::IConfig > onert::backend::Backend::config () const pure virtual
Implemented in onert::backend::acl_cl::Backend, onert::backend::acl_neon::Backend, onert::backend::cpu::Backend, onert::backend::ggml::Backend, onert::backend::ruy::Backend, onert::backend::train::Backend, onert::backend::trix::Backend, and onert::backend::builtin::Backend.
Referenced by onert::exec::ExecTime::getPermuteTime(), onert::exec::ProfileObserver::handleJobBegin(), onert::exec::TracingObserver::handleJobBegin(), onert::exec::TracingObserver::handleJobEnd(), and onert::exec::ExecTime::updatePermuteTime().
newContext()
virtual std::unique_ptr< BackendContext > onert::backend::Backend::newContext (ContextData &&) const pure virtual
Implemented in onert::backend::acl_cl::Backend, onert::backend::acl_neon::Backend, onert::backend::cpu::Backend, onert::backend::ggml::Backend, onert::backend::ruy::Backend, onert::backend::train::Backend, onert::backend::trix::Backend, and onert::backend::builtin::Backend.
validator()
virtual std::unique_ptr< ValidatorBase > onert::backend::Backend::validator (const ir::Graph & graph) const inline virtual
Reimplemented in onert::backend::acl_cl::Backend, onert::backend::acl_neon::Backend, onert::backend::cpu::Backend, onert::backend::ggml::Backend, onert::backend::ruy::Backend, and onert::backend::trix::Backend.
Definition at line 43 of file Backend.h.
  {
    return std::make_unique<ValidatorBase>(graph);
  }
The documentation for this class was generated from the following file:
runtime/onert/core/include/backend/Backend.h