ONE - On-device Neural Engine: Tensor Class Reference
Tensor Class Reference
Public Member Functions
Tensor (const vector< hsize_t > &shape)
~Tensor ()
int rank () const
int dim (int d) const
float * data ()
float numElems () const
float & at (const vector< int > &coords)
Tensor transpose (const vector< hsize_t > &reshape)
Detailed Description
Definition at line 31 of file tensor_gen.cpp.
Constructor & Destructor Documentation
Tensor()
Tensor::Tensor (const vector< hsize_t > & shape) inline explicit
Definition at line 34 of file tensor_gen.cpp.
                                                : _shape(shape), _data(0), _num_elems(1)
  {
    _strides.resize(shape.size());
    for (int i = _shape.size() - 1; i >= 0; --i)
    {
      _strides[i] = _num_elems;
      _num_elems *= _shape[i];
    }
    _data = new float[_num_elems];
  }
~Tensor()
Tensor::~Tensor () inline
Definition at line 47 of file tensor_gen.cpp.
{ delete[] _data; }
Member Function Documentation
at()
float & Tensor::at (const vector< int > & coords) inline
Definition at line 53 of file tensor_gen.cpp.
  {
    int offset = 0;
    for (auto i = 0; i < coords.size(); ++i)
      offset += coords[i] * _strides[i];
    return _data[offset];
  }
References coords, and offset().
Referenced by TEST(), and transpose().
data()
float * Tensor::data () inline
Definition at line 50 of file tensor_gen.cpp.
{ return _data; }
dim()
int Tensor::dim (int d) const inline
Definition at line 49 of file tensor_gen.cpp.
{ return _shape[d]; }
numElems()
float Tensor::numElems () const inline
Definition at line 51 of file tensor_gen.cpp.
{ return _num_elems; }
rank()
int Tensor::rank () const inline
Definition at line 48 of file tensor_gen.cpp.
{ return _shape.size(); }
Referenced by transpose().
transpose()
Tensor Tensor::transpose (const vector< hsize_t > & reshape) inline
Definition at line 63 of file tensor_gen.cpp.
  {
    vector<hsize_t> tr_shape(_shape.size());
    for (auto i = 0; i < _shape.size(); ++i)
      tr_shape[i] = _shape[reshape[i]];
    Tensor result(tr_shape);
    auto on_loop = [this, &reshape, &result](vector<int> &coords) {
      vector<int> tr_coords(_shape.size());
      for (int i = 0; i < rank(); ++i)
        tr_coords[i] = coords[reshape[i]];
      result.at(tr_coords) = at(coords);
    };
    iterate(*this, on_loop);
    return result;
  }
References at(), coords, and rank().
Referenced by main().
The documentation for this class was generated from the following file:
compiler/nnc/utils/input_gen/tensor_gen.cpp