ONE - On-device Neural Engine: onert::backend::cpu::ops::ReverseLayer Class Reference
onert::backend::cpu::ops::ReverseLayer Class Reference
#include <ReverseLayer.h>
Public Member Functions
ReverseLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *axis, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file ReverseLayer.h.
Constructor & Destructor Documentation
ReverseLayer()
onert::backend::cpu::ops::ReverseLayer::ReverseLayer () inline
Definition at line 36 of file ReverseLayer.h.
                 : _input{nullptr}, _axis{nullptr}, _output{nullptr}
  {
    // DO NOTHING
  }
Member Function Documentation
configure()
void onert::backend::cpu::ops::ReverseLayer::configure (const IPortableTensor * input, const IPortableTensor * axis, IPortableTensor * output)
Definition at line 56 of file ReverseLayer.cc.
{
  _input = input;
  _axis = axis;
  _output = output;
}
run()
void onert::backend::cpu::ops::ReverseLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 32 of file ReverseLayer.cc.
{
  if (_axis->total_size() != 4)
  {
    throw std::runtime_error{"Reverse: only support 1 axis"};
  }
  int32_t axis = *getBuffer<int32_t>(_axis);
  if (axis < 0)
  {
    axis += _input->getShape().rank();
  }
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
      nnfw::cker::Reverse<float>(axis, getShape(_input), getBuffer<float>(_input),
                                 getShape(_output), getBuffer<float>(_output));
      break;
    default:
      throw std::runtime_error{"Reverse: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), onert::backend::cpu::ops::getShape(), and onert::backend::ITensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ReverseLayer.h
runtime/onert/backend/cpu/ops/ReverseLayer.cc