ONE - On-device Neural Engine: onert::compiler::pass::PermutationInsertionPass Class Reference
onert::compiler::pass::PermutationInsertionPass Class Reference
#include <PermutationInsertionPass.h>
Public Member Functions
std::string id () override
void callback (const ir::OperandIndex &index, ir::Operand &object) override
LoweredOperandPass (compiler::LoweredGraph &lowered_graph)
Public Member Functions inherited from onert::compiler::pass::LoweredOperandPass
LoweredOperandPass (compiler::LoweredGraph &lowered_graph)
virtual ~LoweredOperandPass ()=default
std::string id () override=0
void callback (const ir::OperandIndex &i, ir::Operand &o) override=0
Public Member Functions inherited from onert::compiler::pass::OperandPass
virtual ~OperandPass ()=default
std::string id () override=0
void run () override final
virtual void callback (const ir::OperandIndex &i, ir::Operand &o)=0
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::LoweredOperandPass
compiler::LoweredGraph & _lowered_graph
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Definition at line 32 of file PermutationInsertionPass.h.
Member Function Documentation
callback()
void onert::compiler::pass::PermutationInsertionPass::callback (const ir::OperandIndex & index, ir::Operand & object) override virtual
Implements onert::compiler::pass::LoweredOperandPass.
Definition at line 38 of file PermutationInsertionPass.cc.
{
  auto &operand_li_map = _lowered_graph.lower_info().operand;
  auto &&operand_li = operand_li_map.getRawPtr(index);
  assert(operand_li);
  // NOTE Later, constants also will have Def
  // Ignore constants
  if (operand_li->def_factors().size() == 0)
  {
    return;
  }
  std::list<ir::OperationIndex> permute_indexes;
  // Build a map for all necessary type of operands
  std::unordered_map<PermuteFactor, ir::OperandIndex> factor_to_index;
  {
    assert(operand_li->def_factors().size() == 1);
    for (auto factor : operand_li->def_factors())
    {
      factor_to_index.emplace(factor, index);
    }
    auto insert_set = operand_li->use_factors() - operand_li->def_factors();
    for (auto factor : insert_set)
    {
      const auto permute_operation_index = insertPermute(index, factor);
      permute_indexes.push_back(permute_operation_index);
      const auto &permute_operation = _graph.operations().at(permute_operation_index);
      const auto permuted_operand_index = permute_operation.getOutputs().at(0);
      factor_to_index.emplace(factor, permuted_operand_index);
    }
  }
  // Update operations' input that uses this operand
  {
    std::list<ir::OperationIndex> remove_list;
    auto uses = object.getUses();
    for (auto use : uses)
    {
      // If permute operation, ignore it
      if (std::find(permute_indexes.begin(), permute_indexes.end(), use) != permute_indexes.end())
        continue;
      auto &operation = _graph.operations().at(use);
      auto op_li = _lowered_graph.lower_info().operation.getRawPtr(use);
      assert(op_li);
      const auto op_layout = op_li->layout();
      const backend::Backend *backend = op_li->backend();
      assert(backend);
      auto use_node_inputs = operation.getInputs();
      assert(use_node_inputs.contains(index));
      auto new_index = factor_to_index.at({backend, op_layout});
      if (index != new_index)
      {
        // Update from operation
        // Replace the same inputs of an operation at once for the following reasons:
        // No. 2 and 3 above
        operation.replaceInputs(index, new_index);
        // Update from operand
        remove_list.push_back(
          use); // Removal should be done in another loop since we are in the loop
        _graph.operands().at(new_index).insertUse(use);
      }
    }
    for (auto &operation : remove_list)
    {
      object.removeUse(operation);
    }
  }
}
References onert::compiler::pass::Pass::_graph, onert::compiler::pass::LoweredOperandPass::_lowered_graph, onert::util::ObjectManager< Index, Object >::at(), onert::compiler::LoweredGraph::lower_info(), onert::compiler::GraphLowerInfo::operand, onert::ir::Graph::operands(), onert::compiler::GraphLowerInfo::operation, and onert::ir::Graph::operations().
id()
std::string onert::compiler::pass::PermutationInsertionPass::id () inline override virtual
Implements onert::compiler::pass::LoweredOperandPass.
Definition at line 38 of file PermutationInsertionPass.h.
{ return "PermutationInsertionPass"; }
LoweredOperandPass()
onert::compiler::pass::LoweredOperandPass::LoweredOperandPass (compiler::LoweredGraph & lowered_graph) inline
Definition at line 33 of file LoweredOperandPass.h.
    : OperandPass{lowered_graph.graph()}, _lowered_graph{lowered_graph}
  {
    // DO NOTHING
  }
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/PermutationInsertionPass.h
runtime/onert/core/src/compiler/pass/PermutationInsertionPass.cc