ONE - On-device Neural Engine: luci::FixedArityNode< N, Base > Class Template Reference
luci::FixedArityNode< N, Base > Class Template Reference
Nodes with the fixed number of inputs.
#include <CircleNodeMixins.h>
Public Member Functions
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Protected Member Functions
loco::Use * at (uint32_t n) const
Detailed Description
template<uint32_t N, typename Base>
class luci::FixedArityNode< N, Base >
Nodes with the fixed number of inputs.
TODO Deprecated this class, and use loco::FixedArity instead
Definition at line 70 of file CircleNodeMixins.h.
Constructor & Destructor Documentation
FixedArityNode()
template<uint32_t N, typename Base > luci::FixedArityNode< N, Base >::FixedArityNode () inline
Definition at line 73 of file CircleNodeMixins.h.
  {
    _args.resize(N);
    for (uint32_t n = 0; n < N; ++n)
    {
      _args[n] = std::make_unique<loco::Use>(this);
    }
  }
~FixedArityNode()
template<uint32_t N, typename Base > virtual luci::FixedArityNode< N, Base >::~FixedArityNode () virtual default
Member Function Documentation
arg()
template<uint32_t N, typename Base > loco::Node * luci::FixedArityNode< N, Base >::arg (uint32_t n) const inline final
Definition at line 87 of file CircleNodeMixins.h.
{ return _args.at(n)->node(); }
Referenced by luci::propagate_pad_v2_quantparam().
arity()
template<uint32_t N, typename Base > uint32_t luci::FixedArityNode< N, Base >::arity (void) const inline final
Definition at line 85 of file CircleNodeMixins.h.
{ return N; }
at()
template<uint32_t N, typename Base > loco::Use * luci::FixedArityNode< N, Base >::at (uint32_t n) const inline protected
Definition at line 99 of file CircleNodeMixins.h.
{ return _args.at(n).get(); }
Referenced by luci::CircleInstanceNorm::beta(), luci::CircleInstanceNorm::gamma(), and luci::CircleInstanceNorm::input().
drop()
template<uint32_t N, typename Base > void luci::FixedArityNode< N, Base >::drop (void) inline final
Definition at line 89 of file CircleNodeMixins.h.
  {
    for (uint32_t n = 0; n < N; ++n)
    {
      _args.at(n)->node(nullptr);
    }
  }
Referenced by luci::fuse_sub_with_conv().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/CircleNodeMixins.h