ONE - On-device Neural Engine: onert::exec::Executors Class Reference
onert::exec::Executors Class Reference
Class to gather executors.
#include <Executors.h>
Data Structures
class EdgeTensor
Public Member Functions
Executors (void)=delete
Executors (std::unique_ptr< ir::ModelEdges > model_edges)
Executors (const Executors &)=delete
Executors (Executors &&)=default
~Executors ()=default
void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec) override
Insert executor in executor set.
IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const override
Return executor of index.
uint32_t inputSize () const override
Return executor set's number of input.
uint32_t outputSize () const override
Return executor set's number of output.
const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const override
Return NN package input tensor info.
const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const override
Return NN package output tensor info.
void execute (const IODescription &desc) override
Execute NN package executor set.
Public Member Functions inherited from onert::exec::IExecutors
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
Insert executor in executor set.
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
Return executor of index.
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
Return executor set's number of input.
virtual uint32_t outputSize () const =0
Return executor set's number of output.
virtual const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const =0
Return NN package input tensor info.
virtual const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const =0
Return NN package output tensor info.
virtual void execute (const IODescription &desc)=0
Execute NN package executor set.
Detailed Description
Class to gather executors.
Definition at line 47 of file Executors.h.
Constructor & Destructor Documentation
Executors() [1/4]
onert::exec::Executors::Executors (void) delete
Executors() [2/4]
onert::exec::Executors::Executors (std::unique_ptr< ir::ModelEdges > model_edges) inline
Definition at line 51 of file Executors.h.
    : _type_aware_quant_layers{}, _type_aware_quant_tensors{}, _edge_tensors{},
      _is_created_type_quant_layers{false}
  {
    _model_edges = std::move(model_edges);
    for (const auto &edge : _model_edges->edges)
    {
      _edge_map[edge.from].emplace_back(edge.to);
    }
  }
Executors() [3/4]
onert::exec::Executors::Executors (const Executors &) delete
Executors() [4/4]
onert::exec::Executors::Executors (Executors &&) default
~Executors()
onert::exec::Executors::~Executors () default
Member Function Documentation
at()
IExecutor * onert::exec::Executors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const override virtual
Return executor of index.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
Returns
Executor
Implements onert::exec::IExecutors.
Definition at line 72 of file Executors.cc.
{
  return _executors.at(std::make_pair(model_index, subg_index)).get();
}
Referenced by execute(), inputInfo(), and outputInfo().
emplace()
void onert::exec::Executors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) override virtual
Insert executor in executor set.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
[in] exec Executor to insert
Implements onert::exec::IExecutors.
Definition at line 66 of file Executors.cc.
{
  _executors.emplace(std::make_pair(model_index, subg_index), std::move(exec));
}
execute()
void onert::exec::Executors::execute (const IODescription & desc) override virtual
Execute NN package executor set.
Parameters
[in] desc Input and output buffer description
Implements onert::exec::IExecutors.
Definition at line 234 of file Executors.cc.
{
  // Check supported multi model package
  checkSupportedMultimodel();
  // TODO Move creating layers for type-aware quantization in compilation stage
  createTypeAwareQuantLayers();
  // TODO Find better way to schedule order of executors
  std::vector<std::unique_ptr<backend::builtin::IOTensor>> pkgs_inputs(desc.inputs.size());
  std::vector<std::unique_ptr<backend::builtin::IOTensor>> pkgs_outputs(desc.outputs.size());
  auto const model_count = modelCount();
  auto find_input_index = [&](const ir::ModelIndex &model_index,
                              const ir::SubgraphIndex &subg_index, const ir::IOIndex &io_index) {
    for (size_t i = 0; i < _model_edges->pkg_inputs.size(); i++)
    {
      auto &input_desc = _model_edges->pkg_inputs[i];
      if ((std::get<ir::ModelIndex>(input_desc) == model_index) &&
          (std::get<ir::SubgraphIndex>(input_desc) == subg_index) &&
          (std::get<ir::IOIndex>(input_desc) == io_index))
        return static_cast<int32_t>(i);
    }
    return -1;
  };
  auto find_output_index = [&](const ir::ModelIndex &model_index,
                               const ir::SubgraphIndex &subg_index, const ir::IOIndex &io_index) {
    for (size_t i = 0; i < _model_edges->pkg_outputs.size(); i++)
    {
      auto &input_desc = _model_edges->pkg_outputs[i];
      if ((std::get<ir::ModelIndex>(input_desc) == model_index) &&
          (std::get<ir::SubgraphIndex>(input_desc) == subg_index) &&
          (std::get<ir::IOIndex>(input_desc) == io_index))
        return static_cast<int32_t>(i);
    }
    return -1;
  };
  auto find_from = [&](const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index,
                       const ir::IOIndex &io_index) {
    for (const auto &edge : _model_edges->edges)
    {
      if ((std::get<ir::ModelIndex>(edge.to) == model_index) &&
          (std::get<ir::SubgraphIndex>(edge.to) == subg_index) &&
          (std::get<ir::IOIndex>(edge.to) == io_index))
        return edge.from;
    }
    throw std::runtime_error{"Cannot find edge for model input"};
  };
  // Assumption: nnpkg inputs/outputs are not duplicated.
  // TODO Unify _type_aware_quant_tensors, pkg_input_edge_tensors and pkg_output_edge_tensors into
  // one
  std::unordered_map<ir::IODesc, std::shared_ptr<EdgeTensor>> pkg_io_edge_tensors;
  // Execute each model
  // NOTE May be better to use vector instead of unordered_map for _executors
  for (auto model_index = ir::ModelIndex{0}; model_index.value() < model_count; model_index++)
  {
    // Find executor
    auto executor = at(model_index, ir::SubgraphIndex{0});
    // Set IOTensors
    std::vector<backend::IPortableTensor *> inputs_inter;
    std::vector<backend::IPortableTensor *> outputs_inter;
    const auto &input_tensors = executor->getInputTensors();
    const auto &output_tensors = executor->getOutputTensors();
    auto const input_size = input_tensors.size();
    auto const output_size = output_tensors.size();
    inputs_inter.resize(input_size);
    outputs_inter.resize(output_size);
    // Set inputs of executor
    std::vector<backend::ITensor *> pkg_input_src_tensors;
    std::vector<backend::ITensor *> pkg_input_dst_tensors;
    for (uint32_t i = 0; i < input_size; i++)
    {
      const auto input_tensor = input_tensors.at(i);
      auto input_pkg_index = find_input_index(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
      if (input_pkg_index != -1)
      {
        auto input_desc = desc.inputs[input_pkg_index].get();
        pkgs_inputs[input_pkg_index] =
          std::make_unique<backend::builtin::IOTensor>(input_desc->info, input_desc->layout);
        // TODO Remove const_cast (we need const_cast as ITensor is writable)
        pkgs_inputs[input_pkg_index]->setUserTensor(
          reinterpret_cast<uint8_t *>(const_cast<void *>(input_desc->buffer)), input_desc->size);
        inputs_inter[i] = pkgs_inputs[input_pkg_index].get();
        // Create type-aware quantization tensors for nnpkg inputs and reset inputs of executor
        const auto &orig_info = input_tensor->orig_info();
        const auto orig_type = input_tensor->orig_info().typeInfo().type();
        if (input_desc->info.typeInfo().type() != orig_type)
        {
          // TODO Move creating EdgeTensor into the function createTypeAwareQuantLayers
          const auto input_io_desc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
          const auto orig_layout = input_tensor->orig_layout();
          auto pkg_input_edge_tensor = std::make_unique<EdgeTensor>(orig_info, orig_layout);
          pkg_input_edge_tensor->allocate_buffer();
          pkg_io_edge_tensors[input_io_desc] = std::move(pkg_input_edge_tensor);
          pkg_input_src_tensors.emplace_back(pkgs_inputs[input_pkg_index].get());
          pkg_input_dst_tensors.emplace_back(pkg_io_edge_tensors[input_io_desc].get());
          inputs_inter[i] = pkg_io_edge_tensors[input_io_desc].get();
        }
      }
      else
      {
        auto from_iodesc = find_from(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
        const auto &from_model_index = std::get<ir::ModelIndex>(from_iodesc);
        const auto &from_subg_index = std::get<ir::SubgraphIndex>(from_iodesc);
        const auto &from_ioindex = std::get<ir::IOIndex>(from_iodesc).value();
        // Supported only sequantial execution of models
        assert(from_model_index.value() < model_index.value());
        assert(from_subg_index.value() == 0);
        const auto from_executor = _executors.at({from_model_index, from_subg_index}).get();
        const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
        if (_type_aware_quant_tensors.find(to_iodesc) == _type_aware_quant_tensors.end())
        {
          inputs_inter[i] = from_executor->getOutputTensors().at(from_ioindex);
        }
        else
        {
          inputs_inter[i] = _type_aware_quant_tensors.at(to_iodesc).get();
        }
        assert(inputs_inter[i]->buffer() != nullptr);
      }
    }
    // Set outputs of executor
    std::vector<backend::ITensor *> pkg_output_src_tensors;
    std::vector<backend::ITensor *> pkg_output_dst_tensors;
    for (uint32_t i = 0; i < output_size; i++)
    {
      const auto output_tensor = output_tensors.at(i);
      auto output_pkg_index = find_output_index(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
      if (output_pkg_index != -1)
      {
        auto output_desc = desc.outputs[output_pkg_index].get();
        const auto orig_layout = output_tensor->orig_layout();
        if (output_desc->layout != orig_layout)
        {
          throw std::runtime_error("Executors.cc: Changing layout is not supported");
        }
        pkgs_outputs[output_pkg_index] =
          std::make_unique<backend::builtin::IOTensor>(output_desc->info, output_desc->layout);
        pkgs_outputs[output_pkg_index]->setUserTensor(
          reinterpret_cast<uint8_t *>(output_desc->buffer), output_desc->size);
        outputs_inter[i] = pkgs_outputs[output_pkg_index].get();
        // Create type-aware quantization tensors for nnpkg outputs reset outputs of executor
        const auto &orig_info = output_tensor->orig_info();
        const auto orig_type = output_tensor->orig_info().typeInfo().type();
        if (output_desc->info.typeInfo().type() != orig_type)
        {
          // TODO Move creating EdgeTensor into the function createTypeAwareQuantLayers
          const auto output_io_desc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
          const auto orig_layout = output_tensor->orig_layout();
          auto pkg_output_edge_tensor = std::make_unique<EdgeTensor>(orig_info, orig_layout);
          pkg_output_edge_tensor->allocate_buffer();
          pkg_io_edge_tensors[output_io_desc] = std::move(pkg_output_edge_tensor);
          pkg_output_src_tensors.emplace_back(pkg_io_edge_tensors[output_io_desc].get());
          pkg_output_dst_tensors.emplace_back(pkgs_outputs[output_pkg_index].get());
          outputs_inter[i] = pkg_io_edge_tensors[output_io_desc].get();
        }
      }
      else
      {
        // Allocate buffer of `from` tensors
        const auto from_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
        _edge_tensors[from_iodesc]->allocate_buffer();
        outputs_inter[i] = _edge_tensors[from_iodesc].get();
        // Allocate buffer of tensors for type-aware quantization
        for (const auto &to_iodesc : _edge_map[from_iodesc])
        {
          _edge_tensors[from_iodesc]->increase_ref();
          if (_type_aware_quant_tensors.find(to_iodesc) != _type_aware_quant_tensors.end())
          {
            auto type_aware_quant_tensor = _type_aware_quant_tensors.at(to_iodesc).get();
            type_aware_quant_tensor->allocate_buffer();
            _edge_tensors[from_iodesc]->decrease_ref();
          }
        }
      }
    }
    // TODO Move creating PermuteLayer into the function createTypeAwareQuantLayers
    // TODO Recreate this layer only if nnpkg inputs' type changes
    auto pre_layer = std::make_unique<PermuteLayer>(pkg_input_src_tensors, pkg_input_dst_tensors);
    pre_layer->prepare();
    pre_layer->run();
    executor->execute(inputs_inter, outputs_inter);
    _type_aware_quant_layers[{model_index, ir::SubgraphIndex{0}}]->run();
    // TODO Move creating PermuteLayer into the function createTypeAwareQuantLayers
    // TODO Recreate this layer only if nnpkg outputs' type changes
    auto post_layer =
      std::make_unique<PermuteLayer>(pkg_output_src_tensors, pkg_output_dst_tensors);
    post_layer->prepare();
    post_layer->run();
    // Release input buffers that are no longer needed
    for (uint32_t i = 0; i < input_size; i++)
    {
      const auto input_pkg_index =
        find_input_index(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
      const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      if (input_pkg_index == -1)
      {
        if (_type_aware_quant_tensors.find(to_iodesc) != _type_aware_quant_tensors.end())
        {
          // Decrease reference count of tensor for type-aware quantization if input tensor is the
          // tensor
          const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
          if (_type_aware_quant_tensors.find(to_iodesc) != _type_aware_quant_tensors.end())
          {
            _type_aware_quant_tensors[to_iodesc]->decrease_ref();
          }
        }
        else
        {
          // Decrease reference count of `from` tensor if input tensor is the `from` tensor
          const auto from_iodesc = find_from(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
          _edge_tensors[from_iodesc]->decrease_ref();
          // Decrease reference count of nnpkg inputs
          // Assumption: nnpkg inputs/outputs are not duplicated with edges.
          if (pkg_io_edge_tensors.find(to_iodesc) != pkg_io_edge_tensors.end())
          {
            pkg_io_edge_tensors[to_iodesc]->decrease_ref();
          }
        }
      }
    }
    // Release output buffers if those buffers are no longer used other executors because of
    // type-aware quantization
    // FIXME if tensors for type-aware quantization unified for the same `from` tensor and same type
    for (uint32_t i = 0; i < output_size; i++)
    {
      auto from_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      // Check if other executors will use the buffer of edge tensor
      const auto &to_list = _edge_map[from_iodesc];
      if (to_list.size() == 0)
      {
        // This condition means `from_iodesc` tensor is an output of nnpkg
        continue;
      }
      bool to_be_release =
        !std::any_of(to_list.begin(), to_list.end(), [&](const ir::IODesc &to_iodesc) {
          // This condition means another executor uses the buffer of edge tensor
          return _type_aware_quant_tensors.find(to_iodesc) == _type_aware_quant_tensors.end();
        });
      if (to_be_release)
      {
        // This edge tensor's buffer won't be used in other executors
        // Tensors for type-aware quantization take over the role of this edge tensor instead
        _edge_tensors[from_iodesc]->decrease_ref();
      }
      // Decrease reference count of nnpkg outputs
      // Assumption: nnpkg inputs/outputs are not duplicated with edges.
      if (pkg_io_edge_tensors.find(from_iodesc) != pkg_io_edge_tensors.end())
      {
        pkg_io_edge_tensors[from_iodesc]->decrease_ref();
      }
    }
  }
}
References at(), onert::exec::IExecutor::getInputTensors(), onert::exec::IODescription::inputs, onert::exec::IODescription::outputs, and onert::util::Index< T, DummyTag >::value().
inputInfo()
const ir::OperandInfo & onert::exec::Executors::inputInfo (const ir::IOIndex & index) const override virtual
Return NN package input tensor info.
Parameters
[in] index Input index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 82 of file Executors.cc.
{
  auto const desc = _model_edges->pkg_inputs[index.value()];
  auto const model_index = std::get<0>(desc);
  auto const subg_index = std::get<1>(desc);
  auto const io_index = std::get<2>(desc);
  auto const executor = at(model_index, subg_index);
  return executor->getInputTensors().at(io_index.value())->orig_info();
}
References at().
inputSize()
uint32_t onert::exec::Executors::inputSize () const override virtual
Return executor set's number of input.
Returns
Number of input
Implements onert::exec::IExecutors.
Definition at line 78 of file Executors.cc.
{ return _model_edges->pkg_inputs.size(); }
outputInfo()
const ir::OperandInfo & onert::exec::Executors::outputInfo (const ir::IOIndex & index) const override virtual
Return NN package output tensor info.
Parameters
[in] index Output index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 92 of file Executors.cc.
{
  auto const desc = _model_edges->pkg_outputs[index.value()];
  auto const model_index = std::get<0>(desc);
  auto const subg_index = std::get<1>(desc);
  auto const io_index = std::get<2>(desc);
  auto const executor = at(model_index, subg_index);
  return executor->getOutputTensors().at(io_index.value())->orig_info();
}
References at().
outputSize()
uint32_t onert::exec::Executors::outputSize () const override virtual
Return executor set's number of output.
Returns
Number of output
Implements onert::exec::IExecutors.
Definition at line 80 of file Executors.cc.
{ return _model_edges->pkg_outputs.size(); }
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/Executors.h
runtime/onert/core/src/exec/Executors.cc