ONE - On-device Neural Engine: onert::backend::builtin::TensorRegistry Class Reference
onert::backend::builtin::TensorRegistry Class Reference
Tensor registry class for builtin backend.
#include <TensorRegistry.h>
Public Member Functions
TensorRegistry ()
ITensor * getITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native tensors.
IPortableTensor * getPortableTensor (const ir::OperandIndex &ind)
IPortableTensor * getNativeTensor (const ir::OperandIndex &ind)
Tensor * getNativeOwnTensor (const ir::OperandIndex &ind)
IOTensor * getNativeIOTensor (const ir::OperandIndex &ind)
bool setMigrantTensor (const ir::OperandIndex &ind, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void setNativeOwnTensor (ir::OperandIndex ind, std::unique_ptr< Tensor > &&tensor)
void setNativeIOTensor (ir::OperandIndex ind, std::unique_ptr< IOTensor > &&tensor)
const ir::OperandIndexMap< std::unique_ptr< IOTensor > > & native_io_tensors ()
std::shared_ptr< basic::TensorRegistry > base_reg ()
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Detailed Description
Tensor registry class for builtin backend.
This class contains three types of tensors. Two native tensors(tensors that are managed by this backend) and the other is migrant tensor.
NativeIOTensor - IOTensor managed by this backend (in _base_reg)
NOTE The tensor it actually points to can be from another backend
NativeOwnTensor - basic::Tensor managed by this backend (in _base_reg)
MigrantTensor - IPortableTensor managed by other backends
Note
_base_reg is used in implementation to reuse basic::StaticTensorManager
Definition at line 47 of file TensorRegistry.h.
Constructor & Destructor Documentation
TensorRegistry()
onert::backend::builtin::TensorRegistry::TensorRegistry () inline
Definition at line 50 of file TensorRegistry.h.
: _base_reg{new basic::TensorRegistry} {}
Member Function Documentation
base_reg()
std::shared_ptr< basic::TensorRegistry > onert::backend::builtin::TensorRegistry::base_reg () inline
Definition at line 123 of file TensorRegistry.h.
{ return _base_reg; }
getITensor()
ITensor * onert::backend::builtin::TensorRegistry::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 52 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getITensor(ind);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(ind);
  }
References getNativeIOTensor().
Referenced by setMigrantTensor(), setNativeIOTensor(), and setNativeOwnTensor().
getNativeIOTensor()
IOTensor * onert::backend::builtin::TensorRegistry::getNativeIOTensor (const ir::OperandIndex & ind) inline
Definition at line 89 of file TensorRegistry.h.
  {
    auto tensor = _native_io_tensors.find(ind);
    if (tensor != _native_io_tensors.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by getITensor(), getNativeITensor(), getNativeTensor(), and getPortableTensor().
getNativeITensor()
ITensor * onert::backend::builtin::TensorRegistry::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 60 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getNativeITensor(ind);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(ind);
  }
References getNativeIOTensor().
getNativeOwnTensor()
Tensor * onert::backend::builtin::TensorRegistry::getNativeOwnTensor (const ir::OperandIndex & ind) inline
Definition at line 84 of file TensorRegistry.h.
  {
    return _base_reg->getNativeTensor(ind);
  }
getNativeTensor()
IPortableTensor * onert::backend::builtin::TensorRegistry::getNativeTensor (const ir::OperandIndex & ind) inline
Definition at line 76 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getNativeTensor(ind);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(ind);
  }
References getNativeIOTensor().
getPortableTensor()
IPortableTensor * onert::backend::builtin::TensorRegistry::getPortableTensor (const ir::OperandIndex & ind) inline
Definition at line 68 of file TensorRegistry.h.
  {
    auto base_tensor = _base_reg->getPortableTensor(ind);
    if (base_tensor)
      return base_tensor;
    return getNativeIOTensor(ind);
  }
References getNativeIOTensor().
native_io_tensors()
const ir::OperandIndexMap< std::unique_ptr< IOTensor > > & onert::backend::builtin::TensorRegistry::native_io_tensors () inline
Definition at line 119 of file TensorRegistry.h.
  {
    return _native_io_tensors;
  }
setMigrantTensor()
bool onert::backend::builtin::TensorRegistry::setMigrantTensor (const ir::OperandIndex & , IPortableTensor *) inline override virtual
Set the Migrant Tensor which are from other backends.
Returns
true if supported
false if not supported
Reimplemented from onert::backend::ITensorRegistry.
Definition at line 97 of file TensorRegistry.h.
  {
    assert(tensor);
    assert(!getITensor(ind)); // For the ind, tensor is not registered yet
    _base_reg->setMigrantTensor(ind, tensor);
    return true;
  }
References getITensor().
setNativeIOTensor()
void onert::backend::builtin::TensorRegistry::setNativeIOTensor (ir::OperandIndex ind, std::unique_ptr< IOTensor > && tensor) inline
Definition at line 112 of file TensorRegistry.h.
  {
    assert(tensor);
    assert(!getITensor(ind)); // For the ind, tensor is not registered yet
    _native_io_tensors[ind] = std::move(tensor);
  }
References getITensor().
setNativeOwnTensor()
void onert::backend::builtin::TensorRegistry::setNativeOwnTensor (ir::OperandIndex ind, std::unique_ptr< Tensor > && tensor) inline
Definition at line 105 of file TensorRegistry.h.
  {
    assert(tensor);
    assert(!getITensor(ind)); // For the ind, tensor is not registered yet
    _base_reg->setNativeTensor(ind, std::move(tensor));
  }
References getITensor().
The documentation for this class was generated from the following file:
runtime/onert/core/src/backend/builtin/TensorRegistry.h