ONE - On-device Neural Engine: onert_micro::OMTrainingInterpreter Class Reference
onert_micro::OMTrainingInterpreter Class Reference
#include <OMTrainingInterpreter.h>
Public Member Functions
OMTrainingInterpreter ()=default
OMTrainingInterpreter (const OMTrainingInterpreter &)=delete
OMTrainingInterpreter (OMTrainingInterpreter &&)=delete
OMTrainingInterpreter & operator= (const OMTrainingInterpreter &)=delete
OMTrainingInterpreter && operator= (const OMTrainingInterpreter &&)=delete
~OMTrainingInterpreter ()=default
OMStatus importTrainModel (char *model_ptr, const OMConfig &config)
void setInput (uint8_t *data, uint32_t input_index)
void setTarget (uint8_t *data, uint32_t target_index)
OMStatus trainSingleStep (OMConfig &config)
OMStatus reset ()
OMStatus evaluateMetric (OMMetrics metric, void *metric_val, uint32_t test_size)
uint32_t getInputSizeAt (uint32_t position)
uint32_t getOutputSizeAt (uint32_t position)
OMStatus saveModel (const OMConfig &config, const char *save_path)
OMStatus saveCheckpoint (const OMConfig &config, const char *save_path)
OMStatus loadCheckpoint (OMConfig &config, const char *load_path)
Detailed Description
Definition at line 28 of file OMTrainingInterpreter.h.
Constructor & Destructor Documentation
OMTrainingInterpreter() [1/3]
onert_micro::OMTrainingInterpreter::OMTrainingInterpreter () default
OMTrainingInterpreter() [2/3]
onert_micro::OMTrainingInterpreter::OMTrainingInterpreter (const OMTrainingInterpreter &) delete
OMTrainingInterpreter() [3/3]
onert_micro::OMTrainingInterpreter::OMTrainingInterpreter (OMTrainingInterpreter &&) delete
~OMTrainingInterpreter()
onert_micro::OMTrainingInterpreter::~OMTrainingInterpreter () default
Member Function Documentation
evaluateMetric()
OMStatus onert_micro::OMTrainingInterpreter::evaluateMetric (OMMetrics metric, void * metric_val, uint32_t test_size) inline
Definition at line 71 of file OMTrainingInterpreter.h.
  {
    return _training_runtime_module.evaluateMetric(metric, metric_val, test_size);
  }
References onert_micro::core::OMTrainingRuntimeModule::evaluateMetric().
getInputSizeAt()
uint32_t OMTrainingInterpreter::getInputSizeAt (uint32_t position)
Definition at line 41 of file OMTrainingInterpreter.cpp.
{
  return _training_runtime_module.getInputSizeAt(position);
}
References onert_micro::core::OMRuntimeModule::getInputSizeAt().
getOutputSizeAt()
uint32_t OMTrainingInterpreter::getOutputSizeAt (uint32_t position)
Definition at line 46 of file OMTrainingInterpreter.cpp.
{
  return _training_runtime_module.getOutputSizeAt(position);
}
References onert_micro::core::OMRuntimeModule::getOutputSizeAt().
importTrainModel()
OMStatus OMTrainingInterpreter::importTrainModel (char * model_ptr, const OMConfig & config)
Definition at line 25 of file OMTrainingInterpreter.cpp.
{
  assert(model_ptr != nullptr && "Model ptr shouldn't be nullptr");
  if (model_ptr == nullptr)
    return UnknownError;
  return _training_runtime_module.importTrainModel(model_ptr, config);
}
References onert_micro::core::OMTrainingRuntimeModule::importTrainModel(), and onert_micro::UnknownError.
loadCheckpoint()
OMStatus OMTrainingInterpreter::loadCheckpoint (OMConfig & config, const char * load_path)
Definition at line 77 of file OMTrainingInterpreter.cpp.
{
  // Not imported or path is empty
  if (load_path == nullptr or config.model_ptr == nullptr or config.model_size == 0)
    return UnknownError;
  // Get DataBuffer (vector of chars) of checkpoints
  std::vector<char> checkpoint_data;
  // Read data
#ifndef DIS_STREAM
  std::ifstream file(load_path, std::ios::binary | std::ios::in);
  if (!file.good())
  {
    assert(false && "Fail to open");
    return UnknownError;
  }
  file.seekg(0, std::ios::end);
  auto fileSize = file.tellg();
  file.seekg(0, std::ios::beg);
  // reserve capacity
  checkpoint_data.resize(fileSize);
  // read the data
  file.read(checkpoint_data.data(), fileSize);
  if (file.fail())
  {
    assert(false && "Fail to read");
    return UnknownError;
  }
#else
  assert(false && "Not supported");
  return UnknownError;
#endif // DIS_STREAM
  // Load data
  OMStatus status = _training_runtime_module.loadCheckpointData(config, checkpoint_data.data());
  return status;
}
References onert_micro::core::OMTrainingRuntimeModule::loadCheckpointData(), and onert_micro::UnknownError.
operator=() [1/2]
OMTrainingInterpreter && onert_micro::OMTrainingInterpreter::operator= (const OMTrainingInterpreter &&) delete
operator=() [2/2]
OMTrainingInterpreter & onert_micro::OMTrainingInterpreter::operator= (const OMTrainingInterpreter &) delete
reset()
OMStatus OMTrainingInterpreter::reset ()
Definition at line 39 of file OMTrainingInterpreter.cpp.
{ return _training_runtime_module.reset(); }
References onert_micro::core::OMTrainingRuntimeModule::reset().
saveCheckpoint()
OMStatus OMTrainingInterpreter::saveCheckpoint (const OMConfig & config, const char * save_path)
Definition at line 120 of file OMTrainingInterpreter.cpp.
{
  // Not imported or path is empty
  if (save_path == nullptr or config.model_ptr == nullptr or config.model_size == 0)
    return UnknownError;
  // Get DataBuffer (vector of chars) of checkpoints
  std::vector<char> checkpoint_data;
  OMStatus status = _training_runtime_module.createCheckpointFile(config, checkpoint_data);
  assert(status == Ok);
  if (status != Ok)
    return status;
    // Save it into save_path
#ifndef DIS_STREAM
  // Open or create file
  // Note: if the file existed, it will be overwritten
  std::ofstream out_file(save_path, std::ios::binary | std::ios::trunc);
  if (not out_file.is_open())
    return UnknownError;
  // Write data
  out_file.write(checkpoint_data.data(), checkpoint_data.size());
  // Close file
  out_file.close();
#else
  assert(false && "Not supported");
  return UnknownError;
#endif // DIS_STREAM
  return Ok;
}
References onert_micro::core::OMTrainingRuntimeModule::createCheckpointFile(), onert_micro::Ok, and onert_micro::UnknownError.
saveModel()
OMStatus OMTrainingInterpreter::saveModel (const OMConfig & config, const char * save_path)
Definition at line 51 of file OMTrainingInterpreter.cpp.
{
  if (save_path == nullptr or config.model_size == 0 or config.model_ptr == nullptr)
    return UnknownError;
#ifndef DIS_STREAM
  // Open or create file
  // Note: if the file existed, it will be overwritten
  std::ofstream out_file(save_path, std::ios::binary | std::ios::trunc);
  if (not out_file.is_open())
    return UnknownError;
  // Write data
  out_file.write(config.model_ptr, config.model_size);
  // Close file
  out_file.close();
#else
  assert(false && "Not supported");
  return UnknownError;
#endif // DIS_STREAM
  // Saving done
  return Ok;
}
References onert_micro::Ok, and onert_micro::UnknownError.
setInput()
void onert_micro::OMTrainingInterpreter::setInput (uint8_t * data, uint32_t input_index) inline
Definition at line 47 of file OMTrainingInterpreter.h.
  {
    _training_runtime_module.setInputData(data, input_index);
  }
References onert_micro::core::OMTrainingRuntimeModule::setInputData().
setTarget()
void onert_micro::OMTrainingInterpreter::setTarget (uint8_t * data, uint32_t target_index) inline
Definition at line 53 of file OMTrainingInterpreter.h.
  {
    _training_runtime_module.setTargetData(data, target_index);
  }
References onert_micro::core::OMTrainingRuntimeModule::setTargetData().
trainSingleStep()
OMStatus OMTrainingInterpreter::trainSingleStep (OMConfig & config)
Definition at line 34 of file OMTrainingInterpreter.cpp.
{
  return _training_runtime_module.trainSingleStep(config);
}
References onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/OMTrainingInterpreter.h
onert-micro/onert-micro/src/OMTrainingInterpreter.cpp