ONE - On-device Neural Engine: onert::compiler::OperationLowerInfo Class Reference
onert::compiler::OperationLowerInfo Class Reference
#include <OperationLowerInfo.h>
Public Member Functions
OperationLowerInfo (const backend::Backend *backend, ir::Layout layout)
const backend::Backend * backend () const
ir::Layout layout () const
Detailed Description
Definition at line 38 of file OperationLowerInfo.h.
Constructor & Destructor Documentation
OperationLowerInfo()
onert::compiler::OperationLowerInfo::OperationLowerInfo (const backend::Backend * backend, ir::Layout layout)
Definition at line 24 of file OperationLowerInfo.cc.
  : _permute_factor{backend, layout}
{
  // DO NOTHING
}
Member Function Documentation
backend()
const backend::Backend * onert::compiler::OperationLowerInfo::backend () const inline
Definition at line 42 of file OperationLowerInfo.h.
{ return _permute_factor.backend(); }
References onert::compiler::PermuteFactor::backend().
Referenced by onert::exec::ParallelExecutor::executeImpl().
layout()
ir::Layout onert::compiler::OperationLowerInfo::layout () const inline
Definition at line 43 of file OperationLowerInfo.h.
{ return _permute_factor.layout(); }
References onert::compiler::PermuteFactor::layout().
The documentation for this class was generated from the following files:
runtime/onert/core/include/compiler/OperationLowerInfo.h
runtime/onert/core/src/compiler/OperationLowerInfo.cc