ONE - On-device Neural Engine: caffeimport::GraphBuilderContext Class Reference
caffeimport::GraphBuilderContext Class Reference
#include <Context.h>
Public Member Functions
GraphBuilderContext (coco::Module *module, coco::Data *data, coco::Block *block, ShapeContext &shape_ctx, StoreContext &bag_ctx, WeightContext &weight_ctx)
GraphBuilderContext (const GraphBuilderContext &)=delete
GraphBuilderContext (GraphBuilderContext &&)=delete
coco::Module * module ()
coco::Data * data ()
coco::Block * block ()
ShapeContext & shape_ctx ()
StoreContext & bag_ctx ()
WeightContext & weight_ctx ()
Detailed Description
Definition at line 78 of file Context.h.
Constructor & Destructor Documentation
GraphBuilderContext() [1/3]
caffeimport::GraphBuilderContext::GraphBuilderContext (coco::Module * module, coco::Data * data, coco::Block * block, ShapeContext & shape_ctx, StoreContext & bag_ctx, WeightContext & weight_ctx) inline explicit
Definition at line 81 of file Context.h.
    : _module(module), _data(data), _block(block), _shape_ctx(shape_ctx), _bag_ctx(bag_ctx),
      _weight_ctx(weight_ctx)
  {
    // DO NOTHING
  }
GraphBuilderContext() [2/3]
caffeimport::GraphBuilderContext::GraphBuilderContext (const GraphBuilderContext &) delete
GraphBuilderContext() [3/3]
caffeimport::GraphBuilderContext::GraphBuilderContext (GraphBuilderContext &&) delete
Member Function Documentation
bag_ctx()
StoreContext & caffeimport::GraphBuilderContext::bag_ctx () inline
Definition at line 98 of file Context.h.
{ return _bag_ctx; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
block()
coco::Block * caffeimport::GraphBuilderContext::block () inline
Definition at line 96 of file Context.h.
{ return _block; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
data()
coco::Data * caffeimport::GraphBuilderContext::data () inline
Definition at line 95 of file Context.h.
{ return _data; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), and caffeimport::ScaleBuilder::build().
module()
coco::Module * caffeimport::GraphBuilderContext::module () inline
Definition at line 94 of file Context.h.
{ return _module; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
shape_ctx()
ShapeContext & caffeimport::GraphBuilderContext::shape_ctx () inline
Definition at line 97 of file Context.h.
{ return _shape_ctx; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
weight_ctx()
WeightContext & caffeimport::GraphBuilderContext::weight_ctx () inline
Definition at line 99 of file Context.h.
{ return _weight_ctx; }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), and caffeimport::ScaleBuilder::build().
The documentation for this class was generated from the following file:
compiler/enco/frontend/caffe/src/Context.h