ONE - On-device Neural Engine: nnc::ArtifactClass Class Reference
nnc::ArtifactClass Class Reference
Represents a class.
#include <ArtifactModel.h>
Public Member Functions
ArtifactClass (const std::string &class_name)
void accept (IArtifactGenerator *g) const override
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
std::shared_ptr< ArtifactClassVariable > var (bool is_public, const std::string &type_name, const std::string &var_name, const std::list< std::shared_ptr< ArtifactExpr > > &dimensions={}, const std::list< std::shared_ptr< ArtifactExpr > > &initializers={})
Creates a class member variable.
std::shared_ptr< ArtifactClassFunction > func (bool is_public, const std::string &ret_type_name, const std::string &func_name, const std::list< std::shared_ptr< ArtifactVariable > > &params={})
Creates a class member function.
const std::list< std::shared_ptr< ArtifactClassVariable > > & publicVariables () const
const std::list< std::shared_ptr< ArtifactClassVariable > > & privateVariables () const
const std::list< std::shared_ptr< ArtifactClassFunction > > & publicFunctions () const
const std::list< std::shared_ptr< ArtifactClassFunction > > & privateFunctions () const
ArtifactBlock * getConstrBlock ()
const ArtifactBlock * getConstrBlock () const
Public Member Functions inherited from nnc::ArtifactNamed
ArtifactNamed (std::string name)
const std::string & name () const
Public Member Functions inherited from nnc::ArtifactEntity
virtual ~ArtifactEntity ()=default
virtual bool isBlock () const
If this entity represents something containing a block of instructions.
virtual void accept (IArtifactGenerator *g) const =0
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Additional Inherited Members
Protected Member Functions inherited from nnc::ArtifactEntity
ArtifactEntity ()=default
Detailed Description
Represents a class.
Definition at line 597 of file ArtifactModel.h.
Constructor & Destructor Documentation
ArtifactClass()
nnc::ArtifactClass::ArtifactClass (const std::string & class_name) inline explicit
Definition at line 600 of file ArtifactModel.h.
: ArtifactNamed(class_name) {}
Member Function Documentation
accept()
void nnc::ArtifactClass::accept (IArtifactGenerator * g) const inline override virtual
This is the core function of each artifact entity and is implemented by all concrete classes in the hierarchy.
Implements nnc::ArtifactEntity.
Definition at line 602 of file ArtifactModel.h.
{ g->visit(this); }
Referenced by TEST().
func()
std::shared_ptr< ArtifactClassFunction > nnc::ArtifactClass::func (bool is_public, const std::string & ret_type_name, const std::string & func_name, const std::list< std::shared_ptr< ArtifactVariable > > & params = {}) inline
Creates a class member function.
Parameters
is_public - if the created function be public.
ret_type_name
func_name
params
Returns
Definition at line 644 of file ArtifactModel.h.
                                                                {})
  {
    if (is_public)
    {
      auto func = std::make_shared<ArtifactClassFunction>(this, ret_type_name, func_name, params);
      _publicFunctions.push_back(func);
      return func;
    }
    else
    {
      auto func = std::make_shared<ArtifactClassFunction>(this, ret_type_name, func_name, params);
      _privateFunctions.push_back(func);
      return func;
    }
  }
Referenced by TEST().
getConstrBlock() [1/2]
ArtifactBlock * nnc::ArtifactClass::getConstrBlock () inline
Definition at line 681 of file ArtifactModel.h.
{ return &_constrBlock; }
Referenced by nnc::ArtifactGeneratorCppCode::visit().
getConstrBlock() [2/2]
const ArtifactBlock * nnc::ArtifactClass::getConstrBlock () const inline
Definition at line 683 of file ArtifactModel.h.
{ return &_constrBlock; }
privateFunctions()
const std::list< std::shared_ptr< ArtifactClassFunction > > & nnc::ArtifactClass::privateFunctions () const inline
Definition at line 676 of file ArtifactModel.h.
  {
    return _privateFunctions;
  }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
privateVariables()
const std::list< std::shared_ptr< ArtifactClassVariable > > & nnc::ArtifactClass::privateVariables () const inline
Definition at line 666 of file ArtifactModel.h.
  {
    return _privateVariables;
  }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
publicFunctions()
const std::list< std::shared_ptr< ArtifactClassFunction > > & nnc::ArtifactClass::publicFunctions () const inline
Definition at line 671 of file ArtifactModel.h.
  {
    return _publicFunctions;
  }
Referenced by nnc::ArtifactGeneratorCppCode::visit(), and nnc::ArtifactGeneratorCppDecl::visit().
publicVariables()
const std::list< std::shared_ptr< ArtifactClassVariable > > & nnc::ArtifactClass::publicVariables () const inline
Definition at line 661 of file ArtifactModel.h.
  {
    return _publicVariables;
  }
var()
std::shared_ptr< ArtifactClassVariable > nnc::ArtifactClass::var (bool is_public, const std::string & type_name, const std::string & var_name, const std::list< std::shared_ptr< ArtifactExpr > > & dimensions = {}, const std::list< std::shared_ptr< ArtifactExpr > > & initializers = {}) inline
Creates a class member variable.
Parameters
is_public - if the created variable be public.
type_name
var_name
dimensions
initializer
constructors
Returns
Definition at line 615 of file ArtifactModel.h.
                                                               {},
      const std::list<std::shared_ptr<ArtifactExpr>> &initializers = {})
  {
    if (is_public)
    {
      auto var = std::make_shared<ArtifactClassVariable>(this, type_name, var_name, dimensions,
                                                         initializers);
      _publicVariables.push_back(var);
      return var;
    }
    else
    {
      auto var = std::make_shared<ArtifactClassVariable>(this, type_name, var_name, dimensions,
                                                         initializers);
      _privateVariables.push_back(var);
      return var;
    }
  }
The documentation for this class was generated from the following file:
compiler/nnc/backends/acl_soft_backend/ArtifactModel.h