ONE - On-device Neural Engine: onert::Exception Class Reference
onert::Exception Class Reference
#include <Exceptions.h>
Public Member Functions
Exception (const std::string &msg)
Exception (const std::string &tag, const std::string &msg)
const char * what () const noexcept override
Detailed Description
Definition at line 25 of file Exceptions.h.
Constructor & Destructor Documentation
Exception() [1/2]
onert::Exception::Exception (const std::string & msg) inline
Definition at line 28 of file Exceptions.h.
: _msg{msg} {}
Exception() [2/2]
onert::Exception::Exception (const std::string & tag, const std::string & msg) inline
Definition at line 29 of file Exceptions.h.
: _msg{tag + " : " + msg} {}
Member Function Documentation
what()
const char * onert::Exception::what () const inline override noexcept
Definition at line 31 of file Exceptions.h.
{ return _msg.c_str(); }
Referenced by onert::api::Session::run(), onert::api::Session::run_with_auto_compilation(), and onert::api::Session::train_run().
The documentation for this class was generated from the following file:
runtime/onert/core/include/util/Exceptions.h