ONE - On-device Neural Engine: coco::Def Class Reference
coco::Def Class Reference final
#include <Def.h>
Public Member Functions
Def (Object::Producer *producer)
~Def ()
Object * value (void) const
void value (Object *value)
Object::Producer * producer (void) const
Detailed Description
Definition at line 25 of file Def.h.
Constructor & Destructor Documentation
Def()
coco::Def::Def (Object::Producer * producer) inline
Definition at line 28 of file Def.h.
                                : _producer{producer}
  {
    // DO NOTHING
  }
~Def()
coco::Def::~Def () inline
Definition at line 34 of file Def.h.
{ value(nullptr); }
References value().
Member Function Documentation
producer()
Object::Producer * coco::Def::producer (void) const inline
Definition at line 43 of file Def.h.
{ return _producer; }
Referenced by coco::producer().
value() [1/2]
void coco::Def::value (Object * value)
Definition at line 24 of file Def.cpp.
{
  if (_value)
  {
    _value->def(nullptr);
    _value = nullptr;
  }
  assert(_value == nullptr);
  if (value)
  {
    _value = value;
    _value->def(this);
  }
  assert(_value == value);
}
References coco::Object::def(), and value().
value() [2/2]
Object * coco::Def::value (void) const inline
Definition at line 37 of file Def.h.
{ return _value; }
Referenced by coco::Copy::into(), ANNConv2D::ofm(), coco::Eval::out(), ANNDepthConcatF::out(), value(), and ~Def().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Def.h
compiler/coco/core/src/IR/Def.cpp