ONE - On-device Neural Engine: arm_compute::CLArgMinMaxLayerKernelEx Class Reference
arm_compute::CLArgMinMaxLayerKernelEx Class Reference
#include <CLArgMinMaxLayerKernelEx.h>
Public Member Functions
CLArgMinMaxLayerKernelEx ()
CLArgMinMaxLayerKernelEx (const CLArgMinMaxLayerKernelEx &)=delete
CLArgMinMaxLayerKernelEx & operator= (const CLArgMinMaxLayerKernelEx &)=delete
CLArgMinMaxLayerKernelEx (CLArgMinMaxLayerKernelEx &&)=default
CLArgMinMaxLayerKernelEx & operator= (CLArgMinMaxLayerKernelEx &&)=default
~CLArgMinMaxLayerKernelEx ()=default
void configure (const ICLTensor *input, const ICLTensor *prev_output, ICLTensor *output, unsigned int axis, ReductionOperation op)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *prev_output, const ITensorInfo *output, unsigned int axis, ReductionOperation op)
Detailed Description
Interface for the reduction operation kernel
Note
The default data type for an uninitialized output tensor is signed 32-bit integer (S32). It is the user's responsibility to check that the results do not overflow because the indices are computed in unsigned 32-bit (U32).
Definition at line 57 of file CLArgMinMaxLayerKernelEx.h.
Constructor & Destructor Documentation
CLArgMinMaxLayerKernelEx() [1/3]
arm_compute::CLArgMinMaxLayerKernelEx::CLArgMinMaxLayerKernelEx ()
Default constructor
Definition at line 149 of file CLArgMinMaxLayerKernelEx.cpp.
  : _input(nullptr), _prev_output(nullptr), _output(nullptr), _reduction_axis(0),
    _op(ReductionOperation::ARG_IDX_MAX)
{
}
CLArgMinMaxLayerKernelEx() [2/3]
arm_compute::CLArgMinMaxLayerKernelEx::CLArgMinMaxLayerKernelEx (const CLArgMinMaxLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLArgMinMaxLayerKernelEx() [3/3]
arm_compute::CLArgMinMaxLayerKernelEx::CLArgMinMaxLayerKernelEx (CLArgMinMaxLayerKernelEx &&) default
Allow instances of this class to be moved
~CLArgMinMaxLayerKernelEx()
arm_compute::CLArgMinMaxLayerKernelEx::~CLArgMinMaxLayerKernelEx () default
Default destructor
References validate().
Member Function Documentation
configure()
void arm_compute::CLArgMinMaxLayerKernelEx::configure (const ICLTensor * input, const ICLTensor * prev_output, ICLTensor * output, unsigned int axis, ReductionOperation op)
Set the input and output tensors.
Parameters
[in] input Source tensor. Data types supported: S32/F16/F32.
[in] prev_output Destination tensor of the previous iterations of CLArgMinMaxLayerKernelEx. Data types supported: U32/S32 Has to be nullptr for the first iteration
[out] output Destination tensor. Data types supported: U32/S32 Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0,1,2,3
[in] op Reduction operation to perform. Only ArgMin and ArgMax are supported.
Definition at line 155 of file CLArgMinMaxLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), (prev_output != nullptr) ? prev_output->info() : nullptr,
                       output->info(), axis, op));
  auto win_config = validate_and_configure_window(
    input->info(), (prev_output != nullptr) ? prev_output->info() : nullptr, output->info(), axis,
    op);
  ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
  _input = input;
  _prev_output = prev_output;
  _output = output;
  _reduction_axis = axis;
  _op = op;
  // Set build options
  CLBuildOptions build_opts;
  build_opts.add_option_if(_prev_output != nullptr, "-DPREV_OUTPUT");
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.add_option_if(is_data_type_float(input->info()->data_type()), "-DFLOAT_DATA_TYPE");
  build_opts.add_option_if_else(op == ReductionOperation::ARG_IDX_MAX, "-DARG_MAX", "-DARG_MIN");
  build_opts.add_option("-DDATA_TYPE_OUTPUT=" +
                        get_cl_type_from_data_type(output->info()->data_type()));
  build_opts.add_option("-DDATA_TYPE_SELECT=" +
                        get_cl_signed_type_from_element_size(input->info()->element_size()));
  // Create kernel
  cl::NDRange lws_hint = CLKernelLibrary::get().default_ndrange();
  std::string kernel_axis_name;
  switch (axis)
  {
    case 0:
    {
      const ICLTensor *input_for_width = prev_output != nullptr ? _prev_output : _input;
      build_opts.add_option("-DWIDTH=" +
                            support::cpp11::to_string(input_for_width->info()->dimension(0)));
      kernel_axis_name = "x";
      lws_hint = create_lws_hint_parallel_implementations(input_for_width->info()->dimension(0),
                                                          vector_size);
    }
    break;
    case 1:
      build_opts.add_option("-DHEIGHT=" + support::cpp11::to_string(input->info()->dimension(1)));
      kernel_axis_name = "y";
      break;
    case 2:
      build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
      kernel_axis_name = "z";
      break;
    case 3:
      build_opts.add_option("-DDEPTH=" + support::cpp11::to_string(input->info()->dimension(2)));
      build_opts.add_option("-DBATCH=" + support::cpp11::to_string(input->info()->dimension(3)));
      kernel_axis_name = "w";
      break;
    default:
      ARM_COMPUTE_ERROR("Not supported");
  }
  _kernel = static_cast<cl::Kernel>(CLKernelLibraryEx::get().create_kernel(
    "arg_min_max_ex_" + kernel_axis_name, build_opts.options()));
  // Configure kernel window
  ICLKernel::configure_internal(std::get<1>(win_config), lws_hint);
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
operator=() [1/2]
CLArgMinMaxLayerKernelEx & arm_compute::CLArgMinMaxLayerKernelEx::operator= (CLArgMinMaxLayerKernelEx &&) default
Allow instances of this class to be moved
operator=() [2/2]
CLArgMinMaxLayerKernelEx & arm_compute::CLArgMinMaxLayerKernelEx::operator= (const CLArgMinMaxLayerKernelEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLArgMinMaxLayerKernelEx::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 236 of file CLArgMinMaxLayerKernelEx.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  switch (_reduction_axis)
  {
    case 0:
    {
      // Set out window
      Window out_window(window);
      out_window.set(Window::DimX, Window::Dimension(0, 0, 0));
      // Get first input and output slices
      Window in_slice = window.first_slice_window_2D();
      Window out_slice = out_window.first_slice_window_2D();
      // Reshape window
      const unsigned int num_tensors = _prev_output != nullptr ? 3 : 2;
      // Set local sums buffer
      unsigned int local_res_size = lws_hint()[0] * _output->info()->element_size();
      _kernel.setArg(num_arguments_per_2D_tensor() * num_tensors, local_res_size, nullptr);
      do
      {
        unsigned int idx = 0;
        add_2D_tensor_argument(idx, _input, in_slice);
        if (_prev_output != nullptr)
        {
          add_2D_tensor_argument(idx, _prev_output, in_slice);
        }
        add_2D_tensor_argument(idx, _output, out_slice);
        enqueue(queue, *this, in_slice, lws_hint());
      } while (window.slide_window_slice_2D(in_slice) && window.slide_window_slice_2D(out_slice));
    }
    break;
    case 1:
    {
      // Get first input and output slices
      Window window_in{window};
      window_in.set(Window::DimY, Window::Dimension(0, _input->info()->dimension(1),
                                                    _input->info()->dimension(1)));
      Window in_slice = window_in.first_slice_window_2D();
      Window out_slice = window.first_slice_window_2D();
      do
      {
        unsigned int idx = 0;
        add_2D_tensor_argument(idx, _input, in_slice);
        add_2D_tensor_argument(idx, _output, out_slice);
        enqueue(queue, *this, in_slice, lws_hint());
      } while (window_in.slide_window_slice_2D(in_slice) &&
               window.slide_window_slice_2D(out_slice));
    }
    break;
    case 2:
    {
      // Get first input and output slices
      Window window_in{window};
      window_in.set(Window::DimZ, Window::Dimension(0, _input->info()->dimension(2),
                                                    _input->info()->dimension(2)));
      Window in_slice = window_in.first_slice_window_3D();
      Window out_slice = window.first_slice_window_3D();
      do
      {
        unsigned int idx = 0;
        add_3D_tensor_argument(idx, _input, in_slice);
        add_3D_tensor_argument(idx, _output, out_slice);
        enqueue(queue, *this, in_slice, lws_hint());
      } while (window_in.slide_window_slice_3D(in_slice) &&
               window.slide_window_slice_3D(out_slice));
    }
    break;
    case 3:
    {
      // Get first input and output slices
      Window window_in{window};
      window_in.set(3, Window::Dimension(0, 1, 1));
      Window in_slice = window_in.first_slice_window_4D();
      Window out_slice = window.first_slice_window_4D();
      do
      {
        unsigned int idx = 0;
        add_4D_tensor_argument(idx, _input, in_slice);
        add_4D_tensor_argument(idx, _output, out_slice);
        enqueue(queue, *this, in_slice, lws_hint());
      } while (window_in.slide_window_slice_4D(in_slice) &&
               window.slide_window_slice_4D(out_slice));
    }
    break;
    default:
      ARM_COMPUTE_ERROR("Not supported");
  }
}
validate()
Status arm_compute::CLArgMinMaxLayerKernelEx::validate (const ITensorInfo * input, const ITensorInfo * prev_output, const ITensorInfo * output, unsigned int axis, ReductionOperation op) static
Static function to check if given info will lead to a valid configuration of CLArgMinMaxLayerKernelEx.
Parameters
[in] input Source tensor info. Data types supported: S32/F16/F32.
[in] prev_output Destination tensor info of the previous iterations. Data types supported: U32/S32 Has to be nullptr for the first iteration
[in] output Destination tensor info. Data types supported: U32/S32 Output will have the same number of dimensions as input.
[in] axis Axis along which to reduce. Supported reduction axis : 0,1,2,3
[in] op Reduction operation to perform. Only ArgMin and ArgMax are supported.
Returns
a status
Definition at line 225 of file CLArgMinMaxLayerKernelEx.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, prev_output, output, axis, op));
  ARM_COMPUTE_RETURN_ON_ERROR(std::get<0>(validate_and_configure_window(
    input->clone().get(), (prev_output != nullptr) ? prev_output->clone().get() : nullptr,
    output->clone().get(), axis, op)));
  return Status{};
}
Referenced by arm_compute::CLArgMinMaxLayerEx::validate(), and ~CLArgMinMaxLayerKernelEx().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLArgMinMaxLayerKernelEx.h
compute/ARMComputeEx/src/core/CL/kernels/CLArgMinMaxLayerKernelEx.cpp