ONE - On-device Neural Engine: locoex::TFLReshape::Shape Class Reference
locoex::TFLReshape::Shape Class Reference
#include <TFLNodes.h>
Public Member Functions
uint32_t rank (void) const
void rank (uint32_t rank)
int32_t dim (uint32_t n) const
int32_t & dim (uint32_t n)
Detailed Description
Definition at line 419 of file TFLNodes.h.
Member Function Documentation
dim() [1/2]
int32_t & locoex::TFLReshape::Shape::dim (uint32_t n) inline
Definition at line 426 of file TFLNodes.h.
{ return _shape.at(n); }
dim() [2/2]
int32_t locoex::TFLReshape::Shape::dim (uint32_t n) const inline
Definition at line 425 of file TFLNodes.h.
{ return _shape.at(n); }
Referenced by locoex::set_new_shape().
rank() [1/2]
void locoex::TFLReshape::Shape::rank (uint32_t rank) inline
Definition at line 423 of file TFLNodes.h.
{ _shape.resize(rank); }
References rank().
rank() [2/2]
uint32_t locoex::TFLReshape::Shape::rank (void) const inline
Definition at line 422 of file TFLNodes.h.
{ return _shape.size(); }
Referenced by rank(), and locoex::set_new_shape().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h