ONE - On-device Neural Engine: luci::CircleUnpackGraphBuilder Class Reference
luci::CircleUnpackGraphBuilder Class Reference
#include <CircleUnpack.h>
Public Member Functions
bool validate (const ValidateArgs &args) const final
Public Member Functions inherited from luci::GraphBuilderMultiOutput
virtual ~GraphBuilderMultiOutput ()=default
CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const final
Public Member Functions inherited from luci::GraphBuilderBase
virtual bool validate (const ValidateArgs &) const =0
virtual CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const =0
virtual ~GraphBuilderBase ()=default
Detailed Description
Definition at line 25 of file CircleUnpack.h.
Member Function Documentation
validate()
bool luci::CircleUnpackGraphBuilder::validate (const ValidateArgs & args) const final virtual
Implements luci::GraphBuilderBase.
Definition at line 31 of file CircleUnpack.cpp.
{
  LOGGER(l);
  auto settings = luci::UserSettings::settings();
  const auto &inputs = args.op.inputs;
  const auto &outputs = args.op.outputs;
  const auto *options = args.op.builtin_options.AsUnpackOptions();
  if (inputs.size() != 1)
    return false;
  // NOTE real models may have mismatch
  if (static_cast<int32_t>(outputs.size()) != options->num)
  {
    if (settings->get(luci::UserSettings::Key::DisableValidation))
    {
      const auto tensors = args.reader.tensors();
      const auto output_tensor = tensors[outputs[0]];
      auto name = tensor_name(output_tensor);
      WARN(l) << "Warning: import Unpack(" << name << ") 'num' is not same as outputs used";
    }
    else
      return false;
  }
  if (options->num < 0)
    return false;
  const auto tensors = args.reader.tensors();
  const auto tensor = tensors.at(inputs.at(0));
  assert(tensor != nullptr);
  const auto shape = wrap(tensor->shape());
  auto shape_size = static_cast<int32_t>(shape.size());
  if (shape_size > 0)
  {
    // NOTE for unknown shape, shape_size is 0
    if (options->axis < -shape_size || options->axis >= shape_size)
      return false;
  }
  return true;
}
References luci::UserSettings::DisableValidation, LOGGER, luci::UserSettings::settings(), luci::tensor_name(), WARN, and luci::wrap().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Import/Nodes/CircleUnpack.h
compiler/luci/import/src/Nodes/CircleUnpack.cpp