ONE - On-device Neural Engine: arm_compute::CLGatherExKernel Class Reference
arm_compute::CLGatherExKernel Class Reference
Class to define an interface for the gather kernel.
#include <CLGatherExKernel.h>
Public Member Functions
CLGatherExKernel ()
Construct CLGatherExKernel object.
CLGatherExKernel (const CLGatherExKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLGatherExKernel & operator= (const CLGatherExKernel &)=delete
Prevent instances of this class from being copied (As this class contains pointers).
CLGatherExKernel (CLGatherExKernel &&)=default
Construct CLGatherExKernel object by using default move constructor.
CLGatherExKernel & operator= (CLGatherExKernel &&)=default
Move assignment operator.
void configure (const ICLTensor *input, const ICLTensor *indices, ICLTensor *output, int axis=0)
Initialise the kernel's input, output and border mode.
void run (const Window &window, cl::CommandQueue &queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *indices, const ITensorInfo *output, int axis=0)
Static function to check if given info will lead to a valid configuration of CLGatherExKernel.
Detailed Description
Class to define an interface for the gather kernel.
Definition at line 59 of file CLGatherExKernel.h.
Constructor & Destructor Documentation
CLGatherExKernel() [1/3]
CLGatherExKernel::CLGatherExKernel ()
Construct CLGatherExKernel object.
Definition at line 106 of file CLGatherExKernel.cpp.
  : _input(nullptr), _indices(nullptr), _output(nullptr), _axis(0)
{
}
CLGatherExKernel() [2/3]
arm_compute::CLGatherExKernel::CLGatherExKernel (const CLGatherExKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
CLGatherExKernel() [3/3]
arm_compute::CLGatherExKernel::CLGatherExKernel (CLGatherExKernel &&) default
Construct CLGatherExKernel object by using default move constructor.
Parameters
[in] CLGatherExKernel object to move
Member Function Documentation
configure()
void CLGatherExKernel::configure (const ICLTensor * input, const ICLTensor * indices, ICLTensor * output, int axis = 0)
Initialise the kernel's input, output and border mode.
Parameters
[in] input An input tensor. Data types supported: U8/QASYMM8/S32/F32.
[in] indices Indices tensor. Data types supported: S32.
[out] output The output tensor, Data types supported: same as input1.
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Returns
N/A
Definition at line 111 of file CLGatherExKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output, indices);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), indices->info(), output->info(), axis));
  // Configure kernel window
  auto win_config =
    validate_and_configure_window(input->info(), indices->info(), output->info(), axis);
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  _input = input;
  _output = output;
  _indices = indices;
  _axis = wrap_around(axis, static_cast<int>(input->info()->num_dimensions()));
  // Set build options
  CLBuildOptions build_opts;
  build_opts.add_option("-DDATA_TYPE=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.add_option("-DOUTPUT_DIM_Z=" +
                        support::cpp11::to_string(output->info()->dimension(2)));
  build_opts.add_option("-DINPUT_DIM_Z=" + support::cpp11::to_string(input->info()->dimension(2)));
  build_opts.add_option("-DAXIS=" + support::cpp11::to_string(_axis));
  build_opts.add_option("-DINDICES_DIM=" +
                        support::cpp11::to_string(indices->info()->num_dimensions()));
  // Create kernel
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("gather_ex", build_opts.options()));
  ICLKernel::configure_internal(win_config.second);
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
operator=() [1/2]
CLGatherExKernel & arm_compute::CLGatherExKernel::operator= (CLGatherExKernel &&) default
Move assignment operator.
Parameters
[in] CLGatherExKernel object to move
References validate().
operator=() [2/2]
CLGatherExKernel & arm_compute::CLGatherExKernel::operator= (const CLGatherExKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers).
run()
void CLGatherExKernel::run (const Window & window, cl::CommandQueue & queue) override
Enqueue the OpenCL kernel to process the given window on the passed OpenCL command queue.
Note
The queue is not flushed by this method, and therefore the kernel will not have been executed by the time this method returns.
Parameters
[in] window Region on which to execute the kernel. (Must be a valid region of the window returned by window()).
[in,out] queue Command queue on which to enqueue the kernel.
Returns
N/A
N/A
Definition at line 155 of file CLGatherExKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ, 4);
  unsigned int idx = 0;
  add_4D_tensor_argument(idx, _input, window_collapsed);
  add_3D_tensor_argument(idx, _indices, window_collapsed);
  add_4D_tensor_argument(idx, _output, window_collapsed);
  enqueue(queue, *this, window_collapsed, lws_hint());
}
validate()
Status CLGatherExKernel::validate (const ITensorInfo * input, const ITensorInfo * indices, const ITensorInfo * output, int axis = 0) static
Static function to check if given info will lead to a valid configuration of CLGatherExKernel.
Parameters
[in] input An input tensor. Data types supported: U8/QASYMM8/S32/F32.
[in] indices Indices tensor. Data types supported: S32.
[out] output The output tensor, Data types supported: same as input1.
[in] axis (Optional) The axis in input to gather indices from. Negative values wrap around. Defaults to 0
Returns
a status
Definition at line 144 of file CLGatherExKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, indices, output, axis));
  ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(input->clone().get(),
                                                            indices->clone().get(),
                                                            output->clone().get(), axis)
                                .first);
  return Status{};
}
Referenced by operator=(), and arm_compute::CLGatherEx::validate().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLGatherExKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLGatherExKernel.cpp