ONE - On-device Neural Engine: luci::CloneNodeLet< CN::STUV > Class Reference
luci::CloneNodeLet< CN::STUV > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleScatterNd *) final
luci::CircleNode * visit (const luci::CircleSegmentSum *) final
luci::CircleNode * visit (const luci::CircleSelect *) final
luci::CircleNode * visit (const luci::CircleSelectV2 *) final
luci::CircleNode * visit (const luci::CircleShape *) final
luci::CircleNode * visit (const luci::CircleSin *) final
luci::CircleNode * visit (const luci::CircleSlice *) final
luci::CircleNode * visit (const luci::CircleSoftmax *) final
luci::CircleNode * visit (const luci::CircleSpaceToBatchND *) final
luci::CircleNode * visit (const luci::CircleSpaceToDepth *) final
luci::CircleNode * visit (const luci::CircleSparseToDense *) final
luci::CircleNode * visit (const luci::CircleSplit *) final
luci::CircleNode * visit (const luci::CircleSplitV *) final
luci::CircleNode * visit (const luci::CircleSqrt *) final
luci::CircleNode * visit (const luci::CircleSquare *) final
luci::CircleNode * visit (const luci::CircleSquaredDifference *) final
luci::CircleNode * visit (const luci::CircleSqueeze *) final
luci::CircleNode * visit (const luci::CircleStridedSlice *) final
luci::CircleNode * visit (const luci::CircleSVDF *) final
luci::CircleNode * visit (const luci::CircleSub *) final
luci::CircleNode * visit (const luci::CircleSum *) final
luci::CircleNode * visit (const luci::CircleTanh *) final
luci::CircleNode * visit (const luci::CircleTile *) final
luci::CircleNode * visit (const luci::CircleTopKV2 *) final
luci::CircleNode * visit (const luci::CircleTranspose *) final
luci::CircleNode * visit (const luci::CircleTransposeConv *) final
luci::CircleNode * visit (const luci::CircleUnidirectionalSequenceLSTM *) final
luci::CircleNode * visit (const luci::CircleUnique *) final
luci::CircleNode * visit (const luci::CircleUnpack *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 188 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::STUV >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 191 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 224 of file CircleCloneNode.h.
{ return nullptr; }
visit() [2/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleScatterNd *) final
Definition at line 22 of file CircleScatterNd.cpp.
{
  return _graph->nodes()->create<luci::CircleScatterNd>();
}
visit() [3/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSegmentSum *) final
Definition at line 22 of file CircleSegmentSum.cpp.
{
  return _graph->nodes()->create<luci::CircleSegmentSum>();
}
visit() [4/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSelect *) final
Definition at line 22 of file CircleSelect.cpp.
{
  return _graph->nodes()->create<luci::CircleSelect>();
}
visit() [5/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSelectV2 *) final
Definition at line 22 of file CircleSelectV2.cpp.
{
  return _graph->nodes()->create<luci::CircleSelectV2>();
}
visit() [6/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleShape * node) final
Definition at line 22 of file CircleShape.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleShape>();
  if (cloned != nullptr)
    cloned->out_type(node->out_type());
  return cloned;
}
References luci::CircleShape::out_type().
visit() [7/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSin *) final
Definition at line 22 of file CircleSin.cpp.
{
  return _graph->nodes()->create<luci::CircleSin>();
}
visit() [8/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSlice *) final
Definition at line 22 of file CircleSlice.cpp.
{
  return _graph->nodes()->create<luci::CircleSlice>();
}
visit() [9/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSoftmax * node) final
Definition at line 22 of file CircleSoftmax.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSoftmax>();
  if (cloned != nullptr)
    cloned->beta(node->beta());
  return cloned;
}
References luci::CircleSoftmax::beta().
visit() [10/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSpaceToBatchND *) final
Definition at line 22 of file CircleSpaceToBatchND.cpp.
{
  return _graph->nodes()->create<luci::CircleSpaceToBatchND>();
}
visit() [11/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSpaceToDepth * node) final
Definition at line 22 of file CircleSpaceToDepth.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSpaceToDepth>();
  if (cloned != nullptr)
    cloned->block_size(node->block_size());
  return cloned;
}
References luci::CircleSpaceToDepth::block_size().
visit() [12/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSparseToDense * node) final
Definition at line 22 of file CircleSparseToDense.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSparseToDense>();
  if (cloned != nullptr)
    cloned->validate_indices(node->validate_indices());
  return cloned;
}
References luci::CircleSparseToDense::validate_indices().
visit() [13/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSplit * node) final
Definition at line 22 of file CircleSplit.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSplit>();
  if (cloned != nullptr)
    cloned->num_split(node->num_split());
  return cloned;
}
References luci::CircleSplit::num_split().
visit() [14/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSplitV * node) final
Definition at line 22 of file CircleSplitV.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSplitV>();
  if (cloned != nullptr)
    cloned->num_split(node->num_split());
  return cloned;
}
References luci::CircleSplitV::num_split().
visit() [15/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSqrt *) final
Definition at line 22 of file CircleSqrt.cpp.
{
  return _graph->nodes()->create<luci::CircleSqrt>();
}
visit() [16/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSquare *) final
Definition at line 22 of file CircleSquare.cpp.
{
  return _graph->nodes()->create<luci::CircleSquare>();
}
visit() [17/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSquaredDifference *) final
Definition at line 22 of file CircleSquaredDifference.cpp.
{
  return _graph->nodes()->create<luci::CircleSquaredDifference>();
}
visit() [18/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSqueeze * node) final
Definition at line 22 of file CircleSqueeze.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSqueeze>();
  if (cloned != nullptr)
    cloned->squeeze_dims(node->squeeze_dims());
  return cloned;
}
References luci::CircleSqueeze::squeeze_dims().
visit() [19/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleStridedSlice * node) final
Definition at line 22 of file CircleStridedSlice.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleStridedSlice>();
  if (cloned != nullptr)
  {
    cloned->begin_mask(node->begin_mask());
    cloned->end_mask(node->end_mask());
    cloned->ellipsis_mask(node->ellipsis_mask());
    cloned->new_axis_mask(node->new_axis_mask());
    cloned->shrink_axis_mask(node->shrink_axis_mask());
  }
  return cloned;
}
References luci::CircleStridedSlice::begin_mask(), luci::CircleStridedSlice::ellipsis_mask(), luci::CircleStridedSlice::end_mask(), luci::CircleStridedSlice::new_axis_mask(), and luci::CircleStridedSlice::shrink_axis_mask().
visit() [20/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSub * node) final
Definition at line 22 of file CircleSub.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleSub>();
  if (cloned != nullptr)
    cloned->fusedActivationFunction(node->fusedActivationFunction());
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), and luci::UNDEFINED.
visit() [21/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSum * node) final
Definition at line 22 of file CircleSum.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleSum>();
  if (cloned != nullptr)
    cloned->keep_dims(node->keep_dims());
  return cloned;
}
References luci::CircleSum::keep_dims().
visit() [22/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleSVDF * node) final
Definition at line 22 of file CircleSVDF.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleSVDF>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->asymmetric_quantize_inputs(node->asymmetric_quantize_inputs());
    cloned->svdf_rank(node->svdf_rank());
  }
  return cloned;
}
References luci::CircleSVDF::asymmetric_quantize_inputs(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleSVDF::svdf_rank(), and luci::UNDEFINED.
visit() [23/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleTanh *) final
Definition at line 22 of file CircleTanh.cpp.
{
  return _graph->nodes()->create<luci::CircleTanh>();
}
visit() [24/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleTile *) final
Definition at line 22 of file CircleTile.cpp.
{
  return _graph->nodes()->create<luci::CircleTile>();
}
visit() [25/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleTopKV2 *) final
Definition at line 22 of file CircleTopKV2.cpp.
{
  return _graph->nodes()->create<luci::CircleTopKV2>();
}
visit() [26/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleTranspose *) final
Definition at line 22 of file CircleTranspose.cpp.
{
  return _graph->nodes()->create<luci::CircleTranspose>();
}
visit() [27/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleTransposeConv * node) final
Definition at line 22 of file CircleTransposeConv.cpp.
{
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleTransposeConv>();
  if (cloned != nullptr)
  {
    cloned->padding(node->padding());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
  }
  return cloned;
}
References luci::Stride::h(), luci::CircleTransposeConv::padding(), luci::CircleTransposeConv::stride(), luci::UNDEFINED, and luci::Stride::w().
visit() [28/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleUnidirectionalSequenceLSTM * node) final
Definition at line 22 of file CircleUnidirectionalSequenceLSTM.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleUnidirectionalSequenceLSTM>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->cell_clip(node->cell_clip());
    cloned->proj_clip(node->proj_clip());
    cloned->time_major(node->time_major());
    cloned->asymmetric_quantize_inputs(node->asymmetric_quantize_inputs());
  }
  return cloned;
}
References luci::CircleUnidirectionalSequenceLSTM::asymmetric_quantize_inputs(), luci::CircleUnidirectionalSequenceLSTM::cell_clip(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleUnidirectionalSequenceLSTM::proj_clip(), luci::CircleUnidirectionalSequenceLSTM::time_major(), and luci::UNDEFINED.
visit() [29/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleUnique * node) final
Definition at line 22 of file CircleUnique.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleUnique>();
  if (cloned != nullptr)
    cloned->idx_out_type(node->idx_out_type());
  return cloned;
}
References luci::CircleUnique::idx_out_type().
visit() [30/30]
luci::CircleNode * luci::CloneNodeLet< CN::STUV >::visit (const luci::CircleUnpack * node) final
Definition at line 22 of file CircleUnpack.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleUnpack>();
  if (cloned != nullptr)
  {
    cloned->num(node->num());
    cloned->axis(node->axis());
  }
  return cloned;
}
References luci::CircleUnpack::axis(), and luci::CircleUnpack::num().
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::STUV >::_graph = nullptr protected
Definition at line 227 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleScatterNd.cpp
compiler/luci/service/src/Nodes/CircleSegmentSum.cpp
compiler/luci/service/src/Nodes/CircleSelect.cpp
compiler/luci/service/src/Nodes/CircleSelectV2.cpp
compiler/luci/service/src/Nodes/CircleShape.cpp
compiler/luci/service/src/Nodes/CircleSin.cpp
compiler/luci/service/src/Nodes/CircleSlice.cpp
compiler/luci/service/src/Nodes/CircleSoftmax.cpp
compiler/luci/service/src/Nodes/CircleSpaceToBatchND.cpp
compiler/luci/service/src/Nodes/CircleSpaceToDepth.cpp
compiler/luci/service/src/Nodes/CircleSparseToDense.cpp
compiler/luci/service/src/Nodes/CircleSplit.cpp
compiler/luci/service/src/Nodes/CircleSplitV.cpp
compiler/luci/service/src/Nodes/CircleSqrt.cpp
compiler/luci/service/src/Nodes/CircleSquare.cpp
compiler/luci/service/src/Nodes/CircleSquaredDifference.cpp
compiler/luci/service/src/Nodes/CircleSqueeze.cpp
compiler/luci/service/src/Nodes/CircleStridedSlice.cpp
compiler/luci/service/src/Nodes/CircleSub.cpp
compiler/luci/service/src/Nodes/CircleSum.cpp
compiler/luci/service/src/Nodes/CircleSVDF.cpp
compiler/luci/service/src/Nodes/CircleTanh.cpp
compiler/luci/service/src/Nodes/CircleTile.cpp
compiler/luci/service/src/Nodes/CircleTopKV2.cpp
compiler/luci/service/src/Nodes/CircleTranspose.cpp
compiler/luci/service/src/Nodes/CircleTransposeConv.cpp
compiler/luci/service/src/Nodes/CircleUnidirectionalSequenceLSTM.cpp
compiler/luci/service/src/Nodes/CircleUnique.cpp
compiler/luci/service/src/Nodes/CircleUnpack.cpp