ONE - On-device Neural Engine: coco::Padding2D Class Reference
coco::Padding2D Class Reference
#include <Padding2D.h>
Public Member Functions
Padding2D ()
Padding2D (uint32_t top, uint32_t bottom, uint32_t left, uint32_t right)
uint32_t top (void) const
Padding2D & top (uint32_t value)
uint32_t bottom (void) const
Padding2D & bottom (uint32_t value)
uint32_t left (void) const
Padding2D & left (uint32_t value)
uint32_t right (void) const
Padding2D & right (uint32_t value)
Detailed Description
Definition at line 25 of file Padding2D.h.
Constructor & Destructor Documentation
Padding2D() [1/2]
coco::Padding2D::Padding2D () inline
Definition at line 28 of file Padding2D.h.
              : _top{0}, _bottom{0}, _left{0}, _right{0}
  {
    // DO NOTHING
  }
Padding2D() [2/2]
coco::Padding2D::Padding2D (uint32_t top, uint32_t bottom, uint32_t left, uint32_t right) inline
Definition at line 34 of file Padding2D.h.
    : _top{top}, _bottom{bottom}, _left{left}, _right{right}
  {
    // DO NOTHING
  }
Member Function Documentation
bottom() [1/2]
Padding2D & coco::Padding2D::bottom (uint32_t value)
Definition at line 28 of file Padding2D.cpp.
{
  _bottom = value;
  return (*this);
}
bottom() [2/2]
uint32_t coco::Padding2D::bottom (void) const inline
Definition at line 45 of file Padding2D.h.
{ return _bottom; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and OpPrinter::visit().
left() [1/2]
Padding2D & coco::Padding2D::left (uint32_t value)
Definition at line 34 of file Padding2D.cpp.
{
  _left = value;
  return (*this);
}
left() [2/2]
uint32_t coco::Padding2D::left (void) const inline
Definition at line 49 of file Padding2D.h.
{ return _left; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::get_padding(), enco::output_shape(), and OpPrinter::visit().
right() [1/2]
Padding2D & coco::Padding2D::right (uint32_t value)
Definition at line 40 of file Padding2D.cpp.
{
  _right = value;
  return (*this);
}
right() [2/2]
uint32_t coco::Padding2D::right (void) const inline
Definition at line 53 of file Padding2D.h.
{ return _right; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and OpPrinter::visit().
top() [1/2]
Padding2D & coco::Padding2D::top (uint32_t value)
Definition at line 22 of file Padding2D.cpp.
{
  _top = value;
  return (*this);
}
top() [2/2]
uint32_t coco::Padding2D::top (void) const inline
Definition at line 41 of file Padding2D.h.
{ return _top; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::get_padding(), and OpPrinter::visit().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Padding2D.h
compiler/coco/core/src/IR/Padding2D.cpp