ONE - On-device Neural Engine: onert::backend::gpu_cl::BackendContext Class Reference
onert::backend::gpu_cl::BackendContext Class Reference
#include <BackendContext.h>
Public Member Functions
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< TensorRegistry > tensor_registry=nullptr, std::shared_ptr< TensorBuilder > tensor_builder=nullptr, std::shared_ptr< ConstantInitializer > constant_initializer=nullptr, std::shared_ptr< KernelGenerator > kernel_gen=nullptr)
ITensorRegistry * genTensors () override
FunctionMap genKernels () override
Public Member Functions inherited from onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< TensorBuilder > tensor_builder=nullptr, std::shared_ptr< ConstantInitializer > constant_initializer=nullptr, std::shared_ptr< KernelGenerator > kernel_gen=nullptr)
FunctionMap genKernels () override
Public Member Functions inherited from onert::backend::BackendContext
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~BackendContext ()=default
const Backend * backend () const
const ir::Graph * graph () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
const ContextData & data () const
virtual ITensorRegistry * genTensors ()=0
virtual FunctionMap genKernels ()=0
Protected Member Functions
void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout) override
Protected Member Functions inherited from onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >
void initConsts ()
virtual void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout)=0
void planTensors ()
Additional Inherited Members
Data Fields inherited from onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >
std::shared_ptr< TensorBuilder > tensor_builder
std::shared_ptr< ConstantInitializer > constant_initializer
std::shared_ptr< KernelGenerator > kernel_gen
Data Fields inherited from onert::backend::BackendContext
std::shared_ptr< ITensorRegistry > tensor_registry
Protected Attributes inherited from onert::backend::BackendContext
const Backend * _backend {nullptr}
ContextData _data
Detailed Description
Definition at line 38 of file BackendContext.h.
Constructor & Destructor Documentation
BackendContext()
onert::backend::gpu_cl::BackendContext::BackendContext (const Backend * backend, ContextData && data, std::shared_ptr< TensorRegistry > tensor_registry = nullptr, std::shared_ptr< TensorBuilder > tensor_builder = nullptr, std::shared_ptr< ConstantInitializer > constant_initializer = nullptr, std::shared_ptr< KernelGenerator > kernel_gen = nullptr) inline
Definition at line 43 of file BackendContext.h.
    : onert::backend::cl_common::BackendContext<TensorBuilder, ConstantInitializer,
                                                KernelGenerator>(
        backend, std::move(data), tensor_registry, tensor_builder, constant_initializer, kernel_gen)
  {
    // DO NOTHING
  }
Member Function Documentation
genKernels()
FunctionMap onert::backend::gpu_cl::BackendContext::genKernels () override virtual
Implements onert::backend::BackendContext.
Definition at line 89 of file BackendContext.cc.
{
  FunctionMap fn_map;
  for (auto op_ind : _data.op_order)
  {
    auto fn_seq = kernel_gen->generate(op_ind);
    fn_map.emplace_back(op_ind, std::move(fn_seq));
  }
  kernel_gen->get_operation(fn_map);
  tensor_builder->allocate();
  // NOTE For memory optimization, we want to free some operand data
  const_cast<ir::Graph &>(*_data.graph)
    .operands()
    .iterate([&](const ir::OperandIndex &, ir::Operand &obj) { obj.releaseData(); });
  for (auto &it : fn_map)
  {
    auto &fn_seq = it.second;
    fn_seq->iterate([&](exec::IFunction &ifunc) { ifunc.prepare(); });
  }
  return fn_map;
}
References onert::backend::BackendContext::_data, onert::backend::ContextData::graph, onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >::kernel_gen, onert::backend::ContextData::op_order, onert::exec::IFunction::prepare(), and onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >::tensor_builder.
genTensors()
ITensorRegistry * onert::backend::gpu_cl::BackendContext::genTensors () override virtual
Implements onert::backend::BackendContext.
Definition at line 43 of file BackendContext.cc.
{
  ir::OperandIndexMap<TensorType> type_map;
  for (const auto &ind : graph()->getInputs())
  {
    type_map[ind] = TensorType::TENSOR_TYPE_INPUT;
  }
  for (const auto &ind : graph()->getOutputs())
  {
    type_map[ind] = TensorType::TENSOR_TYPE_OUTPUT;
  }
  graph()->operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &obj) {
    if (external_operands().contains(ind))
      return;
    const auto frontend_layout = graph()->layout();
    const auto backend_layout = operand_layouts().at(ind);
    ir::OperandInfo backend_info{permuteShape(obj.shape(), frontend_layout, backend_layout),
                                 obj.typeInfo(), obj.info().memAllocType(), obj.isConstant()};
    if (obj.isConstant())
    {
      type_map[ind] = TensorType::TENSOR_TYPE_INPUT;
    }
    tensor_builder->registerTensorInfo(ind, backend_info, backend_layout, type_map[ind]);
  });
  // TODO Get compiler options from compiler, and use it rather than getting it from Env
  if (util::getConfigString(util::config::EXECUTOR) == "Linear")
  {
    planTensors();
  }
  else
  {
    // For the executors that does not have fixed linear execution order:
    // To make tensors never be deallocated, this is a workaround to use static memory planner
    graph()->operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &) {
      if (tensor_builder->isRegistered(ind))
        tensor_builder->notifyFirstUse(ind);
    });
  }
  tensor_builder->prepare();
  return tensor_registry.get();
}
References onert::backend::BackendContext::external_operands(), onert::util::getConfigString(), onert::backend::BackendContext::graph(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::Graph::layout(), onert::backend::BackendContext::operand_layouts(), onert::ir::Graph::operands(), onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >::planTensors(), onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >::tensor_builder, onert::backend::BackendContext::tensor_registry, onert::backend::gpu_cl::TENSOR_TYPE_INPUT, and onert::backend::gpu_cl::TENSOR_TYPE_OUTPUT.
registerTensorInfo()
void onert::backend::gpu_cl::BackendContext::registerTensorInfo (const ir::OperandIndex & ind, const ir::OperandInfo & info, ir::Layout backend_layout) override protected virtual
Implements onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >.
Definition at line 36 of file BackendContext.cc.
{
  TensorType type = TensorType::TENSOR_TYPE_VALID;
  tensor_builder->registerTensorInfo(ind, info, backend_layout, type);
}
References info, onert::backend::cl_common::BackendContext< TensorBuilder, ConstantInitializer, KernelGenerator >::tensor_builder, and onert::backend::gpu_cl::TENSOR_TYPE_VALID.
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/BackendContext.h
runtime/onert/backend/gpu_cl/BackendContext.cc