ONE - On-device Neural Engine: moco::onnx::SymbolTable Class Reference
moco::onnx::SymbolTable Class Reference
Class to store relations of Nodes and string names.
#include <GraphBuilderContext.h>
Public Member Functions
void enroll (const std::string &node_name, loco::Node *node)
Registers one node for a name.
loco::Node * node (const std::string &node_name)
Queries enrolled(registered) with name and return node if found Will throw runtime_error if not found Table is independent with registering with list()
void list (loco::Node *node, const std::string &name)
Registers multiple (appends) names for a node Table is independent with registering with enroll()
unsigned size (loco::Node *node)
Returns number of listed(registered) names for a node.
const std::string & name (loco::Node *node, unsigned index)
Queries listed(registered) with node and index(from 0 to size-1) Will throw runtime_error if node is not found or index is out of bounds.
Detailed Description
Class to store relations of Nodes and string names.
Definition at line 34 of file GraphBuilderContext.h.
Member Function Documentation
enroll()
void moco::onnx::SymbolTable::enroll (const std::string & node_name, loco::Node * node)
Registers one node for a name.
Definition at line 24 of file GraphBuilderContext.cpp.
{
  MapNameNode_t::iterator iter = _namenode.find(node_name);
  if (iter != _namenode.end())
  {
    throw std::runtime_error{"Error: Duplicate node name in Graph: " + node_name};
  }
  _namenode[node_name] = node;
}
References node().
Referenced by moco::onnx::Constant_V1::build(), moco::onnx::Constant_V9::build(), and moco::onnx::Identity_V1::build().
list()
void moco::onnx::SymbolTable::list (loco::Node * node, const std::string & name)
Registers multiple (appends) names for a node Table is independent with registering with enroll()
Definition at line 48 of file GraphBuilderContext.cpp.
{
  MapNodeNames_t::iterator iter = _nodenames.find(node);
  if (iter == _nodenames.end())
  {
    // add a new vector for the first name
    _nodenames[node] = {name};
    return;
  }
  _nodenames[node].push_back(name);
}
References name(), and node().
Referenced by moco::onnx::Identity_V1::build().
name()
const std::string & moco::onnx::SymbolTable::name (loco::Node * node, unsigned index)
Queries listed(registered) with node and index(from 0 to size-1) Will throw runtime_error if node is not found or index is out of bounds.
Definition at line 74 of file GraphBuilderContext.cpp.
{
  MapNodeNames_t::iterator iter = _nodenames.find(node);
  if (iter == _nodenames.end())
  {
    throw std::runtime_error{"Error: Cannot find names given node"};
  }
  if (index >= iter->second.size())
  {
    throw std::runtime_error{"Error: Invalid name index for given node"};
  }
  return iter->second.at(index);
}
References moco::index(), and node().
Referenced by list().
node()
loco::Node * moco::onnx::SymbolTable::node (const std::string & node_name)
Queries enrolled(registered) with name and return node if found Will throw runtime_error if not found Table is independent with registering with list()
Definition at line 36 of file GraphBuilderContext.cpp.
{
  MapNameNode_t::iterator iter = _namenode.find(node_name);
  if (iter == _namenode.end())
  {
    throw std::runtime_error{"Error: Cannot find node with name in Graph: " + node_name};
  }
  return iter->second;
}
Referenced by enroll(), list(), name(), and size().
size()
unsigned moco::onnx::SymbolTable::size (loco::Node * node)
Returns number of listed(registered) names for a node.
Definition at line 62 of file GraphBuilderContext.cpp.
{
  MapNodeNames_t::iterator iter = _nodenames.find(node);
  if (iter == _nodenames.end())
  {
    return 0;
  }
  return iter->second.size();
}
References node().
The documentation for this class was generated from the following files:
compiler/oneco/src/GraphBuilderContext.h
compiler/oneco/src/GraphBuilderContext.cpp