ONE - On-device Neural Engine: onert::backend::builtin::UserTensor Class Reference
onert::backend::builtin::UserTensor Class Reference
Tensor object that is for Input and Output tensors from the user.
#include <UserTensor.h>
Public Member Functions
UserTensor (const ir::OperandInfo &info, ir::Layout layout, uint8_t *buffer, size_t size)
UserTensor (const ir::OperandInfo &info, ir::Layout layout)
void setBuffer (uint8_t *buffer, size_t size)
uint8_t * buffer () const override
size_t total_size () const override
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
ir::Shape getShape () const override
Get ir::Shape of tensor.
void setShape (const ir::Shape &new_shape) override
Set the shape of tenser to new_shape.
bool is_constant () const override
Return true if the tensor is constant.
bool applyShape (const ir::Shape &) override
Set the shape to shape and possibly re-allocate the buffer.
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Tensor object that is for Input and Output tensors from the user.
This class is a wrapped buffer that is allocated by the user. So it does not have resposibility on allocation nor deallocation. All the model input/output tensors are wrapped with this class for execution.
Definition at line 38 of file UserTensor.h.
Constructor & Destructor Documentation
UserTensor() [1/2]
onert::backend::builtin::UserTensor::UserTensor (const ir::OperandInfo & info, ir::Layout layout, uint8_t * buffer, size_t size) inline
Definition at line 41 of file UserTensor.h.
    : IPortableTensor{info}, _layout{layout}, _buffer{buffer}, _size{size}, _dynamic{false}
  {
  }
UserTensor() [2/2]
onert::backend::builtin::UserTensor::UserTensor (const ir::OperandInfo & info, ir::Layout layout) inline
Definition at line 46 of file UserTensor.h.
                                                         : UserTensor{info, layout, nullptr, 0}
  {
  }
Member Function Documentation
applyShape()
bool onert::backend::builtin::UserTensor::applyShape (const ir::Shape &) override virtual
Set the shape to shape and possibly re-allocate the buffer.
If a tensor is dynamic tensor and previously allocated memory exists, it will be deallocated. If a tensor is static tensor (with previously allocated memory by StaticTensorManager), buffer() will be overwriten
Parameters
shape tensor's new shape. While allocating memory for this new_shape, tensor's shape is set to new_shape
Returns
true If applying shape is successful
false If not applying shape is not supported (it throws for other errors)
Reimplemented from onert::backend::ITensor.
Definition at line 41 of file UserTensor.cc.
{
  // User tensors cannot be reallocated.
  auto new_size = new_shape.num_elements() * ir::sizeOfDataType(data_type());
  if (total_size() < new_size)
    throw InsufficientBufferSizeException{"User given buffer size is too small."};
  setShape(new_shape);
  return true;
}
References data_type(), setShape(), onert::ir::sizeOfDataType(), and total_size().
buffer()
uint8_t * onert::backend::builtin::UserTensor::buffer () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 58 of file UserTensor.h.
{ return _buffer; }
Referenced by setBuffer().
calcOffset()
size_t onert::backend::builtin::UserTensor::calcOffset (const ir::Coordinates & coords) const override virtual
Implements onert::backend::ITensor.
Definition at line 29 of file UserTensor.cc.
{
  size_t rank = getShape().rank();
  size_t offset = 0;
  for (size_t i = 0; i < rank; ++i)
  {
    offset = offset * getShape().dim(i) + coords[i];
  }
  offset *= sizeOfDataType(data_type());
  return offset;
}
References coords, data_type(), getShape(), and offset().
data_type()
ir::DataType onert::backend::builtin::UserTensor::data_type () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 62 of file UserTensor.h.
{ return _info.typeInfo().type(); }
References onert::backend::IPortableTensor::_info, onert::ir::TypeInfo::type(), and onert::ir::OperandInfo::typeInfo().
Referenced by applyShape(), and calcOffset().
getShape()
ir::Shape onert::backend::builtin::UserTensor::getShape () const inline override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 65 of file UserTensor.h.
{ return _info.shape(); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::shape().
Referenced by calcOffset().
is_constant()
bool onert::backend::builtin::UserTensor::is_constant () const inline override virtual
Return true if the tensor is constant.
Reimplemented from onert::backend::ITensor.
Definition at line 67 of file UserTensor.h.
{ return false; }
is_dynamic()
bool onert::backend::builtin::UserTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 63 of file UserTensor.h.
{ return _dynamic; }
layout()
ir::Layout onert::backend::builtin::UserTensor::layout () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 61 of file UserTensor.h.
{ return _layout; }
set_dynamic()
void onert::backend::builtin::UserTensor::set_dynamic () inline override virtual
set this tensor dynamic
Reimplemented from onert::backend::ITensor.
Definition at line 64 of file UserTensor.h.
{ _dynamic = true; }
setBuffer()
void onert::backend::builtin::UserTensor::setBuffer (uint8_t * buffer, size_t size) inline
Definition at line 51 of file UserTensor.h.
  {
    _buffer = buffer;
    _size = size;
  }
References buffer().
setShape()
void onert::backend::builtin::UserTensor::setShape (const ir::Shape & new_shape) inline override virtual
Set the shape of tenser to new_shape.
Note
Higer dimension will be placed on front.
Reimplemented from onert::backend::ITensor.
Definition at line 66 of file UserTensor.h.
{ _info.shape(new_shape); }
References onert::backend::IPortableTensor::_info, and onert::ir::OperandInfo::shape().
Referenced by applyShape().
total_size()
size_t onert::backend::builtin::UserTensor::total_size () const inline override virtual
Implements onert::backend::ITensor.
Definition at line 59 of file UserTensor.h.
{ return _size; }
Referenced by applyShape().
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/UserTensor.h
runtime/onert/core/src/backend/builtin/UserTensor.cc