ONE - On-device Neural Engine: hermes::Filter Class Reference
hermes::Filter Class Reference final
#include <SourceSetting.h>
Public Member Functions
Filter (int32_t *ptr)
void reject_all (void)
void accept_upto (uint16_t lv)
void accept_all (void)
Detailed Description
Definition at line 26 of file SourceSetting.h.
Constructor & Destructor Documentation
Filter()
hermes::Filter::Filter (int32_t * ptr) inline
Definition at line 29 of file SourceSetting.h.
                       : _ptr{ptr}
  {
    // DO NOTHING
  }
Member Function Documentation
accept_all()
void hermes::Filter::accept_all (void) inline
Definition at line 37 of file SourceSetting.h.
{ *_ptr = 65536; }
Referenced by hermes::SourceSetting::accept_all(), and luci::LoggerConfig::configure().
accept_upto()
void hermes::Filter::accept_upto (uint16_t lv) inline
Definition at line 36 of file SourceSetting.h.
{ *_ptr = static_cast<int32_t>(lv); }
Referenced by luci::LoggerConfig::configure().
reject_all()
void hermes::Filter::reject_all (void) inline
Definition at line 35 of file SourceSetting.h.
{ *_ptr = -1; }
Referenced by luci::LoggerConfig::configure(), and hermes::SourceSetting::reject_all().
The documentation for this class was generated from the following file:
compiler/hermes/include/hermes/core/SourceSetting.h