ONE - On-device Neural Engine: InterpreterWrapper Class Reference
InterpreterWrapper Class Reference
Public Member Functions
InterpreterWrapper (const uint8_t *data, const size_t data_size)
~InterpreterWrapper ()
void interpret (void)
void writeInputTensor (const int input_idx, const void *data, size_t input_size)
void readOutputTensor (const int output_idx, void *output, size_t output_size)
Detailed Description
Definition at line 116 of file CircleInterpreter_cffi.cpp.
Constructor & Destructor Documentation
InterpreterWrapper()
InterpreterWrapper::InterpreterWrapper (const uint8_t * data, const size_t data_size) inline explicit
Definition at line 119 of file CircleInterpreter_cffi.cpp.
  {
    luci::Importer importer;
    _module = importer.importModule(data, data_size);
    if (_module == nullptr)
    {
      throw std::runtime_error{"Cannot import module."};
    }
    _intp = new luci_interpreter::Interpreter(_module.get());
  }
~InterpreterWrapper()
InterpreterWrapper::~InterpreterWrapper () inline
Definition at line 130 of file CircleInterpreter_cffi.cpp.
{ delete _intp; }
Member Function Documentation
interpret()
void InterpreterWrapper::interpret (void) inline
Definition at line 132 of file CircleInterpreter_cffi.cpp.
{ _intp->interpret(); }
References luci_interpreter::Interpreter::interpret().
readOutputTensor()
void InterpreterWrapper::readOutputTensor (const int output_idx, void * output, size_t output_size) inline
Definition at line 149 of file CircleInterpreter_cffi.cpp.
  {
    const auto output_nodes = loco::output_nodes(_module->graph());
    const auto output_node =
      loco::must_cast<const luci::CircleOutput *>(output_nodes.at(output_idx));
    const auto fb_output_size = ::getTensorSize(output_node);
    if (fb_output_size != output_size)
    {
      const auto msg = "Invalid output size: " + std::to_string(fb_output_size) +
                       " != " + std::to_string(output_size);
      throw std::runtime_error(msg);
    }
    _intp->readOutputTensor(output_node, output, fb_output_size);
  }
References loco::must_cast(), loco::output_nodes(), and luci_interpreter::Interpreter::readOutputTensor().
writeInputTensor()
void InterpreterWrapper::writeInputTensor (const int input_idx, const void * data, size_t input_size) inline
Definition at line 134 of file CircleInterpreter_cffi.cpp.
  {
    const auto input_nodes = loco::input_nodes(_module->graph());
    const auto input_node = loco::must_cast<const luci::CircleInput *>(input_nodes.at(input_idx));
    // Input size from model binary
    const auto fb_input_size = ::getTensorSize(input_node);
    if (fb_input_size != input_size)
    {
      const auto msg = "Invalid input size: " + std::to_string(fb_input_size) +
                       " != " + std::to_string(input_size);
      throw std::runtime_error(msg);
    }
    _intp->writeInputTensor(input_node, data, fb_input_size);
  }
References loco::input_nodes(), loco::must_cast(), and luci_interpreter::Interpreter::writeInputTensor().
The documentation for this class was generated from the following file:
compiler/circle-interpreter/src/CircleInterpreter_cffi.cpp