ONE - On-device Neural Engine: flatbuffers::FLATBUFFERS_FINAL_CLASS< T > Class Template Reference
flatbuffers::FLATBUFFERS_FINAL_CLASS< T > Class Template Reference
#include <stl_emulation.h>
Data Structures
struct Options
Public Types
typedef T element_type
typedef T & reference
typedef const T & const_reference
typedef T * pointer
typedef const T * const_pointer
typedef std::size_t size_type
Public Member Functions
~Optional ()
FLATBUFFERS_CONSTEXPR_CPP11 Optional () FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 Optional (nullopt_t) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 Optional (T val) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 Optional (const Optional &other) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP14 Optional & operator= (const Optional &other) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP14 Optional & operator= (nullopt_t) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP14 Optional & operator= (T val) FLATBUFFERS_NOEXCEPT
void reset () FLATBUFFERS_NOEXCEPT
void swap (Optional &other) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 FLATBUFFERS_EXPLICIT_CPP11 operator bool () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 bool has_value () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 const T & operator* () const FLATBUFFERS_NOEXCEPT
const T & value () const
T value_or (T default_value) const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 size_type size () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 size_type size_bytes () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 bool empty () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 pointer data () const FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 reference operator[] (size_type idx) const
FLATBUFFERS_CONSTEXPR_CPP11 span (const span &other) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP14 span & operator= (const span &other) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 span (pointer first, size_type count) FLATBUFFERS_NOEXCEPT
FLATBUFFERS_CONSTEXPR_CPP11 span () FLATBUFFERS_NOEXCEPT
template<typename T >
T GetField (uoffset_t o) const
template<typename T >
T GetStruct (uoffset_t o) const
const uint8_t * GetAddressOf (uoffset_t o) const
uint8_t * GetAddressOf (uoffset_t o)
Verifier (const uint8_t *const buf, const size_t buf_len, const Options &opts)
Verifier (const uint8_t *const buf, const size_t buf_len, const uoffset_t max_depth=64, const uoffset_t max_tables=1000000, const bool check_alignment=true)
bool Check (const bool ok) const
bool Verify (const size_t elem, const size_t elem_len) const
bool VerifyAlignment (const size_t elem, const size_t align) const
template<typename T >
bool Verify (const size_t elem) const
bool VerifyFromPointer (const uint8_t *const p, const size_t len)
bool VerifyFieldStruct (const uint8_t *const base, const voffset_t elem_off, const size_t elem_len, const size_t align) const
template<typename T >
bool VerifyField (const uint8_t *const base, const voffset_t elem_off, const size_t align) const
template<typename T >
bool VerifyTable (const T *const table)
template<int & ..., typename T , typename LenT >
bool VerifyVector (const Vector< T, LenT > *const vec) const
template<int & ..., typename T , typename LenT >
bool VerifyVector (const Vector< const T *, LenT > *const vec) const
bool VerifyString (const String *const str) const
template<typename LenT = uoffset_t>
bool VerifyVectorOrString (const uint8_t *const vec, const size_t elem_size, size_t *const end=nullptr) const
bool VerifyVectorOfStrings (const Vector< Offset< String > > *const vec) const
template<typename T >
bool VerifyVectorOfTables (const Vector< Offset< T > > *const vec)
bool VerifyTableStart (const uint8_t *const table)
template<typename T >
bool VerifyBufferFromStart (const char *const identifier, const size_t start)
template<typename T , int & ..., typename SizeT >
bool VerifyNestedFlatBuffer (const Vector< uint8_t, SizeT > *const buf, const char *const identifier)
template<typename T >
bool VerifyBuffer ()
template<typename T >
bool VerifyBuffer (const char *const identifier)
template<typename T , typename SizeT = uoffset_t>
bool VerifySizePrefixedBuffer (const char *const identifier)
template<typename OffsetT = uoffset_t, typename SOffsetT = soffset_t>
size_t VerifyOffset (const size_t start) const
template<typename OffsetT = uoffset_t>
size_t VerifyOffset (const uint8_t *const base, const voffset_t start) const
bool VerifyComplexity ()
bool EndTable ()
size_t GetComputedSize () const
std::vector< uint8_t > * GetFlexReuseTracker ()
void SetFlexReuseTracker (std::vector< uint8_t > *const rt)
Static Public Attributes
static FLATBUFFERS_CONSTEXPR size_type extent = Extent
Detailed Description
template<class T>
class flatbuffers::FLATBUFFERS_FINAL_CLASS< T >
Definition at line 178 of file stl_emulation.h.
Member Typedef Documentation
const_pointer
template<class T > typedef const T* flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::const_pointer
Definition at line 345 of file stl_emulation.h.
const_reference
template<class T > typedef const T& flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::const_reference
Definition at line 343 of file stl_emulation.h.
element_type
template<class T > typedef T flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::element_type
Definition at line 341 of file stl_emulation.h.
pointer
template<class T > typedef T* flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::pointer
Definition at line 344 of file stl_emulation.h.
reference
template<class T > typedef T& flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::reference
Definition at line 342 of file stl_emulation.h.
size_type
template<class T > typedef std::size_t flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::size_type
Definition at line 346 of file stl_emulation.h.
Constructor & Destructor Documentation
~Optional()
template<class T > flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::~Optional () inline
Definition at line 185 of file stl_emulation.h.
{}
Member Function Documentation
Check()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Check (const bool ok) const inline
Definition at line 62 of file verifier.h.
{
    // clang-format off
    #ifdef FLATBUFFERS_DEBUG_VERIFICATION_FAILURE
       if (opts_.assert) { FLATBUFFERS_ASSERT(ok); }
    #endif
    #ifdef FLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE
      if (!ok)
        upper_bound_ = 0;
    #endif
    // clang-format on
    return ok;
  }
References FLATBUFFERS_ASSERT.
data()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 pointer flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::data () const inline
Definition at line 367 of file stl_emulation.h.
{
    return data_;
  }
empty()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::empty () const inline
Definition at line 362 of file stl_emulation.h.
{
    return size() == 0;
  }
References size.
EndTable()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::EndTable () inline
Definition at line 284 of file verifier.h.
                  {
    depth_--;
    return true;
  }
GetAddressOf() [1/2]
template<class T > uint8_t * flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetAddressOf (uoffset_t o) inline
Definition at line 39 of file struct.h.
{ return &data_[o]; }
GetAddressOf() [2/2]
template<class T > const uint8_t * flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetAddressOf (uoffset_t o) const inline
Definition at line 38 of file struct.h.
{ return &data_[o]; }
GetComputedSize()
template<class T > size_t flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetComputedSize () const inline
Definition at line 290 of file verifier.h.
{
    // clang-format off
    #ifdef FLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE
      uintptr_t size = upper_bound_;
      // Align the size to uoffset_t
      size = (size - 1 + sizeof(uoffset_t)) & ~(sizeof(uoffset_t) - 1);
      return (size > size_) ?  0 : size;
    #else
      // Must turn on FLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE for this to work.
      (void)upper_bound_;
      FLATBUFFERS_ASSERT(false);
      return 0;
    #endif
    // clang-format on
  }
References FLATBUFFERS_ASSERT, and size.
GetField()
template<class T > template<typename T > T flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetField (uoffset_t o) const inline
Definition at line 30 of file struct.h.
{
    return ReadScalar<T>(&data_[o]);
  }
GetFlexReuseTracker()
template<class T > std::vector< uint8_t > * flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetFlexReuseTracker () inline
Definition at line 306 of file verifier.h.
{ return flex_reuse_tracker_; }
GetStruct()
template<class T > template<typename T > T flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::GetStruct (uoffset_t o) const inline
Definition at line 34 of file struct.h.
{
    return reinterpret_cast<T>(&data_[o]);
  }
has_value()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::has_value () const inline
Definition at line 230 of file stl_emulation.h.
{
    return has_value_;
  }
operator bool()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 FLATBUFFERS_EXPLICIT_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator bool () const inline
Definition at line 226 of file stl_emulation.h.
{
    return has_value_;
  }
operator*()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 const T & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator* () const inline
Definition at line 234 of file stl_emulation.h.
{
    return value_;
  }
operator=() [1/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP14 Optional & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator= (const Optional & other) inline
Definition at line 199 of file stl_emulation.h.
{
    value_ = other.value_;
    has_value_ = other.has_value_;
    return *this;
  }
operator=() [2/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP14 span & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator= (const span & other) inline
Definition at line 387 of file stl_emulation.h.
{
    data_ = other.data_;
    count_ = other.count_;
  }
operator=() [3/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP14 Optional & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator= (nullopt_t) inline
Definition at line 205 of file stl_emulation.h.
{
    value_ = T();
    has_value_ = false;
    return *this;
  }
operator=() [4/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP14 Optional & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator= (T val) inline
Definition at line 211 of file stl_emulation.h.
{
    value_ = val;
    has_value_ = true;
    return *this;
  }
operator[]()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 reference flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::operator[] (size_type idx) const inline
Definition at line 380 of file stl_emulation.h.
{
    return data()[idx];
  }
Optional() [1/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Optional () inline
Definition at line 187 of file stl_emulation.h.
    : value_(), has_value_(false) {}
Optional() [2/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Optional (const Optional & other) inline
Definition at line 196 of file stl_emulation.h.
    : value_(other.value_), has_value_(other.has_value_) {}
Optional() [3/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Optional (nullopt_t) inline
Definition at line 190 of file stl_emulation.h.
    : value_(), has_value_(false) {}
Optional() [4/4]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Optional (T val) inline
Definition at line 193 of file stl_emulation.h.
    : value_(val), has_value_(true) {}
reset()
template<class T > void flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::reset () inline
Definition at line 217 of file stl_emulation.h.
{
    *this = nullopt;
  }
SetFlexReuseTracker()
template<class T > void flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::SetFlexReuseTracker (std::vector< uint8_t > *const rt) inline
Definition at line 308 of file verifier.h.
{
    flex_reuse_tracker_ = rt;
  }
size()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 size_type flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::size () const inline
Definition at line 351 of file stl_emulation.h.
{
    return count_;
  }
size_bytes()
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 size_type flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::size_bytes () const inline
Definition at line 357 of file stl_emulation.h.
{
    return size() * sizeof(element_type);
  }
References size.
span() [1/3]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::span () inline
Definition at line 410 of file stl_emulation.h.
                                                          : data_(nullptr),
                                                            count_(0) {
    static_assert(extent == 0 || extent == dynamic_extent, "invalid span");
  }
References flatbuffers::dynamic_extent.
span() [2/3]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::span (const span & other) inline
Definition at line 384 of file stl_emulation.h.
      : data_(other.data_), count_(other.count_) {}
span() [3/3]
template<class T > FLATBUFFERS_CONSTEXPR_CPP11 flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::span (pointer first, size_type count) inline explicit
Definition at line 401 of file stl_emulation.h.
    : data_ (Extent == dynamic_extent ? first : (Extent == count ? first : nullptr)),
      count_(Extent == dynamic_extent ? count : (Extent == count ? Extent : 0)) {
      // Make span empty if the count argument is incompatible with span<T,N>.
  }
References flatbuffers::dynamic_extent.
swap()
template<class T > void flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::swap (Optional & other) inline
Definition at line 221 of file stl_emulation.h.
{
    std::swap(value_, other.value_);
    std::swap(has_value_, other.has_value_);
  }
value()
template<class T > const T & flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::value () const inline
Definition at line 238 of file stl_emulation.h.
{
    FLATBUFFERS_ASSERT(has_value());
    return value_;
  }
References FLATBUFFERS_ASSERT.
value_or()
template<class T > T flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::value_or (T default_value) const inline
Definition at line 243 of file stl_emulation.h.
{
    return has_value() ? value_ : default_value;
  }
Verifier() [1/2]
template<class T > flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Verifier (const uint8_t *const buf, const size_t buf_len, const Options & opts) inline explicit
Definition at line 43 of file verifier.h.
      : buf_(buf), size_(buf_len), opts_(opts) {
    FLATBUFFERS_ASSERT(size_ < opts.max_size);
  }
References FLATBUFFERS_ASSERT, and flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Options::max_size.
Verifier() [2/2]
template<class T > flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Verifier (const uint8_t *const buf, const size_t buf_len, const uoffset_t max_depth = 64, const uoffset_t max_tables = 1000000, const bool check_alignment = true) inline
Definition at line 50 of file verifier.h.
      : Verifier(buf, buf_len, [&] {
          Options opts;
          opts.max_depth = max_depth;
          opts.max_tables = max_tables;
          opts.check_alignment = check_alignment;
          return opts;
        }()) {}
References flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Options::check_alignment, flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Options::max_depth, and flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Options::max_tables.
Verify() [1/2]
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Verify (const size_t elem) const inline
Definition at line 92 of file verifier.h.
{
    return VerifyAlignment(elem, sizeof(T)) && Verify(elem, sizeof(T));
  }
References flatbuffers::Verify().
Verify() [2/2]
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::Verify (const size_t elem, const size_t elem_len) const inline
Definition at line 76 of file verifier.h.
{
    // clang-format off
    #ifdef FLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE
      auto upper_bound = elem + elem_len;
      if (upper_bound_ < upper_bound)
        upper_bound_ =  upper_bound;
    #endif
    // clang-format on
    return Check(elem_len < size_ && elem <= size_ - elem_len);
  }
VerifyAlignment()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyAlignment (const size_t elem, const size_t align) const inline
Definition at line 87 of file verifier.h.
{
    return Check((elem & (align - 1)) == 0 || !opts_.check_alignment);
  }
VerifyBuffer() [1/2]
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyBuffer () inline
Definition at line 240 of file verifier.h.
{ return VerifyBuffer<T>(nullptr); }
VerifyBuffer() [2/2]
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyBuffer (const char *const identifier) inline
Definition at line 242 of file verifier.h.
{
    return VerifyBufferFromStart<T>(identifier, 0);
  }
VerifyBufferFromStart()
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyBufferFromStart (const char *const identifier, const size_t start) inline
Definition at line 199 of file verifier.h.
{
    // Buffers have to be of some size to be valid. The reason it is a runtime
    // check instead of static_assert, is that nested flatbuffers go through
    // this call and their size is determined at runtime.
    if (!Check(size_ >= FLATBUFFERS_MIN_BUFFER_SIZE)) return false;
    // If an identifier is provided, check that we have a buffer
    if (identifier && !Check((size_ >= 2 * sizeof(flatbuffers::uoffset_t) &&
                              BufferHasIdentifier(buf_ + start, identifier)))) {
      return false;
    }
    // Call T::Verify, which must be in the generated code for this type.
    const auto o = VerifyOffset<uoffset_t>(start);
    return Check(o != 0) &&
           reinterpret_cast<const T *>(buf_ + start + o)->Verify(*this)
    // clang-format off
    #ifdef FLATBUFFERS_TRACK_VERIFIER_BUFFER_SIZE
           && GetComputedSize()
    #endif
        ;
    // clang-format on
  }
References flatbuffers::Verify().
VerifyComplexity()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyComplexity () inline
Definition at line 277 of file verifier.h.
{
    depth_++;
    num_tables_++;
    return Check(depth_ <= opts_.max_depth && num_tables_ <= opts_.max_tables);
  }
VerifyField()
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyField (const uint8_t *const base, const voffset_t elem_off, const size_t align) const inline
Definition at line 108 of file verifier.h.
{
    const auto f = static_cast<size_t>(base - buf_) + elem_off;
    return VerifyAlignment(f, align) && Verify(f, sizeof(T));
  }
References flatbuffers::Verify().
VerifyFieldStruct()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyFieldStruct (const uint8_t *const base, const voffset_t elem_off, const size_t elem_len, const size_t align) const inline
Definition at line 101 of file verifier.h.
{
    const auto f = static_cast<size_t>(base - buf_) + elem_off;
    return VerifyAlignment(f, align) && Verify(f, elem_len);
  }
References flatbuffers::Verify().
VerifyFromPointer()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyFromPointer (const uint8_t *const p, const size_t len) inline
Definition at line 96 of file verifier.h.
{
    return Verify(static_cast<size_t>(p - buf_), len);
  }
References p, and flatbuffers::Verify().
VerifyNestedFlatBuffer()
template<class T > template<typename T , int & ..., typename SizeT > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyNestedFlatBuffer (const Vector< uint8_t, SizeT > *const buf, const char *const identifier) inline
Definition at line 224 of file verifier.h.
{
    // Caller opted out of this.
    if (!opts_.check_nested_flatbuffers) return true;
    // An empty buffer is OK as it indicates not present.
    if (!buf) return true;
    // If there is a nested buffer, it must be greater than the min size.
    if (!Check(buf->size() >= FLATBUFFERS_MIN_BUFFER_SIZE)) return false;
    Verifier nested_verifier(buf->data(), buf->size(), opts_);
    return nested_verifier.VerifyBuffer<T>(identifier);
  }
VerifyOffset() [1/2]
template<class T > template<typename OffsetT = uoffset_t, typename SOffsetT = soffset_t> size_t flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyOffset (const size_t start) const inline
Definition at line 256 of file verifier.h.
{
    if (!Verify<OffsetT>(start)) return 0;
    const auto o = ReadScalar<OffsetT>(buf_ + start);
    // May not point to itself.
    if (!Check(o != 0)) return 0;
    // Can't wrap around larger than the max size.
    if (!Check(static_cast<SOffsetT>(o) >= 0)) return 0;
    // Must be inside the buffer to create a pointer from it (pointer outside
    // buffer is UB).
    if (!Verify(start + o, 1)) return 0;
    return o;
  }
References flatbuffers::Verify().
VerifyOffset() [2/2]
template<class T > template<typename OffsetT = uoffset_t> size_t flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyOffset (const uint8_t *const base, const voffset_t start) const inline
Definition at line 270 of file verifier.h.
{
    return VerifyOffset<OffsetT>(static_cast<size_t>(base - buf_) + start);
  }
VerifySizePrefixedBuffer()
template<class T > template<typename T , typename SizeT = uoffset_t> bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifySizePrefixedBuffer (const char *const identifier) inline
Definition at line 247 of file verifier.h.
{
    return Verify<SizeT>(0U) &&
           // Ensure the prefixed size is within the bounds of the provided
           // length.
           Check(ReadScalar<SizeT>(buf_) + sizeof(SizeT) <= size_) &&
           VerifyBufferFromStart<T>(identifier, sizeof(SizeT));
  }
VerifyString()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyString (const String *const str) const inline
Definition at line 133 of file verifier.h.
{
    size_t end;
    return !str || (VerifyVectorOrString<uoffset_t>(
                        reinterpret_cast<const uint8_t *>(str), 1, &end) &&
                    Verify(end, 1) &&           // Must have terminator
                    Check(buf_[end] == '\0'));  // Terminating byte must be 0.
  }
References flatbuffers::Verify().
VerifyTable()
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyTable (const T *const table) inline
Definition at line 115 of file verifier.h.
{
    return !table || table->Verify(*this);
  }
VerifyTableStart()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyTableStart (const uint8_t *const table) inline
Definition at line 181 of file verifier.h.
{
    // Check the vtable offset.
    const auto tableo = static_cast<size_t>(table - buf_);
    if (!Verify<soffset_t>(tableo)) return false;
    // This offset may be signed, but doing the subtraction unsigned always
    // gives the result we want.
    const auto vtableo =
        tableo - static_cast<size_t>(ReadScalar<soffset_t>(table));
    // Check the vtable size field, then check vtable fits in its entirety.
    if (!(VerifyComplexity() && Verify<voffset_t>(vtableo) &&
          VerifyAlignment(ReadScalar<voffset_t>(buf_ + vtableo),
                          sizeof(voffset_t))))
      return false;
    const auto vsize = ReadScalar<voffset_t>(buf_ + vtableo);
    return Check((vsize & 1) == 0) && Verify(vtableo, vsize);
  }
References flatbuffers::Verify().
VerifyVector() [1/2]
template<class T > template<int & ..., typename T , typename LenT > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyVector (const Vector< const T *, LenT > *const vec) const inline
Definition at line 128 of file verifier.h.
{
    return VerifyVector(reinterpret_cast<const Vector<T, LenT> *>(vec));
  }
VerifyVector() [2/2]
template<class T > template<int & ..., typename T , typename LenT > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyVector (const Vector< T, LenT > *const vec) const inline
Definition at line 121 of file verifier.h.
{
    return !vec || VerifyVectorOrString<LenT>(
                       reinterpret_cast<const uint8_t *>(vec), sizeof(T));
  }
VerifyVectorOfStrings()
template<class T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyVectorOfStrings (const Vector< Offset< String > > *const vec) const inline
Definition at line 160 of file verifier.h.
{
    if (vec) {
      for (uoffset_t i = 0; i < vec->size(); i++) {
        if (!VerifyString(vec->Get(i))) return false;
      }
    }
    return true;
  }
VerifyVectorOfTables()
template<class T > template<typename T > bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyVectorOfTables (const Vector< Offset< T > > *const vec) inline
Definition at line 171 of file verifier.h.
{
    if (vec) {
      for (uoffset_t i = 0; i < vec->size(); i++) {
        if (!vec->Get(i)->Verify(*this)) return false;
      }
    }
    return true;
  }
VerifyVectorOrString()
template<class T > template<typename LenT = uoffset_t> bool flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::VerifyVectorOrString (const uint8_t *const vec, const size_t elem_size, size_t *const end = nullptr) const inline
Definition at line 143 of file verifier.h.
{
    const auto vec_offset = static_cast<size_t>(vec - buf_);
    // Check we can read the size field.
    if (!Verify<LenT>(vec_offset)) return false;
    // Check the whole array. If this is a string, the byte past the array must
    // be 0.
    const LenT size = ReadScalar<LenT>(vec);
    const auto max_elems = opts_.max_size / elem_size;
    if (!Check(size < max_elems))
      return false;  // Protect against byte_size overflowing.
    const auto byte_size = sizeof(LenT) + elem_size * size;
    if (end) *end = vec_offset + byte_size;
    return Verify(vec_offset, byte_size);
  }
References size, and flatbuffers::Verify().
Field Documentation
extent
template<class T > FLATBUFFERS_CONSTEXPR size_type flatbuffers::FLATBUFFERS_FINAL_CLASS< T >::extent = Extent static
Definition at line 348 of file stl_emulation.h.
The documentation for this class was generated from the following files:
onert-micro/externals/flatbuffers/stl_emulation.h
onert-micro/externals/flatbuffers/struct.h
onert-micro/externals/flatbuffers/verifier.h