ONE - On-device Neural Engine: nnc::SinkRelu Class Reference
nnc::SinkRelu Class Reference
This pass sinks relu below MaxPooling and Concat nodes.
#include <SinkRelu.h>
Public Member Functions
PassData run (PassData data) override
run compiler pass
std::string getName () override
Public Member Functions inherited from nnc::Pass
virtual PassData run (PassData data)=0
run compiler pass
virtual void cleanup ()
clean compiler pass data
virtual ~Pass ()=default
virtual std::string getName ()
Detailed Description
This pass sinks relu below MaxPooling and Concat nodes.
Definition at line 29 of file SinkRelu.h.
Member Function Documentation
getName()
std::string nnc::SinkRelu::getName () inline override virtual
Reimplemented from nnc::Pass.
Definition at line 34 of file SinkRelu.h.
{ return "SinkRelu"; };
run()
PassData nnc::SinkRelu::run (PassData data) override virtual
run compiler pass
Parameters
data - data that pass is taken
Returns
data that can be passed to the next pass
Exceptions
PassException object if errors occured
Implements nnc::Pass.
Definition at line 33 of file SinkRelu.cpp.
{
  auto g = static_cast<Graph *>(data);
  assert(g);
  GraphPatternMatcher matcher(g);
  auto is_relu = [](const Operation *op) { return op->getType() == Operation::Type::ReLU; };
  auto is_concat = [](const Operation *op) { return op->getType() == Operation::Type::concat; };
  auto is_max_pool = [](const Operation *op) {
    return op->getType() == Operation::Type::maxPool2D;
  };
  std::vector<std::pair<Operation *, Operation *>> matches;
  // sink ReLU through MaxPool
  matches = matcher.matchEdge(is_relu, is_max_pool);
  for (auto pair : matches)
  {
    swapAdjacent(g, pair.first, pair.second);
  }
  // sink ReLU through Concat
  auto matches_v = matcher.matchUpBush(is_relu, is_concat);
  for (const auto &pair : matches_v)
  {
    auto relus = pair.first;
    auto *concat = dynamic_cast<ops::ConcatOp *>(pair.second);
    std::vector<Operation::Output *> pre_relu;
    pre_relu.reserve(relus.size());
    for (auto *r : relus)
    {
      pre_relu.emplace_back(r->getInput(0));
    }
    // create replacement nodes
    auto new_concat = g->create<ops::ConcatOp>(pre_relu, concat->getAxis());
    auto new_relu = g->create<ops::ReluOp>(new_concat->getOutput(0));
    // concat is deleted here
    g->replaceNode(concat, new_relu);
    for (auto r : relus)
    {
      removeNodeIfUnused(g, r);
    }
  }
  return g;
}
References mir::GraphPatternMatcher::matchEdge(), mir::GraphPatternMatcher::matchUpBush(), nnc::opt_util::removeNodeIfUnused(), and nnc::opt_util::swapAdjacent().
The documentation for this class was generated from the following files:
compiler/nnc/include/passes/optimizations/SinkRelu.h
compiler/nnc/passes/optimizations/SinkRelu.cpp