ONE - On-device Neural Engine: luci::CircleConcatenation Class Reference
luci::CircleConcatenation Class Reference final
CONCATENATION in Circle.
#include <CircleConcatenation.h>
Public Member Functions
CircleConcatenation (uint32_t arity)
uint32_t numValues (void) const
Node * values (uint32_t index) const
void values (uint32_t index, Node *node)
int32_t axis (void) const
void axis (int32_t axis)
Public Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::CONCATENATION >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >
loco::Use * at (uint32_t n) const
Detailed Description
CONCATENATION in Circle.
Definition at line 35 of file CircleConcatenation.h.
Constructor & Destructor Documentation
CircleConcatenation()
luci::CircleConcatenation::CircleConcatenation (uint32_t arity) inline
Definition at line 40 of file CircleConcatenation.h.
    : VariadicArityNode<CircleNodeImpl<CircleOpcode::CONCATENATION>>(arity)
  {
    // TODO Support when arity is 0
    assert(arity >= 1);
  }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >::arity().
Member Function Documentation
axis() [1/2]
void luci::CircleConcatenation::axis (int32_t axis) inline
Definition at line 64 of file CircleConcatenation.h.
{ _axis = axis; }
References axis().
Referenced by axis().
axis() [2/2]
int32_t luci::CircleConcatenation::axis (void) const inline
Definition at line 63 of file CircleConcatenation.h.
{ return _axis; }
Referenced by luci::CloneNodeLet< CN::ABC >::visit(), and luci::BuiltinOptionsExtractor::visit().
numValues()
uint32_t luci::CircleConcatenation::numValues (void) const inline
Definition at line 48 of file CircleConcatenation.h.
{ return arity(); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >::arity().
Referenced by values(), values(), and luci::CloneNodeLet< CN::ABC >::visit().
values() [1/2]
Node * luci::CircleConcatenation::values (uint32_t index) const inline
Definition at line 51 of file CircleConcatenation.h.
  {
    assert(index < numValues());
    return at(index)->node();
  }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >::at(), loco::Use::node(), and numValues().
values() [2/2]
void luci::CircleConcatenation::values (uint32_t index, Node * node) inline
Definition at line 56 of file CircleConcatenation.h.
  {
    assert(index < numValues());
    at(index)->node(node);
  }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::CONCATENATION > >::at(), loco::Use::node(), and numValues().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleConcatenation.h