ONE - On-device Neural Engine: luci_interpreter::kernels::Unpack Class Reference
luci_interpreter::kernels::Unpack Class Reference
#include <Unpack.h>
Public Member Functions
Unpack (const Tensor *input, std::vector< Tensor * > outputs, const UnpackParams &params)
const Tensor * input () const
Tensor * output (int index) const
void configure () override
void execute () const override
Unpack (const Tensor *input, std::vector< Tensor * > outputs, const UnpackParams &params)
const Tensor * input () const
Tensor * output (int index) const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< UnpackParams >
const UnpackParams & params () const
const UnpackParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< UnpackParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const UnpackParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const UnpackParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< UnpackParams >
const UnpackParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Unpack.h.
Constructor & Destructor Documentation
Unpack() [1/2]
luci_interpreter::kernels::Unpack::Unpack (const Tensor * input, std::vector< Tensor * > outputs, const UnpackParams & params)
Definition at line 31 of file Unpack.cpp.
  : KernelWithParams<UnpackParams>({input}, std::move(outputs), params)
{
}
References input().
Unpack() [2/2]
luci_interpreter::kernels::Unpack::Unpack (const Tensor * input, std::vector< Tensor * > outputs, const UnpackParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Unpack::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 36 of file Unpack.cpp.
{
  const Shape &input_shape = input()->shape();
  int axis = _params.axis;
  if (axis < 0)
    axis += input()->shape().num_dims();
  assert(axis >= 0 && axis < input_shape.num_dims());
  Shape output_shape(input_shape.num_dims() - 1);
  int out_index = 0;
  for (int in_index = 0; in_index < input_shape.num_dims(); ++in_index)
  {
    if (in_index != axis)
      output_shape.dim(out_index++) = input_shape.dim(in_index);
  }
  for (Tensor *output : _outputs)
  {
    assert(output->element_type() == input()->element_type());
    output->resize(output_shape);
  }
}
References luci_interpreter::Kernel::_outputs, luci_interpreter::KernelWithParams< UnpackParams >::_params, luci_interpreter::UnpackParams::axis, luci_interpreter::Shape::dim(), luci_interpreter::Tensor::element_type(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Unpack::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Unpack::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 70 of file Unpack.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      return executeImpl<float>();
    case DataType::U8:
      return executeImpl<uint8_t>();
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Unpack::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Unpack::input () const inline
Definition at line 33 of file Unpack.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Unpack().
input() [2/2]
const Tensor * luci_interpreter::kernels::Unpack::input () const inline
Definition at line 33 of file Unpack.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Unpack::output (int index) const inline
Definition at line 34 of file Unpack.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Unpack::output (int index) const inline
Definition at line 34 of file Unpack.h.
{ return _outputs[index]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Unpack.h
onert-micro/luci-interpreter/src/kernels/Unpack.h
compiler/luci-interpreter/src/kernels/Unpack.cpp
onert-micro/luci-interpreter/src/kernels/Unpack.cpp