ONE - On-device Neural Engine: onert::backend::train::DisposableTensorIndex Class Reference
onert::backend::train::DisposableTensorIndex Class Reference
Class that is index of DisposableTensor.
#include <DisposableTensorIndex.h>
Public Member Functions
DisposableTensorIndex (const ir::OperationIndex &op_index, const ir::OperandIndex &operand_index)
Construct DisposableTensorIndex object.
const ir::OperationIndex & op_index () const
Get Operation index.
const ir::OperandIndex & operand_index () const
Get operand index.
bool operator== (const DisposableTensorIndex &other) const
operator overloading function for ==
bool operator!= (const DisposableTensorIndex &other) const
operator overloading function for !=
Detailed Description
Class that is index of DisposableTensor.
Definition at line 35 of file DisposableTensorIndex.h.
Constructor & Destructor Documentation
DisposableTensorIndex()
onert::backend::train::DisposableTensorIndex::DisposableTensorIndex (const ir::OperationIndex & op_index, const ir::OperandIndex & operand_index) inline
Construct DisposableTensorIndex object.
Parameters
op_index The operation index
operand_index The operand index
Definition at line 43 of file DisposableTensorIndex.h.
    : _op_index{op_index}, _operand_index{operand_index}
  {
    assert(op_index.valid());
    assert(operand_index.valid());
  }
References op_index(), operand_index(), and onert::util::Index< T, DummyTag >::valid().
Member Function Documentation
op_index()
const ir::OperationIndex & onert::backend::train::DisposableTensorIndex::op_index () const inline
Get Operation index.
Returns
Operation index
Definition at line 56 of file DisposableTensorIndex.h.
{ return _op_index; }
Referenced by DisposableTensorIndex(), and operator==().
operand_index()
const ir::OperandIndex & onert::backend::train::DisposableTensorIndex::operand_index () const inline
Get operand index.
Returns
Operand index
Definition at line 62 of file DisposableTensorIndex.h.
{ return _operand_index; }
Referenced by DisposableTensorIndex(), onert::backend::train::operator<<(), and operator==().
operator!=()
bool onert::backend::train::DisposableTensorIndex::operator!= (const DisposableTensorIndex & other) const inline
operator overloading function for !=
Returns
Whether two DisposableTensorIndex are differenct
Definition at line 79 of file DisposableTensorIndex.h.
{ return !(*this == other); }
operator==()
bool onert::backend::train::DisposableTensorIndex::operator== (const DisposableTensorIndex & other) const inline
operator overloading function for ==
Returns
Whether two DisposableTensorIndex are the same
Definition at line 70 of file DisposableTensorIndex.h.
  {
    return _op_index == other.op_index() && _operand_index == other.operand_index();
  }
References op_index(), and operand_index().
The documentation for this class was generated from the following file:
runtime/onert/backend/train/DisposableTensorIndex.h