ONE - On-device Neural Engine: flatbuffers::grpc::SliceAllocator Class Reference
flatbuffers::grpc::SliceAllocator Class Reference
#include <grpc.h>
Public Member Functions
SliceAllocator ()
SliceAllocator (const SliceAllocator &other)=delete
SliceAllocator & operator= (const SliceAllocator &other)=delete
SliceAllocator (SliceAllocator &&other)
SliceAllocator & operator= (SliceAllocator &&other)
void swap (SliceAllocator &other)
virtual ~SliceAllocator ()
virtual uint8_t * allocate (size_t size) override
virtual void deallocate (uint8_t *p, size_t size) override
virtual uint8_t * reallocate_downward (uint8_t *old_p, size_t old_size, size_t new_size, size_t in_use_back, size_t in_use_front) override
Public Member Functions inherited from flatbuffers::Allocator
virtual ~Allocator ()
Friends
class MessageBuilder
Additional Inherited Members
Protected Member Functions inherited from flatbuffers::Allocator
void memcpy_downward (uint8_t *old_p, size_t old_size, uint8_t *new_p, size_t new_size, size_t in_use_back, size_t in_use_front)
Detailed Description
Definition at line 87 of file grpc.h.
Constructor & Destructor Documentation
SliceAllocator() [1/3]
flatbuffers::grpc::SliceAllocator::SliceAllocator () inline
Definition at line 90 of file grpc.h.
: slice_(grpc_empty_slice()) {}
SliceAllocator() [2/3]
flatbuffers::grpc::SliceAllocator::SliceAllocator (const SliceAllocator & other) delete
SliceAllocator() [3/3]
flatbuffers::grpc::SliceAllocator::SliceAllocator (SliceAllocator && other) inline
Definition at line 95 of file grpc.h.
                                         : slice_(grpc_empty_slice())
  {
    // default-construct and swap idiom
    swap(other);
  }
References swap().
~SliceAllocator()
virtual flatbuffers::grpc::SliceAllocator::~SliceAllocator () inline virtual
Definition at line 115 of file grpc.h.
{ grpc_slice_unref(slice_); }
Member Function Documentation
allocate()
virtual uint8_t * flatbuffers::grpc::SliceAllocator::allocate (size_t size) inline override virtual
Implements flatbuffers::Allocator.
Definition at line 117 of file grpc.h.
  {
    FLATBUFFERS_ASSERT(GRPC_SLICE_IS_EMPTY(slice_));
    slice_ = grpc_slice_malloc(size);
    return GRPC_SLICE_START_PTR(slice_);
  }
References FLATBUFFERS_ASSERT, and size.
deallocate()
virtual void flatbuffers::grpc::SliceAllocator::deallocate (uint8_t * p, size_t size) inline override virtual
Implements flatbuffers::Allocator.
Definition at line 124 of file grpc.h.
  {
    FLATBUFFERS_ASSERT(p == GRPC_SLICE_START_PTR(slice_));
    FLATBUFFERS_ASSERT(size == GRPC_SLICE_LENGTH(slice_));
    grpc_slice_unref(slice_);
    slice_ = grpc_empty_slice();
  }
References FLATBUFFERS_ASSERT, and size.
operator=() [1/2]
SliceAllocator & flatbuffers::grpc::SliceAllocator::operator= (const SliceAllocator & other) delete
operator=() [2/2]
SliceAllocator & flatbuffers::grpc::SliceAllocator::operator= (SliceAllocator && other) inline
Definition at line 101 of file grpc.h.
  {
    // move-construct and swap idiom
    SliceAllocator temp(std::move(other));
    swap(temp);
    return *this;
  }
References swap().
reallocate_downward()
virtual uint8_t * flatbuffers::grpc::SliceAllocator::reallocate_downward (uint8_t * old_p, size_t old_size, size_t new_size, size_t in_use_back, size_t in_use_front) inline override virtual
Reimplemented from flatbuffers::Allocator.
Definition at line 132 of file grpc.h.
  {
    FLATBUFFERS_ASSERT(old_p == GRPC_SLICE_START_PTR(slice_));
    FLATBUFFERS_ASSERT(old_size == GRPC_SLICE_LENGTH(slice_));
    FLATBUFFERS_ASSERT(new_size > old_size);
    grpc_slice old_slice = slice_;
    grpc_slice new_slice = grpc_slice_malloc(new_size);
    uint8_t *new_p = GRPC_SLICE_START_PTR(new_slice);
    memcpy_downward(old_p, old_size, new_p, new_size, in_use_back, in_use_front);
    slice_ = new_slice;
    grpc_slice_unref(old_slice);
    return new_p;
  }
References FLATBUFFERS_ASSERT, and flatbuffers::Allocator::memcpy_downward().
swap()
void flatbuffers::grpc::SliceAllocator::swap (SliceAllocator & other) inline
Definition at line 109 of file grpc.h.
  {
    using std::swap;
    swap(slice_, other.slice_);
  }
References swap().
Referenced by operator=(), SliceAllocator(), and swap().
Friends And Related Symbol Documentation
MessageBuilder
friend class MessageBuilder friend
Definition at line 157 of file grpc.h.
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/grpc.h