ONE - On-device Neural Engine: npud::core::DevManager Class Reference
npud::core::DevManager Class Reference
#include <DevManager.h>
Public Member Functions
DevManager ()
~DevManager ()=default
DevManager (const DevManager &)=delete
DevManager & operator= (const DevManager &)=delete
void loadModules ()
void releaseModules ()
std::shared_ptr< Backend > getBackend ()
int createContext (int deviceId, int priority, NpuContext **npuContext)
int destroyContext (NpuContext *npuContext)
int registerModel (NpuContext *npuContext, const std::string &modelPath, ModelID *modelId)
int unregisterModel (NpuContext *npuContext, ModelID modelId)
int createRequest (NpuContext *npuContext, ModelID modelId, RequestID *requestId)
int destroyRequest (NpuContext *npuContext, RequestID requestId)
Detailed Description
Definition at line 35 of file DevManager.h.
Constructor & Destructor Documentation
DevManager() [1/2]
npud::core::DevManager::DevManager ()
Definition at line 27 of file DevManager.cc.
{
  const auto env = util::getConfigString(util::config::DEVICE_MODULE_PATH);
  _module_dir = std::move(env);
}
References npud::util::getConfigString().
~DevManager()
npud::core::DevManager::~DevManager () default
DevManager() [2/2]
npud::core::DevManager::DevManager (const DevManager &) delete
Member Function Documentation
createContext()
int npud::core::DevManager::createContext (int deviceId, int priority, NpuContext ** npuContext)
Definition at line 99 of file DevManager.cc.
{
  try
  {
    return getBackend()->createContext(deviceId, priority, npuContext);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
createRequest()
int npud::core::DevManager::createRequest (NpuContext * npuContext, ModelID modelId, RequestID * requestId)
Definition at line 152 of file DevManager.cc.
{
  try
  {
    return getBackend()->createRequest(npuContext, modelId, requestId);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
destroyContext()
int npud::core::DevManager::destroyContext (NpuContext * npuContext)
Definition at line 112 of file DevManager.cc.
{
  try
  {
    return getBackend()->destroyContext(npuContext);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
destroyRequest()
int npud::core::DevManager::destroyRequest (NpuContext * npuContext, RequestID requestId)
Definition at line 165 of file DevManager.cc.
{
  try
  {
    return getBackend()->destroyRequest(npuContext, requestId);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
getBackend()
std::shared_ptr< Backend > npud::core::DevManager::getBackend ()
Definition at line 90 of file DevManager.cc.
{
  if (!_dev)
  {
    throw std::runtime_error("No backend device.");
  }
  return _dev->loader->getInstance();
}
Referenced by createContext(), createRequest(), destroyContext(), destroyRequest(), registerModel(), and unregisterModel().
loadModules()
void npud::core::DevManager::loadModules ()
Definition at line 33 of file DevManager.cc.
{
  VERBOSE(DevManager) << "load modules from " << _module_dir << std::endl;
  releaseModules();
  DIR *dir;
  struct dirent *entry;
  // NOTE
  // Return NULL(0) value when opendir or readdir error occurs.
  // NULL should be used instead of nullptr.
  dir = opendir(_module_dir.c_str());
  if (dir == NULL)
  {
    VERBOSE(DevManager) << "Fail to open module directory" << std::endl;
    return;
  }
  while ((entry = readdir(dir)) != NULL)
  {
    std::string modulePath(entry->d_name);
    if (modulePath.find("npud_backend") == std::string::npos)
    {
      continue;
    }
    DynamicLoader *loader = nullptr;
    try
    {
      loader = new DynamicLoader(modulePath.c_str());
    }
    catch (const std::exception &e)
    {
      VERBOSE(DevManager) << e.what() << std::endl;
      continue;
    }
    std::unique_ptr<Device> dev = std::make_unique<Device>();
    dev->modulePath = std::move(modulePath);
    dev->loader = std::unique_ptr<DynamicLoader>(loader);
    _dev = std::move(dev);
    break;
  }
  closedir(dir);
}
References entry(), releaseModules(), and VERBOSE.
operator=()
DevManager & npud::core::DevManager::operator= (const DevManager &) delete
registerModel()
int npud::core::DevManager::registerModel (NpuContext * npuContext, const std::string & modelPath, ModelID * modelId)
Definition at line 125 of file DevManager.cc.
{
  try
  {
    return getBackend()->registerModel(npuContext, modelPath, modelId);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
releaseModules()
void npud::core::DevManager::releaseModules ()
Definition at line 82 of file DevManager.cc.
{
  if (_dev)
  {
    _dev.reset();
  }
}
Referenced by loadModules().
unregisterModel()
int npud::core::DevManager::unregisterModel (NpuContext * npuContext, ModelID modelId)
Definition at line 139 of file DevManager.cc.
{
  try
  {
    return getBackend()->unregisterModel(npuContext, modelId);
  }
  catch (const std::exception &e)
  {
    VERBOSE(DevManager) << e.what() << std::endl;
    return NPU_STATUS_ERROR_OPERATION_FAILED;
  }
}
References getBackend(), npud::core::NPU_STATUS_ERROR_OPERATION_FAILED, and VERBOSE.
The documentation for this class was generated from the following files:
runtime/service/npud/core/DevManager.h
runtime/service/npud/core/DevManager.cc