ONE - On-device Neural Engine: onert::backend::basic::ExternalTensor Class Reference
onert::backend::basic::ExternalTensor Class Reference
Class that uses data from external memory that is not managed by a backend instead of allocating and copying the data. ExternalTensor's data pointer points to an address of memory such as where memory is already allocated, or mmapped area. This is meaning that ExternalTensor can take all of types' ir::Data. To support this, assume below things no padding, always NHWC layout, constant tensor and not dynamic.
#include <Tensor.h>
Public Member Functions
ExternalTensor ()=delete
virtual ~ExternalTensor ()
ExternalTensor (const ir::OperandInfo &info, const ir::Layout layout)
void setData (const std::shared_ptr< ir::Data > data)
set Data to be shared from external so that this ExternalTensor will not be allocated on CPU backend
uint8_t * buffer () const override
bool is_constant () const override
Return true if the tensor is constant.
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
void setShape (const ir::Shape &) override
Set the shape of tenser to new_shape.
void increase_ref () override
void decrease_ref () override
void reset_ref () override
Reset reference count to zero and release data.
int32_t num_references () override
Public Member Functions inherited from onert::backend::basic::Tensor
Tensor ()=delete
virtual ~Tensor ()
Tensor (const ir::OperandInfo &info, const ir::Layout layout, DynamicMemoryManager *dynamic_mem_mgr)
void setBuffer (uint8_t *buffer)
Set the Buffer object. This method is called for static and non-const tensor.
void setBuffer (const std::shared_ptr< Allocator > &alloc)
Set the Buffer object. This method is called for dynamic or const tensor.
void deallocBuffer () override
Reset the buffer and deallocate the allocation if it is managed by itself.
uint8_t * buffer () const override
size_t total_size () const override
Get dimension by index.
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_constant () const override
Return true if the tensor is constant.
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
bool applyShape (const ir::Shape &new_shape) override
Set the shape to shape and possibly re-allocate the buffer.
const ir::Sparsity * sparsity () const override
virtual void increase_ref ()
virtual void decrease_ref ()
virtual void reset_ref ()
Reset reference count to zero and release data.
virtual int32_t num_references ()
void setShape (const ir::Shape &new_shape) override
Set the shape of tenser to new_shape.
ir::Shape getShape () const override
Get ir::Shape of tensor.
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::basic::Tensor
ir::Layout _layout
uint8_t * _buffer
int32_t _num_references
DynamicMemoryManager * _dynamic_mem_mgr
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Class that uses data from external memory that is not managed by a backend instead of allocating and copying the data. ExternalTensor's data pointer points to an address of memory such as where memory is already allocated, or mmapped area. This is meaning that ExternalTensor can take all of types' ir::Data. To support this, assume below things no padding, always NHWC layout, constant tensor and not dynamic.
Definition at line 169 of file Tensor.h.
Constructor & Destructor Documentation
ExternalTensor() [1/2]
onert::backend::basic::ExternalTensor::ExternalTensor () delete
~ExternalTensor()
onert::backend::basic::ExternalTensor::~ExternalTensor () virtual
Definition at line 115 of file Tensor.cc.
{}
ExternalTensor() [2/2]
onert::backend::basic::ExternalTensor::ExternalTensor (const ir::OperandInfo & info, const ir::Layout layout) inline
Definition at line 176 of file Tensor.h.
    : Tensor(info, layout, nullptr)
  {
    assert(_layout == ir::Layout::NHWC);
    assert(_info.isConstant());
    assert(_info.isDynamic() == false);
  }
References onert::backend::IPortableTensor::_info, onert::backend::basic::Tensor::_layout, onert::ir::OperandInfo::isConstant(), onert::ir::OperandInfo::isDynamic(), and onert::ir::NHWC.
Member Function Documentation
buffer()
uint8_t * onert::backend::basic::ExternalTensor::buffer () const inline override virtual
Reimplemented from onert::backend::basic::Tensor.
Definition at line 200 of file Tensor.h.
{ return _buffer; }
References onert::backend::basic::Tensor::_buffer.
decrease_ref()
void onert::backend::basic::ExternalTensor::decrease_ref () inline override virtual
Reimplemented from onert::backend::basic::Tensor.
Definition at line 216 of file Tensor.h.
  {
    assert(_data != nullptr);
    assert(_num_references > 0);
    --_num_references;
    if (_num_references == 0)
    {
      _data.reset();
      _buffer = nullptr;
    }
  }
References onert::backend::basic::Tensor::_buffer, and onert::backend::basic::Tensor::_num_references.
increase_ref()
void onert::backend::basic::ExternalTensor::increase_ref () inline override virtual
Reimplemented from onert::backend::basic::Tensor.
Definition at line 214 of file Tensor.h.
{ ++_num_references; }
References onert::backend::basic::Tensor::_num_references.
is_constant()
bool onert::backend::basic::ExternalTensor::is_constant () const inline override virtual
Return true if the tensor is constant.
Reimplemented from onert::backend::basic::Tensor.
Definition at line 202 of file Tensor.h.
{ return true; }
is_dynamic()
bool onert::backend::basic::ExternalTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Reimplemented from onert::backend::basic::Tensor.
Definition at line 203 of file Tensor.h.
{ return false; }
num_references()
int32_t onert::backend::basic::ExternalTensor::num_references () inline override virtual
Reimplemented from onert::backend::basic::Tensor.
Definition at line 241 of file Tensor.h.
{ return _num_references; }
References onert::backend::basic::Tensor::_num_references.
reset_ref()
void onert::backend::basic::ExternalTensor::reset_ref () inline override virtual
Reset reference count to zero and release data.
Reimplemented from onert::backend::basic::Tensor.
Definition at line 231 of file Tensor.h.
  {
    assert(_data != nullptr);
    assert(_num_references > 0);
    _num_references = 0;
    _data.reset();
    _buffer = nullptr;
  }
References onert::backend::basic::Tensor::_buffer, and onert::backend::basic::Tensor::_num_references.
set_dynamic()
void onert::backend::basic::ExternalTensor::set_dynamic () inline override virtual
set this tensor dynamic
Reimplemented from onert::backend::basic::Tensor.
Definition at line 204 of file Tensor.h.
  {
    throw std::runtime_error("This tensor does not support changing dynamic");
  }
setData()
void onert::backend::basic::ExternalTensor::setData (const std::shared_ptr< ir::Data > data) inline
set Data to be shared from external so that this ExternalTensor will not be allocated on CPU backend
Parameters
[in] data data of Operand to be set
Definition at line 190 of file Tensor.h.
  {
    assert(data != nullptr);
    _data = data;
    // Note. Some op such as cker::Conv could take buffer as nullptr.
    // That's why _buffer also would be used
    _buffer = const_cast<uint8_t *>(_data->base());
  }
References onert::backend::basic::Tensor::_buffer.
Referenced by onert::backend::basic::initConsts().
setShape()
void onert::backend::basic::ExternalTensor::setShape (const ir::Shape & new_shape) inline override virtual
Set the shape of tenser to new_shape.
Note
Higer dimension will be placed on front.
Reimplemented from onert::backend::basic::Tensor.
Definition at line 209 of file Tensor.h.
  {
    throw std::runtime_error("This tensor does not support changing shape");
  }
The documentation for this class was generated from the following files:
runtime/onert/core/include/backend/basic/Tensor.h
runtime/onert/core/src/backend/basic/Tensor.cc