ONE - On-device Neural Engine: loco::AnnotatedItem< Annotation > Class Template Reference
loco::AnnotatedItem< Annotation > Class Template Reference
#include <AnnotatedItem.h>
Public Member Functions
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
template<typename T >
const T * annot (void) const
Retrieve a stored annotation of type T.
template<typename T >
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
template<typename Annotation>
class loco::AnnotatedItem< Annotation >
Definition at line 27 of file AnnotatedItem.h.
Constructor & Destructor Documentation
AnnotatedItem()
template<typename Annotation > loco::AnnotatedItem< Annotation >::AnnotatedItem () default
~AnnotatedItem()
template<typename Annotation > virtual loco::AnnotatedItem< Annotation >::~AnnotatedItem () virtual default
Member Function Documentation
annot() [1/2]
template<typename Annotation > template<typename T > void loco::AnnotatedItem< Annotation >::annot (std::unique_ptr< T > && p) inline
Attach or remove a new annotation of type T.
Note
annot<T>(nullptr) removes an attached annotation if it exists
Definition at line 61 of file AnnotatedItem.h.
  {
    // TODO: Insert static_assert(T derives Annotation);
    if (p == nullptr)
    {
      _attrs.erase(typeid(T));
    }
    else
    {
      // TODO: assert(_attribs.find(typeid(T)) == _attribs.end());
      _attrs[typeid(T)] = std::move(p);
    }
  }
annot() [2/2]
template<typename Annotation > template<typename T > const T * loco::AnnotatedItem< Annotation >::annot (void) const inline
Retrieve a stored annotation of type T.
Note
This method returns nullptr if annotation does not exist
Definition at line 41 of file AnnotatedItem.h.
  {
    // TODO Insert static_assert(T derives Annotation);
    auto it = _attrs.find(typeid(T));
    if (it == _attrs.end())
    {
      return nullptr;
    }
    // TODO Insert null check
    return dynamic_cast<T *>(it->second.get());
  }
Referenced by luci::add_execution_plan(), luci::add_origin(), locomotiv::annot_data(), locomotiv::annot_domain(), loco::ShapeInference::erase(), loco::TypeInference::erase(), locomotiv::erase_annot_data(), locomotiv::erase_annot_domain(), locomotiv::erase_user_data(), loco::ShapeInference::get(), loco::TypeInference::get(), luci::get_execution_plan(), luci::get_node_id(), luci::get_origin(), exo::circle_detail::get_tensor_index(), exo::tflite_detail::get_tensor_index(), luci::get_tensor_index(), luci::has_execution_plan(), luci::has_node_id(), luci::has_origin(), moco::index(), moco::indexed(), loco::ShapeInference::known(), loco::TypeInference::known(), luci::set_node_id(), luci::set_tensor_index(), exo::circle_detail::set_tensor_index(), exo::tflite_detail::set_tensor_index(), loco::ShapeInferenceSession::to(), loco::TypeInferenceSession::to(), and locomotiv::user_data().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/ADT/AnnotatedItem.h