ONE - On-device Neural Engine: mir::ops::TransposeOp Class Reference
mir::ops::TransposeOp Class Reference
Tensor transpose operation.
#include <TransposeOp.h>
Public Member Functions
TransposeOp (Output *arg, const std::vector< std::size_t > &axis_order)
const std::vector< std::size_t > & getAxisOrder () const
Operation * copyWithInputs (const std::vector< Output * > &arg) override
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Tensor transpose operation.
Rearranges axes of input tensor.
Definition at line 33 of file TransposeOp.h.
Constructor & Destructor Documentation
TransposeOp()
mir::ops::TransposeOp::TransposeOp (Output * arg, const std::vector< std::size_t > & axis_order)
Definition at line 24 of file TransposeOp.cpp.
  : Operation(Type::transpose, {arg}), _axis_order(axis_order)
{
  assert(_axis_order.size() == static_cast<std::size_t>(getInputShape(0).rank()));
  inferOutputTypes();
}
Member Function Documentation
copyWithInputs()
Operation * mir::ops::TransposeOp::copyWithInputs (const std::vector< Output * > & arg) inline override virtual
Implements mir::Operation.
Definition at line 40 of file TransposeOp.h.
  {
    return new TransposeOp(arg[0], _axis_order);
  }
getAxisOrder()
const std::vector< std::size_t > & mir::ops::TransposeOp::getAxisOrder () const inline
Definition at line 38 of file TransposeOp.h.
{ return _axis_order; }
Referenced by mir_interpreter::TransposeImpl< T >::run(), mir2loco::Transformer::visit(), nnc::AclCppOpGenerator::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/TransposeOp.h
compiler/mir/src/ops/TransposeOp.cpp