ONE - On-device Neural Engine: fme_apply::InsertScaleShift Class Reference
fme_apply::InsertScaleShift Class Reference
Class to insert scale/shift virtual Ops to loco::Graph.
#include <InsertScaleShift.h>
Public Member Functions
InsertScaleShift (std::vector< EqualizePattern > &patterns)
void run (loco::Graph *graph)
Detailed Description
Class to insert scale/shift virtual Ops to loco::Graph.
Definition at line 30 of file InsertScaleShift.h.
Constructor & Destructor Documentation
InsertScaleShift()
fme_apply::InsertScaleShift::InsertScaleShift (std::vector< EqualizePattern > & patterns) inline
Definition at line 33 of file InsertScaleShift.h.
                                                         : _patterns{patterns}
  {
    // DO NOTHING
  }
Member Function Documentation
run()
void fme_apply::InsertScaleShift::run (loco::Graph * graph)
Definition at line 338 of file InsertScaleShift.cpp.
{
  // Create a map for pattern matching
  // { back(string) -> EqualizationPattern*}
  // This assumes that each EqualizePattern has a unique 'back'
  std::map<std::string, EqualizePattern *> pattern_by_back;
  {
    for (auto &pattern : _patterns)
    {
      auto back = pattern.back;
      pattern_by_back[back] = &pattern;
    }
  }
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    auto cnode = loco::must_cast<luci::CircleNode *>(node);
    if (pattern_by_back.find(cnode->name()) == pattern_by_back.end())
      continue;
    auto pattern = pattern_by_back.at(cnode->name());
    InsertScaleShiftVisitor issv(pattern);
    cnode->accept(&issv);
  }
}
References loco::must_cast(), loco::output_nodes(), and loco::postorder_traversal().
Referenced by fme_apply::FMEqualizer::equalize().
The documentation for this class was generated from the following files:
compiler/fme-apply/src/InsertScaleShift.h
compiler/fme-apply/src/InsertScaleShift.cpp