ONE - On-device Neural Engine: mir::ShapeRange Class Reference
mir::ShapeRange Class Reference
#include <ShapeRange.h>
Public Member Functions
ShapeRange (const Shape &shape)
ShapeRange (Shape &&shape)
ShapeIter begin ()
ShapeIter end ()
bool contains (const Index &idx)
Detailed Description
Definition at line 81 of file ShapeRange.h.
Constructor & Destructor Documentation
ShapeRange() [1/2]
mir::ShapeRange::ShapeRange (const Shape & shape) inline explicit
Definition at line 84 of file ShapeRange.h.
: _shape(shape) {}
ShapeRange() [2/2]
mir::ShapeRange::ShapeRange (Shape && shape) inline explicit
Definition at line 86 of file ShapeRange.h.
: _shape(std::move(shape)) {}
Member Function Documentation
begin()
ShapeIter mir::ShapeRange::begin () inline
Definition at line 88 of file ShapeRange.h.
{ return ShapeIter(_shape, 0); }
Referenced by mir_interpreter::Reshape().
contains()
bool mir::ShapeRange::contains (const Index & idx) inline
Definition at line 92 of file ShapeRange.h.
  {
    assert(idx.rank() == _shape.rank());
    for (int32_t d = 0; d < idx.rank(); ++d)
    {
      if ((idx.at(d) >= _shape.dim(d)) || (idx.at(d) < 0))
        return false;
    }
    return true;
  }
References mir::Index::at(), mir::Shape::dim(), mir::Index::rank(), and mir::Shape::rank().
Referenced by mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), and mir_interpreter::MaxPool2DImpl< T >::run().
end()
ShapeIter mir::ShapeRange::end () inline
Definition at line 90 of file ShapeRange.h.
{ return ShapeIter(_shape, _shape.numElements()); }
References mir::Shape::numElements().
The documentation for this class was generated from the following file:
compiler/mir/include/mir/ShapeRange.h