ONE - On-device Neural Engine: tflimport::GraphBuilderContext Class Reference
tflimport::GraphBuilderContext Class Reference
Class to store context to build IR from tflite.
#include <Context.h>
Public Member Functions
GraphBuilderContext (coco::Module *m, coco::Data *d, coco::Block *block, TensorBags &tensor_bags, TensorContext &tensor_context, TflBufferContext &buffer_context, const tflite::SubGraph *graph)
GraphBuilderContext ()=delete
GraphBuilderContext (const GraphBuilderContext &)=delete
GraphBuilderContext (GraphBuilderContext &&)=delete
coco::Module * m ()
coco::Data * d ()
coco::Block * block ()
TensorContext & tensor ()
TensorBags & bags ()
TflBufferContext & buffer ()
const tflite::SubGraph * graph ()
Detailed Description
Class to store context to build IR from tflite.
Definition at line 132 of file Context.h.
Constructor & Destructor Documentation
GraphBuilderContext() [1/4]
tflimport::GraphBuilderContext::GraphBuilderContext (coco::Module * m, coco::Data * d, coco::Block * block, TensorBags & tensor_bags, TensorContext & tensor_context, TflBufferContext & buffer_context, const tflite::SubGraph * graph) inline explicit
Definition at line 135 of file Context.h.
    : _m(m), _d(d), _block(block), _tensor_bags(tensor_bags), _tensor_context(tensor_context),
      _buffer_context(buffer_context), _graph(graph)
  {
    // DO NOTHING
  }
GraphBuilderContext() [2/4]
tflimport::GraphBuilderContext::GraphBuilderContext () delete
GraphBuilderContext() [3/4]
tflimport::GraphBuilderContext::GraphBuilderContext (const GraphBuilderContext &) delete
GraphBuilderContext() [4/4]
tflimport::GraphBuilderContext::GraphBuilderContext (GraphBuilderContext &&) delete
Member Function Documentation
bags()
TensorBags & tflimport::GraphBuilderContext::bags () inline
Definition at line 153 of file Context.h.
{ return _tensor_bags; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::copy_tensors().
block()
coco::Block * tflimport::GraphBuilderContext::block () inline
Definition at line 151 of file Context.h.
{ return _block; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), and tflimport::DepthwiseConv2DGraphBuilder::build().
buffer()
TflBufferContext & tflimport::GraphBuilderContext::buffer () inline
Definition at line 154 of file Context.h.
{ return _buffer_context; }
Referenced by tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::copy_tensors().
d()
coco::Data * tflimport::GraphBuilderContext::d () inline
Definition at line 150 of file Context.h.
{ return _d; }
Referenced by tflimport::ConcatenationGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::copy_tensors().
graph()
const tflite::SubGraph * tflimport::GraphBuilderContext::graph () inline
Definition at line 155 of file Context.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::copy_tensors(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
m()
coco::Module * tflimport::GraphBuilderContext::m () inline
Definition at line 149 of file Context.h.
{ return _m; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), and tflimport::DepthwiseConv2DGraphBuilder::build().
tensor()
TensorContext & tflimport::GraphBuilderContext::tensor () inline
Definition at line 152 of file Context.h.
{ return _tensor_context; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::copy_tensors().
The documentation for this class was generated from the following file:
compiler/enco/frontend/tflite/src/Context.h