ONE - On-device Neural Engine: nnc::CPPCodeGenerator Class Reference
nnc::CPPCodeGenerator Class Reference final
CPPCodeGenerator implements interfaces that provides BaseCodeGenerator for C++ language This includes header file generation, code file generation and variable renaming according to C++ naming requirements.
#include <CPPGenerator.h>
Public Member Functions
CPPCodeGenerator (std::string output_dir, std::string artifact_name)
void run (mir::Graph *graph)
Method represents base generation sequence: analysis, serialization, header/code generation, etc.
Detailed Description
CPPCodeGenerator implements interfaces that provides BaseCodeGenerator for C++ language This includes header file generation, code file generation and variable renaming according to C++ naming requirements.
Definition at line 47 of file CPPGenerator.h.
Constructor & Destructor Documentation
CPPCodeGenerator()
nnc::CPPCodeGenerator::CPPCodeGenerator (std::string output_dir, std::string artifact_name)
Definition at line 82 of file CPPGenerator.cpp.
  : _output_dir(std::move(output_dir)), _artifact_name(std::move(artifact_name))
{
}
Member Function Documentation
run()
void nnc::CPPCodeGenerator::run (mir::Graph * graph)
Method represents base generation sequence: analysis, serialization, header/code generation, etc.
Parameters
graph MIR graph
Definition at line 110 of file CPPGenerator.cpp.
{
  assert(graph);
  // visit and analyze graph
  ModelAnalyzer ma;
  ma.analyze(graph);
  // serialize parameters
  Serializer serializer;
  serializer.serialize(ma.getInferenceSequence());
  // rename tensors for specific backend language
  formatTensorNames(ma);
  fs::create_directory(_output_dir);
  const string base_path = _output_dir + "/" + _artifact_name;
  const string header_path = base_path + ".h";
  const string code_path = base_path + ".cpp";
  const string params_path = base_path + ".params";
  // Print header
  auto header_stream = getStream(header_path);
  materializeHeader(*header_stream, ma);
  header_stream.reset();
  // Print code
  auto code_stream = getStream(code_path);
  materializeCode(*code_stream, ma, serializer);
  code_stream.reset();
  // Print model parameters
  auto model_stream = getStream(params_path);
  materializeModelParams(*model_stream, serializer);
  model_stream.reset();
}
References nnc::ModelAnalyzer::analyze(), nnc::ModelAnalyzer::getInferenceSequence(), and nnc::Serializer::serialize().
Referenced by TEST().
The documentation for this class was generated from the following files:
compiler/nnc/include/backends/soft_backend/CPPGenerator.h
compiler/nnc/backends/soft_backend/CPPGenerator.cpp