ONE - On-device Neural Engine: tflimport::ReshapeGraphBuilder Class Reference
tflimport::ReshapeGraphBuilder Class Reference
GraphBuilder for Reshape operator.
#include <Reshape.h>
Public Member Functions
void build (const tflite::Operator *op, GraphBuilderContext *) const override
Public Member Functions inherited from tflimport::GraphBuilder
virtual bool validate (const tflite::Operator *) const
virtual void build (const tflite::Operator *op, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Reshape operator.
Definition at line 30 of file Reshape.h.
Member Function Documentation
build()
void tflimport::ReshapeGraphBuilder::build (const tflite::Operator * op, GraphBuilderContext * context) const override virtual
Implements tflimport::GraphBuilder.
Definition at line 37 of file Reshape.cpp.
{
  assert(context != nullptr); // check if init(..) is called
  coco::Module *m = context->m();
  coco::Block *blk = context->block();
  TensorBags &bags = context->bags();
  IndexVector opinputs = as_index_vector(op->inputs());
  IndexVector opoutputs = as_index_vector(op->outputs());
  // these are fixed in tflite
  // input index 0 : input feature
  // input index 1 : output shape (int32_t), (optional or not, is not clear)
  // output index 0 : output feature
  assert(opinputs.size() == 1 || opinputs.size() == 2);
  assert(opoutputs.size() == 1);
  // Note: there are actually 3 places where we can get output shape from
  // current TF lite implementation. From output operand shape, second input,
  // and ReshapeOption (new_shape). Here we use output operand shape
  int ifm_idx = opinputs.at(0);
  int ofm_idx = opoutputs.at(0);
  auto ifm_bag = bags.bag(ifm_idx);
  auto ofm_bag = bags.bag(ofm_idx);
  // TODO: move to InstrBuilder as 'shuffle_elements()'
  // Create a 1:1 shuffle instruction from ifm into ofm
  // Note: Reshape is change of shape information and there is no value change
  // in the bag itself. We implement this as just make a element wise copy of
  // the bag from input to output. So there is no need of 'reshape' operator
  auto shuffle_ins = m->entity()->instr()->create<coco::Shuffle>();
  auto num_elem = ifm_bag->size();
  assert(num_elem == ofm_bag->size());
  shuffle_ins->from(ifm_bag);
  shuffle_ins->into(ofm_bag);
  for (uint32_t n = 0; n < num_elem; ++n)
  {
    const auto from = coco::ElemID(n);
    const auto into = coco::ElemID(n);
    shuffle_ins->insert(from, into);
  }
  // Append the instruction
  blk->instr()->append(shuffle_ins);
}
References coco::DLinkedList< Child, Parent >::Head::append(), tflimport::as_index_vector(), tflimport::TensorBags::bag(), tflimport::GraphBuilderContext::bags(), tflimport::GraphBuilderContext::block(), coco::Block::instr(), tflimport::GraphBuilderContext::m(), m, and coco::Shuffle::size().
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Op/Reshape.h
compiler/enco/frontend/tflite/src/Op/Reshape.cpp