ONE - On-device Neural Engine: onert::backend::train::ops::BinaryArithmeticLayer Class Reference
onert::backend::train::ops::BinaryArithmeticLayer Class Reference
#include <BinaryArithmeticLayer.h>
Public Member Functions
BinaryArithmeticLayer ()
void configure (const IPortableTensor *lhs, const IPortableTensor *rhs, IPortableTensor *output, IPortableTensor *back_prop_lhs, IPortableTensor *back_prop_rhs, const IPortableTensor *back_prop_output, const ir::Activation activation, const ArithmeticType arithmetic_type)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
Public Member Functions inherited from onert::backend::cpu::ops::BinaryArithmeticLayer
BinaryArithmeticLayer ()
void configure (const IPortableTensor *lhs, const IPortableTensor *rhs, IPortableTensor *output, const ir::Activation activation, const ArithmeticType arithmetic_type)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::BinaryArithmeticLayer
const IPortableTensor * _lhs
const IPortableTensor * _rhs
IPortableTensor * _output
std::function< void(const IPortableTensor *, const IPortableTensor *, IPortableTensor *)> _kernel
Detailed Description
Definition at line 43 of file BinaryArithmeticLayer.h.
Constructor & Destructor Documentation
BinaryArithmeticLayer()
onert::backend::train::ops::BinaryArithmeticLayer::BinaryArithmeticLayer ()
Definition at line 36 of file BinaryArithmeticLayer.cc.
  : cpu::ops::BinaryArithmeticLayer(), _back_prop_lhs{nullptr}, _back_prop_rhs{nullptr},
    _back_prop_output{nullptr}, _arithmetic_type{ArithmeticType::kAdd},
    _activation{ir::Activation::NONE}, _act_back_prop_output{nullptr}
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::BinaryArithmeticLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 63 of file BinaryArithmeticLayer.cc.
{
  // Calculate gradient for activation
  if (_back_prop_output->data_type() != OperandType::FLOAT32)
    throw std::runtime_error{"Unsupported Data Type"};
  const IPortableTensor *backprop_act;
  try
  {
    backprop_act =
      backpropActivation(_activation, _output, _back_prop_output, _act_back_prop_output.get());
  }
  catch (const std::exception &e)
  {
    throw std::runtime_error{"train BinaryArithmeticLayer: " + std::string(e.what())};
  }
  assert(backprop_act != nullptr);
  nnfw::cker::train::BinaryArithmeticGrad(
    getShape(_lhs), getBuffer<float>(_lhs), getShape(_rhs), getBuffer<float>(_rhs),
    getShape(backprop_act), getBuffer<float>(backprop_act), getShape(_back_prop_lhs),
    getBuffer<float>(_back_prop_lhs), getShape(_back_prop_rhs), getBuffer<float>(_back_prop_rhs),
    static_cast<nnfw::cker::train::ArithmeticType>(_arithmetic_type));
}
References onert::backend::cpu::ops::BinaryArithmeticLayer::_lhs, onert::backend::cpu::ops::BinaryArithmeticLayer::_output, onert::backend::cpu::ops::BinaryArithmeticLayer::_rhs, onert::backend::train::ops::backpropActivation(), nnfw::cker::train::BinaryArithmeticGrad(), and onert::backend::ITensor::data_type().
configure()
void onert::backend::train::ops::BinaryArithmeticLayer::configure (const IPortableTensor * lhs, const IPortableTensor * rhs, IPortableTensor * output, IPortableTensor * back_prop_lhs, IPortableTensor * back_prop_rhs, const IPortableTensor * back_prop_output, const ir::Activation activation, const ArithmeticType arithmetic_type)
Definition at line 44 of file BinaryArithmeticLayer.cc.
{
  cpu::ops::BinaryArithmeticLayer::configure(
    lhs, rhs, output, activation, static_cast<cpu::ops::ArithmeticType>(arithmetic_type));
  _back_prop_lhs = back_prop_lhs;
  _back_prop_rhs = back_prop_rhs;
  _back_prop_output = back_prop_output;
  _arithmetic_type = arithmetic_type;
  _activation = activation;
}
References onert::backend::cpu::ops::BinaryArithmeticLayer::configure().
forward()
void onert::backend::train::ops::BinaryArithmeticLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 61 of file BinaryArithmeticLayer.cc.
{ cpu::ops::BinaryArithmeticLayer::run(); }
References onert::backend::cpu::ops::BinaryArithmeticLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/BinaryArithmeticLayer.h
runtime/onert/backend/train/ops/BinaryArithmeticLayer.cc