ONE - On-device Neural Engine: loco::CanonicalDialect Class Reference
loco::CanonicalDialect Class Reference final
A singleton for Canonical Dialect.
#include <CanonicalDialect.h>
Public Member Functions
CanonicalDialect (const CanonicalDialect &)=delete
CanonicalDialect (CanonicalDialect &&)=delete
Public Member Functions inherited from loco::Dialect
virtual ~Dialect ()=default
template<typename ConcreteService >
ConcreteService * service (void) const
Static Public Member Functions
static Dialect * get (void)
Additional Inherited Members
Protected Member Functions inherited from loco::Dialect
template<typename ConcreteService >
void service (std::unique_ptr< ConcreteService > &&s)
Detailed Description
A singleton for Canonical Dialect.
CanonicalDialect serves as an in-memory unique identifier.
Definition at line 30 of file CanonicalDialect.h.
Constructor & Destructor Documentation
CanonicalDialect() [1/2]
loco::CanonicalDialect::CanonicalDialect (const CanonicalDialect &) delete
CanonicalDialect() [2/2]
loco::CanonicalDialect::CanonicalDialect (CanonicalDialect &&) delete
Member Function Documentation
get()
Dialect * loco::CanonicalDialect::get (void) static
Definition at line 60 of file CanonicalDialect.cpp.
{
  static CanonicalDialect d;
  return &d;
}
Referenced by locop::CanonicalNodeSummaryBuilder::build(), loco::CanonicalNode::dialect(), loco::CanonicalShapeInferenceRule::infer(), loco::CanonicalTypeInferenceRule::infer(), loco::CanonicalShapeInferenceRule::recognize(), loco::CanonicalTypeInferenceRule::recognize(), logo::RemoveForwardNodePass::run(), logo::SimplifyDomainConversionPass::run(), exo::CanonicalNodeConverter< CanonicalType >::run(), exo::ShapeInferencePass::run(), exo::TypeInferencePass::run(), moco::tf::ShapeInferencePass::run(), and moco::tf::TypeInferencePass::run().
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/CanonicalDialect.h
compiler/loco/src/IR/CanonicalDialect.cpp