ONE - On-device Neural Engine: DepthwiseFilterEncodeLayer::Return Class Reference
DepthwiseFilterEncodeLayer::Return Class Reference
#include <GraphBuilder.h>
Public Member Functions
Return (loco::DepthwiseFilterEncode *node)
Return * perm (const loco::Permutation< loco::Domain::DepthwiseFilter > &perm)
loco::DepthwiseFilterEncode * node (void)
Detailed Description
Definition at line 386 of file GraphBuilder.h.
Constructor & Destructor Documentation
Return()
DepthwiseFilterEncodeLayer::Return::Return (loco::DepthwiseFilterEncode * node) inline
Definition at line 389 of file GraphBuilder.h.
                                            : _node{node}
    {
      // DO NOTHING
    }
Member Function Documentation
node()
loco::DepthwiseFilterEncode * DepthwiseFilterEncodeLayer::Return::node (void) inline
Definition at line 403 of file GraphBuilder.h.
{ return _node; }
perm()
Return * DepthwiseFilterEncodeLayer::Return::perm (const loco::Permutation< loco::Domain::DepthwiseFilter > & perm) inline
Definition at line 395 of file GraphBuilder.h.
    {
      using namespace loco;
      _node->encoder(std::make_unique<PermutingEncoder<Domain::DepthwiseFilter>>(perm));
      return this;
    }
References loco::DepthwiseFilterEncode::encoder(), and perm().
Referenced by perm().
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h