ONE - On-device Neural Engine: mir::Shape Class Reference
mir::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape ()=default
Shape (int32_t rank)
Shape (std::initializer_list< int32_t > &&dims)
Shape (const std::vector< int32_t > &dims)
int32_t rank () const
void resize (int32_t size)
int32_t & dim (int32_t axis) noexcept
int32_t dim (int32_t axis) const noexcept
int32_t numElements () const
bool operator== (const Shape &rhs) const
bool operator!= (const Shape &rhs) const
Static Public Attributes
static constexpr int32_t autoDim = -1
Detailed Description
Definition at line 30 of file Shape.h.
Constructor & Destructor Documentation
Shape() [1/4]
mir::Shape::Shape () default
Shape() [2/4]
mir::Shape::Shape (int32_t rank) inline explicit
Definition at line 37 of file Shape.h.
: _dims(rank) {}
Shape() [3/4]
mir::Shape::Shape (std::initializer_list< int32_t > && dims) inline
Definition at line 39 of file Shape.h.
: _dims(std::move(dims)) {}
Shape() [4/4]
mir::Shape::Shape (const std::vector< int32_t > & dims) inline explicit
Definition at line 41 of file Shape.h.
: _dims(std::begin(dims), std::end(dims)) {}
Member Function Documentation
dim() [1/2]
int32_t mir::Shape::dim (int32_t axis) const inline noexcept
Definition at line 53 of file Shape.h.
  {
    auto dim = wrap_index(axis, _dims.size());
    return _dims[dim];
  }
References dim(), adt::small_vector< T, Capacity >::size(), and mir::wrap_index().
dim() [2/2]
int32_t & mir::Shape::dim (int32_t axis) inline noexcept
Definition at line 47 of file Shape.h.
  {
    auto dim = wrap_index(axis, _dims.size());
    return _dims[dim];
  };
References dim(), adt::small_vector< T, Capacity >::size(), and mir::wrap_index().
Referenced by mir::broadcastShapes(), mir_caffe::CaffeOpCreator::checkReshape(), mir::ShapeRange::contains(), mir_onnx::convertBatchNormalizationV9(), mir_caffe2::Caffe2OpCreator::convertFC(), mir_tflite::TFLiteOpCreator::convertFullyConnected(), mir_tflite::TFLiteOpCreator::convertReshape(), mir_onnx::convertReshapeV1(), mir_tflite::TFLiteOpCreator::convertResizeNearestNeighbor(), mir_tflite::TFLiteOpCreator::convertShape(), mir_tflite::TFLiteOpCreator::convertStridedSlice(), mir_onnx::convertUnsqueezeV1(), mir_onnx::createTensor(), dim(), mir_onnx::fixPads(), nnc::AclCppOpGenerator::genPadStrideInfo(), mir::Tensor< T >::getRegion(), mir_onnx::inferAutoPadding(), numElements(), mir::ShapeIter::operator++(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::SoftmaxImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), mir_interpreter::FullyConnectedImpl< T >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), mir_interpreter::Conv2DImpl< T >::run(), mir_interpreter::Conv2DImpl< uint8_t >::run(), mir_interpreter::DeConv2DImpl< T >::run(), mir_interpreter::shift(), mir::TensorVariant::TensorVariant(), TEST(), mir::toString(), mir::transposeShape(), mir::transposeTensor(), mir2loco::Transformer::visit(), nnc::ModelAnalyzer::visit(), and nnc::AclCppOpGenerator::visit().
numElements()
int32_t Shape::numElements () const
Definition at line 30 of file Shape.cpp.
{
  int32_t res = 1;
  for (int32_t axis = 0; axis < rank(); ++axis)
  {
    assert(dim(axis) != Shape::autoDim);
    res *= dim(axis);
  }
  return res;
}
References dim(), and rank().
Referenced by mir_tflite::TFLiteOpCreator::convertFullyConnected(), mir_onnx::convertReshapeV5(), mir::ShapeRange::end(), mir_interpreter::erase(), and mir::TensorVariant::TensorVariant().
operator!=()
bool mir::Shape::operator!= (const Shape & rhs) const inline
Definition at line 63 of file Shape.h.
{ return !(*this == rhs); }
operator==()
bool mir::Shape::operator== (const Shape & rhs) const inline
Definition at line 61 of file Shape.h.
{ return _dims == rhs._dims; }
rank()
int32_t mir::Shape::rank () const inline
Definition at line 43 of file Shape.h.
{ return static_cast<int32_t>(_dims.size()); }
References adt::small_vector< T, Capacity >::size().
Referenced by mir::broadcastShapes(), mir_caffe::CaffeOpCreator::checkReshape(), mir::ShapeRange::contains(), mir_onnx::convertBatchNormalizationV9(), mir_tflite::TFLiteOpCreator::convertPad(), mir_onnx::convertReshapeV1(), mir_onnx::convertReshapeV5(), mir_tflite::TFLiteOpCreator::convertShape(), mir_tflite::TFLiteOpCreator::convertStridedSlice(), mir_onnx::convertUnsqueezeV1(), nnc::AclCppOpGenerator::genPadStrideInfo(), mir::ops::ConcatOp::getAxis(), mir::ops::SoftmaxOp::getAxis(), mir::TensorVariant::getOffset(), mir::Tensor< T >::getRegion(), numElements(), mir::ShapeIter::operator++(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::TransposeImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), mir_interpreter::FullyConnectedImpl< T >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), mir_interpreter::Conv2DImpl< uint8_t >::run(), mir_interpreter::shift(), mir::TensorVariant::TensorVariant(), mir::toString(), mir::transposeShape(), mir2loco::Transformer::visit(), nnc::Serializer::visit(), and nnc::AclCppOpGenerator::visit().
resize()
void Shape::resize (int32_t size)
Definition at line 28 of file Shape.cpp.
{ _dims.resize(size); }
References adt::small_vector< T, Capacity >::resize().
Field Documentation
autoDim
constexpr int32_t Shape::autoDim = -1 static constexpr
Definition at line 33 of file Shape.h.
The documentation for this class was generated from the following files:
compiler/mir/include/mir/Shape.h
compiler/mir/src/Shape.cpp