ONE - On-device Neural Engine: onert::backend::train::ops::MeanLayer Class Reference
onert::backend::train::ops::MeanLayer Class Reference
#include <MeanLayer.h>
Public Member Functions
MeanLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *axes, IPortableTensor *output, bool keep_dims, IPortableTensor *back_prop_input, const IPortableTensor *back_prop_output)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
Public Member Functions inherited from onert::backend::cpu::ops::MeanLayer
MeanLayer ()
void MeanFloat32 ()
void MeanQuant8 ()
void configure (const IPortableTensor *input, const IPortableTensor *axes, IPortableTensor *output, bool keep_dims)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::MeanLayer
const IPortableTensor * _input
const IPortableTensor * _axes
IPortableTensor * _output
bool _keep_dims
Detailed Description
Definition at line 34 of file MeanLayer.h.
Constructor & Destructor Documentation
MeanLayer()
onert::backend::train::ops::MeanLayer::MeanLayer ()
Definition at line 34 of file MeanLayer.cc.
  : cpu::ops::MeanLayer(), _back_prop_input{nullptr}, _back_prop_output{nullptr}
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::MeanLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 52 of file MeanLayer.cc.
{
  nnfw::cker::Shape keep_dim_shape;
  if (_keep_dims == false)
  {
    keep_dim_shape.ReplaceWith(getShape(_input));
    auto axes_vec = cpu::ops::getReducerAxes(_axes);
    for (const auto &axis : axes_vec)
    {
      keep_dim_shape.SetDim(axis, 1);
    }
  }
  else
  {
    keep_dim_shape.ReplaceWith(getShape(_back_prop_input));
  }
  switch (_back_prop_output->data_type())
  {
    case OperandType::FLOAT32:
    {
      nnfw::cker::train::MeanGrad(keep_dim_shape, getBuffer<float>(_back_prop_output),
                                  getShape(_back_prop_input), getBuffer<float>(_back_prop_input));
      break;
    }
    default:
      throw std::runtime_error("train MeanLayer: unsupported data type");
  }
}
References onert::backend::cpu::ops::MeanLayer::_axes, onert::backend::cpu::ops::MeanLayer::_input, onert::backend::cpu::ops::MeanLayer::_keep_dims, onert::backend::ITensor::data_type(), onert::backend::cpu::ops::getReducerAxes(), nnfw::cker::train::MeanGrad(), nnfw::cker::Shape::ReplaceWith(), and nnfw::cker::Shape::SetDim().
configure()
void onert::backend::train::ops::MeanLayer::configure (const IPortableTensor * input, const IPortableTensor * axes, IPortableTensor * output, bool keep_dims, IPortableTensor * back_prop_input, const IPortableTensor * back_prop_output)
Definition at line 40 of file MeanLayer.cc.
{
  cpu::ops::MeanLayer::configure(input, axes, output, keep_dims);
  _back_prop_input = back_prop_input;
  _back_prop_output = back_prop_output;
}
References onert::backend::cpu::ops::MeanLayer::configure().
forward()
void onert::backend::train::ops::MeanLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 50 of file MeanLayer.cc.
{ cpu::ops::MeanLayer::run(); }
References onert::backend::cpu::ops::MeanLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/MeanLayer.h
runtime/onert/backend/train/ops/MeanLayer.cc