ONE - On-device Neural Engine: nncc::core::ADT::kernel::Buffer< T > Class Template Reference
nncc::core::ADT::kernel::Buffer< T > Class Template Reference final
#include <Buffer.h>
Public Member Functions
Buffer (const Shape &shape, const Layout &layout)
T at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col) const override
T & at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col) override
const Shape & shape (void) const override
virtual const Shape & shape (void) const =0
Public Member Functions inherited from nncc::core::ADT::kernel::Reader< T >
virtual ~Reader ()=default
virtual T at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col) const =0
Public Member Functions inherited from nncc::core::ADT::kernel::Accessor< T >
virtual ~Accessor ()=default
virtual T & at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col)=0
Detailed Description
template<typename T>
class nncc::core::ADT::kernel::Buffer< T >
Definition at line 34 of file Buffer.h.
Constructor & Destructor Documentation
Buffer()
template<typename T > nncc::core::ADT::kernel::Buffer< T >::Buffer (const Shape & shape, const Layout & layout) inline explicit
Definition at line 37 of file Buffer.h.
                                                            : _impl{shape, layout}
  {
    _buffer.resize(num_elements(shape));
  }
References nncc::core::ADT::kernel::Buffer< T >::shape().
Member Function Documentation
at() [1/2]
template<typename T > T nncc::core::ADT::kernel::Buffer< T >::at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col) const inline override virtual
Implements nncc::core::ADT::kernel::Reader< T >.
Definition at line 43 of file Buffer.h.
  {
    return _impl.at(_buffer.begin(), nth, ch, row, col);
  }
Referenced by nnsuite::conv::RandomModel::RandomModel().
at() [2/2]
template<typename T > T & nncc::core::ADT::kernel::Buffer< T >::at (uint32_t nth, uint32_t ch, uint32_t row, uint32_t col) inline override virtual
Implements nncc::core::ADT::kernel::Accessor< T >.
Definition at line 49 of file Buffer.h.
  {
    return _impl.at(_buffer.begin(), nth, ch, row, col);
  }
shape()
template<typename T > const Shape & nncc::core::ADT::kernel::Buffer< T >::shape (void) const inline override virtual
Implements nncc::core::ADT::kernel::View< T >.
Definition at line 55 of file Buffer.h.
{ return _impl.shape(); }
Referenced by nncc::core::ADT::kernel::Buffer< T >::Buffer(), nnsuite::conv::RandomModel::ker_shape(), and nnsuite::conv::RandomModel::RandomModel().
The documentation for this class was generated from the following file:
compiler/angkor/include/nncc/core/ADT/kernel/Buffer.h