ONE - On-device Neural Engine: onert_micro::core::OMBaseContext Class Reference
onert_micro::core::OMBaseContext Class Reference
#include <OMRuntimeData.h>
Public Member Functions
OMBaseContext (const circle::Tensor *tensor)
virtual ~OMBaseContext ()=default
const circle::Tensor * Tensor () const noexcept
const OMRuntimeShape & Shape () const noexcept
const int32_t * Dims () const
size_t DimsCount () const
size_t ShapeFlatSize () const
Protected Attributes
const circle::Tensor * _tensor
OMRuntimeShape _shape
Detailed Description
Definition at line 34 of file OMRuntimeData.h.
Constructor & Destructor Documentation
OMBaseContext()
onert_micro::core::OMBaseContext::OMBaseContext (const circle::Tensor * tensor) inline explicit
Definition at line 41 of file OMRuntimeData.h.
    : _tensor(tensor)
    , _shape(tensor)
  {
    assert(_tensor != nullptr);
  }
References _tensor.
~OMBaseContext()
virtual onert_micro::core::OMBaseContext::~OMBaseContext () virtual default
Member Function Documentation
Dims()
const int32_t * onert_micro::core::OMBaseContext::Dims () const inline
Definition at line 61 of file OMRuntimeData.h.
  {
    return _shape.dimsData();
  }
References _shape, and onert_micro::core::OMRuntimeShape::dimsData().
DimsCount()
size_t onert_micro::core::OMBaseContext::DimsCount () const inline
Definition at line 66 of file OMRuntimeData.h.
  {
    return _shape.dimensionsCount();
  }
References _shape, and onert_micro::core::OMRuntimeShape::dimensionsCount().
Shape()
const OMRuntimeShape & onert_micro::core::OMBaseContext::Shape () const inline noexcept
Definition at line 56 of file OMRuntimeData.h.
  {
    return _shape;
  }
References _shape.
ShapeFlatSize()
size_t onert_micro::core::OMBaseContext::ShapeFlatSize () const inline
Definition at line 71 of file OMRuntimeData.h.
  {
    return _shape.flatSize();
  }
References _shape, and onert_micro::core::OMRuntimeShape::flatSize().
Tensor()
const circle::Tensor * onert_micro::core::OMBaseContext::Tensor () const inline noexcept
Definition at line 51 of file OMRuntimeData.h.
  {
    return _tensor;
  }
References _tensor.
Field Documentation
_shape
OMRuntimeShape onert_micro::core::OMBaseContext::_shape protected
Definition at line 38 of file OMRuntimeData.h.
Referenced by Dims(), DimsCount(), Shape(), and ShapeFlatSize().
_tensor
const circle::Tensor* onert_micro::core::OMBaseContext::_tensor protected
Definition at line 37 of file OMRuntimeData.h.
Referenced by OMBaseContext(), and Tensor().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMRuntimeData.h