ONE - On-device Neural Engine: nest::Module Class Reference
nest::Module Class Reference
#include <Module.h>
Public Member Functions
Module ()=default
VarContext & var (void)
const VarContext & var (void) const
DomainContext & domain (void)
const DomainContext & domain (void) const
const Block & block (void) const
void push (const Expr &expr)
const Ret & ret (void) const
void ret (const Closure &closure)
Detailed Description
Definition at line 28 of file Module.h.
Constructor & Destructor Documentation
Module()
nest::Module::Module () default
Member Function Documentation
block()
const Block & nest::Module::block (void) const inline
Definition at line 51 of file Module.h.
{ return _block; }
Referenced by nest::Schedule::block().
domain() [1/2]
DomainContext & nest::Module::domain (void) inline
Definition at line 44 of file Module.h.
{ return _domain_ctx; }
Referenced by nest::Schedule::domain().
domain() [2/2]
const DomainContext & nest::Module::domain (void) const inline
Definition at line 45 of file Module.h.
{ return _domain_ctx; }
push()
void nest::Module::push (const Expr & expr)
Definition at line 24 of file Module.cpp.
{
  auto stmt = std::make_shared<stmt::PushNode>(expr);
  _block.append(stmt);
}
References nest::Block::append().
ret() [1/2]
void nest::Module::ret (const Closure & closure)
Definition at line 30 of file Module.cpp.
{
  // Only one RET is allowed for each module
  assert(_ret == nullptr);
  _ret = std::make_shared<Ret>(clo.id(), clo.sub());
}
References nest::Closure::id(), and nest::Closure::sub().
ret() [2/2]
const Ret & nest::Module::ret (void) const
Definition at line 37 of file Module.cpp.
{
  // Caller should NOT invoke this method before setting ret
  assert(_ret != nullptr);
  return *_ret;
}
Referenced by nest::Schedule::ret().
var() [1/2]
VarContext & nest::Module::var (void) inline
Definition at line 37 of file Module.h.
{ return _var_ctx; }
Referenced by nest::Schedule::Schedule(), and nest::Schedule::var().
var() [2/2]
const VarContext & nest::Module::var (void) const inline
Definition at line 38 of file Module.h.
{ return _var_ctx; }
The documentation for this class was generated from the following files:
compiler/nest/core/include/nest/Module.h
compiler/nest/core/src/Module.cpp