ONE - On-device Neural Engine: onert::backend::cpu::ops::FusedBatchNormLayer Class Reference
onert::backend::cpu::ops::FusedBatchNormLayer Class Reference
#include <FusedBatchNormLayer.h>
Public Member Functions
FusedBatchNormLayer ()
~FusedBatchNormLayer ()
void fusedbatchnormFloat32 ()
void configure (const std::vector< const IPortableTensor * > &inputs, float epsilon, bool is_training, std::string data_format, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 44 of file FusedBatchNormLayer.h.
Constructor & Destructor Documentation
FusedBatchNormLayer()
onert::backend::cpu::ops::FusedBatchNormLayer::FusedBatchNormLayer ()
Definition at line 30 of file FusedBatchNormLayer.cc.
  : _inputs(), _output(nullptr), _epsilon(0), _is_training(true),
    _fusedbatchnorm_kernel(new nnfw::cker::FusedBatchNorm())
{
  // DO NOTHING
}
~FusedBatchNormLayer()
onert::backend::cpu::ops::FusedBatchNormLayer::~FusedBatchNormLayer () default
Member Function Documentation
configure()
void onert::backend::cpu::ops::FusedBatchNormLayer::configure (const std::vector< const IPortableTensor * > & inputs, float epsilon, bool is_training, std::string data_format, IPortableTensor * output)
Definition at line 76 of file FusedBatchNormLayer.cc.
{
  assert(inputs.size() > 0);
  assert(output != nullptr);
  _inputs = inputs;
  _output = output;
  _epsilon = epsilon;
  _is_training = is_training;
  _data_format = data_format;
}
fusedbatchnormFloat32()
void onert::backend::cpu::ops::FusedBatchNormLayer::fusedbatchnormFloat32 ()
Definition at line 39 of file FusedBatchNormLayer.cc.
{
  uint32_t num_inputs = _inputs.size();
  nnfw::cker::FusedBatchNorm &kernel = *_fusedbatchnorm_kernel;
  kernel.prepare();
  std::vector<nnfw::cker::Shape> inputShapes;
  std::vector<const float *> inputFloatPtrs;
  for (uint32_t i = 0; i < num_inputs; i++)
  {
    inputShapes.emplace_back(getShape(_inputs[i]));
    inputFloatPtrs.emplace_back(getBuffer<float>(_inputs[i]));
  }
  nnfw::cker::FusedBatchNormParams param;
  param.epsilon = _epsilon;
  param.is_training = _is_training;
  param.data_format = _data_format;
  kernel(inputShapes, inputFloatPtrs, getShape(_output), getBuffer<float>(_output), param);
}
References nnfw::cker::FusedBatchNormParams::data_format, nnfw::cker::FusedBatchNormParams::epsilon, onert::backend::cpu::ops::getShape(), nnfw::cker::FusedBatchNormParams::is_training, and nnfw::cker::FusedBatchNorm::prepare().
Referenced by run().
run()
void onert::backend::cpu::ops::FusedBatchNormLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 64 of file FusedBatchNormLayer.cc.
{
  if (_output->data_type() == OperandType::FLOAT32)
  {
    fusedbatchnormFloat32();
  }
  else
  {
    throw std::runtime_error{"FusedBatchNorm: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), and fusedbatchnormFloat32().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/FusedBatchNormLayer.h
runtime/onert/backend/cpu/ops/FusedBatchNormLayer.cc