ONE - On-device Neural Engine: onert_micro::core::OMRuntimeStorage Class Reference
onert_micro::core::OMRuntimeStorage Class Reference
#include <OMRuntimeStorage.h>
Public Member Functions
OMRuntimeStorage ()=default
OMRuntimeStorage (const OMRuntimeStorage &)=delete
OMRuntimeStorage (OMRuntimeStorage &&)=default
OMRuntimeStorage & operator= (const OMRuntimeStorage &)=delete
OMRuntimeStorage && operator= (const OMRuntimeStorage &&)=delete
~OMRuntimeStorage ()=default
std::unordered_map< uint16_t, uint8_t * > & getTensorIndexToData ()
OMStatus saveDataToTensorIndex (uint8_t *data, uint16_t tensor_index)
OMStatus removeTensorFromTensorIndexToData (uint16_t tensor_index)
OMStatus getDataByTensorIndex (uint8_t **data, uint16_t tensor_index)
OMKernelType getKernelType (uint16_t op_index)
OMStatus setKernelType (uint16_t op_index, OMKernelType type)
OMRuntimeShape getDynamicRuntimeShape (uint16_t tensor_index)
OMStatus setDynamicRuntimeShape (uint16_t tensor_index, const OMRuntimeShape &shape)
void clearTensorIndexToData ()
Detailed Description
Definition at line 34 of file OMRuntimeStorage.h.
Constructor & Destructor Documentation
OMRuntimeStorage() [1/3]
onert_micro::core::OMRuntimeStorage::OMRuntimeStorage () default
OMRuntimeStorage() [2/3]
onert_micro::core::OMRuntimeStorage::OMRuntimeStorage (const OMRuntimeStorage &) delete
OMRuntimeStorage() [3/3]
onert_micro::core::OMRuntimeStorage::OMRuntimeStorage (OMRuntimeStorage &&) default
~OMRuntimeStorage()
onert_micro::core::OMRuntimeStorage::~OMRuntimeStorage () default
Member Function Documentation
clearTensorIndexToData()
void onert_micro::core::OMRuntimeStorage::clearTensorIndexToData () inline
Definition at line 90 of file OMRuntimeStorage.h.
{ _tensor_index_to_data.clear(); }
Referenced by onert_micro::core::OMRuntimeGraph::reset().
getDataByTensorIndex()
OMStatus OMRuntimeStorage::getDataByTensorIndex (uint8_t ** data, uint16_t tensor_index)
Definition at line 42 of file OMRuntimeStorage.cpp.
{
  auto tensor_to_data_it = _tensor_index_to_data.find(tensor_index);
  if (tensor_to_data_it != _tensor_index_to_data.end())
    *data = tensor_to_data_it->second;
  else
    *data = nullptr;
  return Ok;
}
References onert_micro::Ok.
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocate(), onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::core::memory::OMRuntimeAllocator::deallocate(), onert_micro::core::train::OMTrainingHandler::evaluateMetric(), onert_micro::execute::OMRuntimeKernel::getDataFromStorage(), onert_micro::core::OMRuntimeGraph::getInputDataAt(), onert_micro::core::OMRuntimeGraph::getOutputDataAt(), and onert_micro::core::train::OMTrainingHandler::handleError().
getDynamicRuntimeShape()
OMRuntimeShape onert_micro::core::OMRuntimeStorage::getDynamicRuntimeShape (uint16_t tensor_index) inline
Definition at line 74 of file OMRuntimeStorage.h.
  {
    auto it = _tensor_index_to_dynamic_tensor_size.find(tensor_index);
    if (it == _tensor_index_to_dynamic_tensor_size.end())
      return {}; // Return empty
    return it->second;
  }
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocate(), onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::core::memory::OMRuntimeAllocator::clearAllTensorsData(), onert_micro::execute::execute_kernel_CircleAdd(), onert_micro::train::optimizers::Adam::handle(), onert_micro::train::optimizers::SGD::handle(), onert_micro::train::optimizers::Adam::updateWeights(), and onert_micro::train::optimizers::SGD::updateWeights().
getKernelType()
OMKernelType onert_micro::core::OMRuntimeStorage::getKernelType (uint16_t op_index) inline
Definition at line 59 of file OMRuntimeStorage.h.
  {
    auto it = _operator_index_to_kernel_type.find(op_index);
    if (it == _operator_index_to_kernel_type.end())
      return Normal;
    return it->second;
  }
References onert_micro::core::Normal.
Referenced by onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), and onert_micro::execute::OMRuntimeKernel::getDataFromStorage().
getTensorIndexToData()
std::unordered_map< uint16_t, uint8_t * > & onert_micro::core::OMRuntimeStorage::getTensorIndexToData () inline
Definition at line 51 of file OMRuntimeStorage.h.
{ return _tensor_index_to_data; }
Referenced by onert_micro::core::memory::OMRuntimeAllocator::clearAllTensorsData(), onert_micro::train::optimizers::Adam::handle(), and onert_micro::train::optimizers::SGD::handle().
operator=() [1/2]
OMRuntimeStorage && onert_micro::core::OMRuntimeStorage::operator= (const OMRuntimeStorage &&) delete
operator=() [2/2]
OMRuntimeStorage & onert_micro::core::OMRuntimeStorage::operator= (const OMRuntimeStorage &) delete
removeTensorFromTensorIndexToData()
OMStatus OMRuntimeStorage::removeTensorFromTensorIndexToData (uint16_t tensor_index)
Definition at line 29 of file OMRuntimeStorage.cpp.
{
  auto tensor_to_data_it = _tensor_index_to_data.find(tensor_index);
  assert(tensor_to_data_it != _tensor_index_to_data.end() && "No data");
  if (tensor_to_data_it == _tensor_index_to_data.end())
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  _tensor_index_to_data.erase(tensor_to_data_it);
  return Ok;
}
References onert_micro::Ok, OM_LOG_AND_RETURN, and onert_micro::UnknownError.
Referenced by onert_micro::core::memory::OMRuntimeAllocator::deallocate(), and onert_micro::execute::OMRuntimeKernel::getDataFromStorage().
saveDataToTensorIndex()
OMStatus OMRuntimeStorage::saveDataToTensorIndex (uint8_t * data, uint16_t tensor_index)
Definition at line 22 of file OMRuntimeStorage.cpp.
{
  _tensor_index_to_data[tensor_index] = data;
  return Ok;
}
References onert_micro::Ok.
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocate(), onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::execute::execute_kernel_CircleGRU(), onert_micro::execute::OMRuntimeKernel::getDataFromStorage(), and onert_micro::core::train::OMTrainingHandler::handleError().
setDynamicRuntimeShape()
OMStatus onert_micro::core::OMRuntimeStorage::setDynamicRuntimeShape (uint16_t tensor_index, const OMRuntimeShape & shape) inline
Definition at line 83 of file OMRuntimeStorage.h.
  {
    _tensor_index_to_dynamic_tensor_size[tensor_index] = shape;
    return Ok;
  }
References onert_micro::Ok.
Referenced by onert_micro::import::configure_kernel_CircleReshape(), and onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig().
setKernelType()
OMStatus onert_micro::core::OMRuntimeStorage::setKernelType (uint16_t op_index, OMKernelType type) inline
Definition at line 68 of file OMRuntimeStorage.h.
  {
    _operator_index_to_kernel_type[op_index] = type;
    return Ok;
  }
References onert_micro::Ok, and type.
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/OMRuntimeStorage.h
onert-micro/onert-micro/src/core/OMRuntimeStorage.cpp