ONE - On-device Neural Engine: tflchef::LoggerConfig Class Reference
tflchef::LoggerConfig Class Reference final
Logger Configuration.
#include <Log.h>
Public Member Functions
LoggerConfig ()
void configure (const hermes::Source *, hermes::Source::Setting &) const final
void configure (const Logger *, hermes::Source::Setting &) const
Public Member Functions inherited from hermes::Config
virtual ~Config ()=default
virtual void configure (const Source *, SourceSetting &) const =0
Detailed Description
Logger Configuration.
Users are able to turn logging on/off via TFLCHEF_LOG environment variable.
Definition at line 40 of file Log.h.
Constructor & Destructor Documentation
LoggerConfig()
tflchef::LoggerConfig::LoggerConfig ()
Definition at line 58 of file Log.cpp.
{
  // Turn on logging if TFLCHEF_LOG is set as non-zero value
  _enabled = safecast<bool>(std::getenv("TFLCHEF_LOG"), false);
}
Member Function Documentation
configure() [1/2]
void tflchef::LoggerConfig::configure (const hermes::Source * source, hermes::Source::Setting & setting) const final virtual
Implements hermes::Config.
Definition at line 64 of file Log.cpp.
{
  // Let's ignore hermes::Sources if that is not a moco logger
  if (auto logger = dynamic_cast<const Logger *>(source))
  {
    configure(logger, setting);
  }
}
References configure().
Referenced by configure().
configure() [2/2]
void tflchef::LoggerConfig::configure (const Logger * , hermes::Source::Setting & setting) const
Definition at line 73 of file Log.cpp.
{
  if (_enabled)
  {
    // Enable all catagories
    setting.accept_all();
  }
  else
  {
    // Disable all catagories
    setting.reject_all();
  }
}
References hermes::SourceSetting::accept_all(), and hermes::SourceSetting::reject_all().
The documentation for this class was generated from the following files:
compiler/tflchef/log/include/Log.h
compiler/tflchef/log/src/Log.cpp