ONE - On-device Neural Engine: exo::MergeConcatNodesPass Class Reference
exo::MergeConcatNodesPass Class Reference
Merge concat nodes whose axis and fusedActivationFunction are same.
#include <MergeConcatNodesPass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Merge TFLConcatenate nodes whose axis and fusedActivationFunction are same.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Merge concat nodes whose axis and fusedActivationFunction are same.
Definition at line 30 of file MergeConcatNodesPass.h.
Member Function Documentation
name()
virtual const char * exo::MergeConcatNodesPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 33 of file MergeConcatNodesPass.h.
{ return "exo::MergeConcatNodesPass"; }
run()
bool exo::MergeConcatNodesPass::run (loco::Graph * graph) virtual
Merge TFLConcatenate nodes whose axis and fusedActivationFunction are same.
[Before] in:0 ----------------------------—\ in:1 -— TFLConcatenation:0 -----— TFLConcatenation:3 — C (axis = 0, NONE) (axis = 0, NONE) in:2 —/ / in:3 -— TFLConcatenation:1 ---—/ (axis = 1, NONE) / in:4 —/ / in:5 -— TFLConcatenation:2 —/ (axis = 0, RELU) in:6 —/
[After] in:0 ----------------------------—\ in:1 -----------------------------— TFLConcatenation:4 — C (axis = 0, NONE) in:2 ----------------------------—/ in:3 -— TFLConcatenation:1 ---—/ (axis = 1, NONE) / in:4 —/ / in:5 -— TFLConcatenation:2 —/ (axis = 0, RELU) in:6 —/
in:1 -— TFLConcatenation:0 -— (axis = 0, NONE) in:2 —/
    ---- TFLConcatenation:3 ----
         (axis = 0, NONE)
Implements logo::Pass.
Definition at line 147 of file MergeConcatNodesPass.cpp.
{
  // Let's enumerate nodes required to compute output nodes
  auto active_nodes = loco::active_nodes(loco::output_nodes(graph));
  // Find TFLConcatenation nodes which have another TFLConcatenation nodes
  // as inputs, with same axis and same fusedActivationFunction
  std::vector<locoex::TFLConcatenation *> candidates;
  for (auto node : active_nodes)
  {
    if (auto concat = dynamic_cast<locoex::TFLConcatenation *>(node))
    {
      for (uint32_t i = 0; i < concat->numValues(); ++i)
      {
        auto input = dynamic_cast<locoex::TFLConcatenation *>(concat->values(i));
        if (input != nullptr && canMerge(input, concat))
        {
          candidates.push_back(concat);
          break;
        }
      }
    }
  }
  // Merge multiple TFLConcatenation nodes as one TFLConcatenation node
  for (auto node : candidates)
  {
    auto inputs = dfs(node);
    auto new_concat = graph->nodes()->create<locoex::TFLConcatenation>(inputs.size());
    new_concat->axis(node->axis());
    new_concat->fusedActivationFunction(node->fusedActivationFunction());
    for (uint32_t i = 0; i < inputs.size(); ++i)
      new_concat->values(i, inputs.at(i));
    loco::replace(node).with(new_concat);
    for (uint32_t i = 0; i < node->numValues(); ++i)
      node->values(i, nullptr);
  }
  return candidates.size() > 0;
}
References loco::active_nodes(), locoex::TFLConcatenation::axis(), loco::output_nodes(), loco::replace(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this class was generated from the following files:
compiler/exo/src/Pass/MergeConcatNodesPass.h
compiler/exo/src/Pass/MergeConcatNodesPass.cpp