ONE - On-device Neural Engine: arm_compute::CLScaleFactorSymm8Kernel Class Reference
arm_compute::CLScaleFactorSymm8Kernel Class Reference
#include <CLScaleFactorSymm8Kernel.h>
Public Member Functions
CLScaleFactorSymm8Kernel ()
CLScaleFactorSymm8Kernel (const CLScaleFactorSymm8Kernel &)=delete
CLScaleFactorSymm8Kernel & operator= (const CLScaleFactorSymm8Kernel &)=delete
CLScaleFactorSymm8Kernel (CLScaleFactorSymm8Kernel &&)=default
CLScaleFactorSymm8Kernel & operator= (CLScaleFactorSymm8Kernel &&)=default
void configure (const ICLTensor *input, ICLTensor *output)
void reset (cl::CommandQueue &queue)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output)
Detailed Description
Interface for the kernel to perform min max search on a 3D tensor.
Definition at line 52 of file CLScaleFactorSymm8Kernel.h.
Constructor & Destructor Documentation
CLScaleFactorSymm8Kernel() [1/3]
CLScaleFactorSymm8Kernel::CLScaleFactorSymm8Kernel ()
Default constructor
Definition at line 107 of file CLScaleFactorSymm8Kernel.cpp.
: _input(nullptr), _output(nullptr) {}
CLScaleFactorSymm8Kernel() [2/3]
arm_compute::CLScaleFactorSymm8Kernel::CLScaleFactorSymm8Kernel (const CLScaleFactorSymm8Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLScaleFactorSymm8Kernel() [3/3]
arm_compute::CLScaleFactorSymm8Kernel::CLScaleFactorSymm8Kernel (CLScaleFactorSymm8Kernel &&) default
Allow instances of this class to be moved
Member Function Documentation
configure()
void CLScaleFactorSymm8Kernel::configure (const ICLTensor * input, ICLTensor * output)
Initialise the kernel's input and output.
Parameters
[in] input Input tensor with 2 dimensions. The first dimension will be interpreted as batches. Data types supported: F32.
[out] output Output tensor with shape [batches] which stores the scale values for each 2D input tensor. The dimensions over the first must match the batched dimensions of the input tensor. Data types supported: F32.
Definition at line 109 of file CLScaleFactorSymm8Kernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(validate_arguments(input->info(), output->info()));
  _input = input;
  _output = output;
  std::set<std::string> build_opts;
  build_opts.emplace("-DWIDTH=" + support::cpp11::to_string(input->info()->dimension(0)));
  // Create kernel
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("scale_factor_symm8", build_opts));
  auto win_config = validate_and_configure_window(input->info(), output->info());
  ARM_COMPUTE_ERROR_THROW_ON(std::get<0>(win_config));
  ICLKernel::configure_internal(std::get<1>(win_config));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
Referenced by arm_compute::CLFullyConnectedHybridLayer::configure().
operator=() [1/2]
CLScaleFactorSymm8Kernel & arm_compute::CLScaleFactorSymm8Kernel::operator= (CLScaleFactorSymm8Kernel &&) default
Allow instances of this class to be moved
References validate().
operator=() [2/2]
CLScaleFactorSymm8Kernel & arm_compute::CLScaleFactorSymm8Kernel::operator= (const CLScaleFactorSymm8Kernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
reset()
void arm_compute::CLScaleFactorSymm8Kernel::reset (cl::CommandQueue & queue)
Resets global minimum and maximum
Parameters
[in,out] queue Command queue on which to map and unmap the min_max tensor
run()
void CLScaleFactorSymm8Kernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 140 of file CLScaleFactorSymm8Kernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
  Window slice = window_collapsed.first_slice_window_2D();
  slice.set(Window::DimX, Window::Dimension(0, 1, 1));
  do
  {
    Window output_slice = slice.shift_dimensions(1);
    unsigned int idx = 0;
    // Set inputs
    add_2D_tensor_argument(idx, _input, slice);
    add_1D_tensor_argument(idx, _output, output_slice);
    enqueue(queue, *this, slice, lws_hint());
  } while (window_collapsed.slide_window_slice_2D(slice));
}
validate()
Status CLScaleFactorSymm8Kernel::validate (const ITensorInfo * input, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLScaleFactorSymm8Kernel
Parameters
[in] input Input tensor info. Data types supported: F32.
[in] output Output tensor info with shape [batches] which stores the scale values for each 2D input tensor. The dimensions over the first must match the batched dimensions of the input tensor. Data types supported: F32.
Returns
a status
Definition at line 131 of file CLScaleFactorSymm8Kernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, output));
  ARM_COMPUTE_RETURN_ON_ERROR(
    std::get<0>(validate_and_configure_window(input->clone().get(), output->clone().get())));
  return Status{};
}
Referenced by operator=(), and arm_compute::CLFullyConnectedHybridLayer::validate().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLScaleFactorSymm8Kernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLScaleFactorSymm8Kernel.cpp