ONE - On-device Neural Engine: fme_apply::FusePostScalePass Class Reference
fme_apply::FusePostScalePass Class Reference
Pass to fuse CircleCustom(PostScale) to succeeding Ops.
#include <FusePostScalePass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to fuse CircleCustom(PostScale) to succeeding Ops.
BEFORE
    [Node]
      |
  [PostScale]
AFTER
   [Node'] (Weights are updated)
Definition at line 41 of file FusePostScalePass.h.
Member Function Documentation
name()
virtual const char * fme_apply::FusePostScalePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 44 of file FusePostScalePass.h.
{ return "fme::FusePostScalePass"; }
run()
bool fme_apply::FusePostScalePass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 507 of file FusePostScalePass.cpp.
{
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    FusePostScale fps;
    auto cnode = loco::must_cast<luci::CircleNode *>(node);
    if (cnode->accept(&fps))
      changed = true;
  }
  return changed;
}
References loco::active_nodes(), loco::must_cast(), and loco::output_nodes().
The documentation for this class was generated from the following files:
compiler/fme-apply/src/pass/FusePostScalePass.h
compiler/fme-apply/src/pass/FusePostScalePass.cpp