ONE - On-device Neural Engine: tflchef::TFliteImport Class Reference
tflchef::TFliteImport Class Reference
Loads TF lite file and provides helpers to access attributes.
#include <TFliteImport.h>
Public Member Functions
TFliteImport (const tflite::Model *model)
TFliteImport ()=delete
bool select_sub_graph (uint32_t subgraph)
const TFliteBuffers_t * buffers ()
const TFliteTensors_t * tensors ()
const TFliteOperators_t * operators ()
const std::vector< int32_t > & inputs () const
const std::vector< int32_t > & outputs () const
uint32_t num_subgraph () const
tflite::BuiltinOperator builtin_code (const tflite::Operator *op) const
std::string opcode_name (const tflite::Operator *op) const
size_t buffer_info (const tflite::Tensor *tensor, const uint8_t **buff_data)
Public Member Functions inherited from souschef::TensorFiller
virtual ~TensorFiller ()=default
void set_tensor_filler (uint32_t tensor_index)
This will record the tensor by index, if it needs filler option, such as kernel, bias.
void set_tensor_filler (uint32_t tensor_index, std::vector< int32_t > &expvalues)
This will store int32 filler values such as reshape information for the tensor.
void set_tensor_filler (uint32_t tensor_index, std::vector< float > &expvalues)
bool get_tensor_filler (uint32_t tensor_index)
This will return true if the tensor by index, needs a filler option.
bool get_tensor_filler (uint32_t tensor_index, std::vector< int32_t > &expvalues)
This will return true if the tensor by index, needs a int array filler option.
bool get_tensor_filler (uint32_t tensor_index, std::vector< float > &expvalues)
Detailed Description
Loads TF lite file and provides helpers to access attributes.
Definition at line 40 of file TFliteImport.h.
Constructor & Destructor Documentation
TFliteImport() [1/2]
tflchef::TFliteImport::TFliteImport (const tflite::Model * model)
Definition at line 28 of file TFliteImport.cpp.
{
  _subgraphs = model->subgraphs();
  _buffers = model->buffers();
  auto opcodes = model->operator_codes();
  for (const ::tflite::OperatorCode *opcode : *opcodes)
  {
    _op_codes.push_back(opcode);
  }
}
TFliteImport() [2/2]
tflchef::TFliteImport::TFliteImport () delete
Member Function Documentation
buffer_info()
size_t tflchef::TFliteImport::buffer_info (const tflite::Tensor * tensor, const uint8_t ** buff_data)
Definition at line 98 of file TFliteImport.cpp.
{
  *buff_data = nullptr;
  if (tensor->buffer() == 0)
    return 0;
  if (auto *buffer = (*_buffers)[tensor->buffer()])
  {
    if (auto *array = buffer->data())
    {
      if (size_t size = array->size())
      {
        *buff_data = reinterpret_cast<const uint8_t *>(array->data());
        return size;
      }
    }
  }
  return 0;
}
buffers()
const TFliteBuffers_t * tflchef::TFliteImport::buffers () inline
Definition at line 51 of file TFliteImport.h.
{ return _buffers; }
Referenced by tflchef::generate_recipe().
builtin_code()
tflite::BuiltinOperator tflchef::TFliteImport::builtin_code (const tflite::Operator * op) const
Definition at line 64 of file TFliteImport.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  return mio::tflite::builtin_code_neutral(opcode);
}
References mio::tflite::builtin_code_neutral().
Referenced by tflchef::generate_recipe().
inputs()
const std::vector< int32_t > & tflchef::TFliteImport::inputs () const inline
Definition at line 54 of file TFliteImport.h.
{ return _inputs; }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs(), and tflchef::generate_recipe().
num_subgraph()
uint32_t tflchef::TFliteImport::num_subgraph () const inline
Definition at line 57 of file TFliteImport.h.
{ return _subgraphs->Length(); }
Referenced by tflchef::generate_recipe().
opcode_name()
std::string tflchef::TFliteImport::opcode_name (const tflite::Operator * op) const
Definition at line 73 of file TFliteImport.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  if (!mio::tflite::is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  if (mio::tflite::is_custom(opcode))
  {
    if (!opcode->custom_code())
      return "(invalid custom)";
    return opcode->custom_code()->c_str();
  }
  tflite::BuiltinOperator code = mio::tflite::builtin_code_neutral(opcode);
  return EnumNameBuiltinOperator(code);
}
References mio::tflite::builtin_code_neutral(), mio::tflite::is_custom(), and mio::tflite::is_valid().
Referenced by tflchef::generate_recipe().
operators()
const TFliteOperators_t * tflchef::TFliteImport::operators () inline
Definition at line 53 of file TFliteImport.h.
{ return _operators; }
Referenced by tflchef::generate_recipe().
outputs()
const std::vector< int32_t > & tflchef::TFliteImport::outputs () const inline
Definition at line 55 of file TFliteImport.h.
{ return _outputs; }
Referenced by tflchef::generate_recipe(), and validate_onnx2circle.OnnxRunner::get_outputs().
select_sub_graph()
bool tflchef::TFliteImport::select_sub_graph (uint32_t subgraph)
Definition at line 40 of file TFliteImport.cpp.
{
  _tensors = nullptr;
  _operators = nullptr;
  _inputs.clear();
  _outputs.clear();
  if (_subgraphs->Length() <= sgindex)
  {
    assert(false);
    return false;
  }
  const tflite::SubGraph *subgraph = (*_subgraphs)[sgindex];
  _tensors = subgraph->tensors();
  _operators = subgraph->operators();
  _inputs = as_index_vector(subgraph->inputs());
  _outputs = as_index_vector(subgraph->outputs());
  return true;
}
References tflchef::as_index_vector().
Referenced by tflchef::generate_recipe().
tensors()
const TFliteTensors_t * tflchef::TFliteImport::tensors () inline
Definition at line 52 of file TFliteImport.h.
{ return _tensors; }
Referenced by tflchef::generate_recipe().
The documentation for this class was generated from the following files:
compiler/tflchef/tflite/src/TFliteImport.h
compiler/tflchef/tflite/src/TFliteImport.cpp