ONE - On-device Neural Engine: loco::MultiDialectShapeInferenceRule Class Reference
loco::MultiDialectShapeInferenceRule Class Reference final
Shape inference rule for multiple dialects.
#include <MultiDialectShapeInferenceRule.h>
Public Member Functions
bool recognize (const Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const Node *, NodeShape &) const final
Infer node's shape.
MultiDialectShapeInferenceRule & bind (const Dialect *d, const ShapeInferenceRule *rule)
Bind a specific rule to a Dialect.
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Shape inference rule for multiple dialects.
Definition at line 30 of file MultiDialectShapeInferenceRule.h.
Member Function Documentation
bind()
MultiDialectShapeInferenceRule & loco::MultiDialectShapeInferenceRule::bind (const Dialect * d, const ShapeInferenceRule * rule)
Bind a specific rule to a Dialect.
Definition at line 56 of file MultiDialectShapeInferenceRule.cpp.
{
  assert(_rules.find(d) == _rules.end());
  assert(rule->recognize(d));
  _rules[d] = rule;
  return (*this);
}
References loco::ShapeInferenceRule::recognize().
Referenced by exo::ShapeInferencePass::run(), and moco::tf::ShapeInferencePass::run().
infer()
bool loco::MultiDialectShapeInferenceRule::infer (const Node * , NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 42 of file MultiDialectShapeInferenceRule.cpp.
{
  const auto found = _rules.find(node->dialect());
  if (found == _rules.cend())
    return false;
  auto rule = found->second;
  if (rule->infer(node, shape))
    return true;
  return false;
}
References loco::Node::dialect().
recognize()
bool loco::MultiDialectShapeInferenceRule::recognize (const Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 29 of file MultiDialectShapeInferenceRule.cpp.
{
  const auto found = _rules.find(d);
  if (found == _rules.cend())
    return false;
  auto rule = found->second;
  auto result = rule->recognize(d);
  return result;
}
The documentation for this class was generated from the following files:
compiler/loco/include/loco/Service/MultiDialectShapeInferenceRule.h
compiler/loco/src/Service/MultiDialectShapeInferenceRule.cpp