ONE - On-device Neural Engine: luci_interpreter::kernels::Gelu Class Reference
luci_interpreter::kernels::Gelu Class Reference
#include <Gelu.h>
Public Member Functions
Gelu (const Tensor *input, Tensor *output, const GeluParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< GeluParams >
const GeluParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< GeluParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const GeluParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< GeluParams >
const GeluParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file Gelu.h.
Constructor & Destructor Documentation
Gelu()
luci_interpreter::kernels::Gelu::Gelu (const Tensor * input, Tensor * output, const GeluParams & params)
Definition at line 31 of file Gelu.cpp.
  : KernelWithParams<GeluParams>({input}, {output}, params)
{
}
References input().
Member Function Documentation
configure()
void luci_interpreter::kernels::Gelu::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 36 of file Gelu.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
execute()
void luci_interpreter::kernels::Gelu::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 43 of file Gelu.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("luci-intp Gelu Unsupported type.");
  }
}
References input().
input()
const Tensor * luci_interpreter::kernels::Gelu::input () const inline
Definition at line 33 of file Gelu.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Gelu().
output()
Tensor * luci_interpreter::kernels::Gelu::output () const inline
Definition at line 34 of file Gelu.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Gelu.h
compiler/luci-interpreter/src/kernels/Gelu.cpp