ONE - On-device Neural Engine: nnfw::tflite::TensorView< T > Class Template Reference
nnfw::tflite::TensorView< T > Class Template Reference final
Class to define TensorView which is inherited from nnfw::misc::tensor::Reader<T> class.
#include <TensorView.h>
Public Member Functions
TensorView (const nnfw::misc::tensor::Shape &shape, T *base)
Construct a TensorView object with base and shape informations.
const nnfw::misc::tensor::Shape & shape (void) const
Get shape of tensor.
T at (const nnfw::misc::tensor::Index &index) const override
Get value of tensor index.
T & at (const nnfw::misc::tensor::Index &index)
Get reference value of tensor index.
Public Member Functions inherited from nnfw::misc::tensor::Reader< T >
virtual ~Reader ()=default
Destroy the Reader object.
virtual T at (const Index &index) const =0
Get an element of tensor.
Static Public Member Functions
static TensorView< T > make (const TfLiteTensor *tensor)
Create TensorView object using given parameters.
Data Fields
T * _base
nnfw::misc::tensor::NonIncreasingStride _stride
Detailed Description
template<typename T>
class nnfw::tflite::TensorView< T >
Class to define TensorView which is inherited from nnfw::misc::tensor::Reader<T> class.
Definition at line 41 of file TensorView.h.
Constructor & Destructor Documentation
TensorView()
template<typename T > nnfw::tflite::TensorView< T >::TensorView (const nnfw::misc::tensor::Shape & shape, T * base) inline
Construct a TensorView object with base and shape informations.
Parameters
[in] shape The shape of a tensor
[in] base The base address of a tensor
Definition at line 49 of file TensorView.h.
                                                        : _shape{shape}, _base{base}
  {
    // Set 'stride'
    _stride.init(_shape);
  }
References nnfw::tflite::TensorView< T >::_stride, and nnfw::misc::tensor::NonIncreasingStride::init().
Member Function Documentation
at() [1/2]
template<typename T > T & nnfw::tflite::TensorView< T >::at (const nnfw::misc::tensor::Index & index) inline
Get reference value of tensor index.
Parameters
[in] index The tensor index
Returns
The reference value at the index
Definition at line 80 of file TensorView.h.
  {
    const auto offset = _stride.offset(index);
    return *(_base + offset);
  }
References nnfw::tflite::TensorView< T >::_base, nnfw::tflite::TensorView< T >::_stride, offset(), and nnfw::misc::tensor::NonIncreasingStride::offset().
at() [2/2]
template<typename T > T nnfw::tflite::TensorView< T >::at (const nnfw::misc::tensor::Index & index) const inline override virtual
Get value of tensor index.
Parameters
[in] index The tensor index
Returns
The value at the index
Implements nnfw::misc::tensor::Reader< T >.
Definition at line 68 of file TensorView.h.
  {
    const auto offset = _stride.offset(index);
    return *(_base + offset);
  }
References nnfw::tflite::TensorView< T >::_base, nnfw::tflite::TensorView< T >::_stride, offset(), and nnfw::misc::tensor::NonIncreasingStride::offset().
make()
template<typename T > static TensorView< T > nnfw::tflite::TensorView< T >::make (const TfLiteTensor * tensor) inline static
Create TensorView object using given parameters.
Parameters
[in] interp The TfLite interpreter
[in] tensor_index The tensor index
Returns
The new TensorView<T> object
Definition at line 101 of file TensorView.h.
  {
    // Set 'shape'
    nnfw::misc::tensor::Shape shape(TfLiteTensorNumDims(tensor));
    for (uint32_t axis = 0; axis < shape.rank(); ++axis)
    {
      shape.dim(axis) = TfLiteTensorDim(tensor, axis);
    }
    return TensorView<T>(shape, reinterpret_cast<T *>(TfLiteTensorData(tensor)));
  }
References nnfw::misc::tensor::Shape::dim(), nnfw::misc::tensor::Shape::rank(), and nnfw::tflite::TensorView< T >::shape().
Referenced by TfLiteInterpMatchApp::run().
shape()
template<typename T > const nnfw::misc::tensor::Shape & nnfw::tflite::TensorView< T >::shape (void) const inline
Get shape of tensor.
Returns
Reference of shape
Definition at line 60 of file TensorView.h.
{ return _shape; }
Referenced by TfLiteInterpMatchApp::compareSingleTensorView(), and nnfw::tflite::TensorView< T >::make().
Field Documentation
_base
template<typename T > T* nnfw::tflite::TensorView< T >::_base
The base address of tensor
Definition at line 90 of file TensorView.h.
Referenced by nnfw::tflite::TensorView< T >::at().
_stride
template<typename T > nnfw::misc::tensor::NonIncreasingStride nnfw::tflite::TensorView< T >::_stride
The NonIncreasingStride object
Definition at line 91 of file TensorView.h.
Referenced by nnfw::tflite::TensorView< T >::at(), and nnfw::tflite::TensorView< T >::TensorView().
The documentation for this class was generated from the following file:
runtime/libs/tflite/include/tflite/TensorView.h