ONE - On-device Neural Engine: onert::backend::cpu::ops::TransposeLayer Class Reference
onert::backend::cpu::ops::TransposeLayer Class Reference
#include <TransposeLayer.h>
Public Member Functions
TransposeLayer ()
template<typename T >
void transpose ()
void transposeQuant8 ()
void configure (const IPortableTensor *input, const IPortableTensor *perm, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Detailed Description
Definition at line 27 of file TransposeLayer.h.
Constructor & Destructor Documentation
TransposeLayer()
onert::backend::cpu::ops::TransposeLayer::TransposeLayer ()
Definition at line 53 of file TransposeLayer.cc.
                               : _input(nullptr), _perm(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::TransposeLayer::configure (const IPortableTensor * input, const IPortableTensor * perm, IPortableTensor * output)
Definition at line 100 of file TransposeLayer.cc.
{
  _input = input;
  _perm = perm;
  _output = output;
}
run()
void onert::backend::cpu::ops::TransposeLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 108 of file TransposeLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    transpose<float>();
  }
  else if (_input->data_type() == OperandType::INT32)
  {
    transpose<int32_t>();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    transposeQuant8();
  }
  else
  {
    throw std::runtime_error{"Transpose: unsupported data type"};
  }
}
References onert::backend::IPortableTensor::data_type(), and transposeQuant8().
transpose()
template<typename T > void onert::backend::cpu::ops::TransposeLayer::transpose ()
Definition at line 58 of file TransposeLayer.cc.
{
  nnfw::cker::TransposeParams param;
  auto perm_shape = _perm->getShape();
  assert(perm_shape.rank() == 1);
  param.perm_count = _input->getShape().rank();
  if (perm_shape.dim(0) == 0) // This means _perm is (n-1...0)
  {
    const auto begin = param.perm;
    const auto end = param.perm + _input->getShape().rank();
    std::iota(begin, end, 0);
    std::reverse(begin, end);
  }
  else
  {
    assert(param.perm_count == static_cast<int>(perm_shape.dim(0)));
    for (auto i = 0; i < param.perm_count; i++)
    {
      param.perm[i] = *(getBuffer<int32_t>(_perm) + i);
    }
  }
  nnfw::cker::Transpose(param, getShape(_input), getBuffer<T>(_input), getShape(_output),
                        getBuffer<T>(_output));
}
References begin, onert::backend::IPortableTensor::getShape(), onert::backend::cpu::ops::getShape(), nnfw::cker::TransposeParams::perm, nnfw::cker::TransposeParams::perm_count, and nnfw::cker::Transpose().
transposeQuant8()
void onert::backend::cpu::ops::TransposeLayer::transposeQuant8 ()
Definition at line 85 of file TransposeLayer.cc.
{
  if (_input->data_zero_point() != _output->data_zero_point())
  {
    throw std::runtime_error("TransposeLayer : qassym8 input and output offsets unmatched");
  }
  if (_input->data_scale() != _output->data_scale())
  {
    throw std::runtime_error("TransposeLayer : qassym8 input and output scales unmatched");
  }
  transpose<uint8_t>();
}
References onert::backend::IPortableTensor::data_scale(), and onert::backend::IPortableTensor::data_zero_point().
Referenced by run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/TransposeLayer.h
runtime/onert/backend/cpu/ops/TransposeLayer.cc