ONE - On-device Neural Engine: coco::BlockIndex Class Reference
coco::BlockIndex Class Reference final
A BlockIndex denotes the index of a block in a block list.
#include <BlockIndex.h>
Public Member Functions
BlockIndex ()
BlockIndex (uint32_t value)
bool valid (void) const
uint32_t value (void) const
void set (uint32_t value)
void reset (void)
Detailed Description
A BlockIndex denotes the index of a block in a block list.
Definition at line 28 of file BlockIndex.h.
Constructor & Destructor Documentation
BlockIndex() [1/2]
coco::BlockIndex::BlockIndex () inline
Definition at line 34 of file BlockIndex.h.
               : _value{undefined}
  {
    // DO NOTHING
  }
BlockIndex() [2/2]
coco::BlockIndex::BlockIndex (uint32_t value) inline
Definition at line 40 of file BlockIndex.h.
{ set(value); }
References set(), and value().
Member Function Documentation
reset()
void coco::BlockIndex::reset (void) inline
Definition at line 50 of file BlockIndex.h.
{ _value = undefined; }
Referenced by coco::DLinkedList< Child, Parent >::leaving().
set()
void coco::BlockIndex::set (uint32_t value)
Definition at line 24 of file BlockIndex.cpp.
{
  assert(value != undefined);
  _value = value;
}
References value().
Referenced by BlockIndex().
valid()
bool coco::BlockIndex::valid (void) const inline
Definition at line 43 of file BlockIndex.h.
{ return _value != undefined; }
Referenced by coco::DLinkedList< Child, Parent >::joined(), and coco::DLinkedList< Child, Parent >::leaving().
value()
uint32_t coco::BlockIndex::value (void) const inline
Definition at line 46 of file BlockIndex.h.
{ return _value; }
Referenced by BlockIndex(), dump(), coco::DLinkedList< Child, Parent >::leaving(), and set().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/BlockIndex.h
compiler/coco/core/src/IR/BlockIndex.cpp