ONE - On-device Neural Engine: luci_interpreter::GraphLoader Class Reference
luci_interpreter::GraphLoader Class Reference
#include <GraphLoader.h>
Public Member Functions
GraphLoader (const loco::Graph *graph, RuntimeGraph *runtime_graph, RuntimeToIR &runtime_to_ir, const std::unordered_map< const loco::Graph *, RuntimeGraph * > &graph_to_runtime_graph, std::unordered_map< const loco::Node *, Tensor * > &node_to_tensor, IMemoryManager *memory_manager)
void loadTensors ()
void initInputOutputTensors () const
void loadOperators ()
GraphLoader (CircleReader *reader, IBaseRuntimeGraph *runtime_graph, IMemoryManager *memory_manager, std::unordered_map< int32_t, Tensor * > *index_to_tensor)
void loadTensors ()
void initInputTensors (bool use_static_memory_manager) const
void loadOperators (bool use_static_memory_manager)
Detailed Description
Definition at line 31 of file GraphLoader.h.
Constructor & Destructor Documentation
GraphLoader() [1/2]
luci_interpreter::GraphLoader::GraphLoader (const loco::Graph * graph, RuntimeGraph * runtime_graph, RuntimeToIR & runtime_to_ir, const std::unordered_map< const loco::Graph *, RuntimeGraph * > & graph_to_runtime_graph, std::unordered_map< const loco::Node *, Tensor * > & node_to_tensor, IMemoryManager * memory_manager)
Definition at line 173 of file GraphLoader.cpp.
  : _graph(graph), _runtime_graph(runtime_graph), _runtime_to_ir(runtime_to_ir),
    _graph_to_runtime_graph(graph_to_runtime_graph), _node_to_tensor(node_to_tensor),
    _memory_manager(memory_manager)
{
}
GraphLoader() [2/2]
luci_interpreter::GraphLoader::GraphLoader (CircleReader * reader, IBaseRuntimeGraph * runtime_graph, IMemoryManager * memory_manager, std::unordered_map< int32_t, Tensor * > * index_to_tensor)
Definition at line 45 of file GraphLoader.cpp.
  : _reader(reader), _runtime_graph(runtime_graph), _memory_manager(memory_manager),
    _index_to_tensor(index_to_tensor)
{
}
Member Function Documentation
initInputOutputTensors()
void luci_interpreter::GraphLoader::initInputOutputTensors () const
Definition at line 270 of file GraphLoader.cpp.
{
  auto input_nodes = loco::input_nodes(_graph);
  std::vector<Tensor *> input_tensors(input_nodes.size());
  for (size_t i = 0; i < input_nodes.size(); ++i)
  {
    input_tensors[i] = _node_to_tensor.at(input_nodes[i]);
    _memory_manager->allocate_memory(*input_tensors[i]);
  }
  _runtime_graph->setInputTensors(input_tensors);
  auto output_nodes = loco::output_nodes(const_cast<loco::Graph *>(_graph));
  std::vector<Tensor *> output_tensors(output_nodes.size());
  for (size_t i = 0; i < output_nodes.size(); ++i)
  {
    const auto *node = loco::must_cast<const luci::CircleOutput *>(output_nodes[i]);
    output_tensors[i] = _node_to_tensor.at(node->from());
  }
  _runtime_graph->setOutputTensors(output_tensors);
}
References luci_interpreter::IMemoryManager::allocate_memory(), loco::input_nodes(), loco::output_nodes(), luci_interpreter::RuntimeGraph::setInputTensors(), and luci_interpreter::RuntimeGraph::setOutputTensors().
Referenced by luci_interpreter::ModuleLoader::load().
initInputTensors()
void luci_interpreter::GraphLoader::initInputTensors (bool use_static_memory_manager) const
Definition at line 140 of file GraphLoader.cpp.
{
  for (const auto input_ind : _reader->inputs())
  {
    const auto tensor = _reader->tensors()[input_ind];
    const auto dtype = luci_datatype(tensor->type());
    const auto tensor_shape = wrap(tensor->shape());
    Shape shape(static_cast<int>(tensor_shape.size()));
    for (int i = 0; i < tensor_shape.size(); ++i)
    {
      shape.dim(i) = tensor_shape.at(i);
    }
    AffineQuantization *quantization = nullptr;
    if (dtype == DataType::U8 or dtype == DataType::S8 or dtype == DataType::S16)
    {
      auto unique_ptr_quantization = std::make_unique<AffineQuantization>();
      const auto quant_params = tensor->quantization();
      assert(quant_params->zero_point()->size() == quant_params->scale()->size());
      unique_ptr_quantization->scale.assign(quant_params->scale()->cbegin(),
                                            quant_params->scale()->cend());
      unique_ptr_quantization->zero_point.assign(quant_params->zero_point()->cbegin(),
                                                 quant_params->zero_point()->cend());
      unique_ptr_quantization->quantized_dimension = quant_params->quantized_dimension();
      quantization = _runtime_graph->addAffineQuantization(std::move(unique_ptr_quantization));
    }
    auto tensor_interpreter = std::make_unique<Tensor>(dtype, std::move(shape), quantization);
    tensor_interpreter->set_allocatable(_memory_manager->is_allocate_input());
    if (not use_static_memory_manager)
    {
      // Using Dynamic Allocations
      _memory_manager->allocate_memory(*tensor_interpreter);
    }
    else
    {
      // Using static allocations
      _memory_manager->allocate_input_buf();
    }
    _runtime_graph->addInputTensor(tensor_interpreter.get());
    _index_to_tensor->emplace(input_ind, tensor_interpreter.get());
    _runtime_graph->addTensor(std::move(tensor_interpreter));
  }
}
References luci_interpreter::IBaseRuntimeGraph::addAffineQuantization(), luci_interpreter::IBaseRuntimeGraph::addInputTensor(), luci_interpreter::RuntimeGraph::addTensor(), luci_interpreter::IMemoryManager::allocate_input_buf(), luci_interpreter::IMemoryManager::allocate_memory(), luci_interpreter::Shape::dim(), luci::CircleReader::inputs(), luci_interpreter::IMemoryManager::is_allocate_input(), luci::luci_datatype(), luci::CircleReader::tensors(), and luci::wrap().
Referenced by luci_interpreter::ModuleLoader::load().
loadOperators() [1/2]
void luci_interpreter::GraphLoader::loadOperators ()
Definition at line 291 of file GraphLoader.cpp.
{
  KernelBuilder kernel_builder(_graph_to_runtime_graph, _node_to_tensor);
  // Create kernels for executable nodes. This has to be done in execution order.
  auto graph = const_cast<loco::Graph *>(_graph);
  auto const graph_nodes = loco::all_nodes(graph);
  // Checking for execution plan in node annotations.
  bool has_execution_annotation = true;
  auto const checking_exec_plan = [&has_execution_annotation](auto const node) {
    const auto *circle_node = loco::must_cast<const luci::CircleNode *>(node);
    if (!luci::has_execution_plan(circle_node))
      has_execution_annotation = false;
  };
  std::for_each(begin(graph_nodes), end(graph_nodes), checking_exec_plan);
  if (has_execution_annotation)
  {
    // Build ordered_nodes vector that stores the order of execution of graph nodes.
    std::vector<const luci::CircleNode *> ordered_nodes(graph_nodes.size());
    auto const filler = [&ordered_nodes](auto const node) {
      const auto *circle_node = loco::must_cast<const luci::CircleNode *>(node);
      auto const position = luci::get_execution_plan(circle_node).order_in_plan();
      ordered_nodes.at(position) = circle_node;
    };
    std::for_each(begin(graph_nodes), end(graph_nodes), filler);
    for (auto node : ordered_nodes)
    {
      if (isExecutableNode(node))
      {
        std::unique_ptr<Kernel> kernel = kernel_builder.build(node);
        _runtime_to_ir.kernel_to_node.emplace(kernel.get(), node);
        _runtime_graph->addKernel(std::move(kernel));
      }
    }
  }
  else
  {
    // If it is impossible to build the execution order plan,
    // then we use the default postorder_traversal approach.
    for (const loco::Node *loco_node : loco::postorder_traversal(loco::output_nodes(graph)))
    {
      const auto *node = loco::must_cast<const luci::CircleNode *>(loco_node);
      if (isExecutableNode(node))
      {
        std::unique_ptr<Kernel> kernel = kernel_builder.build(node);
        _runtime_to_ir.kernel_to_node.emplace(kernel.get(), node);
        _runtime_graph->addKernel(std::move(kernel));
      }
    }
  }
}
References luci_interpreter::RuntimeGraph::addKernel(), loco::all_nodes(), luci_interpreter::KernelBuilder::build(), luci::get_execution_plan(), luci::has_execution_plan(), luci_interpreter::RuntimeToIR::kernel_to_node, luci::CircleNodeExecutionPlan::order_in_plan(), loco::output_nodes(), and loco::postorder_traversal().
Referenced by luci_interpreter::ModuleLoader::load().
loadOperators() [2/2]
void luci_interpreter::GraphLoader::loadOperators (bool use_static_memory_manager)
Definition at line 189 of file GraphLoader.cpp.
{
  ExecutionPlanTable execution_plan;
  // Set execution plan for static memory manager
  if (use_static_memory_manager)
  {
    // Read metadata
    const auto metadata = _reader->metadata();
    for (auto meta : metadata)
    {
      assert(meta != nullptr);
      assert(meta->buffer() < _reader->buffers().size());
      assert(_reader->buffers()[meta->buffer()] != nullptr);
      const auto buffer = wrap(_reader->buffers()[meta->buffer()]->data());
      if (meta->name()->str().compare("ONE_execution_plan_table") == 0)
      {
        execution_plan = read_metadata::decode_execution_plan(buffer);
      }
    }
    if (execution_plan.empty())
      assert(false && "Static Memory Manager should be used with circle-execution-planner");
  }
  KernelBuilder kernel_builder(_runtime_graph, _reader);
  const uint32_t input_size = _runtime_graph->getInputTensors().size();
  const uint32_t output_size = _reader->outputs().size();
  if (use_static_memory_manager)
  {
    // Set offset for input tensors
    for (int32_t input_ind = 0; input_ind < input_size; ++input_ind)
    {
      auto input_tensor = _runtime_graph->getInputTensors().at(input_ind);
      input_tensor->set_offset(execution_plan.at(input_ind)[0]);
      _memory_manager->allocate_memory_for_input(*input_tensor);
    }
  }
  for (uint32_t i = 0; i < _reader->operators().size(); ++i)
  {
    const auto op = _reader->operators().at(i);
    assert(op != nullptr);
    std::vector<const Tensor *> input_tensors(op->inputs()->size());
    std::vector<Tensor *> output_tensors(op->outputs()->size());
    bool is_inplace = false;
    for (int32_t j = 0; j < op->inputs()->size(); ++j)
    {
      const auto input_index = op->inputs()->operator[](j);
      if (_index_to_tensor->find(input_index) != _index_to_tensor->end())
      {
        auto input_tensor = _index_to_tensor->at(input_index);
        input_tensors.at(j) = input_tensor;
        const auto &graph_input_tensors = _runtime_graph->getInputTensors();
        // TODO: handle Inplace Optimization with Static Memory Manager
        if (not use_static_memory_manager and
            isCouldBeEmplaceOperation(_reader->builtin_code(op)) and op->outputs()->size() == 1 and
            isCouldBeEmplaceTensor(input_index) and
            (std::find(graph_input_tensors.begin(), graph_input_tensors.end(), input_tensor) ==
             graph_input_tensors.end()))
        {
          is_inplace = true;
        }
      }
      else
      {
        input_tensors.at(j) = nullptr;
      }
    }
    for (int32_t j = 0; j < op->outputs()->size(); ++j)
    {
      const auto output_index = op->outputs()->operator[](j);
      const auto tensor = _reader->tensors()[output_index];
      const auto dtype = luci_datatype(tensor->type());
      const auto tensor_shape = wrap(tensor->shape());
      Shape shape(static_cast<int>(tensor_shape.size()));
      for (int k = 0; k < tensor_shape.size(); ++k)
      {
        shape.dim(k) = tensor_shape.at(k);
      }
      AffineQuantization *quantization = nullptr;
      if (dtype == DataType::U8 or dtype == DataType::S8 or dtype == DataType::S16)
      {
        auto unique_ptr_quantization = std::make_unique<AffineQuantization>();
        const auto quant_params = tensor->quantization();
        assert(quant_params->zero_point()->size() == quant_params->scale()->size());
        unique_ptr_quantization->scale.assign(quant_params->scale()->cbegin(),
                                              quant_params->scale()->cend());
        unique_ptr_quantization->zero_point.assign(quant_params->zero_point()->cbegin(),
                                                   quant_params->zero_point()->cend());
        unique_ptr_quantization->quantized_dimension = quant_params->quantized_dimension();
        quantization = _runtime_graph->addAffineQuantization(std::move(unique_ptr_quantization));
      }
      auto tensor_interpreter = std::make_unique<Tensor>(dtype, std::move(shape), quantization);
      if (use_static_memory_manager and
          (std::find(_reader->outputs().begin(), _reader->outputs().end(), output_index) ==
           _reader->outputs().end()))
      {
        tensor_interpreter->set_offset(execution_plan.at(i + input_size + output_size).at(0));
      }
      _index_to_tensor->emplace(output_index, tensor_interpreter.get());
      output_tensors.at(j) = tensor_interpreter.get();
      if (std::find(_reader->outputs().begin(), _reader->outputs().end(), output_index) !=
          _reader->outputs().end())
        _runtime_graph->addOutputTensor(tensor_interpreter.get());
      _runtime_graph->addTensor(std::move(tensor_interpreter));
    }
    const auto opcode = _reader->builtin_code(op);
    std::unique_ptr<Kernel> kernel =
      kernel_builder.build(std::move(input_tensors), std::move(output_tensors), opcode, i);
    kernel->setInplaceValue(is_inplace);
    _runtime_graph->addKernel(std::move(kernel));
  }
  if (use_static_memory_manager)
  {
    for (int32_t ind = 0; ind < output_size; ++ind)
    {
      auto output_tensor = _runtime_graph->getOutputTensors().at(ind);
      output_tensor->set_offset(execution_plan.at(input_size + ind)[0]);
    }
  }
}
References luci_interpreter::IBaseRuntimeGraph::addAffineQuantization(), luci_interpreter::RuntimeGraph::addKernel(), luci_interpreter::IBaseRuntimeGraph::addOutputTensor(), luci_interpreter::RuntimeGraph::addTensor(), luci_interpreter::IMemoryManager::allocate_memory_for_input(), luci::VectorWrapper< T >::at(), luci::CircleReader::buffers(), luci_interpreter::KernelBuilder::build(), luci::CircleReader::builtin_code(), luci::VectorWrapper< T >::data(), luci_interpreter::read_metadata::decode_execution_plan(), luci_interpreter::Shape::dim(), luci_interpreter::RuntimeGraph::getInputTensors(), luci_interpreter::RuntimeGraph::getOutputTensors(), luci::luci_datatype(), luci::CircleReader::metadata(), luci::CircleReader::operators(), luci::CircleReader::outputs(), luci::VectorWrapper< T >::size(), luci_interpreter::size(), luci::CircleReader::tensors(), and luci::wrap().
loadTensors() [1/2]
void luci_interpreter::GraphLoader::loadTensors ()
Definition at line 183 of file GraphLoader.cpp.
{
  for (uint32_t i = 0; i < _graph->nodes()->size(); ++i)
  {
    const auto *node = loco::must_cast<const luci::CircleNode *>(_graph->nodes()->at(i));
    if (node->opcode() == luci::CircleOpcode::CUSTOM && !isSupportedCustomNode(node))
    {
      const auto *cnode = loco::must_cast<const luci::CircleCustom *>(node);
      throw std::runtime_error("Unsupported Custom operator. " + cnode->custom_code() + " in " +
                               node->name());
    }
    if (!isTensorProducingNode(node))
      continue;
    // Only Input, Const, Custom and Variable nodes have shapes. Shapes of intermediate tensors will
    // be inferred.
    Shape shape{};
    switch (node->opcode())
    {
      case luci::CircleOpcode::CIRCLECONST:
      case luci::CircleOpcode::CIRCLECUSTOMOUT:
      case luci::CircleOpcode::CIRCLEINPUT:
      case luci::CircleOpcode::CIRCLEVARIABLE:
        shape = getNodeShape(node);
        break;
      default:
        break;
    }
    AffineQuantization quantization;
    if (node->quantparam() != nullptr)
    {
      const luci::CircleQuantParam *params = node->quantparam();
      assert(params->scale.size() == params->zerop.size());
      quantization.scale.assign(params->scale.cbegin(), params->scale.cend());
      quantization.zero_point.assign(params->zerop.cbegin(), params->zerop.cend());
      quantization.quantized_dimension = params->quantized_dimension;
    }
    auto tensor = std::make_unique<Tensor>(node->dtype(), std::move(shape), std::move(quantization),
                                           node->name());
    // If node has execution plan then read memory offsets for nodes
    // from the beginning of shared memory buffer. Used in Static Memory Manager.
    if (luci::has_execution_plan(node))
    {
      auto execution_plan = luci::get_execution_plan(node);
      assert(!execution_plan.offsets().empty());
      tensor->set_offset(execution_plan.offsets().front());
    }
    if (const auto *const_node = dynamic_cast<const luci::CircleConst *>(node))
    {
      size_t data_size{};
      const void *const_data = getNodeData(const_node, &data_size);
      if (const_data != nullptr)
      {
        _memory_manager->allocate_memory(*tensor);
        tensor->writeData(const_data, data_size);
      }
    }
    else if (const auto *custom_out_node = dynamic_cast<const luci::CircleCustomOut *>(node))
    {
      const auto *custom_node =
        loco::must_cast<const luci::CircleCustom *>(custom_out_node->input());
      if (custom_node->custom_code() == "CircleReferencingConst")
      {
        size_t data_size{};
        const void *const_data = getNodeData(custom_node, &data_size);
        if (const_data != nullptr)
        {
          _memory_manager->allocate_memory(*tensor);
          tensor->writeData(const_data, data_size);
        }
      }
    }
    _node_to_tensor.emplace(node, tensor.get());
    _runtime_to_ir.tensor_to_node.emplace(tensor.get(), node);
    _runtime_graph->addTensor(std::move(tensor));
  }
}
References luci_interpreter::RuntimeGraph::addTensor(), luci_interpreter::IMemoryManager::allocate_memory(), loco::ObjectPool< T >::at(), luci::get_execution_plan(), luci::has_execution_plan(), luci::CircleNode::name(), loco::Graph::nodes(), luci::CircleNode::opcode(), luci_interpreter::AffineQuantization::quantized_dimension, luci::CircleQuantParam::quantized_dimension, luci::CircleNode::quantparam(), luci_interpreter::AffineQuantization::scale, luci::CircleQuantParam::scale, luci_interpreter::size(), luci_interpreter::RuntimeToIR::tensor_to_node, luci_interpreter::AffineQuantization::zero_point, and luci::CircleQuantParam::zerop.
Referenced by luci_interpreter::ModuleLoader::load().
loadTensors() [2/2]
void luci_interpreter::GraphLoader::loadTensors ()
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/loader/GraphLoader.h
onert-micro/luci-interpreter/src/loader/GraphLoader.h
compiler/luci-interpreter/src/loader/GraphLoader.cpp
onert-micro/luci-interpreter/src/loader/GraphLoader.cpp