ONE - On-device Neural Engine: mpqsolver::bisection::Quantizer Class Reference
mpqsolver::bisection::Quantizer Class Reference
#include <Quantizer.h>
Public Member Functions
Quantizer (const std::string &input_dtype, const std::string &output_type)
bool quantize (luci::Module *module, const std::string &quant_dtype, LayerParams &layer_params)
quantize recorded module (min/max initialized) with specified parameters returns true on success
bool fake_quantize (luci::Module *module, const std::string &quant_dtype, LayerParams &layer_params)
fake_quantize recorded module (min/max initialized) with specified parameters returns true on success
Detailed Description
Definition at line 35 of file Quantizer.h.
Constructor & Destructor Documentation
Quantizer()
Quantizer::Quantizer (const std::string & input_dtype, const std::string & output_type)
Definition at line 52 of file Quantizer.cpp.
  : _input_dtype(input_dtype), _output_dtype(output_dtype)
{
}
Member Function Documentation
fake_quantize()
bool Quantizer::fake_quantize (luci::Module * module, const std::string & quant_dtype, LayerParams & layer_params)
fake_quantize recorded module (min/max initialized) with specified parameters returns true on success
Definition at line 114 of file Quantizer.cpp.
{
  if (!quantize(module, quant_dtype, layer_params))
    return false;
  if (!make_model_fake_quantized(module))
    return false;
  return true;
}
References quantize().
quantize()
bool Quantizer::quantize (luci::Module * module, const std::string & quant_dtype, LayerParams & layer_params)
quantize recorded module (min/max initialized) with specified parameters returns true on success
Definition at line 61 of file Quantizer.cpp.
{
  if (!module)
    return false;
  static const std::string default_dtype = "float32";
  static const std::string granularity_type = "channel";
  luci::CircleQuantizer quantizer;
  auto options = quantizer.options();
  options->enable(Algorithms::QuantizeWithMinMax);
  options->param(AlgorithmParameters::Quantize_input_model_dtype, default_dtype);
  options->param(AlgorithmParameters::Quantize_output_model_dtype, quant_dtype);
  options->param(AlgorithmParameters::Quantize_granularity, granularity_type);
  options->param(AlgorithmParameters::Quantize_input_type, _input_dtype);
  options->param(AlgorithmParameters::Quantize_output_type, _output_dtype);
  options->param(AlgorithmParameters::Quantize_TF_style_maxpool, "False");
  if (!layer_params.empty())
  {
    try
    {
      options->layer_params(AlgorithmParameters::Quantize_layer_params, layer_params);
    }
    catch (const std::runtime_error &e)
    {
      std::cerr << e.what() << '\n';
      return false;
    }
  }
  for (size_t idx = 0; idx < module->size(); ++idx)
  {
    auto graph = module->graph(idx);
    // quantize the graph
    quantizer.quantize(graph);
    if (!luci::validate(graph))
    {
      std::cerr << "ERROR: Quantized graph is invalid" << std::endl;
      return false;
    }
  }
  return true;
}
References luci::CircleQuantizer::options(), luci::CircleQuantizer::quantize(), and luci::validate().
Referenced by fake_quantize().
The documentation for this class was generated from the following files:
compiler/circle-mpqsolver/src/bisection/Quantizer.h
compiler/circle-mpqsolver/src/bisection/Quantizer.cpp