ONE - On-device Neural Engine: loco::Mixin< Trait::DataTyped > Class Reference
loco::Mixin< Trait::DataTyped > Class Reference
#include <Graph.h>
Public Member Functions
Mixin ()=default
const DataType & dtype (void) const
void dtype (const DataType &value)
Detailed Description
Definition at line 57 of file Graph.h.
Constructor & Destructor Documentation
Mixin()
loco::Mixin< Trait::DataTyped >::Mixin () default
Member Function Documentation
dtype() [1/2]
void loco::Mixin< Trait::DataTyped >::dtype (const DataType & value) inline
Definition at line 64 of file Graph.h.
{ _dtype = value; }
dtype() [2/2]
const DataType & loco::Mixin< Trait::DataTyped >::dtype (void) const inline
Definition at line 63 of file Graph.h.
{ return _dtype; }
Referenced by loco::Pull::dtype(), loco::Pull::index(), and mir2loco::Transformer::visit().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Graph.h