ONE - On-device Neural Engine: loco::NodePool Class Reference
loco::NodePool Class Reference final
#include <NodePool.h>
Public Member Functions
~NodePool ()
template<typename Derived , typename... Args>
Derived * create (Args &&... args)
void destroy (Node *node)
Public Member Functions inherited from loco::ObjectPool< Node >
virtual ~ObjectPool ()=default
uint32_t size (void) const
Return the number of objects.
Node * at (uint32_t n) const
Access N-th object.
Friends
class Graph
Additional Inherited Members
Protected Member Functions inherited from loco::ObjectPool< Node >
U * take (std::unique_ptr< U > &&o)
Take the ownership of a given object and returns its raw pointer.
bool erase (Node *ptr)
Erase an object from the pool.
Detailed Description
Definition at line 28 of file NodePool.h.
Constructor & Destructor Documentation
~NodePool()
loco::NodePool::~NodePool ()
Definition at line 22 of file NodePool.cpp.
{
  // Drop all the references before deallocation
  for (uint32_t n = 0; n < size(); ++n)
  {
    at(n)->drop();
  }
}
References loco::ObjectPool< Node >::at(), loco::Node::drop(), and loco::ObjectPool< Node >::size().
Member Function Documentation
create()
template<typename Derived , typename... Args> Derived * loco::NodePool::create (Args &&... args) inline
Definition at line 37 of file NodePool.h.
  {
    std::unique_ptr<Derived> ptr{new Derived(std::forward<Args>(args)...)};
    ptr->graph(_graph);
    return ObjectPool<Node>::take<Derived>(std::move(ptr));
  }
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), exo::TensorConcatConverter::convert(), InputLayer::operator()(), OutputLayer::operator()(), ReLULayer::operator()(), ConstGenLayer::operator()(), FeatureEncodeLayer::operator()(), FeatureDecodeLayer::operator()(), FilterEncodeLayer::operator()(), DepthwiseFilterEncodeLayer::operator()(), DepthwiseConv2DLayer::operator()(), TransposedConv2DLayer::operator()(), FixedReshapeLayer::operator()(), TensorBroadcastLayer::operator()(), luci::FuseBCQPass::run(), locoex::set_new_shape(), and luci::CloneNode::visit().
destroy()
void loco::NodePool::destroy (Node * node) inline
Definition at line 44 of file NodePool.h.
  {
    if (!ObjectPool<Node>::erase(node))
    {
      throw std::invalid_argument{"node"};
    }
  }
Friends And Related Function Documentation
Graph
friend class Graph friend
Definition at line 31 of file NodePool.h.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/NodePool.h
compiler/loco/src/IR/NodePool.cpp