ONE - On-device Neural Engine: luci_interpreter::kernels::Neg Class Reference
luci_interpreter::kernels::Neg Class Reference
#include <Neg.h>
Public Member Functions
Neg (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Neg (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Neg.h.
Constructor & Destructor Documentation
Neg() [1/2]
luci_interpreter::kernels::Neg::Neg (const Tensor * input, Tensor * output)
Definition at line 30 of file Neg.cpp.
: Kernel({input}, {output}) {}
References input().
Neg() [2/2]
luci_interpreter::kernels::Neg::Neg (const Tensor * input, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Neg::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 32 of file Neg.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::Neg::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Neg::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 39 of file Neg.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Neg::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Neg::input () const inline
Definition at line 33 of file Neg.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Neg().
input() [2/2]
const Tensor * luci_interpreter::kernels::Neg::input () const inline
Definition at line 33 of file Neg.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Neg::output () const inline
Definition at line 34 of file Neg.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Neg::output () const inline
Definition at line 34 of file Neg.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Neg.h
onert-micro/luci-interpreter/src/kernels/Neg.h
compiler/luci-interpreter/src/kernels/Neg.cpp
onert-micro/luci-interpreter/src/kernels/Neg.cpp