ONE - On-device Neural Engine: luci_interpreter_pal::lstm_internal::LstmStepManager Class Reference
luci_interpreter_pal::lstm_internal::LstmStepManager Class Reference
#include <PALUnidirectionalSequenceLSTMCommon.h>
Public Member Functions
LstmStepManager ()=delete
LstmStepManager (const LstmSizeInfo &size_info)
void updateTime ()
void updateBatch ()
void resetTime ()
luci_interpreter::RuntimeShape inputShape () const
luci_interpreter::RuntimeShape stateShape () const
int inputOffset () const
int outputOffset () const
int hiddenStateOffset () const
int cellStateOffset () const
Detailed Description
Definition at line 190 of file PALUnidirectionalSequenceLSTMCommon.h.
Constructor & Destructor Documentation
LstmStepManager() [1/2]
luci_interpreter_pal::lstm_internal::LstmStepManager::LstmStepManager () delete
LstmStepManager() [2/2]
luci_interpreter_pal::lstm_internal::LstmStepManager::LstmStepManager (const LstmSizeInfo & size_info) inline explicit
Definition at line 196 of file PALUnidirectionalSequenceLSTMCommon.h.
: size_info_(size_info) {}
Member Function Documentation
cellStateOffset()
int luci_interpreter_pal::lstm_internal::LstmStepManager::cellStateOffset () const inline
Definition at line 260 of file PALUnidirectionalSequenceLSTMCommon.h.
{ return cell_state_offset_; }
Referenced by luci_interpreter_pal::lstm_internal::updateLstmCell(), and luci_interpreter_pal::lstm_internal::updateLstmHidden().
hiddenStateOffset()
int luci_interpreter_pal::lstm_internal::LstmStepManager::hiddenStateOffset () const inline
Definition at line 258 of file PALUnidirectionalSequenceLSTMCommon.h.
{ return hidden_state_offset_; }
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate(), luci_interpreter_pal::lstm_internal::lstmStep(), and luci_interpreter_pal::lstm_internal::updateLstmHidden().
inputOffset()
int luci_interpreter_pal::lstm_internal::LstmStepManager::inputOffset () const inline
Definition at line 254 of file PALUnidirectionalSequenceLSTMCommon.h.
{ return input_offset_; }
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate().
inputShape()
luci_interpreter::RuntimeShape luci_interpreter_pal::lstm_internal::LstmStepManager::inputShape () const inline
Definition at line 230 of file PALUnidirectionalSequenceLSTMCommon.h.
  {
    int batch_size = 1;
    if (size_info_.time_major)
    {
      batch_size = size_info_.batch_size;
    }
    const int dims[2] = {batch_size, size_info_.input_dimension};
    const int32_t *dims_data = reinterpret_cast<const int32_t *>(dims);
    return luci_interpreter::RuntimeShape(2, dims_data);
  }
References luci_interpreter_pal::lstm_internal::LstmSizeInfo::batch_size, luci_interpreter_pal::lstm_internal::LstmSizeInfo::input_dimension, and luci_interpreter_pal::lstm_internal::LstmSizeInfo::time_major.
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate().
outputOffset()
int luci_interpreter_pal::lstm_internal::LstmStepManager::outputOffset () const inline
Definition at line 256 of file PALUnidirectionalSequenceLSTMCommon.h.
{ return output_offset_; }
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
resetTime()
void luci_interpreter_pal::lstm_internal::LstmStepManager::resetTime () inline
Definition at line 228 of file PALUnidirectionalSequenceLSTMCommon.h.
{ current_time_ = 0; }
Referenced by luci_interpreter_pal::evalLSTM(), and luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >().
stateShape()
luci_interpreter::RuntimeShape luci_interpreter_pal::lstm_internal::LstmStepManager::stateShape () const inline
Definition at line 242 of file PALUnidirectionalSequenceLSTMCommon.h.
  {
    int batch_size = 1;
    if (size_info_.time_major)
    {
      batch_size = size_info_.batch_size;
    }
    const int dims[2] = {batch_size, size_info_.state_dimension};
    const int32_t *dims_data = reinterpret_cast<const int32_t *>(dims);
    return luci_interpreter::RuntimeShape(2, dims_data);
  }
References luci_interpreter_pal::lstm_internal::LstmSizeInfo::batch_size, luci_interpreter_pal::lstm_internal::LstmSizeInfo::state_dimension, and luci_interpreter_pal::lstm_internal::LstmSizeInfo::time_major.
Referenced by luci_interpreter_pal::lstm_internal::calculateLstmGate(), luci_interpreter_pal::lstm_internal::lstmStep(), luci_interpreter_pal::lstm_internal::updateLstmCell(), and luci_interpreter_pal::lstm_internal::updateLstmHidden().
updateBatch()
void luci_interpreter_pal::lstm_internal::LstmStepManager::updateBatch () inline
Definition at line 215 of file PALUnidirectionalSequenceLSTMCommon.h.
  {
    current_batch_ += 1;
    // batch inference for time major: no action needed
    if (size_info_.time_major)
    {
      return;
    }
    // otherwise: singe batch inference, go to the next batch
    hidden_state_offset_ += size_info_.state_dimension;
    cell_state_offset_ += size_info_.state_dimension;
  }
References luci_interpreter_pal::lstm_internal::LstmSizeInfo::state_dimension, and luci_interpreter_pal::lstm_internal::LstmSizeInfo::time_major.
Referenced by luci_interpreter_pal::evalLSTM(), and luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >().
updateTime()
void luci_interpreter_pal::lstm_internal::LstmStepManager::updateTime () inline
Definition at line 198 of file PALUnidirectionalSequenceLSTMCommon.h.
  {
    current_time_ += 1;
    // default as one batch per inference
    int input_step = size_info_.input_dimension;
    int output_step = size_info_.state_dimension;
    // time major: batch inference
    if (size_info_.time_major)
    {
      input_step = input_step * size_info_.batch_size;
      output_step = output_step * size_info_.batch_size;
    }
    input_offset_ += input_step;
    output_offset_ += output_step;
  }
References luci_interpreter_pal::lstm_internal::LstmSizeInfo::batch_size, luci_interpreter_pal::lstm_internal::LstmSizeInfo::input_dimension, luci_interpreter_pal::lstm_internal::LstmSizeInfo::state_dimension, and luci_interpreter_pal::lstm_internal::LstmSizeInfo::time_major.
Referenced by luci_interpreter_pal::evalLSTM(), and luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >().
The documentation for this class was generated from the following file:
onert-micro/luci-interpreter/pal/common/PALUnidirectionalSequenceLSTMCommon.h