ONE - On-device Neural Engine: AveragePool2DChef Class Reference
AveragePool2DChef Class Reference final
#include <AveragePool2D.h>
Public Member Functions
AveragePool2DChef (const tflchef::Operation *operation)
tflite::BuiltinOperator code (void) const override
tflite::BuiltinOptions type (void) const override
flatbuffers::Offset< void > value (flatbuffers::FlatBufferBuilder &fbb) const override
Public Member Functions inherited from OpChef
virtual ~OpChef ()=default
virtual circle::BuiltinOperator code (void) const =0
virtual circle::BuiltinOptions type (void) const =0
virtual flatbuffers::Offset< void > value (flatbuffers::FlatBufferBuilder &fbb) const =0
virtual flatbuffers::Offset< flatbuffers::Vector< uint8_t > > custom_value (flatbuffers::FlatBufferBuilder &fbb) const
virtual ~OpChef ()=default
virtual tflite::BuiltinOperator code (void) const =0
virtual tflite::BuiltinOptions type (void) const =0
virtual flatbuffers::Offset< void > value (flatbuffers::FlatBufferBuilder &fbb) const =0
virtual flatbuffers::Offset< flatbuffers::Vector< uint8_t > > custom_value (flatbuffers::FlatBufferBuilder &fbb) const
Detailed Description
Definition at line 22 of file AveragePool2D.h.
Constructor & Destructor Documentation
AveragePool2DChef()
AveragePool2DChef::AveragePool2DChef (const tflchef::Operation * operation) inline explicit
Definition at line 25 of file AveragePool2D.h.
                                                                : _operation{operation}
  {
    // DO NOTHING
  }
Member Function Documentation
code()
tflite::BuiltinOperator AveragePool2DChef::code (void) const inline override virtual
Implements OpChef.
Definition at line 31 of file AveragePool2D.h.
  {
    return tflite::BuiltinOperator_AVERAGE_POOL_2D;
  }
type()
tflite::BuiltinOptions AveragePool2DChef::type (void) const inline override virtual
Implements OpChef.
Definition at line 36 of file AveragePool2D.h.
{ return tflite::BuiltinOptions_Pool2DOptions; }
Referenced by OptionBuilder.OptionBuilder::build().
value()
flatbuffers::Offset< void > AveragePool2DChef::value (flatbuffers::FlatBufferBuilder & fbb) const override virtual
Implements OpChef.
Definition at line 22 of file AveragePool2D.cpp.
{
  auto &operation = (*_operation);
  assert(operation.has_averagepool2d_options());
  auto options = operation.averagepool2d_options();
  auto tflite_padding = as_tflite_padding(options.padding());
  auto tflite_activation = as_tflite_activation(options.activation());
  tflite::Pool2DOptionsBuilder options_builder{fbb};
  options_builder.add_padding(tflite_padding);
  options_builder.add_stride_h(options.stride_h());
  options_builder.add_stride_w(options.stride_w());
  options_builder.add_filter_width(options.filter_width());
  options_builder.add_filter_height(options.filter_height());
  options_builder.add_fused_activation_function(tflite_activation);
  return options_builder.Finish().Union();
}
References as_tflite_activation(), and as_tflite_padding().
The documentation for this class was generated from the following files:
compiler/tflchef/core/src/Op/AveragePool2D.h
compiler/tflchef/core/src/Op/AveragePool2D.cpp