ONE - On-device Neural Engine: exo::TensorConcatConverter Class Reference
exo::TensorConcatConverter Class Reference
Convert loco::TensorConcat to TFLConcatenate.
#include <TensorConcatConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::TensorConcat *origin) final
Converts loco::TensorConcat to locoex::TFLConcatenate.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::TensorConcat >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::TensorConcat *node)=0
Detailed Description
Convert loco::TensorConcat to TFLConcatenate.
Definition at line 30 of file TensorConcatConverter.h.
Member Function Documentation
convert()
bool exo::TensorConcatConverter::convert (loco::TensorConcat * origin) final virtual
Converts loco::TensorConcat to locoex::TFLConcatenate.
Before: input:0 --— loco::TensorConcat ----— C input:1 -—/
After: input:0 --— locoex::TFLConcatenate — C input:1 -—/
input:0 --— loco::TensorConcat — input:1 -—/
Implements exo::CanonicalNodeConverter< loco::TensorConcat >.
Definition at line 43 of file TensorConcatConverter.cpp.
{
  assert(loco::shape_get(origin).domain() == loco::Domain::Tensor);
  if (!loco::shape_known(origin))
  {
    return false;
  }
  auto tfl_concat = origin->graph()->nodes()->create<locoex::TFLConcatenation>(2);
  tfl_concat->values(0, origin->lhs());
  tfl_concat->values(1, origin->rhs());
  tfl_concat->axis(origin->axis());
  tfl_concat->fusedActivationFunction(locoex::FusedActFunc::NONE);
  loco::replace(origin).with(tfl_concat);
  origin->lhs(nullptr);
  origin->rhs(nullptr);
  return true;
}
References loco::TensorConcat::axis(), loco::NodePool::create(), loco::Node::graph(), loco::TensorConcat::lhs(), loco::Graph::nodes(), locoex::NONE, loco::replace(), loco::TensorConcat::rhs(), loco::shape_get(), loco::shape_known(), loco::Tensor, locoex::TFLConcatenation::values(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::TensorConcatConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::TensorConcat >.
Definition at line 33 of file TensorConcatConverter.h.
{ return "exo::TensorConcatConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/TensorConcatConverter.h
compiler/exo/src/Conversion/TensorConcatConverter.cpp