ONE - On-device Neural Engine: GraphTestcase< GraphCode::TensorConcat > Class Reference
GraphTestcase< GraphCode::TensorConcat > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::Pull * lhs_node = nullptr
loco::Pull * rhs_node = nullptr
loco::TensorConcat * concat_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 393 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::TensorConcat >::GraphTestcase () inline
Definition at line 396 of file GraphTestcase.h.
  {
    using namespace loco;
    // Create a sample network
    _graph = make_graph();
    // Create Graph Input/Output
    auto graph_lhs = _graph->inputs()->create();
    auto graph_rhs = _graph->inputs()->create();
    auto graph_out = _graph->outputs()->create();
    graph_lhs->name("lhs");
    graph_rhs->name("rhs");
    graph_out->name("output");
    // Create and connect nodes
    lhs_node = _graph->nodes()->create<Pull>();
    lhs_node->index(0);
    rhs_node = _graph->nodes()->create<Pull>();
    rhs_node->index(1);
    concat_node = _graph->nodes()->create<TensorConcat>();
    concat_node->lhs(lhs_node);
    concat_node->rhs(rhs_node);
    push_node = _graph->nodes()->create<loco::Push>();
    push_node->index(0);
    push_node->from(concat_node);
    // Create a link between input/output and corresponding nodes
    loco::link(graph_lhs, lhs_node);
    loco::link(graph_rhs, rhs_node);
    loco::link(graph_out, push_node);
  }
References loco::Push::from(), loco::Pull::index(), loco::Push::index(), loco::TensorConcat::lhs(), and loco::link().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::TensorConcat >::graph () inline
Definition at line 434 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
concat_node
loco::TensorConcat* GraphTestcase< GraphCode::TensorConcat >::concat_node = nullptr
Definition at line 438 of file GraphTestcase.h.
lhs_node
loco::Pull* GraphTestcase< GraphCode::TensorConcat >::lhs_node = nullptr
Definition at line 436 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::TensorConcat >::push_node = nullptr
Definition at line 439 of file GraphTestcase.h.
rhs_node
loco::Pull* GraphTestcase< GraphCode::TensorConcat >::rhs_node = nullptr
Definition at line 437 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h