ONE - On-device Neural Engine: onert::exec::Executors::EdgeTensor Class Reference
onert::exec::Executors::EdgeTensor Class Reference
Public Member Functions
EdgeTensor (const ir::OperandInfo &info, ir::Layout layout)
~EdgeTensor ()=default
void allocate_buffer ()
void increase_ref ()
void decrease_ref ()
Public Member Functions inherited from onert::backend::builtin::IOTensor
IOTensor (const ir::OperandInfo &info, ir::Layout layout)
~IOTensor ()
void setTensor (IPortableTensor *tensor)
void setUserTensor (uint8_t *buffer, size_t size)
const ir::OperandInfo & orig_info () const
ir::Layout orig_layout () const
uint8_t * buffer () const override
size_t total_size () const override
size_t calcOffset (const ir::Coordinates &coords) const override
ir::Layout layout () const override
ir::DataType data_type () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
void set_dynamic () override
set this tensor dynamic
ir::Shape getShape () const override
Get ir::Shape of tensor.
void setShape (const ir::Shape &shape) override
Set the shape of tenser to new_shape.
bool is_constant () const override
Return true if the tensor is constant.
bool applyShape (const ir::Shape &shape) override
Set the shape to shape and possibly re-allocate the buffer.
void setShapeOfIPortableTensor (const ir::Shape &shape)
Public Member Functions inherited from onert::backend::IPortableTensor
IPortableTensor (const ir::OperandInfo &info)
virtual ~IPortableTensor ()
virtual const ir::Sparsity * sparsity () const
const ir::OperandInfo & get_info () const
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const final
void access (const std::function< void(ITensor &tensor)> &fn) final
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::IPortableTensor
ir::OperandInfo _info
Detailed Description
Definition at line 63 of file Executors.cc.
Constructor & Destructor Documentation
EdgeTensor()
onert::exec::Executors::EdgeTensor::EdgeTensor (const ir::OperandInfo & info, ir::Layout layout) inline
Definition at line 66 of file Executors.cc.
    : backend::builtin::IOTensor(info, layout), _buffer{nullptr}, _ref_count{0}
  {
  }
~EdgeTensor()
onert::exec::Executors::EdgeTensor::~EdgeTensor () default
Member Function Documentation
allocate_buffer()
void onert::exec::Executors::EdgeTensor::allocate_buffer () inline
Definition at line 72 of file Executors.cc.
  {
    const auto total_size = orig_info().total_size();
    _buffer = std::make_unique<uint8_t[]>(total_size);
    _ref_count = 1;
    // NOTE Executor's inputs/outputs are always IPortableTensor. If backend of inputs/outputs
    //      is using tensor that does not inherit IPortableTensor, Permute operation is added
    //      and all inputs/outputs become IPortableTensor at compile stage.
    //      This allows user's buffers to be set to inputs/outputs of executors.
    setUserTensor(_buffer.get(), total_size);
  }
References onert::backend::builtin::IOTensor::orig_info(), onert::backend::builtin::IOTensor::setUserTensor(), onert::ir::OperandInfo::total_size(), and onert::backend::builtin::IOTensor::total_size().
decrease_ref()
void onert::exec::Executors::EdgeTensor::decrease_ref () inline
Definition at line 87 of file Executors.cc.
  {
    assert(_ref_count > 0);
    _ref_count--;
    if (_ref_count == 0)
    {
      _buffer.reset();
      setUserTensor(nullptr, orig_info().total_size());
    }
  }
References onert::backend::builtin::IOTensor::orig_info(), onert::backend::builtin::IOTensor::setUserTensor(), and onert::backend::builtin::IOTensor::total_size().
increase_ref()
void onert::exec::Executors::EdgeTensor::increase_ref () inline
Definition at line 85 of file Executors.cc.
{ _ref_count++; }
The documentation for this class was generated from the following file:
runtime/onert/core/src/exec/Executors.cc