ONE - On-device Neural Engine: onert::util::MinMaxMap< N, Hash > Class Template Reference
onert::util::MinMaxMap< N, Hash > Class Template Reference
#include <MinMaxMap.h>
Public Member Functions
void append (N node, float min, float max)
auto begin () const
auto end () const
auto size () const
Detailed Description
template<typename N, typename Hash = std::hash<N>>
class onert::util::MinMaxMap< N, Hash >
Definition at line 28 of file MinMaxMap.h.
Member Function Documentation
append()
template<typename N , typename Hash = std::hash<N>> void onert::util::MinMaxMap< N, Hash >::append (N node, float min, float max) inline
Definition at line 36 of file MinMaxMap.h.
{ _minmax_map[node] = {min, max}; }
Referenced by onert::exec::MinMaxRecorder::handleJobEnd(), and onert::exec::MinMaxRecorder::handleSubgraphBegin().
begin()
template<typename N , typename Hash = std::hash<N>> auto onert::util::MinMaxMap< N, Hash >::begin () const inline
Definition at line 37 of file MinMaxMap.h.
{ return _minmax_map.begin(); }
end()
template<typename N , typename Hash = std::hash<N>> auto onert::util::MinMaxMap< N, Hash >::end () const inline
Definition at line 38 of file MinMaxMap.h.
{ return _minmax_map.end(); }
size()
template<typename N , typename Hash = std::hash<N>> auto onert::util::MinMaxMap< N, Hash >::size () const inline
Definition at line 39 of file MinMaxMap.h.
{ return _minmax_map.size(); }
Referenced by onert::exec::RawMinMaxDumper::dump().
The documentation for this class was generated from the following file:
runtime/onert/core/include/util/MinMaxMap.h