ONE - On-device Neural Engine: luci_interpreter::kernels::PRelu Class Reference
luci_interpreter::kernels::PRelu Class Reference
#include <PRelu.h>
Public Member Functions
PRelu (const Tensor *input, const Tensor *alpha, Tensor *output)
~PRelu ()
const Tensor * input () const
const Tensor * alpha () const
Tensor * output () const
void configure () override
void execute () const override
PRelu (const Tensor *input, const Tensor *alpha, Tensor *output)
~PRelu ()
const Tensor * input () const
const Tensor * alpha () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 30 of file PRelu.h.
Constructor & Destructor Documentation
PRelu() [1/2]
luci_interpreter::kernels::PRelu::PRelu (const Tensor * input, const Tensor * alpha, Tensor * output)
Definition at line 33 of file PRelu.cpp.
  : Kernel({input, alpha}, {output})
{
}
References alpha(), and input().
~PRelu() [1/2]
luci_interpreter::kernels::PRelu::~PRelu ()
Definition at line 38 of file PRelu.cpp.
{
  // Destructor declared to delete vector of alpha quantized data properly
}
PRelu() [2/2]
luci_interpreter::kernels::PRelu::PRelu (const Tensor * input, const Tensor * alpha, Tensor * output)
~PRelu() [2/2]
luci_interpreter::kernels::PRelu::~PRelu ()
Member Function Documentation
alpha() [1/2]
const Tensor * luci_interpreter::kernels::PRelu::alpha () const inline
Definition at line 38 of file PRelu.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and PRelu().
alpha() [2/2]
const Tensor * luci_interpreter::kernels::PRelu::alpha () const inline
Definition at line 38 of file PRelu.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::PRelu::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 43 of file PRelu.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(alpha()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(input()->scales().size() <= 1);
  LUCI_INTERPRETER_CHECK(output()->scales().size() <= 1);
  if (input()->element_type() == DataType::U8)
  {
    LUCI_INTERPRETER_CHECK(alpha()->scales().size() <= 1); // remove when CWQ kernel arrives
    _alpha_multipliers.resize(1);
    double alpha_multiplier = input()->scale() * alpha()->scale() / output()->scale();
    quantizeMultiplier(alpha_multiplier, &_alpha_multipliers[0].multiplier,
                       &_alpha_multipliers[0].shift);
    double identity_multiplier = input()->scale() / output()->scale();
    quantizeMultiplier(identity_multiplier, &_output_multiplier_identity, &_output_shift_identity);
  }
  else if (input()->element_type() == DataType::S16)
  {
    // Common check for correctness of quant params
    LUCI_INTERPRETER_CHECK(input()->zero_point() == 0 && output()->zero_point() == 0);
    for (size_t channel = 0; channel < alpha()->zero_points().size(); ++channel)
    {
      LUCI_INTERPRETER_CHECK(alpha()->zero_points()[channel] == 0);
    }
    // PRelu specific checks for CWQ
    LUCI_INTERPRETER_CHECK(alpha()->quantized_dimension() == alpha()->shape().num_dims() - 1);
    LUCI_INTERPRETER_CHECK(static_cast<int32_t>(alpha()->scales().size()) ==
                           alpha()->shape().dim(alpha()->quantized_dimension()));
    LUCI_INTERPRETER_CHECK(alpha()->shape().num_elements() ==
                           input()->shape().dim(input()->shape().num_dims() - 1));
    // all dimension of alpha except last one should be size 1
    for (int dim = 0; dim < alpha()->shape().num_dims() - 1; ++dim)
    {
      LUCI_INTERPRETER_CHECK(alpha()->shape().dim(dim) == 1);
    }
    std::vector<double> real_multipliers =
      getQuantizedConvolutionMultiplers(input()->scale(), alpha()->scales(), output()->scale());
    _alpha_multipliers = quantizeMultipliers(real_multipliers);
    double identity_multiplier = input()->scale() / output()->scale();
    quantizeMultiplier(identity_multiplier, &_output_multiplier_identity, &_output_shift_identity);
  }
  output()->resize(calculateShapeForBroadcast(input()->shape(), alpha()->shape()));
}
References alpha(), luci_interpreter::kernels::calculateShapeForBroadcast(), luci_interpreter::kernels::getQuantizedConvolutionMultiplers(), input(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::kernels::quantizeMultiplier(), luci_interpreter::kernels::quantizeMultipliers(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::scale(), luci_interpreter::Tensor::shape(), luci_interpreter::size(), and luci_interpreter::Tensor::zero_points().
configure() [2/2]
void luci_interpreter::kernels::PRelu::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::PRelu::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 92 of file PRelu.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    case DataType::S16:
      evalQuantizedS16();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::PRelu::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::PRelu::input () const inline
Definition at line 37 of file PRelu.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and PRelu().
input() [2/2]
const Tensor * luci_interpreter::kernels::PRelu::input () const inline
Definition at line 37 of file PRelu.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::PRelu::output () const inline
Definition at line 39 of file PRelu.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::PRelu::output () const inline
Definition at line 39 of file PRelu.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/PRelu.h
onert-micro/luci-interpreter/src/kernels/PRelu.h
compiler/luci-interpreter/src/kernels/PRelu.cpp
onert-micro/luci-interpreter/src/kernels/PRelu.cpp