ONE - On-device Neural Engine: coco::FeatureLayouts::BCHW Class Reference
coco::FeatureLayouts::BCHW Class Reference final
BCHW Feature Layout.
#include <FeatureLayouts.h>
Public Member Functions
const FeatureLayout::ID * id (void) const override
const FeatureShape & shape (void) const override
ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override
Public Member Functions inherited from coco::FeatureLayout
virtual ~FeatureLayout ()=default
virtual const ID * id (void) const =0
virtual const FeatureShape & shape (void) const =0
uint32_t batch (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
virtual ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const FeatureLayout::ID * uid (void)
static std::unique_ptr< BCHW > create (const nncc::core::ADT::feature::Shape &shape)
Detailed Description
BCHW Feature Layout.
Definition at line 35 of file FeatureLayouts.h.
Member Function Documentation
at()
ElemID coco::FeatureLayouts::BCHW::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::FeatureLayout.
Definition at line 43 of file FeatureLayouts.cpp.
{
  static CHWLayout l;
  uint32_t offset = 0;
  offset += b * num_elements(_shape);
  offset += l.offset(_shape, ch, row, col);
  return ElemID{offset};
}
References nncc::core::ADT::feature::num_elements(), and offset().
create()
std::unique_ptr< BCHW > coco::FeatureLayouts::BCHW::create (const nncc::core::ADT::feature::Shape & shape) static
Definition at line 53 of file FeatureLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<BCHW>{new BCHW{FeatureShape{shape}}};
}
References shape().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
id()
const FeatureLayout::ID * coco::FeatureLayouts::BCHW::id (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 45 of file FeatureLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
shape()
const FeatureShape & coco::FeatureLayouts::BCHW::shape (void) const inline override virtual
Implements coco::FeatureLayout.
Definition at line 47 of file FeatureLayouts.h.
{ return _shape; }
Referenced by create().
uid()
const FeatureLayout::ID * coco::FeatureLayouts::BCHW::uid (void) static
Definition at line 34 of file FeatureLayouts.cpp.
{
  struct LayoutID final : public FeatureLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/FeatureLayouts.h
compiler/coco/core/src/IR/FeatureLayouts.cpp