ONE - On-device Neural Engine: loco::TensorShape Class Reference
loco::TensorShape Class Reference
#include <TensorShape.h>
Public Member Functions
TensorShape ()=default
TensorShape (std::initializer_list< Dimension > dims)
uint32_t rank (void) const
void rank (uint32_t r)
const Dimension & dim (uint32_t axis) const
Dimension & dim (uint32_t axis)
Detailed Description
Definition at line 28 of file TensorShape.h.
Constructor & Destructor Documentation
TensorShape() [1/2]
loco::TensorShape::TensorShape () default
TensorShape() [2/2]
loco::TensorShape::TensorShape (std::initializer_list< Dimension > dims) inline
Definition at line 32 of file TensorShape.h.
: _dims(dims.begin(), dims.end()) {}
Member Function Documentation
dim() [1/2]
Dimension & loco::TensorShape::dim (uint32_t axis) inline
Definition at line 39 of file TensorShape.h.
{ return _dims.at(axis); }
dim() [2/2]
const Dimension & loco::TensorShape::dim (uint32_t axis) const inline
Definition at line 38 of file TensorShape.h.
{ return _dims.at(axis); }
Referenced by moco::as_feature_shape(), moco::as_tensor_shape(), onert::backend::acl_common::asTensorShape(), luci::cal_offset(), luci::sinf::circle_shape(), loco::element_count(), luci::get_channel_dim_index(), locoex::COpShapeInferenceRule::infer(), moco::new_const(), loco::operator<<(), loco::operator==(), luci::CircleShapeInferencePass::run(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingDecoder< Domain::Matrix >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::Matrix >::shape(), moco::TensorPackEnumerator::start(), moco::tensor_shape(), exo::to_shape_description(), luci::to_shape_description(), moco::valid_shape_for_constfold_binary_op(), and moco::window_of().
rank() [1/2]
void loco::TensorShape::rank (uint32_t r) inline
Definition at line 36 of file TensorShape.h.
{ _dims.resize(r); }
rank() [2/2]
uint32_t loco::TensorShape::rank (void) const inline
Definition at line 35 of file TensorShape.h.
{ return _dims.size(); }
Referenced by moco::as_feature_shape(), moco::as_tensor_shape(), onert::backend::acl_common::asTensorShape(), moco::tf::BroadcastFunctor::build(), luci::sinf::circle_shape(), loco::element_count(), locoex::COpShapeInferenceRule::infer(), luci::infer_output_shape(), moco::new_const(), loco::operator<<(), loco::operator==(), luci::CircleShapeInferencePass::run(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingDecoder< Domain::Filter >::shape(), moco::TensorPackEnumerator::shape(), loco::PermutingDecoder< Domain::Matrix >::shape(), moco::TensorSliceEnumerator::shape(), moco::tensor_shape(), exo::to_shape_description(), luci::to_shape_description(), and moco::valid_shape_for_constfold_binary_op().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/TensorShape.h