ONE - On-device Neural Engine: luci_interpreter::kernels::Softmax Class Reference
luci_interpreter::kernels::Softmax Class Reference
#include <Softmax.h>
Public Member Functions
Softmax (const Tensor *input, Tensor *output, const SoftmaxParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Softmax (const Tensor *input, Tensor *output, const SoftmaxParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< SoftmaxParams >
const SoftmaxParams & params () const
const SoftmaxParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< SoftmaxParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SoftmaxParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SoftmaxParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< SoftmaxParams >
const SoftmaxParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Softmax.h.
Constructor & Destructor Documentation
Softmax() [1/2]
luci_interpreter::kernels::Softmax::Softmax (const Tensor * input, Tensor * output, const SoftmaxParams & params)
Definition at line 32 of file Softmax.cpp.
  : KernelWithParams<SoftmaxParams>({input}, {output}, params)
{
}
References input().
Softmax() [2/2]
luci_interpreter::kernels::Softmax::Softmax (const Tensor * input, Tensor * output, const SoftmaxParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Softmax::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file Softmax.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() >= 1);
  if (input()->element_type() == DataType::U8 || input()->element_type() == DataType::S8)
  {
    LUCI_INTERPRETER_CHECK(input()->element_type() == DataType::S8 || output()->zero_point() == 0);
    LUCI_INTERPRETER_CHECK(input()->element_type() == DataType::U8 ||
                           output()->zero_point() == std::numeric_limits<int8_t>::min());
    tflite::SoftmaxParams op_params{};
    op_params.table = _table;
    luci_interpreter_pal::PopulateSoftmaxLookupTable(&op_params, input()->scale(), params().beta);
  }
  output()->resize(input()->shape());
}
References input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::KernelWithParams< SoftmaxParams >::params(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::Softmax::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Softmax::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 53 of file Softmax.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::S8:
      evalQuantized<int8_t>();
      break;
    case DataType::U8:
      evalQuantized<uint8_t>();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Softmax::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Softmax::input () const inline
Definition at line 33 of file Softmax.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Softmax().
input() [2/2]
const Tensor * luci_interpreter::kernels::Softmax::input () const inline
Definition at line 33 of file Softmax.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Softmax::output () const inline
Definition at line 34 of file Softmax.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Softmax::output () const inline
Definition at line 34 of file Softmax.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Softmax.h
onert-micro/luci-interpreter/src/kernels/Softmax.h
compiler/luci-interpreter/src/kernels/Softmax.cpp
onert-micro/luci-interpreter/src/kernels/Softmax.cpp