ONE - On-device Neural Engine: enco::MemoryContext Class Reference
enco::MemoryContext Class Reference
Record C/C++ expression that denotes the base and size of memory region dedicated to each bag.
#include <MemoryContext.h>
Public Member Functions
bool member (const coco::Bag *bag) const
Check whether a base/size expression for a given bag.
void base (const coco::Bag *bag, const std::string &exp)
void size (const coco::Bag *bag, const std::string &exp)
const std::string & base (const coco::Bag *bag) const
const std::string & size (const coco::Bag *bag) const
Detailed Description
Record C/C++ expression that denotes the base and size of memory region dedicated to each bag.
Definition at line 32 of file MemoryContext.h.
Member Function Documentation
base() [1/2]
const std::string & enco::MemoryContext::base (const coco::Bag * bag) const inline
Definition at line 45 of file MemoryContext.h.
{ return _base.at(bag); }
base() [2/2]
void enco::MemoryContext::base (const coco::Bag * bag, const std::string & exp)
Definition at line 37 of file MemoryContext.cpp.
{ _base[bag] = exp; }
Referenced by enco::CppCode::dump().
member()
bool enco::MemoryContext::member (const coco::Bag * bag) const
Check whether a base/size expression for a given bag.
Definition at line 24 of file MemoryContext.cpp.
{
  // NOTE _base and _size SHOULD BE consistent
  if (_base.find(bag) != _base.end())
  {
    assert(_size.find(bag) != _size.end());
    return true;
  }
  assert(_size.find(bag) == _size.end());
  return false;
}
Referenced by enco::CppCode::dump().
size() [1/2]
const std::string & enco::MemoryContext::size (const coco::Bag * bag) const inline
Definition at line 46 of file MemoryContext.h.
{ return _size.at(bag); }
size() [2/2]
void enco::MemoryContext::size (const coco::Bag * bag, const std::string & exp)
Definition at line 38 of file MemoryContext.cpp.
{ _size[bag] = exp; }
Referenced by enco::CppCode::dump().
The documentation for this class was generated from the following files:
compiler/enco/core/src/CppGen/MemoryContext.h
compiler/enco/core/src/CppGen/MemoryContext.cpp