ONE - On-device Neural Engine: exo::CanonicalNodeConverter< CanonicalType > Class Template Reference
exo::CanonicalNodeConverter< CanonicalType > Class Template Reference abstract
Class to convert a canonical node to TFL node.
#include <CanonicalNodeConverter.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Protected Member Functions
virtual bool convert (CanonicalType *node)=0
Detailed Description
template<typename CanonicalType>
class exo::CanonicalNodeConverter< CanonicalType >
Class to convert a canonical node to TFL node.
TODO Find a better name
Definition at line 34 of file CanonicalNodeConverter.h.
Member Function Documentation
convert()
template<typename CanonicalType > virtual bool exo::CanonicalNodeConverter< CanonicalType >::convert (CanonicalType * node) protected pure virtual
Implemented in exo::AvgPool2DConverter, exo::ConstGenConverter, exo::Conv2DConverter, exo::DepthwiseConv2DConverter, exo::EltwiseAddConverter, exo::EltwiseDivConverter, exo::EltwiseMaxConverter, exo::EltwiseMulConverter, exo::EltwiseSqrtConverter, exo::EltwiseSubConverter, exo::FeatureBiasAddConverter, exo::MatMulConverter, exo::MaxPool2DConverter, exo::ReluConverter, exo::Relu6Converter, exo::TensorConcatConverter, exo::TensorReduceConverter, exo::TensorTransposeConverter, and exo::TransposedConv2DConverter.
name()
template<typename CanonicalType > virtual const char * exo::CanonicalNodeConverter< CanonicalType >::name (void) const inline virtual
Reimplemented from logo::Pass.
Reimplemented in exo::AvgPool2DConverter, exo::ConstGenConverter, exo::Conv2DConverter, exo::DepthwiseConv2DConverter, exo::EltwiseAddConverter, exo::EltwiseDivConverter, exo::EltwiseMaxConverter, exo::EltwiseMulConverter, exo::EltwiseSqrtConverter, exo::EltwiseSubConverter, exo::FeatureBiasAddConverter, exo::MatMulConverter, exo::MaxPool2DConverter, exo::Relu6Converter, exo::ReluConverter, exo::TensorConcatConverter, exo::TensorReduceConverter, exo::TensorTransposeConverter, and exo::TransposedConv2DConverter.
Definition at line 37 of file CanonicalNodeConverter.h.
{ return nullptr; }
run()
template<typename CanonicalType > bool exo::CanonicalNodeConverter< CanonicalType >::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 47 of file CanonicalNodeConverter.h.
{
  auto active_nodes = loco::active_nodes(loco::output_nodes(graph));
  bool changed = false;
  for (auto node : active_nodes)
  {
    // TODO Generalize this to all loco dialects
    if (node->dialect() == loco::CanonicalDialect::get())
    {
      auto the_node = dynamic_cast<CanonicalType *>(node);
      if (the_node != nullptr)
      {
        if (convert(the_node))
          changed = true;
      }
    }
  }
  return changed;
}
References loco::active_nodes(), loco::CanonicalDialect::get(), and loco::output_nodes().
The documentation for this class was generated from the following file:
compiler/exo/src/Conversion/CanonicalNodeConverter.h