ONE - On-device Neural Engine: luci_interpreter::kernels::SelectV2 Class Reference
luci_interpreter::kernels::SelectV2 Class Reference
#include <SelectV2.h>
Public Member Functions
SelectV2 (const Tensor *cond, const Tensor *t, const Tensor *e, Tensor *output)
const Tensor * condition () const
const Tensor * t () const
const Tensor * e () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file SelectV2.h.
Constructor & Destructor Documentation
SelectV2()
luci_interpreter::kernels::SelectV2::SelectV2 (const Tensor * cond, const Tensor * t, const Tensor * e, Tensor * output)
Definition at line 32 of file SelectV2.cpp.
  : Kernel({condition, t, e}, {output})
{
}
References condition(), e(), and t().
Member Function Documentation
condition()
const Tensor * luci_interpreter::kernels::SelectV2::condition () const inline
Definition at line 33 of file SelectV2.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SelectV2().
configure()
void luci_interpreter::kernels::SelectV2::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file SelectV2.cpp.
{
  LUCI_INTERPRETER_CHECK(condition()->element_type() == DataType::BOOL);
  LUCI_INTERPRETER_CHECK(t()->element_type() == e()->element_type());
  LUCI_INTERPRETER_CHECK(t()->element_type() == output()->element_type());
  auto cond_shape = condition()->shape();
  auto t_shape = t()->shape();
  auto e_shape = e()->shape();
  output()->resize(
    calculateShapeForBroadcast(cond_shape, calculateShapeForBroadcast(t_shape, e_shape)));
}
References luci_interpreter::kernels::calculateShapeForBroadcast(), condition(), e(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), and t().
e()
const Tensor * luci_interpreter::kernels::SelectV2::e () const inline
Definition at line 35 of file SelectV2.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SelectV2().
execute()
void luci_interpreter::kernels::SelectV2::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 51 of file SelectV2.cpp.
{
  switch (t()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("luci-intp SelectV2 unsupported type.");
  }
}
References t().
output()
Tensor * luci_interpreter::kernels::SelectV2::output () const inline
Definition at line 36 of file SelectV2.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
t()
const Tensor * luci_interpreter::kernels::SelectV2::t () const inline
Definition at line 34 of file SelectV2.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SelectV2().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/SelectV2.h
compiler/luci-interpreter/src/kernels/SelectV2.cpp