ONE - On-device Neural Engine: onert_micro::core::reader::OMCircleReader Class Reference
onert_micro::core::reader::OMCircleReader Class Reference
Loads Circle file and provides helpers to access attributes.
#include <OMCircleReader.h>
Public Member Functions
OMCircleReader ()=default
OMCircleReader (const OMCircleReader &)=delete
OMCircleReader (OMCircleReader &&)=default
OMCircleReader & operator= (const OMCircleReader &)=delete
OMCircleReader && operator= (const OMCircleReader &&)=delete
~OMCircleReader ()=default
const CircleOperatorCodes * opcodes () const
const CircleBuffers * buffers () const
const CircleTensors * tensors () const
const CircleOperators * operators () const
const CircleValues * inputs () const
const CircleValues * outputs () const
const circle::DataFormat data_format () const
const CircleMetadataSet * metadata () const
uint32_t num_subgraph () const
circle::BuiltinOperator builtin_code (const circle::Operator *op) const
OMStatus parse (const char *model_ptr)
OMStatus select_subgraph (uint32_t subgraph)
uint32_t get_current_subgraph_index () const
bool isConstTensor (uint32_t tensor_index)
Detailed Description
Loads Circle file and provides helpers to access attributes.
Definition at line 41 of file OMCircleReader.h.
Constructor & Destructor Documentation
OMCircleReader() [1/3]
onert_micro::core::reader::OMCircleReader::OMCircleReader () default
OMCircleReader() [2/3]
onert_micro::core::reader::OMCircleReader::OMCircleReader (const OMCircleReader &) delete
OMCircleReader() [3/3]
onert_micro::core::reader::OMCircleReader::OMCircleReader (OMCircleReader &&) default
~OMCircleReader()
onert_micro::core::reader::OMCircleReader::~OMCircleReader () default
Member Function Documentation
buffers()
const CircleBuffers * onert_micro::core::reader::OMCircleReader::buffers () const inline
Definition at line 53 of file OMCircleReader.h.
{ return _model->buffers(); }
Referenced by onert_micro::core::OMRuntimeContext::getConstDataByTensorIndex().
builtin_code()
circle::BuiltinOperator OMCircleReader::builtin_code (const circle::Operator * op) const
Definition at line 40 of file OMCircleReader.cpp.
{
  assert(op != nullptr);
  const auto op_codes = opcodes();
  uint32_t index = op->opcode_index();
  assert(index < op_codes->size());
  const auto opcode = op_codes->operator[](index);
  assert(opcode != nullptr);
  return builtin_code_neutral(opcode);
}
References opcodes(), and size.
data_format()
const circle::DataFormat onert_micro::core::reader::OMCircleReader::data_format () const inline
Definition at line 58 of file OMCircleReader.h.
{ return _current_subgraph->data_format(); }
get_current_subgraph_index()
uint32_t onert_micro::core::reader::OMCircleReader::get_current_subgraph_index () const inline
Definition at line 67 of file OMCircleReader.h.
{ return _current_subgraph_index; }
inputs()
const CircleValues * onert_micro::core::reader::OMCircleReader::inputs () const inline
Definition at line 56 of file OMCircleReader.h.
{ return _current_subgraph->inputs(); }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs(), onert_micro::core::OMRuntimeContext::getCircleInputs(), onert_micro::core::OMRuntimeContext::getGraphInputTensorIndex(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_inputs().
isConstTensor()
bool OMCircleReader::isConstTensor (uint32_t tensor_index)
Definition at line 87 of file OMCircleReader.cpp.
{
  if (tensor_index == -1)
    return false;
  const auto tmp_tensor = _current_subgraph->tensors()->operator[](tensor_index);
  return _model->buffers()->operator[](tmp_tensor->buffer())->data() != nullptr;
}
Referenced by onert_micro::core::OMRuntimeContext::isConstTensor().
metadata()
const CircleMetadataSet * onert_micro::core::reader::OMCircleReader::metadata () const inline
Definition at line 59 of file OMCircleReader.h.
{ return _model->metadata(); }
num_subgraph()
uint32_t onert_micro::core::reader::OMCircleReader::num_subgraph () const inline
Definition at line 61 of file OMCircleReader.h.
{ return _model->subgraphs()->size(); }
Referenced by onert_micro::core::OMRuntimeModule::importModel(), and select_subgraph().
opcodes()
const CircleOperatorCodes * onert_micro::core::reader::OMCircleReader::opcodes () const inline
Definition at line 52 of file OMCircleReader.h.
{ return _model->operator_codes(); }
Referenced by builtin_code(), and onert_micro::core::OMRuntimeContext::getCircleOpcodes().
operator=() [1/2]
OMCircleReader && onert_micro::core::reader::OMCircleReader::operator= (const OMCircleReader &&) delete
operator=() [2/2]
OMCircleReader & onert_micro::core::reader::OMCircleReader::operator= (const OMCircleReader &) delete
operators()
const CircleOperators * onert_micro::core::reader::OMCircleReader::operators () const inline
Definition at line 55 of file OMCircleReader.h.
{ return _current_subgraph->operators(); }
Referenced by onert_micro::core::OMRuntimeContext::getCircleOperatorAt(), and onert_micro::core::OMRuntimeContext::getCircleOperators().
outputs()
const CircleValues * onert_micro::core::reader::OMCircleReader::outputs () const inline
Definition at line 57 of file OMCircleReader.h.
{ return _current_subgraph->outputs(); }
Referenced by validate_onnx2circle.OnnxRunner::get_outputs(), onert_micro::core::OMRuntimeContext::getCircleOutputs(), onert_micro::core::OMRuntimeContext::getGraphOutputTensorIndex(), package.libnnfw_api_pybind.nnfw_session_wrapper::inference(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_outputs().
parse()
OMStatus OMCircleReader::parse (const char * model_ptr)
Definition at line 55 of file OMCircleReader.cpp.
{
  assert(_model == nullptr && "Already init _model");
  assert(model_ptr != nullptr && "Model pointer cannot be null");
  if (model_ptr == nullptr or _model != nullptr)
  {
    return UnknownError;
  }
  _model = circle::GetModel(model_ptr);
  return Ok;
}
References onert_micro::Ok, and onert_micro::UnknownError.
Referenced by onert_micro::core::OMRuntimeModule::importModel(), and onert_micro::core::OMRuntimeContext::setModel().
select_subgraph()
OMStatus OMCircleReader::select_subgraph (uint32_t subgraph)
Definition at line 69 of file OMCircleReader.cpp.
{
  if (num_subgraph() <= sgindex)
    return UnknownError;
  auto subgraphs = _model->subgraphs();
  if (subgraphs == nullptr)
    return UnknownError;
  _current_subgraph = subgraphs->Get(sgindex);
  if (_current_subgraph == nullptr)
    return UnknownError;
  _current_subgraph_index = sgindex;
  return Ok;
}
References num_subgraph(), onert_micro::Ok, and onert_micro::UnknownError.
Referenced by onert_micro::core::OMRuntimeContext::setModel().
tensors()
const CircleTensors * onert_micro::core::reader::OMCircleReader::tensors () const inline
Definition at line 54 of file OMCircleReader.h.
{ return _current_subgraph->tensors(); }
Referenced by onert_micro::core::OMRuntimeContext::getCircleTensors(), and onert_micro::core::OMRuntimeContext::getTensorByIndex().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/reader/OMCircleReader.h
onert-micro/onert-micro/src/core/reader/OMCircleReader.cpp