ONE - On-device Neural Engine: loco::TypeInferenceSession Class Reference
loco::TypeInferenceSession Class Reference
#include <TypeInference.h>
Public Member Functions
TypeInferenceSession (const TypeInferenceRule *rule)
bool to (Graph *g) const
Detailed Description
Definition at line 84 of file TypeInference.h.
Constructor & Destructor Documentation
TypeInferenceSession()
loco::TypeInferenceSession::TypeInferenceSession (const TypeInferenceRule * rule) inline
Definition at line 87 of file TypeInference.h.
                                                      : _rule{rule}
  {
    // DO NOTHING
  }
Member Function Documentation
to()
bool loco::TypeInferenceSession::to (Graph * g) const
Definition at line 61 of file TypeInference.cpp.
{
  bool changed = false;
  for (auto node : postorder_traversal(output_nodes(g)))
  {
    if (_rule->recognize(node->dialect()))
    {
      DataType dtype = DataType::Unknown;
      if (!dtype_known(node) && inputs_dtype_ready(node))
      {
        if (_rule->infer(node, dtype))
        {
          node->annot(std::make_unique<DataTypeAnnotation>(dtype));
          changed = true;
        }
      }
    }
  }
  return changed;
}
References loco::AnnotatedItem< Annotation >::annot(), loco::Node::dialect(), loco::dtype_known(), loco::TypeInferenceRule::infer(), loco::output_nodes(), loco::postorder_traversal(), and loco::TypeInferenceRule::recognize().
The documentation for this class was generated from the following files:
compiler/loco/include/loco/Service/TypeInference.h
compiler/loco/src/Service/TypeInference.cpp