ONE - On-device Neural Engine: nnfw::cker::train::DepthwiseConv Class Reference
nnfw::cker::train::DepthwiseConv Class Reference
#include <DepthwiseConv.h>
Public Member Functions
DepthwiseConv ()=default
template<typename T >
int64_t kPacketSize () const
int getThreadCount () const
template<typename T >
void backpropInput (const DepthwiseConvParams &params, const Shape &incoming_shape, const T *incoming_data, const Shape &filter_shape, const T *filter_data, T *padded_filter_data, const Shape &grad_shape, T *grad_data, bool pad_filter, T *filter_buffers_data, T *filter_dim_buffers_data)
template<typename T >
void backpropFilter (const DepthwiseConvParams &params, const Shape &incoming_shape, const T *incoming_data, const Shape &input_shape, const T *input_data, const Shape &filter_grad_shape, T *filter_grad_data, T *padded_filter_data, T *filter_buffers_data)
Detailed Description
Definition at line 31 of file DepthwiseConv.h.
Constructor & Destructor Documentation
DepthwiseConv()
nnfw::cker::train::DepthwiseConv::DepthwiseConv () default
Member Function Documentation
backpropFilter()
template<typename T > void nnfw::cker::train::DepthwiseConv::backpropFilter (const DepthwiseConvParams & params, const Shape & incoming_shape, const T * incoming_data, const Shape & input_shape, const T * input_data, const Shape & filter_grad_shape, T * filter_grad_data, T * padded_filter_data, T * filter_buffers_data) inline
Definition at line 81 of file DepthwiseConv.h.
  {
    if (params.stride_height != params.stride_width)
      throw std::runtime_error("Not support different length strides");
    const int batch = MatchingDim(incoming_shape, 0, input_shape, 0);
    const int input_depth = input_shape.Dims(3);
    const int output_depth = incoming_shape.Dims(3);
    const int incoming_height = incoming_shape.Dims(1);
    const int incoming_width = incoming_shape.Dims(2);
    const int input_height = input_shape.Dims(1);
    const int input_width = input_shape.Dims(2);
    const int stride = params.stride_height;
    const int depth_multiplier = params.depth_multiplier;
    const int filter_height = filter_grad_shape.Dims(1);
    const int filter_width = filter_grad_shape.Dims(2);
    const int pad_height = params.padding_values.height;
    const int pad_width = params.padding_values.width;
    depthwise_conv_op::LaunchDepthwiseConvBackpropFilterOp<Eigen::ThreadPoolDevice, T>()(
      batch, input_width, input_height, input_depth, filter_width, filter_height, depth_multiplier,
      stride, pad_width, pad_height, incoming_width, incoming_height, output_depth, incoming_data,
      input_data, filter_grad_data, padded_filter_data, filter_buffers_data);
  }
References nnfw::cker::DepthwiseConvParams::depth_multiplier, nnfw::cker::Shape::Dims(), nnfw::cker::PaddingValues::height, nnfw::cker::MatchingDim(), nnfw::cker::DepthwiseConvParams::padding_values, nnfw::cker::DepthwiseConvParams::stride_height, nnfw::cker::DepthwiseConvParams::stride_width, and nnfw::cker::PaddingValues::width.
backpropInput()
template<typename T > void nnfw::cker::train::DepthwiseConv::backpropInput (const DepthwiseConvParams & params, const Shape & incoming_shape, const T * incoming_data, const Shape & filter_shape, const T * filter_data, T * padded_filter_data, const Shape & grad_shape, T * grad_data, bool pad_filter, T * filter_buffers_data, T * filter_dim_buffers_data) inline
Definition at line 51 of file DepthwiseConv.h.
  {
    if (params.stride_height != params.stride_width)
      throw std::runtime_error("Not support different length strides");
    const int batch = MatchingDim(incoming_shape, 0, grad_shape, 0);
    const int input_depth = grad_shape.Dims(3);
    const int output_depth = incoming_shape.Dims(3);
    const int incoming_height = incoming_shape.Dims(1);
    const int incoming_width = incoming_shape.Dims(2);
    const int grad_height = grad_shape.Dims(1);
    const int grad_width = grad_shape.Dims(2);
    const int stride = params.stride_height;
    const int depth_multiplier = params.depth_multiplier;
    const int filter_height = filter_shape.Dims(1);
    const int filter_width = filter_shape.Dims(2);
    const int pad_height = params.padding_values.height;
    const int pad_width = params.padding_values.width;
    depthwise_conv_op::LaunchDepthwiseConvBackpropInputOp<Eigen::ThreadPoolDevice, T>()(
      batch, grad_height, grad_width, input_depth, filter_height, filter_width, depth_multiplier,
      stride, pad_height, pad_width, incoming_height, incoming_width, output_depth, incoming_data,
      filter_data, padded_filter_data, grad_data, pad_filter, filter_buffers_data,
      filter_dim_buffers_data);
  }
References nnfw::cker::DepthwiseConvParams::depth_multiplier, nnfw::cker::Shape::Dims(), nnfw::cker::PaddingValues::height, nnfw::cker::MatchingDim(), nnfw::cker::DepthwiseConvParams::padding_values, nnfw::cker::DepthwiseConvParams::stride_height, nnfw::cker::DepthwiseConvParams::stride_width, and nnfw::cker::PaddingValues::width.
getThreadCount()
int nnfw::cker::train::DepthwiseConv::getThreadCount () const inline
Definition at line 42 of file DepthwiseConv.h.
  {
    // NOTE The Eigen library uses both main thread as well as a thread pool.
    // Therefore, it needs to add an additional memory buffer for main thread.
    const Eigen::ThreadPoolDevice &d = *eigen_support::GetThreadPoolDevice();
    return d.numThreads() + 1;
  }
References nnfw::cker::eigen_support::GetThreadPoolDevice().
kPacketSize()
template<typename T > int64_t nnfw::cker::train::DepthwiseConv::kPacketSize () const inline
Definition at line 36 of file DepthwiseConv.h.
  {
    typedef typename Eigen::internal::packet_traits<T>::type Packet;
    return sizeof(Packet) / sizeof(T);
  }
The documentation for this class was generated from the following file:
compute/cker/include/cker/train/operation/DepthwiseConv.h