ONE - On-device Neural Engine: onert::backend::gpu_cl::KernelGenerator Class Reference
onert::backend::gpu_cl::KernelGenerator Class Reference
#include <KernelGenerator.h>
Public Member Functions
KernelGenerator (const ir::Graph &graph, const std::shared_ptr< TensorBuilder > &tensor_builder, const std::shared_ptr< TensorRegistry > &tensor_reg, const std::shared_ptr< tflite::gpu::cl::CreationContext > &creation_context)
std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind) override
void get_operation (FunctionMap &Functions)
Public Member Functions inherited from onert::backend::basic::KernelGeneratorBase
virtual ~KernelGeneratorBase ()=default
KernelGeneratorBase (const ir::Graph &graph)
virtual std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind)=0
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Protected Member Functions inherited from onert::backend::basic::KernelGeneratorBase
std::unique_ptr< exec::IFunction > releaseFunction ()
Protected Attributes inherited from onert::backend::basic::KernelGeneratorBase
const ir::Graph & _graph
std::unique_ptr< exec::IFunction > _return_fn
Detailed Description
Definition at line 41 of file KernelGenerator.h.
Constructor & Destructor Documentation
KernelGenerator()
onert::backend::gpu_cl::KernelGenerator::KernelGenerator (const ir::Graph & graph, const std::shared_ptr< TensorBuilder > & tensor_builder, const std::shared_ptr< TensorRegistry > & tensor_reg, const std::shared_ptr< tflite::gpu::cl::CreationContext > & creation_context)
Definition at line 209 of file KernelGenerator.cc.
  : basic::KernelGeneratorBase{graph}, _ctx(graph.operands()),
    _operations_ctx(graph.operations()), _current_layout{graph.layout()},
    _tensor_builder(tensor_builder), _tensor_reg(tensor_reg), _creation_context(creation_context)
{
}
Member Function Documentation
generate()
std::unique_ptr< exec::FunctionSequence > onert::backend::gpu_cl::KernelGenerator::generate (ir::OperationIndex ind) override virtual
Implements onert::backend::basic::KernelGeneratorBase.
Definition at line 219 of file KernelGenerator.cc.
{
  auto fn_seq = std::make_unique<exec::FunctionSequence>();
  fn_seq->enableDynamicShapeInferer(false);
  _operation_index = ind;
  const auto &op = _graph.operations().at(ind);
  op.accept(*this);
  fn_seq->append(releaseFunction());
  return fn_seq;
}
References onert::backend::basic::KernelGeneratorBase::_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::Graph::operations(), and onert::backend::basic::KernelGeneratorBase::releaseFunction().
get_operation()
void onert::backend::gpu_cl::KernelGenerator::get_operation (FunctionMap & Functions)
Definition at line 70 of file KernelGenerator.cc.
{
  size_t size = _nodes.size();
  size_t i = 0;
  for (auto &it : Functions)
  {
    auto index = it.first;
    auto node_index = _operation_indexes[i];
    while (index == node_index)
    {
      auto &fn_seq = it.second;
      auto &node = _nodes[i++];
      for (size_t j = 0; j < node.inputs.size(); ++j)
      {
        uint32_t idx = node.inputs[j];
        node.cl_operation.GetGpuOperation().SetSrc(
          _tensor_reg->getClTensor(ir::OperandIndex{idx})->handle(), j);
      }
      for (size_t j = 0; j < node.outputs.size(); ++j)
      {
        uint32_t idx = node.outputs[j];
        node.cl_operation.GetGpuOperation().SetDst(
          _tensor_reg->getClTensor(ir::OperandIndex{idx})->handle(), j);
      }
      fn_seq->iterate([&](exec::IFunction &ifunc) {
        static_cast<ClFunction &>(ifunc).add_operation(&node.cl_operation);
      });
      if (i == size)
      {
        break;
      }
      node_index = _operation_indexes[i];
    }
    if (i == size)
    {
      break;
    }
  }
}
The documentation for this class was generated from the following files:
runtime/onert/backend/gpu_cl/KernelGenerator.h
runtime/onert/backend/gpu_cl/KernelGenerator.cc