ONE - On-device Neural Engine: loco::DepthwiseFilterShape Class Reference
loco::DepthwiseFilterShape Class Reference final
DepthwiseFilter Shape.
#include <DepthwiseFilterShape.h>
Public Member Functions
DepthwiseFilterShape ()=default
const Dimension & depth (void) const
Dimension & depth (void)
const Dimension & multiplier (void) const
Dimension & multiplier (void)
const Dimension & height (void) const
Dimension & height (void)
const Dimension & width (void) const
Dimension & width (void)
Detailed Description
DepthwiseFilter Shape.
This class describes the shape of depthwise filter, which is an input of depthwise 2D convolutional operation.
depth() refers to expected channel depth of matching input multiplier() refers to number of traverse for one input height() refers to the height of 2D weights width() refers to the width of 2D weights
Definition at line 36 of file DepthwiseFilterShape.h.
Constructor & Destructor Documentation
DepthwiseFilterShape()
loco::DepthwiseFilterShape::DepthwiseFilterShape () default
Member Function Documentation
depth() [1/2]
Dimension & loco::DepthwiseFilterShape::depth (void) inline
Definition at line 43 of file DepthwiseFilterShape.h.
{ return _depth; }
depth() [2/2]
const Dimension & loco::DepthwiseFilterShape::depth (void) const inline
Definition at line 42 of file DepthwiseFilterShape.h.
{ return _depth; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), and exo::to_shape_description().
height() [1/2]
Dimension & loco::DepthwiseFilterShape::height (void) inline
Definition at line 49 of file DepthwiseFilterShape.h.
{ return _height; }
height() [2/2]
const Dimension & loco::DepthwiseFilterShape::height (void) const inline
Definition at line 48 of file DepthwiseFilterShape.h.
{ return _height; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), and exo::to_shape_description().
multiplier() [1/2]
Dimension & loco::DepthwiseFilterShape::multiplier (void) inline
Definition at line 46 of file DepthwiseFilterShape.h.
{ return _multiplier; }
multiplier() [2/2]
const Dimension & loco::DepthwiseFilterShape::multiplier (void) const inline
Definition at line 45 of file DepthwiseFilterShape.h.
{ return _multiplier; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), and exo::to_shape_description().
width() [1/2]
Dimension & loco::DepthwiseFilterShape::width (void) inline
Definition at line 52 of file DepthwiseFilterShape.h.
{ return _width; }
width() [2/2]
const Dimension & loco::DepthwiseFilterShape::width (void) const inline
Definition at line 51 of file DepthwiseFilterShape.h.
{ return _width; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), and exo::to_shape_description().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/DepthwiseFilterShape.h