ONE - On-device Neural Engine: onert::ir::CachedData Class Reference
onert::ir::CachedData Class Reference final
#include <Data.h>
Public Member Functions
CachedData (const uint8_t *base, size_t size)
~CachedData ()
size_t size (void) const override
const uint8_t * base (void) const override
Public Member Functions inherited from onert::ir::Data
virtual ~Data ()=default
virtual size_t size (void) const =0
virtual const uint8_t * base (void) const =0
Detailed Description
Definition at line 36 of file Data.h.
Constructor & Destructor Documentation
CachedData()
onert::ir::CachedData::CachedData (const uint8_t * base, size_t size) inline
Definition at line 39 of file Data.h.
                                               : _base{new uint8_t[size]}, _size{size}
  {
    std::copy(base, base + size, _base);
  }
References base(), and size().
~CachedData()
onert::ir::CachedData::~CachedData () inline
Definition at line 45 of file Data.h.
{ delete[] _base; }
Member Function Documentation
base()
const uint8_t * onert::ir::CachedData::base (void) const inline override virtual
Implements onert::ir::Data.
Definition at line 49 of file Data.h.
{ return _base; }
Referenced by CachedData().
size()
size_t onert::ir::CachedData::size (void) const inline override virtual
Implements onert::ir::Data.
Definition at line 48 of file Data.h.
{ return _size; }
Referenced by CachedData().
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/Data.h