ONE - On-device Neural Engine: moco::TFConv2DBackpropInput Class Reference
moco::TFConv2DBackpropInput Class Reference final
#include <TFConv2DBackpropInput.h>
Public Member Functions
loco::Node * input_sizes (void) const
void input_sizes (Node *node)
loco::Node * filter (void) const
void filter (Node *node)
loco::Node * out_backprop (void) const
void out_backprop (Node *node)
const TFPadding & padding (void) const
void padding (const TFPadding &padding)
const TFDataLayout & data_layout (void) const
void data_layout (const TFDataLayout &data_layout)
const std::vector< int64_t > & strides (void) const
void strides (const std::vector< int64_t > &strides)
Public Member Functions inherited from moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::Conv2DBackpropInput >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >
loco::Use * at (unsigned n) const
Detailed Description
Note
TFConv2DBackpropInput corresponds to the following GraphDef
For Tensorflow Conv2DBackpropInput, 'input' refers actual output of the node, and 'input' refers actual input. The reasone of this is, as name suggests, because it is inspired from backpropagation of convolution. For example, 'out_backprop' of Conv2DBackpropInput is its actual input feature map, and 'input_sizes' means desired output node's size. Note that this convention is against loco canonical's convention.
Definition at line 70 of file TFConv2DBackpropInput.h.
Member Function Documentation
data_layout() [1/2]
void moco::TFConv2DBackpropInput::data_layout (const TFDataLayout & data_layout) inline
Definition at line 88 of file TFConv2DBackpropInput.h.
{ _data_layout = data_layout; }
References data_layout().
Referenced by data_layout().
data_layout() [2/2]
const TFDataLayout & moco::TFConv2DBackpropInput::data_layout (void) const inline
Definition at line 87 of file TFConv2DBackpropInput.h.
{ return _data_layout; }
filter() [1/2]
void moco::TFConv2DBackpropInput::filter (Node * node) inline
Definition at line 78 of file TFConv2DBackpropInput.h.
{ at(1)->node(node); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
filter() [2/2]
loco::Node * moco::TFConv2DBackpropInput::filter (void) const inline
Definition at line 77 of file TFConv2DBackpropInput.h.
{ return at(1)->node(); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
input_sizes() [1/2]
void moco::TFConv2DBackpropInput::input_sizes (Node * node) inline
Definition at line 75 of file TFConv2DBackpropInput.h.
{ at(0)->node(node); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
input_sizes() [2/2]
loco::Node * moco::TFConv2DBackpropInput::input_sizes (void) const inline
Definition at line 74 of file TFConv2DBackpropInput.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
out_backprop() [1/2]
void moco::TFConv2DBackpropInput::out_backprop (Node * node) inline
Definition at line 81 of file TFConv2DBackpropInput.h.
{ at(2)->node(node); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
out_backprop() [2/2]
loco::Node * moco::TFConv2DBackpropInput::out_backprop (void) const inline
Definition at line 80 of file TFConv2DBackpropInput.h.
{ return at(2)->node(); }
References moco::FixedArityNode< 3, TFNodeImpl< TFOpcode::Conv2DBackpropInput > >::at(), and loco::Use::node().
padding() [1/2]
void moco::TFConv2DBackpropInput::padding (const TFPadding & padding) inline
Definition at line 85 of file TFConv2DBackpropInput.h.
{ _padding = padding; }
References padding().
Referenced by padding().
padding() [2/2]
const TFPadding & moco::TFConv2DBackpropInput::padding (void) const inline
Definition at line 84 of file TFConv2DBackpropInput.h.
{ return _padding; }
strides() [1/2]
void moco::TFConv2DBackpropInput::strides (const std::vector< int64_t > & strides) inline
Definition at line 91 of file TFConv2DBackpropInput.h.
{ _strides = strides; }
References strides().
Referenced by strides().
strides() [2/2]
const std::vector< int64_t > & moco::TFConv2DBackpropInput::strides (void) const inline
Definition at line 90 of file TFConv2DBackpropInput.h.
{ return _strides; }
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFConv2DBackpropInput.h