ONE - On-device Neural Engine: nnfw::ruy::Shape Class Reference
nnfw::ruy::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape & operator= (Shape const &)=delete
Shape ()
Shape (int dimensions_count)
Shape (int shape_size, int32_t value)
Shape (int dimensions_count, const int32_t *dims_data)
Shape (const std::initializer_list< int > init_list)
Shape (Shape const &other)
bool operator== (const Shape &comp) const
~Shape ()
int32_t DimensionsCount () const
int32_t Dims (int i) const
void SetDim (int i, int32_t val)
int32_t * DimsData ()
const int32_t * DimsData () const
const int32_t * DimsDataUpTo4D () const
void Resize (int dimensions_count)
void ReplaceWith (int dimensions_count, const int32_t *dims_data)
void ReplaceWith (const Shape &other)
void ReplaceWith (Shape &&other)
template<typename T >
void BuildFrom (const T &src_iterable)
void BuildFrom (const std::initializer_list< int > init_list)
int FlatSize () const
bool operator!= (const Shape &comp) const
Static Public Member Functions
static Shape ExtendedShape (int new_shape_size, const Shape &shape)
Static Public Attributes
static constexpr int kMaxSmallSize = 5
Detailed Description
Definition at line 33 of file Shape.h.
Constructor & Destructor Documentation
Shape() [1/6]
nnfw::ruy::Shape::Shape () inline
Definition at line 42 of file Shape.h.
: _size(0) {}
Referenced by ExtendedShape().
Shape() [2/6]
nnfw::ruy::Shape::Shape (int dimensions_count) inline explicit
Definition at line 44 of file Shape.h.
                                       : _size(dimensions_count)
  {
    if (dimensions_count > kMaxSmallSize)
    {
      _dims_pointer = new int32_t[dimensions_count];
    }
  }
References _dims_pointer, and kMaxSmallSize.
Shape() [3/6]
nnfw::ruy::Shape::Shape (int shape_size, int32_t value) inline
Definition at line 52 of file Shape.h.
                                       : _size(0)
  {
    Resize(shape_size);
    for (int i = 0; i < shape_size; ++i)
    {
      SetDim(i, value);
    }
  }
References Resize(), and SetDim().
Shape() [4/6]
nnfw::ruy::Shape::Shape (int dimensions_count, const int32_t * dims_data) inline
Definition at line 61 of file Shape.h.
                                                        : _size(0)
  {
    ReplaceWith(dimensions_count, dims_data);
  }
References ReplaceWith().
Shape() [5/6]
nnfw::ruy::Shape::Shape (const std::initializer_list< int > init_list) inline
Definition at line 66 of file Shape.h.
: _size(0) { BuildFrom(init_list); }
References BuildFrom().
Shape() [6/6]
nnfw::ruy::Shape::Shape (Shape const & other) inline
Definition at line 70 of file Shape.h.
                            : _size(other.DimensionsCount())
  {
    if (_size > kMaxSmallSize)
    {
      _dims_pointer = new int32_t[_size];
    }
    std::memcpy(DimsData(), other.DimsData(), sizeof(int32_t) * _size);
  }
References _dims_pointer, DimsData(), and kMaxSmallSize.
~Shape()
nnfw::ruy::Shape::~Shape () inline
Definition at line 85 of file Shape.h.
  {
    if (_size > kMaxSmallSize)
    {
      delete[] _dims_pointer;
    }
  }
References _dims_pointer, and kMaxSmallSize.
Member Function Documentation
BuildFrom() [1/2]
void nnfw::ruy::Shape::BuildFrom (const std::initializer_list< int > init_list) inline
Definition at line 176 of file Shape.h.
  {
    BuildFrom<const std::initializer_list<int>>(init_list);
  }
BuildFrom() [2/2]
template<typename T > void nnfw::ruy::Shape::BuildFrom (const T & src_iterable) inline
Definition at line 154 of file Shape.h.
  {
    const int dimensions_count = std::distance(src_iterable.begin(), src_iterable.end());
    Resize(dimensions_count);
    int32_t *data = DimsData();
    for (auto it : src_iterable)
    {
      *data = it;
      ++data;
    }
  }
References DimsData(), and Resize().
Referenced by Shape().
DimensionsCount()
int32_t nnfw::ruy::Shape::DimensionsCount () const inline
Definition at line 93 of file Shape.h.
{ return _size; }
Referenced by nnfw::ruy::checkMatching(), nnfw::ruy::DilatedIm2col(), nnfw::ruy::ExtractPatchIntoBufferColumn(), nnfw::ruy::FlatSizeSkipDim(), nnfw::ruy::FullyConnected(), nnfw::ruy::Im2col(), nnfw::ruy::MatchingFlatSizeSkipDim(), nnfw::ruy::Offset(), and ReplaceWith().
Dims()
int32_t nnfw::ruy::Shape::Dims (int i) const inline
Definition at line 94 of file Shape.h.
  {
    assert(i >= 0);
    assert(i < _size);
    return _size > kMaxSmallSize ? _dims_pointer[i] : _dims[i];
  }
References _dims, _dims_pointer, and kMaxSmallSize.
Referenced by nnfw::ruy::checkMatching(), nnfw::ruy::DilatedIm2col(), nnfw::ruy::FullyConnected(), nnfw::ruy::Im2col(), nnfw::ruy::MatchingDim(), and nnfw::ruy::MatchingFlatSizeSkipDim().
DimsData() [1/2]
int32_t * nnfw::ruy::Shape::DimsData () inline
Definition at line 114 of file Shape.h.
{ return _size > kMaxSmallSize ? _dims_pointer : _dims; }
References _dims, _dims_pointer, and kMaxSmallSize.
Referenced by BuildFrom(), FlatSize(), nnfw::ruy::FlatSizeSkipDim(), onert::backend::ruy::ops::getTensorShape(), operator==(), ReplaceWith(), and Shape().
DimsData() [2/2]
const int32_t * nnfw::ruy::Shape::DimsData () const inline
Definition at line 115 of file Shape.h.
{ return _size > kMaxSmallSize ? _dims_pointer : _dims; }
References _dims, _dims_pointer, and kMaxSmallSize.
DimsDataUpTo4D()
const int32_t * nnfw::ruy::Shape::DimsDataUpTo4D () const inline
Definition at line 117 of file Shape.h.
{ return _dims; }
References _dims.
Referenced by nnfw::ruy::Offset().
ExtendedShape()
static Shape nnfw::ruy::Shape::ExtendedShape (int new_shape_size, const Shape & shape) inline static
Definition at line 171 of file Shape.h.
  {
    return Shape(new_shape_size, shape, 1);
  }
References Shape().
FlatSize()
int nnfw::ruy::Shape::FlatSize () const inline
Definition at line 183 of file Shape.h.
  {
    int buffer_size = 1;
    const int *dims_data = DimsData();
    for (int i = 0; i < _size; i++)
    {
      const int dim = dims_data[i];
      assert(dim >= 1);
      buffer_size *= dim;
    }
    return buffer_size;
  }
References DimsData().
Referenced by nnfw::ruy::checkMatching(), nnfw::ruy::FullyConnected(), nnfw::ruy::MatchingElementsSize(), nnfw::ruy::MatchingFlatSize(), nnfw::ruy::Conv::operator()(), and onert::backend::ruy::ops::FullyConnectedLayer::prepare().
operator!=()
bool nnfw::ruy::Shape::operator!= (const Shape & comp) const inline
Definition at line 196 of file Shape.h.
{ return !((*this) == comp); }
operator=()
Shape & nnfw::ruy::Shape::operator= (Shape const &) delete
operator==()
bool nnfw::ruy::Shape::operator== (const Shape & comp) const inline
Definition at line 79 of file Shape.h.
  {
    return this->_size == comp._size &&
           std::memcmp(DimsData(), comp.DimsData(), _size * sizeof(int32_t)) == 0;
  }
References DimsData().
ReplaceWith() [1/3]
void nnfw::ruy::Shape::ReplaceWith (const Shape & other) inline
Definition at line 139 of file Shape.h.
  {
    ReplaceWith(other.DimensionsCount(), other.DimsData());
  }
References DimensionsCount(), DimsData(), and ReplaceWith().
ReplaceWith() [2/3]
void nnfw::ruy::Shape::ReplaceWith (int dimensions_count, const int32_t * dims_data) inline
Definition at line 132 of file Shape.h.
  {
    Resize(dimensions_count);
    int32_t *dst_dims = DimsData();
    std::memcpy(dst_dims, dims_data, dimensions_count * sizeof(int32_t));
  }
References DimsData(), and Resize().
Referenced by ReplaceWith(), and Shape().
ReplaceWith() [3/3]
void nnfw::ruy::Shape::ReplaceWith (Shape && other) inline
Definition at line 144 of file Shape.h.
  {
    Resize(0);
    std::swap(_size, other._size);
    if (_size <= kMaxSmallSize)
      std::copy(other._dims, other._dims + kMaxSmallSize, _dims);
    else
      _dims_pointer = other._dims_pointer;
  }
References _dims, _dims_pointer, kMaxSmallSize, and Resize().
Resize()
void nnfw::ruy::Shape::Resize (int dimensions_count) inline
Definition at line 119 of file Shape.h.
  {
    if (_size > kMaxSmallSize)
    {
      delete[] _dims_pointer;
    }
    _size = dimensions_count;
    if (dimensions_count > kMaxSmallSize)
    {
      _dims_pointer = new int32_t[dimensions_count];
    }
  }
References _dims_pointer, and kMaxSmallSize.
Referenced by BuildFrom(), ReplaceWith(), and Shape().
SetDim()
void nnfw::ruy::Shape::SetDim (int i, int32_t val) inline
Definition at line 100 of file Shape.h.
  {
    assert(i >= 0);
    assert(i < _size);
    if (_size > kMaxSmallSize)
    {
      _dims_pointer[i] = val;
    }
    else
    {
      _dims[i] = val;
    }
  }
References _dims, _dims_pointer, and kMaxSmallSize.
Referenced by Shape().
Field Documentation
_dims
int32_t nnfw::ruy::Shape::_dims[kMaxSmallSize]
Definition at line 218 of file Shape.h.
Referenced by Dims(), DimsData(), DimsDataUpTo4D(), ReplaceWith(), and SetDim().
_dims_pointer
int32_t* nnfw::ruy::Shape::_dims_pointer {nullptr}
Definition at line 219 of file Shape.h.
Referenced by Dims(), DimsData(), ReplaceWith(), Resize(), SetDim(), Shape(), and ~Shape().
kMaxSmallSize
constexpr int nnfw::ruy::Shape::kMaxSmallSize = 5 static constexpr
Definition at line 38 of file Shape.h.
Referenced by Dims(), DimsData(), ReplaceWith(), Resize(), SetDim(), Shape(), and ~Shape().
The documentation for this class was generated from the following file:
compute/ruy/include/ruy/Shape.h