ONE - On-device Neural Engine: loco::Use Class Reference
loco::Use Class Reference final
The edge between a node definition and its user.
#include <Use.h>
Public Member Functions
Use (Node *user)
Construct Use with its user.
Use (const Use &)=delete
Use (Use &&)=delete
~Use ()
Node * node (void) const
void node (Node *node)
Node * user (void) const
Detailed Description
The edge between a node definition and its user.
Note that this "Use" denotes one edge between a node and its users, and thus there are unique node and user for each Use.
There will be multiple "Use" edges for the same node if there are multiple users.
This class design is heavily inspired from "Use" class in LLVM.
Definition at line 36 of file Use.h.
Constructor & Destructor Documentation
Use() [1/3]
loco::Use::Use (Node * user) inline
Construct Use with its user.
Note
user SHOULD BE set on construction.
Definition at line 43 of file Use.h.
                  : _user{user}
  {
    // DO NOTHING
  }
Use() [2/3]
loco::Use::Use (const Use &) delete
Use() [3/3]
loco::Use::Use (Use &&) delete
~Use()
loco::Use::~Use () inline
Definition at line 51 of file Use.h.
  {
    // Unlink itself from the node
    node(nullptr);
  }
References node().
Member Function Documentation
node() [1/2]
void loco::Use::node (Node * node)
Definition at line 25 of file Use.cpp.
{
  if (_node != nullptr)
  {
    assert(_node->_uses.find(this) != _node->_uses.end());
    _node->_uses.erase(this);
    _node = nullptr;
  }
  assert(_node == nullptr);
  if (node != nullptr)
  {
    _node = node;
    _node->_uses.insert(this);
  }
  assert(_node == node);
}
References node().
node() [2/2]
Node * loco::Use::node (void) const inline
Definition at line 58 of file Use.h.
{ return _node; }
Referenced by locoex::TFLTranspose::a(), luci::CircleTranspose::a(), luci::CirclePRelu::alpha(), luci::CircleBidirectionalSequenceLSTM::auxillary_input(), luci::CircleExpandDims::axis(), luci::CircleReverseV2::axis(), moco::TFConcatV2::axis(), luci::CircleSlice::begin(), luci::CircleStridedSlice::begin(), moco::TFStridedSlice::begin(), locoex::CircleInstanceNorm::beta(), luci::CircleInstanceNorm::beta(), luci::CircleSVDF::bias(), moco::TFBiasAdd::bias(), locoex::TFLConv2D::bias(), locoex::TFLDepthwiseConv2D::bias(), locoex::TFLFullyConnected::bias(), luci::CircleBCQFullyConnected::bias(), luci::CircleConv2D::bias(), luci::CircleDepthwiseConv2D::bias(), luci::CircleFullyConnected::bias(), luci::CircleTransposeConv::bias(), luci::CircleBatchToSpaceND::block_shape(), luci::CircleSpaceToBatchND::block_shape(), luci::CircleNonMaxSuppressionV4::boxes(), luci::CircleNonMaxSuppressionV5::boxes(), luci::CircleBidirectionalSequenceLSTM::bw_activation_state(), luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::bw_auxillary_input_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::bw_cell_gate_bias(), luci::CircleBidirectionalSequenceLSTM::bw_cell_state(), luci::CircleBidirectionalSequenceLSTM::bw_cell_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::bw_cell_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::bw_cell_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::bw_forget_gate_bias(), luci::CircleBidirectionalSequenceLSTM::bw_input_gate_bias(), luci::CircleBidirectionalSequenceLSTM::bw_input_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::bw_input_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::bw_input_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::bw_input_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::bw_output_gate_bias(), luci::CircleBidirectionalSequenceLSTM::bw_projection_bias(), luci::CircleBidirectionalSequenceLSTM::bw_projection_weights(), luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::bw_recurrent_to_output_weights(), luci::CircleUnidirectionalSequenceLSTM::cell_gate_bias(), luci::CircleUnidirectionalSequenceLSTM::cell_layer_norm_coefficients(), luci::CircleUnidirectionalSequenceLSTM::cell_state(), luci::CircleUnidirectionalSequenceLSTM::cell_to_forget_weights(), luci::CircleUnidirectionalSequenceLSTM::cell_to_input_weights(), luci::CircleUnidirectionalSequenceLSTM::cell_to_output_weights(), luci::CircleIf::cond(), luci::CircleWhere::condition(), luci::CircleSelect::condition(), luci::CircleSelectV2::condition(), luci::CirclePadV2::constant_values(), luci::CircleBatchToSpaceND::crops(), luci::CircleSparseToDense::default_value(), luci::CircleRange::delta(), luci::CircleOneHot::depth(), luci::CircleMatrixDiag::diagonal(), luci::CircleMatrixSetDiag::diagonal(), luci::CircleArgMax::dimension(), luci::CircleArgMin::dimension(), luci::CircleFill::dims(), luci::CircleSelect::e(), luci::CircleSelectV2::e(), luci::CircleStridedSlice::end(), moco::TFStridedSlice::end(), locoex::TFLRelu::features(), locoex::TFLRelu6::features(), luci::CircleElu::features(), luci::CircleLeakyRelu::features(), luci::CircleRelu::features(), luci::CircleRelu6::features(), luci::CircleReluN1To1::features(), moco::TFRelu::features(), moco::TFRelu6::features(), locoex::TFLConv2D::filter(), locoex::TFLDepthwiseConv2D::filter(), locoex::TFLTransposeConv::filter(), luci::CircleConv2D::filter(), luci::CircleDepthwiseConv2D::filter(), luci::CircleTransposeConv::filter(), moco::TFConv2D::filter(), moco::TFConv2DBackpropInput::filter(), moco::TFDepthwiseConv2dNative::filter(), luci::CircleUnidirectionalSequenceLSTM::forget_gate_bias(), luci::CircleUnidirectionalSequenceLSTM::forget_layer_norm_coefficients(), luci::CircleOutput::from(), moco::TFPush::from(), luci::CircleBidirectionalSequenceLSTM::fw_activation_state(), luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::fw_auxillary_input_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::fw_cell_gate_bias(), luci::CircleBidirectionalSequenceLSTM::fw_cell_state(), luci::CircleBidirectionalSequenceLSTM::fw_cell_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::fw_cell_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::fw_cell_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::fw_forget_gate_bias(), luci::CircleBidirectionalSequenceLSTM::fw_input_gate_bias(), luci::CircleBidirectionalSequenceLSTM::fw_input_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::fw_input_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::fw_input_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::fw_input_to_output_weights(), luci::CircleBidirectionalSequenceLSTM::fw_output_gate_bias(), luci::CircleBidirectionalSequenceLSTM::fw_projection_bias(), luci::CircleBidirectionalSequenceLSTM::fw_projection_weights(), luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_cell_weights(), luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_forget_weights(), luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_input_weights(), luci::CircleBidirectionalSequenceLSTM::fw_recurrent_to_output_weights(), locoex::CircleInstanceNorm::gamma(), luci::CircleInstanceNorm::gamma(), luci::CircleBCQGather::indices(), luci::CircleGather::indices(), luci::CircleGatherNd::indices(), luci::CircleOneHot::indices(), luci::CircleScatterNd::indices(), luci::CircleSparseToDense::indices(), luci::CircleIf::input(), luci::CircleWhile::input(), locoex::COpCall::input(), locoex::CircleInstanceNorm::input(), locoex::TFLConv2D::input(), locoex::TFLDepthwiseConv2D::input(), locoex::TFLFullyConnected::input(), locoex::TFLMean::input(), luci::CircleArgMax::input(), luci::CircleArgMin::input(), luci::CircleBatchToSpaceND::input(), luci::CircleBCQFullyConnected::input(), luci::CircleBidirectionalSequenceLSTM::input(), luci::CircleBidirectionalSequenceLSTMOut::input(), luci::CircleConv2D::input(), luci::CircleCustomOut::input(), luci::CircleDensify::input(), luci::CircleDepthToSpace::input(), luci::CircleDepthwiseConv2D::input(), luci::CircleDequantize::input(), luci::CircleExpandDims::input(), luci::CircleFullyConnected::input(), luci::CircleIfOut::input(), luci::CircleInstanceNorm::input(), luci::CircleLocalResponseNormalization::input(), luci::CircleMatrixSetDiag::input(), luci::CircleMean::input(), luci::CircleMirrorPad::input(), luci::CircleNonMaxSuppressionV4Out::input(), luci::CircleNonMaxSuppressionV5Out::input(), luci::CirclePad::input(), luci::CirclePadV2::input(), luci::CirclePRelu::input(), luci::CircleQuantize::input(), luci::CircleRank::input(), luci::CircleReduceAny::input(), luci::CircleReduceMax::input(), luci::CircleReduceMin::input(), luci::CircleReduceProd::input(), luci::CircleResizeBilinear::input(), luci::CircleResizeNearestNeighbor::input(), luci::CircleReverseSequence::input(), luci::CircleSegmentSum::input(), luci::CircleShape::input(), luci::CircleSlice::input(), luci::CircleSpaceToBatchND::input(), luci::CircleSpaceToDepth::input(), luci::CircleSplit::input(), luci::CircleSplitOut::input(), luci::CircleSplitV::input(), luci::CircleSplitVOut::input(), luci::CircleSqueeze::input(), luci::CircleStridedSlice::input(), luci::CircleSum::input(), luci::CircleSVDF::input(), luci::CircleTile::input(), luci::CircleTopKV2::input(), luci::CircleTopKV2Out::input(), luci::CircleUnidirectionalSequenceLSTM::input(), luci::CircleUnique::input(), luci::CircleUniqueOut::input(), luci::CircleUnpackOut::input(), luci::CircleWhileOut::input(), luci::CircleZerosLike::input(), moco::TFConv2D::input(), moco::TFDepthwiseConv2dNative::input(), moco::TFIdentity::input(), moco::TFMaxPool::input(), moco::TFMean::input(), moco::TFPad::input(), moco::TFShape::input(), moco::TFSqueeze::input(), moco::TFStopGradient::input(), moco::TFStridedSlice::input(), luci::CircleSVDF::input_activation_state(), luci::CircleBCQGather::input_binary(), luci::CircleBCQGather::input_clusters(), luci::CircleUnidirectionalSequenceLSTM::input_gate_bias(), luci::CircleUnidirectionalSequenceLSTM::input_layer_norm_coefficients(), luci::CircleBCQGather::input_scales(), moco::TFConv2DBackpropInput::input_sizes(), luci::CircleUnidirectionalSequenceLSTM::input_to_cell_weights(), luci::CircleUnidirectionalSequenceLSTM::input_to_forget_weights(), luci::CircleUnidirectionalSequenceLSTM::input_to_input_weights(), luci::CircleUnidirectionalSequenceLSTM::input_to_output_weights(), luci::CircleAddN::inputs(), luci::CircleCustom::inputs(), luci::CircleFakeQuant::inputs(), moco::TFFakeQuantWithMinMaxVars::inputs(), locoex::TFLTransposeConv::inputSizes(), luci::CircleTransposeConv::inputSizes(), luci::CircleNonMaxSuppressionV4::iou_threshold(), luci::CircleNonMaxSuppressionV5::iou_threshold(), luci::CircleTopKV2::k(), luci::CircleRange::limit(), luci::CircleLogSoftmax::logits(), luci::CircleSoftmax::logits(), moco::TFSoftmax::logits(), moco::TFFakeQuantWithMinMaxVars::max(), luci::CircleNonMaxSuppressionV4::max_output_size(), luci::CircleNonMaxSuppressionV5::max_output_size(), moco::TFFusedBatchNorm::mean(), moco::TFFakeQuantWithMinMaxVars::min(), luci::CircleTile::multiples(), node(), luci::CircleOneHot::off_value(), moco::TFFusedBatchNorm::offset(), luci::CircleOneHot::on_value(), moco::TFConv2DBackpropInput::out_backprop(), locoex::TFLTransposeConv::outBackprop(), luci::CircleTransposeConv::outBackprop(), luci::CircleUnidirectionalSequenceLSTM::output_gate_bias(), luci::CircleUnidirectionalSequenceLSTM::output_layer_norm_coefficients(), luci::CircleSparseToDense::output_shape(), luci::CircleUnidirectionalSequenceLSTM::output_state(), luci::CircleMirrorPad::paddings(), luci::CirclePad::paddings(), luci::CirclePadV2::paddings(), luci::CircleSpaceToBatchND::paddings(), moco::TFPad::paddings(), luci::CircleGather::params(), luci::CircleGatherNd::params(), locoex::TFLTranspose::perm(), luci::CircleTranspose::perm(), luci::CircleUnidirectionalSequenceLSTM::projection_bias(), luci::CircleUnidirectionalSequenceLSTM::projection_weights(), luci::CircleUnidirectionalSequenceLSTM::recurrent_to_cell_weights(), luci::CircleUnidirectionalSequenceLSTM::recurrent_to_forget_weights(), luci::CircleUnidirectionalSequenceLSTM::recurrent_to_input_weights(), luci::CircleUnidirectionalSequenceLSTM::recurrent_to_output_weights(), locoex::TFLMean::reduction_indices(), luci::CircleMean::reduction_indices(), luci::CircleReduceAny::reduction_indices(), luci::CircleReduceMax::reduction_indices(), luci::CircleReduceMin::reduction_indices(), luci::CircleReduceProd::reduction_indices(), luci::CircleSum::reduction_indices(), moco::TFMean::reduction_indices(), moco::TFFusedBatchNorm::scale(), luci::CircleNonMaxSuppressionV4::score_threshold(), luci::CircleNonMaxSuppressionV5::score_threshold(), luci::CircleNonMaxSuppressionV4::scores(), luci::CircleNonMaxSuppressionV5::scores(), luci::CircleSegmentSum::segment_ids(), luci::CircleReverseSequence::seq_lengths(), locoex::TFLReshape::shape(), luci::CircleReshape::shape(), luci::CircleScatterNd::shape(), moco::TFReshape::shape(), luci::CircleResizeBilinear::size(), luci::CircleResizeNearestNeighbor::size(), luci::CircleSlice::size(), luci::CircleSplitV::size_splits(), luci::CircleNonMaxSuppressionV5::soft_nms_sigma(), luci::CircleSplit::split_dim(), luci::CircleSplitV::split_dim(), luci::CircleRange::start(), luci::CircleStridedSlice::strides(), moco::TFStridedSlice::strides(), luci::CircleSelect::t(), luci::CircleSelectV2::t(), locoex::TFLReshape::tensor(), luci::CircleReshape::tensor(), luci::CircleReverseV2::tensor(), moco::TFReshape::tensor(), luci::CircleScatterNd::updates(), locoex::TFLAveragePool2D::value(), locoex::TFLMaxPool2D::value(), luci::CircleAveragePool2D::value(), luci::CircleFill::value(), luci::CircleL2Pool2D::value(), luci::CircleMaxPool2D::value(), luci::CircleUnpack::value(), moco::TFAvgPool::value(), moco::TFBiasAdd::value(), locoex::TFLConcatenation::values(), luci::CircleConcatenation::values(), luci::CirclePack::values(), moco::TFConcatV2::values(), moco::TFPack::values(), luci::CircleSparseToDense::values(), moco::TFFusedBatchNorm::variance(), luci::CircleSVDF::weight_feature(), luci::CircleSVDF::weight_time(), locoex::TFLFullyConnected::weights(), luci::CircleFullyConnected::weights(), luci::CircleBCQFullyConnected::weights_binary(), luci::CircleBCQFullyConnected::weights_clusters(), luci::CircleBCQFullyConnected::weights_scales(), locoex::TFLAdd::x(), locoex::TFLDiv::x(), locoex::TFLMaximum::x(), locoex::TFLMul::x(), locoex::TFLRsqrt::x(), locoex::TFLSqrt::x(), locoex::TFLSquaredDifference::x(), locoex::TFLSub::x(), luci::CircleAbs::x(), luci::CircleAdd::x(), luci::CircleBatchMatMul::x(), luci::CircleCast::x(), luci::CircleCeil::x(), luci::CircleCos::x(), luci::CircleDiv::x(), luci::CircleEqual::x(), luci::CircleExp::x(), luci::CircleFloor::x(), luci::CircleFloorDiv::x(), luci::CircleFloorMod::x(), luci::CircleGreater::x(), luci::CircleGreaterEqual::x(), luci::CircleL2Normalize::x(), luci::CircleLess::x(), luci::CircleLessEqual::x(), luci::CircleLog::x(), luci::CircleLogicalAnd::x(), luci::CircleLogicalNot::x(), luci::CircleLogicalOr::x(), luci::CircleLogistic::x(), luci::CircleMaximum::x(), luci::CircleMinimum::x(), luci::CircleMul::x(), luci::CircleNeg::x(), luci::CircleNotEqual::x(), luci::CirclePow::x(), luci::CircleRound::x(), luci::CircleRsqrt::x(), luci::CircleSin::x(), luci::CircleSqrt::x(), luci::CircleSquare::x(), luci::CircleSquaredDifference::x(), luci::CircleSub::x(), luci::CircleTanh::x(), moco::TFAdd::x(), moco::TFFusedBatchNorm::x(), moco::TFMaximum::x(), moco::TFMul::x(), moco::TFRealDiv::x(), moco::TFRsqrt::x(), moco::TFSqrt::x(), moco::TFSquaredDifference::x(), moco::TFSub::x(), moco::TFTanh::x(), locoex::TFLAdd::y(), locoex::TFLDiv::y(), locoex::TFLMaximum::y(), locoex::TFLMul::y(), locoex::TFLSquaredDifference::y(), locoex::TFLSub::y(), luci::CircleAdd::y(), luci::CircleBatchMatMul::y(), luci::CircleDiv::y(), luci::CircleEqual::y(), luci::CircleFloorDiv::y(), luci::CircleFloorMod::y(), luci::CircleGreater::y(), luci::CircleGreaterEqual::y(), luci::CircleLess::y(), luci::CircleLessEqual::y(), luci::CircleLogicalAnd::y(), luci::CircleLogicalOr::y(), luci::CircleMaximum::y(), luci::CircleMinimum::y(), luci::CircleMul::y(), luci::CircleNotEqual::y(), luci::CirclePow::y(), luci::CircleSquaredDifference::y(), luci::CircleSub::y(), moco::TFAdd::y(), moco::TFMaximum::y(), moco::TFMul::y(), moco::TFRealDiv::y(), moco::TFSquaredDifference::y(), moco::TFSub::y(), and ~Use().
user()
Node * loco::Use::user (void) const inline
Definition at line 62 of file Use.h.
{ return _user; }
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/Use.h
compiler/loco/src/IR/Use.cpp