ONE - On-device Neural Engine: luci::QuantizeDequantizeWeightsPass Class Reference
luci::QuantizeDequantizeWeightsPass Class Reference
Pass to quantize weights.
#include <QuantizeDequantizeWeightsPass.h>
Data Structures
struct Context
Public Member Functions
QuantizeDequantizeWeightsPass (std::unique_ptr< Context > &&ctx)
QuantizeDequantizeWeightsPass (loco::DataType input_model_dtype, loco::DataType output_model_dtype, QuantizationGranularity granularity)
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to quantize weights.
Definition at line 32 of file QuantizeDequantizeWeightsPass.h.
Constructor & Destructor Documentation
QuantizeDequantizeWeightsPass() [1/2]
luci::QuantizeDequantizeWeightsPass::QuantizeDequantizeWeightsPass (std::unique_ptr< Context > && ctx) inline
Definition at line 44 of file QuantizeDequantizeWeightsPass.h.
                                                              : _ctx{std::move(ctx)}
  {
    // DO NOTHING
  }
QuantizeDequantizeWeightsPass() [2/2]
luci::QuantizeDequantizeWeightsPass::QuantizeDequantizeWeightsPass (loco::DataType input_model_dtype, loco::DataType output_model_dtype, QuantizationGranularity granularity) inline
Definition at line 50 of file QuantizeDequantizeWeightsPass.h.
  {
    _ctx = std::make_unique<Context>();
    {
      _ctx->input_model_dtype = input_model_dtype;
      _ctx->output_model_dtype = output_model_dtype;
      _ctx->granularity = granularity;
    }
  }
Member Function Documentation
name()
virtual const char * luci::QuantizeDequantizeWeightsPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 60 of file QuantizeDequantizeWeightsPass.h.
{ return "luci::QuantizeDequantizeWeightsPass"; }
run()
bool luci::QuantizeDequantizeWeightsPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 432 of file QuantizeDequantizeWeightsPass.cpp.
{
  LOGGER(l);
  INFO(l) << "QuantizeDequantizeWeightsPass Start" << std::endl;
  auto info_by_name = layer_info_map(g, _ctx->layers_info);
  auto quantize_dtype = [&](const luci::CircleNode *node) {
    auto iter = info_by_name.find(node->name());
    // Return designated quantization dtype
    if (iter != info_by_name.end())
      return iter->second.dtype;
    // Return default quantization dtype
    return _ctx->output_model_dtype;
  };
  auto quantize_granularity = [&](const luci::CircleNode *node) {
    auto iter = info_by_name.find(node->name());
    // Return designated quantization granularity
    if (iter != info_by_name.end())
      return iter->second.granularity;
    // Return default quantization granularity
    return _ctx->granularity;
  };
  // Quantize weights
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    QuantizeDequantizeWeights qw(_ctx->input_model_dtype, quantize_dtype(circle_node),
                                 quantize_granularity(circle_node));
    circle_node->accept(&qw);
  }
  INFO(l) << "QuantizeDequantizeWeightsPass End" << std::endl;
  return false; // one time run
}
References loco::active_nodes(), INFO, luci::layer_info_map(), LOGGER, luci::CircleNode::name(), and loco::output_nodes().
Referenced by luci::CircleQuantizer::quantize().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/QuantizeDequantizeWeightsPass.h
compiler/luci/pass/src/QuantizeDequantizeWeightsPass.cpp