ONE - On-device Neural Engine: loco::PermutingDecoder< Domain::Feature > Class Reference
loco::PermutingDecoder< Domain::Feature > Class Reference final
#include <PermutingCodec.h>
Public Member Functions
PermutingDecoder ()=default
PermutingDecoder (const Permutation< Domain::Feature > &perm)
bool valid (void) const
TensorShape shape (const FeatureShape &tensor_shape) const override
FeatureIndex value (const TensorIndex &index) const override
std::unique_ptr< FeatureDecoder > clone (void) const override
const Permutation< Domain::Feature > * perm (void) const
Permutation< Domain::Feature > * perm (void)
void perm (const Permutation< Domain::Feature > &p)
Public Member Functions inherited from loco::FeatureDecoder
virtual ~FeatureDecoder ()=default
virtual TensorShape shape (const FeatureShape &) const =0
virtual FeatureIndex value (const TensorIndex &) const =0
virtual std::unique_ptr< FeatureDecoder > clone (void) const =0
Detailed Description
Definition at line 105 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingDecoder() [1/2]
loco::PermutingDecoder< Domain::Feature >::PermutingDecoder () default
PermutingDecoder() [2/2]
loco::PermutingDecoder< Domain::Feature >::PermutingDecoder (const Permutation< Domain::Feature > & perm) inline
Definition at line 111 of file PermutingCodec.h.
                                                           : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
clone()
std::unique_ptr< FeatureDecoder > loco::PermutingDecoder< Domain::Feature >::clone (void) const override virtual
Implements loco::FeatureDecoder.
Definition at line 179 of file PermutingCodec.cpp.
{
  return std::make_unique<PermutingDecoder<Domain::Feature>>(_perm);
}
perm() [1/3]
void loco::PermutingDecoder< Domain::Feature >::perm (const Permutation< Domain::Feature > & p) inline
Definition at line 128 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Feature > * loco::PermutingDecoder< Domain::Feature >::perm (void) inline
Definition at line 127 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Feature > * loco::PermutingDecoder< Domain::Feature >::perm (void) const inline
Definition at line 126 of file PermutingCodec.h.
{ return &_perm; }
shape()
TensorShape loco::PermutingDecoder< Domain::Feature >::shape (const FeatureShape & tensor_shape) const override virtual
Implements loco::FeatureDecoder.
Definition at line 149 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permuation");
  TensorShape out;
  out.rank(4);
  out.dim(_perm[FeatureAxis::Count]) = in.count();
  out.dim(_perm[FeatureAxis::Depth]) = in.depth();
  out.dim(_perm[FeatureAxis::Height]) = in.height();
  out.dim(_perm[FeatureAxis::Width]) = in.width();
  return out;
}
References loco::Count, loco::FeatureShape::count(), loco::Depth, loco::FeatureShape::depth(), loco::TensorShape::dim(), loco::Height, loco::FeatureShape::height(), loco::TensorShape::rank(), loco::valid(), loco::Width, and loco::FeatureShape::width().
valid()
bool loco::PermutingDecoder< Domain::Feature >::valid (void) const
Definition at line 184 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
FeatureIndex loco::PermutingDecoder< Domain::Feature >::value (const TensorIndex & index) const override virtual
Implements loco::FeatureDecoder.
Definition at line 165 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  FeatureIndex out;
  out.batch() = in.at(_perm[FeatureAxis::Count]);
  out.channel() = in.at(_perm[FeatureAxis::Depth]);
  out.row() = in.at(_perm[FeatureAxis::Height]);
  out.column() = in.at(_perm[FeatureAxis::Width]);
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::FeatureIndex::batch(), loco::FeatureIndex::channel(), loco::FeatureIndex::column(), loco::Count, loco::Depth, loco::Height, loco::FeatureIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp