ONE - On-device Neural Engine: luci_interpreter::kernels::Cast Class Reference
luci_interpreter::kernels::Cast Class Reference
#include <Cast.h>
Public Member Functions
Cast (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Cast (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Cast.h.
Constructor & Destructor Documentation
Cast() [1/2]
luci_interpreter::kernels::Cast::Cast (const Tensor * input, Tensor * output)
Definition at line 124 of file Cast.cpp.
: Kernel({input}, {output}) {}
References input().
Cast() [2/2]
luci_interpreter::kernels::Cast::Cast (const Tensor * input, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Cast::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 126 of file Cast.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() != loco::DataType::Unknown);
  LUCI_INTERPRETER_CHECK(output()->element_type() != loco::DataType::Unknown);
  const Shape &shape = input()->shape();
  output()->resize(shape);
}
References input(), LUCI_INTERPRETER_CHECK, output(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Cast::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Cast::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 135 of file Cast.cpp.
{
  assert(input()->shape().num_elements() == output()->shape().num_elements());
  cast_from_tensor_to_tensor(input(), output());
}
References input(), and output().
execute() [2/2]
void luci_interpreter::kernels::Cast::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Cast::input () const inline
Definition at line 33 of file Cast.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by Cast(), configure(), and execute().
input() [2/2]
const Tensor * luci_interpreter::kernels::Cast::input () const inline
Definition at line 33 of file Cast.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Cast::output () const inline
Definition at line 34 of file Cast.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Cast::output () const inline
Definition at line 34 of file Cast.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Cast.h
onert-micro/luci-interpreter/src/kernels/Cast.h
compiler/luci-interpreter/src/kernels/Cast.cpp
onert-micro/luci-interpreter/src/kernels/Cast.cpp