ONE - On-device Neural Engine: onert::exec::train::TrainableExecutor Class Reference
onert::exec::train::TrainableExecutor Class Reference
#include <TrainableExecutor.h>
Public Member Functions
TrainableExecutor (std::unique_ptr< compiler::train::LoweredTrainableGraph > lowered_graph, backend::train::TrainableBackendContexts &&backend_contexts, const compiler::train::TensorRegistries &tensor_regs, compiler::train::TrainableCodeMap &&code_map, const std::vector< ir::OperationIndex > &forward_order, const std::vector< ir::OperationIndex > &backward_order, const util::TracingCtx *tracing_ctx, const ir::train::LossInfo &training_info)
Construct a new TrainableExecutor object.
const ir::Graph & graph () const final
Returns graph object.
void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs, const ExecutionOptions &options) override
Execute with given input/output tensors.
uint32_t inputSize () const override
Get input size.
uint32_t outputSize () const override
Get output size.
const ir::OperandInfo & inputInfo (uint32_t index) const override
Get input info at index.
const ir::OperandInfo & outputInfo (uint32_t index) const override
Get output info at index.
ir::Layout inputLayout (uint32_t index) const override
Get input layout at index.
ir::Layout outputLayout (uint32_t index) const override
Get output layout at index.
const uint8_t * outputBuffer (uint32_t index) const final
Get output buffer at index.
void forward (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs, const ExecutionOptions &options, bool training)
void backward (const ExecutionOptions &options, uint32_t training_step)
void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > > ranks) final
Set an ordering on operations.
void addObserver (std::unique_ptr< IExecutionObserver > ref)
float getLoss (const ir::IOIndex &pred_io_ind) const
void iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> &fn) const
backend::train::TrainableBackendContexts & getBackendContexts ()
const ExecutionOptions & currentOptions () const override
Return current execution configuration.
Public Member Functions inherited from onert::exec::IExecutor
IExecutor ()=default
Construct a new IExecutor object.
virtual ~IExecutor ()=default
Destroy the IExecutor object.
Detailed Description
Definition at line 35 of file TrainableExecutor.h.
Constructor & Destructor Documentation
TrainableExecutor()
onert::exec::train::TrainableExecutor::TrainableExecutor (std::unique_ptr< compiler::train::LoweredTrainableGraph > lowered_graph, backend::train::TrainableBackendContexts && backend_contexts, const compiler::train::TensorRegistries & tensor_regs, compiler::train::TrainableCodeMap && code_map, const std::vector< ir::OperationIndex > & forward_order, const std::vector< ir::OperationIndex > & backward_order, const util::TracingCtx * tracing_ctx, const ir::train::LossInfo & training_info)
Construct a new TrainableExecutor object.
Parameters
lowered_graph LoweredTrainableGraph object
tensor_builders Tensor builders that are currently used
code_map ir::Operation and its code map
Definition at line 27 of file TrainableExecutor.cc.
  : _code_map{std::move(code_map)}, _forward_order{std::move(forward_order)},
    _backward_order{std::move(backward_order)}, _lowered_graph{std::move(lowered_graph)},
    _backend_contexts{std::move(backend_contexts)},
    _trainable_graph{_lowered_graph->trainable_graph()}, _tensor_regs{std::move(tensor_regs)},
    _mutex(), _tracing_ctx(tracing_ctx), _loss_info(loss_info)
{
  auto build_tensor_list = [&](const auto &ind_seq, auto &tensors) {
    assert(tensors.empty());
    for (auto &&ind : ind_seq)
    {
      backend::ITensor *tensor = _tensor_regs.getITensor(ind);
      assert(tensor != nullptr);
      auto io_tensor = nnfw::misc::polymorphic_downcast<backend::builtin::IOTensor *>(tensor);
      tensors.push_back(io_tensor);
    }
  };
  build_tensor_list(_trainable_graph.getInputs(), _input_tensors);
  build_tensor_list(_trainable_graph.getOutputs(), _output_tensors);
}
References onert::ir::train::TrainableGraph::getInputs(), onert::compiler::train::TensorRegistries::getITensor(), and onert::ir::train::TrainableGraph::getOutputs().
Member Function Documentation
addObserver()
void onert::exec::train::TrainableExecutor::addObserver (std::unique_ptr< IExecutionObserver > ref) inline
Definition at line 99 of file TrainableExecutor.h.
{ _observers.add(std::move(ref)); };
References onert::exec::ExecObservers::add().
backward()
void onert::exec::train::TrainableExecutor::backward (const ExecutionOptions & options, uint32_t training_step)
Definition at line 133 of file TrainableExecutor.cc.
{
  // For thread-safe, use mutex
  // TODO: if all used backends on this executor are thread-safe,
  //       do not need to use mutex (otherwise, use mutex)
  std::lock_guard<std::mutex> lock(_mutex);
  _current_options = options;
  // Create observee
  ExecutionObservee subject(_observers, options);
  backwardImpl(subject, training_step);
}
Referenced by onert::exec::train::TrainableExecutors::train().
currentOptions()
const ExecutionOptions & onert::exec::train::TrainableExecutor::currentOptions () const inline override virtual
Return current execution configuration.
Returns
Current execution configuration
Implements onert::exec::IExecutor.
Definition at line 109 of file TrainableExecutor.h.
{ return _current_options; }
execute()
void onert::exec::train::TrainableExecutor::execute (const std::vector< backend::IPortableTensor * > & inputs, const std::vector< backend::IPortableTensor * > & outputs, const ExecutionOptions & options) inline override virtual
Execute with given input/output tensors.
Input and output tensors must be given.
Parameters
[in] inputs Tensors that are passed as inputs
[in] outputs Tensors that are passed as outputs
[in] options Execution options
Implements onert::exec::IExecutor.
Definition at line 55 of file TrainableExecutor.h.
  {
    forward(inputs, outputs, options, false);
  }
References forward().
forward()
void onert::exec::train::TrainableExecutor::forward (const std::vector< backend::IPortableTensor * > & inputs, const std::vector< backend::IPortableTensor * > & outputs, const ExecutionOptions & options, bool training)
Definition at line 55 of file TrainableExecutor.cc.
{
  // For thread-safe, use mutex
  // TODO: if all used backends on this executor are thread-safe,
  //       do not need to use mutex (otherwise, use mutex)
  std::lock_guard<std::mutex> lock(_mutex);
  _current_options = options;
  assert(_input_tensors.size() == inputs.size());
  for (uint32_t i = 0; i < _input_tensors.size(); ++i)
  {
    auto tensor = _input_tensors[i];
    const auto input = inputs[i];
    assert(input->buffer() != nullptr || input->get_info().total_size() == 0);
    assert(tensor != nullptr);
    tensor->setTensor(input);
  }
  // Set output(s)
  assert(_output_tensors.size() == outputs.size());
  for (uint32_t i = 0; i < _output_tensors.size(); ++i)
  {
    auto tensor = _output_tensors[i];
    const auto output = outputs[i];
    // Output may not be used on training, so don't check optional
    assert(tensor != nullptr);
    tensor->setTensor(output);
  }
  // Create observee
  ExecutionObservee subject(_observers, options);
  forwardImpl(subject, training);
  // TODO Update output(s) desc if desc has dynamic input
}
Referenced by execute().
getBackendContexts()
backend::train::TrainableBackendContexts & onert::exec::train::TrainableExecutor::getBackendContexts () inline
Definition at line 107 of file TrainableExecutor.h.
{ return _backend_contexts; }
getLoss()
float onert::exec::train::TrainableExecutor::getLoss (const ir::IOIndex & pred_io_ind) const
Definition at line 194 of file TrainableExecutor.cc.
{
  const auto &loss_ind = _trainable_graph.getLossIndex(pred_io_ind);
  if (loss_ind.undefined())
    throw std::runtime_error{"Loss " + std::to_string(loss_ind.value()) + " is not defined."};
  backend::ITensor *tensor = _tensor_regs.getITensor(loss_ind);
  long double sum = 0;
  for (uint64_t i = 0; i < tensor->getShape().num_elements(); ++i)
  {
    sum += reinterpret_cast<float *>(tensor->buffer())[i];
  }
  if (_loss_info.reduction_type == ir::train::LossReductionType::SumOverBatchSize)
  {
    sum /= tensor->getShape().num_elements();
  }
  return static_cast<float>(sum);
}
References onert::compiler::train::TensorRegistries::getITensor(), onert::ir::train::TrainableGraph::getLossIndex(), onert::ir::train::LossInfo::reduction_type, and onert::ir::train::SumOverBatchSize.
Referenced by onert::exec::train::TrainableExecutors::getLoss().
graph()
const ir::Graph & onert::exec::train::TrainableExecutor::graph () const inline final virtual
Returns graph object.
Returns
Graph object
Implements onert::exec::IExecutor.
Definition at line 53 of file TrainableExecutor.h.
{ return _trainable_graph.graph(); }
References onert::ir::train::TrainableGraph::graph().
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
inputInfo()
const ir::OperandInfo & onert::exec::train::TrainableExecutor::inputInfo (uint32_t index) const inline override virtual
Get input info at index.
Parameters
[in] index Index of input
Returns
Input operand info
Implements onert::exec::IExecutor.
Definition at line 66 of file TrainableExecutor.h.
  {
    return _input_tensors[index]->get_info();
  }
Referenced by onert::exec::train::TrainableExecutors::inputInfo().
inputLayout()
ir::Layout onert::exec::train::TrainableExecutor::inputLayout (uint32_t index) const inline override virtual
Get input layout at index.
Parameters
[in] index Index of input
Returns
Input operand layout
Implements onert::exec::IExecutor.
Definition at line 76 of file TrainableExecutor.h.
{ return _input_tensors[index]->layout(); }
inputSize()
uint32_t onert::exec::train::TrainableExecutor::inputSize () const inline override virtual
Get input size.
Returns
Input size
Implements onert::exec::IExecutor.
Definition at line 62 of file TrainableExecutor.h.
{ return _input_tensors.size(); }
Referenced by onert::exec::train::TrainableExecutors::inputSize().
iterateTrainableTensors()
void onert::exec::train::TrainableExecutor::iterateTrainableTensors (const std::function< void(const ir::OperandIndex &, const backend::train::ITrainableTensor *)> & fn) const
Definition at line 212 of file TrainableExecutor.cc.
{
  _tensor_regs.iterateTrainableTensors(fn);
}
References onert::compiler::train::TensorRegistries::iterateTrainableTensors().
Referenced by onert::exec::train::TrainableExecutors::iterateTrainableTensors().
outputBuffer()
const uint8_t * onert::exec::train::TrainableExecutor::outputBuffer (uint32_t index) const inline final virtual
Get output buffer at index.
Parameters
[in] index Index of output
Returns
Output buffer
Implements onert::exec::IExecutor.
Definition at line 83 of file TrainableExecutor.h.
  {
    return _output_tensors[index]->buffer();
  }
Referenced by onert::exec::train::TrainableExecutors::outputBuffer().
outputInfo()
const ir::OperandInfo & onert::exec::train::TrainableExecutor::outputInfo (uint32_t index) const inline override virtual
Get output info at index.
Parameters
[in] index Index of output
Returns
Output operand info
Implements onert::exec::IExecutor.
Definition at line 71 of file TrainableExecutor.h.
  {
    return _output_tensors[index]->get_info();
  }
Referenced by onert::exec::train::TrainableExecutors::outputInfo().
outputLayout()
ir::Layout onert::exec::train::TrainableExecutor::outputLayout (uint32_t index) const inline override virtual
Get output layout at index.
Parameters
[in] index Index of output
Returns
Output operand layout
Implements onert::exec::IExecutor.
Definition at line 78 of file TrainableExecutor.h.
  {
    return _output_tensors[index]->layout();
  }
outputSize()
uint32_t onert::exec::train::TrainableExecutor::outputSize () const inline override virtual
Get output size.
Returns
Output size
Implements onert::exec::IExecutor.
Definition at line 64 of file TrainableExecutor.h.
{ return _output_tensors.size(); }
Referenced by onert::exec::train::TrainableExecutors::outputSize().
setIndexedRanks()
void onert::exec::train::TrainableExecutor::setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >) inline final virtual
Set an ordering on operations.
Parameters
[in] ranks The table encoding the ordering
Implements onert::exec::IExecutor.
Definition at line 94 of file TrainableExecutor.h.
  {
    _indexed_ranks = std::move(ranks);
  };
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/train/TrainableExecutor.h
runtime/onert/core/src/exec/train/TrainableExecutor.cc