ONE - On-device Neural Engine: onert::ir::train::TrainingIndex< T > Class Template Reference
onert::ir::train::TrainingIndex< T > Class Template Reference
Class that provides index of tensor for training.
#include <Index.h>
Public Member Functions
TrainingIndex ()
Construct TrainingOperationIndex object.
TrainingIndex (const T &index, bool is_forward)
Construct TrainingOperationIndex object.
const T & index () const
Get index.
bool is_forward () const
Get whether the tensor is forward tensor or not.
bool valid () const
Check if the index is valid or not.
bool operator== (const TrainingIndex &other) const
operator overloading function for ==
bool operator!= (const TrainingIndex &other) const
operator overloading function for !=
bool operator< (const TrainingIndex &other) const
operator overloading function for <
Detailed Description
template<typename T>
class onert::ir::train::TrainingIndex< T >
Class that provides index of tensor for training.
Template Parameters
T Type of index
Definition at line 33 of file Index.h.
Constructor & Destructor Documentation
TrainingIndex() [1/2]
template<typename T > onert::ir::train::TrainingIndex< T >::TrainingIndex () inline
Construct TrainingOperationIndex object.
Parameters
index The operation index
is_forward Whether the tensor is forward tensor or not
Definition at line 41 of file Index.h.
                  : _index{T{}}, _is_forward{true}
  {
    // DO NOTHING
  }
TrainingIndex() [2/2]
template<typename T > onert::ir::train::TrainingIndex< T >::TrainingIndex (const T & index, bool is_forward) inline
Construct TrainingOperationIndex object.
Template Parameters
T Type of index
Parameters
index The operation index
is_forward Whether the tensor is forward tensor or not
Definition at line 52 of file Index.h.
                                                 : _index{index}, _is_forward{is_forward}
  {
    // DO NOTHING
  }
Member Function Documentation
index()
template<typename T > const T & onert::ir::train::TrainingIndex< T >::index () const inline
Get index.
Returns
index
Definition at line 63 of file Index.h.
{ return _index; }
Referenced by onert.experimental.train.dataloader.DataLoader::__next__(), onert::ir::train::operator<<(), onert::ir::train::operator<<(), and onert::ir::train::TrainingIndex< T >::operator==().
is_forward()
template<typename T > bool onert::ir::train::TrainingIndex< T >::is_forward () const inline
Get whether the tensor is forward tensor or not.
Returns
true if the tensor is forward tensor
Definition at line 69 of file Index.h.
{ return _is_forward; }
Referenced by onert::ir::train::TrainingIndex< T >::operator==().
operator!=()
template<typename T > bool onert::ir::train::TrainingIndex< T >::operator!= (const TrainingIndex< T > & other) const inline
operator overloading function for !=
Returns
Whether two TrainingIndex are differenct
Definition at line 95 of file Index.h.
{ return !(*this == other); }
operator<()
template<typename T > bool onert::ir::train::TrainingIndex< T >::operator< (const TrainingIndex< T > & other) const inline
operator overloading function for <
Returns
Whether this TrainingIndex is less than other TrainingIndex
Definition at line 102 of file Index.h.
  {
    return std::hash<TrainingIndex<T>>{}(*this) < std::hash<TrainingIndex<T>>{}(other);
  }
operator==()
template<typename T > bool onert::ir::train::TrainingIndex< T >::operator== (const TrainingIndex< T > & other) const inline
operator overloading function for ==
Returns
Whether two TrainingIndex are equal
Definition at line 85 of file Index.h.
  {
    return (!_index.valid() && !other.index().valid()) ||
           (_index == other.index() && _is_forward == other.is_forward());
  }
References onert::ir::train::TrainingIndex< T >::index(), and onert::ir::train::TrainingIndex< T >::is_forward().
valid()
template<typename T > bool onert::ir::train::TrainingIndex< T >::valid () const inline
Check if the index is valid or not.
Returns
true if the index is valid, false otherwise
Definition at line 77 of file Index.h.
{ return _index.valid(); }
Referenced by onert::ir::train::UseDefChain::insertTrainingDef().
The documentation for this class was generated from the following file:
runtime/onert/core/include/ir/train/Index.h