ONE - On-device Neural Engine: EventCollector Class Reference
EventCollector Class Reference
#include <EventCollector.h>
Data Structures
struct Event
class EventVisitor
struct OpSeqEvent
struct SubgEvent
Public Types
enum class Edge { BEGIN , END }
Public Member Functions
EventCollector (EventRecorder *rec)
template<typename EventT >
void onEvent (const EventT &event)
Protected Attributes
EventRecorder * _rec
Detailed Description
Definition at line 28 of file EventCollector.h.
Member Enumeration Documentation
Edge
enum class EventCollector::Edge strong
Enumerator
BEGIN
END
Definition at line 31 of file EventCollector.h.
  {
    BEGIN,
    END
  };
Constructor & Destructor Documentation
EventCollector()
EventCollector::EventCollector (EventRecorder * rec) inline
Definition at line 103 of file EventCollector.h.
                                     : _rec{rec}
  {
    // DO NOTHING
  }
Member Function Documentation
onEvent()
template<typename EventT > void EventCollector::onEvent (const EventT & event)
Definition at line 127 of file EventCollector.cc.
{
  auto ts = timestamp();
  DurationEventBuilder builder(ts);
  switch (event.edge)
  {
    case Edge::BEGIN:
    {
      auto duration_evt = builder.build(event, "B");
      _rec->emit(std::move(duration_evt));
      break;
    }
    case Edge::END:
    {
      auto duration_evt = builder.build(event, "E");
      _rec->emit(std::move(duration_evt));
      break;
    }
  }
// TODO: Add resurece measurement(e.g. RSS)
// when ready with low overhead in release build
#ifdef DEBUG
  emit_rusage(_rec, ts);
#endif
}
References _rec, BEGIN, EventRecorder::emit(), and END.
Referenced by onert::exec::TracingObserver::handleJobBegin(), onert::exec::TracingObserver::handleJobEnd(), onert::exec::TracingObserver::handleSubgraphBegin(), and onert::exec::TracingObserver::handleSubgraphEnd().
Field Documentation
_rec
EventRecorder* EventCollector::_rec protected
Definition at line 112 of file EventCollector.h.
Referenced by onEvent().
The documentation for this class was generated from the following files:
runtime/onert/core/src/util/EventCollector.h
runtime/onert/core/src/util/EventCollector.cc