ONE - On-device Neural Engine: luci::compute::FullyConnected Class Reference
luci::compute::FullyConnected Class Reference
#include <FullyConnected.h>
Public Member Functions
FullyConnected ()=default
FullyConnectedParams & params (void)
bool keep_num_dims (void) const
void keep_num_dims (bool knd)
void input (const loco::TensorShape &shape, const float *data)
void weights (const loco::TensorShape &shape, const float *data)
void bias (const loco::TensorShape &shape, const float *data)
void fused_act_func (FusedActFunc func)
void output (float *data)
bool prepare (void)
const loco::TensorShape & output_shape (void) const
void compute (void)
Detailed Description
Definition at line 29 of file FullyConnected.h.
Constructor & Destructor Documentation
FullyConnected()
luci::compute::FullyConnected::FullyConnected () default
Member Function Documentation
bias()
void luci::compute::FullyConnected::bias (const loco::TensorShape & shape, const float * data) inline
Definition at line 52 of file FullyConnected.h.
  {
    _bias_shape = shape;
    _bias_data = data;
  }
References flatbuffers::data().
compute()
void luci::compute::FullyConnected::compute (void)
Definition at line 76 of file FullyConnected.cpp.
{
  assert(_input_data != nullptr);
  assert(_weights_data != nullptr);
  // NOTE _bias_shape can be nullptr
  assert(_output_data != nullptr);
  // NOTE if this fails, structure may have changed
  static_assert(sizeof(compute::FullyConnectedParams) == sizeof(tflite::FullyConnectedParams));
  tflite::FullyConnectedParams params;
  // clang-format off
  params.input_offset             = _params.input_offset;
  params.weights_offset           = _params.weights_offset;
  params.output_offset            = _params.output_offset;
  params.output_multiplier        = _params.output_multiplier;
  params.output_shift             = _params.output_shift;
  params.quantized_activation_min = _params.quantized_activation_min;
  params.quantized_activation_max = _params.quantized_activation_max;
  params.float_activation_min     = _params.float_activation_min;
  params.float_activation_max     = _params.float_activation_max;
  params.lhs_cacheable            = _params.lhs_cacheable;
  params.rhs_cacheable            = _params.rhs_cacheable;
  params.weights_format           = tflite_weights_format(_params.weights_format);
  // clang-format on
  tflite::reference_ops::FullyConnected(
    params, tflite_shape(_input_shape), _input_data, tflite_shape(_weights_shape), _weights_data,
    tflite_shape(_bias_shape), _bias_data, tflite_shape(_output_shape), _output_data);
}
References luci::compute::FullyConnectedParams::float_activation_max, luci::compute::FullyConnectedParams::float_activation_min, luci::compute::FullyConnectedParams::input_offset, luci::compute::FullyConnectedParams::lhs_cacheable, luci::compute::FullyConnectedParams::output_multiplier, luci::compute::FullyConnectedParams::output_offset, luci::compute::FullyConnectedParams::output_shift, params(), luci::compute::FullyConnectedParams::quantized_activation_max, luci::compute::FullyConnectedParams::quantized_activation_min, luci::compute::FullyConnectedParams::rhs_cacheable, luci::compute::tflite_shape(), luci::compute::tflite_weights_format(), luci::compute::FullyConnectedParams::weights_format, and luci::compute::FullyConnectedParams::weights_offset.
fused_act_func()
void luci::compute::FullyConnected::fused_act_func (FusedActFunc func) inline
Definition at line 58 of file FullyConnected.h.
{ _fused_act_func = func; };
input()
void luci::compute::FullyConnected::input (const loco::TensorShape & shape, const float * data) inline
Definition at line 40 of file FullyConnected.h.
  {
    _input_shape = shape;
    _input_data = data;
  }
References flatbuffers::data().
keep_num_dims() [1/2]
void luci::compute::FullyConnected::keep_num_dims (bool knd) inline
Definition at line 38 of file FullyConnected.h.
{ _keep_num_dims = knd; }
keep_num_dims() [2/2]
bool luci::compute::FullyConnected::keep_num_dims (void) const inline
Definition at line 37 of file FullyConnected.h.
{ return _keep_num_dims; }
output()
void luci::compute::FullyConnected::output (float * data) inline
Definition at line 60 of file FullyConnected.h.
{ _output_data = data; }
References flatbuffers::data().
output_shape()
const loco::TensorShape & luci::compute::FullyConnected::output_shape (void) const inline
Definition at line 64 of file FullyConnected.h.
{ return _output_shape; }
params()
FullyConnectedParams & luci::compute::FullyConnected::params (void) inline
Definition at line 35 of file FullyConnected.h.
{ return _params; }
Referenced by compute().
prepare()
bool luci::compute::FullyConnected::prepare (void)
Definition at line 37 of file FullyConnected.cpp.
{
  if (_input_shape.rank() < 1 || _weights_shape.rank() != 2)
    return false;
  auto const input_elems = element_count(&_input_shape);
  auto const weights_height = _weights_shape.dim(0).value();
  auto const weights_width = _weights_shape.dim(1).value();
  if (weights_height == 0 || weights_width == 0)
    return false;
  if (input_elems % weights_width != 0)
    return false;
  auto const batch_size = input_elems / weights_width;
  auto const num_units = weights_height;
  if (_bias_data)
  {
    if (element_count(&_bias_shape) != num_units)
      return false;
  }
  get_act_minmax(_fused_act_func, _params.float_activation_min, _params.float_activation_max);
  if (_keep_num_dims)
  {
    _output_shape.rank(_input_shape.rank());
    for (uint32_t i = 0; i < _input_shape.rank(); i++)
      _output_shape.dim(i) = _input_shape.dim(i);
    _output_shape.dim(_input_shape.rank() - 1) = num_units;
  }
  else
  {
    _output_shape.rank(2);
    _output_shape.dim(0) = batch_size;
    _output_shape.dim(1) = num_units;
  }
  return true;
}
References loco::TensorShape::dim(), luci::compute::FullyConnectedParams::float_activation_max, luci::compute::FullyConnectedParams::float_activation_min, luci::compute::get_act_minmax(), loco::TensorShape::rank(), and loco::Dimension::value().
weights()
void luci::compute::FullyConnected::weights (const loco::TensorShape & shape, const float * data) inline
Definition at line 46 of file FullyConnected.h.
  {
    _weights_shape = shape;
    _weights_data = data;
  }
References flatbuffers::data().
The documentation for this class was generated from the following files:
compiler/luci-compute/include/luci_compute/FullyConnected.h
compiler/luci-compute/src/FullyConnected.cpp