ONE - On-device Neural Engine: onert::exec::JSON Class Reference
onert::exec::JSON Class Reference
#include <JSONExecTime.h>
Public Member Functions
JSON (const std::vector< const backend::Backend * > &backends, MeasurementData &measurements)
void storeOperationsExecTime () const
Update _measurement_file with new data.
Detailed Description
Definition at line 43 of file JSONExecTime.h.
Constructor & Destructor Documentation
JSON()
onert::exec::JSON::JSON (const std::vector< const backend::Backend * > & backends, MeasurementData & measurements) inline explicit
Definition at line 46 of file JSONExecTime.h.
    : _measurement_file("exec_time.json"), _backends(), _measurements(measurements)
  {
    for (const auto b : backends)
    {
      _backends.emplace(b->config()->id(), b);
    }
    loadOperationsExecTime();
  };
Member Function Documentation
storeOperationsExecTime()
void onert::exec::JSON::storeOperationsExecTime () const
Update _measurement_file with new data.
Definition at line 138 of file JSONExecTime.cc.
{
  std::ofstream stream(_measurement_file);
  if (!stream.is_open())
  {
    throw std::runtime_error("Failed to save backend config file");
  }
  else
  {
    stream << "{";
    for (const auto &backend : _measurements)
    {
      printString(backend.first->config()->id(), stream);
      stream << ": {";
      for (const auto &operation : backend.second)
      {
        printString(operation.first, stream);
        stream << ": {";
        for (const auto &type : operation.second)
        {
          printBool(type.first, stream);
          stream << ": [";
          printOperation(type.second, stream);
          stream << "], ";
        }
        stream.seekp(-2, std::ofstream::end);
        stream << "}, ";
      }
      stream.seekp(-2, std::ofstream::end);
      stream << "}, ";
    }
    stream.seekp(-2, std::ofstream::end);
    stream << "}";
    stream.close();
  }
}
References onert::exec::printBool(), and onert::exec::printString().
Referenced by onert::exec::ExecTime::storeOperationsExecTime().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/JSONExecTime.h
runtime/onert/core/src/exec/JSONExecTime.cc