ONE - On-device Neural Engine: onert::ir::operation::Pool2D Class Reference
onert::ir::operation::Pool2D Class Reference
#include <Pool2D.h>
Data Structures
struct Param
Public Types
enum Input { INPUT = 0 }
enum class PoolType { AVG , L2 , MAX }
Public Member Functions
Pool2D (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, const Param &param)
void accept (OperationVisitor &v) const override
std::string name () const override
OpCode opcode () const final
const Param & param () const
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
void replaceInputs (const OperandIndex &from, const OperandIndex &to)
void replaceOutputs (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const
const OperandIndexSequence & getOutputs () const
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Detailed Description
Definition at line 33 of file Pool2D.h.
Member Enumeration Documentation
Input
enum onert::ir::operation::Pool2D::Input
Enumerator
INPUT
Definition at line 36 of file Pool2D.h.
  {
    INPUT = 0
  };
PoolType
enum class onert::ir::operation::Pool2D::PoolType strong
Enumerator
AVG
L2
MAX
Definition at line 41 of file Pool2D.h.
  {
    AVG,
    L2,
    MAX,
  };
Constructor & Destructor Documentation
Pool2D()
onert::ir::operation::Pool2D::Pool2D (const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, const Param & param)
Definition at line 31 of file Pool2D.cc.
  : Operation{OperandConstraint::createExact(1u), inputs, outputs}, _param{param}
{
}
Member Function Documentation
accept()
void onert::ir::operation::Pool2D::accept (OperationVisitor & v) const override virtual
Implements onert::ir::Operation.
Definition at line 29 of file Pool2D.cc.
{ v.visit(*this); }
name()
std::string onert::ir::operation::Pool2D::name () const override virtual
Reimplemented from onert::ir::Operation.
Definition at line 37 of file Pool2D.cc.
{
  using PoolType = onert::ir::operation::Pool2D::PoolType;
  static const std::unordered_map<PoolType, std::string> name_map{
    {PoolType::AVG, "Avg" + std::string{toString(opcode())}},
    {PoolType::L2, "L2" + std::string{toString(opcode())}},
    {PoolType::MAX, "Max" + std::string{toString(opcode())}}};
  return name_map.at(_param.op_type);
}
References AVG, L2, MAX, onert::ir::operation::Pool2D::Param::op_type, opcode(), and onert::ir::toString().
Referenced by onert::ir::OperationDumper::visit().
opcode()
OpCode onert::ir::operation::Pool2D::opcode () const inline final virtual
Implements onert::ir::Operation.
Definition at line 65 of file Pool2D.h.
{ return OpCode::Pool2D; }
Referenced by name().
param()
const Param & onert::ir::operation::Pool2D::param () const inline
Definition at line 68 of file Pool2D.h.
{ return _param; }
Referenced by onert::backend::cpu::KernelGenerator::visit(), and onert::ir::OperationDumper::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/operation/Pool2D.h
runtime/onert/core/src/ir/operation/Pool2D.cc