ONE - On-device Neural Engine: moco::TFConst Class Reference
moco::TFConst Class Reference final
IR for tf.constant.
#include <TFConst.h>
Public Member Functions
TFConst ()=default
template<loco::DataType DT>
uint32_t size (void) const
template<loco::DataType DT>
void size (uint32_t size)
template<loco::DataType DT>
const loco::DataTypeImpl< DT >::Type & at (uint32_t n) const
template<loco::DataType DT>
loco::DataTypeImpl< DT >::Type & at (uint32_t n)
Public Member Functions inherited from moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Const > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::Const >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 0, TFNodeImpl< TFOpcode::Const > >
loco::Use * at (unsigned n) const
Detailed Description
IR for tf.constant.
Note
TFConst corresponds to the following GraphDef
Implementation for this class came from Canonical ConstGen Read comments in loco::ConstGen for details
Definition at line 64 of file TFConst.h.
Constructor & Destructor Documentation
TFConst()
moco::TFConst::TFConst () default
Member Function Documentation
at() [1/2]
template<loco::DataType DT> loco::DataTypeImpl< DT >::Type & moco::TFConst::at (uint32_t n)
Definition at line 45 of file TFConst.cpp.
{
  assert(dtype() == DT);
  assert(n < size<DT>());
  return *(reinterpret_cast<typename loco::DataTypeImpl<DT>::Type *>(_data.data()) + n);
}
at() [2/2]
template<loco::DataType DT> const loco::DataTypeImpl< DT >::Type & moco::TFConst::at (uint32_t n) const
Definition at line 38 of file TFConst.cpp.
{
  assert(dtype() == DT);
  assert(n < size<DT>());
  return *(reinterpret_cast<const typename loco::DataTypeImpl<DT>::Type *>(_data.data()) + n);
}
Referenced by moco::scalar_from_const< float >(), and moco::scalar_from_const< int32_t >().
size() [1/2]
template<loco::DataType DT> void moco::TFConst::size (uint32_t size)
Definition at line 31 of file TFConst.cpp.
{
  assert(dtype() == DT);
  _data.resize(l * sizeof(typename loco::DataTypeImpl<DT>::Type));
}
size() [2/2]
template<loco::DataType DT> uint32_t moco::TFConst::size (void) const
Definition at line 24 of file TFConst.cpp.
{
  assert(dtype() == DT);
  assert(_data.size() % sizeof(typename loco::DataTypeImpl<DT>::Type) == 0);
  return _data.size() / sizeof(typename loco::DataTypeImpl<DT>::Type);
}
Referenced by moco::ConstGraphBuilder::build().
The documentation for this class was generated from the following files:
compiler/moco/lang/include/moco/IR/Nodes/TFConst.h
compiler/moco/lang/src/IR/Nodes/TFConst.cpp