ONE - On-device Neural Engine: nncc::core::ADT::kernel::Shape Class Reference
nncc::core::ADT::kernel::Shape Class Reference
#include <Shape.h>
Public Member Functions
Shape (uint32_t count, uint32_t depth, uint32_t height, uint32_t width)
uint32_t count (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
Detailed Description
Definition at line 34 of file Shape.h.
Constructor & Destructor Documentation
Shape()
nncc::core::ADT::kernel::Shape::Shape (uint32_t count, uint32_t depth, uint32_t height, uint32_t width) inline
Definition at line 37 of file Shape.h.
    : _count{count}, _depth{depth}, _height{height}, _width{width}
  {
    // DO NOTHING
  }
Member Function Documentation
count()
uint32_t nncc::core::ADT::kernel::Shape::count (void) const inline
Definition at line 44 of file Shape.h.
{ return _count; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), dump(), nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::kernel::num_elements(), nnsuite::conv::RandomModel::RandomModel(), and coco::KernelLayouts::Generic::reorder().
depth()
uint32_t nncc::core::ADT::kernel::Shape::depth (void) const inline
Definition at line 45 of file Shape.h.
{ return _depth; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnop::conv(), nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::kernel::num_elements(), nnsuite::conv::RandomModel::RandomModel(), and coco::KernelLayouts::Generic::reorder().
height()
uint32_t nncc::core::ADT::kernel::Shape::height (void) const inline
Definition at line 46 of file Shape.h.
{ return _height; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnop::conv(), nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::kernel::num_elements(), nnsuite::conv::RandomModel::RandomModel(), and coco::KernelLayouts::Generic::reorder().
width()
uint32_t nncc::core::ADT::kernel::Shape::width (void) const inline
Definition at line 47 of file Shape.h.
{ return _width; }
Referenced by morph::caffe::as_tensor_shape(), morph::nnapi::as_tensor_shape(), morph::tflite::as_tensor_shape(), nnop::conv(), nncc::core::ADT::kernel::IndexEnumerator::IndexEnumerator(), nncc::core::ADT::kernel::num_elements(), nnsuite::conv::RandomModel::RandomModel(), and coco::KernelLayouts::Generic::reorder().
The documentation for this class was generated from the following file:
compiler/angkor/include/nncc/core/ADT/kernel/Shape.h