ONE - On-device Neural Engine: onert_micro::core::OMRuntimeContext Class Reference
onert_micro::core::OMRuntimeContext Class Reference
#include <OMRuntimeContext.h>
Public Member Functions
OMRuntimeContext ()=default
OMRuntimeContext (const OMRuntimeContext &)=delete
OMRuntimeContext & operator= (const OMRuntimeContext &)=delete
OMRuntimeContext && operator= (const OMRuntimeContext &&)=delete
OMRuntimeContext (OMRuntimeContext &&)=default
~OMRuntimeContext ()=default
OMStatus setModel (const char *model_ptr, uint32_t graph_index)
OMStatus setWofFile (char *wof_ptr)
OMStatus setTrainConfigFile (char *train_config_file_ptr)
std::unordered_map< uint16_t, uint8_t > getTrainableOpsIndexes ()
bool isConstTensor (uint32_t tensor_index)
const reader::CircleValues * getCircleOutputs ()
const reader::CircleValues * getCircleInputs ()
const reader::CircleTensors * getCircleTensors ()
const reader::CircleOperators * getCircleOperators ()
const reader::CircleOperatorCodes * getCircleOpcodes ()
const circle::Operator * getCircleOperatorAt (uint16_t index)
const circle::Tensor * getTensorByIndex (int32_t tensor_index)
uint32_t getGraphInputTensorIndex (uint32_t index)
uint32_t getGraphOutputTensorIndex (uint32_t index)
OMStatus getConstDataByTensorIndex (uint8_t **data, uint16_t tensor_index)
Detailed Description
Definition at line 36 of file OMRuntimeContext.h.
Constructor & Destructor Documentation
OMRuntimeContext() [1/3]
onert_micro::core::OMRuntimeContext::OMRuntimeContext () default
OMRuntimeContext() [2/3]
onert_micro::core::OMRuntimeContext::OMRuntimeContext (const OMRuntimeContext &) delete
OMRuntimeContext() [3/3]
onert_micro::core::OMRuntimeContext::OMRuntimeContext (OMRuntimeContext &&) default
~OMRuntimeContext()
onert_micro::core::OMRuntimeContext::~OMRuntimeContext () default
Member Function Documentation
getCircleInputs()
const reader::CircleValues * onert_micro::core::OMRuntimeContext::getCircleInputs () inline
Definition at line 93 of file OMRuntimeContext.h.
{ return _reader.inputs(); }
References onert_micro::core::reader::OMCircleReader::inputs().
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), and onert_micro::core::OMRuntimeGraph::getNumberOfInputs().
getCircleOpcodes()
const reader::CircleOperatorCodes * onert_micro::core::OMRuntimeContext::getCircleOpcodes () inline
Definition at line 98 of file OMRuntimeContext.h.
{ return _reader.opcodes(); }
References onert_micro::core::reader::OMCircleReader::opcodes().
Referenced by onert_micro::import::OMKernelConfiguration::configureKernels(), onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(), onert_micro::train::OMBackpropExecute::runBackward(), and onert_micro::execute::OMKernelExecute::runForward().
getCircleOperatorAt()
const circle::Operator * OMRuntimeContext::getCircleOperatorAt (uint16_t index)
Definition at line 22 of file OMRuntimeContext.cpp.
{
  const auto *operators = _reader.operators();
  assert(index < operators->size());
  return operators->operator[](index);
}
References onert_micro::core::reader::OMCircleReader::operators(), and size.
Referenced by onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(), and onert_micro::execute::OMRuntimeKernel::readKernel().
getCircleOperators()
const reader::CircleOperators * OMRuntimeContext::getCircleOperators ()
Definition at line 29 of file OMRuntimeContext.cpp.
{
  return _reader.operators();
}
References onert_micro::core::reader::OMCircleReader::operators().
Referenced by onert_micro::import::OMKernelConfiguration::configureKernels(), onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), onert_micro::execute::execute_kernel_CircleGRU(), onert_micro::train::OMBackpropExecute::runBackward(), and onert_micro::execute::OMKernelExecute::runForward().
getCircleOutputs()
const reader::CircleValues * onert_micro::core::OMRuntimeContext::getCircleOutputs () inline
Definition at line 92 of file OMRuntimeContext.h.
{ return _reader.outputs(); }
References onert_micro::core::reader::OMCircleReader::outputs().
Referenced by onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), onert_micro::core::train::OMTrainingHandler::evaluateMetric(), onert_micro::core::OMRuntimeGraph::getNumberOfOutputs(), and onert_micro::core::train::OMTrainingHandler::handleError().
getCircleTensors()
const reader::CircleTensors * onert_micro::core::OMRuntimeContext::getCircleTensors () inline
Definition at line 94 of file OMRuntimeContext.h.
{ return _reader.tensors(); }
References onert_micro::core::reader::OMCircleReader::tensors().
getConstDataByTensorIndex()
OMStatus OMRuntimeContext::getConstDataByTensorIndex (uint8_t ** data, uint16_t tensor_index)
Definition at line 53 of file OMRuntimeContext.cpp.
{
  auto *tensor = getTensorByIndex(tensor_index);
  if (tensor == nullptr)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  // To handle with separated weights:
  // 1) first we try to get weigths from wof file (using wof_reader)
  // 2) If it is not null -> return it
  // 3) It it is null try to get it from main circle file
  uint8_t *buffer_data = reinterpret_cast<uint8_t *>(_wof_reader.buffer(tensor_index));
  if (buffer_data != nullptr)
  {
    *data = buffer_data;
    return Ok;
  }
  auto const *buffer = _reader.buffers()->operator[](tensor->buffer())->data();
  if (buffer == nullptr)
    return Ok;
  *data = const_cast<uint8_t *>(buffer->data());
  return Ok;
}
References onert_micro::core::reader::OMWeightOnlyFormatReader::buffer(), onert_micro::core::reader::OMCircleReader::buffers(), getTensorByIndex(), onert_micro::Ok, OM_LOG_AND_RETURN, and onert_micro::UnknownError.
Referenced by onert_micro::execute::OMRuntimeKernel::getDataFromStorage(), onert_micro::train::optimizers::Adam::updateWeights(), and onert_micro::train::optimizers::SGD::updateWeights().
getGraphInputTensorIndex()
uint32_t OMRuntimeContext::getGraphInputTensorIndex (uint32_t index)
Definition at line 41 of file OMRuntimeContext.cpp.
{
  auto *inputs = _reader.inputs();
  return inputs->operator[](index);
}
References onert_micro::core::reader::OMCircleReader::inputs().
Referenced by onert_micro::core::OMRuntimeGraph::getInputDataAt(), onert_micro::core::OMRuntimeGraph::getInputDataTypeSize(), and onert_micro::core::OMRuntimeGraph::getInputSizeAt().
getGraphOutputTensorIndex()
uint32_t OMRuntimeContext::getGraphOutputTensorIndex (uint32_t index)
Definition at line 47 of file OMRuntimeContext.cpp.
{
  auto *outputs = _reader.outputs();
  return outputs->operator[](index);
}
References onert_micro::core::reader::OMCircleReader::outputs().
Referenced by onert_micro::import::configure_kernel_CircleWhile(), onert_micro::core::OMRuntimeGraph::getOutputDataAt(), onert_micro::core::OMRuntimeGraph::getOutputDataTypeSize(), and onert_micro::core::OMRuntimeGraph::getOutputSizeAt().
getTensorByIndex()
const circle::Tensor * OMRuntimeContext::getTensorByIndex (int32_t tensor_index)
Definition at line 34 of file OMRuntimeContext.cpp.
{
  if (tensor_index == -1)
    return nullptr;
  return _reader.tensors()->operator[](tensor_index);
}
References onert_micro::core::reader::OMCircleReader::tensors().
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocate(), onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::core::memory::OMRuntimeAllocator::clearAllTensorsData(), onert_micro::import::configure_kernel_CircleWhile(), onert_micro::core::train::OMTrainingHandler::evaluateMetric(), getConstDataByTensorIndex(), onert_micro::core::OMRuntimeGraph::getInputDataTypeSize(), onert_micro::core::OMRuntimeGraph::getInputSizeAt(), onert_micro::core::OMRuntimeGraph::getOutputDataTypeSize(), onert_micro::core::OMRuntimeGraph::getOutputSizeAt(), onert_micro::train::optimizers::Adam::handle(), onert_micro::train::optimizers::SGD::handle(), onert_micro::core::train::OMTrainingHandler::handleError(), onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(), onert_micro::execute::OMRuntimeKernel::readKernel(), onert_micro::train::optimizers::Adam::updateWeights(), and onert_micro::train::optimizers::SGD::updateWeights().
getTrainableOpsIndexes()
std::unordered_map< uint16_t, uint8_t > onert_micro::core::OMRuntimeContext::getTrainableOpsIndexes () inline
Definition at line 85 of file OMRuntimeContext.h.
  {
    return _train_config_reader.getTrainableOpsIndexes();
  }
References onert_micro::core::reader::OMTrainingConfigReader::getTrainableOpsIndexes().
Referenced by onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan(), onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(), and onert_micro::train::OMBackpropExecute::runBackward().
isConstTensor()
bool onert_micro::core::OMRuntimeContext::isConstTensor (uint32_t tensor_index) inline
Definition at line 90 of file OMRuntimeContext.h.
{ return _reader.isConstTensor(tensor_index); }
References onert_micro::core::reader::OMCircleReader::isConstTensor().
Referenced by onert_micro::import::configure_kernel_CircleReshape(), onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::import::OMExecutionPlanCreator::createExecutionPlan(), and onert_micro::import::OMExecutionPlanCreator::createForwardExecutionPlan().
operator=() [1/2]
OMRuntimeContext && onert_micro::core::OMRuntimeContext::operator= (const OMRuntimeContext &&) delete
operator=() [2/2]
OMRuntimeContext & onert_micro::core::OMRuntimeContext::operator= (const OMRuntimeContext &) delete
setModel()
OMStatus onert_micro::core::OMRuntimeContext::setModel (const char * model_ptr, uint32_t graph_index) inline
Definition at line 51 of file OMRuntimeContext.h.
  {
    OMStatus status;
    status = _reader.parse(model_ptr);
    if (status != Ok)
      return status;
    status = _reader.select_subgraph(graph_index);
    if (status != Ok)
      return status;
    return Ok;
  }
References onert_micro::Ok, onert_micro::core::reader::OMCircleReader::parse(), and onert_micro::core::reader::OMCircleReader::select_subgraph().
Referenced by onert_micro::core::OMRuntimeModule::importModel(), and onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
setTrainConfigFile()
OMStatus onert_micro::core::OMRuntimeContext::setTrainConfigFile (char * train_config_file_ptr) inline
Definition at line 74 of file OMRuntimeContext.h.
  {
    OMStatus status = Ok;
    _train_config_reader.parse(train_config_file_ptr);
    status = _train_config_reader.validate(&_reader);
    if (status != Ok)
      return status;
    return Ok;
  }
References onert_micro::Ok, onert_micro::core::reader::OMTrainingConfigReader::parse(), and onert_micro::core::reader::OMTrainingConfigReader::validate().
Referenced by onert_micro::core::OMRuntimeModule::importModel(), and onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
setWofFile()
OMStatus onert_micro::core::OMRuntimeContext::setWofFile (char * wof_ptr) inline
Definition at line 63 of file OMRuntimeContext.h.
  {
    OMStatus status;
    _wof_reader.parse(wof_ptr);
    status = _wof_reader.validate(&_reader);
    if (status != Ok)
      return status;
    return Ok;
  }
References onert_micro::Ok, onert_micro::core::reader::OMWeightOnlyFormatReader::parse(), and onert_micro::core::reader::OMWeightOnlyFormatReader::validate().
Referenced by onert_micro::core::OMRuntimeModule::importModel(), and onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/OMRuntimeContext.h
onert-micro/onert-micro/src/core/OMRuntimeContext.cpp