ONE - On-device Neural Engine: onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer > Class Template Reference
onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer > Class Template Reference
#include <AclBackendContext.h>
Public Member Functions
AclBackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< T_TensorBuilder > tensor_builder=nullptr, std::shared_ptr< T_ConstantInitializer > constant_initializer=nullptr, std::shared_ptr< T_KernelGenerator > kernel_gen=nullptr)
ITensorRegistry * genTensors () override
Public Member Functions inherited from onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< T_TensorBuilder > tensor_builder=nullptr, std::shared_ptr< T_ConstantInitializer > constant_initializer=nullptr, std::shared_ptr< T_KernelGenerator > kernel_gen=nullptr)
FunctionMap genKernels () override
Public Member Functions inherited from onert::backend::BackendContext
BackendContext (const Backend *backend, ContextData &&data, std::shared_ptr< ITensorRegistry > tensor_registry=nullptr)
virtual ~BackendContext ()=default
const Backend * backend () const
const ir::Graph * graph () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
const ContextData & data () const
virtual ITensorRegistry * genTensors ()=0
virtual FunctionMap genKernels ()=0
Data Fields
std::shared_ptr< T_Optimizer > optimizer
Data Fields inherited from onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >
std::shared_ptr< T_TensorBuilder > tensor_builder
std::shared_ptr< T_ConstantInitializer > constant_initializer
std::shared_ptr< T_KernelGenerator > kernel_gen
Data Fields inherited from onert::backend::BackendContext
std::shared_ptr< ITensorRegistry > tensor_registry
Protected Member Functions
void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout) override
Protected Member Functions inherited from onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >
void initConsts ()
virtual void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout)=0
void planTensors ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::BackendContext
const Backend * _backend {nullptr}
ContextData _data
Detailed Description
template<typename T_TensorBuilder, typename T_ConstantInitializer, typename T_KernelGenerator, typename T_Optimizer>
class onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >
Definition at line 38 of file AclBackendContext.h.
Constructor & Destructor Documentation
AclBackendContext()
template<typename T_TensorBuilder , typename T_ConstantInitializer , typename T_KernelGenerator , typename T_Optimizer > onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::AclBackendContext (const Backend * backend, ContextData && data, std::shared_ptr< ITensorRegistry > tensor_registry = nullptr, std::shared_ptr< T_TensorBuilder > tensor_builder = nullptr, std::shared_ptr< T_ConstantInitializer > constant_initializer = nullptr, std::shared_ptr< T_KernelGenerator > kernel_gen = nullptr) inline
Definition at line 43 of file AclBackendContext.h.
    : onert::backend::cl_common::BackendContext<T_TensorBuilder, T_ConstantInitializer,
                                                T_KernelGenerator>(
        backend, std::move(data), tensor_registry, tensor_builder, constant_initializer, kernel_gen)
  {
    // DO NOTHING
  }
Member Function Documentation
genTensors()
template<typename T_TensorBuilder , typename T_ConstantInitializer , typename T_KernelGenerator , typename T_Optimizer > ITensorRegistry * onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors () inline override virtual
Implements onert::backend::BackendContext.
Definition at line 55 of file AclBackendContext.h.
  {
    optimizer->optimize();
    this->graph()->operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &obj) {
      if (this->external_operands().contains(ind))
        return;
      const auto frontend_layout = this->graph()->layout();
      const auto backend_layout = this->operand_layouts().at(ind);
      ir::OperandInfo backend_info{permuteShape(obj.shape(), frontend_layout, backend_layout),
                                   obj.typeInfo(), obj.info().memAllocType(), obj.isConstant()};
      this->tensor_builder->registerTensorInfo(ind, backend_info, backend_layout);
    });
    // TODO Get compiler options from compiler, and use it rather than getting it from Env
    if (util::getConfigString(util::config::EXECUTOR) == "Linear")
    {
      this->planTensors();
    }
    else
    {
      // For the executors that does not have fixed linear execution order:
      // To make tensors never be deallocated, this is a workaround to use static memory planner
      this->graph()->operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &) {
        if (this->tensor_builder->isRegistered(ind))
          this->tensor_builder->notifyFirstUse(ind);
      });
    }
    this->tensor_builder->prepare();
    return this->tensor_registry.get();
  }
References onert::backend::BackendContext::external_operands(), onert::util::getConfigString(), onert::backend::BackendContext::graph(), onert::util::ObjectManager< Index, Object >::iterate(), onert::ir::Graph::layout(), onert::backend::BackendContext::operand_layouts(), onert::ir::Graph::operands(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::optimizer, onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::tensor_builder, and onert::backend::BackendContext::tensor_registry.
registerTensorInfo()
template<typename T_TensorBuilder , typename T_ConstantInitializer , typename T_KernelGenerator , typename T_Optimizer > void onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::registerTensorInfo (const ir::OperandIndex & ind, const ir::OperandInfo & info, ir::Layout backend_layout) inline override protected virtual
Implements onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >.
Definition at line 91 of file AclBackendContext.h.
  {
    this->tensor_builder->registerTensorInfo(ind, info, backend_layout);
  }
References info, and onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::tensor_builder.
Field Documentation
optimizer
template<typename T_TensorBuilder , typename T_ConstantInitializer , typename T_KernelGenerator , typename T_Optimizer > std::shared_ptr<T_Optimizer> onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::optimizer
Definition at line 99 of file AclBackendContext.h.
Referenced by onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors().
The documentation for this class was generated from the following file:
runtime/onert/backend/acl_common/AclBackendContext.h