ONE - On-device Neural Engine: luci::SparseIndexVector Class Reference
luci::SparseIndexVector Class Reference
#include <SparsityParam.h>
Public Member Functions
SparseIndexVector ()=default
SparseIndexVector (const SparseIndexVectorType &type, const std::vector< int32_t > &sparse_index_vec)
SparseIndexVector (SparseIndexVectorType type, const void *sparse_index_vec)
SparseIndexVector (const SparseIndexVector &sparse_index_vec)
SparseIndexVector (SparseIndexVector &&sparse_index_vec)
SparseIndexVector & operator= (const SparseIndexVector &sparse_index_vec)
SparseIndexVector & operator= (SparseIndexVector &&sparse_index_vector)
~SparseIndexVector ()
SparseIndexVectorType type (void) const
const std::vector< int32_t > * as_int32_vector (void) const
const std::vector< uint16_t > * as_uint16_vector (void) const
const std::vector< uint8_t > * as_uint8_vector (void) const
Detailed Description
Definition at line 42 of file SparsityParam.h.
Constructor & Destructor Documentation
SparseIndexVector() [1/5]
luci::SparseIndexVector::SparseIndexVector () default
Referenced by operator=().
SparseIndexVector() [2/5]
luci::SparseIndexVector::SparseIndexVector (const SparseIndexVectorType & type, const std::vector< int32_t > & sparse_index_vec) inline
Definition at line 46 of file SparsityParam.h.
    : _type{type}
  {
    switch (type)
    {
      case SparseIndexVectorType::NONE:
        break;
      case SparseIndexVectorType::I32:
      {
        _vec_ptr = static_cast<void *>(
          new std::vector<int32_t>(sparse_index_vec.begin(), sparse_index_vec.end()));
        break;
      }
      case SparseIndexVectorType::U16:
      {
        auto new_vec = new std::vector<uint16_t>(sparse_index_vec.size());
        for (uint32_t idx = 0; idx < sparse_index_vec.size(); idx++)
        {
          new_vec->at(idx) = static_cast<uint16_t>(sparse_index_vec.at(idx));
        }
        _vec_ptr = static_cast<void *>(new_vec);
        break;
      }
      case SparseIndexVectorType::U8:
      {
        auto new_vec = new std::vector<uint8_t>(sparse_index_vec.size());
        for (uint32_t idx = 0; idx < sparse_index_vec.size(); idx++)
        {
          new_vec->at(idx) = static_cast<uint8_t>(sparse_index_vec.at(idx));
        }
        _vec_ptr = static_cast<void *>(new_vec);
        break;
      }
      default:
        std::runtime_error("Invalid SparseIndexVectorType");
    }
  }
References luci::I32, luci::NONE, type(), luci::U16, and luci::U8.
SparseIndexVector() [3/5]
luci::SparseIndexVector::SparseIndexVector (SparseIndexVectorType type, const void * sparse_index_vec) inline
Definition at line 84 of file SparsityParam.h.
                                                                              : _type{type}
  {
    switch (type)
    {
      case SparseIndexVectorType::NONE:
        break;
      case SparseIndexVectorType::I32:
      {
        const std::vector<int32_t> *vec =
          static_cast<const std::vector<int32_t> *>(sparse_index_vec);
        _vec_ptr = static_cast<void *>(new std::vector<int32_t>(vec->begin(), vec->end()));
        break;
      }
      case SparseIndexVectorType::U16:
      {
        const std::vector<uint16_t> *vec =
          static_cast<const std::vector<uint16_t> *>(sparse_index_vec);
        _vec_ptr = static_cast<void *>(new std::vector<uint16_t>(vec->begin(), vec->end()));
        break;
      }
      case SparseIndexVectorType::U8:
      {
        const std::vector<uint8_t> *vec =
          static_cast<const std::vector<uint8_t> *>(sparse_index_vec);
        _vec_ptr = static_cast<void *>(new std::vector<uint8_t>(vec->begin(), vec->end()));
        break;
      }
      default:
        std::runtime_error("Invalid SparseIndexVectorType");
    }
  }
References luci::I32, luci::NONE, type(), luci::U16, and luci::U8.
SparseIndexVector() [4/5]
luci::SparseIndexVector::SparseIndexVector (const SparseIndexVector & sparse_index_vec) inline
Definition at line 116 of file SparsityParam.h.
    : SparseIndexVector(sparse_index_vec._type, sparse_index_vec._vec_ptr)
  {
  }
SparseIndexVector() [5/5]
luci::SparseIndexVector::SparseIndexVector (SparseIndexVector && sparse_index_vec) inline
Definition at line 121 of file SparsityParam.h.
    : _type{sparse_index_vec._type}, _vec_ptr{std::exchange(sparse_index_vec._vec_ptr, nullptr)}
  {
  }
~SparseIndexVector()
luci::SparseIndexVector::~SparseIndexVector () inline
Definition at line 138 of file SparsityParam.h.
  {
    switch (_type)
    {
      case SparseIndexVectorType::NONE:
        break;
      case SparseIndexVectorType::I32:
      {
        auto vec_ptr = static_cast<std::vector<int32_t> *>(_vec_ptr);
        delete vec_ptr;
        break;
      }
      case SparseIndexVectorType::U16:
      {
        auto vec_ptr = static_cast<std::vector<uint16_t> *>(_vec_ptr);
        delete vec_ptr;
        break;
      }
      case SparseIndexVectorType::U8:
      {
        auto vec_ptr = static_cast<std::vector<uint8_t> *>(_vec_ptr);
        delete vec_ptr;
        break;
      }
      default:
        break;
    }
    _vec_ptr = nullptr;
    _type = SparseIndexVectorType::NONE;
  }
References luci::I32, luci::NONE, luci::U16, and luci::U8.
Member Function Documentation
as_int32_vector()
const std::vector< int32_t > * luci::SparseIndexVector::as_int32_vector (void) const inline
Definition at line 173 of file SparsityParam.h.
  {
    return _type == SparseIndexVectorType::I32 ? static_cast<const std::vector<int32_t> *>(_vec_ptr)
                                               : nullptr;
  }
References luci::I32.
Referenced by luci::to_circle_sparse_index_vector().
as_uint16_vector()
const std::vector< uint16_t > * luci::SparseIndexVector::as_uint16_vector (void) const inline
Definition at line 178 of file SparsityParam.h.
  {
    return _type == SparseIndexVectorType::U16
             ? static_cast<const std::vector<uint16_t> *>(_vec_ptr)
             : nullptr;
  }
References luci::U16.
Referenced by luci::to_circle_sparse_index_vector().
as_uint8_vector()
const std::vector< uint8_t > * luci::SparseIndexVector::as_uint8_vector (void) const inline
Definition at line 184 of file SparsityParam.h.
  {
    return _type == SparseIndexVectorType::U8 ? static_cast<const std::vector<uint8_t> *>(_vec_ptr)
                                              : nullptr;
  }
References luci::U8.
Referenced by luci::to_circle_sparse_index_vector().
operator=() [1/2]
SparseIndexVector & luci::SparseIndexVector::operator= (const SparseIndexVector & sparse_index_vec) inline
Definition at line 126 of file SparsityParam.h.
  {
    return *this = SparseIndexVector(sparse_index_vec);
  }
References SparseIndexVector().
operator=() [2/2]
SparseIndexVector & luci::SparseIndexVector::operator= (SparseIndexVector && sparse_index_vector) inline
Definition at line 131 of file SparsityParam.h.
  {
    std::swap(_vec_ptr, sparse_index_vector._vec_ptr);
    std::swap(_type, sparse_index_vector._type);
    return *this;
  }
type()
SparseIndexVectorType luci::SparseIndexVector::type (void) const inline
Definition at line 170 of file SparsityParam.h.
{ return _type; }
Referenced by OptionBuilder.OptionBuilder::build(), SparseIndexVector(), and luci::to_circle_sparse_index_vector().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/SparsityParam.h