ONE - On-device Neural Engine: MemoryTracker Class Reference
MemoryTracker Class Reference
#include <MemoryTracker.h>
Public Member Functions
uint32_t add (const Memory *memory)
uint32_t size () const
const Memory * operator[] (size_t i) const
Detailed Description
Definition at line 31 of file MemoryTracker.h.
Member Function Documentation
add()
uint32_t MemoryTracker::add (const Memory * memory)
Definition at line 28 of file MemoryTracker.cpp.
{
  VLOG(MODEL) << __func__ << " for " << memory;
  // See if we already have this memory. If so,
  // return its index.
  auto i = mKnown.find(memory);
  if (i != mKnown.end())
  {
    return i->second;
  }
  VLOG(MODEL) << "It's new";
  // It's a new one.  Save it an assign an index to it.
  size_t next = mKnown.size();
  if (next > 0xFFFFFFFF)
  {
    LOG(ERROR) << "ANeuralNetworks more than 2^32 memories.";
    return ANEURALNETWORKS_BAD_DATA;
  }
  uint32_t idx = static_cast<uint32_t>(next);
  mKnown[memory] = idx;
  mMemories.push_back(memory);
  return idx;
}
References ANEURALNETWORKS_BAD_DATA, LOG, and VLOG.
Referenced by ExecutionBuilder::setInputFromMemory(), ModelBuilder::setOperandValueFromMemory(), and ExecutionBuilder::setOutputFromMemory().
operator[]()
const Memory * MemoryTracker::operator[] (size_t i) const inline
Definition at line 40 of file MemoryTracker.h.
{ return mMemories[i]; }
size()
uint32_t MemoryTracker::size () const inline
Definition at line 38 of file MemoryTracker.h.
{ return static_cast<uint32_t>(mKnown.size()); }
Referenced by ModelBuilder::publish(), and ExecutionBuilder::startCompute().
The documentation for this class was generated from the following files:
compiler/ann-ref/src/MemoryTracker.h
compiler/ann-ref/src/MemoryTracker.cpp