ONE - On-device Neural Engine: onert_micro::execute::OMRuntimeKernel Class Reference
onert_micro::execute::OMRuntimeKernel Class Reference
#include <OMRuntimeKernel.h>
Public Member Functions
OMRuntimeKernel ()=default
OMRuntimeKernel (const OMRuntimeKernel &)=delete
OMRuntimeKernel (OMRuntimeKernel &&)=delete
~OMRuntimeKernel ()=default
OMRuntimeKernel & operator= (const OMRuntimeKernel &)=delete
OMRuntimeKernel && operator= (const OMRuntimeKernel &&)=delete
OMStatus readKernel (uint16_t op_index, core::OMRuntimeContext &runtime_context)
OMStatus getDataFromStorage (uint16_t op_index, core::OMRuntimeStorage &storage, core::OMRuntimeContext &context)
Data Fields
const circle::Tensor * inputs [maxInputSize] = {nullptr}
const circle::Tensor * outputs [maxOutputSize] = {nullptr}
uint8_t * inputs_data [maxInputSize] = {nullptr}
uint8_t * outputs_data [maxOutputSize] = {nullptr}
int32_t inputs_index [maxInputSize] = {-1}
int32_t outputs_index [maxOutputSize] = {-1}
uint32_t outputs_num = -1
uint32_t inputs_num = -1
const circle::Operator * first_operator = nullptr
Detailed Description
Definition at line 34 of file OMRuntimeKernel.h.
Constructor & Destructor Documentation
OMRuntimeKernel() [1/3]
onert_micro::execute::OMRuntimeKernel::OMRuntimeKernel () default
OMRuntimeKernel() [2/3]
onert_micro::execute::OMRuntimeKernel::OMRuntimeKernel (const OMRuntimeKernel &) delete
OMRuntimeKernel() [3/3]
onert_micro::execute::OMRuntimeKernel::OMRuntimeKernel (OMRuntimeKernel &&) delete
~OMRuntimeKernel()
onert_micro::execute::OMRuntimeKernel::~OMRuntimeKernel () default
Member Function Documentation
getDataFromStorage()
OMStatus onert_micro::execute::OMRuntimeKernel::getDataFromStorage (uint16_t op_index, core::OMRuntimeStorage & storage, core::OMRuntimeContext & context)
Definition at line 67 of file OMRuntimeKernel.cpp.
{
  OMStatus status = Ok;
  for (uint32_t i = 0; i < inputs_num; ++i)
  {
    if (inputs_index[i] == -1)
      continue;
    status = storage.getDataByTensorIndex(&inputs_data[i], inputs_index[i]);
    if (inputs_data[i] == nullptr)
      status = context.getConstDataByTensorIndex(&inputs_data[i], inputs_index[i]);
    if (status != Ok)
      return status;
  }
  for (uint32_t i = 0; i < outputs_num; ++i)
  {
    if (outputs_index[i] == -1)
      continue;
    status = storage.getDataByTensorIndex(&outputs_data[i], outputs_index[i]);
    if (status != Ok)
      return status;
    if (storage.getKernelType(op_index) == core::Inplace)
    {
      outputs_data[i] = inputs_data[i];
      status = storage.removeTensorFromTensorIndexToData(inputs_index[i]);
      if (status != Ok)
        return status;
      status = storage.saveDataToTensorIndex(outputs_data[i], outputs_index[i]);
    }
  }
  return status;
}
References onert_micro::core::OMRuntimeContext::getConstDataByTensorIndex(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::core::OMRuntimeStorage::getKernelType(), onert_micro::core::Inplace, onert_micro::Ok, onert_micro::core::OMRuntimeStorage::removeTensorFromTensorIndexToData(), and onert_micro::core::OMRuntimeStorage::saveDataToTensorIndex().
operator=() [1/2]
OMRuntimeKernel && onert_micro::execute::OMRuntimeKernel::operator= (const OMRuntimeKernel &&) delete
operator=() [2/2]
OMRuntimeKernel & onert_micro::execute::OMRuntimeKernel::operator= (const OMRuntimeKernel &) delete
readKernel()
OMStatus onert_micro::execute::OMRuntimeKernel::readKernel (uint16_t op_index, core::OMRuntimeContext & runtime_context)
Definition at line 22 of file OMRuntimeKernel.cpp.
{
  first_operator = runtime_context.getCircleOperatorAt(op_index);
  const circle::Operator *last_operator = runtime_context.getCircleOperatorAt(op_index);
  inputs_num = first_operator->inputs()->size();
  assert(inputs_num < maxInputSize);
  if (inputs_num >= maxInputSize)
    return UnknownError;
  outputs_num = last_operator->outputs()->size();
  assert(outputs_num < maxOutputSize);
  if (outputs_num >= maxOutputSize)
    return UnknownError;
  assert(inputs_num > 0 and outputs_num > 0);
  // Read inputs
  {
    const auto *inputs_op = first_operator->inputs();
    for (uint32_t i = 0; i < inputs_num; ++i)
    {
      inputs_index[i] = inputs_op->operator[](i);
      if (inputs_index[i] != -1)
        inputs[i] = runtime_context.getTensorByIndex(inputs_index[i]);
    }
  }
  // Read outputs
  {
    const auto *outputs_op = last_operator->outputs();
    for (uint32_t i = 0; i < outputs_num; ++i)
    {
      outputs_index[i] = outputs_op->operator[](i);
      if (outputs_index[i] != -1)
        outputs[i] = runtime_context.getTensorByIndex(outputs_index[i]);
    }
  }
  return Ok;
}
References first_operator, onert_micro::core::OMRuntimeContext::getCircleOperatorAt(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), inputs, inputs_index, inputs_num, onert_micro::Ok, outputs, outputs_index, outputs_num, and onert_micro::UnknownError.
Field Documentation
first_operator
const circle::Operator* onert_micro::execute::OMRuntimeKernel::first_operator = nullptr
Definition at line 63 of file OMRuntimeKernel.h.
Referenced by readKernel().
inputs
const circle::Tensor* onert_micro::execute::OMRuntimeKernel::inputs[maxInputSize] = {nullptr}
Definition at line 51 of file OMRuntimeKernel.h.
{nullptr};
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs(), readKernel(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_inputs().
inputs_data
uint8_t* onert_micro::execute::OMRuntimeKernel::inputs_data[maxInputSize] = {nullptr}
Definition at line 54 of file OMRuntimeKernel.h.
{nullptr};
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
inputs_index
int32_t onert_micro::execute::OMRuntimeKernel::inputs_index[maxInputSize] = {-1}
Definition at line 57 of file OMRuntimeKernel.h.
{-1};
Referenced by readKernel().
inputs_num
uint32_t onert_micro::execute::OMRuntimeKernel::inputs_num = -1
Definition at line 61 of file OMRuntimeKernel.h.
Referenced by readKernel().
outputs
const circle::Tensor* onert_micro::execute::OMRuntimeKernel::outputs[maxOutputSize] = {nullptr}
Definition at line 52 of file OMRuntimeKernel.h.
{nullptr};
Referenced by validate_onnx2circle.OnnxRunner::get_outputs(), package.libnnfw_api_pybind.nnfw_session_wrapper::inference(), readKernel(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_outputs().
outputs_data
uint8_t* onert_micro::execute::OMRuntimeKernel::outputs_data[maxOutputSize] = {nullptr}
Definition at line 55 of file OMRuntimeKernel.h.
{nullptr};
outputs_index
int32_t onert_micro::execute::OMRuntimeKernel::outputs_index[maxOutputSize] = {-1}
Definition at line 58 of file OMRuntimeKernel.h.
{-1};
Referenced by readKernel().
outputs_num
uint32_t onert_micro::execute::OMRuntimeKernel::outputs_num = -1
Definition at line 60 of file OMRuntimeKernel.h.
Referenced by readKernel().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/execute/OMRuntimeKernel.h
onert-micro/onert-micro/src/execute/OMRuntimeKernel.cpp