ONE - On-device Neural Engine: luci::ProgressReporter Class Reference
luci::ProgressReporter Class Reference
#include <ProgressReporter.h>
Public Member Functions
ProgressReporter (loco::Graph *graph, logo::PhaseStrategy strategy)
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > *) override
loco::Graph * graph (void) const
logo::PhaseStrategy strategy (void) const
ProgressReporter (loco::Graph *graph, logo::PhaseStrategy strategy)
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > *) override
loco::Graph * graph (void) const
logo::PhaseStrategy strategy (void) const
Public Member Functions inherited from logo::PhaseEventListener
virtual ~PhaseEventListener ()=default
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseEnd > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassEnd > *)
Detailed Description
Definition at line 27 of file ProgressReporter.h.
Constructor & Destructor Documentation
ProgressReporter() [1/2]
luci::ProgressReporter::ProgressReporter (loco::Graph * graph, logo::PhaseStrategy strategy) inline
Definition at line 30 of file ProgressReporter.h.
    : _graph{graph}, _strategy{strategy}
  {
    // DO NOTHING
  }
ProgressReporter() [2/2]
luci::ProgressReporter::ProgressReporter (loco::Graph * graph, logo::PhaseStrategy strategy) inline
Definition at line 32 of file ProgressReporter.h.
    : _graph{graph}, _strategy{strategy}
  {
    // DO NOTHING
  }
Member Function Documentation
graph() [1/2]
loco::Graph * luci::ProgressReporter::graph (void) const inline
Definition at line 43 of file ProgressReporter.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), notify(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
graph() [2/2]
loco::Graph * luci::ProgressReporter::graph (void) const inline
Definition at line 45 of file ProgressReporter.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
notify() [1/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > * info) override
Definition at line 67 of file ProgressReporter.cpp.
{
  LOGGER(l);
  VERBOSE(l, 4) << "--------------------------------------------------------------";
  VERBOSE(l, 4) << "Before " << logo::pass_name(info->pass());
}
References info, LOGGER, logo::pass_name(), and VERBOSE.
notify() [2/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > *) override
notify() [3/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > * info) override
Definition at line 75 of file ProgressReporter.cpp.
{
  LOGGER(l);
  VERBOSE(l, 4) << "After " << logo::pass_name(info->pass())
                << " (changed: " << to_char(info->changed()) << ")";
  VERBOSE(l, 4) << fmt(graph());
}
References luci::fmt(), graph(), info, LOGGER, logo::pass_name(), and VERBOSE.
notify() [4/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > *) override
notify() [5/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
Definition at line 50 of file ProgressReporter.cpp.
{
  LOGGER(l);
  VERBOSE(l, 4) << "==============================================================";
  VERBOSE(l, 4) << "luci::PhaseRunner<" << to_str(strategy()) << ">";
  VERBOSE(l, 4) << "Initial graph";
  VERBOSE(l, 4) << fmt(graph());
}
References luci::fmt(), graph(), LOGGER, strategy(), and VERBOSE.
notify() [6/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
notify() [7/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
Definition at line 60 of file ProgressReporter.cpp.
{
  LOGGER(l);
  VERBOSE(l, 4) << "luci::PhaseRunner<" << to_str(strategy()) << "> - done";
}
References LOGGER, strategy(), and VERBOSE.
notify() [8/8]
void luci::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
strategy() [1/2]
logo::PhaseStrategy luci::ProgressReporter::strategy (void) const inline
Definition at line 44 of file ProgressReporter.h.
{ return _strategy; }
Referenced by notify().
strategy() [2/2]
logo::PhaseStrategy luci::ProgressReporter::strategy (void) const inline
Definition at line 46 of file ProgressReporter.h.
{ return _strategy; }
The documentation for this class was generated from the following files:
compiler/luci/export/src/ProgressReporter.h
compiler/luci/pass/src/ProgressReporter.h
compiler/luci/export/src/ProgressReporter.cpp
compiler/luci/pass/src/ProgressReporter.cpp