ONE - On-device Neural Engine: exo::TypeInferencePass Class Reference
exo::TypeInferencePass Class Reference
Pass to infer type of nodes.
#include <TypeInferencePass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to infer type of nodes.
Definition at line 31 of file TypeInferencePass.h.
Member Function Documentation
name()
virtual const char * exo::TypeInferencePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 34 of file TypeInferencePass.h.
{ return "exo::TypeInferencePass"; }
run()
bool exo::TypeInferencePass::run (loco::Graph * g) virtual
Note
Currently, TFL and Circle backend share this inference. However, TFL backend does not require rule for Circle dialect. TODO Make dedicated inference pass for Circle Dialect.
Implements logo::Pass.
Definition at line 40 of file TypeInferencePass.cpp.
{
  loco::CanonicalTypeInferenceRule canonical_rule;
  locoex::TFLTypeInferenceRule tfl_rule;
  locoex::CircleTypeInferenceRule circle_rule;
  locoex::COpTypeInferenceRule cop_rule;
  loco::MultiDialectTypeInferenceRule rules;
  rules.bind(loco::CanonicalDialect::get(), &canonical_rule)
    .bind(locoex::TFLDialect::get(), &tfl_rule)
    .bind(locoex::CircleDialect::get(), &circle_rule)
    .bind(locoex::COpDialect::get(), &cop_rule);
  return loco::apply(&rules).to(g);
}
References loco::apply(), loco::MultiDialectTypeInferenceRule::bind(), locoex::CircleDialect::get(), locoex::TFLDialect::get(), loco::CanonicalDialect::get(), locoex::COpDialect::get(), and loco::ShapeInferenceSession::to().
The documentation for this class was generated from the following files:
compiler/exo/src/Pass/TypeInferencePass.h
compiler/exo/src/Pass/TypeInferencePass.cpp