ONE - On-device Neural Engine: onert::exec::ProfileObserver Class Reference
onert::exec::ProfileObserver Class Reference
#include <ExecutionObservers.h>
Public Member Functions
ProfileObserver (std::shared_ptr< ExecTime > et, const ir::Graph &graph)
void handleJobBegin (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *) override
void handleJobEnd (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *) override
void handleSubgraphEnd (ir::SubgraphIndex) override
Invoked just after model (not individual operation) execution ends.
Public Member Functions inherited from onert::exec::IExecutionObserver
virtual void handleSubgraphBegin (ir::SubgraphIndex)
Invoked just before model (not individual operation) execution begins.
virtual void handleJobBegin (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *)=0
virtual void handleJobEnd (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *)=0
virtual void handleSubgraphEnd (ir::SubgraphIndex)
Invoked just after model (not individual operation) execution ends.
virtual ~IExecutionObserver ()=default
Detailed Description
Definition at line 52 of file ExecutionObservers.h.
Constructor & Destructor Documentation
ProfileObserver()
onert::exec::ProfileObserver::ProfileObserver (std::shared_ptr< ExecTime > et, const ir::Graph & graph) inline explicit
Definition at line 55 of file ExecutionObservers.h.
    : _et(std::move(et)), _graph(graph)
  {
  }
Member Function Documentation
handleJobBegin()
void onert::exec::ProfileObserver::handleJobBegin (IExecutor * , ir::SubgraphIndex , ir::OperationIndex , const backend::Backend * backend) override virtual
Implements onert::exec::IExecutionObserver.
Definition at line 76 of file ExecutionObservers.cc.
{
  _timer = backend->config()->timer();
  if (_timer == nullptr)
    throw std::runtime_error("To profile backend timer() method must be implemented");
  _timer->handleBegin();
}
References onert::backend::Backend::config().
handleJobEnd()
void onert::exec::ProfileObserver::handleJobEnd (IExecutor * exec, ir::SubgraphIndex , ir::OperationIndex op_ind, const backend::Backend * backend) override virtual
Implements onert::exec::IExecutionObserver.
Definition at line 85 of file ExecutionObservers.cc.
{
  _timer->handleEnd();
  const auto timer_res = _timer->getTime();
  // NOTE This assumes there is just one operation in a op
  const auto &node = _graph.operations().at(op_ind);
  auto node_name = node.name();
  VERBOSE(ProfileInfo) << "Time for " << node_name << " : " << timer_res << std::endl;
  // fill ExecTime:
  bool is_quantized = exec->graph().operands().at(node.getInputs().at(0)).typeInfo().type() ==
                      ir::DataType::QUANT_UINT8_ASYMM;
  uint32_t size = 0;
  for (const auto &ind : (node.getInputs() + node.getOutputs()) | ir::Remove::UNDEFINED)
  {
    size += exec->graph().operands().at(ind).info().total_size();
  }
  if (node_name == "Permute")
  {
    // TODO Change it to updateOperationExecTime()
    _et->updatePermuteTime(backend, backend, is_quantized, size, timer_res);
  }
  else
  {
    _et->updateOperationExecTime(backend, node_name, is_quantized, size, timer_res);
  }
};
References onert::util::ObjectManager< Index, Object >::at(), onert::exec::IExecutor::graph(), onert::ir::Graph::operands(), onert::ir::Graph::operations(), Operand::type, onert::ir::UNDEFINED, and VERBOSE.
handleSubgraphEnd()
void onert::exec::ProfileObserver::handleSubgraphEnd (ir::SubgraphIndex) inline override virtual
Invoked just after model (not individual operation) execution ends.
Reimplemented from onert::exec::IExecutionObserver.
Definition at line 64 of file ExecutionObservers.h.
{ _et->storeOperationsExecTime(); }
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/ExecutionObservers.h
runtime/onert/core/src/exec/ExecutionObservers.cc