ONE - On-device Neural Engine: circledump::CustomOpPrinter Class Reference
circledump::CustomOpPrinter Class Reference
Public Member Functions
void options (const circle::Operator *op, std::ostream &os) const override
Detailed Description
Definition at line 723 of file OpPrinter.cpp.
Member Function Documentation
options()
void circledump::CustomOpPrinter::options (const circle::Operator * op, std::ostream & os) const inline override virtual
Reimplemented from circledump::OpPrinter.
Definition at line 726 of file OpPrinter.cpp.
  {
    if (op->custom_options_format() != circle::CustomOptionsFormat::CustomOptionsFormat_FLEXBUFFERS)
    {
      os << "    ";
      os << "Unknown custom option format";
      return;
    }
    const flatbuffers::Vector<uint8_t> *option_buf = op->custom_options();
    if (option_buf == nullptr || option_buf->size() == 0)
    {
      os << "No attrs found." << std::endl;
      return;
    }
    // printing attrs
    // attrs of custom ops are encoded in flexbuffer format
    auto attr_map = flexbuffers::GetRoot(option_buf->data(), option_buf->size()).AsMap();
    os << "    ";
    auto keys = attr_map.Keys();
    for (int i = 0; i < keys.size(); i++)
    {
      auto key = keys[i].ToString();
      os << key << "(" << attr_map[key].ToString() << ") ";
    }
    // Note: attr in "Shape" type does not seem to be converted by circle_convert.
    // When the converted circle file (with custom op) is opened with hexa editory,
    // attrs names can be found but attr name in "Shape" type is not found.
    os << std::endl;
  }
References flexbuffers::Reference::AsMap(), flatbuffers::Vector< T >::data(), flexbuffers::GetRoot(), flexbuffers::Map::Keys(), and flatbuffers::Vector< T >::size().
The documentation for this class was generated from the following file:
compiler/circledump/src/OpPrinter.cpp