ONE - On-device Neural Engine: arm_compute::CLQuantizationSymmetricKernel Class Reference
arm_compute::CLQuantizationSymmetricKernel Class Reference
#include <CLQuantizationSymmetricKernel.h>
Public Member Functions
CLQuantizationSymmetricKernel ()
CLQuantizationSymmetricKernel (const CLQuantizationSymmetricKernel &)=delete
CLQuantizationSymmetricKernel & operator= (const CLQuantizationSymmetricKernel &)=delete
CLQuantizationSymmetricKernel (CLQuantizationSymmetricKernel &&)=default
CLQuantizationSymmetricKernel & operator= (CLQuantizationSymmetricKernel &&)=default
~CLQuantizationSymmetricKernel ()=default
void configure (const ICLTensor *input, const ICLTensor *scale_factor, ICLTensor *output)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *scale_factor, const ITensorInfo *output)
Detailed Description
Interface for the quantization layer kernel.
Note
The implementation supports only 2D input tensors.
Definition at line 54 of file CLQuantizationSymmetricKernel.h.
Constructor & Destructor Documentation
CLQuantizationSymmetricKernel() [1/3]
arm_compute::CLQuantizationSymmetricKernel::CLQuantizationSymmetricKernel ()
Default constructor
Definition at line 107 of file CLQuantizationSymmetricKernel.cpp.
  : _input(nullptr), _scale_factor(nullptr), _output(nullptr)
{
}
CLQuantizationSymmetricKernel() [2/3]
arm_compute::CLQuantizationSymmetricKernel::CLQuantizationSymmetricKernel (const CLQuantizationSymmetricKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLQuantizationSymmetricKernel() [3/3]
arm_compute::CLQuantizationSymmetricKernel::CLQuantizationSymmetricKernel (CLQuantizationSymmetricKernel &&) default
Default Move Constructor.
~CLQuantizationSymmetricKernel()
arm_compute::CLQuantizationSymmetricKernel::~CLQuantizationSymmetricKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void arm_compute::CLQuantizationSymmetricKernel::configure (const ICLTensor * input, const ICLTensor * scale_factor, ICLTensor * output)
Set the input, output.
Parameters
[in] input Source tensor. Data types supported: F32/F16.
[in] scale_factor Scale tensor of output. Data type supported: Same as input.
[out] output Destination tensor with the same dimensions of input. Data types supported: S8.
Note
Output auto initialization is not supported by this kernel
Definition at line 112 of file CLQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, scale_factor, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), scale_factor->info(), output->info()));
  _input = input;
  _scale_factor = scale_factor;
  _output = output;
  const int vec_size_x = 16 / input->info()->element_size();
  const int input_width_x = input->info()->tensor_shape().x();
  const bool multi_access_x = (input_width_x / vec_size_x > 0);
  // Configure kernel window
  auto win_config = validate_and_configure_window(input->info(), output->info());
  ARM_COMPUTE_ERROR_THROW_ON(win_config.first);
  ICLKernel::configure_internal(win_config.second);
  // Create kernel
  CLBuildOptions build_opts;
  build_opts.add_option("-DVEC_SIZE=" + support::cpp11::to_string(vec_size_x));
  build_opts.add_option("-DDATA_TYPE_IN=" + get_cl_type_from_data_type(input->info()->data_type()));
  build_opts.add_option("-DDATA_TYPE_OUT=" +
                        get_cl_type_from_data_type(output->info()->data_type()));
  build_opts.add_option_if(
    multi_access_x,
    "-DLAST_ACCESSED_X=" + support::cpp11::to_string(std::max<int>(input_width_x - vec_size_x, 0)));
  _kernel = static_cast<cl::Kernel>(
    CLKernelLibraryEx::get().create_kernel("quantization_symm8", build_opts.options()));
}
References arm_compute::CLKernelLibraryEx::create_kernel(), and arm_compute::CLKernelLibraryEx::get().
Referenced by arm_compute::CLFullyConnectedHybridLayer::configure().
operator=() [1/2]
CLQuantizationSymmetricKernel & arm_compute::CLQuantizationSymmetricKernel::operator= (CLQuantizationSymmetricKernel &&) default
Default move assignment operator
operator=() [2/2]
CLQuantizationSymmetricKernel & arm_compute::CLQuantizationSymmetricKernel::operator= (const CLQuantizationSymmetricKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLQuantizationSymmetricKernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 157 of file CLQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(ICLKernel::window(), window);
  // Support only 2D
  Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
  Window slice = window_collapsed.first_slice_window_2D();
  do
  {
    Window scale_slice = slice.shift_dimensions(1);
    unsigned int idx = 0;
    add_2D_tensor_argument(idx, _input, slice);
    add_1D_tensor_argument(idx, _scale_factor, scale_slice);
    add_2D_tensor_argument(idx, _output, slice);
    enqueue(queue, *this, slice, lws_hint());
  } while (window_collapsed.slide_window_slice_2D(slice));
}
validate()
Status arm_compute::CLQuantizationSymmetricKernel::validate (const ITensorInfo * input, const ITensorInfo * scale_factor, const ITensorInfo * output) static
Static function to check if given info will lead to a valid configuration of CLQuantizationSymmetricKernel
Parameters
[in] input Input tensor info. Data types supported: F32/F16.
[in] scale_factor Scale tensor of output. Data type supported: Same as input.
[in] output Destination tensor info with the same dimensions of input. Data types supported: S8.
Returns
a status
Definition at line 146 of file CLQuantizationSymmetricKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, scale_factor, output));
  ARM_COMPUTE_RETURN_ON_ERROR(
    validate_and_configure_window(input->clone().get(), output->clone().get()).first);
  return Status{};
}
Referenced by arm_compute::CLFullyConnectedHybridLayer::validate(), and ~CLQuantizationSymmetricKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLQuantizationSymmetricKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLQuantizationSymmetricKernel.cpp