ONE - On-device Neural Engine: nnfw::misc::tensor::IndexEnumerator Class Reference
nnfw::misc::tensor::IndexEnumerator Class Reference
Class to enumerate index of a tensor.
#include <IndexEnumerator.h>
Public Member Functions
IndexEnumerator (const Shape &shape)
Construct a new IndexEnumerator object.
IndexEnumerator (IndexEnumerator &&)=delete
Prevent constructing IndexEnumerator object by using R-value reference.
IndexEnumerator (const IndexEnumerator &)=delete
Prevent copy constructor.
bool valid (void) const
Check if more enumeration is available.
const Index & curr (void) const
Get the current index to enumerate.
void advance (void)
Advance index by +1.
Data Fields
const Shape _shape
Shape to enumerate.
Detailed Description
Class to enumerate index of a tensor.
Definition at line 39 of file IndexEnumerator.h.
Constructor & Destructor Documentation
IndexEnumerator() [1/3]
nnfw::misc::tensor::IndexEnumerator::IndexEnumerator (const Shape & shape) inline explicit
Construct a new IndexEnumerator object.
Parameters
[in] shape Shape of tensor of which index will be enumerate
Definition at line 46 of file IndexEnumerator.h.
                                               : _shape(shape), _cursor(0), _index(shape.rank())
  {
    const uint32_t rank = _shape.rank();
    for (uint32_t axis = 0; axis < rank; ++axis)
    {
      _index.at(axis) = 0;
    }
    for (_cursor = 0; _cursor < rank; ++_cursor)
    {
      if (_index.at(_cursor) < _shape.dim(_cursor))
      {
        break;
      }
    }
  }
References _shape, nnfw::misc::tensor::Index::at(), nnfw::misc::tensor::Shape::dim(), and nnfw::misc::tensor::Shape::rank().
IndexEnumerator() [2/3]
nnfw::misc::tensor::IndexEnumerator::IndexEnumerator (IndexEnumerator &&) delete
Prevent constructing IndexEnumerator object by using R-value reference.
IndexEnumerator() [3/3]
nnfw::misc::tensor::IndexEnumerator::IndexEnumerator (const IndexEnumerator &) delete
Prevent copy constructor.
Member Function Documentation
advance()
void nnfw::misc::tensor::IndexEnumerator::advance (void) inline
Advance index by +1.
Definition at line 92 of file IndexEnumerator.h.
  {
    const uint32_t rank = _shape.rank();
    // Find axis to be updated
    while ((_cursor < rank) && !(_index.at(_cursor) + 1 < _shape.dim(_cursor)))
    {
      ++_cursor;
    }
    if (_cursor == rank)
    {
      return;
    }
    // Update index
    _index.at(_cursor) += 1;
    for (uint32_t axis = 0; axis < _cursor; ++axis)
    {
      _index.at(axis) = 0;
    }
    // Update cursor
    _cursor = 0;
  }
References _shape, nnfw::misc::tensor::Index::at(), nnfw::misc::tensor::Shape::dim(), and nnfw::misc::tensor::Shape::rank().
curr()
const Index & nnfw::misc::tensor::IndexEnumerator::curr (void) const inline
Get the current index to enumerate.
Returns
Current index
Definition at line 86 of file IndexEnumerator.h.
{ return _index; }
valid()
bool nnfw::misc::tensor::IndexEnumerator::valid (void) const inline
Check if more enumeration is available.
Returns
true if more advance() is available, otherwise false
Definition at line 79 of file IndexEnumerator.h.
{ return _cursor < _shape.rank(); }
References _shape, and nnfw::misc::tensor::Shape::rank().
Field Documentation
_shape
const Shape nnfw::misc::tensor::IndexEnumerator::_shape
Shape to enumerate.
Definition at line 120 of file IndexEnumerator.h.
Referenced by advance(), IndexEnumerator(), and valid().
The documentation for this class was generated from the following file:
runtime/libs/misc/include/misc/tensor/IndexEnumerator.h