ONE - On-device Neural Engine: onert::exec::IExecutors Class Reference
onert::exec::IExecutors Class Reference abstract
Class to gather NN package's executor set.
#include <IExecutors.h>
Public Member Functions
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
Insert executor in executor set.
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
Return executor of index.
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
Return executor set's number of input.
virtual uint32_t outputSize () const =0
Return executor set's number of output.
virtual const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const =0
Return NN package input tensor info.
virtual const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const =0
Return NN package output tensor info.
virtual void execute (const IODescription &desc)=0
Execute NN package executor set.
Detailed Description
Class to gather NN package's executor set.
Definition at line 30 of file IExecutors.h.
Constructor & Destructor Documentation
~IExecutors()
virtual onert::exec::IExecutors::~IExecutors () virtual default
Virtual IExecutors destructor.
Note
Require derived class destructor
Member Function Documentation
at()
virtual IExecutor * onert::exec::IExecutors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const pure virtual
Return executor of index.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
Returns
Executor
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
Referenced by entryExecutor(), onert::backend::builtin::kernel::IfLayer::run(), and onert::backend::builtin::kernel::WhileLayer::run().
emplace()
virtual void onert::exec::IExecutors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) pure virtual
Insert executor in executor set.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
[in] exec Executor to insert
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
entryExecutor()
IExecutor * onert::exec::IExecutors::entryExecutor () const inline
Definition at line 60 of file IExecutors.h.
{ return at(ir::ModelIndex{0}, ir::SubgraphIndex{0}); }
References at().
Referenced by onert::exec::SingleModelExecutors::execute(), onert::exec::SingleModelExecutors::inputInfo(), onert::exec::SingleModelExecutors::inputSize(), onert::exec::SingleModelExecutors::outputInfo(), and onert::exec::SingleModelExecutors::outputSize().
execute()
virtual void onert::exec::IExecutors::execute (const IODescription & desc) pure virtual
Execute NN package executor set.
Parameters
[in] desc Input and output buffer description
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
inputInfo()
virtual const ir::OperandInfo & onert::exec::IExecutors::inputInfo (const ir::IOIndex & index) const pure virtual
Return NN package input tensor info.
Parameters
[in] index Input index
Returns
Tensor info
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
inputSize()
virtual uint32_t onert::exec::IExecutors::inputSize () const pure virtual
Return executor set's number of input.
Returns
Number of input
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
outputInfo()
virtual const ir::OperandInfo & onert::exec::IExecutors::outputInfo (const ir::IOIndex & index) const pure virtual
Return NN package output tensor info.
Parameters
[in] index Output index
Returns
Tensor info
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
outputSize()
virtual uint32_t onert::exec::IExecutors::outputSize () const pure virtual
Return executor set's number of output.
Returns
Number of output
Implemented in onert::exec::Executors, and onert::exec::SingleModelExecutors.
The documentation for this class was generated from the following file:
runtime/onert/core/include/exec/IExecutors.h