ONE - On-device Neural Engine: mir2loco::Transformer Class Reference
mir2loco::Transformer Class Reference final
#include <mir2loco.h>
Public Member Functions
Transformer ()=default
~Transformer ()=default
void visit (mir::ops::AddOp &op) override
void visit (mir::ops::AvgPool2DOp &op) override
void visit (mir::ops::ConcatOp &op) override
void visit (mir::ops::ConstantOp &op) override
void visit (mir::ops::Conv2DOp &op) override
void visit (mir::ops::DeConv2DOp &op) override
void visit (mir::ops::DepthwiseConv2DOp &op) override
void visit (mir::ops::DivOp &op) override
void visit (mir::ops::FullyConnectedOp &op) override
void visit (mir::ops::InputOp &op) override
void visit (mir::ops::MaxPool2DOp &op) override
void visit (mir::ops::MulOp &op) override
void visit (mir::ops::OutputOp &op) override
void visit (mir::ops::ReluOp &op) override
void visit (mir::ops::ReshapeOp &op) override
void visit (mir::ops::SoftmaxOp &op) override
void visit (mir::ops::SubOp &op) override
void visit (mir::ops::TransposeOp &op) override
void visit_fallback (mir::Operation &op) override
std::unique_ptr< loco::Graph > transform (mir::Graph *mir_graph)
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Additional Inherited Members
virtual void visit_fallback (Operation &)
Detailed Description
Definition at line 24 of file mir2loco.h.
Constructor & Destructor Documentation
Transformer()
mir2loco::Transformer::Transformer () default
~Transformer()
mir2loco::Transformer::~Transformer () default
Member Function Documentation
transform()
std::unique_ptr< loco::Graph > mir2loco::Transformer::transform (mir::Graph * mir_graph)
Definition at line 710 of file mir2loco.cpp.
{
  _mir2loco_map.clear();
  _loco_graph.reset();
  _loco_graph = loco::make_graph();
  // Transform Nodes
  mir_graph->accept(this);
  // validate graph
  assert(loco::valid(_loco_graph.get()));
  return std::move(_loco_graph);
}
References mir::Graph::accept(), loco::make_graph(), and loco::valid().
Referenced by main().
visit() [1/18]
void mir2loco::Transformer::visit (mir::ops::AddOp & op) override
Definition at line 266 of file mir2loco.cpp.
{
  // Get Input
  auto lhs = _mir2loco_map.at(op.getInput(0));
  auto rhs = _mir2loco_map.at(op.getInput(1));
  auto result = createEltwiseBinary<loco::EltwiseAdd>(op, lhs, rhs);
  // Not set Shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), result);
}
References mir::Operation::getInput(), and mir::Operation::getOutput().
visit() [2/18]
void mir2loco::Transformer::visit (mir::ops::AvgPool2DOp & op) override
Definition at line 277 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
  encoded_input->input(input);
  encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
  auto *avg_pool_node = _loco_graph->nodes()->create<loco::AvgPool2D>();
  avg_pool_node->ifm(encoded_input);
  avg_pool_node->convention(op.getIncludePad() ? loco::AvgPool2D::Convention::Full
                                               : loco::AvgPool2D::Convention::Valid);
  setupWindow(op.getWindowSize(), avg_pool_node->window());
  setupStride(op.getStrides(), avg_pool_node->stride());
  setupPad(op.getPaddingBefore(), op.getPaddingAfter(), avg_pool_node->pad());
  auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
  output->input(avg_pool_node);
  output->decoder(createFeatureDecoder(op.getDataFormat()));
  _mir2loco_map.emplace(op.getOutput(0), output);
}
References loco::AvgPool2D::Full, mir::ops::AvgPool2DOp::getDataFormat(), mir::ops::AvgPool2DOp::getIncludePad(), mir::Operation::getInput(), mir::Operation::getOutput(), mir::ops::AvgPool2DOp::getPaddingAfter(), mir::ops::AvgPool2DOp::getPaddingBefore(), mir::ops::AvgPool2DOp::getStrides(), mir::ops::AvgPool2DOp::getWindowSize(), loco::AvgPool2D::ifm(), loco::FeatureEncode::input(), and loco::AvgPool2D::Valid.
visit() [3/18]
void mir2loco::Transformer::visit (mir::ops::ConcatOp & op) override
Definition at line 300 of file mir2loco.cpp.
{
  if (op.getNumInputs() < 2)
    throw std::runtime_error("Not enough tensors for concatenation!");
  loco::Node *last_concat = nullptr;
  for (std::size_t i = 1; i < op.getNumInputs(); i++)
  {
    loco::Node *lhs = last_concat;
    if (lhs == nullptr)
    {
      mir::Operation::Output *mir_lhs = op.getInput(i - 1);
      lhs = _mir2loco_map.at(mir_lhs);
    }
    mir::Operation::Output *mir_rhs = op.getInput(i);
    loco::Node *rhs = _mir2loco_map.at(mir_rhs);
    // Create TensorConcat
    auto concat_node = _loco_graph->nodes()->create<loco::TensorConcat>();
    // Set inputs
    concat_node->lhs(lhs);
    concat_node->rhs(rhs);
    // Set axis
    concat_node->axis(op.getAxis());
    // Set last concat
    last_concat = concat_node;
  }
  // Not set Shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), last_concat);
}
References mir::ops::ConcatOp::getAxis(), mir::Operation::getInput(), mir::Operation::getNumInputs(), mir::Operation::getOutput(), and loco::TensorConcat::lhs().
visit() [4/18]
void mir2loco::Transformer::visit (mir::ops::ConstantOp & op) override
Definition at line 332 of file mir2loco.cpp.
{
  auto const_node = _loco_graph->nodes()->create<loco::ConstGen>();
  // Not set Input
  // Set Shape
  const auto &out_shape = op.getOutputShape(0);
  setupShape(out_shape, const_node);
  // Copy value
  const auto &value = op.getValue();
  const_node->dtype(convertDataType(value.getElementType()));
  // TODO Support other data types
  switch (const_node->dtype())
  {
    case loco::DataType::FLOAT32:
    {
      const_node->size<loco::DataType::FLOAT32>(out_shape.numElements());
      float &const_float = const_node->at<loco::DataType::FLOAT32>(0);
      char *loco_ptr = reinterpret_cast<char *>(&const_float);
      char *mir_ptr = value.at(mir::Index(out_shape.rank()));
      std::memcpy(loco_ptr, mir_ptr, out_shape.numElements() * sizeof(float));
      break;
    }
    case loco::DataType::FLOAT64:
    {
      // TODO Change that when loco support other DataTypeImpl
      const_node->dtype(loco::DataType::FLOAT32);
      const_node->size<loco::DataType::FLOAT32>(out_shape.numElements());
      float &const_float = const_node->at<loco::DataType::FLOAT32>(0);
      char *mir_ptr = value.at(mir::Index(out_shape.rank()));
      double *mir_double = reinterpret_cast<double *>(mir_ptr);
      float *loco_float = &const_float;
      for (const mir::Index &idx : mir::ShapeRange(out_shape))
      {
        *loco_float = static_cast<float>(*mir_double);
        loco_float++;
        mir_double++;
      }
      break;
    }
    case loco::DataType::S32:
    {
      const_node->size<loco::DataType::S32>(out_shape.numElements());
      int32_t &const_int32 = const_node->at<loco::DataType::S32>(0);
      char *loco_ptr = reinterpret_cast<char *>(&const_int32);
      char *mir_ptr = value.at(mir::Index(out_shape.rank()));
      std::memcpy(loco_ptr, mir_ptr, out_shape.numElements() * sizeof(int32_t));
      break;
    }
    case loco::DataType::S64:
    {
      // TODO Change that when loco support other DataTypeImpl
      const_node->dtype(loco::DataType::S32);
      const_node->size<loco::DataType::S32>(out_shape.numElements());
      int32_t &const_int32 = const_node->at<loco::DataType::S32>(0);
      char *mir_ptr = value.at(mir::Index(out_shape.rank()));
      int64_t *mir_int64 = reinterpret_cast<int64_t *>(mir_ptr);
      int32_t *loco_int32 = &const_int32;
      for (const mir::Index &idx : mir::ShapeRange(out_shape))
      {
        *loco_int32 = static_cast<float>(*mir_int64);
        loco_int32++;
        mir_int64++;
      }
      break;
    }
    default:
      std::runtime_error("Unsupported data type");
  }
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), const_node);
}
References mir::TensorVariant::at(), mir::Operation::getOutput(), mir::Operation::getOutputShape(), and mir::ops::ConstantOp::getValue().
visit() [5/18]
void mir2loco::Transformer::visit (mir::ops::Conv2DOp & op) override
Definition at line 404 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_input = op.getInput(0);
  mir::Operation::Output *mir_filter = op.getInput(1);
  loco::Node *input = _mir2loco_map.at(mir_input);
  loco::Node *filter = _mir2loco_map.at(mir_filter);
  // loco does not have grouped Conv2D operation. Try to translate into something else.
  if (op.getNumGroups() != 1)
  {
    const std::int32_t group_size = mir_filter->getShape().dim(3);
    const std::int32_t num_in_channels = group_size * op.getNumGroups();
    const std::int32_t num_out_channels = mir_filter->getShape().dim(0);
    // If the size of the group is 1, translate the operation into DepthwiseConv2D. Limit ourselves
    // with the case of 'multiplier' == 1 for now.
    if (group_size == 1 && (num_out_channels == num_in_channels))
    {
      // [O, H, W, I / group] == [I, H, W, M].
      auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
      encoded_input->input(input);
      encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
      auto *encoded_filter = _loco_graph->nodes()->create<loco::DepthwiseFilterEncode>();
      encoded_filter->input(filter);
      encoded_filter->encoder(createIHWMDepthwiseFilterEncoder());
      auto *dw_conv2d_node = _loco_graph->nodes()->create<loco::DepthwiseConv2D>();
      dw_conv2d_node->ifm(encoded_input);
      dw_conv2d_node->ker(encoded_filter);
      setupStride(op.getStrides(), dw_conv2d_node->stride());
      setupPad(op.getPaddingBefore(), op.getPaddingAfter(), dw_conv2d_node->pad());
      auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
      output->input(dw_conv2d_node);
      output->decoder(createFeatureDecoder(op.getDataFormat()));
      _mir2loco_map.emplace(op.getOutput(0), output);
    }
    else
    {
      // There are few things we can do here:
      // 1) If group_size == 1, reshape the kernel [O, H, W, I / group] == [I * M, H, W, 1] ->
      //    [I, M, H, W] and use DepthwiseConv2D.
      // 2) Split the operation into smaller Conv2Ds.
      // 3) Replicate the filter along 'O' axis 'num_groups' times, zero out some elements, and use
      //    ordinary Conv2D.
      throw std::runtime_error("Grouped Conv2D operation is not fully supported.");
    }
  }
  else
  {
    auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
    encoded_input->input(input);
    encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
    auto *encoded_filter = _loco_graph->nodes()->create<loco::FilterEncode>();
    encoded_filter->input(filter);
    encoded_filter->encoder(createOHWIFilterEncoder());
    auto *conv2d_node = _loco_graph->nodes()->create<loco::Conv2D>();
    conv2d_node->ifm(encoded_input);
    conv2d_node->ker(encoded_filter);
    setupStride(op.getStrides(), conv2d_node->stride());
    setupPad(op.getPaddingBefore(), op.getPaddingAfter(), conv2d_node->pad());
    auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
    output->input(conv2d_node);
    output->decoder(createFeatureDecoder(op.getDataFormat()));
    _mir2loco_map.emplace(op.getOutput(0), output);
  }
}
References mir::Shape::dim(), mir::ops::Conv2DOp::getDataFormat(), mir::Operation::getInput(), mir::ops::Conv2DOp::getNumGroups(), mir::Operation::getOutput(), mir::ops::Conv2DOp::getPaddingAfter(), mir::ops::Conv2DOp::getPaddingBefore(), mir::Operation::Output::getShape(), mir::ops::Conv2DOp::getStrides(), loco::Conv2D::ifm(), loco::DepthwiseConv2D::ifm(), loco::FeatureEncode::input(), loco::FilterEncode::input(), and loco::DepthwiseFilterEncode::input().
visit() [6/18]
void mir2loco::Transformer::visit (mir::ops::DeConv2DOp & op) override
Definition at line 479 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_input = op.getInput(0);
  mir::Operation::Output *mir_filter = op.getInput(1);
  loco::Node *input = _mir2loco_map.at(mir_input);
  loco::Node *filter = _mir2loco_map.at(mir_filter);
  auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
  encoded_input->input(input);
  encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
  auto *encoded_filter = _loco_graph->nodes()->create<loco::FilterEncode>();
  encoded_filter->input(filter);
  encoded_filter->encoder(createHWOIFilterEncoder());
  auto *tr_conv2d_node = _loco_graph->nodes()->create<loco::TransposedConv2D>();
  tr_conv2d_node->ifm(encoded_input);
  tr_conv2d_node->ker(encoded_filter);
  setupStride(op.getStrides(), tr_conv2d_node->stride());
  if (op.getPaddingType() == mir::ops::PaddingType::Explicit)
    setupPad(op.getPaddingBefore(), op.getPaddingAfter(), tr_conv2d_node->pad());
  else
    throw std::runtime_error("Not supported non explicit paddings on loco!");
  auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
  output->input(tr_conv2d_node);
  output->decoder(createFeatureDecoder(op.getDataFormat()));
  _mir2loco_map.emplace(op.getOutput(0), output);
}
References mir::ops::Explicit, mir::ops::DeConv2DOp::getDataFormat(), mir::Operation::getInput(), mir::Operation::getOutput(), mir::ops::DeConv2DOp::getPaddingAfter(), mir::ops::DeConv2DOp::getPaddingBefore(), mir::ops::DeConv2DOp::getPaddingType(), mir::ops::DeConv2DOp::getStrides(), loco::TransposedConv2D::ifm(), loco::FeatureEncode::input(), and loco::FilterEncode::input().
visit() [7/18]
void mir2loco::Transformer::visit (mir::ops::DepthwiseConv2DOp & op) override
Definition at line 511 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_input = op.getInput(0);
  mir::Operation::Output *mir_filter = op.getInput(1);
  loco::Node *input = _mir2loco_map.at(mir_input);
  loco::Node *filter = _mir2loco_map.at(mir_filter);
  auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
  encoded_input->input(input);
  encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
  auto *encoded_filter = _loco_graph->nodes()->create<loco::DepthwiseFilterEncode>();
  encoded_filter->input(filter);
  encoded_filter->encoder(createHWIMDepthwiseFilterEncoder());
  auto *dw_conv2d_node = _loco_graph->nodes()->create<loco::DepthwiseConv2D>();
  dw_conv2d_node->ifm(encoded_input);
  dw_conv2d_node->ker(encoded_filter);
  setupStride(op.getStrides(), dw_conv2d_node->stride());
  setupPad(op.getPaddingBefore(), op.getPaddingAfter(), dw_conv2d_node->pad());
  auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
  output->input(dw_conv2d_node);
  output->decoder(createFeatureDecoder(op.getDataFormat()));
  _mir2loco_map.emplace(op.getOutput(0), output);
}
References mir::ops::DepthwiseConv2DOp::getDataFormat(), mir::Operation::getInput(), mir::Operation::getOutput(), mir::ops::DepthwiseConv2DOp::getPaddingAfter(), mir::ops::DepthwiseConv2DOp::getPaddingBefore(), mir::ops::DepthwiseConv2DOp::getStrides(), loco::DepthwiseConv2D::ifm(), loco::FeatureEncode::input(), and loco::DepthwiseFilterEncode::input().
visit() [8/18]
void mir2loco::Transformer::visit (mir::ops::DivOp & op) override
Definition at line 540 of file mir2loco.cpp.
{
  // Get Input
  loco::Node *lhs = _mir2loco_map.at(op.getInput(0));
  loco::Node *rhs = _mir2loco_map.at(op.getInput(1));
  auto result = createEltwiseBinary<loco::EltwiseDiv>(op, lhs, rhs);
  // Not set Shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), result);
}
References mir::Operation::getInput(), and mir::Operation::getOutput().
visit() [9/18]
void mir2loco::Transformer::visit (mir::ops::FullyConnectedOp & op) override
Definition at line 551 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_lhs = op.getInput(0);
  mir::Operation::Output *mir_rhs = op.getInput(1);
  // Check 2D shape
  assert(op.getInput(0)->getShape().rank() == 2);
  assert(op.getInput(1)->getShape().rank() == 2);
  loco::Node *lhs = _mir2loco_map.at(mir_lhs);
  loco::Node *rhs = _mir2loco_map.at(mir_rhs);
  auto *encoded_lhs = _loco_graph->nodes()->create<loco::MatrixEncode>();
  encoded_lhs->input(lhs);
  encoded_lhs->encoder(createHWMatrixEncoder());
  auto *encoded_rhs = _loco_graph->nodes()->create<loco::MatrixEncode>();
  encoded_rhs->input(rhs);
  encoded_rhs->encoder(createHWMatrixEncoder());
  auto *mat_mul = _loco_graph->nodes()->create<loco::MatMul>();
  mat_mul->lhs(encoded_lhs);
  mat_mul->rhs(encoded_rhs);
  auto *output = _loco_graph->nodes()->create<loco::MatrixDecode>();
  output->input(mat_mul);
  output->decoder(createHWMatrixDecoder());
  _mir2loco_map.emplace(op.getOutput(0), output);
}
References mir::Operation::getInput(), mir::Operation::getOutput(), mir::Operation::Output::getShape(), loco::MatrixEncode::input(), loco::MatMul::lhs(), and mir::Shape::rank().
visit() [10/18]
void mir2loco::Transformer::visit (mir::ops::InputOp & op) override
Definition at line 581 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_output = op.getOutput(0);
  loco::GraphInput *graph_input = _loco_graph->inputs()->create();
  graph_input->name(mir_output->getName());
  graph_input->dtype(convertDataType(mir_output->getElementType()));
  auto *pull_node = _loco_graph->nodes()->create<loco::Pull>();
  setupShape(mir_output->getShape(), pull_node);
  loco::link(graph_input, pull_node);
  _mir2loco_map.emplace(mir_output, pull_node);
}
References loco::Mixin< Trait::DataTyped >::dtype(), mir::Operation::Output::getElementType(), mir::Operation::Output::getName(), mir::Operation::getOutput(), mir::Operation::Output::getShape(), and loco::link().
visit() [11/18]
void mir2loco::Transformer::visit (mir::ops::MaxPool2DOp & op) override
Definition at line 597 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  auto *encoded_input = _loco_graph->nodes()->create<loco::FeatureEncode>();
  encoded_input->input(input);
  encoded_input->encoder(createFeatureEncoder(op.getDataFormat()));
  auto max_pool_node = _loco_graph->nodes()->create<loco::MaxPool2D>();
  max_pool_node->ifm(encoded_input);
  setupWindow(op.getWindowSize(), max_pool_node->window());
  setupStride(op.getStrides(), max_pool_node->stride());
  setupPad(op.getPaddingBefore(), op.getPaddingAfter(), max_pool_node->pad());
  auto *output = _loco_graph->nodes()->create<loco::FeatureDecode>();
  output->input(max_pool_node);
  output->decoder(createFeatureDecoder(op.getDataFormat()));
  _mir2loco_map.emplace(op.getOutput(0), output);
}
References mir::ops::MaxPool2DOp::getDataFormat(), mir::Operation::getInput(), mir::Operation::getOutput(), mir::ops::MaxPool2DOp::getPaddingAfter(), mir::ops::MaxPool2DOp::getPaddingBefore(), mir::ops::MaxPool2DOp::getStrides(), mir::ops::MaxPool2DOp::getWindowSize(), loco::MaxPool2D::ifm(), and loco::FeatureEncode::input().
visit() [12/18]
void mir2loco::Transformer::visit (mir::ops::MulOp & op) override
Definition at line 618 of file mir2loco.cpp.
{
  // Get Input
  loco::Node *lhs = _mir2loco_map.at(op.getInput(0));
  loco::Node *rhs = _mir2loco_map.at(op.getInput(1));
  auto result = createEltwiseBinary<loco::EltwiseMul>(op, lhs, rhs);
  // Not set Shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), result);
}
References mir::Operation::getInput(), and mir::Operation::getOutput().
visit() [13/18]
void mir2loco::Transformer::visit (mir::ops::OutputOp & op) override
Definition at line 629 of file mir2loco.cpp.
{
  mir::Operation::Output *mir_input = op.getInput(0);
  loco::Node *input = _mir2loco_map.at(mir_input);
  loco::GraphOutput *graph_output = _loco_graph->outputs()->create();
  graph_output->name(mir_input->getName());
  graph_output->dtype(convertDataType(mir_input->getElementType()));
  graph_output->shape(make_tensor_shape(mir_input->getShape()));
  auto *push_node = _loco_graph->nodes()->create<loco::Push>();
  push_node->from(input);
  loco::link(graph_output, push_node);
}
References loco::Mixin< Trait::DataTyped >::dtype(), loco::Push::from(), mir::Operation::Output::getElementType(), mir::Operation::getInput(), mir::Operation::Output::getName(), mir::Operation::Output::getShape(), loco::link(), and loco::Mixin< Trait::TensorShaped >::shape().
visit() [14/18]
void mir2loco::Transformer::visit (mir::ops::ReluOp & op) override
Definition at line 645 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  auto relu_node = _loco_graph->nodes()->create<loco::ReLU>();
  relu_node->input(input);
  // Not set shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), relu_node);
}
References mir::Operation::getInput(), mir::Operation::getOutput(), and loco::ReLU::input().
visit() [15/18]
void mir2loco::Transformer::visit (mir::ops::ReshapeOp & op) override
Definition at line 656 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  auto reshape_node = _loco_graph->nodes()->create<loco::Reshape<loco::ReshapeType::Fixed>>();
  reshape_node->input(input);
  // Set Shape
  auto &out_shape = op.getOutputShape(0);
  setupShape(out_shape, reshape_node);
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), reshape_node);
}
References mir::Operation::getInput(), mir::Operation::getOutput(), and mir::Operation::getOutputShape().
visit() [16/18]
void mir2loco::Transformer::visit (mir::ops::SoftmaxOp & op) override
Definition at line 669 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  auto softmax_node = _loco_graph->nodes()->create<loco::TensorSoftmax>();
  softmax_node->input(input);
  // Set Axis
  softmax_node->axis(op.getAxis());
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), softmax_node);
}
References mir::ops::SoftmaxOp::getAxis(), mir::Operation::getInput(), mir::Operation::getOutput(), and loco::Softmax< Domain::Tensor >::input().
visit() [17/18]
void mir2loco::Transformer::visit (mir::ops::SubOp & op) override
Definition at line 681 of file mir2loco.cpp.
{
  // Get Input
  loco::Node *lhs = _mir2loco_map.at(op.getInput(0));
  loco::Node *rhs = _mir2loco_map.at(op.getInput(1));
  auto result = createEltwiseBinary<loco::EltwiseSub>(op, lhs, rhs);
  // Not set Shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), result);
}
References mir::Operation::getInput(), and mir::Operation::getOutput().
visit() [18/18]
void mir2loco::Transformer::visit (mir::ops::TransposeOp & op) override
Definition at line 692 of file mir2loco.cpp.
{
  loco::Node *input = _mir2loco_map.at(op.getInput(0));
  const auto &axis_order = op.getAxisOrder();
  auto transpose_node = _loco_graph->nodes()->create<loco::TensorTranspose>();
  transpose_node->input(input);
  // Set axis order
  transpose_node->perm()->size(axis_order.size());
  for (size_t i = 0; i < axis_order.size(); i++)
    transpose_node->perm()->axis(i) = axis_order[i];
  // Not set shape
  // Add to map
  _mir2loco_map.emplace(op.getOutput(0), transpose_node);
}
References mir::ops::TransposeOp::getAxisOrder(), mir::Operation::getInput(), mir::Operation::getOutput(), and loco::TensorTranspose::input().
visit_fallback()
void mir2loco::Transformer::visit_fallback (mir::Operation & op) override virtual
Reimplemented from mir::Visitor.
Definition at line 708 of file mir2loco.cpp.
{ throw std::runtime_error("NYI operation"); }
The documentation for this class was generated from the following files:
compiler/mir2loco/include/mir2loco.h
compiler/mir2loco/src/mir2loco.cpp