ONE - On-device Neural Engine: coco::Arg Class Reference
coco::Arg Class Reference
Base class for NN model arguments (Input/Output)
#include <Arg.h>
Public Member Functions
Arg (const nncc::core::ADT::tensor::Shape &shape)
virtual ~Arg ()=default
const nncc::core::ADT::tensor::Shape & shape (void) const
const std::string & name (void) const
void name (const std::string &s)
Bag * bag (void) const
void bag (Bag *)
ElemID & at (const nncc::core::ADT::tensor::Index &)
const ElemID & at (const nncc::core::ADT::tensor::Index &) const
void reorder (const nncc::core::ADT::tensor::Layout &l)
template<typename LayoutImpl >
void reorder (void)
Protected Member Functions
virtual void onTake (Bag *)
virtual void onRelease (Bag *)
Detailed Description
Base class for NN model arguments (Input/Output)
Definition at line 36 of file Arg.h.
Constructor & Destructor Documentation
Arg()
coco::Arg::Arg (const nncc::core::ADT::tensor::Shape & shape) explicit
Definition at line 34 of file Arg.cpp.
                                            : _shape{shape}, _bag{nullptr}
{
  _map.resize(nncc::core::ADT::tensor::num_elements(shape));
}
References nncc::core::ADT::tensor::num_elements(), and shape().
~Arg()
virtual coco::Arg::~Arg () virtual default
Member Function Documentation
at() [1/2]
ElemID & coco::Arg::at (const nncc::core::ADT::tensor::Index & index)
Definition at line 56 of file Arg.cpp.
{
  return _map.at(l.offset(_shape, index));
}
Referenced by reorder().
at() [2/2]
const ElemID & coco::Arg::at (const nncc::core::ADT::tensor::Index & index) const
Definition at line 61 of file Arg.cpp.
{
  return _map.at(l.offset(_shape, index));
}
bag() [1/2]
void coco::Arg::bag (Bag * bag)
Definition at line 39 of file Arg.cpp.
{
  if (_bag != nullptr)
  {
    onRelease(_bag);
    _bag = nullptr;
  }
  assert(_bag == nullptr);
  if (bag != nullptr)
  {
    _bag = bag;
    onTake(_bag);
  }
}
References bag(), onRelease(), and onTake().
bag() [2/2]
Bag * coco::Arg::bag (void) const inline
Definition at line 56 of file Arg.h.
{ return _bag; }
Referenced by bag().
name() [1/2]
void coco::Arg::name (const std::string & s) inline
Definition at line 49 of file Arg.h.
{ _name = s; }
name() [2/2]
const std::string & coco::Arg::name (void) const inline
Definition at line 48 of file Arg.h.
{ return _name; }
onRelease()
virtual void coco::Arg::onRelease (Bag *) inline protected virtual
Definition at line 53 of file Arg.h.
{ return; }
Referenced by bag().
onTake()
virtual void coco::Arg::onTake (Bag *) inline protected virtual
Definition at line 52 of file Arg.h.
{ return; }
Referenced by bag().
reorder() [1/2]
void coco::Arg::reorder (const nncc::core::ADT::tensor::Layout & l)
Definition at line 66 of file Arg.cpp.
{
  using nncc::core::ADT::tensor::IndexEnumerator;
  for (IndexEnumerator e{shape()}; e.valid(); e.advance())
  {
    const auto offset = static_cast<uint32_t>(l.offset(shape(), e.current()));
    at(e.current()) = coco::ElemID{offset};
  }
}
References at(), offset(), and shape().
reorder() [2/2]
template<typename LayoutImpl > void coco::Arg::reorder (void) inline
Definition at line 65 of file Arg.h.
{ reorder(LayoutImpl{}); }
References reorder().
Referenced by reorder().
shape()
const nncc::core::ADT::tensor::Shape & coco::Arg::shape (void) const inline
Definition at line 45 of file Arg.h.
{ return _shape; }
Referenced by Arg(), and reorder().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Arg.h
compiler/coco/core/src/IR/Arg.cpp