ONE - On-device Neural Engine: onert::exec::MultiModelExecutors Class Reference
onert::exec::MultiModelExecutors Class Reference
Class to gather executors.
#include <MultiModelExecutors.h>
Data Structures
class EdgeTensor
Public Member Functions
MultiModelExecutors (void)=delete
MultiModelExecutors (std::unique_ptr< ir::ModelEdges > model_edges)
MultiModelExecutors (const MultiModelExecutors &)=delete
MultiModelExecutors (MultiModelExecutors &&)=default
~MultiModelExecutors ()=default
void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec) override
Insert executor in executor set.
IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const override
Return executor of index.
uint32_t inputSize () const override
Return executor set's number of input.
uint32_t outputSize () const override
Return executor set's number of output.
const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const override
Return NN package input tensor info.
const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const override
Return NN package output tensor info.
void execute (const IODescription &desc) override
Execute NN package executor set.
Public Member Functions inherited from onert::exec::IExecutors
virtual ~IExecutors ()=default
Virtual IExecutors destructor.
virtual void emplace (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index, std::unique_ptr< IExecutor > exec)=0
Insert executor in executor set.
virtual IExecutor * at (const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index) const =0
Return executor of index.
IExecutor * entryExecutor () const
virtual uint32_t inputSize () const =0
Return executor set's number of input.
virtual uint32_t outputSize () const =0
Return executor set's number of output.
virtual const ir::OperandInfo & inputInfo (const ir::IOIndex &index) const =0
Return NN package input tensor info.
virtual const ir::OperandInfo & outputInfo (const ir::IOIndex &index) const =0
Return NN package output tensor info.
virtual void execute (const IODescription &desc)=0
Execute NN package executor set.
Detailed Description
Class to gather executors.
Definition at line 46 of file MultiModelExecutors.h.
Constructor & Destructor Documentation
MultiModelExecutors() [1/4]
onert::exec::MultiModelExecutors::MultiModelExecutors (void) delete
MultiModelExecutors() [2/4]
onert::exec::MultiModelExecutors::MultiModelExecutors (std::unique_ptr< ir::ModelEdges > model_edges) inline
Definition at line 50 of file MultiModelExecutors.h.
    : _executors{}, _model_edges{std::move(model_edges)}, _edge_quant_layers{},
      _edge_quant_tensors{}, _edge_tensors{}, _is_created_edge_quant_layers{false},
      _pkg_input_quant_layers{}, _pkg_output_quant_layers{}, _pkg_input_quant_tensors{},
      _pkg_output_quant_tensors{}, _pkg_input_tensors{}, _pkg_output_tensors{}
  {
    for (const auto &edge : _model_edges->edges)
    {
      _edge_map[edge.from].emplace_back(edge.to);
    }
  }
MultiModelExecutors() [3/4]
onert::exec::MultiModelExecutors::MultiModelExecutors (const MultiModelExecutors &) delete
MultiModelExecutors() [4/4]
onert::exec::MultiModelExecutors::MultiModelExecutors (MultiModelExecutors &&) default
~MultiModelExecutors()
onert::exec::MultiModelExecutors::~MultiModelExecutors () default
Member Function Documentation
at()
IExecutor * onert::exec::MultiModelExecutors::at (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index) const override virtual
Return executor of index.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
Returns
Executor
Implements onert::exec::IExecutors.
Definition at line 110 of file MultiModelExecutors.cc.
{
  return _executors.at(std::make_pair(model_index, subg_index)).get();
}
Referenced by execute(), inputInfo(), and outputInfo().
emplace()
void onert::exec::MultiModelExecutors::emplace (const ir::ModelIndex & model_index, const ir::SubgraphIndex & subg_index, std::unique_ptr< IExecutor > exec) override virtual
Insert executor in executor set.
Parameters
[in] model_index Model index
[in] subg_index Subgraph index
[in] exec Executor to insert
Implements onert::exec::IExecutors.
Definition at line 103 of file MultiModelExecutors.cc.
{
  _executors.emplace(std::make_pair(model_index, subg_index), std::move(exec));
}
execute()
void onert::exec::MultiModelExecutors::execute (const IODescription & desc) override virtual
Execute NN package executor set.
Parameters
[in] desc Input and output buffer description
Implements onert::exec::IExecutors.
Definition at line 409 of file MultiModelExecutors.cc.
{
  // Check supported multi model package
  checkSupportedMultimodel();
  // TODO Move creating type-aware quantization layers for edges in compilation stage
  createEdgeQuantLayers();
  // TODO Create IOTensors only once and recreate them only if nnpkg info changes
  CreatePkgIOTensors(desc);
  // TODO Create type-aware quantization layers only once and recreate them only if type changes
  createPkgIOQuantLayers(desc);
  // TODO Find better way to schedule order of executors
  auto const model_count = modelCount();
  auto find_from = [&](const ir::ModelIndex &model_index, const ir::SubgraphIndex &subg_index,
                       const ir::IOIndex &io_index) {
    for (const auto &edge : _model_edges->edges)
    {
      if ((std::get<ir::ModelIndex>(edge.to) == model_index) &&
          (std::get<ir::SubgraphIndex>(edge.to) == subg_index) &&
          (std::get<ir::IOIndex>(edge.to) == io_index))
        return edge.from;
    }
    throw std::runtime_error{"Cannot find edge for model input"};
  };
  // Execute each model
  // NOTE May be better to use vector instead of unordered_map for _executors
  for (auto model_index = ir::ModelIndex{0}; model_index.value() < model_count; model_index++)
  {
    // Find executor
    auto executor = at(model_index, ir::SubgraphIndex{0});
    // Set IOTensors
    // TODO Set internal IOTensors only once
    std::vector<backend::IPortableTensor *> inputs_inter;
    std::vector<backend::IPortableTensor *> outputs_inter;
    const auto &input_tensors = executor->getInputTensors();
    const auto &output_tensors = executor->getOutputTensors();
    auto const input_size = input_tensors.size();
    auto const output_size = output_tensors.size();
    inputs_inter.resize(input_size);
    outputs_inter.resize(output_size);
    // Set inputs of executor
    // TODO Create layer to allocate/deallocate buffers of EdgeTensor for each executor
    for (uint32_t i = 0; i < input_size; i++)
    {
      const auto input_pkg_index = find_input_index(_model_edges->pkg_inputs, model_index,
                                                    ir::SubgraphIndex{0}, ir::IOIndex{i});
      const auto input_io_desc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      if (input_pkg_index != -1)
      {
        // Allocate type-aware quantization tensors for nnpkg inputs and set internal tensors
        if (_pkg_input_quant_tensors.find(input_io_desc) != _pkg_input_quant_tensors.end())
        {
          _pkg_input_quant_tensors[input_io_desc]->allocate_buffer();
          inputs_inter[i] = _pkg_input_quant_tensors[input_io_desc].get();
        }
        else
        {
          inputs_inter[i] = _pkg_input_tensors[input_io_desc].get();
        }
        // Set buffer of IOTensor
        auto input_desc = desc.inputs[input_pkg_index].get();
        // TODO Remove const_cast (we need const_cast as ITensor is writable)
        _pkg_input_tensors[input_io_desc]->setUserTensor(
          reinterpret_cast<uint8_t *>(const_cast<void *>(input_desc->buffer)), input_desc->size);
      }
      else
      {
        auto from_iodesc = find_from(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
        const auto &from_model_index = std::get<ir::ModelIndex>(from_iodesc);
        const auto &from_subg_index = std::get<ir::SubgraphIndex>(from_iodesc);
        const auto &from_ioindex = std::get<ir::IOIndex>(from_iodesc).value();
        // Supported only sequantial execution of models
        assert(from_model_index.value() < model_index.value());
        assert(from_subg_index.value() == 0);
        const auto from_executor = _executors.at({from_model_index, from_subg_index}).get();
        const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
        if (_edge_quant_tensors.find(to_iodesc) == _edge_quant_tensors.end())
        {
          inputs_inter[i] = from_executor->getOutputTensors().at(from_ioindex);
        }
        else
        {
          inputs_inter[i] = _edge_quant_tensors.at(to_iodesc).get();
        }
        assert(inputs_inter[i]->buffer() != nullptr);
      }
    }
    // Set outputs of executor
    for (uint32_t i = 0; i < output_size; i++)
    {
      const auto output_pkg_index = find_output_index(_model_edges->pkg_outputs, model_index,
                                                      ir::SubgraphIndex{0}, ir::IOIndex{i});
      const auto output_io_desc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      if (output_pkg_index != -1)
      {
        // Allocate type-aware quantization tensors for nnpkg outputs and set internal tensors
        if (_pkg_output_quant_tensors.find(output_io_desc) != _pkg_output_quant_tensors.end())
        {
          _pkg_output_quant_tensors[output_io_desc]->allocate_buffer();
          outputs_inter[i] = _pkg_output_quant_tensors[output_io_desc].get();
        }
        else
        {
          outputs_inter[i] = _pkg_output_tensors[output_io_desc].get();
        }
        // Set buffer of IOTensor
        auto output_desc = desc.outputs[output_pkg_index].get();
        _pkg_output_tensors[output_io_desc]->setUserTensor(
          reinterpret_cast<uint8_t *>(output_desc->buffer), output_desc->size);
      }
      else
      {
        // Allocate buffer of `from` tensors
        const auto from_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
        _edge_tensors[from_iodesc]->allocate_buffer();
        outputs_inter[i] = _edge_tensors[from_iodesc].get();
        // Allocate buffer of tensors for type-aware quantization
        for (const auto &to_iodesc : _edge_map[from_iodesc])
        {
          _edge_tensors[from_iodesc]->increase_ref();
          if (_edge_quant_tensors.find(to_iodesc) != _edge_quant_tensors.end())
          {
            auto type_aware_quant_tensor = _edge_quant_tensors.at(to_iodesc).get();
            type_aware_quant_tensor->allocate_buffer();
            _edge_tensors[from_iodesc]->decrease_ref();
          }
        }
      }
    }
    _pkg_input_quant_layers[{model_index, ir::SubgraphIndex{0}}]->run();
    executor->execute(inputs_inter, outputs_inter);
    _edge_quant_layers[{model_index, ir::SubgraphIndex{0}}]->run();
    _pkg_output_quant_layers[{model_index, ir::SubgraphIndex{0}}]->run();
    // Release input buffers that are no longer needed
    for (uint32_t i = 0; i < input_size; i++)
    {
      const auto input_pkg_index = find_input_index(_model_edges->pkg_inputs, model_index,
                                                    ir::SubgraphIndex{0}, ir::IOIndex{i});
      const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      if (input_pkg_index == -1)
      {
        if (_edge_quant_tensors.find(to_iodesc) != _edge_quant_tensors.end())
        {
          // Decrease reference count of tensor for type-aware quantization if input tensor is the
          // tensor
          const auto to_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
          if (_edge_quant_tensors.find(to_iodesc) != _edge_quant_tensors.end())
          {
            _edge_quant_tensors[to_iodesc]->decrease_ref();
          }
        }
        else
        {
          // Decrease reference count of `from` tensor if input tensor is the `from` tensor
          const auto from_iodesc = find_from(model_index, ir::SubgraphIndex{0}, ir::IOIndex{i});
          _edge_tensors[from_iodesc]->decrease_ref();
          // Decrease reference count of nnpkg inputs
          if (_pkg_input_quant_tensors.find(to_iodesc) != _pkg_input_quant_tensors.end())
          {
            _pkg_input_quant_tensors[to_iodesc]->decrease_ref();
          }
        }
      }
    }
    // Release output buffers if those buffers are no longer used other executors because of
    // type-aware quantization
    // FIXME if tensors for type-aware quantization unified for the same `from` tensor and same type
    for (uint32_t i = 0; i < output_size; i++)
    {
      auto from_iodesc = ir::IODesc{model_index, ir::SubgraphIndex{0}, ir::IOIndex{i}};
      // Check if other executors will use the buffer of edge tensor
      const auto &to_list = _edge_map[from_iodesc];
      if (to_list.size() == 0)
      {
        // This condition means `from_iodesc` tensor is an output of nnpkg
        continue;
      }
      bool to_be_release =
        !std::any_of(to_list.begin(), to_list.end(), [&](const ir::IODesc &to_iodesc) {
          // This condition means another executor uses the buffer of edge tensor
          return _edge_quant_tensors.find(to_iodesc) == _edge_quant_tensors.end();
        });
      if (to_be_release)
      {
        // This edge tensor's buffer won't be used in other executors
        // Tensors for type-aware quantization take over the role of this edge tensor instead
        _edge_tensors[from_iodesc]->decrease_ref();
      }
      // Decrease reference count of nnpkg outputs
      if (_pkg_output_quant_tensors.find(from_iodesc) != _pkg_output_quant_tensors.end())
      {
        _pkg_output_quant_tensors[from_iodesc]->decrease_ref();
      }
    }
  }
}
References at(), onert::exec::IExecutor::getInputTensors(), onert::exec::IODescription::inputs, onert::exec::IODescription::outputs, and onert::util::Index< T, DummyTag >::value().
inputInfo()
const ir::OperandInfo & onert::exec::MultiModelExecutors::inputInfo (const ir::IOIndex & index) const override virtual
Return NN package input tensor info.
Parameters
[in] index Input index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 120 of file MultiModelExecutors.cc.
{
  auto const desc = _model_edges->pkg_inputs[index.value()];
  auto const model_index = std::get<0>(desc);
  auto const subg_index = std::get<1>(desc);
  auto const io_index = std::get<2>(desc);
  auto const executor = at(model_index, subg_index);
  return executor->getInputTensors().at(io_index.value())->orig_info();
}
References at(), and onert::util::Index< T, DummyTag >::value().
inputSize()
uint32_t onert::exec::MultiModelExecutors::inputSize () const override virtual
Return executor set's number of input.
Returns
Number of input
Implements onert::exec::IExecutors.
Definition at line 116 of file MultiModelExecutors.cc.
{ return _model_edges->pkg_inputs.size(); }
outputInfo()
const ir::OperandInfo & onert::exec::MultiModelExecutors::outputInfo (const ir::IOIndex & index) const override virtual
Return NN package output tensor info.
Parameters
[in] index Output index
Returns
Tensor info
Implements onert::exec::IExecutors.
Definition at line 130 of file MultiModelExecutors.cc.
{
  auto const desc = _model_edges->pkg_outputs[index.value()];
  auto const model_index = std::get<0>(desc);
  auto const subg_index = std::get<1>(desc);
  auto const io_index = std::get<2>(desc);
  auto const executor = at(model_index, subg_index);
  return executor->getOutputTensors().at(io_index.value())->orig_info();
}
References at(), and onert::util::Index< T, DummyTag >::value().
outputSize()
uint32_t onert::exec::MultiModelExecutors::outputSize () const override virtual
Return executor set's number of output.
Returns
Number of output
Implements onert::exec::IExecutors.
Definition at line 118 of file MultiModelExecutors.cc.
{ return _model_edges->pkg_outputs.size(); }
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/MultiModelExecutors.h
runtime/onert/core/src/exec/MultiModelExecutors.cc