ONE - On-device Neural Engine: loco::Conv2D Class Reference
loco::Conv2D Class Reference final
2D Spatial Convolution
#include <Nodes.h>
Public Member Functions
Node * ifm (void) const
void ifm (Node *node)
Node * ker (void) const
void ker (Node *node)
const Padding2D * pad (void) const
Padding2D * pad (void)
const Stride< 2 > * stride (void) const
Stride< 2 > * stride (void)
Public Member Functions inherited from loco::CanonicalNodeDef< CanonicalOpcode::Conv2D, FixedArity< 2 >::Mixin >
virtual ~CanonicalNodeDef ()=default
uint32_t opnum (void) const final
CanonicalOpcode opcode (void) const final
Public Member Functions inherited from loco::CanonicalNode
virtual ~CanonicalNode ()=default
const Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CanonicalOpcode opcode (void) const =0
template<typename T >
T accept (CanonicalNodeVisitorBase< T > *) const
template<typename T >
T accept (CanonicalNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
2D Spatial Convolution
Definition at line 553 of file Nodes.h.
Member Function Documentation
ifm() [1/2]
void loco::Conv2D::ifm (Node * node) inline
Definition at line 557 of file Nodes.h.
{ at(0)->node(node); }
ifm() [2/2]
Node * loco::Conv2D::ifm (void) const inline
Definition at line 556 of file Nodes.h.
{ return at(0)->node(); }
Referenced by exo::Conv2DConverter::convert(), and mir2loco::Transformer::visit().
ker() [1/2]
void loco::Conv2D::ker (Node * node) inline
Definition at line 560 of file Nodes.h.
{ at(1)->node(node); }
ker() [2/2]
Node * loco::Conv2D::ker (void) const inline
Definition at line 559 of file Nodes.h.
{ return at(1)->node(); }
Referenced by exo::Conv2DConverter::convert().
pad() [1/2]
Padding2D * loco::Conv2D::pad (void) inline
Definition at line 564 of file Nodes.h.
{ return &_pad; }
pad() [2/2]
const Padding2D * loco::Conv2D::pad (void) const inline
Definition at line 563 of file Nodes.h.
{ return &_pad; }
Referenced by exo::Conv2DConverter::convert().
stride() [1/2]
Stride< 2 > * loco::Conv2D::stride (void) inline
Definition at line 568 of file Nodes.h.
{ return &_stride; }
stride() [2/2]
const Stride< 2 > * loco::Conv2D::stride (void) const inline
Definition at line 567 of file Nodes.h.
{ return &_stride; }
Referenced by exo::Conv2DConverter::convert().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Nodes.h