ONE - On-device Neural Engine: mir::ops::Conv2DOp Class Reference
mir::ops::Conv2DOp Class Reference
#include <Conv2DOp.h>
Public Member Functions
Conv2DOp (Output *input, Output *kernel, const Conv2DOpAttributes &attributes)
Conv2DOp (Output *input, Output *kernel, Output *bias, const Conv2DOpAttributes &attributes)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
const std::vector< std::int32_t > & getStrides () const
const std::vector< std::int32_t > & getPaddingBefore () const
const std::vector< std::int32_t > & getPaddingAfter () const
std::int32_t getNumGroups () const
DataFormat getDataFormat () const
const Conv2DOpAttributes & getAttributes () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 29 of file Conv2DOp.h.
Constructor & Destructor Documentation
Conv2DOp() [1/2]
mir::ops::Conv2DOp::Conv2DOp (Output * input, Output * kernel, const Conv2DOpAttributes & attributes) inline
Definition at line 32 of file Conv2DOp.h.
    : Operation(Type::conv2D, {input, kernel}), _attributes(attributes)
  {
    inferOutputTypes();
  }
Conv2DOp() [2/2]
mir::ops::Conv2DOp::Conv2DOp (Output * input, Output * kernel, Output * bias, const Conv2DOpAttributes & attributes) inline
Definition at line 38 of file Conv2DOp.h.
    : Operation(Type::conv2D, {input, kernel, bias}), _attributes(attributes)
  {
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::Conv2DOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 44 of file Conv2DOp.h.
  {
    if (inputs.size() == 2)
      return new Conv2DOp(inputs[0], inputs[1], _attributes);
    else
      return new Conv2DOp(inputs[0], inputs[1], inputs[2], _attributes);
  };
getAttributes()
const Conv2DOpAttributes & mir::ops::Conv2DOp::getAttributes () const inline
Definition at line 62 of file Conv2DOp.h.
{ return _attributes; }
Referenced by mir_interpreter::MIRInterpreter::visit().
getDataFormat()
DataFormat mir::ops::Conv2DOp::getDataFormat () const inline
Definition at line 60 of file Conv2DOp.h.
{ return _attributes.data_format; }
References mir::Conv2DOpAttributes::data_format.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getNumGroups()
std::int32_t mir::ops::Conv2DOp::getNumGroups () const inline
Definition at line 58 of file Conv2DOp.h.
{ return _attributes.num_groups; }
References mir::Conv2DOpAttributes::num_groups.
Referenced by mir2loco::Transformer::visit(), nnc::AclCppOpGenerator::visit(), nnc::ModelAnalyzer::visit(), and mir::DotNodeBuilder::visit().
getPaddingAfter()
const std::vector< std::int32_t > & mir::ops::Conv2DOp::getPaddingAfter () const inline
Definition at line 56 of file Conv2DOp.h.
{ return _attributes.padding_after; }
References mir::Conv2DOpAttributes::padding_after.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getPaddingBefore()
const std::vector< std::int32_t > & mir::ops::Conv2DOp::getPaddingBefore () const inline
Definition at line 54 of file Conv2DOp.h.
{ return _attributes.padding_before; }
References mir::Conv2DOpAttributes::padding_before.
Referenced by mir2loco::Transformer::visit(), and mir::DotNodeBuilder::visit().
getStrides()
const std::vector< std::int32_t > & mir::ops::Conv2DOp::getStrides () const inline
Definition at line 52 of file Conv2DOp.h.
{ return _attributes.strides; }
References mir::Conv2DOpAttributes::strides.
Referenced by mir2loco::Transformer::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/Conv2DOp.h
compiler/mir/src/ops/Conv2DOp.cpp