ONE - On-device Neural Engine: coco::ObjectManager Class Reference
coco::ObjectManager Class Reference final
#include <ObjectManager.h>
Public Member Functions
ObjectManager (Module *m=nullptr)
template<typename T >
T * create (void)
void destroy (Object *o)
Destroy (= deallocate) an Object entity.
template<>
FeatureObject * create (void)
Public Member Functions inherited from coco::PtrManager< Object >
uint32_t size (void) const
Return the number of managed objects.
Object * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Object >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Object > release (Object *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 33 of file ObjectManager.h.
Constructor & Destructor Documentation
ObjectManager()
coco::ObjectManager::ObjectManager (Module * m = nullptr) inline
Definition at line 36 of file ObjectManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
Member Function Documentation
create() [1/2]
template<typename T > T * coco::ObjectManager::create (void)
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
create() [2/2]
template<> KernelObject * coco::ObjectManager::create (void)
Definition at line 30 of file ObjectManager.cpp.
{
  auto feature = make_unique<FeatureObject>();
  modulize(feature.get());
  return take(std::move(feature));
}
References coco::EntityBuilder::modulize(), and coco::PtrManager< Object >::take().
destroy()
void coco::ObjectManager::destroy (Object * o)
Destroy (= deallocate) an Object entity.
NOTE An Object SHOULD HAVE NO DEF & USES to be destructed NOTE An Object WILL BE unlinked from its dependent bag (if has) on destruction
Definition at line 44 of file ObjectManager.cpp.
{
  assert(o->def() == nullptr);
  assert(o->uses()->size() == 0);
  release(o);
}
References coco::Object::def(), coco::PtrManager< Object >::release(), and coco::Object::uses().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/ObjectManager.h
compiler/coco/core/src/IR/ObjectManager.cpp