ONE - On-device Neural Engine: luci_interpreter::kernels::TransposeConv Class Reference
luci_interpreter::kernels::TransposeConv Class Reference
#include <TransposeConv.h>
Public Member Functions
TransposeConv (const Tensor *output_shape, const Tensor *filter, const Tensor *input, const Tensor *bias, Tensor *output, Tensor *scratch_tensor, const TransposeConvParams &params)
~TransposeConv ()
const Tensor * output_shape () const
const Tensor * filter () const
const Tensor * input () const
const Tensor * bias () const
Tensor * output () const
void configure () override
void execute () const override
TransposeConv (const Tensor *output_shape, const Tensor *filter, const Tensor *input, const Tensor *bias, Tensor *output, Tensor *scratch_tensor, const TransposeConvParams &params)
~TransposeConv ()
const Tensor * output_shape () const
const Tensor * filter () const
const Tensor * input () const
const Tensor * bias () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< TransposeConvParams >
const TransposeConvParams & params () const
const TransposeConvParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< TransposeConvParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const TransposeConvParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const TransposeConvParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< TransposeConvParams >
const TransposeConvParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 30 of file TransposeConv.h.
Constructor & Destructor Documentation
TransposeConv() [1/2]
luci_interpreter::kernels::TransposeConv::TransposeConv (const Tensor * output_shape, const Tensor * filter, const Tensor * input, const Tensor * bias, Tensor * output, Tensor * scratch_tensor, const TransposeConvParams & params)
Definition at line 33 of file TransposeConv.cpp.
  : KernelWithParams<TransposeConvParams>({output_shape, filter, input, bias},
                                          {output, scratch_tensor}, params)
{
}
References bias(), filter(), input(), and output_shape().
~TransposeConv() [1/2]
luci_interpreter::kernels::TransposeConv::~TransposeConv ()
Definition at line 41 of file TransposeConv.cpp.
{
  // Define destructor here, to delete vector of qunatized multipliers properly
}
TransposeConv() [2/2]
luci_interpreter::kernels::TransposeConv::TransposeConv (const Tensor * output_shape, const Tensor * filter, const Tensor * input, const Tensor * bias, Tensor * output, Tensor * scratch_tensor, const TransposeConvParams & params)
~TransposeConv() [2/2]
luci_interpreter::kernels::TransposeConv::~TransposeConv ()
Member Function Documentation
bias() [1/2]
const Tensor * luci_interpreter::kernels::TransposeConv::bias () const inline
Definition at line 42 of file TransposeConv.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
Referenced by TransposeConv().
bias() [2/2]
const Tensor * luci_interpreter::kernels::TransposeConv::bias () const inline
Definition at line 42 of file TransposeConv.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::TransposeConv::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 46 of file TransposeConv.cpp.
{
  assert(output_shape()->shape().num_dims() == 1);
  assert(input()->shape().num_dims() == 4);
  assert(filter()->shape().num_dims() == 4);
  assert(input()->element_type() == DataType::FLOAT32 || input()->element_type() == DataType::U8 ||
         input()->element_type() == DataType::S16);
  assert(input()->element_type() == output()->element_type());
  assert(input()->shape().dim(3) == filter()->shape().dim(3));
  const int num_dims = output_shape()->shape().dim(0);
  Shape out_shape(num_dims);
  const auto *shape_data = getTensorData<int32_t>(output_shape());
  for (int i = 0; i < num_dims; i++)
    out_shape.dim(i) = shape_data[i];
  output()->resize(out_shape);
  const int32_t filter_height = filter()->shape().dim(1);
  const int32_t filter_width = filter()->shape().dim(2);
  const int32_t output_height = out_shape.dim(1);
  const int32_t output_width = out_shape.dim(2);
  const int32_t unused_output_height =
    computeOutputSize(params().padding, output_height, filter_height, params().stride_height, 1);
  const int32_t unused_output_width =
    computeOutputSize(params().padding, output_width, filter_width, params().stride_width, 1);
  _padding_height =
    computePadding(params().stride_height, 1, output_height, filter_height, unused_output_height);
  _padding_width =
    computePadding(params().stride_width, 1, output_width, filter_width, unused_output_width);
  if (input()->element_type() == DataType::U8 || input()->element_type() == DataType::S16)
  {
    auto scratch_tensor = getOutputTensors()[1];
    scratch_tensor->resize(output()->shape());
    const std::vector<double> real_multipliers =
      getQuantizedConvolutionMultiplers(input()->scale(), filter()->scales(), output()->scale());
    _quant_multipliers = quantizeMultipliers(real_multipliers);
  }
  else
  {
    auto scratch_tensor = getOutputTensors()[1];
    scratch_tensor->set_allocatable(false);
  }
}
References luci_interpreter::kernels::computeOutputSize(), luci_interpreter::kernels::computePadding(), luci_interpreter::Shape::dim(), filter(), luci_interpreter::Kernel::getOutputTensors(), luci_interpreter::kernels::getQuantizedConvolutionMultiplers(), input(), output(), output_shape(), luci_interpreter::KernelWithParams< TransposeConvParams >::params(), luci_interpreter::kernels::quantizeMultipliers(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::TransposeConv::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::TransposeConv::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 94 of file TransposeConv.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::U8:
      if (filter()->scales().size() == 1)
      {
        evalQuantized();
      }
      else if (filter()->scales().size() > 1)
      {
        LUCI_INTERPRETER_CHECK(filter()->shape().num_dims() == 4);
        LUCI_INTERPRETER_CHECK(filter()->scales().size() ==
                               static_cast<size_t>(filter()->shape().dim(0)));
        evalQuantizedPerChannel();
      }
      break;
    case DataType::S16:
      evalQuantizedS16();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References filter(), input(), LUCI_INTERPRETER_CHECK, and luci_interpreter::size().
execute() [2/2]
void luci_interpreter::kernels::TransposeConv::execute () const override virtual
Implements luci_interpreter::Kernel.
filter() [1/2]
const Tensor * luci_interpreter::kernels::TransposeConv::filter () const inline
Definition at line 40 of file TransposeConv.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and TransposeConv().
filter() [2/2]
const Tensor * luci_interpreter::kernels::TransposeConv::filter () const inline
Definition at line 40 of file TransposeConv.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
input() [1/2]
const Tensor * luci_interpreter::kernels::TransposeConv::input () const inline
Definition at line 41 of file TransposeConv.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and TransposeConv().
input() [2/2]
const Tensor * luci_interpreter::kernels::TransposeConv::input () const inline
Definition at line 41 of file TransposeConv.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::TransposeConv::output () const inline
Definition at line 43 of file TransposeConv.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::TransposeConv::output () const inline
Definition at line 43 of file TransposeConv.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
output_shape() [1/2]
const Tensor * luci_interpreter::kernels::TransposeConv::output_shape () const inline
Definition at line 39 of file TransposeConv.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and TransposeConv().
output_shape() [2/2]
const Tensor * luci_interpreter::kernels::TransposeConv::output_shape () const inline
Definition at line 39 of file TransposeConv.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/TransposeConv.h
onert-micro/luci-interpreter/src/kernels/TransposeConv.h
compiler/luci-interpreter/src/kernels/TransposeConv.cpp
onert-micro/luci-interpreter/src/kernels/TransposeConv.cpp