ONE - On-device Neural Engine: onert_micro::core::train::OMTrainingHandler Class Reference
onert_micro::core::train::OMTrainingHandler Class Reference
#include <OMTrainingHandler.h>
Public Member Functions
OMTrainingHandler ()=default
OMTrainingHandler (const OMTrainingHandler &)=delete
OMTrainingHandler (OMTrainingHandler &&)=delete
OMTrainingHandler & operator= (const OMTrainingHandler &)=delete
OMTrainingHandler && operator= (const OMTrainingHandler &&)=delete
~OMTrainingHandler ()=default
void setInputData (uint8_t *data, uint32_t input_index)
void setTargetData (uint8_t *data, uint32_t target_index)
uint8_t * getInputData (uint32_t input_index)
uint8_t * getTargetData (uint32_t target_index)
OMStatus handleError (const OMConfig &config, OMRuntimeStorage &forward_storage, OMRuntimeStorage &backward_storage, OMRuntimeContext &context, uint32_t batch_num)
OMStatus updateOptimizerState (const OMConfig &config, OMRuntimeStorage &backward_storage, OMRuntimeContext &context)
OMStatus updateWeights (const OMConfig &config, OMRuntimeContext &context, OMRuntimeStorage &storage)
OMStatus evaluateMetric (OMMetrics metric, void *metric_val, OMRuntimeStorage &storage, OMRuntimeContext &context, uint32_t batch_num)
OMStatus setOptimizer (const OMConfig &config)
OMTrainingStorage & getTrainingStorage ()
void reset ()
Detailed Description
Definition at line 36 of file OMTrainingHandler.h.
Constructor & Destructor Documentation
OMTrainingHandler() [1/3]
onert_micro::core::train::OMTrainingHandler::OMTrainingHandler () default
OMTrainingHandler() [2/3]
onert_micro::core::train::OMTrainingHandler::OMTrainingHandler (const OMTrainingHandler &) delete
OMTrainingHandler() [3/3]
onert_micro::core::train::OMTrainingHandler::OMTrainingHandler (OMTrainingHandler &&) delete
~OMTrainingHandler()
onert_micro::core::train::OMTrainingHandler::~OMTrainingHandler () default
Member Function Documentation
evaluateMetric()
OMStatus OMTrainingHandler::evaluateMetric (OMMetrics metric, void * metric_val, OMRuntimeStorage & storage, OMRuntimeContext & context, uint32_t batch_num)
NOTE: This offset will always return 0 if the MODEL OUTPUT is returning 1 value of prediction. (forward_output->size() == length of output vector.) one-hot: size == target_numbers Sparse cross : size == 1
Definition at line 232 of file OMTrainingHandler.cpp.
{
  // Go over all outputs and calculate metric
  auto forward_outputs = context.getCircleOutputs();
  for (uint32_t i = 0; i < forward_outputs->size(); ++i)
  {
    // Get output tensor
    const auto forward_output_index = forward_outputs->operator[](i);
    const auto forward_output_tensor = context.getTensorByIndex(forward_output_index);
    OMRuntimeShape shape(forward_output_tensor);
    const auto flat_size = shape.flatSize();
    // Check type
    assert(forward_output_tensor->type() == circle::TensorType_FLOAT32 && "Unsupported type");
    if (forward_output_tensor->type() != circle::TensorType_FLOAT32)
      return UnsupportedType;
    // Get calculated data
    uint8_t *calculated_data = nullptr;
    OMStatus status = storage.getDataByTensorIndex(&calculated_data, forward_output_index);
    assert(calculated_data != nullptr);
    // Get target data
    size_t offset = batch_num * sizeof(core::OMDataType(forward_output_tensor->type())) * flat_size;
    uint8_t *target_data = _training_storage.getTargetData(i) + offset;
    // Note: always cast it to float
    float *f_metric_val = reinterpret_cast<float *>(metric_val);
    switch (metric)
    {
      case MSE_METRICS:
      {
        // Note: sum up new calculated value for current sample
        *f_metric_val +=
          metrics::MSE::calculateValue(flat_size, reinterpret_cast<float *>(calculated_data),
                                       reinterpret_cast<float *>(target_data));
        break;
      }
      case MAE_METRICS:
      {
        // Note: sum up new calculated value for current sample
        *f_metric_val +=
          metrics::MAE::calculateValue(flat_size, reinterpret_cast<float *>(calculated_data),
                                       reinterpret_cast<float *>(target_data));
        break;
      }
      case CROSS_ENTROPY_METRICS:
      {
        // Note: sum up new calculated value for current sample
        *f_metric_val += metrics::CrossEntropy::calculateValue(
          flat_size, reinterpret_cast<float *>(calculated_data),
          reinterpret_cast<float *>(target_data));
        break;
      }
      case ACCURACY:
      {
        // Note: sum up new calculated value for current sample
        *f_metric_val +=
          metrics::Accuracy::calculateValue(flat_size, reinterpret_cast<float *>(calculated_data),
                                            reinterpret_cast<float *>(target_data));
        break;
      }
      case SPARSE_CROSS_ENTROPY_ACCURACY:
      {
        // Note: sum up new calculated value for current sample
        *f_metric_val += metrics::SparseCrossEntropyAccuracy::calculateValue(
          flat_size, reinterpret_cast<float *>(calculated_data),
          reinterpret_cast<float *>(target_data));
        break;
      }
      default:
      {
        assert(false && "Unsupported loss type");
        return UnsupportedType;
      }
    }
  }
  return Ok;
}
References onert_micro::ACCURACY, onert_micro::train::metrics::Accuracy::calculateValue(), onert_micro::train::metrics::CrossEntropy::calculateValue(), onert_micro::train::metrics::MAE::calculateValue(), onert_micro::train::metrics::MSE::calculateValue(), onert_micro::train::metrics::SparseCrossEntropyAccuracy::calculateValue(), onert_micro::CROSS_ENTROPY_METRICS, onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeContext::getCircleOutputs(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::core::train::OMTrainingStorage::getTargetData(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::MAE_METRICS, onert_micro::MSE_METRICS, offset(), onert_micro::Ok, onert_micro::SPARSE_CROSS_ENTROPY_ACCURACY, and onert_micro::UnsupportedType.
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric().
getInputData()
uint8_t * onert_micro::core::train::OMTrainingHandler::getInputData (uint32_t input_index) inline
Definition at line 59 of file OMTrainingHandler.h.
  {
    return _training_storage.getInputData(input_index);
  }
References onert_micro::core::train::OMTrainingStorage::getInputData().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), onert_micro::core::OMTrainingRuntimeModule::getInputData(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getTargetData()
uint8_t * onert_micro::core::train::OMTrainingHandler::getTargetData (uint32_t target_index) inline
Definition at line 63 of file OMTrainingHandler.h.
  {
    return _training_storage.getTargetData(target_index);
  }
References onert_micro::core::train::OMTrainingStorage::getTargetData().
getTrainingStorage()
OMTrainingStorage & onert_micro::core::train::OMTrainingHandler::getTrainingStorage () inline
Definition at line 95 of file OMTrainingHandler.h.
{ return _training_storage; }
Referenced by onert_micro::core::OMTrainingRuntimeModule::createCheckpointFile(), onert_micro::core::OMTrainingRuntimeModule::importTrainModel(), and onert_micro::core::OMTrainingRuntimeModule::loadCheckpointData().
handleError()
OMStatus OMTrainingHandler::handleError (const OMConfig & config, OMRuntimeStorage & forward_storage, OMRuntimeStorage & backward_storage, OMRuntimeContext & context, uint32_t batch_num)
Definition at line 37 of file OMTrainingHandler.cpp.
{
  auto forward_outputs = context.getCircleOutputs();
  // Go over all outputs
  for (uint32_t i = 0; i < forward_outputs->size(); ++i)
  {
    const auto forward_output_index = forward_outputs->operator[](i);
    const auto forward_output_tensor = context.getTensorByIndex(forward_output_index);
    OMRuntimeShape shape(forward_output_tensor);
    const auto flat_size = shape.flatSize();
    // Check type
    assert(forward_output_tensor->type() == circle::TensorType_FLOAT32 && "Unsupported type");
    if (forward_output_tensor->type() != circle::TensorType_FLOAT32)
      return UnsupportedType;
    // Get calculated data
    uint8_t *calculated_data = nullptr;
    OMStatus status = forward_storage.getDataByTensorIndex(&calculated_data, forward_output_index);
    assert(calculated_data != nullptr);
    OMLoss loss_type = config.training_context.loss;
    // Get target data
    auto data_type_size = sizeof(core::OMDataType(forward_output_tensor->type()));
    size_t offset = batch_num * data_type_size * flat_size;
    // Need to check loss type to control proper offset.
    if (loss_type == SPARSE_CROSS_ENTROPY)
    {
      offset = batch_num * data_type_size;
    }
    uint8_t *target_data = _training_storage.getTargetData(i) + offset;
    // Allocate data for error gradient for current calculated data and target data
    uint8_t *output_grad_data;
    core::memory::OMMemoryManager::allocateMemory(flat_size * data_type_size, &output_grad_data);
    // Save error gradient into backward storage associated with current output tensor index
    backward_storage.saveDataToTensorIndex(output_grad_data, forward_output_index);
    // Handle different loss types
    switch (loss_type)
    {
      case MSE:
      {
        losses_functions::MSE::calculateErrorBackpropagation(
          flat_size, reinterpret_cast<float *>(calculated_data),
          reinterpret_cast<float *>(target_data), reinterpret_cast<float *>(output_grad_data));
        break;
      }
      case CROSS_ENTROPY:
      {
        losses_functions::CrossEntropy::calculateErrorBackpropagation(
          flat_size, reinterpret_cast<float *>(calculated_data),
          reinterpret_cast<float *>(target_data), reinterpret_cast<float *>(output_grad_data));
        break;
      }
      case SPARSE_CROSS_ENTROPY:
      {
        losses_functions::SparseCrossEntropy::calculateErrorBackpropagation(
          flat_size, reinterpret_cast<float *>(calculated_data),
          reinterpret_cast<float *>(target_data), reinterpret_cast<float *>(output_grad_data));
        break;
      }
      default:
      {
        assert(false && "Unsupported loss type");
        return UnsupportedType;
      }
    }
  }
  return Ok;
}
References onert_micro::core::memory::OMMemoryManager::allocateMemory(), onert_micro::train::losses_functions::CrossEntropy::calculateErrorBackpropagation(), onert_micro::train::losses_functions::MSE::calculateErrorBackpropagation(), onert_micro::train::losses_functions::SparseCrossEntropy::calculateErrorBackpropagation(), onert_micro::CROSS_ENTROPY, onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeContext::getCircleOutputs(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), onert_micro::core::train::OMTrainingStorage::getTargetData(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::MSE, offset(), onert_micro::Ok, onert_micro::core::OMRuntimeStorage::saveDataToTensorIndex(), onert_micro::SPARSE_CROSS_ENTROPY, and onert_micro::UnsupportedType.
Referenced by onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
operator=() [1/2]
OMTrainingHandler && onert_micro::core::train::OMTrainingHandler::operator= (const OMTrainingHandler &&) delete
operator=() [2/2]
OMTrainingHandler & onert_micro::core::train::OMTrainingHandler::operator= (const OMTrainingHandler &) delete
reset()
void OMTrainingHandler::reset ()
Definition at line 215 of file OMTrainingHandler.cpp.
{ _training_storage.reset(); }
References onert_micro::core::train::OMTrainingStorage::reset().
Referenced by onert_micro::core::OMTrainingRuntimeModule::reset().
setInputData()
void onert_micro::core::train::OMTrainingHandler::setInputData (uint8_t * data, uint32_t input_index) inline
Definition at line 49 of file OMTrainingHandler.h.
  {
    _training_storage.setInputData(data, input_index);
  }
References onert_micro::core::train::OMTrainingStorage::setInputData().
Referenced by onert_micro::core::OMTrainingRuntimeModule::setInputData().
setOptimizer()
OMStatus onert_micro::core::train::OMTrainingHandler::setOptimizer (const OMConfig & config) inline
Definition at line 92 of file OMTrainingHandler.h.
{ return _training_storage.setOptimizer(config); }
References onert_micro::core::train::OMTrainingStorage::setOptimizer().
Referenced by onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
setTargetData()
void onert_micro::core::train::OMTrainingHandler::setTargetData (uint8_t * data, uint32_t target_index) inline
Definition at line 53 of file OMTrainingHandler.h.
  {
    _training_storage.setTargetData(data, target_index);
  }
References onert_micro::core::train::OMTrainingStorage::setTargetData().
Referenced by onert_micro::core::OMTrainingRuntimeModule::setTargetData().
updateOptimizerState()
OMStatus OMTrainingHandler::updateOptimizerState (const OMConfig & config, OMRuntimeStorage & backward_storage, OMRuntimeContext & context)
Definition at line 177 of file OMTrainingHandler.cpp.
{
  OMStatus status = Ok;
  switch (config.training_context.optimizer)
  {
    case SGD:
    {
      auto *sgd_optimizer = _training_storage.getSGD();
      assert(sgd_optimizer != nullptr);
      if (sgd_optimizer == nullptr)
        return UnknownError;
      sgd_optimizer->handle(backward_storage, context, backward_storage);
      break;
    }
    case ADAM:
    {
      auto *adam_optimizer = _training_storage.getAdam();
      assert(adam_optimizer != nullptr);
      if (adam_optimizer == nullptr)
        return UnknownError;
      adam_optimizer->handle(backward_storage, context, backward_storage);
      break;
    }
    default:
    {
      assert(false && "Unsupported type");
      return UnsupportedType;
    }
  }
  return status;
}
References onert_micro::ADAM, onert_micro::core::train::OMTrainingStorage::getAdam(), onert_micro::core::train::OMTrainingStorage::getSGD(), onert_micro::Ok, onert_micro::SGD, onert_micro::UnknownError, and onert_micro::UnsupportedType.
Referenced by onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
updateWeights()
OMStatus OMTrainingHandler::updateWeights (const OMConfig & config, OMRuntimeContext & context, OMRuntimeStorage & storage)
Definition at line 118 of file OMTrainingHandler.cpp.
{
  OMStatus status = Ok;
  // Chose optimizer type
  switch (config.training_context.optimizer)
  {
    case SGD:
    {
      auto *sgd_optimizer = _training_storage.getSGD();
      assert(sgd_optimizer != nullptr);
      if (sgd_optimizer == nullptr)
        return UnknownError;
      status = sgd_optimizer->updateWeights(config.training_context, context, storage,
                                            _training_storage.getTensorIndexToRankTypeTable());
      assert(status == Ok);
      // Reset values
#ifdef OM_MEMORY_ESTIMATE
      sgd_optimizer->reset(context, storage);
#else
      sgd_optimizer->reset();
#endif // OM_MEMORY_ESTIMATE
      break;
    }
    case ADAM:
    {
      auto *adam_optimizer = _training_storage.getAdam();
      assert(adam_optimizer != nullptr);
      if (adam_optimizer == nullptr)
        return UnknownError;
      status = adam_optimizer->updateWeights(config.training_context, context, storage,
                                             _training_storage.getTensorIndexToRankTypeTable());
      assert(status == Ok);
      // Reset values
#ifdef OM_MEMORY_ESTIMATE
      adam_optimizer->reset(context, storage);
#else
      adam_optimizer->reset();
#endif // OM_MEMORY_ESTIMATE
      break;
    }
    default:
    {
      assert(false && "Unsupported type");
      return UnsupportedType;
    }
  }
  return status;
}
References onert_micro::ADAM, onert_micro::core::train::OMTrainingStorage::getAdam(), onert_micro::core::train::OMTrainingStorage::getSGD(), onert_micro::core::train::OMTrainingStorage::getTensorIndexToRankTypeTable(), onert_micro::Ok, onert_micro::SGD, onert_micro::UnknownError, and onert_micro::UnsupportedType.
Referenced by onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/train/OMTrainingHandler.h
onert-micro/onert-micro/src/core/train/OMTrainingHandler.cpp