ONE - On-device Neural Engine: mir::Tensor< T > Class Template Reference
mir::Tensor< T > Class Template Reference final
#include <Tensor.h>
Public Member Functions
Tensor (const TensorVariant &t)
T at (const Index &id) const
T & at (const Index &id)
T atOffset (int32_t offset) const
T & atOffset (int32_t offset)
ExternalRegion< T > getRegion (const Index &idx)
const Shape & getShape () const
Detailed Description
template<typename T>
class mir::Tensor< T >
Definition at line 26 of file Tensor.h.
Constructor & Destructor Documentation
Tensor()
template<typename T > mir::Tensor< T >::Tensor (const TensorVariant & t) inline explicit
Definition at line 29 of file Tensor.h.
: _proxy(t) {}
Member Function Documentation
at() [1/2]
template<typename T > T & mir::Tensor< T >::at (const Index & id) inline
Definition at line 33 of file Tensor.h.
{ return *reinterpret_cast<T *>(this->_proxy.at(id)); }
References mir::TensorVariant::at().
at() [2/2]
template<typename T > T mir::Tensor< T >::at (const Index & id) const inline
Definition at line 31 of file Tensor.h.
{ return *reinterpret_cast<T *>(this->_proxy.at(id)); }
References mir::TensorVariant::at().
Referenced by mir_caffe::CaffeOpCreator::convertBatchNorm(), mir_onnx::convertBatchNormalizationV9(), mir_tflite::TFLiteOpCreator::convertPad(), mir_caffe2::Caffe2OpCreator::convertReshape(), mir_onnx::convertReshapeV5(), mir_tflite::TFLiteOpCreator::convertResizeNearestNeighbor(), mir_caffe2::Caffe2OpCreator::convertSpatialBN(), mir_interpreter::Dequantize(), mir_interpreter::Quantize(), mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::ELUImpl< T >::run(), mir_interpreter::LeakyReLUImpl< T >::run(), mir_interpreter::CappedReLUImpl< T >::run(), mir_interpreter::CappedReLUImpl< uint8_t >::run(), mir_interpreter::SoftmaxImpl< T >::run(), mir_interpreter::AbsImpl< T >::run(), mir_interpreter::ReLUImpl< T >::run(), mir_interpreter::SigmoidImpl< T >::run(), mir_interpreter::SqrtImpl< T >::run(), mir_interpreter::TanhImpl< T >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), mir_interpreter::ReduceMeanImpl< T >::run(), mir_interpreter::FullyConnectedImpl< T >::run(), mir_interpreter::Conv2DImpl< uint8_t >::run(), mir_interpreter::AddImpl< T >::run(), mir_interpreter::AddImpl< uint8_t >::run(), mir_interpreter::DivImpl< T >::run(), mir_interpreter::EqualImpl< T >::run(), mir_interpreter::GreaterImpl< T >::run(), mir_interpreter::LessImpl< T >::run(), mir_interpreter::MaxImpl< T >::run(), mir_interpreter::MulImpl< T >::run(), mir_interpreter::SubImpl< T >::run(), and mir_interpreter::FillImpl< T >::run().
atOffset() [1/2]
template<typename T > T & mir::Tensor< T >::atOffset (int32_t offset) inline
Definition at line 37 of file Tensor.h.
{ return *reinterpret_cast<T *>(this->_proxy.atOffset(offset)); }
References mir::TensorVariant::atOffset(), and offset().
atOffset() [2/2]
template<typename T > T mir::Tensor< T >::atOffset (int32_t offset) const inline
Definition at line 35 of file Tensor.h.
{ return *reinterpret_cast<T *>(this->_proxy.atOffset(offset)); }
References mir::TensorVariant::atOffset(), and offset().
Referenced by mir_interpreter::GatherImpl< T, IndicesT >::run().
getRegion()
template<typename T > ExternalRegion< T > mir::Tensor< T >::getRegion (const Index & idx) inline
Definition at line 39 of file Tensor.h.
  {
    // Only last dimension is safe to process continiously
    auto last_dim = getShape().rank() - 1;
    auto base = reinterpret_cast<T *>(_proxy.at(idx));
    auto length = getShape().dim(last_dim) - idx.at(last_dim);
    return ExternalRegion<T>(base, length);
  }
References mir::TensorVariant::at(), mir::Index::at(), mir::Shape::dim(), mir::Tensor< T >::getShape(), and mir::Shape::rank().
getShape()
template<typename T > const Shape & mir::Tensor< T >::getShape () const inline
Definition at line 48 of file Tensor.h.
{ return _proxy.getShape(); };
References mir::TensorVariant::getShape().
Referenced by mir_caffe::CaffeOpCreator::convertBatchNorm(), mir_onnx::convertBatchNormalizationV9(), mir_caffe2::Caffe2OpCreator::convertReshape(), mir_caffe2::Caffe2OpCreator::convertSpatialBN(), mir::Tensor< T >::getRegion(), and mir_interpreter::PadImpl< T >::run().
The documentation for this class was generated from the following file:
compiler/mir/include/mir/Tensor.h