ONE - On-device Neural Engine: benchmark::Phases Class Reference
benchmark::Phases Class Reference
#include <Phases.h>
Public Types
using PhaseFunc = std::function< void(const Phase &, uint32_t)>
Public Member Functions
Phases (const PhaseOption &option)
void run (const std::string &tag, const PhaseFunc &exec, uint32_t loop_num=1, bool option_disable=false)
void run (const std::string &tag, const PhaseFunc &exec, const PhaseFunc &post, uint32_t loop_num=1, bool option_disable=false)
const PhaseOption & option () const
const MemoryPoller & mem_poll () const
const Phase & at (const std::string &tag) const
uint32_t mem_before_init () const
uint32_t mem_after_run () const
Detailed Description
Definition at line 30 of file Phases.h.
Member Typedef Documentation
PhaseFunc
using benchmark::Phases::PhaseFunc = std::function<void(const Phase &, uint32_t)>
Definition at line 35 of file Phases.h.
Constructor & Destructor Documentation
Phases()
benchmark::Phases::Phases (const PhaseOption & option)
Definition at line 50 of file Phases.cpp.
                                        : _option(option), _mem_before_init(0), _mem_after_run(0)
{
  assert(prepareVmRSS());
  _mem_before_init = getVmHWM();
  if (_option.memory)
  {
    _mem_poll = std::make_unique<MemoryPoller>(std::chrono::milliseconds(option.memory_interval),
                                               option.memory_gpu);
  }
}
References benchmark::getVmHWM(), benchmark::PhaseOption::memory, benchmark::PhaseOption::memory_gpu, benchmark::PhaseOption::memory_interval, option(), and benchmark::prepareVmRSS().
Member Function Documentation
at()
const Phase & benchmark::Phases::at (const std::string & tag) const inline
Definition at line 51 of file Phases.h.
{ return _phases.at(tag); }
Referenced by benchmark::Result::Result().
mem_after_run()
uint32_t benchmark::Phases::mem_after_run () const inline
Definition at line 54 of file Phases.h.
{ return _mem_after_run; }
Referenced by benchmark::Result::Result().
mem_before_init()
uint32_t benchmark::Phases::mem_before_init () const inline
Definition at line 53 of file Phases.h.
{ return _mem_before_init; }
Referenced by benchmark::Result::Result().
mem_poll()
const MemoryPoller & benchmark::Phases::mem_poll () const inline
Definition at line 50 of file Phases.h.
{ return *_mem_poll; }
option()
const PhaseOption & benchmark::Phases::option () const inline
Definition at line 49 of file Phases.h.
{ return _option; }
Referenced by Phases(), and benchmark::Result::Result().
run() [1/2]
void benchmark::Phases::run (const std::string & tag, const PhaseFunc & exec, const PhaseFunc & post, uint32_t loop_num = 1, bool option_disable = false) inline
Definition at line 43 of file Phases.h.
  {
    run(tag, exec, &post, loop_num, option_disable);
  }
References run().
run() [2/2]
void benchmark::Phases::run (const std::string & tag, const PhaseFunc & exec, uint32_t loop_num = 1, bool option_disable = false) inline
Definition at line 37 of file Phases.h.
  {
    run(tag, exec, nullptr, loop_num, option_disable);
  }
References run().
Referenced by run().
The documentation for this class was generated from the following files:
runtime/libs/benchmark/include/benchmark/Phases.h
runtime/libs/benchmark/src/Phases.cpp