ONE - On-device Neural Engine: luci_interpreter::kernels::ResizeNearestNeighbor Class Reference
luci_interpreter::kernels::ResizeNearestNeighbor Class Reference
#include <ResizeNearestNeighbor.h>
Public Member Functions
ResizeNearestNeighbor (const Tensor *input, const Tensor *shape, Tensor *output, const ResizeNearestNeighborParams &params)
const Tensor * input () const
const Tensor * size () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< ResizeNearestNeighborParams >
const ResizeNearestNeighborParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< ResizeNearestNeighborParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ResizeNearestNeighborParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< ResizeNearestNeighborParams >
const ResizeNearestNeighborParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
Detailed Description
Definition at line 28 of file ResizeNearestNeighbor.h.
Constructor & Destructor Documentation
ResizeNearestNeighbor()
luci_interpreter::kernels::ResizeNearestNeighbor::ResizeNearestNeighbor (const Tensor * input, const Tensor * shape, Tensor * output, const ResizeNearestNeighborParams & params)
Definition at line 30 of file ResizeNearestNeighbor.cpp.
  : KernelWithParams<ResizeNearestNeighborParams>({input, size}, {output}, params)
{
}
References input(), and size().
Member Function Documentation
configure()
void luci_interpreter::kernels::ResizeNearestNeighbor::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 37 of file ResizeNearestNeighbor.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() == 4);
  LUCI_INTERPRETER_CHECK(size()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(size()->element_type() == DataType::S32);
  LUCI_INTERPRETER_CHECK(size()->shape().dim(0) == 2);
  Shape output_shape(4);
  output_shape.dim(0) = input()->shape().dim(0);
  output_shape.dim(1) = getTensorData<int32_t>(size())[0];
  output_shape.dim(2) = getTensorData<int32_t>(size())[1];
  output_shape.dim(3) = input()->shape().dim(3);
  output()->resize(output_shape);
}
References luci_interpreter::Shape::dim(), input(), LUCI_INTERPRETER_CHECK, output(), output_shape, luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), and size().
execute()
void luci_interpreter::kernels::ResizeNearestNeighbor::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 51 of file ResizeNearestNeighbor.cpp.
{
  tflite::ResizeNearestNeighborParams op_params{};
  op_params.align_corners = params().align_corners;
  op_params.half_pixel_centers = params().half_pixel_centers;
  switch (output()->element_type())
  {
    case DataType::FLOAT32:
      tflite::reference_ops::ResizeNearestNeighbor(
        op_params, getTensorShape(input()), getTensorData<int32_t>(input()), getTensorShape(size()),
        getTensorData<int32_t>(size()), getTensorShape(output()), getTensorData<int32_t>(output()));
      break;
    case DataType::U8:
      luci_interpreter_pal::ResizeNearestNeighbor(
        op_params, getTensorShape(input()), getTensorData<uint8_t>(input()), getTensorShape(size()),
        getTensorData<int32_t>(size()), getTensorShape(output()), getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("luci-intp ResizeNearestNeighbor Unsupported type.");
  }
}
References luci_interpreter::ResizeNearestNeighborParams::align_corners, luci_interpreter::kernels::getTensorShape(), luci_interpreter::ResizeNearestNeighborParams::half_pixel_centers, input(), output(), luci_interpreter::KernelWithParams< ResizeNearestNeighborParams >::params(), and size().
input()
const Tensor * luci_interpreter::kernels::ResizeNearestNeighbor::input () const inline
Definition at line 34 of file ResizeNearestNeighbor.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ResizeNearestNeighbor().
output()
Tensor * luci_interpreter::kernels::ResizeNearestNeighbor::output () const inline
Definition at line 36 of file ResizeNearestNeighbor.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
size()
const Tensor * luci_interpreter::kernels::ResizeNearestNeighbor::size () const inline
Definition at line 35 of file ResizeNearestNeighbor.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ResizeNearestNeighbor().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.h
compiler/luci-interpreter/src/kernels/ResizeNearestNeighbor.cpp