ONE - On-device Neural Engine: coco::Step Class Reference
coco::Step Class Reference final
A Step denotes the edge between Op and Instr.
#include <Step.h>
Public Member Functions
Step (Instr *instr)
~Step ()
Op * op (void) const
void op (Op *o)
Instr * instr (void) const
Detailed Description
A Step denotes the edge between Op and Instr.
Definition at line 29 of file Step.h.
Constructor & Destructor Documentation
Step()
coco::Step::Step (Instr * instr) inline explicit
Definition at line 32 of file Step.h.
                              : _instr{instr}
  {
    // DO NOTHING
  }
~Step()
coco::Step::~Step () inline
Definition at line 38 of file Step.h.
{ op(nullptr); }
References op().
Member Function Documentation
instr()
Instr * coco::Step::instr (void) const inline
Definition at line 45 of file Step.h.
{ return _instr; }
Referenced by coco::Op::parent().
op() [1/2]
void coco::Step::op (Op * o)
Definition at line 25 of file Step.cpp.
{
  if (_op != nullptr)
  {
    // Unlink step from _op
    assert(_op->_step == this);
    _op->_step = nullptr;
    // Reset _op
    _op = nullptr;
  }
  assert(_op == nullptr);
  if (o)
  {
    // Update _op
    _op = o;
    // Link step to _op
    assert(_op->_step == nullptr);
    _op->_step = this;
  }
  assert(_op == o);
}
op() [2/2]
Op * coco::Step::op (void) const inline
Definition at line 41 of file Step.h.
{ return _op; }
Referenced by coco::Eval::op(), and ~Step().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Step.h
compiler/coco/core/src/IR/Step.cpp