ONE - On-device Neural Engine: onert_micro::execute::pal::Reducer< T, ReduceFn > Class Template Reference
onert_micro::execute::pal::Reducer< T, ReduceFn > Class Template Reference
#include <PALReduceCommon.h>
Public Member Functions
Reducer (core::OMReduceDataContext< T > &ctx, T init_value)
bool Mean ()
bool Reduce ()
Detailed Description
template<typename T, template< typename > class ReduceFn>
class onert_micro::execute::pal::Reducer< T, ReduceFn >
Definition at line 76 of file PALReduceCommon.h.
Constructor & Destructor Documentation
Reducer()
template<typename T , template< typename > class ReduceFn> onert_micro::execute::pal::Reducer< T, ReduceFn >::Reducer (core::OMReduceDataContext< T > & ctx, T init_value) inline explicit
Definition at line 93 of file PALReduceCommon.h.
    : _input(ctx.Input())
    , _output(ctx.Output())
    , _axes(ctx.Axis())
    , _init_value(init_value)
  {}
Member Function Documentation
Mean()
template<typename T , template< typename > class ReduceFn> bool onert_micro::execute::pal::Reducer< T, ReduceFn >::Mean () inline
Definition at line 101 of file PALReduceCommon.h.
  {
    if (SpecialCaseMeanImpl())
      return true;
    return ReduceImpl(true);
  }
Referenced by impl::CircleMean().
Reduce()
template<typename T , template< typename > class ReduceFn> bool onert_micro::execute::pal::Reducer< T, ReduceFn >::Reduce () inline
Definition at line 109 of file PALReduceCommon.h.
  {
    return ReduceImpl();
  }
Referenced by impl::CircleReduceMax(), impl::CircleReduceProd(), and impl::CircleSum().
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/pal/mcu/PALReduceCommon.h