ONE - On-device Neural Engine: moco::ConstGraphBuilder Class Reference
moco::ConstGraphBuilder Class Reference
#include <Const.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const final
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const final
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 25 of file Const.h.
Member Function Documentation
build()
void moco::ConstGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const final virtual
Implements moco::GraphBuilder.
Definition at line 172 of file Const.cpp.
{
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  // Create a "TFConstant" node for Const
  auto const_node = graph->nodes()->create<TFConst>();
  const_node->name(node.name());
  // set dtype
  auto dtype = plier::tf::as_loco_datatype(plier::tf::get_datatype_attr(node, "dtype"));
  const_node->dtype(dtype);
  // import shape and value
  const auto &input_tensor = plier::tf::get_tensor_attr(node, "value");
  const auto &input_shape = input_tensor.tensor_shape();
  const auto &input_dims = input_shape.dim();
  assert(input_shape.dim_size() <= 6);
  const_node->rank(input_shape.dim_size());
  int index = 0;
  bool zero_sized_shape = false;
  for (auto &d : input_dims)
  {
    assert(d.size() <= std::numeric_limits<int>::max());
    if (d.size() == 0)
      zero_sized_shape = true;
    assert(d.size() >= 0);
    const_node->dim(index++) = d.size();
  }
  int num_elements = 1;
  if (zero_sized_shape)
  {
    const_node->rank(0);
    num_elements = 0;
  }
  else
  {
    for (uint32_t d = 0; d < const_node->rank(); d++)
    {
      num_elements *= const_node->dim(d).value();
    }
  }
  switch (dtype)
  {
    case loco::DataType::S8:
      read_value_int8(const_node, num_elements, input_tensor);
      break;
    case loco::DataType::S32:
      read_value_int32(const_node, num_elements, input_tensor);
      break;
    case loco::DataType::FLOAT32:
      read_value_float32(const_node, num_elements, input_tensor);
      break;
      // TODO support other types
    default:
      assert(false);
  }
  // register string-name to node
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, const_node);
}
References plier::tf::as_loco_datatype(), moco::SymbolTable::enroll(), plier::tf::get_datatype_attr(), plier::tf::get_tensor_attr(), moco::GraphBuilderContext::graph(), moco::index(), moco::TFNode::name(), moco::TFConst::size(), and moco::GraphBuilderContext::tensor_names().
validate()
bool moco::ConstGraphBuilder::validate (const tensorflow::NodeDef & node) const final virtual
Implements moco::GraphBuilder.
Definition at line 142 of file Const.cpp.
{
  if (!plier::tf::has_attrs(node, {"dtype", "value"}))
    return false;
  const auto &input_tensor = plier::tf::get_tensor_attr(node, "value");
  const auto &input_shape = input_tensor.tensor_shape();
  const auto &input_dims = input_shape.dim();
  if (!(input_shape.dim_size() <= 6))
    return false;
  for (auto &d : input_dims)
  {
    if (d.size() > std::numeric_limits<int>::max())
      throw oops::UserExn("Const Shape element overflows", node.name());
    if (d.size() < 0)
      throw oops::UserExn("Unknown dim size", node.name());
  }
  auto dtype = plier::tf::as_loco_datatype(plier::tf::get_datatype_attr(node, "dtype"));
  if (!(dtype == loco::DataType::S32 || dtype == loco::DataType::FLOAT32 ||
        dtype == loco::DataType::S8))
    return false;
  // TODO support other dtype
  return true;
}
References plier::tf::as_loco_datatype(), plier::tf::get_datatype_attr(), plier::tf::get_tensor_attr(), and plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Const.h
compiler/moco/import/src/Nodes/Const.cpp