ONE - On-device Neural Engine: onert::backend::train::ops::LossCategoricalCrossentropyLayer Class Reference
onert::backend::train::ops::LossCategoricalCrossentropyLayer Class Reference
#include <LossCategoricalCrossentropyLayer.h>
Public Member Functions
LossCategoricalCrossentropyLayer ()=default
void configure (const IPortableTensor *y_pred, const IPortableTensor *y_true, IPortableTensor *output, IPortableTensor *back_prop_y_pred, int32_t axis, float label_smoothing)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::backend::train::ops::LossLayer
LossLayer ()
void configure (const IPortableTensor *y_pred, const IPortableTensor *y_true, IPortableTensor *output, IPortableTensor *back_prop_y_pred)
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
virtual void forward (bool training)=0
virtual void backward ()=0
Additional Inherited Members
Protected Attributes inherited from onert::backend::train::ops::LossLayer
const IPortableTensor * _y_pred
const IPortableTensor * _y_true
IPortableTensor * _output
IPortableTensor * _back_prop_y_pred
Detailed Description
Definition at line 32 of file LossCategoricalCrossentropyLayer.h.
Constructor & Destructor Documentation
LossCategoricalCrossentropyLayer()
onert::backend::train::ops::LossCategoricalCrossentropyLayer::LossCategoricalCrossentropyLayer () default
Member Function Documentation
backward()
void onert::backend::train::ops::LossCategoricalCrossentropyLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 105 of file LossCategoricalCrossentropyLayer.cc.
{
  if (_y_pred->data_type() == OperandType::FLOAT32)
  {
    categoricalCrossEntropyGradFloat32();
  }
  else
  {
    throw std::runtime_error("LossCategoricalCrossentropyLayer: unsupported data type");
  }
}
References onert::backend::train::ops::LossLayer::_y_pred, and onert::backend::ITensor::data_type().
configure()
void onert::backend::train::ops::LossCategoricalCrossentropyLayer::configure (const IPortableTensor * y_pred, const IPortableTensor * y_true, IPortableTensor * output, IPortableTensor * back_prop_y_pred, int32_t axis, float label_smoothing)
Definition at line 31 of file LossCategoricalCrossentropyLayer.cc.
{
  LossLayer::configure(y_pred, y_true, output, back_prop_y_pred);
  _axis = axis;
  _label_smoothing = label_smoothing;
}
References onert::backend::train::ops::LossLayer::configure().
forward()
void onert::backend::train::ops::LossCategoricalCrossentropyLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 93 of file LossCategoricalCrossentropyLayer.cc.
{
  if (_y_pred->data_type() == OperandType::FLOAT32)
  {
    categoricalCrossEntropyFloat32();
  }
  else
  {
    throw std::runtime_error("LossCategoricalCrossentropyLayer: unsupported data type");
  }
}
References onert::backend::train::ops::LossLayer::_y_pred, and onert::backend::ITensor::data_type().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.h
runtime/onert/backend/train/ops/LossCategoricalCrossentropyLayer.cc