ONE - On-device Neural Engine: luci::VerifyQuantizedNodeTypeBase< Qtype, Btype > Class Template Reference
luci::VerifyQuantizedNodeTypeBase< Qtype, Btype > Class Template Reference
Verify using quantization type of a node and bias.
#include <VerifyQuantizedNodeType.h>
Public Member Functions
bool verify (luci::CircleNode *node)
Public Member Functions inherited from luci::CircleNodeVisitor< bool >
virtual ~CircleNodeVisitor ()=default
virtual bool visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
virtual bool verify (luci::CircleNode *node)=0
Protected Member Functions
bool has_type (const loco::Node *node, loco::DataType dtype)
bool group_has_type (const loco::Node *node, loco::DataType dtype)
Additional Inherited Members
Static Public Member Functions inherited from luci::VerifyQuantizedNodeType
static std::shared_ptr< VerifyQuantizedNodeType > create (loco::DataType dtype)
Detailed Description
template<loco::DataType Qtype, loco::DataType Btype>
class luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >
Verify using quantization type of a node and bias.
Template Parameters
Qtype Quantization type for a node (e.g. Q8, Q16, ...)
Btype Bias quantization type (e.g. For Q8, S32 is used)
Definition at line 50 of file VerifyQuantizedNodeType.h.
Member Function Documentation
group_has_type()
template<loco::DataType Qtype, loco::DataType Btype> bool luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::group_has_type (const loco::Node * node, loco::DataType dtype) inline protected
Definition at line 64 of file VerifyQuantizedNodeType.h.
  {
    if (!has_type(node, dtype))
      return false;
    for (uint32_t i = 0; i < node->arity(); ++i)
      if (!has_type(node->arg(i), dtype))
        return false;
    return true;
  }
References loco::Node::arg(), loco::Node::arity(), and luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::has_type().
has_type()
template<loco::DataType Qtype, loco::DataType Btype> bool luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::has_type (const loco::Node * node, loco::DataType dtype) inline protected
Definition at line 57 of file VerifyQuantizedNodeType.h.
  {
    auto circle_node = loco::must_cast<const luci::CircleNode *>(node);
    return circle_node->dtype() == dtype;
  }
Referenced by luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::group_has_type().
verify()
template<loco::DataType Qtype, loco::DataType Btype> bool luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::verify (luci::CircleNode * node) inline virtual
Implements luci::VerifyQuantizedNodeType.
Definition at line 54 of file VerifyQuantizedNodeType.h.
{ return node->accept(this); }
References luci::CircleNode::accept().
The documentation for this class was generated from the following files:
compiler/luci/pass/src/VerifyQuantizedNodeType.h
compiler/luci/pass/src/VerifyQuantizedNodeType.cpp