ONE - On-device Neural Engine: flexbuffers::Reference Class Reference
flexbuffers::Reference Class Reference
#include <flexbuffers.h>
Public Member Functions
Reference ()
Reference (const uint8_t *data, uint8_t parent_width, uint8_t byte_width, Type type)
Reference (const uint8_t *data, uint8_t parent_width, uint8_t packed_type)
Type GetType () const
bool IsNull () const
bool IsBool () const
bool IsInt () const
bool IsUInt () const
bool IsIntOrUint () const
bool IsFloat () const
bool IsNumeric () const
bool IsString () const
bool IsKey () const
bool IsVector () const
bool IsUntypedVector () const
bool IsTypedVector () const
bool IsFixedTypedVector () const
bool IsAnyVector () const
bool IsMap () const
bool IsBlob () const
bool AsBool () const
int64_t AsInt64 () const
int32_t AsInt32 () const
int16_t AsInt16 () const
int8_t AsInt8 () const
uint64_t AsUInt64 () const
uint32_t AsUInt32 () const
uint16_t AsUInt16 () const
uint8_t AsUInt8 () const
double AsDouble () const
float AsFloat () const
const char * AsKey () const
String AsString () const
std::string ToString () const
void ToString (bool strings_quoted, bool keys_quoted, std::string &s) const
Blob AsBlob () const
Vector AsVector () const
TypedVector AsTypedVector () const
FixedTypedVector AsFixedTypedVector () const
Map AsMap () const
template<typename T >
T As () const
bool MutateInt (int64_t i)
bool MutateBool (bool b)
bool MutateUInt (uint64_t u)
bool MutateFloat (float f)
bool MutateFloat (double d)
bool MutateString (const char *str, size_t len)
bool MutateString (const char *str)
bool MutateString (const std::string &str)
template<>
bool As () const
template<>
int8_t As () const
template<>
int16_t As () const
template<>
int32_t As () const
template<>
int64_t As () const
template<>
uint8_t As () const
template<>
uint16_t As () const
template<>
uint32_t As () const
template<>
uint64_t As () const
template<>
double As () const
template<>
float As () const
template<>
String As () const
template<>
Blob As () const
template<>
Vector As () const
template<>
TypedVector As () const
template<>
FixedTypedVector As () const
template<>
Map As () const
Friends
class Verifier
Detailed Description
Definition at line 373 of file flexbuffers.h.
Constructor & Destructor Documentation
Reference() [1/3]
flexbuffers::Reference::Reference () inline
Definition at line 375 of file flexbuffers.h.
      : data_(nullptr), parent_width_(0), byte_width_(0), type_(FBT_NULL) {}
Reference() [2/3]
flexbuffers::Reference::Reference (const uint8_t * data, uint8_t parent_width, uint8_t byte_width, Type type) inline
Definition at line 378 of file flexbuffers.h.
      : data_(data),
        parent_width_(parent_width),
        byte_width_(byte_width),
        type_(type) {}
Reference() [3/3]
flexbuffers::Reference::Reference (const uint8_t * data, uint8_t parent_width, uint8_t packed_type) inline
Definition at line 385 of file flexbuffers.h.
      : data_(data),
        parent_width_(parent_width),
        byte_width_(static_cast<uint8_t>(1 << (packed_type & 3))),
        type_(static_cast<Type>(packed_type >> 2)) {}
Member Function Documentation
As() [1/18]
template<typename T > T flexbuffers::Reference::As () const
As() [2/18]
template<> bool flexbuffers::Reference::As () const inline
Definition at line 786 of file flexbuffers.h.
{ return AsBool(); }
References AsBool().
As() [3/18]
template<> int8_t flexbuffers::Reference::As () const inline
Definition at line 788 of file flexbuffers.h.
{ return AsInt8(); }
References AsInt8().
As() [4/18]
template<> int16_t flexbuffers::Reference::As () const inline
Definition at line 789 of file flexbuffers.h.
{ return AsInt16(); }
References AsInt16().
As() [5/18]
template<> int32_t flexbuffers::Reference::As () const inline
Definition at line 790 of file flexbuffers.h.
{ return AsInt32(); }
References AsInt32().
As() [6/18]
template<> int64_t flexbuffers::Reference::As () const inline
Definition at line 791 of file flexbuffers.h.
{ return AsInt64(); }
References AsInt64().
As() [7/18]
template<> uint8_t flexbuffers::Reference::As () const inline
Definition at line 793 of file flexbuffers.h.
{ return AsUInt8(); }
References AsUInt8().
As() [8/18]
template<> uint16_t flexbuffers::Reference::As () const inline
Definition at line 794 of file flexbuffers.h.
{
  return AsUInt16();
}
References AsUInt16().
As() [9/18]
template<> uint32_t flexbuffers::Reference::As () const inline
Definition at line 797 of file flexbuffers.h.
{
  return AsUInt32();
}
References AsUInt32().
As() [10/18]
template<> uint64_t flexbuffers::Reference::As () const inline
Definition at line 800 of file flexbuffers.h.
{
  return AsUInt64();
}
References AsUInt64().
As() [11/18]
template<> double flexbuffers::Reference::As () const inline
Definition at line 804 of file flexbuffers.h.
{ return AsDouble(); }
References AsDouble().
As() [12/18]
template<> float flexbuffers::Reference::As () const inline
Definition at line 805 of file flexbuffers.h.
{ return AsFloat(); }
References AsFloat().
As() [13/18]
template<> String flexbuffers::Reference::As () const inline
Definition at line 807 of file flexbuffers.h.
{ return AsString(); }
References AsString().
As() [14/18]
template<> Blob flexbuffers::Reference::As () const inline
Definition at line 812 of file flexbuffers.h.
{ return AsBlob(); }
References AsBlob().
As() [15/18]
template<> Vector flexbuffers::Reference::As () const inline
Definition at line 813 of file flexbuffers.h.
{ return AsVector(); }
References AsVector().
As() [16/18]
template<> TypedVector flexbuffers::Reference::As () const inline
Definition at line 814 of file flexbuffers.h.
{
  return AsTypedVector();
}
References AsTypedVector().
As() [17/18]
template<> FixedTypedVector flexbuffers::Reference::As () const inline
Definition at line 817 of file flexbuffers.h.
{
  return AsFixedTypedVector();
}
References AsFixedTypedVector().
As() [18/18]
template<> Map flexbuffers::Reference::As () const inline
Definition at line 820 of file flexbuffers.h.
{ return AsMap(); }
References AsMap().
AsBlob()
Blob flexbuffers::Reference::AsBlob () const inline
Definition at line 616 of file flexbuffers.h.
                      {
    if (type_ == FBT_BLOB || type_ == FBT_STRING) {
      return Blob(Indirect(), byte_width_);
    } else {
      return Blob::EmptyBlob();
    }
  }
References flexbuffers::Blob::EmptyBlob(), flexbuffers::FBT_BLOB, and flexbuffers::FBT_STRING.
Referenced by As(), and ToString().
AsBool()
bool flexbuffers::Reference::AsBool () const inline
Definition at line 417 of file flexbuffers.h.
                      {
    return (type_ == FBT_BOOL ? ReadUInt64(data_, parent_width_)
                              : AsUInt64()) != 0;
  }
References AsUInt64(), flexbuffers::FBT_BOOL, and flexbuffers::ReadUInt64().
Referenced by As(), and ToString().
AsDouble()
double flexbuffers::Reference::AsDouble () const inline
Definition at line 481 of file flexbuffers.h.
{
    if (type_ == FBT_FLOAT) {
      // A fast path for the common case.
      return ReadDouble(data_, parent_width_);
    } else
      switch (type_) {
        case FBT_INDIRECT_FLOAT: return ReadDouble(Indirect(), byte_width_);
        case FBT_INT:
          return static_cast<double>(ReadInt64(data_, parent_width_));
        case FBT_UINT:
          return static_cast<double>(ReadUInt64(data_, parent_width_));
        case FBT_INDIRECT_INT:
          return static_cast<double>(ReadInt64(Indirect(), byte_width_));
        case FBT_INDIRECT_UINT:
          return static_cast<double>(ReadUInt64(Indirect(), byte_width_));
        case FBT_NULL: return 0.0;
        case FBT_STRING: {
          double d;
          flatbuffers::StringToNumber(AsString().c_str(), &d);
          return d;
        }
        case FBT_VECTOR: return static_cast<double>(AsVector().size());
        case FBT_BOOL:
          return static_cast<double>(ReadUInt64(data_, parent_width_));
        default:
          // Convert strings and other things to float.
          return 0;
      }
  }
References AsString(), AsVector(), flexbuffers::FBT_BOOL, flexbuffers::FBT_FLOAT, flexbuffers::FBT_INDIRECT_FLOAT, flexbuffers::FBT_INDIRECT_INT, flexbuffers::FBT_INDIRECT_UINT, flexbuffers::FBT_INT, flexbuffers::FBT_NULL, flexbuffers::FBT_STRING, flexbuffers::FBT_UINT, flexbuffers::FBT_VECTOR, flexbuffers::ReadDouble(), flexbuffers::ReadInt64(), flexbuffers::ReadUInt64(), flexbuffers::Sized::size(), and flatbuffers::StringToNumber().
Referenced by As(), AsFloat(), and ToString().
AsFixedTypedVector()
FixedTypedVector flexbuffers::Reference::AsFixedTypedVector () const inline
Definition at line 653 of file flexbuffers.h.
{
    if (IsFixedTypedVector()) {
      uint8_t len = 0;
      auto vtype = ToFixedTypedVectorElementType(type_, &len);
      return FixedTypedVector(Indirect(), byte_width_, vtype, len);
    } else {
      return FixedTypedVector::EmptyFixedTypedVector();
    }
  }
References flexbuffers::FixedTypedVector::EmptyFixedTypedVector(), IsFixedTypedVector(), and flexbuffers::ToFixedTypedVectorElementType().
Referenced by As(), and ToString().
AsFloat()
float flexbuffers::Reference::AsFloat () const inline
Definition at line 511 of file flexbuffers.h.
{ return static_cast<float>(AsDouble()); }
References AsDouble().
Referenced by As().
AsInt16()
int16_t flexbuffers::Reference::AsInt16 () const inline
Definition at line 451 of file flexbuffers.h.
{ return static_cast<int16_t>(AsInt64()); }
References AsInt64().
Referenced by As().
AsInt32()
int32_t flexbuffers::Reference::AsInt32 () const inline
Definition at line 450 of file flexbuffers.h.
{ return static_cast<int32_t>(AsInt64()); }
References AsInt64().
Referenced by As().
AsInt64()
int64_t flexbuffers::Reference::AsInt64 () const inline
Definition at line 425 of file flexbuffers.h.
{
    if (type_ == FBT_INT) {
      // A fast path for the common case.
      return ReadInt64(data_, parent_width_);
    } else
      switch (type_) {
        case FBT_INDIRECT_INT: return ReadInt64(Indirect(), byte_width_);
        case FBT_UINT: return ReadUInt64(data_, parent_width_);
        case FBT_INDIRECT_UINT: return ReadUInt64(Indirect(), byte_width_);
        case FBT_FLOAT:
          return static_cast<int64_t>(ReadDouble(data_, parent_width_));
        case FBT_INDIRECT_FLOAT:
          return static_cast<int64_t>(ReadDouble(Indirect(), byte_width_));
        case FBT_NULL: return 0;
        case FBT_STRING: return flatbuffers::StringToInt(AsString().c_str());
        case FBT_VECTOR: return static_cast<int64_t>(AsVector().size());
        case FBT_BOOL: return ReadInt64(data_, parent_width_);
        default:
          // Convert other things to int.
          return 0;
      }
  }
References AsString(), AsVector(), flexbuffers::FBT_BOOL, flexbuffers::FBT_FLOAT, flexbuffers::FBT_INDIRECT_FLOAT, flexbuffers::FBT_INDIRECT_INT, flexbuffers::FBT_INDIRECT_UINT, flexbuffers::FBT_INT, flexbuffers::FBT_NULL, flexbuffers::FBT_STRING, flexbuffers::FBT_UINT, flexbuffers::FBT_VECTOR, flexbuffers::ReadDouble(), flexbuffers::ReadInt64(), flexbuffers::ReadUInt64(), flexbuffers::Sized::size(), and flatbuffers::StringToInt().
Referenced by As(), AsInt16(), AsInt32(), AsInt8(), and ToString().
AsInt8()
int8_t flexbuffers::Reference::AsInt8 () const inline
Definition at line 452 of file flexbuffers.h.
{ return static_cast<int8_t>(AsInt64()); }
References AsInt64().
Referenced by As().
AsKey()
const char * flexbuffers::Reference::AsKey () const inline
Definition at line 513 of file flexbuffers.h.
{
    if (type_ == FBT_KEY || type_ == FBT_STRING) {
      return reinterpret_cast<const char *>(Indirect());
    } else {
      return "";
    }
  }
References flexbuffers::FBT_KEY, and flexbuffers::FBT_STRING.
Referenced by ToString().
AsMap()
Map flexbuffers::Reference::AsMap () const inline
Definition at line 663 of file flexbuffers.h.
                    {
    if (type_ == FBT_MAP) {
      return Map(Indirect(), byte_width_);
    } else {
      return Map::EmptyMap();
    }
  }
References flexbuffers::Map::EmptyMap(), and flexbuffers::FBT_MAP.
Referenced by As(), circledump::CustomOpPrinter::options(), tfldump::CustomOpPrinter::options(), and ToString().
AsString()
String flexbuffers::Reference::AsString () const inline
Definition at line 523 of file flexbuffers.h.
{
    if (type_ == FBT_STRING) {
      return String(Indirect(), byte_width_);
    } else if (type_ == FBT_KEY) {
      auto key = Indirect();
      return String(key, byte_width_,
                    strlen(reinterpret_cast<const char *>(key)));
    } else {
      return String::EmptyString();
    }
  }
References flexbuffers::String::EmptyString(), flexbuffers::FBT_KEY, and flexbuffers::FBT_STRING.
Referenced by As(), AsDouble(), AsInt64(), AsUInt64(), and MutateString().
AsTypedVector()
TypedVector flexbuffers::Reference::AsTypedVector () const inline
Definition at line 634 of file flexbuffers.h.
{
    if (IsTypedVector()) {
      auto tv =
          TypedVector(Indirect(), byte_width_, ToTypedVectorElementType(type_));
      if (tv.type_ == FBT_STRING) {
        // These can't be accessed as strings, since we don't know the bit-width
        // of the size field, see the declaration of
        // FBT_VECTOR_STRING_DEPRECATED above for details.
        // We change the type here to be keys, which are a subtype of strings,
        // and will ignore the size field. This will truncate strings with
        // embedded nulls.
        tv.type_ = FBT_KEY;
      }
      return tv;
    } else {
      return TypedVector::EmptyTypedVector();
    }
  }
References flexbuffers::TypedVector::EmptyTypedVector(), flexbuffers::FBT_KEY, flexbuffers::FBT_STRING, IsTypedVector(), and flexbuffers::ToTypedVectorElementType().
Referenced by As(), and ToString().
AsUInt16()
uint16_t flexbuffers::Reference::AsUInt16 () const inline
Definition at line 478 of file flexbuffers.h.
{ return static_cast<uint16_t>(AsUInt64()); }
References AsUInt64().
Referenced by As().
AsUInt32()
uint32_t flexbuffers::Reference::AsUInt32 () const inline
Definition at line 477 of file flexbuffers.h.
{ return static_cast<uint32_t>(AsUInt64()); }
References AsUInt64().
Referenced by As().
AsUInt64()
uint64_t flexbuffers::Reference::AsUInt64 () const inline
Definition at line 454 of file flexbuffers.h.
{
    if (type_ == FBT_UINT) {
      // A fast path for the common case.
      return ReadUInt64(data_, parent_width_);
    } else
      switch (type_) {
        case FBT_INDIRECT_UINT: return ReadUInt64(Indirect(), byte_width_);
        case FBT_INT: return ReadInt64(data_, parent_width_);
        case FBT_INDIRECT_INT: return ReadInt64(Indirect(), byte_width_);
        case FBT_FLOAT:
          return static_cast<uint64_t>(ReadDouble(data_, parent_width_));
        case FBT_INDIRECT_FLOAT:
          return static_cast<uint64_t>(ReadDouble(Indirect(), byte_width_));
        case FBT_NULL: return 0;
        case FBT_STRING: return flatbuffers::StringToUInt(AsString().c_str());
        case FBT_VECTOR: return static_cast<uint64_t>(AsVector().size());
        case FBT_BOOL: return ReadUInt64(data_, parent_width_);
        default:
          // Convert other things to uint.
          return 0;
      }
  }
References AsString(), AsVector(), flexbuffers::FBT_BOOL, flexbuffers::FBT_FLOAT, flexbuffers::FBT_INDIRECT_FLOAT, flexbuffers::FBT_INDIRECT_INT, flexbuffers::FBT_INDIRECT_UINT, flexbuffers::FBT_INT, flexbuffers::FBT_NULL, flexbuffers::FBT_STRING, flexbuffers::FBT_UINT, flexbuffers::FBT_VECTOR, flexbuffers::ReadDouble(), flexbuffers::ReadInt64(), flexbuffers::ReadUInt64(), flexbuffers::Sized::size(), and flatbuffers::StringToUInt().
Referenced by As(), AsBool(), AsUInt16(), AsUInt32(), AsUInt8(), and ToString().
AsUInt8()
uint8_t flexbuffers::Reference::AsUInt8 () const inline
Definition at line 479 of file flexbuffers.h.
{ return static_cast<uint8_t>(AsUInt64()); }
References AsUInt64().
Referenced by As().
AsVector()
Vector flexbuffers::Reference::AsVector () const inline
Definition at line 626 of file flexbuffers.h.
{
    if (type_ == FBT_VECTOR || type_ == FBT_MAP) {
      return Vector(Indirect(), byte_width_);
    } else {
      return Vector::EmptyVector();
    }
  }
References flexbuffers::FBT_MAP, and flexbuffers::FBT_VECTOR.
Referenced by As(), AsDouble(), AsInt64(), AsUInt64(), and ToString().
GetType()
Type flexbuffers::Reference::GetType () const inline
Definition at line 391 of file flexbuffers.h.
{ return type_; }
IsAnyVector()
bool flexbuffers::Reference::IsAnyVector () const inline
Definition at line 412 of file flexbuffers.h.
{
    return (IsTypedVector() || IsFixedTypedVector() || IsVector());
  }
References IsFixedTypedVector(), IsTypedVector(), and IsVector().
IsBlob()
bool flexbuffers::Reference::IsBlob () const inline
Definition at line 416 of file flexbuffers.h.
{ return type_ == FBT_BLOB; }
References flexbuffers::FBT_BLOB.
Referenced by ToString().
IsBool()
bool flexbuffers::Reference::IsBool () const inline
Definition at line 394 of file flexbuffers.h.
{ return type_ == FBT_BOOL; }
References flexbuffers::FBT_BOOL.
Referenced by ToString().
IsFixedTypedVector()
bool flexbuffers::Reference::IsFixedTypedVector () const inline
Definition at line 409 of file flexbuffers.h.
{
    return flexbuffers::IsFixedTypedVector(type_);
  }
References flexbuffers::IsFixedTypedVector().
Referenced by AsFixedTypedVector(), IsAnyVector(), and ToString().
IsFloat()
bool flexbuffers::Reference::IsFloat () const inline
Definition at line 400 of file flexbuffers.h.
                       {
    return type_ == FBT_FLOAT || type_ == FBT_INDIRECT_FLOAT;
  }
References flexbuffers::FBT_FLOAT, and flexbuffers::FBT_INDIRECT_FLOAT.
Referenced by IsNumeric(), and ToString().
IsInt()
bool flexbuffers::Reference::IsInt () const inline
Definition at line 395 of file flexbuffers.h.
{ return type_ == FBT_INT || type_ == FBT_INDIRECT_INT; }
References flexbuffers::FBT_INDIRECT_INT, and flexbuffers::FBT_INT.
Referenced by IsIntOrUint(), and ToString().
IsIntOrUint()
bool flexbuffers::Reference::IsIntOrUint () const inline
Definition at line 399 of file flexbuffers.h.
{ return IsInt() || IsUInt(); }
References IsInt(), and IsUInt().
Referenced by IsNumeric().
IsKey()
bool flexbuffers::Reference::IsKey () const inline
Definition at line 405 of file flexbuffers.h.
{ return type_ == FBT_KEY; }
References flexbuffers::FBT_KEY.
Referenced by ToString().
IsMap()
bool flexbuffers::Reference::IsMap () const inline
Definition at line 415 of file flexbuffers.h.
{ return type_ == FBT_MAP; }
References flexbuffers::FBT_MAP.
Referenced by ToString().
IsNull()
bool flexbuffers::Reference::IsNull () const inline
Definition at line 393 of file flexbuffers.h.
{ return type_ == FBT_NULL; }
References flexbuffers::FBT_NULL.
Referenced by ToString().
IsNumeric()
bool flexbuffers::Reference::IsNumeric () const inline
Definition at line 403 of file flexbuffers.h.
{ return IsIntOrUint() || IsFloat(); }
References IsFloat(), and IsIntOrUint().
IsString()
bool flexbuffers::Reference::IsString () const inline
Definition at line 404 of file flexbuffers.h.
{ return type_ == FBT_STRING; }
References flexbuffers::FBT_STRING.
IsTypedVector()
bool flexbuffers::Reference::IsTypedVector () const inline
Definition at line 408 of file flexbuffers.h.
{ return flexbuffers::IsTypedVector(type_); }
References flexbuffers::IsTypedVector().
Referenced by AsTypedVector(), IsAnyVector(), and ToString().
IsUInt()
bool flexbuffers::Reference::IsUInt () const inline
Definition at line 396 of file flexbuffers.h.
                      {
    return type_ == FBT_UINT || type_ == FBT_INDIRECT_UINT;
  }
References flexbuffers::FBT_INDIRECT_UINT, and flexbuffers::FBT_UINT.
Referenced by IsIntOrUint(), and ToString().
IsUntypedVector()
bool flexbuffers::Reference::IsUntypedVector () const inline
Definition at line 407 of file flexbuffers.h.
{ return type_ == FBT_VECTOR; }
References flexbuffers::FBT_VECTOR.
IsVector()
bool flexbuffers::Reference::IsVector () const inline
Definition at line 406 of file flexbuffers.h.
{ return type_ == FBT_VECTOR || type_ == FBT_MAP; }
References flexbuffers::FBT_MAP, and flexbuffers::FBT_VECTOR.
Referenced by IsAnyVector(), and ToString().
MutateBool()
bool flexbuffers::Reference::MutateBool (bool b) inline
Definition at line 695 of file flexbuffers.h.
{
    return type_ == FBT_BOOL && Mutate(data_, b, parent_width_, BIT_WIDTH_8);
  }
References flexbuffers::BIT_WIDTH_8, and flexbuffers::FBT_BOOL.
MutateFloat() [1/2]
bool flexbuffers::Reference::MutateFloat (double d) inline
Definition at line 725 of file flexbuffers.h.
{
    if (type_ == FBT_FLOAT) {
      return MutateF(data_, d, parent_width_, WidthF(d));
    } else if (type_ == FBT_INDIRECT_FLOAT) {
      return MutateF(Indirect(), d, byte_width_, WidthF(d));
    } else {
      return false;
    }
  }
References flexbuffers::FBT_FLOAT, flexbuffers::FBT_INDIRECT_FLOAT, and flexbuffers::WidthF().
MutateFloat() [2/2]
bool flexbuffers::Reference::MutateFloat (float f) inline
Definition at line 715 of file flexbuffers.h.
{
    if (type_ == FBT_FLOAT) {
      return MutateF(data_, f, parent_width_, BIT_WIDTH_32);
    } else if (type_ == FBT_INDIRECT_FLOAT) {
      return MutateF(Indirect(), f, byte_width_, BIT_WIDTH_32);
    } else {
      return false;
    }
  }
References flexbuffers::BIT_WIDTH_32, flexbuffers::FBT_FLOAT, and flexbuffers::FBT_INDIRECT_FLOAT.
MutateInt()
bool flexbuffers::Reference::MutateInt (int64_t i) inline
Definition at line 679 of file flexbuffers.h.
{
    if (type_ == FBT_INT) {
      return Mutate(data_, i, parent_width_, WidthI(i));
    } else if (type_ == FBT_INDIRECT_INT) {
      return Mutate(Indirect(), i, byte_width_, WidthI(i));
    } else if (type_ == FBT_UINT) {
      auto u = static_cast<uint64_t>(i);
      return Mutate(data_, u, parent_width_, WidthU(u));
    } else if (type_ == FBT_INDIRECT_UINT) {
      auto u = static_cast<uint64_t>(i);
      return Mutate(Indirect(), u, byte_width_, WidthU(u));
    } else {
      return false;
    }
  }
References flexbuffers::FBT_INDIRECT_INT, flexbuffers::FBT_INDIRECT_UINT, flexbuffers::FBT_INT, flexbuffers::FBT_UINT, flexbuffers::WidthI(), and flexbuffers::WidthU().
MutateString() [1/3]
bool flexbuffers::Reference::MutateString (const char * str) inline
Definition at line 744 of file flexbuffers.h.
{ return MutateString(str, strlen(str)); }
References MutateString().
Referenced by MutateString().
MutateString() [2/3]
bool flexbuffers::Reference::MutateString (const char * str, size_t len) inline
Definition at line 735 of file flexbuffers.h.
{
    auto s = AsString();
    if (s.IsTheEmptyString()) return false;
    // This is very strict, could allow shorter strings, but that creates
    // garbage.
    if (s.length() != len) return false;
    memcpy(const_cast<char *>(s.c_str()), str, len);
    return true;
  }
References AsString().
Referenced by MutateString().
MutateString() [3/3]
bool flexbuffers::Reference::MutateString (const std::string & str) inline
Definition at line 745 of file flexbuffers.h.
{
    return MutateString(str.data(), str.length());
  }
References MutateString().
MutateUInt()
bool flexbuffers::Reference::MutateUInt (uint64_t u) inline
Definition at line 699 of file flexbuffers.h.
{
    if (type_ == FBT_UINT) {
      return Mutate(data_, u, parent_width_, WidthU(u));
    } else if (type_ == FBT_INDIRECT_UINT) {
      return Mutate(Indirect(), u, byte_width_, WidthU(u));
    } else if (type_ == FBT_INT) {
      auto i = static_cast<int64_t>(u);
      return Mutate(data_, i, parent_width_, WidthI(i));
    } else if (type_ == FBT_INDIRECT_INT) {
      auto i = static_cast<int64_t>(u);
      return Mutate(Indirect(), i, byte_width_, WidthI(i));
    } else {
      return false;
    }
  }
References flexbuffers::FBT_INDIRECT_INT, flexbuffers::FBT_INDIRECT_UINT, flexbuffers::FBT_INT, flexbuffers::FBT_UINT, flexbuffers::WidthI(), and flexbuffers::WidthU().
ToString() [1/2]
std::string flexbuffers::Reference::ToString () const inline
Definition at line 536 of file flexbuffers.h.
{
    std::string s;
    ToString(false, false, s);
    return s;
  }
References ToString().
Referenced by ToString().
ToString() [2/2]
void flexbuffers::Reference::ToString (bool strings_quoted, bool keys_quoted, std::string & s) const inline
Definition at line 546 of file flexbuffers.h.
{
    if (type_ == FBT_STRING) {
      String str(Indirect(), byte_width_);
      if (strings_quoted) {
        flatbuffers::EscapeString(str.c_str(), str.length(), &s, true, false);
      } else {
        s.append(str.c_str(), str.length());
      }
    } else if (IsKey()) {
      auto str = AsKey();
      if (keys_quoted) {
        flatbuffers::EscapeString(str, strlen(str), &s, true, false);
      } else {
        s += str;
      }
    } else if (IsInt()) {
      s += flatbuffers::NumToString(AsInt64());
    } else if (IsUInt()) {
      s += flatbuffers::NumToString(AsUInt64());
    } else if (IsFloat()) {
      s += flatbuffers::NumToString(AsDouble());
    } else if (IsNull()) {
      s += "null";
    } else if (IsBool()) {
      s += AsBool() ? "true" : "false";
    } else if (IsMap()) {
      s += "{ ";
      auto m = AsMap();
      auto keys = m.Keys();
      auto vals = m.Values();
      for (size_t i = 0; i < keys.size(); i++) {
        bool kq = keys_quoted;
        if (!kq) {
          // FlexBuffers keys may contain arbitrary characters, only allow
          // unquoted if it looks like an "identifier":
          const char *p = keys[i].AsKey();
          if (!flatbuffers::is_alpha(*p) && *p != '_') {
            kq = true;
          } else {
            while (*++p) {
              if (!flatbuffers::is_alnum(*p) && *p != '_') {
                kq = true;
                break;
              }
            }
          }
        }
        keys[i].ToString(true, kq, s);
        s += ": ";
        vals[i].ToString(true, keys_quoted, s);
        if (i < keys.size() - 1) s += ", ";
      }
      s += " }";
    } else if (IsVector()) {
      AppendToString<Vector>(s, AsVector(), keys_quoted);
    } else if (IsTypedVector()) {
      AppendToString<TypedVector>(s, AsTypedVector(), keys_quoted);
    } else if (IsFixedTypedVector()) {
      AppendToString<FixedTypedVector>(s, AsFixedTypedVector(), keys_quoted);
    } else if (IsBlob()) {
      auto blob = AsBlob();
      flatbuffers::EscapeString(reinterpret_cast<const char *>(blob.data()),
                                blob.size(), &s, true, false);
    } else {
      s += "(?)";
    }
  }
References AsBlob(), AsBool(), AsDouble(), AsFixedTypedVector(), AsInt64(), AsKey(), AsMap(), AsTypedVector(), AsUInt64(), AsVector(), flatbuffers::EscapeString(), flexbuffers::FBT_STRING, flatbuffers::is_alnum(), flatbuffers::is_alpha(), IsBlob(), IsBool(), IsFixedTypedVector(), IsFloat(), IsInt(), IsKey(), IsMap(), IsNull(), IsTypedVector(), IsUInt(), IsVector(), m, flatbuffers::NumToString(), and p.
Friends And Related Symbol Documentation
Verifier
friend class Verifier friend
Definition at line 777 of file flexbuffers.h.
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h