ONE - On-device Neural Engine: onert_micro::OMInterpreter Class Reference
onert_micro::OMInterpreter Class Reference
#include <OMInterpreter.h>
Public Member Functions
OMInterpreter ()=default
OMInterpreter (const OMInterpreter &)=delete
OMInterpreter (OMInterpreter &&)=delete
OMInterpreter & operator= (const OMInterpreter &)=delete
OMInterpreter && operator= (const OMInterpreter &&)=delete
~OMInterpreter ()=default
OMStatus importModel (const char *model_ptr, const OMConfig &config)
OMStatus run ()
OMStatus reset ()
uint32_t getNumberOfInputs ()
uint32_t getNumberOfOutputs ()
OMStatus allocateInputs ()
uint32_t getInputSizeAt (uint32_t position)
uint32_t getOutputSizeAt (uint32_t position)
void * getInputDataAt (uint32_t position)
void * getOutputDataAt (uint32_t position)
Detailed Description
Definition at line 28 of file OMInterpreter.h.
Constructor & Destructor Documentation
OMInterpreter() [1/3]
onert_micro::OMInterpreter::OMInterpreter () default
OMInterpreter() [2/3]
onert_micro::OMInterpreter::OMInterpreter (const OMInterpreter &) delete
OMInterpreter() [3/3]
onert_micro::OMInterpreter::OMInterpreter (OMInterpreter &&) delete
~OMInterpreter()
onert_micro::OMInterpreter::~OMInterpreter () default
Member Function Documentation
allocateInputs()
OMStatus OMInterpreter::allocateInputs ()
Definition at line 58 of file OMInterpreter.cpp.
{ return _runtime_module.allocateInputs(); }
References onert_micro::core::OMRuntimeModule::allocateInputs().
getInputDataAt()
void * OMInterpreter::getInputDataAt (uint32_t position)
Definition at line 38 of file OMInterpreter.cpp.
{
  return _runtime_module.getInputDataAt(position);
}
References onert_micro::core::OMRuntimeModule::getInputDataAt().
getInputSizeAt()
uint32_t OMInterpreter::getInputSizeAt (uint32_t position)
Definition at line 48 of file OMInterpreter.cpp.
{
  return _runtime_module.getInputSizeAt(position);
}
References onert_micro::core::OMRuntimeModule::getInputSizeAt().
getNumberOfInputs()
uint32_t OMInterpreter::getNumberOfInputs ()
Definition at line 34 of file OMInterpreter.cpp.
{ return _runtime_module.getNumberOfInputs(); }
References onert_micro::core::OMRuntimeModule::getNumberOfInputs().
getNumberOfOutputs()
uint32_t OMInterpreter::getNumberOfOutputs ()
Definition at line 36 of file OMInterpreter.cpp.
{ return _runtime_module.getNumberOfOutputs(); }
References onert_micro::core::OMRuntimeModule::getNumberOfOutputs().
getOutputDataAt()
void * OMInterpreter::getOutputDataAt (uint32_t position)
Definition at line 43 of file OMInterpreter.cpp.
{
  return _runtime_module.getOutputDataAt(position);
}
References onert_micro::core::OMRuntimeModule::getOutputDataAt().
getOutputSizeAt()
uint32_t OMInterpreter::getOutputSizeAt (uint32_t position)
Definition at line 53 of file OMInterpreter.cpp.
{
  return _runtime_module.getOutputSizeAt(position);
}
References onert_micro::core::OMRuntimeModule::getOutputSizeAt().
importModel()
OMStatus OMInterpreter::importModel (const char * model_ptr, const OMConfig & config)
Definition at line 21 of file OMInterpreter.cpp.
{
  assert(model_ptr != nullptr && "Model ptr shouldn't be nullptr");
  if (model_ptr == nullptr)
    return UnknownError;
  return _runtime_module.importModel(model_ptr, config);
}
References onert_micro::core::OMRuntimeModule::importModel(), and onert_micro::UnknownError.
operator=() [1/2]
OMInterpreter && onert_micro::OMInterpreter::operator= (const OMInterpreter &&) delete
operator=() [2/2]
OMInterpreter & onert_micro::OMInterpreter::operator= (const OMInterpreter &) delete
reset()
OMStatus OMInterpreter::reset ()
Definition at line 32 of file OMInterpreter.cpp.
{ return _runtime_module.reset(); }
References onert_micro::core::OMRuntimeModule::reset().
run()
OMStatus OMInterpreter::run ()
Definition at line 30 of file OMInterpreter.cpp.
{ return _runtime_module.run(); }
References onert_micro::core::OMRuntimeModule::run().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/OMInterpreter.h
onert-micro/onert-micro/src/OMInterpreter.cpp