ONE - On-device Neural Engine: onert_micro::core::reader::OMWeightOnlyFormatReader Class Reference
onert_micro::core::reader::OMWeightOnlyFormatReader Class Reference
Loads Weight Only Format files and provides helpers functions.
#include <OMWeightOnlyFormatReader.h>
Public Member Functions
OMWeightOnlyFormatReader ()=default
OMWeightOnlyFormatReader (const OMWeightOnlyFormatReader &)=delete
OMWeightOnlyFormatReader (OMWeightOnlyFormatReader &&)=default
OMWeightOnlyFormatReader & operator= (const OMWeightOnlyFormatReader &)=delete
OMWeightOnlyFormatReader && operator= (const OMWeightOnlyFormatReader &&)=delete
~OMWeightOnlyFormatReader ()=default
OMStatus validate (OMCircleReader *reader)
void parse (char *ptr)
char * buffer (const uint32_t tensor_index)
Detailed Description
Loads Weight Only Format files and provides helpers functions.
Definition at line 48 of file OMWeightOnlyFormatReader.h.
Constructor & Destructor Documentation
OMWeightOnlyFormatReader() [1/3]
onert_micro::core::reader::OMWeightOnlyFormatReader::OMWeightOnlyFormatReader () default
OMWeightOnlyFormatReader() [2/3]
onert_micro::core::reader::OMWeightOnlyFormatReader::OMWeightOnlyFormatReader (const OMWeightOnlyFormatReader &) delete
OMWeightOnlyFormatReader() [3/3]
onert_micro::core::reader::OMWeightOnlyFormatReader::OMWeightOnlyFormatReader (OMWeightOnlyFormatReader &&) default
~OMWeightOnlyFormatReader()
onert_micro::core::reader::OMWeightOnlyFormatReader::~OMWeightOnlyFormatReader () default
References validate().
Member Function Documentation
buffer()
char * OMWeightOnlyFormatReader::buffer (const uint32_t tensor_index)
Definition at line 62 of file OMWeightOnlyFormatReader.cpp.
{
  if (_wof_ptr == nullptr)
    return nullptr;
  uint32_t buffer_offset = 0;
  uint32_t offset_offset = FIRST_OFFSET + tensor_index * sizeof(uint32_t);
  std::memcpy(&buffer_offset, &_wof_ptr[offset_offset], sizeof(buffer_offset));
  if (buffer_offset == 0)
    return nullptr;
  return _wof_ptr + buffer_offset;
}
Referenced by onert_micro::core::OMRuntimeContext::getConstDataByTensorIndex().
operator=() [1/2]
OMWeightOnlyFormatReader && onert_micro::core::reader::OMWeightOnlyFormatReader::operator= (const OMWeightOnlyFormatReader &&) delete
operator=() [2/2]
OMWeightOnlyFormatReader & onert_micro::core::reader::OMWeightOnlyFormatReader::operator= (const OMWeightOnlyFormatReader &) delete
parse()
void onert_micro::core::reader::OMWeightOnlyFormatReader::parse (char * ptr) inline
Definition at line 62 of file OMWeightOnlyFormatReader.h.
{ _wof_ptr = ptr; }
Referenced by onert_micro::core::OMRuntimeContext::setWofFile().
validate()
OMStatus OMWeightOnlyFormatReader::validate (OMCircleReader * reader)
Definition at line 25 of file OMWeightOnlyFormatReader.cpp.
{
  OMStatus status = Ok;
  // Validate magic number
  uint16_t mag_num = 0;
  std::memcpy(&mag_num, &_wof_ptr[MAGIC_NUMBER], sizeof(mag_num));
  assert(mag_num == wof_magic_number && "False MAGIC NUMBER, check correctness of wof file");
  if (mag_num != wof_magic_number)
    return FailReadWOFFile;
  // Validate schema version
  uint8_t version = 0;
  std::memcpy(&version, &_wof_ptr[SCHEMA_VERSION], sizeof(version));
  assert(version == schema_version && "False MAGIC NUMBER, check correctness of wof file");
  if (version != schema_version)
    return FailReadWOFFile;
  // Validate count of tensors
  assert(reader != nullptr && "Reader should exist");
  if (reader == nullptr)
    return ModelNotImport;
  uint32_t num_tensors = reader->tensors()->size();
  uint32_t num_tensors_in_wof_file = 0;
  std::memcpy(&num_tensors_in_wof_file, &_wof_ptr[NUM_BUFFERS], sizeof(num_tensors_in_wof_file));
  assert(num_tensors == num_tensors_in_wof_file &&
         "Number of tensors in circle and in wof file should be the same");
  if (num_tensors != num_tensors_in_wof_file)
    return FailReadWOFFile;
  return status;
}
References onert_micro::FailReadWOFFile, onert_micro::ModelNotImport, onert_micro::Ok, onert_micro::core::reader::schema_version, flatbuffers::Vector< T, SizeT >::size(), onert_micro::core::reader::OMCircleReader::tensors(), and onert_micro::core::reader::wof_magic_number.
Referenced by onert_micro::core::OMRuntimeContext::setWofFile(), and ~OMWeightOnlyFormatReader().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/reader/OMWeightOnlyFormatReader.h
onert-micro/onert-micro/src/core/reader/OMWeightOnlyFormatReader.cpp