ONE - On-device Neural Engine: pp::LinearDocument Class Reference
pp::LinearDocument Class Reference final
#include <LinearDocument.h>
Public Types
enum class Direction { Forward , Reverse }
Public Member Functions
LinearDocument ()
LinearDocument (const Direction &direction)
void indent (void)
void unindent (void)
void append (void)
void append (const std::string &line)
template<typename Derived >
std::enable_if< std::is_base_of< MultiLineText, Derived >::value >::type append (const Derived &txt)
template<typename... Args>
void append (const Args &... args)
void append (const LinearDocument &doc)
uint32_t lines (void) const override
const std::string & line (uint32_t n) const override
Public Member Functions inherited from pp::MultiLineText
virtual ~MultiLineText ()=default
virtual uint32_t lines (void) const =0
virtual const std::string & line (uint32_t n) const =0
Detailed Description
Definition at line 32 of file LinearDocument.h.
Member Enumeration Documentation
Direction
enum class pp::LinearDocument::Direction strong
Enumerator
Forward
Reverse
Definition at line 35 of file LinearDocument.h.
  {
    Forward,
    Reverse
  };
Constructor & Destructor Documentation
LinearDocument() [1/2]
pp::LinearDocument::LinearDocument () inline
Definition at line 42 of file LinearDocument.h.
                   : _direction{Direction::Forward}
  {
    // DO NOTHING
  }
LinearDocument() [2/2]
pp::LinearDocument::LinearDocument (const Direction & direction) inline
Definition at line 48 of file LinearDocument.h.
                                             : _direction{direction}
  {
    // DO NOTHING
  }
Member Function Documentation
append() [1/5]
template<typename... Args> void pp::LinearDocument::append (const Args &... args) inline
Definition at line 73 of file LinearDocument.h.
{ append(fmt(args...)); }
References append().
Referenced by append().
append() [2/5]
template<typename Derived > std::enable_if< std::is_base_of< MultiLineText, Derived >::value >::type pp::LinearDocument::append (const Derived & txt) inline
Definition at line 65 of file LinearDocument.h.
  {
    for (uint32_t n = 0; n < txt.lines(); ++n)
    {
      append(txt.line(n));
    }
  }
References append().
append() [3/5]
void pp::LinearDocument::append (const LinearDocument & doc)
Definition at line 45 of file LinearDocument.cpp.
{
  for (uint32_t n = 0; n < doc.lines(); ++n)
  {
    // NOTE Do NOT update _lines here and use append method
    append(doc.line(n));
  }
}
References append(), line(), and lines().
append() [4/5]
void pp::LinearDocument::append (const std::string & line)
Definition at line 33 of file LinearDocument.cpp.
{
  if (line.empty())
  {
    append();
    return;
  }
  // Append indentation space(s), and insert the update string to lines
  _lines.emplace_back(_indent.build(line));
}
References append(), pp::IndentedStringBuilder::build(), and line().
append() [5/5]
void pp::LinearDocument::append (void)
Definition at line 27 of file LinearDocument.cpp.
{
  // NOTE Do NOT indent empty lines
  _lines.emplace_back("");
}
Referenced by append(), DEBUGGING_API_P(), and enco::CppCode::dump().
indent()
void pp::LinearDocument::indent (void)
Definition at line 24 of file LinearDocument.cpp.
{ _indent.increase(); }
References pp::IndentedStringBuilder::increase().
Referenced by enco::CppCode::dump().
line()
const std::string & pp::LinearDocument::line (uint32_t n) const override virtual
Implements pp::MultiLineText.
Definition at line 54 of file LinearDocument.cpp.
{
  switch (_direction)
  {
    case Direction::Forward:
    {
      return _lines.at(n);
    }
    case Direction::Reverse:
    {
      return _lines.at(lines() - n - 1);
    }
    default:
      throw std::runtime_error{"Not supported Direction"};
  }
}
References Forward, lines(), and Reverse.
Referenced by append(), and pp::EnclosedDocument::line().
lines()
uint32_t pp::LinearDocument::lines (void) const inline override virtual
Implements pp::MultiLineText.
Definition at line 79 of file LinearDocument.h.
{ return _lines.size(); }
Referenced by append(), pp::EnclosedDocument::line(), line(), and pp::EnclosedDocument::lines().
unindent()
void pp::LinearDocument::unindent (void)
Definition at line 25 of file LinearDocument.cpp.
{ _indent.decrease(); }
References pp::IndentedStringBuilder::decrease().
Referenced by enco::CppCode::dump().
The documentation for this class was generated from the following files:
compiler/pp/include/pp/LinearDocument.h
compiler/pp/src/LinearDocument.cpp