ONE - On-device Neural Engine: nnc::ModelAnalyzer Class Reference
nnc::ModelAnalyzer Class Reference
Constructs inference sequence for given computational graph, gathers list of variables used in artifact.
#include <ModelAnalyzer.h>
Public Member Functions
void analyze (const mir::Graph *g)
contructs inference sequence
void visit (mir::ops::AbsOp &) override
void visit (mir::ops::AddOp &op) override
void visit (mir::ops::AvgPool2DOp &op) override
void visit (mir::ops::BroadcastOp &op) override
void visit (mir::ops::CappedReluOp &op) override
void visit (mir::ops::ConcatOp &op) override
void visit (mir::ops::ConstantOp &op) override
void visit (mir::ops::Conv2DOp &op) override
void visit (mir::ops::DeConv2DOp &op) override
void visit (mir::ops::DepthwiseConv2DOp &op) override
void visit (mir::ops::DivOp &op) override
void visit (mir::ops::EluOp &op) override
void visit (mir::ops::FullyConnectedOp &op) override
void visit (mir::ops::GatherOp &op) override
void visit (mir::ops::InputOp &op) override
void visit (mir::ops::LeakyReluOp &op) override
void visit (mir::ops::MaxOp &op) override
void visit (mir::ops::MaxPool2DOp &op) override
void visit (mir::ops::MulOp &op) override
void visit (mir::ops::OutputOp &op) override
void visit (mir::ops::PadOp &op) override
void visit (mir::ops::ReduceMeanOp &op) override
void visit (mir::ops::ReluOp &op) override
void visit (mir::ops::ReshapeOp &op) override
void visit (mir::ops::ResizeOp &op) override
void visit (mir::ops::SigmoidOp &op) override
void visit (mir::ops::SliceOp &op) override
void visit (mir::ops::SoftmaxOp &op) override
void visit (mir::ops::SqrtOp &op) override
void visit (mir::ops::SqueezeOp &op) override
void visit (mir::ops::SubOp &op) override
void visit (mir::ops::TanhOp &op) override
void visit (mir::ops::TransposeOp &op) override
const std::vector< size_t > & getInputs () const
const std::vector< size_t > & getPersistentTensors () const
const std::vector< size_t > & getOutputs () const
const std::vector< sir::TensorDescriptor > & getTensors () const
const std::vector< std::unique_ptr< sir::Action > > & getInferenceSequence () const
std::vector< std::unique_ptr< sir::Action > > & getInferenceSequence ()
const std::string & getModelName () const
size_t getMaxTemporarySize () const
size_t getTempTID () const
Public Member Functions inherited from mir::IVisitor
virtual ~IVisitor ()=default
Protected Member Functions
void visit_fallback (mir::Operation &op) override
virtual void visit_fallback (Operation &)
Detailed Description
Constructs inference sequence for given computational graph, gathers list of variables used in artifact.
Definition at line 41 of file ModelAnalyzer.h.
Member Function Documentation
analyze()
void nnc::ModelAnalyzer::analyze (const mir::Graph * g)
contructs inference sequence
Parameters
g pointer to graph to linearize
Definition at line 231 of file ModelAnalyzer.cpp.
{
  // Current path through graph
  stack<pair<Operation *, size_t>> s;
  // Nodes in Reverse Post Order stored by DFS
  vector<Operation *> post_order;
  // Set contains pointer to node if it is visited by DFS
  set<Operation *> visited;
  vector<Operation *> init_ops;
  for (Operation *op : g->getNodes())
  {
    if (op->getNumInputs() == 0)
    {
      init_ops.emplace_back(op);
    }
  }
  // Register temporary tensor for im2col buffer
  _temp_tensor_id = declareTemporaryTensor();
  // Walk all network inputs
  for (Operation *in : init_ops)
  {
    if (!visited.count(in))
    {
      visited.insert(in);
      s.push({in, 0});
    }
    // main DFS loop
    while (!s.empty())
    {
      // top stores current node and current outgoing edge from it
      auto &top = s.top();
      Operation *node = top.first;
      auto edge = top.second++;
      // FIXME Refactor me.
      std::vector<Operation *> next_nodes;
      for (const auto &out : node->getOutputs())
      {
        const auto &uses = out.getUses();
        std::transform(uses.begin(), uses.end(), std::back_inserter(next_nodes),
                       [](Operation::Use use) { return use.getNode(); });
      }
      if (edge == next_nodes.size())
      {
        // this node is fully analyzed, push it into RPO and pop from stack
        post_order.push_back(node);
        s.pop();
      }
      else
      {
        // Search current outgoing edge
        Operation *successor = next_nodes[edge];
        if (!visited.count(successor))
        {
          visited.insert(successor);
          s.push({next_nodes[edge], 0});
        }
      }
    }
  }
  constructInferenceSequence(post_order);
  collectOutputs(g);
}
References mir::Operation::getOutputs().
Referenced by nnc::CPPCodeGenerator::run(), and TEST().
getInferenceSequence() [1/2]
std::vector< std::unique_ptr< sir::Action > > & nnc::ModelAnalyzer::getInferenceSequence () inline
Returns
Inference sequence
Definition at line 115 of file ModelAnalyzer.h.
{ return _inferenceSequence; }
getInferenceSequence() [2/2]
const std::vector< std::unique_ptr< sir::Action > > & nnc::ModelAnalyzer::getInferenceSequence () const inline
Returns
Inference sequence
Definition at line 107 of file ModelAnalyzer.h.
  {
    return _inferenceSequence;
  }
Referenced by nnc::CPPCodeGenerator::run(), and TEST().
getInputs()
const std::vector< size_t > & nnc::ModelAnalyzer::getInputs () const inline
Returns
vector of id's of network input tensors
Definition at line 87 of file ModelAnalyzer.h.
{ return _inputs; }
getMaxTemporarySize()
size_t nnc::ModelAnalyzer::getMaxTemporarySize () const inline
Definition at line 122 of file ModelAnalyzer.h.
{ return _max_temp_size; }
getModelName()
const std::string & nnc::ModelAnalyzer::getModelName () const inline
Returns
Model name, taken from Model IR
Definition at line 120 of file ModelAnalyzer.h.
{ return _modelName; }
getOutputs()
const std::vector< size_t > & nnc::ModelAnalyzer::getOutputs () const inline
Returns
vector of id's of network output tensors
Definition at line 97 of file ModelAnalyzer.h.
{ return _outputs; }
getPersistentTensors()
const std::vector< size_t > & nnc::ModelAnalyzer::getPersistentTensors () const inline
Returns
vector of id's of tensors with unique names taken from Model IR
Definition at line 92 of file ModelAnalyzer.h.
{ return _persistent_tensors; }
getTempTID()
size_t nnc::ModelAnalyzer::getTempTID () const inline
Definition at line 124 of file ModelAnalyzer.h.
{ return _temp_tensor_id; }
getTensors()
const std::vector< sir::TensorDescriptor > & nnc::ModelAnalyzer::getTensors () const inline
Returns
vector of all network tensors
Definition at line 102 of file ModelAnalyzer.h.
{ return _tensors; }
visit() [1/33]
void nnc::ModelAnalyzer::visit (mir::ops::AbsOp & op) override
Definition at line 423 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "absFN"); }
visit() [2/33]
void nnc::ModelAnalyzer::visit (mir::ops::AddOp & op) override
Definition at line 425 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "ElementWise<Add>");
}
visit() [3/33]
void nnc::ModelAnalyzer::visit (mir::ops::AvgPool2DOp & op) override
Definition at line 320 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "avgPool"); }
visit() [4/33]
void nnc::ModelAnalyzer::visit (mir::ops::BroadcastOp & op) override
Definition at line 329 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "broadcast"); }
visit() [5/33]
void nnc::ModelAnalyzer::visit (mir::ops::CappedReluOp & op) override
Definition at line 331 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "cappedRelu"); }
visit() [6/33]
void nnc::ModelAnalyzer::visit (mir::ops::ConcatOp & op) override
Definition at line 300 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "concat"); }
visit() [7/33]
void nnc::ModelAnalyzer::visit (mir::ops::ConstantOp & op) override
Definition at line 339 of file ModelAnalyzer.cpp.
{
  assert(op.getNumInputs() == 0);
  // FIXME This is to work around deserializeTensors not being able to deserialize tensors of type
  // other than float32.
  const auto *output = op.getOutput(0);
  if (output->getUses().empty())
    return;
  appendOperationToInference(&op, "constant");
}
References mir::Operation::getNumInputs(), and mir::Operation::getOutput().
visit() [8/33]
void nnc::ModelAnalyzer::visit (mir::ops::Conv2DOp & op) override
Definition at line 302 of file ModelAnalyzer.cpp.
{
  assert(op.getNumGroups() == 1);
  const auto &kernel_shape = op.getInputShape(1);
  const auto &out_shape = op.getOutputShape(0);
  const int32_t tmp_size = kernel_shape.dim(1) * kernel_shape.dim(2) * kernel_shape.dim(3) *
                           out_shape.dim(0) * out_shape.dim(1) * out_shape.dim(2);
  updateMaxTemporarySize(static_cast<size_t>(tmp_size));
  appendOperationToInference(&op, "conv2d", {_temp_tensor_id});
}
References mir::Shape::dim(), mir::Operation::getInputShape(), mir::ops::Conv2DOp::getNumGroups(), and mir::Operation::getOutputShape().
visit() [9/33]
void nnc::ModelAnalyzer::visit (mir::ops::DeConv2DOp & op) override
Definition at line 386 of file ModelAnalyzer.cpp.
{
  const auto &kernel_shape = op.getInputShape(1);
  const auto &out_shape = op.getOutputShape(0);
  const int32_t tmp_size = kernel_shape.dim(0) * kernel_shape.dim(1) * kernel_shape.dim(3) *
                           out_shape.dim(0) * out_shape.dim(1) * out_shape.dim(2);
  updateMaxTemporarySize(static_cast<size_t>(tmp_size));
  appendOperationToInference(&op, "convTransposed2d", {_temp_tensor_id});
}
References mir::Shape::dim(), mir::Operation::getInputShape(), and mir::Operation::getOutputShape().
visit() [10/33]
void nnc::ModelAnalyzer::visit (mir::ops::DepthwiseConv2DOp & op) override
Definition at line 313 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "depthwiseConv2d");
}
visit() [11/33]
void nnc::ModelAnalyzer::visit (mir::ops::DivOp & op) override
Definition at line 430 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "ElementWise<Div>");
}
visit() [12/33]
void nnc::ModelAnalyzer::visit (mir::ops::EluOp & op) override
Definition at line 384 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "elu"); }
visit() [13/33]
void nnc::ModelAnalyzer::visit (mir::ops::FullyConnectedOp & op) override
Definition at line 324 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "fullConnect");
}
visit() [14/33]
void nnc::ModelAnalyzer::visit (mir::ops::GatherOp & op) override
Definition at line 412 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "gather"); }
visit() [15/33]
void nnc::ModelAnalyzer::visit (mir::ops::InputOp & op) override
Definition at line 333 of file ModelAnalyzer.cpp.
{
  assert(op.getNumInputs() == 0);
  appendOperationToInference(&op, "in");
}
References mir::Operation::getNumInputs().
visit() [16/33]
void nnc::ModelAnalyzer::visit (mir::ops::LeakyReluOp & op) override
Definition at line 416 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "leakyRelu");
}
visit() [17/33]
void nnc::ModelAnalyzer::visit (mir::ops::MaxOp & op) override
Definition at line 435 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "ElementWise<Max>");
}
visit() [18/33]
void nnc::ModelAnalyzer::visit (mir::ops::MaxPool2DOp & op) override
Definition at line 322 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "maxPool"); }
visit() [19/33]
void nnc::ModelAnalyzer::visit (mir::ops::MulOp & op) override
Definition at line 440 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "ElementWise<Mul>");
}
visit() [20/33]
void nnc::ModelAnalyzer::visit (mir::ops::OutputOp & op) override
Definition at line 421 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "out"); }
visit() [21/33]
void nnc::ModelAnalyzer::visit (mir::ops::PadOp & op) override
Definition at line 400 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "pad"); }
visit() [22/33]
void nnc::ModelAnalyzer::visit (mir::ops::ReduceMeanOp & op) override
Definition at line 402 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "reduceMean");
}
visit() [23/33]
void nnc::ModelAnalyzer::visit (mir::ops::ReluOp & op) override
Definition at line 352 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "relu"); }
visit() [24/33]
void nnc::ModelAnalyzer::visit (mir::ops::ReshapeOp & op) override
Definition at line 354 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "reshape"); }
visit() [25/33]
void nnc::ModelAnalyzer::visit (mir::ops::ResizeOp & op) override
Definition at line 356 of file ModelAnalyzer.cpp.
{
  const auto &in_shape = op.getInputShape(0);
  const auto &out_shape = op.getOutputShape(0);
  assert(in_shape.rank() == 4);
  assert(in_shape.rank() == out_shape.rank());
  if (in_shape.dim(0) != out_shape.dim(0) || in_shape.dim(3) != out_shape.dim(3))
    throw std::runtime_error("Not supported Resize on other dims besides height and width!");
  switch (op.getMode())
  {
    case mir::ops::ResizeOp::ResizeMethod::nearestNeighbor:
      appendOperationToInference(&op, "resize");
      break;
    default:
      assert(false && "Not Implemented!");
  }
}
References mir::Operation::getInputShape(), mir::ops::ResizeOp::getMode(), mir::Operation::getOutputShape(), and mir::ops::ResizeOp::nearestNeighbor.
visit() [26/33]
void nnc::ModelAnalyzer::visit (mir::ops::SigmoidOp & op) override
Definition at line 414 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "sigmoid"); }
visit() [27/33]
void nnc::ModelAnalyzer::visit (mir::ops::SliceOp & op) override
Definition at line 377 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "slice"); }
visit() [28/33]
void nnc::ModelAnalyzer::visit (mir::ops::SoftmaxOp & op) override
Definition at line 318 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "softmax"); }
visit() [29/33]
void nnc::ModelAnalyzer::visit (mir::ops::SqrtOp & op) override
Definition at line 398 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "sqrtFN"); }
visit() [30/33]
void nnc::ModelAnalyzer::visit (mir::ops::SqueezeOp & op) override
Definition at line 396 of file ModelAnalyzer.cpp.
{ appendOperationToInference(&op, "reshape"); }
visit() [31/33]
void nnc::ModelAnalyzer::visit (mir::ops::SubOp & op) override
Definition at line 445 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "ElementWise<Sub>");
}
visit() [32/33]
void nnc::ModelAnalyzer::visit (mir::ops::TanhOp & op) override
Definition at line 379 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "tanhActivation");
}
visit() [33/33]
void nnc::ModelAnalyzer::visit (mir::ops::TransposeOp & op) override
Definition at line 407 of file ModelAnalyzer.cpp.
{
  appendOperationToInference(&op, "transpose");
}
visit_fallback()
void nnc::ModelAnalyzer::visit_fallback (mir::Operation & op) override protected virtual
Reimplemented from mir::Visitor.
Definition at line 450 of file ModelAnalyzer.cpp.
{ throw std::runtime_error("NYI operation"); }
The documentation for this class was generated from the following files:
compiler/nnc/backends/soft_backend/ModelAnalyzer.h
compiler/nnc/backends/soft_backend/ModelAnalyzer.cpp