ONE - On-device Neural Engine: mir::ShapeIter Class Reference
mir::ShapeIter Class Reference
#include <ShapeRange.h>
Public Member Functions
ShapeIter & operator++ ()
const ShapeIter operator++ (int)
const Index & operator* () const
bool operator!= (const ShapeIter &iter) const
Friends
class ShapeRange
Detailed Description
Definition at line 28 of file ShapeRange.h.
Member Function Documentation
operator!=()
bool mir::ShapeIter::operator!= (const ShapeIter & iter) const inline
Definition at line 60 of file ShapeRange.h.
  {
    assert(iter._index.rank() == _index.rank());
    assert(iter._shape == _shape);
    return _pos != iter._pos;
  }
References mir::Index::rank().
operator*()
const Index & mir::ShapeIter::operator* () const inline
Definition at line 58 of file ShapeRange.h.
{ return _index; }
operator++() [1/2]
ShapeIter & mir::ShapeIter::operator++ () inline
Definition at line 32 of file ShapeRange.h.
  {
    if (_shape.rank() > 0)
    {
      auto *pidx = &_index.at(0);
      auto *pshape = &_shape.dim(0);
      int32_t rank = _shape.rank();
      int32_t c = rank - 1;
      pidx[c]++;
      while (pidx[c] >= pshape[c] && c > 0)
      {
        pidx[c] = 0;
        pidx[--c]++;
      }
    }
    _pos++;
    return *this;
  }
References mir::Index::at(), mir::Shape::dim(), and mir::Shape::rank().
operator++() [2/2]
const ShapeIter mir::ShapeIter::operator++ (int) inline
Definition at line 51 of file ShapeRange.h.
  {
    ShapeIter it = *this;
    ++*this;
    return it;
  }
Friends And Related Function Documentation
ShapeRange
friend class ShapeRange friend
Definition at line 78 of file ShapeRange.h.
The documentation for this class was generated from the following file:
compiler/mir/include/mir/ShapeRange.h