ONE - On-device Neural Engine: crew::JsonExport Class Reference
crew::JsonExport Class Reference
#include <PConfigJson.h>
Public Member Functions
JsonExport (std::ostream &os)
void open_brace (void)
void open_brace (const std::string &key)
void open_bracket (const std::string &key)
void close_bracket (bool cont)
void close_brace (bool cont)
void key_val (const std::string &key, const std::string &value, bool cont)
void key_val (const std::string &key, const std::vector< std::string > &l, bool cont)
Detailed Description
Definition at line 27 of file PConfigJson.h.
Constructor & Destructor Documentation
JsonExport()
crew::JsonExport::JsonExport (std::ostream & os) inline
Definition at line 30 of file PConfigJson.h.
: _os(os) {}
Member Function Documentation
close_brace()
void crew::JsonExport::close_brace (bool cont)
Definition at line 75 of file PConfigJson.cpp.
{
  _indent--;
  indent();
  _os << "}";
  if (cont)
    _os << ",";
  _os << _CLF;
}
Referenced by crew::write_json().
close_bracket()
void crew::JsonExport::close_bracket (bool cont)
Definition at line 64 of file PConfigJson.cpp.
{
  _indent--;
  indent();
  _os << "]";
  if (cont)
    _os << ",";
  _os << _CLF;
}
Referenced by crew::write_json().
key_val() [1/2]
void crew::JsonExport::key_val (const std::string & key, const std::string & value, bool cont)
Definition at line 86 of file PConfigJson.cpp.
{
  indent();
  _os << _DQU << key << _DQU << " : " << _DQU << value << _DQU;
  if (cont)
    _os << ",";
  _os << _CLF;
}
key_val() [2/2]
void crew::JsonExport::key_val (const std::string & key, const std::vector< std::string > & l, bool cont)
Definition at line 96 of file PConfigJson.cpp.
{
  indent();
  _os << _DQU << key << _DQU << " : [ ";
  bool comma = false;
  for (auto &v : l)
  {
    if (comma)
      _os << ", ";
    else
      comma = true;
    _os << _DQU << v << _DQU;
  }
  _os << " ]";
  if (cont)
    _os << ",";
  _os << _CLF;
}
open_brace() [1/2]
void crew::JsonExport::open_brace (const std::string & key)
Definition at line 48 of file PConfigJson.cpp.
{
  indent();
  _os << _DQU << key << _DQU << " : {" << _CLF;
  _indent++;
}
open_brace() [2/2]
void crew::JsonExport::open_brace (void)
Definition at line 40 of file PConfigJson.cpp.
{
  indent();
  _os << "{" << _CLF;
  _indent++;
}
Referenced by crew::write_json().
open_bracket()
void crew::JsonExport::open_bracket (const std::string & key)
Definition at line 56 of file PConfigJson.cpp.
{
  indent();
  _os << _DQU << key << _DQU << " : [" << _CLF;
  _indent++;
}
Referenced by crew::write_json().
The documentation for this class was generated from the following files:
compiler/crew/src/PConfigJson.h
compiler/crew/src/PConfigJson.cpp