ONE - On-device Neural Engine: onert::backend::trix::KernelGenerator Class Reference
onert::backend::trix::KernelGenerator Class Reference
#include <KernelGenerator.h>
Public Member Functions
KernelGenerator (const ir::Graph &graph, const std::shared_ptr< TensorBuilder > &tensor_builder, const std::shared_ptr< basic::TensorRegistry > &tensor_reg, const std::shared_ptr< DevContext > &dev_context)
std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex op_ind) override
Public Member Functions inherited from onert::backend::basic::KernelGeneratorBase
virtual ~KernelGeneratorBase ()=default
KernelGeneratorBase (const ir::Graph &graph)
virtual std::unique_ptr< exec::FunctionSequence > generate (ir::OperationIndex ind)=0
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Protected Member Functions inherited from onert::backend::basic::KernelGeneratorBase
std::unique_ptr< exec::IFunction > releaseFunction ()
Protected Attributes inherited from onert::backend::basic::KernelGeneratorBase
const ir::Graph & _graph
std::unique_ptr< exec::IFunction > _return_fn
Detailed Description
Definition at line 36 of file KernelGenerator.h.
Constructor & Destructor Documentation
KernelGenerator()
onert::backend::trix::KernelGenerator::KernelGenerator (const ir::Graph & graph, const std::shared_ptr< TensorBuilder > & tensor_builder, const std::shared_ptr< basic::TensorRegistry > & tensor_reg, const std::shared_ptr< DevContext > & dev_context)
Definition at line 37 of file KernelGenerator.cc.
  : basic::KernelGeneratorBase{graph},
    _ctx(graph.operands()), _operations_ctx{graph.operations()}, _current_layout{graph.layout()},
    _tensor_builder(tensor_builder), _tensor_reg{tensor_reg}, _dev_context{dev_context}
{
  // DO NOTHING
}
Member Function Documentation
generate()
std::unique_ptr< exec::FunctionSequence > onert::backend::trix::KernelGenerator::generate (ir::OperationIndex op_ind) override virtual
Implements onert::backend::basic::KernelGeneratorBase.
Definition at line 48 of file KernelGenerator.cc.
{
  auto ret = std::make_unique<exec::FunctionSequence>();
  ret->enableDynamicShapeInferer(false);
  const auto &op = _graph.operations().at(ind);
  op.accept(*this);
  ret->append(releaseFunction());
  return ret;
}
References onert::backend::basic::KernelGeneratorBase::_graph, onert::util::ObjectManager< Index, Object >::at(), onert::ir::Graph::operations(), and onert::backend::basic::KernelGeneratorBase::releaseFunction().
The documentation for this class was generated from the following files:
runtime/onert/backend/trix/KernelGenerator.h
runtime/onert/backend/trix/KernelGenerator.cc