ONE - On-device Neural Engine: exo::TransposedConv2DConverter Class Reference
exo::TransposedConv2DConverter Class Reference
Convert loco::TransposedConv2D to locoex::TFLTransposeConv and auxiliary.
#include <TransposedConv2DConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::TransposedConv2D *origin) final
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::TransposedConv2D >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::TransposedConv2D *node)=0
Detailed Description
Convert loco::TransposedConv2D to locoex::TFLTransposeConv and auxiliary.
<BEFORE>
IFM ----— TransposedConv2D — OFM (Feature) / (Feature) / KER ---— (Filter)
<AFTER>
out_backprop : IFM ----— FeatureDecode — TFLTransposeConv — FeatureEncode — OFM [Feature] [Tensor] / / [Tensor] [Feature] / / filter: KER ----— FilterDecode — / [Filter] [Tensor] / / input_sizes : TFLConst (new) ---------— [Tensor]
Definition at line 51 of file TransposedConv2DConverter.h.
Member Function Documentation
convert()
bool exo::TransposedConv2DConverter::convert (loco::TransposedConv2D * origin) final virtual
Implements exo::CanonicalNodeConverter< loco::TransposedConv2D >.
Definition at line 29 of file TransposedConv2DConverter.cpp.
{
  // Shape is required to set origin->inputSizes()
  if (not loco::shape_known(origin))
    return false;
  if ((origin->ifm() == nullptr) or (origin->ker() == nullptr))
    return false;
  auto *graph = origin->graph();
  auto tfl_tr_conv = graph->nodes()->create<locoex::TFLTransposeConv>();
  {
    tfl_tr_conv->stride()->w(origin->stride()->horizontal());
    tfl_tr_conv->stride()->h(origin->stride()->vertical());
    auto pad = origin->pad();
    if (pad->bottom() == 0 && pad->top() == 0 && pad->left() == 0 && pad->right() == 0)
      tfl_tr_conv->padding(locoex::Padding::VALID);
    else
      // TODO This is necessary, but not sufficient condition. More rigorous check required
      tfl_tr_conv->padding(locoex::Padding::SAME);
  }
  // let's create a new graph connection with tfl_tr_conv
  {
    // Make inputSizes from shape of origin
    auto input_sizes_const = graph->nodes()->create<locoex::TFLConst>();
    auto origin_shape = loco::shape_get(origin).as<loco::FeatureShape>();
    const loco::DataType S32 = loco::DataType::S32;
    input_sizes_const->dtype(S32);
    input_sizes_const->rank(1);
    input_sizes_const->dim(0) = 4;
    input_sizes_const->size<S32>(4);
    // Note that NHWC is layout for inputSizes determined by tflite format
    input_sizes_const->at<S32>(0) = origin_shape.count().value();  // N
    input_sizes_const->at<S32>(1) = origin_shape.height().value(); // H
    input_sizes_const->at<S32>(2) = origin_shape.width().value();  // W
    input_sizes_const->at<S32>(3) = origin_shape.depth().value();  // C
    tfl_tr_conv->inputSizes(input_sizes_const);
    // filter
    auto filter_dec = make_filter_decode<FilterLayout::OHWI>(origin->ker());
    tfl_tr_conv->filter(filter_dec);
    // outBackprop
    auto feature_dec = make_feature_decode<FeatureLayout::NHWC>(origin->ifm());
    tfl_tr_conv->outBackprop(feature_dec);
    // output
    auto feature_enc = make_feature_encode<FeatureLayout::NHWC>(tfl_tr_conv);
    // replace canonical node
    loco::replace(origin).with(feature_enc);
    origin->ifm(nullptr);
  }
  return true;
}
References loco::NodeShape::as(), locoex::TFLConst::at(), loco::Node::graph(), loco::Stride< 2 >::horizontal(), loco::TransposedConv2D::ifm(), loco::TransposedConv2D::ker(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), exo::make_filter_decode< FilterLayout::OHWI >(), loco::TransposedConv2D::pad(), loco::replace(), locoex::SAME, loco::shape_get(), loco::shape_known(), locoex::TFLTransposeConv::stride(), loco::TransposedConv2D::stride(), locoex::VALID, loco::Stride< 2 >::vertical(), locoex::Stride::w(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::TransposedConv2DConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::TransposedConv2D >.
Definition at line 54 of file TransposedConv2DConverter.h.
{ return "exo::TransposedConv2DConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/TransposedConv2DConverter.h
compiler/exo/src/Conversion/TransposedConv2DConverter.cpp