ONE - On-device Neural Engine: luci::CircleCastGraphBuilder Class Reference
luci::CircleCastGraphBuilder Class Reference
#include <CircleCast.h>
Public Member Functions
bool validate (const ValidateArgs &args) const final
Public Member Functions inherited from luci::GraphBuilder
virtual ~GraphBuilder ()=default
bool validate (const ValidateArgs &args, size_t input_cnt) const
CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const final
Public Member Functions inherited from luci::GraphBuilderBase
virtual bool validate (const ValidateArgs &) const =0
virtual CircleNode * build (const circle::OperatorT &op, GraphBuilderContext *context) const =0
virtual ~GraphBuilderBase ()=default
Detailed Description
Definition at line 25 of file CircleCast.h.
Member Function Documentation
validate()
bool luci::CircleCastGraphBuilder::validate (const ValidateArgs & args) const final virtual
Implements luci::GraphBuilderBase.
Definition at line 29 of file CircleCast.cpp.
{
  LOGGER(l);
  if (!GraphBuilder::validate(args, 1))
    return false;
  auto settings = luci::UserSettings::settings();
  const auto &inputs = args.op.inputs;
  const auto &outputs = args.op.outputs;
  // NOTE real models do have type mismatch
  const auto *options = args.op.builtin_options.AsCastOptions();
  if (options != nullptr)
  {
    const auto tensors = args.reader.tensors();
    const auto output_tensor = tensors[outputs[0]];
    assert(output_tensor != nullptr);
    auto name = tensor_name(output_tensor);
    const auto tensor_in = tensors.at(inputs.at(0));
    assert(tensor_in != nullptr);
    if (tensor_in->type() != options->in_data_type)
    {
      if (settings->get(luci::UserSettings::Key::DisableValidation))
      {
        WARN(l) << "Warning: import Cast(" << name << ") dtype mismatch";
      }
      else
        return false;
    }
    const auto &tensor_out = tensors.at(outputs[0]);
    if (tensor_out->type() != options->out_data_type)
    {
      if (settings->get(luci::UserSettings::Key::DisableValidation))
      {
        WARN(l) << "Warning: import Cast(" << name << ") dtype mismatch";
      }
      else
        return false;
    }
  }
  return true;
}
References luci::UserSettings::DisableValidation, LOGGER, luci::UserSettings::settings(), luci::tensor_name(), luci::GraphBuilder::validate(), and WARN.
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Import/Nodes/CircleCast.h
compiler/luci/import/src/Nodes/CircleCast.cpp