ONE - On-device Neural Engine: onert::backend::cpu::ops::ArgMinMaxLayer Class Reference
onert::backend::cpu::ops::ArgMinMaxLayer Class Reference
#include <ArgMinMaxLayer.h>
Public Member Functions
ArgMinMaxLayer ()
void configure (const IPortableTensor *indices, IPortableTensor *output, const IPortableTensor *axis, bool is_arg_max)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file ArgMinMaxLayer.h.
Constructor & Destructor Documentation
ArgMinMaxLayer()
onert::backend::cpu::ops::ArgMinMaxLayer::ArgMinMaxLayer () inline
Definition at line 36 of file ArgMinMaxLayer.h.
: _input(nullptr), _output(nullptr), _axis(nullptr), _is_arg_max(true) {}
Member Function Documentation
configure()
void onert::backend::cpu::ops::ArgMinMaxLayer::configure (const IPortableTensor * indices, IPortableTensor * output, const IPortableTensor * axis, bool is_arg_max)
Definition at line 47 of file ArgMinMaxLayer.cc.
{
  _input = input;
  _output = output;
  _axis = axis;
  _is_arg_max = is_arg_max;
}
run()
void onert::backend::cpu::ops::ArgMinMaxLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 56 of file ArgMinMaxLayer.cc.
{
  if (_axis->total_size() != sizeof(int32_t))
  {
    throw std::runtime_error("ArgMinMax: wrong shape of axis");
  }
  auto axis = *getBuffer<int32_t>(_axis);
  if (axis < 0)
  {
    axis += _input->getShape().rank();
  }
#define TF_LITE_ARG_MIN_MAX(input_type, axis_type, output_type)                 \
  ArgMinMax(getShape(_input), getBuffer<input_type>(_input), getShape(_output), \
            getBuffer<output_type>(_output), axis, GetComparefunction<input_type>(_is_arg_max));
  if (_output->data_type() == ir::DataType::INT32)
  {
    switch (_input->data_type())
    {
      case ir::DataType::FLOAT32:
        TF_LITE_ARG_MIN_MAX(float, int32_t, int32_t);
        break;
      case ir::DataType::QUANT_UINT8_ASYMM:
      case ir::DataType::UINT8:
        TF_LITE_ARG_MIN_MAX(uint8_t, int32_t, int32_t);
        break;
      case ir::DataType::QUANT_INT8_ASYMM:
        TF_LITE_ARG_MIN_MAX(uint8_t, int32_t, int32_t);
        break;
      case ir::DataType::INT32:
        TF_LITE_ARG_MIN_MAX(int32_t, int32_t, int32_t);
        break;
      default:
        throw std::runtime_error("ArgMinMax: unsupported data type");
    }
  }
  else if (_output->data_type() == ir::DataType::INT64)
  {
    switch (_input->data_type())
    {
      case ir::DataType::FLOAT32:
        TF_LITE_ARG_MIN_MAX(float, int32_t, int64_t);
        break;
      case ir::DataType::QUANT_UINT8_ASYMM:
      case ir::DataType::UINT8:
        TF_LITE_ARG_MIN_MAX(uint8_t, int32_t, int64_t);
        break;
      case ir::DataType::QUANT_INT8_ASYMM:
        TF_LITE_ARG_MIN_MAX(uint8_t, int32_t, int64_t);
        break;
      case ir::DataType::INT32:
        TF_LITE_ARG_MIN_MAX(int32_t, int32_t, int64_t);
        break;
      default:
        throw std::runtime_error("ArgMinMax: unsupported data type");
    }
  }
  else
  {
    throw std::runtime_error("ArgMinMax: unsupported data type");
  }
#undef TF_LITE_ARG_MIN_MAX
}
References onert::backend::ITensor::data_type(), onert::backend::ITensor::getShape(), TF_LITE_ARG_MIN_MAX, and onert::backend::ITensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/ArgMinMaxLayer.h
runtime/onert/backend/cpu/ops/ArgMinMaxLayer.cc