ONE - On-device Neural Engine: onert::odc::Quantizer Class Reference
onert::odc::Quantizer Class Reference
#include <Quantizer.h>
Public Member Functions
Quantizer ()=default
~Quantizer ()=default
int quantize (const char *in, const char *out, QuantizeType qtype) override
void setMinMaxRecordsThreshold (uint32_t value) override
Set the number of minmax records enough for quantization.
bool readyForQuantize () override
Checking the number of minmax records enough for quantization (comparison with threshold)
bool deleteMinMaxFile () override
Delete minmax file.
Public Member Functions inherited from onert::odc::IQuantizer
virtual ~IQuantizer ()=default
Detailed Description
Definition at line 25 of file Quantizer.h.
Constructor & Destructor Documentation
Quantizer()
onert::odc::Quantizer::Quantizer () default
~Quantizer()
onert::odc::Quantizer::~Quantizer () default
Member Function Documentation
deleteMinMaxFile()
bool onert::odc::Quantizer::deleteMinMaxFile () override virtual
Delete minmax file.
Returns
True if there were no errors, False otherwise
Implements onert::odc::IQuantizer.
Definition at line 172 of file Quantizer.cc.
{
  int result = 0;
  std::string minmax_path = getMinMaxFilePath();
  result = std::remove(minmax_path.c_str());
  if (!result)
  {
    return true;
  }
  else
    return false;
}
quantize()
int onert::odc::Quantizer::quantize (const char * in, const char * out, QuantizeType qtype) override virtual
Implements onert::odc::IQuantizer.
Definition at line 85 of file Quantizer.cc.
{
  if (not in || not out)
    return 1;
  bool full_quantize = false;
  if (qtype == QuantizeType::ODC_QTYPE_U8_ASYM || qtype == QuantizeType::ODC_QTYPE_I16_SYM)
    full_quantize = true;
  // Load model from the file
  luci::ImporterEx importerex;
  auto module = importerex.importVerifyModule(std::string(in));
  if (module.get() == nullptr)
    return 1;
  // Additional phase for full quantization
  if (full_quantize)
  {
    luci::CircleQuantizer quantizer;
    auto options = quantizer.options();
    fillQuantizeOptionParam(options, qtype);
    // Fake quantization
    options->enable(QuantizerOptions::Algorithm::QuantizeDequantizeWeights);
    for (size_t idx = 0; idx < module->size(); ++idx)
    {
      auto graph = module->graph(idx);
      // quantize the graph
      quantizer.quantize(graph);
    }
    // Record minmax by minmax-embedder
    auto minmax_path = getMinMaxFilePath();
    Embedder().embed(module.get(), minmax_path, {1.f, 99.f});
  }
  luci::CircleQuantizer quantizer;
  auto options = quantizer.options();
  fillQuantizeOptionParam(options, qtype);
  if (full_quantize)
    options->enable(QuantizerOptions::Algorithm::QuantizeWithMinMax);
  else
    options->enable(QuantizerOptions::Algorithm::QuantizeWeights);
  for (size_t idx = 0; idx < module->size(); ++idx)
  {
    auto graph = module->graph(idx);
    // quantize the graph
    quantizer.quantize(graph);
    // Skip validate
    // TODO Validate if needed
#if 0
    if (!luci::validate(graph))
    {
      std::cerr << "ERROR: Quantized graph is invalid" << std::endl;
      return 1;
    }
#endif
  }
  // Export to output Circle file
  luci::CircleExporter exporter;
  luci::CircleFileExpContract contract(module.get(), std::string(out));
  if (!exporter.invoke(&contract))
    return 1;
  return 0;
}
References onert::odc::Embedder::embed(), luci::CircleExporter::invoke(), luci::CircleQuantizer::options(), luci::CircleQuantizer::quantize(), luci::CircleQuantizer::Options::QuantizeDequantizeWeights, luci::CircleQuantizer::Options::QuantizeWeights, luci::CircleQuantizer::Options::QuantizeWithMinMax, and luci::validate().
readyForQuantize()
bool onert::odc::Quantizer::readyForQuantize () override virtual
Checking the number of minmax records enough for quantization (comparison with threshold)
Returns
True if ready, False otherwise
Implements onert::odc::IQuantizer.
Definition at line 159 of file Quantizer.cc.
{
  std::string minmax_path = getMinMaxFilePath();
  MinMaxReader mmr{minmax_path};
  uint32_t numRuns = mmr.readNumRuns();
  if (_minmax_threshold != 0 && numRuns >= _minmax_threshold)
    return true;
  else
    return false;
}
References onert::odc::MinMaxReader::readNumRuns().
setMinMaxRecordsThreshold()
void onert::odc::Quantizer::setMinMaxRecordsThreshold (uint32_t value) inline override virtual
Set the number of minmax records enough for quantization.
Implements onert::odc::IQuantizer.
Definition at line 36 of file Quantizer.h.
{ _minmax_threshold = value; };
The documentation for this class was generated from the following files:
runtime/onert/odc/Quantizer.h
runtime/onert/odc/Quantizer.cc