ONE - On-device Neural Engine: moco::tf::ShapeInferencePass Class Reference
moco::tf::ShapeInferencePass Class Reference
Run shape inference to the graph.
#include <ShapeInferencePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *graph) override
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Run shape inference to the graph.
Definition at line 32 of file ShapeInferencePass.h.
Member Function Documentation
name()
const char * moco::tf::ShapeInferencePass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 35 of file ShapeInferencePass.h.
{ return "ShapeInferencePass"; }
run()
bool moco::tf::ShapeInferencePass::run (loco::Graph * graph) override virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 40 of file ShapeInferencePass.cpp.
{
  loco::CanonicalShapeInferenceRule canonical_rule;
  moco::TFShapeInferenceRule tf_rule;
  locoex::COpShapeInferenceRule cop_rule; // rule for custop op
  loco::MultiDialectShapeInferenceRule rules;
  rules.bind(loco::CanonicalDialect::get(), &canonical_rule)
    .bind(TFDialect::get(), &tf_rule)
    .bind(locoex::COpDialect::get(), &cop_rule);
  return loco::apply(&rules).to(graph);
}
References loco::apply(), loco::MultiDialectShapeInferenceRule::bind(), loco::CanonicalDialect::get(), locoex::COpDialect::get(), moco::TFDialect::get(), and loco::ShapeInferenceSession::to().
The documentation for this class was generated from the following files:
compiler/moco-tf/src/Transforms/ShapeInferencePass.h
compiler/moco-tf/src/Transforms/ShapeInferencePass.cpp