ONE - On-device Neural Engine: onert::backend::acl_cl::operand::ICLTensor Class Reference
onert::backend::acl_cl::operand::ICLTensor Class Reference abstract
#include <ICLTensor.h>
Public Member Functions
ICLTensor (size_t rank)
const arm_compute::ICLTensor * handle () const override=0
arm_compute::ICLTensor * handle () override=0
void access (const std::function< void(ITensor &tensor)> &fn) final
bool needMemoryMap () const final
void enqueueWriteBuffer (const void *ptr, bool blocking=true) final
void enqueueReadBuffer (void *ptr, bool blocking=true) final
Public Member Functions inherited from onert::backend::acl_common::IACLTensor
IACLTensor ()=default
IACLTensor (const IACLTensor &)=delete
IACLTensor & operator= (const IACLTensor &)=delete
IACLTensor (IACLTensor &&)=default
IACLTensor & operator= (IACLTensor &&)=default
IACLTensor (size_t rank)
uint8_t * buffer () const final
size_t total_size () const final
size_t calcOffset (const ir::Coordinates &coords) const final
ir::Layout layout () const final
ir::DataType data_type () const final
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
ir::Shape getShape () const override
Get ir::Shape of tensor.
virtual const arm_compute::ITensor * handle () const =0
virtual arm_compute::ITensor * handle ()=0
const arm_compute::ITensorInfo * info () const
arm_compute::ITensorInfo * info ()
size_t dimension (size_t index) const
size_t num_dimensions () const
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::acl_common::IACLTensor
size_t _rank
Detailed Description
Definition at line 33 of file ICLTensor.h.
Constructor & Destructor Documentation
ICLTensor()
onert::backend::acl_cl::operand::ICLTensor::ICLTensor (size_t rank) inline
Definition at line 36 of file ICLTensor.h.
: IACLTensor{rank} {}
Member Function Documentation
access()
void onert::backend::acl_cl::operand::ICLTensor::access (const std::function< void(ITensor &tensor)> & fn) final virtual
Implements onert::backend::ITensor.
Definition at line 31 of file ICLTensor.cc.
{
  auto &queue = ::arm_compute::CLScheduler::get().queue();
  // This is an optional input
  if (total_size() == 0)
    return;
  map(queue);
  fn(*this);
  unmap(queue);
}
References onert::backend::acl_common::IACLTensor::total_size().
enqueueReadBuffer()
void onert::backend::acl_cl::operand::ICLTensor::enqueueReadBuffer (void * ptr, bool blocking = true) final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 51 of file ICLTensor.cc.
{
  auto &queue = ::arm_compute::CLScheduler::get().queue();
  queue.enqueueReadBuffer(handle()->cl_buffer(), blocking ? CL_TRUE : CL_FALSE, 0,
                          info()->total_size(), ptr);
}
References handle(), onert::backend::acl_common::IACLTensor::info(), and onert::backend::acl_common::IACLTensor::total_size().
enqueueWriteBuffer()
void onert::backend::acl_cl::operand::ICLTensor::enqueueWriteBuffer (const void * ptr, bool blocking = true) final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 44 of file ICLTensor.cc.
{
  auto &queue = ::arm_compute::CLScheduler::get().queue();
  queue.enqueueWriteBuffer(handle()->cl_buffer(), blocking ? CL_TRUE : CL_FALSE, 0,
                           info()->total_size(), ptr);
}
References handle(), onert::backend::acl_common::IACLTensor::info(), and onert::backend::acl_common::IACLTensor::total_size().
handle() [1/2]
const arm_compute::ICLTensor * onert::backend::acl_cl::operand::ICLTensor::handle () const override pure virtual
Implements onert::backend::acl_common::IACLTensor.
Implemented in onert::backend::acl_cl::operand::CLSubTensor, and onert::backend::acl_cl::operand::CLTensor.
Referenced by enqueueReadBuffer(), and enqueueWriteBuffer().
handle() [2/2]
arm_compute::ICLTensor * onert::backend::acl_cl::operand::ICLTensor::handle () override pure virtual
Implements onert::backend::acl_common::IACLTensor.
Implemented in onert::backend::acl_cl::operand::CLSubTensor, and onert::backend::acl_cl::operand::CLTensor.
needMemoryMap()
bool onert::backend::acl_cl::operand::ICLTensor::needMemoryMap () const inline final virtual
Reimplemented from onert::backend::ITensor.
Definition at line 42 of file ICLTensor.h.
{ return true; }
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/operand/ICLTensor.h
runtime/onert/backend/acl_cl/operand/ICLTensor.cc