ONE - On-device Neural Engine: ANNBinder Class Reference
ANNBinder Class Reference
A bridge between ann::Module and coco::Block.
#include <Binder.h>
Public Member Functions
ANNBinder (coco::Block *block, std::unique_ptr< ann::Module > &&module)
const coco::Block * block (void) const
coco::Block * block (void)
const ann::Module * module (void) const
std::set< coco::Bag * > bags (void) const
Return the set of bags that the current ANN subnet accesses.
template<typename T >
ann::OperandID addOperand (void)
template<typename T >
ann::OperandID addOperand (const nncc::core::ADT::tensor::Shape &shape)
template<typename T >
ann::OperandID addOperand (const coco::FeatureObject *obj)
template<typename T >
ann::OperandID addOperand (const coco::KernelObject *obj)
template<typename T >
void setOperand (const ann::OperandID &id, const T &value)
Set scalar weight.
template<typename It >
void setOperand (const ann::OperandID &id, It beg, It end)
Set non-scalar weight.
void addOperation (ann::Operation::Code code, std::initializer_list< ann::OperandID > inputs, std::initializer_list< ann::OperandID > outputs)
template<typename It >
void identifyInputs (It beg, It end)
Identify a sequence of coco::Bag * as subnet's inputs.
template<typename T >
void identifyInputs (T &&values)
template<typename It >
void identifyOutputs (It beg, It end)
Identify a sequence of coco::Bag * as subnet's outputs.
template<typename T >
void identifyOutputs (T &&values)
coco::Bag * input (uint32_t n) const
coco::Bag * output (uint32_t n) const
bool associated (coco::Bag *b) const
Return true if a given bag has an associated operand in ANN IR.
ann::OperandID operand (coco::Bag *b) const
Return operand ID associated with a given bag.
Detailed Description
A bridge between ann::Module and coco::Block.
Definition at line 31 of file Binder.h.
Constructor & Destructor Documentation
ANNBinder()
ANNBinder::ANNBinder (coco::Block * block, std::unique_ptr< ann::Module > && module) inline
Definition at line 34 of file Binder.h.
    : _block{block}, _module{std::move(module)}
  {
    // DO NOTHING
  }
Member Function Documentation
addOperand() [1/4]
template<typename T > ann::OperandID ANNBinder::addOperand (const coco::FeatureObject * obj) inline
Definition at line 75 of file Binder.h.
  {
    auto bag = obj->bag();
    assert(bag != nullptr);
    auto it = _operands.find(bag);
    if (it != _operands.end())
    {
      return it->second;
    }
    auto operand = addOperand<T>(morph::nnapi::as_tensor_shape(obj->shape()));
    _operands[obj->bag()] = operand;
    return operand;
  };
References morph::nnapi::as_tensor_shape(), and operand().
addOperand() [2/4]
template<typename T > ann::OperandID ANNBinder::addOperand (const coco::KernelObject * obj) inline
Definition at line 92 of file Binder.h.
  {
    auto bag = obj->bag();
    assert(bag != nullptr);
    auto it = _operands.find(bag);
    if (it != _operands.end())
    {
      return it->second;
    }
    auto operand = addOperand<T>(morph::nnapi::as_tensor_shape(obj->shape()));
    _operands[obj->bag()] = operand;
    return operand;
  };
References morph::nnapi::as_tensor_shape(), and operand().
addOperand() [3/4]
template<typename T > ann::OperandID ANNBinder::addOperand (const nncc::core::ADT::tensor::Shape & shape) inline
Definition at line 69 of file Binder.h.
  {
    return _module->operand()->create(ann::dtype<T>(), shape);
  }
addOperand() [4/4]
template<typename T > ann::OperandID ANNBinder::addOperand (void) inline
Definition at line 64 of file Binder.h.
  {
    return _module->operand()->create(ann::dtype<T>());
  };
addOperation()
void ANNBinder::addOperation (ann::Operation::Code code, std::initializer_list< ann::OperandID > inputs, std::initializer_list< ann::OperandID > outputs) inline
Definition at line 128 of file Binder.h.
  {
    _module->operation()->create(code, inputs, outputs);
  }
associated()
bool ANNBinder::associated (coco::Bag * b) const inline
Return true if a given bag has an associated operand in ANN IR.
Definition at line 194 of file Binder.h.
{ return _operands.find(b) != _operands.end(); }
Referenced by operand().
bags()
std::set< coco::Bag * > ANNBinder::bags (void) const inline
Return the set of bags that the current ANN subnet accesses.
Definition at line 51 of file Binder.h.
  {
    std::set<coco::Bag *> res;
    for (auto it = _operands.begin(); it != _operands.end(); ++it)
    {
      res.insert(it->first);
    }
    return res;
  }
block() [1/2]
coco::Block * ANNBinder::block (void) inline
Definition at line 42 of file Binder.h.
{ return _block; }
block() [2/2]
const coco::Block * ANNBinder::block (void) const inline
Definition at line 41 of file Binder.h.
{ return _block; }
identifyInputs() [1/2]
template<typename It > void ANNBinder::identifyInputs (It beg, It end) inline
Identify a sequence of coco::Bag * as subnet's inputs.
NOTE 1. This method takes input iterator over coco::Bag * values NOTE 2. All the identifyInputs class except the last one will be ignored if there are multiple identifyInputs calls
Definition at line 142 of file Binder.h.
  {
    _inputs.clear();
    _module->input()->clear();
    for (auto it = beg; it != end; ++it)
    {
      auto const bag = *it;
      _inputs.emplace_back(*it);
      _module->input()->emplace_back(_operands.at(bag));
    }
  }
Referenced by identifyInputs().
identifyInputs() [2/2]
template<typename T > void ANNBinder::identifyInputs (T && values) inline
Definition at line 155 of file Binder.h.
  {
    identifyInputs(std::begin(values), std::end(values));
  }
References identifyInputs().
identifyOutputs() [1/2]
template<typename It > void ANNBinder::identifyOutputs (It beg, It end) inline
Identify a sequence of coco::Bag * as subnet's outputs.
NOTE 1. This method takes input iterator over coco::Bag * values NOTE 2. All the identifyOutputs class except the last one will be ignored if there are multiple identifyOutputs calls
Definition at line 168 of file Binder.h.
  {
    _outputs.clear();
    _module->output()->clear();
    for (auto it = beg; it != end; ++it)
    {
      auto const bag = *it;
      _outputs.emplace_back(bag);
      _module->output()->emplace_back(_operands.at(bag));
    }
  }
Referenced by identifyOutputs().
identifyOutputs() [2/2]
template<typename T > void ANNBinder::identifyOutputs (T && values) inline
Definition at line 181 of file Binder.h.
  {
    identifyOutputs(std::begin(values), std::end(values));
  }
References identifyOutputs().
input()
coco::Bag * ANNBinder::input (uint32_t n) const inline
Definition at line 187 of file Binder.h.
{ return _inputs.at(n); }
Referenced by enco::SubnetBlockCompiler::compile().
module()
const ann::Module * ANNBinder::module (void) const inline
Definition at line 45 of file Binder.h.
{ return _module.get(); }
Referenced by enco::SubnetStructBuilder::build(), and enco::SubnetBlockCompiler::compile().
operand()
ann::OperandID ANNBinder::operand (coco::Bag * b) const inline
Return operand ID associated with a given bag.
Note
The behavior of operand(b) is defined only when associated(b) holds.
Definition at line 200 of file Binder.h.
  {
    assert(associated(b));
    return _operands.at(b);
  }
References associated().
Referenced by addOperand().
output()
coco::Bag * ANNBinder::output (uint32_t n) const inline
Definition at line 188 of file Binder.h.
{ return _outputs.at(n); }
Referenced by enco::SubnetBlockCompiler::compile().
setOperand() [1/2]
template<typename T > void ANNBinder::setOperand (const ann::OperandID & id, const T & value) inline
Set scalar weight.
Definition at line 111 of file Binder.h.
  {
    static_assert(std::is_arithmetic<T>::value, "T should be arithmetic");
    auto weight = _module->weight()->create();
    weight->fill(value);
    _module->operand()->at(id)->weight(weight);
  }
setOperand() [2/2]
template<typename It > void ANNBinder::setOperand (const ann::OperandID & id, It beg, It end) inline
Set non-scalar weight.
Definition at line 120 of file Binder.h.
  {
    auto weight = _module->weight()->create();
    weight->fill(beg, end);
    _module->operand()->at(id)->weight(weight);
  }
The documentation for this class was generated from the following file:
compiler/enco/core/src/ANN/Binder.h