ONE - On-device Neural Engine: nnfw::cker::BatchMatMul Class Reference
nnfw::cker::BatchMatMul Class Reference
#include <BatchMatMul.h>
Public Member Functions
BatchMatMul ()
void prepare (const Shape &lhs_shape, const Shape &rhs_shape, bool adj_x, bool adj_y)
Prepare temporary area for calculation.
void operator() (const Shape &lhs_shape, const float *lhs_data, const Shape &rhs_shape, const float *rhs_data, bool adj_x, bool adj_y, const Shape &output_shape, float *output_data)
Detailed Description
Definition at line 35 of file BatchMatMul.h.
Constructor & Destructor Documentation
BatchMatMul()
nnfw::cker::BatchMatMul::BatchMatMul () inline
Definition at line 38 of file BatchMatMul.h.
  {
    // DO NOTHING
  }
Member Function Documentation
operator()()
void nnfw::cker::BatchMatMul::operator() (const Shape & lhs_shape, const float * lhs_data, const Shape & rhs_shape, const float * rhs_data, bool adj_x, bool adj_y, const Shape & output_shape, float * output_data) inline
Definition at line 79 of file BatchMatMul.h.
  {
    // Assume lhs and rhs is not constant
    // TODO Handle constant input
    if (!adj_y)
    {
      transposeRowsCols(rhs_shape, rhs_data, _temp_rhs_shape, _temp_rhs.data());
    }
    if (adj_x)
    {
      transposeRowsCols(lhs_shape, lhs_data, _temp_lhs_shape, _temp_lhs.data());
    }
    Shape new_lhs_shape = adj_x ? lhs_shape : swapRowColDims(lhs_shape);
    Shape new_rhs_shape = adj_y ? rhs_shape : swapRowColDims(rhs_shape);
    const float *new_lhs_data = adj_x ? _temp_lhs.data() : lhs_data;
    const float *new_rhs_data = adj_y ? rhs_data : _temp_rhs.data();
    // Note we pass RHS args first, LHS args second
    // Check accumulative dimensions of lhs and rhs of are equal
    assert(Shape::ExtendedShape(5, new_rhs_shape).Dims(4) ==
           Shape::ExtendedShape(5, new_lhs_shape).Dims(3));
    reference::BatchMatMul(new_rhs_shape, new_rhs_data, new_lhs_shape, new_lhs_data, output_shape,
                           output_data);
  }
References nnfw::cker::reference::BatchMatMul().
prepare()
void nnfw::cker::BatchMatMul::prepare (const Shape & lhs_shape, const Shape & rhs_shape, bool adj_x, bool adj_y) inline
Prepare temporary area for calculation.
Definition at line 46 of file BatchMatMul.h.
  {
    if (adj_x)
    {
      int32_t rank = lhs_shape.DimensionsCount();
      _temp_lhs_shape.Resize(rank);
      for (int32_t i = 0; i < rank - 2; i++)
      {
        _temp_lhs_shape.SetDim(i, lhs_shape.Dims(i));
      }
      _temp_lhs_shape.SetDim(rank - 2, lhs_shape.Dims(rank - 1));
      _temp_lhs_shape.SetDim(rank - 1, lhs_shape.Dims(rank - 2));
      _temp_lhs.resize(_temp_lhs_shape.FlatSize());
    }
    if (!adj_y)
    {
      int32_t rank = rhs_shape.DimensionsCount();
      _temp_rhs_shape.Resize(rank);
      for (int32_t i = 0; i < rank - 2; i++)
      {
        _temp_rhs_shape.SetDim(i, rhs_shape.Dims(i));
      }
      _temp_rhs_shape.SetDim(rank - 2, rhs_shape.Dims(rank - 1));
      _temp_rhs_shape.SetDim(rank - 1, rhs_shape.Dims(rank - 2));
      _temp_rhs.resize(_temp_rhs_shape.FlatSize());
    }
  }
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::Shape::FlatSize(), nnfw::cker::Shape::Resize(), and nnfw::cker::Shape::SetDim().
Referenced by onert::backend::cpu::ops::BatchMatMulLayer::batchMatMulFloat32().
The documentation for this class was generated from the following file:
compute/cker/include/cker/operation/BatchMatMul.h