ONE - On-device Neural Engine: luci_interpreter::kernels::Pad Class Reference
luci_interpreter::kernels::Pad Class Reference
#include <Pad.h>
Public Member Functions
Pad (const Tensor *input, const Tensor *paddings, Tensor *output)
const Tensor * input () const
const Tensor * paddings () const
Tensor * output () const
void configure () override
void execute () const override
Pad (const Tensor *input, const Tensor *paddings, Tensor *output)
const Tensor * input () const
const Tensor * paddings () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file Pad.h.
Constructor & Destructor Documentation
Pad() [1/2]
luci_interpreter::kernels::Pad::Pad (const Tensor * input, const Tensor * paddings, Tensor * output)
Definition at line 30 of file Pad.cpp.
  : Kernel({input, paddings}, {output})
{
}
References input(), and paddings().
Pad() [2/2]
luci_interpreter::kernels::Pad::Pad (const Tensor * input, const Tensor * paddings, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Pad::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 35 of file Pad.cpp.
{
  const Shape &input_shape = input()->shape();
  const int num_dims = input_shape.num_dims();
  if (num_dims > 4)
    throw std::runtime_error("Unsupported number of dimensions.");
  assert(output()->element_type() == input()->element_type());
  assert(paddings()->element_type() == DataType::S32);
  // Paddings shape should be [N, 2].
  assert(paddings()->shape().num_dims() == 2);
  assert(paddings()->shape().dim(0) == num_dims);
  assert(paddings()->shape().dim(1) == 2);
  Shape output_shape(num_dims);
  const auto *paddings_data = getTensorData<int32_t>(paddings());
  for (int i = 0; i < num_dims; ++i)
  {
    const int32_t padding_before = paddings_data[i * 2];
    const int32_t padding_after = paddings_data[i * 2 + 1];
    assert(padding_before >= 0 && padding_after >= 0);
    output_shape.dim(i) = input_shape.dim(i) + padding_before + padding_after;
  }
  output()->resize(output_shape);
}
References luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), output(), paddings(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Pad::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Pad::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 63 of file Pad.cpp.
{
  const int num_dims = input()->shape().num_dims();
  tflite::PadParams params{};
  params.left_padding_count = num_dims;
  params.right_padding_count = num_dims;
  const auto *paddings_data = getTensorData<int32_t>(paddings());
  for (int i = num_dims - 1; i >= 0; --i)
  {
    params.left_padding[i] = paddings_data[i * 2];
    params.right_padding[i] = paddings_data[i * 2 + 1];
  }
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
    {
      const float pad_value = 0.0f;
      tflite::reference_ops::Pad(params, getTensorShape(input()), getTensorData<float>(input()),
                                 &pad_value, getTensorShape(output()),
                                 getTensorData<float>(output()));
      break;
    }
    case DataType::U8:
    {
      assert(output()->zero_point() >= std::numeric_limits<uint8_t>::min());
      assert(output()->zero_point() <= std::numeric_limits<uint8_t>::max());
      const auto pad_value = static_cast<uint8_t>(output()->zero_point());
      tflite::reference_ops::Pad(params, getTensorShape(input()), getTensorData<uint8_t>(input()),
                                 &pad_value, getTensorShape(output()),
                                 getTensorData<uint8_t>(output()));
      break;
    }
    case DataType::S8:
    {
      assert(output()->zero_point() >= std::numeric_limits<int8_t>::min());
      assert(output()->zero_point() <= std::numeric_limits<int8_t>::max());
      const auto pad_value = static_cast<int8_t>(output()->zero_point());
      tflite::reference_ops::Pad(params, getTensorShape(input()), getTensorData<int8_t>(input()),
                                 &pad_value, getTensorShape(output()),
                                 getTensorData<int8_t>(output()));
      break;
    }
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::kernels::getTensorShape(), input(), luci_interpreter::Shape::num_dims(), output(), paddings(), luci_interpreter::Tensor::shape(), and luci_interpreter::Tensor::zero_point().
execute() [2/2]
void luci_interpreter::kernels::Pad::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Pad::input () const inline
Definition at line 32 of file Pad.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Pad().
input() [2/2]
const Tensor * luci_interpreter::kernels::Pad::input () const inline
Definition at line 32 of file Pad.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Pad::output () const inline
Definition at line 34 of file Pad.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Pad::output () const inline
Definition at line 34 of file Pad.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
paddings() [1/2]
const Tensor * luci_interpreter::kernels::Pad::paddings () const inline
Definition at line 33 of file Pad.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Pad().
paddings() [2/2]
const Tensor * luci_interpreter::kernels::Pad::paddings () const inline
Definition at line 33 of file Pad.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Pad.h
onert-micro/luci-interpreter/src/kernels/Pad.h
compiler/luci-interpreter/src/kernels/Pad.cpp
onert-micro/luci-interpreter/src/kernels/Pad.cpp