ONE - On-device Neural Engine: moco::tf::ProgressReporter Class Reference
moco::tf::ProgressReporter Class Reference
#include <ProgressReporter.h>
Public Member Functions
ProgressReporter (loco::Graph *graph, logo::PhaseStrategy strategy)
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > *) override
void notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > *) override
loco::Graph * graph (void) const
logo::PhaseStrategy strategy (void) const
Public Member Functions inherited from logo::PhaseEventListener
virtual ~PhaseEventListener ()=default
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseEnd > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassEnd > *)
Detailed Description
Definition at line 29 of file ProgressReporter.h.
Constructor & Destructor Documentation
ProgressReporter()
moco::tf::ProgressReporter::ProgressReporter (loco::Graph * graph, logo::PhaseStrategy strategy) inline
Definition at line 32 of file ProgressReporter.h.
    : _graph{graph}, _strategy{strategy}
  {
    // DO NOTHING
  }
Member Function Documentation
graph()
loco::Graph * moco::tf::ProgressReporter::graph (void) const inline
Definition at line 45 of file ProgressReporter.h.
{ return _graph; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), notify(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
notify() [1/4]
void moco::tf::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassBegin > * info) override
Definition at line 70 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "--------------------------------------------------------------";
  INFO(prime) << "Before " << logo::pass_name(info->pass());
}
References INFO, info, LOGGER, and logo::pass_name().
notify() [2/4]
void moco::tf::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PassEnd > * info) override
Definition at line 78 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "After " << logo::pass_name(info->pass())
              << " (changed: " << to_char(info->changed()) << ")";
  INFO(prime) << moco::tf::fmt(graph());
}
References moco::tf::fmt(), graph(), INFO, info, LOGGER, and logo::pass_name().
notify() [3/4]
void moco::tf::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseBegin > * info) override
Definition at line 53 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "==============================================================";
  INFO(prime) << "PhaseRunner<" << to_str(strategy()) << ">";
  INFO(prime) << "Initial graph";
  INFO(prime) << moco::tf::fmt(graph());
}
References moco::tf::fmt(), graph(), INFO, LOGGER, and strategy().
notify() [4/4]
void moco::tf::ProgressReporter::notify (const logo::PhaseEventInfo< logo::PhaseEvent::PhaseEnd > * info) override
Definition at line 63 of file ProgressReporter.cpp.
{
  LOGGER(prime);
  INFO(prime) << "PhaseRunner<" << to_str(strategy()) << "> - done";
}
References INFO, LOGGER, and strategy().
strategy()
logo::PhaseStrategy moco::tf::ProgressReporter::strategy (void) const inline
Definition at line 46 of file ProgressReporter.h.
{ return _strategy; }
Referenced by notify().
The documentation for this class was generated from the following files:
compiler/moco-tf/src/ProgressReporter.h
compiler/moco-tf/src/ProgressReporter.cpp