ONE - On-device Neural Engine: onert::backend::train::ops::PadLayer Class Reference
onert::backend::train::ops::PadLayer Class Reference
#include <PadLayer.h>
Public Member Functions
PadLayer ()
template<typename T >
void depad ()
void configureBackward (IPortableTensor *back_prop_input, const IPortableTensor *back_prop_output)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
Public Member Functions inherited from onert::backend::cpu::ops::PadLayer
PadLayer ()
template<typename T >
void padImpl (const T *constant_value_data)
void configure (const IPortableTensor *input, const IPortableTensor *pad, const IPortableTensor *value, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::PadLayer
const IPortableTensor * _input
const IPortableTensor * _pad
const IPortableTensor * _value
IPortableTensor * _output
ConstDataPtr _constantValueData
Detailed Description
Definition at line 37 of file PadLayer.h.
Constructor & Destructor Documentation
PadLayer()
onert::backend::train::ops::PadLayer::PadLayer ()
Definition at line 30 of file PadLayer.cc.
                   : cpu::ops::PadLayer(), _back_prop_input{nullptr}, _back_prop_output{nullptr}
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::PadLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 55 of file PadLayer.cc.
{
  switch (_back_prop_output->data_type())
  {
    case OperandType::FLOAT32:
      depad<float>();
      break;
    case OperandType::QUANT_UINT8_ASYMM:
      depad<uint8_t>();
      break;
    case OperandType::QUANT_INT8_ASYMM:
      depad<int8_t>();
      break;
    default:
      throw std::runtime_error{"Pad: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type().
configureBackward()
void onert::backend::train::ops::PadLayer::configureBackward (IPortableTensor * back_prop_input, const IPortableTensor * back_prop_output)
Definition at line 46 of file PadLayer.cc.
{
  _back_prop_input = back_prop_input;
  _back_prop_output = back_prop_output;
}
depad()
template<typename T > void onert::backend::train::ops::PadLayer::depad ()
Definition at line 35 of file PadLayer.cc.
{
  assert(_pad->data_type() == onert::ir::DataType::INT32);
  assert(_pad->buffer());
  const auto pad_data = reinterpret_cast<const int32_t *>(_pad->buffer());
  auto pad_rank = _pad->getShape().dim(0);
  nnfw::cker::train::Depad<T>(pad_data, pad_rank, getShape(_back_prop_output),
                              getBuffer<T>(_back_prop_output), getShape(_back_prop_input),
                              getBuffer<T>(_back_prop_input));
}
References onert::backend::cpu::ops::PadLayer::_pad, onert::backend::ITensor::buffer(), onert::backend::ITensor::data_type(), and onert::backend::ITensor::getShape().
forward()
void onert::backend::train::ops::PadLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 53 of file PadLayer.cc.
{ cpu::ops::PadLayer::run(); }
References onert::backend::cpu::ops::PadLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/PadLayer.h
runtime/onert/backend/train/ops/PadLayer.cc