ONE - On-device Neural Engine: nnc::cli::CommandLine Class Reference
nnc::cli::CommandLine Class Reference
this class describes a common command line interface
#include <CommandLine.h>
Public Member Functions
CommandLine (const CommandLine &)=delete
CommandLine & operator= (const CommandLine &)=delete
void parseCommandLine (int argc, const char **argv, bool check_nonoptional=true)
parse command line option
void registerOption (IOption *opt)
register option for parser
Static Public Member Functions
static CommandLine * getParser ()
singleton method
Detailed Description
this class describes a common command line interface
Definition at line 304 of file CommandLine.h.
Constructor & Destructor Documentation
CommandLine()
nnc::cli::CommandLine::CommandLine (const CommandLine &) delete
Member Function Documentation
getParser()
CommandLine * nnc::cli::CommandLine::getParser () static
singleton method
Definition at line 106 of file CommandLine.cpp.
{
  static CommandLine Parser;
  return &Parser;
} // getParser
Referenced by main(), nnc::cli::Option< T >::Option(), and TEST().
operator=()
CommandLine & nnc::cli::CommandLine::operator= (const CommandLine &) delete
parseCommandLine()
void nnc::cli::CommandLine::parseCommandLine (int argc, const char ** argv, bool check_nonoptional = true)
parse command line option
Parameters
argc - number of command line arguments
argv - command line arguments
check_nonoptional - if true then check that all non optional declared options are presented
Definition at line 466 of file CommandLine.cpp.
{
  std::set<std::string> cmd_args;
  IOption *opt;
  const char *arg_val = nullptr;
  _prog_name = argv[0];
  _args_num = argc;
  if (argc == 1)
  {
    // empty command line
    usage();
  }
  // search help option and print help if this option is passed
  for (int i = 1; i < argc; i++)
  {
    if (!strcmp(argv[i], "-h") || !strcmp(argv[i], "--help"))
    {
      usage("", EXIT_SUCCESS);
    }
  }
  for (int i = 1; i < argc; i += (argv[i + 1] == arg_val) ? 2 : 1)
  {
    if (argv[i][0] != '-')
    {
      std::string err_msg(std::string("invalid command line argument: ") + argv[i]);
      usage(err_msg);
    }
    // find registered option
    try
    {
      opt = findOption(argv[i]);
    }
    catch (BadOption &e)
    {
      std::string err_msg(std::string("invalid option: ") + e.getName());
      usage(err_msg);
    }
    // figure out value for option
    try
    {
      if (opt->canHaveSeveralVals())
      {
        int j = i + 1;
        for (arg_val = findValueForMultOption(opt, argv[i], argv, j); arg_val;
             arg_val = findValueForMultOption(opt, argv[i], argv, j))
        {
          // set value for option
          opt->setValue(arg_val);
          j++;
        }
        i = j - 1;
      }
      else
      {
        arg_val = findOptionValue(opt, argv, i);
        // set value for option
        opt->setValue(arg_val);
      }
    }
    catch (BadOption &e)
    {
      std::string optname = e.getName();
      optname = optname.empty() ? argv[i] : optname;
      std::string err_msg(std::string("invalid value: ") + e.getValue() +
                          std::string(" for option: ") + optname);
      usage(err_msg);
    }
    // we can't just put argv[i] because option can have separators
    cmd_args.insert(opt->getNames()[0]);
  }
  if (check_nonoptional)
  {
    // check that all registered options are present in command line
    checkRegisteredOptions(cmd_args);
  }
  // verify options
  checkOptions(cmd_args);
} // parseCommandLine
References nnc::cli::IOption::canHaveSeveralVals(), nnc::cli::BadOption::getName(), nnc::cli::IOption::getNames(), nnc::cli::BadOption::getValue(), nnc::cli::optname(), and nnc::cli::IOption::setValue().
Referenced by main(), and TEST().
registerOption()
void nnc::cli::CommandLine::registerOption (IOption * opt)
register option for parser
Parameters
opt - option
Definition at line 199 of file CommandLine.cpp.
{
  for (const auto &n : opt->getNames())
  {
    auto i = _options_name.emplace(n, opt);
    if (!i.second)
    {
      std::cerr << "option name must be unique: `" << n << "'" << std::endl;
      exit(EXIT_FAILURE);
    }
  }
  _options.push_back(opt);
  if (opt->isGrouped())
  {
    auto it = _grouped_options.find(opt->getGroup());
    if (it == _grouped_options.end())
      _grouped_options.emplace(opt->getGroup(), std::vector<IOption *>{opt});
    else
      it->second.push_back(opt);
  }
} // registerOption
References nnc::cli::IOption::getGroup(), nnc::cli::IOption::getNames(), and nnc::cli::IOption::isGrouped().
Referenced by nnc::cli::Option< T >::Option().
The documentation for this class was generated from the following files:
compiler/nnc/include/support/CommandLine.h
compiler/nnc/support/CommandLine.cpp