ONE - On-device Neural Engine: moco::PlaceholderGraphBuilder Class Reference
moco::PlaceholderGraphBuilder Class Reference final
GraphBuilder for Placeholder node.
#include <Placeholder.h>
Public Member Functions
bool validate (const tensorflow::NodeDef &) const override
void build (const tensorflow::NodeDef &, GraphBuilderContext *) const override
Public Member Functions inherited from moco::GraphBuilder
virtual bool validate (const tensorflow::NodeDef &) const =0
virtual void build (const tensorflow::NodeDef &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Placeholder node.
Definition at line 28 of file Placeholder.h.
Member Function Documentation
build()
void moco::PlaceholderGraphBuilder::build (const tensorflow::NodeDef & node, GraphBuilderContext * context) const override virtual
Implements moco::GraphBuilder.
Definition at line 43 of file Placeholder.cpp.
{
  assert(context != nullptr);
  loco::Graph *graph = context->graph();
  SymbolTable *tensor_names = context->tensor_names();
  loco::DataType dtype = plier::tf::as_loco_datatype(plier::tf::get_datatype_attr(node, "dtype"));
  const auto &shape = plier::tf::get_shape_attr(node, "shape");
  // TODO handle for unknown rank
  assert(!shape.unknown_rank());
  int64_t num_dims = shape.dim_size();
  // TODO support other types
  assert(dtype == loco::DataType::FLOAT32);
  // Create a "Placeholder" node as an input
  auto placeholder_node = graph->nodes()->create<moco::TFPlaceholder>();
  placeholder_node->name(node.name());
  placeholder_node->dtype(dtype);
  // Setting shape info.
  placeholder_node->rank(num_dims);
  for (int64_t d = 0; d < num_dims; d++)
  {
    assert(shape.dim(d).size() < std::numeric_limits<uint32_t>::max());
    int64_t dim_value = shape.dim(d).size();
    if (dim_value >= 0)
    {
      uint32_t dim_value32 = static_cast<uint32_t>(dim_value);
      placeholder_node->dim(d) = dim_value32;
    }
    else
    {
      placeholder_node->dim(d).unset();
      // TODO Remove assert() and do implement
      // NOTE Current implementation assumes dim is all know
      assert(false);
    }
  }
  // register string-name to node
  TensorName output_name(node.name(), 0);
  tensor_names->enroll(output_name, placeholder_node);
}
References plier::tf::as_loco_datatype(), moco::SymbolTable::enroll(), plier::tf::get_datatype_attr(), plier::tf::get_shape_attr(), moco::GraphBuilderContext::graph(), moco::TFNode::name(), moco::placeholder_node(), and moco::GraphBuilderContext::tensor_names().
validate()
bool moco::PlaceholderGraphBuilder::validate (const tensorflow::NodeDef & node) const override virtual
Implements moco::GraphBuilder.
Definition at line 30 of file Placeholder.cpp.
{
  if (!plier::tf::has_attrs(node, {"dtype", "shape"}))
    return false;
  loco::DataType dtype = plier::tf::as_loco_datatype(plier::tf::get_datatype_attr(node, "dtype"));
  if (dtype != loco::DataType::FLOAT32)
    return false;
  // TODO support other types
  return true;
}
References plier::tf::as_loco_datatype(), plier::tf::get_datatype_attr(), and plier::tf::has_attrs().
The documentation for this class was generated from the following files:
compiler/moco/import/include/moco/Import/Nodes/Placeholder.h
compiler/moco/import/src/Nodes/Placeholder.cpp