ONE - On-device Neural Engine: cwrap::Fildes Class Reference
cwrap::Fildes Class Reference final
POSIX File Descriptor.
#include <Fildes.h>
Public Member Functions
Fildes ()
Fildes (int value)
Fildes (const Fildes &)=delete
Fildes (Fildes &&)
~Fildes ()
Fildes & operator= (Fildes &&)
int get (void) const
void set (int value)
int release (void)
Detailed Description
POSIX File Descriptor.
Note
Fildes owns underlying file descriptor
Definition at line 28 of file Fildes.h.
Constructor & Destructor Documentation
Fildes() [1/4]
cwrap::Fildes::Fildes ()
Definition at line 38 of file Fildes.cpp.
               : _value{-1}
{
  // DO NOTHING
}
Fildes() [2/4]
cwrap::Fildes::Fildes (int value) explicit
Definition at line 43 of file Fildes.cpp.
                        : _value{value}
{
  // DO NOTHING
  assert(error_value(value) || valid_value(value));
}
Fildes() [3/4]
cwrap::Fildes::Fildes (const Fildes &) delete
Fildes() [4/4]
cwrap::Fildes::Fildes (Fildes && fildes)
Definition at line 49 of file Fildes.cpp.
{
  set(fildes.release());
  assert(error_value(fildes.get()));
}
References set().
~Fildes()
cwrap::Fildes::~Fildes ()
Definition at line 55 of file Fildes.cpp.
{
  assert(error_value(_value) || valid_value(_value));
  if (valid_value(_value))
  {
    close(_value);
    _value = -1;
  }
  assert(error_value(_value));
}
Member Function Documentation
get()
int cwrap::Fildes::get (void) const
Definition at line 74 of file Fildes.cpp.
{ return _value; }
Referenced by release(), and cwrap::valid().
operator=()
Fildes & cwrap::Fildes::operator= (Fildes && fildes)
Definition at line 68 of file Fildes.cpp.
{
  set(fildes.release());
  return (*this);
}
References set().
release()
int cwrap::Fildes::release (void)
Definition at line 91 of file Fildes.cpp.
{
  int res = get();
  _value = -1;
  return res;
}
References get().
set()
void cwrap::Fildes::set (int value)
Definition at line 76 of file Fildes.cpp.
{
  assert(error_value(_value) || valid_value(_value));
  if (valid_value(_value))
  {
    close(_value);
    _value = -1;
  }
  assert(error_value(_value));
  _value = value;
  assert(_value == value);
}
Referenced by Fildes(), and operator=().
The documentation for this class was generated from the following files:
compiler/cwrap/include/cwrap/Fildes.h
compiler/cwrap/src/Fildes.cpp