ONE - On-device Neural Engine: loco::PermutingDecoder< Domain::Matrix > Class Reference
loco::PermutingDecoder< Domain::Matrix > Class Reference final
Permutation-based Matrix-to-Tensor converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingDecoder ()=default
PermutingDecoder (const Permutation< Domain::Matrix > &perm)
bool valid (void) const
TensorShape shape (const MatrixShape &tensor_shape) const override
MatrixIndex value (const TensorIndex &index) const override
const Permutation< Domain::Matrix > * perm (void) const
Permutation< Domain::Matrix > * perm (void)
void perm (const Permutation< Domain::Matrix > &p)
Public Member Functions inherited from loco::MatrixDecoder
virtual ~MatrixDecoder ()=default
virtual TensorShape shape (const MatrixShape &) const =0
virtual MatrixIndex value (const TensorIndex &) const =0
Detailed Description
Permutation-based Matrix-to-Tensor converter.
Definition at line 392 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingDecoder() [1/2]
loco::PermutingDecoder< Domain::Matrix >::PermutingDecoder () default
PermutingDecoder() [2/2]
loco::PermutingDecoder< Domain::Matrix >::PermutingDecoder (const Permutation< Domain::Matrix > & perm) inline
Definition at line 398 of file PermutingCodec.h.
                                                          : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingDecoder< Domain::Matrix >::perm (const Permutation< Domain::Matrix > & p) inline
Definition at line 413 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Matrix > * loco::PermutingDecoder< Domain::Matrix >::perm (void) inline
Definition at line 412 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Matrix > * loco::PermutingDecoder< Domain::Matrix >::perm (void) const inline
Definition at line 411 of file PermutingCodec.h.
{ return &_perm; }
shape()
TensorShape loco::PermutingDecoder< Domain::Matrix >::shape (const MatrixShape & tensor_shape) const override virtual
Implements loco::MatrixDecoder.
Definition at line 601 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permuation");
  TensorShape out;
  out.rank(2);
  out.dim(_perm[MatrixAxis::Height]) = in.height();
  out.dim(_perm[MatrixAxis::Width]) = in.width();
  return out;
}
References loco::TensorShape::dim(), loco::Height, loco::MatrixShape::height(), loco::TensorShape::rank(), loco::valid(), loco::Width, and loco::MatrixShape::width().
valid()
bool loco::PermutingDecoder< Domain::Matrix >::valid (void) const
Definition at line 627 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
MatrixIndex loco::PermutingDecoder< Domain::Matrix >::value (const TensorIndex & index) const override virtual
Implements loco::MatrixDecoder.
Definition at line 615 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  MatrixIndex out;
  out.row() = in.at(_perm[MatrixAxis::Height]);
  out.column() = in.at(_perm[MatrixAxis::Width]);
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::MatrixIndex::column(), loco::Height, loco::MatrixIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp