ONE - On-device Neural Engine: onert::backend::train::ops::LossLayer Class Reference
onert::backend::train::ops::LossLayer Class Reference
#include <LossLayer.h>
Public Member Functions
LossLayer ()
void configure (const IPortableTensor *y_pred, const IPortableTensor *y_true, IPortableTensor *output, IPortableTensor *back_prop_y_pred, LossType loss_type)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
virtual void forward (bool training)=0
virtual void backward ()=0
Detailed Description
Definition at line 39 of file LossLayer.h.
Constructor & Destructor Documentation
LossLayer()
onert::backend::train::ops::LossLayer::LossLayer ()
Definition at line 31 of file LossLayer.cc.
  : _y_pred(nullptr), _y_true(nullptr), _output(nullptr), _back_prop_y_pred(nullptr),
    _loss_type(LossType::kMSE)
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::LossLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 79 of file LossLayer.cc.
{
  switch (_loss_type)
  {
    case LossType::kMSE:
      if (_y_pred->data_type() == OperandType::FLOAT32)
      {
        nnfw::cker::train::MSEGrad(getShape(_y_pred), getBuffer<float>(_y_pred), getShape(_y_true),
                                   getBuffer<float>(_y_true), getShape(_back_prop_y_pred),
                                   getBuffer<float>(_back_prop_y_pred));
      }
      break;
    default:
      throw std::runtime_error("LossLayer: unsupported loss type");
  }
}
References onert::backend::ITensor::data_type(), onert::backend::train::ops::kMSE, and nnfw::cker::train::MSEGrad().
configure()
void onert::backend::train::ops::LossLayer::configure (const IPortableTensor * y_pred, const IPortableTensor * y_true, IPortableTensor * output, IPortableTensor * back_prop_y_pred, LossType loss_type)
Definition at line 38 of file LossLayer.cc.
{
  assert(y_pred != nullptr);
  assert(y_true != nullptr);
  assert(output != nullptr);
  assert(back_prop_y_pred != nullptr);
  switch (loss_type)
  {
    case LossType::kMSE:
      break;
    default:
      throw std::runtime_error("LossLayer: unsupported loss type");
  }
  _y_pred = y_pred;
  _y_true = y_true;
  _output = output;
  _back_prop_y_pred = back_prop_y_pred;
  _loss_type = loss_type;
}
References onert::backend::train::ops::kMSE.
forward()
void onert::backend::train::ops::LossLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 61 of file LossLayer.cc.
{
  // TODO Implement this
  switch (_loss_type)
  {
    case LossType::kMSE:
      if (_y_pred->data_type() == OperandType::FLOAT32)
      {
        nnfw::cker::train::MSE(getShape(_y_pred), getBuffer<float>(_y_pred), getShape(_y_true),
                               getBuffer<float>(_y_true), getShape(_output),
                               getBuffer<float>(_output));
      }
      break;
    default:
      throw std::runtime_error("LossLayer: unsupported loss type");
  }
}
References onert::backend::ITensor::data_type(), onert::backend::train::ops::kMSE, and nnfw::cker::train::MSE().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/LossLayer.h
runtime/onert/backend/train/ops/LossLayer.cc