ONE - On-device Neural Engine: ann::OperandInventory Class Reference
ann::OperandInventory Class Reference
#include <OperandInventory.h>
Public Member Functions
OperandID create (const DType &)
OperandID create (const DType &, const nncc::core::ADT::tensor::Shape &)
template<typename Callable >
void each (Callable &&cb) const
Operand * at (const OperandID &id)
const Operand * at (const OperandID &id) const
Detailed Description
Definition at line 31 of file OperandInventory.h.
Member Function Documentation
at() [1/2]
Operand * ann::OperandInventory::at (const OperandID & id)
Definition at line 50 of file OperandInventory.cpp.
{ return _operands.at(id.value()).get(); }
at() [2/2]
const Operand * ann::OperandInventory::at (const OperandID & id) const
Definition at line 52 of file OperandInventory.cpp.
{
  return _operands.at(id.value()).get();
}
create() [1/2]
OperandID ann::OperandInventory::create (const DType & dtype)
Definition at line 26 of file OperandInventory.cpp.
{
  uint32_t id = _operands.size();
  auto operand = make_unique<ScalarOperand>();
  operand->dtype(dtype);
  _operands.emplace_back(std::move(operand));
  return OperandID{id};
}
References ann::dtype().
create() [2/2]
OperandID ann::OperandInventory::create (const DType & dtype, const nncc::core::ADT::tensor::Shape & shape)
Definition at line 38 of file OperandInventory.cpp.
{
  uint32_t id = _operands.size();
  auto operand = make_unique<TensorOperand>(shape);
  operand->dtype(dtype);
  _operands.emplace_back(std::move(operand));
  return OperandID{id};
}
References ann::dtype().
each()
template<typename Callable > void ann::OperandInventory::each (Callable && cb) const inline
Definition at line 38 of file OperandInventory.h.
  {
    for (uint32_t n = 0; n < _operands.size(); ++n)
    {
      cb(OperandID{n}, _operands.at(n).get());
    }
  }
Referenced by enco::SubnetStructBuilder::build().
The documentation for this class was generated from the following files:
compiler/enco/core/src/ANN/IR/OperandInventory.h
compiler/enco/core/src/ANN/IR/OperandInventory.cpp