ONE - On-device Neural Engine: loco::Stride< 2 > Class Reference
loco::Stride< 2 > Class Reference final
Stride configuration for 2D spatial operations.
#include <Stride.h>
Public Member Functions
uint32_t vertical (void) const
void vertical (uint32_t value)
uint32_t horizontal (void) const
void horizontal (uint32_t value)
Detailed Description
Stride configuration for 2D spatial operations.
Definition at line 33 of file Stride.h.
Member Function Documentation
horizontal() [1/2]
void loco::Stride< 2 >::horizontal (uint32_t value) inline
Definition at line 41 of file Stride.h.
{ _horizontal = value; }
horizontal() [2/2]
uint32_t loco::Stride< 2 >::horizontal (void) const inline
Definition at line 40 of file Stride.h.
{ return _horizontal; }
Referenced by exo::AvgPool2DConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MaxPool2DConverter::convert(), exo::TransposedConv2DConverter::convert(), and moco::PlaneInference::fill().
vertical() [1/2]
void loco::Stride< 2 >::vertical (uint32_t value) inline
Definition at line 37 of file Stride.h.
{ _vertical = value; }
vertical() [2/2]
uint32_t loco::Stride< 2 >::vertical (void) const inline
Definition at line 36 of file Stride.h.
{ return _vertical; }
Referenced by exo::AvgPool2DConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MaxPool2DConverter::convert(), exo::TransposedConv2DConverter::convert(), and moco::PlaneInference::fill().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/Stride.h