ONE - On-device Neural Engine: coco::OutputManager Class Reference
coco::OutputManager Class Reference final
#include <OutputManager.h>
Public Member Functions
OutputManager (Module *m=nullptr)
Output * create (const nncc::core::ADT::tensor::Shape &)
Public Member Functions inherited from coco::PtrManager< Output >
uint32_t size (void) const
Return the number of managed objects.
Output * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Output >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Output > release (Output *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 28 of file OutputManager.h.
Constructor & Destructor Documentation
OutputManager()
coco::OutputManager::OutputManager (Module * m = nullptr) inline
Definition at line 31 of file OutputManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
Member Function Documentation
create()
Output * coco::OutputManager::create (const nncc::core::ADT::tensor::Shape & shape)
Definition at line 24 of file OutputManager.cpp.
{
  auto output = std::make_unique<Output>(shape);
  modulize(output.get());
  return take(std::move(output));
}
References coco::EntityBuilder::modulize(), and coco::PtrManager< Output >::take().
Referenced by Frontend::load().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/OutputManager.h
compiler/coco/core/src/IR/OutputManager.cpp