ONE - On-device Neural Engine: onert::compiler::OperandLowerInfo Class Reference
onert::compiler::OperandLowerInfo Class Reference
#include <OperandLowerInfo.h>
Public Member Functions
OperandLowerInfo ()
const PermuteFactorSet & def_factors (void) const
const PermuteFactorSet & use_factors (void) const
void addDefPermuteFactor (const PermuteFactor &factor)
void addUsePermuteFactor (const PermuteFactor &factor)
void removeDefPermuteFactor (const PermuteFactor &factor)
void removeUsePermuteFactor (const PermuteFactor &factor)
Detailed Description
Definition at line 41 of file OperandLowerInfo.h.
Constructor & Destructor Documentation
OperandLowerInfo()
onert::compiler::OperandLowerInfo::OperandLowerInfo () inline
Definition at line 44 of file OperandLowerInfo.h.
  {
    // DO NOTHING
  }
Member Function Documentation
addDefPermuteFactor()
void onert::compiler::OperandLowerInfo::addDefPermuteFactor (const PermuteFactor & factor) inline
Definition at line 54 of file OperandLowerInfo.h.
{ _def_factors.add(factor); }
References onert::util::Set< Element >::add().
addUsePermuteFactor()
void onert::compiler::OperandLowerInfo::addUsePermuteFactor (const PermuteFactor & factor) inline
Definition at line 55 of file OperandLowerInfo.h.
{ _use_factors.add(factor); }
References onert::util::Set< Element >::add().
def_factors()
const PermuteFactorSet & onert::compiler::OperandLowerInfo::def_factors (void) const inline
Definition at line 50 of file OperandLowerInfo.h.
{ return _def_factors; }
removeDefPermuteFactor()
void onert::compiler::OperandLowerInfo::removeDefPermuteFactor (const PermuteFactor & factor) inline
Definition at line 56 of file OperandLowerInfo.h.
{ _def_factors.remove(factor); }
References onert::util::Set< Element >::remove().
removeUsePermuteFactor()
void onert::compiler::OperandLowerInfo::removeUsePermuteFactor (const PermuteFactor & factor) inline
Definition at line 57 of file OperandLowerInfo.h.
{ _use_factors.remove(factor); }
References onert::util::Set< Element >::remove().
use_factors()
const PermuteFactorSet & onert::compiler::OperandLowerInfo::use_factors (void) const inline
Definition at line 51 of file OperandLowerInfo.h.
{ return _use_factors; }
The documentation for this class was generated from the following file:
runtime/onert/core/include/compiler/OperandLowerInfo.h