ONE - On-device Neural Engine: flatbuffers::Table Class Reference
flatbuffers::Table Class Reference
#include <table.h>
Public Member Functions
const uint8_t * GetVTable () const
voffset_t GetOptionalFieldOffset (voffset_t field) const
template<typename T >
T GetField (voffset_t field, T defaultval) const
template<typename P , typename OffsetSize = uoffset_t>
P GetPointer (voffset_t field)
template<typename P , typename OffsetSize = uoffset_t>
P GetPointer (voffset_t field) const
template<typename P >
P GetPointer64 (voffset_t field)
template<typename P >
P GetPointer64 (voffset_t field) const
template<typename P >
P GetStruct (voffset_t field) const
template<typename Raw , typename Face >
flatbuffers::Optional< Face > GetOptional (voffset_t field) const
template<typename T >
bool SetField (voffset_t field, T val, T def)
template<typename T >
bool SetField (voffset_t field, T val)
bool SetPointer (voffset_t field, const uint8_t *val)
uint8_t * GetAddressOf (voffset_t field)
const uint8_t * GetAddressOf (voffset_t field) const
bool CheckField (voffset_t field) const
bool VerifyTableStart (Verifier &verifier) const
template<typename T >
bool VerifyField (const Verifier &verifier, voffset_t field, size_t align) const
template<typename T >
bool VerifyFieldRequired (const Verifier &verifier, voffset_t field, size_t align) const
template<typename OffsetT = uoffset_t>
bool VerifyOffset (const Verifier &verifier, voffset_t field) const
template<typename OffsetT = uoffset_t>
bool VerifyOffsetRequired (const Verifier &verifier, voffset_t field) const
bool VerifyOffset64 (const Verifier &verifier, voffset_t field) const
bool VerifyOffset64Required (const Verifier &verifier, voffset_t field) const
template<>
flatbuffers::Optional< bool > GetOptional (voffset_t field) const
Detailed Description
Definition at line 27 of file table.h.
Member Function Documentation
CheckField()
bool flatbuffers::Table::CheckField (voffset_t field) const inline
Definition at line 113 of file table.h.
{
    return GetOptionalFieldOffset(field) != 0;
  }
References GetOptionalFieldOffset().
GetAddressOf() [1/2]
uint8_t * flatbuffers::Table::GetAddressOf (voffset_t field) inline
Definition at line 105 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    return field_offset ? data_ + field_offset : nullptr;
  }
References GetOptionalFieldOffset().
Referenced by GetAddressOf(), flatbuffers::GetAnyFieldAddressOf(), flatbuffers::GetAnyFieldF(), flatbuffers::GetAnyFieldI(), flatbuffers::GetAnyFieldS(), flatbuffers::SetAnyFieldF(), flatbuffers::SetAnyFieldI(), and flatbuffers::SetAnyFieldS().
GetAddressOf() [2/2]
const uint8_t * flatbuffers::Table::GetAddressOf (voffset_t field) const inline
Definition at line 109 of file table.h.
{
    return const_cast<Table *>(this)->GetAddressOf(field);
  }
References GetAddressOf().
GetField()
template<typename T > T flatbuffers::Table::GetField (voffset_t field, T defaultval) const inline
Definition at line 45 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    return field_offset ? ReadScalar<T>(data_ + field_offset) : defaultval;
  }
References GetOptionalFieldOffset().
Referenced by flatbuffers::GetFieldF(), and flatbuffers::GetFieldI().
GetOptional() [1/2]
template<> flatbuffers::Optional< bool > flatbuffers::Table::GetOptional (voffset_t field) const inline
Definition at line 1 of file table.h.
{
  auto field_offset = GetOptionalFieldOffset(field);
  auto p = data_ + field_offset;
  return field_offset ? Optional<bool>(ReadScalar<uint8_t>(p) != 0)
                      : Optional<bool>();
}
GetOptional() [2/2]
template<typename Raw , typename Face > flatbuffers::Optional< Face > flatbuffers::Table::GetOptional (voffset_t field) const inline
Definition at line 77 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    auto p = data_ + field_offset;
    return field_offset ? Optional<Face>(static_cast<Face>(ReadScalar<Raw>(p)))
                        : Optional<Face>();
  }
References GetOptionalFieldOffset(), and p.
GetOptionalFieldOffset()
voffset_t flatbuffers::Table::GetOptionalFieldOffset (voffset_t field) const inline
Definition at line 35 of file table.h.
{
    // The vtable offset is always at the start.
    auto vtable = GetVTable();
    // The first element is the size of the vtable (fields + type id + itself).
    auto vtsize = ReadScalar<voffset_t>(vtable);
    // If the field we're accessing is outside the vtable, we're reading older
    // data, so it's the same as if the offset was 0 (not present).
    return field < vtsize ? ReadScalar<voffset_t>(vtable + field) : 0;
  }
References GetVTable().
Referenced by CheckField(), GetAddressOf(), GetField(), GetOptional(), GetPointer(), GetStruct(), SetField(), SetField(), SetPointer(), VerifyField(), VerifyFieldRequired(), VerifyOffset(), and VerifyOffsetRequired().
GetPointer() [1/2]
template<typename P , typename OffsetSize = uoffset_t> P flatbuffers::Table::GetPointer (voffset_t field) inline
Definition at line 51 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    auto p = data_ + field_offset;
    return field_offset ? reinterpret_cast<P>(p + ReadScalar<OffsetSize>(p))
                        : nullptr;
  }
References GetOptionalFieldOffset(), and p.
Referenced by flatbuffers::GetFieldAnyV(), flatbuffers::GetFieldS(), flatbuffers::GetFieldT(), and flatbuffers::GetFieldV().
GetPointer() [2/2]
template<typename P , typename OffsetSize = uoffset_t> P flatbuffers::Table::GetPointer (voffset_t field) const inline
Definition at line 58 of file table.h.
{
    return const_cast<Table *>(this)->GetPointer<P, OffsetSize>(field);
  }
GetPointer64() [1/2]
template<typename P > P flatbuffers::Table::GetPointer64 (voffset_t field) inline
Definition at line 62 of file table.h.
{
    return GetPointer<P, uoffset64_t>(field);
  }
GetPointer64() [2/2]
template<typename P > P flatbuffers::Table::GetPointer64 (voffset_t field) const inline
Definition at line 66 of file table.h.
{
    return GetPointer<P, uoffset64_t>(field);
  }
GetStruct()
template<typename P > P flatbuffers::Table::GetStruct (voffset_t field) const inline
Definition at line 70 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    auto p = const_cast<uint8_t *>(data_ + field_offset);
    return field_offset ? reinterpret_cast<P>(p) : nullptr;
  }
References GetOptionalFieldOffset(), and p.
Referenced by flatbuffers::GetFieldStruct().
GetVTable()
const uint8_t * flatbuffers::Table::GetVTable () const inline
Definition at line 29 of file table.h.
{
    return data_ - ReadScalar<soffset_t>(data_);
  }
Referenced by flatbuffers::GetBufferStartFromRootPointer(), and GetOptionalFieldOffset().
SetField() [1/2]
template<typename T > bool flatbuffers::Table::SetField (voffset_t field, T val) inline
Definition at line 90 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    if (!field_offset) return false;
    WriteScalar(data_ + field_offset, val);
    return true;
  }
References GetOptionalFieldOffset().
SetField() [2/2]
template<typename T > bool flatbuffers::Table::SetField (voffset_t field, T val, T def) inline
Definition at line 84 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    if (!field_offset) return IsTheSameAs(val, def);
    WriteScalar(data_ + field_offset, val);
    return true;
  }
References GetOptionalFieldOffset().
Referenced by flatbuffers::SetField().
SetPointer()
bool flatbuffers::Table::SetPointer (voffset_t field, const uint8_t * val) inline
Definition at line 97 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    if (!field_offset) return false;
    WriteScalar(data_ + field_offset,
                static_cast<uoffset_t>(val - (data_ + field_offset)));
    return true;
  }
References GetOptionalFieldOffset().
Referenced by flatbuffers::SetFieldT().
VerifyField()
template<typename T > bool flatbuffers::Table::VerifyField (const Verifier & verifier, voffset_t field, size_t align) const inline
Definition at line 125 of file table.h.
{
    // Calling GetOptionalFieldOffset should be safe now thanks to
    // VerifyTable().
    auto field_offset = GetOptionalFieldOffset(field);
    // Check the actual field.
    return !field_offset || verifier.VerifyField<T>(data_, field_offset, align);
  }
References GetOptionalFieldOffset().
VerifyFieldRequired()
template<typename T > bool flatbuffers::Table::VerifyFieldRequired (const Verifier & verifier, voffset_t field, size_t align) const inline
Definition at line 136 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    return verifier.Check(field_offset != 0) &&
           verifier.VerifyField<T>(data_, field_offset, align);
  }
References GetOptionalFieldOffset().
VerifyOffset()
template<typename OffsetT = uoffset_t> bool flatbuffers::Table::VerifyOffset (const Verifier & verifier, voffset_t field) const inline
Definition at line 145 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    return !field_offset || verifier.VerifyOffset<OffsetT>(data_, field_offset);
  }
References GetOptionalFieldOffset().
VerifyOffset64()
bool flatbuffers::Table::VerifyOffset64 (const Verifier & verifier, voffset_t field) const inline
Definition at line 157 of file table.h.
{
    return VerifyOffset<uoffset64_t>(verifier, field);
  }
VerifyOffset64Required()
bool flatbuffers::Table::VerifyOffset64Required (const Verifier & verifier, voffset_t field) const inline
Definition at line 161 of file table.h.
{
    return VerifyOffsetRequired<uoffset64_t>(verifier, field);
  }
VerifyOffsetRequired()
template<typename OffsetT = uoffset_t> bool flatbuffers::Table::VerifyOffsetRequired (const Verifier & verifier, voffset_t field) const inline
Definition at line 151 of file table.h.
{
    auto field_offset = GetOptionalFieldOffset(field);
    return verifier.Check(field_offset != 0) &&
           verifier.VerifyOffset<OffsetT>(data_, field_offset);
  }
References GetOptionalFieldOffset().
VerifyTableStart()
bool flatbuffers::Table::VerifyTableStart (Verifier & verifier) const inline
Definition at line 119 of file table.h.
{
    return verifier.VerifyTableStart(data_);
  }
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/table.h