ONE - On-device Neural Engine: moco::TFSquaredDifference Class Reference
moco::TFSquaredDifference Class Reference final
#include <TFSquaredDifference.h>
Public Member Functions
TFSquaredDifference ()=default
Node * x (void) const
void x (Node *node)
Node * y (void) const
void y (Node *node)
Public Member Functions inherited from moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::SquaredDifference >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >
loco::Use * at (unsigned n) const
Detailed Description
Note
TFSquaredDifference corresponds to the following GraphDef
Definition at line 41 of file TFSquaredDifference.h.
Constructor & Destructor Documentation
TFSquaredDifference()
moco::TFSquaredDifference::TFSquaredDifference () default
Member Function Documentation
x() [1/2]
void moco::TFSquaredDifference::x (Node * node) inline
Definition at line 48 of file TFSquaredDifference.h.
{ at(0)->node(node); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >::at(), and loco::Use::node().
x() [2/2]
Node * moco::TFSquaredDifference::x (void) const inline
Definition at line 47 of file TFSquaredDifference.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >::at(), and loco::Use::node().
y() [1/2]
void moco::TFSquaredDifference::y (Node * node) inline
Definition at line 51 of file TFSquaredDifference.h.
{ at(1)->node(node); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >::at(), and loco::Use::node().
y() [2/2]
Node * moco::TFSquaredDifference::y (void) const inline
Definition at line 50 of file TFSquaredDifference.h.
{ return at(1)->node(); }
References moco::FixedArityNode< 2, TFNodeImpl< TFOpcode::SquaredDifference > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFSquaredDifference.h