ONE - On-device Neural Engine: luci::Dilation Class Reference
luci::Dilation Class Reference final
#include <AttrDilation.h>
Public Member Functions
Dilation ()
uint32_t w () const
void w (uint32_t w)
void w (int32_t w)
uint32_t h () const
void h (uint32_t h)
void h (int32_t h)
Detailed Description
Definition at line 25 of file AttrDilation.h.
Constructor & Destructor Documentation
Dilation()
luci::Dilation::Dilation () inline
Definition at line 28 of file AttrDilation.h.
: _w(1), _h(1) {}
Member Function Documentation
h() [1/3]
uint32_t luci::Dilation::h () const inline
Definition at line 34 of file AttrDilation.h.
{ return _h; }
Referenced by h(), luci::CloneNodeLet< CN::ABC >::visit(), luci::CloneNodeLet< CN::DEF >::visit(), and luci::BuiltinOptionsExtractor::visit().
h() [2/3]
void luci::Dilation::h (int32_t h)
Definition at line 30 of file AttrDilation.cpp.
{
  assert(h >= 0);
  _h = static_cast<uint32_t>(h);
}
References h().
h() [3/3]
void luci::Dilation::h (uint32_t h) inline
Definition at line 35 of file AttrDilation.h.
{ _h = h; }
References h().
Referenced by h().
w() [1/3]
uint32_t luci::Dilation::w () const inline
Definition at line 30 of file AttrDilation.h.
{ return _w; }
Referenced by luci::CloneNodeLet< CN::ABC >::visit(), luci::CloneNodeLet< CN::DEF >::visit(), luci::BuiltinOptionsExtractor::visit(), and w().
w() [2/3]
void luci::Dilation::w (int32_t w)
Definition at line 24 of file AttrDilation.cpp.
{
  assert(w >= 0);
  _w = static_cast<uint32_t>(w);
}
References w().
w() [3/3]
void luci::Dilation::w (uint32_t w) inline
Definition at line 31 of file AttrDilation.h.
{ _w = w; }
References w().
Referenced by w().
The documentation for this class was generated from the following files:
compiler/luci/lang/include/luci/IR/AttrDilation.h
compiler/luci/lang/src/AttrDilation.cpp