ONE - On-device Neural Engine: moco::onnx::ConstantGraphBuilder Class Reference
moco::onnx::ConstantGraphBuilder Class Reference
GraphBuilder for Constant node.
#include <Constant.h>
Public Member Functions
bool validate (OpsetVersion, const ::onnx::NodeProto &) const
void build (OpsetVersion, const ::onnx::NodeProto &, GraphBuilderContext *) const
Public Member Functions inherited from moco::onnx::GraphBuilder
virtual bool validate (OpsetVersion, const ::onnx::NodeProto &) const
virtual void build (OpsetVersion, const ::onnx::NodeProto &, GraphBuilderContext *) const =0
virtual ~GraphBuilder ()
Additional Inherited Members
Public Types inherited from moco::onnx::GraphBuilder
using OpsetVersion = int64_t
Detailed Description
GraphBuilder for Constant node.
Definition at line 51 of file Constant.h.
Member Function Documentation
build()
void moco::onnx::ConstantGraphBuilder::build (OpsetVersion opset_version, const ::onnx::NodeProto & node, GraphBuilderContext * context) const virtual
Implements moco::onnx::GraphBuilder.
Definition at line 36 of file Constant.cpp.
{
  if (opset_version >= 9)
    Constant_V9().build(node, context);
  else if (opset_version >= 1)
    Constant_V1().build(node, context);
  else
    throw std::runtime_error("Invalid ONNX IR version");
}
References moco::onnx::Constant_V1::build(), and moco::onnx::Constant_V9::build().
validate()
bool moco::onnx::ConstantGraphBuilder::validate (OpsetVersion opset_version, const ::onnx::NodeProto & node) const virtual
Reimplemented from moco::onnx::GraphBuilder.
Definition at line 26 of file Constant.cpp.
{
  if (opset_version >= 9)
    return Constant_V9().validate(node);
  else if (opset_version >= 1)
    return Constant_V1().validate(node);
  else
    throw std::runtime_error("Invalid ONNX IR version");
}
References moco::onnx::Constant_V1::validate(), and moco::onnx::Constant_V9::validate().
The documentation for this class was generated from the following files:
compiler/oneco/src/Op/Constant.h
compiler/oneco/src/Op/Constant.cpp