ONE - On-device Neural Engine: nnfw::cker::DynamicUpdateSlice Class Reference
nnfw::cker::DynamicUpdateSlice Class Reference
#include <DynamicUpdateSlice.h>
Public Member Functions
DynamicUpdateSlice ()=default
~DynamicUpdateSlice ()=default
template<typename T >
void operator() (const Shape &input_shape, const T *input_data, const Shape &update_shape, const T *update_data, const std::vector< int64_t > &indices_data, T *output_data)
Detailed Description
Definition at line 28 of file DynamicUpdateSlice.h.
Constructor & Destructor Documentation
DynamicUpdateSlice()
nnfw::cker::DynamicUpdateSlice::DynamicUpdateSlice () default
~DynamicUpdateSlice()
nnfw::cker::DynamicUpdateSlice::~DynamicUpdateSlice () default
References nnfw::cker::Shape::Dims().
Member Function Documentation
operator()()
template<typename T > void nnfw::cker::DynamicUpdateSlice::operator() (const Shape & input_shape, const T * input_data, const Shape & update_shape, const T * update_data, const std::vector< int64_t > & indices_data, T * output_data) inline
Definition at line 62 of file DynamicUpdateSlice.h.
  {
    // Special case 1 : output is copy of update
    if (input_shape == update_shape)
    {
      memcpy(output_data, update_data, update_shape.FlatSize() * sizeof(T));
      return;
    }
    // Prepare update
    if (input_data != output_data)
      memcpy(output_data, input_data, input_shape.FlatSize() * sizeof(T));
    // Special case 2: no update
    if (update_shape.FlatSize() == 0)
      return;
    // Calculate clamped_start_indices
    const auto input_dims = input_shape.DimensionsCount();
    std::vector<int64_t> clamped_start_indices(input_dims, 0);
    assert(input_dims == update_shape.DimensionsCount());
    for (int i = 0; i < input_dims; i++)
    {
      clamped_start_indices[i] = std::min<int64_t>(std::max<int64_t>(0, indices_data[i]),
                                                   input_shape.Dims(i) - update_shape.Dims(i));
    }
    // Calculate strides
    std::vector<int32_t> output_stride(input_dims);
    std::vector<int32_t> update_stride(input_dims);
    output_stride[input_dims - 1] = 1;
    update_stride[input_dims - 1] = 1;
    for (int i = input_dims - 2; i >= 0; --i)
    {
      output_stride[i] = output_stride[i + 1] * input_shape.Dims(i + 1);
      update_stride[i] = update_stride[i + 1] * update_shape.Dims(i + 1);
    }
    UpdateSlice<T>(0, input_dims, output_stride, update_stride, update_shape, update_data,
                   clamped_start_indices, output_data);
  }
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), and nnfw::cker::Shape::FlatSize().
The documentation for this class was generated from the following file:
runtime/compute/cker/include/cker/operation/DynamicUpdateSlice.h