ONE - On-device Neural Engine: tflchef::TFliteOpBidirectionalSequenceLSTM Class Reference
tflchef::TFliteOpBidirectionalSequenceLSTM Class Reference
tflchef operator builder for BidirectionalSequenceLSTM
#include <BidirectionalSequenceLSTM.h>
Public Member Functions
void filler (const tflite::Operator *op, TFliteImport *import, tflchef::ModelRecipe *model_recipe) const override
tflchef::Operation * build (const tflite::Operator *op, TFliteImport *import, tflchef::ModelRecipe *model_recipe) const override
Public Member Functions inherited from tflchef::TFliteOpChef
virtual void filler (const tflite::Operator *op, TFliteImport *import, tflchef::ModelRecipe *model_recipe) const =0
virtual ::tflchef::Operation * build (const tflite::Operator *op, TFliteImport *import, tflchef::ModelRecipe *model_recipe) const =0
virtual ~TFliteOpChef ()
Detailed Description
tflchef operator builder for BidirectionalSequenceLSTM
Definition at line 28 of file BidirectionalSequenceLSTM.h.
Member Function Documentation
build()
tflchef::Operation * tflchef::TFliteOpBidirectionalSequenceLSTM::build (const tflite::Operator * op, TFliteImport * import, tflchef::ModelRecipe * model_recipe) const override virtual
Implements tflchef::TFliteOpChef.
Definition at line 45 of file BidirectionalSequenceLSTM.cpp.
{
  auto op_params = op->builtin_options_as_BidirectionalSequenceLSTMOptions();
  assert(op_params != nullptr);
  auto operation = model_recipe->add_operation();
  operation->set_type("BidirectionalSequenceLSTM");
  auto op_options = operation->mutable_bidirectional_sequence_lstm_options();
  op_options->set_activation(as_tflchef_activation(op_params->fused_activation_function()));
  op_options->set_cell_clip(op_params->cell_clip());
  op_options->set_proj_clip(op_params->proj_clip());
  op_options->set_time_major(op_params->time_major());
  op_options->set_asymmetric_quantize_inputs(op_params->asymmetric_quantize_inputs());
  op_options->set_merge_outputs(op_params->merge_outputs());
  return operation;
}
References tflchef::as_tflchef_activation().
filler()
void tflchef::TFliteOpBidirectionalSequenceLSTM::filler (const tflite::Operator * op, TFliteImport * import, tflchef::ModelRecipe * model_recipe) const override virtual
Implements tflchef::TFliteOpChef.
Definition at line 25 of file BidirectionalSequenceLSTM.cpp.
{
  const std::vector<int32_t> &inputs = as_index_vector(op->inputs());
  assert(inputs.size() == 48);
  for (int32_t i = 0; i < inputs.size(); i++)
  {
    // Except for Input 0, 35, 36, 37 and 38.
    // Each Input mean Input Tensor, ActivationState Tensor (forward and backward), and CellState
    // Tensor (forward and backward).
    // This could be updated from previous input or User Given data, so This could not be Const
    if (i == 0 || i == 35 || i == 36 || i == 37 || i == 38)
      continue;
    if (inputs[i] != -1)
      fill_tensor_to_import(inputs[i], import);
  }
}
References tflchef::as_index_vector(), and tflchef::fill_tensor_to_import().
The documentation for this class was generated from the following files:
compiler/tflchef/tflite/src/Op/include/BidirectionalSequenceLSTM.h
compiler/tflchef/tflite/src/Op/BidirectionalSequenceLSTM.cpp