ONE - On-device Neural Engine: mir::Operation Class Reference
mir::Operation Class Reference abstract
#include <Operation.h>
Data Structures
class Output
Represents an output of a node.
struct Use
Represents a use of an operation output.
Public Types
enum class Type { HANDLE_OP }
Public Member Functions
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Protected Member Functions
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Definition at line 32 of file Operation.h.
Member Enumeration Documentation
Type
enum class mir::Operation::Type strong
Enumerator
HANDLE_OP
Definition at line 35 of file Operation.h.
  {
#define HANDLE_OP(OpType, OpClass) OpType,
#include "mir/Operations.inc"
#undef HANDLE_OP
  };
Constructor & Destructor Documentation
~Operation()
virtual mir::Operation::~Operation () virtual default
Operation()
Operation::Operation (Type type, const std::vector< Output * > & inputs, std::size_t num_outputs = 1) protected
Definition at line 42 of file Operation.cpp.
  : _type(type)
{
  for (std::size_t i = 0; i < inputs.size(); ++i)
  {
    inputs[i]->addUse(Use(this, i));
    _inputs.push_back(inputs[i]);
  }
  for (std::size_t i = 0; i < num_outputs; ++i)
  {
    _outputs.emplace_back(this, i);
  }
}
Member Function Documentation
accept()
void Operation::accept (IVisitor * v)
Definition at line 56 of file Operation.cpp.
{
  switch (getType())
  {
#define HANDLE_OP(OpType, OpClass)                 \
  case Type::OpType:                               \
    v->visit(dynamic_cast<ops::OpClass &>(*this)); \
    break;
#include "mir/Operations.inc"
#undef HANDLE_OP
    default:
      assert(false && "OP not defined!");
  }
}
References getType().
Referenced by mir_onnx::foldConstants(), and nnc::Serializer::serialize().
copyWithInputs()
virtual Operation * mir::Operation::copyWithInputs (const std::vector< Output * > & inputs) pure virtual
Implemented in mir::ops::ReluOp, mir::ops::TransposeOp, mir::ops::InputOp, mir::ops::AbsOp, mir::ops::AddOp, mir::ops::AvgPool2DOp, mir::ops::BroadcastOp, mir::ops::CappedReluOp, mir::ops::ConcatOp, mir::ops::Conv2DOp, mir::ops::DeConv2DOp, mir::ops::DepthwiseConv2DOp, mir::ops::DequantizeOp, mir::ops::DivOp, mir::ops::EluOp, mir::ops::EqualOp, mir::ops::FullyConnectedOp, mir::ops::GatherOp, mir::ops::GreaterOp, mir::ops::HardSwishOp, mir::ops::LeakyReluOp, mir::ops::LessOp, mir::ops::MaxOp, mir::ops::MaxPool2DOp, mir::ops::MulOp, mir::ops::OutputOp, mir::ops::PadOp, mir::ops::QuantizeOp, mir::ops::ReduceMeanOp, mir::ops::ReshapeOp, mir::ops::ResizeOp, mir::ops::SigmoidOp, mir::ops::SliceOp, mir::ops::SoftmaxOp, mir::ops::SqrtOp, mir::ops::SqueezeOp, mir::ops::SubOp, and mir::ops::TanhOp.
Referenced by mir::Graph::copyOpWithInputs().
getId()
std::size_t mir::Operation::getId () const inline
Definition at line 125 of file Operation.h.
{ return _id; }
Referenced by mir::DotNodeBuilder::DotNodeBuilder(), and nnc::DumpVisitor::visit().
getInput() [1/2]
Output * mir::Operation::getInput (std::size_t index) inline
Definition at line 137 of file Operation.h.
  {
    assert(index < _inputs.size());
    return _inputs[index];
  }
Referenced by getInputShape(), mir::ops::SqueezeOp::inferOutputTypes(), mir::Graph::removeNode(), nnc::CombineTransposes::run(), mir2loco::Transformer::visit(), mir_interpreter::MIRInterpreter::visit(), and nnc::AclCppOpGenerator::visit().
getInput() [2/2]
const Output * mir::Operation::getInput (std::size_t index) const inline
Definition at line 143 of file Operation.h.
  {
    assert(index < _inputs.size());
    return _inputs[index];
  }
getInputs() [1/2]
std::deque< Output * > & mir::Operation::getInputs () inline
Definition at line 131 of file Operation.h.
{ return _inputs; }
Referenced by mir_onnx::foldConstants(), nnc::opt_util::swapAdjacent(), and nnc::AclCppOpGenerator::visit().
getInputs() [2/2]
const std::deque< Output * > & mir::Operation::getInputs () const inline
Definition at line 132 of file Operation.h.
{ return _inputs; }
getInputShape()
const Shape & mir::Operation::getInputShape (std::size_t index) const inline
Definition at line 161 of file Operation.h.
{ return getInput(index)->getShape(); }
References getInput(), and mir::Operation::Output::getShape().
Referenced by mir::DotNodeBuilder::DotNodeBuilder(), mir::ops::EqualOp::EqualOp(), mir::ops::ConcatOp::getAxis(), mir::ops::SoftmaxOp::getAxis(), mir::ops::GreaterOp::GreaterOp(), mir::ops::SqueezeOp::inferOutputTypes(), mir::ops::LessOp::LessOp(), mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir_interpreter::PadImpl< T >::run(), mir_interpreter::ReduceMeanImpl< T >::run(), TEST(), nnc::ModelAnalyzer::visit(), and nnc::Serializer::visit().
getNumInputs()
std::size_t mir::Operation::getNumInputs () const inline
Definition at line 128 of file Operation.h.
{ return _inputs.size(); }
Referenced by mir::Graph::copyOpWithInputs(), mir::DotNodeBuilder::DotNodeBuilder(), mir::getSortedNodes(), mir::ops::SqueezeOp::inferOutputTypes(), mir::Graph::removeNode(), nnc::opt_util::swapAdjacent(), mir2loco::Transformer::visit(), nnc::ModelAnalyzer::visit(), and nnc::AclCppOpGenerator::visit().
getNumOutputs()
std::size_t mir::Operation::getNumOutputs () const inline
Definition at line 129 of file Operation.h.
{ return _outputs.size(); }
Referenced by mir::DotNodeBuilder::DotNodeBuilder(), mir_onnx::foldConstants(), and nnc::opt_util::swapAdjacent().
getOutput() [1/2]
Output * mir::Operation::getOutput (std::size_t index) inline
Definition at line 149 of file Operation.h.
  {
    assert(index < _outputs.size());
    return &_outputs[index];
  }
Referenced by mir_onnx::foldConstants(), getOutputShape(), nnc::opt_util::removeNodeIfUnused(), mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), setOutputType(), TEST(), mir2loco::Transformer::visit(), nnc::AclCppOpGenerator::visit(), nnc::ModelAnalyzer::visit(), and mir_interpreter::MIRInterpreter::visit().
getOutput() [2/2]
const Output * mir::Operation::getOutput (std::size_t index) const inline
Definition at line 155 of file Operation.h.
  {
    assert(index < _outputs.size());
    return &_outputs[index];
  }
getOutputs() [1/2]
std::deque< Output > & mir::Operation::getOutputs () inline
Definition at line 134 of file Operation.h.
{ return _outputs; }
Referenced by nnc::ModelAnalyzer::analyze(), mir::getSortedNodes(), mir::Graph::removeNode(), and nnc::opt_util::swapAdjacent().
getOutputs() [2/2]
const std::deque< Output > & mir::Operation::getOutputs () const inline
Definition at line 135 of file Operation.h.
{ return _outputs; }
getOutputShape()
const Shape & mir::Operation::getOutputShape (std::size_t index) const inline
Definition at line 163 of file Operation.h.
{ return getOutput(index)->getShape(); }
References getOutput(), and mir::Operation::Output::getShape().
Referenced by mir::ops::BroadcastOp::copyWithInputs(), mir::ops::DeConv2DOp::copyWithInputs(), mir::ops::ReshapeOp::copyWithInputs(), mir::ops::ResizeOp::copyWithInputs(), mir::DotNodeBuilder::DotNodeBuilder(), mir_interpreter::AvgPool2DImpl< uint8_t >::run(), mir_interpreter::AvgPool2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< T >::run(), mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run(), mir_interpreter::MaxPool2DImpl< uint8_t >::run(), mir_interpreter::TransposeImpl< T >::run(), mir_interpreter::MaxPool2DImpl< T >::run(), mir_interpreter::ReduceMeanImpl< T >::run(), mir_interpreter::FullyConnectedImpl< uint8_t >::run(), nnc::ConstantFoldTranspose::run(), TEST(), mir_interpreter::MIRInterpreter::visit(), nnc::Serializer::visit(), mir2loco::Transformer::visit(), and nnc::ModelAnalyzer::visit().
getType()
Type mir::Operation::getType () const inline
Definition at line 123 of file Operation.h.
{ return _type; }
Referenced by accept(), mir::DotNodeBuilder::DotNodeBuilder(), mir_onnx::foldConstants(), and mir::Graph::removeNode().
setId()
void mir::Operation::setId (std::size_t id) inline
Definition at line 126 of file Operation.h.
{ _id = id; }
Referenced by mir::Graph::copyOpWithInputs().
setOutputType()
void mir::Operation::setOutputType (std::size_t index, const TensorType & type) inline protected
Definition at line 172 of file Operation.h.
{ getOutput(index)->setType(type); }
References getOutput(), and mir::Operation::Output::setType().
Referenced by mir::ops::EqualOp::EqualOp(), mir::ops::GreaterOp::GreaterOp(), mir::ops::SqueezeOp::inferOutputTypes(), and mir::ops::LessOp::LessOp().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/Operation.h
compiler/mir/src/Operation.cpp