ONE - On-device Neural Engine: flatbuffers::pointer_inside_vector< T, U > Class Template Reference
flatbuffers::pointer_inside_vector< T, U > Class Template Reference
#include <reflection.h>
Public Member Functions
pointer_inside_vector (T *ptr, std::vector< U > &vec)
T * operator* () const
T * operator-> () const
Detailed Description
template<typename T, typename U>
class flatbuffers::pointer_inside_vector< T, U >
Definition at line 392 of file reflection.h.
Constructor & Destructor Documentation
pointer_inside_vector()
template<typename T , typename U > flatbuffers::pointer_inside_vector< T, U >::pointer_inside_vector (T * ptr, std::vector< U > & vec) inline
Definition at line 395 of file reflection.h.
    : offset_(reinterpret_cast<uint8_t *>(ptr) -
              reinterpret_cast<uint8_t *>(flatbuffers::vector_data(vec))),
      vec_(vec)
  {
  }
Member Function Documentation
operator*()
template<typename T , typename U > T * flatbuffers::pointer_inside_vector< T, U >::operator* () const inline
Definition at line 402 of file reflection.h.
  {
    return reinterpret_cast<T *>(reinterpret_cast<uint8_t *>(flatbuffers::vector_data(vec_)) +
                                 offset_);
  }
References flatbuffers::vector_data().
Referenced by flatbuffers::pointer_inside_vector< T, U >::operator->().
operator->()
template<typename T , typename U > T * flatbuffers::pointer_inside_vector< T, U >::operator-> () const inline
Definition at line 407 of file reflection.h.
{ return operator*(); }
References flatbuffers::pointer_inside_vector< T, U >::operator*().
The documentation for this class was generated from the following file:
onert-micro/externals/flatbuffers/reflection.h