ONE - On-device Neural Engine: moco::ResolveSquaredDifference Class Reference
moco::ResolveSquaredDifference Class Reference
Decompose TFSquaredDifference to TFSub, TFMul.
#include <ResolveSquaredDifference.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *graph) override
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Decompose TFSquaredDifference to TFSub, TFMul.
Definition at line 30 of file ResolveSquaredDifference.h.
Member Function Documentation
name()
const char * moco::ResolveSquaredDifference::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 33 of file ResolveSquaredDifference.h.
{ return "ResolveSquaredDifference"; }
run()
bool moco::ResolveSquaredDifference::run (loco::Graph * graph) override virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 74 of file ResolveSquaredDifference.cpp.
{
  auto active_nodes = loco::active_nodes(loco::output_nodes(graph));
  bool changed = false;
  for (auto node : active_nodes)
  {
    if (node->dialect() == TFDialect::get())
    {
      auto tf_node = dynamic_cast<moco::TFSquaredDifference *>(node);
      if (tf_node != nullptr)
      {
        if (decompose_sqdiff(tf_node))
          changed = true;
      }
    }
  }
  return changed;
}
References loco::active_nodes(), moco::TFNode::dialect(), moco::TFDialect::get(), and loco::output_nodes().
The documentation for this class was generated from the following files:
compiler/moco/pass/include/moco/Pass/Passes/ResolveSquaredDifference.h
compiler/moco/pass/src/Passes/ResolveSquaredDifference.cpp