ONE - On-device Neural Engine: onert::compiler::train::pass::LossInsertionPass Class Reference
onert::compiler::train::pass::LossInsertionPass Class Reference
#include <LossInsertionPass.h>
Public Member Functions
LossInsertionPass (ir::train::TrainableGraph &trainable_graph, const TrainingInfo *training_info, const ir::SubgraphIndex &subg_index)
std::string id () final
void run () final
Public Member Functions inherited from onert::compiler::train::pass::Pass
Pass (ir::train::TrainableGraph &trainable_graph, const TrainingInfo *training_info)
virtual ~Pass ()=default
Public Member Functions inherited from onert::compiler::pass::IPass
virtual ~IPass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::train::pass::Pass
ir::train::TrainableGraph & _trainable_graph
const TrainingInfo * _training_info
Detailed Description
Definition at line 33 of file LossInsertionPass.h.
Constructor & Destructor Documentation
LossInsertionPass()
onert::compiler::train::pass::LossInsertionPass::LossInsertionPass (ir::train::TrainableGraph & trainable_graph, const TrainingInfo * training_info, const ir::SubgraphIndex & subg_index) inline
Definition at line 36 of file LossInsertionPass.h.
    : Pass{trainable_graph, training_info}, _subg_index{subg_index}
  {
  }
Member Function Documentation
id()
std::string onert::compiler::train::pass::LossInsertionPass::id () inline final virtual
Implements onert::compiler::pass::IPass.
Definition at line 43 of file LossInsertionPass.h.
{ return "LossInsertionPass"; }
run()
void onert::compiler::train::pass::LossInsertionPass::run () final virtual
Implements onert::compiler::pass::IPass.
Definition at line 31 of file LossInsertionPass.cc.
{
  const auto &loss_info = _training_info->lossInfo();
  if (_trainable_graph.getOutputs().size() != 1)
  {
    throw std::runtime_error("LossInsertionPass: Not supported multiple outputs");
  }
  // TODO Consider SparseCategoricalCrossentropy y_true shape
  //      SparseCategoricalCrossentropy loss has a different y_true shape than y_pred.
  // TODO Implement Loop [0, getOutputs().size())
  //      index: a loop index
  const auto index = 0;
  const auto &y_pred_index = _trainable_graph.getOutputs().at(index);
  const auto &y_pred = _trainable_graph.operands().at(y_pred_index);
  auto y_true_index = _trainable_graph.addOperand(y_pred.shape(), y_pred.typeInfo());
  ir::OperandIndexSequence inputs{y_pred_index, y_true_index};
  ir::Shape output_shape;
  if (loss_info.reduction_type == ir::train::LossReductionType::Sum ||
      loss_info.reduction_type == ir::train::LossReductionType::SumOverBatchSize)
  {
    output_shape = ir::Shape{1};
  }
  else
  {
    throw std::runtime_error("LossInsertionPass: Not supported reduction type");
  }
  const ir::TypeInfo float_op(ir::DataType::FLOAT32);
  auto output_index = _trainable_graph.addOperand(output_shape, float_op);
  ir::OperandIndexSequence outputs{output_index};
  auto loss_op = std::make_unique<ir::operation::Loss>(inputs, outputs);
  auto trainable_loss_op = std::make_unique<ir::train::operation::Loss>(*loss_op, loss_info);
  _trainable_graph.addOperation(std::move(trainable_loss_op));
  _trainable_graph.addInput(y_true_index);
  // TODO Add loss as many as output size
  _trainable_graph.addLoss(output_index, ir::IOIndex{index});
}
References onert::compiler::train::pass::Pass::_trainable_graph, onert::compiler::train::pass::Pass::_training_info, onert::ir::train::TrainableGraph::addInput(), onert::ir::train::TrainableGraph::addLoss(), onert::ir::train::TrainableGraph::addOperand(), onert::ir::train::TrainableGraph::addOperation(), onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::train::TrainableGraph::getOutputs(), onert::compiler::train::TrainingInfo::lossInfo(), onert::ir::train::TrainableGraph::operands(), output_shape, onert::ir::OperandIndexSequence::size(), onert::ir::train::Sum, and onert::ir::train::SumOverBatchSize.
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/train/pass/LossInsertionPass.h
runtime/onert/core/src/compiler/train/pass/LossInsertionPass.cc