ONE - On-device Neural Engine: tflimport::TensorBags Class Reference
tflimport::TensorBags Class Reference
Pre-creates coco:Bags for each operands(tensors)
#include <TensorBags.h>
Public Member Functions
void prepare (const tflite::SubGraph *graph, std::unique_ptr< coco::Module > &m)
coco::Bag * bag (int32_t tensor_id)
std::map< uint32_t, coco::Bag * >::iterator begin ()
std::map< uint32_t, coco::Bag * >::iterator end ()
Detailed Description
Pre-creates coco:Bags for each operands(tensors)
Definition at line 37 of file TensorBags.h.
Member Function Documentation
bag()
coco::Bag * tflimport::TensorBags::bag (int32_t tensor_id) inline
Definition at line 52 of file TensorBags.h.
{ return _bag_ctx[tensor_id]; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::set_module_inputs(), and tflimport::set_module_outputs().
begin()
std::map< uint32_t, coco::Bag * >::iterator tflimport::TensorBags::begin () inline
Definition at line 55 of file TensorBags.h.
{ return _bag_ctx.begin(); }
end()
std::map< uint32_t, coco::Bag * >::iterator tflimport::TensorBags::end () inline
Definition at line 57 of file TensorBags.h.
{ return _bag_ctx.end(); }
prepare()
void tflimport::TensorBags::prepare (const tflite::SubGraph * graph, std::unique_ptr< coco::Module > & m) inline
Definition at line 40 of file TensorBags.h.
  {
    for (uint32_t tensor_id = 0; tensor_id < graph->tensors()->size(); ++tensor_id)
    {
      auto const tensor_info = graph->tensors()->Get(tensor_id);
      auto const tensor_shape = as_tensor_shape(tensor_info->shape());
      auto const tensor_bag = m->entity()->bag()->create(num_elements(tensor_shape));
      _bag_ctx[tensor_id] = tensor_bag;
    }
  }
References tflimport::as_tensor_shape(), and m.
The documentation for this class was generated from the following file:
compiler/enco/frontend/tflite/src/TensorBags.h