ONE - On-device Neural Engine: onert::exec::IPermuteFunction Class Reference
onert::exec::IPermuteFunction Class Reference abstract
#include <IPermuteFunction.h>
Public Member Functions
virtual void run () override
virtual void prepare () override
virtual void optimize ()=0
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Protected Types
enum class PermuteType { NHWC_TO_NCHW , NCHW_TO_NHWC , COPY }
Protected Member Functions
void permute (backend::ITensor *src_tensor, backend::ITensor *dst_tensor, size_t rank, std::vector< size_t > &src_offsets, std::vector< size_t > &dst_offsets)
const std::type_info & underlying_type (ir::DataType type) const
Protected Attributes
std::vector< backend::ITensor * > _src_tensors
std::vector< backend::ITensor * > _dst_tensors
std::vector< std::vector< size_t > > _src_tensors_offsets
std::vector< std::vector< size_t > > _dst_tensors_offsets
std::unordered_map< const backend::ITensor *, std::vector< uint8_t > > _buffers_map
Detailed Description
Definition at line 71 of file IPermuteFunction.h.
Member Enumeration Documentation
PermuteType
enum class onert::exec::IPermuteFunction::PermuteType strong protected
Enumerator
NHWC_TO_NCHW
NCHW_TO_NHWC
COPY
Definition at line 74 of file IPermuteFunction.h.
  {
    NHWC_TO_NCHW,
    NCHW_TO_NHWC,
    COPY
  };
Member Function Documentation
optimize()
virtual void onert::exec::IPermuteFunction::optimize () pure virtual
Implemented in onert::backend::builtin::kernel::PermuteLayer.
Referenced by prepare().
permute()
void onert::exec::IPermuteFunction::permute (backend::ITensor * src_tensor, backend::ITensor * dst_tensor, size_t rank, std::vector< size_t > & src_offsets, std::vector< size_t > & dst_offsets) inline protected
Definition at line 113 of file IPermuteFunction.h.
  {
    if (src_tensor->total_size() == 0)
    {
      assert(dst_tensor->total_size() == 0);
      return;
    }
    assert(src_tensor != dst_tensor);
    if (underlying_type(src_tensor->data_type()) != underlying_type(dst_tensor->data_type()))
      throw std::runtime_error("data type does not match");
    switch (src_tensor->data_type())
    {
      case ir::DataType::FLOAT32:
        permute<float>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::INT32:
        permute<int32_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::UINT32:
        permute<uint32_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::BOOL8:
      case ir::DataType::QUANT_UINT8_ASYMM:
      case ir::DataType::UINT8:
        permute<uint8_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::QUANT_INT8_ASYMM:
      case ir::DataType::QUANT_INT8_SYMM:
        permute<int8_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::INT64:
        permute<int64_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      case ir::DataType::QUANT_INT16_SYMM:
        permute<int16_t>(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
        break;
      default:
        throw std::runtime_error("IPermuteFunction: Not supported data type");
        break;
    }
  }
References onert::backend::ITensor::data_type(), onert::backend::ITensor::total_size(), and underlying_type().
Referenced by onert::backend::builtin::kernel::PermuteLayer::run(), and run().
prepare()
virtual void onert::exec::IPermuteFunction::prepare () inline override virtual
Reimplemented from onert::exec::IFunction.
Definition at line 108 of file IPermuteFunction.h.
{ optimize(); }
References optimize().
run()
virtual void onert::exec::IPermuteFunction::run () inline override virtual
Implements onert::exec::IFunction.
Reimplemented in onert::backend::builtin::kernel::PermuteLayer.
Definition at line 82 of file IPermuteFunction.h.
  {
    // TODO Optimization : Make control does not reach here? when (_src_tensors.size() == 0)
    assert(_src_tensors.size() == _dst_tensors.size());
    if (_src_tensors_offsets.size() == 0)
    {
      _src_tensors_offsets.resize(_src_tensors.size());
      _dst_tensors_offsets.resize(_dst_tensors.size());
    }
    assert(_src_tensors.size() == _src_tensors_offsets.size());
    assert(_src_tensors_offsets.size() == _dst_tensors_offsets.size());
    for (size_t i = 0; i < _src_tensors.size(); ++i)
    {
      auto src_tensor = _src_tensors.at(i);
      auto dst_tensor = _dst_tensors.at(i);
      auto &src_offsets = _src_tensors_offsets.at(i);
      auto &dst_offsets = _dst_tensors_offsets.at(i);
      if (src_tensor != dst_tensor)
      {
        const auto rank = src_tensor->getShape().rank();
        permute(src_tensor, dst_tensor, rank, src_offsets, dst_offsets);
      }
    }
  }
References _dst_tensors, _dst_tensors_offsets, _src_tensors, _src_tensors_offsets, and permute().
underlying_type()
const std::type_info & onert::exec::IPermuteFunction::underlying_type (ir::DataType type) const inline protected
Definition at line 325 of file IPermuteFunction.h.
  {
    switch (type)
    {
      case ir::DataType::FLOAT32:
        return typeid(float);
      case ir::DataType::INT32:
        return typeid(int32_t);
      case ir::DataType::UINT32:
        return typeid(uint32_t);
      case ir::DataType::INT64:
        return typeid(int64_t);
      case ir::DataType::BOOL8:
      case ir::DataType::QUANT_UINT8_ASYMM:
      case ir::DataType::UINT8:
        return typeid(uint8_t);
      case ir::DataType::QUANT_INT8_ASYMM:
      case ir::DataType::QUANT_INT8_SYMM:
        return typeid(int8_t);
      case ir::DataType::QUANT_INT16_SYMM:
        return typeid(int16_t);
      default:
        throw std::runtime_error("IPermuteFunction: Not supported data type");
    }
  }
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize(), and permute().
Field Documentation
_buffers_map
std::unordered_map<const backend::ITensor *, std::vector<uint8_t> > onert::exec::IPermuteFunction::_buffers_map protected
Definition at line 356 of file IPermuteFunction.h.
Referenced by onert::backend::builtin::kernel::PermuteLayer::run().
_dst_tensors
std::vector<backend::ITensor *> onert::exec::IPermuteFunction::_dst_tensors protected
Definition at line 353 of file IPermuteFunction.h.
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize(), onert::backend::builtin::kernel::PermuteLayer::PermuteLayer(), onert::backend::builtin::kernel::PermuteLayer::run(), and run().
_dst_tensors_offsets
std::vector<std::vector<size_t> > onert::exec::IPermuteFunction::_dst_tensors_offsets protected
Definition at line 355 of file IPermuteFunction.h.
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize(), onert::backend::builtin::kernel::PermuteLayer::PermuteLayer(), onert::backend::builtin::kernel::PermuteLayer::run(), and run().
_src_tensors
std::vector<backend::ITensor *> onert::exec::IPermuteFunction::_src_tensors protected
Definition at line 352 of file IPermuteFunction.h.
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize(), onert::backend::builtin::kernel::PermuteLayer::PermuteLayer(), onert::backend::builtin::kernel::PermuteLayer::run(), and run().
_src_tensors_offsets
std::vector<std::vector<size_t> > onert::exec::IPermuteFunction::_src_tensors_offsets protected
Definition at line 354 of file IPermuteFunction.h.
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize(), onert::backend::builtin::kernel::PermuteLayer::PermuteLayer(), onert::backend::builtin::kernel::PermuteLayer::run(), and run().
The documentation for this class was generated from the following file:
runtime/onert/core/src/exec/IPermuteFunction.h