ONE - On-device Neural Engine: coco::InstrIndex Class Reference
coco::InstrIndex Class Reference final
A InstrIndex denotes the index of an instruction in an instruction list.
#include <InstrIndex.h>
Public Member Functions
InstrIndex ()
InstrIndex (uint32_t value)
bool valid (void) const
uint32_t value (void) const
void set (uint32_t value)
void reset (void)
Detailed Description
A InstrIndex denotes the index of an instruction in an instruction list.
Definition at line 28 of file InstrIndex.h.
Constructor & Destructor Documentation
InstrIndex() [1/2]
coco::InstrIndex::InstrIndex () inline
Definition at line 34 of file InstrIndex.h.
               : _value{undefined}
  {
    // DO NOTHING
  }
InstrIndex() [2/2]
coco::InstrIndex::InstrIndex (uint32_t value) inline
Definition at line 40 of file InstrIndex.h.
{ set(value); }
References set(), and value().
Member Function Documentation
reset()
void coco::InstrIndex::reset (void) inline
Definition at line 50 of file InstrIndex.h.
{ _value = undefined; }
Referenced by coco::DLinkedList< Child, Parent >::leaving().
set()
void coco::InstrIndex::set (uint32_t value)
Definition at line 24 of file InstrIndex.cpp.
{
  assert(value != undefined);
  _value = value;
}
References value().
Referenced by InstrIndex().
valid()
bool coco::InstrIndex::valid (void) const inline
Definition at line 43 of file InstrIndex.h.
{ return _value != undefined; }
Referenced by coco::DLinkedList< Child, Parent >::joined(), and coco::DLinkedList< Child, Parent >::leaving().
value()
uint32_t coco::InstrIndex::value (void) const inline
Definition at line 46 of file InstrIndex.h.
{ return _value; }
Referenced by InstrIndex(), coco::DLinkedList< Child, Parent >::leaving(), and set().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/InstrIndex.h
compiler/coco/core/src/IR/InstrIndex.cpp