ONE - On-device Neural Engine: luci_interpreter::RuntimeModule Class Reference
luci_interpreter::RuntimeModule Class Reference
#include <RuntimeModule.h>
Public Member Functions
RuntimeModule (EventNotifier *event_notifier)
EventNotifier * getEventNotifier () const
RuntimeGraph * addGraph (IMemoryManager *memory_manager)
const std::vector< Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
void execute () const
RuntimeModule ()=default
IBaseRuntimeGraph * addGraph (IMemoryManager *memory_manager, bool use_static_allocations)
const std::vector< Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
void execute () const
Detailed Description
Definition at line 30 of file RuntimeModule.h.
Constructor & Destructor Documentation
RuntimeModule() [1/2]
luci_interpreter::RuntimeModule::RuntimeModule (EventNotifier * event_notifier) inline explicit
Definition at line 33 of file RuntimeModule.h.
: _event_notifier(event_notifier) {}
RuntimeModule() [2/2]
luci_interpreter::RuntimeModule::RuntimeModule () default
Member Function Documentation
addGraph() [1/2]
RuntimeGraph * luci_interpreter::RuntimeModule::addGraph (IMemoryManager * memory_manager) inline
Definition at line 37 of file RuntimeModule.h.
  {
    _graphs.push_back(std::make_unique<RuntimeGraph>(this, memory_manager));
    return _graphs.back().get();
  }
Referenced by luci_interpreter::ModuleLoader::load().
addGraph() [2/2]
IBaseRuntimeGraph * luci_interpreter::RuntimeModule::addGraph (IMemoryManager * memory_manager, bool use_static_allocations) inline
Definition at line 35 of file RuntimeModule.h.
  {
    if (use_static_allocations)
      _graphs.push_back(std::make_unique<StaticRuntimeGraph>(memory_manager));
    else
      _graphs.push_back(std::make_unique<RuntimeGraph>(memory_manager));
    return _graphs.back().get();
  }
execute() [1/2]
void luci_interpreter::RuntimeModule::execute () const inline
Definition at line 49 of file RuntimeModule.h.
{ getMainGraph()->execute(); }
References luci_interpreter::RuntimeGraph::execute().
execute() [2/2]
void luci_interpreter::RuntimeModule::execute () const inline
Definition at line 50 of file RuntimeModule.h.
{ getMainGraph()->execute(); }
References luci_interpreter::RuntimeGraph::execute().
getEventNotifier()
EventNotifier * luci_interpreter::RuntimeModule::getEventNotifier () const inline
Definition at line 35 of file RuntimeModule.h.
{ return _event_notifier; }
Referenced by luci_interpreter::RuntimeGraph::execute().
getInputTensors() [1/2]
const std::vector< Tensor * > & luci_interpreter::RuntimeModule::getInputTensors () const inline
Definition at line 43 of file RuntimeModule.h.
{ return getMainGraph()->getInputTensors(); }
References luci_interpreter::RuntimeGraph::getInputTensors().
getInputTensors() [2/2]
const std::vector< Tensor * > & luci_interpreter::RuntimeModule::getInputTensors () const inline
Definition at line 44 of file RuntimeModule.h.
{ return getMainGraph()->getInputTensors(); }
References luci_interpreter::RuntimeGraph::getInputTensors().
getOutputTensors() [1/2]
const std::vector< Tensor * > & luci_interpreter::RuntimeModule::getOutputTensors () const inline
Definition at line 44 of file RuntimeModule.h.
  {
    return getMainGraph()->getOutputTensors();
  }
References luci_interpreter::RuntimeGraph::getOutputTensors().
getOutputTensors() [2/2]
const std::vector< Tensor * > & luci_interpreter::RuntimeModule::getOutputTensors () const inline
Definition at line 45 of file RuntimeModule.h.
  {
    return getMainGraph()->getOutputTensors();
  }
References luci_interpreter::RuntimeGraph::getOutputTensors().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/core/RuntimeModule.h
onert-micro/luci-interpreter/src/core/RuntimeModule.h