ONE - On-device Neural Engine: coco::Eval Class Reference
coco::Eval Class Reference final
Evaluate an Object from a given Op.
#include <Instrs.h>
Public Member Functions
Eval ()
Eval * asEval (void) override
const Eval * asEval (void) const override
Instr * loc (void) override
Object * out (void) const
void out (Object *obj)
Op * op (void) const
void op (Op *op)
Public Member Functions inherited from coco::Instr
Instr ()=default
Instr (const Instr &)=delete
Instr (Instr &&)=delete
virtual ~Instr ()
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
const InstrIndex & index (void) const
Public Member Functions inherited from coco::DLinkedList< Child, Parent >::Node
Node ()
virtual ~Node ()
Parent * parent (void) const
Child * prev (void) const
Child * next (void) const
void insertBefore (Node *next)
void insertAfter (Node *prev)
void detach (void)
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Public Member Functions inherited from coco::Object::Producer
virtual ~Producer ()=default
Public Member Functions inherited from coco::Bag::Updater
virtual ~Updater ()=default
Public Member Functions inherited from coco::Locatable
virtual ~Locatable ()=default
virtual Instr * loc (void)=0
Detailed Description
Evaluate an Object from a given Op.
Definition at line 42 of file Instrs.h.
Constructor & Destructor Documentation
Eval()
coco::Eval::Eval () explicit
Definition at line 23 of file Eval.cpp.
           : _out{this}, _step{this}
{
  // DO NOTHING
}
Member Function Documentation
asEval() [1/2]
const Eval * coco::Eval::asEval (void) const inline override
Definition at line 49 of file Instrs.h.
{ return this; }
asEval() [2/2]
Eval * coco::Eval::asEval (void) inline override
Definition at line 48 of file Instrs.h.
{ return this; }
loc()
Instr * coco::Eval::loc (void) inline override virtual
Implements coco::Locatable.
Definition at line 52 of file Instrs.h.
{ return this; }
op() [1/2]
void coco::Eval::op (Op * op) inline
Definition at line 60 of file Instrs.h.
{ _step.op(op); }
References op(), and coco::Step::op().
op() [2/2]
Op * coco::Eval::op (void) const inline
Definition at line 59 of file Instrs.h.
{ return _step.op(); }
References coco::Step::op().
Referenced by InstrBuilder::eval(), op(), and InstrPrinter::visit().
out() [1/2]
void coco::Eval::out (Object * obj) inline
Definition at line 56 of file Instrs.h.
{ _out.value(obj); }
References coco::Def::value().
out() [2/2]
Object * coco::Eval::out (void) const inline
Definition at line 55 of file Instrs.h.
{ return _out.value(); }
References coco::Def::value().
Referenced by InstrPrinter::visit().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Instrs.h
compiler/coco/core/src/IR/Eval.cpp