ONE - On-device Neural Engine: onert::backend::cpu::ops::LogSoftMaxLayer Class Reference
onert::backend::cpu::ops::LogSoftMaxLayer Class Reference
#include <LogSoftMaxLayer.h>
Public Member Functions
LogSoftMaxLayer ()
void logsoftmaxFloat32 ()
void logsoftmaxQuant8 ()
void configure (const IPortableTensor *input, const float beta, const int axis, IPortableTensor *output)
void run ()
void PopulateLookupTable (const float kBeta)
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file LogSoftMaxLayer.h.
Constructor & Destructor Documentation
LogSoftMaxLayer()
onert::backend::cpu::ops::LogSoftMaxLayer::LogSoftMaxLayer ()
Definition at line 32 of file LogSoftMaxLayer.cc.
                                 : _input(nullptr), _output(nullptr), _beta(0.0), _axis(0)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::LogSoftMaxLayer::configure (const IPortableTensor * input, const float beta, const int axis, IPortableTensor * output)
Definition at line 69 of file LogSoftMaxLayer.cc.
{
  _input = input;
  _output = output;
  _beta = beta;
  _axis = axis;
  if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    PopulateLookupTable(_beta);
  }
}
References onert::backend::ITensor::data_type(), and PopulateLookupTable().
logsoftmaxFloat32()
void onert::backend::cpu::ops::LogSoftMaxLayer::logsoftmaxFloat32 ()
Definition at line 47 of file LogSoftMaxLayer.cc.
{
  nnfw::cker::SoftmaxParams op_params;
  op_params.beta = _beta;
  op_params.axis = _axis;
  nnfw::cker::LogSoftmax(op_params, getShape(_input), getBuffer<float>(_input), getShape(_output),
                         getBuffer<float>(_output));
}
References nnfw::cker::SoftmaxParams::axis, nnfw::cker::SoftmaxParams::beta, onert::backend::cpu::ops::getShape(), and nnfw::cker::LogSoftmax().
Referenced by run().
logsoftmaxQuant8()
void onert::backend::cpu::ops::LogSoftMaxLayer::logsoftmaxQuant8 ()
Definition at line 56 of file LogSoftMaxLayer.cc.
{
  nnfw::cker::SoftmaxParams op_params;
  op_params.beta = _beta;
  op_params.axis = _axis;
  op_params.table = _table;
  op_params.zero_point = _output->data_zero_point();
  op_params.scale = _output->data_scale();
  nnfw::cker::LogSoftmax(op_params, _input->data_scale(), getShape(_input),
                         getBuffer<uint8_t>(_input), getShape(_output),
                         getBuffer<uint8_t>(_output));
}
References nnfw::cker::SoftmaxParams::axis, nnfw::cker::SoftmaxParams::beta, onert::backend::IPortableTensor::data_scale(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::cpu::ops::getShape(), nnfw::cker::LogSoftmax(), nnfw::cker::SoftmaxParams::scale, nnfw::cker::SoftmaxParams::table, and nnfw::cker::SoftmaxParams::zero_point.
Referenced by run().
PopulateLookupTable()
void onert::backend::cpu::ops::LogSoftMaxLayer::PopulateLookupTable (const float kBeta)
Definition at line 37 of file LogSoftMaxLayer.cc.
{
  const float scale = -_input->data_scale() * kBeta;
  const int32_t max_uint8 = std::numeric_limits<uint8_t>::max();
  for (int32_t val = 0; val <= max_uint8; ++val)
  {
    _table[max_uint8 - val] = expf(scale * val);
  }
}
References onert::backend::IPortableTensor::data_scale().
Referenced by configure().
run()
void onert::backend::cpu::ops::LogSoftMaxLayer::run () virtual
Implements onert::exec::IFunction.
Definition at line 82 of file LogSoftMaxLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    logsoftmaxFloat32();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    logsoftmaxQuant8();
  }
  else
  {
    throw std::runtime_error{"LogSoftmax : unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), logsoftmaxFloat32(), and logsoftmaxQuant8().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/LogSoftMaxLayer.h
runtime/onert/backend/cpu/ops/LogSoftMaxLayer.cc