ONE - On-device Neural Engine: OpBuilder Class Reference
OpBuilder Class Reference
#include <IRBuilder.h>
Public Member Functions
OpBuilder (coco::Module *module)
bool empty (void) const
Return true if the internal stack is empty.
coco::Op * top (void) const
Return the operation at the top of the internal stack.
OpBuilder & push (coco::Op *op)
Push op onto the internal stack.
OpBuilder & load (coco::Object *obj)
Create "Load" op and push it onto the internal stack.
OpBuilder & add (void)
Create "Add" op and push it onto the internal stack.
OpBuilder & sub (void)
Create "Sub" op and push it onto the internal stack.
OpBuilder & mul (void)
Create "Mul" op and push it onto the internal stack.
OpBuilder & div (void)
Create "Div" op and push it onto the internal stack.
coco::Op * pop (void)
Pop op from the internal stack.
OpBuilder (coco::Module *module)
bool empty (void) const
Return true if the internal stack is empty.
coco::Op * top (void) const
Return the operation at the top of the internal stack.
OpBuilder & push (coco::Op *op)
Push op onto the internal stack.
OpBuilder & load (coco::Object *obj)
Create "Load" op and push it onto the internal stack.
OpBuilder & add (void)
Create "Add" op and push it onto the internal stack.
OpBuilder & mul (void)
Create "Mul" op and push it onto the internal stack.
coco::Op * pop (void)
Pop op from the internal stack.
Detailed Description
coco IR builders
Definition at line 28 of file IRBuilder.h.
Constructor & Destructor Documentation
OpBuilder() [1/2]
OpBuilder::OpBuilder (coco::Module * module) inline
Definition at line 31 of file IRBuilder.h.
                                : _module{module}
  {
    // module SHOULD BE valid
    assert(_module != nullptr);
  }
OpBuilder() [2/2]
OpBuilder::OpBuilder (coco::Module * module) inline
Definition at line 33 of file IRBuilder.h.
                                : _module{module}
  {
    // module SHOULD BE valid
    assert(_module != nullptr);
  }
Member Function Documentation
add() [1/2]
OpBuilder & OpBuilder::add (void) inline
Create "Add" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Add(Left, Right); Stack
Definition at line 84 of file IRBuilder.h.
{ return binary<coco::Add>(); }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::Conv2DGraphBuilder::build(), and tflimport::DepthwiseConv2DGraphBuilder::build().
add() [2/2]
OpBuilder & OpBuilder::add (void) inline
Create "Add" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Add(Left, Right); Stack
Definition at line 86 of file IRBuilder.h.
{ return binary<coco::Add>(); }
div()
OpBuilder & OpBuilder::div (void) inline
Create "Div" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Div(Left, Right); Stack
Definition at line 108 of file IRBuilder.h.
{ return binary<coco::Div>(); }
Referenced by caffeimport::BatchNormBuilder::build().
empty() [1/2]
bool OpBuilder::empty (void) const inline
Return true if the internal stack is empty.
Definition at line 41 of file IRBuilder.h.
{ return _stack.empty(); }
empty() [2/2]
bool OpBuilder::empty (void) const inline
Return true if the internal stack is empty.
Definition at line 43 of file IRBuilder.h.
{ return _stack.empty(); }
load() [1/2]
OpBuilder & OpBuilder::load (coco::Object * obj) inline
Create "Load" op and push it onto the internal stack.
BEFORE| Stack AFTER | Load(obj); Stack
Definition at line 70 of file IRBuilder.h.
  {
    auto op = _module->entity()->op()->create<coco::Load>();
    op->object(obj);
    push(op);
    return (*this);
  }
References coco::OpManager::create(), coco::Module::entity(), coco::Load::object(), coco::EntityManager::op(), and push().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::build_activation().
load() [2/2]
OpBuilder & OpBuilder::load (coco::Object * obj) inline
Create "Load" op and push it onto the internal stack.
BEFORE| Stack AFTER | Load(obj); Stack
Definition at line 72 of file IRBuilder.h.
  {
    auto op = _module->entity()->op()->create<coco::Load>();
    op->object(obj);
    push(op);
    return (*this);
  }
References coco::OpManager::create(), coco::Module::entity(), coco::Load::object(), coco::EntityManager::op(), and push().
mul() [1/2]
OpBuilder & OpBuilder::mul (void) inline
Create "Mul" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Mul(Left, Right); Stack
Definition at line 100 of file IRBuilder.h.
{ return binary<coco::Mul>(); }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::EltwiseBuilder::build(), and caffeimport::ScaleBuilder::build().
mul() [2/2]
OpBuilder & OpBuilder::mul (void) inline
Create "Mul" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Mul(Left, Right); Stack
Definition at line 94 of file IRBuilder.h.
{ return binary<coco::Mul>(); }
pop() [1/2]
coco::Op * OpBuilder::pop (void) inline
Pop op from the internal stack.
BEFORE| Op; Stack AFTER | Stack
Definition at line 116 of file IRBuilder.h.
  {
    assert(_stack.size() > 0);
    auto op = _stack.front();
    _stack.pop_front();
    return op;
  }
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), and tflimport::build_activation().
pop() [2/2]
coco::Op * OpBuilder::pop (void) inline
Pop op from the internal stack.
BEFORE| Op; Stack AFTER | Stack
Definition at line 102 of file IRBuilder.h.
  {
    assert(_stack.size() > 0);
    auto op = _stack.front();
    _stack.pop_front();
    return op;
  }
push() [1/2]
OpBuilder & OpBuilder::push (coco::Op * op) inline
Push op onto the internal stack.
BEFORE| Stack AFTER | Op; Stack
Definition at line 58 of file IRBuilder.h.
  {
    _stack.push_front(op);
    return (*this);
  }
Referenced by caffeimport::EltwiseBuilder::build(), and load().
push() [2/2]
OpBuilder & OpBuilder::push (coco::Op * op) inline
Push op onto the internal stack.
BEFORE| Stack AFTER | Op; Stack
Definition at line 60 of file IRBuilder.h.
  {
    _stack.push_front(op);
    return (*this);
  }
sub()
OpBuilder & OpBuilder::sub (void) inline
Create "Sub" op and push it onto the internal stack.
BEFORE| Left; Right; Stack AFTER | Sub(Left, Right); Stack
Definition at line 92 of file IRBuilder.h.
{ return binary<coco::Sub>(); }
Referenced by caffeimport::BatchNormBuilder::build().
top() [1/2]
coco::Op * OpBuilder::top (void) const inline
Return the operation at the top of the internal stack.
Definition at line 46 of file IRBuilder.h.
  {
    assert(_stack.size() > 0);
    return _stack.front();
  }
top() [2/2]
coco::Op * OpBuilder::top (void) const inline
Return the operation at the top of the internal stack.
Definition at line 48 of file IRBuilder.h.
  {
    assert(_stack.size() > 0);
    return _stack.front();
  }
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/IRBuilder.h
compiler/enco/frontend/tflite/src/IRBuilder.h