ONE - On-device Neural Engine: luci_interpreter::kernels::Squeeze Class Reference
luci_interpreter::kernels::Squeeze Class Reference
#include <Squeeze.h>
Public Member Functions
Squeeze (const Tensor *input, Tensor *output, const SqueezeParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Squeeze (const Tensor *input, Tensor *output, const SqueezeParams &params)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< SqueezeParams >
const SqueezeParams & params () const
const SqueezeParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< SqueezeParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SqueezeParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SqueezeParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< SqueezeParams >
const SqueezeParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 29 of file Squeeze.h.
Constructor & Destructor Documentation
Squeeze() [1/2]
luci_interpreter::kernels::Squeeze::Squeeze (const Tensor * input, Tensor * output, const SqueezeParams & params)
Definition at line 29 of file Squeeze.cpp.
  : KernelWithParams<SqueezeParams>({input}, {output}, params)
{
}
References input().
Squeeze() [2/2]
luci_interpreter::kernels::Squeeze::Squeeze (const Tensor * input, Tensor * output, const SqueezeParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Squeeze::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 34 of file Squeeze.cpp.
{
  int input_num_dims = input()->shape().num_dims();
  int num_squeeze_dims = params().squeeze_dims.size();
  assert(input_num_dims <= 8);
  bool should_squeeze[8] = {false};
  int num_squeezed_dims = 0;
  if (num_squeeze_dims == 0)
  {
    for (int idx = 0; idx < input_num_dims; ++idx)
    {
      if (input()->shape().dim(idx) == 1)
      {
        should_squeeze[idx] = true;
        ++num_squeezed_dims;
      }
    }
  }
  else
  {
    for (int idx = 0; idx < num_squeeze_dims; ++idx)
    {
      int current = params().squeeze_dims[idx] < 0 ? params().squeeze_dims[idx] + input_num_dims
                                                   : params().squeeze_dims[idx];
      assert(current >= 0 && current < input_num_dims && input()->shape().dim(current) == 1);
      if (!should_squeeze[current])
        ++num_squeezed_dims;
      should_squeeze[current] = true;
    }
  }
  Shape output_shape(input_num_dims - num_squeezed_dims);
  for (int in_idx = 0, out_idx = 0; in_idx < input_num_dims; ++in_idx)
  {
    if (!should_squeeze[in_idx])
    {
      output_shape.dim(out_idx++) = input()->shape().dim(in_idx);
    }
  }
  output()->resize(output_shape);
}
References luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< SqueezeParams >::params(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), and luci_interpreter::SqueezeParams::squeeze_dims.
configure() [2/2]
void luci_interpreter::kernels::Squeeze::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Squeeze::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 75 of file Squeeze.cpp.
{
  assert(input()->shape().num_elements() == output()->shape().num_elements());
  const auto *input_data = input()->data<void>();
  auto *output_data = output()->data<void>();
  std::memcpy(output_data, input_data,
              getDataTypeSize(input()->element_type()) * input()->shape().num_elements());
}
References luci_interpreter::Tensor::data(), luci_interpreter::getDataTypeSize(), input(), and output().
execute() [2/2]
void luci_interpreter::kernels::Squeeze::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Squeeze::input () const inline
Definition at line 34 of file Squeeze.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Squeeze().
input() [2/2]
const Tensor * luci_interpreter::kernels::Squeeze::input () const inline
Definition at line 34 of file Squeeze.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Squeeze::output () const inline
Definition at line 35 of file Squeeze.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Squeeze::output () const inline
Definition at line 35 of file Squeeze.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Squeeze.h
onert-micro/luci-interpreter/src/kernels/Squeeze.h
compiler/luci-interpreter/src/kernels/Squeeze.cpp
onert-micro/luci-interpreter/src/kernels/Squeeze.cpp