ONE - On-device Neural Engine: luci::DynamicBatchToSingleBatchPass Class Reference
luci::DynamicBatchToSingleBatchPass Class Reference
Pass to convert dynamic batch to single batch.
#include <DynamicBatchToSingleBatchPass.h>
Public Member Functions
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Pass to convert dynamic batch to single batch.
Definition at line 28 of file DynamicBatchToSingleBatchPass.h.
Member Function Documentation
name()
virtual const char * luci::DynamicBatchToSingleBatchPass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 31 of file DynamicBatchToSingleBatchPass.h.
{ return "luci::DynamicBatchToSingleBatchPass"; }
run()
bool luci::DynamicBatchToSingleBatchPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 25 of file DynamicBatchToSingleBatchPass.cpp.
{
  assert(g); // FIX CALLER UNLESS
  bool changed = false;
  auto graph_inputs = g->inputs();
  // Assume the first dimension is batch dimension
  const uint32_t BATCH_DIM = 0;
  for (auto node : loco::input_nodes(g))
  {
    auto input_node = loco::must_cast<luci::CircleInput *>(node);
    if (input_node->rank() == 0)
      continue;
    // Skip if batch dimension is known
    if (input_node->dim(BATCH_DIM).known())
      continue;
    if (input_node->rank() != 4)
    {
      // Limit use only for rank 4 inputs (for NHWC and NCHW)
      // TODO Enable this if necessary
      throw std::runtime_error("First dimension of input is unknown, but its rank is not 4.");
    }
    // 'set' will make the dimension known
    input_node->dim(BATCH_DIM).set(1);
    // Update graph input
    auto graph_input = graph_inputs->at(input_node->index());
    auto graph_input_shape = graph_input->shape();
    auto tensor_shape = std::make_unique<loco::TensorShape>();
    {
      tensor_shape->rank(graph_input_shape->rank());
      for (uint32_t i = 0; i < tensor_shape->rank(); i++)
      {
        tensor_shape->dim(i) = graph_input_shape->dim(i);
      }
      tensor_shape->dim(BATCH_DIM).set(1);
    }
    graph_input->shape(std::move(tensor_shape));
    changed = true;
  }
  return changed;
}
References luci::FixedArityNode< N, Base >::at(), loco::TensorShape::dim(), luci::CircleInput::index(), luci::input_node(), loco::input_nodes(), loco::TensorShape::rank(), and loco::Dimension::set().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/DynamicBatchToSingleBatchPass.h
compiler/luci/pass/src/DynamicBatchToSingleBatchPass.cpp