ONE - On-device Neural Engine: onert::backend::acl_cl::operand::CLTensor Class Reference
onert::backend::acl_cl::operand::CLTensor Class Reference
#include <CLTensor.h>
Public Member Functions
CLTensor ()=delete
CLTensor (const arm_compute::TensorInfo &info, size_t rank, size_t num_uses)
const arm_compute::CLTensor * handle () const override
arm_compute::CLTensor * handle () override
size_t num_uses () const
arm_compute::CLTensorAllocator * allocator ()
void setBuffer (void *host_ptr)
Public Member Functions inherited from onert::backend::acl_cl::operand::ICLTensor
ICLTensor (size_t rank)
const arm_compute::ICLTensor * handle () const override=0
arm_compute::ICLTensor * handle () override=0
void access (const std::function< void(ITensor &tensor)> &fn) final
bool needMemoryMap () const final
void enqueueWriteBuffer (const void *ptr, bool blocking=true) final
void enqueueReadBuffer (void *ptr, bool blocking=true) final
Public Member Functions inherited from onert::backend::acl_common::IACLTensor
IACLTensor ()=default
IACLTensor (const IACLTensor &)=delete
IACLTensor & operator= (const IACLTensor &)=delete
IACLTensor (IACLTensor &&)=default
IACLTensor & operator= (IACLTensor &&)=default
IACLTensor (size_t rank)
uint8_t * buffer () const final
size_t total_size () const final
size_t calcOffset (const ir::Coordinates &coords) const final
ir::Layout layout () const final
ir::DataType data_type () const final
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
ir::Shape getShape () const override
Get ir::Shape of tensor.
virtual const arm_compute::ITensor * handle () const =0
virtual arm_compute::ITensor * handle ()=0
const arm_compute::ITensorInfo * info () const
arm_compute::ITensorInfo * info ()
size_t dimension (size_t index) const
size_t num_dimensions () const
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Additional Inherited Members
Protected Attributes inherited from onert::backend::acl_common::IACLTensor
size_t _rank
Detailed Description
Definition at line 35 of file CLTensor.h.
Constructor & Destructor Documentation
CLTensor() [1/2]
onert::backend::acl_cl::operand::CLTensor::CLTensor () delete
CLTensor() [2/2]
onert::backend::acl_cl::operand::CLTensor::CLTensor (const arm_compute::TensorInfo & info, size_t rank, size_t num_uses)
Definition at line 34 of file CLTensor.cc.
  : ICLTensor{rank}, _cl_tensor(std::make_shared<arm_compute::CLTensor>()), _num_uses{num_uses}
{
  allocator()->init(info);
}
References allocator(), and onert::backend::acl_common::IACLTensor::info().
Member Function Documentation
allocator()
arm_compute::CLTensorAllocator * onert::backend::acl_cl::operand::CLTensor::allocator ()
Definition at line 44 of file CLTensor.cc.
{ return _cl_tensor->allocator(); }
Referenced by CLTensor(), and setBuffer().
handle() [1/2]
const arm_compute::CLTensor * onert::backend::acl_cl::operand::CLTensor::handle () const override virtual
Implements onert::backend::acl_cl::operand::ICLTensor.
Definition at line 40 of file CLTensor.cc.
{ return _cl_tensor.get(); }
handle() [2/2]
arm_compute::CLTensor * onert::backend::acl_cl::operand::CLTensor::handle () override virtual
Implements onert::backend::acl_cl::operand::ICLTensor.
Definition at line 42 of file CLTensor.cc.
{ return _cl_tensor.get(); }
num_uses()
size_t onert::backend::acl_cl::operand::CLTensor::num_uses () const inline
Definition at line 46 of file CLTensor.h.
{ return _num_uses; }
setBuffer()
void onert::backend::acl_cl::operand::CLTensor::setBuffer (void * host_ptr)
Set given buffer as the buffer of the tensor
Note
Ownership of the memory is not transferred to this object. Thus management (allocate/free) should be done by the client.
Parameters
[in] host_ptr Storage to be used.
Definition at line 46 of file CLTensor.cc.
{
  // Constructs a Buffer on a user-supplied memory
  auto buffer = cl::Buffer(arm_compute::CLScheduler::get().context(),
                           CL_MEM_USE_HOST_PTR | CL_MEM_READ_WRITE, info()->total_size(), host_ptr);
  // import memory
  allocator()->import_memory(buffer);
}
References allocator(), onert::backend::acl_common::IACLTensor::buffer(), onert::backend::acl_common::IACLTensor::info(), and onert::backend::acl_common::IACLTensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_cl/operand/CLTensor.h
runtime/onert/backend/acl_cl/operand/CLTensor.cc