ONE - On-device Neural Engine: mpqsolver::MPQSolver Class Reference
mpqsolver::MPQSolver Class Reference abstract
#include <MPQSolver.h>
Public Member Functions
MPQSolver (const core::Quantizer::Context &ctx)
virtual ~MPQSolver ()=default
virtual std::unique_ptr< luci::Module > run (const std::string &module_path)=0
run solver for recorded float module at module_path
void setSaveIntermediate (const std::string &save_path)
set all intermediate artifacts to be saved
Protected Member Functions
std::unique_ptr< luci::Module > readModule (const std::string &path)
Protected Attributes
std::string _input_quantization
std::string _output_quantization
std::unique_ptr< core::Quantizer > _quantizer
std::unique_ptr< core::DumpingHooks > _hooks
Detailed Description
Definition at line 31 of file MPQSolver.h.
Constructor & Destructor Documentation
MPQSolver()
MPQSolver::MPQSolver (const core::Quantizer::Context & ctx)
Definition at line 24 of file MPQSolver.cpp.
{
  _quantizer = std::make_unique<core::Quantizer>(ctx);
}
References _quantizer.
~MPQSolver()
virtual mpqsolver::MPQSolver::~MPQSolver () virtual default
Member Function Documentation
readModule()
std::unique_ptr< luci::Module > MPQSolver::readModule (const std::string & path) protected
Definition at line 34 of file MPQSolver.cpp.
{
  luci::ImporterEx importerex;
  auto module = importerex.importVerifyModule(path);
  if (module.get() == nullptr)
  {
    throw std::runtime_error("Failed to load model");
  }
  return module;
}
References luci::ImporterEx::importVerifyModule().
Referenced by mpqsolver::bisection::BisectionSolver::run(), and mpqsolver::pattern::PatternSolver::run().
run()
virtual std::unique_ptr< luci::Module > mpqsolver::MPQSolver::run (const std::string & module_path) pure virtual
run solver for recorded float module at module_path
Implemented in mpqsolver::bisection::BisectionSolver, and mpqsolver::pattern::PatternSolver.
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
setSaveIntermediate()
void MPQSolver::setSaveIntermediate (const std::string & save_path)
set all intermediate artifacts to be saved
Definition at line 29 of file MPQSolver.cpp.
{
  _hooks = std::make_unique<core::DumpingHooks>(save_path);
}
References _hooks.
Field Documentation
_hooks
std::unique_ptr<core::DumpingHooks> mpqsolver::MPQSolver::_hooks protected
Definition at line 55 of file MPQSolver.h.
Referenced by mpqsolver::bisection::BisectionSolver::run(), and setSaveIntermediate().
_input_quantization
std::string mpqsolver::MPQSolver::_input_quantization protected
Definition at line 52 of file MPQSolver.h.
_output_quantization
std::string mpqsolver::MPQSolver::_output_quantization protected
Definition at line 53 of file MPQSolver.h.
_quantizer
std::unique_ptr<core::Quantizer> mpqsolver::MPQSolver::_quantizer protected
Definition at line 54 of file MPQSolver.h.
Referenced by MPQSolver(), mpqsolver::bisection::BisectionSolver::run(), and mpqsolver::pattern::PatternSolver::run().
The documentation for this class was generated from the following files:
compiler/circle-mpqsolver/src/MPQSolver.h
compiler/circle-mpqsolver/src/MPQSolver.cpp