ONE - On-device Neural Engine: arm_compute::CLPadLayerEx Class Reference
arm_compute::CLPadLayerEx Class Reference
#include <CLPadLayerEx.h>
Public Member Functions
CLPadLayerEx ()
CLPadLayerEx (const CLPadLayerEx &)=delete
CLPadLayerEx (CLPadLayerEx &&)=default
CLPadLayerEx & operator= (const CLPadLayerEx &)=delete
CLPadLayerEx & operator= (CLPadLayerEx &&)=default
void configure (ICLTensor *input, ICLTensor *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
void run () override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *output, const PaddingList &padding, PixelValue constant_value=PixelValue(), PaddingMode mode=PaddingMode::CONSTANT)
Detailed Description
Basic function to pad a tensor. This function calls the following OpenCL functions/kernels:
CLPadLayerKernelEx if there is padding to be added
CLCopyKernel otherwise
Definition at line 59 of file CLPadLayerEx.h.
Constructor & Destructor Documentation
CLPadLayerEx() [1/3]
arm_compute::CLPadLayerEx::CLPadLayerEx ()
Default constructor
Definition at line 45 of file CLPadLayerEx.cpp.
  : _pad_kernel(std::make_unique<CLPadLayerKernelEx>()),
    _copy_kernel(std::make_unique<opencl::kernels::ClCopyKernel>()), _perform_pad(false)
{
}
CLPadLayerEx() [2/3]
arm_compute::CLPadLayerEx::CLPadLayerEx (const CLPadLayerEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLPadLayerEx() [3/3]
arm_compute::CLPadLayerEx::CLPadLayerEx (CLPadLayerEx &&) default
Default move constructor
Member Function Documentation
configure() [1/2]
void arm_compute::CLPadLayerEx::configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT)
Initialize the function
Parameters
[in] compile_context The compile context to be used.
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 58 of file CLPadLayerEx.cpp.
{
  ARM_COMPUTE_ERROR_THROW_ON(
    validate(input->info(), output->info(), padding, constant_value, mode));
  _perform_pad = std::any_of(padding.begin(), padding.end(),
                             [](PaddingInfo info) { return info.first > 0 || info.second > 0; });
  if (_perform_pad)
  {
    _pad_kernel->configure(compile_context, input, output, padding, constant_value, mode);
  }
  else
  {
    Window copy_window = Window();
    copy_window.use_tensor_dimensions(output->info()->tensor_shape());
    // Copy the input to the whole output if no padding is applied
    _copy_kernel->configure(compile_context, input->info(), output->info(), &copy_window);
  }
}
References info, and validate().
configure() [2/2]
void arm_compute::CLPadLayerEx::configure (ICLTensor * input, ICLTensor * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT)
Initialize the function
Parameters
[in] input Source tensor. Data types supported: All.
[out] output Output tensor. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding.
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 51 of file CLPadLayerEx.cpp.
{
  configure(CLKernelLibrary::get().get_compile_context(), input, output, padding, constant_value,
            mode);
}
References configure().
Referenced by configure().
operator=() [1/2]
CLPadLayerEx & arm_compute::CLPadLayerEx::operator= (CLPadLayerEx &&) default
Default move assignment operator
References validate().
operator=() [2/2]
CLPadLayerEx & arm_compute::CLPadLayerEx::operator= (const CLPadLayerEx &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLPadLayerEx::run () override
Definition at line 99 of file CLPadLayerEx.cpp.
{
  if (_perform_pad)
  {
    CLScheduler::get().enqueue(*_pad_kernel);
  }
  else
  {
    CLScheduler::get().enqueue(*_copy_kernel);
  }
}
validate()
Status arm_compute::CLPadLayerEx::validate (const ITensorInfo * input, const ITensorInfo * output, const PaddingList & padding, PixelValue constant_value = PixelValue(), PaddingMode mode = PaddingMode::CONSTANT) static
Static function to check if given info will lead to a valid configuration of CLPadLayerEx.
Parameters
[in] input Source tensor info. Data types supported: All.
[in] output Output tensor info. Data type supported: same as input
[in] padding The padding for each spatial dimension of the input tensor. The pair padding[i] specifies the front and the end padding in the i-th dimension.
[in] constant_value (Optional) Constant value to be used for the padding
[in] mode (Optional) Controls whether the padding should be filled with constant_value using CONSTANT, or reflect the input, either including the border values (SYMMETRIC) or not (REFLECT).
Definition at line 80 of file CLPadLayerEx.cpp.
{
  bool perform_pad = std::any_of(padding.begin(), padding.end(), [](PaddingInfo info) {
    return info.first > 0 || info.second > 0;
  });
  if (perform_pad)
  {
    ARM_COMPUTE_RETURN_ON_ERROR(
      CLPadLayerKernelEx::validate(input, output, padding, constant_value, mode));
  }
  else
  {
    ARM_COMPUTE_RETURN_ON_ERROR(opencl::kernels::ClCopyKernel::validate(input, output));
  }
  return Status{};
}
References info, and arm_compute::CLPadLayerKernelEx::validate().
Referenced by configure(), and operator=().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLPadLayerEx.h
compute/ARMComputeEx/src/runtime/CL/functions/CLPadLayerEx.cpp