ONE - On-device Neural Engine: exo::DepthwiseConv2DConverter Class Reference
exo::DepthwiseConv2DConverter Class Reference
Convert loco::DepthwiseConv2D to locoex::TFLDepthwiseConv2D and auxiliary.
#include <DepthwiseConv2DConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::DepthwiseConv2D *origin) final
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::DepthwiseConv2D >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::DepthwiseConv2D *node)=0
Detailed Description
Convert loco::DepthwiseConv2D to locoex::TFLDepthwiseConv2D and auxiliary.
<BEFORE>
IFM -----— DepthwiseConv2D — Out [Feature] / [Feature] / KER ----— [DWFilter]
<AFTER> TFLConst (bias) ------------------------— \ IFM ---— FeatureDecode ---------------— TFLDepthwiseConv2D — FeatureEncode — Out [Feature] [Tensor] / [Tensor] [Feature] / KER ----— DepthwiseFilterDecode — TFLReshape [DWFilter] [Tensor / H W C M] [Tensor / 1 H W CM]
Definition at line 50 of file DepthwiseConv2DConverter.h.
Member Function Documentation
convert()
bool exo::DepthwiseConv2DConverter::convert (loco::DepthwiseConv2D * origin) final virtual
Implements exo::CanonicalNodeConverter< loco::DepthwiseConv2D >.
Definition at line 33 of file DepthwiseConv2DConverter.cpp.
{
  // Filter shape is required
  if (not loco::shape_known(origin->ker()))
    return false;
  auto filter_shape = loco::shape_get(origin->ker()).as<loco::DepthwiseFilterShape>();
  if ((origin->ifm() == nullptr) or (origin->ker() == nullptr))
    return false;
  auto *graph = origin->graph();
  auto tfl_dw_conv2d = graph->nodes()->create<locoex::TFLDepthwiseConv2D>();
  {
    tfl_dw_conv2d->stride()->w(origin->stride()->horizontal());
    tfl_dw_conv2d->stride()->h(origin->stride()->vertical());
    auto pad = origin->pad();
    if (pad->bottom() == 0 && pad->top() == 0 && pad->left() == 0 && pad->right() == 0)
      tfl_dw_conv2d->padding(locoex::Padding::VALID);
    else
      // TODO This is necessary, but not sufficient condition. More rigorous check required
      tfl_dw_conv2d->padding(locoex::Padding::SAME);
    tfl_dw_conv2d->fusedActivationFunction(locoex::FusedActFunc::NONE);
    uint32_t multiplier = filter_shape.multiplier().value();
    EXO_ASSERT(multiplier < static_cast<uint32_t>(std::numeric_limits<int32_t>::max()),
               "Multiplier is too big that casting may occur unintended behavior")
    tfl_dw_conv2d->depthMultiplier(static_cast<int32_t>(multiplier));
  }
  // let's create a new graph connection with tfl_dw_conv2d
  {
    // ifm --- feature_dec --- tfl_dw_conv2d
    auto feature_dec = make_feature_decode<FeatureLayout::NHWC>(origin->ifm());
    tfl_dw_conv2d->input(feature_dec);
    // ker --- filter_dec(H x W x C x M) --- reshape(1 x H x W x CM) --- tfl_dw_conv2d
    auto filter_dec = make_dw_filter_decode<DepthwiseFilterLayout::HWCM>(origin->ker());
    auto reshape = graph->nodes()->create<locoex::TFLReshape>();
    reshape->tensor(filter_dec);
    int32_t new_shape[4] = {
      1, static_cast<int32_t>(filter_shape.height().value()),
      static_cast<int32_t>(filter_shape.width().value()),
      static_cast<int32_t>(filter_shape.depth().value() * filter_shape.multiplier().value())};
    locoex::set_new_shape(reshape, new_shape, 4);
    tfl_dw_conv2d->filter(reshape);
    // bias
    auto zero_const = graph->nodes()->create<locoex::TFLConst>();
    {
      assert(loco::shape_known(origin));
      assert(loco::dtype_known(origin) && loco::dtype_get(origin) == loco::DataType::FLOAT32);
      // bias size is C * M
      uint32_t bias_size = filter_shape.depth().value() * filter_shape.multiplier().value();
      zero_const->dtype(loco::DataType::FLOAT32);
      zero_const->rank(1);
      zero_const->dim(0) = bias_size;
      zero_const->size<loco::DataType::FLOAT32>(bias_size);
      for (uint32_t x = 0; x < bias_size; x++)
        zero_const->at<loco::DataType::FLOAT32>(x) = 0.0;
    }
    tfl_dw_conv2d->bias(zero_const);
    // output
    auto feature_enc = make_feature_encode<FeatureLayout::NHWC>(tfl_dw_conv2d);
    // replace canonical node
    loco::replace(origin).with(feature_enc);
    origin->ifm(nullptr);
  }
  return true;
}
References loco::NodeShape::as(), loco::dtype_get(), loco::dtype_known(), EXO_ASSERT, loco::Node::graph(), loco::Stride< 2 >::horizontal(), loco::DepthwiseConv2D::ifm(), loco::DepthwiseConv2D::ker(), exo::make_dw_filter_decode< DepthwiseFilterLayout::HWCM >(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), locoex::NONE, loco::DepthwiseConv2D::pad(), loco::replace(), locoex::SAME, locoex::set_new_shape(), loco::shape_get(), loco::shape_known(), locoex::TFLDepthwiseConv2D::stride(), loco::DepthwiseConv2D::stride(), locoex::VALID, loco::Stride< 2 >::vertical(), locoex::Stride::w(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::DepthwiseConv2DConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::DepthwiseConv2D >.
Definition at line 53 of file DepthwiseConv2DConverter.h.
{ return "exo::DepthwiseConv2DConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/DepthwiseConv2DConverter.h
compiler/exo/src/Conversion/DepthwiseConv2DConverter.cpp