ONE - On-device Neural Engine: locop::GenericNodeSummaryBuilder Class Reference
locop::GenericNodeSummaryBuilder Class Reference final
Dialect-agnostic Node Summary Builder.
#include <GenericNodeSummaryBuilder.h>
Public Member Functions
GenericNodeSummaryBuilder (const SymbolTable *tbl)
bool build (const loco::Node *node, locop::NodeSummary &out) const final
Public Member Functions inherited from locop::NodeSummaryBuilder
virtual ~NodeSummaryBuilder ()=default
virtual bool build (const loco::Node *, NodeSummary &) const =0
Detailed Description
Dialect-agnostic Node Summary Builder.
Definition at line 28 of file GenericNodeSummaryBuilder.h.
Constructor & Destructor Documentation
GenericNodeSummaryBuilder()
locop::GenericNodeSummaryBuilder::GenericNodeSummaryBuilder (const SymbolTable * tbl) inline
Definition at line 31 of file GenericNodeSummaryBuilder.h.
                                                    : _tbl{tbl}
  {
    // DO NOTHING
  }
Member Function Documentation
build()
bool locop::GenericNodeSummaryBuilder::build (const loco::Node * node, locop::NodeSummary & out) const final virtual
Implements locop::NodeSummaryBuilder.
Definition at line 24 of file GenericNodeSummaryBuilder.cpp.
{
  out.opname(pp::fmt(node->dialect(), ".op_", node->opnum()));
  for (uint32_t n = 0; n < node->arity(); ++n)
  {
    out.args().append(pp::fmt("arg", n), _tbl->lookup(node->arg(n)));
  }
  out.state(NodeDesc::State::PartiallyKnown);
  return true;
}
References locop::ArgDesc::append(), loco::Node::arg(), locop::NodeDesc::args(), loco::Node::arity(), loco::Node::dialect(), locop::SymbolTable::lookup(), locop::NodeDesc::opname(), loco::Node::opnum(), locop::NodeDesc::PartiallyKnown, and locop::NodeDesc::state().
The documentation for this class was generated from the following files:
compiler/locop/include/locop/GenericNodeSummaryBuilder.h
compiler/locop/src/GenericNodeSummaryBuilder.cpp