ONE - On-device Neural Engine: npud::core::Signal Class Reference
npud::core::Signal Class Reference
#include <Signal.h>
Public Member Functions
Signal () noexcept
void init (void)
Static Public Member Functions
static void handleSignal (int signum)
Detailed Description
Definition at line 25 of file Signal.h.
Constructor & Destructor Documentation
Signal()
npud::core::Signal::Signal (void) noexcept
Definition at line 28 of file Signal.cc.
{ init(); }
Member Function Documentation
handleSignal()
void npud::core::Signal::handleSignal (int signum) static
Definition at line 46 of file Signal.cc.
{
  VERBOSE(signal) << "Signal received: " << strsignal(signum) << "(" << signum << ")\n";
  Server::instance().stop();
}
References npud::core::Server::instance(), npud::core::Server::stop(), and VERBOSE.
Referenced by init().
init()
void npud::core::Signal::init (void)
Definition at line 30 of file Signal.cc.
{
  // NOTE Types of signals
  // SIGTERM: termination request, sent to the program
  // SIGINT:  external interrupt, usually initiated by the user
  // SIGILL:    invalid program image, such as invalid instruction
  // SIGABRT:   abnormal termination condition, as is e.g. initiated by std::abort()
  // SIGFPE:    erroneous arithmetic operation such as divide by zero
  // from https://en.cppreference.com/w/cpp/utility/program/SIG_types
  std::signal(SIGTERM, handleSignal);
  std::signal(SIGINT, handleSignal);
  std::signal(SIGILL, handleSignal);
  std::signal(SIGABRT, handleSignal);
  std::signal(SIGFPE, handleSignal);
}
References handleSignal().
The documentation for this class was generated from the following files:
runtime/service/npud/core/Signal.h
runtime/service/npud/core/Signal.cc