ONE - On-device Neural Engine: coco::DLinkedList< Child, Parent >::Node Class Reference
coco::DLinkedList< Child, Parent >::Node Class Reference
#include <DLinkedList.h>
Public Member Functions
Node ()
virtual ~Node ()
Parent * parent (void) const
Child * prev (void) const
Child * next (void) const
void insertBefore (Node *next)
void insertAfter (Node *prev)
void detach (void)
Friends
class Head
Detailed Description
template<typename Child, typename Parent>
class coco::DLinkedList< Child, Parent >::Node
Definition at line 160 of file DLinkedList.h.
Constructor & Destructor Documentation
Node()
template<typename Child , typename Parent > coco::DLinkedList< Child, Parent >::Node::Node () inline
Definition at line 166 of file DLinkedList.h.
    {
      static_assert(std::is_base_of<Node, Child>::value,
                    "Type `Child` must be subclass of `Node`.");
      _prev = nullptr;
      _next = nullptr;
    }
~Node()
template<typename Child , typename Parent > virtual coco::DLinkedList< Child, Parent >::Node::~Node () inline virtual
Definition at line 176 of file DLinkedList.h.
    {
      // Each Child should unlink itself on destruction
      //
      // NOTE detach invokes "leaving" hook which may access the internal of each Child,
      //      so it is not safe to invoke detach here
      assert(parent() == nullptr);
    }
References coco::DLinkedList< Child, Parent >::Node::parent().
Member Function Documentation
detach()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Node::detach (void) inline
Definition at line 250 of file DLinkedList.h.
    {
      // Update parent-child relation
      assert(parent() != nullptr);
      assert(head(parent()) != nullptr);
      head(parent())->delist(curr());
      assert(parent() == nullptr);
      // Update the link of sibling nodes
      if (prev())
      {
        prev()->_next = next();
      }
      if (next())
      {
        next()->_prev = prev();
      }
      // Update the link of the current node
      _prev = nullptr;
      _next = nullptr;
    }
References coco::DLinkedList< Child, Parent >::Head::delist(), coco::DLinkedList< Child, Parent >::head(), coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::parent(), and coco::DLinkedList< Child, Parent >::Node::prev().
Referenced by coco::Block::~Block(), and coco::Instr::~Instr().
insertAfter()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Node::insertAfter (Node * prev) inline
Definition at line 223 of file DLinkedList.h.
    {
      assert(prev != nullptr);
      assert(prev->parent() != nullptr);
      assert(head(prev->parent()) != nullptr);
      assert(_prev == nullptr);
      assert(_next == nullptr);
      // Update the link of the current node
      _prev = prev->curr();
      _next = prev->next();
      // Update the link of the sibling nodes
      if (auto next = prev->next())
      {
        next->_prev = curr();
      }
      prev->_next = curr();
      // Update parent-child relation
      assert(parent() == nullptr);
      head(prev->parent())->enlist(curr());
      assert(parent() == prev->parent());
    };
References coco::DLinkedList< Child, Parent >::Head::enlist(), coco::DLinkedList< Child, Parent >::head(), coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::parent(), and coco::DLinkedList< Child, Parent >::Node::prev().
insertBefore()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Node::insertBefore (Node * next) inline
Definition at line 197 of file DLinkedList.h.
    {
      assert(next != nullptr);
      assert(next->parent() != nullptr);
      assert(head(next->parent()) != nullptr);
      assert(_prev == nullptr);
      assert(_next == nullptr);
      // Update the link of the current node
      _prev = next->prev();
      _next = next->curr();
      if (auto prev = next->prev())
      {
        prev->_next = curr();
      }
      next->_prev = curr();
      // Update parent-child relation
      assert(parent() == nullptr);
      head(next->parent())->enlist(curr());
      assert(parent() == next->parent());
    }
References coco::DLinkedList< Child, Parent >::Head::enlist(), coco::DLinkedList< Child, Parent >::head(), coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::parent(), and coco::DLinkedList< Child, Parent >::Node::prev().
next()
template<typename Child , typename Parent > Child * coco::DLinkedList< Child, Parent >::Node::next (void) const inline
Definition at line 194 of file DLinkedList.h.
{ return _next; }
Referenced by coco::BlockManager::destroy(), coco::DLinkedList< Child, Parent >::Node::detach(), coco::DLinkedList< Child, Parent >::Node::insertAfter(), coco::DLinkedList< Child, Parent >::Node::insertBefore(), coco::DLinkedList< Child, Parent >::joined(), and coco::DLinkedList< Child, Parent >::leaving().
parent()
template<typename Child , typename Parent > Parent * coco::DLinkedList< Child, Parent >::Node::parent (void) const inline
Definition at line 186 of file DLinkedList.h.
{ return _parent; }
Referenced by coco::BlockManager::destroy(), coco::InstrManager::destroy(), coco::DLinkedList< Child, Parent >::Node::detach(), enco::hoist_object(), coco::DLinkedList< Child, Parent >::Node::insertAfter(), coco::DLinkedList< Child, Parent >::Node::insertBefore(), coco::Block::~Block(), coco::Instr::~Instr(), and coco::DLinkedList< Child, Parent >::Node::~Node().
prev()
template<typename Child , typename Parent > Child * coco::DLinkedList< Child, Parent >::Node::prev (void) const inline
Definition at line 193 of file DLinkedList.h.
{ return _prev; }
Referenced by coco::BlockManager::destroy(), coco::DLinkedList< Child, Parent >::Node::detach(), coco::DLinkedList< Child, Parent >::Node::insertAfter(), coco::DLinkedList< Child, Parent >::Node::insertBefore(), and coco::DLinkedList< Child, Parent >::joined().
Friends And Related Function Documentation
Head
template<typename Child , typename Parent > friend class Head friend
Definition at line 163 of file DLinkedList.h.
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/ADT/DLinkedList.h