ONE - On-device Neural Engine: exo::ConstGenConverter Class Reference
exo::ConstGenConverter Class Reference
#include <ConstGenConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::ConstGen *constgen) final
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::ConstGen >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::ConstGen *node)=0
Detailed Description
Definition at line 27 of file ConstGenConverter.h.
Member Function Documentation
convert()
bool exo::ConstGenConverter::convert (loco::ConstGen * constgen) final virtual
Implements exo::CanonicalNodeConverter< loco::ConstGen >.
Definition at line 29 of file ConstGenConverter.cpp.
{
  auto *graph = constgen->graph();
  auto tfl_const = graph->nodes()->create<locoex::TFLConst>();
  {
    if (constgen->dtype() == loco::DataType::FLOAT32)
    {
      tfl_const->dtype(loco::DataType::FLOAT32);
      tfl_const->rank(constgen->rank());
      for (uint32_t axis = 0; axis < constgen->rank(); axis++)
        tfl_const->dim(axis) = constgen->dim(axis);
      auto size = constgen->size<loco::DataType::FLOAT32>();
      tfl_const->size<loco::DataType::FLOAT32>(size);
      for (uint32_t i = 0; i < size; ++i)
      {
        tfl_const->at<loco::DataType::FLOAT32>(i) = constgen->at<loco::DataType::FLOAT32>(i);
      }
    }
    else
      INTERNAL_EXN_V("Unsupported DataType", oops::to_uint32(constgen->dtype()));
  }
  loco::replace(constgen).with(tfl_const);
  return true;
}
References loco::ConstGen::at(), loco::Node::graph(), INTERNAL_EXN_V, loco::replace(), loco::ConstGen::size(), oops::to_uint32(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::ConstGenConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::ConstGen >.
Definition at line 30 of file ConstGenConverter.h.
{ return "exo::ConstGenConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/ConstGenConverter.h
compiler/exo/src/Conversion/ConstGenConverter.cpp