ONE - On-device Neural Engine: hermes::Context Class Reference
hermes::Context Class Reference final
Logging controller.
#include <Context.h>
Public Member Functions
const Config * config (void) const
Get the global configuration.
void config (std::unique_ptr< Config > &&)
Update the global configuration.
MessageBus * bus (void)
Source::Registry * sources (void)
Sink::Registry * sinks (void)
Detailed Description
Logging controller.
This "Context" serves as a controller for associated logging source/sink.
WARNING This "Context" is not yet thread-safe. TODO Support multi-threaded application logging
Definition at line 39 of file Context.h.
Member Function Documentation
bus()
MessageBus * hermes::Context::bus (void) inline
Definition at line 48 of file Context.h.
{ return this; }
Referenced by circlechef::Logger::Logger(), exo::Logger::Logger(), luci::Logger::Logger(), moco::Logger::Logger(), and tflchef::Logger::Logger().
config() [1/2]
void hermes::Context::config (std::unique_ptr< Config > && config)
Update the global configuration.
Definition at line 30 of file Context.cpp.
{
  _config = std::move(config);
  // Apply updated configurations
  for (auto source : _sources)
  {
    source->reload(_config.get());
  }
}
References config().
config() [2/2]
const Config * hermes::Context::config (void) const
Get the global configuration.
Definition at line 24 of file Context.cpp.
{
  // Return the current configuration
  return _config.get();
}
Referenced by config(), circlechef::LoggingContext::get(), exo::LoggingContext::get(), luci::LoggingContext::get(), moco::LoggingContext::get(), tflchef::LoggingContext::get(), and main().
sinks()
Sink::Registry * hermes::Context::sinks (void) inline
Definition at line 64 of file Context.h.
{ return this; }
Referenced by circlechef::LoggingContext::get(), exo::LoggingContext::get(), luci::LoggingContext::get(), moco::LoggingContext::get(), and tflchef::LoggingContext::get().
sources()
Source::Registry * hermes::Context::sources (void) inline
Definition at line 55 of file Context.h.
{ return this; }
Referenced by circlechef::Logger::Logger(), exo::Logger::Logger(), luci::Logger::Logger(), moco::Logger::Logger(), and tflchef::Logger::Logger().
The documentation for this class was generated from the following files:
compiler/hermes/include/hermes/core/Context.h
compiler/hermes/src/core/Context.cpp