ONE - On-device Neural Engine: luci::IndexNodeFinder Class Reference
luci::IndexNodeFinder Class Reference
#include <GraphBuilderContext.h>
Public Member Functions
void enroll (TensorIndex idx, CircleNode *node)
CircleNode * node (TensorIndex idx) const
Detailed Description
Definition at line 38 of file GraphBuilderContext.h.
Member Function Documentation
enroll()
void luci::IndexNodeFinder::enroll (TensorIndex idx, CircleNode * node)
Definition at line 26 of file GraphBuilderContext.cpp.
{
  auto iter = _table.find(idx);
  if (iter != _table.end())
  {
    LOGGER(l);
    INFO(l) << "[luci] NodeFinder SKIP (" << idx << ") " << node << ":" << node->name()
            << " existing: " << iter->second << ":" << iter->second->name() << std::endl;
    return;
  }
  _table[idx] = node;
}
References INFO, LOGGER, luci::CircleNode::name(), and node().
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), and luci::CircleWhileGraphBuilder::build().
node()
CircleNode * luci::IndexNodeFinder::node (TensorIndex idx) const
Definition at line 40 of file GraphBuilderContext.cpp.
{
  MapIndexNode_t::const_iterator iter = _table.find(idx);
  // dangle output node may exist that are not enrolled
  return (iter != _table.end()) ? iter->second : nullptr;
}
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::CircleWhileGraphBuilder::build(), and enroll().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Import/GraphBuilderContext.h
compiler/luci/import/src/GraphBuilderContext.cpp