ONE - On-device Neural Engine: onert::backend::acl_common::IACLTensor Class Reference
onert::backend::acl_common::IACLTensor Class Reference abstract
Class representing Tensor for ACL.
#include <IACLTensor.h>
Public Member Functions
IACLTensor ()=default
IACLTensor (const IACLTensor &)=delete
IACLTensor & operator= (const IACLTensor &)=delete
IACLTensor (IACLTensor &&)=default
IACLTensor & operator= (IACLTensor &&)=default
IACLTensor (size_t rank)
uint8_t * buffer () const final
size_t total_size () const final
size_t calcOffset (const ir::Coordinates &coords) const final
ir::Layout layout () const final
ir::DataType data_type () const final
float data_scale () const override
int32_t data_zero_point () const override
const std::vector< float > & data_scales () const override
const std::vector< int32_t > & data_zero_points () const override
bool has_padding () const override
bool is_dynamic () const override
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
ir::Shape getShape () const override
Get ir::Shape of tensor.
virtual const arm_compute::ITensor * handle () const =0
virtual arm_compute::ITensor * handle ()=0
const arm_compute::ITensorInfo * info () const
arm_compute::ITensorInfo * info ()
size_t dimension (size_t index) const
size_t num_dimensions () const
Public Member Functions inherited from onert::backend::ITensor
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Protected Attributes
size_t _rank
Detailed Description
Class representing Tensor for ACL.
Definition at line 37 of file IACLTensor.h.
Constructor & Destructor Documentation
IACLTensor() [1/4]
onert::backend::acl_common::IACLTensor::IACLTensor () default
IACLTensor() [2/4]
onert::backend::acl_common::IACLTensor::IACLTensor (const IACLTensor &) delete
IACLTensor() [3/4]
onert::backend::acl_common::IACLTensor::IACLTensor (IACLTensor &&) default
IACLTensor() [4/4]
onert::backend::acl_common::IACLTensor::IACLTensor (size_t rank) inline
Definition at line 46 of file IACLTensor.h.
: _rank{rank} {}
Member Function Documentation
buffer()
uint8_t * onert::backend::acl_common::IACLTensor::buffer () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 49 of file IACLTensor.h.
{ return handle()->buffer(); }
References handle().
Referenced by onert::backend::acl_cl::operand::CLTensor::setBuffer().
calcOffset()
size_t onert::backend::acl_common::IACLTensor::calcOffset (const ir::Coordinates & coords) const final virtual
Implements onert::backend::ITensor.
Definition at line 28 of file IACLTensor.cc.
{
  auto rank = _rank;
  rank = rank == 0 ? 1 : rank;
  assert(static_cast<size_t>(rank) == coords.size());
  ::arm_compute::Coordinates acl_coords;
  for (size_t i = 0; i < rank; ++i)
  {
    const ARMComputeAxis reversed{static_cast<uint32_t>((rank - i) - 1)};
    acl_coords.set(reversed.value(), coords[i]);
  }
  return info()->offset_element_in_bytes(acl_coords);
}
References _rank, coords, and info().
data_scale()
float onert::backend::acl_common::IACLTensor::data_scale () const override virtual
Implements onert::backend::ITensor.
Definition at line 51 of file IACLTensor.cc.
{
  // FIXME What if quantization info is non-uniform?
  return info()->quantization_info().uniform().scale;
}
References info().
data_scales()
const std::vector< float > & onert::backend::acl_common::IACLTensor::data_scales () const override virtual
Implements onert::backend::ITensor.
Definition at line 63 of file IACLTensor.cc.
{
  throw std::runtime_error("IACLTensor::data_scales() is not supported.");
}
data_type()
ir::DataType onert::backend::acl_common::IACLTensor::data_type () const final virtual
Implements onert::backend::ITensor.
Definition at line 46 of file IACLTensor.cc.
{
  return acl_common::asRuntimeDataType(info()->data_type());
}
References onert::backend::acl_common::asRuntimeDataType(), data_type(), and info().
Referenced by data_type().
data_zero_point()
int32_t onert::backend::acl_common::IACLTensor::data_zero_point () const override virtual
Implements onert::backend::ITensor.
Definition at line 57 of file IACLTensor.cc.
{
  // FIXME What if quantization info is non-uniform?
  return info()->quantization_info().uniform().offset;
}
References info().
data_zero_points()
const std::vector< int32_t > & onert::backend::acl_common::IACLTensor::data_zero_points () const override virtual
Implements onert::backend::ITensor.
Definition at line 68 of file IACLTensor.cc.
{
  throw std::runtime_error("IACLTensor::data_zero_points() is not supported.");
}
dimension()
size_t onert::backend::acl_common::IACLTensor::dimension (size_t index) const inline
Definition at line 75 of file IACLTensor.h.
  {
    // Assume that the front is higher dimensional.
    // i.g. N: 0, C: 1, H: 2, W: 3 for NCHW layout
    // NOTE This tensor must not be applied dim correction
    auto rank = _rank;
    rank = rank == 0 ? 1 : rank;
    assert(rank > index);
    const ARMComputeAxis reversed{(static_cast<uint32_t>(rank - index) - 1)};
    return info()->dimension(reversed.value());
  }
References _rank, and info().
Referenced by getShape().
getShape()
ir::Shape onert::backend::acl_common::IACLTensor::getShape () const inline override virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implements onert::backend::ITensor.
Definition at line 60 of file IACLTensor.h.
  {
    onert::ir::Shape shape(num_dimensions());
    for (uint32_t d = 0; d < num_dimensions(); d++)
      shape.dim(d) = dimension(d);
    return shape;
  }
References dimension(), and num_dimensions().
handle() [1/2]
virtual const arm_compute::ITensor * onert::backend::acl_common::IACLTensor::handle () const pure virtual
Implemented in onert::backend::acl_cl::operand::CLSubTensor, onert::backend::acl_cl::operand::CLTensor, onert::backend::acl_neon::operand::NESubTensor, onert::backend::acl_neon::operand::NETensor, onert::backend::acl_cl::operand::ICLTensor, and onert::backend::acl_neon::operand::INETensor.
Referenced by buffer(), and info().
handle() [2/2]
virtual arm_compute::ITensor * onert::backend::acl_common::IACLTensor::handle () pure virtual
Implemented in onert::backend::acl_cl::operand::CLSubTensor, onert::backend::acl_cl::operand::CLTensor, onert::backend::acl_neon::operand::NESubTensor, onert::backend::acl_neon::operand::NETensor, onert::backend::acl_cl::operand::ICLTensor, and onert::backend::acl_neon::operand::INETensor.
has_padding()
bool onert::backend::acl_common::IACLTensor::has_padding () const inline override virtual
Implements onert::backend::ITensor.
Reimplemented in onert::backend::acl_neon::operand::NESubTensor.
Definition at line 58 of file IACLTensor.h.
{ return info()->has_padding(); }
References info().
info() [1/2]
arm_compute::ITensorInfo * onert::backend::acl_common::IACLTensor::info () inline
Definition at line 73 of file IACLTensor.h.
{ return handle()->info(); }
References handle().
info() [2/2]
const arm_compute::ITensorInfo * onert::backend::acl_common::IACLTensor::info () const inline
Definition at line 72 of file IACLTensor.h.
{ return handle()->info(); }
References handle().
Referenced by calcOffset(), onert::backend::acl_cl::operand::CLTensor::CLTensor(), data_scale(), data_type(), data_zero_point(), dimension(), onert::backend::acl_cl::operand::ICLTensor::enqueueReadBuffer(), onert::backend::acl_cl::operand::ICLTensor::enqueueWriteBuffer(), has_padding(), layout(), onert::backend::acl_neon::operand::NETensor::NETensor(), onert::backend::acl_cl::operand::CLTensor::setBuffer(), and total_size().
is_dynamic()
bool onert::backend::acl_common::IACLTensor::is_dynamic () const inline override virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implements onert::backend::ITensor.
Definition at line 59 of file IACLTensor.h.
{ return false; }
layout()
ir::Layout onert::backend::acl_common::IACLTensor::layout () const final virtual
Implements onert::backend::ITensor.
Definition at line 44 of file IACLTensor.cc.
{ return acl_common::asRuntimeLayout(info()->data_layout()); }
References onert::backend::acl_common::asRuntimeLayout(), and info().
num_dimensions()
size_t onert::backend::acl_common::IACLTensor::num_dimensions () const inline
Definition at line 86 of file IACLTensor.h.
{ return _rank; }
References _rank.
Referenced by getShape().
operator=() [1/2]
IACLTensor & onert::backend::acl_common::IACLTensor::operator= (const IACLTensor &) delete
operator=() [2/2]
IACLTensor & onert::backend::acl_common::IACLTensor::operator= (IACLTensor &&) default
total_size()
size_t onert::backend::acl_common::IACLTensor::total_size () const inline final virtual
Implements onert::backend::ITensor.
Definition at line 50 of file IACLTensor.h.
{ return info()->total_size(); }
References info().
Referenced by onert::backend::acl_cl::operand::ICLTensor::access(), onert::backend::acl_neon::operand::INETensor::access(), onert::backend::acl_cl::operand::ICLTensor::enqueueReadBuffer(), onert::backend::acl_cl::operand::ICLTensor::enqueueWriteBuffer(), and onert::backend::acl_cl::operand::CLTensor::setBuffer().
Field Documentation
_rank
size_t onert::backend::acl_common::IACLTensor::_rank protected
Definition at line 89 of file IACLTensor.h.
Referenced by calcOffset(), dimension(), and num_dimensions().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_common/IACLTensor.h
runtime/onert/backend/acl_common/IACLTensor.cc