ONE - On-device Neural Engine: onert_micro::core::reader::OMTrainingConfigReader Class Reference
onert_micro::core::reader::OMTrainingConfigReader Class Reference
Loads Training Config files and provides helpers functions.
#include <OMTrainingConfigFileReader.h>
Public Member Functions
OMTrainingConfigReader ()=default
OMTrainingConfigReader (const OMTrainingConfigReader &)=delete
OMTrainingConfigReader (OMTrainingConfigReader &&)=default
OMTrainingConfigReader & operator= (const OMTrainingConfigReader &)=delete
OMTrainingConfigReader && operator= (const OMTrainingConfigReader &&)=delete
~OMTrainingConfigReader ()=default
OMStatus validate (OMCircleReader *reader)
void parse (char *ptr)
std::unordered_map< uint16_t, uint8_t > getTrainableOpsIndexes ()
Detailed Description
Loads Training Config files and provides helpers functions.
Definition at line 50 of file OMTrainingConfigFileReader.h.
Constructor & Destructor Documentation
OMTrainingConfigReader() [1/3]
onert_micro::core::reader::OMTrainingConfigReader::OMTrainingConfigReader () default
OMTrainingConfigReader() [2/3]
onert_micro::core::reader::OMTrainingConfigReader::OMTrainingConfigReader (const OMTrainingConfigReader &) delete
OMTrainingConfigReader() [3/3]
onert_micro::core::reader::OMTrainingConfigReader::OMTrainingConfigReader (OMTrainingConfigReader &&) default
~OMTrainingConfigReader()
onert_micro::core::reader::OMTrainingConfigReader::~OMTrainingConfigReader () default
References validate().
Member Function Documentation
getTrainableOpsIndexes()
std::unordered_map< uint16_t, uint8_t > OMTrainingConfigReader::getTrainableOpsIndexes ()
Definition at line 62 of file OMTrainingConfigFileReader.cpp.
{
  std::unordered_map<uint16_t, uint8_t> result;
  // If reader is not parsed then return empty vector
  if (_train_config_ptr == nullptr)
    return result;
  // Read number of ops
  uint32_t num_ops_in_file = 0;
  std::memcpy(&num_ops_in_file, &_train_config_ptr[NUM_LAYERS_FIELD], sizeof(num_ops_in_file));
  assert(num_ops_in_file > 0);
  // Obtain pointer to the first layer index position in the file
  char *cur_op_index_ptr = &_train_config_ptr[FIRST_LAYER_INDEX_FIELD];
  char *cur_op_train_rank_ptr =
    &_train_config_ptr[FIRST_LAYER_INDEX_FIELD + sizeof(uint16_t) * num_ops_in_file];
  // Fill result set with indexes and its rank
  for (uint32_t i = 0; i < num_ops_in_file; ++i)
  {
    // Read op index
    uint16_t cur_op_index;
    std::memcpy(&cur_op_index, cur_op_index_ptr, sizeof(cur_op_index));
    cur_op_index_ptr += sizeof(cur_op_index);
    // Read op train rank
    uint8_t cur_op_train_rank;
    std::memcpy(&cur_op_train_rank, cur_op_train_rank_ptr, sizeof(cur_op_train_rank));
    cur_op_train_rank_ptr += sizeof(cur_op_train_rank);
    // Insert op index and op rank
    result[cur_op_index] = cur_op_train_rank;
  }
  return result;
}
Referenced by onert_micro::core::OMRuntimeContext::getTrainableOpsIndexes().
operator=() [1/2]
OMTrainingConfigReader && onert_micro::core::reader::OMTrainingConfigReader::operator= (const OMTrainingConfigReader &&) delete
operator=() [2/2]
OMTrainingConfigReader & onert_micro::core::reader::OMTrainingConfigReader::operator= (const OMTrainingConfigReader &) delete
parse()
void onert_micro::core::reader::OMTrainingConfigReader::parse (char * ptr) inline
Definition at line 65 of file OMTrainingConfigFileReader.h.
{ _train_config_ptr = ptr; }
Referenced by onert_micro::core::OMRuntimeContext::setTrainConfigFile().
validate()
OMStatus OMTrainingConfigReader::validate (OMCircleReader * reader)
Definition at line 25 of file OMTrainingConfigFileReader.cpp.
{
  OMStatus status = Ok;
  // Validate magic number
  uint16_t mag_num = 0;
  std::memcpy(&mag_num, &_train_config_ptr[MAGIC_NUMBER_FIELD], sizeof(mag_num));
  assert(mag_num == train_config_file_magic_number &&
         "False MAGIC NUMBER, check correctness of wof file");
  if (mag_num != train_config_file_magic_number)
    return FailReadWOFFile;
  // Validate schema version
  uint8_t version = 0;
  std::memcpy(&version, &_train_config_ptr[SCHEMA_VERSION_FIELD], sizeof(version));
  assert(version == train_config_file_schema_version &&
         "False MAGIC NUMBER, check correctness of wof file");
  if (version != train_config_file_schema_version)
    return FailReadWOFFile;
  // Validate count of ops is not greater than current model has
  assert(reader != nullptr && "Reader should exist");
  if (reader == nullptr)
    return ModelNotImport;
  uint32_t num_ops = reader->operators()->size();
  uint32_t num_ops_in_file = 0;
  std::memcpy(&num_ops_in_file, &_train_config_ptr[NUM_LAYERS_FIELD], sizeof(num_ops_in_file));
  assert(num_ops_in_file > 0 and num_ops >= num_ops_in_file &&
         "Number of operators in circle should be greater than train config file has");
  if (num_ops_in_file > 0 and num_ops < num_ops_in_file)
    return FailReadWOFFile;
  return status;
}
References onert_micro::FailReadWOFFile, onert_micro::ModelNotImport, onert_micro::Ok, onert_micro::core::reader::OMCircleReader::operators(), flatbuffers::Vector< T, SizeT >::size(), onert_micro::core::reader::train_config_file_magic_number, and onert_micro::core::reader::train_config_file_schema_version.
Referenced by onert_micro::core::OMRuntimeContext::setTrainConfigFile(), and ~OMTrainingConfigReader().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/reader/OMTrainingConfigFileReader.h
onert-micro/onert-micro/src/core/reader/OMTrainingConfigFileReader.cpp