ONE - On-device Neural Engine: luci_interpreter::kernels::UnidirectionalSequenceLSTM Class Reference
luci_interpreter::kernels::UnidirectionalSequenceLSTM Class Reference
#include <UnidirectionalSequenceLSTM.h>
Public Member Functions
UnidirectionalSequenceLSTM (const Tensor *input, const Tensor *input_to_input_weights, const Tensor *input_to_forget_weights, const Tensor *input_to_cell_weights, const Tensor *input_to_output_weights, const Tensor *recurrent_to_input_weights, const Tensor *recurrent_to_forget_weights, const Tensor *recurrent_to_cell_weights, const Tensor *recurrent_to_output_weights, const Tensor *cell_to_input_weights, const Tensor *cell_to_forget_weights, const Tensor *cell_to_output_weights, const Tensor *input_gate_bias, const Tensor *forget_gate_bias, const Tensor *cell_gate_bias, const Tensor *output_gate_bias, const Tensor *projection_weights, const Tensor *projection_bias, const Tensor *output_state, const Tensor *cell_state, const Tensor *input_layer_norm_coefficients, const Tensor *forget_layer_norm_coefficients, const Tensor *cell_layer_norm_coefficients, const Tensor *output_layer_norm_coefficients, Tensor *output, Tensor *scratchpad_1, Tensor *scratchpad_2, Tensor *scratchpad_3, const UnidirectionalSequenceLSTMParams &params)
const Tensor * input () const
const Tensor * input_to_input_weights () const
const Tensor * input_to_forget_weights () const
const Tensor * input_to_cell_weights () const
const Tensor * input_to_output_weights () const
const Tensor * recurrent_to_input_weights () const
const Tensor * recurrent_to_forget_weights () const
const Tensor * recurrent_to_cell_weights () const
const Tensor * recurrent_to_output_weights () const
const Tensor * cell_to_input_weights () const
const Tensor * cell_to_forget_weights () const
const Tensor * cell_to_output_weights () const
const Tensor * input_gate_bias () const
const Tensor * forget_gate_bias () const
const Tensor * cell_gate_bias () const
const Tensor * output_gate_bias () const
const Tensor * projection_weights () const
const Tensor * projection_bias () const
const Tensor * output_state () const
const Tensor * cell_state () const
const Tensor * input_layer_norm_coefficients () const
const Tensor * forget_layer_norm_coefficients () const
const Tensor * cell_layer_norm_coefficients () const
const Tensor * output_layer_norm_coefficients () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< UnidirectionalSequenceLSTMParams >
const UnidirectionalSequenceLSTMParams & params () const
const UnidirectionalSequenceLSTMParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< UnidirectionalSequenceLSTMParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const UnidirectionalSequenceLSTMParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const UnidirectionalSequenceLSTMParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< UnidirectionalSequenceLSTMParams >
const UnidirectionalSequenceLSTMParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 29 of file UnidirectionalSequenceLSTM.h.
Constructor & Destructor Documentation
UnidirectionalSequenceLSTM()
luci_interpreter::kernels::UnidirectionalSequenceLSTM::UnidirectionalSequenceLSTM (const Tensor * input, const Tensor * input_to_input_weights, const Tensor * input_to_forget_weights, const Tensor * input_to_cell_weights, const Tensor * input_to_output_weights, const Tensor * recurrent_to_input_weights, const Tensor * recurrent_to_forget_weights, const Tensor * recurrent_to_cell_weights, const Tensor * recurrent_to_output_weights, const Tensor * cell_to_input_weights, const Tensor * cell_to_forget_weights, const Tensor * cell_to_output_weights, const Tensor * input_gate_bias, const Tensor * forget_gate_bias, const Tensor * cell_gate_bias, const Tensor * output_gate_bias, const Tensor * projection_weights, const Tensor * projection_bias, const Tensor * output_state, const Tensor * cell_state, const Tensor * input_layer_norm_coefficients, const Tensor * forget_layer_norm_coefficients, const Tensor * cell_layer_norm_coefficients, const Tensor * output_layer_norm_coefficients, Tensor * output, Tensor * scratchpad_1, Tensor * scratchpad_2, Tensor * scratchpad_3, const UnidirectionalSequenceLSTMParams & params)
Definition at line 440 of file UnidirectionalSequenceLSTM.cpp.
  : KernelWithParams<UnidirectionalSequenceLSTMParams>(
      {input,
       input_to_input_weights,
       input_to_forget_weights,
       input_to_cell_weights,
       input_to_output_weights,
       recurrent_to_input_weights,
       recurrent_to_forget_weights,
       recurrent_to_cell_weights,
       recurrent_to_output_weights,
       cell_to_input_weights,
       cell_to_forget_weights,
       cell_to_output_weights,
       input_gate_bias,
       forget_gate_bias,
       cell_gate_bias,
       output_gate_bias,
       projection_weights,
       projection_bias,
       output_state,
       cell_state,
       input_layer_norm_coefficients,
       forget_layer_norm_coefficients,
       cell_layer_norm_coefficients,
       output_layer_norm_coefficients},
      {output, scratchpad_1, scratchpad_2, scratchpad_3}, params)
{
  // Do nothing
}
References cell_gate_bias(), cell_layer_norm_coefficients(), cell_state(), cell_to_forget_weights(), cell_to_input_weights(), cell_to_output_weights(), forget_gate_bias(), forget_layer_norm_coefficients(), input(), input_gate_bias(), input_layer_norm_coefficients(), input_to_cell_weights(), input_to_forget_weights(), input_to_input_weights(), input_to_output_weights(), output_gate_bias(), output_layer_norm_coefficients(), output_state(), projection_bias(), projection_weights(), recurrent_to_cell_weights(), recurrent_to_forget_weights(), recurrent_to_input_weights(), and recurrent_to_output_weights().
Member Function Documentation
cell_gate_bias()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_gate_bias () const inline
Definition at line 75 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[14]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
cell_layer_norm_coefficients()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_layer_norm_coefficients () const inline
Definition at line 86 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[22]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
cell_state()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_state () const inline
Definition at line 82 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[19]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
cell_to_forget_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_to_forget_weights () const inline
Definition at line 70 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[10]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
cell_to_input_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_to_input_weights () const inline
Definition at line 69 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[9]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
cell_to_output_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::cell_to_output_weights () const inline
Definition at line 71 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[11]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
configure()
void luci_interpreter::kernels::UnidirectionalSequenceLSTM::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 751 of file UnidirectionalSequenceLSTM.cpp.
{
  LUCI_INTERPRETER_CHECK(getInputTensors().size() == 24);
  LUCI_INTERPRETER_CHECK(getOutputTensors().size() >= 1);
  // TODO support U8
  LUCI_INTERPRETER_CHECK(input()->element_type() == loco::DataType::FLOAT32);
  const bool is_integer = false;
  const bool use_layer_norm = (forget_layer_norm_coefficients() != nullptr);
  // Inferring batch size, number of outputs and sequence length and
  // number of cells from the input tensors.
  const Shape &input_shape = input()->shape();
  LUCI_INTERPRETER_CHECK(input_shape.num_dims() > 1);
  const bool time_major = params().time_major;
  const int n_batch = time_major ? input_shape.dim(1) : input_shape.dim(0);
  // NOTE as dim(2) is accessed, we need to check this is valid
  LUCI_INTERPRETER_CHECK(input_shape.num_dims() > 2);
  const int n_input = input_shape.dim(2);
  const Shape &input_to_output_weights_shape = input_to_output_weights()->shape();
  const int n_cell = input_to_output_weights_shape.dim(0);
  LUCI_INTERPRETER_CHECK(input_to_output_weights_shape.num_dims() == 2);
  LUCI_INTERPRETER_CHECK(input_to_output_weights_shape.dim(1) == n_input);
  const Shape &recurrent_to_output_weights_shape = recurrent_to_output_weights()->shape();
  LUCI_INTERPRETER_CHECK(recurrent_to_output_weights_shape.num_dims() == 2);
  LUCI_INTERPRETER_CHECK(recurrent_to_output_weights_shape.dim(0) == n_cell);
  const int n_output = recurrent_to_output_weights_shape.dim(1);
  // Check that input tensor dimensions matches with each other.
  check_input_tensor_dimensions(n_input, n_output, n_cell, use_layer_norm, is_integer);
  // Check the shape of input state tensors.
  // These tensor may be 1D or 2D. It's fine as long as the total size is
  // correct.
  const Shape &output_state_shape = output_state()->shape();
  const Shape &cell_state_shape = cell_state()->shape();
  LUCI_INTERPRETER_CHECK(output_state_shape.num_elements() == n_batch * n_output);
  LUCI_INTERPRETER_CHECK(cell_state_shape.num_elements() == n_batch * n_cell);
  // Resize the output tensors.
  Shape output_shape = Shape(input_shape.num_dims());
  for (int i = 0; i < input_shape.num_dims() - 1; i++)
  {
    output_shape.dim(i) = input_shape.dim(i);
  }
  output_shape.dim(input_shape.num_dims() - 1) = n_output;
  output()->resize(output_shape);
  // TODO import integer
  // output_state and cell_state are variable tensor; use scratchpad.
  getOutputTensors()[1]->resize(output_state_shape);
  getOutputTensors()[2]->resize(cell_state_shape);
  const bool use_cifg = (input_to_input_weights() == nullptr);
  if (use_cifg)
    getOutputTensors()[3]->resize({n_batch, n_cell * 3});
  else
    getOutputTensors()[3]->resize({n_batch, n_cell * 4});
  // hybrid not supported
  if (input_to_output_weights()->element_type() == loco::DataType::U8 &&
      input()->element_type() == loco::DataType::FLOAT32)
  {
    throw std::runtime_error("Hybrid type is not currently supported");
  }
  // TODO support hybrid
  // TODO support U8
}
References cell_state(), luci_interpreter::Shape::dim(), forget_layer_norm_coefficients(), luci_interpreter::Kernel::getInputTensors(), luci_interpreter::Kernel::getOutputTensors(), input(), input_to_input_weights(), input_to_output_weights(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), luci_interpreter::Shape::num_elements(), output(), output_state(), luci_interpreter::KernelWithParams< UnidirectionalSequenceLSTMParams >::params(), recurrent_to_output_weights(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), luci_interpreter::size(), and luci_interpreter::UnidirectionalSequenceLSTMParams::time_major.
execute()
void luci_interpreter::kernels::UnidirectionalSequenceLSTM::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 824 of file UnidirectionalSequenceLSTM.cpp.
{
  switch (input()->element_type())
  {
    case loco::DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Unsupported type");
  }
}
References input().
forget_gate_bias()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::forget_gate_bias () const inline
Definition at line 74 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[13]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
forget_layer_norm_coefficients()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::forget_layer_norm_coefficients () const inline
Definition at line 85 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[21]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
input()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input () const inline
Definition at line 57 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and UnidirectionalSequenceLSTM().
input_gate_bias()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_gate_bias () const inline
Definition at line 73 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[12]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
input_layer_norm_coefficients()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_layer_norm_coefficients () const inline
Definition at line 84 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[20]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
input_to_cell_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_to_cell_weights () const inline
Definition at line 61 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
input_to_forget_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_to_forget_weights () const inline
Definition at line 60 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
input_to_input_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_to_input_weights () const inline
Definition at line 59 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
input_to_output_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::input_to_output_weights () const inline
Definition at line 62 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[4]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
output()
Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::output () const inline
Definition at line 89 of file UnidirectionalSequenceLSTM.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output_gate_bias()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::output_gate_bias () const inline
Definition at line 76 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[15]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
output_layer_norm_coefficients()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::output_layer_norm_coefficients () const inline
Definition at line 87 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[23]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
output_state()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::output_state () const inline
Definition at line 81 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[18]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
projection_bias()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::projection_bias () const inline
Definition at line 79 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[17]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
projection_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::projection_weights () const inline
Definition at line 78 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[16]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
recurrent_to_cell_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::recurrent_to_cell_weights () const inline
Definition at line 66 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[7]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
recurrent_to_forget_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::recurrent_to_forget_weights () const inline
Definition at line 65 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[6]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
recurrent_to_input_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::recurrent_to_input_weights () const inline
Definition at line 64 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[5]; }
References luci_interpreter::Kernel::_inputs.
Referenced by UnidirectionalSequenceLSTM().
recurrent_to_output_weights()
const Tensor * luci_interpreter::kernels::UnidirectionalSequenceLSTM::recurrent_to_output_weights () const inline
Definition at line 67 of file UnidirectionalSequenceLSTM.h.
{ return _inputs[8]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and UnidirectionalSequenceLSTM().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h
compiler/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.cpp