ONE - On-device Neural Engine: PaddingBase< Derived > Class Template Reference
PaddingBase< Derived > Class Template Reference
A PaddingBase encapsulates common implementation for derived Padding classes.
#include <Padding.h>
Public Member Functions
virtual ~PaddingBase ()=default
uint32_t count (void) const
uint32_t & value (uint32_t n)
const uint32_t & value (uint32_t n) const
void resize (uint32_t len)
Detailed Description
template<typename Derived>
class PaddingBase< Derived >
A PaddingBase encapsulates common implementation for derived Padding classes.
Definition at line 30 of file Padding.h.
Constructor & Destructor Documentation
~PaddingBase()
template<typename Derived > virtual PaddingBase< Derived >::~PaddingBase () virtual default
Member Function Documentation
count()
template<typename Derived > uint32_t PaddingBase< Derived >::count (void) const inline
Definition at line 36 of file Padding.h.
{ return _values.size(); }
Referenced by SpatialPaddingBuilder::with().
resize()
template<typename Derived > void PaddingBase< Derived >::resize (uint32_t len) inline
Definition at line 43 of file Padding.h.
{ return _values.resize(len); }
Referenced by build_spatial_padding(), and SpatialPaddingBuilder::with().
value() [1/2]
template<typename Derived > uint32_t & PaddingBase< Derived >::value (uint32_t n) inline
Definition at line 39 of file Padding.h.
{ return _values.at(n); }
Referenced by build_spatial_padding(), PoolingSpec::horizontal_pad(), ConvolutionSpec::pad(), PoolingSpec::vertical_pad(), and SpatialPaddingBuilder::with().
value() [2/2]
template<typename Derived > const uint32_t & PaddingBase< Derived >::value (uint32_t n) const inline
Definition at line 40 of file Padding.h.
{ return _values.at(n); }
The documentation for this class was generated from the following file:
compiler/enco/frontend/caffe/src/Padding.h