ONE - On-device Neural Engine: tflread::Reader Class Reference
tflread::Reader Class Reference
Loads TF lite file and provides helpers to access attributes.
#include <Read.h>
Public Member Functions
Reader (const tflite::Model *model)
Reader ()=delete
uint32_t version () const
const std::vector< const tflite::OperatorCode * > & opcodes ()
const TFliteBuffers_t * buffers ()
const TFliteTensors_t * tensors ()
const TFliteOperators_t * operators ()
const std::vector< int32_t > & inputs () const
const std::vector< int32_t > & outputs () const
const TFliteMetadata_t * metadata () const
const TFliteSignatureDef_t * signaturedefs () const
uint32_t num_subgraph () const
size_t buffer_info (uint32_t buf_idx, const uint8_t **buff_data)
tflite::BuiltinOperator builtin_code (const tflite::Operator *op) const
std::string opcode_name (const tflite::Operator *op) const
bool select_subgraph (uint32_t subgraph)
const std::string & subgraph_name (void) const
uint32_t subgraph_index (void) const
Detailed Description
Loads TF lite file and provides helpers to access attributes.
Definition at line 42 of file Read.h.
Constructor & Destructor Documentation
Reader() [1/2]
tflread::Reader::Reader (const tflite::Model * model)
Definition at line 27 of file Read.cpp.
{
  _version = model->version();
  _subgraphs = model->subgraphs();
  _buffers = model->buffers();
  _metadata = model->metadata();
  _signaturedefs = model->signature_defs();
  auto opcodes = model->operator_codes();
  for (const ::tflite::OperatorCode *opcode : *opcodes)
  {
    _op_codes.push_back(opcode);
  }
}
References opcodes().
Reader() [2/2]
tflread::Reader::Reader () delete
Member Function Documentation
buffer_info()
size_t tflread::Reader::buffer_info (uint32_t buf_idx, const uint8_t ** buff_data)
Definition at line 42 of file Read.cpp.
{
  *buff_data = nullptr;
  if (buf_idx == 0)
    return 0;
  if (auto *buffer = (*_buffers)[buf_idx])
  {
    if (auto *array = buffer->data())
    {
      if (size_t size = array->size())
      {
        *buff_data = reinterpret_cast<const uint8_t *>(array->data());
        return size;
      }
    }
  }
  return 0;
}
Referenced by tfldump::dump_model().
buffers()
const TFliteBuffers_t * tflread::Reader::buffers () inline
Definition at line 61 of file Read.h.
{ return _buffers; }
Referenced by tfldump::dump_model().
builtin_code()
tflite::BuiltinOperator tflread::Reader::builtin_code (const tflite::Operator * op) const
Definition at line 64 of file Read.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  return mio::tflite::builtin_code_neutral(opcode);
}
References mio::tflite::builtin_code_neutral().
Referenced by tfldump::dump_sub_graph().
inputs()
const std::vector< int32_t > & tflread::Reader::inputs () const inline
Definition at line 64 of file Read.h.
{ return _inputs; }
Referenced by tfldump::dump_sub_graph(), and validate_onnx2circle.OnnxRunner::feed_random_inputs().
metadata()
const TFliteMetadata_t * tflread::Reader::metadata () const inline
Definition at line 66 of file Read.h.
{ return _metadata; }
Referenced by tfldump::dump_model().
num_subgraph()
uint32_t tflread::Reader::num_subgraph () const inline
Definition at line 69 of file Read.h.
{ return _subgraphs->Length(); }
Referenced by tfldump::dump_model().
opcode_name()
std::string tflread::Reader::opcode_name (const tflite::Operator * op) const
Definition at line 73 of file Read.cpp.
{
  uint32_t index = op->opcode_index();
  assert(index < _op_codes.size());
  const tflite::OperatorCode *opcode = _op_codes.at(index);
  if (!mio::tflite::is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid: " << index << ")";
    return oss.str();
  }
  return mio::tflite::opcode_name(opcode);
}
References mio::tflite::is_valid(), and mio::tflite::opcode_name().
Referenced by tfldump::dump_sub_graph().
opcodes()
const std::vector< const tflite::OperatorCode * > & tflread::Reader::opcodes () inline
Definition at line 60 of file Read.h.
{ return _op_codes; }
Referenced by tfldump::dump_model(), and Reader().
operators()
const TFliteOperators_t * tflread::Reader::operators () inline
Definition at line 63 of file Read.h.
{ return _operators; }
Referenced by tfldump::dump_sub_graph().
outputs()
const std::vector< int32_t > & tflread::Reader::outputs () const inline
Definition at line 65 of file Read.h.
{ return _outputs; }
Referenced by tfldump::dump_sub_graph(), and validate_onnx2circle.OnnxRunner::get_outputs().
select_subgraph()
bool tflread::Reader::select_subgraph (uint32_t subgraph)
Definition at line 89 of file Read.cpp.
{
  _subgraph_index = sgindex;
  _tensors = nullptr;
  _operators = nullptr;
  _inputs.clear();
  _outputs.clear();
  if (_subgraphs->Length() <= sgindex)
  {
    assert(false);
    return false;
  }
  const tflite::SubGraph *subgraph = (*_subgraphs)[sgindex];
  auto name = subgraph->name();
  _subgraph_name = name ? name->c_str() : "(noname)";
  _tensors = subgraph->tensors();
  _operators = subgraph->operators();
  _inputs = as_index_vector(subgraph->inputs());
  _outputs = as_index_vector(subgraph->outputs());
  return true;
}
References tflread::as_index_vector().
Referenced by tfldump::dump_model().
signaturedefs()
const TFliteSignatureDef_t * tflread::Reader::signaturedefs () const inline
Definition at line 67 of file Read.h.
{ return _signaturedefs; }
Referenced by tfldump::dump_model().
subgraph_index()
uint32_t tflread::Reader::subgraph_index (void) const inline
Definition at line 78 of file Read.h.
{ return _subgraph_index; }
Referenced by tfldump::dump_sub_graph().
subgraph_name()
const std::string & tflread::Reader::subgraph_name (void) const inline
Definition at line 77 of file Read.h.
{ return _subgraph_name; }
Referenced by tfldump::dump_model().
tensors()
const TFliteTensors_t * tflread::Reader::tensors () inline
Definition at line 62 of file Read.h.
{ return _tensors; }
Referenced by tfldump::dump_sub_graph().
version()
uint32_t tflread::Reader::version () const inline
Definition at line 58 of file Read.h.
{ return _version; }
Referenced by tfldump::dump_model().
The documentation for this class was generated from the following files:
compiler/tfldump/src/Read.h
compiler/tfldump/src/Read.cpp