ONE - On-device Neural Engine: luci::compute::DepthwiseConv2D Class Reference
luci::compute::DepthwiseConv2D Class Reference
#include <DepthwiseConv2D.h>
Public Member Functions
DepthwiseConv2D ()=default
DepthwiseParams & params (void)
void input (const loco::TensorShape &shape, const float *data)
void filter (const loco::TensorShape &shape, const float *data)
void bias (const loco::TensorShape &shape, const float *data)
void fused_act_func (FusedActFunc func)
void output (float *data)
bool prepare (void)
const loco::TensorShape & output_shape (void) const
void compute (void)
Detailed Description
Definition at line 29 of file DepthwiseConv2D.h.
Constructor & Destructor Documentation
DepthwiseConv2D()
luci::compute::DepthwiseConv2D::DepthwiseConv2D () default
Member Function Documentation
bias()
void luci::compute::DepthwiseConv2D::bias (const loco::TensorShape & shape, const float * data) inline
Definition at line 49 of file DepthwiseConv2D.h.
  {
    _bias_shape = shape;
    _bias_data = data;
  }
References flatbuffers::data().
compute()
void luci::compute::DepthwiseConv2D::compute (void)
Definition at line 129 of file DepthwiseConv2D.cpp.
{
  assert(_input_data != nullptr);
  assert(_filter_data != nullptr);
  // NOTE _bias_shape can be nullptr
  assert(_output_data != nullptr);
  // NOTE if this fails, structure may have changed
  static_assert(sizeof(compute::DepthwiseParams) == sizeof(tflite::DepthwiseParams));
  tflite::DepthwiseParams params;
  // clang-format off
  params.padding_type                   = tflite_padding(_params.padding_type);
  params.padding_values.width           = _params.padding_values.width;
  params.padding_values.height          = _params.padding_values.height;
  params.padding_values.width_offset    = _params.padding_values.width_offset;
  params.padding_values.height_offset   = _params.padding_values.height_offset;
  params.stride_width                   = _params.stride_width;
  params.stride_height                  = _params.stride_height;
  params.dilation_width_factor          = _params.dilation_width_factor;
  params.dilation_height_factor         = _params.dilation_height_factor;
  params.depth_multiplier               = _params.depth_multiplier;
  params.input_offset                   = _params.input_offset;
  params.weights_offset                 = _params.weights_offset;
  params.output_offset                  = _params.output_offset;
  params.output_multiplier              = _params.output_multiplier;
  params.output_shift                   = _params.output_shift;
  params.quantized_activation_min       = _params.quantized_activation_min;
  params.quantized_activation_max       = _params.quantized_activation_max;
  params.float_activation_min           = _params.float_activation_min;
  params.float_activation_max           = _params.float_activation_max;
  params.output_multiplier_per_channel  = _params.output_multiplier_per_channel;
  params.output_shift_per_channel       = _params.output_shift_per_channel;
  // clang-format on
  tflite::reference_ops::DepthwiseConv(
    params, tflite_shape(_input_shape), _input_data, tflite_shape(_filter_shape), _filter_data,
    tflite_shape(_bias_shape), _bias_data, tflite_shape(_output_shape), _output_data);
}
References luci::compute::DepthwiseParams::depth_multiplier, luci::compute::DepthwiseParams::dilation_height_factor, luci::compute::DepthwiseParams::dilation_width_factor, luci::compute::DepthwiseParams::float_activation_max, luci::compute::DepthwiseParams::float_activation_min, luci::compute::PaddingValues::height, luci::compute::PaddingValues::height_offset, luci::compute::DepthwiseParams::input_offset, luci::compute::DepthwiseParams::output_multiplier, luci::compute::DepthwiseParams::output_multiplier_per_channel, luci::compute::DepthwiseParams::output_offset, luci::compute::DepthwiseParams::output_shift, luci::compute::DepthwiseParams::output_shift_per_channel, luci::compute::DepthwiseParams::padding_type, luci::compute::DepthwiseParams::padding_values, params(), luci::compute::DepthwiseParams::quantized_activation_max, luci::compute::DepthwiseParams::quantized_activation_min, luci::compute::DepthwiseParams::stride_height, luci::compute::DepthwiseParams::stride_width, luci::compute::tflite_padding(), luci::compute::tflite_shape(), luci::compute::DepthwiseParams::weights_offset, luci::compute::PaddingValues::width, and luci::compute::PaddingValues::width_offset.
filter()
void luci::compute::DepthwiseConv2D::filter (const loco::TensorShape & shape, const float * data) inline
Definition at line 43 of file DepthwiseConv2D.h.
  {
    _filter_shape = shape;
    _filter_data = data;
  }
References flatbuffers::data().
fused_act_func()
void luci::compute::DepthwiseConv2D::fused_act_func (FusedActFunc func) inline
Definition at line 55 of file DepthwiseConv2D.h.
{ _fused_act_func = func; };
input()
void luci::compute::DepthwiseConv2D::input (const loco::TensorShape & shape, const float * data) inline
Definition at line 37 of file DepthwiseConv2D.h.
  {
    _input_shape = shape;
    _input_data = data;
  }
References flatbuffers::data().
output()
void luci::compute::DepthwiseConv2D::output (float * data) inline
Definition at line 57 of file DepthwiseConv2D.h.
{ _output_data = data; }
References flatbuffers::data().
output_shape()
const loco::TensorShape & luci::compute::DepthwiseConv2D::output_shape (void) const inline
Definition at line 61 of file DepthwiseConv2D.h.
{ return _output_shape; }
params()
DepthwiseParams & luci::compute::DepthwiseConv2D::params (void) inline
Definition at line 35 of file DepthwiseConv2D.h.
{ return _params; }
Referenced by compute().
prepare()
bool luci::compute::DepthwiseConv2D::prepare (void)
Definition at line 75 of file DepthwiseConv2D.cpp.
{
  // TODO support other ranks if necessary
  if (_input_shape.rank() != 4 || _filter_shape.rank() != 4)
    return false;
  // if bias exist, check if rank is 1
  if (_bias_data && _bias_shape.rank() != 1)
    return false;
  auto const input_batches = _input_shape.dim(0).value();
  auto const input_height = _input_shape.dim(1).value();
  auto const input_width = _input_shape.dim(2).value();
  auto const input_depth = _input_shape.dim(3).value();
  auto const filter_height = _filter_shape.dim(1).value();
  auto const filter_width = _filter_shape.dim(2).value();
  auto const filter_channels_out = _filter_shape.dim(3).value();
  if (filter_channels_out % input_depth != 0)
    return false; // wrong input/output depth ratio
  if (_params.depth_multiplier != static_cast<int32_t>(filter_channels_out / input_depth))
    return false; // wrong depth multiplier value
  if (_bias_shape.dim(0).value() != filter_channels_out)
    return false; // unsupported bias value
  auto output_height = compute_output(_params.padding_type, input_height, filter_height,
                                      _params.stride_height, _params.dilation_height_factor);
  if (output_height < 0)
    return false;
  auto output_width = compute_output(_params.padding_type, input_width, filter_width,
                                     _params.stride_width, _params.dilation_width_factor);
  if (output_width < 0)
    return false;
  get_act_minmax(_fused_act_func, _params.float_activation_min, _params.float_activation_max);
  _output_shape.rank(4);
  _output_shape.dim(0) = input_batches;
  _output_shape.dim(1) = output_height;
  _output_shape.dim(2) = output_width;
  _output_shape.dim(3) = filter_channels_out;
  _params.padding_values.height =
    compute_padding(output_height, input_height, filter_height, _params.stride_height,
                    _params.dilation_height_factor);
  _params.padding_values.width = compute_padding(
    output_width, input_width, filter_width, _params.stride_width, _params.dilation_width_factor);
  return true;
}
References luci::compute::DepthwiseParams::depth_multiplier, luci::compute::DepthwiseParams::dilation_height_factor, luci::compute::DepthwiseParams::dilation_width_factor, loco::TensorShape::dim(), luci::compute::DepthwiseParams::float_activation_max, luci::compute::DepthwiseParams::float_activation_min, luci::compute::get_act_minmax(), luci::compute::PaddingValues::height, luci::compute::DepthwiseParams::padding_type, luci::compute::DepthwiseParams::padding_values, loco::TensorShape::rank(), luci::compute::DepthwiseParams::stride_height, luci::compute::DepthwiseParams::stride_width, loco::Dimension::value(), and luci::compute::PaddingValues::width.
The documentation for this class was generated from the following files:
compiler/luci-compute/include/luci_compute/DepthwiseConv2D.h
compiler/luci-compute/src/DepthwiseConv2D.cpp