ONE - On-device Neural Engine: luci_interpreter::kernels::Pack Class Reference
luci_interpreter::kernels::Pack Class Reference
#include <Pack.h>
Public Member Functions
Pack (std::vector< const Tensor * > inputs, Tensor *output, const PackParams &params)
const Tensor * input (int index) const
Tensor * output () const
void configure () override
void execute () const override
Pack (std::vector< const Tensor * > inputs, Tensor *output, const PackParams &params)
const Tensor * input (int index) const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< PackParams >
const PackParams & params () const
const PackParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< PackParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const PackParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const PackParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< PackParams >
const PackParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Pack.h.
Constructor & Destructor Documentation
Pack() [1/2]
luci_interpreter::kernels::Pack::Pack (std::vector< const Tensor * > inputs, Tensor * output, const PackParams & params)
Definition at line 30 of file Pack.cpp.
  : KernelWithParams<PackParams>(std::move(inputs), {output}, params)
{
}
References output().
Pack() [2/2]
luci_interpreter::kernels::Pack::Pack (std::vector< const Tensor * > inputs, Tensor * output, const PackParams & params)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Pack::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 35 of file Pack.cpp.
{
  LUCI_INTERPRETER_CHECK(_inputs.size() == static_cast<uint32_t>(params().values_count));
  const Tensor *t0 = _inputs[0];
  const int dimension_size = t0->shape().num_dims() + 1;
  int axis = params().axis;
  if (axis < 0)
  {
    axis += dimension_size;
  }
  LUCI_INTERPRETER_CHECK(axis >= 0 && axis <= t0->shape().num_dims());
  if (t0->element_type() != DataType::S32 && t0->element_type() != DataType::FLOAT32 &&
      t0->element_type() != DataType::U8 && t0->element_type() != DataType::S8 &&
      t0->element_type() != DataType::S16 && t0->element_type() != DataType::S64)
  {
    throw std::runtime_error("Unsupported type.");
  }
  for (uint32_t i = 1; i < _inputs.size(); ++i)
  {
    const Tensor *tensor = _inputs[i];
    LUCI_INTERPRETER_CHECK(tensor->element_type() == t0->element_type());
    LUCI_INTERPRETER_CHECK(tensor->shape().num_dims() == t0->shape().num_dims());
    for (int d = 0; d < t0->shape().num_dims(); ++d)
    {
      LUCI_INTERPRETER_CHECK(tensor->shape().dim(d) == t0->shape().dim(d));
    }
  }
  Shape output_shape(dimension_size);
  int i = 0;
  for (int index = 0; index < dimension_size; ++index)
  {
    if (index == axis)
    {
      output_shape.dim(index) = params().values_count;
    }
    else
    {
      output_shape.dim(index) = t0->shape().dim(i++);
    }
  }
  if (t0->element_type() == DataType::U8 || t0->element_type() == DataType::S8 ||
      t0->element_type() == DataType::S16)
  {
    LUCI_INTERPRETER_CHECK(output()->zero_point() == t0->zero_point());
    LUCI_INTERPRETER_CHECK(output()->scale() == t0->scale());
    // Guarantee input/output quantization params match as we do not support
    // packing quantized tensors.
    for (int i = 0; i < params().values_count; i++)
    {
      LUCI_INTERPRETER_CHECK(_inputs[i]->zero_point() == t0->zero_point());
      LUCI_INTERPRETER_CHECK(_inputs[i]->scale() == t0->scale());
    }
  }
  output()->resize(output_shape);
}
References luci_interpreter::Kernel::_inputs, luci_interpreter::PackParams::axis, luci_interpreter::Shape::dim(), luci_interpreter::Tensor::element_type(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< PackParams >::params(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::scale(), luci_interpreter::Tensor::shape(), luci_interpreter::PackParams::values_count, and luci_interpreter::Tensor::zero_point().
configure() [2/2]
void luci_interpreter::kernels::Pack::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Pack::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 96 of file Pack.cpp.
{
  switch (_inputs[0]->element_type())
  {
    case DataType::FLOAT32:
      evalGeneric<float>();
      break;
    case DataType::U8:
      evalGeneric<uint8_t>();
      break;
    case DataType::S8:
      evalGeneric<int8_t>();
      break;
    case DataType::S16:
      evalGeneric<int16_t>();
      break;
    case DataType::S32:
      evalGeneric<int32_t>();
      break;
    case DataType::S64:
      evalGeneric<int64_t>();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::Kernel::_inputs.
execute() [2/2]
void luci_interpreter::kernels::Pack::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Pack::input (int index) const inline
Definition at line 33 of file Pack.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
input() [2/2]
const Tensor * luci_interpreter::kernels::Pack::input (int index) const inline
Definition at line 33 of file Pack.h.
{ return _inputs[index]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Pack::output () const inline
Definition at line 34 of file Pack.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and Pack().
output() [2/2]
Tensor * luci_interpreter::kernels::Pack::output () const inline
Definition at line 34 of file Pack.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Pack.h
onert-micro/luci-interpreter/src/kernels/Pack.h
compiler/luci-interpreter/src/kernels/Pack.cpp
onert-micro/luci-interpreter/src/kernels/Pack.cpp