ONE - On-device Neural Engine: caffeimport::ReLUBuilder Class Reference
caffeimport::ReLUBuilder Class Reference final
#include <ReLU.h>
Public Member Functions
void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const override
Public Member Functions inherited from caffeimport::GraphBuilder
virtual void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 27 of file ReLU.h.
Member Function Documentation
build()
void caffeimport::ReLUBuilder::build (const ::caffe::LayerParameter & layer, GraphBuilderContext * context) const override virtual
Implements caffeimport::GraphBuilder.
Definition at line 32 of file ReLU.cpp.
{
  coco::Module *module = context->module();
  coco::Block *blk = context->block();
  std::map<std::string, tensor::Shape> &shape_ctx = context->shape_ctx();
  std::map<std::string, coco::Bag *> &bag_ctx = context->bag_ctx();
  assert(layer.bottom().size() == 1);
  assert(layer.top().size() == 1);
  // PReLU is not supported, yet
  // TODO Support PReLU
  assert(!layer.has_relu_param());
  // NOTE The current implementation treats ReLU as Feature op
  // TODO Support ReLU over general tensor
  const auto ifm_name = layer.bottom(0);
  const auto ifm_shape = shape_ctx.at(ifm_name);
  auto ifm_bag = bag_ctx.at(ifm_name);
  auto ifm_obj = module->entity()->object()->create<coco::FeatureObject>();
  ifm_obj->bag(ifm_bag);
  ifm_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(ifm_shape)));
  const auto ofm_name = layer.top(0);
  const auto ofm_shape = ifm_shape;
  auto ofm_bag = module->entity()->bag()->create(num_elements(ofm_shape));
  auto ofm_obj = module->entity()->object()->create<coco::FeatureObject>();
  ofm_obj->bag(ofm_bag);
  ofm_obj->layout(coco::FeatureLayouts::BCHW::create(as_feature_shape(ofm_shape)));
  // Create a Load Op
  auto load = op_builder(module).load(ifm_obj).pop();
  // Create a ReLU op
  auto op = module->entity()->op()->create<coco::ReLU>();
  op->arg(load);
  // Create a Eval instruction
  auto ins = instr_builder(module).eval(ofm_obj, op);
  // Append the instruction to the block
  blk->instr()->append(ins);
  // Update bag and shape context
  bag_ctx[ofm_name] = ofm_bag;
  shape_ctx[ofm_name] = ofm_shape;
}
References coco::DLinkedList< Child, Parent >::Head::append(), coco::UnaryOp::arg(), morph::caffe::as_feature_shape(), coco::Object::bag(), coco::EntityManager::bag(), caffeimport::GraphBuilderContext::bag_ctx(), caffeimport::GraphBuilderContext::block(), coco::FeatureLayouts::BCHW::create(), coco::BagManager::create(), coco::ObjectManager::create(), coco::OpManager::create(), coco::Module::entity(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), OpBuilder::load(), caffeimport::GraphBuilderContext::module(), coco::EntityManager::object(), coco::EntityManager::op(), op_builder(), OpBuilder::pop(), and caffeimport::GraphBuilderContext::shape_ctx().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/Layer/ReLU.h
compiler/enco/frontend/caffe/src/Layer/ReLU.cpp