ONE - On-device Neural Engine: QErrorComputer.SRMSEComputer Class Reference
QErrorComputer.SRMSEComputer Class Reference
Public Member Functions
__init__ (self, fp32_dir, fq_dir)
advance_on (self, fp32_dir, fq_dir)
get_final_result (self)
run (self)
Public Member Functions inherited from QErrorComputer.QErrorComputer
collect_data_path (self, fp32_dir, fq_dir)
Data Fields
scale_file
Data Fields inherited from QErrorComputer.QErrorComputer
qerror_map
Protected Attributes
_fq_dir
_fp32_dir
Protected Attributes inherited from QErrorComputer.QErrorComputer
_fp32_dir
_fq_dir
_num_processed_data
_num_data
_tid_to_tname
Detailed Description
Definition at line 210 of file QErrorComputer.py.
Constructor & Destructor Documentation
__init__()
QErrorComputer.SRMSEComputer.__init__ (self, fp32_dir, fq_dir)
Reimplemented from QErrorComputer.QErrorComputer.
Definition at line 211 of file QErrorComputer.py.
    def __init__(self, fp32_dir, fq_dir):
        super().__init__(fp32_dir, fq_dir)
        if fq_dir != None:
            self.scale_file = Path(fq_dir) / 'scales.txt'
References QErrorComputer.SRMSEComputer.__init__().
Referenced by QErrorComputer.SRMSEComputer.__init__().
Member Function Documentation
advance_on()
QErrorComputer.SRMSEComputer.advance_on (self, fp32_dir, fq_dir)
Definition at line 217 of file QErrorComputer.py.
    def advance_on(self, fp32_dir, fq_dir):
        if fq_dir != None:
            self.scale_file = Path(fq_dir) / 'scales.txt'
            self._fq_dir = fq_dir
        data_paths = self.collect_data_path(fp32_dir, fq_dir)
        for tensor_name, data_path in data_paths.items():
            for (fp32_data_path, fq_data_path) in data_path:
                fp32_data = np.load(fp32_data_path)
                fq_data = np.load(fq_data_path)
                MSE = np.square(fp32_data - fq_data).mean()
                self.qerror_map[tensor_name] += MSE
References QErrorComputer.SRMSEComputer.scale_file.
get_final_result()
QErrorComputer.SRMSEComputer.get_final_result (self)
Definition at line 237 of file QErrorComputer.py.
    def get_final_result(self):
        with open(self.scale_file) as f:
            # scale_map: {tensor_name(str) -> scale(float)}
            scale_map = json.load(f)
        qerror_max = 0.0
        qerror_map = dict()
        for tensor_name, acc in self.qerror_map.items():
            MSE = acc / self._num_processed_data
            SRMSE = np.sqrt(MSE) / scale_map[tensor_name]
            qerror_map[tensor_name] = SRMSE
            qerror_max = max(SRMSE, qerror_max)
        return qerror_map, 0.0, qerror_max
References QErrorComputer.QErrorComputer._num_processed_data, QErrorComputer.QErrorComputer.qerror_map, and QErrorComputer.SRMSEComputer.scale_file.
run()
QErrorComputer.SRMSEComputer.run (self)
Return qerror map (dict: tensor_name(string) -> qerror(float)).
Reimplemented from QErrorComputer.QErrorComputer.
Definition at line 252 of file QErrorComputer.py.
    def run(self):
        self.advance_on(self._fp32_dir, self._fq_dir)
        return self.get_final_result()
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper.inference().
Field Documentation
_fp32_dir
QErrorComputer.SRMSEComputer._fp32_dir protected
Definition at line 253 of file QErrorComputer.py.
_fq_dir
QErrorComputer.SRMSEComputer._fq_dir protected
Definition at line 220 of file QErrorComputer.py.
scale_file
QErrorComputer.SRMSEComputer.scale_file
Definition at line 214 of file QErrorComputer.py.
Referenced by QErrorComputer.SRMSEComputer.advance_on(), and QErrorComputer.SRMSEComputer.get_final_result().
The documentation for this class was generated from the following file:
compiler/visq/visqlib/QErrorComputer.py