ONE - On-device Neural Engine: GraphTestcase< GraphCode::ConstGen > Class Reference
GraphTestcase< GraphCode::ConstGen > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::ConstGen * const_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 120 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::ConstGen >::GraphTestcase () inline
Definition at line 123 of file GraphTestcase.h.
  {
    _graph = loco::make_graph();
    auto graph_builder = make_graph_builder(_graph.get());
    const_node = graph_builder->push<ConstGenLayer>()->node();
    push_node = graph_builder->push<OutputLayer>()->name("output")->node();
  }
References loco::make_graph().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::ConstGen >::graph () inline
Definition at line 135 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
const_node
loco::ConstGen* GraphTestcase< GraphCode::ConstGen >::const_node = nullptr
Definition at line 137 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::ConstGen >::push_node = nullptr
Definition at line 138 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h