ONE - On-device Neural Engine: luci_interpreter::kernels::SVDF Class Reference
luci_interpreter::kernels::SVDF Class Reference
#include <SVDF.h>
Public Member Functions
SVDF (const Tensor *input, const Tensor *weight_feature, const Tensor *weight_time, const Tensor *bias, const Tensor *input_activation_state, Tensor *output, Tensor *scratchpad_activation_state, Tensor *scratchpad_1, Tensor *scratchpad_2, Tensor *scratchpad_3, Tensor *scratchpad_4, Tensor *scratchpad_5, Tensor *scratchpad_6, const SVDFParams &params)
const Tensor * input () const
const Tensor * weight_feature () const
const Tensor * weight_time () const
const Tensor * bias () const
const Tensor * input_activation_state () const
Tensor * output () const
void configure () override
void execute () const override
SVDF (const Tensor *input, const Tensor *weight_feature, const Tensor *weight_time, const Tensor *bias, const Tensor *input_activation_state, Tensor *output, Tensor *scratchpad_activation_state, Tensor *scratchpad_1, Tensor *scratchpad_2, Tensor *scratchpad_3, Tensor *scratchpad_4, Tensor *scratchpad_5, Tensor *scratchpad_6, const SVDFParams &params)
const Tensor * input () const
const Tensor * weight_feature () const
const Tensor * weight_time () const
const Tensor * bias () const
const Tensor * input_activation_state () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< SVDFParams >
const SVDFParams & params () const
const SVDFParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< SVDFParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SVDFParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const SVDFParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< SVDFParams >
const SVDFParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file SVDF.h.
Constructor & Destructor Documentation
SVDF() [1/2]
luci_interpreter::kernels::SVDF::SVDF (const Tensor * input, const Tensor * weight_feature, const Tensor * weight_time, const Tensor * bias, const Tensor * input_activation_state, Tensor * output, Tensor * scratchpad_activation_state, Tensor * scratchpad_1, Tensor * scratchpad_2, Tensor * scratchpad_3, Tensor * scratchpad_4, Tensor * scratchpad_5, Tensor * scratchpad_6, const SVDFParams & params)
Definition at line 29 of file SVDF.cpp.
  : KernelWithParams<SVDFParams>({input, weight_feature, weight_time, bias, input_activation_state},
                                 {output, scratchpad_activation_state, scratchpad_1, scratchpad_2,
                                  scratchpad_3, scratchpad_4, scratchpad_5, scratchpad_6},
                                 params)
{
  // Do nothing
}
References bias(), input(), input_activation_state(), weight_feature(), and weight_time().
SVDF() [2/2]
luci_interpreter::kernels::SVDF::SVDF (const Tensor * input, const Tensor * weight_feature, const Tensor * weight_time, const Tensor * bias, const Tensor * input_activation_state, Tensor * output, Tensor * scratchpad_activation_state, Tensor * scratchpad_1, Tensor * scratchpad_2, Tensor * scratchpad_3, Tensor * scratchpad_4, Tensor * scratchpad_5, Tensor * scratchpad_6, const SVDFParams & params)
Member Function Documentation
bias() [1/2]
const Tensor * luci_interpreter::kernels::SVDF::bias () const inline
Definition at line 40 of file SVDF.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SVDF().
bias() [2/2]
const Tensor * luci_interpreter::kernels::SVDF::bias () const inline
Definition at line 40 of file SVDF.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::SVDF::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 42 of file SVDF.cpp.
{
  const Shape &input_shape = input()->shape();
  const Shape &weight_features_shape = weight_feature()->shape();
  const Shape &weight_time_shape = weight_time()->shape();
  // Validate Input Tensor:
  LUCI_INTERPRETER_CHECK(input()->element_type() == loco::DataType::FLOAT32 ||
                         input()->element_type() == loco::DataType::S8);
  LUCI_INTERPRETER_CHECK(input_shape.num_dims() == 2);
  // Validate inputs and output types
  if (input()->element_type() == loco::DataType::S8)
  {
    LUCI_INTERPRETER_CHECK(weight_feature()->element_type() == loco::DataType::S8);
    LUCI_INTERPRETER_CHECK(weight_time()->element_type() == loco::DataType::S16 ||
                           weight_time()->element_type() == loco::DataType::S8);
    if (bias())
      LUCI_INTERPRETER_CHECK(bias()->element_type() == loco::DataType::S32);
    LUCI_INTERPRETER_CHECK(input_activation_state()->element_type() == loco::DataType::S16 ||
                           input_activation_state()->element_type() == loco::DataType::S8);
    LUCI_INTERPRETER_CHECK(output()->element_type() == loco::DataType::S8);
    // Note: now tflite support only ReLU activation for integer SVDF
    LUCI_INTERPRETER_CHECK(params().activation == luci::FusedActFunc::RELU);
  }
  else if (weight_feature()->element_type() == loco::DataType::FLOAT32)
  {
    LUCI_INTERPRETER_CHECK(weight_feature()->element_type() == loco::DataType::FLOAT32);
    LUCI_INTERPRETER_CHECK(weight_time()->element_type() == loco::DataType::FLOAT32);
    LUCI_INTERPRETER_CHECK(input_activation_state()->element_type() == loco::DataType::FLOAT32);
    if (bias())
      LUCI_INTERPRETER_CHECK(bias()->element_type() == loco::DataType::FLOAT32);
    LUCI_INTERPRETER_CHECK(output()->element_type() == loco::DataType::FLOAT32);
  }
  else if ((weight_feature()->element_type() == loco::DataType::U8 ||
            weight_feature()->element_type() == loco::DataType::S8) &&
           input()->element_type() == loco::DataType::FLOAT32)
  {
    // TODO:: support hybrid SVDF op
    throw std::runtime_error("Hybrid type is not currently supported");
  }
  else
  {
    throw std::runtime_error("Unsupported type.");
  }
  // Check all the parameters of tensor match within themselves and match the
  // input configuration.
  const int rank = params().svdf_rank;
  const int batch_size = input_shape.dim(0);
  const int num_filters = weight_features_shape.dim(0);
  LUCI_INTERPRETER_CHECK(rank != 0);
  LUCI_INTERPRETER_CHECK(num_filters % rank == 0);
  const int num_units = num_filters / rank;
  const int memory_size = weight_time_shape.dim(1);
  // Validate Weight_Feature Input Tensor:
  LUCI_INTERPRETER_CHECK(weight_features_shape.num_dims() == 2);
  LUCI_INTERPRETER_CHECK(weight_features_shape.dim(1) == input_shape.dim(1));
  // Validate Weight_Time Input Tensor:
  LUCI_INTERPRETER_CHECK(weight_time_shape.num_dims() == 2);
  LUCI_INTERPRETER_CHECK(weight_time_shape.dim(0) == num_filters);
  // Validate Bias
  if (bias())
    LUCI_INTERPRETER_CHECK(bias()->shape().dim(0) == num_units);
  // Validate Input Activation State
  LUCI_INTERPRETER_CHECK(input_activation_state()->shape().num_dims() == 2);
  LUCI_INTERPRETER_CHECK(input_activation_state()->shape().dim(0) == batch_size);
  LUCI_INTERPRETER_CHECK(input_activation_state()->shape().dim(1) == memory_size * num_filters);
  // Resize scratchpad_state to input_activation_state
  auto scratchpad_activation_state = getOutputTensors()[1];
  scratchpad_activation_state->resize({batch_size, memory_size * num_filters});
  // Resize output tensor
  output()->resize({batch_size, num_units});
  luci_interpreter_pal::SetupScratchpadTensor(
    input()->element_type(), weight_feature()->element_type(), getOutputTensors()[2],
    getOutputTensors()[3], getOutputTensors()[4], getOutputTensors()[5], getOutputTensors()[6],
    getOutputTensors()[7], input_shape, weight_time_shape, batch_size, num_filters, num_units);
}
References bias(), luci_interpreter::Shape::dim(), luci_interpreter::Kernel::getOutputTensors(), input(), input_activation_state(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< SVDFParams >::params(), luci::RELU, luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), luci_interpreter::SVDFParams::svdf_rank, weight_feature(), and weight_time().
configure() [2/2]
void luci_interpreter::kernels::SVDF::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::SVDF::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 131 of file SVDF.cpp.
{
  switch (weight_feature()->element_type())
  {
    case loco::DataType::FLOAT32:
      evalFloat();
      break;
    case loco::DataType::S8:
    {
      if (input()->element_type() == loco::DataType::S8)
        evalInteger();
      else
        // TODO:: support hybrid SVDF op
        throw std::runtime_error("Hybrid type is not currently supported");
      break;
    }
    default:
      throw std::runtime_error("Unsupported type");
  }
}
References input(), and weight_feature().
execute() [2/2]
void luci_interpreter::kernels::SVDF::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::SVDF::input () const inline
Definition at line 37 of file SVDF.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SVDF().
input() [2/2]
const Tensor * luci_interpreter::kernels::SVDF::input () const inline
Definition at line 37 of file SVDF.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
input_activation_state() [1/2]
const Tensor * luci_interpreter::kernels::SVDF::input_activation_state () const inline
Definition at line 41 of file SVDF.h.
{ return _inputs[4]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SVDF().
input_activation_state() [2/2]
const Tensor * luci_interpreter::kernels::SVDF::input_activation_state () const inline
Definition at line 41 of file SVDF.h.
{ return _inputs[4]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::SVDF::output () const inline
Definition at line 43 of file SVDF.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::SVDF::output () const inline
Definition at line 43 of file SVDF.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
weight_feature() [1/2]
const Tensor * luci_interpreter::kernels::SVDF::weight_feature () const inline
Definition at line 38 of file SVDF.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SVDF().
weight_feature() [2/2]
const Tensor * luci_interpreter::kernels::SVDF::weight_feature () const inline
Definition at line 38 of file SVDF.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
weight_time() [1/2]
const Tensor * luci_interpreter::kernels::SVDF::weight_time () const inline
Definition at line 39 of file SVDF.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and SVDF().
weight_time() [2/2]
const Tensor * luci_interpreter::kernels::SVDF::weight_time () const inline
Definition at line 39 of file SVDF.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/SVDF.h
onert-micro/luci-interpreter/src/kernels/SVDF.h
compiler/luci-interpreter/src/kernels/SVDF.cpp
onert-micro/luci-interpreter/src/kernels/SVDF.cpp