ONE - On-device Neural Engine: onert_micro::core::OMTrainingRuntimeModule Class Reference
onert_micro::core::OMTrainingRuntimeModule Class Reference
#include <OMTrainingRuntimeModule.h>
Public Member Functions
OMTrainingRuntimeModule ()=default
OMTrainingRuntimeModule (const OMTrainingRuntimeModule &)=delete
OMTrainingRuntimeModule (OMTrainingRuntimeModule &&)=delete
OMTrainingRuntimeModule & operator= (const OMTrainingRuntimeModule &)=delete
OMTrainingRuntimeModule && operator= (const OMTrainingRuntimeModule &&)=delete
~OMTrainingRuntimeModule ()=default
OMStatus importTrainModel (char *model_ptr, const OMConfig &config)
OMStatus trainSingleStep (OMConfig &config)
OMStatus reset ()
OMStatus evaluateMetric (const OMConfig &config, OMMetrics metric, void *metric_val, uint32_t test_size)
void setInputData (uint8_t *data, uint32_t input_index)
void setTargetData (uint8_t *data, uint32_t target_index)
OMStatus createCheckpointFile (const OMConfig &config, std::vector< char > &data_buffer)
OMStatus loadCheckpointData (OMConfig &config, const char *data)
void * getInputData (int32_t index)
Public Member Functions inherited from onert_micro::core::OMRuntimeModule
OMRuntimeModule ()=default
OMRuntimeModule (const OMRuntimeModule &)=delete
OMRuntimeModule (OMRuntimeModule &&)=delete
OMRuntimeModule & operator= (const OMRuntimeModule &)=delete
OMRuntimeModule && operator= (const OMRuntimeModule &&)=delete
~OMRuntimeModule ()=default
OMStatus importModel (const char *model_ptr, const OMConfig &config)
OMStatus run (const OMConfig &config)
OMStatus reset ()
uint32_t getNumberOfInputs ()
uint32_t getNumberOfOutputs ()
uint32_t getInputSizeAt (uint32_t position)
uint32_t getOutputSizeAt (uint32_t position)
void * getInputDataAt (uint32_t position)
void * getOutputDataAt (uint32_t position)
OMStatus getRuntimeGraphAt (uint32_t pos, OMRuntimeGraph **runtime_graph)
OMStatus allocateInputs ()
Additional Inherited Members
Protected Attributes inherited from onert_micro::core::OMRuntimeModule
std::vector< OMRuntimeGraph > _graphs
Detailed Description
Definition at line 34 of file OMTrainingRuntimeModule.h.
Constructor & Destructor Documentation
OMTrainingRuntimeModule() [1/3]
onert_micro::core::OMTrainingRuntimeModule::OMTrainingRuntimeModule () default
OMTrainingRuntimeModule() [2/3]
onert_micro::core::OMTrainingRuntimeModule::OMTrainingRuntimeModule (const OMTrainingRuntimeModule &) delete
OMTrainingRuntimeModule() [3/3]
onert_micro::core::OMTrainingRuntimeModule::OMTrainingRuntimeModule (OMTrainingRuntimeModule &&) delete
~OMTrainingRuntimeModule()
onert_micro::core::OMTrainingRuntimeModule::~OMTrainingRuntimeModule () default
Member Function Documentation
createCheckpointFile()
OMStatus OMTrainingRuntimeModule::createCheckpointFile (const OMConfig & config, std::vector< char > & data_buffer)
Definition at line 293 of file OMTrainingRuntimeModule.cpp.
{
  // Model wasn't imported
  if (_backward_graphs.size() == 0 or _graphs.size() == 0)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  OMRuntimeContext &context = _backward_graphs.at(0).getRuntimeContext();
  train::OMTrainingStorage &train_storage = _training_handler.getTrainingStorage();
  OMStatus status =
    train::OMCheckpointSaver::createCheckpointData(context, train_storage, data_buffer, config);
  return status;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::core::train::OMCheckpointSaver::createCheckpointData(), onert_micro::core::train::OMTrainingHandler::getTrainingStorage(), OM_LOG_AND_RETURN, and onert_micro::UnknownError.
Referenced by onert_micro::OMTrainingInterpreter::saveCheckpoint().
evaluateMetric()
OMStatus OMTrainingRuntimeModule::evaluateMetric (const OMConfig & config, OMMetrics metric, void * metric_val, uint32_t test_size)
Definition at line 206 of file OMTrainingRuntimeModule.cpp.
{
  OMStatus status = Ok;
  OMRuntimeGraph &forward_main_graph = _graphs.at(0);
  assert(test_size > 0);
  if (test_size == 0)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  uint32_t input_nums = forward_main_graph.getNumberOfInputs();
  for (uint32_t b = 0; b < test_size; ++b)
  {
    //  a. Allocate forward inputs and memcopy current sample (in current batch) into forward inputs
    {
      forward_main_graph.allocateGraphInputs();
      for (uint32_t i = 0; i < input_nums; ++i)
      {
        uint8_t *allocated_input_data =
          reinterpret_cast<uint8_t *>(forward_main_graph.getInputDataAt(i));
        size_t type_size = forward_main_graph.getInputDataTypeSize(i);
        size_t tensor_size = forward_main_graph.getInputSizeAt(i);
        size_t offset = b * type_size * tensor_size;
        uint8_t *input_data = _training_handler.getInputData(i);
        std::memcpy(allocated_input_data, input_data + offset, tensor_size * type_size);
      }
    }
    //  b. Run forward graph
    {
      status = run(config);
      assert(status == Ok);
      if (status != Ok)
        return status;
    }
    // c. Calculate loss on test_size data
    _training_handler.evaluateMetric(metric, metric_val, forward_main_graph.getRuntimeStorage(),
                                     forward_main_graph.getRuntimeContext(), b);
    // Reset values
    forward_main_graph.reset();
  }
  // Averaged result
  {
    float *f_metric_val = reinterpret_cast<float *>(metric_val);
    *f_metric_val /= test_size;
  }
  return Ok;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::core::OMRuntimeGraph::allocateGraphInputs(), onert_micro::core::train::OMTrainingHandler::evaluateMetric(), onert_micro::core::train::OMTrainingHandler::getInputData(), onert_micro::core::OMRuntimeGraph::getInputDataAt(), onert_micro::core::OMRuntimeGraph::getInputDataTypeSize(), onert_micro::core::OMRuntimeGraph::getInputSizeAt(), onert_micro::core::OMRuntimeGraph::getNumberOfInputs(), onert_micro::core::OMRuntimeGraph::getRuntimeContext(), onert_micro::core::OMRuntimeGraph::getRuntimeStorage(), offset(), onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::core::OMRuntimeGraph::reset(), onert_micro::core::OMRuntimeModule::run(), and onert_micro::UnknownError.
Referenced by onert_micro::OMTrainingInterpreter::evaluateMetric().
getInputData()
void * OMTrainingRuntimeModule::getInputData (int32_t index)
Definition at line 327 of file OMTrainingRuntimeModule.cpp.
{
  return _training_handler.getInputData(index);
}
References onert_micro::core::train::OMTrainingHandler::getInputData().
Referenced by onert_micro::OMTrainingInterpreter::getInputData().
importTrainModel()
OMStatus OMTrainingRuntimeModule::importTrainModel (char * model_ptr, const OMConfig & config)
Definition at line 34 of file OMTrainingRuntimeModule.cpp.
{
  // 1 - Import main model
  // 2 - Import and create training entities
  // 1 - Import main model
  OMStatus status = importModel(model_ptr, config);
  if (status != Ok)
    return status;
  // 2 - Import and create training entities
  _backward_graphs.resize(_graphs.size());
  for (uint32_t i = 0; i < _backward_graphs.size(); ++i)
  {
    // load default backward graph
    OMRuntimeGraph &graph = _backward_graphs.at(i);
    OMRuntimeContext &runtime_context = graph.getRuntimeContext();
    OMRuntimeStorage &runtime_storage = graph.getRuntimeStorage();
    memory::OMRuntimeAllocator &runtime_allocator = graph.getRuntimeAllocator();
    runtime_context.setModel(model_ptr, i);
    // Parse and validate WOF file if it is exist
    // WARNING: setWofFile method of RuntimeContext should follow after setModel.
    if (config.wof_ptr != nullptr)
      runtime_context.setWofFile(config.wof_ptr);
    // Parse and validate Train Config File if it is exists
    // WARNING: setTrainConfigFile method of RuntimeContext should follow after setModel.
    if (config.train_mode and config.training_context.training_config_info_data != nullptr)
      runtime_context.setTrainConfigFile(config.training_context.training_config_info_data);
    // AllocDeallocPlan backward graph creation
    status = import::OMExecutionPlanCreator::createBackwardExecutionPlan(
      runtime_storage, runtime_context, runtime_allocator, config);
    if (status != Ok)
      return status;
    // Set tensor to train rank type
    auto &train_storage = _training_handler.getTrainingStorage();
    import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(
      runtime_storage, runtime_context, train_storage);
  }
  // Set current optimizer
  _training_handler.setOptimizer(config);
  return Ok;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::import::OMExecutionPlanCreator::createBackwardExecutionPlan(), onert_micro::core::train::OMTrainingHandler::getTrainingStorage(), onert_micro::import::OMDynamicShapesHandler::importDynamicShapesFromTrainConfig(), onert_micro::core::OMRuntimeModule::importModel(), onert_micro::Ok, onert_micro::core::OMRuntimeContext::setModel(), onert_micro::core::train::OMTrainingHandler::setOptimizer(), onert_micro::core::OMRuntimeContext::setTrainConfigFile(), and onert_micro::core::OMRuntimeContext::setWofFile().
Referenced by onert_micro::OMTrainingInterpreter::importTrainModel().
loadCheckpointData()
OMStatus OMTrainingRuntimeModule::loadCheckpointData (OMConfig & config, const char * data)
Definition at line 312 of file OMTrainingRuntimeModule.cpp.
{
  // Model wasn't imported
  if (_backward_graphs.size() == 0 or _graphs.size() == 0)
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  OMRuntimeContext &context = _backward_graphs.at(0).getRuntimeContext();
  train::OMTrainingStorage &train_storage = _training_handler.getTrainingStorage();
  OMStatus status =
    train::OMCheckpointLoader::loadCheckpointData(context, train_storage, data, config);
  return status;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::core::train::OMTrainingHandler::getTrainingStorage(), onert_micro::core::train::OMCheckpointLoader::loadCheckpointData(), OM_LOG_AND_RETURN, and onert_micro::UnknownError.
Referenced by onert_micro::OMTrainingInterpreter::loadCheckpoint().
operator=() [1/2]
OMTrainingRuntimeModule && onert_micro::core::OMTrainingRuntimeModule::operator= (const OMTrainingRuntimeModule &&) delete
operator=() [2/2]
OMTrainingRuntimeModule & onert_micro::core::OMTrainingRuntimeModule::operator= (const OMTrainingRuntimeModule &) delete
reset()
OMStatus OMTrainingRuntimeModule::reset ()
Definition at line 263 of file OMTrainingRuntimeModule.cpp.
{
  OMStatus status = Ok;
  if (_graphs.empty())
    return ModelNotImport;
  for (auto &graph : _graphs)
  {
    graph.reset();
  }
  for (auto &graph : _backward_graphs)
  {
    graph.reset();
  }
#ifdef OM_MEMORY_ESTIMATE
  auto &context = _backward_graphs.begin()->getRuntimeContext();
  auto &storage = _backward_graphs.begin()->getRuntimeStorage();
  _training_handler.reset(context, storage);
#else
  _training_handler.reset();
#endif // OM_MEMORY_ESTIMATE
  return status;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::ModelNotImport, onert_micro::Ok, and onert_micro::core::train::OMTrainingHandler::reset().
Referenced by onert_micro::OMTrainingInterpreter::reset().
setInputData()
void onert_micro::core::OMTrainingRuntimeModule::setInputData (uint8_t * data, uint32_t input_index) inline
Definition at line 76 of file OMTrainingRuntimeModule.h.
  {
    _training_handler.setInputData(data, input_index);
  }
References onert_micro::core::train::OMTrainingHandler::setInputData().
Referenced by onert_micro::OMTrainingInterpreter::setInput().
setTargetData()
void onert_micro::core::OMTrainingRuntimeModule::setTargetData (uint8_t * data, uint32_t target_index) inline
Definition at line 82 of file OMTrainingRuntimeModule.h.
  {
    _training_handler.setTargetData(data, target_index);
  }
References onert_micro::core::train::OMTrainingHandler::setTargetData().
Referenced by onert_micro::OMTrainingInterpreter::setTarget().
trainSingleStep()
OMStatus OMTrainingRuntimeModule::trainSingleStep (OMConfig & config)
Definition at line 91 of file OMTrainingRuntimeModule.cpp.
{
  OMStatus status = Ok;
  uint32_t batch_size = config.training_context.batch_size;
  config.training_context.num_step += 1;
  // A - Run and update optimizers state batch_size times
  //  a. Allocate forward inputs and memcopy current sample (in current batch) into forward inputs
  //  b. Run forward graph
  //  c. Handle (calculate) current error backpropagation function result
  //  d. Run backward graph (calculate backpropagation values)
  //  e. Update optimization state
  //  f. Reset runtime graphs (to deallocate forward outputs)
  // B - Update weights according chosen optimization strategy (after batch_size times)
  // A
  for (uint32_t b = 0; b < batch_size; ++b)
  {
    //  a. Allocate forward inputs and memcopy current sample (in current batch) into forward inputs
    {
      OMRuntimeGraph &forward_main_graph = _graphs.at(0);
      forward_main_graph.allocateGraphInputs();
      uint32_t input_nums = forward_main_graph.getNumberOfInputs();
      for (uint32_t i = 0; i < input_nums; ++i)
      {
        uint8_t *allocated_input_data =
          reinterpret_cast<uint8_t *>(forward_main_graph.getInputDataAt(i));
        size_t type_size = forward_main_graph.getInputDataTypeSize(i);
        size_t tensor_size = forward_main_graph.getInputSizeAt(i);
        size_t offset = b * type_size * tensor_size;
        uint8_t *input_data = _training_handler.getInputData(i);
        std::memcpy(allocated_input_data, input_data + offset, tensor_size * type_size);
      }
    }
    //  b. Run forward graph
    {
      status = run(config);
      assert(status == Ok);
      if (status != Ok)
        return status;
    }
    if (_backward_graphs.empty())
      return ModelNotImport;
    for (uint32_t i = 0; i < _graphs.size(); ++i)
    {
      // Get forward entities
      OMRuntimeGraph &forward_graph = _graphs.at(i);
      OMRuntimeContext &forward_context = forward_graph.getRuntimeContext();
      OMRuntimeStorage &forward_storage = forward_graph.getRuntimeStorage();
      // Get backward entities
      OMRuntimeGraph &backward_graph = _backward_graphs.at(i);
      OMRuntimeContext &backward_context = backward_graph.getRuntimeContext();
      OMRuntimeStorage &backward_storage = backward_graph.getRuntimeStorage();
      //  c. Handle (calculate) current error backpropagation function result
      {
        status = _training_handler.handleError(config, forward_storage, backward_storage,
                                               backward_context, b);
        assert(status == Ok);
        if (status != Ok)
          return status;
      }
      //  d. Run backward graph
      {
        onert_micro::train::OMBackpropExecuteArgs backprop_execute_args = {
          forward_storage, backward_storage, backward_context, false, false, 0, ALL};
        status = onert_micro::train::OMBackpropExecute::runBackward(
          config, backprop_execute_args, backward_graph.getRuntimeAllocator());
        assert(status == Ok);
        if (status != Ok)
          return status;
      }
      //  e. Update optimization state
      {
        status = _training_handler.updateOptimizerState(config, backward_storage, backward_context);
        assert(status == Ok);
        if (status != Ok)
          return status;
      }
      //  f. Reset runtime graphs
      backward_graph.reset();
      forward_graph.reset();
    }
  }
  // B - Update weights according chosen optimization strategy
  for (uint32_t i = 0; i < _graphs.size(); ++i)
  {
    // Get backward context
    OMRuntimeGraph &backward_graph = _backward_graphs.at(i);
    OMRuntimeContext &backward_context = backward_graph.getRuntimeContext();
    OMRuntimeStorage &backward_storage = backward_graph.getRuntimeStorage();
    status = _training_handler.updateWeights(config, backward_context, backward_storage);
  }
  return status;
}
References onert_micro::core::OMRuntimeModule::_graphs, onert_micro::core::ALL, onert_micro::core::OMRuntimeGraph::allocateGraphInputs(), onert_micro::core::train::OMTrainingHandler::getInputData(), onert_micro::core::OMRuntimeGraph::getInputDataAt(), onert_micro::core::OMRuntimeGraph::getInputDataTypeSize(), onert_micro::core::OMRuntimeGraph::getInputSizeAt(), onert_micro::core::OMRuntimeGraph::getNumberOfInputs(), onert_micro::core::OMRuntimeGraph::getRuntimeAllocator(), onert_micro::core::OMRuntimeGraph::getRuntimeContext(), onert_micro::core::OMRuntimeGraph::getRuntimeStorage(), onert_micro::core::train::OMTrainingHandler::handleError(), onert_micro::ModelNotImport, offset(), onert_micro::Ok, onert_micro::core::OMRuntimeGraph::reset(), onert_micro::core::OMRuntimeModule::run(), onert_micro::train::OMBackpropExecute::runBackward(), onert_micro::core::train::OMTrainingHandler::updateOptimizerState(), and onert_micro::core::train::OMTrainingHandler::updateWeights().
Referenced by onert_micro::OMTrainingInterpreter::trainSingleStep().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/OMTrainingRuntimeModule.h
onert-micro/onert-micro/src/core/OMTrainingRuntimeModule.cpp