ONE - On-device Neural Engine: onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor > Class Template Reference
onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor > Class Template Reference
#include <ITensorRegistry.h>
Public Types
using TrainingTensors = std::tuple< TrainableTensor *, GradientTensor * >
Public Member Functions
ITensor * getITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native tensors.
ITensor * getDerivativeITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for derivative.
ITensor * getGradientITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for gradient.
IPortableTensor * getPortableTensor (const ir::OperandIndex &index)
Tensor * getNonConstTensor (const ir::OperandIndex &index)
TrainableTensor * getTrainableTensor (const ir::OperandIndex &index)
DerivativeTensor * getDerivativeTensor (const ir::OperandIndex &index)
GradientTensor * getGradientTensor (const ir::OperandIndex &index)
TrainingTensors getTrainingTensors (const ir::OperandIndex &index)
bool setMigrantTensor (const ir::OperandIndex &index, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void setNonConstTensor (const ir::OperandIndex &index, std::unique_ptr< Tensor > tensor)
void setTrainableTensor (const ir::OperandIndex &index, std::unique_ptr< TrainableTensor > tensor)
void setDerivativeTensor (const ir::OperandIndex &index, std::unique_ptr< DerivativeTensor > tensor)
void setGradientTensor (const ir::OperandIndex &index, std::unique_ptr< GradientTensor > tensor)
const ir::OperandIndexMap< std::unique_ptr< TrainableTensor > > & trainable_tensors ()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & nonconst_tensors ()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & derivative_tensors ()
const ir::OperandIndexMap< std::unique_ptr< GradientTensor > > & gradient_tensors ()
virtual ITensor * getDerivativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for derivative.
virtual ITensor * getGradientITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for gradient.
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Detailed Description
template<typename Tensor, typename TrainableTensor, typename DerivativeTensor, typename GradientTensor>
class onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >
Definition at line 72 of file ITensorRegistry.h.
Member Typedef Documentation
TrainingTensors
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > using onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::TrainingTensors = std::tuple<TrainableTensor *, GradientTensor *>
Definition at line 75 of file ITensorRegistry.h.
Member Function Documentation
derivative_tensors()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > const ir::OperandIndexMap< std::unique_ptr< Tensor > > & onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::derivative_tensors () inline
Definition at line 221 of file ITensorRegistry.h.
{ return _derivative; }
getDerivativeITensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > ITensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getDerivativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor for derivative.
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::train::ITensorRegistry.
Definition at line 94 of file ITensorRegistry.h.
  {
    return getDerivativeTensor(index);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getDerivativeTensor().
getDerivativeTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > DerivativeTensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getDerivativeTensor (const ir::OperandIndex & index) inline
Definition at line 132 of file ITensorRegistry.h.
  {
    auto tensor = _derivative.find(index);
    if (tensor != _derivative.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getDerivativeITensor().
getGradientITensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > ITensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getGradientITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor for gradient.
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::train::ITensorRegistry.
Definition at line 99 of file ITensorRegistry.h.
  {
    return getGradientTensor(index);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getGradientTensor().
getGradientTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > GradientTensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getGradientTensor (const ir::OperandIndex & index) inline
Definition at line 140 of file ITensorRegistry.h.
  {
    auto tensor = _gradient.find(index);
    if (tensor != _gradient.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getGradientITensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainingTensors().
getITensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > ITensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 78 of file ITensorRegistry.h.
  {
    auto _migrant_tensor = _migrant.find(index);
    if (_migrant_tensor != _migrant.end())
      return _migrant_tensor->second;
    return getNativeITensor(index);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNativeITensor().
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setMigrantTensor(), onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setNonConstTensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setTrainableTensor().
getNativeITensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > ITensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 86 of file ITensorRegistry.h.
  {
    ITensor *tensor = getTrainableTensor(index);
    if (tensor == nullptr)
      tensor = getNonConstTensor(index);
    return tensor;
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNonConstTensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainableTensor().
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor().
getNonConstTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > Tensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNonConstTensor (const ir::OperandIndex & index) inline
Definition at line 115 of file ITensorRegistry.h.
  {
    auto tensor = _non_const.find(index);
    if (tensor != _non_const.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNativeITensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getPortableTensor().
getPortableTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > IPortableTensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getPortableTensor (const ir::OperandIndex & index) inline
Definition at line 104 of file ITensorRegistry.h.
  {
    auto tensor = _trainable.find(index);
    if (tensor != _trainable.end())
    {
      if (tensor->second)
        return tensor->second.get();
    }
    return getNonConstTensor(index);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNonConstTensor().
getTrainableTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > TrainableTensor * onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainableTensor (const ir::OperandIndex & index) inline
Definition at line 123 of file ITensorRegistry.h.
  {
    auto tensor = _trainable.find(index);
    if (tensor != _trainable.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getNativeITensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainingTensors().
getTrainingTensors()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > TrainingTensors onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainingTensors (const ir::OperandIndex & index) inline
Definition at line 148 of file ITensorRegistry.h.
  {
    auto trainable = getTrainableTensor(index);
    if (trainable == nullptr)
      throw std::runtime_error{
        "Tried to get a trainable tensor but the corresponding tensor does not exist."};
    auto gradient = getGradientTensor(index);
    if (gradient == nullptr)
      throw std::runtime_error{
        "Tried to get a gradient tensor but the corresponding tensor does not exist."};
    return TrainingTensors{std::make_pair(trainable, gradient)};
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getGradientTensor(), and onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getTrainableTensor().
gradient_tensors()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > const ir::OperandIndexMap< std::unique_ptr< GradientTensor > > & onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::gradient_tensors () inline
Definition at line 222 of file ITensorRegistry.h.
  {
    return _gradient;
  }
nonconst_tensors()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > const ir::OperandIndexMap< std::unique_ptr< Tensor > > & onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::nonconst_tensors () inline
Definition at line 220 of file ITensorRegistry.h.
{ return _non_const; }
setDerivativeTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > void onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setDerivativeTensor (const ir::OperandIndex & index, std::unique_ptr< DerivativeTensor > tensor) inline
Definition at line 194 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _derivative.find(index);
    if (itr != _derivative.end())
      throw std::runtime_error{
        "Tried to set a derivative tensor but another derivative tensor already exists."};
    _derivative[index] = std::move(tensor);
  }
setGradientTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > void onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setGradientTensor (const ir::OperandIndex & index, std::unique_ptr< GradientTensor > tensor) inline
Definition at line 205 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _gradient.find(index);
    if (itr != _gradient.end())
      throw std::runtime_error{
        "Tried to set a gradient tensor but another gradient tensor already exists."};
    _gradient[index] = std::move(tensor);
  }
setMigrantTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > bool onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setMigrantTensor (const ir::OperandIndex & , IPortableTensor *) inline override virtual
Set the Migrant Tensor which are from other backends.
Returns
true if supported
false if not supported
Reimplemented from onert::backend::ITensorRegistry.
Definition at line 163 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    if (getITensor(index) != nullptr)
      throw std::runtime_error{
        "Tried to set a trainable tensor but another tensor already exists."};
    _migrant[index] = tensor;
    return true;
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor().
setNonConstTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > void onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setNonConstTensor (const ir::OperandIndex & index, std::unique_ptr< Tensor > tensor) inline
Definition at line 174 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    if (getITensor(index) != nullptr)
      throw std::runtime_error{
        "Tried to set a trainable tensor but another tensor already exists."};
    _non_const[index] = std::move(tensor);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor().
setTrainableTensor()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > void onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setTrainableTensor (const ir::OperandIndex & index, std::unique_ptr< TrainableTensor > tensor) inline
Definition at line 184 of file ITensorRegistry.h.
  {
    assert(tensor != nullptr);
    if (getITensor(index) != nullptr)
      throw std::runtime_error{
        "Tried to set a trainable tensor but another tensor already exists."};
    _trainable[index] = std::move(tensor);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor().
trainable_tensors()
template<typename Tensor , typename TrainableTensor , typename DerivativeTensor , typename GradientTensor > const ir::OperandIndexMap< std::unique_ptr< TrainableTensor > > & onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::trainable_tensors () inline
Definition at line 216 of file ITensorRegistry.h.
  {
    return _trainable;
  }
The documentation for this class was generated from the following file:
runtime/onert/core/include/backend/train/ITensorRegistry.h