ONE - On-device Neural Engine: circletensordump::DumpTensorsToHdf5 Class Reference
circletensordump::DumpTensorsToHdf5 Class Reference final
#include <Dump.h>
Public Member Functions
DumpTensorsToHdf5 ()=default
void run (std::ostream &os, const circle::Model *model, const std::string &output_path) override
Public Member Functions inherited from circletensordump::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const circle::Model *model, const std::string &output_path={})=0
Detailed Description
Definition at line 46 of file Dump.h.
Constructor & Destructor Documentation
DumpTensorsToHdf5()
circletensordump::DumpTensorsToHdf5::DumpTensorsToHdf5 () default
Member Function Documentation
run()
void circletensordump::DumpTensorsToHdf5::run (std::ostream & os, const circle::Model * model, const std::string & output_path) override virtual
HDF5 layout is like below
GROUP "/" ㄴGROUP "tensor name" ㄴDATASET "weights" : Shape (x, y, ...), type(uint8, int16) ㄴDATASET "min" : Shape (n) ㄴDATASET "max" : Shape (n) ㄴDATASET "scale" : Shape (m) ㄴDATASET "zero_point" : Shape (m)
NOTE All Dataset is optional. It means that if tensor doesn't have the data, it won't be created as a Dataset
Implements circletensordump::DumpInterface.
Definition at line 296 of file Dump.cpp.
{
  // loads a circle model
  mio::circle::Reader reader(model);
  uint32_t num_subgraph = reader.num_subgraph();
  // create a hdf5 file
  H5::H5File file{output_path, H5F_ACC_TRUNC};
  for (uint32_t subgraph_idx = 0; subgraph_idx < num_subgraph; subgraph_idx++)
  {
    reader.select_subgraph(subgraph_idx);
    auto tensors = reader.tensors();
    for (const auto &tensor : *tensors)
    {
      // If tensor does not have name, do nothing.
      const auto tensor_name = tensor->name();
      if (tensor_name == nullptr)
      {
        assert(false && "There is no tensor name");
        continue;
      }
      // create a group for each tensor whose name is its tensor name
      std::string group_name = ::mangle(tensor_name->c_str());
      std::unique_ptr<H5::Group> tensor_group =
        std::make_unique<H5::Group>(file.createGroup(group_name));
      // write a buffer data
      uint32_t buff_idx = tensor->buffer();
      auto buff_data_ptr = reader.buffers()->Get(buff_idx)->data();
      if (buff_data_ptr)
      {
        ::write_vector_data_to_hdf5(file, group_name, "weights", ::hdf5_dtype_cast(tensor->type()),
                                    buff_data_ptr,
                                    ::hdf5_dims_cast(buff_data_ptr, tensor->shape()));
      }
      // write quantization parameters
      auto quant_param = tensor->quantization();
      if (quant_param)
      {
        auto min = quant_param->min();
        ::write_vector_data_to_hdf5(file, group_name, "min", H5::PredType::NATIVE_FLOAT, min,
                                    ::hdf5_dims_cast(min));
        auto max = quant_param->max();
        ::write_vector_data_to_hdf5(file, group_name, "max", H5::PredType::NATIVE_FLOAT, max,
                                    ::hdf5_dims_cast(max));
        auto scale = quant_param->scale();
        ::write_vector_data_to_hdf5(file, group_name, "scale", H5::PredType::NATIVE_FLOAT, scale,
                                    ::hdf5_dims_cast(scale));
        auto zero_point = quant_param->zero_point();
        ::write_vector_data_to_hdf5(file, group_name, "zero_point", H5::PredType::NATIVE_INT64,
                                    zero_point, ::hdf5_dims_cast(zero_point));
        auto quantized_dimension = quant_param->quantized_dimension();
        ::write_scalar_data_to_hdf5(file, group_name, "quantized_dimension",
                                    H5::PredType::NATIVE_INT32, quantized_dimension);
      }
    }
  }
}
References mio::circle::Reader::buffers(), mangle(), mio::circle::Reader::num_subgraph(), mio::circle::Reader::select_subgraph(), and mio::circle::Reader::tensors().
The documentation for this class was generated from the following files:
compiler/circle-tensordump/src/Dump.h
compiler/circle-tensordump/src/Dump.cpp