ONE - On-device Neural Engine: onert::ir::train::operation::Loss Class Reference
onert::ir::train::operation::Loss Class Reference
#include <Loss.h>
Public Member Functions
Loss (const OperationType &operation, const LossInfo &info)
std::unique_ptr< ITrainableOperation > clone () const override
void accept (OperationVisitor &v) const override
void accept (TrainableOperationVisitor &v) const override
bool hasTrainableParameter () const override
std::string name () const override
const LossInfo & param () const
Public Member Functions inherited from onert::ir::operation::Loss
Loss (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs)
OpCode opcode () const final
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
void replaceInputs (const OperandIndex &from, const OperandIndex &to) override
void replaceOutputs (const OperandIndex &from, const OperandIndex &to) override
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const override
const OperandIndexSequence & getOutputs () const override
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Public Member Functions inherited from onert::ir::IOperation
virtual ~IOperation ()=default
Public Member Functions inherited from onert::ir::train::ITrainableOperation
virtual ~ITrainableOperation ()=default
Additional Inherited Members
Public Types inherited from onert::ir::operation::Loss
enum Input { Y_PRED = 0 , Y_TRUE = 1 }
Detailed Description
Definition at line 35 of file Loss.h.
Constructor & Destructor Documentation
Loss()
onert::ir::train::operation::Loss::Loss (const OperationType & operation, const LossInfo & info)
Definition at line 39 of file Loss.cc.
  : OperationType{operation.getInputs(), operation.getOutputs()}, _param{param}
{
  // DO NOTHING
}
Member Function Documentation
accept() [1/2]
void onert::ir::train::operation::Loss::accept (OperationVisitor & v) const override virtual
Reimplemented from onert::ir::operation::Loss.
Definition at line 35 of file Loss.cc.
{ v.visit(*this); }
accept() [2/2]
void onert::ir::train::operation::Loss::accept (TrainableOperationVisitor & v) const override virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 37 of file Loss.cc.
{ v.visit(*this); }
clone()
std::unique_ptr< ITrainableOperation > onert::ir::train::operation::Loss::clone () const override virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 33 of file Loss.cc.
{ return std::make_unique<Loss>(*this); }
hasTrainableParameter()
bool onert::ir::train::operation::Loss::hasTrainableParameter () const inline override virtual
Implements onert::ir::train::ITrainableOperation.
Definition at line 47 of file Loss.h.
{ return false; }
name()
std::string onert::ir::train::operation::Loss::name () const inline override virtual
Reimplemented from onert::ir::IOperation.
Definition at line 48 of file Loss.h.
{ return toString(_param.loss_code) + toString(opcode()); };
References onert::ir::train::LossInfo::loss_code, onert::ir::operation::Loss::opcode(), and onert::ir::train::toString().
param()
const LossInfo & onert::ir::train::operation::Loss::param () const inline
Definition at line 51 of file Loss.h.
{ return _param; }
Referenced by onert::backend::train::KernelGenerator::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/train/operation/Loss.h
runtime/onert/core/src/ir/train/operation/Loss.cc