ONE - On-device Neural Engine: onert::backend::cpu::ops::SoftMaxLayer Class Reference
onert::backend::cpu::ops::SoftMaxLayer Class Reference
#include <SoftMaxLayer.h>
Public Member Functions
SoftMaxLayer ()
void softmaxFloat32 ()
template<typename T >
void softmaxQuant8 ()
void configure (const IPortableTensor *input, const float beta, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Protected Attributes
const IPortableTensor * _input
IPortableTensor * _output
Detailed Description
Definition at line 33 of file SoftMaxLayer.h.
Constructor & Destructor Documentation
SoftMaxLayer()
onert::backend::cpu::ops::SoftMaxLayer::SoftMaxLayer ()
Definition at line 32 of file SoftMaxLayer.cc.
                           : _input(nullptr), _output(nullptr), _beta(0.0)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::SoftMaxLayer::configure (const IPortableTensor * input, const float beta, IPortableTensor * output)
Definition at line 88 of file SoftMaxLayer.cc.
{
  _input = input;
  _output = output;
  _beta = beta;
  if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM ||
      _input->data_type() == OperandType::QUANT_INT8_ASYMM)
  {
#ifdef TFLITE_SOFTMAX_USE_UINT16_LUT
    // Only apply when both input & output are uint8/int8 & build with clang
    // on aarch64.
    nnfw::cker::PopulateSoftmaxUInt8LookupTable(_uint8_table1, _uint8_table2, _input->data_scale(),
                                                _beta);
#else
    nnfw::cker::PopulateSoftmaxLookupTable(_table, _input->data_scale(), _beta);
#endif
  }
}
References _input, _output, onert::backend::IPortableTensor::data_scale(), onert::backend::ITensor::data_type(), and nnfw::cker::PopulateSoftmaxLookupTable().
run()
void onert::backend::cpu::ops::SoftMaxLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 109 of file SoftMaxLayer.cc.
{
  switch (_input->data_type())
  {
    case OperandType::FLOAT32:
      softmaxFloat32();
      break;
    case OperandType::QUANT_UINT8_ASYMM:
      softmaxQuant8<uint8_t>();
      break;
    case OperandType::QUANT_INT8_ASYMM:
      softmaxQuant8<int8_t>();
      break;
    default:
      throw std::runtime_error{"SoftMax: unsupported data type"};
  }
}
References _input, onert::backend::ITensor::data_type(), and softmaxFloat32().
Referenced by onert::backend::train::ops::SoftMaxLayer::forward(), and package.libnnfw_api_pybind.nnfw_session_wrapper::inference().
softmaxFloat32()
void onert::backend::cpu::ops::SoftMaxLayer::softmaxFloat32 ()
Definition at line 37 of file SoftMaxLayer.cc.
{
  if (getNumberOfDimensions(_input) == 1)
  {
    uint32_t input_size = getNumberOfElements(_input);
    nnfw::cker::Softmax(getBuffer<float>(_input), input_size, 1, _beta, getBuffer<float>(_output));
  }
  else if (getNumberOfDimensions(_input) == 2)
  {
    uint32_t batch_size = getSizeOfDimension(_input, 0);
    if (batch_size == 0)
      throw std::runtime_error("batch_size should not be 0");
    uint32_t input_size = getNumberOfElements(_input) / batch_size;
    nnfw::cker::Softmax(getBuffer<float>(_input), input_size, batch_size, _beta,
                        getBuffer<float>(_output));
  }
  else if (getNumberOfDimensions(_input) == 4)
  {
    nnfw::cker::SoftmaxParams op_params;
    op_params.beta = _beta;
    nnfw::cker::Softmax(op_params, getShape(_input), getBuffer<float>(_input), getShape(_output),
                        getBuffer<float>(_output));
  }
  else
  {
    nnfw::cker::SoftmaxParams op_params;
    op_params.beta = _beta;
    nnfw::cker::reference::Softmax(op_params, getShape(_input), getBuffer<float>(_input),
                                   getShape(_output), getBuffer<float>(_output));
  }
}
References _input, _output, nnfw::cker::SoftmaxParams::beta, getNumberOfDimensions(), getNumberOfElements(), onert::backend::cpu::ops::getShape(), getSizeOfDimension(), nnfw::cker::Softmax(), and nnfw::cker::reference::Softmax().
Referenced by run().
softmaxQuant8()
template<typename T > void onert::backend::cpu::ops::SoftMaxLayer::softmaxQuant8 ()
Definition at line 70 of file SoftMaxLayer.cc.
{
  nnfw::cker::SoftmaxParams op_params;
  op_params.scale = _output->data_scale();
  op_params.zero_point = _output->data_zero_point();
  op_params.uint8_table1 = _uint8_table1;
  op_params.uint8_table2 = _uint8_table2;
  op_params.table = _table;
#ifdef TFLITE_SOFTMAX_USE_UINT16_LUT
  nnfw::cker::SoftmaxInt8LUT<T, T>(op_params, getShape(_input), getBuffer<T>(_input),
                                   getShape(_output), getBuffer<T>(_output));
#else
  nnfw::cker::Softmax<T, T>(op_params, getShape(_input), getBuffer<T>(_input), getShape(_output),
                            getBuffer<T>(_output));
#endif
}
References _input, _output, onert::backend::IPortableTensor::data_scale(), onert::backend::IPortableTensor::data_zero_point(), onert::backend::cpu::ops::getShape(), nnfw::cker::SoftmaxParams::scale, nnfw::cker::SoftmaxParams::table, nnfw::cker::SoftmaxParams::uint8_table1, nnfw::cker::SoftmaxParams::uint8_table2, and nnfw::cker::SoftmaxParams::zero_point.
Field Documentation
_input
const IPortableTensor* onert::backend::cpu::ops::SoftMaxLayer::_input protected
Definition at line 48 of file SoftMaxLayer.h.
Referenced by onert::backend::train::ops::SoftMaxLayer::backward(), configure(), run(), softmaxFloat32(), and softmaxQuant8().
_output
IPortableTensor* onert::backend::cpu::ops::SoftMaxLayer::_output protected
Definition at line 49 of file SoftMaxLayer.h.
Referenced by onert::backend::train::ops::SoftMaxLayer::backward(), configure(), softmaxFloat32(), and softmaxQuant8().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/SoftMaxLayer.h
runtime/onert/backend/cpu/ops/SoftMaxLayer.cc