ONE - On-device Neural Engine: mpqsolver::core::DumpingHooks Class Reference
mpqsolver::core::DumpingHooks Class Reference final
DumpingHooks is intended to save intermediate results.
#include <DumpingHooks.h>
Public Member Functions
DumpingHooks (const std::string &save_path)
DumpingHooks constructor.
virtual void onQuantized (luci::Module *module) const override
called on successfull quantization
virtual void onBeginSolver (const std::string &model_path, float q8error, float q16error) override
called on the start of iterative search
virtual void onBeginIteration () override
called on the start of current iteration
virtual void onEndIteration (const LayerParams &layers, const std::string &def_dtype, float error) const override
called at the end of current iteration
virtual void onEndSolver (const LayerParams &layers, const std::string &def_dtype, float qerror) override
called at the end of iterative search
virtual void onQuantized (luci::Module *module) const =0
called on successfull quantization
virtual void onBeginSolver (const std::string &model_path, float q8error, float q16error)=0
called on the start of iterative search
virtual void onBeginIteration ()=0
called on the start of current iteration
virtual void onEndIteration (const LayerParams &layers, const std::string &def_dtype, float error) const =0
called at the end of current iteration
virtual void onEndSolver (const LayerParams &layers, const std::string &def_dtype, float qerror)=0
called at the end of iterative search
Protected Attributes
std::string _model_path
std::string _save_path
Dumper _dumper
uint32_t _num_of_iterations = 0
bool _in_iterations = false
Detailed Description
DumpingHooks is intended to save intermediate results.
Definition at line 36 of file DumpingHooks.h.
Constructor & Destructor Documentation
DumpingHooks()
DumpingHooks::DumpingHooks (const std::string & save_path)
DumpingHooks constructor.
Parameters
save_path directory where all intermediate data will be saved
Definition at line 21 of file DumpingHooks.cpp.
  : _save_path(save_path), _dumper(_save_path)
{
}
Member Function Documentation
onBeginIteration()
void DumpingHooks::onBeginIteration () override virtual
called on the start of current iteration
Implements mpqsolver::core::SolverHooks.
Definition at line 35 of file DumpingHooks.cpp.
{
  _in_iterations = true;
  _num_of_iterations += 1;
}
References _in_iterations, and _num_of_iterations.
onBeginSolver()
void DumpingHooks::onBeginSolver (const std::string & model_path, float q8error, float q16error) override virtual
called on the start of iterative search
Implements mpqsolver::core::SolverHooks.
Definition at line 26 of file DumpingHooks.cpp.
{
  _model_path = model_path;
  _dumper.setModelPath(_model_path);
  _dumper.prepareForErrorDumping();
  _dumper.dumpQ8Error(q8error);
  _dumper.dumpQ16Error(q16error);
}
References _dumper, _model_path, mpqsolver::core::Dumper::dumpQ16Error(), mpqsolver::core::Dumper::dumpQ8Error(), mpqsolver::core::Dumper::prepareForErrorDumping(), and mpqsolver::core::Dumper::setModelPath().
onEndIteration()
void DumpingHooks::onEndIteration (const LayerParams & layers, const std::string & def_dtype, float error) const override virtual
called at the end of current iteration
Implements mpqsolver::core::SolverHooks.
Definition at line 41 of file DumpingHooks.cpp.
{
  _dumper.dumpMPQConfiguration(layers, def_type, _num_of_iterations);
  _dumper.dumpMPQError(error, _num_of_iterations);
}
References _dumper, _num_of_iterations, mpqsolver::core::Dumper::dumpMPQConfiguration(), and mpqsolver::core::Dumper::dumpMPQError().
onEndSolver()
void DumpingHooks::onEndSolver (const LayerParams & layers, const std::string & def_dtype, float qerror) override virtual
called at the end of iterative search
Implements mpqsolver::core::SolverHooks.
Definition at line 48 of file DumpingHooks.cpp.
{
  _dumper.dumpFinalMPQ(layers, def_dtype);
  _dumper.dumpMPQError(qerror);
  _in_iterations = false;
}
References _dumper, _in_iterations, mpqsolver::core::Dumper::dumpFinalMPQ(), and mpqsolver::core::Dumper::dumpMPQError().
onQuantized()
void DumpingHooks::onQuantized (luci::Module * module) const override virtual
called on successfull quantization
Implements mpqsolver::core::QuantizerHook.
Definition at line 56 of file DumpingHooks.cpp.
{
  if (_in_iterations)
  {
    _dumper.dumpQuantized(module, _num_of_iterations);
  }
}
References _dumper, _in_iterations, _num_of_iterations, and mpqsolver::core::Dumper::dumpQuantized().
Field Documentation
_dumper
Dumper mpqsolver::core::DumpingHooks::_dumper protected
Definition at line 75 of file DumpingHooks.h.
Referenced by onBeginSolver(), onEndIteration(), onEndSolver(), and onQuantized().
_in_iterations
bool mpqsolver::core::DumpingHooks::_in_iterations = false protected
Definition at line 77 of file DumpingHooks.h.
Referenced by onBeginIteration(), onEndSolver(), and onQuantized().
_model_path
std::string mpqsolver::core::DumpingHooks::_model_path protected
Definition at line 73 of file DumpingHooks.h.
Referenced by onBeginSolver().
_num_of_iterations
uint32_t mpqsolver::core::DumpingHooks::_num_of_iterations = 0 protected
Definition at line 76 of file DumpingHooks.h.
Referenced by onBeginIteration(), onEndIteration(), and onQuantized().
_save_path
std::string mpqsolver::core::DumpingHooks::_save_path protected
Definition at line 74 of file DumpingHooks.h.
The documentation for this class was generated from the following files:
compiler/circle-mpqsolver/src/core/DumpingHooks.h
compiler/circle-mpqsolver/src/core/DumpingHooks.cpp