ONE - On-device Neural Engine: onert::backend::ITensor Class Reference
onert::backend::ITensor Class Reference abstract
#include <ITensor.h>
Public Member Functions
virtual ~ITensor ()
virtual uint8_t * buffer () const =0
virtual size_t total_size () const =0
virtual size_t calcOffset (const ir::Coordinates &coords) const =0
virtual ir::Layout layout () const =0
virtual ir::DataType data_type () const =0
virtual float data_scale () const =0
virtual int32_t data_zero_point () const =0
virtual const std::vector< float > & data_scales () const =0
virtual const std::vector< int32_t > & data_zero_points () const =0
virtual bool has_padding () const =0
virtual void access (const std::function< void(ITensor &tensor)> &fn)=0
virtual bool applyShape (const ir::Shape &)
Set the shape to shape and possibly re-allocate the buffer.
virtual bool is_constant () const
Return true if the tensor is constant.
virtual bool is_dynamic () const =0
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
virtual void set_dynamic ()
set this tensor dynamic
virtual void deallocBuffer ()
Dealloc the buffer (only for dynamic tensors)
virtual void setShape (const ir::Shape &new_shape)
Set the shape of tenser to new_shape.
virtual ir::Shape getShape () const =0
Get ir::Shape of tensor.
virtual bool is_subtensor () const
virtual bool needMemoryMap () const
virtual void enqueueWriteBuffer (const void *, bool)
virtual void enqueueReadBuffer (void *, bool)
Detailed Description
Definition at line 36 of file ITensor.h.
Constructor & Destructor Documentation
~ITensor()
onert::backend::ITensor::~ITensor () virtual
Reimplemented in onert::interp::ITensor.
Definition at line 26 of file ITensor.cc.
{}
Member Function Documentation
access()
virtual void onert::backend::ITensor::access (const std::function< void(ITensor &tensor)> & fn) pure virtual
Implemented in onert::backend::acl_cl::operand::ICLTensor, onert::backend::acl_neon::operand::INETensor, onert::backend::gpu_cl::operand::ICLTensor, and onert::backend::IPortableTensor.
applyShape()
virtual bool onert::backend::ITensor::applyShape (const ir::Shape &) inline virtual
Set the shape to shape and possibly re-allocate the buffer.
If a tensor is dynamic tensor and previously allocated memory exists, it will be deallocated. If a tensor is static tensor (with previously allocated memory by StaticTensorManager), buffer() will be overwriten
Parameters
shape tensor's new shape. While allocating memory for this new_shape, tensor's shape is set to new_shape
Returns
true If applying shape is successful
false If not applying shape is not supported (it throws for other errors)
Reimplemented in onert::backend::builtin::UserTensor, onert::backend::basic::Tensor, and onert::backend::builtin::IOTensor.
Definition at line 67 of file ITensor.h.
{ return false; }
Referenced by onert::backend::builtin::IOTensor::applyShape(), and onert::backend::builtin::kernel::PermuteLayer::run().
buffer()
virtual uint8_t * onert::backend::ITensor::buffer () const pure virtual
Implemented in onert::interp::ITensor, onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::basic::ExternalTensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::builtin::IOTensor::buffer(), onert::backend::ruy::ops::ConvolutionLayer::convFloat32(), onert::backend::cpu::ops::ConvolutionLayer::convQ8i(), onert::backend::xnnpack::ops::ConvolutionLayer::create(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::create(), onert::backend::xnnpack::ops::FullyConnectedLayer::create(), onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32(), onert::backend::builtin::kernel::PermuteLayer::optimize(), onert::backend::cpu::ops::FullyConnectedLayer::prepare(), onert::backend::ruy::ops::FullyConnectedLayer::prepare(), onert::backend::cpu::ops::ReshapeLayer::reshapeGeneric(), onert::backend::cpu::ops::BroadcastToLayer::run(), onert::backend::cpu::ops::DetectionPostProcessLayer::run(), onert::backend::cpu::ops::ExpandDimsLayer::run(), onert::backend::builtin::kernel::PermuteLayer::run(), onert::backend::xnnpack::ops::ConvolutionLayer::setup(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::setup(), and onert::backend::xnnpack::ops::FullyConnectedLayer::setup().
calcOffset()
virtual size_t onert::backend::ITensor::calcOffset (const ir::Coordinates & coords) const pure virtual
Implemented in onert::backend::gpu_cl::operand::ICLTensor, onert::interp::ITensor, onert::backend::acl_common::IACLTensor, onert::backend::basic::Tensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, onert::interp::ROTensor, onert::interp::Tensor, and MockTensor< T >.
Referenced by onert::backend::builtin::IOTensor::calcOffset(), and onert::exec::UpdateOffsets().
data_scale()
virtual float onert::backend::ITensor::data_scale () const pure virtual
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::IPortableTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
data_scales()
virtual const std::vector< float > & onert::backend::ITensor::data_scales () const pure virtual
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::IPortableTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
data_type()
virtual ir::DataType onert::backend::ITensor::data_type () const pure virtual
Implemented in onert::interp::ITensor, onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::cpu::ops::LogSoftMaxLayer::configure(), onert::backend::cpu::ops::SoftMaxLayer::configure(), onert::backend::cpu::ops::MeanLayer::configure(), onert::backend::cpu::ops::ReduceLayer::configure(), onert::backend::cpu::ops::DepthwiseConvolutionLayer::configure(), onert::backend::cpu::ops::FullyConnectedLayer::configure(), onert::backend::cpu::ops::PoolLayer::configure(), onert::backend::cpu::ops::QuantizeLayer::configure(), onert::backend::cpu::ops::ElementwiseActivationLayer::configure(), onert::backend::cpu::ops::ElementwiseBinaryLayer::configure(), onert::backend::cpu::ops::BinaryArithmeticLayer::configure(), onert::backend::builtin::IOTensor::data_type(), onert::backend::cpu::ops::getReducerAxes(), onert::backend::cpu::ops::MatrixBandPartLayer::matrixBandPartFloat32(), onert::exec::IPermuteFunction::permute(), onert::backend::cpu::ops::ConvolutionLayer::prepare(), onert::backend::cpu::ops::FullyConnectedLayer::prepare(), onert::backend::ruy::ops::ConvolutionLayer::prepare(), onert::backend::cpu::ops::LogSoftMaxLayer::run(), onert::backend::cpu::ops::AddNLayer::run(), onert::backend::cpu::ops::ArgMinMaxLayer::run(), onert::backend::cpu::ops::BatchMatMulLayer::run(), onert::backend::cpu::ops::BatchToSpaceNDLayer::run(), onert::backend::cpu::ops::BroadcastToLayer::run(), onert::backend::cpu::ops::CompareLayer::run(), onert::backend::cpu::ops::ConcatLayer::run(), onert::backend::cpu::ops::ConvolutionLayer::run(), onert::backend::cpu::ops::DepthToSpaceLayer::run(), onert::backend::cpu::ops::DepthwiseConvolutionLayer::run(), onert::backend::cpu::ops::EinsumLayer::run(), onert::backend::cpu::ops::FillLayer::run(), onert::backend::cpu::ops::FullyConnectedLayer::run(), onert::backend::cpu::ops::FusedBatchNormLayer::run(), onert::backend::cpu::ops::GatherLayer::run(), onert::backend::cpu::ops::L2NormLayer::run(), onert::backend::cpu::ops::LSTMLayer::run(), onert::backend::cpu::ops::MatrixBandPartLayer::run(), onert::backend::cpu::ops::MeanLayer::run(), onert::backend::cpu::ops::OneHotLayer::run(), onert::backend::cpu::ops::PackLayer::run(), onert::backend::cpu::ops::PadLayer::run(), onert::backend::cpu::ops::PowLayer::run(), onert::backend::cpu::ops::QuantizeLayer::run(), onert::backend::cpu::ops::RangeLayer::run(), onert::backend::cpu::ops::ReduceLayer::run(), onert::backend::cpu::ops::ResizeBilinearLayer::run(), onert::backend::cpu::ops::ReverseLayer::run(), onert::backend::cpu::ops::SelectLayer::run(), onert::backend::cpu::ops::ShapeLayer::run(), onert::backend::cpu::ops::SliceLayer::run(), onert::backend::cpu::ops::SoftMaxLayer::run(), onert::backend::cpu::ops::SpaceToBatchNDLayer::run(), onert::backend::cpu::ops::SpaceToDepthLayer::run(), onert::backend::cpu::ops::SplitLayer::run(), onert::backend::cpu::ops::SplitVLayer::run(), onert::backend::cpu::ops::SqDiffLayer::run(), onert::backend::cpu::ops::StatelessRandomUniformLayer::run(), onert::backend::cpu::ops::StridedSliceLayer::run(), onert::backend::cpu::ops::TileLayer::run(), onert::backend::cpu::ops::TransposeLayer::run(), onert::backend::cpu::ops::UnpackLayer::run(), onert::backend::ruy::ops::ConvolutionLayer::run(), onert::backend::ruy::ops::FullyConnectedLayer::run(), onert::backend::xnnpack::ops::ConvolutionLayer::run(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::run(), onert::backend::xnnpack::ops::FullyConnectedLayer::run(), onert::backend::cpu::ops::SplitLayer::split(), and onert::backend::cpu::ops::SplitVLayer::splitV().
data_zero_point()
virtual int32_t onert::backend::ITensor::data_zero_point () const pure virtual
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::IPortableTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
data_zero_points()
virtual const std::vector< int32_t > & onert::backend::ITensor::data_zero_points () const pure virtual
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::IPortableTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
deallocBuffer()
virtual void onert::backend::ITensor::deallocBuffer () inline virtual
Dealloc the buffer (only for dynamic tensors)
Reimplemented in onert::backend::basic::Tensor.
Definition at line 91 of file ITensor.h.
  {
    throw std::runtime_error("This backend does not support resetting buffer");
  }
enqueueReadBuffer()
virtual void onert::backend::ITensor::enqueueReadBuffer (void * , bool) inline virtual
Reimplemented in onert::backend::acl_cl::operand::ICLTensor, and onert::backend::gpu_cl::operand::ICLTensor.
Definition at line 118 of file ITensor.h.
  {
    throw std::runtime_error("This backend does not support enqueueReadBuffer");
  }
enqueueWriteBuffer()
virtual void onert::backend::ITensor::enqueueWriteBuffer (const void * , bool) inline virtual
Reimplemented in onert::backend::acl_cl::operand::ICLTensor, and onert::backend::gpu_cl::operand::ICLTensor.
Definition at line 114 of file ITensor.h.
  {
    throw std::runtime_error("This backend does not support enqueueWriteBuffer");
  }
getShape()
virtual ir::Shape onert::backend::ITensor::getShape () const pure virtual
Get ir::Shape of tensor.
Note
Higer dimension will be placed on front.
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::xnnpack::ops::ConvolutionLayer::create(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::create(), onert::backend::xnnpack::ops::FullyConnectedLayer::create(), onert::backend::cpu::ops::getReducerAxes(), onert::backend::builtin::IOTensor::getShape(), onert::backend::cpu::ops::HaveSameShapes(), onert::backend::cpu::ops::LSTMLayer::LSTMFloat(), onert::interp::concat::prepareConcat(), onert::backend::cpu::ops::ArgMinMaxLayer::run(), onert::backend::cpu::ops::ConvolutionLayer::run(), onert::backend::cpu::ops::RankLayer::run(), onert::backend::cpu::ops::ReduceLayer::run(), onert::backend::cpu::ops::ReverseLayer::run(), onert::backend::cpu::ops::SelectLayer::run(), onert::backend::ruy::ops::ConvolutionLayer::run(), onert::backend::builtin::kernel::PermuteLayer::run(), onert::backend::xnnpack::ops::ConvolutionLayer::setup(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::setup(), onert::backend::xnnpack::ops::FullyConnectedLayer::setup(), onert::backend::cpu::ops::SplitLayer::split(), onert::backend::cpu::ops::SplitVLayer::splitV(), onert::backend::cpu::ops::TransposeLayer::transpose(), and onert::exec::DynamicShapeInferer::visit().
has_padding()
virtual bool onert::backend::ITensor::has_padding () const pure virtual
Implemented in onert::interp::ITensor, onert::backend::IPortableTensor, onert::backend::acl_cl::operand::CLSubTensor, onert::backend::acl_common::IACLTensor, onert::backend::acl_neon::operand::NESubTensor, onert::backend::gpu_cl::operand::ICLTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::builtin::kernel::PermuteLayer::optimize().
is_constant()
virtual bool onert::backend::ITensor::is_constant () const inline virtual
Return true if the tensor is constant.
Reimplemented in onert::backend::basic::Tensor, onert::backend::basic::ExternalTensor, onert::backend::builtin::IOTensor, and onert::backend::builtin::UserTensor.
Definition at line 72 of file ITensor.h.
  {
    throw std::runtime_error("This backend does not support checking constant");
  }
Referenced by onert::backend::cpu::ops::DepthwiseConvolutionLayer::configure(), onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32(), onert::backend::builtin::IOTensor::is_constant(), onert::backend::cpu::ops::ConvolutionLayer::prepare(), onert::backend::cpu::ops::FullyConnectedLayer::prepare(), onert::backend::ruy::ops::ConvolutionLayer::prepare(), and onert::backend::ruy::ops::FullyConnectedLayer::prepare().
is_dynamic()
virtual bool onert::backend::ITensor::is_dynamic () const pure virtual
Return true if the tensor needs dynamic allocation, meaning that during compile-time the outpus shape cannot be known and the output shape is calculated during kernel execution-time.
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::basic::ExternalTensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::cpu::ops::DepthwiseConvolutionLayer::configure(), onert::backend::builtin::IOTensor::is_dynamic(), onert::backend::cpu::ops::ConvolutionLayer::prepare(), onert::backend::cpu::ops::FullyConnectedLayer::prepare(), onert::backend::cpu::ops::ConvolutionLayer::run(), onert::backend::ruy::ops::ConvolutionLayer::run(), and onert::backend::builtin::kernel::PermuteLayer::run().
is_subtensor()
virtual bool onert::backend::ITensor::is_subtensor () const inline virtual
Reimplemented in onert::backend::acl_cl::operand::CLSubTensor, and onert::backend::acl_neon::operand::NESubTensor.
Definition at line 112 of file ITensor.h.
{ return false; }
layout()
virtual ir::Layout onert::backend::ITensor::layout () const pure virtual
Implemented in onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::xnnpack::ops::FullyConnectedLayer::configure(), onert::backend::xnnpack::ops::ConvolutionLayer::configure(), onert::backend::xnnpack::ops::DepthwiseConvolutionLayer::configure(), onert::backend::cpu::ops::getReducerAxes(), onert::backend::builtin::IOTensor::layout(), onert::backend::cpu::ops::ConvolutionLayer::run(), onert::backend::ruy::ops::ConvolutionLayer::run(), and onert::backend::builtin::kernel::PermuteLayer::run().
needMemoryMap()
virtual bool onert::backend::ITensor::needMemoryMap () const inline virtual
Reimplemented in onert::backend::acl_cl::operand::ICLTensor, and onert::backend::gpu_cl::operand::ICLTensor.
Definition at line 113 of file ITensor.h.
{ return false; }
set_dynamic()
virtual void onert::backend::ITensor::set_dynamic () inline virtual
set this tensor dynamic
Reimplemented in onert::backend::basic::Tensor, onert::backend::basic::ExternalTensor, onert::backend::builtin::IOTensor, and onert::backend::builtin::UserTensor.
Definition at line 85 of file ITensor.h.
  {
    throw std::runtime_error("This backend does not support dynamic tensor");
  }
setShape()
virtual void onert::backend::ITensor::setShape (const ir::Shape & new_shape) inline virtual
Set the shape of tenser to new_shape.
Note
Higer dimension will be placed on front.
Reimplemented in onert::backend::basic::ExternalTensor, onert::backend::basic::Tensor, onert::backend::builtin::UserTensor, and onert::backend::builtin::IOTensor.
Definition at line 100 of file ITensor.h.
  {
    UNUSED_RELEASE(new_shape);
    throw std::runtime_error("This backend does not support dynamic setShape");
  }
References UNUSED_RELEASE.
Referenced by onert::backend::builtin::IOTensor::setShape().
total_size()
virtual size_t onert::backend::ITensor::total_size () const pure virtual
Implemented in onert::interp::ITensor, onert::backend::acl_common::IACLTensor, onert::backend::gpu_cl::operand::ICLTensor, onert::backend::basic::Tensor, onert::backend::builtin::IOTensor, onert::backend::builtin::UserTensor, MockTensor< T >, onert::interp::ROTensor, and onert::interp::Tensor.
Referenced by onert::backend::cpu::ops::LSTMLayer::LSTMFloat(), onert::exec::IPermuteFunction::permute(), onert::backend::cpu::ops::ReshapeLayer::reshapeGeneric(), onert::backend::cpu::ops::ArgMinMaxLayer::run(), onert::backend::cpu::ops::ExpandDimsLayer::run(), onert::backend::cpu::ops::ReverseLayer::run(), onert::backend::cpu::ops::SplitLayer::split(), onert::backend::cpu::ops::SplitVLayer::splitV(), and onert::backend::builtin::IOTensor::total_size().
The documentation for this class was generated from the following files:
runtime/onert/core/include/backend/ITensor.h
runtime/onert/core/src/backend/ITensor.cc