ONE - On-device Neural Engine: nnfw::cker::MatMulBCast Class Reference
nnfw::cker::MatMulBCast Class Reference
#include <MatmulBCast.h>
Public Member Functions
MatMulBCast (Shape &shape_x, Shape &shape_y)
bool IsValid () const
int32_t x_batch_size () const
int32_t y_batch_size () const
int32_t output_batch_size () const
const Shape & output_batch_shape () const
Detailed Description
Definition at line 38 of file MatmulBCast.h.
Constructor & Destructor Documentation
MatMulBCast()
nnfw::cker::MatMulBCast::MatMulBCast (Shape & shape_x, Shape & shape_y) inline
Definition at line 41 of file MatmulBCast.h.
  {
    if (shape_x.DimensionsCount() < 2 || shape_y.DimensionsCount() < 2)
      return;
    std::vector<int32_t> x;
    std::vector<int32_t> y;
    x.resize(shape_x.DimensionsCount() - 2);
    y.resize(shape_y.DimensionsCount() - 2);
    for (size_t i = 0; i < x.size(); i++)
    {
      x[i] = shape_x.Dims(i);
    }
    for (size_t i = 0; i < y.size(); i++)
    {
      y[i] = shape_y.Dims(i);
    }
    _batch_bcast = std::make_unique<BCast>(std::move(x), std::move(y));
    if (!_batch_bcast->IsValid())
      return;
    auto x_reshaped = _batch_bcast->x_reshape();
    auto y_reshaped = _batch_bcast->y_reshape();
    auto output_shape = _batch_bcast->output_shape();
    _x_batch_size = std::accumulate(x_reshaped.cbegin(), x_reshaped.cend(), INT32_C(1),
                                    std::multiplies<int32_t>());
    _y_batch_size = std::accumulate(x_reshaped.cbegin(), x_reshaped.cend(), INT32_C(1),
                                    std::multiplies<int32_t>());
    _output_shape.ReplaceWith(output_shape.size(), output_shape.data());
    _output_batch_size = _output_shape.FlatSize();
  }
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::Shape::FlatSize(), and nnfw::cker::Shape::ReplaceWith().
Member Function Documentation
IsValid()
bool nnfw::cker::MatMulBCast::IsValid () const inline
Definition at line 77 of file MatmulBCast.h.
{ return (_batch_bcast != nullptr) && _batch_bcast->IsValid(); }
output_batch_shape()
const Shape & nnfw::cker::MatMulBCast::output_batch_shape () const inline
Definition at line 81 of file MatmulBCast.h.
{ return _output_shape; }
output_batch_size()
int32_t nnfw::cker::MatMulBCast::output_batch_size () const inline
Definition at line 80 of file MatmulBCast.h.
{ return _output_batch_size; }
x_batch_size()
int32_t nnfw::cker::MatMulBCast::x_batch_size () const inline
Definition at line 78 of file MatmulBCast.h.
{ return _x_batch_size; }
y_batch_size()
int32_t nnfw::cker::MatMulBCast::y_batch_size () const inline
Definition at line 79 of file MatmulBCast.h.
{ return _y_batch_size; }
The documentation for this class was generated from the following file:
compute/cker/include/cker/operation/Helper/MatmulBCast.h