ONE - On-device Neural Engine: luci::CircleUnidirectionalSequenceLSTM Class Reference
luci::CircleUnidirectionalSequenceLSTM Class Reference final
UNIDIRECTIONAL_SEQUENCE_LSTM in Circle.
#include <CircleUnidirectionalSequenceLSTM.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * input_to_input_weights (void) const
void input_to_input_weights (loco::Node *node)
loco::Node * input_to_forget_weights (void) const
void input_to_forget_weights (loco::Node *node)
loco::Node * input_to_cell_weights (void) const
void input_to_cell_weights (loco::Node *node)
loco::Node * input_to_output_weights (void) const
void input_to_output_weights (loco::Node *node)
loco::Node * recurrent_to_input_weights (void) const
void recurrent_to_input_weights (loco::Node *node)
loco::Node * recurrent_to_forget_weights (void) const
void recurrent_to_forget_weights (loco::Node *node)
loco::Node * recurrent_to_cell_weights (void) const
void recurrent_to_cell_weights (loco::Node *node)
loco::Node * recurrent_to_output_weights (void) const
void recurrent_to_output_weights (loco::Node *node)
loco::Node * cell_to_input_weights (void) const
void cell_to_input_weights (loco::Node *node)
loco::Node * cell_to_forget_weights (void) const
void cell_to_forget_weights (loco::Node *node)
loco::Node * cell_to_output_weights (void) const
void cell_to_output_weights (loco::Node *node)
loco::Node * input_gate_bias (void) const
void input_gate_bias (loco::Node *node)
loco::Node * forget_gate_bias (void) const
void forget_gate_bias (loco::Node *node)
loco::Node * cell_gate_bias (void) const
void cell_gate_bias (loco::Node *node)
loco::Node * output_gate_bias (void) const
void output_gate_bias (loco::Node *node)
loco::Node * projection_weights (void) const
void projection_weights (loco::Node *node)
loco::Node * projection_bias (void) const
void projection_bias (loco::Node *node)
loco::Node * output_state (void) const
void output_state (loco::Node *node)
loco::Node * cell_state (void) const
void cell_state (loco::Node *node)
loco::Node * input_layer_norm_coefficients (void) const
void input_layer_norm_coefficients (loco::Node *node)
loco::Node * forget_layer_norm_coefficients (void) const
void forget_layer_norm_coefficients (loco::Node *node)
loco::Node * cell_layer_norm_coefficients (void) const
void cell_layer_norm_coefficients (loco::Node *node)
loco::Node * output_layer_norm_coefficients (void) const
void output_layer_norm_coefficients (loco::Node *node)
float cell_clip (void) const
void cell_clip (float cell_clip)
float proj_clip (void) const
void proj_clip (float proj_clip)
bool time_major (void) const
void time_major (bool time_major)
bool asymmetric_quantize_inputs (void) const
void asymmetric_quantize_inputs (bool asymmetric_quantize_inputs)
Public Member Functions inherited from luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >
loco::Use * at (uint32_t n) const
Detailed Description
UNIDIRECTIONAL_SEQUENCE_LSTM in Circle.
Definition at line 32 of file CircleUnidirectionalSequenceLSTM.h.
Member Function Documentation
asymmetric_quantize_inputs() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::asymmetric_quantize_inputs (bool asymmetric_quantize_inputs) inline
Definition at line 101 of file CircleUnidirectionalSequenceLSTM.h.
  {
    _asymmetric_quantize_inputs = asymmetric_quantize_inputs;
  }
References asymmetric_quantize_inputs().
asymmetric_quantize_inputs() [2/2]
bool luci::CircleUnidirectionalSequenceLSTM::asymmetric_quantize_inputs (void) const inline
Definition at line 100 of file CircleUnidirectionalSequenceLSTM.h.
{ return _asymmetric_quantize_inputs; }
Referenced by asymmetric_quantize_inputs(), luci::CloneNodeLet< CN::STUV >::visit(), and luci::BuiltinOptionsExtractor::visit().
cell_clip() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_clip (float cell_clip) inline
Definition at line 95 of file CircleUnidirectionalSequenceLSTM.h.
{ _cell_clip = cell_clip; }
References cell_clip().
Referenced by cell_clip().
cell_clip() [2/2]
float luci::CircleUnidirectionalSequenceLSTM::cell_clip (void) const inline
Definition at line 94 of file CircleUnidirectionalSequenceLSTM.h.
{ return _cell_clip; }
Referenced by luci::CloneNodeLet< CN::STUV >::visit(), and luci::BuiltinOptionsExtractor::visit().
cell_gate_bias() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_gate_bias (loco::Node * node) inline
Definition at line 70 of file CircleUnidirectionalSequenceLSTM.h.
{ at(14)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_gate_bias() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_gate_bias (void) const inline
Definition at line 69 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(14)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_layer_norm_coefficients() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_layer_norm_coefficients (loco::Node * node) inline
Definition at line 89 of file CircleUnidirectionalSequenceLSTM.h.
{ at(22)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_layer_norm_coefficients() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_layer_norm_coefficients (void) const inline
Definition at line 88 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(22)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_state() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_state (loco::Node * node) inline
Definition at line 82 of file CircleUnidirectionalSequenceLSTM.h.
{ at(19)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_state() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_state (void) const inline
Definition at line 81 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(19)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_forget_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_to_forget_weights (loco::Node * node) inline
Definition at line 61 of file CircleUnidirectionalSequenceLSTM.h.
{ at(10)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_forget_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_to_forget_weights (void) const inline
Definition at line 60 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(10)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_input_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_to_input_weights (loco::Node * node) inline
Definition at line 59 of file CircleUnidirectionalSequenceLSTM.h.
{ at(9)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_input_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_to_input_weights (void) const inline
Definition at line 58 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(9)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_output_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::cell_to_output_weights (loco::Node * node) inline
Definition at line 63 of file CircleUnidirectionalSequenceLSTM.h.
{ at(11)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
cell_to_output_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::cell_to_output_weights (void) const inline
Definition at line 62 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(11)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
forget_gate_bias() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::forget_gate_bias (loco::Node * node) inline
Definition at line 68 of file CircleUnidirectionalSequenceLSTM.h.
{ at(13)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
forget_gate_bias() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::forget_gate_bias (void) const inline
Definition at line 67 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(13)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
forget_layer_norm_coefficients() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::forget_layer_norm_coefficients (loco::Node * node) inline
Definition at line 87 of file CircleUnidirectionalSequenceLSTM.h.
{ at(21)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
forget_layer_norm_coefficients() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::forget_layer_norm_coefficients (void) const inline
Definition at line 86 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(21)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input (loco::Node * node) inline
Definition at line 38 of file CircleUnidirectionalSequenceLSTM.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input (void) const inline
Definition at line 37 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_gate_bias() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_gate_bias (loco::Node * node) inline
Definition at line 66 of file CircleUnidirectionalSequenceLSTM.h.
{ at(12)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_gate_bias() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_gate_bias (void) const inline
Definition at line 65 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(12)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_layer_norm_coefficients() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_layer_norm_coefficients (loco::Node * node) inline
Definition at line 85 of file CircleUnidirectionalSequenceLSTM.h.
{ at(20)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_layer_norm_coefficients() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_layer_norm_coefficients (void) const inline
Definition at line 84 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(20)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_cell_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_to_cell_weights (loco::Node * node) inline
Definition at line 45 of file CircleUnidirectionalSequenceLSTM.h.
{ at(3)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_cell_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_to_cell_weights (void) const inline
Definition at line 44 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(3)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_forget_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_to_forget_weights (loco::Node * node) inline
Definition at line 43 of file CircleUnidirectionalSequenceLSTM.h.
{ at(2)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_forget_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_to_forget_weights (void) const inline
Definition at line 42 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(2)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_input_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_to_input_weights (loco::Node * node) inline
Definition at line 41 of file CircleUnidirectionalSequenceLSTM.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_input_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_to_input_weights (void) const inline
Definition at line 40 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_output_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::input_to_output_weights (loco::Node * node) inline
Definition at line 47 of file CircleUnidirectionalSequenceLSTM.h.
{ at(4)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
input_to_output_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::input_to_output_weights (void) const inline
Definition at line 46 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(4)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_gate_bias() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::output_gate_bias (loco::Node * node) inline
Definition at line 72 of file CircleUnidirectionalSequenceLSTM.h.
{ at(15)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_gate_bias() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::output_gate_bias (void) const inline
Definition at line 71 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(15)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_layer_norm_coefficients() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::output_layer_norm_coefficients (loco::Node * node) inline
Definition at line 91 of file CircleUnidirectionalSequenceLSTM.h.
{ at(23)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_layer_norm_coefficients() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::output_layer_norm_coefficients (void) const inline
Definition at line 90 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(23)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_state() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::output_state (loco::Node * node) inline
Definition at line 80 of file CircleUnidirectionalSequenceLSTM.h.
{ at(18)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
output_state() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::output_state (void) const inline
Definition at line 79 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(18)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
proj_clip() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::proj_clip (float proj_clip) inline
Definition at line 97 of file CircleUnidirectionalSequenceLSTM.h.
{ _proj_clip = proj_clip; }
References proj_clip().
Referenced by proj_clip().
proj_clip() [2/2]
float luci::CircleUnidirectionalSequenceLSTM::proj_clip (void) const inline
Definition at line 96 of file CircleUnidirectionalSequenceLSTM.h.
{ return _proj_clip; }
Referenced by luci::CloneNodeLet< CN::STUV >::visit(), and luci::BuiltinOptionsExtractor::visit().
projection_bias() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::projection_bias (loco::Node * node) inline
Definition at line 77 of file CircleUnidirectionalSequenceLSTM.h.
{ at(17)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
projection_bias() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::projection_bias (void) const inline
Definition at line 76 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(17)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
projection_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::projection_weights (loco::Node * node) inline
Definition at line 75 of file CircleUnidirectionalSequenceLSTM.h.
{ at(16)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
projection_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::projection_weights (void) const inline
Definition at line 74 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(16)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_cell_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::recurrent_to_cell_weights (loco::Node * node) inline
Definition at line 54 of file CircleUnidirectionalSequenceLSTM.h.
{ at(7)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_cell_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::recurrent_to_cell_weights (void) const inline
Definition at line 53 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(7)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_forget_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::recurrent_to_forget_weights (loco::Node * node) inline
Definition at line 52 of file CircleUnidirectionalSequenceLSTM.h.
{ at(6)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_forget_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::recurrent_to_forget_weights (void) const inline
Definition at line 51 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(6)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_input_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::recurrent_to_input_weights (loco::Node * node) inline
Definition at line 50 of file CircleUnidirectionalSequenceLSTM.h.
{ at(5)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_input_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::recurrent_to_input_weights (void) const inline
Definition at line 49 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(5)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_output_weights() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::recurrent_to_output_weights (loco::Node * node) inline
Definition at line 56 of file CircleUnidirectionalSequenceLSTM.h.
{ at(8)->node(node); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
recurrent_to_output_weights() [2/2]
loco::Node * luci::CircleUnidirectionalSequenceLSTM::recurrent_to_output_weights (void) const inline
Definition at line 55 of file CircleUnidirectionalSequenceLSTM.h.
{ return at(8)->node(); }
References luci::FixedArityNode< 24, CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM > >::at(), and loco::Use::node().
time_major() [1/2]
void luci::CircleUnidirectionalSequenceLSTM::time_major (bool time_major) inline
Definition at line 99 of file CircleUnidirectionalSequenceLSTM.h.
{ _time_major = time_major; }
References time_major().
Referenced by time_major().
time_major() [2/2]
bool luci::CircleUnidirectionalSequenceLSTM::time_major (void) const inline
Definition at line 98 of file CircleUnidirectionalSequenceLSTM.h.
{ return _time_major; }
Referenced by luci::CloneNodeLet< CN::STUV >::visit(), and luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleUnidirectionalSequenceLSTM.h