ONE - On-device Neural Engine: onert_micro::core::OMTensorData< T > Class Template Reference
onert_micro::core::OMTensorData< T > Class Template Reference
#include <OMTensorData.h>
Public Member Functions
OMTensorData (T *data, const circle::Tensor *tensor)
bool IsNull () const noexcept
T * Get () const noexcept
T & At (size_t idx) const
void SetAt (size_t idx, T value)
template<typename U = T>
std::enable_if_t< IsQuantized< U > > SetAt (size_t idx, float value)
template<typename U = T>
std::enable_if_t<!IsQuantized< U >, T & > ValueAt (size_t idx) const
template<typename U = T>
std::enable_if_t< HasQuantizedConstData< U >, float > ValueAt (size_t idx) const
template<typename U = T>
std::enable_if_t< HasQuantizedNonConstData< U >, float > ValueAt (size_t idx) const
template<typename U = T>
std::enable_if_t<!IsQuantized< U > > SetValueAt (size_t idx, T value)
template<typename U = T>
std::enable_if_t< HasQuantizedNonConstData< U > > SetValueAt (size_t idx, float value)
Static Public Attributes
template<typename U = T>
static constexpr bool IsInt8 = std::is_same<std::decay_t<U>, int8_t>::value
template<typename U = T>
static constexpr bool IsUInt8 = std::is_same<std::decay_t<U>, uint8_t>::value
template<typename U = T>
static constexpr bool IsQuantized = IsInt8<U> || IsUInt8<U>
template<typename U = T>
static constexpr bool HasConstData = std::is_const<U>::value
template<typename U = T>
static constexpr bool HasNonConstData = !HasConstData<U>
template<typename U = T>
static constexpr bool HasQuantizedConstData = IsQuantized<U> && HasConstData<U>
template<typename U = T>
static constexpr bool HasQuantizedNonConstData = IsQuantized<U> && HasNonConstData<U>
Detailed Description
template<typename T>
class onert_micro::core::OMTensorData< T >
Definition at line 36 of file OMTensorData.h.
Constructor & Destructor Documentation
OMTensorData()
template<typename T > onert_micro::core::OMTensorData< T >::OMTensorData (T * data, const circle::Tensor * tensor) inline
Definition at line 48 of file OMTensorData.h.
    : _data(data)
  {
    assert(data != nullptr);
    assert(tensor != nullptr);
    _size = OMRuntimeShape(tensor).flatSize();
    if (IsQuantized<T>)
    {
      _quant = std::make_unique<QuantData>(_data, tensor);
    }
  }
References onert_micro::core::OMRuntimeShape::flatSize().
Member Function Documentation
At()
template<typename T > T & onert_micro::core::OMTensorData< T >::At (size_t idx) const inline
Definition at line 97 of file OMTensorData.h.
  {
    CheckIndex(idx);
    return _data[idx];
  }
Referenced by onert_micro::core::OMTensorData< T >::ValueAt().
Get()
template<typename T > T * onert_micro::core::OMTensorData< T >::Get () const inline noexcept
Definition at line 92 of file OMTensorData.h.
  {
    return _data;
  }
IsNull()
template<typename T > bool onert_micro::core::OMTensorData< T >::IsNull () const inline noexcept
Definition at line 86 of file OMTensorData.h.
  {
    return (_data == nullptr) || (_size == 0);
  }
Referenced by onert_micro::core::OMInputContext< T, InputTensorIdx >::OMInputContext().
SetAt() [1/2]
template<typename T > template<typename U = T> std::enable_if_t< IsQuantized< U > > onert_micro::core::OMTensorData< T >::SetAt (size_t idx, float value) inline
Definition at line 110 of file OMTensorData.h.
  {
    CheckIndex(idx);
    _quant->SetDataAt(idx, value);
  }
SetAt() [2/2]
template<typename T > void onert_micro::core::OMTensorData< T >::SetAt (size_t idx, T value) inline
Definition at line 103 of file OMTensorData.h.
  {
    CheckIndex(idx);
    _data[idx] = value;
  }
Referenced by onert_micro::core::OMTensorData< T >::SetValueAt().
SetValueAt() [1/2]
template<typename T > template<typename U = T> std::enable_if_t< HasQuantizedNonConstData< U > > onert_micro::core::OMTensorData< T >::SetValueAt (size_t idx, float value) inline
Definition at line 149 of file OMTensorData.h.
  {
    CheckIndex(idx);
    _out_float_data[idx] = value;
  }
SetValueAt() [2/2]
template<typename T > template<typename U = T> std::enable_if_t<!IsQuantized< U > > onert_micro::core::OMTensorData< T >::SetValueAt (size_t idx, T value) inline
Definition at line 143 of file OMTensorData.h.
  {
    SetAt(idx, value);
  }
References onert_micro::core::OMTensorData< T >::SetAt().
ValueAt() [1/3]
template<typename T > template<typename U = T> std::enable_if_t<!IsQuantized< U >, T & > onert_micro::core::OMTensorData< T >::ValueAt (size_t idx) const inline
Definition at line 118 of file OMTensorData.h.
  {
    return At(idx);
  }
References onert_micro::core::OMTensorData< T >::At().
ValueAt() [2/3]
template<typename T > template<typename U = T> std::enable_if_t< HasQuantizedConstData< U >, float > onert_micro::core::OMTensorData< T >::ValueAt (size_t idx) const inline
Definition at line 124 of file OMTensorData.h.
  {
    CheckIndex(idx);
    return _quant->DataAt(idx);
  }
ValueAt() [3/3]
template<typename T > template<typename U = T> std::enable_if_t< HasQuantizedNonConstData< U >, float > onert_micro::core::OMTensorData< T >::ValueAt (size_t idx) const inline
Definition at line 131 of file OMTensorData.h.
  {
    CheckIndex(idx);
    if (_out_float_data.count(idx) == 0)
      return 0.f;
    return _out_float_data.at(idx);
  }
Field Documentation
HasConstData
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::HasConstData = std::is_const<U>::value static constexpr
Definition at line 74 of file OMTensorData.h.
HasNonConstData
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::HasNonConstData = !HasConstData<U> static constexpr
Definition at line 77 of file OMTensorData.h.
HasQuantizedConstData
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::HasQuantizedConstData = IsQuantized<U> && HasConstData<U> static constexpr
Definition at line 80 of file OMTensorData.h.
HasQuantizedNonConstData
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::HasQuantizedNonConstData = IsQuantized<U> && HasNonConstData<U> static constexpr
Definition at line 83 of file OMTensorData.h.
IsInt8
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::IsInt8 = std::is_same<std::decay_t<U>, int8_t>::value static constexpr
Definition at line 64 of file OMTensorData.h.
IsQuantized
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::IsQuantized = IsInt8<U> || IsUInt8<U> static constexpr
Definition at line 70 of file OMTensorData.h.
IsUInt8
template<typename T > template<typename U = T> constexpr bool onert_micro::core::OMTensorData< T >::IsUInt8 = std::is_same<std::decay_t<U>, uint8_t>::value static constexpr
Definition at line 67 of file OMTensorData.h.
The documentation for this class was generated from the following file:
onert-micro/onert-micro/include/core/OMTensorData.h