ONE - On-device Neural Engine: luci::CloneNodeLet< CN::ABC > Class Reference
luci::CloneNodeLet< CN::ABC > Class Reference final
#include <CircleCloneNode.h>
Public Member Functions
CloneNodeLet (loco::Graph *graph)
luci::CircleNode * visit (const luci::CircleAbs *) final
luci::CircleNode * visit (const luci::CircleAdd *) final
luci::CircleNode * visit (const luci::CircleAddN *) final
luci::CircleNode * visit (const luci::CircleArgMax *) final
luci::CircleNode * visit (const luci::CircleArgMin *) final
luci::CircleNode * visit (const luci::CircleAveragePool2D *) final
luci::CircleNode * visit (const luci::CircleBatchMatMul *) final
luci::CircleNode * visit (const luci::CircleBatchToSpaceND *) final
luci::CircleNode * visit (const luci::CircleCast *) final
luci::CircleNode * visit (const luci::CircleCeil *) final
luci::CircleNode * visit (const luci::CircleConcatenation *) final
luci::CircleNode * visit (const luci::CircleConst *) final
luci::CircleNode * visit (const luci::CircleConv2D *) final
luci::CircleNode * visit (const luci::CircleCos *) final
luci::CircleNode * visit (const luci::CircleCustom *) final
luci::CircleNode * visit (const luci::CircleNode *) final
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitor< luci::CircleNode * >
virtual ~CircleNodeVisitor ()=default
virtual luci::CircleNode * visit (const CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeVisitorBase< T >
virtual ~CircleNodeVisitorBase ()=default
Protected Attributes
loco::Graph * _graph = nullptr
Detailed Description
Definition at line 41 of file CircleCloneNode.h.
Constructor & Destructor Documentation
CloneNodeLet()
luci::CloneNodeLet< CN::ABC >::CloneNodeLet (loco::Graph * graph) inline
Definition at line 44 of file CircleCloneNode.h.
: _graph(graph){};
Member Function Documentation
visit() [1/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleAbs *) final
Definition at line 22 of file CircleAbs.cpp.
{
  return _graph->nodes()->create<luci::CircleAbs>();
}
visit() [2/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleAdd * node) final
Definition at line 22 of file CircleAdd.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleAdd>();
  if (cloned != nullptr)
    cloned->fusedActivationFunction(node->fusedActivationFunction());
  return cloned;
}
References luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), and luci::UNDEFINED.
visit() [3/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleAddN * node) final
Definition at line 22 of file CircleAddN.cpp.
{
  auto arity = node->arity();
  return _graph->nodes()->create<luci::CircleAddN>(arity);
}
References luci::VariadicArityNode< Base >::arity().
visit() [4/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleArgMax * node) final
Definition at line 22 of file CircleArgMax.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleArgMax>();
  if (cloned != nullptr)
    cloned->output_type(node->output_type());
  return cloned;
}
References luci::CircleArgMax::output_type().
visit() [5/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleArgMin * node) final
Definition at line 22 of file CircleArgMin.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleArgMin>();
  if (cloned != nullptr)
    cloned->output_type(node->output_type());
  return cloned;
}
References luci::CircleArgMin::output_type().
visit() [6/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleAveragePool2D * node) final
Definition at line 22 of file CircleAveragePool2D.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleAveragePool2D>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->padding(node->padding());
    cloned->filter()->h(node->filter()->h());
    cloned->filter()->w(node->filter()->w());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
  }
  return cloned;
}
References luci::CircleAveragePool2D::filter(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::Filter::h(), luci::Stride::h(), luci::CircleAveragePool2D::padding(), luci::CircleAveragePool2D::stride(), luci::UNDEFINED, luci::Filter::w(), and luci::Stride::w().
visit() [7/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleBatchMatMul * node) final
Definition at line 22 of file CircleBatchMatMul.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleBatchMatMul>();
  if (cloned != nullptr)
  {
    cloned->adj_x(node->adj_x());
    cloned->adj_y(node->adj_y());
  }
  return cloned;
}
References luci::CircleBatchMatMul::adj_x(), and luci::CircleBatchMatMul::adj_y().
visit() [8/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleBatchToSpaceND *) final
Definition at line 22 of file CircleBatchToSpaceND.cpp.
{
  return _graph->nodes()->create<luci::CircleBatchToSpaceND>();
}
visit() [9/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleCast * node) final
Definition at line 22 of file CircleCast.cpp.
{
  auto *cloned = _graph->nodes()->create<luci::CircleCast>();
  if (cloned != nullptr)
  {
    cloned->in_data_type(node->in_data_type());
    cloned->out_data_type(node->out_data_type());
  }
  return cloned;
}
References luci::CircleCast::in_data_type(), and luci::CircleCast::out_data_type().
visit() [10/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleCeil *) final
Definition at line 22 of file CircleCeil.cpp.
{
  return _graph->nodes()->create<luci::CircleCeil>();
}
visit() [11/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleConcatenation * node) final
Definition at line 22 of file CircleConcatenation.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleConcatenation>(node->numValues());
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->axis(node->axis());
  }
  return cloned;
}
References luci::CircleConcatenation::axis(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::CircleConcatenation::numValues(), and luci::UNDEFINED.
visit() [12/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleConst * node) final
Definition at line 113 of file CircleConst.cpp.
{
  return clone_circleconst(node, _graph);
}
visit() [13/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleConv2D * node) final
Definition at line 22 of file CircleConv2D.cpp.
{
  if (node->fusedActivationFunction() == luci::FusedActFunc::UNDEFINED)
    return nullptr;
  if (node->padding() == luci::Padding::UNDEFINED)
    return nullptr;
  auto *cloned = _graph->nodes()->create<luci::CircleConv2D>();
  if (cloned != nullptr)
  {
    cloned->fusedActivationFunction(node->fusedActivationFunction());
    cloned->padding(node->padding());
    cloned->stride()->h(node->stride()->h());
    cloned->stride()->w(node->stride()->w());
    cloned->dilation()->h(node->dilation()->h());
    cloned->dilation()->w(node->dilation()->w());
  }
  return cloned;
}
References luci::CircleConv2D::dilation(), luci::CircleNodeMixin< CircleNodeTrait::FusedActFunc >::fusedActivationFunction(), luci::Dilation::h(), luci::Stride::h(), luci::CircleConv2D::padding(), luci::CircleConv2D::stride(), luci::UNDEFINED, luci::Dilation::w(), and luci::Stride::w().
visit() [14/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleCos *) final
Definition at line 22 of file CircleCos.cpp.
{
  return _graph->nodes()->create<luci::CircleCos>();
}
visit() [15/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleCustom * node) final
Definition at line 22 of file CircleCustom.cpp.
{
  uint32_t num_in = node->numInputs();
  uint32_t num_out = node->numOutputs();
  auto *cloned = _graph->nodes()->create<luci::CircleCustom>(num_in, num_out);
  if (cloned != nullptr)
  {
    cloned->custom_options(node->custom_options());
    cloned->custom_code(node->custom_code());
  }
  return cloned;
}
References luci::CircleCustom::custom_code(), luci::CircleCustom::custom_options(), luci::CircleCustom::numInputs(), and luci::CircleCustom::numOutputs().
visit() [16/16]
luci::CircleNode * luci::CloneNodeLet< CN::ABC >::visit (const luci::CircleNode *) inline final virtual
Default fallback.
Reimplemented from luci::CircleNodeVisitor< luci::CircleNode * >.
Definition at line 63 of file CircleCloneNode.h.
{ return nullptr; }
Field Documentation
_graph
loco::Graph* luci::CloneNodeLet< CN::ABC >::_graph = nullptr protected
Definition at line 66 of file CircleCloneNode.h.
The documentation for this class was generated from the following files:
compiler/luci/service/src/CircleCloneNode.h
compiler/luci/service/src/Nodes/CircleAbs.cpp
compiler/luci/service/src/Nodes/CircleAdd.cpp
compiler/luci/service/src/Nodes/CircleAddN.cpp
compiler/luci/service/src/Nodes/CircleArgMax.cpp
compiler/luci/service/src/Nodes/CircleArgMin.cpp
compiler/luci/service/src/Nodes/CircleAveragePool2D.cpp
compiler/luci/service/src/Nodes/CircleBatchMatMul.cpp
compiler/luci/service/src/Nodes/CircleBatchToSpaceND.cpp
compiler/luci/service/src/Nodes/CircleCast.cpp
compiler/luci/service/src/Nodes/CircleCeil.cpp
compiler/luci/service/src/Nodes/CircleConcatenation.cpp
compiler/luci/service/src/Nodes/CircleConst.cpp
compiler/luci/service/src/Nodes/CircleConv2D.cpp
compiler/luci/service/src/Nodes/CircleCos.cpp
compiler/luci/service/src/Nodes/CircleCustom.cpp