ONE - On-device Neural Engine: onert::compiler::pass::OperationPass Class Reference
onert::compiler::pass::OperationPass Class Reference abstract
Class to iterate over operations and calls callback() method.
#include <OperationPass.h>
Public Member Functions
virtual ~OperationPass ()=default
std::string id () override=0
Returns string id for this pass. Same with class name.
virtual void callback (const ir::OperationIndex &index, ir::Operation &node)=0
Be called for all nodes of graph.
void run () final
Run the pass.
Pass (ir::Graph &graph)
Public Member Functions inherited from onert::compiler::pass::Pass
Pass (ir::Graph &graph)
virtual ~Pass ()=default
virtual std::string id ()=0
virtual void run ()=0
Additional Inherited Members
Protected Attributes inherited from onert::compiler::pass::Pass
ir::Graph & _graph
Detailed Description
Class to iterate over operations and calls callback() method.
Definition at line 46 of file OperationPass.h.
Constructor & Destructor Documentation
~OperationPass()
virtual onert::compiler::pass::OperationPass::~OperationPass () virtual default
Member Function Documentation
callback()
virtual void onert::compiler::pass::OperationPass::callback (const ir::OperationIndex & index, ir::Operation & node) pure virtual
Be called for all nodes of graph.
Parameters
index is the index of a node in graph
node is the node in graph
Implemented in onert::compiler::pass::PermutationEliminationPass, onert::compiler::pass::PermutationOperationPass, onert::compiler::pass::LoweredOperationPass, onert::compiler::pass::ConstantInsertionPass, and onert::compiler::pass::ConstantLoweringPass.
Referenced by run().
id()
std::string onert::compiler::pass::OperationPass::id () override pure virtual
Returns string id for this pass. Same with class name.
Returns
string id
Implements onert::compiler::pass::Pass.
Implemented in onert::compiler::pass::ConstantInsertionPass, onert::compiler::pass::ConstantLoweringPass, onert::compiler::pass::PermutationEliminationPass, onert::compiler::pass::PermutationOperationPass, and onert::compiler::pass::LoweredOperationPass.
Pass()
onert::compiler::pass::Pass::Pass (ir::Graph & graph) inline
Definition at line 40 of file Pass.h.
: _graph{graph} {}
run()
void onert::compiler::pass::OperationPass::run () final virtual
Run the pass.
Implements onert::compiler::pass::Pass.
Definition at line 30 of file OperationPass.cc.
{
  _graph.operations().iterate(
    [&](const ir::OperationIndex &index, ir::Operation &node) { callback(index, node); });
}
References onert::compiler::pass::Pass::_graph, callback(), onert::util::ObjectManager< Index, Object >::iterate(), and onert::ir::Graph::operations().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/pass/OperationPass.h
runtime/onert/core/src/compiler/pass/OperationPass.cc