ONE - On-device Neural Engine: pp::EnclosedDocument Class Reference
pp::EnclosedDocument Class Reference final
#include <EnclosedDocument.h>
Public Member Functions
EnclosedDocument ()
LinearDocument & front (void)
const LinearDocument & front (void) const
LinearDocument & back (void)
const LinearDocument & back (void) const
uint32_t lines (void) const override
const std::string & line (uint32_t n) const override
Public Member Functions inherited from pp::MultiLineText
virtual ~MultiLineText ()=default
virtual uint32_t lines (void) const =0
virtual const std::string & line (uint32_t n) const =0
Detailed Description
Definition at line 26 of file EnclosedDocument.h.
Constructor & Destructor Documentation
EnclosedDocument()
pp::EnclosedDocument::EnclosedDocument () inline
Definition at line 29 of file EnclosedDocument.h.
                     : _front{}, _back{LinearDocument::Direction::Reverse}
  {
    // DO NOTHING
  }
Member Function Documentation
back() [1/2]
LinearDocument & pp::EnclosedDocument::back (void) inline
Definition at line 39 of file EnclosedDocument.h.
{ return _back; }
back() [2/2]
const LinearDocument & pp::EnclosedDocument::back (void) const inline
Definition at line 40 of file EnclosedDocument.h.
{ return _back; }
front() [1/2]
LinearDocument & pp::EnclosedDocument::front (void) inline
Definition at line 35 of file EnclosedDocument.h.
{ return _front; }
front() [2/2]
const LinearDocument & pp::EnclosedDocument::front (void) const inline
Definition at line 36 of file EnclosedDocument.h.
{ return _front; }
line()
const std::string & pp::EnclosedDocument::line (uint32_t n) const override virtual
Implements pp::MultiLineText.
Definition at line 24 of file EnclosedDocument.cpp.
{
  if (n < _front.lines())
  {
    return _front.line(n);
  }
  return _back.line(n - _front.lines());
}
References pp::LinearDocument::line(), and pp::LinearDocument::lines().
lines()
uint32_t pp::EnclosedDocument::lines (void) const override virtual
Implements pp::MultiLineText.
Definition at line 22 of file EnclosedDocument.cpp.
{ return _front.lines() + _back.lines(); }
References pp::LinearDocument::lines().
The documentation for this class was generated from the following files:
compiler/pp/include/pp/EnclosedDocument.h
compiler/pp/src/EnclosedDocument.cpp