ONE - On-device Neural Engine: nnfw::cker::FusedBatchNorm Class Reference
nnfw::cker::FusedBatchNorm Class Reference
#include <FusedBatchNorm.h>
Public Member Functions
FusedBatchNorm ()
void prepare ()
void operator() (const std::vector< Shape > &input_shapes, const std::vector< const float * > &input_data, const Shape &output_shape, float *output_data, FusedBatchNormParams param)
template<typename T >
void copyFrom (const InputTensor< T > &input, const Shape &shape, Tensor *output)
void copyFrom (const Tensor &input, const Shape &shape, Tensor *output)
Detailed Description
Definition at line 42 of file FusedBatchNorm.h.
Constructor & Destructor Documentation
FusedBatchNorm()
nnfw::cker::FusedBatchNorm::FusedBatchNorm () inline
Definition at line 45 of file FusedBatchNorm.h.
                   : _prepared(false)
  {
    // DO NOTHING
  }
Member Function Documentation
copyFrom() [1/2]
template<typename T > void nnfw::cker::FusedBatchNorm::copyFrom (const InputTensor< T > & input, const Shape & shape, Tensor * output) inline
Definition at line 135 of file FusedBatchNorm.h.
  {
    Tensor temp_tensor;
    temp_tensor.shape.ReplaceWith(input.shape.DimensionsCount(), input.shape.DimsData());
    temp_operand.emplace_back(std::make_unique<float[]>(input.shape.FlatSize()));
    temp_tensor.buffer = temp_operand.back().get();
    memcpy(temp_tensor.buffer, input.buffer, input.shape.FlatSize() * sizeof(float));
    copyFrom(temp_tensor, shape, output);
  }
References nnfw::cker::Tensor::buffer, copyFrom(), nnfw::cker::Shape::ReplaceWith(), and nnfw::cker::Tensor::shape.
Referenced by copyFrom().
copyFrom() [2/2]
void nnfw::cker::FusedBatchNorm::copyFrom (const Tensor & input, const Shape & shape, Tensor * output) inline
Definition at line 146 of file FusedBatchNorm.h.
  {
    if (output->copyFrom(input, shape))
      return;
    throw std::runtime_error{"Einsum: Encountered error while reshaping a Tensor"};
  }
operator()()
void nnfw::cker::FusedBatchNorm::operator() (const std::vector< Shape > & input_shapes, const std::vector< const float * > & input_data, const Shape & output_shape, float * output_data, FusedBatchNormParams param) inline
Definition at line 52 of file FusedBatchNorm.h.
  {
    // TODO: support fused_batch_norm if is_traninig is false
    assert(param.is_training == true);
    // TODO: support case where dim[1] != 1 or dim[3] !=1.
    // Here we only support input tensor of [B, 1, X, 1] shape
    assert(input_shapes[0].Dims(1) == 1 && input_shapes[0].Dims(3) == 1);
    if (!_prepared)
    {
      prepare();
    }
    Tensor transformed_input[5];
    Tensor transformed_output;
    const int num_inputs = input_shapes.size();
    std::vector<InputTensor<float>> inputs(num_inputs);
    for (int i = 0; i < num_inputs; i++)
    {
      inputs[i].shape.ReplaceWith(input_shapes[i].DimensionsCount(), input_shapes[i].DimsData());
      inputs[i].buffer = input_data[i];
      copyFrom<float>(inputs[i], inputs[i].shape, &transformed_input[i]);
    }
    InputTensor<float> output;
    output.shape.ReplaceWith(output_shape.DimensionsCount(), output_shape.DimsData());
    output.buffer = output_data;
    copyFrom<float>(output, output.shape, &transformed_output);
    // TODO: support transpose if data_format is NCHW
    // Here, Eigen use RowMajor kernel(NHWC)
    typename TTypes<float, 4>::Tensor x(transformed_input[0].shaped<float, 4>());
    typename TTypes<float, 4>::Tensor y(transformed_output.shaped<float, 4>());
    typename TTypes<float, 1>::Tensor scale(transformed_input[1].shaped<float, 1>());
    typename TTypes<float, 1>::Tensor offset(transformed_input[2].shaped<float, 1>());
    const int depth = x.dimension(3);
    const int size = x.size();
    const int rest_size = size / depth;
    Eigen::DSizes<Eigen::Index, 2> rest_by_depth(rest_size, depth);
    Eigen::DSizes<Eigen::Index, 2> one_by_depth(1, depth);
    Eigen::array<int, 1> reduce_dims({0});
    Eigen::array<int, 2> bcast_spec({rest_size, 1});
    auto x_rest_by_depth = x.reshape(rest_by_depth).template cast<float>();
    const int rest_size_minus_one = (rest_size > 1) ? (rest_size - 1) : 1;
    float rest_size_inv = static_cast<float>(1.0f / static_cast<float>(rest_size));
    // This adjustment is for Bessel's correction
    float rest_size_adjust =
      static_cast<float>(rest_size) / static_cast<float>(rest_size_minus_one);
    Eigen::Tensor<float, 1, Eigen::RowMajor> batch_mean(depth);
    Eigen::Tensor<float, 1, Eigen::RowMajor> batch_variance(depth);
    const Eigen::ThreadPoolDevice &d = *eigen_support::GetThreadPoolDevice();
    batch_mean.device(d) = (x_rest_by_depth.sum(reduce_dims) * rest_size_inv);
    auto x_centered = x_rest_by_depth - batch_mean.reshape(one_by_depth).broadcast(bcast_spec);
    batch_variance.device(d) = x_centered.square().sum(reduce_dims) * rest_size_inv;
    auto scaling_factor = ((batch_variance + param.epsilon).rsqrt() * scale)
                            .eval()
                            .reshape(one_by_depth)
                            .broadcast(bcast_spec);
    auto x_scaled = x_centered * scaling_factor;
    auto x_shifted =
      (x_scaled + offset.reshape(one_by_depth).broadcast(bcast_spec)).template cast<float>();
    UNUSED_RELEASE(rest_size_adjust);
    y.reshape(rest_by_depth).device(d) = x_shifted;
    memcpy(output_data, y.data(), output_shape.FlatSize() * sizeof(float));
  }
References nnfw::cker::FusedBatchNormParams::epsilon, nnfw::cker::eigen_support::GetThreadPoolDevice(), nnfw::cker::FusedBatchNormParams::is_training, offset(), prepare(), nnfw::cker::Tensor::shaped(), and UNUSED_RELEASE.
prepare()
void nnfw::cker::FusedBatchNorm::prepare () inline
Definition at line 50 of file FusedBatchNorm.h.
{ _prepared = true; }
Referenced by onert::backend::cpu::ops::FusedBatchNormLayer::fusedbatchnormFloat32(), and operator()().
The documentation for this class was generated from the following file:
compute/cker/include/cker/operation/FusedBatchNorm.h