ONE - On-device Neural Engine: tflimport::SubGraphBuilder Class Reference
tflimport::SubGraphBuilder Class Reference
GraphBuilder for Sub operator.
#include <Sub.h>
Public Member Functions
void build (const tflite::Operator *op, GraphBuilderContext *) const override
Public Member Functions inherited from tflimport::GraphBuilder
virtual bool validate (const tflite::Operator *) const
virtual void build (const tflite::Operator *op, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for Sub operator.
Definition at line 30 of file Sub.h.
Member Function Documentation
build()
void tflimport::SubGraphBuilder::build (const tflite::Operator * op, GraphBuilderContext * context) const override virtual
Implements tflimport::GraphBuilder.
Definition at line 39 of file Sub.cpp.
{
  assert(context != nullptr); // check if init(..) is called
  coco::Module *m = context->m();
  coco::Block *blk = context->block();
  TensorContext &tensor_context = context->tensor();
  TensorBags &bags = context->bags();
  IndexVector opinputs = as_index_vector(op->inputs());
  IndexVector opoutputs = as_index_vector(op->outputs());
  // these are fixed in tflite
  // input index 0 : left input feature
  // input index 1 : right input feature
  // output index 0 : output feature
  assert(opinputs.size() == 2);
  assert(opoutputs.size() == 1);
  // Default parameter values are referenced from schema_generated.h
  auto *params = op->builtin_options_as_SubOptions();
  tflite::ActivationFunctionType activation = tflite::ActivationFunctionType_NONE;
  if (auto *params = op->builtin_options_as_SubOptions())
  {
    activation = params->fused_activation_function();
  }
  assert(activation == tflite::ActivationFunctionType_NONE);
  // Construct a vector of input objects
  std::vector<coco::FeatureObject *> input_objects;
  for (auto &input_index : opinputs)
  {
    // Add objects for input feature map
    const tensor::Shape &input_shape = tensor_context.shape(input_index);
    coco::FeatureObject *input_obj = m->entity()->object()->create<coco::FeatureObject>();
    coco::Bag *input_bag = bags.bag(input_index);
    input_obj->bag(input_bag);
    input_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(input_shape)));
    input_objects.emplace_back(input_obj);
  }
  // Create an object for an output feature map
  int const output_index = opoutputs.at(0);
  const tensor::Shape &output_shape = tensor_context.shape(output_index);
  coco::FeatureObject *output_obj = m->entity()->object()->create<coco::FeatureObject>();
  coco::Bag *output_bag = bags.bag(output_index);
  output_obj->bag(output_bag);
  output_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(output_shape)));
  // Create Load ops
  auto left_load = op_builder(m).load(input_objects[0]).pop();
  auto right_load = op_builder(m).load(input_objects[1]).pop();
  // Create a Sub
  auto coco_sub = m->entity()->op()->create<coco::Sub>();
  coco_sub->left(left_load);
  coco_sub->right(right_load);
  // Create an Eval instruction
  auto eval = instr_builder(m).eval(output_obj, coco_sub);
  // Append the instruction to the block
  blk->instr()->append(eval);
  // TODO activation, e.g., relu
  assert(params->fused_activation_function() ==
         tflite::ActivationFunctionType::ActivationFunctionType_NONE);
}
References coco::DLinkedList< Child, Parent >::Head::append(), morph::tflite::as_feature_shape(), tflimport::as_index_vector(), coco::FeatureLayout::at(), tflimport::TensorBags::bag(), coco::Object::bag(), tflimport::GraphBuilderContext::bags(), tflimport::GraphBuilderContext::block(), coco::FeatureLayouts::BHWC::create(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), coco::FeatureObject::layout(), coco::BinaryOp::left(), OpBuilder::load(), tflimport::GraphBuilderContext::m(), m, op_builder(), OpBuilder::pop(), tflimport::TensorContext::shape(), and tflimport::GraphBuilderContext::tensor().
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Op/Sub.h
compiler/enco/frontend/tflite/src/Op/Sub.cpp