ONE - On-device Neural Engine: coco::OpManager Class Reference
coco::OpManager Class Reference final
#include <OpManager.h>
Public Member Functions
OpManager (Module *m=nullptr)
~OpManager ()
template<typename T >
T * create (void)
void destroy (Op *)
Destroy (= deallocate) a Op instance.
void destroy_all (Op *)
Destroy a Op tree.
Public Member Functions inherited from coco::PtrManager< Op >
uint32_t size (void) const
Return the number of managed objects.
Op * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Op >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Op > release (Op *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 34 of file OpManager.h.
Constructor & Destructor Documentation
OpManager()
coco::OpManager::OpManager (Module * m = nullptr) inline
Definition at line 37 of file OpManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
~OpManager()
coco::OpManager::~OpManager ()
Definition at line 29 of file OpManager.cpp.
{
  std::set<coco::Op *> roots;
  for (uint32_t n = 0; n < size(); ++n)
  {
    auto op = at(n);
    if (op->up() != nullptr)
    {
      continue;
    }
    roots.insert(op);
  }
  for (const auto &op : roots)
  {
    destroy_all(op);
  }
}
References coco::PtrManager< Op >::at(), destroy_all(), and coco::PtrManager< Op >::size().
Member Function Documentation
create()
template<typename T > T * coco::OpManager::create (void)
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and OpBuilder::load().
destroy()
void coco::OpManager::destroy (Op * op)
Destroy (= deallocate) a Op instance.
NOTE destroy(op) WILL NOT update op->parent(). Client SHOULD detach op before destroy(op) call
Definition at line 64 of file OpManager.cpp.
{
  assert(op->parent() == nullptr);
  release(op);
}
References coco::Op::parent(), and coco::PtrManager< Op >::release().
Referenced by destroy_all().
destroy_all()
void coco::OpManager::destroy_all (Op * op)
Destroy a Op tree.
@require op->parent() == nullptr && op->up() == nullptr
Definition at line 70 of file OpManager.cpp.
{
  assert(op->parent() == nullptr);
  assert(op->up() == nullptr);
  std::queue<coco::Op *> q;
  q.emplace(op);
  while (q.size() > 0)
  {
    auto cur = q.front();
    q.pop();
    // Insert child op nodes
    for (uint32_t n = 0; n < cur->arity(); ++n)
    {
      if (auto child = cur->arg(n))
      {
        q.emplace(child);
      }
    }
    // Destroy the current op node
    destroy(cur);
  }
}
References destroy(), coco::Op::parent(), and coco::Op::up().
Referenced by ~OpManager().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/OpManager.h
compiler/coco/core/src/IR/OpManager.cpp