ONE - On-device Neural Engine: loco::ObjectPool< T > Class Template Reference
loco::ObjectPool< T > Class Template Reference
Object Pool.
#include <ObjectPool.h>
Public Member Functions
virtual ~ObjectPool ()=default
uint32_t size (void) const
Return the number of objects.
T * at (uint32_t n) const
Access N-th object.
Protected Member Functions
template<typename U >
U * take (std::unique_ptr< U > &&o)
Take the ownership of a given object and returns its raw pointer.
bool erase (T *ptr)
Erase an object from the pool.
Detailed Description
template<typename T>
class loco::ObjectPool< T >
Object Pool.
Note
ObjectPool owns registered objects.
Definition at line 31 of file ObjectPool.h.
Constructor & Destructor Documentation
~ObjectPool()
template<typename T > virtual loco::ObjectPool< T >::~ObjectPool () virtual default
Member Function Documentation
at()
template<typename T > T * loco::ObjectPool< T >::at (uint32_t n) const inline
Access N-th object.
Definition at line 41 of file ObjectPool.h.
{ return _pool.at(n).get(); }
Referenced by loco::Pull::dtype(), exo::test::find_first_node_bytype(), moco::tf::test::find_first_node_bytype(), moco::test::find_first_node_bytype(), moco::find_node_byname(), moco::tf::test::find_nodes_bytype(), loco::Pull::index(), luci_interpreter::GraphLoader::loadTensors(), and locomotiv::Session::~Session().
erase()
template<typename T > bool loco::ObjectPool< T >::erase (T * ptr) inline protected
Erase an object from the pool.
erase(p) returns false if p does not belong to this object pool.
Definition at line 57 of file ObjectPool.h.
  {
    auto pred = [ptr](const std::unique_ptr<T> &o) { return o.get() == ptr; };
    auto it = std::find_if(_pool.begin(), _pool.end(), pred);
    if (it == _pool.end())
    {
      return false;
    }
    _pool.erase(it);
    return true;
  }
size()
template<typename T > uint32_t loco::ObjectPool< T >::size (void) const inline
Return the number of objects.
Definition at line 38 of file ObjectPool.h.
{ return _pool.size(); }
Referenced by exo::test::find_first_node_bytype(), moco::tf::test::find_first_node_bytype(), moco::test::find_first_node_bytype(), moco::find_node_byname(), moco::tf::test::find_nodes_bytype(), locomotiv::Session::input_size(), InputLayer::operator()(), and OutputLayer::operator()().
take()
template<typename T > template<typename U > U * loco::ObjectPool< T >::take (std::unique_ptr< U > && o) inline protected
Take the ownership of a given object and returns its raw pointer.
Definition at line 45 of file ObjectPool.h.
  {
    auto res = o.get();
    _pool.emplace_back(std::move(o));
    return res;
  }
Referenced by loco::Graph::SimpleFactoryObjectPool< T >::create().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/ADT/ObjectPool.h