ONE - On-device Neural Engine: nnfw::misc::tensor::Object< T > Class Template Reference
nnfw::misc::tensor::Object< T > Class Template Reference final
Class to build a tensor using specific generator.
#include <Object.h>
Public Types
using Generator = std::function< T(const Shape &shape, const Index &index)>
Function to generate tensor element.
Public Member Functions
Object (const Shape &shape, const Generator &fn)
Construct a new Object object.
const Shape & shape (void) const
Get reference of shape.
T at (const Index &index) const override
Get and element of tensor.
Public Member Functions inherited from nnfw::misc::tensor::Reader< T >
virtual ~Reader ()=default
Destroy the Reader object.
virtual T at (const Index &index) const =0
Get an element of tensor.
Detailed Description
template<typename T>
class nnfw::misc::tensor::Object< T >
Class to build a tensor using specific generator.
Template Parameters
T Type of tensor element
Definition at line 46 of file Object.h.
Member Typedef Documentation
Generator
template<typename T > using nnfw::misc::tensor::Object< T >::Generator = std::function<T(const Shape &shape, const Index &index)>
Function to generate tensor element.
Definition at line 52 of file Object.h.
Constructor & Destructor Documentation
Object()
template<typename T > nnfw::misc::tensor::Object< T >::Object (const Shape & shape, const Generator & fn) inline
Construct a new Object object.
Parameters
[in] shape Tensor shape
[in] fn Function to generate tensor elements
Definition at line 60 of file Object.h.
                                                  : _shape{shape}
  {
    // Set 'stride'
    _stride.init(shape);
    // Handle scalar object
    if (shape.rank() == 0)
    {
      _values.resize(1);
      _values.at(0) = fn(_shape, 0);
    }
    else
    {
      // Pre-allocate buffer
      _values.resize(_shape.dim(0) * _stride.at(0));
      // Set 'value'
      iterate(_shape) <<
        [this, &fn](const Index &index) { _values.at(_stride.offset(index)) = fn(_shape, index); };
    }
  }
References nnfw::misc::tensor::NonIncreasingStride::at(), nnfw::misc::tensor::Shape::dim(), nnfw::misc::tensor::NonIncreasingStride::init(), nnfw::misc::tensor::iterate(), nnfw::misc::tensor::NonIncreasingStride::offset(), nnfw::misc::tensor::Shape::rank(), and nnfw::misc::tensor::Object< T >::shape().
Member Function Documentation
at()
template<typename T > T nnfw::misc::tensor::Object< T >::at (const Index & index) const inline override virtual
Get and element of tensor.
Parameters
[in] index Index of a tensor element
Returns
Value of tensor element
Implements nnfw::misc::tensor::Reader< T >.
Definition at line 95 of file Object.h.
{ return _values.at(_stride.offset(index)); }
References nnfw::misc::tensor::NonIncreasingStride::offset().
shape()
template<typename T > const Shape & nnfw::misc::tensor::Object< T >::shape (void) const inline
Get reference of shape.
Returns
Reference of shape
Definition at line 87 of file Object.h.
{ return _shape; }
Referenced by nnfw::misc::tensor::Object< T >::Object().
The documentation for this class was generated from the following file:
runtime/libs/misc/include/misc/tensor/Object.h