ONE - On-device Neural Engine: onert_micro::core::OMRuntimeGraph Class Reference
onert_micro::core::OMRuntimeGraph Class Reference
#include <OMRuntimeGraph.h>
Public Member Functions
OMRuntimeGraph ()=default
OMRuntimeGraph (const OMRuntimeGraph &)=delete
OMRuntimeGraph (OMRuntimeGraph &&)=default
OMRuntimeGraph & operator= (const OMRuntimeGraph &)=delete
OMRuntimeGraph && operator= (const OMRuntimeGraph &&)=delete
~OMRuntimeGraph ()
uint32_t getNumberOfInputs ()
uint32_t getNumberOfOutputs ()
uint32_t getInputSizeAt (uint32_t position)
uint32_t getOutputSizeAt (uint32_t position)
void * getInputDataAt (uint32_t position)
void * getOutputDataAt (uint32_t position)
OMStatus allocateGraphInputs ()
OMStatus reset ()
OMRuntimeStorage & getRuntimeStorage ()
memory::OMRuntimeAllocator & getRuntimeAllocator ()
OMRuntimeContext & getRuntimeContext ()
Detailed Description
Definition at line 33 of file OMRuntimeGraph.h.
Constructor & Destructor Documentation
OMRuntimeGraph() [1/3]
onert_micro::core::OMRuntimeGraph::OMRuntimeGraph () default
OMRuntimeGraph() [2/3]
onert_micro::core::OMRuntimeGraph::OMRuntimeGraph (const OMRuntimeGraph &) delete
OMRuntimeGraph() [3/3]
onert_micro::core::OMRuntimeGraph::OMRuntimeGraph (OMRuntimeGraph &&) default
~OMRuntimeGraph()
OMRuntimeGraph::~OMRuntimeGraph ()
Definition at line 31 of file OMRuntimeGraph.cpp.
{ reset(); }
References reset().
Member Function Documentation
allocateGraphInputs()
OMStatus OMRuntimeGraph::allocateGraphInputs ()
Definition at line 58 of file OMRuntimeGraph.cpp.
{
  return _allocator.allocateGraphInputs(&_context, &_storage);
}
References onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getInputDataAt()
void * OMRuntimeGraph::getInputDataAt (uint32_t position)
Definition at line 33 of file OMRuntimeGraph.cpp.
{
  const auto input_index = _context.getGraphInputTensorIndex(position);
  uint8_t *data;
  _storage.getDataByTensorIndex(&data, input_index);
  if (data == nullptr)
  {
    _allocator.allocateGraphInputs(&_context, &_storage);
    _storage.getDataByTensorIndex(&data, input_index);
  }
  return reinterpret_cast<void *>(data);
}
References onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), and onert_micro::core::OMRuntimeContext::getGraphInputTensorIndex().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getInputSizeAt()
uint32_t OMRuntimeGraph::getInputSizeAt (uint32_t position)
Definition at line 72 of file OMRuntimeGraph.cpp.
{
  const auto input_index = _context.getGraphInputTensorIndex(position);
  const circle::Tensor *input_tensor = _context.getTensorByIndex(input_index);
  OMRuntimeShape shape(input_tensor);
  return shape.flatSize();
}
References onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeContext::getGraphInputTensorIndex(), and onert_micro::core::OMRuntimeContext::getTensorByIndex().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getNumberOfInputs()
uint32_t OMRuntimeGraph::getNumberOfInputs ()
Definition at line 90 of file OMRuntimeGraph.cpp.
{
  auto *inputs = _context.getCircleInputs();
  if (inputs == nullptr)
    return 0;
  return inputs->size();
}
References onert_micro::core::OMRuntimeContext::getCircleInputs().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getNumberOfOutputs()
uint32_t OMRuntimeGraph::getNumberOfOutputs ()
Definition at line 81 of file OMRuntimeGraph.cpp.
{
  auto *outputs = _context.getCircleOutputs();
  if (outputs == nullptr)
    return 0;
  return outputs->size();
}
References onert_micro::core::OMRuntimeContext::getCircleOutputs(), and flatbuffers::Vector< T >::size().
getOutputDataAt()
void * OMRuntimeGraph::getOutputDataAt (uint32_t position)
Definition at line 49 of file OMRuntimeGraph.cpp.
{
  const auto output_index = _context.getGraphOutputTensorIndex(position);
  uint8_t *data;
  _storage.getDataByTensorIndex(&data, output_index);
  return reinterpret_cast<void *>(data);
}
References onert_micro::core::OMRuntimeStorage::getDataByTensorIndex(), and onert_micro::core::OMRuntimeContext::getGraphOutputTensorIndex().
getOutputSizeAt()
uint32_t OMRuntimeGraph::getOutputSizeAt (uint32_t position)
Definition at line 63 of file OMRuntimeGraph.cpp.
{
  const auto output_index = _context.getGraphOutputTensorIndex(position);
  const circle::Tensor *output_tensor = _context.getTensorByIndex(output_index);
  OMRuntimeShape shape(output_tensor);
  return shape.flatSize();
}
References onert_micro::core::OMRuntimeShape::flatSize(), onert_micro::core::OMRuntimeContext::getGraphOutputTensorIndex(), and onert_micro::core::OMRuntimeContext::getTensorByIndex().
getRuntimeAllocator()
memory::OMRuntimeAllocator & onert_micro::core::OMRuntimeGraph::getRuntimeAllocator () inline
Definition at line 63 of file OMRuntimeGraph.h.
{ return _allocator; }
Referenced by onert_micro::core::OMRuntimeModule::run(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getRuntimeContext()
OMRuntimeContext & onert_micro::core::OMRuntimeGraph::getRuntimeContext () inline
Definition at line 65 of file OMRuntimeGraph.h.
{ return _context; }
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), onert_micro::core::OMRuntimeModule::run(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
getRuntimeStorage()
OMRuntimeStorage & onert_micro::core::OMRuntimeGraph::getRuntimeStorage () inline
Definition at line 61 of file OMRuntimeGraph.h.
{ return _storage; }
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), onert_micro::core::OMRuntimeModule::run(), and onert_micro::core::OMTrainingRuntimeModule::trainSingleStep().
operator=() [1/2]
OMRuntimeGraph && onert_micro::core::OMRuntimeGraph::operator= (const OMRuntimeGraph &&) delete
operator=() [2/2]
OMRuntimeGraph & onert_micro::core::OMRuntimeGraph::operator= (const OMRuntimeGraph &) delete
reset()
OMStatus OMRuntimeGraph::reset ()
Definition at line 23 of file OMRuntimeGraph.cpp.
{
  OMStatus status = _allocator.clearAllTensorsData(&_context, &_storage);
  _storage.clearTensorIndexToData();
  return status;
}
References onert_micro::core::memory::OMRuntimeAllocator::clearAllTensorsData(), and onert_micro::core::OMRuntimeStorage::clearTensorIndexToData().
Referenced by onert_micro::core::OMTrainingRuntimeModule::evaluateMetric(), onert_micro::core::OMTrainingRuntimeModule::trainSingleStep(), and ~OMRuntimeGraph().
The documentation for this class was generated from the following files:
onert-micro/onert-micro/include/core/OMRuntimeGraph.h
onert-micro/onert-micro/src/core/OMRuntimeGraph.cpp