ONE - On-device Neural Engine: arm_compute::NEMultiplyScaleFactorKernel Class Reference
arm_compute::NEMultiplyScaleFactorKernel Class Reference
#include <NEMuliplyScaleFactorKernel.h>
Public Member Functions
const char * name () const override
NEMultiplyScaleFactorKernel ()
NEMultiplyScaleFactorKernel (const NEMultiplyScaleFactorKernel &)=delete
NEMultiplyScaleFactorKernel & operator= (const NEMultiplyScaleFactorKernel &)=delete
NEMultiplyScaleFactorKernel (NEMultiplyScaleFactorKernel &&)=default
NEMultiplyScaleFactorKernel & operator= (NEMultiplyScaleFactorKernel &&)=default
~NEMultiplyScaleFactorKernel ()=default
void configure (const ITensor *input, const ITensor *scale_factor, ITensor *output, float multiplier=1.f)
void run (const Window &window, const ThreadInfo &info) override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *scale_factor, const ITensorInfo *output, float multiplier=1.f)
Detailed Description
Interface to multiply scale factor kernel.
Definition at line 51 of file NEMuliplyScaleFactorKernel.h.
Constructor & Destructor Documentation
NEMultiplyScaleFactorKernel() [1/3]
NEMultiplyScaleFactorKernel::NEMultiplyScaleFactorKernel ()
Default constructor
Definition at line 137 of file NEMultiplyScaleFactorKernel.cpp.
  : _input(nullptr), _scale_factor(nullptr), _output(nullptr), _multiplier(1.f)
{
}
NEMultiplyScaleFactorKernel() [2/3]
arm_compute::NEMultiplyScaleFactorKernel::NEMultiplyScaleFactorKernel (const NEMultiplyScaleFactorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
NEMultiplyScaleFactorKernel() [3/3]
arm_compute::NEMultiplyScaleFactorKernel::NEMultiplyScaleFactorKernel (NEMultiplyScaleFactorKernel &&) default
Default Move Constructor.
~NEMultiplyScaleFactorKernel()
arm_compute::NEMultiplyScaleFactorKernel::~NEMultiplyScaleFactorKernel () default
Default destructor
References validate().
Member Function Documentation
configure()
void NEMultiplyScaleFactorKernel::configure (const ITensor * input, const ITensor * scale_factor, ITensor * output, float multiplier = 1.f)
Set input, output tensors.
Parameters
[in/out] input Source tensor. Data type supported: S32.
[in] scale_factor Scale tensor. Data type supported: F16/F32.
[out] output Destination tensor. Data type supported: Same as scale_factor.
Definition at line 142 of file NEMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, output);
  ARM_COMPUTE_ERROR_THROW_ON(
    validate_arguments(input->info(), scale_factor->info(), output->info()));
  _input = input;
  _scale_factor = scale_factor;
  _output = output;
  _multiplier = multiplier;
  // Configure kernel window
  Window win_config = calculate_max_window(*input->info(), Steps());
  Coordinates coord;
  coord.set_num_dimensions(output->info()->num_dimensions());
  output->info()->set_valid_region(ValidRegion(coord, output->info()->tensor_shape()));
  INEKernel::configure(win_config);
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::configure().
name()
const char * arm_compute::NEMultiplyScaleFactorKernel::name () const inline override
Definition at line 54 of file NEMuliplyScaleFactorKernel.h.
{ return "NEMultiplyScaleFactorKernel"; }
operator=() [1/2]
NEMultiplyScaleFactorKernel & arm_compute::NEMultiplyScaleFactorKernel::operator= (const NEMultiplyScaleFactorKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
operator=() [2/2]
NEMultiplyScaleFactorKernel & arm_compute::NEMultiplyScaleFactorKernel::operator= (NEMultiplyScaleFactorKernel &&) default
Default move assignment operator
run()
void NEMultiplyScaleFactorKernel::run (const Window & window, const ThreadInfo & info) override
Definition at line 208 of file NEMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_UNUSED(info);
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(INEKernel::window(), window);
  switch (_output->info()->data_type())
  {
    case DataType::F32:
      NEMultiplyScaleFactorKernel::multiply<float>(window);
      break;
#ifdef __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
    case DataType::F16:
      NEMultiplyScaleFactorKernel::multiply<float16_t>(window);
      break;
#endif // __ARM_FEATURE_FP16_VECTOR_ARITHMETIC
    default:
      ARM_COMPUTE_ERROR("Unsupported data type.");
  }
}
References info.
validate()
Status NEMultiplyScaleFactorKernel::validate (const ITensorInfo * input, const ITensorInfo * scale_factor, const ITensorInfo * output, float multiplier = 1.f) static
Static function to check if given info will lead to a valid configuration of NEMultiplyScaleFactorKernel
Parameters
[in] input Input tensor info. Data types supported: S32.
[in] scale_factor Scale tensor. Data type supported: F16/F32.
[in] output Output tensor info. Data types supported: Same as scale_factor.
Returns
a status
Definition at line 164 of file NEMultiplyScaleFactorKernel.cpp.
{
  ARM_COMPUTE_UNUSED(multiplier);
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(input, scale_factor, output));
  return Status{};
}
Referenced by arm_compute::NEFullyConnectedHybridLayer::validate(), and ~NEMultiplyScaleFactorKernel().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/NEON/kernels/NEMuliplyScaleFactorKernel.h
compute/ARMComputeEx/src/core/NEON/kernels/NEMultiplyScaleFactorKernel.cpp