ONE - On-device Neural Engine: enco::SubnetBlockCompiler Class Reference
enco::SubnetBlockCompiler Class Reference
Generate C++ code that invokes Android NN subnet.
#include <Subnet.h>
Public Member Functions
SubnetBlockCompiler (const enco::MemoryContext &mem)
void bind (const ANNBinder *binder, const std::string &exp)
Specify how to access ANeuralNetworksCompilation value (C expression)
std::unique_ptr< pp::MultiLineText > compile (const ANNBinder *binder) const
Detailed Description
Generate C++ code that invokes Android NN subnet.
Definition at line 69 of file Subnet.h.
Constructor & Destructor Documentation
SubnetBlockCompiler()
enco::SubnetBlockCompiler::SubnetBlockCompiler (const enco::MemoryContext & mem) inline
Definition at line 72 of file Subnet.h.
                                                    : _mem(mem)
  {
    // DO NOTHING
  }
Member Function Documentation
bind()
void enco::SubnetBlockCompiler::bind (const ANNBinder * binder, const std::string & exp) inline
Specify how to access ANeuralNetworksCompilation value (C expression)
Definition at line 79 of file Subnet.h.
{ _compilation_ctx[binder] = exp; }
compile()
std::unique_ptr< pp::MultiLineText > enco::SubnetBlockCompiler::compile (const ANNBinder * binder) const
Definition at line 379 of file Subnet.cpp.
{
  auto res = make_unique<pp::LinearDocument>();
  const auto compilation = _compilation_ctx.at(binder);
  res->append("ANeuralNetworksExecution *execution;");
  res->append("ANeuralNetworksEvent *event;");
  res->append();
  res->append("ANeuralNetworksExecution_create(", compilation, ", &execution);");
  // Emit ANeuralNetworksExecution_setInput call(s)
  for (uint32_t n = 0; n < binder->module()->input()->size(); ++n)
  {
    auto bag = binder->input(n);
    auto base = _mem.base(bag);
    auto size = _mem.size(bag);
    res->append("ANeuralNetworksExecution_setInput(execution, ", n, ", nullptr, ", base, ", ", size,
                ");");
  }
  // Emit ANeuralNetworksExecution_setOutput call(s)
  for (uint32_t n = 0; n < binder->module()->output()->size(); ++n)
  {
    auto bag = binder->output(n);
    auto base = _mem.base(bag);
    auto size = _mem.size(bag);
    res->append("ANeuralNetworksExecution_setOutput(execution, ", n, ", nullptr, ", base, ", ",
                size, ");");
  }
  res->append("ANeuralNetworksExecution_startCompute(execution, &event);");
  res->append("ANeuralNetworksEvent_wait(event);");
  res->append("ANeuralNetworksEvent_free(event);");
  res->append("ANeuralNetworksExecution_free(execution);");
  return res;
}
References ANNBinder::input(), ANNBinder::module(), and ANNBinder::output().
The documentation for this class was generated from the following files:
compiler/enco/core/src/CppGen/Subnet.h
compiler/enco/core/src/CppGen/Subnet.cpp