ONE - On-device Neural Engine: coco::Read Class Reference
coco::Read Class Reference final
A Read represents an edge between a Bag and its Reader.
#include <Read.h>
Public Member Functions
Read (Bag::Reader *r)
~Read ()
Bag * bag (void) const
void bag (Bag *bag)
Bag::Reader * reader (void) const
void reader (Bag::Reader *r)
Detailed Description
A Read represents an edge between a Bag and its Reader.
Definition at line 28 of file Read.h.
Constructor & Destructor Documentation
Read()
coco::Read::Read (Bag::Reader * r) inline
Definition at line 31 of file Read.h.
  {
    // Initialize link and reader
    reader(r);
  }
References reader().
~Read()
coco::Read::~Read ()
Definition at line 24 of file Read.cpp.
{
  // Unlink self from Bag if there is a linked bag
  bag(nullptr);
}
References bag().
Member Function Documentation
bag() [1/2]
void coco::Read::bag (Bag * bag)
Definition at line 30 of file Read.cpp.
{
  if (_bag)
  {
    _bag->mutable_reads()->erase(this);
    _bag = nullptr;
  }
  assert(_bag == nullptr);
  if (bag)
  {
    _bag = bag;
    _bag->mutable_reads()->insert(this);
  }
  assert(_bag == bag);
}
References bag().
Referenced by bag().
bag() [2/2]
Bag * coco::Read::bag (void) const inline
Definition at line 41 of file Read.h.
{ return _bag; }
Referenced by bag(), coco::Shuffle::from(), and ~Read().
reader() [1/2]
void coco::Read::reader (Bag::Reader * r) inline
Definition at line 46 of file Read.h.
{ _reader = r; }
reader() [2/2]
Bag::Reader * coco::Read::reader (void) const inline
Definition at line 45 of file Read.h.
{ return _reader; }
Referenced by Read().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Read.h
compiler/coco/core/src/IR/Read.cpp