ONE - On-device Neural Engine: loco::PermutingEncoder< Domain::DepthwiseFilter > Class Reference
loco::PermutingEncoder< Domain::DepthwiseFilter > Class Reference final
Permutation-based Tensor-to-DepthwiseFilter converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingEncoder ()=default
PermutingEncoder (const Permutation< Domain::DepthwiseFilter > &perm)
bool valid (void) const
DepthwiseFilterShape shape (const TensorShape &tensor_shape) const override
TensorIndex value (const DepthwiseFilterIndex &index) const override
const Permutation< Domain::DepthwiseFilter > * perm (void) const
Permutation< Domain::DepthwiseFilter > * perm (void)
void perm (const Permutation< Domain::DepthwiseFilter > &p)
Public Member Functions inherited from loco::DepthwiseFilterEncoder
virtual ~DepthwiseFilterEncoder ()=default
virtual DepthwiseFilterShape shape (const TensorShape &shape) const =0
virtual TensorIndex value (const DepthwiseFilterIndex &index) const =0
Detailed Description
Permutation-based Tensor-to-DepthwiseFilter converter.
Definition at line 267 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingEncoder() [1/2]
loco::PermutingEncoder< Domain::DepthwiseFilter >::PermutingEncoder () default
PermutingEncoder() [2/2]
loco::PermutingEncoder< Domain::DepthwiseFilter >::PermutingEncoder (const Permutation< Domain::DepthwiseFilter > & perm) inline
Definition at line 273 of file PermutingCodec.h.
                                                                   : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingEncoder< Domain::DepthwiseFilter >::perm (const Permutation< Domain::DepthwiseFilter > & p) inline
Definition at line 288 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::DepthwiseFilter > * loco::PermutingEncoder< Domain::DepthwiseFilter >::perm (void) inline
Definition at line 287 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::DepthwiseFilter > * loco::PermutingEncoder< Domain::DepthwiseFilter >::perm (void) const inline
Definition at line 286 of file PermutingCodec.h.
{ return &_perm; }
shape()
DepthwiseFilterShape loco::PermutingEncoder< Domain::DepthwiseFilter >::shape (const TensorShape & tensor_shape) const override virtual
Implements loco::DepthwiseFilterEncoder.
Definition at line 426 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  DepthwiseFilterShape out;
  out.depth() = in.dim(_perm[DepthwiseFilterAxis::Depth]);
  out.multiplier() = in.dim(_perm[DepthwiseFilterAxis::Multiplier]);
  out.height() = in.dim(_perm[DepthwiseFilterAxis::Height]);
  out.width() = in.dim(_perm[DepthwiseFilterAxis::Width]);
  return out;
}
References loco::Depth, loco::DepthwiseFilterShape::depth(), loco::TensorShape::dim(), loco::Height, loco::DepthwiseFilterShape::height(), loco::Multiplier, loco::DepthwiseFilterShape::multiplier(), loco::valid(), loco::Width, and loco::DepthwiseFilterShape::width().
valid()
bool loco::PermutingEncoder< Domain::DepthwiseFilter >::valid (void) const
Definition at line 456 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
TensorIndex loco::PermutingEncoder< Domain::DepthwiseFilter >::value (const DepthwiseFilterIndex & index) const override virtual
Implements loco::DepthwiseFilterEncoder.
Definition at line 440 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorIndex out;
  out.resize(4);
  out.at(_perm[DepthwiseFilterAxis::Depth]) = in.channel();
  out.at(_perm[DepthwiseFilterAxis::Multiplier]) = in.nth();
  out.at(_perm[DepthwiseFilterAxis::Height]) = in.row();
  out.at(_perm[DepthwiseFilterAxis::Width]) = in.column();
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::DepthwiseFilterIndex::channel(), loco::DepthwiseFilterIndex::column(), loco::Depth, loco::Height, loco::Multiplier, loco::DepthwiseFilterIndex::nth(), nncc::core::ADT::tensor::Index::resize(), loco::DepthwiseFilterIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp