ONE - On-device Neural Engine: exo::AvgPool2DConverter Class Reference
exo::AvgPool2DConverter Class Reference
Convert loco::AvgPool2D to locoex::TFLAveragePool2D.
#include <AvgPool2DConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::AvgPool2D *origin) final
Converts loco::AvgPool2D to locoex::TFLAveragePool2D.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::AvgPool2D >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::AvgPool2D *node)=0
Detailed Description
Convert loco::AvgPool2D to locoex::TFLAveragePool2D.
Definition at line 30 of file AvgPool2DConverter.h.
Member Function Documentation
convert()
bool exo::AvgPool2DConverter::convert (loco::AvgPool2D * origin) final virtual
Converts loco::AvgPool2D to locoex::TFLAveragePool2D.
How it works: (note: ten->fea means input: tensor, output: feature)
Before: Foo -— FeatureEncode -— AvgPool2D -— FeatureDecode -— Bar ten->ten ten->fea fea->fea fea->ten ten->ten
After: AvgPool2D / Foo – FeatureEncode - FeatureDecode - TFLAvgPool2D - FeatureEncode - FeatureDecode – Bar ten->ten ten->fea fea->ten ten->ten ten->fea fea->ten ten->ten
Note
This method replaces AvgPool2D with "FeatureDecode -- TFLAvgPool2D -- FeatureEncode". Redundant nodes will be removed during transforms.
Implements exo::CanonicalNodeConverter< loco::AvgPool2D >.
Definition at line 45 of file AvgPool2DConverter.cpp.
{
  auto *graph = origin->graph();
  auto dec = make_feature_decode<FeatureLayout::NHWC>(origin->ifm());
  auto tfl_average = graph->nodes()->create<locoex::TFLAveragePool2D>();
  {
    tfl_average->value(dec);
    // set attributes
    tfl_average->stride()->w(origin->stride()->horizontal());
    tfl_average->stride()->h(origin->stride()->vertical());
    tfl_average->filter()->w(origin->window()->horizontal());
    tfl_average->filter()->h(origin->window()->vertical());
    auto pad = origin->pad();
    if (pad->bottom() == 0 && pad->top() == 0 && pad->left() == 0 && pad->right() == 0)
      tfl_average->padding(locoex::Padding::VALID);
    else
      // TODO This is necessary, but not sufficient condition. More rigorous check required
      tfl_average->padding(locoex::Padding::SAME);
    tfl_average->fusedActivationFunction(locoex::FusedActFunc::NONE);
  }
  auto enc = make_feature_encode<FeatureLayout::NHWC>(tfl_average);
  // replace canonical node
  loco::replace(origin).with(enc);
  origin->ifm(nullptr);
  return true;
}
References loco::Node::graph(), loco::Stride< 2 >::horizontal(), loco::Window< 2 >::horizontal(), loco::AvgPool2D::ifm(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), locoex::NONE, loco::AvgPool2D::pad(), loco::replace(), locoex::SAME, loco::AvgPool2D::stride(), locoex::VALID, locoex::TFLAveragePool2D::value(), loco::Stride< 2 >::vertical(), loco::Window< 2 >::vertical(), loco::AvgPool2D::window(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::AvgPool2DConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::AvgPool2D >.
Definition at line 33 of file AvgPool2DConverter.h.
{ return "exo::AvgPool2DConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/AvgPool2DConverter.h
compiler/exo/src/Conversion/AvgPool2DConverter.cpp