ONE - On-device Neural Engine: onert::compiler::Linear Class Reference
onert::compiler::Linear Class Reference
#include <Linear.h>
Static Public Member Functions
static std::vector< ir::OperationIndex > linearize (const compiler::LoweredGraph &lowered_graph)
static void dump (const compiler::LoweredGraph &lowered_graph, const std::vector< ir::OperationIndex > &order)
Detailed Description
Definition at line 31 of file Linear.h.
Member Function Documentation
dump()
void onert::compiler::Linear::dump (const compiler::LoweredGraph & lowered_graph, const std::vector< ir::OperationIndex > & order) static
Definition at line 37 of file Linear.cc.
{
  for (const auto ind : order)
  {
    // TODO Could logging system can handle this? (Inserting prefix for each line)
    std::istringstream iss{dumper::text::formatOperation(lowered_graph.graph(), ind)};
    std::string line;
    while (std::getline(iss, line))
      VERBOSE(GraphDumper) << line << std::endl;
  }
}
References onert::dumper::text::formatOperation(), onert::compiler::LoweredGraph::graph(), and VERBOSE.
linearize()
std::vector< ir::OperationIndex > onert::compiler::Linear::linearize (const compiler::LoweredGraph & lowered_graph) static
Definition at line 31 of file Linear.cc.
{
  return lowered_graph.graph().topolSortOperations();
}
References onert::compiler::LoweredGraph::graph(), and onert::ir::Graph::topolSortOperations().
The documentation for this class was generated from the following files:
runtime/onert/core/src/compiler/Linear.h
runtime/onert/core/src/compiler/Linear.cc