ONE - On-device Neural Engine: luci_interpreter::kernels::Transpose Class Reference
luci_interpreter::kernels::Transpose Class Reference
#include <Transpose.h>
Public Member Functions
Transpose (const Tensor *input, const Tensor *perm, Tensor *output)
const Tensor * input () const
const Tensor * perm () const
Tensor * output () const
void configure () override
void execute () const override
Transpose (const Tensor *input, const Tensor *perm, Tensor *output)
const Tensor * input () const
const Tensor * perm () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Transpose.h.
Constructor & Destructor Documentation
Transpose() [1/2]
luci_interpreter::kernels::Transpose::Transpose (const Tensor * input, const Tensor * perm, Tensor * output)
Definition at line 31 of file Transpose.cpp.
  : Kernel({input, perm}, {output})
{
}
References input(), and perm().
Transpose() [2/2]
luci_interpreter::kernels::Transpose::Transpose (const Tensor * input, const Tensor * perm, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Transpose::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 36 of file Transpose.cpp.
{
  // Transpose op only supports 1D-4D input arrays.
  int dims = input()->shape().num_dims();
  const int32_t *perm_data = getTensorData<int32_t>(perm());
  assert(input()->shape().num_dims() <= 4);
  assert(input()->element_type() == output()->element_type());
  assert(perm()->shape().num_dims() == 1);
  assert(perm()->shape().dim(0) == dims);
  Shape output_shape(dims);
  for (int i = 0; i < dims; i++)
  {
    assert(perm_data[i] < dims && perm_data[i] >= 0);
    output_shape.dim(i) = input()->shape().dim(perm_data[i]);
  }
  output()->resize(output_shape);
}
References luci_interpreter::Shape::dim(), input(), luci_interpreter::Shape::num_dims(), output(), perm(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Transpose::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Transpose::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 58 of file Transpose.cpp.
{
  tflite::TransposeParams params{};
  const int32_t *perm_data = getTensorData<int32_t>(perm());
  const int32_t size = perm()->shape().dim(0);
  params.perm_count = size;
  for (int i = 0; i < size; i++)
    params.perm[i] = perm_data[i];
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      tflite::reference_ops::Transpose(params, getTensorShape(input()),
                                       getTensorData<float>(input()), getTensorShape(output()),
                                       getTensorData<float>(output()));
      break;
    case DataType::U8:
      tflite::reference_ops::Transpose(params, getTensorShape(input()),
                                       getTensorData<uint8_t>(input()), getTensorShape(output()),
                                       getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References luci_interpreter::Shape::dim(), luci_interpreter::kernels::getTensorShape(), input(), output(), perm(), luci_interpreter::Tensor::shape(), and luci_interpreter::size().
execute() [2/2]
void luci_interpreter::kernels::Transpose::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Transpose::input () const inline
Definition at line 33 of file Transpose.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Transpose().
input() [2/2]
const Tensor * luci_interpreter::kernels::Transpose::input () const inline
Definition at line 33 of file Transpose.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Transpose::output () const inline
Definition at line 35 of file Transpose.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::Transpose::output () const inline
Definition at line 35 of file Transpose.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
perm() [1/2]
const Tensor * luci_interpreter::kernels::Transpose::perm () const inline
Definition at line 34 of file Transpose.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Transpose().
perm() [2/2]
const Tensor * luci_interpreter::kernels::Transpose::perm () const inline
Definition at line 34 of file Transpose.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Transpose.h
onert-micro/luci-interpreter/src/kernels/Transpose.h
compiler/luci-interpreter/src/kernels/Transpose.cpp
onert-micro/luci-interpreter/src/kernels/Transpose.cpp