ONE - On-device Neural Engine: luci_interpreter::kernels::SpaceToBatchND Class Reference
luci_interpreter::kernels::SpaceToBatchND Class Reference
#include <SpaceToBatchND.h>
Public Member Functions
SpaceToBatchND (const Tensor *input, const Tensor *block_shape, const Tensor *paddings, Tensor *output)
const Tensor * input () const
const Tensor * block_shape () const
const Tensor * paddings () const
Tensor * output () const
void configure () override
void execute () const override
SpaceToBatchND (const Tensor *input, const Tensor *block_shape, const Tensor *paddings, Tensor *output)
const Tensor * input () const
const Tensor * block_shape () const
const Tensor * paddings () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file SpaceToBatchND.h.
Constructor & Destructor Documentation
SpaceToBatchND() [1/2]
luci_interpreter::kernels::SpaceToBatchND::SpaceToBatchND (const Tensor * input, const Tensor * block_shape, const Tensor * paddings, Tensor * output)
Definition at line 37 of file SpaceToBatchND.cpp.
  : Kernel({input, block_shape, paddings}, {output})
{
}
References block_shape(), input(), and paddings().
SpaceToBatchND() [2/2]
luci_interpreter::kernels::SpaceToBatchND::SpaceToBatchND (const Tensor * input, const Tensor * block_shape, const Tensor * paddings, Tensor * output)
Member Function Documentation
block_shape() [1/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::block_shape () const inline
Definition at line 34 of file SpaceToBatchND.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SpaceToBatchND().
block_shape() [2/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::block_shape () const inline
Definition at line 34 of file SpaceToBatchND.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::SpaceToBatchND::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 43 of file SpaceToBatchND.cpp.
{
  const auto *block_shape_data = block_shape()->data<int32_t>();
  const auto *paddings_data = paddings()->data<int32_t>();
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() >= kInputMinDimensionNum);
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() <= kInputMaxDimensionNum);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  int spatial_dims_num = input()->shape().num_dims() - 2;
  LUCI_INTERPRETER_CHECK(block_shape()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(block_shape()->shape().dim(0) == spatial_dims_num);
  LUCI_INTERPRETER_CHECK(paddings()->shape().num_dims() == 2);
  LUCI_INTERPRETER_CHECK(paddings()->shape().dim(0) == spatial_dims_num);
  LUCI_INTERPRETER_CHECK(paddings()->shape().dim(1) == 2);
  Shape output_shape = Shape(input()->shape().num_dims());
  int output_batch_size = input()->shape().dim(0);
  for (int i = 0; i < spatial_dims_num; ++i)
  {
    int final_dim_size =
      (input()->shape().dim(i + 1) + paddings_data[i * 2] + paddings_data[i * 2 + 1]);
    LUCI_INTERPRETER_CHECK(final_dim_size % block_shape_data[i] == 0);
    output_shape.dim(i + 1) = final_dim_size / block_shape_data[i];
    output_batch_size = output_batch_size * block_shape_data[i];
  }
  output_shape.dim(0) = output_batch_size;
  output_shape.dim(input()->shape().num_dims() - 1) =
    input()->shape().dim(input()->shape().num_dims() - 1);
  output()->resize(output_shape);
}
References block_shape(), luci_interpreter::Tensor::data(), luci_interpreter::Shape::dim(), input(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), paddings(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::SpaceToBatchND::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::SpaceToBatchND::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 76 of file SpaceToBatchND.cpp.
{
  switch (input()->element_type())
  {
    tflite::SpaceToBatchParams op_params;
    case DataType::FLOAT32:
      op_params.output_offset = 0;
      luci_interpreter_pal::SpaceToBatchND(
        op_params, getTensorShape(input()), getTensorData<float>(input()),
        getTensorShape(block_shape()), getTensorData<int32_t>(block_shape()),
        getTensorShape(paddings()), getTensorData<int32_t>(paddings()), getTensorShape(output()),
        getTensorData<float>(output()));
      break;
    case DataType::U8:
      op_params.output_offset = output()->zero_point();
      luci_interpreter_pal::SpaceToBatchND(
        op_params, getTensorShape(input()), getTensorData<uint8_t>(input()),
        getTensorShape(block_shape()), getTensorData<int32_t>(block_shape()),
        getTensorShape(paddings()), getTensorData<int32_t>(paddings()), getTensorShape(output()),
        getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References block_shape(), luci_interpreter::kernels::getTensorShape(), input(), output(), paddings(), and luci_interpreter::Tensor::zero_point().
execute() [2/2]
void luci_interpreter::kernels::SpaceToBatchND::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::input () const inline
Definition at line 33 of file SpaceToBatchND.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SpaceToBatchND().
input() [2/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::input () const inline
Definition at line 33 of file SpaceToBatchND.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::SpaceToBatchND::output () const inline
Definition at line 36 of file SpaceToBatchND.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::SpaceToBatchND::output () const inline
Definition at line 36 of file SpaceToBatchND.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
paddings() [1/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::paddings () const inline
Definition at line 35 of file SpaceToBatchND.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and SpaceToBatchND().
paddings() [2/2]
const Tensor * luci_interpreter::kernels::SpaceToBatchND::paddings () const inline
Definition at line 35 of file SpaceToBatchND.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/SpaceToBatchND.h
onert-micro/luci-interpreter/src/kernels/SpaceToBatchND.h
compiler/luci-interpreter/src/kernels/SpaceToBatchND.cpp
onert-micro/luci-interpreter/src/kernels/SpaceToBatchND.cpp