ONE - On-device Neural Engine: ShapeQuery Class Reference
ShapeQuery Class Reference
A wrapper class that allows additional queries over tensor shape.
#include <ShapeQuery.h>
Public Member Functions
ShapeQuery (const nncc::core::ADT::tensor::Shape *shape)
uint32_t axis (const AxisSpecifier &) const
Return the dimension number (axis) specified by a given axis specifier.
Detailed Description
A wrapper class that allows additional queries over tensor shape.
Definition at line 57 of file ShapeQuery.h.
Constructor & Destructor Documentation
ShapeQuery()
ShapeQuery::ShapeQuery (const nncc::core::ADT::tensor::Shape * shape) inline explicit
Definition at line 60 of file ShapeQuery.h.
                                                           : _shape{shape}
  {
    // DO NOTHING
  }
Member Function Documentation
axis()
uint32_t ShapeQuery::axis (const AxisSpecifier & specifier) const
Return the dimension number (axis) specified by a given axis specifier.
Definition at line 29 of file ShapeQuery.cpp.
{
  if (specifier.value() > 0)
  {
    return static_cast<uint32_t>(specifier.value());
  }
  assert(_shape->rank() >= static_cast<uint32_t>(-specifier.value()));
  return static_cast<uint32_t>(_shape->rank() + specifier.value());
}
References nncc::core::ADT::tensor::Shape::rank(), and AxisSpecifier::value().
Referenced by ConvolutionSpec::channel_axis().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/ShapeQuery.h
compiler/enco/frontend/caffe/src/ShapeQuery.cpp