ONE - On-device Neural Engine: nnfw::misc::vector::Object< T > Class Template Reference
nnfw::misc::vector::Object< T > Class Template Reference final
Class to have information of the operand for vector.
#include <Object.h>
Public Types
using Generator = std::function< T(int32_t size, int32_t offset)>
Public Member Functions
Object (int32_t size, const Generator &gen)
Construct Object object with size of vector and set value used by Generator.
int32_t size (void) const
Get size of vector.
T at (uint32_t nth) const override
Get the value used by index.
Public Member Functions inherited from nnfw::misc::vector::Reader< T >
virtual ~Reader ()=default
Destruct Reader object using default destructor.
virtual T at (uint32_t nth) const =0
Get the value used by the index.
Detailed Description
template<typename T>
class nnfw::misc::vector::Object< T >
Class to have information of the operand for vector.
Definition at line 41 of file Object.h.
Member Typedef Documentation
Generator
template<typename T > using nnfw::misc::vector::Object< T >::Generator = std::function<T(int32_t size, int32_t offset)>
Definition at line 44 of file Object.h.
Constructor & Destructor Documentation
Object()
template<typename T > nnfw::misc::vector::Object< T >::Object (int32_t size, const Generator & gen) inline
Construct Object object with size of vector and set value used by Generator.
Parameters
[in] size The size of vector
[in] gen A function to set values of operand tensor
Definition at line 52 of file Object.h.
                                             : _size{size}
  {
    _value.resize(_size);
    for (int32_t offset = 0; offset < size; ++offset)
    {
      _value.at(offset) = gen(size, offset);
    }
  }
References offset(), and nnfw::misc::vector::Object< T >::size().
Member Function Documentation
at()
template<typename T > T nnfw::misc::vector::Object< T >::at (uint32_t nth) const inline override virtual
Get the value used by index.
Parameters
[in] nth The vector index
Returns
The value at the offset
Implements nnfw::misc::vector::Reader< T >.
Definition at line 75 of file Object.h.
{ return _value.at(nth); }
size()
template<typename T > int32_t nnfw::misc::vector::Object< T >::size (void) const inline
Get size of vector.
Returns
Size of vector
Definition at line 67 of file Object.h.
{ return _size; }
Referenced by nnfw::misc::vector::Object< T >::Object().
The documentation for this class was generated from the following file:
runtime/libs/misc/include/misc/vector/Object.h