ONE - On-device Neural Engine: arm_compute::CLOneHotKernel Class Reference
arm_compute::CLOneHotKernel Class Reference
#include <CLOneHotKernel.h>
Public Member Functions
CLOneHotKernel ()
CLOneHotKernel (const CLOneHotKernel &)=delete
CLOneHotKernel & operator= (const CLOneHotKernel &)=delete
CLOneHotKernel (CLOneHotKernel &&)=default
CLOneHotKernel & operator= (CLOneHotKernel &&)=default
~CLOneHotKernel ()=default
void configure (const ICLTensor *indices, const ICLTensor *on_value, const ICLTensor *off_value, ICLTensor *output, int depth, int axis=-1)
void configure (const ICLTensor *indices, const ICLTensor *on_value, ICLTensor *output, int depth, int axis=-1)
void run (const Window &window, cl::CommandQueue &queue) override
Static Public Member Functions
static Status validate (const ITensorInfo *indices, const ITensorInfo *on_value, const ITensorInfo *off_value, const ITensorInfo *output, int depth, int axis=-1)
static Status validate (const ITensorInfo *indices, const ITensorInfo *on_value, const ITensorInfo *output, int depth, int axis=-1)
Detailed Description
Interface for the kernel to perform one-hot encoding
Definition at line 48 of file CLOneHotKernel.h.
Constructor & Destructor Documentation
CLOneHotKernel() [1/3]
arm_compute::CLOneHotKernel::CLOneHotKernel ()
Default constructor
Definition at line 94 of file CLOneHotKernel.cpp.
  : _indices(nullptr), _on_value(nullptr), _off_value(nullptr), _output(nullptr),
    _is_off_value_memset(false)
{
}
CLOneHotKernel() [2/3]
arm_compute::CLOneHotKernel::CLOneHotKernel (const CLOneHotKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
CLOneHotKernel() [3/3]
arm_compute::CLOneHotKernel::CLOneHotKernel (CLOneHotKernel &&) default
Allow instances of this class to be moved
~CLOneHotKernel()
arm_compute::CLOneHotKernel::~CLOneHotKernel () default
Default destructor
References validate().
Member Function Documentation
configure() [1/2]
void arm_compute::CLOneHotKernel::configure (const ICLTensor * indices, const ICLTensor * on_value, const ICLTensor * off_value, ICLTensor * output, int depth, int axis = -1)
Initialise the kernel's inputs and output
Parameters
[in] indices Indices tensor. Supported tensor rank: up to 3. Must be one of the following types: U32/S32
[in] on_value On value tensor. Supported tensor rank: only 1. Data type supported: U8/S8/U16/S16/F16/U32/S32/F32
[in] off_value Off value tensor. Supported tensor rank: only 1. Data type supported: Same as on_value
[out] output Destination tensor. Data type supported: Same as on_value
[in] depth The depth of the one hot dimension.
[in] axis (Optional) The axis to fill. Negative values wrap around. Defaults to -1. value must be in range [-indices.rank , indices.rank)
Definition at line 99 of file CLOneHotKernel.cpp.
{
  _is_off_value_memset = false;
  ARM_COMPUTE_ERROR_ON_NULLPTR(indices, on_value, off_value, output);
  ARM_COMPUTE_ERROR_ON_NULLPTR(off_value->info());
  ARM_COMPUTE_ERROR_ON(off_value->info()->tensor_shape().total_size() != 1);
  ARM_COMPUTE_ERROR_ON_MISMATCHING_DATA_TYPES(on_value, off_value);
  _off_value = off_value;
  configure_common(indices, on_value, output, depth, axis);
}
Referenced by arm_compute::CLOneHot::configure().
configure() [2/2]
void arm_compute::CLOneHotKernel::configure (const ICLTensor * indices, const ICLTensor * on_value, ICLTensor * output, int depth, int axis = -1)
Initialise the kernel's inputs and output already initialized to off_value
Parameters
[in] indices Indices tensor. Supported tensor rank: up to 3. Must be one of the following types: U32/S32
[in] on_value On value tensor. Supported tensor rank: only 1. Data type supported: U8/S8/U16/S16/F16/U32/S32/F32
[out] output Destination tensor. Data type supported: Same as on_value
[in] depth The depth of the one hot dimension.
[in] axis (Optional) The axis to fill. Negative values wrap around. Defaults to -1. value must be in range [-indices.rank , indices.rank)
Definition at line 110 of file CLOneHotKernel.cpp.
{
  _is_off_value_memset = true;
  ARM_COMPUTE_ERROR_ON_NULLPTR(indices, on_value, output);
  configure_common(indices, on_value, output, depth, axis);
}
operator=() [1/2]
CLOneHotKernel & arm_compute::CLOneHotKernel::operator= (CLOneHotKernel &&) default
Allow instances of this class to be moved
operator=() [2/2]
CLOneHotKernel & arm_compute::CLOneHotKernel::operator= (const CLOneHotKernel &) delete
Prevent instances of this class from being copied (As this class contains pointers)
run()
void arm_compute::CLOneHotKernel::run (const Window & window, cl::CommandQueue & queue) override
Definition at line 173 of file CLOneHotKernel.cpp.
{
  ARM_COMPUTE_ERROR_ON_UNCONFIGURED_KERNEL(this);
  ARM_COMPUTE_ERROR_ON_INVALID_SUBWINDOW(IKernel::window(), window);
  Window window_collapsed = window.collapse_if_possible(ICLKernel::window(), Window::DimZ);
  unsigned int idx = 0;
  add_3D_tensor_argument(idx, _indices, window_collapsed);
  add_1D_tensor_argument(idx, _on_value, window_collapsed);
  if (!_is_off_value_memset)
  {
    add_1D_tensor_argument(idx, _off_value, window_collapsed);
  }
  add_4D_tensor_argument(idx, _output, window_collapsed);
  enqueue(queue, *this, window_collapsed, lws_hint());
}
validate() [1/2]
Status arm_compute::CLOneHotKernel::validate (const ITensorInfo * indices, const ITensorInfo * on_value, const ITensorInfo * off_value, const ITensorInfo * output, int depth, int axis = -1) static
Static function to check if given info will lead to a valid configuration of CLOneHotKernel
Parameters
[in] indices Indices tensor. Supported tensor rank: up to 3. Must be one of the following types: U32/S32
[in] on_value On value tensor. Supported tensor rank: only 1. Data type supported: U8/S8/U16/S16/F16/U32/S32/F32
[in] off_value Off value tensor. Supported tensor rank: only 1. Data type supported: Same as on_value
[in] output Destination tensor. Data type supported: Same as on_value
[in] depth The depth of the one hot dimension.
[in] axis (Optional) The axis to fill. Negative values wrap around. Defaults to -1. value must be in range [-indices.rank , indices.rank)
Returns
a status
Definition at line 149 of file CLOneHotKernel.cpp.
{
  ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(off_value);
  ARM_COMPUTE_RETURN_ERROR_ON(off_value->tensor_shape().total_size() != 1);
  ARM_COMPUTE_RETURN_ERROR_ON_MISMATCHING_DATA_TYPES(on_value, off_value);
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(indices, on_value, output, depth, axis));
  ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(indices->clone().get(),
                                                            on_value->clone().get(),
                                                            output->clone().get(), depth, axis)
                                .first);
  return Status{};
}
Referenced by arm_compute::CLOneHot::validate(), and ~CLOneHotKernel().
validate() [2/2]
Status arm_compute::CLOneHotKernel::validate (const ITensorInfo * indices, const ITensorInfo * on_value, const ITensorInfo * output, int depth, int axis = -1) static
Static function to check if given info will lead to a valid configuration of CLOneHotKernel without off_value
Parameters
[in] indices Indices tensor. Supported tensor rank: up to 3. Must be one of the following types: U32/S32
[in] on_value On value tensor. Supported tensor rank: only 1. Data type supported: U8/S8/U16/S16/F16/U32/S32/F32
[in] output Destination tensor. Data type supported: Same as on_value
[in] depth The depth of the one hot dimension.
[in] axis (Optional) The axis to fill. Negative values wrap around. Defaults to -1. value must be in range [-indices.rank , indices.rank)
Returns
a status
Definition at line 163 of file CLOneHotKernel.cpp.
{
  ARM_COMPUTE_RETURN_ON_ERROR(validate_arguments(indices, on_value, output, depth, axis));
  ARM_COMPUTE_RETURN_ON_ERROR(validate_and_configure_window(indices->clone().get(),
                                                            on_value->clone().get(),
                                                            output->clone().get(), depth, axis)
                                .first);
  return Status{};
}
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/core/CL/kernels/CLOneHotKernel.h
compute/ARMComputeEx/src/core/CL/kernels/CLOneHotKernel.cpp