ONE - On-device Neural Engine: onert::compiler::train::LoweredTrainableGraph Class Reference
onert::compiler::train::LoweredTrainableGraph Class Reference
Class that contains lowering information on graph. In addition, after lowering, operands in graph will be set to "dynamic" if the shape of output of an operation cannot be decided at compilation time.
#include <LoweredTrainableGraph.h>
Public Member Functions
LoweredTrainableGraph (ir::train::TrainableGraph &graph, const compiler::CompilerOptions &options)
ir::Graph & graph () override
const ir::Graph & graph () const override
ir::train::TrainableGraph & trainable_graph ()
const ir::train::TrainableGraph & trainable_graph () const
const compiler::GraphLowerInfo & lower_info () const override
compiler::GraphLowerInfo & lower_info () override
std::shared_ptr< ir::OperationIndexMap< int64_t > > indexed_ranks ()
void setHasDynamicTensor (ir::OperationIndex, bool has_dynamic) override
bool getHasDynamicTensor (ir::OperationIndex) const override
Public Member Functions inherited from onert::compiler::ILoweredGraph
virtual ~ILoweredGraph ()=default
virtual ir::Graph & graph ()=0
virtual const ir::Graph & graph () const =0
virtual const compiler::GraphLowerInfo & lower_info () const =0
virtual compiler::GraphLowerInfo & lower_info ()=0
virtual void setHasDynamicTensor (ir::OperationIndex ind, bool val)=0
virtual bool getHasDynamicTensor (ir::OperationIndex ind) const =0
Detailed Description
Class that contains lowering information on graph. In addition, after lowering, operands in graph will be set to "dynamic" if the shape of output of an operation cannot be decided at compilation time.
Definition at line 39 of file LoweredTrainableGraph.h.
Constructor & Destructor Documentation
LoweredTrainableGraph()
onert::compiler::train::LoweredTrainableGraph::LoweredTrainableGraph (ir::train::TrainableGraph & graph, const compiler::CompilerOptions & options)
Definition at line 46 of file LoweredTrainableGraph.cc.
  : _trainable_graph{graph}
{
  lowerGraph(options);
}
Member Function Documentation
getHasDynamicTensor()
bool onert::compiler::train::LoweredTrainableGraph::getHasDynamicTensor (ir::OperationIndex) const inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 58 of file LoweredTrainableGraph.h.
{ return false; }
graph() [1/2]
const ir::Graph & onert::compiler::train::LoweredTrainableGraph::graph () const inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 46 of file LoweredTrainableGraph.h.
{ return _trainable_graph.graph(); }
References onert::ir::train::TrainableGraph::graph().
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
graph() [2/2]
ir::Graph & onert::compiler::train::LoweredTrainableGraph::graph () inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 45 of file LoweredTrainableGraph.h.
{ return const_cast<ir::Graph &>(_trainable_graph.graph()); }
References onert::ir::train::TrainableGraph::graph().
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::compiler::train::StaticDerivativeShapeInferer::infer(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
indexed_ranks()
std::shared_ptr< ir::OperationIndexMap< int64_t > > onert::compiler::train::LoweredTrainableGraph::indexed_ranks () inline
Definition at line 51 of file LoweredTrainableGraph.h.
{ return _indexed_ranks; }
lower_info() [1/2]
const compiler::GraphLowerInfo & onert::compiler::train::LoweredTrainableGraph::lower_info () const inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 49 of file LoweredTrainableGraph.h.
{ return _lower_info_map; }
lower_info() [2/2]
compiler::GraphLowerInfo & onert::compiler::train::LoweredTrainableGraph::lower_info () inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 50 of file LoweredTrainableGraph.h.
{ return _lower_info_map; }
setHasDynamicTensor()
void onert::compiler::train::LoweredTrainableGraph::setHasDynamicTensor (ir::OperationIndex , bool has_dynamic) inline override virtual
Implements onert::compiler::ILoweredGraph.
Definition at line 53 of file LoweredTrainableGraph.h.
  {
    if (has_dynamic)
      throw std::runtime_error("LoweredTrainableGraph does not support dynamic tensors yet");
  }
trainable_graph() [1/2]
ir::train::TrainableGraph & onert::compiler::train::LoweredTrainableGraph::trainable_graph () inline
Definition at line 47 of file LoweredTrainableGraph.h.
{ return _trainable_graph; }
Referenced by onert::compiler::train::StaticDerivativeShapeInferer::infer().
trainable_graph() [2/2]
const ir::train::TrainableGraph & onert::compiler::train::LoweredTrainableGraph::trainable_graph () const inline
Definition at line 48 of file LoweredTrainableGraph.h.
{ return _trainable_graph; }
The documentation for this class was generated from the following files:
runtime/onert/core/include/compiler/train/LoweredTrainableGraph.h
runtime/onert/core/src/compiler/train/LoweredTrainableGraph.cc