ONE - On-device Neural Engine: tflimport::AvgPool2DGraphBuilder Class Reference
tflimport::AvgPool2DGraphBuilder Class Reference
GraphBuilder for AvgPool2D operator.
#include <AveragePool2D.h>
Public Member Functions
bool validate (const tflite::Operator *op) const override
void build (const tflite::Operator *op, GraphBuilderContext *) const override
Public Member Functions inherited from tflimport::GraphBuilder
virtual bool validate (const tflite::Operator *) const
virtual void build (const tflite::Operator *op, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for AvgPool2D operator.
Definition at line 30 of file AveragePool2D.h.
Member Function Documentation
build()
void tflimport::AvgPool2DGraphBuilder::build (const tflite::Operator * op, GraphBuilderContext * context) const override virtual
Implements tflimport::GraphBuilder.
Definition at line 52 of file AveragePool2D.cpp.
{
  assert(context != nullptr); // check if init(..) is called
  coco::Module *m = context->m();
  coco::Block *blk = context->block();
  TensorContext &tensor_context = context->tensor();
  TensorBags &bags = context->bags();
  IndexVector opinputs = as_index_vector(op->inputs());
  IndexVector opoutputs = as_index_vector(op->outputs());
  // these are fixed in tflite
  // input index 0 : input feature
  // output index 0 : output feature
  assert(opinputs.size() == 1);
  assert(opoutputs.size() == 1);
  int ifm_idx = opinputs.at(0);
  int ofm_idx = opoutputs.at(0);
  const tensor::Shape &ifm_shape = tensor_context.shape(ifm_idx);
  const tensor::Shape &ofm_shape = tensor_context.shape(ofm_idx);
  // Create an object for an input feature map
  coco::FeatureObject *ifm_obj = m->entity()->object()->create<coco::FeatureObject>();
  coco::Bag *ifm_bag = bags.bag(ifm_idx);
  ifm_obj->bag(ifm_bag);
  ifm_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(ifm_shape)));
  // Create an object for an output feature map
  coco::FeatureObject *ofm_obj = m->entity()->object()->create<coco::FeatureObject>();
  coco::Bag *ofm_bag = bags.bag(ofm_idx);
  ofm_obj->bag(ofm_bag);
  ofm_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(ofm_shape)));
  // Create a Load op
  auto coco_load = op_builder(m).load(ifm_obj).pop();
  // Create a AvgPool2D
  auto coco_avgpool2d = m->entity()->op()->create<coco::AvgPool2D>();
  auto *params = op->builtin_options_as_Pool2DOptions();
  // NOTE For Tensorflow lite, PaddingExcluded is needed
  coco_avgpool2d->divisor(coco::AvgPool2D::Divisor::PaddingExcluded);
  coco_avgpool2d->window()->height(params->filter_height());
  coco_avgpool2d->window()->width(params->filter_width());
  coco_avgpool2d->stride()->vertical(params->stride_h());
  coco_avgpool2d->stride()->horizontal(params->stride_w());
  coco::Padding2D padding =
    pool2D_padding(params, ifm_shape, params->filter_width(), params->filter_height());
  coco_avgpool2d->pad()->top(padding.top());
  coco_avgpool2d->pad()->bottom(padding.bottom());
  coco_avgpool2d->pad()->left(padding.left());
  coco_avgpool2d->pad()->right(padding.right());
  // Link ops
  coco_avgpool2d->arg(coco_load);
  // Create an Eval instruction
  auto ins = instr_builder(m).eval(ofm_obj, coco_avgpool2d);
  // Append the instruction to the block
  blk->instr()->append(ins);
  // TODO activation, e.g., relu
  assert(params->fused_activation_function() ==
         tflite::ActivationFunctionType::ActivationFunctionType_NONE);
}
References coco::DLinkedList< Child, Parent >::Head::append(), morph::tflite::as_feature_shape(), tflimport::as_index_vector(), tflimport::TensorBags::bag(), coco::Object::bag(), tflimport::GraphBuilderContext::bags(), tflimport::GraphBuilderContext::block(), coco::Padding2D::bottom(), coco::FeatureLayouts::BHWC::create(), coco::AvgPool2D::divisor(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), coco::FeatureObject::layout(), coco::Padding2D::left(), OpBuilder::load(), tflimport::GraphBuilderContext::m(), m, op_builder(), coco::AvgPool2D::PaddingExcluded, tflimport::pool2D_padding(), OpBuilder::pop(), coco::Padding2D::right(), tflimport::TensorContext::shape(), tflimport::GraphBuilderContext::tensor(), and coco::Padding2D::top().
validate()
bool tflimport::AvgPool2DGraphBuilder::validate (const tflite::Operator *) const override virtual
TODO Declare "validate" method as a pure virtual method
Q: Is it possible to validate T/F Lite model only with this interface?
Reimplemented from tflimport::GraphBuilder.
Definition at line 40 of file AveragePool2D.cpp.
{
  auto const options = op->builtin_options_as_Pool2DOptions();
  if ((options->stride_h() == 0) || (options->stride_w() == 0))
  {
    return false;
  }
  return true;
}
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Op/AveragePool2D.h
compiler/enco/frontend/tflite/src/Op/AveragePool2D.cpp