ONE - On-device Neural Engine: onert::backend::train::ops::SoftMaxLayer Class Reference
onert::backend::train::ops::SoftMaxLayer Class Reference
#include <SoftMaxLayer.h>
Public Member Functions
SoftMaxLayer ()
void configure (const IPortableTensor *input, const float beta, IPortableTensor *output, IPortableTensor *back_prop_input, const IPortableTensor *back_prop_output)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
Public Member Functions inherited from onert::backend::cpu::ops::SoftMaxLayer
SoftMaxLayer ()
void softmaxFloat32 ()
template<typename T >
void softmaxQuant8 ()
void configure (const IPortableTensor *input, const float beta, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::SoftMaxLayer
const IPortableTensor * _input
IPortableTensor * _output
Detailed Description
Definition at line 34 of file SoftMaxLayer.h.
Constructor & Destructor Documentation
SoftMaxLayer()
onert::backend::train::ops::SoftMaxLayer::SoftMaxLayer ()
Definition at line 32 of file SoftMaxLayer.cc.
  : cpu::ops::SoftMaxLayer(), _back_prop_input{nullptr}, _back_prop_output{nullptr}
{
  // DO NOTHING
}
Member Function Documentation
backward()
void onert::backend::train::ops::SoftMaxLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 50 of file SoftMaxLayer.cc.
{
  assert(_back_prop_output->data_type() == _input->data_type());
  switch (_back_prop_output->data_type())
  {
    case OperandType::FLOAT32:
    {
      nnfw::cker::train::SoftMaxGrad(
        getShape(_output), getBuffer<float>(_output), getShape(_back_prop_output),
        getBuffer<float>(_back_prop_output), getShape(_back_prop_input),
        getBuffer<float>(_back_prop_input));
      break;
    }
    default:
      throw std::runtime_error("train SoftMaxLayer: unsupported data type");
  }
}
References onert::backend::cpu::ops::SoftMaxLayer::_input, onert::backend::cpu::ops::SoftMaxLayer::_output, onert::backend::ITensor::data_type(), and nnfw::cker::train::SoftMaxGrad().
configure()
void onert::backend::train::ops::SoftMaxLayer::configure (const IPortableTensor * input, const float beta, IPortableTensor * output, IPortableTensor * back_prop_input, const IPortableTensor * back_prop_output)
Definition at line 38 of file SoftMaxLayer.cc.
{
  cpu::ops::SoftMaxLayer::configure(input, beta, output);
  _back_prop_input = back_prop_input;
  _back_prop_output = back_prop_output;
}
References onert::backend::cpu::ops::SoftMaxLayer::configure().
forward()
void onert::backend::train::ops::SoftMaxLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 48 of file SoftMaxLayer.cc.
{ cpu::ops::SoftMaxLayer::run(); }
References onert::backend::cpu::ops::SoftMaxLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/SoftMaxLayer.h
runtime/onert/backend/train/ops/SoftMaxLayer.cc