ONE - On-device Neural Engine: coco::BlockManager Class Reference
coco::BlockManager Class Reference final
#include <BlockManager.h>
Public Member Functions
BlockManager (Module *m=nullptr)
Block * create (void)
void destroy (Block *)
Free 'Block' object.
Public Member Functions inherited from coco::PtrManager< Block >
uint32_t size (void) const
Return the number of managed objects.
Block * at (uint32_t n) const
Public Member Functions inherited from coco::EntityBuilder
virtual ~EntityBuilder ()=default
Additional Inherited Members
Protected Member Functions inherited from coco::PtrManager< Block >
U * take (std::unique_ptr< U > &&o)
std::unique_ptr< Block > release (Block *ptr)
Protected Member Functions inherited from coco::EntityBuilder
Module * module (void) const
void module (Module *m)
void modulize (Entity *entity) const
Detailed Description
Definition at line 28 of file BlockManager.h.
Constructor & Destructor Documentation
BlockManager()
coco::BlockManager::BlockManager (Module * m = nullptr) inline
Definition at line 31 of file BlockManager.h.
{ module(m); }
References m, and coco::EntityBuilder::module().
Member Function Documentation
create()
Block * coco::BlockManager::create (void)
Definition at line 25 of file BlockManager.cpp.
{
  auto blk = std::make_unique<Block>();
  modulize(blk.get());
  return take(std::move(blk));
}
References coco::EntityBuilder::modulize(), and coco::PtrManager< Block >::take().
Referenced by Frontend::load().
destroy()
void coco::BlockManager::destroy (Block * blk)
Free 'Block' object.
NOTE Block SHOULD be detached from any list before it is destructed
Definition at line 32 of file BlockManager.cpp.
{
  assert(blk->parent() == nullptr);
  assert(blk->prev() == nullptr);
  assert(blk->next() == nullptr);
  release(blk);
}
References coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::parent(), coco::DLinkedList< Child, Parent >::Node::prev(), and coco::PtrManager< Block >::release().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/BlockManager.h
compiler/coco/core/src/IR/BlockManager.cpp