ONE - On-device Neural Engine: onert::backend::train::TensorRegistry Class Reference
onert::backend::train::TensorRegistry Class Reference
#include <TensorRegistry.h>
Public Member Functions
ITensor * getITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &ind) override
Returns pointer of ITensor among native tensors.
IPortableTensor * getPortableTensor (const ir::OperandIndex &ind)
Tensor * getNonConstTensor (const ir::OperandIndex &ind)
TrainableTensor * getTrainableTensor (const ir::OperandIndex &ind)
bool setMigrantTensor (const ir::OperandIndex &ind, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void setNonConstTensor (const ir::OperandIndex &ind, std::unique_ptr< Tensor > tensor)
void setTrainableTensor (const ir::OperandIndex &ind, std::unique_ptr< TrainableTensor > tensor)
const ir::OperandIndexMap< std::unique_ptr< TrainableTensor > > & trainable_tensors ()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & nonconst_tensors ()
Public Member Functions inherited from onert::backend::train::PortableTensorRegistryTemplate< Tensor >
ITensor * getITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native and migrant tensors.
ITensor * getNativeITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor among native tensors.
ITensor * getDerivativeITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for derivative.
ITensor * getGradientITensor (const ir::OperandIndex &index) override
Returns pointer of ITensor for gradient.
IPortableTensor * getPortableTensor (const ir::OperandIndex &index)
Tensor * getNonConstTensor (const ir::OperandIndex &index)
TrainableTensor * getTrainableTensor (const ir::OperandIndex &index)
DerivativeTensor * getDerivativeTensor (const ir::OperandIndex &index)
GradientTensor * getGradientTensor (const ir::OperandIndex &index)
TrainingTensors getTrainingTensors (const ir::OperandIndex &index)
bool setMigrantTensor (const ir::OperandIndex &index, IPortableTensor *tensor) override
Set the Migrant Tensor which are from other backends.
void setNonConstTensor (const ir::OperandIndex &index, std::unique_ptr< Tensor > tensor)
void setTrainableTensor (const ir::OperandIndex &index, std::unique_ptr< TrainableTensor > tensor)
void setDerivativeTensor (const ir::OperandIndex &index, std::unique_ptr< DerivativeTensor > tensor)
void setGradientTensor (const ir::OperandIndex &index, std::unique_ptr< GradientTensor > tensor)
const ir::OperandIndexMap< std::unique_ptr< TrainableTensor > > & trainable_tensors ()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & nonconst_tensors ()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & derivative_tensors ()
const ir::OperandIndexMap< std::unique_ptr< GradientTensor > > & gradient_tensors ()
virtual ITensor * getDerivativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for derivative.
virtual ITensor * getGradientITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor for gradient.
Public Member Functions inherited from onert::backend::ITensorRegistry
virtual ~ITensorRegistry ()=default
Deconstruct itself.
virtual ITensor * getITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native and migrant tensors.
virtual ITensor * getNativeITensor (const ir::OperandIndex &)=0
Returns pointer of ITensor among native tensors.
virtual bool setMigrantTensor (const ir::OperandIndex &, IPortableTensor *)
Set the Migrant Tensor which are from other backends.
Additional Inherited Members
Public Types inherited from onert::backend::train::PortableTensorRegistryTemplate< Tensor >
using TrainingTensors = std::tuple< TrainableTensor *, GradientTensor * >
Detailed Description
Definition at line 31 of file TensorRegistry.h.
Member Function Documentation
getITensor()
ITensor * onert::backend::train::TensorRegistry::getITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native and migrant tensors.
Native Tensor is a tensor that is managed by this backend Migrant Tensor is a tensor that is imported from another backend
Note
Return tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 34 of file TensorRegistry.h.
  {
    auto tensor = _trainable.find(ind);
    if (tensor != _trainable.end())
      return tensor->second.get();
    return PortableTensorRegistryTemplate<Tensor>::getITensor(ind);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getITensor().
getNativeITensor()
ITensor * onert::backend::train::TensorRegistry::getNativeITensor (const ir::OperandIndex &) inline override virtual
Returns pointer of ITensor among native tensors.
Unlike getITensor , this function only searches from native tensors
Note
Returned tensor cannot be used longer than dynamic tensor manager
Implements onert::backend::ITensorRegistry.
Definition at line 43 of file TensorRegistry.h.
  {
    ITensor *tensor = getTrainableTensor(ind);
    if (tensor == nullptr)
      tensor = getNonConstTensor(ind);
    return tensor;
  }
References getNonConstTensor(), and getTrainableTensor().
getNonConstTensor()
Tensor * onert::backend::train::TensorRegistry::getNonConstTensor (const ir::OperandIndex & ind) inline
Definition at line 62 of file TensorRegistry.h.
  {
    return PortableTensorRegistryTemplate<Tensor>::getNativeTensor(ind);
  }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::getNativeTensor().
Referenced by getNativeITensor().
getPortableTensor()
IPortableTensor * onert::backend::train::TensorRegistry::getPortableTensor (const ir::OperandIndex & ind) inline
Definition at line 51 of file TensorRegistry.h.
  {
    auto tensor = _trainable.find(ind);
    if (tensor != _trainable.end())
    {
      if (tensor->second)
        return tensor->second.get();
    }
    return PortableTensorRegistryTemplate<Tensor>::getPortableTensor(ind);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::getPortableTensor().
getTrainableTensor()
TrainableTensor * onert::backend::train::TensorRegistry::getTrainableTensor (const ir::OperandIndex & ind) inline
Definition at line 67 of file TensorRegistry.h.
  {
    auto tensor = _trainable.find(ind);
    if (tensor != _trainable.end())
      return tensor->second.get();
    return nullptr;
  }
Referenced by getNativeITensor().
nonconst_tensors()
const ir::OperandIndexMap< std::unique_ptr< Tensor > > & onert::backend::train::TensorRegistry::nonconst_tensors () inline
Definition at line 117 of file TensorRegistry.h.
  {
    return PortableTensorRegistryTemplate<Tensor>::native_tensors();
  }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::native_tensors().
setMigrantTensor()
bool onert::backend::train::TensorRegistry::setMigrantTensor (const ir::OperandIndex & , IPortableTensor *) inline override virtual
Set the Migrant Tensor which are from other backends.
Returns
true if supported
false if not supported
Reimplemented from onert::backend::ITensorRegistry.
Definition at line 76 of file TensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _trainable.find(ind);
    if (itr != _trainable.end())
      throw std::runtime_error{
        "Tried to set a migrant tensor but a trainable tensor already exists."};
    return PortableTensorRegistryTemplate<Tensor>::setMigrantTensor(ind, tensor);
  }
References onert::backend::train::PortableTensorRegistryTemplate< Tensor, TrainableTensor, DerivativeTensor, GradientTensor >::setMigrantTensor().
setNonConstTensor()
void onert::backend::train::TensorRegistry::setNonConstTensor (const ir::OperandIndex & ind, std::unique_ptr< Tensor > tensor) inline
Definition at line 87 of file TensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _trainable.find(ind);
    if (itr != _trainable.end())
      throw std::runtime_error{
        "Tried to set a non const tensor but a trainable tensor already exists."};
    PortableTensorRegistryTemplate<Tensor>::setNativeTensor(ind, std::move(tensor));
  }
References onert::backend::PortableTensorRegistryTemplate< T_Tensor >::setNativeTensor().
setTrainableTensor()
void onert::backend::train::TensorRegistry::setTrainableTensor (const ir::OperandIndex & ind, std::unique_ptr< TrainableTensor > tensor) inline
Definition at line 98 of file TensorRegistry.h.
  {
    assert(tensor != nullptr);
    auto itr = _trainable.find(ind);
    if (itr != _trainable.end())
      throw std::runtime_error{
        "Tried to set a trainable tensor but a trainable tensor already exists."};
    if (PortableTensorRegistryTemplate<Tensor>::getITensor(ind) != nullptr)
      throw std::runtime_error{
        "Tried to set a trainable tensor but another tensor already exists."};
    _trainable[ind] = std::move(tensor);
  }
trainable_tensors()
const ir::OperandIndexMap< std::unique_ptr< TrainableTensor > > & onert::backend::train::TensorRegistry::trainable_tensors () inline
Definition at line 113 of file TensorRegistry.h.
  {
    return _trainable;
  }
The documentation for this class was generated from the following file:
runtime/onert/backend/train/TensorRegistry.h