ONE - On-device Neural Engine: locoex::CircleDialect Class Reference
locoex::CircleDialect Class Reference final
#include <CircleDialect.h>
Public Member Functions
CircleDialect (const CircleDialect &)=delete
CircleDialect (CircleDialect &&)=delete
Public Member Functions inherited from loco::Dialect
virtual ~Dialect ()=default
template<typename ConcreteService >
ConcreteService * service (void) const
Static Public Member Functions
static loco::Dialect * get (void)
Additional Inherited Members
Protected Member Functions inherited from loco::Dialect
template<typename ConcreteService >
void service (std::unique_ptr< ConcreteService > &&s)
Detailed Description
Definition at line 25 of file CircleDialect.h.
Constructor & Destructor Documentation
CircleDialect() [1/2]
locoex::CircleDialect::CircleDialect (const CircleDialect &) delete
CircleDialect() [2/2]
locoex::CircleDialect::CircleDialect (CircleDialect &&) delete
Member Function Documentation
get()
loco::Dialect * locoex::CircleDialect::get (void) static
Definition at line 22 of file CircleDialect.cpp.
{
  static CircleDialect d;
  return &d;
}
Referenced by locoex::CircleNode::dialect(), locoex::CircleTypeInferenceRule::infer(), locoex::CircleShapeInferenceRule::infer(), locoex::CircleShapeInferenceRule::recognize(), locoex::CircleTypeInferenceRule::recognize(), exo::ShapeInferencePass::run(), and exo::TypeInferencePass::run().
The documentation for this class was generated from the following files:
compiler/exo/src/Dialect/IR/CircleDialect.h
compiler/exo/src/Dialect/IR/CircleDialect.cpp