ONE - On-device Neural Engine: HD5ImportAction Class Reference
HD5ImportAction Class Reference final
Public Member Functions
HD5ImportAction (const std::string &path)
void run (TensorContext &ctx) override
Public Member Functions inherited from nnkit::Action
virtual ~Action ()=default
virtual void run (TensorContext &ctx)=0
Detailed Description
Definition at line 30 of file Import.cpp.
Constructor & Destructor Documentation
HD5ImportAction()
HD5ImportAction::HD5ImportAction (const std::string & path) inline
Definition at line 33 of file Import.cpp.
                                         : _file{path, H5F_ACC_RDONLY}
  {
    _value_grp = _file.openGroup(value_grpname());
  }
References value_grpname().
Member Function Documentation
run()
void HD5ImportAction::run (TensorContext & ctx) inline override virtual
Implements nnkit::Action.
Definition at line 39 of file Import.cpp.
  {
    for (uint32_t n = 0; n < ctx.size(); ++n)
    {
      using nncc::core::ADT::tensor::Accessor;
      auto fn = [this](const TensorContext &ctx, uint32_t n, Accessor<float> &t) {
        const auto name = ctx.name(n);
        auto dataset = _value_grp.openDataSet(value_filename(n));
        // TODO Support non-float tensors
        assert(dataset.getDataType() == H5::PredType::IEEE_F32BE);
        // TODO Check whether shape is consistent
        const auto shape = ctx.shape(n);
        std::vector<float> buffer;
        using nncc::core::ADT::tensor::num_elements;
        buffer.resize(num_elements(shape));
        dataset.read(buffer.data(), H5::PredType::NATIVE_FLOAT);
        using nncc::core::ADT::tensor::Index;
        using nncc::core::ADT::tensor::IndexEnumerator;
        using nncc::core::ADT::tensor::LexicalLayout;
        LexicalLayout layout{};
        for (IndexEnumerator e{shape}; e.valid(); e.advance())
        {
          auto i = e.current();
          t.at(i) = buffer[layout.offset(shape, i)];
        }
        // TODO Check name
      };
      try
      {
        ctx.getMutableFloatTensor(n, fn);
      }
      catch (const H5::FileIException &)
      {
        // Skip if data is not present in HDF5 file
      }
    }
  }
References nnkit::TensorContext::getMutableFloatTensor(), nnkit::TensorContext::name(), nncc::core::ADT::tensor::num_elements(), nnkit::TensorContext::shape(), nnkit::TensorContext::size(), and value_filename().
The documentation for this class was generated from the following file:
compiler/nnkit/actions/HDF5/Import.cpp