ONE - On-device Neural Engine: onert::compiler::CompilerOptions Class Reference
onert::compiler::CompilerOptions Class Reference
#include <CompilerOptions.h>
Public Member Functions
void enableToFp16 ()
Allow to compute float32 using float16 data type.
void forceInternalOptions ()
Force default values of CompilerOptions for correct compilations.
void verboseOptions ()
Print option value.
Static Public Member Functions
static std::unique_ptr< CompilerOptions > fromGlobalConfig ()
Set default values for CompilerOptions.
Data Fields
std::vector< std::string > backend_list
std::string trace_filepath
int graph_dump_level
std::string executor
ManualSchedulerOptions manual_scheduler_options
bool he_scheduler
bool he_profiling_mode
bool disable_compile
bool fp16_enable
Detailed Description
Definition at line 44 of file CompilerOptions.h.
Member Function Documentation
enableToFp16()
void onert::compiler::CompilerOptions::enableToFp16 () inline
Allow to compute float32 using float16 data type.
Definition at line 59 of file CompilerOptions.h.
{ fp16_enable = true; }
References fp16_enable.
forceInternalOptions()
void onert::compiler::CompilerOptions::forceInternalOptions ()
Force default values of CompilerOptions for correct compilations.
Note
This should be called after CompilerOptions setting is finished to prevent value overwriting
Definition at line 111 of file CompilerOptions.cc.
{
  // Set control flow backend for control flow operators
  auto &builtin_id = backend::builtin::Config::ID;
  manual_scheduler_options.opcode_to_backend[ir::OpCode::If] = builtin_id;
  manual_scheduler_options.opcode_to_backend[ir::OpCode::While] = builtin_id;
  manual_scheduler_options.opcode_to_backend[ir::OpCode::Permute] = builtin_id;
  // FIXME This is a workaround for bcq operations, should remove it
  manual_scheduler_options.opcode_to_backend[ir::OpCode::BCQFullyConnected] = "bcq";
  manual_scheduler_options.opcode_to_backend[ir::OpCode::BCQGather] = "bcq";
  // FIXME This is a workaround for bulk operations, should remove it
  manual_scheduler_options.opcode_to_backend[ir::OpCode::Bulk] = "trix";
}
References onert::backend::builtin::Config::ID, manual_scheduler_options, and onert::compiler::ManualSchedulerOptions::opcode_to_backend.
Referenced by onert::compiler::Compiler::compile().
fromGlobalConfig()
std::unique_ptr< CompilerOptions > onert::compiler::CompilerOptions::fromGlobalConfig () static
Set default values for CompilerOptions.
Returns
Generated CompileOption
Note
All these default values should not be fetched from Env when we stop supporting Android NNAPI.
Definition at line 74 of file CompilerOptions.cc.
{
  auto o = std::make_unique<CompilerOptions>();
  o->backend_list = nnfw::misc::split(util::getConfigString(util::config::BACKENDS), ';');
  o->trace_filepath = util::getConfigString(util::config::TRACE_FILEPATH);
  o->graph_dump_level = util::getConfigInt(util::config::GRAPH_DOT_DUMP);
  o->executor = util::getConfigString(util::config::EXECUTOR);
  o->he_scheduler = util::getConfigBool(util::config::USE_SCHEDULER);
  o->he_profiling_mode = util::getConfigBool(util::config::PROFILING_MODE);
  o->disable_compile = util::getConfigBool(util::config::DISABLE_COMPILE);
  o->fp16_enable = util::getConfigBool(util::config::FP16_ENABLE);
  {
    // Backend for all
    auto &ms_options = o->manual_scheduler_options;
    // Default value for op_backend_all is first element in the backend list
    ms_options.backend_for_all = util::getConfigString(util::config::OP_BACKEND_ALLOPS);
// Opcode to Backend
#define OP(OpName)                                                                      \
  {                                                                                     \
    const auto &backend_str = util::getConfigString(util::config::OP_BACKEND_##OpName); \
    if (!backend_str.empty())                                                           \
    {                                                                                   \
      ms_options.opcode_to_backend[ir::OpCode::OpName] = backend_str;                   \
    }                                                                                   \
  }
#include "ir/Operations.lst"
#undef OP
    // Index to Backend
    auto map_str = util::getConfigString(util::config::OP_BACKEND_MAP);
    ms_options.setBackendMap(map_str);
  }
  return o;
}
References onert::util::getConfigBool(), onert::util::getConfigInt(), onert::util::getConfigString(), and nnfw::misc::split().
Referenced by nnfw_session::load_circle_from_buffer(), nnfw_session::load_model_from_modelfile(), and nnfw_session::load_model_from_nnpackage().
verboseOptions()
void onert::compiler::CompilerOptions::verboseOptions ()
Print option value.
Definition at line 127 of file CompilerOptions.cc.
{
  VERBOSE(Compiler) << std::boolalpha << "==== Compiler Options ====" << std::endl;
  VERBOSE(Compiler) << "backend_list             : "
                    << nnfw::misc::join(backend_list.begin(), backend_list.end(), "/") << std::endl;
  VERBOSE(Compiler) << "trace_filepath           : " << trace_filepath << std::endl;
  VERBOSE(Compiler) << "graph_dump_level         : " << graph_dump_level << std::endl;
  VERBOSE(Compiler) << "executor                 : " << executor << std::endl;
  VERBOSE(Compiler) << "manual backend_for_all   : " << manual_scheduler_options.backend_for_all
                    << std::endl;
  VERBOSE(Compiler) << "manual_scheduler_options : "
                    << getOpBackends(manual_scheduler_options.opcode_to_backend) << std::endl;
  VERBOSE(Compiler) << "he_scheduler             : " << he_scheduler << std::endl;
  VERBOSE(Compiler) << "he_profiling_mode        : " << he_profiling_mode << std::endl;
  VERBOSE(Compiler) << "disable_compile          : " << disable_compile << std::endl;
  VERBOSE(Compiler) << "fp16_enable              : " << fp16_enable << std::endl
                    << std::noboolalpha;
}
References onert::compiler::ManualSchedulerOptions::backend_for_all, backend_list, disable_compile, executor, fp16_enable, graph_dump_level, he_profiling_mode, he_scheduler, nnfw::misc::join(), manual_scheduler_options, onert::compiler::ManualSchedulerOptions::opcode_to_backend, trace_filepath, and VERBOSE.
Referenced by onert::compiler::Compiler::compile().
Field Documentation
backend_list
std::vector<std::string> onert::compiler::CompilerOptions::backend_list
Definition at line 76 of file CompilerOptions.h.
Referenced by onert::compiler::ManualScheduler::schedule(), and verboseOptions().
disable_compile
bool onert::compiler::CompilerOptions::disable_compile
Definition at line 85 of file CompilerOptions.h.
Referenced by onert::compiler::Compiler::compile(), and verboseOptions().
executor
std::string onert::compiler::CompilerOptions::executor
Definition at line 81 of file CompilerOptions.h.
Referenced by onert::compiler::Compiler::compile(), and verboseOptions().
fp16_enable
bool onert::compiler::CompilerOptions::fp16_enable
Definition at line 86 of file CompilerOptions.h.
Referenced by enableToFp16(), and verboseOptions().
graph_dump_level
int onert::compiler::CompilerOptions::graph_dump_level
Definition at line 80 of file CompilerOptions.h.
Referenced by onert::compiler::Compiler::compile(), and verboseOptions().
he_profiling_mode
bool onert::compiler::CompilerOptions::he_profiling_mode
Definition at line 84 of file CompilerOptions.h.
Referenced by onert::compiler::Compiler::compile(), and verboseOptions().
he_scheduler
bool onert::compiler::CompilerOptions::he_scheduler
Definition at line 83 of file CompilerOptions.h.
Referenced by onert::compiler::Compiler::compile(), and verboseOptions().
manual_scheduler_options
ManualSchedulerOptions onert::compiler::CompilerOptions::manual_scheduler_options
Definition at line 82 of file CompilerOptions.h.
Referenced by forceInternalOptions(), onert::compiler::ManualScheduler::schedule(), and verboseOptions().
trace_filepath
std::string onert::compiler::CompilerOptions::trace_filepath
Definition at line 79 of file CompilerOptions.h.
Referenced by verboseOptions().
The documentation for this class was generated from the following files:
runtime/onert/core/include/compiler/CompilerOptions.h
runtime/onert/core/src/compiler/CompilerOptions.cc