ONE - On-device Neural Engine: exo::DomainConverter< CanonicalT, TFLT > Class Template Reference
exo::DomainConverter< CanonicalT, TFLT > Class Template Reference
Class to handle domain conversion while converting a canonical node to TFL node(s)
#include <GraphBlock.h>
Public Member Functions
template<FeatureLayout FeatureLayoutT>
TFLT * convert (CanonicalT *origin, InputHandler< CanonicalT, TFLT > &input_handler)
Performs domain conversion.
Detailed Description
template<class CanonicalT, class TFLT>
class exo::DomainConverter< CanonicalT, TFLT >
Class to handle domain conversion while converting a canonical node to TFL node(s)
Definition at line 134 of file GraphBlock.h.
Member Function Documentation
convert()
template<class CanonicalT , class TFLT > template<FeatureLayout FeatureLayoutT> TFLT * exo::DomainConverter< CanonicalT, TFLT >::convert (CanonicalT * origin, InputHandler< CanonicalT, TFLT > & input_handler)
Performs domain conversion.
if origin belong to loco::Domain::Tensor, and replace origin to a TFL node.
if origin belong to loco::Domain::Feature, insert loco::FeatureDecode for input(s) and insert loco::FeatureEncode for output. Then replace origin to a TFL node.
Returns
new TFL node; nullptr if shape of origin cannot be known
Definition at line 152 of file GraphBlock.h.
{
  static_assert(FeatureLayoutT == FeatureLayout::NHWC, "Feature layout should be NHWC");
  if (!loco::shape_known(origin))
  {
    return nullptr;
  }
  auto tfl_node = origin->graph()->nodes()->template create<TFLT>();
  // when the input is Tensor, just replace canonical node to TFL node.
  if (loco::shape_get(origin).domain() == loco::Domain::Tensor)
  {
    input_handler.handover(origin, tfl_node);
    loco::replace(origin).with(tfl_node);
    input_handler.nullify(origin);
    return tfl_node;
  }
  else if (loco::shape_get(origin).domain() == loco::Domain::Feature)
  {
    std::vector<loco::Node *> feature_decodes;
    for (auto input : input_handler.getInputsToConvert(origin))
    {
      auto dec = make_feature_decode<FeatureLayoutT>(input);
      feature_decodes.emplace_back(dec);
    }
    input_handler.set(tfl_node, feature_decodes);
    auto enc = make_feature_encode<FeatureLayoutT>(tfl_node);
    loco::replace(origin).with(enc);
    input_handler.nullify(origin);
    return tfl_node;
  }
  else
    INTERNAL_EXN_V("Unsupported loco::Domain", oops::to_uint32(loco::shape_get(origin).domain()));
}
References loco::Feature, exo::InputHandler< CanonicalT, TFLT >::getInputsToConvert(), exo::InputHandler< CanonicalT, TFLT >::handover(), INTERNAL_EXN_V, exo::NHWC, exo::InputHandler< CanonicalT, TFLT >::nullify(), loco::replace(), exo::InputHandler< CanonicalT, TFLT >::set(), loco::shape_get(), loco::shape_known(), loco::Tensor, oops::to_uint32(), and loco::Subst< SubstQualifier::Default >::with().
Referenced by exo::EltwiseMaxConverter::convert(), exo::EltwiseSqrtConverter::convert(), exo::ReluConverter::convert(), and exo::Relu6Converter::convert().
The documentation for this class was generated from the following file:
compiler/exo/src/GraphBlock.h