ONE - On-device Neural Engine: luci::CircleTypeInferencePass Class Reference
luci::CircleTypeInferencePass Class Reference
Pass to infer type of circle nodes.
#include <CircleTypeInferencePass.h>
Public Member Functions
virtual const char * name (void) const
bool run (luci::Module *m)
bool run (loco::Graph *g)
Run the pass.
virtual bool run (luci::Module *)=0
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Pass to infer type of circle nodes.
Definition at line 30 of file CircleTypeInferencePass.h.
Member Function Documentation
name()
virtual const char * luci::CircleTypeInferencePass::name (void) const inline virtual
Reimplemented from logo::Pass.
Definition at line 33 of file CircleTypeInferencePass.h.
{ return "luci::CircleTypeInferencePass"; }
run() [1/2]
bool luci::CircleTypeInferencePass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 41 of file CircleTypeInferencePass.cpp.
{
  luci::tinf::Rule type_infer_rule;
  bool changed = false;
  for (auto node : inference_candidates(g))
  {
    loco::DataType dtype;
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    if (type_infer_rule.infer(circle_node, dtype) && circle_node->dtype() != dtype)
    {
      circle_node->dtype(dtype);
      changed = true;
    }
  }
  return changed;
}
References luci::tinf::Rule::infer(), and luci::inference_candidates().
run() [2/2]
bool luci::CircleTypeInferencePass::run (luci::Module * m) virtual
Implements luci::Pass.
Definition at line 28 of file CircleTypeInferencePass.cpp.
{
  bool changed = false;
  for (size_t g = 0; g < m->size(); ++g)
  {
    if (run(m->graph(g)))
      changed = true;
  }
  return changed;
}
References m, and run().
Referenced by run().
The documentation for this class was generated from the following files:
compiler/luci/pass/include/luci/Pass/CircleTypeInferencePass.h
compiler/luci/pass/src/CircleTypeInferencePass.cpp