ONE - On-device Neural Engine: luci_interpreter::StaticRuntimeGraph Class Reference
luci_interpreter::StaticRuntimeGraph Class Reference final
#include <RuntimeGraph.h>
Public Member Functions
StaticRuntimeGraph (IMemoryManager *memory_manager)
~StaticRuntimeGraph () final
void execute () final
void configure () final
void configure_kernels () final
Public Member Functions inherited from luci_interpreter::IBaseRuntimeGraph
IBaseRuntimeGraph (IMemoryManager *memory_manager)
virtual ~IBaseRuntimeGraph ()=default
Tensor * addTensor (std::unique_ptr< Tensor > &&tensor)
AffineQuantization * addAffineQuantization (std::unique_ptr< AffineQuantization > &&quantization)
void addIntermediateTensorAffineQuantization (AffineQuantization *intermediate_tensor)
void addInputTensor (Tensor *input_tensor)
void addOutputTensor (Tensor *output_tensor)
void configureAllocations (Tensor *tensor)
const std::vector< AffineQuantization * > & getIntermediateAffineQuantizations () const
const std::vector< Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
void addKernel (std::unique_ptr< Kernel > &&kernel)
virtual void execute ()=0
virtual void configure ()=0
virtual void configure_kernels ()=0
void invalidate ()
bool isValid () const
Additional Inherited Members
Protected Attributes inherited from luci_interpreter::IBaseRuntimeGraph
IMemoryManager * _memory_manager
std::vector< std::unique_ptr< Tensor > > _tensors
std::vector< std::unique_ptr< AffineQuantization > > _affine_quantizations
std::vector< Tensor * > _input_tensors
std::vector< AffineQuantization * > _intermediate_tensors_affine_quantizations
std::vector< Tensor * > _output_tensors
bool _is_valid = false
std::vector< std::unique_ptr< Kernel > > _kernels
Detailed Description
Definition at line 100 of file RuntimeGraph.h.
Constructor & Destructor Documentation
StaticRuntimeGraph()
luci_interpreter::StaticRuntimeGraph::StaticRuntimeGraph (IMemoryManager * memory_manager) explicit
Definition at line 186 of file RuntimeGraph.cpp.
  : IBaseRuntimeGraph(memory_manager)
{
}
~StaticRuntimeGraph()
luci_interpreter::StaticRuntimeGraph::~StaticRuntimeGraph () final
Definition at line 191 of file RuntimeGraph.cpp.
{
  // Release intermediate computing buffer.
  _memory_manager->release_computing_buf();
  _memory_manager->release_input_buf();
  _memory_manager->release_output_buf();
}
References luci_interpreter::IBaseRuntimeGraph::_memory_manager, luci_interpreter::IMemoryManager::release_computing_buf(), luci_interpreter::IMemoryManager::release_input_buf(), and luci_interpreter::IMemoryManager::release_output_buf().
Member Function Documentation
configure()
void luci_interpreter::StaticRuntimeGraph::configure () final virtual
Implements luci_interpreter::IBaseRuntimeGraph.
Definition at line 199 of file RuntimeGraph.cpp.
{
  // Allocate memory for intermediate computing buffer and for output buffer.
  _memory_manager->allocate_computing_buf();
  _memory_manager->allocate_output_buf();
  // Set tensor's data pointer for intermediate tensors
  for (auto &kernel : _kernels)
  {
    const auto output_tensors = kernel->getOutputTensors();
    for (auto tensor : output_tensors)
      _memory_manager->allocate_memory(*tensor);
  }
  // Set tensor's data pointer for output tensors
  for (const auto output_tensor : _output_tensors)
    _memory_manager->allocate_memory_for_output(*output_tensor);
  _is_valid = true;
}
References luci_interpreter::IBaseRuntimeGraph::_is_valid, luci_interpreter::IBaseRuntimeGraph::_kernels, luci_interpreter::IBaseRuntimeGraph::_memory_manager, luci_interpreter::IBaseRuntimeGraph::_output_tensors, luci_interpreter::IMemoryManager::allocate_computing_buf(), luci_interpreter::IMemoryManager::allocate_memory(), luci_interpreter::IMemoryManager::allocate_memory_for_output(), and luci_interpreter::IMemoryManager::allocate_output_buf().
Referenced by execute().
configure_kernels()
void luci_interpreter::StaticRuntimeGraph::configure_kernels () final virtual
Implements luci_interpreter::IBaseRuntimeGraph.
Definition at line 222 of file RuntimeGraph.cpp.
{
  for (auto &kernel : _kernels)
  {
    kernel->configure();
  }
}
References luci_interpreter::IBaseRuntimeGraph::_kernels.
execute()
void luci_interpreter::StaticRuntimeGraph::execute () final virtual
Implements luci_interpreter::IBaseRuntimeGraph.
Definition at line 230 of file RuntimeGraph.cpp.
{
  if (not _is_valid)
    configure();
  for (auto &kernel : _kernels)
  {
    // TODO: add kernel->configure for methods with dynamic shapes
    kernel->execute();
  }
  // Release intermediate computing buffer.
  _memory_manager->release_computing_buf();
  _is_valid = false;
}
References luci_interpreter::IBaseRuntimeGraph::_is_valid, luci_interpreter::IBaseRuntimeGraph::_kernels, luci_interpreter::IBaseRuntimeGraph::_memory_manager, configure(), and luci_interpreter::IMemoryManager::release_computing_buf().
The documentation for this class was generated from the following files:
onert-micro/luci-interpreter/src/core/RuntimeGraph.h
onert-micro/luci-interpreter/src/core/RuntimeGraph.cpp