ONE - On-device Neural Engine: coco::Update Class Reference
coco::Update Class Reference final
A Update represents an edge between a Bag and its Updater.
#include <Update.h>
Public Member Functions
Update (Bag::Updater *u)
~Update ()
Bag * bag (void) const
void bag (Bag *bag)
Bag::Updater * updater (void) const
void updater (Bag::Updater *u)
Detailed Description
A Update represents an edge between a Bag and its Updater.
Definition at line 28 of file Update.h.
Constructor & Destructor Documentation
Update()
coco::Update::Update (Bag::Updater * u) inline
Definition at line 31 of file Update.h.
{ updater(u); }
References updater().
~Update()
coco::Update::~Update ()
Definition at line 24 of file Update.cpp.
{
  // Unlink self from a linked bag if it exists
  bag(nullptr);
}
References bag().
Member Function Documentation
bag() [1/2]
void coco::Update::bag (Bag * bag)
Definition at line 30 of file Update.cpp.
{
  if (_bag)
  {
    _bag->mutable_updates()->erase(this);
    _bag = nullptr;
  }
  assert(_bag == nullptr);
  if (bag)
  {
    _bag = bag;
    _bag->mutable_updates()->insert(this);
  }
  assert(_bag == bag);
}
References bag().
bag() [2/2]
Bag * coco::Update::bag (void) const inline
Definition at line 37 of file Update.h.
{ return _bag; }
Referenced by bag(), coco::Shuffle::into(), and ~Update().
updater() [1/2]
void coco::Update::updater (Bag::Updater * u) inline
Definition at line 42 of file Update.h.
{ _updater = u; }
updater() [2/2]
Bag::Updater * coco::Update::updater (void) const inline
Definition at line 41 of file Update.h.
{ return _updater; }
Referenced by Update().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Update.h
compiler/coco/core/src/IR/Update.cpp