ONE - On-device Neural Engine: luci_interpreter::kernels::Rsqrt Class Reference
luci_interpreter::kernels::Rsqrt Class Reference
#include <Rsqrt.h>
Public Member Functions
Rsqrt (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Rsqrt (const Tensor *input, Tensor *output)
const Tensor * input () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file Rsqrt.h.
Constructor & Destructor Documentation
Rsqrt() [1/2]
luci_interpreter::kernels::Rsqrt::Rsqrt (const Tensor * input, Tensor * output)
Definition at line 29 of file Rsqrt.cpp.
: Kernel({input}, {output}) {}
References input().
Rsqrt() [2/2]
luci_interpreter::kernels::Rsqrt::Rsqrt (const Tensor * input, Tensor * output)
Member Function Documentation
configure() [1/2]
void luci_interpreter::kernels::Rsqrt::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 31 of file Rsqrt.cpp.
{
  if (input()->element_type() != output()->element_type())
  {
    throw std::runtime_error("Input/output tensor data type mismatch.");
  }
  output()->resize(input()->shape());
}
References input(), output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::Rsqrt::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Rsqrt::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 40 of file Rsqrt.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Rsqrt::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Rsqrt::input () const inline
Definition at line 33 of file Rsqrt.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Rsqrt().
input() [2/2]
const Tensor * luci_interpreter::kernels::Rsqrt::input () const inline
Definition at line 33 of file Rsqrt.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Rsqrt::output () const inline
Definition at line 34 of file Rsqrt.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Rsqrt::output () const inline
Definition at line 34 of file Rsqrt.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Rsqrt.h
onert-micro/luci-interpreter/src/kernels/Rsqrt.h
compiler/luci-interpreter/src/kernels/Rsqrt.cpp
onert-micro/luci-interpreter/src/kernels/Rsqrt.cpp