ONE - On-device Neural Engine: circle_eval_diff::HDF5Loader Class Reference
circle_eval_diff::HDF5Loader Class Reference final
#include <InputDataLoader.h>
Public Member Functions
HDF5Loader (const std::string &file_path, const std::vector< loco::Node * > &input_nodes)
uint32_t size (void) const final
Data get (uint32_t data_idx) const final
Public Member Functions inherited from circle_eval_diff::InputDataLoader
virtual ~InputDataLoader ()=default
virtual uint32_t size (void) const =0
virtual Data get (uint32_t data_idx) const =0
Additional Inherited Members
Public Types inherited from circle_eval_diff::InputDataLoader
using Data = std::vector< Tensor >
Detailed Description
Definition at line 63 of file InputDataLoader.h.
Constructor & Destructor Documentation
HDF5Loader()
circle_eval_diff::HDF5Loader::HDF5Loader (const std::string & file_path, const std::vector< loco::Node * > & input_nodes)
Definition at line 97 of file InputDataLoader.cpp.
  : _input_nodes{input_nodes}
{
  try
  {
    using HDF5Importer = dio::hdf5::HDF5Importer;
    _hdf5 = std::make_unique<HDF5Importer>(file_path);
    _hdf5->importGroup("value");
  }
  catch (const H5::Exception &e)
  {
    H5::Exception::printErrorStack();
    throw std::runtime_error("HDF5 error occurred.");
  }
}
Member Function Documentation
get()
InputDataLoader::Data circle_eval_diff::HDF5Loader::get (uint32_t data_idx) const final virtual
Implements circle_eval_diff::InputDataLoader.
Definition at line 116 of file InputDataLoader.cpp.
{
  Data data;
  data.resize(_input_nodes.size());
  for (uint32_t input_idx = 0; input_idx < _input_nodes.size(); input_idx++)
  {
    auto input_node = loco::must_cast<luci::CircleInput *>(_input_nodes.at(input_idx));
    assert(input_node->index() == input_idx);
    data.at(input_idx) = *createEmptyTensor(input_node).get();
    auto input_buffer = data.at(input_idx).buffer();
    try
    {
      if (_hdf5->isRawData())
      {
        _hdf5->readTensor(data_idx, input_idx, input_buffer);
      }
      else
      {
        DataType dtype;
        Shape shape;
        _hdf5->readTensor(data_idx, input_idx, &dtype, &shape, input_buffer);
        // Check the type and the shape of the input data is valid
        verifyTypeShape(input_node, dtype, shape);
      }
    }
    catch (const H5::Exception &e)
    {
      H5::Exception::printErrorStack();
      throw std::runtime_error("HDF5 error occurred.");
    }
  }
  return data;
}
References circle_eval_diff::createEmptyTensor(), luci::CircleInput::index(), and circle_eval_diff::verifyTypeShape().
size()
uint32_t circle_eval_diff::HDF5Loader::size (void) const final virtual
Implements circle_eval_diff::InputDataLoader.
Definition at line 114 of file InputDataLoader.cpp.
{ return _hdf5->numData(); }
The documentation for this class was generated from the following files:
compiler/circle-eval-diff/src/InputDataLoader.h
compiler/circle-eval-diff/src/InputDataLoader.cpp