ONE - On-device Neural Engine: circleinspect::DumpOperatorVersion Class Reference
circleinspect::DumpOperatorVersion Class Reference final
#include <Dump.h>
Public Member Functions
DumpOperatorVersion ()=default
void run (std::ostream &os, const circle::Model *model)
Public Member Functions inherited from circleinspect::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const circle::Model *model)=0
Detailed Description
Definition at line 54 of file Dump.h.
Constructor & Destructor Documentation
DumpOperatorVersion()
circleinspect::DumpOperatorVersion::DumpOperatorVersion () default
Member Function Documentation
run()
void circleinspect::DumpOperatorVersion::run (std::ostream & os, const circle::Model * model) virtual
Implements circleinspect::DumpInterface.
Definition at line 148 of file Dump.cpp.
{
  std::map<std::string, int32_t> op_version_map;
  mio::circle::Reader reader(model);
  // This assert is subject to be changed later
  assert(reader.num_subgraph() == 1);
  reader.select_subgraph(0);
  auto ops = reader.operators();
  // Dump operators' version
  for (uint32_t i = 0; i < ops->Length(); ++i)
  {
    const auto op = ops->Get(i);
    auto op_name = reader.opcode_name(op);
    auto op_version = reader.opcodes().at(op->opcode_index())->version();
    if (op_version_map.find(op_name) == op_version_map.end() ||
        op_version_map[op_name] < op_version)
      op_version_map[op_name] = op_version;
  }
  for (auto op : op_version_map)
  {
    os << op.first << "," << op.second << std::endl;
  }
}
References mio::circle::Reader::num_subgraph(), mio::circle::Reader::opcode_name(), mio::circle::Reader::opcodes(), mio::circle::Reader::operators(), and mio::circle::Reader::select_subgraph().
The documentation for this class was generated from the following files:
compiler/circle-inspect/src/Dump.h
compiler/circle-inspect/src/Dump.cpp