ONE - On-device Neural Engine: mir_onnx::ConverterContext Class Reference
mir_onnx::ConverterContext Class Reference
#include <ONNXNodeConverterRegistry.h>
Public Member Functions
ConverterContext (mir::Graph *graph)
~ConverterContext ()=default
void setOutput (const std::string &name, mir::Operation::Output *output)
mir::Operation::Output * getOutput (const std::string &name) const
std::vector< mir::Operation::Output * > getNodeInputs (const onnx::NodeProto &onnx_node) const
void setNodeOutputs (const onnx::NodeProto &onnx_node, const std::vector< mir::Operation::Output * > &outputs)
mir::Graph * getGraph () const
Detailed Description
Definition at line 42 of file ONNXNodeConverterRegistry.h.
Constructor & Destructor Documentation
ConverterContext()
mir_onnx::ConverterContext::ConverterContext (mir::Graph * graph) explicit
Definition at line 59 of file ONNXNodeConverterRegistry.cpp.
: _graph(graph) {}
~ConverterContext()
mir_onnx::ConverterContext::~ConverterContext () default
Member Function Documentation
getGraph()
mir::Graph * mir_onnx::ConverterContext::getGraph () const inline
Definition at line 53 of file ONNXNodeConverterRegistry.h.
{ return _graph; }
Referenced by mir_onnx::convertAddV7(), mir_onnx::convertAveragePoolV1(), mir_onnx::convertBatchNormalizationV9(), mir_onnx::convertConcatV1(), mir_onnx::convertConcatV4(), mir_onnx::convertConstantV1(), mir_onnx::convertConvTransposeV1(), mir_onnx::convertConvV1(), mir_onnx::convertDivV7(), mir_onnx::convertEqualV11(), mir_onnx::convertExpandV8(), mir_onnx::convertFlattenV1(), mir_onnx::convertGatherV1(), mir_onnx::convertGlobalAveragePoolV2(), mir_onnx::convertMatMulV1(), mir_onnx::convertMaxPoolV1(), mir_onnx::convertMulV7(), mir_onnx::convertPadAttrName(), mir_onnx::convertReduceMeanV1(), mir_onnx::convertReshapeV1(), mir_onnx::convertReshapeV5(), mir_onnx::convertShapeV1(), mir_onnx::convertSoftmaxV1(), mir_onnx::convertSubV7(), mir_onnx::convertSumV8(), mir_onnx::convertTransposeV1(), mir_onnx::convertUnsqueezeV1(), mir_onnx::convertUpsampleV1(), mir_onnx::convertUpsampleV7(), and mir_onnx::convertUpsampleV9().
getNodeInputs()
std::vector< mir::Operation::Output * > mir_onnx::ConverterContext::getNodeInputs (const onnx::NodeProto & onnx_node) const
Definition at line 79 of file ONNXNodeConverterRegistry.cpp.
{
  const auto &input_names = onnx_node.input();
  std::vector<mir::Operation::Output *> outputs;
  for (const auto &input_name : input_names)
  {
    if (!input_name.empty())
    {
      auto *mir_output = getOutput(input_name);
      assert(mir_output != nullptr);
      outputs.emplace_back(mir_output);
    }
  }
  return outputs;
}
References getOutput().
Referenced by mir_onnx::convertAddV7(), mir_onnx::convertAveragePoolV1(), mir_onnx::convertBatchNormalizationV9(), mir_onnx::convertConcatV1(), mir_onnx::convertConcatV4(), mir_onnx::convertConstantV1(), mir_onnx::convertConvTransposeV1(), mir_onnx::convertConvV1(), mir_onnx::convertDivV7(), mir_onnx::convertDropoutV10(), mir_onnx::convertEqualV11(), mir_onnx::convertExpandV8(), mir_onnx::convertFlattenV1(), mir_onnx::convertGatherV1(), mir_onnx::convertGlobalAveragePoolV2(), mir_onnx::convertIdentityV1(), mir_onnx::convertMatMulV1(), mir_onnx::convertMaxPoolV1(), mir_onnx::convertMulV7(), mir_onnx::convertPadAttrName(), mir_onnx::convertReduceMeanV1(), mir_onnx::convertReshapeV1(), mir_onnx::convertReshapeV5(), mir_onnx::convertShapeV1(), mir_onnx::convertSoftmaxV1(), mir_onnx::convertSubV7(), mir_onnx::convertSumV8(), mir_onnx::convertTransposeV1(), mir_onnx::convertUnsqueezeV1(), mir_onnx::convertUpsampleV1(), mir_onnx::convertUpsampleV7(), and mir_onnx::convertUpsampleV9().
getOutput()
mir::Operation::Output * mir_onnx::ConverterContext::getOutput (const std::string & name) const
Definition at line 69 of file ONNXNodeConverterRegistry.cpp.
{
  auto iter = _tensorNameToOutput.find(name);
  if (iter == _tensorNameToOutput.end())
    return nullptr;
  else
    return iter->second;
}
Referenced by getNodeInputs().
setNodeOutputs()
void mir_onnx::ConverterContext::setNodeOutputs (const onnx::NodeProto & onnx_node, const std::vector< mir::Operation::Output * > & outputs)
Definition at line 96 of file ONNXNodeConverterRegistry.cpp.
{
  assert(!outputs.empty());
  for (std::size_t i = 0; i < outputs.size(); ++i)
  {
    setOutput(onnx_node.output(i), outputs[i]);
  }
}
References setOutput().
Referenced by mir_onnx::convertAddV7(), mir_onnx::convertAveragePoolV1(), mir_onnx::convertBatchNormalizationV9(), mir_onnx::convertConcatV1(), mir_onnx::convertConcatV4(), mir_onnx::convertConstantV1(), mir_onnx::convertConvTransposeV1(), mir_onnx::convertConvV1(), mir_onnx::convertDivV7(), mir_onnx::convertDropoutV10(), mir_onnx::convertEqualV11(), mir_onnx::convertExpandV8(), mir_onnx::convertFlattenV1(), mir_onnx::convertGatherV1(), mir_onnx::convertGlobalAveragePoolV2(), mir_onnx::convertIdentityV1(), mir_onnx::convertMatMulV1(), mir_onnx::convertMaxPoolV1(), mir_onnx::convertMulV7(), mir_onnx::convertPadAttrName(), mir_onnx::convertReduceMeanV1(), mir_onnx::convertReshapeV1(), mir_onnx::convertReshapeV5(), mir_onnx::convertShapeV1(), mir_onnx::convertSoftmaxV1(), mir_onnx::convertSubV7(), mir_onnx::convertSumV8(), mir_onnx::convertTransposeV1(), mir_onnx::convertUnsqueezeV1(), mir_onnx::convertUpsampleV1(), mir_onnx::convertUpsampleV7(), and mir_onnx::convertUpsampleV9().
setOutput()
void mir_onnx::ConverterContext::setOutput (const std::string & name, mir::Operation::Output * output)
Definition at line 61 of file ONNXNodeConverterRegistry.cpp.
{
  output->setName(name);
  auto result = _tensorNameToOutput.emplace(name, output);
  if (!result.second)
    throw std::runtime_error("Name duplication: " + name);
}
Referenced by setNodeOutputs().
The documentation for this class was generated from the following files:
compiler/mir/src/mir_onnx_importer/ONNXNodeConverterRegistry.h
compiler/mir/src/mir_onnx_importer/ONNXNodeConverterRegistry.cpp