ONE - On-device Neural Engine: onert::backend::acl_neon::ConstantInitializer Class Reference
onert::backend::acl_neon::ConstantInitializer Class Reference
#include <ConstantInitializer.h>
Public Member Functions
ConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void visit (const ir::operation::SpaceToBatchND &node) final
Public Member Functions inherited from onert::backend::acl_common::AclConstantInitializer
void run ()
AclConstantInitializer (const ir::Operands &operands, const std::shared_ptr< ITensorRegistry > &tensor_reg)
void registerDefaultInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerCopyInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void registerPermuteInitializer (const ir::OperandIndex &index, const ir::Operand &obj)
void setLayout (ir::Layout layout)
bool exist (const ir::OperandIndex &ind)
void visit (const ir::operation::BatchToSpaceND &) override
void visit (const ir::operation::Conv2D &) override
void visit (const ir::operation::DepthwiseConv2D &) override
void visit (const ir::operation::FullyConnected &) override
void visit (const ir::operation::LSTM &) override
void visit (const ir::operation::RNN &) override
void visit (const ir::operation::TransposeConv &) override
Public Member Functions inherited from onert::ir::OperationVisitor
virtual ~OperationVisitor ()=default
Additional Inherited Members
Public Types inherited from onert::backend::acl_common::AclConstantInitializer
using Initializer = std::function< void(const ir::Operand &, backend::ITensor &)>
Protected Member Functions inherited from onert::backend::acl_common::AclConstantInitializer
void copyInputInitialize (const ir::Operation &node, uint32_t index)
void permuteInputInitialize (const ir::Operation &node, uint32_t index)
Protected Attributes inherited from onert::backend::acl_common::AclConstantInitializer
const ir::Operands & _operands
std::shared_ptr< ITensorRegistry > _tensor_reg
std::unordered_map< ir::OperandIndex, Initializer > _init_map
ir::Layout _current_layout
Detailed Description
Definition at line 29 of file ConstantInitializer.h.
Constructor & Destructor Documentation
ConstantInitializer()
onert::backend::acl_neon::ConstantInitializer::ConstantInitializer (const ir::Operands & operands, const std::shared_ptr< ITensorRegistry > & tensor_reg)
Definition at line 26 of file ConstantInitializer.cc.
  : acl_common::AclConstantInitializer{operands, tensor_reg}
{
  // DO NOTHING
}
Member Function Documentation
visit()
void onert::backend::acl_neon::ConstantInitializer::visit (const ir::operation::SpaceToBatchND & node) final
Definition at line 33 of file ConstantInitializer.cc.
{
  const auto &block_size_index = node.getInputs().at(ir::operation::SpaceToBatchND::BLOCK_SIZE);
  const auto &block_size_obj = _operands.at(block_size_index);
  if (block_size_obj.isConstant())
  {
    _init_map[block_size_index] = acl_common::initReverseOrder<int32_t>;
  }
  const auto &paddings_index = node.getInputs().at(ir::operation::SpaceToBatchND::PADDINGS);
  const auto &paddings_obj = _operands.at(paddings_index);
  if (paddings_obj.isConstant())
  {
    _init_map[paddings_index] = [](const ir::Operand &model_obj, backend::ITensor &obj) {
      assert(model_obj.data());
      const auto &shape = model_obj.shape();
      const auto base = reinterpret_cast<const int32_t *>(model_obj.data()->base());
      assert(model_obj.shape().rank() == 2);
      assert(shape.dim(0) == 2);
      assert(shape.dim(1) == 2);
      obj.access([&](ITensor &tensor) {
        for (auto i = 0; i < shape.dim(0); ++i)
        {
          for (auto j = 0; j < shape.dim(1); ++j)
          {
            const int32_t value = base[i * 2 + j];
            int32_t *into = reinterpret_cast<int32_t *>(
              // The coordinates of NETensor are different from the coordiantes of CLTensor in
              // this operand.
              // NEON : {j, reversed i}
              // CL : {reversed i, j}
              tensor.buffer() + tensor.calcOffset({j, shape.dim(0) - i - 1}));
            *into = value;
          }
        }
      });
    };
  }
}
References onert::backend::acl_common::AclConstantInitializer::_init_map, onert::backend::acl_common::AclConstantInitializer::_operands, onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::SpaceToBatchND::BLOCK_SIZE, onert::ir::Operand::data(), onert::ir::Operation::getInputs(), onert::ir::operation::SpaceToBatchND::PADDINGS, and onert::ir::Operand::shape().
The documentation for this class was generated from the following files:
runtime/onert/backend/acl_neon/ConstantInitializer.h
runtime/onert/backend/acl_neon/ConstantInitializer.cc