ONE - On-device Neural Engine: PoolingSpec Class Reference
PoolingSpec Class Reference
#include <PoolingSpec.h>
Public Member Functions
PoolingSpec (const ::caffe::PoolingParameter &param)
const nncc::core::ADT::tensor::Shape & ifm_shape (void) const
void ifm_shape (const nncc::core::ADT::tensor::Shape &shape)
PoolingMethod method (void) const
uint32_t window_height (void) const
uint32_t window_width (void) const
uint32_t vertical_pad (void) const
uint32_t horizontal_pad (void) const
uint32_t vertical_stride (void) const
uint32_t horizontal_stride (void) const
nncc::core::ADT::tensor::Shape ofm_shape (void) const
Detailed Description
Definition at line 30 of file PoolingSpec.h.
Constructor & Destructor Documentation
PoolingSpec()
PoolingSpec::PoolingSpec (const ::caffe::PoolingParameter & param)
Definition at line 23 of file PoolingSpec.cpp.
                                                           : _param(param)
{
  // DO NOTHING
}
Member Function Documentation
horizontal_pad()
uint32_t PoolingSpec::horizontal_pad (void) const
Definition at line 87 of file PoolingSpec.cpp.
{
  // NOTE The input of Pooling SHOULD BE a rank-4 tensor.
  // Reference: PoolingLayer<Dtype>::Reshape in pooling_layer.cpp
  auto raw_padding = build_raw_padding().with(_param);
  auto spatial_padding = build_spatial_padding(2 /* SPATIAL RANK */).with(raw_padding);
  return spatial_padding.value(1 /* W */);
}
References build_raw_padding(), build_spatial_padding(), PaddingBase< Derived >::value(), RawPaddingBuilder::with(), and SpatialPaddingBuilder::with().
Referenced by ofm_shape().
horizontal_stride()
uint32_t PoolingSpec::horizontal_stride (void) const
Definition at line 111 of file PoolingSpec.cpp.
{
  if (_param.has_stride_w())
  {
    return _param.stride_w();
  }
  if (_param.has_stride())
  {
    return _param.stride();
  }
  return 1;
}
Referenced by ofm_shape().
ifm_shape() [1/2]
void PoolingSpec::ifm_shape (const nncc::core::ADT::tensor::Shape & shape) inline
Definition at line 37 of file PoolingSpec.h.
{ _ifm_shape = shape; }
ifm_shape() [2/2]
const nncc::core::ADT::tensor::Shape & PoolingSpec::ifm_shape (void) const inline
Definition at line 36 of file PoolingSpec.h.
{ return _ifm_shape; }
Referenced by caffeimport::PoolingBuilder::build().
method()
PoolingMethod PoolingSpec::method (void) const
Definition at line 28 of file PoolingSpec.cpp.
{
  if (!_param.has_pool())
  {
    // Default pooling method is MAX
    // Reference: http://caffe.berkeleyvision.org/tutorial/layers/pooling.html
    return PoolingMethod::Max;
  }
  std::map<::caffe::PoolingParameter_PoolMethod, PoolingMethod> methods;
  // NOTE STOCHASTIC Pooling is not supported, yet
  // TODO Support STOCHASTIC Pooling
  methods[::caffe::PoolingParameter_PoolMethod_MAX] = PoolingMethod::Max;
  methods[::caffe::PoolingParameter_PoolMethod_AVE] = PoolingMethod::Avg;
  assert(_param.has_pool());
  return methods.at(_param.pool());
}
ofm_shape()
nncc::core::ADT::tensor::Shape PoolingSpec::ofm_shape (void) const
Definition at line 126 of file PoolingSpec.cpp.
{
  nncc::core::ADT::tensor::Shape res;
  // NOTE Caffe supports only pooling over rank-4 tensor
  assert(_ifm_shape.rank() == 4);
  res.resize(4);
  // N (= the number of bacths) SHOULD be same
  res.dim(0) = _ifm_shape.dim(0);
  // C (= the number of chaanels) SHOULD be same
  res.dim(1) = _ifm_shape.dim(1);
  // H and W are derived from IFM, Window, and Padding
  const auto effective_input_height = _ifm_shape.dim(2) + 2 * vertical_pad() - window_height();
  const auto effective_input_width = _ifm_shape.dim(3) + 2 * horizontal_pad() - window_width();
  // TODO Remove the following asserts
  assert(effective_input_height % vertical_stride() == 0);
  assert(effective_input_width % horizontal_stride() == 0);
  res.dim(2) = effective_input_height / vertical_stride() + 1;
  res.dim(3) = effective_input_width / horizontal_stride() + 1;
  return res;
}
References nncc::core::ADT::tensor::Shape::dim(), horizontal_pad(), horizontal_stride(), nncc::core::ADT::tensor::Shape::rank(), nncc::core::ADT::tensor::Shape::resize(), vertical_pad(), vertical_stride(), window_height(), and window_width().
vertical_pad()
uint32_t PoolingSpec::vertical_pad (void) const
Definition at line 78 of file PoolingSpec.cpp.
{
  // NOTE The input of Pooling SHOULD BE a rank-4 tensor.
  // Reference: PoolingLayer<Dtype>::Reshape in pooling_layer.cpp
  auto raw_padding = build_raw_padding().with(_param);
  auto spatial_padding = build_spatial_padding(2 /* SPATIAL RANK */).with(raw_padding);
  return spatial_padding.value(0 /* H */);
}
References build_raw_padding(), build_spatial_padding(), PaddingBase< Derived >::value(), RawPaddingBuilder::with(), and SpatialPaddingBuilder::with().
Referenced by ofm_shape().
vertical_stride()
uint32_t PoolingSpec::vertical_stride (void) const
Definition at line 96 of file PoolingSpec.cpp.
{
  if (_param.has_stride_h())
  {
    return _param.stride_h();
  }
  if (_param.has_stride())
  {
    return _param.stride();
  }
  return 1;
}
Referenced by ofm_shape().
window_height()
uint32_t PoolingSpec::window_height (void) const
Definition at line 48 of file PoolingSpec.cpp.
{
  // NOTE Global pooling is not supported, yet
  // TODO Support global pooling
  assert(!_param.global_pooling());
  if (_param.has_kernel_h())
  {
    return _param.kernel_h();
  }
  assert(_param.has_kernel_size());
  return _param.kernel_size();
}
Referenced by ofm_shape().
window_width()
uint32_t PoolingSpec::window_width (void) const
Definition at line 63 of file PoolingSpec.cpp.
{
  // NOTE Global pooling is not supported, yet
  // TODO Support global pooling
  assert(!_param.global_pooling());
  if (_param.has_kernel_w())
  {
    return _param.kernel_w();
  }
  assert(_param.has_kernel_size());
  return _param.kernel_size();
}
Referenced by ofm_shape().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/PoolingSpec.h
compiler/enco/frontend/caffe/src/PoolingSpec.cpp