ONE - On-device Neural Engine: coco::Use Class Reference
coco::Use Class Reference final
#include <Use.h>
Public Member Functions
Use (Object::Consumer *use)
~Use ()
Object * value (void) const
void value (Object *value)
Object::Consumer * consumer (void) const
Detailed Description
Definition at line 25 of file Use.h.
Constructor & Destructor Documentation
Use()
coco::Use::Use (Object::Consumer * use) inline
Definition at line 28 of file Use.h.
                           : _value{nullptr}, _consumer{use}
  {
    // DO NOTHING
  }
~Use()
coco::Use::~Use () inline
Definition at line 34 of file Use.h.
{ value(nullptr); }
References value().
Member Function Documentation
consumer()
Object::Consumer * coco::Use::consumer (void) const inline
Definition at line 43 of file Use.h.
{ return _consumer; }
value() [1/2]
void coco::Use::value (Object * value)
Definition at line 24 of file Use.cpp.
{
  if (_value)
  {
    _value->mutable_uses()->erase(this);
    _value = nullptr;
  }
  assert(_value == nullptr);
  if (value)
  {
    _value = value;
    _value->mutable_uses()->insert(this);
  }
  assert(_value == value);
}
References value().
value() [2/2]
Object * coco::Use::value (void) const inline
Definition at line 37 of file Use.h.
{ return _value; }
Referenced by ANNConv2D::bias(), coco::Copy::from(), ANNDepthConcatF::fst(), ANNConv2D::ifm(), coco::Conv2D::ker(), ANNConv2D::ker(), coco::Load::object(), ANNDepthConcatF::snd(), value(), and ~Use().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/Use.h
compiler/coco/core/src/IR/Use.cpp