ONE - On-device Neural Engine: foder::FileLoader Class Reference
foder::FileLoader Class Reference
#include <FileLoader.h>
Public Member Functions
FileLoader (const std::string &path)
FileLoader (const FileLoader &)=delete
FileLoader & operator= (const FileLoader &)=delete
DataBuffer load (void) const
Detailed Description
Definition at line 26 of file FileLoader.h.
Constructor & Destructor Documentation
FileLoader() [1/2]
foder::FileLoader::FileLoader (const std::string & path) inline explicit
Definition at line 32 of file FileLoader.h.
: _path(path) {}
FileLoader() [2/2]
foder::FileLoader::FileLoader (const FileLoader &) delete
Member Function Documentation
load()
DataBuffer foder::FileLoader::load (void) const inline
Definition at line 39 of file FileLoader.h.
  {
    std::ifstream file(_path, std::ios::binary | std::ios::in);
    if (!file.good())
    {
      std::string errmsg = "Failed to open file: " + _path;
      throw std::runtime_error(errmsg.c_str());
    }
    file.unsetf(std::ios::skipws);
    file.seekg(0, std::ios::end);
    auto fileSize = file.tellg();
    file.seekg(0, std::ios::beg);
    // reserve capacity
    DataBuffer data(fileSize);
    // read the data
    file.read(data.data(), fileSize);
    if (file.fail())
    {
      std::string errmsg = "Failed to read file: " + _path;
      throw std::runtime_error(errmsg.c_str());
    }
    return data;
  }
Referenced by entry(), opselector::getModule(), luci::ImporterEx::importVerifyModule(), dalgona::Dalgona::initialize(), crew::read_ini(), ReadModule(), and VerifyFlatbuffers::run().
operator=()
FileLoader & foder::FileLoader::operator= (const FileLoader &) delete
The documentation for this class was generated from the following file:
compiler/foder/include/foder/FileLoader.h