ONE - On-device Neural Engine: onert::backend::builtin::TensorBuilder Class Reference
onert::backend::builtin::TensorBuilder Class Reference
#include <TensorBuilder.h>
Public Member Functions
TensorBuilder (const std::shared_ptr< TensorRegistry > &tensor_reg)
void registerTensorInfo (const ir::OperandIndex &ind, const ir::OperandInfo &info, ir::Layout backend_layout)
Register tensor information to allocate on CPU backend.
void notifyFirstUse (const ir::OperandIndex &)
void notifyLastUse (const ir::OperandIndex &)
bool isRegistered (const ir::OperandIndex &) const
void allocate (void)
DynamicTensorManager * dynamicTensorManager (void)
basic::Tensor * nativeOwnTensorAt (const ir::OperandIndex &ind)
Get tensor with a specific OperandIndex.
Detailed Description
Definition at line 37 of file TensorBuilder.h.
Constructor & Destructor Documentation
TensorBuilder()
onert::backend::builtin::TensorBuilder::TensorBuilder (const std::shared_ptr< TensorRegistry > & tensor_reg)
Definition at line 30 of file TensorBuilder.cc.
  : _tensor_reg{tensor_reg}, _dynamic_tensor_mgr{new DynamicTensorManager(_tensor_reg->base_reg())},
    _static_tensor_mgr{
      new basic::StaticTensorManager(_tensor_reg->base_reg(), _dynamic_tensor_mgr.get())}
{
  /* empty */
}
Member Function Documentation
allocate()
void onert::backend::builtin::TensorBuilder::allocate (void)
Definition at line 91 of file TensorBuilder.cc.
{ _static_tensor_mgr->allocateNonconsts(); }
dynamicTensorManager()
DynamicTensorManager * onert::backend::builtin::TensorBuilder::dynamicTensorManager (void)
Definition at line 93 of file TensorBuilder.cc.
{
  return _dynamic_tensor_mgr.get();
}
isRegistered()
bool onert::backend::builtin::TensorBuilder::isRegistered (const ir::OperandIndex & ind) const
Definition at line 81 of file TensorBuilder.cc.
{
  // User tensors are not registered in _tensor_info_map but objects for them are exist
  // in the tensor registry.
  // TODO Enhance the way of checking user tensors
  if (_tensor_reg->getITensor(ind))
    return true;
  return _tensor_info_map.find(ind) != _tensor_info_map.end();
}
nativeOwnTensorAt()
basic::Tensor * onert::backend::builtin::TensorBuilder::nativeOwnTensorAt (const ir::OperandIndex & ind)
Get tensor with a specific OperandIndex.
Parameters
ind OperandIndex for the tensor. There must exist a tensor with this ind. If not, program will crash with assert or exception.
Returns
operand::Tensor *
Definition at line 98 of file TensorBuilder.cc.
{
  return _tensor_reg->getNativeOwnTensor(ind);
}
Referenced by notifyFirstUse(), and notifyLastUse().
notifyFirstUse()
void onert::backend::builtin::TensorBuilder::notifyFirstUse (const ir::OperandIndex & ind)
Definition at line 54 of file TensorBuilder.cc.
{
  // TODO Enhance the way of checking user tensors
  if (_tensor_info_map.find(ind) == _tensor_info_map.end()) // Do not proceed for user tensors
    return;
  const auto tensor_info = _tensor_info_map.at(ind);
  if (!nativeOwnTensorAt(ind)->is_dynamic())
  {
    const auto size = tensor_info.total_size();
    _static_tensor_mgr->claimPlan(ind, size);
  }
}
References nativeOwnTensorAt().
notifyLastUse()
void onert::backend::builtin::TensorBuilder::notifyLastUse (const ir::OperandIndex & ind)
Definition at line 69 of file TensorBuilder.cc.
{
  // TODO Enhance the way of checking user tensors
  if (_tensor_info_map.find(ind) == _tensor_info_map.end()) // Do not proceed for user tensors
    return;
  if (!nativeOwnTensorAt(ind)->is_dynamic())
  {
    _static_tensor_mgr->releasePlan(ind);
  }
}
References nativeOwnTensorAt().
registerTensorInfo()
void onert::backend::builtin::TensorBuilder::registerTensorInfo (const ir::OperandIndex & ind, const ir::OperandInfo & info, ir::Layout backend_layout)
Register tensor information to allocate on CPU backend.
Parameters
[in] ind Operand index
[in] info Operand information
[in] layout Operand data layout
Definition at line 38 of file TensorBuilder.cc.
{
  _tensor_info_map.emplace(ind, info);
  VERBOSE_F() << "cpucommon REGISTER!! " << ind << std::endl;
  if (info.isDynamic())
  {
    _dynamic_tensor_mgr->buildTensor(ind, info, backend_layout);
  }
  else
  {
    _static_tensor_mgr->buildTensor(ind, info, backend_layout, info.isConstant());
  }
}
References info, and VERBOSE_F.
The documentation for this class was generated from the following files:
runtime/onert/core/src/backend/builtin/TensorBuilder.h
runtime/onert/core/src/backend/builtin/TensorBuilder.cc