ONE - On-device Neural Engine: luci_interpreter::kernels::Mean Class Reference
luci_interpreter::kernels::Mean Class Reference
#include <Mean.h>
Public Member Functions
Mean (const Tensor *input, const Tensor *axes, Tensor *output, Tensor *temp_index, Tensor *resolved_axes, Tensor *temp_sum, const ReducerParams &params)
const Tensor * input () const
const Tensor * axes () const
Tensor * output () const
void configure () override
void execute () const override
Mean (const Tensor *input, const Tensor *axes, Tensor *output, Tensor *temp_index, Tensor *resolved_axes, Tensor *temp_sum, const ReducerParams &params)
const Tensor * input () const
const Tensor * axes () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< ReducerParams >
const ReducerParams & params () const
const ReducerParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< ReducerParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ReducerParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const ReducerParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< ReducerParams >
const ReducerParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 30 of file Mean.h.
Constructor & Destructor Documentation
Mean() [1/2]
luci_interpreter::kernels::Mean::Mean (const Tensor * input, const Tensor * axes, Tensor * output, Tensor * temp_index, Tensor * resolved_axes, Tensor * temp_sum, const ReducerParams & params)
Definition at line 126 of file Mean.cpp.
  : KernelWithParams<ReducerParams>({input, axes}, {output, temp_index, resolved_axes, temp_sum},
                                    params)
{
}
References axes(), and input().
Mean() [2/2]
luci_interpreter::kernels::Mean::Mean (const Tensor * input, const Tensor * axes, Tensor * output, Tensor * temp_index, Tensor * resolved_axes, Tensor * temp_sum, const ReducerParams & params)
Member Function Documentation
axes() [1/2]
const Tensor * luci_interpreter::kernels::Mean::axes () const inline
Definition at line 37 of file Mean.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), and Mean().
axes() [2/2]
const Tensor * luci_interpreter::kernels::Mean::axes () const inline
Definition at line 37 of file Mean.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::Mean::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 133 of file Mean.cpp.
{
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  LUCI_INTERPRETER_CHECK(axes()->element_type() == DataType::S32);
  if (input()->element_type() == DataType::S16)
  {
    LUCI_INTERPRETER_CHECK(input()->zero_point() == 0 && output()->zero_point() == 0);
  }
  const Shape &input_shape = input()->shape();
  int input_num_dims = input_shape.num_dims();
  const auto *axes_data = getTensorData<int32_t>(axes());
  int num_axes = axes()->shape().num_elements();
  assert(num_axes <= 4);
  Shape output_shape = getOutputShape(input_shape, axes_data, num_axes, _params.keep_dims);
  output()->resize(output_shape);
  tflite::MeanParams params{};
  resolveAxes(axes_data, num_axes, &params);
  _need_temporaries = !(
    _params.keep_dims && input_num_dims == 4 && params.axis_count == 2 &&
    ((params.axis[0] == 1 && params.axis[1] == 2) || (params.axis[0] == 2 && params.axis[1] == 1)));
  if (_need_temporaries)
  {
    auto temp_index = getOutputTensors()[1];
    auto resolved_axes = getOutputTensors()[2];
    auto temp_sum = getOutputTensors()[3];
    temp_index->resize(Shape(input_num_dims));
    resolved_axes->resize(Shape(num_axes));
    temp_sum->resize(output()->shape());
  }
  else
  {
    auto temp_index = getOutputTensors()[1];
    auto resolved_axes = getOutputTensors()[2];
    auto temp_sum = getOutputTensors()[3];
    temp_index->set_allocatable(false);
    resolved_axes->set_allocatable(false);
    temp_sum->set_allocatable(false);
  }
}
References luci_interpreter::KernelWithParams< ReducerParams >::_params, axes(), luci_interpreter::Kernel::getOutputTensors(), input(), luci_interpreter::ReducerParams::keep_dims, LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), luci_interpreter::Shape::num_elements(), output(), luci_interpreter::KernelWithParams< ReducerParams >::params(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::Mean::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::Mean::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 179 of file Mean.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      evalFloat();
      break;
    case DataType::U8:
      evalQuantized();
      break;
    case DataType::S16:
      evalQuantizedS16();
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References input().
execute() [2/2]
void luci_interpreter::kernels::Mean::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::Mean::input () const inline
Definition at line 36 of file Mean.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and Mean().
input() [2/2]
const Tensor * luci_interpreter::kernels::Mean::input () const inline
Definition at line 36 of file Mean.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::Mean::output () const inline
Definition at line 38 of file Mean.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure().
output() [2/2]
Tensor * luci_interpreter::kernels::Mean::output () const inline
Definition at line 38 of file Mean.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/Mean.h
onert-micro/luci-interpreter/src/kernels/Mean.h
compiler/luci-interpreter/src/kernels/Mean.cpp
onert-micro/luci-interpreter/src/kernels/Mean.cpp