ONE - On-device Neural Engine: exo::MaxPool2DConverter Class Reference
exo::MaxPool2DConverter Class Reference
Convert loco::MaxPool2D to locoex::TFLMaxPool2D.
#include <MaxPool2DConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::MaxPool2D *origin) final
Converts loco::MaxPool2D to locoex::TFLMaxPool2D.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::MaxPool2D >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::MaxPool2D *node)=0
Detailed Description
Convert loco::MaxPool2D to locoex::TFLMaxPool2D.
Definition at line 30 of file MaxPool2DConverter.h.
Member Function Documentation
convert()
bool exo::MaxPool2DConverter::convert (loco::MaxPool2D * origin) final virtual
Converts loco::MaxPool2D to locoex::TFLMaxPool2D.
Note
This works similar to AvgPool2DConverter. Please refer to the comment in AvgPool2DConverter.
Implements exo::CanonicalNodeConverter< loco::MaxPool2D >.
Definition at line 33 of file MaxPool2DConverter.cpp.
{
  auto *graph = origin->graph();
  auto dec = make_feature_decode<FeatureLayout::NHWC>(origin->ifm());
  auto tfl_max = graph->nodes()->create<locoex::TFLMaxPool2D>();
  {
    tfl_max->value(dec);
    // set attributes
    tfl_max->stride()->w(origin->stride()->horizontal());
    tfl_max->stride()->h(origin->stride()->vertical());
    tfl_max->filter()->w(origin->window()->horizontal());
    tfl_max->filter()->h(origin->window()->vertical());
    auto pad = origin->pad();
    if (pad->bottom() == 0 && pad->top() == 0 && pad->left() == 0 && pad->right() == 0)
      tfl_max->padding(locoex::Padding::VALID);
    else
      // TODO This is necessary, but not sufficient condition. More rigorous check required
      tfl_max->padding(locoex::Padding::SAME);
    tfl_max->fusedActivationFunction(locoex::FusedActFunc::NONE);
  }
  auto enc = make_feature_encode<FeatureLayout::NHWC>(tfl_max);
  loco::replace(origin).with(enc);
  origin->ifm(nullptr);
  return true;
}
References loco::Node::graph(), loco::Stride< 2 >::horizontal(), loco::Window< 2 >::horizontal(), loco::MaxPool2D::ifm(), exo::make_feature_decode< FeatureLayout::NHWC >(), exo::make_feature_encode< FeatureLayout::NHWC >(), locoex::NONE, loco::MaxPool2D::pad(), loco::replace(), locoex::SAME, loco::MaxPool2D::stride(), locoex::VALID, locoex::TFLMaxPool2D::value(), loco::Stride< 2 >::vertical(), loco::Window< 2 >::vertical(), loco::MaxPool2D::window(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::MaxPool2DConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::MaxPool2D >.
Definition at line 33 of file MaxPool2DConverter.h.
{ return "exo::MaxPool2DConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/MaxPool2DConverter.h
compiler/exo/src/Conversion/MaxPool2DConverter.cpp