ONE - On-device Neural Engine: luci_interpreter::kernels::BatchToSpaceND Class Reference
luci_interpreter::kernels::BatchToSpaceND Class Reference
#include <BatchToSpaceND.h>
Public Member Functions
BatchToSpaceND (const Tensor *input, const Tensor *block_shape, const Tensor *crops, Tensor *output)
const Tensor * input () const
const Tensor * block_shape () const
const Tensor * crops () const
Tensor * output () const
void configure () override
void execute () const override
BatchToSpaceND (const Tensor *input, const Tensor *block_shape, const Tensor *crops, Tensor *output)
const Tensor * input () const
const Tensor * block_shape () const
const Tensor * crops () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file BatchToSpaceND.h.
Constructor & Destructor Documentation
BatchToSpaceND() [1/2]
luci_interpreter::kernels::BatchToSpaceND::BatchToSpaceND (const Tensor * input, const Tensor * block_shape, const Tensor * crops, Tensor * output)
Definition at line 37 of file BatchToSpaceND.cpp.
  : Kernel({input, block_shape, crops}, {output})
{
}
References block_shape(), crops(), and input().
BatchToSpaceND() [2/2]
luci_interpreter::kernels::BatchToSpaceND::BatchToSpaceND (const Tensor * input, const Tensor * block_shape, const Tensor * crops, Tensor * output)
Member Function Documentation
block_shape() [1/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::block_shape () const inline
Definition at line 34 of file BatchToSpaceND.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by BatchToSpaceND(), configure(), and execute().
block_shape() [2/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::block_shape () const inline
Definition at line 34 of file BatchToSpaceND.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::BatchToSpaceND::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 43 of file BatchToSpaceND.cpp.
{
  const auto *block_shape_data = block_shape()->data<int32_t>();
  const auto *crops_data = crops()->data<int32_t>();
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() >= kInputMinDimensionNum);
  LUCI_INTERPRETER_CHECK(input()->shape().num_dims() <= kInputMaxDimensionNum);
  LUCI_INTERPRETER_CHECK(input()->element_type() == output()->element_type());
  int spatial_dims_num = input()->shape().num_dims() - 2;
  LUCI_INTERPRETER_CHECK(block_shape()->shape().num_dims() == 1);
  LUCI_INTERPRETER_CHECK(block_shape()->shape().dim(0) == spatial_dims_num);
  LUCI_INTERPRETER_CHECK(crops()->shape().num_dims() == 2);
  LUCI_INTERPRETER_CHECK(crops()->shape().dim(0) == spatial_dims_num);
  LUCI_INTERPRETER_CHECK(crops()->shape().dim(1) == 2);
  for (int i = 0; i < spatial_dims_num * 2; ++i)
  {
    LUCI_INTERPRETER_CHECK(crops_data[i] >= 0);
  }
  Shape output_shape = Shape(input()->shape().num_dims());
  int output_batch_size = input()->shape().dim(0);
  for (int i = 0; i < spatial_dims_num; ++i)
  {
    LUCI_INTERPRETER_CHECK(output_batch_size % block_shape_data[i] == 0);
    output_batch_size = output_batch_size / block_shape_data[i];
    output_shape.dim(i + 1) =
      input()->shape().dim(i + 1) * block_shape_data[i] - crops_data[i * 2] - crops_data[i * 2 + 1];
  }
  output_shape.dim(0) = output_batch_size;
  output_shape.dim(input()->shape().num_dims() - 1) =
    input()->shape().dim(input()->shape().num_dims() - 1);
  output()->resize(output_shape);
}
References block_shape(), crops(), luci_interpreter::Tensor::data(), luci_interpreter::Shape::dim(), input(), LUCI_INTERPRETER_CHECK, luci_interpreter::Shape::num_dims(), output(), luci_interpreter::Tensor::resize(), and luci_interpreter::Tensor::shape().
configure() [2/2]
void luci_interpreter::kernels::BatchToSpaceND::configure () override virtual
Implements luci_interpreter::Kernel.
crops() [1/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::crops () const inline
Definition at line 35 of file BatchToSpaceND.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by BatchToSpaceND(), configure(), and execute().
crops() [2/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::crops () const inline
Definition at line 35 of file BatchToSpaceND.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
execute() [1/2]
void luci_interpreter::kernels::BatchToSpaceND::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 81 of file BatchToSpaceND.cpp.
{
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      luci_interpreter_pal::BatchToSpaceND(
        getTensorShape(input()), getTensorData<float>(input()), getTensorShape(block_shape()),
        getTensorData<int32_t>(block_shape()), getTensorShape(crops()),
        getTensorData<int32_t>(crops()), getTensorShape(output()), getTensorData<float>(output()));
      break;
    case DataType::U8:
      luci_interpreter_pal::BatchToSpaceND(
        getTensorShape(input()), getTensorData<uint8_t>(input()), getTensorShape(block_shape()),
        getTensorData<int32_t>(block_shape()), getTensorShape(crops()),
        getTensorData<int32_t>(crops()), getTensorShape(output()),
        getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References block_shape(), crops(), luci_interpreter::kernels::getTensorShape(), input(), and output().
execute() [2/2]
void luci_interpreter::kernels::BatchToSpaceND::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::input () const inline
Definition at line 33 of file BatchToSpaceND.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by BatchToSpaceND(), configure(), and execute().
input() [2/2]
const Tensor * luci_interpreter::kernels::BatchToSpaceND::input () const inline
Definition at line 33 of file BatchToSpaceND.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::BatchToSpaceND::output () const inline
Definition at line 36 of file BatchToSpaceND.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::BatchToSpaceND::output () const inline
Definition at line 36 of file BatchToSpaceND.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/BatchToSpaceND.h
onert-micro/luci-interpreter/src/kernels/BatchToSpaceND.h
compiler/luci-interpreter/src/kernels/BatchToSpaceND.cpp
onert-micro/luci-interpreter/src/kernels/BatchToSpaceND.cpp