ONE - On-device Neural Engine: luci::CircleTransposeConv Class Reference
luci::CircleTransposeConv Class Reference final
TRANSPOSE_CONV in Circle.
#include <CircleTransposeConv.h>
Public Member Functions
loco::Node * inputSizes (void) const
void inputSizes (Node *node)
loco::Node * filter (void) const
void filter (Node *node)
loco::Node * outBackprop (void) const
void outBackprop (Node *node)
loco::Node * bias (void) const override
void bias (loco::Node *node) override
get the input for bias.
const Padding & padding (void) const
void padding (const Padding &padding)
const Stride * stride (void) const
Stride * stride (void)
Public Member Functions inherited from luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from luci::CircleNodeMixin< CircleNodeTrait::Bias >
CircleNodeMixin ()=default
virtual loco::Node * bias (void) const =0
virtual void bias (loco::Node *node)=0
get the input for bias.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >
loco::Use * at (uint32_t n) const
Detailed Description
TRANSPOSE_CONV in Circle.
Note
Argument node function names are from TensorFlow. So referring 'in' and 'out' acutally means 'out' and 'in' of the this node.
Definition at line 36 of file CircleTransposeConv.h.
Member Function Documentation
bias() [1/2]
void luci::CircleTransposeConv::bias (loco::Node * node) inline override virtual
get the input for bias.
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 63 of file CircleTransposeConv.h.
{ at(3)->node(node); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
bias() [2/2]
loco::Node * luci::CircleTransposeConv::bias (void) const inline override virtual
Note
"bias" is optional. When this node has no conceptual bias, "bias()" expected to be luci::CircleOutputExclude type.
<Comment on tflite TRANSPOSE_CONV>
(Circle node has no dependency on tflite, but just for information on converting) Before TF v2.3.0, tflite TRANSPOSE_CONV didn't support fused bias as argument. From TF v2.3.0, tflite TRANSPOSE_CONV supports bias as optional 4th argument.
Ref: https://github.com/tensorflow/tensorflow/commit/43b8f6e710
Implements luci::CircleNodeMixin< CircleNodeTrait::Bias >.
Definition at line 62 of file CircleTransposeConv.h.
{ return at(3)->node(); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
filter() [1/2]
void luci::CircleTransposeConv::filter (Node * node) inline
Definition at line 45 of file CircleTransposeConv.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
filter() [2/2]
loco::Node * luci::CircleTransposeConv::filter (void) const inline
Definition at line 44 of file CircleTransposeConv.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
inputSizes() [1/2]
void luci::CircleTransposeConv::inputSizes (Node * node) inline
Definition at line 42 of file CircleTransposeConv.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
inputSizes() [2/2]
loco::Node * luci::CircleTransposeConv::inputSizes (void) const inline
Definition at line 41 of file CircleTransposeConv.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
outBackprop() [1/2]
void luci::CircleTransposeConv::outBackprop (Node * node) inline
Definition at line 48 of file CircleTransposeConv.h.
{ at(2)->node(node); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
outBackprop() [2/2]
loco::Node * luci::CircleTransposeConv::outBackprop (void) const inline
Definition at line 47 of file CircleTransposeConv.h.
{ return at(2)->node(); }
References luci::FixedArityNode< 4, CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV > >::at(), and loco::Use::node().
padding() [1/2]
void luci::CircleTransposeConv::padding (const Padding & padding) inline
Definition at line 67 of file CircleTransposeConv.h.
{ _padding = padding; }
References padding().
Referenced by padding().
padding() [2/2]
const Padding & luci::CircleTransposeConv::padding (void) const inline
Definition at line 66 of file CircleTransposeConv.h.
{ return _padding; }
Referenced by luci::CloneNodeLet< CN::STUV >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
stride() [1/2]
Stride * luci::CircleTransposeConv::stride (void) inline
Definition at line 70 of file CircleTransposeConv.h.
{ return &_stride; }
stride() [2/2]
const Stride * luci::CircleTransposeConv::stride (void) const inline
Definition at line 69 of file CircleTransposeConv.h.
{ return &_stride; }
Referenced by luci::CloneNodeLet< CN::STUV >::visit(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleTransposeConv.h