ONE - On-device Neural Engine: mir::ops::ConcatOp Class Reference
mir::ops::ConcatOp Class Reference
Description of tensor concatenation operation.
#include <ConcatOp.h>
Public Member Functions
ConcatOp (const std::vector< Output * > &args, int32_t axis)
Operation * copyWithInputs (const std::vector< Output * > &inputs) override
int32_t getAxis () const
Public Member Functions inherited from mir::Operation
virtual ~Operation ()=default
Type getType () const
std::size_t getId () const
void setId (std::size_t id)
std::size_t getNumInputs () const
std::size_t getNumOutputs () const
std::deque< Output * > & getInputs ()
const std::deque< Output * > & getInputs () const
std::deque< Output > & getOutputs ()
const std::deque< Output > & getOutputs () const
Output * getInput (std::size_t index)
const Output * getInput (std::size_t index) const
Output * getOutput (std::size_t index)
const Output * getOutput (std::size_t index) const
const Shape & getInputShape (std::size_t index) const
const Shape & getOutputShape (std::size_t index) const
void accept (IVisitor *v)
virtual Operation * copyWithInputs (const std::vector< Output * > &inputs)=0
Additional Inherited Members
Public Types inherited from mir::Operation
enum class Type { HANDLE_OP }
Protected Member Functions inherited from mir::Operation
Operation (Type type, const std::vector< Output * > &inputs, std::size_t num_outputs=1)
void setOutputType (std::size_t index, const TensorType &type)
Detailed Description
Description of tensor concatenation operation.
Definition at line 30 of file ConcatOp.h.
Constructor & Destructor Documentation
ConcatOp()
mir::ops::ConcatOp::ConcatOp (const std::vector< Output * > & args, int32_t axis) inline
Definition at line 33 of file ConcatOp.h.
    : Operation(Type::concat, args), _axis(axis)
  {
    inferOutputTypes();
  }
Member Function Documentation
copyWithInputs()
Operation * mir::ops::ConcatOp::copyWithInputs (const std::vector< Output * > & inputs) inline override virtual
Implements mir::Operation.
Definition at line 39 of file ConcatOp.h.
  {
    return new ConcatOp(inputs, _axis);
  };
getAxis()
int32_t mir::ops::ConcatOp::getAxis () const inline
Definition at line 44 of file ConcatOp.h.
  {
    if (_axis < 0)
    {
      // Negative axis is used to index starting from the last element of the shape
      // -1 means last element, -2 means second from end, like in python
      int32_t res = _axis + getInputShape(0).rank();
      assert(res >= 0);
      return res;
    }
    return _axis;
  }
References mir::Operation::getInputShape(), and mir::Shape::rank().
Referenced by mir_interpreter::MIRInterpreter::visit(), mir2loco::Transformer::visit(), nnc::AclCppOpGenerator::visit(), nnc::Serializer::visit(), and mir::DotNodeBuilder::visit().
The documentation for this class was generated from the following files:
compiler/mir/include/mir/ops/ConcatOp.h
compiler/mir/src/ops/ConcatOp.cpp