ONE - On-device Neural Engine: locoex::TFLConcatenation Class Reference
locoex::TFLConcatenation Class Reference final
CONCATENATION in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
TFLConcatenation (uint32_t arity)
uint32_t numValues (void) const
Node * values (uint32_t index) const
void values (uint32_t index, Node *node)
uint32_t axis (void) const
void axis (uint32_t axis)
Public Member Functions inherited from locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::CONCATENATION >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFLOpcode opcode (void) const =0
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >
TFLNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >
loco::Use * at (uint32_t n) const
Detailed Description
CONCATENATION in TensorFlow Lite.
Definition at line 158 of file TFLNodes.h.
Constructor & Destructor Documentation
TFLConcatenation()
locoex::TFLConcatenation::TFLConcatenation (uint32_t arity) inline
Definition at line 162 of file TFLNodes.h.
                                   : VariadicArityNode<TFLNodeImpl<TFLOpcode::CONCATENATION>>(arity)
  {
    // TODO Support when arity is 0
    assert(arity >= 1);
  }
References locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >::arity().
Member Function Documentation
axis() [1/2]
void locoex::TFLConcatenation::axis (uint32_t axis) inline
Definition at line 185 of file TFLNodes.h.
{ _axis = axis; }
References axis().
Referenced by axis().
axis() [2/2]
uint32_t locoex::TFLConcatenation::axis (void) const inline
Definition at line 184 of file TFLNodes.h.
{ return _axis; }
Referenced by exo::MergeConcatNodesPass::run().
numValues()
uint32_t locoex::TFLConcatenation::numValues (void) const inline
Definition at line 169 of file TFLNodes.h.
{ return arity(); }
References locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >::arity().
Referenced by values().
values() [1/2]
Node * locoex::TFLConcatenation::values (uint32_t index) const inline
Definition at line 172 of file TFLNodes.h.
  {
    assert(index < numValues());
    return at(index)->node();
  }
References locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >::at(), loco::Use::node(), and numValues().
Referenced by exo::TensorConcatConverter::convert().
values() [2/2]
void locoex::TFLConcatenation::values (uint32_t index, Node * node) inline
Definition at line 177 of file TFLNodes.h.
  {
    assert(index < numValues());
    at(index)->node(node);
  }
References locoex::VariadicArityNode< TFLNodeImpl< TFLOpcode::CONCATENATION > >::at(), loco::Use::node(), and numValues().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h