ONE - On-device Neural Engine: locoex::CircleInstanceNorm Class Reference
locoex::CircleInstanceNorm Class Reference final
INSTANCE_NORM in circle.
#include <CircleNodes.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * gamma (void) const
void gamma (loco::Node *node)
loco::Node * beta (void) const
void beta (loco::Node *node)
float epsilon () const
void epsilon (float epsilon)
Public Member Functions inherited from locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::CircleNodeImpl< CircleOpcode::INSTANCE_NORM >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from locoex::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::CircleNodeMixin< CircleNodeTrait::FusedActFunc >
CircleNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >
loco::Use * at (unsigned n) const
Detailed Description
INSTANCE_NORM in circle.
Definition at line 55 of file CircleNodes.h.
Member Function Documentation
beta() [1/2]
void locoex::CircleInstanceNorm::beta (loco::Node * node) inline
Definition at line 68 of file CircleNodes.h.
{ at(2)->node(node); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
beta() [2/2]
loco::Node * locoex::CircleInstanceNorm::beta (void) const inline
Definition at line 67 of file CircleNodes.h.
{ return at(2)->node(); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
epsilon() [1/2]
float locoex::CircleInstanceNorm::epsilon () const inline
Definition at line 70 of file CircleNodes.h.
{ return _epsilon; }
epsilon() [2/2]
void locoex::CircleInstanceNorm::epsilon (float epsilon) inline
Definition at line 71 of file CircleNodes.h.
{ _epsilon = epsilon; }
References epsilon().
Referenced by epsilon().
gamma() [1/2]
void locoex::CircleInstanceNorm::gamma (loco::Node * node) inline
Definition at line 65 of file CircleNodes.h.
{ at(1)->node(node); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
gamma() [2/2]
loco::Node * locoex::CircleInstanceNorm::gamma (void) const inline
Definition at line 64 of file CircleNodes.h.
{ return at(1)->node(); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
input() [1/2]
void locoex::CircleInstanceNorm::input (loco::Node * node) inline
Definition at line 62 of file CircleNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * locoex::CircleInstanceNorm::input (void) const inline
Note
Currently only support FLOAT32 as input node
Definition at line 61 of file CircleNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 3, CircleNodeImpl< CircleOpcode::INSTANCE_NORM > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/CircleNodes.h