ONE - On-device Neural Engine: nnkit::support::tf::Backend Class Reference
nnkit::support::tf::Backend Class Reference final
#include <Backend.h>
Public Member Functions
Backend ()=delete
Backend (const Backend &)=delete
Backend (Backend &&)=delete
Backend (const char *pb_path, const char *info_path)
void prepare (const std::function< void(nnkit::TensorContext &)> &f) override
void run (void) override
void teardown (const std::function< void(nnkit::TensorContext &)> &f) override
Public Member Functions inherited from nnkit::Backend
virtual ~Backend ()=default
virtual void prepare (const std::function< void(TensorContext &)> &f)=0
virtual void run (void)=0
virtual void teardown (const std::function< void(TensorContext &)> &f)=0
Detailed Description
Definition at line 39 of file Backend.h.
Constructor & Destructor Documentation
Backend() [1/4]
nnkit::support::tf::Backend::Backend () delete
Backend() [2/4]
nnkit::support::tf::Backend::Backend (const Backend &) delete
Backend() [3/4]
nnkit::support::tf::Backend::Backend (Backend &&) delete
Backend() [4/4]
Backend::Backend (const char * pb_path, const char * info_path)
Definition at line 40 of file Backend.cpp.
                                                           : _tf_runner(pb_path)
{
  auto parsed_tensors = nnkit::support::tftestinfo::parse(info_path);
  for (auto &parsed_tensor : parsed_tensors)
  {
    if (parsed_tensor->kind() == ParsedTensor::Kind::Input)
    {
      // user didn't specify input
      if (!parsed_tensor->hasShape())
      {
        angkor::TensorShape shape;
        if (!_tf_runner.getTensorShapeFromGraphDef(parsed_tensor, shape))
          throw oops::UserExn(
            "Info you provided may be wrong or not enough. Please check the info file.");
        parsed_tensor->mutable_shape().resize(shape.rank());
        for (int r = 0; r < shape.rank(); r++)
        {
          parsed_tensor->mutable_shape().dim(r) = shape.dim(r);
        }
      }
      _inputs.emplace_back(std::move(parsed_tensor));
    }
    else
      _outputs.emplace_back(std::move(parsed_tensor));
  }
}
References nncc::core::ADT::tensor::Shape::dim(), nnkit::support::tf::Runner::getTensorShapeFromGraphDef(), nnkit::support::tftestinfo::ParsedTensor::Input, nnkit::support::tftestinfo::parse(), and nncc::core::ADT::tensor::Shape::rank().
Member Function Documentation
prepare()
void Backend::prepare (const std::function< void(nnkit::TensorContext &)> & f) override
Definition at line 68 of file Backend.cpp.
{
  for (const auto &input_tensor : _inputs)
    _data_map.allocate(input_tensor.get());
  TensorContext ctx(_inputs, _data_map);
  f(ctx); // fill values
  _tf_runner.prepareInputs(_inputs, _data_map);
  _tf_runner.prepareOutputs(_outputs);
}
References nnkit::support::tf::TensorDataMap::allocate(), nnkit::support::tf::Runner::prepareInputs(), and nnkit::support::tf::Runner::prepareOutputs().
run()
void Backend::run (void) override virtual
Implements nnkit::Backend.
Definition at line 80 of file Backend.cpp.
{
  _tf_runner.run();
  // get result
  auto actual_outputs = _tf_runner.output();
  for (int n = 0; n < _outputs.size(); n++)
  {
    auto actual = actual_outputs[n];
    const size_t byte_size = TF_TensorByteSize(actual);
    const uint8_t *tf_data = reinterpret_cast<const uint8_t *>(TF_TensorData(actual));
    const uint32_t shape_rank = TF_NumDims(actual);
    _outputs[n]->mutable_shape().resize(shape_rank);
    for (uint32_t r = 0; r < shape_rank; r++)
    {
      _outputs[n]->mutable_shape().dim(r) = TF_Dim(actual, r);
    }
    uint8_t *dest = _data_map.allocate(_outputs[n].get());
    std::memcpy(dest, tf_data, byte_size);
  }
}
References nnkit::support::tf::TensorDataMap::allocate(), nnkit::support::tf::Runner::output(), and nnkit::support::tf::Runner::run().
teardown()
void Backend::teardown (const std::function< void(nnkit::TensorContext &)> & f) override
Definition at line 105 of file Backend.cpp.
{
  TensorContext ctx(_outputs, _data_map);
  f(ctx);
}
The documentation for this class was generated from the following files:
compiler/nnkit-tf/support/include/nnkit/support/tf/Backend.h
compiler/nnkit-tf/support/src/Backend.cpp