ONE - On-device Neural Engine: onert::backend::cpu::ops::TileLayer Class Reference
onert::backend::cpu::ops::TileLayer Class Reference
#include <TileLayer.h>
Public Member Functions
TileLayer ()
void tileFloat32 ()
void tileQuant8 ()
void configure (const IPortableTensor *input, const IPortableTensor *_multipliers, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 33 of file TileLayer.h.
Constructor & Destructor Documentation
TileLayer()
onert::backend::cpu::ops::TileLayer::TileLayer ()
Definition at line 32 of file TileLayer.cc.
                     : _input(nullptr), _multipliers(nullptr), _output(nullptr)
{
  // DO NOTHING
}
Member Function Documentation
configure()
void onert::backend::cpu::ops::TileLayer::configure (const IPortableTensor * input, const IPortableTensor * _multipliers, IPortableTensor * output)
Definition at line 49 of file TileLayer.cc.
{
  _input = input;
  _multipliers = multipliers;
  _output = output;
}
run()
void onert::backend::cpu::ops::TileLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 57 of file TileLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    tileFloat32();
  }
  else if (_input->data_type() == OperandType::QUANT_UINT8_ASYMM)
  {
    tileQuant8();
  }
  else
  {
    throw std::runtime_error{"Tile: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), tileFloat32(), and tileQuant8().
tileFloat32()
void onert::backend::cpu::ops::TileLayer::tileFloat32 ()
Definition at line 37 of file TileLayer.cc.
{
  TileOneDimension(getShape(_input), getBuffer<float>(_input), getBuffer<int>(_multipliers),
                   getBuffer<float>(_output), 0);
}
References onert::backend::cpu::ops::getShape().
Referenced by run().
tileQuant8()
void onert::backend::cpu::ops::TileLayer::tileQuant8 ()
Definition at line 43 of file TileLayer.cc.
{
  // cker quant8 tile is not implemented yet
  throw std::runtime_error{"NYI"};
}
Referenced by run().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/TileLayer.h
runtime/onert/backend/cpu/ops/TileLayer.cc