ONE - On-device Neural Engine: luci_interpreter::kernels::StridedSlice Class Reference
luci_interpreter::kernels::StridedSlice Class Reference
#include <StridedSlice.h>
Public Member Functions
StridedSlice (const Tensor *input, const Tensor *begin, const Tensor *end, const Tensor *strides, Tensor *output, const StridedSliceParams &params)
const Tensor * input () const
const Tensor * begin () const
const Tensor * end () const
const Tensor * strides () const
Tensor * output () const
void configure () override
void execute () const override
StridedSlice (const Tensor *input, const Tensor *begin, const Tensor *end, const Tensor *strides, Tensor *output, const StridedSliceParams &params)
const Tensor * input () const
const Tensor * begin () const
const Tensor * end () const
const Tensor * strides () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::KernelWithParams< StridedSliceParams >
const StridedSliceParams & params () const
const StridedSliceParams & params () const
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::KernelWithParams< StridedSliceParams >
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const StridedSliceParams &params)
KernelWithParams (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs, const StridedSliceParams &params)
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::KernelWithParams< StridedSliceParams >
const StridedSliceParams _params
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 28 of file StridedSlice.h.
Constructor & Destructor Documentation
StridedSlice() [1/2]
luci_interpreter::kernels::StridedSlice::StridedSlice (const Tensor * input, const Tensor * begin, const Tensor * end, const Tensor * strides, Tensor * output, const StridedSliceParams & params)
Definition at line 32 of file StridedSlice.cpp.
  : KernelWithParams<StridedSliceParams>({input, begin, end, strides}, {output}, params)
{
}
References begin(), end(), input(), and strides().
StridedSlice() [2/2]
luci_interpreter::kernels::StridedSlice::StridedSlice (const Tensor * input, const Tensor * begin, const Tensor * end, const Tensor * strides, Tensor * output, const StridedSliceParams & params)
Member Function Documentation
begin() [1/2]
const Tensor * luci_interpreter::kernels::StridedSlice::begin () const inline
Definition at line 35 of file StridedSlice.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and StridedSlice().
begin() [2/2]
const Tensor * luci_interpreter::kernels::StridedSlice::begin () const inline
Definition at line 35 of file StridedSlice.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::StridedSlice::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 38 of file StridedSlice.cpp.
{
  assert(begin()->shape().num_dims() == 1);
  assert(end()->shape().num_dims() == 1);
  assert(strides()->shape().num_dims() == 1);
  assert(input()->element_type() == output()->element_type());
  assert(begin()->element_type() == DataType::S32);
  assert(end()->element_type() == DataType::S32);
  assert(strides()->element_type() == DataType::S32);
  assert(input()->shape().num_dims() <= 4);
  if (params().ellipsis_mask != 0)
  {
    throw std::runtime_error("ellipsis_mask is not implemented yet.");
  }
  if (params().new_axis_mask != 0)
  {
    throw std::runtime_error("new_axis_mask is not implemented yet.");
  }
  if (input()->element_type() == DataType::U8)
  {
    assert(input()->scale() == output()->scale());
    assert(input()->zero_point() == output()->zero_point());
  }
  tflite::StridedSliceParams op_params{};
  op_params.start_indices_count = input()->shape().num_dims();
  op_params.stop_indices_count = input()->shape().num_dims();
  op_params.strides_count = input()->shape().num_dims();
  for (int i = 0; i < input()->shape().num_dims(); i++)
  {
    op_params.start_indices[i] = getTensorData<int32_t>(begin())[i];
    op_params.stop_indices[i] = getTensorData<int32_t>(end())[i];
    op_params.strides[i] = getTensorData<int32_t>(strides())[i];
  }
  op_params.begin_mask = params().begin_mask;
  op_params.ellipsis_mask = 0;
  op_params.end_mask = params().end_mask;
  op_params.new_axis_mask = 0;
  op_params.shrink_axis_mask = params().shrink_axis_mask;
  std::vector<int32_t> output_shape_vector;
  for (int i = 0; i < input()->shape().num_dims(); i++)
  {
    int idx = input()->shape().num_dims() - i - 1;
    int32_t stride = getTensorData<int32_t>(strides())[idx];
    assert(stride != 0);
    int32_t begin = ::tflite::strided_slice::StartForAxis(op_params, getTensorShape(input()), idx);
    int32_t end =
      ::tflite::strided_slice::StopForAxis(op_params, getTensorShape(input()), idx, begin);
    const bool shrink_axis = params().shrink_axis_mask & (1 << idx);
    if (shrink_axis)
    {
      end = begin + 1;
    }
    int32_t dim_shape = std::ceil((end - begin) / static_cast<float>(stride));
    dim_shape = dim_shape < 0 ? 0 : dim_shape;
    if (!shrink_axis)
    {
      output_shape_vector.push_back(dim_shape);
    }
  }
  Shape output_shape = Shape(output_shape_vector.size());
  for (size_t i = 0; i < output_shape_vector.size(); i++)
  {
    output_shape.dim(i) = output_shape_vector[output_shape_vector.size() - i - 1];
  }
  output()->resize(output_shape);
}
References begin(), luci_interpreter::StridedSliceParams::begin_mask, end(), luci_interpreter::StridedSliceParams::end_mask, luci_interpreter::kernels::getTensorShape(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< StridedSliceParams >::params(), luci_interpreter::Tensor::resize(), luci_interpreter::Tensor::shape(), luci_interpreter::StridedSliceParams::shrink_axis_mask, and strides().
configure() [2/2]
void luci_interpreter::kernels::StridedSlice::configure () override virtual
Implements luci_interpreter::Kernel.
end() [1/2]
const Tensor * luci_interpreter::kernels::StridedSlice::end () const inline
Definition at line 36 of file StridedSlice.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and StridedSlice().
end() [2/2]
const Tensor * luci_interpreter::kernels::StridedSlice::end () const inline
Definition at line 36 of file StridedSlice.h.
{ return _inputs[2]; }
References luci_interpreter::Kernel::_inputs.
execute() [1/2]
void luci_interpreter::kernels::StridedSlice::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 108 of file StridedSlice.cpp.
{
  tflite::StridedSliceParams op_params{};
  op_params.start_indices_count = input()->shape().num_dims();
  op_params.stop_indices_count = input()->shape().num_dims();
  op_params.strides_count = input()->shape().num_dims();
  for (int i = 0; i < input()->shape().num_dims(); i++)
  {
    op_params.start_indices[i] = getTensorData<int32_t>(begin())[i];
    op_params.stop_indices[i] = getTensorData<int32_t>(end())[i];
    op_params.strides[i] = getTensorData<int32_t>(strides())[i];
  }
  op_params.begin_mask = params().begin_mask;
  op_params.ellipsis_mask = 0;
  op_params.end_mask = params().end_mask;
  op_params.new_axis_mask = 0;
  op_params.shrink_axis_mask = params().shrink_axis_mask;
  switch (input()->element_type())
  {
    case DataType::FLOAT32:
      tflite::reference_ops::StridedSlice(op_params, getTensorShape(input()),
                                          getTensorData<float>(input()), getTensorShape(output()),
                                          getTensorData<float>(output()));
      break;
    case DataType::U8:
      tflite::reference_ops::StridedSlice(op_params, getTensorShape(input()),
                                          getTensorData<uint8_t>(input()), getTensorShape(output()),
                                          getTensorData<uint8_t>(output()));
      break;
    case DataType::S32:
      tflite::reference_ops::StridedSlice(op_params, getTensorShape(input()),
                                          getTensorData<int32_t>(input()), getTensorShape(output()),
                                          getTensorData<int32_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported type.");
  }
}
References begin(), luci_interpreter::StridedSliceParams::begin_mask, end(), luci_interpreter::StridedSliceParams::end_mask, luci_interpreter::kernels::getTensorShape(), input(), luci_interpreter::Shape::num_dims(), output(), luci_interpreter::KernelWithParams< StridedSliceParams >::params(), luci_interpreter::Tensor::shape(), luci_interpreter::StridedSliceParams::shrink_axis_mask, and strides().
execute() [2/2]
void luci_interpreter::kernels::StridedSlice::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::StridedSlice::input () const inline
Definition at line 34 of file StridedSlice.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and StridedSlice().
input() [2/2]
const Tensor * luci_interpreter::kernels::StridedSlice::input () const inline
Definition at line 34 of file StridedSlice.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::StridedSlice::output () const inline
Definition at line 38 of file StridedSlice.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::StridedSlice::output () const inline
Definition at line 38 of file StridedSlice.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
strides() [1/2]
const Tensor * luci_interpreter::kernels::StridedSlice::strides () const inline
Definition at line 37 of file StridedSlice.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and StridedSlice().
strides() [2/2]
const Tensor * luci_interpreter::kernels::StridedSlice::strides () const inline
Definition at line 37 of file StridedSlice.h.
{ return _inputs[3]; }
References luci_interpreter::Kernel::_inputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/StridedSlice.h
onert-micro/luci-interpreter/src/kernels/StridedSlice.h
compiler/luci-interpreter/src/kernels/StridedSlice.cpp
onert-micro/luci-interpreter/src/kernels/StridedSlice.cpp