ONE - On-device Neural Engine: GraphTestcase< GraphCode::TensorTranspose > Class Reference
GraphTestcase< GraphCode::TensorTranspose > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase ()
loco::Graph * graph ()
Data Fields
loco::Pull * pull_node = nullptr
loco::TensorTranspose * transpose_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 495 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::TensorTranspose >::GraphTestcase () inline
Definition at line 498 of file GraphTestcase.h.
  {
    using namespace loco;
    // Create a sample network
    _graph = make_graph();
    // Create Graph Input/Output
    auto graph_input = _graph->inputs()->create();
    auto graph_output = _graph->outputs()->create();
    graph_input->name("input");
    graph_output->name("output");
    // Create and connect nodes
    pull_node = _graph->nodes()->create<Pull>();
    pull_node->index(0);
    transpose_node = _graph->nodes()->create<TensorTranspose>();
    transpose_node->input(pull_node);
    push_node = _graph->nodes()->create<loco::Push>();
    push_node->index(0);
    push_node->from(transpose_node);
    // Create a link between input/output and corresponding nodes
    loco::link(graph_input, pull_node);
    loco::link(graph_output, push_node);
  }
References loco::Push::from(), loco::Pull::index(), loco::Push::index(), loco::TensorTranspose::input(), and loco::link().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::TensorTranspose >::graph () inline
Definition at line 529 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
pull_node
loco::Pull* GraphTestcase< GraphCode::TensorTranspose >::pull_node = nullptr
Definition at line 531 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::TensorTranspose >::push_node = nullptr
Definition at line 533 of file GraphTestcase.h.
transpose_node
loco::TensorTranspose* GraphTestcase< GraphCode::TensorTranspose >::transpose_node = nullptr
Definition at line 532 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h