ONE - On-device Neural Engine: onert::backend::cpu::ops::DynamicUpdateSliceLayer Class Reference
onert::backend::cpu::ops::DynamicUpdateSliceLayer Class Reference
#include <DynamicUpdateSliceLayer.h>
Public Member Functions
DynamicUpdateSliceLayer ()
~DynamicUpdateSliceLayer ()
void configure (const IPortableTensor *operand, const IPortableTensor *update, const IPortableTensor *indices, IPortableTensor *output)
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void prepare ()
Detailed Description
Definition at line 28 of file DynamicUpdateSliceLayer.h.
Constructor & Destructor Documentation
DynamicUpdateSliceLayer()
onert::backend::cpu::ops::DynamicUpdateSliceLayer::DynamicUpdateSliceLayer ()
Definition at line 25 of file DynamicUpdateSliceLayer.cc.
  : _operand(nullptr), _update(nullptr), _indices(nullptr), _output(nullptr)
{
  // DO NOTHING
}
~DynamicUpdateSliceLayer()
onert::backend::cpu::ops::DynamicUpdateSliceLayer::~DynamicUpdateSliceLayer () default
Member Function Documentation
configure()
void onert::backend::cpu::ops::DynamicUpdateSliceLayer::configure (const IPortableTensor * operand, const IPortableTensor * update, const IPortableTensor * indices, IPortableTensor * output)
Definition at line 33 of file DynamicUpdateSliceLayer.cc.
{
  assert(operand != nullptr);
  assert(update != nullptr);
  assert(indices != nullptr);
  assert(output != nullptr);
  _operand = operand;
  _update = update;
  _indices = indices;
  _output = output;
}
run()
void onert::backend::cpu::ops::DynamicUpdateSliceLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 48 of file DynamicUpdateSliceLayer.cc.
{
  // Get indices data as int64 type vector
  std::vector<int64_t> indices_data(_indices->getShape().num_elements());
  for (size_t i = 0; i < indices_data.size(); ++i)
  {
    if (_indices->data_type() == OperandType::INT32)
    {
      indices_data[i] = static_cast<int64_t>(getBuffer<int32_t>(_indices)[i]);
    }
    else
    {
      assert(_indices->data_type() == OperandType::INT64);
      indices_data[i] = getBuffer<int64_t>(_indices)[i];
    }
  }
  switch (_operand->data_type())
  {
    case OperandType::FLOAT32:
      nnfw::cker::DynamicUpdateSlice()(getShape(_operand), getBuffer<float>(_operand),
                                       getShape(_update), getBuffer<float>(_update), indices_data,
                                       getBuffer<float>(_output));
      break;
    case OperandType::QUANT_UINT8_ASYMM:
      nnfw::cker::DynamicUpdateSlice()(getShape(_operand), getBuffer<uint8_t>(_operand),
                                       getShape(_update), getBuffer<uint8_t>(_update), indices_data,
                                       getBuffer<uint8_t>(_output));
      break;
    case OperandType::QUANT_INT16_SYMM:
      nnfw::cker::DynamicUpdateSlice()(getShape(_operand), getBuffer<int8_t>(_operand),
                                       getShape(_update), getBuffer<int8_t>(_update), indices_data,
                                       getBuffer<int8_t>(_output));
      break;
    default:
      throw std::runtime_error{"DynamicUpdateSlice: NYI - unsupported data type"};
      break;
  }
}
References onert::backend::IPortableTensor::data_type(), onert::backend::IPortableTensor::getShape(), and onert::backend::cpu::ops::getShape().
The documentation for this class was generated from the following files:
runtime/onert/backend/cpu/ops/DynamicUpdateSliceLayer.h
runtime/onert/backend/cpu/ops/DynamicUpdateSliceLayer.cc