ONE - On-device Neural Engine: tflite2circle::CircleModel Class Reference
tflite2circle::CircleModel Class Reference
#include <CircleModel.h>
Public Member Functions
CircleModel (void)=delete
CircleModel (FlatBufBuilder &fb, const std::vector< char > &fr)
void load_offsets (const tflite::Model *tfl_model)
void model_build (void) const
void finalize (void)
const char * base (void) const
size_t size (void) const
Detailed Description
Definition at line 93 of file CircleModel.h.
Constructor & Destructor Documentation
CircleModel() [1/2]
tflite2circle::CircleModel::CircleModel (void) delete
CircleModel() [2/2]
tflite2circle::CircleModel::CircleModel (FlatBufBuilder & fb, const std::vector< char > & fr)
Definition at line 413 of file CircleModel.cpp.
  : _version{0}, _description{fb->CreateString("ONE-tflite2circle")}, _fb{fb}, _file_raw{fr}
{
  // NOTHING TODO
}
Member Function Documentation
base()
const char * tflite2circle::CircleModel::base (void) const
Definition at line 509 of file CircleModel.cpp.
{
  if (_buffer_data_map.empty())
    return reinterpret_cast<const char *>(_fb->GetBufferPointer());
  return reinterpret_cast<const char *>(_fb_data_with_ext.data());
}
finalize()
void tflite2circle::CircleModel::finalize (void)
Definition at line 451 of file CircleModel.cpp.
{
  if (_buffer_data_map.empty())
    return;
  auto align16 = [](size_t &v) {
    while (v % 16 != 0)
      v++;
  };
  // get total memory for flatbuffer + all buffer_data
  size_t result_size = _fb->GetSize();
  align16(result_size);
  for (auto &it : _buffer_data_map)
  {
    BufferData &buffer_data = it.second;
    result_size += buffer_data.size();
    align16(result_size);
  }
  align16(result_size);
  result_size += 16; // for safety
  std::string result;
  const char *buff_ptr = reinterpret_cast<const char *>(_fb->GetBufferPointer());
  auto padalign16 = [](std::string &str) {
    while (str.size() % 16 != 0)
      str += '\0';
  };
  result.reserve(result_size);
  result.append(buff_ptr, _fb->GetSize());
  auto mutable_model = circle::GetMutableModel(result.data());
  auto mutable_buffers = mutable_model->mutable_buffers();
  // pad to be 16 bytes aligned
  padalign16(result);
  for (auto &it : _buffer_data_map)
  {
    int32_t buffer_index = it.first;
    BufferData &buffer_data = it.second;
    uint64_t offset = result.size();
    uint64_t size = buffer_data.size();
    circle::Buffer *mutable_buffer = mutable_buffers->GetMutableObject(buffer_index);
    mutable_buffer->mutate_offset(offset);
    mutable_buffer->mutate_size(size);
    result.append(buffer_data.begin(), buffer_data.end());
    padalign16(result);
  }
  padalign16(result);
  // use final result
  _fb_data_with_ext = result;
}
References offset(), and size().
load_offsets()
void tflite2circle::CircleModel::load_offsets (const tflite::Model * tfl_model)
Definition at line 419 of file CircleModel.cpp.
{
  _operator_codes_offset = std::make_unique<Offset<OperatorCodeLink>>(_fb);
  _subGraphs_offset = std::make_unique<Offset<SubGraphLink>>(_fb);
  _buffers_offset = std::make_unique<Offset<BufferLink>>(_fb);
  _metadata_buffer_offset = std::make_unique<Offset<MetaDataBufferLink>>(_fb);
  _subGraphs_offset->set_signature_defs(tfl_model->signature_defs());
  _buffers_offset->set_buffer_data_map(&_buffer_data_map);
  _buffers_offset->set_file_raw(&_file_raw);
  _operator_codes_offset->build(tfl_model->operator_codes());
  _subGraphs_offset->build(tfl_model->subgraphs());
  _buffers_offset->build(tfl_model->buffers());
  _metadata_buffer_offset->build(tfl_model->metadata_buffer());
}
model_build()
void tflite2circle::CircleModel::model_build (void) const
Definition at line 436 of file CircleModel.cpp.
{
  circle::ModelBuilder model_builder{*_fb};
  model_builder.add_version(_version);
  model_builder.add_description(_description);
  model_builder.add_operator_codes(_operator_codes_offset->offset());
  model_builder.add_subgraphs(_subGraphs_offset->offset());
  model_builder.add_buffers(_buffers_offset->offset());
  model_builder.add_metadata_buffer(_metadata_buffer_offset->offset());
  auto model = model_builder.Finish();
  circle::FinishModelBuffer(*_fb, model);
}
size()
size_t tflite2circle::CircleModel::size (void) const
Definition at line 516 of file CircleModel.cpp.
{
  if (_buffer_data_map.empty())
    return _fb->GetSize();
  return _fb_data_with_ext.size();
}
Referenced by finalize().
The documentation for this class was generated from the following files:
compiler/tflite2circle/include/CircleModel.h
compiler/tflite2circle/src/CircleModel.cpp