ONE - On-device Neural Engine: GraphTestcase< GraphCode::TensorBroadcast > Class Reference
GraphTestcase< GraphCode::TensorBroadcast > Class Reference final
#include <GraphTestcase.h>
Public Member Functions
GraphTestcase (std::initializer_list< uint32_t > dims)
loco::Graph * graph (void)
Data Fields
loco::Pull * pull_node = nullptr
loco::TensorBroadcast * broadcast_node = nullptr
loco::Push * push_node = nullptr
Detailed Description
Definition at line 470 of file GraphTestcase.h.
Constructor & Destructor Documentation
GraphTestcase()
GraphTestcase< GraphCode::TensorBroadcast >::GraphTestcase (std::initializer_list< uint32_t > dims) inline
Definition at line 473 of file GraphTestcase.h.
  {
    _graph = loco::make_graph();
    auto graph_builder = make_graph_builder(_graph.get());
    pull_node = graph_builder->push<InputLayer>()->name("input")->shape(dims)->node();
    broadcast_node = graph_builder->push<TensorBroadcastLayer>()->node();
    push_node = graph_builder->push<OutputLayer>()->name("output")->node();
  }
References loco::make_graph().
Member Function Documentation
graph()
loco::Graph * GraphTestcase< GraphCode::TensorBroadcast >::graph (void) inline
Definition at line 485 of file GraphTestcase.h.
{ return _graph.get(); }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
Field Documentation
broadcast_node
loco::TensorBroadcast* GraphTestcase< GraphCode::TensorBroadcast >::broadcast_node = nullptr
Definition at line 488 of file GraphTestcase.h.
pull_node
loco::Pull* GraphTestcase< GraphCode::TensorBroadcast >::pull_node = nullptr
Definition at line 487 of file GraphTestcase.h.
push_node
loco::Push* GraphTestcase< GraphCode::TensorBroadcast >::push_node = nullptr
Definition at line 489 of file GraphTestcase.h.
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphTestcase.h