ONE - On-device Neural Engine: nnkit::support::tflite::AbstractBackend Class Reference
nnkit::support::tflite::AbstractBackend Class Reference abstract
#include <AbstractBackend.h>
Public Member Functions
virtual ~AbstractBackend ()=default
virtual ::tflite::Interpreter & interpreter (void)=0
void prepare (const std::function< void(TensorContext &)> &f) override
void run (void) override
void teardown (const std::function< void(TensorContext &)> &f) override
Public Member Functions inherited from nnkit::Backend
virtual ~Backend ()=default
virtual void prepare (const std::function< void(TensorContext &)> &f)=0
virtual void run (void)=0
virtual void teardown (const std::function< void(TensorContext &)> &f)=0
Detailed Description
Definition at line 30 of file AbstractBackend.h.
Constructor & Destructor Documentation
~AbstractBackend()
virtual nnkit::support::tflite::AbstractBackend::~AbstractBackend () virtual default
Member Function Documentation
interpreter()
virtual ::tflite::Interpreter & nnkit::support::tflite::AbstractBackend::interpreter (void) pure virtual
Implemented in ConvBackend.
Referenced by prepare(), run(), and teardown().
prepare()
void nnkit::support::tflite::AbstractBackend::prepare (const std::function< void(TensorContext &)> & f) override
Definition at line 32 of file Backend.cpp.
{
  ensure(interpreter().AllocateTensors());
  InputTensorSet inputs(interpreter());
  TensorContext ctx(inputs);
  f(ctx);
}
References interpreter().
run()
void nnkit::support::tflite::AbstractBackend::run (void) override virtual
Implements nnkit::Backend.
Definition at line 41 of file Backend.cpp.
{ ensure(interpreter().Invoke()); }
References interpreter().
teardown()
void nnkit::support::tflite::AbstractBackend::teardown (const std::function< void(TensorContext &)> & f) override
Definition at line 43 of file Backend.cpp.
{
  OutputTensorSet outputs(interpreter());
  TensorContext ctx(outputs);
  f(ctx);
}
References interpreter().
The documentation for this class was generated from the following files:
compiler/nnkit-tflite/support/include/nnkit/support/tflite/AbstractBackend.h
compiler/nnkit-tflite/support/src/Backend.cpp