ONE - On-device Neural Engine: luci_interpreter::kernels::ReverseV2 Class Reference
luci_interpreter::kernels::ReverseV2 Class Reference
#include <ReverseV2.h>
Public Member Functions
ReverseV2 (const Tensor *input, const Tensor *axes, Tensor *output)
const Tensor * input () const
const Tensor * axes () const
Tensor * output () const
void configure () override
void execute () const override
ReverseV2 (const Tensor *input, const Tensor *axes, Tensor *output)
const Tensor * input () const
const Tensor * axes () const
Tensor * output () const
void configure () override
void execute () const override
Public Member Functions inherited from luci_interpreter::Kernel
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
virtual ~Kernel ()=default
const std::vector< const Tensor * > & getInputTensors () const
const std::vector< Tensor * > & getOutputTensors () const
virtual void configure ()=0
virtual void execute () const =0
void setInplaceValue (bool is_inplace)
bool getInplaceValue () const
Additional Inherited Members
Protected Member Functions inherited from luci_interpreter::Kernel
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Kernel (std::vector< const Tensor * > inputs, std::vector< Tensor * > outputs)
Protected Attributes inherited from luci_interpreter::Kernel
const std::vector< const Tensor * > _inputs
const std::vector< Tensor * > _outputs
bool _is_inplace
Detailed Description
Definition at line 27 of file ReverseV2.h.
Constructor & Destructor Documentation
ReverseV2() [1/2]
luci_interpreter::kernels::ReverseV2::ReverseV2 (const Tensor * input, const Tensor * axes, Tensor * output)
Definition at line 27 of file ReverseV2.cpp.
  : Kernel({input, axes}, {output})
{
}
References axes(), and input().
ReverseV2() [2/2]
luci_interpreter::kernels::ReverseV2::ReverseV2 (const Tensor * input, const Tensor * axes, Tensor * output)
Member Function Documentation
axes() [1/2]
const Tensor * luci_interpreter::kernels::ReverseV2::axes () const inline
Definition at line 33 of file ReverseV2.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ReverseV2().
axes() [2/2]
const Tensor * luci_interpreter::kernels::ReverseV2::axes () const inline
Definition at line 33 of file ReverseV2.h.
{ return _inputs[1]; }
References luci_interpreter::Kernel::_inputs.
configure() [1/2]
void luci_interpreter::kernels::ReverseV2::configure () override virtual
Implements luci_interpreter::Kernel.
Definition at line 32 of file ReverseV2.cpp.
{
  assert(axes()->shape().num_dims() == 1);
  assert(input()->shape().num_dims() >= axes()->shape().num_elements());
  if (input()->element_type() != DataType::S32 && input()->element_type() != DataType::FLOAT32 &&
      input()->element_type() != DataType::U8 && input()->element_type() != DataType::S16 &&
      input()->element_type() != DataType::S64)
  {
    throw std::runtime_error("Unsupported input type.");
  }
  if (axes()->element_type() != DataType::S32)
  {
    throw std::runtime_error("Unsupported axes type.");
  }
  if (axes()->shape().num_elements() > 1)
  {
    throw std::runtime_error("Current implementation does not support more than 1 axis.");
  }
  int axis_value = getTensorData<int32_t>(axes())[0];
  if (axis_value < 0 || axis_value >= input()->shape().num_dims())
  {
    throw std::runtime_error("Invalid axes value");
  }
  assert(input()->element_type() == output()->element_type());
  output()->resize(input()->shape());
}
References axes(), input(), output(), and luci_interpreter::Tensor::resize().
configure() [2/2]
void luci_interpreter::kernels::ReverseV2::configure () override virtual
Implements luci_interpreter::Kernel.
execute() [1/2]
void luci_interpreter::kernels::ReverseV2::execute () const override virtual
Implements luci_interpreter::Kernel.
Definition at line 60 of file ReverseV2.cpp.
{
  int axis_value = getTensorData<int32_t>(axes())[0];
  switch (output()->element_type())
  {
    case DataType::FLOAT32:
      tflite::reference_ops::Reverse<float>(axis_value, getTensorShape(input()),
                                            getTensorData<float>(input()), getTensorShape(output()),
                                            getTensorData<float>(output()));
      break;
    case DataType::U8:
      tflite::reference_ops::Reverse<uint8_t>(
        axis_value, getTensorShape(input()), getTensorData<uint8_t>(input()),
        getTensorShape(output()), getTensorData<uint8_t>(output()));
      break;
    default:
      throw std::runtime_error("Unsupported output type");
  }
}
References axes(), luci_interpreter::kernels::getTensorShape(), input(), and output().
execute() [2/2]
void luci_interpreter::kernels::ReverseV2::execute () const override virtual
Implements luci_interpreter::Kernel.
input() [1/2]
const Tensor * luci_interpreter::kernels::ReverseV2::input () const inline
Definition at line 32 of file ReverseV2.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
Referenced by configure(), execute(), and ReverseV2().
input() [2/2]
const Tensor * luci_interpreter::kernels::ReverseV2::input () const inline
Definition at line 32 of file ReverseV2.h.
{ return _inputs[0]; }
References luci_interpreter::Kernel::_inputs.
output() [1/2]
Tensor * luci_interpreter::kernels::ReverseV2::output () const inline
Definition at line 34 of file ReverseV2.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
Referenced by configure(), and execute().
output() [2/2]
Tensor * luci_interpreter::kernels::ReverseV2::output () const inline
Definition at line 34 of file ReverseV2.h.
{ return _outputs[0]; }
References luci_interpreter::Kernel::_outputs.
The documentation for this class was generated from the following files:
compiler/luci-interpreter/src/kernels/ReverseV2.h
onert-micro/luci-interpreter/src/kernels/ReverseV2.h
compiler/luci-interpreter/src/kernels/ReverseV2.cpp
onert-micro/luci-interpreter/src/kernels/ReverseV2.cpp