ONE - On-device Neural Engine: loco::PermutingEncoder< Domain::Filter > Class Reference
loco::PermutingEncoder< Domain::Filter > Class Reference final
Permutation-based Tensor-to-Filter converter.
#include <PermutingCodec.h>
Public Member Functions
PermutingEncoder ()=default
PermutingEncoder (const Permutation< Domain::Filter > &perm)
bool valid (void) const
FilterShape shape (const TensorShape &tensor_shape) const override
TensorIndex value (const FilterIndex &index) const override
const Permutation< Domain::Filter > * perm (void) const
Permutation< Domain::Filter > * perm (void)
void perm (const Permutation< Domain::Filter > &p)
Public Member Functions inherited from loco::FilterEncoder
virtual ~FilterEncoder ()=default
virtual FilterShape shape (const TensorShape &shape) const =0
virtual TensorIndex value (const FilterIndex &index) const =0
Detailed Description
Permutation-based Tensor-to-Filter converter.
Definition at line 172 of file PermutingCodec.h.
Constructor & Destructor Documentation
PermutingEncoder() [1/2]
loco::PermutingEncoder< Domain::Filter >::PermutingEncoder () default
PermutingEncoder() [2/2]
loco::PermutingEncoder< Domain::Filter >::PermutingEncoder (const Permutation< Domain::Filter > & perm) inline explicit
Definition at line 178 of file PermutingCodec.h.
                                                                   : _perm{perm}
  {
    // DO NOTHING
  }
Member Function Documentation
perm() [1/3]
void loco::PermutingEncoder< Domain::Filter >::perm (const Permutation< Domain::Filter > & p) inline
Definition at line 193 of file PermutingCodec.h.
{ _perm = p; }
perm() [2/3]
Permutation< Domain::Filter > * loco::PermutingEncoder< Domain::Filter >::perm (void) inline
Definition at line 192 of file PermutingCodec.h.
{ return &_perm; }
perm() [3/3]
const Permutation< Domain::Filter > * loco::PermutingEncoder< Domain::Filter >::perm (void) const inline
Definition at line 191 of file PermutingCodec.h.
{ return &_perm; }
shape()
FilterShape loco::PermutingEncoder< Domain::Filter >::shape (const TensorShape & tensor_shape) const override virtual
Implements loco::FilterEncoder.
Definition at line 273 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  FilterShape out;
  out.count() = in.dim(_perm[FilterAxis::Count]);
  out.depth() = in.dim(_perm[FilterAxis::Depth]);
  out.height() = in.dim(_perm[FilterAxis::Height]);
  out.width() = in.dim(_perm[FilterAxis::Width]);
  return out;
}
References loco::Count, loco::FilterShape::count(), loco::Depth, loco::FilterShape::depth(), loco::TensorShape::dim(), loco::Height, loco::FilterShape::height(), loco::valid(), loco::Width, and loco::FilterShape::width().
valid()
bool loco::PermutingEncoder< Domain::Filter >::valid (void) const
Definition at line 303 of file PermutingCodec.cpp.
{ return ::valid(_perm); }
value()
TensorIndex loco::PermutingEncoder< Domain::Filter >::value (const FilterIndex & index) const override virtual
Implements loco::FilterEncoder.
Definition at line 287 of file PermutingCodec.cpp.
{
  assert(valid() && "invalid permutation");
  TensorIndex out;
  out.resize(4);
  out.at(_perm[FilterAxis::Count]) = in.nth();
  out.at(_perm[FilterAxis::Depth]) = in.channel();
  out.at(_perm[FilterAxis::Height]) = in.row();
  out.at(_perm[FilterAxis::Width]) = in.column();
  return out;
}
References nncc::core::ADT::tensor::Index::at(), loco::FilterIndex::channel(), loco::FilterIndex::column(), loco::Count, loco::Depth, loco::Height, loco::FilterIndex::nth(), nncc::core::ADT::tensor::Index::resize(), loco::FilterIndex::row(), loco::valid(), and loco::Width.
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp