ONE - On-device Neural Engine: onert::backend::train::ops::ConvolutionLayer Class Reference
onert::backend::train::ops::ConvolutionLayer Class Reference
#include <ConvolutionLayer.h>
Public Member Functions
ConvolutionLayer ()
~ConvolutionLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *weights, const IPortableTensor *bias, IPortableTensor *output, IPortableTensor *back_prop_input, IPortableTensor *grad_weights, IPortableTensor *grad_bias, const IPortableTensor *back_prop_output, ir::PaddingType paddingType, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t dilationWidthFactor, const uint32_t dilationHeightFactor, const ir::Activation activation)
void forward (bool training) override
void backward () override
Public Member Functions inherited from onert::exec::train::ITrainableFunction
virtual ~ITrainableFunction ()=default
virtual void forward (bool training)=0
virtual void backward ()=0
Public Member Functions inherited from onert::backend::cpu::ops::ConvolutionLayer
ConvolutionLayer ()
~ConvolutionLayer ()
void configure (const IPortableTensor *input, const IPortableTensor *kernel, const IPortableTensor *bias, ir::PaddingType _paddingType, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t dilationWidthFactor, const uint32_t dilationHeightFactor, const ir::Activation activation, IPortableTensor *output, bool is_cachable_weights)
void prepare () override
void run () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Additional Inherited Members
Protected Attributes inherited from onert::backend::cpu::ops::ConvolutionLayer
const IPortableTensor * _input
const IPortableTensor * _kernel
const IPortableTensor * _bias
IPortableTensor * _output
ir::PaddingType _paddingType
uint32_t _paddingLeft
uint32_t _paddingTop
uint32_t _paddingRight
uint32_t _paddingBottom
uint32_t _strideWidth
uint32_t _strideHeight
uint32_t _dilationWidthFactor
uint32_t _dilationHeightFactor
ir::Activation _activation
std::unique_ptr< nnfw::cker::Conv > _conv_kernel
std::unique_ptr< nnfw::cker::ConvHybridTempArena > _hybrid_arena
bool _prepare
bool _is_cachable_weights
bool _is_hybrid
Detailed Description
Definition at line 34 of file ConvolutionLayer.h.
Constructor & Destructor Documentation
ConvolutionLayer()
onert::backend::train::ops::ConvolutionLayer::ConvolutionLayer ()
Definition at line 60 of file ConvolutionLayer.cc.
  : cpu::ops::ConvolutionLayer(), _grad_weights{nullptr}, _grad_bias{nullptr},
    _back_prop_input{nullptr}, _back_prop_output{nullptr}, _transposed_weights{nullptr}
{
  // DO NOTHING
}
~ConvolutionLayer()
onert::backend::train::ops::ConvolutionLayer::~ConvolutionLayer () default
Member Function Documentation
backward()
void onert::backend::train::ops::ConvolutionLayer::backward () override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 116 of file ConvolutionLayer.cc.
{
  const auto data_type = _back_prop_output->data_type();
  assert(data_type == _input->data_type());
  switch (data_type)
  {
    case OperandType::FLOAT32:
    {
      assert(data_type == _grad_bias->data_type());
      backwardFloat32();
      break;
    }
    default:
      throw std::runtime_error{"train ConvolutionLayer: unsupported data type"};
  }
}
References onert::backend::cpu::ops::ConvolutionLayer::_input, and onert::backend::ITensor::data_type().
configure()
void onert::backend::train::ops::ConvolutionLayer::configure (const IPortableTensor * input, const IPortableTensor * weights, const IPortableTensor * bias, IPortableTensor * output, IPortableTensor * back_prop_input, IPortableTensor * grad_weights, IPortableTensor * grad_bias, const IPortableTensor * back_prop_output, ir::PaddingType paddingType, const uint32_t paddingLeft, const uint32_t paddingRight, const uint32_t paddingTop, const uint32_t paddingBottom, const uint32_t strideWidth, const uint32_t strideHeight, const uint32_t dilationWidthFactor, const uint32_t dilationHeightFactor, const ir::Activation activation)
Definition at line 69 of file ConvolutionLayer.cc.
{
  const bool is_cacheable_weights = false;
  cpu::ops::ConvolutionLayer::configure(input, weights, bias, paddingType, paddingLeft,
                                        paddingRight, paddingTop, paddingBottom, strideWidth,
                                        strideHeight, dilationWidthFactor, dilationHeightFactor,
                                        activation, output, is_cacheable_weights);
  _back_prop_input = back_prop_input;
  _grad_weights = grad_weights;
  _grad_bias = grad_bias;
  _back_prop_output = back_prop_output;
  if (_dilationHeightFactor != 1 || _dilationWidthFactor != 1)
    throw std::runtime_error("train ConvolutionLayer: Unsupported dilation yet");
  // TODO Optimize transposed tensors
  _transposed_weights = createTransposedWeights<Tensor>(weights);
  _transposed_weights->setBuffer(
    std::make_shared<basic::Allocator>(_transposed_weights->total_size()));
  _conv_back_prop_output =
    std::make_unique<BackPropTensor>(back_prop_output->get_info(), back_prop_output->layout());
  _conv_back_prop_output->setBuffer(
    std::make_shared<basic::Allocator>(_conv_back_prop_output->total_size()));
  _transposed_grad_weights = createTransposedWeights<GradientTensor>(weights);
  _transposed_grad_weights->setBuffer(
    std::make_shared<basic::Allocator>(_transposed_grad_weights->total_size()));
  if (activation != ir::Activation::NONE)
  {
    _act_back_prop_output =
      std::make_unique<BackPropTensor>(_back_prop_output->get_info(), _back_prop_output->layout());
    _act_back_prop_output->setBuffer(
      std::make_shared<basic::Allocator>(_act_back_prop_output->total_size()));
  }
}
References onert::backend::cpu::ops::ConvolutionLayer::_dilationHeightFactor, onert::backend::cpu::ops::ConvolutionLayer::_dilationWidthFactor, onert::backend::cpu::ops::ConvolutionLayer::configure(), onert::backend::IPortableTensor::get_info(), onert::backend::ITensor::layout(), and onert::ir::NONE.
forward()
void onert::backend::train::ops::ConvolutionLayer::forward (bool training) override virtual
Implements onert::exec::train::ITrainableFunction.
Definition at line 115 of file ConvolutionLayer.cc.
{ cpu::ops::ConvolutionLayer::run(); }
References onert::backend::cpu::ops::ConvolutionLayer::run().
The documentation for this class was generated from the following files:
runtime/onert/backend/train/ops/ConvolutionLayer.h
runtime/onert/backend/train/ops/ConvolutionLayer.cc