ONE - On-device Neural Engine: luci_interpreter::Interpreter Class Reference
luci_interpreter::Interpreter Class Reference
#include <Interpreter.h>
Public Member Functions
Interpreter (const luci::Module *module)
Interpreter (const luci::Module *module, IMemoryManager *memory_manager)
~Interpreter ()
void writeInputTensor (const luci::CircleInput *input_node, const void *data, size_t data_size)
void readOutputTensor (const luci::CircleOutput *output_node, void *data, size_t data_size)
void interpret ()
void attachObserver (ExecutionObserver *observer)
const Tensor * getTensor (const loco::Node *node)
Interpreter (const char *model_data_raw)
Interpreter (const char *model_data_raw, const InterpreterConfigure &configuration)
~Interpreter ()
void interpret ()
std::vector< Tensor * > getInputTensors ()
std::vector< Tensor * > getOutputTensors ()
Static Public Member Functions
static void writeInputTensor (Tensor *input_tensor, const void *data, size_t data_size)
static void writeInputTensorWithoutCopy (Tensor *input_tensor, const void *data)
static void readOutputTensor (const Tensor *output_tensor, void *data, size_t data_size)
Detailed Description
Definition at line 50 of file Interpreter.h.
Constructor & Destructor Documentation
Interpreter() [1/4]
luci_interpreter::Interpreter::Interpreter (const luci::Module * module) explicit
Definition at line 73 of file Interpreter.cpp.
{
  _runtime_to_ir = std::make_unique<RuntimeToIR>();
  _event_notifier = std::make_unique<EventNotifierImpl>(*_runtime_to_ir, _observers);
  _runtime_module = std::make_unique<RuntimeModule>(_event_notifier.get());
  _default_memory_manager = std::make_unique<SimpleMemoryManager>();
  ModuleLoader loader(module, _runtime_module.get(), *_runtime_to_ir, _node_to_tensor,
                      _default_memory_manager.get());
  loader.load();
}
References luci_interpreter::ModuleLoader::load().
Interpreter() [2/4]
luci_interpreter::Interpreter::Interpreter (const luci::Module * module, luci_interpreter::IMemoryManager * memory_manager) explicit
Definition at line 86 of file Interpreter.cpp.
{
  assert(memory_manager && "Use Interpreter::Interpreter(module) constructor instead");
  _runtime_to_ir = std::make_unique<RuntimeToIR>();
  _event_notifier = std::make_unique<EventNotifierImpl>(*_runtime_to_ir, _observers);
  _runtime_module = std::make_unique<RuntimeModule>(_event_notifier.get());
  ModuleLoader loader(module, _runtime_module.get(), *_runtime_to_ir, _node_to_tensor,
                      memory_manager);
  loader.load();
}
References luci_interpreter::ModuleLoader::load().
~Interpreter() [1/2]
luci_interpreter::Interpreter::~Interpreter () default
Interpreter() [3/4]
luci_interpreter::Interpreter::Interpreter (const char * model_data_raw) explicit
Definition at line 27 of file Interpreter.cpp.
{
  _runtime_module = std::make_unique<RuntimeModule>();
  _memory_manager = std::make_unique<SimpleMemoryManager>();
  _memory_manager->is_allocate_input(true);
  ModuleLoader loader(model_data_raw, _runtime_module.get(), _memory_manager.get());
  loader.load(/* is_static_allocations */ false);
}
References luci_interpreter::ModuleLoader::load().
Interpreter() [4/4]
luci_interpreter::Interpreter::Interpreter (const char * model_data_raw, const InterpreterConfigure & configuration) explicit
Definition at line 39 of file Interpreter.cpp.
{
  _runtime_module = std::make_unique<RuntimeModule>();
  // Note:
  // configuration._input_buf_size, configuration._temp_buf_size, configuration._output_buf_size
  // will be removed and will be read from circle file
  if (configuration.isStaticManager())
  {
    _memory_manager = std::make_unique<StaticMemoryManager>(
      configuration._input_buf_size, configuration._temp_buf_size, configuration._output_buf_size);
  }
  else
  {
    _memory_manager = std::make_unique<SimpleMemoryManager>();
  }
  _memory_manager->is_allocate_input(configuration.getAllocateInputValue());
  ModuleLoader loader(model_data_raw, _runtime_module.get(), _memory_manager.get());
  loader.load(configuration.isStaticManager());
}
References luci_interpreter::InterpreterConfigure::_input_buf_size, luci_interpreter::InterpreterConfigure::_output_buf_size, luci_interpreter::InterpreterConfigure::_temp_buf_size, luci_interpreter::InterpreterConfigure::getAllocateInputValue(), luci_interpreter::InterpreterConfigure::isStaticManager(), and luci_interpreter::ModuleLoader::load().
~Interpreter() [2/2]
luci_interpreter::Interpreter::~Interpreter ()
Member Function Documentation
attachObserver()
void luci_interpreter::Interpreter::attachObserver (ExecutionObserver * observer)
Definition at line 130 of file Interpreter.cpp.
{
  if (std::find(_observers.cbegin(), _observers.cend(), observer) != _observers.cend())
    throw std::runtime_error("Observer is already attached.");
  _observers.push_back(observer);
}
getInputTensors()
std::vector< Tensor * > luci_interpreter::Interpreter::getInputTensors ()
Definition at line 66 of file Interpreter.cpp.
{ return _runtime_module->getInputTensors(); }
getOutputTensors()
std::vector< Tensor * > luci_interpreter::Interpreter::getOutputTensors ()
Definition at line 68 of file Interpreter.cpp.
{
  return _runtime_module->getOutputTensors();
}
getTensor()
const Tensor * luci_interpreter::Interpreter::getTensor (const loco::Node * node) inline
Definition at line 67 of file Interpreter.h.
{ return _node_to_tensor[node]; }
interpret() [1/2]
void luci_interpreter::Interpreter::interpret ()
Definition at line 128 of file Interpreter.cpp.
{ _runtime_module->execute(); }
Referenced by record_minmax::RecordMinMax::profileData(), record_minmax::RecordMinMax::profileDataWithRandomInputs(), record_minmax::RecordMinMax::profileRawData(), and record_minmax::RecordMinMax::profileRawDataDirectory().
interpret() [2/2]
void luci_interpreter::Interpreter::interpret ()
readOutputTensor() [1/2]
void luci_interpreter::Interpreter::readOutputTensor (const luci::CircleOutput * output_node, void * data, size_t data_size)
Definition at line 115 of file Interpreter.cpp.
{
  Tensor *tensor = _runtime_module->getOutputTensors()[output_node->index()];
  if (tensor == nullptr)
  {
    const std::string &name = output_node->name();
    throw std::runtime_error("Cannot find tensor for output node named \"" + name + "\".");
  }
  if (data != nullptr)
    tensor->readData(data, data_size);
}
References luci::CircleOutput::index(), luci::CircleNode::name(), and luci::output_node().
Referenced by entry().
readOutputTensor() [2/2]
void luci_interpreter::Interpreter::readOutputTensor (const Tensor * output_tensor, void * data, size_t data_size) static
Definition at line 85 of file Interpreter.cpp.
{
  if (data != nullptr)
    output_tensor->readData(data, data_size);
}
writeInputTensor() [1/2]
void luci_interpreter::Interpreter::writeInputTensor (const luci::CircleInput * input_node, const void * data, size_t data_size)
Definition at line 102 of file Interpreter.cpp.
{
  Tensor *tensor = _runtime_module->getInputTensors()[input_node->index()];
  if (tensor == nullptr)
  {
    const std::string &name = input_node->name();
    throw std::runtime_error("Cannot find tensor for input node named \"" + name + "\".");
  }
  if (data != nullptr)
    tensor->writeData(data, data_size);
}
References luci::CircleInput::index(), luci::input_node(), and luci::CircleNode::name().
Referenced by entry(), record_minmax::RecordMinMax::profileData(), record_minmax::RecordMinMax::profileDataWithRandomInputs(), record_minmax::RecordMinMax::profileRawData(), and record_minmax::RecordMinMax::profileRawDataDirectory().
writeInputTensor() [2/2]
void luci_interpreter::Interpreter::writeInputTensor (Tensor * input_tensor, const void * data, size_t data_size) static
Definition at line 73 of file Interpreter.cpp.
{
  if (data != nullptr)
    input_tensor->writeData(data, data_size);
}
References luci_interpreter::Tensor::writeData().
writeInputTensorWithoutCopy()
void luci_interpreter::Interpreter::writeInputTensorWithoutCopy (Tensor * input_tensor, const void * data) static
Definition at line 79 of file Interpreter.cpp.
{
  if (data != nullptr)
    input_tensor->writeDataWithoutCopy(const_cast<void *>(data));
}
References luci_interpreter::Tensor::writeDataWithoutCopy().
The documentation for this class was generated from the following files:
compiler/luci-interpreter/include/luci_interpreter/Interpreter.h
onert-micro/luci-interpreter/include/luci_interpreter/Interpreter.h
compiler/luci-interpreter/src/Interpreter.cpp
onert-micro/luci-interpreter/src/Interpreter.cpp