ONE - On-device Neural Engine: SpatialPaddingBuilder Class Reference
SpatialPaddingBuilder Class Reference
Convert a raw padding to a spatial padding of a given spatial rank.
#include <PaddingUtils.h>
Public Member Functions
SpatialPadding with (const RawPadding &raw) const
Friends
SpatialPaddingBuilder build_spatial_padding (uint32_t spatial_rank)
Detailed Description
Convert a raw padding to a spatial padding of a given spatial rank.
Note
This class is an auxiliary class for build_raw_padding function below
Definition at line 55 of file PaddingUtils.h.
Member Function Documentation
with()
SpatialPadding SpatialPaddingBuilder::with (const RawPadding & raw) const
Definition at line 91 of file PaddingUtils.cpp.
{
  const auto spatial_rank = _spatial_rank;
  SpatialPadding res;
  res.resize(spatial_rank);
  if (raw.count() == 0)
  {
    // NOTE default padding is 0
    for (uint32_t spatial_axis = 0; spatial_axis < spatial_rank; ++spatial_axis)
    {
      res.value(spatial_axis) = 0;
    }
  }
  else if (raw.count() == 1)
  {
    // NOTE One-for-all scheme
    for (uint32_t spatial_axis = 0; spatial_axis < spatial_rank; ++spatial_axis)
    {
      res.value(spatial_axis) = raw.value(0);
    }
  }
  else
  {
    // NOTE One-to-one scheme
    assert(raw.count() == spatial_rank);
    for (uint32_t spatial_axis = 0; spatial_axis < spatial_rank; ++spatial_axis)
    {
      res.value(spatial_axis) = raw.value(spatial_axis);
    }
  }
  return res;
}
References PaddingBase< Derived >::count(), PaddingBase< Derived >::resize(), and PaddingBase< Derived >::value().
Referenced by PoolingSpec::horizontal_pad(), ConvolutionSpec::pad(), and PoolingSpec::vertical_pad().
Friends And Related Function Documentation
build_spatial_padding
SpatialPaddingBuilder build_spatial_padding (uint32_t spatial_rank) friend
SpatialPaddingBuilder is introduced to support the following code pattern:
auto raw_padding = build_raw_padding().with(conv_param); auto spatial_padding = build_spatial_padding(4).with(raw_padding);
Definition at line 128 of file PaddingUtils.cpp.
{
  return SpatialPaddingBuilder{spatial_rank};
}
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/PaddingUtils.h
compiler/enco/frontend/caffe/src/PaddingUtils.cpp