ONE - On-device Neural Engine: luci::Importer Class Reference
luci::Importer Class Reference final
#include <Importer.h>
Public Member Functions
Importer ()
Importer (const GraphBuilderSource *source)
std::unique_ptr< loco::Graph > import (const circle::Model *model) const
std::unique_ptr< Module > importModule (const circle::Model *model) const
Detailed Description
Definition at line 33 of file Importer.h.
Constructor & Destructor Documentation
Importer() [1/2]
luci::Importer::Importer ()
Definition at line 262 of file Importer.cpp.
{
  // DO NOTHING
}
Importer() [2/2]
luci::Importer::Importer (const GraphBuilderSource * source) inline explicit
Definition at line 39 of file Importer.h.
                                                      : _source{source}
  {
    // DO NOTHING
  }
Member Function Documentation
import()
std::unique_ptr< loco::Graph > luci::Importer::import (const circle::Model * model) const
Definition at line 267 of file Importer.cpp.
{
  auto graph = loco::make_graph();
  const GraphBuilderSource *source_ptr = &GraphBuilderRegistry::get();
  if (_source != nullptr)
  {
    // Use user-defined GraphBuilderSource
    source_ptr = _source;
  }
  CircleReader reader;
  if (!reader.parse(model))
    return nullptr;
  if (reader.num_subgraph() != 1)
  {
    INTERNAL_EXN("Use 'importModule()' for multiple subgraphs");
  }
  if (!reader.select_subgraph(0))
    return nullptr;
  // Convert circle::Model to loco::Graph
  convert_graph(*source_ptr, reader, graph.get());
  LOGGER(l);
  VERBOSE(l, 3) << "--- graph dump begin -------------------------------------------";
  VERBOSE(l, 3) << "Name: " << graph->name();
  VERBOSE(l, 3) << fmt(graph.get());
  VERBOSE(l, 3) << "--- graph dump end ---------------------------------------------";
  assert(loco::valid(graph.get(), std::make_unique<ValidateCollector>()));
  return graph;
}
References luci::fmt(), luci::GraphBuilderRegistry::get(), INTERNAL_EXN, LOGGER, loco::make_graph(), luci::CircleReader::num_subgraph(), luci::CircleReader::parse(), luci::CircleReader::select_subgraph(), loco::valid(), and VERBOSE.
importModule()
std::unique_ptr< Module > luci::Importer::importModule (const circle::Model * model) const
Definition at line 304 of file Importer.cpp.
{
  auto module = make_module();
  const GraphBuilderSource *source_ptr = &GraphBuilderRegistry::get();
  if (_source != nullptr)
  {
    // Use user-defined GraphBuilderSource
    source_ptr = _source;
  }
  CircleReader reader;
  if (!reader.parse(model))
    return nullptr;
  for (uint32_t g = 0; g < reader.num_subgraph(); ++g)
  {
    auto graph = loco::make_graph();
    if (!reader.select_subgraph(g))
      return nullptr;
    graph->name(reader.name());
    // Convert circle::Model to loco::Graph
    convert_graph(*source_ptr, reader, graph.get());
    LOGGER(l);
    VERBOSE(l, 3) << "--- graph dump begin -------------------------------------------";
    VERBOSE(l, 3) << "Name: " << graph->name();
    VERBOSE(l, 3) << fmt(graph.get());
    VERBOSE(l, 3) << "--- graph dump end ---------------------------------------------";
    assert(loco::valid(graph.get(), std::make_unique<ValidateCollector>()));
    module->add(std::move(graph));
  }
  post_import_graph(module.get(), reader);
  // Initialize 'source_table'
  auto circle_metadata = std::make_unique<luci::CircleImportMetadata>(reader);
  if (circle_metadata->source_table().size() > 0)
  {
    // If there is 'source_table' metadata in circle model, copy the table.
    module->source_table(circle_metadata->source_table());
  }
  else
  {
    // If there is no 'source_table' metadata in circle model,
    // create new table with circle nodes.
    std::map<uint32_t, std::string> table;
    // NOTE Only first subgraph is considered
    for (auto node : loco::all_nodes(module->graph(0)))
    {
      auto circle_node = loco::must_cast<luci::CircleNode *>(node);
      // Virtual nodes may not have id
      if (!has_node_id(circle_node))
        continue;
      assert(table.find(get_node_id(circle_node)) == table.end());
      table.insert({get_node_id(circle_node), circle_node->name()});
    }
    module->source_table(table);
  }
  // Add execution_plan annotations
  if (circle_metadata->execution_plan_table().size() > 0)
  {
    auto execution_plan_table = circle_metadata->execution_plan_table();
    auto node_position = 0;
    for (auto node : loco::postorder_traversal(loco::output_nodes(module->graph())))
    {
      if (auto circle_node = dynamic_cast<luci::CircleNode *>(node))
      {
        if (execution_plan_table.count(node_position) == 0)
          continue;
        auto node_plan = execution_plan_table[node_position];
        assert(node_plan.size() > 0);
        luci::add_execution_plan(
          circle_node,
          luci::CircleNodeExecutionPlan(
            node_plan[0], std::vector<uint32_t>(node_plan.begin() + 1, node_plan.end())));
      }
      node_position++;
    }
  }
  return module;
}
References luci::add_execution_plan(), loco::all_nodes(), luci::fmt(), luci::GraphBuilderRegistry::get(), luci::get_node_id(), luci::has_node_id(), LOGGER, loco::make_graph(), luci::make_module(), luci::CircleReader::name(), luci::CircleReader::num_subgraph(), loco::output_nodes(), luci::CircleReader::parse(), luci::post_import_graph(), loco::postorder_traversal(), luci::CircleReader::select_subgraph(), loco::valid(), and VERBOSE.
Referenced by entry(), opselector::getModule(), luci::ImporterEx::importVerifyModule(), dalgona::Dalgona::initialize(), record_minmax::RecordMinMax::initialize(), and ReadModule().
The documentation for this class was generated from the following files:
compiler/luci/import/include/luci/Importer.h
compiler/luci/import/src/Importer.cpp