ONE - On-device Neural Engine: tflimport::TensorContext Class Reference
tflimport::TensorContext Class Reference
Extracts and holds operand(tensor) information such as name, shape, and type.
#include <Context.h>
Public Member Functions
void prepare (const tflite::SubGraph *graph)
const std::string & name (uint32_t tensor_id)
const tensor::Shape & shape (uint32_t tensor_id)
const tflite::TensorType & type (uint32_t tensor_id)
Detailed Description
Extracts and holds operand(tensor) information such as name, shape, and type.
Definition at line 38 of file Context.h.
Member Function Documentation
name()
const std::string & tflimport::TensorContext::name (uint32_t tensor_id) inline
Definition at line 43 of file Context.h.
{ return _name_ctx[tensor_id]; }
Referenced by tflimport::set_module_inputs(), and tflimport::set_module_outputs().
prepare()
void tflimport::TensorContext::prepare (const tflite::SubGraph * graph)
Definition at line 35 of file Context.cpp.
{
  for (uint32_t tensor_id = 0; tensor_id < graph->tensors()->size(); ++tensor_id)
  {
    auto const tensor_info = graph->tensors()->Get(tensor_id);
    auto const tensor_name = tensor_info->name()->str();
    auto const tensor_shape = as_tensor_shape(tensor_info->shape());
    auto const tensor_type = tensor_info->type();
    _name_ctx[tensor_id] = tensor_name;
    _shape_ctx[tensor_id] = tensor_shape;
    _type_ctx[tensor_id] = tensor_type;
  }
}
References tflimport::as_tensor_shape().
shape()
const tensor::Shape & tflimport::TensorContext::shape (uint32_t tensor_id) inline
Definition at line 44 of file Context.h.
{ return _shape_ctx[tensor_id]; }
Referenced by tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::set_module_inputs(), and tflimport::set_module_outputs().
type()
const tflite::TensorType & tflimport::TensorContext::type (uint32_t tensor_id) inline
Definition at line 45 of file Context.h.
{ return _type_ctx[tensor_id]; }
Referenced by OptionBuilder.OptionBuilder::build(), and tflimport::copy_tensors().
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Context.h
compiler/enco/frontend/tflite/src/Context.cpp