ONE - On-device Neural Engine: exo::MatMulConverter Class Reference
exo::MatMulConverter Class Reference
Convert loco::MatMul to locoex::TFLFullyConnected.
#include <MatMulConverter.h>
Public Member Functions
const char * name (void) const final
bool convert (loco::MatMul *origin) final
Converts loco::MatMul to locoex::TFLFullyConnected.
Public Member Functions inherited from exo::CanonicalNodeConverter< loco::MatMul >
virtual const char * name (void) const
bool run (loco::Graph *graph)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Additional Inherited Members
virtual bool convert (loco::MatMul *node)=0
Detailed Description
Convert loco::MatMul to locoex::TFLFullyConnected.
Definition at line 30 of file MatMulConverter.h.
Member Function Documentation
convert()
bool exo::MatMulConverter::convert (loco::MatMul * origin) final virtual
Converts loco::MatMul to locoex::TFLFullyConnected.
Note
Because TFLFullyConnected accepts input and weights of loco::Domain::Matrix, loco::MatrixDecode will be inserted as an input and weights to meet domain invariant.
How it works:
Before: Foo1 -— MatrixEncode -— MatMul -— MatrixDecode -— Bar Foo2 -— MatrixEncode -—/
After:
Foo1 - MatrixEncode - MatrixDecode - TFLFullyConnected - MatrixEncode - MatrixDecode - Bar Foo2 - MatrixEncode - MatrixDecode -/
Note
This method replaces MatMul with "- MatrixDecode - TFLFullyConnected - MatrixEncode -".
MatrixDecode -/ Redundant nodes will be removed during transforms.
https://github.com/tensorflow/tensorflow/blob/v1.13.1/tensorflow/lite/kernels/internal/reference/fully_connected.h
Implements exo::CanonicalNodeConverter< loco::MatMul >.
Definition at line 54 of file MatMulConverter.cpp.
{
  auto *graph = origin->graph();
  assert(origin->lhs());
  assert(origin->rhs());
  auto tfl_fc = graph->nodes()->create<locoex::TFLFullyConnected>();
  tfl_fc->fusedActivationFunction(locoex::FusedActFunc::NONE);
  // let's create a new graph connection with tfl_fc
  {
    // input
    auto lhs_matrix_dec = make_matrix_decode<MatrixLayout::HW>(origin->lhs());
    tfl_fc->input(lhs_matrix_dec);
    // weights (WH format on TFLite)
    auto rhs_matrix_dec = make_matrix_decode<MatrixLayout::WH>(origin->rhs());
    tfl_fc->weights(rhs_matrix_dec);
    // bias
    auto zero_const = graph->nodes()->create<locoex::TFLConst>();
    { // TODO Create optimization pass which fuse additional Add into bias of Conv or FC
      assert(loco::shape_known(origin));
      assert(loco::dtype_known(origin) && loco::dtype_get(origin) == loco::DataType::FLOAT32);
      auto output_depth = loco::shape_get(origin->rhs()).as<loco::MatrixShape>().width();
      // TODO Fix it with type inference
      zero_const->dtype(loco::DataType::FLOAT32);
      zero_const->rank(1);
      zero_const->dim(0) = output_depth;
      zero_const->size<loco::DataType::FLOAT32>(output_depth.value());
      for (uint32_t x = 0; x < output_depth.value(); x++)
        zero_const->at<loco::DataType::FLOAT32>(x) = 0.0;
    }
    tfl_fc->bias(zero_const);
    // output
    auto matrix_enc = make_matrix_encode<MatrixLayout::HW>(tfl_fc);
    // replace canonical node
    loco::replace(origin).with(matrix_enc);
    origin->lhs(nullptr);
    origin->rhs(nullptr);
  }
  return true;
}
References loco::NodeShape::as(), loco::dtype_get(), loco::dtype_known(), locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >::fusedActivationFunction(), loco::Node::graph(), loco::MatMul::lhs(), exo::make_matrix_decode< MatrixLayout::HW >(), exo::make_matrix_decode< MatrixLayout::WH >(), exo::make_matrix_encode< MatrixLayout::HW >(), locoex::NONE, loco::replace(), loco::MatMul::rhs(), loco::shape_get(), loco::shape_known(), and loco::Subst< SubstQualifier::Default >::with().
name()
const char * exo::MatMulConverter::name (void) const inline final virtual
Reimplemented from exo::CanonicalNodeConverter< loco::MatMul >.
Definition at line 33 of file MatMulConverter.h.
{ return "exo::MatMulConverter"; }
The documentation for this class was generated from the following files:
compiler/exo/src/Conversion/MatMulConverter.h
compiler/exo/src/Conversion/MatMulConverter.cpp