ONE - On-device Neural Engine: coco::DLinkedList< Child, Parent >::Head Class Reference
coco::DLinkedList< Child, Parent >::Head Class Reference
#include <DLinkedList.h>
Public Member Functions
Head (Parent *parent)
Head (const Head &)=delete
Head (Head &&)=delete
Child * head (void) const
Child * tail (void) const
bool empty (void) const
void enlist (Child *child)
void delist (Child *child)
void prepend (Child *child)
void append (Child *child)
Detailed Description
template<typename Child, typename Parent>
class coco::DLinkedList< Child, Parent >::Head
Definition at line 34 of file DLinkedList.h.
Constructor & Destructor Documentation
Head() [1/3]
template<typename Child , typename Parent > coco::DLinkedList< Child, Parent >::Head::Head (Parent * parent) inline
Definition at line 37 of file DLinkedList.h.
                         : _parent{parent}
    {
      _head = nullptr;
      _tail = nullptr;
    }
Head() [2/3]
template<typename Child , typename Parent > coco::DLinkedList< Child, Parent >::Head::Head (const Head &) delete
Head() [3/3]
template<typename Child , typename Parent > coco::DLinkedList< Child, Parent >::Head::Head (Head &&) delete
Member Function Documentation
append()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Head::append (Child * child) inline
Definition at line 137 of file DLinkedList.h.
    {
      if (empty())
      {
        enlist(child);
      }
      else
      {
        child->insertAfter(_tail);
      }
    }
References coco::DLinkedList< Child, Parent >::Head::empty(), and coco::DLinkedList< Child, Parent >::Head::enlist().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), tflimport::AvgPool2DGraphBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), tflimport::DivGraphBuilder::build(), tflimport::MaxPool2DGraphBuilder::build(), tflimport::ReLUGraphBuilder::build(), tflimport::ReLU6GraphBuilder::build(), tflimport::ReshapeGraphBuilder::build(), tflimport::SubGraphBuilder::build(), tflimport::Conv2DGraphBuilder::build(), tflimport::DepthwiseConv2DGraphBuilder::build(), tflimport::build_activation(), and Frontend::load().
delist()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Head::delist (Child * child) inline
Definition at line 101 of file DLinkedList.h.
    {
      assert(child->parent() == _parent);
      assert(!empty());
      // Notify Child-Leaving event
      leaving(_parent, child);
      if (child == _head)
      {
        _head = child->next();
      }
      if (child == _tail)
      {
        _tail = child->prev();
      }
      // Update parent-child relation
      child->parent(nullptr);
    }
References coco::DLinkedList< Child, Parent >::Head::empty(), and coco::DLinkedList< Child, Parent >::leaving().
Referenced by coco::DLinkedList< Child, Parent >::Node::detach().
empty()
template<typename Child , typename Parent > bool coco::DLinkedList< Child, Parent >::Head::empty (void) const inline
Definition at line 52 of file DLinkedList.h.
    {
      if (_head == nullptr)
      {
        assert(_head == _tail);
        return true;
      }
      assert(_head != nullptr);
      assert(_tail != nullptr);
      return false;
    }
Referenced by coco::DLinkedList< Child, Parent >::Head::append(), coco::DLinkedList< Child, Parent >::Head::delist(), coco::DLinkedList< Child, Parent >::Head::enlist(), and coco::DLinkedList< Child, Parent >::Head::prepend().
enlist()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Head::enlist (Child * child) inline
Definition at line 66 of file DLinkedList.h.
    {
      assert((child->prev() == nullptr) || (child->prev()->parent() == _parent));
      assert((child->next() == nullptr) || (child->next()->parent() == _parent));
      if (empty())
      {
        _head = child;
        _tail = child;
      }
      else
      {
        if (child->next() == _head)
        {
          // _child is a new head
          assert(child->prev() == nullptr);
          _head = child;
        }
        if (child->prev() == _tail)
        {
          // _child is a new tail
          assert(child->next() == nullptr);
          _tail = child;
        }
      }
      // Update parent-child relation
      child->parent(_parent);
      // Notify Child-Joining event
      joined(_parent, child);
    }
References coco::DLinkedList< Child, Parent >::Head::empty(), and coco::DLinkedList< Child, Parent >::joined().
Referenced by coco::DLinkedList< Child, Parent >::Head::append(), coco::DLinkedList< Child, Parent >::Node::insertAfter(), coco::DLinkedList< Child, Parent >::Node::insertBefore(), and coco::DLinkedList< Child, Parent >::Head::prepend().
head()
template<typename Child , typename Parent > Child * coco::DLinkedList< Child, Parent >::Head::head (void) const inline
Definition at line 48 of file DLinkedList.h.
{ return _head; }
Referenced by enco::HostBlockCompiler::compile(), dump(), and enco::validate_output_shape().
prepend()
template<typename Child , typename Parent > void coco::DLinkedList< Child, Parent >::Head::prepend (Child * child) inline
Definition at line 124 of file DLinkedList.h.
    {
      if (empty())
      {
        enlist(child);
      }
      else
      {
        child->insertBefore(_head);
      }
    }
References coco::DLinkedList< Child, Parent >::Head::empty(), and coco::DLinkedList< Child, Parent >::Head::enlist().
tail()
template<typename Child , typename Parent > Child * coco::DLinkedList< Child, Parent >::Head::tail (void) const inline
Definition at line 49 of file DLinkedList.h.
{ return _tail; }
The documentation for this class was generated from the following file:
compiler/coco/core/include/coco/ADT/DLinkedList.h