ONE - On-device Neural Engine: onert::exec::ExecObservers Class Reference
onert::exec::ExecObservers Class Reference
#include <ExecutionObservers.h>
Public Member Functions
void add (std::unique_ptr< IExecutionObserver > &&observer)
IExecutionObserver * get (ObserverType type) const
Detailed Description
Definition at line 62 of file ExecutionObservers.h.
Member Function Documentation
add()
void onert::exec::ExecObservers::add (std::unique_ptr< IExecutionObserver > && observer) inline
Definition at line 65 of file ExecutionObservers.h.
  {
    _observers.emplace(observer->type(), std::move(observer));
  }
Referenced by onert::exec::ExecutorBase::addObserver(), and onert::exec::train::TrainableExecutor::addObserver().
get()
IExecutionObserver * onert::exec::ExecObservers::get (ObserverType type) const inline
Definition at line 70 of file ExecutionObservers.h.
  {
    if (_observers.find(type) != _observers.end())
      return _observers.at(type).get();
    return nullptr;
  }
Referenced by onert::exec::ExecutionObservee::ExecutionObservee().
The documentation for this class was generated from the following file:
runtime/onert/core/src/exec/ExecutionObservers.h