ONE - On-device Neural Engine: onert::interp::OperationExecutor Class Reference
onert::interp::OperationExecutor Class Reference
Public Member Functions
OperationExecutor (ExecEnv *env)
void execute (const ir::OperationIndex &idx)
Detailed Description
Definition at line 37 of file Interpreter.cc.
Constructor & Destructor Documentation
OperationExecutor()
onert::interp::OperationExecutor::OperationExecutor (ExecEnv * env) inline
Definition at line 40 of file Interpreter.cc.
                                  : _env{env}
  {
#define INTERP_OP(InternalName) _kernels[ir::OpCode::InternalName] = get##InternalName();
#include "InterpOps.lst"
#undef INTERP_OP
  }
Member Function Documentation
execute()
void onert::interp::OperationExecutor::execute (const ir::OperationIndex & idx) inline
Definition at line 47 of file Interpreter.cc.
  {
    const ir::Operation &node = _env->graph().operations().at(idx);
    const auto nodeName = node.name();
    VERBOSE(INTERPRETER) << "Prepare output operands and execute " << nodeName
                         << " operation (id: " << idx << ")" << std::endl;
    const auto nodeOpCode = node.opcode();
    if (_kernels.find(nodeOpCode) == _kernels.end())
    {
      throw std::runtime_error{"Interpreter: Operation " + nodeName + " is not yet implemented"};
    }
    if (_kernels[nodeOpCode]->prepare != nullptr)
    {
      _kernels[nodeOpCode]->prepare(_env, node);
    }
    _kernels[nodeOpCode]->invoke(_env, node);
  }
References onert::util::ObjectManager< Index, Object >::at(), onert::interp::ExecEnv::graph(), onert::ir::Operation::name(), onert::ir::Operation::opcode(), onert::ir::Graph::operations(), and VERBOSE.
The documentation for this class was generated from the following file:
runtime/onert/core/src/interp/Interpreter.cc