ONE - On-device Neural Engine: FilterEncodeLayer::Return Class Reference
FilterEncodeLayer::Return Class Reference
#include <GraphBuilder.h>
Public Member Functions
Return (loco::FilterEncode *node)
Return * perm (const loco::Permutation< loco::Domain::Filter > &perm)
loco::FilterEncode * node (void)
Detailed Description
Definition at line 348 of file GraphBuilder.h.
Constructor & Destructor Documentation
Return()
FilterEncodeLayer::Return::Return (loco::FilterEncode * node) inline
Definition at line 351 of file GraphBuilder.h.
                                   : _node{node}
    {
      // DO NOTHING
    }
Member Function Documentation
node()
loco::FilterEncode * FilterEncodeLayer::Return::node (void) inline
Definition at line 366 of file GraphBuilder.h.
{ return _node; }
perm()
Return * FilterEncodeLayer::Return::perm (const loco::Permutation< loco::Domain::Filter > & perm) inline
Definition at line 357 of file GraphBuilder.h.
    {
      auto encoder = std::make_unique<loco::PermutingEncoder<loco::Domain::Filter>>();
      encoder->perm(perm);
      _node->encoder(std::move(encoder));
      return this;
    }
References loco::FilterEncode::encoder(), and perm().
Referenced by perm().
The documentation for this class was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h