ONE - On-device Neural Engine: loco::MatrixShape Class Reference
loco::MatrixShape Class Reference final
Matrix Shape.
#include <MatrixShape.h>
Public Member Functions
MatrixShape ()=default
const Dimension & height (void) const
Dimension & height (void)
const Dimension & width (void) const
Dimension & width (void)
Detailed Description
Matrix Shape.
This class describes the shape of matrix, which serves as the input/output of matrix operations (e.g. Matrix Multiplication).
Each matrix is a collection of 2D features conceptually. Each matrix has height, width.
height() refers to the height of matrix in a given matrix width() refers to the width of matrix in a given matrix
Definition at line 37 of file MatrixShape.h.
Constructor & Destructor Documentation
MatrixShape()
loco::MatrixShape::MatrixShape () default
Member Function Documentation
height() [1/2]
Dimension & loco::MatrixShape::height (void) inline
Definition at line 44 of file MatrixShape.h.
{ return _height; }
height() [2/2]
const Dimension & loco::MatrixShape::height (void) const inline
Definition at line 43 of file MatrixShape.h.
{ return _height; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Matrix >::shape(), loco::PermutingEncoder< Domain::Matrix >::shape(), and exo::to_shape_description().
width() [1/2]
Dimension & loco::MatrixShape::width (void) inline
Definition at line 47 of file MatrixShape.h.
{ return _width; }
width() [2/2]
const Dimension & loco::MatrixShape::width (void) const inline
Definition at line 46 of file MatrixShape.h.
{ return _width; }
Referenced by loco::operator==(), loco::NodeShape::set(), loco::PermutingDecoder< Domain::Matrix >::shape(), loco::PermutingEncoder< Domain::Matrix >::shape(), and exo::to_shape_description().
The documentation for this class was generated from the following file:
compiler/loco/include/loco/IR/MatrixShape.h