ONE - On-device Neural Engine: luci::CircleReshape::Shape Class Reference
luci::CircleReshape::Shape Class Reference
#include <CircleReshape.h>
Public Member Functions
uint32_t rank (void) const
void rank (uint32_t rank)
int32_t dim (uint32_t n) const
int32_t & dim (uint32_t n)
Detailed Description
Definition at line 43 of file CircleReshape.h.
Member Function Documentation
dim() [1/2]
int32_t & luci::CircleReshape::Shape::dim (uint32_t n) inline
Definition at line 50 of file CircleReshape.h.
{ return _shape.at(n); }
dim() [2/2]
int32_t luci::CircleReshape::Shape::dim (uint32_t n) const inline
Definition at line 49 of file CircleReshape.h.
{ return _shape.at(n); }
Referenced by luci::CloneNodeLet< CN::OPQR >::visit(), and luci::BuiltinOptionsExtractor::visit().
rank() [1/2]
void luci::CircleReshape::Shape::rank (uint32_t rank) inline
Definition at line 47 of file CircleReshape.h.
{ _shape.resize(rank); }
References rank().
rank() [2/2]
uint32_t luci::CircleReshape::Shape::rank (void) const inline
Definition at line 46 of file CircleReshape.h.
{ return _shape.size(); }
Referenced by rank(), luci::CloneNodeLet< CN::OPQR >::visit(), and luci::BuiltinOptionsExtractor::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleReshape.h