ONE - On-device Neural Engine: luci::CircleResizeNearestNeighbor Class Reference
luci::CircleResizeNearestNeighbor Class Reference final
RESIZE_NEAREST_NEIGHBOR in Circle.
#include <CircleResizeNearestNeighbor.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * size (void) const
void size (loco::Node *node)
bool align_corners () const
void align_corners (bool value)
Public Member Functions inherited from luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >
loco::Use * at (uint32_t n) const
Detailed Description
RESIZE_NEAREST_NEIGHBOR in Circle.
Definition at line 31 of file CircleResizeNearestNeighbor.h.
Member Function Documentation
align_corners() [1/2]
bool luci::CircleResizeNearestNeighbor::align_corners () const inline
Definition at line 42 of file CircleResizeNearestNeighbor.h.
{ return _align_corners; }
Referenced by luci::CloneNodeLet< CN::OPQR >::visit(), and luci::BuiltinOptionsExtractor::visit().
align_corners() [2/2]
void luci::CircleResizeNearestNeighbor::align_corners (bool value) inline
Definition at line 43 of file CircleResizeNearestNeighbor.h.
{ _align_corners = value; }
input() [1/2]
void luci::CircleResizeNearestNeighbor::input (loco::Node * node) inline
Definition at line 36 of file CircleResizeNearestNeighbor.h.
{ at(0)->node(node); }
References luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * luci::CircleResizeNearestNeighbor::input (void) const inline
Definition at line 35 of file CircleResizeNearestNeighbor.h.
{ return at(0)->node(); }
References luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >::at(), and loco::Use::node().
size() [1/2]
void luci::CircleResizeNearestNeighbor::size (loco::Node * node) inline
Definition at line 39 of file CircleResizeNearestNeighbor.h.
{ at(1)->node(node); }
References luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >::at(), and loco::Use::node().
size() [2/2]
loco::Node * luci::CircleResizeNearestNeighbor::size (void) const inline
Definition at line 38 of file CircleResizeNearestNeighbor.h.
{ return at(1)->node(); }
References luci::FixedArityNode< 2, CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleResizeNearestNeighbor.h