ONE - On-device Neural Engine: onert::backend::train::TrainableBackendContext Class Reference
onert::backend::train::TrainableBackendContext Class Reference abstract
#include <TrainableBackendContext.h>
Public Member Functions
TrainableBackendContext (const ITrainableBackend *backend, std::unique_ptr< TrainableContextData > &&tdata, std::shared_ptr< backend::ITensorRegistry > tensor_registry=nullptr, std::shared_ptr< backend::ITensorRegistry > grad_tensor_registry=nullptr)
virtual ~TrainableBackendContext ()=default
const ir::train::TrainableGraph * trainable_graph () const
const TrainableContextData * data () const
const ITrainableBackend * backend () const
const util::Set< ir::OperandIndex > & external_operands () const
const ir::OperandIndexMap< ir::Layout > & operand_layouts () const
std::shared_ptr< backend::ITensorRegistry > tensor_registry ()
std::shared_ptr< backend::ITensorRegistry > grad_tensor_registry ()
virtual ITensorRegistry * genTrainingTensors ()=0
virtual ITensorRegistry * genTensors ()=0
virtual FunctionMap genKernels ()=0
Protected Attributes
std::unique_ptr< TrainableContextData > _tdata
std::shared_ptr< backend::ITensorRegistry > _tensor_registry
std::shared_ptr< backend::ITensorRegistry > _grad_tensor_registry
Detailed Description
Definition at line 54 of file TrainableBackendContext.h.
Constructor & Destructor Documentation
TrainableBackendContext()
onert::backend::train::TrainableBackendContext::TrainableBackendContext (const ITrainableBackend * backend, std::unique_ptr< TrainableContextData > && tdata, std::shared_ptr< backend::ITensorRegistry > tensor_registry = nullptr, std::shared_ptr< backend::ITensorRegistry > grad_tensor_registry = nullptr) inline
Definition at line 57 of file TrainableBackendContext.h.
    : _backend{backend}, _tdata{std::move(tdata)}, _tensor_registry{tensor_registry},
      _grad_tensor_registry{grad_tensor_registry}
  {
    assert(_tdata);
  }
References _tdata.
~TrainableBackendContext()
virtual onert::backend::train::TrainableBackendContext::~TrainableBackendContext () virtual default
Member Function Documentation
backend()
const ITrainableBackend * onert::backend::train::TrainableBackendContext::backend () const inline
Definition at line 72 of file TrainableBackendContext.h.
{ return _backend; }
Referenced by CfgRunner.CfgRunner::run(), and CfgRunner.CfgRunner::set_backend().
data()
const TrainableContextData * onert::backend::train::TrainableBackendContext::data () const inline
Definition at line 70 of file TrainableBackendContext.h.
{ return _tdata.get(); }
References _tdata.
external_operands()
const util::Set< ir::OperandIndex > & onert::backend::train::TrainableBackendContext::external_operands () const inline
Definition at line 73 of file TrainableBackendContext.h.
{ return _tdata->external_operands; }
References _tdata.
Referenced by onert::backend::basic::train::genTensors(), and onert::backend::basic::train::initConsts().
genKernels()
virtual FunctionMap onert::backend::train::TrainableBackendContext::genKernels () pure virtual
Implemented in onert::backend::train::BackendContext, and onert::backend::builtin::train::BackendContext.
genTensors()
virtual ITensorRegistry * onert::backend::train::TrainableBackendContext::genTensors () pure virtual
Implemented in onert::backend::train::BackendContext, and onert::backend::builtin::train::BackendContext.
genTrainingTensors()
virtual ITensorRegistry * onert::backend::train::TrainableBackendContext::genTrainingTensors () pure virtual
Implemented in onert::backend::train::BackendContext, and onert::backend::builtin::train::BackendContext.
grad_tensor_registry()
std::shared_ptr< backend::ITensorRegistry > onert::backend::train::TrainableBackendContext::grad_tensor_registry () inline
Definition at line 77 of file TrainableBackendContext.h.
{ return _grad_tensor_registry; }
References _grad_tensor_registry.
Referenced by onert::backend::builtin::train::BackendContext::genTrainingTensors().
operand_layouts()
const ir::OperandIndexMap< ir::Layout > & onert::backend::train::TrainableBackendContext::operand_layouts () const inline
Definition at line 74 of file TrainableBackendContext.h.
{ return _tdata->operand_layouts; }
References _tdata.
tensor_registry()
std::shared_ptr< backend::ITensorRegistry > onert::backend::train::TrainableBackendContext::tensor_registry () inline
Definition at line 76 of file TrainableBackendContext.h.
{ return _tensor_registry; }
References _tensor_registry.
Referenced by onert::backend::basic::train::genTensors(), and onert::backend::basic::train::initConsts().
trainable_graph()
const ir::train::TrainableGraph * onert::backend::train::TrainableBackendContext::trainable_graph () const inline
Definition at line 68 of file TrainableBackendContext.h.
{ return _tdata->tgraph.get(); }
References _tdata.
Referenced by onert::backend::basic::train::genTensors(), and onert::backend::basic::train::initConsts().
Field Documentation
_grad_tensor_registry
std::shared_ptr<backend::ITensorRegistry> onert::backend::train::TrainableBackendContext::_grad_tensor_registry protected
Definition at line 91 of file TrainableBackendContext.h.
Referenced by onert::backend::train::BackendContext::genTrainingTensors(), and grad_tensor_registry().
_tdata
std::unique_ptr<TrainableContextData> onert::backend::train::TrainableBackendContext::_tdata protected
Definition at line 87 of file TrainableBackendContext.h.
Referenced by data(), external_operands(), onert::backend::train::BackendContext::genKernels(), onert::backend::builtin::train::BackendContext::genKernels(), operand_layouts(), trainable_graph(), and TrainableBackendContext().
_tensor_registry
std::shared_ptr<backend::ITensorRegistry> onert::backend::train::TrainableBackendContext::_tensor_registry protected
Definition at line 90 of file TrainableBackendContext.h.
Referenced by tensor_registry().
The documentation for this class was generated from the following file:
runtime/onert/core/include/backend/train/TrainableBackendContext.h