ONE - On-device Neural Engine: onert::ir::operation::Reduce Class Reference
onert::ir::operation::Reduce Class Reference
#include <Reduce.h>
Data Structures
struct Param
Public Types
enum Input { INPUT = 0 , AXES = 1 }
enum class ReduceType {
ALL , ANY , MAX , MEAN ,
MIN , PROD , SUM
}
Public Member Functions
Reduce (const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, const Param &param)
void accept (OperationVisitor &v) const override
std::string name () const override
OpCode opcode () const final
const Param & param () const
Public Member Functions inherited from onert::ir::Operation
Operation (OperandConstraint input_constr, const OperandIndexSequence &inputs, const OperandIndexSequence &outputs, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (OperandConstraint input_constr, OperandConstraint output_constr=OperandConstraint::createAny())
Operation (const Operation &)=default
Operation (Operation &&)=default
Operation & operator= (const Operation &)=default
Operation & operator= (Operation &&)=default
virtual ~Operation ()
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
void replaceInputs (const OperandIndex &from, const OperandIndex &to)
void replaceOutputs (const OperandIndex &from, const OperandIndex &to)
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getInputs () const
const OperandIndexSequence & getOutputs () const
void setInputs (const OperandIndexSequence &indexes)
void setOutputs (const OperandIndexSequence &indexes)
Detailed Description
Definition at line 31 of file Reduce.h.
Member Enumeration Documentation
Input
enum onert::ir::operation::Reduce::Input
Enumerator
INPUT
AXES
Definition at line 34 of file Reduce.h.
  {
    INPUT = 0,
    AXES = 1
  };
ReduceType
enum class onert::ir::operation::Reduce::ReduceType strong
Enumerator
ALL
ANY
MAX
MEAN
MIN
PROD
SUM
Definition at line 40 of file Reduce.h.
  {
    ALL,
    ANY,
    MAX,
    MEAN,
    MIN,
    PROD,
    SUM
  };
Constructor & Destructor Documentation
Reduce()
onert::ir::operation::Reduce::Reduce (const OperandIndexSequence & inputs, const OperandIndexSequence & outputs, const Param & param)
Definition at line 31 of file Reduce.cc.
  : Operation{OperandConstraint::createExact(2u), inputs, outputs}, _param{param}
{
}
Member Function Documentation
accept()
void onert::ir::operation::Reduce::accept (OperationVisitor & v) const override virtual
Implements onert::ir::Operation.
Definition at line 29 of file Reduce.cc.
{ v.visit(*this); }
name()
std::string onert::ir::operation::Reduce::name () const override virtual
Reimplemented from onert::ir::Operation.
Definition at line 37 of file Reduce.cc.
{
  using ReduceType = onert::ir::operation::Reduce::ReduceType;
  static const std::unordered_map<ReduceType, std::string> name_map{
    {ReduceType::ALL, std::string{toString(opcode())} + "All"},
    {ReduceType::ANY, std::string{toString(opcode())} + "Any"},
    {ReduceType::MAX, std::string{toString(opcode())} + "Max"},
    {ReduceType::MEAN, std::string{toString(opcode())} + "Mean"},
    {ReduceType::MIN, std::string{toString(opcode())} + "Min"},
    {ReduceType::PROD, std::string{toString(opcode())} + "Prod"},
    {ReduceType::SUM, std::string{toString(opcode())} + "SUM"}};
  return name_map.at(_param.reduce_type);
  //  return std::string(toString(opcode())) + reduce_type_str_map.at(_param.reduce_type);
}
References ALL, ANY, MAX, MEAN, MIN, opcode(), PROD, onert::ir::operation::Reduce::Param::reduce_type, SUM, and onert::ir::toString().
Referenced by onert::exec::DynamicShapeInferer::visit().
opcode()
OpCode onert::ir::operation::Reduce::opcode () const inline final virtual
Implements onert::ir::Operation.
Definition at line 64 of file Reduce.h.
{ return OpCode::Reduce; }
Referenced by name().
param()
const Param & onert::ir::operation::Reduce::param () const inline
Definition at line 67 of file Reduce.h.
{ return _param; }
Referenced by onert::backend::cpu::KernelGenerator::visit(), and onert::exec::DynamicShapeInferer::visit().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/operation/Reduce.h
runtime/onert/core/src/ir/operation/Reduce.cc