ONE - On-device Neural Engine: onert::ir::Graph Class Reference
onert::ir::Graph Class Reference
#include <Graph.h>
Public Member Functions
Graph (void)
Graph (const Graph &)
~Graph (void)
OperandIndex addOperand (const Shape &shape, const TypeInfo &type)
OperandIndex addOperand (OperandIndex index, std::unique_ptr< Operand > &&operand)
Add an operand to the graph with the given index and object.
OperationIndex addOperation (std::unique_ptr< IOperation > &&node)
OperationIndex addOperation (OperationIndex index, std::unique_ptr< IOperation > &&operation)
Add an operation to the graph with the given index and object.
OperationIndex replaceOperation (OperationIndex index, std::unique_ptr< IOperation > &&operation)
Replace an operation which the graph already has.
void setOperandValue (const OperandIndex &ind, std::shared_ptr< Data > data)
void changeShape (const OperandIndex &ind, const ir::Shape &new_shape) override
void addInput (const OperandIndex &ind, const std::string &name="")
void addOutput (const OperandIndex &ind, const std::string &name="")
void verify (void) const
void removeOperand (const OperandIndex &ind)
void setLayout (Layout layout)
const OperandIndexSequence & getInputs () const override
OperandIndexSequence & getInputs ()
const OperandIndexSequence & getOutputs () const override
OperandIndexSequence & getOutputs ()
IOIndex getInputIndex (const std::string &name) const override
IOIndex getOutputIndex (const std::string &name) const override
const Operands & operands () const override
Operands & operands ()
const Operations & operations () const override
Operations & operations ()
Layout layout () const
std::vector< ir::OperationIndex > topolSortOperations () const
Public Member Functions inherited from onert::ir::IGraph
virtual ~IGraph ()=default
Detailed Description
Definition at line 33 of file Graph.h.
Constructor & Destructor Documentation
Graph() [1/2]
onert::ir::Graph::Graph (void) explicit default
Graph() [2/2]
onert::ir::Graph::Graph (const Graph &) explicit default
~Graph()
onert::ir::Graph::~Graph (void) default
Member Function Documentation
addInput()
void onert::ir::Graph::addInput (const OperandIndex & ind, const std::string & name = "")
Definition at line 123 of file Graph.cc.
{
  if (!name.empty())
    _name_to_input.emplace(name, IOIndex{_inputs.size()});
  _inputs.append(ind);
}
References onert::ir::OperandIndexSequence::append(), and onert::ir::OperandIndexSequence::size().
Referenced by onert::ir::train::TrainableGraph::addInput().
addOperand() [1/2]
OperandIndex onert::ir::Graph::addOperand (const Shape & shape, const TypeInfo & type)
Definition at line 35 of file Graph.cc.
{
  return _operands.emplace(shape, type);
}
References onert::util::ObjectManager< Index, Object >::emplace().
Referenced by onert::ir::train::TrainableGraph::addOperand(), onert::ir::train::TrainableGraph::addOperand(), onert::compiler::pass::ConstantOutputPass::callback(), and onert::base_loader::BaseLoader< LoaderDomain >::loadOperand().
addOperand() [2/2]
OperandIndex onert::ir::Graph::addOperand (OperandIndex index, std::unique_ptr< Operand > && operand)
Add an operand to the graph with the given index and object.
If the given index is available, it succeeds. And operand is moved which invalidates the caller's pointer. If the given index is already taken, it fails. And operand will not be moved so the caller's pointer will be still valid.
Parameters
[in] index Index to be added
[in] operand Operand to be added
Returns
OperandIndex index if successful, Undefined otherwise
Definition at line 40 of file Graph.cc.
{
  return _operands.push(std::move(operand), index);
}
References onert::util::ObjectManager< Index, Object >::push().
addOperation() [1/2]
OperationIndex onert::ir::Graph::addOperation (OperationIndex index, std::unique_ptr< IOperation > && operation)
Add an operation to the graph with the given index and object.
If the given index is available, it succeeds. And operation is moved which invalidates the caller's pointer. If the given index is already taken, it fails. And operation will not be moved so the caller's pointer will be still valid.
Parameters
index Index to be added
operation IOperation to be added
Returns
OperandIndex index if successful, Undefined otherwise
Definition at line 80 of file Graph.cc.
{
  const IOperation &op_ref = *operation;
  if (!checkOperandsForOperation(op_ref))
    return OperationIndex{};
  auto ind_gen = _operations.push(std::move(operation), index);
  if (ind_gen.valid())
  {
    assert(ind_gen == index);
    linkOperandToOperation(index, op_ref);
  }
  return index;
}
References onert::util::ObjectManager< Index, Object >::push().
addOperation() [2/2]
OperationIndex onert::ir::Graph::addOperation (std::unique_ptr< IOperation > && node)
Definition at line 69 of file Graph.cc.
{
  const IOperation &op_ref = *operation;
  if (!checkOperandsForOperation(op_ref))
    return OperationIndex{};
  auto ind = _operations.push(std::move(operation));
  if (ind.valid())
    linkOperandToOperation(ind, op_ref);
  return ind;
}
References onert::util::ObjectManager< Index, Object >::push().
Referenced by onert::ir::train::TrainableGraph::addOperation().
addOutput()
void onert::ir::Graph::addOutput (const OperandIndex & ind, const std::string & name = "")
Definition at line 130 of file Graph.cc.
{
  if (!name.empty())
    _name_to_output.emplace(name, IOIndex{_outputs.size()});
  _outputs.append(ind);
}
References onert::ir::OperandIndexSequence::append(), and onert::ir::OperandIndexSequence::size().
Referenced by onert::ir::train::TrainableGraph::addOutput().
changeShape()
void onert::ir::Graph::changeShape (const OperandIndex & ind, const ir::Shape & new_shape) override virtual
Implements onert::ir::IGraph.
Definition at line 117 of file Graph.cc.
{
  assert(_operands.exist(ind));
  _operands.at(ind).info().shape(new_shape);
}
References onert::util::ObjectManager< Index, Object >::at(), and onert::util::ObjectManager< Index, Object >::exist().
Referenced by onert::ir::train::TrainableGraph::changeShape().
getInputIndex()
IOIndex onert::ir::Graph::getInputIndex (const std::string & name) const override virtual
Implements onert::ir::IGraph.
Definition at line 137 of file Graph.cc.
{
  auto itr = _name_to_input.find(name);
  return (itr == _name_to_input.end()) ? IOIndex{} : itr->second;
}
Referenced by onert::ir::train::TrainableGraph::getInputIndex().
getInputs() [1/2]
OperandIndexSequence & onert::ir::Graph::getInputs () inline
Definition at line 108 of file Graph.h.
{ return _inputs; }
getInputs() [2/2]
const OperandIndexSequence & onert::ir::Graph::getInputs () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 107 of file Graph.h.
{ return _inputs; }
Referenced by onert::exec::ExecutorBase::execute(), onert::exec::ExecutorBase::ExecutorBase(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::ir::train::TrainableGraph::getInputs(), onert::exec::MinMaxRecorder::handleSubgraphBegin(), onert::compiler::pass::UnusedOperandEliminationPass::run(), onert::compiler::pass::OddOutputPass::run(), and onert::backend::acl_common::AclSubTensorAnalyzer::visit().
getOutputIndex()
IOIndex onert::ir::Graph::getOutputIndex (const std::string & name) const override virtual
Implements onert::ir::IGraph.
Definition at line 143 of file Graph.cc.
{
  auto itr = _name_to_output.find(name);
  return (itr == _name_to_output.end()) ? IOIndex{} : itr->second;
}
Referenced by onert::ir::train::TrainableGraph::getOutputIndex().
getOutputs() [1/2]
OperandIndexSequence & onert::ir::Graph::getOutputs () inline
Definition at line 110 of file Graph.h.
{ return _outputs; }
getOutputs() [2/2]
const OperandIndexSequence & onert::ir::Graph::getOutputs () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 109 of file Graph.h.
{ return _outputs; }
Referenced by onert::compiler::pass::ConstantOutputPass::callback(), onert::exec::ExecutorBase::execute(), onert::exec::ExecutorBase::execute(), onert::exec::ExecutorBase::ExecutorBase(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::ir::train::TrainableGraph::getOutputs(), onert::compiler::pass::UnusedOperandEliminationPass::run(), and onert::compiler::pass::OddOutputPass::run().
layout()
Layout onert::ir::Graph::layout () const inline
Definition at line 117 of file Graph.h.
{ return _layout; }
Referenced by onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::ir::train::TrainableGraph::layout(), onert::backend::acl_cl::Optimizer::optimize(), onert::backend::acl_neon::Optimizer::optimize(), setLayout(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), and onert::compiler::ShapeValidator::visit().
operands() [1/2]
Operands & onert::ir::Graph::operands () inline
Definition at line 114 of file Graph.h.
{ return _operands; } // TODO Remove this non-const accessor
operands() [2/2]
const Operands & onert::ir::Graph::operands () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 113 of file Graph.h.
{ return _operands; }
Referenced by onert::compiler::pass::ConstantOutputPass::callback(), onert::compiler::pass::PermutationInsertionPass::callback(), onert::compiler::pass::ConstantInsertionPass::callback(), onert::compiler::pass::ConstantLoweringPass::callback(), onert::compiler::StaticShapeInferer::dump(), onert::backend::builtin::KernelGenerator::generate(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::exec::ProfileObserver::handleJobEnd(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::initConsts(), onert::backend::basic::initConsts(), onert::base_loader::BaseLoader< LoaderDomain >::loadOperand(), onert::ir::train::TrainableGraph::operands(), onert::ir::train::TrainableGraph::operands(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), onert::compiler::pass::UnusedOperandEliminationPass::run(), onert::compiler::pass::OddOutputPass::run(), onert::compiler::pass::OperandPass::run(), topolSortOperations(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::backend::acl_common::AclSubTensorAnalyzer::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::pass::PermutationOperationPass::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::ShapeValidator::visit(), onert::compiler::pass::PermutationOperationPass::visit(), and onert::compiler::ShapeValidator::visit().
operations() [1/2]
Operations & onert::ir::Graph::operations () inline
Definition at line 116 of file Graph.h.
{ return _operations; }
operations() [2/2]
const Operations & onert::ir::Graph::operations () const inline override virtual
Implements onert::ir::IGraph.
Definition at line 115 of file Graph.h.
{ return _operations; }
Referenced by onert::exec::DataflowExecutor::calculateRank(), onert::compiler::pass::ConstantOutputPass::callback(), onert::compiler::pass::PermutationInsertionPass::callback(), onert::backend::acl_cl::KernelGenerator::generate(), onert::backend::acl_neon::KernelGenerator::generate(), onert::backend::gpu_cl::KernelGenerator::generate(), onert::backend::ruy::KernelGenerator::generate(), onert::backend::builtin::KernelGenerator::generate(), onert::backend::trix::KernelGenerator::generate(), onert::exec::TracingObserver::handleJobBegin(), onert::exec::ProfileObserver::handleJobEnd(), onert::exec::TracingObserver::handleJobEnd(), onert::exec::MinMaxRecorder::handleJobEnd(), onert::compiler::StaticShapeInferer::infer(), onert::ir::train::TrainableGraph::operation(), onert::ir::train::TrainableGraph::operations(), onert::compiler::ShapeValidator::operator()(), onert::backend::acl_cl::Optimizer::optimize(), onert::backend::acl_neon::Optimizer::optimize(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::planTensors(), onert::compiler::pass::OperationPass::run(), onert::compiler::pass::UnusedOperandEliminationPass::run(), onert::compiler::HEScheduler::schedule(), and topolSortOperations().
removeOperand()
void onert::ir::Graph::removeOperand (const OperandIndex & ind) inline
Definition at line 94 of file Graph.h.
{ _operands.remove(ind); }
References onert::util::ObjectManager< Index, Object >::remove().
Referenced by onert::compiler::pass::ConstantInsertionPass::callback(), and onert::ir::train::TrainableGraph::removeOperand().
replaceOperation()
OperationIndex onert::ir::Graph::replaceOperation (OperationIndex index, std::unique_ptr< IOperation > && operation)
Replace an operation which the graph already has.
If the given index is available, it succeeds. And operation is moved which invalidates the caller's pointer. If the given operation has at least one invalid operand index, it fails. And operation will not be moved so the caller's pointer will be still valid.
No information in the graph is changed except for replacing an operation.
Parameters
operation Operation to be added
Returns
OperationIndex index if successful, UNDEFINED otherwise
Definition at line 94 of file Graph.cc.
{
  const IOperation &op_ref = *operation;
  if (!checkOperandsForOperation(op_ref) || !_operations.exist(index))
    return OperationIndex{};
  // Check the new operation has the same inputs/outputs as the existing operation
  const auto &old_op = _operations.at(index);
  if (!(old_op.getInputs() == op_ref.getInputs() && old_op.getOutputs() == op_ref.getOutputs()))
  {
    return OperationIndex{};
  }
  return _operations.set(index, std::move(operation));
}
References onert::util::ObjectManager< Index, Object >::at(), onert::util::ObjectManager< Index, Object >::exist(), onert::ir::IOperation::getInputs(), onert::ir::IOperation::getOutputs(), and onert::util::ObjectManager< Index, Object >::set().
Referenced by onert::ir::train::TrainableGraph::replaceOperation().
setLayout()
void onert::ir::Graph::setLayout (Layout layout) inline
Definition at line 95 of file Graph.h.
{ _layout = layout; }
References layout().
Referenced by onert::ir::train::TrainableGraph::setLayout().
setOperandValue()
void onert::ir::Graph::setOperandValue (const OperandIndex & ind, std::shared_ptr< Data > data)
Definition at line 111 of file Graph.cc.
{
  assert(_operands.exist(ind));
  _operands.at(ind).data(std::move(data));
}
References onert::util::ObjectManager< Index, Object >::at(), and onert::util::ObjectManager< Index, Object >::exist().
Referenced by onert::base_loader::BaseLoader< LoaderDomain >::loadOperand().
topolSortOperations()
std::vector< ir::OperationIndex > onert::ir::Graph::topolSortOperations () const
Definition at line 184 of file Graph.cc.
{
  std::vector<ir::OperationIndex> ret;
  util::Set<ir::OperationIndex> unvisited;
  operations().iterate(
    [&](const ir::OperationIndex &index, const ir::IOperation &) { unvisited.add(index); });
  std::function<void(const ir::OperationIndex &, const ir::IOperation &)> dfs =
    [&](const ir::OperationIndex &index, const ir::IOperation &op) -> void {
    if (!unvisited.contains(index))
      return;
    unvisited.remove(index);
    for (const auto &output : op.getOutputs() | ir::Remove::DUPLICATED | ir::Remove::UNDEFINED)
    {
      const auto &operand = operands().at(output);
      for (const auto &use : operand.getUses())
      {
        dfs(use, operations().at(use));
      }
    }
    ret.push_back(index);
  };
  operations().iterate(dfs);
  assert(unvisited.empty()); // All of the nodes must have been visited
  // Reversing Postorder DFS result to make it sorted in topoligical order
  std::reverse(ret.begin(), ret.end());
  return ret;
}
References onert::util::Set< Element >::add(), onert::util::ObjectManager< Index, Object >::at(), onert::util::Set< Element >::contains(), onert::ir::DUPLICATED, onert::util::Set< Element >::empty(), onert::util::ObjectManager< Index, Object >::iterate(), operands(), operations(), onert::util::Set< Element >::remove(), and onert::ir::UNDEFINED.
Referenced by onert::compiler::StaticShapeInferer::infer(), onert::compiler::train::StaticBackwardShapeInferer::infer(), onert::compiler::Linear::linearize(), and onert::ir::train::TrainableGraph::topolSortOperations().
verify()
void onert::ir::Graph::verify (void) const
Definition at line 149 of file Graph.cc.
{
  // Call graph verifications for the MODEL phase
  {
    // Except for edge consistency, the user might have been given a bad model
    // so here it throws an execption rather than assertion.
    if (!verifier::InputOutputChecker().verify(*this))
      throw std::runtime_error{"One of model input and output operands does not exist."};
    if (!verifier::DAGChecker().verify(*this))
      throw std::runtime_error{"The graph is cyclic."};
    assert(verifier::EdgeChecker().verify(*this));
  }
  // Check shape independent operation feature
  // - Operand type
  // - Shape independent parameter
  OperationValidator{*this}();
}
References verify().
Referenced by onert::ir::train::TrainableGraph::verify(), and verify().
The documentation for this class was generated from the following files:
runtime/onert/core/include/ir/Graph.h
runtime/onert/core/src/ir/Graph.cc