ONE - On-device Neural Engine: luci::CircleExportMetadata Class Reference
luci::CircleExportMetadata Class Reference
#include <SerializedData.h>
Public Member Functions
void source_table (const std::map< uint32_t, std::string > &table)
void add_op_table (uint32_t node_id, uint32_t source_id)
void add_execution_plan_table (uint32_t node_id, const std::vector< uint32_t > &execution_plan_inform)
const std::vector< uint8_t > encoded_source_table (void)
const std::vector< uint8_t > encoded_op_table (void)
const std::vector< uint8_t > encoded_execution_plan_table (void)
Detailed Description
Definition at line 52 of file SerializedData.h.
Member Function Documentation
add_execution_plan_table()
void luci::CircleExportMetadata::add_execution_plan_table (uint32_t node_id, const std::vector< uint32_t > & execution_plan_inform) inline
Definition at line 67 of file SerializedData.h.
  {
    _execution_plan_table[node_id] = execution_plan_inform;
  }
Referenced by luci::exportNodes().
add_op_table()
void luci::CircleExportMetadata::add_op_table (uint32_t node_id, uint32_t source_id) inline
Definition at line 57 of file SerializedData.h.
  {
    // Model with multiple subgraph may have duplicated node id.
    // For now, as we do not consider about multiple subgraph in profiling,
    // just ignore those cases and support them in the future.
    if (_op_table.find(node_id) == _op_table.end())
      _op_table.emplace(node_id, std::set<uint32_t>());
    _op_table.at(node_id).emplace(source_id);
  }
Referenced by luci::exportNodes().
encoded_execution_plan_table()
const std::vector< uint8_t > luci::CircleExportMetadata::encoded_execution_plan_table (void)
Definition at line 48 of file CircleExportMetadata.cpp.
{
  std::vector<uint8_t> data;
  write_u32(data, _execution_plan_table.size());
  for (auto &kv : _execution_plan_table)
  {
    const auto id = kv.first;
    write_u32(data, id);
    const auto plan_vector = kv.second;
    const auto size = plan_vector.size();
    write_u32(data, size);
    for (auto elem : plan_vector)
    {
      write_u32(data, elem);
    }
  }
  return data;
}
Referenced by luci::createCircleMetadataVector().
encoded_op_table()
const std::vector< uint8_t > luci::CircleExportMetadata::encoded_op_table (void)
Definition at line 99 of file CircleExportMetadata.cpp.
{
  std::vector<uint8_t> data;
  write_u32(data, _op_table.size());
  for (auto &kv : _op_table)
  {
    const auto id = kv.first;
    write_u32(data, id);
    const auto origins = kv.second;
    const auto node_num = origins.size();
    write_u32(data, node_num);
    for (auto origin : origins)
    {
      write_u32(data, origin);
    }
  }
  return data;
}
Referenced by luci::createCircleMetadataVector().
encoded_source_table()
const std::vector< uint8_t > luci::CircleExportMetadata::encoded_source_table (void)
Definition at line 73 of file CircleExportMetadata.cpp.
{
  std::vector<uint8_t> data;
  write_u32(data, _source_table.size());
  for (auto &kv : _source_table)
  {
    const auto id = kv.first;
    write_u32(data, id);
    const auto origin_name = kv.second;
    const auto length = origin_name.length();
    write_u32(data, length + 1); // name + '\0
    for (uint32_t i = 0; i < length; ++i)
    {
      data.emplace_back(origin_name.at(i));
    }
    data.emplace_back('\0');
  }
  return data;
}
Referenced by luci::createCircleMetadataVector().
source_table()
void luci::CircleExportMetadata::source_table (const std::map< uint32_t, std::string > & table) inline
Definition at line 55 of file SerializedData.h.
{ _source_table = table; }
The documentation for this class was generated from the following files:
compiler/luci/export/src/SerializedData.h
compiler/luci/export/src/CircleExportMetadata.cpp