ONE - On-device Neural Engine: luci::GraphBuilderContext Class Reference
luci::GraphBuilderContext Class Reference
Class to store context to build loco graph IR from TensorFlow.
#include <GraphBuilderContext.h>
Public Member Functions
GraphBuilderContext (loco::Graph *g, CircleReader *reader, IndexNodeFinder *nodefinder, IndexTensorOutputs *tensoroutputs)
GraphBuilderContext (const GraphBuilderContext &)=delete
GraphBuilderContext (GraphBuilderContext &&)=delete
loco::Graph * graph ()
CircleReader * reader ()
IndexNodeFinder * nodefinder ()
IndexTensorOutputs * tensoroutputs ()
Detailed Description
Class to store context to build loco graph IR from TensorFlow.
Definition at line 69 of file GraphBuilderContext.h.
Constructor & Destructor Documentation
GraphBuilderContext() [1/3]
luci::GraphBuilderContext::GraphBuilderContext (loco::Graph * g, CircleReader * reader, IndexNodeFinder * nodefinder, IndexTensorOutputs * tensoroutputs) inline
Definition at line 72 of file GraphBuilderContext.h.
    : _g(g), _reader(reader), _indexnodefinder(nodefinder), _indextensoroutputs(tensoroutputs)
  {
    // DO NOTHING
  }
GraphBuilderContext() [2/3]
luci::GraphBuilderContext::GraphBuilderContext (const GraphBuilderContext &) delete
GraphBuilderContext() [3/3]
luci::GraphBuilderContext::GraphBuilderContext (GraphBuilderContext &&) delete
Member Function Documentation
graph()
loco::Graph * luci::GraphBuilderContext::graph () inline
Definition at line 83 of file GraphBuilderContext.h.
{ return _g; }
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::CircleWhileGraphBuilder::build(), luci_interpreter::CircleReferencingConstNodeBuilder::build(), luci::CircleConstNodeBuilder::build(), luci::create_circlevariable(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
nodefinder()
IndexNodeFinder * luci::GraphBuilderContext::nodefinder () inline
Definition at line 86 of file GraphBuilderContext.h.
{ return _indexnodefinder; }
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), and luci::CircleWhileGraphBuilder::build().
reader()
CircleReader * luci::GraphBuilderContext::reader () inline
Definition at line 84 of file GraphBuilderContext.h.
{ return _reader; }
Referenced by luci::GraphBuilder::build(), luci::GraphBuilderMultiOutput::build(), luci::CircleWhileGraphBuilder::build(), luci_interpreter::CircleReferencingConstNodeBuilder::build(), luci::CircleConstNodeBuilder::build(), and luci::create_circlevariable().
tensoroutputs()
IndexTensorOutputs * luci::GraphBuilderContext::tensoroutputs () inline
Definition at line 87 of file GraphBuilderContext.h.
{ return _indextensoroutputs; }
Referenced by luci_interpreter::CircleReferencingConstNodeBuilder::build(), and luci::CircleConstNodeBuilder::build().
The documentation for this class was generated from the following file:
compiler/luci/import/include/luci/Import/GraphBuilderContext.h