ONE - On-device Neural Engine: locoex::TFLFullyConnected Class Reference
locoex::TFLFullyConnected Class Reference final
FULLY_CONNECTED in TensorFlow Lite.
#include <TFLNodes.h>
Public Member Functions
loco::Node * input (void) const
void input (loco::Node *node)
loco::Node * weights (void) const
void weights (loco::Node *node)
loco::Node * bias (void) const override
void bias (loco::Node *node) override
get the input for bias.
Public Member Functions inherited from locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from locoex::TFLNodeImpl< TFLOpcode::FULLY_CONNECTED >
virtual ~TFLNodeImpl ()=default
uint32_t opnum (void) const final
TFLOpcode opcode (void) const final
Public Member Functions inherited from locoex::TFLNode
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFLOpcode opcode (void) const =0
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::FusedActFunc >
TFLNodeMixin ()=default
FusedActFunc fusedActivationFunction () const
void fusedActivationFunction (FusedActFunc fused_act_fun)
Public Member Functions inherited from locoex::TFLNodeMixin< TFLNodeTrait::Bias >
TFLNodeMixin ()=default
virtual loco::Node * bias (void) const =0
virtual void bias (loco::Node *node)=0
get the input for bias.
Additional Inherited Members
Protected Member Functions inherited from locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >
loco::Use * at (unsigned n) const
Detailed Description
FULLY_CONNECTED in TensorFlow Lite.
Definition at line 295 of file TFLNodes.h.
Member Function Documentation
bias() [1/2]
void locoex::TFLFullyConnected::bias (loco::Node * node) inline override virtual
get the input for bias.
Implements locoex::TFLNodeMixin< TFLNodeTrait::Bias >.
Definition at line 307 of file TFLNodes.h.
{ at(2)->node(node); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
bias() [2/2]
loco::Node * locoex::TFLFullyConnected::bias (void) const inline override virtual
Implements locoex::TFLNodeMixin< TFLNodeTrait::Bias >.
Definition at line 306 of file TFLNodes.h.
{ return at(2)->node(); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
input() [1/2]
void locoex::TFLFullyConnected::input (loco::Node * node) inline
Definition at line 301 of file TFLNodes.h.
{ at(0)->node(node); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
input() [2/2]
loco::Node * locoex::TFLFullyConnected::input (void) const inline
Definition at line 300 of file TFLNodes.h.
{ return at(0)->node(); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
weights() [1/2]
void locoex::TFLFullyConnected::weights (loco::Node * node) inline
Definition at line 304 of file TFLNodes.h.
{ at(1)->node(node); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
weights() [2/2]
loco::Node * locoex::TFLFullyConnected::weights (void) const inline
Definition at line 303 of file TFLNodes.h.
{ return at(1)->node(); }
References locoex::FixedArityNode< 3, TFLNodeImpl< TFLOpcode::FULLY_CONNECTED > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/exo/src/Dialect/IR/TFLNodes.h