ONE - On-device Neural Engine: locomotiv::NodeExecution Class Reference
locomotiv::NodeExecution Class Reference
Helper class for Session, responsible to process one node calculation.
#include <NodeExecution.h>
Public Member Functions
void run (loco::Node *node)
Run calculation for one unspecified Node.
Static Public Member Functions
static NodeExecution & get ()
Detailed Description
Helper class for Session, responsible to process one node calculation.
Definition at line 45 of file NodeExecution.h.
Member Function Documentation
get()
static NodeExecution & locomotiv::NodeExecution::get () inline static
Definition at line 51 of file NodeExecution.h.
  {
    static NodeExecution me;
    return me;
  }
Referenced by locomotiv::Session::infer().
run()
void locomotiv::NodeExecution::run (loco::Node * node)
Run calculation for one unspecified Node.
Definition at line 54 of file NodeExecution.cpp.
{
  erase_annot_data(node);
#define NODE(Name)                 \
  if (as<loco::Name>(node))        \
  {                                \
    execute(as<loco::Name>(node)); \
    return;                        \
  }
#include "Node.lst"
#undef NODE
  throw std::runtime_error("Not supported loco::Node type");
}
References locomotiv::erase_annot_data().
Referenced by locomotiv::Session::infer().
The documentation for this class was generated from the following files:
compiler/locomotiv/src/NodeExecution.h
compiler/locomotiv/src/NodeExecution.cpp