ONE - On-device Neural Engine: loco::Permutation< Domain::Filter > Class Reference
loco::Permutation< Domain::Filter > Class Reference
Mapping between Filter/Tensor Axis.
#include <PermutingCodec.h>
Public Member Functions
Permutation ()=default
bool mapped (const FilterAxis &axis_f) const
Return whether a given filter axis has a corresponding tensor axis.
const TensorAxis & axis (const FilterAxis &axis_f) const
Get the tensor axis corresponding to a given filter axis.
TensorAxis & axis (const FilterAxis &axis_f)
Set the tensor axis corresponding to a given filter axis.
TensorAxis operator[] (const FilterAxis &axis_f) const
TensorAxis & operator[] (const FilterAxis &axis_f)
Detailed Description
Mapping between Filter/Tensor Axis.
Definition at line 137 of file PermutingCodec.h.
Constructor & Destructor Documentation
Permutation()
loco::Permutation< Domain::Filter >::Permutation () default
Member Function Documentation
axis() [1/2]
uint32_t & loco::Permutation< Domain::Filter >::axis (const FilterAxis & axis_f)
Set the tensor axis corresponding to a given filter axis.
Definition at line 264 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid filter axis");
  return _map[axis_f];
}
References loco::valid().
axis() [2/2]
const uint32_t & loco::Permutation< Domain::Filter >::axis (const FilterAxis & axis_f) const
Get the tensor axis corresponding to a given filter axis.
This method works correctly only for mapped filter axes.
Definition at line 257 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid filter axis");
  assert(mapped(axis_f) && "unmapped filter axis");
  return _map.at(axis_f);
}
References loco::valid().
mapped()
bool loco::Permutation< Domain::Filter >::mapped (const FilterAxis & axis_f) const
Return whether a given filter axis has a corresponding tensor axis.
This method does not validate the corresponding value.
Definition at line 251 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid filter axis");
  return _map.find(axis_f) != _map.end();
}
References loco::valid().
operator[]() [1/2]
TensorAxis & loco::Permutation< Domain::Filter >::operator[] (const FilterAxis & axis_f) inline
Definition at line 163 of file PermutingCodec.h.
{ return axis(axis_f); }
operator[]() [2/2]
TensorAxis loco::Permutation< Domain::Filter >::operator[] (const FilterAxis & axis_f) const inline
Definition at line 162 of file PermutingCodec.h.
{ return axis(axis_f); }
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp