ONE - On-device Neural Engine: onert::exec::TracingObserver Class Reference
onert::exec::TracingObserver Class Reference
#include <ExecutionObservers.h>
Public Member Functions
TracingObserver (const std::string &filepath, const ir::Graph &graph, const util::TracingCtx *tracing_ctx)
~TracingObserver ()
void handleSubgraphBegin (ir::SubgraphIndex) override
Invoked just before model (not individual operation) execution begins.
void handleJobBegin (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *) override
void handleJobEnd (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *) override
void handleSubgraphEnd (ir::SubgraphIndex) override
Invoked just after model (not individual operation) execution ends.
Public Member Functions inherited from onert::exec::IExecutionObserver
virtual void handleSubgraphBegin (ir::SubgraphIndex)
Invoked just before model (not individual operation) execution begins.
virtual void handleJobBegin (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *)=0
virtual void handleJobEnd (IExecutor *, ir::SubgraphIndex, ir::OperationIndex, const backend::Backend *)=0
virtual void handleSubgraphEnd (ir::SubgraphIndex)
Invoked just after model (not individual operation) execution ends.
virtual ~IExecutionObserver ()=default
Detailed Description
Definition at line 72 of file ExecutionObservers.h.
Constructor & Destructor Documentation
TracingObserver()
onert::exec::TracingObserver::TracingObserver (const std::string & filepath, const ir::Graph & graph, const util::TracingCtx * tracing_ctx)
Definition at line 116 of file ExecutionObservers.cc.
  : _recorder{std::make_unique<EventRecorder>()}, _collector{_recorder.get()}, _graph{graph},
    _tracing_ctx{tracing_ctx}
{
  _event_writer = EventWriter::get(filepath);
  _event_writer->startToUse();
}
References EventWriter::get(), and EventWriter::startToUse().
~TracingObserver()
onert::exec::TracingObserver::~TracingObserver ()
Definition at line 125 of file ExecutionObservers.cc.
{
  try
  {
    _event_writer->readyToFlush(std::move(_recorder));
  }
  catch (const std::exception &e)
  {
    std::cerr << "E: Fail to record event in TracingObserver: " << e.what() << std::endl;
  }
}
References EventWriter::readyToFlush().
Member Function Documentation
handleJobBegin()
void onert::exec::TracingObserver::handleJobBegin (IExecutor * , ir::SubgraphIndex subg_ind, ir::OperationIndex op_ind, const backend::Backend * backend) override virtual
Implements onert::exec::IExecutionObserver.
Definition at line 143 of file ExecutionObservers.cc.
{
  std::string backend_id = backend->config()->id();
  const auto &op = _graph.operations().at(op_ind);
  auto ev = EventCollector::OpSeqEvent{_tracing_ctx,     EventCollector::Edge::BEGIN,
                                       subg_ind.value(), backend_id,
                                       op_ind.value(),   op.name()};
  // add shape of inputs
  setUserData(_graph, &op, ev.userData);
  _collector.onEvent(ev);
}
References onert::util::ObjectManager< Index, Object >::at(), EventCollector::BEGIN, onert::backend::Backend::config(), onert::ir::Operation::name(), EventCollector::onEvent(), onert::ir::Graph::operations(), and onert::util::Index< T, DummyTag >::value().
handleJobEnd()
void onert::exec::TracingObserver::handleJobEnd (IExecutor * , ir::SubgraphIndex subg_ind, ir::OperationIndex op_ind, const backend::Backend * backend) override virtual
Implements onert::exec::IExecutionObserver.
Definition at line 156 of file ExecutionObservers.cc.
{
  std::string backend_id = backend->config()->id();
  _collector.onEvent(EventCollector::OpSeqEvent{_tracing_ctx, EventCollector::Edge::END,
                                                subg_ind.value(), backend_id, op_ind.value(),
                                                _graph.operations().at(op_ind).name()});
}
References onert::util::ObjectManager< Index, Object >::at(), onert::backend::Backend::config(), EventCollector::END, EventCollector::onEvent(), onert::ir::Graph::operations(), and onert::util::Index< T, DummyTag >::value().
handleSubgraphBegin()
void onert::exec::TracingObserver::handleSubgraphBegin (ir::SubgraphIndex) override virtual
Invoked just before model (not individual operation) execution begins.
Reimplemented from onert::exec::IExecutionObserver.
Definition at line 137 of file ExecutionObservers.cc.
{
  _collector.onEvent(
    EventCollector::SubgEvent{_tracing_ctx, EventCollector::Edge::BEGIN, subg_ind.value()});
}
References EventCollector::BEGIN, EventCollector::onEvent(), and onert::util::Index< T, DummyTag >::value().
handleSubgraphEnd()
void onert::exec::TracingObserver::handleSubgraphEnd (ir::SubgraphIndex) override virtual
Invoked just after model (not individual operation) execution ends.
Reimplemented from onert::exec::IExecutionObserver.
Definition at line 165 of file ExecutionObservers.cc.
{
  _collector.onEvent(
    EventCollector::SubgEvent{_tracing_ctx, EventCollector::Edge::END, subg_ind.value()});
}
References EventCollector::END, EventCollector::onEvent(), and onert::util::Index< T, DummyTag >::value().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/ExecutionObservers.h
runtime/onert/core/src/exec/ExecutionObservers.cc