ONE - On-device Neural Engine: circleinspect::DumpConstants Class Reference
circleinspect::DumpConstants Class Reference final
#include <Dump.h>
Public Member Functions
DumpConstants ()=default
void run (std::ostream &os, const circle::Model *model)
Public Member Functions inherited from circleinspect::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const circle::Model *model)=0
Detailed Description
Definition at line 72 of file Dump.h.
Constructor & Destructor Documentation
DumpConstants()
circleinspect::DumpConstants::DumpConstants () default
Member Function Documentation
run()
void circleinspect::DumpConstants::run (std::ostream & os, const circle::Model * model) virtual
Implements circleinspect::DumpInterface.
Definition at line 209 of file Dump.cpp.
{
  mio::circle::Reader reader(model);
  const uint32_t subgraph_size = reader.num_subgraph();
  for (uint32_t g = 0; g < subgraph_size; g++)
  {
    reader.select_subgraph(g);
    auto tensors = reader.tensors();
    for (uint32_t i = 0; i < tensors->Length(); ++i)
    {
      const auto tensor = tensors->Get(i);
      if (tensor->is_variable())
        continue;
      auto const buffer_id = tensor->buffer();
      auto const buffer_size = reader.buffer_info(buffer_id, nullptr);
      if (buffer_size == 0)
        continue;
      os << reader.tensor_name(tensor) << std::endl;
    }
  }
}
References mio::circle::Reader::buffer_info(), mio::circle::Reader::num_subgraph(), mio::circle::Reader::select_subgraph(), mio::circle::Reader::tensor_name(), and mio::circle::Reader::tensors().
The documentation for this class was generated from the following files:
compiler/circle-inspect/src/Dump.h
compiler/circle-inspect/src/Dump.cpp