ONE - On-device Neural Engine: onert::exec::ExecutorBase Class Reference
onert::exec::ExecutorBase Class Reference abstract
#include <ExecutorBase.h>
Public Member Functions
ExecutorBase (std::unique_ptr< compiler::LoweredGraph > &&lowered_graph, backend::BackendContexts &&backend_contexts, const compiler::TensorRegistries &tensor_regs, const util::TracingCtx *tracing_ctx)
Construct a new ExecutorBase object.
virtual ~ExecutorBase ()=default
const ir::Graph & graph () const final
Returns graph object.
void execute (const IODescription &desc) final
Execute with user-given input/output description (for primary subgraph)
void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs) override
Execute with given input/output tensors.
void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > > ranks) final
Set an ordering on operations.
virtual void executeImpl (void)=0
void addObserver (std::unique_ptr< IExecutionObserver > ref)
const std::vector< backend::builtin::IOTensor * > & getOutputTensors () const override
Get output tensor objects.
Public Member Functions inherited from onert::exec::IExecutor
IExecutor ()=default
Construct a new IExecutor object.
virtual ~IExecutor ()=default
Destroy the IExecutor object.
virtual const ir::Graph & graph () const =0
Returns graph object.
virtual void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >)=0
Set an ordering on operations.
virtual void execute (const IODescription &desc)=0
Execute with user-given input/output description (for primary subgraph)
virtual void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs)=0
Execute with given input/output tensors.
virtual const std::vector< backend::builtin::IOTensor * > & getOutputTensors () const =0
Get output tensor objects.
Protected Member Functions
bool hasDynamicInput ()
Returns true if any input tensor is dynamic; false if all are static tensors.
Protected Attributes
ExecutionObservee _subject
std::shared_ptr< ir::OperationIndexMap< int64_t > > _indexed_ranks
std::unique_ptr< compiler::LoweredGraph > _lowered_graph
backend::BackendContexts _backend_contexts
const ir::Graph & _graph
std::vector< backend::builtin::IOTensor * > _input_tensors
std::vector< backend::builtin::IOTensor * > _output_tensors
std::mutex _mutex
const util::TracingCtx * _tracing_ctx
Detailed Description
Definition at line 40 of file ExecutorBase.h.
Constructor & Destructor Documentation
ExecutorBase()
onert::exec::ExecutorBase::ExecutorBase (std::unique_ptr< compiler::LoweredGraph > && lowered_graph, backend::BackendContexts && backend_contexts, const compiler::TensorRegistries & tensor_regs, const util::TracingCtx * tracing_ctx)
Construct a new ExecutorBase object.
Parameters
graph Graph object
tensor_builders Tensor builders that are currently used
Definition at line 28 of file ExecutorBase.cc.
  : _lowered_graph{std::move(lowered_graph)},
    _backend_contexts{std::move(backend_contexts)}, _graph{_lowered_graph->graph()}, _mutex(),
    _tracing_ctx(tracing_ctx)
{
  auto build_tensor_list = [&](const auto &ind_seq, auto &tensors) {
    assert(tensors.empty());
    for (auto ind : ind_seq)
    {
      backend::ITensor *tensor = tensor_regs.getITensor(ind);
      assert(tensor != nullptr);
      auto io_tensor = nnfw::misc::polymorphic_downcast<backend::builtin::IOTensor *>(tensor);
      tensors.push_back(io_tensor);
    }
  };
  build_tensor_list(_graph.getInputs(), _input_tensors);
  build_tensor_list(_graph.getOutputs(), _output_tensors);
}
References _graph, _input_tensors, _output_tensors, onert::ir::Graph::getInputs(), onert::compiler::TensorRegistries::getITensor(), and onert::ir::Graph::getOutputs().
~ExecutorBase()
virtual onert::exec::ExecutorBase::~ExecutorBase () virtual default
Member Function Documentation
addObserver()
void onert::exec::ExecutorBase::addObserver (std::unique_ptr< IExecutionObserver > ref) inline
Definition at line 69 of file ExecutorBase.h.
{ _subject.add(std::move(ref)); };
References _subject, and onert::exec::ExecutionObservee::add().
execute() [1/2]
void onert::exec::ExecutorBase::execute (const IODescription & desc) final virtual
Execute with user-given input/output description (for primary subgraph)
Parameters
[in] desc Input and output description
Note
This method should be thread-safe
Implements onert::exec::IExecutor.
Definition at line 100 of file ExecutorBase.cc.
{
  // For thread-safe, use mutex
  // TODO: if all used backends on this executor are thread-safe,
  //       do not need to use mutex (otherwise, use mutex)
  std::lock_guard<std::mutex> lock(_mutex);
  // Set input(s)
  assert(_input_tensors.size() == desc.inputs.size());
  for (uint32_t i = 0; i < _input_tensors.size(); ++i)
  {
    auto tensor = _input_tensors[i];
    // TODO Check if (desc.inputs[i] == nullptr)
    // TODO Better design for ITensor? (we need const_cast as ITensor is writable)
    tensor->setUserTensor(static_cast<uint8_t *>(const_cast<void *>(desc.inputs[i]->buffer)),
                          desc.inputs[i]->size);
    auto input_shape = desc.dynamic_input_shapes.find(ir::IOIndex{i});
    if (input_shape != desc.dynamic_input_shapes.end())
    {
      tensor->set_dynamic();
      tensor->setShape(input_shape->second);
      /*
       * Changes tensor shape and allocate memory since its shape was changed
       * perhaps by nnfw_set_input_tensorinfo()
       *
       * Cases are:
       * 1) static operand -> nnfw_set_input_tensorinfo() -> execute() -> execute()
       *                                                 (a)          (b)
       *
       * at (a), operand is static, tensor is static - memory dealloc is not needed
       *   (DynamicTensorManager cannot dealloc memory allocated by StaticTensorManager)
       * at (b), operand is static, tensor is dynamic - memory dealloc is needed
       *
       * 2) dynamic operand -> nnfw_set_input_tensorinfo() -> execute() -> execute()
       *                                                  (a)          (b)
       *
       * at (a), operand is dynamic, tensor is dynamic - memory dealloc is not needed
       *                                       since it has not been allocated yet
       * at (b), operand is dynamic, tensor is dynamic - memory dealloc is needed
       */
      tensor->applyShape(input_shape->second);
    }
  }
  assert(_output_tensors.size() == desc.outputs.size());
  for (uint32_t i = 0; i < _output_tensors.size(); ++i)
  {
    auto tensor = _output_tensors[i];
    if (desc.outputs[i] == nullptr)
      throw std::runtime_error{"Output " + std::to_string(i) + "'s buffer is not set."};
    tensor->setUserTensor(static_cast<uint8_t *>(desc.outputs[i]->buffer), desc.outputs[i]->size);
    tensor->set_dynamic(); // It can't be resized but shape could change
  }
  executeImpl();
  // Update output(s) desc
  for (uint32_t n = 0; n < _graph.getOutputs().size(); ++n)
  {
    ir::IOIndex output_index{n};
    // Optional output
    if (desc.outputs.at(n) == nullptr)
    {
      continue;
    }
    auto &output = *desc.outputs.at(n);
    // set shape of outputDesc to tensor shape since tensor can be dynamic
    const auto output_tensor_shape = _output_tensors[n]->getShape();
    output.info.shape(
      convertShape(output_tensor_shape, _output_tensors[n]->layout(), output.layout));
  }
}
References _graph, _input_tensors, _mutex, _output_tensors, onert::exec::convertShape(), onert::exec::IODescription::dynamic_input_shapes, executeImpl(), onert::ir::Graph::getOutputs(), onert::exec::IODescription::inputs, and onert::exec::IODescription::outputs.
execute() [2/2]
void onert::exec::ExecutorBase::execute (const std::vector< backend::IPortableTensor * > & inputs, const std::vector< backend::IPortableTensor * > & outputs) override virtual
Execute with given input/output tensors.
For non-primary subgraphs, input and output tensors must be given.
Parameters
[in] inputs tensors that are passed as inputs
[in] outputs tensors that are passed as outputs
Implements onert::exec::IExecutor.
Definition at line 50 of file ExecutorBase.cc.
{
  // For thread-safe, use mutex
  // TODO: if all used backends on this executor are thread-safe,
  //       do not need to use mutex (otherwise, use mutex)
  // Deadlock occurs when an Executor is called recursively.
  std::lock_guard<std::mutex> lock(_mutex);
  assert(inputs.size() == _graph.getInputs().size());
  assert(inputs.size() == _input_tensors.size());
  for (uint32_t n = 0; n < inputs.size(); ++n)
  {
    const auto input = inputs[n];
    assert(input->buffer() != nullptr);
    auto input_tensor = _input_tensors[n];
    assert(input_tensor != nullptr);
    if (input != nullptr)
    {
      const auto orig_input_shape = input_tensor->orig_info().shape();
      const auto changed_input_shape =
        convertShape(input->getShape(), input->layout(), input_tensor->orig_layout());
      if (input_tensor->get_info().shape() != changed_input_shape)
      {
        // TODO Fix this workaround that is introduced since cpu based kernels directly use `_info`
        // rather than interface methods to avoid virtual function calls.
        input_tensor->setShapeOfIPortableTensor(changed_input_shape);
      }
      if (orig_input_shape != changed_input_shape)
      {
        input_tensor->set_dynamic();
      }
    }
    input_tensor->setTensor(input);
  }
  assert(outputs.size() == _graph.getOutputs().size());
  assert(outputs.size() == _output_tensors.size());
  for (uint32_t n = 0; n < outputs.size(); ++n)
  {
    const auto output = outputs[n];
    // assert(dst_tensor->buffer() != nullptr);
    auto output_tensor = _output_tensors[n];
    assert(output_tensor != nullptr);
    output_tensor->setTensor(output);
  }
  executeImpl();
}
References _graph, _input_tensors, _mutex, _output_tensors, onert::exec::convertShape(), executeImpl(), onert::ir::Graph::getInputs(), onert::ir::Graph::getOutputs(), and onert::ir::OperandIndexSequence::size().
executeImpl()
virtual void onert::exec::ExecutorBase::executeImpl (void) pure virtual
Implemented in onert::exec::DataflowExecutor, onert::exec::ParallelExecutor, and onert::exec::LinearExecutor.
Referenced by execute().
getOutputTensors()
const std::vector< backend::builtin::IOTensor * > & onert::exec::ExecutorBase::getOutputTensors () const inline override virtual
Get output tensor objects.
Returns
Vector of IOTensor
Implements onert::exec::IExecutor.
Definition at line 71 of file ExecutorBase.h.
  {
    return _output_tensors;
  }
References _output_tensors.
graph()
const ir::Graph & onert::exec::ExecutorBase::graph () const inline final virtual
Returns graph object.
Returns
Graph object
Implements onert::exec::IExecutor.
Definition at line 54 of file ExecutorBase.h.
{ return _graph; }
References _graph.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
hasDynamicInput()
bool onert::exec::ExecutorBase::hasDynamicInput () protected
Returns true if any input tensor is dynamic; false if all are static tensors.
Definition at line 177 of file ExecutorBase.cc.
{
  for (auto &tensor : _input_tensors)
  {
    if (tensor->is_dynamic())
      return true;
  }
  return false;
}
References _input_tensors.
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::ParallelExecutor::executeImpl(), and onert::exec::LinearExecutor::executeImpl().
setIndexedRanks()
void onert::exec::ExecutorBase::setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >) inline final virtual
Set an ordering on operations.
Parameters
[in] ranks The table encoding the ordering
Implements onert::exec::IExecutor.
Definition at line 62 of file ExecutorBase.h.
  {
    _indexed_ranks = std::move(ranks);
  };
References _indexed_ranks.
Field Documentation
_backend_contexts
backend::BackendContexts onert::exec::ExecutorBase::_backend_contexts protected
Definition at line 86 of file ExecutorBase.h.
_graph
const ir::Graph& onert::exec::ExecutorBase::_graph protected
Definition at line 87 of file ExecutorBase.h.
Referenced by onert::exec::DataflowExecutor::calculateRank(), execute(), onert::exec::DataflowExecutor::executeImpl(), onert::exec::ParallelExecutor::executeImpl(), onert::exec::LinearExecutor::executeImpl(), ExecutorBase(), and graph().
_indexed_ranks
std::shared_ptr<ir::OperationIndexMap<int64_t> > onert::exec::ExecutorBase::_indexed_ranks protected
Definition at line 84 of file ExecutorBase.h.
Referenced by onert::exec::DataflowExecutor::calculateRank(), and setIndexedRanks().
_input_tensors
std::vector<backend::builtin::IOTensor *> onert::exec::ExecutorBase::_input_tensors protected
Definition at line 88 of file ExecutorBase.h.
Referenced by execute(), ExecutorBase(), and hasDynamicInput().
_lowered_graph
std::unique_ptr<compiler::LoweredGraph> onert::exec::ExecutorBase::_lowered_graph protected
Definition at line 85 of file ExecutorBase.h.
Referenced by onert::exec::DataflowExecutor::DataflowExecutor(), onert::exec::DataflowExecutor::executeImpl(), onert::exec::ParallelExecutor::executeImpl(), and onert::exec::LinearExecutor::executeImpl().
_mutex
std::mutex onert::exec::ExecutorBase::_mutex protected
Definition at line 90 of file ExecutorBase.h.
Referenced by execute().
_output_tensors
std::vector<backend::builtin::IOTensor *> onert::exec::ExecutorBase::_output_tensors protected
Definition at line 89 of file ExecutorBase.h.
Referenced by execute(), ExecutorBase(), and getOutputTensors().
_subject
ExecutionObservee onert::exec::ExecutorBase::_subject protected
Definition at line 83 of file ExecutorBase.h.
Referenced by addObserver(), onert::exec::DataflowExecutor::executeImpl(), onert::exec::ParallelExecutor::executeImpl(), and onert::exec::LinearExecutor::executeImpl().
_tracing_ctx
const util::TracingCtx* onert::exec::ExecutorBase::_tracing_ctx protected
Definition at line 91 of file ExecutorBase.h.
Referenced by onert::exec::DataflowExecutor::executeImpl(), onert::exec::ParallelExecutor::executeImpl(), and onert::exec::LinearExecutor::executeImpl().
The documentation for this class was generated from the following files:
runtime/onert/core/src/exec/ExecutorBase.h
runtime/onert/core/src/exec/ExecutorBase.cc