ONE - On-device Neural Engine: nnkit::support::tf::TensorContext Class Reference
nnkit::support::tf::TensorContext Class Reference final
#include <TensorContext.h>
Public Member Functions
TensorContext (const std::vector< std::unique_ptr< ParsedTensor > > &tensors, TensorDataMap &data_map)
TensorContext (const TensorContext &)=delete
TensorContext (TensorContext &&)=delete
uint32_t size (void) const override
std::string name (uint32_t n) const override
nncc::core::ADT::tensor::Shape shape (uint32_t n) const override
bool isFloatTensor (uint32_t n) const override
void getMutableFloatTensor (uint32_t n, const nnkit::TensorContext::TypedAccessor< float > &f) override
void getConstFloatTensor (uint32_t n, const nnkit::TensorContext::TypedReader< float > &f) const override
Public Member Functions inherited from nnkit::TensorContext
virtual ~TensorContext ()=default
virtual uint32_t size (void) const =0
virtual std::string name (uint32_t n) const =0
virtual nncc::core::ADT::tensor::Shape shape (uint32_t n) const =0
virtual bool isFloatTensor (uint32_t n) const
virtual void getMutableFloatTensor (uint32_t n, const TypedAccessor< float > &cb)
virtual void getConstFloatTensor (uint32_t n, const TypedReader< float > &cb) const
virtual bool isS32Tensor (uint32_t n) const
virtual void getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > &cb)
virtual void getConstS32Tensor (uint32_t n, const TypedReader< int32_t > &cb) const
Additional Inherited Members
Public Types inherited from nnkit::TensorContext
template<typename T >
using TypedReader = std::function< void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader< T > &)>
template<typename T >
using TypedAccessor = std::function< void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor< T > &)>
Detailed Description
Definition at line 35 of file TensorContext.h.
Constructor & Destructor Documentation
TensorContext() [1/3]
nnkit::support::tf::TensorContext::TensorContext (const std::vector< std::unique_ptr< ParsedTensor > > & tensors, TensorDataMap & data_map) inline
Definition at line 38 of file TensorContext.h.
    : _tensors(tensors), _data_map(data_map)
  {
    // empty
  }
TensorContext() [2/3]
nnkit::support::tf::TensorContext::TensorContext (const TensorContext &) delete
TensorContext() [3/3]
nnkit::support::tf::TensorContext::TensorContext (TensorContext &&) delete
Member Function Documentation
getConstFloatTensor()
void nnkit::support::tf::TensorContext::getConstFloatTensor (uint32_t n, const nnkit::TensorContext::TypedReader< float > & f) const override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 45 of file TensorContext.cpp.
{ // for output
  using nncc::core::ADT::tensor::LexicalLayout;
  using nncc::core::ADT::tensor::make_overlay;
  const ParsedTensor *parsed_tensor = _tensors.at(n).get();
  float *data = reinterpret_cast<float *>(_data_map.data(parsed_tensor));
  auto overlay = make_overlay<float, LexicalLayout>(shape(n), data);
  f(*this, n, overlay);
}
References nnkit::support::tf::TensorDataMap::data(), nncc::core::ADT::tensor::make_overlay(), and shape().
getMutableFloatTensor()
void nnkit::support::tf::TensorContext::getMutableFloatTensor (uint32_t n, const nnkit::TensorContext::TypedAccessor< float > & f) override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 32 of file TensorContext.cpp.
{ // for input
  using nncc::core::ADT::tensor::LexicalLayout;
  using nncc::core::ADT::tensor::make_overlay;
  const ParsedTensor *parsed_tensor = _tensors.at(n).get();
  float *data = reinterpret_cast<float *>(_data_map.data(parsed_tensor));
  auto overlay = make_overlay<float, LexicalLayout>(shape(n), data);
  f(*this, n, overlay);
}
References nnkit::support::tf::TensorDataMap::data(), nncc::core::ADT::tensor::make_overlay(), and shape().
isFloatTensor()
bool nnkit::support::tf::TensorContext::isFloatTensor (uint32_t n) const inline override virtual
Reimplemented from nnkit::TensorContext.
Definition at line 64 of file TensorContext.h.
{ return _tensors.at(n)->isFloatTensor(); }
name()
std::string nnkit::support::tf::TensorContext::name (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 51 of file TensorContext.h.
  {
    return _tensors.at(n)->name();
  }
shape()
nncc::core::ADT::tensor::Shape nnkit::support::tf::TensorContext::shape (uint32_t n) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 57 of file TensorContext.h.
  {
    return _tensors.at(n)->shape();
  }
Referenced by getConstFloatTensor(), and getMutableFloatTensor().
size()
uint32_t nnkit::support::tf::TensorContext::size (void) const inline override virtual
Implements nnkit::TensorContext.
Definition at line 48 of file TensorContext.h.
{ return _tensors.size(); }
The documentation for this class was generated from the following files:
compiler/nnkit-tf/support/include/nnkit/support/tf/TensorContext.h
compiler/nnkit-tf/support/src/TensorContext.cpp