ONE - On-device Neural Engine: arm_compute::CLTransposeConvLayer Class Reference
arm_compute::CLTransposeConvLayer Class Reference
#include <CLTransposeConvLayer.h>
Public Member Functions
CLTransposeConvLayer (std::shared_ptr< IMemoryManager > memory_manager=nullptr)
void configure (ICLTensor *input, ICLTensor *weights, const ICLTensor *bias, ICLTensor *output, const PadStrideInfo &deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo &weights_info=WeightsInfo())
void configure (const CLCompileContext &compile_context, ICLTensor *input, ICLTensor *weights, const ICLTensor *bias, ICLTensor *output, const PadStrideInfo &deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo &weights_info=WeightsInfo())
void run () override
void prepare () override
Static Public Member Functions
static Status validate (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *output, const PadStrideInfo &deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo &weights_info=WeightsInfo())
static DeconvolutionMethod get_deconvolution_method (const ITensorInfo *input, const ITensorInfo *weights, const ITensorInfo *bias, ITensorInfo *output, const PadStrideInfo &deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo &weights_info)
Detailed Description
Basic function to compute the deconvolution layer. This function calls the following OpenCL kernels/functions:
CLGEMMDeconvolutionLayer
CLDirectTransposeConvLayer
Definition at line 58 of file CLTransposeConvLayer.h.
Constructor & Destructor Documentation
CLTransposeConvLayer()
CLTransposeConvLayer::CLTransposeConvLayer (std::shared_ptr< IMemoryManager > memory_manager = nullptr)
Default constructor
Definition at line 55 of file CLTransposeConvLayer.cpp.
  : _memory_manager(std::move(memory_manager)), _function()
{
}
Member Function Documentation
configure() [1/2]
void CLTransposeConvLayer::configure (const CLCompileContext & compile_context, ICLTensor * input, ICLTensor * weights, const ICLTensor * bias, ICLTensor * output, const PadStrideInfo & deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo & weights_info = WeightsInfo())
Set the input, weights, biases and output tensors.
Parameters
[in] compile_context The compile context to be used.
[in,out] input Input tensor. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights with dimensions [width, height, IFM, OFM]. Data type supported: Same as input.
[in] bias (Optional) The biases have one dimension. Data type supported: Same as input.
[out] output Output tensor. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] invalid_right The number of zeros added to right edge of the output.
[in] invalid_bottom The number of zeros added to bottom edge of the output.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with CLWeightsReshapeKernel.
Definition at line 69 of file CLTransposeConvLayer.cpp.
{
  ARM_COMPUTE_ERROR_ON_NULLPTR(input, weights, output);
  switch (CLTransposeConvLayer::get_deconvolution_method(input->info(), weights->info(), nullptr,
                                                         output->info(), deconv_info, invalid_right,
                                                         invalid_bottom, weights_info))
  {
    case DeconvolutionMethod::DIRECT:
    {
      auto f = std::make_unique<CLDirectTransposeConvLayer>();
      f->configure(compile_context, input, weights, bias, output, deconv_info, invalid_right,
                   invalid_bottom, weights_info);
      _function = std::move(f);
      break;
    }
    case DeconvolutionMethod::GEMM:
    {
      auto f = std::make_unique<CLGEMMDeconvolutionLayer>(_memory_manager);
      f->configure(compile_context, input, weights, bias, output, deconv_info);
      _function = std::move(f);
      break;
    }
    default:
      ARM_COMPUTE_ERROR("Not supported.");
      break;
  }
}
References get_deconvolution_method().
configure() [2/2]
void CLTransposeConvLayer::configure (ICLTensor * input, ICLTensor * weights, const ICLTensor * bias, ICLTensor * output, const PadStrideInfo & deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo & weights_info = WeightsInfo())
Set the input, weights, biases and output tensors.
Parameters
[in,out] input Input tensor. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights with dimensions [width, height, IFM, OFM]. Data type supported: Same as input.
[in] bias (Optional) The biases have one dimension. Data type supported: Same as input.
[out] output Output tensor. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] invalid_right The number of zeros added to right edge of the output.
[in] invalid_bottom The number of zeros added to bottom edge of the output.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with CLWeightsReshapeKernel.
Definition at line 60 of file CLTransposeConvLayer.cpp.
{
  configure(CLKernelLibrary::get().get_compile_context(), input, weights, bias, output, deconv_info,
            invalid_right, invalid_bottom, weights_info);
}
References configure().
Referenced by configure().
get_deconvolution_method()
DeconvolutionMethod CLTransposeConvLayer::get_deconvolution_method (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * output, const PadStrideInfo & deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo & weights_info) static
Definition at line 132 of file CLTransposeConvLayer.cpp.
{
  ARM_COMPUTE_UNUSED(output, bias, weights_info);
  const DataLayout data_layout = input->data_layout();
  const size_t idx_w = get_data_layout_dimension_index(data_layout, DataLayoutDimension::WIDTH);
  const size_t idx_h = get_data_layout_dimension_index(data_layout, DataLayoutDimension::HEIGHT);
  if (weights->dimension(idx_w) != deconv_info.stride().first ||
      weights->dimension(idx_h) != deconv_info.stride().second || invalid_right != 0 ||
      invalid_bottom != 0)
  {
    return DeconvolutionMethod::DIRECT;
  }
  return DeconvolutionMethod::GEMM;
}
Referenced by configure(), and validate().
prepare()
void CLTransposeConvLayer::prepare () override
Definition at line 160 of file CLTransposeConvLayer.cpp.
{ _function->prepare(); }
Referenced by run().
run()
void CLTransposeConvLayer::run () override
Definition at line 154 of file CLTransposeConvLayer.cpp.
{
  prepare();
  _function->run();
}
References prepare().
validate()
Status CLTransposeConvLayer::validate (const ITensorInfo * input, const ITensorInfo * weights, const ITensorInfo * bias, ITensorInfo * output, const PadStrideInfo & deconv_info, unsigned int invalid_right, unsigned int invalid_bottom, const WeightsInfo & weights_info = WeightsInfo()) static
Static function to check if given info will lead to a valid configuration of CLTransposeConvLayer
Parameters
[in] input Input tensor info. 3 lower dimensions represent a single input, and an optional 4th dimension for batch of inputs. Data types supported: QASYMM8_SIGNED/QASYMM8/F16/F32.
[in] weights The 4d weights info with dimensions [width, height, IFM, OFM]. Data type supported: Same as input.
[in] bias (Optional) The biases have one dimension. Data type supported: Same as input.
[in] output Output tensor info. The output has the same number of dimensions as the input.
[in] deconv_info Contains padding and policies to be used in the deconvolution, this is described in PadStrideInfo.
[in] invalid_right The number of zeros added to right edge of the output.
[in] invalid_bottom The number of zeros added to bottom edge of the output.
[in] weights_info (Optional) Weights information needed for CLConvolutionLayer, specifies if the weights tensor has been reshaped with CLWeightsReshapeKernel.
Returns
a status
Definition at line 101 of file CLTransposeConvLayer.cpp.
{
  ARM_COMPUTE_RETURN_ERROR_ON_NULLPTR(input, weights, output);
  switch (CLTransposeConvLayer::get_deconvolution_method(
    input, weights, bias, output, deconv_info, invalid_right, invalid_bottom, weights_info))
  {
    case DeconvolutionMethod::DIRECT:
    {
      // Validate direct convolution layer
      ARM_COMPUTE_RETURN_ON_ERROR(CLDirectTransposeConvLayer::validate(
        input, weights, bias, output, deconv_info, invalid_right, invalid_bottom, weights_info));
      break;
    }
    case DeconvolutionMethod::GEMM:
    {
      // Validate gemm-based convolution layer
      ARM_COMPUTE_RETURN_ON_ERROR(
        CLGEMMDeconvolutionLayer::validate(input, weights, bias, output, deconv_info));
      break;
    }
    default:
      ARM_COMPUTE_ERROR("Not supported.");
      break;
  }
  return Status{};
}
References get_deconvolution_method(), and arm_compute::CLDirectTransposeConvLayer::validate().
The documentation for this class was generated from the following files:
compute/ARMComputeEx/arm_compute/runtime/CL/functions/CLTransposeConvLayer.h
compute/ARMComputeEx/src/runtime/CL/functions/CLTransposeConvLayer.cpp