ONE - On-device Neural Engine: caffeimport::ConcatBuilder Class Reference
caffeimport::ConcatBuilder Class Reference final
#include <Concatenation.h>
Public Member Functions
void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const override
Public Member Functions inherited from caffeimport::GraphBuilder
virtual void build (const ::caffe::LayerParameter &layer, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
Definition at line 27 of file Concatenation.h.
Member Function Documentation
build()
void caffeimport::ConcatBuilder::build (const ::caffe::LayerParameter & layer, GraphBuilderContext * context) const override virtual
Implements caffeimport::GraphBuilder.
Definition at line 32 of file Concatenation.cpp.
{
  coco::Module *module = context->module();
  coco::Block *blk = context->block();
  std::map<std::string, tensor::Shape> &shape_ctx = context->shape_ctx();
  std::map<std::string, coco::Bag *> &bag_ctx = context->bag_ctx();
  assert(layer.bottom().size() > 0);
  assert(layer.top().size() == 1);
  // Assume default concat axis
  // - Please refer to http://caffe.berkeleyvision.org/tutorial/layers/concat.html for details
  // TODO Get concat axis from concat param
  assert(!layer.has_concat_param());
  const uint32_t concat_axis = 1;
  // Construct a vector of input objects
  std::vector<coco::FeatureObject *> input_objects;
  for (const auto &input_name : layer.bottom())
  {
    const auto input_shape = as_feature_shape(shape_ctx.at(input_name));
    auto input_bag = bag_ctx.at(input_name);
    auto input_feature = module->entity()->object()->create<coco::FeatureObject>();
    input_feature->bag(input_bag);
    input_feature->layout(coco::FeatureLayouts::BCHW::create(input_shape));
    input_objects.emplace_back(input_feature);
  }
  coco::FeatureObject *last_feature = input_objects.at(0);
  assert(last_feature != nullptr);
  assert(last_feature->bag() != nullptr);
  // Update coco IR
  //
  // Given a sequence of input features %in[0] / %in[1] / ... / %in[N]
  // the below code constructs a sequence of eval instructions
  //  - Load is omitted for simplicity
  //
  // %out[0] = eval(ConcatF(%in[0], %in[1]))
  // %out[1] = eval(ConcatF(%out[0], %in[2]))
  // ...
  // %out[N - 1] = eval(ConcatF(%out[N - 2], %in[N]))
  //
  for (uint32_t n = 1; n < input_objects.size(); ++n)
  {
    auto const left_feature = last_feature;
    auto const left_shape = left_feature->layout()->shape();
    auto right_feature = input_objects.at(n);
    auto right_shape = right_feature->layout()->shape();
    // Batch is not supported, yet
    assert(left_feature->layout()->batch() == 1);
    assert(right_feature->layout()->batch() == 1);
    // Height and Width SHOULD BE IDENTICAL for depth concat
    assert(left_shape.height() == right_shape.height());
    assert(left_shape.width() == right_shape.width());
    const uint32_t C = left_shape.depth() + right_shape.depth();
    const uint32_t H = left_shape.height();
    const uint32_t W = left_shape.width();
    const nncc::core::ADT::feature::Shape out_shape{C, H, W};
    auto out_bag = module->entity()->bag()->create(num_elements(out_shape));
    auto out_feature = module->entity()->object()->create<coco::FeatureObject>();
    out_feature->bag(out_bag);
    out_feature->layout(coco::FeatureLayouts::BCHW::create(out_shape));
    auto left_load = op_builder(module).load(left_feature).pop();
    auto right_load = op_builder(module).load(right_feature).pop();
    auto concat_f = module->entity()->op()->create<coco::ConcatF>();
    concat_f->axis(coco::ConcatF::Axis::Depth);
    concat_f->left(left_load);
    concat_f->right(right_load);
    auto eval = instr_builder(module).eval(out_feature, concat_f);
    // Append the constructed Shuffle instruction
    blk->instr()->append(eval);
    // Update 'last_feature'
    last_feature = out_feature;
  }
  assert(last_feature != nullptr);
  assert(last_feature->bag() != nullptr);
  // Update bag and shape context
  auto const out_name = layer.top(0);
  auto const out_shape = as_tensor_shape(last_feature->layout()->shape());
  auto const out_bag = last_feature->bag();
  bag_ctx[out_name] = out_bag;
  shape_ctx[out_name] = out_shape;
}
References coco::DLinkedList< Child, Parent >::Head::append(), morph::caffe::as_feature_shape(), caffeimport::as_tensor_shape(), coco::ConcatF::axis(), coco::Object::bag(), coco::EntityManager::bag(), caffeimport::GraphBuilderContext::bag_ctx(), caffeimport::GraphBuilderContext::block(), coco::FeatureLayouts::BCHW::create(), coco::BagManager::create(), coco::ObjectManager::create(), coco::OpManager::create(), coco::ConcatF::Depth, coco::Module::entity(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), coco::FeatureObject::layout(), OpBuilder::load(), caffeimport::GraphBuilderContext::module(), coco::EntityManager::object(), coco::EntityManager::op(), op_builder(), OpBuilder::pop(), coco::FeatureLayout::shape(), and caffeimport::GraphBuilderContext::shape_ctx().
The documentation for this class was generated from the following files:
compiler/enco/frontend/caffe/src/Layer/Concatenation.h
compiler/enco/frontend/caffe/src/Layer/Concatenation.cpp