ONE - On-device Neural Engine: onert::exec::IFunction Class Reference
onert::exec::IFunction Class Reference abstract
#include <IFunction.h>
Public Member Functions
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 25 of file IFunction.h.
Constructor & Destructor Documentation
~IFunction()
virtual onert::exec::IFunction::~IFunction () virtual default
Member Function Documentation
prepare()
virtual void onert::exec::IFunction::prepare () inline virtual
Reimplemented in onert::backend::acl_common::AclFunction, onert::backend::cpu::ops::ConvolutionLayer, onert::backend::cpu::ops::FullyConnectedLayer, onert::backend::gpu_cl::ClFunction, onert::backend::ruy::ops::ConvolutionLayer, onert::backend::ruy::ops::FullyConnectedLayer, onert::backend::trix::ops::BulkLayer, onert::backend::xnnpack::ops::Layer, onert::exec::FunctionSequence, and onert::exec::IPermuteFunction.
Definition at line 30 of file IFunction.h.
{}
Referenced by onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::genKernels(), onert::backend::cpu::BackendContext::genKernels(), onert::backend::gpu_cl::BackendContext::genKernels(), onert::backend::ruy::BackendContext::genKernels(), onert::backend::trix::BackendContext::genKernels(), onert::backend::xnnpack::BackendContext::genKernels(), and onert::backend::builtin::BackendContext::genKernels().
run()
virtual void onert::exec::IFunction::run () pure virtual
Implemented in onert::backend::cpu::ops::LogSoftMaxLayer, onert::api::CustomKernel, onert::backend::acl_common::AclFunction, onert::backend::cpu::ops::AddNLayer, onert::backend::cpu::ops::ArgMinMaxLayer, onert::backend::cpu::ops::BatchMatMulLayer, onert::backend::cpu::ops::BatchToSpaceNDLayer, onert::backend::cpu::ops::BinaryArithmeticLayer, onert::backend::cpu::ops::BroadcastToLayer, onert::backend::cpu::ops::CompareLayer, onert::backend::cpu::ops::ConcatLayer, onert::backend::cpu::ops::ConvolutionLayer, onert::backend::cpu::ops::DepthToSpaceLayer, onert::backend::cpu::ops::DepthwiseConvolutionLayer, onert::backend::cpu::ops::DetectionPostProcessLayer, onert::backend::cpu::ops::EinsumLayer, onert::backend::cpu::ops::ElementwiseActivationLayer, onert::backend::cpu::ops::ElementwiseBinaryLayer, onert::backend::cpu::ops::ElementwiseUnaryLayer, onert::backend::cpu::ops::ExpandDimsLayer, onert::backend::cpu::ops::FillLayer, onert::backend::cpu::ops::FullyConnectedLayer, onert::backend::cpu::ops::FusedBatchNormLayer, onert::backend::cpu::ops::GatherLayer, onert::backend::cpu::ops::L2NormLayer, onert::backend::cpu::ops::LSTMLayer, onert::backend::cpu::ops::MatrixBandPartLayer, onert::backend::cpu::ops::MeanLayer, onert::backend::cpu::ops::OneHotLayer, onert::backend::cpu::ops::PackLayer, onert::backend::cpu::ops::PadLayer, onert::backend::cpu::ops::PoolLayer, onert::backend::cpu::ops::PowLayer, onert::backend::cpu::ops::QuantizeLayer, onert::backend::cpu::ops::RangeLayer, onert::backend::cpu::ops::RankLayer, onert::backend::cpu::ops::ReduceLayer, onert::backend::cpu::ops::ReshapeLayer, onert::backend::cpu::ops::ResizeBilinearLayer, onert::backend::cpu::ops::ReverseLayer, onert::backend::cpu::ops::SelectLayer, onert::backend::cpu::ops::ShapeLayer, onert::backend::cpu::ops::SliceLayer, onert::backend::cpu::ops::SoftMaxLayer, onert::backend::cpu::ops::SpaceToBatchNDLayer, onert::backend::cpu::ops::SpaceToDepthLayer, onert::backend::cpu::ops::SplitLayer, onert::backend::cpu::ops::SplitVLayer, onert::backend::cpu::ops::SqDiffLayer, onert::backend::cpu::ops::StatelessRandomUniformLayer, onert::backend::cpu::ops::StridedSliceLayer, onert::backend::cpu::ops::TileLayer, onert::backend::cpu::ops::TransposeLayer, onert::backend::cpu::ops::UnpackLayer, onert::backend::gpu_cl::ClFunction, onert::backend::ruy::ops::ConvolutionLayer, onert::backend::ruy::ops::FullyConnectedLayer, onert::backend::trix::ops::BulkLayer, onert::backend::xnnpack::ops::ConvolutionLayer, onert::backend::xnnpack::ops::DepthwiseConvolutionLayer, onert::backend::xnnpack::ops::FullyConnectedLayer, onert::exec::FunctionSequence, onert::exec::NopFunction, onert::backend::builtin::kernel::IfLayer, onert::backend::builtin::kernel::PermuteLayer, onert::backend::builtin::kernel::WhileLayer, onert::exec::IPermuteFunction, and onert::exec::HookFunction.
Referenced by onert::exec::HookFunction::run().
The documentation for this class was generated from the following file:
runtime/onert/core/include/exec/IFunction.h