ONE - On-device Neural Engine: luci::VariadicArityNode< Base > Class Template Reference
luci::VariadicArityNode< Base > Class Template Reference
Nodes with the variadic inputs.
#include <VariadicArityNode.h>
Public Member Functions
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Protected Member Functions
loco::Use * at (uint32_t n) const
Detailed Description
template<typename Base>
class luci::VariadicArityNode< Base >
Nodes with the variadic inputs.
Definition at line 33 of file VariadicArityNode.h.
Constructor & Destructor Documentation
VariadicArityNode()
template<typename Base > luci::VariadicArityNode< Base >::VariadicArityNode (uint32_t arity) inline
Definition at line 36 of file VariadicArityNode.h.
  {
    for (uint32_t n = 0; n < arity; ++n)
    {
      _args.push_back(std::make_unique<loco::Use>(this));
    }
  };
References luci::VariadicArityNode< Base >::arity().
~VariadicArityNode()
template<typename Base > virtual luci::VariadicArityNode< Base >::~VariadicArityNode () virtual default
Member Function Documentation
arg()
template<typename Base > loco::Node * luci::VariadicArityNode< Base >::arg (uint32_t n) const inline final
Definition at line 49 of file VariadicArityNode.h.
{ return _args.at(n)->node(); }
arity()
template<typename Base > uint32_t luci::VariadicArityNode< Base >::arity (void) const inline final
Definition at line 47 of file VariadicArityNode.h.
{ return _args.size(); }
Referenced by luci::VariadicArityNode< Base >::VariadicArityNode(), and luci::CloneNodeLet< CN::ABC >::visit().
at()
template<typename Base > loco::Use * luci::VariadicArityNode< Base >::at (uint32_t n) const inline protected
Definition at line 61 of file VariadicArityNode.h.
{ return _args.at(n).get(); }
drop()
template<typename Base > void luci::VariadicArityNode< Base >::drop (void) inline final
Definition at line 51 of file VariadicArityNode.h.
  {
    for (uint32_t n = 0; n < _args.size(); ++n)
    {
      _args.at(n)->node(nullptr);
    }
  }
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/VariadicArityNode.h