ONE - On-device Neural Engine: tflimport::ReLUGraphBuilder Class Reference
tflimport::ReLUGraphBuilder Class Reference
GraphBuilder for ReLU operator.
#include <ReLU.h>
Public Member Functions
void build (const tflite::Operator *op, GraphBuilderContext *) const override
Public Member Functions inherited from tflimport::GraphBuilder
virtual bool validate (const tflite::Operator *) const
virtual void build (const tflite::Operator *op, GraphBuilderContext *context) const =0
virtual ~GraphBuilder ()
Detailed Description
GraphBuilder for ReLU operator.
Definition at line 30 of file ReLU.h.
Member Function Documentation
build()
void tflimport::ReLUGraphBuilder::build (const tflite::Operator * op, GraphBuilderContext * context) const override virtual
Implements tflimport::GraphBuilder.
Definition at line 37 of file ReLU.cpp.
{
  assert(context != nullptr); // check if init(..) is called
  coco::Module *m = context->m();
  coco::Block *blk = context->block();
  TensorContext &tensor_context = context->tensor();
  TensorBags &bags = context->bags();
  IndexVector opinputs = as_index_vector(op->inputs());
  IndexVector opoutputs = as_index_vector(op->outputs());
  // these are fixed in tflite
  // input index 0 : input feature
  // output index 0 : output feature
  assert(opinputs.size() == 1);
  assert(opoutputs.size() == 1);
  auto ifm_idx = opinputs.at(0);
  auto ofm_idx = opoutputs.at(0);
  const tensor::Shape &ifm_shape = tensor_context.shape(ifm_idx);
  const tensor::Shape &ofm_shape = tensor_context.shape(ofm_idx);
  // Create an object for an input feature map
  coco::FeatureObject *ifm_obj = m->entity()->object()->create<coco::FeatureObject>();
  coco::Bag *ifm_bag = bags.bag(ifm_idx);
  ifm_obj->bag(ifm_bag);
  ifm_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(ifm_shape)));
  // Create an object for an output feature map
  coco::FeatureObject *ofm_obj = m->entity()->object()->create<coco::FeatureObject>();
  coco::Bag *ofm_bag = bags.bag(ofm_idx);
  ofm_obj->bag(ofm_bag);
  ofm_obj->layout(coco::FeatureLayouts::BHWC::create(as_feature_shape(ofm_shape)));
  // Create a Load op
  auto coco_load = op_builder(m).load(ifm_obj).pop();
  // Create a ReLU
  auto coco_relu = m->entity()->op()->create<coco::ReLU>();
  // Link ops
  coco_relu->arg(coco_load);
  // Create an Eval instruction
  auto eval_ins = instr_builder(m).eval(ofm_obj, coco_relu);
  // Append the instruction to the block
  blk->instr()->append(eval_ins);
}
References coco::DLinkedList< Child, Parent >::Head::append(), coco::UnaryOp::arg(), morph::tflite::as_feature_shape(), tflimport::as_index_vector(), tflimport::TensorBags::bag(), coco::Object::bag(), tflimport::GraphBuilderContext::bags(), tflimport::GraphBuilderContext::block(), coco::FeatureLayouts::BHWC::create(), InstrBuilder::eval(), coco::Block::instr(), instr_builder(), coco::FeatureObject::layout(), OpBuilder::load(), tflimport::GraphBuilderContext::m(), m, op_builder(), OpBuilder::pop(), tflimport::TensorContext::shape(), and tflimport::GraphBuilderContext::tensor().
The documentation for this class was generated from the following files:
compiler/enco/frontend/tflite/src/Op/ReLU.h
compiler/enco/frontend/tflite/src/Op/ReLU.cpp