ONE - On-device Neural Engine: luci::LoggerConfig Class Reference
luci::LoggerConfig Class Reference final
Logger Configuration.
#include <Log.h>
Public Member Functions
LoggerConfig ()
void configure (const hermes::Source *, hermes::Source::Setting &) const final
void configure (const Logger *, hermes::Source::Setting &) const
Public Member Functions inherited from hermes::Config
virtual ~Config ()=default
virtual void configure (const Source *, SourceSetting &) const =0
Detailed Description
Logger Configuration.
Users are able to turn logging on/off via LUCI_LOG environment variable.
Definition at line 40 of file Log.h.
Constructor & Destructor Documentation
LoggerConfig()
luci::LoggerConfig::LoggerConfig ()
Definition at line 60 of file Log.cpp.
{
  auto settings = luci::UserSettings::settings();
  _show_warn = !settings->get(luci::UserSettings::Key::MuteWarnings);
  // Turn on verbose logging if LUCI_LOG is set to some level
  // VERBOSE(l, 1) will be visible with LUCI_LOG=2 and VERBOSE(l, 2) with LUCI_LOG=3 and so on
  _show_verbose = safecast<int>(std::getenv("LUCI_LOG"), 0);
}
References luci::UserSettings::MuteWarnings, and luci::UserSettings::settings().
Member Function Documentation
configure() [1/2]
void luci::LoggerConfig::configure (const hermes::Source * source, hermes::Source::Setting & setting) const final virtual
Implements hermes::Config.
Definition at line 71 of file Log.cpp.
{
  // Let's ignore hermes::Sources if that is not a moco logger
  if (auto logger = dynamic_cast<const Logger *>(source))
  {
    configure(logger, setting);
  }
}
References configure().
Referenced by configure().
configure() [2/2]
void luci::LoggerConfig::configure (const Logger * , hermes::Source::Setting & setting) const
Definition at line 80 of file Log.cpp.
{
  // TODO remove deprecated codes
#if 0
  setting.filter(hermes::SeverityCategory::FATAL).reject_all();
  setting.filter(hermes::SeverityCategory::ERROR).reject_all();
  setting.filter(hermes::SeverityCategory::WARN).reject_all();
  setting.filter(hermes::SeverityCategory::INFO).reject_all();
  setting.filter(hermes::SeverityCategory::VERBOSE).reject_all();
  // TODO enable FATAL and ERROR
  if (_show_warn)
  {
    setting.filter(hermes::SeverityCategory::WARN).accept_all();
  }
  if (_show_info)
  {
    setting.filter(hermes::SeverityCategory::INFO).accept_all();
  }
  if (_show_verbose)
  {
    setting.filter(hermes::SeverityCategory::VERBOSE).accept_upto(_show_verbose);
  }
#endif
  setting.reject_all();
  setting.filter(hermes::SeverityCategory::FATAL).accept_upto(_show_verbose);
  setting.filter(hermes::SeverityCategory::ERROR).accept_upto(_show_verbose);
  if (_show_warn)
  {
    setting.filter(hermes::SeverityCategory::WARN).accept_upto(_show_verbose);
  }
  setting.filter(hermes::SeverityCategory::INFO).accept_upto(_show_verbose);
  setting.filter(hermes::SeverityCategory::VERBOSE).accept_upto(_show_verbose);
}
References hermes::Filter::accept_all(), hermes::Filter::accept_upto(), hermes::ERROR, hermes::FATAL, hermes::SourceSetting::filter(), hermes::INFO, hermes::Filter::reject_all(), hermes::SourceSetting::reject_all(), hermes::VERBOSE, and hermes::WARN.
The documentation for this class was generated from the following files:
compiler/luci/log/include/luci/Log.h
compiler/luci/log/src/Log.cpp