ONE - On-device Neural Engine: onert::backend::ruy::ops::FullyConnectedLayer Class Reference
onert::backend::ruy::ops::FullyConnectedLayer Class Reference
#include <FullyConnectedLayer.h>
Public Member Functions
FullyConnectedLayer ()
~FullyConnectedLayer ()
void fullyConnectedFloat32 ()
void configure (const IPortableTensor *input, const IPortableTensor *weights, const IPortableTensor *bias, ir::Activation activation, ir::FullyConnectedWeightsFormat weights_format, IPortableTensor *output, const std::shared_ptr< ExternalContext > &external_context)
void run () override
void prepare () override
Public Member Functions inherited from onert::exec::IFunction
virtual ~IFunction ()=default
virtual void run ()=0
virtual void prepare ()
Detailed Description
Definition at line 35 of file FullyConnectedLayer.h.
Constructor & Destructor Documentation
FullyConnectedLayer()
onert::backend::ruy::ops::FullyConnectedLayer::FullyConnectedLayer ()
Definition at line 32 of file FullyConnectedLayer.cc.
  : _input(nullptr), _weights(nullptr), _bias(nullptr), _output(nullptr),
    _activation(ir::Activation::NONE), _external_context(nullptr)
{
  // DO NOTHING
}
~FullyConnectedLayer()
onert::backend::ruy::ops::FullyConnectedLayer::~FullyConnectedLayer () default
Member Function Documentation
configure()
void onert::backend::ruy::ops::FullyConnectedLayer::configure (const IPortableTensor * input, const IPortableTensor * weights, const IPortableTensor * bias, ir::Activation activation, ir::FullyConnectedWeightsFormat weights_format, IPortableTensor * output, const std::shared_ptr< ExternalContext > & external_context)
Definition at line 61 of file FullyConnectedLayer.cc.
{
  UNUSED_RELEASE(weights_format);
  _input = input;
  _weights = weights;
  _bias = bias;
  _activation = activation;
  _output = output;
  _external_context = external_context;
}
References UNUSED_RELEASE.
fullyConnectedFloat32()
void onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32 ()
Definition at line 41 of file FullyConnectedLayer.cc.
{
  float output_activation_min = 0, output_activation_max = 0;
  CalculateActivationRange(_activation, &output_activation_min, &output_activation_max);
  nnfw::ruy::FullyConnectedParams op_params;
  op_params.float_activation_min = output_activation_min;
  op_params.float_activation_max = output_activation_max;
  op_params.activation = convertActivationType(_activation);
  op_params.lhs_cacheable = _weights->is_constant();
  op_params.rhs_cacheable = _input->is_constant();
  nnfw::ruy::FullyConnected(
    op_params, getTensorShape(_input), reinterpret_cast<const float *>(_input->buffer()),
    getTensorShape(_weights), reinterpret_cast<const float *>(_weights->buffer()),
    getTensorShape(_bias), reinterpret_cast<const float *>(_bias ? _bias->buffer() : nullptr),
    getTensorShape(_output), reinterpret_cast<float *>(_output->buffer()),
    _external_context->ruy_context());
}
References nnfw::ruy::FullyConnectedParams::activation, onert::backend::ITensor::buffer(), onert::util::CalculateActivationRange(), onert::backend::ruy::ops::convertActivationType(), nnfw::ruy::FullyConnectedParams::float_activation_max, nnfw::ruy::FullyConnectedParams::float_activation_min, nnfw::ruy::FullyConnected(), onert::backend::ruy::ops::getTensorShape(), onert::backend::ITensor::is_constant(), nnfw::ruy::FullyConnectedParams::lhs_cacheable, and nnfw::ruy::FullyConnectedParams::rhs_cacheable.
Referenced by run().
prepare()
void onert::backend::ruy::ops::FullyConnectedLayer::prepare () override virtual
Reimplemented from onert::exec::IFunction.
Definition at line 88 of file FullyConnectedLayer.cc.
{
  if (_bias && _bias->is_constant())
  {
    const int bias_size = getTensorShape(_bias).FlatSize();
    if (nnfw::ruy::IsZeroVector(reinterpret_cast<float *>(_bias->buffer()), bias_size))
    {
      _bias = nullptr;
    }
  }
}
References onert::backend::ITensor::buffer(), nnfw::ruy::Shape::FlatSize(), onert::backend::ruy::ops::getTensorShape(), onert::backend::ITensor::is_constant(), and nnfw::ruy::IsZeroVector().
run()
void onert::backend::ruy::ops::FullyConnectedLayer::run () override virtual
Implements onert::exec::IFunction.
Definition at line 76 of file FullyConnectedLayer.cc.
{
  if (_input->data_type() == OperandType::FLOAT32)
  {
    fullyConnectedFloat32();
  }
  else
  {
    throw std::runtime_error{"FullyConnected: unsupported data type"};
  }
}
References onert::backend::ITensor::data_type(), and fullyConnectedFloat32().
The documentation for this class was generated from the following files:
runtime/onert/backend/ruy/ops/FullyConnectedLayer.h
runtime/onert/backend/ruy/ops/FullyConnectedLayer.cc