ONE - On-device Neural Engine: nnkit::support::onnx::Backend Class Reference
nnkit::support::onnx::Backend Class Reference final
#include <Backend.h>
Public Member Functions
Backend (const std::string &onnx_path)
void prepare (const std::function< void(nnkit::TensorContext &)> &f) override
void run (void) override
void teardown (const std::function< void(nnkit::TensorContext &)> &f) override
Public Member Functions inherited from nnkit::Backend
virtual ~Backend ()=default
virtual void prepare (const std::function< void(TensorContext &)> &f)=0
virtual void run (void)=0
virtual void teardown (const std::function< void(TensorContext &)> &f)=0
Detailed Description
Definition at line 31 of file Backend.h.
Constructor & Destructor Documentation
Backend()
nnkit::support::onnx::Backend::Backend (const std::string & onnx_path) inline
Definition at line 34 of file Backend.h.
                                      : _runner(onnx_path)
  {
    // DO NOTHING
  }
Member Function Documentation
prepare()
void Backend::prepare (const std::function< void(nnkit::TensorContext &)> & f) override
Definition at line 27 of file Backend.cpp.
{
  // Prepare input and output tensors
  _runner.prepareInputs();
  _runner.prepareOutputs();
  TensorContext ctx(_runner.inputs());
  f(ctx);
}
References nnkit::support::onnx::Runner::inputs(), nnkit::support::onnx::Runner::prepareInputs(), and nnkit::support::onnx::Runner::prepareOutputs().
run()
void Backend::run (void) override virtual
Implements nnkit::Backend.
Definition at line 37 of file Backend.cpp.
{ _runner.run(); }
References nnkit::support::onnx::Runner::run().
teardown()
void Backend::teardown (const std::function< void(nnkit::TensorContext &)> & f) override
Definition at line 39 of file Backend.cpp.
{
  TensorContext ctx(_runner.outputs());
  f(ctx);
}
References nnkit::support::onnx::Runner::outputs().
The documentation for this class was generated from the following files:
compiler/nnkit-onnxrt/support/include/nnkit/support/onnx/Backend.h
compiler/nnkit-onnxrt/support/src/Backend.cpp