ONE - On-device Neural Engine: moco::tf::BroadcastFunctor Class Reference
moco::tf::BroadcastFunctor Class Reference final
#include <BroadcastHelper.h>
Public Member Functions
BroadcastFunctor (const loco::TensorShape &shape)
loco::Node * build (loco::Node *in_node, const loco::TensorShape &in_shape) const
loco::Node * operator() (loco::Node *in_node, const loco::TensorShape &in_shape) const
loco::Node * build (loco::Node *node) const
loco::Node * operator() (loco::Node *node) const
Detailed Description
Definition at line 32 of file BroadcastHelper.h.
Constructor & Destructor Documentation
BroadcastFunctor()
moco::tf::BroadcastFunctor::BroadcastFunctor (const loco::TensorShape & shape) inline
Definition at line 35 of file BroadcastHelper.h.
                                                 : _shape{shape}
  {
    // DO NOTHING
  }
Member Function Documentation
build() [1/2]
loco::Node * moco::tf::BroadcastFunctor::build (loco::Node * in_node, const loco::TensorShape & in_shape) const
Definition at line 210 of file BroadcastHelper.cpp.
{
  // clang-format off
  return glue(node, shape)
       | expand_rank_to(_shape.rank())
       | expand_dims_as(_shape)
       | [] (const NodeWithTensorShape &in) { return in.node(); };
  // clang-format on
}
References loco::TensorShape::rank().
Referenced by build(), and operator()().
build() [2/2]
loco::Node * moco::tf::BroadcastFunctor::build (loco::Node * node) const
Definition at line 220 of file BroadcastHelper.cpp.
{
  return build(node, loco::shape_get(node).as<loco::TensorShape>());
}
References build(), and loco::shape_get().
operator()() [1/2]
loco::Node * moco::tf::BroadcastFunctor::operator() (loco::Node * in_node, const loco::TensorShape & in_shape) const inline
Definition at line 43 of file BroadcastHelper.h.
  {
    return build(in_node, in_shape);
  }
References build().
operator()() [2/2]
loco::Node * moco::tf::BroadcastFunctor::operator() (loco::Node * node) const inline
Definition at line 53 of file BroadcastHelper.h.
{ return build(node); }
References build().
The documentation for this class was generated from the following files:
compiler/moco-tf/src/BroadcastHelper.h
compiler/moco-tf/src/BroadcastHelper.cpp