ONE - On-device Neural Engine: tflinspect::DumpOperators Class Reference
tflinspect::DumpOperators Class Reference final
#include <Dump.h>
Public Member Functions
DumpOperators ()=default
void run (std::ostream &os, const tflite::Model *model)
Public Member Functions inherited from tflinspect::DumpInterface
virtual ~DumpInterface ()=default
virtual void run (std::ostream &os, const tflite::Model *model)=0
Detailed Description
Definition at line 36 of file Dump.h.
Constructor & Destructor Documentation
DumpOperators()
tflinspect::DumpOperators::DumpOperators () default
Member Function Documentation
run()
void tflinspect::DumpOperators::run (std::ostream & os, const tflite::Model * model) virtual
Implements tflinspect::DumpInterface.
Definition at line 27 of file Dump.cpp.
{
  tflinspect::Reader reader(model);
  const uint32_t subgraph_size = reader.num_subgraph();
  for (uint32_t g = 0; g < subgraph_size; g++)
  {
    reader.select_subgraph(g);
    auto ops = reader.operators();
    // dump operators
    for (uint32_t i = 0; i < ops->Length(); ++i)
    {
      const auto op = ops->Get(i);
      auto op_name = reader.opcode_name(op);
      os << op_name << std::endl;
    }
  }
}
References tflinspect::Reader::num_subgraph(), tflinspect::Reader::opcode_name(), tflinspect::Reader::operators(), and tflinspect::Reader::select_subgraph().
The documentation for this class was generated from the following files:
compiler/tfl-inspect/src/Dump.h
compiler/tfl-inspect/src/Dump.cpp