ONE - On-device Neural Engine: luci::CircleWhile Class Reference
luci::CircleWhile Class Reference final
WHILE in Circle.
#include <CircleWhile.h>
Public Member Functions
CircleWhile (uint32_t arity, uint32_t out)
uint32_t input_count (void) const
uint32_t output_count (void) const
Node * input (uint32_t index) const
void input (uint32_t index, Node *node)
int32_t cond_branch (void) const
void cond_branch (int32_t cond_branch)
int32_t body_branch (void) const
void body_branch (int32_t body_branch)
loco::Graph * cond_graph (void) const
void cond_graph (loco::Graph *cond_graph)
loco::Graph * body_graph (void) const
void body_graph (loco::Graph *body_graph)
Public Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >
VariadicArityNode (uint32_t arity)
virtual ~VariadicArityNode ()=default
uint32_t arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from luci::CircleNodeImpl< CircleOpcode::WHILE >
virtual ~CircleNodeImpl ()=default
uint32_t opnum (void) const final
CircleOpcode opcode (void) const final
Public Member Functions inherited from luci::CircleNode
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >
loco::Use * at (uint32_t n) const
Detailed Description
WHILE in Circle.
Definition at line 33 of file CircleWhile.h.
Constructor & Destructor Documentation
CircleWhile()
luci::CircleWhile::CircleWhile (uint32_t arity, uint32_t out) inline
Definition at line 36 of file CircleWhile.h.
    : VariadicArityNode<CircleNodeImpl<CircleOpcode::WHILE>>(arity), _output_count(out)
  {
    assert(arity > 0);
    assert(out > 0);
    // input and output must have the same size
    assert(arity == out);
  }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >::arity().
Member Function Documentation
body_branch() [1/2]
void luci::CircleWhile::body_branch (int32_t body_branch) inline
Definition at line 59 of file CircleWhile.h.
{ _body_branch = body_branch; }
References body_branch().
Referenced by body_branch().
body_branch() [2/2]
int32_t luci::CircleWhile::body_branch (void) const inline
Definition at line 58 of file CircleWhile.h.
{ return _body_branch; }
Referenced by luci::CircleWhileGraphBuilder::build(), and luci::BuiltinOptionsExtractor::visit().
body_graph() [1/2]
void luci::CircleWhile::body_graph (loco::Graph * body_graph) inline
Definition at line 66 of file CircleWhile.h.
{ _body_graph = body_graph; }
References body_graph().
Referenced by body_graph().
body_graph() [2/2]
loco::Graph * luci::CircleWhile::body_graph (void) const inline
Definition at line 65 of file CircleWhile.h.
{ return _body_graph; }
cond_branch() [1/2]
void luci::CircleWhile::cond_branch (int32_t cond_branch) inline
Definition at line 56 of file CircleWhile.h.
{ _cond_branch = cond_branch; }
References cond_branch().
Referenced by cond_branch().
cond_branch() [2/2]
int32_t luci::CircleWhile::cond_branch (void) const inline
Definition at line 55 of file CircleWhile.h.
{ return _cond_branch; }
Referenced by luci::CircleWhileGraphBuilder::build(), and luci::BuiltinOptionsExtractor::visit().
cond_graph() [1/2]
void luci::CircleWhile::cond_graph (loco::Graph * cond_graph) inline
Definition at line 63 of file CircleWhile.h.
{ _cond_graph = cond_graph; }
References cond_graph().
Referenced by cond_graph().
cond_graph() [2/2]
loco::Graph * luci::CircleWhile::cond_graph (void) const inline
Definition at line 62 of file CircleWhile.h.
{ return _cond_graph; }
input() [1/2]
Node * luci::CircleWhile::input (uint32_t index) const inline
Definition at line 51 of file CircleWhile.h.
{ return at(index)->node(); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >::at(), and loco::Use::node().
Referenced by luci::CircleWhileGraphBuilder::build().
input() [2/2]
void luci::CircleWhile::input (uint32_t index, Node * node) inline
Definition at line 52 of file CircleWhile.h.
{ at(index)->node(node); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >::at(), and loco::Use::node().
input_count()
uint32_t luci::CircleWhile::input_count (void) const inline
Definition at line 47 of file CircleWhile.h.
{ return arity(); }
References luci::VariadicArityNode< CircleNodeImpl< CircleOpcode::WHILE > >::arity().
Referenced by luci::CloneNodeLet< CN::WXYZ >::visit().
output_count()
uint32_t luci::CircleWhile::output_count (void) const inline
Definition at line 48 of file CircleWhile.h.
{ return _output_count; }
Referenced by luci::CloneNodeLet< CN::WXYZ >::visit().
The documentation for this class was generated from the following file:
compiler/luci/lang/include/luci/IR/Nodes/CircleWhile.h