ONE - On-device Neural Engine: loco::MultiDialectTypeInferenceRule Class Reference
loco::MultiDialectTypeInferenceRule Class Reference final
Type Inference Rule for multiple dialects.
#include <TypeInference.h>
Public Member Functions
bool recognize (const Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const Node *, DataType &) const final
MultiDialectTypeInferenceRule & bind (const Dialect *d, const TypeInferenceRule *rule)
Bind a specific rule to a Dialect.
Public Member Functions inherited from loco::TypeInferenceRule
virtual ~TypeInferenceRule ()=default
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, DataType &) const =0
Detailed Description
Type Inference Rule for multiple dialects.
Definition at line 71 of file TypeInference.h.
Member Function Documentation
bind()
MultiDialectTypeInferenceRule & loco::MultiDialectTypeInferenceRule::bind (const Dialect * d, const TypeInferenceRule * rule)
Bind a specific rule to a Dialect.
Definition at line 216 of file TypeInference.cpp.
{
  assert(_rules.find(d) == _rules.end());
  assert(rule->recognize(d));
  _rules[d] = rule;
  return (*this);
}
References loco::TypeInferenceRule::recognize().
Referenced by exo::TypeInferencePass::run(), and moco::tf::TypeInferencePass::run().
infer()
bool loco::MultiDialectTypeInferenceRule::infer (const Node * , DataType &) const final virtual
Framework guarantees the followings:
Framework tries to infer the data type of each node only after the data type of all of its valid (= non-nullptr) argument nodes is inferred.
The result of preceding "infer" is accessible through below dtype_get method.
This holds only when preceding "infer" returns true.
Implements loco::TypeInferenceRule.
Definition at line 202 of file TypeInference.cpp.
{
  const auto found = _rules.find(node->dialect());
  if (found == _rules.cend())
    return false;
  auto rule = found->second;
  if (rule->infer(node, dtype))
    return true;
  return false;
}
References loco::Node::dialect().
recognize()
bool loco::MultiDialectTypeInferenceRule::recognize (const Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::TypeInferenceRule.
Definition at line 189 of file TypeInference.cpp.
{
  const auto found = _rules.find(d);
  if (found == _rules.cend())
    return false;
  auto rule = found->second;
  auto result = rule->recognize(d);
  return result;
}
The documentation for this class was generated from the following files:
compiler/loco/include/loco/Service/TypeInference.h
compiler/loco/src/Service/TypeInference.cpp