ONE - On-device Neural Engine: coco::KernelLayouts::NHWC Class Reference
coco::KernelLayouts::NHWC Class Reference final
NHWC Kernel Layout.
#include <KernelLayouts.h>
Public Member Functions
const KernelLayout::ID * id (void) const override
Return the identifier of each layout.
const nncc::core::ADT::kernel::Shape & shape (void) const override
ElemID at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const override
Public Member Functions inherited from coco::KernelLayout
virtual ~KernelLayout ()=default
virtual const ID * id (void) const =0
Return the identifier of each layout.
virtual const nncc::core::ADT::kernel::Shape & shape (void) const =0
virtual ElemID at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const =0
Static Public Member Functions
static const KernelLayout::ID * uid (void)
static std::unique_ptr< NHWC > create (const nncc::core::ADT::kernel::Shape &shape)
Detailed Description
NHWC Kernel Layout.
Definition at line 61 of file KernelLayouts.h.
Member Function Documentation
at()
ElemID coco::KernelLayouts::NHWC::at (uint32_t n, uint32_t ch, uint32_t row, uint32_t col) const override virtual
Implements coco::KernelLayout.
Definition at line 78 of file KernelLayouts.cpp.
{
  static NHWCLayout l;
  return ElemID{l.offset(_shape, n, ch, row, col)};
}
create()
std::unique_ptr< NHWC > coco::KernelLayouts::NHWC::create (const nncc::core::ADT::kernel::Shape & shape) static
Definition at line 84 of file KernelLayouts.cpp.
{
  // NOTE It is impossible to use make_unique here as the constructor is private
  return std::unique_ptr<NHWC>{new NHWC{shape}};
}
References shape().
Referenced by tflimport::Conv2DGraphBuilder::build(), and tflimport::DepthwiseConv2DGraphBuilder::build().
id()
const KernelLayout::ID * coco::KernelLayouts::NHWC::id (void) const inline override virtual
Return the identifier of each layout.
REQUIRED
Given l1 and l2 of KernelLayout * type, typeid(*l1) == typeif(*l2) SHOULD hold if l1->id() == l2->id() holds.
Implements coco::KernelLayout.
Definition at line 71 of file KernelLayouts.h.
{ return uid(); }
References uid().
Referenced by uid().
shape()
const nncc::core::ADT::kernel::Shape & coco::KernelLayouts::NHWC::shape (void) const inline override virtual
Implements coco::KernelLayout.
Definition at line 73 of file KernelLayouts.h.
{ return _shape; }
Referenced by create().
uid()
const KernelLayout::ID * coco::KernelLayouts::NHWC::uid (void) static
Definition at line 69 of file KernelLayouts.cpp.
{
  struct LayoutID final : public KernelLayout::ID
  {
  };
  static LayoutID id;
  return &id;
}
References id().
Referenced by id().
The documentation for this class was generated from the following files:
compiler/coco/core/include/coco/IR/KernelLayouts.h
compiler/coco/core/src/IR/KernelLayouts.cpp