ONE - On-device Neural Engine: loco::Permutation< Domain::Matrix > Class Reference
loco::Permutation< Domain::Matrix > Class Reference
Mapping between Matrix/Tensor Axis.
#include <PermutingCodec.h>
Public Member Functions
Permutation ()=default
bool mapped (const MatrixAxis &axis_f) const
Return whether a given matrix axis has a corresponding tensor axis.
TensorAxis axis (const MatrixAxis &axis_f) const
Get the tensor axis corresponding to a given matrix axis.
TensorAxis & axis (const MatrixAxis &axis_f)
Set the tensor axis corresponding to a given matrix axis.
TensorAxis operator[] (const MatrixAxis &axis_f) const
TensorAxis & operator[] (const MatrixAxis &axis_f)
Detailed Description
Mapping between Matrix/Tensor Axis.
Definition at line 327 of file PermutingCodec.h.
Constructor & Destructor Documentation
Permutation()
loco::Permutation< Domain::Matrix >::Permutation () default
Member Function Documentation
axis() [1/2]
uint32_t & loco::Permutation< Domain::Matrix >::axis (const MatrixAxis & axis_f)
Set the tensor axis corresponding to a given matrix axis.
Definition at line 561 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid matrix axis");
  return _map[axis_f];
}
References loco::valid().
axis() [2/2]
uint32_t loco::Permutation< Domain::Matrix >::axis (const MatrixAxis & axis_f) const
Get the tensor axis corresponding to a given matrix axis.
This method works correctly only for mapped matrix axes.
Definition at line 554 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid matrix axis");
  assert(mapped(axis_f) && "unmapped matrix axis");
  return _map.at(axis_f);
}
References loco::valid().
mapped()
bool loco::Permutation< Domain::Matrix >::mapped (const MatrixAxis & axis_f) const
Return whether a given matrix axis has a corresponding tensor axis.
This method does not validate the corresponding value.
Definition at line 548 of file PermutingCodec.cpp.
{
  assert(valid(axis_f) && "invalid matrix axis");
  return _map.find(axis_f) != _map.end();
}
References loco::valid().
operator[]() [1/2]
TensorAxis & loco::Permutation< Domain::Matrix >::operator[] (const MatrixAxis & axis_f) inline
Definition at line 353 of file PermutingCodec.h.
{ return axis(axis_f); }
operator[]() [2/2]
TensorAxis loco::Permutation< Domain::Matrix >::operator[] (const MatrixAxis & axis_f) const inline
Definition at line 352 of file PermutingCodec.h.
{ return axis(axis_f); }
The documentation for this class was generated from the following files:
compiler/loco/include/loco/IR/PermutingCodec.h
compiler/loco/src/IR/PermutingCodec.cpp