ONE - On-device Neural Engine: moco::TFShape Class Reference
moco::TFShape Class Reference final
#include <TFShape.h>
Public Member Functions
TFShape ()=default
Node * input (void) const
void input (Node *node)
Public Member Functions inherited from moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >
FixedArityNode ()
virtual ~FixedArityNode ()=default
unsigned arity (void) const final
loco::Node * arg (uint32_t n) const final
void drop (void) final
Public Member Functions inherited from moco::TFNodeImpl< TFOpcode::Shape >
virtual ~TFNodeImpl ()=default
uint32_t opnum (void) const final
TFOpcode opcode (void) const final
Public Member Functions inherited from moco::TFNode
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Additional Inherited Members
Protected Member Functions inherited from moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >
loco::Use * at (unsigned n) const
Detailed Description
Note
TFShape corresponds to the following GraphDef
Mixed in dtype() is for 'out_type' attribute
Definition at line 47 of file TFShape.h.
Constructor & Destructor Documentation
TFShape()
moco::TFShape::TFShape () default
Member Function Documentation
input() [1/2]
void moco::TFShape::input (Node * node) inline
Definition at line 55 of file TFShape.h.
{ at(0)->node(node); }
References moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >::at(), and loco::Use::node().
input() [2/2]
Node * moco::TFShape::input (void) const inline
Definition at line 54 of file TFShape.h.
{ return at(0)->node(); }
References moco::FixedArityNode< 1, TFNodeImpl< TFOpcode::Shape > >::at(), and loco::Use::node().
The documentation for this class was generated from the following file:
compiler/moco/lang/include/moco/IR/Nodes/TFShape.h