ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Div.cpp File Reference
Div.cpp File Reference
#include "Div.h"
#include "Assert.h"
Functions
bool divPrepare (const Shape &in1, const Shape &in2, Shape *out)
Function Documentation
divPrepare()
bool divPrepare (const Shape & in1, const Shape & in2, Shape * out)
Definition at line 21 of file Div.cpp.
{
  ASSERT(getNumberOfDimensions(in1) <= 4 && getNumberOfDimensions(in2) <= 4);
  ASSERT(in1.type == in2.type);
  if (SameShape(in1, in2))
  {
    return SetShape(in1, out);
  }
  else
  {
    // Broadcast needed
    uint32_t numberOfDims1 = getNumberOfDimensions(in1);
    uint32_t numberOfDims2 = getNumberOfDimensions(in2);
    uint32_t maxDims = std::max(numberOfDims1, numberOfDims2);
    out->dimensions = std::vector<uint32_t>(maxDims);
    for (uint32_t i = 1; i <= maxDims; i++)
    {
      uint32_t dim1 = 1;
      if (i <= numberOfDims1)
      {
        dim1 = getSizeOfDimension(in1, numberOfDims1 - i);
      }
      uint32_t dim2 = 1;
      if (i <= numberOfDims2)
      {
        dim2 = getSizeOfDimension(in2, numberOfDims2 - i);
      }
      if (dim1 != dim2 && dim1 != 1 && dim2 != 1)
      {
        LOG(ERROR) << "Dimensions mismatch for BroadcastDiv";
        return false;
      }
      out->dimensions[maxDims - i] = std::max(dim1, dim2);
    }
  }
  return true;
}
References ASSERT, Shape::dimensions, getNumberOfDimensions(), getSizeOfDimension(), LOG, SameShape(), SetShape(), and Shape::type.