ONE - On-device Neural Engine: compiler/tf2tflite/src/Driver.cpp File Reference
Driver.cpp File Reference
#include "CustomopConfLoader.h"
#include <moco/LoggingContext.h>
#include <moco/tf/Frontend.h>
#include <exo/LoggingContext.h>
#include <exo/TFLExporter.h>
#include <nnkit/support/tftestinfo/TensorInfoParser.h>
#include <locop/FormattedGraph.h>
#include <hermes/ConsoleReporter.h>
#include <hermes/EnvConfig.h>
#include <cassert>
#include <memory>
#include <iostream>
#include <stdexcept>
#include <string>
Macros
#define LOGGER(name) ::Logger name { ::LoggingContext::get() }
#define INFO(name) HERMES_INFO(name)
Functions
int main (int argc, char **argv)
Macro Definition Documentation
INFO
#define INFO (name) HERMES_INFO(name)
Definition at line 90 of file Driver.cpp.
LOGGER
#define LOGGER (name) ::Logger name { ::LoggingContext::get() }
Definition at line 87 of file Driver.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 92 of file Driver.cpp.
{
  using EnvConfig = hermes::EnvConfig<hermes::EnvFormat::BooleanNumber>;
  // This line allows users to control all the moco-tf loggers via TF2TFLITE_Log_Frontend
  moco::LoggingContext::get()->config(std::make_unique<EnvConfig>("TF2TFLITE_Log_Frontend"));
  // This line allows users to control all the exo-tflite loggers via TF2TFLITE_Log_Backend
  exo::LoggingContext::get()->config(std::make_unique<EnvConfig>("TF2TFLITE_Log_Backend"));
  LOGGER(l);
  // TODO We need better args parsing in future
  if (!(argc == 4 or argc == 6))
  {
    print_help();
    return 255;
  }
  std::string info_path{argv[1]};
  std::string tf_path{argv[2]}; // .pb file
  std::string tflite_path{argv[3]};
  std::cout << "Read '" << info_path << "'" << std::endl;
  moco::ModelSignature sig;
  {
    for (const auto &info : nnkit::support::tftestinfo::parse(info_path.c_str()))
    {
      switch (info->kind())
      {
        case nnkit::support::tftestinfo::ParsedTensor::Kind::Input:
          sig.add_input(moco::TensorName{info->name()});
          sig.shape(info->name(), info->shape());
          break;
        case nnkit::support::tftestinfo::ParsedTensor::Kind::Output:
          sig.add_output(moco::TensorName{info->name()});
          sig.shape(info->name(), info->shape());
          break;
        default:
          throw std::runtime_error{"Unknown kind"};
      }
    }
  }
  if (argc == 6) // optional parameter: path of customop.conf
  {
    if (std::string{argv[4]} == "--customop")
    {
      tf2tflite::load_customop_conf(argv[5], sig);
    }
    else
    {
      print_help();
      return 255;
    }
  }
  std::cout << "Read '" << info_path << "' - Done" << std::endl;
  std::cout << "Import from '" << tf_path << "'" << std::endl;
  auto g = import(sig, tf_path);
  std::cout << "Import from '" << tf_path << "' - Done" << std::endl;
  INFO(l) << "Import Graph" << std::endl;
  INFO(l) << locop::fmt<locop::Formatter::LinearV1>(g) << std::endl;
  std::cout << "Export into '" << tflite_path << "'" << std::endl;
  exo::TFLExporter(g.get()).dumpToFile(tflite_path.c_str());
  std::cout << "Export into '" << tflite_path << "' - Done" << std::endl;
  return 0;
}
References moco::ModelSignature::add_input(), moco::ModelSignature::add_output(), hermes::Context::config(), exo::TFLExporter::dumpToFile(), exo::LoggingContext::get(), moco::LoggingContext::get(), INFO, info, nnkit::support::tftestinfo::ParsedTensor::Input, tf2tflite::load_customop_conf(), LOGGER, nnkit::support::tftestinfo::ParsedTensor::Output, nnkit::support::tftestinfo::parse(), and moco::ModelSignature::shape().