ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Array.h File Reference
Array.h File Reference
#include "Shape.h"
#include "Dims.h"
#include "Macro.h"
Functions
template<typename ArrayType1 , typename ArrayType2 >
int MatchingArraySize (const ArrayType1 &array1, int index1, const ArrayType2 &array2, int index2)
template<typename ArrayType1 , typename ArrayType2 , typename... Args>
int MatchingArraySize (const ArrayType1 &array1, int index1, const ArrayType2 &array2, int index2, Args... args)
Function Documentation
MatchingArraySize() [1/2]
template<typename ArrayType1 , typename ArrayType2 > int MatchingArraySize (const ArrayType1 & array1, int index1, const ArrayType2 & array2, int index2)
Definition at line 31 of file Array.h.
{
  DCHECK_EQ(ArraySize(array1, index1), ArraySize(array2, index2));
  return ArraySize(array1, index1);
}
References ArraySize(), and DCHECK_EQ.
Referenced by Add(), AveragePool(), Concatenation(), optimized_ops::DepthwiseConv(), Div(), Im2col(), MatchingArraySize(), MaxPool(), Mul(), Softmax(), and Sub().
MatchingArraySize() [2/2]
template<typename ArrayType1 , typename ArrayType2 , typename... Args> int MatchingArraySize (const ArrayType1 & array1, int index1, const ArrayType2 & array2, int index2, Args... args)
Definition at line 39 of file Array.h.
{
  DCHECK_EQ(ArraySize(array1, index1), ArraySize(array2, index2));
  return MatchingArraySize(array1, index1, args...);
}
References ArraySize(), DCHECK_EQ, and MatchingArraySize().