ONE - On-device Neural Engine: compiler/circlechef/tools/reverse/Driver.cpp File Reference
Driver.cpp File Reference
#include <circlechef/RecipeChef.h>
#include <arser/arser.h>
#include <foder/FileLoader.h>
#include <memory>
#include <iostream>
Functions
int entry (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Definition at line 25 of file Driver.cpp.
{
  arser::Arser arser;
  arser.add_argument("circle").help("Source circle file path to convert");
  arser.add_argument("recipe").help("Target recipe file path");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cout << err.what() << std::endl;
    std::cout << arser;
    return 255;
  }
  std::string circle_path = arser.get<std::string>("circle");
  // Load TF lite model from a circle file
  const foder::FileLoader fileLoader{circle_path};
  std::vector<char> modelData = fileLoader.load();
  const circle::Model *circlemodel = circle::GetModel(modelData.data());
  if (circlemodel == nullptr)
  {
    std::cerr << "ERROR: Failed to load circle '" << circle_path << "'" << std::endl;
    return 255;
  }
  // Generate ModelRecipe recipe
  std::unique_ptr<circlechef::ModelRecipe> recipe = circlechef::generate_recipe(circlemodel);
  if (recipe.get() == nullptr)
  {
    std::cerr << "ERROR: Failed to generate recipe" << std::endl;
    return 255;
  }
  std::string recipe_path = arser.get<std::string>("recipe");
  // Save to a file
  bool result = circlechef::write_recipe(recipe_path, recipe);
  if (!result)
  {
    std::cerr << "ERROR: Failed to write to recipe '" << recipe_path << "'" << std::endl;
    return 255;
  }
  return 0;
}
References circlechef::generate_recipe(), foder::FileLoader::load(), and circlechef::write_recipe().