ONE - On-device Neural Engine: compiler/ann-ref/src/Shape.cpp File Reference
Shape.cpp File Reference
#include "Shape.h"
#include <cstddef>
Functions
bool SameShape (const Shape &in1, const Shape &in2)
bool SetShape (const Shape &in, Shape *out)
uint32_t getNumberOfElements (const Shape &shape)
uint32_t getNumberOfDimensions (const Shape &shape)
uint32_t getSizeOfDimension (const Shape &shape, uint32_t dimensionIdx)
Function Documentation
getNumberOfDimensions()
uint32_t getNumberOfDimensions (const Shape & shape)
Definition at line 58 of file Shape.cpp.
{ return shape.dimensions.size(); }
References Shape::dimensions.
Referenced by addPrepare(), concatenationFloat32(), concatenationPrepare(), convPrepare(), depthwiseConvPrepare(), divPrepare(), fullyConnectedPrepare(), genericActivationPrepare(), genericPoolingPrepare(), mulPrepare(), padGeneric(), padPrepare(), softmaxFloat32(), and subPrepare().
getNumberOfElements()
uint32_t getNumberOfElements (const Shape & shape)
Definition at line 48 of file Shape.cpp.
{
  uint32_t count = 1;
  for (size_t i = 0; i < shape.dimensions.size(); i++)
  {
    count *= shape.dimensions[i];
  }
  return count;
}
References Shape::dimensions.
Referenced by fullyConnectedPrepare(), relu6Float32(), reluFloat32(), reshapePrepare(), and softmaxFloat32().
getSizeOfDimension()
uint32_t getSizeOfDimension (const Shape & shape, uint32_t dimensionIdx)
Definition at line 60 of file Shape.cpp.
{
  if (dimensionIdx >= shape.dimensions.size())
  {
    // TODO, log the error
    return 0;
  }
  return shape.dimensions[dimensionIdx];
}
References Shape::dimensions.
Referenced by addPrepare(), concatenationPrepare(), convertShapeToDims(), convPrepare(), depthwiseConvPrepare(), divPrepare(), fullyConnectedPrepare(), genericPoolingPrepare(), mulPrepare(), padPrepare(), softmaxFloat32(), and subPrepare().
SameShape()
bool SameShape (const Shape & in1, const Shape & in2)
Definition at line 22 of file Shape.cpp.
{
  if (in1.type != in2.type || in1.dimensions.size() != in2.dimensions.size())
  {
    return false;
  }
  for (size_t i = 0; i < in1.dimensions.size(); i++)
  {
    if (in1.dimensions[i] != in2.dimensions[i])
    {
      return false;
    }
  }
  return true;
}
References Shape::dimensions, and Shape::type.
Referenced by addFloat32(), addPrepare(), divFloat32(), divPrepare(), mulFloat32(), mulPrepare(), subFloat32(), and subPrepare().
SetShape()
bool SetShape (const Shape & in, Shape * out)
Definition at line 38 of file Shape.cpp.
{
  if (in.type != out->type || in.dimensions.size() != out->dimensions.size())
  {
    return false;
  }
  out->dimensions = in.dimensions;
  return true;
}
References Shape::dimensions, and Shape::type.
Referenced by addPrepare(), divPrepare(), genericActivationPrepare(), mulPrepare(), and subPrepare().