ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Concatenation.h File Reference
Concatenation.h File Reference
#include "Shape.h"
#include <vector>
#include <cstdint>
Functions
bool concatenationPrepare (const std::vector< Shape > &inputShapes, int32_t axis, Shape *output)
Function Documentation
concatenationPrepare()
bool concatenationPrepare (const std::vector< Shape > & inputShapes, int32_t axis, Shape * output)
Definition at line 21 of file Concatenation.cpp.
{
  int num_inputs = inputShapes.size();
  OperandType input_type = inputShapes[0].type;
  uint32_t num_dimensions = getNumberOfDimensions(inputShapes[0]);
  ASSERT(axis >= 0);
  ASSERT(axis < (int32_t)num_dimensions);
  int sum_axis = getSizeOfDimension(inputShapes[0], axis);
  for (int i = 1; i < num_inputs; ++i)
  {
    ASSERT(getNumberOfDimensions(inputShapes[i]) == num_dimensions);
    ASSERT(inputShapes[i].type == inputShapes[0].type);
    if (input_type == OperandType::TENSOR_QUANT8_ASYMM)
    {
      ASSERT(inputShapes[0].offset == inputShapes[i].offset);
      ASSERT(inputShapes[0].scale == inputShapes[i].scale);
    }
    for (int d = 0; d < (int32_t)num_dimensions; ++d)
    {
      if (d == axis)
      {
        sum_axis += getSizeOfDimension(inputShapes[i], axis);
      }
      else
      {
        ASSERT(getSizeOfDimension(inputShapes[0], d) ==
                     getSizeOfDimension(inputShapes[i], d));
      }
    }
  }
  output->type = input_type;
  output->dimensions = inputShapes[0].dimensions;
  output->dimensions[axis] = sum_axis;
  if (input_type == OperandType::TENSOR_QUANT8_ASYMM)
  {
    ASSERT(inputShapes[0].offset == output->offset);
    ASSERT(inputShapes[0].scale == output->scale);
  }
  return true;
}
References ASSERT, getNumberOfDimensions(), getSizeOfDimension(), and offset().