ONE - On-device Neural Engine: compiler/ann-ref/src/ops/Conv2D.h File Reference
Conv2D.h File Reference
#include "Shape.h"
#include <cstdint>
Functions
bool convPrepare (const Shape &input, const Shape &filter, const Shape &bias, int32_t padding_left, int32_t padding_right, int32_t padding_top, int32_t padding_bottom, int32_t stride_width, int32_t stride_height, Shape *output)
Function Documentation
convPrepare()
bool convPrepare (const Shape & input, const Shape & filter, const Shape & bias, int32_t padding_left, int32_t padding_right, int32_t padding_top, int32_t padding_bottom, int32_t stride_width, int32_t stride_height, Shape * output)
Definition at line 23 of file Conv2D.cpp.
{
  ASSERT(input.type == filter.type);
  if (input.type == OperandType::TENSOR_QUANT8_ASYMM)
  {
    ASSERT(bias.type == OperandType::TENSOR_INT32);
  }
  else
  {
    ASSERT(input.type == bias.type);
  }
  ASSERT(getNumberOfDimensions(input) == 4);
  ASSERT(getNumberOfDimensions(filter) == 4);
  ASSERT(getNumberOfDimensions(bias) == 1);
  ASSERT(getSizeOfDimension(filter, 0) == getSizeOfDimension(bias, 0));
  ASSERT(getSizeOfDimension(filter, 3) == getSizeOfDimension(input, 3));
  uint32_t channels_out = getSizeOfDimension(filter, 0);
  uint32_t width = getSizeOfDimension(input, 2);
  uint32_t height = getSizeOfDimension(input, 1);
  uint32_t filterWidth = getSizeOfDimension(filter, 2);
  uint32_t filterHeight = getSizeOfDimension(filter, 1);
  uint32_t batches = getSizeOfDimension(input, 0);
  uint32_t outWidth = computeOutSize(width, filterWidth, stride_width, padding_left, padding_right);
  uint32_t outHeight =
      computeOutSize(height, filterHeight, stride_height, padding_top, padding_bottom);
  output->type = input.type;
  output->dimensions = {batches, outHeight, outWidth, channels_out};
  return true;
}
References ASSERT, computeOutSize(), getNumberOfDimensions(), and getSizeOfDimension().