ONE - On-device Neural Engine: compiler/circlechef/tools/console/Driver.cpp File Reference
Driver.cpp File Reference
#include "circlechef/ModelChef.h"
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/io/zero_copy_stream_impl.h>
#include <google/protobuf/text_format.h>
#include <iostream>
Functions
int entry_stream (std::istream &is)
int entry (int, char **)
Function Documentation
entry()
int entry (int argc, char ** argv)
Definition at line 60 of file Driver.cpp.
{
  // forward to entry_stream
  return entry_stream(std::cin);
}
References entry_stream().
entry_stream()
int entry_stream (std::istream & is)
Definition at line 25 of file Driver.cpp.
{
  int32_t model_version = 1;
  ::circlechef::ModelRecipe model_recipe;
  // Read a model recipe from standard input
  {
    google::protobuf::io::IstreamInputStream iis{&is};
    if (!google::protobuf::TextFormat::Parse(&iis, &model_recipe))
    {
      std::cerr << "ERROR: Failed to parse recipe" << std::endl;
      return 255;
    }
    if (model_recipe.has_version())
    {
      model_version = model_recipe.version();
    }
  }
  if (model_version > 1)
  {
    std::cerr << "ERROR: Unsupported recipe version: " << model_version << std::endl;
    return 255;
  }
  auto generated_model = circlechef::cook(model_recipe);
  // Write a generated model into standard output
  std::cout.write(generated_model.base(), generated_model.size());
  return 0;
}
References circlechef::cook().
Referenced by entry().