ONE - On-device Neural Engine: compiler/circle-part-driver/src/Driver.cpp File Reference
Driver.cpp File Reference
#include "PModelsRunner.h"
#include <luci/Log.h>
#include <iostream>
Functions
int entry (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Definition at line 23 of file Driver.cpp.
{
  LOGGER(l);
  if (argc != 5)
  {
    std::cerr
      << "Usage: " << argv[0]
      << " <path/to/partition/config> <num_inputs> <path/to/input/prefix> <path/to/output/file>\n";
    return EXIT_FAILURE;
  }
  // NOTE: about input/output data file name
  // - I/O file name format is like filename.ext0, filename.ext1, ...
  // NOTE: about output shape
  // - file name with filename.ext0.shape, filename.ext1.shape, ...
  //   having one line text content of CSV format(like H,W or N,C,H,W)
  const char *config_filename = argv[1];
  const int32_t num_inputs = atoi(argv[2]);
  const char *input_prefix = argv[3];
  const char *output_file = argv[4];
  prunner::PModelsRunner pmrunner;
  INFO(l) << "Read config file: " << config_filename << std::endl;
  if (not pmrunner.load_config(config_filename))
    return EXIT_FAILURE;
  INFO(l) << "Read input file: " << input_prefix << ", #inputs: " << num_inputs << std::endl;
  pmrunner.load_inputs(input_prefix, num_inputs);
  INFO(l) << "Run all partitioned models..." << std::endl;
  if (!pmrunner.run())
    return EXIT_FAILURE;
  INFO(l) << "Save output file: " << output_file << std::endl;
  pmrunner.save_outputs(output_file);
  return EXIT_SUCCESS;
}
References INFO, prunner::PModelsRunner::load_config(), prunner::PModelsRunner::load_inputs(), LOGGER, prunner::PModelsRunner::run(), and prunner::PModelsRunner::save_outputs().