ONE - On-device Neural Engine: compiler/onnx2tflite/src/Driver.cpp File Reference
Driver.cpp File Reference
#include <ONNXImporterImpl.h>
#include <mir2loco.h>
#include <exo/TFLExporter.h>
#include <iostream>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 52 of file Driver.cpp.
{
  // onnx2tflite <mode> <path/to/onnx> <path/to/output>
  // modes: -t (text file); -b (binary file)
  if (argc != 4)
  {
    printHelp();
    exit(1);
  }
  std::string mode{argv[1]};
  std::string onnx_path{argv[2]};
  std::string tflite_path{argv[3]};
  std::cout << "Import " << quote(onnx_path) << std::endl;
  std::unique_ptr<mir::Graph> mir_graph;
  if (mode == "-t")
    mir_graph = mir_onnx::importModelFromTextFile(onnx_path);
  else if (mode == "-b")
    mir_graph = mir_onnx::importModelFromBinaryFile(onnx_path);
  else
  {
    printHelp();
    exit(1);
  }
  std::cout << "Import " << quote(onnx_path) << " - Done" << std::endl;
  auto loco_graph = transform(mir_graph);
  exo::TFLExporter(loco_graph.get()).dumpToFile(tflite_path.c_str());
  return 0;
}
References exo::TFLExporter::dumpToFile(), mir_onnx::importModelFromBinaryFile(), and mir_onnx::importModelFromTextFile().