ONE - On-device Neural Engine: compiler/tflite2circle/driver/Driver.cpp File Reference
Driver.cpp File Reference
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <arser/arser.h>
#include "CircleModel.h"
#include "TFLModel.h"
#include <vconone/vconone.h>
Functions
void print_version (void)
int entry (int argc, char **argv)
Dump IR for given arguments.
Function Documentation
entry()
int entry (int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 35 of file Driver.cpp.
{
  arser::Arser arser{"tflite2circle is a Tensorflow lite to circle model converter"};
  arser::Helper::add_version(arser, print_version);
  arser::Helper::add_verbose(arser);
  arser.add_argument("tflite").help("Source tflite file path to convert");
  arser.add_argument("circle").help("Target circle file path");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cerr << err.what() << std::endl;
    std::cout << arser;
    return 255;
  }
  std::string tfl_path = arser.get<std::string>("tflite");
  std::string circle_path = arser.get<std::string>("circle");
  // read tflite file
  tflite2circle::TFLModel tfl_model(tfl_path);
  if (not tfl_model.verify_data())
  {
    std::cerr << "ERROR: Failed to verify tflite '" << tfl_path << "'" << std::endl;
    return 255;
  }
  // create flatbuffer builder
  auto flatbuffer_builder = std::make_unique<flatbuffers::FlatBufferBuilder>(1024);
  // convert tflite to circle
  tflite2circle::CircleModel circle_model{flatbuffer_builder};
  circle_model.load_offsets(tfl_model.get_model());
  circle_model.model_build();
  std::ofstream outfile{circle_path, std::ios::binary};
  outfile.write(circle_model.base(), circle_model.size());
  outfile.close();
  // TODO find a better way of error handling
  if (outfile.fail())
  {
    std::cerr << "ERROR: Failed to write circle '" << circle_path << "'" << std::endl;
    return 255;
  }
  return 0;
}
References arser::Helper::add_verbose(), arser::Helper::add_version(), and print_version().
print_version()
void print_version (void)
Definition at line 29 of file Driver.cpp.
{
  std::cout << "tflite2circle version " << vconone::get_string() << std::endl;
  std::cout << vconone::get_copyright() << std::endl;
}
References vconone::get_copyright(), and vconone::get_string().