ONE - On-device Neural Engine: compiler/record-minmax/driver/Driver.cpp File Reference
Driver.cpp File Reference
#include "RecordMinMax.h"
#include <arser/arser.h>
#include <vconone/vconone.h>
#include <luci/UserSettings.h>
#include <luci/Log.h>
Functions
void print_version (void)
int entry (const int argc, char **argv)
Dump IR for given arguments.
Function Documentation
entry()
int entry (const int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 33 of file Driver.cpp.
{
  using namespace record_minmax;
  LOGGER(l);
  arser::Arser arser(
    "Embedding min/max values of activations to the circle model for post-training quantization");
  arser::Helper::add_version(arser, print_version);
  arser::Helper::add_verbose(arser);
  arser.add_argument("--input_model").required(true).help("Input model filepath");
  arser.add_argument("--input_data")
    .help("Input data filepath. If not given, record-minmax will run with randomly generated data. "
          "Note that the random dataset does not represent inference workload, leading to poor "
          "model accuracy.");
  arser.add_argument("--output_model").required(true).help("Output model filepath");
  arser.add_argument("--min_percentile")
    .type(arser::DataType::FLOAT)
    .help("Record n'th percentile of min");
  arser.add_argument("--num_threads")
    .type(arser::DataType::INT32)
    .help("Number of threads (default: 1)");
  arser.add_argument("--max_percentile")
    .type(arser::DataType::FLOAT)
    .help("Record n'th percentile of max");
  arser.add_argument("--mode").help("Record mode. percentile (default) or moving_average");
  arser.add_argument("--input_data_format")
    .help("Input data format. h5/hdf5 (default) or list/filelist");
  arser.add_argument("--generate_profile_data")
    .nargs(0)
    .default_value(false)
    .help("This will turn on profiling data generation.");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cout << err.what() << std::endl;
    std::cout << arser;
    return 255;
  }
  if (arser.get<bool>("--verbose"))
  {
    // The third parameter of setenv means REPLACE.
    // If REPLACE is zero, it does not overwrite an existing value.
    setenv("LUCI_LOG", "100", 0);
  }
  auto settings = luci::UserSettings::settings();
  auto input_model_path = arser.get<std::string>("--input_model");
  auto output_model_path = arser.get<std::string>("--output_model");
  // Default values
  std::string mode("percentile");
  float min_percentile = 1.0;
  float max_percentile = 99.0;
  std::string input_data_format("h5");
  uint32_t num_threads = 1;
  if (arser["--min_percentile"])
    min_percentile = arser.get<float>("--min_percentile");
  if (arser["--num_threads"])
    num_threads = arser.get<int>("--num_threads");
  if (num_threads < 1)
    throw std::runtime_error("The number of threads must be greater than zero");
  if (arser["--max_percentile"])
    max_percentile = arser.get<float>("--max_percentile");
  if (arser["--mode"])
    mode = arser.get<std::string>("--mode");
  if (mode != "percentile" && mode != "moving_average")
    throw std::runtime_error("Unsupported mode");
  if (arser["--generate_profile_data"])
    settings->set(luci::UserSettings::Key::ProfilingDataGen, true);
  if (arser["--input_data_format"])
    input_data_format = arser.get<std::string>("--input_data_format");
  RecordMinMax rmm(num_threads);
  // TODO: support parallel record for profile with random data
  if (num_threads > 1 and not arser["--input_data"])
  {
    throw std::runtime_error("Input data must be given for parallel recording");
  }
  // Initialize interpreter and observer
  rmm.initialize(input_model_path);
  if (arser["--input_data"])
  {
    auto input_data_path = arser.get<std::string>("--input_data");
    // TODO: support parallel record from file and dir input data format
    if (num_threads > 1 and not(input_data_format == "h5") and not(input_data_format == "hdf5"))
    {
      throw std::runtime_error("Parallel recording is used only for h5 now");
    }
    if (input_data_format == "h5" || input_data_format == "hdf5")
    {
      // Profile min/max while executing the H5 data
      if (num_threads == 1)
        rmm.profileData(mode, input_data_path, min_percentile, max_percentile);
      else
      {
        INFO(l) << "Using parallel recording" << std::endl;
        rmm.profileDataInParallel(mode, input_data_path, min_percentile, max_percentile);
      }
    }
    // input_data is a text file having a file path in each line.
    // Each data file is composed of inputs of a model, concatenated in
    // the same order with the input index of the model
    //
    // For example, for a model with n inputs, the contents of each data
    // file can be visualized as below
    // [input 1][input 2]...[input n]
    // |start............end of file|
    else if (input_data_format == "list" || input_data_format == "filelist")
    {
      // Profile min/max while executing the list of Raw data
      rmm.profileRawData(mode, input_data_path, min_percentile, max_percentile);
    }
    else if (input_data_format == "directory" || input_data_format == "dir")
    {
      // Profile min/max while executing all files under the given directory
      // The contents of each file is same as the raw data in the 'list' type
      rmm.profileRawDataDirectory(mode, input_data_path, min_percentile, max_percentile);
    }
    else
    {
      throw std::runtime_error(
        "Unsupported input data format (supported formats: h5/hdf5 (default), list/filelist)");
    }
  }
  else
  {
    // Profile min/max while executing random input data
    rmm.profileDataWithRandomInputs(mode, min_percentile, max_percentile);
  }
  // Save profiled values to the model
  rmm.saveModel(output_model_path);
  return EXIT_SUCCESS;
}
References arser::Helper::add_verbose(), arser::Helper::add_version(), INFO, LOGGER, print_version(), luci::UserSettings::ProfilingDataGen, and luci::UserSettings::settings().
print_version()
void print_version (void)
Definition at line 27 of file Driver.cpp.
{
  std::cout << "record-minmax version " << vconone::get_string() << std::endl;
  std::cout << vconone::get_copyright() << std::endl;
}
References vconone::get_copyright(), and vconone::get_string().