ONE - On-device Neural Engine: compiler/ann-ref/src/ops/FullyConnected.cpp File Reference
FullyConnected.cpp File Reference
#include "FullyConnected.h"
#include "Assert.h"
Functions
bool fullyConnectedPrepare (const Shape &input, const Shape &weights, const Shape &bias, Shape *output)
Function Documentation
fullyConnectedPrepare()
bool fullyConnectedPrepare (const Shape & input, const Shape & weights, const Shape & bias, Shape * output)
Definition at line 28 of file FullyConnected.cpp.
{
  // Check all the parameters of tensor match within themselves and match the
  // input configuration.
  ASSERT(input.type == weights.type);
  if (input.type == OperandType::TENSOR_QUANT8_ASYMM)
  {
    ASSERT(bias.type == OperandType::TENSOR_INT32);
  }
  else
  {
    ASSERT(input.type == bias.type);
  }
  ASSERT(getNumberOfDimensions(input) >= 2);
  uint32_t input_size = getNumberOfElements(input);
  uint32_t num_units = getSizeOfDimension(weights, 0);
  // modified to resolve Coverity 118949 (Apr 25, 2018) by hyunsik.yoon
  // Original Code:
  // uint32_t batch_size = input_size / getSizeOfDimension(weights, 1);
  //
  // Coverity Detection: Division by zero
  //
  // Code below is modified code
  uint32_t shape_size = getSizeOfDimension(weights, 1);
  if (shape_size == 0)
  {
    return false;
  }
  uint32_t batch_size = input_size / shape_size;
  ASSERT(getSizeOfDimension(bias, 0) == num_units);
  ASSERT(getSizeOfDimension(weights, 1) * batch_size == input_size);
  ASSERT(getNumberOfDimensions(weights) == 2);
  output->type = input.type;
  output->dimensions = {batch_size, num_units};
  return true;
}
References ASSERT, getNumberOfDimensions(), getNumberOfElements(), getSizeOfDimension(), and Shape::type.