ONE - On-device Neural Engine: compiler/circle-opselector/driver/Driver.cpp File Reference
Driver.cpp File Reference
#include "ModuleIO.h"
#include "OpSelector.h"
#include <luci/ConnectNode.h>
#include <luci/Profile/CircleNodeID.h>
#include <luci/Service/CircleNodeClone.h>
#include <arser/arser.h>
#include <vconone/vconone.h>
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <cctype>
#include <numeric>
#include <sstream>
Functions
void print_version (void)
int entry (int argc, char **argv)
Function Documentation
entry()
int entry (int argc, char ** argv)
Definition at line 41 of file Driver.cpp.
{
  // TODO Add new option names!
  arser::Arser arser("circle-opselector provides selecting operations in circle model");
  arser::Helper::add_version(arser, print_version);
  // TODO Add new options!
  arser.add_argument("input").help("Input circle model");
  arser.add_argument("output").help("Output circle model");
  // select option
  arser.add_argument("--by_id").help("Input operation id to select nodes.");
  arser.add_argument("--by_name").help("Input operation name to select nodes.");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cerr << err.what() << std::endl;
    std::cout << arser;
    return EXIT_FAILURE;
  }
  std::string input_path = arser.get<std::string>("input");
  std::string output_path = arser.get<std::string>("output");
  if (!arser["--by_id"] && !arser["--by_name"] || arser["--by_id"] && arser["--by_name"])
  {
    std::cerr << "ERROR: Either option '--by_id' or '--by_name' must be specified" << std::endl;
    std::cerr << arser;
    return EXIT_FAILURE;
  }
  // Import original circle file.
  auto module = opselector::getModule(input_path);
  // TODO support two or more subgraphs
  if (module.get()->size() != 1)
  {
    std::cerr << "ERROR: Not support two or more subgraphs" << std::endl;
    return EXIT_FAILURE;
  }
  opselector::OpSelector op_selector{module.get()};
  std::unique_ptr<luci::Module> new_module;
  std::string operator_input;
  if (arser["--by_id"])
  {
    operator_input = arser.get<std::string>("--by_id");
    new_module = op_selector.select_by<opselector::SelectType::ID>(operator_input);
  }
  if (arser["--by_name"])
  {
    operator_input = arser.get<std::string>("--by_name");
    new_module = op_selector.select_by<opselector::SelectType::NAME>(operator_input);
  }
  assert(opselector::exportModule(new_module.get(), output_path));
  return 0;
}
References arser::Helper::add_version(), opselector::exportModule(), opselector::getModule(), opselector::ID, opselector::NAME, and print_version().
print_version()
void print_version (void)
Definition at line 35 of file Driver.cpp.
{
  std::cout << "circle-opselector version " << vconone::get_string() << std::endl;
  std::cout << vconone::get_copyright() << std::endl;
}
References vconone::get_copyright(), and vconone::get_string().
Referenced by entry().