ONE - On-device Neural Engine: compiler/fme-detect/driver/Driver.cpp File Reference
Driver.cpp File Reference
#include "EqualizePatternFinder.h"
#include "EqualizePatternWrite.h"
#include <arser/arser.h>
#include <foder/FileLoader.h>
#include <luci/CircleExporter.h>
#include <luci/CircleFileExpContract.h>
#include <luci/ImporterEx.h>
#include <luci/Service/Validate.h>
#include <iostream>
#include <string>
Functions
int entry (int argc, char **argv)
Dump IR for given arguments.
Function Documentation
entry()
int entry (int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 32 of file Driver.cpp.
{
  arser::Arser arser("fme-detect detects patterns to apply FM equalization in "
                     "the circle model");
  arser::Helper::add_verbose(arser);
  arser.add_argument("--input").required().help("Input circle model");
  arser.add_argument("--output")
    .required()
    .help("Output json file that describes equalization patterns");
  arser.add_argument("--allow_dup_op")
    .nargs(0)
    .default_value(false)
    .help("Allow to create duplicate operations when a feature map matches "
          "with multiple equalization patterns. This can increase the size of "
          "the model. Default is false.");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cerr << err.what() << std::endl;
    std::cout << arser;
    return EXIT_FAILURE;
  }
  if (arser.get<bool>("--verbose"))
  {
    // The third parameter of setenv means REPLACE.
    // If REPLACE is zero, it does not overwrite an existing value.
    setenv("LUCI_LOG", "100", 0);
  }
  const std::string input_path = arser.get<std::string>("--input");
  const std::string output_path = arser.get<std::string>("--output");
  const bool allow_dup_op = arser.get<bool>("--allow_dup_op");
  EqualizePatternFinder::Context ctx;
  {
    ctx._allow_dup_op = allow_dup_op;
  }
  EqualizePatternFinder finder(ctx);
  luci::ImporterEx importerex;
  auto module = importerex.importVerifyModule(input_path);
  assert(module != nullptr); // FIX_ME_UNLESS
  std::vector<EqualizePattern> patterns;
  for (size_t idx = 0; idx < module->size(); ++idx)
  {
    auto graph = module->graph(idx);
    auto matched = finder.find(graph);
    patterns.insert(patterns.end(), matched.begin(), matched.end());
  }
  fme_detect::write(patterns, output_path);
  return EXIT_SUCCESS;
}
References fme_detect::EqualizePatternFinder::Context::_allow_dup_op, arser::Helper::add_verbose(), fme_detect::EqualizePatternFinder::find(), and fme_detect::write().