ONE - On-device Neural Engine: compiler/minmax-embedder/driver/Driver.cpp File Reference
Driver.cpp File Reference
#include "minmax-embedder/Embedder.h"
#include <arser/arser.h>
#include <vconone/vconone.h>
#include <stdlib.h>
Functions
void print_version (void)
int entry (const int argc, char **argv)
Dump IR for given arguments.
Function Documentation
entry()
int entry (const int argc, char ** argv)
Dump IR for given arguments.
Call example: $ ./build/compiler/encodump/encodump \ –frontend build/compiler/enco/frontend/caffe/libenco_caffe_frontend.so \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.prototxt \ –frontend-arg build/compiler/enco/test/caffe/Convolution_003.caffemodel
HDF5 layout is like below
GROUP "/" ㄴGROUP "name" ㄴATTRIBUTE "0" ㄴDATA (0): "input_01:0" ㄴATTRIBUTE "1" ㄴDATA (0): "input_02:0" ㄴGROUP "value" ㄴDATASET "0" ㄴDATA ... ㄴDATASET "1" ㄴDATA ...
Definition at line 32 of file Driver.cpp.
{
  arser::Arser arser("minmax-embedder embeds given minmax into circle");
  arser::Helper::add_version(arser, print_version);
  // named args
  arser.add_argument("--min_percentile")
    .type(arser::DataType::FLOAT)
    .default_value(1.f)
    .help("Set min percentile (default: 1)");
  arser.add_argument("--max_percentile")
    .type(arser::DataType::FLOAT)
    .default_value(99.f)
    .help("Set max percentile (default: 99)");
  arser.add_argument("-o").default_value("out.circle").help("Path to output circle model");
  // positional args: minmax(h5), input(circle)
  arser.add_argument("circle").help("Path to input circle model");
  arser.add_argument("minmax").help("Path to minmax data in hdf5");
  try
  {
    arser.parse(argc, argv);
  }
  catch (const std::runtime_error &err)
  {
    std::cout << err.what() << std::endl;
    std::cout << arser;
    return EXIT_FAILURE;
  }
  std::string minmax_path = arser.get<std::string>("minmax");
  std::string circle_path = arser.get<std::string>("circle");
  std::string output_path = arser.get<std::string>("-o");
  float min_percentile = arser.get<float>("--min_percentile");
  float max_percentile = arser.get<float>("--max_percentile");
  EmbedderOptions opt{min_percentile, max_percentile};
  try
  {
    Embedder().embed(output_path, circle_path, minmax_path, opt);
  }
  catch (const std::runtime_error &err)
  {
    std::cout << err.what() << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
References arser::Helper::add_version(), minmax_embedder::Embedder::embed(), and print_version().
print_version()
void print_version (void)
Definition at line 26 of file Driver.cpp.
{
  std::cout << "minmax-embedder version " << vconone::get_string() << std::endl;
  std::cout << vconone::get_copyright() << std::endl;
}
References vconone::get_copyright(), and vconone::get_string().
Referenced by entry().