ONE - On-device Neural Engine: compiler/ann-ref/src/ops/internal/Elementwise.h File Reference
Elementwise.h File Reference
#include "Shape.h"
Functions
bool genericActivationPrepare (const Shape &input, Shape *output)
Function Documentation
genericActivationPrepare()
bool genericActivationPrepare (const Shape & input, Shape * output)
Definition at line 21 of file Elementwise.cpp.
{
  ASSERT(getNumberOfDimensions(input) <= 4);
  return SetShape(input, output);
}
References ASSERT, getNumberOfDimensions(), and SetShape().
Referenced by relu6Prepare(), reluPrepare(), and softmaxPrepare().