ONE - On-device Neural Engine: compiler/nnc/utils/def2src.cpp File Reference
def2src.cpp File Reference
#include <iostream>
#include <fstream>
#include <cassert>
Functions
int fileToArray (const std::string &source, const std::string &dest, const std::string &arrName)
std::string extractFileName (std::string path)
int main (int argc, char *argv[])
Function Documentation
extractFileName()
std::string extractFileName (std::string path)
Definition at line 73 of file def2src.cpp.
{
  auto pos = path.find_last_of('/');
  if (pos != std::string::npos)
    path = path.substr(pos + 1);
  pos = path.find_first_of('.');
  if (pos != std::string::npos)
    path = path.substr(0, pos);
  return path;
}
Referenced by main().
fileToArray()
int fileToArray (const std::string & source, const std::string & dest, const std::string & arrName)
Definition at line 21 of file def2src.cpp.
{
  FILE *fs = fopen(source.c_str(), "rb");
  if (!fs)
  {
    std::cerr << "source file not found: <" << source << ">" << std::endl;
    return -1;
  }
  std::ofstream fo(dest.c_str());
  if (fo.fail())
  {
    std::cerr << "cannot generate file: <" << dest << ">" << std::endl;
    fclose(fs);
    return -1;
  }
  std::cout << "generating <" << dest << ">" << std::endl;
  fo << "#ifndef _" << arrName << "_H_" << std::endl;
  fo << "#define _" << arrName << "_H_" << std::endl;
  fo << "const char " << arrName << "[] = {" << std::endl;
  int is_error = fseek(fs, 0L, SEEK_SET);
  assert(!is_error);
  (void)is_error;
  size_t bytes;
  do
  {
    char buf[1024];
    bytes = fread(buf, 1, sizeof(buf), fs);
    assert(!ferror(fs) && "file read error");
    // convert line
    for (size_t i = 0; i < bytes; i++)
    {
      fo << "0x" << std::hex << static_cast<int>(buf[i]) << ", ";
    }
  } while (bytes != 0);
  fo << "};" << std::endl;
  fo << std::endl;
  fo << "#endif /* _" << arrName << "_H_ */" << std::endl;
  fo.flush();
  fclose(fs);
  return 0;
}
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 86 of file def2src.cpp.
{
  if (argc < 3)
    return -1;
  std::string OutPutDir = argv[1];
  for (int i = 2; i < argc; i++)
  {
    std::string sourceFullFileName = argv[i];
    std::string filename = extractFileName(sourceFullFileName);
    // NOLINTNEXTLINE (performance-inefficient-string-concatenation)
    std::string outputFileName = OutPutDir + "/" + filename + ".generated.h";
    if (fileToArray(sourceFullFileName, outputFileName, filename) != 0)
      return -1;
  }
  return 0;
}
References extractFileName(), and fileToArray().