var dir_d6ac38abd3e09f1b248b4c90dea454cb =
[
    [ "TFAdd.h", "_t_f_add_8h.html", "_t_f_add_8h" ],
    [ "TFAvgPool.h", "_t_f_avg_pool_8h.html", "_t_f_avg_pool_8h" ],
    [ "TFBiasAdd.h", "_t_f_bias_add_8h.html", "_t_f_bias_add_8h" ],
    [ "TFConcatV2.h", "_t_f_concat_v2_8h.html", "_t_f_concat_v2_8h" ],
    [ "TFConst.h", "_t_f_const_8h.html", "_t_f_const_8h" ],
    [ "TFConv2D.h", "_t_f_conv2_d_8h.html", "_t_f_conv2_d_8h" ],
    [ "TFConv2DBackpropInput.h", "_t_f_conv2_d_backprop_input_8h.html", "_t_f_conv2_d_backprop_input_8h" ],
    [ "TFDepthwiseConv2dNative.h", "_t_f_depthwise_conv2d_native_8h.html", "_t_f_depthwise_conv2d_native_8h" ],
    [ "TFFakeQuantWithMinMaxVars.h", "_t_f_fake_quant_with_min_max_vars_8h.html", "_t_f_fake_quant_with_min_max_vars_8h" ],
    [ "TFFusedBatchNorm.h", "_t_f_fused_batch_norm_8h.html", "_t_f_fused_batch_norm_8h" ],
    [ "TFIdentity.h", "_t_f_identity_8h.html", "_t_f_identity_8h" ],
    [ "TFMaximum.h", "_t_f_maximum_8h.html", "_t_f_maximum_8h" ],
    [ "TFMaxPool.h", "_t_f_max_pool_8h.html", "_t_f_max_pool_8h" ],
    [ "TFMean.h", "_t_f_mean_8h.html", "_t_f_mean_8h" ],
    [ "TFMul.h", "_t_f_mul_8h.html", "_t_f_mul_8h" ],
    [ "TFPack.h", "_t_f_pack_8h.html", "_t_f_pack_8h" ],
    [ "TFPad.h", "_t_f_pad_8h.html", "_t_f_pad_8h" ],
    [ "TFPlaceholder.h", "_t_f_placeholder_8h.html", "_t_f_placeholder_8h" ],
    [ "TFPush.h", "_t_f_push_8h.html", "_t_f_push_8h" ],
    [ "TFRealDiv.h", "_t_f_real_div_8h.html", "_t_f_real_div_8h" ],
    [ "TFRelu.h", "_t_f_relu_8h.html", "_t_f_relu_8h" ],
    [ "TFRelu6.h", "_t_f_relu6_8h.html", "_t_f_relu6_8h" ],
    [ "TFReshape.h", "_t_f_reshape_8h.html", "_t_f_reshape_8h" ],
    [ "TFRsqrt.h", "_t_f_rsqrt_8h.html", "_t_f_rsqrt_8h" ],
    [ "TFShape.h", "_t_f_shape_8h.html", "_t_f_shape_8h" ],
    [ "TFSoftmax.h", "_t_f_softmax_8h.html", "_t_f_softmax_8h" ],
    [ "TFSqrt.h", "_t_f_sqrt_8h.html", "_t_f_sqrt_8h" ],
    [ "TFSquaredDifference.h", "_t_f_squared_difference_8h.html", "_t_f_squared_difference_8h" ],
    [ "TFSqueeze.h", "_t_f_squeeze_8h.html", "_t_f_squeeze_8h" ],
    [ "TFStopGradient.h", "_t_f_stop_gradient_8h.html", "_t_f_stop_gradient_8h" ],
    [ "TFStridedSlice.h", "_t_f_strided_slice_8h.html", "_t_f_strided_slice_8h" ],
    [ "TFSub.h", "_t_f_sub_8h.html", "_t_f_sub_8h" ],
    [ "TFTanh.h", "_t_f_tanh_8h.html", "_t_f_tanh_8h" ]
];