var dir_dad969bcd4bb86726cba627183e1408c =
[
    [ "FloatLogSoftmaxKernel.h", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_float_log_softmax_kernel_8h.html", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_float_log_softmax_kernel_8h" ],
    [ "NegLogSoftmaxKernel.h", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_neg_log_softmax_kernel_8h.html", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_neg_log_softmax_kernel_8h" ],
    [ "TestDataLogSoftmaxBase.h", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_test_data_log_softmax_base_8h.html", "luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_test_data_log_softmax_base_8h" ]
];