ONE - On-device Neural Engine: compiler/encodump/src/Dump.h File Reference
Dump.h File Reference
#include <coco/IR.h>
Functions
void dump (const coco::Module *module)
Function Documentation
dump()
void dump (const coco::Module * module)
Definition at line 362 of file Dump.cpp.
{
  std::cout << "<Module>" << std::endl;
  dump(module->block(), 1);
  dump(module->input(), 1);
  dump(module->output(), 1);
  dump(module->entity()->bag(), 1);
  dump(module->entity()->object(), 1);
}
References coco::EntityManager::bag(), coco::Module::block(), dump(), coco::Module::entity(), coco::Module::input(), coco::EntityManager::object(), and coco::Module::output().