ONE - On-device Neural Engine: compiler/encodump/src/Dump.cpp File Reference
Dump.cpp File Reference
Print coco IR produced from enco frontend.
#include "Dump.h"
#include <functional>
#include <iostream>
Data Structures
struct OpPrinter
struct InstrPrinter
Functions
std::string tab (int n)
void dump (const coco::Op *op, int indent)
void dump (const coco::Instr *ins, int indent)
void dump (const coco::Block *B, int indent)
void dump (const coco::BlockList *L, int indent)
template<typename SetT , typename EntityF >
void dump (std::string header, SetT set, EntityF print_addr_f)
void dump (const coco::BagManager *l, int indent)
void dump (coco::FeatureObject *feature_ob)
void dump (coco::KernelObject *kernel_ob)
void dump (const coco::ObjectManager *l, int indent)
template<typename T >
void head (int indent)
template<>
void head< coco::Input > (int indent)
template<>
void head< coco::Output > (int indent)
template<typename PtrItemT >
void dump (const coco::PtrList< PtrItemT > *list, int indent)
void dump (const coco::Module *module)
Detailed Description
Print coco IR produced from enco frontend.
Note
Some object inherits multiple parents. For example, coco:Conv2D inherits coco::Consumer and more. Assume that op is an instance of coco::Conv2D. In this case, the printing results of the following may be different: 1) cout << op; // printing address of type coco::Conv2D 2) cout << reinterpret_cast<const coco::Object::Consumer *>(op); 3) cout << object->consumer(); // assume that this object->consumer() returns op 4) cout << dynamic_cast<const coco::Object::Consumer *>(op); 1) and 2) prints same address. 3) and 4) prints same address but different from 1) and 2). For details, refer to https://stackoverflow.com/questions/22256620/why-pointers-to-the-same-object-have-different-values For dumping, we will use 3), 4)
Definition in file Dump.cpp.
Function Documentation
dump() [1/11]
void dump (coco::FeatureObject * feature_ob)
Definition at line 280 of file Dump.cpp.
{
  auto shape = feature_ob->shape();
  std::cout << "kind: Feature, Shape [H/W/D=" << shape.height() << "," << shape.width() << ","
            << shape.depth() << "]";
}
References nncc::core::ADT::feature::Shape::height(), and coco::FeatureObject::shape().
dump() [2/11]
void dump (coco::KernelObject * kernel_ob)
Definition at line 287 of file Dump.cpp.
{
  auto shape = kernel_ob->shape();
  std::cout << "kind: Kernel, Shape [N/H/W/D=" << shape.count() << "," << shape.height() << ","
            << shape.width() << "," << shape.depth() << "]";
}
References nncc::core::ADT::kernel::Shape::count(), and coco::KernelObject::shape().
dump() [3/11]
void dump (const coco::BagManager * l, int indent)
Definition at line 228 of file Dump.cpp.
{
  std::cout << tab(indent) << "<Bag>:" << std::endl;
  for (auto n = 0; n < l->size(); ++n)
  {
    auto bag = l->at(n);
    std::cout << tab(indent + 1) << bag << ", ";
    // print objects in bag->deps()
    auto print_dep_object = [](coco::Dep *dep) { std::cout << dep->object(); };
    dump("obj", bag->deps(), print_dep_object);
    std::cout << ", ";
    std::cout << "size: " << bag->size() << ", ";
    if (bag->isInput())
      std::cout << "input, ";
    if (bag->isOutput())
      std::cout << "output, ";
    if ((!bag->isInput()) || (!bag->isOutput()))
      std::cout << "const, ";
    // print readers in bag->reads()
    auto print_read_reader = [](coco::Read *read) {
      if (coco::Op *op = dynamic_cast<coco::Op *>(read->reader()))
        std::cout << "op: " << op;
      else if (coco::Instr *instr = dynamic_cast<coco::Instr *>(read->reader()))
        std::cout << "instr: " << instr;
      else
        std::cout << "x";
    };
    dump("reader", bag->reads(), print_read_reader);
    std::cout << ", ";
    // print updaters in bag->updates()
    auto print_update_updater = [](coco::Update *update) {
      if (coco::Op *op = dynamic_cast<coco::Op *>(update->updater()))
        std::cout << "op: " << op;
      else if (coco::Instr *instr = dynamic_cast<coco::Instr *>(update->updater()))
        std::cout << "instr: " << instr;
      else
        std::cout << "x";
    };
    dump("updater", bag->updates(), print_update_updater);
    std::cout << ", ";
    std::cout << std::endl;
  }
}
References dump(), and tab().
dump() [4/11]
void dump (const coco::Block * B, int indent)
Definition at line 192 of file Dump.cpp.
{
  std::cout << tab(indent) << "<Block> (index: " << B->index().value() << ")" << std::endl;
  for (auto I = B->instr()->head(); I != nullptr; I = I->next())
  {
    dump(I, indent + 1);
  }
}
References dump(), coco::DLinkedList< Child, Parent >::Head::head(), coco::Block::index(), coco::Block::instr(), tab(), and coco::BlockIndex::value().
dump() [5/11]
void dump (const coco::BlockList * L, int indent)
Definition at line 201 of file Dump.cpp.
{
  for (auto B = L->head(); B != nullptr; B = B->next())
  {
    dump(B, indent);
  }
}
References dump(), and coco::DLinkedList< Child, Parent >::Head::head().
dump() [6/11]
void dump (const coco::Instr * ins, int indent)
Definition at line 183 of file Dump.cpp.
{
  std::cout << tab(indent) << "<Inst>:" << std::endl;
  static InstrPrinter prn(indent + 1);
  ins->accept(prn);
}
References coco::Instr::accept(), and tab().
dump() [7/11]
void dump (const coco::Module * module)
Definition at line 362 of file Dump.cpp.
{
  std::cout << "<Module>" << std::endl;
  dump(module->block(), 1);
  dump(module->input(), 1);
  dump(module->output(), 1);
  dump(module->entity()->bag(), 1);
  dump(module->entity()->object(), 1);
}
References coco::EntityManager::bag(), coco::Module::block(), dump(), coco::Module::entity(), coco::Module::input(), coco::EntityManager::object(), and coco::Module::output().
dump() [8/11]
void dump (const coco::ObjectManager * l, int indent)
Definition at line 294 of file Dump.cpp.
{
  std::cout << tab(indent) << "<Object>:" << std::endl;
  for (auto n = 0; n < l->size(); ++n)
  {
    auto obj = l->at(n);
    std::cout << tab(indent + 1) << obj << ", bag: " << obj->bag() << ", ";
    using ObDumpers = std::function<void(coco::Object * ob)>;
    std::map<coco::Object::Kind, ObDumpers> ob_dumpers;
    ob_dumpers[coco::Object::Kind::Feature] = [](coco::Object *ob) { dump(ob->asFeature()); };
    ob_dumpers[coco::Object::Kind::Kernel] = [](coco::Object *ob) { dump(ob->asKernel()); };
    ob_dumpers[coco::Object::Kind::Unknown] = [](coco::Object *ob) {
      std::cout << "kind: Unknown";
    };
    ob_dumpers[obj->kind()](obj);
    std::cout << ", producer: ";
    auto def = obj->def();
    if (def)
    {
      if (coco::Op *op = dynamic_cast<coco::Op *>(def->producer()))
        std::cout << "op: " << op;
      else if (coco::Instr *instr = dynamic_cast<coco::Instr *>(def->producer()))
        std::cout << "instr: " << instr;
      else
        std::cout << "x";
    }
    else
      std::cout << "x";
    std::cout << ", ";
    // print consumers in obj->uses()
    auto print_consumer = [](coco::Use *use) {
      if (coco::Op *op = dynamic_cast<coco::Op *>(use->consumer()))
        std::cout << "op: " << op;
      else if (coco::Instr *instr = dynamic_cast<coco::Instr *>(use->consumer()))
        std::cout << "inst: " << instr;
      else
        std::cout << "x";
    };
    dump("comsumer", obj->uses(), print_consumer);
    std::cout << std::endl;
  }
}
References coco::Object::asFeature(), coco::Object::asKernel(), dump(), and tab().
dump() [9/11]
void dump (const coco::Op * op, int indent)
Definition at line 177 of file Dump.cpp.
{
  OpPrinter prn(std::cout, indent);
  op->accept(prn);
}
References coco::Op::accept().
Referenced by dump(), entry(), and operator<<().
dump() [10/11]
template<typename PtrItemT > void dump (const coco::PtrList< PtrItemT > * list, int indent)
Definition at line 349 of file Dump.cpp.
{
  head<PtrItemT>(indent);
  for (int n = 0; n < list->size(); n++)
  {
    const PtrItemT *item = list->at(n);
    if (n != 0)
      std::cout << ", ";
    std::cout << "bag " << item->bag() << ", name=" << item->name();
  }
  std::cout << std::endl;
}
References coco::PtrList< T >::at(), and coco::PtrList< T >::size().
dump() [11/11]
template<typename SetT , typename EntityF > void dump (std::string header, SetT set, EntityF print_addr_f)
Definition at line 210 of file Dump.cpp.
{
  std::cout << header << ": [";
  if (set->size() == 0)
    std::cout << "x";
  else
  {
    int idx = 0;
    for (auto entity : *set)
    {
      if (idx++ != 0)
        std::cout << ", ";
      print_addr_f(entity);
    }
  }
  std::cout << "]";
}
head()
template<typename T > void head (int indent)
Referenced by nncc::core::ADT::kernel::IndexEnumerator::advance().
head< coco::Input >()
template<> void head< coco::Input > (int indent)
Definition at line 345 of file Dump.cpp.
{ std::cout << tab(indent) << "<Input>: "; }
References tab().
head< coco::Output >()
template<> void head< coco::Output > (int indent)
Definition at line 347 of file Dump.cpp.
{ std::cout << tab(indent) << "<Output>: "; }
References tab().
tab()
std::string tab (int n)
Definition at line 38 of file Dump.cpp.
{ return std::string(n * 2, ' '); }
Referenced by dump(), head< coco::Input >(), head< coco::Output >(), InstrPrinter::visit(), and OpPrinter::visit().