ONE - On-device Neural Engine: runtime/libs/ndarray/example/example_array.cpp File Reference
example_array.cpp File Reference
#include "ndarray/Array.h"
#include <iostream>
#include <iterator>
Functions
void gather_array (const Array< float > &input, Array< float > &output, const Array< int > &indices)
int main ()
Function Documentation
gather_array()
void gather_array (const Array< float > & input, Array< float > & output, const Array< int > & indices)
Definition at line 24 of file example_array.cpp.
{
  assert(indices.shape().rank() == 3);
  assert(input.shape().rank() == 3);
  assert(indices.shape().dim(1) == input.shape().rank());
  for (size_t i = 0; i < indices.shape().dim(0); ++i)
  {
    for (size_t j = 0; j < indices.shape().dim(1); ++j)
    {
      auto index = indices.slice(i, j);
      output.slice(i, j).assign(input.slice(index[0], index[1]));
    }
  }
}
References ndarray::Shape::dim(), ndarray::Shape::rank(), ndarray::Array< T >::shape(), and ndarray::Array< T >::slice().
Referenced by main().
main()
int main ()
Definition at line 40 of file example_array.cpp.
{
  // fill tensor of shape[3,3,4] with sequential numbers from [0..36)
  Shape in_shape{3, 3, 4};
  std::vector<float> input_data(in_shape.element_count());
  for (size_t i = 0; i < in_shape.element_count(); ++i)
    input_data[i] = i;
  Array<float> input(input_data.data(), in_shape);
  // select column-vectors on main diagonal
  Shape indices_shape{1, 3, 2};
  std::vector<int> indices_data(indices_shape.element_count());
  Array<int> indices(indices_data.data(), indices_shape);
  indices.slice(0, 0) = {0, 0};
  indices.slice(0, 1) = {1, 1};
  indices.slice(0, 2) = {2, 2};
  Shape output_shape{1, 3, 4};
  std::vector<float> output_data(output_shape.element_count());
  Array<float> output(output_data.data(), output_shape);
  gather_array(input, output, indices);
  for (size_t i = 0; i < indices_shape.dim(0); ++i)
  {
    for (size_t j = 0; j < indices_shape.dim(1); ++j)
    {
      auto output_piece = output.slice(i, j);
      std::ostream_iterator<int> cout_it(std::cout, ", ");
      std::copy(output_piece.begin(), output_piece.end(), cout_it);
      std::cout << std::endl;
    }
  }
}
References gather_array(), and ndarray::Array< T >::slice().
Referenced by main(), and utils::safemain().