ONE - On-device Neural Engine: compute/ARMComputeEx/src/core/CL/cl_kernels/helpers_asymm.h File Reference
helpers_asymm.h File Reference
#include "helpers.h"
Macros
#define CONVERT_DOWN_RTE_STR(x, type) (convert_##type##_rte((x)))
#define CONVERT_DOWN_RTE(x, type) CONVERT_DOWN_RTE_STR(x, type)
#define QUANTIZE_IMPL(type, size)
#define DEQUANTIZE_IMPL(type, size)
#define ASYMM_ROUNDING_DIVIDE_BY_POW2_IMPL(size)
#define ASYMM_MULT_IMPL(size)
#define ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL_IMPL(size)
#define ASYMM_SELECT_USING_MASK_IMPL(size)
#define ASYMM_MASK_IF_ZERO_IMPL(size)
#define ASYMM_MASK_IF_NON_ZERO_IMPL(size)
#define EXP_BARREL_SHIFTER_IMPL(size)
#define ASYMM_EXP_ON_NEGATIVE_VALUES_IMPL(size)
#define ASYMM_SATURATING_ROUNDING_MULT_BY_POW2_IMPL(size)
#define ASYMM_ROUNDING_HALF_SUM_IMPL(size)
#define ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1_IMPL(size)
#define ASYMM_RESCALE_IMPL(size)
#define QUANTIZE_STR(input, offset, scale, type, size) quantize_##type##size(input, offset, scale)
#define QUANTIZE(input, offset, scale, type, size) QUANTIZE_STR(input, offset, scale, type, size)
#define DEQUANTIZE_STR(input, offset, scale, type, size) dequantize_##type##size(input, offset, scale)
#define DEQUANTIZE(input, offset, scale, type, size) DEQUANTIZE_STR(input, offset, scale, type, size)
#define ASYMM_ROUNDING_DIVIDE_BY_POW2(x, exponent, size) asymm_rounding_divide_by_POW2_##size(x, exponent)
#define ASYMM_MULT(a, b, size) asymm_mult##size(a, b)
#define ASYMM_MULT_BY_QUANT_MULTIPLIER_GREATER_THAN_ONE(x, quantized_multiplier, left_shift, size) ASYMM_MULT(x *((VEC_DATA_TYPE(int, size))(1) << (-left_shift)), quantized_multiplier, size)
#define ASYMM_MULT_BY_QUANT_MULTIPLIER_LESS_THAN_ONE(x, quantized_multiplier, right_shift, size) ASYMM_ROUNDING_DIVIDE_BY_POW2(ASYMM_MULT(x, quantized_multiplier, size), right_shift, size)
#define ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL(a, size) asymm_exp_on_interval_between_negative_one_quarter_and_0_excl##size(a)
#define ASYMM_SELECT_USING_MASK(if_mask, then_val, else_val, size) asymm_select_using_mask##size(if_mask, then_val, else_val)
#define ASYMM_MASK_IF_ZERO(a, size) asymm_mask_if_zero##size(a)
#define ASYMM_MASK_IF_NON_ZERO(a, size) asymm_mask_if_non_zero##size(a)
#define EXP_BARREL_SHIFTER(result, exponent, fp_multiplier, k_integer_bits, k_fractional_bits, remainder, size)
#define ASYMM_EXP_ON_NEGATIVE_VALUES(a, k_integer_bits, size) asymm_exp_on_negative_values##size(a, k_integer_bits)
#define ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1(a, size) asymm_one_over_one_plus_x_for_x_in_0_1##size(a)
#define ASYMM_SATURATING_ROUNDING_MULT_BY_POW2(x, exponent, size) asymm_saturating_rounding_mult_by_pow2##size(x, exponent)
#define ASYMM_ROUNDING_HALF_SUM(a, b, size) asymm_rounding_half_sum##size(a, b)
#define ASYMM_RESCALE(value, src_integer_bits, dst_integer_bits, size) asymm_rescale##size(value, src_integer_bits, dst_integer_bits)
#define MULTIPLY_BY_QUANTIZED_MULTIPLIER_IMPL(size)
#define MULTIPLY_BY_QUANTIZED_MULTIPLIER(input, qmul, shift, size) multiply_by_quantized_multiplier##size(input, qmul, shift)
Functions
uchar quantize_qasymm8 (float input, float offset, float scale)
float dequantize_qasymm8 (uchar input, float offset, float scale)
float dequantize_qasymm8_signed (char input, float offset, float scale)
Macro Definition Documentation
ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL
#define ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL (a, size) asymm_exp_on_interval_between_negative_one_quarter_and_0_excl##size(a)
Definition at line 445 of file helpers_asymm.h.
ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL_IMPL
#define ASYMM_EXP_ON_INTERVAL_BETWEEN_NEGATIVE_ONE_QUARTER_AND_0_EXCL_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                                                \
    asymm_exp_on_interval_between_negative_one_quarter_and_0_excl##size(VEC_DATA_TYPE(int, size) \
                                                                          a)                     \
  {                                                                                              \
    const VEC_DATA_TYPE(int, size) constant_term = 1895147668;                                   \
    const VEC_DATA_TYPE(int, size) constant_1_over_3 = 715827883;                                \
    const int k_fractional_bits = 31;                                                            \
    VEC_DATA_TYPE(int, size)                                                                     \
    x = a + (1 << (k_fractional_bits - 3));                                                      \
    VEC_DATA_TYPE(int, size)                                                                     \
    x2 = ASYMM_MULT(x, x, size);                                                                 \
    VEC_DATA_TYPE(int, size)                                                                     \
    x3 = ASYMM_MULT(x2, x, size);                                                                \
    VEC_DATA_TYPE(int, size)                                                                     \
    x4 = ASYMM_MULT(x2, x2, size);                                                               \
    VEC_DATA_TYPE(int, size)                                                                     \
    x4_over_4 = ASYMM_ROUNDING_DIVIDE_BY_POW2(x4, 2, size);                                      \
    VEC_DATA_TYPE(int, size)                                                                     \
    x4_over_24_plus_x3_over_6_plus_x2 =                                                          \
      ASYMM_MULT((x4_over_4 + x3), constant_1_over_3, size) + x2;                                \
    VEC_DATA_TYPE(int, size)                                                                     \
    x4_over_24_plus_x3_over_6_plus_x2_over_2 =                                                   \
      ASYMM_ROUNDING_DIVIDE_BY_POW2(x4_over_24_plus_x3_over_6_plus_x2, 1, size);                 \
    return constant_term +                                                                       \
           ASYMM_MULT(constant_term, x + x4_over_24_plus_x3_over_6_plus_x2_over_2, size);        \
  }
Calculates for x in [-1/4, 0).
Parameters
[in] size Size of vector.
Returns
Result in fixed-point format Q0.
Definition at line 189 of file helpers_asymm.h.
ASYMM_EXP_ON_NEGATIVE_VALUES
#define ASYMM_EXP_ON_NEGATIVE_VALUES (a, k_integer_bits, size) asymm_exp_on_negative_values##size(a, k_integer_bits)
Definition at line 455 of file helpers_asymm.h.
ASYMM_EXP_ON_NEGATIVE_VALUES_IMPL
#define ASYMM_EXP_ON_NEGATIVE_VALUES_IMPL (size)
Calculates for x < 0.
Parameters
[in] size Size of vector.
Returns
Result in fixed-point format Q0.
Definition at line 286 of file helpers_asymm.h.
ASYMM_MASK_IF_NON_ZERO
#define ASYMM_MASK_IF_NON_ZERO (a, size) asymm_mask_if_non_zero##size(a)
Definition at line 450 of file helpers_asymm.h.
ASYMM_MASK_IF_NON_ZERO_IMPL
#define ASYMM_MASK_IF_NON_ZERO_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) asymm_mask_if_non_zero##size(VEC_DATA_TYPE(int, size) a) \
  {                                                                                        \
    const VEC_DATA_TYPE(int, size) all_zeros = 0;                                          \
    const VEC_DATA_TYPE(int, size) all_ones = ~0;                                          \
    return select(all_zeros, all_ones, a != 0);                                            \
  }
For each element of input vector, the corresponding bits of the result item are set if the input item is non-zero.
Parameters
[in] size Size of vector.
Returns
Output vector with bits set when corresponding bit in a is non zero.
Definition at line 256 of file helpers_asymm.h.
ASYMM_MASK_IF_ZERO
#define ASYMM_MASK_IF_ZERO (a, size) asymm_mask_if_zero##size(a)
Definition at line 449 of file helpers_asymm.h.
ASYMM_MASK_IF_ZERO_IMPL
#define ASYMM_MASK_IF_ZERO_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) asymm_mask_if_zero##size(VEC_DATA_TYPE(int, size) a) \
  {                                                                                    \
    const VEC_DATA_TYPE(int, size) all_zeros = 0;                                      \
    const VEC_DATA_TYPE(int, size) all_ones = ~0;                                      \
    return select(all_zeros, all_ones, a == 0);                                        \
  }
For each element of input vector, the corresponding bits of the result item are set if the input item is zero.
Parameters
[in] size Size of vector.
Returns
Output vector with bits set when corresponding bit in a is zero.
Definition at line 241 of file helpers_asymm.h.
ASYMM_MULT
#define ASYMM_MULT (a, b, size) asymm_mult##size(a, b)
Definition at line 440 of file helpers_asymm.h.
ASYMM_MULT_BY_QUANT_MULTIPLIER_GREATER_THAN_ONE
#define ASYMM_MULT_BY_QUANT_MULTIPLIER_GREATER_THAN_ONE (x, quantized_multiplier, left_shift, size) ASYMM_MULT(x *((VEC_DATA_TYPE(int, size))(1) << (-left_shift)), quantized_multiplier, size)
Definition at line 441 of file helpers_asymm.h.
ASYMM_MULT_BY_QUANT_MULTIPLIER_LESS_THAN_ONE
#define ASYMM_MULT_BY_QUANT_MULTIPLIER_LESS_THAN_ONE (x, quantized_multiplier, right_shift, size) ASYMM_ROUNDING_DIVIDE_BY_POW2(ASYMM_MULT(x, quantized_multiplier, size), right_shift, size)
Definition at line 443 of file helpers_asymm.h.
ASYMM_MULT_IMPL
#define ASYMM_MULT_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                            \
    asymm_mult##size(VEC_DATA_TYPE(int, size) a, VEC_DATA_TYPE(int, size) b) \
  {                                                                          \
    VEC_DATA_TYPE(int, size)                                                 \
    overflow = a == b && a == INT_MIN;                                       \
    VEC_DATA_TYPE(long, size)                                                \
    a_64 = convert_long##size(a);                                            \
    VEC_DATA_TYPE(long, size)                                                \
    b_64 = convert_long##size(b);                                            \
    VEC_DATA_TYPE(long, size)                                                \
    ab_64 = a_64 * b_64;                                                     \
    /* Revert COMPMID-907 */                                                 \
    VEC_DATA_TYPE(long, size)                                                \
    mask1 = 1 << 30;                                                         \
    VEC_DATA_TYPE(long, size)                                                \
    mask2 = 1 - (1 << 30);                                                   \
    VEC_DATA_TYPE(long, size)                                                \
    is_positive_or_zero = ab_64 >= 0;                                        \
    VEC_DATA_TYPE(long, size)                                                \
    nudge = select(mask2, mask1, is_positive_or_zero);                       \
    VEC_DATA_TYPE(long, size)                                                \
    mask = 1ll << 31;                                                        \
    VEC_DATA_TYPE(int, size)                                                 \
    ab_x2_high32 = convert_int##size((ab_64 + nudge) / mask);                \
    return select(ab_x2_high32, INT_MAX, overflow);                          \
  }
Product of two numbers, interpreting them as fixed-point values in the interval [-1, 1), rounding to the nearest value, and saturating -1 * -1 to the maximum value.
Parameters
[in] size Size of vector.
Returns
Product of two fixed-point numbers.
Definition at line 155 of file helpers_asymm.h.
ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1
#define ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1 (a, size) asymm_one_over_one_plus_x_for_x_in_0_1##size(a)
Definition at line 457 of file helpers_asymm.h.
ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1_IMPL
#define ASYMM_ONE_OVER_ONE_PLUS_X_FOR_X_IN_0_1_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                              \
    asymm_one_over_one_plus_x_for_x_in_0_1##size(VEC_DATA_TYPE(int, size) a)   \
  {                                                                            \
    const VEC_DATA_TYPE(int, size) Q0_one = INT_MAX;                           \
    const VEC_DATA_TYPE(int, size) Q2_one = 1 << (31 - 2);                     \
    VEC_DATA_TYPE(int, size)                                                   \
    half_denominator = ASYMM_ROUNDING_HALF_SUM(a, Q0_one, size);               \
    const VEC_DATA_TYPE(int, size) Q2_48_over_17 = 1515870810;                 \
    const VEC_DATA_TYPE(int, size) Q2_neg_32_over_17 = -1010580540;            \
    VEC_DATA_TYPE(int, size)                                                   \
    x = Q2_48_over_17 + ASYMM_MULT(half_denominator, Q2_neg_32_over_17, size); \
    for (int i = 0; i < 3; i++)                                                \
    {                                                                          \
      VEC_DATA_TYPE(int, size)                                                 \
      half_denominator_times_x = ASYMM_MULT(half_denominator, x, size);        \
      VEC_DATA_TYPE(int, size)                                                 \
      one_minus_half_denominator_times_x = Q2_one - half_denominator_times_x;  \
      VEC_DATA_TYPE(int, size)                                                 \
      tmp = ASYMM_MULT(x, one_minus_half_denominator_times_x, size);           \
      x = x + ASYMM_SATURATING_ROUNDING_MULT_BY_POW2(tmp, 2, size);            \
    }                                                                          \
    return ASYMM_SATURATING_ROUNDING_MULT_BY_POW2(x, 1, size);                 \
  }
Calculates for x in (0, 1).
Parameters
[in] size Size of vector.
Returns
Result in fixed-point format Q0.
Definition at line 391 of file helpers_asymm.h.
ASYMM_RESCALE
#define ASYMM_RESCALE (value, src_integer_bits, dst_integer_bits, size) asymm_rescale##size(value, src_integer_bits, dst_integer_bits)
Definition at line 462 of file helpers_asymm.h.
ASYMM_RESCALE_IMPL
#define ASYMM_RESCALE_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) asymm_rescale##size(VEC_DATA_TYPE(int, size) value,             \
                                                      int src_integer_bits, int dst_integer_bits) \
  {                                                                                               \
    int exponent = src_integer_bits - dst_integer_bits;                                           \
    return ASYMM_SATURATING_ROUNDING_MULT_BY_POW2(value, exponent, size);                         \
  }
Considering the integer value as fixed-point, change the number of integer bits and update value accordingly.
Parameters
[in] size Size of vector.
Returns
Rescaled value.
Definition at line 423 of file helpers_asymm.h.
ASYMM_ROUNDING_DIVIDE_BY_POW2
#define ASYMM_ROUNDING_DIVIDE_BY_POW2 (x, exponent, size) asymm_rounding_divide_by_POW2_##size(x, exponent)
Definition at line 438 of file helpers_asymm.h.
ASYMM_ROUNDING_DIVIDE_BY_POW2_IMPL
#define ASYMM_ROUNDING_DIVIDE_BY_POW2_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) asymm_rounding_divide_by_POW2_##size( \
    VEC_DATA_TYPE(int, size) x, VEC_DATA_TYPE(int, size) exponent)      \
  {                                                                     \
    const VEC_DATA_TYPE(int, size) zero = (VEC_DATA_TYPE(int, size))0;  \
    const VEC_DATA_TYPE(int, size) one = (VEC_DATA_TYPE(int, size))1;   \
    VEC_DATA_TYPE(int, size)                                            \
    mask = (one << exponent) - one;                                     \
    VEC_DATA_TYPE(int, size)                                            \
    threshold = (mask >> 1) + select(zero, one, x < 0);                 \
    return (x >> exponent) + select(zero, one, (x & mask) > threshold); \
  }
Correctly-rounded-to-nearest division by a power-of-two.
Parameters
[in] size Size of vector.
Returns
Correctly-rounded-to-nearest division by a power-of-two.
Definition at line 135 of file helpers_asymm.h.
ASYMM_ROUNDING_HALF_SUM
#define ASYMM_ROUNDING_HALF_SUM (a, b, size) asymm_rounding_half_sum##size(a, b)
Definition at line 461 of file helpers_asymm.h.
ASYMM_ROUNDING_HALF_SUM_IMPL
#define ASYMM_ROUNDING_HALF_SUM_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                                         \
    asymm_rounding_half_sum##size(VEC_DATA_TYPE(int, size) a, VEC_DATA_TYPE(int, size) b) \
  {                                                                                       \
    VEC_DATA_TYPE(long, size)                                                             \
    a64 = convert_long##size(a);                                                          \
    VEC_DATA_TYPE(long, size)                                                             \
    b64 = convert_long##size(b);                                                          \
    VEC_DATA_TYPE(long, size)                                                             \
    sum = a64 + b64;                                                                      \
    const VEC_DATA_TYPE(long, size) one = 1;                                              \
    const VEC_DATA_TYPE(long, size) minus_one = -1;                                       \
    VEC_DATA_TYPE(long, size)                                                             \
    sign = select(minus_one, one, sum >= 0);                                              \
    return convert_int##size((sum + sign) / 2);                                           \
  }
Calculates (a+b)/2, rounded to the nearest integer. Equivalent to VRHADD in the ARM NEON instruction set.
Parameters
[in] size Size of vector.
Returns
(a+b)/2, rounded to the nearest integer.
Definition at line 368 of file helpers_asymm.h.
ASYMM_SATURATING_ROUNDING_MULT_BY_POW2
#define ASYMM_SATURATING_ROUNDING_MULT_BY_POW2 (x, exponent, size) asymm_saturating_rounding_mult_by_pow2##size(x, exponent)
Definition at line 459 of file helpers_asymm.h.
ASYMM_SATURATING_ROUNDING_MULT_BY_POW2_IMPL
#define ASYMM_SATURATING_ROUNDING_MULT_BY_POW2_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                                          \
    asymm_saturating_rounding_mult_by_pow2##size(VEC_DATA_TYPE(int, size) x, int exponent) \
  {                                                                                        \
    if (exponent < 0)                                                                      \
    {                                                                                      \
      return ASYMM_ROUNDING_DIVIDE_BY_POW2(x, -exponent, size);                            \
    }                                                                                      \
                                                                                           \
    const VEC_DATA_TYPE(int, size) min = INT_MIN;                                          \
    const VEC_DATA_TYPE(int, size) max = INT_MAX;                                          \
    int threshold = ((1 << (31 - exponent)) - 1);                                          \
    VEC_DATA_TYPE(int, size)                                                               \
    positive_mask = ASYMM_MASK_IF_NON_ZERO(x > threshold, size);                           \
    VEC_DATA_TYPE(int, size)                                                               \
    negative_mask = ASYMM_MASK_IF_NON_ZERO(x < -threshold, size);                          \
    VEC_DATA_TYPE(int, size)                                                               \
    result = x << exponent;                                                                \
    result = ASYMM_SELECT_USING_MASK(positive_mask, max, result, size);                    \
    result = ASYMM_SELECT_USING_MASK(negative_mask, min, result, size);                    \
    return result;                                                                         \
  }
Calculates the product of a integer value by a power of two, with either a positive exponent (equivalent to an arithmetic left shift, saturating) or a negative exponent (equivalent to an arithmetic right shift, rounding to nearest).
Parameters
[in] size Size of vector.
Returns
Arithmetic left or right shift.
Definition at line 338 of file helpers_asymm.h.
ASYMM_SELECT_USING_MASK
#define ASYMM_SELECT_USING_MASK (if_mask, then_val, else_val, size) asymm_select_using_mask##size(if_mask, then_val, else_val)
Definition at line 447 of file helpers_asymm.h.
ASYMM_SELECT_USING_MASK_IMPL
#define ASYMM_SELECT_USING_MASK_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) asymm_select_using_mask##size(VEC_DATA_TYPE(int, size) if_mask,  \
                                                                VEC_DATA_TYPE(int, size) then_val, \
                                                                VEC_DATA_TYPE(int, size) else_val) \
  {                                                                                                \
    return (if_mask & then_val) ^ (~if_mask & else_val);                                           \
  }
Each bit of the result is set to the corresponding bit of either then_val or else_val depending on whether the corresponding bit of if_mask is set. Equivalent to the VBSL instruction in ARM NEON.
Parameters
[in] size Size of vector.
Returns
Result contaning bits from then_val or from else_val depending on corresponding bit in if_mask is set or not.
Definition at line 226 of file helpers_asymm.h.
CONVERT_DOWN_RTE
#define CONVERT_DOWN_RTE (x, type) CONVERT_DOWN_RTE_STR(x, type)
Definition at line 53 of file helpers_asymm.h.
CONVERT_DOWN_RTE_STR
#define CONVERT_DOWN_RTE_STR (x, type) (convert_##type##_rte((x)))
Convert the given vector with round to nearest even rounding mode
Parameters
[in] x The target to be converted
[in] type The target type
Returns
The converted vector
Definition at line 52 of file helpers_asymm.h.
DEQUANTIZE
#define DEQUANTIZE (input, offset, scale, type, size) DEQUANTIZE_STR(input, offset, scale, type, size)
Definition at line 435 of file helpers_asymm.h.
DEQUANTIZE_IMPL
#define DEQUANTIZE_IMPL (type, size)
Value:
  inline VEC_DATA_TYPE(float, size)                                                     \
    dequantize_##type##size(VEC_DATA_TYPE(type, size) input, float offset, float scale) \
  {                                                                                     \
    return (CONVERT(input, VEC_DATA_TYPE(float, size)) - offset) * scale;               \
  }
Dequantize a vector of values to floating-point
Parameters
[in] type Input data type.
[in] size Size of vector.
Returns
dequantized values in floating point
Definition at line 122 of file helpers_asymm.h.
DEQUANTIZE_STR
#define DEQUANTIZE_STR (input, offset, scale, type, size) dequantize_##type##size(input, offset, scale)
Definition at line 433 of file helpers_asymm.h.
EXP_BARREL_SHIFTER
#define EXP_BARREL_SHIFTER (result, exponent, fp_multiplier, k_integer_bits, k_fractional_bits, remainder, size)
Value:
  exp_barrel_shifter##size(result, exponent, fp_multiplier, k_integer_bits, k_fractional_bits, \
                           remainder)
Definition at line 451 of file helpers_asymm.h.
EXP_BARREL_SHIFTER_IMPL
#define EXP_BARREL_SHIFTER_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size) exp_barrel_shifter##size(                                    \
    VEC_DATA_TYPE(int, size) result, int exponent, int fp_multiplier, int k_integer_bits,      \
    int k_fractional_bits, VEC_DATA_TYPE(int, size) remainder)                                 \
  {                                                                                            \
    if (k_integer_bits > exponent)                                                             \
    {                                                                                          \
      const int k_shift_amount = k_integer_bits > exponent ? k_fractional_bits + exponent : 0; \
      return ASYMM_SELECT_USING_MASK(                                                          \
        ASYMM_MASK_IF_NON_ZERO(remainder & (1 << k_shift_amount), size),                       \
        ASYMM_MULT(result, fp_multiplier, size), result, size);                                \
    }                                                                                          \
                                                                                               \
    return result;                                                                             \
  }
Definition at line 264 of file helpers_asymm.h.
MULTIPLY_BY_QUANTIZED_MULTIPLIER
#define MULTIPLY_BY_QUANTIZED_MULTIPLIER (input, qmul, shift, size) multiply_by_quantized_multiplier##size(input, qmul, shift)
Definition at line 474 of file helpers_asymm.h.
MULTIPLY_BY_QUANTIZED_MULTIPLIER_IMPL
#define MULTIPLY_BY_QUANTIZED_MULTIPLIER_IMPL (size)
Value:
  inline VEC_DATA_TYPE(int, size)                                                               \
    multiply_by_quantized_multiplier##size(VEC_DATA_TYPE(int, size) input, int qmul, int shift) \
  {                                                                                             \
    const int left_shift = shift > 0 ? shift : 0;                                               \
    const int right_shift = shift > 0 ? 0 : -shift;                                             \
    return ASYMM_ROUNDING_DIVIDE_BY_POW2(ASYMM_MULT(input * (1 << left_shift), qmul, size),     \
                                         right_shift, size);                                    \
  }
Definition at line 465 of file helpers_asymm.h.
QUANTIZE
#define QUANTIZE (input, offset, scale, type, size) QUANTIZE_STR(input, offset, scale, type, size)
Definition at line 432 of file helpers_asymm.h.
QUANTIZE_IMPL
#define QUANTIZE_IMPL (type, size)
Value:
  inline VEC_DATA_TYPE(type, size)                                                                 \
    quantize_##type##size(VEC_DATA_TYPE(float, size) input, float offset, float scale)             \
  {                                                                                                \
    VEC_DATA_TYPE(float, size)                                                                     \
    out_f32 = input / (VEC_DATA_TYPE(float, size))(scale) + (VEC_DATA_TYPE(float, size))(offset);  \
    VEC_DATA_TYPE(type, size)                                                                      \
    res =                                                                                          \
      CONVERT_SAT(CONVERT_DOWN_RTE(out_f32, VEC_DATA_TYPE(int, size)), VEC_DATA_TYPE(type, size)); \
    return res;                                                                                    \
  }
Quantize a vector of values from floating-point
Parameters
[in] type Output data type.
[in] size Size of vector.
Returns
quantized values
Definition at line 103 of file helpers_asymm.h.
QUANTIZE_STR
#define QUANTIZE_STR (input, offset, scale, type, size) quantize_##type##size(input, offset, scale)
Definition at line 431 of file helpers_asymm.h.
Function Documentation
dequantize_qasymm8()
float dequantize_qasymm8 (uchar input, float offset, float scale) inline
Dequantize a scalar value from 8-bit asymmetric to floating-point
Parameters
[in] input Input value to quantize
[in] offset Quantization offset
[in] scale Quantization scale
Returns
quantized value
Definition at line 78 of file helpers_asymm.h.
{
  return ((float)input - offset) * scale;
}
References offset().
dequantize_qasymm8_signed()
float dequantize_qasymm8_signed (char input, float offset, float scale) inline
Dequantize a scalar value from signed 8-bit asymmetric to floating-point
Parameters
[in] input Input value to quantize
[in] offset Quantization offset
[in] scale Quantization scale
Returns
quantized value
Definition at line 91 of file helpers_asymm.h.
{
  return ((float)input - offset) * scale;
}
References offset().
quantize_qasymm8()
uchar quantize_qasymm8 (float input, float offset, float scale) inline
Quantize a floating-point scalar value to 8-bit asymmetric
Parameters
[in] input Input value to quantize
[in] offset Quantization offset
[in] scale Quantization scale
Returns
quantized value
Definition at line 63 of file helpers_asymm.h.
{
  float out_f32 = input / scale + offset;
  uchar res_u8 = CONVERT_SAT(CONVERT_DOWN_RTE(out_f32, int), uchar);
  return res_u8;
}
References CONVERT_DOWN_RTE, CONVERT_SAT, and offset().