ONE - On-device Neural Engine: runtime/onert/core/src/library_info.cc File Reference
library_info.cc File Reference
Variables
volatile const char info [] = "library information : runtime=onert"
Variable Documentation
info
volatile const char info[] (void) = "library information : runtime=onert"
Definition at line 17 of file library_info.cc.
Referenced by onert::interp::ExecEnv::allocateAndShareIfNeeded(), onert::interp::ExecEnv::allocateIfNeeded(), nnfw_session::apply_tensorinfo(), onert::backend::acl_common::asTensorInfo(), enco::SubnetStructBuilder::build(), onert::backend::acl_common::AclTensorManager< T_ITensor, T_Tensor, T_SubTensor >::buildTensor(), onert::backend::acl_common::AclMemoryManager< T_ITensor, T_Tensor, T_SubTensor >::buildTensor(), onert::backend::gpu_cl::MemoryManager::buildTensor(), onert::backend::gpu_cl::TensorManager::buildTensor(), arm_compute::misc::shape_calculator::compute_transposeconv_upsampled_shape(), arm_compute::CLPadLayerEx::configure(), arm_compute::CLDirectTransposeConvLayer::configure(), arm_compute::NEReduceSum::configure(), arm_compute::NEReduceOperation::configure(), arm_compute::NETransposeConvLayer::configure(), enco::CppCode::dump(), onert::exec::Executors::execute(), exo::circle_detail::exportOpDefinedTensor(), exo::tflite_detail::exportOpDefinedTensor(), enco::generate_global_data(), nnfw_session::input_tensorinfo(), onert::backend::acl_common::kernelGenPool2D(), luci::layer_info_map(), nnfw::loadFunction(), main(), nnfw_register_custom_op_info(), exo::ProgressReporter::notify(), luci::ProgressReporter::notify(), luci::ModuleProgressReporter::notify(), moco::tf::ProgressReporter::notify(), logo::PhaseRunnerMixinObservable::notifyPassBegin(), logo::PhaseRunnerMixinObservable::notifyPassEnd(), logo::PhaseRunnerMixinObservable::notifyPhaseBegin(), logo::PhaseRunnerMixinObservable::notifyPhaseEnd(), nnfw_session::output_tensorinfo(), onert::backend::basic::planTensors(), luci::CircleQuantizer::quantize(), onert::backend::acl_common::AclTensorBuilder< T_ITensor, T_Tensor, T_SubTensor >::registerTensorInfo(), onert::backend::basic::TensorBuilder::registerTensorInfo(), onert::backend::builtin::TensorBuilder::registerTensorInfo(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::registerTensorInfo(), onert::backend::gpu_cl::BackendContext::registerTensorInfo(), onert::backend::gpu_cl::TensorBuilder::registerTensorInfo(), arm_compute::NECastBoolKernel::run(), arm_compute::NEEmbeddingLookupKernel::run(), arm_compute::NEGatherKernelEx::run(), arm_compute::NEGEMMMatrixAccumulateBiasesKernel::run(), arm_compute::NEHashtableLookupKernel::run(), arm_compute::NEInstanceNormalizationLayerKernelEx::run(), arm_compute::NEMultiplyScaleFactorKernel::run(), arm_compute::NEOneHotKernel::run(), arm_compute::NEQuantizationSymmetricKernel::run(), onert::backend::trix::setDataInfo(), onert::exec::Execution::setInput(), onert::exec::Execution::setOutput(), arm_compute::transposeconv_output_dimensions(), arm_compute::CLPadLayerEx::validate(), arm_compute::NETransposeConvLayer::validate(), and arm_compute::CLDirectTransposeConvLayer::validate().