ONE - On-device Neural Engine: compiler/luci/pass/src/FuseInstanceNormPass.cpp File Reference
FuseInstanceNormPass.cpp File Reference
#include "luci/Pass/FuseInstanceNormPass.h"
#include "helpers/NodeFiller.h"
#include "FuseInstanceNormPassInternal.h"
#include <luci/IR/CircleNodes.h>
#include <luci/Profile/CircleNodeOrigin.h>
#include <luci/Service/CircleNodeClone.h>
#include <cassert>
#include <set>
Namespaces
namespace luci
Macros
#define CHECK_OR_FALSE(condition)
Functions
bool is_1D_with_dummy_dim (luci::CircleConst *node, uint32_t depth)
bool is_instance_mean_v1 (luci::CircleMean *mean)
bool is_1D_float32_const (const luci::CircleConst *node, uint32_t channel_size)
Macro Definition Documentation
CHECK_OR_FALSE
#define CHECK_OR_FALSE (condition)
Value:
  if (not(condition))             \
    return false;
Definition at line 371 of file FuseInstanceNormPass.cpp.
{
  add_as_variance = dynamic_cast<luci::CircleAdd *>(rsqrt->x());
  CHECK_OR_FALSE(add_as_variance);
  CHECK_OR_FALSE(
    luci::fill(&mean_as_variance, &const_as_epsilon).with_commutative_args_of(add_as_variance));
  CHECK_OR_FALSE(const_as_epsilon->dtype() == loco::DataType::FLOAT32);
  // TODO Support regarding broadcast
  CHECK_OR_FALSE(const_as_epsilon->size<loco::DataType::FLOAT32>() == 1);
  CHECK_OR_FALSE(is_instance_mean_v1(mean_as_variance));
  sqdiff = dynamic_cast<luci::CircleSquaredDifference *>(mean_as_variance->input());
  CHECK_OR_FALSE(sqdiff);
  loco::Node *ifm_should_be = nullptr;
  CHECK_OR_FALSE(luci::fill(&ifm_should_be, &mean_of_ifm).with_commutative_args_of(sqdiff));
  CHECK_OR_FALSE(ifm == ifm_should_be);
  CHECK_OR_FALSE(is_instance_mean_v1(mean_of_ifm));
  CHECK_OR_FALSE(ifm == mean_of_ifm->input());
  const_as_beta = dynamic_cast<luci::CircleConst *>(sub->x());
  CHECK_OR_FALSE(const_as_beta);
  CHECK_OR_FALSE(is_1D_with_dummy_dim(const_as_beta, ifm_channel_depth));
  return true;
}
bool InstanceNormPattern::condition_common_3_4()
{
  // check left sub
  ifm = sub->x();
  CHECK_OR_FALSE(ifm);
  luci::CircleNode *ifm_node = loco::must_cast<luci::CircleNode *>(ifm);
  CHECK_OR_FALSE(ifm_node->rank() == 4);
  CHECK_OR_FALSE(ifm_node->dim(3).known());
  mean_of_ifm = dynamic_cast<luci::CircleMean *>(sub->y());
  CHECK_OR_FALSE(mean_of_ifm);
  CHECK_OR_FALSE(ifm == mean_of_ifm->input());
  // continue search from add_as_variance
  CHECK_OR_FALSE(luci::fill(&sqrt, &const_as_epsilon).with_commutative_args_of(add_as_variance));
  CHECK_OR_FALSE(const_as_epsilon->dtype() == loco::DataType::FLOAT32);
  // TODO Support regarding broadcast
  CHECK_OR_FALSE(const_as_epsilon->size<loco::DataType::FLOAT32>() == 1);
  mean_as_variance = dynamic_cast<luci::CircleMean *>(sqrt->x());
  CHECK_OR_FALSE(mean_as_variance);
  square = dynamic_cast<luci::CircleSquare *>(mean_as_variance->input());
  CHECK_OR_FALSE(square);
  sub_2 = dynamic_cast<luci::CircleSub *>(square->x());
  CHECK_OR_FALSE(sub_2);
  CHECK_OR_FALSE(ifm == sub_2->x());
  mean_of_ifm_2 = dynamic_cast<luci::CircleMean *>(sub_2->y());
  CHECK_OR_FALSE(mean_of_ifm_2);
  CHECK_OR_FALSE(ifm == mean_of_ifm_2->input());
  loco::Node *ifm_should_be = nullptr;
  luci::CircleMean *mean_of_ifm_2_should_be = nullptr;
  CHECK_OR_FALSE(
    luci::fill(&ifm_should_be, &mean_of_ifm_2_should_be).with_commutative_args_of(sub_2));
  CHECK_OR_FALSE(ifm == ifm_should_be);
  CHECK_OR_FALSE(mean_of_ifm_2 == mean_of_ifm_2_should_be);
  return true;
}
template <> bool InstanceNormPattern::match<InstanceNormPattern::PatternVersion::Version_1>()
{
  CHECK_OR_FALSE(luci::fill(&mul_as_scaled_ifm, &sub).with_commutative_args_of(add_as_terminal));
  CHECK_OR_FALSE(luci::fill(&ifm, &mul_gamma).with_commutative_args_of(mul_as_scaled_ifm));
  auto ifm_circle = loco::must_cast<luci::CircleNode *>(ifm);
  CHECK_OR_FALSE(ifm_circle->shape_status() == luci::ShapeStatus::VALID);
  CHECK_OR_FALSE(ifm_circle->rank() == 4);
  CHECK_OR_FALSE(ifm_circle->dim(3).known());
  uint32_t ifm_channel_depth = ifm_circle->dim(3).value();
  CHECK_OR_FALSE(luci::fill(&rsqrt, &const_as_gamma).with_commutative_args_of(mul_gamma));
  CHECK_OR_FALSE(is_1D_with_dummy_dim(const_as_gamma, ifm_channel_depth));
  CHECK_OR_FALSE(condition_common_1_5(ifm_channel_depth));
  luci::CircleMul *mul_gamma_should_be = nullptr;
  luci::CircleMean *mean_of_ifm_should_be = nullptr;
  mul_as_scaled_mean = dynamic_cast<luci::CircleMul *>(sub->y());
  CHECK_OR_FALSE(mul_as_scaled_mean);
  CHECK_OR_FALSE(luci::fill(&mul_gamma_should_be, &mean_of_ifm_should_be)
                   .with_commutative_args_of(mul_as_scaled_mean));
  CHECK_OR_FALSE(mul_gamma == mul_gamma_should_be);
  CHECK_OR_FALSE(mean_of_ifm == mean_of_ifm_should_be);
  _matched = true;
  return true;
}
template <> bool InstanceNormPattern::match<InstanceNormPattern::PatternVersion::Version_2>()
{
  CHECK_OR_FALSE(luci::fill(&mul_gamma, &const_as_beta).with_commutative_args_of(add_as_terminal));
  CHECK_OR_FALSE(luci::fill(&div, &const_as_gamma).with_commutative_args_of(mul_gamma));
  sub = dynamic_cast<luci::CircleSub *>(div->x());
  CHECK_OR_FALSE(sub);
  ifm = sub->x();
  CHECK_OR_FALSE(ifm);
  luci::CircleNode *ifm_node = loco::must_cast<luci::CircleNode *>(ifm);
  CHECK_OR_FALSE(ifm_node->rank() == 4);
  CHECK_OR_FALSE(ifm_node->dim(3).known());
  uint32_t ifm_channel_depth = ifm_node->dim(3).value();
  mean_of_ifm = dynamic_cast<luci::CircleMean *>(sub->y());
  CHECK_OR_FALSE(mean_of_ifm);
  CHECK_OR_FALSE(ifm == mean_of_ifm->input());
  pow = dynamic_cast<luci::CirclePow *>(div->y());
  CHECK_OR_FALSE(pow);
  add_as_variance = dynamic_cast<luci::CircleAdd *>(pow->x());
  CHECK_OR_FALSE(add_as_variance);
  luci::CircleConst *zero_point_five = dynamic_cast<luci::CircleConst *>(pow->y());
  CHECK_OR_FALSE(zero_point_five);
  CHECK_OR_FALSE(zero_point_five->dtype() == loco::DataType::FLOAT32);
  // TODO Support regarding broadcast
  CHECK_OR_FALSE(zero_point_five->size<loco::DataType::FLOAT32>() == 1);
  CHECK_OR_FALSE(zero_point_five->at<loco::DataType::FLOAT32>(0) == 0.5);
  CHECK_OR_FALSE(
    luci::fill(&mean_as_variance, &const_as_epsilon).with_commutative_args_of(add_as_variance));
  CHECK_OR_FALSE(const_as_epsilon->dtype() == loco::DataType::FLOAT32);
  // TODO Support regarding broadcast
  CHECK_OR_FALSE(const_as_epsilon->size<loco::DataType::FLOAT32>() == 1);
  CHECK_OR_FALSE(is_instance_mean_v1(mean_as_variance));
  sqdiff = dynamic_cast<luci::CircleSquaredDifference *>(mean_as_variance->input());
  CHECK_OR_FALSE(sqdiff);
  loco::Node *ifm_should_be = nullptr;
  luci::CircleMean *mean_of_ifm_should_be = nullptr;
  CHECK_OR_FALSE(
    luci::fill(&ifm_should_be, &mean_of_ifm_should_be).with_commutative_args_of(sqdiff));
  CHECK_OR_FALSE(ifm == ifm_should_be);
  CHECK_OR_FALSE(mean_of_ifm == mean_of_ifm_should_be);
  // Check for channel size
  CHECK_OR_FALSE(is_1D_float32_const(const_as_gamma, ifm_channel_depth));
  CHECK_OR_FALSE(is_1D_float32_const(const_as_beta, ifm_channel_depth));
  _matched = true;
  return true;
}
template <> bool InstanceNormPattern::match<InstanceNormPattern::PatternVersion::Version_3>()
{
  CHECK_OR_FALSE(luci::fill(&mul_gamma, &const_as_beta).with_commutative_args_of(add_as_terminal));
  CHECK_OR_FALSE(luci::fill(&div, &const_as_gamma).with_commutative_args_of(mul_gamma));
  CHECK_OR_FALSE(luci::fill(&sub, &add_as_variance).with_commutative_args_of(div));
  CHECK_OR_FALSE(condition_common_3_4());
  _matched = true;
  return true;
}
luci::CircleConst *make_const_one(loco::Graph *graph, float value)
{
  auto const_one = graph->nodes()->create<luci::CircleConst>();
  const_one->dtype(loco::DataType::FLOAT32);
  const_one->rank(1);
  const_one->size<loco::DataType::FLOAT32>(1);
  const_one->at<loco::DataType::FLOAT32>(0) = value;
  return const_one;
}
template <> bool InstanceNormPattern::match<InstanceNormPattern::PatternVersion::Version_4>()
{
  CHECK_OR_FALSE(div);
  CHECK_OR_FALSE(luci::fill(&sub, &add_as_variance).with_commutative_args_of(div));
  CHECK_OR_FALSE(condition_common_3_4());
  assert(const_as_gamma == nullptr);
  assert(const_as_beta == nullptr);
  assert(mul_gamma == nullptr);
  assert(add_as_terminal == nullptr);
  // create 1.0 gamma and 0.0 beta
  auto graph = div->graph();
  const_as_gamma = make_const_one(graph, 1.0f);
  const_as_beta = make_const_one(graph, 0.0f);
  const_as_gamma->name(div->name() + "/gamma");
  const_as_beta->name(div->name() + "/beta");
  _matched = true;
  return true;
}
template <> bool InstanceNormPattern::match<InstanceNormPattern::PatternVersion::Version_5>()
{
  CHECK_OR_FALSE(luci::fill(&mul_as_scaled_ifm, &sub).with_commutative_args_of(add_as_terminal));
  CHECK_OR_FALSE(luci::fill(&ifm, &rsqrt).with_commutative_args_of(mul_as_scaled_ifm));
  auto ifm_circle = loco::must_cast<luci::CircleNode *>(ifm);
  CHECK_OR_FALSE(ifm_circle->shape_status() == luci::ShapeStatus::VALID);
  CHECK_OR_FALSE(ifm_circle->rank() == 4);
  CHECK_OR_FALSE(ifm_circle->dim(3).known());
  uint32_t ifm_channel_depth = ifm_circle->dim(3).value();
  CHECK_OR_FALSE(condition_common_1_5(ifm_channel_depth));
  luci::CircleRsqrt *rsqrt_should_be = nullptr;
  luci::CircleMean *mean_of_ifm_should_be = nullptr;
  mul_as_scaled_mean = dynamic_cast<luci::CircleMul *>(sub->y());
  CHECK_OR_FALSE(mul_as_scaled_mean);
  CHECK_OR_FALSE(luci::fill(&rsqrt_should_be, &mean_of_ifm_should_be)
                   .with_commutative_args_of(mul_as_scaled_mean));
  CHECK_OR_FALSE(rsqrt == rsqrt_should_be);
  CHECK_OR_FALSE(mean_of_ifm == mean_of_ifm_should_be);
  // mul_gamma is absent
  // const_as_gamma assume to be 1.0
  auto graph = add_as_terminal->graph();
  const_as_gamma = make_const_one(graph, 1.0f);
  const_as_gamma->name(add_as_terminal->name() + "/gamma");
  _matched = true;
  return true;
}
bool InstanceNormPattern::matched()
{
  if (_matched)
    return true;
  // Check order is DFS
  switch (_pv)
  {
    case PatternVersion::Version_1:
      return match<PatternVersion::Version_1>();
    case PatternVersion::Version_2:
      return match<PatternVersion::Version_2>();
    case PatternVersion::Version_3:
      return match<PatternVersion::Version_3>();
    case PatternVersion::Version_4:
      return match<PatternVersion::Version_4>();
    case PatternVersion::Version_5:
      return match<PatternVersion::Version_5>();
    default:
      break;
  }
  throw std::runtime_error("Invalid InstanceNorm PatternVersion.");
}
#undef CHECK_OR_FALSE
class FuseInstanceNorm final
{
public:
  FuseInstanceNorm(const InstanceNormPattern &p) : _p(p) {}
public:
  void apply(void);
private:
  template <InstanceNormPattern::PatternVersion> void apply(void);
private:
  void reshape_gamma_beta(void);
  luci::CircleInstanceNorm *create_inst_norm(loco::Graph *graph);
private:
  const InstanceNormPattern &_p;
};
void FuseInstanceNorm::reshape_gamma_beta()
{
  // Version 1 and 3 need to reshape
  {
    _p.const_as_gamma->rank(1);
    _p.const_as_gamma->dim(0).set(_p.const_as_gamma->size<loco::DataType::FLOAT32>());
    _p.const_as_beta->rank(1);
    _p.const_as_beta->dim(0).set(_p.const_as_beta->size<loco::DataType::FLOAT32>());
    _p.const_as_gamma->shape_status(luci::ShapeStatus::UNDEFINED);
    _p.const_as_beta->shape_status(luci::ShapeStatus::UNDEFINED);
  }
}
luci::CircleInstanceNorm *FuseInstanceNorm::create_inst_norm(loco::Graph *graph)
{
  // Make Instance Norm to replace
  auto instance_norm = graph->nodes()->create<luci::CircleInstanceNorm>();
  instance_norm->input(_p.ifm);
  instance_norm->gamma(_p.const_as_gamma);
  instance_norm->beta(_p.const_as_beta);
  float epsilon = _p.const_as_epsilon->at<loco::DataType::FLOAT32>(0);
  instance_norm->epsilon(epsilon);
  if (_p.add_as_terminal != nullptr)
  {
    instance_norm->fusedActivationFunction(_p.add_as_terminal->fusedActivationFunction());
    // NOTE unique name should be assigned in export
    instance_norm->name("FusedInstanceNorm/" + _p.add_as_terminal->name());
  }
  else
  {
    // VERSION_4
    assert(_p.div != nullptr);
    instance_norm->fusedActivationFunction(_p.div->fusedActivationFunction());
    instance_norm->name("FusedInstanceNorm/" + _p.div->name());
  }
  return instance_norm;
}
template <> void FuseInstanceNorm::apply<InstanceNormPattern::PatternVersion::Version_1>()
{
  auto graph = _p.add_as_terminal->graph();
  reshape_gamma_beta();
  auto instance_norm = create_inst_norm(graph);
  // set origin
  std::vector<std::shared_ptr<luci::CircleNodeOrigin>> origin_vec{
    luci::get_origin(_p.mean_of_ifm),
    luci::get_origin(_p.sqdiff),
    luci::get_origin(_p.mean_as_variance),
    luci::get_origin(_p.add_as_variance),
    luci::get_origin(_p.rsqrt),
    luci::get_origin(_p.mul_gamma),
    luci::get_origin(_p.mul_as_scaled_ifm),
    luci::get_origin(_p.mul_as_scaled_mean),
    luci::get_origin(_p.sub),
    luci::get_origin(_p.add_as_terminal)};
  luci::add_origin(instance_norm, luci::composite_origin(origin_vec));
  replace(_p.add_as_terminal).with(instance_norm);
}
template <> void FuseInstanceNorm::apply<InstanceNormPattern::PatternVersion::Version_2>()
{
  auto graph = _p.add_as_terminal->graph();
  auto instance_norm = create_inst_norm(graph);
  // set origin
  std::vector<std::shared_ptr<luci::CircleNodeOrigin>> origin_vec{
    luci::get_origin(_p.mean_of_ifm),
    luci::get_origin(_p.sqdiff),
    luci::get_origin(_p.mean_as_variance),
    luci::get_origin(_p.add_as_variance),
    luci::get_origin(_p.pow),
    luci::get_origin(_p.sub),
    luci::get_origin(_p.div),
    luci::get_origin(_p.mul_gamma),
    luci::get_origin(_p.add_as_terminal)};
  luci::add_origin(instance_norm, luci::composite_origin(origin_vec));
  replace(_p.add_as_terminal).with(instance_norm);
}
template <> void FuseInstanceNorm::apply<InstanceNormPattern::PatternVersion::Version_3>()
{
  auto graph = _p.add_as_terminal->graph();
  reshape_gamma_beta();
  auto instance_norm = create_inst_norm(graph);
  // set origin
  std::vector<std::shared_ptr<luci::CircleNodeOrigin>> origin_vec{
    luci::get_origin(_p.mean_of_ifm),
    luci::get_origin(_p.sub),
    luci::get_origin(_p.mean_of_ifm_2),
    luci::get_origin(_p.sub_2),
    luci::get_origin(_p.square),
    luci::get_origin(_p.mean_as_variance),
    luci::get_origin(_p.sqrt),
    luci::get_origin(_p.add_as_variance),
    luci::get_origin(_p.div),
    luci::get_origin(_p.mul_gamma),
    luci::get_origin(_p.add_as_terminal)};
  luci::add_origin(instance_norm, luci::composite_origin(origin_vec));
  replace(_p.add_as_terminal).with(instance_norm);
}
template <> void FuseInstanceNorm::apply<InstanceNormPattern::PatternVersion::Version_4>()
{
  auto graph = _p.div->graph();
  auto instance_norm = create_inst_norm(graph);
  // set origin
  std::vector<std::shared_ptr<luci::CircleNodeOrigin>> origin_vec{
    luci::get_origin(_p.mean_of_ifm),
    luci::get_origin(_p.sub),
    luci::get_origin(_p.mean_of_ifm_2),
    luci::get_origin(_p.sub_2),
    luci::get_origin(_p.square),
    luci::get_origin(_p.mean_as_variance),
    luci::get_origin(_p.sqrt),
    luci::get_origin(_p.add_as_variance),
    luci::get_origin(_p.div)};
  luci::add_origin(instance_norm, luci::composite_origin(origin_vec));
  replace(_p.div).with(instance_norm);
}
template <> void FuseInstanceNorm::apply<InstanceNormPattern::PatternVersion::Version_5>()
{
  auto graph = _p.add_as_terminal->graph();
  reshape_gamma_beta();
  auto instance_norm = create_inst_norm(graph);
  // set origin
  std::vector<std::shared_ptr<luci::CircleNodeOrigin>> origin_vec{
    luci::get_origin(_p.mean_of_ifm),
    luci::get_origin(_p.sqdiff),
    luci::get_origin(_p.mean_as_variance),
    luci::get_origin(_p.add_as_variance),
    luci::get_origin(_p.rsqrt),
    luci::get_origin(_p.mul_as_scaled_ifm),
    luci::get_origin(_p.mul_as_scaled_mean),
    luci::get_origin(_p.sub),
    luci::get_origin(_p.add_as_terminal)};
  luci::add_origin(instance_norm, luci::composite_origin(origin_vec));
  replace(_p.add_as_terminal).with(instance_norm);
}
void FuseInstanceNorm::apply()
{
  assert(_p.matched());
  switch (_p.version())
  {
    case InstanceNormPattern::PatternVersion::Version_1:
      apply<InstanceNormPattern::PatternVersion::Version_1>();
      break;
    case InstanceNormPattern::PatternVersion::Version_2:
      apply<InstanceNormPattern::PatternVersion::Version_2>();
      break;
    case InstanceNormPattern::PatternVersion::Version_3:
      apply<InstanceNormPattern::PatternVersion::Version_3>();
      break;
    case InstanceNormPattern::PatternVersion::Version_4:
      apply<InstanceNormPattern::PatternVersion::Version_4>();
      break;
    case InstanceNormPattern::PatternVersion::Version_5:
      apply<InstanceNormPattern::PatternVersion::Version_5>();
      break;
    default:
      break;
  }
}
} // namespace
namespace
{
class PostFusion final
{
public:
  PostFusion(luci::CircleInstanceNorm *inst_norm) : _inst_norm(inst_norm) {}
private:
  uint32_t input_channel(void);
  luci::CircleConst *match_const_channel(luci::CircleConst *, uint32_t);
  bool match_const_gamma_channel(void);
  bool match_const_beta_channel(void);
public:
  bool process(void);
private:
  luci::CircleInstanceNorm *_inst_norm = nullptr;
};
uint32_t PostFusion::input_channel(void)
{
  auto input = dynamic_cast<luci::CircleNode *>(_inst_norm->input());
  if (input == nullptr)
    return 0;
  if (input->shape_status() != luci::ShapeStatus::VALID)
    return 0;
  auto input_rank = input->rank();
  if (input_rank < 1)
    return 0;
  // assume channel-last
  return input->dim(input_rank - 1).value();
}
luci::CircleConst *PostFusion::match_const_channel(luci::CircleConst *input_const, uint32_t C)
{
  luci::CircleConst *new_input_const = nullptr;
  auto input_chn = input_const->dim(0).value();
  if (input_chn == 1 && input_chn != C)
  {
    float value = input_const->at<loco::DataType::FLOAT32>(0);
    auto clone = luci::clone_node(input_const, input_const->graph());
    new_input_const = loco::must_cast<luci::CircleConst *>(clone);
    new_input_const->rank(1);
    new_input_const->dim(0).set(C);
    new_input_const->size<loco::DataType::FLOAT32>(C);
    for (uint32_t c = 0; c < C; ++c)
      new_input_const->at<loco::DataType::FLOAT32>(c) = value;
  }
  return new_input_const;
}
bool PostFusion::match_const_gamma_channel(void)
{
  auto const_as_gamma = dynamic_cast<luci::CircleConst *>(_inst_norm->gamma());
  if (const_as_gamma == nullptr)
    return false;
  auto C = input_channel();
  if (C == 0)
    return false;
  auto new_const_as_gamma = match_const_channel(const_as_gamma, C);
  if (new_const_as_gamma == nullptr)
    return false;
  _inst_norm->gamma(new_const_as_gamma);
  return true;
}
bool PostFusion::match_const_beta_channel(void)
{
  auto const_as_beta = dynamic_cast<luci::CircleConst *>(_inst_norm->beta());
  if (const_as_beta == nullptr)
    return false;
  auto C = input_channel();
  if (C == 0)
    return false;
  auto new_const_as_beta = match_const_channel(const_as_beta, C);
  if (new_const_as_beta == nullptr)
    return false;
  _inst_norm->beta(new_const_as_beta);
  return true;
}
bool PostFusion::process(void)
{
  bool changed = false;
  if (match_const_gamma_channel())
    changed = true;
  if (match_const_beta_channel())
    changed = true;
  return changed;
}
} // namespace
namespace
{
bool is_add_input_mul_const(luci::CircleAdd *add)
{
  luci::CircleMul *p_mul = nullptr;
  luci::CircleConst *p_const = nullptr;
  return luci::fill(&p_mul, &p_const).with_commutative_args_of(add);
}
bool fuse_instance_norm(luci::CircleAdd *add)
{
  InstanceNormPattern::PatternVersion pv = InstanceNormPattern::PatternVersion::Version_1;
  if (is_add_input_mul_const(add))
    pv = InstanceNormPattern::PatternVersion::Version_2;
  InstanceNormPattern pattern(add, pv);
  if (pattern.matched())
  {
    FuseInstanceNorm fuse(pattern);
    fuse.apply();
    return true;
  }
  if (pv == InstanceNormPattern::PatternVersion::Version_1)
  {
    // if Version_1 failed, try with Version_5
    pv = InstanceNormPattern::PatternVersion::Version_5;
    InstanceNormPattern pattern(add, pv);
    if (pattern.matched())
    {
      FuseInstanceNorm fuse(pattern);
      fuse.apply();
      return true;
    }
  }
  else if (pv == InstanceNormPattern::PatternVersion::Version_2)
  {
    // if Version_2 failed, try with Version_3
    pv = InstanceNormPattern::PatternVersion::Version_3;
    InstanceNormPattern pattern(add, pv);
    if (pattern.matched())
    {
      FuseInstanceNorm fuse(pattern);
      fuse.apply();
      return true;
    }
  }
  return false;
}
bool fuse_instance_norm(luci::CircleDiv *div)
{
  InstanceNormPattern::PatternVersion pv = InstanceNormPattern::PatternVersion::Version_4;
  InstanceNormPattern pattern(div, pv);
  if (pattern.matched())
  {
    FuseInstanceNorm fuse(pattern);
    fuse.apply();
    return true;
  }
  return false;
}
bool post_fusion(luci::CircleInstanceNorm *inst_norm)
{
  PostFusion postfusion(inst_norm);
  return postfusion.process();
}
} // namespace
namespace luci
{
bool FuseInstanceNormPass::run(loco::Graph *g)
{
  bool changed = false;
  // Check Version_1, Version_2, Version_3, Version_5
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto add = dynamic_cast<luci::CircleAdd *>(node);
    if (not add)
      continue;
    if (fuse_instance_norm(add))
      changed = true;
  }
  // Check Version_4(from DIV) if MUL-ADD pattern is not found
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto div = dynamic_cast<luci::CircleDiv *>(node);
    if (not div)
      continue;
    if (fuse_instance_norm(div))
      changed = true;
  }
  // Post processing of FuseInstanceNorm
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto inst_norm = dynamic_cast<luci::CircleInstanceNorm *>(node);
    if (not inst_norm)
      continue;
    if (post_fusion(inst_norm))
      changed = true;
  }
  return changed;
}
} // namespace luci
Function Documentation
is_1D_float32_const()
bool is_1D_float32_const (const luci::CircleConst * node, uint32_t channel_size)
Returns
true When node has the shape of 1D channel_size
Definition at line 89 of file FuseInstanceNormPass.cpp.
{
  if (node->rank() != 1)
    return false;
  if (node->dim(0).value() != channel_size)
    return false;
  if (node->dtype() != loco::DataType::FLOAT32)
    return false;
  if (node->size<loco::DataType::FLOAT32>() != channel_size)
    return false;
  return true;
}
References luci::CircleConst::size().
is_1D_with_dummy_dim()
bool is_1D_with_dummy_dim (luci::CircleConst * node, uint32_t depth)
Returns
true When node has shape of '1 x .. x 1 x depth'
Definition at line 32 of file FuseInstanceNormPass.cpp.
{
  auto rank = node->rank();
  uint32_t axis;
  for (axis = 0; axis < rank - 1; ++axis)
  {
    if (node->dim(axis).value() != 1)
      return false;
  }
  return node->dim(axis).value() == depth;
}
is_instance_mean_v1()
bool is_instance_mean_v1 (luci::CircleMean * mean)
Definition at line 44 of file FuseInstanceNormPass.cpp.
{
  //
  // CHECK 1) input is rank 4
  //
  auto input = loco::must_cast<luci::CircleNode *>(mean->input());
  if (input->shape_status() != luci::ShapeStatus::VALID)
    return false;
  if (input->rank() != 4)
    return false;
  //
  // CHECK 2) 'reduction indices' is CircleConst of value [1,2], that is HW of NHWC
  //
  // TODO Support equivalent case, like [-3,-2]
  // TODO Support non-Const case?
  // TODO What if input is NCHW format in Circle?
  auto red_indices = dynamic_cast<luci::CircleConst *>(mean->reduction_indices());
  if (not red_indices)
    return false;
  if (red_indices->rank() != 1)
    return false;
  std::set<int32_t> red_indices_set;
  {
    // TODO Currently only support S32, support other types
    assert(red_indices->dtype() == loco::DataType::S32);
    for (uint32_t i = 0; i < red_indices->dim(0).value(); ++i)
      red_indices_set.insert(red_indices->at<loco::DataType::S32>(i));
  }
  if (red_indices_set.size() != 2)
    return false;
  if (red_indices_set.find(1) == red_indices_set.end())
    return false;
  if (red_indices_set.find(2) == red_indices_set.end())
    return false;
  //
  // CHECK 3) keep_dims == true (?)
  //
  // We only have case of 'keep_dims == true' so far, but it might be okay with 'keep_dims == false'
  // TODO Check this fact, and if true, return true regardless of keep_dims
  return mean->keep_dims();
}
References luci::CircleMean::input(), luci::CircleMean::keep_dims(), luci::CircleMean::reduction_indices(), and luci::VALID.