ONE - On-device Neural Engine: runtime/onert/sample/minimal/src/minimal.cc File Reference
minimal.cc File Reference
#include "nnfw.h"
#include <vector>
#include <iostream>
Functions
uint64_t num_elems (const nnfw_tensorinfo *ti)
int main (const int argc, char **argv)
Function Documentation
main()
int main (const int argc, char ** argv)
Definition at line 31 of file minimal.cc.
{
  nnfw_session *session = nullptr;
  nnfw_create_session(&session);
  // Loading nnpackage
  nnfw_load_model_from_file(session, argv[1]);
  // Use acl_neon backend for CONV_2D and acl_cl for otherwise.
  // Note that defalut backend is acl_cl
  nnfw_set_op_backend(session, "CONV_2D", "acl_neon");
  // Compile model
  nnfw_prepare(session);
  // Prepare input. Here we just allocate dummy input arrays.
  std::vector<float> input;
  nnfw_tensorinfo ti;
  nnfw_input_tensorinfo(session, 0, &ti); // get first input's info
  uint32_t input_elements = num_elems(&ti);
  input.resize(input_elements);
  // TODO: Please add initialization for your input.
  nnfw_set_input(session, 0, ti.dtype, input.data(), sizeof(float) * input_elements);
  // Prepare output
  std::vector<float> output;
  nnfw_output_tensorinfo(session, 0, &ti); // get first output's info
  uint32_t output_elements = num_elems(&ti);
  output.resize(output_elements);
  nnfw_set_output(session, 0, ti.dtype, output.data(), sizeof(float) * output_elements);
  // Do inference
  nnfw_run(session);
  // TODO: Please print or compare the output value in your way.
  nnfw_close_session(session);
  std::cout << "nnpackage " << argv[1] << " runs successfully." << std::endl;
  return 0;
}
References nnfw_tensorinfo::dtype, nnfw_close_session(), nnfw_create_session(), nnfw_input_tensorinfo(), nnfw_load_model_from_file(), nnfw_output_tensorinfo(), nnfw_prepare(), nnfw_run(), nnfw_set_input(), nnfw_set_op_backend(), nnfw_set_output(), and num_elems().
num_elems()
uint64_t num_elems (const nnfw_tensorinfo * ti)
Definition at line 21 of file minimal.cc.
{
  uint64_t n = 1;
  for (uint32_t i = 0; i < ti->rank; ++i)
  {
    n *= ti->dims[i];
  }
  return n;
}
References nnfw_tensorinfo::dims, and nnfw_tensorinfo::rank.
Referenced by circle_eval_diff::MAEPrinter::init(), circle_eval_diff::MSEPrinter::init(), circle_eval_diff::MAPEPrinter::init(), circle_eval_diff::TopKMatchPrinter::init(), main(), and dalgona::Dalgona::runAnalysisWithRandomInput().