ONE - On-device Neural Engine: compiler/mir/unittests/ShapeInference.cpp File Reference
ShapeInference.cpp File Reference
#include "mir/Graph.h"
#include "mir/ops/AddOp.h"
#include "mir/ops/ReshapeOp.h"
#include "mir/ops/ResizeOp.h"
#include "mir/ops/SqueezeOp.h"
#include "mir/ops/ReduceMeanOp.h"
#include "mir/Shape.h"
#include <vector>
#include "gtest/gtest.h"
Functions
TEST (ShapeInferenceTest, BidirectionalBroadcast)
TEST (ShapeInferenceTest, ReshapeAutoDimension)
TEST (ShapeInferenceTest, ResizeWithShape)
TEST (ShapeInferenceTest, ResizeWithScale)
TEST (ShapeInferenceTest, ReduceChangeRank)
TEST (ShapeInferenceTest, ReshapeAutoDimensionShrink)
TEST (ShapeInferenceTest, ReshapeAutoDimensionExpand)
TEST (ShapeInferenceTest, ReshapeAutoDimensionUnsqueeze)
TEST (ShapeInferenceTest, SqueezeTestAllDims)
TEST (ShapeInferenceTest, ElementwiseBC)
TEST (ShapeInferenceTest, SqueezeTestSpecificDims)
TEST (ShapeInferenceTest, SqueezeTestScalarResult)
Function Documentation
TEST() [1/12]
TEST (ShapeInferenceTest , BidirectionalBroadcast)
Definition at line 31 of file ShapeInference.cpp.
{
  const Shape shape1{2, 1, 2};
  const Shape shape2{3, 1};
  const Shape reference{2, 3, 2};
  const Shape result1 = broadcastShapes(shape1, shape2);
  const Shape result2 = broadcastShapes(shape2, shape1);
  ASSERT_EQ(result1, reference);
  ASSERT_EQ(result2, reference);
}
References mir::broadcastShapes().
TEST() [2/12]
TEST (ShapeInferenceTest , ElementwiseBC)
Definition at line 159 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{1, 10, 10, 1};
  Shape input2_shape{1, 1, 10, 10};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  mir::TensorType input2_type{mir::DataType::FLOAT32, input2_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto input2 = g.create<ops::InputOp>(input2_type);
  auto add = g.create<ops::AddOp>(input->getOutput(0), input2->getOutput(0));
  ASSERT_EQ(add->getOutputShape(0), Shape({1, 10, 10, 10}));
}
References mir::Operation::getOutput().
TEST() [3/12]
TEST (ShapeInferenceTest , ReduceChangeRank)
Definition at line 89 of file ShapeInference.cpp.
{
  Graph g;
  Shape resultShape{10, 10};
  mir::TensorType input_type{mir::DataType::FLOAT32, Shape{10, 2, 10, 9}};
  auto input = g.create<ops::InputOp>(input_type);
  auto n = g.create<ops::ReduceMeanOp>(input->getOutput(0), std::vector<int32_t>{1, 3}, false);
  ASSERT_EQ(resultShape, n->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [4/12]
TEST (ShapeInferenceTest , ReshapeAutoDimension)
Definition at line 44 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{10, 2, 5};
  Shape expected_shape{10, 1, 10};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto op = g.create<ops::ReshapeOp>(input->getOutput(0), Shape{10, 1, Shape::autoDim});
  ASSERT_EQ(expected_shape, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [5/12]
TEST (ShapeInferenceTest , ReshapeAutoDimensionExpand)
Definition at line 117 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{10, 2, 10};
  Shape result_shape_expand{5, 10, 2, 2};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto op = g.create<ops::ReshapeOp>(input->getOutput(0), Shape{5, Shape::autoDim, 2, 2});
  ASSERT_EQ(result_shape_expand, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [6/12]
TEST (ShapeInferenceTest , ReshapeAutoDimensionShrink)
Definition at line 103 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{10, 2, 10};
  Shape result_shape_shrink{10, 20};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto op = g.create<ops::ReshapeOp>(input->getOutput(0), Shape{10, Shape::autoDim});
  ASSERT_EQ(result_shape_shrink, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [7/12]
TEST (ShapeInferenceTest , ReshapeAutoDimensionUnsqueeze)
Definition at line 131 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{10, 2, 10};
  Shape result_shape_expand{1, 10, 2, 1, 10, 1};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto op = g.create<ops::ReshapeOp>(input->getOutput(0), Shape{1, Shape::autoDim, 2, 1, 10, 1});
  ASSERT_EQ(result_shape_expand, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [8/12]
TEST (ShapeInferenceTest , ResizeWithScale)
Definition at line 73 of file ShapeInference.cpp.
{
  Graph g;
  Shape result_shape{1, 30, 10, 3};
  mir::TensorType input_type{mir::DataType::FLOAT32, Shape{1, 5, 5, 3}};
  auto input = g.create<ops::InputOp>(input_type);
  auto op =
    g.create<ops::ResizeOp>(input->getOutput(0), ops::ResizeOp::ResizeMethod::nearestNeighbor,
                            std::vector<float>{1, 6, 2, 1});
  ASSERT_EQ(result_shape, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [9/12]
TEST (ShapeInferenceTest , ResizeWithShape)
Definition at line 58 of file ShapeInference.cpp.
{
  Graph g;
  Shape result_shape{2, 10, 10, 3};
  mir::TensorType input_type{mir::DataType::FLOAT32, Shape{1, 5, 5, 3}};
  auto input = g.create<ops::InputOp>(input_type);
  auto op = g.create<ops::ResizeOp>(input->getOutput(0),
                                    ops::ResizeOp::ResizeMethod::nearestNeighbor, result_shape);
  ASSERT_EQ(result_shape, op->getOutputShape(0));
}
References mir::Operation::getOutputShape().
TEST() [10/12]
TEST (ShapeInferenceTest , SqueezeTestAllDims)
Definition at line 145 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{1, 2, 1, 4};
  Shape expected_shape{2, 4};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto sq1 = g.create<ops::SqueezeOp>(input->getOutput(0), std::vector<int32_t>{});
  ASSERT_EQ(sq1->getOutputShape(0), expected_shape);
}
References mir::Operation::getOutputShape().
TEST() [11/12]
TEST (ShapeInferenceTest , SqueezeTestScalarResult)
Definition at line 191 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{1, 1, 1, 1};
  Shape expected_shape{1};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto sq1 = g.create<ops::SqueezeOp>(input->getOutput(0), std::vector<int32_t>{});
  ASSERT_EQ(sq1->getOutputShape(0), expected_shape);
}
References mir::Operation::getOutputShape().
TEST() [12/12]
TEST (ShapeInferenceTest , SqueezeTestSpecificDims)
Definition at line 177 of file ShapeInference.cpp.
{
  Graph g;
  Shape input_shape{1, 2, 1, 4};
  Shape expected_shape{1, 2, 4};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  auto input = g.create<ops::InputOp>(input_type);
  auto sq1 = g.create<ops::SqueezeOp>(input->getOutput(0), std::vector<int32_t>{2});
  ASSERT_EQ(sq1->getOutputShape(0), expected_shape);
}
References mir::Operation::getOutputShape().