ONE - On-device Neural Engine: locoex Namespace Reference
locoex Namespace Reference
Data Structures
struct AttrTypeTrait
struct AttrTypeTrait< COpAttrType::Float >
struct AttrTypeTrait< COpAttrType::Int >
class CircleDialect
class CircleInstanceNorm
INSTANCE_NORM in circle.
struct CircleNode
struct CircleNodeImpl
class CircleNodeMixin
class CircleNodeMixin< CircleNodeTrait::FusedActFunc >
struct CircleNodeMutableVisitor
struct CircleNodeMutableVisitorBase
struct CircleNodeVisitor
struct CircleNodeVisitorBase
struct CircleShapeInferenceRule
struct CircleTypeInferenceRule
Type Inference Rule for CircleDialect.
struct COpAttrData
Struct that holds attr type.
struct COpAttrFloat
Struct that holds attr data of float type.
struct COpAttrInt
Struct that holds attr data of int type.
class COpCall
Class to calls custom operation.
class COpDialect
A singleton for locoex custom op Dialect.
struct COpNode
class COpNodeSummaryBuilder
struct COpShapeInferenceRule
Shape inference rule for COpDialect.
struct COpTypeInferenceRule
Type Inference Rule for COpDialect.
class Filter
class FixedArityNode
Nodes with the fixed number of inputs.
class Stride
class TFLAdd
ADD in TensorFlow Lite.
class TFLAveragePool2D
AVERAGE_POOL_2D in TensorFlow Lite.
class TFLConcatenation
CONCATENATION in TensorFlow Lite.
class TFLConst
Class to build tensor data.
class TFLConv2D
CONV_2D in TensorFlow Lite.
class TFLDepthwiseConv2D
DEPTHWISE_CONV_2D in TensorFlow Lite.
class TFLDialect
class TFLDiv
DIV in TensorFlow Lite.
class TFLFullyConnected
FULLY_CONNECTED in TensorFlow Lite.
class TFLMaximum
MAXIMUM in TensorFlow Lite.
class TFLMaxPool2D
MAX_POOL_2D in TensorFlow Lite.
class TFLMean
class TFLMul
MUL in TensorFlow Lite.
struct TFLNode
struct TFLNodeImpl
class TFLNodeMixin
class TFLNodeMixin< TFLNodeTrait::Bias >
Mixin class for nodes that has a bias input.
class TFLNodeMixin< TFLNodeTrait::FusedActFunc >
struct TFLNodeMutableVisitor
struct TFLNodeMutableVisitorBase
struct TFLNodeVisitor
struct TFLNodeVisitorBase
class TFLRelu
class TFLRelu6
class TFLReshape
class TFLRsqrt
struct TFLShapeInferenceRule
class TFLSqrt
class TFLSquaredDifference
class TFLSub
SUB in TensorFlow Lite.
class TFLTranspose
TRANSPOSE in TensorFlow Lite.
class TFLTransposeConv
TRANSPOSE_CONV in TensorFlow Lite.
struct TFLTypeInferenceRule
Type Inference Rule for TFLDialect.
class VariadicArityNode
Nodes with the variadic inputs.
Enumerations
enum class CircleNodeTrait { FusedActFunc }
enumeration of mixin class
enum class CircleOpcode { CIRCLE_NODE }
enum class FusedActFunc { UNDEFINED , NONE , RELU , RELU6 }
enum class Padding { UNDEFINED , SAME , VALID }
enum class TFLNodeTrait { FusedActFunc , Bias }
enumeration of mixin class
enum class TFLOpcode { TFL_NODE }
enum class COpAttrType { Int , Float }
Tensorflow attribute type Refer to https://www.tensorflow.org/guide/extend/op#attr_types.
Functions
INSTANTIATE (loco::DataType::S32)
INSTANTIATE (loco::DataType::FLOAT32)
void set_new_shape (locoex::TFLReshape *node, int32_t *base, uint32_t size)
Set both TFLReshape's 2nd input as TFLConst, and newShape attribute with same value.
Enumeration Type Documentation
CircleNodeTrait
enum class locoex::CircleNodeTrait strong
enumeration of mixin class
Enumerator
FusedActFunc
Definition at line 32 of file CircleNodes.h.
{
  FusedActFunc,
};
CircleOpcode
enum class locoex::CircleOpcode strong
Enumerator
CIRCLE_NODE
Definition at line 23 of file CircleOpcode.h.
{
#define CIRCLE_NODE(OPCODE, CLASS) OPCODE,
#include "CircleNodes.lst"
#undef CIRCLE_NODE
};
COpAttrType
enum class locoex::COpAttrType strong
Tensorflow attribute type Refer to https://www.tensorflow.org/guide/extend/op#attr_types.
Enumerator
Int
Float
Definition at line 29 of file COpAttrTypes.h.
{
  Int,
  Float,
  // TODO Support more attr types such as String, Bool, DataType, Tensor, Shape, List
};
FusedActFunc
enum class locoex::FusedActFunc strong
Enumerator
UNDEFINED
NONE
RELU
RELU6
Definition at line 24 of file FusedActFunc.h.
{
  UNDEFINED, // This is not defined by TFLite or Circle. This was added to
             // prevent programming error.
  NONE,
  RELU,
  RELU6
};
Padding
enum class locoex::Padding strong
Enumerator
UNDEFINED
SAME
VALID
Definition at line 37 of file TFLNodes.h.
{
  UNDEFINED, // This is not defined by TFLite. This was added to prevent programming error.
  SAME,
  VALID,
};
TFLNodeTrait
enum class locoex::TFLNodeTrait strong
enumeration of mixin class
Enumerator
FusedActFunc
Bias
Definition at line 77 of file TFLNodes.h.
{
  FusedActFunc,
  Bias
};
TFLOpcode
enum class locoex::TFLOpcode strong
Enumerator
TFL_NODE
Definition at line 23 of file TFLOpcode.h.
{
#define TFL_NODE(OPCODE, CLASS) OPCODE,
#include "TFLNodes.lst"
#undef TFL_NODE
};
Function Documentation
INSTANTIATE() [1/2]
locoex::INSTANTIATE (loco::DataType::FLOAT32)
INSTANTIATE() [2/2]
locoex::INSTANTIATE (loco::DataType::S32)
set_new_shape()
void locoex::set_new_shape (locoex::TFLReshape * node, int32_t * base, uint32_t size)
Set both TFLReshape's 2nd input as TFLConst, and newShape attribute with same value.
Note
Shape inference for TFLReshape forces them to be same TODO find better place for this helper
Definition at line 67 of file TFLNodes.cpp.
{
  // Check node does not have both of new shape infos
  EXO_ASSERT(node->shape() == nullptr, "node already has shape input");
  EXO_ASSERT(node->newShape()->rank() == 0, "node already has newShape attribute");
  const loco::DataType S32 = loco::DataType::S32;
  // Set 2nd input as TFLConst
  auto const_shape_node = node->graph()->nodes()->create<locoex::TFLConst>();
  const_shape_node->rank(1);
  const_shape_node->dim(0) = size;
  const_shape_node->dtype(S32);
  const_shape_node->size<S32>(size);
  for (uint32_t axis = 0; axis < size; ++axis)
    const_shape_node->at<S32>(axis) = base[axis];
  node->shape(const_shape_node);
  // Set newShape attribute
  node->newShape()->rank(size);
  for (uint32_t axis = 0; axis < size; ++axis)
    node->newShape()->dim(axis) = base[axis];
}
References loco::NodePool::create(), locoex::TFLReshape::Shape::dim(), EXO_ASSERT, loco::Node::graph(), locoex::TFLReshape::newShape(), loco::Graph::nodes(), locoex::TFLReshape::Shape::rank(), and locoex::TFLReshape::shape().
Referenced by exo::DepthwiseConv2DConverter::convert().