ONE - On-device Neural Engine: partee Namespace Reference
partee Namespace Reference
Functions
bool make_dir (const std::string &path)
create folder
std::string get_filename_ext (const std::string &base)
get filename part of base
std::string make_path (const std::string &base, const std::string &input, uint32_t idx, const std::string &backend)
Make file path from base and backend.
bool export_part_conn_json (const std::string &output_base, const std::string &input, const luci::Module *source, luci::PartedModules &pms)
This will save partition connection to json format file.
bool export_part_conn_ini (const std::string &output_base, const std::string &input, const luci::Module *source, luci::PartedModules &pms)
This will save partition connection to ini format file.
luci::PartitionTable read (const std::string &path)
Reads and parse file and return PartitionTable.
Function Documentation
export_part_conn_ini()
bool partee::export_part_conn_ini (const std::string & output_base, const std::string & input, const luci::Module * source, luci::PartedModules & pms)
This will save partition connection to ini format file.
Definition at line 115 of file PartitionExport.cpp.
{
  crew::PConfig pconfig;
  // TODO is graph I/O using main graph is enough?
  auto *graph = source->graph();
  pconfig.source.model_file = input;
  graph_io_to_config_part(graph, pconfig.source);
  pms2config(pms, pconfig);
  auto filepath_ini = export_file_path(output_base, input, ".ini");
  std::ofstream fs(filepath_ini.c_str(), std::ofstream::binary | std::ofstream::trunc);
  if (not fs.good())
  {
    std::cerr << "ERROR: Failed to create file: " << filepath_ini;
    return false;
  }
  if (not write_ini(fs, pconfig))
  {
    std::cerr << "ERROR: Failed to write ini file: " << filepath_ini;
    return false;
  }
  fs.close();
  return true;
}
References luci::Module::graph(), crew::Part::model_file, and crew::PConfig::source.
Referenced by entry().
export_part_conn_json()
bool partee::export_part_conn_json (const std::string & output_base, const std::string & input, const luci::Module * source, luci::PartedModules & pms)
This will save partition connection to json format file.
Definition at line 85 of file PartitionExport.cpp.
{
  crew::PConfig pconfig;
  // TODO is graph I/O using main graph is enough?
  auto *graph = source->graph();
  pconfig.source.model_file = input;
  graph_io_to_config_part(graph, pconfig.source);
  pms2config(pms, pconfig);
  auto filepath_json = export_file_path(output_base, input, ".json");
  std::ofstream fs(filepath_json.c_str(), std::ofstream::binary | std::ofstream::trunc);
  if (not fs.good())
  {
    std::cerr << "ERROR: Failed to create file: " << filepath_json;
    return false;
  }
  if (not write_json(fs, pconfig))
  {
    std::cerr << "ERROR: Failed to write json file: " << filepath_json;
    return false;
  }
  fs.close();
  return true;
}
References luci::Module::graph(), crew::Part::model_file, and crew::PConfig::source.
Referenced by entry().
get_filename_ext()
std::string partee::get_filename_ext (const std::string & base)
get filename part of base
Definition at line 34 of file HelperPath.cpp.
{
  // find last '/' to get filename.ext
  auto pos = base.find_last_of("/");
  if (pos == std::string::npos)
    return base;
  return base.substr(pos + 1);
}
Referenced by entry(), and make_path().
make_dir()
bool partee::make_dir (const std::string & path)
create folder
Definition at line 26 of file HelperPath.cpp.
{
  std::string command("mkdir -p ");
  command += path;
  int ret = ::system(command.c_str());
  return ret == 0;
}
make_path()
std::string partee::make_path (const std::string & base, const std::string & input, uint32_t idx, const std::string & backend)
Make file path from base and backend.
Definition at line 44 of file HelperPath.cpp.
{
  auto filename_ext = get_filename_ext(input);
  // We will assume file type .circle if not given
  // TODO maybe throw if there is no extension?
  std::string filename = filename_ext;
  std::string ext = "circle";
  auto pos = filename_ext.find_last_of(".");
  if (pos != std::string::npos)
  {
    filename = filename_ext.substr(0, pos);
    ext = filename_ext.substr(pos + 1);
  }
  // format idx with 5 '0' paddings like '00123'
  uint32_t length = 5;
  auto seq = std::string(length, '0').append(std::to_string(idx));
  auto seq_fmt = seq.substr(seq.size() - length);
  return base + "/" + filename + "." + seq_fmt + "_" + backend + "." + ext;
}
References get_filename_ext().
Referenced by entry().
read()
luci::PartitionTable partee::read (const std::string & path)
Reads and parse file and return PartitionTable.
Definition at line 132 of file PartitionRead.cpp.
{
  LOGGER(l);
  INFO(l) << "PartitionConfig: " << path << std::endl;
  auto partition_config = crew::read_ini(path);
  INFO(l) << partition_config << std::endl;
  auto partition_table = parse_table(partition_config);
  return partition_table;
}
References INFO, LOGGER, and crew::read_ini().
Referenced by entry().