ONE - On-device Neural Engine: tflchef Namespace Reference
tflchef Namespace Reference
Data Structures
class GeneratedModel
class Logger
Logger Implementation.
class LoggerConfig
Logger Configuration.
struct LoggingContext
Global logging context.
class TFliteImport
Loads TF lite file and provides helpers to access attributes.
class TFliteOpAbs
tflchef operator builder for abs
class TFliteOpAdd
tflchef operator builder for add
class TFliteOpAddN
tflchef operator builder for AddN
class TFliteOpArgMax
tflchef operator builder for ArgMax
class TFliteOpArgMin
tflchef operator builder for ArgMin
class TFliteOpAveragePool2D
tflchef operator builder for AveragePool2D
class TFliteOpBatchMatMul
tflchef operator builder for BATCH_MATMUL
class TFliteOpBatchToSpaceND
tflchef operator builder for BatchToSpaceND
class TFliteOpBidirectionalSequenceLSTM
tflchef operator builder for BidirectionalSequenceLSTM
class TFliteOpCast
tflchef operator builder for CAST
class TFliteOpCeil
tflchef operator builder for CEIL
class TFliteOpChef
Interface for each operators to build tflchef.
class TFliteOpConcatenation
tflchef operator builder for Concatenation
class TFliteOpConv2D
tflchef operator builder for Conv2D
class TFliteOpCos
tflchef operator builder for Cos
class TFliteOpDepthToSpace
tflchef operator builder for DepthToSpace
class TFliteOpDepthwiseConv2D
tflchef operator builder for DepthwiseConv2D
class TFliteOpDequantize
tflchef operator builder for Dequantize
class TFliteOpDiv
tflchef operator builder for division
class TFliteOpELU
tflchef operator builder for ELU
class TFliteOpEqual
tflchef operator builder for Equal
class TFliteOpExp
tflchef operator builder for Exp
class TFliteOpExpandDims
tflchef operator builder for ExpandDims
class TFliteOpFakeQuant
tflchef operator builder for FakeQuant
class TFliteOpFill
tflchef operator builder for Fill
class TFliteOpFloor
tflchef operator builder for FLOOR
class TFliteOpFloorDiv
tflchef operator builder for floor division
class TFliteOpFloorMod
tflchef operator builder for FLOOR_MOD
class TFliteOpFullyConnected
tflchef operator builder for FullyConnected
class TFliteOpGather
tflchef operator builder for Gather
class TFliteOpGatherNd
tflchef operator builder for GatherNd
class TFliteOpGreater
tflchef operator builder for Greater
class TFliteOpGreaterEqual
tflchef operator builder for Greater Equal
class TFliteOpL2Normalize
tflchef operator builder for L2Normalize
class TFliteOpL2Pool2D
tflchef operator builder for L2_POOL_2D
class TFliteOpLeakyRelu
tflchef operator builder for LeakyReLU
class TFliteOpLess
tflchef operator builder for Less
class TFliteOpLessEqual
tflchef operator builder for LessEqual
class TFliteOpLocalResponseNormalization
tflchef operator builder for LocalResponseNormalization
class TFliteOpLog
tflchef operator builder for Log
class TFliteOpLogicalAnd
tflchef operator builder for LogicalAnd
class TFliteOpLogicalNot
tflchef operator builder for LogicalNot
class TFliteOpLogicalOr
tflchef operator builder for LogicalOr
class TFliteOpLogistic
tflchef operator builder for LOGISTIC
class TFliteOpLogSoftmax
tflchef operator builder for LogSoftmax
class TFliteOpMatrixDiag
tflchef operator builder for MatrixDiag
class TFliteOpMatrixSetDiag
tflchef operator builder for MatrixSetDiag
class TFliteOpMaximum
tflchef operator builder for maximum
class TFliteOpMaxPool2D
tflchef operator builder for MaxPool2D
class TFliteOpMean
tflchef operator builder for mean
class TFliteOpMinimum
tflchef operator builder for minimum
class TFliteOpMirrorPad
tflchef operator builder for MIRROR_PAD
class TFliteOpMul
tflchef operator builder for MUL
class TFliteOpNeg
tflchef operator builder for abs
class TFliteOpNonMaxSuppressionV4
tflchef operator builder for NON_MAX_SUPPRESSION_V4
class TFliteOpNonMaxSuppressionV5
tflchef operator builder for NON_MAX_SUPPRESSION_V5
class TFliteOpNotEqual
tflchef operator builder for Not Equal
class TFliteOpOneHot
tflchef operator builder for OneHot
class TFliteOpPack
tflchef operator builder for pack
class TFliteOpPad
tflchef operator builder for PAD
class TFliteOpPadV2
tflchef operator builder for PADV2
class TFliteOpPow
tflchef operator builder for Pow
class TFliteOpPRelu
tflchef operator builder for PRelu
class TFliteOpQuantize
tflchef operator builder for Quantize
class TFliteOpRange
tflchef operator builder for abs
class TFliteOpRank
tflchef operator builder for rank
class TFliteOpReduceAny
tflchef operator builder for REDUCE_ANY
class TFliteOpReduceMax
tflchef operator builder for Reduce Max
class TFliteOpReduceMin
tflchef operator builder for Reduce Min
class TFliteOpReduceProd
tflchef operator builder for REDUCE_PROD
class TFliteOpRegistry
tflchef operator registry
class TFliteOpReLU
tflchef operator builder for ReLU
class TFliteOpReLU6
tflchef operator builder for ReLU6
class TFliteOpReLUN1To1
tflchef operator builder for RELU_N1_TO_1
class TFliteOpReshape
tflchef operator builder for Reshape
class TFliteOpResizeBilinear
tflchef operator builder for ResizeBilinear
class TFliteOpResizeNearestNeighbor
tflchef operator builder for ResizeNearestNeighbor
class TFliteOpReverseSequence
tflchef operator builder for ReverseSequence
class TFliteOpReverseV2
tflchef operator builder for ReverseV2
class TFliteOpRound
tflchef operator builder for Round
class TFliteOpRsqrt
tflchef operator builder for Rsqrt
class TFliteOpScatterNd
tflchef operator builder for ScatterNd
class TFliteOpSegmentSum
tflchef operator builder for SEGMENT_SUM
class TFliteOpSelect
tflchef operator builder for SELECT
class TFliteOpSelectV2
tflchef operator builder for SELECT
class TFliteOpShape
tflchef operator builder for SHAPE
class TFliteOpSin
tflchef operator builder for Sin
class TFliteOpSlice
tflchef operator builder for SLICE
class TFliteOpSoftmax
tflchef operator builder for Softmax
class TFliteOpSpaceToBatchND
tflchef operator builder for SpaceToBatchND
class TFliteOpSpaceToDepth
tflchef operator builder for SpaceToDepth
class TFliteOpSparseToDense
tflchef operator builder for SparseToDense
class TFliteOpSplit
tflchef operator builder for SPLIT
class TFliteOpSplitV
tflchef operator builder for SPLIT_V
class TFliteOpSqrt
tflchef operator builder for Sqrt
class TFliteOpSquare
tflchef operator builder for Square
class TFliteOpSquaredDifference
tflchef operator builder for SquaredDifference
class TFliteOpSqueeze
tflchef operator builder for Squeeze
class TFliteOpStridedSlice
tflchef operator builder for StridedSlice
class TFliteOpSub
tflchef operator builder for Sub
class TFliteOpSum
tflchef operator builder for sum
class TFliteOpSVDF
tflchef operator builder for SVDF
class TFliteOpTanh
tflchef operator builder for Tanh
class TFliteOpTile
tflchef operator builder for Tile
class TFliteOpTopKV2
tflchef operator builder for TOPK_V2
class TFliteOpTranspose
tflchef operator builder for Transpose
class TFliteOpTransposeConv
tflchef operator builder for TransposeConv
class TFliteOpUnidirectionalSequenceLSTM
tflchef operator builder for UnidirectionalSequenceLSTM
class TFliteOpUnique
tflchef operator builder for Unique
class TFliteOpUnpack
tflchef operator builder for Unpack
class TFliteOpWhere
tflchef operator builder for Where
class TFliteOpZerosLike
tflchef operator builder for ZerosLike
Typedefs
using TFliteSubGraphs_t = flatbuffers::Vector< flatbuffers::Offset< tflite::SubGraph > >
using TFliteTensors_t = flatbuffers::Vector< flatbuffers::Offset< tflite::Tensor > >
using TFliteBuffers_t = flatbuffers::Vector< flatbuffers::Offset< tflite::Buffer > >
using TFliteOperators_t = flatbuffers::Vector< flatbuffers::Offset< tflite::Operator > >
Functions
GeneratedModel cook (const ModelRecipe &model_recipe)
GeneratedModel cook (const ::tflchef::ModelRecipe &model_recipe)
Generate a (in-memory) TensorFlow Lite model from a given model recipe.
std::unique_ptr< ModelRecipe > generate_recipe (const tflite::Model *model)
Create ModelRecipe from tflite::Model.
bool write_recipe (const std::string &filename, std::unique_ptr< ModelRecipe > &recipe)
Write ModelRecipe to file with given name.
tflchef::TensorType as_tflchef_type (const tflite::TensorType type)
tflchef::Activation as_tflchef_activation (const tflite::ActivationFunctionType type)
tflchef::Padding as_tflchef_padding (const tflite::Padding padding)
tflchef::MirrorPadMode as_tflchef_mirrorpadmode (const tflite::MirrorPadMode mode)
tflchef::DimensionType as_tflchef_sparse_dim_type (const tflite::DimensionType type)
tflchef::SparseIndexVecType as_tflchef_sparse_idx_vec_type (const tflite::SparseIndexVector type)
template<typename DT >
std::vector< DT > extract_buffer (const tflite::Buffer *buffer)
extract buffer data to std::vector<DT>
template<typename T >
std::vector< T > as_index_vector (const flatbuffers::Vector< T > *flat_array)
void fill_tensor_to_import (int32_t idx, TFliteImport *import)
void fill_two_inputs (const tflite::Operator *op, TFliteImport *import)
void set_inputs (TFliteImport *import, tflchef::Operation *operation, const tflite::Operator *op)
void set_outputs (TFliteImport *import, tflchef::Operation *operation, const tflite::Operator *op)
Typedef Documentation
TFliteBuffers_t
using tflchef::TFliteBuffers_t = typedef flatbuffers::Vector<flatbuffers::Offset<tflite::Buffer> >
Definition at line 34 of file TFliteImport.h.
TFliteOperators_t
using tflchef::TFliteOperators_t = typedef flatbuffers::Vector<flatbuffers::Offset<tflite::Operator> >
Definition at line 35 of file TFliteImport.h.
TFliteSubGraphs_t
using tflchef::TFliteSubGraphs_t = typedef flatbuffers::Vector<flatbuffers::Offset<tflite::SubGraph> >
Definition at line 32 of file TFliteImport.h.
TFliteTensors_t
using tflchef::TFliteTensors_t = typedef flatbuffers::Vector<flatbuffers::Offset<tflite::Tensor> >
Definition at line 33 of file TFliteImport.h.
Function Documentation
as_index_vector()
template<typename T > std::vector< T > tflchef::as_index_vector (const flatbuffers::Vector< T > * flat_array)
Definition at line 47 of file Convert.h.
{
  std::vector<T> ret(flat_array->Length());
  for (uint32_t i = 0; i < flat_array->Length(); i++)
  {
    ret[i] = flat_array->Get(i);
  }
  return ret;
}
Referenced by tflchef::TFliteOpReshape::build(), tflchef::TFliteOpSqueeze::build(), fill_two_inputs(), tflchef::TFliteOpAddN::filler(), tflchef::TFliteOpBidirectionalSequenceLSTM::filler(), tflchef::TFliteOpConv2D::filler(), tflchef::TFliteOpDepthwiseConv2D::filler(), tflchef::TFliteOpPadV2::filler(), tflchef::TFliteOpReshape::filler(), tflchef::TFliteOpReverseSequence::filler(), tflchef::TFliteOpReverseV2::filler(), tflchef::TFliteOpScatterNd::filler(), tflchef::TFliteOpSegmentSum::filler(), tflchef::TFliteOpSlice::filler(), tflchef::TFliteOpStridedSlice::filler(), tflchef::TFliteOpSVDF::filler(), tflchef::TFliteOpUnidirectionalSequenceLSTM::filler(), generate_recipe(), tflchef::TFliteImport::select_sub_graph(), set_inputs(), and set_outputs().
as_tflchef_activation()
tflchef::Activation tflchef::as_tflchef_activation (const tflite::ActivationFunctionType type)
Definition at line 48 of file Convert.cpp.
{
  switch (type)
  {
    case tflite::ActivationFunctionType_NONE:
      return tflchef::NONE;
    case tflite::ActivationFunctionType_RELU:
      return tflchef::RELU;
    case tflite::ActivationFunctionType_RELU_N1_TO_1:
      return tflchef::RELU_N1_TO_1;
    case tflite::ActivationFunctionType_RELU6:
      return tflchef::RELU6;
    case tflite::ActivationFunctionType_TANH:
      return tflchef::TANH;
    case tflite::ActivationFunctionType_SIGN_BIT:
      return tflchef::SIGN_BIT;
    default:
      throw std::runtime_error{"unsupported activation type"};
  }
}
Referenced by tflchef::TFliteOpAdd::build(), tflchef::TFliteOpAveragePool2D::build(), tflchef::TFliteOpBidirectionalSequenceLSTM::build(), tflchef::TFliteOpConcatenation::build(), tflchef::TFliteOpConv2D::build(), tflchef::TFliteOpDepthwiseConv2D::build(), tflchef::TFliteOpDiv::build(), tflchef::TFliteOpFullyConnected::build(), tflchef::TFliteOpL2Normalize::build(), tflchef::TFliteOpL2Pool2D::build(), tflchef::TFliteOpMaxPool2D::build(), tflchef::TFliteOpMul::build(), tflchef::TFliteOpSub::build(), tflchef::TFliteOpSVDF::build(), and tflchef::TFliteOpUnidirectionalSequenceLSTM::build().
as_tflchef_mirrorpadmode()
tflchef::MirrorPadMode tflchef::as_tflchef_mirrorpadmode (const tflite::MirrorPadMode mode)
Definition at line 82 of file Convert.cpp.
{
  switch (mode)
  {
    case tflite::MirrorPadMode_REFLECT:
      return tflchef::REFLECT;
    case tflite::MirrorPadMode_SYMMETRIC:
      return tflchef::SYMMETRIC;
    default:
      throw std::runtime_error{"Unknown mirrorpad mode"};
  }
}
Referenced by tflchef::TFliteOpMirrorPad::build().
as_tflchef_padding()
tflchef::Padding tflchef::as_tflchef_padding (const tflite::Padding padding)
Definition at line 69 of file Convert.cpp.
{
  switch (padding)
  {
    case tflite::Padding_SAME:
      return tflchef::SAME;
    case tflite::Padding_VALID:
      return tflchef::VALID;
    default:
      throw std::runtime_error{"unsupported padding"};
  }
}
Referenced by tflchef::TFliteOpAveragePool2D::build(), tflchef::TFliteOpConv2D::build(), tflchef::TFliteOpDepthwiseConv2D::build(), tflchef::TFliteOpL2Pool2D::build(), tflchef::TFliteOpMaxPool2D::build(), and tflchef::TFliteOpTransposeConv::build().
as_tflchef_sparse_dim_type()
tflchef::DimensionType tflchef::as_tflchef_sparse_dim_type (const tflite::DimensionType type)
Definition at line 95 of file Convert.cpp.
{
  switch (type)
  {
    case tflite::DimensionType_DENSE:
      return tflchef::DimensionType::DENSE;
    case tflite::DimensionType_SPARSE_CSR:
      return tflchef::DimensionType::SPARSE_CSR;
    default:
      throw std::runtime_error("unsupported sparse dimension type");
  }
}
Referenced by generate_recipe().
as_tflchef_sparse_idx_vec_type()
tflchef::SparseIndexVecType tflchef::as_tflchef_sparse_idx_vec_type (const tflite::SparseIndexVector type)
Definition at line 108 of file Convert.cpp.
{
  switch (type)
  {
    case tflite::SparseIndexVector_NONE:
      return tflchef::SparseIndexVecType::SparseIdxVecType_NONE;
    case tflite::SparseIndexVector_Int32Vector:
      return tflchef::SparseIndexVecType::INT32VEC;
    case tflite::SparseIndexVector_Uint16Vector:
      return tflchef::SparseIndexVecType::UINT16VEC;
    case tflite::SparseIndexVector_Uint8Vector:
      return tflchef::SparseIndexVecType::UINT8VEC;
    default:
      throw std::runtime_error("unsupported sparse index vector type");
  }
}
as_tflchef_type()
tflchef::TensorType tflchef::as_tflchef_type (const tflite::TensorType type)
Definition at line 22 of file Convert.cpp.
{
  switch (type)
  {
    case tflite::TensorType_FLOAT32:
      return tflchef::FLOAT32;
    case tflite::TensorType_INT32:
      return tflchef::INT32;
    case tflite::TensorType_INT64:
      return tflchef::INT64;
    case tflite::TensorType_UINT8:
      return tflchef::UINT8;
    case tflite::TensorType_BOOL:
      return tflchef::BOOL;
    case tflite::TensorType_INT16:
      return tflchef::INT16;
    case tflite::TensorType_FLOAT16:
      return tflchef::FLOAT16;
    // TODO handle other types
    // TensorType_STRING
    // TensorType_COMPLEX64
    default:
      throw std::runtime_error{"unsupported tensor type"};
  }
}
Referenced by tflchef::TFliteOpArgMax::build(), tflchef::TFliteOpArgMin::build(), tflchef::TFliteOpCast::build(), tflchef::TFliteOpShape::build(), tflchef::TFliteOpUnique::build(), and generate_recipe().
cook() [1/2]
GeneratedModel tflchef::cook (const ::tflchef::ModelRecipe & model_recipe)
Generate a (in-memory) TensorFlow Lite model from a given model recipe.
Definition at line 699 of file ModelChef.cpp.
{
// Initialize Op Chef Registry
#define OP_CHEF(NAME, FACTORY_CLASS) \
  op_chef_registry().add(#NAME, std::unique_ptr<FACTORY_CLASS>(new FACTORY_CLASS()));
#include "OpChef.def"
#undef OP_CHEF
// Initialize Data Chef Registry
#define DATA_CHEF(TYPE, NAME, FACTORY_CLASS) \
  data_chef_registry(::tflchef::TYPE)        \
    .add(#NAME, std::unique_ptr<FACTORY_CLASS>(new FACTORY_CLASS()));
#include "DataChef.def"
#undef DATA_CHEF
  //
  // Create FlatBufferBuilder
  //
  auto flatbuffer_builder =
    std::unique_ptr<flatbuffers::FlatBufferBuilder>(new flatbuffers::FlatBufferBuilder(1024));
  // Operand-related
  std::vector<flatbuffers::Offset<::tflite::Buffer>> buffer_vec;
  // Operation-related
  std::vector<flatbuffers::Offset<::tflite::OperatorCode>> code_vec;
  // SignatureDef-related
  std::vector<flatbuffers::Offset<::tflite::SignatureDef>> signdef_vec;
  // Graphs-related
  std::vector<flatbuffers::Offset<::tflite::SubGraph>> subgraph_vec;
  // Create OperatorCode with Builtin Operator
  auto builtin_code_map = gather_builtincode_map(model_recipe);
  for (auto const &opcode : builtin_code_map)
  {
    tflite::OperatorCodeBuilder code_builder{*flatbuffer_builder};
    // TODO support for opcode.first >= 127
    assert(opcode.first < 127);
    code_builder.add_deprecated_builtin_code(opcode.first);
    code_builder.add_version(opcode.second);
    code_builder.add_builtin_code(opcode.first);
    auto code = code_builder.Finish();
    // Update OperatorCode vector
    code_vec.emplace_back(code);
  }
  // Create OperatorCode with Custom Operator
  std::set<std::string> custom_code_set = gather_customcode_set(model_recipe);
  std::vector<std::string> custom_code_vec{custom_code_set.begin(), custom_code_set.end()};
  for (auto opcode : custom_code_vec)
  {
    auto custom_code = flatbuffer_builder->CreateString(opcode);
    tflite::OperatorCodeBuilder code_builder{*flatbuffer_builder};
    code_builder.add_deprecated_builtin_code(tflite::BuiltinOperator_CUSTOM);
    code_builder.add_custom_code(custom_code);
    code_builder.add_builtin_code(tflite::BuiltinOperator_CUSTOM);
    auto code = code_builder.Finish();
    // Update OperatorCode vector
    code_vec.emplace_back(code);
  }
  // Create an Empty Buffer
  //
  // Buffer 0 SHOULD be an empty buffer in TensorFlow Lite model file
  // (Please refer to the comment for Tensor.buffer field in schema)
  {
    tflite::BufferBuilder buffer_builder{*flatbuffer_builder};
    buffer_vec.emplace_back(buffer_builder.Finish());
  }
  // symbol_tables stores symbol_table of each sub graph
  // this is used to find tensor ID(index) with tensor name
  std::vector<std::map<std::string, int32_t>> symbol_tables;
  //
  // Create Main graph
  //
  CookParams cp{buffer_vec,       code_vec,        subgraph_vec, flatbuffer_builder,
                builtin_code_map, custom_code_vec, "main"};
  auto table = cook_graph<::tflchef::ModelRecipe>(model_recipe, cp);
  symbol_tables.push_back(table);
  //
  // Create subgraphs if exist
  //
  for (int g = 0; g < model_recipe.graph_size(); ++g)
  {
    const auto &graph = model_recipe.graph(g);
    std::ostringstream stringStream;
    stringStream << "sub_" << (g + 1);
    CookParams cp{buffer_vec,       code_vec,        subgraph_vec,      flatbuffer_builder,
                  builtin_code_map, custom_code_vec, stringStream.str()};
    auto table = cook_graph<::tflchef::Graph>(graph, cp);
    symbol_tables.push_back(table);
  }
  // Create Signature-Def
  //
  for (int s = 0; s < model_recipe.signature_def_size(); ++s)
  {
    // load from recipe
    const auto &rec_signature_def = model_recipe.signature_def(s);
    std::vector<flatbuffers::Offset<::tflite::TensorMap>> tensormap_inputs;
    std::vector<flatbuffers::Offset<::tflite::TensorMap>> tensormap_outputs;
    // which subgraph index to cook
    auto subgraph_index = 0;
    if (rec_signature_def.has_subgraph_index())
    {
      subgraph_index = rec_signature_def.subgraph_index();
    }
    assert(subgraph_index < symbol_tables.size());
    auto &symbol_table = symbol_tables[subgraph_index];
    // cook for inputs
    for (int si = 0; si < rec_signature_def.inputs_size(); ++si)
    {
      // recipe for input TensorMap
      auto rec_tm_input = rec_signature_def.inputs(si);
      auto name = flatbuffer_builder->CreateString(rec_tm_input.name());
      uint32_t tensor_index = 0;
      // either tensor or tensor_index should exist
      assert(rec_tm_input.has_tensor() || rec_tm_input.has_tensor_index());
      if (rec_tm_input.has_tensor())
      {
        // we can get tensor_index from symbol_table
        auto tensor = rec_tm_input.tensor();
        tensor_index = symbol_table[tensor];
      }
      else
      {
        // or we can use tensor_index itself
        tensor_index = rec_tm_input.tensor_index();
      }
      ::tflite::TensorMapBuilder tensormap_builder{*flatbuffer_builder};
      tensormap_builder.add_name(name);
      tensormap_builder.add_tensor_index(tensor_index);
      tensormap_inputs.push_back(tensormap_builder.Finish());
    }
    // cook for outputs, same as inputs
    for (int so = 0; so < rec_signature_def.outputs_size(); ++so)
    {
      auto rec_tm_output = rec_signature_def.outputs(so);
      auto name = flatbuffer_builder->CreateString(rec_tm_output.name());
      uint32_t tensor_index = 0;
      assert(rec_tm_output.has_tensor() || rec_tm_output.has_tensor_index());
      if (rec_tm_output.has_tensor())
      {
        auto tensor = rec_tm_output.tensor();
        tensor_index = symbol_table[tensor];
      }
      else
      {
        tensor_index = rec_tm_output.tensor_index();
      }
      ::tflite::TensorMapBuilder tensormap_builder{*flatbuffer_builder};
      tensormap_builder.add_name(name);
      tensormap_builder.add_tensor_index(tensor_index);
      tensormap_outputs.push_back(tensormap_builder.Finish());
    }
    auto inputs = flatbuffer_builder->CreateVector(tensormap_inputs);
    auto outputs = flatbuffer_builder->CreateVector(tensormap_outputs);
    auto signature_key = flatbuffer_builder->CreateString(rec_signature_def.signature_key());
    // TODO add validation for signature_key
    ::tflite::SignatureDefBuilder signature_def_builder{*flatbuffer_builder};
    signature_def_builder.add_inputs(inputs);
    signature_def_builder.add_outputs(outputs);
    signature_def_builder.add_signature_key(signature_key);
    signature_def_builder.add_subgraph_index(rec_signature_def.subgraph_index());
    signdef_vec.emplace_back(signature_def_builder.Finish());
  }
  // Create "Model" arguments
  auto buffers = flatbuffer_builder->CreateVector(buffer_vec);
  auto signdefs = flatbuffer_builder->CreateVector(signdef_vec);
  auto operator_codes = flatbuffer_builder->CreateVector(code_vec);
  auto subgraphs = flatbuffer_builder->CreateVector(subgraph_vec);
  auto description = flatbuffer_builder->CreateString("Generated by tflchef");
  // Create "Model"
  tflite::ModelBuilder model_builder{*flatbuffer_builder};
  model_builder.add_version(3);
  model_builder.add_operator_codes(operator_codes);
  model_builder.add_signature_defs(signdefs);
  model_builder.add_subgraphs(subgraphs);
  model_builder.add_description(description);
  model_builder.add_buffers(buffers);
  auto model = model_builder.Finish();
  // Finalize
  ::tflite::FinishModelBuffer(*flatbuffer_builder, model);
  // Return "GenerateModel"
  return GeneratedModel{
    std::unique_ptr<GeneratedModelImpl>(new GeneratedModelImpl(std::move(flatbuffer_builder)))};
}
cook() [2/2]
GeneratedModel tflchef::cook (const ModelRecipe & model_recipe)
Referenced by entry(), and entry_stream().
extract_buffer()
template<typename DT > std::vector< DT > tflchef::extract_buffer (const tflite::Buffer * buffer)
extract buffer data to std::vector<DT>
Definition at line 37 of file Convert.h.
{
  assert(buffer->data() != nullptr);
  auto buffer_length = buffer->data()->size();
  auto num_elements = buffer_length / sizeof(DT);
  std::vector<DT> result(num_elements);
  std::memcpy(result.data(), buffer->data()->data(), buffer_length);
  return result;
}
fill_tensor_to_import()
void tflchef::fill_tensor_to_import (int32_t idx, TFliteImport * import)
Definition at line 24 of file FillerHelper.cpp.
{
  const tflite::Tensor *tensor = import->tensors()->Get(idx);
  if (tensor != nullptr)
  {
    if (tensor->type() == tflite::TensorType::TensorType_INT32)
    {
      const tflite::Buffer *buffer = import->buffers()->Get(tensor->buffer());
      if (buffer && buffer->data())
      {
        auto vec = extract_buffer<int32_t>(buffer);
        import->set_tensor_filler(idx, vec);
      }
    }
    else if (tensor->type() == tflite::TensorType::TensorType_FLOAT32)
    {
      const tflite::Buffer *buffer = import->buffers()->Get(tensor->buffer());
      if (buffer && buffer->data())
      {
        auto vec = extract_buffer<float>(buffer);
        import->set_tensor_filler(idx, vec);
      }
    }
  }
}
Referenced by fill_two_inputs(), tflchef::TFliteOpAddN::filler(), tflchef::TFliteOpBidirectionalSequenceLSTM::filler(), tflchef::TFliteOpFullyConnected::filler(), tflchef::TFliteOpNonMaxSuppressionV4::filler(), tflchef::TFliteOpNonMaxSuppressionV5::filler(), tflchef::TFliteOpPadV2::filler(), tflchef::TFliteOpReshape::filler(), tflchef::TFliteOpReverseSequence::filler(), tflchef::TFliteOpReverseV2::filler(), tflchef::TFliteOpScatterNd::filler(), tflchef::TFliteOpSegmentSum::filler(), and tflchef::TFliteOpUnidirectionalSequenceLSTM::filler().
fill_two_inputs()
void tflchef::fill_two_inputs (const tflite::Operator * op, TFliteImport * import)
Definition at line 56 of file FillerHelper.cpp.
{
  const std::vector<int32_t> &inputs = as_index_vector(op->inputs());
  assert(inputs.size() == 2);
  fill_tensor_to_import(inputs[0], import);
  fill_tensor_to_import(inputs[1], import);
}
References as_index_vector(), and fill_tensor_to_import().
Referenced by tflchef::TFliteOpAdd::filler(), tflchef::TFliteOpMaximum::filler(), tflchef::TFliteOpMinimum::filler(), tflchef::TFliteOpMul::filler(), and tflchef::TFliteOpSub::filler().
generate_recipe()
std::unique_ptr< ModelRecipe > tflchef::generate_recipe (const tflite::Model * model)
Create ModelRecipe from tflite::Model.
This will build ModelRecipe from tflite::Model First to check operand filler options by scanning all operators, then translate all operands and operators. Last will set network inputs and outputs.
Definition at line 71 of file RecipeChef.cpp.
{
  std::unique_ptr<ModelRecipe> model_recipe{new ModelRecipe()};
  TFliteImport tflite_import(model);
  assert(tflite_import.num_subgraph() == 1);
  tflite_import.select_sub_graph(0);
  auto tensors = tflite_import.tensors();
  auto buffers = tflite_import.buffers();
  auto operators = tflite_import.operators();
  // operand fillers for adding all operators
  for (uint32_t i = 0; i < operators->Length(); ++i)
  {
    const auto *op = operators->Get(i);
    tflite::BuiltinOperator builtincode = tflite_import.builtin_code(op);
    if (const auto *graph_builder = TFliteOpRegistry::get().lookup(builtincode))
    {
      graph_builder->filler(op, &tflite_import, model_recipe.get());
    }
    else
    {
      std::string opcodename = tflite_import.opcode_name(op);
      throw std::runtime_error{"Not supported: " + opcodename};
    }
  }
  // add all operands(tensors)
  for (uint32_t i = 0; i < tensors->Length(); ++i)
  {
    auto tensor = tensors->Get(i);
    // check buffer
    if (tensor->buffer() >= buffers->size())
      throw std::runtime_error{"file load failed"};
    ::tflchef::Operand *operand = model_recipe->add_operand();
    operand->set_name(mio::tflite::tensor_name(tensor));
    operand->set_type(as_tflchef_type(tensor->type()));
    operand->set_is_variable(tensor->is_variable());
    if (tensor->shape())
    {
      std::vector<int32_t> dims = as_index_vector(tensor->shape());
      ::tflchef::TensorShape *shape = operand->mutable_shape();
      for (auto dim : dims)
      {
        shape->add_dim(dim);
      }
    }
    // filler for weights, bias and so on
    std::vector<int32_t> expvalues;
    std::vector<float> expfvalues;
    if (tflite_import.get_tensor_filler(i))
    {
      tflchef::TensorFiller *filler = operand->mutable_filler();
      // Note: it is OK to use random weights for functionality validation
      filler->set_tag("gaussian");
      filler->add_arg("0.0"); // average
      filler->add_arg("0.1"); // standard deviation
    }
    else if (tflite_import.get_tensor_filler(i, expvalues))
    {
      tflchef::TensorFiller *filler = operand->mutable_filler();
      filler->set_tag("explicit");
      for (auto value : expvalues)
      {
        std::ostringstream ss;
        ss << value;
        filler->add_arg(ss.str());
      }
    }
    else if (tflite_import.get_tensor_filler(i, expfvalues))
    {
      tflchef::TensorFiller *filler = operand->mutable_filler();
      filler->set_tag("explicit");
      for (auto value : expfvalues)
      {
        std::ostringstream ss;
        ss << value;
        filler->add_arg(ss.str());
      }
    }
    auto quant = tensor->quantization();
    if (quant != nullptr)
    {
      // Note: Calling 'operand->mutable_quant()' will create empty 'quant' node
      // in the recipe file. We want this only when valid parameter exist.
      if (quant->min() != nullptr && quant->min()->size() > 0)
      {
        tflchef::TensorQuantization *chef_quant = operand->mutable_quant();
        for (uint32_t idx = 0; idx < quant->min()->size(); ++idx)
          chef_quant->add_min(quant->min()->Get(idx));
      }
      if (quant->max() != nullptr && quant->max()->size() > 0)
      {
        tflchef::TensorQuantization *chef_quant = operand->mutable_quant();
        for (uint32_t idx = 0; idx < quant->max()->size(); idx++)
          chef_quant->add_max(quant->max()->Get(idx));
      }
      if (quant->scale() != nullptr && quant->scale()->size() > 0)
      {
        tflchef::TensorQuantization *chef_quant = operand->mutable_quant();
        for (uint32_t idx = 0; idx < quant->scale()->size(); ++idx)
          chef_quant->add_scale(quant->scale()->Get(idx));
      }
      if (quant->zero_point() != nullptr && quant->zero_point()->size() > 0)
      {
        tflchef::TensorQuantization *chef_quant = operand->mutable_quant();
        for (uint32_t idx = 0; idx < quant->zero_point()->size(); ++idx)
          chef_quant->add_zero_point(quant->zero_point()->Get(idx));
      }
      tflchef::TensorQuantization *chef_quant = operand->mutable_quant();
      chef_quant->set_quantized_dimension(quant->quantized_dimension());
    }
    auto sparsity = tensor->sparsity();
    if (sparsity != nullptr)
    {
      tflchef::TensorSparsity *chef_sparsity = operand->mutable_sparsity();
      // traversal_order
      auto chef_traversal_order = chef_sparsity->mutable_traversal_order();
      for (const auto &to : *(sparsity->traversal_order()))
      {
        chef_traversal_order->add_dim(to);
      }
      // block_map
      auto chef_block_map = chef_sparsity->mutable_block_map();
      for (const auto &bm : *(sparsity->block_map()))
      {
        chef_block_map->add_dim(bm);
      }
      // dim_metadata
      for (const auto &dm : *(sparsity->dim_metadata()))
      {
        auto chef_dm = chef_sparsity->add_dim_metadata();
        // format
        chef_dm->set_format(as_tflchef_sparse_dim_type(dm->format()));
        // dense_size
        chef_dm->set_dense_size(dm->dense_size());
        // array_segments
        auto chef_array_segments = chef_dm->mutable_array_segments();
        switch (dm->array_segments_type())
        {
          case tflite::SparseIndexVector_NONE:
            // DO NOTHING
            break;
          case tflite::SparseIndexVector_Int32Vector:
            for (const auto &as : *(dm->array_segments_as_Int32Vector()->values()))
            {
              chef_array_segments->add_dim(as);
            }
            break;
          case tflite::SparseIndexVector_Uint16Vector:
            for (const auto &as : *(dm->array_segments_as_Uint16Vector()->values()))
            {
              chef_array_segments->add_dim(as);
            }
            break;
          case tflite::SparseIndexVector_Uint8Vector:
            for (const auto &as : *(dm->array_segments_as_Uint8Vector()->values()))
            {
              chef_array_segments->add_dim(as);
            }
            break;
          default:
            throw std::runtime_error("unsupported sparse index vector type");
        }
        // array_indices
        auto chef_array_indices = chef_dm->mutable_array_indices();
        switch (dm->array_indices_type())
        {
          case tflite::SparseIndexVector_NONE:
            // DO NOTHING
            break;
          case tflite::SparseIndexVector_Int32Vector:
            for (const auto &as : *(dm->array_indices_as_Int32Vector()->values()))
            {
              chef_array_indices->add_dim(as);
            }
            break;
          case tflite::SparseIndexVector_Uint16Vector:
            for (const auto &as : *(dm->array_indices_as_Uint16Vector()->values()))
            {
              chef_array_indices->add_dim(as);
            }
            break;
          case tflite::SparseIndexVector_Uint8Vector:
            for (const auto &as : *(dm->array_indices_as_Uint8Vector()->values()))
            {
              chef_array_indices->add_dim(as);
            }
            break;
          default:
            throw std::runtime_error("unsupported sparse index vector type");
        }
      }
    }
    auto shape_signature = tensor->shape_signature();
    if (shape_signature != nullptr)
    {
      tflchef::ShapeSignature *chef_shape_signature = operand->mutable_shape_signature();
      for (uint32_t i = 0; i < shape_signature->size(); ++i)
      {
        chef_shape_signature->add_dim(shape_signature->Get(i));
      }
    }
  }
  // add all operators
  for (uint32_t i = 0; i < operators->Length(); ++i)
  {
    const auto *op = operators->Get(i);
    tflite::BuiltinOperator builtincode = tflite_import.builtin_code(op);
    if (const auto *graph_builder = TFliteOpRegistry::get().lookup(builtincode))
    {
      auto operation = graph_builder->build(op, &tflite_import, model_recipe.get());
      // common for all operators: inputs, outputs
      set_inputs(&tflite_import, operation, op);
      set_outputs(&tflite_import, operation, op);
    }
    else
    {
      std::string opcodename = tflite_import.opcode_name(op);
      throw std::runtime_error{"Not supported: " + opcodename};
    }
  }
  // network inputs/outputs
  const std::vector<int32_t> &inputs = tflite_import.inputs();
  const std::vector<int32_t> &outputs = tflite_import.outputs();
  for (const auto input : inputs)
  {
    auto tensor = tensors->Get(input);
    std::string name = mio::tflite::tensor_name(tensor);
    model_recipe->add_input(name);
  }
  for (const auto output : outputs)
  {
    auto tensor = tensors->Get(output);
    std::string name = mio::tflite::tensor_name(tensor);
    model_recipe->add_output(name);
  }
  return std::move(model_recipe);
}
References as_index_vector(), as_tflchef_sparse_dim_type(), as_tflchef_type(), tflchef::TFliteImport::buffers(), tflchef::TFliteImport::builtin_code(), tflchef::TFliteOpRegistry::get(), souschef::TensorFiller::get_tensor_filler(), tflchef::TFliteImport::inputs(), tflchef::TFliteImport::num_subgraph(), tflchef::TFliteImport::opcode_name(), tflchef::TFliteImport::operators(), tflchef::TFliteImport::outputs(), tflchef::TFliteImport::select_sub_graph(), set_inputs(), set_outputs(), mio::tflite::tensor_name(), and tflchef::TFliteImport::tensors().
Referenced by entry().
set_inputs()
void tflchef::set_inputs (TFliteImport * import, tflchef::Operation * operation, const tflite::Operator * op)
Definition at line 32 of file RecipeChef.cpp.
{
  auto tensors = import->tensors();
  const std::vector<int32_t> &inputs = as_index_vector(op->inputs());
  for (auto input : inputs)
  {
    if (input == -1)
    {
      operation->add_input("");
    }
    else
    {
      auto tensor = tensors->Get(input);
      std::string name = mio::tflite::tensor_name(tensor);
      operation->add_input(name);
    }
  }
}
References as_index_vector(), and mio::tflite::tensor_name().
Referenced by generate_recipe().
set_outputs()
void tflchef::set_outputs (TFliteImport * import, tflchef::Operation * operation, const tflite::Operator * op)
Definition at line 52 of file RecipeChef.cpp.
{
  auto tensors = import->tensors();
  const std::vector<int32_t> &outputs = as_index_vector(op->outputs());
  for (auto output : outputs)
  {
    auto tensor = tensors->Get(output);
    std::string name = mio::tflite::tensor_name(tensor);
    operation->add_output(name);
  }
}
References as_index_vector(), and mio::tflite::tensor_name().
Referenced by generate_recipe().
write_recipe()
bool tflchef::write_recipe (const std::string & filename, std::unique_ptr< ModelRecipe > & recipe)
Write ModelRecipe to file with given name.
Definition at line 330 of file RecipeChef.cpp.
{
  std::fstream fo(filename, std::ios::binary | std::ios::out);
  if (!fo.is_open())
  {
    throw std::runtime_error{"file store failed"};
  }
  // Note: SerializeToString() or SerializeToOstream() writes in binary mode
  // DebugString() and Utf8DebugString() will print as a human readable text
  fo << recipe->Utf8DebugString();
  fo.close();
  return true;
}
Referenced by entry().