ONE - On-device Neural Engine: nnfw Namespace Reference
nnfw Namespace Reference
Namespaces
namespace cker
namespace misc
namespace rt
namespace ruy
namespace tflite
Functions
void * loadLibrary (const char *name)
Load NN API library.
void * getLibraryHandle ()
Load libneuralnetworks.so and return handle of library.
void * loadFunction (const char *name)
Return function ptr in libneuralnetworks.so.
bool NNAPIExists ()
Check if libneuralnetworks.so can be loaded.
Detailed Description
ToDo : This file will be moved into upper folder when integrate with other custom operations. And It should merged with EinsumHelper's BCast.
Function Documentation
getLibraryHandle()
void * nnfw::getLibraryHandle () inline
Load libneuralnetworks.so and return handle of library.
Returns
a symbol table handle of NN API library
Definition at line 92 of file NeuralNetworksLoadHelpers.h.
{
  static void* handle = loadLibrary("libneuralnetworks.so");
  return handle;
}
References loadLibrary().
Referenced by loadFunction(), and NNAPIExists().
loadFunction()
void * nnfw::loadFunction (const char * name) inline
Return function ptr in libneuralnetworks.so.
Parameters
[in] name Name of function
Returns
function pointer
Definition at line 102 of file NeuralNetworksLoadHelpers.h.
{
  void* fn = nullptr;
  if (getLibraryHandle() != nullptr) {
    fn = dlsym(getLibraryHandle(), name);
  }
  if (fn == nullptr) {
    NNAPI_LOG("nnapi error: unable to open function %s", name);
    abort();
  }
  else {
#ifdef _GNU_SOURCE
    Dl_info info;
    if (dladdr(fn, &info))
    {
      NNAPI_LOG("nnapi function '%s' is loaded from '%s' ", name, info.dli_fname);
    }
    else
    {
      NNAPI_LOG("nnapi function '%s' is failed to load", name);
    }
#endif // _GNU_SOURCE
  }
  return fn;
}
References getLibraryHandle(), info, and NNAPI_LOG.
loadLibrary()
void * nnfw::loadLibrary (const char * name) inline
Load NN API library.
Parameters
[in] name path of NN API library
Returns
a symbol table handle of NN API library
Definition at line 75 of file NeuralNetworksLoadHelpers.h.
{
  // TODO: change RTLD_LOCAL? Assumes there can be multiple instances of nn
  // api RT
  void* handle = nullptr;
#if 1 //#ifdef __ANDROID__
  handle = dlopen(name, RTLD_LAZY | RTLD_LOCAL);
  if (handle == nullptr) {
    NNAPI_LOG("nnapi error: unable to open library %s", name);
  }
#endif
  return handle;
}
References NNAPI_LOG.
Referenced by getLibraryHandle().
NNAPIExists()
bool nnfw::NNAPIExists () inline
Check if libneuralnetworks.so can be loaded.
Returns
true if loading is successful, otherwise false.
Definition at line 131 of file NeuralNetworksLoadHelpers.h.
{
  static bool nnapi_is_available = getLibraryHandle();
  return nnapi_is_available;
}
References getLibraryHandle().