ONE - On-device Neural Engine: conftest Namespace Reference
conftest Namespace Reference
Functions
extract_test_args (s)
pytest_addoption (parser)
pytest_generate_tests (metafunc)
copy_if_changed (src_filepath, dst_filepath)
copy_ref_files (ref_file_src, ref_file_dst)
copy_circle_model (model_src, model_dst)
prepare_materials (test_name, tflrecipe_path, circlerecipe_path, binary_path, artifacts_path)
Function Documentation
copy_circle_model()
conftest.copy_circle_model (model_src, model_dst)
Definition at line 53 of file conftest.py.
def copy_circle_model(model_src, model_dst):
    copy_if_changed(model_src, model_dst)
References copy_if_changed().
Referenced by prepare_materials().
copy_if_changed()
conftest.copy_if_changed (src_filepath, dst_filepath)
Definition at line 22 of file conftest.py.
def copy_if_changed(src_filepath, dst_filepath):
    do_copy = False
    if (os.path.isfile(dst_filepath)):
        file_diff = os.stat(src_filepath).st_mtime - os.stat(dst_filepath).st_mtime
        if file_diff > 1:
            print("file:" + src_filepath + " changed, update")
            do_copy = True
    else:
        do_copy = True
    if do_copy:
        print("file:" + src_filepath + " copy to: " + dst_filepath)
        shutil.copyfile(src_filepath, dst_filepath)
# prepare reference input/output files to build folder for luci-eval-driver
# from ref data in res/TensorFlowLiteRecipes/*/ref.input* and ref.output*
# as model_name.ref.input* and model_name.ref.output*
Referenced by copy_circle_model(), and copy_ref_files().
copy_ref_files()
conftest.copy_ref_files (ref_file_src, ref_file_dst)
Definition at line 40 of file conftest.py.
def copy_ref_files(ref_file_src, ref_file_dst):
    num_data = 0
    while True:
        input_file_src = ref_file_src + str(num_data)
        if (not os.path.isfile(input_file_src)):
            break
        input_file_dst = ref_file_dst + str(num_data)
        copy_if_changed(input_file_src, input_file_dst)
        # try next file
        num_data = num_data + 1
# copy circle mode from common-artifacts to build binary
References copy_if_changed().
Referenced by prepare_materials().
extract_test_args()
conftest.extract_test_args (s)
Definition at line 4 of file conftest.py.
def extract_test_args(s):
    p = re.compile('add\\((.*)\\)')
    result = p.search(s)
    return result.group(1)
Referenced by prepare_materials(), and pytest_generate_tests().
prepare_materials()
conftest.prepare_materials (test_name, tflrecipe_path, circlerecipe_path, binary_path, artifacts_path)
Definition at line 57 of file conftest.py.
                      artifacts_path):
    # tfl? or circle?
    recipe_path = tflrecipe_path
    # check with 'test.recipe' file as 'ref.input?' can be absent for no input model
    test_recipe = os.path.join(recipe_path, test_name, 'test.recipe')
    if (not os.path.isfile(test_recipe)):
        recipe_path = circlerecipe_path
    ref_input_src = os.path.join(recipe_path, test_name, 'ref.input')
    ref_input_dst = os.path.join(binary_path, test_name + '.ref.input')
    copy_ref_files(ref_input_src, ref_input_dst)
    ref_input_src = os.path.join(recipe_path, test_name, 'ref.output')
    ref_input_dst = os.path.join(binary_path, test_name + '.ref.output')
    copy_ref_files(ref_input_src, ref_input_dst)
    cirle_model_src = os.path.join(artifacts_path, test_name + '.circle')
    cicle_model_dst = os.path.join(binary_path, test_name + '.circle')
    copy_circle_model(cirle_model_src, cicle_model_dst)
References copy_circle_model(), copy_ref_files(), extract_test_args(), and prepare_materials().
Referenced by prepare_materials().
pytest_addoption()
conftest.pytest_addoption (parser)
Definition at line 10 of file conftest.py.
def pytest_addoption(parser):
    parser.addoption("--test_list", action="store", help="Path to test list")
    parser.addoption("--bin_dir", action="store", help="Directory including artifacts")
    parser.addoption(
        "--circle_part_driver", action="store", help="Path to circle part driver")
pytest_generate_tests()
conftest.pytest_generate_tests (metafunc)
Definition at line 17 of file conftest.py.
def pytest_generate_tests(metafunc):
    list_path = metafunc.config.getoption('test_list')
    bin_dir = metafunc.config.getoption('bin_dir')
    circle_part_driver = metafunc.config.getoption('circle_part_driver')
    with open(list_path) as f:
        contents = [line.rstrip() for line in f]
    comment_removed = [line for line in contents if not line.startswith('#')]
    newline_removed = [line for line in comment_removed if line.startswith('add(')]
    test_args = [extract_test_args(line) for line in newline_removed]
    # add(RECIPE_NAME PARTITION_NAME EXPECTED_OUTPUT_COUNT)
    partition_list = [(arg.split()[1], bin_dir, circle_part_driver) for arg in test_args]
    if 'test_name' in metafunc.fixturenames:
        metafunc.parametrize('test_name,bin_dir,part_driver_path', partition_list)
References extract_test_args().