ONE - On-device Neural Engine: mir_caffe2 Namespace Reference
mir_caffe2 Namespace Reference
Data Structures
class Caffe2OpCreator
Typedefs
using RepArgument = const ::google::protobuf::RepeatedPtrField<::caffe2::Argument > &
Enumerations
enum class SupportedCaffe2OpType {
add , averagePool , clip , concat ,
conv , constantFill , dropout , FC ,
givenTensorFill , givenTensorInt64Fill , maxPool , mul ,
relu , reshape , resizeNearest , sigmoid ,
softmax , spatialBN , sum
}
Functions
std::unique_ptr< mir::Graph > loadModel (std::string predict_net, std::string init_net, const std::vector< std::vector< int > > &input_shapes)
const ::caffe2::Argument & findArgumentByName (RepArgument args, const std::string &name)
bool hasArgument (RepArgument args, const std::string &name)
int getSingleArgument (const ::caffe2::OperatorDef &op, const std::string &argument_name, const int default_value)
float getSingleArgument (const ::caffe2::OperatorDef &op, const std::string &argument_name, const float default_value)
std::string getSingleArgument (const ::caffe2::OperatorDef &op, const std::string &argument_name, const std::string &default_value)
Typedef Documentation
RepArgument
using mir_caffe2::RepArgument = typedef const ::google::protobuf::RepeatedPtrField<::caffe2::Argument> &
Definition at line 25 of file caffe2_proto_helper.h.
Enumeration Type Documentation
SupportedCaffe2OpType
enum class mir_caffe2::SupportedCaffe2OpType strong
Enumerator
add
averagePool
clip
concat
conv
constantFill
dropout
FC
givenTensorFill
givenTensorInt64Fill
maxPool
mul
relu
reshape
resizeNearest
sigmoid
softmax
spatialBN
sum
Definition at line 23 of file caffe2_op_types.h.
{
  add,
  averagePool,
  clip,
  concat,
  conv,
  constantFill,
  dropout,
  FC,
  givenTensorFill,
  givenTensorInt64Fill,
  maxPool,
  mul,
  relu,
  reshape,
  resizeNearest,
  sigmoid,
  softmax,
  spatialBN,
  sum,
};
Function Documentation
findArgumentByName()
const ::caffe2::Argument & mir_caffe2::findArgumentByName (RepArgument args, const std::string & name)
Definition at line 22 of file caffe2_proto_helper.cpp.
{
  for (auto &arg : args)
    if (arg.name() == name)
      return arg;
  throw std::runtime_error("Can't find argument with name: " + name);
}
Referenced by getSingleArgument().
getSingleArgument() [1/3]
float mir_caffe2::getSingleArgument (const ::caffe2::OperatorDef & op, const std::string & argument_name, const float default_value)
Definition at line 46 of file caffe2_proto_helper.cpp.
{
  if (hasArgument(op.arg(), argument_name))
    return findArgumentByName(op.arg(), argument_name).f();
  return default_value;
}
References findArgumentByName(), and hasArgument().
getSingleArgument() [2/3]
int mir_caffe2::getSingleArgument (const ::caffe2::OperatorDef & op, const std::string & argument_name, const int default_value)
Definition at line 38 of file caffe2_proto_helper.cpp.
{
  if (hasArgument(op.arg(), argument_name))
    return static_cast<int>(findArgumentByName(op.arg(), argument_name).i());
  return default_value;
}
References findArgumentByName(), and hasArgument().
Referenced by mir_caffe2::Caffe2OpCreator::convertAdd(), mir_caffe2::Caffe2OpCreator::convertClip(), mir_caffe2::Caffe2OpCreator::convertConcat(), mir_caffe2::Caffe2OpCreator::convertConv(), mir_caffe2::Caffe2OpCreator::convertMul(), mir_caffe2::Caffe2OpCreator::convertResizeNearest(), mir_caffe2::Caffe2OpCreator::convertSoftmax(), and mir_caffe2::Caffe2OpCreator::convertSpatialBN().
getSingleArgument() [3/3]
std::string mir_caffe2::getSingleArgument (const ::caffe2::OperatorDef & op, const std::string & argument_name, const std::string & default_value)
Definition at line 54 of file caffe2_proto_helper.cpp.
{
  if (hasArgument(op.arg(), argument_name))
    return findArgumentByName(op.arg(), argument_name).s();
  return default_value;
}
References findArgumentByName(), and hasArgument().
hasArgument()
bool mir_caffe2::hasArgument (RepArgument args, const std::string & name)
Definition at line 30 of file caffe2_proto_helper.cpp.
{
  for (auto &arg : args)
    if (arg.name() == name)
      return true;
  return false;
}
Referenced by mir_caffe2::Caffe2OpCreator::convertConstant(), mir_caffe2::Caffe2OpCreator::convertFC(), and getSingleArgument().
loadModel()
std::unique_ptr< mir::Graph > mir_caffe2::loadModel (std::string predict_net, std::string init_net, const std::vector< std::vector< int > > & input_shapes)
Definition at line 336 of file caffe2_importer.cpp.
{
  Caffe2Importer importer(std::move(predict_net), std::move(init_net), input_shapes);
  return importer.importModel();
}
Referenced by main().