ONE - On-device Neural Engine: nest Namespace Reference
nest Namespace Reference
Namespaces
namespace expr
namespace stmt
Data Structures
struct Block
class Bound
class Closure
class Domain
class DomainContext
class DomainID
class DomainInfo
struct FV
Collect free variables from nest expr/stmt/block/...
class Level
class Module
class Ret
class Schedule
class Var
class VarContext
class VarID
Typedefs
using Expr = std::shared_ptr< nest::expr::Node >
using Stmt = std::shared_ptr< stmt::Node >
Functions
bool operator== (const DomainID &lhs, const DomainID &rhs)
bool operator< (const DomainID &lhs, const DomainID &rhs)
bool operator== (const Level &lhs, const Level &rhs)
bool operator< (const Level &lhs, const Level &rhs)
bool operator== (const VarID &lhs, const VarID &rhs)
bool operator< (const VarID &lhs, const VarID &rhs)
Typedef Documentation
Expr
using nest::Expr = typedef std::shared_ptr<nest::expr::Node>
Definition at line 37 of file Expr.h.
Stmt
using nest::Stmt = typedef std::shared_ptr<stmt::Node>
Definition at line 30 of file Stmt.h.
Function Documentation
operator<() [1/3]
bool nest::operator< (const DomainID & lhs, const DomainID & rhs)
Definition at line 28 of file DomainID.cpp.
{ return lhs.value() < rhs.value(); }
References nest::DomainID::value().
operator<() [2/3]
bool nest::operator< (const Level & lhs, const Level & rhs)
Definition at line 43 of file Level.cpp.
{
  assert(lhs.valid() && rhs.valid());
  return lhs.value() < rhs.value();
}
References nest::Level::valid(), and nest::Level::value().
operator<() [3/3]
bool nest::operator< (const VarID & lhs, const VarID & rhs)
Definition at line 28 of file VarID.cpp.
{ return lhs.value() < rhs.value(); }
References nest::VarID::value().
operator==() [1/3]
bool nest::operator== (const DomainID & lhs, const DomainID & rhs)
Definition at line 27 of file DomainID.cpp.
{ return lhs.value() == rhs.value(); }
References nest::DomainID::value().
operator==() [2/3]
bool nest::operator== (const Level & lhs, const Level & rhs)
Definition at line 37 of file Level.cpp.
{
  assert(lhs.valid() && rhs.valid());
  return lhs.value() == rhs.value();
}
References nest::Level::valid(), and nest::Level::value().
operator==() [3/3]
bool nest::operator== (const VarID & lhs, const VarID & rhs)
Definition at line 27 of file VarID.cpp.
{ return lhs.value() == rhs.value(); }
References nest::VarID::value().