ONE - On-device Neural Engine: mio::tflite Namespace Reference
mio::tflite Namespace Reference
Functions
::tflite::BuiltinOperator builtin_code_neutral (const ::tflite::OperatorCode *opcode)
bool is_valid (const ::tflite::OperatorCode *opcode)
bool is_custom (const ::tflite::OperatorCode *opcode)
std::string opcode_name (const ::tflite::OperatorCode *opcode)
const char * tensor_type (const ::tflite::Tensor *tensor)
const char * tensor_name (const ::tflite::Tensor *tensor)
Function Documentation
builtin_code_neutral()
tflite::BuiltinOperator mio::tflite::builtin_code_neutral (const ::tflite::OperatorCode * opcode)
This will provide v3/v3a format neutral BuiltinOperator
This function referenced https://github.com/tensorflow/tensorflow/blob/7d12007d7800d3714a02e05059f3ea602d1aec78/tensorflow/lite/schema/schema_utils.cc
Definition at line 33 of file Helper.cpp.
{
  assert(opcode != nullptr);
  return std::max(opcode->builtin_code(),
                  static_cast<::tflite::BuiltinOperator>(opcode->deprecated_builtin_code()));
}
Referenced by tflinspect::Reader::builtin_code(), tflchef::TFliteImport::builtin_code(), tflread::Reader::builtin_code(), is_custom(), opcode_name(), and tflchef::TFliteImport::opcode_name().
is_custom()
bool mio::tflite::is_custom (const ::tflite::OperatorCode * opcode)
Definition at line 55 of file Helper.cpp.
{
  ::tflite::BuiltinOperator code = builtin_code_neutral(opcode);
  return (code == ::tflite::BuiltinOperator_CUSTOM);
}
References builtin_code_neutral().
Referenced by opcode_name(), and tflchef::TFliteImport::opcode_name().
is_valid()
bool mio::tflite::is_valid (const ::tflite::OperatorCode * opcode)
Definition at line 40 of file Helper.cpp.
{
  // Valid Range : 0 <= deprecated_builtin_code <= 127
  const int8_t deprecated_builtin_code = opcode->deprecated_builtin_code();
  if (deprecated_builtin_code < 0)
    return false;
  const ::tflite::BuiltinOperator builtin_code = opcode->builtin_code();
  if (!(::tflite::BuiltinOperator_MIN <= builtin_code &&
        builtin_code <= ::tflite::BuiltinOperator_MAX))
    return false;
  return true;
}
Referenced by opcode_name(), tflinspect::Reader::opcode_name(), tflchef::TFliteImport::opcode_name(), and tflread::Reader::opcode_name().
opcode_name()
std::string mio::tflite::opcode_name (const ::tflite::OperatorCode * opcode)
Definition at line 61 of file Helper.cpp.
{
  assert(opcode);
  if (!is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid)";
    return oss.str();
  }
  if (is_custom(opcode))
  {
    if (!opcode->custom_code())
      return "(invalid custom)";
    std::string custom_op = "CUSTOM(";
    custom_op += opcode->custom_code()->c_str();
    custom_op += ")";
    return custom_op;
  }
  ::tflite::BuiltinOperator code = builtin_code_neutral(opcode);
  return ::tflite::EnumNameBuiltinOperator(code);
}
References builtin_code_neutral(), is_custom(), and is_valid().
Referenced by tfldump::dump_model(), tflinspect::Reader::opcode_name(), and tflread::Reader::opcode_name().
tensor_name()
const char * mio::tflite::tensor_name (const ::tflite::Tensor * tensor)
Definition at line 92 of file Helper.cpp.
{
  static const char *kEmptyTensorName = "(noname)";
  auto name = tensor->name();
  if (name)
    return name->c_str();
  return kEmptyTensorName;
}
Referenced by tfldump::dump_sub_graph(), tflchef::generate_recipe(), tflchef::set_inputs(), and tflchef::set_outputs().
tensor_type()
const char * mio::tflite::tensor_type (const ::tflite::Tensor * tensor)
Definition at line 87 of file Helper.cpp.
{
  return ::tflite::EnumNameTensorType(tensor->type());
}
Referenced by tfldump::dump_sub_graph().