ONE - On-device Neural Engine: onert::backend::train::ops Namespace Reference
onert::backend::train::ops Namespace Reference
Data Structures
class BackPropAccumulator
class BackPropInitializer
class BinaryArithmeticLayer
class ConvolutionLayer
class DepthwiseConvolutionLayer
class ElementwiseActivationLayer
class FullyConnectedLayer
class GradientApplier
class LossCategoricalCrossentropyLayer
class LossLayer
class LossMeanSquaredErrorLayer
class MeanLayer
class PadLayer
class PoolLayer
class ReshapeLayer
class SoftMaxLayer
class TrainingKernelRegistry
Typedefs
using OperandType = onert::ir::DataType
Enumerations
enum class ArithmeticType { kAdd , kSub , kMul , kDiv }
enum class ElementwiseActivationType { kReLU }
enum class LossType { kMSE }
enum class PoolType { kMax , kAvg }
Functions
nnfw::cker::Shape getShape (const IPortableTensor *tensor)
Get shape of tensor.
const IPortableTensor * backpropActivation (const ir::Activation &activation, const IPortableTensor *output, const IPortableTensor *input_backprop, IPortableTensor *output_backprop)
backpropagate acitvation
void biasGrad (const IPortableTensor *input_backprop, IPortableTensor *bias_grad)
backpropagate bias
nnfw::cker::train::LossReductionType convertLossReductionType (ir::train::LossReductionType type)
convert loss reduction type
Typedef Documentation
OperandType
using onert::backend::train::ops::OperandType = typedef onert::ir::DataType
Definition at line 27 of file OperationUtils.h.
Enumeration Type Documentation
ArithmeticType
enum class onert::backend::train::ops::ArithmeticType strong
Enumerator
kAdd
kSub
kMul
kDiv
Definition at line 29 of file BinaryArithmeticLayer.h.
{
  kAdd,
  kSub,
  kMul,
  kDiv,
};
ElementwiseActivationType
enum class onert::backend::train::ops::ElementwiseActivationType strong
Enumerator
kReLU
Definition at line 28 of file ElementwiseActivationLayer.h.
{
  kReLU,
};
LossType
enum class onert::backend::train::ops::LossType strong
Enumerator
kMSE
Definition at line 29 of file LossLayer.h.
{
  kMSE,
};
PoolType
enum class onert::backend::train::ops::PoolType strong
Enumerator
kMax
kAvg
Definition at line 39 of file PoolLayer.h.
{
  kMax,
  kAvg,
};
Function Documentation
backpropActivation()
const IPortableTensor * onert::backend::train::ops::backpropActivation (const ir::Activation & activation, const IPortableTensor * output, const IPortableTensor * input_backprop, IPortableTensor * output_backprop)
backpropagate acitvation
        -- forward direction -->
[ current layer ] -— [ next layer ] [ op | act ]
      <-- backward direction --
Parameters
activation activation of current layer
output forward direction's output of current layer
input_backprop backward direction's output of next layer In other words, incoming gradient to current layer
output_backprop backward direction's output of activation, In other words, outcoming gradient of current layer's acitvation If activation is NONE, this param can be nullptr
Returns
tensor that holds backpropagate result of activation If activation is NONE, just return input_backprop
Definition at line 44 of file OperationUtils.cc.
{
  assert(output != nullptr);
  assert(input_backprop != nullptr);
  // handle NONE - just propagate incoming gradient
  if (activation == ir::Activation::NONE)
  {
    return input_backprop;
  }
  assert(output_backprop != nullptr);
  // handle other activation
  switch (activation)
  {
    case ir::Activation::RELU:
      nnfw::cker::train::ReLUGrad(getShape(output), getBuffer<float>(output),
                                  getShape(input_backprop), getBuffer<float>(input_backprop),
                                  getShape(output_backprop), getBuffer<float>(output_backprop));
      break;
    case ir::Activation::RELU6:
      nnfw::cker::train::ReLU6Grad(getShape(output), getBuffer<float>(output),
                                   getShape(input_backprop), getBuffer<float>(input_backprop),
                                   getShape(output_backprop), getBuffer<float>(output_backprop));
      break;
    // TODO: Add other activation backpropagation here
    default:
      throw std::runtime_error("Unsupported activation type yet");
  }
  return output_backprop;
}
References getShape(), onert::ir::NONE, onert::ir::RELU, onert::ir::RELU6, nnfw::cker::train::ReLU6Grad(), and nnfw::cker::train::ReLUGrad().
Referenced by onert::backend::train::ops::BinaryArithmeticLayer::backward().
biasGrad()
void onert::backend::train::ops::biasGrad (const IPortableTensor * input_backprop, IPortableTensor * bias_grad)
backpropagate bias
Parameters
input_backprop backward direction's output of next layer In other words, incoming gradient to current layer
bias_grad gradient tensor of bias
Definition at line 80 of file OperationUtils.cc.
{
  assert(bias_grad);
  nnfw::cker::Shape input_backprop_shape = getShape(input_backprop);
  float *input_backprop_buffer = reinterpret_cast<float *>(input_backprop->buffer());
  nnfw::cker::Shape bias_grad_shape = getShape(bias_grad);
  float *bias_grad_buffer = getBuffer<float>(bias_grad);
  nnfw::cker::functor::biasReductionHelper(input_backprop_buffer, input_backprop_shape,
                                           bias_grad_buffer, bias_grad_shape);
}
References nnfw::cker::functor::biasReductionHelper(), onert::backend::ITensor::buffer(), and getShape().
convertLossReductionType()
nnfw::cker::train::LossReductionType onert::backend::train::ops::convertLossReductionType (ir::train::LossReductionType type)
convert loss reduction type
Parameters
type loss reduction type defined in ir::train::LossReductionType
Returns
corresponding type defined in cker::train::LossReductionType
Definition at line 94 of file OperationUtils.cc.
{
  switch (type)
  {
    case ir::train::LossReductionType::SumOverBatchSize:
      return nnfw::cker::train::LossReductionType::SUM_OVER_BATCH_SIZE;
    case ir::train::LossReductionType::Sum:
      return nnfw::cker::train::LossReductionType::SUM;
    default:
      throw std::runtime_error("Unsupported LossReductionType");
  }
}
References nnfw::cker::train::SUM, onert::ir::train::Sum, nnfw::cker::train::SUM_OVER_BATCH_SIZE, and onert::ir::train::SumOverBatchSize.
Referenced by onert::backend::train::ops::LossCategoricalCrossentropyLayer::backward(), and onert::backend::train::ops::LossMeanSquaredErrorLayer::backward().
getShape()
nnfw::cker::Shape onert::backend::train::ops::getShape (const IPortableTensor * tensor)
Get shape of tensor.
Parameters
tensor tensor to get shape
Returns
Shape to be used in cker
Definition at line 26 of file OperationUtils.cc.
{
  if (tensor == nullptr)
    return nnfw::cker::Shape();
  assert(!tensor->is_dynamic() && "Dynamic tensor is not supported yet");
  const ir::Shape &shape = tensor->get_info().shape();
  auto rank = shape.rank();
  nnfw::cker::Shape ret(rank);
  auto data = ret.DimsData();
  for (int i = 0; i < rank; ++i)
  {
    data[i] = shape.dim(i);
  }
  return ret;
}
References nnfw::cker::Shape::DimsData().
Referenced by backpropActivation(), onert::backend::train::ops::BackPropAccumulator::backward(), onert::backend::train::ops::BinaryArithmeticLayer::backward(), onert::backend::train::ops::LossCategoricalCrossentropyLayer::backward(), onert::backend::train::ops::LossMeanSquaredErrorLayer::backward(), onert::backend::train::ops::MeanLayer::backward(), onert::backend::train::ops::SoftMaxLayer::backward(), biasGrad(), onert::backend::train::ops::ElementwiseActivationLayer::configureBackward(), onert::backend::train::ops::DepthwiseConvolutionLayer::configureBackward(), onert::backend::train::ops::PadLayer::depad(), onert::backend::train::ops::LossCategoricalCrossentropyLayer::forward(), and onert::backend::train::ops::LossMeanSquaredErrorLayer::forward().