ONE - On-device Neural Engine: nnfw::cker::train Namespace Reference
nnfw::cker::train Namespace Reference
Namespaces
namespace functor
Data Structures
class DepthwiseConv
struct LaunchConv2DBackpropFilterOp
struct LaunchConv2DBackpropInputOp
struct LaunchConv2DBackpropInputOpImpl
Functions
void ConvInputGrad (const ConvParams &params, const Shape &incoming_shape, const float *incoming_data, const Shape &filter_shape, const float *filter_data, const int padding_bottom, const int padding_right, const Shape &grad_shape, float *grad_data)
void ConvFilterGrad (const ConvParams &params, const Shape &incoming_shape, const float *incoming_data, const Shape &input_shape, const float *input_data, const int padding_bottom, const int padding_right, const Shape &filter_backprop_shape, float *filter_backprop_data)
template<typename T >
void FullyConnectedBiasGrad (const Shape &incomming_shape, const T *incomming_data, const Shape &grad_shape, T *grad_data)
template<typename T >
T square (T value)
template<typename T >
T log_threshold ()
template<typename T >
void MSE (const Shape &y_pred_shape, const T *y_pred_data, const Shape &y_true_shape, const T *y_true_data, const Shape &output_shape, T *output_data)
template<typename T >
void MSEGrad (const Shape &y_pred_shape, const T *y_pred_data, const Shape &y_true_shape, const T *y_true_data, const Shape &grad_shape, T *grad_data)
template<typename T >
void CategoricalCrossEntropy (const Shape &y_pred_shape, const T *y_pred_data, const Shape &y_true_shape, const T *y_true_data, const Shape &output_shape, T *output_data)
template<typename T >
void CategoricalCrossEntropyGrad (const Shape &y_pred_shape, const T *y_pred_data, const Shape &y_true_shape, const T *y_true_data, const Shape &grad_shape, T *grad_data)
void MaxPool2D (const PoolParams &params, const Shape &input_shape, const float *input_data, const Shape &output_shape, float *output_data, int *arg_max_index)
void MaxPool2DGrad (const Shape &incoming_shape, const float *incoming_data, const int *arg_max_index, const Shape &grad_shape, float *grad_data)
template<typename T >
void MeanGrad (const Shape &incoming_shape, const T *incoming_data, const Shape &grad_shape, T *grad_data)
void ReLUGrad (const Shape &output_shape, const float *output_data, const Shape &incoming_shape, const float *incoming_data, const Shape &grad_shape, float *grad_data)
void ReLU6Grad (const Shape &output_shape, const float *output_data, const Shape &incoming_shape, const float *incoming_data, const Shape &grad_shape, float *grad_data)
void SoftMaxGrad (const Shape &output_shape, const float *output_data, const Shape &incoming_shape, const float *incoming_data, const Shape &grad_shape, float *grad_data)
void Adam (const Shape &trainable_shape, float *trainable_data, const Shape &grad_shape, const float *grad_data, const Shape &m_shape, float *m_data, const Shape &v_shape, float *v_data, float beta1_power, float beta2_power, float learning_rate, float beta1, float beta2, float epsilon, bool use_nesterov)
void GradientDescent (const Shape &output_shape, float *output_data, const Shape &grad_shape, const float *grad_data, float learning_rate)
Function Documentation
Adam()
void nnfw::cker::train::Adam (const Shape & trainable_shape, float * trainable_data, const Shape & grad_shape, const float * grad_data, const Shape & m_shape, float * m_data, const Shape & v_shape, float * v_data, float beta1_power, float beta2_power, float learning_rate, float beta1, float beta2, float epsilon, bool use_nesterov) inline
Definition at line 33 of file Adam.h.
{
  Tensor trainable_tensor;
  Tensor grad_tensor;
  Tensor m_tensor;
  Tensor v_tensor;
  Tensor beta1_power_tensor;
  Tensor beta2_power_tensor;
  Tensor lr_tensor;
  Tensor beta1_tensor;
  Tensor beta2_tensor;
  Tensor epsilon_tensor;
  trainable_tensor.shape.ReplaceWith(trainable_shape.DimensionsCount(), trainable_shape.DimsData());
  trainable_tensor.buffer = trainable_data;
  grad_tensor.shape.ReplaceWith(grad_shape.DimensionsCount(), grad_shape.DimsData());
  grad_tensor.buffer = const_cast<float *>(grad_data);
  m_tensor.shape.ReplaceWith(m_shape.DimensionsCount(), m_shape.DimsData());
  m_tensor.buffer = m_data;
  v_tensor.shape.ReplaceWith(v_shape.DimensionsCount(), v_shape.DimsData());
  v_tensor.buffer = v_data;
  std::vector<float> beta1_power_vec{beta1_power};
  beta1_power_tensor.buffer = beta1_power_vec.data();
  std::vector<float> beta2_power_vec{beta2_power};
  beta2_power_tensor.buffer = beta2_power_vec.data();
  std::vector<float> lr_vec{learning_rate};
  lr_tensor.buffer = lr_vec.data();
  std::vector<float> beta1_vec{beta1};
  beta1_tensor.buffer = beta1_vec.data();
  std::vector<float> beta2_vec{beta2};
  beta2_tensor.buffer = beta2_vec.data();
  std::vector<float> epsilon_vec{epsilon};
  epsilon_tensor.buffer = epsilon_vec.data();
  if (trainable_shape != m_shape)
    throw std::runtime_error("cker::Adam: output and m do not have the same shape");
  if (trainable_shape != v_shape)
    throw std::runtime_error("cker::Adam: output and v do not have the same shape");
  if (trainable_shape != grad_shape)
    throw std::runtime_error("cker::Adam: output and gradient do not have the same shape");
  const training_ops::CPUDevice &device = *eigen_support::GetThreadPoolDevice();
  training_ops::functor::ApplyAdam<training_ops::CPUDevice, float>()(
    device, trainable_tensor.flat<float>(), m_tensor.flat<float>(), v_tensor.flat<float>(),
    beta1_power_tensor.scalar<float>(), beta2_power_tensor.scalar<float>(),
    lr_tensor.scalar<float>(), beta1_tensor.scalar<float>(), beta2_tensor.scalar<float>(),
    epsilon_tensor.scalar<float>(), static_cast<const Tensor &>(grad_tensor).flat<float>(),
    use_nesterov);
}
References nnfw::cker::Tensor::buffer, nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::DimsData(), nnfw::cker::Tensor::flat(), nnfw::cker::eigen_support::GetThreadPoolDevice(), nnfw::cker::Shape::ReplaceWith(), nnfw::cker::Tensor::scalar(), and nnfw::cker::Tensor::shape.
Referenced by onert::backend::train::optimizer::Adam::applyGradient().
CategoricalCrossEntropy()
template<typename T > void nnfw::cker::train::CategoricalCrossEntropy (const Shape & y_pred_shape, const T * y_pred_data, const Shape & y_true_shape, const T * y_true_data, const Shape & output_shape, T * output_data) inline
Definition at line 77 of file Loss.h.
{
  if (output_shape.DimensionsCount() != 1)
    throw std::runtime_error("cker::CategoricalCrossEntropy: output dimension count should be 1");
  if (y_pred_shape != y_true_shape)
    throw std::runtime_error(
      "cker::CategoricalCrossEntropy: y_pred and y_true do not have the same shape");
  if (output_shape.Dims(0) != y_pred_shape.Dims(0))
    throw std::runtime_error(
      "cker::CategoricalCrossEntropy: output and y_pred do not have the same batch");
  const auto y_pred = MapAsMatrixWithLastDimAsRows(y_pred_data, y_pred_shape);
  const auto y_true = MapAsMatrixWithLastDimAsRows(y_true_data, y_true_shape);
  auto output = MapAsVector(output_data, output_shape);
  output = -(y_true.array() * y_pred.array().cwiseMax(log_threshold<T>()).log()).colwise().sum();
}
References nnfw::cker::Shape::Dims(), nnfw::cker::MapAsMatrixWithLastDimAsRows(), nnfw::cker::MapAsVector(), and output_shape.
Referenced by onert::backend::train::ops::LossCategoricalCrossentropyLayer::forward().
CategoricalCrossEntropyGrad()
template<typename T > void nnfw::cker::train::CategoricalCrossEntropyGrad (const Shape & y_pred_shape, const T * y_pred_data, const Shape & y_true_shape, const T * y_true_data, const Shape & grad_shape, T * grad_data) inline
Definition at line 98 of file Loss.h.
{
  if (y_pred_shape != y_true_shape)
    throw std::runtime_error(
      "cker::CategoricalCrossEntropyGrad: y_pred and y_true do not have the same shape");
  if (y_pred_shape != grad_shape)
    throw std::runtime_error(
      "cker::CategoricalCrossEntropyGrad: y_pred and grad do not have the same shape");
  const auto y_pred = MapAsMatrixWithLastDimAsRows(y_pred_data, y_pred_shape);
  const auto y_true = MapAsMatrixWithLastDimAsRows(y_true_data, y_true_shape);
  auto grad = MapAsMatrixWithLastDimAsRows(grad_data, grad_shape);
  grad = -(y_true.array() / y_pred.array().cwiseMax(log_threshold<T>()));
}
References nnfw::cker::MapAsMatrixWithLastDimAsRows().
Referenced by onert::backend::train::ops::LossCategoricalCrossentropyLayer::backward().
ConvFilterGrad()
void nnfw::cker::train::ConvFilterGrad (const ConvParams & params, const Shape & incoming_shape, const float * incoming_data, const Shape & input_shape, const float * input_data, const int padding_bottom, const int padding_right, const Shape & filter_backprop_shape, float * filter_backprop_data) inline
Definition at line 225 of file Conv.h.
{
  const int stride_rows = params.stride_height;
  const int stride_cols = params.stride_width;
  const PaddingType padding = params.padding_type;
  const int padding_top = params.padding_values.height;
  const int padding_left = params.padding_values.width;
  assert(padding_top >= 0);
  assert(padding_bottom >= 0);
  assert(padding_left >= 0);
  assert(padding_right >= 0);
  const int dilation_rows = params.dilation_height_factor;
  const int dilation_cols = params.dilation_width_factor;
  const int batches = MatchingDim(input_shape, 0, incoming_shape, 0);
  const int input_depth = MatchingDim(filter_backprop_shape, 2, input_shape, 3);
  const int output_depth = MatchingDim(filter_backprop_shape, 3, incoming_shape, 3);
  const int input_height = input_shape.Dims(1);
  const int input_width = input_shape.Dims(2);
  const int filter_backprop_height = filter_backprop_shape.Dims(0);
  const int filter_backprop_width = filter_backprop_shape.Dims(1);
  const int incoming_height = incoming_shape.Dims(1);
  const int incoming_width = incoming_shape.Dims(2);
  if (dilation_rows != 1 || dilation_cols != 1)
    throw std::runtime_error("cker::ConvFilterGrad: not yet support dilation rates larger than 1.");
  LaunchConv2DBackpropFilterOp<float>()(
    incoming_data, batches, incoming_height, incoming_width, output_depth, input_data, input_height,
    input_width, input_depth, dilation_rows, dilation_cols, stride_rows, stride_cols, padding,
    padding_top, padding_bottom, padding_left, padding_right, filter_backprop_data,
    filter_backprop_height, filter_backprop_width);
}
References nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, nnfw::cker::Shape::Dims(), nnfw::cker::PaddingValues::height, nnfw::cker::MatchingDim(), nnfw::cker::ConvParams::padding_type, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
ConvInputGrad()
void nnfw::cker::train::ConvInputGrad (const ConvParams & params, const Shape & incoming_shape, const float * incoming_data, const Shape & filter_shape, const float * filter_data, const int padding_bottom, const int padding_right, const Shape & grad_shape, float * grad_data) inline
Definition at line 188 of file Conv.h.
{
  const int stride_rows = params.stride_height;
  const int stride_cols = params.stride_width;
  const PaddingType padding = params.padding_type;
  const int padding_top = params.padding_values.height;
  const int padding_left = params.padding_values.width;
  assert(padding_top >= 0);
  assert(padding_bottom >= 0);
  assert(padding_left >= 0);
  assert(padding_right >= 0);
  const int dilation_rows = params.dilation_height_factor;
  const int dilation_cols = params.dilation_width_factor;
  const int batches = MatchingDim(grad_shape, 0, incoming_shape, 0);
  const int input_depth = MatchingDim(filter_shape, 2, grad_shape, 3);
  const int output_depth = MatchingDim(filter_shape, 3, incoming_shape, 3);
  const int grad_height = grad_shape.Dims(1);
  const int grad_width = grad_shape.Dims(2);
  const int filter_height = filter_shape.Dims(0);
  const int filter_width = filter_shape.Dims(1);
  const int incoming_height = incoming_shape.Dims(1);
  const int incoming_width = incoming_shape.Dims(2);
  if (dilation_rows != 1 || dilation_cols != 1)
    throw std::runtime_error("cker::ConvFilterGrad: not yet support dilation rates larger than 1.");
  LaunchConv2DBackpropInputOp<float>()(
    incoming_data, batches, incoming_height, incoming_width, output_depth, filter_data,
    filter_height, filter_width, dilation_rows, dilation_cols, stride_rows, stride_cols, padding,
    padding_top, padding_bottom, padding_left, padding_right, grad_data, grad_height, grad_width,
    input_depth);
}
References nnfw::cker::ConvParams::dilation_height_factor, nnfw::cker::ConvParams::dilation_width_factor, nnfw::cker::Shape::Dims(), nnfw::cker::PaddingValues::height, nnfw::cker::MatchingDim(), nnfw::cker::ConvParams::padding_type, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
FullyConnectedBiasGrad()
template<typename T > void nnfw::cker::train::FullyConnectedBiasGrad (const Shape & incomming_shape, const T * incomming_data, const Shape & grad_shape, T * grad_data) inline
Definition at line 31 of file FullyConnected.h.
{
  const auto bias_size = grad_shape.FlatSize();
  if (bias_size != incomming_shape.Dims(incomming_shape.DimensionsCount() - 1) ||
      bias_size != grad_shape.Dims(0))
    throw std::runtime_error("cker::FullyConnectedBiasGrad: Unmatched shape");
  const auto in_mat = MapAsMatrixWithLastDimAsRows(incomming_data, incomming_shape);
  auto grad_mat = MapAsMatrixWithLastDimAsRows(grad_data, grad_shape);
  grad_mat = in_mat.rowwise().sum();
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::Shape::FlatSize(), and nnfw::cker::MapAsMatrixWithLastDimAsRows().
GradientDescent()
void nnfw::cker::train::GradientDescent (const Shape & output_shape, float * output_data, const Shape & grad_shape, const float * grad_data, float learning_rate) inline
Definition at line 33 of file SGD.h.
{
  Tensor output_tensor;
  Tensor grad_tensor;
  Tensor lr_tensor;
  output_tensor.shape.ReplaceWith(output_shape.DimensionsCount(), output_shape.DimsData());
  output_tensor.buffer = output_data;
  grad_tensor.shape.ReplaceWith(grad_shape.DimensionsCount(), grad_shape.DimsData());
  grad_tensor.buffer = const_cast<float *>(grad_data);
  std::vector<float> lr_vec{learning_rate};
  lr_tensor.buffer = lr_vec.data();
  if (output_shape != grad_shape)
    throw std::runtime_error(
      "cker::GradientDescent: output and gradient do not have the same shape");
  const training_ops::CPUDevice &device = *eigen_support::GetThreadPoolDevice();
  training_ops::functor::ApplyGradientDescent<training_ops::CPUDevice, float>()(
    device, output_tensor.flat<float>(), lr_tensor.scalar<float>(),
    static_cast<const Tensor &>(grad_tensor).flat<float>());
}
References nnfw::cker::Tensor::buffer, nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::DimsData(), nnfw::cker::eigen_support::GetThreadPoolDevice(), output_shape, nnfw::cker::Shape::ReplaceWith(), nnfw::cker::Tensor::scalar(), and nnfw::cker::Tensor::shape.
Referenced by onert::backend::train::optimizer::SGD::applyGradient().
log_threshold()
template<typename T > T nnfw::cker::train::log_threshold () inline
Definition at line 33 of file Loss.h.
{ return static_cast<T>(1e-20); }
MaxPool2D()
void nnfw::cker::train::MaxPool2D (const PoolParams & params, const Shape & input_shape, const float * input_data, const Shape & output_shape, float * output_data, int * arg_max_index) inline
Definition at line 36 of file MaxPool.h.
{
  assert(input_shape.DimensionsCount() == 4);
  assert(output_shape.DimensionsCount() == 4);
  assert(input_shape.Dims(0) == output_shape.Dims(0)); // MaxPool2D doesn't change batch
  assert(input_shape.Dims(3) == output_shape.Dims(3)); // MaxPool2D doesn't change depth
  const int batches = MatchingDim(input_shape, 0, output_shape, 0);
  const int input_height = input_shape.Dims(1);
  const int input_width = input_shape.Dims(2);
  const int output_height = output_shape.Dims(1);
  const int output_width = output_shape.Dims(2);
  const int filter_height = params.filter_height;
  const int filter_width = params.filter_width;
  const int pad_height = params.padding_values.height;
  const int pad_width = params.padding_values.width;
  const int stride_height = params.stride_height;
  const int stride_width = params.stride_width;
  const auto in_mat = MapAsMatrixWithLastDimAsRows(input_data, input_shape);
  auto out_mat = MapAsMatrixWithLastDimAsRows(output_data, output_shape);
  auto arg_max_index_mat = MapAsMatrixWithLastDimAsRows(arg_max_index, output_shape);
  // initialize output area
  std::fill(output_data, output_data + output_shape.FlatSize(), 0.0);
  std::fill(arg_max_index, arg_max_index + output_shape.FlatSize(), -1);
  // initialize projected area with lowest float
  const int h_start =
    (pad_height < filter_height) ? 0 : (pad_height - filter_height) / stride_height + 1;
  const int h_end = std::min((input_height + pad_height - 1) / stride_height + 1, output_height);
  const int w_start =
    (pad_width < filter_width) ? 0 : (pad_width - filter_width) / stride_width + 1;
  const int w_end = std::min((input_width + pad_width - 1) / stride_width + 1, output_width);
  for (int b = 0; b < batches; ++b)
  {
    for (int h_idx = h_start; h_idx < h_end; h_idx++)
    {
      for (int w_idx = w_start; w_idx < w_end; w_idx++)
      {
        const int offset = NodeOffset(b, h_idx, w_idx, output_height, output_width);
        out_mat.col(offset).setConstant(std::numeric_limits<float>::lowest());
      }
    }
  }
  for (int b = 0; b < batches; ++b)
  {
    for (int h = 0; h < input_height; ++h)
    {
      for (int w = 0; w < input_width; ++w)
      {
        // (h_start, h_end) * (w_start, w_end) is the range that the input
        // vector projects to.
        int hpad = h + pad_height;
        int wpad = w + pad_width;
        int h_start = (hpad < filter_height) ? 0 : (hpad - filter_height) / stride_height + 1;
        int h_end = std::min(hpad / stride_height + 1, output_height);
        int w_start = (wpad < filter_width) ? 0 : (wpad - filter_width) / stride_width + 1;
        int w_end = std::min(wpad / stride_width + 1, output_width);
        // compute elementwise sum
        for (int ph = h_start; ph < h_end; ++ph)
        {
          for (int pw = w_start; pw < w_end; ++pw)
          {
            const int out_offset = NodeOffset(b, ph, pw, output_height, output_width);
            const int in_offset = NodeOffset(b, h, w, input_height, input_width);
            const auto out_vector = out_mat.col(out_offset);
            const auto in_vector = in_mat.col(in_offset);
            // update arg_max_index_mat
            arg_max_index_mat.col(out_offset) =
              (out_vector.array() < in_vector.array())
                .select(in_offset, arg_max_index_mat.col(out_offset));
            // update out_mat
            out_mat.col(out_offset) = out_vector.cwiseMax(in_vector);
          }
        }
      }
    }
  }
  out_mat.cwiseMin(params.float_activation_min).cwiseMax(params.float_activation_max);
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::PoolParams::filter_height, nnfw::cker::PoolParams::filter_width, nnfw::cker::PoolParams::float_activation_max, nnfw::cker::PoolParams::float_activation_min, nnfw::cker::PaddingValues::height, nnfw::cker::MapAsMatrixWithLastDimAsRows(), nnfw::cker::MatchingDim(), nnfw::cker::NodeOffset(), offset(), output_shape, nnfw::cker::PoolParams::padding_values, nnfw::cker::PoolParams::stride_height, nnfw::cker::PoolParams::stride_width, and nnfw::cker::PaddingValues::width.
MaxPool2DGrad()
void nnfw::cker::train::MaxPool2DGrad (const Shape & incoming_shape, const float * incoming_data, const int * arg_max_index, const Shape & grad_shape, float * grad_data) inline
Definition at line 129 of file MaxPool.h.
{
  assert(grad_shape.DimensionsCount() == 4);
  assert(incoming_shape.DimensionsCount() == 4);
  // initialize grad_data
  std::fill(grad_data, grad_data + grad_shape.FlatSize(), 0.0);
  const int depth = MatchingDim(grad_shape, 3, incoming_shape, 3);
  const auto incoming_mat = MapAsMatrixWithLastDimAsRows(incoming_data, incoming_shape);
  auto arg_max_index_mat = MapAsMatrixWithLastDimAsRows(arg_max_index, incoming_shape);
  auto grad_mat = MapAsMatrixWithLastDimAsRows(grad_data, grad_shape);
  for (int col_index = 0; col_index < incoming_mat.cols(); col_index++)
  {
    auto arg_indices = arg_max_index_mat.col(col_index);
    for (int d = 0; d < depth; d++)
    {
      // output value is from padding, so nothing to propagate
      if (arg_indices(d) == -1)
        continue;
      grad_mat(d, arg_indices(d)) += incoming_mat(d, col_index);
    }
  }
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::FlatSize(), nnfw::cker::MapAsMatrixWithLastDimAsRows(), and nnfw::cker::MatchingDim().
MeanGrad()
template<typename T > void nnfw::cker::train::MeanGrad (const Shape & incoming_shape, const T * incoming_data, const Shape & grad_shape, T * grad_data)
Definition at line 32 of file ReduceMean.h.
{
  BroadcastTo(incoming_shape, const_cast<T *>(incoming_data), grad_shape, grad_data);
  const auto incoming = MapAsMatrixWithLastDimAsRows(incoming_data, incoming_shape);
  auto grad = MapAsMatrixWithLastDimAsRows(grad_data, grad_shape);
  grad /= (grad.size() / incoming.size());
}
References nnfw::cker::BroadcastTo(), and nnfw::cker::MapAsMatrixWithLastDimAsRows().
Referenced by onert::backend::train::ops::MeanLayer::backward().
MSE()
template<typename T > void nnfw::cker::train::MSE (const Shape & y_pred_shape, const T * y_pred_data, const Shape & y_true_shape, const T * y_true_data, const Shape & output_shape, T * output_data) inline
Definition at line 36 of file Loss.h.
{
  if (output_shape.DimensionsCount() != 1)
    throw std::runtime_error("cker::MSE: output dimension count should be 1");
  if (output_shape.Dims(0) != y_pred_shape.Dims(0))
    throw std::runtime_error("cker::MSE: output and y_pred do not have the same batch");
  if (y_pred_shape != y_true_shape)
    throw std::runtime_error("cker::MSE: y_pred_shape != y_true_shape");
  const auto batch = y_pred_shape.Dims(0);
  const auto size = FlatSizeSkipDim(y_pred_shape, 0);
  for (int b = 0; b < batch; ++b)
  {
    float sum = 0.f;
    for (int i = 0; i < size; ++i)
    {
      sum += square(y_pred_data[b * size + i] - y_true_data[b * size + i]);
    }
    output_data[b] = static_cast<T>(sum / size);
  }
}
References nnfw::cker::Shape::Dims(), nnfw::cker::FlatSizeSkipDim(), output_shape, size, and square().
Referenced by onert::backend::train::ops::LossMeanSquaredErrorLayer::forward().
MSEGrad()
template<typename T > void nnfw::cker::train::MSEGrad (const Shape & y_pred_shape, const T * y_pred_data, const Shape & y_true_shape, const T * y_true_data, const Shape & grad_shape, T * grad_data) inline
Definition at line 61 of file Loss.h.
{
  if (y_pred_shape != y_true_shape)
    throw std::runtime_error("cker::MSEGrad: y_pred_shape != y_true_shape");
  if (y_pred_shape != grad_shape)
    throw std::runtime_error("cker::MSEGrad: y_pred_shape != grad_shape");
  const int size = grad_shape.FlatSize();
  for (int i = 0; i < size; ++i)
  {
    grad_data[i] = static_cast<T>(-2 * (y_true_data[i] - y_pred_data[i]) / size);
  }
}
References nnfw::cker::Shape::FlatSize(), and size.
Referenced by onert::backend::train::ops::LossMeanSquaredErrorLayer::backward().
ReLU6Grad()
void nnfw::cker::train::ReLU6Grad (const Shape & output_shape, const float * output_data, const Shape & incoming_shape, const float * incoming_data, const Shape & grad_shape, float * grad_data) inline
Definition at line 31 of file ReLU6.h.
{
  const auto output_map = MapAsVector(output_data, output_shape);
  const auto incoming_map = MapAsVector(incoming_data, incoming_shape);
  auto grad_map = MapAsVector(grad_data, grad_shape);
  if (output_shape != incoming_shape || output_shape != grad_shape)
    throw std::runtime_error{"cker::ReLU6Grad: Unsupported shape"};
  grad_map.array() =
    incoming_map.array() *
    (0.0f < output_map.array() && output_map.array() < 6.0f).template cast<float>();
}
References nnfw::cker::MapAsVector(), and output_shape.
Referenced by onert::backend::train::ops::ElementwiseActivationLayer::configure().
ReLUGrad()
void nnfw::cker::train::ReLUGrad (const Shape & output_shape, const float * output_data, const Shape & incoming_shape, const float * incoming_data, const Shape & grad_shape, float * grad_data) inline
Definition at line 32 of file ReLU.h.
{
  const auto output_map = MapAsVector(output_data, output_shape);
  const auto incoming_map = MapAsVector(incoming_data, incoming_shape);
  auto grad_map = MapAsVector(grad_data, grad_shape);
  if (output_shape == incoming_shape && output_shape == grad_shape)
    grad_map.array() = incoming_map.array() * (output_map.array() > 0.0f).template cast<float>();
  else
    throw std::runtime_error("cker::ReLUGrad: Unsupported shape");
}
References nnfw::cker::MapAsVector(), and output_shape.
Referenced by onert::backend::train::ops::ElementwiseActivationLayer::configure().
SoftMaxGrad()
void nnfw::cker::train::SoftMaxGrad (const Shape & output_shape, const float * output_data, const Shape & incoming_shape, const float * incoming_data, const Shape & grad_shape, float * grad_data) inline
Definition at line 30 of file SoftMax.h.
{
  // TODO Support 4dim softmax gradient
  assert(incoming_shape.DimensionsCount() == 2);
  MatchingFlatSize(output_shape, incoming_shape, grad_shape);
  const int batches = incoming_shape.Dims(0);
  const int width = incoming_shape.Dims(1);
  for (int b = 0; b < batches; ++b)
  {
    int b_offset = b * width;
    for (int w1 = 0; w1 < width; ++w1)
    {
      float sum = 0.0f;
      for (int w2 = 0; w2 < width; ++w2)
      {
        float val;
        if (w1 == w2)
        {
          val = output_data[b_offset + w2] * (1.f - output_data[b_offset + w2]);
        }
        else
        {
          val = -output_data[b_offset + w2] * output_data[b_offset + w1];
        }
        val *= incoming_data[b_offset + w2];
        sum += val;
      }
      grad_data[b_offset + w1] = sum;
    }
  }
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::MatchingFlatSize(), and output_shape.
Referenced by onert::backend::train::ops::SoftMaxLayer::backward().
square()
template<typename T > T nnfw::cker::train::square (T value) inline
Definition at line 32 of file Loss.h.
{ return value * value; }
Referenced by MSE().