ONE - On-device Neural Engine: onert::backend::cpu Namespace Reference
onert::backend::cpu Namespace Reference
Namespaces
namespace ops
Data Structures
class Backend
class BackendContext
class Config
class ExternalContext
class KernelGenerator
class Validator
Typedefs
using StaticTensorManager = basic::StaticTensorManager
using Tensor = basic::Tensor
using ExternalTensor = basic::ExternalTensor
using TensorBuilder = basic::TensorBuilder
Functions
ops::ArithmeticType convertArithmeticType (ir::operation::BinaryArithmetic::ArithmeticType arithmetic_type_ir)
ops::ElementwiseActivationType convertElementwiseActivationType (ir::operation::ElementwiseActivation::Type type_ir)
ops::ElementwiseBinaryType convertElementwiseBinaryType (ir::operation::ElementwiseBinary::ElementwiseBinaryType type_ir)
ops::ElementwiseUnaryType convertElementwiseUnaryType (ir::operation::ElementwiseUnary::Type type_ir)
ops::PoolType convertPoolType (ir::operation::Pool2D::PoolType type_ir)
ops::ReduceType convertReduceType (ir::operation::Reduce::ReduceType reduce_type_ir)
ir::OperandIndexMap< ir::OperandIndex > findSharedMemoryOperandIndexes (const ir::IGraph &graph)
Typedef Documentation
ExternalTensor
using onert::backend::cpu::ExternalTensor = typedef basic::ExternalTensor
Definition at line 27 of file Tensor.h.
StaticTensorManager
using onert::backend::cpu::StaticTensorManager = typedef basic::StaticTensorManager
Definition at line 25 of file StaticTensorManager.h.
Tensor
using onert::backend::cpu::Tensor = typedef basic::Tensor
Definition at line 26 of file Tensor.h.
TensorBuilder
using onert::backend::cpu::TensorBuilder = typedef basic::TensorBuilder
Definition at line 25 of file TensorBuilder.h.
Function Documentation
convertArithmeticType()
ops::ArithmeticType onert::backend::cpu::convertArithmeticType (ir::operation::BinaryArithmetic::ArithmeticType arithmetic_type_ir)
Definition at line 30 of file BinaryArithmeticLayer.cc.
{
  switch (arithmetic_type_ir)
  {
    case ir::operation::BinaryArithmetic::ArithmeticType::ADD:
      return ops::ArithmeticType::kAdd;
    case ir::operation::BinaryArithmetic::ArithmeticType::SUB:
      return ops::ArithmeticType::kSub;
    case ir::operation::BinaryArithmetic::ArithmeticType::MUL:
      return ops::ArithmeticType::kMul;
    case ir::operation::BinaryArithmetic::ArithmeticType::DIV:
      return ops::ArithmeticType::kDiv;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::BinaryArithmetic::ADD, onert::ir::operation::BinaryArithmetic::DIV, onert::backend::cpu::ops::kAdd, onert::backend::cpu::ops::kDiv, onert::backend::cpu::ops::kMul, onert::backend::cpu::ops::kSub, onert::ir::operation::BinaryArithmetic::MUL, and onert::ir::operation::BinaryArithmetic::SUB.
convertElementwiseActivationType()
ops::ElementwiseActivationType onert::backend::cpu::convertElementwiseActivationType (ir::operation::ElementwiseActivation::Type type_ir)
Definition at line 37 of file ElementwiseActivationLayer.cc.
{
  switch (type_ir)
  {
    case ir::operation::ElementwiseActivation::Type::ELU:
      return ops::ElementwiseActivationType::kElu;
    case ir::operation::ElementwiseActivation::Type::LOGISTIC:
      return ops::ElementwiseActivationType::kLogistic;
    case ir::operation::ElementwiseActivation::Type::RELU:
      return ops::ElementwiseActivationType::kReLU;
    case ir::operation::ElementwiseActivation::Type::TANH:
      return ops::ElementwiseActivationType::kTanh;
    case ir::operation::ElementwiseActivation::Type::LEAKY_RELU:
      return ops::ElementwiseActivationType::kLeakyReLU;
    case ir::operation::ElementwiseActivation::Type::GELU:
      return ops::ElementwiseActivationType::kGELU;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::ElementwiseActivation::ELU, onert::ir::operation::ElementwiseActivation::GELU, onert::backend::cpu::ops::kElu, onert::backend::cpu::ops::kGELU, onert::backend::cpu::ops::kLeakyReLU, onert::backend::cpu::ops::kLogistic, onert::backend::cpu::ops::kReLU, onert::backend::cpu::ops::kTanh, onert::ir::operation::ElementwiseActivation::LEAKY_RELU, onert::ir::operation::ElementwiseActivation::LOGISTIC, onert::ir::operation::ElementwiseActivation::RELU, and onert::ir::operation::ElementwiseActivation::TANH.
convertElementwiseBinaryType()
ops::ElementwiseBinaryType onert::backend::cpu::convertElementwiseBinaryType (ir::operation::ElementwiseBinary::ElementwiseBinaryType type_ir)
Definition at line 35 of file ElementwiseBinaryLayer.cc.
{
  switch (type_ir)
  {
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::FLOOR_DIV:
      return ops::ElementwiseBinaryType::kFloorDiv;
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::FLOOR_MOD:
      return ops::ElementwiseBinaryType::kFloorMod;
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::LOGICAL_AND:
      return ops::ElementwiseBinaryType::kLogicalAnd;
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::LOGICAL_OR:
      return ops::ElementwiseBinaryType::kLogicalOr;
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::MAX:
      return ops::ElementwiseBinaryType::kMax;
    case ir::operation::ElementwiseBinary::ElementwiseBinaryType::MIN:
      return ops::ElementwiseBinaryType::kMin;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::ElementwiseBinary::FLOOR_DIV, onert::ir::operation::ElementwiseBinary::FLOOR_MOD, onert::backend::cpu::ops::kFloorDiv, onert::backend::cpu::ops::kFloorMod, onert::backend::cpu::ops::kLogicalAnd, onert::backend::cpu::ops::kLogicalOr, onert::backend::cpu::ops::kMax, onert::backend::cpu::ops::kMin, onert::ir::operation::ElementwiseBinary::LOGICAL_AND, onert::ir::operation::ElementwiseBinary::LOGICAL_OR, onert::ir::operation::ElementwiseBinary::MAX, and onert::ir::operation::ElementwiseBinary::MIN.
convertElementwiseUnaryType()
ops::ElementwiseUnaryType onert::backend::cpu::convertElementwiseUnaryType (ir::operation::ElementwiseUnary::Type type_ir)
Definition at line 36 of file ElementwiseUnaryLayer.cc.
{
  switch (type_ir)
  {
    case ir::operation::ElementwiseUnary::Type::ABS:
      return ops::ElementwiseUnaryType::kAbs;
    case ir::operation::ElementwiseUnary::Type::CAST:
      return ops::ElementwiseUnaryType::kCast;
    case ir::operation::ElementwiseUnary::Type::COS:
      return ops::ElementwiseUnaryType::kCos;
    case ir::operation::ElementwiseUnary::Type::DEQUANTIZE:
      return ops::ElementwiseUnaryType::kDequantize;
    case ir::operation::ElementwiseUnary::Type::ERF:
      return ops::ElementwiseUnaryType::kErf;
    case ir::operation::ElementwiseUnary::Type::EXP:
      return ops::ElementwiseUnaryType::kExp;
    case ir::operation::ElementwiseUnary::Type::FLOOR:
      return ops::ElementwiseUnaryType::kFloor;
    case ir::operation::ElementwiseUnary::Type::LOG:
      return ops::ElementwiseUnaryType::kLog;
    case ir::operation::ElementwiseUnary::Type::LOGICAL_NOT:
      return ops::ElementwiseUnaryType::kLogicalNot;
    case ir::operation::ElementwiseUnary::Type::NEG:
      return ops::ElementwiseUnaryType::kNeg;
    case ir::operation::ElementwiseUnary::Type::QUANTIZE:
      return ops::ElementwiseUnaryType::kQuantize;
    case ir::operation::ElementwiseUnary::Type::ROUND:
      return ops::ElementwiseUnaryType::kRound;
    case ir::operation::ElementwiseUnary::Type::RSQRT:
      return ops::ElementwiseUnaryType::kRSqrt;
    case ir::operation::ElementwiseUnary::Type::SIN:
      return ops::ElementwiseUnaryType::kSin;
    case ir::operation::ElementwiseUnary::Type::SQRT:
      return ops::ElementwiseUnaryType::kSqrt;
    case ir::operation::ElementwiseUnary::Type::SQUARE:
      return ops::ElementwiseUnaryType::kSquare;
    case ir::operation::ElementwiseUnary::Type::ZEROS_LIKE:
      return ops::ElementwiseUnaryType::kZerosLike;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::ElementwiseUnary::ABS, onert::ir::operation::ElementwiseUnary::CAST, onert::ir::operation::ElementwiseUnary::COS, onert::ir::operation::ElementwiseUnary::DEQUANTIZE, onert::ir::operation::ElementwiseUnary::ERF, onert::ir::operation::ElementwiseUnary::EXP, onert::ir::operation::ElementwiseUnary::FLOOR, onert::backend::cpu::ops::kAbs, onert::backend::cpu::ops::kCast, onert::backend::cpu::ops::kCos, onert::backend::cpu::ops::kDequantize, onert::backend::cpu::ops::kErf, onert::backend::cpu::ops::kExp, onert::backend::cpu::ops::kFloor, onert::backend::cpu::ops::kLog, onert::backend::cpu::ops::kLogicalNot, onert::backend::cpu::ops::kNeg, onert::backend::cpu::ops::kQuantize, onert::backend::cpu::ops::kRound, onert::backend::cpu::ops::kRSqrt, onert::backend::cpu::ops::kSin, onert::backend::cpu::ops::kSqrt, onert::backend::cpu::ops::kSquare, onert::backend::cpu::ops::kZerosLike, onert::ir::operation::ElementwiseUnary::LOG, onert::ir::operation::ElementwiseUnary::LOGICAL_NOT, onert::ir::operation::ElementwiseUnary::NEG, onert::ir::operation::ElementwiseUnary::QUANTIZE, onert::ir::operation::ElementwiseUnary::ROUND, onert::ir::operation::ElementwiseUnary::RSQRT, onert::ir::operation::ElementwiseUnary::SIN, onert::ir::operation::ElementwiseUnary::SQRT, onert::ir::operation::ElementwiseUnary::SQUARE, and onert::ir::operation::ElementwiseUnary::ZEROS_LIKE.
convertPoolType()
ops::PoolType onert::backend::cpu::convertPoolType (ir::operation::Pool2D::PoolType type_ir)
Definition at line 32 of file Pool2DLayer.cc.
{
  switch (type_ir)
  {
    case ir::operation::Pool2D::PoolType::AVG:
      return ops::PoolType::kAvg;
    case ir::operation::Pool2D::PoolType::MAX:
      return ops::PoolType::kMax;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::Pool2D::AVG, onert::backend::cpu::ops::kAvg, onert::backend::cpu::ops::kMax, and onert::ir::operation::Pool2D::MAX.
convertReduceType()
ops::ReduceType onert::backend::cpu::convertReduceType (ir::operation::Reduce::ReduceType reduce_type_ir)
Definition at line 32 of file ReduceLayer.cc.
{
  switch (reduce_type_ir)
  {
    case ir::operation::Reduce::ReduceType::ALL:
      return ops::ReduceType::kAll;
    case ir::operation::Reduce::ReduceType::ANY:
      return ops::ReduceType::kAny;
    case ir::operation::Reduce::ReduceType::MAX:
      return ops::ReduceType::kMax;
    case ir::operation::Reduce::ReduceType::MIN:
      return ops::ReduceType::kMin;
    case ir::operation::Reduce::ReduceType::PROD:
      return ops::ReduceType::kProd;
    case ir::operation::Reduce::ReduceType::SUM:
      return ops::ReduceType::kSum;
    default:
      throw std::runtime_error("cpu KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::Reduce::ALL, onert::ir::operation::Reduce::ANY, onert::backend::cpu::ops::kAll, onert::backend::cpu::ops::kAny, onert::backend::cpu::ops::kMax, onert::backend::cpu::ops::kMin, onert::backend::cpu::ops::kProd, onert::backend::cpu::ops::kSum, onert::ir::operation::Reduce::MAX, onert::ir::operation::Reduce::MIN, onert::ir::operation::Reduce::PROD, and onert::ir::operation::Reduce::SUM.
findSharedMemoryOperandIndexes()
ir::OperandIndexMap< ir::OperandIndex > onert::backend::cpu::findSharedMemoryOperandIndexes (const ir::IGraph & graph)
Definition at line 73 of file SharedMemoryOperands.cc.
{
  ir::OperandIndexMap<ir::OperandIndex> shared_memory_operand_map;
  graph.operations().iterate([&](const ir::OperationIndex &, const ir::IOperation &op) {
    if (is_memory_sharing_allowed(graph, op))
    {
      assert(op.getInputs().size() == 1 || op.getInputs().size() == 2);
      assert(op.getOutputs().size() == 1);
      shared_memory_operand_map[op.getOutputs().at(0)] = op.getInputs().at(0);
    }
  });
  reassign_indexes_to_single_sources(shared_memory_operand_map);
  return shared_memory_operand_map;
}
References onert::ir::OperandIndexSequence::at(), onert::ir::IOperation::getInputs(), onert::ir::IOperation::getOutputs(), and onert::ir::OperandIndexSequence::size().
Referenced by onert::backend::cpu::Backend::newContext().