ONE - On-device Neural Engine: mio::circle Namespace Reference
mio::circle Namespace Reference
Data Structures
class Reader
Loads Circle file and provides helpers to access attributes.
Functions
bool is_valid (const ::circle::OperatorCode *opcode)
bool is_custom (const ::circle::OperatorCode *opcode)
std::string opcode_name (const ::circle::OperatorCode *opcode)
const char * tensor_type (const ::circle::Tensor *tensor)
const char * tensor_name (const ::circle::Tensor *tensor)
::circle::BuiltinOperator builtin_code_neutral (const ::circle::OperatorCode *opcode)
template<typename T >
std::vector< T > as_index_vector (const flatbuffers::Vector< T > *flat_array)
Function Documentation
as_index_vector()
template<typename T > std::vector< T > mio::circle::as_index_vector (const flatbuffers::Vector< T > * flat_array)
Definition at line 36 of file Helper.h.
{
  if (flat_array == nullptr)
  {
    throw std::runtime_error("flat array is nullptr");
  }
  std::vector<T> ret(flat_array->Length());
  for (uint32_t i = 0; i < flat_array->Length(); i++)
  {
    ret[i] = flat_array->Get(i);
  }
  return ret;
}
Referenced by circledump::dump_sub_graph(), circledump::ReshapePrinter::options(), mio::circle::Reader::outputs(), circleinspect::DumpConv2DWeight::run(), and mio::circle::Reader::select_subgraph().
builtin_code_neutral()
circle::BuiltinOperator mio::circle::builtin_code_neutral (const ::circle::OperatorCode * opcode)
This will provide v3/v3a/v3b format neutral BuiltinOperator NOTE circle has minus value opcode (252~254 as uint8_t) we cannot use std::max() like tflite as deprecated_builtin_code can be minus and builtin_code being 0 for v0.3 files.
Definition at line 33 of file Helper.cpp.
{
  assert(opcode != nullptr);
  if (opcode->deprecated_builtin_code() == 127)
  {
    assert(opcode->builtin_code() >= 127);
    return opcode->builtin_code();
  }
  // There was no 255(-1) value in v0.3
  assert(opcode->deprecated_builtin_code() != -1);
  return static_cast<::circle::BuiltinOperator>(opcode->deprecated_builtin_code());
}
Referenced by mio::circle::Reader::builtin_code(), circlechef::CircleImport::builtin_code(), and luci::CircleReader::builtin_code().
is_custom()
bool mio::circle::is_custom (const ::circle::OperatorCode * opcode)
Definition at line 32 of file Helper.cpp.
{
  ::circle::BuiltinOperator code = opcode->builtin_code();
  return (code == ::circle::BuiltinOperator_CUSTOM);
}
Referenced by opcode_name(), and circlechef::CircleImport::opcode_name().
is_valid()
bool mio::circle::is_valid (const ::circle::OperatorCode * opcode)
Definition at line 26 of file Helper.cpp.
{
  ::circle::BuiltinOperator code = opcode->builtin_code();
  return (::circle::BuiltinOperator_MIN <= code && code <= ::circle::BuiltinOperator_MAX);
}
Referenced by mio::circle::Reader::opcode_name(), opcode_name(), and circlechef::CircleImport::opcode_name().
opcode_name()
std::string mio::circle::opcode_name (const ::circle::OperatorCode * opcode)
Definition at line 38 of file Helper.cpp.
{
  assert(opcode);
  if (!is_valid(opcode))
  {
    std::ostringstream oss;
    oss << "(invalid)";
    return oss.str();
  }
  if (is_custom(opcode))
  {
    if (!opcode->custom_code())
      return "(invalid custom)";
    std::string custom_op = "CUSTOM(";
    custom_op += opcode->custom_code()->c_str();
    custom_op += ")";
    return custom_op;
  }
  ::circle::BuiltinOperator code = opcode->builtin_code();
  return ::circle::EnumNameBuiltinOperator(code);
}
References is_custom(), and is_valid().
Referenced by circledump::dump_model(), mio::circle::Reader::opcode_name(), and luci::CircleReader::opcode_name().
tensor_name()
const char * mio::circle::tensor_name (const ::circle::Tensor * tensor)
Definition at line 69 of file Helper.cpp.
{
  static const char *kEmptyTensorName = "(noname)";
  auto name = tensor->name();
  if (name)
    return name->c_str();
  return kEmptyTensorName;
}
Referenced by circledump::dump_sub_graph(), circlechef::generate_recipe(), circlechef::set_inputs(), circlechef::set_outputs(), and mio::circle::Reader::tensor_name().
tensor_type()
const char * mio::circle::tensor_type (const ::circle::Tensor * tensor)
Definition at line 64 of file Helper.cpp.
{
  return ::circle::EnumNameTensorType(tensor->type());
}
Referenced by circledump::dump_sub_graph(), and mio::circle::Reader::tensor_dtype().