ONE - On-device Neural Engine: benchmark Namespace Reference
benchmark Namespace Reference
Data Structures
class CsvWriter
class MemoryPoller
struct Phase
struct PhaseOption
class Phases
class Result
Enumerations
enum MemoryType { RSS , HWM , PSS , END_OF_MEM_TYPE }
enum PhaseEnum {
MODEL_LOAD , PREPARE , WARMUP , EXECUTE ,
END_OF_PHASE
}
enum FigureType {
MEAN , MAX , MIN , GEOMEAN ,
END_OF_FIG_TYPE
}
Functions
bool prepareVmRSS ()
bool prepareVmHWM ()
bool prepareGpuMemory ()
bool preparePssSum ()
uint32_t getVmRSS ()
uint32_t getVmHWM ()
uint32_t getGpuMemory (const std::string &process_name)
uint32_t getPssSum ()
std::string getProcessName ()
void printResult (const Result &result)
void writeResult (const Result &result, const std::string &exec, const std::string &model, const std::string &backend)
std::string getMemoryTypeString (MemoryType type)
std::string getMemoryTypeString (int type)
std::string getPhaseString (PhaseEnum phase)
std::string getPhaseString (int phase)
PhaseEnum getPhaseEnum (const std::string &phase)
std::string getFigureTypeString (FigureType type)
std::string getFigureTypeString (int type)
CsvWriter & operator<< (CsvWriter &csvw, const std::string &val)
CsvWriter & operator<< (CsvWriter &csvw, double val)
CsvWriter & operator<< (CsvWriter &csvw, uint32_t val)
CsvWriter & operator<< (CsvWriter &csvw, char val)
Variables
const std::vector< std::string > gPhaseStrings {"MODEL_LOAD", "PREPARE", "WARMUP", "EXECUTE"}
Enumeration Type Documentation
FigureType
enum benchmark::FigureType
Enumerator
MEAN
MAX
MIN
GEOMEAN
END_OF_FIG_TYPE
Definition at line 100 of file Types.h.
{
  MEAN,
  MAX,
  MIN,
  GEOMEAN,
  END_OF_FIG_TYPE
};
MemoryType
enum benchmark::MemoryType
Enumerator
RSS
HWM
PSS
END_OF_MEM_TYPE
Definition at line 26 of file Types.h.
{
  RSS,
  HWM,
  PSS,
  END_OF_MEM_TYPE
};
PhaseEnum
enum benchmark::PhaseEnum
Enumerator
MODEL_LOAD
PREPARE
WARMUP
EXECUTE
END_OF_PHASE
Definition at line 54 of file Types.h.
{
  MODEL_LOAD,
  PREPARE,
  WARMUP,
  EXECUTE,
  END_OF_PHASE,
};
Function Documentation
getFigureTypeString() [1/2]
std::string benchmark::getFigureTypeString (FigureType type) inline
Definition at line 109 of file Types.h.
{
  switch (type)
  {
    case MEAN:
      return "MEAN";
    case MAX:
      return "MAX";
    case MIN:
      return "MIN";
    case GEOMEAN:
      return "GEOMEAN";
    default:
      return "END_OF_FIG_TYPE";
  }
}
References GEOMEAN, MAX, MEAN, and MIN.
Referenced by getFigureTypeString().
getFigureTypeString() [2/2]
std::string benchmark::getFigureTypeString (int type) inline
Definition at line 126 of file Types.h.
{
  return getFigureTypeString(static_cast<FigureType>(type));
}
References getFigureTypeString().
getGpuMemory()
uint32_t benchmark::getGpuMemory (const std::string & process_name)
Definition at line 149 of file MemoryInfo.cpp.
{
  assert(!process_name.empty());
  auto val = getValueFromFileStatus(gpu_memory_path, process_name);
  if (val.size() == 0)
    return 0;
  // process_name -> pid -> gpu_mem -> max_gpu_mem
  assert(isStrNumber(val[2]));
  return std::stoul(val[2]);
}
Referenced by benchmark::MemoryPoller::end().
getMemoryTypeString() [1/2]
std::string benchmark::getMemoryTypeString (int type) inline
Definition at line 49 of file Types.h.
{
  return getMemoryTypeString(static_cast<MemoryType>(type));
}
References getMemoryTypeString().
getMemoryTypeString() [2/2]
std::string benchmark::getMemoryTypeString (MemoryType type) inline
Definition at line 34 of file Types.h.
{
  switch (type)
  {
    case MemoryType::RSS:
      return "RSS";
    case MemoryType::HWM:
      return "HWM";
    case MemoryType::PSS:
      return "PSS";
    default:
      return "END_OF_MEM_TYPE";
  }
}
References HWM, PSS, and RSS.
Referenced by getMemoryTypeString().
getPhaseEnum()
PhaseEnum benchmark::getPhaseEnum (const std::string & phase) inline
Definition at line 85 of file Types.h.
{
  if (phase.compare("MODEL_LOAD") == 0)
    return PhaseEnum::MODEL_LOAD;
  if (phase.compare("PREPARE") == 0)
    return PhaseEnum::PREPARE;
  if (phase.compare("WARMUP") == 0)
    return PhaseEnum::WARMUP;
  if (phase.compare("EXECUTE") == 0)
    return PhaseEnum::EXECUTE;
  return PhaseEnum::END_OF_PHASE;
}
References END_OF_PHASE, EXECUTE, MODEL_LOAD, PREPARE, and WARMUP.
getPhaseString() [1/2]
std::string benchmark::getPhaseString (int phase) inline
Definition at line 80 of file Types.h.
{
  return getPhaseString(static_cast<PhaseEnum>(phase));
}
References getPhaseString().
getPhaseString() [2/2]
std::string benchmark::getPhaseString (PhaseEnum phase) inline
Definition at line 63 of file Types.h.
{
  switch (phase)
  {
    case PhaseEnum::MODEL_LOAD:
      return "MODEL_LOAD";
    case PhaseEnum::PREPARE:
      return "PREPARE";
    case PhaseEnum::WARMUP:
      return "WARMUP";
    case PhaseEnum::EXECUTE:
      return "EXECUTE";
    default:
      return "END_OF_PHASE";
  }
}
References EXECUTE, MODEL_LOAD, PREPARE, and WARMUP.
Referenced by benchmark::MemoryPoller::end(), getPhaseString(), and benchmark::MemoryPoller::start().
getProcessName()
std::string benchmark::getProcessName ()
Definition at line 162 of file MemoryInfo.cpp.
{
  auto val = getValueFromFileStatus(proc_status_path, "Name");
  assert(val.size() >= 2);
  return val[1];
}
getPssSum()
uint32_t benchmark::getPssSum ()
Definition at line 160 of file MemoryInfo.cpp.
{ return getSumValueFromFileSmaps(proc_smaps_path, "Pss"); }
Referenced by benchmark::MemoryPoller::end().
getVmHWM()
uint32_t benchmark::getVmHWM ()
Definition at line 139 of file MemoryInfo.cpp.
{
  auto val = getValueFromFileStatus(proc_status_path, "VmHWM");
  if (val.size() == 0)
    return 0;
  // key: value
  assert(isStrNumber(val[1]));
  return std::stoul(val[1]);
}
Referenced by benchmark::MemoryPoller::end(), and benchmark::Phases::Phases().
getVmRSS()
uint32_t benchmark::getVmRSS ()
Definition at line 130 of file MemoryInfo.cpp.
{
  auto val = getValueFromFileStatus(proc_status_path, "VmRSS");
  if (val.size() == 0)
    return 0;
  assert(isStrNumber(val[1]));
  return std::stoul(val[1]);
}
Referenced by benchmark::MemoryPoller::end().
operator<<() [1/4]
CsvWriter & benchmark::operator<< (CsvWriter & csvw, char val)
Definition at line 117 of file CsvWriter.cpp.
{
  csvw.write(val);
  return csvw;
}
operator<<() [2/4]
CsvWriter & benchmark::operator<< (CsvWriter & csvw, const std::string & val)
Definition at line 99 of file CsvWriter.cpp.
{
  csvw.write(val);
  return csvw;
}
operator<<() [3/4]
CsvWriter & benchmark::operator<< (CsvWriter & csvw, double val)
Definition at line 105 of file CsvWriter.cpp.
{
  csvw.write(val);
  return csvw;
}
operator<<() [4/4]
CsvWriter & benchmark::operator<< (CsvWriter & csvw, uint32_t val)
Definition at line 111 of file CsvWriter.cpp.
{
  csvw.write(val);
  return csvw;
}
prepareGpuMemory()
bool benchmark::prepareGpuMemory ()
Definition at line 126 of file MemoryInfo.cpp.
{ return std::ifstream(gpu_memory_path).is_open(); }
preparePssSum()
bool benchmark::preparePssSum ()
Definition at line 128 of file MemoryInfo.cpp.
{ return std::ifstream(proc_smaps_path).is_open(); }
prepareVmHWM()
bool benchmark::prepareVmHWM ()
Definition at line 124 of file MemoryInfo.cpp.
{ return std::ifstream(proc_status_path).is_open(); }
prepareVmRSS()
bool benchmark::prepareVmRSS ()
Definition at line 122 of file MemoryInfo.cpp.
{ return std::ifstream(proc_status_path).is_open(); }
Referenced by benchmark::Phases::Phases().
printResult()
void benchmark::printResult (const Result & result)
Definition at line 191 of file Result.cpp.
{
  printResultTime(result.time);
  if (result.print_memory == false)
    return;
  printResultMemory(result.memory);
  printUsedPeakMemory(result.init_memory, result.peak_memory);
}
References benchmark::Result::init_memory, benchmark::Result::memory, benchmark::Result::peak_memory, benchmark::Result::print_memory, and benchmark::Result::time.
writeResult()
void benchmark::writeResult (const Result & result, const std::string & exec, const std::string & model, const std::string & backend)
Definition at line 204 of file Result.cpp.
{
  std::string csv_filename = exec + "-" + model + "-" + backend + ".csv";
  // write to csv
  CsvWriter writer(csv_filename);
  writer << model << backend;
  // TODO Add GEOMEAN
  // time
  auto time = result.time;
  writer << time[PhaseEnum::MODEL_LOAD][FigureType::MEAN]
         << time[PhaseEnum::PREPARE][FigureType::MEAN] << time[PhaseEnum::EXECUTE][FigureType::MIN]
         << time[PhaseEnum::EXECUTE][FigureType::MAX] << time[PhaseEnum::EXECUTE][FigureType::MEAN];
  // memory
  auto memory = result.memory;
  for (int j = MemoryType::RSS; j <= MemoryType::PSS; ++j)
  {
    // Tricky. Handle WARMUP as EXECUTE
    for (int i = PhaseEnum::MODEL_LOAD; i <= PhaseEnum::WARMUP; ++i)
    {
      writer << memory[i][j];
    }
    writer << peakMemory(memory, j);
  }
  bool done = writer.done();
  if (!done)
  {
    std::cerr << "Writing to " << csv_filename << " is failed" << std::endl;
  }
}
References benchmark::CsvWriter::done(), EXECUTE, MAX, MEAN, benchmark::Result::memory, MIN, MODEL_LOAD, PREPARE, PSS, RSS, benchmark::Result::time, and WARMUP.
Variable Documentation
gPhaseStrings
const std::vector<std::string> benchmark::gPhaseStrings {"MODEL_LOAD", "PREPARE", "WARMUP", "EXECUTE"}
Definition at line 98 of file Types.h.
Referenced by benchmark::Result::Result().