ONE - On-device Neural Engine: compare_tensors Namespace Reference
compare_tensors Namespace Reference
Functions
def compare_fake_quantization (tensor, tensor_name, expect_dir)
def compare_record_minmax (tensor, tensor_name, expect_dir)
def compare_quantization (tensor, tensor_name, expect_dir)
Variables
parser = argparse.ArgumentParser()
type
str
required
args = parser.parse_args()
list supported_modes = ["fake_quantization", "record_minmax", "quantization"]
model = args.input_h5
expect_dir = args.expect_dir
mode = args.mode
int failed_cases = 0
Function Documentation
compare_fake_quantization()
def compare_tensors.compare_fake_quantization (tensor, tensor_name, expect_dir)
Definition at line 34 of file compare_tensors.py.
def compare_fake_quantization(tensor, tensor_name, expect_dir):
    global failed_cases
    with open(expect_dir + "/" + tensor_name + ".json", "r") as expect_file:
        json_load = json.load(expect_file)
    expected_weights = np.array(json_load["weights"])
    input_weights = tensor["weights"][:]
    if np.allclose(input_weights, expected_weights, rtol=1.e-5, atol=1.e-5) == False:
        print("Fake-quantized weights of " + tensor_name + " (" + str(input_weights) +
              ") do not match with expected value (" + str(expected_weights) + ").")
        failed_cases += 1
References str.
Referenced by compare_quantization().
compare_quantization()
def compare_tensors.compare_quantization (tensor, tensor_name, expect_dir)
Definition at line 64 of file compare_tensors.py.
def compare_quantization(tensor, tensor_name, expect_dir):
    global failed_cases
    with open(expect_dir + "/" + tensor_name + ".json", "r") as expect_file:
        json_load = json.load(expect_file)
    for key in json_load:
        if key == "weights":
            expected_weights = np.array(json_load["weights"])
            input_weights = tensor["weights"][()]
            abs_tolerance = 1
            # We use higher tolerance for int64 data (bias of int16-quantized model)
            if tensor["weights"].dtype == 'int64':
                abs_tolerance = 5
            if np.allclose(
                    input_weights, expected_weights, rtol=0, atol=abs_tolerance) == False:
                print("Quantized weights of " + tensor_name + " (" + str(input_weights) +
                      ") do not match with expected value (" + str(expected_weights) +
                      ").")
                failed_cases += 1
        if key == "scale":
            expected_scale = np.array(json_load["scale"])
            input_scale = tensor["scale"][:]
            if np.allclose(input_scale, expected_scale, rtol=1.e-5, atol=1.e-5) == False:
                print("Quantized scale of " + tensor_name + " (" + str(input_scale) +
                      ") do not match with expected value (" + str(expected_scale) + ").")
                failed_cases += 1
        if key == "zero_point":
            expected_zero_point = np.array(json_load["zero_point"])
            input_zero_point = tensor["zero_point"][:]
            if np.allclose(
                    input_zero_point, expected_zero_point, rtol=0, atol=1) == False:
                print("Quantized zero_point of " + tensor_name + " (" +
                      str(input_zero_point) + ") do not match with expected value (" +
                      str(expected_zero_point) + ").")
                failed_cases += 1
References compare_fake_quantization(), compare_quantization(), compare_record_minmax(), and str.
Referenced by compare_quantization().
compare_record_minmax()
def compare_tensors.compare_record_minmax (tensor, tensor_name, expect_dir)
Definition at line 46 of file compare_tensors.py.
def compare_record_minmax(tensor, tensor_name, expect_dir):
    global failed_cases
    with open(expect_dir + "/" + tensor_name + ".json", "r") as expect_file:
        json_load = json.load(expect_file)
    expected_min = np.array(json_load["min"])
    expected_max = np.array(json_load["max"])
    input_min = tensor["min"][:]
    input_max = tensor["max"][:]
    if np.allclose(input_min, expected_min, rtol=1.e-5, atol=1.e-5) == False:
        print("Recorded min of " + tensor_name + " (" + str(input_min) +
              ") does not match with expected value (" + str(expected_min) + ").")
        failed_cases += 1
    if np.allclose(input_max, expected_max, rtol=1.e-5, atol=1.e-5) == False:
        print("Recorded max of " + tensor_name + " (" + str(input_max) +
              ") does not match with expected value (" + str(expected_max) + ").")
        failed_cases += 1
References str.
Referenced by compare_quantization().
Variable Documentation
args
compare_tensors.args = parser.parse_args()
Definition at line 20 of file compare_tensors.py.
expect_dir
compare_tensors.expect_dir = args.expect_dir
Definition at line 25 of file compare_tensors.py.
failed_cases
int compare_tensors.failed_cases = 0
Definition at line 28 of file compare_tensors.py.
mode
compare_tensors.mode = args.mode
Definition at line 26 of file compare_tensors.py.
model
compare_tensors.model = args.input_h5
Definition at line 24 of file compare_tensors.py.
parser
compare_tensors.parser = argparse.ArgumentParser()
Definition at line 16 of file compare_tensors.py.
required
compare_tensors.required
Definition at line 17 of file compare_tensors.py.
str
compare_tensors.str
Definition at line 17 of file compare_tensors.py.
Referenced by compare_fake_quantization(), compare_quantization(), and compare_record_minmax().
supported_modes
list compare_tensors.supported_modes = ["fake_quantization", "record_minmax", "quantization"]
Definition at line 22 of file compare_tensors.py.
type
compare_tensors.type
Definition at line 17 of file compare_tensors.py.