ONE - On-device Neural Engine: luci_interpreter_pal::lstm_internal Namespace Reference
luci_interpreter_pal::lstm_internal Namespace Reference
Data Structures
struct LstmSizeInfo
class LstmStepManager
Functions
template<typename T >
T activationFunctionWithMinMax (T x, T output_activation_min, T output_activation_max)
template<typename T >
void mul (const luci_interpreter::lstm::ArithmeticParams *params, const tflite::RuntimeShape &input1_shape, const T *input1_data, const tflite::RuntimeShape &input2_shape, const T *input2_data, const tflite::RuntimeShape &output_shape, T *output_data)
int32_t multiplyByQuantizedMultiplier (int32_t x, int32_t quantized_multiplier, int shift)
template<typename InputType , typename WeightType , typename OutputType , typename BiasType >
void fullyConnectedInteger (const tflite::FullyConnectedParams &params, const tflite::RuntimeShape &input_shape, const InputType *input_data, const tflite::RuntimeShape &filter_shape, const WeightType *filter_data, const tflite::RuntimeShape &bias_shape, const BiasType *bias_data, const tflite::RuntimeShape &output_shape, OutputType *output_data)
void fullyConnected (const tflite::FullyConnectedParams &params, const tflite::RuntimeShape &input_shape, const int8_t *input_data, const tflite::RuntimeShape &filter_shape, const int8_t *filter_data, const tflite::RuntimeShape &bias_shape, const int32_t *bias_data, const tflite::RuntimeShape &output_shape, int16_t *output_data)
void fullyConnected (const tflite::FullyConnectedParams &params, const tflite::RuntimeShape &input_shape, const int16_t *input_data, const tflite::RuntimeShape &filter_shape, const int8_t *filter_data, const tflite::RuntimeShape &bias_shape, const int64_t *bias_data, const tflite::RuntimeShape &output_shape, int16_t *output_data)
template<typename InputType , typename OutputType >
void mulElementwise (int size, const luci_interpreter::lstm::ArithmeticParams *params, const InputType *input1_data, const InputType *input2_data, OutputType *output_data)
void mul (const tflite::RuntimeShape &shape, const luci_interpreter::lstm::ArithmeticParams *params, const int16_t *input1_data, const int16_t *input2_data, int8_t *output_data)
void mul (const tflite::RuntimeShape &shape, const luci_interpreter::lstm::ArithmeticParams *params, const int16_t *input1_data, const int16_t *input2_data, int16_t *output_data)
void addElementWise (const int16_t *input_1, const int16_t *input_2, int n_batch, int n_input, int16_t *output)
void tanh (int32_t cell_state_scale_power, const tflite::RuntimeShape &input_data_shape, int16_t *input_data, const tflite::RuntimeShape &output_data_shape, int16_t *output_data)
void sigmoid (const tflite::RuntimeShape &data_shape, int16_t *data)
void clipping (const int v_size, const luci_interpreter::lstm::CellStateInfo *cell_state_info, int16_t *vector)
void fullyConnected (const tflite::FullyConnectedParams &params, const tflite::RuntimeShape &input_shape, const float *input_data, const tflite::RuntimeShape &filter_shape, const float *filter_data, const tflite::RuntimeShape &bias_shape, const float *bias_data, const tflite::RuntimeShape &output_shape, float *output_data)
void mul (const tflite::RuntimeShape &shape, const luci_interpreter::lstm::ArithmeticParams *params, const float *input1_data, const float *input2_data, float *output_data)
void addElementWise (const float *input_1, const float *input_2, int n_batch, int n_input, float *output)
void tanh (int32_t cell_state_scale_power, const tflite::RuntimeShape &input_data_shape, float *input_data, const tflite::RuntimeShape &output_data_shape, float *output_data)
void sigmoid (const tflite::RuntimeShape &data_shape, float *data)
void clipping (const int v_size, const luci_interpreter::lstm::CellStateInfo *cell_state_info, float *vector)
template<typename ActivationType , typename WeightType , typename CellType , typename BiasType >
void calculateLstmGate (const LstmStepManager *step_info, const luci_interpreter::lstm::GateParameters *gate_params, ActivationType *input_data, const circle::Tensor *input_weight, const circle::Tensor *input_bias, ActivationType *recurrent_data, const circle::Tensor *recurrent_weight, const circle::Tensor *recurrent_bias, CellType *gate_output, CellType *fc_output_buffer, const TfLiteFusedActivation activation, luci_interpreter::BaseRuntimeGraph *runtime_graph)
template<typename CellType , typename ActivationType >
void updateLstmHidden (const LstmStepManager *step_info, CellType *cell_state_data_base, ActivationType *hidden_state_data, const CellType *output_gate_output, const luci_interpreter::lstm::ArithmeticParams *mul_params, int32_t cell_state_scale_power, CellType *buffer)
template<typename CellType >
void updateLstmCell (const LstmStepManager *step_info, CellType *cell_state_data, CellType *forget_gate_output, const CellType *input_gate_output, const CellType *cell_gate_output, const luci_interpreter::lstm::ArithmeticParams &forget_cell_mul_params, const luci_interpreter::lstm::ArithmeticParams &input_mul_params, const luci_interpreter::lstm::CellStateInfo *cell_state_info, CellType *buffer)
template<typename ActivationType , typename WeightType , typename CellType , typename BiasType >
void lstmStep (luci_interpreter::lstm::LSTMStruct *lstm_struct, luci_interpreter::lstm::LSTMParameters *lstm_params, LstmStepManager *step_info, luci_interpreter::lstm::CellStateInfo *cell_state_info, ActivationType *output_state_data, CellType *cell_state_data, CellType *scratch0, CellType *scratch1, CellType *scratch2, CellType *scratch3, luci_interpreter::BaseRuntimeGraph *runtime_graph)
Function Documentation
activationFunctionWithMinMax()
template<typename T > T luci_interpreter_pal::lstm_internal::activationFunctionWithMinMax (T x, T output_activation_min, T output_activation_max) inline
Definition at line 49 of file PALUnidirectionalSequenceLSTM.h.
{
  using std::max;
  using std::min;
  return min(max(x, output_activation_min), output_activation_max);
}
Referenced by mul().
addElementWise() [1/2]
void luci_interpreter_pal::lstm_internal::addElementWise (const float * input_1, const float * input_2, int n_batch, int n_input, float * output)
Definition at line 257 of file PALUnidirectionalSequenceLSTM.h.
{
  for (int batch = 0; batch < n_batch; ++batch)
  {
    for (int i = 0; i < n_input; ++i)
    {
      const int index = batch * n_input + i;
      output[index] = input_1[index] + input_2[index];
    }
  }
}
addElementWise() [2/2]
void luci_interpreter_pal::lstm_internal::addElementWise (const int16_t * input_1, const int16_t * input_2, int n_batch, int n_input, int16_t * output)
Definition at line 187 of file PALUnidirectionalSequenceLSTM.h.
{
  for (int batch = 0; batch < n_batch; ++batch)
  {
    for (int i = 0; i < n_input; ++i)
    {
      const int index = batch * n_input + i;
      int32_t sum = input_1[index] + input_2[index];
      const int32_t sum_clamped =
        std::min(static_cast<int32_t>(std::numeric_limits<int16_t>::max()),
                 std::max(static_cast<int32_t>(std::numeric_limits<int16_t>::min()), sum));
      output[index] = static_cast<int16_t>(sum_clamped);
    }
  }
}
Referenced by calculateLstmGate(), and updateLstmCell().
calculateLstmGate()
template<typename ActivationType , typename WeightType , typename CellType , typename BiasType > void luci_interpreter_pal::lstm_internal::calculateLstmGate (const LstmStepManager * step_info, const luci_interpreter::lstm::GateParameters * gate_params, ActivationType * input_data, const circle::Tensor * input_weight, const circle::Tensor * input_bias, ActivationType * recurrent_data, const circle::Tensor * recurrent_weight, const circle::Tensor * recurrent_bias, CellType * gate_output, CellType * fc_output_buffer, const TfLiteFusedActivation activation, luci_interpreter::BaseRuntimeGraph * runtime_graph)
Definition at line 392 of file PALUnidirectionalSequenceLSTM.h.
{
  // Input FC
  const auto gate_output_shape = step_info->stateShape();
  {
    tflite::FullyConnectedParams op_params{};
    op_params.input_offset = gate_params->input_fc_params.input_offset;
    op_params.weights_offset = gate_params->input_fc_params.weights_offset;
    op_params.output_offset = gate_params->input_fc_params.output_offset;
    op_params.output_multiplier = gate_params->input_fc_params.output_multiplier;
    op_params.output_shift = gate_params->input_fc_params.output_shift;
    op_params.quantized_activation_min = gate_params->input_fc_params.quantized_activation_min;
    op_params.quantized_activation_max = gate_params->input_fc_params.quantized_activation_max;
    op_params.float_activation_max = gate_params->input_fc_params.float_activation_max;
    op_params.float_activation_min = gate_params->input_fc_params.float_activation_min;
    fullyConnected(op_params, step_info->inputShape(), input_data + step_info->inputOffset(),
                   luci_interpreter::kernels::getTensorShape(input_weight),
                   luci_interpreter::kernels::getTensorData<WeightType>(
                     runtime_graph->getConstDataByTensor(input_weight)),
                   luci_interpreter::kernels::getTensorShape(input_bias),
                   luci_interpreter::kernels::getTensorData<BiasType>(
                     runtime_graph->getConstDataByTensor(input_bias)),
                   gate_output_shape, gate_output);
  }
  // Recurrent FC
  {
    tflite::FullyConnectedParams op_params{};
    op_params.input_offset = gate_params->recurrent_fc_params.input_offset;
    op_params.weights_offset = gate_params->recurrent_fc_params.weights_offset;
    op_params.output_offset = gate_params->recurrent_fc_params.output_offset;
    op_params.output_multiplier = gate_params->recurrent_fc_params.output_multiplier;
    op_params.output_shift = gate_params->recurrent_fc_params.output_shift;
    op_params.quantized_activation_min = gate_params->recurrent_fc_params.quantized_activation_min;
    op_params.quantized_activation_max = gate_params->recurrent_fc_params.quantized_activation_max;
    op_params.float_activation_max = gate_params->recurrent_fc_params.float_activation_max;
    op_params.float_activation_min = gate_params->recurrent_fc_params.float_activation_min;
    fullyConnected(op_params, step_info->stateShape(),
                   recurrent_data + step_info->hiddenStateOffset(),
                   luci_interpreter::kernels::getTensorShape(recurrent_weight),
                   luci_interpreter::kernels::getTensorData<WeightType>(
                     runtime_graph->getConstDataByTensor(recurrent_weight)),
                   luci_interpreter::kernels::getTensorShape(recurrent_bias),
                   luci_interpreter::kernels::getTensorData<BiasType>(
                     runtime_graph->getConstDataByTensor(recurrent_bias)),
                   gate_output_shape, fc_output_buffer);
    addElementWise(gate_output, fc_output_buffer, /*n_batch=*/gate_output_shape.DimsData()[0],
                   /*n_state=*/gate_output_shape.DimsData()[1], gate_output);
    switch (activation)
    {
      case TfLiteFusedActivation::kTfLiteActSigmoid:
        sigmoid(gate_output_shape, gate_output);
        break;
      case TfLiteFusedActivation::kTfLiteActTanh:
      {
        // Set the scale power to -12 to avoid shift
        tanh(/*cell_state_scale_power=*/-12, gate_output_shape, gate_output, gate_output_shape,
             gate_output);
      }
      break;
      default:
        // Only Sigmoid or Tanh is used.
        assert(false && "Only Sigmoid or Tanh is used");
    }
  }
}
References addElementWise(), luci_interpreter::lstm::FullyConnectedParams::float_activation_max, luci_interpreter::lstm::FullyConnectedParams::float_activation_min, fullyConnected(), luci_interpreter::RuntimeGraph::getConstDataByTensor(), luci_interpreter::kernels::getTensorShape(), luci_interpreter_pal::lstm_internal::LstmStepManager::hiddenStateOffset(), luci_interpreter::lstm::GateParameters::input_fc_params, luci_interpreter::lstm::FullyConnectedParams::input_offset, luci_interpreter_pal::lstm_internal::LstmStepManager::inputOffset(), luci_interpreter_pal::lstm_internal::LstmStepManager::inputShape(), luci_interpreter::lstm::FullyConnectedParams::output_multiplier, luci_interpreter::lstm::FullyConnectedParams::output_offset, luci_interpreter::lstm::FullyConnectedParams::output_shift, luci_interpreter::lstm::FullyConnectedParams::quantized_activation_max, luci_interpreter::lstm::FullyConnectedParams::quantized_activation_min, luci_interpreter::lstm::GateParameters::recurrent_fc_params, sigmoid(), luci_interpreter_pal::lstm_internal::LstmStepManager::stateShape(), tanh(), and luci_interpreter::lstm::FullyConnectedParams::weights_offset.
clipping() [1/2]
void luci_interpreter_pal::lstm_internal::clipping (const int v_size, const luci_interpreter::lstm::CellStateInfo * cell_state_info, float * vector)
Definition at line 281 of file PALUnidirectionalSequenceLSTM.h.
{
  for (int i = 0; i < v_size; i++)
  {
    vector[i] =
      std::max(std::min(cell_state_info->cell_clip, vector[i]), -cell_state_info->cell_clip);
  }
}
References luci_interpreter::lstm::CellStateInfo::cell_clip.
clipping() [2/2]
void luci_interpreter_pal::lstm_internal::clipping (const int v_size, const luci_interpreter::lstm::CellStateInfo * cell_state_info, int16_t * vector)
Definition at line 227 of file PALUnidirectionalSequenceLSTM.h.
{
  for (int i = 0; i < v_size; i++)
  {
    vector[i] = std::max(std::min(cell_state_info->quantized_cell_clip, vector[i]),
                         static_cast<int16_t>(-cell_state_info->quantized_cell_clip));
  }
}
References luci_interpreter::lstm::CellStateInfo::quantized_cell_clip.
Referenced by updateLstmCell().
fullyConnected() [1/3]
void luci_interpreter_pal::lstm_internal::fullyConnected (const tflite::FullyConnectedParams & params, const tflite::RuntimeShape & input_shape, const float * input_data, const tflite::RuntimeShape & filter_shape, const float * filter_data, const tflite::RuntimeShape & bias_shape, const float * bias_data, const tflite::RuntimeShape & output_shape, float * output_data)
Definition at line 239 of file PALUnidirectionalSequenceLSTM.h.
{
  return tflite::reference_ops::FullyConnected(params, input_shape, input_data, filter_shape,
                                               filter_data, bias_shape, bias_data, output_shape,
                                               output_data);
}
fullyConnected() [2/3]
void luci_interpreter_pal::lstm_internal::fullyConnected (const tflite::FullyConnectedParams & params, const tflite::RuntimeShape & input_shape, const int16_t * input_data, const tflite::RuntimeShape & filter_shape, const int8_t * filter_data, const tflite::RuntimeShape & bias_shape, const int64_t * bias_data, const tflite::RuntimeShape & output_shape, int16_t * output_data)
Definition at line 142 of file PALUnidirectionalSequenceLSTM.h.
{
  return fullyConnectedInteger(params, input_shape, input_data, filter_shape, filter_data,
                               bias_shape, bias_data, output_shape, output_data);
}
References fullyConnectedInteger().
fullyConnected() [3/3]
void luci_interpreter_pal::lstm_internal::fullyConnected (const tflite::FullyConnectedParams & params, const tflite::RuntimeShape & input_shape, const int8_t * input_data, const tflite::RuntimeShape & filter_shape, const int8_t * filter_data, const tflite::RuntimeShape & bias_shape, const int32_t * bias_data, const tflite::RuntimeShape & output_shape, int16_t * output_data)
Definition at line 132 of file PALUnidirectionalSequenceLSTM.h.
{
  return fullyConnectedInteger(params, input_shape, input_data, filter_shape, filter_data,
                               bias_shape, bias_data, output_shape, output_data);
}
References fullyConnectedInteger().
Referenced by calculateLstmGate().
fullyConnectedInteger()
template<typename InputType , typename WeightType , typename OutputType , typename BiasType > void luci_interpreter_pal::lstm_internal::fullyConnectedInteger (const tflite::FullyConnectedParams & params, const tflite::RuntimeShape & input_shape, const InputType * input_data, const tflite::RuntimeShape & filter_shape, const WeightType * filter_data, const tflite::RuntimeShape & bias_shape, const BiasType * bias_data, const tflite::RuntimeShape & output_shape, OutputType * output_data)
Definition at line 85 of file PALUnidirectionalSequenceLSTM.h.
{
  const int32_t input_offset = params.input_offset;
  const int32_t filter_offset = params.weights_offset;
  const int32_t output_offset = params.output_offset;
  const int32_t output_multiplier = params.output_multiplier;
  const int output_shift = params.output_shift;
  const int32_t output_activation_min = params.quantized_activation_min;
  const int32_t output_activation_max = params.quantized_activation_max;
  TFLITE_DCHECK_GE(filter_shape.DimensionsCount(), 2);
  TFLITE_DCHECK_GE(output_shape.DimensionsCount(), 1);
  TFLITE_DCHECK_LE(output_activation_min, output_activation_max);
  const int filter_dim_count = filter_shape.DimensionsCount();
  const int output_dim_count = output_shape.DimensionsCount();
  const int batches = FlatSizeSkipDim(output_shape, output_dim_count - 1);
  const int output_depth = output_shape.Dims(output_dim_count - 1);
  TFLITE_DCHECK_LE(output_depth, filter_shape.Dims(filter_dim_count - 2));
  const int accum_depth = filter_shape.Dims(filter_dim_count - 1);
  for (int b = 0; b < batches; ++b)
  {
    for (int out_c = 0; out_c < output_depth; ++out_c)
    {
      BiasType acc = 0;
      for (int d = 0; d < accum_depth; ++d)
      {
        int32_t input_val = input_data[b * accum_depth + d];
        int32_t filter_val = filter_data[out_c * accum_depth + d];
        acc += (filter_val + filter_offset) * (input_val + input_offset);
      }
      if (bias_data)
      {
        acc += bias_data[out_c];
      }
      int32_t acc_scaled = multiplyByQuantizedMultiplier(acc, output_multiplier, output_shift);
      acc_scaled += output_offset;
      acc_scaled = std::max(acc_scaled, output_activation_min);
      acc_scaled = std::min(acc_scaled, output_activation_max);
      output_data[out_c + output_depth * b] = static_cast<OutputType>(acc_scaled);
    }
  }
}
References multiplyByQuantizedMultiplier().
Referenced by fullyConnected().
lstmStep()
template<typename ActivationType , typename WeightType , typename CellType , typename BiasType > void luci_interpreter_pal::lstm_internal::lstmStep (luci_interpreter::lstm::LSTMStruct * lstm_struct, luci_interpreter::lstm::LSTMParameters * lstm_params, LstmStepManager * step_info, luci_interpreter::lstm::CellStateInfo * cell_state_info, ActivationType * output_state_data, CellType * cell_state_data, CellType * scratch0, CellType * scratch1, CellType * scratch2, CellType * scratch3, luci_interpreter::BaseRuntimeGraph * runtime_graph)
Definition at line 529 of file PALUnidirectionalSequenceLSTM.h.
{
  /*Step1: Calculate gate outputs to prepare cell state update*/
  CellType *gate_internal_buffer = scratch3;
  CellType *forget_gate_output = scratch0;
  auto input_data = luci_interpreter::kernels::getTensorData<ActivationType>(
    runtime_graph->getDataByTensor(lstm_struct->input()));
  calculateLstmGate<ActivationType, WeightType, CellType, BiasType>(
    step_info, &lstm_params->forget_gate_parameters,
    // Input FC
    input_data, lstm_struct->input_to_forget_weights(), lstm_struct->forget_gate_bias(),
    // Recurrent FC
    output_state_data, lstm_struct->recurrent_to_forget_weights(), nullptr,
    // Output
    forget_gate_output, gate_internal_buffer, TfLiteFusedActivation::kTfLiteActSigmoid,
    runtime_graph);
  // Input Gate calculation;
  CellType *input_gate_output = scratch1;
  calculateLstmGate<ActivationType, WeightType, CellType, BiasType>(
    step_info, &lstm_params->input_gate_parameters,
    // Input FC
    input_data, lstm_struct->input_to_input_weights(), lstm_struct->input_gate_bias(),
    // Recurrent FC
    output_state_data, lstm_struct->recurrent_to_input_weights(),
    /*recurrent_bias*/ nullptr,
    // Output
    input_gate_output,
    // Scratch arrays
    gate_internal_buffer, TfLiteFusedActivation::kTfLiteActSigmoid, runtime_graph);
  // Cell Gate calculation
  CellType *cell_gate_output = scratch2;
  calculateLstmGate<ActivationType, WeightType, CellType, BiasType>(
    step_info, &lstm_params->cell_gate_parameters,
    // Input FC
    input_data, lstm_struct->input_to_cell_weights(), lstm_struct->cell_gate_bias(),
    // Recurrent FC
    output_state_data, lstm_struct->recurrent_to_cell_weights(),
    /*recurrent_bias*/ nullptr,
    // Output
    cell_gate_output,
    // Scratch arrays
    gate_internal_buffer, TfLiteFusedActivation::kTfLiteActTanh, runtime_graph);
  /*Step2: update the cell state */
  {
    // const InterGateParameters& inter_gate_params = op_data.inter_gate_parameters;
    CellType *updated_input_buffer = scratch1; // reuse buffer
    updateLstmCell<CellType>(
      step_info, cell_state_data, forget_gate_output, input_gate_output, cell_gate_output,
      lstm_params->inter_gate_parameters.forget_cell_mul_params,
      lstm_params->inter_gate_parameters.input_mul_params, cell_state_info, updated_input_buffer);
  }
  {
    /*Step3: update the hidden state */
    CellType *output_gate_output = scratch1; // reuse buffer
    calculateLstmGate<ActivationType, WeightType, CellType, BiasType>(
      step_info, &lstm_params->output_gate_parameters,
      // Input FC
      input_data, lstm_struct->input_to_output_weights(), lstm_struct->output_gate_bias(),
      // Recurrent FC
      output_state_data, lstm_struct->recurrent_to_output_weights(), nullptr,
      // Output
      output_gate_output,
      // Scratch arrays
      gate_internal_buffer, TfLiteFusedActivation::kTfLiteActSigmoid, runtime_graph);
    CellType *tanh_activated_cell_buffer = scratch0; // reuse buffer
    updateLstmHidden<CellType, ActivationType>(
      step_info, cell_state_data, output_state_data, output_gate_output,
      &lstm_params->inter_gate_parameters.output_mul_params,
      cell_state_info->cell_state_scale_power, tanh_activated_cell_buffer);
    ActivationType *output_ptr = luci_interpreter::kernels::getTensorData<ActivationType>(
      runtime_graph->getDataByTensor(lstm_struct->output()));
    std::memcpy(output_ptr + step_info->outputOffset(),
                output_state_data + step_info->hiddenStateOffset(),
                step_info->stateShape().FlatSize() * sizeof(ActivationType));
  }
}
References luci_interpreter::lstm::LSTMStruct::cell_gate_bias(), luci_interpreter::lstm::LSTMParameters::cell_gate_parameters, luci_interpreter::lstm::CellStateInfo::cell_state_scale_power, luci_interpreter::lstm::InterGateParameters::forget_cell_mul_params, luci_interpreter::lstm::LSTMStruct::forget_gate_bias(), luci_interpreter::lstm::LSTMParameters::forget_gate_parameters, luci_interpreter::RuntimeGraph::getDataByTensor(), luci_interpreter_pal::lstm_internal::LstmStepManager::hiddenStateOffset(), luci_interpreter::lstm::LSTMStruct::input(), luci_interpreter::lstm::LSTMStruct::input_gate_bias(), luci_interpreter::lstm::LSTMParameters::input_gate_parameters, luci_interpreter::lstm::InterGateParameters::input_mul_params, luci_interpreter::lstm::LSTMStruct::input_to_cell_weights(), luci_interpreter::lstm::LSTMStruct::input_to_forget_weights(), luci_interpreter::lstm::LSTMStruct::input_to_input_weights(), luci_interpreter::lstm::LSTMStruct::input_to_output_weights(), luci_interpreter::lstm::LSTMParameters::inter_gate_parameters, luci_interpreter::lstm::LSTMStruct::output(), luci_interpreter::lstm::LSTMStruct::output_gate_bias(), luci_interpreter::lstm::LSTMParameters::output_gate_parameters, luci_interpreter::lstm::InterGateParameters::output_mul_params, luci_interpreter_pal::lstm_internal::LstmStepManager::outputOffset(), luci_interpreter::lstm::LSTMStruct::recurrent_to_cell_weights(), luci_interpreter::lstm::LSTMStruct::recurrent_to_forget_weights(), luci_interpreter::lstm::LSTMStruct::recurrent_to_input_weights(), luci_interpreter::lstm::LSTMStruct::recurrent_to_output_weights(), and luci_interpreter_pal::lstm_internal::LstmStepManager::stateShape().
mul() [1/4]
template<typename T > void luci_interpreter_pal::lstm_internal::mul (const luci_interpreter::lstm::ArithmeticParams * params, const tflite::RuntimeShape & input1_shape, const T * input1_data, const tflite::RuntimeShape & input2_shape, const T * input2_data, const tflite::RuntimeShape & output_shape, T * output_data) inline
Definition at line 57 of file PALUnidirectionalSequenceLSTM.h.
{
  T output_activation_min = params->quantized_activation_min;
  T output_activation_max = params->quantized_activation_max;
  const int flat_size = input1_shape.FlatSize();
  for (int i = 0; i < flat_size; ++i)
  {
    output_data[i] = activationFunctionWithMinMax(input1_data[i] * input2_data[i],
                                                  output_activation_min, output_activation_max);
  }
}
References activationFunctionWithMinMax(), luci_interpreter::lstm::ArithmeticParams::quantized_activation_max, and luci_interpreter::lstm::ArithmeticParams::quantized_activation_min.
Referenced by mul(), updateLstmCell(), and updateLstmHidden().
mul() [2/4]
void luci_interpreter_pal::lstm_internal::mul (const tflite::RuntimeShape & shape, const luci_interpreter::lstm::ArithmeticParams * params, const float * input1_data, const float * input2_data, float * output_data)
Definition at line 251 of file PALUnidirectionalSequenceLSTM.h.
{
  return mul(params, shape, input1_data, shape, input2_data, shape, output_data);
}
References mul().
mul() [3/4]
void luci_interpreter_pal::lstm_internal::mul (const tflite::RuntimeShape & shape, const luci_interpreter::lstm::ArithmeticParams * params, const int16_t * input1_data, const int16_t * input2_data, int16_t * output_data)
Definition at line 181 of file PALUnidirectionalSequenceLSTM.h.
{
  return mulElementwise(shape.FlatSize(), params, input1_data, input2_data, output_data);
}
References mulElementwise().
mul() [4/4]
void luci_interpreter_pal::lstm_internal::mul (const tflite::RuntimeShape & shape, const luci_interpreter::lstm::ArithmeticParams * params, const int16_t * input1_data, const int16_t * input2_data, int8_t * output_data)
Definition at line 173 of file PALUnidirectionalSequenceLSTM.h.
{
  return mulElementwise<int16_t, int8_t>(shape.FlatSize(), params, input1_data, input2_data,
                                         output_data);
}
mulElementwise()
template<typename InputType , typename OutputType > void luci_interpreter_pal::lstm_internal::mulElementwise (int size, const luci_interpreter::lstm::ArithmeticParams * params, const InputType * input1_data, const InputType * input2_data, OutputType * output_data)
Definition at line 153 of file PALUnidirectionalSequenceLSTM.h.
{
  for (int i = 0; i < size; ++i)
  {
    const int32_t input1_val = params->input1_offset + input1_data[i];
    const int32_t input2_val = params->input2_offset + input2_data[i];
    const int32_t unclamped_result =
      params->output_offset + multiplyByQuantizedMultiplier(input1_val * input2_val,
                                                            params->output_multiplier,
                                                            params->output_shift);
    const int32_t clamped_output =
      std::min(params->quantized_activation_max,
               std::max(params->quantized_activation_min, unclamped_result));
    output_data[i] = static_cast<OutputType>(clamped_output);
  }
}
References luci_interpreter::lstm::ArithmeticParams::input1_offset, luci_interpreter::lstm::ArithmeticParams::input2_offset, multiplyByQuantizedMultiplier(), luci_interpreter::lstm::ArithmeticParams::output_multiplier, luci_interpreter::lstm::ArithmeticParams::output_offset, luci_interpreter::lstm::ArithmeticParams::output_shift, luci_interpreter::lstm::ArithmeticParams::quantized_activation_max, and luci_interpreter::lstm::ArithmeticParams::quantized_activation_min.
Referenced by mul().
multiplyByQuantizedMultiplier()
int32_t luci_interpreter_pal::lstm_internal::multiplyByQuantizedMultiplier (int32_t x, int32_t quantized_multiplier, int shift) inline
Definition at line 74 of file PALUnidirectionalSequenceLSTM.h.
{
  using gemmlowp::RoundingDivideByPOT;
  using gemmlowp::SaturatingRoundingDoublingHighMul;
  int left_shift = shift > 0 ? shift : 0;
  int right_shift = shift > 0 ? 0 : -shift;
  return RoundingDivideByPOT(
    SaturatingRoundingDoublingHighMul(x * (1 << left_shift), quantized_multiplier), right_shift);
}
Referenced by fullyConnectedInteger(), and mulElementwise().
sigmoid() [1/2]
void luci_interpreter_pal::lstm_internal::sigmoid (const tflite::RuntimeShape & data_shape, float * data)
Definition at line 276 of file PALUnidirectionalSequenceLSTM.h.
{
  tflite::reference_ops::Logistic(data_shape, data, data_shape, data);
}
sigmoid() [2/2]
void luci_interpreter_pal::lstm_internal::sigmoid (const tflite::RuntimeShape & data_shape, int16_t * data)
Definition at line 218 of file PALUnidirectionalSequenceLSTM.h.
{
  tflite::reference_integer_ops::Logistic(0 /*data->input_multiplier*/,
                                          0 /*data->input_left_shift */,
                                          data_shape.FlatSize() /*NumElements(input->dims)*/,
                                          data /* tflite::micro::GetTensorData<int16_t>(input) */,
                                          data /*tflite::micro::GetTensorData<int16_t>(output) */);
}
Referenced by calculateLstmGate().
tanh() [1/2]
void luci_interpreter_pal::lstm_internal::tanh (int32_t cell_state_scale_power, const tflite::RuntimeShape & input_data_shape, float * input_data, const tflite::RuntimeShape & output_data_shape, float * output_data)
Definition at line 270 of file PALUnidirectionalSequenceLSTM.h.
{
  tflite::reference_ops::Tanh(input_data_shape, input_data, output_data_shape, output_data);
}
tanh() [2/2]
void luci_interpreter_pal::lstm_internal::tanh (int32_t cell_state_scale_power, const tflite::RuntimeShape & input_data_shape, int16_t * input_data, const tflite::RuntimeShape & output_data_shape, int16_t * output_data)
Definition at line 204 of file PALUnidirectionalSequenceLSTM.h.
{
  int32_t tanh_input_left_shift = (15 + cell_state_scale_power) - 3;
  int32_t input_multiplier = 0;
  if (tanh_input_left_shift < 0) /* handling negative shift value */
  {
    tanh_input_left_shift = -tanh_input_left_shift;
    input_multiplier = 3;
  }
  tflite::reference_integer_ops::Tanh(input_multiplier, tanh_input_left_shift, input_data_shape,
                                      input_data, output_data_shape, output_data);
}
Referenced by calculateLstmGate(), and updateLstmHidden().
updateLstmCell()
template<typename CellType > void luci_interpreter_pal::lstm_internal::updateLstmCell (const LstmStepManager * step_info, CellType * cell_state_data, CellType * forget_gate_output, const CellType * input_gate_output, const CellType * cell_gate_output, const luci_interpreter::lstm::ArithmeticParams & forget_cell_mul_params, const luci_interpreter::lstm::ArithmeticParams & input_mul_params, const luci_interpreter::lstm::CellStateInfo * cell_state_info, CellType * buffer)
Definition at line 498 of file PALUnidirectionalSequenceLSTM.h.
{
  auto cell_state_shape = step_info->stateShape();
  // Forget Gate x Cell State
  mul(cell_state_shape, &forget_cell_mul_params, forget_gate_output,
      cell_state_data + step_info->cellStateOffset(),
      cell_state_data + step_info->cellStateOffset());
  // Input Gate x Cell Gate
  mul(cell_state_shape, &input_mul_params, input_gate_output, cell_gate_output, buffer);
  // Update the cell state
  addElementWise(cell_state_data + step_info->cellStateOffset(), buffer,
                 /*n_batch=*/cell_state_shape.DimsData()[0],
                 /*n_state=*/cell_state_shape.DimsData()[1],
                 cell_state_data + step_info->cellStateOffset());
  if (cell_state_info->cell_clip > 0)
  {
    clipping(cell_state_shape.FlatSize(), cell_state_info,
             cell_state_data + step_info->cellStateOffset());
  }
}
References addElementWise(), luci_interpreter::lstm::CellStateInfo::cell_clip, luci_interpreter_pal::lstm_internal::LstmStepManager::cellStateOffset(), clipping(), mul(), and luci_interpreter_pal::lstm_internal::LstmStepManager::stateShape().
updateLstmHidden()
template<typename CellType , typename ActivationType > void luci_interpreter_pal::lstm_internal::updateLstmHidden (const LstmStepManager * step_info, CellType * cell_state_data_base, ActivationType * hidden_state_data, const CellType * output_gate_output, const luci_interpreter::lstm::ArithmeticParams * mul_params, int32_t cell_state_scale_power, CellType * buffer)
Definition at line 479 of file PALUnidirectionalSequenceLSTM.h.
{
  auto cell_state_shape = step_info->stateShape();
  CellType *cell_state_data = cell_state_data_base + step_info->cellStateOffset();
  // Tanh(cell_state)
  tanh(cell_state_scale_power, cell_state_shape, cell_state_data, cell_state_shape, buffer);
  // Update the hidden state
  mul(cell_state_shape, mul_params, buffer, output_gate_output,
      hidden_state_data + step_info->hiddenStateOffset());
}
References luci_interpreter_pal::lstm_internal::LstmStepManager::cellStateOffset(), luci_interpreter_pal::lstm_internal::LstmStepManager::hiddenStateOffset(), mul(), luci_interpreter_pal::lstm_internal::LstmStepManager::stateShape(), and tanh().