ONE - On-device Neural Engine: fmelib.DumpFMEParams Namespace Reference
fmelib.DumpFMEParams Namespace Reference
Data Structures
class DumpFMEParams
Functions
_pretty_float (item, ndigits=6)
Function Documentation
_pretty_float()
fmelib.DumpFMEParams._pretty_float (item, ndigits = 6) protected
Definition at line 29 of file DumpFMEParams.py.
def _pretty_float(item, ndigits=6):
    if isinstance(item, list):
        return [_pretty_float(x, ndigits) for x in item]
    if isinstance(item, float):
        return round(item, ndigits)
    return item
# Dump scale parameters for FM equalization
# The parameters are saved in the json file given as an input
#
# Contents of the json file ('<model_name>.fme_patterns.json')
#
# Before
# [
#   {
#     “front”: <tensor_name>,
#     “back”: <tensor_name>,
#     “type”: ScaleOnly,
#   },
#   …
# ]
#
# After
# [
#   {
#     “front”: <tensor_name>,
#     “back”: <tensor_name>,
#     “type”: ScaleOnly,
#     “act_scale”: [..],
#   },
#   …
# ]
References fmelib.DumpFMEParams._pretty_float().
Referenced by fmelib.DumpFMEParams._pretty_float(), and fmelib.DumpFMEParams.DumpFMEParams.EndAnalysis().