ONE - On-device Neural Engine: coco Namespace Reference
coco Namespace Reference
Namespaces
namespace FeatureLayouts
namespace KernelLayouts
Data Structures
class Add
Element-wise addition.
class Arg
Base class for NN model arguments (Input/Output)
class AvgPool2D
2D Average Pooling
class Bag
A collection of (abstracted) elements of the same type.
class BagManager
class BinaryOp
Op with two arguments.
class Block
A unit of (grouped) instructions.
class BlockIndex
A BlockIndex denotes the index of a block in a block list.
class BlockManager
class ConcatF
Concatenate two feature maps.
class Conv2D
2D Convolution over 3D Feature Map with 4D kernel
class Copy
Index-wise element transfer between two objects.
struct Data
Core coco entity for constant weights.
class Def
class Dep
A Dep represents the edge between a Bag and its dependent Object.
class Div
Element-wise division.
struct DLinkedList
class ElemID
class Entity
A base class for IR entities.
class EntityBuilder
A base class for IR entity builders.
struct EntityManager
Meta (lifetime) manager interface.
class Eval
Evaluate an Object from a given Op.
struct FeatureLayout
A FeatureLayout connects each feature index to a Bag element.
class FeatureObject
FeatureMap values (used in CNN)
class FeatureShape
The shape of a feature map.
class Input
class InputManager
class Instr
Base interface on explicit computation steps in coco IR.
class InstrIndex
A InstrIndex denotes the index of an instruction in an instruction list.
class InstrManager
struct KernelLayout
A KernelLayout connectes each kernel index to an element (in a bag)
class KernelObject
Convolution Kernel (in CNN) values.
class Load
Load an Object.
struct Locatable
Return the associated instruction if exists.
class MaxPool2D
2D Max Pooling
class Module
Top-level element of coco IR which represents a neural network.
class Mul
Element-wise multiplication.
class Object
Base interface on all typed NN values.
class ObjectManager
struct Op
Base interface on all supported NN operations.
class OpManager
class Output
class OutputManager
class Padding2D
class PadF
Introduce padding area.
class Part
A Part represents the edge between a child Op and its parent Op.
struct PlainWeightContext
Non-quantized (plain) Weight Data Accessor.
class PtrList
class PtrManager
class Read
A Read represents an edge between a Bag and its Reader.
class ReLU
Apply ReLU over elements.
class ReLU6
Apply ReLU6 over elements.
class Shuffle
Generic element transfer.
class Span
A Span is a non-owing reference to a memory chunk.
class Sqrt
Apply Sqrt over elements.
class Step
A Step denotes the edge between Op and Instr.
class Stride2D
class Sub
Element-wise subtraction.
class UnaryOp
Op with a single argument.
class Update
A Update represents an edge between a Bag and its Updater.
class Use
class Window2D
Typedefs
using BlockList = DLinkedList< Block, Module >::Head
using DepSet = std::set< Dep * >
using InputList = PtrList< Input >
using InstrList = coco::DLinkedList< Instr, Block >::Head
using ObjectSet = std::set< Object * >
using OutputList = PtrList< Output >
using ReadSet = std::set< Read * >
using UpdateSet = std::set< Update * >
using UseSet = std::set< Use * >
Functions
ObjectSet dependent_objects (const Bag *)
Return a set of objects that depends on a given bag.
Bag::ReaderSet readers (const Bag *)
Return a set of readers that reads a given bag.
Bag::UpdaterSet updaters (const Bag *)
Return a set of updaters that updates a given bag.
bool operator== (const ElemID &lhs, const ElemID &rhs)
bool operator< (const ElemID &lhs, const ElemID &rhs)
template<typename T >
bool isa (const Instr *ins)
Return true if a given instruction is of T type.
template<typename T >
T * safe_cast (Instr *ins)
Cast as a derived instruction.
template<typename T >
bool isa (const Object *)
Check whether a given object is of type T.
template<typename T >
T * cast (Object *)
Cast a generic object as a specific one.
template<typename T >
T * safe_cast (Object *)
Cast a generic object as a specific one.
Object::Producer * producer (const Object *)
Return the producer of a given object if it exists.
Object::ConsumerSet consumers (const Object *)
Return a set of consumers of a given object.
Op * root (Op *)
Return the root Op from a given Op node.
template<>
bool isa< FeatureObject > (const Object *o)
template<>
bool isa< KernelObject > (const Object *o)
template<>
FeatureObject * cast (Object *o)
template<>
KernelObject * cast (Object *o)
template<>
FeatureObject * safe_cast (Object *o)
template<>
KernelObject * safe_cast (Object *o)
Typedef Documentation
BlockList
using coco::BlockList = typedef DLinkedList<Block, Module>::Head
Definition at line 31 of file Block.h.
DepSet
using coco::DepSet = typedef std::set<Dep *>
Definition at line 27 of file DepSet.h.
InputList
using coco::InputList = typedef PtrList<Input>
Definition at line 27 of file InputList.h.
InstrList
using coco::InstrList = typedef coco::DLinkedList<Instr, Block>::Head
Definition at line 38 of file Instr.h.
ObjectSet
using coco::ObjectSet = typedef std::set<Object *>
Definition at line 27 of file ObjectSet.h.
OutputList
using coco::OutputList = typedef PtrList<Output>
Definition at line 27 of file OutputList.h.
ReadSet
using coco::ReadSet = typedef std::set<Read *>
Definition at line 27 of file ReadSet.h.
UpdateSet
using coco::UpdateSet = typedef std::set<Update *>
Definition at line 27 of file UpdateSet.h.
UseSet
using coco::UseSet = typedef std::set<Use *>
Definition at line 27 of file UseSet.h.
Function Documentation
cast() [1/3]
template<typename T > T * coco::cast (Object *)
Cast a generic object as a specific one.
"cast<T>(o)" accepts only a valid object pointer "o" that "isa<T>(o)" holds
Then, "cast<T>(o)" always returns a valid object pointer.
References cast().
Referenced by cast().
cast() [2/3]
template<> FeatureObject * coco::cast (Object * o)
Definition at line 88 of file Object.cpp.
{
  assert(o != nullptr);
  auto res = o->asFeature();
  assert(res != nullptr);
  return res;
}
References coco::Object::asFeature(), and cast().
cast() [3/3]
template<> KernelObject * coco::cast (Object * o)
Definition at line 96 of file Object.cpp.
{
  assert(o != nullptr);
  auto res = o->asKernel();
  assert(res != nullptr);
  return res;
}
References coco::Object::asKernel(), and cast().
consumers()
Object::ConsumerSet coco::consumers (const Object * obj)
Return a set of consumers of a given object.
Definition at line 65 of file Object.cpp.
{
  Object::ConsumerSet res;
  for (const auto &use : *(obj->uses()))
  {
    if (auto consumer = use->consumer())
    {
      res.insert(consumer);
    }
  }
  return res;
}
Referenced by readers().
dependent_objects()
ObjectSet coco::dependent_objects (const Bag * b)
Return a set of objects that depends on a given bag.
Definition at line 87 of file Bag.cpp.
{
  ObjectSet res;
  for (const auto &dep : *(b->deps()))
  {
    if (auto obj = dep->object())
    {
      res.insert(obj);
    }
  }
  return res;
}
Referenced by readers(), enco::unify_feature(), and updaters().
isa() [1/2]
template<typename T > bool coco::isa (const Instr * ins)
Return true if a given instruction is of T type.
Note
"ins" cannot be a null pointer
Definition at line 141 of file Instr.h.
{
  assert(ins != nullptr);
  return dynamic_cast<const T *>(ins) != nullptr;
}
isa() [2/2]
template<typename T > bool coco::isa (const Object *)
Check whether a given object is of type T.
The example below shows how to use this "isa<T>" helper: auto obj = new FeatureObject{};
if (isa<FeatureObject>()) { std::cout << "FeatureObject" << std::endl; }
isa< FeatureObject >()
template<> bool coco::isa< FeatureObject > (const Object * o)
Casting Helpers
TODO Use Macro to reduce code duplication
Definition at line 85 of file Object.cpp.
{ return o->asFeature() != nullptr; }
References coco::Object::asFeature().
isa< KernelObject >()
template<> bool coco::isa< KernelObject > (const Object * o)
Definition at line 86 of file Object.cpp.
{ return o->asKernel() != nullptr; }
References coco::Object::asKernel().
operator<()
bool coco::operator< (const ElemID & lhs, const ElemID & rhs)
Definition at line 23 of file ElemID.cpp.
{ return lhs.value() < rhs.value(); }
References operator<(), and coco::ElemID::value().
Referenced by operator<().
operator==()
bool coco::operator== (const ElemID & lhs, const ElemID & rhs)
Definition at line 22 of file ElemID.cpp.
{ return lhs.value() == rhs.value(); }
References coco::ElemID::value().
producer()
Object::Producer * coco::producer (const Object * obj)
Return the producer of a given object if it exists.
Definition at line 55 of file Object.cpp.
{
  if (auto d = obj->def())
  {
    return d->producer();
  }
  return nullptr;
}
References coco::Def::producer().
Referenced by enco::eliminate_dead_object(), enco::eliminate_indirect_copy(), enco::reduce_duplicated_object(), and updaters().
readers()
Bag::ReaderSet coco::readers (const Bag * b)
Return a set of readers that reads a given bag.
Definition at line 102 of file Bag.cpp.
{
  Bag::ReaderSet res;
  for (auto obj : dependent_objects(b))
  {
    for (auto consumer : consumers(obj))
    {
      // NOTE Object::Consumer inherits Bag::Reader
      res.insert(consumer);
    }
  }
  for (auto read : *b->reads())
  {
    auto reader = read->reader();
    assert(reader != nullptr);
    res.insert(reader);
  }
  return res;
}
References consumers(), and dependent_objects().
Referenced by enco::fold_constants(), enco::generate_bypass_shuffle(), enco::hoist_object(), and enco::readers().
root()
Op * coco::root (Op * cur)
Return the root Op from a given Op node.
Note
root(op) == op holds for a root op
Definition at line 144 of file Op.cpp.
{
  while (cur->up())
  {
    cur = cur->up();
  }
  return cur;
}
References coco::Op::up().
safe_cast() [1/4]
template<typename T > T * coco::safe_cast (Instr * ins)
Cast as a derived instruction.
Note
"safe_cast<T>(ins)" returns a null pointer if "ins" is not of T type
"safe_cast<T>(ins)" returns a null pointer if "ins" is a null pointer
Definition at line 153 of file Instr.h.
{
  // NOTE dynamic_cast<T *>(nullptr) returns nullptr
  return dynamic_cast<T *>(ins);
}
safe_cast() [2/4]
template<typename T > T * coco::safe_cast (Object *)
Cast a generic object as a specific one.
Unlike "cast<T>", "safe_cast<T>" accepts any object pointer
"safe_cast<T>(nullptr)" returns "nullptr"
"safe_cast<T>(o)" returns "nullptr" if "isa<T>(o)" does not hold
safe_cast() [3/4]
template<> FeatureObject * coco::safe_cast (Object * o)
Definition at line 104 of file Object.cpp.
{
  // NOTE o may be nullptr
  return (o == nullptr) ? nullptr : o->asFeature();
}
References coco::Object::asFeature().
safe_cast() [4/4]
template<> KernelObject * coco::safe_cast (Object * o)
Definition at line 110 of file Object.cpp.
{
  // NOTE o may be nullptr
  return (o == nullptr) ? nullptr : o->asKernel();
}
References coco::Object::asKernel().
updaters()
Bag::UpdaterSet coco::updaters (const Bag * b)
Return a set of updaters that updates a given bag.
Definition at line 125 of file Bag.cpp.
{
  Bag::UpdaterSet res;
  for (auto obj : dependent_objects(b))
  {
    if (auto p = producer(obj))
    {
      res.insert(p);
    }
  }
  for (auto update : *b->updates())
  {
    auto updater = update->updater();
    assert(updater != nullptr);
    res.insert(updater);
  }
  return res;
}
References dependent_objects(), and producer().
Referenced by enco::eliminate_dead_bag(), enco::generate_bypass_shuffle(), and enco::updaters().