ONE - On-device Neural Engine: utils Namespace Reference
utils Namespace Reference
Functions
def add_default_arg (parser)
def add_default_arg_no_CS (parser)
def is_accumulated_arg (arg, driver)
def is_valid_attr (args, attr)
def parse_cfg_and_overwrite (config_path, section, args)
def parse_cfg (args, driver_name)
def print_version_and_exit (file_path)
def safemain (main, mainpath)
def run (cmd, err_prefix=None, logfile=None)
def remove_prefix (str, prefix)
def remove_suffix (str, suffix)
def get_optimization_list (get_name=False)
def detect_one_import_drivers (search_path)
Function Documentation
add_default_arg()
def utils.add_default_arg (parser)
Definition at line 29 of file utils.py.
def add_default_arg(parser):
    # version
    parser.add_argument(
        '-v',
        '--version',
        action='store_true',
        help='show program\'s version number and exit')
    # verbose
    parser.add_argument(
        '-V',
        '--verbose',
        action='store_true',
        help='output additional information to stdout or stderr')
    # configuration file
    parser.add_argument('-C', '--config', type=str, help='run with configuation file')
    # section name that you want to run in configuration file
    parser.add_argument('-S', '--section', type=str, help=argparse.SUPPRESS)
add_default_arg_no_CS()
def utils.add_default_arg_no_CS (parser)
This adds -v -V args only (no -C nor -S)
Definition at line 50 of file utils.py.
def add_default_arg_no_CS(parser):
    """
    This adds -v -V args only (no -C nor -S)
    """
    # version
    parser.add_argument(
        '-v',
        '--version',
        action='store_true',
        help='show program\'s version number and exit')
    # verbose
    parser.add_argument(
        '-V',
        '--verbose',
        action='store_true',
        help='output additional information to stdout or stderr')
detect_one_import_drivers()
def utils.detect_one_import_drivers (search_path)
Looks for import drivers in given directory
Args:
    search_path: path to the directory where to search import drivers
Returns:
dict: each entry is related to single detected driver,
      key is a config section name, value is a driver name
Definition at line 252 of file utils.py.
def detect_one_import_drivers(search_path):
    """Looks for import drivers in given directory
    Args:
        search_path: path to the directory where to search import drivers
    Returns:
    dict: each entry is related to single detected driver,
          key is a config section name, value is a driver name
    """
    import_drivers_dict = {}
    for module_name in os.listdir(search_path):
        full_path = os.path.join(search_path, module_name)
        if not os.path.isfile(full_path):
            continue
        if module_name.find("one-import-") != 0:
            continue
        module_loader = importlib.machinery.SourceFileLoader(module_name, full_path)
        module_spec = importlib.util.spec_from_loader(module_name, module_loader)
        module = importlib.util.module_from_spec(module_spec)
        try:
            module_loader.exec_module(module)
            if hasattr(module, "get_driver_cfg_section"):
                section = module.get_driver_cfg_section()
                import_drivers_dict[section] = module_name
        except:
            pass
    return import_drivers_dict
get_optimization_list()
def utils.get_optimization_list (get_name = False)
returns a list of optimization. If `get_name` is True,
only basename without extension is returned rather than full file path.
[one hierarchy]
one
├── backends
├── bin
├── doc
├── include
├── lib
├── optimization
└── test
Optimization options must be placed in `optimization` folder
Definition at line 211 of file utils.py.
def get_optimization_list(get_name=False):
    """
    returns a list of optimization. If `get_name` is True,
    only basename without extension is returned rather than full file path.
    [one hierarchy]
    one
    ├── backends
    ├── bin
    ├── doc
    ├── include
    ├── lib
    ├── optimization
    └── test
    Optimization options must be placed in `optimization` folder
    """
    dir_path = os.path.dirname(os.path.realpath(__file__))
    # optimization folder
    files = [
        f for f in glob.glob(dir_path + '/../../optimization/O*.cfg', recursive=True)
    ]
    # exclude if the name has space
    files = [s for s in files if not ' ' in s]
    opt_list = []
    for cand in files:
        base = ntpath.basename(cand)
        if os.path.isfile(cand) and os.access(cand, os.R_OK):
            opt_list.append(cand)
    if get_name == True:
        # NOTE the name includes prefix 'O'
        # e.g. O1, O2, ONCHW not just 1, 2, NCHW
        opt_list = [ntpath.basename(f) for f in opt_list]
        opt_list = [remove_suffix(s, '.cfg') for s in opt_list]
    return opt_list
References remove_suffix().
is_accumulated_arg()
def utils.is_accumulated_arg (arg, driver)
Definition at line 69 of file utils.py.
def is_accumulated_arg(arg, driver):
    if driver == "one-quantize":
        accumulables = [
            "tensor_name", "scale", "zero_point", "src_tensor_name", "dst_tensor_name"
        ]
        if arg in accumulables:
            return True
    return False
Referenced by parse_cfg().
is_valid_attr()
def utils.is_valid_attr (args, attr)
Definition at line 80 of file utils.py.
def is_valid_attr(args, attr):
    return hasattr(args, attr) and getattr(args, attr)
Referenced by parse_cfg().
parse_cfg()
def utils.parse_cfg (args, driver_name)
parse configuration file. If the option is directly given to the command line,
   the option is processed prior to the configuration file.
   That is, if the values parsed from the configuration file already exist in args,
   the values are ignored.
Definition at line 107 of file utils.py.
def parse_cfg(args, driver_name):
    """parse configuration file. If the option is directly given to the command line,
       the option is processed prior to the configuration file.
       That is, if the values parsed from the configuration file already exist in args,
       the values are ignored."""
    if is_valid_attr(args, 'config'):
        config = configparser.ConfigParser()
        config.optionxform = str
        config.read(args.config)
        # if section is given, verify given section
        if is_valid_attr(args, 'section'):
            if not config.has_section(args.section):
                raise AssertionError('configuration file must have \'' + driver_name +
                                     '\' section')
            for key in config[args.section]:
                if is_accumulated_arg(key, driver_name):
                    if not is_valid_attr(args, key):
                        setattr(args, key, [config[args.section][key]])
                    else:
                        getattr(args, key).append(config[args.section][key])
                    continue
                if not is_valid_attr(args, key):
                    setattr(args, key, config[args.section][key])
        # if section is not given, section name is same with its driver name
        else:
            if not config.has_section(driver_name):
                raise AssertionError('configuration file must have \'' + driver_name +
                                     '\' section')
            secton_to_run = driver_name
            for key in config[secton_to_run]:
                if is_accumulated_arg(key, driver_name):
                    if not is_valid_attr(args, key):
                        setattr(args, key, [config[secton_to_run][key]])
                    else:
                        getattr(args, key).append(config[secton_to_run][key])
                    continue
                if not is_valid_attr(args, key):
                    setattr(args, key, config[secton_to_run][key])
References is_accumulated_arg(), and is_valid_attr().
parse_cfg_and_overwrite()
def utils.parse_cfg_and_overwrite (config_path, section, args)
parse given section of configuration file and set the values of args.
Even if the values parsed from the configuration file already exist in args,
the values are overwritten.
Definition at line 84 of file utils.py.
def parse_cfg_and_overwrite(config_path, section, args):
    """
    parse given section of configuration file and set the values of args.
    Even if the values parsed from the configuration file already exist in args,
    the values are overwritten.
    """
    if config_path == None:
        # DO NOTHING
        return
    config = configparser.ConfigParser()
    # make option names case sensitive
    config.optionxform = str
    parsed = config.read(config_path)
    if not parsed:
        raise FileNotFoundError('Not found given configuration file')
    if not config.has_section(section):
        raise AssertionError('configuration file doesn\'t have \'' + section +
                             '\' section')
    for key in config[section]:
        setattr(args, key, config[section][key])
    # TODO support accumulated arguments
print_version_and_exit()
def utils.print_version_and_exit (file_path)
print version of the file located in the file_path
Definition at line 147 of file utils.py.
def print_version_and_exit(file_path):
    """print version of the file located in the file_path"""
    script_path = os.path.realpath(file_path)
    dir_path = os.path.dirname(script_path)
    script_name = os.path.splitext(os.path.basename(script_path))[0]
    # run one-version
    subprocess.call([os.path.join(dir_path, 'one-version'), script_name])
    sys.exit()
remove_prefix()
def utils.remove_prefix (str, prefix)
Definition at line 199 of file utils.py.
def remove_prefix(str, prefix):
    if str.startswith(prefix):
        return str[len(prefix):]
    return str
remove_suffix()
def utils.remove_suffix (str, suffix)
Definition at line 205 of file utils.py.
def remove_suffix(str, suffix):
    if str.endswith(suffix):
        return str[:-len(suffix)]
    return str
Referenced by get_optimization_list().
run()
def utils.run (cmd, err_prefix = None, logfile = None)
Execute command in subprocess
Args:
    cmd: command to be executed in subprocess
    err_prefix: prefix to be put before every stderr lines
    logfile: file stream to which both of stdout and stderr lines will be written
Definition at line 167 of file utils.py.
def run(cmd, err_prefix=None, logfile=None):
    """Execute command in subprocess
    Args:
        cmd: command to be executed in subprocess
        err_prefix: prefix to be put before every stderr lines
        logfile: file stream to which both of stdout and stderr lines will be written
    """
    with subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as p:
        import select
        inputs = set([p.stdout, p.stderr])
        while inputs:
            readable, _, _ = select.select(inputs, [], [])
            for x in readable:
                line = x.readline()
                if len(line) == 0:
                    inputs.discard(x)
                    continue
                if x == p.stdout:
                    out = sys.stdout
                if x == p.stderr:
                    out = sys.stderr
                    if err_prefix:
                        line = f"{err_prefix}: ".encode() + line
                out.buffer.write(line)
                out.buffer.flush()
                if logfile != None:
                    logfile.write(line)
    if p.returncode != 0:
        sys.exit(p.returncode)
safemain()
def utils.safemain (main, mainpath)
execute given method and print with program name for all uncaught exceptions
Definition at line 157 of file utils.py.
def safemain(main, mainpath):
    """execute given method and print with program name for all uncaught exceptions"""
    try:
        main()
    except Exception as e:
        prog_name = os.path.basename(mainpath)
        print(f"{prog_name}: {type(e).__name__}: " + str(e), file=sys.stderr)
        sys.exit(255)
References main().