ONE - On-device Neural Engine: onert::backend::train::optimizer Namespace Reference
onert::backend::train::optimizer Namespace Reference
Data Structures
class Adam
Adam optimizer.
class SGD
SGD optimizer.
Functions
template<typename T , typename L >
void elementwise (const ir::Shape &shape, const backend::ITensor &src, backend::ITensor &dst, const L &f)
Function Documentation
elementwise()
template<typename T , typename L > void onert::backend::train::optimizer::elementwise (const ir::Shape & shape, const backend::ITensor & src, backend::ITensor & dst, const L & f)
Definition at line 32 of file OptimizerHelpers.h.
{
  ShapeLoop(shape, [&](const ir::Coordinates &coords) {
    const T src_val = *reinterpret_cast<const T *>(src.buffer() + src.calcOffset(coords));
    T *dst_data = reinterpret_cast<T *>(dst.buffer() + dst.calcOffset(coords));
    *dst_data = f(src_val, *dst_data);
  });
}
References onert::backend::ITensor::buffer(), onert::backend::ITensor::calcOffset(), coords, and ShapeLoop().