ONE - On-device Neural Engine: onert::dumper::text Namespace Reference
onert::dumper::text Namespace Reference
Functions
std::string formatOperandBrief (ir::OperandIndex ind)
std::string formatOperand (const ir::Graph &, ir::OperandIndex ind)
std::string formatOperation (const ir::Graph &graph, ir::OperationIndex ind)
void dumpGraph (const ir::Graph &graph)
void dumpLoweredGraph (const compiler::LoweredGraph &lgraph)
Function Documentation
dumpGraph()
void onert::dumper::text::dumpGraph (const ir::Graph & graph)
Definition at line 72 of file GraphDumper.cc.
{
  VERBOSE(GraphDumper) << "{\n";
  auto ops_topol = graph.topolSortOperations();
  for (auto op_ind : ops_topol)
  {
    VERBOSE(GraphDumper) << "  " << formatOperation(graph, op_ind) << "\n";
  }
  VERBOSE(GraphDumper) << "}\n";
  VERBOSE(GraphDumper) << std::endl;
}
References formatOperation(), and VERBOSE.
Referenced by dumpLoweredGraph().
dumpLoweredGraph()
void onert::dumper::text::dumpLoweredGraph (const compiler::LoweredGraph & lgraph)
Definition at line 84 of file GraphDumper.cc.
{
  // TODO Graph dump with backend info
  dumpGraph(lgraph.graph());
}
References dumpGraph(), and onert::compiler::LoweredGraph::graph().
formatOperand()
std::string onert::dumper::text::formatOperand (const ir::Graph & , ir::OperandIndex ind)
Definition at line 51 of file GraphDumper.cc.
{
  std::stringstream ss;
  ss << ind;
  // TODO Print shape, type and maybe more
  return ss.str();
}
formatOperandBrief()
std::string onert::dumper::text::formatOperandBrief (ir::OperandIndex ind)
Definition at line 44 of file GraphDumper.cc.
{
  std::stringstream ss;
  ss << ind;
  return ss.str();
}
formatOperation()
std::string onert::dumper::text::formatOperation (const ir::Graph & graph, ir::OperationIndex ind)
Definition at line 59 of file GraphDumper.cc.
{
  std::stringstream ss;
  const auto &op = graph.operations().at(ind);
  ss << formatOperandIndexSequence(op.getOutputs());
  ss << " = ";
  ss << ind << "_" << op.name() << "(";
  ss << formatOperandIndexSequence(op.getInputs());
  ss << ")";
  return ss.str();
}
Referenced by onert::compiler::Linear::dump(), and dumpGraph().