ONE - On-device Neural Engine: nnfw::misc Namespace Reference
nnfw::misc Namespace Reference
Namespaces
namespace benchmark
namespace feature
namespace fp32
namespace kernel
namespace matrix
namespace tensor
namespace vector
Data Structures
class EnvConfigSource
class EnvVar
Class to access environment variable.
class GeneralConfigSource
struct IConfigSource
class RandomGenerator
Class to generate random values.
Functions
template<typename DstType , typename SrcType >
DstType polymorphic_downcast (SrcType *x)
template<typename DstType , typename SrcType >
DstType polymorphic_downcast (SrcType &x)
std::vector< std::string > split (const std::string &s, char delim)
template<typename... Args>
std::string str (Args &&... args)
template<typename InputIt >
std::string join (InputIt first, InputIt last, const std::string &concat)
Function Documentation
join()
template<typename InputIt > std::string nnfw::misc::join (InputIt first, InputIt last, const std::string & concat)
Definition at line 65 of file string_helpers.h.
{
  std::string ret;
  if (first == last)
    return ret;
  ret += *first;
  for (++first; first != last; ++first)
  {
    ret += concat;
    ret += *first;
  }
  return ret;
}
Referenced by nnfw_session::get_config(), and onert::compiler::CompilerOptions::verboseOptions().
polymorphic_downcast() [1/2]
template<typename DstType , typename SrcType > DstType nnfw::misc::polymorphic_downcast (SrcType & x) inline
Definition at line 34 of file polymorphic_downcast.h.
{
  assert(std::addressof(dynamic_cast<DstType>(x)) == std::addressof(x));
  return static_cast<DstType>(x);
}
polymorphic_downcast() [2/2]
template<typename DstType , typename SrcType > DstType nnfw::misc::polymorphic_downcast (SrcType * x) inline
Definition at line 28 of file polymorphic_downcast.h.
{
  assert(dynamic_cast<DstType>(x) == x);
  return static_cast<DstType>(x);
}
split()
std::vector< std::string > nnfw::misc::split (const std::string & s, char delim) inline
Definition at line 46 of file string_helpers.h.
{
  std::stringstream ss(s);
  std::string item;
  std::vector<std::string> elems;
  while (std::getline(ss, item, delim))
  {
    elems.push_back(item);
  }
  return elems;
}
Referenced by onert::compiler::CompilerOptions::fromGlobalConfig(), nnfw_session::load_model_from_nnpackage(), nnfw_session::set_available_backends(), and onert::compiler::ManualSchedulerOptions::setBackendMap().
str()
template<typename... Args> std::string nnfw::misc::str (Args &&... args)
Definition at line 58 of file string_helpers.h.
{
  std::stringstream ss;
  _str(ss, std::forward<Args>(args)...);
  return ss.str();
}
Referenced by onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), and nnfw::misc::tensor::Shape::from().