ONE - On-device Neural Engine: kbenchmark Namespace Reference
kbenchmark Namespace Reference
Namespaces
namespace kernels
namespace operation
Data Structures
class Args
class ConfigFile
class Operation
class OperationLoader
Typedefs
using OperationInfo = std::map< std::string, std::string >
Functions
void check_valid_key (const std::string &key, OperationInfo &info)
std::vector< int > dims (const std::string &src)
std::vector< int > get_key_dims (const std::string &key, OperationInfo &info)
int get_key_int (const std::string &key, OperationInfo &info)
std::string get_key_string (const std::string &key, OperationInfo &info)
Typedef Documentation
OperationInfo
using kbenchmark::OperationInfo = typedef std::map<std::string, std::string>
Definition at line 62 of file ConfigFile.h.
Function Documentation
check_valid_key()
void kbenchmark::check_valid_key (const std::string & key, OperationInfo & info)
Definition at line 28 of file Utils.h.
{
  OperationInfo::const_iterator it;
  it = info.find(key);
  assert(it != info.end());
}
References info.
Referenced by get_key_dims(), get_key_int(), and get_key_string().
dims()
std::vector< int > kbenchmark::dims (const std::string & src)
Definition at line 35 of file Utils.h.
{
  std::vector<int> dim;
  std::stringstream ss(src);
  int i;
  while (ss >> i)
  {
    dim.push_back(i);
    if (ss.peek() == ',')
      ss.ignore();
  }
  return dim;
}
Referenced by get_key_dims().
get_key_dims()
std::vector< int > kbenchmark::get_key_dims (const std::string & key, OperationInfo & info)
Definition at line 50 of file Utils.h.
{
  check_valid_key(key, info);
  return dims(info[key]);
}
References check_valid_key(), dims(), and info.
Referenced by kbenchmark::operation::Convolution::params(), and kbenchmark::operation::TransposeConv::params().
get_key_int()
int kbenchmark::get_key_int (const std::string & key, OperationInfo & info)
Definition at line 56 of file Utils.h.
{
  check_valid_key(key, info);
  return std::stoi(info[key]);
}
References check_valid_key(), and info.
Referenced by kbenchmark::operation::Convolution::params(), and kbenchmark::operation::TransposeConv::params().
get_key_string()
std::string kbenchmark::get_key_string (const std::string & key, OperationInfo & info)
Definition at line 62 of file Utils.h.
{
  check_valid_key(key, info);
  return info[key];
}
References check_valid_key(), and info.
Referenced by kbenchmark::operation::Convolution::params(), and kbenchmark::operation::TransposeConv::params().