ONE - On-device Neural Engine: nnkit::support::tftestinfo Namespace Reference
nnkit::support::tftestinfo Namespace Reference
Data Structures
class ParsedTensor
Class to store tensor information parsed from test.info file under moco/test/tf.
Enumerations
enum class DataType { FLOAT32 }
Supported Data Types.
Functions
std::vector< std::unique_ptr< ParsedTensor > > parse (const char *info_path)
Function to parse test.info.
std::unique_ptr< ParsedTensor > parse_line (std::string &line)
Function to parse a line of test.info file Examples:
Enumeration Type Documentation
DataType
enum class nnkit::support::tftestinfo::DataType strong
Supported Data Types.
Enumerator
FLOAT32
Definition at line 38 of file ParsedTensor.h.
{
  FLOAT32, // IEEE 32-bit floating point
  /* To be added */
};
Function Documentation
parse()
std::vector< std::unique_ptr< ParsedTensor > > nnkit::support::tftestinfo::parse (const char * info_path)
Function to parse test.info.
Definition at line 204 of file TensorInfoParser.cpp.
{
  std::ifstream infile;
  infile.open(info_path);
  if (infile.fail())
  {
    throw oops::UserExn("Fail to open file", "path", info_path);
  }
  std::vector<std::unique_ptr<ParsedTensor>> tensors;
  std::string line;
  while (std::getline(infile, line))
  {
    auto tensor = parse_line(line);
    if (tensor)
      tensors.emplace_back(std::move(tensor));
  }
  return tensors;
}
References parse_line().
Referenced by nnkit::support::moco::tf::Backend::Backend(), nnkit::support::tf::Backend::Backend(), and main().
parse_line()
std::unique_ptr< ParsedTensor > nnkit::support::tftestinfo::parse_line (std::string & line)
Function to parse a line of test.info file Examples:
"input, in/placeholder_32:0, TF_INT32, [3, 4, 2, 3]"
"output, result:0, TF_FLOAT, []"
Definition at line 143 of file TensorInfoParser.cpp.
{
  // parsed data
  ParsedTensor::Kind kind;
  std::string name;
  TF_DataType dtype;
  std::vector<int32_t> shape;
  remove_comment(line);
  if (line.length() == 0) // empty line or line with comment
    return nullptr;
  std::string tok, trimmed, dim;
  std::istringstream line_stream(line);
  CHECK_NOT_NULL(std::getline(line_stream, tok, ',')); // kind
  kind = get_kind(trim(tok));
  CHECK_NOT_NULL(std::getline(line_stream, tok, ',')); // tensor name
  trimmed = trim(tok);
  if (!validate_name(trimmed))
    throw oops::UserExn("Tensor name in wrong format", "name", tok);
  name.assign(trimmed);
  CHECK_NOT_NULL(std::getline(line_stream, tok, ',')); // data type
  dtype = get_dtype(trim(tok));
  CHECK_NOT_NULL(std::getline(line_stream, tok, '[')); // start of shape
  trimmed = trim(tok);
  if (trimmed.length())
    throw oops::UserExn("Unknown token between data type and shape", "token", tok);
  CHECK_NOT_NULL(std::getline(line_stream, tok, ']'));
  std::istringstream shape_stream(tok);
  bool first = true;
  while (std::getline(shape_stream, dim, ',')) // each dim
  {
    dim = trim(dim);
    if (first && dim.length() == 0)
      continue; // scalar
    first = false;
    if (dim.length() == 0)
      throw oops::UserExn("Empty dim in shape", "shape", tok);
    if (!validate_num(dim))
      throw oops::UserExn("Dim in shape must be a number", "dim", dim);
    shape.emplace_back(std::stoi(dim));
  }
  return std::make_unique<ParsedTensor>(kind, name, dtype, shape);
}
References CHECK_NOT_NULL.
Referenced by parse().