ONE - On-device Neural Engine: nncc::core::ADT::tensor Namespace Reference
nncc::core::ADT::tensor Namespace Reference
Data Structures
struct Accessor
class Buffer
class Index
class IndexEnumerator
class Layout
struct LexicalLayout
class Overlay
struct Reader
class Shape
class View
Functions
template<typename T , typename LayoutImpl >
Buffer< T > make_buffer (const Shape &shape)
Index operator+ (const Index &lhs, const Index &rhs)
bool operator== (const Index &lhs, const Index &rhs)
template<typename T , typename LayoutImpl >
Overlay< T > make_overlay (const Shape &shape, T *base)
uint64_t num_elements (const Shape &)
Shape squeeze (const Shape &)
bool operator== (const Shape &, const Shape &)
Function Documentation
make_buffer()
template<typename T , typename LayoutImpl > Buffer< T > nncc::core::ADT::tensor::make_buffer (const Shape & shape)
Definition at line 47 of file Buffer.h.
{
  return Buffer<T>{shape, LayoutImpl{}};
}
Referenced by nnkit::support::moco::tf::Backend::prepare().
make_overlay()
template<typename T , typename LayoutImpl > Overlay< T > nncc::core::ADT::tensor::make_overlay (const Shape & shape, T * base)
Definition at line 48 of file Overlay.h.
{
  return Overlay<T>{shape, LayoutImpl{}, base};
}
Referenced by nnkit::support::moco::tf::OutputTensorContext::getConstFloatTensor(), nnkit::support::tf::TensorContext::getConstFloatTensor(), nnkit::support::caffe::TensorContext< DType >::getConstFloatTensor(), nnkit::support::onnx::TensorContext::getConstFloatTensor(), nnkit::support::tflite::TensorContext::getConstFloatTensor(), nnkit::support::tf::TensorContext::getMutableFloatTensor(), nnkit::support::caffe::TensorContext< DType >::getMutableFloatTensor(), nnkit::support::onnx::TensorContext::getMutableFloatTensor(), and nnkit::support::tflite::TensorContext::getMutableFloatTensor().
num_elements()
uint64_t nncc::core::ADT::tensor::num_elements (const Shape & shape)
NOTE num_elements returns 1 for rank-0 tensors
Definition at line 51 of file Shape.cpp.
{
  uint64_t res = 1;
  for (uint32_t axis = 0; axis < shape.rank(); ++axis)
  {
    res *= shape.dim(axis);
  }
  return res;
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::rank().
Referenced by coco::Arg::Arg(), HD5ExportAction::run(), and HD5ImportAction::run().
operator+()
Index nncc::core::ADT::tensor::operator+ (const Index & lhs, const Index & rhs)
Definition at line 52 of file Index.cpp.
{
  if (lhs.rank() != rhs.rank())
    throw std::runtime_error("Two tensors should have same rank");
  Index ret;
  ret.resize(lhs.rank());
  for (uint32_t axis = 0; axis < lhs.rank(); axis++)
  {
    ret.at(axis) = lhs.at(axis) + rhs.at(axis);
  }
  return ret;
}
References nncc::core::ADT::tensor::Index::at(), nncc::core::ADT::tensor::Index::rank(), and nncc::core::ADT::tensor::Index::resize().
operator==() [1/2]
bool nncc::core::ADT::tensor::operator== (const Index & lhs, const Index & rhs)
Definition at line 66 of file Index.cpp.
{
  if (lhs.rank() != rhs.rank())
    return false;
  for (uint32_t axis = 0; axis < lhs.rank(); axis++)
  {
    if (lhs.at(axis) != rhs.at(axis))
      return false;
  }
  return true;
}
References nncc::core::ADT::tensor::Index::at(), and nncc::core::ADT::tensor::Index::rank().
operator==() [2/2]
bool nncc::core::ADT::tensor::operator== (const Shape & lhs, const Shape & rhs)
Definition at line 70 of file Shape.cpp.
{
  if (lhs.rank() != rhs.rank())
  {
    return false;
  }
  for (uint32_t axis = 0; axis < lhs.rank(); ++axis)
  {
    if (lhs.dim(axis) != rhs.dim(axis))
    {
      return false;
    }
  }
  return true;
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::rank().
squeeze()
Shape nncc::core::ADT::tensor::squeeze (const Shape & shape)
Definition at line 63 of file Shape.cpp.
{
  Shape res{shape};
  res.squeeze();
  return res;
}
References nncc::core::ADT::tensor::Shape::squeeze().