ONE - On-device Neural Engine: impl Namespace Reference
impl Namespace Reference
Functions
template<typename T >
OMStatus CircleMean (OMRuntimeKernel &rt_kernel)
template<typename T >
OMStatus CircleReduceMax (OMRuntimeKernel &rt_kernel)
template<typename T >
OMStatus CircleReduceProd (OMRuntimeKernel &rt_kernel)
template<typename T >
OMStatus CircleSum (OMRuntimeKernel &rt_kernel)
Function Documentation
CircleMean()
template<typename T > OMStatus impl::CircleMean (OMRuntimeKernel & rt_kernel)
Definition at line 32 of file Mean.cpp.
{
  constexpr static T kInitValue = 0;
  core::OMReduceDataContext<T> ctx(rt_kernel);
  pal::Reducer<T, pal::ReduceSumFn> reducer(ctx, kInitValue);
  bool is_ok = reducer.Mean();
  if (!is_ok)
  {
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  }
  return Ok;
}
References onert_micro::execute::pal::Reducer< T, ReduceFn >::Mean(), onert_micro::Ok, OM_LOG_AND_RETURN, and onert_micro::UnknownError.
CircleReduceMax()
template<typename T > OMStatus impl::CircleReduceMax (OMRuntimeKernel & rt_kernel)
Definition at line 32 of file ReduceMax.cpp.
{
  constexpr static T kInitValue = std::numeric_limits<T>::lowest();
  core::OMReduceDataContext<T> ctx(rt_kernel);
  pal::Reducer<T, pal::ReduceMaxFn> reducer(ctx, kInitValue);
  bool is_ok = reducer.Reduce();
  if (!is_ok)
  {
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  }
  return Ok;
}
References onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::execute::pal::Reducer< T, ReduceFn >::Reduce(), and onert_micro::UnknownError.
CircleReduceProd()
template<typename T > OMStatus impl::CircleReduceProd (OMRuntimeKernel & rt_kernel)
Definition at line 34 of file ReduceProd.cpp.
{
  constexpr static T kInitValue = 1;
  core::OMReduceDataContext<T> ctx(rt_kernel);
  pal::Reducer<T, pal::ReduceProductFn> reducer(ctx, kInitValue);
  bool is_ok = reducer.Reduce();
  if (!is_ok)
  {
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  }
  return Ok;
}
References onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::execute::pal::Reducer< T, ReduceFn >::Reduce(), and onert_micro::UnknownError.
CircleSum()
template<typename T > OMStatus impl::CircleSum (OMRuntimeKernel & rt_kernel)
Definition at line 30 of file Sum.cpp.
{
  constexpr static T kInitValue = 0;
  core::OMReduceDataContext<T> ctx(rt_kernel);
  pal::Reducer<T, pal::ReduceSumFn> reducer(ctx, kInitValue);
  bool is_ok = reducer.Reduce();
  if (!is_ok)
  {
    OM_LOG_AND_RETURN(UnknownError, "Unknown error encountered");
  }
  return Ok;
}
References onert_micro::Ok, OM_LOG_AND_RETURN, onert_micro::execute::pal::Reducer< T, ReduceFn >::Reduce(), and onert_micro::UnknownError.