ONE - On-device Neural Engine: onert::ir::train Namespace Reference
onert::ir::train Namespace Reference
Namespaces
namespace operation
Data Structures
struct CategoricalCrossentropyParam
class ITrainableOperation
struct LossInfo
struct OptimizerInfo
class TrainableGraph
class TrainableOperation
struct TrainableOperationVisitor
class TrainingIndex
Class that provides index of tensor for training.
class TrainingInfo
class UseDefChain
Typedefs
using TrainingOperationIndex = TrainingIndex< OperationIndex >
Type that provides index of operation node for training.
using TrainingOperandIndex = TrainingIndex< OperandIndex >
Type that provides index of operand for training.
using UseDefChains = std::unordered_map< TrainingOperandIndex, UseDefChain >
Enumerations
enum class LossCode { Undefined , MeanSquaredError , CategoricalCrossentropy }
enum class LossReductionType { Undefined , SumOverBatchSize , Sum }
enum class OptimizerCode { Undefined , SGD , Adam }
Functions
std::ostream & operator<< (std::ostream &o, const TrainingOperationIndex &i)
std::ostream & operator<< (std::ostream &o, const TrainingOperandIndex &i)
std::string toString (LossCode opcode)
Convert the optimizer code to the name.
std::string toString (OptimizerCode opcode)
Convert the optimizer code to the name.
Typedef Documentation
TrainingOperandIndex
using onert::ir::train::TrainingOperandIndex = typedef TrainingIndex<OperandIndex>
Type that provides index of operand for training.
Note
TrainingOperandIndex can be index of an operand used in forwarding if the member "_is_forward" of TrainingIndex is true TrainingOperandIndex can be index of an operand used in backwarding if the member "_is_forward" of TrainingIndex is false
Definition at line 132 of file Index.h.
TrainingOperationIndex
using onert::ir::train::TrainingOperationIndex = typedef TrainingIndex<OperationIndex>
Type that provides index of operation node for training.
Note
TrainingOperationIndex can be index of a forwarding node if the member "_is_forward" of TrainingIndex is true TrainingOperationIndex can be index of a backwarding node if the membwr "_is_forward" of TrainingIndex is false
Definition at line 123 of file Index.h.
UseDefChains
using onert::ir::train::UseDefChains = typedef std::unordered_map<TrainingOperandIndex, UseDefChain>
Definition at line 30 of file UseDefChains.h.
Enumeration Type Documentation
LossCode
enum class onert::ir::train::LossCode strong
Enumerator
Undefined
MeanSquaredError
CategoricalCrossentropy
Definition at line 29 of file LossCode.h.
{
  Undefined,              //< Undefined
  MeanSquaredError,       //< MeanSquaredError optimizer
  CategoricalCrossentropy //< CategoricalCrossentropy optimizer
};
LossReductionType
enum class onert::ir::train::LossReductionType strong
Enumerator
Undefined
SumOverBatchSize
Sum
Definition at line 29 of file LossInfo.h.
{
  Undefined,        //< Undefined
  SumOverBatchSize, //< SumOverBatchSize loss reduction type
  Sum,              //< Sum loss reduction type
};
OptimizerCode
enum class onert::ir::train::OptimizerCode strong
Enumerator
Undefined
SGD
Adam
Definition at line 31 of file OptimizerCode.h.
{
  Undefined, //< Undefined
  SGD,       //< SGD optimizer
  Adam       //< Adam optimizer
};
Function Documentation
operator<<() [1/2]
std::ostream & onert::ir::train::operator<< (std::ostream & o, const TrainingOperandIndex & i) inline
Definition at line 139 of file Index.h.
{
  return operator<<(o, i.index());
}
References onert::ir::train::TrainingIndex< T >::index(), and operator<<().
operator<<() [2/2]
std::ostream & onert::ir::train::operator<< (std::ostream & o, const TrainingOperationIndex & i) inline
Definition at line 134 of file Index.h.
{
  return operator<<(o, i.index());
}
References onert::ir::train::TrainingIndex< T >::index(), and operator<<().
Referenced by operator<<(), and operator<<().
toString() [1/2]
std::string onert::ir::train::toString (LossCode opcode)
Convert the optimizer code to the name.
Parameters
opcode The optimizer code
Returns
The name of the optimizer
Definition at line 28 of file LossCode.cc.
{
  static const std::unordered_map<LossCode, const char *> map{
    {LossCode::Undefined, "Undefined"},
    {LossCode::MeanSquaredError, "MeanSquaredError"},
    {LossCode::CategoricalCrossentropy, "CategoricalCrossentropy"}};
  return map.at(code);
}
References CategoricalCrossentropy, MeanSquaredError, and Undefined.
Referenced by onert::backend::train::createOptimizer(), and onert::ir::train::operation::Loss::name().
toString() [2/2]
std::string onert::ir::train::toString (OptimizerCode opcode)
Convert the optimizer code to the name.
Parameters
opcode The optimizer code
Returns
The name of the optimizer
Definition at line 28 of file OptimizerCode.cc.
{
  static const std::unordered_map<OptimizerCode, const char *> map{
    {OptimizerCode::Undefined, "Undefined"},
    {OptimizerCode::SGD, "SGD"},
    {OptimizerCode::Adam, "Adam"}};
  return map.at(code);
}
References Adam, SGD, and Undefined.