ONE - On-device Neural Engine: onert::interp::fc Namespace Reference
onert::interp::fc Namespace Reference
Functions
void prepareFC (ExecEnv *env, const ir::Operation &node)
void invoke (const ITensor *ifm_tensor, const ITensor *ker_tensor, const ITensor *bias_tensor, const ITensor *ofm_tensor, const ir::operation::FullyConnected::Param &param)
void invokeFC (const ExecEnv *env, const ir::Operation &node)
Function Documentation
invoke()
void onert::interp::fc::invoke (const ITensor * ifm_tensor, const ITensor * ker_tensor, const ITensor * bias_tensor, const ITensor * ofm_tensor, const ir::operation::FullyConnected::Param & param)
Definition at line 76 of file FullyConnected.cc.
{
  const auto ifm_buffer = ifm_tensor->bufferRO();
  const auto ker_buffer = ker_tensor->bufferRO();
  const auto bias_buffer = bias_tensor->bufferRO();
  auto ofm_buffer = ofm_tensor->buffer();
  // Calculate
  nnfw::cker::FullyConnectedParams cker_param;
  cker_param.activation = convertActivationType(param.activation);
  const auto cker_ifm_shape = convertShape(ifm_tensor->tensorInfo().shape());
  const auto cker_ker_shape = convertShape(ker_tensor->tensorInfo().shape());
  const auto cker_bias_shape = convertShape(bias_tensor->tensorInfo().shape());
  const auto cker_ofm_shape = convertShape(ofm_tensor->tensorInfo().shape());
  const float *ifm_ptr = reinterpret_cast<const float *>(ifm_buffer);
  const float *ker_ptr = reinterpret_cast<const float *>(ker_buffer);
  const float *bias_ptr = reinterpret_cast<const float *>(bias_buffer);
  float *ofm_ptr = reinterpret_cast<float *>(ofm_buffer);
  nnfw::cker::FullyConnected(cker_param, cker_ifm_shape, ifm_ptr, cker_ker_shape, ker_ptr,
                             cker_bias_shape, bias_ptr, cker_ofm_shape, ofm_ptr);
}
References nnfw::cker::FullyConnectedParams::activation, onert::ir::operation::FullyConnected::Param::activation, onert::interp::ITensor::buffer(), onert::interp::ITensor::bufferRO(), onert::interp::convertActivationType(), onert::interp::convertShape(), nnfw::cker::FullyConnected(), onert::ir::OperandInfo::shape(), and onert::interp::ITensor::tensorInfo().
Referenced by invokeFC().
invokeFC()
void onert::interp::fc::invokeFC (const ExecEnv * env, const ir::Operation & node)
Definition at line 100 of file FullyConnected.cc.
{
  const auto &conv_node =
    nnfw::misc::polymorphic_downcast<const ir::operation::FullyConnected &>(node);
  const auto ifm_index = node.getInputs().at(ir::operation::FullyConnected::INPUT);
  const auto ker_index = node.getInputs().at(ir::operation::FullyConnected::WEIGHT);
  const auto bias_index = node.getInputs().at(ir::operation::FullyConnected::BIAS);
  const auto ofm_index = node.getOutputs().at(0);
  const auto ifm_tensor = env->tensorAt(ifm_index);
  const auto ker_tensor = env->tensorAt(ker_index);
  const auto bias_tensor = env->tensorAt(bias_index);
  const auto ofm_tensor = env->tensorAt(ofm_index);
  const auto data_type = ifm_tensor->data_type();
  if (data_type == ir::DataType::FLOAT32)
  {
    invoke(ifm_tensor, ker_tensor, bias_tensor, ofm_tensor, conv_node.param());
  }
  else
  {
    throw std::runtime_error{"NYI: Support float only"};
  }
}
References onert::ir::OperandIndexSequence::at(), onert::ir::operation::FullyConnected::BIAS, onert::interp::ITensor::data_type(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::FullyConnected::INPUT, invoke(), onert::interp::ExecEnv::tensorAt(), and onert::ir::operation::FullyConnected::WEIGHT.
Referenced by onert::interp::getFullyConnected().
prepareFC()
void onert::interp::fc::prepareFC (ExecEnv * env, const ir::Operation & node)
Definition at line 32 of file FullyConnected.cc.
{
  const auto in_index = node.getInputs().at(ir::operation::FullyConnected::INPUT);
  const auto kernel_index = node.getInputs().at(ir::operation::FullyConnected::WEIGHT);
  const auto bias_index = node.getInputs().at(ir::operation::FullyConnected::BIAS);
  const auto out_index = node.getOutputs().at(0);
  const auto in_tensor = env->tensorAt(in_index);
  const auto kernel_tensor = env->tensorAt(kernel_index);
  const auto bias_tensor = env->tensorAt(bias_index);
  UNUSED_RELEASE(in_tensor);
  UNUSED_RELEASE(kernel_tensor);
  UNUSED_RELEASE(bias_tensor);
  assert(in_tensor->getShape().rank() >= 2);
  assert(kernel_tensor->getShape().rank() == 2);
  assert(bias_tensor->getShape().rank() == 1);
  const auto input_size_with_batch = in_tensor->num_elements();
  const auto num_units = kernel_tensor->getShape().dim(0);
  const auto input_size = kernel_tensor->getShape().dim(1);
  const int32_t batch_size = input_size_with_batch / input_size;
  assert(input_size_with_batch % input_size == 0);
  assert(num_units == bias_tensor->getShape().dim(0));
  // Make output tensor info
  ir::Shape output_shape(2);
  output_shape.dim(0) = batch_size;
  output_shape.dim(1) = num_units;
  const auto out_info =
    ir::OperandInfo::createStaticInfo(output_shape, in_tensor->tensorInfo().typeInfo());
  env->allocateIfNeeded(out_index, out_info);
  auto out_tensor = env->tensorAt(out_index);
  UNUSED_RELEASE(out_tensor);
  // Handle same ifm & ofm data type only
  assert(in_tensor->data_type() == out_tensor->data_type());
  assert(out_tensor->getShape().rank() == 2);
  assert(out_tensor->getShape().dim(0) == batch_size);
  assert(out_tensor->getShape().dim(1) == num_units);
}
References onert::interp::ExecEnv::allocateIfNeeded(), onert::ir::OperandIndexSequence::at(), onert::ir::operation::FullyConnected::BIAS, onert::ir::OperandInfo::createStaticInfo(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::ir::operation::FullyConnected::INPUT, onert::interp::ExecEnv::tensorAt(), UNUSED_RELEASE, and onert::ir::operation::FullyConnected::WEIGHT.
Referenced by onert::interp::getFullyConnected().