ONE - On-device Neural Engine: nnfw::misc::tensor Namespace Reference
nnfw::misc::tensor Namespace Reference
Data Structures
class Comparator
Class to compare two tensors (expected and obtained to compare)
struct Diff
Struct to have information after comparing two elements of two tensors.
struct Index
Struct to represent index of each dimension of a tensor.
class IndexEnumerator
Class to enumerate index of a tensor.
class IndexFormatter
Class to send Index object to output stream.
class IndexIterator
Class to iterate indexes available for given shape.
class NonIncreasingStride
Class to represent strides where stride[N-1] >= stride[N] holds for all N < rank.
class Object
Class to build a tensor using specific generator.
struct Reader
Struct to read element of tensor.
class Shape
Class to represent shape of a tensor.
class Zipper
Class to apply a function with three params: Index, elements of a tensor at passed index read by Reader objects.
Functions
std::ostream & operator<< (std::ostream &os, const IndexFormatter &fmt)
Send IndexFormatter object to output stream.
IndexIterator iterate (const Shape &shape)
Get an IndexItator object.
template<typename Callable >
IndexIterator & operator<< (IndexIterator &&it, Callable cb)
Iterate all indexes and apply a function.
bool operator== (const Shape &, const Shape &)
Check equality of two Shape.
std::ostream & operator<< (std::ostream &os, const Shape &shape)
Send Shape to std::ostream.
template<typename T , typename Callable >
const Zipper< T > & operator<< (const Zipper< T > &zipper, Callable cb)
Apply cb by using lhs and rhs passed to the constructor of zipper.
template<typename T >
Zipper< T > zip (const Shape &shape, const Reader< T > &lhs, const Reader< T > &rhs)
Get Zipper object constructed using passed params.
Function Documentation
iterate()
IndexIterator nnfw::misc::tensor::iterate (const Shape & shape) inline
Get an IndexItator object.
Parameters
[in] shape Shape of tensor of which index will be iterated
Returns
IndexIterator object
Definition at line 89 of file IndexIterator.h.
{ return IndexIterator{shape}; }
Referenced by nnfw::misc::tensor::Object< T >::Object(), and nnfw::misc::tensor::Zipper< T >::zip().
operator<<() [1/4]
template<typename T , typename Callable > const Zipper< T > & nnfw::misc::tensor::operator<< (const Zipper< T > & zipper, Callable cb)
Apply cb by using lhs and rhs passed to the constructor of zipper.
Parameters
[in] zipper Zipper object
[in] cb Function to zpply using zip function
Returns
zipper object after applying cb to zipper
Definition at line 82 of file Zipper.h.
{
  zipper.zip(cb);
  return zipper;
}
References nnfw::misc::tensor::Zipper< T >::zip().
operator<<() [2/4]
template<typename Callable > IndexIterator & nnfw::misc::tensor::operator<< (IndexIterator && it, Callable cb)
Iterate all indexes and apply a function.
Parameters
[in] it IndexIterator object that is constructed with a tensor shape
[in] cb A function that will receive a specific index. Inside the function, the index is used to manipulate tensor element.
Returns
IndexIterator object
Definition at line 98 of file IndexIterator.h.
{
  return it.iter(cb);
}
operator<<() [3/4]
std::ostream & nnfw::misc::tensor::operator<< (std::ostream & os, const IndexFormatter & fmt)
Send IndexFormatter object to output stream.
Parameters
[in] os Output stream
[in] fmt IndexFormatter object that is sent to output stream
Returns
Output stream
Definition at line 28 of file IndexFormatter.cpp.
{
  const auto rank = fmt.index().rank();
  assert(rank > 0);
  os << fmt.index().at(0);
  if (rank > 1)
  {
    for (uint32_t axis = 1; axis < rank; ++axis)
    {
      os << ", " << fmt.index().at(axis);
    }
  }
  return os;
}
operator<<() [4/4]
std::ostream & nnfw::misc::tensor::operator<< (std::ostream & os, const Shape & shape)
Send Shape to std::ostream.
Parameters
[in] os std::ostream to process this Shape
[in] shape Shape to send to ostream
Returns
Reference of std::ostream
Definition at line 90 of file Shape.cpp.
{
  if (shape.rank() > 0)
  {
    os << shape.dim(0);
    for (uint32_t axis = 1; axis < shape.rank(); ++axis)
    {
      os << "," << shape.dim(axis);
    }
  }
  return os;
}
References nnfw::misc::tensor::Shape::dim(), and nnfw::misc::tensor::Shape::rank().
operator==()
bool nnfw::misc::tensor::operator== (const Shape & lhs, const Shape & rhs)
Check equality of two Shape.
Parameters
[in] Shape First shape to compare
[in] Shape Second shape to compare
Returns
true if both shapes are equal, otherwise false
Definition at line 30 of file Shape.cpp.
{
  if (lhs.rank() != rhs.rank())
  {
    return false;
  }
  for (uint32_t axis = 0; axis < lhs.rank(); ++axis)
  {
    if (lhs.dim(axis) != rhs.dim(axis))
    {
      return false;
    }
  }
  return true;
}
References nnfw::misc::tensor::Shape::dim(), and nnfw::misc::tensor::Shape::rank().
zip()
template<typename T > Zipper< T > nnfw::misc::tensor::zip (const Shape & shape, const Reader< T > & lhs, const Reader< T > & rhs)
Get Zipper object constructed using passed params.
Parameters
shape Shape of lhs and rhs
lhs Reader object of a tensor
rhs Reader object of a tensor
Returns
Zipper object
Definition at line 95 of file Zipper.h.
{
  return Zipper<T>{shape, lhs, rhs};
}
Referenced by nnfw::misc::tensor::Comparator::compare(), and TfLiteInterpMatchApp::compareSingleTensorView().