ONE - On-device Neural Engine: nnfw::cker::multithreaded Namespace Reference
nnfw::cker::multithreaded Namespace Reference
Functions
void Conv (const ConvParams &params, const Shape &input_shape, const float *input_data, const Shape &filter_shape, const float *filter_data, const Shape &bias_shape, const float *bias_data, const Shape &output_shape, float *output_data)
Function Documentation
Conv()
void nnfw::cker::multithreaded::Conv (const ConvParams & params, const Shape & input_shape, const float * input_data, const Shape & filter_shape, const float * filter_data, const Shape & bias_shape, const float * bias_data, const Shape & output_shape, float * output_data) inline
Definition at line 254 of file Conv.h.
{
  const Eigen::ThreadPoolDevice &device = *eigen_support::GetThreadPoolDevice();
  const int stride_width = params.stride_width;
  const int stride_height = params.stride_height;
  const PaddingType padding = params.padding_type;
  const int pad_width = params.padding_values.width;
  const int pad_height = params.padding_values.height;
  const float output_activation_min = params.float_activation_min;
  const float output_activation_max = params.float_activation_max;
  assert(input_shape.DimensionsCount() == 4);
  assert(filter_shape.DimensionsCount() == 4);
  assert(output_shape.DimensionsCount() == 4);
  const int batches = MatchingDim(input_shape, 0, output_shape, 0);
  const int input_depth = MatchingDim(input_shape, 3, filter_shape, 3);
  const int output_depth = MatchingDim(filter_shape, 0, output_shape, 3);
  const int input_height = input_shape.Dims(1);
  const int input_width = input_shape.Dims(2);
  const int filter_height = filter_shape.Dims(1);
  const int filter_width = filter_shape.Dims(2);
  const int output_height = output_shape.Dims(1);
  const int output_width = output_shape.Dims(2);
  EigenTensorConvFunctor<float> conv_functor;
  conv_functor(device, input_data, batches, input_height, input_width, input_depth, filter_data,
               filter_height, filter_width, output_depth, stride_height, stride_width, pad_height,
               pad_width, padding, output_data, output_height, output_width);
  optimized::AddBiasAndEvalActivationFunction(output_activation_min, output_activation_max,
                                              bias_shape, bias_data, output_shape, output_data);
}
References nnfw::cker::optimized::AddBiasAndEvalActivationFunction(), nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), nnfw::cker::ConvParams::float_activation_max, nnfw::cker::ConvParams::float_activation_min, nnfw::cker::eigen_support::GetThreadPoolDevice(), nnfw::cker::PaddingValues::height, nnfw::cker::MatchingDim(), nnfw::cker::ConvParams::padding_type, nnfw::cker::ConvParams::padding_values, nnfw::cker::ConvParams::stride_height, nnfw::cker::ConvParams::stride_width, and nnfw::cker::PaddingValues::width.
Referenced by nnfw::cker::Conv::operator()().