ONE - On-device Neural Engine: test_utils Namespace Reference
test_utils Namespace Reference
Data Structures
class TestCase
class TestRunner
Functions
_dump_npy_included_json (str output_dir, dict json_content)
_str_to_npy_dtype (str dtype_str)
dict gen_random_tensor (str dtype_str, typing.Tuple[int] scale_shape, typing.Tuple[int] zerop_shape, int quantized_dimension, typing.Optional[typing.Tuple[int]] value_shape=None)
Function Documentation
_dump_npy_included_json()
test_utils._dump_npy_included_json (str output_dir, dict json_content) protected
Dump json and npy files to output_dir
Definition at line 7 of file test_utils.py.
def _dump_npy_included_json(output_dir: str, json_content: dict):
    """
    Dump json and npy files to output_dir
    """
    # Create output_dir if not exists
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    # file name for npy data (ex: 0.npy, 1.npy, ...)
    _index = 0
    _index_to_value = dict()
    # Replace npy to the path to the npy file
    for tensor_name, qparam in json_content.items():
        assert type(tensor_name) == str
        assert type(qparam) == dict
        for field, value in qparam.items():
            if isinstance(value, np.ndarray):
                npy_name = str(_index) + '.npy'
                # Save npy file
                np.save(os.path.join(output_dir, npy_name), value)
                # Replace to the path to the npy file
                json_content[tensor_name][field] = npy_name
                # Save the mapping from index to tensor name
                _index_to_value[_index] = tensor_name + "_" + field
                _index += 1
    # Dump json
    with open(os.path.join(output_dir, 'qparam.json'), 'w') as f:
        json.dump(json_content, f, indent=2)
Referenced by test_utils.TestRunner.run().
_str_to_npy_dtype()
test_utils._str_to_npy_dtype (str dtype_str) protected
Definition at line 42 of file test_utils.py.
def _str_to_npy_dtype(dtype_str: str):
    if dtype_str == "uint8":
        return np.uint8
    if dtype_str == "int16":
        return np.int16
    if dtype_str == "int32":
        return np.int32
    if dtype_str == "int64":
        return np.int64
    raise SystemExit("Unsupported npy dtype", dtype_str)
Referenced by gen_random_tensor().
gen_random_tensor()
dict test_utils.gen_random_tensor (str dtype_str, typing.Tuple[int] scale_shape, typing.Tuple[int] zerop_shape, int quantized_dimension, typing.Optional[typing.Tuple[int]] value_shape = None)
Definition at line 54 of file test_utils.py.
                      value_shape: typing.Optional[typing.Tuple[int]] = None) -> dict:
    content = dict()
    content['dtype'] = dtype_str
    content['scale'] = np.random.rand(scale_shape).astype(np.float32)
    # Why 256? To ensure the smallest dtype (uint8) range [0, 256)
    content['zerop'] = np.random.randint(256, size=zerop_shape, dtype=np.int64)
    content['quantized_dimension'] = quantized_dimension
    if value_shape != None:
        dtype = _str_to_npy_dtype(dtype_str)
        content['value'] = np.random.randint(256, size=value_shape, dtype=dtype)
    return content
References _str_to_npy_dtype().