ONE - On-device Neural Engine: oops Namespace Reference
oops Namespace Reference
Data Structures
class InternalExn
Exception caused by internal error.
class UserExn
Exception to user.
Functions
template<typename T >
uint32_t to_uint32 (T a)
Function Documentation
to_uint32()
template<typename T > uint32_t oops::to_uint32 (T a)
Definition at line 32 of file InternalExn.h.
{ return static_cast<uint32_t>(a); }
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert(), exo::ConstGenConverter::convert(), exo::TensorReduceConverter::convert(), exo::TensorTransposeConverter::convert(), exo::circle_detail::getOpPadding(), exo::tflite_detail::getOpPadding(), luci::getOpPadding(), exo::to_circle_actfunc(), luci::to_circle_actfunc(), luci::to_circle_dimensiontype(), luci::to_circle_mirrorpadmode(), luci::to_circle_sparse_index_vector(), luci::to_circle_sparse_index_vector_type(), luci::to_circle_tensortype(), luci::to_circle_weightsformat(), exo::to_shape_description(), luci::to_shape_description(), exo::to_tflite_actfunc(), and luci::to_tflite_sparsity().