ONE - On-device Neural Engine: moco::tf::test Namespace Reference
moco::tf::test Namespace Reference
Data Structures
class TFNodeBuildTester
Functions
template<typename T >
T * find_first_node_bytype (loco::Graph *g)
template<typename T >
std::vector< T * > find_nodes_bytype (loco::Graph *g)
void setup_output_node (loco::Graph *graph, loco::Node *last_node)
Append setup output of graph by adding loco::Push node.
Function Documentation
find_first_node_bytype()
template<typename T > T * moco::tf::test::find_first_node_bytype (loco::Graph * g)
Definition at line 33 of file TestHelper.h.
{
  T *first_node = nullptr;
  loco::Graph::NodeContext *nodes = g->nodes();
  uint32_t count = nodes->size();
  for (uint32_t i = 0; i < count; ++i)
  {
    first_node = dynamic_cast<T *>(nodes->at(i));
    if (first_node != nullptr)
      break;
  }
  return first_node;
}
References loco::ObjectPool< T >::at(), and loco::ObjectPool< T >::size().
find_nodes_bytype()
template<typename T > std::vector< T * > moco::tf::test::find_nodes_bytype (loco::Graph * g)
Definition at line 49 of file TestHelper.h.
{
  std::vector<T *> find_nodes;
  loco::Graph::NodeContext *nodes = g->nodes();
  uint32_t count = nodes->size();
  for (uint32_t i = 0; i < count; ++i)
  {
    auto node = dynamic_cast<T *>(nodes->at(i));
    if (node != nullptr)
      find_nodes.push_back(node);
  }
  return find_nodes;
}
References loco::ObjectPool< T >::at(), and loco::ObjectPool< T >::size().
setup_output_node()
void moco::tf::test::setup_output_node (loco::Graph * graph, loco::Node * last_node)
Append setup output of graph by adding loco::Push node.
Note
This is subject to change when loco changes I/O treatment