ONE - On-device Neural Engine: tfkit Namespace Reference
tfkit Namespace Reference
Namespaces
namespace tf
Data Structures
class CmdArguments
struct ConvertCommand
struct DecodeCommand
struct EncodeCommand
class IOConfiguration
struct PackCommand
struct UnpackCommand
Functions
std::unique_ptr< IOConfiguration > make_ioconfig (const CmdArguments &cmdargs)
Function Documentation
make_ioconfig()
std::unique_ptr< IOConfiguration > tfkit::make_ioconfig (const CmdArguments & cmdargs)
Definition at line 111 of file Support.cpp.
{
  auto iocfg = std::make_unique<IOConfiguration>();
  auto in = open_fstream<std::ifstream>(cmdargs.get_or(0, "-"), std::ios::in | std::ios::binary);
  iocfg->in(std::move(in));
  auto out = open_fstream<std::ofstream>(cmdargs.get_or(1, "-"), std::ios::out | std::ios::binary);
  iocfg->out(std::move(out));
  return iocfg;
}
References tfkit::CmdArguments::get_or().
Referenced by tfkit::ConvertCommand::run(), tfkit::DecodeCommand::run(), tfkit::EncodeCommand::run(), tfkit::PackCommand::run(), and tfkit::UnpackCommand::run().