ONE - On-device Neural Engine: moco::test Namespace Reference
moco::test Namespace Reference
Data Structures
class TFNodeBuildTester
Functions
template<typename T >
T * find_first_node_bytype (loco::Graph *g)
template<typename T >
std::vector< T * > find_nodes_bytype (loco::Graph *g)
void setup_output_node (loco::Graph *graph, loco::Node *last_node)
Append setup output of graph by adding loco::Push node.
Function Documentation
find_first_node_bytype()
template<typename T > T * moco::test::find_first_node_bytype (loco::Graph * g)
Definition at line 35 of file TestHelper.h.
{
  T *first_node = nullptr;
  loco::Graph::NodeContext *nodes = g->nodes();
  uint32_t count = nodes->size();
  for (uint32_t i = 0; i < count; ++i)
  {
    first_node = dynamic_cast<T *>(nodes->at(i));
    if (first_node != nullptr)
      break;
  }
  return first_node;
}
References loco::ObjectPool< T >::at(), and loco::ObjectPool< T >::size().
find_nodes_bytype()
template<typename T > std::vector< T * > moco::test::find_nodes_bytype (loco::Graph * g)
Definition at line 42 of file TestHelper.h.
{
  std::vector<T *> find_nodes;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (auto T_node = as<T>(node))
    {
      find_nodes.push_back(T_node);
    }
  }
  return find_nodes;
}
References loco::active_nodes(), and loco::output_nodes().
setup_output_node()
void moco::test::setup_output_node (loco::Graph * graph, loco::Node * last_node)
Append setup output of graph by adding loco::Push node.
Note
This is subject to change when loco changes I/O treatment
Note
This is subject to change when loco changes I/O treatment