ONE - On-device Neural Engine: onert::backend::trix Namespace Reference
onert::backend::trix Namespace Reference
Namespaces
namespace ops
Data Structures
class Backend
class BackendContext
class BatchThreadPool
Class that has a threadpool for batch-by-batch multi-threading.
class Config
class DevContext
NPU device context of trix backend.
class KernelGenerator
Typedefs
using ModelID = uint32_t
using Tensor = basic::Tensor
using ExternalTensor = basic::ExternalTensor
using TensorBuilder = basic::TensorBuilder
Functions
data_layout convertDataLayout (const ir::Layout layout)
Convert type of layout from onert type to npu type.
data_type convertDataType (const ir::DataType type)
Convert type of data from onert type to npu type.
template<typename T , std::enable_if_t< std::is_base_of< IPortableTensor, T >::value, bool > = true>
void setDataInfo (const std::vector< T * > &tensors, tensors_data_info *info)
Set the tensors_data_info object.
template<typename T , std::enable_if_t< std::is_base_of< IPortableTensor, T >::value, bool > = true>
void setBuffers (const std::vector< T * > &tensors, generic_buffers *buf)
Set the generic_buffers object.
Typedef Documentation
ExternalTensor
using onert::backend::trix::ExternalTensor = typedef basic::ExternalTensor
Definition at line 31 of file Tensor.h.
ModelID
using onert::backend::trix::ModelID = typedef uint32_t
Definition at line 34 of file DevContext.h.
Tensor
using onert::backend::trix::Tensor = typedef basic::Tensor
Definition at line 30 of file Tensor.h.
TensorBuilder
using onert::backend::trix::TensorBuilder = typedef basic::TensorBuilder
Definition at line 29 of file TensorBuilder.h.
Function Documentation
convertDataLayout()
data_layout onert::backend::trix::convertDataLayout (const ir::Layout layout)
Convert type of layout from onert type to npu type.
Parameters
layout Layout type in onert
Returns
data_layout Layout type in npu
Definition at line 26 of file Convert.cc.
{
  switch (layout)
  {
    case ir::Layout::NCHW:
      return DATA_LAYOUT_NCHW;
    case ir::Layout::NHWC:
      return DATA_LAYOUT_NHWC;
    default:
      throw std::runtime_error("Unknown Layout");
  }
}
References onert::ir::NCHW, and onert::ir::NHWC.
Referenced by setDataInfo().
convertDataType()
data_type onert::backend::trix::convertDataType (const ir::DataType type)
Convert type of data from onert type to npu type.
Parameters
type Data type in onert
Returns
data_type Data type in npu
Definition at line 39 of file Convert.cc.
{
  switch (type)
  {
    case ir::DataType::QUANT_UINT8_ASYMM:
      return DATA_TYPE_QASYMM8;
    case ir::DataType::QUANT_INT16_SYMM:
      return DATA_TYPE_QSYMM16;
    default:
      throw std::runtime_error("Unsupported data type");
  }
}
Referenced by setDataInfo().
setBuffers()
template<typename T , std::enable_if_t< std::is_base_of< IPortableTensor, T >::value, bool > = true> void onert::backend::trix::setBuffers (const std::vector< T * > & tensors, generic_buffers * buf)
Set the generic_buffers object.
Template Parameters
T Type of tensor based of IPortableTensor
Parameters
tensors Tensors that have buffer information
buf generic_buffers to be set
Definition at line 77 of file Convert.h.
{
  buf->num_buffers = static_cast<uint32_t>(tensors.size());
  for (uint32_t idx = 0; idx < buf->num_buffers; ++idx)
  {
    buf->bufs[idx].addr = tensors[idx]->buffer();
    buf->bufs[idx].size = static_cast<uint64_t>(tensors[idx]->total_size());
    buf->bufs[idx].type = BUFFER_MAPPED;
  }
}
Referenced by onert::backend::trix::ops::BulkLayer::run().
setDataInfo()
template<typename T , std::enable_if_t< std::is_base_of< IPortableTensor, T >::value, bool > = true> void onert::backend::trix::setDataInfo (const std::vector< T * > & tensors, tensors_data_info * info)
Set the tensors_data_info object.
Template Parameters
T Type of tensor based of IPortableTensor
Parameters
tensors Tensors that have data information
info tensors_data_info to be set
Definition at line 58 of file Convert.h.
{
  info->num_info = static_cast<uint32_t>(tensors.size());
  for (uint32_t idx = 0; idx < info->num_info; ++idx)
  {
    info->info[idx].layout = convertDataLayout(tensors[idx]->layout());
    info->info[idx].type = convertDataType(tensors[idx]->data_type());
  }
}
References convertDataLayout(), convertDataType(), and info.
Referenced by onert::backend::trix::ops::BulkLayer::run().