ONE - On-device Neural Engine: npud::util Namespace Reference
npud::util Namespace Reference
Namespaces
namespace config
namespace logging
Functions
void config_source (std::unique_ptr< IConfigSource > &&source)
bool toBool (const std::string &val)
int toInt (const std::string &val)
bool getConfigBool (const std::string &key)
int getConfigInt (const std::string &key)
std::string getConfigString (const std::string &key)
Function Documentation
config_source()
void npud::util::config_source (std::unique_ptr< IConfigSource > && source)
Definition at line 37 of file ConfigSource.cc.
{ _source = std::move(source); }
getConfigBool()
bool npud::util::getConfigBool (const std::string & key)
Definition at line 94 of file ConfigSource.cc.
{
  auto raw = getConfigOrDefault(key);
  return toBool(raw);
}
References toBool().
getConfigInt()
int npud::util::getConfigInt (const std::string & key)
Definition at line 100 of file ConfigSource.cc.
{
  auto raw = getConfigOrDefault(key);
  return toInt(raw);
}
References toInt().
getConfigString()
std::string npud::util::getConfigString (const std::string & key)
Definition at line 106 of file ConfigSource.cc.
{ return getConfigOrDefault(key); }
Referenced by npud::core::DevManager::DevManager().
toBool()
bool npud::util::toBool (const std::string & val)
Definition at line 85 of file ConfigSource.cc.
{
  static const std::array<std::string, 5> false_list{"0", "OFF", "FALSE", "N", "NO"};
  auto false_found = std::find(false_list.begin(), false_list.end(), val);
  return false_found == false_list.end();
}
Referenced by getConfigBool().
toInt()
int npud::util::toInt (const std::string & val)
Definition at line 92 of file ConfigSource.cc.
{ return std::stoi(val); }
Referenced by getConfigInt().