ONE - On-device Neural Engine: onnx-ops Namespace Reference
onnx-ops Namespace Reference
Functions
_dump_operators (onnx_model)
_help_exit (cmd_name)
main ()
Function Documentation
_dump_operators()
onnx-ops._dump_operators (onnx_model) protected
Definition at line 22 of file onnx-ops.py.
def _dump_operators(onnx_model):
    for node in onnx_model.graph.node:
        print(node.op_type)
Referenced by main().
_help_exit()
onnx-ops._help_exit (cmd_name) protected
Definition at line 27 of file onnx-ops.py.
def _help_exit(cmd_name):
    print('Dump ONNX model file Operators')
    print('Usage: {0} [onnx_path]'.format(cmd_name))
    print('')
    exit()
Referenced by main().
main()
onnx-ops.main ()
Definition at line 34 of file onnx-ops.py.
def main():
    if len(sys.argv) < 2:
        _help_exit(os.path.basename(sys.argv[0]))
    onnx_model = onnx.load(sys.argv[1])
    onnx.checker.check_model(onnx_model)
    _dump_operators(onnx_model)
References _dump_operators(), _help_exit(), and main().
Referenced by main().