ONE - On-device Neural Engine: onert::interp::pool2d Namespace Reference
onert::interp::pool2d Namespace Reference
Functions
void preparePool2D (ExecEnv *env, const ir::Operation &node)
template<typename T >
void invoke (const nnfw::cker::PoolParams &params, const nnfw::cker::Shape &in_shape, const T *in_ptr, const nnfw::cker::Shape &out_shape, T *out_ptr, ir::operation::Pool2D::PoolType op_type)
void invokePool2DOps (const ExecEnv *env, const ir::Operation &node)
Function Documentation
invoke()
template<typename T > void onert::interp::pool2d::invoke (const nnfw::cker::PoolParams & params, const nnfw::cker::Shape & in_shape, const T * in_ptr, const nnfw::cker::Shape & out_shape, T * out_ptr, ir::operation::Pool2D::PoolType op_type)
Definition at line 69 of file Pool2D.cc.
{
  switch (op_type)
  {
    case ir::operation::Pool2D::PoolType::AVG:
      nnfw::cker::AveragePool<T>(params, in_shape, in_ptr, out_shape, out_ptr);
      break;
    case ir::operation::Pool2D::PoolType::MAX:
      nnfw::cker::MaxPool<T>(params, in_shape, in_ptr, out_shape, out_ptr);
      break;
    default:
      throw std::runtime_error{"Interp(Pool2D): NYI unsupported operation"};
      break;
  }
}
References onert::ir::operation::Pool2D::AVG, and onert::ir::operation::Pool2D::MAX.
invokePool2DOps()
void onert::interp::pool2d::invokePool2DOps (const ExecEnv * env, const ir::Operation & node)
Definition at line 87 of file Pool2D.cc.
{
  const auto &pool_node = nnfw::misc::polymorphic_downcast<const ir::operation::Pool2D &>(node);
  const auto in_index = node.getInputs().at(0);
  const auto out_index = node.getOutputs().at(0);
  // Check lhs shape is same with rhs (with broadcast)
  const auto in_tensor = env->tensorAt(in_index);
  const auto out_tensor = env->tensorAt(out_index);
  // TODO support NCHW frontend
  const auto ifm_shape = in_tensor->tensorInfo().shape().asFeature(ir::Layout::NHWC);
  const auto ofm_shape = out_tensor->tensorInfo().shape().asFeature(ir::Layout::NHWC);
  const auto param = pool_node.param();
  const auto padding =
    ir::calculatePadding(param.padding, ifm_shape, ofm_shape, param.stride, param.kw, param.kh);
  // Calculate
  nnfw::cker::PoolParams cker_param;
  cker_param.filter_width = param.kw;
  cker_param.filter_height = param.kh;
  cker_param.padding_values.width = padding.left;
  cker_param.padding_values.height = padding.top;
  cker_param.stride_width = param.stride.horizontal;
  cker_param.stride_height = param.stride.vertical;
  const auto data_type = in_tensor->data_type();
  if (data_type == ir::DataType::FLOAT32)
  {
    calculateActivationRange(param.activation, &cker_param.float_activation_min,
                             &cker_param.float_activation_max);
    const auto in_shape = convertShape(in_tensor->tensorInfo().shape());
    const auto out_shape = convertShape(out_tensor->tensorInfo().shape());
    const float *in_ptr = reinterpret_cast<const float *>(in_tensor->bufferRO());
    float *out_ptr = reinterpret_cast<float *>(out_tensor->buffer());
    // Now, invoke() supports only Pool2D in float
    invoke<float>(cker_param, in_shape, in_ptr, out_shape, out_ptr, param.op_type);
  }
  else
  {
    throw std::runtime_error{"NYI: Support float only"};
  }
}
References onert::ir::OperandIndexSequence::at(), onert::interp::calculateActivationRange(), onert::ir::calculatePadding(), onert::interp::convertShape(), nnfw::cker::PoolParams::filter_height, nnfw::cker::PoolParams::filter_width, nnfw::cker::PoolParams::float_activation_max, nnfw::cker::PoolParams::float_activation_min, onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), nnfw::cker::PaddingValues::height, onert::ir::NHWC, nnfw::cker::PoolParams::padding_values, onert::ir::OperandInfo::shape(), nnfw::cker::PoolParams::stride_height, nnfw::cker::PoolParams::stride_width, onert::interp::ExecEnv::tensorAt(), onert::interp::ITensor::tensorInfo(), and nnfw::cker::PaddingValues::width.
Referenced by onert::interp::getPool2D().
preparePool2D()
void onert::interp::pool2d::preparePool2D (ExecEnv * env, const ir::Operation & node)
Definition at line 35 of file Pool2D.cc.
{
  const auto &pool_node = nnfw::misc::polymorphic_downcast<const ir::operation::Pool2D &>(node);
  const auto in_index = node.getInputs().at(pool_node.INPUT);
  const auto out_index = node.getOutputs().at(0);
  const auto in_tensor = env->tensorAt(in_index);
  UNUSED_RELEASE(in_tensor);
  assert(in_tensor->getShape().rank() == 4);
  const auto output_info = env->graph().operands().at(out_index).info();
  if (output_info.total_size() == 0)
  {
    // Handle unspecified output shape
    const auto infered_output_shape =
      shape_inference::inferPoolShape(in_tensor->tensorInfo().shape(), pool_node.param());
    env->allocateIfNeeded(
      out_index, ir::OperandInfo::createStaticInfo(infered_output_shape, output_info.typeInfo()));
  }
  else
  {
    env->allocateIfNeeded(out_index, output_info);
  }
  auto out_tensor = env->tensorAt(out_index);
  UNUSED_RELEASE(out_tensor);
  // Handle same ifm & ofm data type only
  assert(in_tensor->data_type() == out_tensor->data_type());
  assert(out_tensor->getShape().rank() == 4);
}
References onert::interp::ExecEnv::allocateIfNeeded(), onert::util::ObjectManager< Index, Object >::at(), onert::ir::OperandIndexSequence::at(), onert::ir::OperandInfo::createStaticInfo(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::interp::ExecEnv::graph(), onert::shape_inference::inferPoolShape(), onert::ir::Graph::operands(), onert::interp::ExecEnv::tensorAt(), and UNUSED_RELEASE.
Referenced by onert::interp::getPool2D().