ONE - On-device Neural Engine: nnfw::cker::bias_op Namespace Reference
nnfw::cker::bias_op Namespace Reference
Namespaces
namespace functor
Typedefs
using Device = Eigen::ThreadPoolDevice
Functions
template<typename T >
void biasHelper (const Shape &bias_shape, const T *bias_data, const Shape &input_shape, T *input_data, T activation_min, T activation_max)
Typedef Documentation
Device
using nnfw::cker::bias_op::Device = typedef Eigen::ThreadPoolDevice
Definition at line 94 of file bias_op.h.
Function Documentation
biasHelper()
template<typename T > void nnfw::cker::bias_op::biasHelper (const Shape & bias_shape, const T * bias_data, const Shape & input_shape, T * input_data, T activation_min, T activation_max)
Definition at line 97 of file bias_op.h.
{
  [[maybe_unused]] int channel_dim = input_shape.DimensionsCount() - 1;
  assert(input_shape.Dims(channel_dim) == bias_shape.Dims(0));
  assert(input_data);
  assert(bias_data);
  Tensor bias{bias_shape, const_cast<T *>(bias_data)};
  Tensor input{input_shape, input_data};
  functor::Bias<Device, T> functor;
  const Eigen::ThreadPoolDevice &d = *eigen_support::GetThreadPoolDevice();
  functor(d, static_cast<const Tensor &>(input).flat<T>(),
          static_cast<const Tensor &>(bias).flat<T>(), input.flat<T>(), activation_min,
          activation_max);
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), and nnfw::cker::eigen_support::GetThreadPoolDevice().