ONE - On-device Neural Engine: onert::util Namespace Reference
onert::util Namespace Reference
Namespaces
namespace config
namespace logging
Data Structures
class CPUTimer
class Index
A wrapper class for unsigned integral Index NOTE : Max value of the underlying type is used as the invalid value.
class ITimer
class ObjectManager
Class that owns objects and maps them with indices as a handle for them.
class Set
Class for set of custom element &.
class TracingCtx
Class to maintain information about profiling per session.
Typedefs
using CfgKeyValues = std::unordered_map< std::string, std::string >
Functions
template<typename T >
void CalculateActivationRange (ir::Activation activation, T *activation_min, T *activation_max)
void setConfigKeyValues (const CfgKeyValues &keyValues)
bool toBool (const std::string &val)
int toInt (const std::string &val)
bool getConfigBool (const std::string &key)
int getConfigInt (const std::string &key)
std::string getConfigString (const std::string &key)
void config_source (std::unique_ptr< IConfigSource > &&source)
void config_source_ext (std::unique_ptr< IConfigSource > &&source)
Typedef Documentation
CfgKeyValues
using onert::util::CfgKeyValues = typedef std::unordered_map<std::string, std::string>
Definition at line 28 of file ConfigSource.h.
Function Documentation
CalculateActivationRange()
template<typename T > void onert::util::CalculateActivationRange (ir::Activation activation, T * activation_min, T * activation_max)
Definition at line 30 of file CalculateActivationRange.h.
{
  if (activation == ir::Activation::RELU)
  {
    *activation_min = 0;
    *activation_max = std::numeric_limits<T>::max();
  }
  else if (activation == ir::Activation::RELU6)
  {
    *activation_min = 0;
    *activation_max = 6;
  }
  else if (activation == ir::Activation::RELU1)
  {
    *activation_min = -1;
    *activation_max = 1;
  }
  else if (activation == ir::Activation::SIGMOID)
  {
    *activation_min = 0;
    *activation_max = 1;
  }
  else if (activation == ir::Activation::NONE)
  {
    *activation_min = std::numeric_limits<T>::lowest();
    *activation_max = std::numeric_limits<T>::max();
  }
  else
  {
    throw std::runtime_error{"Unsupported fused activation function."};
  }
}
References onert::ir::NONE, onert::ir::RELU, onert::ir::RELU1, onert::ir::RELU6, and onert::ir::SIGMOID.
Referenced by onert::backend::cpu::ops::ConvolutionLayer::convFloat32(), onert::backend::cpu::ops::DepthwiseConvolutionLayer::convFloat32(), onert::backend::ruy::ops::ConvolutionLayer::convFloat32(), onert::backend::cpu::ops::FullyConnectedLayer::fullyConnected16x1Float32(), onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32(), and onert::backend::cpu::ops::PowLayer::powFloat32().
config_source()
void onert::util::config_source (std::unique_ptr< IConfigSource > && source)
Definition at line 39 of file ConfigSource.cc.
{ _source = std::move(source); }
References config_source().
Referenced by config_source().
config_source_ext()
void onert::util::config_source_ext (std::unique_ptr< IConfigSource > && source)
Definition at line 40 of file ConfigSource.cc.
{ _source_ext = std::move(source); }
Referenced by setConfigKeyValues().
getConfigBool()
bool onert::util::getConfigBool (const std::string & key)
Definition at line 118 of file ConfigSource.cc.
{
  auto raw = getConfigOrDefault(key);
  return toBool(raw);
}
References toBool().
Referenced by onert::base_loader::BaseLoader< LoaderDomain >::BaseLoader(), and onert::compiler::CompilerOptions::fromGlobalConfig().
getConfigInt()
int onert::util::getConfigInt (const std::string & key)
Definition at line 124 of file ConfigSource.cc.
{
  auto raw = getConfigOrDefault(key);
  return toInt(raw);
}
References toInt().
Referenced by onert::backend::xnnpack::BackendContext::BackendContext(), onert::backend::cpu::ExternalContext::ExternalContext(), onert::backend::ruy::ExternalContext::ExternalContext(), onert::backend::builtin::ExternalContext::ExternalContext(), and onert::compiler::CompilerOptions::fromGlobalConfig().
getConfigString()
std::string onert::util::getConfigString (const std::string & key)
Definition at line 130 of file ConfigSource.cc.
{ return getConfigOrDefault(key); }
Referenced by onert::compiler::CompilerOptions::fromGlobalConfig(), onert::backend::acl_common::AclBackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator, T_Optimizer >::genTensors(), onert::backend::gpu_cl::BackendContext::genTensors(), onert::backend::basic::genTensors(), onert::backend::acl_cl::Config::supportLayout(), and onert::backend::acl_neon::Config::supportLayout().
setConfigKeyValues()
void onert::util::setConfigKeyValues (const CfgKeyValues & keyValues)
Definition at line 42 of file ConfigSource.cc.
{
  auto configsrc = std::make_unique<GeneralConfigSource>();
  for (auto it = keyValues.begin(); it != keyValues.end(); ++it)
  {
    VERBOSE(NNPKG_CONFIGS) << "(" << it->first << ") = (" << it->second << ")" << std::endl;
    configsrc->set(it->first, it->second);
  }
  onert::util::config_source_ext(std::move(configsrc));
}
References config_source_ext(), and VERBOSE.
Referenced by nnfw_session::load_model_from_nnpackage().
toBool()
bool onert::util::toBool (const std::string & val)
Definition at line 109 of file ConfigSource.cc.
{
  static const std::array<std::string, 5> false_list{"0", "OFF", "FALSE", "N", "NO"};
  auto false_found = std::find(false_list.begin(), false_list.end(), val);
  return false_found == false_list.end();
}
Referenced by getConfigBool().
toInt()
int onert::util::toInt (const std::string & val)
Definition at line 116 of file ConfigSource.cc.
{ return std::stoi(val); }
Referenced by getConfigInt().