ONE - On-device Neural Engine: onert::backend::ggml::ops Namespace Reference
onert::backend::ggml::ops Namespace Reference
Data Structures
class FullyConnectedLayer
class GatherLayer
Functions
ggml_type getGGMLType (ir::DataType type)
struct ggml_tensor getGGMLTensor (const IPortableTensor *tensor)
int32_t getAxis (uint32_t rank, int32_t axis)
Function Documentation
getAxis()
int32_t onert::backend::ggml::ops::getAxis (uint32_t rank, int32_t axis) inline
Definition at line 25 of file OperationUtils.h.
{
  auto ret = axis;
  if (axis < 0)
  {
    ret += rank;
  }
  return ret;
}
getGGMLTensor()
struct ggml_tensor onert::backend::ggml::ops::getGGMLTensor (const IPortableTensor * tensor)
Definition at line 41 of file GGMLHelper.cc.
{
  struct ggml_tensor res;
  res.type = getGGMLType(tensor->data_type());
  const auto rank = tensor->getShape().rank();
  for (int i = 0; i < GGML_MAX_DIMS; ++i)
  {
    if (i >= rank)
      res.ne[i] = 1;
    else
      res.ne[i] = tensor->getShape().dim(rank - i - 1);
  }
  res.nb[0] = ggml_type_size(res.type);
  res.nb[1] = res.nb[0] * (res.ne[0] / ggml_blck_size(res.type));
  for (int i = 2; i < GGML_MAX_DIMS; ++i)
    res.nb[i] = res.nb[i - 1] * res.ne[i - 1];
  res.op = GGML_OP_NONE;
  res.grad = nullptr;
  res.data = (void *)(tensor->buffer());
  return res;
}
References getGGMLType().
Referenced by onert::backend::ggml::ops::FullyConnectedLayer::fullyConnectedGGMLWeight().
getGGMLType()
ggml_type onert::backend::ggml::ops::getGGMLType (ir::DataType type)
Definition at line 22 of file GGMLHelper.cc.
{
  switch (type)
  {
    case ir::DataType::FLOAT32:
      return GGML_TYPE_F32;
    case ir::DataType::QUANT_GGML_Q4_0:
      return GGML_TYPE_Q4_0;
    case ir::DataType::QUANT_GGML_Q8_0:
      return GGML_TYPE_Q8_0;
    case ir::DataType::INT32:
      return GGML_TYPE_I32;
    case ir::DataType::INT64:
      return GGML_TYPE_I64;
    default:
      throw std::runtime_error("Unsupported data type");
  }
}
References type.
Referenced by getGGMLTensor().