ONE - On-device Neural Engine: onert::exec Namespace Reference
onert::exec Namespace Reference
Namespaces
namespace feature
Data Structures
class DataflowExecutor
class DynamicShapeInferer
Class to infer shape of output tensor at execution time and allocate memory fo output tensor if needed.
class ExecTime
class Execution
Class to define execution instance to collect input/output information for inference and prepare executor run (TODO)
class ExecutionObservee
Class that.
class ExecutorBase
class Executors
Class to gather executors.
class FunctionSequence
class HookFunction
class IExecutionObserver
struct IExecutor
Struct to define interface of Executor.
class IExecutors
Class to gather NN package's executor set.
class IFunction
struct InputDesc
struct IODescription
class IPermuteFunction
class Job
class JSON
class LinearExecutor
Class to handle execution phase. Simple run the sequence of operations that is sorted in topological order.
class NopFunction
A derivative of IFunction tha does nothing.
struct OutputDesc
class ParallelExecutor
Class to execute Graph in parallel.
class ParallelScheduler
class ProfileObserver
class SingleModelExecutors
Class to gather executor set for single model NN package.
class ThreadPool
class TracingObserver
class WorkQueue
Typedefs
using BackendSet = util::Set< const backend::Backend * >
using MeasurementData = std::unordered_map< const backend::Backend *, std::unordered_map< std::string, std::unordered_map< bool, std::map< uint32_t, int64_t > > > >
table, that contains execution time of an operation on some backend for different input sizes and transfer time from one backend to another for various input sizes (permutation time)
Functions
void UpdateOffsets (::onert::backend::ITensor *src, ::onert::backend::ITensor *dst, const ::onert::ir::Shape &loop_shape, std::vector< size_t > &src_offsets, std::vector< size_t > &dst_offsets)
void CopyStatic (const uint8_t *src_buffer, uint8_t *dst_buffer, const std::vector< size_t > &src_offsets, const std::vector< size_t > &dst_offsets, size_t copy_len)
void CopyDynamic (const ::onert::backend::ITensor *src, const ::onert::backend::ITensor *dst, uint8_t *dst_buffer, const ::onert::ir::Shape &loop_shape, size_t copy_len)
void readString (std::string &str, std::ifstream &stream)
Helper function for reading string from stream.
void readBool (bool &quant, std::ifstream &stream)
Helper function for reading bool from stream.
void printString (const std::string &str, std::ofstream &stream)
void printBool (bool quant, std::ofstream &stream)
ir::Shape convertShape (const ir::Shape &shape, ir::Layout src_layout, ir::Layout dst_layout)
Converts shape when its rank is 4.
Typedef Documentation
BackendSet
using onert::exec::BackendSet = typedef util::Set<const backend::Backend *>
Definition at line 35 of file BackendSet.h.
MeasurementData
using onert::exec::MeasurementData = typedef std::unordered_map< const backend::Backend *, std::unordered_map<std::string, std::unordered_map<bool, std::map<uint32_t, int64_t> >> >
table, that contains execution time of an operation on some backend for different input sizes and transfer time from one backend to another for various input sizes (permutation time)
          backend ->  op ->  quant->  size   --> time
_measurements[Backend*]["string"][bool][uint32_t] = int64_t
Definition at line 39 of file JSONExecTime.h.
Function Documentation
convertShape()
ir::Shape onert::exec::convertShape (const ir::Shape & shape, ir::Layout src_layout, ir::Layout dst_layout)
Converts shape when its rank is 4.
Returns
ir::Shape Return a shape based on dst_layout. If rank is not 4, input shape is returned without conversion.
Definition at line 24 of file ShapeConverter.cc.
{
  if (shape.rank() != 4)
    return shape;
  if (src_layout == dst_layout)
    return shape;
  if (src_layout == ir::Layout::NCHW && dst_layout == ir::Layout::NHWC)
  {
    const ir::Shape &src_NCHW = shape;
    ir::Shape dst_NHWC(4);
    dst_NHWC.dim(0) = src_NCHW.dim(0); // N
    dst_NHWC.dim(1) = src_NCHW.dim(2); // H
    dst_NHWC.dim(2) = src_NCHW.dim(3); // W
    dst_NHWC.dim(3) = src_NCHW.dim(1); // C
    return dst_NHWC;
  }
  if (src_layout == ir::Layout::NHWC && dst_layout == ir::Layout::NCHW)
  {
    const ir::Shape &src_NHWC = shape;
    ir::Shape dst_NCHW(4);
    dst_NCHW.dim(0) = src_NHWC.dim(0); // N
    dst_NCHW.dim(1) = src_NHWC.dim(3); // C
    dst_NCHW.dim(2) = src_NHWC.dim(1); // H
    dst_NCHW.dim(3) = src_NHWC.dim(2); // W
    return dst_NCHW;
  }
  throw std::runtime_error("Should not reach here");
}
References onert::ir::NCHW, and onert::ir::NHWC.
Referenced by onert::exec::ExecutorBase::execute(), and onert::backend::builtin::kernel::PermuteLayer::run().
CopyDynamic()
void onert::exec::CopyDynamic (const ::onert::backend::ITensor * src, const ::onert::backend::ITensor * dst, uint8_t * dst_buffer, const ::onert::ir::Shape & loop_shape, size_t copy_len) inline
Definition at line 62 of file IPermuteFunction.h.
{
  ShapeLoop(loop_shape, [&](const onert::ir::Coordinates &coords) {
    // Copy src tensor's data to dst_buffer with calculated offset of dst tensor
    memcpy(dst_buffer + dst->calcOffset(coords), src->buffer() + src->calcOffset(coords), copy_len);
  });
}
References coords, and ShapeLoop().
CopyStatic()
void onert::exec::CopyStatic (const uint8_t * src_buffer, uint8_t * dst_buffer, const std::vector< size_t > & src_offsets, const std::vector< size_t > & dst_offsets, size_t copy_len) inline
Definition at line 51 of file IPermuteFunction.h.
{
  assert(src_offsets.size() == dst_offsets.size());
  for (size_t i = 0; i < src_offsets.size(); ++i)
  {
    memcpy(dst_buffer + dst_offsets.at(i), src_buffer + src_offsets.at(i), copy_len);
  }
}
printBool()
void onert::exec::printBool (bool quant, std::ofstream & stream)
Definition at line 60 of file JSONExecTime.cc.
{ stream << "\"" << quant << "\""; }
Referenced by onert::exec::JSON::storeOperationsExecTime().
printString()
void onert::exec::printString (const std::string & str, std::ofstream & stream)
Definition at line 58 of file JSONExecTime.cc.
{ stream << "\"" << str << "\""; }
Referenced by onert::exec::JSON::storeOperationsExecTime().
readBool()
void onert::exec::readBool (bool & quant, std::ifstream & stream)
Helper function for reading bool from stream.
Parameters
quant Output bool
stream File stream
Definition at line 50 of file JSONExecTime.cc.
{
  char buf;
  stream.get(buf);
  quant = (buf == '1');
  stream.get(buf);
}
readString()
void onert::exec::readString (std::string & str, std::ifstream & stream)
Helper function for reading string from stream.
Parameters
str Output string
stream File stream
Definition at line 31 of file JSONExecTime.cc.
{
  str.clear();
  char buf;
  while (stream.good())
  {
    stream.get(buf);
    if (buf == '"')
      break;
    str.push_back(buf);
  }
}
UpdateOffsets()
void onert::exec::UpdateOffsets (::onert::backend::ITensor * src, ::onert::backend::ITensor * dst, const ::onert::ir::Shape & loop_shape, std::vector< size_t > & src_offsets, std::vector< size_t > & dst_offsets) inline
Definition at line 41 of file IPermuteFunction.h.
{
  ShapeLoop(loop_shape, [&](const onert::ir::Coordinates &coords) {
    src_offsets.emplace_back(src->calcOffset(coords));
    dst_offsets.emplace_back(dst->calcOffset(coords));
  });
}
References onert::backend::ITensor::calcOffset(), coords, and ShapeLoop().