ONE - On-device Neural Engine: exo::circle_detail Namespace Reference
exo::circle_detail Namespace Reference
Data Structures
struct OpCode
struct SerializedModelData
struct SubGraphContext
Record the information of T/F Lite SubGraph and its mapping to loco.
struct TypeInference
Get the type of each node as NodeAnnotation.
Typedefs
using TFLTensorIndex = int32_t
Functions
circle::Padding getOpPadding (const loco::Padding2D *pad, const loco::Stride< 2 > *stride, const ShapeDescription &ifm, const ShapeDescription &ofm)
circle::Padding getOpPadding (const locoex::Padding pad)
void registerGraphIOName (loco::Graph *graph, SerializedModelData &gd)
Register graph input and output names to SerializedModelData.
void set_tensor_index (loco::Node *node, const TFLTensorIndex &tensor_id)
TFLTensorIndex get_tensor_index (loco::Node *node)
void exportNodes (loco::Graph *g, FlatBufferBuilder &builder, SerializedModelData &gd)
void exportNodes (loco::Graph *g, flatbuffers::FlatBufferBuilder &builder, SerializedModelData &gd)
create Operators corresponding to model nodes
void exportOpDefinedTensor (const TFLTensorInfo &info, FlatBufferBuilder &builder, SerializedModelData &gd)
void exportOpDefinedTensors (loco::Graph *g, FlatBufferBuilder &builder, SerializedModelData &gd)
void exportOpDefinedTensors (loco::Graph *g, flatbuffers::FlatBufferBuilder &builder, SerializedModelData &gd)
create Tensors corresponding to results of all nodes in graph
Typedef Documentation
TFLTensorIndex
using exo::circle_detail::TFLTensorIndex = typedef int32_t
Definition at line 112 of file CircleExporterUtils.h.
Function Documentation
exportNodes() [1/2]
void exo::circle_detail::exportNodes (loco::Graph * g, FlatBufferBuilder & builder, SerializedModelData & gd)
Definition at line 1225 of file CircleOperationExporter.cpp.
{
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    exportNode(node, builder, gd);
  }
}
References loco::output_nodes(), and loco::postorder_traversal().
exportNodes() [2/2]
void exo::circle_detail::exportNodes (loco::Graph * g, flatbuffers::FlatBufferBuilder & builder, SerializedModelData & gd)
create Operators corresponding to model nodes
Parameters
nodes container with nodes
gd information about serializer parts of model
exportOpDefinedTensor()
void exo::circle_detail::exportOpDefinedTensor (const TFLTensorInfo & info, FlatBufferBuilder & builder, SerializedModelData & gd)
Definition at line 217 of file CircleTensorExporter.cpp.
{
  // Create and register output tensor shape
  auto shape_offset = encodeShape(builder, info.shape());
  // encode and register output tensor buffer
  auto buffer = info.tfl_content() == nullptr ? encodeOpBuffer(builder)
                                              : encodeOpBuffer(builder, info.tfl_content());
  auto buffer_id = static_cast<uint32_t>(gd._buffers.size());
  gd._buffers.push_back(buffer);
  auto name_offset = builder.CreateString(info.name());
  auto tensor_offset = CreateTensor(builder, shape_offset, info.dtype(), buffer_id, name_offset,
                                    /*quantization*/ 0, /*is_variable*/ false);
  gd._tensors.push_back(tensor_offset);
}
References exo::circle_detail::SerializedModelData::_buffers, exo::circle_detail::SerializedModelData::_tensors, and info.
Referenced by exportOpDefinedTensors().
exportOpDefinedTensors() [1/2]
void exo::circle_detail::exportOpDefinedTensors (loco::Graph * g, FlatBufferBuilder & builder, SerializedModelData & gd)
Definition at line 236 of file CircleTensorExporter.cpp.
{
  TFLTensorContext tensor_ctx;
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    allocateCircleTensor(node, tensor_ctx);
  }
  // add one empty buffer
  //   note: this follows TFLite
  //   note: there's a comment in tflite fbs file
  //   - Note the 0th entry of this array must be an empty buffer (sentinel).
  //   - This is a convention so that tensors without a buffer can provide 0 as
  //   - their buffer.
  auto buffer = encodeOpBuffer(builder);
  gd._buffers.push_back(buffer);
  for (const auto &tensor_info : tensor_ctx)
  {
    exportOpDefinedTensor(tensor_info, builder, gd);
  }
}
References exo::circle_detail::SerializedModelData::_buffers, exportOpDefinedTensor(), loco::output_nodes(), and loco::postorder_traversal().
exportOpDefinedTensors() [2/2]
void exo::circle_detail::exportOpDefinedTensors (loco::Graph * g, flatbuffers::FlatBufferBuilder & builder, SerializedModelData & gd)
create Tensors corresponding to results of all nodes in graph
Parameters
computational graph
gd information about serialized parts of model
get_tensor_index()
TFLTensorIndex exo::circle_detail::get_tensor_index (loco::Node * node)
Definition at line 155 of file CircleExporterUtils.cpp.
{
  assert(node->annot<TFLTensorIndexAnnotation>() != nullptr);
  return node->annot<TFLTensorIndexAnnotation>()->index();
}
References loco::AnnotatedItem< Annotation >::annot().
getOpPadding() [1/2]
circle::Padding exo::circle_detail::getOpPadding (const loco::Padding2D * pad, const loco::Stride< 2 > * stride, const ShapeDescription & ifm, const ShapeDescription & ofm)
Definition at line 66 of file CircleExporterUtils.cpp.
{
  // VALID padding
  if (pad->top() == 0 && pad->bottom() == 0 && pad->left() == 0 && pad->right() == 0)
    return circle::Padding_VALID;
  // SAME padding
  //
  // For same padding, by definition, following equation should hold:
  //   O = floor((I - 1) / S) + 1
  //   where input size I, output size O, stride S
  //
  // NOTE input and output 'feature' map are shape of NHWC
  bool same_padding_criterion_1 =
    (static_cast<uint32_t>(ofm._dims[1]) == (ifm._dims[1] - 1) / stride->vertical() + 1) &&
    (static_cast<uint32_t>(ofm._dims[2]) == (ifm._dims[2] - 1) / stride->horizontal() + 1);
  // For same padding, rear padding is same or bigger than front padding by at most 1
  bool same_padding_criterion_2 =
    (pad->top() <= pad->bottom()) && (pad->bottom() <= pad->top() + 1) &&
    (pad->left() <= pad->right()) && (pad->right() <= pad->left() + 1);
  if (same_padding_criterion_1 && same_padding_criterion_2)
    return circle::Padding_SAME;
  INTERNAL_EXN("Unsupported padding criteria");
}
References exo::ShapeDescription::_dims, loco::Padding2D::bottom(), INTERNAL_EXN, loco::Padding2D::left(), loco::Padding2D::right(), and loco::Padding2D::top().
getOpPadding() [2/2]
circle::Padding exo::circle_detail::getOpPadding (const locoex::Padding pad)
Definition at line 95 of file CircleExporterUtils.cpp.
{
  if (pad == locoex::Padding::VALID)
    return circle::Padding_VALID;
  if (pad == locoex::Padding::SAME)
    return circle::Padding_SAME;
  INTERNAL_EXN_V("Unsupported locoex::Padding", oops::to_uint32(pad));
}
References INTERNAL_EXN_V, locoex::SAME, oops::to_uint32(), and locoex::VALID.
registerGraphIOName()
void exo::circle_detail::registerGraphIOName (loco::Graph * graph, SerializedModelData & gd)
Register graph input and output names to SerializedModelData.
Definition at line 105 of file CircleExporterUtils.cpp.
{
  for (uint32_t in = 0; in < graph->inputs()->size(); ++in)
  {
    auto pull = loco::pull_node(graph, in);
    auto name = graph->inputs()->at(in)->name();
    gd._pull_to_name[pull] = name;
  }
  for (uint32_t out = 0; out < graph->outputs()->size(); ++out)
  {
    auto push = loco::push_node(graph, out);
    auto name = graph->outputs()->at(out)->name();
    gd._push_to_name[push] = name;
  }
  // TODO set this value properly
  gd._data_format = circle::DataFormat::DataFormat_CHANNELS_LAST;
}
References exo::circle_detail::SubGraphContext::_data_format, exo::circle_detail::SerializedModelData::_pull_to_name, exo::circle_detail::SerializedModelData::_push_to_name, loco::pull_node(), and loco::push_node().
set_tensor_index()
void exo::circle_detail::set_tensor_index (loco::Node * node, const TFLTensorIndex & tensor_id)
Definition at line 149 of file CircleExporterUtils.cpp.
{
  assert(node->annot<TFLTensorIndexAnnotation>() == nullptr);
  node->annot(std::make_unique<TFLTensorIndexAnnotation>(tensor_id));
}
References loco::AnnotatedItem< Annotation >::annot().