ONE - On-device Neural Engine: exo::test Namespace Reference
exo::test Namespace Reference
Data Structures
class ExampleGraph
class ExampleGraph< ExampleGraphType::ConstGen_ReLU >
Class to creates the following:
class ExampleGraph< ExampleGraphType::FeatureBiasAdd >
Class to create the following:
class ExampleGraph< ExampleGraphType::FilterEncode_FilterDecode >
Class to creates the following:
class ExampleGraph< ExampleGraphType::TFLTranspose >
Class to create the following:
class ExampleGraph< ExampleGraphType::Transpose >
Class to creates the following:
class TestGraph
class TypeShapeReadyPhase
Phase for test, that is used to test pass. This phase initially adds TypeInferencePass and ShapeInferencePass.
Enumerations
enum class ExampleGraphType {
FeatureBiasAdd , ConstGen_ReLU , FilterEncode_FilterDecode , Transpose ,
TFLTranspose
}
Functions
template<typename LocoNodeT >
LocoNodeT * get_only_succ (loco::Node *parent)
Get the only succ object of type LocoNodeT. (The name only succ comes from English word only child.) parent must have 1 succ only. When there is no succ of type LocoNodeT, nullptr will be returned.
template<typename T >
T * find_first_node_bytype (loco::Graph *g)
Enumeration Type Documentation
ExampleGraphType
enum class exo::test::ExampleGraphType strong
Enumerator
FeatureBiasAdd
ConstGen_ReLU
FilterEncode_FilterDecode
Transpose
TFLTranspose
Definition at line 191 of file TestGraph.h.
{
  FeatureBiasAdd,
  ConstGen_ReLU,
  FilterEncode_FilterDecode,
  Transpose,
  TFLTranspose,
};
Function Documentation
find_first_node_bytype()
template<typename T > T * exo::test::find_first_node_bytype (loco::Graph * g) inline
Definition at line 91 of file TestHelper.h.
{
  T *first_node = nullptr;
  loco::Graph::NodeContext *nodes = g->nodes();
  uint32_t count = nodes->size();
  for (uint32_t i = 0; i < count; ++i)
  {
    first_node = dynamic_cast<T *>(nodes->at(i));
    if (first_node != nullptr)
      break;
  }
  return first_node;
}
References loco::ObjectPool< T >::at(), and loco::ObjectPool< T >::size().
get_only_succ()
template<typename LocoNodeT > LocoNodeT * exo::test::get_only_succ (loco::Node * parent) inline
Get the only succ object of type LocoNodeT. (The name only succ comes from English word only child.) parent must have 1 succ only. When there is no succ of type LocoNodeT, nullptr will be returned.
Definition at line 83 of file TestHelper.h.
{
  auto succs = loco::succs(parent);
  EXO_ASSERT(succs.size() == 1, "parent has more than 1 succs.");
  return dynamic_cast<LocoNodeT *>(*succs.begin());
}
References EXO_ASSERT, and loco::succs().