ONE - On-device Neural Engine: tflite2circle Namespace Reference
tflite2circle Namespace Reference
Data Structures
struct BufferLink
class CircleModel
struct MetaDataBufferLink
class Offset
struct OperatorCodeLink
struct SubGraphLink
class TFLModel
Typedefs
using FlatBufBuilder = std::unique_ptr< flatbuffers::FlatBufferBuilder >
Functions
flatbuffers::Offset< circle::AbsOptions > build_circle_AbsOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::AddNOptions > build_circle_AddNOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::AddOptions > build_circle_AddOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ArgMaxOptions > build_circle_ArgMaxOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ArgMinOptions > build_circle_ArgMinOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::BatchMatMulOptions > build_circle_BatchMatMulOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::BatchToSpaceNDOptions > build_circle_BatchToSpaceNDOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::BidirectionalSequenceLSTMOptions > build_circle_BidirectionalSequenceLSTMOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::CastOptions > build_circle_CastOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ConcatenationOptions > build_circle_ConcatenationOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::Conv2DOptions > build_circle_Conv2DOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::CosOptions > build_circle_CosOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::DensifyOptions > build_circle_DensifyOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::DepthToSpaceOptions > build_circle_DepthToSpaceOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::DepthwiseConv2DOptions > build_circle_DepthwiseConv2DOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::DequantizeOptions > build_circle_DequantizeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::DivOptions > build_circle_DivOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::EqualOptions > build_circle_EqualOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ExpandDimsOptions > build_circle_ExpandDimsOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ExpOptions > build_circle_ExpOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::FakeQuantOptions > build_circle_FakeQuantOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::FillOptions > build_circle_FillOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::FloorDivOptions > build_circle_FloorDivOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::FloorModOptions > build_circle_FloorModOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::FullyConnectedOptions > build_circle_FullyConnectedOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::GatherNdOptions > build_circle_GatherNdOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::GatherOptions > build_circle_GatherOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::GreaterEqualOptions > build_circle_GreaterEqualOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::GreaterOptions > build_circle_GreaterOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::IfOptions > build_circle_IfOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::L2NormOptions > build_circle_L2NormOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LeakyReluOptions > build_circle_LeakyReluOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LessEqualOptions > build_circle_LessEqualOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LessOptions > build_circle_LessOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LocalResponseNormalizationOptions > build_circle_LocalResponseNormalizationOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LogicalAndOptions > build_circle_LogicalAndOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LogicalNotOptions > build_circle_LogicalNotOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LogicalOrOptions > build_circle_LogicalOrOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::LogSoftmaxOptions > build_circle_LogSoftmaxOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::MatrixDiagOptions > build_circle_MatrixDiagOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::MatrixSetDiagOptions > build_circle_MatrixSetDiagOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::MaximumMinimumOptions > build_circle_MaximumMinimumOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::MirrorPadOptions > build_circle_MirrorPadOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::MulOptions > build_circle_MulOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::NegOptions > build_circle_NegOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::NonMaxSuppressionV4Options > build_circle_NonMaxSuppressionV4Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::NonMaxSuppressionV5Options > build_circle_NonMaxSuppressionV5Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::NotEqualOptions > build_circle_NotEqualOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::OneHotOptions > build_circle_OneHotOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::PackOptions > build_circle_PackOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::PadOptions > build_circle_PadOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::PadV2Options > build_circle_PadV2Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::Pool2DOptions > build_circle_Pool2DOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::PowOptions > build_circle_PowOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::RangeOptions > build_circle_RangeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::RankOptions > build_circle_RankOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::ReducerOptions > build_circle_ReducerOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ReshapeOptions > build_circle_ReshapeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ResizeBilinearOptions > build_circle_ResizeBilinearOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ResizeNearestNeighborOptions > build_circle_ResizeNearestNeighborOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ReverseSequenceOptions > build_circle_ReverseSequenceOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ReverseV2Options > build_circle_ReverseV2Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::ScatterNdOptions > build_circle_ScatterNdOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SegmentSumOptions > build_circle_SegmentSumOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SelectOptions > build_circle_SelectOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SelectV2Options > build_circle_SelectV2Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ShapeOptions > build_circle_ShapeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SliceOptions > build_circle_SliceOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SoftmaxOptions > build_circle_SoftmaxOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SpaceToBatchNDOptions > build_circle_SpaceToBatchNDOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::SpaceToDepthOptions > build_circle_SpaceToDepthOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SparseToDenseOptions > build_circle_SparseToDenseOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SplitOptions > build_circle_SplitOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SplitVOptions > build_circle_SplitVOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SquaredDifferenceOptions > build_circle_SquaredDifferenceOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SquareOptions > build_circle_SquareOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::SqueezeOptions > build_circle_SqueezeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::StridedSliceOptions > build_circle_StridedSliceOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SubOptions > build_circle_SubOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::SVDFOptions > build_circle_SVDFOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::TileOptions > build_circle_TileOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::TopKV2Options > build_circle_TopKV2Options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::TransposeConvOptions > build_circle_TransposeConvOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::TransposeOptions > build_circle_TransposeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::UnidirectionalSequenceLSTMOptions > build_circle_UnidirectionalSequenceLSTMOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::UniqueOptions > build_circle_UniqueOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::UnpackOptions > build_circle_UnpackOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::WhereOptions > build_circle_WhereOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
flatbuffers::Offset< circle::WhileOptions > build_circle_WhileOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
flatbuffers::Offset< circle::ZerosLikeOptions > build_circle_ZerosLikeOptions (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *)
circle::BuiltinOperator get_circle_builtin_code (tflite::BuiltinOperator tfl_bop)
Returns circle builtin_code according to tflite.
int8_t get_circle_builtin_code (int8_t tfl_bop_i8)
int32_t get_circle_builtin_code (int32_t tfl_bop_i32)
circle::TensorType get_circle_tensortype (tflite::TensorType tfl_tt)
Returns circle TensorType according to tflite.
circle::Padding get_circle_padding (tflite::Padding tfl_p)
Returns circle Padding enum according to tflite.
circle::ActivationFunctionType get_circle_activation_function_type (tflite::ActivationFunctionType tfl_aft)
Returns circle ActivationFunctionType according to tflite.
flatbuffers::Offset< void > get_circle_builtin_options (flatbuffers::FlatBufferBuilder &fb, const tflite::Operator *op)
Returns circle builtin_options according to tflite.
circle::BuiltinOptions get_circle_builtin_options_type (const tflite::Operator *op)
Returns circle builtin_options_type according to tflite.
circle::MirrorPadMode get_circle_mirrorpad_mode (tflite::MirrorPadMode tfl_mode)
Returns circle MirrorPadMode according to tflite.
circle::DimensionType get_circle_dimension_type (tflite::DimensionType tfl_dim_type)
Returns circle DimensionType according to tflite.
flatbuffers::Offset< void > get_circle_sparse_index_vector (flatbuffers::FlatBufferBuilder &fb, const void *values, const tflite::SparseIndexVector &tfl_sparse_index_vector_type)
Returns circle SparseIndexVector according to tflite.
circle::SparseIndexVector get_circle_sparse_index_vector_type (const tflite::SparseIndexVector &tfl_sparse_index_vector_type)
Returns circle SparseIndexVector type according to tflite.
Typedef Documentation
FlatBufBuilder
using tflite2circle::FlatBufBuilder = typedef std::unique_ptr<flatbuffers::FlatBufferBuilder>
Definition at line 32 of file CircleModel.h.
Function Documentation
build_circle_AbsOptions()
flatbuffers::Offset< circle::AbsOptions > tflite2circle::build_circle_AbsOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 25 of file AbsOptions.cpp.
{
  circle::AbsOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_AddNOptions()
flatbuffers::Offset< circle::AddNOptions > tflite2circle::build_circle_AddNOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file AddNOptions.cpp.
{
  circle::AddNOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_AddOptions()
flatbuffers::Offset< circle::AddOptions > tflite2circle::build_circle_AddOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file AddOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_AddOptions();
  assert(tflite_builtin_options);
  circle::AddOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_ArgMaxOptions()
flatbuffers::Offset< circle::ArgMaxOptions > tflite2circle::build_circle_ArgMaxOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file ArgMaxOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ArgMaxOptions();
  assert(tflite_builtin_options);
  circle::ArgMaxOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_output_type(
    get_circle_tensortype(tflite_builtin_options->output_type()));
  return builtin_options_builder.Finish();
}
References get_circle_tensortype().
build_circle_ArgMinOptions()
flatbuffers::Offset< circle::ArgMinOptions > tflite2circle::build_circle_ArgMinOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file ArgMinOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ArgMinOptions();
  assert(tflite_builtin_options);
  circle::ArgMinOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_output_type(
    get_circle_tensortype(tflite_builtin_options->output_type()));
  return builtin_options_builder.Finish();
}
References get_circle_tensortype().
build_circle_BatchMatMulOptions()
flatbuffers::Offset< circle::BatchMatMulOptions > tflite2circle::build_circle_BatchMatMulOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file BatchMatMulOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_BatchMatMulOptions();
  assert(tflite_builtin_options);
  circle::BatchMatMulOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_adjoint_lhs(tflite_builtin_options->adj_x());
  builtin_options_builder.add_adjoint_rhs(tflite_builtin_options->adj_y());
  return builtin_options_builder.Finish();
}
build_circle_BatchToSpaceNDOptions()
flatbuffers::Offset< circle::BatchToSpaceNDOptions > tflite2circle::build_circle_BatchToSpaceNDOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 26 of file BatchToSpaceNDOptions.cpp.
{
  circle::BatchToSpaceNDOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_BidirectionalSequenceLSTMOptions()
flatbuffers::Offset< circle::BidirectionalSequenceLSTMOptions > tflite2circle::build_circle_BidirectionalSequenceLSTMOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file BidirectionalSequenceLSTMOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_BidirectionalSequenceLSTMOptions();
  circle::BidirectionalSequenceLSTMOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  builtin_options_builder.add_cell_clip(tflite_builtin_options->cell_clip());
  builtin_options_builder.add_proj_clip(tflite_builtin_options->proj_clip());
  builtin_options_builder.add_time_major(tflite_builtin_options->time_major());
  builtin_options_builder.add_merge_outputs(tflite_builtin_options->merge_outputs());
  builtin_options_builder.add_asymmetric_quantize_inputs(
    tflite_builtin_options->asymmetric_quantize_inputs());
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_CastOptions()
flatbuffers::Offset< circle::CastOptions > tflite2circle::build_circle_CastOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file CastOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_CastOptions();
  if (tflite_builtin_options == nullptr)
    return 0;
  circle::CastOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_in_data_type(
    get_circle_tensortype(tflite_builtin_options->in_data_type()));
  builtin_options_builder.add_out_data_type(
    get_circle_tensortype(tflite_builtin_options->out_data_type()));
  return builtin_options_builder.Finish();
}
References get_circle_tensortype().
build_circle_ConcatenationOptions()
flatbuffers::Offset< circle::ConcatenationOptions > tflite2circle::build_circle_ConcatenationOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file ConcatenationOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ConcatenationOptions();
  assert(tflite_builtin_options);
  circle::ConcatenationOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_axis(tflite_builtin_options->axis());
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_Conv2DOptions()
flatbuffers::Offset< circle::Conv2DOptions > tflite2circle::build_circle_Conv2DOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file Conv2DOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_Conv2DOptions();
  assert(tflite_builtin_options);
  circle::Conv2DOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_padding(get_circle_padding(tflite_builtin_options->padding()));
  builtin_options_builder.add_stride_w(tflite_builtin_options->stride_w());
  builtin_options_builder.add_stride_h(tflite_builtin_options->stride_h());
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  builtin_options_builder.add_dilation_w_factor(tflite_builtin_options->dilation_w_factor());
  builtin_options_builder.add_dilation_h_factor(tflite_builtin_options->dilation_h_factor());
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type(), and get_circle_padding().
build_circle_CosOptions()
flatbuffers::Offset< circle::CosOptions > tflite2circle::build_circle_CosOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file CosOptions.cpp.
{
  circle::CosOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_DensifyOptions()
flatbuffers::Offset< circle::DensifyOptions > tflite2circle::build_circle_DensifyOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file DensifyOptions.cpp.
{
  circle::DensifyOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_DepthToSpaceOptions()
flatbuffers::Offset< circle::DepthToSpaceOptions > tflite2circle::build_circle_DepthToSpaceOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file DepthToSpaceOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_DepthToSpaceOptions();
  assert(tflite_builtin_options);
  circle::DepthToSpaceOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_block_size(tflite_builtin_options->block_size());
  return builtin_options_builder.Finish();
}
build_circle_DepthwiseConv2DOptions()
flatbuffers::Offset< circle::DepthwiseConv2DOptions > tflite2circle::build_circle_DepthwiseConv2DOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file DepthwiseConv2DOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_DepthwiseConv2DOptions();
  assert(tflite_builtin_options);
  circle::DepthwiseConv2DOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_padding(get_circle_padding(tflite_builtin_options->padding()));
  builtin_options_builder.add_stride_w(tflite_builtin_options->stride_w());
  builtin_options_builder.add_stride_h(tflite_builtin_options->stride_h());
  builtin_options_builder.add_depth_multiplier(tflite_builtin_options->depth_multiplier());
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  builtin_options_builder.add_dilation_w_factor(tflite_builtin_options->dilation_w_factor());
  builtin_options_builder.add_dilation_h_factor(tflite_builtin_options->dilation_h_factor());
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type(), and get_circle_padding().
build_circle_DequantizeOptions()
flatbuffers::Offset< circle::DequantizeOptions > tflite2circle::build_circle_DequantizeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 24 of file DequantizeOptions.cpp.
{
  circle::DequantizeOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_DivOptions()
flatbuffers::Offset< circle::DivOptions > tflite2circle::build_circle_DivOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file DivOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_DivOptions();
  assert(tflite_builtin_options);
  circle::DivOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_EqualOptions()
flatbuffers::Offset< circle::EqualOptions > tflite2circle::build_circle_EqualOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file EqualOptions.cpp.
{
  circle::EqualOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_ExpandDimsOptions()
flatbuffers::Offset< circle::ExpandDimsOptions > tflite2circle::build_circle_ExpandDimsOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file ExpandDimsOptions.cpp.
{
  circle::ExpandDimsOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_ExpOptions()
flatbuffers::Offset< circle::ExpOptions > tflite2circle::build_circle_ExpOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 25 of file ExpOptions.cpp.
{
  circle::ExpOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_FakeQuantOptions()
flatbuffers::Offset< circle::FillOptions > tflite2circle::build_circle_FakeQuantOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file FakeQuantOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_FakeQuantOptions();
  assert(tflite_builtin_options);
  circle::FakeQuantOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_min(tflite_builtin_options->min());
  builtin_options_builder.add_max(tflite_builtin_options->max());
  builtin_options_builder.add_num_bits(tflite_builtin_options->num_bits());
  builtin_options_builder.add_narrow_range(tflite_builtin_options->narrow_range());
  return builtin_options_builder.Finish();
}
build_circle_FillOptions()
flatbuffers::Offset< circle::FillOptions > tflite2circle::build_circle_FillOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file FillOptions.cpp.
{
  circle::FillOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_FloorDivOptions()
flatbuffers::Offset< circle::FloorDivOptions > tflite2circle::build_circle_FloorDivOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file FloorDivOptions.cpp.
{
  circle::FloorDivOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_FloorModOptions()
flatbuffers::Offset< circle::FloorModOptions > tflite2circle::build_circle_FloorModOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file FloorModOptions.cpp.
{
  circle::FloorModOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_FullyConnectedOptions()
flatbuffers::Offset< circle::FullyConnectedOptions > tflite2circle::build_circle_FullyConnectedOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file FullyConnectedOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_FullyConnectedOptions();
  assert(tflite_builtin_options);
  circle::FullyConnectedOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  // Get FullyConnectedOptionsWeightsFormat
  auto tflite_weight_format = tflite_builtin_options->weights_format();
  if (tflite_weight_format == tflite::FullyConnectedOptionsWeightsFormat_DEFAULT)
    builtin_options_builder.add_weights_format(circle::FullyConnectedOptionsWeightsFormat_DEFAULT);
  else if (tflite_weight_format == tflite::FullyConnectedOptionsWeightsFormat_SHUFFLED4x16INT8)
    builtin_options_builder.add_weights_format(
      circle::FullyConnectedOptionsWeightsFormat_SHUFFLED4x16INT8);
  builtin_options_builder.add_keep_num_dims(tflite_builtin_options->keep_num_dims());
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_GatherNdOptions()
flatbuffers::Offset< circle::GatherNdOptions > tflite2circle::build_circle_GatherNdOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 26 of file GatherNdOptions.cpp.
{
  circle::GatherNdOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_GatherOptions()
flatbuffers::Offset< circle::GatherOptions > tflite2circle::build_circle_GatherOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file GatherOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_GatherOptions();
  assert(tflite_builtin_options);
  circle::GatherOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_axis(tflite_builtin_options->axis());
  return builtin_options_builder.Finish();
}
build_circle_GreaterEqualOptions()
flatbuffers::Offset< circle::GreaterEqualOptions > tflite2circle::build_circle_GreaterEqualOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file GreaterEqualOptions.cpp.
{
  circle::GreaterEqualOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_GreaterOptions()
flatbuffers::Offset< circle::GreaterOptions > tflite2circle::build_circle_GreaterOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file GreaterOptions.cpp.
{
  circle::GreaterOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_IfOptions()
flatbuffers::Offset< circle::IfOptions > tflite2circle::build_circle_IfOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file IfOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_IfOptions();
  assert(tflite_builtin_options);
  circle::IfOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_then_subgraph_index(tflite_builtin_options->then_subgraph_index());
  builtin_options_builder.add_else_subgraph_index(tflite_builtin_options->else_subgraph_index());
  return builtin_options_builder.Finish();
}
build_circle_L2NormOptions()
flatbuffers::Offset< circle::L2NormOptions > tflite2circle::build_circle_L2NormOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file L2NormalizeOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_L2NormOptions();
  assert(tflite_builtin_options);
  circle::L2NormOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_LeakyReluOptions()
flatbuffers::Offset< circle::LeakyReluOptions > tflite2circle::build_circle_LeakyReluOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file LeakyReluOptions.cpp.
{
  auto *tflite_builtin_options = op->builtin_options_as_LeakyReluOptions();
  assert(tflite_builtin_options);
  circle::LeakyReluOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_alpha(tflite_builtin_options->alpha());
  return builtin_options_builder.Finish();
}
build_circle_LessEqualOptions()
flatbuffers::Offset< circle::LessEqualOptions > tflite2circle::build_circle_LessEqualOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file LessEqualOptions.cpp.
{
  circle::LessEqualOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_LessOptions()
flatbuffers::Offset< circle::LessOptions > tflite2circle::build_circle_LessOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file LessOptions.cpp.
{
  circle::LessOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_LocalResponseNormalizationOptions()
flatbuffers::Offset< circle::LocalResponseNormalizationOptions > tflite2circle::build_circle_LocalResponseNormalizationOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file LocalResponseNormalizationOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_LocalResponseNormalizationOptions();
  assert(tflite_builtin_options);
  circle::LocalResponseNormalizationOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_radius(tflite_builtin_options->radius());
  builtin_options_builder.add_bias(tflite_builtin_options->bias());
  builtin_options_builder.add_alpha(tflite_builtin_options->alpha());
  builtin_options_builder.add_beta(tflite_builtin_options->beta());
  return builtin_options_builder.Finish();
}
build_circle_LogicalAndOptions()
flatbuffers::Offset< circle::LogicalAndOptions > tflite2circle::build_circle_LogicalAndOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file LogicalAndOptions.cpp.
{
  circle::LogicalAndOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_LogicalNotOptions()
flatbuffers::Offset< circle::LogicalNotOptions > tflite2circle::build_circle_LogicalNotOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file LogicalNotOptions.cpp.
{
  circle::LogicalNotOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_LogicalOrOptions()
flatbuffers::Offset< circle::LogicalOrOptions > tflite2circle::build_circle_LogicalOrOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file LogicalOrOptions.cpp.
{
  circle::LogicalOrOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_LogSoftmaxOptions()
flatbuffers::Offset< circle::LogSoftmaxOptions > tflite2circle::build_circle_LogSoftmaxOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file LogSoftmaxOptions.cpp.
{
  circle::LogSoftmaxOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_MatrixDiagOptions()
flatbuffers::Offset< circle::MatrixDiagOptions > tflite2circle::build_circle_MatrixDiagOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file MatrixDiagOptions.cpp.
{
  circle::MatrixDiagOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_MatrixSetDiagOptions()
flatbuffers::Offset< circle::MatrixSetDiagOptions > tflite2circle::build_circle_MatrixSetDiagOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file MatrixSetDiagOptions.cpp.
{
  circle::MatrixSetDiagOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_MaximumMinimumOptions()
flatbuffers::Offset< circle::MaximumMinimumOptions > tflite2circle::build_circle_MaximumMinimumOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file MaximumMinimumOptions.cpp.
{
  circle::MaximumMinimumOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_MirrorPadOptions()
flatbuffers::Offset< circle::MirrorPadOptions > tflite2circle::build_circle_MirrorPadOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file MirrorPadOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_MirrorPadOptions();
  assert(tflite_builtin_options);
  circle::MirrorPadOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_mode(get_circle_mirrorpad_mode(tflite_builtin_options->mode()));
  return builtin_options_builder.Finish();
}
References get_circle_mirrorpad_mode().
build_circle_MulOptions()
flatbuffers::Offset< circle::MulOptions > tflite2circle::build_circle_MulOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file MulOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_MulOptions();
  assert(tflite_builtin_options);
  circle::MulOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_NegOptions()
flatbuffers::Offset< circle::NegOptions > tflite2circle::build_circle_NegOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 25 of file NegOptions.cpp.
{
  circle::NegOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_NonMaxSuppressionV4Options()
flatbuffers::Offset< circle::NonMaxSuppressionV4Options > tflite2circle::build_circle_NonMaxSuppressionV4Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file NonMaxSuppressionV4Options.cpp.
{
  circle::NonMaxSuppressionV4OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_NonMaxSuppressionV5Options()
flatbuffers::Offset< circle::NonMaxSuppressionV5Options > tflite2circle::build_circle_NonMaxSuppressionV5Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file NonMaxSuppressionV5Options.cpp.
{
  circle::NonMaxSuppressionV5OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_NotEqualOptions()
flatbuffers::Offset< circle::NotEqualOptions > tflite2circle::build_circle_NotEqualOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file NotEqualOptions.cpp.
{
  circle::NotEqualOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_OneHotOptions()
flatbuffers::Offset< circle::OneHotOptions > tflite2circle::build_circle_OneHotOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file OneHotOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_OneHotOptions();
  assert(tflite_builtin_options);
  circle::OneHotOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_axis(tflite_builtin_options->axis());
  return builtin_options_builder.Finish();
}
build_circle_PackOptions()
flatbuffers::Offset< circle::PackOptions > tflite2circle::build_circle_PackOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file PackOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_PackOptions();
  assert(tflite_builtin_options);
  circle::PackOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_values_count(tflite_builtin_options->values_count());
  builtin_options_builder.add_axis(tflite_builtin_options->axis());
  return builtin_options_builder.Finish();
}
build_circle_PadOptions()
flatbuffers::Offset< circle::PadOptions > tflite2circle::build_circle_PadOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 24 of file PadOptions.cpp.
{
  circle::PadOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_PadV2Options()
flatbuffers::Offset< circle::PadV2Options > tflite2circle::build_circle_PadV2Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file PadV2Options.cpp.
{
  circle::PadV2OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_Pool2DOptions()
flatbuffers::Offset< circle::Pool2DOptions > tflite2circle::build_circle_Pool2DOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file Pool2DOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_Pool2DOptions();
  assert(tflite_builtin_options);
  circle::Pool2DOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_padding(get_circle_padding(tflite_builtin_options->padding()));
  builtin_options_builder.add_stride_w(tflite_builtin_options->stride_w());
  builtin_options_builder.add_stride_h(tflite_builtin_options->stride_h());
  builtin_options_builder.add_filter_width(tflite_builtin_options->filter_width());
  builtin_options_builder.add_filter_height(tflite_builtin_options->filter_height());
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type(), and get_circle_padding().
build_circle_PowOptions()
flatbuffers::Offset< circle::PowOptions > tflite2circle::build_circle_PowOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file PowOptions.cpp.
{
  circle::PowOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_RangeOptions()
flatbuffers::Offset< circle::RangeOptions > tflite2circle::build_circle_RangeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 26 of file RangeOptions.cpp.
{
  circle::RangeOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_RankOptions()
flatbuffers::Offset< circle::RankOptions > tflite2circle::build_circle_RankOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file RankOptions.cpp.
{
  circle::RankOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_ReducerOptions()
flatbuffers::Offset< circle::ReducerOptions > tflite2circle::build_circle_ReducerOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file ReducerOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ReducerOptions();
  assert(tflite_builtin_options);
  circle::ReducerOptionsBuilder reducer_options_builder{fb};
  reducer_options_builder.add_keep_dims(tflite_builtin_options->keep_dims());
  return reducer_options_builder.Finish();
}
build_circle_ReshapeOptions()
flatbuffers::Offset< circle::ReshapeOptions > tflite2circle::build_circle_ReshapeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file ReshapeOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ReshapeOptions();
  if (tflite_builtin_options == nullptr)
    return 0;
  std::vector<int32_t> new_shape_vec{tflite_builtin_options->new_shape()->begin(),
                                     tflite_builtin_options->new_shape()->end()};
  auto new_shape = fb.CreateVector(new_shape_vec);
  circle::ReshapeOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_new_shape(new_shape);
  return builtin_options_builder.Finish();
}
build_circle_ResizeBilinearOptions()
flatbuffers::Offset< circle::ResizeBilinearOptions > tflite2circle::build_circle_ResizeBilinearOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file ResizeBilinearOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ResizeBilinearOptions();
  assert(tflite_builtin_options);
  circle::ResizeBilinearOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_align_corners(tflite_builtin_options->align_corners());
  builtin_options_builder.add_half_pixel_centers(tflite_builtin_options->half_pixel_centers());
  return builtin_options_builder.Finish();
}
build_circle_ResizeNearestNeighborOptions()
flatbuffers::Offset< circle::ResizeNearestNeighborOptions > tflite2circle::build_circle_ResizeNearestNeighborOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file ResizeNearestNeighborOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ResizeNearestNeighborOptions();
  assert(tflite_builtin_options);
  circle::ResizeNearestNeighborOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_align_corners(tflite_builtin_options->align_corners());
  return builtin_options_builder.Finish();
}
build_circle_ReverseSequenceOptions()
flatbuffers::Offset< circle::ReverseSequenceOptions > tflite2circle::build_circle_ReverseSequenceOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file ReverseSequenceOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ReverseSequenceOptions();
  assert(tflite_builtin_options);
  circle::ReverseSequenceOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_seq_dim(tflite_builtin_options->seq_dim());
  builtin_options_builder.add_batch_dim(tflite_builtin_options->batch_dim());
  return builtin_options_builder.Finish();
}
build_circle_ReverseV2Options()
flatbuffers::Offset< circle::ReverseV2Options > tflite2circle::build_circle_ReverseV2Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file ReverseV2Options.cpp.
{
  circle::ReverseV2OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_ScatterNdOptions()
flatbuffers::Offset< circle::ScatterNdOptions > tflite2circle::build_circle_ScatterNdOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file ScatterNdOptions.cpp.
{
  circle::ScatterNdOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SegmentSumOptions()
flatbuffers::Offset< circle::SegmentSumOptions > tflite2circle::build_circle_SegmentSumOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file SegmentSumOptions.cpp.
{
  circle::SegmentSumOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SelectOptions()
flatbuffers::Offset< circle::SelectOptions > tflite2circle::build_circle_SelectOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file SelectOptions.cpp.
{
  circle::SelectOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SelectV2Options()
flatbuffers::Offset< circle::SelectV2Options > tflite2circle::build_circle_SelectV2Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file SelectV2Options.cpp.
{
  circle::SelectV2OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_ShapeOptions()
flatbuffers::Offset< circle::ShapeOptions > tflite2circle::build_circle_ShapeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file ShapeOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_ShapeOptions();
  assert(tflite_builtin_options);
  circle::ShapeOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_out_type(get_circle_tensortype(tflite_builtin_options->out_type()));
  return builtin_options_builder.Finish();
}
References get_circle_tensortype().
build_circle_SliceOptions()
flatbuffers::Offset< circle::SliceOptions > tflite2circle::build_circle_SliceOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file SliceOptions.cpp.
{
  circle::SliceOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SoftmaxOptions()
flatbuffers::Offset< circle::SoftmaxOptions > tflite2circle::build_circle_SoftmaxOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file SoftmaxOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SoftmaxOptions();
  assert(tflite_builtin_options);
  circle::SoftmaxOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_beta(tflite_builtin_options->beta());
  return builtin_options_builder.Finish();
}
build_circle_SpaceToBatchNDOptions()
flatbuffers::Offset< circle::SpaceToBatchNDOptions > tflite2circle::build_circle_SpaceToBatchNDOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 26 of file SpaceToBatchNDOptions.cpp.
{
  circle::SpaceToBatchNDOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SpaceToDepthOptions()
flatbuffers::Offset< circle::SpaceToDepthOptions > tflite2circle::build_circle_SpaceToDepthOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file SpaceToDepthOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SpaceToDepthOptions();
  assert(tflite_builtin_options);
  circle::SpaceToDepthOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_block_size(tflite_builtin_options->block_size());
  return builtin_options_builder.Finish();
}
build_circle_SparseToDenseOptions()
flatbuffers::Offset< circle::SparseToDenseOptions > tflite2circle::build_circle_SparseToDenseOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file SparseToDenseOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SparseToDenseOptions();
  assert(tflite_builtin_options);
  circle::SparseToDenseOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_validate_indices(tflite_builtin_options->validate_indices());
  return builtin_options_builder.Finish();
}
build_circle_SplitOptions()
flatbuffers::Offset< circle::SplitOptions > tflite2circle::build_circle_SplitOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file SplitOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SplitOptions();
  assert(tflite_builtin_options);
  circle::SplitOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_num_splits(tflite_builtin_options->num_splits());
  return builtin_options_builder.Finish();
}
build_circle_SplitVOptions()
flatbuffers::Offset< circle::SplitVOptions > tflite2circle::build_circle_SplitVOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file SplitVOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SplitVOptions();
  assert(tflite_builtin_options);
  circle::SplitVOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_num_splits(tflite_builtin_options->num_splits());
  return builtin_options_builder.Finish();
}
build_circle_SquaredDifferenceOptions()
flatbuffers::Offset< circle::SquaredDifferenceOptions > tflite2circle::build_circle_SquaredDifferenceOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 23 of file SquaredDifferenceOptions.cpp.
{
  circle::SquaredDifferenceOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SquareOptions()
flatbuffers::Offset< circle::SquareOptions > tflite2circle::build_circle_SquareOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file SquareOptions.cpp.
{
  circle::SquareOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_SqueezeOptions()
flatbuffers::Offset< circle::SqueezeOptions > tflite2circle::build_circle_SqueezeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file SqueezeOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SqueezeOptions();
  assert(tflite_builtin_options);
  std::vector<int32_t> squeeze_dims_vec{tflite_builtin_options->squeeze_dims()->begin(),
                                        tflite_builtin_options->squeeze_dims()->end()};
  auto squeeze_dims = fb.CreateVector(squeeze_dims_vec);
  circle::SqueezeOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_squeeze_dims(squeeze_dims);
  return builtin_options_builder.Finish();
}
build_circle_StridedSliceOptions()
flatbuffers::Offset< circle::StridedSliceOptions > tflite2circle::build_circle_StridedSliceOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file StridedSliceOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_StridedSliceOptions();
  assert(tflite_builtin_options);
  circle::StridedSliceOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_begin_mask(tflite_builtin_options->begin_mask());
  builtin_options_builder.add_end_mask(tflite_builtin_options->end_mask());
  builtin_options_builder.add_ellipsis_mask(tflite_builtin_options->ellipsis_mask());
  builtin_options_builder.add_new_axis_mask(tflite_builtin_options->new_axis_mask());
  builtin_options_builder.add_shrink_axis_mask(tflite_builtin_options->shrink_axis_mask());
  return builtin_options_builder.Finish();
}
build_circle_SubOptions()
flatbuffers::Offset< circle::SubOptions > tflite2circle::build_circle_SubOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file SubOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_SubOptions();
  assert(tflite_builtin_options);
  circle::SubOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_SVDFOptions()
flatbuffers::Offset< circle::SVDFOptions > tflite2circle::build_circle_SVDFOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file SVDFOptions.cpp.
{
  auto *tflite_builtin_options = op->builtin_options_as_SVDFOptions();
  assert(tflite_builtin_options);
  circle::SVDFOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_rank(tflite_builtin_options->rank());
  builtin_options_builder.add_asymmetric_quantize_inputs(
    tflite_builtin_options->asymmetric_quantize_inputs());
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_TileOptions()
flatbuffers::Offset< circle::TileOptions > tflite2circle::build_circle_TileOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file TileOptions.cpp.
{
  circle::TileOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_TopKV2Options()
flatbuffers::Offset< circle::TopKV2Options > tflite2circle::build_circle_TopKV2Options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file TopKV2Options.cpp.
{
  circle::TopKV2OptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_TransposeConvOptions()
flatbuffers::Offset< circle::TransposeConvOptions > tflite2circle::build_circle_TransposeConvOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file TransposeConvOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_TransposeConvOptions();
  assert(tflite_builtin_options);
  circle::TransposeConvOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_padding(get_circle_padding(tflite_builtin_options->padding()));
  builtin_options_builder.add_stride_w(tflite_builtin_options->stride_w());
  builtin_options_builder.add_stride_h(tflite_builtin_options->stride_h());
  return builtin_options_builder.Finish();
}
References get_circle_padding().
build_circle_TransposeOptions()
flatbuffers::Offset< circle::TransposeOptions > tflite2circle::build_circle_TransposeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 25 of file TransposeOptions.cpp.
{
  circle::TransposeOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_UnidirectionalSequenceLSTMOptions()
flatbuffers::Offset< circle::UnidirectionalSequenceLSTMOptions > tflite2circle::build_circle_UnidirectionalSequenceLSTMOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file UnidirectionalSequenceLSTMOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_UnidirectionalSequenceLSTMOptions();
  circle::UnidirectionalSequenceLSTMOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_fused_activation_function(
    get_circle_activation_function_type(tflite_builtin_options->fused_activation_function()));
  builtin_options_builder.add_cell_clip(tflite_builtin_options->cell_clip());
  builtin_options_builder.add_proj_clip(tflite_builtin_options->proj_clip());
  builtin_options_builder.add_time_major(tflite_builtin_options->time_major());
  builtin_options_builder.add_asymmetric_quantize_inputs(
    tflite_builtin_options->asymmetric_quantize_inputs());
  return builtin_options_builder.Finish();
}
References get_circle_activation_function_type().
build_circle_UniqueOptions()
flatbuffers::Offset< circle::UniqueOptions > tflite2circle::build_circle_UniqueOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file UniqueOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_UniqueOptions();
  assert(tflite_builtin_options);
  circle::UniqueOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_idx_out_type(
    get_circle_tensortype(tflite_builtin_options->idx_out_type()));
  return builtin_options_builder.Finish();
}
References get_circle_tensortype().
build_circle_UnpackOptions()
flatbuffers::Offset< circle::UnpackOptions > tflite2circle::build_circle_UnpackOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file UnpackOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_UnpackOptions();
  assert(tflite_builtin_options);
  circle::UnpackOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_num(tflite_builtin_options->num());
  builtin_options_builder.add_axis(tflite_builtin_options->axis());
  return builtin_options_builder.Finish();
}
build_circle_WhereOptions()
flatbuffers::Offset< circle::WhereOptions > tflite2circle::build_circle_WhereOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 23 of file WhereOptions.cpp.
{
  circle::WhereOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
build_circle_WhileOptions()
flatbuffers::Offset< circle::WhileOptions > tflite2circle::build_circle_WhileOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Definition at line 26 of file WhileOptions.cpp.
{
  auto tflite_builtin_options = op->builtin_options_as_WhileOptions();
  assert(tflite_builtin_options);
  circle::WhileOptionsBuilder builtin_options_builder{fb};
  builtin_options_builder.add_cond_subgraph_index(tflite_builtin_options->cond_subgraph_index());
  builtin_options_builder.add_body_subgraph_index(tflite_builtin_options->body_subgraph_index());
  return builtin_options_builder.Finish();
}
build_circle_ZerosLikeOptions()
flatbuffers::Offset< circle::ZerosLikeOptions > tflite2circle::build_circle_ZerosLikeOptions (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator *)
Definition at line 26 of file ZerosLikeOptions.cpp.
{
  circle::ZerosLikeOptionsBuilder builtin_options_builder{fb};
  return builtin_options_builder.Finish();
}
get_circle_activation_function_type()
circle::ActivationFunctionType tflite2circle::get_circle_activation_function_type (tflite::ActivationFunctionType tfl_aft)
Returns circle ActivationFunctionType according to tflite.
Note
You can see a list of currently supported ActivationFunctionType in TFLActivationFunctionType.lst file.
Definition at line 88 of file DataLookup.cpp.
{
  switch (tfl_aft)
  {
#define TFL_ACTIVATION_FUNCTION(TYPE)         \
  case tflite::ActivationFunctionType_##TYPE: \
    return circle::ActivationFunctionType_##TYPE;
#include "TFLActivationFunctionType.lst"
#undef TFL_ACTIVATION_FUNCTION
    default:
      throw std::runtime_error("tflite2circle: wrong activation function type.");
  }
}
Referenced by build_circle_AddOptions(), build_circle_BidirectionalSequenceLSTMOptions(), build_circle_ConcatenationOptions(), build_circle_Conv2DOptions(), build_circle_DepthwiseConv2DOptions(), build_circle_DivOptions(), build_circle_FullyConnectedOptions(), build_circle_L2NormOptions(), build_circle_MulOptions(), build_circle_Pool2DOptions(), build_circle_SubOptions(), build_circle_SVDFOptions(), and build_circle_UnidirectionalSequenceLSTMOptions().
get_circle_builtin_code() [1/3]
int32_t tflite2circle::get_circle_builtin_code (int32_t tfl_bop_i32)
Definition at line 42 of file DataLookup.cpp.
{
  tflite::BuiltinOperator tfl_bop = static_cast<tflite::BuiltinOperator>(tfl_bop_i32);
  switch (tfl_bop)
  {
#define TFL_OPERATOR(OP)             \
  case tflite::BuiltinOperator_##OP: \
    return static_cast<int32_t>(circle::BuiltinOperator_##OP);
#include "TFLOperator.lst"
#undef TFL_OPERATOR
    case tflite::BuiltinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES:
      return static_cast<int32_t>(circle::BuiltinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES);
    default:
      throw std::runtime_error("tflite2circle: wrong op");
  }
}
get_circle_builtin_code() [2/3]
int8_t tflite2circle::get_circle_builtin_code (int8_t tfl_bop_i8)
Definition at line 37 of file DataLookup.cpp.
{
  return get_circle_builtin_code(static_cast<int32_t>(tfl_bop_i8));
}
References get_circle_builtin_code().
get_circle_builtin_code() [3/3]
circle::BuiltinOperator tflite2circle::get_circle_builtin_code (tflite::BuiltinOperator tfl_bop)
Returns circle builtin_code according to tflite.
Note
You can see a list of currently supported BuiltinOperator in TFLOperator.lst file.
Definition at line 23 of file DataLookup.cpp.
{
  switch (tfl_bop)
  {
#define TFL_OPERATOR(OP)             \
  case tflite::BuiltinOperator_##OP: \
    return circle::BuiltinOperator_##OP;
#include "TFLOperator.lst"
#undef TFL_OPERATOR
    default:
      throw std::runtime_error("tflite2circle: wrong op");
  }
}
Referenced by tflite2circle::Offset< T >::build(), and get_circle_builtin_code().
get_circle_builtin_options()
flatbuffers::Offset< void > tflite2circle::get_circle_builtin_options (flatbuffers::FlatBufferBuilder & fb, const tflite::Operator * op)
Returns circle builtin_options according to tflite.
Note
You can see a list of currently supported BuiltinOptions in TFLBuiltinOptions.lst file.
This function calls the build_circle_#BuiltinOptions internally(e.g. build_circle_AbsOptions, build_circle_AddOptions, etc.), so refer to it for a more detailed implementation.
Definition at line 102 of file DataLookup.cpp.
{
  auto tflite_builtin_options_type = op->builtin_options_type();
  switch (tflite_builtin_options_type)
  {
    case tflite::BuiltinOptions_NONE:
      return flatbuffers::Offset<void>();
#define TFL_BUILTIN_OPTIONS(TYPE)     \
  case tflite::BuiltinOptions_##TYPE: \
    return build_circle_##TYPE(fb, op).Union();
#include "TFLBuiltinOptions.lst"
#undef TFL_BUILTIN_OPTIONS
    default:
      throw std::runtime_error("tflite2circle: wrong builtin options type.");
  }
}
Referenced by tflite2circle::Offset< T >::build().
get_circle_builtin_options_type()
circle::BuiltinOptions tflite2circle::get_circle_builtin_options_type (const tflite::Operator * op)
Returns circle builtin_options_type according to tflite.
Note
You can see a list of currently supported BuiltinOptions in TFLBuiltinOptions.lst file.
Definition at line 120 of file DataLookup.cpp.
{
  switch (op->builtin_options_type())
  {
    case tflite::BuiltinOptions_NONE:
      return circle::BuiltinOptions_NONE;
#define TFL_BUILTIN_OPTIONS(TYPE)     \
  case tflite::BuiltinOptions_##TYPE: \
    return circle::BuiltinOptions_##TYPE;
#include "TFLBuiltinOptions.lst"
#undef TFL_BUILTIN_OPTIONS
    default:
      throw std::runtime_error("tflite2circle: wrong builtin options type.");
  }
}
Referenced by tflite2circle::Offset< T >::build().
get_circle_dimension_type()
circle::DimensionType tflite2circle::get_circle_dimension_type (tflite::DimensionType tfl_dim_type)
Returns circle DimensionType according to tflite.
Definition at line 149 of file DataLookup.cpp.
{
  switch (tfl_dim_type)
  {
    case tflite::DimensionType_DENSE:
      return circle::DimensionType_DENSE;
    case tflite::DimensionType_SPARSE_CSR:
      return circle::DimensionType_SPARSE_CSR;
    default:
      throw std::runtime_error("tflite2circle: wrong dimension type.");
  }
}
Referenced by tflite2circle::Offset< T >::build().
get_circle_mirrorpad_mode()
circle::MirrorPadMode tflite2circle::get_circle_mirrorpad_mode (tflite::MirrorPadMode tfl_mode)
Returns circle MirrorPadMode according to tflite.
Definition at line 136 of file DataLookup.cpp.
{
  switch (tfl_mode)
  {
    case tflite::MirrorPadMode_REFLECT:
      return circle::MirrorPadMode_REFLECT;
    case tflite::MirrorPadMode_SYMMETRIC:
      return circle::MirrorPadMode_SYMMETRIC;
    default:
      throw std::runtime_error("tflite2circle: wrong mirrorpad mode.");
  }
}
Referenced by build_circle_MirrorPadOptions().
get_circle_padding()
circle::Padding tflite2circle::get_circle_padding (tflite::Padding tfl_p)
Returns circle Padding enum according to tflite.
Definition at line 74 of file DataLookup.cpp.
{
  switch (tfl_p)
  {
    case tflite::Padding_SAME:
      return circle::Padding_SAME;
    case tflite::Padding_VALID:
      return circle::Padding_VALID;
    default:
      throw std::runtime_error("tflite2circle: wrong padding");
  }
}
Referenced by build_circle_Conv2DOptions(), build_circle_DepthwiseConv2DOptions(), build_circle_Pool2DOptions(), and build_circle_TransposeConvOptions().
get_circle_sparse_index_vector()
flatbuffers::Offset< void > tflite2circle::get_circle_sparse_index_vector (flatbuffers::FlatBufferBuilder & fb, const void * v_array, const tflite::SparseIndexVector & tfl_sparse_index_vector_type)
Returns circle SparseIndexVector according to tflite.
Definition at line 163 of file DataLookup.cpp.
{
  switch (tfl_sparse_index_vector_type)
  {
    case tflite::SparseIndexVector_NONE:
      return flatbuffers::Offset<void>();
    case tflite::SparseIndexVector_Int32Vector:
    {
      const tflite::Int32Vector *i32_array = static_cast<const tflite::Int32Vector *>(v_array);
      auto values_vec_int32 =
        std::vector<int32_t>{i32_array->values()->begin(), i32_array->values()->end()};
      auto values_int32 = fb.CreateVector(values_vec_int32);
      circle::Int32VectorBuilder int32_vector_builder{fb};
      int32_vector_builder.add_values(values_int32);
      return int32_vector_builder.Finish().Union();
    }
    case tflite::SparseIndexVector_Uint16Vector:
    {
      const tflite::Uint16Vector *u16_array = static_cast<const tflite::Uint16Vector *>(v_array);
      auto values_vec_uint16 =
        std::vector<uint16_t>{u16_array->values()->begin(), u16_array->values()->end()};
      auto values_uint16 = fb.CreateVector(values_vec_uint16);
      circle::Uint16VectorBuilder uint16_vector_builder{fb};
      uint16_vector_builder.add_values(values_uint16);
      return uint16_vector_builder.Finish().Union();
    }
    case tflite::SparseIndexVector_Uint8Vector:
    {
      const tflite::Uint8Vector *u8_array = static_cast<const tflite::Uint8Vector *>(v_array);
      auto values_vec_uint8 =
        std::vector<uint8_t>{u8_array->values()->begin(), u8_array->values()->end()};
      auto values_uint8 = fb.CreateVector(values_vec_uint8);
      circle::Uint8VectorBuilder uint8_vector_builder{fb};
      uint8_vector_builder.add_values(values_uint8);
      return uint8_vector_builder.Finish().Union();
    }
    default:
      throw std::runtime_error("tflite2circle: wrong SparseIndexVector type.");
  }
}
Referenced by tflite2circle::Offset< T >::build().
get_circle_sparse_index_vector_type()
circle::SparseIndexVector tflite2circle::get_circle_sparse_index_vector_type (const tflite::SparseIndexVector & tfl_sparse_index_vector_type)
Returns circle SparseIndexVector type according to tflite.
Definition at line 206 of file DataLookup.cpp.
{
  switch (tfl_sparse_index_vector_type)
  {
    case tflite::SparseIndexVector_NONE:
      return circle::SparseIndexVector_NONE;
    case tflite::SparseIndexVector_Int32Vector:
      return circle::SparseIndexVector_Int32Vector;
    case tflite::SparseIndexVector_Uint16Vector:
      return circle::SparseIndexVector_Uint16Vector;
    case tflite::SparseIndexVector_Uint8Vector:
      return circle::SparseIndexVector_Uint8Vector;
    default:
      throw std::runtime_error("tflite2circle: wrong SparseIndexVector type.");
  }
}
Referenced by tflite2circle::Offset< T >::build().
get_circle_tensortype()
circle::TensorType tflite2circle::get_circle_tensortype (tflite::TensorType tfl_tt)
Returns circle TensorType according to tflite.
Note
You can see a list of currently supported TensorType in TFLTensorType.lst file.
Definition at line 60 of file DataLookup.cpp.
{
  switch (tfl_tt)
  {
#define TFL_TENSORTYPE(TENSORTYPE)      \
  case tflite::TensorType_##TENSORTYPE: \
    return circle::TensorType_##TENSORTYPE;
#include "TFLTensorType.lst"
#undef TFL_TENSORTYPE
    default:
      throw std::runtime_error("tflite2circle: wrong tensor type");
  }
}
Referenced by tflite2circle::Offset< T >::build(), build_circle_ArgMaxOptions(), build_circle_ArgMinOptions(), build_circle_CastOptions(), build_circle_ShapeOptions(), and build_circle_UniqueOptions().