ONE - On-device Neural Engine: vconone Namespace Reference
vconone Namespace Reference
Data Structures
struct four
union version
Functions
version get_number (void)
get_number will return version union structure
std::string get_string (void)
get_string will return string of major.minor.patch (without build)
std::string get_string4 (void)
get_string4 will return string of major.minor.patch.build
std::string get_copyright (void)
get_copyright will return copyright string
Function Documentation
get_copyright()
std::string vconone::get_copyright (void)
get_copyright will return copyright string
Definition at line 54 of file version.cpp.
{
  std::string str;
  str = "Copyright (c) 2020-2022 Samsung Electronics Co., Ltd. All Rights Reserved\r\n";
  str += "Licensed under the Apache License, Version 2.0\r\n";
  str += "https://github.com/Samsung/ONE";
  return str;
}
Referenced by main(), and print_version().
get_number()
version vconone::get_number (void)
get_number will return version union structure
Definition at line 26 of file version.cpp.
{
  version v;
  v.v = VCONONE_VERSION;
  return v;
}
References vconone::version::v.
Referenced by get_string(), and get_string4().
get_string()
std::string vconone::get_string (void)
get_string will return string of major.minor.patch (without build)
Definition at line 44 of file version.cpp.
{
  std::ostringstream ss;
  auto v = get_number();
  ss << unsigned(v.f.major) << "." << unsigned(v.f.minor) << "." << unsigned(v.f.patch);
  return ss.str();
}
References get_number().
Referenced by main(), and print_version().
get_string4()
std::string vconone::get_string4 (void)
get_string4 will return string of major.minor.patch.build
Definition at line 33 of file version.cpp.
{
  std::ostringstream ss;
  auto v = get_number();
  ss << unsigned(v.f.major) << "." << unsigned(v.f.minor) << "." << unsigned(v.f.patch) << "."
     << unsigned(v.f.build);
  return ss.str();
}
References get_number().