var namespacearm__compute =
[
    [ "misc", "namespacearm__compute_1_1misc.html", "namespacearm__compute_1_1misc" ],
    [ "weights_transformations", "namespacearm__compute_1_1weights__transformations.html", "namespacearm__compute_1_1weights__transformations" ],
    [ "CLArgMinMaxLayerEx", "classarm__compute_1_1_c_l_arg_min_max_layer_ex.html", "classarm__compute_1_1_c_l_arg_min_max_layer_ex" ],
    [ "CLArgMinMaxLayerKernelEx", "classarm__compute_1_1_c_l_arg_min_max_layer_kernel_ex.html", "classarm__compute_1_1_c_l_arg_min_max_layer_kernel_ex" ],
    [ "CLBinaryLogicalOp", "classarm__compute_1_1_c_l_binary_logical_op.html", "classarm__compute_1_1_c_l_binary_logical_op" ],
    [ "CLBinaryLogicalOpKernel", "classarm__compute_1_1_c_l_binary_logical_op_kernel.html", "classarm__compute_1_1_c_l_binary_logical_op_kernel" ],
    [ "CLCastBool", "classarm__compute_1_1_c_l_cast_bool.html", "classarm__compute_1_1_c_l_cast_bool" ],
    [ "CLCastBoolKernel", "classarm__compute_1_1_c_l_cast_bool_kernel.html", "classarm__compute_1_1_c_l_cast_bool_kernel" ],
    [ "CLDirectTransposeConvLayer", "classarm__compute_1_1_c_l_direct_transpose_conv_layer.html", "classarm__compute_1_1_c_l_direct_transpose_conv_layer" ],
    [ "CLEmbeddingLookup", "classarm__compute_1_1_c_l_embedding_lookup.html", "classarm__compute_1_1_c_l_embedding_lookup" ],
    [ "CLEmbeddingLookupKernel", "classarm__compute_1_1_c_l_embedding_lookup_kernel.html", "classarm__compute_1_1_c_l_embedding_lookup_kernel" ],
    [ "CLFullyConnectedHybridLayer", "classarm__compute_1_1_c_l_fully_connected_hybrid_layer.html", "classarm__compute_1_1_c_l_fully_connected_hybrid_layer" ],
    [ "CLFullyConnectedHybridLayerReshapeWeights", "classarm__compute_1_1_c_l_fully_connected_hybrid_layer_reshape_weights.html", "classarm__compute_1_1_c_l_fully_connected_hybrid_layer_reshape_weights" ],
    [ "CLFullyConnectedLayerEx", "classarm__compute_1_1_c_l_fully_connected_layer_ex.html", "classarm__compute_1_1_c_l_fully_connected_layer_ex" ],
    [ "CLFullyConnectedLayerReshapeWeightsEx", "classarm__compute_1_1_c_l_fully_connected_layer_reshape_weights_ex.html", "classarm__compute_1_1_c_l_fully_connected_layer_reshape_weights_ex" ],
    [ "CLFullyConnectedReshapingLayer", "classarm__compute_1_1_c_l_fully_connected_reshaping_layer.html", "classarm__compute_1_1_c_l_fully_connected_reshaping_layer" ],
    [ "CLGatherEx", "classarm__compute_1_1_c_l_gather_ex.html", "classarm__compute_1_1_c_l_gather_ex" ],
    [ "CLGatherExKernel", "classarm__compute_1_1_c_l_gather_ex_kernel.html", "classarm__compute_1_1_c_l_gather_ex_kernel" ],
    [ "CLGEMMMatrixAccumulateBiasesKernel", "classarm__compute_1_1_c_l_g_e_m_m_matrix_accumulate_biases_kernel.html", "classarm__compute_1_1_c_l_g_e_m_m_matrix_accumulate_biases_kernel" ],
    [ "CLHashtableLookup", "classarm__compute_1_1_c_l_hashtable_lookup.html", "classarm__compute_1_1_c_l_hashtable_lookup" ],
    [ "CLHashtableLookupKernel", "classarm__compute_1_1_c_l_hashtable_lookup_kernel.html", "classarm__compute_1_1_c_l_hashtable_lookup_kernel" ],
    [ "CLInstanceNormalizationLayerEx", "classarm__compute_1_1_c_l_instance_normalization_layer_ex.html", "classarm__compute_1_1_c_l_instance_normalization_layer_ex" ],
    [ "CLInstanceNormalizationLayerKernelEx", "classarm__compute_1_1_c_l_instance_normalization_layer_kernel_ex.html", "classarm__compute_1_1_c_l_instance_normalization_layer_kernel_ex" ],
    [ "CLKernelLibraryEx", "classarm__compute_1_1_c_l_kernel_library_ex.html", "classarm__compute_1_1_c_l_kernel_library_ex" ],
    [ "CLMemsetKernel", "classarm__compute_1_1_c_l_memset_kernel.html", "classarm__compute_1_1_c_l_memset_kernel" ],
    [ "CLMultiplyScaleFactorKernel", "classarm__compute_1_1_c_l_multiply_scale_factor_kernel.html", "classarm__compute_1_1_c_l_multiply_scale_factor_kernel" ],
    [ "CLNeg", "classarm__compute_1_1_c_l_neg.html", "classarm__compute_1_1_c_l_neg" ],
    [ "CLNegKernel", "classarm__compute_1_1_c_l_neg_kernel.html", "classarm__compute_1_1_c_l_neg_kernel" ],
    [ "CLOneHot", "classarm__compute_1_1_c_l_one_hot.html", "classarm__compute_1_1_c_l_one_hot" ],
    [ "CLOneHotKernel", "classarm__compute_1_1_c_l_one_hot_kernel.html", "classarm__compute_1_1_c_l_one_hot_kernel" ],
    [ "CLPadLayerEx", "classarm__compute_1_1_c_l_pad_layer_ex.html", "classarm__compute_1_1_c_l_pad_layer_ex" ],
    [ "CLPadLayerKernelEx", "classarm__compute_1_1_c_l_pad_layer_kernel_ex.html", "classarm__compute_1_1_c_l_pad_layer_kernel_ex" ],
    [ "CLQuantizationSymmetricKernel", "classarm__compute_1_1_c_l_quantization_symmetric_kernel.html", "classarm__compute_1_1_c_l_quantization_symmetric_kernel" ],
    [ "CLReduceOperation", "classarm__compute_1_1_c_l_reduce_operation.html", "classarm__compute_1_1_c_l_reduce_operation" ],
    [ "CLReduceOperationKernel", "classarm__compute_1_1_c_l_reduce_operation_kernel.html", "classarm__compute_1_1_c_l_reduce_operation_kernel" ],
    [ "CLScaleFactorSymm8Kernel", "classarm__compute_1_1_c_l_scale_factor_symm8_kernel.html", "classarm__compute_1_1_c_l_scale_factor_symm8_kernel" ],
    [ "CLSplitVEx", "classarm__compute_1_1_c_l_split_v_ex.html", "classarm__compute_1_1_c_l_split_v_ex" ],
    [ "CLTopKV2", "classarm__compute_1_1_c_l_top_k_v2.html", "classarm__compute_1_1_c_l_top_k_v2" ],
    [ "CLTransposeConvLayer", "classarm__compute_1_1_c_l_transpose_conv_layer.html", "classarm__compute_1_1_c_l_transpose_conv_layer" ],
    [ "NEBinaryLogicalOperation", "classarm__compute_1_1_n_e_binary_logical_operation.html", "classarm__compute_1_1_n_e_binary_logical_operation" ],
    [ "NEBinaryLogicalOperationKernel", "classarm__compute_1_1_n_e_binary_logical_operation_kernel.html", "classarm__compute_1_1_n_e_binary_logical_operation_kernel" ],
    [ "NEBinaryLogicalOperationStatic", "classarm__compute_1_1_n_e_binary_logical_operation_static.html", "classarm__compute_1_1_n_e_binary_logical_operation_static" ],
    [ "NECastBool", "classarm__compute_1_1_n_e_cast_bool.html", "classarm__compute_1_1_n_e_cast_bool" ],
    [ "NECastBoolKernel", "classarm__compute_1_1_n_e_cast_bool_kernel.html", "classarm__compute_1_1_n_e_cast_bool_kernel" ],
    [ "NEEmbeddingLookup", "classarm__compute_1_1_n_e_embedding_lookup.html", "classarm__compute_1_1_n_e_embedding_lookup" ],
    [ "NEEmbeddingLookupKernel", "classarm__compute_1_1_n_e_embedding_lookup_kernel.html", "classarm__compute_1_1_n_e_embedding_lookup_kernel" ],
    [ "NEFullyConnectedHybridLayer", "classarm__compute_1_1_n_e_fully_connected_hybrid_layer.html", "classarm__compute_1_1_n_e_fully_connected_hybrid_layer" ],
    [ "NEFullyConnectedHybridLayerReshapeWeights", "classarm__compute_1_1_n_e_fully_connected_hybrid_layer_reshape_weights.html", "classarm__compute_1_1_n_e_fully_connected_hybrid_layer_reshape_weights" ],
    [ "NEFullyConnectedLayerEx", "classarm__compute_1_1_n_e_fully_connected_layer_ex.html", "classarm__compute_1_1_n_e_fully_connected_layer_ex" ],
    [ "NEFullyConnectedReshapingLayer", "classarm__compute_1_1_n_e_fully_connected_reshaping_layer.html", "classarm__compute_1_1_n_e_fully_connected_reshaping_layer" ],
    [ "NEGatherEx", "classarm__compute_1_1_n_e_gather_ex.html", "classarm__compute_1_1_n_e_gather_ex" ],
    [ "NEGatherKernelEx", "classarm__compute_1_1_n_e_gather_kernel_ex.html", "classarm__compute_1_1_n_e_gather_kernel_ex" ],
    [ "NEGEMMMatrixAccumulateBiasesKernel", "classarm__compute_1_1_n_e_g_e_m_m_matrix_accumulate_biases_kernel.html", "classarm__compute_1_1_n_e_g_e_m_m_matrix_accumulate_biases_kernel" ],
    [ "NEHashtableLookup", "classarm__compute_1_1_n_e_hashtable_lookup.html", "classarm__compute_1_1_n_e_hashtable_lookup" ],
    [ "NEHashtableLookupKernel", "classarm__compute_1_1_n_e_hashtable_lookup_kernel.html", "classarm__compute_1_1_n_e_hashtable_lookup_kernel" ],
    [ "NEInstanceNormalizationLayerEx", "classarm__compute_1_1_n_e_instance_normalization_layer_ex.html", "classarm__compute_1_1_n_e_instance_normalization_layer_ex" ],
    [ "NEInstanceNormalizationLayerKernelEx", "classarm__compute_1_1_n_e_instance_normalization_layer_kernel_ex.html", "classarm__compute_1_1_n_e_instance_normalization_layer_kernel_ex" ],
    [ "NEMultiplyScaleFactorKernel", "classarm__compute_1_1_n_e_multiply_scale_factor_kernel.html", "classarm__compute_1_1_n_e_multiply_scale_factor_kernel" ],
    [ "NEOneHot", "classarm__compute_1_1_n_e_one_hot.html", "classarm__compute_1_1_n_e_one_hot" ],
    [ "NEOneHotKernel", "classarm__compute_1_1_n_e_one_hot_kernel.html", "classarm__compute_1_1_n_e_one_hot_kernel" ],
    [ "NEQuantizationSymmetricKernel", "classarm__compute_1_1_n_e_quantization_symmetric_kernel.html", "classarm__compute_1_1_n_e_quantization_symmetric_kernel" ],
    [ "NEReduceOperation", "classarm__compute_1_1_n_e_reduce_operation.html", "classarm__compute_1_1_n_e_reduce_operation" ],
    [ "NEReduceSum", "classarm__compute_1_1_n_e_reduce_sum.html", "classarm__compute_1_1_n_e_reduce_sum" ],
    [ "NETransposeConvLayer", "classarm__compute_1_1_n_e_transpose_conv_layer.html", "classarm__compute_1_1_n_e_transpose_conv_layer" ],
    [ "NELogicalAnd", "namespacearm__compute.html#a3c1d37a2b138520f5c1f138bbcd26488", null ],
    [ "NELogicalOr", "namespacearm__compute.html#a50bb7b981f1fa17145d6b11759307a5b", null ],
    [ "ArgOperation", "namespacearm__compute.html#a02982cbe2213549832c79a81acb63a99", [
      [ "MAX", "namespacearm__compute.html#a02982cbe2213549832c79a81acb63a99a26a4b44a837bf97b972628509912b4a5", null ],
      [ "MIN", "namespacearm__compute.html#a02982cbe2213549832c79a81acb63a99ace31e2a082d17e038fcc6e3006166653", null ]
    ] ],
    [ "BinaryLogicalOperation", "namespacearm__compute.html#aa942f8520662d206f0cddf63dadc10c9", [
      [ "AND", "namespacearm__compute.html#aa942f8520662d206f0cddf63dadc10c9a558ffc8f5770d8e4f95f51d822685532", null ],
      [ "OR", "namespacearm__compute.html#aa942f8520662d206f0cddf63dadc10c9a1d00e7dce692e8dc3f6877f035e3a616", null ]
    ] ],
    [ "ComparisonOperationEx", "namespacearm__compute.html#aa98b7f35f1cc6c32c83f5449508ee527", [
      [ "EQUAL", "namespacearm__compute.html#aa98b7f35f1cc6c32c83f5449508ee527a969f331a87d8c958473c32b4d0e61a44", null ],
      [ "NOT_EQUAL", "namespacearm__compute.html#aa98b7f35f1cc6c32c83f5449508ee527a4ea2d378cdec20f59330f113297bc1ce", null ]
    ] ],
    [ "ElementWiseUnaryEx", "namespacearm__compute.html#a61e4792e7691a069c74b3011c2d53444", [
      [ "NEG", "namespacearm__compute.html#a61e4792e7691a069c74b3011c2d53444a5dd68b1a7db42a1cce4dce09dbaa179e", null ]
    ] ],
    [ "SubDataType", "namespacearm__compute.html#aab54f1a8a8f027a9fbe26873be292eec", [
      [ "NONE", "namespacearm__compute.html#aab54f1a8a8f027a9fbe26873be292eecab50339a10e1de285ac99d4c3990b8693", null ],
      [ "BOOL", "namespacearm__compute.html#aab54f1a8a8f027a9fbe26873be292eecaa97b2c144243b2b9d2c593ec268b62f5", null ]
    ] ],
    [ "configure_func", "namespacearm__compute.html#aae42968895315eff699fde4aad00d71d", null ],
    [ "configure_logic_func", "namespacearm__compute.html#a5854916ef3b19a08b50fc1265f7bf3d0", null ],
    [ "elementwise_logic_op", "namespacearm__compute.html#a2c70f605ab933bd2e61cac978fac4925", null ],
    [ "elementwise_logic_op", "namespacearm__compute.html#ae1a4d9334f986f2a8a269850e31e327d", null ],
    [ "elementwise_logic_op", "namespacearm__compute.html#a026ec0b95882133c3daabaf2b7bee600", null ],
    [ "elementwise_logic_op_broadcast", "namespacearm__compute.html#a2b6803d55b858faf47ed1372c6301e76", null ],
    [ "elementwise_logic_op_broadcast_loop", "namespacearm__compute.html#aee9a058eb42f5f20e97f4832cf2e5d08", null ],
    [ "elementwise_logic_op_loop", "namespacearm__compute.html#a2710156b3181775e2e18624bb9f421c5", null ],
    [ "elementwise_logic_op_scalar", "namespacearm__compute.html#a8c9867d98ccdc3e77b15904cf62cf0ce", null ],
    [ "elementwise_op", "namespacearm__compute.html#a4c26cde94486dfea155ac5ba45e628e9", null ],
    [ "elementwise_op", "namespacearm__compute.html#a3cfe06ba40310d230cef7d46eca74f7f", null ],
    [ "transposeconv_output_dimensions", "namespacearm__compute.html#a386704431e8e28600e5b069d1275d0ea", null ]
];