ONE - On-device Neural Engine: onert::interp::concat Namespace Reference
onert::interp::concat Namespace Reference
Functions
void prepareConcat (ExecEnv *env, const ir::Operation &node)
void invoke (const std::vector< const ITensor * > in_tensors, const ITensor *out_tensor, uint32_t axis)
void invokeConcat (const ExecEnv *env, const ir::Operation &node)
Function Documentation
invoke()
void onert::interp::concat::invoke (const std::vector< const ITensor * > in_tensors, const ITensor * out_tensor, uint32_t axis)
Definition at line 83 of file Concat.cc.
{
  const uint32_t count = in_tensors.size();
  // Calculate
  nnfw::cker::ConcatenationParams cker_param;
  cker_param.axis = (int8_t)axis;
  cker_param.inputs_count = count;
  const auto out_shape = convertShape(out_tensor->tensorInfo().shape());
  std::vector<nnfw::cker::Shape> in_shapes;
  std::vector<const nnfw::cker::Shape *> in_shape_ptrs;
  in_shapes.reserve(count);
  in_shape_ptrs.reserve(count);
  std::vector<const float *> in_ptrs;
  for (uint32_t i = 0; i < count; i++)
  {
    in_shapes.push_back(convertShape(in_tensors[i]->tensorInfo().shape()));
    in_shape_ptrs.push_back(&in_shapes[i]);
    in_ptrs.push_back(reinterpret_cast<const float *>(in_tensors[i]->bufferRO()));
  }
  auto out_buffer = out_tensor->buffer();
  float *out_ptr = reinterpret_cast<float *>(out_buffer);
  nnfw::cker::Concatenation<float>(cker_param, in_shape_ptrs.data(), in_ptrs.data(), out_shape,
                                   out_ptr);
}
References nnfw::cker::ConcatenationParams::axis, onert::interp::ITensor::buffer(), onert::interp::convertShape(), nnfw::cker::ConcatenationParams::inputs_count, onert::ir::OperandInfo::shape(), and onert::interp::ITensor::tensorInfo().
Referenced by invokeConcat().
invokeConcat()
void onert::interp::concat::invokeConcat (const ExecEnv * env, const ir::Operation & node)
Definition at line 113 of file Concat.cc.
{
  const auto &concat_node = nnfw::misc::polymorphic_downcast<const ir::operation::Concat &>(node);
  const int32_t axis_raw = concat_node.param().axis;
  std::vector<const ITensor *> in_tensors;
  for (const auto &e : concat_node.getInputs())
  {
    in_tensors.emplace_back(env->tensorAt(e));
  }
  const auto out_index = node.getOutputs().at(0);
  const auto out_tensor = env->tensorAt(out_index);
  const uint32_t axis = (axis_raw < 0) ? (axis_raw + out_tensor->getShape().rank()) : axis_raw;
  const auto data_type = in_tensors[0]->data_type();
  if (data_type == ir::DataType::FLOAT32)
  {
    invoke(in_tensors, out_tensor, axis);
  }
  else
  {
    throw std::runtime_error{"NYI: Support float32 only"};
  }
}
References onert::ir::OperandIndexSequence::at(), onert::interp::ITensor::data_type(), onert::ir::Operation::getOutputs(), invoke(), and onert::interp::ExecEnv::tensorAt().
Referenced by onert::interp::getConcat().
prepareConcat()
void onert::interp::concat::prepareConcat (ExecEnv * env, const ir::Operation & node)
Definition at line 32 of file Concat.cc.
{
  const auto &concat_node = nnfw::misc::polymorphic_downcast<const ir::operation::Concat &>(node);
  const auto first_index = node.getInputs().at(0);
  const auto out_index = node.getOutputs().at(0);
  const auto first_tensor = env->tensorAt(first_index);
  uint32_t out_axis_dimension = 0;
  const int32_t axis_raw = concat_node.param().axis;
  const int32_t axis = (axis_raw < 0) ? (axis_raw + first_tensor->getShape().rank()) : axis_raw;
  // All inputs shape should be same except axis dimension
  // All inputs type should be same
  for (auto input : node.getInputs())
  {
    assert(first_tensor->getShape().rank() == env->tensorAt(input)->getShape().rank());
    assert(first_tensor->data_type() == env->tensorAt(input)->data_type());
    for (int i = 0; i < first_tensor->getShape().rank(); i++)
    {
      if (i == axis)
      {
        out_axis_dimension += env->tensorAt(input)->getShape().dim(i);
        continue;
      }
      assert(first_tensor->getShape().dim(i) == env->tensorAt(input)->getShape().dim(i));
    }
  }
  // Make output tensor info using first input tensor info, and accumulated axis dimension value
  auto out_shape = first_tensor->tensorInfo().shape();
  out_shape.dim(axis) = out_axis_dimension;
  env->allocateIfNeeded(
    out_index, ir::OperandInfo::createStaticInfo(out_shape, first_tensor->tensorInfo().typeInfo()));
  auto out_tensor = env->tensorAt(out_index);
  UNUSED_RELEASE(out_tensor);
  // Output shape should be same with input except axis getShape().dim
  // Output type should be same with input
  assert(first_tensor->data_type() == out_tensor->data_type());
  for (int i = 0; i < first_tensor->getShape().rank(); i++)
  {
    if (i == axis)
    {
      continue;
    }
    assert(first_tensor->getShape().dim(i) == out_tensor->getShape().dim(i));
  }
}
References onert::interp::ExecEnv::allocateIfNeeded(), onert::ir::OperandIndexSequence::at(), onert::ir::OperandInfo::createStaticInfo(), onert::interp::ITensor::data_type(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::backend::ITensor::getShape(), onert::interp::ExecEnv::tensorAt(), and UNUSED_RELEASE.
Referenced by onert::interp::getConcat().