ONE - On-device Neural Engine: logo Namespace Reference
logo Namespace Reference
Namespaces
namespace test
Data Structures
class ConstantFoldingPass
Performs constant folding optimization.
struct DeadNodeQueryService
class Pass
struct PhaseEventInfo
class PhaseEventInfo< PhaseEvent::PassBegin >
class PhaseEventInfo< PhaseEvent::PassEnd >
class PhaseEventInfo< PhaseEvent::PhaseBegin >
class PhaseEventInfo< PhaseEvent::PhaseEnd >
struct PhaseEventListener
class PhaseRunner
class PhaseRunner< PhaseStrategy::Restart >
class PhaseRunner< PhaseStrategy::Saturate >
class PhaseRunnerMixinObservable
struct RemoveDeadNodePass
struct RemoveDeadNodeWithQueryPass
struct RemoveForwardNodePass
Use the input of "Forward" node instead.
struct ReorderDecodePass
Reorder XXXDecode -> ? as ? -> XXXDecode if possible.
struct ReorderDecodePass< loco::ReLU >
struct ReorderDecodePass< loco::TensorBiasAdd >
class ResolveDuplicateReshapePass
Resolve duplicated Reshape nodes in a row.
class ResolveRedundantReshapePass
Remove redundant canonical FixedReshape.
struct SimplifyDomainConversionPass
Simplify redundant domain conversion.
Typedefs
using Phase = std::vector< std::unique_ptr< Pass > >
Enumerations
enum class PhaseEvent { PhaseBegin , PhaseEnd , PassBegin , PassEnd }
enum class PhaseStrategy { Saturate , Restart }
Functions
std::string pass_name (const Pass *)
void create_empty_test_net (loco::Graph *graph)
Typedef Documentation
Phase
using logo::Phase = typedef std::vector<std::unique_ptr<Pass> >
Definition at line 31 of file Phase.h.
Enumeration Type Documentation
PhaseEvent
enum class logo::PhaseEvent strong
Enumerator
PhaseBegin
PhaseEnd
PassBegin
PassEnd
Definition at line 33 of file Phase.h.
{
  PhaseBegin,
  PhaseEnd,
  PassBegin,
  PassEnd,
};
PhaseStrategy
enum class logo::PhaseStrategy strong
Enumerator
Saturate
Restart
Definition at line 150 of file Phase.h.
{
  // Run all the passes until there is no pass that makes a change
  Saturate,
  // Same as Saturate but will restart from the first when there is a change
  Restart,
};
Function Documentation
create_empty_test_net()
void logo::create_empty_test_net (loco::Graph * graph)
pass_name()
std::string logo::pass_name (const Pass * t)
Definition at line 22 of file Pass.cpp.
{
  if (t->name() == nullptr)
  {
    return "(unknown)";
  }
  return t->name();
}
References logo::Pass::name().
Referenced by exo::ProgressReporter::notify(), luci::ProgressReporter::notify(), luci::ModuleProgressReporter::notify(), and moco::tf::ProgressReporter::notify().