ONE - On-device Neural Engine: locomotiv Namespace Reference
locomotiv Namespace Reference
Data Structures
struct BinaryFunc
struct NodeData
Read-only no-template wrapper for 'Buffer'. Serves interface for input and output of 'Session'.
class NodeDataImpl
An implementation of NodeData interface.
struct NodeDomain
class NodeExecution
Helper class for Session, responsible to process one node calculation.
class Session
Session for loco graph inference.
struct UnaryFunc
Functions
template<typename DT >
std::unique_ptr< NodeData > make_data (const NodeData::Buffer< DT > &buffer)
Copy buffer to make NodeData.
template<>
std::unique_ptr< NodeData > make_data (const NodeData::Buffer< int32_t > &buf)
template<>
std::unique_ptr< NodeData > make_data (const NodeData::Buffer< float > &buf)
void annot_data (loco::Node *node, std::unique_ptr< NodeData > &&data)
Bind "NodeData" to "Node".
const NodeData * annot_data (const loco::Node *node)
Get "NodeData" for a given node.
void erase_annot_data (loco::Node *node)
Release "NodeData" bound to a given node.
void annot_domain (loco::Node *node, const loco::Domain &domain)
Wrapper to annotate domain to node. Cannot annotate unknown domain.
loco::Domain annot_domain (const loco::Node *node)
Wrapper to get domain annotation of node.
void erase_annot_domain (loco::Node *node)
Erase already annotated node domain.
const NodeData * user_data (const loco::Node *node)
void user_data (loco::Node *node, std::unique_ptr< NodeData > &&data)
void erase_user_data (loco::Node *node)
void validate (bool true_cond, const std::string &&exception_msg)
Function Documentation
annot_data() [1/2]
const NodeData * locomotiv::annot_data (const loco::Node * node)
Get "NodeData" for a given node.
NOTE Returns nullptr if "NodeData" is not binded yet
Definition at line 64 of file NodeDataImpl.cpp.
{
  if (auto annot = node->annot<NodeDataAnnotation>())
  {
    return annot->data();
  }
  return nullptr;
}
References loco::AnnotatedItem< Annotation >::annot().
annot_data() [2/2]
void locomotiv::annot_data (loco::Node * node, std::unique_ptr< NodeData > && data)
Bind "NodeData" to "Node".
Definition at line 59 of file NodeDataImpl.cpp.
{
  node->annot(std::make_unique<NodeDataAnnotation>(std::move(data)));
}
References loco::AnnotatedItem< Annotation >::annot().
Referenced by locomotiv::Session::get_output().
annot_domain() [1/2]
loco::Domain locomotiv::annot_domain (const loco::Node * node)
Wrapper to get domain annotation of node.
Definition at line 42 of file NodeDomain.cpp.
{
  auto node_domain = node->annot<NodeDomain>();
  if (node_domain)
    return node_domain->value;
  else
    return loco::Domain::Unknown;
}
References loco::AnnotatedItem< Annotation >::annot(), loco::Unknown, and locomotiv::NodeDomain::value.
annot_domain() [2/2]
void locomotiv::annot_domain (loco::Node * node, const loco::Domain & domain)
Wrapper to annotate domain to node. Cannot annotate unknown domain.
Definition at line 34 of file NodeDomain.cpp.
{
  assert(domain != loco::Domain::Unknown);
  auto node_domain = std::unique_ptr<NodeDomain>(new NodeDomain(domain));
  assert(node_domain);
  node->annot(std::move(node_domain));
}
References loco::AnnotatedItem< Annotation >::annot(), and loco::Unknown.
erase_annot_data()
void locomotiv::erase_annot_data (loco::Node * node)
Release "NodeData" bound to a given node.
Definition at line 74 of file NodeDataImpl.cpp.
{ node->annot<NodeDataAnnotation>(nullptr); }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by locomotiv::NodeExecution::run(), and locomotiv::Session::~Session().
erase_annot_domain()
void locomotiv::erase_annot_domain (loco::Node * node)
Erase already annotated node domain.
Definition at line 51 of file NodeDomain.cpp.
{ node->annot<NodeDomain>(nullptr); }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by locomotiv::Session::~Session().
erase_user_data()
void locomotiv::erase_user_data (loco::Node * node)
Definition at line 60 of file UserData.cpp.
{ node->annot<UserDataAnnotation>(nullptr); }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by locomotiv::Session::~Session().
make_data() [1/3]
template<typename DT > std::unique_ptr< NodeData > locomotiv::make_data (const NodeData::Buffer< DT > & buffer)
Copy buffer to make NodeData.
Note
NodeData is read-only. You may prepare buffer with ALL data, then call this function to make data.
References make_data().
Referenced by make_data(), and nnkit::support::moco::tf::Backend::prepare().
make_data() [2/3]
template<> std::unique_ptr< NodeData > locomotiv::make_data (const NodeData::Buffer< float > & buf)
Definition at line 28 of file NodeData.cpp.
{
  return std::unique_ptr<NodeDataImpl>(new NodeDataImpl(buf));
}
References make_data().
make_data() [3/3]
template<> std::unique_ptr< NodeData > locomotiv::make_data (const NodeData::Buffer< int32_t > & buf)
Definition at line 23 of file NodeData.cpp.
{
  return std::unique_ptr<NodeDataImpl>(new NodeDataImpl(buf));
}
References make_data().
user_data() [1/2]
const NodeData * locomotiv::user_data (const loco::Node * node)
Definition at line 45 of file UserData.cpp.
{
  if (auto annot = node->annot<UserDataAnnotation>())
  {
    return annot->data();
  }
  return nullptr;
}
References loco::AnnotatedItem< Annotation >::annot().
Referenced by locomotiv::Session::set_input().
user_data() [2/2]
void locomotiv::user_data (loco::Node * node, std::unique_ptr< NodeData > && data)
Definition at line 55 of file UserData.cpp.
{
  node->annot(std::make_unique<UserDataAnnotation>(std::move(data)));
}
References loco::AnnotatedItem< Annotation >::annot().
validate()
void locomotiv::validate (bool true_cond, const std::string && exception_msg) inline
Definition at line 26 of file Validation.h.
{
  if (!true_cond)
    throw std::runtime_error(exception_msg);
}