ONE - On-device Neural Engine: onnx-dump Namespace Reference
onnx-dump Namespace Reference
Functions
_data_type_str (data_type)
_get_attribute_value (attr)
_dump_header (onnx_model)
_dump_operators (onnx_model)
_dump_initializers (onnx_model)
_dump_nodes (onnx_model)
_dump_inputoutputs (onnx_model)
_dump_graph (onnx_model)
_help_exit (cmd_name)
main ()
Function Documentation
_data_type_str()
onnx-dump._data_type_str (data_type) protected
Definition at line 26 of file onnx-dump.py.
def _data_type_str(data_type):
    return TensorProto.DataType.Name(data_type)
Referenced by _dump_initializers(), _dump_inputoutputs(), and _get_attribute_value().
_dump_graph()
onnx-dump._dump_graph (onnx_model) protected
Definition at line 120 of file onnx-dump.py.
def _dump_graph(onnx_model):
    _dump_header(onnx_model)
    _dump_operators(onnx_model)
    _dump_initializers(onnx_model)
    _dump_nodes(onnx_model)
    _dump_inputoutputs(onnx_model)
References _dump_header(), _dump_initializers(), _dump_inputoutputs(), _dump_nodes(), and _dump_operators().
Referenced by main().
_dump_header()
onnx-dump._dump_header (onnx_model) protected
Definition at line 46 of file onnx-dump.py.
def _dump_header(onnx_model):
    print("[General] -----------------------------")
    print("IR version =", onnx_model.ir_version)
    print("Producer   =", onnx_model.producer_name, onnx_model.producer_version)
    print("")
Referenced by _dump_graph().
_dump_initializers()
onnx-dump._dump_initializers (onnx_model) protected
Definition at line 68 of file onnx-dump.py.
def _dump_initializers(onnx_model):
    print("[Initializers] ------------------------")
    for initializer in onnx_model.graph.initializer:
        init_name = '"{}"'.format(initializer.name)
        dtstr = _data_type_str(initializer.data_type)
        print('{:<15} {} {}'.format(init_name, dtstr, initializer.dims))
    print("")
References _data_type_str().
Referenced by _dump_graph().
_dump_inputoutputs()
onnx-dump._dump_inputoutputs (onnx_model) protected
Definition at line 101 of file onnx-dump.py.
def _dump_inputoutputs(onnx_model):
    print("[Graph Input/Output]-------------------")
    for mod_input in onnx_model.graph.input:
        io_name = '"{}"'.format(mod_input.name)
        dtstr = _data_type_str(mod_input.type.tensor_type.elem_type)
        shape = mod_input.type.tensor_type.shape
        input_shape = [dim.dim_value for dim in shape.dim]
        print('    I: {:<15} {} {}'.format(io_name, dtstr, input_shape))
    for mod_output in onnx_model.graph.output:
        io_name = '"{}"'.format(mod_output.name)
        dtstr = _data_type_str(mod_output.type.tensor_type.elem_type)
        shape = mod_output.type.tensor_type.shape
        output_shape = [dim.dim_value for dim in shape.dim]
        print('    O: {:<15} {} {}'.format(io_name, dtstr, output_shape))
    print("")
References _data_type_str().
Referenced by _dump_graph().
_dump_nodes()
onnx-dump._dump_nodes (onnx_model) protected
Definition at line 78 of file onnx-dump.py.
def _dump_nodes(onnx_model):
    print("[Nodes] -------------------------------")
    for node in onnx_model.graph.node:
        print('{0}("{1}")'.format(node.op_type, node.name))
        attribute = ''
        for attr in node.attribute:
            if attribute != '':
                attribute += ', '
            attribute += "{}: {}".format(attr.name, _get_attribute_value(attr))
        if attribute != '':
            print('    A {0}'.format(attribute))
        for inp in node.input:
            print('    I "{0}"'.format(inp))
        for out in node.output:
            print('    O "{0}"'.format(out))
    print("")
References _get_attribute_value().
Referenced by _dump_graph().
_dump_operators()
onnx-dump._dump_operators (onnx_model) protected
Definition at line 53 of file onnx-dump.py.
def _dump_operators(onnx_model):
    opcodes_dict = dict()
    for node in onnx_model.graph.node:
        if node.op_type in opcodes_dict:
            opcodes_dict[node.op_type] = opcodes_dict[node.op_type] + 1
        else:
            opcodes_dict[node.op_type] = 1
    print("[Operators] ---------------------------")
    for opcode_key in opcodes_dict:
        print("{:>5} {}".format(opcodes_dict[opcode_key], opcode_key))
    print("")
Referenced by _dump_graph().
_get_attribute_value()
onnx-dump._get_attribute_value (attr) protected
Definition at line 30 of file onnx-dump.py.
def _get_attribute_value(attr):
    if attr.type == AttributeProto.TENSOR:
        return "{}, {}".format(
            _data_type_str(attr.t.data_type), numpy_helper.to_array(attr.t))
    if attr.type == AttributeProto.GRAPH:
        # TODO revise when graph node is available
        return "<graph>"
    if attr.type == AttributeProto.TENSORS:
        # TODO revise to see contents
        return "<tensors>..."
    if attr.type == AttributeProto.GRAPHS:
        # TODO revise when graph node is available
        return "<graphs>..."
    return helper.get_attribute_value(attr)
References _data_type_str().
Referenced by _dump_nodes().
_help_exit()
onnx-dump._help_exit (cmd_name) protected
Definition at line 128 of file onnx-dump.py.
def _help_exit(cmd_name):
    print('Dump ONNX model file Graph')
    print('Usage: {0} [onnx_path]'.format(cmd_name))
    print('')
    exit()
Referenced by main().
main()
onnx-dump.main ()
Definition at line 135 of file onnx-dump.py.
def main():
    if len(sys.argv) < 2:
        _help_exit(os.path.basename(sys.argv[0]))
    onnx_model = onnx.load(sys.argv[1])
    onnx.checker.check_model(onnx_model)
    _dump_graph(onnx_model)
References _dump_graph(), _help_exit(), and main().
Referenced by main().