ONE - On-device Neural Engine: onert::backend::ruy::ops Namespace Reference
onert::backend::ruy::ops Namespace Reference
Data Structures
class ConvolutionLayer
class FullyConnectedLayer
Functions
nnfw::ruy::PaddingType getPaddingType (ir::PaddingType ir_padding_type)
nnfw::ruy::Shape getTensorShape (const IPortableTensor *tensor)
nnfw::ruy::FusedActivationFunctionType convertActivationType (const ir::Activation activation)
Function Documentation
convertActivationType()
nnfw::ruy::FusedActivationFunctionType onert::backend::ruy::ops::convertActivationType (const ir::Activation activation) inline
Definition at line 61 of file OperationUtils.h.
{
  switch (activation)
  {
    case ir::Activation::NONE:
      return nnfw::ruy::FusedActivationFunctionType::kNone;
    case ir::Activation::RELU:
      return nnfw::ruy::FusedActivationFunctionType::kRelu;
    case ir::Activation::RELU1:
      return nnfw::ruy::FusedActivationFunctionType::kRelu1;
    case ir::Activation::RELU6:
      return nnfw::ruy::FusedActivationFunctionType::kRelu6;
    case ir::Activation::TANH:
      return nnfw::ruy::FusedActivationFunctionType::kTanh;
    case ir::Activation::SIGMOID:
      return nnfw::ruy::FusedActivationFunctionType::kSigmoid;
    default:
      throw std::runtime_error{"RUY backend: Cannot convert activation type"};
  }
}
References nnfw::ruy::kNone, nnfw::ruy::kRelu, nnfw::ruy::kRelu1, nnfw::ruy::kRelu6, nnfw::ruy::kSigmoid, nnfw::ruy::kTanh, onert::ir::NONE, onert::ir::RELU, onert::ir::RELU1, onert::ir::RELU6, onert::ir::SIGMOID, and onert::ir::TANH.
Referenced by onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32().
getPaddingType()
nnfw::ruy::PaddingType onert::backend::ruy::ops::getPaddingType (ir::PaddingType ir_padding_type)
Definition at line 28 of file OperationUtils.cc.
{
  switch (ir_padding_type)
  {
    case ir::PaddingType::EXPLICIT:
      return nnfw::ruy::PaddingType::kNone;
    case ir::PaddingType::SAME:
      return nnfw::ruy::PaddingType::kSame;
    case ir::PaddingType::VALID:
      return nnfw::ruy::PaddingType::kValid;
    default:
      throw std::runtime_error("Wrong padding type.");
      break;
  }
}
References onert::ir::EXPLICIT, nnfw::ruy::kNone, nnfw::ruy::kSame, nnfw::ruy::kValid, onert::ir::SAME, and onert::ir::VALID.
Referenced by onert::backend::ruy::ops::ConvolutionLayer::convFloat32().
getTensorShape()
nnfw::ruy::Shape onert::backend::ruy::ops::getTensorShape (const IPortableTensor * tensor) inline
Definition at line 42 of file OperationUtils.h.
{
  if (tensor == nullptr)
    return nnfw::ruy::Shape();
  const ir::Shape &shape = tensor->get_info().shape();
  assert(tensor->layout() == ir::Layout::NHWC);
  auto rank = shape.rank();
  nnfw::ruy::Shape ret(rank);
  auto data = ret.DimsData();
  for (int i = 0; i < rank; ++i)
  {
    data[i] = shape.dim(i);
  }
  return ret;
}
References nnfw::ruy::Shape::DimsData(), and onert::ir::NHWC.
Referenced by onert::backend::ruy::ops::ConvolutionLayer::convFloat32(), onert::backend::ruy::ops::FullyConnectedLayer::fullyConnectedFloat32(), onert::backend::ruy::ops::ConvolutionLayer::prepare(), and onert::backend::ruy::ops::FullyConnectedLayer::prepare().