ONE - On-device Neural Engine: mir_caffe Namespace Reference
mir_caffe Namespace Reference
Data Structures
class CaffeOpCreator
Enumerations
enum class CaffeOpType {
absVal , accuracy , argMax , batchNorm ,
batchReindex , bias , BNLL , clip ,
concat , contrastiveLoss , convolution , crop ,
data , deconvolution , dropout , dummyData ,
eltwise , ELU , embed , euclidianLoss ,
exp , filter , flatten , HDF5Data ,
HDF5Output , hingeLoss , im2Col , imageData ,
infogainLoss , innerProduct , input , log ,
LRN , LSTM , memoryData , multinomialLogisticLoss ,
MVN , parameter , pooling , power ,
PReLU , python , recurrent , reduction ,
ReLU , reshape , RNN , scale ,
sigmoidCrossEntropyLoss , sigmoid , silence , slice ,
softmax , softmaxWithLoss , split , SPP ,
tanh , threshold , tile , windowData
}
Functions
std::unique_ptr< mir::Graph > importModelFromBinaryFile (const std::string &filename)
std::unique_ptr< mir::Graph > importModelFromTextFile (const std::string &filename)
std::unique_ptr< mir::Graph > loadModel (const std::string &filename)
Enumeration Type Documentation
CaffeOpType
enum class mir_caffe::CaffeOpType strong
Enumerator
absVal
accuracy
argMax
batchNorm
batchReindex
bias
BNLL
clip
concat
contrastiveLoss
convolution
crop
data
deconvolution
dropout
dummyData
eltwise
ELU
embed
euclidianLoss
exp
filter
flatten
HDF5Data
HDF5Output
hingeLoss
im2Col
imageData
infogainLoss
innerProduct
input
log
LRN
LSTM
memoryData
multinomialLogisticLoss
MVN
parameter
pooling
power
PReLU
python
recurrent
reduction
ReLU
reshape
RNN
scale
sigmoidCrossEntropyLoss
sigmoid
silence
slice
softmax
softmaxWithLoss
split
SPP
tanh
threshold
tile
windowData
Definition at line 23 of file caffe_op_types.h.
{
  absVal,
  accuracy,
  argMax,
  batchNorm,
  batchReindex,
  bias,
  BNLL,
  clip,
  concat,
  contrastiveLoss,
  convolution,
  crop,
  data,
  deconvolution,
  dropout,
  dummyData,
  eltwise,
  ELU,
  embed,
  euclidianLoss,
  exp,
  filter,
  flatten,
  HDF5Data,
  HDF5Output,
  hingeLoss,
  im2Col,
  imageData,
  infogainLoss,
  innerProduct,
  input,
  log,
  LRN,
  LSTM,
  memoryData,
  multinomialLogisticLoss,
  MVN,
  parameter,
  pooling,
  power,
  PReLU,
  python,
  recurrent,
  reduction,
  ReLU,
  reshape,
  RNN,
  scale,
  sigmoidCrossEntropyLoss,
  sigmoid,
  silence,
  slice,
  softmax,
  softmaxWithLoss,
  split,
  SPP,
  tanh,
  threshold,
  tile,
  windowData
};
Function Documentation
importModelFromBinaryFile()
std::unique_ptr< mir::Graph > mir_caffe::importModelFromBinaryFile (const std::string & filename)
Definition at line 422 of file caffe_importer.cpp.
{
  CaffeImporter importer;
  return importer.importModelFromBinaryFile(filename);
}
Referenced by loadModel(), and main().
importModelFromTextFile()
std::unique_ptr< mir::Graph > mir_caffe::importModelFromTextFile (const std::string & filename)
Definition at line 428 of file caffe_importer.cpp.
{
  CaffeImporter importer;
  return importer.importModelFromTextFile(filename);
}
loadModel()
std::unique_ptr< mir::Graph > mir_caffe::loadModel (const std::string & filename)
Definition at line 434 of file caffe_importer.cpp.
{
  return importModelFromBinaryFile(filename);
}
References importModelFromBinaryFile().
Referenced by main().