ONE - On-device Neural Engine: plier::tf Namespace Reference
plier::tf Namespace Reference
Enumerations
enum class DataLayout { NHWC , NCHW }
Class to represent TensorFlow "data_format" attr.
Functions
bool has_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
bool has_attrs (const tensorflow::NodeDef &node, const std::vector< std::string > &attr_names)
tensorflow::DataType get_datatype_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
const tensorflow::TensorShapeProto & get_shape_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
const tensorflow::TensorProto & get_tensor_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
const tensorflow::AttrValue_ListValue & get_list_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
const std::string & get_string_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
int64_t get_int_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
float get_float_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
bool get_bool_attr (const tensorflow::NodeDef &node, const std::string &attr_name)
std::vector< int64_t > as_int64_list (const tensorflow::AttrValue_ListValue &lv)
loco::DataType as_loco_datatype (const tensorflow::DataType dtype)
DataLayout as_data_layout (const std::string &tf_layout_str)
@ brief Convert TF Data Layout string (e.g., "NHWC") to enum class for programming convenience
DataLayout get_data_layout (const tensorflow::NodeDef &node, const std::string &attr_name)
void copy_shape (const tensorflow::TensorShapeProto &tf_shape, nncc::core::ADT::tensor::Shape &to_shape)
Copy shape defined in TensorShapeProto to angkor shape.
bool parse_graphdef (char const *pbtxt, tensorflow::GraphDef &graphdef)
bool parse_nodedef (char const *pbtxt, tensorflow::NodeDef &nodedef)
Enumeration Type Documentation
DataLayout
enum class plier::tf::DataLayout strong
Class to represent TensorFlow "data_format" attr.
Enumerator
NHWC
NCHW
Definition at line 56 of file Convert.h.
{
  NHWC,
  NCHW,
};
Function Documentation
as_data_layout()
DataLayout plier::tf::as_data_layout (const std::string & tf_layout_str)
@ brief Convert TF Data Layout string (e.g., "NHWC") to enum class for programming convenience
Definition at line 146 of file Convert.cpp.
{
  if (tf_layout_str == "NHWC")
    return DataLayout::NHWC;
  else if (tf_layout_str == "NCHW")
    return DataLayout::NCHW;
  else
    throw std::runtime_error("unknown data layout");
}
References NCHW, and NHWC.
as_int64_list()
std::vector< int64_t > plier::tf::as_int64_list (const tensorflow::AttrValue_ListValue & lv)
Definition at line 111 of file Convert.cpp.
{
  std::vector<int64_t> vi;
  int isize = lv.i_size();
  vi.resize(isize);
  for (int i = 0; i < isize; ++i)
    vi[i] = lv.i(i);
  return vi;
}
Referenced by moco::AvgPoolGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::AvgPoolGraphBuilder::validate(), moco::MaxPoolGraphBuilder::validate(), and moco::DepthwiseConv2dNativeGraphBuilder::validate().
as_loco_datatype()
loco::DataType plier::tf::as_loco_datatype (const tensorflow::DataType dtype)
Definition at line 123 of file Convert.cpp.
{
  switch (tf_dtype)
  {
    case tensorflow::DT_INT8:
      return loco::DataType::S8;
    case tensorflow::DT_UINT8:
      return loco::DataType::U8;
    case tensorflow::DT_FLOAT:
      return loco::DataType::FLOAT32;
    case tensorflow::DT_INT32:
      return loco::DataType::S32;
    case tensorflow::DT_INT64:
      return loco::DataType::S64;
    case tensorflow::DT_BOOL:
    case tensorflow::DT_STRING:
    case tensorflow::DT_COMPLEX64:
    default:
      break;
  }
  throw std::runtime_error{"Unsupported tensorflow dtype: " + tensorflow::DataType_Name(tf_dtype)};
}
Referenced by moco::ConstGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::ConstGraphBuilder::validate(), and moco::PlaceholderGraphBuilder::validate().
copy_shape()
void plier::tf::copy_shape (const tensorflow::TensorShapeProto & tf_shape, nncc::core::ADT::tensor::Shape & to_shape)
Copy shape defined in TensorShapeProto to angkor shape.
Note
Unknown dimension is not supported
Definition at line 168 of file Convert.cpp.
{
  assert(!tf_shape.unknown_rank());
  int64_t tf_rank = tf_shape.dim_size();
  assert(tf_rank < std::numeric_limits<uint32_t>::max());
  int32_t rank = static_cast<int32_t>(tf_rank);
  to_shape.resize(rank);
  for (int32_t d = 0; d < rank; d++)
  {
    int64_t dim_value = tf_shape.dim(d).size();
    assert(dim_value < std::numeric_limits<uint32_t>::max());
    if (dim_value >= 0LL)
    {
      uint32_t dim_value32 = static_cast<uint32_t>(dim_value);
      to_shape.dim(d) = dim_value32;
    }
    else
    {
      throw std::runtime_error("Cannot handle unknown dimension");
      // TODO support unknown dimension
    }
  }
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::resize().
get_bool_attr()
bool plier::tf::get_bool_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 103 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kB);
  return attr.b();
}
References has_attr().
Referenced by moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), and moco::MeanGraphBuilder::build().
get_data_layout()
DataLayout plier::tf::get_data_layout (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 156 of file Convert.cpp.
{
  auto layout = get_string_attr(node, attr_name);
  if (layout == "NHWC")
    return DataLayout::NHWC;
  else if (layout == "NCHW")
    return DataLayout::NCHW;
  else
    throw std::runtime_error("unknown data layout");
}
References get_string_attr(), NCHW, and NHWC.
get_datatype_attr()
tensorflow::DataType plier::tf::get_datatype_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 43 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kType);
  return attr.type();
}
References has_attr().
Referenced by moco::ConstGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::ConstGraphBuilder::validate(), moco::MeanGraphBuilder::validate(), and moco::PlaceholderGraphBuilder::validate().
get_float_attr()
float plier::tf::get_float_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 95 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kF);
  return attr.f();
}
References has_attr().
Referenced by moco::FusedBatchNormGraphBuilder::build().
get_int_attr()
int64_t plier::tf::get_int_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 87 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kI);
  return attr.i();
}
References has_attr().
Referenced by moco::PackGraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::ConcatV2GraphBuilder::validate(), and moco::PackGraphBuilder::validate().
get_list_attr()
const ::tensorflow::AttrValue_ListValue & plier::tf::get_list_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 70 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kList);
  return attr.list();
}
References has_attr().
Referenced by moco::AvgPoolGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::AvgPoolGraphBuilder::validate(), moco::Conv2DGraphBuilder::validate(), moco::MaxPoolGraphBuilder::validate(), moco::Conv2DBackpropInputGraphBuilder::validate(), and moco::DepthwiseConv2dNativeGraphBuilder::validate().
get_shape_attr()
const tensorflow::TensorShapeProto & plier::tf::get_shape_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 52 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kShape);
  return attr.shape();
}
References has_attr().
Referenced by moco::PlaceholderGraphBuilder::build().
get_string_attr()
const std::string & plier::tf::get_string_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 79 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kS);
  return attr.s();
}
References has_attr().
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), get_data_layout(), moco::BiasAddGraphBuilder::validate(), moco::Conv2DGraphBuilder::validate(), moco::MaxPoolGraphBuilder::validate(), moco::Conv2DBackpropInputGraphBuilder::validate(), and moco::DepthwiseConv2dNativeGraphBuilder::validate().
get_tensor_attr()
const tensorflow::TensorProto & plier::tf::get_tensor_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 61 of file Convert.cpp.
{
  assert(has_attr(node, attr_name));
  const auto &attr = node.attr().at(attr_name);
  assert(attr.value_case() == tensorflow::AttrValue::kTensor);
  return attr.tensor();
}
References has_attr().
Referenced by moco::ConstGraphBuilder::build(), and moco::ConstGraphBuilder::validate().
has_attr()
bool plier::tf::has_attr (const tensorflow::NodeDef & node, const std::string & attr_name)
Definition at line 30 of file Convert.cpp.
{
  return node.attr().count(attr_name) > 0;
}
Referenced by moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), get_bool_attr(), get_datatype_attr(), get_float_attr(), get_int_attr(), get_list_attr(), get_shape_attr(), get_string_attr(), get_tensor_attr(), has_attrs(), moco::Conv2DGraphBuilder::validate(), and moco::Conv2DBackpropInputGraphBuilder::validate().
has_attrs()
bool plier::tf::has_attrs (const tensorflow::NodeDef & node, const std::vector< std::string > & attr_names)
Definition at line 35 of file Convert.cpp.
{
  for (auto &attr : attr_names)
    if (!has_attr(node, attr))
      return false;
  return true;
}
References has_attr().
Referenced by moco::ShapeGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::AvgPoolGraphBuilder::validate(), moco::BiasAddGraphBuilder::validate(), moco::ConcatV2GraphBuilder::validate(), moco::ConstGraphBuilder::validate(), moco::Conv2DGraphBuilder::validate(), moco::MaxPoolGraphBuilder::validate(), moco::PackGraphBuilder::validate(), moco::StridedSliceGraphBuilder::validate(), moco::Conv2DBackpropInputGraphBuilder::validate(), moco::DepthwiseConv2dNativeGraphBuilder::validate(), moco::FusedBatchNormGraphBuilder::validate(), moco::MeanGraphBuilder::validate(), moco::PadGraphBuilder::validate(), moco::PlaceholderGraphBuilder::validate(), moco::ReshapeGraphBuilder::validate(), moco::ShapeGraphBuilder::validate(), moco::SoftmaxGraphBuilder::validate(), moco::SqueezeGraphBuilder::validate(), and moco::StopGradientGraphBuilder::validate().
parse_graphdef()
bool plier::tf::parse_graphdef (char const * pbtxt, tensorflow::GraphDef & graphdef)
Definition at line 55 of file TestHelper.cpp.
{
  imemstream mempb(pbtxt, std::strlen(pbtxt));
  google::protobuf::io::IstreamInputStream iis(&mempb);
  return google::protobuf::TextFormat::Parse(&iis, &graphdef);
}
parse_nodedef()
bool plier::tf::parse_nodedef (char const * pbtxt, tensorflow::NodeDef & nodedef)
Definition at line 62 of file TestHelper.cpp.
{
  imemstream mempb(pbtxt, std::strlen(pbtxt));
  google::protobuf::io::IstreamInputStream iis(&mempb);
  return google::protobuf::TextFormat::Parse(&iis, &nodedef);
}