ONE - On-device Neural Engine: nnfw::rt::optimized_ops Namespace Reference
nnfw::rt::optimized_ops Namespace Reference
Data Structures
class TopContainer
class to define TopK operation
Functions
template<typename T >
void TopK (int32 row_size, int32 num_rows, const T *data, int32 k, int32 *output_indexes, T *output_values)
Operates TopK operation with params.
Function Documentation
TopK()
template<typename T > void nnfw::rt::optimized_ops::TopK (int32 row_size, int32 num_rows, const T * data, int32 k, int32 * output_indexes, T * output_values)
Operates TopK operation with params.
Parameters
[in] row_size Size of row in data
[in] num_rows The number of rows in data
[in] data To be operated in
[in] k The top k predictions
[out] output_indexes Indexes of targets in the top k predictions
[out] output_values Values of targets in the top k predictions
Returns
N/A
Definition at line 163 of file topk_v2.h.
{
  TopContainer<T> topc(k, row_size);
  for (int row = 0; row < num_rows; ++row)
  {
    const T *values_row = data + row * row_size;
    topc.start_collecting(values_row);
    for (int32 c = 0; c < row_size; ++c)
    {
      topc.push(c);
    }
    // Prepare output buffers.
    int32 *indexes_row = output_indexes + row * k;
    T *output_row = output_values + row * k;
    // We always assume that the output is sorted.
    const auto &top_k = topc.sorted_result();
    std::copy(top_k.begin(), top_k.end(), indexes_row);
    std::transform(top_k.begin(), top_k.end(), output_row,
                   [values_row](const int32 loc) { return values_row[loc]; });
  }
}
References nnfw::rt::optimized_ops::TopContainer< T >::push(), nnfw::rt::optimized_ops::TopContainer< T >::sorted_result(), and nnfw::rt::optimized_ops::TopContainer< T >::start_collecting().