ONE - On-device Neural Engine: onert::interp Namespace Reference
onert::interp Namespace Reference
Namespaces
namespace concat
namespace conv2d
namespace fc
namespace instancenorm
namespace pool2d
Data Structures
class Buffer
Interface for writable data area.
class ExecEnv
Class to gather interpreter execution environment Each interpreter instance own execution environment.
class ExternalBuffer
Class for data area from outside.
class InternalBuffer
Class for internally allocated data area.
class InterpExecutor
Class to execute model using interpreter.
class Interpreter
Class for interpretation.
class ITensor
Interface to handle Tensor in interpreter.
class OperationExecutor
struct OpKernel
class ROTensor
Class to handle tensor in interpreter as read-only.
class Tensor
Class to handle tensor in interpreter as writable.
Functions
OpKernel * getBinaryArithmetic ()
OpKernel * getConcat ()
OpKernel * getConv2D ()
OpKernel * getDepthwiseConv2D ()
OpKernel * getElementwiseActivation ()
OpKernel * getFullyConnected ()
OpKernel * getGather ()
OpKernel * getInstanceNorm ()
nnfw::cker::Shape convertShape (const ir::Shape &shape)
nnfw::cker::Shape convertExtendShape (const ir::Shape &shape)
nnfw::cker::FusedActivationFunctionType convertActivationType (const ir::Activation activation)
template<typename T >
void calculateActivationRange (ir::Activation activation, T *activation_min, T *activation_max)
ir::Shape calcBroadcastShape (const ir::Shape &lhs, const ir::Shape &rhs, bool &success)
nnfw::cker::PaddingType convertPaddingType (ir::PaddingType ir_padding_type)
OpKernel * getPad ()
OpKernel * getPool2D ()
OpKernel * getReshape ()
OpKernel * getSoftmax ()
OpKernel * getTransposeConv ()
Function Documentation
calcBroadcastShape()
ir::Shape onert::interp::calcBroadcastShape (const ir::Shape & lhs, const ir::Shape & rhs, bool & success) inline
Definition at line 117 of file OperationUtil.h.
{
  int lhs_rank = lhs.rank();
  int rhs_rank = rhs.rank();
  int out_rank = (lhs_rank > rhs_rank ? lhs_rank : rhs_rank);
  ir::Shape out_shape(out_rank);
  int lhs_idim = lhs_rank - 1;
  int rhs_idim = rhs_rank - 1;
  success = true;
  for (int out_idim = out_rank - 1; out_idim >= 0; out_idim--)
  {
    if (lhs_idim == -1 && rhs_idim == -1)
    {
      // invalid result
      success = false;
      break;
    }
    if (lhs_idim == -1)
    {
      out_shape.dim(out_idim) = rhs.dim(rhs_idim);
      rhs_idim--;
    }
    else if (rhs_idim == -1)
    {
      out_shape.dim(out_idim) = lhs.dim(lhs_idim);
      lhs_idim--;
    }
    else
    {
      if (lhs.dim(lhs_idim) == rhs.dim(rhs_idim))
      {
        out_shape.dim(out_idim) = lhs.dim(lhs_idim);
        lhs_idim--;
        rhs_idim--;
      }
      else if (lhs.dim(lhs_idim) == 1)
      {
        out_shape.dim(out_idim) = rhs.dim(rhs_idim);
        lhs_idim--;
        rhs_idim--;
      }
      else if (rhs.dim(rhs_idim) == 1)
      {
        out_shape.dim(out_idim) = lhs.dim(lhs_idim);
        lhs_idim--;
        rhs_idim--;
      }
      else
      {
        // invalid result
        success = false;
        break;
      }
    }
  }
  if (lhs_idim != -1 || rhs_idim != -1)
  {
    // invalid result
    success = false;
  }
  return out_shape;
}
calculateActivationRange()
template<typename T > void onert::interp::calculateActivationRange (ir::Activation activation, T * activation_min, T * activation_max)
Definition at line 89 of file OperationUtil.h.
{
  if (activation == ir::Activation::RELU)
  {
    *activation_min = 0;
    *activation_max = std::numeric_limits<T>::max();
  }
  else if (activation == ir::Activation::RELU6)
  {
    *activation_min = 0;
    *activation_max = 6;
  }
  else if (activation == ir::Activation::RELU1)
  {
    *activation_min = -1;
    *activation_max = 1;
  }
  else if (activation == ir::Activation::NONE)
  {
    *activation_min = std::numeric_limits<T>::lowest();
    *activation_max = std::numeric_limits<T>::max();
  }
  else
  {
    throw std::runtime_error{"Unsupported activation type"};
  }
}
References onert::ir::NONE, onert::ir::RELU, onert::ir::RELU1, and onert::ir::RELU6.
Referenced by onert::interp::conv2d::invoke(), onert::interp::instancenorm::invoke(), and onert::interp::pool2d::invokePool2DOps().
convertActivationType()
nnfw::cker::FusedActivationFunctionType onert::interp::convertActivationType (const ir::Activation activation) inline
Definition at line 71 of file OperationUtil.h.
{
  switch (activation)
  {
    case ir::Activation::NONE:
      return nnfw::cker::FusedActivationFunctionType::kNone;
    case ir::Activation::RELU:
      return nnfw::cker::FusedActivationFunctionType::kRelu;
    case ir::Activation::RELU1:
      return nnfw::cker::FusedActivationFunctionType::kRelu1;
    case ir::Activation::RELU6:
      return nnfw::cker::FusedActivationFunctionType::kRelu6;
    default:
      throw std::runtime_error{"CPU backend: Cannot convert activation type"};
  }
}
References nnfw::cker::kNone, nnfw::cker::kRelu, nnfw::cker::kRelu1, nnfw::cker::kRelu6, onert::ir::NONE, onert::ir::RELU, onert::ir::RELU1, and onert::ir::RELU6.
Referenced by onert::interp::fc::invoke().
convertExtendShape()
nnfw::cker::Shape onert::interp::convertExtendShape (const ir::Shape & shape) inline
Definition at line 47 of file OperationUtil.h.
{
  auto dimensions = std::vector<uint32_t>(shape.dims().begin(), shape.dims().end());
  const int32_t extended_rank = 4;
  int32_t raw_shape[extended_rank];
  uint32_t start = extended_rank - dimensions.size();
  for (uint32_t i = 0; i < extended_rank; ++i)
  {
    if (i < start)
    {
      raw_shape[i] = 1;
    }
    else
    {
      raw_shape[i] = dimensions[i - start];
    }
  }
  return nnfw::cker::Shape(extended_rank, raw_shape);
}
convertPaddingType()
nnfw::cker::PaddingType onert::interp::convertPaddingType (ir::PaddingType ir_padding_type) inline
Definition at line 184 of file OperationUtil.h.
{
  switch (ir_padding_type)
  {
    case ir::PaddingType::EXPLICIT:
      return nnfw::cker::PaddingType::kNone;
    case ir::PaddingType::SAME:
      return nnfw::cker::PaddingType::kSame;
    case ir::PaddingType::VALID:
      return nnfw::cker::PaddingType::kValid;
    default:
      throw std::runtime_error("Wrong padding type.");
      break;
  }
}
References onert::ir::EXPLICIT, nnfw::cker::kNone, nnfw::cker::kSame, nnfw::cker::kValid, onert::ir::SAME, and onert::ir::VALID.
Referenced by onert::interp::conv2d::invoke().
convertShape()
nnfw::cker::Shape onert::interp::convertShape (const ir::Shape & shape) inline
Definition at line 32 of file OperationUtil.h.
{
  auto dimensions = std::vector<uint32_t>(shape.dims().begin(), shape.dims().end());
  std::vector<int32_t> raw_shape;
  raw_shape.resize(dimensions.size());
  for (uint32_t i = 0; i < dimensions.size(); ++i)
  {
    raw_shape[i] = dimensions[i];
  }
  return nnfw::cker::GetShape(raw_shape);
}
References nnfw::cker::GetShape().
Referenced by onert::interp::conv2d::invoke(), onert::interp::fc::invoke(), onert::interp::instancenorm::invoke(), onert::interp::concat::invoke(), and onert::interp::pool2d::invokePool2DOps().
getBinaryArithmetic()
OpKernel * onert::interp::getBinaryArithmetic ()
Definition at line 197 of file BinaryArithmeticOps.cc.
{
  static OpKernel kernel = {prepare, invokeBinaryArithmeticOps};
  return &kernel;
}
getConcat()
OpKernel * onert::interp::getConcat ()
Definition at line 140 of file Concat.cc.
{
  static OpKernel kernel = {concat::prepareConcat, concat::invokeConcat};
  return &kernel;
}
References onert::interp::concat::invokeConcat(), and onert::interp::concat::prepareConcat().
getConv2D()
OpKernel * onert::interp::getConv2D ()
Definition at line 144 of file Conv2D.cc.
{
  static OpKernel kernel = {conv2d::prepareConv2D, conv2d::invokeConv2D};
  return &kernel;
}
References onert::interp::conv2d::invokeConv2D(), and onert::interp::conv2d::prepareConv2D().
getDepthwiseConv2D()
OpKernel * onert::interp::getDepthwiseConv2D ()
Definition at line 149 of file DepthwiseConv2D.cc.
{
  static OpKernel kernel = {prepareDepthwiseConv, invokeDepthwiseConv};
  return &kernel;
}
getElementwiseActivation()
OpKernel * onert::interp::getElementwiseActivation ()
Definition at line 153 of file ElementwiseActivations.cc.
{
  static OpKernel kernel = {prepare, invokeElementwiseActivation};
  return &kernel;
}
getFullyConnected()
OpKernel * onert::interp::getFullyConnected ()
Definition at line 127 of file FullyConnected.cc.
{
  static OpKernel kernel = {fc::prepareFC, fc::invokeFC};
  return &kernel;
}
References onert::interp::fc::invokeFC(), and onert::interp::fc::prepareFC().
getGather()
OpKernel * onert::interp::getGather ()
Definition at line 131 of file Gather.cc.
{
  static OpKernel kernel = {prepareGather, invokeGather};
  return &kernel;
}
getInstanceNorm()
OpKernel * onert::interp::getInstanceNorm ()
Definition at line 114 of file InstanceNorm.cc.
{
  static OpKernel kernel = {instancenorm::prepareInstanceNorm, instancenorm::invokeInstanceNorm};
  return &kernel;
}
References onert::interp::instancenorm::invokeInstanceNorm(), and onert::interp::instancenorm::prepareInstanceNorm().
getPad()
OpKernel * onert::interp::getPad ()
Definition at line 99 of file Pad.cc.
{
  static OpKernel kernel = {preparePad, invokePad};
  return &kernel;
}
getPool2D()
OpKernel * onert::interp::getPool2D ()
Definition at line 133 of file Pool2D.cc.
{
  static OpKernel kernel = {pool2d::preparePool2D, pool2d::invokePool2DOps};
  return &kernel;
}
References onert::interp::pool2d::invokePool2DOps(), and onert::interp::pool2d::preparePool2D().
getReshape()
OpKernel * onert::interp::getReshape ()
Definition at line 56 of file Reshape.cc.
{
  static OpKernel kernel = {prepare, invoke};
  return &kernel;
}
getSoftmax()
OpKernel * onert::interp::getSoftmax ()
Definition at line 116 of file Softmax.cc.
{
  static OpKernel kernel = {prepareSoftMax, invokeSoftMax};
  return &kernel;
}
getTransposeConv()
OpKernel * onert::interp::getTransposeConv ()
Definition at line 134 of file TransposeConv.cc.
{
  static OpKernel kernel = {prepareTransposeConv, invokeTransposeConv};
  return &kernel;
}