ONE - On-device Neural Engine: onert::exec::train::optimizer Namespace Reference
onert::exec::train::optimizer Namespace Reference
Data Structures
class Optimizer
Base class for all optimizers.
class SGD
SGD optimizer.
Typedefs
using UpdateFactors = std::tuple< const backend::IPortableTensor &, backend::train::ITrainableTensor &, size_t >
Enumerations
enum class OptimizerCode { Invalid , SGD , Adam }
Functions
std::string toString (OptimizerCode opcode)
Convert the optimizer code to the name.
template<typename T , typename L >
void elementwise (const ir::Shape &shape, const backend::ITensor &src, backend::ITensor &dst, const L &f)
Typedef Documentation
UpdateFactors
using onert::exec::train::optimizer::UpdateFactors = typedef std::tuple<const backend::IPortableTensor &, backend::train::ITrainableTensor &, size_t>
Definition at line 35 of file Optimizer.h.
Enumeration Type Documentation
OptimizerCode
enum class onert::exec::train::optimizer::OptimizerCode strong
Enumerator
Invalid
SGD
Adam
Definition at line 33 of file OptimizerCode.h.
{
  Invalid, //< Invalid
  SGD,     //< SGD optimizer
  Adam     //< Adam optimizer
};
Function Documentation
elementwise()
template<typename T , typename L > void onert::exec::train::optimizer::elementwise (const ir::Shape & shape, const backend::ITensor & src, backend::ITensor & dst, const L & f)
Definition at line 32 of file OptimizerHelpers.h.
{
  ShapeLoop(shape, [&](const ir::Coordinates &coords) {
    const T src_val = *reinterpret_cast<const T *>(src.buffer() + src.calcOffset(coords));
    T *dst_data = reinterpret_cast<T *>(dst.buffer() + dst.calcOffset(coords));
    *dst_data = f(src_val, *dst_data);
  });
}
References onert::backend::ITensor::buffer(), onert::backend::ITensor::calcOffset(), coords, and ShapeLoop().
toString()
std::string onert::exec::train::optimizer::toString (OptimizerCode opcode)
Convert the optimizer code to the name.
Parameters
opcode The optimizer code
Returns
The name of the optimizer
Definition at line 30 of file OptimizerCode.cc.
{
  static const std::unordered_map<OptimizerCode, const char *> map{
    {OptimizerCode::Invalid, "Invalid"},
    {OptimizerCode::SGD, "SGD"},
    {OptimizerCode::Adam, "Adam"}};
  return map.at(code);
}
References Adam, Invalid, and SGD.
Referenced by onert::compiler::train::TrainingCompiler::compile().