ONE - On-device Neural Engine: onert::backend::gpu_cl Namespace Reference
onert::backend::gpu_cl Namespace Reference
Namespaces
namespace operand
Data Structures
class Backend
class BackendContext
class ClConstantInitializer
class ClFunction
class Config
class ConstantInitializer
class KernelGenerator
class MemoryManager
class TensorBuilder
class TensorManager
class TensorRegistry
Tensor registry class for gpu-cl backends.
Typedefs
using float16 = uint16_t
using UsesType = cl_common::UsesType
Enumerations
enum TensorType { TENSOR_TYPE_VALID = 0 , TENSOR_TYPE_INPUT = 1 , TENSOR_TYPE_OUTPUT = 2 , TENSOR_TYPE_DELETE = 3 }
Functions
template<typename T >
void copyInit (const onert::ir::Operand &model_obj, onert::backend::ITensor &obj)
template<typename T >
void permuteInit (const onert::ir::Operand &model_obj, onert::backend::ITensor &obj, const onert::ir::Layout frontend_layout)
TensorManager * createTensorManager (tflite::gpu::cl::CLContext *context, tflite::gpu::CreateGpuModelInfo create_info, const std::shared_ptr< tflite::gpu::cl::Environment > &environment)
tflite::gpu::HW ToHW (int32_t h, int32_t w)
template<typename AttrT >
void UpdatePadding (const ir::PaddingType type, const tflite::gpu::BHWC &input_shape, AttrT *attr)
tflite::gpu::PoolingType convertPoolType (ir::operation::Pool2D::PoolType type_ir)
tflite::gpu::BHWC ToBHWC (ir::Shape shape)
bool CheckIfLinearConvertible (const ir::Shape *shape)
tflite::gpu::OperationType convertArithmeticType (ir::operation::BinaryArithmetic::ArithmeticType arithmetic_type_ir)
tflite::gpu::OperationType convertElementwiseActivationType (ir::operation::ElementwiseActivation::Type type_ir)
Typedef Documentation
float16
using onert::backend::gpu_cl::float16 = typedef uint16_t
Definition at line 55 of file ClConstantInitializer.cc.
UsesType
using onert::backend::gpu_cl::UsesType = typedef cl_common::UsesType
Definition at line 45 of file TensorBuilder.cc.
Enumeration Type Documentation
TensorType
enum onert::backend::gpu_cl::TensorType
Enumerator
TENSOR_TYPE_VALID
TENSOR_TYPE_INPUT
TENSOR_TYPE_OUTPUT
TENSOR_TYPE_DELETE
Definition at line 143 of file Utils.h.
{
  TENSOR_TYPE_VALID = 0,
  TENSOR_TYPE_INPUT = 1,
  TENSOR_TYPE_OUTPUT = 2,
  TENSOR_TYPE_DELETE = 3
};
Function Documentation
CheckIfLinearConvertible()
bool onert::backend::gpu_cl::CheckIfLinearConvertible (const ir::Shape * shape) inline
Definition at line 97 of file Utils.h.
{
  if (shape->num_elements() <= 0)
  {
    return false;
  }
  for (int i = 0; i < shape->rank() - 1; ++i)
  {
    if (shape->dim(i) != 1)
    {
      return false;
    }
  }
  return true;
}
convertArithmeticType()
tflite::gpu::OperationType onert::backend::gpu_cl::convertArithmeticType (ir::operation::BinaryArithmetic::ArithmeticType arithmetic_type_ir) inline
Definition at line 114 of file Utils.h.
{
  switch (arithmetic_type_ir)
  {
    case ir::operation::BinaryArithmetic::ArithmeticType::ADD:
      return tflite::gpu::OperationType::ADD;
    case ir::operation::BinaryArithmetic::ArithmeticType::SUB:
      return tflite::gpu::OperationType::SUB;
    case ir::operation::BinaryArithmetic::ArithmeticType::MUL:
      return tflite::gpu::OperationType::MUL;
    case ir::operation::BinaryArithmetic::ArithmeticType::DIV:
      return tflite::gpu::OperationType::DIV;
    default:
      throw std::runtime_error("Unsupported ArithmeticType");
  }
}
References onert::ir::operation::BinaryArithmetic::ADD, onert::ir::operation::BinaryArithmetic::DIV, onert::ir::operation::BinaryArithmetic::MUL, and onert::ir::operation::BinaryArithmetic::SUB.
convertElementwiseActivationType()
tflite::gpu::OperationType onert::backend::gpu_cl::convertElementwiseActivationType (ir::operation::ElementwiseActivation::Type type_ir) inline
Definition at line 132 of file Utils.h.
{
  switch (type_ir)
  {
    case ir::operation::ElementwiseActivation::Type::LOGISTIC:
      return tflite::gpu::OperationType::SIGMOID;
    default:
      throw std::runtime_error("Unsupported ElementwiseActivationType");
  }
}
References onert::ir::operation::ElementwiseActivation::LOGISTIC.
convertPoolType()
tflite::gpu::PoolingType onert::backend::gpu_cl::convertPoolType (ir::operation::Pool2D::PoolType type_ir) inline
Definition at line 58 of file Utils.h.
{
  switch (type_ir)
  {
    case ir::operation::Pool2D::PoolType::AVG:
      return tflite::gpu::PoolingType::AVERAGE;
    case ir::operation::Pool2D::PoolType::MAX:
      return tflite::gpu::PoolingType::MAX;
    default:
      throw std::runtime_error("gpu_Cl KernelGenerator : Not supported operation yet");
  }
}
References onert::ir::operation::Pool2D::AVG, and onert::ir::operation::Pool2D::MAX.
copyInit()
template<typename T > void onert::backend::gpu_cl::copyInit (const onert::ir::Operand & model_obj, onert::backend::ITensor & obj)
Definition at line 70 of file ClConstantInitializer.h.
{
  Init<T>(model_obj, obj, true);
}
createTensorManager()
TensorManager * onert::backend::gpu_cl::createTensorManager (tflite::gpu::cl::CLContext * context, tflite::gpu::CreateGpuModelInfo create_info, const std::shared_ptr< tflite::gpu::cl::Environment > & environment) inline
Definition at line 73 of file TensorManager.h.
{
  VERBOSE(createTensorManager) << "GPU-CL TensorManager" << std::endl;
  return new TensorManager(new MemoryManager(context, create_info, environment),
                           new MemoryManager(context, create_info, environment));
}
References createTensorManager(), and VERBOSE.
Referenced by createTensorManager(), and onert::backend::gpu_cl::Backend::newContext().
permuteInit()
template<typename T > void onert::backend::gpu_cl::permuteInit (const onert::ir::Operand & model_obj, onert::backend::ITensor & obj, const onert::ir::Layout frontend_layout)
Definition at line 76 of file ClConstantInitializer.h.
{
  const bool copy = frontend_layout == obj.layout();
  Init<T>(model_obj, obj, copy, frontend_layout);
}
ToBHWC()
tflite::gpu::BHWC onert::backend::gpu_cl::ToBHWC (ir::Shape shape) inline
Definition at line 71 of file Utils.h.
{
  switch (shape.rank())
  {
    case 1:
      // B layout
      return tflite::gpu::BHWC(shape.dim(0), 1, 1, 1);
      break;
    case 2:
      // BC layout
      return tflite::gpu::BHWC(shape.dim(0), 1, 1, shape.dim(1));
      break;
    case 3:
      // BWC layout
      return tflite::gpu::BHWC(shape.dim(0), 1, shape.dim(1), shape.dim(2));
      break;
    case 4:
      // BHWC layout
      return tflite::gpu::BHWC(shape.dim(0), shape.dim(1), shape.dim(2), shape.dim(3));
      break;
    default:
      break;
  }
  return tflite::gpu::BHWC();
}
Referenced by onert::backend::gpu_cl::MemoryManager::addTensor(), and onert::backend::gpu_cl::MemoryManager::buildTensor().
ToHW()
tflite::gpu::HW onert::backend::gpu_cl::ToHW (int32_t h, int32_t w) inline
Definition at line 38 of file Utils.h.
{
  return tflite::gpu::HW(h > 0 ? h : 1, w > 0 ? w : 1);
}
UpdatePadding()
template<typename AttrT > void onert::backend::gpu_cl::UpdatePadding (const ir::PaddingType type, const tflite::gpu::BHWC & input_shape, AttrT * attr) inline
Definition at line 44 of file Utils.h.
{
  if (type == ir::PaddingType::SAME)
  {
    attr->padding = CalculateSamePadding(input_shape, *attr);
  }
  else
  {
    attr->padding.prepended = tflite::gpu::HW(0, 0);
    attr->padding.appended = tflite::gpu::HW(0, 0);
  }
}
References onert::ir::SAME.