ONE - On-device Neural Engine: arm_compute Namespace Reference
arm_compute Namespace Reference
Namespaces
namespace misc
namespace weights_transformations
Data Structures
class CLArgMinMaxLayerEx
class CLArgMinMaxLayerKernelEx
class CLBinaryLogicalOp
class CLBinaryLogicalOpKernel
class CLCastBool
Class to run CLCastBoolKernel. This converts the boolean input tensor to the output tensor's type.
class CLCastBoolKernel
Class for the kernel converting boolean type.
class CLDirectTransposeConvLayer
class CLEmbeddingLookup
Class to perform EmbeddingLookup operation.
class CLEmbeddingLookupKernel
Class to perform EmbeddingLookup operation with opencl kernel.
class CLFullyConnectedHybridLayer
class CLFullyConnectedHybridLayerReshapeWeights
class CLFullyConnectedLayerEx
class CLFullyConnectedLayerReshapeWeightsEx
class CLFullyConnectedReshapingLayer
Class to run FullyConnected Layer after reshaping input tensor.
class CLGatherEx
Class to to run CLGatherKernel.
class CLGatherExKernel
Class to define an interface for the gather kernel.
class CLGEMMMatrixAccumulateBiasesKernel
class CLHashtableLookup
Class to perform HashtableLookup operation.
class CLHashtableLookupKernel
Class to perform HashtableLookup operation with opencl kernel.
class CLInstanceNormalizationLayerEx
class CLInstanceNormalizationLayerKernelEx
class CLKernelLibraryEx
Class to build OpenCL kernels added from nnfw.
class CLMemsetKernel
class CLMultiplyScaleFactorKernel
class CLNeg
class CLNegKernel
class CLOneHot
class CLOneHotKernel
class CLPadLayerEx
class CLPadLayerKernelEx
class CLQuantizationSymmetricKernel
class CLReduceOperation
Class to perform ReduceOperation.
class CLReduceOperationKernel
Class to define interface for the reduce operation kernel.
class CLScaleFactorSymm8Kernel
class CLSplitVEx
class CLTopKV2
Class to execute TopKV2 operation.
class CLTransposeConvLayer
class NEBinaryLogicalOperation
class NEBinaryLogicalOperationKernel
class NEBinaryLogicalOperationStatic
class NECastBool
Class to run INESimpleFunctionNoBorder.
class NECastBoolKernel
Class for the kernel converting boolean type.
class NEEmbeddingLookup
Class to perform EmbeddingLookup operation.
class NEEmbeddingLookupKernel
class NEFullyConnectedHybridLayer
class NEFullyConnectedHybridLayerReshapeWeights
class NEFullyConnectedLayerEx
class NEFullyConnectedReshapingLayer
Class to run FullyConnected Layer after reshaping input tensor.
class NEGatherEx
class NEGatherKernelEx
class NEGEMMMatrixAccumulateBiasesKernel
class NEHashtableLookup
Class to perform HashtableLookup operation.
class NEHashtableLookupKernel
class NEInstanceNormalizationLayerEx
class NEInstanceNormalizationLayerKernelEx
class NEMultiplyScaleFactorKernel
class NEOneHot
class NEOneHotKernel
class NEQuantizationSymmetricKernel
class NEReduceOperation
class NEReduceSum
class NETransposeConvLayer
Typedefs
using NELogicalAnd = NEBinaryLogicalOperationStatic< BinaryLogicalOperation::AND >
using NELogicalOr = NEBinaryLogicalOperationStatic< BinaryLogicalOperation::OR >
Enumerations
enum class ArgOperation { MAX , MIN }
enum class BinaryLogicalOperation { AND , OR }
enum class ComparisonOperationEx { EQUAL , NOT_EQUAL }
enum class ElementWiseUnaryEx { NEG }
enum class SubDataType { NONE , BOOL }
Functions
void elementwise_op (const ITensor *in1, const ITensor *in2, ITensor *out, const Window &window, float(*scalar_func)(const float &, const float &), int(*broadcast_func)(int, int, int, const float *, const float &, float *, const bool), int(*neon_func)(int, int, int, const float *, const float *, float *))
void elementwise_op (const ITensor *in1, const ITensor *in2, ITensor *out, const Window &window, uint8_t(*scalar_func)(const uint8_t &, const uint8_t &), int(*broadcast_func)(int, int, int, const uint8_t *, const uint8_t &, uint8_t *, const bool), int(*neon_func)(int, int, int, const uint8_t *, const uint8_t *, uint8_t *))
const std::pair< unsigned int, unsigned int > transposeconv_output_dimensions (unsigned int in_width, unsigned int in_height, unsigned int kernel_width, unsigned int kernel_height, const PadStrideInfo &info, unsigned int invalid_right, unsigned int invalid_top)
template<BinaryLogicalOperation op, typename ScalarType >
ScalarType elementwise_logic_op_scalar (const ScalarType &a, const ScalarType &b)
template<BinaryLogicalOperation op, typename VectorType >
VectorType elementwise_logic_op (const VectorType &a, const VectorType &b)
template<BinaryLogicalOperation op>
uint8x16x4_t elementwise_logic_op (const uint8x16x4_t &a, const uint8x16x4_t &b)
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType >
VectorType elementwise_logic_op_broadcast (const VectorType &a, const ScalarType &broadcast_value, const bool reorder)
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType >
int elementwise_logic_op_loop (int window_start_x, int window_end_x, int window_step_x, const ScalarType *input1_ptr, const ScalarType *input2_ptr, ScalarType *output_ptr)
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType >
int elementwise_logic_op_broadcast_loop (int window_start_x, int window_end_x, int window_step_x, const ScalarType *non_broadcast_input_ptr, const ScalarType &broadcast_value, ScalarType *output_ptr, const bool reorder)
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType >
void elementwise_logic_op (const ITensor *in1, const ITensor *in2, ITensor *out, const Window &window)
std::function< void(const ITensor *, const ITensor *, ITensor *, const Window &)> configure_func (const ITensor *input1, const ITensor *input2, ITensor *output, std::map< std::string, cpu::kernels::CpuElementwiseKernel::ElementwiseFunction * > map_function)
template<BinaryLogicalOperation op>
std::function< void(const ITensor *, const ITensor *, ITensor *, const Window &)> configure_logic_func (const ITensor *input1, const ITensor *input2, ITensor *output)
Typedef Documentation
NELogicalAnd
using arm_compute::NELogicalAnd = typedef NEBinaryLogicalOperationStatic<BinaryLogicalOperation::AND>
Basic function to run equal comparison.
Definition at line 112 of file NEBinaryLogicalOperation.h.
NELogicalOr
using arm_compute::NELogicalOr = typedef NEBinaryLogicalOperationStatic<BinaryLogicalOperation::OR>
Basic function to run not equal comparison.
Definition at line 114 of file NEBinaryLogicalOperation.h.
Enumeration Type Documentation
ArgOperation
enum class arm_compute::ArgOperation strong
Available ArgIndex operations
Enumerator
MAX
MIN
Definition at line 48 of file TypesEx.h.
{
  MAX,
  MIN,
};
BinaryLogicalOperation
enum class arm_compute::BinaryLogicalOperation strong
Available binary logical operations
Enumerator
AND
AND
OR
OR
Definition at line 55 of file TypesEx.h.
{
  AND,
  OR,
};
ComparisonOperationEx
enum class arm_compute::ComparisonOperationEx strong
Enumerator
EQUAL
EQUAL
NOT_EQUAL
NOT_EQUAL
Definition at line 61 of file TypesEx.h.
{
  EQUAL,
  NOT_EQUAL,
};
ElementWiseUnaryEx
enum class arm_compute::ElementWiseUnaryEx strong
Enumerator
NEG
NEG
Definition at line 67 of file TypesEx.h.
{
  NEG,
};
SubDataType
enum class arm_compute::SubDataType strong
Enumerator
NONE
BOOL
Definition at line 72 of file TypesEx.h.
{
  NONE,
  BOOL,
};
Function Documentation
configure_func()
std::function< void(const ITensor *, const ITensor *, ITensor *, const Window &)> arm_compute::configure_func (const ITensor * input1, const ITensor * input2, ITensor * output, std::map< std::string, cpu::kernels::CpuElementwiseKernel::ElementwiseFunction * > map_function)
Definition at line 164 of file NEBinaryLogicalOperationKernel.cpp.
{
  std::string function_to_call("op_");
  function_to_call += string_from_data_type(input1->info()->data_type()) + "_";
  function_to_call += string_from_data_type(input2->info()->data_type()) + "_";
  function_to_call += string_from_data_type(output->info()->data_type());
  auto it = map_function.find(function_to_call);
  if (it != map_function.end())
  {
    auto func = it->second;
    return [func](const ITensor *input1, const ITensor *input2, ITensor *output,
                  const Window &window) { func(input1, input2, output, window); };
  }
  return nullptr;
}
Referenced by configure_logic_func().
configure_logic_func()
template<BinaryLogicalOperation op> std::function< void(const ITensor *, const ITensor *, ITensor *, const Window &)> arm_compute::configure_logic_func (const ITensor * input1, const ITensor * input2, ITensor * output)
Definition at line 186 of file NEBinaryLogicalOperationKernel.cpp.
{
  static std::map<std::string, cpu::kernels::CpuElementwiseKernel::ElementwiseFunction *>
    map_function = {{"op_U8_U8_U8", &elementwise_logic_op<op, uint8_t, uint8x16_t>},
                    {"op_QASYMM8_QASYMM8_QASYMM8", &elementwise_logic_op<op, uint8_t, uint8x16_t>}};
  return configure_func(input1, input2, output, map_function);
}
References configure_func().
elementwise_logic_op() [1/3]
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType > void arm_compute::elementwise_logic_op (const ITensor * in1, const ITensor * in2, ITensor * out, const Window & window)
Definition at line 156 of file NEBinaryLogicalOperationKernel.cpp.
{
  elementwise_op(in1, in2, out, window, &elementwise_logic_op_scalar<op, ScalarType>,
                 &elementwise_logic_op_broadcast_loop<op, ScalarType, VectorType>,
                 &elementwise_logic_op_loop<op, ScalarType, VectorType>);
}
References elementwise_op().
elementwise_logic_op() [2/3]
template<BinaryLogicalOperation op> uint8x16x4_t arm_compute::elementwise_logic_op (const uint8x16x4_t & a, const uint8x16x4_t & b) inline
Definition at line 103 of file NEBinaryLogicalOperationKernel.cpp.
{
  uint8x16x4_t out = {{
    elementwise_logic_op<op>(a.val[0], b.val[0]),
    elementwise_logic_op<op>(a.val[1], b.val[1]),
    elementwise_logic_op<op>(a.val[2], b.val[2]),
    elementwise_logic_op<op>(a.val[3], b.val[3]),
  }};
  return out;
}
elementwise_logic_op() [3/3]
template<BinaryLogicalOperation op, typename VectorType > VectorType arm_compute::elementwise_logic_op (const VectorType & a, const VectorType & b) inline
Definition at line 84 of file NEBinaryLogicalOperationKernel.cpp.
{
  VectorType res = {0, 0, 0, 0};
  switch (op)
  {
    case BinaryLogicalOperation::AND:
      res = wrapper::vand(a, b);
      break;
    case BinaryLogicalOperation::OR:
      res = wrapper::vorr(a, b);
      break;
    default:
      ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
  }
  return res;
}
References AND, and OR.
elementwise_logic_op_broadcast()
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType > VectorType arm_compute::elementwise_logic_op_broadcast (const VectorType & a, const ScalarType & broadcast_value, const bool reorder) inline
Definition at line 115 of file NEBinaryLogicalOperationKernel.cpp.
{
  VectorType broadcast_vector = wrapper::vdup_n(broadcast_value, wrapper::traits::vector_128_tag());
  return elementwise_logic_op<op>(reorder ? broadcast_vector : a, reorder ? a : broadcast_vector);
}
elementwise_logic_op_broadcast_loop()
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType > int arm_compute::elementwise_logic_op_broadcast_loop (int window_start_x, int window_end_x, int window_step_x, const ScalarType * non_broadcast_input_ptr, const ScalarType & broadcast_value, ScalarType * output_ptr, const bool reorder) inline
Definition at line 139 of file NEBinaryLogicalOperationKernel.cpp.
{
  int x = window_start_x;
  for (; x <= (window_end_x - window_step_x); x += window_step_x)
  {
    const auto a = wrapper::vloadq((non_broadcast_input_ptr + x));
    wrapper::vstore(output_ptr + x,
                    elementwise_logic_op_broadcast<op>(a, broadcast_value, reorder));
  }
  return x;
}
elementwise_logic_op_loop()
template<BinaryLogicalOperation op, typename ScalarType , typename VectorType > int arm_compute::elementwise_logic_op_loop (int window_start_x, int window_end_x, int window_step_x, const ScalarType * input1_ptr, const ScalarType * input2_ptr, ScalarType * output_ptr) inline
Definition at line 124 of file NEBinaryLogicalOperationKernel.cpp.
{
  int x = window_start_x;
  for (; x <= (window_end_x - window_step_x); x += window_step_x)
  {
    const auto a = wrapper::vloadq(input1_ptr + x);
    const auto b = wrapper::vloadq(input2_ptr + x);
    wrapper::vstore(output_ptr + x, elementwise_logic_op<op>(a, b));
  }
  return x;
}
elementwise_logic_op_scalar()
template<BinaryLogicalOperation op, typename ScalarType > ScalarType arm_compute::elementwise_logic_op_scalar (const ScalarType & a, const ScalarType & b) inline
Definition at line 65 of file NEBinaryLogicalOperationKernel.cpp.
{
  auto res = ScalarType(0);
  switch (op)
  {
    case BinaryLogicalOperation::AND:
      res = a & b;
      break;
    case BinaryLogicalOperation::OR:
      res = a | b;
      break;
    default:
      ARM_COMPUTE_ERROR("NOT_SUPPORTED!");
  }
  return res;
}
References AND, and OR.
elementwise_op() [1/2]
void arm_compute::elementwise_op (const ITensor * in1, const ITensor * in2, ITensor * out, const Window & window, float(*)(const float &, const float &) scalar_func, int(*)(int, int, int, const float *, const float &, float *, const bool) broadcast_func, int(*)(int, int, int, const float *, const float *, float *) neon_func)
Definition at line 147 of file NEElementwiseOperationFuncs.cpp.
{
  elementwise_op_templ<float, float, float32x4_t>(in1, in2, out, window, scalar_func,
                                                  broadcast_func, neon_func);
}
Referenced by elementwise_logic_op().
elementwise_op() [2/2]
void arm_compute::elementwise_op (const ITensor * in1, const ITensor * in2, ITensor * out, const Window & window, uint8_t(*)(const uint8_t &, const uint8_t &) scalar_func, int(*)(int, int, int, const uint8_t *, const uint8_t &, uint8_t *, const bool) broadcast_func, int(*)(int, int, int, const uint8_t *, const uint8_t *, uint8_t *) neon_func)
Definition at line 157 of file NEElementwiseOperationFuncs.cpp.
{
  elementwise_op_templ<uint8_t, uint8_t, uint8x16_t>(in1, in2, out, window, scalar_func,
                                                     broadcast_func, neon_func);
}
transposeconv_output_dimensions()
const std::pair< unsigned int, unsigned int > arm_compute::transposeconv_output_dimensions (unsigned int in_width, unsigned int in_height, unsigned int kernel_width, unsigned int kernel_height, const PadStrideInfo & info, unsigned int invalid_right, unsigned int invalid_top)
Returns expected width and height of the transpose convolution's output tensor.
Note
This function was copied in order to fix a bug computing to wrong output dimensions.
Parameters
[in] in_width Width of input tensor (Number of columns)
[in] in_height Height of input tensor (Number of rows)
[in] kernel_width Kernel width.
[in] kernel_height Kernel height.
[in] info padding and stride info.
[in] invalid_right The number of zeros added to right edge of the output.
[in] invalid_top The number of zeros added to bottom edge of the output.
Returns
A pair with the new width in the first position and the new height in the second.
Definition at line 47 of file UtilsEx.cpp.
{
  const unsigned int stride_x = info.stride().first;
  const unsigned int stride_y = info.stride().second;
  const unsigned int padx = info.pad_left() + info.pad_right();
  const unsigned int pady = info.pad_top() + info.pad_bottom();
  ARM_COMPUTE_ERROR_ON(in_width < 1 || in_height < 1);
  ARM_COMPUTE_ERROR_ON(kernel_width <= padx);
  ARM_COMPUTE_ERROR_ON(kernel_height <= pady);
  // Find the transpose conv out dimensions
  // transpose conv out:
  //    tconv_out + pad = 1 + (in - 1) * stride + invalid
  //    tconv_out = 1 + (in - 1) * stride + invalid - pad
  const int w = stride_x * (in_width - 1) + kernel_width - padx + invalid_right;
  const int h = stride_y * (in_height - 1) + kernel_height - pady + invalid_bottom;
  return std::make_pair<unsigned int, unsigned int>(w, h);
}
References info.
Referenced by arm_compute::CLDirectTransposeConvLayer::configure(), arm_compute::NETransposeConvLayer::configure(), arm_compute::NETransposeConvLayer::validate(), and arm_compute::CLDirectTransposeConvLayer::validate().