ONE - On-device Neural Engine: morph::caffe Namespace Reference
morph::caffe Namespace Reference
Functions
nncc::core::ADT::tensor::Shape as_tensor_shape (const nncc::core::ADT::feature::Shape &)
nncc::core::ADT::tensor::Shape as_tensor_shape (const nncc::core::ADT::kernel::Shape &)
nncc::core::ADT::feature::Shape as_feature_shape (const nncc::core::ADT::tensor::Shape &)
nncc::core::ADT::kernel::Shape as_kernel_shape (const nncc::core::ADT::tensor::Shape &)
Function Documentation
as_feature_shape()
feature::Shape morph::caffe::as_feature_shape (const nncc::core::ADT::tensor::Shape & shape)
Definition at line 54 of file caffe.cpp.
{
  assert(shape.rank() == 4);
  assert(shape.dim(0) == 1);
  return feature::Shape{shape.dim(1), shape.dim(2), shape.dim(3)};
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::rank().
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and caffeimport::ScaleBuilder::build().
as_kernel_shape()
kernel::Shape morph::caffe::as_kernel_shape (const nncc::core::ADT::tensor::Shape & shape)
Definition at line 61 of file caffe.cpp.
{
  assert(shape.rank() == 4);
  return kernel::Shape{shape.dim(0), shape.dim(1), shape.dim(2), shape.dim(3)};
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::rank().
Referenced by caffeimport::ConvolutionBuilder::build().
as_tensor_shape() [1/2]
tensor::Shape morph::caffe::as_tensor_shape (const nncc::core::ADT::feature::Shape & shape)
Definition at line 28 of file caffe.cpp.
{
  tensor::Shape res;
  res.resize(4);
  res.dim(0) = 1;
  res.dim(1) = shape.depth();
  res.dim(2) = shape.height();
  res.dim(3) = shape.width();
  return res;
}
References nncc::core::ADT::feature::Shape::depth(), nncc::core::ADT::tensor::Shape::dim(), nncc::core::ADT::feature::Shape::height(), nncc::core::ADT::tensor::Shape::resize(), and nncc::core::ADT::feature::Shape::width().
as_tensor_shape() [2/2]
tensor::Shape morph::caffe::as_tensor_shape (const nncc::core::ADT::kernel::Shape & shape)
Definition at line 41 of file caffe.cpp.
{
  tensor::Shape res;
  res.resize(4);
  res.dim(0) = shape.count();
  res.dim(1) = shape.depth();
  res.dim(2) = shape.height();
  res.dim(3) = shape.width();
  return res;
}
References nncc::core::ADT::kernel::Shape::count(), nncc::core::ADT::kernel::Shape::depth(), nncc::core::ADT::tensor::Shape::dim(), nncc::core::ADT::kernel::Shape::height(), nncc::core::ADT::tensor::Shape::resize(), and nncc::core::ADT::kernel::Shape::width().