ONE - On-device Neural Engine: caffeimport Namespace Reference
caffeimport Namespace Reference
Data Structures
class BatchNormBuilder
class ConcatBuilder
class ConvolutionBuilder
class EltwiseBuilder
class GraphBuilder
class GraphBuilderContext
class GraphBuilderRegistry
class InputBuilder
class PoolingBuilder
class ReLUBuilder
class ScaleBuilder
class WeightContext
Typedefs
using LayerName = std::string
using BlobName = std::string
using ShapeContext = std::map< BlobName, nncc::core::ADT::tensor::Shape >
using StoreContext = std::map< BlobName, coco::Bag * >
Functions
tensor::Shape as_tensor_shape (const ::caffe::BlobShape &blob_shape)
nncc::core::ADT::tensor::Shape as_tensor_shape (const ::caffe::BlobProto *blob_proto)
Typedef Documentation
BlobName
using caffeimport::BlobName = typedef std::string
Definition at line 33 of file Context.h.
LayerName
using caffeimport::LayerName = typedef std::string
Definition at line 32 of file Context.h.
ShapeContext
using caffeimport::ShapeContext = typedef std::map<BlobName, nncc::core::ADT::tensor::Shape>
Definition at line 35 of file Context.h.
StoreContext
using caffeimport::StoreContext = typedef std::map<BlobName, coco::Bag *>
Definition at line 36 of file Context.h.
Function Documentation
as_tensor_shape() [1/2]
nncc::core::ADT::tensor::Shape caffeimport::as_tensor_shape (const ::caffe::BlobProto * blob_proto) inline
Definition at line 29 of file Convert.h.
{
  return as_tensor_shape(blob_proto->shape());
}
References as_tensor_shape().
as_tensor_shape() [2/2]
nncc::core::ADT::tensor::Shape caffeimport::as_tensor_shape (const ::caffe::BlobShape & blob_shape)
Definition at line 24 of file Convert.cpp.
{
  const uint32_t rank = blob_shape.dim_size();
  tensor::Shape res;
  res.resize(rank);
  for (uint32_t axis = 0; axis < rank; ++axis)
  {
    res.dim(axis) = blob_shape.dim(axis);
  }
  return res;
}
References nncc::core::ADT::tensor::Shape::dim(), and nncc::core::ADT::tensor::Shape::resize().
Referenced by as_tensor_shape(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), and caffeimport::InputBuilder::build().