ONE - On-device Neural Engine: luci::compute Namespace Reference
luci::compute Namespace Reference
Data Structures
class DepthwiseConv2D
struct DepthwiseParams
class FullyConnected
struct FullyConnectedParams
struct PaddingValues
Enumerations
enum class PaddingType : uint8_t { kNone , kSame , kValid }
enum class FullyConnectedWeightsFormat : uint8_t { kDefault , kShuffled4x16Int8 }
enum class FusedActFunc {
UNDEFINED , NONE , RELU , RELU_N1_TO_1 ,
RELU6 , TANH , SIGN_BIT
}
Functions
tflite::RuntimeShape tflite_shape (const loco::TensorShape &shape)
tflite::PaddingType tflite_padding (const PaddingType type)
tflite::FullyConnectedWeightsFormat tflite_weights_format (const FullyConnectedWeightsFormat type)
Enumeration Type Documentation
FullyConnectedWeightsFormat
enum class luci::compute::FullyConnectedWeightsFormat : uint8_t strong
Enumerator
kDefault
kShuffled4x16Int8
Definition at line 80 of file Types.h.
{
  kDefault,
  kShuffled4x16Int8,
};
FusedActFunc
enum class luci::compute::FusedActFunc strong
Enumerator
UNDEFINED
NONE
RELU
RELU_N1_TO_1
RELU6
TANH
SIGN_BIT
Definition at line 109 of file Types.h.
{
  UNDEFINED, // This is not defined by TFLite or Circle. This was added to
             // prevent programming error.
  NONE,
  RELU,
  RELU_N1_TO_1,
  RELU6,
  TANH,
  SIGN_BIT
};
PaddingType
enum class luci::compute::PaddingType : uint8_t strong
Enumerator
kNone
kSame
kValid
Definition at line 32 of file Types.h.
{
  kNone,
  kSame,
  kValid
};
Function Documentation
tflite_padding()
tflite::PaddingType luci::compute::tflite_padding (const PaddingType type)
Definition at line 37 of file ConvertTypes.cpp.
{
  switch (type)
  {
    case PaddingType::kSame:
      return tflite::PaddingType::kSame;
    case PaddingType::kValid:
      return tflite::PaddingType::kValid;
    default:
      break;
  }
  throw std::runtime_error("luci-comp tflite_padding unsupported type.");
}
References kSame, and kValid.
Referenced by luci::compute::DepthwiseConv2D::compute().
tflite_shape()
tflite::RuntimeShape luci::compute::tflite_shape (const loco::TensorShape & shape)
Definition at line 26 of file ConvertTypes.cpp.
{
  tflite::RuntimeShape runtime_shape(shape.rank());
  for (uint32_t i = 0; i < shape.rank(); ++i)
  {
    assert(shape.dim(i).known());
    runtime_shape.SetDim(i, shape.dim(i).value());
  }
  return runtime_shape;
}
References loco::TensorShape::dim(), loco::Dimension::known(), loco::TensorShape::rank(), and loco::Dimension::value().
Referenced by luci::compute::DepthwiseConv2D::compute(), and luci::compute::FullyConnected::compute().
tflite_weights_format()
tflite::FullyConnectedWeightsFormat luci::compute::tflite_weights_format (const FullyConnectedWeightsFormat type)
Definition at line 51 of file ConvertTypes.cpp.
{
  switch (type)
  {
    case FullyConnectedWeightsFormat::kDefault:
      return tflite::FullyConnectedWeightsFormat::kDefault;
    case FullyConnectedWeightsFormat::kShuffled4x16Int8:
      return tflite::FullyConnectedWeightsFormat::kShuffled4x16Int8;
    default:
      break;
  }
  throw std::runtime_error("luci-comp tflite_weights_format unsupported type.");
}
References kDefault, and kShuffled4x16Int8.
Referenced by luci::compute::FullyConnected::compute().