ONE - On-device Neural Engine: onert::interp::instancenorm Namespace Reference
onert::interp::instancenorm Namespace Reference
Functions
void prepareInstanceNorm (ExecEnv *env, const ir::Operation &node)
void setActivationParams (float min, float max, nnfw::cker::InstanceNormParams *params)
void invoke (const ITensor *input_tensor, const ITensor *gamma_tensor, const ITensor *beta_tensor, const ITensor *output_tensor, const ir::operation::InstanceNorm::Param &param)
void invokeInstanceNorm (const ExecEnv *env, const ir::Operation &node)
Function Documentation
invoke()
void onert::interp::instancenorm::invoke (const ITensor * input_tensor, const ITensor * gamma_tensor, const ITensor * beta_tensor, const ITensor * output_tensor, const ir::operation::InstanceNorm::Param & param)
Definition at line 63 of file InstanceNorm.cc.
{
  // Calculate
  float activation_min, activation_max;
  calculateActivationRange(param.activation, &activation_min, &activation_max);
  nnfw::cker::InstanceNormParams cker_param;
  cker_param.epsilon = param.epsilon;
  cker_param.float_activation_min = activation_min;
  cker_param.float_activation_max = activation_max;
  const auto cker_input_shape = convertShape(input_tensor->tensorInfo().shape());
  const auto cker_gamma_shape = convertShape(gamma_tensor->tensorInfo().shape());
  const auto cker_beta_shape = convertShape(beta_tensor->tensorInfo().shape());
  const auto cker_output_shape = convertShape(output_tensor->tensorInfo().shape());
  const float *input_ptr = reinterpret_cast<const float *>(input_tensor->bufferRO());
  const float *gamma_ptr = reinterpret_cast<const float *>(gamma_tensor->bufferRO());
  const float *beta_ptr = reinterpret_cast<const float *>(beta_tensor->bufferRO());
  float *output_ptr = reinterpret_cast<float *>(output_tensor->buffer());
  nnfw::cker::InstanceNorm(cker_param, cker_input_shape, input_ptr, cker_gamma_shape, gamma_ptr,
                           cker_beta_shape, beta_ptr, cker_output_shape, output_ptr);
}
References onert::ir::operation::InstanceNorm::Param::activation, onert::interp::ITensor::bufferRO(), onert::interp::calculateActivationRange(), onert::interp::convertShape(), nnfw::cker::InstanceNormParams::epsilon, onert::ir::operation::InstanceNorm::Param::epsilon, nnfw::cker::InstanceNormParams::float_activation_max, nnfw::cker::InstanceNormParams::float_activation_min, nnfw::cker::InstanceNorm(), onert::ir::OperandInfo::shape(), and onert::interp::ITensor::tensorInfo().
Referenced by invokeInstanceNorm().
invokeInstanceNorm()
void onert::interp::instancenorm::invokeInstanceNorm (const ExecEnv * env, const ir::Operation & node)
Definition at line 88 of file InstanceNorm.cc.
{
  const auto &instancenorm_node =
    nnfw::misc::polymorphic_downcast<const ir::operation::InstanceNorm &>(node);
  const auto input_index = node.getInputs().at(instancenorm_node.INPUT);
  const auto gamma_index = node.getInputs().at(instancenorm_node.GAMMA);
  const auto beta_index = node.getInputs().at(instancenorm_node.BETA);
  const auto out_index = node.getOutputs().at(0);
  const auto input_tensor = env->tensorAt(input_index);
  const auto gamma_tensor = env->tensorAt(gamma_index);
  const auto beta_tensor = env->tensorAt(beta_index);
  const auto out_tensor = env->tensorAt(out_index);
  const auto data_type = input_tensor->data_type();
  if (data_type == ir::DataType::FLOAT32)
  {
    invoke(input_tensor, gamma_tensor, beta_tensor, out_tensor, instancenorm_node.param());
  }
  else
  {
    throw std::runtime_error{"NYI: Unsupported data type"};
  }
}
References onert::ir::OperandIndexSequence::at(), onert::interp::ITensor::data_type(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), invoke(), and onert::interp::ExecEnv::tensorAt().
Referenced by onert::interp::getInstanceNorm().
prepareInstanceNorm()
void onert::interp::instancenorm::prepareInstanceNorm (ExecEnv * env, const ir::Operation & node)
Definition at line 32 of file InstanceNorm.cc.
{
  const auto &instancenorm_node =
    nnfw::misc::polymorphic_downcast<const ir::operation::InstanceNorm &>(node);
  const auto input_index = node.getInputs().at(instancenorm_node.INPUT);
  const auto output_index = node.getOutputs().at(0);
  const auto input_tensor = env->tensorAt(input_index);
  if (input_tensor->getShape().rank() != 4)
  {
    throw std::runtime_error{"Interp(InstanceNorm): Input should be 4D-tensor"};
  }
  // Output shape should be same with input
  env->allocateIfNeeded(output_index, input_tensor->tensorInfo());
  auto output_tensor = env->tensorAt(output_index);
  UNUSED_RELEASE(output_tensor);
  // Handle same ifm & ofm data type only
  assert(input_tensor->data_type() == output_tensor->data_type());
  assert(input_tensor->tensorInfo().shape() == output_tensor->tensorInfo().shape());
}
References onert::interp::ExecEnv::allocateIfNeeded(), onert::ir::OperandIndexSequence::at(), onert::ir::Operation::getInputs(), onert::ir::Operation::getOutputs(), onert::interp::ExecEnv::tensorAt(), and UNUSED_RELEASE.
Referenced by onert::interp::getInstanceNorm().
setActivationParams()
void onert::interp::instancenorm::setActivationParams (float min, float max, nnfw::cker::InstanceNormParams * params) inline
Definition at line 57 of file InstanceNorm.cc.
{
  params->float_activation_min = min;
  params->float_activation_max = max;
}
References nnfw::cker::InstanceNormParams::float_activation_max, and nnfw::cker::InstanceNormParams::float_activation_min.