ONE - On-device Neural Engine: filesystem Namespace Reference
filesystem Namespace Reference
Functions
const std::string separator ()
std::string normalize_path (const std::string &path)
Normalize compatible separator in path to default separator.
bool is_dir (const std::string &path)
bool mkdir (const std::string &path)
std::string join (const std::string &path1, const std::string &path2)
std::string basename (const std::string &path)
Function Documentation
basename()
std::string filesystem::basename (const std::string & path)
Definition at line 29 of file filesystem_common.cpp.
{
  auto last_index = path.find_last_of(separator());
  // No separator
  if (last_index == std::string::npos)
    return path;
  // Trailing separator
  if (last_index + separator().size() == path.size())
    return basename(path.substr(0, last_index));
  return path.substr(last_index + separator().size());
}
References basename(), and separator().
Referenced by basename().
is_dir()
bool filesystem::is_dir (const std::string & path)
Definition at line 33 of file filesystem_linux.cpp.
{
  DIR *dir = opendir(path.c_str());
  if (dir)
  {
    closedir(dir);
    return true;
  }
  return false;
}
join()
std::string filesystem::join (const std::string & path1, const std::string & path2)
Definition at line 22 of file filesystem_common.cpp.
{
  // TODO check path1 does not end with separator
  // TODO check path2 does not start with separator
  return path1 + separator() + path2;
}
References separator().
mkdir()
bool filesystem::mkdir (const std::string & path)
Definition at line 44 of file filesystem_linux.cpp.
{ return ::mkdir(path.c_str(), 0775) == 0; }
normalize_path()
std::string filesystem::normalize_path (const std::string & path)
Normalize compatible separator in path to default separator.
Definition at line 27 of file filesystem_linux.cpp.
{
  // DO NOTHING
  return path;
}
separator()
const std::string filesystem::separator ()
Definition at line 25 of file filesystem_linux.cpp.
{ return "/"; }
Referenced by basename(), and join().