ONE - On-device Neural Engine: nnc::opt_util Namespace Reference
nnc::opt_util Namespace Reference
Functions
void swapAdjacent (mir::Graph *g, mir::Operation *top, mir::Operation *bottom)
Swap adjacent nodes in Graph. Creates new nodes and replaces the old ones with new.
void removeNodeIfUnused (mir::Graph *g, mir::Operation *op)
Function Documentation
removeNodeIfUnused()
void nnc::opt_util::removeNodeIfUnused (mir::Graph * g, mir::Operation * op)
Definition at line 48 of file OptimizationUtils.cpp.
{
  if (op->getOutput(0)->getUses().empty())
    g->removeNode(op);
}
References mir::Operation::getOutput(), and mir::Operation::Output::getUses().
Referenced by nnc::ConstantFoldTranspose::run(), nnc::SinkRelu::run(), and nnc::SinkTranspose::run().
swapAdjacent()
void nnc::opt_util::swapAdjacent (mir::Graph * g, mir::Operation * top, mir::Operation * bottom)
Swap adjacent nodes in Graph. Creates new nodes and replaces the old ones with new.
Parameters
g MIR Graph
top Node
bottom Node
Definition at line 23 of file OptimizationUtils.cpp.
{
  assert(top->getNumInputs() == bottom->getNumInputs() && top->getNumInputs() == 1 &&
         top->getNumInputs() == top->getNumOutputs() &&
         top->getNumInputs() == bottom->getNumOutputs() && "incompatible ops");
  const auto &ins = top->getInputs();
  std::vector<mir::Operation::Output *> prods;
  prods.reserve(top->getNumInputs());
  for (mir::Operation::Output *in : ins)
  {
    prods.emplace_back(in);
  }
  mir::Operation *new_bottom = g->copyOpWithInputs(bottom, prods);
  prods.clear();
  prods.reserve(new_bottom->getNumOutputs());
  for (mir::Operation::Output &out : new_bottom->getOutputs())
  {
    prods.emplace_back(&out);
  }
  mir::Operation *new_top = g->copyOpWithInputs(top, prods);
  g->replaceNode(bottom, new_top);
  g->replaceNode(top, new_bottom);
}
References mir::Operation::getInputs(), mir::Operation::getNumInputs(), mir::Operation::getNumOutputs(), and mir::Operation::getOutputs().
Referenced by nnc::SinkRelu::run(), and nnc::SinkTranspose::run().