ONE - On-device Neural Engine: nnfw::ruy::ruy_support Namespace Reference
nnfw::ruy::ruy_support Namespace Reference
Functions
inline ::ruy::CachePolicy ToRuyCachePolicy (CachePolicy cache_policy)
template<typename Scalar , typename DataPointer >
void MakeRuyMatrix (const MatrixParams< Scalar > &params, DataPointer data_ptr, ::ruy::Matrix< Scalar > *dst, bool use_caching=false)
template<typename AccumScalar , typename DstScalar , QuantizationFlavor quantization_flavor>
void MakeRuyMulParams (const GemmParams< AccumScalar, DstScalar, quantization_flavor > &params, ::ruy::MulParams< AccumScalar, DstScalar > *ruy_mul_params)
template<typename DstScalar , QuantizationFlavor quantization_flavor>
void MakeRuyMulParams (const GemmParams< std::int32_t, DstScalar, quantization_flavor > &params, ::ruy::MulParams< std::int32_t, DstScalar > *ruy_mul_params)
template<QuantizationFlavor quantization_flavor>
void MakeRuyMulParams (const GemmParams< std::int32_t, std::int32_t, quantization_flavor > &params, ::ruy::MulParams< std::int32_t, std::int32_t > *ruy_mul_params)
Function Documentation
MakeRuyMatrix()
template<typename Scalar , typename DataPointer > void nnfw::ruy::ruy_support::MakeRuyMatrix (const MatrixParams< Scalar > & params, DataPointer data_ptr, ::ruy::Matrix< Scalar > * dst, bool use_caching = false)
Definition at line 51 of file RuySupport.h.
{
  ::ruy::Order ruy_order =
    params.order == Order::kColMajor ? ::ruy::Order::kColMajor : ::ruy::Order::kRowMajor;
  ::ruy::MakeSimpleLayout(params.rows, params.cols, ruy_order, dst->mutable_layout());
  // Note that ruy::Matrix::data is a ConstCheckingPtr, not a plain pointer.
  // It does care whether we assign to it a Scalar* or a const Scalar*.
  dst->set_data(data_ptr);
  dst->set_zero_point(params.zero_point);
  if (use_caching)
  {
    dst->set_cache_policy(ToRuyCachePolicy(params.cache_policy));
  }
}
References nnfw::ruy::MatrixParams< Scalar >::cache_policy, nnfw::ruy::MatrixParams< Scalar >::cols, nnfw::ruy::kColMajor, nnfw::ruy::kRowMajor, nnfw::ruy::MatrixParams< Scalar >::order, nnfw::ruy::MatrixParams< Scalar >::rows, ToRuyCachePolicy(), and nnfw::ruy::MatrixParams< Scalar >::zero_point.
Referenced by nnfw::ruy::FullyConnected().
MakeRuyMulParams() [1/3]
template<typename AccumScalar , typename DstScalar , QuantizationFlavor quantization_flavor> void nnfw::ruy::ruy_support::MakeRuyMulParams (const GemmParams< AccumScalar, DstScalar, quantization_flavor > & params, ::ruy::MulParams< AccumScalar, DstScalar > * ruy_mul_params)
Definition at line 69 of file RuySupport.h.
{
  static_assert(quantization_flavor == QuantizationFlavor::kFloatingPoint, "");
  ruy_mul_params->set_bias(params.bias);
  ruy_mul_params->set_clamp_min(params.clamp_min);
  ruy_mul_params->set_clamp_max(params.clamp_max);
}
References nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::bias, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::clamp_max, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::clamp_min, and nnfw::ruy::kFloatingPoint.
Referenced by nnfw::ruy::FullyConnected().
MakeRuyMulParams() [2/3]
template<typename DstScalar , QuantizationFlavor quantization_flavor> void nnfw::ruy::ruy_support::MakeRuyMulParams (const GemmParams< std::int32_t, DstScalar, quantization_flavor > & params, ::ruy::MulParams< std::int32_t, DstScalar > * ruy_mul_params)
Definition at line 80 of file RuySupport.h.
{
  static_assert(sizeof(DstScalar) < sizeof(std::int32_t), "");
  if (quantization_flavor == QuantizationFlavor::kIntegerWithUniformMultiplier)
  {
    ruy_mul_params->set_multiplier_fixedpoint(params.multiplier_fixedpoint);
    ruy_mul_params->set_multiplier_exponent(params.multiplier_exponent);
  }
  if (quantization_flavor == QuantizationFlavor::kIntegerWithPerRowMultiplier)
  {
    ruy_mul_params->set_multiplier_fixedpoint_perchannel(params.multiplier_fixedpoint_perchannel);
    ruy_mul_params->set_multiplier_exponent_perchannel(params.multiplier_exponent_perchannel);
  }
  ruy_mul_params->set_bias(params.bias);
  ruy_mul_params->set_clamp_min(params.clamp_min);
  ruy_mul_params->set_clamp_max(params.clamp_max);
}
References nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::bias, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::clamp_max, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::clamp_min, nnfw::ruy::kIntegerWithPerRowMultiplier, nnfw::ruy::kIntegerWithUniformMultiplier, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::multiplier_exponent, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::multiplier_exponent_perchannel, nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::multiplier_fixedpoint, and nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::multiplier_fixedpoint_perchannel.
MakeRuyMulParams() [3/3]
template<QuantizationFlavor quantization_flavor> void nnfw::ruy::ruy_support::MakeRuyMulParams (const GemmParams< std::int32_t, std::int32_t, quantization_flavor > & params, ::ruy::MulParams< std::int32_t, std::int32_t > * ruy_mul_params)
Definition at line 101 of file RuySupport.h.
{
  ruy_mul_params->set_bias(params.bias);
}
References nnfw::ruy::GemmParams< AccumScalar, DstScalar, quantization_flavor >::bias.
ToRuyCachePolicy()
inline ::ruy::CachePolicy nnfw::ruy::ruy_support::ToRuyCachePolicy (CachePolicy cache_policy)
Definition at line 34 of file RuySupport.h.
{
  switch (cache_policy)
  {
    case CachePolicy::kNeverCache:
      return ::ruy::CachePolicy::kNeverCache;
    case CachePolicy::kCacheIfLargeSpeedup:
      return ::ruy::CachePolicy::kCacheIfLargeSpeedup;
    case CachePolicy::kAlwaysCache:
      return ::ruy::CachePolicy::kAlwaysCache;
    default:
      assert(false);
      return ::ruy::CachePolicy::kNeverCache;
  }
}
References nnfw::ruy::kAlwaysCache, nnfw::ruy::kCacheIfLargeSpeedup, and nnfw::ruy::kNeverCache.
Referenced by MakeRuyMatrix().