ONE - On-device Neural Engine: onert::backend::basic::train Namespace Reference
onert::backend::basic::train Namespace Reference
Data Structures
class TrainableTensor
Functions
template<typename TensorBuilder >
ITensorRegistry * genTensors (backend::train::TrainableBackendContext &ctx, const std::shared_ptr< TensorBuilder > &tensor_builder)
Function Documentation
genTensors()
template<typename TensorBuilder > ITensorRegistry * onert::backend::basic::train::genTensors (backend::train::TrainableBackendContext & ctx, const std::shared_ptr< TensorBuilder > & tensor_builder)
Definition at line 34 of file TrainableBackendContextHelpers.h.
{
  const auto &tgraph = *ctx.trainable_graph();
  auto model_io =
    (tgraph.getInputs() + tgraph.getOutputs()) | ir::Remove::UNDEFINED | ir::Remove::DUPLICATED;
  tgraph.operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &obj) {
    if (ctx.external_operands().contains(ind))
      return;
    // NOTE Assuming there is no layout changes (Always assume NHWC or UNKNOWN)
    assert(tgraph.layout() != ir::Layout::NCHW);
    tensor_builder->registerTensorInfo(ind, obj.info(), ir::Layout::NHWC);
  });
  // For the executors that does not have fixed linear execution order:
  // To make tensors never be deallocated, this is a workaround to use static memory planner
  tgraph.operands().iterate([&](const ir::OperandIndex &ind, const ir::Operand &) {
    if (tensor_builder->isRegistered(ind))
      tensor_builder->notifyFirstUse(ind);
  });
  tensor_builder->allocate();
  return ctx.tensor_registry().get();
}
References onert::ir::DUPLICATED, onert::backend::train::TrainableBackendContext::external_operands(), onert::ir::NCHW, onert::ir::NHWC, onert::backend::train::TrainableBackendContext::tensor_registry(), onert::backend::train::TrainableBackendContext::trainable_graph(), and onert::ir::UNDEFINED.
Referenced by onert::backend::train::BackendContext::genTensors().