ONE - On-device Neural Engine: circle_resizer Namespace Reference
circle_resizer Namespace Reference
Data Structures
class CircleModel
class Dim
class ModelEditor
class Shape
Functions
std::ostream & operator<< (std::ostream &os, const Shape &shape)
Print the shape in format [1, 2, 3].
std::vector< Shape > parse_shapes (const std::string &shapes)
Parse shapes from string representation to Shapes object.
Function Documentation
operator<<()
std::ostream & circle_resizer::operator<< (std::ostream & os, const Shape & shape)
Print the shape in format [1, 2, 3].
Definition at line 86 of file Shape.cpp.
{
  if (shape.is_scalar())
  {
    os << "[]";
    return os;
  }
  os << "[";
  for (int i = 0; i < shape.rank() - 1; ++i)
  {
    os << shape[i].value() << ", ";
  }
  os << shape[shape.rank() - 1].value() << "]";
  return os;
}
References circle_resizer::Shape::is_scalar(), and circle_resizer::Shape::rank().
parse_shapes()
std::vector< Shape > circle_resizer::parse_shapes (const std::string & shapes)
Parse shapes from string representation to Shapes object.
The single shape is represented by comma-separated integers inside squared brackets. If there is more than one shape, they are separated by commas. An example for single shape: [1,2,3], an example for many shapes: [1,2,3],[4,5].
Exceptions: std::invalid_argument if the parsing failed.
Definition at line 65 of file ShapeParser.cpp.
{
  std::vector<Shape> result_shapes;
  auto shapes_tmp = shapes;
  std::string token;
  size_t begin_pos = 0, end_pos = 0;
  while ((begin_pos = shapes_tmp.find_first_of("[")) != std::string::npos &&
         (end_pos = shapes_tmp.find_first_of("]")) != std::string::npos)
  {
    if (begin_pos > end_pos)
    {
      throw std::invalid_argument("Invalid shape format: " + shapes);
    }
    const size_t token_size = end_pos - begin_pos - 1;
    token = shapes_tmp.substr(begin_pos + 1, token_size);
    result_shapes.push_back(parse_single_shape(token));
    shapes_tmp.erase(0, end_pos + 1);
  }
  if (result_shapes.empty())
  {
    throw std::invalid_argument("No shapes found in the input string: " + shapes);
  }
  // the rest of the input not handled by loop above cannot be processed properly
  if (shapes_tmp.size() > 0 && !is_blank(shapes_tmp))
  {
    throw std::invalid_argument("The part of input shapes: " + shapes_tmp + " cannot be processed");
  }
  return result_shapes;
}
Referenced by entry().