ONE - On-device Neural Engine: exo Namespace Reference
exo Namespace Reference
Namespaces
namespace circle_detail
namespace test
namespace tflite_detail
Data Structures
class AvgPool2DConverter
Convert loco::AvgPool2D to locoex::TFLAveragePool2D.
class CanonicalNodeConverter
Class to convert a canonical node to TFL node.
class CircleExporter
class ConstGenConverter
class Conv2DConverter
Convert loco::Conv2D to locoex::TFLConv2D.
class DepthwiseConv2DConverter
Convert loco::DepthwiseConv2D to locoex::TFLDepthwiseConv2D and auxiliary.
class DomainConverter
Class to handle domain conversion while converting a canonical node to TFL node(s)
class EltwiseAddConverter
Convert loco::EltwiseAdd to TFLAdd.
class EltwiseDivConverter
Convert loco::EltwiseDiv to TFLDiv.
class EltwiseMaxConverter
Convert loco::EltwiseMax to TFLMaximum.
class EltwiseMulConverter
Convert loco::EltwiseMul to TFLMul.
class EltwiseSqrtConverter
Convert loco::EltwiseSqrt to TFLSqrt.
class EltwiseSubConverter
Convert loco::EltwiseSub to TFLSub.
class FeatureBiasAddConverter
struct FoldReshapeOfConstPass
Class to fuse TFLReshape + TFLConst into one equivalent TFLConst.
struct FoldTransposeOfConstPass
Class to fuse TFLTranspose + TFLConst into one equivalent TFLConst.
struct FuseBiasAddPass
Class to fuse TFLAdd or TFLSub into Bias input of the following ops:
struct FuseInstanceNormPass
Class to fuse certain pattern of subgraph into CircleInstanceNorm with auxiliary nodes.
struct FuseReluPass
Class to fuse TFLRelu or TFLRelu6 into the TensorFlow Lite ops below:
struct FuseRsqrtPass
Class to fuse TFLSqrt that is divided(TFLDiv) by 1, into TFLRsqrt.
struct FuseSquaredDifferencePass
Class to fuse SquaredDifference pattern.
class InputHandler
Handles input(s) while converting a canonical node to TFL node(s). This class informs DomainConverter how to handle inputs of a specific canonical node.
struct KnobTrait
class Logger
Logger Implementation.
class LoggerConfig
Logger Configuration.
struct LoggingContext
Global logging context.
class MatMulConverter
Convert loco::MatMul to locoex::TFLFullyConnected.
class MaxPool2DConverter
Convert loco::MaxPool2D to locoex::TFLMaxPool2D.
class MergeConcatNodesPass
Merge concat nodes whose axis and fusedActivationFunction are same.
class NodeSummaryBuilder
class NodeSummaryBuilderFactory
class ProgressReporter
class Relu6Converter
Convert loco::Relu6 to TFLRelu6.
class ReluConverter
Convert loco::Relu to TFLRelu.
struct ShapeDescription
struct ShapeInference
Get the shape of each node as a node annotation.
class ShapeInferencePass
Pass to infer shape of nodes.
class TensorBroadcastConverter
Pass to resolve TensorBroadcast IR.
class TensorConcatConverter
Convert loco::TensorConcat to TFLConcatenate.
class TensorReduceConverter
Convert loco::TensorReduce to appropriate TFL reduce operation.
class TensorTransposeConverter
Convert loco::TensorTranspose to locoex::TFLTranspose.
class TFLExporter
class TransposedConv2DConverter
Convert loco::TransposedConv2D to locoex::TFLTransposeConv and auxiliary.
struct TypeInference
Get the type of each node as NodeAnnotation.
class TypeInferencePass
Pass to infer type of nodes.
Typedefs
using FormattedGraph = locop::FormattedGraphImpl< locop::Formatter::LinearV1 >
Enumerations
enum class FeatureLayout { NHWC }
feature layout of TFLITE file
enum class FilterLayout { OHWI , HWIO }
enum class DepthwiseFilterLayout { HWCM }
enum class MatrixLayout { HW , WH }
enum class Dialect { TFLITE , CIRCLE }
enum class Knob { KNOB_BOOL }
Functions
circle::ActivationFunctionType to_circle_actfunc (locoex::FusedActFunc func)
template<class ELTWISEBIN , class TFLBIN >
bool EltwiseBinaryConvert (ELTWISEBIN *origin)
void convert_to_TFLNodes (loco::Graph *graph)
void optimize (loco::Graph *)
Run passes for a graph after completion of converting canonical nodes into TFL nodes.
ShapeDescription to_shape_description (const loco::TensorShape &shape)
ShapeDescription to_shape_description (const loco::FeatureShape &shape)
ShapeDescription to_shape_description (const loco::FilterShape &shape)
ShapeDescription to_shape_description (const loco::DepthwiseFilterShape &shape)
ShapeDescription to_shape_description (const loco::BiasShape &shape)
ShapeDescription to_shape_description (const loco::MatrixShape &shape)
ShapeDescription to_shape_description (const loco::NodeShape &shape)
template<typename Permutation >
bool isNHWC (Permutation *perm)
template<>
bool isNHWC (loco::Permutation< loco::Domain::Feature > *perm)
template<>
bool isNHWC (loco::Permutation< loco::Domain::Filter > *perm)
template<FeatureLayout T>
loco::FeatureEncode * make_feature_encode (loco::Node *input_for_encode)
Creates a loco::FeatureEncode with T layout (NHWC for tflite) and add it to graph.
template<FeatureLayout T>
loco::FeatureDecode * make_feature_decode (loco::Node *input_for_decode)
Creates a loco::FeatureDecode with T layout (NHWC for tflite) and add it to graph.
template<FilterLayout T>
loco::FilterEncode * make_filter_encode (loco::Node *input_for_encode)
Create a loco::FilterEncode of given layout.
template<FilterLayout T>
loco::FilterDecode * make_filter_decode (loco::Node *input_for_decode)
Create a loco::FilterDecode of given layout.
template<DepthwiseFilterLayout T>
loco::DepthwiseFilterDecode * make_dw_filter_decode (loco::Node *input_for_decode)
Create a loco::DepthwiseFilterDecode of given layout.
template<MatrixLayout T>
loco::MatrixEncode * make_matrix_encode (loco::Node *input_for_encode)
Create a loco::MatrixEncode of given layout.
template<MatrixLayout T>
loco::MatrixDecode * make_matrix_decode (loco::Node *input_for_decode)
Create a loco::MatrixDecode of given layout.
template loco::FeatureEncode * make_feature_encode< FeatureLayout::NHWC > (loco::Node *input_for_encode)
template loco::FeatureDecode * make_feature_decode< FeatureLayout::NHWC > (loco::Node *input_for_encode)
template loco::FilterEncode * make_filter_encode< FilterLayout::HWIO > (loco::Node *input_for_encode)
template loco::FilterDecode * make_filter_decode< FilterLayout::OHWI > (loco::Node *input_for_decode)
template loco::DepthwiseFilterDecode * make_dw_filter_decode< DepthwiseFilterLayout::HWCM > (loco::Node *input_for_decode)
template loco::MatrixEncode * make_matrix_encode< MatrixLayout::HW > (loco::Node *input_for_encode)
template loco::MatrixEncode * make_matrix_encode< MatrixLayout::WH > (loco::Node *input_for_encode)
template loco::MatrixDecode * make_matrix_decode< MatrixLayout::HW > (loco::Node *input_for_decode)
template loco::MatrixDecode * make_matrix_decode< MatrixLayout::WH > (loco::Node *input_for_decode)
void set (Dialect d)
template<Knob K>
KnobTrait< K >::ValueType get (void)
FormattedGraph fmt (loco::Graph *g)
tflite::ActivationFunctionType to_tflite_actfunc (locoex::FusedActFunc func)
Detailed Description
Some canonical nodes can have input of various loco::Domain, e.g., loco::Domain::Tensor, loco::Domain::Feature, etc. However, TFL node accepts only loco::Domain::Tensor. So, When converting such canonical node to TFL node and input(s) of a canonical node are not loco::Domain::Tensor, additional nodes need to be inserted.
The following two classes helps this insertion.
For example, in case of loco::Relu conversion,
Before:
A (output: feature) – loco::ReLU — B (input:feature)
After:
A – loco::FeatureDecode – locoex::TFLRelu – loco::FeatureEncode — B
          loco::ReLU (dead node)
Typedef Documentation
FormattedGraph
using exo::FormattedGraph = typedef locop::FormattedGraphImpl<locop::Formatter::LinearV1>
Definition at line 62 of file LogHelper.h.
Enumeration Type Documentation
DepthwiseFilterLayout
enum class exo::DepthwiseFilterLayout strong
Enumerator
HWCM
Definition at line 54 of file GraphBlock.h.
{
  HWCM,
};
Dialect
enum class exo::Dialect strong
Enumerator
TFLITE
CIRCLE
Definition at line 23 of file Knob.h.
{
  TFLITE,
  CIRCLE
};
FeatureLayout
enum class exo::FeatureLayout strong
feature layout of TFLITE file
Enumerator
NHWC
Definition at line 31 of file GraphBlock.h.
{
  NHWC,
};
FilterLayout
enum class exo::FilterLayout strong
Enumerator
OHWI
HWIO
Definition at line 42 of file GraphBlock.h.
{
  OHWI, // a.k.a., NHWC, Tensorflow Lite uses this layout for filter
  HWIO, // a.k.a., HWCN, Tensorflow uses this layout for filter
};
Knob
enum class exo::Knob strong
Enumerator
KNOB_BOOL
Definition at line 29 of file Knob.h.
{
#define KNOB_BOOL(NAME, TFL_DEFAULT, CIRCLE_DEFAULT, DESC) NAME,
#include "Knob.lst"
#undef KNOB_BOOL
};
MatrixLayout
enum class exo::MatrixLayout strong
Enumerator
HW
WH
Definition at line 63 of file GraphBlock.h.
{
  HW,
  WH
};
Function Documentation
convert_to_TFLNodes()
void exo::convert_to_TFLNodes (loco::Graph * graph)
Definition at line 40 of file Convert.cpp.
{
  // run Shape and Type inference must be run before conversion
  loco::CanonicalShapeInferenceRule shape_rule;
  loco::apply(&shape_rule).to(graph);
  loco::CanonicalTypeInferenceRule type_rule;
  loco::apply(&type_rule).to(graph);
  logo::Phase phase;
  {
    // prepare type and shape before conversion
    phase.emplace_back(std::make_unique<TypeInferencePass>());
    phase.emplace_back(std::make_unique<ShapeInferencePass>());
    // Add converters for canonical nodes. Note: Not all loco canonical nodes are listed.
    phase.emplace_back(std::make_unique<AvgPool2DConverter>());
    phase.emplace_back(std::make_unique<ConstGenConverter>());
    phase.emplace_back(std::make_unique<Conv2DConverter>());
    phase.emplace_back(std::make_unique<DepthwiseConv2DConverter>());
    // TODO loco::DepthwiseFilterEncode
    phase.emplace_back(std::make_unique<EltwiseAddConverter>());
    phase.emplace_back(std::make_unique<EltwiseDivConverter>());
    phase.emplace_back(std::make_unique<EltwiseMaxConverter>());
    phase.emplace_back(std::make_unique<EltwiseMulConverter>());
    phase.emplace_back(std::make_unique<EltwiseSqrtConverter>());
    phase.emplace_back(std::make_unique<EltwiseSubConverter>());
    phase.emplace_back(std::make_unique<FeatureBiasAddConverter>());
    // TODO loco::FixedReshape
    phase.emplace_back(std::make_unique<MatMulConverter>());
    phase.emplace_back(std::make_unique<MaxPool2DConverter>());
    phase.emplace_back(std::make_unique<ReluConverter>());
    phase.emplace_back(std::make_unique<Relu6Converter>());
    // TODO loco::Tanh
    phase.emplace_back(std::make_unique<TensorConcatConverter>());
    // TODO loco::TensorBiasAdd
    phase.emplace_back(std::make_unique<TensorBroadcastConverter>());
    phase.emplace_back(std::make_unique<TensorReduceConverter>());
    // TODO loco::TensorSoftmax
    phase.emplace_back(std::make_unique<TensorTransposeConverter>());
    phase.emplace_back(std::make_unique<TransposedConv2DConverter>());
    // Add optimization below
    phase.emplace_back(std::make_unique<logo::SimplifyDomainConversionPass>());
    phase.emplace_back(std::make_unique<logo::RemoveForwardNodePass>());
    phase.emplace_back(std::make_unique<logo::RemoveDeadNodePass>());
  }
  logo::PhaseRunner<logo::PhaseStrategy::Restart> phase_runner{graph};
  ProgressReporter prog(graph, logo::PhaseStrategy::Restart);
  phase_runner.attach(&prog);
  phase_runner.run(phase);
  // TODO Assert if all canonical nodes are converted to TFL node
}
References loco::apply(), logo::Restart, and loco::ShapeInferenceSession::to().
EltwiseBinaryConvert()
template<class ELTWISEBIN , class TFLBIN > bool exo::EltwiseBinaryConvert (ELTWISEBIN * origin)
Definition at line 93 of file EltwiseBinaryConverter.h.
{
  EltwiseBinInputHandler<ELTWISEBIN, TFLBIN> input_handler;
  exo::DomainConverter<ELTWISEBIN, TFLBIN> domain_converter;
  auto tfl_node = domain_converter.template convert<FeatureLayout::NHWC>(origin, input_handler);
  if (tfl_node == nullptr)
    return false;
  init_fused_act_func(tfl_node);
  return true;
}
fmt()
FormattedGraph exo::fmt (loco::Graph * g)
Definition at line 73 of file LogHelper.cpp.
{
  auto node_summary_builder = std::make_unique<NodeSummaryBuilderFactory>();
  return std::move(locop::fmt<locop::LinearV1>(g).with(std::move(node_summary_builder)));
}
Referenced by exo::ProgressReporter::notify().
get()
template<Knob K> KnobTrait< K >::ValueType exo::get (void)
isNHWC() [1/3]
template<> bool exo::isNHWC (loco::Permutation< loco::Domain::Feature > * perm) inline
Definition at line 43 of file ExporterUtils.h.
{
  return perm->axis(loco::FeatureAxis::Count) == 0 && perm->axis(loco::FeatureAxis::Height) == 1 &&
         perm->axis(loco::FeatureAxis::Width) == 2 && perm->axis(loco::FeatureAxis::Depth) == 3;
}
References loco::Count, loco::Depth, loco::Height, and loco::Width.
isNHWC() [2/3]
template<> bool exo::isNHWC (loco::Permutation< loco::Domain::Filter > * perm) inline
Definition at line 49 of file ExporterUtils.h.
{
  return perm->axis(loco::FilterAxis::Count) == 0 && perm->axis(loco::FilterAxis::Height) == 1 &&
         perm->axis(loco::FilterAxis::Width) == 2 && perm->axis(loco::FilterAxis::Depth) == 3;
}
References loco::Count, loco::Depth, loco::Height, and loco::Width.
isNHWC() [3/3]
template<typename Permutation > bool exo::isNHWC (Permutation * perm) inline
make_dw_filter_decode()
template<DepthwiseFilterLayout T> loco::DepthwiseFilterDecode * exo::make_dw_filter_decode (loco::Node * input_for_decode)
Create a loco::DepthwiseFilterDecode of given layout.
Definition at line 177 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_decode != nullptr, "filter should not be nullptr");
  loco::Graph *g = input_for_decode->graph();
  auto decoder = std::make_unique<loco::PermutingDecoder<loco::Domain::DepthwiseFilter>>();
  decoder->perm(perm<T>());
  auto dec = g->nodes()->create<loco::DepthwiseFilterDecode>();
  dec->input(input_for_decode);
  dec->decoder(std::move(decoder));
  return dec;
}
References EXO_ASSERT, loco::Node::graph(), and loco::DepthwiseFilterDecode::input().
make_dw_filter_decode< DepthwiseFilterLayout::HWCM >()
template loco::DepthwiseFilterDecode * exo::make_dw_filter_decode< DepthwiseFilterLayout::HWCM > (loco::Node * input_for_decode)
Referenced by exo::DepthwiseConv2DConverter::convert().
make_feature_decode()
template<FeatureLayout T> loco::FeatureDecode * exo::make_feature_decode (loco::Node * input_for_decode)
Creates a loco::FeatureDecode with T layout (NHWC for tflite) and add it to graph.
Definition at line 128 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_decode != nullptr, "input should not be nullptr");
  loco::Graph *g = input_for_decode->graph();
  auto decoder = std::make_unique<loco::PermutingDecoder<loco::Domain::Feature>>();
  decoder->perm(perm<T>());
  auto dec = g->nodes()->create<loco::FeatureDecode>();
  dec->input(input_for_decode);
  dec->decoder(std::move(decoder));
  return dec;
}
References EXO_ASSERT, loco::Node::graph(), and loco::FeatureDecode::input().
make_feature_decode< FeatureLayout::NHWC >()
template loco::FeatureDecode * exo::make_feature_decode< FeatureLayout::NHWC > (loco::Node * input_for_encode)
Referenced by exo::AvgPool2DConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MaxPool2DConverter::convert(), and exo::TransposedConv2DConverter::convert().
make_feature_encode()
template<FeatureLayout T> loco::FeatureEncode * exo::make_feature_encode (loco::Node * input_for_encode)
Creates a loco::FeatureEncode with T layout (NHWC for tflite) and add it to graph.
Definition at line 112 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_encode != nullptr, "input should not be nullptr");
  loco::Graph *g = input_for_encode->graph();
  auto encoder = std::make_unique<loco::PermutingEncoder<loco::Domain::Feature>>();
  encoder->perm(perm<T>());
  auto enc = g->nodes()->create<loco::FeatureEncode>();
  enc->input(input_for_encode);
  enc->encoder(std::move(encoder));
  return enc;
}
References EXO_ASSERT, loco::Node::graph(), and loco::FeatureEncode::input().
make_feature_encode< FeatureLayout::NHWC >()
template loco::FeatureEncode * exo::make_feature_encode< FeatureLayout::NHWC > (loco::Node * input_for_encode)
Referenced by exo::AvgPool2DConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MaxPool2DConverter::convert(), and exo::TransposedConv2DConverter::convert().
make_filter_decode()
template<FilterLayout T> loco::FilterDecode * exo::make_filter_decode (loco::Node * input_for_decode)
Create a loco::FilterDecode of given layout.
Definition at line 160 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_decode != nullptr, "filter should not be nullptr");
  loco::Graph *g = input_for_decode->graph();
  auto decoder = std::make_unique<loco::PermutingDecoder<loco::Domain::Filter>>();
  decoder->perm(perm<T>());
  auto dec = g->nodes()->create<loco::FilterDecode>();
  dec->input(input_for_decode);
  dec->decoder(std::move(decoder));
  return dec;
}
References EXO_ASSERT, loco::Node::graph(), and loco::FilterDecode::input().
make_filter_decode< FilterLayout::OHWI >()
template loco::FilterDecode * exo::make_filter_decode< FilterLayout::OHWI > (loco::Node * input_for_decode)
Referenced by exo::Conv2DConverter::convert(), and exo::TransposedConv2DConverter::convert().
make_filter_encode()
template<FilterLayout T> loco::FilterEncode * exo::make_filter_encode (loco::Node * input_for_encode)
Create a loco::FilterEncode of given layout.
Definition at line 144 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_encode != nullptr, "filter should not be nullptr");
  loco::Graph *g = input_for_encode->graph();
  auto encoder = std::make_unique<loco::PermutingEncoder<loco::Domain::Filter>>();
  encoder->perm(perm<T>());
  auto enc = g->nodes()->create<loco::FilterEncode>();
  enc->input(input_for_encode);
  enc->encoder(std::move(encoder));
  return enc;
}
References EXO_ASSERT, loco::Node::graph(), and loco::FilterEncode::input().
make_filter_encode< FilterLayout::HWIO >()
template loco::FilterEncode * exo::make_filter_encode< FilterLayout::HWIO > (loco::Node * input_for_encode)
make_matrix_decode()
template<MatrixLayout T> loco::MatrixDecode * exo::make_matrix_decode (loco::Node * input_for_decode)
Create a loco::MatrixDecode of given layout.
Definition at line 209 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_decode != nullptr, "input should not be nullptr");
  loco::Graph *g = input_for_decode->graph();
  auto decoder = std::make_unique<loco::PermutingDecoder<loco::Domain::Matrix>>();
  decoder->perm(perm<T>());
  auto dec = g->nodes()->create<loco::MatrixDecode>();
  dec->input(input_for_decode);
  dec->decoder(std::move(decoder));
  return dec;
}
References EXO_ASSERT, loco::Node::graph(), and loco::MatrixDecode::input().
make_matrix_decode< MatrixLayout::HW >()
template loco::MatrixDecode * exo::make_matrix_decode< MatrixLayout::HW > (loco::Node * input_for_decode)
Referenced by exo::MatMulConverter::convert().
make_matrix_decode< MatrixLayout::WH >()
template loco::MatrixDecode * exo::make_matrix_decode< MatrixLayout::WH > (loco::Node * input_for_decode)
Referenced by exo::MatMulConverter::convert().
make_matrix_encode()
template<MatrixLayout T> loco::MatrixEncode * exo::make_matrix_encode (loco::Node * input_for_encode)
Create a loco::MatrixEncode of given layout.
Definition at line 193 of file GraphBlock.cpp.
{
  EXO_ASSERT(input_for_encode != nullptr, "input should not be nullptr");
  loco::Graph *g = input_for_encode->graph();
  auto encoder = std::make_unique<loco::PermutingEncoder<loco::Domain::Matrix>>();
  encoder->perm(perm<T>());
  auto enc = g->nodes()->create<loco::MatrixEncode>();
  enc->input(input_for_encode);
  enc->encoder(std::move(encoder));
  return enc;
}
References EXO_ASSERT, loco::Node::graph(), and loco::MatrixEncode::input().
make_matrix_encode< MatrixLayout::HW >()
template loco::MatrixEncode * exo::make_matrix_encode< MatrixLayout::HW > (loco::Node * input_for_encode)
Referenced by exo::MatMulConverter::convert().
make_matrix_encode< MatrixLayout::WH >()
template loco::MatrixEncode * exo::make_matrix_encode< MatrixLayout::WH > (loco::Node * input_for_encode)
optimize()
void exo::optimize (loco::Graph *)
Run passes for a graph after completion of converting canonical nodes into TFL nodes.
TODO Separate optimize pass dedicated to TFL and Circle dialect when necessary
Definition at line 30 of file ExoOptimize.cpp.
{
  logo::Phase phase;
  {
    // prepare type and shape before optimization
    phase.emplace_back(std::make_unique<TypeInferencePass>());
    phase.emplace_back(std::make_unique<ShapeInferencePass>());
    phase.emplace_back(std::make_unique<FoldReshapeOfConstPass>());
    phase.emplace_back(std::make_unique<FoldTransposeOfConstPass>());
    if (get<Knob::UseFuseBiasAddPass>())
    {
      phase.emplace_back(std::make_unique<FuseBiasAddPass>());
    }
    if (get<Knob::UseFuseInstanceNormPass>())
    {
      phase.emplace_back(std::make_unique<FuseInstanceNormPass>());
    }
    if (get<Knob::UseFuseReluPass>())
    {
      phase.emplace_back(std::make_unique<FuseReluPass>());
    }
    phase.emplace_back(std::make_unique<FuseRsqrtPass>());
    if (get<Knob::UseFuseSquaredDifferencePass>())
    {
      phase.emplace_back(std::make_unique<FuseSquaredDifferencePass>());
    }
    phase.emplace_back(std::make_unique<MergeConcatNodesPass>());
    phase.emplace_back(std::make_unique<logo::RemoveDeadNodePass>());
  }
  logo::PhaseRunner<logo::PhaseStrategy::Restart> phase_runner{g};
  ProgressReporter prog(g, logo::PhaseStrategy::Restart);
  phase_runner.attach(&prog);
  phase_runner.run(phase);
}
References logo::Restart.
set()
void exo::set (Dialect d)
Definition at line 100 of file Knob.cpp.
{
  ::knob_loader().dialect_set(d);
  switch (d)
  {
    case Dialect::TFLITE:
#define KNOB_BOOL(NAME, TFL_DEFAULT, CIRCLE_DEFAULT, DESC) \
  ::knob_loader().knob_set(#NAME, TFL_DEFAULT);
#include "Knob.lst"
#undef KNOB_BOOL
      break;
    case Dialect::CIRCLE:
#define KNOB_BOOL(NAME, TFL_DEFAULT, CIRCLE_DEFAULT, DESC) \
  ::knob_loader().knob_set(#NAME, CIRCLE_DEFAULT);
#include "Knob.lst"
#undef KNOB_BOOL
      break;
    default:
      std::runtime_error("UnKnown dialect");
  }
}
References CIRCLE, and TFLITE.
to_circle_actfunc()
circle::ActivationFunctionType exo::to_circle_actfunc (locoex::FusedActFunc func)
Definition at line 24 of file CircleExporterUtils.cpp.
{
  switch (func)
  {
    case locoex::FusedActFunc::NONE:
      return circle::ActivationFunctionType_NONE;
    case locoex::FusedActFunc::RELU:
      return circle::ActivationFunctionType_RELU;
    case locoex::FusedActFunc::RELU6:
      return circle::ActivationFunctionType_RELU6;
    default:
      INTERNAL_EXN_V("trying to convert unsupported locoex::FusedActFunc", oops::to_uint32(func));
  }
}
References INTERNAL_EXN_V, locoex::NONE, locoex::RELU, locoex::RELU6, and oops::to_uint32().
to_shape_description() [1/7]
ShapeDescription exo::to_shape_description (const loco::BiasShape & shape)
Definition at line 91 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  res._dims.resize(1);
  res._dims.at(0) = shape.length().value();
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::BiasShape::length(), and loco::Dimension::value().
to_shape_description() [2/7]
ShapeDescription exo::to_shape_description (const loco::DepthwiseFilterShape & shape)
Definition at line 75 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  // T/F Lite encodes a depthwise convolution filter as a [1, H, W, C*M] tensor
  res._dims.resize(4);
  res._dims.at(0) = 1;
  res._dims.at(1) = shape.height().value();
  res._dims.at(2) = shape.width().value();
  res._dims.at(3) = shape.depth().value() * shape.multiplier().value();
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::DepthwiseFilterShape::depth(), loco::DepthwiseFilterShape::height(), loco::DepthwiseFilterShape::multiplier(), loco::Dimension::value(), and loco::DepthwiseFilterShape::width().
to_shape_description() [3/7]
ShapeDescription exo::to_shape_description (const loco::FeatureShape & shape)
Definition at line 43 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  // T/F Lite encodes a feature map as a NHWC tensor
  res._dims.resize(4);
  res._dims.at(0) = shape.count().value();
  res._dims.at(1) = shape.height().value();
  res._dims.at(2) = shape.width().value();
  res._dims.at(3) = shape.depth().value();
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::FeatureShape::count(), loco::FeatureShape::depth(), loco::FeatureShape::height(), loco::Dimension::value(), and loco::FeatureShape::width().
to_shape_description() [4/7]
ShapeDescription exo::to_shape_description (const loco::FilterShape & shape)
Definition at line 59 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  // T/F Lite encodes a convolution filter as a NHWC tensor
  res._dims.resize(4);
  res._dims.at(0) = shape.count().value();
  res._dims.at(1) = shape.height().value();
  res._dims.at(2) = shape.width().value();
  res._dims.at(3) = shape.depth().value();
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::FilterShape::count(), loco::FilterShape::depth(), loco::FilterShape::height(), loco::Dimension::value(), and loco::FilterShape::width().
to_shape_description() [5/7]
ShapeDescription exo::to_shape_description (const loco::MatrixShape & shape)
Definition at line 103 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  res._dims.resize(2);
  res._dims.at(0) = shape.height().value();
  res._dims.at(1) = shape.width().value();
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::MatrixShape::height(), loco::Dimension::value(), and loco::MatrixShape::width().
to_shape_description() [6/7]
ShapeDescription exo::to_shape_description (const loco::NodeShape & shape)
Definition at line 116 of file ExporterUtils.cpp.
{
  switch (shape.domain())
  {
    case loco::Domain::Tensor:
      return to_shape_description(shape.as<loco::TensorShape>());
    case loco::Domain::Feature:
      return to_shape_description(shape.as<loco::FeatureShape>());
    case loco::Domain::Filter:
      return to_shape_description(shape.as<loco::FilterShape>());
    case loco::Domain::DepthwiseFilter:
      return to_shape_description(shape.as<loco::DepthwiseFilterShape>());
    case loco::Domain::Bias:
      return to_shape_description(shape.as<loco::BiasShape>());
    case loco::Domain::Matrix:
      return to_shape_description(shape.as<loco::MatrixShape>());
    default:
      break;
  }
  INTERNAL_EXN_V("Unsupported loco domain", oops::to_uint32(shape.domain()));
}
References loco::NodeShape::as(), loco::Bias, loco::DepthwiseFilter, loco::NodeShape::domain(), loco::Feature, loco::Filter, INTERNAL_EXN_V, loco::Matrix, loco::Tensor, to_shape_description(), and oops::to_uint32().
to_shape_description() [7/7]
ShapeDescription exo::to_shape_description (const loco::TensorShape & shape)
Definition at line 26 of file ExporterUtils.cpp.
{
  ShapeDescription res;
  res._rank_known = true;
  res._dims.resize(shape.rank());
  for (uint32_t axis = 0; axis < shape.rank(); ++axis)
  {
    // All the dimensions SHOULD be known
    assert(shape.dim(axis).known());
    res._dims.at(axis) = shape.dim(axis).value();
  }
  return res;
}
References exo::ShapeDescription::_dims, exo::ShapeDescription::_rank_known, loco::TensorShape::dim(), loco::Dimension::known(), loco::TensorShape::rank(), and loco::Dimension::value().
Referenced by exo::ShapeInference::get(), and to_shape_description().
to_tflite_actfunc()
tflite::ActivationFunctionType exo::to_tflite_actfunc (locoex::FusedActFunc func)
Definition at line 24 of file TFLExporterUtils.cpp.
{
  switch (func)
  {
    case locoex::FusedActFunc::NONE:
      return tflite::ActivationFunctionType_NONE;
    case locoex::FusedActFunc::RELU:
      return tflite::ActivationFunctionType_RELU;
    case locoex::FusedActFunc::RELU6:
      return tflite::ActivationFunctionType_RELU6;
    default:
      INTERNAL_EXN_V("Unsupported locoex FusedActFunc Type", oops::to_uint32(func));
  }
}
References INTERNAL_EXN_V, locoex::NONE, locoex::RELU, locoex::RELU6, and oops::to_uint32().