ONE - On-device Neural Engine: nnfw::cker::functor Namespace Reference
nnfw::cker::functor Namespace Reference
Data Structures
struct BroadcastTo
struct FillFunctor
struct FillFunctor< Eigen::ThreadPoolDevice, T >
struct FillPhiloxRandom
struct FillPhiloxRandom< CPUDevice, Distribution >
struct FillPhiloxRandomTask
struct FillPhiloxRandomTask< Distribution, false >
struct FillPhiloxRandomTask< Distribution, true >
struct InflateFunctor
struct ReduceFunctor
struct ReduceOuterDimensions
struct SetZeroFunctor
struct StrideFunctor
Typedefs
typedef Eigen::ThreadPoolDevice CPUDevice
Functions
void biasReductionHelper (float *input_backprop_buffer, const Shape &input_backprop_shape, float *bias_grad_buffer, const Shape &bias_grad_shape)
Typedef Documentation
CPUDevice
typedef Eigen::ThreadPoolDevice nnfw::cker::functor::CPUDevice
Definition at line 37 of file RandomOp.h.
Function Documentation
biasReductionHelper()
void nnfw::cker::functor::biasReductionHelper (float * input_backprop_buffer, const Shape & input_backprop_shape, float * bias_grad_buffer, const Shape & bias_grad_shape)
Definition at line 193 of file redux_functor.h.
{
  assert(input_backprop_buffer);
  assert(bias_grad_buffer);
  const nnfw::cker::functor::ReduceOuterDimensions<Eigen::ThreadPoolDevice, float, float, float,
                                                   Eigen::internal::scalar_sum_op<float>>
    redux;
  const Tensor input_backprop_t{input_backprop_shape, static_cast<void *>(input_backprop_buffer)};
  Tensor bias_grad_t{bias_grad_shape, bias_grad_buffer};
  int outer = 1;
  for (int i = 0; i < input_backprop_shape.DimensionsCount() - 1; ++i)
    outer *= input_backprop_shape.Dims(i);
  int inner = input_backprop_shape.Dims(input_backprop_shape.DimensionsCount() - 1);
  redux(*eigen_support::GetThreadPoolDevice(), Eigen::DSizes<Eigen::Index, 2>{outer, inner},
        input_backprop_t, &bias_grad_t);
}
References nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::Dims(), and nnfw::cker::eigen_support::GetThreadPoolDevice().
Referenced by onert::backend::train::ops::biasGrad().