ONE - On-device Neural Engine: loco Namespace Reference
loco Namespace Reference
Data Structures
class AnnotatedItem
class AvgPool2D
2D Average Pooling
class BiasAdd
Produce a value of domain D from an input value (of domain D) and a bias.
class BiasAdd< Domain::Feature >
Add Feature and Bias along "depth" axis.
class BiasAdd< Domain::Tensor >
Add Tensor and Bias.
class BiasDecode
Create a "Tensor" from a "Bias".
class BiasEncode
Create a "Bias" from a "Tensor".
class BiasShape
Bias Shape.
class CanonicalDialect
A singleton for Canonical Dialect.
struct CanonicalNode
struct CanonicalNodeDef
struct CanonicalNodeMutableVisitor
struct CanonicalNodeMutableVisitorBase
struct CanonicalNodeVisitor
struct CanonicalNodeVisitorBase
struct CanonicalShapeInferenceRule
Shape inference rule for canonical dialect.
struct CanonicalTypeInferenceRule
Type Inference Rule for Canonical Dialect.
class ConstGen
Create a value from constant byte array.
class Conv2D
2D Spatial Convolution
struct DataTypeImpl
C++ scalar type corresponding to each DataType.
struct DataTypeImpl< DataType::BOOL >
struct DataTypeImpl< DataType::FLOAT16 >
struct DataTypeImpl< DataType::FLOAT32 >
struct DataTypeImpl< DataType::FLOAT64 >
struct DataTypeImpl< DataType::S16 >
struct DataTypeImpl< DataType::S32 >
struct DataTypeImpl< DataType::S64 >
struct DataTypeImpl< DataType::S8 >
struct DataTypeImpl< DataType::STRING >
struct DataTypeImpl< DataType::U16 >
struct DataTypeImpl< DataType::U32 >
struct DataTypeImpl< DataType::U64 >
struct DataTypeImpl< DataType::U8 >
class DepthwiseConv2D
Depthwise 2D Convolution.
class DepthwiseFilterDecode
Create a tensor from a depthwise filter.
struct DepthwiseFilterDecoder
Describe how to build a tensor from a depthwise convolution filter.
class DepthwiseFilterEncode
Create a depthwise filter from a tensor.
struct DepthwiseFilterEncoder
Describe how to build a depthwise convolution filter from a tensor.
class DepthwiseFilterIndex
DepthwiseFilter Index.
class DepthwiseFilterShape
DepthwiseFilter Shape.
class Dialect
Dialect interface.
struct DialectService
Dialect Service interface.
class Dimension
The value of one dimension in a tensor shape.
class EltwiseAdd
Elementwise Add lhs and rhs.
class EltwiseDiv
Elementwise Div lhs and rhs.
class EltwiseMax
Elementwise Maximum of lhs and rhs.
class EltwiseMul
Elementwise Mul lhs and rhs.
class EltwiseSqrt
Elementwise Sqrt of input.
class EltwiseSub
Elementwise Sub lhs and rhs.
class ErrorDetail
The details of each error.
class ErrorDetail< ErrorCategory::MissingArgument >
The details of MissingArgument error.
struct ErrorListener
Error listener (with default implementation)
class FeatureDecode
Create a tensor from a feature map.
struct FeatureDecoder
Describe how to build a tensor from a (convolution) feature map.
class FeatureEncode
Create a feature map from a tensor.
struct FeatureEncoder
Decribe how to build a (convolution) feature map from a tensor.
class FeatureIndex
Feature Index.
class FeatureShape
Feature Map Shape.
class FilterDecode
Create a tensor from a filter.
struct FilterDecoder
Decribe how to build a a tensor from a filter.
class FilterEncode
Create a filter from a tensor.
struct FilterEncoder
Decribe how to build a (convolution) filter from a tensor.
class FilterIndex
Filter Index.
class FilterShape
Filter Shape.
struct FixedArity
class Forward
Create a new value identical to its input.
class Graph
A neural network graph.
class GraphInput
Graph-level Input Metadata.
struct GraphInputIndexQueryService
class GraphOutput
Graph-level Output Metadata.
struct GraphOutputIndexQueryService
struct IErrorListener
Error listener interface.
class MatMul
Matrix Multiplication lhs and rhs.
class MatrixDecode
Create Tensor from Matrix.
struct MatrixDecoder
Describe how to build a tensor from a matrix.
class MatrixEncode
Create Matrix from Tensor.
struct MatrixEncoder
Decribe how to build a matrix from a tensor.
class MatrixIndex
Matrix Index.
class MatrixShape
Matrix Shape.
class MaxPool2D
2D Max Pooling
class Mixin
class Mixin< Trait::DataTyped >
class Mixin< Trait::TensorShaped >
class MultiDialectShapeInferenceRule
Shape inference rule for multiple dialects.
class MultiDialectTypeInferenceRule
Type Inference Rule for multiple dialects.
class NamedEntity
Trait for elements with name.
class Node
Logical unit of computation.
struct NodeAnnotation
Extensible Node Metadata.
class NodeMixin
class NodeMixin< NodeTrait::DataType >
class NodeMixin< NodeTrait::TensorShape >
class NodePool
class NodeShape
class ObjectPool
Object Pool.
class Padding2D
class PaddingND
class Permutation
class Permutation< Domain::DepthwiseFilter >
Mapping between DepthwiseFilter/Tensor Axis.
class Permutation< Domain::Feature >
Mapping between Feature/Tensor Axis.
class Permutation< Domain::Filter >
Mapping between Filter/Tensor Axis.
class Permutation< Domain::Matrix >
Mapping between Matrix/Tensor Axis.
class PermutingDecoder
class PermutingDecoder< Domain::DepthwiseFilter >
Permutation-based DepthwiseFilter-to-Tensor converter.
class PermutingDecoder< Domain::Feature >
class PermutingDecoder< Domain::Filter >
Permutation-based Filter-to-Tensor converter.
class PermutingDecoder< Domain::Matrix >
Permutation-based Matrix-to-Tensor converter.
class PermutingEncoder
class PermutingEncoder< Domain::DepthwiseFilter >
Permutation-based Tensor-to-DepthwiseFilter converter.
class PermutingEncoder< Domain::Feature >
class PermutingEncoder< Domain::Filter >
Permutation-based Tensor-to-Filter converter.
class PermutingEncoder< Domain::Matrix >
Permutation-based Tensor-to-Matrix converter.
class Pull
Create a value from user data.
class Push
Make a value visible to user.
class ReLU
Create a new value that rectifies its input.
class ReLU6
Create a new value that rectifies its input capping the units at 6.
class Reshape
class Reshape< ReshapeType::Fixed >
Reshape a tensor to another tensor whose shape is known at compile time.
struct ShapeInference
struct ShapeInferenceRule
class ShapeInferenceSession
class Softmax
Computes softmax activations.
class Softmax< Domain::Tensor >
Computes softmax activations for Tensor domain.
class Stride
Stride configuration for N-dimensional spatial operations.
class Stride< 2 >
Stride configuration for 2D spatial operations.
class Subst
class Subst< SubstQualifier::Default >
A helper for below "replace" helper.
class Tanh
Create a new value that rectifies its input by tanh.
class TensorAxisSet
class TensorBroadcast
Duplicate elements along specified axes.
class TensorConcat
Concatenate two tensors.
class TensorConstantPad
Pads a tensor with constant value.
class TensorReduce
Computes ReduceFunc operations for Tensor domain.
class TensorShape
class TensorTranspose
Permute an input.
class TransposedConv2D
2D Transposed Convolution
struct TypeInference
struct TypeInferenceRule
class TypeInferenceSession
class Use
The edge between a node definition and its user.
class Window
ND Receptive Field Shape.
class Window< 2 >
2D Receptive Field Shape
struct With
Typedefs
using GraphInputIndex = uint32_t
using GraphOutputIndex = uint32_t
using FixedReshape = Reshape< ReshapeType::Fixed >
using TensorSoftmax = Softmax< Domain::Tensor >
using TensorBiasAdd = BiasAdd< Domain::Tensor >
using FeatureBiasAdd = BiasAdd< Domain::Feature >
using TensorAxis = uint32_t
using TensorIndex = nncc::core::ADT::tensor::Index
Enumerations
enum class CanonicalOpcode { CANONICAL_NODE }
Canonical Node Opcode.
enum class DataType {
Unknown , U8 , U16 , U32 ,
U64 , S8 , S16 , S32 ,
S64 , FLOAT16 , FLOAT32 , FLOAT64 ,
BOOL , STRING
}
"scalar" value type
enum class DepthwiseFilterAxis { Depth , Multiplier , Height , Width }
enum class Domain {
Unknown , Tensor , Feature , Filter ,
DepthwiseFilter , Bias , Matrix
}
Describe the kind of (N-dimensional) loco values.
enum class FeatureAxis { Count , Depth , Height , Width }
enum class FilterAxis { Count , Depth , Height , Width }
enum class Trait { DataTyped , TensorShaped }
enum class MatrixAxis { Height , Width }
enum class SubstQualifier { Default }
enum class NodeTrait { DataType , TensorShape }
enum class ReshapeType { Fixed }
enum class ReduceFunc { Mean }
Reduce type functions.
enum class ErrorCategory { MissingArgument }
Possible error categories.
Functions
std::ostream & operator<< (std::ostream &os, const loco::FeatureShape &feature_shape)
dump FeatureShape values to stream
std::ostream & operator<< (std::ostream &os, const loco::FilterShape &filter_shape)
dump FilterShape values to stream
std::ostream & operator<< (std::ostream &os, const loco::TensorShape &tensor_shape)
dump TensorShape values to stream
std::ostream & operator<< (std::ostream &os, const loco::Padding2D &pad)
dump Padding2D values to stream
std::vector< loco::Node * > postorder_traversal (const std::vector< loco::Node * > &roots)
Generate postorder traversal sequence starting from "roots".
std::set< loco::Node * > active_nodes (const std::vector< loco::Node * > &roots)
Enumerate all the nodes required to compute "roots".
template<typename T , typename ARG >
T _must_cast (ARG arg)
uint32_t size (DataType data_type)
Returns the size of the data type.
bool operator== (const Dimension &, const Dimension &)
Equality operator between two Dimensions.
bool operator== (const Dimension &, uint32_t)
bool operator== (uint32_t, const Dimension &)
Dimension make_dimension (void)
Make an "unknown" dimension.
template<typename T >
T must_cast (FeatureEncoder *node)
A helper dynamic_cast that throws when failed.
template<typename T >
T must_cast (const FeatureEncoder *node)
template<typename T >
T must_cast (FeatureDecoder *node)
template<typename T >
T must_cast (const FeatureDecoder *node)
template<typename T >
T must_cast (FilterEncoder *node)
A helper dynamic_cast that throws when failed.
template<typename T >
T must_cast (const FilterEncoder *node)
std::vector< Node * > input_nodes (const Graph *)
std::vector< Node * > output_nodes (Graph *)
std::set< Node * > all_nodes (Graph *)
Enumerate all the nodes in a given graph.
std::unique_ptr< Graph > make_graph (void)
std::set< Node * > preds (const Node *node)
Enumerate all the predecessors of a given node.
std::set< Node * > succs (const Node *node)
Enumerate all the successors of a given node.
Subst< SubstQualifier::Default > replace (Node *node)
template<typename T >
T must_cast (Node *node)
A helper dynamic_cast that throws when failed.
template<typename T >
T must_cast (const Node *node)
void link (GraphOutput *, Push *push)
Push * push_node (Graph *g, const GraphOutputIndex &index)
Find a Push node with a given output index.
void link (GraphInput *, Pull *pull)
Pull * pull_node (Graph *g, const GraphInputIndex &index)
Find a Pull node with a given input index.
bool operator== (const NodeShape &lhs, const NodeShape &rhs)
uint32_t element_count (const loco::TensorShape *tensor_shape)
Return the number of elements in a tensor of given shape.
bool operator== (const TensorShape &lhs, const TensorShape &rhs)
'==' operator for TensorShape
bool valid (Graph *g, std::unique_ptr< ErrorListener > &&l=nullptr)
Validate a loco graph.
ShapeInferenceSession apply (ShapeInferenceRule *r)
bool shape_known (const Node *node)
NodeShape shape_get (const Node *node)
void shape_erase (Node *node)
TypeInferenceSession apply (TypeInferenceRule *r)
bool dtype_known (const Node *node)
DataType dtype_get (const Node *node)
void dtype_erase (Node *node)
INSTANTIATE (DataType::S32)
INSTANTIATE (DataType::FLOAT32)
std::ostream & operator<< (std::ostream &os, const loco::Dimension &d)
Detailed Description
Push
Pull
ConstGen
TensorBroadcast
Typedef Documentation
FeatureBiasAdd
using loco::FeatureBiasAdd = typedef BiasAdd<Domain::Feature>
Definition at line 829 of file Nodes.h.
FixedReshape
using loco::FixedReshape = typedef Reshape<ReshapeType::Fixed>
Definition at line 523 of file Nodes.h.
GraphInputIndex
using loco::GraphInputIndex = typedef uint32_t
Definition at line 25 of file GraphInputIndex.h.
GraphOutputIndex
using loco::GraphOutputIndex = typedef uint32_t
Definition at line 25 of file GraphOutputIndex.h.
TensorAxis
using loco::TensorAxis = typedef uint32_t
Definition at line 25 of file TensorAxis.h.
TensorBiasAdd
using loco::TensorBiasAdd = typedef BiasAdd<Domain::Tensor>
Definition at line 806 of file Nodes.h.
TensorIndex
using loco::TensorIndex = typedef nncc::core::ADT::tensor::Index
Definition at line 26 of file TensorIndex.h.
TensorSoftmax
using loco::TensorSoftmax = typedef Softmax<Domain::Tensor>
Definition at line 737 of file Nodes.h.
Enumeration Type Documentation
CanonicalOpcode
enum class loco::CanonicalOpcode strong
Canonical Node Opcode.
WARNING The order is subject to change. DO NOT serialize this value.
Enumerator
CANONICAL_NODE
Definition at line 28 of file CanonicalOpcode.h.
{
#define CANONICAL_NODE(OPCODE, CLASS) OPCODE,
#include "CanonicalNodes.lst"
#undef CANONICAL_NODE
};
DataType
enum class loco::DataType strong
"scalar" value type
Enumerator
Unknown
U8
U16
U32
U64
S8
S16
S32
S64
FLOAT16
FLOAT32
FLOAT64
BOOL
STRING
Definition at line 26 of file DataType.h.
{
  Unknown, // Unknown type (serves as a default value)
  U8,  // 8-bit unsigned integer
  U16, // 16-bit unsigned integer
  U32, // 32-bit unsigned integer
  U64, // 64-bit unsigned integer
  S8,  // 8-bit signed integer
  S16, // 16-bit signed integer
  S32, // 32-bit signed integer
  S64, // 64-bit signed integer
  FLOAT16, // IEEE 16-bit floating-point
  FLOAT32, // IEEE 32-bit floating-point
  FLOAT64, // IEEE 64-bit floating-point
  // WARNING the size of Bool may vary for NN frameworks
  // TODO we need to find a way to resolve this issue
  BOOL, // Boolean
  // WARNING STRING is NOT fully supported yet
  STRING, // String
};
DepthwiseFilterAxis
enum class loco::DepthwiseFilterAxis strong
Enumerator
Depth
Multiplier
Height
Width
Definition at line 23 of file DepthwiseFilterAxis.h.
{
  Depth,
  Multiplier,
  Height,
  Width
};
Domain
enum class loco::Domain strong
Describe the kind of (N-dimensional) loco values.
loco is an intermediate representation for neural network compiler, which mainly focuses on N-dimensional values (usually referred to as Tensor).
There are several special cases for N-dimensional values according to its usage. For example, vision community often refers to 4D array as "FeatureMap".
It is definitely possible to represent all of these special cases using Tensor, but that scheme may introduces some confusion (e.g. NCHW vs NHWC issue).
loco distinguishes these special cases from Tensor in order to reduce such confusion.
This "Domain" enum class enumerates all of these special cases that loco supports.
Enumerator
Unknown
Tensor
Feature
Filter
DepthwiseFilter
Bias
Matrix
Definition at line 39 of file Domain.h.
{
  Unknown,
  Tensor,
  Feature,
  Filter,          /* 2D Convolution Filter */
  DepthwiseFilter, /* Depthwise 2D Convolution Filter */
  Bias,
  Matrix,
  /* ... */
};
ErrorCategory
enum class loco::ErrorCategory strong
Possible error categories.
This enum class enumerates all the possible validation failure reasons.
WARN DO NOT serialize this code. The tag value is subject to change.
Enumerator
MissingArgument
Definition at line 34 of file Verifier.h.
{
  MissingArgument,
  /* TO BE ADDED */
};
FeatureAxis
enum class loco::FeatureAxis strong
Enumerator
Count
Depth
Height
Width
Definition at line 23 of file FeatureAxis.h.
{
  Count,
  Depth,
  Height,
  Width
};
FilterAxis
enum class loco::FilterAxis strong
Enumerator
Count
Depth
Height
Width
Definition at line 23 of file FilterAxis.h.
{
  Count,
  Depth,
  Height,
  Width
};
MatrixAxis
enum class loco::MatrixAxis strong
Enumerator
Height
Width
Definition at line 23 of file MatrixAxis.h.
{
  Height,
  Width
};
NodeTrait
enum class loco::NodeTrait strong
Enumerator
DataType
TensorShape
Definition at line 30 of file NodeMixins.h.
{
  DataType,
  // Nodes with TensorShape trait will provide the following methods:
  // - rank()
  // - rank(value)
  // - dim()
  // - dim(value)
  // - shape({...})
  TensorShape,
};
ReduceFunc
enum class loco::ReduceFunc strong
Reduce type functions.
Enumerator
Mean
Definition at line 608 of file Nodes.h.
{
  Mean, // ReduceMean
  // TODO Support other reduce operations
};
ReshapeType
enum class loco::ReshapeType strong
Enumerator
Fixed
Definition at line 489 of file Nodes.h.
{
  Fixed, // shape is known at compile time
  // Add another type for a case when shape is not known at compile time
};
SubstQualifier
enum class loco::SubstQualifier strong
Enumerator
Default
Definition at line 43 of file Node.h.
{
  Default, // Replace all the occurrences as "Use" (by default)
};
Trait
enum class loco::Trait strong
Enumerator
DataTyped
TensorShaped
Definition at line 39 of file Graph.h.
{
  // Any "DataTyped" class has the following methods
  // - DataType dtype(void) const;
  // - void dtype(const DataType &value);
  DataTyped,
  // Any "TensorShaped" class has the following methods
  // - const TensorShape *shape(void) const;
  // - void shape(std::unique_ptr<TensorShape> &&);
  // - void shape(std::initializer_list<Dimension> &&);
  //
  // TODO Rename NodeMixin::TensorShape as NodeMixin::NDShape
  TensorShaped,
};
Function Documentation
_must_cast()
template<typename T , typename ARG > T loco::_must_cast (ARG arg)
Definition at line 28 of file CastHelpers.h.
{
  auto cast_arg = dynamic_cast<T>(arg);
  if (cast_arg == nullptr)
  {
    std::string msg = "loco::must_cast() failed to cast: ";
    msg += typeid(T).name();
    throw std::invalid_argument(msg.c_str());
  }
  return cast_arg;
}
active_nodes()
std::set< loco::Node * > loco::active_nodes (const std::vector< loco::Node * > & roots)
Enumerate all the nodes required to compute "roots".
Definition at line 112 of file Algorithm.cpp.
{
  // This implementation works but may be inefficient
  //
  // TODO Use efficient implementation if necessary
  auto nodes = postorder_traversal(roots);
  return std::set<loco::Node *>{nodes.begin(), nodes.end()};
}
References postorder_traversal().
Referenced by moco::test::find_nodes_bytype(), luci::DeadNodeQueryServiceImpl::isDeadNode(), luci::layer_info_map(), luci::CircleQuantizer::quantize(), mpqsolver::bisection::BisectionSolver::run(), logo::RemoveDeadNodePass::run(), logo::RemoveDeadNodeWithQueryPass::run(), exo::FoldReshapeOfConstPass::run(), exo::FoldTransposeOfConstPass::run(), exo::FuseBiasAddPass::run(), exo::FuseInstanceNormPass::run(), exo::FuseReluPass::run(), exo::FuseRsqrtPass::run(), exo::FuseSquaredDifferencePass::run(), logo::SimplifyDomainConversionPass::run(), luci::ConvertNCHWToNHWCPass::run(), luci::ConvertToFakeQuantizedModelPass::run(), luci::ExpandBroadcastConstPass::run(), luci::FoldAddV2Pass::run(), luci::FoldCastPass::run(), luci::FoldDensifyPass::run(), luci::FoldDepthwiseConv2DPass::run(), luci::FoldDequantizePass::run(), luci::FoldFullyConnectedPass::run(), luci::FoldGatherPass::run(), luci::FoldSparseToDensePass::run(), luci::ForwardReshapeToUnaryOpPass::run(), luci::ForwardTransposeOpPass::run(), luci::FuseActivationFunctionPass::run(), luci::FuseAddWithFullyConnectedPass::run(), luci::FuseAddWithTConvPass::run(), luci::FuseBatchNormWithConvPass::run(), luci::FuseBatchNormWithDwConvPass::run(), luci::FuseBatchNormWithTConvPass::run(), luci::FuseInstanceNormPass::run(), luci::FuseMeanWithMeanPass::run(), luci::FusePreActivationBatchNormPass::run(), luci::FusePReluPass::run(), luci::FuseTransposeWithMeanPass::run(), luci::MakeBatchNormGammaPositivePass::run(), luci::PropagateQParamForwardPass::run(), luci::RemoveDuplicateConstPass::run(), luci::RemoveFakeQuantPass::run(), luci::RemoveQuantDequantSeqPass::run(), luci::RemoveRedundantDequantizePass::run(), luci::RemoveRedundantReshapePass::run(), luci::RemoveRedundantTransposePass::run(), luci::RemoveUnnecessaryReshapeNetPass::run(), luci::RemoveUnnecessaryReshapePass::run(), luci::RemoveUnnecessarySlicePass::run(), luci::RemoveUnnecessarySplitPass::run(), luci::RemoveUnnecessaryStridedSlicePass::run(), luci::ReplaceMulAddWithDepthwiseConvPass::run(), luci::ReplaceNonConstFCWithBatchMatMulPass::run(), luci::ReplaceSubWithAddPass::run(), luci::ResolveCustomOpAddPass::run(), luci::ResolveCustomOpBatchMatMulPass::run(), luci::ResolveCustomOpMatMulPass::run(), luci::ResolveCustomOpMaxPoolWithArgmaxPass::run(), luci::ResolveCustomOpSplitVPass::run(), luci::ShuffleWeightTo16x1Float32Pass::run(), luci::SparsifyTensorPass::run(), luci::SubstitutePackToReshapePass::run(), luci::SubstitutePadV2ToPadPass::run(), luci::SubstituteSplitVToSplitPass::run(), luci::SubstituteSqueezeToReshapePass::run(), luci::SubstituteStridedSliceToReshapePass::run(), luci::SubstituteTransposeToReshapePass::run(), luci::TransformMinMaxToRelu6Pass::run(), luci::TransformMinReluToRelu6Pass::run(), luci::UnrollUnidirectionalSequenceLSTMPass::run(), exo::CanonicalNodeConverter< CanonicalType >::run(), exo::TensorBroadcastConverter::run(), exo::MergeConcatNodesPass::run(), luci::CopyQuantParamPass::run(), luci::ForceQuantParamPass::run(), luci::QuantizeDequantizeWeightsPass::run(), luci::QuantizeWithMinMaxPass::run(), luci::RequantizePass::run(), luci::QuantizePreCheckerPass::run(), moco::tf::SimpleNodeTransform< ConcreteNode >::run(), moco::ConstantFoldAdd::run(), moco::ConstantFoldMul::run(), moco::ConstantFoldPack::run(), moco::ConstantFoldStridedSlice::run(), moco::FuseBinaryIntoPreceding::run(), moco::ResolveConstantShape::run(), moco::ResolveFusedBatchNorm::run(), moco::ResolveReshapeWildcardDim::run(), moco::ResolveSquaredDifference::run(), moco::SqueezeReduceNode::run(), and luci::QuantizedModelVerifier::verify().
all_nodes()
std::set< loco::Node * > loco::all_nodes (loco::Graph * g)
Enumerate all the nodes in a given graph.
NOTE This method returns std::set<Node *> unlike input_nodes and output_nodes.
Please use traverse algorithms that "Algorithm.h" provides (such as postorder_traversal) if order is relevant for implementation.
Definition at line 59 of file Graph.cpp.
{
  std::set<loco::Node *> res;
  for (uint32_t n = 0; n < g->nodes()->size(); ++n)
  {
    res.insert(g->nodes()->at(n));
  }
  return res;
}
References size().
Referenced by locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), luci::Importer::importModule(), luci::inference_candidates(), luci_interpreter::GraphLoader::loadOperators(), logo::RemoveDeadNodePass::run(), logo::RemoveDeadNodeWithQueryPass::run(), logo::RemoveForwardNodePass::run(), moco::RemoveTFIdentityNode::run(), and luci::QuantizeWithMinMaxPass::run().
apply() [1/2]
ShapeInferenceSession loco::apply (ShapeInferenceRule * r) inline
Definition at line 51 of file ShapeInference.h.
{ return ShapeInferenceSession{r}; }
Referenced by exo::convert_to_TFLNodes(), exo::ShapeInferencePass::run(), exo::TypeInferencePass::run(), moco::tf::ShapeInferencePass::run(), and moco::tf::TypeInferencePass::run().
apply() [2/2]
TypeInferenceSession loco::apply (TypeInferenceRule * r) inline
Definition at line 99 of file TypeInference.h.
{ return TypeInferenceSession{r}; }
dtype_erase()
void loco::dtype_erase (Node * node) inline
Definition at line 110 of file TypeInference.h.
{ TypeInference::erase(node); }
References loco::TypeInference::erase().
dtype_get()
DataType loco::dtype_get (const Node * node) inline
Definition at line 109 of file TypeInference.h.
{ return TypeInference::get(node); }
References loco::TypeInference::get().
Referenced by exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MatMulConverter::convert(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), and exo::circle_detail::TypeInference::get().
dtype_known()
bool loco::dtype_known (const Node * node) inline
Definition at line 108 of file TypeInference.h.
{ return TypeInference::known(node); }
References loco::TypeInference::known().
Referenced by exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MatMulConverter::convert(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), exo::circle_detail::TypeInference::get(), and loco::TypeInferenceSession::to().
element_count()
uint32_t loco::element_count (const loco::TensorShape * tensor_shape)
Return the number of elements in a tensor of given shape.
NOTE 1.
"volume" returns 1 if the rank is 0.
NOTE 2.
"caller" SHOULD pass a valid shape that has no unknown dimension.
The behavior of "volume" on invalid is undefined.
Definition at line 24 of file TensorShape.cpp.
{
  uint32_t res = 1;
  for (uint32_t axis = 0; axis < tensor_shape->rank(); ++axis)
  {
    // Let's use "assert" here as "caller" is responsible for this check.
    // Please refer to the header for details.
    assert(tensor_shape->dim(axis).known());
    res *= tensor_shape->dim(axis).value();
  }
  return res;
}
References loco::TensorShape::dim(), loco::Dimension::known(), loco::TensorShape::rank(), and loco::Dimension::value().
input_nodes()
std::vector< Node * > loco::input_nodes (const Graph * g)
Definition at line 71 of file Graph.cpp.
{
  std::map<GraphInputIndex, loco::Node *> table;
  for (uint32_t n = 0; n < g->nodes()->size(); ++n)
  {
    auto node = g->nodes()->at(n);
    if (auto service = node->dialect()->service<GraphInputIndexQueryService>())
    {
      if (service->associated(node))
      {
        auto input_index = service->index(node);
        assert(table.find(input_index) == table.end());
        table[input_index] = node;
      }
    }
  }
  std::vector<loco::Node *> res;
  for (uint32_t n = 0; n < g->inputs()->size(); ++n)
  {
    auto it = table.find(n);
    res.emplace_back(it == table.end() ? nullptr : it->second);
  }
  return res;
}
References size().
Referenced by mpqsolver::bisection::compute_depth(), entry(), luci_interpreter::GraphLoader::initInputOutputTensors(), luci::DeadNodeQueryServiceImpl::isDeadNode(), record_minmax::RecordMinMax::profileData(), record_minmax::RecordMinMax::profileDataInParallel(), record_minmax::RecordMinMax::profileDataWithRandomInputs(), record_minmax::RecordMinMax::profileRawData(), record_minmax::RecordMinMax::profileRawDataDirectory(), mpqsolver::bisection::BisectionSolver::run(), prunner::PModelsRunner::run(), dalgona::Dalgona::runAnalysisWithH5Input(), dalgona::Dalgona::runAnalysisWithRandomInput(), and dalgona::PythonHooks::startNetworkExecution().
INSTANTIATE() [1/2]
loco::INSTANTIATE (DataType::FLOAT32)
INSTANTIATE() [2/2]
loco::INSTANTIATE (DataType::S32)
link() [1/2]
void loco::link (GraphInput * input, Pull * pull)
Definition at line 160 of file Nodes.cpp.
{ pull->index(input->index()); }
References loco::Pull::index().
link() [2/2]
void loco::link (GraphOutput * output, Push * push)
Definition at line 65 of file Nodes.cpp.
{ push->index(output->index()); }
References loco::Push::index().
Referenced by GraphTestcase< GraphCode::AvgPool2D >::GraphTestcase(), GraphTestcase< GraphCode::MaxPool2D >::GraphTestcase(), GraphTestcase< GraphCode::TensorConcat >::GraphTestcase(), GraphTestcase< GraphCode::TensorTranspose >::GraphTestcase(), InputLayer::operator()(), OutputLayer::operator()(), exo::test::TestGraph::TestGraph(), and mir2loco::Transformer::visit().
make_dimension()
Dimension loco::make_dimension (void)
Make an "unknown" dimension.
Definition at line 30 of file Dimension.cpp.
{ return Dimension{}; }
make_graph()
std::unique_ptr< Graph > loco::make_graph (void)
Definition at line 131 of file Graph.cpp.
{ return std::unique_ptr<Graph>{new Graph}; }
Referenced by GraphTestcase< GraphCode::ConstGen >::GraphTestcase(), GraphTestcase< GraphCode::Relu >::GraphTestcase(), GraphTestcase< GraphCode::FixedReshape >::GraphTestcase(), GraphTestcase< GraphCode::TensorBroadcast >::GraphTestcase(), luci::Importer::import(), moco::Importer::import(), luci::Importer::importModule(), moco::onnx::Frontend::load(), luci::produce_pmodules(), exo::test::TestGraph::TestGraph(), luci::test::TestGraph::TestGraph(), and mir2loco::Transformer::transform().
must_cast() [1/8]
template<typename T > T loco::must_cast (const FeatureDecoder * node)
Definition at line 95 of file FeatureCodec.h.
{
  return _must_cast<T, const FeatureDecoder *>(node);
}
must_cast() [2/8]
template<typename T > T loco::must_cast (const FeatureEncoder * node)
Definition at line 85 of file FeatureCodec.h.
{
  return _must_cast<T, const FeatureEncoder *>(node);
}
must_cast() [3/8]
template<typename T > T loco::must_cast (const FilterEncoder * node)
Definition at line 69 of file FilterCodec.h.
{
  return _must_cast<T, const FilterEncoder *>(node);
}
must_cast() [4/8]
template<typename T > T loco::must_cast (const Node * node)
Definition at line 151 of file Node.h.
{ return _must_cast<T, const Node *>(node); }
must_cast() [5/8]
template<typename T > T loco::must_cast (FeatureDecoder * node)
Definition at line 90 of file FeatureCodec.h.
{
  return _must_cast<T, FeatureDecoder *>(node);
}
must_cast() [6/8]
template<typename T > T loco::must_cast (FeatureEncoder * node)
A helper dynamic_cast that throws when failed.
Definition at line 80 of file FeatureCodec.h.
{
  return _must_cast<T, FeatureEncoder *>(node);
}
must_cast() [7/8]
template<typename T > T loco::must_cast (FilterEncoder * node)
A helper dynamic_cast that throws when failed.
Definition at line 64 of file FilterCodec.h.
{
  return _must_cast<T, FilterEncoder *>(node);
}
must_cast() [8/8]
template<typename T > T loco::must_cast (Node * node)
A helper dynamic_cast that throws when failed.
Definition at line 149 of file Node.h.
{ return _must_cast<T, Node *>(node); }
operator<<() [1/5]
std::ostream & loco::operator<< (std::ostream & os, const loco::Dimension & d)
Definition at line 22 of file FormattedTensorShape.cpp.
{
  os << (d.known() ? std::to_string(d.value()) : std::string{"?"});
  return os;
}
References loco::Dimension::known(), and loco::Dimension::value().
operator<<() [2/5]
std::ostream & loco::operator<< (std::ostream & os, const loco::FeatureShape & feature_shape)
dump FeatureShape values to stream
Definition at line 22 of file LogHelper.cpp.
{
  os << "[" << feature_shape.count().value() << "," << feature_shape.height().value() << ","
     << feature_shape.width().value() << "," << feature_shape.depth().value() << "]";
  return os;
}
References loco::FeatureShape::count(), loco::FeatureShape::depth(), loco::FeatureShape::height(), loco::Dimension::value(), and loco::FeatureShape::width().
operator<<() [3/5]
std::ostream & loco::operator<< (std::ostream & os, const loco::FilterShape & filter_shape)
dump FilterShape values to stream
Definition at line 29 of file LogHelper.cpp.
{
  os << "[" << filter_shape.height().value() << "," << filter_shape.width().value() << ","
     << filter_shape.depth().value() << "," << filter_shape.count().value() << "]";
  return os;
}
References loco::FilterShape::count(), loco::FilterShape::depth(), loco::FilterShape::height(), loco::Dimension::value(), and loco::FilterShape::width().
operator<<() [4/5]
std::ostream & loco::operator<< (std::ostream & os, const loco::Padding2D & pad)
dump Padding2D values to stream
Definition at line 49 of file LogHelper.cpp.
{
  os << "[TLBR " << pad.top() << "," << pad.left() << "," << pad.bottom() << "," << pad.right()
     << "]";
  return os;
}
References loco::Padding2D::bottom(), loco::Padding2D::left(), loco::Padding2D::right(), and loco::Padding2D::top().
operator<<() [5/5]
std::ostream & loco::operator<< (std::ostream & os, const loco::TensorShape & tensor_shape)
dump TensorShape values to stream
Definition at line 36 of file LogHelper.cpp.
{
  os << "[";
  for (uint32_t r = 0; r < tensor_shape.rank(); ++r)
  {
    if (r)
      os << ",";
    os << tensor_shape.dim(r).value();
  }
  os << "]";
  return os;
}
References loco::TensorShape::dim(), loco::TensorShape::rank(), and loco::Dimension::value().
operator==() [1/5]
bool loco::operator== (const Dimension & lhs, const Dimension & rhs)
Equality operator between two Dimensions.
Note
Refer to the definition of equality of dimemsion at https://www.tensorflow.org/api_docs/python/tf/Dimension#__eq__
Definition at line 22 of file Dimension.cpp.
{
  return lhs.known() && rhs.known() && lhs.value() == rhs.value();
}
References loco::Dimension::known(), and loco::Dimension::value().
operator==() [2/5]
bool loco::operator== (const Dimension & lhs, uint32_t rhs)
Definition at line 27 of file Dimension.cpp.
{ return lhs.known() && lhs.value() == rhs; }
References loco::Dimension::known(), and loco::Dimension::value().
operator==() [3/5]
bool loco::operator== (const NodeShape & lhs, const NodeShape & rhs)
Definition at line 214 of file NodeShape.cpp.
{
  if (lhs.domain() != rhs.domain())
    return false;
  switch (lhs.domain())
  {
    case loco::Domain::Tensor:
    {
      auto lhs_t = lhs.as<TensorShape>();
      auto rhs_t = rhs.as<TensorShape>();
      if (lhs_t.rank() != rhs_t.rank())
        return false;
      for (uint32_t axis = 0; axis < lhs_t.rank(); ++axis)
      {
        if (!(lhs_t.dim(axis) == rhs_t.dim(axis)))
          return false;
      }
      return true;
    }
    case loco::Domain::Feature:
    {
      auto lhs_f = lhs.as<FeatureShape>();
      auto rhs_f = rhs.as<FeatureShape>();
      return (lhs_f.count() == rhs_f.count() && lhs_f.depth() == rhs_f.depth() &&
              lhs_f.height() == rhs_f.height() && lhs_f.width() == rhs_f.width());
    }
    case loco::Domain::Filter:
    {
      auto lhs_f = lhs.as<FilterShape>();
      auto rhs_f = rhs.as<FilterShape>();
      return (lhs_f.count() == rhs_f.count() && lhs_f.depth() == rhs_f.depth() &&
              lhs_f.height() == rhs_f.height() && lhs_f.width() == rhs_f.width());
    }
    case loco::Domain::DepthwiseFilter:
    {
      auto lhs_f = lhs.as<DepthwiseFilterShape>();
      auto rhs_f = rhs.as<DepthwiseFilterShape>();
      return (lhs_f.multiplier() == rhs_f.multiplier() && lhs_f.depth() == rhs_f.depth() &&
              lhs_f.height() == rhs_f.height() && lhs_f.width() == rhs_f.width());
    }
    case loco::Domain::Bias:
    {
      auto lhs_f = lhs.as<BiasShape>();
      auto rhs_f = rhs.as<BiasShape>();
      return (lhs_f.length() == rhs_f.length());
    }
    case loco::Domain::Matrix:
    {
      auto lhs_f = lhs.as<MatrixShape>();
      auto rhs_f = rhs.as<MatrixShape>();
      return (lhs_f.height() == rhs_f.height() && lhs_f.width() == rhs_f.width());
    }
    default:
      throw std::runtime_error("Not supported domain for NodeShape equality");
  }
  return false;
}
References loco::NodeShape::as(), Bias, loco::FeatureShape::count(), loco::FilterShape::count(), loco::DepthwiseFilterShape::depth(), loco::FeatureShape::depth(), loco::FilterShape::depth(), DepthwiseFilter, loco::TensorShape::dim(), loco::NodeShape::domain(), Feature, Filter, loco::DepthwiseFilterShape::height(), loco::FeatureShape::height(), loco::FilterShape::height(), loco::MatrixShape::height(), loco::BiasShape::length(), Matrix, loco::DepthwiseFilterShape::multiplier(), loco::TensorShape::rank(), Tensor, loco::DepthwiseFilterShape::width(), loco::FeatureShape::width(), loco::FilterShape::width(), and loco::MatrixShape::width().
operator==() [4/5]
bool loco::operator== (const TensorShape & lhs, const TensorShape & rhs)
'==' operator for TensorShape
Definition at line 44 of file TensorShape.cpp.
{
  if (lhs.rank() != rhs.rank())
    return false;
  for (uint32_t axis = 0; axis < lhs.rank(); ++axis)
  {
    if (!(lhs.dim(axis) == rhs.dim(axis)))
      return false;
  }
  return true;
}
References loco::TensorShape::dim(), and loco::TensorShape::rank().
operator==() [5/5]
bool loco::operator== (uint32_t lhs, const Dimension & rhs)
Definition at line 28 of file Dimension.cpp.
{ return rhs.known() && lhs == rhs.value(); }
References loco::Dimension::known(), and loco::Dimension::value().
output_nodes()
std::vector< loco::Node * > loco::output_nodes (loco::Graph * g)
Definition at line 101 of file Graph.cpp.
{
  std::map<GraphOutputIndex, loco::Node *> table;
  for (uint32_t n = 0; n < g->nodes()->size(); ++n)
  {
    auto node = g->nodes()->at(n);
    if (auto service = node->dialect()->service<GraphOutputIndexQueryService>())
    {
      if (service->associated(node))
      {
        auto output_index = service->index(node);
        assert(table.find(output_index) == table.end());
        table[output_index] = node;
      }
    }
  }
  std::vector<loco::Node *> res;
  for (uint32_t n = 0; n < g->outputs()->size(); ++n)
  {
    auto it = table.find(n);
    res.emplace_back(it == table.end() ? nullptr : it->second);
  }
  return res;
}
References size().
Referenced by dalgona::PythonHooks::endNetworkExecution(), entry(), exo::circle_detail::exportNodes(), exo::tflite_detail::exportNodes(), luci::exportNodes(), exo::circle_detail::exportOpDefinedTensors(), exo::tflite_detail::exportOpDefinedTensors(), luci::exportOpDefinedTensors(), logo::test::find_first_node_by_type(), moco::test::find_nodes_bytype(), luci::Importer::importModule(), luci::inference_candidates(), circle_eval_diff::MAEPrinter::init(), circle_eval_diff::MSEPrinter::init(), circle_eval_diff::MAPEPrinter::init(), circle_eval_diff::MPEIRPrinter::init(), circle_eval_diff::TopKMatchPrinter::init(), luci_interpreter::GraphLoader::initInputOutputTensors(), luci::DeadNodeQueryServiceImpl::isDeadNode(), luci::layer_info_map(), luci_interpreter::GraphLoader::loadOperators(), luci::CircleQuantizer::quantize(), mpqsolver::bisection::BisectionSolver::run(), logo::RemoveDeadNodePass::run(), logo::RemoveDeadNodeWithQueryPass::run(), exo::FoldReshapeOfConstPass::run(), exo::FoldTransposeOfConstPass::run(), exo::FuseBiasAddPass::run(), exo::FuseInstanceNormPass::run(), exo::FuseReluPass::run(), exo::FuseRsqrtPass::run(), exo::FuseSquaredDifferencePass::run(), logo::SimplifyDomainConversionPass::run(), luci::ConvertNCHWToNHWCPass::run(), luci::ConvertToFakeQuantizedModelPass::run(), luci::ExpandBroadcastConstPass::run(), luci::FoldAddV2Pass::run(), luci::FoldCastPass::run(), luci::FoldDensifyPass::run(), luci::FoldDepthwiseConv2DPass::run(), luci::FoldDequantizePass::run(), luci::FoldFullyConnectedPass::run(), luci::FoldGatherPass::run(), luci::FoldSparseToDensePass::run(), luci::ForwardReshapeToUnaryOpPass::run(), luci::ForwardTransposeOpPass::run(), luci::FuseActivationFunctionPass::run(), luci::FuseAddWithFullyConnectedPass::run(), luci::FuseAddWithTConvPass::run(), luci::FuseBatchNormWithConvPass::run(), luci::FuseBatchNormWithDwConvPass::run(), luci::FuseBatchNormWithTConvPass::run(), luci::FuseInstanceNormPass::run(), luci::FuseMeanWithMeanPass::run(), luci::FusePreActivationBatchNormPass::run(), luci::FusePReluPass::run(), luci::FuseTransposeWithMeanPass::run(), luci::MakeBatchNormGammaPositivePass::run(), luci::PropagateQParamBackwardPass::run(), luci::PropagateQParamForwardPass::run(), luci::RemoveDuplicateConstPass::run(), luci::RemoveFakeQuantPass::run(), luci::RemoveQuantDequantSeqPass::run(), luci::RemoveRedundantDequantizePass::run(), luci::RemoveRedundantQuantizePass::run(), luci::RemoveRedundantReshapePass::run(), luci::RemoveRedundantTransposePass::run(), luci::RemoveUnnecessaryReshapeNetPass::run(), luci::RemoveUnnecessaryReshapePass::run(), luci::RemoveUnnecessarySlicePass::run(), luci::RemoveUnnecessarySplitPass::run(), luci::RemoveUnnecessaryStridedSlicePass::run(), luci::ReplaceMulAddWithDepthwiseConvPass::run(), luci::ReplaceNonConstFCWithBatchMatMulPass::run(), luci::ReplaceSubWithAddPass::run(), luci::ResolveCustomOpAddPass::run(), luci::ResolveCustomOpBatchMatMulPass::run(), luci::ResolveCustomOpMatMulPass::run(), luci::ResolveCustomOpMaxPoolWithArgmaxPass::run(), luci::ResolveCustomOpSplitVPass::run(), luci::ShuffleWeightTo16x1Float32Pass::run(), luci::SparsifyTensorPass::run(), luci::SubstitutePackToReshapePass::run(), luci::SubstitutePadV2ToPadPass::run(), luci::SubstituteSplitVToSplitPass::run(), luci::SubstituteSqueezeToReshapePass::run(), luci::SubstituteStridedSliceToReshapePass::run(), luci::SubstituteTransposeToReshapePass::run(), luci::TransformMinMaxToRelu6Pass::run(), luci::TransformMinReluToRelu6Pass::run(), luci::UnrollUnidirectionalSequenceLSTMPass::run(), exo::CanonicalNodeConverter< CanonicalType >::run(), exo::TensorBroadcastConverter::run(), exo::MergeConcatNodesPass::run(), luci::CopyQuantParamPass::run(), luci::ForceQuantParamPass::run(), luci::QuantizeDequantizeWeightsPass::run(), luci::QuantizeWithMinMaxPass::run(), luci::RequantizePass::run(), luci::QuantizePreCheckerPass::run(), moco::tf::SimpleNodeTransform< ConcreteNode >::run(), logo::ConstantFoldingPass::run(), logo::ResolveDuplicateReshapePass::run(), logo::ResolveRedundantReshapePass::run(), moco::ConstantFoldAdd::run(), moco::ConstantFoldMul::run(), moco::ConstantFoldPack::run(), moco::ConstantFoldStridedSlice::run(), moco::FuseBinaryIntoPreceding::run(), moco::ResolveConstantShape::run(), moco::ResolveFusedBatchNorm::run(), moco::ResolveReshapeWildcardDim::run(), moco::ResolveSquaredDifference::run(), moco::SqueezeReduceNode::run(), luci::FuseBCQPass::run(), prunner::PModelsRunner::run(), prunner::PModelsRunner::save_outputs(), loco::ShapeInferenceSession::to(), loco::TypeInferenceSession::to(), and luci::QuantizedModelVerifier::verify().
postorder_traversal()
std::vector< loco::Node * > loco::postorder_traversal (const std::vector< loco::Node * > & roots)
Generate postorder traversal sequence starting from "roots".
HOW TO USE
for (auto node : postorder_traversal(...)) { ... node->do_something() ... }
Definition at line 53 of file Algorithm.cpp.
{
  std::vector<loco::Node *> res;
  std::set<loco::Node *> visited_nodes;
  std::stack<Frame> frames;
  auto visited = [&visited_nodes](loco::Node *node) {
    return visited_nodes.find(node) != visited_nodes.end();
  };
  // NOTE There is not much difference between "auto" and "auto &" as node is of "loco::Node *"
  // type.
  for (auto node : roots)
  {
    assert((node != nullptr) && "root is invalid");
    frames.push(Frame{node});
  }
  while (!frames.empty())
  {
    auto &top_frame = frames.top();
    if (top_frame.pos() == -1)
    {
      if (visited(top_frame.ptr()))
      {
        frames.pop();
        continue;
      }
      visited_nodes.insert(top_frame.ptr());
    }
    top_frame.advance();
    assert(top_frame.pos() >= 0);
    if (top_frame.pos() < static_cast<int64_t>(top_frame.node().arity()))
    {
      // Let's visit the next argument
      //
      // NOTE "next" may be nullptr if a graph is under construction.
      if (auto next = top_frame.node().arg(top_frame.pos()))
      {
        frames.push(Frame{next});
      }
    }
    else
    {
      // Let's visit the current argument (all the arguments are already visited)
      auto curr = top_frame.ptr();
      res.emplace_back(curr);
      frames.pop();
    }
  }
  return res;
}
Referenced by active_nodes(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), exo::circle_detail::exportNodes(), exo::tflite_detail::exportNodes(), luci::exportNodes(), exo::circle_detail::exportOpDefinedTensors(), exo::tflite_detail::exportOpDefinedTensors(), luci::exportOpDefinedTensors(), logo::test::find_first_node_by_type(), luci::Importer::importModule(), locomotiv::Session::infer(), luci::inference_candidates(), luci_interpreter::GraphLoader::loadOperators(), luci::ConvertNCHWToNHWCPass::run(), luci::PropagateQParamBackwardPass::run(), luci::RemoveRedundantQuantizePass::run(), logo::ConstantFoldingPass::run(), logo::ResolveDuplicateReshapePass::run(), logo::ResolveRedundantReshapePass::run(), loco::ShapeInferenceSession::to(), and loco::TypeInferenceSession::to().
preds()
std::set< Node * > loco::preds (const Node * node)
Enumerate all the predecessors of a given node.
Definition at line 31 of file Node.cpp.
{
  std::set<Node *> res;
  for (uint32_t n = 0; n < node->arity(); ++n)
  {
    if (auto pred = node->arg(n))
    {
      res.insert(pred);
    }
  }
  return res;
}
References loco::Node::arg(), and loco::Node::arity().
Referenced by luci::fuse_activation_function().
pull_node()
Pull * loco::pull_node (Graph * g, const GraphInputIndex & index)
Find a Pull node with a given input index.
Definition at line 162 of file Nodes.cpp.
{
  for (uint32_t n = 0; n < g->nodes()->size(); ++n)
  {
    if (auto pull = dynamic_cast<Pull *>(g->nodes()->at(n)))
    {
      if (pull->indexed() && pull->index() == index)
      {
        return pull;
      }
    }
  }
  return nullptr;
}
References size().
Referenced by exo::circle_detail::registerGraphIOName(), exo::tflite_detail::registerGraphIOName(), and locomotiv::Session::set_input().
push_node()
Push * loco::push_node (Graph * g, const GraphOutputIndex & index)
Find a Push node with a given output index.
Definition at line 67 of file Nodes.cpp.
{
  for (uint32_t n = 0; n < g->nodes()->size(); ++n)
  {
    if (auto push = dynamic_cast<Push *>(g->nodes()->at(n)))
    {
      if (push->indexed() && push->index() == index)
      {
        return push;
      }
    }
  }
  return nullptr;
}
References size().
Referenced by exo::circle_detail::registerGraphIOName(), and exo::tflite_detail::registerGraphIOName().
replace()
Subst< SubstQualifier::Default > loco::replace (Node * node)
Definition at line 82 of file Node.cpp.
{
  // Let's create Subst<SubstQualifier::Default>!
  return Subst<SubstQualifier::Default>{node};
}
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert(), exo::AvgPool2DConverter::convert(), exo::ConstGenConverter::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MatMulConverter::convert(), exo::MaxPool2DConverter::convert(), exo::TensorConcatConverter::convert(), exo::TensorTransposeConverter::convert(), exo::TransposedConv2DConverter::convert(), luci::fuse_activation_function(), luci::fuse_add_with_conv(), luci::fuse_mul_with_conv(), luci::fuse_sub_with_conv(), logo::ReorderDecodePass< loco::TensorBiasAdd >::run(), logo::ReorderDecodePass< loco::ReLU >::run(), logo::SimplifyDomainConversionPass::run(), luci::FoldDequantizePass::run(), exo::MergeConcatNodesPass::run(), and luci::swap_mul_add().
shape_erase()
void loco::shape_erase (Node * node) inline
Definition at line 62 of file ShapeInference.h.
{ ShapeInference::erase(node); }
References loco::ShapeInference::erase().
shape_get()
NodeShape loco::shape_get (const Node * node) inline
Definition at line 61 of file ShapeInference.h.
{ return ShapeInference::get(node); }
References loco::ShapeInference::get().
Referenced by moco::tf::BroadcastFunctor::build(), exo::DomainConverter< CanonicalT, TFLT >::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::FeatureBiasAddConverter::convert(), exo::MatMulConverter::convert(), exo::TensorConcatConverter::convert(), exo::TensorTransposeConverter::convert(), exo::TransposedConv2DConverter::convert(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), exo::ShapeInference::get(), locoex::COpShapeInferenceRule::infer(), and moco::node_shape().
shape_known()
bool loco::shape_known (const Node * node) inline
Definition at line 60 of file ShapeInference.h.
{ return ShapeInference::known(node); }
References loco::ShapeInference::known().
Referenced by exo::DomainConverter< CanonicalT, TFLT >::convert(), exo::Conv2DConverter::convert(), exo::DepthwiseConv2DConverter::convert(), exo::MatMulConverter::convert(), exo::TensorConcatConverter::convert(), exo::TransposedConv2DConverter::convert(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), exo::ShapeInference::get(), moco::node_shape(), and loco::ShapeInferenceSession::to().
size()
uint32_t loco::size (DataType data_type) inline
Returns the size of the data type.
Note
If you need the size at compile time, use sizeof(typename DataTypeImpl<DT>::Type).
Definition at line 122 of file DataTypeTraits.h.
{
  switch (data_type)
  {
    case DataType::S8:
      return sizeof(DataTypeImpl<DataType::S8>::Type);
    case DataType::U8:
      return sizeof(DataTypeImpl<DataType::U8>::Type);
    case DataType::S16:
      return sizeof(DataTypeImpl<DataType::S16>::Type);
    case DataType::U16:
      return sizeof(DataTypeImpl<DataType::U16>::Type);
    case DataType::S32:
      return sizeof(DataTypeImpl<DataType::S32>::Type);
    case DataType::U32:
      return sizeof(DataTypeImpl<DataType::U32>::Type);
    case DataType::S64:
      return sizeof(DataTypeImpl<DataType::S64>::Type);
    case DataType::U64:
      return sizeof(DataTypeImpl<DataType::U64>::Type);
    case DataType::FLOAT16:
      return sizeof(DataTypeImpl<DataType::FLOAT16>::Type);
    case DataType::FLOAT32:
      return sizeof(DataTypeImpl<DataType::FLOAT32>::Type);
    case DataType::FLOAT64:
      return sizeof(DataTypeImpl<DataType::FLOAT64>::Type);
    case DataType::BOOL:
      return sizeof(DataTypeImpl<DataType::BOOL>::Type);
    case DataType::STRING:
      // STRING is variable length. Cannot decide size by type
      throw std::runtime_error("Invalid size call with STRING type");
    default:
      // TODO Support remaining data types.
      assert(false);
      return UINT32_MAX; // Avoid compiler warning.
  }
}
Referenced by all_nodes(), mpqsolver::bisection::MAEMetric::compute(), circle_planner::ScratchpadHelperLinux::ComputeScratchpadSizeBatchMatMul(), loco::Graph::OutputContext::create(), entry(), luci_interpreter::getDataTypeSize(), circle_eval_diff::getEachByteSizeOf(), circle_eval_diff::getTotalByteSizeOf(), input_nodes(), output_nodes(), pull_node(), and push_node().
succs()
std::set< Node * > loco::succs (const Node * node)
Enumerate all the successors of a given node.
Definition at line 46 of file Node.cpp.
{
  std::set<Node *> res;
  for (auto use : node->_uses)
  {
    auto user = use->user();
    assert(user != nullptr);
    res.insert(user);
  }
  return res;
}
Referenced by luci_interpreter::collectOutputNodes(), mpqsolver::bisection::compute_depth(), locop::FormattedGraphImpl< Formatter::LinearV1 >::dump(), luci::fuse_activation_function(), luci::fuse_add_with_conv(), luci::fuse_mul_with_conv(), luci::fuse_sub_with_conv(), luci::get_channel_dim_index(), exo::test::get_only_succ(), dalgona::outputsPyArray(), luci::propagate_concat_quantparam(), luci::propagate_pad_v2_quantparam(), logo::ReorderDecodePass< loco::TensorBiasAdd >::run(), logo::ReorderDecodePass< loco::ReLU >::run(), luci::ConvertNCHWToNHWCPass::run(), luci::FoldDequantizePass::run(), and luci::swap_mul_add().
valid()
bool loco::valid (Graph * g, std::unique_ptr< ErrorListener > && l = nullptr)
Validate a loco graph.
"valid" returns true if a given graph has no error.
NOTE Given a valid(non-null) listener, "valid" notifies error details to the listener.
Definition at line 100 of file Verifier.cpp.
{
  class ErrorCounter final : public ErrorListener
  {
  public:
    uint32_t count(void) const { return _count; }
  public:
    void notify(const ErrorDetail<ErrorCategory::MissingArgument> &) { _count += 1; }
  private:
    uint32_t _count = 0;
  };
  ErrorCounter counter;
  graph_verifier(g).enroll(&counter).enroll(std::move(l)).run();
  return counter.count() == 0;
}
Referenced by loco::Permutation< Domain::DepthwiseFilter >::axis(), loco::Permutation< Domain::Feature >::axis(), loco::Permutation< Domain::Filter >::axis(), loco::Permutation< Domain::Matrix >::axis(), luci::Importer::import(), luci::Importer::importModule(), loco::Permutation< Domain::DepthwiseFilter >::mapped(), loco::Permutation< Domain::Feature >::mapped(), loco::Permutation< Domain::Filter >::mapped(), loco::Permutation< Domain::Matrix >::mapped(), loco::PermutingDecoder< Domain::DepthwiseFilter >::shape(), loco::PermutingDecoder< Domain::Feature >::shape(), loco::PermutingDecoder< Domain::Filter >::shape(), loco::PermutingDecoder< Domain::Matrix >::shape(), loco::PermutingEncoder< Domain::Feature >::shape(), loco::PermutingEncoder< Domain::Filter >::shape(), loco::PermutingEncoder< Domain::DepthwiseFilter >::shape(), loco::PermutingEncoder< Domain::Matrix >::shape(), mir2loco::Transformer::transform(), luci::validate(), loco::PermutingEncoder< Domain::DepthwiseFilter >::value(), loco::PermutingEncoder< Domain::Feature >::value(), loco::PermutingEncoder< Domain::Filter >::value(), loco::PermutingEncoder< Domain::Matrix >::value(), loco::PermutingDecoder< Domain::Feature >::value(), loco::PermutingDecoder< Domain::Filter >::value(), loco::PermutingDecoder< Domain::DepthwiseFilter >::value(), and loco::PermutingDecoder< Domain::Matrix >::value().