#!/bin/bash

NNAS_CONFIG_RPATH="infra/config"
NNAS_COMMAND_RPATH="infra/command"
NNAS_PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
NNAS_COMMAND_PATH="${NNAS_PROJECT_PATH}/${NNAS_COMMAND_RPATH}"

function Usage()
{
  echo "Usage: $0 [COMMAND] ..."
  echo "Command:"
  for file in "$NNAS_COMMAND_PATH"/*;
  do
    echo "  $(basename "$file")"
  done
}

function import()
{
  source "${NNAS_PROJECT_PATH}/${NNAS_CONFIG_RPATH}/$1"
}

COMMAND=$1; shift

if [[ -z "${COMMAND}" ]]; then
  Usage
  exit 255
fi

COMMAND_FILE="${NNAS_COMMAND_PATH}/${COMMAND}"

if [[ ! -f "${COMMAND_FILE}" ]]; then
  echo "ERROR: '${COMMAND}' is not supported"
  exit 255
fi

export NNAS_PROJECT_PATH

source "${COMMAND_FILE}" "$@"
