#!/bin/bash

NNFW_SCRIPT_RPATH="runtime/infra"
NNFW_COMMAND_RPATH="${NNFW_SCRIPT_RPATH}/command"

NNFW_PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
NNFW_COMMAND_PATH="${NNFW_PROJECT_PATH}/${NNFW_COMMAND_RPATH}"
NNFW_SCRIPT_PATH="${NNFW_PROJECT_PATH}/${NNFW_SCRIPT_RPATH}"

function Usage()
{
  echo "Usage: $0 [COMMAND] ..."
  echo "Command:"
  for file in "$NNFW_COMMAND_PATH"/*;
  do
    echo "  $(basename "$file")"
  done
}

COMMAND=$1; shift

if [[ -z "${COMMAND}" ]]; then
  Usage
  exit 255
fi

COMMAND_FILE="${NNFW_COMMAND_PATH}/${COMMAND}"

if [[ ! -f "${COMMAND_FILE}" ]]; then
  echo "ERROR: '${COMMAND}' is not supported"
  exit 255
fi

export NNFW_PROJECT_PATH
export NNFW_SCRIPT_PATH

function import()
{
  source "${NNFW_PROJECT_PATH}/${NNFW_SCRIPT_RPATH}/config/$1"
}

source "${COMMAND_FILE}" "$@"
