ONE - On-device Neural Engine: runtime/onert/python/api/include/nnfw_api_wrapper.h File Reference
nnfw_api_wrapper.h File Reference
#include "nnfw.h"
#include <pybind11/stl.h>
#include <pybind11/numpy.h>
Data Structures
struct tensorinfo
tensor info describes the type and shape of tensors
class NNFW_SESSION
Functions
void ensure_status (NNFW_STATUS status)
Handle errors with NNFW_STATUS in API functions.
NNFW_LAYOUT getLayout (const char *layout="")
NNFW_TYPE getType (const char *type="")
const char * getStringType (NNFW_TYPE type)
uint64_t num_elems (const nnfw_tensorinfo *tensor_info)
Get the total number of elements in nnfw_tensorinfo->dims.
py::list get_dims (const tensorinfo &tensor_info)
Get nnfw_tensorinfo->dims.
void set_dims (tensorinfo &tensor_info, const py::list &array)
Set nnfw_tensorinfo->dims.
Function Documentation
ensure_status()
void ensure_status (NNFW_STATUS status)
Handle errors with NNFW_STATUS in API functions.
This only handles NNFW_STATUS errors.
Parameters
[in] status The status returned by API functions
Definition at line 19 of file nnfw_api_wrapper.cc.
{
  switch (status)
  {
    case NNFW_STATUS::NNFW_STATUS_NO_ERROR:
      break;
    case NNFW_STATUS::NNFW_STATUS_ERROR:
      std::cout << "[ERROR]\tNNFW_STATUS_ERROR\n";
      exit(1);
    case NNFW_STATUS::NNFW_STATUS_UNEXPECTED_NULL:
      std::cout << "[ERROR]\tNNFW_STATUS_UNEXPECTED_NULL\n";
      exit(1);
    case NNFW_STATUS::NNFW_STATUS_INVALID_STATE:
      std::cout << "[ERROR]\tNNFW_STATUS_INVALID_STATE\n";
      exit(1);
    case NNFW_STATUS::NNFW_STATUS_OUT_OF_MEMORY:
      std::cout << "[ERROR]\tNNFW_STATUS_OUT_OF_MEMORY\n";
      exit(1);
    case NNFW_STATUS::NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE:
      std::cout << "[ERROR]\tNNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE\n";
      exit(1);
  }
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_OUT_OF_MEMORY, and NNFW_STATUS_UNEXPECTED_NULL.
Referenced by NNFW_SESSION::await(), NNFW_SESSION::close_session(), NNFW_SESSION::input_size(), NNFW_SESSION::input_tensorinfo(), NNFW_SESSION::NNFW_SESSION(), NNFW_SESSION::output_size(), NNFW_SESSION::output_tensorinfo(), NNFW_SESSION::run(), NNFW_SESSION::run_async(), NNFW_SESSION::set_input(), NNFW_SESSION::set_input_layout(), NNFW_SESSION::set_input_tensorinfo(), NNFW_SESSION::set_output(), and NNFW_SESSION::set_output_layout().
get_dims()
py::list get_dims (const tensorinfo & tensor_info)
Get nnfw_tensorinfo->dims.
This function is called to get dimension array of tensorinfo.
Parameters
[in] tensor_info Tensor info (shape, type, etc)
Returns
python list of dims
Definition at line 137 of file nnfw_api_wrapper.cc.
{
  py::list dims_list;
  for (int32_t i = 0; i < tensor_info.rank; ++i)
  {
    dims_list.append(tensor_info.dims[i]);
  }
  return dims_list;
}
References tensorinfo::dims, and tensorinfo::rank.
Referenced by PYBIND11_MODULE().
getLayout()
NNFW_LAYOUT getLayout (const char * layout = "")
Convert the layout with string to NNFW_LAYOUT
Parameters
[in] layout layout to be converted
Returns
proper layout if exists
Definition at line 43 of file nnfw_api_wrapper.cc.
{
  if (!strcmp(layout, "NCHW"))
  {
    return NNFW_LAYOUT::NNFW_LAYOUT_CHANNELS_FIRST;
  }
  else if (!strcmp(layout, "NHWC"))
  {
    return NNFW_LAYOUT::NNFW_LAYOUT_CHANNELS_LAST;
  }
  else if (!strcmp(layout, "NONE"))
  {
    return NNFW_LAYOUT::NNFW_LAYOUT_NONE;
  }
  else
  {
    std::cout << "[ERROR]\tLAYOUT_TYPE\n";
    exit(1);
  }
}
References NNFW_LAYOUT_CHANNELS_FIRST, NNFW_LAYOUT_CHANNELS_LAST, and NNFW_LAYOUT_NONE.
Referenced by NNFW_SESSION::set_input_layout(), and NNFW_SESSION::set_output_layout().
getStringType()
const char * getStringType (NNFW_TYPE type)
Convert the type with NNFW_TYPE to string
Parameters
[in] type type to be converted
Returns
proper type
Definition at line 102 of file nnfw_api_wrapper.cc.
{
  switch (type)
  {
    case NNFW_TYPE::NNFW_TYPE_TENSOR_FLOAT32:
      return "float32";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_INT32:
      return "int32";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT8_ASYMM:
    case NNFW_TYPE::NNFW_TYPE_TENSOR_UINT8:
      return "uint8";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_BOOL:
      return "bool";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_INT64:
      return "int64";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED:
      return "int8";
    case NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED:
      return "int16";
    default:
      std::cout << "[ERROR] NNFW_TYPE to String Failure\n";
      exit(1);
  }
}
References NNFW_TYPE_TENSOR_BOOL, NNFW_TYPE_TENSOR_FLOAT32, NNFW_TYPE_TENSOR_INT32, NNFW_TYPE_TENSOR_INT64, NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED, NNFW_TYPE_TENSOR_QUANT8_ASYMM, NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED, and NNFW_TYPE_TENSOR_UINT8.
Referenced by NNFW_SESSION::input_tensorinfo(), and NNFW_SESSION::output_tensorinfo().
getType()
NNFW_TYPE getType (const char * type = "")
Convert the type with string to NNFW_TYPE
Parameters
[in] type type to be converted
Returns
proper type if exists
Definition at line 64 of file nnfw_api_wrapper.cc.
{
  if (!strcmp(type, "float32"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_FLOAT32;
  }
  else if (!strcmp(type, "int32"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_INT32;
  }
  else if (!strcmp(type, "uint8"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_UINT8;
    // return NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT8_ASYMM;
  }
  else if (!strcmp(type, "bool"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_BOOL;
  }
  else if (!strcmp(type, "int64"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_INT64;
  }
  else if (!strcmp(type, "int8"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED;
  }
  else if (!strcmp(type, "int16"))
  {
    return NNFW_TYPE::NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED;
  }
  else
  {
    std::cout << "[ERROR] String to NNFW_TYPE Failure\n";
    exit(1);
  }
}
References NNFW_TYPE_TENSOR_BOOL, NNFW_TYPE_TENSOR_FLOAT32, NNFW_TYPE_TENSOR_INT32, NNFW_TYPE_TENSOR_INT64, NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED, NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED, and NNFW_TYPE_TENSOR_UINT8.
Referenced by mir_onnx::convertExpandV8(), mir::Operation::Output::getElementType(), mir::Operation::Output::getShape(), and NNFW_SESSION::set_input_tensorinfo().
num_elems()
uint64_t num_elems (const nnfw_tensorinfo * tensor_info)
Get the total number of elements in nnfw_tensorinfo->dims.
This function is called to set the size of the input, output array.
Parameters
[in] tensor_info Tensor info (shape, type, etc)
Returns
total number of elements
Definition at line 127 of file nnfw_api_wrapper.cc.
{
  uint64_t n = 1;
  for (uint32_t i = 0; i < tensor_info->rank; ++i)
  {
    n *= tensor_info->dims[i];
  }
  return n;
}
References nnfw_tensorinfo::dims, and nnfw_tensorinfo::rank.
Referenced by circle_eval_diff::MAEPrinter::init(), circle_eval_diff::MSEPrinter::init(), circle_eval_diff::MAPEPrinter::init(), circle_eval_diff::TopKMatchPrinter::init(), main(), dalgona::Dalgona::runAnalysisWithRandomInput(), NNFW_SESSION::set_input(), and NNFW_SESSION::set_output().
set_dims()
void set_dims (tensorinfo & tensor_info, const py::list & array)
Set nnfw_tensorinfo->dims.
This function is called to set dimension array of tensorinfo.
Parameters
[in] tensor_info Tensor info (shape, type, etc)
[in] array array to set dimension
Definition at line 147 of file nnfw_api_wrapper.cc.
{
  tensor_info.rank = py::len(array);
  for (int32_t i = 0; i < tensor_info.rank; ++i)
  {
    tensor_info.dims[i] = py::cast<int32_t>(array[i]);
  }
}
References tensorinfo::dims, and tensorinfo::rank.
Referenced by PYBIND11_MODULE().