ONE - On-device Neural Engine: runtime/onert/api/include/nnfw.h File Reference
nnfw.h File Reference
This file describes runtime API.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct nnfw_tensorinfo
tensor info describes the type and shape of tensors
Macros
#define NNFW_MAX_RANK (6)
Maximum rank expressible with nnfw.
Typedefs
typedef struct nnfw_session nnfw_session
Session to query with runtime.
typedef struct nnfw_tensorinfo nnfw_tensorinfo
tensor info describes the type and shape of tensors
Enumerations
enum NNFW_TYPE {
NNFW_TYPE_TENSOR_FLOAT32 = 0 , NNFW_TYPE_TENSOR_INT32 = 1 , NNFW_TYPE_TENSOR_QUANT8_ASYMM = 2 , NNFW_TYPE_TENSOR_BOOL = 3 ,
NNFW_TYPE_TENSOR_UINT8 = 4 , NNFW_TYPE_TENSOR_INT64 = 5 , NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED = 6 , NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED = 7
}
Tensor types.
enum NNFW_STATUS {
NNFW_STATUS_NO_ERROR = 0 , NNFW_STATUS_ERROR = 1 , NNFW_STATUS_UNEXPECTED_NULL = 2 , NNFW_STATUS_INVALID_STATE = 3 ,
NNFW_STATUS_OUT_OF_MEMORY = 4 , NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE = 5
}
Result values returned from a call to an API function.
enum NNFW_LAYOUT { NNFW_LAYOUT_NONE = 0 , NNFW_LAYOUT_CHANNELS_LAST = 1 , NNFW_LAYOUT_CHANNELS_FIRST = 2 }
Data format of a tensor.
enum NNFW_INFO_ID { NNFW_INFO_ID_VERSION = 0 }
Information ID for retrieving information on nnfw (e.g. version)
Functions
NNFW_STATUS nnfw_create_session (nnfw_session **session)
Create a new session instance.
NNFW_STATUS nnfw_close_session (nnfw_session *session)
Close a session instance.
NNFW_STATUS nnfw_load_model_from_file (nnfw_session *session, const char *package_file_path)
Load model from nnpackage file or directory.
NNFW_STATUS nnfw_apply_tensorinfo (nnfw_session *session, uint32_t index, nnfw_tensorinfo tensor_info)
Apply i-th input's tensor info to resize input tensor.
NNFW_STATUS nnfw_set_input_tensorinfo (nnfw_session *session, uint32_t index, const nnfw_tensorinfo *tensor_info)
Set input model's tensor info for resizing.
NNFW_STATUS nnfw_prepare (nnfw_session *session)
Prepare session to be ready for inference.
NNFW_STATUS nnfw_run (nnfw_session *session)
Run inference.
NNFW_STATUS nnfw_run_async (nnfw_session *session)
Run inference asynchronously.
NNFW_STATUS nnfw_await (nnfw_session *session)
Wait for asynchronous run to finish.
NNFW_STATUS nnfw_set_input (nnfw_session *session, uint32_t index, NNFW_TYPE type, const void *buffer, size_t length)
Set input buffer.
NNFW_STATUS nnfw_set_output (nnfw_session *session, uint32_t index, NNFW_TYPE type, void *buffer, size_t length)
Set output buffer.
NNFW_STATUS nnfw_input_size (nnfw_session *session, uint32_t *number)
Get the number of inputs.
NNFW_STATUS nnfw_output_size (nnfw_session *session, uint32_t *number)
Get the number of outputs.
NNFW_STATUS nnfw_set_input_layout (nnfw_session *session, uint32_t index, NNFW_LAYOUT layout)
Set the layout of an input.
NNFW_STATUS nnfw_set_output_layout (nnfw_session *session, uint32_t index, NNFW_LAYOUT layout)
Set the layout of an output.
NNFW_STATUS nnfw_input_tensorinfo (nnfw_session *session, uint32_t index, nnfw_tensorinfo *tensor_info)
Get i-th input tensor info.
NNFW_STATUS nnfw_output_tensorinfo (nnfw_session *session, uint32_t index, nnfw_tensorinfo *tensor_info)
Get i-th output tensor info.
NNFW_STATUS nnfw_set_available_backends (nnfw_session *session, const char *backends)
Set available backends.
NNFW_STATUS nnfw_set_op_backend (nnfw_session *session, const char *op, const char *backend)
Set the operation's backend.
NNFW_STATUS nnfw_query_info_u32 (nnfw_session *session, NNFW_INFO_ID id, uint32_t *val)
Retrieve uint32 type of nnfw information for given information ID.
Detailed Description
This file describes runtime API.
Definition in file nnfw.h.
Macro Definition Documentation
NNFW_MAX_RANK
#define NNFW_MAX_RANK (6)
Maximum rank expressible with nnfw.
Definition at line 161 of file nnfw.h.
Typedef Documentation
nnfw_session
typedef struct nnfw_session nnfw_session
Session to query with runtime.
nnfw_session is started and passed by calling nnfw_create_session. Each session has its own inference environment, such as model to inference, backend usage, etc.
Load model by calling nnfw_load_model_from_file
After loading, prepare inference by calling nnfw_prepare. Application can set runtime environment before prepare by calling nnfw_set_available_backends and nnfw_set_op_backend, and it is optional.
Application can inference by calling nnfw_run. Before inference, application has responsibility to set input tensor to set input data by calling nnfw_set_output, and output tensor to get output by calling nnfw_set_input
To support input and output setting, application can get input and output tensor information by calling
nnfw_input_size
nnfw_output_size
nnfw_input_tensorinfo
nnfw_output_tensorinfo
Application can inference many times using one session, but next inference can do after prior inference end
Application cannot use muitiple model using one session
Definition at line 60 of file nnfw.h.
nnfw_tensorinfo
typedef struct nnfw_tensorinfo nnfw_tensorinfo
tensor info describes the type and shape of tensors
This structure is used to describe input and output tensors. Application can get input and output tensor type and shape described in model by using nnfw_input_tensorinfo and nnfw_output_tensorinfo
Maximum rank is 6 (NNFW_MAX_RANK). And tensor's dimension value is filled in 'dims' field from index 0. For example, if tensor's rank is 4, application can get dimension value from dims[0], dims[1], dims[2], and dims[3]
Enumeration Type Documentation
NNFW_INFO_ID
enum NNFW_INFO_ID
Information ID for retrieving information on nnfw (e.g. version)
Enumerator
NNFW_INFO_ID_VERSION
nnfw runtime version Its value is uint32 in 0xMMmmmmPP, where MM = major, mmmm = minor, PP = patch.
Definition at line 150 of file nnfw.h.
{
  NNFW_INFO_ID_VERSION = 0,
} NNFW_INFO_ID;
NNFW_LAYOUT
enum NNFW_LAYOUT
Data format of a tensor.
Enumerator
NNFW_LAYOUT_NONE
Don't care layout
NNFW_LAYOUT_CHANNELS_LAST
Channel last layout If rank is 4, layout is NHWC
NNFW_LAYOUT_CHANNELS_FIRST
Channel first layout If rank is 4, layout is NCHW
Definition at line 131 of file nnfw.h.
{
  NNFW_LAYOUT_NONE = 0,
  NNFW_LAYOUT_CHANNELS_LAST = 1,
  NNFW_LAYOUT_CHANNELS_FIRST = 2,
} NNFW_LAYOUT;
NNFW_STATUS
enum NNFW_STATUS
Result values returned from a call to an API function.
Enumerator
NNFW_STATUS_NO_ERROR
Successful
NNFW_STATUS_ERROR
An error code for general use. Mostly used when there is no specific value for that certain situation.
NNFW_STATUS_UNEXPECTED_NULL
Unexpected null argument is given.
NNFW_STATUS_INVALID_STATE
When a function was called but it is not valid for the current session state.
NNFW_STATUS_OUT_OF_MEMORY
When it is out of memory
NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE
When it was given an insufficient output buffer
Definition at line 109 of file nnfw.h.
{
  NNFW_STATUS_NO_ERROR = 0,
  NNFW_STATUS_ERROR = 1,
  NNFW_STATUS_UNEXPECTED_NULL = 2,
  NNFW_STATUS_INVALID_STATE = 3,
  NNFW_STATUS_OUT_OF_MEMORY = 4,
  NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE = 5,
} NNFW_STATUS;
NNFW_TYPE
enum NNFW_TYPE
Tensor types.
The type of tensor represented in nnfw_tensorinfo
Enumerator
NNFW_TYPE_TENSOR_FLOAT32
A tensor of 32 bit floating point
NNFW_TYPE_TENSOR_INT32
A tensor of 32 bit signed integer
NNFW_TYPE_TENSOR_QUANT8_ASYMM
A tensor of 8 bit unsigned integers that represent real numbers.
real_value = (integer_value - zeroPoint) * scale.
NNFW_TYPE_TENSOR_BOOL
A tensor of boolean
NNFW_TYPE_TENSOR_UINT8
A tensor of 8 bit unsigned integer
NNFW_TYPE_TENSOR_INT64
A tensor of 64 bit signed integer
NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED
A tensor of 8 bit signed integers that represent real numbers.
real_value = (integer_value - zeroPoint) * scale.
NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED
A tensor of 16 bit signed integers that represent real numbers.
real_value = (integer_value - zeroPoint) * scale.
Forced to have zeroPoint equal to 0.
Definition at line 67 of file nnfw.h.
{
  NNFW_TYPE_TENSOR_FLOAT32 = 0,
  NNFW_TYPE_TENSOR_INT32 = 1,
  NNFW_TYPE_TENSOR_QUANT8_ASYMM = 2,
  NNFW_TYPE_TENSOR_BOOL = 3,
  NNFW_TYPE_TENSOR_UINT8 = 4,
  NNFW_TYPE_TENSOR_INT64 = 5,
  NNFW_TYPE_TENSOR_QUANT8_ASYMM_SIGNED = 6,
  NNFW_TYPE_TENSOR_QUANT16_SYMM_SIGNED = 7,
} NNFW_TYPE;
Function Documentation
nnfw_apply_tensorinfo()
NNFW_STATUS nnfw_apply_tensorinfo (nnfw_session * session, uint32_t index, nnfw_tensorinfo tensor_info)
Apply i-th input's tensor info to resize input tensor.
This function should be called before nnfw_prepare is invoked, and should be called after nnfw_load_model_from_file is invoked See nnfw_prepare for information applying updated tensor info If this function is called many times for same index, tensor info is overwritten
Parameters
[in] session Session to the input tensor info is to be set
[in] index Index of input to be applied (0-indexed)
[in] tensor_info Tensor info to be applied
Returns
NNFW_STATUS_NO_ERROR if successful, otherwise return NNFW_STATUS_ERROR
Definition at line 271 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->apply_tensorinfo(index, tensor_info);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_await()
NNFW_STATUS nnfw_await (nnfw_session * session)
Wait for asynchronous run to finish.
This function must be called after calling nnfw_run_asnyc, and can be called only once for a nnfw_run_async call.
When this function returns, it means that this session has finished the asynchronous run. Then the user can safely use the output data.
This function returns after the asynchronous inference is finished.
Parameters
[in] session The session to run inference
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 120 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->await();
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_close_session()
NNFW_STATUS nnfw_close_session (nnfw_session * session)
Close a session instance.
After called, access to closed session by application will be invalid
Parameters
[in] session The session to be closed
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 69 of file nnfw_api.cc.
{
  delete session;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_NO_ERROR.
Referenced by main().
nnfw_create_session()
NNFW_STATUS nnfw_create_session (nnfw_session ** session)
Create a new session instance.
This only creates a session. Model is loaded after nnfw_load_model_from_file is invoked. And inference is performed after nnfw_run is invoked.
nnfw_close_session should be called once if session is no longer needed
Parameters
[out] session The session to be created
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 61 of file nnfw_api.cc.
{ return nnfw_session::create(session); }
References nnfw_session::create().
Referenced by main().
nnfw_input_size()
NNFW_STATUS nnfw_input_size (nnfw_session * session, uint32_t * number)
Get the number of inputs.
Application can call this function to get number of inputs defined in loaded model. This function should be called after nnfw_load_model_from_file is invoked to load model
Parameters
[in] session Session from input information is to be extracted
[out] number Variable which the number of inputs is put into
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 173 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->input_size(number);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_input_tensorinfo()
NNFW_STATUS nnfw_input_tensorinfo (nnfw_session * session, uint32_t index, nnfw_tensorinfo * tensor_info)
Get i-th input tensor info.
Before nnfw_prepare is invoked, this function return tensor info in model, so updated tensor info by nnfw_apply_tensorinfo is not returned.
After nnfw_prepare is invoked, this function return updated tensor info if tensor info is updated by nnfw_apply_tensorinfo.
Parameters
[in] session Session from input information is to be extracted
[in] index Index of input
[out] tensor_info Tensor info (shape, type, etc)
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 234 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->input_tensorinfo(index, tensor_info);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_load_model_from_file()
NNFW_STATUS nnfw_load_model_from_file (nnfw_session * session, const char * package_file_path)
Load model from nnpackage file or directory.
The length of package_file_path must not exceed 1024 bytes including zero at the end.
Parameters
[in] session nnfw_session loading the given nnpackage file/dir
[in] package_file_path Path to the nnpackage file or unzipped directory to be loaded
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 83 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->load_model_from_nnpackage(pacakge_file_path);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_output_size()
NNFW_STATUS nnfw_output_size (nnfw_session * session, uint32_t * number)
Get the number of outputs.
Application can call this function to get number of outputs defined in loaded model. This function should be called after nnfw_load_model_from_file is invoked to load model
Parameters
[in] session Session from output information is to be extracted
[out] number Variable which the number of outputs is put into
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 187 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->output_size(number);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_output_tensorinfo()
NNFW_STATUS nnfw_output_tensorinfo (nnfw_session * session, uint32_t index, nnfw_tensorinfo * tensor_info)
Get i-th output tensor info.
After nnfw_load_model_from_file and before nnfw_prepare is invoked, it returns tensor info in the model.
After nnfw_prepare and before nnfw_run is invoked, this function returns updated tensor info if tensor info is updated by nnfw_set_input_tensorinfo.
After nnfw_run is invoked(at least once), it returns the updated tensor info during the latest execution.
Parameters
[in] session Session from output information is to be extracted
[in] index Index of output
[out] tensor_info Tensor info (shape, type, etc)
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 250 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->output_tensorinfo(index, tensor_info);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_prepare()
NNFW_STATUS nnfw_prepare (nnfw_session * session)
Prepare session to be ready for inference.
This phase may finalize model compilation, scheduling, and additional settings. If nnfw_apply_tensor is called to apply input tensor info different with model before this function, tries to resize all tensors.
Parameters
[in] session the session to be prepared
Returns
NNFW_STATUS_NO_ERROR if successful, otherwise return NNFW_STATUS_ERROR
Definition at line 96 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->prepare();
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_query_info_u32()
NNFW_STATUS nnfw_query_info_u32 (nnfw_session * session, NNFW_INFO_ID id, uint32_t * val)
Retrieve uint32 type of nnfw information for given information ID.
Retrieves the information of property given by information id
Note
: The input session could be null for global information (e.g. runtime version).*
Parameters
[in] session session to be queried on.
[in] information ID to be queried
[out] val uint32 value to be returned.
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 321 of file nnfw_api.cc.
{
  (void)session;
  switch (id)
  {
    case NNFW_INFO_ID_VERSION:
      if (val)
      {
        *val = NNFW_VERSION;
        return NNFW_STATUS_NO_ERROR;
      }
      break;
    default:
      return NNFW_STATUS_ERROR;
  }
  // It should not be reached.
  return NNFW_STATUS_ERROR;
}
References NNFW_INFO_ID_VERSION, NNFW_STATUS_ERROR, NNFW_STATUS_NO_ERROR, and NNFW_VERSION.
nnfw_run()
NNFW_STATUS nnfw_run (nnfw_session * session)
Run inference.
This function should be called after model is loaded by nnfw_load_model_from_file, session is prepared for inference by nnfw_prepare, set input and output buffers by nnfw_set_input and nnfw_set_output.
This function return after inference is finished.
Parameters
[in] session The session to run inference
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 108 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->run();
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_run_async()
NNFW_STATUS nnfw_run_async (nnfw_session * session)
Run inference asynchronously.
This function must be called after model is loaded by nnfw_load_model_from_file, session is prepared for inference by nnfw_prepare, set input and output buffers by nnfw_set_input and nnfw_set_output.
This function returns immediately after starting a thread to run the inference. To get the result of it or to do the next inference with nnfw_run or nnfw_run_async, nnfw_await must be called to ensure the current asynchronous inference has finished. Only one asynchronous inference is allowed at a time for a session. If this function is called while the previous one is still running, it returns an error.
Parameters
[in] session The session to run inference
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 114 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->run_async();
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_set_available_backends()
NNFW_STATUS nnfw_set_available_backends (nnfw_session * session, const char * backends)
Set available backends.
This function should be called before nnfw_prepare is invoked.
Supported backends differs on each platforms. For example, x86_64 supports "cpu" only. Multiple backends can be set and they must be separated by a semicolon (ex: "acl_cl;cpu"). For each backend string, libbackend_{backend}.so will be dynamically loaded during nnfw_prepare. Among the multiple backends, the 1st element is used as the default backend.
Parameters
[in] session session to which avilable backends are set
[in] backends available backends on which nnfw uses
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 291 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_available_backends(backends);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_set_input()
NNFW_STATUS nnfw_set_input (nnfw_session * session, uint32_t index, NNFW_TYPE type, const void * buffer, size_t length)
Set input buffer.
This function must be called after nnfw_prepare, buffer given to this function can be reused for many inferences. length must be greater or equal than the operand requires. To specify an optional input, you can either not call this for that input or call this with buffer of NULL and length of 0.
Parameters
[in] session Session to the input is to be set
[in] index Index of input to be set (0-indexed)
[in] type Type of the input
[in] buffer Raw buffer for input
[in] length Size of bytes of input buffer
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 138 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_input(index, type, buffer, length);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_set_input_layout()
NNFW_STATUS nnfw_set_input_layout (nnfw_session * session, uint32_t index, NNFW_LAYOUT layout)
Set the layout of an input.
The input that does not call this has NNFW_LAYOUT_NHWC layout
Parameters
[in] session session from inference input is to be extracted
[in] index index of input to be set (0-indexed)
[in] layout layout to set to target input
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 203 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_input_layout(index, layout);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_set_input_tensorinfo()
NNFW_STATUS nnfw_set_input_tensorinfo (nnfw_session * session, uint32_t index, const nnfw_tensorinfo * tensor_info)
Set input model's tensor info for resizing.
This function can be called at any time after calling nnfw_model_load_from_file. Changing input tensor's shape will cause shape inference for the model. There are two different types of shape inference - static and dynamic. Which one to use is depend on the current state of the session. When it is called after calling nnfw_model_load_from_file and before calling nnfw_prepare, this info will be used when nnfw_prepare. And it will perform static shape inference for all tensors. When it is called after calling nnfw_prepare or even after nnfw_run, this info will be used when nnfw_run. And the shapes of the tensors are determined on the fly. If this function is called many times for the same index, it is overwritten.
Parameters
[in] session Session to the input tensor info is to be set
[in] index Index of input to be set (0-indexed)
[in] tensor_info Tensor info to be set
Returns
NNFW_STATUS_NO_ERROR if successful, otherwise return NNFW_STATUS_ERROR
Definition at line 278 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_input_tensorinfo(index, tensor_info);
}
References NNFW_RETURN_ERROR_IF_NULL.
nnfw_set_op_backend()
NNFW_STATUS nnfw_set_op_backend (nnfw_session * session, const char * op, const char * backend)
Set the operation's backend.
This function should be called before nnfw_prepare is invoked.
The backend for op has higher priority than available backends specified by nnfw_set_available_backends.
Parameters
[in] session session to be modified
[in] op operation to be set
[in] backend bakcend on which operation run
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 306 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_op_backend(op, backend);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_set_output()
NNFW_STATUS nnfw_set_output (nnfw_session * session, uint32_t index, NNFW_TYPE type, void * buffer, size_t length)
Set output buffer.
This function must be called after nnfw_prepare, buffer given to this function can be reused for many inferences. length must be greater or equal than the operand requires. An output operand can have unspecified shape and deduced dynamically during the execution. You must provide buffer large enough.
Parameters
[in] session Session from inference output is to be extracted
[in] index Index of output to be set (0-indexed)
[in] type Type of the output
[out] buffer Raw buffer for output
[in] length Size of bytes of output buffer
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 157 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_output(index, type, buffer, length);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by main().
nnfw_set_output_layout()
NNFW_STATUS nnfw_set_output_layout (nnfw_session * session, uint32_t index, NNFW_LAYOUT layout)
Set the layout of an output.
The output that does not call this has NNFW_LAYOUT_NHWC layout
Parameters
[in] session session from inference output is to be extracted
[in] index index of output to be set (0-indexed)
[in] layout layout to set to target output
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 219 of file nnfw_api.cc.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->set_output_layout(index, layout);
}
References NNFW_RETURN_ERROR_IF_NULL.