ONE - On-device Neural Engine: runtime/onert/api/python/src/bindings/nnfw_traininfo_bindings.cc File Reference
nnfw_traininfo_bindings.cc File Reference
#include "nnfw_traininfo_bindings.h"
#include "nnfw_api_wrapper.h"
Functions
void bind_nnfw_train_enums (py::module_ &m)
void bind_nnfw_loss_info (py::module_ &m)
void bind_nnfw_train_info (py::module_ &m)
Function Documentation
bind_nnfw_loss_info()
void bind_nnfw_loss_info (py::module_ & m)
Definition at line 54 of file nnfw_traininfo_bindings.cc.
{
  py::class_<nnfw_loss_info>(m, "lossinfo", py::module_local())
    .def(py::init<>()) // Default constructor
    .def_readwrite("loss", &nnfw_loss_info::loss, "Loss type")
    .def_readwrite("reduction_type", &nnfw_loss_info::reduction_type, "Reduction type");
}
References nnfw_loss_info::loss, m, and nnfw_loss_info::reduction_type.
Referenced by PYBIND11_MODULE().
bind_nnfw_train_enums()
void bind_nnfw_train_enums (py::module_ & m)
Definition at line 26 of file nnfw_traininfo_bindings.cc.
{
  // Bind NNFW_TRAIN_LOSS
  py::enum_<NNFW_TRAIN_LOSS>(m, "loss", py::module_local())
    .value("UNDEFINED", NNFW_TRAIN_LOSS_UNDEFINED)
    .value("MEAN_SQUARED_ERROR", NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR)
    .value("CATEGORICAL_CROSSENTROPY", NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY);
  // Bind NNFW_TRAIN_LOSS_REDUCTION
  py::enum_<NNFW_TRAIN_LOSS_REDUCTION>(m, "loss_reduction", py::module_local())
    .value("UNDEFINED", NNFW_TRAIN_LOSS_REDUCTION_UNDEFINED)
    .value("SUM_OVER_BATCH_SIZE", NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE)
    .value("SUM", NNFW_TRAIN_LOSS_REDUCTION_SUM);
  // Bind NNFW_TRAIN_OPTIMIZER
  py::enum_<NNFW_TRAIN_OPTIMIZER>(m, "optimizer", py::module_local())
    .value("UNDEFINED", NNFW_TRAIN_OPTIMIZER_UNDEFINED)
    .value("SGD", NNFW_TRAIN_OPTIMIZER_SGD)
    .value("ADAM", NNFW_TRAIN_OPTIMIZER_ADAM);
  // Bind NNFW_TRAIN_NUM_OF_TRAINABLE_OPS_SPECIAL_VALUES
  py::enum_<NNFW_TRAIN_NUM_OF_TRAINABLE_OPS_SPECIAL_VALUES>(m, "trainable_ops", py::module_local())
    .value("INCORRECT_STATE", NNFW_TRAIN_TRAINABLE_INCORRECT_STATE)
    .value("ALL", NNFW_TRAIN_TRAINABLE_ALL)
    .value("NONE", NNFW_TRAIN_TRAINABLE_NONE);
}
References m, NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY, NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR, NNFW_TRAIN_LOSS_REDUCTION_SUM, NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE, NNFW_TRAIN_LOSS_REDUCTION_UNDEFINED, NNFW_TRAIN_LOSS_UNDEFINED, NNFW_TRAIN_OPTIMIZER_ADAM, NNFW_TRAIN_OPTIMIZER_SGD, NNFW_TRAIN_OPTIMIZER_UNDEFINED, NNFW_TRAIN_TRAINABLE_ALL, NNFW_TRAIN_TRAINABLE_INCORRECT_STATE, and NNFW_TRAIN_TRAINABLE_NONE.
Referenced by PYBIND11_MODULE().
bind_nnfw_train_info()
void bind_nnfw_train_info (py::module_ & m)
Definition at line 63 of file nnfw_traininfo_bindings.cc.
{
  py::class_<nnfw_train_info>(m, "traininfo", py::module_local())
    .def(py::init<>()) // Default constructor
    .def_readwrite("learning_rate", &nnfw_train_info::learning_rate, "Learning rate")
    .def_readwrite("batch_size", &nnfw_train_info::batch_size, "Batch size")
    .def_readwrite("loss_info", &nnfw_train_info::loss_info, "Loss information")
    .def_readwrite("opt", &nnfw_train_info::opt, "Optimizer type")
    .def_readwrite("num_of_trainable_ops", &nnfw_train_info::num_of_trainable_ops,
                   "Number of trainable operations");
}
References nnfw_train_info::batch_size, nnfw_train_info::learning_rate, nnfw_train_info::loss_info, m, nnfw_train_info::num_of_trainable_ops, and nnfw_train_info::opt.
Referenced by PYBIND11_MODULE().