#!/bin/bash

NNMI_SCRIPT_RPATH="scripts"
NNMI_COMMAND_RPATH="infra/onert-micro/command"

NNMI_PROJECT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NNMI_SCRIPT_PATH="${NNMI_PROJECT_PATH}/${NNMI_SCRIPT_RPATH}"

function Usage()
{
  echo "Usage: $0 [COMMAND] ..."
  echo "Command:"
  for file in "$NNMI_COMMAND_RPATH"/*;
  do
    echo "  $(basename "$file")"
  done
}

# Get command from command-line
COMMAND=$1; shift

if [[ -z "${COMMAND}" ]]; then
  Usage
  exit 255
fi

COMMAND_FILE="${NNMI_PROJECT_PATH}/${NNMI_COMMAND_RPATH}/${COMMAND}"

if [[ ! -f "${COMMAND_FILE}" ]]; then
  echo "ERROR: '${COMMAND}' is not supported"
  Usage
  exit 255
fi

export NNMI_PROJECT_PATH
export NNMI_SCRIPT_PATH

function import()
{
  source "${NNMI_PROJECT_PATH}/infra/onert-micro/config/$1"
}

source "${COMMAND_FILE}" "$@"
