ONE - On-device Neural Engine: onert-micro/examples/speech_recognition/DISCO_F746/mbed-os/main.cpp File Reference
main.cpp File Reference
#include <luci_interpreter/Interpreter.h>
#include <iostream>
#include <vector>
#include "mbed.h"
#include "speech_recognition_float.circle.h"
#include "test_data.h"
Functions
std::vector< float > infer ()
void print_float (float x)
int main ()
Function Documentation
infer()
std::vector< float > infer ()
Definition at line 25 of file main.cpp.
{
  auto input_data = reinterpret_cast<float *>(interpreter.allocateInputTensor(0));
  for (int i = 0; i < 1960; ++i)
  {
    *(input_data + i) = test_data[i];
  }
  interpreter.interpret();
  auto data = interpreter.readOutputTensor(0);
  std::vector<float> output;
  for (int i = 0; i < 4; ++i)
  {
    output.push_back(*(reinterpret_cast<float *>(data) + i));
  }
  return output;
}
References test_data.
Referenced by moco::TFShapeInferenceRule::infer(), loco::CanonicalShapeInferenceRule::infer(), main(), moco::PlaneInference::operator()(), and moco::Padding2DInference::operator()().
main()
int main ()
Definition at line 58 of file main.cpp.
{
  Timer t;
  t.start();
  auto res = infer();
  t.stop();
  std::cout << "Executed in " << t.read_us() << "us\n";
  // Predictions after inference with TFLite on PC:
  std::cout << "CORRECT PREDICTION\n0.960639\n0.006082\n0.005203\n0.028074\n";
  std::cout << "MODEL PREDICTION\n";
  for (int i = 0; i < 4; ++i)
    print_float(res[i]);
  while (true)
  {
    ThisThread::sleep_for(100ms);
  }
}
References infer(), and print_float().
Referenced by main(), and utils::safemain().
print_float()
void print_float (float x)
Definition at line 41 of file main.cpp.
{
  int tmp = x * 1000000 - static_cast<int>(x) * 1000000;
  std::cout << (tmp >= 0 ? "" : "-") << static_cast<int>(x) << ".";
  int zeros_to_add = 0;
  for (int i = 100000; i >= 1; i = i / 10)
  {
    if (tmp / i != 0)
      break;
    zeros_to_add++;
  }
  for (int i = 0; i < zeros_to_add; ++i)
  {
    std::cout << "0";
  }
  std::cout << (tmp >= 0 ? tmp : -tmp) << "\n";
}
Referenced by main().