ONE - On-device Neural Engine: onert-micro/onert-micro/src/api/onert-micro.cpp File Reference
onert-micro.cpp File Reference
#include <string>
#include <memory>
#include <thread>
#include <vector>
#include <iostream>
#include <fstream>
#include "OMTrainingInterpreter.h"
#include "onert-micro.h"
#include <circle-generated/circle/schema_generated.h>
#include <circle-generated/circle/traininfo_generated.h>
Data Structures
struct nnfw_session
Macros
#define NNFW_RETURN_ERROR_IF_NULL(p)
Typedefs
using DataBuffer = std::vector< char >
Functions
DataBuffer readFile (const char *path)
NNFW_STATUS nnfw_create_session (nnfw_session **session)
Create a new session instance.
NNFW_STATUS nnfw_load_model_from_file (nnfw_session *session, const char *package_file_path)
Load model from nnpackage file or directory.
NNFW_STATUS nnfw_train_prepare (nnfw_session *session)
Prepare session to be ready for training.
NNFW_STATUS nnfw_train (nnfw_session *session, bool update_weights)
Train the model.
NNFW_STATUS nnfw_train_export_circle (nnfw_session *session, const char *path)
Export current training model into circle model.
NNFW_STATUS nnfw_train_export_checkpoint (nnfw_session *session, const char *path)
Export circle checkpoint.
NNFW_STATUS nnfw_train_import_checkpoint (nnfw_session *session, const char *path)
Import circle checkpoint.
NNFW_STATUS nnfw_train_set_input (nnfw_session *session, uint32_t index, void *input, const nnfw_tensorinfo *input_info)
Set training input.
NNFW_STATUS nnfw_train_set_expected (nnfw_session *session, uint32_t index, void *expected, const nnfw_tensorinfo *expected_info)
Set training expected output.
NNFW_STATUS nnfw_train_get_loss (nnfw_session *session, uint32_t index, float *loss)
Get loss value for expected output.
NNFW_STATUS nnfw_train_set_traininfo (nnfw_session *session, const nnfw_train_info *info)
Set training information.
NNFW_STATUS nnfw_train_set_output (nnfw_session *session, uint32_t index, NNFW_TYPE type, void *buffer, size_t length)
Set training output buffer.
Macro Definition Documentation
NNFW_RETURN_ERROR_IF_NULL
#define NNFW_RETURN_ERROR_IF_NULL (p)
Value:
  do                                      \
  {                                       \
    if ((p) == NULL)                      \
      return NNFW_STATUS_UNEXPECTED_NULL; \
  } while (0)
Definition at line 29 of file onert-micro.cpp.
  {                                       \
    if ((p) == NULL)                      \
      return NNFW_STATUS_UNEXPECTED_NULL; \
  } while (0)
Typedef Documentation
DataBuffer
using DataBuffer = std::vector<char>
Definition at line 37 of file onert-micro.cpp.
Function Documentation
nnfw_create_session()
NNFW_STATUS nnfw_create_session (nnfw_session ** session)
Create a new session instance.
This only creates a session. Model is loaded after nnfw_load_model_from_file is invoked. And inference is performed after nnfw_run is invoked.
nnfw_close_session should be called once if session is no longer needed
Parameters
[out] session The session to be created
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 390 of file onert-micro.cpp.
{ return nnfw_session::create(session); }
nnfw_load_model_from_file()
NNFW_STATUS nnfw_load_model_from_file (nnfw_session * session, const char * package_file_path)
Load model from nnpackage file or directory.
Load model from path to model or nnpackage.
The length of package_file_path must not exceed 1024 bytes including zero at the end.
Parameters
[in] session nnfw_session loading the given nnpackage file/dir
[in] package_file_path Path to the nnpackage file or unzipped directory to be loaded
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 392 of file onert-micro.cpp.
{
  return session->load_model_from_file(package_file_path);
}
nnfw_train()
NNFW_STATUS nnfw_train (nnfw_session * session, bool update_weights)
Train the model.
Note
This function should be called after nnfw_train_set_input and nnfw_train_set_expected for each input and expected output
In order to use update_weights as false, it should be called after nnfw_train_set_output.
Parameters
[in] session The session to be trained
[in] update_weights If true, update weights of the model If false, do not update weights of the model (for validation)
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 399 of file onert-micro.cpp.
{
  return session->train_run(update_weights);
}
nnfw_train_export_checkpoint()
NNFW_STATUS nnfw_train_export_checkpoint (nnfw_session * session, const char * path)
Export circle checkpoint.
Note
This function should be called on training mode This function should be called after nnfw_train
Parameters
[in] session The session to export a checkpoint
[in] path The path to export a checkpoint
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 409 of file onert-micro.cpp.
{
  return session->train_export_checkpoint(path);
}
nnfw_train_export_circle()
NNFW_STATUS nnfw_train_export_circle (nnfw_session * session, const char * path)
Export current training model into circle model.
Export circle model.
Note
This function should be called on training mode This function should be called after nnfw_train
Parameters
[in] session The session to export inference model
[in] path The path to export inference model
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 404 of file onert-micro.cpp.
{
  return session->train_export_circle(path);
}
nnfw_train_get_loss()
NNFW_STATUS nnfw_train_get_loss (nnfw_session * session, uint32_t index, float * loss)
Get loss value for expected output.
Note
This function should be called after nnfw_train
Parameters
[in] session The session to get loss value
[in] index The index of loss value [0, number of expected outputs)
[out] loss The loss value
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 433 of file onert-micro.cpp.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->train_get_loss(index, loss);
}
nnfw_train_import_checkpoint()
NNFW_STATUS nnfw_train_import_checkpoint (nnfw_session * session, const char * path)
Import circle checkpoint.
Note
This function should be called on training mode This function should be called before nnfw_train
Parameters
[in] session The session to export a checkpoint
[in] path The path to export a checkpoint
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 414 of file onert-micro.cpp.
{
  return session->train_import_checkpoint(path);
}
nnfw_train_prepare()
NNFW_STATUS nnfw_train_prepare (nnfw_session * session)
Prepare session to be ready for training.
Note
The session will be entered into training mode
   If training info is NOT set in session, this function returns @c NNFW_STATUS_ERROR .
   You should set training info using {@link nnfw_train_set_traininfo}.
Parameters
[in] session The session to be prepared for training
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 397 of file onert-micro.cpp.
{ return session->train_prepare(); }
nnfw_train_set_expected()
NNFW_STATUS nnfw_train_set_expected (nnfw_session * session, uint32_t index, void * expected, const nnfw_tensorinfo * expected_info)
Set training expected output.
Note
This function should be called after nnfw_train_prepare
Parameters
session The session to be set training inputs and expected model outputs
index The index of training expected output
expected The expected buffers for training
expected_info The shape and type of expected buffer If it is nullptr, it will not change shape and batch size
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 426 of file onert-micro.cpp.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->train_set_expected(index, expected);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by onert::api::python::NNFW_SESSION::train_set_expected().
nnfw_train_set_input()
NNFW_STATUS nnfw_train_set_input (nnfw_session * session, uint32_t index, void * input, const nnfw_tensorinfo * input_info)
Set training input.
Note
This function should be called after nnfw_train_prepare
Parameters
[in] session The session to be set training inputs and expected model outputs
[in] index The index of training input
[in] input The input buffers for training
[in] input_info The shape and type of input buffer If it is nullptr, it will not change shape and batch size
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 419 of file onert-micro.cpp.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->train_set_input(index, input);
}
References NNFW_RETURN_ERROR_IF_NULL.
Referenced by onert::api::python::NNFW_SESSION::train_set_input().
nnfw_train_set_output()
NNFW_STATUS nnfw_train_set_output (nnfw_session * session, uint32_t index, NNFW_TYPE type, void * buffer, size_t length)
Set training output buffer.
This function must be called after nnfw_train_prepare, buffer given to this function can be reused for training. length must be greater or equal than the operand requires. An output operand can have unspecified shape and deduced dynamically during the execution. You must provide buffer large enough.
Parameters
[in] session Session from inference output is to be extracted
[in] index Index of output to be set (0-indexed)
[in] type Type of the output
[out] buffer Raw buffer for output
[in] length Size of bytes of output buffer
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 445 of file onert-micro.cpp.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->train_set_output(index, type, buffer, length);
}
nnfw_train_set_traininfo()
NNFW_STATUS nnfw_train_set_traininfo (nnfw_session * session, const nnfw_train_info * info)
Set training information.
Note
This function should be called after calling nnfw_load_model_from_file and before calling nnfw_train_prepare
Parameters
[in] session The session to be set training information
[in] info The training information
Returns
NNFW_STATUS_NO_ERROR if successful
Definition at line 439 of file onert-micro.cpp.
{
  NNFW_RETURN_ERROR_IF_NULL(session);
  return session->train_set_traininfo(info);
}
readFile()
DataBuffer readFile (const char * path)
Definition at line 39 of file onert-micro.cpp.
{
  std::ifstream file(path, std::ios::binary | std::ios::in);
  if (!file.good())
  {
    std::string errmsg = "Failed to open file";
    std::cerr << errmsg << std::endl;
    exit(-1); // FIXME: proper way
  }
  file.seekg(0, std::ios::end);
  auto fileSize = file.tellg();
  file.seekg(0, std::ios::beg);
  // reserve capacity
  DataBuffer model_data(fileSize);
  // read the data
  file.read(model_data.data(), fileSize);
  if (file.fail())
  {
    std::string errmsg = "Failed to read file";
    std::cerr << errmsg << std::endl;
    exit(-1); // FIXME: proper way
  }
  return model_data;
}
Referenced by entry(), and nnfw_session::load_model_from_file().