ONE - On-device Neural Engine: compiler/onnx2circle/src/onnx2circle.cpp File Reference
onnx2circle.cpp File Reference
#include "exo/LoggingContext.h"
#include "exo/CircleExporter.h"
#include "mir2loco.h"
#include "ONNXImporterImpl.h"
#include "locop/FormattedGraph.h"
#include "hermes/ConsoleReporter.h"
#include "hermes/EnvConfig.h"
#include <cassert>
#include <memory>
#include <iostream>
#include <stdexcept>
#include <string>
Macros
#define LOGGER(name) ::Logger name { ::LoggingContext::get() }
#define INFO(name) HERMES_INFO(name)
Functions
int main (int argc, char **argv)
Macro Definition Documentation
INFO
#define INFO (name) HERMES_INFO(name)
Definition at line 75 of file onnx2circle.cpp.
LOGGER
#define LOGGER (name) ::Logger name { ::LoggingContext::get() }
Definition at line 72 of file onnx2circle.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 77 of file onnx2circle.cpp.
{
  using EnvConfig = hermes::EnvConfig<hermes::EnvFormat::BooleanNumber>;
  // This line allows users to control all the exo-circle loggers via ONNX2CIRCLE_Log_Backend
  exo::LoggingContext::get()->config(std::make_unique<EnvConfig>("ONNX2CIRCLE_Log_Backend"));
  LOGGER(l);
  // TODO We need better args parsing in future
  if (!(argc == 3))
  {
    print_help();
    return 255;
  }
  std::string onnx_path{argv[1]}; // .pb file
  std::string circle_path{argv[2]};
  std::cout << "Import from '" << onnx_path << "'" << std::endl;
  auto mir_g = mir_onnx::loadModel(onnx_path);
  auto loco_g = mir2loco::Transformer().transform(mir_g.get());
  std::cout << "Import from '" << onnx_path << "' - Done" << std::endl;
  INFO(l) << "Import Graph" << std::endl;
  INFO(l) << locop::fmt<locop::Formatter::LinearV1>(loco_g) << std::endl;
  std::cout << "Export into '" << circle_path << "'" << std::endl;
  exo::CircleExporter(loco_g.get()).dumpToFile(circle_path.c_str());
  std::cout << "Export into '" << circle_path << "' - Done" << std::endl;
  return 0;
}
References hermes::Context::config(), exo::CircleExporter::dumpToFile(), exo::LoggingContext::get(), INFO, mir_onnx::loadModel(), LOGGER, and mir2loco::Transformer::transform().