ONE - On-device Neural Engine: runtime/onert/core/include/util/Utils.h File Reference
Utils.h File Reference
This file contains utility macro.
#include "ir/Coordinates.h"
#include "ir/Shape.h"
Data Structures
struct ForEachDimension< from, to, Enable >
struct ForEachDimension< from, to, typename std::enable_if< from==to >::type >
Macros
#define UNUSED_RELEASE(a) (void)(a)
Functions
template<typename L , typename... Args>
void ShapeLoop (const onert::ir::Shape &shape, L &&lambda_function, Args &&... args)
Detailed Description
This file contains utility macro.
Definition in file Utils.h.
Macro Definition Documentation
UNUSED_RELEASE
#define UNUSED_RELEASE (a) (void)(a)
Definition at line 28 of file Utils.h.
Function Documentation
ShapeLoop()
template<typename L , typename... Args> void ShapeLoop (const onert::ir::Shape & shape, L && lambda_function, Args &&... args) inline
Definition at line 63 of file Utils.h.
{
  assert(shape.rank() > 0);
  for (auto i = 0; i < shape.rank(); ++i)
  {
    assert(shape.dim(i) > 0);
  }
  onert::ir::Coordinates coords;
  switch (shape.rank())
  {
    case 0:
      coords.set(0, 0);
      ForEachDimension<0, 0>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 1:
      ForEachDimension<0, 1>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 2:
      ForEachDimension<0, 2>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 3:
      ForEachDimension<0, 3>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 4:
      ForEachDimension<0, 4>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 5:
      ForEachDimension<0, 5>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    case 6:
      ForEachDimension<0, 6>::unroll(shape, coords, std::forward<L>(lambda_function),
                                     std::forward<Args>(args)...);
      break;
    default:
      assert(false && "ShapeLoop, 1 <= Shape'rank <= 6");
      break;
  }
}
References coords, and ForEachDimension< from, to, Enable >::unroll().
Referenced by onert::exec::CopyDynamic(), and onert::exec::UpdateOffsets().