ONE - On-device Neural Engine: luci_interpreter::lstm::LSTMStruct Struct Reference
luci_interpreter::lstm::LSTMStruct Struct Reference
#include <UnidirectionalSequenceLSTM.h>
Public Member Functions
LSTMStruct ()=delete
LSTMStruct (const LSTMStruct &)=delete
LSTMStruct (const circle::Operator *cur_op, luci_interpreter::BaseRuntimeGraph *runtime_graph)
void validateTensorTypes ()
const circle::Tensor * input ()
const circle::Tensor * input_to_input_weights ()
const circle::Tensor * input_to_forget_weights ()
const circle::Tensor * input_to_cell_weights ()
const circle::Tensor * input_to_output_weights ()
const circle::Tensor * recurrent_to_input_weights ()
const circle::Tensor * recurrent_to_forget_weights ()
const circle::Tensor * recurrent_to_cell_weights ()
const circle::Tensor * recurrent_to_output_weights ()
const circle::Tensor * cell_to_input_weights ()
const circle::Tensor * cell_to_forget_weights ()
const circle::Tensor * cell_to_output_weights ()
const circle::Tensor * input_gate_bias ()
const circle::Tensor * forget_gate_bias ()
const circle::Tensor * cell_gate_bias ()
const circle::Tensor * output_gate_bias ()
const circle::Tensor * projection_weights ()
const circle::Tensor * projection_bias ()
const circle::Tensor * output_state ()
const circle::Tensor * cell_state ()
const circle::Tensor * input_layer_norm_coefficients ()
const circle::Tensor * forget_layer_norm_coefficients ()
const circle::Tensor * cell_layer_norm_coefficients ()
const circle::Tensor * output_layer_norm_coefficients ()
const circle::Tensor * output ()
const circle::Tensor * get_internal_tensor (int i)
Data Fields
const circle::UnidirectionalSequenceLSTMOptions * options
Detailed Description
Definition at line 27 of file UnidirectionalSequenceLSTM.h.
Constructor & Destructor Documentation
LSTMStruct() [1/3]
luci_interpreter::lstm::LSTMStruct::LSTMStruct () delete
LSTMStruct() [2/3]
luci_interpreter::lstm::LSTMStruct::LSTMStruct (const LSTMStruct &) delete
LSTMStruct() [3/3]
luci_interpreter::lstm::LSTMStruct::LSTMStruct (const circle::Operator * cur_op, luci_interpreter::BaseRuntimeGraph * runtime_graph) inline explicit
Definition at line 32 of file UnidirectionalSequenceLSTM.h.
  {
    const auto input_index = cur_op->inputs()->operator[](0);
    const auto input_to_input_weights_index = cur_op->inputs()->operator[](1);
    const auto input_to_forget_weights_index = cur_op->inputs()->operator[](2);
    const auto input_to_cell_weights_index = cur_op->inputs()->operator[](3);
    const auto input_to_output_weights_index = cur_op->inputs()->operator[](4);
    assert(input_index != -1);
    // input_to_input_weights_index - optional
    assert(input_to_forget_weights_index != -1);
    assert(input_to_cell_weights_index != -1);
    assert(input_to_output_weights_index != -1);
    internal_tensors[0] = runtime_graph->getCircleTensorByIndex(input_index);
    internal_tensors[1] = runtime_graph->getCircleTensorByIndex(input_to_input_weights_index);
    internal_tensors[2] = runtime_graph->getCircleTensorByIndex(input_to_forget_weights_index);
    internal_tensors[3] = runtime_graph->getCircleTensorByIndex(input_to_cell_weights_index);
    internal_tensors[4] = runtime_graph->getCircleTensorByIndex(input_to_output_weights_index);
    const auto recurrent_to_input_weights_index = cur_op->inputs()->operator[](5);
    const auto recurrent_to_forget_weights_index = cur_op->inputs()->operator[](6);
    const auto recurrent_to_cell_weights_index = cur_op->inputs()->operator[](7);
    const auto recurrent_to_output_weights_index = cur_op->inputs()->operator[](8);
    // recurrent_to_input_weights_index - optional
    assert(recurrent_to_forget_weights_index != -1);
    assert(recurrent_to_cell_weights_index != -1);
    assert(recurrent_to_output_weights_index != -1);
    internal_tensors[5] = runtime_graph->getCircleTensorByIndex(recurrent_to_input_weights_index);
    internal_tensors[6] = runtime_graph->getCircleTensorByIndex(recurrent_to_forget_weights_index);
    internal_tensors[7] = runtime_graph->getCircleTensorByIndex(recurrent_to_cell_weights_index);
    internal_tensors[8] = runtime_graph->getCircleTensorByIndex(recurrent_to_output_weights_index);
    const auto cell_to_input_weights_index = cur_op->inputs()->operator[](9);
    const auto cell_to_forget_weights_index = cur_op->inputs()->operator[](10);
    const auto cell_to_output_weights_index = cur_op->inputs()->operator[](11);
    // optional cell_to_input_weights_index
    // optional cell_to_forget_weights_index
    // optional cell_to_output_weights_index
    internal_tensors[9] = runtime_graph->getCircleTensorByIndex(cell_to_input_weights_index);
    internal_tensors[10] = runtime_graph->getCircleTensorByIndex(cell_to_forget_weights_index);
    internal_tensors[11] = runtime_graph->getCircleTensorByIndex(cell_to_output_weights_index);
    const auto input_gate_bias_index = cur_op->inputs()->operator[](12);
    const auto forget_gate_bias_index = cur_op->inputs()->operator[](13);
    const auto cell_gate_bias_index = cur_op->inputs()->operator[](14);
    const auto output_gate_bias_index = cur_op->inputs()->operator[](15);
    // optional input_gate_bias_index
    assert(forget_gate_bias_index != -1);
    assert(cell_gate_bias_index != -1);
    assert(output_gate_bias_index != -1);
    internal_tensors[12] = runtime_graph->getCircleTensorByIndex(input_gate_bias_index);
    internal_tensors[13] = runtime_graph->getCircleTensorByIndex(forget_gate_bias_index);
    internal_tensors[14] = runtime_graph->getCircleTensorByIndex(cell_gate_bias_index);
    internal_tensors[15] = runtime_graph->getCircleTensorByIndex(output_gate_bias_index);
    const auto projection_weights_index = cur_op->inputs()->operator[](16);
    const auto projection_bias_index = cur_op->inputs()->operator[](17);
    // optional projection_weights_index
    // optional projection_bias_index
    internal_tensors[16] = runtime_graph->getCircleTensorByIndex(projection_weights_index);
    internal_tensors[17] = runtime_graph->getCircleTensorByIndex(projection_bias_index);
    const auto output_state_index = cur_op->inputs()->operator[](18);
    const auto cell_state_index = cur_op->inputs()->operator[](19);
    assert(output_state_index != -1);
    assert(cell_state_index != -1);
    internal_tensors[18] = runtime_graph->getCircleTensorByIndex(output_state_index);
    internal_tensors[19] = runtime_graph->getCircleTensorByIndex(cell_state_index);
    const auto input_layer_norm_coefficients_index = cur_op->inputs()->operator[](20);
    const auto forget_layer_norm_coefficients_index = cur_op->inputs()->operator[](21);
    const auto cell_layer_norm_coefficients_index = cur_op->inputs()->operator[](22);
    const auto output_layer_norm_coefficients_index = cur_op->inputs()->operator[](23);
    // optional input_layer_norm_coefficients_index
    // optional forget_layer_norm_coefficients_index
    // optional cell_layer_norm_coefficients_index
    // optional output_layer_norm_coefficients_index
    internal_tensors[20] =
      runtime_graph->getCircleTensorByIndex(input_layer_norm_coefficients_index);
    internal_tensors[21] =
      runtime_graph->getCircleTensorByIndex(forget_layer_norm_coefficients_index);
    internal_tensors[22] =
      runtime_graph->getCircleTensorByIndex(cell_layer_norm_coefficients_index);
    internal_tensors[23] =
      runtime_graph->getCircleTensorByIndex(output_layer_norm_coefficients_index);
    const auto output_index = cur_op->outputs()->operator[](0);
    assert(output_index != -1);
    output_internal = runtime_graph->getCircleTensorByIndex(output_index);
    options = cur_op->builtin_options_as_UnidirectionalSequenceLSTMOptions();
  }
References luci_interpreter::RuntimeGraph::getCircleTensorByIndex(), and options.
Member Function Documentation
cell_gate_bias()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_gate_bias () inline
Definition at line 163 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[14]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
cell_layer_norm_coefficients()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_layer_norm_coefficients () inline
Definition at line 174 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[22]; };
cell_state()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_state () inline
Definition at line 170 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[19]; };
cell_to_forget_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_to_forget_weights () inline
Definition at line 158 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[10]; };
cell_to_input_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_to_input_weights () inline
Definition at line 157 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[9]; };
cell_to_output_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::cell_to_output_weights () inline
Definition at line 159 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[11]; };
forget_gate_bias()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::forget_gate_bias () inline
Definition at line 162 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[13]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep(), and validateTensorTypes().
forget_layer_norm_coefficients()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::forget_layer_norm_coefficients () inline
Definition at line 173 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[21]; };
get_internal_tensor()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::get_internal_tensor (int i) inline
Definition at line 180 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[i]; }
Referenced by luci_interpreter::configure_kernel_CircleUnidirectionalSequenceLSTM().
input()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input () inline
Definition at line 145 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[0]; };
Referenced by luci_interpreter::configure_kernel_CircleUnidirectionalSequenceLSTM(), luci_interpreter_pal::evalLSTM(), luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >(), luci_interpreter_pal::lstm_internal::lstmStep(), and validateTensorTypes().
input_gate_bias()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_gate_bias () inline
Definition at line 161 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[12]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
input_layer_norm_coefficients()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_layer_norm_coefficients () inline
Definition at line 172 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[20]; };
input_to_cell_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_to_cell_weights () inline
Definition at line 149 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[3]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
input_to_forget_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_to_forget_weights () inline
Definition at line 148 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[2]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep(), and validateTensorTypes().
input_to_input_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_to_input_weights () inline
Definition at line 147 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[1]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
input_to_output_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::input_to_output_weights () inline
Definition at line 150 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[4]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
output()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::output () inline
Definition at line 176 of file UnidirectionalSequenceLSTM.h.
{ return output_internal; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep(), and validateTensorTypes().
output_gate_bias()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::output_gate_bias () inline
Definition at line 164 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[15]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
output_layer_norm_coefficients()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::output_layer_norm_coefficients () inline
Definition at line 175 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[23]; };
output_state()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::output_state () inline
Definition at line 169 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[18]; };
Referenced by luci_interpreter_pal::evalLSTM(), luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >(), and validateTensorTypes().
projection_bias()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::projection_bias () inline
Definition at line 167 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[17]; };
projection_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::projection_weights () inline
Definition at line 166 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[16]; };
recurrent_to_cell_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::recurrent_to_cell_weights () inline
Definition at line 154 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[7]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
recurrent_to_forget_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::recurrent_to_forget_weights () inline
Definition at line 153 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[6]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
recurrent_to_input_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::recurrent_to_input_weights () inline
Definition at line 152 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[5]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
recurrent_to_output_weights()
const circle::Tensor * luci_interpreter::lstm::LSTMStruct::recurrent_to_output_weights () inline
Definition at line 155 of file UnidirectionalSequenceLSTM.h.
{ return internal_tensors[8]; };
Referenced by luci_interpreter_pal::lstm_internal::lstmStep().
validateTensorTypes()
void luci_interpreter::lstm::LSTMStruct::validateTensorTypes () inline
Definition at line 125 of file UnidirectionalSequenceLSTM.h.
  {
    LUCI_INTERPRETER_CHECK(Tensor::element_type(input()) == Tensor::element_type(output_state()));
    LUCI_INTERPRETER_CHECK(Tensor::element_type(output()) == Tensor::element_type(input()));
    for (int32_t i = 1; i < 9; ++i)
    {
      LUCI_INTERPRETER_CHECK(internal_tensors[i] == nullptr or
                             Tensor::element_type(input_to_forget_weights()) ==
                               Tensor::element_type(internal_tensors[i]));
    }
    for (int32_t i = 12; i < 16; ++i)
    {
      LUCI_INTERPRETER_CHECK(internal_tensors[i] == nullptr or
                             Tensor::element_type(forget_gate_bias()) ==
                               Tensor::element_type(internal_tensors[i]));
    }
  }
References forget_gate_bias(), input(), input_to_forget_weights(), LUCI_INTERPRETER_CHECK, output(), and output_state().
Referenced by luci_interpreter::configure_kernel_CircleUnidirectionalSequenceLSTM().
Field Documentation
options
const circle::UnidirectionalSequenceLSTMOptions* luci_interpreter::lstm::LSTMStruct::options
Definition at line 178 of file UnidirectionalSequenceLSTM.h.
Referenced by luci_interpreter::configure_kernel_CircleUnidirectionalSequenceLSTM(), luci_interpreter_pal::evalLSTM(), luci_interpreter_pal::evalLSTM< int8_t, int8_t, int16_t, int32_t >(), and LSTMStruct().
The documentation for this struct was generated from the following file:
onert-micro/luci-interpreter/src/kernels/UnidirectionalSequenceLSTM.h