ONE - On-device Neural Engine: loco::CanonicalShapeInferenceRule Struct Reference
loco::CanonicalShapeInferenceRule Struct Reference final
Shape inference rule for canonical dialect.
#include <CanonicalShapeInferenceRule.h>
Public Member Functions
bool support (const API &ver) const final
Check whether a given API is available or not.
bool recognize (const Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const Node *, NodeShape &) const final
Infer node's shape.
void infer (const Context *, const Node *, Sink *) const final
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Shape inference rule for canonical dialect.
Definition at line 28 of file CanonicalShapeInferenceRule.h.
Member Function Documentation
infer() [1/2]
void loco::CanonicalShapeInferenceRule::infer (const Context * ctx, const Node * node, Sink * sink) const final virtual
Reimplemented from loco::ShapeInferenceRule.
Definition at line 763 of file CanonicalShapeInferenceRule.cpp.
{
  assert(node->dialect() == loco::CanonicalDialect::get());
  assert(dynamic_cast<const loco::CanonicalNode *>(node) != nullptr);
  ForwardShapeInferenceAlgorithm alg{ctx};
  auto shape = loco::must_cast<const loco::CanonicalNode *>(node)->accept(&alg);
  sink->okay(shape);
}
References loco::Node::dialect(), and loco::CanonicalDialect::get().
infer() [2/2]
bool loco::CanonicalShapeInferenceRule::infer (const Node * , NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 745 of file CanonicalShapeInferenceRule.cpp.
{
  ::compat::Context ctx;
  ::compat::Sink sink;
  infer(&ctx, node, &sink);
  assert(sink.status() == ::compat::Sink::Okay or sink.status() == ::compat::Sink::Fail);
  if (sink.status() == ::compat::Sink::Fail)
  {
    return false;
  }
  shape = sink.shape();
  return true;
}
References infer().
Referenced by infer().
recognize()
bool loco::CanonicalShapeInferenceRule::recognize (const Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 740 of file CanonicalShapeInferenceRule.cpp.
{
  return CanonicalDialect::get() == d;
}
References loco::CanonicalDialect::get().
support()
bool loco::CanonicalShapeInferenceRule::support (const API & api) const final virtual
Check whether a given API is available or not.
Reimplemented from loco::ShapeInferenceRule.
Definition at line 735 of file CanonicalShapeInferenceRule.cpp.
{
  return api == API::V1 or api == API::V2;
}
References loco::ShapeInferenceRule::V1, and loco::ShapeInferenceRule::V2.
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/Service/CanonicalShapeInferenceRule.h
compiler/loco/src/Service/CanonicalShapeInferenceRule.cpp