ONE - On-device Neural Engine: onert_micro::core::memory::OMMemoryManager Struct Reference
onert_micro::core::memory::OMMemoryManager Struct Reference
#include <OMMemoryManager.h>
Static Public Member Functions
static OMStatus allocateMemory (uint32_t size, uint8_t **data)
static OMStatus deallocateMemory (uint8_t *data)
Detailed Description
Definition at line 31 of file OMMemoryManager.h.
Member Function Documentation
allocateMemory()
OMStatus OMMemoryManager::allocateMemory (uint32_t size, uint8_t ** data) static
Definition at line 22 of file OMMemoryManager.cpp.
{
  if (size == 0)
    return UnknownError;
  auto data_tmp = new uint8_t[size];
  *data = data_tmp;
  if (*data == nullptr)
    return UnknownError;
  return Ok;
}
References onert_micro::Ok, size, and onert_micro::UnknownError.
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocate(), and onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs().
deallocateMemory()
OMStatus OMMemoryManager::deallocateMemory (uint8_t * data) static
Definition at line 36 of file OMMemoryManager.cpp.
{
  delete[] data;
  return Ok;
}
References onert_micro::Ok.
Referenced by onert_micro::core::memory::OMRuntimeAllocator::allocateGraphInputs(), onert_micro::core::memory::OMRuntimeAllocator::clearAllTensorsData(), and onert_micro::core::memory::OMRuntimeAllocator::deallocate().
The documentation for this struct was generated from the following files:
onert-micro/onert-micro/include/core/memory/OMMemoryManager.h
onert-micro/onert-micro/src/core/memory/OMMemoryManager.cpp