ONE - On-device Neural Engine: luci::QuantizeWithPredecessorPass Struct Reference
luci::QuantizeWithPredecessorPass Struct Reference final
Class to quantize nodes using their predecessors' qparam.
#include <QuantizeWithPredecessorPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Class to quantize nodes using their predecessors' qparam.
Definition at line 29 of file QuantizeWithPredecessorPass.h.
Member Function Documentation
name()
const char * luci::QuantizeWithPredecessorPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 31 of file QuantizeWithPredecessorPass.h.
{ return "luci::QuantizeWithPredecessor"; }
run()
bool luci::QuantizeWithPredecessorPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 136 of file QuantizeWithPredecessorPass.cpp.
{
  bool changed = false;
  LOGGER(l);
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    INFO(l) << "QuantizeWithPredecessorPass visit node: " << circle_node->name() << std::endl;
    QuantizeWithPredecessor qwp;
    if (circle_node->accept(&qwp))
    {
      changed = true;
    }
  }
  return changed;
}
References loco::active_nodes(), INFO, LOGGER, and loco::output_nodes().
Referenced by package.libnnfw_api_pybind.nnfw_session_wrapper::inference(), and luci::QuantizeOnnxFakeQuantModelPass::run().
The documentation for this struct was generated from the following files:
compiler/luci/pass/src/QuantizeWithPredecessorPass.h
compiler/luci/pass/src/QuantizeWithPredecessorPass.cpp