ONE - On-device Neural Engine: rua::RuntimeService Struct Reference
rua::RuntimeService Struct Reference abstract
A wrapper for Android NN rutime itself.
#include <Service.h>
Public Member Functions
virtual ~RuntimeService ()=default
virtual const MemoryService * memory (void) const =0
virtual const ModelService * model (void) const =0
virtual const CompilationService * compilation (void) const =0
virtual const ExecutionService * execution (void) const =0
virtual const EventService * event (void) const =0
Detailed Description
A wrapper for Android NN rutime itself.
Definition at line 146 of file Service.h.
Constructor & Destructor Documentation
~RuntimeService()
virtual rua::RuntimeService::~RuntimeService () virtual default
Member Function Documentation
compilation()
virtual const CompilationService * rua::RuntimeService::compilation (void) const pure virtual
Referenced by ANeuralNetworksCompilation_create(), ANeuralNetworksCompilation_finish(), ANeuralNetworksCompilation_free(), and ANeuralNetworksCompilation_setPreference().
event()
virtual const EventService * rua::RuntimeService::event (void) const pure virtual
Referenced by ANeuralNetworksEvent_free(), and ANeuralNetworksEvent_wait().
execution()
virtual const ExecutionService * rua::RuntimeService::execution (void) const pure virtual
Referenced by ANeuralNetworksExecution_create(), ANeuralNetworksExecution_free(), ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), ANeuralNetworksExecution_setOutputFromMemory(), and ANeuralNetworksExecution_startCompute().
memory()
virtual const MemoryService * rua::RuntimeService::memory (void) const pure virtual
Referenced by ANeuralNetworksMemory_createFromFd(), and ANeuralNetworksMemory_free().
model()
virtual const ModelService * rua::RuntimeService::model (void) const pure virtual
Referenced by ANeuralNetworksModel_addOperand(), ANeuralNetworksModel_addOperation(), ANeuralNetworksModel_create(), ANeuralNetworksModel_finish(), ANeuralNetworksModel_free(), ANeuralNetworksModel_identifyInputsAndOutputs(), ANeuralNetworksModel_relaxComputationFloat32toFloat16(), ANeuralNetworksModel_setOperandValue(), and ANeuralNetworksModel_setOperandValueFromMemory().
The documentation for this struct was generated from the following file:
runtime/libs/rua/core/include/rua/Service.h