ONE - On-device Neural Engine: circle_eval_diff::TensorDataType Struct Reference
circle_eval_diff::TensorDataType Struct Reference
#include <Tensor.h>
Public Member Functions
const loco::DataType & dtype (void) const
void dtype (const loco::DataType &dtype)
Detailed Description
Definition at line 28 of file Tensor.h.
Member Function Documentation
dtype() [1/2]
void circle_eval_diff::TensorDataType::dtype (const loco::DataType & dtype) inline
Definition at line 32 of file Tensor.h.
{ _dtype = dtype; }
References dtype().
Referenced by dtype().
dtype() [2/2]
const loco::DataType & circle_eval_diff::TensorDataType::dtype (void) const inline
Definition at line 31 of file Tensor.h.
{ return _dtype; }
Referenced by circle_eval_diff::Tensor::at(), and circle_eval_diff::Tensor::size().
The documentation for this struct was generated from the following file:
compiler/circle-eval-diff/src/Tensor.h