ONE - On-device Neural Engine: coco::FeatureLayout Struct Reference
coco::FeatureLayout Struct Reference abstract
A FeatureLayout connects each feature index to a Bag element.
#include <FeatureLayout.h>
Data Structures
struct ID
Public Member Functions
virtual ~FeatureLayout ()=default
virtual const ID * id (void) const =0
virtual const FeatureShape & shape (void) const =0
uint32_t batch (void) const
uint32_t depth (void) const
uint32_t height (void) const
uint32_t width (void) const
virtual ElemID at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const =0
Detailed Description
A FeatureLayout connects each feature index to a Bag element.
NOTE FeatureLayout is an immutable interface
Definition at line 31 of file FeatureLayout.h.
Constructor & Destructor Documentation
~FeatureLayout()
virtual coco::FeatureLayout::~FeatureLayout () virtual default
Member Function Documentation
at()
virtual ElemID coco::FeatureLayout::at (uint32_t b, uint32_t ch, uint32_t row, uint32_t col) const pure virtual
Implemented in coco::FeatureLayouts::BCHW, coco::FeatureLayouts::BHWC, coco::FeatureLayouts::BC, and coco::FeatureLayouts::Generic.
Referenced by tflimport::SubGraphBuilder::build().
batch()
uint32_t coco::FeatureLayout::batch (void) const inline
Definition at line 44 of file FeatureLayout.h.
{ return shape().batch(); }
References coco::FeatureShape::batch(), and shape().
Referenced by coco::FeatureLayouts::BC::at(), and coco::FeatureLayouts::Generic::reorder().
depth()
uint32_t coco::FeatureLayout::depth (void) const inline
Definition at line 45 of file FeatureLayout.h.
{ return shape().depth(); }
References nncc::core::ADT::feature::Shape::depth(), and shape().
height()
uint32_t coco::FeatureLayout::height (void) const inline
Definition at line 46 of file FeatureLayout.h.
{ return shape().height(); }
References nncc::core::ADT::feature::Shape::height(), and shape().
id()
virtual const ID * coco::FeatureLayout::id (void) const pure virtual
Implemented in coco::FeatureLayouts::BCHW, coco::FeatureLayouts::BHWC, coco::FeatureLayouts::BC, and coco::FeatureLayouts::Generic.
shape()
virtual const FeatureShape & coco::FeatureLayout::shape (void) const pure virtual
Implemented in coco::FeatureLayouts::BCHW, coco::FeatureLayouts::BHWC, coco::FeatureLayouts::BC, and coco::FeatureLayouts::Generic.
Referenced by batch(), caffeimport::ConcatBuilder::build(), tflimport::ConcatenationGraphBuilder::build(), depth(), height(), and width().
width()
uint32_t coco::FeatureLayout::width (void) const inline
Definition at line 47 of file FeatureLayout.h.
{ return shape().width(); }
References shape(), and nncc::core::ADT::feature::Shape::width().
The documentation for this struct was generated from the following file:
compiler/coco/core/include/coco/IR/FeatureLayout.h