ONE - On-device Neural Engine: loco::TypeInference Struct Reference
loco::TypeInference Struct Reference
#include <TypeInference.h>
Static Public Member Functions
static bool known (const Node *)
static DataType get (const Node *)
static void erase (Node *)
Detailed Description
Definition at line 101 of file TypeInference.h.
Member Function Documentation
erase()
void loco::TypeInference::erase (Node * node) static
Definition at line 93 of file TypeInference.cpp.
{ return node->annot<DataTypeAnnotation>(nullptr); }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by loco::dtype_erase().
get()
DataType loco::TypeInference::get (const Node * node) static
Definition at line 87 of file TypeInference.cpp.
{
  assert(known(node));
  return node->annot<DataTypeAnnotation>()->dtype();
}
References loco::AnnotatedItem< Annotation >::annot(), and known().
Referenced by loco::dtype_get().
known()
bool loco::TypeInference::known (const Node * node) static
Definition at line 85 of file TypeInference.cpp.
{ return node->annot<DataTypeAnnotation>() != nullptr; }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by loco::dtype_known(), and get().
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/Service/TypeInference.h
compiler/loco/src/Service/TypeInference.cpp