ONE - On-device Neural Engine: mir_interpreter::MaxPool2DImpl< T > Struct Template Reference
mir_interpreter::MaxPool2DImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &inputv, const mir::ops::MaxPool2DOp &op, mir::TensorVariant &result)
Detailed Description
template<typename T>
struct mir_interpreter::MaxPool2DImpl< T >
Definition at line 30 of file MaxPool2D.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::MaxPool2DImpl< T >::run (const mir::TensorVariant & inputv, const mir::ops::MaxPool2DOp & op, mir::TensorVariant & result) static
Definition at line 37 of file MaxPool2D.cpp.
{
  const auto &input_shape = op.getInputShape(0);
  const auto &output_shape = op.getOutputShape(0);
  const auto &window_size = op.getWindowSize();
  const auto &strides = op.getStrides();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  (void)padding_after;
  Tensor<T> input(inputv);
  constexpr int num_spatial_dims = 2;
  assert(input.getShape().rank() == 4);
  assert(window_size.size() == num_spatial_dims);
  assert(strides.size() == num_spatial_dims);
  assert(padding_before.size() == num_spatial_dims);
  assert(padding_after.size() == num_spatial_dims);
  Tensor<T> res_accessor(result);
  ShapeRange in_range(input_shape);
  Index in_index(input_shape.rank());
  for (const auto &out_index : ShapeRange(output_shape))
  {
    T result = std::numeric_limits<T>::lowest();
    // Assuming NHWC format.
    in_index.at(0) = out_index.at(0);
    in_index.at(3) = out_index.at(3);
    for (const auto &window_index : ShapeRange(Shape(window_size)))
    {
      // Assuming NHWC format.
      for (int i = 0; i < num_spatial_dims; ++i)
        in_index.at(1 + i) =
          out_index.at(1 + i) * strides[i] + window_index.at(i) - padding_before[i];
      if (in_range.contains(in_index))
      {
        result = std::max(result, input.at(in_index));
      }
    }
    res_accessor.at(out_index) = result;
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::ShapeRange::contains(), mir::Operation::getInputShape(), mir::Operation::getOutputShape(), mir::ops::MaxPool2DOp::getPaddingAfter(), mir::ops::MaxPool2DOp::getPaddingBefore(), mir::ops::MaxPool2DOp::getStrides(), and mir::ops::MaxPool2DOp::getWindowSize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/MaxPool2D.cpp