ONE - On-device Neural Engine: mir_interpreter::DepthwiseConv2DImpl< T > Struct Template Reference
mir_interpreter::DepthwiseConv2DImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::ops::DepthwiseConv2DOp &op, const mir::TensorVariant &inputv, const mir::TensorVariant &kernelv, const mir::TensorVariant *biasv, mir::TensorVariant &output)
Detailed Description
template<typename T>
struct mir_interpreter::DepthwiseConv2DImpl< T >
Definition at line 32 of file DepthwiseConv2D.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::DepthwiseConv2DImpl< T >::run (const mir::ops::DepthwiseConv2DOp & op, const mir::TensorVariant & inputv, const mir::TensorVariant & kernelv, const mir::TensorVariant * biasv, mir::TensorVariant & output) static
Definition at line 40 of file DepthwiseConv2D.cpp.
{
  const Shape &in_shape = op.getInputShape(0);
  const Shape &kernel_shape = op.getInputShape(1);
  const Shape &out_shape = op.getOutputShape(0);
  const auto &strides = op.getStrides();
  const std::vector<int32_t> &pads = op.getPaddingBefore();
  assert(in_shape.rank() == 4);
  assert(kernel_shape.rank() == 4);
  assert(kernel_shape.dim(2) == in_shape.dim(3));
  assert(in_shape.dim(3) * kernel_shape.dim(3) == out_shape.dim(3));
  assert(strides.size() == 2);
  assert(pads.size() == 2);
  int32_t channel_multiplier = kernel_shape.dim(3);
  Tensor<T> res_accessor(output);
  Tensor<T> input(inputv);
  Tensor<T> bias(*biasv);
  Tensor<T> kernel(kernelv);
  ShapeRange in_range(in_shape);
  ShapeRange kernel_range(kernel_shape);
  ShapeRange out_range(Shape{out_shape.dim(0), out_shape.dim(1), out_shape.dim(2), 1});
  Index in_index;
  in_index.resize(4);
  erase<T>(output);
  for (const auto &out_index : out_range)
  {
    Index out_index_k = out_index;
    for (const auto &kernel_index : kernel_range)
    {
      in_index.at(0) = out_index.at(0);
      for (int i = 0; i < 2; ++i)
        in_index.at(1 + i) = out_index.at(1 + i) * strides[i] + kernel_index.at(i) - pads[i];
      in_index.at(3) = kernel_index.at(2);
      if (in_range.contains(in_index))
      {
        out_index_k.at(3) = kernel_index.at(2) * channel_multiplier + kernel_index.at(3);
        res_accessor.at(out_index_k) += input.at(in_index) * kernel.at(kernel_index);
      }
    }
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::ShapeRange::contains(), mir::Shape::dim(), mir::Operation::getInputShape(), mir::Operation::getOutputShape(), mir::ops::DepthwiseConv2DOp::getPaddingBefore(), mir::ops::DepthwiseConv2DOp::getStrides(), mir::Shape::rank(), and mir::Index::resize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/DepthwiseConv2D.cpp