ONE - On-device Neural Engine: luci::CircleTypeInferenceRule Struct Reference
luci::CircleTypeInferenceRule Struct Reference final
Type Inference Rule for CircleDialect.
#include <CircleTypeInferenceRule.h>
Public Member Functions
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::DataType &) const final
Public Member Functions inherited from loco::TypeInferenceRule
virtual ~TypeInferenceRule ()=default
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, DataType &) const =0
Detailed Description
Type Inference Rule for CircleDialect.
Definition at line 28 of file CircleTypeInferenceRule.h.
Member Function Documentation
infer()
bool luci::CircleTypeInferenceRule::infer (const loco::Node * , loco::DataType &) const final virtual
Framework guarantees the followings:
Framework tries to infer the data type of each node only after the data type of all of its valid (= non-nullptr) argument nodes is inferred.
The result of preceding "infer" is accessible through below dtype_get method.
This holds only when preceding "infer" returns true.
Implements loco::TypeInferenceRule.
Definition at line 681 of file CircleTypeInferenceRule.cpp.
{
  assert(node->dialect() == CircleDialect::get());
  TypeInferenceAlgorithm alg;
  auto circle_node = loco::must_cast<const CircleNode *>(node);
  dtype = circle_node->accept(&alg);
  assert(dtype != loco::DataType::Unknown);
  return true;
}
References loco::Node::dialect(), and luci::CircleDialect::get().
Referenced by luci::tinf::Algorithm::visit().
recognize()
bool luci::CircleTypeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::TypeInferenceRule.
Definition at line 676 of file CircleTypeInferenceRule.cpp.
{
  return CircleDialect::get() == d;
}
References luci::CircleDialect::get().
The documentation for this struct was generated from the following files:
compiler/luci/service/include/luci/Service/CircleTypeInferenceRule.h
compiler/luci/service/src/CircleTypeInferenceRule.cpp