ONE - On-device Neural Engine: luci::CanonicalizePass Struct Reference
luci::CanonicalizePass Struct Reference final
Class to canoncalize CircleNodes.
#include <CanonicalizePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Class to canoncalize CircleNodes.
Definition at line 29 of file CanonicalizePass.h.
Member Function Documentation
name()
const char * luci::CanonicalizePass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 31 of file CanonicalizePass.h.
{ return "luci::CanonicalizePass"; }
run()
bool luci::CanonicalizePass::run (loco::Graph * g) final virtual
Canonicalize circle nodes
Implements logo::Pass.
Definition at line 84 of file CanonicalizePass.cpp.
{
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (auto pad = dynamic_cast<luci::CirclePad *>(node))
    {
      if (paddings_to_s32(pad))
        changed = true;
    }
    else if (auto padv2 = dynamic_cast<luci::CirclePadV2 *>(node))
    {
      if (paddings_to_s32(padv2))
        changed = true;
    }
    // TODO add more canonicalization
  }
  return changed;
}
References loco::active_nodes(), luci::must_cast(), and loco::output_nodes().
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/CanonicalizePass.h
compiler/luci/pass/src/CanonicalizePass.cpp