ONE - On-device Neural Engine: ANeuralNetworksMemory Struct Reference
ANeuralNetworksMemory Struct Reference
#include <ANeuralNetworksMemory.h>
Public Member Functions
ANeuralNetworksMemory (size_t size, int protect, int fd, size_t offset)
~ANeuralNetworksMemory ()
size_t size (void) const
uint8_t * base (void)
uint8_t * base (void) const
bool vaildAccess (size_t offset, size_t length) const
Detailed Description
Definition at line 22 of file ANeuralNetworksMemory.h.
Constructor & Destructor Documentation
ANeuralNetworksMemory()
ANeuralNetworksMemory::ANeuralNetworksMemory (size_t size, int protect, int fd, size_t offset)
Definition at line 25 of file ANeuralNetworksMemory.cc.
{
  _base = reinterpret_cast<uint8_t *>(mmap(nullptr, size, protect, MAP_PRIVATE, fd, offset));
  _size = size;
}
References offset(), and size().
~ANeuralNetworksMemory()
ANeuralNetworksMemory::~ANeuralNetworksMemory ()
Definition at line 31 of file ANeuralNetworksMemory.cc.
{ munmap(reinterpret_cast<void *>(_base), _size); }
Member Function Documentation
base() [1/2]
uint8_t * ANeuralNetworksMemory::base (void) inline
Definition at line 30 of file ANeuralNetworksMemory.h.
{ return _base; }
Referenced by ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutputFromMemory(), and ANeuralNetworksModel_setOperandValueFromMemory().
base() [2/2]
uint8_t * ANeuralNetworksMemory::base (void) const inline
Definition at line 31 of file ANeuralNetworksMemory.h.
{ return _base; }
size()
size_t ANeuralNetworksMemory::size (void) const inline
Definition at line 29 of file ANeuralNetworksMemory.h.
{ return _size; }
Referenced by ANeuralNetworksMemory(), and ANeuralNetworksModel_setOperandValueFromMemory().
vaildAccess()
bool ANeuralNetworksMemory::vaildAccess (size_t offset, size_t length) const
Definition at line 33 of file ANeuralNetworksMemory.cc.
{
  if ((offset >= _size) || (length > _size))
  {
    return false;
  }
  if ((offset + length) >= _size)
  {
    return false;
  }
  return true;
}
References offset().
Referenced by ANeuralNetworksExecution_setInputFromMemory(), and ANeuralNetworksExecution_setOutputFromMemory().
The documentation for this struct was generated from the following files:
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksMemory.h
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksMemory.cc