ONE - On-device Neural Engine: circle_eval_diff::TensorShape Struct Reference
circle_eval_diff::TensorShape Struct Reference
#include <Tensor.h>
Public Member Functions
uint32_t rank (void) const
void rank (uint32_t value)
const loco::Dimension & dim (uint32_t axis) const
loco::Dimension & dim (uint32_t axis)
void shape (std::initializer_list< uint32_t > dims)
Detailed Description
Definition at line 38 of file Tensor.h.
Member Function Documentation
dim() [1/2]
loco::Dimension & circle_eval_diff::TensorShape::dim (uint32_t axis) inline
Definition at line 45 of file Tensor.h.
{ return _dims.at(axis); }
dim() [2/2]
const loco::Dimension & circle_eval_diff::TensorShape::dim (uint32_t axis) const inline
Definition at line 44 of file Tensor.h.
{ return _dims.at(axis); }
Referenced by shape().
rank() [1/2]
void circle_eval_diff::TensorShape::rank (uint32_t value) inline
Definition at line 42 of file Tensor.h.
{ _dims.resize(value); }
rank() [2/2]
uint32_t circle_eval_diff::TensorShape::rank (void) const inline
Definition at line 41 of file Tensor.h.
{ return _dims.size(); }
Referenced by shape().
shape()
void circle_eval_diff::TensorShape::shape (std::initializer_list< uint32_t > dims) inline
Definition at line 47 of file Tensor.h.
  {
    rank(dims.size());
    uint32_t axis = 0;
    for (auto d : dims)
    {
      dim(axis++) = d;
    }
  }
References dim(), and rank().
The documentation for this struct was generated from the following file:
compiler/circle-eval-diff/src/Tensor.h