ONE - On-device Neural Engine: ShowAction Struct Reference
ShowAction Struct Reference final
Public Member Functions
void run (nnkit::TensorContext &ctx) override
Public Member Functions inherited from nnkit::Action
virtual ~Action ()=default
virtual void run (TensorContext &ctx)=0
Detailed Description
Definition at line 39 of file Show.cpp.
Member Function Documentation
run()
void ShowAction::run (nnkit::TensorContext & ctx) override virtual
Implements nnkit::Action.
Definition at line 44 of file Show.cpp.
{
  std::cout << "count: " << ctx.size() << std::endl;
  for (uint32_t n = 0; n < ctx.size(); ++n)
  {
    std::cout << "  tensor(" << n << ") : " << ctx.name(n) << std::endl;
    using nncc::core::ADT::tensor::Reader;
    using nnkit::TensorContext;
    ctx.getConstFloatTensor(n, [](const TensorContext &ctx, uint32_t n, const Reader<float> &t) {
      for (IndexEnumerator e{ctx.shape(n)}; e.valid(); e.advance())
      {
        const auto &index = e.current();
        std::cout << "    " << index << ": " << t.at(index) << std::endl;
      }
    });
  }
}
References nnkit::TensorContext::getConstFloatTensor(), nnkit::TensorContext::name(), nnkit::TensorContext::size(), and nncc::core::ADT::tensor::IndexEnumerator::valid().
The documentation for this struct was generated from the following file:
compiler/nnkit/actions/builtin/Show.cpp