ONE - On-device Neural Engine: locoex::CircleShapeInferenceRule Struct Reference
locoex::CircleShapeInferenceRule Struct Reference final
#include <CircleShapeInferenceRule.h>
Public Member Functions
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::NodeShape &) const final
Infer node's shape.
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Definition at line 25 of file CircleShapeInferenceRule.h.
Member Function Documentation
infer()
bool locoex::CircleShapeInferenceRule::infer (const loco::Node * , loco::NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 56 of file CircleShapeInferenceRule.cpp.
{
  assert(node->dialect() == CircleDialect::get());
  assert(dynamic_cast<const CircleNode *>(node) != nullptr);
  ShapeInferenceAlgorithm alg;
  shape = dynamic_cast<const CircleNode *>(node)->accept(&alg);
  return true;
}
References loco::Node::dialect(), and locoex::CircleDialect::get().
recognize()
bool locoex::CircleShapeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 51 of file CircleShapeInferenceRule.cpp.
{
  return CircleDialect::get() == d;
}
References locoex::CircleDialect::get().
The documentation for this struct was generated from the following files:
compiler/exo/src/Dialect/Service/CircleShapeInferenceRule.h
compiler/exo/src/Dialect/Service/CircleShapeInferenceRule.cpp