ONE - On-device Neural Engine: rua::ModelService Struct Reference
rua::ModelService Struct Reference abstract
A wrapper for ANeuralNetworkModel API.
#include <Service.h>
Public Member Functions
virtual ~ModelService ()=default
virtual int create (ANeuralNetworksModel **model) const =0
virtual int addOperand (ANeuralNetworksModel *model, const ANeuralNetworksOperandType *type) const =0
virtual int setOperandValue (ANeuralNetworksModel *model, int32_t index, const void *buffer, size_t length) const =0
virtual int setOperandValueFromMemory (ANeuralNetworksModel *model, int32_t index, const ANeuralNetworksMemory *memory, size_t offset, size_t length) const =0
virtual int addOperation (ANeuralNetworksModel *model, ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs) const =0
virtual int identifyInputsAndOutputs (ANeuralNetworksModel *model, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs) const =0
virtual int relaxComputationFloat32toFloat16 (ANeuralNetworksModel *model, bool allow) const =0
virtual int finish (ANeuralNetworksModel *model) const =0
virtual void free (ANeuralNetworksModel *model) const =0
Detailed Description
A wrapper for ANeuralNetworkModel API.
Definition at line 53 of file Service.h.
Constructor & Destructor Documentation
~ModelService()
virtual rua::ModelService::~ModelService () virtual default
Member Function Documentation
addOperand()
virtual int rua::ModelService::addOperand (ANeuralNetworksModel * model, const ANeuralNetworksOperandType * type) const pure virtual
Referenced by ANeuralNetworksModel_addOperand().
addOperation()
virtual int rua::ModelService::addOperation (ANeuralNetworksModel * model, ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs) const pure virtual
Referenced by ANeuralNetworksModel_addOperation().
create()
virtual int rua::ModelService::create (ANeuralNetworksModel ** model) const pure virtual
Referenced by ANeuralNetworksModel_create().
finish()
virtual int rua::ModelService::finish (ANeuralNetworksModel * model) const pure virtual
Referenced by ANeuralNetworksModel_finish().
free()
virtual void rua::ModelService::free (ANeuralNetworksModel * model) const pure virtual
Referenced by ANeuralNetworksModel_free().
identifyInputsAndOutputs()
virtual int rua::ModelService::identifyInputsAndOutputs (ANeuralNetworksModel * model, uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs) const pure virtual
Referenced by ANeuralNetworksModel_identifyInputsAndOutputs().
relaxComputationFloat32toFloat16()
virtual int rua::ModelService::relaxComputationFloat32toFloat16 (ANeuralNetworksModel * model, bool allow) const pure virtual
Referenced by ANeuralNetworksModel_relaxComputationFloat32toFloat16().
setOperandValue()
virtual int rua::ModelService::setOperandValue (ANeuralNetworksModel * model, int32_t index, const void * buffer, size_t length) const pure virtual
Referenced by ANeuralNetworksModel_setOperandValue().
setOperandValueFromMemory()
virtual int rua::ModelService::setOperandValueFromMemory (ANeuralNetworksModel * model, int32_t index, const ANeuralNetworksMemory * memory, size_t offset, size_t length) const pure virtual
Referenced by ANeuralNetworksModel_setOperandValueFromMemory().
The documentation for this struct was generated from the following file:
runtime/libs/rua/core/include/rua/Service.h