ONE - On-device Neural Engine: locoex::TFLNode Struct Reference
locoex::TFLNode Struct Reference abstract
#include <TFLNodeDecl.h>
Public Member Functions
virtual ~TFLNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFLOpcode opcode (void) const =0
template<typename T >
T accept (TFLNodeVisitorBase< T > *) const
template<typename T >
T accept (TFLNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Definition at line 29 of file TFLNodeDecl.h.
Constructor & Destructor Documentation
~TFLNode()
virtual locoex::TFLNode::~TFLNode () virtual default
Member Function Documentation
accept() [1/2]
template<typename T > T locoex::TFLNode::accept (TFLNodeMutableVisitorBase< T > * v)
Definition at line 48 of file TFLNodeImpl.h.
{
  switch (this->opcode())
  {
#define TFL_NODE(OPCODE, CLASS) \
                                \
  case TFLOpcode::OPCODE:       \
    return v->visit(dynamic_cast<CLASS *>(this));
#include "TFLNodes.lst"
#undef TFL_NODE
    default:
      break;
  }
  INTERNAL_EXN("TFLNode::accept(TFLNodeMutableVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
accept() [2/2]
template<typename T > T locoex::TFLNode::accept (TFLNodeVisitorBase< T > * v) const
Definition at line 29 of file TFLNodeImpl.h.
{
  switch (this->opcode())
  {
#define TFL_NODE(OPCODE, CLASS) \
                                \
  case TFLOpcode::OPCODE:       \
    return v->visit(dynamic_cast<const CLASS *>(this));
#include "TFLNodes.lst"
#undef TFL_NODE
    default:
      break;
  }
  INTERNAL_EXN("TFLNode::accept(TFLNodeVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
Referenced by exo::FuseBiasAddPass::run().
dialect()
const loco::Dialect * locoex::TFLNode::dialect (void) const final virtual
Return "Dialect" identifier that this node belongs to.
dialect() SHOULD return a valid pointer.
Implements loco::Node.
Definition at line 24 of file TFLNode.cpp.
{ return TFLDialect::get(); }
References locoex::TFLDialect::get().
Referenced by exo::FuseBiasAddPass::run().
opcode()
virtual TFLOpcode locoex::TFLNode::opcode (void) const pure virtual
Implemented in locoex::TFLNodeImpl< Code >, locoex::TFLNodeImpl< TFLOpcode::ADD >, locoex::TFLNodeImpl< TFLOpcode::AVERAGE_POOL_2D >, locoex::TFLNodeImpl< TFLOpcode::CONCATENATION >, locoex::TFLNodeImpl< TFLOpcode::CONST >, locoex::TFLNodeImpl< TFLOpcode::CONV_2D >, locoex::TFLNodeImpl< TFLOpcode::DEPTHWISE_CONV_2D >, locoex::TFLNodeImpl< TFLOpcode::DIV >, locoex::TFLNodeImpl< TFLOpcode::FULLY_CONNECTED >, locoex::TFLNodeImpl< TFLOpcode::MAX_POOL_2D >, locoex::TFLNodeImpl< TFLOpcode::MAXIMUM >, locoex::TFLNodeImpl< TFLOpcode::MEAN >, locoex::TFLNodeImpl< TFLOpcode::MUL >, locoex::TFLNodeImpl< TFLOpcode::RELU >, locoex::TFLNodeImpl< TFLOpcode::RELU6 >, locoex::TFLNodeImpl< TFLOpcode::RESHAPE >, locoex::TFLNodeImpl< TFLOpcode::RSQRT >, locoex::TFLNodeImpl< TFLOpcode::SQRT >, locoex::TFLNodeImpl< TFLOpcode::SQUARED_DIFFERENCE >, locoex::TFLNodeImpl< TFLOpcode::SUB >, locoex::TFLNodeImpl< TFLOpcode::TRANSPOSE >, and locoex::TFLNodeImpl< TFLOpcode::TRANSPOSE_CONV >.
Referenced by accept().
The documentation for this struct was generated from the following files:
compiler/exo/src/Dialect/IR/TFLNodeDecl.h
compiler/exo/src/Dialect/IR/TFLNode.cpp
compiler/exo/src/Dialect/IR/TFLNodeImpl.h