ONE - On-device Neural Engine: coco::Op Struct Reference
coco::Op Struct Reference abstract
Base interface on all supported NN operations.
#include <Op.h>
Data Structures
struct IMutator
Op mutator interface.
struct IVisitor
Op visitor interface.
struct Mutator
struct Visitor
Public Member Functions
virtual ~Op ()
virtual uint32_t arity (void) const =0
Return the number of arguments (# of child Ops)
virtual Op * arg (uint32_t n) const =0
Return N-th argument.
virtual std::set< Object * > uses (void) const =0
Return a set of object(s) used during execution.
template<typename T >
T accept (IVisitor< T > *v) const
template<typename T >
T accept (IVisitor< T > &v) const
template<typename T >
T accept (IVisitor< T > &&v) const
void accept (IMutator *m)
void accept (IMutator &m)
void accept (IMutator &&m)
Instr * parent (void) const
Op * up (void) const
Return a pointer to the parent Op.
Public Member Functions inherited from coco::Entity
virtual ~Entity ()=default
Module * module (void) const
Friends
class Step
class Part
Detailed Description
Base interface on all supported NN operations.
Definition at line 44 of file Op.h.
Constructor & Destructor Documentation
~Op()
coco::Op::~Op () virtual
Definition at line 25 of file Op.cpp.
{
  // NOTE Op SHOULD NOT be referred by an instruction to be destructed
  assert(_step == nullptr);
}
Member Function Documentation
accept() [1/6]
void coco::Op::accept (IMutator && m) inline
Definition at line 155 of file Op.h.
{ return accept(&m); }
References accept(), and m.
Referenced by accept().
accept() [2/6]
void coco::Op::accept (IMutator & m) inline
Definition at line 154 of file Op.h.
{ return accept(&m); }
References accept(), and m.
Referenced by accept().
accept() [3/6]
void coco::Op::accept (IMutator * m) inline
Definition at line 142 of file Op.h.
  {
#define OP(Name)            \
  if (auto op = as##Name()) \
  {                         \
    return m->mutate(op);   \
  }
#include "coco/IR/Op.lst"
#undef OP
    throw std::runtime_error{"unreachable"};
  }
accept() [4/6]
template<typename T > T coco::Op::accept (IVisitor< T > && v) const inline
Definition at line 114 of file Op.h.
{ return accept(&v); }
References accept().
Referenced by accept().
accept() [5/6]
template<typename T > T coco::Op::accept (IVisitor< T > & v) const inline
Definition at line 113 of file Op.h.
{ return accept(&v); }
References accept().
Referenced by accept().
accept() [6/6]
template<typename T > T coco::Op::accept (IVisitor< T > * v) const inline
Definition at line 101 of file Op.h.
  {
#define OP(Name)            \
  if (auto op = as##Name()) \
  {                         \
    return v->visit(op);    \
  }
#include "coco/IR/Op.lst"
#undef OP
    throw std::runtime_error{"unreachable"};
  }
Referenced by dump(), InstrPrinter::visit(), and OpPrinter::visit().
arg()
virtual Op * coco::Op::arg (uint32_t n) const pure virtual
Return N-th argument.
Note
The behavior of arg(n) is defined only when n < artiy()
Implemented in coco::UnaryOp, coco::BinaryOp, coco::Load, and coco::Conv2D.
arity()
virtual uint32_t coco::Op::arity (void) const pure virtual
Return the number of arguments (# of child Ops)
Implemented in coco::UnaryOp, coco::BinaryOp, coco::Load, and coco::Conv2D.
parent()
Instr * coco::Op::parent (void) const
Definition at line 31 of file Op.cpp.
{
  // Get the parent instruction specified by _step for root nodes
  if (_step)
  {
    // Op SHOULD BE a root node
    assert(_part == nullptr);
    assert(_step->instr() != nullptr);
    return _step->instr();
  }
  // Get the parent instruction of its parent Op for non-root nodes
  if (_part)
  {
    assert(_part->parent() != nullptr);
    return _part->parent()->parent();
  }
  return nullptr;
}
References coco::Step::instr(), parent(), and coco::Part::parent().
Referenced by coco::OpManager::destroy(), coco::OpManager::destroy_all(), coco::Load::loc(), coco::Conv2D::loc(), and parent().
up()
Op * coco::Op::up (void) const
Return a pointer to the parent Op.
Definition at line 52 of file Op.cpp.
{
  if (_part)
  {
    assert(_part->parent() != nullptr);
    return _part->parent();
  }
  return nullptr;
}
References coco::Part::parent().
Referenced by coco::OpManager::destroy_all(), and coco::root().
uses()
virtual std::set< Object * > coco::Op::uses (void) const pure virtual
Return a set of object(s) used during execution.
NOTE There is no 'def' method as Op is not allowed to define a new object
Implemented in coco::UnaryOp, coco::BinaryOp, coco::Load, and coco::Conv2D.
Friends And Related Function Documentation
Part
friend class Part friend
Definition at line 47 of file Op.h.
Step
friend class Step friend
Definition at line 46 of file Op.h.
The documentation for this struct was generated from the following files:
compiler/coco/core/include/coco/IR/Op.h
compiler/coco/core/src/IR/Op.cpp