ONE - On-device Neural Engine: luci::FusePreActivationBatchNormPass Struct Reference
luci::FusePreActivationBatchNormPass Struct Reference final
Class to fuse batch normalization of pre-activation.
#include <FusePreActivationBatchNormPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Data Fields
std::vector< luci::CircleMul * > _mul_list
std::vector< luci::CircleAdd * > _add_list
std::vector< luci::CircleSub * > _sub_list
Detailed Description
Class to fuse batch normalization of pre-activation.
Definition at line 29 of file FusePreActivationBatchNormPass.h.
Member Function Documentation
name()
const char * luci::FusePreActivationBatchNormPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 31 of file FusePreActivationBatchNormPass.h.
{ return "luci::FusePreActivationBatchNormPass"; }
run()
bool luci::FusePreActivationBatchNormPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 577 of file FusePreActivationBatchNormPass.cpp.
{
  LOGGER(l);
  bool changed = false;
  // Step 1. Swap MUL <-> ADD
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto add = dynamic_cast<luci::CircleAdd *>(node);
    if (add == nullptr)
      continue;
    if (swap_mul_add(add, _mul_list, _add_list))
      changed = true;
  }
  INFO(l) << "[FusePreActivationBatchNorm] Target pre-activations: " << _mul_list.size()
          << std::endl;
  // Valid pattern was not detected. Fast exit.
  if (!changed)
    return false;
  // Step 2. Fuse MUL with the next CONV
  for (auto const &mul : _mul_list)
  {
    if (fuse_mul_with_conv(mul))
      INFO(l) << "[FusePreActivationBatchNorm] Fused MUL: " << mul->name() << std::endl;
  }
  // Step 3. Fuse ADD with the preceding CONV and insert SUB
  for (auto const &add : _add_list)
  {
    if (fuse_add_with_conv(add, _sub_list))
      INFO(l) << "[FusePreActivationBatchNorm] Fused ADD: " << add->name() << std::endl;
  }
  INFO(l) << "[FusePreActivationBatchNorm] " << _sub_list.size() << " SUB were added." << std::endl;
  // Step 4. Fuse SUB to CONV (SUB -> ADD <- CONV pattern)
  for (auto const &sub : _sub_list)
  {
    if (fuse_sub_with_conv(sub))
      INFO(l) << "[FusePreActivationBatchNorm] Fused SUB: " << sub->name() << std::endl;
  }
  return changed;
}
References _add_list, _mul_list, _sub_list, loco::active_nodes(), luci::fuse_add_with_conv(), luci::fuse_mul_with_conv(), luci::fuse_sub_with_conv(), INFO, LOGGER, loco::output_nodes(), and luci::swap_mul_add().
Field Documentation
_add_list
std::vector<luci::CircleAdd *> luci::FusePreActivationBatchNormPass::_add_list
Definition at line 36 of file FusePreActivationBatchNormPass.h.
Referenced by run().
_mul_list
std::vector<luci::CircleMul *> luci::FusePreActivationBatchNormPass::_mul_list
Definition at line 35 of file FusePreActivationBatchNormPass.h.
Referenced by run().
_sub_list
std::vector<luci::CircleSub *> luci::FusePreActivationBatchNormPass::_sub_list
Definition at line 37 of file FusePreActivationBatchNormPass.h.
Referenced by run().
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/FusePreActivationBatchNormPass.h
compiler/luci/pass/src/FusePreActivationBatchNormPass.cpp