ONE - On-device Neural Engine: Memory Struct Reference
Memory Struct Reference abstract
#include <Memory.h>
Public Member Functions
Memory ()=default
virtual ~Memory ()=default
Memory (const Memory &)=delete
Memory & operator= (const Memory &)=delete
virtual int getPointer (uint8_t **buffer) const =0
virtual bool validateSize (uint32_t offset, uint32_t length) const =0
Detailed Description
Definition at line 25 of file Memory.h.
Constructor & Destructor Documentation
Memory() [1/2]
Memory::Memory () default
~Memory()
virtual Memory::~Memory () virtual default
Memory() [2/2]
Memory::Memory (const Memory &) delete
Member Function Documentation
getPointer()
virtual int Memory::getPointer (uint8_t ** buffer) const pure virtual
Implemented in PrivateMemory, AllocatedMemory, and MappedMemory.
operator=()
Memory & Memory::operator= (const Memory &) delete
validateSize()
virtual bool Memory::validateSize (uint32_t offset, uint32_t length) const pure virtual
Implemented in PrivateMemory, AllocatedMemory, and MappedMemory.
Referenced by ExecutionBuilder::setInputFromMemory(), ModelBuilder::setOperandValueFromMemory(), and ExecutionBuilder::setOutputFromMemory().
The documentation for this struct was generated from the following file:
compiler/ann-ref/src/Memory.h