ONE - On-device Neural Engine: ANeuralNetworksModel Struct Reference
ANeuralNetworksModel Struct Reference
#include <ANeuralNetworksModel.h>
Public Types
enum class OperandUsage { NOT_DEFINED = 0 , MODEL_INPUT , CONSTANT , OPERATION_OUTPUT }
Public Member Functions
ANeuralNetworksModel () noexcept
bool addOperand (const ANeuralNetworksOperandType *type) noexcept
bool setOperandValue (uint32_t index, const void *buffer, size_t length, bool optional=false, bool copy=false) noexcept
bool addOperation (ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs) noexcept
bool addOperationEx (ANeuralNetworksOperationTypeEx type, uint32_t inputCount, const uint32_t *inputs, uint32_t outputCount, const uint32_t *outputs) noexcept
bool addModelInput (uint32_t index) noexcept
bool addModelOutput (uint32_t index) noexcept
void allowFloat32toFloat16 (bool allow) noexcept
bool allowedToFp16 () const noexcept
bool finish () noexcept
onert::ir::Graph & deref (void)
bool isFinished () noexcept
bool isExistOperand (uint32_t index) noexcept
size_t operandSize (uint32_t index) noexcept
bool isUsageSet (uint32_t index) noexcept
bool isOperationOutput (uint32_t index) noexcept
std::shared_ptr< onert::ir::Model > getModel () const
Detailed Description
Definition at line 27 of file ANeuralNetworksModel.h.
Member Enumeration Documentation
OperandUsage
enum class ANeuralNetworksModel::OperandUsage strong
Enumerator
NOT_DEFINED
MODEL_INPUT
CONSTANT
OPERATION_OUTPUT
Definition at line 30 of file ANeuralNetworksModel.h.
  {
    NOT_DEFINED = 0,
    MODEL_INPUT,
    CONSTANT,
    OPERATION_OUTPUT,
  };
Constructor & Destructor Documentation
ANeuralNetworksModel()
ANeuralNetworksModel::ANeuralNetworksModel () noexcept
Definition at line 29 of file ANeuralNetworksModel.cc.
  : _finished_building{false}, _optional_operands{}, _operand_usages{}, _allowFloat32toFloat16{
                                                                          false}
{
  _graph = std::make_shared<onert::ir::Graph>();
}
Member Function Documentation
addModelInput()
bool ANeuralNetworksModel::addModelInput (uint32_t index) noexcept
Definition at line 159 of file ANeuralNetworksModel.cc.
{
  try
  {
    _operand_usages[index] = OperandUsage::MODEL_INPUT;
    const onert::ir::OperandIndex ind{index};
    _graph->addInput(ind);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
addModelOutput()
bool ANeuralNetworksModel::addModelOutput (uint32_t index) noexcept
Definition at line 177 of file ANeuralNetworksModel.cc.
{
  try
  {
    const onert::ir::OperandIndex ind{index};
    // Duplicated output is not allowed
    if (_graph->getOutputs().contains(ind))
    {
      return false;
    }
    _graph->addOutput(ind);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
addOperand()
bool ANeuralNetworksModel::addOperand (const ANeuralNetworksOperandType * type) noexcept
Definition at line 36 of file ANeuralNetworksModel.cc.
{
  try
  {
    const auto shape = NNAPIConvert::getShape(type);
    const auto typeInfo = NNAPIConvert::getTypeInfo(type);
    _graph->addOperand(shape, typeInfo);
    _operand_usages.emplace_back(OperandUsage::NOT_DEFINED);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References NNAPIConvert::getShape(), NNAPIConvert::getTypeInfo(), and VERBOSE.
addOperation()
bool ANeuralNetworksModel::addOperation (ANeuralNetworksOperationType type, uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs) noexcept
Definition at line 94 of file ANeuralNetworksModel.cc.
{
  try
  {
    for (uint32_t i = 0; i < outputCount; i++)
    {
      _operand_usages[outputs[i]] = OperandUsage::OPERATION_OUTPUT;
    }
    auto &factory = OperationFactory::get();
    OperationFactory::Param param{inputCount, inputs, outputCount, outputs};
    auto node = factory.create(type, param, _graph->operands());
    _graph->addOperation(std::unique_ptr<onert::ir::Operation>{node});
    // TODO Move these codes to delegate.cpp
    if (type == ANEURALNETWORKS_FULLY_CONNECTED)
    {
      const auto &input_operand =
        _graph->operands().at(node->getInputs().at(onert::ir::operation::FullyConnected::INPUT));
      auto &weights_operand =
        _graph->operands().at(node->getInputs().at(onert::ir::operation::FullyConnected::WEIGHT));
      if (input_operand.typeInfo().type() == onert::ir::DataType::FLOAT32 &&
          weights_operand.typeInfo().type() == onert::ir::DataType::QUANT_UINT8_ASYMM)
      {
        weights_operand.type(onert::ir::DataType::QUANT_INT8_SYMM);
      }
    }
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References ANEURALNETWORKS_FULLY_CONNECTED, OperationFactory::get(), onert::ir::operation::FullyConnected::INPUT, VERBOSE, and onert::ir::operation::FullyConnected::WEIGHT.
addOperationEx()
bool ANeuralNetworksModel::addOperationEx (ANeuralNetworksOperationTypeEx type, uint32_t inputCount, const uint32_t * inputs, uint32_t outputCount, const uint32_t * outputs) noexcept
Definition at line 135 of file ANeuralNetworksModel.cc.
{
  try
  {
    for (uint32_t i = 0; i < outputCount; i++)
    {
      _operand_usages[outputs[i]] = OperandUsage::OPERATION_OUTPUT;
    }
    auto &factory = OperationFactory::get();
    OperationFactory::Param param{inputCount, inputs, outputCount, outputs};
    auto node = factory.create(type, param, _graph->operands());
    _graph->addOperation(std::unique_ptr<onert::ir::Operation>{node});
  }
  catch (const std::exception &e)
  {
    return false;
  }
  return true;
}
References OperationFactory::get().
allowedToFp16()
bool ANeuralNetworksModel::allowedToFp16 () const inline noexcept
Definition at line 53 of file ANeuralNetworksModel.h.
{ return _allowFloat32toFloat16; }
allowFloat32toFloat16()
void ANeuralNetworksModel::allowFloat32toFloat16 (bool allow) noexcept
Definition at line 201 of file ANeuralNetworksModel.cc.
{
  _allowFloat32toFloat16 = allow;
}
deref()
onert::ir::Graph & ANeuralNetworksModel::deref (void) inline
Definition at line 56 of file ANeuralNetworksModel.h.
{ return *_graph; }
finish()
bool ANeuralNetworksModel::finish () noexcept
Definition at line 206 of file ANeuralNetworksModel.cc.
{
  try
  {
    fillOptionalOperand();
    _graph->verify();
    _operand_usages.clear();
    _finished_building = true;
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << '\n';
    return false;
  }
  return true;
}
References VERBOSE.
getModel()
std::shared_ptr< onert::ir::Model > ANeuralNetworksModel::getModel () const
Definition at line 276 of file ANeuralNetworksModel.cc.
{
  auto model = std::make_shared<onert::ir::Model>();
  model->push(onert::ir::SubgraphIndex{0}, _graph);
  // TODO Find all child subgraphs and copy them to all_subgs
  // Must find the same subgraph by using to compare pointer of subgraphs and set subgraph's index
  // to operands of control flow operations
  // Must clean all child subgraphs's pointer to prevent memory leak in case of that graph has
  // subgraph itself recursively
  return model;
}
isExistOperand()
bool ANeuralNetworksModel::isExistOperand (uint32_t index) noexcept
Definition at line 228 of file ANeuralNetworksModel.cc.
{
  return _graph->operands().exist(onert::ir::OperandIndex{index});
}
isFinished()
bool ANeuralNetworksModel::isFinished () noexcept
Definition at line 226 of file ANeuralNetworksModel.cc.
{ return _finished_building; }
isOperationOutput()
bool ANeuralNetworksModel::isOperationOutput (uint32_t index) noexcept
Definition at line 252 of file ANeuralNetworksModel.cc.
{
  return (_operand_usages[index] == OperandUsage::OPERATION_OUTPUT);
}
isUsageSet()
bool ANeuralNetworksModel::isUsageSet (uint32_t index) noexcept
Definition at line 247 of file ANeuralNetworksModel.cc.
{
  return (_operand_usages[index] != OperandUsage::NOT_DEFINED);
}
operandSize()
size_t ANeuralNetworksModel::operandSize (uint32_t index) noexcept
Definition at line 233 of file ANeuralNetworksModel.cc.
{
  try
  {
    return _graph->operands().at(onert::ir::OperandIndex{index}).operandSize();
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << '\n';
    return 0;
  }
}
References VERBOSE.
setOperandValue()
bool ANeuralNetworksModel::setOperandValue (uint32_t index, const void * buffer, size_t length, bool optional = false, bool copy = false) noexcept
Definition at line 55 of file ANeuralNetworksModel.cc.
{
  const onert::ir::OperandIndex ind{index};
  try
  {
    _operand_usages[index] = OperandUsage::CONSTANT;
    // Remain operands.at(ind).data()->base() as nullptr for optional operand
    // This will be filled when model finished
    if (optional)
    {
      setOptionalOperand(ind);
    }
    using onert::ir::CachedData;
    using onert::ir::ExternalData;
    if (copy)
    {
      _graph->operands().at(ind).data(
        std::make_unique<CachedData>(reinterpret_cast<const uint8_t *>(buffer), length));
    }
    else
    {
      _graph->operands().at(ind).data(
        std::make_unique<ExternalData>(reinterpret_cast<const uint8_t *>(buffer), length));
    }
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
The documentation for this struct was generated from the following files:
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.h
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksModel.cc