ONE - On-device Neural Engine: nnkit::support::tflite::TensorSet Struct Reference
nnkit::support::tflite::TensorSet Struct Reference abstract
#include <TensorSet.h>
Public Member Functions
virtual ~TensorSet ()=default
virtual uint32_t size (void) const =0
virtual TfLiteTensor * at (uint32_t n) const =0
Detailed Description
Definition at line 31 of file TensorSet.h.
Constructor & Destructor Documentation
~TensorSet()
virtual nnkit::support::tflite::TensorSet::~TensorSet () virtual default
Member Function Documentation
at()
virtual TfLiteTensor * nnkit::support::tflite::TensorSet::at (uint32_t n) const pure virtual
Implemented in nnkit::support::tflite::InputTensorSet, and nnkit::support::tflite::OutputTensorSet.
Referenced by nnkit::support::tflite::TensorContext::getConstFloatTensor(), nnkit::support::tflite::TensorContext::getMutableFloatTensor(), nnkit::support::tflite::TensorContext::isFloatTensor(), nnkit::support::tflite::TensorContext::name(), and nnkit::support::tflite::TensorContext::shape().
size()
virtual uint32_t nnkit::support::tflite::TensorSet::size (void) const pure virtual
Implemented in nnkit::support::tflite::InputTensorSet, and nnkit::support::tflite::OutputTensorSet.
Referenced by nnkit::support::tflite::TensorContext::size().
The documentation for this struct was generated from the following file:
compiler/nnkit-tflite/support/include/nnkit/support/tflite/TensorSet.h