ONE - On-device Neural Engine: moco::TFShapeInferenceRule Struct Reference
moco::TFShapeInferenceRule Struct Reference final
Shape inference rule for TensorFlow dialect.
#include <TFShapeInferenceRule.h>
Public Member Functions
bool support (const API &ver) const final
Check whether a given API is available or not.
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::NodeShape &) const final
Infer node's shape.
void infer (const Context *, const loco::Node *, Sink *) const final
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Shape inference rule for TensorFlow dialect.
Definition at line 28 of file TFShapeInferenceRule.h.
Member Function Documentation
infer() [1/2]
void moco::TFShapeInferenceRule::infer (const Context * ctx, const loco::Node * node, Sink * sink) const final virtual
Reimplemented from loco::ShapeInferenceRule.
Definition at line 876 of file TFShapeInferenceRule.cpp.
{
  assert(node->dialect() == TFDialect::get());
  assert(dynamic_cast<const TFNode *>(node) != nullptr);
  ShapeInferenceAlgorithm alg{ctx};
  auto shape = loco::must_cast<const TFNode *>(node)->accept(&alg);
  if (shape.domain() == loco::Domain::Unknown)
    sink->fail();
  else
    sink->okay(shape);
}
References loco::Node::dialect(), moco::TFDialect::get(), and loco::Unknown.
infer() [2/2]
bool moco::TFShapeInferenceRule::infer (const loco::Node * , loco::NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 857 of file TFShapeInferenceRule.cpp.
{
  ::compat::Context ctx;
  ::compat::Sink sink;
  infer(&ctx, node, &sink);
  assert(sink.status() == ::compat::Sink::Okay or sink.status() == ::compat::Sink::Fail);
  if (sink.status() == ::compat::Sink::Fail)
  {
    return false;
  }
  shape = sink.shape();
  return true;
}
References infer().
Referenced by infer().
recognize()
bool moco::TFShapeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 851 of file TFShapeInferenceRule.cpp.
{
  // handle only TensorFlow dialect
  return TFDialect::get() == d;
}
References moco::TFDialect::get().
support()
bool moco::TFShapeInferenceRule::support (const API & api) const final virtual
Check whether a given API is available or not.
Reimplemented from loco::ShapeInferenceRule.
Definition at line 846 of file TFShapeInferenceRule.cpp.
{
  return api == API::V1 or api == API::V2;
}
References loco::ShapeInferenceRule::V1, and loco::ShapeInferenceRule::V2.
The documentation for this struct was generated from the following files:
compiler/moco/service/include/moco/Service/TFShapeInferenceRule.h
compiler/moco/service/src/Service/TFShapeInferenceRule.cpp