ONE - On-device Neural Engine: nnkit::TensorContext Struct Reference
nnkit::TensorContext Struct Reference abstract
#include <TensorContext.h>
Public Types
template<typename T >
using TypedReader = std::function< void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader< T > &)>
template<typename T >
using TypedAccessor = std::function< void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor< T > &)>
Public Member Functions
virtual ~TensorContext ()=default
virtual uint32_t size (void) const =0
virtual std::string name (uint32_t n) const =0
virtual nncc::core::ADT::tensor::Shape shape (uint32_t n) const =0
virtual bool isFloatTensor (uint32_t n) const
virtual void getMutableFloatTensor (uint32_t n, const TypedAccessor< float > &cb)
virtual void getConstFloatTensor (uint32_t n, const TypedReader< float > &cb) const
virtual bool isS32Tensor (uint32_t n) const
virtual void getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > &cb)
virtual void getConstS32Tensor (uint32_t n, const TypedReader< int32_t > &cb) const
Detailed Description
Definition at line 33 of file TensorContext.h.
Member Typedef Documentation
TypedAccessor
template<typename T > using nnkit::TensorContext::TypedAccessor = std::function<void(const TensorContext &, uint32_t n, nncc::core::ADT::tensor::Accessor<T> &)>
Definition at line 40 of file TensorContext.h.
TypedReader
template<typename T > using nnkit::TensorContext::TypedReader = std::function<void(const TensorContext &, uint32_t n, const nncc::core::ADT::tensor::Reader<T> &)>
Definition at line 36 of file TensorContext.h.
Constructor & Destructor Documentation
~TensorContext()
virtual nnkit::TensorContext::~TensorContext () virtual default
Member Function Documentation
getConstFloatTensor()
virtual void nnkit::TensorContext::getConstFloatTensor (uint32_t n, const TypedReader< float > & cb) const inline virtual
Reimplemented in nnkit::support::moco::tf::TensorContext, nnkit::support::moco::tf::InputTensorContext, nnkit::support::moco::tf::OutputTensorContext, nnkit::support::tf::TensorContext, nnkit::support::caffe::TensorContext< DType >, nnkit::support::onnx::TensorContext, and nnkit::support::tflite::TensorContext.
Definition at line 67 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
Referenced by ShowAction::run(), and HD5ExportAction::run().
getConstS32Tensor()
virtual void nnkit::TensorContext::getConstS32Tensor (uint32_t n, const TypedReader< int32_t > & cb) const inline virtual
Definition at line 83 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
getMutableFloatTensor()
virtual void nnkit::TensorContext::getMutableFloatTensor (uint32_t n, const TypedAccessor< float > & cb) inline virtual
Reimplemented in nnkit::support::moco::tf::InputTensorContext, nnkit::support::moco::tf::OutputTensorContext, nnkit::support::tf::TensorContext, nnkit::support::moco::tf::TensorContext, nnkit::support::caffe::TensorContext< DType >, nnkit::support::onnx::TensorContext, and nnkit::support::tflite::TensorContext.
Definition at line 62 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
Referenced by HD5ImportAction::run().
getMutableS32Tensor()
virtual void nnkit::TensorContext::getMutableS32Tensor (uint32_t n, const TypedAccessor< int32_t > & cb) inline virtual
Definition at line 78 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
isFloatTensor()
virtual bool nnkit::TensorContext::isFloatTensor (uint32_t n) const inline virtual
Reimplemented in nnkit::support::caffe::TensorContext< DType >, nnkit::support::moco::tf::TensorContext, nnkit::support::onnx::TensorContext, nnkit::support::tf::TensorContext, and nnkit::support::tflite::TensorContext.
Definition at line 57 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
isS32Tensor()
virtual bool nnkit::TensorContext::isS32Tensor (uint32_t n) const inline virtual
Definition at line 73 of file TensorContext.h.
  {
    throw std::runtime_error("This method should be overriden");
  }
name()
virtual std::string nnkit::TensorContext::name (uint32_t n) const pure virtual
Implemented in nnkit::support::caffe::TensorContext< DType >, nnkit::support::moco::tf::TensorContext, nnkit::support::onnx::TensorContext, nnkit::support::tf::TensorContext, and nnkit::support::tflite::TensorContext.
Referenced by ShowAction::run(), HD5ExportAction::run(), and HD5ImportAction::run().
shape()
virtual nncc::core::ADT::tensor::Shape nnkit::TensorContext::shape (uint32_t n) const pure virtual
Implemented in nnkit::support::caffe::TensorContext< DType >, nnkit::support::moco::tf::TensorContext, nnkit::support::onnx::TensorContext, nnkit::support::tf::TensorContext, and nnkit::support::tflite::TensorContext.
Referenced by HD5ExportAction::run(), and HD5ImportAction::run().
size()
virtual uint32_t nnkit::TensorContext::size (void) const pure virtual
Implemented in nnkit::support::caffe::TensorContext< DType >, nnkit::support::moco::tf::TensorContext, nnkit::support::onnx::TensorContext, nnkit::support::tf::TensorContext, and nnkit::support::tflite::TensorContext.
Referenced by ShowAction::run(), RandomizeAction::run(), HD5ExportAction::run(), and HD5ImportAction::run().
The documentation for this struct was generated from the following file:
compiler/nnkit-intf/tensor/include/nnkit/TensorContext.h