ONE - On-device Neural Engine: mir_interpreter::PadImpl< T > Struct Template Reference
mir_interpreter::PadImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &inputv, const mir::ops::PadOp &op, mir::TensorVariant &result)
Detailed Description
template<typename T>
struct mir_interpreter::PadImpl< T >
Definition at line 28 of file Pad.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::PadImpl< T >::run (const mir::TensorVariant & inputv, const mir::ops::PadOp & op, mir::TensorVariant & result) static
Definition at line 35 of file Pad.cpp.
{
  Tensor<T> result_accessor(result);
  Tensor<T> input(inputv);
  Shape out_shape = result_accessor.getShape();
  ShapeRange out_range(out_shape);
  const int rank = op.getInputShape(0).rank();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  Index temp_index;
  temp_index.resize(rank);
  bool index_on_padding(false);
  for (const Index &ind : out_range)
  {
    index_on_padding = false;
    for (int32_t i = 0; i < rank; i++)
    {
      // index on input values
      if (ind.at(i) >= padding_before[i] && ind.at(i) < out_shape.dim(i) - padding_after[i])
      {
        temp_index.at(i) = ind.at(i) - padding_before[i];
      }
      else
      { // not in input
        index_on_padding = true;
        break;
      }
    }
    if (index_on_padding)
    {
      result_accessor.at(ind) = op.getPaddingValue();
    }
    else
    {
      result_accessor.at(ind) = input.at(temp_index);
    }
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::Shape::dim(), mir::Operation::getInputShape(), mir::ops::PadOp::getPaddingAfter(), mir::ops::PadOp::getPaddingBefore(), mir::ops::PadOp::getPaddingValue(), mir::Tensor< T >::getShape(), mir::Shape::rank(), and mir::Index::resize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Pad.cpp