ONE - On-device Neural Engine: flatbuffers::String Struct Reference
flatbuffers::String Struct Reference
#include <string.h>
Public Member Functions
const char * c_str () const
std::string str () const
bool operator< (const String &o) const
Public Member Functions inherited from flatbuffers::Vector< char >
uoffset_t size () const
FLATBUFFERS_ATTRIBUTE () uoffset_t Length() const
return_type Get (uoffset_t i) const
return_type operator[] (uoffset_t i) const
E GetEnum (uoffset_t i) const
const U * GetAs (uoffset_t i) const
const String * GetAsString (uoffset_t i) const
const void * GetStructFromOffset (size_t o) const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
const_iterator cbegin () const
const_iterator cend () const
const_reverse_iterator crbegin () const
const_reverse_iterator crend () const
void Mutate (uoffset_t i, const char &val)
void MutateOffset (uoffset_t i, const uint8_t *val)
mutable_return_type GetMutableObject (uoffset_t i) const
const uint8_t * Data () const
uint8_t * Data ()
const char * data () const
char * data ()
return_type LookupByKey (K key) const
mutable_return_type MutableLookupByKey (K key)
Additional Inherited Members
Public Types inherited from flatbuffers::Vector< char >
typedef VectorIterator< char, typename IndirectHelper< char >::mutable_return_type, uint8_t *, uoffset_t > iterator
typedef VectorConstIterator< char, typename IndirectHelper< char >::return_type, uoffset_t > const_iterator
typedef VectorReverseIterator< iterator > reverse_iterator
typedef VectorReverseIterator< const_iterator > const_reverse_iterator
typedef flatbuffers::bool_constant< flatbuffers::is_scalar< char >::value > scalar_tag
typedef uoffset_t size_type
typedef IndirectHelper< char >::return_type return_type
typedef IndirectHelper< char >::mutable_return_type mutable_return_type
typedef return_type value_type
Static Public Attributes inherited from flatbuffers::Vector< char >
static FLATBUFFERS_CONSTEXPR bool is_span_observable
Protected Member Functions inherited from flatbuffers::Vector< char >
Vector ()
Protected Attributes inherited from flatbuffers::Vector< char >
uoffset_t length_
Detailed Description
Definition at line 25 of file string.h.
Member Function Documentation
c_str()
const char * flatbuffers::String::c_str () const inline
Definition at line 26 of file string.h.
{ return reinterpret_cast<const char *>(Data()); }
References flatbuffers::Vector< char >::Data().
Referenced by onert_micro::core::getCustomOperatorBuilderId(), and str().
operator<()
bool flatbuffers::String::operator< (const String & o) const inline
Definition at line 37 of file string.h.
{
    return StringLessThan(this->data(), this->size(), o.data(), o.size());
  }
References flatbuffers::Vector< T, SizeT >::data(), flatbuffers::Vector< char >::data(), flatbuffers::Vector< T, SizeT >::size(), and flatbuffers::Vector< char >::size().
str()
std::string flatbuffers::String::str () const inline
Definition at line 27 of file string.h.
{ return std::string(c_str(), size()); }
References c_str(), and flatbuffers::Vector< char >::size().
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/string.h