ONE - On-device Neural Engine: moco::TFNode Struct Reference
moco::TFNode Struct Reference abstract
#include <TFNodeDecl.h>
Public Member Functions
virtual ~TFNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual TFOpcode opcode (void) const =0
template<typename T >
T accept (TFNodeVisitorBase< T > *) const
template<typename T >
T accept (TFNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Definition at line 40 of file TFNodeDecl.h.
Constructor & Destructor Documentation
~TFNode()
virtual moco::TFNode::~TFNode () virtual default
Member Function Documentation
accept() [1/2]
template<typename T > T moco::TFNode::accept (TFNodeMutableVisitorBase< T > * v)
Definition at line 47 of file TFNodeImpl.h.
{
  switch (this->opcode())
  {
#define TENSORFLOW_NODE(OPCODE, CLASS) \
  case TFOpcode::OPCODE:               \
    return v->visit(dynamic_cast<CLASS *>(this));
#include "TFNodes.lst"
#undef TENSORFLOW_NODE
    default:
      break;
  }
  // TODO including oops will make oops dependent to modules that include this
  // postpone decision to this or not
  throw std::runtime_error{"Unsupported Node"};
}
References opcode().
accept() [2/2]
template<typename T > T moco::TFNode::accept (TFNodeVisitorBase< T > * v) const
Definition at line 28 of file TFNodeImpl.h.
{
  switch (this->opcode())
  {
#define TENSORFLOW_NODE(OPCODE, CLASS) \
  case TFOpcode::OPCODE:               \
    return v->visit(dynamic_cast<const CLASS *>(this));
#include "TFNodes.lst"
#undef TENSORFLOW_NODE
    default:
      break;
  }
  // TODO including oops will make oops dependent to modules that include this
  // postpone decision to this or not
  throw std::runtime_error{"Unsupported Node"};
}
References opcode().
Referenced by moco::RemoveTFIdentityNode::run().
dialect()
const loco::Dialect * moco::TFNode::dialect (void) const final virtual
Return "Dialect" identifier that this node belongs to.
dialect() SHOULD return a valid pointer.
Implements loco::Node.
Definition at line 27 of file TFNode.cpp.
{ return TFDialect::get(); }
References moco::TFDialect::get().
Referenced by moco::FuseBinaryIntoPreceding::run(), and moco::ResolveSquaredDifference::run().
name() [1/2]
void moco::TFNode::name (const NodeName & name) inline
Definition at line 51 of file TFNodeDecl.h.
{ _name = name; }
References name().
Referenced by name().
name() [2/2]
NodeName moco::TFNode::name (void) const inline
Definition at line 50 of file TFNodeDecl.h.
{ return _name; }
Referenced by moco::AvgPoolGraphBuilder::build(), moco::BiasAddGraphBuilder::build(), moco::ConcatV2GraphBuilder::build(), moco::ConstGraphBuilder::build(), moco::Conv2DGraphBuilder::build(), moco::IdentityGraphBuilder::build(), moco::MaxPoolGraphBuilder::build(), moco::PackGraphBuilder::build(), moco::ReluGraphBuilder::build(), moco::Relu6GraphBuilder::build(), moco::StridedSliceGraphBuilder::build(), moco::AddGraphBuilder::build(), moco::Conv2DBackpropInputGraphBuilder::build(), moco::DepthwiseConv2dNativeGraphBuilder::build(), moco::FakeQuantWithMinMaxVarsGraphBuilder::build(), moco::FusedBatchNormGraphBuilder::build(), moco::MaximumGraphBuilder::build(), moco::MeanGraphBuilder::build(), moco::MulGraphBuilder::build(), moco::PadGraphBuilder::build(), moco::PlaceholderGraphBuilder::build(), moco::RealDivGraphBuilder::build(), moco::RsqrtGraphBuilder::build(), moco::ShapeGraphBuilder::build(), moco::SoftmaxGraphBuilder::build(), moco::SqrtGraphBuilder::build(), moco::SquaredDifferenceGraphBuilder::build(), moco::SqueezeGraphBuilder::build(), moco::StopGradientGraphBuilder::build(), moco::SubGraphBuilder::build(), and moco::TanhGraphBuilder::build().
opcode()
virtual TFOpcode moco::TFNode::opcode (void) const pure virtual
Implemented in moco::TFNodeImpl< Code >, moco::TFNodeImpl< TFOpcode::Add >, moco::TFNodeImpl< TFOpcode::AvgPool >, moco::TFNodeImpl< TFOpcode::BiasAdd >, moco::TFNodeImpl< TFOpcode::ConcatV2 >, moco::TFNodeImpl< TFOpcode::Const >, moco::TFNodeImpl< TFOpcode::Conv2D >, moco::TFNodeImpl< TFOpcode::Conv2DBackpropInput >, moco::TFNodeImpl< TFOpcode::DepthwiseConv2dNative >, moco::TFNodeImpl< TFOpcode::FakeQuantWithMinMaxVars >, moco::TFNodeImpl< TFOpcode::FusedBatchNorm >, moco::TFNodeImpl< TFOpcode::Identity >, moco::TFNodeImpl< TFOpcode::MaxPool >, moco::TFNodeImpl< TFOpcode::Maximum >, moco::TFNodeImpl< TFOpcode::Mean >, moco::TFNodeImpl< TFOpcode::Mul >, moco::TFNodeImpl< TFOpcode::Pack >, moco::TFNodeImpl< TFOpcode::Pad >, moco::TFNodeImpl< TFOpcode::Placeholder >, moco::TFNodeImpl< TFOpcode::TFPush >, moco::TFNodeImpl< TFOpcode::RealDiv >, moco::TFNodeImpl< TFOpcode::Relu >, moco::TFNodeImpl< TFOpcode::Relu6 >, moco::TFNodeImpl< TFOpcode::Reshape >, moco::TFNodeImpl< TFOpcode::Rsqrt >, moco::TFNodeImpl< TFOpcode::Shape >, moco::TFNodeImpl< TFOpcode::Softmax >, moco::TFNodeImpl< TFOpcode::Sqrt >, moco::TFNodeImpl< TFOpcode::SquaredDifference >, moco::TFNodeImpl< TFOpcode::Squeeze >, moco::TFNodeImpl< TFOpcode::StopGradient >, moco::TFNodeImpl< TFOpcode::StridedSlice >, moco::TFNodeImpl< TFOpcode::Sub >, and moco::TFNodeImpl< TFOpcode::Tanh >.
Referenced by accept().
The documentation for this struct was generated from the following files:
compiler/moco/lang/include/moco/IR/TFNodeDecl.h
compiler/moco/lang/include/moco/IR/TFNodeImpl.h
compiler/moco/lang/src/IR/TFNode.cpp