ONE - On-device Neural Engine: coco::EntityManager Struct Reference
coco::EntityManager Struct Reference abstract
Meta (lifetime) manager interface.
#include <EntityManager.h>
Public Member Functions
virtual ~EntityManager ()=default
virtual BagManager * bag (void)=0
virtual const BagManager * bag (void) const =0
virtual ObjectManager * object (void)=0
virtual const ObjectManager * object (void) const =0
virtual OpManager * op (void)=0
virtual const OpManager * op (void) const =0
virtual InstrManager * instr (void)=0
virtual const InstrManager * instr (void) const =0
virtual BlockManager * block (void)=0
virtual const BlockManager * block (void) const =0
virtual InputManager * input (void)=0
virtual const InputManager * input (void) const =0
virtual OutputManager * output (void)=0
virtual const OutputManager * output (void) const =0
Detailed Description
Meta (lifetime) manager interface.
EntityManager is referred as meta manager as it is a gateway to other managers.
Definition at line 39 of file EntityManager.h.
Constructor & Destructor Documentation
~EntityManager()
virtual coco::EntityManager::~EntityManager () virtual default
Member Function Documentation
bag() [1/2]
virtual const BagManager * coco::EntityManager::bag (void) const pure virtual
bag() [2/2]
virtual BagManager * coco::EntityManager::bag (void) pure virtual
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::InputBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), and dump().
block() [1/2]
virtual const BlockManager * coco::EntityManager::block (void) const pure virtual
block() [2/2]
virtual BlockManager * coco::EntityManager::block (void) pure virtual
Referenced by Frontend::load().
input() [1/2]
virtual const InputManager * coco::EntityManager::input (void) const pure virtual
input() [2/2]
virtual InputManager * coco::EntityManager::input (void) pure virtual
Referenced by caffeimport::InputBuilder::build().
instr() [1/2]
virtual const InstrManager * coco::EntityManager::instr (void) const pure virtual
instr() [2/2]
virtual InstrManager * coco::EntityManager::instr (void) pure virtual
Referenced by InstrBuilder::copy(), and InstrBuilder::eval().
object() [1/2]
virtual const ObjectManager * coco::EntityManager::object (void) const pure virtual
object() [2/2]
virtual ObjectManager * coco::EntityManager::object (void) pure virtual
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::EltwiseBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), caffeimport::ScaleBuilder::build(), and dump().
op() [1/2]
virtual const OpManager * coco::EntityManager::op (void) const pure virtual
op() [2/2]
virtual OpManager * coco::EntityManager::op (void) pure virtual
Referenced by caffeimport::BatchNormBuilder::build(), caffeimport::ConcatBuilder::build(), caffeimport::ConvolutionBuilder::build(), caffeimport::PoolingBuilder::build(), caffeimport::ReLUBuilder::build(), and OpBuilder::load().
output() [1/2]
virtual const OutputManager * coco::EntityManager::output (void) const pure virtual
output() [2/2]
virtual OutputManager * coco::EntityManager::output (void) pure virtual
Referenced by Frontend::load().
The documentation for this struct was generated from the following file:
compiler/coco/core/include/coco/IR/EntityManager.h