ONE - On-device Neural Engine: flatbuffers::ToStringVisitor Struct Reference
flatbuffers::ToStringVisitor Struct Reference
#include <minireflect.h>
Public Member Functions
ToStringVisitor (std::string delimiter, bool quotes, std::string indent, bool vdelimited=true)
ToStringVisitor (std::string delimiter)
void append_indent ()
void StartSequence ()
void EndSequence ()
void Field (size_t, size_t set_idx, ElementaryType, bool, const TypeTable *, const char *name, const uint8_t *val)
template<typename T >
void Named (T x, const char *name)
void UType (uint8_t x, const char *name)
void Bool (bool x)
void Char (int8_t x, const char *name)
void UChar (uint8_t x, const char *name)
void Short (int16_t x, const char *name)
void UShort (uint16_t x, const char *name)
void Int (int32_t x, const char *name)
void UInt (uint32_t x, const char *name)
void Long (int64_t x)
void ULong (uint64_t x)
void Float (float x)
void Double (double x)
void String (const struct String *str)
void Unknown (const uint8_t *)
void StartVector ()
void EndVector ()
void Element (size_t i, ElementaryType, const TypeTable *, const uint8_t *)
Public Member Functions inherited from flatbuffers::IterationVisitor
virtual void String (const String *)
virtual ~IterationVisitor ()
Data Fields
std::string s
std::string d
bool q
std::string in
size_t indent_level
bool vector_delimited
Detailed Description
Definition at line 296 of file minireflect.h.
Constructor & Destructor Documentation
ToStringVisitor() [1/2]
flatbuffers::ToStringVisitor::ToStringVisitor (std::string delimiter, bool quotes, std::string indent, bool vdelimited = true) inline
Definition at line 303 of file minireflect.h.
      : d(delimiter),
        q(quotes),
        in(indent),
        indent_level(0),
        vector_delimited(vdelimited) {}
ToStringVisitor() [2/2]
flatbuffers::ToStringVisitor::ToStringVisitor (std::string delimiter) inline
Definition at line 310 of file minireflect.h.
      : d(delimiter),
        q(false),
        in(""),
        indent_level(0),
        vector_delimited(true) {}
Member Function Documentation
append_indent()
void flatbuffers::ToStringVisitor::append_indent () inline
Definition at line 317 of file minireflect.h.
                       {
    for (size_t i = 0; i < indent_level; i++) { s += in; }
  }
References in, indent_level, and s.
Referenced by Element(), EndSequence(), EndVector(), Field(), and StartVector().
Bool()
void flatbuffers::ToStringVisitor::Bool (bool x) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 358 of file minireflect.h.
{ s += x ? "true" : "false"; }
References s.
Char()
void flatbuffers::ToStringVisitor::Char (int8_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 359 of file minireflect.h.
{ Named(x, name); }
References Named().
Double()
void flatbuffers::ToStringVisitor::Double (double x) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 368 of file minireflect.h.
{ s += NumToString(x); }
References flatbuffers::NumToString(), and s.
Element()
void flatbuffers::ToStringVisitor::Element (size_t i, ElementaryType , const TypeTable * , const uint8_t *) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 393 of file minireflect.h.
{
    if (i) {
      s += ",";
      if (vector_delimited) {
        s += d;
        append_indent();
      } else {
        s += " ";
      }
    }
  }
References append_indent(), d, s, and vector_delimited.
EndSequence()
void flatbuffers::ToStringVisitor::EndSequence () inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 326 of file minireflect.h.
                     {
    s += d;
    indent_level--;
    append_indent();
    s += "}";
  }
References append_indent(), d, indent_level, and s.
EndVector()
void flatbuffers::ToStringVisitor::EndVector () inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 383 of file minireflect.h.
                   {
    if (vector_delimited) {
      s += d;
      indent_level--;
      append_indent();
    } else {
      s += " ";
    }
    s += "]";
  }
References append_indent(), d, indent_level, s, and vector_delimited.
Field()
void flatbuffers::ToStringVisitor::Field (size_t , size_t set_idx, ElementaryType , bool , const TypeTable * , const char * name, const uint8_t * val) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 332 of file minireflect.h.
{
    if (!val) return;
    if (set_idx) {
      s += ",";
      s += d;
    }
    append_indent();
    if (name) {
      if (q) s += "\"";
      s += name;
      if (q) s += "\"";
      s += ": ";
    }
  }
References append_indent(), d, q, and s.
Float()
void flatbuffers::ToStringVisitor::Float (float x) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 367 of file minireflect.h.
{ s += NumToString(x); }
References flatbuffers::NumToString(), and s.
Int()
void flatbuffers::ToStringVisitor::Int (int32_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 363 of file minireflect.h.
{ Named(x, name); }
References Named().
Long()
void flatbuffers::ToStringVisitor::Long (int64_t x) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 365 of file minireflect.h.
{ s += NumToString(x); }
References flatbuffers::NumToString(), and s.
Named()
template<typename T > void flatbuffers::ToStringVisitor::Named (T x, const char * name) inline
Definition at line 348 of file minireflect.h.
{
    if (name) {
      if (q) s += "\"";
      s += name;
      if (q) s += "\"";
    } else {
      s += NumToString(x);
    }
  }
References flatbuffers::NumToString(), q, and s.
Referenced by Char(), Int(), Short(), UChar(), UInt(), UShort(), and UType().
Short()
void flatbuffers::ToStringVisitor::Short (int16_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 361 of file minireflect.h.
{ Named(x, name); }
References Named().
StartSequence()
void flatbuffers::ToStringVisitor::StartSequence () inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 321 of file minireflect.h.
                       {
    s += "{";
    s += d;
    indent_level++;
  }
References d, indent_level, and s.
StartVector()
void flatbuffers::ToStringVisitor::StartVector () inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 373 of file minireflect.h.
                     {
    s += "[";
    if (vector_delimited) {
      s += d;
      indent_level++;
      append_indent();
    } else {
      s += " ";
    }
  }
References append_indent(), d, indent_level, s, and vector_delimited.
String()
void flatbuffers::ToStringVisitor::String (const struct String * str) inline
Definition at line 369 of file minireflect.h.
{
    EscapeString(str->c_str(), str->size(), &s, true, false);
  }
References flatbuffers::EscapeString(), and s.
UChar()
void flatbuffers::ToStringVisitor::UChar (uint8_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 360 of file minireflect.h.
{ Named(x, name); }
References Named().
UInt()
void flatbuffers::ToStringVisitor::UInt (uint32_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 364 of file minireflect.h.
{ Named(x, name); }
References Named().
ULong()
void flatbuffers::ToStringVisitor::ULong (uint64_t x) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 366 of file minireflect.h.
{ s += NumToString(x); }
References flatbuffers::NumToString(), and s.
Unknown()
void flatbuffers::ToStringVisitor::Unknown (const uint8_t *) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 372 of file minireflect.h.
{ s += "(?)"; }
References s.
UShort()
void flatbuffers::ToStringVisitor::UShort (uint16_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 362 of file minireflect.h.
{ Named(x, name); }
References Named().
UType()
void flatbuffers::ToStringVisitor::UType (uint8_t x, const char * name) inline virtual
Reimplemented from flatbuffers::IterationVisitor.
Definition at line 357 of file minireflect.h.
{ Named(x, name); }
References Named().
Field Documentation
d
std::string flatbuffers::ToStringVisitor::d
Definition at line 298 of file minireflect.h.
Referenced by Element(), EndSequence(), EndVector(), Field(), StartSequence(), and StartVector().
in
std::string flatbuffers::ToStringVisitor::in
Definition at line 300 of file minireflect.h.
Referenced by append_indent().
indent_level
size_t flatbuffers::ToStringVisitor::indent_level
Definition at line 301 of file minireflect.h.
Referenced by append_indent(), EndSequence(), EndVector(), StartSequence(), and StartVector().
q
bool flatbuffers::ToStringVisitor::q
Definition at line 299 of file minireflect.h.
Referenced by Field(), and Named().
s
std::string flatbuffers::ToStringVisitor::s
Definition at line 297 of file minireflect.h.
Referenced by append_indent(), Bool(), Double(), Element(), EndSequence(), EndVector(), Field(), flatbuffers::FlatBufferToString(), Float(), Long(), Named(), StartSequence(), StartVector(), String(), ULong(), and Unknown().
vector_delimited
bool flatbuffers::ToStringVisitor::vector_delimited
Definition at line 302 of file minireflect.h.
Referenced by Element(), EndVector(), and StartVector().
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/minireflect.h