ONE - On-device Neural Engine: luci::PropagateQParamBackwardPass Struct Reference
luci::PropagateQParamBackwardPass Struct Reference final
Class to propagate quantization parameters of an operator's output to input.
#include <PropagateQParamBackwardPass.h>
Public Member Functions
PropagateQParamBackwardPass (loco::DataType output)
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Class to propagate quantization parameters of an operator's output to input.
Definition at line 28 of file PropagateQParamBackwardPass.h.
Constructor & Destructor Documentation
PropagateQParamBackwardPass()
luci::PropagateQParamBackwardPass::PropagateQParamBackwardPass (loco::DataType output) inline
Definition at line 30 of file PropagateQParamBackwardPass.h.
: _output_model_dtype(output) {}
Member Function Documentation
name()
const char * luci::PropagateQParamBackwardPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 32 of file PropagateQParamBackwardPass.h.
{ return "luci::PropagateQParamBackwardPass"; }
run()
bool luci::PropagateQParamBackwardPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 458 of file PropagateQParamBackwardPass.cpp.
{
  LOGGER(l);
  // We use reverse post-order traversal as qparam is propagated backward
  auto nodes = loco::postorder_traversal(loco::output_nodes(g));
  std::reverse(nodes.begin(), nodes.end());
  for (auto node : nodes)
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    INFO(l) << "PropagateQParamBackwardPass visit node: " << circle_node->name() << std::endl;
    // We can't propagate non-existent qparam
    if (circle_node->quantparam() == nullptr)
      continue;
    PropagateQParamBackward pqb;
    circle_node->accept(&pqb);
  }
  // This pass is only run once, so return false
  // TODO Refactoring not to return meaningless value
  return false;
}
References INFO, LOGGER, loco::output_nodes(), and loco::postorder_traversal().
Referenced by luci::QuantizeWithMinMaxPass::run().
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/PropagateQParamBackwardPass.h
compiler/luci/pass/src/PropagateQParamBackwardPass.cpp