ONE - On-device Neural Engine: OutputLayer Struct Reference
OutputLayer Struct Reference final
#include <GraphBuilder.h>
Data Structures
class Return
Public Member Functions
std::unique_ptr< Return > operator() (GraphBuilder::Context *ctx)
Detailed Description
Definition at line 165 of file GraphBuilder.h.
Member Function Documentation
operator()()
std::unique_ptr< Return > OutputLayer::operator() (GraphBuilder::Context * ctx) inline
Definition at line 192 of file GraphBuilder.h.
  {
    auto output_index = ctx->graph()->outputs()->size();
    auto graph_output = ctx->graph()->outputs()->create();
    auto push_node = ctx->graph()->nodes()->create<loco::Push>();
    push_node->from(ctx->stack()->pop());
    push_node->index(output_index);
    loco::link(graph_output, push_node);
    ctx->stack()->push(push_node);
    return std::make_unique<Return>(graph_output, push_node);
  }
References loco::NodePool::create(), loco::Graph::OutputContext::create(), loco::Push::from(), GraphBuilder::Context::graph(), loco::Push::index(), loco::link(), loco::Graph::nodes(), loco::Graph::outputs(), GraphBuilder::Stack::pop(), GraphBuilder::Stack::push(), loco::ObjectPool< T >::size(), and GraphBuilder::Context::stack().
The documentation for this struct was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h