ONE - On-device Neural Engine: moco::tf::SimpleNodeTransform< ConcreteNode > Struct Template Reference
moco::tf::SimpleNodeTransform< ConcreteNode > Struct Template Reference abstract
Per-Node Transform.
#include <SimpleNodeTransform.h>
Public Member Functions
SimpleNodeTransform ()=default
virtual ~SimpleNodeTransform ()=default
virtual bool transform (ConcreteNode *node) const =0
bool run (loco::Graph *graph) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
template<typename ConcreteNode>
struct moco::tf::SimpleNodeTransform< ConcreteNode >
Per-Node Transform.
Definition at line 30 of file SimpleNodeTransform.h.
Constructor & Destructor Documentation
SimpleNodeTransform()
template<typename ConcreteNode > moco::tf::SimpleNodeTransform< ConcreteNode >::SimpleNodeTransform () default
~SimpleNodeTransform()
template<typename ConcreteNode > virtual moco::tf::SimpleNodeTransform< ConcreteNode >::~SimpleNodeTransform () virtual default
Member Function Documentation
run()
template<typename ConcreteNode > bool moco::tf::SimpleNodeTransform< ConcreteNode >::run (loco::Graph * graph) inline final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 39 of file SimpleNodeTransform.h.
  {
    using loco::active_nodes;
    using loco::output_nodes;
    bool changed = false;
    for (auto node : active_nodes(output_nodes(graph)))
    {
      if (auto casted = dynamic_cast<ConcreteNode *>(node))
      {
        if (transform(casted))
        {
          changed = true;
        }
      }
    }
    return changed;
  }
References loco::active_nodes(), loco::output_nodes(), and moco::tf::SimpleNodeTransform< ConcreteNode >::transform().
transform()
template<typename ConcreteNode > virtual bool moco::tf::SimpleNodeTransform< ConcreteNode >::transform (ConcreteNode * node) const pure virtual
Implemented in moco::tf::ConcatV2Canonicalizer, moco::tf::ConstCanonicalizer, moco::tf::Conv2DBackpropInputCanonicalizer, moco::tf::DepthwiseConv2dNativeCanonicalizer, moco::tf::IdentityCanonicalizer, moco::tf::MaximumCanonicalizer, moco::tf::MaxPoolCanonicalizer, moco::tf::MeanCanonicalizer, moco::tf::MulCanonicalizer, moco::tf::PadCanonicalizer, moco::tf::TFPushCanonicalizer, moco::tf::RealDivCanonicalizer, moco::tf::ReluCanonicalizer, moco::tf::Relu6Canonicalizer, moco::tf::ReshapeCanonicalizer, moco::tf::RsqrtCanonicalizer, moco::tf::SoftmaxCanonicalizer, moco::tf::SqrtCanonicalizer, moco::tf::SqueezeCanonicalizer, moco::tf::StopGradientCanonicalizer, moco::tf::SubCanonicalizer, moco::tf::TanhCanonicalizer, moco::tf::AddCanonicalizer, moco::tf::AvgPoolCanonicalizer, moco::tf::BiasAddCanonicalizer, and moco::tf::Conv2DCanonicalizer.
Referenced by moco::tf::SimpleNodeTransform< ConcreteNode >::run().
The documentation for this struct was generated from the following file:
compiler/moco-tf/src/SimpleNodeTransform.h