ONE - On-device Neural Engine: onert_micro::import::OMKernelConfiguration Struct Reference
onert_micro::import::OMKernelConfiguration Struct Reference
#include <OMKernelConfiguration.h>
Static Public Member Functions
static OMStatus configureKernels (OMConfigureArgs &)
Detailed Description
Definition at line 31 of file OMKernelConfiguration.h.
Member Function Documentation
configureKernels()
OMStatus OMKernelConfiguration::configureKernels (OMConfigureArgs & configure_args) static
Definition at line 25 of file OMKernelConfiguration.cpp.
{
  OMRuntimeContext &runtime_context = configure_args.runtime_context;
  const reader::CircleOperators *operators = runtime_context.getCircleOperators();
  const auto num_operators = static_cast<uint16_t>(operators->size());
  const auto op_codes = runtime_context.getCircleOpcodes();
  OMStatus status = Ok;
  for (uint16_t i = 0; i < num_operators; ++i)
  {
    OMBuilderID builder_id = core::OMBuilderID::Size;
    const circle::Operator *op = operators->operator[](i);
    uint32_t index = op->opcode_index();
    assert(index < op_codes->size());
    const auto opcode = op_codes->operator[](index);
    status = core::getBuilderId(opcode, builder_id);
    assert(status == Ok);
    if (status != Ok)
      return status;
    KernelConfigureFunc *configure_func = nullptr;
    if (size_t(builder_id) < size_t(core::OMBuilderID::BuiltinOperatorsSize))
    {
      // Builtin operator
      status = kernel_builtin_configure.getKernelConfigureFunc(builder_id, &configure_func);
    }
    else
    {
      // Custom
      status = kernel_custom_configure.getKernelConfigureFunc(builder_id, &configure_func);
    }
    assert(configure_func != nullptr);
    if (status != Ok)
      return status;
    configure_args.kernel_index = i;
    status = configure_func(configure_args);
    assert(status == Ok && "");
  }
  return status;
}
References onert_micro::core::BuiltinOperatorsSize, onert_micro::core::getBuilderId(), onert_micro::core::OMRuntimeContext::getCircleOpcodes(), onert_micro::core::OMRuntimeContext::getCircleOperators(), onert_micro::import::KernelBuiltinConfigureRegistry::getKernelConfigureFunc(), onert_micro::import::KernelCustomConfigureRegistry::getKernelConfigureFunc(), onert_micro::import::kernel_builtin_configure, onert_micro::import::kernel_custom_configure, onert_micro::import::OMConfigureArgs::kernel_index, onert_micro::Ok, onert_micro::import::OMConfigureArgs::runtime_context, flatbuffers::Vector< T >::size(), size, and onert_micro::core::Size.
Referenced by onert_micro::core::OMRuntimeModule::importModel().
The documentation for this struct was generated from the following files:
onert-micro/onert-micro/include/import/OMKernelConfiguration.h
onert-micro/onert-micro/src/import/OMKernelConfiguration.cpp