ONE - On-device Neural Engine: coco::DLinkedList< Child, Parent > Struct Template Reference
coco::DLinkedList< Child, Parent > Struct Template Reference
#include <DLinkedList.h>
Data Structures
class Head
class Node
Public Member Functions
void joined (Module *, Block *curr_blk)
void leaving (Module *, Block *curr_blk)
BlockList * head (Module *m)
void joined (Block *, Instr *curr_ins)
void leaving (Block *, Instr *curr_ins)
InstrList * head (Block *b)
Static Public Member Functions
static void joined (Parent *, Child *)
A hook for Child-Join event.
static void leaving (Parent *, Child *)
A hook for Child-Leave event.
static Head * head (Parent *)
Detailed Description
template<typename Child, typename Parent>
struct coco::DLinkedList< Child, Parent >
Definition at line 27 of file DLinkedList.h.
Member Function Documentation
head() [1/3]
InstrList * coco::DLinkedList< Instr, Block >::head (Block * b)
Definition at line 54 of file Instr.cpp.
{ return b->instr(); }
head() [2/3]
BlockList * coco::DLinkedList< Block, Module >::head (Module * m)
Definition at line 54 of file Block.cpp.
{ return m->block(); }
References m.
head() [3/3]
template<typename Child , typename Parent > static Head * coco::DLinkedList< Child, Parent >::head (Parent *) static
Referenced by coco::DLinkedList< Child, Parent >::Node::detach(), coco::DLinkedList< Child, Parent >::Node::insertAfter(), and coco::DLinkedList< Child, Parent >::Node::insertBefore().
joined() [1/3]
void coco::DLinkedList< Instr, Block >::joined (Block * , Instr * curr_ins)
Definition at line 25 of file Instr.cpp.
{
  assert(!curr_ins->index().valid());
  uint32_t value = 0;
  if (auto prev_ins = curr_ins->prev())
  {
    value = prev_ins->index().value() + 1;
  }
  for (auto ins = curr_ins; ins; ins = ins->next())
  {
    ins->_index.set(value++);
  }
}
References coco::Instr::index(), coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::prev(), and coco::InstrIndex::valid().
joined() [2/3]
void coco::DLinkedList< Block, Module >::joined (Module * , Block * curr_blk)
Definition at line 25 of file Block.cpp.
{
  assert(!curr_blk->index().valid());
  uint32_t value = 0;
  if (auto prev_blk = curr_blk->prev())
  {
    value = prev_blk->index().value() + 1;
  }
  for (auto blk = curr_blk; blk; blk = blk->next())
  {
    blk->_index.set(value++);
  }
}
References coco::Block::index(), coco::DLinkedList< Child, Parent >::Node::next(), coco::DLinkedList< Child, Parent >::Node::prev(), and coco::BlockIndex::valid().
joined() [3/3]
template<typename Child , typename Parent > static void coco::DLinkedList< Child, Parent >::joined (Parent * , Child *) static
A hook for Child-Join event.
Referenced by coco::DLinkedList< Child, Parent >::Head::enlist().
leaving() [1/3]
void coco::DLinkedList< Instr, Block >::leaving (Block * , Instr * curr_ins)
Definition at line 41 of file Instr.cpp.
{
  assert(curr_ins->index().valid());
  uint32_t value = curr_ins->index().value();
  for (auto ins = curr_ins->next(); ins; ins = ins->next())
  {
    ins->_index.set(value++);
  }
  curr_ins->_index.reset();
}
References coco::Instr::index(), coco::DLinkedList< Child, Parent >::Node::next(), coco::InstrIndex::reset(), coco::InstrIndex::valid(), and coco::InstrIndex::value().
leaving() [2/3]
void coco::DLinkedList< Block, Module >::leaving (Module * , Block * curr_blk)
Definition at line 41 of file Block.cpp.
{
  assert(curr_blk->index().valid());
  uint32_t value = curr_blk->index().value();
  for (auto blk = curr_blk->next(); blk; blk = blk->next())
  {
    blk->_index.set(value++);
  }
  curr_blk->_index.reset();
}
References coco::Block::index(), coco::DLinkedList< Child, Parent >::Node::next(), coco::BlockIndex::reset(), coco::BlockIndex::valid(), and coco::BlockIndex::value().
leaving() [3/3]
template<typename Child , typename Parent > static void coco::DLinkedList< Child, Parent >::leaving (Parent * , Child *) static
A hook for Child-Leave event.
Referenced by coco::DLinkedList< Child, Parent >::Head::delist().
The documentation for this struct was generated from the following file:
compiler/coco/core/include/coco/ADT/DLinkedList.h