ONE - On-device Neural Engine: luci::FuseBCQPass Struct Reference
luci::FuseBCQPass Struct Reference final
Class to fuse certain pattern of subgraph into CircleBCQFullyConnected or CircleBCQGather.
#include <FuseBCQPass.h>
Public Member Functions
const char * name (void) const final
bool run (luci::Module *m) final
bool run (loco::Graph *g) final
Run the pass.
virtual bool run (luci::Module *)=0
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Class to fuse certain pattern of subgraph into CircleBCQFullyConnected or CircleBCQGather.
Definition at line 29 of file FuseBCQPass.h.
Member Function Documentation
name()
const char * luci::FuseBCQPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 31 of file FuseBCQPass.h.
{ return "luci::FuseBCQPass"; }
run() [1/2]
bool luci::FuseBCQPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 692 of file FuseBCQPass.cpp.
{
  // Do nothing for graph
  return false;
}
run() [2/2]
bool luci::FuseBCQPass::run (luci::Module * m) final virtual
Implements luci::Pass.
Definition at line 613 of file FuseBCQPass.cpp.
{
  bool changed = false;
  const int32_t start_magicnum = -2e9 + 27;
  const int32_t end_magicnum = 2e9 - 27;
  loco::Graph *main_graph = m->graph(0);
  luci::CircleConst *metadata_node = nullptr;
  for (auto node : loco::output_nodes(main_graph))
  {
    auto output_node = loco::must_cast<luci::CircleOutput *>(node);
    // Metadata node should be first output
    if (output_node->index() != 0)
      continue;
    // Metadata should be constant and dtype should be S32
    auto const_node = dynamic_cast<luci::CircleConst *>(output_node->from());
    if (const_node == nullptr || const_node->dtype() != loco::DataType::S32)
      continue;
    // Metadata has at least four elements
    const auto element_cnt = const_node->size<loco::DataType::S32>();
    if (element_cnt < 4)
      continue;
    // Metadata has magic numbers at first and at last
    const auto start_value = const_node->at<loco::DataType::S32>(0);
    const auto end_value = const_node->at<loco::DataType::S32>(element_cnt - 1);
    if (start_value == start_magicnum && end_value == end_magicnum)
    {
      metadata_node = const_node;
      break;
    }
  }
  if (metadata_node != nullptr)
  {
    const auto bcq_version = metadata_node->at<loco::DataType::S32>(1);
    const auto original_output_cnt = metadata_node->at<loco::DataType::S32>(2);
    if (bcq_version == 1)
    {
      const auto bundle_cnt = metadata_node->at<loco::DataType::S32>(3);
      BCQFuser<1> fuser{original_output_cnt, bundle_cnt};
      fuser.register_bcq_info(main_graph);
      for (size_t g = 0; g < m->size(); ++g)
        if (fuser.fuseBCQ(m->graph(g)))
          changed = true;
    }
    else
    {
      LOGGER(l);
      WARN(l) << "Not supported BCQ version is found." << std::endl;
    }
    // Remove all of BCQ information nodes iff there is no change
    if (changed == false)
    {
      for (auto node : loco::output_nodes(main_graph))
      {
        auto output_node = loco::must_cast<luci::CircleOutput *>(node);
        if (output_node->index() == 0 || (int)output_node->index() > original_output_cnt)
        {
          auto noOp = main_graph->nodes()->create<luci::CircleOutputExclude>();
          output_node->from(noOp);
          changed = true;
        }
      }
    }
  }
  return changed;
}
References luci::CircleConst::at(), loco::NodePool::create(), luci::CircleOutput::from(), luci::CircleOutput::index(), LOGGER, m, loco::Graph::nodes(), luci::output_node(), loco::output_nodes(), luci::CircleConst::size(), and WARN.
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/FuseBCQPass.h
compiler/luci/pass/src/FuseBCQPass.cpp