ONE - On-device Neural Engine: enco::GlobalData Struct Reference
enco::GlobalData Struct Reference
#include <GlobalDataGeneration.h>
Static Public Member Functions
static GlobalOffset data_offset (const ann::Operand *)
static GlobalOffset data_offset (const coco::Bag *)
Return the weight offset of a given bag.
static GlobalOffset name_offset (const coco::Input *)
static GlobalOffset dims_offset (const coco::Input *)
static GlobalOffset name_offset (const coco::Output *)
static GlobalOffset dims_offset (const coco::Output *)
Detailed Description
Definition at line 29 of file GlobalDataGeneration.h.
Member Function Documentation
data_offset() [1/2]
GlobalOffset enco::GlobalData::data_offset (const ann::Operand * o) static
Definition at line 95 of file GlobalDataGeneration.cpp.
{ return data_offset_ctx.at(o); }
Referenced by enco::CppCode::dump().
data_offset() [2/2]
GlobalOffset enco::GlobalData::data_offset (const coco::Bag * bag) static
Return the weight offset of a given bag.
Note
The behavior of "data_offset" is undefined if a bag has no weight.
Definition at line 97 of file GlobalDataGeneration.cpp.
{
  assert(bag_data_offset_ctx.find(bag) != bag_data_offset_ctx.end());
  return bag_data_offset_ctx.at(bag);
}
dims_offset() [1/2]
GlobalOffset enco::GlobalData::dims_offset (const coco::Input * in) static
Definition at line 104 of file GlobalDataGeneration.cpp.
{ return dims_offset_ctx.at(in); }
Referenced by enco::CppCode::dump().
dims_offset() [2/2]
GlobalOffset enco::GlobalData::dims_offset (const coco::Output * out) static
Definition at line 107 of file GlobalDataGeneration.cpp.
{ return dims_offset_ctx.at(out); }
name_offset() [1/2]
GlobalOffset enco::GlobalData::name_offset (const coco::Input * in) static
Definition at line 103 of file GlobalDataGeneration.cpp.
{ return name_offset_ctx.at(in); }
Referenced by enco::CppCode::dump().
name_offset() [2/2]
GlobalOffset enco::GlobalData::name_offset (const coco::Output * out) static
Definition at line 106 of file GlobalDataGeneration.cpp.
{ return name_offset_ctx.at(out); }
The documentation for this struct was generated from the following files:
compiler/enco/core/src/Transforms/GlobalDataGeneration.h
compiler/enco/core/src/Transforms/GlobalDataGeneration.cpp