ONE - On-device Neural Engine: nnfw::cker::functor::BroadcastTo< Device, T > Struct Template Reference
nnfw::cker::functor::BroadcastTo< Device, T > Struct Template Reference
#include <BroadcastTo.h>
Public Member Functions
template<int NDIMS>
void DoBCast32Bit (const Device &device, typename TTypes< T, NDIMS >::Tensor out, typename TTypes< T, NDIMS >::ConstTensor in, const typename Eigen::array< int, NDIMS > &bcast) const
template<int NDIMS>
void DoBCast (const Device &device, typename TTypes< T, NDIMS >::Tensor out, typename TTypes< T, NDIMS >::ConstTensor in, const typename Eigen::array< Eigen::DenseIndex, NDIMS > &bcast) const
template<int NDIMS>
void ReshapeAndBCast (const Device &device, Tensor &output_tensor, const Tensor &input_tensor, const BCast &bcast) const
void operator() (const Device &device, Tensor &output_tensor, const Shape &output_shape, const Tensor &input_tensor, const Shape &input_shape, const BCast &bcast) const
Detailed Description
template<typename Device, typename T>
struct nnfw::cker::functor::BroadcastTo< Device, T >
Definition at line 58 of file BroadcastTo.h.
Member Function Documentation
DoBCast()
template<typename Device , typename T > template<int NDIMS> void nnfw::cker::functor::BroadcastTo< Device, T >::DoBCast (const Device & device, typename TTypes< T, NDIMS >::Tensor out, typename TTypes< T, NDIMS >::ConstTensor in, const typename Eigen::array< Eigen::DenseIndex, NDIMS > & bcast) const inline
Definition at line 69 of file BroadcastTo.h.
  {
    out.device(device) = in.broadcast(bcast);
  }
DoBCast32Bit()
template<typename Device , typename T > template<int NDIMS> void nnfw::cker::functor::BroadcastTo< Device, T >::DoBCast32Bit (const Device & device, typename TTypes< T, NDIMS >::Tensor out, typename TTypes< T, NDIMS >::ConstTensor in, const typename Eigen::array< int, NDIMS > & bcast) const inline
Definition at line 61 of file BroadcastTo.h.
  {
    To32Bit(out).device(device) = To32Bit(in).broadcast(bcast);
  }
References nnfw::cker::To32Bit().
operator()()
template<typename Device , typename T > void nnfw::cker::functor::BroadcastTo< Device, T >::operator() (const Device & device, Tensor & output_tensor, const Shape & output_shape, const Tensor & input_tensor, const Shape & input_shape, const BCast & bcast) const inline
Definition at line 100 of file BroadcastTo.h.
  {
    const int ndims = bcast.y_reshape().size();
    switch (ndims)
    {
      case 1:
        ReshapeAndBCast<1>(device, output_tensor, input_tensor, bcast);
        break;
      case 2:
        ReshapeAndBCast<2>(device, output_tensor, input_tensor, bcast);
        break;
      case 3:
        ReshapeAndBCast<3>(device, output_tensor, input_tensor, bcast);
        break;
      case 4:
        ReshapeAndBCast<4>(device, output_tensor, input_tensor, bcast);
        break;
      case 5:
        ReshapeAndBCast<5>(device, output_tensor, input_tensor, bcast);
        break;
      default:
        // NOTE : UNUSED leaves for maintenance purposes.
        UNUSED(output_shape);
        UNUSED(input_shape);
        break;
    }
  }
References UNUSED, and nnfw::cker::BCast::y_reshape().
ReshapeAndBCast()
template<typename Device , typename T > template<int NDIMS> void nnfw::cker::functor::BroadcastTo< Device, T >::ReshapeAndBCast (const Device & device, Tensor & output_tensor, const Tensor & input_tensor, const BCast & bcast) const inline
Definition at line 77 of file BroadcastTo.h.
  {
    const bool can_use_32bit = std::is_same<Eigen::GpuDevice, Device>::value &&
                               output_tensor.shape.FlatSize() < kint32max &&
                               input_tensor.shape.FlatSize() < kint32max;
    if (can_use_32bit)
    {
      DoBCast32Bit<NDIMS>(device, output_tensor.template shaped<T, NDIMS>(bcast.result_shape()),
                          input_tensor.template shaped<T, NDIMS>(bcast.x_reshape()),
                          BCast::ToIndexArrayType<int, NDIMS>(bcast.x_bcast()));
    }
    else
    {
      DoBCast<NDIMS>(device, output_tensor.template shaped<T, NDIMS>(bcast.result_shape()),
                     input_tensor.template shaped<T, NDIMS>(bcast.x_reshape()),
                     BCast::ToIndexArrayType<Eigen::DenseIndex, NDIMS>(bcast.x_bcast()));
    }
  }
References nnfw::cker::Shape::FlatSize(), nnfw::cker::BCast::result_shape(), nnfw::cker::Tensor::shape, nnfw::cker::BCast::x_bcast(), and nnfw::cker::BCast::x_reshape().
The documentation for this struct was generated from the following file:
compute/cker/include/cker/operation/BroadcastTo.h