ONE - On-device Neural Engine: luci::sinf::Rule Struct Reference
luci::sinf::Rule Struct Reference
#include <CircleShapeInference.h>
Public Member Functions
bool infer (const luci::CircleNode *, loco::TensorShape &) const
Detailed Description
Definition at line 33 of file CircleShapeInference.h.
Member Function Documentation
infer()
bool luci::sinf::Rule::infer (const luci::CircleNode * circle_node, loco::TensorShape & shape) const
Definition at line 67 of file CircleShapeInference.cpp.
{
  LOGGER(l);
  VERBOSE(l, 1) << "[CircleShapeInference] " << circle_node->name();
  VERBOSE(l, 1) << "  before: " << circle_shape(circle_node);
  if (!inputs_shape_ready(circle_node))
  {
    VERBOSE(l, 1) << " after: Some inputs are not ready for inference";
    return false;
  }
  Algorithm alg;
  shape = circle_node->accept(&alg);
  VERBOSE(l, 1) << " after: " << shape;
  return true;
}
References luci::CircleNode::accept(), luci::sinf::circle_shape(), LOGGER, luci::CircleNode::name(), and VERBOSE.
Referenced by luci::CircleShapeInferencePass::run().
The documentation for this struct was generated from the following files:
compiler/luci/service/include/luci/Service/CircleShapeInference.h
compiler/luci/service/src/CircleShapeInference.cpp