ONE - On-device Neural Engine: loco::CanonicalTypeInferenceRule Struct Reference
loco::CanonicalTypeInferenceRule Struct Reference final
Type Inference Rule for Canonical Dialect.
#include <TypeInference.h>
Public Member Functions
bool recognize (const Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const Node *, DataType &) const final
Public Member Functions inherited from loco::TypeInferenceRule
virtual ~TypeInferenceRule ()=default
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, DataType &) const =0
Detailed Description
Type Inference Rule for Canonical Dialect.
Definition at line 62 of file TypeInference.h.
Member Function Documentation
infer()
bool loco::CanonicalTypeInferenceRule::infer (const Node * , DataType &) const final virtual
Framework guarantees the followings:
Framework tries to infer the data type of each node only after the data type of all of its valid (= non-nullptr) argument nodes is inferred.
The result of preceding "infer" is accessible through below dtype_get method.
This holds only when preceding "infer" returns true.
Implements loco::TypeInferenceRule.
Definition at line 178 of file TypeInference.cpp.
{
  assert(node->dialect() == loco::CanonicalDialect::get());
  assert(dynamic_cast<const loco::CanonicalNode *>(node) != nullptr);
  CanonicalTypeForwardAlgorithm alg;
  dtype = loco::must_cast<const loco::CanonicalNode *>(node)->accept(&alg);
  return true;
}
References loco::Node::dialect(), and loco::CanonicalDialect::get().
recognize()
bool loco::CanonicalTypeInferenceRule::recognize (const Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::TypeInferenceRule.
Definition at line 172 of file TypeInference.cpp.
{
  // This rule recognizes only "loco.canonical" dialect!
  return CanonicalDialect::get() == d;
}
References loco::CanonicalDialect::get().
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/Service/TypeInference.h
compiler/loco/src/Service/TypeInference.cpp