ONE - On-device Neural Engine: logo::ReorderDecodePass< loco::TensorBiasAdd > Struct Reference
logo::ReorderDecodePass< loco::TensorBiasAdd > Struct Reference final
#include <ReorderDecodePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Definition at line 35 of file ReorderDecodePass.h.
Member Function Documentation
name()
const char * logo::ReorderDecodePass< loco::TensorBiasAdd >::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 37 of file ReorderDecodePass.h.
{ return "ReorderDecodePass<TensorBiasAdd> "; }
run()
bool logo::ReorderDecodePass< loco::TensorBiasAdd >::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Let us consider the following graph:
A —> FeatureDecode(1) —> ReLU(2)
ReorderDecodeTransform rewrites this graph as follows:
A -+-> FeatureDecode(1) —> ReLU(2) | +-> ReLU(2') —> FeatureDecode(1')
Let us feed this updates graph to ReorderDecodeTransform.
The naive implementation will create a new ReLU->FeatureDecode chain again, and results in unbounded graph blow-up.
A -+-> FeatureDeocde(1) —> ReLU(2) | +-> ReLU(2') —> FeatureDecode(1') | +-> ReLU(2'') —> FeatureDecode(1'')
This check prevents such unbounded graph blow-up.
Let us consider the following example:
A -=-> FeatureDecode(1) -+-> TensorBiasAdd(2) -+-> B1 | | | +-> B2 | | | +-> ... | +-> ...
At this point, "cur_decode" points to (1) and "u" points to (2).
First rewrite the graph as follows:
A -+-> FeatureBiasAdd(2') —> FeatureDecode(1') -+-> B1 | | | +-> B2 | | | +-> ... | +-> FeatureDecode(1) -+-> TensorBiasAdd(2) ; NO USE | +-> ...
Q. Is it safe to apply this transform without "decoder" check?
Implements logo::Pass.
Definition at line 83 of file ReorderDecodePass.cpp.
{
  std::queue<loco::FeatureDecode *> q;
  gather_candidates(g, q);
  bool changed = false;
  while (!q.empty())
  {
    auto cur_decode = q.front();
    q.pop();
    // Collector IS EXPECTED TO guarantee this property
    assert(cur_decode->input() != nullptr);
    for (auto u : loco::succs(cur_decode))
    {
      if (loco::succs(u).empty())
      {
        continue;
      }
      // Q. Is it better to create an independent transform for this rewriting rule?
      if (isTensorBiasAdd(u))
      {
        auto old_badd = loco::must_cast<loco::TensorBiasAdd *>(u);
        auto new_badd = g->nodes()->create<loco::FeatureBiasAdd>();
        auto new_decode = g->nodes()->create<loco::FeatureDecode>();
        new_badd->value(cur_decode->input());
        new_badd->bias(old_badd->bias());
        new_decode->input(new_badd);
        new_decode->decoder(cur_decode->decoder()->clone());
        loco::replace(u).with(new_decode);
        // Enque FeatureDeocde(1') for the further optimization.
        q.push(new_decode);
        changed = true;
      }
    }
  }
  return changed;
}
References loco::replace(), loco::succs(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this struct was generated from the following files:
compiler/logo/include/logo/ReorderDecodePass.h
compiler/logo/src/Passes/ReorderDecodePass.cpp