ONE - On-device Neural Engine: onert::exec::IExecutor Struct Reference
onert::exec::IExecutor Struct Reference abstract
Struct to define interface of Executor.
#include <IExecutor.h>
Public Member Functions
IExecutor ()=default
Construct a new IExecutor object.
virtual ~IExecutor ()=default
Destroy the IExecutor object.
virtual const ir::Graph & graph () const =0
Returns graph object.
virtual void setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >)=0
Set an ordering on operations.
virtual void execute (const std::vector< backend::IPortableTensor * > &inputs, const std::vector< backend::IPortableTensor * > &outputs, const ExecutionOptions &options)=0
Execute with given input/output tensors.
virtual uint32_t inputSize () const =0
Get input size.
virtual uint32_t outputSize () const =0
Get output size.
virtual const ir::OperandInfo & inputInfo (uint32_t index) const =0
Get input info at index.
virtual const ir::OperandInfo & outputInfo (uint32_t index) const =0
Get output info at index.
virtual ir::Layout inputLayout (uint32_t index) const =0
Get input layout at index.
virtual ir::Layout outputLayout (uint32_t index) const =0
Get output layout at index.
virtual const uint8_t * outputBuffer (uint32_t index) const =0
Get output buffer at index.
virtual const backend::IPortableTensor * outputTensor (uint32_t index) const =0
Get output tensor at index.
virtual const ExecutionOptions & currentOptions () const =0
Return current execution configuration.
Detailed Description
Struct to define interface of Executor.
Definition at line 40 of file IExecutor.h.
Constructor & Destructor Documentation
IExecutor()
onert::exec::IExecutor::IExecutor () default
Construct a new IExecutor object.
~IExecutor()
virtual onert::exec::IExecutor::~IExecutor () virtual default
Destroy the IExecutor object.
Member Function Documentation
currentOptions()
virtual const ExecutionOptions & onert::exec::IExecutor::currentOptions () const pure virtual
Return current execution configuration.
Returns
Current execution configuration
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::backend::builtin::kernel::IfLayer::run(), and onert::backend::builtin::kernel::WhileLayer::run().
execute()
virtual void onert::exec::IExecutor::execute (const std::vector< backend::IPortableTensor * > & inputs, const std::vector< backend::IPortableTensor * > & outputs, const ExecutionOptions & options) pure virtual
Execute with given input/output tensors.
Input and output tensors must be given.
Parameters
[in] inputs Tensors that are passed as inputs
[in] outputs Tensors that are passed as outputs
[in] options Execution options
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::execute(), and onert::backend::builtin::kernel::IfLayer::run().
graph()
virtual const ir::Graph & onert::exec::IExecutor::graph () const pure virtual
Returns graph object.
Returns
Graph object
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::exec::ProfileObserver::handleJobEnd(), onert::exec::Execution::primary_subgraph(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
inputInfo()
virtual const ir::OperandInfo & onert::exec::IExecutor::inputInfo (uint32_t index) const pure virtual
Get input info at index.
Parameters
[in] index Index of input
Returns
Input operand info
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::execute(), and onert::exec::SingleModelExecutors::inputInfo().
inputLayout()
virtual ir::Layout onert::exec::IExecutor::inputLayout (uint32_t index) const pure virtual
Get input layout at index.
Parameters
[in] index Index of input
Returns
Input operand layout
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
inputSize()
virtual uint32_t onert::exec::IExecutor::inputSize () const pure virtual
Get input size.
Returns
Input size
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::MultiModelExecutors::execute(), and onert::exec::SingleModelExecutors::inputSize().
outputBuffer()
virtual const uint8_t * onert::exec::IExecutor::outputBuffer (uint32_t index) const pure virtual
Get output buffer at index.
Parameters
[in] index Index of output
Returns
Output buffer
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::outputBuffer().
outputInfo()
virtual const ir::OperandInfo & onert::exec::IExecutor::outputInfo (uint32_t index) const pure virtual
Get output info at index.
Parameters
[in] index Index of output
Returns
Output operand info
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::execute(), and onert::exec::SingleModelExecutors::outputInfo().
outputLayout()
virtual ir::Layout onert::exec::IExecutor::outputLayout (uint32_t index) const pure virtual
Get output layout at index.
Parameters
[in] index Index of output
Returns
Output operand layout
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
outputSize()
virtual uint32_t onert::exec::IExecutor::outputSize () const pure virtual
Get output size.
Returns
Output size
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::outputSize().
outputTensor()
virtual const backend::IPortableTensor * onert::exec::IExecutor::outputTensor (uint32_t index) const pure virtual
Get output tensor at index.
Parameters
[in] index Index of output
Returns
Output tensor
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::exec::SingleModelExecutors::outputTensor().
setIndexedRanks()
virtual void onert::exec::IExecutor::setIndexedRanks (std::shared_ptr< ir::OperationIndexMap< int64_t > >) pure virtual
Set an ordering on operations.
Parameters
[in] ranks The table encoding the ordering
Implemented in onert::exec::ExecutorBase, and onert::exec::train::TrainableExecutor.
Referenced by onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), and onert::compiler::train::TrainingCompiler::compile().
The documentation for this struct was generated from the following file:
runtime/onert/core/include/exec/IExecutor.h