ONE - On-device Neural Engine: onert::api::Session Struct Reference
onert::api::Session Struct Reference
#include <Session.h>
Public Member Functions
~Session ()
NNFW_STATUS load_model_from_path (const char *path)
NNFW_STATUS prepare ()
NNFW_STATUS run ()
NNFW_STATUS run_async ()
NNFW_STATUS await ()
NNFW_STATUS set_input (uint32_t index, NNFW_TYPE type, const void *buffer, size_t length)
NNFW_STATUS set_output (uint32_t index, NNFW_TYPE type, void *buffer, size_t length)
NNFW_STATUS input_size (uint32_t *number)
NNFW_STATUS output_size (uint32_t *number)
NNFW_STATUS set_input_layout (uint32_t index, NNFW_LAYOUT layout)
NNFW_STATUS set_output_layout (uint32_t index, NNFW_LAYOUT layout)
NNFW_STATUS set_input_type (uint32_t index, NNFW_TYPE type)
NNFW_STATUS set_output_type (uint32_t index, NNFW_TYPE type)
NNFW_STATUS set_input_tensorinfo (uint32_t index, const nnfw_tensorinfo *ti)
NNFW_STATUS input_tensorinfo (uint32_t index, nnfw_tensorinfo *ti)
NNFW_STATUS output_tensorinfo (uint32_t index, nnfw_tensorinfo *ti)
NNFW_STATUS set_available_backends (const char *backends)
NNFW_STATUS set_workspace (const char *dir)
NNFW_STATUS configure_signature (const char *signature)
NNFW_STATUS set_signature_run (const char *signature)
NNFW_STATUS set_config (const char *key, const char *value)
NNFW_STATUS get_config (const char *key, char *value, size_t value_size)
NNFW_STATUS load_circle_from_buffer (uint8_t *buffer, size_t size)
NNFW_STATUS get_output (uint32_t index, nnfw_tensorinfo *out_info, const void **out_buffer)
NNFW_STATUS register_custom_operation (const std::string &id, nnfw_custom_eval eval_func)
NNFW_STATUS input_tensorindex (const char *tensorname, uint32_t *index)
NNFW_STATUS output_tensorindex (const char *tensorname, uint32_t *index)
NNFW_STATUS run_with_auto_compilation (const char *target, NNFW_CODEGEN_PREF pref)
NNFW_STATUS set_odc_param_minmax_records_count (int minmax_records_count)
NNFW_STATUS delete_odc_minmax_file ()
NNFW_STATUS set_backends_per_operation (const char *backend_settings)
Set backends with string-encoded mapping from operation index to backend type (cpu, acl_cl)
NNFW_STATUS train_get_traininfo (nnfw_train_info *info)
NNFW_STATUS train_set_traininfo (const nnfw_train_info *info)
NNFW_STATUS train_prepare ()
NNFW_STATUS train_input_tensorinfo (uint32_t index, nnfw_tensorinfo *ti)
NNFW_STATUS train_expected_tensorinfo (uint32_t index, nnfw_tensorinfo *ti)
NNFW_STATUS train_set_input (uint32_t index, const void *input, const nnfw_tensorinfo *input_tensorinfo)
NNFW_STATUS train_set_expected (uint32_t index, const void *expected, const nnfw_tensorinfo *expected_tensorinfo)
NNFW_STATUS train_set_output (uint32_t index, NNFW_TYPE type, void *buffer, size_t length)
NNFW_STATUS train_run (bool update_weights)
NNFW_STATUS train_get_loss (uint32_t index, float *loss)
NNFW_STATUS train_export_circle (const char *path)
NNFW_STATUS train_export_circleplus (const char *path)
NNFW_STATUS train_import_checkpoint (const char *path)
NNFW_STATUS train_export_checkpoint (const char *path)
NNFW_STATUS set_quantization_type (NNFW_QUANTIZE_TYPE qtype)
NNFW_STATUS set_quantized_model_path (const char *path)
NNFW_STATUS quantize ()
NNFW_STATUS set_codegen_model_path (const char *path)
NNFW_STATUS codegen (const char *target, NNFW_CODEGEN_PREF pref)
NNFW_STATUS set_prepare_config (const NNFW_PREPARE_CONFIG key, const char *value)
NNFW_STATUS reset_prepare_config ()
NNFW_STATUS set_execute_config (const NNFW_RUN_CONFIG key, const char *value)
NNFW_STATUS reset_execute_config ()
Static Public Member Functions
static NNFW_STATUS create (Session **session)
Factory method. It creates and initialize Session.
static NNFW_STATUS deprecated (const char *msg)
Detailed Description
Definition at line 42 of file Session.h.
Constructor & Destructor Documentation
~Session()
onert::api::Session::~Session () default
Member Function Documentation
await()
NNFW_STATUS onert::api::Session::await ()
Definition at line 547 of file Session.cc.
{
  if (!isStateRunning())
  {
    std::cerr << "Error during Session::run_await : "
              << "run_await should be run after run_async" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  _execution->waitFinish();
  _state = State::FINISHED_RUN;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, and NNFW_STATUS_NO_ERROR.
codegen()
NNFW_STATUS onert::api::Session::codegen (const char * target, NNFW_CODEGEN_PREF pref)
Definition at line 2122 of file Session.cc.
{
  try
  {
    if (isStateInitialized() || isStateRunning())
    {
      std::cerr << "Error during Session::codegen : Invalid state" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    std::string target_str{target};
    if (target_str.empty() || target_str.size() < 5 ||
        target_str.substr(target_str.size() - 4) != "-gen")
    {
      std::cerr << "Error during Session::codegen : Invalid target" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    onert::odc::CodegenPreference codegen_pref;
    switch (pref)
    {
      case NNFW_CODEGEN_PREF_DEFAULT:
        codegen_pref = onert::odc::CodegenPreference::CODEGEN_PREF_DEFAULT;
        break;
      case NNFW_CODEGEN_PREF_PERFORMANCE_FIRST:
        codegen_pref = onert::odc::CodegenPreference::CODEGEN_PREF_PERFORMANCE_FIRST;
        break;
      case NNFW_CODEGEN_PREF_MEMORY_FIRST:
        codegen_pref = onert::odc::CodegenPreference::CODEGEN_PREF_MEMORY_FIRST;
        break;
      case NNFW_CODEGEN_PREF_COMPILE_TIME_FIRST:
        codegen_pref = onert::odc::CodegenPreference::CODEGEN_PREF_COMPILE_TIME_FIRST;
        break;
      default:
        std::cerr << "Error during Session::codegen : Invalid preference" << std::endl;
        return NNFW_STATUS_ERROR;
    }
    assert(_codegen_manager != nullptr);
    auto export_model_path = std::filesystem::path(_codegen_manager->exportModelPath());
    const auto model_type = target_str.substr(0, target_str.size() - 4);
    // If the export_model_path is not set, it generates a compiled model path
    // automatically.
    if (export_model_path.empty())
    {
      // The compiled model path is the same directory of the original model/package with
      // target backend extension.
      export_model_path = _model_path.replace_extension(model_type);
      _codegen_manager->exportModelPath(export_model_path.string());
    }
    _codegen_manager->codegen(_model_path, target, codegen_pref);
    // Replace model
    // TODO Support buffer replace, not file reload
    return loadModelFile(export_model_path, model_type);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::compile : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
}
References onert::odc::CODEGEN_PREF_COMPILE_TIME_FIRST, onert::odc::CODEGEN_PREF_DEFAULT, onert::odc::CODEGEN_PREF_MEMORY_FIRST, onert::odc::CODEGEN_PREF_PERFORMANCE_FIRST, NNFW_CODEGEN_PREF_COMPILE_TIME_FIRST, NNFW_CODEGEN_PREF_DEFAULT, NNFW_CODEGEN_PREF_MEMORY_FIRST, NNFW_CODEGEN_PREF_PERFORMANCE_FIRST, NNFW_STATUS_ERROR, and NNFW_STATUS_INVALID_STATE.
configure_signature()
NNFW_STATUS onert::api::Session::configure_signature (const char * signature)
Definition at line 1074 of file Session.cc.
{
  if (!signature)
    return NNFW_STATUS_UNEXPECTED_NULL;
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::configure_signature : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  for (const auto &[subg_idx, sig_str] : _signature_map)
  {
    if (sig_str == std::string(signature))
    {
      _selected_signature = subg_idx;
      return NNFW_STATUS_NO_ERROR;
    }
  }
  std::cerr << "Error during Session::configure_signature : cannot find signature \"" << signature
            << "\"" << std::endl;
  return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
create()
NNFW_STATUS onert::api::Session::create (Session ** session) static
Factory method. It creates and initialize Session.
Note
Use factory instead of constructor to get status
Definition at line 267 of file Session.cc.
{
  if (session == nullptr)
    return NNFW_STATUS_UNEXPECTED_NULL;
  try
  {
    auto new_session = std::unique_ptr<Session>(new Session());
    new_session->_kernel_registry = std::make_shared<onert::api::CustomKernelRegistry>();
    *session = new_session.release();
  }
  catch (const std::bad_alloc &e)
  {
    std::cerr << "Error during session creation" << std::endl;
    *session = nullptr; // Set nullptr on error to keep the old behavior
    return NNFW_STATUS_OUT_OF_MEMORY;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during session initialization : " << e.what() << std::endl;
    *session = nullptr; // Set nullptr on error to keep the old behavior
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_NO_ERROR, NNFW_STATUS_OUT_OF_MEMORY, and NNFW_STATUS_UNEXPECTED_NULL.
Referenced by nnfw_create_session().
delete_odc_minmax_file()
NNFW_STATUS onert::api::Session::delete_odc_minmax_file ()
Definition at line 2281 of file Session.cc.
{
  if (isStateRunning())
  {
    std::cerr << "invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (_quant_manager->deleteMinMaxFile())
    return NNFW_STATUS_NO_ERROR;
  else
    return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
deprecated()
NNFW_STATUS onert::api::Session::deprecated (const char * msg) static
Definition at line 1125 of file Session.cc.
{
  std::cerr << msg << std::endl;
  return NNFW_STATUS_DEPRECATED_API;
}
References NNFW_STATUS_DEPRECATED_API.
Referenced by nnfw_apply_tensorinfo(), nnfw_pop_pipeline_output(), nnfw_prepare_pipeline(), nnfw_push_pipeline_input(), and nnfw_set_op_backend().
get_config()
NNFW_STATUS onert::api::Session::get_config (const char * key, char * value, size_t value_size)
Definition at line 1235 of file Session.cc.
{
  if (!isStateModelLoaded())
    return NNFW_STATUS_INVALID_STATE;
  if (!key || !value)
    return NNFW_STATUS_UNEXPECTED_NULL;
  auto check_boundary = [](size_t dest_size, std::string &src) {
    if (dest_size < src.length() + 1 /* for '\0' */)
    {
      std::cerr << "buffer is small to copy config value." << std::endl;
      return false;
    }
    return true;
  };
  const std::string skey = key;
  if (skey == onert::util::config::BACKENDS)
  {
    if (_coptions->backend_list.size() == 0)
      return NNFW_STATUS_NO_ERROR; // no setting backend is not an error of get_config_str()
    auto str =
      nnfw::misc::join(_coptions->backend_list.begin(), _coptions->backend_list.end(), ";");
    if (!check_boundary(value_size, str))
      return NNFW_STATUS_ERROR;
    strncpy(value, str.c_str(), value_size);
  }
  else if (skey == onert::util::config::EXECUTOR)
  {
    if (!check_boundary(value_size, _coptions->executor))
      return NNFW_STATUS_ERROR;
    strncpy(value, _coptions->executor.c_str(), _coptions->executor.length());
  }
  else
  {
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References nnfw::misc::join(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
get_output()
NNFW_STATUS onert::api::Session::get_output (uint32_t index, nnfw_tensorinfo * out_info, const void ** out_buffer)
Definition at line 979 of file Session.cc.
{
  if (ti == nullptr)
  {
    std::cerr << "Error during Session::get_output : tensor info is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (out_buffer == nullptr)
  {
    std::cerr << "Error during Session::get_output : output buffer is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStateFinishedRun())
  {
    std::cerr << "Error during Session::get_output : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (index >= getOutputSize())
    {
      std::cerr << "Error during Session::get_output, index " << index
                << " is out of range. (output count: " << getOutputSize() << ")" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    if (!_coptions->internal_output_alloc)
    {
      std::cerr << "Error during Session::get_output: "
                << "internal output allocation is not enabled. "
                << "Call nnfw_set_prepare_config(session, "
                   "NNFW_PREPARE_CONFIG_ENABLE_INTERNAL_OUTPUT_ALLOC, \"true\") "
                << "before nnfw_prepare()." << std::endl;
      return NNFW_STATUS_ERROR;
    }
    auto io_index = onert::ir::IOIndex{index};
    const auto &info = _execution->outputInfo(io_index);
    const auto &shape = info.shape();
    const auto &dtype = info.typeInfo().type();
    fillTensorInfo(ti, shape, dtype);
    *out_buffer = _execution->outputBuffer(io_index);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::get_output : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References info, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
input_size()
NNFW_STATUS onert::api::Session::input_size (uint32_t * number)
Definition at line 616 of file Session.cc.
{
  if (isStateInitialized()) // Model is not loaded
    return NNFW_STATUS_INVALID_STATE;
  try
  {
    if (number == nullptr)
    {
      std::cerr << "Error during Session::input_size, number is null pointer." << std::endl;
      return NNFW_STATUS_UNEXPECTED_NULL;
    }
    *number = getInputSize();
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::input_size : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
input_tensorindex()
NNFW_STATUS onert::api::Session::input_tensorindex (const char * tensorname, uint32_t * index)
Definition at line 1351 of file Session.cc.
{
  return getTensorIndexImpl(*primary_subgraph(), tensorname, index, true);
}
input_tensorinfo()
NNFW_STATUS onert::api::Session::input_tensorinfo (uint32_t index, nnfw_tensorinfo * ti)
Definition at line 889 of file Session.cc.
{
  if (isStateInitialized())
    return NNFW_STATUS_INVALID_STATE;
  try
  {
    if (ti == nullptr)
    {
      std::cerr << "Error during Session::input_tensorinfo, tensorinfo is null pointer."
                << std::endl;
      return NNFW_STATUS_UNEXPECTED_NULL;
    }
    if (index >= getInputSize())
    {
      std::cerr << "Error during Session::input_tensorinfo, index is out of range." << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto input_index = onert::ir::IOIndex{index};
    if (isStateModelLoaded())
    {
      const auto &info = _selected_signature.valid() ? _nnpkg->inputInfo(_selected_signature, index)
                                                     : _nnpkg->inputInfo(input_index);
      fillTensorInfo(ti, info.shape(), info.typeInfo().type());
    }
    else
    {
      const auto &info = _execution->inputInfo(input_index);
      fillTensorInfo(ti, info.shape(), info.typeInfo().type());
    }
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::input_tensorinfo : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References info, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
load_circle_from_buffer()
NNFW_STATUS onert::api::Session::load_circle_from_buffer (uint8_t * buffer, size_t size)
Definition at line 294 of file Session.cc.
{
  if (!isStateInitialized())
    return NNFW_STATUS_INVALID_STATE;
  if (!buffer)
    return NNFW_STATUS_UNEXPECTED_NULL;
  if (size == 0)
    return NNFW_STATUS_ERROR;
  try
  {
    auto model = onert::loader::loadCircleModel(buffer, size);
    // TODO: Update _model_path if necessary
    _nnpkg = std::make_unique<onert::ir::NNPkg>(std::move(model));
    _train_info = loadTrainingInfo(_nnpkg->primary_model());
    _state = State::MODEL_LOADED;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during model loading : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::loader::loadCircleModel(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and size.
load_model_from_path()
NNFW_STATUS onert::api::Session::load_model_from_path (const char * path)
Definition at line 321 of file Session.cc.
{
  if (!isStateInitialized())
    return NNFW_STATUS_INVALID_STATE;
  if (!path)
  {
    std::cerr << "Path is null." << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!null_terminating(path, MAX_PATH_LENGTH))
  {
    std::cerr << "Path is too long" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    std::filesystem::path filename{path};
    if (!std::filesystem::is_directory(filename))
    {
      std::string model_type = inferModelType(filename);
      if (model_type.empty())
      {
        std::cerr << "Error: Cannot determine model type for '" << filename << "'."
                  << "Please use a file with valid extension." << std::endl;
        return NNFW_STATUS_ERROR;
      }
      else
        return loadModelFile(filename, model_type);
    }
    const auto &package_dir = filename;
    // TODO : add support for zipped package file load
    if (!std::filesystem::is_directory(package_dir))
    {
      std::cerr << "invalid path: " << package_dir << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto manifest_file_name = package_dir / "metadata/MANIFEST";
    std::ifstream mfs(manifest_file_name);
    // extract the filename of the first(index 0) model
    // e.g. In MANIFEST file, { "models" : [ "firstmodel.tflite", "2nd.tflite" ] }
    Json::Value root;
    mfs >> root;
    const Json::Value &models = root["models"];
    const Json::Value &model_types = root["model-types"];
    const Json::Value &configs = root["configs"];
    if (!configs.empty() && !configs[0].empty())
    {
      const auto filepath = package_dir / "metadata" / configs[0].asString();
      onert::util::CfgKeyValues keyValues;
      if (loadConfigure(filepath.string(), keyValues))
      {
        onert::util::setConfigKeyValues(keyValues);
      }
    }
    _nnpkg = std::make_unique<onert::ir::NNPkg>();
    auto num_models = models.size();
    if (num_models == 0 || (num_models - 1) > onert::ir::ModelIndex::max())
    {
      std::cerr << "Invalid model size - " << std::to_string(num_models) << std::endl;
      return NNFW_STATUS_ERROR;
    }
    // Not support backend mapping to operator index for multiple models yet
    // TODO Support this
    if (num_models > 1 && _coptions->manual_scheduler_options.index_to_backend.size() != 0)
    {
      std::cerr << "Cannot set backend to operator index for multiple models" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    for (uint16_t i = 0; i < num_models; ++i)
    {
      const auto model_file_name = std::filesystem::path(models[i].asString());
      const auto model_file_path = package_dir / model_file_name;
      std::string model_type;
      // Use model-types if available and not empty, otherwise infer from file extension
      if (!model_types.empty() && i < model_types.size())
        model_type = model_types[i].asString();
      else
        model_type = inferModelType(model_file_name);
      if (model_type.empty())
      {
        std::cerr << "Error: Cannot determine model type for '" << models[i].asString() << "'."
                  << "Please specify model-types in MANIFEST or use a file with valid extension."
                  << std::endl;
        return NNFW_STATUS_ERROR;
      }
      auto model = loadModel(model_file_path.string(), model_type);
      if (model == nullptr)
        return NNFW_STATUS_ERROR;
      _model_path = model_file_path; // TODO Support multiple models
      model->bindKernelBuilder(_kernel_registry->getBuilder());
      _nnpkg->push(onert::ir::ModelIndex{i}, std::move(model));
    }
    _train_info = loadTrainingInfo(_nnpkg->primary_model());
    auto toIODesc = [](std::string str) {
      auto indices = nnfw::misc::split(str, ':');
      if (indices.size() != 3)
      {
        std::cerr << "IODesc should be 3-tuple." << std::endl;
        return onert::ir::IODesc{};
      }
      auto model_idx = static_cast<uint32_t>(std::stoi(indices.at(0)));
      auto subgraph_idx = static_cast<uint32_t>(std::stoi(indices.at(1)));
      auto operand_idx = static_cast<uint32_t>(std::stoi(indices.at(2)));
      return onert::ir::IODesc{model_idx, subgraph_idx, operand_idx};
    };
    // read pkg-inputs and pkg-outputs
    const Json::Value &pkg_inputs = root["pkg-inputs"];
    for (uint32_t i = 0; i < pkg_inputs.size(); ++i)
      _nnpkg->addInput(toIODesc(pkg_inputs[i].asString()));
    const Json::Value &pkg_outputs = root["pkg-outputs"];
    for (uint32_t i = 0; i < pkg_outputs.size(); ++i)
      _nnpkg->addOutput(toIODesc(pkg_outputs[i].asString()));
    // read model-connect
    const Json::Value &fromtos = root["model-connect"];
    for (uint32_t i = 0; i < fromtos.size(); ++i)
    {
      const Json::Value &tos = fromtos[i]["to"];
      for (uint32_t j = 0; j < tos.size(); ++j)
        _nnpkg->addEdge(toIODesc(fromtos[i]["from"].asString()), toIODesc(tos[j].asString()));
    }
    _nnpkg->verify();
    _state = State::MODEL_LOADED;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during model loading : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::util::Index< uint16_t, ModelIndexTag >::max(), MAX_PATH_LENGTH, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, onert::util::setConfigKeyValues(), and nnfw::misc::split().
output_size()
NNFW_STATUS onert::api::Session::output_size (uint32_t * number)
Definition at line 638 of file Session.cc.
{
  if (isStateInitialized()) // Model is not loaded
    return NNFW_STATUS_INVALID_STATE;
  try
  {
    if (number == nullptr)
    {
      std::cerr << "Error during Session::output_size, number is null pointer." << std::endl;
      return NNFW_STATUS_UNEXPECTED_NULL;
    }
    *number = getOutputSize();
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::output_size" << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
output_tensorindex()
NNFW_STATUS onert::api::Session::output_tensorindex (const char * tensorname, uint32_t * index)
Definition at line 1356 of file Session.cc.
{
  return getTensorIndexImpl(*primary_subgraph(), tensorname, index, false);
}
output_tensorinfo()
NNFW_STATUS onert::api::Session::output_tensorinfo (uint32_t index, nnfw_tensorinfo * ti)
Definition at line 930 of file Session.cc.
{
  if (isStateInitialized())
    return NNFW_STATUS_INVALID_STATE;
  if (ti == nullptr)
  {
    std::cerr << "Error during Session::output_tensorinfo, tensorinfo is null pointer."
              << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  try
  {
    if (index >= getOutputSize())
    {
      std::cerr << "Error during Session::output_tensorinfo, index is out of range." << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto output_index = onert::ir::IOIndex{index};
    if (isStateModelLoaded())
    {
      const auto &info = _selected_signature.valid()
                           ? _nnpkg->outputInfo(_selected_signature, index)
                           : _nnpkg->outputInfo(output_index);
      fillTensorInfo(ti, info.shape(), info.typeInfo().type());
    }
    else
    {
      auto info = _execution->outputInfo(output_index);
      fillTensorInfo(ti, info.shape(), info.typeInfo().type());
    }
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::output_tensorinfo : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References info, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
prepare()
NNFW_STATUS onert::api::Session::prepare ()
Definition at line 468 of file Session.cc.
{
  // NOTE. If users want to run prepare() more than one time, this could be removed.
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during model prepare : ";
    if (isStateInitialized())
    {
      std::cerr << "prepare should be run once";
    }
    else
    {
      std::cerr << "invalid state";
    }
    std::cerr << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    auto compiler =
      onert::compiler::CompilerFactory::get().create(std::move(_nnpkg), _coptions.get());
    _compiler_artifact = compiler->compile();
    _execution = std::make_unique<onert::exec::Execution>(_compiler_artifact->_executors);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during model prepare : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  _state = State::PREPARED;
  return NNFW_STATUS_NO_ERROR;
}
References onert::compiler::CompilerFactory::create(), onert::compiler::CompilerFactory::get(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
quantize()
NNFW_STATUS onert::api::Session::quantize ()
Definition at line 2075 of file Session.cc.
{
  try
  {
    if (isStateInitialized() || isStateRunning())
    {
      std::cerr << "invalid state" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    auto result = _quant_manager->quantize(_model_path.string());
    if (!result)
      return NNFW_STATUS_INVALID_STATE;
    // Replace model
    // TODO Support buffer replace, not file reload
    return loadModelFile(_quant_manager->exportModelPath(), "circle");
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::quantize : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
}
References NNFW_STATUS_ERROR, and NNFW_STATUS_INVALID_STATE.
register_custom_operation()
NNFW_STATUS onert::api::Session::register_custom_operation (const std::string & id, nnfw_custom_eval eval_func)
Definition at line 973 of file Session.cc.
{
  _kernel_registry->registerKernel(id, eval_func);
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_NO_ERROR.
reset_execute_config()
NNFW_STATUS onert::api::Session::reset_execute_config ()
Definition at line 2252 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::set_execution_config : Invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  _execution->executionOptions().dump_minmax = false;
  _execution->executionOptions().trace = false;
  _execution->executionOptions().profile = false;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
reset_prepare_config()
NNFW_STATUS onert::api::Session::reset_prepare_config ()
Definition at line 2209 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::reset_prepare_config : Invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  _coptions->he_profiling_mode = false;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
run()
NNFW_STATUS onert::api::Session::run ()
Definition at line 503 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::run : "
              << "run should be run after prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    _execution->execute();
  }
  catch (const onert::InsufficientBufferSizeException &e)
  {
    // Currently insufficient buffer always means output buffer.
    std::cerr << "Error during Session::run : " << e.what() << std::endl;
    return NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::run : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  _state = State::FINISHED_RUN;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and onert::Exception::what().
run_async()
NNFW_STATUS onert::api::Session::run_async ()
Definition at line 532 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::run_async : "
              << "run_async should be run after prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  _execution->startExecute();
  _state = State::RUNNING;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
run_with_auto_compilation()
NNFW_STATUS onert::api::Session::run_with_auto_compilation (const char * target, NNFW_CODEGEN_PREF pref)
Definition at line 2296 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::run_with_auto_compilation : "
              << "run should be after preparation" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  // Check quantization and code-generation parameters
  std::string target_str{target};
  if (_quant_manager->exportModelPath().empty() || _codegen_manager->exportModelPath().empty() ||
      target_str.empty() || target_str.substr(target_str.size() - 4) != "-gen")
  {
    std::cerr << "Error during Session::run_with_auto_compilation : "
              << "quantization and code generation parameters should be set" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  // Odc: auto compilation with hidden switching mechanizm
  // Check is model already quantized or compiled
  std::ifstream file_quantized_model(_quant_manager->exportModelPath());
  std::ifstream file_compiled_model(_codegen_manager->exportModelPath());
  if (!file_quantized_model.good() && !file_compiled_model.good())
  {
    // Run float model and try to quantize it
    {
      // Save execution options
      auto saved_options = _execution->executionOptions();
      // turn on minmax recording
      _execution->executionOptions().dump_minmax = true;
      try
      {
        _execution->execute();
      }
      catch (const onert::InsufficientBufferSizeException &e)
      {
        // Currently insufficient buffer always means output buffer.
        std::cerr << "Error during Session::run_with_auto_compilation : " << e.what() << std::endl;
        return NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE;
      }
      catch (const std::exception &e)
      {
        std::cerr << "Error during Session::run_with_auto_compilation : " << e.what() << std::endl;
        return NNFW_STATUS_ERROR;
      }
      _state = State::FINISHED_RUN;
      // restore min_max option to user defined state
      _execution->executionOptions().dump_minmax = saved_options.dump_minmax;
      // if enough statistics are collected, then run the quantization
      if (_quant_manager->readyForQuantize())
      {
        try
        {
          if (isStateInitialized() || isStateRunning())
          {
            std::cerr << "invalid state" << std::endl;
            return NNFW_STATUS_INVALID_STATE;
          }
          auto result = _quant_manager->quantize(_model_path);
          if (!result)
            return NNFW_STATUS_INVALID_STATE;
          // remove minmax file
          result = _quant_manager->deleteMinMaxFile();
          if (!result)
            return NNFW_STATUS_INVALID_STATE;
        }
        catch (const std::exception &e)
        {
          std::cerr << "Error during Session::run_with_auto_compilation in quantize operation: "
                    << e.what() << std::endl;
          return NNFW_STATUS_ERROR;
        }
      }
    }
  }
  else
  {
    // run compiled or quantized model
    NNFW_STATUS status;
    // turn off minmax recording
    _execution->executionOptions().dump_minmax = false;
    // save initial buffers if quantized model or compiled model is not loaded
    if (_autoCompilationState == Session::AutoCompilationState::INITIAL_STATE)
    {
      auto dotidx = _codegen_manager->exportModelPath().rfind('.');
      if (dotidx == std::string::npos)
      {
        std::cerr << "Error during Session::run_with_auto_compilation : Invalid compiled "
                     "model path. Please use a "
                     "path that includes the extension."
                  << std::endl;
        return NNFW_STATUS_ERROR;
      }
      std::string compiled_model_type =
        _codegen_manager->exportModelPath().substr(dotidx + 1); // + 1 to exclude dot
      dotidx = _quant_manager->exportModelPath().rfind('.');
      if (dotidx == std::string::npos)
      {
        std::cerr << "Error during Session::run_with_auto_compilation : Invalid quantized "
                     "model path. Please use a "
                     "path that includes the extension."
                  << std::endl;
        return NNFW_STATUS_ERROR;
      }
      std::string quantized_model_type =
        _quant_manager->exportModelPath().substr(dotidx + 1); // + 1 to exclude dot
      // Save initial (float) input and output buffers
      auto input_size = _execution->inputSize();
      auto output_size = _execution->outputSize();
      std::vector<const void *> _input_buffers;
      std::vector<void *> _output_buffers;
      using namespace onert::ir;
      // Copy execution context for backup: I/O buffer, shape, and execution options
      const onert::exec::ExecutionContext ctx_backup = _execution->context();
      // Set compile option to use float type
      for (auto input_index = IOIndex{0}; input_index < IOIndex{input_size}; input_index++)
        _coptions->input_type.insert_or_assign(IODesc{ModelIndex{0}, SubgraphIndex{0}, input_index},
                                               TypeInfo(DataType::FLOAT32));
      // Save Outputs buffers
      for (auto output_index = IOIndex{0}; output_index < IOIndex{output_size}; output_index++)
        _coptions->output_type.insert_or_assign(
          IODesc{ModelIndex{0}, SubgraphIndex{0}, output_index}, TypeInfo(DataType::FLOAT32));
      // if there is compiled model - try to load it
      if (file_compiled_model.good())
      {
        // load compiled model
        status = loadModelFile(_codegen_manager->exportModelPath(), compiled_model_type);
        if (status == NNFW_STATUS_NO_ERROR)
        {
          _autoCompilationState = Session::AutoCompilationState::COMPILED_MODEL_LOADED;
        }
      }
      else // there is no compiled model - try to compile and load it
      {
        // avoiding code duplication use existing "codegen" function. Set up _model_path for the
        // codegen function.
        // TODO: change it if codegen function will be generalized
        _model_path = _quant_manager->exportModelPath();
        // try to compile and load compiled model
        status = codegen(target, pref);
        if (status == NNFW_STATUS_NO_ERROR)
        {
          _autoCompilationState = Session::AutoCompilationState::COMPILED_MODEL_LOADED;
          // TODO delete quantized model
        }
      }
      // loading compiled model is fail - try to load quantized model
      if (_autoCompilationState != Session::AutoCompilationState::COMPILED_MODEL_LOADED)
      {
        // load quantized model
        status = loadModelFile(_quant_manager->exportModelPath(), quantized_model_type);
        if (status != NNFW_STATUS_NO_ERROR)
          return status;
        else
          _autoCompilationState = Session::AutoCompilationState::QUANTIZED_MODEL_LOADED;
      }
      status = prepare();
      if (status != NNFW_STATUS_NO_ERROR)
        return status;
      // Restore execution context: I/O buffer, shape, and execution options
      _execution->restoreContext(ctx_backup);
    }
    // Run quantized model
    if (!isStatePreparedOrFinishedRun())
    {
      std::cerr << "Error during Session::run_with_auto_compilation : "
                << "run should be run after prepare" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    try
    {
      _execution->execute();
    }
    catch (const onert::InsufficientBufferSizeException &e)
    {
      // Currently insufficient buffer always means output buffer.
      std::cerr << "Error during Session::run_with_auto_compilation : " << e.what() << std::endl;
      return NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE;
    }
    catch (const std::exception &e)
    {
      std::cerr << "Error during Session::run_with_auto_compilation : " << e.what() << std::endl;
      return NNFW_STATUS_ERROR;
    }
    _state = State::FINISHED_RUN;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE, NNFW_STATUS_INVALID_STATE, and onert::Exception::what().
set_available_backends()
NNFW_STATUS onert::api::Session::set_available_backends (const char * backends)
Definition at line 1035 of file Session.cc.
{
  if (!isStateModelLoaded())
    return NNFW_STATUS_INVALID_STATE;
  try
  {
    if (!backends)
      return NNFW_STATUS_UNEXPECTED_NULL;
    if (null_terminating(backends, MAX_BACKEND_NAME_LENGTH) == false)
      return NNFW_STATUS_ERROR;
    using namespace onert::util;
    _coptions->backend_list = nnfw::misc::split(std::string{backends}, ';');
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_available_backends : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References MAX_BACKEND_NAME_LENGTH, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and nnfw::misc::split().
set_backends_per_operation()
NNFW_STATUS onert::api::Session::set_backends_per_operation (const char * backend_settings)
Set backends with string-encoded mapping from operation index to backend type (cpu, acl_cl)
Definition at line 1361 of file Session.cc.
{
  if (backend_settings == NULL)
    return NNFW_STATUS_ERROR;
  if (!isStateModelLoaded())
    return NNFW_STATUS_INVALID_STATE;
  // Not supported multiple model
  // TODO Support this
  if (_nnpkg->model_count() > 1)
  {
    std::cerr << "Not supported multiple model" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    // Backend for all
    auto &ms_options = _coptions->manual_scheduler_options;
    ms_options.setBackendMap(std::string{backend_settings});
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_backends_per_operation" << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_codegen_model_path()
NNFW_STATUS onert::api::Session::set_codegen_model_path (const char * path)
Definition at line 2100 of file Session.cc.
{
  try
  {
    if (isStateInitialized() || isStateRunning())
    {
      std::cerr << "invalid state" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    assert(_codegen_manager != nullptr);
    _codegen_manager->exportModelPath(std::string(path));
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_codegen_model_path : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_config()
NNFW_STATUS onert::api::Session::set_config (const char * key, const char * value)
Definition at line 1131 of file Session.cc.
{
  if (!isStateModelLoaded())
    return NNFW_STATUS_INVALID_STATE;
  if (!key || !value)
    return NNFW_STATUS_UNEXPECTED_NULL;
  using namespace onert::util;
  const std::string skey = key;
  if (skey == config::GRAPH_DOT_DUMP)
  {
    _coptions->graph_dump_level = toInt(value);
  }
  else if (skey == config::EXECUTOR)
  {
    _coptions->executor = value;
  }
  else if (skey == config::USE_SCHEDULER)
  {
    _coptions->he_scheduler = toBool(value);
  }
  else if (skey == config::PROFILING_MODE)
  {
    _coptions->he_profiling_mode = toBool(value);
  }
  else if (skey == config::ENABLE_LOG || skey == config::NUM_THREADS)
  {
    onert::util::CfgKeyValues keyValues;
    keyValues[skey] = std::string(value);
    onert::util::setConfigKeyValues(keyValues);
    if (skey == config::ENABLE_LOG)
    {
      UPDATE_VERBOSE_CONFIG();
    }
  }
  else
  {
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, onert::util::setConfigKeyValues(), and UPDATE_VERBOSE_CONFIG.
set_execute_config()
NNFW_STATUS onert::api::Session::set_execute_config (const NNFW_RUN_CONFIG key, const char * value)
Definition at line 2222 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::set_execution_config : Invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  switch (key)
  {
    case NNFW_RUN_CONFIG_DUMP_MINMAX:
      if (_coptions->workspace_dir.empty())
        return NNFW_STATUS_ERROR;
      _execution->executionOptions().dump_minmax = true;
      break;
    case NNFW_RUN_CONFIG_TRACE:
      if (_coptions->workspace_dir.empty())
        return NNFW_STATUS_ERROR;
      _execution->executionOptions().trace = true;
      break;
    case NNFW_RUN_CONFIG_PROFILE:
      _execution->executionOptions().profile = true;
      break;
    default:
      return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_RUN_CONFIG_DUMP_MINMAX, NNFW_RUN_CONFIG_PROFILE, NNFW_RUN_CONFIG_TRACE, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_input()
NNFW_STATUS onert::api::Session::set_input (uint32_t index, NNFW_TYPE type, const void * buffer, size_t length)
Definition at line 562 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::set_input : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (!buffer && length != 0)
  {
    std::cerr << "Error during Session::set_input : given buffer is NULL but the length is not 0"
              << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    _execution->setInput(onert::ir::IOIndex(index), buffer, length);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_input : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_input_layout()
NNFW_STATUS onert::api::Session::set_input_layout (uint32_t index, NNFW_LAYOUT layout)
Definition at line 660 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::set_input_layout : "
              << "run should be run before prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (layout != NNFW_LAYOUT_NONE && layout != NNFW_LAYOUT_CHANNELS_FIRST &&
        layout != NNFW_LAYOUT_CHANNELS_LAST)
    {
      std::cerr << "Error during Session::set_input_layout, not supported layout" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    if (_selected_signature.valid())
    {
      // TODO Support this
      std::cerr << "Error during Session::set_input_layout : "
                << "set_input_layout after signature selection is not supported yet" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto io_index = onert::ir::IOIndex{index};
    // Signature is supported on single model only
    assert(!_selected_signature.valid() || _nnpkg->model_count() != 1);
    const auto io_desc =
      _selected_signature.valid()
        ? onert::ir::IODesc{onert::ir::ModelIndex{0}, _selected_signature, io_index}
        : _nnpkg->input(io_index);
    // Insert if not exists, otherwise update the value
    _coptions->input_layout[io_desc] = convertLayout(layout);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_input_layout : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_LAYOUT_CHANNELS_FIRST, NNFW_LAYOUT_CHANNELS_LAST, NNFW_LAYOUT_NONE, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_input_tensorinfo()
NNFW_STATUS onert::api::Session::set_input_tensorinfo (uint32_t index, const nnfw_tensorinfo * ti)
Definition at line 839 of file Session.cc.
{
  // sanity check
  {
    if (isStateInitialized())
    {
      std::cerr << "Error during set_input_tensorinfo : should be run after load_model"
                << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    if (ti == nullptr)
    {
      std::cerr << "Error during Session::set_input_tensorinfo : tensorinfo is null" << std::endl;
      return NNFW_STATUS_UNEXPECTED_NULL;
    }
    if (ti->rank < 0 || ti->rank > NNFW_MAX_RANK)
    {
      std::cerr << "unsupported rank: " << ti->rank << std::endl;
      return NNFW_STATUS_ERROR;
    }
    for (int32_t i = 0; i < ti->rank; ++i)
    {
      if (ti->dims[i] <= 0)
      {
        std::cerr << "dim must be positive integer but was " << ti->dims[i] << std::endl;
        return NNFW_STATUS_ERROR;
      }
    }
  }
  onert::ir::Shape new_shape(ti->rank);
  for (int32_t i = 0; i < ti->rank; i++)
    new_shape.dim(i) = ti->dims[i];
  const auto input_index = onert::ir::IOIndex(index);
  if (!isStatePreparedOrFinishedRun())
  {
    // In this case, if we apply input shape, it will propagate after compilation and excution
    _selected_signature.valid() ? _nnpkg->changeInputShape(_selected_signature, index, new_shape)
                                : _nnpkg->changeInputShape(input_index, new_shape);
  }
  else // when called after Session::prepare()
    _execution->changeInputShape(input_index, new_shape);
  return NNFW_STATUS_NO_ERROR;
}
References nnfw_tensorinfo::dims, NNFW_MAX_RANK, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and nnfw_tensorinfo::rank.
set_input_type()
NNFW_STATUS onert::api::Session::set_input_type (uint32_t index, NNFW_TYPE type)
Definition at line 749 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::set_input_type : "
              << "set_input_type should be called before prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (type != NNFW_TYPE_TENSOR_FLOAT32)
    {
      std::cerr << "Error during Session::set_input_type, not supported type" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    if (_selected_signature.valid())
    {
      // TODO Support this
      std::cerr << "Error during Session::set_input_type : "
                << "set_input_type after signature selection is not supported yet" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto io_index = onert::ir::IOIndex{index};
    // Signature is supported on single model only
    assert(!_selected_signature.valid() || _nnpkg->model_count() != 1);
    const auto io_desc =
      _selected_signature.valid()
        ? onert::ir::IODesc{onert::ir::ModelIndex{0}, _selected_signature, io_index}
        : _nnpkg->input(io_index);
    // Insert if not exists, otherwise update the value
    _coptions->input_type.insert_or_assign(io_desc,
                                           onert::ir::TypeInfo(onert::ir::DataType::FLOAT32));
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_input_type : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_TYPE_TENSOR_FLOAT32.
set_odc_param_minmax_records_count()
NNFW_STATUS onert::api::Session::set_odc_param_minmax_records_count (int minmax_records_count)
Definition at line 2267 of file Session.cc.
{
  if (isStateInitialized() || isStateRunning())
  {
    std::cerr << "invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (_quant_manager->setMinMaxRecordsThreshold(minmax_records_count))
    return NNFW_STATUS_NO_ERROR;
  else
    return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_output()
NNFW_STATUS onert::api::Session::set_output (uint32_t index, NNFW_TYPE type, void * buffer, size_t length)
Definition at line 589 of file Session.cc.
{
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::set_output : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (!buffer && length != 0)
  {
    std::cerr << "Error during Session::set_output : given buffer is NULL but the length is not 0"
              << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    _execution->setOutput(onert::ir::IOIndex(index), buffer, length);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_output : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_output_layout()
NNFW_STATUS onert::api::Session::set_output_layout (uint32_t index, NNFW_LAYOUT layout)
Definition at line 704 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::set_output_layout : "
              << "run should be run before prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (layout != NNFW_LAYOUT_NONE && layout != NNFW_LAYOUT_CHANNELS_FIRST &&
        layout != NNFW_LAYOUT_CHANNELS_LAST)
    {
      std::cerr << "Error during Session::set_output_layout, not supported layout" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    if (_selected_signature.valid())
    {
      // TODO Support this
      std::cerr << "Error during Session::set_output_layout : "
                << "set_output_layout after signature selection is not supported yet" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto io_index = onert::ir::IOIndex{index};
    // Signature is supported on single model only
    assert(!_selected_signature.valid() || _nnpkg->model_count() != 1);
    const auto io_desc =
      _selected_signature.valid()
        ? onert::ir::IODesc{onert::ir::ModelIndex{0}, _selected_signature, io_index}
        : _nnpkg->output(io_index);
    // Insert if not exists, otherwise update the value
    _coptions->output_layout[io_desc] = convertLayout(layout);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_output_layout : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_LAYOUT_CHANNELS_FIRST, NNFW_LAYOUT_CHANNELS_LAST, NNFW_LAYOUT_NONE, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_output_type()
NNFW_STATUS onert::api::Session::set_output_type (uint32_t index, NNFW_TYPE type)
Definition at line 794 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::set_output_type : "
              << "set_output_type should be called before prepare" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (type != NNFW_TYPE_TENSOR_FLOAT32)
    {
      std::cerr << "Error during Session::set_output_type, not supported type" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    if (_selected_signature.valid())
    {
      // TODO Support this
      std::cerr << "Error during Session::set_output_type : "
                << "set_output_type after signature selection is not supported yet" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const auto io_index = onert::ir::IOIndex{index};
    // Signature is supported on single model only
    assert(!_selected_signature.valid() || _nnpkg->model_count() != 1);
    const auto io_desc =
      _selected_signature.valid()
        ? onert::ir::IODesc{onert::ir::ModelIndex{0}, _selected_signature, io_index}
        : _nnpkg->output(io_index);
    // Insert if not exists, otherwise update the value
    _coptions->output_type.insert_or_assign(io_desc,
                                            onert::ir::TypeInfo(onert::ir::DataType::FLOAT32));
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_output_type : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_TYPE_TENSOR_FLOAT32.
set_prepare_config()
NNFW_STATUS onert::api::Session::set_prepare_config (const NNFW_PREPARE_CONFIG key, const char * value)
Definition at line 2186 of file Session.cc.
{
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during Session::set_prepare_config : Invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  switch (key)
  {
    case NNFW_PREPARE_CONFIG_PROFILE:
      _coptions->he_profiling_mode = true;
      break;
    case NNFW_ENABLE_INTERNAL_OUTPUT_ALLOC:
      _coptions->internal_output_alloc = true;
      break;
    default:
      return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_ENABLE_INTERNAL_OUTPUT_ALLOC, NNFW_PREPARE_CONFIG_PROFILE, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_quantization_type()
NNFW_STATUS onert::api::Session::set_quantization_type (NNFW_QUANTIZE_TYPE qtype)
Definition at line 2014 of file Session.cc.
{
  using onert::odc::QuantizeType;
  try
  {
    if (isStateInitialized() || isStateRunning())
    {
      std::cerr << "invalid state" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    QuantizeType odc_qtype = onert::odc::ODC_QTYPE_NOT_SET;
    switch (qtype)
    {
      case NNFW_QUANTIZE_TYPE_U8_ASYM:
        odc_qtype = onert::odc::ODC_QTYPE_U8_ASYM;
        break;
      case NNFW_QUANTIZE_TYPE_I16_SYM:
        odc_qtype = onert::odc::ODC_QTYPE_I16_SYM;
        break;
      case NNFW_QUANTIZE_TYPE_WO_I8_SYM:
        odc_qtype = onert::odc::ODC_QTYPE_WO_I8_SYM;
        break;
      case NNFW_QUANTIZE_TYPE_WO_I16_SYM:
        odc_qtype = onert::odc::ODC_QTYPE_WO_I16_SYM;
        break;
      default:
        return NNFW_STATUS_INVALID_STATE;
    }
    _quant_manager->quantizeType(odc_qtype);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_quantization_type : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_QUANTIZE_TYPE_I16_SYM, NNFW_QUANTIZE_TYPE_U8_ASYM, NNFW_QUANTIZE_TYPE_WO_I16_SYM, NNFW_QUANTIZE_TYPE_WO_I8_SYM, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, onert::odc::ODC_QTYPE_I16_SYM, onert::odc::ODC_QTYPE_NOT_SET, onert::odc::ODC_QTYPE_U8_ASYM, onert::odc::ODC_QTYPE_WO_I16_SYM, and onert::odc::ODC_QTYPE_WO_I8_SYM.
set_quantized_model_path()
NNFW_STATUS onert::api::Session::set_quantized_model_path (const char * path)
Definition at line 2054 of file Session.cc.
{
  try
  {
    if (isStateInitialized() || isStateRunning())
    {
      std::cerr << "invalid state" << std::endl;
      return NNFW_STATUS_INVALID_STATE;
    }
    _quant_manager->exportModelPath(std::string(path));
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::set_quantized_model_path : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
set_signature_run()
NNFW_STATUS onert::api::Session::set_signature_run (const char * signature)
Definition at line 1100 of file Session.cc.
{
  if (!signature)
    return NNFW_STATUS_UNEXPECTED_NULL;
  if (!isStatePreparedOrFinishedRun())
  {
    std::cerr << "Error during Session::set_signature_run : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  for (const auto &[subg_idx, sig_str] : _signature_map)
  {
    if (sig_str == std::string(signature))
    {
      _execution =
        std::make_unique<onert::exec::Execution>(_compiler_artifact->_executors, subg_idx);
      return NNFW_STATUS_NO_ERROR;
    }
  }
  std::cerr << "Error during Session::set_signature_run : cannot find signature" << std::endl;
  return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
set_workspace()
NNFW_STATUS onert::api::Session::set_workspace (const char * dir)
Definition at line 1059 of file Session.cc.
{
  // TODO Check dir read & write permission
  if (!dir)
    return NNFW_STATUS_UNEXPECTED_NULL;
  if (!isStateInitialized())
    return NNFW_STATUS_INVALID_STATE;
  _coptions->workspace_dir = std::string(dir);
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
train_expected_tensorinfo()
NNFW_STATUS onert::api::Session::train_expected_tensorinfo (uint32_t index, nnfw_tensorinfo * ti)
Definition at line 1668 of file Session.cc.
{
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_expected_tensorinfo : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  // Check index is valid: [0, getExpectedSize())
  // NYI
  (void)index;
  (void)ti;
  return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, and NNFW_STATUS_INVALID_STATE.
train_export_checkpoint()
NNFW_STATUS onert::api::Session::train_export_checkpoint (const char * path)
Definition at line 1957 of file Session.cc.
{
  if (path == nullptr)
  {
    std::cerr << "Error during Session::train_export_checkpoint : path is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  // Check training mode is enabled
  if (!isStateFinishedTraining())
  {
    std::cerr << "Error during Session::train_export_checkpoint : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    onert::exporter::train::exportCheckpoint(path, _train_info, _execution);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_export_checkpoint : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::exporter::train::exportCheckpoint(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
train_export_circle()
NNFW_STATUS onert::api::Session::train_export_circle (const char * path)
Definition at line 1872 of file Session.cc.
{
  if (path == nullptr)
  {
    std::cerr << "Error during Session::train_export_circle : path is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  // Check training mode is enabled
  if (!isStateFinishedTraining())
  {
    std::cerr << "Error during Session::train_export_circle : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    onert::exporter::CircleExporter exporter(_model_path.string(), std::string{path});
    exporter.updateWeight(_execution);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_export_circle : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and onert::exporter::CircleExporter::updateWeight().
train_export_circleplus()
NNFW_STATUS onert::api::Session::train_export_circleplus (const char * path)
Definition at line 1901 of file Session.cc.
{
  if (path == nullptr)
  {
    std::cerr << "Error during Session::train_export_circleplus : path is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_export_circleplus : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    onert::exporter::CircleExporter exporter(_model_path.string(), std::string{path});
    exporter.updateWeight(_execution);
    exporter.updateMetadata(_train_info);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_export_circleplus : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, onert::exporter::CircleExporter::updateMetadata(), and onert::exporter::CircleExporter::updateWeight().
train_get_loss()
NNFW_STATUS onert::api::Session::train_get_loss (uint32_t index, float * loss)
Definition at line 1838 of file Session.cc.
{
  if (loss == nullptr)
  {
    std::cerr << "Error during Session::train_get_loss : loss is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStateFinishedTraining())
  {
    std::cerr << "Error during Session::train_get_loss : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (index >= getOutputSize())
  {
    std::cerr << "Error during Session::train_get_loss : index is out of range" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    auto ind = onert::ir::IOIndex(index);
    *loss = _execution->getLoss(ind);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_get_loss : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
train_get_traininfo()
NNFW_STATUS onert::api::Session::train_get_traininfo (nnfw_train_info * info)
Definition at line 1392 of file Session.cc.
{
  if (isStateInitialized())
  {
    // There is no _train_info in INITIALIZED, since _train_info is set when a model loaded
    std::cerr << "Error during Session::train_get_traininfo : invalid state";
    return NNFW_STATUS_INVALID_STATE;
  }
  if (info == nullptr)
  {
    std::cerr << "Error during Session::train_get_traininfo : info is nullptr" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  // after model loaded, it ensures that _train_info is not nullptr
  assert(_train_info != nullptr);
  auto convertLossCode = [](const onert::ir::train::LossCode &code) -> NNFW_TRAIN_LOSS {
    switch (code)
    {
      case onert::ir::train::LossCode::Undefined:
        return NNFW_TRAIN_LOSS_UNDEFINED;
      case onert::ir::train::LossCode::MeanSquaredError:
        return NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR;
      case onert::ir::train::LossCode::CategoricalCrossentropy:
        return NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY;
      default:
        throw std::runtime_error{"fail to convert ir::train::LossCode"};
    }
  };
  auto convertLossReduction =
    [](const onert::ir::train::LossReductionType &type) -> NNFW_TRAIN_LOSS_REDUCTION {
    switch (type)
    {
      case onert::ir::train::LossReductionType::Undefined:
        return NNFW_TRAIN_LOSS_REDUCTION_UNDEFINED;
      case onert::ir::train::LossReductionType::SumOverBatchSize:
        return NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE;
      case onert::ir::train::LossReductionType::Sum:
        return NNFW_TRAIN_LOSS_REDUCTION_SUM;
      default:
        throw std::runtime_error{"fail to convert from ir::train::LossReductionType"};
        break;
    }
  };
  auto convertOptimizerCode =
    [](const onert::ir::train::OptimizerCode &code) -> NNFW_TRAIN_OPTIMIZER {
    switch (code)
    {
      case onert::ir::train::OptimizerCode::Undefined:
        return NNFW_TRAIN_OPTIMIZER_UNDEFINED;
      case onert::ir::train::OptimizerCode::SGD:
        return NNFW_TRAIN_OPTIMIZER_SGD;
      case onert::ir::train::OptimizerCode::Adam:
        return NNFW_TRAIN_OPTIMIZER_ADAM;
      default:
        throw std::runtime_error{"fail to convert from ir::train::OptimizerCode"};
    }
  };
  const auto &loss = _train_info->lossInfo();
  const auto &optim = _train_info->optimizerInfo();
  try
  {
    info->learning_rate = optim.learning_rate;
    info->batch_size = _train_info->batchSize();
    info->loss_info.loss = convertLossCode(loss.loss_code);
    info->loss_info.reduction_type = convertLossReduction(loss.reduction_type);
    info->opt = convertOptimizerCode(optim.optim_code);
    if (_train_info->getTrainableOps().size() > 0)
    {
      const uint32_t first_trainable_idx = _train_info->getTrainableOps().cbegin()->value();
      const uint32_t last_trainable_idx = _train_info->getTrainableOps().crbegin()->value();
      const uint32_t ops_size = primary_subgraph()->operations().size();
      const uint32_t trainable_indexes_range = last_trainable_idx - first_trainable_idx + 1;
      // check if trainable ops set contains continuous indexes on the back of the set
      if (last_trainable_idx == ops_size - 1 &&
          trainable_indexes_range == _train_info->getTrainableOps().size())
      {
        // check if all ops are trainable
        if (0 == first_trainable_idx)
        {
          info->num_of_trainable_ops = NNFW_TRAIN_TRAINABLE_ALL;
        }
        else
        {
          info->num_of_trainable_ops = trainable_indexes_range;
        }
      }
      else
      {
        info->num_of_trainable_ops = NNFW_TRAIN_TRAINABLE_INCORRECT_STATE;
        std::cerr << "conversion from set of trainable ops to num_of_trainable_ops is impossible"
                  << std::endl;
        return NNFW_STATUS_INVALID_STATE;
      }
    }
    else
    {
      // no layer will be trained
      info->num_of_trainable_ops = NNFW_TRAIN_TRAINABLE_NONE;
    }
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_get_traininfo" << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::ir::train::Adam, onert::ir::train::CategoricalCrossentropy, info, onert::ir::train::MeanSquaredError, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY, NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR, NNFW_TRAIN_LOSS_REDUCTION_SUM, NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE, NNFW_TRAIN_LOSS_REDUCTION_UNDEFINED, NNFW_TRAIN_LOSS_UNDEFINED, NNFW_TRAIN_OPTIMIZER_ADAM, NNFW_TRAIN_OPTIMIZER_SGD, NNFW_TRAIN_OPTIMIZER_UNDEFINED, NNFW_TRAIN_TRAINABLE_ALL, NNFW_TRAIN_TRAINABLE_INCORRECT_STATE, NNFW_TRAIN_TRAINABLE_NONE, onert::ir::train::SGD, onert::ir::train::Sum, onert::ir::train::SumOverBatchSize, and onert::ir::train::Undefined.
train_import_checkpoint()
NNFW_STATUS onert::api::Session::train_import_checkpoint (const char * path)
Definition at line 1930 of file Session.cc.
{
  if (path == nullptr)
  {
    std::cerr << "Error during Session::train_import_checkpoint : path is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_import_checkpoint : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    onert::loader::train::loadCheckpoint(path, _train_info, _execution);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_import_checkpoint : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::loader::train::loadCheckpoint(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and NNFW_STATUS_UNEXPECTED_NULL.
train_input_tensorinfo()
NNFW_STATUS onert::api::Session::train_input_tensorinfo (uint32_t index, nnfw_tensorinfo * ti)
Definition at line 1652 of file Session.cc.
{
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_input_tensorinfo : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  // Check index is valid: [0, getInputSize())
  // NYI
  (void)index;
  (void)ti;
  return NNFW_STATUS_ERROR;
}
References NNFW_STATUS_ERROR, and NNFW_STATUS_INVALID_STATE.
train_prepare()
NNFW_STATUS onert::api::Session::train_prepare ()
Definition at line 1612 of file Session.cc.
{
  // We may need different state to represent training model is loaded
  if (!isStateModelLoaded())
  {
    std::cerr << "Error during model prepare training: ";
    if (_state == State::PREPARED_TRAINING)
      std::cerr << "prepare should be run once";
    else
      std::cerr << "invalid state";
    std::cerr << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  // after model loaded, it ensures that _train_info is not nullptr
  assert(_train_info != nullptr);
  try
  {
    if (not _train_info->isValid())
      throw std::runtime_error{"training info is not valid"};
    // initialize trainingStep count
    _train_info->trainingStep() = 0;
    auto compiler = onert::compiler::CompilerFactory::get().create(
      std::move(_nnpkg), _coptions.get(), _train_info.get());
    _compiler_artifact = compiler->compile();
    _execution = std::make_unique<onert::exec::Execution>(_compiler_artifact->_executors);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_prepare : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  _state = State::PREPARED_TRAINING;
  return NNFW_STATUS_NO_ERROR;
}
References onert::compiler::CompilerFactory::create(), onert::compiler::CompilerFactory::get(), NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
train_run()
NNFW_STATUS onert::api::Session::train_run (bool update_weights)
Definition at line 1804 of file Session.cc.
{
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_run : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  try
  {
    if (update_weights)
    {
      auto &training_step = _train_info->trainingStep();
      _execution->train(training_step++);
    }
    else
      _execution->execute();
  }
  catch (const onert::InsufficientBufferSizeException &e)
  {
    // Currently insufficient buffer always means output buffer.
    std::cerr << "Error during Session::train_run : " << e.what() << std::endl;
    return NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE;
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_run : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  _state = State::FINISHED_TRAINING;
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INSUFFICIENT_OUTPUT_SIZE, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, and onert::Exception::what().
train_set_expected()
NNFW_STATUS onert::api::Session::train_set_expected (uint32_t index, const void * expected, const nnfw_tensorinfo * expected_tensorinfo)
Definition at line 1727 of file Session.cc.
{
  if (expected == nullptr)
  {
    std::cerr << "Error during Session::train_set_expected : expected buffer is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_set_expected : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (index >= getOutputSize())
  {
    std::cerr << "Error during Session::train_set_expected : index is out of range" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    const auto ind = onert::ir::IOIndex{index};
    auto size = _execution->outputInfo(ind).total_size();
    if (expected_tensorinfo && getBufSize(expected_tensorinfo) != size)
    {
      std::cerr << "Error during Session::train_set_expected : invalid tensorinfo" << std::endl;
      return NNFW_STATUS_ERROR;
    }
    // NOTE Find the loss input index
    // Input is added as many as the number of outputs.
    // The loss index is calculated from the value obtained by subtracting the
    // total output(added loss input) from the total input size.
    auto input_index = getInputSize() - getOutputSize() + index;
    auto input_ind = onert::ir::IOIndex(input_index);
    _execution->setInput(input_ind, expected, size);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_set_expected : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and size.
train_set_input()
NNFW_STATUS onert::api::Session::train_set_input (uint32_t index, const void * input, const nnfw_tensorinfo * input_tensorinfo)
Definition at line 1684 of file Session.cc.
{
  if (input == nullptr)
  {
    std::cerr << "Error during Session::train_set_input : input buffer is null" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_set_input : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (index >= getInputSize())
  {
    std::cerr << "Error during Session::train_set_input : index is out of range" << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    auto ind = onert::ir::IOIndex(index);
    auto size = _execution->inputInfo(ind).total_size();
    if (input_tensorinfo && getBufSize(input_tensorinfo) != size)
    {
      std::cerr << "Error during Session::train_set_input : not supporeted to change tensorinfo"
                << std::endl;
      return NNFW_STATUS_ERROR;
    }
    _execution->setInput(ind, input, size);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_set_input : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, and size.
train_set_output()
NNFW_STATUS onert::api::Session::train_set_output (uint32_t index, NNFW_TYPE type, void * buffer, size_t length)
Definition at line 1775 of file Session.cc.
{
  if (!isStatePreparedOrFinishedTraining())
  {
    std::cerr << "Error during Session::train_set_output : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (!buffer && length != 0)
  {
    std::cerr << "Error during Session::train_set_output : given buffer is NULL but the "
                 "length is not 0"
              << std::endl;
    return NNFW_STATUS_ERROR;
  }
  try
  {
    _execution->setOutput(onert::ir::IOIndex(index), buffer, length);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_set_output : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, and NNFW_STATUS_NO_ERROR.
train_set_traininfo()
NNFW_STATUS onert::api::Session::train_set_traininfo (const nnfw_train_info * info)
Definition at line 1510 of file Session.cc.
{
  if (not isStateModelLoaded())
  {
    std::cerr << "Error during Session::train_set_traininfo : invalid state" << std::endl;
    return NNFW_STATUS_INVALID_STATE;
  }
  if (info == nullptr)
  {
    std::cerr << "Session::train_set_traininfo : info is nullptr" << std::endl;
    return NNFW_STATUS_UNEXPECTED_NULL;
  }
  // after model loaded, it ensures that _train_info is not nullptr
  assert(_train_info != nullptr);
  auto convertLossType = [](const int &type) {
    if (type == NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR)
      return onert::ir::train::LossCode::MeanSquaredError;
    else if (type == NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY)
      return onert::ir::train::LossCode::CategoricalCrossentropy;
    else
      throw std::runtime_error("not supported loss type");
  };
  auto convertLossReductionType = [](const int &type) {
    if (type == NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE)
      return onert::ir::train::LossReductionType::SumOverBatchSize;
    else if (type == NNFW_TRAIN_LOSS_REDUCTION_SUM)
      return onert::ir::train::LossReductionType::Sum;
    else
      throw std::runtime_error("not supported loss reduction type");
  };
  auto convertOptType = [](const int &type) {
    if (type == NNFW_TRAIN_OPTIMIZER_SGD)
      return onert::ir::train::OptimizerCode::SGD;
    else if (type == NNFW_TRAIN_OPTIMIZER_ADAM)
      return onert::ir::train::OptimizerCode::Adam;
    else
      throw std::runtime_error("not supported optimizer type");
  };
  try
  {
    onert::ir::train::LossInfo loss_info;
    loss_info.loss_code = convertLossType(info->loss_info.loss);
    loss_info.reduction_type = convertLossReductionType(info->loss_info.reduction_type);
    onert::ir::train::OptimizerInfo opt_info;
    opt_info.learning_rate = info->learning_rate;
    opt_info.optim_code = convertOptType(info->opt);
    _train_info->setBatchSize(info->batch_size);
    _train_info->setLossInfo(loss_info);
    _train_info->setOptimizerInfo(opt_info);
    if (info->num_of_trainable_ops < -1)
    {
      std::cerr << "Error during Session::train_set_traininfo: provided num_of_trainable_ops "
                   "has incorrect value: "
                << info->num_of_trainable_ops << std::endl;
      return NNFW_STATUS_ERROR;
    }
    const uint32_t ops_size = primary_subgraph()->operations().size();
    std::set<onert::ir::OperationIndex> trainable_ops;
    if (NNFW_TRAIN_TRAINABLE_ALL == info->num_of_trainable_ops)
    {
      for (uint32_t idx = 0; idx < ops_size; ++idx)
      {
        trainable_ops.emplace(idx);
      }
    }
    else
    {
      if (static_cast<uint32_t>(info->num_of_trainable_ops) > ops_size)
      {
        std::cerr << "Error during Session::train_set_traininfo: provided num_of_trainable_ops="
                  << info->num_of_trainable_ops << " is out of operators range equals: " << ops_size
                  << std::endl;
        return NNFW_STATUS_ERROR;
      }
      for (uint32_t i = 1; i <= static_cast<uint32_t>(info->num_of_trainable_ops); ++i)
      {
        trainable_ops.emplace(ops_size - i);
      }
    }
    // Note that possible setting an empty trainable_ops set (for NNFW_TRAIN_TRAINABLE_NONE value)
    _train_info->setTrainableOps(trainable_ops);
  }
  catch (const std::exception &e)
  {
    std::cerr << "Error during Session::train_set_traininfo : " << e.what() << std::endl;
    return NNFW_STATUS_ERROR;
  }
  return NNFW_STATUS_NO_ERROR;
}
References onert::ir::train::Adam, onert::ir::train::CategoricalCrossentropy, info, onert::ir::train::OptimizerInfo::learning_rate, onert::ir::train::LossInfo::loss_code, onert::ir::train::MeanSquaredError, NNFW_STATUS_ERROR, NNFW_STATUS_INVALID_STATE, NNFW_STATUS_NO_ERROR, NNFW_STATUS_UNEXPECTED_NULL, NNFW_TRAIN_LOSS_CATEGORICAL_CROSSENTROPY, NNFW_TRAIN_LOSS_MEAN_SQUARED_ERROR, NNFW_TRAIN_LOSS_REDUCTION_SUM, NNFW_TRAIN_LOSS_REDUCTION_SUM_OVER_BATCH_SIZE, NNFW_TRAIN_OPTIMIZER_ADAM, NNFW_TRAIN_OPTIMIZER_SGD, NNFW_TRAIN_TRAINABLE_ALL, onert::ir::train::OptimizerInfo::optim_code, onert::ir::train::LossInfo::reduction_type, onert::ir::train::SGD, onert::ir::train::Sum, and onert::ir::train::SumOverBatchSize.
The documentation for this struct was generated from the following files:
runtime/onert/api/nnfw/src/Session.h
runtime/onert/api/nnfw/src/Session.cc