ONE - On-device Neural Engine: luci::CloneContext Struct Reference
luci::CloneContext Struct Reference
#include <ConnectNode.h>
Public Member Functions
std::pair< MapNode2Clone::iterator, bool > emplace (const CircleNode *org, CircleNode *clone)
MapNode2Clone::iterator find (const CircleNode *org)
MapNode2Clone::iterator end (void)
MapNode2Clone::const_iterator find (const CircleNode *org) const
MapNode2Clone::const_iterator end (void) const
Data Fields
MapNode2Clone node2clone
Detailed Description
Definition at line 44 of file ConnectNode.h.
Member Function Documentation
emplace()
std::pair< MapNode2Clone::iterator, bool > luci::CloneContext::emplace (const CircleNode * org, CircleNode * clone) inline
Definition at line 46 of file ConnectNode.h.
  {
    return node2clone.emplace(org, clone);
  }
References luci::clone(), and node2clone.
end() [1/2]
MapNode2Clone::iterator luci::CloneContext::end (void) inline
Definition at line 51 of file ConnectNode.h.
{ return node2clone.end(); }
References node2clone.
Referenced by luci::ConnectNode::find_clone().
end() [2/2]
MapNode2Clone::const_iterator luci::CloneContext::end (void) const inline
Definition at line 54 of file ConnectNode.h.
{ return node2clone.end(); }
References node2clone.
find() [1/2]
MapNode2Clone::iterator luci::CloneContext::find (const CircleNode * org) inline
Definition at line 50 of file ConnectNode.h.
{ return node2clone.find(org); }
References node2clone.
Referenced by luci::ConnectNode::find_clone().
find() [2/2]
MapNode2Clone::const_iterator luci::CloneContext::find (const CircleNode * org) const inline
Definition at line 53 of file ConnectNode.h.
{ return node2clone.find(org); }
References node2clone.
Field Documentation
node2clone
MapNode2Clone luci::CloneContext::node2clone
Definition at line 56 of file ConnectNode.h.
Referenced by emplace(), end(), and find().
The documentation for this struct was generated from the following file:
compiler/luci/partition/include/luci/ConnectNode.h