ONE - On-device Neural Engine: mir_interpreter::SoftmaxImpl< T > Struct Template Reference
mir_interpreter::SoftmaxImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &arg, int axis, mir::TensorVariant &result)
Detailed Description
template<typename T>
struct mir_interpreter::SoftmaxImpl< T >
Definition at line 38 of file Softmax.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::SoftmaxImpl< T >::run (const mir::TensorVariant & arg, int axis, mir::TensorVariant & result) static
Definition at line 44 of file Softmax.cpp.
{
  mir::Tensor<T> arg_accessor(arg);
  mir::Tensor<T> res_accessor(result);
  mir::Shape expsum_shape = arg.getShape();
  expsum_shape.dim(axis) = 1;
  mir::TensorType expsum_type(arg.getElementType(), expsum_shape);
  mir::TensorVariant expsum(expsum_type);
  mir::Tensor<T> expsum_accessor(expsum);
  for (const auto &expsum_index : mir::ShapeRange(expsum_shape))
  {
    T sum = 0;
    mir::Index arg_index = expsum_index;
    std::int32_t axis_size = arg.getShape().dim(axis);
    for (std::int32_t i = 0; i < axis_size; ++i)
    {
      arg_index.at(axis) = i;
      sum += std::exp(arg_accessor.at(arg_index));
    }
    expsum_accessor.at(expsum_index) = sum;
  }
  for (const auto &res_index : mir::ShapeRange(result.getShape()))
  {
    mir::Index expsum_index = res_index;
    expsum_index.at(axis) = 0;
    res_accessor.at(res_index) =
      std::exp(arg_accessor.at(res_index)) / expsum_accessor.at(expsum_index);
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::Shape::dim(), and mir::TensorVariant::getShape().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Softmax.cpp