ONE - On-device Neural Engine: mir_interpreter::AddImpl< uint8_t > Struct Reference
mir_interpreter::AddImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const TensorVariant &lhs, const TensorVariant &rhs, TensorVariant &res)
Detailed Description
Definition at line 52 of file Add.cpp.
Member Function Documentation
run()
void mir_interpreter::AddImpl< uint8_t >::run (const TensorVariant & lhs, const TensorVariant & rhs, TensorVariant & res) static
Definition at line 57 of file Add.cpp.
{
  const auto &lhs_type = lhs.getType();
  const auto &rhs_type = rhs.getType();
  const auto &res_type = res.getType();
  assert(lhs_type.isQuantized());
  assert(rhs_type.isQuantized());
  assert(res_type.isQuantized());
  int32_t lhs_offset = -lhs_type.getQuantization().getZeroPoint();
  int32_t rhs_offset = -rhs_type.getQuantization().getZeroPoint();
  int32_t output_offset = res_type.getQuantization().getZeroPoint();
  double lhs_scale = lhs_type.getQuantization().getScale();
  double rhs_scale = rhs_type.getQuantization().getScale();
  double output_scale = res_type.getQuantization().getScale();
  int left_shift = 20;
  const double twice_max_input_scale = 2 * std::max(lhs_scale, rhs_scale);
  const double real_lhs_multiplier = lhs_scale / twice_max_input_scale;
  const double real_rhs_multiplier = rhs_scale / twice_max_input_scale;
  const double real_output_multiplier = twice_max_input_scale / ((1 << left_shift) * output_scale);
  int32_t lhs_multiplier = 0;
  int32_t rhs_multiplier = 0;
  int32_t output_multiplier = 0;
  int lhs_shift = 0;
  int rhs_shift = 0;
  int output_shift = 0;
  QuantizeMultiplierSmallerThanOneExp(real_lhs_multiplier, &lhs_multiplier, &lhs_shift);
  QuantizeMultiplierSmallerThanOneExp(real_rhs_multiplier, &rhs_multiplier, &rhs_shift);
  QuantizeMultiplierSmallerThanOneExp(real_output_multiplier, &output_multiplier, &output_shift);
  TensorVariant broadcasted_lhs(lhs, res_type.getShape());
  TensorVariant broadcasted_rhs(rhs, res_type.getShape());
  Tensor<uint8_t> lhs_accessor(broadcasted_lhs);
  Tensor<uint8_t> rhs_accessor(broadcasted_rhs);
  Tensor<uint8_t> res_accessor(res);
  int32_t output_min = std::numeric_limits<uint8_t>::min();
  int32_t output_max = std::numeric_limits<uint8_t>::max();
  for (const auto &index : ShapeRange(res_type.getShape()))
  {
    const int32_t lhs_val = lhs_accessor.at(index) + lhs_offset;
    const int32_t rhs_val = rhs_accessor.at(index) + rhs_offset;
    const int32_t shifted_lhs_val = lhs_val * (1 << left_shift);
    const int32_t shifted_rhs_val = rhs_val * (1 << left_shift);
    const int32_t scaled_lhs_val =
      MultiplyByQuantizedMultiplierSmallerThanOneExp(shifted_lhs_val, lhs_multiplier, lhs_shift);
    const int32_t scaled_rhs_val =
      MultiplyByQuantizedMultiplierSmallerThanOneExp(shifted_rhs_val, rhs_multiplier, rhs_shift);
    const int32_t raw_sum = scaled_lhs_val + scaled_rhs_val;
    const int32_t raw_output =
      MultiplyByQuantizedMultiplierSmallerThanOneExp(raw_sum, output_multiplier, output_shift) +
      output_offset;
    const int32_t clamped_output = std::min(output_max, std::max(output_min, raw_output));
    res_accessor.at(index) = static_cast<uint8_t>(clamped_output);
  }
}
References mir::Tensor< T >::at(), mir::TensorVariant::getShape(), mir::TensorVariant::getType(), mir_interpreter::MultiplyByQuantizedMultiplierSmallerThanOneExp(), and mir_interpreter::QuantizeMultiplierSmallerThanOneExp().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Add.cpp