ONE - On-device Neural Engine: ANeuralNetworksCompilation Struct Reference
ANeuralNetworksCompilation Struct Reference
#include <ANeuralNetworksCompilation.h>
Public Member Functions
ANeuralNetworksCompilation (const ANeuralNetworksModel *model) noexcept
bool finish () noexcept
bool isFinished () noexcept
void publish (std::shared_ptr< onert::exec::IExecutors > &executors) noexcept
Detailed Description
Definition at line 28 of file ANeuralNetworksCompilation.h.
Constructor & Destructor Documentation
ANeuralNetworksCompilation()
ANeuralNetworksCompilation::ANeuralNetworksCompilation (const ANeuralNetworksModel * model) noexcept
Definition at line 24 of file ANeuralNetworksCompilation.cc.
  : _model{model->getModel()}, _coptions{compiler::CompilerOptions::fromGlobalConfig()},
    _compiler{std::make_shared<compiler::Compiler>(_model, *_coptions)}
{
  if (model->allowedToFp16())
    _coptions->enableToFp16();
}
Member Function Documentation
finish()
bool ANeuralNetworksCompilation::finish () noexcept
Definition at line 32 of file ANeuralNetworksCompilation.cc.
{
  try
  {
    _artifact = _compiler->compile();
    _compiler = nullptr;
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
Referenced by ANeuralNetworksCompilation_finish().
isFinished()
bool ANeuralNetworksCompilation::isFinished () inline noexcept
Definition at line 35 of file ANeuralNetworksCompilation.h.
{ return _compiler == nullptr; }
Referenced by ANeuralNetworksCompilation_finish(), and ANeuralNetworksCompilation_setPreference().
publish()
void ANeuralNetworksCompilation::publish (std::shared_ptr< onert::exec::IExecutors > & executors) inline noexcept
Definition at line 37 of file ANeuralNetworksCompilation.h.
  {
    executors = _artifact ? _artifact->_executors : nullptr;
  }
Referenced by ANeuralNetworksExecution_create().
The documentation for this struct was generated from the following files:
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.h
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksCompilation.cc