ONE - On-device Neural Engine: luci::CircleExporter::Contract Struct Reference
luci::CircleExporter::Contract Struct Reference abstract
#include <CircleExporter.h>
Public Member Functions
virtual ~Contract ()=default
virtual loco::Graph * graph (void) const =0
virtual luci::Module * module (void) const
virtual bool store (const char *ptr, const size_t size) const =0
Detailed Description
Definition at line 33 of file CircleExporter.h.
Constructor & Destructor Documentation
~Contract()
virtual luci::CircleExporter::Contract::~Contract () virtual default
Member Function Documentation
graph()
virtual loco::Graph * luci::CircleExporter::Contract::graph (void) const pure virtual
Implemented in luci::CircleFileExpContract.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), luci::CircleExporter::invoke(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
module()
Module * luci::CircleExporter::Contract::module (void) const virtual
Reimplemented in luci::CircleFileExpContract.
Definition at line 30 of file CircleExporter.cpp.
{ return nullptr; }
Referenced by luci::CircleExporter::invoke().
store()
virtual bool luci::CircleExporter::Contract::store (const char * ptr, const size_t size) const pure virtual
Implemented in luci::CircleFileExpContract.
Referenced by luci::CircleExporter::invoke().
The documentation for this struct was generated from the following files:
compiler/luci/export/include/luci/CircleExporter.h
compiler/luci/export/src/CircleExporter.cpp