ONE - On-device Neural Engine: locop::NodeDesc Struct Reference
locop::NodeDesc Struct Reference
#include <NodeSummary.h>
Data Structures
class Comments
Multi-line comments.
Public Types
enum class State { Invalid , PartiallyKnown , Complete }
Public Member Functions
NodeDesc ()=default
NodeDesc (const OpName &opname)
const OpName & opname (void) const
void opname (const OpName &value)
const ArgDesc & args (void) const
ArgDesc & args (void)
const Comments & comments (void) const
Comments & comments (void)
const State & state (void) const
void state (const State &s)
Detailed Description
Definition at line 49 of file NodeSummary.h.
Member Enumeration Documentation
State
enum class locop::NodeDesc::State strong
Enumerator
Invalid
PartiallyKnown
Complete
Definition at line 70 of file NodeSummary.h.
  {
    // All the node descriptions are "Invalid" at the beginning.
    //
    // Any valid node description SHOULD NOT be at this state.
    Invalid,
    // This state means that the producer is **NOT** confident about the information that
    // it generates.
    //
    // There may be some missing information.
    PartiallyKnown,
    // This state means that the producer is confident about the information that it
    // generates.
    Complete,
  };
Constructor & Destructor Documentation
NodeDesc() [1/2]
locop::NodeDesc::NodeDesc () default
NodeDesc() [2/2]
locop::NodeDesc::NodeDesc (const OpName & opname) inline
Definition at line 88 of file NodeSummary.h.
{ this->opname(opname); }
References opname().
Member Function Documentation
args() [1/2]
ArgDesc & locop::NodeDesc::args (void) inline
Definition at line 95 of file NodeSummary.h.
{ return _args; }
Referenced by Command.Command::add_noarg_option_if_valid_arg(), and Command.Command::add_option_with_valid_args().
args() [2/2]
const ArgDesc & locop::NodeDesc::args (void) const inline
Definition at line 94 of file NodeSummary.h.
{ return _args; }
Referenced by Command.Command::add_noarg_option_if_valid_arg(), Command.Command::add_option_with_valid_args(), and locop::GenericNodeSummaryBuilder::build().
comments() [1/2]
Comments & locop::NodeDesc::comments (void) inline
Definition at line 98 of file NodeSummary.h.
{ return _comments; }
comments() [2/2]
const Comments & locop::NodeDesc::comments (void) const inline
Definition at line 97 of file NodeSummary.h.
{ return _comments; }
Referenced by locop::FormattedGraphImpl< Formatter::LinearV1 >::dump().
opname() [1/2]
void locop::NodeDesc::opname (const OpName & value)
Definition at line 38 of file NodeSummary.cpp.
{ _name = std::make_unique<std::string>(v); }
opname() [2/2]
const std::string & locop::NodeDesc::opname (void) const
Definition at line 31 of file NodeSummary.cpp.
{
  // _name SHOULD BE set before use
  assert(_name != nullptr);
  return *_name;
}
Referenced by locop::GenericNodeSummaryBuilder::build(), and NodeDesc().
state() [1/2]
void locop::NodeDesc::state (const State & s) inline
Definition at line 101 of file NodeSummary.h.
{ _state = s; }
state() [2/2]
const State & locop::NodeDesc::state (void) const inline
Definition at line 100 of file NodeSummary.h.
{ return _state; }
Referenced by locop::GenericNodeSummaryBuilder::build().
The documentation for this struct was generated from the following files:
compiler/locop/include/locop/NodeSummary.h
compiler/locop/src/NodeSummary.cpp