ONE - On-device Neural Engine: logo::ReorderDecodePass< loco::ReLU > Struct Reference
logo::ReorderDecodePass< loco::ReLU > Struct Reference final
#include <ReorderDecodePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Definition at line 42 of file ReorderDecodePass.h.
Member Function Documentation
name()
const char * logo::ReorderDecodePass< loco::ReLU >::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 44 of file ReorderDecodePass.h.
{ return "ReorderDecodePass<ReLU> "; }
run()
bool logo::ReorderDecodePass< loco::ReLU >::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Let us consider the following graph:
A —> FeatureDecode(1) —> ReLU(2)
ReorderDecodeTransform rewrites this graph as follows:
A -+-> FeatureDecode(1) —> ReLU(2) | +-> ReLU(2') —> FeatureDecode(1')
Let us feed this updates graph to ReorderDecodeTransform.
The naive implementation will create a new ReLU->FeatureDecode chain again, and results in unbounded graph blow-up.
A -+-> FeatureDeocde(1) —> ReLU(2) | +-> ReLU(2') —> FeatureDecode(1') | +-> ReLU(2'') —> FeatureDecode(1'')
This check prevents such unbounded graph blow-up.
Let us consider the following example:
A -=-> FeatureDecode(1) -+-> ReLU(2) -+-> B1 | | | +-> B2 | | | +-> ... | +-> ...
At this point, "cur_decode" points to FeatureDecode(1) and "u" points to ReLU(2).
First rewrite the graph as follows:
A -+-> ReLU(2') —> FeatureDecode(1') -+-> B1 | | | +-> B2 | | | +-> ... | +-> FeatureDecode -+-> ReLU(2) ; NO USE | +-> ...
Enque FeatureDeocde(1') for the further optimization.
Implements logo::Pass.
Definition at line 184 of file ReorderDecodePass.cpp.
{
  std::queue<loco::FeatureDecode *> q;
  gather_candidates(g, q);
  bool changed = false;
  while (!q.empty())
  {
    auto cur_decode = q.front();
    q.pop();
    // Collector IS EXPECTED TO guarantee this property
    assert(cur_decode->input() != nullptr);
    for (auto u : loco::succs(cur_decode))
    {
      if (loco::succs(u).empty())
      {
        continue;
      }
      if (isReLU(u))
      {
        auto new_relu = g->nodes()->create<loco::ReLU>();
        auto new_decode = g->nodes()->create<loco::FeatureDecode>();
        new_relu->input(cur_decode->input());
        new_decode->input(new_relu);
        new_decode->decoder(cur_decode->decoder()->clone());
        loco::replace(u).with(new_decode);
        q.push(new_decode);
        changed = true;
      }
    }
  }
  return changed;
}
References loco::ReLU::input(), loco::FeatureDecode::input(), loco::replace(), loco::succs(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this struct was generated from the following files:
compiler/logo/include/logo/ReorderDecodePass.h
compiler/logo/src/Passes/ReorderDecodePass.cpp