ONE - On-device Neural Engine: luci::CircleShapeInferenceRule Struct Reference
luci::CircleShapeInferenceRule Struct Reference final
#include <CircleShapeInferenceRule.h>
Public Member Functions
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::NodeShape &) const final
Infer node's shape.
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Definition at line 25 of file CircleShapeInferenceRule.h.
Member Function Documentation
infer()
bool luci::CircleShapeInferenceRule::infer (const loco::Node * , loco::NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 2477 of file CircleShapeInferenceRule.cpp.
{
  LOGGER(l);
  assert(node->dialect() == CircleDialect::get());
  ShapeInferenceAlgorithm alg;
  auto circle_node = loco::must_cast<const CircleNode *>(node);
  bool is_shape_undefined = (circle_node->shape_status() == ShapeStatus::UNDEFINED);
  bool is_shape_none = (circle_node->shape_status() == ShapeStatus::NOSHAPE);
  bool is_scalar = (circle_node->rank() == 0);
  if (is_shape_undefined)
    shape = circle_node->accept(&alg);
  else
  {
    if (is_shape_none || is_scalar)
      shape = own_shape(circle_node);
    else
      shape = circle_node->accept(&alg);
  }
  VERBOSE(l, 1) << "[luci] shape: " << circle_node->name();
  VERBOSE(l, 1) << "              own_shape: " << own_shape(circle_node)
                << " -> infer: " << shape.as<loco::TensorShape>();
  return true;
}
References loco::NodeShape::as(), loco::Node::dialect(), luci::CircleDialect::get(), LOGGER, luci::NOSHAPE, luci::UNDEFINED, and VERBOSE.
Referenced by luci::sinf::Algorithm::visit().
recognize()
bool luci::CircleShapeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 2472 of file CircleShapeInferenceRule.cpp.
{
  return CircleDialect::get() == d;
}
References luci::CircleDialect::get().
The documentation for this struct was generated from the following files:
compiler/luci/service/include/luci/Service/CircleShapeInferenceRule.h
compiler/luci/service/src/CircleShapeInferenceRule.cpp