ONE - On-device Neural Engine: QConfReader Struct Reference
QConfReader Struct Reference
Public Member Functions
void init (const std::string &filename)
Json::Value & root (void)
Detailed Description
Definition at line 39 of file CircleQuantizer.cpp.
Member Function Documentation
init()
void QConfReader::init (const std::string & filename) inline
Definition at line 41 of file CircleQuantizer.cpp.
  {
    std::ifstream ifs;
    ifs.open(filename);
    // Failed to open cfg file
    if (not ifs.is_open())
      throw std::runtime_error("Cannot open config file. " + filename);
    JSONCPP_STRING errs;
    Json::CharReaderBuilder builder;
    // Failed to parse
    if (not parseFromStream(builder, ifs, &_root, &errs))
      throw std::runtime_error("Cannot parse config file (json format). " + errs);
    ifs.close();
  }
Referenced by read_layer_params(), and read_layer_params_set().
root()
Json::Value & QConfReader::root (void) inline
Definition at line 61 of file CircleQuantizer.cpp.
{ return _root; }
Referenced by read_layer_params(), and read_layer_params_set().
The documentation for this struct was generated from the following file:
compiler/circle-quantizer/src/CircleQuantizer.cpp