ONE - On-device Neural Engine: exo::FuseBiasAddPass Struct Reference
exo::FuseBiasAddPass Struct Reference final
Class to fuse TFLAdd or TFLSub into Bias input of the following ops:
#include <FuseBiasAddPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Class to fuse TFLAdd or TFLSub into Bias input of the following ops:
TFLConv2D, TFLDepthwiseConv2D
TODO Consider to add FullyConnected, etc.
Case 1. Conv2D and TFLAdd
BEFORE:
              TFLConst A (a scalar or a tensor of shape [1] or [depth of TFLConv2D])
                   |
Foo – TFLConv2D – TFLAdd (or TFLSub) – Bar | TFLConst B –+ (bias)
AFTER: Foo --— TFLConv2D --— Bar | TFLConst A' –+ (bias)
TFLConst B (dead node)
TFLAdd (or TFLSub) (dead node)
Note
TFLSub, of which x() == TFLConv2D and y() == TFLConst, will be fused. If x() == TFLConst and y() == TFLConv2D, it won't be fused.
Definition at line 52 of file FuseBiasAddPass.h.
Member Function Documentation
name()
const char * exo::FuseBiasAddPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 54 of file FuseBiasAddPass.h.
{ return "exo::FuseBiasAddPass"; }
run()
bool exo::FuseBiasAddPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 339 of file FuseBiasAddPass.cpp.
{
  Collector collector;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (node->dialect() == locoex::TFLDialect::get())
    {
      auto tfl_node = loco::must_cast<locoex::TFLNode *>(node);
      tfl_node->accept(&collector);
    }
  }
  Performer performer;
  for (auto node : collector.candidates)
  {
    node->accept(&performer);
  }
  return collector.candidates.size() > 0;
}
References locoex::TFLNode::accept(), loco::active_nodes(), locoex::TFLNode::dialect(), locoex::TFLDialect::get(), and loco::output_nodes().
The documentation for this struct was generated from the following files:
compiler/exo/src/Pass/FuseBiasAddPass.h
compiler/exo/src/Pass/FuseBiasAddPass.cpp