ONE - On-device Neural Engine: logo::RemoveDeadNodeWithQueryPass Struct Reference
logo::RemoveDeadNodeWithQueryPass Struct Reference final
#include <RemoveDeadNodeWithQueryPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g)
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Definition at line 25 of file RemoveDeadNodeWithQueryPass.h.
Member Function Documentation
name()
const char * logo::RemoveDeadNodeWithQueryPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 27 of file RemoveDeadNodeWithQueryPass.h.
{ return "RemoveDeadNodeWithQueryPass"; }
run()
bool logo::RemoveDeadNodeWithQueryPass::run (loco::Graph * graph) virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 29 of file RemoveDeadNodeWithQueryPass.cpp.
{
  // Let's enumerate nodes required to compute output nodes
  auto active_nodes = loco::active_nodes(loco::output_nodes(g));
  // List dead(= non-active) nodes candidates
  std::set<loco::Node *> candidates;
  for (auto node : loco::all_nodes(g))
  {
    if (active_nodes.find(node) == active_nodes.end())
    {
      candidates.insert(node);
    }
  }
  // Find the nodes that should not be dead node in candidates
  for (auto node : candidates)
  {
    if (auto service = node->dialect()->service<DeadNodeQueryService>())
    {
      if (!service->isDeadNode(node))
      {
        candidates.erase(node);
      }
    }
  }
  for (auto node : candidates)
  {
    node->drop();
  }
  for (auto node : candidates)
  {
    g->nodes()->destroy(node);
  }
  return candidates.size() > 0;
}
References loco::active_nodes(), loco::all_nodes(), and loco::output_nodes().
The documentation for this struct was generated from the following files:
compiler/logo/include/logo/RemoveDeadNodeWithQueryPass.h
compiler/logo/src/Passes/RemoveDeadNodeWithQueryPass.cpp