ONE - On-device Neural Engine: moco::RemoveTFIdentityNode Struct Reference
moco::RemoveTFIdentityNode Struct Reference final
Use the input of "TFIdentity" node instead.
#include <RemoveTFIdentityNode.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Use the input of "TFIdentity" node instead.
BEFORE: [X] -> [TFIdentity] -> [Y]
AFTER: [X] -> [Y] [TFIdentity]
NOTE This transform does not remove "TFIdentity" node This transform is identical to RemoveForwardNode
Definition at line 40 of file RemoveTFIdentityNode.h.
Member Function Documentation
name()
const char * moco::RemoveTFIdentityNode::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 42 of file RemoveTFIdentityNode.h.
{ return "RemoveTFIdentityNode"; }
run()
bool moco::RemoveTFIdentityNode::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 27 of file RemoveTFIdentityNode.cpp.
{
  struct Collector final : public moco::TFNodeMutableVisitor<void>
  {
    void visit(moco::TFIdentity *node) final
    {
      if (node->input() != nullptr)
      {
        candidates.insert(node);
      }
    }
    void visit(moco::TFNode *) final { return; }
    std::set<moco::TFIdentity *> candidates;
  };
  Collector collector;
  for (auto node : loco::all_nodes(g))
  {
    if (node->dialect() == moco::TFDialect::get())
    {
      auto tf_node = dynamic_cast<moco::TFNode *>(node);
      // NOTE our analysis tool reports an error for tf_node may be nullptr
      if (tf_node != nullptr)
        tf_node->accept(&collector);
    }
  }
  for (auto node : collector.candidates)
  {
    replace(node).with(node->input());
    node->input(nullptr);
  }
  return collector.candidates.size() > 0;
}
References moco::TFNode::accept(), loco::all_nodes(), moco::TFDialect::get(), moco::TFIdentity::input(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this struct was generated from the following files:
compiler/moco/pass/include/moco/Pass/Passes/RemoveTFIdentityNode.h
compiler/moco/pass/src/Passes/RemoveTFIdentityNode.cpp