ONE - On-device Neural Engine: luci::sinf::StridedSliceContext Struct Reference
luci::sinf::StridedSliceContext Struct Reference
Public Member Functions
StridedSliceContext (const luci::CircleStridedSlice *node)
Data Fields
StridedSliceParams params
luci::CircleNode * input = nullptr
luci::CircleConst * begin = nullptr
luci::CircleConst * end = nullptr
luci::CircleConst * strides = nullptr
loco::TensorShape effective_input_shape
int64_t input_dims = 0
Detailed Description
Definition at line 78 of file CircleStridedSlice.cpp.
Constructor & Destructor Documentation
StridedSliceContext()
luci::sinf::StridedSliceContext::StridedSliceContext (const luci::CircleStridedSlice * node) inline
Definition at line 80 of file CircleStridedSlice.cpp.
  {
    // check overflow issues
    assert(static_cast<int16_t>(node->begin_mask()) == node->begin_mask());
    assert(static_cast<int16_t>(node->ellipsis_mask()) == node->ellipsis_mask());
    assert(static_cast<int16_t>(node->end_mask()) == node->end_mask());
    assert(static_cast<int16_t>(node->new_axis_mask()) == node->new_axis_mask());
    assert(static_cast<int16_t>(node->shrink_axis_mask()) == node->shrink_axis_mask());
    params.begin_mask = node->begin_mask();
    params.ellipsis_mask = node->ellipsis_mask();
    params.end_mask = node->end_mask();
    params.new_axis_mask = node->new_axis_mask();
    params.shrink_axis_mask = node->shrink_axis_mask();
    input = loco::must_cast<luci::CircleNode *>(node->input());
    begin = luci::must_cast<luci::CircleConst *>(node->begin());
    end = luci::must_cast<luci::CircleConst *>(node->end());
    strides = luci::must_cast<luci::CircleConst *>(node->strides());
    loco::TensorShape input_shape = circle_shape(input);
    input_dims = static_cast<int64_t>(input_shape.rank());
  }
References luci::CircleStridedSlice::begin(), begin, luci::CircleStridedSlice::begin_mask(), luci::sinf::StridedSliceParams::begin_mask, luci::sinf::circle_shape(), luci::CircleStridedSlice::ellipsis_mask(), luci::sinf::StridedSliceParams::ellipsis_mask, luci::CircleStridedSlice::end(), end, luci::CircleStridedSlice::end_mask(), luci::sinf::StridedSliceParams::end_mask, luci::CircleStridedSlice::input(), input, input_dims, loco::must_cast(), luci::must_cast(), luci::CircleStridedSlice::new_axis_mask(), luci::sinf::StridedSliceParams::new_axis_mask, params, luci::CircleStridedSlice::shrink_axis_mask(), luci::sinf::StridedSliceParams::shrink_axis_mask, luci::CircleStridedSlice::strides(), and strides.
Field Documentation
begin
luci::CircleConst* luci::sinf::StridedSliceContext::begin = nullptr
Definition at line 105 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
effective_input_shape
loco::TensorShape luci::sinf::StridedSliceContext::effective_input_shape
Definition at line 110 of file CircleStridedSlice.cpp.
end
luci::CircleConst* luci::sinf::StridedSliceContext::end = nullptr
Definition at line 106 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
input
luci::CircleNode* luci::sinf::StridedSliceContext::input = nullptr
Definition at line 104 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
input_dims
int64_t luci::sinf::StridedSliceContext::input_dims = 0
Definition at line 111 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
params
StridedSliceParams luci::sinf::StridedSliceContext::params
Definition at line 103 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
strides
luci::CircleConst* luci::sinf::StridedSliceContext::strides = nullptr
Definition at line 107 of file CircleStridedSlice.cpp.
Referenced by StridedSliceContext().
The documentation for this struct was generated from the following file:
compiler/luci/service/src/Nodes/CircleStridedSlice.cpp