ONE - On-device Neural Engine: mir_interpreter::Conv2DImpl< uint8_t > Struct Reference
mir_interpreter::Conv2DImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const TensorVariant &input, const TensorVariant &kernel, const Conv2DOpAttributes &attributes, TensorVariant &result, const TensorVariant *fused_bias)
Detailed Description
Definition at line 133 of file Conv2D.cpp.
Member Function Documentation
run()
void mir_interpreter::Conv2DImpl< uint8_t >::run (const TensorVariant & input, const TensorVariant & kernel, const Conv2DOpAttributes & attributes, TensorVariant & result, const TensorVariant * fused_bias) static
Definition at line 140 of file Conv2D.cpp.
{
  if (!fused_bias)
  {
    throw std::runtime_error{"Quantized Conv2D cannot be executed without fused bias"};
  }
  const auto &input_type = input.getType();
  const auto &kernel_type = kernel.getType();
  const auto &bias_type = fused_bias->getType();
  const auto &output_type = result.getType();
  (void)bias_type;
  assert(input_type.isQuantized());
  assert(kernel_type.isQuantized());
  assert(bias_type.isQuantized());
  assert(output_type.isQuantized());
  assert(input_type.getElementType() == DataType::UINT8);
  assert(kernel_type.getElementType() == DataType::UINT8);
  assert(bias_type.getElementType() == DataType::INT32);
  assert(output_type.getElementType() == DataType::UINT8);
  int32_t input_offset = -input_type.getQuantization().getZeroPoint();
  int32_t kernel_offset = -kernel_type.getQuantization().getZeroPoint();
  int32_t output_offset = output_type.getQuantization().getZeroPoint();
  double input_scale = input_type.getQuantization().getScale();
  double kernel_scale = kernel_type.getQuantization().getScale();
  double output_scale = output_type.getQuantization().getScale();
  double real_multiplier = input_scale * kernel_scale / output_scale;
  int32_t output_multiplier = 0;
  int output_shift = 0;
  QuantizeMultiplier(real_multiplier, &output_multiplier, &output_shift);
  const Shape &in_shape = input.getShape();
  const Shape &kernel_shape = kernel.getShape();
  const Shape &out_shape = result.getShape();
  const auto &strides = attributes.strides;
  const std::vector<int32_t> &pads = attributes.padding_before;
  assert(attributes.num_groups == 1);
  assert(attributes.data_format == DataFormat::NHWC);
  assert(in_shape.rank() == 4);
  assert(kernel_shape.rank() == 4);
  assert(kernel_shape.dim(3) == in_shape.dim(3));
  assert(kernel_shape.dim(0) == out_shape.dim(3));
  assert(strides.size() == 2);
  assert(pads.size() == 2);
  int32_t stride_height = strides[0];
  int32_t stride_width = strides[1];
  int32_t pad_height = pads[0];
  int32_t pad_width = pads[1];
  int32_t input_height = in_shape.dim(1);
  int32_t input_width = in_shape.dim(2);
  Tensor<uint8_t> input_accessor(input);
  Tensor<uint8_t> kernel_accessor(kernel);
  Tensor<int32_t> bias_accessor(*fused_bias);
  Tensor<uint8_t> res_accessor(result);
  int32_t output_min = std::numeric_limits<uint8_t>::min();
  int32_t output_max = std::numeric_limits<uint8_t>::max();
  for (int batch = 0; batch < out_shape.dim(0); ++batch)
  {
    for (int out_y = 0; out_y < out_shape.dim(1); ++out_y)
    {
      for (int out_x = 0; out_x < out_shape.dim(2); ++out_x)
      {
        for (int out_channel = 0; out_channel < out_shape.dim(3); ++out_channel)
        {
          const int in_x_origin = (out_x * stride_width) - pad_width;
          const int in_y_origin = (out_y * stride_height) - pad_height;
          int32_t acc = 0;
          for (int filter_y = 0; filter_y < kernel_shape.dim(1); ++filter_y)
          {
            for (int filter_x = 0; filter_x < kernel_shape.dim(2); ++filter_x)
            {
              for (int in_channel = 0; in_channel < kernel_shape.dim(3); ++in_channel)
              {
                const int in_x = in_x_origin + filter_x;
                const int in_y = in_y_origin + filter_y;
                // If the location is outside the bounds of the input image,
                // use zero as a default value.
                if ((in_x >= 0) && (in_x < input_width) && (in_y >= 0) && (in_y < input_height))
                {
                  Index in_index{batch, in_y, in_x, in_channel};
                  Index ker_index{out_channel, filter_y, filter_x, in_channel};
                  int32_t input_val = input_accessor.at(in_index);
                  int32_t kernel_val = kernel_accessor.at(ker_index);
                  acc += (kernel_val + kernel_offset) * (input_val + input_offset);
                }
              }
            }
          }
          acc += bias_accessor.at(Index{out_channel});
          acc = MultiplyByQuantizedMultiplier(acc, output_multiplier, output_shift);
          acc += output_offset;
          acc = std::max(acc, output_min);
          acc = std::min(acc, output_max);
          Index out_index{batch, out_y, out_x, out_channel};
          res_accessor.at(out_index) = static_cast<uint8_t>(acc);
        }
      }
    }
  }
}
References mir::Tensor< T >::at(), mir::Conv2DOpAttributes::data_format, mir::Shape::dim(), mir::TensorVariant::getShape(), mir::TensorVariant::getType(), mir_interpreter::MultiplyByQuantizedMultiplier(), mir::Conv2DOpAttributes::num_groups, mir::Conv2DOpAttributes::padding_before, mir_interpreter::QuantizeMultiplier(), mir::Shape::rank(), and mir::Conv2DOpAttributes::strides.
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Conv2D.cpp