ONE - On-device Neural Engine: flatbuffers::VectorIterator< T, IT, Data, SizeT > Struct Template Reference
flatbuffers::VectorIterator< T, IT, Data, SizeT > Struct Template Reference
#include <vector.h>
Public Types
typedef std::random_access_iterator_tag iterator_category
typedef IT value_type
typedef ptrdiff_t difference_type
typedef IT * pointer
typedef IT & reference
Public Member Functions
VectorIterator (Data data, SizeT i)
VectorIterator (const VectorIterator &other)
VectorIterator ()
VectorIterator & operator= (const VectorIterator &other)
VectorIterator & operator= (VectorIterator &&other)
bool operator== (const VectorIterator &other) const
bool operator< (const VectorIterator &other) const
bool operator!= (const VectorIterator &other) const
difference_type operator- (const VectorIterator &other) const
IT operator* () const
IT operator-> () const
VectorIterator & operator++ ()
VectorIterator operator++ (int)
VectorIterator operator+ (const SizeT &offset) const
VectorIterator & operator+= (const SizeT &offset)
VectorIterator & operator-- ()
VectorIterator operator-- (int)
VectorIterator operator- (const SizeT &offset) const
VectorIterator & operator-= (const SizeT &offset)
Static Public Attributes
static const SizeT element_stride = IndirectHelper<T>::element_stride
Detailed Description
template<typename T, typename IT, typename Data = uint8_t *, typename SizeT = uoffset_t>
struct flatbuffers::VectorIterator< T, IT, Data, SizeT >
Definition at line 32 of file vector.h.
Member Typedef Documentation
difference_type
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> typedef ptrdiff_t flatbuffers::VectorIterator< T, IT, Data, SizeT >::difference_type
Definition at line 35 of file vector.h.
iterator_category
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> typedef std::random_access_iterator_tag flatbuffers::VectorIterator< T, IT, Data, SizeT >::iterator_category
Definition at line 33 of file vector.h.
pointer
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> typedef IT* flatbuffers::VectorIterator< T, IT, Data, SizeT >::pointer
Definition at line 36 of file vector.h.
reference
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> typedef IT& flatbuffers::VectorIterator< T, IT, Data, SizeT >::reference
Definition at line 37 of file vector.h.
value_type
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> typedef IT flatbuffers::VectorIterator< T, IT, Data, SizeT >::value_type
Definition at line 34 of file vector.h.
Constructor & Destructor Documentation
VectorIterator() [1/3]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> flatbuffers::VectorIterator< T, IT, Data, SizeT >::VectorIterator (Data data, SizeT i) inline
Definition at line 41 of file vector.h.
: data_(data + element_stride * i) {}
VectorIterator() [2/3]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> flatbuffers::VectorIterator< T, IT, Data, SizeT >::VectorIterator (const VectorIterator< T, IT, Data, SizeT > & other) inline
Definition at line 42 of file vector.h.
: data_(other.data_) {}
VectorIterator() [3/3]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> flatbuffers::VectorIterator< T, IT, Data, SizeT >::VectorIterator () inline
Definition at line 43 of file vector.h.
: data_(nullptr) {}
Referenced by flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator+(), and flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-().
Member Function Documentation
operator!=()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> bool flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator!= (const VectorIterator< T, IT, Data, SizeT > & other) const inline
Definition at line 63 of file vector.h.
{
    return data_ != other.data_;
  }
operator*()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> IT flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator* () const inline
Definition at line 73 of file vector.h.
{ return IndirectHelper<T>::Read(data_, 0); }
operator+()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator+ (const SizeT & offset) const inline
Definition at line 90 of file vector.h.
{
    return VectorIterator(data_ + offset * element_stride, 0);
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride, offset(), and flatbuffers::VectorIterator< T, IT, Data, SizeT >::VectorIterator().
operator++() [1/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator++ () inline
Definition at line 79 of file vector.h.
{
    data_ += element_stride;
    return *this;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride.
operator++() [2/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator++ (int) inline
Definition at line 84 of file vector.h.
{
    VectorIterator temp(data_, 0);
    data_ += element_stride;
    return temp;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride.
operator+=()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator+= (const SizeT & offset) inline
Definition at line 94 of file vector.h.
{
    data_ += offset * element_stride;
    return *this;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride, and offset().
operator-() [1/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator- (const SizeT & offset) const inline
Definition at line 110 of file vector.h.
{
    return VectorIterator(data_ - offset * element_stride, 0);
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride, offset(), and flatbuffers::VectorIterator< T, IT, Data, SizeT >::VectorIterator().
operator-() [2/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> difference_type flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator- (const VectorIterator< T, IT, Data, SizeT > & other) const inline
Definition at line 67 of file vector.h.
{
    return (data_ - other.data_) / element_stride;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride.
operator--() [1/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-- () inline
Definition at line 99 of file vector.h.
{
    data_ -= element_stride;
    return *this;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride.
operator--() [2/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-- (int) inline
Definition at line 104 of file vector.h.
{
    VectorIterator temp(data_, 0);
    data_ -= element_stride;
    return temp;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride.
operator-=()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-= (const SizeT & offset) inline
Definition at line 114 of file vector.h.
{
    data_ -= offset * element_stride;
    return *this;
  }
References flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride, and offset().
operator->()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> IT flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-> () const inline
Definition at line 77 of file vector.h.
{ return IndirectHelper<T>::Read(data_, 0); }
operator<()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> bool flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator< (const VectorIterator< T, IT, Data, SizeT > & other) const inline
Definition at line 59 of file vector.h.
{
    return data_ < other.data_;
  }
operator=() [1/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator= (const VectorIterator< T, IT, Data, SizeT > & other) inline
Definition at line 45 of file vector.h.
{
    data_ = other.data_;
    return *this;
  }
operator=() [2/2]
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> VectorIterator & flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator= (VectorIterator< T, IT, Data, SizeT > && other) inline
Definition at line 50 of file vector.h.
{
    data_ = other.data_;
    return *this;
  }
operator==()
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> bool flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator== (const VectorIterator< T, IT, Data, SizeT > & other) const inline
Definition at line 55 of file vector.h.
{
    return data_ == other.data_;
  }
Field Documentation
element_stride
template<typename T , typename IT , typename Data = uint8_t *, typename SizeT = uoffset_t> const SizeT flatbuffers::VectorIterator< T, IT, Data, SizeT >::element_stride = IndirectHelper<T>::element_stride static
Definition at line 39 of file vector.h.
Referenced by flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator+(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator++(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator++(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator+=(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator--(), flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator--(), and flatbuffers::VectorIterator< T, IT, Data, SizeT >::operator-=().
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/vector.h