ONE - On-device Neural Engine: ANeuralNetworksExecution Struct Reference
ANeuralNetworksExecution Struct Reference
#include <ANeuralNetworksExecution.h>
Public Member Functions
ANeuralNetworksExecution (const std::shared_ptr< onert::exec::IExecutors > &executors)
bool setInput (uint32_t index, const ANeuralNetworksOperandType *type, const void *buffer, size_t length) noexcept
bool setOptionalInput (uint32_t index, const ANeuralNetworksOperandType *type, const void *buffer, size_t length) noexcept
bool setOutput (uint32_t index, const ANeuralNetworksOperandType *type, void *buffer, size_t length) noexcept
bool startExecute (void) noexcept
bool execute (void) noexcept
const onert::ir::OperandIndex getInputOperandIndex (int32_t index) noexcept
const onert::ir::OperandIndex getOutputOperandIndex (int32_t index) noexcept
bool compareDataType (const ANeuralNetworksOperandType *type, const onert::ir::OperandIndex index) noexcept
bool compareShape (const ANeuralNetworksOperandType *type, const onert::ir::OperandIndex index) noexcept
bool IsOptionalInput (const onert::ir::OperandIndex index) noexcept
bool hasUnspecifiedDims (const onert::ir::OperandIndex index) noexcept
size_t getOperandSize (const onert::ir::OperandIndex index) noexcept
const std::shared_ptr< onert::exec::Execution > instance (void) noexcept
bool getOutputOperandRank (uint32_t index, uint32_t *rank) noexcept
Get output operand's rank.
bool getOutputOperandDimensions (uint32_t index, uint32_t *dimensions)
Get dimensions of the output operand.
Detailed Description
Definition at line 26 of file ANeuralNetworksExecution.h.
Constructor & Destructor Documentation
ANeuralNetworksExecution()
ANeuralNetworksExecution::ANeuralNetworksExecution (const std::shared_ptr< onert::exec::IExecutors > & executors) inline
Definition at line 29 of file ANeuralNetworksExecution.h.
    : _execution{std::make_shared<onert::exec::Execution>(executors)}
  {
    // DO NOTHING
  }
Member Function Documentation
compareDataType()
bool ANeuralNetworksExecution::compareDataType (const ANeuralNetworksOperandType * type, const onert::ir::OperandIndex index) noexcept
Definition at line 62 of file ANeuralNetworksExecution.cc.
{
  try
  {
    const auto operand_type = _execution->primary_subgraph().operands().at(index).typeInfo();
    const auto typeInfo = NNAPIConvert::getTypeInfo(type);
    if (operand_type != typeInfo)
    {
      // Data type mismatch
      return false;
    }
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References NNAPIConvert::getTypeInfo(), and VERBOSE.
Referenced by ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
compareShape()
bool ANeuralNetworksExecution::compareShape (const ANeuralNetworksOperandType * type, const onert::ir::OperandIndex index) noexcept
Definition at line 86 of file ANeuralNetworksExecution.cc.
{
  // Passed shape should be specified
  if (hasUnspecifiedDims(index))
  {
    return false;
  }
  const auto &operand_shape = _execution->primary_subgraph().operands().at(index).shape();
  const auto &shape_from_type = NNAPIConvert::getShape(type);
  return operand_shape == shape_from_type;
}
References NNAPIConvert::getShape().
Referenced by ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
execute()
bool ANeuralNetworksExecution::execute (void) noexcept
Definition at line 246 of file ANeuralNetworksExecution.cc.
{
  try
  {
    _execution->execute();
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
Referenced by ANeuralNetworksExecution_compute().
getInputOperandIndex()
const onert::ir::OperandIndex ANeuralNetworksExecution::getInputOperandIndex (int32_t index) noexcept
Definition at line 21 of file ANeuralNetworksExecution.cc.
{
  if (index < 0)
  {
    // Negative index: return invalid index
    return onert::ir::OperandIndex{};
  }
  uint32_t cast_index = static_cast<uint32_t>(index);
  if (cast_index >= _execution->primary_subgraph().getInputs().size())
  {
    // Return invalid index
    return onert::ir::OperandIndex{};
  }
  onert::ir::IOIndex input_index{cast_index};
  const auto operand_index = _execution->primary_subgraph().getInputs().at(input_index);
  return operand_index;
}
Referenced by ANeuralNetworksExecution_setInput(), and ANeuralNetworksExecution_setInputFromMemory().
getOperandSize()
size_t ANeuralNetworksExecution::getOperandSize (const onert::ir::OperandIndex index) noexcept
Definition at line 119 of file ANeuralNetworksExecution.cc.
{
  try
  {
    return _execution->primary_subgraph().operands().at(index).operandSize();
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return 0;
  }
}
References VERBOSE.
Referenced by ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
getOutputOperandDimensions()
bool ANeuralNetworksExecution::getOutputOperandDimensions (uint32_t index, uint32_t * dimensions)
Get dimensions of the output operand.
Parameters
[in] index Output index
[out] dimensions Output operand's dimensions
Returns
true if success to get rank, otherwise false
Note
This must be called after execution is finished to get resolved output shape unspecified in model
Definition at line 297 of file ANeuralNetworksExecution.cc.
{
  try
  {
    onert::ir::IOIndex output_index{index};
    // Check execution is finished
    if (!_execution->isFinished())
    {
      return false;
    }
    const auto shape = _execution->getOutputShape(output_index);
    if (shape.hasUnspecifiedDims())
    {
      throw std::runtime_error{"Internal error: Output tensor has unspecified dims"};
    }
    for (int i = 0; i < shape.rank(); i++)
    {
      auto dim = shape.dim(i);
      if (dim <= 0)
      {
        throw std::runtime_error{"Invalid dimension value"};
      }
      dimensions[i] = static_cast<uint32_t>(dim);
    }
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
Referenced by ANeuralNetworksExecution_getOutputOperandDimensions().
getOutputOperandIndex()
const onert::ir::OperandIndex ANeuralNetworksExecution::getOutputOperandIndex (int32_t index) noexcept
Definition at line 42 of file ANeuralNetworksExecution.cc.
{
  if (index < 0)
  {
    // Negative index: return invalid index
    return onert::ir::OperandIndex{};
  }
  uint32_t cast_index = static_cast<uint32_t>(index);
  if (cast_index >= _execution->primary_subgraph().getOutputs().size())
  {
    // Return invalid index
    return onert::ir::OperandIndex{};
  }
  onert::ir::IOIndex output_index{cast_index};
  const auto operand_index = _execution->primary_subgraph().getOutputs().at(output_index);
  return operand_index;
}
Referenced by ANeuralNetworksExecution_getOutputOperandDimensions(), ANeuralNetworksExecution_getOutputOperandRank(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
getOutputOperandRank()
bool ANeuralNetworksExecution::getOutputOperandRank (uint32_t index, uint32_t * rank) noexcept
Get output operand's rank.
Parameters
[in] index Output index
[out] rank Output operand's rank
Returns
true if success to get rank, otherwise false
Definition at line 267 of file ANeuralNetworksExecution.cc.
{
  try
  {
    onert::ir::IOIndex output_index{index};
    // Check execution is finished
    if (!_execution->isFinished())
    {
      return false;
    }
    const auto shape = _execution->getOutputShape(output_index);
    if (shape.hasUnspecifiedDims())
    {
      throw std::runtime_error{"Internal error: Output tensor has unspecified dims"};
    }
    *rank = shape.rank();
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
Referenced by ANeuralNetworksExecution_getOutputOperandRank().
hasUnspecifiedDims()
bool ANeuralNetworksExecution::hasUnspecifiedDims (const onert::ir::OperandIndex index) noexcept
Definition at line 112 of file ANeuralNetworksExecution.cc.
{
  const auto operand_shape = _execution->primary_subgraph().operands().at(index).shape();
  return operand_shape.hasUnspecifiedDims();
}
Referenced by ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
instance()
const std::shared_ptr< onert::exec::Execution > ANeuralNetworksExecution::instance (void) noexcept
Definition at line 262 of file ANeuralNetworksExecution.cc.
{
  return _execution;
}
Referenced by ANeuralNetworksExecution_startCompute().
IsOptionalInput()
bool ANeuralNetworksExecution::IsOptionalInput (const onert::ir::OperandIndex index) noexcept
Definition at line 101 of file ANeuralNetworksExecution.cc.
{
  const auto &operand_shape = _execution->primary_subgraph().operands().at(index).shape();
  for (int32_t i = 0; i < operand_shape.rank(); ++i)
  {
    if (operand_shape.dim(i) != 0)
      return false;
  }
  return true;
}
Referenced by ANeuralNetworksExecution_setInput().
setInput()
bool ANeuralNetworksExecution::setInput (uint32_t index, const ANeuralNetworksOperandType * type, const void * buffer, size_t length) noexcept
Definition at line 133 of file ANeuralNetworksExecution.cc.
{
  try
  {
    onert::ir::IOIndex input_index{index};
    const auto operand_index = getInputOperandIndex(index);
    const auto type_info = _execution->primary_subgraph().operands().at(operand_index).typeInfo();
    const auto shape = (type != nullptr)
                         ? NNAPIConvert::getShape(type)
                         : _execution->primary_subgraph().operands().at(operand_index).shape();
    // NOTE The nnapi does not provide setting io_layout and not support changing layout. In other
    // words, we can assume that io_layout from nnapi always is the same as layout of the used
    // model.
    // TODO Set layout of model
    _execution->setInput(input_index, type_info, shape, buffer, length, onert::ir::Layout::NHWC);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References NNAPIConvert::getShape(), onert::ir::NHWC, and VERBOSE.
Referenced by ANeuralNetworksExecution_setInput(), and ANeuralNetworksExecution_setInputFromMemory().
setOptionalInput()
bool ANeuralNetworksExecution::setOptionalInput (uint32_t index, const ANeuralNetworksOperandType * type, const void * buffer, size_t length) noexcept
Definition at line 162 of file ANeuralNetworksExecution.cc.
{
  assert(type == nullptr);
  assert(buffer == nullptr);
  assert(length == 0);
  try
  {
    onert::ir::IOIndex input_index{index};
    const auto operand_index = getInputOperandIndex(index);
    const auto type_info = _execution->primary_subgraph().operands().at(operand_index).typeInfo();
    const auto shape = (type != nullptr)
                         ? NNAPIConvert::getShape(type)
                         : _execution->primary_subgraph().operands().at(operand_index).shape();
    // ANeuralNetworksExecution::setInput() uses only shape information
    ANeuralNetworksOperandType optional_input_type;
    optional_input_type.dimensionCount = shape.rank();
    std::vector<uint32_t> dims(optional_input_type.dimensionCount);
    for (uint32_t i = 0; i < optional_input_type.dimensionCount; ++i)
    {
      dims.at(i) = shape.dim(i);
    }
    optional_input_type.dimensions = dims.data();
    return setInput(index, &optional_input_type, buffer, length);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References ANeuralNetworksOperandType::dimensionCount, ANeuralNetworksOperandType::dimensions, NNAPIConvert::getShape(), and VERBOSE.
Referenced by ANeuralNetworksExecution_setInput().
setOutput()
bool ANeuralNetworksExecution::setOutput (uint32_t index, const ANeuralNetworksOperandType * type, void * buffer, size_t length) noexcept
Definition at line 201 of file ANeuralNetworksExecution.cc.
{
  try
  {
    onert::ir::IOIndex output_index{index};
    const auto operand_index = getOutputOperandIndex(index);
    const auto type_info = _execution->primary_subgraph().operands().at(operand_index).typeInfo();
    const auto shape = (type != nullptr)
                         ? NNAPIConvert::getShape(type)
                         : _execution->primary_subgraph().operands().at(operand_index).shape();
    // NOTE The nnapi does not provide setting io_layout and not support changing layout. In other
    // words, we can assume that io_layout from nnapi always is the same as layout of the used
    // model.
    // TODO Set layout of model
    _execution->setOutput(output_index, type_info, shape, buffer, length, onert::ir::Layout::NHWC);
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References NNAPIConvert::getShape(), onert::ir::NHWC, and VERBOSE.
Referenced by ANeuralNetworksExecution_setOutput(), and ANeuralNetworksExecution_setOutputFromMemory().
startExecute()
bool ANeuralNetworksExecution::startExecute (void) noexcept
Definition at line 230 of file ANeuralNetworksExecution.cc.
{
  try
  {
    _execution->startExecute();
  }
  catch (const std::exception &e)
  {
    VERBOSE(EXCEPTION) << e.what() << std::endl;
    return false;
  }
  return true;
}
References VERBOSE.
Referenced by ANeuralNetworksExecution_startCompute().
The documentation for this struct was generated from the following files:
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.h
runtime/onert/frontend/nnapi/wrapper/ANeuralNetworksExecution.cc