ONE - On-device Neural Engine: mir_interpreter::ReduceMeanImpl< T > Struct Template Reference
mir_interpreter::ReduceMeanImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &inputv, const mir::ops::ReduceMeanOp &op, mir::TensorVariant &output)
Detailed Description
template<typename T>
struct mir_interpreter::ReduceMeanImpl< T >
Definition at line 30 of file ReduceMean.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::ReduceMeanImpl< T >::run (const mir::TensorVariant & inputv, const mir::ops::ReduceMeanOp & op, mir::TensorVariant & output) static
Definition at line 37 of file ReduceMean.cpp.
{
  const auto &input_shape = op.getInputShape(0);
  const auto &output_shape = op.getOutputShape(0);
  const auto &reduction_dims = op.getReductionDims();
  const bool keep_dims = op.getKeepDims();
  const auto reductor = [](T result, T x) { return result + x; };
  mir::Tensor<T> input(inputv);
  mir::Tensor<T> res_accessor(output);
  erase<T>(output);
  // This mask contains 'true' for dimensions that should be reduced. For example, if we want
  // to reduce dimensions 1 and 3 with total number of dimensions of 4, the mask will be
  // [false, true, false, true].
  std::vector<bool> reduction_dims_mask(input_shape.rank(), false);
  for (const int dim : reduction_dims)
  {
    reduction_dims_mask[dim] = true;
  }
  mir::Index out_index(output_shape.rank());
  for (const mir::Index &in_index : mir::ShapeRange(input_shape))
  {
    int out_index_dim = 0;
    for (int dim = 0; dim < input_shape.rank(); ++dim)
    {
      if (keep_dims)
      {
        out_index.at(out_index_dim++) = reduction_dims_mask[dim] ? 0 : in_index.at(dim);
      }
      else
      {
        if (!reduction_dims_mask[dim])
        {
          out_index.at(out_index_dim++) = in_index.at(dim);
        }
      }
    }
    res_accessor.at(out_index) = reductor(res_accessor.at(out_index), input.at(in_index));
  }
  const std::int32_t reduction_factor = input_shape.numElements() / output_shape.numElements();
  for (const auto &index : mir::ShapeRange(output_shape))
  {
    res_accessor.at(index) /= reduction_factor;
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::Operation::getInputShape(), mir::ops::ReduceOp::getKeepDims(), mir::Operation::getOutputShape(), and mir::ops::ReduceOp::getReductionDims().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/ReduceMean.cpp