ONE - On-device Neural Engine: mir_interpreter::GatherImpl< T, IndicesT > Struct Template Reference
mir_interpreter::GatherImpl< T, IndicesT > Struct Template Reference
Static Public Member Functions
static void run (const TensorVariant &datav, const TensorVariant &indicesv, const ops::GatherOp &op, mir::TensorVariant &res)
Detailed Description
template<typename T, typename IndicesT>
struct mir_interpreter::GatherImpl< T, IndicesT >
Definition at line 27 of file Gather.cpp.
Member Function Documentation
run()
template<typename T , typename IndicesT > void mir_interpreter::GatherImpl< T, IndicesT >::run (const TensorVariant & datav, const TensorVariant & indicesv, const ops::GatherOp & op, mir::TensorVariant & res) static
Definition at line 34 of file Gather.cpp.
{
  const auto &data_shape = datav.getShape();
  const auto &indices_shape = indicesv.getShape();
  Tensor<T> data(datav);
  Tensor<T> output(res);
  Tensor<IndicesT> indices(indicesv);
  int32_t axis = op.getAxis();
  if (axis < 0)
    axis += data_shape.rank();
  assert(axis >= 0 && axis < data_shape.rank());
  int32_t axis_size = data_shape.dim(axis);
  int32_t num_indices = indices_shape.numElements();
  int32_t outer_size = 1;
  for (int32_t i = 0; i < axis; ++i)
    outer_size *= data_shape.dim(i);
  int32_t inner_size = 1;
  for (int32_t i = axis + 1; i < data_shape.rank(); ++i)
    inner_size *= data_shape.dim(i);
  for (int32_t outer = 0; outer < outer_size; ++outer)
  {
    for (int32_t i = 0; i < num_indices; ++i)
    {
      auto index = indices.atOffset(i);
      assert(index >= 0 && index < axis_size);
      for (int32_t inner = 0; inner < inner_size; inner++)
      {
        output.atOffset((outer * num_indices + i) * inner_size + inner) =
          data.atOffset((outer * axis_size + index) * inner_size + inner);
      }
    }
  }
}
References mir::Tensor< T >::atOffset(), mir::ops::GatherOp::getAxis(), and mir::TensorVariant::getShape().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Gather.cpp