ONE - On-device Neural Engine: rua::CompilationService Struct Reference
rua::CompilationService Struct Reference abstract
A wrapper for ANeuralNetworkCompilation API.
#include <Service.h>
Public Member Functions
virtual ~CompilationService ()=default
virtual int create (ANeuralNetworksModel *model, ANeuralNetworksCompilation **compilation) const =0
virtual int setPreference (ANeuralNetworksCompilation *compilation, int32_t preference) const =0
virtual int finish (ANeuralNetworksCompilation *compilation) const =0
virtual void free (ANeuralNetworksCompilation *compilation) const =0
Detailed Description
A wrapper for ANeuralNetworkCompilation API.
Definition at line 87 of file Service.h.
Constructor & Destructor Documentation
~CompilationService()
virtual rua::CompilationService::~CompilationService () virtual default
Member Function Documentation
create()
virtual int rua::CompilationService::create (ANeuralNetworksModel * model, ANeuralNetworksCompilation ** compilation) const pure virtual
Referenced by ANeuralNetworksCompilation_create().
finish()
virtual int rua::CompilationService::finish (ANeuralNetworksCompilation * compilation) const pure virtual
Referenced by ANeuralNetworksCompilation_finish().
free()
virtual void rua::CompilationService::free (ANeuralNetworksCompilation * compilation) const pure virtual
Referenced by ANeuralNetworksCompilation_free().
setPreference()
virtual int rua::CompilationService::setPreference (ANeuralNetworksCompilation * compilation, int32_t preference) const pure virtual
Referenced by ANeuralNetworksCompilation_setPreference().
The documentation for this struct was generated from the following file:
runtime/libs/rua/core/include/rua/Service.h