ONE - On-device Neural Engine: onert::ir::IOperation Struct Reference
onert::ir::IOperation Struct Reference abstract
#include <IOperation.h>
Public Member Functions
virtual ~IOperation ()=default
virtual void accept (OperationVisitor &v) const =0
virtual std::string name () const
virtual OpCode opcode () const =0
virtual void replaceInputs (const OperandIndex &from, const OperandIndex &to)=0
virtual void replaceOutputs (const OperandIndex &from, const OperandIndex &to)=0
virtual const OperandIndexSequence & getInputs () const =0
virtual const OperandIndexSequence & getOutputs () const =0
Detailed Description
Definition at line 33 of file IOperation.h.
Constructor & Destructor Documentation
~IOperation()
virtual onert::ir::IOperation::~IOperation () virtual default
Member Function Documentation
accept()
virtual void onert::ir::IOperation::accept (OperationVisitor & v) const pure virtual
Implemented in onert_test::ir::SimpleMock, onert::ir::operation::AddN, onert::ir::operation::ArgMinMax, onert::ir::operation::BatchMatMul, onert::ir::operation::BatchToSpaceND, onert::ir::operation::BCQFullyConnected, onert::ir::operation::BCQGather, onert::ir::operation::BinaryArithmetic, onert::ir::operation::BroadcastTo, onert::ir::operation::Bulk, onert::ir::operation::Comparison, onert::ir::operation::Concat, onert::ir::operation::Conv2D, onert::ir::operation::ConvertFp16ToFp32, onert::ir::operation::ConvertFp32ToFp16, onert::ir::operation::Custom, onert::ir::operation::DepthToSpace, onert::ir::operation::DepthwiseConv2D, onert::ir::operation::DetectionPostProcess, onert::ir::operation::Einsum, onert::ir::operation::ElementwiseActivation, onert::ir::operation::ElementwiseBinary, onert::ir::operation::ElementwiseUnary, onert::ir::operation::EmbeddingLookup, onert::ir::operation::ExpandDims, onert::ir::operation::Fill, onert::ir::operation::FullyConnected, onert::ir::operation::FusedBatchNorm, onert::ir::operation::Gather, onert::ir::operation::HashtableLookup, onert::ir::operation::If, onert::ir::operation::InstanceNorm, onert::ir::operation::L2Normalization, onert::ir::operation::LocalResponseNormalization, onert::ir::operation::LogSoftmax, onert::ir::operation::Loss, onert::ir::operation::LSTM, onert::ir::operation::MatrixBandPart, onert::ir::operation::OneHot, onert::ir::operation::Pack, onert::ir::operation::Pad, onert::ir::operation::Permute, onert::ir::operation::Pool2D, onert::ir::operation::Pow, onert::ir::operation::PReLU, onert::ir::operation::Range, onert::ir::operation::Rank, onert::ir::operation::Reduce, onert::ir::operation::Reshape, onert::ir::operation::ResizeBilinear, onert::ir::operation::ResizeNearestNeighbor, onert::ir::operation::Reverse, onert::ir::operation::RNN, onert::ir::operation::Select, onert::ir::operation::Shape, onert::ir::operation::Slice, onert::ir::operation::Softmax, onert::ir::operation::SpaceToBatchND, onert::ir::operation::SpaceToDepth, onert::ir::operation::Split, onert::ir::operation::SplitV, onert::ir::operation::SquaredDifference, onert::ir::operation::Squeeze, onert::ir::operation::StatelessRandomUniform, onert::ir::operation::StridedSlice, onert::ir::operation::Tile, onert::ir::operation::TopKV2, onert::ir::operation::Transpose, onert::ir::operation::TransposeConv, onert::ir::operation::Unpack, onert::ir::operation::While, onert::ir::train::operation::BinaryArithmetic, onert::ir::train::operation::Conv2D, onert::ir::train::operation::DepthwiseConv2D, onert::ir::train::operation::ElementwiseActivation, onert::ir::train::operation::FullyConnected, onert::ir::train::operation::Loss, onert::ir::train::operation::Pad, onert::ir::train::operation::Permute, onert::ir::train::operation::Pool2D, onert::ir::train::operation::Reduce, onert::ir::train::operation::Reshape, onert::ir::train::operation::Softmax, onert::ir::train::operation::UntrainableOperation< OperationType, typename >, and onert::ir::train::ITrainableOperation.
Referenced by onert::compiler::pass::PermutationEliminationPass::callback(), onert::compiler::pass::PermutationOperationPass::callback(), onert::ir::clone(), onert::compiler::Compiler::compile(), onert::compiler::MultiModelCompiler::compile(), onert::compiler::train::TrainingCompiler::compile(), onert::backend::cl_common::BackendContext< T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator >::initConsts(), onert::compiler::ShapeValidator::operator()(), onert::ir::OperationValidator::operator()(), onert::compiler::train::UntrainableOperationConverter::operator()(), onert::backend::acl_cl::Optimizer::optimize(), and onert::backend::acl_neon::Optimizer::optimize().
getInputs()
virtual const OperandIndexSequence & onert::ir::IOperation::getInputs () const pure virtual
Implemented in onert::ir::Operation.
Referenced by onert::ir::train::TrainableGraph::btopolSortOperations(), onert::compiler::pass::ConstantInsertionPass::callback(), onert::compiler::pass::ConstantLoweringPass::callback(), onert::exec::DataflowExecutor::DataflowExecutor(), onert::dumper::text::formatOperation(), onert::ir::Graph::replaceOperation(), onert::compiler::pass::UnusedOperandEliminationPass::run(), and onert::ir::verifier::EdgeChecker::verify().
getOutputs()
virtual const OperandIndexSequence & onert::ir::IOperation::getOutputs () const pure virtual
Implemented in onert::ir::Operation.
Referenced by onert::compiler::pass::ConstantInsertionPass::callback(), onert::compiler::StaticShapeInferer::createStaticShapeInferers(), onert::exec::DataflowExecutor::DataflowExecutor(), onert::dumper::text::formatOperation(), onert::ir::Graph::replaceOperation(), onert::compiler::pass::UnusedOperandEliminationPass::run(), and onert::ir::verifier::EdgeChecker::verify().
name()
virtual std::string onert::ir::IOperation::name () const inline virtual
Reimplemented in onert::ir::operation::BinaryArithmetic, onert::ir::operation::Custom, onert::ir::operation::ElementwiseActivation, onert::ir::operation::ElementwiseBinary, onert::ir::operation::ElementwiseUnary, onert::ir::operation::LSTM, onert::ir::operation::Pool2D, onert::ir::operation::Reduce, and onert::ir::train::operation::Loss.
Definition at line 38 of file IOperation.h.
{ return std::string{toString(opcode())}; }
References opcode(), and onert::ir::toString().
Referenced by onert::dumper::text::formatOperation(), onert::exec::TracingObserver::handleJobBegin(), onert::compiler::train::StaticBackwardShapeInferer::infer(), onert::ir::operation::LSTM::name(), onert::dumper::dot::Operation::Operation(), onert::ir::train::TrainableGraph::verify(), and onert::ir::OperationDumper::visit().
opcode()
virtual OpCode onert::ir::IOperation::opcode () const pure virtual
Implemented in onert::ir::operation::AddN, onert::ir::operation::ArgMinMax, onert::ir::operation::BatchMatMul, onert::ir::operation::BatchToSpaceND, onert::ir::operation::BCQFullyConnected, onert::ir::operation::BCQGather, onert::ir::operation::BinaryArithmetic, onert::ir::operation::BroadcastTo, onert::ir::operation::Bulk, onert::ir::operation::Comparison, onert::ir::operation::Concat, onert::ir::operation::Conv2D, onert::ir::operation::ConvertFp16ToFp32, onert::ir::operation::ConvertFp32ToFp16, onert::ir::operation::Custom, onert::ir::operation::DepthToSpace, onert::ir::operation::DepthwiseConv2D, onert::ir::operation::DetectionPostProcess, onert::ir::operation::Einsum, onert::ir::operation::ElementwiseActivation, onert::ir::operation::ElementwiseBinary, onert::ir::operation::ElementwiseUnary, onert::ir::operation::EmbeddingLookup, onert::ir::operation::ExpandDims, onert::ir::operation::Fill, onert::ir::operation::FullyConnected, onert::ir::operation::FusedBatchNorm, onert::ir::operation::Gather, onert::ir::operation::HashtableLookup, onert::ir::operation::If, onert::ir::operation::InstanceNorm, onert::ir::operation::L2Normalization, onert::ir::operation::LocalResponseNormalization, onert::ir::operation::LogSoftmax, onert::ir::operation::Loss, onert::ir::operation::LSTM, onert::ir::operation::MatrixBandPart, onert::ir::operation::OneHot, onert::ir::operation::Pack, onert::ir::operation::Pad, onert::ir::operation::Permute, onert::ir::operation::Pool2D, onert::ir::operation::Pow, onert::ir::operation::PReLU, onert::ir::operation::Range, onert::ir::operation::Rank, onert::ir::operation::Reduce, onert::ir::operation::Reshape, onert::ir::operation::ResizeBilinear, onert::ir::operation::ResizeNearestNeighbor, onert::ir::operation::Reverse, onert::ir::operation::RNN, onert::ir::operation::Select, onert::ir::operation::Shape, onert::ir::operation::Slice, onert::ir::operation::Softmax, onert::ir::operation::SpaceToBatchND, onert::ir::operation::SpaceToDepth, onert::ir::operation::Split, onert::ir::operation::SplitV, onert::ir::operation::SquaredDifference, onert::ir::operation::Squeeze, onert::ir::operation::StatelessRandomUniform, onert::ir::operation::StridedSlice, onert::ir::operation::Tile, onert::ir::operation::TopKV2, onert::ir::operation::Transpose, onert::ir::operation::TransposeConv, onert::ir::operation::Unpack, onert::ir::operation::While, and onert_test::ir::SimpleMock.
Referenced by onert::ir::train::TrainableGraph::btopolSortOperations(), onert::compiler::StaticShapeInferer::createStaticShapeInferers(), name(), and onert::compiler::ManualScheduler::schedule().
replaceInputs()
virtual void onert::ir::IOperation::replaceInputs (const OperandIndex & from, const OperandIndex & to) pure virtual
Implemented in onert::ir::Operation.
Referenced by onert::compiler::pass::ConstantInsertionPass::callback().
replaceOutputs()
virtual void onert::ir::IOperation::replaceOutputs (const OperandIndex & from, const OperandIndex & to) pure virtual
Implemented in onert::ir::Operation.
The documentation for this struct was generated from the following file:
runtime/onert/core/include/ir/IOperation.h