ONE - On-device Neural Engine: mir_interpreter::CappedReLUImpl< uint8_t > Struct Reference
mir_interpreter::CappedReLUImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const mir::TensorVariant &arg, float cap, mir::TensorVariant &result)
Detailed Description
Definition at line 57 of file CappedReLU.cpp.
Member Function Documentation
run()
static void mir_interpreter::CappedReLUImpl< uint8_t >::run (const mir::TensorVariant & arg, float cap, mir::TensorVariant & result) inline static
Definition at line 59 of file CappedReLU.cpp.
  {
    mir::Tensor<uint8_t> arg_accessor(arg);
    mir::Tensor<uint8_t> res_accessor(result);
    auto quant_info = arg.getType().getQuantization();
    assert(!quant_info.empty());
    for (const auto &index : mir::ShapeRange(result.getShape()))
    {
      auto value = dequantize(arg_accessor.at(index), quant_info);
      auto out_value =
        quantize(std::min(std::max(value, 0.0f), cap), result.getType().getQuantization());
      res_accessor.at(index) = out_value;
    }
  }
References mir::Tensor< T >::at(), mir::TensorType::getQuantization(), mir::TensorVariant::getShape(), and mir::TensorVariant::getType().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/CappedReLU.cpp