ONE - On-device Neural Engine: onert_micro::import::OMDynamicShapesHandler Struct Reference
onert_micro::import::OMDynamicShapesHandler Struct Reference
#include <OMDynamicShapesHandler.h>
Static Public Member Functions
static OMStatus importDynamicShapesFromTrainConfig (core::OMRuntimeStorage &storage, core::OMRuntimeContext &context, core::train::OMTrainingStorage &train_storage)
Detailed Description
Definition at line 34 of file OMDynamicShapesHandler.h.
Member Function Documentation
importDynamicShapesFromTrainConfig()
OMStatus OMDynamicShapesHandler::importDynamicShapesFromTrainConfig (core::OMRuntimeStorage & storage, core::OMRuntimeContext & context, core::train::OMTrainingStorage & train_storage) static
Definition at line 77 of file OMDynamicShapesHandler.cpp.
{
  std::unordered_map<uint16_t, uint8_t> train_op_indexes_to_train_rank =
    context.getTrainableOpsIndexes();
  const auto opcodes = context.getCircleOpcodes();
  // Goes over pairs of op index and train rank value
  for (auto &p : train_op_indexes_to_train_rank)
  {
    const uint16_t op_index = p.first;
    const auto train_rank = static_cast<OpTrainableRankType>(p.second);
    switch (train_rank)
    {
      case core::LOWER_1_2_PART:
      case core::UP_1_2_PART:
      {
        const auto cur_op = context.getCircleOperatorAt(op_index);
        const auto opcode = opcodes->operator[](cur_op->opcode_index());
        int32_t res_index = getWeightTensorIndexForOperatorWithOpcode(opcode);
        // The operation doesn't support such behaviour
        if (res_index == -1)
          continue;
        auto tensor_local_index = static_cast<uint16_t>(res_index);
        auto tensor_index = cur_op->inputs()->operator[](tensor_local_index);
        auto tensor = context.getTensorByIndex(tensor_index);
        OMRuntimeShape old_shape(tensor);
        const float partition_size = 2.f;
        OMRuntimeShape new_shape =
          createDynamicRuntimeShapeForOperator(old_shape, opcode, partition_size);
        storage.setDynamicRuntimeShape(tensor_index, new_shape);
        train_storage.addTrainRank(tensor_index, train_rank);
        break;
      }
      default:
        continue;
    }
  }
  return Ok;
}
References onert_micro::core::train::OMTrainingStorage::addTrainRank(), onert_micro::core::OMRuntimeContext::getCircleOpcodes(), onert_micro::core::OMRuntimeContext::getCircleOperatorAt(), onert_micro::core::OMRuntimeContext::getTensorByIndex(), onert_micro::core::OMRuntimeContext::getTrainableOpsIndexes(), onert_micro::core::LOWER_1_2_PART, onert_micro::Ok, p, onert_micro::core::OMRuntimeStorage::setDynamicRuntimeShape(), and onert_micro::core::UP_1_2_PART.
Referenced by onert_micro::core::OMTrainingRuntimeModule::importTrainModel().
The documentation for this struct was generated from the following files:
onert-micro/onert-micro/include/import/OMDynamicShapesHandler.h
onert-micro/onert-micro/src/import/OMDynamicShapesHandler.cpp