ONE - On-device Neural Engine: OpPrinter Struct Reference
OpPrinter Struct Reference final
Public Member Functions
OpPrinter (std::ostream &os, int indent)
void visit (const coco::Load *op) override
void visit (const coco::PadF *op) override
void visit (const coco::Conv2D *op) override
void visit (const coco::MaxPool2D *op) override
void visit (const coco::AvgPool2D *op) override
void visit (const coco::Add *op) override
void visit (const coco::Mul *op) override
void visit (const coco::ReLU *op) override
void visit (const coco::ReLU6 *op) override
void visit (const coco::Sub *op) override
void visit (const coco::ConcatF *op) override
void visit (const coco::Div *op) override
Public Member Functions inherited from coco::Op::Visitor< T >
virtual ~Visitor ()=default
Public Member Functions inherited from coco::Op::IVisitor< T >
virtual ~IVisitor ()=default
Detailed Description
Definition at line 40 of file Dump.cpp.
Constructor & Destructor Documentation
OpPrinter()
OpPrinter::OpPrinter (std::ostream & os, int indent) inline
Definition at line 43 of file Dump.cpp.
: _os(os), _indent(indent) {}
Member Function Documentation
visit() [1/12]
void OpPrinter::visit (const coco::Add * op) inline override
Definition at line 83 of file Dump.cpp.
  {
    op->left()->accept(this);
    op->right()->accept(this);
    _os << tab(_indent) << "Add" << std::endl;
  }
References coco::Op::accept(), coco::BinaryOp::left(), coco::BinaryOp::right(), and tab().
visit() [2/12]
void OpPrinter::visit (const coco::AvgPool2D * op) inline override
Definition at line 77 of file Dump.cpp.
  {
    op->arg()->accept(this);
    _os << tab(_indent) << "AvgPool2D" << std::endl;
  }
References coco::Op::accept(), coco::UnaryOp::arg(), and tab().
visit() [3/12]
void OpPrinter::visit (const coco::ConcatF * op) inline override
Definition at line 116 of file Dump.cpp.
  {
    op->left()->accept(this);
    op->right()->accept(this);
    _os << tab(_indent) << "ConcatF" << std::endl;
  }
References coco::Op::accept(), coco::BinaryOp::left(), coco::BinaryOp::right(), and tab().
visit() [4/12]
void OpPrinter::visit (const coco::Conv2D * op) inline override
Definition at line 58 of file Dump.cpp.
  {
    op->arg()->accept(this);
    const coco::Padding2D *pad = op->pad();
    const coco::Stride2D *stride = op->stride();
    _os << tab(_indent) << "Conv2D(" << dynamic_cast<const coco::Op *>(op)
        << ", ker obj: " << op->ker() << ", padding [T/B/L/R=" << pad->top() << "," << pad->bottom()
        << "," << pad->left() << "," << pad->right() << "]"
        << ", stride [V/H = " << stride->vertical() << "," << stride->horizontal() << "]"
        << ")" << std::endl;
  }
References coco::Op::accept(), coco::Conv2D::arg(), coco::Padding2D::bottom(), coco::Stride2D::horizontal(), coco::Conv2D::ker(), coco::Padding2D::left(), coco::Conv2D::pad(), coco::Padding2D::right(), coco::Conv2D::stride(), tab(), coco::Padding2D::top(), and coco::Stride2D::vertical().
visit() [5/12]
void OpPrinter::visit (const coco::Div * op) inline override
Definition at line 123 of file Dump.cpp.
  {
    op->left()->accept(this);
    op->right()->accept(this);
    _os << tab(_indent) << "Div" << std::endl;
  }
References coco::Op::accept(), coco::BinaryOp::left(), coco::BinaryOp::right(), and tab().
visit() [6/12]
void OpPrinter::visit (const coco::Load * op) inline override
Definition at line 46 of file Dump.cpp.
  {
    _os << tab(_indent) << "Load(" << dynamic_cast<const coco::Op *>(op)
        << ", obj: " << op->object() << ")" << std::endl;
  }
References coco::Load::object(), and tab().
visit() [7/12]
void OpPrinter::visit (const coco::MaxPool2D * op) inline override
Definition at line 71 of file Dump.cpp.
  {
    op->arg()->accept(this);
    _os << tab(_indent) << "MaxPool2D" << std::endl;
  }
References coco::Op::accept(), coco::UnaryOp::arg(), and tab().
visit() [8/12]
void OpPrinter::visit (const coco::Mul * op) inline override
Definition at line 90 of file Dump.cpp.
  {
    op->left()->accept(this);
    op->right()->accept(this);
    _os << tab(_indent) << "Mul" << std::endl;
  }
References coco::Op::accept(), coco::BinaryOp::left(), coco::BinaryOp::right(), and tab().
visit() [9/12]
void OpPrinter::visit (const coco::PadF * op) inline override
Definition at line 52 of file Dump.cpp.
  {
    op->arg()->accept(this);
    _os << tab(_indent) << "PadF" << std::endl;
  }
References coco::Op::accept(), coco::UnaryOp::arg(), and tab().
visit() [10/12]
void OpPrinter::visit (const coco::ReLU * op) inline override
Definition at line 97 of file Dump.cpp.
  {
    op->arg()->accept(this);
    _os << tab(_indent) << "ReLU" << std::endl;
  }
References coco::Op::accept(), coco::UnaryOp::arg(), and tab().
visit() [11/12]
void OpPrinter::visit (const coco::ReLU6 * op) inline override
Definition at line 103 of file Dump.cpp.
  {
    op->arg()->accept(this);
    _os << tab(_indent) << "ReLU6" << std::endl;
  }
References coco::Op::accept(), coco::UnaryOp::arg(), and tab().
visit() [12/12]
void OpPrinter::visit (const coco::Sub * op) inline override
Definition at line 109 of file Dump.cpp.
  {
    op->left()->accept(this);
    op->right()->accept(this);
    _os << tab(_indent) << "Sub" << std::endl;
  }
References coco::Op::accept(), coco::BinaryOp::left(), coco::BinaryOp::right(), and tab().
The documentation for this struct was generated from the following file:
compiler/encodump/src/Dump.cpp