ONE - On-device Neural Engine: mir_interpreter::AvgPool2DImpl< uint8_t > Struct Reference
mir_interpreter::AvgPool2DImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const mir::ops::AvgPool2DOp &op, const mir::TensorVariant &input, mir::TensorVariant &output)
Detailed Description
Definition at line 93 of file AvgPool2D.cpp.
Member Function Documentation
run()
void mir_interpreter::AvgPool2DImpl< uint8_t >::run (const mir::ops::AvgPool2DOp & op, const mir::TensorVariant & input, mir::TensorVariant & output) static
Definition at line 99 of file AvgPool2D.cpp.
{
  const auto &input_type = input.getType();
  const auto &output_type = op.getOutput(0)->getType();
  (void)input_type;
  assert(input_type.isQuantized());
  assert(output_type.isQuantized());
  assert(input_type.getElementType() == DataType::UINT8);
  const auto &input_shape = op.getInputShape(0);
  const auto &output_shape = op.getOutputShape(0);
  const auto &window_size = op.getWindowSize();
  const auto &strides = op.getStrides();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  (void)padding_after;
  constexpr int num_spatial_dims = 2;
  assert(input.getShape().rank() == 4);
  assert(window_size.size() == num_spatial_dims);
  assert(strides.size() == num_spatial_dims);
  assert(padding_before.size() == num_spatial_dims);
  assert(padding_after.size() == num_spatial_dims);
  Tensor<uint8_t> input_accessor(input);
  Tensor<uint8_t> res_accessor(output);
  ShapeRange in_range(input_shape);
  Index in_index(input_shape.rank());
  int32_t output_min = std::numeric_limits<uint8_t>::min();
  int32_t output_max = std::numeric_limits<uint8_t>::max();
  for (const auto &out_index : ShapeRange(output_shape))
  {
    int32_t result = 0;
    size_t num_elements = 0;
    // Assuming NHWC format.
    in_index.at(0) = out_index.at(0);
    in_index.at(3) = out_index.at(3);
    for (const auto &window_index : ShapeRange(Shape(window_size)))
    {
      // Assuming NHWC format.
      for (int i = 0; i < num_spatial_dims; ++i)
        in_index.at(1 + i) =
          out_index.at(1 + i) * strides[i] + window_index.at(i) - padding_before[i];
      if (in_range.contains(in_index))
      {
        num_elements++;
        result += input_accessor.at(in_index);
      }
      else if (op.getIncludePad())
      {
        num_elements++;
      }
    }
    result = (result + num_elements / 2) / num_elements;
    result = std::max(result, output_min);
    result = std::min(result, output_max);
    res_accessor.at(out_index) = static_cast<uint8_t>(result);
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::ShapeRange::contains(), mir::ops::AvgPool2DOp::getIncludePad(), mir::Operation::getInputShape(), mir::Operation::getOutput(), mir::Operation::getOutputShape(), mir::ops::AvgPool2DOp::getPaddingAfter(), mir::ops::AvgPool2DOp::getPaddingBefore(), mir::ops::AvgPool2DOp::getStrides(), mir::Operation::Output::getType(), and mir::ops::AvgPool2DOp::getWindowSize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/AvgPool2D.cpp