ONE - On-device Neural Engine: flatbuffers::IterationVisitor Struct Reference
flatbuffers::IterationVisitor Struct Reference
#include <minireflect.h>
Public Member Functions
virtual void StartSequence ()
virtual void EndSequence ()
virtual void Field (size_t, size_t, ElementaryType, bool, const TypeTable *, const char *, const uint8_t *)
virtual void UType (uint8_t, const char *)
virtual void Bool (bool)
virtual void Char (int8_t, const char *)
virtual void UChar (uint8_t, const char *)
virtual void Short (int16_t, const char *)
virtual void UShort (uint16_t, const char *)
virtual void Int (int32_t, const char *)
virtual void UInt (uint32_t, const char *)
virtual void Long (int64_t)
virtual void ULong (uint64_t)
virtual void Float (float)
virtual void Double (double)
virtual void String (const String *)
virtual void Unknown (const uint8_t *)
virtual void StartVector ()
virtual void EndVector ()
virtual void Element (size_t, ElementaryType, const TypeTable *, const uint8_t *)
virtual ~IterationVisitor ()
Detailed Description
Definition at line 39 of file minireflect.h.
Constructor & Destructor Documentation
~IterationVisitor()
virtual flatbuffers::IterationVisitor::~IterationVisitor () inline virtual
Definition at line 74 of file minireflect.h.
{}
Member Function Documentation
Bool()
virtual void flatbuffers::IterationVisitor::Bool (bool) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 54 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Char()
virtual void flatbuffers::IterationVisitor::Char (int8_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 55 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Double()
virtual void flatbuffers::IterationVisitor::Double (double) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 64 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Element()
virtual void flatbuffers::IterationVisitor::Element (size_t , ElementaryType , const TypeTable * , const uint8_t *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 70 of file minireflect.h.
  {
  }
Referenced by flatbuffers::IterateObject().
EndSequence()
virtual void flatbuffers::IterationVisitor::EndSequence () inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 43 of file minireflect.h.
{}
Referenced by flatbuffers::IterateObject().
EndVector()
virtual void flatbuffers::IterationVisitor::EndVector () inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 69 of file minireflect.h.
{}
Referenced by flatbuffers::IterateObject().
Field()
virtual void flatbuffers::IterationVisitor::Field (size_t , size_t , ElementaryType , bool , const TypeTable * , const char * , const uint8_t *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 46 of file minireflect.h.
  {
  }
Referenced by flatbuffers::IterateObject().
Float()
virtual void flatbuffers::IterationVisitor::Float (float) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 63 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Int()
virtual void flatbuffers::IterationVisitor::Int (int32_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 59 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Long()
virtual void flatbuffers::IterationVisitor::Long (int64_t) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 61 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Short()
virtual void flatbuffers::IterationVisitor::Short (int16_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 57 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
StartSequence()
virtual void flatbuffers::IterationVisitor::StartSequence () inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 42 of file minireflect.h.
{}
Referenced by flatbuffers::IterateObject().
StartVector()
virtual void flatbuffers::IterationVisitor::StartVector () inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 68 of file minireflect.h.
{}
Referenced by flatbuffers::IterateObject().
String()
virtual void flatbuffers::IterationVisitor::String (const String *) inline virtual
Definition at line 65 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
UChar()
virtual void flatbuffers::IterationVisitor::UChar (uint8_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 56 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
UInt()
virtual void flatbuffers::IterationVisitor::UInt (uint32_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 60 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
ULong()
virtual void flatbuffers::IterationVisitor::ULong (uint64_t) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 62 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
Unknown()
virtual void flatbuffers::IterationVisitor::Unknown (const uint8_t *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 66 of file minireflect.h.
{} // From a future version.
Referenced by flatbuffers::IterateValue().
UShort()
virtual void flatbuffers::IterationVisitor::UShort (uint16_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 58 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
UType()
virtual void flatbuffers::IterationVisitor::UType (uint8_t , const char *) inline virtual
Reimplemented in flatbuffers::ToStringVisitor.
Definition at line 53 of file minireflect.h.
{}
Referenced by flatbuffers::IterateValue().
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/minireflect.h