ONE - On-device Neural Engine: loco::ShapeInferenceRule Struct Reference
loco::ShapeInferenceRule Struct Reference abstract
#include <ShapeInferenceRule.h>
Data Structures
struct Context
struct Sink
Public Types
enum class API { V1 , V2 }
Public Member Functions
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Detailed Description
Definition at line 28 of file ShapeInferenceRule.h.
Member Enumeration Documentation
API
enum class loco::ShapeInferenceRule::API strong
Enumerator
V1
API v1
This API uses "shape_get" method to query the shape of other nodes.
V2
API v2
This API uses a given context (defined below) to query the shape of other nodes.
Definition at line 32 of file ShapeInferenceRule.h.
  {
    V1,
    V2,
  };
Constructor & Destructor Documentation
~ShapeInferenceRule()
virtual loco::ShapeInferenceRule::~ShapeInferenceRule () virtual default
Member Function Documentation
infer() [1/2]
void loco::ShapeInferenceRule::infer (const Context * , const Node * , Sink *) const virtual
Reimplemented in moco::TFShapeInferenceRule, and loco::CanonicalShapeInferenceRule.
Definition at line 26 of file ShapeInferenceRule.cpp.
{
  throw std::runtime_error{"API v2 is not supported"};
}
infer() [2/2]
virtual bool loco::ShapeInferenceRule::infer (const Node * , NodeShape &) const pure virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implemented in locoex::CircleShapeInferenceRule, locoex::TFLShapeInferenceRule, locoex::COpShapeInferenceRule, luci::CircleShapeInferenceRule, moco::TFShapeInferenceRule, loco::CanonicalShapeInferenceRule, and loco::MultiDialectShapeInferenceRule.
Referenced by loco::ShapeInferenceSession::to().
recognize()
virtual bool loco::ShapeInferenceRule::recognize (const Dialect *) const pure virtual
Return true if this rule recognizes a given dialect.
Implemented in loco::CanonicalShapeInferenceRule, loco::MultiDialectShapeInferenceRule, locoex::CircleShapeInferenceRule, locoex::TFLShapeInferenceRule, locoex::COpShapeInferenceRule, luci::CircleShapeInferenceRule, and moco::TFShapeInferenceRule.
Referenced by loco::MultiDialectShapeInferenceRule::bind(), and loco::ShapeInferenceSession::to().
support()
virtual bool loco::ShapeInferenceRule::support (const API & api) const inline virtual
Check whether a given API is available or not.
Reimplemented in loco::CanonicalShapeInferenceRule, and moco::TFShapeInferenceRule.
Definition at line 50 of file ShapeInferenceRule.h.
  {
    // To be backward compatible
    return api == API::V1;
  }
References V1.
Referenced by loco::ShapeInferenceSession::to().
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/Service/ShapeInferenceRule.h
compiler/loco/src/Service/ShapeInferenceRule.cpp