ONE - On-device Neural Engine: luci::FuseInstanceNormPass Struct Reference
luci::FuseInstanceNormPass Struct Reference final
Class to fuse certain pattern of subgraph into CircleInstanceNorm with auxiliary nodes.
#include <FuseInstanceNormPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
Detailed Description
Class to fuse certain pattern of subgraph into CircleInstanceNorm with auxiliary nodes.
For detailed subgraph pattern to be fused, please check its implementation.
Definition at line 31 of file FuseInstanceNormPass.h.
Member Function Documentation
name()
const char * luci::FuseInstanceNormPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 33 of file FuseInstanceNormPass.h.
{ return "luci::FuseInstanceNormPass"; }
run()
bool luci::FuseInstanceNormPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 1271 of file FuseInstanceNormPass.cpp.
{
  bool changed = false;
  // Check Version_1, Version_2, Version_3, Version_5, Version_6
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto add = dynamic_cast<luci::CircleAdd *>(node);
    if (not add)
      continue;
    if (fuse_instance_norm(add))
      changed = true;
  }
  // Check Version_4(from DIV) if MUL-ADD pattern is not found
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto div = dynamic_cast<luci::CircleDiv *>(node);
    if (not div)
      continue;
    if (fuse_instance_norm(div))
      changed = true;
  }
  // Post processing of FuseInstanceNorm
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto inst_norm = dynamic_cast<luci::CircleInstanceNorm *>(node);
    if (not inst_norm)
      continue;
    if (post_fusion(inst_norm))
      changed = true;
  }
  return changed;
}
References loco::active_nodes(), luci::must_cast(), and loco::output_nodes().
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/FuseInstanceNormPass.h
compiler/luci/pass/src/FuseInstanceNormPass.cpp