ONE - On-device Neural Engine: luci::CircleNodeOrigin::Source Struct Reference
luci::CircleNodeOrigin::Source Struct Reference
#include <CircleNodeOrigin.h>
Public Member Functions
std::string name (void) const
void name (const std::string &name)
uint32_t id (void) const
void id (const uint32_t id)
Detailed Description
Definition at line 32 of file CircleNodeOrigin.h.
Member Function Documentation
id() [1/2]
void luci::CircleNodeOrigin::Source::id (const uint32_t id) inline
Definition at line 39 of file CircleNodeOrigin.h.
{ _id = id; }
References id().
Referenced by id().
id() [2/2]
uint32_t luci::CircleNodeOrigin::Source::id (void) const inline
Definition at line 38 of file CircleNodeOrigin.h.
{ return _id; }
name() [1/2]
void luci::CircleNodeOrigin::Source::name (const std::string & name) inline
Definition at line 36 of file CircleNodeOrigin.h.
{ _name = name; }
References name().
Referenced by name().
name() [2/2]
std::string luci::CircleNodeOrigin::Source::name (void) const inline
Definition at line 35 of file CircleNodeOrigin.h.
{ return _name; }
The documentation for this struct was generated from the following file:
compiler/luci/profile/include/luci/Profile/CircleNodeOrigin.h