ONE - On-device Neural Engine: luci::QuantizeSpecialActivation Struct Reference
luci::QuantizeSpecialActivation Struct Reference final
Quantize non-const activaion using pre-defined scale/zp for special Ops.
#include <QuantizeActivation.h>
Public Member Functions
QuantizeSpecialActivation (loco::DataType input, loco::DataType output)
void visit (luci::CircleNode *node)
Default fallback.
void visit (luci::CircleLogistic *node)
void visit (luci::CircleTanh *node)
void visit (luci::CircleSoftmax *node)
void visit (luci::CircleFloor *node)
void visit (luci::CircleFloorDiv *node)
void visit (luci::CircleFloorMod *node)
void visit (luci::CircleCeil *node)
Public Member Functions inherited from luci::CircleNodeMutableVisitor< void >
virtual ~CircleNodeMutableVisitor ()=default
virtual void visit (CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeMutableVisitorBase< T >
virtual ~CircleNodeMutableVisitorBase ()=default
Data Fields
loco::DataType input_type
loco::DataType output_type
Detailed Description
Quantize non-const activaion using pre-defined scale/zp for special Ops.
Definition at line 45 of file QuantizeActivation.h.
Constructor & Destructor Documentation
QuantizeSpecialActivation()
luci::QuantizeSpecialActivation::QuantizeSpecialActivation (loco::DataType input, loco::DataType output) inline
Definition at line 47 of file QuantizeActivation.h.
    : input_type(input), output_type(output)
  {
  }
Member Function Documentation
visit() [1/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleCeil * node)
Definition at line 154 of file QuantizeActivation.cpp.
{
  assert(activation_qtype(node) == luci::ActivationQType::IntScale);
  set_int_scale(node);
}
References luci::activation_qtype(), luci::IntScale, and luci::set_int_scale().
visit() [2/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleFloor * node)
Definition at line 136 of file QuantizeActivation.cpp.
{
  assert(activation_qtype(node) == luci::ActivationQType::IntScale);
  set_int_scale(node);
}
References luci::activation_qtype(), luci::IntScale, and luci::set_int_scale().
visit() [3/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleFloorDiv * node)
Definition at line 142 of file QuantizeActivation.cpp.
{
  assert(activation_qtype(node) == luci::ActivationQType::IntScale);
  set_int_scale(node);
}
References luci::activation_qtype(), luci::IntScale, and luci::set_int_scale().
visit() [4/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleFloorMod * node)
Definition at line 148 of file QuantizeActivation.cpp.
{
  assert(activation_qtype(node) == luci::ActivationQType::IntScale);
  set_int_scale(node);
}
References luci::activation_qtype(), luci::IntScale, and luci::set_int_scale().
visit() [5/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleLogistic * node)
Definition at line 118 of file QuantizeActivation.cpp.
{
  auto qparam = make_predefined_qparam(luci::ActivationQType::PreDefinedLogistic, output_type);
  node->quantparam(std::move(qparam));
}
References luci::make_predefined_qparam(), output_type, luci::PreDefinedLogistic, and luci::CircleNode::quantparam().
visit() [6/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleNode *) virtual
Default fallback.
Reimplemented from luci::CircleNodeMutableVisitor< void >.
Definition at line 107 of file QuantizeActivation.cpp.
{
  // Nodes fused with activation functions which need special quantization
  auto fused_act_node = dynamic_cast<CircleNodeMixin<CircleNodeTrait::FusedActFunc> *>(node);
  if (fused_act_node != nullptr && fused_act_node->fusedActivationFunction() == FusedActFunc::TANH)
  {
    auto qparam = make_predefined_qparam(luci::ActivationQType::PreDefinedTanh, output_type);
    node->quantparam(std::move(qparam));
  }
}
References luci::make_predefined_qparam(), output_type, luci::PreDefinedTanh, luci::CircleNode::quantparam(), and luci::TANH.
visit() [7/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleSoftmax * node)
Definition at line 130 of file QuantizeActivation.cpp.
{
  auto qparam = make_predefined_qparam(luci::ActivationQType::PreDefinedSoftmax, output_type);
  node->quantparam(std::move(qparam));
}
References luci::make_predefined_qparam(), output_type, luci::PreDefinedSoftmax, and luci::CircleNode::quantparam().
visit() [8/8]
void luci::QuantizeSpecialActivation::visit (luci::CircleTanh * node)
Definition at line 124 of file QuantizeActivation.cpp.
{
  auto qparam = make_predefined_qparam(luci::ActivationQType::PreDefinedTanh, output_type);
  node->quantparam(std::move(qparam));
}
References luci::make_predefined_qparam(), output_type, luci::PreDefinedTanh, and luci::CircleNode::quantparam().
Field Documentation
input_type
loco::DataType luci::QuantizeSpecialActivation::input_type
Definition at line 52 of file QuantizeActivation.h.
output_type
loco::DataType luci::QuantizeSpecialActivation::output_type
Definition at line 53 of file QuantizeActivation.h.
Referenced by visit().
The documentation for this struct was generated from the following files:
compiler/luci/pass/src/QuantizeActivation.h
compiler/luci/pass/src/QuantizeActivation.cpp