ONE - On-device Neural Engine: luci::ConvertNCHWToNHWCPass Struct Reference
luci::ConvertNCHWToNHWCPass Struct Reference final
Class to convert NCHW Ops to NHWC.
#include <ConvertNCHWToNHWCPass.h>
Public Member Functions
ConvertNCHWToNHWCPass (bool preserve_input, bool preserve_output)
ConvertNCHWToNHWCPass ()=delete
virtual ~ConvertNCHWToNHWCPass ()=default
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Class to convert NCHW Ops to NHWC.
Find operators that use NCHW layout and make them use NHWC. Strictly speaking, it is impossible to distinguish whether an operator is using NCHW or NHWC without programmers' annotations. But we guess the data layout of each operator as much as possible based on the assumptions described in the comments. Note that this Pass does not change the execution result even for the false-positive cases.
Definition at line 36 of file ConvertNCHWToNHWCPass.h.
Constructor & Destructor Documentation
ConvertNCHWToNHWCPass() [1/2]
luci::ConvertNCHWToNHWCPass::ConvertNCHWToNHWCPass (bool preserve_input, bool preserve_output) inline
Definition at line 39 of file ConvertNCHWToNHWCPass.h.
    : _preserve_input(preserve_input), _preserve_output(preserve_output)
  {
    // Do nothing
  }
ConvertNCHWToNHWCPass() [2/2]
luci::ConvertNCHWToNHWCPass::ConvertNCHWToNHWCPass () delete
~ConvertNCHWToNHWCPass()
virtual luci::ConvertNCHWToNHWCPass::~ConvertNCHWToNHWCPass () virtual default
Member Function Documentation
name()
const char * luci::ConvertNCHWToNHWCPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 49 of file ConvertNCHWToNHWCPass.h.
{ return "luci::ConvertNCHWToNHWCPass"; }
run()
bool luci::ConvertNCHWToNHWCPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 1417 of file ConvertNCHWToNHWCPass.cpp.
{
  LOGGER(l);
  INFO(l) << "ConvertNCHWToNHWCPass Start" << std::endl;
  // Annotate NHWC operators
  // NHWC operators are detected by pattern matching
  //
  // Pattern
  //    pre-Transose (or pre-Reshape) + [intermediate Ops] + post-Transpose (or post-Reshape)
  //
  // [intermediate Ops] are annotated as NHWC
  //
  // NOTE A single pre-Transpose/Reshape can have multiple post-Transpose/Reshape.
  // For example,
  // pre-Transpose --- [intermediate Ops] --- post-Transpose
  //                |
  //                +--[intermediate Ops] --- post-Transpose
  //
  // NOTE Intermediate Ops SHOULD NOT contain pre-Transpose/Reshape
  for (auto node : loco::postorder_traversal(loco::output_nodes(g)))
  {
    if (has_data_format(node))
      continue;
    if (is_pre_transpose(node) || is_pre_reshape(node))
    {
      std::set<loco::Node *> intermediate;
      // Variable to check intermediate Ops contain pre-Transpose/Reshape
      bool has_pre = false;
      // Variable to check the pattern is closed with post-Transpose/Reshape
      bool is_closed = true;
      // For recursive call of lambda
      std::function<void(loco::Node *)> collect_intermediate;
      collect_intermediate = [&](loco::Node *n) {
        for (auto succ : loco::succs(n))
        {
          // Exit condition
          if (is_post_transpose(succ) || is_post_reshape(succ))
            continue;
          if (is_pre_transpose(succ) || is_pre_reshape(succ))
          {
            has_pre = true;
            break;
          }
          if (is_output(succ))
          {
            is_closed = false;
            break;
          }
          intermediate.emplace(succ);
          collect_intermediate(succ);
        }
      };
      collect_intermediate(node);
      if (has_pre or not is_closed)
        continue;
      for (auto inter : intermediate)
      {
        if (not has_data_format(inter))
          set_data_format(inter, DataFormat::NHWC);
      }
    }
  }
  // Annotate NCHW operators
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    auto circle_node = loco::must_cast<luci::CircleNode *>(node);
    switch (circle_node->opcode())
    {
      // List of supported Ops
      case luci::CircleOpcode::CIRCLEINPUT:
        if (!_preserve_input && !has_data_format(node))
        {
          set_data_format(node, DataFormat::NCHW);
        }
        break;
      case luci::CircleOpcode::CIRCLEOUTPUT:
        if (!_preserve_output && !has_data_format(node))
        {
          set_data_format(node, DataFormat::NCHW);
        }
        break;
      case luci::CircleOpcode::ADD:
      case luci::CircleOpcode::CONCATENATION:
      case luci::CircleOpcode::ELU:
      case luci::CircleOpcode::LEAKY_RELU:
      case luci::CircleOpcode::LOGISTIC:
      case luci::CircleOpcode::LOG_SOFTMAX:
      case luci::CircleOpcode::MAXIMUM:
      case luci::CircleOpcode::MEAN:
      case luci::CircleOpcode::MINIMUM:
      case luci::CircleOpcode::MUL:
      case luci::CircleOpcode::NEG:
      case luci::CircleOpcode::PAD:
      case luci::CircleOpcode::PADV2:
      case luci::CircleOpcode::REDUCE_MAX:
      case luci::CircleOpcode::REDUCE_MIN:
      case luci::CircleOpcode::RELU:
      case luci::CircleOpcode::RELU6:
      case luci::CircleOpcode::RSQRT:
      case luci::CircleOpcode::SOFTMAX:
      case luci::CircleOpcode::SPLIT_V:
      case luci::CircleOpcode::SQUARED_DIFFERENCE:
      case luci::CircleOpcode::SUB:
        if (!has_data_format(node))
        {
          set_data_format(node, DataFormat::NCHW);
        }
        break;
      default:
        break;
    }
  }
  bool changed = false;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (!has_data_format(node))
    {
      // Unsupported Op
      continue;
    }
    else if (get_data_format(node) == DataFormat::NHWC)
    {
      // Already converted to NHWC
      continue;
    }
    else if (has_dynamic_shape(node))
    {
      // This pass only works for static-shaped node
      INFO(l) << "Skip the node with a dynamic shape." << std::endl;
      continue;
    }
    else
    {
      ConvertNCHWToNHWC converter;
      auto circle_node = loco::must_cast<luci::CircleNode *>(node);
      if (circle_node->rank() != 4)
      {
        // TODO replace the check above with the input rank check, and remove the condition below
        if (not dynamic_cast<luci::CircleMean *>(node) and
            not dynamic_cast<luci::CircleReduceMax *>(node) and
            not dynamic_cast<luci::CircleReduceMin *>(node))
          continue;
      }
      if (circle_node->accept(&converter))
      {
        set_data_format(node, DataFormat::NHWC);
        changed = true;
      }
      else
      {
        continue;
      }
    }
  }
  INFO(l) << "ConvertNCHWToNHWCPass End" << std::endl;
  return changed;
}
References loco::active_nodes(), luci::has_dynamic_shape(), INFO, LOGGER, loco::output_nodes(), loco::postorder_traversal(), and loco::succs().
The documentation for this struct was generated from the following files:
compiler/luci/pass/include/luci/Pass/ConvertNCHWToNHWCPass.h
compiler/luci/pass/src/ConvertNCHWToNHWCPass.cpp