ONE - On-device Neural Engine: flexbuffers::FLATBUFFERS_FINAL_CLASS::Value Struct Reference
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value Struct Reference
#include <flexbuffers.h>
Public Member Functions
Value ()
Value (bool b)
Value (int64_t i, Type t, BitWidth bw)
Value (uint64_t u, Type t, BitWidth bw)
Value (float f)
Value (double f)
uint8_t StoredPackedType (BitWidth parent_bit_width_=BIT_WIDTH_8) const
BitWidth ElemWidth (size_t buf_size, size_t elem_index) const
BitWidth StoredWidth (BitWidth parent_bit_width_=BIT_WIDTH_8) const
Data Fields
union {
int64_t i_
uint64_t u_
double f_
};
Type type_
BitWidth min_bit_width_
Detailed Description
Definition at line 1607 of file flexbuffers.h.
Constructor & Destructor Documentation
Value() [1/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value () inline
Definition at line 1620 of file flexbuffers.h.
: i_(0), type_(FBT_NULL), min_bit_width_(BIT_WIDTH_8) {}
References flexbuffers::BIT_WIDTH_8, and flexbuffers::FBT_NULL.
Value() [2/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value (bool b) inline
Definition at line 1622 of file flexbuffers.h.
: u_(static_cast<uint64_t>(b)), type_(FBT_BOOL), min_bit_width_(BIT_WIDTH_8) {}
References flexbuffers::BIT_WIDTH_8, and flexbuffers::FBT_BOOL.
Value() [3/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value (int64_t i, Type t, BitWidth bw) inline
Definition at line 1624 of file flexbuffers.h.
: i_(i), type_(t), min_bit_width_(bw) {}
Value() [4/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value (uint64_t u, Type t, BitWidth bw) inline
Definition at line 1625 of file flexbuffers.h.
: u_(u), type_(t), min_bit_width_(bw) {}
Value() [5/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value (float f) inline
Definition at line 1627 of file flexbuffers.h.
: f_(static_cast<double>(f)), type_(FBT_FLOAT), min_bit_width_(BIT_WIDTH_32) {}
References flexbuffers::BIT_WIDTH_32, and flexbuffers::FBT_FLOAT.
Value() [6/6]
flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::Value (double f) inline
Definition at line 1628 of file flexbuffers.h.
: f_(f), type_(FBT_FLOAT), min_bit_width_(WidthF(f)) {}
References flexbuffers::FBT_FLOAT, and flexbuffers::WidthF().
Member Function Documentation
ElemWidth()
BitWidth flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::ElemWidth (size_t buf_size, size_t elem_index) const inline
Definition at line 1635 of file flexbuffers.h.
    {
      if (IsInline(type_))
      {
        return min_bit_width_;
      }
      else
      {
        // We have an absolute offset, but want to store a relative offset
        // elem_index elements beyond the current buffer end. Since whether
        // the relative offset fits in a certain byte_width depends on
        // the size of the elements before it (and their alignment), we have
        // to test for each size in turn.
        for (size_t byte_width = 1; byte_width <= sizeof(flatbuffers::largest_scalar_t);
             byte_width *= 2)
        {
          // Where are we going to write this offset?
          auto offset_loc =
            buf_size + flatbuffers::PaddingBytes(buf_size, byte_width) + elem_index * byte_width;
          // Compute relative offset.
          auto offset = offset_loc - u_;
          // Does it fit?
          auto bit_width = WidthU(offset);
          if (static_cast<size_t>(static_cast<size_t>(1U) << bit_width) == byte_width)
            return bit_width;
        }
        FLATBUFFERS_ASSERT(false); // Must match one of the sizes above.
        return BIT_WIDTH_64;
      }
    }
References flexbuffers::BIT_WIDTH_64, FLATBUFFERS_ASSERT, flexbuffers::IsInline(), offset(), and flexbuffers::WidthU().
StoredPackedType()
uint8_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::StoredPackedType (BitWidth parent_bit_width_ = BIT_WIDTH_8) const inline
Definition at line 1630 of file flexbuffers.h.
    {
      return PackedType(StoredWidth(parent_bit_width_), type_);
    }
References flexbuffers::PackedType().
StoredWidth()
BitWidth flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::StoredWidth (BitWidth parent_bit_width_ = BIT_WIDTH_8) const inline
Definition at line 1666 of file flexbuffers.h.
    {
      if (IsInline(type_))
      {
        return (std::max)(min_bit_width_, parent_bit_width_);
      }
      else
      {
        return min_bit_width_;
      }
    }
References flexbuffers::IsInline().
Field Documentation
union { ... } flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::@8
f_
double flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::f_
Definition at line 1612 of file flexbuffers.h.
i_
int64_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::i_
Definition at line 1610 of file flexbuffers.h.
min_bit_width_
BitWidth flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::min_bit_width_
Definition at line 1618 of file flexbuffers.h.
type_
Type flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::type_
Definition at line 1615 of file flexbuffers.h.
u_
uint64_t flexbuffers::FLATBUFFERS_FINAL_CLASS::Value::u_
Definition at line 1611 of file flexbuffers.h.
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/flexbuffers.h