ONE - On-device Neural Engine: moco::LoggingContext Struct Reference
moco::LoggingContext Struct Reference
Global logging context.
#include <LoggingContext.h>
Static Public Member Functions
static hermes::Context * get (void)
Detailed Description
Global logging context.
Definition at line 28 of file LoggingContext.h.
Member Function Documentation
get()
hermes::Context * moco::LoggingContext::get (void) static
Definition at line 27 of file LoggingContext.cpp.
{
  static hermes::Context *ctx = nullptr;
  if (ctx == nullptr)
  {
    ctx = new hermes::Context;
    ctx->sinks()->append(std::make_unique<hermes::ConsoleReporter>());
    ctx->config(std::make_unique<LoggerConfig>());
  }
  return ctx;
}
References hermes::Sink::Registry::append(), hermes::Context::config(), and hermes::Context::sinks().
Referenced by main().
The documentation for this struct was generated from the following files:
compiler/moco-log/include/moco/LoggingContext.h
compiler/moco-log/src/LoggingContext.cpp