ONE - On-device Neural Engine: exo::FuseReluPass Struct Reference
exo::FuseReluPass Struct Reference final
Class to fuse TFLRelu or TFLRelu6 into the TensorFlow Lite ops below:
#include <FuseReluPass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Class to fuse TFLRelu or TFLRelu6 into the TensorFlow Lite ops below:
ADD, AVERAGE_POOL_2D, CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, FULLY_CONNECTED, L2_NORMALIZATION, L2_POOL_2D, MAX_POOL_2D, MUL
Definition at line 31 of file FuseReluPass.h.
Member Function Documentation
name()
const char * exo::FuseReluPass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 33 of file FuseReluPass.h.
{ return "exo::FuseReluPass"; }
run()
bool exo::FuseReluPass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 92 of file FuseReluPass.cpp.
{
  Collector collector;
  for (auto node : loco::active_nodes(loco::output_nodes(g)))
  {
    if (node->dialect() == locoex::TFLDialect::get())
    {
      auto tfl_node = loco::must_cast<locoex::TFLNode *>(node);
      tfl_node->accept(&collector);
    }
  }
  Performer performer;
  for (auto node : collector.candidates)
  {
    node->accept(&performer);
  }
  return collector.candidates.size() > 0;
}
References loco::active_nodes(), loco::Node::dialect(), locoex::TFLDialect::get(), and loco::output_nodes().
The documentation for this struct was generated from the following files:
compiler/exo/src/Pass/FuseReluPass.h
compiler/exo/src/Pass/FuseReluPass.cpp