ONE - On-device Neural Engine: mir_interpreter::DepthwiseConv2DImpl< uint8_t > Struct Reference
mir_interpreter::DepthwiseConv2DImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const mir::ops::DepthwiseConv2DOp &op, const mir::TensorVariant &inputv, const mir::TensorVariant &kernelv, const mir::TensorVariant *biasv, mir::TensorVariant &output)
Detailed Description
Definition at line 93 of file DepthwiseConv2D.cpp.
Member Function Documentation
run()
void mir_interpreter::DepthwiseConv2DImpl< uint8_t >::run (const mir::ops::DepthwiseConv2DOp & op, const mir::TensorVariant & inputv, const mir::TensorVariant & kernelv, const mir::TensorVariant * biasv, mir::TensorVariant & output) static
Definition at line 100 of file DepthwiseConv2D.cpp.
{
  if (!biasv)
  {
    throw std::runtime_error{"Unsupported quantized DepthwiseConv2D without fused bias"};
  }
  const auto &input_type = inputv.getType();
  const auto &kernel_type = kernelv.getType();
  const auto &bias_type = biasv->getType();
  const auto &output_type = op.getOutput(0)->getType();
  (void)bias_type;
  assert(input_type.isQuantized());
  assert(kernel_type.isQuantized());
  assert(bias_type.isQuantized());
  assert(output_type.isQuantized());
  assert(input_type.getElementType() == DataType::UINT8);
  assert(kernel_type.getElementType() == DataType::UINT8);
  assert(bias_type.getElementType() == DataType::INT32);
  int32_t input_offset = -input_type.getQuantization().getZeroPoint();
  int32_t kernel_offset = -kernel_type.getQuantization().getZeroPoint();
  int32_t output_offset = output_type.getQuantization().getZeroPoint();
  double input_scale = input_type.getQuantization().getScale();
  double kernel_scale = kernel_type.getQuantization().getScale();
  double output_scale = output_type.getQuantization().getScale();
  double real_multiplier = input_scale * kernel_scale / output_scale;
  int32_t output_multiplier = 0;
  int output_shift = 0;
  QuantizeMultiplier(real_multiplier, &output_multiplier, &output_shift);
  const Shape &in_shape = inputv.getShape();
  const Shape &kernel_shape = kernelv.getShape();
  const Shape &out_shape = op.getOutputShape(0);
  const auto &strides = op.getStrides();
  const std::vector<int32_t> &pads = op.getPaddingBefore();
  assert(in_shape.rank() == 4);
  assert(kernel_shape.rank() == 4);
  assert(kernel_shape.dim(2) == in_shape.dim(3)); // HWIO
  assert(in_shape.dim(3) * kernel_shape.dim(3) == out_shape.dim(3));
  assert(strides.size() == 2);
  assert(pads.size() == 2);
  int32_t stride_height = strides[0];
  int32_t stride_width = strides[1];
  int32_t pad_height = pads[0];
  int32_t pad_width = pads[1];
  int32_t input_height = in_shape.dim(1);
  int32_t input_width = in_shape.dim(2);
  Tensor<uint8_t> input_accessor(inputv);
  Tensor<uint8_t> kernel_accessor(kernelv);
  Tensor<int32_t> bias_accessor(*biasv);
  Tensor<uint8_t> res_accessor(output);
  int32_t output_min = std::numeric_limits<uint8_t>::min();
  int32_t output_max = std::numeric_limits<uint8_t>::max();
  int batches = out_shape.dim(0);
  int output_height = out_shape.dim(1);
  int output_width = out_shape.dim(2);
  int input_depth = in_shape.dim(3);
  int filter_height = kernel_shape.dim(0); // HWIO
  int filter_width = kernel_shape.dim(1);  // HWIO
  for (int b = 0; b < batches; ++b)
  {
    for (int out_y = 0; out_y < output_height; ++out_y)
    {
      for (int out_x = 0; out_x < output_width; ++out_x)
      {
        for (int ic = 0; ic < input_depth; ++ic)
        {
          const int oc = ic;
          const int in_x_origin = (out_x * stride_width) - pad_width;
          const int in_y_origin = (out_y * stride_height) - pad_height;
          int32_t acc = 0;
          for (int filter_y = 0; filter_y < filter_height; ++filter_y)
          {
            for (int filter_x = 0; filter_x < filter_width; ++filter_x)
            {
              const int in_x = in_x_origin + filter_x;
              const int in_y = in_y_origin + filter_y;
              // If the location is outside the bounds of the input image,
              // use zero as a default value.
              if ((in_x >= 0) && (in_x < input_width) && (in_y >= 0) && (in_y < input_height))
              {
                Index in_index{b, in_y, in_x, ic};
                Index ker_index{filter_y, filter_x, oc, 0}; // HWIO
                int32_t input_val = input_accessor.at(in_index);
                int32_t kernel_val = kernel_accessor.at(ker_index);
                acc += (kernel_val + kernel_offset) * (input_val + input_offset);
              }
            }
          }
          acc += bias_accessor.at(Index{oc});
          acc = MultiplyByQuantizedMultiplier(acc, output_multiplier, output_shift);
          acc += output_offset;
          acc = std::max(acc, output_min);
          acc = std::min(acc, output_max);
          Index out_index{b, out_y, out_x, oc};
          res_accessor.at(out_index) = static_cast<uint8_t>(acc);
        }
      }
    }
  }
}
References mir::Tensor< T >::at(), mir::Shape::dim(), mir::Operation::getOutput(), mir::Operation::getOutputShape(), mir::ops::DepthwiseConv2DOp::getPaddingBefore(), mir::TensorVariant::getShape(), mir::ops::DepthwiseConv2DOp::getStrides(), mir::Operation::Output::getType(), mir::TensorVariant::getType(), mir_interpreter::MultiplyByQuantizedMultiplier(), mir_interpreter::QuantizeMultiplier(), and mir::Shape::rank().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/DepthwiseConv2D.cpp