ONE - On-device Neural Engine: logo::PhaseEventListener Struct Reference
logo::PhaseEventListener Struct Reference
#include <Phase.h>
Public Member Functions
virtual ~PhaseEventListener ()=default
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PhaseEnd > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassBegin > *)
virtual void notify (const PhaseEventInfo< PhaseEvent::PassEnd > *)
Detailed Description
Definition at line 78 of file Phase.h.
Constructor & Destructor Documentation
~PhaseEventListener()
virtual logo::PhaseEventListener::~PhaseEventListener () virtual default
Member Function Documentation
notify() [1/4]
virtual void logo::PhaseEventListener::notify (const PhaseEventInfo< PhaseEvent::PassBegin > *) inline virtual
Definition at line 84 of file Phase.h.
{ return; };
notify() [2/4]
virtual void logo::PhaseEventListener::notify (const PhaseEventInfo< PhaseEvent::PassEnd > *) inline virtual
Definition at line 85 of file Phase.h.
{ return; };
notify() [3/4]
virtual void logo::PhaseEventListener::notify (const PhaseEventInfo< PhaseEvent::PhaseBegin > *) inline virtual
Definition at line 82 of file Phase.h.
{ return; };
Referenced by logo::PhaseRunnerMixinObservable::notifyPassBegin(), logo::PhaseRunnerMixinObservable::notifyPassEnd(), logo::PhaseRunnerMixinObservable::notifyPhaseBegin(), and logo::PhaseRunnerMixinObservable::notifyPhaseEnd().
notify() [4/4]
virtual void logo::PhaseEventListener::notify (const PhaseEventInfo< PhaseEvent::PhaseEnd > *) inline virtual
Definition at line 83 of file Phase.h.
{ return; };
The documentation for this struct was generated from the following file:
compiler/logo-core/include/logo/Phase.h