ONE - On-device Neural Engine: DepthwiseConv2DLayer Struct Reference
DepthwiseConv2DLayer Struct Reference final
#include <GraphBuilder.h>
Data Structures
class Return
Public Member Functions
std::unique_ptr< Return > operator() (GraphBuilder::Context *ctx)
Detailed Description
Definition at line 421 of file GraphBuilder.h.
Member Function Documentation
operator()()
std::unique_ptr< Return > DepthwiseConv2DLayer::operator() (GraphBuilder::Context * ctx) inline
Definition at line 438 of file GraphBuilder.h.
  {
    auto depthwiseconv2d_node = ctx->graph()->nodes()->create<loco::DepthwiseConv2D>();
    depthwiseconv2d_node->ker(ctx->stack()->pop());
    depthwiseconv2d_node->ifm(ctx->stack()->pop());
    ctx->stack()->push(depthwiseconv2d_node);
    return std::make_unique<Return>(depthwiseconv2d_node);
  }
References loco::NodePool::create(), GraphBuilder::Context::graph(), loco::DepthwiseConv2D::ker(), loco::Graph::nodes(), GraphBuilder::Stack::pop(), GraphBuilder::Stack::push(), and GraphBuilder::Context::stack().
The documentation for this struct was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h