ONE - On-device Neural Engine: loco::Graph::InputContext Struct Reference
loco::Graph::InputContext Struct Reference final
GraphInput Pool.
#include <Graph.h>
Public Member Functions
GraphInput * create (void)
Public Member Functions inherited from loco::ObjectPool< GraphInput >
virtual ~ObjectPool ()=default
uint32_t size (void) const
Return the number of objects.
GraphInput * at (uint32_t n) const
Access N-th object.
Additional Inherited Members
Protected Member Functions inherited from loco::ObjectPool< GraphInput >
U * take (std::unique_ptr< U > &&o)
Take the ownership of a given object and returns its raw pointer.
bool erase (GraphInput *ptr)
Erase an object from the pool.
Detailed Description
GraphInput Pool.
Definition at line 191 of file Graph.h.
Member Function Documentation
create()
GraphInput * loco::Graph::InputContext::create (void)
Definition at line 52 of file Graph.cpp.
{ return take(std::make_unique<GraphInput>(size())); }
References loco::ObjectPool< GraphInput >::size(), and loco::ObjectPool< GraphInput >::take().
Referenced by luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), and InputLayer::operator()().
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/IR/Graph.h
compiler/loco/src/IR/Graph.cpp