ONE - On-device Neural Engine: nnfw::cker::Tensor Struct Reference
nnfw::cker::Tensor Struct Reference
#include <Tensor.h>
Public Member Functions
bool copyFrom (const Tensor &other, const Shape &new_shape)
template<typename T >
T * base () const
template<typename T , size_t NDIMS>
TTypes< T, NDIMS >::Tensor shaped (const std::vector< int32_t > &new_sizes)
template<typename T >
TTypes< T >::Flat flat ()
template<typename T , size_t NDIMS>
TTypes< T, NDIMS >::ConstTensor shaped (const std::vector< int32_t > new_sizes) const
template<typename T , size_t NDIMS>
TTypes< T, NDIMS >::Tensor shaped () const
template<typename T >
TTypes< T >::ConstFlat flat () const
template<typename T >
TTypes< T >::ConstScalar scalar () const
Data Fields
Shape shape
void * buffer
Detailed Description
Definition at line 94 of file Tensor.h.
Member Function Documentation
base()
template<typename T > T * nnfw::cker::Tensor::base () const inline
Definition at line 111 of file Tensor.h.
  {
    return buffer == nullptr ? nullptr : reinterpret_cast<T *>(buffer);
  }
References buffer.
copyFrom()
bool nnfw::cker::Tensor::copyFrom (const Tensor & other, const Shape & new_shape) inline
Definition at line 100 of file Tensor.h.
  {
    if (other.shape.FlatSize() != new_shape.FlatSize())
      return false;
    this->shape.ReplaceWith(new_shape.DimensionsCount(), new_shape.DimsData());
    this->buffer = other.buffer;
    return true;
  }
References buffer, nnfw::cker::Shape::DimensionsCount(), nnfw::cker::Shape::DimsData(), nnfw::cker::Shape::FlatSize(), nnfw::cker::Shape::ReplaceWith(), and shape.
flat() [1/2]
template<typename T > TTypes< T >::Flat nnfw::cker::Tensor::flat () inline
Definition at line 127 of file Tensor.h.
{ return shaped<T, 1>({shape.FlatSize()}); }
References nnfw::cker::Shape::FlatSize(), and shape.
Referenced by nnfw::cker::GenerateKey().
flat() [2/2]
template<typename T > TTypes< T >::ConstFlat nnfw::cker::Tensor::flat () const inline
Definition at line 151 of file Tensor.h.
  {
    return shaped<T, 1>({shape.FlatSize()});
  }
References nnfw::cker::Shape::FlatSize(), and shape.
scalar()
template<typename T > TTypes< T >::ConstScalar nnfw::cker::Tensor::scalar () const inline
Definition at line 156 of file Tensor.h.
  {
    return typename TTypes<T>::ConstScalar(base<T>());
  }
Referenced by nnfw::cker::BroadcastTo().
shaped() [1/3]
template<typename T , size_t NDIMS> TTypes< T, NDIMS >::Tensor nnfw::cker::Tensor::shaped () const inline
Definition at line 141 of file Tensor.h.
  {
    Eigen::array<Eigen::DenseIndex, NDIMS> dims;
    for (size_t d = 0; d < NDIMS; d++)
    {
      dims[d] = shape.Dims(d);
    }
    return typename TTypes<T, NDIMS>::Tensor(base<T>(), dims);
  }
References nnfw::cker::Shape::Dims(), and shape.
shaped() [2/3]
template<typename T , size_t NDIMS> TTypes< T, NDIMS >::Tensor nnfw::cker::Tensor::shaped (const std::vector< int32_t > & new_sizes) inline
Definition at line 117 of file Tensor.h.
  {
    Eigen::array<Eigen::DenseIndex, NDIMS> dims;
    for (size_t d = 0; d < NDIMS; d++)
    {
      dims[d] = new_sizes[d];
    }
    return typename TTypes<T, NDIMS>::Tensor(base<T>(), dims);
  }
Referenced by nnfw::cker::FusedBatchNorm::operator()().
shaped() [3/3]
template<typename T , size_t NDIMS> TTypes< T, NDIMS >::ConstTensor nnfw::cker::Tensor::shaped (const std::vector< int32_t > new_sizes) const inline
Definition at line 130 of file Tensor.h.
  {
    Eigen::array<Eigen::DenseIndex, NDIMS> dims;
    for (size_t d = 0; d < NDIMS; d++)
    {
      dims[d] = new_sizes[d];
    }
    return typename TTypes<T, NDIMS>::ConstTensor(base<T>(), dims);
  }
Field Documentation
buffer
void* nnfw::cker::Tensor::buffer
Definition at line 97 of file Tensor.h.
Referenced by base(), nnfw::cker::BroadcastTo(), nnfw::cker::FusedBatchNorm::copyFrom(), copyFrom(), nnfw::cker::Einsum::operator()(), and nnfw::cker::StatelessRandomUniform().
shape
Shape nnfw::cker::Tensor::shape
Definition at line 96 of file Tensor.h.
Referenced by nnfw::cker::BroadcastTo(), nnfw::cker::FusedBatchNorm::copyFrom(), copyFrom(), flat(), nnfw::cker::Einsum::operator()(), nnfw::cker::functor::BroadcastTo< Device, T >::ReshapeAndBCast(), shaped(), and nnfw::cker::StatelessRandomUniform().
The documentation for this struct was generated from the following file:
compute/cker/include/cker/operation/Helper/Tensor.h