ONE - On-device Neural Engine: locoex::CircleNode Struct Reference
locoex::CircleNode Struct Reference abstract
#include <CircleNodeDecl.h>
Public Member Functions
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Definition at line 29 of file CircleNodeDecl.h.
Constructor & Destructor Documentation
~CircleNode()
virtual locoex::CircleNode::~CircleNode () virtual default
Member Function Documentation
accept() [1/2]
template<typename T > T locoex::CircleNode::accept (CircleNodeMutableVisitorBase< T > * v)
Definition at line 48 of file CircleNodeImpl.h.
{
  switch (this->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS) \
                                   \
  case CircleOpcode::OPCODE:       \
    return v->visit(dynamic_cast<CLASS *>(this));
#include "CircleNodes.lst"
#undef CIRCLE_NODE
    default:
      break;
  }
  INTERNAL_EXN("CircleNode::accept(CircleNodeMutableVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
accept() [2/2]
template<typename T > T locoex::CircleNode::accept (CircleNodeVisitorBase< T > * v) const
Definition at line 29 of file CircleNodeImpl.h.
{
  switch (this->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS) \
                                   \
  case CircleOpcode::OPCODE:       \
    return v->visit(dynamic_cast<const CLASS *>(this));
#include "CircleNodes.lst"
#undef CIRCLE_NODE
    default:
      break;
  }
  INTERNAL_EXN("CircleNode::accept(CircleNodeVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
dialect()
const loco::Dialect * locoex::CircleNode::dialect (void) const final virtual
Return "Dialect" identifier that this node belongs to.
dialect() SHOULD return a valid pointer.
Implements loco::Node.
Definition at line 24 of file CircleNode.cpp.
{ return CircleDialect::get(); }
References locoex::CircleDialect::get().
opcode()
virtual CircleOpcode locoex::CircleNode::opcode (void) const pure virtual
Implemented in locoex::CircleNodeImpl< Code >, and locoex::CircleNodeImpl< CircleOpcode::INSTANCE_NORM >.
Referenced by accept().
The documentation for this struct was generated from the following files:
compiler/exo/src/Dialect/IR/CircleNodeDecl.h
compiler/exo/src/Dialect/IR/CircleNode.cpp
compiler/exo/src/Dialect/IR/CircleNodeImpl.h