ONE - On-device Neural Engine: InputLayer Struct Reference
InputLayer Struct Reference final
#include <GraphBuilder.h>
Data Structures
class Return
Public Member Functions
std::unique_ptr< Return > operator() (GraphBuilder::Context *ctx)
Detailed Description
Definition at line 113 of file GraphBuilder.h.
Member Function Documentation
operator()()
std::unique_ptr< Return > InputLayer::operator() (GraphBuilder::Context * ctx) inline
Definition at line 147 of file GraphBuilder.h.
  {
    auto input_index = ctx->graph()->inputs()->size();
    auto graph_input = ctx->graph()->inputs()->create();
    auto pull_node = ctx->graph()->nodes()->create<loco::Pull>();
    pull_node->index(input_index);
    loco::link(graph_input, pull_node);
    ctx->stack()->push(pull_node);
    return std::make_unique<Return>(graph_input, pull_node);
  }
References loco::NodePool::create(), loco::Graph::InputContext::create(), GraphBuilder::Context::graph(), loco::Pull::index(), loco::Graph::inputs(), loco::link(), loco::Graph::nodes(), GraphBuilder::Stack::push(), loco::ObjectPool< T >::size(), and GraphBuilder::Context::stack().
The documentation for this struct was generated from the following file:
compiler/loco/src/Service/GraphBuilder.h