ONE - On-device Neural Engine: moco::TFTypeInferenceRule Struct Reference
moco::TFTypeInferenceRule Struct Reference final
Type Inference Rule for TFDialect.
#include <TFTypeInferenceRule.h>
Public Member Functions
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::DataType &) const final
Public Member Functions inherited from loco::TypeInferenceRule
virtual ~TypeInferenceRule ()=default
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, DataType &) const =0
Detailed Description
Type Inference Rule for TFDialect.
Definition at line 28 of file TFTypeInferenceRule.h.
Member Function Documentation
infer()
bool moco::TFTypeInferenceRule::infer (const loco::Node * , loco::DataType &) const final virtual
Framework guarantees the followings:
Framework tries to infer the data type of each node only after the data type of all of its valid (= non-nullptr) argument nodes is inferred.
The result of preceding "infer" is accessible through below dtype_get method.
This holds only when preceding "infer" returns true.
Implements loco::TypeInferenceRule.
Definition at line 91 of file TFTypeInferenceRule.cpp.
{
  assert(node->dialect() == TFDialect::get());
  TypeForwardAlgorithm alg;
// clang-format off
#define TENSORFLOW_NODE(OPCODE,CLASS)                          \
  if (dynamic_cast<const moco::CLASS *>(node))             \
  {                                                            \
    auto tfnode = loco::must_cast<const moco::CLASS *>(node); \
    dtype = tfnode->accept(&alg);                              \
    assert(dtype != loco::DataType::Unknown);                  \
    return true;                                               \
  }
#include "moco/IR/TFNodes.lst"
#undef TENSORFLOW_NODE
  // clang-format on
  return false;
}
References loco::Node::dialect(), and moco::TFDialect::get().
recognize()
bool moco::TFTypeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::TypeInferenceRule.
Definition at line 85 of file TFTypeInferenceRule.cpp.
{
  // This rule recognizes only "TFDialect" dialect!
  return TFDialect::get() == d;
}
References moco::TFDialect::get().
The documentation for this struct was generated from the following files:
compiler/moco/service/include/moco/Service/TFTypeInferenceRule.h
compiler/moco/service/src/Service/TFTypeInferenceRule.cpp