ONE - On-device Neural Engine: logo::RemoveForwardNodePass Struct Reference
logo::RemoveForwardNodePass Struct Reference final
Use the input of "Forward" node instead.
#include <RemoveForwardNodePass.h>
Public Member Functions
const char * name (void) const final
bool run (loco::Graph *g) final
Run the pass.
Public Member Functions inherited from logo::Pass
virtual ~Pass ()=default
virtual const char * name (void) const
virtual bool run (loco::Graph *graph)=0
Run the pass.
Detailed Description
Use the input of "Forward" node instead.
BEFORE: [X] -> [Forward] -> [Y]
AFTER: [X] -> [Y] [Forward]
NOTE This transform does not remove "Forward" node
Definition at line 37 of file RemoveForwardNodePass.h.
Member Function Documentation
name()
const char * logo::RemoveForwardNodePass::name (void) const inline final virtual
Reimplemented from logo::Pass.
Definition at line 39 of file RemoveForwardNodePass.h.
{ return "RemoveForwardNodePass"; }
run()
bool logo::RemoveForwardNodePass::run (loco::Graph * graph) final virtual
Run the pass.
Returns
false if there was nothing changed
Implements logo::Pass.
Definition at line 27 of file RemoveForwardNodePass.cpp.
{
  struct Collector final : public loco::CanonicalNodeMutableVisitor<void>
  {
    void visit(loco::Forward *node) final
    {
      if (node->input() != nullptr)
      {
        candidates.insert(node);
      }
    }
    void visit(loco::Node *) final { return; }
    std::set<loco::Forward *> candidates;
  };
  Collector collector;
  for (auto node : loco::all_nodes(g))
  {
    if (node->dialect() == loco::CanonicalDialect::get())
    {
      auto canonical_node = loco::must_cast<loco::CanonicalNode *>(node);
      canonical_node->accept(&collector);
    }
  }
  for (auto node : collector.candidates)
  {
    replace(node).with(node->input());
    node->input(nullptr);
  }
  return collector.candidates.size() > 0;
}
References loco::all_nodes(), loco::CanonicalDialect::get(), loco::Forward::input(), and loco::Subst< SubstQualifier::Default >::with().
The documentation for this struct was generated from the following files:
compiler/logo/include/logo/RemoveForwardNodePass.h
compiler/logo/src/Passes/RemoveForwardNodePass.cpp