ONE - On-device Neural Engine: flatbuffers::EnumVal Struct Reference
flatbuffers::EnumVal Struct Reference
#include <idl.h>
Public Member Functions
Offset< reflection::EnumVal > Serialize (FlatBufferBuilder *builder, const Parser &parser) const
bool Deserialize (Parser &parser, const reflection::EnumVal *val)
flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< reflection::KeyValue > > > SerializeAttributes (FlatBufferBuilder *builder, const Parser &parser) const
bool DeserializeAttributes (Parser &parser, const Vector< Offset< reflection::KeyValue > > *attrs)
uint64_t GetAsUInt64 () const
int64_t GetAsInt64 () const
bool IsZero () const
bool IsNonZero () const
Data Fields
std::string name
std::vector< std::string > doc_comment
Type union_type
SymbolTable< Value > attributes
Friends
bool operator== (const EnumVal &lhs, const EnumVal &rhs)
Detailed Description
Definition at line 427 of file idl.h.
Member Function Documentation
Deserialize()
bool flatbuffers::EnumVal::Deserialize (Parser & parser, const reflection::EnumVal * val)
DeserializeAttributes()
bool flatbuffers::EnumVal::DeserializeAttributes (Parser & parser, const Vector< Offset< reflection::KeyValue > > * attrs)
GetAsInt64()
int64_t flatbuffers::EnumVal::GetAsInt64 () const inline
Definition at line 441 of file idl.h.
{ return value; }
Referenced by flatbuffers::EnumDef::ToString().
GetAsUInt64()
uint64_t flatbuffers::EnumVal::GetAsUInt64 () const inline
Definition at line 440 of file idl.h.
{ return static_cast<uint64_t>(value); }
Referenced by flatbuffers::EnumDef::ToString().
IsNonZero()
bool flatbuffers::EnumVal::IsNonZero () const inline
Definition at line 443 of file idl.h.
{ return !IsZero(); }
References IsZero().
IsZero()
bool flatbuffers::EnumVal::IsZero () const inline
Definition at line 442 of file idl.h.
{ return 0 == value; }
Referenced by IsNonZero().
Serialize()
Offset< reflection::EnumVal > flatbuffers::EnumVal::Serialize (FlatBufferBuilder * builder, const Parser & parser) const
SerializeAttributes()
flatbuffers::Offset< flatbuffers::Vector< flatbuffers::Offset< reflection::KeyValue > > > flatbuffers::EnumVal::SerializeAttributes (FlatBufferBuilder * builder, const Parser & parser) const
Friends And Related Symbol Documentation
operator==
bool operator== (const EnumVal & lhs, const EnumVal & rhs) friend
Definition at line 577 of file idl.h.
{
  return lhs.value == rhs.value;
}
Field Documentation
attributes
SymbolTable<Value> flatbuffers::EnumVal::attributes
Definition at line 448 of file idl.h.
doc_comment
std::vector<std::string> flatbuffers::EnumVal::doc_comment
Definition at line 446 of file idl.h.
name
std::string flatbuffers::EnumVal::name
Definition at line 445 of file idl.h.
union_type
Type flatbuffers::EnumVal::union_type
Definition at line 447 of file idl.h.
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/idl.h