ONE - On-device Neural Engine: mir_interpreter::FullyConnectedImpl< T > Struct Template Reference
mir_interpreter::FullyConnectedImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &inputv, const mir::TensorVariant &weightsv, const mir::ops::FullyConnectedOp &op, mir::TensorVariant &res, const mir::TensorVariant *biasv)
Detailed Description
template<typename T>
struct mir_interpreter::FullyConnectedImpl< T >
Definition at line 59 of file FullyConnected.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::FullyConnectedImpl< T >::run (const mir::TensorVariant & inputv, const mir::TensorVariant & weightsv, const mir::ops::FullyConnectedOp & op, mir::TensorVariant & res, const mir::TensorVariant * biasv) static
Definition at line 67 of file FullyConnected.cpp.
{
  if (biasv)
  {
    throw std::runtime_error("non-quantized FullyConnected with fused bias is unsupported");
  }
  mir::Tensor<T> input{inputv};
  mir::Tensor<T> weights{weightsv};
  erase<T>(res);
  if (input.getShape().rank() == 2 && weights.getShape().rank() == 2 && res.getShape().rank() == 2)
  {
    // optimized case for 2d matrix multiplication
    fullyConnected2D<T>(inputv, weightsv, res);
    return;
  }
  mir::Tensor<T> accessor(res);
  const mir::Shape &in_shape = input.getShape();
  int32_t in_rank = in_shape.rank();
  const mir::Shape &w_shape = weights.getShape();
  int32_t w_rank = w_shape.rank();
  assert(in_shape.dim(in_rank - 1) == w_shape.dim(w_rank - 2));
  (void)in_rank;
  mir::ShapeRange out_range(res.getShape());
  int32_t len = w_shape.dim(w_rank - 2);
  for (auto &out_index : out_range)
  {
    mir::Index t_index = out_index;
    T &output_element = accessor.at(out_index);
    int32_t col = t_index.at(w_rank - 1);
    int32_t row = t_index.at(w_rank - 2);
    for (int32_t i = 0; i < len; ++i)
    {
      t_index.at(w_rank - 1) = i;
      T in = input.at(t_index);
      t_index.at(w_rank - 1) = col;
      t_index.at(w_rank - 2) = i;
      T w = weights.at(t_index);
      t_index.at(w_rank - 2) = row;
      output_element += in * w;
    }
  }
}
References mir::Tensor< T >::at(), mir::TensorVariant::at(), mir::Index::at(), mir::Shape::dim(), mir::TensorVariant::getShape(), and mir::Shape::rank().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/FullyConnected.cpp