ONE - On-device Neural Engine: onert_micro::execute::OMKernelExecute Struct Reference
onert_micro::execute::OMKernelExecute Struct Reference
#include <OMKernelExecute.h>
Static Public Member Functions
static OMStatus executeKernel (OMExecuteArgs &, core::memory::OMRuntimeAllocator &allocator)
Detailed Description
Definition at line 31 of file OMKernelExecute.h.
Member Function Documentation
executeKernel()
OMStatus OMKernelExecute::executeKernel (OMExecuteArgs & execute_args, core::memory::OMRuntimeAllocator & allocator) static
Definition at line 24 of file OMKernelExecute.cpp.
{
  OMStatus status = Ok;
  core::OMRuntimeContext &context = execute_args.runtime_context;
  core::OMRuntimeStorage &storage = execute_args.runtime_storage;
  const core::reader::CircleOperators *operators = context.getCircleOperators();
  const auto num_operators = static_cast<uint16_t>(operators->size());
  const auto *op_codes = context.getCircleOpcodes();
  for (uint16_t i = 0; i < num_operators; ++i)
  {
    status = allocator.allocate(i, &context, &storage);
    if (status != Ok)
      return status;
    core::OMBuilderID builder_id = core::OMBuilderID::Size;
    const circle::Operator *op = operators->operator[](i);
    uint32_t index = op->opcode_index();
    assert(index < op_codes->size());
    const auto opcode = op_codes->operator[](index);
    status = core::getBuilderId(opcode, builder_id);
    assert(status == Ok);
    if (status != Ok)
      return status;
    execute_args.kernel_index = i;
    KernelExecuteFunc *execute_func = nullptr;
    if (size_t(builder_id) < size_t(core::OMBuilderID::BuiltinOperatorsSize))
    {
      // Builtin operator
      status = kernel_builtin_execute.getKernelExecuteFunc(builder_id, &execute_func);
    }
    else
    {
      // Custom
      status = kernel_custom_execute.getKernelExecuteFunc(builder_id, &execute_func);
    }
    assert(execute_func != nullptr);
    if (status != Ok)
      return status;
    status = execute_func(execute_args);
    assert(status == Ok);
    if (status != Ok)
      return status;
    status = allocator.deallocate(i, &storage);
  }
  return status;
}
References onert_micro::core::memory::OMRuntimeAllocator::allocate(), onert_micro::core::BuiltinOperatorsSize, onert_micro::core::memory::OMRuntimeAllocator::deallocate(), onert_micro::core::getBuilderId(), onert_micro::core::OMRuntimeContext::getCircleOpcodes(), onert_micro::core::OMRuntimeContext::getCircleOperators(), onert_micro::execute::KernelBuiltinExecuteRegistry::getKernelExecuteFunc(), onert_micro::execute::KernelCustomExecuteRegistry::getKernelExecuteFunc(), onert_micro::execute::kernel_builtin_execute, onert_micro::execute::kernel_custom_execute, onert_micro::execute::OMExecuteArgs::kernel_index, onert_micro::Ok, onert_micro::execute::OMExecuteArgs::runtime_context, onert_micro::execute::OMExecuteArgs::runtime_storage, flatbuffers::Vector< T >::size(), size, and onert_micro::core::Size.
Referenced by onert_micro::core::OMRuntimeModule::run().
The documentation for this struct was generated from the following files:
onert-micro/onert-micro/include/execute/OMKernelExecute.h
onert-micro/onert-micro/src/execute/OMKernelExecute.cpp