ONE - On-device Neural Engine: ForEachDimension< from, to, Enable > Struct Template Reference
ForEachDimension< from, to, Enable > Struct Template Reference
#include <Utils.h>
Static Public Member Functions
template<typename L , typename... Args>
static void unroll (const onert::ir::Shape &shape, onert::ir::Coordinates &coords, L &&lambda_function, Args &&... args)
Detailed Description
template<size_t from, size_t to, typename Enable = void>
struct ForEachDimension< from, to, Enable >
Definition at line 30 of file Utils.h.
Member Function Documentation
unroll()
template<size_t from, size_t to, typename Enable = void> template<typename L , typename... Args> static void ForEachDimension< from, to, Enable >::unroll (const onert::ir::Shape & shape, onert::ir::Coordinates & coords, L && lambda_function, Args &&... args) inline static
Definition at line 33 of file Utils.h.
  {
    static_assert(from < to, "from must not be less than to");
    assert(static_cast<int>(to) <= shape.rank());
    const auto &d = shape.dim(from);
    for (auto v = 0; v < d; v++)
    {
      coords.set(from, v);
      ForEachDimension<from + 1, to>::unroll(shape, coords, std::forward<L>(lambda_function),
                                             std::forward<Args>(args)...);
    }
  }
References coords, and ForEachDimension< from, to, Enable >::unroll().
Referenced by ShapeLoop(), and ForEachDimension< from, to, Enable >::unroll().
The documentation for this struct was generated from the following file:
runtime/onert/core/include/util/Utils.h