ONE - On-device Neural Engine: flatbuffers::IndirectHelper< T > Struct Template Reference
flatbuffers::IndirectHelper< T > Struct Template Reference
#include <flatbuffers.h>
Public Types
typedef T return_type
typedef T mutable_return_type
Static Public Member Functions
static return_type Read (const uint8_t *p, uoffset_t i)
Static Public Attributes
static const size_t element_stride = sizeof(T)
Detailed Description
template<typename T>
struct flatbuffers::IndirectHelper< T >
Definition at line 108 of file flatbuffers.h.
Member Typedef Documentation
mutable_return_type
template<typename T > typedef T flatbuffers::IndirectHelper< T >::mutable_return_type
Definition at line 111 of file flatbuffers.h.
return_type
template<typename T > typedef T flatbuffers::IndirectHelper< T >::return_type
Definition at line 110 of file flatbuffers.h.
Member Function Documentation
Read()
template<typename T > static return_type flatbuffers::IndirectHelper< T >::Read (const uint8_t * p, uoffset_t i) inline static
Definition at line 113 of file flatbuffers.h.
  {
    return EndianScalar((reinterpret_cast<const T *>(p))[i]);
  }
Referenced by flatbuffers::Vector< T >::Get(), flatbuffers::Array< T, length >::Get(), flatbuffers::Vector< T >::GetMutableObject(), flatbuffers::Vector< T >::LookupByKey(), flatbuffers::VectorIterator< T, IT >::operator*(), and flatbuffers::VectorIterator< T, IT >::operator->().
Field Documentation
element_stride
template<typename T > const size_t flatbuffers::IndirectHelper< T >::element_stride = sizeof(T) static
Definition at line 112 of file flatbuffers.h.
The documentation for this struct was generated from the following file:
onert-micro/externals/flatbuffers/flatbuffers.h