ONE - On-device Neural Engine: mir_interpreter::TransposeImpl< T > Struct Template Reference
mir_interpreter::TransposeImpl< T > Struct Template Reference
Static Public Member Functions
static void run (const mir::TensorVariant &input, const mir::ops::TransposeOp &op, mir::TensorVariant &output)
Detailed Description
template<typename T>
struct mir_interpreter::TransposeImpl< T >
Definition at line 27 of file Transpose.cpp.
Member Function Documentation
run()
template<typename T > void mir_interpreter::TransposeImpl< T >::run (const mir::TensorVariant & input, const mir::ops::TransposeOp & op, mir::TensorVariant & output) static
Definition at line 34 of file Transpose.cpp.
{
  const auto &output_shape = op.getOutputShape(0);
  const auto &axis_order = op.getAxisOrder();
  const int32_t num_axis = static_cast<int32_t>(axis_order.size());
  assert(num_axis == inputv.getShape().rank());
  assert(num_axis == output_shape.rank());
  mir::Index output_index;
  output_index.resize(num_axis);
  mir::Tensor<T> input(inputv);
  mir::Tensor<T> output(outputv);
  for (auto &input_index : mir::ShapeRange(input.getShape()))
  {
    for (int32_t i = 0; i < num_axis; i++)
      output_index.at(i) = input_index.at(axis_order[i]);
    output.at(output_index) = input.at(input_index);
  }
}
References mir::Index::at(), mir::ops::TransposeOp::getAxisOrder(), mir::Operation::getOutputShape(), mir::TensorVariant::getShape(), mir::Shape::rank(), and mir::Index::resize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/Transpose.cpp