ONE - On-device Neural Engine: loco::ShapeInference Struct Reference
loco::ShapeInference Struct Reference
#include <ShapeInference.h>
Static Public Member Functions
static bool known (const Node *)
static NodeShape get (const Node *)
static void erase (Node *)
Detailed Description
Definition at line 53 of file ShapeInference.h.
Member Function Documentation
erase()
void loco::ShapeInference::erase (Node * node) static
Definition at line 102 of file ShapeInference.cpp.
{ node->annot<ShapeAnnotation>(nullptr); }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by loco::shape_erase().
get()
NodeShape loco::ShapeInference::get (const Node * node) static
Definition at line 96 of file ShapeInference.cpp.
{
  assert(known(node));
  return node->annot<ShapeAnnotation>()->shape();
}
References loco::AnnotatedItem< Annotation >::annot(), and known().
Referenced by loco::shape_get().
known()
bool loco::ShapeInference::known (const Node * node) static
Definition at line 94 of file ShapeInference.cpp.
{ return node->annot<ShapeAnnotation>() != nullptr; }
References loco::AnnotatedItem< Annotation >::annot().
Referenced by get(), and loco::shape_known().
The documentation for this struct was generated from the following files:
compiler/loco/include/loco/Service/ShapeInference.h
compiler/loco/src/Service/ShapeInference.cpp