ONE - On-device Neural Engine: rua::ExecutionService Struct Reference
rua::ExecutionService Struct Reference abstract
A wrapper for ANeuralNetworkExecution API.
#include <Service.h>
Public Member Functions
virtual ~ExecutionService ()=default
virtual int create (ANeuralNetworksCompilation *compilation, ANeuralNetworksExecution **execution) const =0
virtual void free (ANeuralNetworksExecution *execution) const =0
virtual int setInput (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const void *buffer, size_t length) const =0
virtual int setInputFromMemory (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const ANeuralNetworksMemory *memory, size_t offset, size_t length) const =0
virtual int setOutput (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, void *buffer, size_t length) const =0
virtual int setOutputFromMemory (ANeuralNetworksExecution *execution, int32_t index, const ANeuralNetworksOperandType *type, const ANeuralNetworksMemory *memory, size_t offset, size_t length) const =0
virtual int startCompute (ANeuralNetworksExecution *execution, ANeuralNetworksEvent **event) const =0
Detailed Description
A wrapper for ANeuralNetworkExecution API.
Definition at line 103 of file Service.h.
Constructor & Destructor Documentation
~ExecutionService()
virtual rua::ExecutionService::~ExecutionService () virtual default
Member Function Documentation
create()
virtual int rua::ExecutionService::create (ANeuralNetworksCompilation * compilation, ANeuralNetworksExecution ** execution) const pure virtual
Referenced by ANeuralNetworksExecution_create().
free()
virtual void rua::ExecutionService::free (ANeuralNetworksExecution * execution) const pure virtual
Referenced by ANeuralNetworksExecution_free().
setInput()
virtual int rua::ExecutionService::setInput (ANeuralNetworksExecution * execution, int32_t index, const ANeuralNetworksOperandType * type, const void * buffer, size_t length) const pure virtual
Referenced by ANeuralNetworksExecution_setInput().
setInputFromMemory()
virtual int rua::ExecutionService::setInputFromMemory (ANeuralNetworksExecution * execution, int32_t index, const ANeuralNetworksOperandType * type, const ANeuralNetworksMemory * memory, size_t offset, size_t length) const pure virtual
Referenced by ANeuralNetworksExecution_setInputFromMemory().
setOutput()
virtual int rua::ExecutionService::setOutput (ANeuralNetworksExecution * execution, int32_t index, const ANeuralNetworksOperandType * type, void * buffer, size_t length) const pure virtual
Referenced by ANeuralNetworksExecution_setOutput().
setOutputFromMemory()
virtual int rua::ExecutionService::setOutputFromMemory (ANeuralNetworksExecution * execution, int32_t index, const ANeuralNetworksOperandType * type, const ANeuralNetworksMemory * memory, size_t offset, size_t length) const pure virtual
Referenced by ANeuralNetworksExecution_setOutputFromMemory().
startCompute()
virtual int rua::ExecutionService::startCompute (ANeuralNetworksExecution * execution, ANeuralNetworksEvent ** event) const pure virtual
Referenced by ANeuralNetworksExecution_startCompute().
The documentation for this struct was generated from the following file:
runtime/libs/rua/core/include/rua/Service.h