ONE - On-device Neural Engine: mir_interpreter::MaxPool2DImpl< uint8_t > Struct Reference
mir_interpreter::MaxPool2DImpl< uint8_t > Struct Reference
Static Public Member Functions
static void run (const mir::TensorVariant &input, const mir::ops::MaxPool2DOp &op, mir::TensorVariant &result)
Detailed Description
Definition at line 87 of file MaxPool2D.cpp.
Member Function Documentation
run()
void mir_interpreter::MaxPool2DImpl< uint8_t >::run (const mir::TensorVariant & input, const mir::ops::MaxPool2DOp & op, mir::TensorVariant & result) static
Definition at line 93 of file MaxPool2D.cpp.
{
  const auto &input_type = input.getType();
  const auto &output_type = op.getOutput(0)->getType();
  (void)input_type;
  assert(input_type.isQuantized());
  assert(output_type.isQuantized());
  assert(input_type.getElementType() == DataType::UINT8);
  const auto &input_shape = op.getInputShape(0);
  const auto &output_shape = op.getOutputShape(0);
  const auto &window_size = op.getWindowSize();
  const auto &strides = op.getStrides();
  const auto &padding_before = op.getPaddingBefore();
  const auto &padding_after = op.getPaddingAfter();
  (void)padding_after;
  constexpr int num_spatial_dims = 2;
  assert(input.getShape().rank() == 4);
  assert(window_size.size() == num_spatial_dims);
  assert(strides.size() == num_spatial_dims);
  assert(padding_before.size() == num_spatial_dims);
  assert(padding_after.size() == num_spatial_dims);
  Tensor<uint8_t> input_accessor(input);
  TensorType res_type(mir::DataType::UINT8, output_shape, output_type.getQuantization());
  TensorVariant res(res_type);
  Tensor<uint8_t> res_accessor(res);
  ShapeRange in_range(input_shape);
  Index in_index(input_shape.rank());
  for (const auto &out_index : ShapeRange(output_shape))
  {
    // Assuming NHWC format.
    in_index.at(0) = out_index.at(0);
    in_index.at(3) = out_index.at(3);
    uint8_t result = 0;
    for (const auto &window_index : ShapeRange(Shape(window_size)))
    {
      // Assuming NHWC format.
      for (int i = 0; i < num_spatial_dims; ++i)
        in_index.at(1 + i) =
          out_index.at(1 + i) * strides[i] + window_index.at(i) - padding_before[i];
      if (in_range.contains(in_index))
      {
        result = std::max(result, input_accessor.at(in_index));
      }
    }
    res_accessor.at(out_index) = result;
  }
}
References mir::Tensor< T >::at(), mir::Index::at(), mir::ShapeRange::contains(), mir::Operation::getInputShape(), mir::Operation::getOutput(), mir::Operation::getOutputShape(), mir::ops::MaxPool2DOp::getPaddingAfter(), mir::ops::MaxPool2DOp::getPaddingBefore(), mir::ops::MaxPool2DOp::getStrides(), mir::Operation::Output::getType(), and mir::ops::MaxPool2DOp::getWindowSize().
The documentation for this struct was generated from the following file:
compiler/mir-interpreter/src/ops/MaxPool2D.cpp