ONE - On-device Neural Engine: luci::UserSettings Struct Reference
luci::UserSettings Struct Reference abstract
UserSettings provides user settings by key-value.
#include <UserSettings.h>
Public Types
enum Key {
Undefined , MuteWarnings , DisableValidation , ProfilingDataGen ,
ExecutionPlanGen
}
Public Member Functions
virtual void set (const Key key, bool value)=0
virtual bool get (const Key key) const =0
Static Public Member Functions
static UserSettings * settings ()
Detailed Description
UserSettings provides user settings by key-value.
Definition at line 28 of file UserSettings.h.
Member Enumeration Documentation
Key
enum luci::UserSettings::Key
Enumerator
Undefined
MuteWarnings
DisableValidation
ProfilingDataGen
ExecutionPlanGen
Definition at line 30 of file UserSettings.h.
  {
    Undefined,
    MuteWarnings,
    DisableValidation,
    ProfilingDataGen,
    ExecutionPlanGen,
  };
Member Function Documentation
get()
virtual bool luci::UserSettings::get (const Key key) const pure virtual
Implemented in luci::UserSettingsImpl.
set()
virtual void luci::UserSettings::set (const Key key, bool value) pure virtual
Implemented in luci::UserSettingsImpl.
settings()
UserSettings * luci::UserSettings::settings () static
Definition at line 83 of file UserSettings.cpp.
{
  static UserSettingsImpl _this;
  return &_this;
}
Referenced by luci::createCircleMetadataVector(), entry(), luci::LoggerConfig::LoggerConfig(), circle_planner::ExecutionPlanner::make_execution_plan(), luci::CircleCastGraphBuilder::validate(), luci::CircleGreaterGraphBuilder::validate(), and luci::CircleUnpackGraphBuilder::validate().
The documentation for this struct was generated from the following files:
compiler/luci/env/include/luci/UserSettings.h
compiler/luci/env/src/UserSettings.cpp