ONE - On-device Neural Engine: onert::compiler::ILoweredGraph Struct Reference
onert::compiler::ILoweredGraph Struct Reference abstract
#include <ILoweredGraph.h>
Public Member Functions
virtual ~ILoweredGraph ()=default
virtual ir::Graph & graph ()=0
virtual const ir::Graph & graph () const =0
virtual const compiler::GraphLowerInfo & lower_info () const =0
virtual compiler::GraphLowerInfo & lower_info ()=0
Detailed Description
Definition at line 28 of file ILoweredGraph.h.
Constructor & Destructor Documentation
~ILoweredGraph()
virtual onert::compiler::ILoweredGraph::~ILoweredGraph () virtual default
Member Function Documentation
graph() [1/2]
virtual const ir::Graph & onert::compiler::ILoweredGraph::graph () const pure virtual
Implemented in onert::compiler::LoweredGraph, and onert::compiler::train::LoweredTrainableGraph.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
graph() [2/2]
virtual ir::Graph & onert::compiler::ILoweredGraph::graph () pure virtual
Implemented in onert::compiler::LoweredGraph, and onert::compiler::train::LoweredTrainableGraph.
Referenced by TopologicalSortHelper.TopologicalSortHelper::add_edge(), onert::dumper::dot::DotDumper::dump(), onert::compiler::Linear::dump(), onert::compiler::Linear::linearize(), and TopologicalSortHelper.TopologicalSortHelper::sort_util().
lower_info() [1/2]
virtual const compiler::GraphLowerInfo & onert::compiler::ILoweredGraph::lower_info () const pure virtual
Implemented in onert::compiler::LoweredGraph, and onert::compiler::train::LoweredTrainableGraph.
Referenced by onert::compiler::pass::PermutationInsertionPass::callback(), onert::compiler::pass::ConstantInsertionPass::callback(), and onert::compiler::pass::ConstantLoweringPass::callback().
lower_info() [2/2]
virtual compiler::GraphLowerInfo & onert::compiler::ILoweredGraph::lower_info () pure virtual
Implemented in onert::compiler::LoweredGraph, and onert::compiler::train::LoweredTrainableGraph.
The documentation for this struct was generated from the following file:
runtime/onert/core/include/compiler/ILoweredGraph.h