ONE - On-device Neural Engine: hermes::Sink::Registry Struct Reference
hermes::Sink::Registry Struct Reference abstract
#include <Sink.h>
Public Member Functions
virtual ~Registry ()=default
virtual void append (std::unique_ptr< Sink > &&)=0
Detailed Description
Definition at line 34 of file Sink.h.
Constructor & Destructor Documentation
~Registry()
virtual hermes::Sink::Registry::~Registry () virtual default
Member Function Documentation
append()
virtual void hermes::Sink::Registry::append (std::unique_ptr< Sink > &&) pure virtual
Referenced by circlechef::LoggingContext::get(), exo::LoggingContext::get(), luci::LoggingContext::get(), moco::LoggingContext::get(), and tflchef::LoggingContext::get().
The documentation for this struct was generated from the following file:
compiler/hermes/include/hermes/core/Sink.h