ONE - On-device Neural Engine: locoex::COpShapeInferenceRule Struct Reference
locoex::COpShapeInferenceRule Struct Reference final
Shape inference rule for COpDialect.
#include <COpShapeInferenceRule.h>
Public Member Functions
bool recognize (const loco::Dialect *) const final
Return true if this rule recognizes a given dialect.
bool infer (const loco::Node *, loco::NodeShape &) const final
Infer node's shape.
Public Member Functions inherited from loco::ShapeInferenceRule
virtual ~ShapeInferenceRule ()=default
virtual bool support (const API &api) const
Check whether a given API is available or not.
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, NodeShape &) const =0
Infer node's shape.
virtual void infer (const Context *, const Node *, Sink *) const
Additional Inherited Members
Public Types inherited from loco::ShapeInferenceRule
enum class API { V1 , V2 }
Detailed Description
Shape inference rule for COpDialect.
Note
the shape of inputs and output of CopCall must belong to loco::Domain::Tensor
Definition at line 33 of file COpShapeInferenceRule.h.
Member Function Documentation
infer()
bool locoex::COpShapeInferenceRule::infer (const loco::Node * , loco::NodeShape &) const final virtual
Infer node's shape.
WARNING!!
Implementation SHOULD return true only when it succeeds in inference!
Implements loco::ShapeInferenceRule.
Definition at line 35 of file COpShapeInferenceRule.cpp.
{
  assert(node->dialect() == COpDialect::get());
  assert(dynamic_cast<const COpNode *>(node) != nullptr);
  auto cop_call = loco::must_cast<const COpCall *>(node);
  // Note that the shape of custom op is considered as TensorShape
  // TODO Decide how to deal with this shape error cases
  for (uint32_t n = 0; n < cop_call->arity(); n++)
    if (loco::shape_get(cop_call->input(n)).domain() != loco::Domain::Tensor)
      throw std::runtime_error("Input of custom op must belong to Tensor domain.");
  loco::TensorShape out_shape;
  out_shape.rank(cop_call->rank());
  for (uint32_t d = 0; d < cop_call->rank(); d++)
    out_shape.dim(d) = cop_call->dim(d);
  shape.set(out_shape);
  return true;
}
References loco::Node::dialect(), loco::TensorShape::dim(), loco::NodeShape::domain(), locoex::COpDialect::get(), loco::TensorShape::rank(), loco::NodeShape::set(), loco::shape_get(), and loco::Tensor.
recognize()
bool locoex::COpShapeInferenceRule::recognize (const loco::Dialect *) const final virtual
Return true if this rule recognizes a given dialect.
Implements loco::ShapeInferenceRule.
Definition at line 30 of file COpShapeInferenceRule.cpp.
{
  return COpDialect::get() == d;
}
References locoex::COpDialect::get().
The documentation for this struct was generated from the following files:
compiler/locoex-customop/include/locoex/Service/COpShapeInferenceRule.h
compiler/locoex-customop/src/Service/COpShapeInferenceRule.cpp