ONE - On-device Neural Engine: rua::Anchor Struct Reference
rua::Anchor Struct Reference
Global Runtime Abstraction Context.
#include <Anchor.h>
Static Public Member Functions
static const RuntimeService * get (void)
static void set (const RuntimeService *svc)
Detailed Description
Global Runtime Abstraction Context.
"set" will have global effect (within each process).
Definition at line 30 of file Anchor.h.
Member Function Documentation
get()
const RuntimeService * rua::Anchor::get (void) static
Definition at line 30 of file Anchor.cpp.
{ return anchored_service; }
Referenced by ANeuralNetworksCompilation_create(), ANeuralNetworksCompilation_finish(), ANeuralNetworksCompilation_free(), ANeuralNetworksCompilation_setPreference(), ANeuralNetworksEvent_free(), ANeuralNetworksEvent_wait(), ANeuralNetworksExecution_create(), ANeuralNetworksExecution_free(), ANeuralNetworksExecution_setInput(), ANeuralNetworksExecution_setInputFromMemory(), ANeuralNetworksExecution_setOutput(), ANeuralNetworksExecution_setOutputFromMemory(), ANeuralNetworksExecution_startCompute(), ANeuralNetworksMemory_createFromFd(), ANeuralNetworksMemory_free(), ANeuralNetworksModel_addOperand(), ANeuralNetworksModel_addOperation(), ANeuralNetworksModel_create(), ANeuralNetworksModel_finish(), ANeuralNetworksModel_free(), ANeuralNetworksModel_identifyInputsAndOutputs(), ANeuralNetworksModel_relaxComputationFloat32toFloat16(), ANeuralNetworksModel_setOperandValue(), and ANeuralNetworksModel_setOperandValueFromMemory().
set()
void rua::Anchor::set (const RuntimeService * svc) static
Definition at line 31 of file Anchor.cpp.
{ anchored_service = service; }
The documentation for this struct was generated from the following files:
runtime/libs/rua/anchor/include/rua/Anchor.h
runtime/libs/rua/anchor/src/Anchor.cpp