ONE - On-device Neural Engine: exo::ShapeInference Struct Reference
exo::ShapeInference Struct Reference
Get the shape of each node as a node annotation.
#include <ShapeInference.h>
Static Public Member Functions
static ShapeDescription get (loco::Node *node)
Detailed Description
Get the shape of each node as a node annotation.
HOW TO USE
ShapeInference::get(g->nodes()->at(..));
Definition at line 34 of file ShapeInference.h.
Member Function Documentation
get()
ShapeDescription exo::ShapeInference::get (loco::Node * node) static
Definition at line 35 of file ShapeInference.cpp.
{
  // TODO Adjust indentation level
  {
    assert(loco::shape_known(node));
    return to_shape_description(loco::shape_get(node));
  }
}
References loco::shape_get(), loco::shape_known(), and exo::to_shape_description().
The documentation for this struct was generated from the following files:
compiler/exo/src/ShapeInference.h
compiler/exo/src/ShapeInference.cpp