ONE - On-device Neural Engine: luci::QuantizeActivation Struct Reference
luci::QuantizeActivation Struct Reference final
Quantize non-const activation using recorded min/max values.
#include <QuantizeActivation.h>
Public Member Functions
QuantizeActivation (loco::DataType input, loco::DataType output)
void visit (luci::CircleNode *node)
Default fallback.
Public Member Functions inherited from luci::CircleNodeMutableVisitor< void >
virtual ~CircleNodeMutableVisitor ()=default
virtual void visit (CircleNode *)
Default fallback.
Public Member Functions inherited from luci::CircleNodeMutableVisitorBase< T >
virtual ~CircleNodeMutableVisitorBase ()=default
Data Fields
loco::DataType input_type
loco::DataType output_type
Detailed Description
Quantize non-const activation using recorded min/max values.
Definition at line 28 of file QuantizeActivation.h.
Constructor & Destructor Documentation
QuantizeActivation()
luci::QuantizeActivation::QuantizeActivation (loco::DataType input, loco::DataType output) inline
Definition at line 30 of file QuantizeActivation.h.
    : input_type(input), output_type(output)
  {
  }
Member Function Documentation
visit()
void luci::QuantizeActivation::visit (luci::CircleNode *) virtual
Default fallback.
Reimplemented from luci::CircleNodeMutableVisitor< void >.
Definition at line 42 of file QuantizeActivation.cpp.
{
  LOGGER(l);
  INFO(l) << "QuantizeActivation visit node: " << node->name() << std::endl;
  // Check if node is fp32
  if (not is_fp32(node))
    return;
  // Check if this is const (const activation is handled by QuantizeConstInputActivation)
  // NOTE QuantizePreChecker guarantees weights/bias are const.
  // Update this code when we accept non-const weights/bias.
  if (node->opcode() == luci::CircleOpcode::CIRCLECONST)
    return;
  // Check if this is activation
  // We assume min/max are recorded only for activations
  if (has_min_max(node))
  {
    // Quantize using recorded min/max
    auto quantparam = node->quantparam();
    assert(quantparam);
    assert(quantparam->min.size() == 1); // only support layer-wise quant
    assert(quantparam->max.size() == 1); // only support layer-wise quant
    auto min = quantparam->min[0];
    auto max = quantparam->max[0];
    float scaling_factor{0};
    int64_t zp{0};
    float nudged_min{0};
    float nudged_max{0};
    if (output_type == loco::DataType::U8)
    {
      compute_asym_scale_zp(min, max, scaling_factor, zp, nudged_min, nudged_max);
      node->dtype(loco::DataType::U8);
    }
    else
    {
      compute_sym_scale_zp(min, max, scaling_factor, zp, nudged_min, nudged_max);
      node->dtype(loco::DataType::S16);
    }
    node->quantparam()->scale.push_back(scaling_factor);
    node->quantparam()->zerop.push_back(zp);
  }
  // Fix special attributes
  if (node->opcode() == luci::CircleOpcode::CAST)
  {
    auto *cast = loco::must_cast<luci::CircleCast *>(node);
    auto *cast_input = loco::must_cast<luci::CircleNode *>(cast->x());
    // make sure that cast_input is already quantized
    assert(cast_input->dtype() != loco::DataType::FLOAT32);
    cast->in_data_type(cast_input->dtype());
    cast->out_data_type(cast->dtype());
  }
}
References luci::compute_asym_scale_zp(), luci::compute_sym_scale_zp(), INFO, luci::is_fp32(), LOGGER, luci::CircleNode::name(), luci::CircleNode::opcode(), output_type, luci::CircleNode::quantparam(), luci::CircleQuantParam::scale, and luci::CircleQuantParam::zerop.
Field Documentation
input_type
loco::DataType luci::QuantizeActivation::input_type
Definition at line 35 of file QuantizeActivation.h.
output_type
loco::DataType luci::QuantizeActivation::output_type
Definition at line 36 of file QuantizeActivation.h.
Referenced by visit().
The documentation for this struct was generated from the following files:
compiler/luci/pass/src/QuantizeActivation.h
compiler/luci/pass/src/QuantizeActivation.cpp