ONE - On-device Neural Engine: luci::DeadNodeQueryServiceImpl Struct Reference
luci::DeadNodeQueryServiceImpl Struct Reference final
#include <DeadNodeQueryService.h>
Public Member Functions
bool isDeadNode (loco::Node *node) final
Check if the node is dead node.
Public Member Functions inherited from logo::DeadNodeQueryService
virtual ~DeadNodeQueryService ()=default
virtual bool isDeadNode (loco::Node *node)=0
Check if the node is dead node.
Public Member Functions inherited from loco::DialectService
virtual ~DialectService ()=default
Detailed Description
Definition at line 27 of file DeadNodeQueryService.h.
Member Function Documentation
isDeadNode()
bool luci::DeadNodeQueryServiceImpl::isDeadNode (loco::Node * node) final virtual
Check if the node is dead node.
Implements logo::DeadNodeQueryService.
Definition at line 39 of file DeadNodeQueryService.cpp.
{
  auto g = node->graph();
  auto input_nodes_vec = loco::input_nodes(g);
  auto output_nodes_vec = loco::output_nodes(g);
  auto input_nodes = std::set<loco::Node *>(input_nodes_vec.begin(), input_nodes_vec.end());
  auto output_nodes = std::set<loco::Node *>(output_nodes_vec.begin(), output_nodes_vec.end());
  auto active_nodes = loco::active_nodes(output_nodes_vec);
  if (active_nodes.find(node) != active_nodes.end())
    return false;
  // input and output nodes are not dead node even if it is not active.
  if (input_nodes.find(node) != input_nodes.end())
    return false;
  // if node is one of virtual mulitple outputs, we need to ask the real node
  if (auto circle_node = dynamic_cast<luci::CircleNode *>(node))
  {
    VirtualOutputDetector d;
    if (circle_node->accept(&d))
    {
      assert(node->arity() == 1);
      loco::Node *real_node = node->arg(0);
      if (active_nodes.find(real_node) != active_nodes.end())
        return false;
      if (input_nodes.find(real_node) != input_nodes.end())
        return false;
    }
  }
  return true;
}
References loco::active_nodes(), loco::Node::arg(), loco::Node::arity(), loco::Node::graph(), loco::input_nodes(), and loco::output_nodes().
Referenced by luci::inference_candidates().
The documentation for this struct was generated from the following files:
compiler/luci/lang/include/luci/IR/DeadNodeQueryService.h
compiler/luci/lang/src/DeadNodeQueryService.cpp