ONE - On-device Neural Engine: moco::ModelSignature Struct Reference
moco::ModelSignature Struct Reference
Class to store information to run a model. Normally this info comes from users via CLI params or configuration file.
#include <ModelSignature.h>
Public Member Functions
void add_input (const TensorName &input)
void add_input (const TensorName &&input)
void add_output (const TensorName &output)
void add_output (const TensorName &&output)
const std::vector< TensorName > & inputs () const
const std::vector< TensorName > & outputs () const
void add_customop (const std::string &op)
Adds customop op type (not name of node) provided from user.
const std::vector< std::string > & customops () const
void shape (const std::string &node_name, const angkor::TensorShape &shape)
Adds node name and its shape provided from user.
const angkor::TensorShape * shape (const std::string &node_name) const
void dtype (const std::string &node_name, loco::DataType dtype)
Adds node name and its dtype provided from user.
loco::DataType dtype (const std::string &node_name) const
Detailed Description
Class to store information to run a model. Normally this info comes from users via CLI params or configuration file.
Definition at line 35 of file ModelSignature.h.
Member Function Documentation
add_customop()
void moco::ModelSignature::add_customop (const std::string & op)
Adds customop op type (not name of node) provided from user.
Definition at line 24 of file ModelSignature.cpp.
{
  if (std::find(_customops.begin(), _customops.end(), op) == _customops.end())
    _customops.emplace_back(op);
  else
    throw oops::UserExn("Duplicate custom operator", op);
}
add_input() [1/2]
void moco::ModelSignature::add_input (const TensorName && input) inline
Definition at line 39 of file ModelSignature.h.
{ _inputs.push_back(input); }
add_input() [2/2]
void moco::ModelSignature::add_input (const TensorName & input) inline
Definition at line 38 of file ModelSignature.h.
{ _inputs.push_back(input); }
Referenced by nnkit::support::moco::tf::Backend::Backend(), and main().
add_output() [1/2]
void moco::ModelSignature::add_output (const TensorName && output) inline
Definition at line 41 of file ModelSignature.h.
{ _outputs.push_back(output); }
add_output() [2/2]
void moco::ModelSignature::add_output (const TensorName & output) inline
Definition at line 40 of file ModelSignature.h.
{ _outputs.push_back(output); }
Referenced by nnkit::support::moco::tf::Backend::Backend(), and main().
customops()
const std::vector< std::string > & moco::ModelSignature::customops () const inline
Definition at line 50 of file ModelSignature.h.
{ return _customops; }
dtype() [1/2]
loco::DataType moco::ModelSignature::dtype (const std::string & node_name) const
Definition at line 57 of file ModelSignature.cpp.
{
  auto res = _dtypes.find(node_name);
  if (res == _dtypes.end())
    return loco::DataType::Unknown;
  else
    return res->second;
}
dtype() [2/2]
void moco::ModelSignature::dtype (const std::string & node_name, loco::DataType dtype)
Adds node name and its dtype provided from user.
Definition at line 49 of file ModelSignature.cpp.
{
  if (_dtypes.find(node_name) != _dtypes.end())
    throw oops::UserExn("Duplicate node name", node_name);
  _dtypes[node_name] = dtype;
}
References dtype().
Referenced by moco::tf::COpCallGraphBuilder::build(), and dtype().
inputs()
const std::vector< TensorName > & moco::ModelSignature::inputs () const inline
Definition at line 43 of file ModelSignature.h.
{ return _inputs; }
Referenced by validate_onnx2circle.OnnxRunner::feed_random_inputs().
outputs()
const std::vector< TensorName > & moco::ModelSignature::outputs () const inline
Definition at line 44 of file ModelSignature.h.
{ return _outputs; }
Referenced by validate_onnx2circle.OnnxRunner::get_outputs().
shape() [1/2]
const angkor::TensorShape * moco::ModelSignature::shape (const std::string & node_name) const
Definition at line 40 of file ModelSignature.cpp.
{
  auto res = _shapes.find(node_name);
  if (res == _shapes.end())
    return nullptr;
  else
    return &res->second;
}
shape() [2/2]
void moco::ModelSignature::shape (const std::string & node_name, const angkor::TensorShape & shape)
Adds node name and its shape provided from user.
Definition at line 32 of file ModelSignature.cpp.
{
  if (_shapes.find(node_name) != _shapes.end())
    throw oops::UserExn("Duplicate node name", node_name);
  _shapes[node_name] = shape;
}
References shape().
Referenced by nnkit::support::moco::tf::Backend::Backend(), moco::tf::COpCallGraphBuilder::build(), main(), and shape().
The documentation for this struct was generated from the following files:
compiler/moco/import/include/moco/Import/ModelSignature.h
compiler/moco/import/src/ModelSignature.cpp