ONE - On-device Neural Engine: onert_micro::optimize::OMOptimizer Struct Reference
onert_micro::optimize::OMOptimizer Struct Reference
#include <OMOptimizer.h>
Static Public Member Functions
static OMStatus optimize (core::OMRuntimeStorage &storage, core::OMRuntimeContext &context, const OMConfig &configs)
Detailed Description
Definition at line 30 of file OMOptimizer.h.
Member Function Documentation
optimize()
OMStatus OMOptimizer::optimize (core::OMRuntimeStorage & storage, core::OMRuntimeContext & context, const OMConfig & configs) static
Definition at line 26 of file OMOptimizer.cpp.
{
  OMGraphStatus graph_status = {Unchanged, Ok};
  const uint32_t number_of_passes = optimize_passes.getPassNumber();
  do
  {
    for (uint32_t i = 0; i < number_of_passes; ++i)
    {
      OptimizePassFunc *cur_pass_func;
      OMStatus status = optimize_passes.getOptimizeFunc(i, &cur_pass_func);
      assert(status == Ok && "Unsupported pass");
      if (status != Ok)
        return status;
      graph_status = cur_pass_func(storage, context, configs);
      assert(graph_status.main_status == Ok);
      if (graph_status.main_status != Ok)
        return graph_status.main_status;
    }
  } while (graph_status.graph_status == Changed);
  return Ok;
}
References onert_micro::optimize::Changed, onert_micro::optimize::OptimizePassRegistry::getOptimizeFunc(), onert_micro::optimize::OptimizePassRegistry::getPassNumber(), onert_micro::optimize::OMGraphStatus::graph_status, onert_micro::optimize::OMGraphStatus::main_status, onert_micro::Ok, onert_micro::optimize::optimize_passes, and onert_micro::optimize::Unchanged.
Referenced by onert_micro::core::OMRuntimeModule::importModel().
The documentation for this struct was generated from the following files:
onert-micro/onert-micro/include/optimize/OMOptimizer.h
onert-micro/onert-micro/src/optimize/OMOptimizer.cpp