ONE - On-device Neural Engine: luci::CircleNode Struct Reference
luci::CircleNode Struct Reference abstract
#include <CircleNodeDecl.h>
Public Member Functions
virtual ~CircleNode ()=default
const loco::Dialect * dialect (void) const final
Return "Dialect" identifier that this node belongs to.
virtual CircleOpcode opcode (void) const =0
template<typename T >
T accept (CircleNodeVisitorBase< T > *) const
template<typename T >
T accept (CircleNodeMutableVisitorBase< T > *)
NodeName name (void) const
void name (const NodeName &name)
CircleQuantParam * quantparam (void) const
void quantparam (std::unique_ptr< CircleQuantParam > &&quantparam)
SparsityParam * sparsityparam (void) const
void sparsityparam (std::unique_ptr< SparsityParam > &&sparsityparam)
ShapeStatus shape_status (void) const
void shape_status (ShapeStatus ss)
int32_t op_version (void) const
void op_version (int32_t op_version)
Public Member Functions inherited from loco::Node
Node ()=default
Node (const Node &)=delete
Node (Node &&)=delete
virtual ~Node ()
Graph * graph (void)
const Graph * graph (void) const
virtual const Dialect * dialect (void) const =0
Return "Dialect" identifier that this node belongs to.
virtual uint32_t opnum (void) const =0
virtual uint32_t arity (void) const =0
Return the number of arguments.
virtual Node * arg (uint32_t N) const =0
Access N-th argument node.
virtual void drop (void)=0
Drop all the reference of arguments.
Public Member Functions inherited from loco::AnnotatedItem< NodeAnnotation >
AnnotatedItem ()=default
virtual ~AnnotatedItem ()=default
const T * annot (void) const
Retrieve a stored annotation of type T.
void annot (std::unique_ptr< T > &&p)
Attach or remove a new annotation of type T.
Detailed Description
Definition at line 37 of file CircleNodeDecl.h.
Constructor & Destructor Documentation
~CircleNode()
virtual luci::CircleNode::~CircleNode () virtual default
Member Function Documentation
accept() [1/2]
template<typename T > T luci::CircleNode::accept (CircleNodeMutableVisitorBase< T > * v)
Definition at line 50 of file CircleNodeImpl.h.
{
  switch (this->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS) \
                                   \
  case CircleOpcode::OPCODE:       \
    return v->visit(dynamic_cast<CLASS *>(this));
#define CIRCLE_VNODE CIRCLE_NODE
#include "CircleNodes.lst"
#undef CIRCLE_VNODE
#undef CIRCLE_NODE
    default:
      break;
  }
  INTERNAL_EXN("CircleNode::accept(CircleNodeMutableVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
accept() [2/2]
template<typename T > T luci::CircleNode::accept (CircleNodeVisitorBase< T > * v) const
Definition at line 29 of file CircleNodeImpl.h.
{
  switch (this->opcode())
  {
#define CIRCLE_NODE(OPCODE, CLASS) \
                                   \
  case CircleOpcode::OPCODE:       \
    return v->visit(dynamic_cast<const CLASS *>(this));
#define CIRCLE_VNODE CIRCLE_NODE
#include "CircleNodes.lst"
#undef CIRCLE_VNODE
#undef CIRCLE_NODE
    default:
      break;
  }
  INTERNAL_EXN("CircleNode::accept(CircleNodeVisitorBase) not handled");
}
References INTERNAL_EXN, and opcode().
Referenced by luci::circle_builtin_operator(), luci::circle_builtin_options(), luci::clone_connect(), luci::clone_node(), luci::tinf::Rule::infer(), luci::sinf::Rule::infer(), luci::opcode_name(), dalgona::PythonHooks::postOperatorExecute(), dalgona::PythonHooks::preOperatorExecute(), luci::validate_name(), luci::validate_unique_name(), luci::VerifyQuantizedBiasScale::verify(), luci::VerifyQuantizedNodeTypeBase< Qtype, Btype >::verify(), and luci::OperationExporterRule::visit().
dialect()
const loco::Dialect * luci::CircleNode::dialect (void) const final virtual
Return "Dialect" identifier that this node belongs to.
dialect() SHOULD return a valid pointer.
Implements loco::Node.
Definition at line 23 of file CircleNode.cpp.
{ return CircleDialect::get(); }
References luci::CircleDialect::get().
name() [1/2]
void luci::CircleNode::name (const NodeName & name) inline
Definition at line 50 of file CircleNodeDecl.h.
{ _name = name; }
References name().
Referenced by name().
name() [2/2]
NodeName luci::CircleNode::name (void) const inline
Definition at line 49 of file CircleNodeDecl.h.
{ return _name; }
Referenced by luci::CircleWhileGraphBuilder::build(), luci_interpreter::KernelBuilder::build(), luci::ConstantFoldingAddTestGraph::ConstantFoldingAddTestGraph(), luci::ConstantFoldingTestGraph::ConstantFoldingTestGraph(), luci::copy_common_attributes(), luci::copy_tensor_attributes(), circle_eval_diff::createEmptyTensor(), luci::dump(), luci::IndexNodeFinder::enroll(), entry(), luci::PGroups::group_of(), luci::tinf::Rule::infer(), luci::sinf::Rule::infer(), SimpleGraph::init(), luci_interpreter::GraphLoader::loadTensors(), dalgona::outputPyArray(), dalgona::outputsPyArray(), record_minmax::MinMaxObserver::postTensorWrite(), luci::produce_pgroups(), luci_interpreter::Interpreter::readOutputTensor(), luci::QuantizeDequantizeWeightsPass::run(), luci::QuantizeWithMinMaxPass::run(), prunner::PModelsRunner::run(), dalgona::Dalgona::runAnalysisWithRandomInput(), prunner::PModelsRunner::save_outputs(), luci::validate_name(), luci::validate_unique_name(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), luci::QuantizeActivation::visit(), luci::warn_accuracy_with_range(), and luci_interpreter::Interpreter::writeInputTensor().
op_version() [1/2]
void luci::CircleNode::op_version (int32_t op_version) inline
Definition at line 68 of file CircleNodeDecl.h.
{ _op_version = op_version; }
References op_version().
Referenced by op_version().
op_version() [2/2]
int32_t luci::CircleNode::op_version (void) const inline
Definition at line 67 of file CircleNodeDecl.h.
{ return _op_version; }
Referenced by luci::GraphBuilder::build(), luci::CircleWhileGraphBuilder::build(), luci::copy_common_attributes(), and luci::OperationExporterRule::visit().
opcode()
virtual CircleOpcode luci::CircleNode::opcode (void) const pure virtual
Implemented in luci::CircleNodeImpl< Code >, luci::CircleNodeImpl< CircleOpcode::ABS >, luci::CircleNodeImpl< CircleOpcode::ADD >, luci::CircleNodeImpl< CircleOpcode::ADD_N >, luci::CircleNodeImpl< CircleOpcode::ARG_MAX >, luci::CircleNodeImpl< CircleOpcode::ARG_MIN >, luci::CircleNodeImpl< CircleOpcode::AVERAGE_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::BCQ_FULLY_CONNECTED >, luci::CircleNodeImpl< CircleOpcode::BCQ_GATHER >, luci::CircleNodeImpl< CircleOpcode::BATCH_MATMUL >, luci::CircleNodeImpl< CircleOpcode::BATCH_TO_SPACE_ND >, luci::CircleNodeImpl< CircleOpcode::BIDIRECTIONAL_SEQUENCE_LSTM >, luci::CircleNodeImpl< CircleOpcode::CIRCLEBIDIRECTIONAL_SEQUENCE_LSTM_OUT >, luci::CircleNodeImpl< CircleOpcode::CAST >, luci::CircleNodeImpl< CircleOpcode::CEIL >, luci::CircleNodeImpl< CircleOpcode::CONCATENATION >, luci::CircleNodeImpl< CircleOpcode::CIRCLECONST >, luci::CircleNodeImpl< CircleOpcode::CONV_2D >, luci::CircleNodeImpl< CircleOpcode::COS >, luci::CircleNodeImpl< CircleOpcode::CUSTOM >, luci::CircleNodeImpl< CircleOpcode::CIRCLECUSTOMOUT >, luci::CircleNodeImpl< CircleOpcode::DENSIFY >, luci::CircleNodeImpl< CircleOpcode::DEPTH_TO_SPACE >, luci::CircleNodeImpl< CircleOpcode::DEPTHWISE_CONV_2D >, luci::CircleNodeImpl< CircleOpcode::DEQUANTIZE >, luci::CircleNodeImpl< CircleOpcode::DIV >, luci::CircleNodeImpl< CircleOpcode::ELU >, luci::CircleNodeImpl< CircleOpcode::EQUAL >, luci::CircleNodeImpl< CircleOpcode::EXP >, luci::CircleNodeImpl< CircleOpcode::EXPAND_DIMS >, luci::CircleNodeImpl< CircleOpcode::FAKE_QUANT >, luci::CircleNodeImpl< CircleOpcode::FILL >, luci::CircleNodeImpl< CircleOpcode::FLOOR >, luci::CircleNodeImpl< CircleOpcode::FLOOR_DIV >, luci::CircleNodeImpl< CircleOpcode::FLOOR_MOD >, luci::CircleNodeImpl< CircleOpcode::FULLY_CONNECTED >, luci::CircleNodeImpl< CircleOpcode::GATHER >, luci::CircleNodeImpl< CircleOpcode::GATHER_ND >, luci::CircleNodeImpl< CircleOpcode::GREATER >, luci::CircleNodeImpl< CircleOpcode::GREATER_EQUAL >, luci::CircleNodeImpl< CircleOpcode::IF >, luci::CircleNodeImpl< CircleOpcode::CIRCLEIFOUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEINPUT >, luci::CircleNodeImpl< CircleOpcode::L2_NORMALIZATION >, luci::CircleNodeImpl< CircleOpcode::L2_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::LEAKY_RELU >, luci::CircleNodeImpl< CircleOpcode::LESS >, luci::CircleNodeImpl< CircleOpcode::LESS_EQUAL >, luci::CircleNodeImpl< CircleOpcode::LOCAL_RESPONSE_NORMALIZATION >, luci::CircleNodeImpl< CircleOpcode::LOG >, luci::CircleNodeImpl< CircleOpcode::LOG_SOFTMAX >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_AND >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_NOT >, luci::CircleNodeImpl< CircleOpcode::LOGICAL_OR >, luci::CircleNodeImpl< CircleOpcode::LOGISTIC >, luci::CircleNodeImpl< CircleOpcode::MATRIX_DIAG >, luci::CircleNodeImpl< CircleOpcode::MATRIX_SET_DIAG >, luci::CircleNodeImpl< CircleOpcode::MAX_POOL_2D >, luci::CircleNodeImpl< CircleOpcode::MAXIMUM >, luci::CircleNodeImpl< CircleOpcode::MEAN >, luci::CircleNodeImpl< CircleOpcode::MINIMUM >, luci::CircleNodeImpl< CircleOpcode::MIRROR_PAD >, luci::CircleNodeImpl< CircleOpcode::MUL >, luci::CircleNodeImpl< CircleOpcode::NEG >, luci::CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V4 >, luci::CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV4OUT >, luci::CircleNodeImpl< CircleOpcode::NON_MAX_SUPPRESSION_V5 >, luci::CircleNodeImpl< CircleOpcode::CIRCLENONMAXSUPPRESSIONV5OUT >, luci::CircleNodeImpl< CircleOpcode::NOT_EQUAL >, luci::CircleNodeImpl< CircleOpcode::ONE_HOT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTDUMMY >, luci::CircleNodeImpl< CircleOpcode::CIRCLEOUTPUTEXCLUDE >, luci::CircleNodeImpl< CircleOpcode::PRELU >, luci::CircleNodeImpl< CircleOpcode::PACK >, luci::CircleNodeImpl< CircleOpcode::PAD >, luci::CircleNodeImpl< CircleOpcode::PADV2 >, luci::CircleNodeImpl< CircleOpcode::POW >, luci::CircleNodeImpl< CircleOpcode::QUANTIZE >, luci::CircleNodeImpl< CircleOpcode::RANGE >, luci::CircleNodeImpl< CircleOpcode::RANK >, luci::CircleNodeImpl< CircleOpcode::REDUCE_ANY >, luci::CircleNodeImpl< CircleOpcode::REDUCE_MAX >, luci::CircleNodeImpl< CircleOpcode::REDUCE_MIN >, luci::CircleNodeImpl< CircleOpcode::REDUCE_PROD >, luci::CircleNodeImpl< CircleOpcode::RELU >, luci::CircleNodeImpl< CircleOpcode::RELU6 >, luci::CircleNodeImpl< CircleOpcode::RELU_N1_TO_1 >, luci::CircleNodeImpl< CircleOpcode::RESHAPE >, luci::CircleNodeImpl< CircleOpcode::RESIZE_BILINEAR >, luci::CircleNodeImpl< CircleOpcode::RESIZE_NEAREST_NEIGHBOR >, luci::CircleNodeImpl< CircleOpcode::REVERSE_SEQUENCE >, luci::CircleNodeImpl< CircleOpcode::REVERSE_V2 >, luci::CircleNodeImpl< CircleOpcode::ROUND >, luci::CircleNodeImpl< CircleOpcode::RSQRT >, luci::CircleNodeImpl< CircleOpcode::SVDF >, luci::CircleNodeImpl< CircleOpcode::SCATTER_ND >, luci::CircleNodeImpl< CircleOpcode::SEGMENT_SUM >, luci::CircleNodeImpl< CircleOpcode::SELECT >, luci::CircleNodeImpl< CircleOpcode::SELECT_V2 >, luci::CircleNodeImpl< CircleOpcode::SHAPE >, luci::CircleNodeImpl< CircleOpcode::SIN >, luci::CircleNodeImpl< CircleOpcode::SLICE >, luci::CircleNodeImpl< CircleOpcode::SOFTMAX >, luci::CircleNodeImpl< CircleOpcode::SPACE_TO_BATCH_ND >, luci::CircleNodeImpl< CircleOpcode::SPACE_TO_DEPTH >, luci::CircleNodeImpl< CircleOpcode::SPARSE_TO_DENSE >, luci::CircleNodeImpl< CircleOpcode::SPLIT >, luci::CircleNodeImpl< CircleOpcode::CIRCLESPLITOUT >, luci::CircleNodeImpl< CircleOpcode::SPLIT_V >, luci::CircleNodeImpl< CircleOpcode::CIRCLESPLITVOUT >, luci::CircleNodeImpl< CircleOpcode::SQRT >, luci::CircleNodeImpl< CircleOpcode::SQUARE >, luci::CircleNodeImpl< CircleOpcode::SQUARED_DIFFERENCE >, luci::CircleNodeImpl< CircleOpcode::SQUEEZE >, luci::CircleNodeImpl< CircleOpcode::STRIDED_SLICE >, luci::CircleNodeImpl< CircleOpcode::SUB >, luci::CircleNodeImpl< CircleOpcode::SUM >, luci::CircleNodeImpl< CircleOpcode::TANH >, luci::CircleNodeImpl< CircleOpcode::TILE >, luci::CircleNodeImpl< CircleOpcode::TOPK_V2 >, luci::CircleNodeImpl< CircleOpcode::CIRCLETOPKV2OUT >, luci::CircleNodeImpl< CircleOpcode::TRANSPOSE >, luci::CircleNodeImpl< CircleOpcode::TRANSPOSE_CONV >, luci::CircleNodeImpl< CircleOpcode::UNIDIRECTIONAL_SEQUENCE_LSTM >, luci::CircleNodeImpl< CircleOpcode::UNIQUE >, luci::CircleNodeImpl< CircleOpcode::CIRCLEUNIQUEOUT >, luci::CircleNodeImpl< CircleOpcode::UNPACK >, luci::CircleNodeImpl< CircleOpcode::CIRCLEUNPACKOUT >, luci::CircleNodeImpl< CircleOpcode::CIRCLEVARIABLE >, luci::CircleNodeImpl< CircleOpcode::WHERE >, luci::CircleNodeImpl< CircleOpcode::WHILE >, luci::CircleNodeImpl< CircleOpcode::CIRCLEWHILEOUT >, and luci::CircleNodeImpl< CircleOpcode::ZEROS_LIKE >.
Referenced by accept(), luci::activation_qtype(), luci_interpreter::KernelBuilder::build(), luci::fuse_activation_function(), luci::fuse_add_with_conv(), luci_interpreter::GraphLoader::loadTensors(), dalgona::outputPyArray(), record_minmax::MinMaxObserver::postTensorWrite(), luci::FuseActivationFunctionPass::run(), luci::validate_unique_name(), dalgona::PostOperatorHook::visit(), dalgona::PreOperatorHook::visit(), and luci::QuantizeActivation::visit().
quantparam() [1/2]
void luci::CircleNode::quantparam (std::unique_ptr< CircleQuantParam > && quantparam) inline
Definition at line 53 of file CircleNodeDecl.h.
  {
    _quantparam = std::move(quantparam);
  }
References quantparam().
quantparam() [2/2]
CircleQuantParam * luci::CircleNode::quantparam (void) const inline
Definition at line 52 of file CircleNodeDecl.h.
{ return _quantparam.get(); }
Referenced by luci::copy_quantparam(), luci::copy_tensor_attributes(), luci::is_quantized(), luci_interpreter::GraphLoader::loadTensors(), luci::propagate_pad_v2_quantparam(), luci::quant_const(), quantparam(), luci::set_int_scale(), luci::QuantizeActivation::visit(), luci::QuantizeSpecialActivation::visit(), and luci::warn_accuracy_with_range().
shape_status() [1/2]
void luci::CircleNode::shape_status (ShapeStatus ss) inline
Definition at line 65 of file CircleNodeDecl.h.
{ _shape_status = ss; }
shape_status() [2/2]
ShapeStatus luci::CircleNode::shape_status (void) const inline
Definition at line 64 of file CircleNodeDecl.h.
{ return _shape_status; }
Referenced by luci::GraphBuilder::build(), luci::CircleConstNodeBuilder::build(), and luci::copy_common_attributes().
sparsityparam() [1/2]
void luci::CircleNode::sparsityparam (std::unique_ptr< SparsityParam > && sparsityparam) inline
Definition at line 59 of file CircleNodeDecl.h.
  {
    _sparsityparam = std::move(sparsityparam);
  }
References sparsityparam().
sparsityparam() [2/2]
SparsityParam * luci::CircleNode::sparsityparam (void) const inline
Definition at line 58 of file CircleNodeDecl.h.
{ return _sparsityparam.get(); }
Referenced by luci::copy_common_attributes(), luci::copy_tensor_attributes(), luci::SparsifyTensorPass::sparsify_tensor(), and sparsityparam().
The documentation for this struct was generated from the following files:
compiler/luci/lang/include/luci/IR/CircleNodeDecl.h
compiler/luci/lang/include/luci/IR/CircleNodeImpl.h
compiler/luci/lang/src/CircleNode.cpp