ONE - On-device Neural Engine: InstrPrinter Struct Reference
InstrPrinter Struct Reference final
Public Member Functions
InstrPrinter ()=delete
InstrPrinter (int indent)
void visit (const coco::Eval *ins) override
void visit (const coco::Copy *ins) override
void visit (const coco::Shuffle *ins) override
Public Member Functions inherited from coco::Instr::Visitor< pp::LinearDocument >
virtual ~Visitor ()=default
Public Member Functions inherited from coco::Instr::IVisitor< T >
virtual ~IVisitor ()=default
Public Member Functions inherited from coco::Instr::Visitor< void >
virtual ~Visitor ()=default
Detailed Description
Definition at line 137 of file Dump.cpp.
Constructor & Destructor Documentation
InstrPrinter() [1/2]
InstrPrinter::InstrPrinter () delete
InstrPrinter() [2/2]
InstrPrinter::InstrPrinter (int indent) inline
Definition at line 142 of file Dump.cpp.
: _indent(indent) {}
Member Function Documentation
visit() [1/3]
void InstrPrinter::visit (const coco::Copy * ins) inline override
Definition at line 156 of file Dump.cpp.
  {
    // copy is Producer and also Customer. We will use address for Producer
    std::cout << tab(_indent) << "Copy (" << dynamic_cast<const coco::Instr *>(ins) << ")"
              << std::endl;
    std::cout << tab(_indent) << "  from: " << ins->from() << std::endl;
    std::cout << tab(_indent) << "  into: " << ins->into() << std::endl;
  }
References coco::Copy::from(), coco::Copy::into(), and tab().
visit() [2/3]
void InstrPrinter::visit (const coco::Eval * ins) inline override
Definition at line 144 of file Dump.cpp.
  {
    std::cout << tab(_indent) << "Eval (" << dynamic_cast<const coco::Instr *>(ins) << ")"
              << std::endl;
    std::cout << tab(_indent + 1) << "out: " << ins->out() << std::endl;
    std::cout << tab(_indent + 1) << "<op>: " << std::endl;
    {
      OpPrinter prn(std::cout, _indent + 2);
      ins->op()->accept(prn);
    }
  }
References coco::Op::accept(), coco::Eval::op(), coco::Eval::out(), and tab().
visit() [3/3]
void InstrPrinter::visit (const coco::Shuffle * ins) inline override
Definition at line 165 of file Dump.cpp.
  {
    std::cout << tab(_indent) << "Shuffle (" << dynamic_cast<const coco::Instr *>(ins) << ")"
              << std::endl;
    std::cout << tab(_indent) << "  from: " << ins->from() << std::endl;
    std::cout << tab(_indent) << "  into: " << ins->into() << std::endl;
  }
References coco::Shuffle::from(), coco::Shuffle::into(), and tab().
The documentation for this struct was generated from the following file:
compiler/encodump/src/Dump.cpp