ONE - On-device Neural Engine: luci::tinf::Rule Struct Reference
luci::tinf::Rule Struct Reference
#include <CircleTypeInference.h>
Public Member Functions
bool infer (const luci::CircleNode *, loco::DataType &) const
Detailed Description
Definition at line 32 of file CircleTypeInference.h.
Member Function Documentation
infer()
bool luci::tinf::Rule::infer (const luci::CircleNode * circle_node, loco::DataType & dtype) const
Definition at line 48 of file CircleTypeInference.cpp.
{
  LOGGER(l);
  VERBOSE(l, 1) << "[CircleTypeInference] " << circle_node->name();
  VERBOSE(l, 1) << "  before: " << static_cast<int>(circle_node->dtype());
  if (!inputs_dtype_ready(circle_node))
  {
    VERBOSE(l, 1) << "   after: Some inputs are not ready for inference";
    return false;
  }
  Algorithm alg;
  dtype = circle_node->accept(&alg);
  VERBOSE(l, 1) << "   after: " << static_cast<int>(dtype);
  return true;
}
References luci::CircleNode::accept(), LOGGER, luci::CircleNode::name(), and VERBOSE.
Referenced by luci::CircleTypeInferencePass::run().
The documentation for this struct was generated from the following files:
compiler/luci/service/include/luci/Service/CircleTypeInference.h
compiler/luci/service/src/CircleTypeInference.cpp