ONE - On-device Neural Engine: loco::TypeInferenceRule Struct Reference
loco::TypeInferenceRule Struct Reference abstract
#include <TypeInference.h>
Public Member Functions
virtual ~TypeInferenceRule ()=default
virtual bool recognize (const Dialect *) const =0
Return true if this rule recognizes a given dialect.
virtual bool infer (const Node *, DataType &) const =0
Detailed Description
Definition at line 41 of file TypeInference.h.
Constructor & Destructor Documentation
~TypeInferenceRule()
virtual loco::TypeInferenceRule::~TypeInferenceRule () virtual default
Member Function Documentation
infer()
virtual bool loco::TypeInferenceRule::infer (const Node * , DataType &) const pure virtual
Framework guarantees the followings:
Framework tries to infer the data type of each node only after the data type of all of its valid (= non-nullptr) argument nodes is inferred.
The result of preceding "infer" is accessible through below dtype_get method.
This holds only when preceding "infer" returns true.
Implemented in locoex::CircleTypeInferenceRule, locoex::TFLTypeInferenceRule, locoex::COpTypeInferenceRule, luci::CircleTypeInferenceRule, moco::TFTypeInferenceRule, loco::CanonicalTypeInferenceRule, and loco::MultiDialectTypeInferenceRule.
Referenced by loco::TypeInferenceSession::to().
recognize()
virtual bool loco::TypeInferenceRule::recognize (const Dialect *) const pure virtual
Return true if this rule recognizes a given dialect.
Implemented in loco::CanonicalTypeInferenceRule, loco::MultiDialectTypeInferenceRule, locoex::CircleTypeInferenceRule, locoex::TFLTypeInferenceRule, locoex::COpTypeInferenceRule, luci::CircleTypeInferenceRule, and moco::TFTypeInferenceRule.
Referenced by loco::MultiDialectTypeInferenceRule::bind(), and loco::TypeInferenceSession::to().
The documentation for this struct was generated from the following file:
compiler/loco/include/loco/Service/TypeInference.h