ONE - On-device Neural Engine: luci::pass::Expression Struct Reference
luci::pass::Expression Struct Reference final
#include <ExpressionCache.h>
Data Structures
struct Hash
Static Public Member Functions
static Expression build (luci::CircleNode *node)
Data Fields
std::vector< loco::Node * > inputs
luci::CircleNode * op = nullptr
Detailed Description
Definition at line 31 of file ExpressionCache.h.
Member Function Documentation
build()
Expression luci::pass::Expression::build (luci::CircleNode * node) static
Definition at line 169 of file ExpressionCache.cpp.
{
  if (node == nullptr)
    throw std::invalid_argument("node");
  Expression key;
  {
    switch (node->opcode())
    {
      case luci::CircleOpcode::QUANTIZE:
      case luci::CircleOpcode::TRANSPOSE:
        key.inputs.emplace_back(node->arg(0));
        break;
      // TODO Add more Ops
      default:
        // NYI. Return invalid expression
        key.op = nullptr;
        return key;
    }
    key.op = node;
  }
  return key;
}
References loco::Node::arg(), inputs, op, and luci::CircleNode::opcode().
Referenced by luci::CommonSubExpressionEliminationPass::run().
Field Documentation
inputs
std::vector<loco::Node *> luci::pass::Expression::inputs
Definition at line 39 of file ExpressionCache.h.
Referenced by build(), validate_onnx2circle.OnnxRunner::feed_random_inputs(), luci::pass::operator==(), and package.libnnfw_api_pybind.nnfw_session_wrapper::set_inputs().
op
luci::CircleNode* luci::pass::Expression::op = nullptr
Definition at line 40 of file ExpressionCache.h.
Referenced by build(), and luci::pass::operator==().
The documentation for this struct was generated from the following files:
compiler/luci/pass/src/helpers/ExpressionCache.h
compiler/luci/pass/src/helpers/ExpressionCache.cpp