ONE - On-device Neural Engine: enco::Code Struct Reference
enco::Code Struct Reference
#include <Code.h>
Public Member Functions
Code (coco::Module *module, coco::Data *data)
coco::Module * module (void) const
coco::Data * data (void) const
Detailed Description
Definition at line 28 of file Code.h.
Constructor & Destructor Documentation
Code()
enco::Code::Code (coco::Module * module, coco::Data * data) inline
Definition at line 31 of file Code.h.
                                           : _module{module}, _data{data}
  {
    // DO NOTHING
  }
Member Function Documentation
data()
coco::Data * enco::Code::data (void) const inline
Definition at line 38 of file Code.h.
{ return _data; }
Referenced by enco::CppCode::dump(), and enco::generate_global_data().
module()
coco::Module * enco::Code::module (void) const inline
Definition at line 37 of file Code.h.
{ return _module; }
Referenced by enco::CppCode::dump(), enco::eliminate_dead_bag(), enco::eliminate_dead_object(), enco::eliminate_indirect_copy(), enco::generate_bypass_shuffle(), enco::generate_global_data(), enco::hoist_object(), enco::lower_concat(), enco::lower_copy(), enco::reduce_duplicated_object(), enco::reduce_identical_object(), enco::select_intrinsic(), enco::unify_feature(), and enco::validate_output_shape().
The documentation for this struct was generated from the following file:
compiler/enco/core/src/Code.h