ONE - On-device Neural Engine: compiler/angkor/src/ADT/tensor/IndexEnumerator.cpp File Reference
IndexEnumerator.cpp File Reference
#include "nncc/core/ADT/tensor/IndexEnumerator.h"
#include <cassert>
Namespaces
namespace nncc
namespace nncc::core
namespace nncc::core::ADT
namespace nncc::core::ADT::tensor
Functions
uint32_t axis_of (const Shape &shape, uint32_t cursor)
Function Documentation
axis_of()
uint32_t axis_of (const Shape & shape, uint32_t cursor) inline
Definition at line 23 of file IndexEnumerator.cpp.
{
  const uint32_t rank = shape.rank();
  assert(cursor < rank);
  return rank - cursor - 1;
}
References nncc::core::ADT::tensor::Shape::rank().
Referenced by nncc::core::ADT::tensor::IndexEnumerator::advance(), and nncc::core::ADT::tensor::IndexEnumerator::IndexEnumerator().