ONE - On-device Neural Engine: compiler/tflchef/core/src/Convert.cpp File Reference
Convert.cpp File Reference
#include "Convert.h"
#include <stdexcept>
Namespaces
namespace sparsity
Functions
tflite::Padding as_tflite_padding (const tflchef::Padding &value)
tflite::ActivationFunctionType as_tflite_activation (const tflchef::Activation &value)
tflite::TensorType as_tflite_tensortype (const tflchef::TensorType &value)
tflite::MirrorPadMode as_tflite_mirrorpadmode (const tflchef::MirrorPadMode &value)
tflite::DimensionType as_tflite_dimensiontype (const tflchef::DimensionType &value)
tflite::SparseIndexVector as_tflite_sparse_idx_vec_type (const tflchef::SparseIndexVecType &value)
flatbuffers::Offset< void > as_tflite_sparse_index_vec (flatbuffers::FlatBufferBuilder &fb, const ::tflchef::TensorSparsity_IndexVec &value)
Function Documentation
as_tflite_activation()
tflite::ActivationFunctionType as_tflite_activation (const tflchef::Activation & value)
Definition at line 37 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::NONE:
      return tflite::ActivationFunctionType_NONE;
    case tflchef::RELU:
      return tflite::ActivationFunctionType_RELU;
    case tflchef::RELU_N1_TO_1:
      return tflite::ActivationFunctionType_RELU_N1_TO_1;
    case tflchef::RELU6:
      return tflite::ActivationFunctionType_RELU6;
    case tflchef::TANH:
      return tflite::ActivationFunctionType_TANH;
    case tflchef::SIGN_BIT:
      return tflite::ActivationFunctionType_SIGN_BIT;
    default:
      break;
  }
  throw std::runtime_error{"Unknown activation"};
}
Referenced by AddChef::value(), AveragePool2DChef::value(), BidirectionalSequenceLSTMChef::value(), ConcatenationChef::value(), Conv2DChef::value(), DepthwiseConv2DChef::value(), DivChef::value(), FullyConnectedChef::value(), L2Normalize::value(), L2Pool2DChef::value(), MaxPool2DChef::value(), MulChef::value(), SubChef::value(), SVDFChef::value(), and UnidirectionalSequenceLSTMChef::value().
as_tflite_dimensiontype()
tflite::DimensionType as_tflite_dimensiontype (const tflchef::DimensionType & value)
Definition at line 102 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::DimensionType::DENSE:
      return tflite::DimensionType_DENSE;
    case tflchef::DimensionType::SPARSE_CSR:
      return tflite::DimensionType_SPARSE_CSR;
    default:
      break;
  }
  throw std::runtime_error("Unknown dimension type");
}
as_tflite_mirrorpadmode()
tflite::MirrorPadMode as_tflite_mirrorpadmode (const tflchef::MirrorPadMode & value)
Definition at line 87 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::REFLECT:
      return tflite::MirrorPadMode_REFLECT;
    case tflchef::SYMMETRIC:
      return tflite::MirrorPadMode_SYMMETRIC;
    default:
      break;
  }
  throw std::runtime_error{"Unknown mirrorpad mode"};
}
Referenced by MirrorPadChef::value().
as_tflite_padding()
tflite::Padding as_tflite_padding (const tflchef::Padding & value)
Definition at line 22 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::SAME:
      return tflite::Padding_SAME;
    case tflchef::VALID:
      return tflite::Padding_VALID;
    default:
      break;
  }
  throw std::runtime_error{"Unknown padding value"};
}
Referenced by AveragePool2DChef::value(), Conv2DChef::value(), DepthwiseConv2DChef::value(), L2Pool2DChef::value(), MaxPool2DChef::value(), and TransposeConvChef::value().
as_tflite_sparse_idx_vec_type()
tflite::SparseIndexVector as_tflite_sparse_idx_vec_type (const tflchef::SparseIndexVecType & value)
Definition at line 117 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::SparseIndexVecType::SparseIdxVecType_NONE:
      return tflite::SparseIndexVector_NONE;
    case tflchef::SparseIndexVecType::INT32VEC:
      return tflite::SparseIndexVector_Int32Vector;
    case tflchef::SparseIndexVecType::UINT16VEC:
      return tflite::SparseIndexVector_Uint16Vector;
    case tflchef::SparseIndexVecType::UINT8VEC:
      return tflite::SparseIndexVector_Uint8Vector;
    default:
      break;
  }
  throw std::runtime_error("Unknown SparseIndexVector type");
}
as_tflite_sparse_index_vec()
flatbuffers::Offset< void > as_tflite_sparse_index_vec (flatbuffers::FlatBufferBuilder & fb, const ::tflchef::TensorSparsity_IndexVec & value)
Definition at line 137 of file Convert.cpp.
{
  auto sparse_idx_type = value.type();
  switch (sparse_idx_type)
  {
    case tflchef::SparseIndexVecType::SparseIdxVecType_NONE:
      return flatbuffers::Offset<void>();
    case tflchef::SparseIndexVecType::INT32VEC:
    {
      auto values_vec_int32 = std::vector<int32_t>{value.dim().begin(), value.dim().end()};
      auto values_int32 = fb.CreateVector(values_vec_int32);
      return tflite::CreateInt32Vector(fb, values_int32).Union();
    }
    case tflchef::SparseIndexVecType::UINT16VEC:
    {
      auto values_vec_uint16 = std::vector<uint16_t>{value.dim().begin(), value.dim().end()};
      auto values_uint16 = fb.CreateVector(values_vec_uint16);
      return tflite::CreateUint16Vector(fb, values_uint16).Union();
    }
    case tflchef::SparseIndexVecType::UINT8VEC:
    {
      auto values_vec_uint8 = std::vector<uint8_t>{value.dim().begin(), value.dim().end()};
      auto values_uint8 = fb.CreateVector(values_vec_uint8);
      return tflite::CreateUint8Vector(fb, values_uint8).Union();
    }
    default:
      break;
  }
  throw std::runtime_error("Unknown SparseIndexVector type");
}
as_tflite_tensortype()
tflite::TensorType as_tflite_tensortype (const tflchef::TensorType & value)
Definition at line 60 of file Convert.cpp.
{
  switch (value)
  {
    case tflchef::FLOAT32:
      return tflite::TensorType_FLOAT32;
    case tflchef::FLOAT16:
      return tflite::TensorType_FLOAT16;
    case tflchef::INT32:
      return tflite::TensorType_INT32;
    case tflchef::UINT8:
      return tflite::TensorType_UINT8;
    case tflchef::INT64:
      return tflite::TensorType_INT64;
    case tflchef::STRING:
      return tflite::TensorType_STRING;
    case tflchef::BOOL:
      return tflite::TensorType_BOOL;
    case tflchef::INT16:
      return tflite::TensorType_INT16;
    default:
      break;
  }
  throw std::runtime_error{"Unknown tensor type"};
}
Referenced by ArgMaxChef::value(), ArgMinChef::value(), CastChef::value(), ShapeChef::value(), and UniqueChef::value().