ONE - On-device Neural Engine: compiler/enco/frontend/tflite/src/IRBuilder.h File Reference
IRBuilder.h File Reference
coco IR builders. This is code is copied from enco caffe frontend.
#include "coco/IR/Module.h"
#include <deque>
Data Structures
class OpBuilder
class InstrBuilder
Typedefs
using ModuleHandle = std::unique_ptr< coco::Module >
Functions
OpBuilder op_builder (coco::Module *m)
OpBuilder op_builder (const std::unique_ptr< coco::Module > &m)
InstrBuilder instr_builder (coco::Module *m)
InstrBuilder instr_builder (const ModuleHandle &m)
Detailed Description
coco IR builders. This is code is copied from enco caffe frontend.
Definition in file IRBuilder.h.
Typedef Documentation
ModuleHandle
using ModuleHandle = std::unique_ptr<coco::Module>
Definition at line 173 of file IRBuilder.h.
Function Documentation
instr_builder() [1/2]
InstrBuilder instr_builder (coco::Module * m) inline
Definition at line 175 of file IRBuilder.h.
{ return InstrBuilder{m}; }
References m.
Referenced by instr_builder().
instr_builder() [2/2]
InstrBuilder instr_builder (const ModuleHandle & m) inline
Definition at line 176 of file IRBuilder.h.
{ return instr_builder(m.get()); }
References instr_builder(), and m.
op_builder() [1/2]
OpBuilder op_builder (coco::Module * m) inline
Definition at line 130 of file IRBuilder.h.
{ return OpBuilder{m}; }
References m.
Referenced by op_builder().
op_builder() [2/2]
OpBuilder op_builder (const std::unique_ptr< coco::Module > & m) inline
Definition at line 131 of file IRBuilder.h.
{ return op_builder(m.get()); }
References m, and op_builder().