ONE - On-device Neural Engine: compiler/nnc/utils/tflite_dot_dumper/model_dump.cpp File Reference
model_dump.cpp File Reference
#include "support/CommandLine.h"
#include "mir/IrDotDumper.h"
#include <tflite_importer.h>
#include <exception>
#include <iostream>
Functions
int main (int argc, const char **argv)
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 28 of file model_dump.cpp.
{
  cli::Option<std::string> model_path(cli::optname("--model"), cli::overview("Path to the model"));
  cli::CommandLine::getParser()->parseCommandLine(argc, argv);
  try
  {
    auto graph = mir_tflite::loadModel(model_path);
    dumpGraph(graph.get(), std::cout);
  }
  catch (std::exception &e)
  {
    std::cout << "Error: " << e.what() << std::endl;
    return -1;
  }
  return 0;
}
References mir::dumpGraph(), nnc::cli::CommandLine::getParser(), mir_tflite::loadModel(), and nnc::cli::CommandLine::parseCommandLine().