ONE - On-device Neural Engine: compiler/mir/unittests/Operation.cpp File Reference
Operation.cpp File Reference
#include "mir/Operation.h"
#include "mir/ops/ConcatOp.h"
#include "mir/ops/InputOp.h"
#include "mir/ops/ReshapeOp.h"
#include "mir/ops/SoftmaxOp.h"
#include <gtest/gtest.h>
#include "mir/Operations.inc"
Macros
#define HANDLE_OP(OpType, OpClass) ASSERT_EQ(getTypeName(Operation::Type::OpType), #OpType);
Functions
TEST (Operation, ConnectionTest)
TEST (Operation, InputOutputShapeTest)
TEST (Operation, SoftmaxAxisTest)
TEST (Operation, ConcatAxisTest)
TEST (Operation, OpNameTest)
Macro Definition Documentation
HANDLE_OP
#define HANDLE_OP (OpType, OpClass) ASSERT_EQ(getTypeName(Operation::Type::OpType), #OpType);
Function Documentation
TEST() [1/5]
TEST (Operation , ConcatAxisTest)
Definition at line 71 of file Operation.cpp.
{
  Shape in_shape{1, 2, 3};
  mir::TensorType in_type{mir::DataType::FLOAT32, in_shape};
  ops::InputOp input1(in_type), input2(in_type);
  ops::ConcatOp op_1({input1.getOutput(0), input2.getOutput(0)}, 1);
  ASSERT_EQ(op_1.getAxis(), 1);
  ops::ConcatOp op_n1({input1.getOutput(0), input2.getOutput(0)}, -1);
  ASSERT_EQ(op_n1.getAxis(), 2);
  ops::ConcatOp op_n3({input1.getOutput(0), input2.getOutput(0)}, -3);
  ASSERT_EQ(op_n3.getAxis(), 0);
}
References mir::Operation::getOutput().
TEST() [2/5]
TEST (Operation , ConnectionTest)
Definition at line 27 of file Operation.cpp.
{
  mir::TensorType input_type{mir::DataType::FLOAT32, Shape{}};
  auto op1 = new ops::InputOp(input_type);
  op1->setId(0);
  auto op2 = new ops::ReshapeOp(op1->getOutput(0), Shape{});
  op2->setId(1);
  ASSERT_EQ(op1, op2->getInput(0)->getNode());
  delete op1;
  delete op2;
}
TEST() [3/5]
TEST (Operation , InputOutputShapeTest)
Definition at line 42 of file Operation.cpp.
{
  Shape input_shape{1, 2, 3};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  ops::InputOp input(input_type);
  ops::SoftmaxOp op(input.getOutput(0), 0);
  ASSERT_EQ(input_shape, input.getOutputShape(0));
  ASSERT_EQ(input_shape, op.getInputShape(0));
}
References mir::Operation::getInputShape().
TEST() [4/5]
TEST (Operation , OpNameTest)
Definition at line 88 of file Operation.cpp.
{
#define HANDLE_OP(OpType, OpClass) ASSERT_EQ(getTypeName(Operation::Type::OpType), #OpType);
#include "mir/Operations.inc"
#undef HANDLE_OP
}
TEST() [5/5]
TEST (Operation , SoftmaxAxisTest)
Definition at line 54 of file Operation.cpp.
{
  Shape input_shape{1, 2, 3};
  mir::TensorType input_type{mir::DataType::FLOAT32, input_shape};
  ops::InputOp input(input_type);
  ops::SoftmaxOp op_1(input.getOutput(0), 1);
  ASSERT_EQ(op_1.getAxis(), 1);
  ops::SoftmaxOp op_n1(input.getOutput(0), -1);
  ASSERT_EQ(op_n1.getAxis(), 2);
  ops::SoftmaxOp op_n3(input.getOutput(0), -3);
  ASSERT_EQ(op_n3.getAxis(), 0);
}
References mir::ops::SoftmaxOp::getAxis().