ONE - On-device Neural Engine: compiler/nnc/unittests/soft_backend/ModelAnalyzer.cpp File Reference
ModelAnalyzer.cpp File Reference
#include "ModelAnalyzer.h"
#include "mir/Graph.h"
#include "mir/ops/InputOp.h"
#include "mir/ops/ReluOp.h"
#include "mir/ops/ConcatOp.h"
#include <gtest/gtest.h>
#include <algorithm>
Functions
TEST (ModelAnalyzer, linearization)
Function Documentation
TEST()
TEST (ModelAnalyzer , linearization)
Definition at line 40 of file ModelAnalyzer.cpp.
{
  mir::Graph g;
  /*
   * Create graph:
   *      [input]
   *     /       \
   *    |         |
   *    V         V
   * [head1]   [head2]
   *    |         |
   *    V         V
   * [tail1]   [tail2]
   *     \       /
   *      \     /
   *      [join]
   */
  mir::TensorType input_type{mir::DataType::FLOAT32, Shape{1, 2, 3}};
  Operation *input = g.create<ops::InputOp>(input_type);
  Operation *head1 = g.create<ops::ReluOp>(input->getOutput(0));
  Operation *head2 = g.create<ops::ReluOp>(input->getOutput(0));
  Operation *tail1 = g.create<ops::ReluOp>(head1->getOutput(0));
  Operation *tail2 = g.create<ops::ReluOp>(head2->getOutput(0));
  vector<mir::Operation::Output *> concat_inputs{tail1->getOutput(0), tail2->getOutput(0)};
  Operation *join = g.create<ops::ConcatOp>(concat_inputs, 0);
  input->getOutput(0)->setName("input");
  head1->getOutput(0)->setName("head1");
  head2->getOutput(0)->setName("head2");
  tail1->getOutput(0)->setName("tail2");
  tail2->getOutput(0)->setName("tail2");
  join->getOutput(0)->setName("join");
  // Check that layout is desired
  ModelAnalyzer ma;
  ma.analyze(&g);
  const auto &seq = ma.getInferenceSequence();
  ASSERT_EQ(seq.size(), 6u);
  vector<Operation *> op_seq(seq.size());
  transform(seq.cbegin(), seq.cend(), op_seq.begin(),
            [](const unique_ptr<sir::Action> &action) { return getCall(action)->mirOp; });
  vector<Operation *> valid_seq1{input, head1, tail1, head2, tail2, join};
  vector<Operation *> valid_seq2{input, head2, tail2, head1, tail1, join};
  ASSERT_TRUE(op_seq == valid_seq1 || op_seq == valid_seq2);
}
References nnc::ModelAnalyzer::analyze(), nnc::ModelAnalyzer::getInferenceSequence(), and mir::Operation::getOutput().