#!/bin/bash

# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage()
{
  echo "Optimize circle model."
  echo "Usage: one-optimize"
  echo "    --version       Show version information and exit"
  echo "    --all           Enable all optimization algorithms"
  echo "    --fold_dequantize"
  echo "                    Enable FoldDequantize Pass"
  echo "    --fuse_add_with_tconv"
  echo "                    Enable FuseAddWithTConv Pass"
  echo "    --fuse_bcq      Enable FuseBCQ Pass"
  echo "    --fuse_instnorm Enable FuseInstanceNormalization Pass"
  echo "    --resolve_customop_add"
  echo "                    Enable ResolveCustomOpAddPass Pass"
  echo "    --resolve_customop_batchmatmul"
  echo "                    Enable ResolveCustomOpBatchMatMulPass Pass"
  echo "    --resolve_customop_matmul"
  echo "                    Enable ResolveCustomOpMatMulPass Pass"
  echo "    --input_path <path/to/input/circle>"
  echo "    --output_path <path/to/output/circle>"
  exit 255
}

version()
{
  $DRIVER_PATH/one-version one-optimize
  exit 255
}

OPTIMIZE_all=0
OPTIMIZE_fold_dequantize=0
OPTIMIZE_fuse_add_with_tconv=0
OPTIMIZE_fuse_bcq=0
OPTIMIZE_fuse_instnorm=0
OPTIMIZE_resolve_customop_add=0
OPTIMIZE_resolve_customop_batchmatmul=0
OPTIMIZE_resolve_customop_matmul=0

# Parse command-line arguments
#
while [ "$#" -ne 0 ]; do
  CUR="$1"

  case $CUR in
    '--help')
      usage
      ;;
    '--version')
      version
      ;;
    '--all')
      OPTIMIZE_all=1
      shift
      ;;
    '--fold_dequantize')
      OPTIMIZE_fold_dequantize=1
      shift
      ;;
    '--fuse_add_with_tconv')
      OPTIMIZE_fuse_add_with_tconv=1
      shift
      ;;
    '--fuse_bcq')
      OPTIMIZE_fuse_bcq=1
      shift
      ;;
    '--fuse_instnorm')
      OPTIMIZE_fuse_instnorm=1
      shift
      ;;
    '--resolve_customop_add')
      OPTIMIZE_resolve_customop_add=1
      shift
      ;;
    '--resolve_customop_batchmatmul')
      OPTIMIZE_resolve_customop_batchmatmul=1
      shift
      ;;
    '--resolve_customop_matmul')
      OPTIMIZE_resolve_customop_matmul=1
      shift
      ;;

    '--input_path')
      export INPUT_PATH="$2"
      shift 2
      ;;
    '--output_path')
      export OUTPUT_PATH="$2"
      shift 2
      ;;
    *)
      echo "Unknown parameter: ${CUR}"
      shift
      ;;
  esac
done

if [ -z ${INPUT_PATH} ] || [ ! -e ${INPUT_PATH} ]; then
  echo "Error: input model not found"
  echo ""
  usage
fi

OPTIMIZE_OPTIONS=""

if [ $OPTIMIZE_all == 1 ]; then
  OPTIMIZE_OPTIONS+="--all "
fi
if [ $OPTIMIZE_fold_dequantize == 1 ]; then
  OPTIMIZE_OPTIONS+="--fold_dequantize "
fi
if [ $OPTIMIZE_fuse_add_with_tconv == 1 ]; then
  OPTIMIZE_OPTIONS+="--fuse_add_with_tconv "
fi
if [ $OPTIMIZE_fuse_bcq == 1 ]; then
  OPTIMIZE_OPTIONS+="--fuse_bcq "
fi
if [ $OPTIMIZE_fuse_instnorm == 1 ]; then
  OPTIMIZE_OPTIONS+="--fuse_instnorm "
fi
if [ $OPTIMIZE_resolve_customop_add == 1 ]; then
  OPTIMIZE_OPTIONS+="--resolve_customop_add "
fi
if [ $OPTIMIZE_resolve_customop_batchmatmul == 1 ]; then
  OPTIMIZE_OPTIONS+="--resolve_customop_batchmatmul "
fi
if [ $OPTIMIZE_resolve_customop_matmul == 1 ]; then
  OPTIMIZE_OPTIONS+="--resolve_customop_matmul "
fi

# remove previous log
rm -rf "${OUTPUT_PATH}.log"

show_err_onexit()
{
  cat "${OUTPUT_PATH}.log"
}

trap show_err_onexit ERR

# NOTE do not wrap ${OPTIMIZE_OPTIONS} with ""
# optimize circle
echo "${DRIVER_PATH}/circle2circle" ${OPTIMIZE_OPTIONS} \
"${INPUT_PATH}" "${OUTPUT_PATH}" > "${OUTPUT_PATH}.log"

"${DRIVER_PATH}/circle2circle" ${OPTIMIZE_OPTIONS} \
"${INPUT_PATH}" "${OUTPUT_PATH}" >> "${OUTPUT_PATH}.log" 2>&1
