#!/bin/bash

# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage()
{
  echo "Convert TensorFlow model with BCQ to circle."
  echo "Usage: one-import-bcq"
  echo "    --version Show version information and exit"
  echo "    --input_path <path/to/tfmodel/with/BCQ>"
  echo "    --output_path <path/to/circle>"
  echo "    --input_arrays <names of the input arrays, comma-separated>"
  echo "    --input_shapes <input shapes, colon-separated>"
  echo "    --output_arrays <names of the output arrays, comma-separated>"
  echo "    --v2 Use TensorFlow 2.x interface (default is 1.x interface)"
  exit 255
}

version()
{
  $DRIVER_PATH/one-version one-import-bcq
  exit 255
}

input_not_set()
{
  echo "Error: input_path not set"
  echo ""
  usage
}

output_not_set()
{
  echo "Error: output_path not set"
  echo ""
  usage
}

input_arrays_not_set()
{
  echo "Error: input_arrays not set"
  echo ""
  usage
}

input_shapes_not_set()
{
  echo "Error: input_shapes not set"
  echo ""
  usage
}

output_arrays_not_set()
{
  echo "Error: output_arrays not set"
  echo ""
  usage
}

TF_INTERFACE="--v1"

# Parse command-line arguments
#
while [ "$#" -ne 0 ]; do
  CUR="$1"

  case $CUR in
    '--help')
      usage
      ;;
    '--version')
      version
      ;;
    '--input_path')
      export INPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        input_not_set
      fi
      shift 2
      ;;
    '--output_path')
      export OUTPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        output_not_set
      fi
      shift 2
      ;;
    '--input_arrays')
      export INPUT_ARRAYS="$2"
      if [ $# -lt 2 ]; then
        input_arrays_not_set
      fi
      shift 2
      ;;
    '--input_shapes')
      export INPUT_SHAPES="$2"
      if [ $# -lt 2 ]; then
        input_shapes_not_set
      fi
      shift 2
      ;;
    '--output_arrays')
      export OUTPUT_ARRAYS="$2"
      if [ $# -lt 2 ]; then
        output_arrays_not_set
      fi
      shift 2
      ;;
    '--v2')
      TF_INTERFACE="--v2"
      shift
      ;;
    *)
      echo "Unknown parameter: ${CUR}"
      shift
      ;;
  esac
done

if [ -z ${INPUT_PATH} ] || [ ! -e ${INPUT_PATH} ]; then
  echo "Error: input model not found"
  echo ""
  usage
  exit 2
fi

if [ -z ${INPUT_ARRAYS} ]; then
  input_arrays_not_set
fi

# INPUT_SHAPES is optional

if [ -z ${OUTPUT_PATH} ]; then
  output_not_set
fi

if [ -z ${OUTPUT_ARRAYS} ]; then
  output_arrays_not_set
fi

FILE_BASE=$(basename ${OUTPUT_PATH})
MODEL_NAME="${FILE_BASE%.*}"

TMPDIR=$(mktemp -d)
trap "{ rm -rf $TMPDIR; }" EXIT

# activate python virtual environment
VIRTUALENV_LINUX="${DRIVER_PATH}/venv/bin/activate"
VIRTUALENV_WINDOWS="${DRIVER_PATH}/venv/Scripts/activate"

if [ -e ${VIRTUALENV_LINUX} ]; then
  source ${VIRTUALENV_LINUX}
elif [ -e ${VIRTUALENV_WINDOWS} ]; then
  source ${VIRTUALENV_WINDOWS}
fi

# remove previous log
rm -rf "${OUTPUT_PATH}.log"

show_err_onexit()
{
  cat "${OUTPUT_PATH}.log"
}

trap show_err_onexit ERR

# Generate BCQ information metadata
# If model has no BCQ information or invalid information, pb file is not changed.
"${ROOT}/bin/generate_bcq_metadata" \
--input_path "${GRAPHDEF_FILE}" \
--output_path "${TMPDIR}/${MODEL_NAME}_withmeta.pb" \
--output_arrays "${OUTPUT}"

# Generate BCQ information nodes as output_arrays
# If model has no BCQ information, output_arrays would be empty.
"${ROOT}/bin/generate_bcq_output_arrays" \
--input_path "${TMPDIR}/${MODEL_NAME}_withmeta.pb" \
--output_path_metadata "${TMPDIR}/${MODEL_NAME}_metadata_arrays.txt" \
--output_path_arrays "${TMPDIR}/${MODEL_NAME}_output_arrays.txt"

# generate tflite file
TF2TFLITE_CONVERT_SCRIPT="python ${ROOT}/bin/tf2tfliteV2.py ${TF_INTERFACE} "
TF2TFLITE_CONVERT_SCRIPT+="--input_path ${TMPDIR}/${MODEL_NAME}_withmeta.pb "
CONVERT_SCRIPT+="--input_arrays ${INPUT} "
CONVERT_SCRIPT+="--output_path ${TMPDIR}/${MODEL_NAME}.tflite "
CONVERT_SCRIPT+="--output_arrays "
CONVERT_SCRIPT+="$(cat ${TMPDIR}/${MODEL_NAME}_metadata_arrays.txt)"
CONVERT_SCRIPT+="${OUTPUT}"
CONVERT_SCRIPT+="$(cat ${TMPDIR}/${MODEL_NAME}_output_arrays.txt) "
if [ ! -z ${INPUT_SHAPES} ]; then
  CONVERT_SCRIPT+="--input_shapes ${INPUT_SHAPES} "
fi

echo ${CONVERT_SCRIPT} > "${OUTPUT_PATH}.log"
$CONVERT_SCRIPT >> "${OUTPUT_PATH}.log" 2>&1

# convert .tflite to .circle
echo " " >> "${OUTPUT_PATH}.log"
echo "${DRIVER_PATH}/tflite2circle" "${TMPDIR}/${MODEL_NAME}.tflite" \
"${OUTPUT_PATH}" >> "${OUTPUT_PATH}.log"
echo " " >> "${OUTPUT_PATH}.log"

"${DRIVER_PATH}/tflite2circle" "${TMPDIR}/${MODEL_NAME}.tflite" \
"${OUTPUT_PATH}" >> "${OUTPUT_PATH}.log" 2>&1
