#!/bin/bash

# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage()
{
  echo "Package circle to nnpkg"
  echo "Usage: one-pack"
  echo "    -v, --version Show version information and exit"
  echo "    -i <path/to/circle>"
  echo "    -o <path/to/nnpackage/folder>"
  exit 255
}

version()
{
  $DRIVER_PATH/one-version one-pack
  exit 255
}

input_not_set()
{
  echo "Error: input path not set"
  echo ""
  usage
}

output_not_set()
{
  echo "Error: output path not set"
  echo ""
  usage
}

# Parse command-line arguments
#
while [ "$#" -ne 0 ]; do
  CUR="$1"

  case $CUR in
    '--help')
      usage
      ;;
    '-v')
      version
      ;;
    '--version')
      version
      ;;
    '-i')
      export INPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        input_not_set
      fi
      shift 2
      ;;
    '-o')
      export OUTPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        output_not_set
      fi
      shift 2
      ;;
    *)
      echo "Unknown parameter: ${CUR}"
      shift
      ;;
  esac
done

if [ -z ${INPUT_PATH} ] || [ ! -e ${INPUT_PATH} ]; then
  echo "Error: input model not found"
  echo ""
  usage
fi

if [ -z ${OUTPUT_PATH} ]; then
  output_not_set
fi

INPUT_FILE=$(basename "${INPUT_PATH}")
LOG_FILE="${INPUT_FILE%.*}.pack.log"

# remove previous log
rm -rf "${LOG_FILE}"

show_err_onexit()
{
  cat "${LOG_FILE}"
}

trap show_err_onexit ERR

# Package circle model file to nnpkg
echo "${DRIVER_PATH}/model2nnpkg.sh" -o "${OUTPUT_PATH}" "${INPUT_PATH}" > "${LOG_FILE}"

"${DRIVER_PATH}/model2nnpkg.sh" -o "${OUTPUT_PATH}" "${INPUT_PATH}" >> "${LOG_FILE}" 2>&1
