#!/bin/bash

# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage()
{
  echo "Quantize circle model."
  echo "Usage: one-quantize"
  echo "    --version         Show version information and exit"
  echo "    --input_dtype     Input data type (supported: float32, default=float32)"
  echo "    --quantized_dtype Output quantized data type (supported: uint8, int16, default=uint8)"
  echo "    --granularity     Quantize granularity (supported: layer, channel, default=layer)"
  echo "    --min_percentile  Minimum percentile (0.0~100.0, default=1.0)"
  echo "    --max_percentile  Maximum percentile (0.0~100.0, default=99.0)"
  echo "    --mode            Record mode (supported: percentile/moving_average, default=percentile)"
  echo "    --input_path <path/to/input/circle>"
  echo "    --input_data <path/to/input/data>"
  echo "    --output_path <path/to/output/circle>"
  exit 255
}

version()
{
  $DRIVER_PATH/one-version one-quantize
  exit 255
}

input_not_set()
{
  echo "Error: input_path not set"
  echo ""
  usage
}

output_not_set()
{
  echo "Error: output_path not set"
  echo ""
  usage
}

input_data_not_set()
{
  echo "Error: input_data not set"
  echo ""
  usage
}

input_dtype_not_set()
{
  echo "Error: input_dtype not set"
  echo ""
  usage
}

quantized_dtype_not_set()
{
  echo "Error: quantized_dtype not set"
  echo ""
  usage
}

granularity_not_set()
{
  echo "Error: granularity not set"
  echo ""
  usage
}

min_percentile_not_set()
{
  echo "Error: min_percentile not set"
  echo ""
  usage
}

max_percentile_not_set()
{
  echo "Error: max_percentile not set"
  echo ""
  usage
}

mode_not_set()
{
  echo "Error: mode not set"
  echo ""
  usage
}

INPUT_DTYPE=float32
QUANTIZED_DTYPE=uint8
GRANULARITY=layer
MIN_PERCENTILE=1
MAX_PERCENTILE=99
MODE=percentile

# Parse command-line arguments
#
while [ "$#" -ne 0 ]; do
  CUR="$1"

  case $CUR in
    '--help')
      usage
      ;;
    '--version')
      version
      ;;

    '--input_dtype')
      INPUT_DTYPE="$2"
      if [ $# -lt 2 ]; then
        input_dtype_not_set
      fi
      shift 2
      ;;
    '--quantized_dtype')
      QUANTIZED_DTYPE="$2"
      if [ $# -lt 2 ]; then
        quantized_dtype_not_set
      fi
      shift 2
      ;;
    '--granularity')
      GRANULARITY="$2"
      if [ $# -lt 2 ]; then
        granularity_not_set
      fi
      shift 2
      ;;
    '--min_percentile')
      MIN_PERCENTILE="$2"
      if [ $# -lt 2 ]; then
        min_percentile_not_set
      fi
      shift 2
      ;;
    '--max_percentile')
      MAX_PERCENTILE="$2"
      if [ $# -lt 2 ]; then
        max_percentile_not_set
      fi
      shift 2
      ;;
    '--mode')
      MODE="$2"
      if [ $# -lt 2 ]; then
        mode_not_set
      fi
      shift 2
      ;;

    '--input_path')
      INPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        input_not_set
      fi
      shift 2
      ;;
    '--input_data')
      INPUT_DATA="$2"
      if [ $# -lt 2 ]; then
        input_data_not_set
      fi
      shift 2
      ;;
    '--output_path')
      OUTPUT_PATH="$2"
      if [ $# -lt 2 ]; then
        output_not_set
      fi
      shift 2
      ;;

    *)
      echo "Unknown parameter: ${CUR}"
      shift
      ;;
  esac
done

if [ -z ${INPUT_PATH} ] || [ ! -e ${INPUT_PATH} ]; then
  echo "Error: input model not found"
  echo ""
  usage
fi
if [ -z ${INPUT_DATA} ] || [ ! -e ${INPUT_DATA} ]; then
  echo "Error: input data not found"
  echo ""
  usage
fi
if [ -z ${OUTPUT_PATH} ]; then
  output_not_set
fi

FILE_BASE=$(basename ${OUTPUT_PATH})
MODEL_NAME="${FILE_BASE%.*}"

TMPDIR=$(mktemp -d)
trap "{ rm -rf $TMPDIR; }" EXIT

# remove previous log
rm -rf "${OUTPUT_PATH}.log"

show_err_onexit()
{
  cat "${OUTPUT_PATH}.log"
}

trap show_err_onexit ERR

# quantize circle
echo "${DRIVER_PATH}/circle-quantizer" \
--quantize_dequantize_weights ${INPUT_DTYPE} ${QUANTIZED_DTYPE} ${GRANULARITY} \
"${INPUT_PATH}" "${TMPDIR}/${MODEL_NAME}.1.circle" > "${OUTPUT_PATH}.log"
echo " " >> "${OUTPUT_PATH}.log"

"${DRIVER_PATH}/circle-quantizer" \
--quantize_dequantize_weights ${INPUT_DTYPE} ${QUANTIZED_DTYPE} ${GRANULARITY} \
"${INPUT_PATH}" "${TMPDIR}/${MODEL_NAME}.1.circle" >> "${OUTPUT_PATH}.log" 2>&1

echo " " >> "${OUTPUT_PATH}.log"
echo "${DRIVER_PATH}/record-minmax" \
--input_model "${TMPDIR}/${MODEL_NAME}.1.circle" \
--input_data "${INPUT_DATA}" \
--min_percentile ${MIN_PERCENTILE} --max_percentile ${MAX_PERCENTILE} \
--mode "${MODE}" \
--output_model "${TMPDIR}/${MODEL_NAME}.2.circle" >> "${OUTPUT_PATH}.log" 2>&1
echo " " >> "${OUTPUT_PATH}.log"

"${DRIVER_PATH}/record-minmax" \
--input_model "${TMPDIR}/${MODEL_NAME}.1.circle" \
--input_data "${INPUT_DATA}" \
--min_percentile ${MIN_PERCENTILE} --max_percentile ${MAX_PERCENTILE} \
--mode "${MODE}" \
--output_model "${TMPDIR}/${MODEL_NAME}.2.circle" >> "${OUTPUT_PATH}.log" 2>&1

echo " " >> "${OUTPUT_PATH}.log"
echo "${DRIVER_PATH}/circle-quantizer" \
--quantize_with_minmax ${INPUT_DTYPE} ${QUANTIZED_DTYPE} ${GRANULARITY} \
"${TMPDIR}/${MODEL_NAME}.2.circle" "${OUTPUT_PATH}" >> "${OUTPUT_PATH}.log" 2>&1
echo " " >> "${OUTPUT_PATH}.log"

"${DRIVER_PATH}/circle-quantizer" \
--quantize_with_minmax ${INPUT_DTYPE} ${QUANTIZED_DTYPE} ${GRANULARITY} \
"${TMPDIR}/${MODEL_NAME}.2.circle" "${OUTPUT_PATH}" >> "${OUTPUT_PATH}.log" 2>&1
