#!/bin/bash

# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
# Boradly speaking, the `postinst` is called after a package is unpacked.

set -e

# This script is invoked as root except environmental variables,
# which causes invalid permission problem.
# e.g. When `pip` installs user packages, it proceeds based on $HOME.
# To proper installation, $HOME should be root.
su - $(whoami) -w ONE_PREPVENV_TORCH_SOURCE -c '/usr/share/one/bin/one-prepare-venv' # $(whoami) = root
