#!/bin/bash

set -e

case "$1" in
  remove|purge)
    rm -rf /usr/share/one/
  ;;
  upgrade)
    # DO NOTHING
  ;;
  failed-upgrade|abort-install|abort-upgrade)
    # DO NOTHING
  ;;
  *)
    # DO NOTHING
  ;;
esac
