# Network with Squeeze that have multiple negative squeeze dimensions
node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value { type: DT_FLOAT }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim { size: 2 }
        dim { size: 1 }
        dim { size: 3 }
        dim { size: 1 }
      }
    }
  }
}
node {
  name: "Squeeze"
  op: "Squeeze"
  input: "Placeholder"
  attr {
    key: "T"
    value { type: DT_FLOAT }
  }
  attr {
    key: "squeeze_dims"
    value {
      list { i: -1 i: -3 }
    }
  }
}
