macro(set_sources_mbed)
    set(SOURCES
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/Include/cmsis_os2.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/Include/os_tick.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config/RTX_Config.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config/RTX_Config.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include/rtx_def.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include/rtx_evr.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include/rtx_os.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1/cmsis_os.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Library/cmsis_os1.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/TOOLCHAIN_GCC/TARGET_RTOS_M4_M7/irq_cm4f.S
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_core_c.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_core_ca.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_core_cm.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_delay.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evflags.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_evr.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_kernel.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_lib.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_lib.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_memory.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mempool.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_msgqueue.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_mutex.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_semaphore.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_system.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_thread.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/rtx_timer.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_systick.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/RTOS2/Source/os_tick_ptim.c
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cachel1_armv7.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_armcc.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_armclang.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_armclang_ltm.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_compiler.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_gcc.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_iccarm.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/cmsis_version.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_armv81mml.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_armv8mbl.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_armv8mml.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm0.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm0plus.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm1.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm23.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm3.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm33.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm35p.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm4.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm55.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_cm7.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_sc000.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/core_sc300.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/mpu_armv7.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/mpu_armv8.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/pmu_armv8.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/tz_context.h
            ${ARGV0}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Source/mbed_tz_context.c
            ${ARGV0}/cmsis/device/RTE/include/RTE_Components.h
            ${ARGV0}/cmsis/device/mbed_cmsis_conf.h
            ${ARGV0}/cmsis/device/rtos/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.c
            ${ARGV0}/cmsis/device/rtos/include/mbed_boot.h
            ${ARGV0}/cmsis/device/rtos/include/mbed_rtx_conf.h
            ${ARGV0}/cmsis/device/rtos/include/mbed_rtx_storage.h
            ${ARGV0}/cmsis/device/rtos/source/mbed_boot.c
            ${ARGV0}/cmsis/device/rtos/source/mbed_rtos_rtx.c
            ${ARGV0}/cmsis/device/rtos/source/mbed_rtx_handlers.c
            ${ARGV0}/cmsis/device/rtos/source/mbed_rtx_idle.cpp
            ${ARGV0}/drivers/device_key/include/device_key/DeviceKey.h
            ${ARGV0}/drivers/device_key/source/DeviceKey.cpp
            ${ARGV0}/drivers/include/drivers/AnalogIn.h
            ${ARGV0}/drivers/include/drivers/AnalogOut.h
            ${ARGV0}/drivers/include/drivers/BufferedSerial.h
            ${ARGV0}/drivers/include/drivers/BusIn.h
            ${ARGV0}/drivers/include/drivers/BusInOut.h
            ${ARGV0}/drivers/include/drivers/BusOut.h
            ${ARGV0}/drivers/include/drivers/CAN.h
            ${ARGV0}/drivers/include/drivers/DigitalIn.h
            ${ARGV0}/drivers/include/drivers/DigitalInOut.h
            ${ARGV0}/drivers/include/drivers/DigitalOut.h
            ${ARGV0}/drivers/include/drivers/FlashIAP.h
            ${ARGV0}/drivers/include/drivers/HighResClock.h
            ${ARGV0}/drivers/include/drivers/I2C.h
            ${ARGV0}/drivers/include/drivers/I2CSlave.h
            ${ARGV0}/drivers/include/drivers/InterruptIn.h
            ${ARGV0}/drivers/include/drivers/LowPowerClock.h
            ${ARGV0}/drivers/include/drivers/LowPowerTicker.h
            ${ARGV0}/drivers/include/drivers/LowPowerTimeout.h
            ${ARGV0}/drivers/include/drivers/LowPowerTimer.h
            ${ARGV0}/drivers/include/drivers/MbedCRC.h
            ${ARGV0}/drivers/include/drivers/OSPI.h
            ${ARGV0}/drivers/include/drivers/PortIn.h
            ${ARGV0}/drivers/include/drivers/PortInOut.h
            ${ARGV0}/drivers/include/drivers/PortOut.h
            ${ARGV0}/drivers/include/drivers/PwmOut.h
            ${ARGV0}/drivers/include/drivers/QSPI.h
            ${ARGV0}/drivers/include/drivers/RawCAN.h
            ${ARGV0}/drivers/include/drivers/RealTimeClock.h
            ${ARGV0}/drivers/include/drivers/ResetReason.h
            ${ARGV0}/drivers/include/drivers/SPI.h
            ${ARGV0}/drivers/include/drivers/SPISlave.h
            ${ARGV0}/drivers/include/drivers/SerialBase.h
            ${ARGV0}/drivers/include/drivers/SerialWireOutput.h
            ${ARGV0}/drivers/include/drivers/Ticker.h
            ${ARGV0}/drivers/include/drivers/TickerDataClock.h
            ${ARGV0}/drivers/include/drivers/Timeout.h
            ${ARGV0}/drivers/include/drivers/Timer.h
            ${ARGV0}/drivers/include/drivers/TimerEvent.h
            ${ARGV0}/drivers/include/drivers/UnbufferedSerial.h
            ${ARGV0}/drivers/include/drivers/Watchdog.h
            ${ARGV0}/drivers/include/drivers/interfaces/InterfaceCAN.h
            ${ARGV0}/drivers/include/drivers/interfaces/InterfaceDigitalIn.h
            ${ARGV0}/drivers/include/drivers/interfaces/InterfaceDigitalInOut.h
            ${ARGV0}/drivers/include/drivers/interfaces/InterfaceDigitalOut.h
            ${ARGV0}/drivers/source/AnalogIn.cpp
            ${ARGV0}/drivers/source/AnalogOut.cpp
            ${ARGV0}/drivers/source/BufferedSerial.cpp
            ${ARGV0}/drivers/source/BusIn.cpp
            ${ARGV0}/drivers/source/BusInOut.cpp
            ${ARGV0}/drivers/source/BusOut.cpp
            ${ARGV0}/drivers/source/CAN.cpp
            ${ARGV0}/drivers/source/DigitalIn.cpp
            ${ARGV0}/drivers/source/DigitalInOut.cpp
            ${ARGV0}/drivers/source/DigitalOut.cpp
            ${ARGV0}/drivers/source/FlashIAP.cpp
            ${ARGV0}/drivers/source/I2C.cpp
            ${ARGV0}/drivers/source/I2CSlave.cpp
            ${ARGV0}/drivers/source/InterruptIn.cpp
            ${ARGV0}/drivers/source/MbedCRC.cpp
            ${ARGV0}/drivers/source/OSPI.cpp
            ${ARGV0}/drivers/source/PortIn.cpp
            ${ARGV0}/drivers/source/PortInOut.cpp
            ${ARGV0}/drivers/source/PortOut.cpp
            ${ARGV0}/drivers/source/PwmOut.cpp
            ${ARGV0}/drivers/source/QSPI.cpp
            ${ARGV0}/drivers/source/ResetReason.cpp
            ${ARGV0}/drivers/source/SPI.cpp
            ${ARGV0}/drivers/source/SPISlave.cpp
            ${ARGV0}/drivers/source/SerialBase.cpp
            ${ARGV0}/drivers/source/SerialWireOutput.cpp
            ${ARGV0}/drivers/source/Ticker.cpp
            ${ARGV0}/drivers/source/Timeout.cpp
            ${ARGV0}/drivers/source/Timer.cpp
            ${ARGV0}/drivers/source/TimerEvent.cpp
            ${ARGV0}/drivers/source/UnbufferedSerial.cpp
            ${ARGV0}/drivers/source/Watchdog.cpp
            ${ARGV0}/drivers/usb/include/usb/USBAudio.h
            ${ARGV0}/drivers/usb/include/usb/USBCDC.h
            ${ARGV0}/drivers/usb/include/usb/USBCDC_ECM.h
            ${ARGV0}/drivers/usb/include/usb/USBHID.h
            ${ARGV0}/drivers/usb/include/usb/USBKeyboard.h
            ${ARGV0}/drivers/usb/include/usb/USBMIDI.h
            ${ARGV0}/drivers/usb/include/usb/USBMSD.h
            ${ARGV0}/drivers/usb/include/usb/USBMouse.h
            ${ARGV0}/drivers/usb/include/usb/USBMouseKeyboard.h
            ${ARGV0}/drivers/usb/include/usb/USBSerial.h
            ${ARGV0}/drivers/usb/include/usb/internal/AsyncOp.h
            ${ARGV0}/drivers/usb/include/usb/internal/ByteBuffer.h
            ${ARGV0}/drivers/usb/include/usb/internal/EndpointResolver.h
            ${ARGV0}/drivers/usb/include/usb/internal/LinkEntry.h
            ${ARGV0}/drivers/usb/include/usb/internal/LinkedList.h
            ${ARGV0}/drivers/usb/include/usb/internal/LinkedListBase.h
            ${ARGV0}/drivers/usb/include/usb/internal/MIDIMessage.h
            ${ARGV0}/drivers/usb/include/usb/internal/OperationList.h
            ${ARGV0}/drivers/usb/include/usb/internal/OperationListBase.h
            ${ARGV0}/drivers/usb/include/usb/internal/PolledQueue.h
            ${ARGV0}/drivers/usb/include/usb/internal/Task.h
            ${ARGV0}/drivers/usb/include/usb/internal/TaskBase.h
            ${ARGV0}/drivers/usb/include/usb/internal/TaskQueue.h
            ${ARGV0}/drivers/usb/include/usb/internal/USBAudio_Types.h
            ${ARGV0}/drivers/usb/include/usb/internal/USBDescriptor.h
            ${ARGV0}/drivers/usb/include/usb/internal/USBDevice.h
            ${ARGV0}/drivers/usb/include/usb/internal/USBDevice_Types.h
            ${ARGV0}/drivers/usb/include/usb/internal/USBHID_Types.h
            ${ARGV0}/drivers/usb/source/AsyncOp.cpp
            ${ARGV0}/drivers/usb/source/ByteBuffer.cpp
            ${ARGV0}/drivers/usb/source/EndpointResolver.cpp
            ${ARGV0}/drivers/usb/source/LinkedListBase.cpp
            ${ARGV0}/drivers/usb/source/OperationListBase.cpp
            ${ARGV0}/drivers/usb/source/PolledQueue.cpp
            ${ARGV0}/drivers/usb/source/TaskBase.cpp
            ${ARGV0}/drivers/usb/source/USBAudio.cpp
            ${ARGV0}/drivers/usb/source/USBCDC.cpp
            ${ARGV0}/drivers/usb/source/USBCDC_ECM.cpp
            ${ARGV0}/drivers/usb/source/USBDevice.cpp
            ${ARGV0}/drivers/usb/source/USBHID.cpp
            ${ARGV0}/drivers/usb/source/USBKeyboard.cpp
            ${ARGV0}/drivers/usb/source/USBMIDI.cpp
            ${ARGV0}/drivers/usb/source/USBMSD.cpp
            ${ARGV0}/drivers/usb/source/USBMouse.cpp
            ${ARGV0}/drivers/usb/source/USBMouseKeyboard.cpp
            ${ARGV0}/drivers/usb/source/USBSerial.cpp
            ${ARGV0}/events/include/events/Event.h
            ${ARGV0}/events/include/events/EventQueue.h
            ${ARGV0}/events/include/events/UserAllocatedEvent.h
            ${ARGV0}/events/include/events/equeue.h
            ${ARGV0}/events/include/events/internal/equeue_platform.h
            ${ARGV0}/events/include/events/mbed_events.h
            ${ARGV0}/events/include/events/mbed_shared_queues.h
            ${ARGV0}/events/source/EventQueue.cpp
            ${ARGV0}/events/source/equeue.c
            ${ARGV0}/events/source/equeue_mbed.cpp
            ${ARGV0}/events/source/equeue_posix.c
            ${ARGV0}/events/source/mbed_shared_queues.cpp
            ${ARGV0}/hal/include/hal/LowPowerTickerWrapper.h
            ${ARGV0}/hal/include/hal/PinNameAliases.h
            ${ARGV0}/hal/include/hal/analogin_api.h
            ${ARGV0}/hal/include/hal/analogout_api.h
            ${ARGV0}/hal/include/hal/buffer.h
            ${ARGV0}/hal/include/hal/can_api.h
            ${ARGV0}/hal/include/hal/can_helper.h
            ${ARGV0}/hal/include/hal/crc_api.h
            ${ARGV0}/hal/include/hal/critical_section_api.h
            ${ARGV0}/hal/include/hal/dma_api.h
            ${ARGV0}/hal/include/hal/flash_api.h
            ${ARGV0}/hal/include/hal/gpio_api.h
            ${ARGV0}/hal/include/hal/gpio_irq_api.h
            ${ARGV0}/hal/include/hal/i2c_api.h
            ${ARGV0}/hal/include/hal/itm_api.h
            ${ARGV0}/hal/include/hal/lp_ticker_api.h
            ${ARGV0}/hal/include/hal/mbed_lp_ticker_wrapper.h
            ${ARGV0}/hal/include/hal/mpu_api.h
            ${ARGV0}/hal/include/hal/ospi_api.h
            ${ARGV0}/hal/include/hal/pinmap.h
            ${ARGV0}/hal/include/hal/port_api.h
            ${ARGV0}/hal/include/hal/pwmout_api.h
            ${ARGV0}/hal/include/hal/qspi_api.h
            ${ARGV0}/hal/include/hal/reset_reason_api.h
            ${ARGV0}/hal/include/hal/rtc_api.h
            ${ARGV0}/hal/include/hal/serial_api.h
            ${ARGV0}/hal/include/hal/sleep_api.h
            ${ARGV0}/hal/include/hal/spi_api.h
            ${ARGV0}/hal/include/hal/static_pinmap.h
            ${ARGV0}/hal/include/hal/ticker_api.h
            ${ARGV0}/hal/include/hal/trng_api.h
            ${ARGV0}/hal/include/hal/us_ticker_api.h
            ${ARGV0}/hal/include/hal/watchdog_api.h
            ${ARGV0}/hal/source/LowPowerTickerWrapper.cpp
            ${ARGV0}/hal/source/mbed_compat.c
            ${ARGV0}/hal/source/mbed_critical_section_api.c
            ${ARGV0}/hal/source/mbed_flash_api.c
            ${ARGV0}/hal/source/mbed_gpio.c
            ${ARGV0}/hal/source/mbed_gpio_irq.c
            ${ARGV0}/hal/source/mbed_itm_api.c
            ${ARGV0}/hal/source/mbed_lp_ticker_api.c
            ${ARGV0}/hal/source/mbed_lp_ticker_wrapper.cpp
            ${ARGV0}/hal/source/mbed_pinmap_common.c
            ${ARGV0}/hal/source/mbed_pinmap_default.cpp
            ${ARGV0}/hal/source/mbed_ticker_api.c
            ${ARGV0}/hal/source/mbed_us_ticker_api.c
            ${ARGV0}/hal/source/mpu/mbed_mpu_v7m.c
            ${ARGV0}/hal/source/mpu/mbed_mpu_v8m.c
            ${ARGV0}/hal/source/static_pinmap.cpp
            ${ARGV0}/hal/usb/include/usb/USBPhy.h
            ${ARGV0}/hal/usb/include/usb/USBPhyEvents.h
            ${ARGV0}/hal/usb/include/usb/USBPhyTypes.h
            ${ARGV0}/hal/usb/include/usb/usb_phy_api.h
            ${ARGV0}/hal/usb/source/mbed_usb_phy.cpp
            ${ARGV0}/mbed.h
            ${ARGV0}/platform/cxxsupport/mstd_algorithm
            ${ARGV0}/platform/cxxsupport/mstd_atomic
            ${ARGV0}/platform/cxxsupport/mstd_cstddef
            ${ARGV0}/platform/cxxsupport/mstd_functional
            ${ARGV0}/platform/cxxsupport/mstd_iterator
            ${ARGV0}/platform/cxxsupport/mstd_memory
            ${ARGV0}/platform/cxxsupport/mstd_mutex
            ${ARGV0}/platform/cxxsupport/mstd_mutex.cpp
            ${ARGV0}/platform/cxxsupport/mstd_new
            ${ARGV0}/platform/cxxsupport/mstd_span
            ${ARGV0}/platform/cxxsupport/mstd_tuple
            ${ARGV0}/platform/cxxsupport/mstd_type_traits
            ${ARGV0}/platform/cxxsupport/mstd_utility
            ${ARGV0}/platform/include/platform/ATCmdParser.h
            ${ARGV0}/platform/include/platform/CThunk.h
            ${ARGV0}/platform/include/platform/Callback.h
            ${ARGV0}/platform/include/platform/CircularBuffer.h
            ${ARGV0}/platform/include/platform/CriticalSectionLock.h
            ${ARGV0}/platform/include/platform/DeepSleepLock.h
            ${ARGV0}/platform/include/platform/DirHandle.h
            ${ARGV0}/platform/include/platform/FileBase.h
            ${ARGV0}/platform/include/platform/FileHandle.h
            ${ARGV0}/platform/include/platform/FileLike.h
            ${ARGV0}/platform/include/platform/FilePath.h
            ${ARGV0}/platform/include/platform/FileSystemHandle.h
            ${ARGV0}/platform/include/platform/FileSystemLike.h
            ${ARGV0}/platform/include/platform/LocalFileSystem.h
            ${ARGV0}/platform/include/platform/NonCopyable.h
            ${ARGV0}/platform/include/platform/PlatformMutex.h
            ${ARGV0}/platform/include/platform/ScopedLock.h
            ${ARGV0}/platform/include/platform/ScopedRamExecutionLock.h
            ${ARGV0}/platform/include/platform/ScopedRomWriteLock.h
            ${ARGV0}/platform/include/platform/SharedPtr.h
            ${ARGV0}/platform/include/platform/SingletonPtr.h
            ${ARGV0}/platform/include/platform/Span.h
            ${ARGV0}/platform/include/platform/Stream.h
            ${ARGV0}/platform/include/platform/Transaction.h
            ${ARGV0}/platform/include/platform/internal/CThunkBase.h
            ${ARGV0}/platform/include/platform/internal/SysTimer.h
            ${ARGV0}/platform/include/platform/internal/mbed_atomic_impl.h
            ${ARGV0}/platform/include/platform/internal/mbed_error_hist.h
            ${ARGV0}/platform/include/platform/internal/mbed_fault_handler.h
            ${ARGV0}/platform/include/platform/internal/mbed_os_timer.h
            ${ARGV0}/platform/include/platform/mbed_application.h
            ${ARGV0}/platform/include/platform/mbed_assert.h
            ${ARGV0}/platform/include/platform/mbed_atomic.h
            ${ARGV0}/platform/include/platform/mbed_chrono.h
            ${ARGV0}/platform/include/platform/mbed_critical.h
            ${ARGV0}/platform/include/platform/mbed_debug.h
            ${ARGV0}/platform/include/platform/mbed_enum_flags.h
            ${ARGV0}/platform/include/platform/mbed_error.h
            ${ARGV0}/platform/include/platform/mbed_interface.h
            ${ARGV0}/platform/include/platform/mbed_mem_trace.h
            ${ARGV0}/platform/include/platform/mbed_mktime.h
            ${ARGV0}/platform/include/platform/mbed_mpu_mgmt.h
            ${ARGV0}/platform/include/platform/mbed_poll.h
            ${ARGV0}/platform/include/platform/mbed_power_mgmt.h
            ${ARGV0}/platform/include/platform/mbed_preprocessor.h
            ${ARGV0}/platform/include/platform/mbed_retarget.h
            ${ARGV0}/platform/include/platform/mbed_rtc_time.h
            ${ARGV0}/platform/include/platform/mbed_semihost_api.h
            ${ARGV0}/platform/include/platform/mbed_stats.h
            ${ARGV0}/platform/include/platform/mbed_thread.h
            ${ARGV0}/platform/include/platform/mbed_toolchain.h
            ${ARGV0}/platform/include/platform/mbed_version.h
            ${ARGV0}/platform/include/platform/mbed_wait_api.h
            ${ARGV0}/platform/include/platform/platform.h
            ${ARGV0}/platform/mbed-trace/include/mbed-trace/mbed_trace.h
            ${ARGV0}/platform/mbed-trace/include/mbed-trace/ns_trace.h
            ${ARGV0}/platform/mbed-trace/source/mbed_trace.c
            ${ARGV0}/platform/randlib/include/mbed-client-randlib/platform/arm_hal_random.h
            ${ARGV0}/platform/randlib/include/mbed-client-randlib/randLIB.h
            ${ARGV0}/platform/randlib/source/randLIB.c
            ${ARGV0}/platform/source/ATCmdParser.cpp
            ${ARGV0}/platform/source/CThunkBase.cpp
            ${ARGV0}/platform/source/CriticalSectionLock.cpp
            ${ARGV0}/platform/source/DeepSleepLock.cpp
            ${ARGV0}/platform/source/FileBase.cpp
            ${ARGV0}/platform/source/FileHandle.cpp
            ${ARGV0}/platform/source/FilePath.cpp
            ${ARGV0}/platform/source/FileSystemHandle.cpp
            ${ARGV0}/platform/source/LocalFileSystem.cpp
            ${ARGV0}/platform/source/Stream.cpp
            ${ARGV0}/platform/source/SysTimer.cpp
            ${ARGV0}/platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
            ${ARGV0}/platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
            ${ARGV0}/platform/source/mbed_alloc_wrappers.cpp
            ${ARGV0}/platform/source/mbed_application.c
            ${ARGV0}/platform/source/mbed_assert.c
            ${ARGV0}/platform/source/mbed_atomic_impl.c
            ${ARGV0}/platform/source/mbed_board.c
            ${ARGV0}/platform/source/mbed_crash_data_offsets.h
            ${ARGV0}/platform/source/mbed_critical.c
            ${ARGV0}/platform/source/mbed_error.c
            ${ARGV0}/platform/source/mbed_error_hist.c
            ${ARGV0}/platform/source/mbed_interface.c
            ${ARGV0}/platform/source/mbed_mem_trace.cpp
            ${ARGV0}/platform/source/mbed_mktime.c
            ${ARGV0}/platform/source/mbed_mpu_mgmt.c
            ${ARGV0}/platform/source/mbed_os_timer.cpp
            ${ARGV0}/platform/source/mbed_poll.cpp
            ${ARGV0}/platform/source/mbed_power_mgmt.c
            ${ARGV0}/platform/source/mbed_retarget.cpp
            ${ARGV0}/platform/source/mbed_rtc_time.cpp
            ${ARGV0}/platform/source/mbed_sdk_boot.c
            ${ARGV0}/platform/source/mbed_semihost_api.c
            ${ARGV0}/platform/source/mbed_stats.c
            ${ARGV0}/platform/source/mbed_thread.cpp
            ${ARGV0}/platform/source/mbed_wait_api_no_rtos.c
            ${ARGV0}/platform/source/minimal-printf/mbed_printf_armlink_overrides.c
            ${ARGV0}/platform/source/minimal-printf/mbed_printf_implementation.c
            ${ARGV0}/platform/source/minimal-printf/mbed_printf_implementation.h
            ${ARGV0}/platform/source/minimal-printf/mbed_printf_wrapper.c
            ${ARGV0}/platform/source/newlib_nano_malloc_workaround.c
            ${ARGV0}/rtos/include/rtos/ConditionVariable.h
            ${ARGV0}/rtos/include/rtos/EventFlags.h
            ${ARGV0}/rtos/include/rtos/Kernel.h
            ${ARGV0}/rtos/include/rtos/Mail.h
            ${ARGV0}/rtos/include/rtos/MemoryPool.h
            ${ARGV0}/rtos/include/rtos/Mutex.h
            ${ARGV0}/rtos/include/rtos/Queue.h
            ${ARGV0}/rtos/include/rtos/Semaphore.h
            ${ARGV0}/rtos/include/rtos/ThisThread.h
            ${ARGV0}/rtos/include/rtos/Thread.h
            ${ARGV0}/rtos/include/rtos/internal/mbed_rtos1_types.h
            ${ARGV0}/rtos/include/rtos/internal/mbed_rtos_storage.h
            ${ARGV0}/rtos/include/rtos/mbed_rtos_types.h
            ${ARGV0}/rtos/include/rtos/rtos.h
            ${ARGV0}/rtos/source/ConditionVariable.cpp
            ${ARGV0}/rtos/source/EventFlags.cpp
            ${ARGV0}/rtos/source/Kernel.cpp
            ${ARGV0}/rtos/source/Mutex.cpp
            ${ARGV0}/rtos/source/Semaphore.cpp
            ${ARGV0}/rtos/source/ThisThread.cpp
            ${ARGV0}/rtos/source/Thread.cpp
            ${ARGV0}/rtos/source/rtos_handlers.h
            ${ARGV0}/rtos/source/rtos_idle.h
            ${ARGV0}/targets/TARGET_STM/PeripheralPins.h
            ${ARGV0}/targets/TARGET_STM/PinNamesTypes.h
            ${ARGV0}/targets/TARGET_STM/PortNames.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f722xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f723xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f730xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f732xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f733xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f745xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f746xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f750xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f756xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f765xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f767xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f769xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f777xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f779xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/stm32f7xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS/system_stm32f7xx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy/stm32_hal_legacy.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy/stm32f7xx_hal_can_legacy.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy/stm32f7xx_hal_can_legacy.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_adc_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_can.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cec.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cec.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cortex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_crc_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_cryp_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dac_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dcmi_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_def.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dfsdm.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dfsdm.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma2d.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma2d.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dma_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_dsi.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_eth.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_eth.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_exti.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_flash_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_gpio_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hash_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hcd.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_hcd.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2c_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2s.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_i2s.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_irda.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_irda.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_irda_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_iwdg.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_iwdg.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_jpeg.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_jpeg.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_lptim.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_lptim.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_ltdc_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mdios.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mdios.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mmc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_mmc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nand.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nand.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nor.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_nor.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pcd_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_pwr_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_qspi.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rcc_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rng.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rng.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_rtc_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sai_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sd.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sd.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sdram.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smartcard_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smbus.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_smbus.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spdifrx.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spdifrx.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_spi_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sram.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_sram.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_tim_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_uart_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_usart.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_usart.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_usart_ex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_wwdg.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_hal_wwdg.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_adc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_adc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_bus.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_cortex.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_crc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_crc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dac.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dac.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma2d.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_dma2d.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_exti.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_exti.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_fmc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_gpio.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_gpio.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_i2c.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_i2c.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_iwdg.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_lptim.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_lptim.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_pwr.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_pwr.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rcc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rcc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rng.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rng.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rtc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_rtc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_sdmmc.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_sdmmc.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_spi.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_spi.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_system.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_tim.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_tim.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usart.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usart.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usb.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_usb.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_utils.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_utils.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/stm32f7xx_ll_wwdg.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/stm32f7xx_hal_conf.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/system_stm32f7xx.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralNames.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TOOLCHAIN_GCC_ARM/startup_stm32f767xx.S
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/cmsis_nvic.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/flash_data.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/analogin_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/analogout_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/can_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/cmsis.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/flash_api.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/i2c_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/i2c_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/objects.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/pin_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/pwmout_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/serial_device.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/spi_api.c
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/spi_device.h
            ${ARGV0}/targets/TARGET_STM/TARGET_STM32F7/us_ticker_data.h
            ${ARGV0}/targets/TARGET_STM/USBPhyHw.h
            ${ARGV0}/targets/TARGET_STM/USBPhy_STM32.cpp
            ${ARGV0}/targets/TARGET_STM/analogin_api.c
            ${ARGV0}/targets/TARGET_STM/analogout_api.c
            ${ARGV0}/targets/TARGET_STM/can_api.c
            ${ARGV0}/targets/TARGET_STM/device.h
            ${ARGV0}/targets/TARGET_STM/gpio_api.c
            ${ARGV0}/targets/TARGET_STM/gpio_irq_api.c
            ${ARGV0}/targets/TARGET_STM/gpio_object.h
            ${ARGV0}/targets/TARGET_STM/hal_tick_overrides.c
            ${ARGV0}/targets/TARGET_STM/i2c_api.c
            ${ARGV0}/targets/TARGET_STM/lp_ticker.c
            ${ARGV0}/targets/TARGET_STM/lp_ticker_defines.h
            ${ARGV0}/targets/TARGET_STM/mbed_crc_api.c
            ${ARGV0}/targets/TARGET_STM/mbed_overrides.c
            ${ARGV0}/targets/TARGET_STM/mbed_rtx.h
            ${ARGV0}/targets/TARGET_STM/nvic_addr.h
            ${ARGV0}/targets/TARGET_STM/ospi_api.c
            ${ARGV0}/targets/TARGET_STM/pinmap.c
            ${ARGV0}/targets/TARGET_STM/port_api.c
            ${ARGV0}/targets/TARGET_STM/pwmout_api.c
            ${ARGV0}/targets/TARGET_STM/qspi_api.c
            ${ARGV0}/targets/TARGET_STM/reset_reason.c
            ${ARGV0}/targets/TARGET_STM/rtc_api.c
            ${ARGV0}/targets/TARGET_STM/rtc_api_hal.h
            ${ARGV0}/targets/TARGET_STM/serial_api.c
            ${ARGV0}/targets/TARGET_STM/serial_api_hal.h
            ${ARGV0}/targets/TARGET_STM/sleep.c
            ${ARGV0}/targets/TARGET_STM/stm32_assert.h
            ${ARGV0}/targets/TARGET_STM/stm_spi_api.c
            ${ARGV0}/targets/TARGET_STM/trng_api.c
            ${ARGV0}/targets/TARGET_STM/us_ticker.c
            ${ARGV0}/targets/TARGET_STM/us_ticker_defines.h
            ${ARGV0}/targets/TARGET_STM/watchdog_api.c
            mbed_config.h
            )
endmacro()

macro(target_include_directories_mbed)
    target_include_directories(${ARGV0} PRIVATE
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver/Legacy
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/STM32F7xx_HAL_Driver
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/CMSIS
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW
            ${ARGV1}/targets/TARGET_STM/TARGET_STM32F7
            ${ARGV1}/targets/TARGET_STM
            ${ARGV1}/storage/kvstore/tdbstore/include/tdbstore
            ${ARGV1}/storage/kvstore/tdbstore/include
            ${ARGV1}/storage/kvstore/tdbstore
            ${ARGV1}/storage/kvstore/securestore/include/securestore
            ${ARGV1}/storage/kvstore/securestore/include
            ${ARGV1}/storage/kvstore/securestore
            ${ARGV1}/storage/kvstore/kvstore_global_api/include/kvstore_global_api
            ${ARGV1}/storage/kvstore/kvstore_global_api/include
            ${ARGV1}/storage/kvstore/kvstore_global_api
            ${ARGV1}/storage/kvstore/kv_config/include/kv_config
            ${ARGV1}/storage/kvstore/kv_config/include
            ${ARGV1}/storage/kvstore/kv_config
            ${ARGV1}/storage/kvstore/include/kvstore
            ${ARGV1}/storage/kvstore/include
            ${ARGV1}/storage/kvstore/filesystemstore/include/filesystemstore
            ${ARGV1}/storage/kvstore/filesystemstore/include
            ${ARGV1}/storage/kvstore/filesystemstore
            ${ARGV1}/storage/kvstore/direct_access_devicekey/include/direct_access_devicekey
            ${ARGV1}/storage/kvstore/direct_access_devicekey/include
            ${ARGV1}/storage/kvstore/direct_access_devicekey
            ${ARGV1}/storage/kvstore
            ${ARGV1}/storage/filesystem/littlefsv2/littlefs
            ${ARGV1}/storage/filesystem/littlefsv2/include/littlefsv2
            ${ARGV1}/storage/filesystem/littlefsv2/include
            ${ARGV1}/storage/filesystem/littlefsv2
            ${ARGV1}/storage/filesystem/littlefs/littlefs
            ${ARGV1}/storage/filesystem/littlefs/include/littlefs
            ${ARGV1}/storage/filesystem/littlefs/include
            ${ARGV1}/storage/filesystem/littlefs
            ${ARGV1}/storage/filesystem/include/filesystem
            ${ARGV1}/storage/filesystem/include
            ${ARGV1}/storage/filesystem/fat/include/fat
            ${ARGV1}/storage/filesystem/fat/include
            ${ARGV1}/storage/filesystem/fat/ChaN
            ${ARGV1}/storage/filesystem/fat
            ${ARGV1}/storage/filesystem
            ${ARGV1}/storage/blockdevice/include/blockdevice/internal
            ${ARGV1}/storage/blockdevice/include/blockdevice
            ${ARGV1}/storage/blockdevice/include
            ${ARGV1}/storage/blockdevice/COMPONENT_FLASHIAP/include/FlashIAP
            ${ARGV1}/storage/blockdevice/COMPONENT_FLASHIAP/include
            ${ARGV1}/storage/blockdevice/COMPONENT_FLASHIAP
            ${ARGV1}/storage/blockdevice
            ${ARGV1}/storage
            ${ARGV1}/rtos/source
            ${ARGV1}/rtos/include/rtos/internal
            ${ARGV1}/rtos/include/rtos
            ${ARGV1}/rtos/include
            ${ARGV1}/rtos
            ${ARGV1}/platform/source/minimal-printf
            ${ARGV1}/platform/source
            ${ARGV1}/platform/randlib/include/mbed-client-randlib/platform
            ${ARGV1}/platform/randlib/include/mbed-client-randlib
            ${ARGV1}/platform/randlib/include
            ${ARGV1}/platform/randlib
            ${ARGV1}/platform/mbed-trace/include/mbed-trace
            ${ARGV1}/platform/mbed-trace/include
            ${ARGV1}/platform/mbed-trace
            ${ARGV1}/platform/include/platform/internal
            ${ARGV1}/platform/include/platform
            ${ARGV1}/platform/include
            ${ARGV1}/platform/cxxsupport
            ${ARGV1}/platform
            ${ARGV1}/hal/usb/include/usb
            ${ARGV1}/hal/usb/include
            ${ARGV1}/hal/usb
            ${ARGV1}/hal/include/hal
            ${ARGV1}/hal/include
            ${ARGV1}/hal
            ${ARGV1}/features/frameworks/utest/utest
            ${ARGV1}/features/frameworks/utest
            ${ARGV1}/features/frameworks/unity/unity
            ${ARGV1}/features/frameworks/unity
            ${ARGV1}/features/frameworks/mbed-client-cli/mbed-client-cli
            ${ARGV1}/features/frameworks/mbed-client-cli
            ${ARGV1}/features/frameworks/greentea-client/greentea-client
            ${ARGV1}/features/frameworks/greentea-client
            ${ARGV1}/features/frameworks
            ${ARGV1}/features
            ${ARGV1}/events/include/events/internal
            ${ARGV1}/events/include/events
            ${ARGV1}/events/include
            ${ARGV1}/events
            ${ARGV1}/drivers/usb/include/usb/internal
            ${ARGV1}/drivers/usb/include/usb
            ${ARGV1}/drivers/usb/include
            ${ARGV1}/drivers/usb
            ${ARGV1}/drivers/include/drivers/interfaces
            ${ARGV1}/drivers/include/drivers
            ${ARGV1}/drivers/include
            ${ARGV1}/drivers/device_key/include/device_key
            ${ARGV1}/drivers/device_key/include
            ${ARGV1}/drivers/device_key
            ${ARGV1}/drivers
            ${ARGV1}/connectivity/nfc/libraries/stack/transceiver
            ${ARGV1}/connectivity/nfc/libraries/stack/tech/type4
            ${ARGV1}/connectivity/nfc/libraries/stack/tech/isodep
            ${ARGV1}/connectivity/nfc/libraries/stack/tech/iso7816
            ${ARGV1}/connectivity/nfc/libraries/stack/tech
            ${ARGV1}/connectivity/nfc/libraries/stack/platform
            ${ARGV1}/connectivity/nfc/libraries/stack/ndef
            ${ARGV1}/connectivity/nfc/libraries/stack
            ${ARGV1}/connectivity/nfc/libraries/acore/acore
            ${ARGV1}/connectivity/nfc/libraries/acore
            ${ARGV1}/connectivity/nfc/libraries
            ${ARGV1}/connectivity/nfc/include/nfc/ndef/common
            ${ARGV1}/connectivity/nfc/include/nfc/ndef
            ${ARGV1}/connectivity/nfc/include/nfc
            ${ARGV1}/connectivity/nfc/include
            ${ARGV1}/connectivity/nfc
            ${ARGV1}/connectivity/netsocket/include/netsocket
            ${ARGV1}/connectivity/netsocket/include
            ${ARGV1}/connectivity/netsocket
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/libNET/src
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/libNET
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/ipv6_stack
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/configs/base
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/configs
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/utils
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/serial
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/dns
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/cpu
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/compiler
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mdns
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/hmac
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fhss
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/etx
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Service_Libs
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/msg_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/protocols
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/kmp
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/eapol
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/TLS
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/PANA
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security/Common
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Security
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/RPL
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/NWK_INTERFACE
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/MPL
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/MLE
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/MAC/virtual_rf
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/MAC
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_client
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_Server
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Core/include
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Core
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/BorderRouter
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ND
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/source
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/nanostack/platform
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack/nanostack
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack-eventloop/source
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop/platform
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack-eventloop
            ${ARGV1}/connectivity/nanostack/sal-stack-nanostack
            ${ARGV1}/connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos
            ${ARGV1}/connectivity/nanostack/mbed-mesh-api/source/include
            ${ARGV1}/connectivity/nanostack/mbed-mesh-api/source
            ${ARGV1}/connectivity/nanostack/mbed-mesh-api/mbed-mesh-api
            ${ARGV1}/connectivity/nanostack/mbed-mesh-api
            ${ARGV1}/connectivity/nanostack/include/nanostack-interface
            ${ARGV1}/connectivity/nanostack/include
            ${ARGV1}/connectivity/nanostack/coap-service/source/include
            ${ARGV1}/connectivity/nanostack/coap-service/source
            ${ARGV1}/connectivity/nanostack/coap-service/coap-service
            ${ARGV1}/connectivity/nanostack/coap-service
            ${ARGV1}/connectivity/nanostack
            ${ARGV1}/connectivity/mbedtls/source
            ${ARGV1}/connectivity/mbedtls/platform/inc
            ${ARGV1}/connectivity/mbedtls/platform
            ${ARGV1}/connectivity/mbedtls/include/mbedtls
            ${ARGV1}/connectivity/mbedtls/include
            ${ARGV1}/connectivity/mbedtls
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/netif
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/lwip/prot
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/lwip/priv
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/lwip
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/compat/posix/sys
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/compat/posix/net
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/compat/posix/arpa
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/compat/posix
            ${ARGV1}/connectivity/lwipstack/lwip/src/include/compat
            ${ARGV1}/connectivity/lwipstack/lwip/src/include
            ${ARGV1}/connectivity/lwipstack/lwip/src
            ${ARGV1}/connectivity/lwipstack/lwip-sys/arch
            ${ARGV1}/connectivity/lwipstack/lwip-sys
            ${ARGV1}/connectivity/lwipstack/lwip
            ${ARGV1}/connectivity/lwipstack/include/lwipstack
            ${ARGV1}/connectivity/lwipstack/include
            ${ARGV1}/connectivity/lwipstack
            ${ARGV1}/connectivity/lorawan/system
            ${ARGV1}/connectivity/lorawan/lorastack/phy
            ${ARGV1}/connectivity/lorawan/lorastack/mac
            ${ARGV1}/connectivity/lorawan/lorastack
            ${ARGV1}/connectivity/lorawan/include/lorawan
            ${ARGV1}/connectivity/lorawan/include
            ${ARGV1}/connectivity/lorawan
            ${ARGV1}/connectivity/libraries/ppp/include/ppp
            ${ARGV1}/connectivity/libraries/ppp/include/polarssl
            ${ARGV1}/connectivity/libraries/ppp/include
            ${ARGV1}/connectivity/libraries/ppp
            ${ARGV1}/connectivity/libraries/nanostack-libservice/mbed-client-libservice/platform
            ${ARGV1}/connectivity/libraries/nanostack-libservice/mbed-client-libservice
            ${ARGV1}/connectivity/libraries/nanostack-libservice
            ${ARGV1}/connectivity/libraries/mbed-coap/source/include
            ${ARGV1}/connectivity/libraries/mbed-coap/source
            ${ARGV1}/connectivity/libraries/mbed-coap/mbed-coap
            ${ARGV1}/connectivity/libraries/mbed-coap
            ${ARGV1}/connectivity/libraries
            ${ARGV1}/connectivity/drivers/wifi/esp8266-driver/ESP8266
            ${ARGV1}/connectivity/drivers/wifi/esp8266-driver
            ${ARGV1}/connectivity/drivers/wifi
            ${ARGV1}/connectivity/drivers/nfc/PN512/source/transceiver
            ${ARGV1}/connectivity/drivers/nfc/PN512/source
            ${ARGV1}/connectivity/drivers/nfc/PN512/include/nfc/controllers
            ${ARGV1}/connectivity/drivers/nfc/PN512/include/nfc
            ${ARGV1}/connectivity/drivers/nfc/PN512/include
            ${ARGV1}/connectivity/drivers/nfc/PN512
            ${ARGV1}/connectivity/drivers/nfc
            ${ARGV1}/connectivity/drivers/mbedtls/TARGET_STM
            ${ARGV1}/connectivity/drivers/emac/TARGET_STM/TARGET_STM32F7
            ${ARGV1}/connectivity/drivers/emac/TARGET_STM
            ${ARGV1}/connectivity/drivers/cellular/UBLOX/PPP
            ${ARGV1}/connectivity/drivers/cellular/UBLOX/N2XX
            ${ARGV1}/connectivity/drivers/cellular/UBLOX/AT
            ${ARGV1}/connectivity/drivers/cellular/UBLOX
            ${ARGV1}/connectivity/drivers/cellular/TELIT/ME910
            ${ARGV1}/connectivity/drivers/cellular/TELIT/ME310
            ${ARGV1}/connectivity/drivers/cellular/TELIT/HE910
            ${ARGV1}/connectivity/drivers/cellular/TELIT
            ${ARGV1}/connectivity/drivers/cellular/RiotMicro/AT
            ${ARGV1}/connectivity/drivers/cellular/RiotMicro
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL/UG96
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL/M26
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL/EC2X
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL/BG96
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL/BC95
            ${ARGV1}/connectivity/drivers/cellular/QUECTEL
            ${ARGV1}/connectivity/drivers/cellular/MultiTech/DragonflyNano/PPP
            ${ARGV1}/connectivity/drivers/cellular/MultiTech/DragonflyNano
            ${ARGV1}/connectivity/drivers/cellular/MultiTech
            ${ARGV1}/connectivity/drivers/cellular/GENERIC/GENERIC_AT3GPP
            ${ARGV1}/connectivity/drivers/cellular/GENERIC
            ${ARGV1}/connectivity/drivers/cellular/GEMALTO/CINTERION
            ${ARGV1}/connectivity/drivers/cellular/GEMALTO
            ${ARGV1}/connectivity/drivers/cellular/Altair/ALT1250/PPP
            ${ARGV1}/connectivity/drivers/cellular/Altair/ALT1250
            ${ARGV1}/connectivity/drivers/cellular/Altair
            ${ARGV1}/connectivity/drivers/cellular
            ${ARGV1}/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source
            ${ARGV1}/connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source
            ${ARGV1}/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF/mcr20a-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF/atmel-rf-driver/source
            ${ARGV1}/connectivity/drivers/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF/atmel-rf-driver
            ${ARGV1}/connectivity/drivers/802.15.4_RF
            ${ARGV1}/connectivity/drivers
            ${ARGV1}/connectivity/cellular/include/cellular/framework/device
            ${ARGV1}/connectivity/cellular/include/cellular/framework/common
            ${ARGV1}/connectivity/cellular/include/cellular/framework/AT
            ${ARGV1}/connectivity/cellular/include/cellular/framework/API
            ${ARGV1}/connectivity/cellular/include/cellular/framework
            ${ARGV1}/connectivity/cellular/include/cellular
            ${ARGV1}/connectivity/cellular/include
            ${ARGV1}/connectivity/cellular
            ${ARGV1}/connectivity
            ${ARGV1}/cmsis/device/rtos/include
            ${ARGV1}/cmsis/device/rtos
            ${ARGV1}/cmsis/device/RTE/include
            ${ARGV1}/cmsis/device/RTE
            ${ARGV1}/cmsis/device
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include1
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Include
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Config
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/RTX
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2/Include
            ${ARGV1}/cmsis/CMSIS_5/CMSIS/RTOS2
            ${ARGV1}/cmsis/CMSIS_5/CMSIS
            ${ARGV1}/cmsis/CMSIS_5
            ${ARGV1}/cmsis
            ${ARGV1}
            )

endmacro()