var searchData=
[
  ['dagchecker_0',['DAGChecker',['../classonert_1_1ir_1_1verifier_1_1_d_a_g_checker.html',1,'onert::ir::verifier']]],
  ['dalgona_1',['Dalgona',['../classdalgona_1_1_dalgona.html',1,'dalgona']]],
  ['data_2',['Data',['../structcoco_1_1_data.html',1,'coco::Data'],['../structonert_1_1ir_1_1_data.html',1,'onert::ir::Data']]],
  ['datachef_3',['DataChef',['../structsouschef_1_1_data_chef.html',1,'souschef']]],
  ['datacheffactory_4',['DataChefFactory',['../structsouschef_1_1_data_chef_factory.html',1,'souschef']]],
  ['dataflowexecutor_5',['DataflowExecutor',['../classonert_1_1exec_1_1_dataflow_executor.html',1,'onert::exec']]],
  ['dataformatswitcher_6',['DataFormatSwitcher',['../classnnc_1_1_data_format_switcher.html',1,'nnc']]],
  ['datagen_7',['DataGen',['../classminmax__embedder__test_1_1_data_gen.html',1,'minmax_embedder_test']]],
  ['datalayoutconversionpass_8',['DataLayoutConversionPass',['../structenco_1_1_data_layout_conversion_pass.html',1,'enco']]],
  ['datalocation_9',['DataLocation',['../struct_data_location.html',1,'']]],
  ['dataptr_10',['DataPtr',['../uniononert_1_1backend_1_1cpu_1_1ops_1_1_data_ptr.html',1,'onert::backend::cpu::ops']]],
  ['dataset_11',['Dataset',['../classsouschef_1_1_dataset.html',1,'souschef']]],
  ['datasetevaluator_12',['DatasetEvaluator',['../classmpqsolver_1_1core_1_1_dataset_evaluator.html',1,'mpqsolver::core']]],
  ['datatypeimpl_13',['DataTypeImpl',['../structloco_1_1_data_type_impl.html',1,'loco::DataTypeImpl&lt; DT &gt;'],['../structluci__interpreter_1_1_data_type_impl.html',1,'luci_interpreter::DataTypeImpl&lt; DT &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3abool_20_3e_14',['DataTypeImpl&lt; DataType::BOOL &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_b_o_o_l_01_4.html',1,'loco::DataTypeImpl&lt; DataType::BOOL &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_b_o_o_l_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::BOOL &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat16_20_3e_15',['DataTypeImpl&lt; DataType::FLOAT16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat32_20_3e_16',['DataTypeImpl&lt; DataType::FLOAT32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat64_20_3e_17',['DataTypeImpl&lt; DataType::FLOAT64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as16_20_3e_18',['DataTypeImpl&lt; DataType::S16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as32_20_3e_19',['DataTypeImpl&lt; DataType::S32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as64_20_3e_20',['DataTypeImpl&lt; DataType::S64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as8_20_3e_21',['DataTypeImpl&lt; DataType::S8 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s8_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S8 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s8_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S8 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3astring_20_3e_22',['DataTypeImpl&lt; DataType::STRING &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s_t_r_i_n_g_01_4.html',1,'loco']]],
  ['datatypeimpl_3c_20datatype_3a_3au16_20_3e_23',['DataTypeImpl&lt; DataType::U16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au32_20_3e_24',['DataTypeImpl&lt; DataType::U32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au64_20_3e_25',['DataTypeImpl&lt; DataType::U64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au8_20_3e_26',['DataTypeImpl&lt; DataType::U8 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u8_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U8 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u8_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U8 &gt;']]],
  ['dbus_27',['DBus',['../classnpud_1_1core_1_1_d_bus.html',1,'npud::core']]],
  ['deadbageliminationpass_28',['DeadBagEliminationPass',['../structenco_1_1_dead_bag_elimination_pass.html',1,'enco']]],
  ['deadcodeelimination_29',['DeadCodeElimination',['../classnnc_1_1_dead_code_elimination.html',1,'nnc']]],
  ['deadnodequeryservice_30',['DeadNodeQueryService',['../structlogo_1_1_dead_node_query_service.html',1,'logo']]],
  ['deadnodequeryserviceimpl_31',['DeadNodeQueryServiceImpl',['../structluci_1_1_dead_node_query_service_impl.html',1,'luci']]],
  ['deadobjecteliminationpass_32',['DeadObjectEliminationPass',['../structenco_1_1_dead_object_elimination_pass.html',1,'enco']]],
  ['decodecommand_33',['DecodeCommand',['../struct_decode_command.html',1,'DecodeCommand'],['../structtfkit_1_1_decode_command.html',1,'tfkit::DecodeCommand']]],
  ['decomposehardswishpass_34',['DecomposeHardSwishPass',['../structluci_1_1_decompose_hard_swish_pass.html',1,'luci']]],
  ['decomposesoftmaxpass_35',['DecomposeSoftmaxPass',['../structluci_1_1_decompose_softmax_pass.html',1,'luci']]],
  ['deconv2dimpl_36',['DeConv2DImpl',['../structmir__interpreter_1_1_de_conv2_d_impl.html',1,'mir_interpreter']]],
  ['deconv2dop_37',['DeConv2DOp',['../classmir_1_1ops_1_1_de_conv2_d_op.html',1,'mir::ops']]],
  ['deconv2dopattributes_38',['Deconv2DOpAttributes',['../structmir_1_1_deconv2_d_op_attributes.html',1,'mir']]],
  ['def_39',['Def',['../classcoco_1_1_def.html',1,'coco']]],
  ['defaultallocator_40',['DefaultAllocator',['../classflatbuffers_1_1_default_allocator.html',1,'flatbuffers']]],
  ['definition_41',['Definition',['../structflatbuffers_1_1_definition.html',1,'flatbuffers']]],
  ['densifychef_42',['DensifyChef',['../class_densify_chef.html',1,'']]],
  ['densifycheffactory_43',['DensifyChefFactory',['../struct_densify_chef_factory.html',1,'']]],
  ['dep_44',['Dep',['../classcoco_1_1_dep.html',1,'coco']]],
  ['depthtospace_45',['DepthToSpace',['../classluci__interpreter_1_1kernels_1_1_depth_to_space.html',1,'luci_interpreter::kernels::DepthToSpace'],['../classonert_1_1ir_1_1operation_1_1_depth_to_space.html',1,'onert::ir::operation::DepthToSpace']]],
  ['depthtospacechef_46',['DepthToSpaceChef',['../class_depth_to_space_chef.html',1,'']]],
  ['depthtospacecheffactory_47',['DepthToSpaceChefFactory',['../struct_depth_to_space_chef_factory.html',1,'']]],
  ['depthtospacelayer_48',['DepthToSpaceLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_depth_to_space_layer.html',1,'onert::backend::cpu::ops']]],
  ['depthtospaceparams_49',['DepthToSpaceParams',['../structluci__interpreter_1_1_depth_to_space_params.html',1,'luci_interpreter']]],
  ['depthtospaceprinter_50',['DepthToSpacePrinter',['../classcircledump_1_1_depth_to_space_printer.html',1,'circledump::DepthToSpacePrinter'],['../classtfldump_1_1_depth_to_space_printer.html',1,'tfldump::DepthToSpacePrinter']]],
  ['depthwiseconv2d_51',['DepthwiseConv2D',['../classloco_1_1_depthwise_conv2_d.html',1,'loco::DepthwiseConv2D'],['../classluci__interpreter_1_1kernels_1_1_depthwise_conv2_d.html',1,'luci_interpreter::kernels::DepthwiseConv2D'],['../classonert_1_1ir_1_1operation_1_1_depthwise_conv2_d.html',1,'onert::ir::operation::DepthwiseConv2D']]],
  ['depthwiseconv2d_5f000_5fq8_52',['DepthwiseConv2D_000_Q8',['../class_depthwise_conv2_d__000_1_1_depthwise_conv2_d__000___q8.html',1,'DepthwiseConv2D_000']]],
  ['depthwiseconv2d_5f001_5fq8_53',['DepthwiseConv2D_001_Q8',['../class_depthwise_conv2_d__001_1_1_depthwise_conv2_d__001___q8.html',1,'DepthwiseConv2D_001']]],
  ['depthwiseconv2d_5f002_5fq8_54',['DepthwiseConv2D_002_Q8',['../class_depthwise_conv2_d__002_1_1_depthwise_conv2_d__002___q8.html',1,'DepthwiseConv2D_002']]],
  ['depthwiseconv2d_5f003_5fq8_55',['DepthwiseConv2D_003_Q8',['../class_depthwise_conv2_d__003_1_1_depthwise_conv2_d__003___q8.html',1,'DepthwiseConv2D_003']]],
  ['depthwiseconv2dchef_56',['DepthwiseConv2DChef',['../class_depthwise_conv2_d_chef.html',1,'']]],
  ['depthwiseconv2dcheffactory_57',['DepthwiseConv2DChefFactory',['../struct_depthwise_conv2_d_chef_factory.html',1,'']]],
  ['depthwiseconv2dconverter_58',['DepthwiseConv2DConverter',['../classexo_1_1_depthwise_conv2_d_converter.html',1,'exo']]],
  ['depthwiseconv2dgraphbuilder_59',['DepthwiseConv2DGraphBuilder',['../classtflimport_1_1_depthwise_conv2_d_graph_builder.html',1,'tflimport']]],
  ['depthwiseconv2dimpl_60',['DepthwiseConv2DImpl',['../structmir__interpreter_1_1_depthwise_conv2_d_impl.html',1,'mir_interpreter']]],
  ['depthwiseconv2dimpl_3c_20uint8_5ft_20_3e_61',['DepthwiseConv2DImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_depthwise_conv2_d_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['depthwiseconv2dlayer_62',['DepthwiseConv2DLayer',['../struct_depthwise_conv2_d_layer.html',1,'']]],
  ['depthwiseconv2dnativecanonicalizer_63',['DepthwiseConv2dNativeCanonicalizer',['../classmoco_1_1tf_1_1_depthwise_conv2d_native_canonicalizer.html',1,'moco::tf']]],
  ['depthwiseconv2dnativegraphbuilder_64',['DepthwiseConv2dNativeGraphBuilder',['../classmoco_1_1_depthwise_conv2d_native_graph_builder.html',1,'moco']]],
  ['depthwiseconv2dop_65',['DepthwiseConv2DOp',['../classmir_1_1ops_1_1_depthwise_conv2_d_op.html',1,'mir::ops']]],
  ['depthwiseconv2dparams_66',['DepthwiseConv2DParams',['../structluci__interpreter_1_1_depthwise_conv2_d_params.html',1,'luci_interpreter']]],
  ['depthwiseconv2dprinter_67',['DepthwiseConv2DPrinter',['../classcircledump_1_1_depthwise_conv2_d_printer.html',1,'circledump::DepthwiseConv2DPrinter'],['../classtfldump_1_1_depthwise_conv2_d_printer.html',1,'tfldump::DepthwiseConv2DPrinter']]],
  ['depthwiseconvolutionlayer_68',['DepthwiseConvolutionLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_depthwise_convolution_layer.html',1,'onert::backend::cpu::ops::DepthwiseConvolutionLayer'],['../classonert_1_1backend_1_1xnnpack_1_1ops_1_1_depthwise_convolution_layer.html',1,'onert::backend::xnnpack::ops::DepthwiseConvolutionLayer']]],
  ['depthwiseconvparams_69',['DepthwiseConvParams',['../structnnfw_1_1cker_1_1_depthwise_conv_params.html',1,'nnfw::cker']]],
  ['depthwiseconvworkertask_70',['DepthwiseConvWorkerTask',['../structnnfw_1_1cker_1_1_depthwise_conv_worker_task.html',1,'nnfw::cker::DepthwiseConvWorkerTask&lt; T, TS &gt;'],['../structnnfw_1_1cker_1_1optimized__integer__ops_1_1_depthwise_conv_worker_task.html',1,'nnfw::cker::optimized_integer_ops::DepthwiseConvWorkerTask&lt; T, TS &gt;']]],
  ['depthwisefilterdecode_71',['DepthwiseFilterDecode',['../classloco_1_1_depthwise_filter_decode.html',1,'loco']]],
  ['depthwisefilterdecoder_72',['DepthwiseFilterDecoder',['../structloco_1_1_depthwise_filter_decoder.html',1,'loco']]],
  ['depthwisefilterencode_73',['DepthwiseFilterEncode',['../classloco_1_1_depthwise_filter_encode.html',1,'loco']]],
  ['depthwisefilterencodelayer_74',['DepthwiseFilterEncodeLayer',['../struct_depthwise_filter_encode_layer.html',1,'']]],
  ['depthwisefilterencoder_75',['DepthwiseFilterEncoder',['../structloco_1_1_depthwise_filter_encoder.html',1,'loco']]],
  ['depthwisefilterindex_76',['DepthwiseFilterIndex',['../classloco_1_1_depthwise_filter_index.html',1,'loco']]],
  ['depthwisefiltershape_77',['DepthwiseFilterShape',['../classloco_1_1_depthwise_filter_shape.html',1,'loco']]],
  ['dequantize_78',['Dequantize',['../classluci__interpreter_1_1kernels_1_1_dequantize.html',1,'luci_interpreter::kernels']]],
  ['dequantizechef_79',['DequantizeChef',['../class_dequantize_chef.html',1,'']]],
  ['dequantizecheffactory_80',['DequantizeChefFactory',['../struct_dequantize_chef_factory.html',1,'']]],
  ['dequantizeop_81',['DequantizeOp',['../classmir_1_1ops_1_1_dequantize_op.html',1,'mir::ops']]],
  ['derefnode_82',['DerefNode',['../classnest_1_1expr_1_1_deref_node.html',1,'nest::expr']]],
  ['destroytmp_83',['DestroyTmp',['../structnnc_1_1sir_1_1_destroy_tmp.html',1,'nnc::sir']]],
  ['detachedbuffer_84',['DetachedBuffer',['../classflatbuffers_1_1_detached_buffer.html',1,'flatbuffers']]],
  ['detectionpostprocess_85',['DetectionPostProcess',['../classonert_1_1ir_1_1operation_1_1_detection_post_process.html',1,'onert::ir::operation']]],
  ['detectionpostprocesslayer_86',['DetectionPostProcessLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_detection_post_process_layer.html',1,'onert::backend::cpu::ops']]],
  ['detectionpostprocessparameters_87',['DetectionPostProcessParameters',['../structonert_1_1backend_1_1cpu_1_1ops_1_1_detection_post_process_layer_1_1_detection_post_process_parameters.html',1,'onert::backend::cpu::ops::DetectionPostProcessLayer']]],
  ['devcontext_88',['DevContext',['../classonert_1_1backend_1_1trix_1_1_dev_context.html',1,'onert::backend::trix']]],
  ['device_89',['Device',['../structnpud_1_1core_1_1_device.html',1,'npud::core']]],
  ['devmanager_90',['DevManager',['../classnpud_1_1core_1_1_dev_manager.html',1,'npud::core']]],
  ['dialect_91',['Dialect',['../classloco_1_1_dialect.html',1,'loco']]],
  ['dialectservice_92',['DialectService',['../structloco_1_1_dialect_service.html',1,'loco']]],
  ['diff_93',['Diff',['../structnnfw_1_1misc_1_1tensor_1_1_diff.html',1,'nnfw::misc::tensor']]],
  ['diffsummary_94',['DiffSummary',['../class_diff_summary.html',1,'']]],
  ['dilation_95',['Dilation',['../classluci_1_1_dilation.html',1,'luci::Dilation'],['../structonert_1_1ir_1_1_dilation.html',1,'onert::ir::Dilation']]],
  ['dimension_96',['Dimension',['../classloco_1_1_dimension.html',1,'loco']]],
  ['dimmetadata_97',['DimMetaData',['../classluci_1_1_dim_meta_data.html',1,'luci']]],
  ['dims_98',['Dims',['../struct_dims.html',1,'']]],
  ['directoryloader_99',['DirectoryLoader',['../classcircle__eval__diff_1_1_directory_loader.html',1,'circle_eval_diff']]],
  ['div_100',['Div',['../classcoco_1_1_div.html',1,'coco::Div'],['../classluci__interpreter_1_1kernels_1_1_div.html',1,'luci_interpreter::kernels::Div']]],
  ['divchef_101',['DivChef',['../class_div_chef.html',1,'']]],
  ['divcheffactory_102',['DivChefFactory',['../struct_div_chef_factory.html',1,'']]],
  ['divgraphbuilder_103',['DivGraphBuilder',['../classtflimport_1_1_div_graph_builder.html',1,'tflimport']]],
  ['divimpl_104',['DivImpl',['../structmir__interpreter_1_1_div_impl.html',1,'mir_interpreter']]],
  ['divimpl_3c_20uint8_5ft_20_3e_105',['DivImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_div_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['divop_106',['DivOp',['../classmir_1_1ops_1_1_div_op.html',1,'mir::ops']]],
  ['divparams_107',['DivParams',['../structluci__interpreter_1_1_div_params.html',1,'luci_interpreter']]],
  ['divprinter_108',['DivPrinter',['../classcircledump_1_1_div_printer.html',1,'circledump::DivPrinter'],['../classtfldump_1_1_div_printer.html',1,'tfldump::DivPrinter']]],
  ['dlinkedlist_109',['DLinkedList',['../structcoco_1_1_d_linked_list.html',1,'coco']]],
  ['dlinkedlist_3c_20coco_3a_3ainstr_2c_20coco_3a_3ablock_20_3e_110',['DLinkedList&lt; coco::Instr, coco::Block &gt;',['../structcoco_1_1_d_linked_list.html',1,'coco']]],
  ['domain_111',['Domain',['../classnest_1_1_domain.html',1,'nest']]],
  ['domaincontext_112',['DomainContext',['../classnest_1_1_domain_context.html',1,'nest']]],
  ['domainconverter_113',['DomainConverter',['../classexo_1_1_domain_converter.html',1,'exo']]],
  ['domainid_114',['DomainID',['../classnest_1_1_domain_i_d.html',1,'nest']]],
  ['domaininfo_115',['DomainInfo',['../classnest_1_1_domain_info.html',1,'nest']]],
  ['dotbuilder_116',['DotBuilder',['../class_dot_builder_1_1_dot_builder.html',1,'DotBuilder.DotBuilder'],['../classonert_1_1dumper_1_1dot_1_1_dot_builder.html',1,'onert::dumper::dot::DotBuilder']]],
  ['dotdumper_117',['DotDumper',['../classonert_1_1dumper_1_1dot_1_1_dot_dumper.html',1,'onert::dumper::dot']]],
  ['dotedge_118',['DotEdge',['../structmir_1_1_dot_edge.html',1,'mir']]],
  ['dotgraph_119',['DotGraph',['../classmir_1_1_dot_graph.html',1,'mir']]],
  ['dotnode_120',['DotNode',['../structmir_1_1_dot_node.html',1,'mir']]],
  ['dotnodebuilder_121',['DotNodeBuilder',['../classmir_1_1_dot_node_builder.html',1,'mir']]],
  ['driver_122',['Driver',['../classnnc_1_1_driver.html',1,'nnc']]],
  ['driverexception_123',['DriverException',['../classnnc_1_1_driver_exception.html',1,'nnc']]],
  ['dummybackendcontext_124',['DummyBackendContext',['../classonert_1_1backend_1_1train_1_1_dummy_backend_context.html',1,'onert::backend::train']]],
  ['dummypass1_125',['DummyPass1',['../class_dummy_pass1.html',1,'']]],
  ['dummypass2_126',['DummyPass2',['../class_dummy_pass2.html',1,'']]],
  ['dumpconstants_127',['DumpConstants',['../classcircleinspect_1_1_dump_constants.html',1,'circleinspect']]],
  ['dumpconv2dweight_128',['DumpConv2DWeight',['../classcircleinspect_1_1_dump_conv2_d_weight.html',1,'circleinspect::DumpConv2DWeight'],['../classtflinspect_1_1_dump_conv2_d_weight.html',1,'tflinspect::DumpConv2DWeight']]],
  ['dumper_129',['Dumper',['../classmpqsolver_1_1core_1_1_dumper.html',1,'mpqsolver::core::Dumper'],['../classonert_1_1dumper_1_1h5_1_1_dumper.html',1,'onert::dumper::h5::Dumper']]],
  ['dumperpass_130',['DumperPass',['../classnnc_1_1_dumper_pass.html',1,'nnc']]],
  ['dumpfakequantfm_131',['DumpFakeQuantFM',['../class_dump_fake_quant_f_m_1_1_dump_fake_quant_f_m.html',1,'DumpFakeQuantFM']]],
  ['dumpfp32fm_132',['DumpFP32FM',['../class_dump_f_p32_f_m_1_1_dump_f_p32_f_m.html',1,'DumpFP32FM']]],
  ['dumpinghooks_133',['DumpingHooks',['../classmpqsolver_1_1core_1_1_dumping_hooks.html',1,'mpqsolver::core']]],
  ['dumpinterface_134',['DumpInterface',['../classcircleinspect_1_1_dump_interface.html',1,'circleinspect::DumpInterface'],['../classcircletensordump_1_1_dump_interface.html',1,'circletensordump::DumpInterface'],['../classtflinspect_1_1_dump_interface.html',1,'tflinspect::DumpInterface']]],
  ['dumpoperators_135',['DumpOperators',['../classcircleinspect_1_1_dump_operators.html',1,'circleinspect::DumpOperators'],['../classcirops_1_1_dump_operators.html',1,'cirops::DumpOperators'],['../classtflinspect_1_1_dump_operators.html',1,'tflinspect::DumpOperators']]],
  ['dumpoperatorversion_136',['DumpOperatorVersion',['../classcircleinspect_1_1_dump_operator_version.html',1,'circleinspect::DumpOperatorVersion'],['../classtflinspect_1_1_dump_operator_version.html',1,'tflinspect::DumpOperatorVersion']]],
  ['dumpoption_137',['DumpOption',['../structcirops_1_1_dump_option.html',1,'cirops']]],
  ['dumptensordtype_138',['DumpTensorDType',['../classcircleinspect_1_1_dump_tensor_d_type.html',1,'circleinspect']]],
  ['dumptensors_139',['DumpTensors',['../classcircletensordump_1_1_dump_tensors.html',1,'circletensordump']]],
  ['dumptensorstohdf5_140',['DumpTensorsToHdf5',['../classcircletensordump_1_1_dump_tensors_to_hdf5.html',1,'circletensordump']]],
  ['dumpvisitor_141',['DumpVisitor',['../classnnc_1_1_dump_visitor.html',1,'nnc']]],
  ['duplicatedobjectreductionpass_142',['DuplicatedObjectReductionPass',['../structenco_1_1_duplicated_object_reduction_pass.html',1,'enco']]],
  ['durationevent_143',['DurationEvent',['../struct_duration_event.html',1,'']]],
  ['dynamicbatchtosinglebatchpass_144',['DynamicBatchToSingleBatchPass',['../classluci_1_1_dynamic_batch_to_single_batch_pass.html',1,'luci']]],
  ['dynamicbinder_145',['DynamicBinder',['../structrua_1_1_dynamic_binder.html',1,'rua']]],
  ['dynamicloader_146',['DynamicLoader',['../classnpud_1_1core_1_1_dynamic_loader.html',1,'npud::core']]],
  ['dynamicmemorymanager_147',['DynamicMemoryManager',['../classonert_1_1backend_1_1basic_1_1_dynamic_memory_manager.html',1,'onert::backend::basic']]],
  ['dynamicshapeinferer_148',['DynamicShapeInferer',['../classonert_1_1exec_1_1_dynamic_shape_inferer.html',1,'onert::exec']]],
  ['dynamictensorctx_149',['DynamicTensorCtx',['../structonert_1_1exec_1_1_function_sequence_1_1_dynamic_tensor_ctx.html',1,'onert::exec::FunctionSequence']]],
  ['dynamictensormanager_150',['DynamicTensorManager',['../classonert_1_1backend_1_1basic_1_1_dynamic_tensor_manager.html',1,'onert::backend::basic']]]
];
