var searchData=
[
  ['iacltensor_0',['IACLTensor',['../classonert_1_1backend_1_1acl__common_1_1_i_a_c_l_tensor.html',1,'onert::backend::acl_common']]],
  ['iartifactgenerator_1',['IArtifactGenerator',['../classnnc_1_1_i_artifact_generator.html',1,'nnc']]],
  ['icltensor_2',['ICLTensor',['../classonert_1_1backend_1_1acl__cl_1_1operand_1_1_i_c_l_tensor.html',1,'onert::backend::acl_cl::operand::ICLTensor'],['../classonert_1_1backend_1_1gpu__cl_1_1operand_1_1_i_c_l_tensor.html',1,'onert::backend::gpu_cl::operand::ICLTensor']]],
  ['icompiler_3',['ICompiler',['../classonert_1_1compiler_1_1_i_compiler.html',1,'onert::compiler']]],
  ['iconfig_4',['IConfig',['../structonert_1_1backend_1_1_i_config.html',1,'onert::backend']]],
  ['iconfigsource_5',['IConfigSource',['../structnnfw_1_1misc_1_1_i_config_source.html',1,'nnfw::misc']]],
  ['id_6',['ID',['../structcoco_1_1_feature_layout_1_1_i_d.html',1,'coco::FeatureLayout::ID'],['../structcoco_1_1_kernel_layout_1_1_i_d.html',1,'coco::KernelLayout::ID']]],
  ['identicalobjectreductionpass_7',['IdenticalObjectReductionPass',['../structenco_1_1_identical_object_reduction_pass.html',1,'enco']]],
  ['identity_5fv1_8',['Identity_V1',['../classmoco_1_1onnx_1_1_identity___v1.html',1,'moco::onnx']]],
  ['identitycanonicalizer_9',['IdentityCanonicalizer',['../classmoco_1_1tf_1_1_identity_canonicalizer.html',1,'moco::tf']]],
  ['identitygraphbuilder_10',['IdentityGraphBuilder',['../classmoco_1_1_identity_graph_builder.html',1,'moco::IdentityGraphBuilder'],['../classmoco_1_1onnx_1_1_identity_graph_builder.html',1,'moco::onnx::IdentityGraphBuilder']]],
  ['idloptions_11',['IDLOptions',['../structflatbuffers_1_1_i_d_l_options.html',1,'flatbuffers']]],
  ['ierrorlistener_12',['IErrorListener',['../structloco_1_1_i_error_listener.html',1,'loco']]],
  ['iexecutionobserver_13',['IExecutionObserver',['../classonert_1_1exec_1_1_i_execution_observer.html',1,'onert::exec']]],
  ['iexecutor_14',['IExecutor',['../structonert_1_1exec_1_1_i_executor.html',1,'onert::exec']]],
  ['iexecutors_15',['IExecutors',['../classonert_1_1exec_1_1_i_executors.html',1,'onert::exec']]],
  ['if_16',['If',['../classluci__interpreter_1_1kernels_1_1_if.html',1,'luci_interpreter::kernels::If'],['../classonert_1_1ir_1_1operation_1_1_if.html',1,'onert::ir::operation::If']]],
  ['ifchef_17',['IfChef',['../class_if_chef.html',1,'']]],
  ['ifcheffactory_18',['IfChefFactory',['../struct_if_chef_factory.html',1,'']]],
  ['iflayer_19',['IfLayer',['../classonert_1_1backend_1_1builtin_1_1kernel_1_1_if_layer.html',1,'onert::backend::builtin::kernel']]],
  ['ifprinter_20',['IfPrinter',['../classcircledump_1_1_if_printer.html',1,'circledump::IfPrinter'],['../classtfldump_1_1_if_printer.html',1,'tfldump::IfPrinter']]],
  ['ifunction_21',['IFunction',['../classonert_1_1exec_1_1_i_function.html',1,'onert::exec']]],
  ['iinternalbuffermanager_22',['IInternalBufferManager',['../structonert_1_1backend_1_1acl__common_1_1_i_internal_buffer_manager.html',1,'onert::backend::acl_common']]],
  ['ikernelbuilder_23',['IKernelBuilder',['../classonert_1_1backend_1_1custom_1_1_i_kernel_builder.html',1,'onert::backend::custom']]],
  ['iloweredgraph_24',['ILoweredGraph',['../structonert_1_1compiler_1_1_i_lowered_graph.html',1,'onert::compiler']]],
  ['image_25',['Image',['../struct_image.html',1,'']]],
  ['imemorymanager_26',['IMemoryManager',['../classluci__interpreter_1_1_i_memory_manager.html',1,'luci_interpreter']]],
  ['imemoryplanner_27',['IMemoryPlanner',['../structonert_1_1backend_1_1basic_1_1_i_memory_planner.html',1,'onert::backend::basic']]],
  ['impl_28',['Impl',['../structcirclechef_1_1_generated_model_1_1_impl.html',1,'circlechef::GeneratedModel::Impl'],['../classexo_1_1_circle_exporter_1_1_impl.html',1,'exo::CircleExporter::Impl'],['../classexo_1_1_t_f_l_exporter_1_1_impl.html',1,'exo::TFLExporter::Impl'],['../structtflchef_1_1_generated_model_1_1_impl.html',1,'tflchef::GeneratedModel::Impl']]],
  ['importer_29',['Importer',['../classluci_1_1_importer.html',1,'luci::Importer'],['../classmoco_1_1_importer.html',1,'moco::Importer']]],
  ['importerex_30',['ImporterEx',['../classluci_1_1_importer_ex.html',1,'luci']]],
  ['imutator_31',['IMutator',['../structcoco_1_1_op_1_1_i_mutator.html',1,'coco::Op']]],
  ['indentedstringbuilder_32',['IndentedStringBuilder',['../classpp_1_1_indented_string_builder.html',1,'pp']]],
  ['index_33',['Index',['../classmir_1_1_index.html',1,'mir::Index'],['../classnncc_1_1core_1_1_a_d_t_1_1tensor_1_1_index.html',1,'nncc::core::ADT::tensor::Index'],['../classnnfw_1_1misc_1_1feature_1_1_index.html',1,'nnfw::misc::feature::Index'],['../structnnfw_1_1misc_1_1tensor_1_1_index.html',1,'nnfw::misc::tensor::Index'],['../classonert_1_1util_1_1_index.html',1,'onert::util::Index&lt; T, DummyTag &gt;']]],
  ['index_3c_20uint16_5ft_2c_20modelindextag_20_3e_34',['Index&lt; uint16_t, ModelIndexTag &gt;',['../classonert_1_1util_1_1_index.html',1,'onert::util']]],
  ['index_3c_20uint16_5ft_2c_20subgraphindextag_20_3e_35',['Index&lt; uint16_t, SubgraphIndexTag &gt;',['../classonert_1_1util_1_1_index.html',1,'onert::util']]],
  ['index_3c_20uint32_5ft_2c_20operandindextag_20_3e_36',['Index&lt; uint32_t, OperandIndexTag &gt;',['../classonert_1_1util_1_1_index.html',1,'onert::util']]],
  ['index_3c_20uint32_5ft_2c_20operationindextag_20_3e_37',['Index&lt; uint32_t, OperationIndexTag &gt;',['../classonert_1_1util_1_1_index.html',1,'onert::util']]],
  ['indexenumerator_38',['IndexEnumerator',['../classnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_index_enumerator.html',1,'nncc::core::ADT::kernel::IndexEnumerator'],['../classnncc_1_1core_1_1_a_d_t_1_1tensor_1_1_index_enumerator.html',1,'nncc::core::ADT::tensor::IndexEnumerator'],['../classnnfw_1_1misc_1_1tensor_1_1_index_enumerator.html',1,'nnfw::misc::tensor::IndexEnumerator']]],
  ['indexformatter_39',['IndexFormatter',['../classnnfw_1_1misc_1_1tensor_1_1_index_formatter.html',1,'nnfw::misc::tensor']]],
  ['indexiterator_40',['IndexIterator',['../classnnfw_1_1misc_1_1feature_1_1_index_iterator.html',1,'nnfw::misc::feature::IndexIterator'],['../classnnfw_1_1misc_1_1kernel_1_1_index_iterator.html',1,'nnfw::misc::kernel::IndexIterator'],['../classnnfw_1_1misc_1_1matrix_1_1_index_iterator.html',1,'nnfw::misc::matrix::IndexIterator'],['../classnnfw_1_1misc_1_1tensor_1_1_index_iterator.html',1,'nnfw::misc::tensor::IndexIterator'],['../classonert_1_1exec_1_1feature_1_1_index_iterator.html',1,'onert::exec::feature::IndexIterator']]],
  ['indexnodefinder_41',['IndexNodeFinder',['../classluci_1_1_index_node_finder.html',1,'luci']]],
  ['indextensoroutputs_42',['IndexTensorOutputs',['../classluci_1_1_index_tensor_outputs.html',1,'luci']]],
  ['indirectcopyeliminationpass_43',['IndirectCopyEliminationPass',['../structenco_1_1_indirect_copy_elimination_pass.html',1,'enco']]],
  ['indirecthelper_44',['IndirectHelper',['../structflatbuffers_1_1_indirect_helper.html',1,'flatbuffers']]],
  ['indirecthelper_3c_20const_20t_20_2a_20_3e_45',['IndirectHelper&lt; const T * &gt;',['../structflatbuffers_1_1_indirect_helper_3_01const_01_t_01_5_01_4.html',1,'flatbuffers']]],
  ['indirecthelper_3c_20offset_3c_20t_20_3e_20_3e_46',['IndirectHelper&lt; Offset&lt; T &gt; &gt;',['../structflatbuffers_1_1_indirect_helper_3_01_offset_3_01_t_01_4_01_4.html',1,'flatbuffers']]],
  ['inetensor_47',['INETensor',['../classonert_1_1backend_1_1acl__neon_1_1operand_1_1_i_n_e_tensor.html',1,'onert::backend::acl_neon::operand']]],
  ['inflatefunctor_48',['InflateFunctor',['../structnnfw_1_1cker_1_1functor_1_1_inflate_functor.html',1,'nnfw::cker::functor']]],
  ['initcommand_49',['InitCommand',['../struct_init_command.html',1,'']]],
  ['initparams_50',['InitParams',['../structflatbuffers_1_1_flat_compiler_1_1_init_params.html',1,'flatbuffers::FlatCompiler']]],
  ['input_51',['Input',['../classcoco_1_1_input.html',1,'coco']]],
  ['inputblobcontext_52',['InputBlobContext',['../classnnkit_1_1support_1_1caffe_1_1_input_blob_context.html',1,'nnkit::support::caffe']]],
  ['inputbuilder_53',['InputBuilder',['../classcaffeimport_1_1_input_builder.html',1,'caffeimport']]],
  ['inputconnector_54',['InputConnector',['../classmoco_1_1tf_1_1eltwise_1_1binary_1_1_input_connector.html',1,'moco::tf::eltwise::binary']]],
  ['inputcontext_55',['InputContext',['../structloco_1_1_graph_1_1_input_context.html',1,'loco::Graph']]],
  ['inputdataloader_56',['InputDataLoader',['../classcircle__eval__diff_1_1_input_data_loader.html',1,'circle_eval_diff']]],
  ['inputdesc_57',['InputDesc',['../structonert_1_1exec_1_1_input_desc.html',1,'onert::exec']]],
  ['inputhandler_58',['InputHandler',['../classexo_1_1_input_handler.html',1,'exo']]],
  ['inputindex_59',['InputIndex',['../classnnfw_1_1tflite_1_1_input_index.html',1,'nnfw::tflite']]],
  ['inputlayer_60',['InputLayer',['../struct_input_layer.html',1,'']]],
  ['inputmanager_61',['InputManager',['../classcoco_1_1_input_manager.html',1,'coco']]],
  ['inputop_62',['InputOp',['../classmir_1_1ops_1_1_input_op.html',1,'mir::ops']]],
  ['inputoutputchecker_63',['InputOutputChecker',['../classonert_1_1ir_1_1verifier_1_1_input_output_checker.html',1,'onert::ir::verifier']]],
  ['inputtensor_64',['InputTensor',['../structnnfw_1_1cker_1_1_input_tensor.html',1,'nnfw::cker']]],
  ['inputtensorcontext_65',['InputTensorContext',['../classnnkit_1_1support_1_1moco_1_1tf_1_1_input_tensor_context.html',1,'nnkit::support::moco::tf']]],
  ['inputtensorset_66',['InputTensorSet',['../classnnkit_1_1support_1_1tflite_1_1_input_tensor_set.html',1,'nnkit::support::tflite']]],
  ['instancenorm_67',['InstanceNorm',['../classluci__interpreter_1_1kernels_1_1_instance_norm.html',1,'luci_interpreter::kernels::InstanceNorm'],['../classonert_1_1ir_1_1operation_1_1_instance_norm.html',1,'onert::ir::operation::InstanceNorm']]],
  ['instancenormchef_68',['InstanceNormChef',['../class_instance_norm_chef.html',1,'']]],
  ['instancenormcheffactory_69',['InstanceNormChefFactory',['../struct_instance_norm_chef_factory.html',1,'']]],
  ['instancenormparams_70',['InstanceNormParams',['../structluci__interpreter_1_1_instance_norm_params.html',1,'luci_interpreter::InstanceNormParams'],['../structnnfw_1_1cker_1_1_instance_norm_params.html',1,'nnfw::cker::InstanceNormParams']]],
  ['instancenormprinter_71',['InstanceNormPrinter',['../classcircledump_1_1_instance_norm_printer.html',1,'circledump']]],
  ['instr_72',['Instr',['../classcoco_1_1_instr.html',1,'coco']]],
  ['instrbuilder_73',['InstrBuilder',['../class_instr_builder.html',1,'']]],
  ['instrindex_74',['InstrIndex',['../classcoco_1_1_instr_index.html',1,'coco']]],
  ['instrmanager_75',['InstrManager',['../classcoco_1_1_instr_manager.html',1,'coco']]],
  ['instrprinter_76',['InstrPrinter',['../struct_instr_printer.html',1,'']]],
  ['insufficientbuffersizeexception_77',['InsufficientBufferSizeException',['../classonert_1_1_insufficient_buffer_size_exception.html',1,'onert']]],
  ['integral_5fconstant_78',['integral_constant',['../structflatbuffers_1_1integral__constant.html',1,'flatbuffers']]],
  ['integral_5fconstant_3c_20bool_2c_20b_20_3e_79',['integral_constant&lt; bool, B &gt;',['../structflatbuffers_1_1integral__constant.html',1,'flatbuffers']]],
  ['intergateparameters_80',['InterGateParameters',['../structluci__interpreter_1_1lstm_1_1_inter_gate_parameters.html',1,'luci_interpreter::lstm']]],
  ['internalexn_81',['InternalExn',['../classoops_1_1_internal_exn.html',1,'oops']]],
  ['interpreter_82',['Interpreter',['../classluci__interpreter_1_1_interpreter.html',1,'luci_interpreter']]],
  ['interpreterbackend_83',['InterpreterBackend',['../classnnc_1_1_interpreter_backend.html',1,'nnc']]],
  ['interpretersession_84',['InterpreterSession',['../classnnfw_1_1tflite_1_1_interpreter_session.html',1,'nnfw::tflite']]],
  ['intervalmask_85',['IntervalMask',['../structkuma_1_1details_1_1_interval_mask.html',1,'kuma::details']]],
  ['intervalset_86',['IntervalSet',['../classkuma_1_1details_1_1_interval_set.html',1,'kuma::details']]],
  ['intrinsicselectionpass_87',['IntrinsicSelectionPass',['../structenco_1_1_intrinsic_selection_pass.html',1,'enco']]],
  ['ioconfiguration_88',['IOConfiguration',['../classtfkit_1_1_i_o_configuration.html',1,'tfkit']]],
  ['iodescription_89',['IODescription',['../structonert_1_1exec_1_1_i_o_description.html',1,'onert::exec']]],
  ['ioperation_90',['IOperation',['../structonert_1_1ir_1_1_i_operation.html',1,'onert::ir']]],
  ['ioption_91',['IOption',['../classnnc_1_1cli_1_1_i_option.html',1,'nnc::cli']]],
  ['iotensor_92',['IOTensor',['../classonert_1_1backend_1_1builtin_1_1_i_o_tensor.html',1,'onert::backend::builtin']]],
  ['ipermutefunction_93',['IPermuteFunction',['../classonert_1_1exec_1_1_i_permute_function.html',1,'onert::exec']]],
  ['iportabletensor_94',['IPortableTensor',['../classonert_1_1backend_1_1_i_portable_tensor.html',1,'onert::backend']]],
  ['is_5fenum_95',['is_enum',['../structflatbuffers_1_1is__enum.html',1,'flatbuffers']]],
  ['is_5ffloating_5fpoint_96',['is_floating_point',['../structflatbuffers_1_1is__floating__point.html',1,'flatbuffers']]],
  ['is_5fquant8_97',['is_quant8',['../structnnfw_1_1cker_1_1is__quant8.html',1,'nnfw::cker']]],
  ['is_5fsame_98',['is_same',['../structflatbuffers_1_1is__same.html',1,'flatbuffers']]],
  ['is_5fscalar_99',['is_scalar',['../structflatbuffers_1_1is__scalar.html',1,'flatbuffers']]],
  ['is_5funsigned_100',['is_unsigned',['../structflatbuffers_1_1is__unsigned.html',1,'flatbuffers']]],
  ['ischeduler_101',['IScheduler',['../structonert_1_1compiler_1_1_i_scheduler.html',1,'onert::compiler']]],
  ['iscratchpadhelper_102',['IScratchpadHelper',['../classcircle__planner_1_1_i_scratchpad_helper.html',1,'circle_planner']]],
  ['itensor_103',['ITensor',['../classonert_1_1backend_1_1_i_tensor.html',1,'onert::backend']]],
  ['itensorregistry_104',['ITensorRegistry',['../structonert_1_1backend_1_1_i_tensor_registry.html',1,'onert::backend']]],
  ['iterationvisitor_105',['IterationVisitor',['../structflatbuffers_1_1_iteration_visitor.html',1,'flatbuffers']]],
  ['itimer_106',['ITimer',['../classonert_1_1util_1_1_i_timer.html',1,'onert::util']]],
  ['itrainablefunction_107',['ITrainableFunction',['../classonert_1_1exec_1_1_i_trainable_function.html',1,'onert::exec']]],
  ['itrainableoperation_108',['ITrainableOperation',['../classonert_1_1ir_1_1train_1_1_i_trainable_operation.html',1,'onert::ir::train']]],
  ['iverifier_109',['IVerifier',['../structonert_1_1ir_1_1verifier_1_1_i_verifier.html',1,'onert::ir::verifier']]],
  ['ivisitor_110',['IVisitor',['../structcoco_1_1_instr_1_1_i_visitor.html',1,'coco::Instr::IVisitor&lt; T &gt;'],['../structcoco_1_1_op_1_1_i_visitor.html',1,'coco::Op::IVisitor&lt; T &gt;'],['../classmir_1_1_i_visitor.html',1,'mir::IVisitor']]],
  ['ivisitor_3c_20pp_3a_3alineardocument_20_3e_111',['IVisitor&lt; pp::LinearDocument &gt;',['../structcoco_1_1_instr_1_1_i_visitor.html',1,'coco::Instr']]],
  ['ivisitor_3c_20void_20_3e_112',['IVisitor&lt; void &gt;',['../structcoco_1_1_instr_1_1_i_visitor.html',1,'coco::Instr']]]
];
