var searchData=
[
  ['gateparameters_0',['GateParameters',['../structluci__interpreter_1_1lstm_1_1_gate_parameters.html',1,'luci_interpreter::lstm']]],
  ['gather_1',['Gather',['../classluci__interpreter_1_1kernels_1_1_gather.html',1,'luci_interpreter::kernels::Gather'],['../classonert_1_1ir_1_1operation_1_1_gather.html',1,'onert::ir::operation::Gather']]],
  ['gatherbyt_2',['GatherByT',['../structmir__interpreter_1_1_gather_by_t.html',1,'mir_interpreter']]],
  ['gatherchef_3',['GatherChef',['../class_gather_chef.html',1,'']]],
  ['gathercheffactory_4',['GatherChefFactory',['../struct_gather_chef_factory.html',1,'']]],
  ['gatherimpl_5',['GatherImpl',['../structmir__interpreter_1_1_gather_impl.html',1,'mir_interpreter']]],
  ['gatherlayer_6',['GatherLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_gather_layer.html',1,'onert::backend::cpu::ops']]],
  ['gatherndchef_7',['GatherNdChef',['../class_gather_nd_chef.html',1,'']]],
  ['gatherndcheffactory_8',['GatherNdChefFactory',['../struct_gather_nd_chef_factory.html',1,'']]],
  ['gatherndhelperresult_9',['GatherNdHelperResult',['../structtflite_1_1reference__ops_1_1_gather_nd_helper_result.html',1,'tflite::reference_ops']]],
  ['gatherop_10',['GatherOp',['../classmir_1_1ops_1_1_gather_op.html',1,'mir::ops']]],
  ['gatherparams_11',['GatherParams',['../structluci__interpreter_1_1_gather_params.html',1,'luci_interpreter::GatherParams'],['../structnnfw_1_1cker_1_1_gather_params.html',1,'nnfw::cker::GatherParams']]],
  ['gatherprinter_12',['GatherPrinter',['../classcircledump_1_1_gather_printer.html',1,'circledump::GatherPrinter'],['../classtfldump_1_1_gather_printer.html',1,'tfldump::GatherPrinter']]],
  ['gaussianfloat16datachef_13',['GaussianFloat16DataChef',['../classsouschef_1_1_gaussian_float16_data_chef.html',1,'souschef']]],
  ['gaussianfloat16datacheffactory_14',['GaussianFloat16DataChefFactory',['../structsouschef_1_1_gaussian_float16_data_chef_factory.html',1,'souschef']]],
  ['gaussianfloat32datachef_15',['GaussianFloat32DataChef',['../classsouschef_1_1_gaussian_float32_data_chef.html',1,'souschef']]],
  ['gaussianfloat32datacheffactory_16',['GaussianFloat32DataChefFactory',['../structsouschef_1_1_gaussian_float32_data_chef_factory.html',1,'souschef']]],
  ['gaussianint16datachef_17',['GaussianInt16DataChef',['../classsouschef_1_1_gaussian_int16_data_chef.html',1,'souschef']]],
  ['gaussianint16datacheffactory_18',['GaussianInt16DataChefFactory',['../structsouschef_1_1_gaussian_int16_data_chef_factory.html',1,'souschef']]],
  ['gaussianint32datachef_19',['GaussianInt32DataChef',['../classsouschef_1_1_gaussian_int32_data_chef.html',1,'souschef']]],
  ['gaussianint32datacheffactory_20',['GaussianInt32DataChefFactory',['../structsouschef_1_1_gaussian_int32_data_chef_factory.html',1,'souschef']]],
  ['gaussianuint8datachef_21',['GaussianUint8DataChef',['../classsouschef_1_1_gaussian_uint8_data_chef.html',1,'souschef']]],
  ['gaussianuint8datacheffactory_22',['GaussianUint8DataChefFactory',['../structsouschef_1_1_gaussian_uint8_data_chef_factory.html',1,'souschef']]],
  ['gelu_23',['Gelu',['../classluci__interpreter_1_1kernels_1_1_gelu.html',1,'luci_interpreter::kernels']]],
  ['geluchef_24',['GeluChef',['../class_gelu_chef.html',1,'']]],
  ['gelucheffactory_25',['GeluChefFactory',['../struct_gelu_chef_factory.html',1,'']]],
  ['geluparams_26',['GeluParams',['../structluci__interpreter_1_1_gelu_params.html',1,'luci_interpreter']]],
  ['geluprinter_27',['GeluPrinter',['../classcircledump_1_1_gelu_printer.html',1,'circledump::GeluPrinter'],['../classtfldump_1_1_gelu_printer.html',1,'tfldump::GeluPrinter']]],
  ['gemm_5fpack_5frhs_3c_20scalar_2c_20index_2c_20tensorcontractionsubmapper_3c_20scalar_2c_20index_2c_20rhs_2c_20tensorevaluator_3c_20const_20tensorreshapingop_3c_20newdimension_2c_20const_20tensorimagepatchop_3c_20rows_2c_20cols_2c_20argtype_20_3e_20_3e_2c_20device_20_3e_2c_20nocontract_5ft_2c_20contract_5ft_2c_201_2c_20inner_5fdim_5fcontiguous_2c_20inner_5fdim_5freordered_2c_20alignment_20_3e_2c_20nr_2c_20colmajor_2c_20false_2c_20false_20_3e_28',['gemm_pack_rhs&lt; Scalar, Index, TensorContractionSubMapper&lt; Scalar, Index, Rhs, TensorEvaluator&lt; const TensorReshapingOp&lt; NewDimension, const TensorImagePatchOp&lt; Rows, Cols, ArgType &gt; &gt;, Device &gt;, nocontract_t, contract_t, 1, inner_dim_contiguous, inner_dim_reordered, Alignment &gt;, nr, ColMajor, false, false &gt;',['../struct_eigen_1_1internal_1_1gemm__pack__rhs_3_01_scalar_00_01_index_00_01_tensor_contraction_sub0131574b4fb4009470407f81bed9cd3b.html',1,'Eigen::internal']]],
  ['gemm_5fpack_5frhs_3c_20scalar_2c_20index_2c_20tensorcontractionsubmapper_3c_20scalar_2c_20index_2c_20rhs_2c_20tensorevaluator_3c_20const_20tensorreshapingop_3c_20newdimension_2c_20const_20tensorimagepatchop_3c_20rows_2c_20cols_2c_20argtype_20_3e_20_3e_2c_20device_20_3e_2c_20nocontract_5ft_2c_20contract_5ft_2c_202_2c_20inner_5fdim_5fcontiguous_2c_20inner_5fdim_5freordered_2c_20alignment_20_3e_2c_20nr_2c_20colmajor_2c_20false_2c_20false_20_3e_29',['gemm_pack_rhs&lt; Scalar, Index, TensorContractionSubMapper&lt; Scalar, Index, Rhs, TensorEvaluator&lt; const TensorReshapingOp&lt; NewDimension, const TensorImagePatchOp&lt; Rows, Cols, ArgType &gt; &gt;, Device &gt;, nocontract_t, contract_t, 2, inner_dim_contiguous, inner_dim_reordered, Alignment &gt;, nr, ColMajor, false, false &gt;',['../struct_eigen_1_1internal_1_1gemm__pack__rhs_3_01_scalar_00_01_index_00_01_tensor_contraction_sub5ea63ee4c723e6af21544d00587ce3c0.html',1,'Eigen::internal']]],
  ['gemm_5fpack_5frhs_3c_20scalar_2c_20index_2c_20tensorcontractionsubmapper_3c_20scalar_2c_20index_2c_20rhs_2c_20tensorevaluator_3c_20const_20tensorreshapingop_3c_20newdimension_2c_20const_20tensorimagepatchop_3c_20rows_2c_20cols_2c_20argtype_20_3e_20_3e_2c_20device_20_3e_2c_20nocontract_5ft_2c_20contract_5ft_2c_20packet_5fsize_2c_20inner_5fdim_5fcontiguous_2c_20inner_5fdim_5freordered_2c_20alignment_20_3e_2c_20nr_2c_20colmajor_2c_20false_2c_20false_20_3e_30',['gemm_pack_rhs&lt; Scalar, Index, TensorContractionSubMapper&lt; Scalar, Index, Rhs, TensorEvaluator&lt; const TensorReshapingOp&lt; NewDimension, const TensorImagePatchOp&lt; Rows, Cols, ArgType &gt; &gt;, Device &gt;, nocontract_t, contract_t, packet_size, inner_dim_contiguous, inner_dim_reordered, Alignment &gt;, nr, ColMajor, false, false &gt;',['../struct_eigen_1_1internal_1_1gemm__pack__rhs_3_01_scalar_00_01_index_00_01_tensor_contraction_subd1dba4e0a9a1b5408e755809176fec52.html',1,'Eigen::internal']]],
  ['gemmcontext_31',['GemmContext',['../structnnfw_1_1cker_1_1gemm__support_1_1_gemm_context.html',1,'nnfw::cker::gemm_support']]],
  ['gemmlowpoutputpipeline_32',['GemmlowpOutputPipeline',['../structnnfw_1_1cker_1_1optimized_1_1_gemmlowp_output_pipeline.html',1,'nnfw::cker::optimized']]],
  ['gemmparams_33',['GemmParams',['../structnnfw_1_1cker_1_1_gemm_params.html',1,'nnfw::cker::GemmParams&lt; AccumScalar, DstScalar, quantization_flavor &gt;'],['../structnnfw_1_1ruy_1_1_gemm_params.html',1,'nnfw::ruy::GemmParams&lt; AccumScalar, DstScalar, quantization_flavor &gt;']]],
  ['generalconfigsource_34',['GeneralConfigSource',['../classnnfw_1_1misc_1_1_general_config_source.html',1,'nnfw::misc']]],
  ['generatedmodel_35',['GeneratedModel',['../classcirclechef_1_1_generated_model.html',1,'circlechef::GeneratedModel'],['../classtflchef_1_1_generated_model.html',1,'tflchef::GeneratedModel']]],
  ['generator_36',['Generator',['../structflatbuffers_1_1_flat_compiler_1_1_generator.html',1,'flatbuffers::FlatCompiler']]],
  ['generic_37',['Generic',['../classcoco_1_1_feature_layouts_1_1_generic.html',1,'coco::FeatureLayouts::Generic'],['../classcoco_1_1_kernel_layouts_1_1_generic.html',1,'coco::KernelLayouts::Generic']]],
  ['genericbuffer_38',['GenericBuffer',['../structnpud_1_1core_1_1_generic_buffer.html',1,'npud::core']]],
  ['genericbuffers_39',['GenericBuffers',['../structnpud_1_1core_1_1_generic_buffers.html',1,'npud::core']]],
  ['genericnodesummarybuilder_40',['GenericNodeSummaryBuilder',['../classlocop_1_1_generic_node_summary_builder.html',1,'locop']]],
  ['globaldata_41',['GlobalData',['../structenco_1_1_global_data.html',1,'enco']]],
  ['graph_42',['Graph',['../classloco_1_1_graph.html',1,'loco::Graph'],['../classmir_1_1_graph.html',1,'mir::Graph'],['../classonert_1_1ir_1_1_graph.html',1,'onert::ir::Graph']]],
  ['graphbuilder_43',['GraphBuilder',['../classcaffeimport_1_1_graph_builder.html',1,'caffeimport::GraphBuilder'],['../class_graph_builder.html',1,'GraphBuilder'],['../classluci_1_1_graph_builder.html',1,'luci::GraphBuilder'],['../classmoco_1_1_graph_builder.html',1,'moco::GraphBuilder'],['../classmoco_1_1onnx_1_1_graph_builder.html',1,'moco::onnx::GraphBuilder'],['../classtflimport_1_1_graph_builder.html',1,'tflimport::GraphBuilder']]],
  ['graphbuilderbase_44',['GraphBuilderBase',['../structluci_1_1_graph_builder_base.html',1,'luci']]],
  ['graphbuildercontext_45',['GraphBuilderContext',['../classcaffeimport_1_1_graph_builder_context.html',1,'caffeimport::GraphBuilderContext'],['../classluci_1_1_graph_builder_context.html',1,'luci::GraphBuilderContext'],['../classmoco_1_1_graph_builder_context.html',1,'moco::GraphBuilderContext'],['../classmoco_1_1onnx_1_1_graph_builder_context.html',1,'moco::onnx::GraphBuilderContext'],['../classtflimport_1_1_graph_builder_context.html',1,'tflimport::GraphBuilderContext']]],
  ['graphbuildermultioutput_46',['GraphBuilderMultiOutput',['../classluci_1_1_graph_builder_multi_output.html',1,'luci']]],
  ['graphbuilderregistry_47',['GraphBuilderRegistry',['../classcaffeimport_1_1_graph_builder_registry.html',1,'caffeimport::GraphBuilderRegistry'],['../classluci_1_1_graph_builder_registry.html',1,'luci::GraphBuilderRegistry'],['../classmoco_1_1_graph_builder_registry.html',1,'moco::GraphBuilderRegistry'],['../classmoco_1_1onnx_1_1_graph_builder_registry.html',1,'moco::onnx::GraphBuilderRegistry'],['../classtflimport_1_1_graph_builder_registry.html',1,'tflimport::GraphBuilderRegistry']]],
  ['graphbuildersource_48',['GraphBuilderSource',['../structluci_1_1_graph_builder_source.html',1,'luci::GraphBuilderSource'],['../structmoco_1_1_graph_builder_source.html',1,'moco::GraphBuilderSource']]],
  ['graphinput_49',['GraphInput',['../classloco_1_1_graph_input.html',1,'loco']]],
  ['graphinputindexannotation_50',['GraphInputIndexAnnotation',['../structmoco_1_1_graph_input_index_annotation.html',1,'moco']]],
  ['graphinputindexqueryservice_51',['GraphInputIndexQueryService',['../structloco_1_1_graph_input_index_query_service.html',1,'loco']]],
  ['graphloader_52',['GraphLoader',['../classluci__interpreter_1_1_graph_loader.html',1,'luci_interpreter']]],
  ['graphlowerinfo_53',['GraphLowerInfo',['../structonert_1_1compiler_1_1_graph_lower_info.html',1,'onert::compiler']]],
  ['graphoutput_54',['GraphOutput',['../classloco_1_1_graph_output.html',1,'loco']]],
  ['graphoutputindexqueryservice_55',['GraphOutputIndexQueryService',['../structloco_1_1_graph_output_index_query_service.html',1,'loco']]],
  ['graphpatternmatcher_56',['GraphPatternMatcher',['../classmir_1_1_graph_pattern_matcher.html',1,'mir']]],
  ['graphtestcase_57',['GraphTestcase',['../class_graph_testcase.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3aavgpool2d_20_3e_58',['GraphTestcase&lt; GraphCode::AvgPool2D &gt;',['../class_graph_testcase_3_01_graph_code_1_1_avg_pool2_d_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3aconstgen_20_3e_59',['GraphTestcase&lt; GraphCode::ConstGen &gt;',['../class_graph_testcase_3_01_graph_code_1_1_const_gen_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3adepthwiseconv2d_20_3e_60',['GraphTestcase&lt; GraphCode::DepthwiseConv2D &gt;',['../class_graph_testcase_3_01_graph_code_1_1_depthwise_conv2_d_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3afeaturecodec_20_3e_61',['GraphTestcase&lt; GraphCode::FeatureCodec &gt;',['../class_graph_testcase_3_01_graph_code_1_1_feature_codec_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3afixedreshape_20_3e_62',['GraphTestcase&lt; GraphCode::FixedReshape &gt;',['../class_graph_testcase_3_01_graph_code_1_1_fixed_reshape_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3aidentity_20_3e_63',['GraphTestcase&lt; GraphCode::Identity &gt;',['../class_graph_testcase_3_01_graph_code_1_1_identity_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3amaxpool2d_20_3e_64',['GraphTestcase&lt; GraphCode::MaxPool2D &gt;',['../class_graph_testcase_3_01_graph_code_1_1_max_pool2_d_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3arelu_20_3e_65',['GraphTestcase&lt; GraphCode::Relu &gt;',['../class_graph_testcase_3_01_graph_code_1_1_relu_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3atensorbroadcast_20_3e_66',['GraphTestcase&lt; GraphCode::TensorBroadcast &gt;',['../class_graph_testcase_3_01_graph_code_1_1_tensor_broadcast_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3atensorconcat_20_3e_67',['GraphTestcase&lt; GraphCode::TensorConcat &gt;',['../class_graph_testcase_3_01_graph_code_1_1_tensor_concat_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3atensortranspose_20_3e_68',['GraphTestcase&lt; GraphCode::TensorTranspose &gt;',['../class_graph_testcase_3_01_graph_code_1_1_tensor_transpose_01_4.html',1,'']]],
  ['graphtestcase_3c_20graphcode_3a_3atransposedconv2d_20_3e_69',['GraphTestcase&lt; GraphCode::TransposedConv2D &gt;',['../class_graph_testcase_3_01_graph_code_1_1_transposed_conv2_d_01_4.html',1,'']]],
  ['graphupdate_70',['GraphUpdate',['../classmoco_1_1_graph_update.html',1,'moco']]],
  ['greater_71',['Greater',['../classluci__interpreter_1_1kernels_1_1_greater.html',1,'luci_interpreter::kernels']]],
  ['greaterchef_72',['GreaterChef',['../class_greater_chef.html',1,'']]],
  ['greatercheffactory_73',['GreaterChefFactory',['../struct_greater_chef_factory.html',1,'']]],
  ['greaterequal_74',['GreaterEqual',['../classluci__interpreter_1_1kernels_1_1_greater_equal.html',1,'luci_interpreter::kernels']]],
  ['greaterequalchef_75',['GreaterEqualChef',['../class_greater_equal_chef.html',1,'']]],
  ['greaterequalcheffactory_76',['GreaterEqualChefFactory',['../struct_greater_equal_chef_factory.html',1,'']]],
  ['greaterimpl_77',['GreaterImpl',['../structmir__interpreter_1_1_greater_impl.html',1,'mir_interpreter']]],
  ['greaterop_78',['GreaterOp',['../classmir_1_1ops_1_1_greater_op.html',1,'mir::ops']]]
];
