var searchData=
[
  ['backend_0',['backend',['../structnnkit_1_1_backend.html',1,'nnkit::Backend'],['../structenco_1_1_backend.html',1,'enco::Backend'],['../classonert_1_1backend_1_1trix_1_1_backend.html',1,'onert::backend::trix::Backend'],['../classonert_1_1backend_1_1train_1_1_backend.html',1,'onert::backend::train::Backend'],['../classonert_1_1backend_1_1ruy_1_1_backend.html',1,'onert::backend::ruy::Backend'],['../classonert_1_1backend_1_1ggml_1_1_backend.html',1,'onert::backend::ggml::Backend'],['../classonert_1_1backend_1_1cpu_1_1_backend.html',1,'onert::backend::cpu::Backend'],['../classonert_1_1backend_1_1builtin_1_1_backend.html',1,'onert::backend::builtin::Backend'],['../classonert_1_1backend_1_1acl__neon_1_1_backend.html',1,'onert::backend::acl_neon::Backend'],['../classonert_1_1backend_1_1_backend.html',1,'onert::backend::Backend'],['../classnnkit_1_1support_1_1caffe_1_1_backend.html',1,'nnkit::support::caffe::Backend&lt; DType &gt;'],['../classnnkit_1_1support_1_1moco_1_1tf_1_1_backend.html',1,'nnkit::support::moco::tf::Backend'],['../classnnkit_1_1support_1_1tf_1_1_backend.html',1,'nnkit::support::tf::Backend'],['../classonert_1_1backend_1_1acl__cl_1_1_backend.html',1,'onert::backend::acl_cl::Backend'],['../classnnkit_1_1support_1_1onnx_1_1_backend.html',1,'nnkit::support::onnx::Backend']]],
  ['backendcontext_1',['backendcontext',['../classonert_1_1backend_1_1_backend_context.html',1,'onert::backend::BackendContext'],['../classonert_1_1backend_1_1builtin_1_1_backend_context.html',1,'onert::backend::builtin::BackendContext'],['../classonert_1_1backend_1_1builtin_1_1train_1_1_backend_context.html',1,'onert::backend::builtin::train::BackendContext'],['../classonert_1_1backend_1_1cl__common_1_1_backend_context.html',1,'onert::backend::cl_common::BackendContext&lt; T_TensorBuilder, T_ConstantInitializer, T_KernelGenerator &gt;'],['../classonert_1_1backend_1_1cpu_1_1_backend_context.html',1,'onert::backend::cpu::BackendContext'],['../classonert_1_1backend_1_1ggml_1_1_backend_context.html',1,'onert::backend::ggml::BackendContext'],['../classonert_1_1backend_1_1ruy_1_1_backend_context.html',1,'onert::backend::ruy::BackendContext'],['../classonert_1_1backend_1_1train_1_1_backend_context.html',1,'onert::backend::train::BackendContext'],['../classonert_1_1backend_1_1trix_1_1_backend_context.html',1,'onert::backend::trix::BackendContext']]],
  ['backendmanager_2',['BackendManager',['../classonert_1_1compiler_1_1_backend_manager.html',1,'onert::compiler']]],
  ['backendplugin_3',['BackendPlugin',['../classnnkit_1_1_backend_plugin.html',1,'nnkit']]],
  ['backendresolver_4',['BackendResolver',['../classonert_1_1compiler_1_1_backend_resolver.html',1,'onert::compiler']]],
  ['backpropaccumulator_5',['BackPropAccumulator',['../classonert_1_1backend_1_1train_1_1ops_1_1_back_prop_accumulator.html',1,'onert::backend::train::ops']]],
  ['backpropinitializer_6',['BackPropInitializer',['../classonert_1_1backend_1_1train_1_1ops_1_1_back_prop_initializer.html',1,'onert::backend::train::ops']]],
  ['badoption_7',['BadOption',['../classnnc_1_1cli_1_1_bad_option.html',1,'nnc::cli']]],
  ['bag_8',['Bag',['../classcoco_1_1_bag.html',1,'coco']]],
  ['bagduplicationpass_9',['BagDuplicationPass',['../structenco_1_1_bag_duplication_pass.html',1,'enco']]],
  ['bagmanager_10',['BagManager',['../classcoco_1_1_bag_manager.html',1,'coco']]],
  ['basegenerator_11',['BaseGenerator',['../classflatbuffers_1_1_base_generator.html',1,'flatbuffers']]],
  ['baseloader_12',['BaseLoader',['../classonert_1_1loader_1_1_base_loader.html',1,'onert::loader']]],
  ['basesession_13',['BaseSession',['../classonert_1_1common_1_1basesession_1_1_base_session.html',1,'onert::common::basesession']]],
  ['batchmatmul_14',['batchmatmul',['../classluci__interpreter_1_1kernels_1_1_batch_mat_mul.html',1,'luci_interpreter::kernels::BatchMatMul'],['../classnnfw_1_1cker_1_1_batch_mat_mul.html',1,'nnfw::cker::BatchMatMul'],['../classonert_1_1ir_1_1operation_1_1_batch_mat_mul.html',1,'onert::ir::operation::BatchMatMul']]],
  ['batchmatmulchef_15',['BatchMatMulChef',['../class_batch_mat_mul_chef.html',1,'']]],
  ['batchmatmulcheffactory_16',['BatchMatMulChefFactory',['../struct_batch_mat_mul_chef_factory.html',1,'']]],
  ['batchmatmullayer_17',['BatchMatMulLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_batch_mat_mul_layer.html',1,'onert::backend::cpu::ops']]],
  ['batchmatmulparams_18',['batchmatmulparams',['../structluci__interpreter_1_1_batch_mat_mul_params.html',1,'luci_interpreter::BatchMatMulParams'],['../structnnfw_1_1cker_1_1_batch_mat_mul_params.html',1,'nnfw::cker::BatchMatMulParams']]],
  ['batchmatmulprinter_19',['BatchMatMulPrinter',['../classcircledump_1_1_batch_mat_mul_printer.html',1,'circledump']]],
  ['batchmatmulv2chef_20',['BatchMatMulV2Chef',['../class_batch_mat_mul_v2_chef.html',1,'']]],
  ['batchmatmulv2cheffactory_21',['BatchMatMulV2ChefFactory',['../struct_batch_mat_mul_v2_chef_factory.html',1,'']]],
  ['batchnormbuilder_22',['BatchNormBuilder',['../classcaffeimport_1_1_batch_norm_builder.html',1,'caffeimport']]],
  ['batchthreadpool_23',['BatchThreadPool',['../classonert_1_1backend_1_1trix_1_1_batch_thread_pool.html',1,'onert::backend::trix']]],
  ['batchtospacend_24',['batchtospacend',['../classluci__interpreter_1_1kernels_1_1_batch_to_space_n_d.html',1,'luci_interpreter::kernels::BatchToSpaceND'],['../classonert_1_1ir_1_1operation_1_1_batch_to_space_n_d.html',1,'onert::ir::operation::BatchToSpaceND']]],
  ['batchtospacendchef_25',['BatchToSpaceNDChef',['../class_batch_to_space_n_d_chef.html',1,'']]],
  ['batchtospacendcheffactory_26',['BatchToSpaceNDChefFactory',['../struct_batch_to_space_n_d_chef_factory.html',1,'']]],
  ['batchtospacendlayer_27',['BatchToSpaceNDLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_batch_to_space_n_d_layer.html',1,'onert::backend::cpu::ops']]],
  ['bc_28',['BC',['../classcoco_1_1_feature_layouts_1_1_b_c.html',1,'coco::FeatureLayouts']]],
  ['bcast_29',['BCast',['../classnnfw_1_1cker_1_1_b_cast.html',1,'nnfw::cker']]],
  ['bcastlist_30',['BCastList',['../classnnfw_1_1cker_1_1_b_cast_list.html',1,'nnfw::cker']]],
  ['bcastlist_3c_202_20_3e_31',['BCastList&lt; 2 &gt;',['../classnnfw_1_1cker_1_1_b_cast_list.html',1,'nnfw::cker']]],
  ['bchw_32',['BCHW',['../classcoco_1_1_feature_layouts_1_1_b_c_h_w.html',1,'coco::FeatureLayouts']]],
  ['bcqfullyconnected_33',['BCQFullyConnected',['../classonert_1_1ir_1_1operation_1_1_b_c_q_fully_connected.html',1,'onert::ir::operation']]],
  ['bcqfullyconnectedchef_34',['BCQFullyConnectedChef',['../class_b_c_q_fully_connected_chef.html',1,'']]],
  ['bcqfullyconnectedcheffactory_35',['BCQFullyConnectedChefFactory',['../struct_b_c_q_fully_connected_chef_factory.html',1,'']]],
  ['bcqfullyconnectedprinter_36',['BCQFullyConnectedPrinter',['../classcircledump_1_1_b_c_q_fully_connected_printer.html',1,'circledump']]],
  ['bcqgather_37',['BCQGather',['../classonert_1_1ir_1_1operation_1_1_b_c_q_gather.html',1,'onert::ir::operation']]],
  ['bcqgatherchef_38',['BCQGatherChef',['../class_b_c_q_gather_chef.html',1,'']]],
  ['bcqgathercheffactory_39',['BCQGatherChefFactory',['../struct_b_c_q_gather_chef_factory.html',1,'']]],
  ['bcqgatherprinter_40',['BCQGatherPrinter',['../classcircledump_1_1_b_c_q_gather_printer.html',1,'circledump']]],
  ['bcqunembedding_41',['BCQUnembedding',['../classonert_1_1ir_1_1operation_1_1_b_c_q_unembedding.html',1,'onert::ir::operation']]],
  ['bhwc_42',['BHWC',['../classcoco_1_1_feature_layouts_1_1_b_h_w_c.html',1,'coco::FeatureLayouts']]],
  ['bias_43',['Bias',['../structnnfw_1_1cker_1_1bias__op_1_1functor_1_1_bias.html',1,'nnfw::cker::bias_op::functor']]],
  ['biasadd_44',['BiasAdd',['../classloco_1_1_bias_add.html',1,'loco']]],
  ['biasadd_3c_20domain_3a_3afeature_20_3e_45',['BiasAdd&lt; Domain::Feature &gt;',['../classloco_1_1_bias_add_3_01_domain_1_1_feature_01_4.html',1,'loco']]],
  ['biasadd_3c_20domain_3a_3atensor_20_3e_46',['BiasAdd&lt; Domain::Tensor &gt;',['../classloco_1_1_bias_add_3_01_domain_1_1_tensor_01_4.html',1,'loco']]],
  ['biasaddcanonicalizer_47',['BiasAddCanonicalizer',['../classmoco_1_1tf_1_1_bias_add_canonicalizer.html',1,'moco::tf']]],
  ['biasaddgraphbuilder_48',['BiasAddGraphBuilder',['../classmoco_1_1_bias_add_graph_builder.html',1,'moco']]],
  ['biasdecode_49',['BiasDecode',['../classloco_1_1_bias_decode.html',1,'loco']]],
  ['biasencode_50',['BiasEncode',['../classloco_1_1_bias_encode.html',1,'loco']]],
  ['biasshape_51',['BiasShape',['../classloco_1_1_bias_shape.html',1,'loco']]],
  ['bidirectionalsequencelstmchef_52',['BidirectionalSequenceLSTMChef',['../class_bidirectional_sequence_l_s_t_m_chef.html',1,'']]],
  ['bidirectionalsequencelstmcheffactory_53',['BidirectionalSequenceLSTMChefFactory',['../struct_bidirectional_sequence_l_s_t_m_chef_factory.html',1,'']]],
  ['bidirectionalsequencelstmprinter_54',['bidirectionalsequencelstmprinter',['../classcircledump_1_1_bidirectional_sequence_l_s_t_m_printer.html',1,'circledump::BidirectionalSequenceLSTMPrinter'],['../classtfldump_1_1_bidirectional_sequence_l_s_t_m_printer.html',1,'tfldump::BidirectionalSequenceLSTMPrinter']]],
  ['binaryarithmetic_55',['binaryarithmetic',['../classonert_1_1ir_1_1operation_1_1_binary_arithmetic.html',1,'onert::ir::operation::BinaryArithmetic'],['../classonert_1_1ir_1_1train_1_1operation_1_1_binary_arithmetic.html',1,'onert::ir::train::operation::BinaryArithmetic']]],
  ['binaryarithmeticbroadcastparams_56',['BinaryArithmeticBroadcastParams',['../structonert__micro_1_1core_1_1_binary_arithmetic_broadcast_params.html',1,'onert_micro::core']]],
  ['binaryarithmeticlayer_57',['binaryarithmeticlayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_binary_arithmetic_layer.html',1,'onert::backend::cpu::ops::BinaryArithmeticLayer'],['../classonert_1_1backend_1_1train_1_1ops_1_1_binary_arithmetic_layer.html',1,'onert::backend::train::ops::BinaryArithmeticLayer']]],
  ['binaryarithmeticopparam_58',['BinaryArithmeticOpParam',['../structnnfw_1_1cker_1_1_binary_arithmetic_op_param.html',1,'nnfw::cker']]],
  ['binaryelementwiseop_59',['BinaryElementwiseOp',['../classmir_1_1ops_1_1_binary_elementwise_op.html',1,'mir::ops']]],
  ['binaryfunc_60',['binaryfunc',['../structlocomotiv_1_1_binary_func.html',1,'locomotiv::BinaryFunc'],['../structmoco_1_1_binary_func.html',1,'moco::BinaryFunc']]],
  ['binaryop_61',['BinaryOp',['../classcoco_1_1_binary_op.html',1,'coco']]],
  ['binaryopactivationfloatmax_62',['BinaryOpActivationFloatMax',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_activation_float_max.html',1,'nnfw::cker::optimized']]],
  ['binaryopactivationfloatminmax_63',['BinaryOpActivationFloatMinMax',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_activation_float_min_max.html',1,'nnfw::cker::optimized']]],
  ['binaryopactivationfloatnone_64',['BinaryOpActivationFloatNone',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_activation_float_none.html',1,'nnfw::cker::optimized']]],
  ['binaryopfuncaddfloat_65',['BinaryOpFuncAddFloat',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_func_add_float.html',1,'nnfw::cker::optimized']]],
  ['binaryopfuncdivfloat_66',['BinaryOpFuncDivFloat',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_func_div_float.html',1,'nnfw::cker::optimized']]],
  ['binaryopfuncmulfloat_67',['BinaryOpFuncMulFloat',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_func_mul_float.html',1,'nnfw::cker::optimized']]],
  ['binaryopfuncsubfloat_68',['BinaryOpFuncSubFloat',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_func_sub_float.html',1,'nnfw::cker::optimized']]],
  ['binaryopfuncswapargs_69',['BinaryOpFuncSwapArgs',['../structnnfw_1_1cker_1_1optimized_1_1_binary_op_func_swap_args.html',1,'nnfw::cker::optimized']]],
  ['bisectionsolver_70',['BisectionSolver',['../classmpqsolver_1_1bisection_1_1_bisection_solver.html',1,'mpqsolver::bisection']]],
  ['blob_71',['Blob',['../classflexbuffers_1_1_blob.html',1,'flexbuffers']]],
  ['blobcontext_72',['BlobContext',['../structnnkit_1_1support_1_1caffe_1_1_blob_context.html',1,'nnkit::support::caffe']]],
  ['block_73',['block',['../structonert_1_1backend_1_1basic_1_1_block.html',1,'onert::backend::basic::Block'],['../classcoco_1_1_block.html',1,'coco::Block'],['../structnest_1_1_block.html',1,'nest::Block']]],
  ['blockindex_74',['BlockIndex',['../classcoco_1_1_block_index.html',1,'coco']]],
  ['blockmanager_75',['BlockManager',['../classcoco_1_1_block_manager.html',1,'coco']]],
  ['bool_5fconstant_76',['bool_constant',['../structflatbuffers_1_1bool__constant.html',1,'flatbuffers']]],
  ['bound_77',['Bound',['../classnest_1_1_bound.html',1,'nest']]],
  ['broadcastablewrapper_78',['BroadcastableWrapper',['../classluci__interpreter_1_1kernels_1_1_broadcastable_wrapper.html',1,'luci_interpreter::kernels']]],
  ['broadcastfunctor_79',['BroadcastFunctor',['../classmoco_1_1tf_1_1_broadcast_functor.html',1,'moco::tf']]],
  ['broadcastop_80',['BroadcastOp',['../classmir_1_1ops_1_1_broadcast_op.html',1,'mir::ops']]],
  ['broadcastto_81',['broadcastto',['../classluci__interpreter_1_1kernels_1_1_broadcast_to.html',1,'luci_interpreter::kernels::BroadcastTo'],['../structnnfw_1_1cker_1_1functor_1_1_broadcast_to.html',1,'nnfw::cker::functor::BroadcastTo&lt; Device, T &gt;'],['../classonert_1_1ir_1_1operation_1_1_broadcast_to.html',1,'onert::ir::operation::BroadcastTo']]],
  ['broadcasttochef_82',['BroadcastToChef',['../class_broadcast_to_chef.html',1,'']]],
  ['broadcasttocheffactory_83',['BroadcastToChefFactory',['../struct_broadcast_to_chef_factory.html',1,'']]],
  ['broadcasttolayer_84',['BroadcastToLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_broadcast_to_layer.html',1,'onert::backend::cpu::ops']]],
  ['buddymemorymanager_85',['BuddyMemoryManager',['../classluci__interpreter_1_1_buddy_memory_manager.html',1,'luci_interpreter']]],
  ['buffer_86',['buffer',['../classnncc_1_1core_1_1_a_d_t_1_1tensor_1_1_buffer.html',1,'nncc::core::ADT::tensor::Buffer&lt; T &gt;'],['../classnncc_1_1core_1_1_a_d_t_1_1feature_1_1_buffer.html',1,'nncc::core::ADT::feature::Buffer&lt; T &gt;'],['../classnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_buffer.html',1,'nncc::core::ADT::kernel::Buffer&lt; T &gt;']]],
  ['buffer_3c_20float_20_3e_87',['Buffer&lt; float &gt;',['../classnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_buffer.html',1,'nncc::core::ADT::kernel']]],
  ['bufferlink_88',['BufferLink',['../structtflite2circle_1_1_buffer_link.html',1,'tflite2circle']]],
  ['bufferref_89',['BufferRef',['../structflatbuffers_1_1_buffer_ref.html',1,'flatbuffers']]],
  ['bufferrefbase_90',['BufferRefBase',['../structflatbuffers_1_1_buffer_ref_base.html',1,'flatbuffers']]],
  ['buildnodeargs_91',['BuildNodeArgs',['../structluci_1_1_graph_builder_multi_output_1_1_build_node_args.html',1,'luci::GraphBuilderMultiOutput']]],
  ['buildoutargs_92',['BuildOutArgs',['../structluci_1_1_graph_builder_multi_output_1_1_build_out_args.html',1,'luci::GraphBuilderMultiOutput']]],
  ['builtinoperatormappingrule_93',['BuiltinOperatorMappingRule',['../classluci_1_1_builtin_operator_mapping_rule.html',1,'luci']]],
  ['builtinoptionsextractor_94',['BuiltinOptionsExtractor',['../classluci_1_1_builtin_options_extractor.html',1,'luci']]],
  ['builtinoptionsmappingrule_95',['BuiltinOptionsMappingRule',['../classluci_1_1_builtin_options_mapping_rule.html',1,'luci']]],
  ['bulk_96',['Bulk',['../classonert_1_1ir_1_1operation_1_1_bulk.html',1,'onert::ir::operation']]],
  ['bulklayer_97',['BulkLayer',['../classonert_1_1backend_1_1trix_1_1ops_1_1_bulk_layer.html',1,'onert::backend::trix::ops']]],
  ['bulkpipelinebuffer_98',['BulkPipelineBuffer',['../classonert_1_1backend_1_1trix_1_1ops_1_1_bulk_pipeline_buffer.html',1,'onert::backend::trix::ops']]],
  ['bulkpipelinemodel_99',['BulkPipelineModel',['../classonert_1_1backend_1_1trix_1_1ops_1_1_bulk_pipeline_model.html',1,'onert::backend::trix::ops']]],
  ['bumpplanner_100',['bumpplanner',['../classonert_1_1backend_1_1basic_1_1_bump_planner.html',1,'onert::backend::basic::BumpPlanner'],['../classonert_1_1backend_1_1train_1_1_bump_planner.html',1,'onert::backend::train::BumpPlanner&lt; Index &gt;']]],
  ['bundle_101',['Bundle',['../classenco_1_1_bundle.html',1,'enco']]],
  ['bypassgenerationpass_102',['BypassGenerationPass',['../structenco_1_1_bypass_generation_pass.html',1,'enco']]]
];
