var searchData=
[
  ['scalar_5flogistic_5fop_0',['scalar_logistic_op',['../structnnfw_1_1cker_1_1scalar__logistic__op.html',1,'nnfw::cker']]],
  ['scalaroperand_1',['ScalarOperand',['../structann_1_1_scalar_operand.html',1,'ann']]],
  ['scale_2',['Scale',['../structonert_1_1ir_1_1operation_1_1_detection_post_process_1_1_scale.html',1,'onert::ir::operation::DetectionPostProcess']]],
  ['scalebuilder_3',['ScaleBuilder',['../classcaffeimport_1_1_scale_builder.html',1,'caffeimport']]],
  ['scatterndchef_4',['ScatterNdChef',['../class_scatter_nd_chef.html',1,'']]],
  ['scatterndcheffactory_5',['ScatterNdChefFactory',['../struct_scatter_nd_chef_factory.html',1,'']]],
  ['schedule_6',['Schedule',['../classnest_1_1_schedule.html',1,'nest']]],
  ['scratchpadhelpercmsisnn_7',['ScratchpadHelperCMSISNN',['../classcircle__planner_1_1_scratchpad_helper_c_m_s_i_s_n_n.html',1,'circle_planner']]],
  ['scratchpadhelperlinux_8',['ScratchpadHelperLinux',['../classcircle__planner_1_1_scratchpad_helper_linux.html',1,'circle_planner']]],
  ['scratchpadhelpermcu_9',['ScratchpadHelperMCU',['../classcircle__planner_1_1_scratchpad_helper_m_c_u.html',1,'circle_planner']]],
  ['section_10',['Section',['../structcrew_1_1_section.html',1,'crew']]],
  ['segmentsumchef_11',['SegmentSumChef',['../class_segment_sum_chef.html',1,'']]],
  ['segmentsumcheffactory_12',['SegmentSumChefFactory',['../struct_segment_sum_chef_factory.html',1,'']]],
  ['select_13',['Select',['../classonert_1_1ir_1_1operation_1_1_select.html',1,'onert::ir::operation']]],
  ['selectchef_14',['SelectChef',['../class_select_chef.html',1,'']]],
  ['selectcheffactory_15',['SelectChefFactory',['../struct_select_chef_factory.html',1,'']]],
  ['selectlayer_16',['SelectLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_select_layer.html',1,'onert::backend::cpu::ops']]],
  ['selectv2chef_17',['SelectV2Chef',['../class_select_v2_chef.html',1,'']]],
  ['selectv2cheffactory_18',['SelectV2ChefFactory',['../struct_select_v2_chef_factory.html',1,'']]],
  ['sequentialtensorwriter_19',['SequentialTensorWriter',['../classnnfw_1_1cker_1_1_sequential_tensor_writer.html',1,'nnfw::cker']]],
  ['serializedgraphdata_20',['SerializedGraphData',['../structluci_1_1_serialized_graph_data.html',1,'luci']]],
  ['serializedmodeldata_21',['SerializedModelData',['../structexo_1_1circle__detail_1_1_serialized_model_data.html',1,'exo::circle_detail::SerializedModelData'],['../structexo_1_1tflite__detail_1_1_serialized_model_data.html',1,'exo::tflite_detail::SerializedModelData'],['../structluci_1_1_serialized_model_data.html',1,'luci::SerializedModelData']]],
  ['serializer_22',['Serializer',['../classnnc_1_1_serializer.html',1,'nnc']]],
  ['server_23',['Server',['../classnpud_1_1core_1_1_server.html',1,'npud::core']]],
  ['session_24',['Session',['../classlocomotiv_1_1_session.html',1,'locomotiv::Session'],['../structnnfw_1_1tflite_1_1_session.html',1,'nnfw::tflite::Session']]],
  ['set_25',['Set',['../classonert_1_1util_1_1_set.html',1,'onert::util']]],
  ['set_3c_20onert_3a_3autil_3a_3aindex_20_3e_26',['Set&lt; onert::util::Index &gt;',['../classonert_1_1util_1_1_set.html',1,'onert::util']]],
  ['set_3c_20permutefactor_20_3e_27',['Set&lt; PermuteFactor &gt;',['../classonert_1_1util_1_1_set.html',1,'onert::util']]],
  ['setzerofunctor_28',['SetZeroFunctor',['../structnnfw_1_1cker_1_1functor_1_1_set_zero_functor.html',1,'nnfw::cker::functor']]],
  ['severity_29',['Severity',['../classhermes_1_1_severity.html',1,'hermes']]],
  ['shape_30',['Shape',['../classlocoex_1_1_t_f_l_reshape_1_1_shape.html',1,'locoex::TFLReshape::Shape'],['../classluci_1_1_circle_reshape_1_1_shape.html',1,'luci::CircleReshape::Shape'],['../classluci__interpreter_1_1_shape.html',1,'luci_interpreter::Shape'],['../classmir_1_1_shape.html',1,'mir::Shape'],['../classndarray_1_1_shape.html',1,'ndarray::Shape'],['../classnncc_1_1core_1_1_a_d_t_1_1feature_1_1_shape.html',1,'nncc::core::ADT::feature::Shape'],['../classnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_shape.html',1,'nncc::core::ADT::kernel::Shape'],['../classnncc_1_1core_1_1_a_d_t_1_1tensor_1_1_shape.html',1,'nncc::core::ADT::tensor::Shape'],['../classnnfw_1_1cker_1_1_shape.html',1,'nnfw::cker::Shape'],['../structnnfw_1_1misc_1_1feature_1_1_shape.html',1,'nnfw::misc::feature::Shape'],['../structnnfw_1_1misc_1_1kernel_1_1_shape.html',1,'nnfw::misc::kernel::Shape'],['../structnnfw_1_1misc_1_1matrix_1_1_shape.html',1,'nnfw::misc::matrix::Shape'],['../classnnfw_1_1misc_1_1tensor_1_1_shape.html',1,'nnfw::misc::tensor::Shape'],['../classnnfw_1_1ruy_1_1_shape.html',1,'nnfw::ruy::Shape'],['../classonert_1_1ir_1_1operation_1_1_shape.html',1,'onert::ir::operation::Shape'],['../structonert_1_1ir_1_1_shape.html',1,'onert::ir::Shape'],['../struct_shape.html',1,'Shape']]],
  ['shapechef_31',['ShapeChef',['../class_shape_chef.html',1,'']]],
  ['shapecheffactory_32',['ShapeChefFactory',['../struct_shape_chef_factory.html',1,'']]],
  ['shapedescription_33',['ShapeDescription',['../structexo_1_1_shape_description.html',1,'exo::ShapeDescription'],['../structluci_1_1_shape_description.html',1,'luci::ShapeDescription']]],
  ['shapegraphbuilder_34',['ShapeGraphBuilder',['../classmoco_1_1_shape_graph_builder.html',1,'moco']]],
  ['shapehint_35',['ShapeHint',['../classtfinfo_1_1v2_1_1_shape_hint.html',1,'tfinfo::ShapeHint'],['../classtfinfo_1_1v2_1_1_shape_hint.html',1,'tfinfo::v2::ShapeHint']]],
  ['shapeinference_36',['ShapeInference',['../structexo_1_1_shape_inference.html',1,'exo::ShapeInference'],['../structloco_1_1_shape_inference.html',1,'loco::ShapeInference']]],
  ['shapeinferencepass_37',['ShapeInferencePass',['../classexo_1_1_shape_inference_pass.html',1,'exo::ShapeInferencePass'],['../classmoco_1_1tf_1_1_shape_inference_pass.html',1,'moco::tf::ShapeInferencePass']]],
  ['shapeinferencerule_38',['ShapeInferenceRule',['../structloco_1_1_shape_inference_rule.html',1,'loco']]],
  ['shapeinferencesession_39',['ShapeInferenceSession',['../classloco_1_1_shape_inference_session.html',1,'loco']]],
  ['shapeiter_40',['ShapeIter',['../classmir_1_1_shape_iter.html',1,'mir']]],
  ['shapekernel_41',['ShapeKernel',['../classluci__interpreter_1_1kernels_1_1_shape_kernel.html',1,'luci_interpreter::kernels']]],
  ['shapelayer_42',['ShapeLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_shape_layer.html',1,'onert::backend::cpu::ops']]],
  ['shapeparams_43',['ShapeParams',['../structluci__interpreter_1_1_shape_params.html',1,'luci_interpreter']]],
  ['shapeprinter_44',['ShapePrinter',['../classcircledump_1_1_shape_printer.html',1,'circledump::ShapePrinter'],['../classtfldump_1_1_shape_printer.html',1,'tfldump::ShapePrinter']]],
  ['shapequery_45',['ShapeQuery',['../class_shape_query.html',1,'']]],
  ['shaperange_46',['ShapeRange',['../classmir_1_1_shape_range.html',1,'mir']]],
  ['shapevalidator_47',['ShapeValidator',['../classonert_1_1compiler_1_1_shape_validator.html',1,'onert::compiler']]],
  ['showaction_48',['ShowAction',['../struct_show_action.html',1,'']]],
  ['shuffle_49',['Shuffle',['../classcoco_1_1_shuffle.html',1,'coco']]],
  ['shuffleweightto16x1float32pass_50',['ShuffleWeightTo16x1Float32Pass',['../structluci_1_1_shuffle_weight_to16x1_float32_pass.html',1,'luci']]],
  ['sigmoidimpl_51',['SigmoidImpl',['../structmir__interpreter_1_1_sigmoid_impl.html',1,'mir_interpreter']]],
  ['sigmoidimpl_3c_20uint8_5ft_20_3e_52',['SigmoidImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_sigmoid_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['sigmoidop_53',['SigmoidOp',['../classmir_1_1ops_1_1_sigmoid_op.html',1,'mir::ops']]],
  ['signal_54',['Signal',['../classnpud_1_1core_1_1_signal.html',1,'npud::core']]],
  ['simplefactoryobjectpool_55',['SimpleFactoryObjectPool',['../structloco_1_1_graph_1_1_simple_factory_object_pool.html',1,'loco::Graph']]],
  ['simplegraph_56',['SimpleGraph',['../class_simple_graph.html',1,'']]],
  ['simplememorymanager_57',['SimpleMemoryManager',['../classluci__interpreter_1_1_simple_memory_manager.html',1,'luci_interpreter']]],
  ['simplemock_58',['SimpleMock',['../classonert__test_1_1ir_1_1_simple_mock.html',1,'onert_test::ir']]],
  ['simplenodetransform_59',['SimpleNodeTransform',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfavgpool_20_3e_60',['SimpleNodeTransform&lt; moco::TFAvgPool &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfbiasadd_20_3e_61',['SimpleNodeTransform&lt; moco::TFBiasAdd &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfconcatv2_20_3e_62',['SimpleNodeTransform&lt; moco::TFConcatV2 &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfconst_20_3e_63',['SimpleNodeTransform&lt; moco::TFConst &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfconv2dbackpropinput_20_3e_64',['SimpleNodeTransform&lt; moco::TFConv2DBackpropInput &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfdepthwiseconv2dnative_20_3e_65',['SimpleNodeTransform&lt; moco::TFDepthwiseConv2dNative &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfidentity_20_3e_66',['SimpleNodeTransform&lt; moco::TFIdentity &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfmaximum_20_3e_67',['SimpleNodeTransform&lt; moco::TFMaximum &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfmaxpool_20_3e_68',['SimpleNodeTransform&lt; moco::TFMaxPool &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfmean_20_3e_69',['SimpleNodeTransform&lt; moco::TFMean &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfmul_20_3e_70',['SimpleNodeTransform&lt; moco::TFMul &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfpad_20_3e_71',['SimpleNodeTransform&lt; moco::TFPad &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfpush_20_3e_72',['SimpleNodeTransform&lt; moco::TFPush &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfrealdiv_20_3e_73',['SimpleNodeTransform&lt; moco::TFRealDiv &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfrelu_20_3e_74',['SimpleNodeTransform&lt; moco::TFRelu &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfrelu6_20_3e_75',['SimpleNodeTransform&lt; moco::TFRelu6 &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfreshape_20_3e_76',['SimpleNodeTransform&lt; moco::TFReshape &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfrsqrt_20_3e_77',['SimpleNodeTransform&lt; moco::TFRsqrt &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfsoftmax_20_3e_78',['SimpleNodeTransform&lt; moco::TFSoftmax &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfsqrt_20_3e_79',['SimpleNodeTransform&lt; moco::TFSqrt &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfsqueeze_20_3e_80',['SimpleNodeTransform&lt; moco::TFSqueeze &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfstopgradient_20_3e_81',['SimpleNodeTransform&lt; moco::TFStopGradient &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atfsub_20_3e_82',['SimpleNodeTransform&lt; moco::TFSub &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20moco_3a_3atftanh_20_3e_83',['SimpleNodeTransform&lt; moco::TFTanh &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20tfadd_20_3e_84',['SimpleNodeTransform&lt; TFAdd &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_20tfconv2d_20_3e_85',['SimpleNodeTransform&lt; TFConv2D &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplenodetransform_3c_3a_3amoco_3a_3atfplaceholder_20_3e_86',['SimpleNodeTransform&lt;::moco::TFPlaceholder &gt;',['../structmoco_1_1tf_1_1_simple_node_transform.html',1,'moco::tf']]],
  ['simplifydomainconversionpass_87',['SimplifyDomainConversionPass',['../structlogo_1_1_simplify_domain_conversion_pass.html',1,'logo']]],
  ['sinchef_88',['SinChef',['../class_sin_chef.html',1,'']]],
  ['sincheffactory_89',['SinChefFactory',['../struct_sin_chef_factory.html',1,'']]],
  ['singlemodelexecutors_90',['SingleModelExecutors',['../classonert_1_1exec_1_1_single_model_executors.html',1,'onert::exec']]],
  ['singleoperatortest_91',['SingleOperatorTest',['../class_single_operator_test_1_1_single_operator_test.html',1,'SingleOperatorTest']]],
  ['singlesampleadapter_92',['SingleSampleAdapter',['../classnnfw_1_1cker_1_1random_1_1_single_sample_adapter.html',1,'nnfw::cker::random']]],
  ['sink_93',['Sink',['../structhermes_1_1_sink.html',1,'hermes::Sink'],['../structloco_1_1_shape_inference_rule_1_1_sink.html',1,'loco::ShapeInferenceRule::Sink']]],
  ['sinkrelu_94',['SinkRelu',['../classnnc_1_1_sink_relu.html',1,'nnc']]],
  ['sinktranspose_95',['SinkTranspose',['../classnnc_1_1_sink_transpose.html',1,'nnc']]],
  ['slice_96',['Slice',['../classluci__interpreter_1_1kernels_1_1_slice.html',1,'luci_interpreter::kernels::Slice'],['../classonert_1_1ir_1_1operation_1_1_slice.html',1,'onert::ir::operation::Slice']]],
  ['slicechef_97',['SliceChef',['../class_slice_chef.html',1,'']]],
  ['slicecheffactory_98',['SliceChefFactory',['../struct_slice_chef_factory.html',1,'']]],
  ['sliceimpl_99',['SliceImpl',['../structmir__interpreter_1_1_slice_impl.html',1,'mir_interpreter']]],
  ['slicelayer_100',['SliceLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_slice_layer.html',1,'onert::backend::cpu::ops']]],
  ['sliceop_101',['SliceOp',['../classmir_1_1ops_1_1_slice_op.html',1,'mir::ops']]],
  ['sliceparams_102',['SliceParams',['../structnnfw_1_1cker_1_1_slice_params.html',1,'nnfw::cker']]],
  ['small_5fvector_103',['small_vector',['../classadt_1_1small__vector.html',1,'adt']]],
  ['small_5fvector_3c_20int32_5ft_2c_20max_5fdimension_5fcount_20_3e_104',['small_vector&lt; int32_t, MAX_DIMENSION_COUNT &gt;',['../classadt_1_1small__vector.html',1,'adt']]],
  ['small_5fvector_3c_20int_5ffast32_5ft_2c_20max_5fdimension_5fcount_20_3e_105',['small_vector&lt; int_fast32_t, MAX_DIMENSION_COUNT &gt;',['../classadt_1_1small__vector.html',1,'adt']]],
  ['snpewriter_106',['SNPEWriter',['../class_s_n_p_e_writer.html',1,'']]],
  ['softmax_107',['Softmax',['../classloco_1_1_softmax.html',1,'loco::Softmax&lt; D &gt;'],['../classluci__interpreter_1_1kernels_1_1_softmax.html',1,'luci_interpreter::kernels::Softmax'],['../classonert_1_1ir_1_1operation_1_1_softmax.html',1,'onert::ir::operation::Softmax']]],
  ['softmax_3c_20domain_3a_3atensor_20_3e_108',['Softmax&lt; Domain::Tensor &gt;',['../classloco_1_1_softmax_3_01_domain_1_1_tensor_01_4.html',1,'loco']]],
  ['softmaxcanonicalizer_109',['SoftmaxCanonicalizer',['../classmoco_1_1tf_1_1_softmax_canonicalizer.html',1,'moco::tf']]],
  ['softmaxchef_110',['SoftmaxChef',['../class_softmax_chef.html',1,'']]],
  ['softmaxcheffactory_111',['SoftmaxChefFactory',['../struct_softmax_chef_factory.html',1,'']]],
  ['softmaxgraphbuilder_112',['SoftmaxGraphBuilder',['../classmoco_1_1_softmax_graph_builder.html',1,'moco']]],
  ['softmaximpl_113',['SoftmaxImpl',['../structmir__interpreter_1_1_softmax_impl.html',1,'mir_interpreter']]],
  ['softmaximpl_3c_20uint8_5ft_20_3e_114',['SoftmaxImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_softmax_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['softmaxlayer_115',['SoftMaxLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_soft_max_layer.html',1,'onert::backend::cpu::ops']]],
  ['softmaxop_116',['SoftmaxOp',['../classmir_1_1ops_1_1_softmax_op.html',1,'mir::ops']]],
  ['softmaxparams_117',['SoftmaxParams',['../structluci__interpreter_1_1_softmax_params.html',1,'luci_interpreter::SoftmaxParams'],['../structnnfw_1_1cker_1_1_softmax_params.html',1,'nnfw::cker::SoftmaxParams']]],
  ['softmaxprinter_118',['SoftmaxPrinter',['../classcircledump_1_1_softmax_printer.html',1,'circledump::SoftmaxPrinter'],['../classtfldump_1_1_softmax_printer.html',1,'tfldump::SoftmaxPrinter']]],
  ['source_119',['Source',['../classhermes_1_1_source.html',1,'hermes::Source'],['../structluci_1_1_circle_node_origin_1_1_source.html',1,'luci::CircleNodeOrigin::Source']]],
  ['sourcesetting_120',['SourceSetting',['../classhermes_1_1_source_setting.html',1,'hermes']]],
  ['sourcetableprinter_121',['SourceTablePrinter',['../classcircledump_1_1_source_table_printer.html',1,'circledump']]],
  ['spacetobatchnd_122',['SpaceToBatchND',['../classluci__interpreter_1_1kernels_1_1_space_to_batch_n_d.html',1,'luci_interpreter::kernels::SpaceToBatchND'],['../classonert_1_1ir_1_1operation_1_1_space_to_batch_n_d.html',1,'onert::ir::operation::SpaceToBatchND']]],
  ['spacetobatchndchef_123',['SpaceToBatchNDChef',['../class_space_to_batch_n_d_chef.html',1,'']]],
  ['spacetobatchndcheffactory_124',['SpaceToBatchNDChefFactory',['../struct_space_to_batch_n_d_chef_factory.html',1,'']]],
  ['spacetobatchndlayer_125',['SpaceToBatchNDLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_space_to_batch_n_d_layer.html',1,'onert::backend::cpu::ops']]],
  ['spacetobatchparams_126',['SpaceToBatchParams',['../structnnfw_1_1cker_1_1_space_to_batch_params.html',1,'nnfw::cker']]],
  ['spacetodepth_127',['SpaceToDepth',['../classluci__interpreter_1_1kernels_1_1_space_to_depth.html',1,'luci_interpreter::kernels::SpaceToDepth'],['../classonert_1_1ir_1_1operation_1_1_space_to_depth.html',1,'onert::ir::operation::SpaceToDepth']]],
  ['spacetodepthchef_128',['SpaceToDepthChef',['../class_space_to_depth_chef.html',1,'']]],
  ['spacetodepthcheffactory_129',['SpaceToDepthChefFactory',['../struct_space_to_depth_chef_factory.html',1,'']]],
  ['spacetodepthlayer_130',['SpaceToDepthLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_space_to_depth_layer.html',1,'onert::backend::cpu::ops']]],
  ['spacetodepthparams_131',['SpaceToDepthParams',['../structluci__interpreter_1_1_space_to_depth_params.html',1,'luci_interpreter::SpaceToDepthParams'],['../structnnfw_1_1cker_1_1_space_to_depth_params.html',1,'nnfw::cker::SpaceToDepthParams']]],
  ['spacetodepthprinter_132',['SpaceToDepthPrinter',['../classcircledump_1_1_space_to_depth_printer.html',1,'circledump::SpaceToDepthPrinter'],['../classtfldump_1_1_space_to_depth_printer.html',1,'tfldump::SpaceToDepthPrinter']]],
  ['span_133',['Span',['../classcoco_1_1_span.html',1,'coco']]],
  ['sparseindexvector_134',['SparseIndexVector',['../classluci_1_1_sparse_index_vector.html',1,'luci']]],
  ['sparsetodensechef_135',['SparseToDenseChef',['../class_sparse_to_dense_chef.html',1,'']]],
  ['sparsetodensecheffactory_136',['SparseToDenseChefFactory',['../struct_sparse_to_dense_chef_factory.html',1,'']]],
  ['sparsetodenseprinter_137',['SparseToDensePrinter',['../classcircledump_1_1_sparse_to_dense_printer.html',1,'circledump::SparseToDensePrinter'],['../classtfldump_1_1_sparse_to_dense_printer.html',1,'tfldump::SparseToDensePrinter']]],
  ['sparsifier_138',['Sparsifier',['../classluci_1_1_sparsifier.html',1,'luci']]],
  ['sparsifytensorpass_139',['SparsifyTensorPass',['../structluci_1_1_sparsify_tensor_pass.html',1,'luci']]],
  ['sparsity_140',['Sparsity',['../structonert_1_1ir_1_1_sparsity.html',1,'onert::ir']]],
  ['sparsityparam_141',['SparsityParam',['../structluci_1_1_sparsity_param.html',1,'luci']]],
  ['spatialpadding_142',['SpatialPadding',['../struct_spatial_padding.html',1,'']]],
  ['spatialpaddingbuilder_143',['SpatialPaddingBuilder',['../class_spatial_padding_builder.html',1,'']]],
  ['spec_144',['Spec',['../structlocop_1_1_spec.html',1,'locop']]],
  ['spec_3c_20interface_3a_3aformatted_20_3e_145',['Spec&lt; Interface::Formatted &gt;',['../structlocop_1_1_spec_3_01_interface_1_1_formatted_01_4.html',1,'locop']]],
  ['split_146',['Split',['../classluci__interpreter_1_1kernels_1_1_split.html',1,'luci_interpreter::kernels::Split'],['../classonert_1_1ir_1_1operation_1_1_split.html',1,'onert::ir::operation::Split']]],
  ['splitchef_147',['SplitChef',['../class_split_chef.html',1,'']]],
  ['splitcheffactory_148',['SplitChefFactory',['../struct_split_chef_factory.html',1,'']]],
  ['splitlayer_149',['SplitLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_split_layer.html',1,'onert::backend::cpu::ops']]],
  ['splitparams_150',['SplitParams',['../structnnfw_1_1cker_1_1_split_params.html',1,'nnfw::cker']]],
  ['splitprinter_151',['SplitPrinter',['../classcircledump_1_1_split_printer.html',1,'circledump::SplitPrinter'],['../classtfldump_1_1_split_printer.html',1,'tfldump::SplitPrinter']]],
  ['splitv_152',['SplitV',['../classluci__interpreter_1_1kernels_1_1_split_v.html',1,'luci_interpreter::kernels::SplitV'],['../classonert_1_1ir_1_1operation_1_1_split_v.html',1,'onert::ir::operation::SplitV']]],
  ['splitvchef_153',['SplitVChef',['../class_split_v_chef.html',1,'']]],
  ['splitvcheffactory_154',['SplitVChefFactory',['../struct_split_v_chef_factory.html',1,'']]],
  ['splitvlayer_155',['SplitVLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_split_v_layer.html',1,'onert::backend::cpu::ops']]],
  ['splitvparams_156',['SplitVParams',['../structnnfw_1_1cker_1_1_split_v_params.html',1,'nnfw::cker']]],
  ['splitvprinter_157',['SplitVPrinter',['../classcircledump_1_1_split_v_printer.html',1,'circledump::SplitVPrinter'],['../classtfldump_1_1_split_v_printer.html',1,'tfldump::SplitVPrinter']]],
  ['sqdifflayer_158',['SqDiffLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_sq_diff_layer.html',1,'onert::backend::cpu::ops']]],
  ['sqrt_159',['Sqrt',['../classcoco_1_1_sqrt.html',1,'coco::Sqrt'],['../classluci__interpreter_1_1kernels_1_1_sqrt.html',1,'luci_interpreter::kernels::Sqrt']]],
  ['sqrtcanonicalizer_160',['SqrtCanonicalizer',['../classmoco_1_1tf_1_1_sqrt_canonicalizer.html',1,'moco::tf']]],
  ['sqrtchef_161',['SqrtChef',['../class_sqrt_chef.html',1,'']]],
  ['sqrtcheffactory_162',['SqrtChefFactory',['../struct_sqrt_chef_factory.html',1,'']]],
  ['sqrtgraphbuilder_163',['SqrtGraphBuilder',['../classmoco_1_1_sqrt_graph_builder.html',1,'moco']]],
  ['sqrtimpl_164',['SqrtImpl',['../structmir__interpreter_1_1_sqrt_impl.html',1,'mir_interpreter']]],
  ['sqrtimpl_3c_20uint8_5ft_20_3e_165',['SqrtImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_sqrt_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['sqrtop_166',['SqrtOp',['../classmir_1_1ops_1_1_sqrt_op.html',1,'mir::ops']]],
  ['square_167',['Square',['../classluci__interpreter_1_1kernels_1_1_square.html',1,'luci_interpreter::kernels']]],
  ['squarechef_168',['SquareChef',['../class_square_chef.html',1,'']]],
  ['squarecheffactory_169',['SquareChefFactory',['../struct_square_chef_factory.html',1,'']]],
  ['squareddifference_170',['SquaredDifference',['../classluci__interpreter_1_1kernels_1_1_squared_difference.html',1,'luci_interpreter::kernels::SquaredDifference'],['../classonert_1_1ir_1_1operation_1_1_squared_difference.html',1,'onert::ir::operation::SquaredDifference']]],
  ['squareddifferencechef_171',['SquaredDifferenceChef',['../class_squared_difference_chef.html',1,'']]],
  ['squareddifferencecheffactory_172',['SquaredDifferenceChefFactory',['../struct_squared_difference_chef_factory.html',1,'']]],
  ['squareddifferencegraphbuilder_173',['SquaredDifferenceGraphBuilder',['../classmoco_1_1_squared_difference_graph_builder.html',1,'moco']]],
  ['squeeze_174',['Squeeze',['../classluci__interpreter_1_1kernels_1_1_squeeze.html',1,'luci_interpreter::kernels::Squeeze'],['../classonert_1_1ir_1_1operation_1_1_squeeze.html',1,'onert::ir::operation::Squeeze']]],
  ['squeezecanonicalizer_175',['SqueezeCanonicalizer',['../classmoco_1_1tf_1_1_squeeze_canonicalizer.html',1,'moco::tf']]],
  ['squeezechef_176',['SqueezeChef',['../class_squeeze_chef.html',1,'']]],
  ['squeezecheffactory_177',['SqueezeChefFactory',['../struct_squeeze_chef_factory.html',1,'']]],
  ['squeezegraphbuilder_178',['SqueezeGraphBuilder',['../classmoco_1_1_squeeze_graph_builder.html',1,'moco']]],
  ['squeezeop_179',['SqueezeOp',['../classmir_1_1ops_1_1_squeeze_op.html',1,'mir::ops']]],
  ['squeezeparams_180',['SqueezeParams',['../structluci__interpreter_1_1_squeeze_params.html',1,'luci_interpreter']]],
  ['squeezeprinter_181',['SqueezePrinter',['../classcircledump_1_1_squeeze_printer.html',1,'circledump::SqueezePrinter'],['../classtfldump_1_1_squeeze_printer.html',1,'tfldump::SqueezePrinter']]],
  ['squeezereducenode_182',['SqueezeReduceNode',['../classmoco_1_1_squeeze_reduce_node.html',1,'moco']]],
  ['stack_183',['Stack',['../class_graph_builder_1_1_stack.html',1,'GraphBuilder']]],
  ['statelessrandomuniform_184',['StatelessRandomUniform',['../classonert_1_1ir_1_1operation_1_1_stateless_random_uniform.html',1,'onert::ir::operation']]],
  ['statelessrandomuniformlayer_185',['StatelessRandomUniformLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_stateless_random_uniform_layer.html',1,'onert::backend::cpu::ops']]],
  ['staticmemorymanager_186',['StaticMemoryManager',['../classluci__interpreter_1_1_static_memory_manager.html',1,'luci_interpreter']]],
  ['staticruntimegraph_187',['StaticRuntimeGraph',['../classluci__interpreter_1_1_static_runtime_graph.html',1,'luci_interpreter']]],
  ['staticshapeinferer_188',['StaticShapeInferer',['../classonert_1_1compiler_1_1_static_shape_inferer.html',1,'onert::compiler']]],
  ['statictensormanager_189',['StaticTensorManager',['../classonert_1_1backend_1_1basic_1_1_static_tensor_manager.html',1,'onert::backend::basic']]],
  ['status_190',['Status',['../classnnkit_1_1support_1_1onnx_1_1_status.html',1,'nnkit::support::onnx']]],
  ['step_191',['Step',['../classcoco_1_1_step.html',1,'coco']]],
  ['stopgradientcanonicalizer_192',['StopGradientCanonicalizer',['../classmoco_1_1tf_1_1_stop_gradient_canonicalizer.html',1,'moco::tf']]],
  ['stopgradientgraphbuilder_193',['StopGradientGraphBuilder',['../classmoco_1_1_stop_gradient_graph_builder.html',1,'moco']]],
  ['stride_194',['Stride',['../classloco_1_1_stride.html',1,'loco::Stride&lt; N &gt;'],['../classlocoex_1_1_stride.html',1,'locoex::Stride'],['../classluci_1_1_stride.html',1,'luci::Stride'],['../structonert_1_1ir_1_1_stride.html',1,'onert::ir::Stride']]],
  ['stride2d_195',['Stride2D',['../classcoco_1_1_stride2_d.html',1,'coco']]],
  ['stride_3c_202_20_3e_196',['Stride&lt; 2 &gt;',['../classloco_1_1_stride_3_012_01_4.html',1,'loco']]],
  ['stridedslice_197',['StridedSlice',['../classluci__interpreter_1_1kernels_1_1_strided_slice.html',1,'luci_interpreter::kernels::StridedSlice'],['../classonert_1_1ir_1_1operation_1_1_strided_slice.html',1,'onert::ir::operation::StridedSlice']]],
  ['stridedslicechef_198',['StridedSliceChef',['../class_strided_slice_chef.html',1,'']]],
  ['stridedslicecheffactory_199',['StridedSliceChefFactory',['../struct_strided_slice_chef_factory.html',1,'']]],
  ['stridedslicegraphbuilder_200',['StridedSliceGraphBuilder',['../classmoco_1_1_strided_slice_graph_builder.html',1,'moco']]],
  ['stridedslicelayer_201',['StridedSliceLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_strided_slice_layer.html',1,'onert::backend::cpu::ops']]],
  ['stridedsliceparams_202',['StridedSliceParams',['../structluci__interpreter_1_1_strided_slice_params.html',1,'luci_interpreter::StridedSliceParams'],['../structnnfw_1_1cker_1_1_strided_slice_params.html',1,'nnfw::cker::StridedSliceParams'],['../structonert_1_1shape__inference_1_1_strided_slice_params.html',1,'onert::shape_inference::StridedSliceParams']]],
  ['stridedsliceprinter_203',['StridedSlicePrinter',['../classcircledump_1_1_strided_slice_printer.html',1,'circledump::StridedSlicePrinter'],['../classtfldump_1_1_strided_slice_printer.html',1,'tfldump::StridedSlicePrinter']]],
  ['stridefunctor_204',['StrideFunctor',['../structnnfw_1_1cker_1_1functor_1_1_stride_functor.html',1,'nnfw::cker::functor']]],
  ['strideinfo_205',['StrideInfo',['../classnnop_1_1_stride_info.html',1,'nnop']]],
  ['strides_206',['Strides',['../structndarray_1_1_strides.html',1,'ndarray']]],
  ['sub_207',['Sub',['../classcoco_1_1_sub.html',1,'coco::Sub'],['../classluci__interpreter_1_1kernels_1_1_sub.html',1,'luci_interpreter::kernels::Sub']]],
  ['subcanonicalizer_208',['SubCanonicalizer',['../classmoco_1_1tf_1_1_sub_canonicalizer.html',1,'moco::tf']]],
  ['subchef_209',['SubChef',['../class_sub_chef.html',1,'']]],
  ['subcheffactory_210',['SubChefFactory',['../struct_sub_chef_factory.html',1,'']]],
  ['subgdurationevent_211',['SubgDurationEvent',['../struct_subg_duration_event.html',1,'']]],
  ['subgevent_212',['SubgEvent',['../struct_event_collector_1_1_subg_event.html',1,'EventCollector']]],
  ['subgraphbuilder_213',['SubGraphBuilder',['../classmoco_1_1_sub_graph_builder.html',1,'moco::SubGraphBuilder'],['../classtflimport_1_1_sub_graph_builder.html',1,'tflimport::SubGraphBuilder']]],
  ['subgraphcontext_214',['SubGraphContext',['../structexo_1_1circle__detail_1_1_sub_graph_context.html',1,'exo::circle_detail::SubGraphContext'],['../structexo_1_1tflite__detail_1_1_sub_graph_context.html',1,'exo::tflite_detail::SubGraphContext'],['../structluci_1_1_sub_graph_context.html',1,'luci::SubGraphContext']]],
  ['subgraphlink_215',['SubGraphLink',['../structtflite2circle_1_1_sub_graph_link.html',1,'tflite2circle']]],
  ['subimpl_216',['SubImpl',['../structmir__interpreter_1_1_sub_impl.html',1,'mir_interpreter']]],
  ['subimpl_3c_20uint8_5ft_20_3e_217',['SubImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_sub_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['subnetblockcompiler_218',['SubnetBlockCompiler',['../classenco_1_1_subnet_block_compiler.html',1,'enco']]],
  ['subnetmanager_219',['SubnetManager',['../structenco_1_1_subnet_manager.html',1,'enco']]],
  ['subnetstruct_220',['SubnetStruct',['../structenco_1_1_subnet_struct.html',1,'enco']]],
  ['subnetstructbuilder_221',['SubnetStructBuilder',['../classenco_1_1_subnet_struct_builder.html',1,'enco']]],
  ['subop_222',['SubOp',['../classmir_1_1ops_1_1_sub_op.html',1,'mir::ops']]],
  ['subparams_223',['SubParams',['../structluci__interpreter_1_1_sub_params.html',1,'luci_interpreter']]],
  ['subprinter_224',['SubPrinter',['../classcircledump_1_1_sub_printer.html',1,'circledump::SubPrinter'],['../classtfldump_1_1_sub_printer.html',1,'tfldump::SubPrinter']]],
  ['subscript_225',['Subscript',['../classnest_1_1expr_1_1_subscript.html',1,'nest::expr']]],
  ['subst_226',['Subst',['../classloco_1_1_subst.html',1,'loco']]],
  ['subst_3c_20substqualifier_3a_3adefault_20_3e_227',['Subst&lt; SubstQualifier::Default &gt;',['../classloco_1_1_subst_3_01_subst_qualifier_1_1_default_01_4.html',1,'loco']]],
  ['substitutepacktoreshapepass_228',['SubstitutePackToReshapePass',['../structluci_1_1_substitute_pack_to_reshape_pass.html',1,'luci']]],
  ['substitutepadv2topadpass_229',['SubstitutePadV2ToPadPass',['../structluci_1_1_substitute_pad_v2_to_pad_pass.html',1,'luci']]],
  ['substitutesplitvtosplitpass_230',['SubstituteSplitVToSplitPass',['../structluci_1_1_substitute_split_v_to_split_pass.html',1,'luci']]],
  ['substitutesqueezetoreshapepass_231',['SubstituteSqueezeToReshapePass',['../structluci_1_1_substitute_squeeze_to_reshape_pass.html',1,'luci']]],
  ['substitutestridedslicetoreshapepass_232',['SubstituteStridedSliceToReshapePass',['../structluci_1_1_substitute_strided_slice_to_reshape_pass.html',1,'luci']]],
  ['substitutetransposetoreshapepass_233',['SubstituteTransposeToReshapePass',['../structluci_1_1_substitute_transpose_to_reshape_pass.html',1,'luci']]],
  ['sumchef_234',['SumChef',['../class_sum_chef.html',1,'']]],
  ['sumcheffactory_235',['SumChefFactory',['../struct_sum_chef_factory.html',1,'']]],
  ['svdf_236',['SVDF',['../classluci__interpreter_1_1kernels_1_1_s_v_d_f.html',1,'luci_interpreter::kernels']]],
  ['svdfchef_237',['SVDFChef',['../class_s_v_d_f_chef.html',1,'']]],
  ['svdfcheffactory_238',['SVDFChefFactory',['../struct_s_v_d_f_chef_factory.html',1,'']]],
  ['svdfparams_239',['SVDFParams',['../structluci__interpreter_1_1_s_v_d_f_params.html',1,'luci_interpreter']]],
  ['svdfprinter_240',['SVDFPrinter',['../classcircledump_1_1_s_v_d_f_printer.html',1,'circledump::SVDFPrinter'],['../classtfldump_1_1_s_v_d_f_printer.html',1,'tfldump::SVDFPrinter']]],
  ['symboltable_241',['SymbolTable',['../structlocop_1_1_symbol_table.html',1,'locop::SymbolTable'],['../classmoco_1_1onnx_1_1_symbol_table.html',1,'moco::onnx::SymbolTable'],['../classmoco_1_1_symbol_table.html',1,'moco::SymbolTable']]]
];
