var searchData=
[
  ['qerrorcomputer_0',['QErrorComputer',['../class_q_error_computer_1_1_q_error_computer.html',1,'QErrorComputer']]],
  ['qimplant_1',['QImplant',['../classq__implant_1_1_q_implant.html',1,'q_implant']]],
  ['quantization_2',['Quantization',['../structonert_1_1ir_1_1_quantization.html',1,'onert::ir']]],
  ['quantize_3',['Quantize',['../classluci__interpreter_1_1kernels_1_1_quantize.html',1,'luci_interpreter::kernels']]],
  ['quantizeactivation_4',['QuantizeActivation',['../structluci_1_1_quantize_activation.html',1,'luci']]],
  ['quantizebias_5',['QuantizeBias',['../structluci_1_1_quantize_bias.html',1,'luci']]],
  ['quantizechef_6',['QuantizeChef',['../class_quantize_chef.html',1,'']]],
  ['quantizecheffactory_7',['QuantizeChefFactory',['../struct_quantize_chef_factory.html',1,'']]],
  ['quantizeconstinputactivation_8',['QuantizeConstInputActivation',['../structluci_1_1_quantize_const_input_activation.html',1,'luci']]],
  ['quantizeddepthwiseconvkernel_9',['QuantizedDepthwiseConvKernel',['../structnnfw_1_1cker_1_1optimized_1_1depthwise__conv_1_1_quantized_depthwise_conv_kernel.html',1,'nnfw::cker::optimized::depthwise_conv::QuantizedDepthwiseConvKernel&lt; kAllowStrided, kFixedInputDepth, kFixedDepthMultiplier &gt;'],['../structnnfw_1_1cker_1_1optimized__integer__ops_1_1depthwise__conv_1_1_quantized_depthwise_conv_kernel.html',1,'nnfw::cker::optimized_integer_ops::depthwise_conv::QuantizedDepthwiseConvKernel&lt; kAllowStrided, kFixedInputDepth, kFixedDepthMultiplier &gt;']]],
  ['quantizedequantizeweightspass_10',['QuantizeDequantizeWeightsPass',['../classluci_1_1_quantize_dequantize_weights_pass.html',1,'luci']]],
  ['quantizedmodelverifier_11',['QuantizedModelVerifier',['../structluci_1_1_quantized_model_verifier.html',1,'luci']]],
  ['quantizelayer_12',['QuantizeLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_quantize_layer.html',1,'onert::backend::cpu::ops']]],
  ['quantizemanager_13',['QuantizeManager',['../classonert_1_1odc_1_1_quantize_manager.html',1,'onert::odc']]],
  ['quantizeop_14',['QuantizeOp',['../classmir_1_1ops_1_1_quantize_op.html',1,'mir::ops']]],
  ['quantizeprecheckerpass_15',['QuantizePreCheckerPass',['../classluci_1_1_quantize_pre_checker_pass.html',1,'luci']]],
  ['quantizer_16',['Quantizer',['../classmpqsolver_1_1core_1_1_quantizer.html',1,'mpqsolver::core::Quantizer'],['../classonert_1_1odc_1_1_quantizer.html',1,'onert::odc::Quantizer']]],
  ['quantizerhook_17',['QuantizerHook',['../structmpqsolver_1_1core_1_1_quantizer_hook.html',1,'mpqsolver::core']]],
  ['quantizerloader_18',['QuantizerLoader',['../classonert_1_1odc_1_1_quantizer_loader.html',1,'onert::odc']]],
  ['quantizespecialactivation_19',['QuantizeSpecialActivation',['../structluci_1_1_quantize_special_activation.html',1,'luci']]],
  ['quantizeweights_20',['QuantizeWeights',['../structluci_1_1_quantize_weights.html',1,'luci']]],
  ['quantizeweightsonly_21',['QuantizeWeightsOnly',['../structluci_1_1_quantize_weights_only.html',1,'luci']]],
  ['quantizeweightspass_22',['QuantizeWeightsPass',['../classluci_1_1_quantize_weights_pass.html',1,'luci']]],
  ['quantizewithminmaxpass_23',['QuantizeWithMinMaxPass',['../classluci_1_1_quantize_with_min_max_pass.html',1,'luci']]]
];
