var searchData=
[
  ['object_0',['object',['../classflexbuffers_1_1_object.html',1,'flexbuffers::Object'],['../classcoco_1_1_object.html',1,'coco::Object'],['../classnnfw_1_1misc_1_1vector_1_1_object.html',1,'nnfw::misc::vector::Object&lt; T &gt;'],['../classnnfw_1_1misc_1_1feature_1_1_object.html',1,'nnfw::misc::feature::Object&lt; T &gt;'],['../classnnfw_1_1misc_1_1tensor_1_1_object.html',1,'nnfw::misc::tensor::Object&lt; T &gt;']]],
  ['objectmanager_1',['objectmanager',['../classonert_1_1util_1_1_object_manager.html',1,'onert::util::ObjectManager&lt; Index, Object &gt;'],['../classcoco_1_1_object_manager.html',1,'coco::ObjectManager']]],
  ['objectmanager_3c_20onert_3a_3autil_3a_3aindex_2c_20onert_3a_3acompiler_3a_3aoperandlowerinfo_20_3e_2',['ObjectManager&lt; onert::util::Index, onert::compiler::OperandLowerInfo &gt;',['../classonert_1_1util_1_1_object_manager.html',1,'onert::util']]],
  ['objectmanager_3c_20operandindex_2c_20operand_20_3e_3',['ObjectManager&lt; OperandIndex, Operand &gt;',['../classonert_1_1util_1_1_object_manager.html',1,'onert::util']]],
  ['objectmanager_3c_20operationindex_2c_20ioperation_20_3e_4',['ObjectManager&lt; OperationIndex, IOperation &gt;',['../classonert_1_1util_1_1_object_manager.html',1,'onert::util']]],
  ['objectpool_5',['ObjectPool',['../classloco_1_1_object_pool.html',1,'loco']]],
  ['objectpool_3c_20graphinput_20_3e_6',['ObjectPool&lt; GraphInput &gt;',['../classloco_1_1_object_pool.html',1,'loco']]],
  ['objectpool_3c_20graphoutput_20_3e_7',['ObjectPool&lt; GraphOutput &gt;',['../classloco_1_1_object_pool.html',1,'loco']]],
  ['objectpool_3c_20node_20_3e_8',['ObjectPool&lt; Node &gt;',['../classloco_1_1_object_pool.html',1,'loco']]],
  ['observer_9',['Observer',['../structnnfw_1_1misc_1_1tensor_1_1_comparator_1_1_observer.html',1,'nnfw::misc::tensor::Comparator']]],
  ['oddoutputpass_10',['OddOutputPass',['../classonert_1_1compiler_1_1pass_1_1_odd_output_pass.html',1,'onert::compiler::pass']]],
  ['offset_11',['offset',['../structflatbuffers_1_1_offset.html',1,'flatbuffers::Offset&lt; T &gt;'],['../classtflite2circle_1_1_offset.html',1,'tflite2circle::Offset&lt; T &gt;']]],
  ['offset_3c_20circle_3a_3abuffer_20_3e_12',['Offset&lt; circle::Buffer &gt;',['../structflatbuffers_1_1_offset.html',1,'flatbuffers']]],
  ['offset_3c_20flatbuffers_3a_3astring_20_3e_13',['Offset&lt; flatbuffers::String &gt;',['../structflatbuffers_1_1_offset.html',1,'flatbuffers']]],
  ['offset_3c_20flatbuffers_3a_3avector_3c_20typename_20t_3a_3acir_20_3e_20_3e_14',['Offset&lt; flatbuffers::Vector&lt; typename T::CIR &gt; &gt;',['../structflatbuffers_1_1_offset.html',1,'flatbuffers']]],
  ['offset_3c_20void_20_3e_15',['Offset&lt; void &gt;',['../structflatbuffers_1_1_offset.html',1,'flatbuffers']]],
  ['omaxiscontextmixin_16',['OMAxisContextMixin',['../classonert__micro_1_1core_1_1_o_m_axis_context_mixin.html',1,'onert_micro::core']]],
  ['ombackpropexecute_17',['OMBackpropExecute',['../structonert__micro_1_1train_1_1_o_m_backprop_execute.html',1,'onert_micro::train']]],
  ['ombackpropexecuteargs_18',['OMBackpropExecuteArgs',['../structonert__micro_1_1train_1_1_o_m_backprop_execute_args.html',1,'onert_micro::train']]],
  ['ombasecontext_19',['OMBaseContext',['../classonert__micro_1_1core_1_1_o_m_base_context.html',1,'onert_micro::core']]],
  ['omcheckpointloader_20',['OMCheckpointLoader',['../classonert__micro_1_1core_1_1train_1_1_o_m_checkpoint_loader.html',1,'onert_micro::core::train']]],
  ['omcheckpointsaver_21',['OMCheckpointSaver',['../classonert__micro_1_1core_1_1train_1_1_o_m_checkpoint_saver.html',1,'onert_micro::core::train']]],
  ['omcirclereader_22',['OMCircleReader',['../classonert__micro_1_1core_1_1reader_1_1_o_m_circle_reader.html',1,'onert_micro::core::reader']]],
  ['omconfig_23',['OMConfig',['../structonert__micro_1_1_o_m_config.html',1,'onert_micro']]],
  ['omconfigureargs_24',['OMConfigureArgs',['../structonert__micro_1_1import_1_1_o_m_configure_args.html',1,'onert_micro::import']]],
  ['omdatacontext_25',['OMDataContext',['../classonert__micro_1_1core_1_1_o_m_data_context.html',1,'onert_micro::core']]],
  ['omdatacontext_3c_20t_2c_20omaxiscontextmixin_3c_201_20_3e_20_3e_26',['OMDataContext&lt; T, OMAxisContextMixin&lt; 1 &gt; &gt;',['../classonert__micro_1_1core_1_1_o_m_data_context.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_27',['OMDataTypeImpl',['../structonert__micro_1_1core_1_1_o_m_data_type_impl.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3abool_20_3e_28',['OMDataTypeImpl&lt; OMDataType::BOOL &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_b_o_o_l_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3afloat16_20_3e_29',['OMDataTypeImpl&lt; OMDataType::FLOAT16 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_f_l_o_a_t16_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3afloat32_20_3e_30',['OMDataTypeImpl&lt; OMDataType::FLOAT32 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_f_l_o_a_t32_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3afloat64_20_3e_31',['OMDataTypeImpl&lt; OMDataType::FLOAT64 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_f_l_o_a_t64_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3as16_20_3e_32',['OMDataTypeImpl&lt; OMDataType::S16 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_s16_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3as32_20_3e_33',['OMDataTypeImpl&lt; OMDataType::S32 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_s32_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3as64_20_3e_34',['OMDataTypeImpl&lt; OMDataType::S64 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_s64_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3as8_20_3e_35',['OMDataTypeImpl&lt; OMDataType::S8 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_s8_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3au16_20_3e_36',['OMDataTypeImpl&lt; OMDataType::U16 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_u16_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3au32_20_3e_37',['OMDataTypeImpl&lt; OMDataType::U32 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_u32_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3au64_20_3e_38',['OMDataTypeImpl&lt; OMDataType::U64 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_u64_01_4.html',1,'onert_micro::core']]],
  ['omdatatypeimpl_3c_20omdatatype_3a_3au8_20_3e_39',['OMDataTypeImpl&lt; OMDataType::U8 &gt;',['../structonert__micro_1_1core_1_1_o_m_data_type_impl_3_01_o_m_data_type_1_1_u8_01_4.html',1,'onert_micro::core']]],
  ['omdynamicshapeshandler_40',['OMDynamicShapesHandler',['../structonert__micro_1_1import_1_1_o_m_dynamic_shapes_handler.html',1,'onert_micro::import']]],
  ['omexecuteargs_41',['OMExecuteArgs',['../structonert__micro_1_1execute_1_1_o_m_execute_args.html',1,'onert_micro::execute']]],
  ['omexecutionplancreator_42',['OMExecutionPlanCreator',['../structonert__micro_1_1import_1_1_o_m_execution_plan_creator.html',1,'onert_micro::import']]],
  ['omgraphstatus_43',['OMGraphStatus',['../structonert__micro_1_1optimize_1_1_o_m_graph_status.html',1,'onert_micro::optimize']]],
  ['ominputcontext_44',['OMInputContext',['../classonert__micro_1_1core_1_1_o_m_input_context.html',1,'onert_micro::core']]],
  ['ominputcontext_3c_20int32_5ft_2c_201_20_3e_45',['OMInputContext&lt; int32_t, 1 &gt;',['../classonert__micro_1_1core_1_1_o_m_input_context.html',1,'onert_micro::core']]],
  ['ominterpreter_46',['OMInterpreter',['../classonert__micro_1_1_o_m_interpreter.html',1,'onert_micro']]],
  ['omkernelconfiguration_47',['OMKernelConfiguration',['../structonert__micro_1_1import_1_1_o_m_kernel_configuration.html',1,'onert_micro::import']]],
  ['omkernelexecute_48',['OMKernelExecute',['../structonert__micro_1_1execute_1_1_o_m_kernel_execute.html',1,'onert_micro::execute']]],
  ['ommemorymanager_49',['OMMemoryManager',['../structonert__micro_1_1core_1_1memory_1_1_o_m_memory_manager.html',1,'onert_micro::core::memory']]],
  ['omoptimizer_50',['OMOptimizer',['../structonert__micro_1_1optimize_1_1_o_m_optimizer.html',1,'onert_micro::optimize']]],
  ['omoutputcontext_51',['OMOutputContext',['../classonert__micro_1_1core_1_1_o_m_output_context.html',1,'onert_micro::core']]],
  ['omquantizationdata_52',['OMQuantizationData',['../classonert__micro_1_1core_1_1_o_m_quantization_data.html',1,'onert_micro::core']]],
  ['omreducedatacontext_53',['OMReduceDataContext',['../classonert__micro_1_1core_1_1_o_m_reduce_data_context.html',1,'onert_micro::core']]],
  ['omruntimeallocator_54',['OMRuntimeAllocator',['../classonert__micro_1_1core_1_1memory_1_1_o_m_runtime_allocator.html',1,'onert_micro::core::memory']]],
  ['omruntimecontext_55',['OMRuntimeContext',['../classonert__micro_1_1core_1_1_o_m_runtime_context.html',1,'onert_micro::core']]],
  ['omruntimegraph_56',['OMRuntimeGraph',['../classonert__micro_1_1core_1_1_o_m_runtime_graph.html',1,'onert_micro::core']]],
  ['omruntimekernel_57',['OMRuntimeKernel',['../classonert__micro_1_1execute_1_1_o_m_runtime_kernel.html',1,'onert_micro::execute']]],
  ['omruntimemodule_58',['OMRuntimeModule',['../classonert__micro_1_1core_1_1_o_m_runtime_module.html',1,'onert_micro::core']]],
  ['omruntimeshape_59',['OMRuntimeShape',['../classonert__micro_1_1core_1_1_o_m_runtime_shape.html',1,'onert_micro::core']]],
  ['omruntimestorage_60',['OMRuntimeStorage',['../classonert__micro_1_1core_1_1_o_m_runtime_storage.html',1,'onert_micro::core']]],
  ['omtensordata_61',['OMTensorData',['../classonert__micro_1_1core_1_1_o_m_tensor_data.html',1,'onert_micro::core']]],
  ['omtensordata_3c_20const_20int32_5ft_20_3e_62',['OMTensorData&lt; const int32_t &gt;',['../classonert__micro_1_1core_1_1_o_m_tensor_data.html',1,'onert_micro::core']]],
  ['omtensordata_3c_20const_20t_20_3e_63',['OMTensorData&lt; const T &gt;',['../classonert__micro_1_1core_1_1_o_m_tensor_data.html',1,'onert_micro::core']]],
  ['omtrainingconfigreader_64',['OMTrainingConfigReader',['../classonert__micro_1_1core_1_1reader_1_1_o_m_training_config_reader.html',1,'onert_micro::core::reader']]],
  ['omtrainingcontext_65',['OMTrainingContext',['../structonert__micro_1_1_o_m_training_context.html',1,'onert_micro']]],
  ['omtraininghandler_66',['OMTrainingHandler',['../classonert__micro_1_1core_1_1train_1_1_o_m_training_handler.html',1,'onert_micro::core::train']]],
  ['omtraininginterpreter_67',['OMTrainingInterpreter',['../classonert__micro_1_1_o_m_training_interpreter.html',1,'onert_micro']]],
  ['omtrainingruntimemodule_68',['OMTrainingRuntimeModule',['../classonert__micro_1_1core_1_1_o_m_training_runtime_module.html',1,'onert_micro::core']]],
  ['omtrainingstorage_69',['OMTrainingStorage',['../classonert__micro_1_1core_1_1train_1_1_o_m_training_storage.html',1,'onert_micro::core::train']]],
  ['omweightonlyformatreader_70',['OMWeightOnlyFormatReader',['../classonert__micro_1_1core_1_1reader_1_1_o_m_weight_only_format_reader.html',1,'onert_micro::core::reader']]],
  ['onehot_71',['onehot',['../classluci__interpreter_1_1kernels_1_1_one_hot.html',1,'luci_interpreter::kernels::OneHot'],['../classonert_1_1ir_1_1operation_1_1_one_hot.html',1,'onert::ir::operation::OneHot']]],
  ['onehotchef_72',['OneHotChef',['../class_one_hot_chef.html',1,'']]],
  ['onehotcheffactory_73',['OneHotChefFactory',['../struct_one_hot_chef_factory.html',1,'']]],
  ['onehotlayer_74',['OneHotLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_one_hot_layer.html',1,'onert::backend::cpu::ops']]],
  ['onehotparams_75',['OneHotParams',['../structluci__interpreter_1_1_one_hot_params.html',1,'luci_interpreter']]],
  ['onehotprinter_76',['onehotprinter',['../classcircledump_1_1_one_hot_printer.html',1,'circledump::OneHotPrinter'],['../classtfldump_1_1_one_hot_printer.html',1,'tfldump::OneHotPrinter']]],
  ['onertexception_77',['OnertException',['../classonert_1_1_onert_exception.html',1,'onert']]],
  ['onnxrunner_78',['OnnxRunner',['../classvalidate__onnx2circle_1_1_onnx_runner.html',1,'validate_onnx2circle']]],
  ['op_79',['Op',['../structcoco_1_1_op.html',1,'coco']]],
  ['opbuilder_80',['OpBuilder',['../class_op_builder.html',1,'']]],
  ['opchef_81',['OpChef',['../struct_op_chef.html',1,'']]],
  ['opcheffactory_82',['OpChefFactory',['../struct_op_chef_factory.html',1,'']]],
  ['opcode_83',['opcode',['../structexo_1_1circle__detail_1_1_op_code.html',1,'exo::circle_detail::OpCode'],['../structexo_1_1tflite__detail_1_1_op_code.html',1,'exo::tflite_detail::OpCode'],['../structluci_1_1_op_code.html',1,'luci::OpCode']]],
  ['operand_84',['operand',['../classonert_1_1ir_1_1_operand.html',1,'onert::ir::Operand'],['../struct_operand.html',1,'Operand'],['../classonert_1_1dumper_1_1dot_1_1_operand.html',1,'onert::dumper::dot::Operand'],['../classann_1_1_operand.html',1,'ann::Operand']]],
  ['operandconstraint_85',['OperandConstraint',['../classonert_1_1ir_1_1_operand_constraint.html',1,'onert::ir']]],
  ['operandid_86',['OperandID',['../classann_1_1_operand_i_d.html',1,'ann']]],
  ['operandindexsequence_87',['OperandIndexSequence',['../classonert_1_1ir_1_1_operand_index_sequence.html',1,'onert::ir']]],
  ['operandinfo_88',['OperandInfo',['../classonert_1_1ir_1_1_operand_info.html',1,'onert::ir']]],
  ['operandinventory_89',['OperandInventory',['../classann_1_1_operand_inventory.html',1,'ann']]],
  ['operandlowerinfo_90',['OperandLowerInfo',['../classonert_1_1compiler_1_1_operand_lower_info.html',1,'onert::compiler']]],
  ['operandobserver_91',['OperandObserver',['../classonert_1_1compiler_1_1_operand_observer.html',1,'onert::compiler']]],
  ['operandpass_92',['OperandPass',['../classonert_1_1compiler_1_1pass_1_1_operand_pass.html',1,'onert::compiler::pass']]],
  ['operands_93',['Operands',['../classonert_1_1ir_1_1_operands.html',1,'onert::ir']]],
  ['operation_94',['operation',['../classann_1_1_operation.html',1,'ann::Operation'],['../classkbenchmark_1_1_operation.html',1,'kbenchmark::Operation'],['../classmir_1_1_operation.html',1,'mir::Operation'],['../classonert_1_1dumper_1_1dot_1_1_operation.html',1,'onert::dumper::dot::Operation'],['../classonert_1_1ir_1_1_operation.html',1,'onert::ir::Operation'],['../struct_operation.html',1,'Operation']]],
  ['operationdumper_95',['OperationDumper',['../classonert_1_1ir_1_1_operation_dumper.html',1,'onert::ir']]],
  ['operationexporterrule_96',['OperationExporterRule',['../classluci_1_1_operation_exporter_rule.html',1,'luci']]],
  ['operationindexset_97',['OperationIndexSet',['../classonert_1_1ir_1_1_operation_index_set.html',1,'onert::ir']]],
  ['operationinventory_98',['OperationInventory',['../classann_1_1_operation_inventory.html',1,'ann']]],
  ['operationloader_99',['OperationLoader',['../classkbenchmark_1_1_operation_loader.html',1,'kbenchmark']]],
  ['operationpass_100',['OperationPass',['../classonert_1_1compiler_1_1pass_1_1_operation_pass.html',1,'onert::compiler::pass']]],
  ['operations_101',['Operations',['../classonert_1_1ir_1_1_operations.html',1,'onert::ir']]],
  ['operationvalidator_102',['OperationValidator',['../classonert_1_1ir_1_1_operation_validator.html',1,'onert::ir']]],
  ['operationvisitor_103',['OperationVisitor',['../structonert_1_1ir_1_1_operation_visitor.html',1,'onert::ir']]],
  ['operatorcodelink_104',['OperatorCodeLink',['../structtflite2circle_1_1_operator_code_link.html',1,'tflite2circle']]],
  ['opmanager_105',['OpManager',['../classcoco_1_1_op_manager.html',1,'coco']]],
  ['opminmaxhash_106',['OpMinMaxHash',['../structonert_1_1exec_1_1_op_min_max_hash.html',1,'onert::exec']]],
  ['opprinter_107',['opprinter',['../classcircledump_1_1_op_printer.html',1,'circledump::OpPrinter'],['../classtfldump_1_1_op_printer.html',1,'tfldump::OpPrinter'],['../struct_op_printer.html',1,'OpPrinter']]],
  ['opprinterregistry_108',['opprinterregistry',['../classcircledump_1_1_op_printer_registry.html',1,'circledump::OpPrinterRegistry'],['../classtfldump_1_1_op_printer_registry.html',1,'tfldump::OpPrinterRegistry']]],
  ['opselector_109',['OpSelector',['../classopselector_1_1_op_selector.html',1,'opselector']]],
  ['opseqdurationevent_110',['OpSeqDurationEvent',['../struct_op_seq_duration_event.html',1,'']]],
  ['opseqevent_111',['OpSeqEvent',['../struct_event_collector_1_1_op_seq_event.html',1,'EventCollector']]],
  ['optableprinter_112',['OpTablePrinter',['../classcircledump_1_1_op_table_printer.html',1,'circledump']]],
  ['optimizepassregistry_113',['OptimizePassRegistry',['../classonert__micro_1_1optimize_1_1_optimize_pass_registry.html',1,'onert_micro::optimize']]],
  ['optimizer_114',['optimizer',['../classonert_1_1exec_1_1train_1_1optimizer_1_1_optimizer.html',1,'onert::exec::train::optimizer::Optimizer'],['../classpackage_1_1experimental_1_1train_1_1optimizer_1_1optimizer_1_1_optimizer.html',1,'package.experimental.train.optimizer.optimizer.Optimizer'],['../classonert_1_1backend_1_1acl__neon_1_1_optimizer.html',1,'onert::backend::acl_neon::Optimizer'],['../classonert_1_1backend_1_1acl__cl_1_1_optimizer.html',1,'onert::backend::acl_cl::Optimizer'],['../classmoco_1_1tf_1_1_optimizer.html',1,'moco::tf::Optimizer']]],
  ['optimizerinfo_115',['OptimizerInfo',['../structonert_1_1ir_1_1train_1_1_optimizer_info.html',1,'onert::ir::train']]],
  ['optimizerregistry_116',['OptimizerRegistry',['../classpackage_1_1experimental_1_1train_1_1optimizer_1_1registry_1_1_optimizer_registry.html',1,'package::experimental::train::optimizer::registry']]],
  ['option_117',['option',['../classargumentparse_1_1_option.html',1,'argumentparse.Option'],['../classnnc_1_1cli_1_1_option.html',1,'nnc::cli::Option&lt; T &gt;']]],
  ['optional_118',['Optional',['../classargumentparse_1_1_optional.html',1,'argumentparse']]],
  ['optionbuilder_119',['OptionBuilder',['../class_option_builder_1_1_option_builder.html',1,'OptionBuilder']]],
  ['options_120',['options',['../structluci_1_1_circle_optimizer_1_1_options.html',1,'luci::CircleOptimizer::Options'],['../structluci_1_1_circle_quantizer_1_1_options.html',1,'luci::CircleQuantizer::Options']]],
  ['optiontype_121',['OptionType',['../classnnc_1_1cli_1_1_option_type.html',1,'nnc::cli']]],
  ['optiontype_3c_20t_2c_20false_20_3e_122',['OptionType&lt; T, false &gt;',['../classnnc_1_1cli_1_1_option_type_3_01_t_00_01false_01_4.html',1,'nnc::cli']]],
  ['optiontype_3c_20t_2c_20std_3a_3ais_5fclass_3c_20t_20_3e_3a_3avalue_20_3e_123',['OptionType&lt; T, std::is_class&lt; T &gt;::value &gt;',['../classnnc_1_1cli_1_1_option_type.html',1,'nnc::cli']]],
  ['optiontype_3c_20t_2c_20true_20_3e_124',['OptionType&lt; T, true &gt;',['../classnnc_1_1cli_1_1_option_type_3_01_t_00_01true_01_4.html',1,'nnc::cli']]],
  ['output_125',['output',['../classcoco_1_1_output.html',1,'coco::Output'],['../classmir_1_1_operation_1_1_output.html',1,'mir::Operation::Output']]],
  ['outputblobcontext_126',['OutputBlobContext',['../classnnkit_1_1support_1_1caffe_1_1_output_blob_context.html',1,'nnkit::support::caffe']]],
  ['outputcontext_127',['OutputContext',['../structloco_1_1_graph_1_1_output_context.html',1,'loco::Graph']]],
  ['outputdesc_128',['OutputDesc',['../structonert_1_1exec_1_1_output_desc.html',1,'onert::exec']]],
  ['outputlayer_129',['OutputLayer',['../struct_output_layer.html',1,'']]],
  ['outputmanager_130',['OutputManager',['../classcoco_1_1_output_manager.html',1,'coco']]],
  ['outputop_131',['OutputOp',['../classmir_1_1ops_1_1_output_op.html',1,'mir::ops']]],
  ['outputtensorcontext_132',['OutputTensorContext',['../classnnkit_1_1support_1_1moco_1_1tf_1_1_output_tensor_context.html',1,'nnkit::support::moco::tf']]],
  ['outputtensorset_133',['OutputTensorSet',['../classnnkit_1_1support_1_1tflite_1_1_output_tensor_set.html',1,'nnkit::support::tflite']]],
  ['overlay_134',['overlay',['../classnncc_1_1core_1_1_a_d_t_1_1feature_1_1_overlay.html',1,'nncc::core::ADT::feature::Overlay&lt; T &gt;'],['../classnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_overlay.html',1,'nncc::core::ADT::kernel::Overlay&lt; T, InputIt &gt;'],['../classnncc_1_1core_1_1_a_d_t_1_1tensor_1_1_overlay.html',1,'nncc::core::ADT::tensor::Overlay&lt; T &gt;']]],
  ['overlayfactory_135',['OverlayFactory',['../structnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_overlay_factory.html',1,'nncc::core::ADT::kernel']]]
];
