var searchData=
[
  ['name_0',['Name',['../classenco_1_1_pass_1_1_name.html',1,'enco::Pass']]],
  ['namedentity_1',['NamedEntity',['../classloco_1_1_named_entity.html',1,'loco']]],
  ['namedhashfunction_2',['NamedHashFunction',['../structflatbuffers_1_1_named_hash_function.html',1,'flatbuffers']]],
  ['namespace_3',['Namespace',['../structflatbuffers_1_1_namespace.html',1,'flatbuffers']]],
  ['nchw_4',['NCHW',['../classcoco_1_1_kernel_layouts_1_1_n_c_h_w.html',1,'coco::KernelLayouts']]],
  ['nchwlayout_5',['NCHWLayout',['../structnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_n_c_h_w_layout.html',1,'nncc::core::ADT::kernel']]],
  ['ndarraydesc_6',['NdArrayDesc',['../structluci__interpreter__pal_1_1_nd_array_desc.html',1,'luci_interpreter_pal::NdArrayDesc&lt; N &gt;'],['../struct_nd_array_desc.html',1,'NdArrayDesc&lt; N &gt;'],['../structnnfw_1_1cker_1_1_nd_array_desc.html',1,'nnfw::cker::NdArrayDesc&lt; N &gt;']]],
  ['nebinarylogicaloperation_7',['NEBinaryLogicalOperation',['../classarm__compute_1_1_n_e_binary_logical_operation.html',1,'arm_compute']]],
  ['nebinarylogicaloperationkernel_8',['NEBinaryLogicalOperationKernel',['../classarm__compute_1_1_n_e_binary_logical_operation_kernel.html',1,'arm_compute']]],
  ['nebinarylogicaloperationstatic_9',['NEBinaryLogicalOperationStatic',['../classarm__compute_1_1_n_e_binary_logical_operation_static.html',1,'arm_compute']]],
  ['necastbool_10',['NECastBool',['../classarm__compute_1_1_n_e_cast_bool.html',1,'arm_compute']]],
  ['necastboolkernel_11',['NECastBoolKernel',['../classarm__compute_1_1_n_e_cast_bool_kernel.html',1,'arm_compute']]],
  ['neembeddinglookup_12',['NEEmbeddingLookup',['../classarm__compute_1_1_n_e_embedding_lookup.html',1,'arm_compute']]],
  ['neembeddinglookupkernel_13',['NEEmbeddingLookupKernel',['../classarm__compute_1_1_n_e_embedding_lookup_kernel.html',1,'arm_compute']]],
  ['nefullyconnectedhybridlayer_14',['NEFullyConnectedHybridLayer',['../classarm__compute_1_1_n_e_fully_connected_hybrid_layer.html',1,'arm_compute']]],
  ['nefullyconnectedhybridlayerreshapeweights_15',['NEFullyConnectedHybridLayerReshapeWeights',['../classarm__compute_1_1_n_e_fully_connected_hybrid_layer_reshape_weights.html',1,'arm_compute']]],
  ['nefullyconnectedlayerex_16',['NEFullyConnectedLayerEx',['../classarm__compute_1_1_n_e_fully_connected_layer_ex.html',1,'arm_compute']]],
  ['nefullyconnectedreshapinglayer_17',['NEFullyConnectedReshapingLayer',['../classarm__compute_1_1_n_e_fully_connected_reshaping_layer.html',1,'arm_compute']]],
  ['neg_18',['Neg',['../classluci__interpreter_1_1kernels_1_1_neg.html',1,'luci_interpreter::kernels']]],
  ['negatherex_19',['NEGatherEx',['../classarm__compute_1_1_n_e_gather_ex.html',1,'arm_compute']]],
  ['negatherkernelex_20',['NEGatherKernelEx',['../classarm__compute_1_1_n_e_gather_kernel_ex.html',1,'arm_compute']]],
  ['negchef_21',['NegChef',['../class_neg_chef.html',1,'']]],
  ['negcheffactory_22',['NegChefFactory',['../struct_neg_chef_factory.html',1,'']]],
  ['negemmmatrixaccumulatebiaseskernel_23',['NEGEMMMatrixAccumulateBiasesKernel',['../classarm__compute_1_1_n_e_g_e_m_m_matrix_accumulate_biases_kernel.html',1,'arm_compute']]],
  ['nehashtablelookup_24',['NEHashtableLookup',['../classarm__compute_1_1_n_e_hashtable_lookup.html',1,'arm_compute']]],
  ['nehashtablelookupkernel_25',['NEHashtableLookupKernel',['../classarm__compute_1_1_n_e_hashtable_lookup_kernel.html',1,'arm_compute']]],
  ['neinstancenormalizationlayerex_26',['NEInstanceNormalizationLayerEx',['../classarm__compute_1_1_n_e_instance_normalization_layer_ex.html',1,'arm_compute']]],
  ['neinstancenormalizationlayerkernelex_27',['NEInstanceNormalizationLayerKernelEx',['../classarm__compute_1_1_n_e_instance_normalization_layer_kernel_ex.html',1,'arm_compute']]],
  ['nemultiplyscalefactorkernel_28',['NEMultiplyScaleFactorKernel',['../classarm__compute_1_1_n_e_multiply_scale_factor_kernel.html',1,'arm_compute']]],
  ['neonehot_29',['NEOneHot',['../classarm__compute_1_1_n_e_one_hot.html',1,'arm_compute']]],
  ['neonehotkernel_30',['NEOneHotKernel',['../classarm__compute_1_1_n_e_one_hot_kernel.html',1,'arm_compute']]],
  ['nequantizationsymmetrickernel_31',['NEQuantizationSymmetricKernel',['../classarm__compute_1_1_n_e_quantization_symmetric_kernel.html',1,'arm_compute']]],
  ['nereduceoperation_32',['NEReduceOperation',['../classarm__compute_1_1_n_e_reduce_operation.html',1,'arm_compute']]],
  ['nereducesum_33',['NEReduceSum',['../classarm__compute_1_1_n_e_reduce_sum.html',1,'arm_compute']]],
  ['nesubtensor_34',['NESubTensor',['../classonert_1_1backend_1_1acl__neon_1_1operand_1_1_n_e_sub_tensor.html',1,'onert::backend::acl_neon::operand']]],
  ['netensor_35',['NETensor',['../classonert_1_1backend_1_1acl__neon_1_1operand_1_1_n_e_tensor.html',1,'onert::backend::acl_neon::operand']]],
  ['netransposeconvlayer_36',['NETransposeConvLayer',['../classarm__compute_1_1_n_e_transpose_conv_layer.html',1,'arm_compute']]],
  ['nhwc_37',['NHWC',['../classcoco_1_1_kernel_layouts_1_1_n_h_w_c.html',1,'coco::KernelLayouts']]],
  ['nhwclayout_38',['NHWCLayout',['../structnncc_1_1core_1_1_a_d_t_1_1kernel_1_1_n_h_w_c_layout.html',1,'nncc::core::ADT::kernel']]],
  ['nnapiconvert_39',['NNAPIConvert',['../class_n_n_a_p_i_convert.html',1,'']]],
  ['nnfw_5fcustom_5fkernel_5fparams_40',['nnfw_custom_kernel_params',['../structnnfw__custom__kernel__params.html',1,'']]],
  ['nnfw_5foperand_41',['nnfw_operand',['../structnnfw__operand.html',1,'']]],
  ['nnfw_5fsession_42',['nnfw_session',['../structnnfw__session.html',1,'']]],
  ['nnfw_5ftensorinfo_43',['nnfw_tensorinfo',['../structnnfw__tensorinfo.html',1,'']]],
  ['nnpkg_44',['NNPkg',['../classonert_1_1ir_1_1_n_n_pkg.html',1,'onert::ir']]],
  ['node_45',['Node',['../classcoco_1_1_d_linked_list_1_1_node.html',1,'coco::DLinkedList&lt; Child, Parent &gt;::Node'],['../classloco_1_1_node.html',1,'loco::Node'],['../structnest_1_1expr_1_1_node.html',1,'nest::expr::Node'],['../structnest_1_1stmt_1_1_node.html',1,'nest::stmt::Node'],['../classonert_1_1dumper_1_1dot_1_1_node.html',1,'onert::dumper::dot::Node']]],
  ['nodeannotation_46',['NodeAnnotation',['../structloco_1_1_node_annotation.html',1,'loco']]],
  ['nodebuilderbase_47',['NodeBuilderBase',['../classluci_1_1_node_builder_base.html',1,'luci']]],
  ['nodeconverterregistry_48',['NodeConverterRegistry',['../classmir__onnx_1_1_node_converter_registry.html',1,'mir_onnx']]],
  ['nodedata_49',['NodeData',['../structlocomotiv_1_1_node_data.html',1,'locomotiv']]],
  ['nodedataimpl_50',['NodeDataImpl',['../classlocomotiv_1_1_node_data_impl.html',1,'locomotiv']]],
  ['nodedeftable_51',['NodeDefTable',['../classmoco_1_1_node_def_table.html',1,'moco']]],
  ['nodedesc_52',['NodeDesc',['../structlocop_1_1_node_desc.html',1,'locop']]],
  ['nodedomain_53',['NodeDomain',['../structlocomotiv_1_1_node_domain.html',1,'locomotiv']]],
  ['nodeexecution_54',['NodeExecution',['../classlocomotiv_1_1_node_execution.html',1,'locomotiv']]],
  ['nodefiller_55',['NodeFiller',['../classluci_1_1_node_filler.html',1,'luci']]],
  ['nodemixin_56',['NodeMixin',['../classloco_1_1_node_mixin.html',1,'loco']]],
  ['nodemixin_3c_20loco_3a_3anodetrait_3a_3adatatype_20_3e_57',['NodeMixin&lt; loco::NodeTrait::DataType &gt;',['../classloco_1_1_node_mixin.html',1,'loco']]],
  ['nodemixin_3c_20loco_3a_3anodetrait_3a_3atensorshape_20_3e_58',['NodeMixin&lt; loco::NodeTrait::TensorShape &gt;',['../classloco_1_1_node_mixin.html',1,'loco']]],
  ['nodemixin_3c_20nodetrait_3a_3adatatype_20_3e_59',['NodeMixin&lt; NodeTrait::DataType &gt;',['../classloco_1_1_node_mixin_3_01_node_trait_1_1_data_type_01_4.html',1,'loco']]],
  ['nodemixin_3c_20nodetrait_3a_3atensorshape_20_3e_60',['NodeMixin&lt; NodeTrait::TensorShape &gt;',['../classloco_1_1_node_mixin_3_01_node_trait_1_1_tensor_shape_01_4.html',1,'loco']]],
  ['nodemixin_3c_20trait_20_3e_61',['NodeMixin&lt; Trait &gt;',['../classloco_1_1_node_mixin.html',1,'loco']]],
  ['nodepool_62',['NodePool',['../classloco_1_1_node_pool.html',1,'loco']]],
  ['nodeshape_63',['NodeShape',['../classloco_1_1_node_shape.html',1,'loco']]],
  ['nodesummarybuilder_64',['NodeSummaryBuilder',['../classexo_1_1_node_summary_builder.html',1,'exo::NodeSummaryBuilder'],['../structlocop_1_1_node_summary_builder.html',1,'locop::NodeSummaryBuilder'],['../classluci_1_1_node_summary_builder.html',1,'luci::NodeSummaryBuilder']]],
  ['nodesummarybuilderfactory_65',['NodeSummaryBuilderFactory',['../classexo_1_1_node_summary_builder_factory.html',1,'exo::NodeSummaryBuilderFactory'],['../structlocop_1_1_node_summary_builder_factory.html',1,'locop::NodeSummaryBuilderFactory'],['../classluci_1_1_node_summary_builder_factory.html',1,'luci::NodeSummaryBuilderFactory']]],
  ['nonincreasingstride_66',['NonIncreasingStride',['../classnnfw_1_1misc_1_1tensor_1_1_non_increasing_stride.html',1,'nnfw::misc::tensor']]],
  ['nonmaxsuppressionv4chef_67',['NonMaxSuppressionV4Chef',['../class_non_max_suppression_v4_chef.html',1,'']]],
  ['nonmaxsuppressionv4cheffactory_68',['NonMaxSuppressionV4ChefFactory',['../struct_non_max_suppression_v4_chef_factory.html',1,'']]],
  ['nonmaxsuppressionv5chef_69',['NonMaxSuppressionV5Chef',['../class_non_max_suppression_v5_chef.html',1,'']]],
  ['nonmaxsuppressionv5cheffactory_70',['NonMaxSuppressionV5ChefFactory',['../struct_non_max_suppression_v5_chef_factory.html',1,'']]],
  ['nopfunction_71',['NopFunction',['../classonert_1_1exec_1_1_nop_function.html',1,'onert::exec']]],
  ['normaldistribution_72',['NormalDistribution',['../classnnfw_1_1cker_1_1random_1_1_normal_distribution.html',1,'nnfw::cker::random']]],
  ['normaldistribution_3c_20generator_2c_20double_20_3e_73',['NormalDistribution&lt; Generator, double &gt;',['../classnnfw_1_1cker_1_1random_1_1_normal_distribution_3_01_generator_00_01double_01_4.html',1,'nnfw::cker::random']]],
  ['normaldistribution_3c_20generator_2c_20eigen_3a_3ahalf_20_3e_74',['NormalDistribution&lt; Generator, Eigen::half &gt;',['../classnnfw_1_1cker_1_1random_1_1_normal_distribution_3_01_generator_00_01_eigen_1_1half_01_4.html',1,'nnfw::cker::random']]],
  ['normaldistribution_3c_20generator_2c_20float_20_3e_75',['NormalDistribution&lt; Generator, float &gt;',['../classnnfw_1_1cker_1_1random_1_1_normal_distribution_3_01_generator_00_01float_01_4.html',1,'nnfw::cker::random']]],
  ['notequal_76',['NotEqual',['../classluci__interpreter_1_1kernels_1_1_not_equal.html',1,'luci_interpreter::kernels']]],
  ['notequalchef_77',['NotEqualChef',['../class_not_equal_chef.html',1,'']]],
  ['notequalcheffactory_78',['NotEqualChefFactory',['../struct_not_equal_chef_factory.html',1,'']]],
  ['npucontext_79',['NpuContext',['../structnpud_1_1core_1_1_npu_context.html',1,'npud::core']]],
  ['nullopt_5fholder_80',['nullopt_holder',['../structflatbuffers_1_1internal_1_1nullopt__holder.html',1,'flatbuffers::internal']]],
  ['nullopt_5ft_81',['nullopt_t',['../structflatbuffers_1_1nullopt__t.html',1,'flatbuffers']]],
  ['numeric_5flimits_82',['numeric_limits',['../classflatbuffers_1_1numeric__limits.html',1,'flatbuffers']]]
];
