var searchData=
[
  ['dagchecker_0',['DAGChecker',['../classonert_1_1ir_1_1verifier_1_1_d_a_g_checker.html',1,'onert::ir::verifier']]],
  ['dalgona_1',['Dalgona',['../classdalgona_1_1_dalgona.html',1,'dalgona']]],
  ['data_2',['Data',['../structcoco_1_1_data.html',1,'coco::Data'],['../structonert_1_1ir_1_1_data.html',1,'onert::ir::Data']]],
  ['datachef_3',['DataChef',['../structsouschef_1_1_data_chef.html',1,'souschef']]],
  ['datacheffactory_4',['DataChefFactory',['../structsouschef_1_1_data_chef_factory.html',1,'souschef']]],
  ['dataflowexecutor_5',['DataflowExecutor',['../classonert_1_1exec_1_1_dataflow_executor.html',1,'onert::exec']]],
  ['dataformatswitcher_6',['DataFormatSwitcher',['../classnnc_1_1_data_format_switcher.html',1,'nnc']]],
  ['datalayoutconversionpass_7',['DataLayoutConversionPass',['../structenco_1_1_data_layout_conversion_pass.html',1,'enco']]],
  ['datalocation_8',['DataLocation',['../struct_data_location.html',1,'']]],
  ['dataptr_9',['DataPtr',['../uniononert_1_1backend_1_1cpu_1_1ops_1_1_data_ptr.html',1,'onert::backend::cpu::ops']]],
  ['dataset_10',['Dataset',['../classsouschef_1_1_dataset.html',1,'souschef']]],
  ['datasetevaluator_11',['DatasetEvaluator',['../classmpqsolver_1_1bisection_1_1_dataset_evaluator.html',1,'mpqsolver::bisection']]],
  ['datatypeimpl_12',['DataTypeImpl',['../structloco_1_1_data_type_impl.html',1,'loco::DataTypeImpl&lt; DT &gt;'],['../structluci__interpreter_1_1_data_type_impl.html',1,'luci_interpreter::DataTypeImpl&lt; DT &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3abool_20_3e_13',['DataTypeImpl&lt; DataType::BOOL &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_b_o_o_l_01_4.html',1,'loco::DataTypeImpl&lt; DataType::BOOL &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_b_o_o_l_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::BOOL &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat16_20_3e_14',['DataTypeImpl&lt; DataType::FLOAT16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat32_20_3e_15',['DataTypeImpl&lt; DataType::FLOAT32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3afloat64_20_3e_16',['DataTypeImpl&lt; DataType::FLOAT64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::FLOAT64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_f_l_o_a_t64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::FLOAT64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as16_20_3e_17',['DataTypeImpl&lt; DataType::S16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as32_20_3e_18',['DataTypeImpl&lt; DataType::S32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as64_20_3e_19',['DataTypeImpl&lt; DataType::S64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3as8_20_3e_20',['DataTypeImpl&lt; DataType::S8 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s8_01_4.html',1,'loco::DataTypeImpl&lt; DataType::S8 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s8_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::S8 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3astring_20_3e_21',['DataTypeImpl&lt; DataType::STRING &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_s_t_r_i_n_g_01_4.html',1,'loco::DataTypeImpl&lt; DataType::STRING &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_s_t_r_i_n_g_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::STRING &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au16_20_3e_22',['DataTypeImpl&lt; DataType::U16 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u16_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U16 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u16_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U16 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au32_20_3e_23',['DataTypeImpl&lt; DataType::U32 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u32_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U32 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u32_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U32 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au64_20_3e_24',['DataTypeImpl&lt; DataType::U64 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u64_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U64 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u64_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U64 &gt;']]],
  ['datatypeimpl_3c_20datatype_3a_3au8_20_3e_25',['DataTypeImpl&lt; DataType::U8 &gt;',['../structloco_1_1_data_type_impl_3_01_data_type_1_1_u8_01_4.html',1,'loco::DataTypeImpl&lt; DataType::U8 &gt;'],['../structluci__interpreter_1_1_data_type_impl_3_01_data_type_1_1_u8_01_4.html',1,'luci_interpreter::DataTypeImpl&lt; DataType::U8 &gt;']]],
  ['dbus_26',['DBus',['../classnpud_1_1core_1_1_d_bus.html',1,'npud::core']]],
  ['deadbageliminationpass_27',['DeadBagEliminationPass',['../structenco_1_1_dead_bag_elimination_pass.html',1,'enco']]],
  ['deadcodeelimination_28',['DeadCodeElimination',['../classnnc_1_1_dead_code_elimination.html',1,'nnc']]],
  ['deadnodequeryservice_29',['DeadNodeQueryService',['../structlogo_1_1_dead_node_query_service.html',1,'logo']]],
  ['deadnodequeryserviceimpl_30',['DeadNodeQueryServiceImpl',['../structluci_1_1_dead_node_query_service_impl.html',1,'luci']]],
  ['deadobjecteliminationpass_31',['DeadObjectEliminationPass',['../structenco_1_1_dead_object_elimination_pass.html',1,'enco']]],
  ['decodecommand_32',['DecodeCommand',['../struct_decode_command.html',1,'DecodeCommand'],['../structtfkit_1_1_decode_command.html',1,'tfkit::DecodeCommand']]],
  ['deconv2dimpl_33',['DeConv2DImpl',['../structmir__interpreter_1_1_de_conv2_d_impl.html',1,'mir_interpreter']]],
  ['deconv2dop_34',['DeConv2DOp',['../classmir_1_1ops_1_1_de_conv2_d_op.html',1,'mir::ops']]],
  ['deconv2dopattributes_35',['Deconv2DOpAttributes',['../structmir_1_1_deconv2_d_op_attributes.html',1,'mir']]],
  ['def_36',['Def',['../classcoco_1_1_def.html',1,'coco']]],
  ['densifychef_37',['DensifyChef',['../class_densify_chef.html',1,'']]],
  ['densifycheffactory_38',['DensifyChefFactory',['../struct_densify_chef_factory.html',1,'']]],
  ['dep_39',['Dep',['../classcoco_1_1_dep.html',1,'coco']]],
  ['depthtospace_40',['DepthToSpace',['../classluci__interpreter_1_1kernels_1_1_depth_to_space.html',1,'luci_interpreter::kernels::DepthToSpace'],['../classonert_1_1ir_1_1operation_1_1_depth_to_space.html',1,'onert::ir::operation::DepthToSpace']]],
  ['depthtospacechef_41',['DepthToSpaceChef',['../class_depth_to_space_chef.html',1,'']]],
  ['depthtospacecheffactory_42',['DepthToSpaceChefFactory',['../struct_depth_to_space_chef_factory.html',1,'']]],
  ['depthtospacelayer_43',['DepthToSpaceLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_depth_to_space_layer.html',1,'onert::backend::cpu::ops']]],
  ['depthtospaceparams_44',['DepthToSpaceParams',['../structluci__interpreter_1_1_depth_to_space_params.html',1,'luci_interpreter']]],
  ['depthtospaceprinter_45',['DepthToSpacePrinter',['../classcircledump_1_1_depth_to_space_printer.html',1,'circledump::DepthToSpacePrinter'],['../classtfldump_1_1_depth_to_space_printer.html',1,'tfldump::DepthToSpacePrinter']]],
  ['depthwiseconv2d_46',['DepthwiseConv2D',['../classloco_1_1_depthwise_conv2_d.html',1,'loco::DepthwiseConv2D'],['../classluci__interpreter_1_1kernels_1_1_depthwise_conv2_d.html',1,'luci_interpreter::kernels::DepthwiseConv2D'],['../classonert_1_1ir_1_1operation_1_1_depthwise_conv2_d.html',1,'onert::ir::operation::DepthwiseConv2D']]],
  ['depthwiseconv2dchef_47',['DepthwiseConv2DChef',['../class_depthwise_conv2_d_chef.html',1,'']]],
  ['depthwiseconv2dcheffactory_48',['DepthwiseConv2DChefFactory',['../struct_depthwise_conv2_d_chef_factory.html',1,'']]],
  ['depthwiseconv2dconverter_49',['DepthwiseConv2DConverter',['../classexo_1_1_depthwise_conv2_d_converter.html',1,'exo']]],
  ['depthwiseconv2dgraphbuilder_50',['DepthwiseConv2DGraphBuilder',['../classtflimport_1_1_depthwise_conv2_d_graph_builder.html',1,'tflimport']]],
  ['depthwiseconv2dimpl_51',['DepthwiseConv2DImpl',['../structmir__interpreter_1_1_depthwise_conv2_d_impl.html',1,'mir_interpreter']]],
  ['depthwiseconv2dimpl_3c_20uint8_5ft_20_3e_52',['DepthwiseConv2DImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_depthwise_conv2_d_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['depthwiseconv2dlayer_53',['DepthwiseConv2DLayer',['../struct_depthwise_conv2_d_layer.html',1,'']]],
  ['depthwiseconv2dnativecanonicalizer_54',['DepthwiseConv2dNativeCanonicalizer',['../classmoco_1_1tf_1_1_depthwise_conv2d_native_canonicalizer.html',1,'moco::tf']]],
  ['depthwiseconv2dnativegraphbuilder_55',['DepthwiseConv2dNativeGraphBuilder',['../classmoco_1_1_depthwise_conv2d_native_graph_builder.html',1,'moco']]],
  ['depthwiseconv2dop_56',['DepthwiseConv2DOp',['../classmir_1_1ops_1_1_depthwise_conv2_d_op.html',1,'mir::ops']]],
  ['depthwiseconv2dparams_57',['DepthwiseConv2DParams',['../structluci__interpreter_1_1_depthwise_conv2_d_params.html',1,'luci_interpreter']]],
  ['depthwiseconv2dprinter_58',['DepthwiseConv2DPrinter',['../classcircledump_1_1_depthwise_conv2_d_printer.html',1,'circledump::DepthwiseConv2DPrinter'],['../classtfldump_1_1_depthwise_conv2_d_printer.html',1,'tfldump::DepthwiseConv2DPrinter']]],
  ['depthwiseconvolutionlayer_59',['DepthwiseConvolutionLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_depthwise_convolution_layer.html',1,'onert::backend::cpu::ops::DepthwiseConvolutionLayer'],['../classonert_1_1backend_1_1xnnpack_1_1ops_1_1_depthwise_convolution_layer.html',1,'onert::backend::xnnpack::ops::DepthwiseConvolutionLayer']]],
  ['depthwiseconvparams_60',['DepthwiseConvParams',['../structnnfw_1_1cker_1_1_depthwise_conv_params.html',1,'nnfw::cker']]],
  ['depthwiseconvworkertask_61',['DepthwiseConvWorkerTask',['../structnnfw_1_1cker_1_1_depthwise_conv_worker_task.html',1,'nnfw::cker::DepthwiseConvWorkerTask&lt; T, TS &gt;'],['../structnnfw_1_1cker_1_1optimized__integer__ops_1_1_depthwise_conv_worker_task.html',1,'nnfw::cker::optimized_integer_ops::DepthwiseConvWorkerTask&lt; T, TS &gt;']]],
  ['depthwisefilterdecode_62',['DepthwiseFilterDecode',['../classloco_1_1_depthwise_filter_decode.html',1,'loco']]],
  ['depthwisefilterdecoder_63',['DepthwiseFilterDecoder',['../structloco_1_1_depthwise_filter_decoder.html',1,'loco']]],
  ['depthwisefilterencode_64',['DepthwiseFilterEncode',['../classloco_1_1_depthwise_filter_encode.html',1,'loco']]],
  ['depthwisefilterencodelayer_65',['DepthwiseFilterEncodeLayer',['../struct_depthwise_filter_encode_layer.html',1,'']]],
  ['depthwisefilterencoder_66',['DepthwiseFilterEncoder',['../structloco_1_1_depthwise_filter_encoder.html',1,'loco']]],
  ['depthwisefilterindex_67',['DepthwiseFilterIndex',['../classloco_1_1_depthwise_filter_index.html',1,'loco']]],
  ['depthwisefiltershape_68',['DepthwiseFilterShape',['../classloco_1_1_depthwise_filter_shape.html',1,'loco']]],
  ['dequantize_69',['Dequantize',['../classluci__interpreter_1_1kernels_1_1_dequantize.html',1,'luci_interpreter::kernels']]],
  ['dequantizechef_70',['DequantizeChef',['../class_dequantize_chef.html',1,'']]],
  ['dequantizecheffactory_71',['DequantizeChefFactory',['../struct_dequantize_chef_factory.html',1,'']]],
  ['dequantizeop_72',['DequantizeOp',['../classmir_1_1ops_1_1_dequantize_op.html',1,'mir::ops']]],
  ['derefnode_73',['DerefNode',['../classnest_1_1expr_1_1_deref_node.html',1,'nest::expr']]],
  ['destroytmp_74',['DestroyTmp',['../structnnc_1_1sir_1_1_destroy_tmp.html',1,'nnc::sir']]],
  ['detectionpostprocess_75',['DetectionPostProcess',['../classonert_1_1ir_1_1operation_1_1_detection_post_process.html',1,'onert::ir::operation']]],
  ['detectionpostprocesslayer_76',['DetectionPostProcessLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_detection_post_process_layer.html',1,'onert::backend::cpu::ops']]],
  ['detectionpostprocessparameters_77',['DetectionPostProcessParameters',['../structonert_1_1backend_1_1cpu_1_1ops_1_1_detection_post_process_layer_1_1_detection_post_process_parameters.html',1,'onert::backend::cpu::ops::DetectionPostProcessLayer']]],
  ['devcontext_78',['DevContext',['../classonert_1_1backend_1_1trix_1_1_dev_context.html',1,'onert::backend::trix']]],
  ['device_79',['Device',['../structnpud_1_1core_1_1_device.html',1,'npud::core']]],
  ['devmanager_80',['DevManager',['../classnpud_1_1core_1_1_dev_manager.html',1,'npud::core']]],
  ['dialect_81',['Dialect',['../classloco_1_1_dialect.html',1,'loco']]],
  ['dialectservice_82',['DialectService',['../structloco_1_1_dialect_service.html',1,'loco']]],
  ['diff_83',['Diff',['../structnnfw_1_1misc_1_1tensor_1_1_diff.html',1,'nnfw::misc::tensor']]],
  ['diffsummary_84',['DiffSummary',['../class_diff_summary.html',1,'']]],
  ['dilation_85',['Dilation',['../classluci_1_1_dilation.html',1,'luci::Dilation'],['../structonert_1_1ir_1_1_dilation.html',1,'onert::ir::Dilation']]],
  ['dimension_86',['Dimension',['../classloco_1_1_dimension.html',1,'loco']]],
  ['dimmetadata_87',['DimMetaData',['../classluci_1_1_dim_meta_data.html',1,'luci']]],
  ['dims_88',['Dims',['../struct_dims.html',1,'']]],
  ['directoryloader_89',['DirectoryLoader',['../classcircle__eval__diff_1_1_directory_loader.html',1,'circle_eval_diff']]],
  ['div_90',['Div',['../classcoco_1_1_div.html',1,'coco::Div'],['../classluci__interpreter_1_1kernels_1_1_div.html',1,'luci_interpreter::kernels::Div']]],
  ['divchef_91',['DivChef',['../class_div_chef.html',1,'']]],
  ['divcheffactory_92',['DivChefFactory',['../struct_div_chef_factory.html',1,'']]],
  ['divgraphbuilder_93',['DivGraphBuilder',['../classtflimport_1_1_div_graph_builder.html',1,'tflimport']]],
  ['divimpl_94',['DivImpl',['../structmir__interpreter_1_1_div_impl.html',1,'mir_interpreter']]],
  ['divimpl_3c_20uint8_5ft_20_3e_95',['DivImpl&lt; uint8_t &gt;',['../structmir__interpreter_1_1_div_impl_3_01uint8__t_01_4.html',1,'mir_interpreter']]],
  ['divop_96',['DivOp',['../classmir_1_1ops_1_1_div_op.html',1,'mir::ops']]],
  ['divparams_97',['DivParams',['../structluci__interpreter_1_1_div_params.html',1,'luci_interpreter']]],
  ['divprinter_98',['DivPrinter',['../classcircledump_1_1_div_printer.html',1,'circledump::DivPrinter'],['../classtfldump_1_1_div_printer.html',1,'tfldump::DivPrinter']]],
  ['dlinkedlist_99',['DLinkedList',['../structcoco_1_1_d_linked_list.html',1,'coco']]],
  ['dlinkedlist_3c_20coco_3a_3ainstr_2c_20coco_3a_3ablock_20_3e_100',['DLinkedList&lt; coco::Instr, coco::Block &gt;',['../structcoco_1_1_d_linked_list.html',1,'coco']]],
  ['domain_101',['Domain',['../classnest_1_1_domain.html',1,'nest']]],
  ['domaincontext_102',['DomainContext',['../classnest_1_1_domain_context.html',1,'nest']]],
  ['domainconverter_103',['DomainConverter',['../classexo_1_1_domain_converter.html',1,'exo']]],
  ['domainid_104',['DomainID',['../classnest_1_1_domain_i_d.html',1,'nest']]],
  ['domaininfo_105',['DomainInfo',['../classnest_1_1_domain_info.html',1,'nest']]],
  ['dotbuilder_106',['DotBuilder',['../class_dot_builder_1_1_dot_builder.html',1,'DotBuilder.DotBuilder'],['../classonert_1_1dumper_1_1dot_1_1_dot_builder.html',1,'onert::dumper::dot::DotBuilder']]],
  ['dotdumper_107',['DotDumper',['../classonert_1_1dumper_1_1dot_1_1_dot_dumper.html',1,'onert::dumper::dot']]],
  ['dotedge_108',['DotEdge',['../structmir_1_1_dot_edge.html',1,'mir']]],
  ['dotgraph_109',['DotGraph',['../classmir_1_1_dot_graph.html',1,'mir']]],
  ['dotnode_110',['DotNode',['../structmir_1_1_dot_node.html',1,'mir']]],
  ['dotnodebuilder_111',['DotNodeBuilder',['../classmir_1_1_dot_node_builder.html',1,'mir']]],
  ['driver_112',['Driver',['../classnnc_1_1_driver.html',1,'nnc']]],
  ['driverexception_113',['DriverException',['../classnnc_1_1_driver_exception.html',1,'nnc']]],
  ['dummypass1_114',['DummyPass1',['../class_dummy_pass1.html',1,'']]],
  ['dummypass2_115',['DummyPass2',['../class_dummy_pass2.html',1,'']]],
  ['dumpconstants_116',['DumpConstants',['../classcircleinspect_1_1_dump_constants.html',1,'circleinspect']]],
  ['dumpconv2dweight_117',['DumpConv2DWeight',['../classcircleinspect_1_1_dump_conv2_d_weight.html',1,'circleinspect::DumpConv2DWeight'],['../classtflinspect_1_1_dump_conv2_d_weight.html',1,'tflinspect::DumpConv2DWeight']]],
  ['dumperpass_118',['DumperPass',['../classnnc_1_1_dumper_pass.html',1,'nnc']]],
  ['dumpfakequantfm_119',['DumpFakeQuantFM',['../class_dump_fake_quant_f_m_1_1_dump_fake_quant_f_m.html',1,'DumpFakeQuantFM']]],
  ['dumpfp32fm_120',['DumpFP32FM',['../class_dump_f_p32_f_m_1_1_dump_f_p32_f_m.html',1,'DumpFP32FM']]],
  ['dumpinterface_121',['DumpInterface',['../classcircleinspect_1_1_dump_interface.html',1,'circleinspect::DumpInterface'],['../classcircletensordump_1_1_dump_interface.html',1,'circletensordump::DumpInterface'],['../classtflinspect_1_1_dump_interface.html',1,'tflinspect::DumpInterface']]],
  ['dumpoperators_122',['DumpOperators',['../classcircleinspect_1_1_dump_operators.html',1,'circleinspect::DumpOperators'],['../classcirops_1_1_dump_operators.html',1,'cirops::DumpOperators'],['../classtflinspect_1_1_dump_operators.html',1,'tflinspect::DumpOperators']]],
  ['dumpoperatorversion_123',['DumpOperatorVersion',['../classcircleinspect_1_1_dump_operator_version.html',1,'circleinspect::DumpOperatorVersion'],['../classtflinspect_1_1_dump_operator_version.html',1,'tflinspect::DumpOperatorVersion']]],
  ['dumpoption_124',['DumpOption',['../structcirops_1_1_dump_option.html',1,'cirops']]],
  ['dumptensordtype_125',['DumpTensorDType',['../classcircleinspect_1_1_dump_tensor_d_type.html',1,'circleinspect']]],
  ['dumptensors_126',['DumpTensors',['../classcircletensordump_1_1_dump_tensors.html',1,'circletensordump']]],
  ['dumptensorstohdf5_127',['DumpTensorsToHdf5',['../classcircletensordump_1_1_dump_tensors_to_hdf5.html',1,'circletensordump']]],
  ['dumpvisitor_128',['DumpVisitor',['../classnnc_1_1_dump_visitor.html',1,'nnc']]],
  ['duplicatedobjectreductionpass_129',['DuplicatedObjectReductionPass',['../structenco_1_1_duplicated_object_reduction_pass.html',1,'enco']]],
  ['durationevent_130',['DurationEvent',['../struct_duration_event.html',1,'']]],
  ['dynamicbinder_131',['DynamicBinder',['../structrua_1_1_dynamic_binder.html',1,'rua']]],
  ['dynamicloader_132',['DynamicLoader',['../classnpud_1_1core_1_1_dynamic_loader.html',1,'npud::core']]],
  ['dynamicmemorymanager_133',['DynamicMemoryManager',['../classonert_1_1backend_1_1basic_1_1_dynamic_memory_manager.html',1,'onert::backend::basic']]],
  ['dynamicshapeinferer_134',['DynamicShapeInferer',['../classonert_1_1exec_1_1_dynamic_shape_inferer.html',1,'onert::exec']]],
  ['dynamictensorctx_135',['DynamicTensorCtx',['../structonert_1_1exec_1_1_function_sequence_1_1_dynamic_tensor_ctx.html',1,'onert::exec::FunctionSequence']]],
  ['dynamictensormanager_136',['DynamicTensorManager',['../classonert_1_1backend_1_1basic_1_1_dynamic_tensor_manager.html',1,'onert::backend::basic']]]
];
