var searchData=
[
  ['ui_0',['UI',['../class_u_i.html',1,'']]],
  ['unaryfunc_1',['UnaryFunc',['../structlocomotiv_1_1_unary_func.html',1,'locomotiv']]],
  ['unaryop_2',['UnaryOp',['../classcoco_1_1_unary_op.html',1,'coco']]],
  ['unidirectionalsequencelstm_3',['UnidirectionalSequenceLSTM',['../classluci__interpreter_1_1kernels_1_1_unidirectional_sequence_l_s_t_m.html',1,'luci_interpreter::kernels']]],
  ['unidirectionalsequencelstmchef_4',['UnidirectionalSequenceLSTMChef',['../class_unidirectional_sequence_l_s_t_m_chef.html',1,'']]],
  ['unidirectionalsequencelstmcheffactory_5',['UnidirectionalSequenceLSTMChefFactory',['../struct_unidirectional_sequence_l_s_t_m_chef_factory.html',1,'']]],
  ['unidirectionalsequencelstmparams_6',['UnidirectionalSequenceLSTMParams',['../structluci__interpreter_1_1_unidirectional_sequence_l_s_t_m_params.html',1,'luci_interpreter']]],
  ['unidirectionalsequencelstmprinter_7',['UnidirectionalSequenceLSTMPrinter',['../classcircledump_1_1_unidirectional_sequence_l_s_t_m_printer.html',1,'circledump::UnidirectionalSequenceLSTMPrinter'],['../classtfldump_1_1_unidirectional_sequence_l_s_t_m_printer.html',1,'tfldump::UnidirectionalSequenceLSTMPrinter']]],
  ['uniformdistribution_8',['UniformDistribution',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution.html',1,'nnfw::cker::random']]],
  ['uniformdistribution_3c_20generator_2c_20double_20_3e_9',['UniformDistribution&lt; Generator, double &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution_3_01_generator_00_01double_01_4.html',1,'nnfw::cker::random']]],
  ['uniformdistribution_3c_20generator_2c_20eigen_3a_3ahalf_20_3e_10',['UniformDistribution&lt; Generator, Eigen::half &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution_3_01_generator_00_01_eigen_1_1half_01_4.html',1,'nnfw::cker::random']]],
  ['uniformdistribution_3c_20generator_2c_20float_20_3e_11',['UniformDistribution&lt; Generator, float &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution_3_01_generator_00_01float_01_4.html',1,'nnfw::cker::random']]],
  ['uniformdistribution_3c_20generator_2c_20int32_5ft_20_3e_12',['UniformDistribution&lt; Generator, int32_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution_3_01_generator_00_01int32__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformdistribution_3c_20generator_2c_20int64_5ft_20_3e_13',['UniformDistribution&lt; Generator, int64_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_distribution_3_01_generator_00_01int64__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution_14',['UniformFullIntDistribution',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution32_15',['UniformFullIntDistribution32',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution32.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution32_3c_20generator_2c_20int32_5ft_20_3e_16',['UniformFullIntDistribution32&lt; Generator, int32_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution32.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution32_3c_20generator_2c_20uint32_5ft_20_3e_17',['UniformFullIntDistribution32&lt; Generator, uint32_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution32.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution64_18',['UniformFullIntDistribution64',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution64.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution64_3c_20generator_2c_20int64_5ft_20_3e_19',['UniformFullIntDistribution64&lt; Generator, int64_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution64.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution64_3c_20generator_2c_20uint64_5ft_20_3e_20',['UniformFullIntDistribution64&lt; Generator, uint64_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution64.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution_3c_20generator_2c_20int32_5ft_20_3e_21',['UniformFullIntDistribution&lt; Generator, int32_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution_3_01_generator_00_01int32__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution_3c_20generator_2c_20int64_5ft_20_3e_22',['UniformFullIntDistribution&lt; Generator, int64_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution_3_01_generator_00_01int64__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution_3c_20generator_2c_20uint32_5ft_20_3e_23',['UniformFullIntDistribution&lt; Generator, uint32_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution_3_01_generator_00_01uint32__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformfullintdistribution_3c_20generator_2c_20uint64_5ft_20_3e_24',['UniformFullIntDistribution&lt; Generator, uint64_t &gt;',['../classnnfw_1_1cker_1_1random_1_1_uniform_full_int_distribution_3_01_generator_00_01uint64__t_01_4.html',1,'nnfw::cker::random']]],
  ['uniformpalette_25',['UniformPalette',['../class_palette_1_1_uniform_palette.html',1,'Palette']]],
  ['uniformtransform_26',['UniformTransform',['../classbino_1_1_uniform_transform.html',1,'bino']]],
  ['uniquechef_27',['UniqueChef',['../class_unique_chef.html',1,'']]],
  ['uniquecheffactory_28',['UniqueChefFactory',['../struct_unique_chef_factory.html',1,'']]],
  ['uniqueprinter_29',['UniquePrinter',['../classcircledump_1_1_unique_printer.html',1,'circledump::UniquePrinter'],['../classtfldump_1_1_unique_printer.html',1,'tfldump::UniquePrinter']]],
  ['unpack_30',['Unpack',['../classluci__interpreter_1_1kernels_1_1_unpack.html',1,'luci_interpreter::kernels::Unpack'],['../classonert_1_1ir_1_1operation_1_1_unpack.html',1,'onert::ir::operation::Unpack']]],
  ['unpackchef_31',['UnpackChef',['../class_unpack_chef.html',1,'']]],
  ['unpackcheffactory_32',['UnpackChefFactory',['../struct_unpack_chef_factory.html',1,'']]],
  ['unpackcommand_33',['UnpackCommand',['../structtfkit_1_1_unpack_command.html',1,'tfkit']]],
  ['unpacklayer_34',['UnpackLayer',['../classonert_1_1backend_1_1cpu_1_1ops_1_1_unpack_layer.html',1,'onert::backend::cpu::ops']]],
  ['unpackparams_35',['UnpackParams',['../structluci__interpreter_1_1_unpack_params.html',1,'luci_interpreter::UnpackParams'],['../structnnfw_1_1cker_1_1_unpack_params.html',1,'nnfw::cker::UnpackParams']]],
  ['unrollunidirectionalsequencelstmpass_36',['UnrollUnidirectionalSequenceLSTMPass',['../structluci_1_1_unroll_unidirectional_sequence_l_s_t_m_pass.html',1,'luci']]],
  ['unused_5fall_37',['UNUSED_ALL',['../structnnfw_1_1cker_1_1_u_n_u_s_e_d___a_l_l.html',1,'nnfw::cker::UNUSED_ALL'],['../structnnfw_1_1ruy_1_1_u_n_u_s_e_d___a_l_l.html',1,'nnfw::ruy::UNUSED_ALL']]],
  ['unusedoperandeliminationpass_38',['UnusedOperandEliminationPass',['../classonert_1_1compiler_1_1pass_1_1_unused_operand_elimination_pass.html',1,'onert::compiler::pass']]],
  ['update_39',['Update',['../classcoco_1_1_update.html',1,'coco']]],
  ['updatequeue_40',['UpdateQueue',['../classmoco_1_1_update_queue.html',1,'moco']]],
  ['updater_41',['Updater',['../structcoco_1_1_bag_1_1_updater.html',1,'coco::Bag']]],
  ['use_42',['Use',['../classcoco_1_1_use.html',1,'coco::Use'],['../classloco_1_1_use.html',1,'loco::Use'],['../structmir_1_1_operation_1_1_use.html',1,'mir::Operation::Use']]],
  ['userdata_43',['Userdata',['../structonert_1_1ir_1_1operation_1_1_custom_1_1_userdata.html',1,'onert::ir::operation::Custom']]],
  ['userexn_44',['UserExn',['../classoops_1_1_user_exn.html',1,'oops']]],
  ['usersettings_45',['UserSettings',['../structluci_1_1_user_settings.html',1,'luci']]],
  ['usersettingsimpl_46',['UserSettingsImpl',['../classluci_1_1_user_settings_impl.html',1,'luci']]],
  ['usertensor_47',['UserTensor',['../classonert_1_1backend_1_1builtin_1_1_user_tensor.html',1,'onert::backend::builtin']]]
];
