var searchData=
[
  ['safemain_2ecpp_0',['SafeMain.cpp',['../_safe_main_8cpp.html',1,'']]],
  ['sbserializer_2ecpp_1',['SBSerializer.cpp',['../_s_b_serializer_8cpp.html',1,'']]],
  ['sbserializer_2eh_2',['SBSerializer.h',['../_s_b_serializer_8h.html',1,'']]],
  ['scale_2ecpp_3',['Scale.cpp',['../_scale_8cpp.html',1,'']]],
  ['scale_2eh_4',['Scale.h',['../_scale_8h.html',1,'']]],
  ['scatternd_2ecpp_5',['ScatterNd.cpp',['../core_2src_2_op_2_scatter_nd_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_scatter_nd_8cpp.html',1,'(Global Namespace)']]],
  ['scatternd_2eh_6',['ScatterNd.h',['../tflite_2src_2_op_2include_2_scatter_nd_8h.html',1,'(Global Namespace)'],['../core_2src_2_op_2_scatter_nd_8h.html',1,'(Global Namespace)']]],
  ['scatterndoptions_2ecpp_7',['ScatterNdOptions.cpp',['../_scatter_nd_options_8cpp.html',1,'']]],
  ['scatterndoptions_2eh_8',['ScatterNdOptions.h',['../_scatter_nd_options_8h.html',1,'']]],
  ['schedule_2ecpp_9',['Schedule.cpp',['../_schedule_8cpp.html',1,'']]],
  ['schedule_2eh_10',['Schedule.h',['../_schedule_8h.html',1,'']]],
  ['scratchpadhelpercmsisnn_2eh_11',['ScratchpadHelperCMSISNN.h',['../_scratchpad_helper_c_m_s_i_s_n_n_8h.html',1,'']]],
  ['scratchpadhelperlinux_2eh_12',['ScratchpadHelperLinux.h',['../_scratchpad_helper_linux_8h.html',1,'']]],
  ['scratchpadhelpermcu_2eh_13',['ScratchpadHelperMCU.h',['../_scratchpad_helper_m_c_u_8h.html',1,'']]],
  ['segmentsum_2ecpp_14',['SegmentSum.cpp',['../core_2src_2_op_2_segment_sum_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_segment_sum_8cpp.html',1,'(Global Namespace)']]],
  ['segmentsum_2eh_15',['SegmentSum.h',['../core_2src_2_op_2_segment_sum_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_segment_sum_8h.html',1,'(Global Namespace)']]],
  ['segmentsumoptions_2ecpp_16',['SegmentSumOptions.cpp',['../_segment_sum_options_8cpp.html',1,'']]],
  ['segmentsumoptions_2eh_17',['SegmentSumOptions.h',['../_segment_sum_options_8h.html',1,'']]],
  ['select_2ecc_18',['Select.cc',['../_select_8cc.html',1,'']]],
  ['select_2ecpp_19',['Select.cpp',['../tflchef_2tflite_2src_2_op_2_select_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2loader_2nodes_2_select_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_select_8cpp.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_select_8cpp.html',1,'(Global Namespace)']]],
  ['select_2eh_20',['Select.h',['../compute_2cker_2include_2cker_2operation_2_select_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_select_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_select_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_select_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_select_8h.html',1,'(Global Namespace)']]],
  ['selectlayer_2ecc_21',['SelectLayer.cc',['../_select_layer_8cc.html',1,'']]],
  ['selectlayer_2eh_22',['SelectLayer.h',['../_select_layer_8h.html',1,'']]],
  ['selectoptions_2ecpp_23',['SelectOptions.cpp',['../_select_options_8cpp.html',1,'']]],
  ['selectoptions_2eh_24',['SelectOptions.h',['../_select_options_8h.html',1,'']]],
  ['selecttype_2eh_25',['SelectType.h',['../_select_type_8h.html',1,'']]],
  ['selectv2_2ecpp_26',['SelectV2.cpp',['../core_2src_2_op_2_select_v2_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_select_v2_8cpp.html',1,'(Global Namespace)']]],
  ['selectv2_2eh_27',['SelectV2.h',['../tflite_2src_2_op_2include_2_select_v2_8h.html',1,'(Global Namespace)'],['../core_2src_2_op_2_select_v2_8h.html',1,'(Global Namespace)']]],
  ['selectv2options_2ecpp_28',['SelectV2Options.cpp',['../_select_v2_options_8cpp.html',1,'']]],
  ['selectv2options_2eh_29',['SelectV2Options.h',['../_select_v2_options_8h.html',1,'']]],
  ['sequencedir_2ecpp_30',['SequencedIR.cpp',['../_sequenced_i_r_8cpp.html',1,'']]],
  ['sequencedir_2eh_31',['SequencedIR.h',['../_sequenced_i_r_8h.html',1,'']]],
  ['serializeddata_2eh_32',['SerializedData.h',['../_serialized_data_8h.html',1,'']]],
  ['server_2ecc_33',['Server.cc',['../_server_8cc.html',1,'']]],
  ['server_2eh_34',['Server.h',['../_server_8h.html',1,'']]],
  ['service_2eh_35',['Service.h',['../_service_8h.html',1,'']]],
  ['session_2ecpp_36',['Session.cpp',['../enco_2core_2src_2_session_8cpp.html',1,'(Global Namespace)'],['../locomotiv_2src_2_session_8cpp.html',1,'(Global Namespace)']]],
  ['session_2eh_37',['Session.h',['../compiler_2enco_2core_2src_2_session_8h.html',1,'(Global Namespace)'],['../compiler_2locomotiv_2include_2locomotiv_2_session_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2tflite_2include_2tflite_2_session_8h.html',1,'(Global Namespace)']]],
  ['set_2eh_38',['Set.h',['../_set_8h.html',1,'']]],
  ['severity_2eh_39',['Severity.h',['../_severity_8h.html',1,'']]],
  ['sgd_2ecc_40',['SGD.cc',['../_s_g_d_8cc.html',1,'']]],
  ['sgd_2eh_41',['SGD.h',['../_s_g_d_8h.html',1,'']]],
  ['shape_2ecc_42',['Shape.cc',['../_shape_8cc.html',1,'(Global Namespace)'],['../operation_2_shape_8cc.html',1,'(Global Namespace)']]],
  ['shape_2ecpp_43',['Shape.cpp',['../compiler_2luci-interpreter_2src_2loader_2nodes_2_shape_8cpp.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2src_2tensor_2_shape_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2angkor_2src_2_a_d_t_2tensor_2_shape_8cpp.html',1,'(Global Namespace)'],['../compiler_2angkor_2src_2_a_d_t_2kernel_2_shape_8cpp.html',1,'(Global Namespace)']]],
  ['shape_2eh_44',['Shape.h',['../runtime_2onert_2core_2include_2ir_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2tensor_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2kernel_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2feature_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2include_2mir_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_shape_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2tensor_2_shape_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2_shape_8h.html',1,'(Global Namespace)'],['../compute_2ruy_2include_2ruy_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2feature_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2kernel_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2matrix_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2ndarray_2include_2ndarray_2_shape_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_shape_8h.html',1,'(Global Namespace)']]],
  ['shapecalculatorex_2eh_45',['ShapeCalculatorEx.h',['../_shape_calculator_ex_8h.html',1,'']]],
  ['shapeconverter_2ecc_46',['ShapeConverter.cc',['../_shape_converter_8cc.html',1,'']]],
  ['shapeconverter_2eh_47',['ShapeConverter.h',['../_shape_converter_8h.html',1,'']]],
  ['shapedescription_2ecpp_48',['ShapeDescription.cpp',['../_shape_description_8cpp.html',1,'']]],
  ['shapedescription_2eh_49',['ShapeDescription.h',['../_shape_description_8h.html',1,'']]],
  ['shapeinfer_5fstridedslice_2ecpp_50',['ShapeInfer_StridedSlice.cpp',['../_shape_infer___strided_slice_8cpp.html',1,'']]],
  ['shapeinfer_5fstridedslice_2eh_51',['ShapeInfer_StridedSlice.h',['../_shape_infer___strided_slice_8h.html',1,'']]],
  ['shapeinference_2ecc_52',['ShapeInference.cc',['../_shape_inference_8cc.html',1,'']]],
  ['shapeinference_2ecpp_53',['ShapeInference.cpp',['../exo_2src_2_shape_inference_8cpp.html',1,'(Global Namespace)'],['../loco_2src_2_service_2_shape_inference_8cpp.html',1,'(Global Namespace)'],['../mir_2unittests_2_shape_inference_8cpp.html',1,'(Global Namespace)']]],
  ['shapeinference_2eh_54',['ShapeInference.h',['../compiler_2loco_2include_2loco_2_service_2_shape_inference_8h.html',1,'(Global Namespace)'],['../compiler_2exo_2src_2_shape_inference_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2util_2_shape_inference_8h.html',1,'(Global Namespace)']]],
  ['shapeinferencepass_2ecpp_55',['ShapeInferencePass.cpp',['../exo_2src_2_pass_2_shape_inference_pass_8cpp.html',1,'(Global Namespace)'],['../moco-tf_2src_2_transforms_2_shape_inference_pass_8cpp.html',1,'(Global Namespace)']]],
  ['shapeinferencepass_2eh_56',['ShapeInferencePass.h',['../exo_2src_2_pass_2_shape_inference_pass_8h.html',1,'(Global Namespace)'],['../moco-tf_2src_2_transforms_2_shape_inference_pass_8h.html',1,'(Global Namespace)']]],
  ['shapeinferencerule_2ecpp_57',['ShapeInferenceRule.cpp',['../_shape_inference_rule_8cpp.html',1,'']]],
  ['shapeinferencerule_2eh_58',['ShapeInferenceRule.h',['../_shape_inference_rule_8h.html',1,'']]],
  ['shapekernel_2eh_59',['ShapeKernel.h',['../_shape_kernel_8h.html',1,'']]],
  ['shapelayer_2ecc_60',['ShapeLayer.cc',['../_shape_layer_8cc.html',1,'']]],
  ['shapelayer_2eh_61',['ShapeLayer.h',['../_shape_layer_8h.html',1,'']]],
  ['shapeoptions_2ecpp_62',['ShapeOptions.cpp',['../_shape_options_8cpp.html',1,'']]],
  ['shapeoptions_2eh_63',['ShapeOptions.h',['../_shape_options_8h.html',1,'']]],
  ['shapequery_2ecpp_64',['ShapeQuery.cpp',['../_shape_query_8cpp.html',1,'']]],
  ['shapequery_2eh_65',['ShapeQuery.h',['../_shape_query_8h.html',1,'']]],
  ['shaperange_2ecpp_66',['ShapeRange.cpp',['../_shape_range_8cpp.html',1,'']]],
  ['shaperange_2eh_67',['ShapeRange.h',['../_shape_range_8h.html',1,'']]],
  ['shapevalidator_2ecc_68',['ShapeValidator.cc',['../_shape_validator_8cc.html',1,'']]],
  ['shapevalidator_2eh_69',['ShapeValidator.h',['../_shape_validator_8h.html',1,'']]],
  ['shim_2eh_70',['Shim.h',['../_shim_8h.html',1,'']]],
  ['show_2ecpp_71',['Show.cpp',['../_show_8cpp.html',1,'']]],
  ['shuffle_2ecpp_72',['Shuffle.cpp',['../_shuffle_8cpp.html',1,'']]],
  ['shuffleweightto16x1float32pass_2ecpp_73',['ShuffleWeightTo16x1Float32Pass.cpp',['../_shuffle_weight_to16x1_float32_pass_8cpp.html',1,'']]],
  ['shuffleweightto16x1float32pass_2eh_74',['ShuffleWeightTo16x1Float32Pass.h',['../_shuffle_weight_to16x1_float32_pass_8h.html',1,'']]],
  ['sigmoid_2ecpp_75',['Sigmoid.cpp',['../mir-interpreter_2src_2ops_2_sigmoid_8cpp.html',1,'(Global Namespace)'],['../mir_2src_2mir__onnx__importer_2_op_2_sigmoid_8cpp.html',1,'(Global Namespace)']]],
  ['sigmoid_2eh_76',['Sigmoid.h',['../mir-interpreter_2src_2ops_2_sigmoid_8h.html',1,'(Global Namespace)'],['../mir_2src_2mir__onnx__importer_2_op_2_sigmoid_8h.html',1,'(Global Namespace)']]],
  ['sigmoidop_2eh_77',['SigmoidOp.h',['../_sigmoid_op_8h.html',1,'']]],
  ['signal_2ecc_78',['Signal.cc',['../_signal_8cc.html',1,'']]],
  ['signal_2eh_79',['Signal.h',['../_signal_8h.html',1,'']]],
  ['simplememorymanager_2ecpp_80',['SimpleMemoryManager.cpp',['../onert-micro_2luci-interpreter_2src_2memory__managers_2_simple_memory_manager_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2_simple_memory_manager_8cpp.html',1,'(Global Namespace)']]],
  ['simplememorymanager_2eh_81',['SimpleMemoryManager.h',['../onert-micro_2luci-interpreter_2src_2memory__managers_2_simple_memory_manager_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2include_2luci__interpreter_2_simple_memory_manager_8h.html',1,'(Global Namespace)']]],
  ['simplenodetransform_2eh_82',['SimpleNodeTransform.h',['../_simple_node_transform_8h.html',1,'']]],
  ['simplifydomainconversionpass_2ecpp_83',['SimplifyDomainConversionPass.cpp',['../_simplify_domain_conversion_pass_8cpp.html',1,'']]],
  ['simplifydomainconversionpass_2eh_84',['SimplifyDomainConversionPass.h',['../_simplify_domain_conversion_pass_8h.html',1,'']]],
  ['sin_2ecpp_85',['Sin.cpp',['../core_2src_2_op_2_sin_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_sin_8cpp.html',1,'(Global Namespace)']]],
  ['sin_2eh_86',['Sin.h',['../core_2src_2_op_2_sin_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_sin_8h.html',1,'(Global Namespace)']]],
  ['singlemodelexecutors_2ecc_87',['SingleModelExecutors.cc',['../_single_model_executors_8cc.html',1,'']]],
  ['singlemodelexecutors_2eh_88',['SingleModelExecutors.h',['../_single_model_executors_8h.html',1,'']]],
  ['singleoperatortest_2epy_89',['SingleOperatorTest.py',['../_single_operator_test_8py.html',1,'']]],
  ['sink_2ecpp_90',['Sink.cpp',['../_sink_8cpp.html',1,'']]],
  ['sink_2eh_91',['Sink.h',['../_sink_8h.html',1,'']]],
  ['sinkrelu_2ecpp_92',['SinkRelu.cpp',['../_sink_relu_8cpp.html',1,'']]],
  ['sinkrelu_2eh_93',['SinkRelu.h',['../_sink_relu_8h.html',1,'']]],
  ['sinktest_2ecpp_94',['SinkTest.cpp',['../_sink_test_8cpp.html',1,'']]],
  ['sinktranspose_2ecpp_95',['SinkTranspose.cpp',['../_sink_transpose_8cpp.html',1,'']]],
  ['sinktranspose_2eh_96',['SinkTranspose.h',['../_sink_transpose_8h.html',1,'']]],
  ['sisokernel_2eh_97',['SISOKernel.h',['../_s_i_s_o_kernel_8h.html',1,'']]],
  ['slice_2ecc_98',['Slice.cc',['../_slice_8cc.html',1,'']]],
  ['slice_2ecpp_99',['Slice.cpp',['../compiler_2tflchef_2tflite_2src_2_op_2_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_slice_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_slice_8cpp.html',1,'(Global Namespace)']]],
  ['slice_2eh_100',['Slice.h',['../runtime_2onert_2core_2include_2ir_2operation_2_slice_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_slice_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_slice_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_slice_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_slice_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_slice_8h.html',1,'(Global Namespace)']]],
  ['slicelayer_2ecc_101',['SliceLayer.cc',['../_slice_layer_8cc.html',1,'']]],
  ['slicelayer_2eh_102',['SliceLayer.h',['../_slice_layer_8h.html',1,'']]],
  ['sliceop_2ecpp_103',['SliceOp.cpp',['../_slice_op_8cpp.html',1,'']]],
  ['sliceop_2eh_104',['SliceOp.h',['../_slice_op_8h.html',1,'']]],
  ['sliceoptions_2ecpp_105',['SliceOptions.cpp',['../_slice_options_8cpp.html',1,'']]],
  ['sliceoptions_2eh_106',['SliceOptions.h',['../_slice_options_8h.html',1,'']]],
  ['smallvector_2eh_107',['SmallVector.h',['../_small_vector_8h.html',1,'']]],
  ['snpeeventwriter_2ecc_108',['SNPEEventWriter.cc',['../_s_n_p_e_event_writer_8cc.html',1,'']]],
  ['softmax_2ecc_109',['Softmax.cc',['../train_2operation_2_softmax_8cc.html',1,'(Global Namespace)'],['../operation_2_softmax_8cc.html',1,'(Global Namespace)']]],
  ['softmax_2ecpp_110',['Softmax.cpp',['../compiler_2luci-interpreter_2src_2loader_2nodes_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_softmax_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2locomotiv_2src_2_node_2_softmax_8cpp.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_softmax_8cpp.html',1,'(Global Namespace)']]],
  ['softmax_2efloat_2ecpp_111',['Softmax.float.cpp',['../_softmax_8float_8cpp.html',1,'']]],
  ['softmax_2efloat_2eh_112',['Softmax.float.h',['../_softmax_8float_8h.html',1,'']]],
  ['softmax_2eh_113',['Softmax.h',['../compiler_2luci-interpreter_2src_2kernels_2_soft_max_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2train_2operation_2_soft_max_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_soft_max_8h.html',1,'(Global Namespace)']]],
  ['softmax_2eh_114',['SoftMax.h',['../compute_2cker_2include_2cker_2operation_2_soft_max_8h.html',1,'']]],
  ['softmax_2eh_115',['Softmax.h',['../compiler_2tflchef_2tflite_2src_2_op_2include_2_soft_max_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_soft_max_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_soft_max_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_soft_max_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_soft_max_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_soft_max_8h.html',1,'(Global Namespace)']]],
  ['softmaxcanonicalizer_2ecpp_116',['SoftmaxCanonicalizer.cpp',['../_softmax_canonicalizer_8cpp.html',1,'']]],
  ['softmaxcanonicalizer_2eh_117',['SoftmaxCanonicalizer.h',['../_softmax_canonicalizer_8h.html',1,'']]],
  ['softmaxlayer_2ecc_118',['SoftMaxLayer.cc',['../_soft_max_layer_8cc.html',1,'']]],
  ['softmaxlayer_2eh_119',['SoftMaxLayer.h',['../_soft_max_layer_8h.html',1,'']]],
  ['softmaxop_2eh_120',['SoftmaxOp.h',['../_softmax_op_8h.html',1,'']]],
  ['softmaxoptions_2ecpp_121',['SoftmaxOptions.cpp',['../_softmax_options_8cpp.html',1,'']]],
  ['softmaxoptions_2eh_122',['SoftmaxOptions.h',['../_softmax_options_8h.html',1,'']]],
  ['solverhooks_2ecpp_123',['SolverHooks.cpp',['../_solver_hooks_8cpp.html',1,'']]],
  ['solverhooks_2eh_124',['SolverHooks.h',['../_solver_hooks_8h.html',1,'']]],
  ['solveroutput_2ecpp_125',['SolverOutput.cpp',['../_solver_output_8cpp.html',1,'']]],
  ['solveroutput_2eh_126',['SolverOutput.h',['../_solver_output_8h.html',1,'']]],
  ['source_2ecpp_127',['Source.cpp',['../_source_8cpp.html',1,'']]],
  ['source_2eh_128',['Source.h',['../_source_8h.html',1,'']]],
  ['sourcesetting_2eh_129',['SourceSetting.h',['../_source_setting_8h.html',1,'']]],
  ['spacetobatchnd_2ecc_130',['SpaceToBatchND.cc',['../_space_to_batch_n_d_8cc.html',1,'']]],
  ['spacetobatchnd_2ecpp_131',['SpaceToBatchND.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_space_to_batch_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_space_to_batch_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_space_to_batch_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_space_to_batch_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_space_to_batch_n_d_8cpp.html',1,'(Global Namespace)']]],
  ['spacetobatchnd_2eh_132',['SpaceToBatchND.h',['../compiler_2tflchef_2core_2src_2_op_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_space_to_batch_n_d_8h.html',1,'(Global Namespace)']]],
  ['spacetobatchndlayer_2ecc_133',['SpaceToBatchNDLayer.cc',['../_space_to_batch_n_d_layer_8cc.html',1,'']]],
  ['spacetobatchndlayer_2eh_134',['SpaceToBatchNDLayer.h',['../_space_to_batch_n_d_layer_8h.html',1,'']]],
  ['spacetobatchndoptions_2ecpp_135',['SpaceToBatchNDOptions.cpp',['../_space_to_batch_n_d_options_8cpp.html',1,'']]],
  ['spacetobatchndoptions_2eh_136',['SpaceToBatchNDOptions.h',['../_space_to_batch_n_d_options_8h.html',1,'']]],
  ['spacetodepth_2ecc_137',['SpaceToDepth.cc',['../_space_to_depth_8cc.html',1,'']]],
  ['spacetodepth_2ecpp_138',['SpaceToDepth.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_space_to_depth_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_space_to_depth_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_space_to_depth_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_space_to_depth_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_space_to_depth_8cpp.html',1,'(Global Namespace)']]],
  ['spacetodepth_2eh_139',['SpaceToDepth.h',['../compiler_2luci-interpreter_2src_2kernels_2_space_to_depth_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_space_to_depth_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_space_to_depth_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_space_to_depth_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_space_to_depth_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_space_to_depth_8h.html',1,'(Global Namespace)']]],
  ['spacetodepthlayer_2ecc_140',['SpaceToDepthLayer.cc',['../_space_to_depth_layer_8cc.html',1,'']]],
  ['spacetodepthlayer_2eh_141',['SpaceToDepthLayer.h',['../_space_to_depth_layer_8h.html',1,'']]],
  ['spacetodepthoptions_2ecpp_142',['SpaceToDepthOptions.cpp',['../_space_to_depth_options_8cpp.html',1,'']]],
  ['spacetodepthoptions_2eh_143',['SpaceToDepthOptions.h',['../_space_to_depth_options_8h.html',1,'']]],
  ['span_2eh_144',['Span.h',['../_span_8h.html',1,'']]],
  ['sparsetodense_2ecpp_145',['SparseToDense.cpp',['../core_2src_2_op_2_sparse_to_dense_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_sparse_to_dense_8cpp.html',1,'(Global Namespace)']]],
  ['sparsetodense_2eh_146',['SparseToDense.h',['../core_2src_2_op_2_sparse_to_dense_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_sparse_to_dense_8h.html',1,'(Global Namespace)']]],
  ['sparsetodenseoptions_2ecpp_147',['SparseToDenseOptions.cpp',['../_sparse_to_dense_options_8cpp.html',1,'']]],
  ['sparsetodenseoptions_2eh_148',['SparseToDenseOptions.h',['../_sparse_to_dense_options_8h.html',1,'']]],
  ['sparsifier_2ecpp_149',['Sparsifier.cpp',['../_sparsifier_8cpp.html',1,'']]],
  ['sparsifier_2eh_150',['Sparsifier.h',['../_sparsifier_8h.html',1,'']]],
  ['sparsifytensorpass_2ecpp_151',['SparsifyTensorPass.cpp',['../_sparsify_tensor_pass_8cpp.html',1,'']]],
  ['sparsifytensorpass_2eh_152',['SparsifyTensorPass.h',['../_sparsify_tensor_pass_8h.html',1,'']]],
  ['sparsity_2eh_153',['Sparsity.h',['../_sparsity_8h.html',1,'']]],
  ['sparsityformatconverter_2ecpp_154',['SparsityFormatConverter.cpp',['../_sparsity_format_converter_8cpp.html',1,'']]],
  ['sparsityformatconverter_2eh_155',['SparsityFormatConverter.h',['../_sparsity_format_converter_8h.html',1,'']]],
  ['sparsityparam_2eh_156',['SparsityParam.h',['../_sparsity_param_8h.html',1,'']]],
  ['spatial_2eh_157',['Spatial.h',['../_spatial_8h.html',1,'']]],
  ['split_2ecc_158',['Split.cc',['../_split_8cc.html',1,'']]],
  ['split_2ecpp_159',['Split.cpp',['../compiler_2enco_2core_2src_2_transforms_2_split_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_split_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_split_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_split_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_split_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_split_8cpp.html',1,'(Global Namespace)']]],
  ['split_2eh_160',['Split.h',['../compute_2cker_2include_2cker_2operation_2_split_8h.html',1,'(Global Namespace)'],['../compiler_2enco_2core_2src_2_transforms_2_split_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_split_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_split_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_split_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_split_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_split_8h.html',1,'(Global Namespace)']]],
  ['splitlayer_2ecc_161',['SplitLayer.cc',['../_split_layer_8cc.html',1,'']]],
  ['splitlayer_2eh_162',['SplitLayer.h',['../_split_layer_8h.html',1,'']]],
  ['splitoptions_2ecpp_163',['SplitOptions.cpp',['../_split_options_8cpp.html',1,'']]],
  ['splitoptions_2eh_164',['SplitOptions.h',['../_split_options_8h.html',1,'']]],
  ['splitv_2ecc_165',['SplitV.cc',['../_split_v_8cc.html',1,'']]],
  ['splitv_2ecpp_166',['SplitV.cpp',['../compiler_2tflchef_2tflite_2src_2_op_2_split_v_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_split_v_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_split_v_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_split_v_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_split_v_8cpp.html',1,'(Global Namespace)']]],
  ['splitv_2eh_167',['SplitV.h',['../compiler_2luci-interpreter_2src_2kernels_2_split_v_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_split_v_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_split_v_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_split_v_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_split_v_8h.html',1,'(Global Namespace)']]],
  ['splitvkernel_2eh_168',['SplitVKernel.h',['../_split_v_kernel_8h.html',1,'']]],
  ['splitvlayer_2ecc_169',['SplitVLayer.cc',['../_split_v_layer_8cc.html',1,'']]],
  ['splitvlayer_2eh_170',['SplitVLayer.h',['../_split_v_layer_8h.html',1,'']]],
  ['splitvoptions_2ecpp_171',['SplitVOptions.cpp',['../_split_v_options_8cpp.html',1,'']]],
  ['splitvoptions_2eh_172',['SplitVOptions.h',['../_split_v_options_8h.html',1,'']]],
  ['sqdiff_2eh_173',['SqDiff.h',['../_sq_diff_8h.html',1,'']]],
  ['sqrt_2ecpp_174',['Sqrt.cpp',['../compiler_2moco_2import_2src_2_nodes_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_sqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_sqrt_8cpp.html',1,'(Global Namespace)']]],
  ['sqrt_2eh_175',['Sqrt.h',['../onert-micro_2luci-interpreter_2src_2kernels_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_sqrt_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_sqrt_8h.html',1,'(Global Namespace)']]],
  ['sqrtcanonicalizer_2ecpp_176',['SqrtCanonicalizer.cpp',['../_sqrt_canonicalizer_8cpp.html',1,'']]],
  ['sqrtcanonicalizer_2eh_177',['SqrtCanonicalizer.h',['../_sqrt_canonicalizer_8h.html',1,'']]],
  ['sqrtop_2eh_178',['SqrtOp.h',['../_sqrt_op_8h.html',1,'']]],
  ['square_2ecpp_179',['Square.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_square_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_square_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_square_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_square_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_square_8cpp.html',1,'(Global Namespace)']]],
  ['square_2eh_180',['Square.h',['../compiler_2luci-interpreter_2src_2kernels_2_square_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_square_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_square_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_square_8h.html',1,'(Global Namespace)']]],
  ['squareddifference_2ecc_181',['SquaredDifference.cc',['../_squared_difference_8cc.html',1,'']]],
  ['squareddifference_2ecpp_182',['SquaredDifference.cpp',['../compiler_2moco_2import_2src_2_nodes_2_squared_difference_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_squared_difference_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_squared_difference_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_squared_difference_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_squared_difference_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_squared_difference_8cpp.html',1,'(Global Namespace)']]],
  ['squareddifference_2eh_183',['SquaredDifference.h',['../runtime_2onert_2core_2include_2ir_2operation_2_squared_difference_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_squared_difference_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_squared_difference_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_squared_difference_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_squared_difference_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_squared_difference_8h.html',1,'(Global Namespace)']]],
  ['squareddifferenceoptions_2ecpp_184',['SquaredDifferenceOptions.cpp',['../_squared_difference_options_8cpp.html',1,'']]],
  ['squareddifferenceoptions_2eh_185',['SquaredDifferenceOptions.h',['../_squared_difference_options_8h.html',1,'']]],
  ['squareddifflayer_2ecc_186',['SquaredDiffLayer.cc',['../_squared_diff_layer_8cc.html',1,'']]],
  ['squareddifflayer_2eh_187',['SquaredDiffLayer.h',['../_squared_diff_layer_8h.html',1,'']]],
  ['squareoptions_2ecpp_188',['SquareOptions.cpp',['../_square_options_8cpp.html',1,'']]],
  ['squareoptions_2eh_189',['SquareOptions.h',['../_square_options_8h.html',1,'']]],
  ['squeeze_2ecc_190',['Squeeze.cc',['../_squeeze_8cc.html',1,'']]],
  ['squeeze_2ecpp_191',['Squeeze.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_squeeze_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_squeeze_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_squeeze_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_squeeze_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_squeeze_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_squeeze_8cpp.html',1,'(Global Namespace)']]],
  ['squeeze_2eh_192',['Squeeze.h',['../compiler_2tflchef_2core_2src_2_op_2_squeeze_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_squeeze_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_squeeze_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_squeeze_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_squeeze_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_squeeze_8h.html',1,'(Global Namespace)']]],
  ['squeezecanonicalizer_2ecpp_193',['SqueezeCanonicalizer.cpp',['../_squeeze_canonicalizer_8cpp.html',1,'']]],
  ['squeezecanonicalizer_2eh_194',['SqueezeCanonicalizer.h',['../_squeeze_canonicalizer_8h.html',1,'']]],
  ['squeezeop_2ecpp_195',['SqueezeOp.cpp',['../_squeeze_op_8cpp.html',1,'']]],
  ['squeezeop_2eh_196',['SqueezeOp.h',['../_squeeze_op_8h.html',1,'']]],
  ['squeezeoptions_2ecpp_197',['SqueezeOptions.cpp',['../_squeeze_options_8cpp.html',1,'']]],
  ['squeezeoptions_2eh_198',['SqueezeOptions.h',['../_squeeze_options_8h.html',1,'']]],
  ['squeezereducenode_2ecpp_199',['SqueezeReduceNode.cpp',['../_squeeze_reduce_node_8cpp.html',1,'']]],
  ['squeezereducenode_2eh_200',['SqueezeReduceNode.h',['../_squeeze_reduce_node_8h.html',1,'']]],
  ['statelessrandomuniform_2ecc_201',['StatelessRandomUniform.cc',['../_stateless_random_uniform_8cc.html',1,'']]],
  ['statelessrandomuniform_2eh_202',['StatelessRandomUniform.h',['../runtime_2onert_2core_2include_2ir_2operation_2_stateless_random_uniform_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_stateless_random_uniform_8h.html',1,'(Global Namespace)']]],
  ['statelessrandomuniformlayer_2ecc_203',['StatelessRandomUniformLayer.cc',['../_stateless_random_uniform_layer_8cc.html',1,'']]],
  ['statelessrandomuniformlayer_2eh_204',['StatelessRandomUniformLayer.h',['../_stateless_random_uniform_layer_8h.html',1,'']]],
  ['staticderivativeshapeinferer_2ecc_205',['StaticDerivativeShapeInferer.cc',['../_static_derivative_shape_inferer_8cc.html',1,'']]],
  ['staticderivativeshapeinferer_2eh_206',['StaticDerivativeShapeInferer.h',['../_static_derivative_shape_inferer_8h.html',1,'']]],
  ['staticmemorymanager_2ecpp_207',['StaticMemoryManager.cpp',['../compiler_2luci-interpreter_2src_2_static_memory_manager_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2memory__managers_2_static_memory_manager_8cpp.html',1,'(Global Namespace)']]],
  ['staticmemorymanager_2eh_208',['StaticMemoryManager.h',['../onert-micro_2luci-interpreter_2src_2memory__managers_2_static_memory_manager_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2include_2luci__interpreter_2_static_memory_manager_8h.html',1,'(Global Namespace)']]],
  ['staticshapeinferer_2ecc_209',['StaticShapeInferer.cc',['../_static_shape_inferer_8cc.html',1,'']]],
  ['staticshapeinferer_2eh_210',['StaticShapeInferer.h',['../_static_shape_inferer_8h.html',1,'']]],
  ['statictensormanager_2ecc_211',['StaticTensorManager.cc',['../_static_tensor_manager_8cc.html',1,'']]],
  ['statictensormanager_2eh_212',['StaticTensorManager.h',['../backend_2ruy_2_static_tensor_manager_8h.html',1,'(Global Namespace)'],['../backend_2cpu_2_static_tensor_manager_8h.html',1,'(Global Namespace)'],['../core_2include_2backend_2basic_2_static_tensor_manager_8h.html',1,'(Global Namespace)'],['../backend_2xnnpack_2_static_tensor_manager_8h.html',1,'(Global Namespace)']]],
  ['status_2eh_213',['Status.h',['../_status_8h.html',1,'']]],
  ['step_2ecpp_214',['Step.cpp',['../_step_8cpp.html',1,'']]],
  ['step_2eforward_2eh_215',['Step.forward.h',['../_step_8forward_8h.html',1,'']]],
  ['step_2eh_216',['Step.h',['../_step_8h.html',1,'']]],
  ['stl_5femulation_2eh_217',['stl_emulation.h',['../stl__emulation_8h.html',1,'']]],
  ['stmt_2eh_218',['Stmt.h',['../_stmt_8h.html',1,'']]],
  ['stopgradient_2ecpp_219',['StopGradient.cpp',['../_stop_gradient_8cpp.html',1,'']]],
  ['stopgradient_2eh_220',['StopGradient.h',['../_stop_gradient_8h.html',1,'']]],
  ['stopgradientcanonicalizer_2ecpp_221',['StopGradientCanonicalizer.cpp',['../_stop_gradient_canonicalizer_8cpp.html',1,'']]],
  ['stopgradientcanonicalizer_2eh_222',['StopGradientCanonicalizer.h',['../_stop_gradient_canonicalizer_8h.html',1,'']]],
  ['str_2eh_223',['str.h',['../str_8h.html',1,'']]],
  ['strcast_2ecpp_224',['strcast.cpp',['../strcast_8cpp.html',1,'']]],
  ['strcast_2eh_225',['strcast.h',['../strcast_8h.html',1,'']]],
  ['stride_2eh_226',['Stride.h',['../_stride_8h.html',1,'']]],
  ['stride2d_2ecpp_227',['Stride2D.cpp',['../_stride2_d_8cpp.html',1,'']]],
  ['stride2d_2eh_228',['Stride2D.h',['../_stride2_d_8h.html',1,'']]],
  ['stridedslice_2ecc_229',['StridedSlice.cc',['../_strided_slice_8cc.html',1,'']]],
  ['stridedslice_2ecpp_230',['StridedSlice.cpp',['../compiler_2luci-interpreter_2src_2loader_2nodes_2_strided_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_strided_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_strided_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_strided_slice_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_strided_slice_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_strided_slice_8cpp.html',1,'(Global Namespace)']]],
  ['stridedslice_2eh_231',['StridedSlice.h',['../compute_2cker_2include_2cker_2operation_2_strided_slice_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_strided_slice_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_strided_slice_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_strided_slice_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_strided_slice_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_strided_slice_8h.html',1,'(Global Namespace)']]],
  ['stridedslicekernel_2eh_232',['StridedSliceKernel.h',['../_strided_slice_kernel_8h.html',1,'']]],
  ['stridedslicelayer_2ecc_233',['StridedSliceLayer.cc',['../_strided_slice_layer_8cc.html',1,'']]],
  ['stridedslicelayer_2eh_234',['StridedSliceLayer.h',['../_strided_slice_layer_8h.html',1,'']]],
  ['stridedsliceoptions_2ecpp_235',['StridedSliceOptions.cpp',['../_strided_slice_options_8cpp.html',1,'']]],
  ['stridedsliceoptions_2eh_236',['StridedSliceOptions.h',['../_strided_slice_options_8h.html',1,'']]],
  ['strideinfo_2eh_237',['StrideInfo.h',['../_stride_info_8h.html',1,'']]],
  ['string_2eh_238',['String.h',['../_string_8h.html',1,'']]],
  ['string_5fhelpers_2eh_239',['string_helpers.h',['../string__helpers_8h.html',1,'']]],
  ['strings_2ecpp_240',['Strings.cpp',['../_strings_8cpp.html',1,'']]],
  ['strings_2eh_241',['Strings.h',['../_strings_8h.html',1,'']]],
  ['stringutils_2ecpp_242',['StringUtils.cpp',['../_string_utils_8cpp.html',1,'']]],
  ['stringutils_2eh_243',['StringUtils.h',['../_string_utils_8h.html',1,'']]],
  ['sub_2ecpp_244',['Sub.cpp',['../compiler_2mir-interpreter_2src_2ops_2_sub_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2tflite_2src_2_op_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_sub_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_sub_8cpp.html',1,'(Global Namespace)']]],
  ['sub_2efloat_2ecpp_245',['Sub.float.cpp',['../_sub_8float_8cpp.html',1,'']]],
  ['sub_2efloat_2eh_246',['Sub.float.h',['../_sub_8float_8h.html',1,'']]],
  ['sub_2eh_247',['Sub.h',['../mir-interpreter_2src_2ops_2_sub_8h.html',1,'(Global Namespace)'],['../ann-ref_2src_2ops_2_sub_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_sub_8h.html',1,'(Global Namespace)'],['../enco_2frontend_2tflite_2src_2_op_2_sub_8h.html',1,'(Global Namespace)'],['../mir_2src_2mir__onnx__importer_2_op_2_sub_8h.html',1,'(Global Namespace)'],['../moco_2import_2include_2moco_2_import_2_nodes_2_sub_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_sub_8h.html',1,'(Global Namespace)'],['../tflchef_2tflite_2src_2_op_2include_2_sub_8h.html',1,'(Global Namespace)']]],
  ['subcanonicalizer_2ecpp_248',['SubCanonicalizer.cpp',['../_sub_canonicalizer_8cpp.html',1,'']]],
  ['subcanonicalizer_2eh_249',['SubCanonicalizer.h',['../_sub_canonicalizer_8h.html',1,'']]],
  ['subnet_2ecpp_250',['Subnet.cpp',['../_subnet_8cpp.html',1,'']]],
  ['subnet_2eh_251',['Subnet.h',['../_subnet_8h.html',1,'']]],
  ['subop_2eh_252',['SubOp.h',['../_sub_op_8h.html',1,'']]],
  ['suboptions_2ecpp_253',['SubOptions.cpp',['../_sub_options_8cpp.html',1,'']]],
  ['suboptions_2eh_254',['SubOptions.h',['../_sub_options_8h.html',1,'']]],
  ['subscript_2eh_255',['Subscript.h',['../_subscript_8h.html',1,'']]],
  ['substitutepacktoreshapepass_2ecpp_256',['SubstitutePackToReshapePass.cpp',['../_substitute_pack_to_reshape_pass_8cpp.html',1,'']]],
  ['substitutepacktoreshapepass_2eh_257',['SubstitutePackToReshapePass.h',['../_substitute_pack_to_reshape_pass_8h.html',1,'']]],
  ['substitutepadv2topadpass_2ecpp_258',['SubstitutePadV2ToPadPass.cpp',['../_substitute_pad_v2_to_pad_pass_8cpp.html',1,'']]],
  ['substitutepadv2topadpass_2eh_259',['SubstitutePadV2ToPadPass.h',['../_substitute_pad_v2_to_pad_pass_8h.html',1,'']]],
  ['substitutesplitvtosplitpass_2ecpp_260',['SubstituteSplitVToSplitPass.cpp',['../_substitute_split_v_to_split_pass_8cpp.html',1,'']]],
  ['substitutesplitvtosplitpass_2eh_261',['SubstituteSplitVToSplitPass.h',['../_substitute_split_v_to_split_pass_8h.html',1,'']]],
  ['substitutesqueezetoreshapepass_2ecpp_262',['SubstituteSqueezeToReshapePass.cpp',['../_substitute_squeeze_to_reshape_pass_8cpp.html',1,'']]],
  ['substitutesqueezetoreshapepass_2eh_263',['SubstituteSqueezeToReshapePass.h',['../_substitute_squeeze_to_reshape_pass_8h.html',1,'']]],
  ['substitutestridedslicetoreshapepass_2ecpp_264',['SubstituteStridedSliceToReshapePass.cpp',['../_substitute_strided_slice_to_reshape_pass_8cpp.html',1,'']]],
  ['substitutestridedslicetoreshapepass_2eh_265',['SubstituteStridedSliceToReshapePass.h',['../_substitute_strided_slice_to_reshape_pass_8h.html',1,'']]],
  ['substitutetransposetoreshapepass_2ecpp_266',['SubstituteTransposeToReshapePass.cpp',['../_substitute_transpose_to_reshape_pass_8cpp.html',1,'']]],
  ['substitutetransposetoreshapepass_2eh_267',['SubstituteTransposeToReshapePass.h',['../_substitute_transpose_to_reshape_pass_8h.html',1,'']]],
  ['sum_2ecpp_268',['Sum.cpp',['../mir_2src_2mir__onnx__importer_2_op_2_sum_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2loader_2nodes_2_sum_8cpp.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_sum_8cpp.html',1,'(Global Namespace)'],['../tflchef_2tflite_2src_2_op_2_sum_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_sum_8cpp.html',1,'(Global Namespace)']]],
  ['sum_2eh_269',['Sum.h',['../luci-interpreter_2src_2kernels_2_sum_8h.html',1,'(Global Namespace)'],['../mir_2src_2mir__onnx__importer_2_op_2_sum_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_sum_8h.html',1,'(Global Namespace)'],['../tflchef_2tflite_2src_2_op_2include_2_sum_8h.html',1,'(Global Namespace)']]],
  ['support_2ecpp_270',['Support.cpp',['../onnxkit_2src_2_support_8cpp.html',1,'(Global Namespace)'],['../tfkit_2src_2_support_8cpp.html',1,'(Global Namespace)']]],
  ['support_2ehpp_271',['Support.hpp',['../onnxkit_2src_2_support_8hpp.html',1,'(Global Namespace)'],['../tfkit_2src_2_support_8hpp.html',1,'(Global Namespace)']]],
  ['supported_2doperations_2dbackend_2emd_272',['supported-operations-backend.md',['../supported-operations-backend_8md.html',1,'']]],
  ['supported_2doperations_2emd_273',['supported-operations.md',['../supported-operations_8md.html',1,'']]],
  ['svdf_2ecpp_274',['SVDF.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_s_v_d_f_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_s_v_d_f_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_s_v_d_f_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_s_v_d_f_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_s_v_d_f_8cpp.html',1,'(Global Namespace)']]],
  ['svdf_2eh_275',['SVDF.h',['../compiler_2luci-interpreter_2src_2kernels_2_s_v_d_f_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_s_v_d_f_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_s_v_d_f_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_s_v_d_f_8h.html',1,'(Global Namespace)']]],
  ['svdfoptions_2ecpp_276',['SVDFOptions.cpp',['../_s_v_d_f_options_8cpp.html',1,'']]],
  ['svdfoptions_2eh_277',['SVDFOptions.h',['../_s_v_d_f_options_8h.html',1,'']]],
  ['switcher_2ecpp_278',['Switcher.cpp',['../_switcher_8cpp.html',1,'']]],
  ['swizzle_2eh_279',['Swizzle.h',['../_swizzle_8h.html',1,'']]],
  ['symboltable_2eh_280',['SymbolTable.h',['../_symbol_table_8h.html',1,'']]]
];
