var searchData=
[
  ['names_2eh_0',['Names.h',['../_names_8h.html',1,'']]],
  ['nchwlayout_2ecpp_1',['NCHWLayout.cpp',['../_n_c_h_w_layout_8cpp.html',1,'']]],
  ['nchwlayout_2eh_2',['NCHWLayout.h',['../_n_c_h_w_layout_8h.html',1,'']]],
  ['ndarray_2eh_3',['NDArray.h',['../_n_d_array_8h.html',1,'']]],
  ['nebinarylogicaloperation_2ecpp_4',['NEBinaryLogicalOperation.cpp',['../_n_e_binary_logical_operation_8cpp.html',1,'']]],
  ['nebinarylogicaloperation_2eh_5',['NEBinaryLogicalOperation.h',['../_n_e_binary_logical_operation_8h.html',1,'']]],
  ['nebinarylogicaloperationkernel_2ecpp_6',['NEBinaryLogicalOperationKernel.cpp',['../_n_e_binary_logical_operation_kernel_8cpp.html',1,'']]],
  ['nebinarylogicaloperationkernel_2eh_7',['NEBinaryLogicalOperationKernel.h',['../_n_e_binary_logical_operation_kernel_8h.html',1,'']]],
  ['necastbool_2ecpp_8',['NECastBool.cpp',['../_n_e_cast_bool_8cpp.html',1,'']]],
  ['necastbool_2eh_9',['NECastBool.h',['../_n_e_cast_bool_8h.html',1,'']]],
  ['necastboolkernel_2ecpp_10',['NECastBoolKernel.cpp',['../_n_e_cast_bool_kernel_8cpp.html',1,'']]],
  ['necastboolkernel_2eh_11',['NECastBoolKernel.h',['../_n_e_cast_bool_kernel_8h.html',1,'']]],
  ['neelementwiseoperationfuncs_2ecpp_12',['NEElementwiseOperationFuncs.cpp',['../_n_e_elementwise_operation_funcs_8cpp.html',1,'']]],
  ['neelementwiseoperationfuncs_2eh_13',['NEElementwiseOperationFuncs.h',['../_n_e_elementwise_operation_funcs_8h.html',1,'']]],
  ['neembeddinglookup_2ecpp_14',['NEEmbeddingLookup.cpp',['../_n_e_embedding_lookup_8cpp.html',1,'']]],
  ['neembeddinglookup_2eh_15',['NEEmbeddingLookup.h',['../_n_e_embedding_lookup_8h.html',1,'']]],
  ['neembeddinglookupkernel_2ecpp_16',['NEEmbeddingLookupKernel.cpp',['../_n_e_embedding_lookup_kernel_8cpp.html',1,'']]],
  ['neembeddinglookupkernel_2eh_17',['NEEmbeddingLookupKernel.h',['../_n_e_embedding_lookup_kernel_8h.html',1,'']]],
  ['nefullyconnectedhybridlayer_2ecpp_18',['NEFullyConnectedHybridLayer.cpp',['../_n_e_fully_connected_hybrid_layer_8cpp.html',1,'']]],
  ['nefullyconnectedhybridlayer_2eh_19',['NEFullyConnectedHybridLayer.h',['../_n_e_fully_connected_hybrid_layer_8h.html',1,'']]],
  ['nefullyconnectedlayerex_2ecpp_20',['NEFullyConnectedLayerEx.cpp',['../_n_e_fully_connected_layer_ex_8cpp.html',1,'']]],
  ['nefullyconnectedlayerex_2eh_21',['NEFullyConnectedLayerEx.h',['../_n_e_fully_connected_layer_ex_8h.html',1,'']]],
  ['nefullyconnectedreshapinglayer_2ecpp_22',['NEFullyConnectedReshapingLayer.cpp',['../_n_e_fully_connected_reshaping_layer_8cpp.html',1,'']]],
  ['nefullyconnectedreshapinglayer_2eh_23',['NEFullyConnectedReshapingLayer.h',['../_n_e_fully_connected_reshaping_layer_8h.html',1,'']]],
  ['nefunctionsex_2ecpp_24',['NEFunctionsEx.cpp',['../_n_e_functions_ex_8cpp.html',1,'']]],
  ['nefunctionsex_2eh_25',['NEFunctionsEx.h',['../_n_e_functions_ex_8h.html',1,'']]],
  ['neg_2ecpp_26',['Neg.cpp',['../onert-micro_2luci-interpreter_2src_2loader_2nodes_2_neg_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_neg_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_neg_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_neg_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_neg_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_neg_8cpp.html',1,'(Global Namespace)']]],
  ['neg_2eh_27',['Neg.h',['../onert-micro_2luci-interpreter_2src_2kernels_2_neg_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_neg_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_neg_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_neg_8h.html',1,'(Global Namespace)']]],
  ['negatherex_2ecpp_28',['NEGatherEx.cpp',['../_n_e_gather_ex_8cpp.html',1,'']]],
  ['negatherex_2eh_29',['NEGatherEx.h',['../_n_e_gather_ex_8h.html',1,'']]],
  ['negatherkernelex_2ecpp_30',['NEGatherKernelEx.cpp',['../_n_e_gather_kernel_ex_8cpp.html',1,'']]],
  ['negatherkernelex_2eh_31',['NEGatherKernelEx.h',['../_n_e_gather_kernel_ex_8h.html',1,'']]],
  ['negemmmatrixaccumulatebiaseskernel_2ecpp_32',['NEGEMMMatrixAccumulateBiasesKernel.cpp',['../_n_e_g_e_m_m_matrix_accumulate_biases_kernel_8cpp.html',1,'']]],
  ['negemmmatrixaccumulatebiaseskernel_2eh_33',['NEGEMMMatrixAccumulateBiasesKernel.h',['../_n_e_g_e_m_m_matrix_accumulate_biases_kernel_8h.html',1,'']]],
  ['negoptions_2ecpp_34',['NegOptions.cpp',['../_neg_options_8cpp.html',1,'']]],
  ['negoptions_2eh_35',['NegOptions.h',['../_neg_options_8h.html',1,'']]],
  ['nehashtablelookup_2ecpp_36',['NEHashtableLookup.cpp',['../_n_e_hashtable_lookup_8cpp.html',1,'']]],
  ['nehashtablelookup_2eh_37',['NEHashtableLookup.h',['../_n_e_hashtable_lookup_8h.html',1,'']]],
  ['nehashtablelookupkernel_2ecpp_38',['NEHashtableLookupKernel.cpp',['../_n_e_hashtable_lookup_kernel_8cpp.html',1,'']]],
  ['nehashtablelookupkernel_2eh_39',['NEHashtableLookupKernel.h',['../_n_e_hashtable_lookup_kernel_8h.html',1,'']]],
  ['neinstancenormalizationlayerex_2ecpp_40',['NEInstanceNormalizationLayerEx.cpp',['../_n_e_instance_normalization_layer_ex_8cpp.html',1,'']]],
  ['neinstancenormalizationlayerex_2eh_41',['NEInstanceNormalizationLayerEx.h',['../_n_e_instance_normalization_layer_ex_8h.html',1,'']]],
  ['neinstancenormalizationlayerkernelex_2ecpp_42',['NEInstanceNormalizationLayerKernelEx.cpp',['../_n_e_instance_normalization_layer_kernel_ex_8cpp.html',1,'']]],
  ['neinstancenormalizationlayerkernelex_2eh_43',['NEInstanceNormalizationLayerKernelEx.h',['../_n_e_instance_normalization_layer_kernel_ex_8h.html',1,'']]],
  ['nemuliplyscalefactorkernel_2eh_44',['NEMuliplyScaleFactorKernel.h',['../_n_e_muliply_scale_factor_kernel_8h.html',1,'']]],
  ['nemultiplyscalefactorkernel_2ecpp_45',['NEMultiplyScaleFactorKernel.cpp',['../_n_e_multiply_scale_factor_kernel_8cpp.html',1,'']]],
  ['neon_5fcheck_2eh_46',['neon_check.h',['../cker_2include_2cker_2neon_2neon__check_8h.html',1,'(Global Namespace)'],['../ruy_2include_2ruy_2neon_2neon__check_8h.html',1,'(Global Namespace)']]],
  ['neonehot_2ecpp_47',['NEOneHot.cpp',['../_n_e_one_hot_8cpp.html',1,'']]],
  ['neonehot_2eh_48',['NEOneHot.h',['../_n_e_one_hot_8h.html',1,'']]],
  ['neonehotkernel_2ecpp_49',['NEOneHotKernel.cpp',['../_n_e_one_hot_kernel_8cpp.html',1,'']]],
  ['neonehotkernel_2eh_50',['NEOneHotKernel.h',['../_n_e_one_hot_kernel_8h.html',1,'']]],
  ['neontensorutils_2eh_51',['NeonTensorUtils.h',['../cker_2include_2cker_2_neon_tensor_utils_8h.html',1,'(Global Namespace)'],['../ruy_2include_2ruy_2_neon_tensor_utils_8h.html',1,'(Global Namespace)']]],
  ['nequantizationsymmetrickernel_2ecpp_52',['NEQuantizationSymmetricKernel.cpp',['../_n_e_quantization_symmetric_kernel_8cpp.html',1,'']]],
  ['nequantizationsymmetrickernel_2eh_53',['NEQuantizationSymmetricKernel.h',['../_n_e_quantization_symmetric_kernel_8h.html',1,'']]],
  ['nereduceoperation_2ecpp_54',['NEReduceOperation.cpp',['../_n_e_reduce_operation_8cpp.html',1,'']]],
  ['nereduceoperation_2eh_55',['NEReduceOperation.h',['../_n_e_reduce_operation_8h.html',1,'']]],
  ['nereducesum_2ecpp_56',['NEReduceSum.cpp',['../_n_e_reduce_sum_8cpp.html',1,'']]],
  ['nereducesum_2eh_57',['NEReduceSum.h',['../_n_e_reduce_sum_8h.html',1,'']]],
  ['nesubtensor_2ecc_58',['NESubTensor.cc',['../_n_e_sub_tensor_8cc.html',1,'']]],
  ['nesubtensor_2eh_59',['NESubTensor.h',['../_n_e_sub_tensor_8h.html',1,'']]],
  ['netensor_2ecc_60',['NETensor.cc',['../_n_e_tensor_8cc.html',1,'']]],
  ['netensor_2eh_61',['NETensor.h',['../_n_e_tensor_8h.html',1,'']]],
  ['netransposeconvlayer_2ecpp_62',['NETransposeConvLayer.cpp',['../_n_e_transpose_conv_layer_8cpp.html',1,'']]],
  ['netransposeconvlayer_2eh_63',['NETransposeConvLayer.h',['../_n_e_transpose_conv_layer_8h.html',1,'']]],
  ['neuralnetworks_2ecpp_64',['NeuralNetworks.cpp',['../_neural_networks_8cpp.html',1,'']]],
  ['neuralnetworks_2eh_65',['NeuralNetworks.h',['../compiler_2ann-api_2include_2_neural_networks_8h.html',1,'(Global Namespace)'],['../runtime_2nnapi-header_2include_2_neural_networks_8h.html',1,'(Global Namespace)']]],
  ['neuralnetworksex_2eh_66',['NeuralNetworksEx.h',['../_neural_networks_ex_8h.html',1,'']]],
  ['neuralnetworksexshim_2eh_67',['NeuralNetworksExShim.h',['../_neural_networks_ex_shim_8h.html',1,'']]],
  ['neuralnetworksextensions_2eh_68',['NeuralNetworksExtensions.h',['../_neural_networks_extensions_8h.html',1,'']]],
  ['neuralnetworksloadhelpers_2eh_69',['NeuralNetworksLoadHelpers.h',['../_neural_networks_load_helpers_8h.html',1,'']]],
  ['neuralnetworksshim_2eh_70',['NeuralNetworksShim.h',['../_neural_networks_shim_8h.html',1,'']]],
  ['neuralnetworkstypes_2eh_71',['NeuralNetworksTypes.h',['../_neural_networks_types_8h.html',1,'']]],
  ['nhwclayout_2ecpp_72',['NHWCLayout.cpp',['../_n_h_w_c_layout_8cpp.html',1,'']]],
  ['nhwclayout_2eh_73',['NHWCLayout.h',['../_n_h_w_c_layout_8h.html',1,'']]],
  ['nnapi_2ecpp_74',['nnapi.cpp',['../nnapi_8cpp.html',1,'']]],
  ['nnapi_2eh_75',['nnapi.h',['../nnapi_8h.html',1,'']]],
  ['nnapiconvert_2ecc_76',['NNAPIConvert.cc',['../_n_n_a_p_i_convert_8cc.html',1,'']]],
  ['nnapiconvert_2eh_77',['NNAPIConvert.h',['../_n_n_a_p_i_convert_8h.html',1,'']]],
  ['nnfw_2eh_78',['nnfw.h',['../nnfw_8h.html',1,'']]],
  ['nnfw_5fapi_2ecc_79',['nnfw_api.cc',['../nnfw__api_8cc.html',1,'']]],
  ['nnfw_5fapi_5finternal_2ecc_80',['nnfw_api_internal.cc',['../nnfw__api__internal_8cc.html',1,'']]],
  ['nnfw_5fapi_5finternal_2eh_81',['nnfw_api_internal.h',['../nnfw__api__internal_8h.html',1,'']]],
  ['nnfw_5fdebug_2ecc_82',['nnfw_debug.cc',['../nnfw__debug_8cc.html',1,'']]],
  ['nnfw_5fexperimental_2eh_83',['nnfw_experimental.h',['../nnfw__experimental_8h.html',1,'']]],
  ['nnfw_5finternal_2eh_84',['nnfw_internal.h',['../nnfw__internal_8h.html',1,'']]],
  ['nnfw_5fversion_2eh_85',['nnfw_version.h',['../nnfw__version_8h.html',1,'']]],
  ['nnkit_2drun_2ecpp_86',['nnkit-run.cpp',['../nnkit-run_8cpp.html',1,'']]],
  ['nnpkg_2eh_87',['NNPkg.h',['../_n_n_pkg_8h.html',1,'']]],
  ['node_2ecc_88',['Node.cc',['../_node_8cc.html',1,'']]],
  ['node_2ecpp_89',['Node.cpp',['../loco_2src_2_i_r_2_node_8cpp.html',1,'(Global Namespace)'],['../nest_2core_2src_2expr_2_node_8cpp.html',1,'(Global Namespace)'],['../nest_2core_2src_2stmt_2_node_8cpp.html',1,'(Global Namespace)']]],
  ['node_2eforward_2eh_90',['Node.forward.h',['../_node_8forward_8h.html',1,'']]],
  ['node_2eh_91',['Node.h',['../compiler_2loco_2include_2loco_2_i_r_2_node_8h.html',1,'(Global Namespace)'],['../compiler_2nest_2core_2include_2nest_2expr_2_node_8h.html',1,'(Global Namespace)'],['../compiler_2nest_2core_2include_2nest_2stmt_2_node_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2dumper_2dot_2_node_8h.html',1,'(Global Namespace)']]],
  ['nodeas_2eh_92',['NodeAs.h',['../_node_as_8h.html',1,'']]],
  ['nodebuilder_2eh_93',['NodeBuilder.h',['../_node_builder_8h.html',1,'']]],
  ['nodedata_2ecpp_94',['NodeData.cpp',['../_node_data_8cpp.html',1,'']]],
  ['nodedata_2eh_95',['NodeData.h',['../_node_data_8h.html',1,'']]],
  ['nodedataimpl_2ecpp_96',['NodeDataImpl.cpp',['../_node_data_impl_8cpp.html',1,'']]],
  ['nodedataimpl_2eh_97',['NodeDataImpl.h',['../_node_data_impl_8h.html',1,'']]],
  ['nodedomain_2ecpp_98',['NodeDomain.cpp',['../_node_domain_8cpp.html',1,'']]],
  ['nodedomain_2eh_99',['NodeDomain.h',['../_node_domain_8h.html',1,'']]],
  ['nodeexecution_2ecpp_100',['NodeExecution.cpp',['../_node_execution_8cpp.html',1,'']]],
  ['nodeexecution_2eh_101',['NodeExecution.h',['../_node_execution_8h.html',1,'']]],
  ['nodefiller_2ecpp_102',['NodeFiller.cpp',['../_node_filler_8cpp.html',1,'']]],
  ['nodefiller_2eh_103',['NodeFiller.h',['../_node_filler_8h.html',1,'']]],
  ['nodemixins_2ecpp_104',['NodeMixins.cpp',['../loco_2src_2_i_r_2_node_mixins_8cpp.html',1,'(Global Namespace)'],['../exo_2src_2_dialect_2_i_r_2_node_mixins_8cpp.html',1,'(Global Namespace)']]],
  ['nodemixins_2eh_105',['NodeMixins.h',['../exo_2src_2_dialect_2_i_r_2_node_mixins_8h.html',1,'(Global Namespace)'],['../loco_2include_2loco_2_i_r_2_node_mixins_8h.html',1,'(Global Namespace)']]],
  ['nodepool_2ecpp_106',['NodePool.cpp',['../_node_pool_8cpp.html',1,'']]],
  ['nodepool_2eforward_2eh_107',['NodePool.forward.h',['../_node_pool_8forward_8h.html',1,'']]],
  ['nodepool_2eh_108',['NodePool.h',['../_node_pool_8h.html',1,'']]],
  ['nodereplacer_2ecpp_109',['NodeReplacer.cpp',['../_node_replacer_8cpp.html',1,'']]],
  ['nodes_2ecpp_110',['Nodes.cpp',['../_nodes_8cpp.html',1,'']]],
  ['nodes_2eh_111',['Nodes.h',['../loco_2include_2loco_2_i_r_2_nodes_8h.html',1,'(Global Namespace)'],['../luci_2import_2include_2luci_2_import_2_nodes_8h.html',1,'(Global Namespace)'],['../moco_2import_2include_2moco_2_import_2_nodes_8h.html',1,'(Global Namespace)']]],
  ['nodeshape_2ecpp_112',['NodeShape.cpp',['../_node_shape_8cpp.html',1,'']]],
  ['nodeshape_2eh_113',['NodeShape.h',['../_node_shape_8h.html',1,'']]],
  ['nodesummary_2ecpp_114',['NodeSummary.cpp',['../_node_summary_8cpp.html',1,'']]],
  ['nodesummary_2eh_115',['NodeSummary.h',['../_node_summary_8h.html',1,'']]],
  ['nodesummarybuilder_2ecpp_116',['NodeSummaryBuilder.cpp',['../_node_summary_builder_8cpp.html',1,'']]],
  ['nodesummarybuilder_2eh_117',['NodeSummaryBuilder.h',['../_node_summary_builder_8h.html',1,'']]],
  ['nonincreasingstride_2ecpp_118',['NonIncreasingStride.cpp',['../_non_increasing_stride_8cpp.html',1,'']]],
  ['nonincreasingstride_2eh_119',['NonIncreasingStride.h',['../_non_increasing_stride_8h.html',1,'']]],
  ['nonmaxsuppressionv4_2ecpp_120',['NonMaxSuppressionV4.cpp',['../tflite_2src_2_op_2_non_max_suppression_v4_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_non_max_suppression_v4_8cpp.html',1,'(Global Namespace)']]],
  ['nonmaxsuppressionv4_2eh_121',['NonMaxSuppressionV4.h',['../core_2src_2_op_2_non_max_suppression_v4_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_non_max_suppression_v4_8h.html',1,'(Global Namespace)']]],
  ['nonmaxsuppressionv4options_2ecpp_122',['NonMaxSuppressionV4Options.cpp',['../_non_max_suppression_v4_options_8cpp.html',1,'']]],
  ['nonmaxsuppressionv4options_2eh_123',['NonMaxSuppressionV4Options.h',['../_non_max_suppression_v4_options_8h.html',1,'']]],
  ['nonmaxsuppressionv5_2ecpp_124',['NonMaxSuppressionV5.cpp',['../tflite_2src_2_op_2_non_max_suppression_v5_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_non_max_suppression_v5_8cpp.html',1,'(Global Namespace)']]],
  ['nonmaxsuppressionv5_2eh_125',['NonMaxSuppressionV5.h',['../core_2src_2_op_2_non_max_suppression_v5_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_non_max_suppression_v5_8h.html',1,'(Global Namespace)']]],
  ['nonmaxsuppressionv5options_2ecpp_126',['NonMaxSuppressionV5Options.cpp',['../_non_max_suppression_v5_options_8cpp.html',1,'']]],
  ['nonmaxsuppressionv5options_2eh_127',['NonMaxSuppressionV5Options.h',['../_non_max_suppression_v5_options_8h.html',1,'']]],
  ['nopfunction_2eh_128',['NopFunction.h',['../_nop_function_8h.html',1,'']]],
  ['notequal_2ecpp_129',['NotEqual.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_not_equal_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2loader_2nodes_2_not_equal_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_not_equal_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_not_equal_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_not_equal_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_not_equal_8cpp.html',1,'(Global Namespace)']]],
  ['notequal_2eh_130',['NotEqual.h',['../compiler_2tflchef_2tflite_2src_2_op_2include_2_not_equal_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_not_equal_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_not_equal_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_not_equal_8h.html',1,'(Global Namespace)']]],
  ['notequaloptions_2ecpp_131',['NotEqualOptions.cpp',['../_not_equal_options_8cpp.html',1,'']]],
  ['notequaloptions_2eh_132',['NotEqualOptions.h',['../_not_equal_options_8h.html',1,'']]]
];
