var searchData=
[
  ['object_2ecpp_0',['Object.cpp',['../_object_8cpp.html',1,'']]],
  ['object_2eforward_2eh_1',['Object.forward.h',['../_object_8forward_8h.html',1,'']]],
  ['object_2eh_2',['Object.h',['../runtime_2libs_2misc_2include_2misc_2vector_2_object_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2tensor_2_object_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2feature_2_object_8h.html',1,'(Global Namespace)'],['../compiler_2coco_2core_2include_2coco_2_i_r_2_object_8h.html',1,'(Global Namespace)']]],
  ['objectmanager_2ecpp_3',['ObjectManager.cpp',['../_object_manager_8cpp.html',1,'']]],
  ['objectmanager_2eh_4',['ObjectManager.h',['../runtime_2onert_2core_2include_2util_2_object_manager_8h.html',1,'(Global Namespace)'],['../compiler_2coco_2core_2include_2coco_2_i_r_2_object_manager_8h.html',1,'(Global Namespace)']]],
  ['objectpool_2ecpp_5',['ObjectPool.cpp',['../_object_pool_8cpp.html',1,'']]],
  ['objectpool_2eh_6',['ObjectPool.h',['../_object_pool_8h.html',1,'']]],
  ['objectset_2eh_7',['ObjectSet.h',['../_object_set_8h.html',1,'']]],
  ['oddoutputpass_2ecc_8',['OddOutputPass.cc',['../_odd_output_pass_8cc.html',1,'']]],
  ['oddoutputpass_2eh_9',['OddOutputPass.h',['../_odd_output_pass_8h.html',1,'']]],
  ['onehot_2ecc_10',['OneHot.cc',['../_one_hot_8cc.html',1,'']]],
  ['onehot_2ecpp_11',['OneHot.cpp',['../compiler_2tflchef_2tflite_2src_2_op_2_one_hot_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2loader_2nodes_2_one_hot_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_one_hot_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_one_hot_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_one_hot_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_one_hot_8cpp.html',1,'(Global Namespace)']]],
  ['onehot_2eh_12',['OneHot.h',['../compiler_2tflchef_2core_2src_2_op_2_one_hot_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_one_hot_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_one_hot_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_one_hot_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_one_hot_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_one_hot_8h.html',1,'(Global Namespace)']]],
  ['onehotlayer_2ecc_13',['OneHotLayer.cc',['../_one_hot_layer_8cc.html',1,'']]],
  ['onehotlayer_2eh_14',['OneHotLayer.h',['../_one_hot_layer_8h.html',1,'']]],
  ['onehotoptions_2ecpp_15',['OneHotOptions.cpp',['../_one_hot_options_8cpp.html',1,'']]],
  ['onehotoptions_2eh_16',['OneHotOptions.h',['../_one_hot_options_8h.html',1,'']]],
  ['onnx_2ddump_2epy_17',['onnx-dump.py',['../onnx-dump_8py.html',1,'']]],
  ['onnx_2dops_2epy_18',['onnx-ops.py',['../onnx-ops_8py.html',1,'']]],
  ['onnx2circle_2ecpp_19',['onnx2circle.cpp',['../onnx2circle_8cpp.html',1,'']]],
  ['onnx_5flegalizer_2epy_20',['onnx_legalizer.py',['../onnx__legalizer_8py.html',1,'']]],
  ['onnxhelpers_2ecpp_21',['ONNXHelpers.cpp',['../_o_n_n_x_helpers_8cpp.html',1,'']]],
  ['onnxhelpers_2eh_22',['ONNXHelpers.h',['../_o_n_n_x_helpers_8h.html',1,'']]],
  ['onnximporterimpl_2ecpp_23',['ONNXImporterImpl.cpp',['../_o_n_n_x_importer_impl_8cpp.html',1,'']]],
  ['onnximporterimpl_2eh_24',['ONNXImporterImpl.h',['../_o_n_n_x_importer_impl_8h.html',1,'']]],
  ['onnxnodeconverterregistry_2ecpp_25',['ONNXNodeConverterRegistry.cpp',['../_o_n_n_x_node_converter_registry_8cpp.html',1,'']]],
  ['onnxnodeconverterregistry_2eh_26',['ONNXNodeConverterRegistry.h',['../_o_n_n_x_node_converter_registry_8h.html',1,'']]],
  ['onnxopregistration_2eh_27',['ONNXOpRegistration.h',['../_o_n_n_x_op_registration_8h.html',1,'']]],
  ['onnxutil_2ecpp_28',['Onnxutil.cpp',['../_onnxutil_8cpp.html',1,'']]],
  ['onnxutil_2eh_29',['Onnxutil.h',['../_onnxutil_8h.html',1,'']]],
  ['op_2ecpp_30',['Op.cpp',['../_op_8cpp.html',1,'']]],
  ['op_2eforward_2eh_31',['Op.forward.h',['../_op_8forward_8h.html',1,'']]],
  ['op_2eh_32',['Op.h',['../_op_8h.html',1,'']]],
  ['opchef_2eh_33',['OpChef.h',['../tflchef_2core_2src_2_op_chef_8h.html',1,'(Global Namespace)'],['../circlechef_2core_2src_2_op_chef_8h.html',1,'(Global Namespace)']]],
  ['opchefs_2eh_34',['OpChefs.h',['../circlechef_2core_2src_2_op_chefs_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_chefs_8h.html',1,'(Global Namespace)']]],
  ['opcode_2ecc_35',['OpCode.cc',['../_op_code_8cc.html',1,'']]],
  ['opcode_2eh_36',['OpCode.h',['../_op_code_8h.html',1,'']]],
  ['opdefs_2eh_37',['OpDefs.h',['../_op_defs_8h.html',1,'']]],
  ['operand_2ecc_38',['Operand.cc',['../_operand_8cc.html',1,'']]],
  ['operand_2eh_39',['Operand.h',['../compiler_2enco_2core_2src_2_a_n_n_2_i_r_2_operand_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2_operand_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2_operand_8h.html',1,'(Global Namespace)']]],
  ['operandconstraint_2eh_40',['OperandConstraint.h',['../_operand_constraint_8h.html',1,'']]],
  ['operandid_2eh_41',['OperandID.h',['../_operand_i_d_8h.html',1,'']]],
  ['operandindexmap_2eh_42',['OperandIndexMap.h',['../_operand_index_map_8h.html',1,'']]],
  ['operandindexsequence_2ecc_43',['OperandIndexSequence.cc',['../_operand_index_sequence_8cc.html',1,'']]],
  ['operandindexsequence_2eh_44',['OperandIndexSequence.h',['../_operand_index_sequence_8h.html',1,'']]],
  ['operandinfo_2eh_45',['OperandInfo.h',['../_operand_info_8h.html',1,'']]],
  ['operandinventory_2ecpp_46',['OperandInventory.cpp',['../_operand_inventory_8cpp.html',1,'']]],
  ['operandinventory_2eh_47',['OperandInventory.h',['../_operand_inventory_8h.html',1,'']]],
  ['operandlowerinfo_2eh_48',['OperandLowerInfo.h',['../_operand_lower_info_8h.html',1,'']]],
  ['operandnode_2ecc_49',['OperandNode.cc',['../_operand_node_8cc.html',1,'']]],
  ['operandnode_2eh_50',['OperandNode.h',['../_operand_node_8h.html',1,'']]],
  ['operandpass_2ecc_51',['OperandPass.cc',['../_operand_pass_8cc.html',1,'']]],
  ['operandpass_2eh_52',['OperandPass.h',['../_operand_pass_8h.html',1,'']]],
  ['operands_2ecc_53',['Operands.cc',['../_operands_8cc.html',1,'']]],
  ['operands_2eh_54',['Operands.h',['../_operands_8h.html',1,'']]],
  ['operandtype_2ecpp_55',['OperandType.cpp',['../_operand_type_8cpp.html',1,'']]],
  ['operandtype_2eh_56',['OperandType.h',['../_operand_type_8h.html',1,'']]],
  ['operandtype_2eprobe_2ecpp_57',['OperandType.probe.cpp',['../_operand_type_8probe_8cpp.html',1,'']]],
  ['operation_2ecc_58',['Operation.cc',['../_operation_8cc.html',1,'']]],
  ['operation_2ecpp_59',['Operation.cpp',['../src_2_operation_8cpp.html',1,'(Global Namespace)'],['../unittests_2_operation_8cpp.html',1,'(Global Namespace)']]],
  ['operation_2eh_60',['Operation.h',['../compiler_2mir_2include_2mir_2_operation_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2_operation_8h.html',1,'(Global Namespace)'],['../compiler_2enco_2core_2src_2_a_n_n_2_i_r_2_operation_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2_operation_8h.html',1,'(Global Namespace)']]],
  ['operationcloner_2ecc_61',['OperationCloner.cc',['../_operation_cloner_8cc.html',1,'']]],
  ['operationcloner_2eh_62',['OperationCloner.h',['../_operation_cloner_8h.html',1,'']]],
  ['operationdumper_2ecc_63',['OperationDumper.cc',['../_operation_dumper_8cc.html',1,'']]],
  ['operationdumper_2eh_64',['OperationDumper.h',['../_operation_dumper_8h.html',1,'']]],
  ['operationfactory_2ecc_65',['OperationFactory.cc',['../_operation_factory_8cc.html',1,'']]],
  ['operationfactory_2eh_66',['OperationFactory.h',['../_operation_factory_8h.html',1,'']]],
  ['operationindexmap_2eh_67',['OperationIndexMap.h',['../_operation_index_map_8h.html',1,'']]],
  ['operationindexset_2ecc_68',['OperationIndexSet.cc',['../_operation_index_set_8cc.html',1,'']]],
  ['operationindexset_2eh_69',['OperationIndexSet.h',['../_operation_index_set_8h.html',1,'']]],
  ['operationinventory_2ecpp_70',['OperationInventory.cpp',['../_operation_inventory_8cpp.html',1,'']]],
  ['operationinventory_2eh_71',['OperationInventory.h',['../_operation_inventory_8h.html',1,'']]],
  ['operationlowerinfo_2ecc_72',['OperationLowerInfo.cc',['../_operation_lower_info_8cc.html',1,'']]],
  ['operationlowerinfo_2eh_73',['OperationLowerInfo.h',['../_operation_lower_info_8h.html',1,'']]],
  ['operationnode_2ecc_74',['OperationNode.cc',['../_operation_node_8cc.html',1,'']]],
  ['operationnode_2eh_75',['OperationNode.h',['../_operation_node_8h.html',1,'']]],
  ['operationpass_2ecc_76',['OperationPass.cc',['../_operation_pass_8cc.html',1,'']]],
  ['operationpass_2eh_77',['OperationPass.h',['../_operation_pass_8h.html',1,'']]],
  ['operations_2ecc_78',['Operations.cc',['../_operations_8cc.html',1,'']]],
  ['operations_2eh_79',['Operations.h',['../_operations_8h.html',1,'']]],
  ['operations_2einc_80',['Operations.inc',['../_operations_8inc.html',1,'']]],
  ['operations_2einclude_2eh_81',['Operations.Include.h',['../_operations_8_include_8h.html',1,'']]],
  ['operationtype_2ecpp_82',['OperationType.cpp',['../_operation_type_8cpp.html',1,'']]],
  ['operationtype_2eh_83',['OperationType.h',['../_operation_type_8h.html',1,'']]],
  ['operationtype_2eprobe_2ecpp_84',['OperationType.probe.cpp',['../_operation_type_8probe_8cpp.html',1,'']]],
  ['operationutil_2eh_85',['OperationUtil.h',['../_operation_util_8h.html',1,'']]],
  ['operationutils_2ecc_86',['OperationUtils.cc',['../cpu_2ops_2_operation_utils_8cc.html',1,'(Global Namespace)'],['../ruy_2ops_2_operation_utils_8cc.html',1,'(Global Namespace)']]],
  ['operationutils_2eh_87',['OperationUtils.h',['../cpu_2ops_2_operation_utils_8h.html',1,'(Global Namespace)'],['../ruy_2ops_2_operation_utils_8h.html',1,'(Global Namespace)'],['../xnnpack_2ops_2_operation_utils_8h.html',1,'(Global Namespace)']]],
  ['operationvalidator_2ecc_88',['OperationValidator.cc',['../_operation_validator_8cc.html',1,'']]],
  ['operationvalidator_2eh_89',['OperationValidator.h',['../_operation_validator_8h.html',1,'']]],
  ['operationvisitor_2eh_90',['OperationVisitor.h',['../_operation_visitor_8h.html',1,'']]],
  ['opmanager_2ecpp_91',['OpManager.cpp',['../_op_manager_8cpp.html',1,'']]],
  ['opmanager_2eh_92',['OpManager.h',['../_op_manager_8h.html',1,'']]],
  ['opprinter_2ecpp_93',['OpPrinter.cpp',['../circledump_2src_2_op_printer_8cpp.html',1,'(Global Namespace)'],['../tfldump_2src_2_op_printer_8cpp.html',1,'(Global Namespace)']]],
  ['opprinter_2eh_94',['OpPrinter.h',['../tfldump_2src_2_op_printer_8h.html',1,'(Global Namespace)'],['../circledump_2src_2_op_printer_8h.html',1,'(Global Namespace)']]],
  ['ops_2ecpp_95',['Ops.cpp',['../_ops_8cpp.html',1,'']]],
  ['ops_2eh_96',['Ops.h',['../_ops_8h.html',1,'']]],
  ['opselector_2ecpp_97',['OpSelector.cpp',['../_op_selector_8cpp.html',1,'']]],
  ['opselector_2eh_98',['OpSelector.h',['../_op_selector_8h.html',1,'']]],
  ['optimizations_2ecpp_99',['Optimizations.cpp',['../_optimizations_8cpp.html',1,'']]],
  ['optimizations_2eh_100',['Optimizations.h',['../_optimizations_8h.html',1,'']]],
  ['optimizationutils_2ecpp_101',['OptimizationUtils.cpp',['../_optimization_utils_8cpp.html',1,'']]],
  ['optimizationutils_2eh_102',['OptimizationUtils.h',['../_optimization_utils_8h.html',1,'']]],
  ['optimize_2ecpp_103',['Optimize.cpp',['../_optimize_8cpp.html',1,'']]],
  ['optimize_2eh_104',['Optimize.h',['../_optimize_8h.html',1,'']]],
  ['optimizedutils_2eh_105',['OptimizedUtils.h',['../_optimized_utils_8h.html',1,'']]],
  ['optimizer_2ecc_106',['Optimizer.cc',['../acl__neon_2_optimizer_8cc.html',1,'(Global Namespace)'],['../acl__cl_2_optimizer_8cc.html',1,'(Global Namespace)']]],
  ['optimizer_2ecpp_107',['Optimizer.cpp',['../_optimizer_8cpp.html',1,'']]],
  ['optimizer_2eh_108',['Optimizer.h',['../runtime_2onert_2backend_2acl__neon_2_optimizer_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2acl__cl_2_optimizer_8h.html',1,'(Global Namespace)'],['../compiler_2moco-tf_2src_2_optimizer_8h.html',1,'(Global Namespace)']]],
  ['optionbuilder_2epy_109',['OptionBuilder.py',['../_option_builder_8py.html',1,'']]],
  ['options_2ecpp_110',['Options.cpp',['../_options_8cpp.html',1,'']]],
  ['options_2eh_111',['Options.h',['../_options_8h.html',1,'']]],
  ['output_2ecpp_112',['Output.cpp',['../_output_8cpp.html',1,'']]],
  ['output_2eforward_2eh_113',['Output.forward.h',['../_output_8forward_8h.html',1,'']]],
  ['output_2eh_114',['Output.h',['../_output_8h.html',1,'']]],
  ['outputblobcontext_2eh_115',['OutputBlobContext.h',['../_output_blob_context_8h.html',1,'']]],
  ['outputlist_2eh_116',['OutputList.h',['../coco_2core_2include_2coco_2_i_r_2_output_list_8h.html',1,'(Global Namespace)'],['../enco_2core_2src_2_a_n_n_2_i_r_2_output_list_8h.html',1,'(Global Namespace)']]],
  ['outputmanager_2ecpp_117',['OutputManager.cpp',['../_output_manager_8cpp.html',1,'']]],
  ['outputmanager_2eh_118',['OutputManager.h',['../_output_manager_8h.html',1,'']]],
  ['outputop_2eh_119',['OutputOp.h',['../_output_op_8h.html',1,'']]],
  ['outputtensorcontext_2ecpp_120',['OutputTensorContext.cpp',['../_output_tensor_context_8cpp.html',1,'']]],
  ['outputtensorcontext_2eh_121',['OutputTensorContext.h',['../_output_tensor_context_8h.html',1,'']]],
  ['overall_2darchitecture_2emd_122',['overall-architecture.md',['../overall-architecture_8md.html',1,'']]],
  ['overlay_2eh_123',['Overlay.h',['../feature_2_overlay_8h.html',1,'(Global Namespace)'],['../tensor_2_overlay_8h.html',1,'(Global Namespace)'],['../kernel_2_overlay_8h.html',1,'(Global Namespace)']]]
];
