var searchData=
[
  ['tanh_2ecpp_0',['tanh.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_tanh_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2import_2kernels_2_tanh_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2execute_2kernels_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2locomotiv_2src_2_node_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_tanh_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_tanh_8cpp.html',1,'(Global Namespace)']]],
  ['tanh_2eh_1',['tanh.h',['../compiler_2mir-interpreter_2src_2ops_2_tanh_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_tanh_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_tanh_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_tanh_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_tanh_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_tanh_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_tanh_8h.html',1,'(Global Namespace)']]],
  ['tanhcanonicalizer_2ecpp_2',['TanhCanonicalizer.cpp',['../_tanh_canonicalizer_8cpp.html',1,'']]],
  ['tanhcanonicalizer_2eh_3',['TanhCanonicalizer.h',['../_tanh_canonicalizer_8h.html',1,'']]],
  ['tanhop_2eh_4',['TanhOp.h',['../_tanh_op_8h.html',1,'']]],
  ['targetplatform_2eh_5',['TargetPlatform.h',['../_target_platform_8h.html',1,'']]],
  ['tensor_2ecc_6',['Tensor.cc',['../_tensor_8cc.html',1,'']]],
  ['tensor_2ecpp_7',['tensor.cpp',['../luci-interpreter_2src_2core_2_tensor_8cpp.html',1,'(Global Namespace)'],['../circle-eval-diff_2src_2_tensor_8cpp.html',1,'(Global Namespace)'],['../mir_2src_2_tensor_8cpp.html',1,'(Global Namespace)']]],
  ['tensor_2eh_8',['tensor.h',['../runtime_2onert_2core_2include_2backend_2basic_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2trix_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2train_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2ruy_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2cpu_2_tensor_8h.html',1,'(Global Namespace)'],['../compiler_2circle-eval-diff_2src_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_helper_2_tensor_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2include_2luci__interpreter_2core_2_tensor_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2include_2mir_2_tensor_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2include_2luci__interpreter_2core_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2backend_2builtin_2_tensor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2backend_2builtin_2train_2_tensor_8h.html',1,'(Global Namespace)']]],
  ['tensor_5fgen_2ecpp_9',['tensor_gen.cpp',['../tensor__gen_8cpp.html',1,'']]],
  ['tensoraxis_2ecpp_10',['TensorAxis.cpp',['../_tensor_axis_8cpp.html',1,'']]],
  ['tensoraxis_2eh_11',['TensorAxis.h',['../_tensor_axis_8h.html',1,'']]],
  ['tensoraxisset_2ecpp_12',['TensorAxisSet.cpp',['../_tensor_axis_set_8cpp.html',1,'']]],
  ['tensoraxisset_2eh_13',['TensorAxisSet.h',['../_tensor_axis_set_8h.html',1,'']]],
  ['tensorbags_2eh_14',['TensorBags.h',['../_tensor_bags_8h.html',1,'']]],
  ['tensorbroadcast_2ecpp_15',['TensorBroadcast.cpp',['../_tensor_broadcast_8cpp.html',1,'']]],
  ['tensorbroadcastconverter_2ecpp_16',['TensorBroadcastConverter.cpp',['../_tensor_broadcast_converter_8cpp.html',1,'']]],
  ['tensorbroadcastconverter_2eh_17',['TensorBroadcastConverter.h',['../_tensor_broadcast_converter_8h.html',1,'']]],
  ['tensorbuilder_2ecc_18',['tensorbuilder.cc',['../core_2src_2backend_2builtin_2_tensor_builder_8cc.html',1,'(Global Namespace)'],['../backend_2train_2_tensor_builder_8cc.html',1,'(Global Namespace)'],['../core_2src_2backend_2basic_2_tensor_builder_8cc.html',1,'(Global Namespace)']]],
  ['tensorbuilder_2eh_19',['tensorbuilder.h',['../backend_2ruy_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../backend_2acl__neon_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../backend_2acl__cl_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../backend_2train_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../backend_2trix_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../core_2include_2backend_2basic_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2_tensor_builder_8h.html',1,'(Global Namespace)'],['../backend_2cpu_2_tensor_builder_8h.html',1,'(Global Namespace)']]],
  ['tensorconcat_2ecpp_20',['TensorConcat.cpp',['../_tensor_concat_8cpp.html',1,'']]],
  ['tensorconcatconverter_2ecpp_21',['TensorConcatConverter.cpp',['../_tensor_concat_converter_8cpp.html',1,'']]],
  ['tensorconcatconverter_2eh_22',['TensorConcatConverter.h',['../_tensor_concat_converter_8h.html',1,'']]],
  ['tensorconstantpad_2ecpp_23',['TensorConstantPad.cpp',['../_tensor_constant_pad_8cpp.html',1,'']]],
  ['tensorcontext_2ecpp_24',['tensorcontext.cpp',['../ite_2support_2src_2_tensor_context_8cpp.html',1,'(Global Namespace)'],['../support_2src_2_tensor_context_8cpp.html',1,'(Global Namespace)']]],
  ['tensorcontext_2eh_25',['tensorcontext.h',['../nnkit-tflite_2support_2include_2nnkit_2support_2tflite_2_tensor_context_8h.html',1,'(Global Namespace)'],['../nnkit-tf_2support_2include_2nnkit_2support_2tf_2_tensor_context_8h.html',1,'(Global Namespace)'],['../nnkit-onnxrt_2support_2include_2nnkit_2support_2onnx_2_tensor_context_8h.html',1,'(Global Namespace)'],['../nnkit-mocotf_2support_2src_2_tensor_context_8h.html',1,'(Global Namespace)'],['../nnkit-intf_2tensor_2include_2nnkit_2_tensor_context_8h.html',1,'(Global Namespace)'],['../nnkit-caffe_2support_2include_2nnkit_2support_2caffe_2_tensor_context_8h.html',1,'(Global Namespace)']]],
  ['tensordatamap_2eh_26',['TensorDataMap.h',['../_tensor_data_map_8h.html',1,'']]],
  ['tensorfiller_2eh_27',['TensorFiller.h',['../_tensor_filler_8h.html',1,'']]],
  ['tensorindex_2ecpp_28',['TensorIndex.cpp',['../_tensor_index_8cpp.html',1,'']]],
  ['tensorindex_2eh_29',['tensorindex.h',['../angkor_2include_2angkor_2_tensor_index_8h.html',1,'(Global Namespace)'],['../loco_2include_2loco_2_i_r_2_tensor_index_8h.html',1,'(Global Namespace)']]],
  ['tensorinfoloader_2ecpp_30',['TensorInfoLoader.cpp',['../_tensor_info_loader_8cpp.html',1,'']]],
  ['tensorinfoloader_2eh_31',['TensorInfoLoader.h',['../_tensor_info_loader_8h.html',1,'']]],
  ['tensorinfoparser_2ecpp_32',['TensorInfoParser.cpp',['../_tensor_info_parser_8cpp.html',1,'']]],
  ['tensorinfoparser_2eh_33',['TensorInfoParser.h',['../_tensor_info_parser_8h.html',1,'']]],
  ['tensormanager_2ecc_34',['TensorManager.cc',['../_tensor_manager_8cc.html',1,'']]],
  ['tensormanager_2eh_35',['tensormanager.h',['../acl__cl_2_tensor_manager_8h.html',1,'(Global Namespace)'],['../train_2_tensor_manager_8h.html',1,'(Global Namespace)'],['../acl__neon_2_tensor_manager_8h.html',1,'(Global Namespace)']]],
  ['tensorpackenumerator_2ecpp_36',['TensorPackEnumerator.cpp',['../_tensor_pack_enumerator_8cpp.html',1,'']]],
  ['tensorpackenumerator_2eh_37',['TensorPackEnumerator.h',['../_tensor_pack_enumerator_8h.html',1,'']]],
  ['tensorplanner_2ecc_38',['TensorPlanner.cc',['../_tensor_planner_8cc.html',1,'']]],
  ['tensorplanner_2eh_39',['TensorPlanner.h',['../_tensor_planner_8h.html',1,'']]],
  ['tensorranksparsebackpropagationhandler_2ecpp_40',['TensorRankSparseBackpropagationHandler.cpp',['../_tensor_rank_sparse_backpropagation_handler_8cpp.html',1,'']]],
  ['tensorranksparsebackpropagationhandler_2eh_41',['TensorRankSparseBackpropagationHandler.h',['../_tensor_rank_sparse_backpropagation_handler_8h.html',1,'']]],
  ['tensorreduce_2ecpp_42',['TensorReduce.cpp',['../_tensor_reduce_8cpp.html',1,'']]],
  ['tensorreduceconverter_2ecpp_43',['TensorReduceConverter.cpp',['../_tensor_reduce_converter_8cpp.html',1,'']]],
  ['tensorreduceconverter_2eh_44',['TensorReduceConverter.h',['../_tensor_reduce_converter_8h.html',1,'']]],
  ['tensorregistries_2eh_45',['tensorregistries.h',['../train_2_tensor_registries_8h.html',1,'(Global Namespace)'],['../_tensor_registries_8h.html',1,'(Global Namespace)']]],
  ['tensorregistry_2eh_46',['tensorregistry.h',['../core_2src_2backend_2builtin_2train_2_tensor_registry_8h.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2_tensor_registry_8h.html',1,'(Global Namespace)'],['../core_2include_2backend_2basic_2_tensor_registry_8h.html',1,'(Global Namespace)'],['../backend_2train_2_tensor_registry_8h.html',1,'(Global Namespace)']]],
  ['tensorset_2eh_47',['tensorset.h',['../nnkit-tflite_2support_2include_2nnkit_2support_2tflite_2_tensor_set_8h.html',1,'(Global Namespace)'],['../nnkit-onnxrt_2support_2include_2nnkit_2support_2onnx_2_tensor_set_8h.html',1,'(Global Namespace)']]],
  ['tensorsets_2eh_48',['TensorSets.h',['../_tensor_sets_8h.html',1,'']]],
  ['tensorshape_2ecpp_49',['TensorShape.cpp',['../_tensor_shape_8cpp.html',1,'']]],
  ['tensorshape_2eh_50',['tensorshape.h',['../angkor_2include_2angkor_2_tensor_shape_8h.html',1,'(Global Namespace)'],['../loco_2include_2loco_2_i_r_2_tensor_shape_8h.html',1,'(Global Namespace)']]],
  ['tensorsignature_2ecpp_51',['TensorSignature.cpp',['../_tensor_signature_8cpp.html',1,'']]],
  ['tensorsignature_2eh_52',['TensorSignature.h',['../_tensor_signature_8h.html',1,'']]],
  ['tensorsliceenumerator_2ecpp_53',['TensorSliceEnumerator.cpp',['../_tensor_slice_enumerator_8cpp.html',1,'']]],
  ['tensorsliceenumerator_2eh_54',['TensorSliceEnumerator.h',['../_tensor_slice_enumerator_8h.html',1,'']]],
  ['tensortransposeconverter_2ecpp_55',['TensorTransposeConverter.cpp',['../_tensor_transpose_converter_8cpp.html',1,'']]],
  ['tensortransposeconverter_2eh_56',['TensorTransposeConverter.h',['../_tensor_transpose_converter_8h.html',1,'']]],
  ['tensortype_2eh_57',['TensorType.h',['../_tensor_type_8h.html',1,'']]],
  ['tensorutil_2eh_58',['TensorUtil.h',['../_tensor_util_8h.html',1,'']]],
  ['tensorutils_2ecpp_59',['TensorUtils.cpp',['../_tensor_utils_8cpp.html',1,'']]],
  ['tensorutils_2eh_60',['tensorutils.h',['../runtime_2compute_2ruy_2include_2ruy_2_tensor_utils_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2_tensor_utils_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-tflite_2support_2include_2nnkit_2support_2tflite_2_tensor_utils_8h.html',1,'(Global Namespace)']]],
  ['tensorvariant_2ecpp_61',['tensorvariant.cpp',['../unittests_2_tensor_variant_8cpp.html',1,'(Global Namespace)'],['../src_2_tensor_variant_8cpp.html',1,'(Global Namespace)']]],
  ['tensorvariant_2eh_62',['TensorVariant.h',['../_tensor_variant_8h.html',1,'']]],
  ['test_5fcircle_5fpart_5fvalue_2epy_63',['test_circle_part_value.py',['../test__circle__part__value_8py.html',1,'']]],
  ['test_5fdata_2eh_64',['test_data.h',['../test__data_8h.html',1,'']]],
  ['test_5fluci_5feval_2epy_65',['test_luci_eval.py',['../luci-value-py-test_2test__luci__eval_8py.html',1,'(Global Namespace)'],['../luci-ref-value-py-test_2test__luci__eval_8py.html',1,'(Global Namespace)'],['../luci-pass-value-py-test_2test__luci__eval_8py.html',1,'(Global Namespace)'],['../fm-equalize-value-py-test_2test__luci__eval_8py.html',1,'(Global Namespace)']]],
  ['test_5fluci_5feval_5fref_2epy_66',['test_luci_eval_ref.py',['../test__luci__eval__ref_8py.html',1,'']]],
  ['test_5futils_2epy_67',['test_utils.py',['../test__utils_8py.html',1,'']]],
  ['testdataabsbase_2eh_68',['testdataabsbase.h',['../onert-micro_2include_2test__models_2abs_2_test_data_abs_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2abs_2_test_data_abs_base_8h.html',1,'(Global Namespace)']]],
  ['testdataaddbase_2eh_69',['testdataaddbase.h',['../onert-micro_2include_2test__models_2add_2_test_data_add_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2add_2_test_data_add_base_8h.html',1,'(Global Namespace)']]],
  ['testdataaddnbase_2eh_70',['testdataaddnbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2add__n_2_test_data_add_n_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2add__n_2_test_data_add_n_base_8h.html',1,'(Global Namespace)']]],
  ['testdataargmaxbase_2eh_71',['testdataargmaxbase.h',['../onert-micro_2include_2test__models_2arg__max_2_test_data_arg_max_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2argmax_2_test_data_arg_max_base_8h.html',1,'(Global Namespace)']]],
  ['testdataargminbase_2eh_72',['testdataargminbase.h',['../onert-micro_2include_2test__models_2arg__min_2_test_data_arg_min_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2argmin_2_test_data_arg_min_base_8h.html',1,'(Global Namespace)']]],
  ['testdataaveragepool2dbase_2eh_73',['testdataaveragepool2dbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2average__pool__2d_2_test_data_average_pool2_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2averagepool2d_2_test_data_average_pool2_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatabase_2eh_74',['testdatabase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2_test_data_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2_test_data_base_8h.html',1,'(Global Namespace)']]],
  ['testdatabatchtospacendbase_2eh_75',['testdatabatchtospacendbase.h',['../onert-micro_2include_2test__models_2batch__to__space__nd_2_test_data_batch_to_space_n_d_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2batch__to__space__nd_2_test_data_batch_to_space_n_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatabmmbase_2eh_76',['TestDataBMMBase.h',['../_test_data_b_m_m_base_8h.html',1,'']]],
  ['testdatabroadcasttobase_2eh_77',['TestDataBroadcastToBase.h',['../_test_data_broadcast_to_base_8h.html',1,'']]],
  ['testdatacastbase_2eh_78',['testdatacastbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2cast_2_test_data_cast_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2cast_2_test_data_cast_base_8h.html',1,'(Global Namespace)']]],
  ['testdataceilbase_2eh_79',['testdataceilbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2ceil_2_test_data_ceil_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2ceil_2_test_data_ceil_base_8h.html',1,'(Global Namespace)']]],
  ['testdataconcatenationbase_2eh_80',['testdataconcatenationbase.h',['../onert-micro_2include_2test__models_2concatenation_2_test_data_concatenation_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2concatenation_2_test_data_concatenation_base_8h.html',1,'(Global Namespace)']]],
  ['testdataconv2dbase_2eh_81',['testdataconv2dbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2conv2d_2_test_data_conv2_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2conv2d_2_test_data_conv2_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatacosbase_2eh_82',['testdatacosbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2cos_2_test_data_cos_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2cos_2_test_data_cos_base_8h.html',1,'(Global Namespace)']]],
  ['testdatadepthtospacebase_2eh_83',['TestDataDepthToSpaceBase.h',['../_test_data_depth_to_space_base_8h.html',1,'']]],
  ['testdatadepthwiseconv2dbase_2eh_84',['testdatadepthwiseconv2dbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2depthwise__conv__2d_2_test_data_depthwise_conv2_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2depthwise__conv__2d_2_test_data_depthwise_conv2_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatadequantizebase_2eh_85',['testdatadequantizebase.h',['../onert-micro_2include_2test__models_2dequantize_2_test_data_dequantize_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2dequantize_2_test_data_dequantize_base_8h.html',1,'(Global Namespace)']]],
  ['testdatadivbase_2eh_86',['testdatadivbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2div_2_test_data_div_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2div_2_test_data_div_base_8h.html',1,'(Global Namespace)']]],
  ['testdataelubase_2eh_87',['testdataelubase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2elu_2_test_data_elu_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2elu_2_test_data_elu_base_8h.html',1,'(Global Namespace)']]],
  ['testdataequalbase_2eh_88',['testdataequalbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2equal_2_test_data_equal_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2equal_2_test_data_equal_base_8h.html',1,'(Global Namespace)']]],
  ['testdataexpbase_2eh_89',['testdataexpbase.h',['../onert-micro_2include_2test__models_2exp_2_test_data_exp_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2exp_2_test_data_exp_base_8h.html',1,'(Global Namespace)']]],
  ['testdatafloorbase_2eh_90',['testdatafloorbase.h',['../onert-micro_2include_2test__models_2floor_2_test_data_floor_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2floor_2_test_data_floor_base_8h.html',1,'(Global Namespace)']]],
  ['testdatafloordivbase_2eh_91',['testdatafloordivbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2floordiv_2_test_data_floor_div_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2floordiv_2_test_data_floor_div_base_8h.html',1,'(Global Namespace)']]],
  ['testdatafloormodbase_2eh_92',['testdatafloormodbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2floormod_2_test_data_floor_mod_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2floormod_2_test_data_floor_mod_base_8h.html',1,'(Global Namespace)']]],
  ['testdatafullyconnectedbase_2eh_93',['testdatafullyconnectedbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2fully__connected_2_test_data_fully_connected_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2fully__connected_2_test_data_fully_connected_base_8h.html',1,'(Global Namespace)']]],
  ['testdatagatherbase_2eh_94',['testdatagatherbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2gather_2_test_data_gather_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2gather_2_test_data_gather_base_8h.html',1,'(Global Namespace)']]],
  ['testdatagatherndbase_2eh_95',['testdatagatherndbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2gather__nd_2_test_data_gather_n_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2gather__nd_2_test_data_gather_n_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatagenerator_2ecpp_96',['TestDataGenerator.cpp',['../_test_data_generator_8cpp.html',1,'']]],
  ['testdatagreaterbase_2eh_97',['testdatagreaterbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2greater_2_test_data_greater_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2greater_2_test_data_greater_base_8h.html',1,'(Global Namespace)']]],
  ['testdatagreaterequalbase_2eh_98',['testdatagreaterequalbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2greater__equal_2_test_data_greater_equal_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2greater__equal_2_test_data_greater_equal_base_8h.html',1,'(Global Namespace)']]],
  ['testdatagrubase_2eh_99',['TestDataGRUBase.h',['../_test_data_g_r_u_base_8h.html',1,'']]],
  ['testdatal2normalizebase_2eh_100',['testdatal2normalizebase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2l2__normalization_2_test_data_l2_normalize_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2l2__normalization_2_test_data_l2_normalize_base_8h.html',1,'(Global Namespace)']]],
  ['testdatal2pool2dbase_2eh_101',['testdatal2pool2dbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2l2__poop__2d_2_test_data_l2_pool2_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2l2pool2d_2_test_data_l2_pool2_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdataleakyrelubase_2eh_102',['testdataleakyrelubase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2leaky__relu_2_test_data_leaky_re_l_u_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2leaky__relu_2_test_data_leaky_re_l_u_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalessbase_2eh_103',['testdatalessbase.h',['../onert-micro_2include_2test__models_2less_2_test_data_less_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2less_2_test_data_less_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalessequalbase_2eh_104',['testdatalessequalbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2less__equal_2_test_data_less_equal_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2less__equal_2_test_data_less_equal_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogbase_2eh_105',['testdatalogbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2log_2_test_data_log_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2log_2_test_data_log_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogicalandbase_2eh_106',['testdatalogicalandbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__and_2_test_data_logical_and_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2logical__and_2_test_data_logical_and_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogicalnotbase_2eh_107',['testdatalogicalnotbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__not_2_test_data_logical_not_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2logical__not_2_test_data_logical_not_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogicalorbase_2eh_108',['testdatalogicalorbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__or_2_test_data_logical_or_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2logical__or_2_test_data_logical_or_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogisticbase_2eh_109',['testdatalogisticbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2logistic_2_test_data_logistic_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2logistic_2_test_data_logistic_base_8h.html',1,'(Global Namespace)']]],
  ['testdatalogsoftmaxbase_2eh_110',['testdatalogsoftmaxbase.h',['../onert-micro_2include_2test__models_2log__softmax_2_test_data_log_softmax_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2log__softmax_2_test_data_log_softmax_base_8h.html',1,'(Global Namespace)']]],
  ['testdatamaximumbase_2eh_111',['testdatamaximumbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2maximum_2_test_data_maximum_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2maximum_2_test_data_maximum_base_8h.html',1,'(Global Namespace)']]],
  ['testdatamaxpool2dbase_2eh_112',['testdatamaxpool2dbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2maxpool2d_2_test_data_max_pool2_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2maxpool2d_2_test_data_max_pool2_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdatameanbase_2eh_113',['testdatameanbase.h',['../onert-micro_2include_2test__models_2mean_2_test_data_mean_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2mean_2_test_data_mean_base_8h.html',1,'(Global Namespace)']]],
  ['testdataminimumbase_2eh_114',['testdataminimumbase.h',['../onert-micro_2include_2test__models_2minimum_2_test_data_minimum_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2minimum_2_test_data_minimum_base_8h.html',1,'(Global Namespace)']]],
  ['testdatamirrorpadbase_2eh_115',['TestDataMirrorPadBase.h',['../_test_data_mirror_pad_base_8h.html',1,'']]],
  ['testdatamulbase_2eh_116',['testdatamulbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2mul_2_test_data_mul_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2mul_2_test_data_mul_base_8h.html',1,'(Global Namespace)']]],
  ['testdatanegbase_2eh_117',['testdatanegbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2neg_2_test_data_neg_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2neg_2_test_data_neg_base_8h.html',1,'(Global Namespace)']]],
  ['testdatanotequalbase_2eh_118',['testdatanotequalbase.h',['../onert-micro_2include_2test__models_2notequal_2_test_data_not_equal_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2notequal_2_test_data_not_equal_base_8h.html',1,'(Global Namespace)']]],
  ['testdatapackbase_2eh_119',['testdatapackbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2pack_2_test_data_pack_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2pack_2_test_data_pack_base_8h.html',1,'(Global Namespace)']]],
  ['testdatapadbase_2eh_120',['testdatapadbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2pad_2_test_data_pad_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2pad_2_test_data_pad_base_8h.html',1,'(Global Namespace)']]],
  ['testdatapadv2base_2eh_121',['TestDataPadV2Base.h',['../_test_data_pad_v2_base_8h.html',1,'']]],
  ['testdataprelubase_2eh_122',['TestDataPReluBase.h',['../_test_data_p_relu_base_8h.html',1,'']]],
  ['testdataquantizebase_2eh_123',['testdataquantizebase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2quantize_2_test_data_quantize_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2quantize_2_test_data_quantize_base_8h.html',1,'(Global Namespace)']]],
  ['testdatareducecommonbase_2eh_124',['TestDataReduceCommonBase.h',['../_test_data_reduce_common_base_8h.html',1,'']]],
  ['testdatareducemaxbase_2eh_125',['TestDataReduceMaxBase.h',['../_test_data_reduce_max_base_8h.html',1,'']]],
  ['testdatareduceprodbase_2eh_126',['TestDataReduceProdBase.h',['../_test_data_reduce_prod_base_8h.html',1,'']]],
  ['testdatarelu6base_2eh_127',['testdatarelu6base.h',['../onert-micro_2include_2test__models_2relu6_2_test_data_re_l_u6_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2relu6_2_test_data_re_l_u6_base_8h.html',1,'(Global Namespace)']]],
  ['testdatarelubase_2eh_128',['testdatarelubase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2relu_2_test_data_re_l_u_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2relu_2_test_data_re_l_u_base_8h.html',1,'(Global Namespace)']]],
  ['testdataresizebilinearbase_2eh_129',['TestDataResizeBilinearBase.h',['../_test_data_resize_bilinear_base_8h.html',1,'']]],
  ['testdataresizenearestneighborbase_2eh_130',['TestDataResizeNearestNeighborBase.h',['../_test_data_resize_nearest_neighbor_base_8h.html',1,'']]],
  ['testdataroundbase_2eh_131',['testdataroundbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2round_2_test_data_round_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2round_2_test_data_round_base_8h.html',1,'(Global Namespace)']]],
  ['testdatarsqrtbase_2eh_132',['testdatarsqrtbase.h',['../onert-micro_2include_2test__models_2rsqrt_2_test_data_rsqrt_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2rsqrt_2_test_data_rsqrt_base_8h.html',1,'(Global Namespace)']]],
  ['testdataselectv2base_2eh_133',['testdataselectv2base.h',['../onert-micro_2include_2test__models_2select__v2_2_test_data_select_v2_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2select__v2_2_test_data_select_v2_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasinbase_2eh_134',['testdatasinbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2sin_2_test_data_sin_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2sin_2_test_data_sin_base_8h.html',1,'(Global Namespace)']]],
  ['testdataslicebase_2eh_135',['testdataslicebase.h',['../onert-micro_2include_2test__models_2slice_2_test_data_slice_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2slice_2_test_data_slice_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasoftmaxbase_2eh_136',['TestDataSoftmaxBase.h',['../_test_data_softmax_base_8h.html',1,'']]],
  ['testdataspacetobatchndbase_2eh_137',['testdataspacetobatchndbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2space__to__batch__nd_2_test_data_space_to_batch_n_d_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2space__to__batch__nd_2_test_data_space_to_batch_n_d_base_8h.html',1,'(Global Namespace)']]],
  ['testdataspacetodepthbase_2eh_138',['testdataspacetodepthbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2space__to__depth_2_test_data_space_to_depth_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2space__to__depth_2_test_data_space_to_depth_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasplitbase_2eh_139',['testdatasplitbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2split_2_test_data_split_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2split_2_test_data_split_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasplitvbase_2eh_140',['TestDataSplitVBase.h',['../_test_data_split_v_base_8h.html',1,'']]],
  ['testdatasqrtbase_2eh_141',['testdatasqrtbase.h',['../onert-micro_2include_2test__models_2sqrt_2_test_data_sqrt_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2sqrt_2_test_data_sqrt_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasquarebase_2eh_142',['testdatasquarebase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2square_2_test_data_square_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2square_2_test_data_square_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasquareddifferencebase_2eh_143',['testdatasquareddifferencebase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2squared__difference_2_test_data_squared_difference_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2squared__difference_2_test_data_squared_difference_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasqueezebase_2eh_144',['TestDataSqueezeBase.h',['../_test_data_squeeze_base_8h.html',1,'']]],
  ['testdatastridedslicebase_2eh_145',['TestDataStridedSliceBase.h',['../_test_data_strided_slice_base_8h.html',1,'']]],
  ['testdatasubbase_2eh_146',['testdatasubbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2sub_2_test_data_sub_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2sub_2_test_data_sub_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasumbase_2eh_147',['testdatasumbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2sum_2_test_data_sum_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2sum_2_test_data_sum_base_8h.html',1,'(Global Namespace)']]],
  ['testdatasvdfbase_2eh_148',['testdatasvdfbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2svdf_2_test_data_s_v_d_f_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2svdf_2_test_data_s_v_d_f_base_8h.html',1,'(Global Namespace)']]],
  ['testdatatanhbase_2eh_149',['testdatatanhbase.h',['../onert-micro_2include_2test__models_2tanh_2_test_data_tanh_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2tanh_2_test_data_tanh_base_8h.html',1,'(Global Namespace)']]],
  ['testdatatransposebase_2eh_150',['TestDataTransposeBase.h',['../_test_data_transpose_base_8h.html',1,'']]],
  ['testdatatransposeconvbase_2eh_151',['testdatatransposeconvbase.h',['../onert-micro_2include_2test__models_2transpose__conv_2_test_data_transpose_conv_base_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2transpose__conv_2_test_data_transpose_conv_base_8h.html',1,'(Global Namespace)']]],
  ['testdataunidirectionallstmbase_2eh_152',['TestDataUnidirectionalLSTMBase.h',['../_test_data_unidirectional_l_s_t_m_base_8h.html',1,'']]],
  ['testdataunpackbase_2eh_153',['testdataunpackbase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2unpack_2_test_data_unpack_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2unpack_2_test_data_unpack_base_8h.html',1,'(Global Namespace)']]],
  ['testdatazeroslikebase_2eh_154',['testdatazeroslikebase.h',['../luci-interpreter_2include_2luci__interpreter_2test__models_2zeros__like_2_test_data_zeros_like_base_8h.html',1,'(Global Namespace)'],['../onert-micro_2include_2test__models_2zeroslike_2_test_data_zeros_like_base_8h.html',1,'(Global Namespace)']]],
  ['testdriver_2ecpp_155',['TestDriver.cpp',['../_test_driver_8cpp.html',1,'']]],
  ['testgraph_2eh_156',['testgraph.h',['../luci_2service_2src_2_test_graph_8h.html',1,'(Global Namespace)'],['../exo_2src_2_test_graph_8h.html',1,'(Global Namespace)']]],
  ['testhelper_2ecpp_157',['TestHelper.cpp',['../_test_helper_8cpp.html',1,'']]],
  ['testhelper_2eh_158',['testhelper.h',['../circle-mpqsolver_2src_2core_2_test_helper_8h.html',1,'(Global Namespace)'],['../moco_2service_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../plier-tf_2include_2plier_2tf_2_test_helper_8h.html',1,'(Global Namespace)'],['../circle-opselector_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../circle2circle_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../exo_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../logo-ex_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../logo_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../moco-tf_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../moco_2import_2src_2_test_helper_8h.html',1,'(Global Namespace)'],['../moco_2pass_2src_2_test_helper_8h.html',1,'(Global Namespace)']]],
  ['testmemorymanager_2ecpp_159',['testmemorymanager.cpp',['../onert-micro_2luci-interpreter_2src_2memory__managers_2_test_memory_manager_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2_test_memory_manager_8cpp.html',1,'(Global Namespace)']]],
  ['testmemorymanager_2eh_160',['testmemorymanager.h',['../onert-micro_2luci-interpreter_2src_2memory__managers_2_test_memory_manager_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2include_2luci__interpreter_2_test_memory_manager_8h.html',1,'(Global Namespace)']]],
  ['testutil_2epy_161',['TestUtil.py',['../_test_util_8py.html',1,'']]],
  ['testutils_2ecpp_162',['testutils.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_test_utils_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_test_utils_8cpp.html',1,'(Global Namespace)']]],
  ['testutils_2eh_163',['testutils.h',['../compiler_2luci-interpreter_2src_2kernels_2_test_utils_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_test_utils_8h.html',1,'(Global Namespace)']]],
  ['textformatter_2eh_164',['TextFormatter.h',['../_text_formatter_8h.html',1,'']]],
  ['tf2circle_2ecpp_165',['tf2circle.cpp',['../tf2circle_8cpp.html',1,'']]],
  ['tf2nnpkg_2ecpp_166',['tf2nnpkg.cpp',['../tf2nnpkg_8cpp.html',1,'']]],
  ['tf2tflitev2_2epy_167',['tf2tfliteV2.py',['../tf2tflite_v2_8py.html',1,'']]],
  ['tfadd_2eh_168',['TFAdd.h',['../_t_f_add_8h.html',1,'']]],
  ['tfavgpool_2eh_169',['TFAvgPool.h',['../_t_f_avg_pool_8h.html',1,'']]],
  ['tfbiasadd_2eh_170',['TFBiasAdd.h',['../_t_f_bias_add_8h.html',1,'']]],
  ['tfconcatv2_2eh_171',['TFConcatV2.h',['../_t_f_concat_v2_8h.html',1,'']]],
  ['tfconst_2ecpp_172',['TFConst.cpp',['../_t_f_const_8cpp.html',1,'']]],
  ['tfconst_2eh_173',['TFConst.h',['../_t_f_const_8h.html',1,'']]],
  ['tfconv2d_2eh_174',['TFConv2D.h',['../_t_f_conv2_d_8h.html',1,'']]],
  ['tfconv2dbackpropinput_2eh_175',['TFConv2DBackpropInput.h',['../_t_f_conv2_d_backprop_input_8h.html',1,'']]],
  ['tfdatalayout_2eh_176',['TFDataLayout.h',['../_t_f_data_layout_8h.html',1,'']]],
  ['tfdepthwiseconv2dnative_2eh_177',['TFDepthwiseConv2dNative.h',['../_t_f_depthwise_conv2d_native_8h.html',1,'']]],
  ['tfdialect_2ecpp_178',['TFDialect.cpp',['../_t_f_dialect_8cpp.html',1,'']]],
  ['tfdialect_2eh_179',['TFDialect.h',['../_t_f_dialect_8h.html',1,'']]],
  ['tfeltwisebinarycanonicalzehelper_2eh_180',['TFEltwiseBinaryCanonicalzeHelper.h',['../_t_f_eltwise_binary_canonicalze_helper_8h.html',1,'']]],
  ['tffakequantwithminmaxvars_2eh_181',['TFFakeQuantWithMinMaxVars.h',['../_t_f_fake_quant_with_min_max_vars_8h.html',1,'']]],
  ['tfformattedgraph_2ecpp_182',['TFFormattedGraph.cpp',['../_t_f_formatted_graph_8cpp.html',1,'']]],
  ['tfformattedgraph_2eh_183',['TFFormattedGraph.h',['../_t_f_formatted_graph_8h.html',1,'']]],
  ['tffusedbatchnorm_2eh_184',['TFFusedBatchNorm.h',['../_t_f_fused_batch_norm_8h.html',1,'']]],
  ['tfidentity_2eh_185',['TFIdentity.h',['../_t_f_identity_8h.html',1,'']]],
  ['tfldialect_2ecpp_186',['TFLDialect.cpp',['../_t_f_l_dialect_8cpp.html',1,'']]],
  ['tfldialect_2eh_187',['TFLDialect.h',['../_t_f_l_dialect_8h.html',1,'']]],
  ['tflexporter_2ecpp_188',['TFLExporter.cpp',['../_t_f_l_exporter_8cpp.html',1,'']]],
  ['tflexporter_2eh_189',['TFLExporter.h',['../_t_f_l_exporter_8h.html',1,'']]],
  ['tflexporterimpl_2ecpp_190',['TFLExporterImpl.cpp',['../_t_f_l_exporter_impl_8cpp.html',1,'']]],
  ['tflexporterimpl_2eh_191',['TFLExporterImpl.h',['../_t_f_l_exporter_impl_8h.html',1,'']]],
  ['tflexporterutils_2ecpp_192',['TFLExporterUtils.cpp',['../_t_f_l_exporter_utils_8cpp.html',1,'']]],
  ['tflexporterutils_2eh_193',['TFLExporterUtils.h',['../_t_f_l_exporter_utils_8h.html',1,'']]],
  ['tflite_2ecpp_194',['tflite.cpp',['../tflite_8cpp.html',1,'']]],
  ['tflite_2eh_195',['tflite.h',['../tflite_8h.html',1,'']]],
  ['tflite_5fimporter_2ecpp_196',['tflite_importer.cpp',['../tflite__importer_8cpp.html',1,'']]],
  ['tflite_5fimporter_2eh_197',['tflite_importer.h',['../tflite__importer_8h.html',1,'']]],
  ['tflite_5fop_5fcreator_2ecpp_198',['tflite_op_creator.cpp',['../tflite__op__creator_8cpp.html',1,'']]],
  ['tflite_5fop_5fcreator_2eh_199',['tflite_op_creator.h',['../tflite__op__creator_8h.html',1,'']]],
  ['tfliteimport_2ecpp_200',['TFliteImport.cpp',['../_t_flite_import_8cpp.html',1,'']]],
  ['tfliteimport_2eh_201',['TFliteImport.h',['../_t_flite_import_8h.html',1,'']]],
  ['tfliteloader_2ecc_202',['TFLiteLoader.cc',['../_t_f_lite_loader_8cc.html',1,'']]],
  ['tfliteloader_2eh_203',['TFLiteLoader.h',['../_t_f_lite_loader_8h.html',1,'']]],
  ['tfliteopchef_2eh_204',['TFliteOpChef.h',['../_t_flite_op_chef_8h.html',1,'']]],
  ['tfliteopchefs_2eh_205',['TFliteOpChefs.h',['../_t_flite_op_chefs_8h.html',1,'']]],
  ['tfliteopregistry_2eh_206',['TFliteOpRegistry.h',['../_t_flite_op_registry_8h.html',1,'']]],
  ['tflmodel_2ecpp_207',['TFLModel.cpp',['../_t_f_l_model_8cpp.html',1,'']]],
  ['tflmodel_2eh_208',['TFLModel.h',['../_t_f_l_model_8h.html',1,'']]],
  ['tflnode_2ecpp_209',['TFLNode.cpp',['../_t_f_l_node_8cpp.html',1,'']]],
  ['tflnode_2eh_210',['TFLNode.h',['../_t_f_l_node_8h.html',1,'']]],
  ['tflnodedecl_2eh_211',['TFLNodeDecl.h',['../_t_f_l_node_decl_8h.html',1,'']]],
  ['tflnodeimpl_2eh_212',['TFLNodeImpl.h',['../_t_f_l_node_impl_8h.html',1,'']]],
  ['tflnodes_2ecpp_213',['TFLNodes.cpp',['../_t_f_l_nodes_8cpp.html',1,'']]],
  ['tflnodes_2eh_214',['TFLNodes.h',['../_t_f_l_nodes_8h.html',1,'']]],
  ['tflnodevisitor_2eforward_2eh_215',['TFLNodeVisitor.forward.h',['../_t_f_l_node_visitor_8forward_8h.html',1,'']]],
  ['tflnodevisitor_2eh_216',['TFLNodeVisitor.h',['../_t_f_l_node_visitor_8h.html',1,'']]],
  ['tflopcode_2eh_217',['TFLOpcode.h',['../_t_f_l_opcode_8h.html',1,'']]],
  ['tfloperationexporter_2ecpp_218',['TFLOperationExporter.cpp',['../_t_f_l_operation_exporter_8cpp.html',1,'']]],
  ['tfloperationexporter_2eh_219',['TFLOperationExporter.h',['../_t_f_l_operation_exporter_8h.html',1,'']]],
  ['tflshapeinferencerule_2ecpp_220',['TFLShapeInferenceRule.cpp',['../_t_f_l_shape_inference_rule_8cpp.html',1,'']]],
  ['tflshapeinferencerule_2eh_221',['TFLShapeInferenceRule.h',['../_t_f_l_shape_inference_rule_8h.html',1,'']]],
  ['tfltensorexporter_2ecpp_222',['TFLTensorExporter.cpp',['../_t_f_l_tensor_exporter_8cpp.html',1,'']]],
  ['tfltensorexporter_2eh_223',['TFLTensorExporter.h',['../_t_f_l_tensor_exporter_8h.html',1,'']]],
  ['tfltypeinference_2ecpp_224',['TFLTypeInference.cpp',['../_t_f_l_type_inference_8cpp.html',1,'']]],
  ['tfltypeinference_2eh_225',['TFLTypeInference.h',['../_t_f_l_type_inference_8h.html',1,'']]],
  ['tfltypeinferencerule_2ecpp_226',['TFLTypeInferenceRule.cpp',['../_t_f_l_type_inference_rule_8cpp.html',1,'']]],
  ['tfltypeinferencerule_2eh_227',['TFLTypeInferenceRule.h',['../_t_f_l_type_inference_rule_8h.html',1,'']]],
  ['tfmaximum_2eh_228',['TFMaximum.h',['../_t_f_maximum_8h.html',1,'']]],
  ['tfmaxpool_2eh_229',['TFMaxPool.h',['../_t_f_max_pool_8h.html',1,'']]],
  ['tfmean_2eh_230',['TFMean.h',['../_t_f_mean_8h.html',1,'']]],
  ['tfmul_2eh_231',['TFMul.h',['../_t_f_mul_8h.html',1,'']]],
  ['tfnode_2ecpp_232',['TFNode.cpp',['../_t_f_node_8cpp.html',1,'']]],
  ['tfnode_2eh_233',['TFNode.h',['../_t_f_node_8h.html',1,'']]],
  ['tfnodedecl_2eh_234',['TFNodeDecl.h',['../_t_f_node_decl_8h.html',1,'']]],
  ['tfnodeimpl_2eh_235',['TFNodeImpl.h',['../_t_f_node_impl_8h.html',1,'']]],
  ['tfnodes_2eh_236',['TFNodes.h',['../_t_f_nodes_8h.html',1,'']]],
  ['tfnodevisitor_2eforward_2eh_237',['TFNodeVisitor.forward.h',['../_t_f_node_visitor_8forward_8h.html',1,'']]],
  ['tfnodevisitor_2eh_238',['TFNodeVisitor.h',['../_t_f_node_visitor_8h.html',1,'']]],
  ['tfopcode_2eh_239',['TFOpcode.h',['../_t_f_opcode_8h.html',1,'']]],
  ['tfoptimizer_2ecpp_240',['TFOptimizer.cpp',['../_t_f_optimizer_8cpp.html',1,'']]],
  ['tfoptimizer_2eh_241',['TFOptimizer.h',['../_t_f_optimizer_8h.html',1,'']]],
  ['tfpack_2eh_242',['TFPack.h',['../_t_f_pack_8h.html',1,'']]],
  ['tfpad_2eh_243',['TFPad.h',['../_t_f_pad_8h.html',1,'']]],
  ['tfpadding_2eh_244',['TFPadding.h',['../_t_f_padding_8h.html',1,'']]],
  ['tfplaceholder_2eh_245',['TFPlaceholder.h',['../_t_f_placeholder_8h.html',1,'']]],
  ['tfpush_2eh_246',['TFPush.h',['../_t_f_push_8h.html',1,'']]],
  ['tfpushcanonicalizer_2ecpp_247',['TFPushCanonicalizer.cpp',['../_t_f_push_canonicalizer_8cpp.html',1,'']]],
  ['tfpushcanonicalizer_2eh_248',['TFPushCanonicalizer.h',['../_t_f_push_canonicalizer_8h.html',1,'']]],
  ['tfrealdiv_2eh_249',['TFRealDiv.h',['../_t_f_real_div_8h.html',1,'']]],
  ['tfreducecanonicalzehelper_2eh_250',['TFReduceCanonicalzeHelper.h',['../_t_f_reduce_canonicalze_helper_8h.html',1,'']]],
  ['tfrelu_2eh_251',['TFRelu.h',['../_t_f_relu_8h.html',1,'']]],
  ['tfrelu6_2eh_252',['TFRelu6.h',['../_t_f_relu6_8h.html',1,'']]],
  ['tfreshape_2eh_253',['TFReshape.h',['../_t_f_reshape_8h.html',1,'']]],
  ['tfrsqrt_2eh_254',['TFRsqrt.h',['../_t_f_rsqrt_8h.html',1,'']]],
  ['tfshape_2eh_255',['TFShape.h',['../_t_f_shape_8h.html',1,'']]],
  ['tfshapeinferencehelper_2ecpp_256',['TFShapeInferenceHelper.cpp',['../_t_f_shape_inference_helper_8cpp.html',1,'']]],
  ['tfshapeinferencehelper_2eh_257',['TFShapeInferenceHelper.h',['../_t_f_shape_inference_helper_8h.html',1,'']]],
  ['tfshapeinferencerule_2ecpp_258',['TFShapeInferenceRule.cpp',['../_t_f_shape_inference_rule_8cpp.html',1,'']]],
  ['tfshapeinferencerule_2eh_259',['TFShapeInferenceRule.h',['../_t_f_shape_inference_rule_8h.html',1,'']]],
  ['tfsoftmax_2eh_260',['TFSoftmax.h',['../_t_f_softmax_8h.html',1,'']]],
  ['tfsqrt_2eh_261',['TFSqrt.h',['../_t_f_sqrt_8h.html',1,'']]],
  ['tfsquareddifference_2eh_262',['TFSquaredDifference.h',['../_t_f_squared_difference_8h.html',1,'']]],
  ['tfsqueeze_2eh_263',['TFSqueeze.h',['../_t_f_squeeze_8h.html',1,'']]],
  ['tfstopgradient_2eh_264',['TFStopGradient.h',['../_t_f_stop_gradient_8h.html',1,'']]],
  ['tfstridedslice_2eh_265',['TFStridedSlice.h',['../_t_f_strided_slice_8h.html',1,'']]],
  ['tfsub_2eh_266',['TFSub.h',['../_t_f_sub_8h.html',1,'']]],
  ['tftanh_2eh_267',['TFTanh.h',['../_t_f_tanh_8h.html',1,'']]],
  ['tftypeinferencerule_2ecpp_268',['TFTypeInferenceRule.cpp',['../_t_f_type_inference_rule_8cpp.html',1,'']]],
  ['tftypeinferencerule_2eh_269',['TFTypeInferenceRule.h',['../_t_f_type_inference_rule_8h.html',1,'']]],
  ['threadpool_2ecc_270',['ThreadPool.cc',['../_thread_pool_8cc.html',1,'']]],
  ['threadpool_2eh_271',['ThreadPool.h',['../_thread_pool_8h.html',1,'']]],
  ['tile_2ecc_272',['Tile.cc',['../_tile_8cc.html',1,'']]],
  ['tile_2ecpp_273',['tile.cpp',['../luci-interpreter_2src_2loader_2nodes_2_tile_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_tile_8cpp.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_tile_8cpp.html',1,'(Global Namespace)'],['../tflchef_2tflite_2src_2_op_2_tile_8cpp.html',1,'(Global Namespace)']]],
  ['tile_2eh_274',['tile.h',['../runtime_2onert_2core_2include_2ir_2operation_2_tile_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_tile_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_tile_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_tile_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_tile_8h.html',1,'(Global Namespace)']]],
  ['tilelayer_2ecc_275',['TileLayer.cc',['../_tile_layer_8cc.html',1,'']]],
  ['tilelayer_2eh_276',['TileLayer.h',['../_tile_layer_8h.html',1,'']]],
  ['tileoptions_2ecpp_277',['TileOptions.cpp',['../_tile_options_8cpp.html',1,'']]],
  ['tileoptions_2eh_278',['TileOptions.h',['../_tile_options_8h.html',1,'']]],
  ['tisokernel_2eh_279',['TISOKernel.h',['../_t_i_s_o_kernel_8h.html',1,'']]],
  ['to_5funderlying_2eh_280',['to_underlying.h',['../to__underlying_8h.html',1,'']]],
  ['topk_5fv2_2eh_281',['topk_v2.h',['../topk__v2_8h.html',1,'']]],
  ['topkv2_2ecc_282',['TopKV2.cc',['../_top_k_v2_8cc.html',1,'']]],
  ['topkv2_2ecpp_283',['topkv2.cpp',['../tflite_2src_2_op_2_top_k_v2_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_top_k_v2_8cpp.html',1,'(Global Namespace)']]],
  ['topkv2_2eh_284',['topkv2.h',['../compiler_2tflchef_2tflite_2src_2_op_2include_2_top_k_v2_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_top_k_v2_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_top_k_v2_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_top_k_v2_8h.html',1,'(Global Namespace)']]],
  ['topkv2layer_2ecc_285',['TopKV2Layer.cc',['../_top_k_v2_layer_8cc.html',1,'']]],
  ['topkv2layer_2eh_286',['TopKV2Layer.h',['../_top_k_v2_layer_8h.html',1,'']]],
  ['topkv2options_2ecpp_287',['TopKV2Options.cpp',['../_top_k_v2_options_8cpp.html',1,'']]],
  ['topkv2options_2eh_288',['TopKV2Options.h',['../_top_k_v2_options_8h.html',1,'']]],
  ['topologicalsorthelper_2epy_289',['TopologicalSortHelper.py',['../_topological_sort_helper_8py.html',1,'']]],
  ['tracingctx_2eh_290',['TracingCtx.h',['../_tracing_ctx_8h.html',1,'']]],
  ['train_2ecc_291',['train.cc',['../train_8cc.html',1,'']]],
  ['train_5fstep_5fwith_5fdataset_2epy_292',['train_step_with_dataset.py',['../train__step__with__dataset_8py.html',1,'']]],
  ['train_5fwith_5fdataset_2epy_293',['train_with_dataset.py',['../train__with__dataset_8py.html',1,'']]],
  ['trainablebackendcontext_2eh_294',['TrainableBackendContext.h',['../_trainable_backend_context_8h.html',1,'']]],
  ['trainablebackendcontexthelpers_2eh_295',['TrainableBackendContextHelpers.h',['../_trainable_backend_context_helpers_8h.html',1,'']]],
  ['trainablecodemap_2eh_296',['TrainableCodeMap.h',['../_trainable_code_map_8h.html',1,'']]],
  ['trainableconstantinsertionpass_2ecc_297',['TrainableConstantInsertionPass.cc',['../_trainable_constant_insertion_pass_8cc.html',1,'']]],
  ['trainableconstantinsertionpass_2eh_298',['TrainableConstantInsertionPass.h',['../_trainable_constant_insertion_pass_8h.html',1,'']]],
  ['trainableexecutor_2ecc_299',['TrainableExecutor.cc',['../_trainable_executor_8cc.html',1,'']]],
  ['trainableexecutor_2eh_300',['TrainableExecutor.h',['../_trainable_executor_8h.html',1,'']]],
  ['trainableexecutors_2ecc_301',['TrainableExecutors.cc',['../_trainable_executors_8cc.html',1,'']]],
  ['trainableexecutors_2eh_302',['TrainableExecutors.h',['../_trainable_executors_8h.html',1,'']]],
  ['trainablefnsequence_2ecc_303',['TrainableFnSequence.cc',['../_trainable_fn_sequence_8cc.html',1,'']]],
  ['trainablefnsequence_2eh_304',['TrainableFnSequence.h',['../_trainable_fn_sequence_8h.html',1,'']]],
  ['trainablegraph_2ecc_305',['TrainableGraph.cc',['../_trainable_graph_8cc.html',1,'']]],
  ['trainablegraph_2eh_306',['TrainableGraph.h',['../_trainable_graph_8h.html',1,'']]],
  ['trainableoperation_2eh_307',['TrainableOperation.h',['../_trainable_operation_8h.html',1,'']]],
  ['trainableoperationconverter_2ecc_308',['TrainableOperationConverter.cc',['../_trainable_operation_converter_8cc.html',1,'']]],
  ['trainableoperationconverter_2eh_309',['TrainableOperationConverter.h',['../_trainable_operation_converter_8h.html',1,'']]],
  ['trainableoperationvisitor_2eh_310',['TrainableOperationVisitor.h',['../_trainable_operation_visitor_8h.html',1,'']]],
  ['trainabletensor_2ecc_311',['TrainableTensor.cc',['../_trainable_tensor_8cc.html',1,'']]],
  ['trainabletensor_2eh_312',['TrainableTensor.h',['../_trainable_tensor_8h.html',1,'']]],
  ['trainableweightstorage_2ecpp_313',['TrainableWeightStorage.cpp',['../_trainable_weight_storage_8cpp.html',1,'']]],
  ['trainableweightstorage_2eh_314',['TrainableWeightStorage.h',['../_trainable_weight_storage_8h.html',1,'']]],
  ['trainconfigdata_2eh_315',['TrainConfigData.h',['../_train_config_data_8h.html',1,'']]],
  ['traininfobuilder_2eh_316',['TrainInfoBuilder.h',['../_train_info_builder_8h.html',1,'']]],
  ['traininfoloader_2ecc_317',['TrainInfoLoader.cc',['../_train_info_loader_8cc.html',1,'']]],
  ['traininfoloader_2eh_318',['TrainInfoLoader.h',['../_train_info_loader_8h.html',1,'']]],
  ['training_2emd_319',['training.md',['../training_8md.html',1,'']]],
  ['training_5fcnn_5fon_5fmnist_2emd_320',['training_cnn_on_mnist.md',['../training__cnn__on__mnist_8md.html',1,'']]],
  ['training_5fmobilenetv2_5fon_5fimagenet_2emd_321',['training_mobilenetv2_on_imagenet.md',['../training__mobilenetv2__on__imagenet_8md.html',1,'']]],
  ['training_5fops_2eh_322',['training_ops.h',['../training__ops_8h.html',1,'']]],
  ['trainingcompiler_2ecc_323',['TrainingCompiler.cc',['../_training_compiler_8cc.html',1,'']]],
  ['trainingcompiler_2eh_324',['TrainingCompiler.h',['../_training_compiler_8h.html',1,'']]],
  ['trainingconfigurefilehandler_2ecpp_325',['TrainingConfigureFileHandler.cpp',['../_training_configure_file_handler_8cpp.html',1,'']]],
  ['trainingconfigurefilehandler_2eh_326',['TrainingConfigureFileHandler.h',['../_training_configure_file_handler_8h.html',1,'']]],
  ['trainingconfiguretool_2ecpp_327',['TrainingConfigureTool.cpp',['../_training_configure_tool_8cpp.html',1,'']]],
  ['trainingdriver_2ecpp_328',['TrainingDriver.cpp',['../_training_driver_8cpp.html',1,'']]],
  ['trainingdriverhandler_2ecpp_329',['TrainingDriverHandler.cpp',['../_training_driver_handler_8cpp.html',1,'']]],
  ['trainingdriverhandler_2eh_330',['TrainingDriverHandler.h',['../_training_driver_handler_8h.html',1,'']]],
  ['traininggraph_2ecpp_331',['TrainingGraph.cpp',['../_training_graph_8cpp.html',1,'']]],
  ['traininggraph_2eh_332',['TrainingGraph.h',['../_training_graph_8h.html',1,'']]],
  ['traininginfo_2ecc_333',['TrainingInfo.cc',['../_training_info_8cc.html',1,'']]],
  ['traininginfo_2eh_334',['TrainingInfo.h',['../_training_info_8h.html',1,'']]],
  ['trainingmodule_2ecpp_335',['TrainingModule.cpp',['../_training_module_8cpp.html',1,'']]],
  ['trainingmodule_2eh_336',['TrainingModule.h',['../_training_module_8h.html',1,'']]],
  ['trainingonertmicro_2ecpp_337',['TrainingOnertMicro.cpp',['../_training_onert_micro_8cpp.html',1,'']]],
  ['trainingonertmicro_2eh_338',['TrainingOnertMicro.h',['../_training_onert_micro_8h.html',1,'']]],
  ['trainingsettings_2eh_339',['TrainingSettings.h',['../_training_settings_8h.html',1,'']]],
  ['transfer_5flearning_2emd_340',['transfer_learning.md',['../transfer__learning_8md.html',1,'']]],
  ['transform_2ecpp_341',['Transform.cpp',['../_transform_8cpp.html',1,'']]],
  ['transform_2eh_342',['Transform.h',['../_transform_8h.html',1,'']]],
  ['transformminmaxtorelu6pass_2ecpp_343',['TransformMinMaxToRelu6Pass.cpp',['../_transform_min_max_to_relu6_pass_8cpp.html',1,'']]],
  ['transformminmaxtorelu6pass_2eh_344',['TransformMinMaxToRelu6Pass.h',['../_transform_min_max_to_relu6_pass_8h.html',1,'']]],
  ['transformminrelutorelu6pass_2ecpp_345',['TransformMinReluToRelu6Pass.cpp',['../_transform_min_relu_to_relu6_pass_8cpp.html',1,'']]],
  ['transformminrelutorelu6pass_2eh_346',['TransformMinReluToRelu6Pass.h',['../_transform_min_relu_to_relu6_pass_8h.html',1,'']]],
  ['transforms_2eh_347',['Transforms.h',['../_transforms_8h.html',1,'']]],
  ['transformsqrtdivtorsqrtmulpass_2ecpp_348',['TransformSqrtDivToRsqrtMulPass.cpp',['../_transform_sqrt_div_to_rsqrt_mul_pass_8cpp.html',1,'']]],
  ['transformsqrtdivtorsqrtmulpass_2eh_349',['TransformSqrtDivToRsqrtMulPass.h',['../_transform_sqrt_div_to_rsqrt_mul_pass_8h.html',1,'']]],
  ['transpose_2ecc_350',['Transpose.cc',['../_transpose_8cc.html',1,'']]],
  ['transpose_2ecpp_351',['transpose.cpp',['../onert-micro_2onert-micro_2src_2import_2kernels_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_transpose_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2execute_2kernels_2_transpose_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_transpose_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_transpose_8cpp.html',1,'(Global Namespace)']]],
  ['transpose_2eh_352',['transpose.h',['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_transpose_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_transpose_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_transpose_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_transpose_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_transpose_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_transpose_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_transpose_8h.html',1,'(Global Namespace)']]],
  ['transposeconv_2ecc_353',['TransposeConv.cc',['../_transpose_conv_8cc.html',1,'']]],
  ['transposeconv_2ecpp_354',['transposeconv.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2execute_2kernels_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2import_2kernels_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../runtime_2tools_2kbenchmark_2kernels_2acl__cl_2_transpose_conv_8cpp.html',1,'(Global Namespace)'],['../runtime_2tools_2kbenchmark_2kernels_2acl__neon_2_transpose_conv_8cpp.html',1,'(Global Namespace)']]],
  ['transposeconv_2eh_355',['transposeconv.h',['../compiler_2tflchef_2core_2src_2_op_2_transpose_conv_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_transpose_conv_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_transpose_conv_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_transpose_conv_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_transpose_conv_8h.html',1,'(Global Namespace)'],['../runtime_2tools_2kbenchmark_2operations_2_transpose_conv_8h.html',1,'(Global Namespace)']]],
  ['transposeconvoptions_2ecpp_356',['TransposeConvOptions.cpp',['../_transpose_conv_options_8cpp.html',1,'']]],
  ['transposeconvoptions_2eh_357',['TransposeConvOptions.h',['../_transpose_conv_options_8h.html',1,'']]],
  ['transposedconv2d_2ecpp_358',['TransposedConv2D.cpp',['../_transposed_conv2_d_8cpp.html',1,'']]],
  ['transposedconv2dconverter_2ecpp_359',['TransposedConv2DConverter.cpp',['../_transposed_conv2_d_converter_8cpp.html',1,'']]],
  ['transposedconv2dconverter_2eh_360',['TransposedConv2DConverter.h',['../_transposed_conv2_d_converter_8h.html',1,'']]],
  ['transposekernel_2eh_361',['TransposeKernel.h',['../_transpose_kernel_8h.html',1,'']]],
  ['transposelayer_2ecc_362',['TransposeLayer.cc',['../_transpose_layer_8cc.html',1,'']]],
  ['transposelayer_2eh_363',['TransposeLayer.h',['../_transpose_layer_8h.html',1,'']]],
  ['transposeop_2ecpp_364',['TransposeOp.cpp',['../_transpose_op_8cpp.html',1,'']]],
  ['transposeop_2eh_365',['TransposeOp.h',['../_transpose_op_8h.html',1,'']]],
  ['transposeoptions_2ecpp_366',['TransposeOptions.cpp',['../_transpose_options_8cpp.html',1,'']]],
  ['transposeoptions_2eh_367',['TransposeOptions.h',['../_transpose_options_8h.html',1,'']]],
  ['trix_2ecc_368',['trix.cc',['../trix_8cc.html',1,'']]],
  ['trixengineconfigversion_2eextra_2ecpp_369',['TRIXEngineConfigVersion.extra.cpp',['../_t_r_i_x_engine_config_version_8extra_8cpp.html',1,'']]],
  ['trixengineconfigversion_2emajor_2ecpp_370',['TRIXEngineConfigVersion.major.cpp',['../_t_r_i_x_engine_config_version_8major_8cpp.html',1,'']]],
  ['trixengineconfigversion_2eminor_2ecpp_371',['TRIXEngineConfigVersion.minor.cpp',['../_t_r_i_x_engine_config_version_8minor_8cpp.html',1,'']]],
  ['trixloader_2ecc_372',['TrixLoader.cc',['../_trix_loader_8cc.html',1,'']]],
  ['typeinference_2ecpp_373',['TypeInference.cpp',['../_type_inference_8cpp.html',1,'']]],
  ['typeinference_2eh_374',['TypeInference.h',['../_type_inference_8h.html',1,'']]],
  ['typeinferencepass_2ecpp_375',['typeinferencepass.cpp',['../exo_2src_2_pass_2_type_inference_pass_8cpp.html',1,'(Global Namespace)'],['../moco-tf_2src_2_transforms_2_type_inference_pass_8cpp.html',1,'(Global Namespace)']]],
  ['typeinferencepass_2eh_376',['typeinferencepass.h',['../exo_2src_2_pass_2_type_inference_pass_8h.html',1,'(Global Namespace)'],['../moco-tf_2src_2_transforms_2_type_inference_pass_8h.html',1,'(Global Namespace)']]],
  ['typeinfo_2ecc_377',['TypeInfo.cc',['../_type_info_8cc.html',1,'']]],
  ['typeinfo_2eh_378',['TypeInfo.h',['../_type_info_8h.html',1,'']]],
  ['typemapper_2ecpp_379',['TypeMapper.cpp',['../_type_mapper_8cpp.html',1,'']]],
  ['typemapper_2eh_380',['TypeMapper.h',['../_type_mapper_8h.html',1,'']]],
  ['types_2eh_381',['types.h',['../compiler_2luci-compute_2include_2luci__compute_2_types_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2train_2_types_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2_types_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2ruy_2include_2ruy_2_types_8h.html',1,'(Global Namespace)']]],
  ['typesex_2eh_382',['TypesEx.h',['../_types_ex_8h.html',1,'']]]
];
