var searchData=
[
  ['backend_2dapi_2emd_0',['backend-api.md',['../backend-api_8md.html',1,'']]],
  ['backend_2ecpp_1',['backend.cpp',['../nnkit-tflite_2support_2src_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-tflite_2backend_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-tf_2support_2src_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-tf_2backend_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-onnxrt_2support_2src_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-onnxrt_2backend_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-mocotf_2support_2src_2_backend_8cpp.html',1,'(Global Namespace)'],['../nnkit-mocotf_2backend_2_backend_8cpp.html',1,'(Global Namespace)'],['../enco_2core_2src_2_backend_8cpp.html',1,'(Global Namespace)']]],
  ['backend_2eh_2',['backend.h',['../compiler_2enco_2core_2include_2enco_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2backend_2builtin_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2backend_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2trix_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2train_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2ruy_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2cpu_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2acl__neon_2_backend_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2backend_2acl__cl_2_backend_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-tf_2support_2include_2nnkit_2support_2tf_2_backend_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-onnxrt_2support_2include_2nnkit_2support_2onnx_2_backend_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-mocotf_2support_2include_2nnkit_2support_2moco_2tf_2_backend_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-intf_2backend_2include_2nnkit_2_backend_8h.html',1,'(Global Namespace)'],['../compiler_2nnkit-caffe_2support_2include_2nnkit_2support_2caffe_2_backend_8h.html',1,'(Global Namespace)']]],
  ['backendcontext_2ecc_3',['backendcontext.cc',['../backend_2ruy_2_backend_context_8cc.html',1,'(Global Namespace)'],['../backend_2cpu_2_backend_context_8cc.html',1,'(Global Namespace)'],['../backend_2train_2_backend_context_8cc.html',1,'(Global Namespace)'],['../backend_2trix_2_backend_context_8cc.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2_backend_context_8cc.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2train_2_backend_context_8cc.html',1,'(Global Namespace)'],['../core_2src_2backend_2_backend_context_8cc.html',1,'(Global Namespace)']]],
  ['backendcontext_2eh_4',['backendcontext.h',['../backend_2trix_2_backend_context_8h.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2train_2_backend_context_8h.html',1,'(Global Namespace)'],['../core_2src_2backend_2builtin_2_backend_context_8h.html',1,'(Global Namespace)'],['../core_2include_2backend_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2train_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2ruy_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2cpu_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2cl__common_2include_2cl__common_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2acl__cl_2_backend_context_8h.html',1,'(Global Namespace)'],['../backend_2acl__neon_2_backend_context_8h.html',1,'(Global Namespace)']]],
  ['backendcontexthelpers_2ecc_5',['BackendContextHelpers.cc',['../_backend_context_helpers_8cc.html',1,'']]],
  ['backendcontexthelpers_2eh_6',['BackendContextHelpers.h',['../_backend_context_helpers_8h.html',1,'']]],
  ['backendmanager_2ecc_7',['BackendManager.cc',['../_backend_manager_8cc.html',1,'']]],
  ['backendmanager_2eh_8',['BackendManager.h',['../_backend_manager_8h.html',1,'']]],
  ['backendplugin_2ecpp_9',['BackendPlugin.cpp',['../_backend_plugin_8cpp.html',1,'']]],
  ['backendplugin_2eh_10',['BackendPlugin.h',['../_backend_plugin_8h.html',1,'']]],
  ['backendresolver_2ecc_11',['BackendResolver.cc',['../_backend_resolver_8cc.html',1,'']]],
  ['backendresolver_2eh_12',['BackendResolver.h',['../_backend_resolver_8h.html',1,'']]],
  ['backends_2epy_13',['backends.py',['../backends_8py.html',1,'']]],
  ['backendset_2eh_14',['BackendSet.h',['../_backend_set_8h.html',1,'']]],
  ['background_2emd_15',['background.md',['../background_8md.html',1,'']]],
  ['backpropaccumulator_2ecc_16',['BackPropAccumulator.cc',['../_back_prop_accumulator_8cc.html',1,'']]],
  ['backpropaccumulator_2eh_17',['BackPropAccumulator.h',['../_back_prop_accumulator_8h.html',1,'']]],
  ['backpropinitializer_2ecc_18',['BackPropInitializer.cc',['../_back_prop_initializer_8cc.html',1,'']]],
  ['backpropinitializer_2eh_19',['BackPropInitializer.h',['../_back_prop_initializer_8h.html',1,'']]],
  ['bag_2ecpp_20',['Bag.cpp',['../_bag_8cpp.html',1,'']]],
  ['bag_2eh_21',['Bag.h',['../_bag_8h.html',1,'']]],
  ['bagmanager_2ecpp_22',['BagManager.cpp',['../_bag_manager_8cpp.html',1,'']]],
  ['bagmanager_2eh_23',['BagManager.h',['../_bag_manager_8h.html',1,'']]],
  ['base_2eh_24',['base.h',['../base_8h.html',1,'']]],
  ['baseloader_2eh_25',['BaseLoader.h',['../_base_loader_8h.html',1,'']]],
  ['basesession_2epy_26',['basesession.py',['../basesession_8py.html',1,'']]],
  ['batchmatmul_2ecc_27',['BatchMatMul.cc',['../_batch_mat_mul_8cc.html',1,'']]],
  ['batchmatmul_2ecpp_28',['batchmatmul.cpp',['../compiler_2circlechef_2core_2src_2_op_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2execute_2kernels_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2import_2kernels_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)'],['../compiler_2circlechef_2circle_2src_2_op_2_batch_mat_mul_8cpp.html',1,'(Global Namespace)']]],
  ['batchmatmul_2eh_29',['batchmatmul.h',['../onert-micro_2luci-interpreter_2src_2kernels_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../compiler_2circlechef_2core_2src_2_op_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../compiler_2circlechef_2circle_2src_2_op_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2optimized_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2reference_2_batch_mat_mul_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_batch_mat_mul_8h.html',1,'(Global Namespace)']]],
  ['batchmatmullayer_2ecc_30',['BatchMatMulLayer.cc',['../_batch_mat_mul_layer_8cc.html',1,'']]],
  ['batchmatmullayer_2eh_31',['BatchMatMulLayer.h',['../_batch_mat_mul_layer_8h.html',1,'']]],
  ['batchmatmuloptions_2ecpp_32',['BatchMatMulOptions.cpp',['../_batch_mat_mul_options_8cpp.html',1,'']]],
  ['batchmatmuloptions_2eh_33',['BatchMatMulOptions.h',['../_batch_mat_mul_options_8h.html',1,'']]],
  ['batchmatmulparams_2eh_34',['BatchMatMulParams.h',['../_batch_mat_mul_params_8h.html',1,'']]],
  ['batchmatmulv2_2ecpp_35',['BatchMatMulV2.cpp',['../_batch_mat_mul_v2_8cpp.html',1,'']]],
  ['batchmatmulv2_2eh_36',['BatchMatMulV2.h',['../_batch_mat_mul_v2_8h.html',1,'']]],
  ['batchnorm_2ecpp_37',['BatchNorm.cpp',['../_batch_norm_8cpp.html',1,'']]],
  ['batchnorm_2eh_38',['BatchNorm.h',['../_batch_norm_8h.html',1,'']]],
  ['batchnormalization_2ecpp_39',['BatchNormalization.cpp',['../_batch_normalization_8cpp.html',1,'']]],
  ['batchnormalization_2eh_40',['BatchNormalization.h',['../_batch_normalization_8h.html',1,'']]],
  ['batchnormpatternfinder_2ecpp_41',['BatchNormPatternFinder.cpp',['../_batch_norm_pattern_finder_8cpp.html',1,'']]],
  ['batchnormpatternfinder_2eh_42',['BatchNormPatternFinder.h',['../_batch_norm_pattern_finder_8h.html',1,'']]],
  ['batchthreadpool_2ecc_43',['BatchThreadPool.cc',['../_batch_thread_pool_8cc.html',1,'']]],
  ['batchthreadpool_2eh_44',['BatchThreadPool.h',['../_batch_thread_pool_8h.html',1,'']]],
  ['batchtospacend_2ecc_45',['batchtospacend.cc',['../core_2src_2ir_2operation_2_batch_to_space_n_d_8cc.html',1,'(Global Namespace)'],['../backend_2acl__cl_2ops_2_batch_to_space_n_d_8cc.html',1,'(Global Namespace)']]],
  ['batchtospacend_2ecpp_46',['batchtospacend.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2import_2kernels_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2onert-micro_2src_2execute_2kernels_2_batch_to_space_n_d_8cpp.html',1,'(Global Namespace)']]],
  ['batchtospacend_2eh_47',['batchtospacend.h',['../runtime_2onert_2core_2include_2ir_2operation_2_batch_to_space_n_d_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_batch_to_space_n_d_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_batch_to_space_n_d_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_batch_to_space_n_d_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_batch_to_space_n_d_8h.html',1,'(Global Namespace)']]],
  ['batchtospacendlayer_2ecc_48',['BatchToSpaceNDLayer.cc',['../_batch_to_space_n_d_layer_8cc.html',1,'']]],
  ['batchtospacendlayer_2eh_49',['BatchToSpaceNDLayer.h',['../_batch_to_space_n_d_layer_8h.html',1,'']]],
  ['batchtospacendoptions_2ecpp_50',['BatchToSpaceNDOptions.cpp',['../_batch_to_space_n_d_options_8cpp.html',1,'']]],
  ['batchtospacendoptions_2eh_51',['BatchToSpaceNDOptions.h',['../_batch_to_space_n_d_options_8h.html',1,'']]],
  ['bcast_2eh_52',['BCast.h',['../_b_cast_8h.html',1,'']]],
  ['bcqfullyconnected_2ecc_53',['BCQFullyConnected.cc',['../_b_c_q_fully_connected_8cc.html',1,'']]],
  ['bcqfullyconnected_2ecpp_54',['bcqfullyconnected.cpp',['../circle_2src_2_op_2_b_c_q_fully_connected_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_b_c_q_fully_connected_8cpp.html',1,'(Global Namespace)']]],
  ['bcqfullyconnected_2eh_55',['bcqfullyconnected.h',['../compiler_2circlechef_2core_2src_2_op_2_b_c_q_fully_connected_8h.html',1,'(Global Namespace)'],['../compiler_2circlechef_2circle_2src_2_op_2_b_c_q_fully_connected_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_b_c_q_fully_connected_8h.html',1,'(Global Namespace)']]],
  ['bcqgather_2ecc_56',['BCQGather.cc',['../_b_c_q_gather_8cc.html',1,'']]],
  ['bcqgather_2ecpp_57',['bcqgather.cpp',['../core_2src_2_op_2_b_c_q_gather_8cpp.html',1,'(Global Namespace)'],['../circle_2src_2_op_2_b_c_q_gather_8cpp.html',1,'(Global Namespace)']]],
  ['bcqgather_2eh_58',['bcqgather.h',['../runtime_2onert_2core_2include_2ir_2operation_2_b_c_q_gather_8h.html',1,'(Global Namespace)'],['../compiler_2circlechef_2core_2src_2_op_2_b_c_q_gather_8h.html',1,'(Global Namespace)'],['../compiler_2circlechef_2circle_2src_2_op_2_b_c_q_gather_8h.html',1,'(Global Namespace)']]],
  ['bcqunembedding_2ecc_59',['BCQUnembedding.cc',['../_b_c_q_unembedding_8cc.html',1,'']]],
  ['bcqunembedding_2eh_60',['BCQUnembedding.h',['../_b_c_q_unembedding_8h.html',1,'']]],
  ['benchmark_2ecpp_61',['Benchmark.cpp',['../_benchmark_8cpp.html',1,'']]],
  ['bias_5fop_2eh_62',['bias_op.h',['../bias__op_8h.html',1,'']]],
  ['biasadd_2ecpp_63',['biasadd.cpp',['../moco_2import_2src_2_nodes_2_bias_add_8cpp.html',1,'(Global Namespace)'],['../locomotiv_2src_2_node_2_bias_add_8cpp.html',1,'(Global Namespace)']]],
  ['biasadd_2eh_64',['BiasAdd.h',['../_bias_add_8h.html',1,'']]],
  ['biasaddcanonicalizer_2ecpp_65',['BiasAddCanonicalizer.cpp',['../_bias_add_canonicalizer_8cpp.html',1,'']]],
  ['biasaddcanonicalizer_2eh_66',['BiasAddCanonicalizer.h',['../_bias_add_canonicalizer_8h.html',1,'']]],
  ['biasencode_2ecpp_67',['BiasEncode.cpp',['../_bias_encode_8cpp.html',1,'']]],
  ['biasshape_2eh_68',['BiasShape.h',['../_bias_shape_8h.html',1,'']]],
  ['bidirectionalsequencelstm_2ecpp_69',['bidirectionalsequencelstm.cpp',['../tflite_2src_2_op_2_bidirectional_sequence_l_s_t_m_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_bidirectional_sequence_l_s_t_m_8cpp.html',1,'(Global Namespace)']]],
  ['bidirectionalsequencelstm_2eh_70',['bidirectionalsequencelstm.h',['../tflite_2src_2_op_2include_2_bidirectional_sequence_l_s_t_m_8h.html',1,'(Global Namespace)'],['../core_2src_2_op_2_bidirectional_sequence_l_s_t_m_8h.html',1,'(Global Namespace)']]],
  ['bidirectionalsequencelstmoptions_2ecpp_71',['BidirectionalSequenceLSTMOptions.cpp',['../_bidirectional_sequence_l_s_t_m_options_8cpp.html',1,'']]],
  ['bidirectionalsequencelstmoptions_2eh_72',['BidirectionalSequenceLSTMOptions.h',['../_bidirectional_sequence_l_s_t_m_options_8h.html',1,'']]],
  ['binaryarithmetic_2ecc_73',['binaryarithmetic.cc',['../core_2src_2ir_2operation_2_binary_arithmetic_8cc.html',1,'(Global Namespace)'],['../backend_2acl__cl_2ops_2_binary_arithmetic_8cc.html',1,'(Global Namespace)'],['../core_2src_2ir_2train_2operation_2_binary_arithmetic_8cc.html',1,'(Global Namespace)']]],
  ['binaryarithmetic_2eh_74',['binaryarithmetic.h',['../onert_2core_2include_2ir_2train_2operation_2_binary_arithmetic_8h.html',1,'(Global Namespace)'],['../onert_2core_2include_2ir_2operation_2_binary_arithmetic_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2train_2operation_2_binary_arithmetic_8h.html',1,'(Global Namespace)']]],
  ['binaryarithmeticlayer_2ecc_75',['binaryarithmeticlayer.cc',['../train_2ops_2_binary_arithmetic_layer_8cc.html',1,'(Global Namespace)'],['../cpu_2ops_2_binary_arithmetic_layer_8cc.html',1,'(Global Namespace)']]],
  ['binaryarithmeticlayer_2eh_76',['binaryarithmeticlayer.h',['../cpu_2ops_2_binary_arithmetic_layer_8h.html',1,'(Global Namespace)'],['../train_2ops_2_binary_arithmetic_layer_8h.html',1,'(Global Namespace)']]],
  ['binaryarithmeticops_2eh_77',['binaryarithmeticops.h',['../_binary_arithmetic_ops_8h.html',1,'(Global Namespace)'],['../optimized_2_binary_arithmetic_ops_8h.html',1,'(Global Namespace)'],['../reference_2_binary_arithmetic_ops_8h.html',1,'(Global Namespace)']]],
  ['binaryelementwiseop_2ecpp_78',['BinaryElementwiseOp.cpp',['../_binary_elementwise_op_8cpp.html',1,'']]],
  ['binaryelementwiseop_2eh_79',['BinaryElementwiseOp.h',['../_binary_elementwise_op_8h.html',1,'']]],
  ['binaryopcommon_2eh_80',['binaryopcommon.h',['../compiler_2luci-interpreter_2src_2kernels_2_binary_op_common_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_binary_op_common_8h.html',1,'(Global Namespace)']]],
  ['binder_2eh_81',['Binder.h',['../_binder_8h.html',1,'']]],
  ['bino_2eh_82',['bino.h',['../bino_8h.html',1,'']]],
  ['bisectionsolver_2ecpp_83',['BisectionSolver.cpp',['../_bisection_solver_8cpp.html',1,'']]],
  ['bisectionsolver_2eh_84',['BisectionSolver.h',['../_bisection_solver_8h.html',1,'']]],
  ['blobcontext_2eh_85',['BlobContext.h',['../_blob_context_8h.html',1,'']]],
  ['block_2ecpp_86',['Block.cpp',['../_block_8cpp.html',1,'']]],
  ['block_2eforward_2eh_87',['Block.forward.h',['../_block_8forward_8h.html',1,'']]],
  ['block_2eh_88',['block.h',['../coco_2core_2include_2coco_2_i_r_2_block_8h.html',1,'(Global Namespace)'],['../nest_2core_2include_2nest_2_block_8h.html',1,'(Global Namespace)']]],
  ['blockindex_2ecpp_89',['BlockIndex.cpp',['../_block_index_8cpp.html',1,'']]],
  ['blockindex_2eh_90',['BlockIndex.h',['../_block_index_8h.html',1,'']]],
  ['blockmanager_2ecpp_91',['BlockManager.cpp',['../_block_manager_8cpp.html',1,'']]],
  ['blockmanager_2eh_92',['BlockManager.h',['../_block_manager_8h.html',1,'']]],
  ['boollogicalandkernel_2eh_93',['boollogicalandkernel.h',['../onert-micro_2include_2test__models_2logical__and_2_bool_logical_and_kernel_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__and_2_bool_logical_and_kernel_8h.html',1,'(Global Namespace)']]],
  ['boollogicalnotkernel_2eh_94',['boollogicalnotkernel.h',['../onert-micro_2include_2test__models_2logical__not_2_bool_logical_not_kernel_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__not_2_bool_logical_not_kernel_8h.html',1,'(Global Namespace)']]],
  ['boollogicalorkernel_2eh_95',['boollogicalorkernel.h',['../onert-micro_2include_2test__models_2logical__or_2_bool_logical_or_kernel_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2include_2luci__interpreter_2test__models_2logical__or_2_bool_logical_or_kernel_8h.html',1,'(Global Namespace)']]],
  ['bound_2eh_96',['Bound.h',['../_bound_8h.html',1,'']]],
  ['broadcast_2eh_97',['Broadcast.h',['../_broadcast_8h.html',1,'']]],
  ['broadcasthelper_2ecpp_98',['BroadcastHelper.cpp',['../_broadcast_helper_8cpp.html',1,'']]],
  ['broadcasthelper_2eh_99',['BroadcastHelper.h',['../_broadcast_helper_8h.html',1,'']]],
  ['broadcastop_2ecpp_100',['BroadcastOp.cpp',['../_broadcast_op_8cpp.html',1,'']]],
  ['broadcastop_2eh_101',['BroadcastOp.h',['../_broadcast_op_8h.html',1,'']]],
  ['broadcastto_2ecc_102',['BroadcastTo.cc',['../_broadcast_to_8cc.html',1,'']]],
  ['broadcastto_2ecpp_103',['broadcastto.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_broadcast_to_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_broadcast_to_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_broadcast_to_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_custom_op_2_broadcast_to_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_broadcast_to_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_broadcast_to_8cpp.html',1,'(Global Namespace)']]],
  ['broadcastto_2eh_104',['broadcastto.h',['../runtime_2onert_2core_2include_2ir_2operation_2_broadcast_to_8h.html',1,'(Global Namespace)'],['../runtime_2compute_2cker_2include_2cker_2operation_2_broadcast_to_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_broadcast_to_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_broadcast_to_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_custom_op_2_broadcast_to_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_broadcast_to_8h.html',1,'(Global Namespace)']]],
  ['broadcasttolayer_2ecc_105',['BroadcastToLayer.cc',['../_broadcast_to_layer_8cc.html',1,'']]],
  ['broadcasttolayer_2eh_106',['BroadcastToLayer.h',['../_broadcast_to_layer_8h.html',1,'']]],
  ['broadcasttooptions_2ecpp_107',['BroadcastToOptions.cpp',['../_broadcast_to_options_8cpp.html',1,'']]],
  ['broadcasttooptions_2eh_108',['BroadcastToOptions.h',['../_broadcast_to_options_8h.html',1,'']]],
  ['buddymemorymanager_2ecpp_109',['buddymemorymanager.cpp',['../compiler_2luci-interpreter_2src_2_buddy_memory_manager_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2memory__managers_2_buddy_memory_manager_8cpp.html',1,'(Global Namespace)']]],
  ['buddymemorymanager_2eh_110',['buddymemorymanager.h',['../compiler_2luci-interpreter_2include_2luci__interpreter_2_buddy_memory_manager_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2memory__managers_2_buddy_memory_manager_8h.html',1,'(Global Namespace)']]],
  ['buffer_2eh_111',['buffer.h',['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2tensor_2_buffer_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2feature_2_buffer_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2kernel_2_buffer_8h.html',1,'(Global Namespace)'],['../onert-micro_2externals_2flatbuffers_2_buffer_8h.html',1,'(Global Namespace)']]],
  ['buffer_5fref_2eh_112',['buffer_ref.h',['../buffer__ref_8h.html',1,'']]],
  ['buildbuiltinoptions_2eh_113',['BuildBuiltinOptions.h',['../_build_builtin_options_8h.html',1,'']]],
  ['builders_2eh_114',['builders.h',['../onert-micro_2luci-interpreter_2src_2kernels_2_builders_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_builders_8h.html',1,'(Global Namespace)']]],
  ['bulk_2ecc_115',['Bulk.cc',['../_bulk_8cc.html',1,'']]],
  ['bulk_2eh_116',['Bulk.h',['../_bulk_8h.html',1,'']]],
  ['bulklayer_2ecc_117',['BulkLayer.cc',['../_bulk_layer_8cc.html',1,'']]],
  ['bulklayer_2eh_118',['BulkLayer.h',['../_bulk_layer_8h.html',1,'']]],
  ['bundle_2eh_119',['Bundle.h',['../_bundle_8h.html',1,'']]]
];
