var searchData=
[
  ['randomdatagenerator_2epy_0',['RandomDataGenerator.py',['../_random_data_generator_8py.html',1,'']]],
  ['randomdistributions_2eh_1',['RandomDistributions.h',['../_random_distributions_8h.html',1,'']]],
  ['randomgenerator_2ecpp_2',['RandomGenerator.cpp',['../_random_generator_8cpp.html',1,'']]],
  ['randomgenerator_2eh_3',['RandomGenerator.h',['../_random_generator_8h.html',1,'']]],
  ['randominputinitializer_2ecpp_4',['RandomInputInitializer.cpp',['../_random_input_initializer_8cpp.html',1,'']]],
  ['randominputinitializer_2eh_5',['RandomInputInitializer.h',['../_random_input_initializer_8h.html',1,'']]],
  ['randomize_2ecpp_6',['Randomize.cpp',['../_randomize_8cpp.html',1,'']]],
  ['randommodel_2ecpp_7',['RandomModel.cpp',['../_random_model_8cpp.html',1,'']]],
  ['randommodel_2eh_8',['RandomModel.h',['../_random_model_8h.html',1,'']]],
  ['randomop_2eh_9',['RandomOp.h',['../_random_op_8h.html',1,'']]],
  ['randomopcpu_2eh_10',['RandomOpCpu.h',['../_random_op_cpu_8h.html',1,'']]],
  ['randomutils_2ecpp_11',['RandomUtils.cpp',['../_random_utils_8cpp.html',1,'']]],
  ['randomutils_2eh_12',['RandomUtils.h',['../_random_utils_8h.html',1,'']]],
  ['range_2ecc_13',['Range.cc',['../_range_8cc.html',1,'']]],
  ['range_2ecpp_14',['Range.cpp',['../core_2src_2_op_2_range_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_range_8cpp.html',1,'(Global Namespace)']]],
  ['range_2eh_15',['Range.h',['../runtime_2onert_2core_2include_2ir_2operation_2_range_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_range_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_range_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_range_8h.html',1,'(Global Namespace)']]],
  ['rangedarguments_2eh_16',['RangedArguments.h',['../_ranged_arguments_8h.html',1,'']]],
  ['rangelayer_2ecc_17',['RangeLayer.cc',['../_range_layer_8cc.html',1,'']]],
  ['rangelayer_2eh_18',['RangeLayer.h',['../_range_layer_8h.html',1,'']]],
  ['rangeoptions_2ecpp_19',['RangeOptions.cpp',['../_range_options_8cpp.html',1,'']]],
  ['rangeoptions_2eh_20',['RangeOptions.h',['../_range_options_8h.html',1,'']]],
  ['rank_2ecc_21',['Rank.cc',['../_rank_8cc.html',1,'']]],
  ['rank_2ecpp_22',['Rank.cpp',['../core_2src_2_op_2_rank_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_rank_8cpp.html',1,'(Global Namespace)']]],
  ['rank_2eh_23',['Rank.h',['../compiler_2tflchef_2tflite_2src_2_op_2include_2_rank_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_rank_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_rank_8h.html',1,'(Global Namespace)']]],
  ['ranklayer_2ecc_24',['RankLayer.cc',['../_rank_layer_8cc.html',1,'']]],
  ['ranklayer_2eh_25',['RankLayer.h',['../_rank_layer_8h.html',1,'']]],
  ['rankoptions_2ecpp_26',['RankOptions.cpp',['../_rank_options_8cpp.html',1,'']]],
  ['rankoptions_2eh_27',['RankOptions.h',['../_rank_options_8h.html',1,'']]],
  ['rawmodel_2eh_28',['RawModel.h',['../_raw_model_8h.html',1,'']]],
  ['rawmodelloader_2ecpp_29',['RawModelLoader.cpp',['../_raw_model_loader_8cpp.html',1,'']]],
  ['rawmodelloader_2eh_30',['RawModelLoader.h',['../_raw_model_loader_8h.html',1,'']]],
  ['read_2ecpp_31',['Read.cpp',['../coco_2core_2src_2_i_r_2_read_8cpp.html',1,'(Global Namespace)'],['../tfldump_2src_2_read_8cpp.html',1,'(Global Namespace)']]],
  ['read_2eforward_2eh_32',['Read.forward.h',['../_read_8forward_8h.html',1,'']]],
  ['read_2eh_33',['Read.h',['../coco_2core_2include_2coco_2_i_r_2_read_8h.html',1,'(Global Namespace)'],['../tfldump_2src_2_read_8h.html',1,'(Global Namespace)']]],
  ['reader_2ecpp_34',['Reader.cpp',['../mio-circle05_2src_2_reader_8cpp.html',1,'(Global Namespace)'],['../angkor_2src_2_a_d_t_2feature_2_reader_8cpp.html',1,'(Global Namespace)'],['../mio-circle04_2src_2_reader_8cpp.html',1,'(Global Namespace)'],['../minmax-embedder_2src_2h5_2_reader_8cpp.html',1,'(Global Namespace)'],['../angkor_2src_2_a_d_t_2tensor_2_reader_8cpp.html',1,'(Global Namespace)'],['../angkor_2src_2_a_d_t_2kernel_2_reader_8cpp.html',1,'(Global Namespace)'],['../mio-circle06_2src_2_reader_8cpp.html',1,'(Global Namespace)'],['../mio-circle07_2src_2_reader_8cpp.html',1,'(Global Namespace)'],['../tfl-inspect_2src_2_reader_8cpp.html',1,'(Global Namespace)']]],
  ['reader_2eh_35',['Reader.h',['../runtime_2onert_2core_2src_2exec_2feature_2nhwc_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2exec_2feature_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2kernel_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2vector_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2tensor_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2src_2exec_2feature_2nchw_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2matrix_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2feature_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2kernel_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2angkor_2include_2nncc_2core_2_a_d_t_2tensor_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2minmax-embedder_2src_2h5_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2mio-circle04_2include_2mio__circle_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2mio-circle05_2include_2mio__circle_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2mio-circle06_2include_2mio__circle_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2mio-circle07_2include_2mio__circle_2_reader_8h.html',1,'(Global Namespace)'],['../compiler_2tfl-inspect_2src_2_reader_8h.html',1,'(Global Namespace)'],['../runtime_2libs_2misc_2include_2misc_2feature_2_reader_8h.html',1,'(Global Namespace)']]],
  ['reader_2emock_2eh_36',['Reader.mock.h',['../_reader_8mock_8h.html',1,'']]],
  ['readme_2emd_37',['README.md',['../_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../onert-micro_2examples_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)'],['../onert-micro_2_r_e_a_d_m_e_8md.html',1,'(Global Namespace)']]],
  ['readmodule_2ecpp_38',['ReadModule.cpp',['../_read_module_8cpp.html',1,'']]],
  ['readmodule_2eh_39',['ReadModule.h',['../_read_module_8h.html',1,'']]],
  ['readset_2eh_40',['ReadSet.h',['../_read_set_8h.html',1,'']]],
  ['readtester_2ecpp_41',['ReadTester.cpp',['../_read_tester_8cpp.html',1,'']]],
  ['realdiv_2ecpp_42',['RealDiv.cpp',['../_real_div_8cpp.html',1,'']]],
  ['realdiv_2eh_43',['RealDiv.h',['../_real_div_8h.html',1,'']]],
  ['realdivcanonicalizer_2ecpp_44',['RealDivCanonicalizer.cpp',['../_real_div_canonicalizer_8cpp.html',1,'']]],
  ['realdivcanonicalizer_2eh_45',['RealDivCanonicalizer.h',['../_real_div_canonicalizer_8h.html',1,'']]],
  ['recipechef_2ecpp_46',['RecipeChef.cpp',['../tflchef_2tflite_2src_2_recipe_chef_8cpp.html',1,'(Global Namespace)'],['../circlechef_2circle_2src_2_recipe_chef_8cpp.html',1,'(Global Namespace)']]],
  ['recipechef_2eh_47',['RecipeChef.h',['../circlechef_2circle_2include_2circlechef_2_recipe_chef_8h.html',1,'(Global Namespace)'],['../tflchef_2tflite_2include_2tflchef_2_recipe_chef_8h.html',1,'(Global Namespace)']]],
  ['reciprocal_2ecpp_48',['Reciprocal.cpp',['../_reciprocal_8cpp.html',1,'']]],
  ['reciprocal_2eh_49',['Reciprocal.h',['../_reciprocal_8h.html',1,'']]],
  ['recordfunction_2ecpp_50',['RecordFunction.cpp',['../_record_function_8cpp.html',1,'']]],
  ['recordfunction_2eh_51',['RecordFunction.h',['../_record_function_8h.html',1,'']]],
  ['recordminmax_2ecpp_52',['RecordMinMax.cpp',['../_record_min_max_8cpp.html',1,'']]],
  ['recordminmax_2eh_53',['RecordMinMax.h',['../_record_min_max_8h.html',1,'']]],
  ['reduce_2ecc_54',['Reduce.cc',['../train_2operation_2_reduce_8cc.html',1,'(Global Namespace)'],['../operation_2_reduce_8cc.html',1,'(Global Namespace)']]],
  ['reduce_2eh_55',['Reduce.h',['../compute_2cker_2include_2cker_2operation_2_reduce_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2train_2operation_2_reduce_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_reduce_8h.html',1,'(Global Namespace)']]],
  ['reduceany_2ecpp_56',['ReduceAny.cpp',['../core_2src_2_op_2_reduce_any_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_reduce_any_8cpp.html',1,'(Global Namespace)']]],
  ['reduceany_2eh_57',['ReduceAny.h',['../core_2src_2_op_2_reduce_any_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_reduce_any_8h.html',1,'(Global Namespace)']]],
  ['reducecommon_2ecpp_58',['ReduceCommon.cpp',['../_reduce_common_8cpp.html',1,'']]],
  ['reducelayer_2ecc_59',['ReduceLayer.cc',['../_reduce_layer_8cc.html',1,'']]],
  ['reducelayer_2eh_60',['ReduceLayer.h',['../_reduce_layer_8h.html',1,'']]],
  ['reducemax_2ecpp_61',['ReduceMax.cpp',['../compiler_2tflchef_2tflite_2src_2_op_2_reduce_max_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_reduce_max_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_reduce_max_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_reduce_max_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_reduce_max_8cpp.html',1,'(Global Namespace)']]],
  ['reducemax_2eh_62',['ReduceMax.h',['../luci-interpreter_2src_2kernels_2_reduce_max_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_reduce_max_8h.html',1,'(Global Namespace)'],['../tflchef_2tflite_2src_2_op_2include_2_reduce_max_8h.html',1,'(Global Namespace)']]],
  ['reducemean_2ecpp_63',['ReduceMean.cpp',['../mir-interpreter_2src_2ops_2_reduce_mean_8cpp.html',1,'(Global Namespace)'],['../mir_2src_2mir__onnx__importer_2_op_2_reduce_mean_8cpp.html',1,'(Global Namespace)']]],
  ['reducemean_2eh_64',['ReduceMean.h',['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_reduce_mean_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_reduce_mean_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_reduce_mean_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2train_2operation_2_reduce_mean_8h.html',1,'(Global Namespace)']]],
  ['reducemeanop_2eh_65',['ReduceMeanOp.h',['../_reduce_mean_op_8h.html',1,'']]],
  ['reducemin_2ecpp_66',['ReduceMin.cpp',['../core_2src_2_op_2_reduce_min_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_reduce_min_8cpp.html',1,'(Global Namespace)']]],
  ['reducemin_2eh_67',['ReduceMin.h',['../tflite_2src_2_op_2include_2_reduce_min_8h.html',1,'(Global Namespace)'],['../core_2src_2_op_2_reduce_min_8h.html',1,'(Global Namespace)']]],
  ['reduceop_2ecpp_68',['ReduceOp.cpp',['../_reduce_op_8cpp.html',1,'']]],
  ['reduceop_2eh_69',['ReduceOp.h',['../_reduce_op_8h.html',1,'']]],
  ['reduceprod_2ecpp_70',['ReduceProd.cpp',['../tflchef_2tflite_2src_2_op_2_reduce_prod_8cpp.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_reduce_prod_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2loader_2nodes_2_reduce_prod_8cpp.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_reduce_prod_8cpp.html',1,'(Global Namespace)']]],
  ['reduceprod_2eh_71',['ReduceProd.h',['../tflchef_2tflite_2src_2_op_2include_2_reduce_prod_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_reduce_prod_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_reduce_prod_8h.html',1,'(Global Namespace)']]],
  ['reduceprodkernel_2eh_72',['ReduceProdKernel.h',['../_reduce_prod_kernel_8h.html',1,'']]],
  ['reduceroptions_2ecpp_73',['ReducerOptions.cpp',['../_reducer_options_8cpp.html',1,'']]],
  ['reduceroptions_2eh_74',['ReducerOptions.h',['../_reducer_options_8h.html',1,'']]],
  ['reflection_2eh_75',['reflection.h',['../reflection_8h.html',1,'']]],
  ['region_2eh_76',['Region.h',['../_region_8h.html',1,'']]],
  ['registry_2eh_77',['registry.h',['../onert-micro_2externals_2flatbuffers_2_registry_8h.html',1,'']]],
  ['registry_2eh_78',['Registry.h',['../compiler_2souschef_2include_2souschef_2_registry_8h.html',1,'']]],
  ['relativeepsilonequal_2ecpp_79',['RelativeEpsilonEqual.cpp',['../_relative_epsilon_equal_8cpp.html',1,'']]],
  ['relativeepsilonequal_2eh_80',['RelativeEpsilonEqual.h',['../_relative_epsilon_equal_8h.html',1,'']]],
  ['relu_2ecpp_81',['ReLU.cpp',['../compiler_2mir-interpreter_2src_2ops_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2caffe_2src_2_layer_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2tflite_2src_2_op_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2locomotiv_2src_2_node_2_relu_8cpp.html',1,'(Global Namespace)']]],
  ['relu_2ecpp_82',['Relu.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_relu_8cpp.html',1,'(Global Namespace)']]],
  ['relu_2ecpp_83',['ReLU.cpp',['../compiler_2tflchef_2core_2src_2_op_2_relu_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_relu_8cpp.html',1,'(Global Namespace)']]],
  ['relu_2ecpp_84',['Relu.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_relu_8cpp.html',1,'']]],
  ['relu_2efloat_2ecpp_85',['ReLU.float.cpp',['../_re_l_u_8float_8cpp.html',1,'']]],
  ['relu_2efloat_2eh_86',['ReLU.float.h',['../_re_l_u_8float_8h.html',1,'']]],
  ['relu_2eh_87',['ReLU.h',['../compiler_2enco_2frontend_2caffe_2src_2_layer_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2train_2operation_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_re_l_u_8h.html',1,'(Global Namespace)']]],
  ['relu_2eh_88',['Relu.h',['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_re_l_u_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_re_l_u_8h.html',1,'(Global Namespace)']]],
  ['relu_2eh_89',['ReLU.h',['../compiler_2mir-interpreter_2src_2ops_2_re_l_u_8h.html',1,'']]],
  ['relu_2eh_90',['Relu.h',['../compiler_2luci-interpreter_2src_2kernels_2_re_l_u_8h.html',1,'']]],
  ['relu_2eh_91',['ReLU.h',['../compiler_2enco_2frontend_2tflite_2src_2_op_2_re_l_u_8h.html',1,'']]],
  ['relu6_2ecpp_92',['Relu6.cpp',['../onert-micro_2luci-interpreter_2src_2kernels_2_relu6_8cpp.html',1,'']]],
  ['relu6_2ecpp_93',['ReLU6.cpp',['../compiler_2ann-ref_2src_2ops_2_relu6_8cpp.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2tflite_2src_2_op_2_relu6_8cpp.html',1,'(Global Namespace)'],['../compiler_2locomotiv_2src_2_node_2_relu6_8cpp.html',1,'(Global Namespace)']]],
  ['relu6_2ecpp_94',['Relu6.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_relu6_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_relu6_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_relu6_8cpp.html',1,'(Global Namespace)']]],
  ['relu6_2ecpp_95',['ReLU6.cpp',['../compiler_2tflchef_2core_2src_2_op_2_relu6_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_relu6_8cpp.html',1,'(Global Namespace)']]],
  ['relu6_2efloat_2ecpp_96',['ReLU6.float.cpp',['../_re_l_u6_8float_8cpp.html',1,'']]],
  ['relu6_2efloat_2eh_97',['ReLU6.float.h',['../_re_l_u6_8float_8h.html',1,'']]],
  ['relu6_2eh_98',['ReLU6.h',['../compute_2cker_2include_2cker_2train_2operation_2_re_l_u6_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_re_l_u6_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_re_l_u6_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_re_l_u6_8h.html',1,'(Global Namespace)']]],
  ['relu6_2eh_99',['Relu6.h',['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_re_l_u6_8h.html',1,'']]],
  ['relu6_2eh_100',['ReLU6.h',['../compiler_2ann-ref_2src_2ops_2_re_l_u6_8h.html',1,'']]],
  ['relu6_2eh_101',['Relu6.h',['../compiler_2luci-interpreter_2src_2kernels_2_re_l_u6_8h.html',1,'']]],
  ['relu6_2eh_102',['ReLU6.h',['../compiler_2enco_2frontend_2tflite_2src_2_op_2_re_l_u6_8h.html',1,'']]],
  ['relu6canonicalizer_2ecpp_103',['Relu6Canonicalizer.cpp',['../_relu6_canonicalizer_8cpp.html',1,'']]],
  ['relu6canonicalizer_2eh_104',['Relu6Canonicalizer.h',['../_relu6_canonicalizer_8h.html',1,'']]],
  ['relu6converter_2ecpp_105',['Relu6Converter.cpp',['../_relu6_converter_8cpp.html',1,'']]],
  ['relu6converter_2eh_106',['Relu6Converter.h',['../_relu6_converter_8h.html',1,'']]],
  ['relucanonicalizer_2ecpp_107',['ReluCanonicalizer.cpp',['../_relu_canonicalizer_8cpp.html',1,'']]],
  ['relucanonicalizer_2eh_108',['ReluCanonicalizer.h',['../_relu_canonicalizer_8h.html',1,'']]],
  ['reluconverter_2ecpp_109',['ReluConverter.cpp',['../_relu_converter_8cpp.html',1,'']]],
  ['reluconverter_2eh_110',['ReluConverter.h',['../_relu_converter_8h.html',1,'']]],
  ['relun1to1_2ecpp_111',['ReLUN1To1.cpp',['../tflite_2src_2_op_2_re_l_u_n1_to1_8cpp.html',1,'(Global Namespace)'],['../core_2src_2_op_2_re_l_u_n1_to1_8cpp.html',1,'(Global Namespace)']]],
  ['relun1to1_2eh_112',['ReLUN1To1.h',['../core_2src_2_op_2_re_l_u_n1_to1_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_re_l_u_n1_to1_8h.html',1,'(Global Namespace)']]],
  ['reluop_2eh_113',['ReluOp.h',['../_relu_op_8h.html',1,'']]],
  ['removedeadnodepass_2ecpp_114',['RemoveDeadNodePass.cpp',['../_remove_dead_node_pass_8cpp.html',1,'']]],
  ['removedeadnodepass_2eh_115',['RemoveDeadNodePass.h',['../_remove_dead_node_pass_8h.html',1,'']]],
  ['removedeadnodewithquerypass_2ecpp_116',['RemoveDeadNodeWithQueryPass.cpp',['../_remove_dead_node_with_query_pass_8cpp.html',1,'']]],
  ['removedeadnodewithquerypass_2eh_117',['RemoveDeadNodeWithQueryPass.h',['../_remove_dead_node_with_query_pass_8h.html',1,'']]],
  ['removeduplicateconstpass_2ecpp_118',['RemoveDuplicateConstPass.cpp',['../_remove_duplicate_const_pass_8cpp.html',1,'']]],
  ['removeduplicateconstpass_2eh_119',['RemoveDuplicateConstPass.h',['../_remove_duplicate_const_pass_8h.html',1,'']]],
  ['removefakequantpass_2ecpp_120',['RemoveFakeQuantPass.cpp',['../_remove_fake_quant_pass_8cpp.html',1,'']]],
  ['removefakequantpass_2eh_121',['RemoveFakeQuantPass.h',['../_remove_fake_quant_pass_8h.html',1,'']]],
  ['removeforwardnodepass_2ecpp_122',['RemoveForwardNodePass.cpp',['../_remove_forward_node_pass_8cpp.html',1,'']]],
  ['removeforwardnodepass_2eh_123',['RemoveForwardNodePass.h',['../_remove_forward_node_pass_8h.html',1,'']]],
  ['removequantdequantseqpass_2ecpp_124',['RemoveQuantDequantSeqPass.cpp',['../_remove_quant_dequant_seq_pass_8cpp.html',1,'']]],
  ['removequantdequantseqpass_2eh_125',['RemoveQuantDequantSeqPass.h',['../_remove_quant_dequant_seq_pass_8h.html',1,'']]],
  ['removeredundantdequantizepass_2ecpp_126',['RemoveRedundantDequantizePass.cpp',['../_remove_redundant_dequantize_pass_8cpp.html',1,'']]],
  ['removeredundantdequantizepass_2eh_127',['RemoveRedundantDequantizePass.h',['../_remove_redundant_dequantize_pass_8h.html',1,'']]],
  ['removeredundantquantizepass_2ecpp_128',['RemoveRedundantQuantizePass.cpp',['../_remove_redundant_quantize_pass_8cpp.html',1,'']]],
  ['removeredundantquantizepass_2eh_129',['RemoveRedundantQuantizePass.h',['../_remove_redundant_quantize_pass_8h.html',1,'']]],
  ['removeredundantreshape_2ecpp_130',['RemoveRedundantReshape.cpp',['../_remove_redundant_reshape_8cpp.html',1,'']]],
  ['removeredundantreshapepass_2eh_131',['RemoveRedundantReshapePass.h',['../_remove_redundant_reshape_pass_8h.html',1,'']]],
  ['removeredundanttransposepass_2ecpp_132',['RemoveRedundantTransposePass.cpp',['../_remove_redundant_transpose_pass_8cpp.html',1,'']]],
  ['removeredundanttransposepass_2eh_133',['RemoveRedundantTransposePass.h',['../_remove_redundant_transpose_pass_8h.html',1,'']]],
  ['removetfidentitynode_2ecpp_134',['RemoveTFIdentityNode.cpp',['../_remove_t_f_identity_node_8cpp.html',1,'']]],
  ['removetfidentitynode_2eh_135',['RemoveTFIdentityNode.h',['../_remove_t_f_identity_node_8h.html',1,'']]],
  ['removeunnecessaryaddpass_2ecpp_136',['RemoveUnnecessaryAddPass.cpp',['../_remove_unnecessary_add_pass_8cpp.html',1,'']]],
  ['removeunnecessaryaddpass_2eh_137',['RemoveUnnecessaryAddPass.h',['../_remove_unnecessary_add_pass_8h.html',1,'']]],
  ['removeunnecessaryreshapenetpass_2ecpp_138',['RemoveUnnecessaryReshapeNetPass.cpp',['../_remove_unnecessary_reshape_net_pass_8cpp.html',1,'']]],
  ['removeunnecessaryreshapenetpass_2eh_139',['RemoveUnnecessaryReshapeNetPass.h',['../_remove_unnecessary_reshape_net_pass_8h.html',1,'']]],
  ['removeunnecessaryreshapepass_2ecpp_140',['RemoveUnnecessaryReshapePass.cpp',['../_remove_unnecessary_reshape_pass_8cpp.html',1,'']]],
  ['removeunnecessaryreshapepass_2eh_141',['RemoveUnnecessaryReshapePass.h',['../_remove_unnecessary_reshape_pass_8h.html',1,'']]],
  ['removeunnecessaryslicepass_2ecpp_142',['RemoveUnnecessarySlicePass.cpp',['../_remove_unnecessary_slice_pass_8cpp.html',1,'']]],
  ['removeunnecessaryslicepass_2eh_143',['RemoveUnnecessarySlicePass.h',['../_remove_unnecessary_slice_pass_8h.html',1,'']]],
  ['removeunnecessarysplitpass_2ecpp_144',['RemoveUnnecessarySplitPass.cpp',['../_remove_unnecessary_split_pass_8cpp.html',1,'']]],
  ['removeunnecessarysplitpass_2eh_145',['RemoveUnnecessarySplitPass.h',['../_remove_unnecessary_split_pass_8h.html',1,'']]],
  ['removeunnecessarystridedslicepass_2ecpp_146',['RemoveUnnecessaryStridedSlicePass.cpp',['../_remove_unnecessary_strided_slice_pass_8cpp.html',1,'']]],
  ['removeunnecessarystridedslicepass_2eh_147',['RemoveUnnecessaryStridedSlicePass.h',['../_remove_unnecessary_strided_slice_pass_8h.html',1,'']]],
  ['removeunnecessarytransposenetpass_2ecpp_148',['RemoveUnnecessaryTransposeNetPass.cpp',['../_remove_unnecessary_transpose_net_pass_8cpp.html',1,'']]],
  ['removeunnecessarytransposenetpass_2eh_149',['RemoveUnnecessaryTransposeNetPass.h',['../_remove_unnecessary_transpose_net_pass_8h.html',1,'']]],
  ['reorderdecodepass_2ecpp_150',['ReorderDecodePass.cpp',['../_reorder_decode_pass_8cpp.html',1,'']]],
  ['reorderdecodepass_2eh_151',['ReorderDecodePass.h',['../_reorder_decode_pass_8h.html',1,'']]],
  ['repeat_2eh_152',['repeat.h',['../repeat_8h.html',1,'']]],
  ['replacemuladdwithdepthwiseconvpass_2ecpp_153',['ReplaceMulAddWithDepthwiseConvPass.cpp',['../_replace_mul_add_with_depthwise_conv_pass_8cpp.html',1,'']]],
  ['replacemuladdwithdepthwiseconvpass_2eh_154',['ReplaceMulAddWithDepthwiseConvPass.h',['../_replace_mul_add_with_depthwise_conv_pass_8h.html',1,'']]],
  ['replacenonconstfcwithbatchmatmulpass_2ecpp_155',['ReplaceNonConstFCWithBatchMatMulPass.cpp',['../_replace_non_const_f_c_with_batch_mat_mul_pass_8cpp.html',1,'']]],
  ['replacenonconstfcwithbatchmatmulpass_2eh_156',['ReplaceNonConstFCWithBatchMatMulPass.h',['../_replace_non_const_f_c_with_batch_mat_mul_pass_8h.html',1,'']]],
  ['replacesubwithaddpass_2ecpp_157',['ReplaceSubWithAddPass.cpp',['../_replace_sub_with_add_pass_8cpp.html',1,'']]],
  ['replacesubwithaddpass_2eh_158',['ReplaceSubWithAddPass.h',['../_replace_sub_with_add_pass_8h.html',1,'']]],
  ['replacewithfcgelufcpass_2ecpp_159',['ReplaceWithFCGeluFCPass.cpp',['../_replace_with_f_c_gelu_f_c_pass_8cpp.html',1,'']]],
  ['replacewithfcgelufcpass_2eh_160',['ReplaceWithFCGeluFCPass.h',['../_replace_with_f_c_gelu_f_c_pass_8h.html',1,'']]],
  ['requantizepass_2ecpp_161',['RequantizePass.cpp',['../_requantize_pass_8cpp.html',1,'']]],
  ['requantizepass_2eh_162',['RequantizePass.h',['../_requantize_pass_8h.html',1,'']]],
  ['request_2eh_163',['Request.h',['../_request_8h.html',1,'']]],
  ['res2bin_2epy_164',['res2bin.py',['../res2bin_8py.html',1,'']]],
  ['reshape_2ecc_165',['Reshape.cc',['../operation_2_reshape_8cc.html',1,'(Global Namespace)'],['../train_2operation_2_reshape_8cc.html',1,'(Global Namespace)']]],
  ['reshape_2ecpp_166',['Reshape.cpp',['../compiler_2locomotiv_2src_2_node_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2tflite_2src_2_op_2_reshape_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_reshape_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_reshape_8cpp.html',1,'(Global Namespace)']]],
  ['reshape_2eh_167',['Reshape.h',['../runtime_2onert_2core_2include_2ir_2train_2operation_2_reshape_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2include_2moco_2_import_2_nodes_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2mir_2src_2mir__onnx__importer_2_op_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2mir-interpreter_2src_2ops_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2enco_2frontend_2tflite_2src_2_op_2_reshape_8h.html',1,'(Global Namespace)'],['../compiler_2ann-ref_2src_2ops_2_reshape_8h.html',1,'(Global Namespace)']]],
  ['reshapecanonicalizer_2ecpp_168',['ReshapeCanonicalizer.cpp',['../_reshape_canonicalizer_8cpp.html',1,'']]],
  ['reshapecanonicalizer_2eh_169',['ReshapeCanonicalizer.h',['../_reshape_canonicalizer_8h.html',1,'']]],
  ['reshapekernel_2eh_170',['ReshapeKernel.h',['../_reshape_kernel_8h.html',1,'']]],
  ['reshapelayer_2ecc_171',['ReshapeLayer.cc',['../cpu_2ops_2_reshape_layer_8cc.html',1,'(Global Namespace)'],['../train_2ops_2_reshape_layer_8cc.html',1,'(Global Namespace)']]],
  ['reshapelayer_2eh_172',['ReshapeLayer.h',['../cpu_2ops_2_reshape_layer_8h.html',1,'(Global Namespace)'],['../train_2ops_2_reshape_layer_8h.html',1,'(Global Namespace)']]],
  ['reshapeop_2eh_173',['ReshapeOp.h',['../_reshape_op_8h.html',1,'']]],
  ['reshapeoptions_2ecpp_174',['ReshapeOptions.cpp',['../_reshape_options_8cpp.html',1,'']]],
  ['reshapeoptions_2eh_175',['ReshapeOptions.h',['../_reshape_options_8h.html',1,'']]],
  ['resizebilinear_2ecc_176',['ResizeBilinear.cc',['../_resize_bilinear_8cc.html',1,'']]],
  ['resizebilinear_2ecpp_177',['ResizeBilinear.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_resize_bilinear_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_resize_bilinear_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_resize_bilinear_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_resize_bilinear_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_resize_bilinear_8cpp.html',1,'(Global Namespace)']]],
  ['resizebilinear_2eh_178',['ResizeBilinear.h',['../compiler_2luci-interpreter_2src_2kernels_2_resize_bilinear_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_resize_bilinear_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_resize_bilinear_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_resize_bilinear_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_resize_bilinear_8h.html',1,'(Global Namespace)']]],
  ['resizebilinearlayer_2ecc_179',['ResizeBilinearLayer.cc',['../_resize_bilinear_layer_8cc.html',1,'']]],
  ['resizebilinearlayer_2eh_180',['ResizeBilinearLayer.h',['../_resize_bilinear_layer_8h.html',1,'']]],
  ['resizebilinearoptions_2ecpp_181',['ResizeBilinearOptions.cpp',['../_resize_bilinear_options_8cpp.html',1,'']]],
  ['resizebilinearoptions_2eh_182',['ResizeBilinearOptions.h',['../_resize_bilinear_options_8h.html',1,'']]],
  ['resizenearestneighbor_2ecc_183',['ResizeNearestNeighbor.cc',['../_resize_nearest_neighbor_8cc.html',1,'']]],
  ['resizenearestneighbor_2ecpp_184',['ResizeNearestNeighbor.cpp',['../compiler_2tflchef_2core_2src_2_op_2_resize_nearest_neighbor_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_resize_nearest_neighbor_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_resize_nearest_neighbor_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_resize_nearest_neighbor_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_resize_nearest_neighbor_8cpp.html',1,'(Global Namespace)']]],
  ['resizenearestneighbor_2eh_185',['ResizeNearestNeighbor.h',['../compiler_2tflchef_2core_2src_2_op_2_resize_nearest_neighbor_8h.html',1,'(Global Namespace)'],['../runtime_2onert_2core_2include_2ir_2operation_2_resize_nearest_neighbor_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_resize_nearest_neighbor_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_resize_nearest_neighbor_8h.html',1,'(Global Namespace)']]],
  ['resizenearestneighboroptions_2ecpp_186',['ResizeNearestNeighborOptions.cpp',['../_resize_nearest_neighbor_options_8cpp.html',1,'']]],
  ['resizenearestneighboroptions_2eh_187',['ResizeNearestNeighborOptions.h',['../_resize_nearest_neighbor_options_8h.html',1,'']]],
  ['resizeop_2eh_188',['ResizeOp.h',['../_resize_op_8h.html',1,'']]],
  ['resolve_5fincludes_2epy_189',['resolve_includes.py',['../resolve__includes_8py.html',1,'']]],
  ['resolveconstantshape_2ecpp_190',['ResolveConstantShape.cpp',['../_resolve_constant_shape_8cpp.html',1,'']]],
  ['resolveconstantshape_2eh_191',['ResolveConstantShape.h',['../_resolve_constant_shape_8h.html',1,'']]],
  ['resolvecustomopaddpass_2ecpp_192',['ResolveCustomOpAddPass.cpp',['../_resolve_custom_op_add_pass_8cpp.html',1,'']]],
  ['resolvecustomopaddpass_2eh_193',['ResolveCustomOpAddPass.h',['../_resolve_custom_op_add_pass_8h.html',1,'']]],
  ['resolvecustomopbatchmatmulpass_2ecpp_194',['ResolveCustomOpBatchMatMulPass.cpp',['../_resolve_custom_op_batch_mat_mul_pass_8cpp.html',1,'']]],
  ['resolvecustomopbatchmatmulpass_2eh_195',['ResolveCustomOpBatchMatMulPass.h',['../_resolve_custom_op_batch_mat_mul_pass_8h.html',1,'']]],
  ['resolvecustomopmatmulpass_2ecpp_196',['ResolveCustomOpMatMulPass.cpp',['../_resolve_custom_op_mat_mul_pass_8cpp.html',1,'']]],
  ['resolvecustomopmatmulpass_2eh_197',['ResolveCustomOpMatMulPass.h',['../_resolve_custom_op_mat_mul_pass_8h.html',1,'']]],
  ['resolvecustomopmaxpoolwithargmaxpass_2ecpp_198',['ResolveCustomOpMaxPoolWithArgmaxPass.cpp',['../_resolve_custom_op_max_pool_with_argmax_pass_8cpp.html',1,'']]],
  ['resolvecustomopmaxpoolwithargmaxpass_2eh_199',['ResolveCustomOpMaxPoolWithArgmaxPass.h',['../_resolve_custom_op_max_pool_with_argmax_pass_8h.html',1,'']]],
  ['resolvecustomopsplitvpass_2ecpp_200',['ResolveCustomOpSplitVPass.cpp',['../_resolve_custom_op_split_v_pass_8cpp.html',1,'']]],
  ['resolvecustomopsplitvpass_2eh_201',['ResolveCustomOpSplitVPass.h',['../_resolve_custom_op_split_v_pass_8h.html',1,'']]],
  ['resolveduplicatereshapepass_2ecpp_202',['ResolveDuplicateReshapePass.cpp',['../_resolve_duplicate_reshape_pass_8cpp.html',1,'']]],
  ['resolveduplicatereshapepass_2eh_203',['ResolveDuplicateReshapePass.h',['../_resolve_duplicate_reshape_pass_8h.html',1,'']]],
  ['resolveformercustomoppass_2ecpp_204',['ResolveFormerCustomOpPass.cpp',['../_resolve_former_custom_op_pass_8cpp.html',1,'']]],
  ['resolveformercustomoppass_2eh_205',['ResolveFormerCustomOpPass.h',['../_resolve_former_custom_op_pass_8h.html',1,'']]],
  ['resolvefusedbatchnorm_2ecpp_206',['ResolveFusedBatchNorm.cpp',['../_resolve_fused_batch_norm_8cpp.html',1,'']]],
  ['resolvefusedbatchnorm_2eh_207',['ResolveFusedBatchNorm.h',['../_resolve_fused_batch_norm_8h.html',1,'']]],
  ['resolveredundantreshapepass_2ecpp_208',['ResolveRedundantReshapePass.cpp',['../_resolve_redundant_reshape_pass_8cpp.html',1,'']]],
  ['resolveredundantreshapepass_2eh_209',['ResolveRedundantReshapePass.h',['../_resolve_redundant_reshape_pass_8h.html',1,'']]],
  ['resolvereshapewildcarddim_2ecpp_210',['ResolveReshapeWildcardDim.cpp',['../_resolve_reshape_wildcard_dim_8cpp.html',1,'']]],
  ['resolvereshapewildcarddim_2eh_211',['ResolveReshapeWildcardDim.h',['../_resolve_reshape_wildcard_dim_8h.html',1,'']]],
  ['resolvesquareddifference_2ecpp_212',['ResolveSquaredDifference.cpp',['../_resolve_squared_difference_8cpp.html',1,'']]],
  ['resolvesquareddifference_2eh_213',['ResolveSquaredDifference.h',['../_resolve_squared_difference_8h.html',1,'']]],
  ['ret_2eh_214',['Ret.h',['../_ret_8h.html',1,'']]],
  ['reverse_2ecc_215',['Reverse.cc',['../_reverse_8cc.html',1,'']]],
  ['reverse_2eh_216',['Reverse.h',['../runtime_2onert_2core_2include_2ir_2operation_2_reverse_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_reverse_8h.html',1,'(Global Namespace)']]],
  ['reverselayer_2ecc_217',['ReverseLayer.cc',['../_reverse_layer_8cc.html',1,'']]],
  ['reverselayer_2eh_218',['ReverseLayer.h',['../_reverse_layer_8h.html',1,'']]],
  ['reversesequence_2ecpp_219',['ReverseSequence.cpp',['../core_2src_2_op_2_reverse_sequence_8cpp.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2_reverse_sequence_8cpp.html',1,'(Global Namespace)']]],
  ['reversesequence_2eh_220',['ReverseSequence.h',['../core_2src_2_op_2_reverse_sequence_8h.html',1,'(Global Namespace)'],['../tflite_2src_2_op_2include_2_reverse_sequence_8h.html',1,'(Global Namespace)']]],
  ['reversesequenceoptions_2ecpp_221',['ReverseSequenceOptions.cpp',['../_reverse_sequence_options_8cpp.html',1,'']]],
  ['reversesequenceoptions_2eh_222',['ReverseSequenceOptions.h',['../_reverse_sequence_options_8h.html',1,'']]],
  ['reversev2_2ecpp_223',['ReverseV2.cpp',['../compiler_2luci-interpreter_2src_2kernels_2_reverse_v2_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_reverse_v2_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_reverse_v2_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_reverse_v2_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_reverse_v2_8cpp.html',1,'(Global Namespace)']]],
  ['reversev2_2eh_224',['ReverseV2.h',['../onert-micro_2luci-interpreter_2src_2kernels_2_reverse_v2_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_reverse_v2_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2core_2src_2_op_2_reverse_v2_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_reverse_v2_8h.html',1,'(Global Namespace)']]],
  ['reversev2options_2ecpp_225',['ReverseV2Options.cpp',['../_reverse_v2_options_8cpp.html',1,'']]],
  ['reversev2options_2eh_226',['ReverseV2Options.h',['../_reverse_v2_options_8h.html',1,'']]],
  ['rnn_2ecc_227',['RNN.cc',['../_r_n_n_8cc.html',1,'']]],
  ['rnn_2eh_228',['RNN.h',['../_r_n_n_8h.html',1,'']]],
  ['roadmap_2emd_229',['roadmap.md',['../roadmap_8md.html',1,'']]],
  ['round_2ecpp_230',['Round.cpp',['../compiler_2tflchef_2core_2src_2_op_2_round_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_round_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_round_8cpp.html',1,'(Global Namespace)']]],
  ['round_2eh_231',['Round.h',['../compiler_2tflchef_2core_2src_2_op_2_round_8h.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2include_2_round_8h.html',1,'(Global Namespace)'],['../compute_2cker_2include_2cker_2operation_2_round_8h.html',1,'(Global Namespace)']]],
  ['rsqrt_2ecpp_232',['Rsqrt.cpp',['../compiler_2tflchef_2core_2src_2_op_2_rsqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2kernels_2_rsqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2loader_2nodes_2_rsqrt_8cpp.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2kernels_2_rsqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2moco_2import_2src_2_nodes_2_rsqrt_8cpp.html',1,'(Global Namespace)'],['../compiler_2tflchef_2tflite_2src_2_op_2_rsqrt_8cpp.html',1,'(Global Namespace)']]],
  ['rsqrt_2eh_233',['Rsqrt.h',['../tflchef_2tflite_2src_2_op_2include_2_rsqrt_8h.html',1,'(Global Namespace)'],['../tflchef_2core_2src_2_op_2_rsqrt_8h.html',1,'(Global Namespace)'],['../luci-interpreter_2src_2kernels_2_rsqrt_8h.html',1,'(Global Namespace)'],['../moco_2import_2include_2moco_2_import_2_nodes_2_rsqrt_8h.html',1,'(Global Namespace)']]],
  ['rsqrtcanonicalizer_2ecpp_234',['RsqrtCanonicalizer.cpp',['../_rsqrt_canonicalizer_8cpp.html',1,'']]],
  ['rsqrtcanonicalizer_2eh_235',['RsqrtCanonicalizer.h',['../_rsqrt_canonicalizer_8h.html',1,'']]],
  ['runner_2ecpp_236',['Runner.cpp',['../nnkit-onnxrt_2support_2src_2_runner_8cpp.html',1,'(Global Namespace)'],['../nnkit-tf_2support_2src_2_runner_8cpp.html',1,'(Global Namespace)']]],
  ['runner_2eh_237',['Runner.h',['../nnkit-tf_2support_2include_2nnkit_2support_2tf_2_runner_8h.html',1,'(Global Namespace)'],['../nnkit-onnxrt_2support_2include_2nnkit_2support_2onnx_2_runner_8h.html',1,'(Global Namespace)']]],
  ['runtimegraph_2ecpp_238',['RuntimeGraph.cpp',['../onert-micro_2luci-interpreter_2src_2core_2_runtime_graph_8cpp.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2core_2_runtime_graph_8cpp.html',1,'(Global Namespace)']]],
  ['runtimegraph_2eh_239',['RuntimeGraph.h',['../onert-micro_2luci-interpreter_2src_2core_2_runtime_graph_8h.html',1,'(Global Namespace)'],['../compiler_2luci-interpreter_2src_2core_2_runtime_graph_8h.html',1,'(Global Namespace)']]],
  ['runtimemodule_2eh_240',['RuntimeModule.h',['../compiler_2luci-interpreter_2src_2core_2_runtime_module_8h.html',1,'(Global Namespace)'],['../onert-micro_2luci-interpreter_2src_2core_2_runtime_module_8h.html',1,'(Global Namespace)']]],
  ['runtimetoir_2eh_241',['RuntimeToIR.h',['../_runtime_to_i_r_8h.html',1,'']]],
  ['ruy_2ecc_242',['ruy.cc',['../ruy_8cc.html',1,'']]],
  ['ruysupport_2eh_243',['RuySupport.h',['../cker_2include_2cker_2ruy_2_ruy_support_8h.html',1,'(Global Namespace)'],['../ruy_2include_2ruy_2_ruy_support_8h.html',1,'(Global Namespace)']]]
];
