#!/bin/bash
#
# Copyright (c) 2018 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMMAND_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="$(dirname $(dirname $COMMAND_DIR))"

MD5_CHECK="on"
DOWNLOAD_MODEL="all"

function Usage()
{
    echo "Usage: $0 $(basename ${BASH_SOURCE[0]}) [OPTIONS]"
    echo ""
    echo "Options:"
    echo "      --ignoremd5                         Ignore MD5 check when download model files"
    echo "      --model=(all|nnpackage|tflite)      Download test model (default=all)"
}

for i in "$@"
do
    case $i in
        -h|--help|help)
            Usage
            exit 1
            ;;
        --ignoremd5)
            MD5_CHECK="off"
            ;;
        --model=*)
            DOWNLOAD_MODEL=${i#*=}
            ;;
        *)
            echo "Unknown option: $i"
            exit 1
        ;;
    esac
    shift
done

if [[ $DOWNLOAD_MODEL == "all" ]] || [[ $DOWNLOAD_MODEL == "tflite" ]]; then
    # Download tflite models
    $INSTALL_DIR/tests/scripts/models/run_test.sh --download=on --run=off --md5=$MD5_CHECK
fi

if [[ $DOWNLOAD_MODEL == "all" ]] || [[ $DOWNLOAD_MODEL == "nnpackage" ]]; then
    # Download nnpackage model
    NNPACKAGE_CONFIG_DIR=$INSTALL_DIR/test/models/nnpackage/
    NNPACKAGE_CACHE_DIR=$INSTALL_DIR/unittest_standalone/nnfw_api_gtest_models/
    $INSTALL_DIR/tests/scripts/models/run_test.sh --download=on --run=off --md5=$MD5_CHECK \
        --configdir=$NNPACKAGE_CONFIG_DIR --cachedir=$NNPACKAGE_CACHE_DIR
fi
