#!/bin/bash
#
# Copyright (c) 2018 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

MODEL_ROOT_DIR=$INSTALL_PATH/test/models
MD5_CHECK="on"

function Usage()
{
    echo "Usage: $0 $(basename ${BASH_SOURCE[0]}) [OPTIONS]"
    echo ""
    echo "Options:"
    echo "          --ignoremd5     Ignore MD5 check when download model files"
    echo "          --cachedir=PATH Set downloaded resouces cache directory (default: $CACHE_PATH)"
    echo "      -h, --help          Display this help message and exit"
}

for i in "$@"
do
    case $i in
        -h|--help|help)
            Usage
            exit 1
            ;;
        --ignoremd5)
            MD5_CHECK="off"
            ;;
        --cachedir=*)
            CACHE_PATH=${i#*=}
            ;;
        *)
            echo "Unknown option: $i"
            exit 1
        ;;
    esac
    shift
done

# Check MODELFILE_SERVER
if [[ -z "$MODELFILE_SERVER" ]]; then
    echo "Fail to download models: Please set MODELFILE_SERVER to download model"
    exit 1
fi
echo "Download from $MODELFILE_SERVER"

$INSTALL_PATH/test/models/run_test.sh --download=on --run=off --md5=$MD5_CHECK --cachedir=$CACHE_PATH
