# HOW TO GENERATE:
#
#  import tensorflow as tf
#  value = tf.placeholder(dtype=tf.float32, shape=[1, 4, 4, 1], name='placeholder')
#  output = tf.nn.avg_pool(value, [1, 3, 3, 1], [1, 1, 1, 1], 'SAME', name='avgpool2d')
#  tf.get_default_graph().as_graph_def()
#
# NOTE 1. The output shape is 1x4x4x1
#
# >>> tf.graph_util.tensor_shape_from_node_def_name(tf.get_default_graph(), 'avgpool2d')
# TensorShape([Dimension(1), Dimension(4), Dimension(4), Dimension(1)])
#
# NOTE 2. Almost all the AvgPool nodes in inception v3 2018.04.27 use this configuration.
#
# The only exception is "InceptionV3/Logits/AvgPool_1a_8x8/AvgPool" which performs global average pooling.
node {
  name: "placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value { type: DT_FLOAT }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim { size: 1 }
        dim { size: 4 }
        dim { size: 4 }
        dim { size: 1 }
      }
    }
  }
}
node {
  name: "avgpool2d"
  op: "AvgPool"
  input: "placeholder"
  attr {
    key: "T"
    value { type: DT_FLOAT }
  }
  attr {
    key: "data_format"
    value { s: "NHWC" }
  }
  attr {
    key: "ksize"
    value {
      list { i: 1 i: 3 i: 3 i: 1 }
    }
  }
  attr {
    key: "padding"
    value { s: "SAME" }
  }
  attr {
    key: "strides"
    value {
      list { i: 1 i: 1 i: 1 i: 1 }
    }
  }
}
