FROM ubuntu:18.04

ARG UBUNTU_MIRROR

# Install 'add-apt-repository'
RUN apt-get update && apt-get -qqy install software-properties-common

# Build tool
RUN apt-get update && apt-get -qqy install build-essential scons git lcov g++-arm-linux-gnueabihf g++-aarch64-linux-gnu

# Download cmake (`apt-get install cmake` installs version 3.10.2 but we need more recent version.
# With 3.10.2, we will get some error, e.g., "Cannot find a target flatbuffer::flatbuffer"
RUN apt-get -qqy install libssl-dev wget
WORKDIR /tmp
RUN wget -q https://cmake.org/files/v3.16/cmake-3.16.2.tar.gz
RUN tar -xvzf cmake-3.16.2.tar.gz
RUN cd cmake-3.16.2 && ./bootstrap --prefix=/usr/local && make && make install
RUN ln -s /usr/local/bin/cmake /usr/bin/cmake
RUN rm -rf cmake-3.16.2*

# Install extra dependencies (Caffe, nnkit)
RUN apt-get update && apt-get -qqy install libboost-all-dev libgflags-dev libgoogle-glog-dev libatlas-base-dev libhdf5-dev

# Install protocol buffer
RUN apt-get update && apt-get -qqy install libprotobuf-dev protobuf-compiler

# Additonal tools
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -qqy install doxygen graphviz unzip clang-format-3.9 python3 python3-pip python3-venv hdf5-tools pylint
RUN pip3 install --upgrade pip
RUN pip3 install yapf==0.22.0 numpy

# Install google test (source)
RUN apt-get update && apt-get -qqy install libgtest-dev

# Build and install google test static libraries
WORKDIR /root/gtest
RUN cmake /usr/src/gtest
RUN make
RUN mv *.a /usr/lib
WORKDIR /root
RUN rm -rf gtest

# Install gbs & sdb
RUN echo 'deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_18.04/ /' | cat >> /etc/apt/sources.list
RUN apt-get update && apt-get -qqy install gbs
RUN wget http://download.tizen.org/sdk/tizenstudio/official/binary/sdb_3.1.4_ubuntu-64.zip -O sdb.zip
RUN unzip -d tmp sdb.zip && rm sdb.zip
RUN cp tmp/data/tools/sdb /usr/bin/. && rm -rf tmp

# Clean archives (to reduce image size)
RUN apt-get clean -y
