# {FILES_TO_INSTALL} {DEST_DIR}
# bin
bin/circle-interpreter usr/share/cirint/bin/
# lib
lib/libloco.so usr/share/cirint/bin/
lib/libluci_env.so usr/share/cirint/bin/
lib/libluci_import.so usr/share/cirint/bin/
lib/libluci_interpreter.so usr/share/cirint/bin/
lib/libluci_lang.so usr/share/cirint/bin/
lib/libluci_logex.so usr/share/cirint/bin/
lib/libluci_log.so usr/share/cirint/bin/
lib/libluci_plan.so usr/share/cirint/bin/
lib/libluci_profile.so usr/share/cirint/bin/
