#!/bin/bash

function Usage()
{
  echo "Usage: $0 $(basename ${BASH_SOURCE[0]}) [OPTIONS]"
  echo ""
  echo "Options:"
  echo "      --codename                ubuntu codename, default image name is nnfw/one-devtools:[codename]"
  echo "Options can use as docker build option:"
  docker build --help
}

DOCKER_FILE_RPATH_BASE="infra/docker"
DOCKER_BUILD_ARGS=()

# Default setting
UBUNTU_CODENAME="bionic"
DOCKER_TAG="latest"

while [[ $# -gt 0 ]]
do
  arg="$1"
  # Handle argument for this script
  # Set default docker image name, tag
  case $arg in
    -h|--help|help)
      Usage
      exit 1
      ;;
    --codename)
      UBUNTU_CODENAME=$2
      DOCKER_TAG=$2
      shift 2
      ;;
    -t|--tag)
      DOCKER_IMAGE_NAME="$2"
      shift 2
      ;;
    *)
      DOCKER_BUILD_ARGS+=(${1})
      shift
      ;;
  esac
done

DOCKER_IMAGE_NAME=${DOCKER_IMAGE_NAME:-nnfw/one-devtools:$DOCKER_TAG}
DOCKER_FILE_RPATH=$DOCKER_FILE_RPATH_BASE/$UBUNTU_CODENAME/Dockerfile

HOST_ARCH=$(uname -m)
if [[ -n $HOST_ARCH  && $HOST_ARCH != "x86_64" ]]; then
  DOCKER_FILE_RPATH=$DOCKER_FILE_RPATH.$HOST_ARCH
fi

DOCKER_BUILD_ARGS+=("-t ${DOCKER_IMAGE_NAME}")

docker build --build-arg http_proxy="${http_proxy}" \
  --build-arg https_proxy="${https_proxy}" \
  ${DOCKER_BUILD_ARGS[@]} \
  - < ${NNAS_PROJECT_PATH}/${DOCKER_FILE_RPATH}
