#!/bin/bash

import "docker.configuration"

DOCKER_RUN_OPTS+=" -it"
docker run $DOCKER_RUN_OPTS $DOCKER_ENV_VARS $DOCKER_VOLUMES $DOCKER_IMAGE_NAME "/bin/bash"
EXITCODE=$?

if [ $EXITCODE -ne 0 ]; then
  exit $EXITCODE
fi
