#!/bin/bash

import "docker.configuration"

# Use host user ID if --user option is given
# It is useful if host userID is different from docker userID 1000
if [[ $1 == '--user' ]]; then
  DOCKER_RUN_OPTS+=" -u $(stat -c "%u" $NNAS_PROJECT_PATH):$(stat -c "%g" $NNAS_PROJECT_PATH)"
  shift
fi

docker run ${DOCKER_RUN_OPTS} ${DOCKER_ENV_VARS} ${DOCKER_VOLUMES} ${DOCKER_IMAGE_NAME} "$@"
EXITCODE=$?

exit ${EXITCODE}
