#!/bin/bash

import "build.configuration"

BUILD_WORKSPACE_PATH="${NNAS_PROJECT_PATH}/${BUILD_WORKSPACE_RPATH}"

LCOV_PATH=$(command -v lcov)
GENHTML_PATH=$(command -v genhtml)

if [[ -z "${LCOV_PATH}" ]]; then
  echo "ERROR: 'lcov' is not found"
  exit 255
fi

if [[ -z "${GENHTML_PATH}" ]]; then
  echo "ERROR: 'genhtml' is not found"
  exit 255
fi

if [[ -z "${GCOV_PATH}" ]]; then
  GCOV_PATH=$(command -v gcov)
  if [[ -z "${GCOV_PATH}" ]]; then
    echo "ERROR: 'gcov' is not found"
    exit 255
  fi
fi

# Function to check gcov version
check_gcov_version() {
  local gcov_version_output
  gcov_version_output=$("${GCOV_PATH}" --version)
  if [[ ${gcov_version_output} =~ gcov\ (GCC)\ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
    local major_version="${BASH_REMATCH[2]}"
    # Check if major version is 13 or 14
    if [[ "${major_version}" == "13" || "${major_version}" == "14" ]]; then
      return 0 # Version is 13.x.y or 14.x.y
    fi
  fi
  return 1 # Version is not 13.x.y or 14.x.y
}

# --ignore-errors mismatch --ignore-errors negative: lcov bug in gcc 13, 14
# Determine if "--ignore-errors mismatch" and "--ignore-errors negative" should be used
IGNORE_ERRORS_MISMATCH_FLAG=""
if check_gcov_version; then
  IGNORE_ERRORS_MISMATCH_FLAG="--ignore-errors mismatch --ignore-errors negative"
fi

OUTPUT_TAG="${NNAS_COVERAGE:-coverage}"
OUTPUT_PATH="${NNAS_COVERAGE_PATH:-${NNAS_PROJECT_PATH}/${OUTPUT_TAG}}"

if [[ -e "${OUTPUT_PATH}" ]]; then
  echo "ERROR: '${OUTPUT_PATH}' already exists"
  exit 255
fi

mkdir -p "${OUTPUT_PATH}"

RAW_BASE_COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.base.raw.info"
RAW_TEST_COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.test.raw.info"
RAW_COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.raw.info"
EXTRACTED_COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.extracted.info"
EXCLUDED_COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.excluded.info"
COVERAGE_INFO_PATH="${OUTPUT_PATH}/coverage.info"
HTML_PATH="${OUTPUT_PATH}/html"

CANDIDATES=()
SRC_PREFIX=${SRC_PREFIX:-${NNAS_PROJECT_PATH}}

for CANDIDATE in "$@";
do
  CANDIDATES+=("${SRC_PREFIX}/${CANDIDATE}/*")
done

# Capture initial zero coverage data
"${LCOV_PATH}" -c -i -d "${BUILD_WORKSPACE_PATH}" --gcov-tool ${GCOV_PATH} \
  -o "${RAW_BASE_COVERAGE_INFO_PATH}" \
  ${IGNORE_ERRORS_MISMATCH_FLAG}

# Capture tests coverage data
"${LCOV_PATH}" -c -d "${BUILD_WORKSPACE_PATH}" --gcov-tool ${GCOV_PATH} \
  -o "${RAW_TEST_COVERAGE_INFO_PATH}" \
  ${IGNORE_ERRORS_MISMATCH_FLAG}

# Append zero coverage data and tests coverage data
"${LCOV_PATH}" -o "${RAW_COVERAGE_INFO_PATH}" \
    -a "${RAW_BASE_COVERAGE_INFO_PATH}" \
    -a "${RAW_TEST_COVERAGE_INFO_PATH}"

# Extract data for particular pathes
"${LCOV_PATH}" -e "${RAW_COVERAGE_INFO_PATH}" \
  -o "${EXTRACTED_COVERAGE_INFO_PATH}" \
  "${CANDIDATES[@]}"

# Exclude test files from coverage report
# Exclude flatbuffer generated files from coverage report
# Exclude external source from coverage report
# --ignore-errors unused: skip unused file/directory pattern error for generalization
"${LCOV_PATH}" -r "${EXTRACTED_COVERAGE_INFO_PATH}" -o "${EXCLUDED_COVERAGE_INFO_PATH}" \
  --ignore-errors unused \
  '*.test.cpp' '*.test.cc' '*/test/*' '*/tests/*' '.test.h' '*/test_models/*' \
  '*_generated.h' \
  '*/externals/*' '*/3rdparty/*'

# Final coverage data
cp -v ${EXCLUDED_COVERAGE_INFO_PATH} ${COVERAGE_INFO_PATH}

# Gen html
"${GENHTML_PATH}" "${EXCLUDED_COVERAGE_INFO_PATH}" \
  --prefix "${NNAS_PROJECT_PATH}" \
  --output-directory "${HTML_PATH}"
