#!/bin/bash

# Copyright (c) 2025 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE this file is used to prepare venv for local circle-mlir development.

set -e

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -z "$VENV_NAME" ]]; then
  VENV_NAME="venv"
fi

VENV_ACTIVATE=${DRIVER_PATH}/${VENV_NAME}/bin/activate
# NOTE please use venv's python instead of python after `source activation`.
VENV_PYTHON=${DRIVER_PATH}/${VENV_NAME}/bin/python

if [ ! -f ${VENV_ACTIVATE} ]; then
  # Create python virtual enviornment
  python3 -m venv "${DRIVER_PATH}/${VENV_NAME}"
fi

# NOTE version
# - https://github.com/onnx/onnx/blob/master/docs/Versioning.md

VER_TORCH=2.4.1+cpu
VER_ONNX=1.17.0
VER_ONNXRUNTIME=1.19.2
VER_NUMPY=1.24.4

PIP_TRUSTED_HOST="--trusted-host pypi.org "
PIP_TRUSTED_HOST+="--trusted-host pypi.python.org "
PIP_TRUSTED_HOST+="--trusted-host files.pythonhosted.org "
PIP_TRUSTED_HOST+="--trusted-host download.pytorch.org "

PIP_TIMEOUT="--default-timeout=1000 "

PIP_OPTIONS="${PIP_TIMEOUT} ${PIP_TRUSTED_HOST}"

# NOTE $PREPVENV_PIP_OPTION is to provide additional PIP options
# such as ceritificate file behind firewall
# ex) PREPVENV_PIP_OPTION="--cert SomePrivateCetificate.crt" ./prepare-venv
if [[ ! -z "$PREPVENV_PIP_OPTION" ]]; then
  PIP_OPTIONS+=" ${PREPVENV_PIP_OPTION} "
fi

${VENV_PYTHON} -m pip ${PIP_OPTIONS} install --upgrade pip setuptools

${VENV_PYTHON} -m pip ${PIP_OPTIONS} install torch==${VER_TORCH} -f https://download.pytorch.org/whl/torch
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install onnx==${VER_ONNX}
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install onnxruntime==${VER_ONNXRUNTIME}

${VENV_PYTHON} -m pip ${PIP_OPTIONS} install h5py==3.8.0 einops
${VENV_PYTHON} -m pip ${PIP_OPTIONS} install numpy==${NUMPY_VERSION}