#!/bin/bash
# NOTE this file is not used and not updated anymore but left for any future referennce.

import "build.configuration"

BUILD_WORKSPACE_PATH="${NNCC_PROJECT_PATH}/${BUILD_WORKSPACE_RPATH}"

if [[ ! -d "${BUILD_WORKSPACE_PATH}" ]]; then
  echo "'${BUILD_WORKSPACE_RPATH}' does not exist. Please run 'configure' first"
  exit 255
fi

BUILD_ITEMS="angkor cwrap pepper-str pepper-strcast pp \
oops pepper-assert \
hermes hermes-std \
loco locop locomotiv logo-core logo \
foder souschef arser vconone crew \
safemain mio-circle mio-tflite mio-tflite260 \
tflite2circle \
luci \
luci-interpreter \
luci-eval-driver \
luci-pass-value-test \
luci-value-test \
record-minmax \
circle2circle circle-quantizer"

function count_all()
{
  local result=`(ctest --verbose | grep -c '\[ RUN      \]') 2>/dev/null`
  echo $result
}

function count_neg()
{
  local result=`(ctest --verbose | grep '\[ RUN      \]' | grep -c '_NEG') 2>/dev/null`
  echo $result
}

export CTEST_OUTPUT_ON_FAILURE=0

for item in $BUILD_ITEMS
do
  cd ${BUILD_WORKSPACE_PATH}/compiler/$item &&
    printf "$item = " &&
      res="$(count_all)" && printf "$res " &&
      res="$(count_neg)" && echo "$res"
done
