all: cfg debug test install

cfg:
	Python3_ROOT_DIR=/usr/bin cmake -B build/debug -S ./ \
	-DCMAKE_INSTALL_PREFIX=build/debug.install \
	-DCMAKE_BUILD_TYPE=Debug \
	-DCIRCLE_MLIR_WORKDIR=/workdir

cc:
	Python3_ROOT_DIR=/usr/bin cmake -B build/debug -S ./ \
	-DCMAKE_INSTALL_PREFIX=build/debug.install \
	-DCMAKE_BUILD_TYPE=Debug

debug:
	cmake --build build/debug -j4

test:
	CTEST_OUTPUT_ON_FAILURE=1 cmake --build build/debug --verbose -- test

install:
	cmake --build build/debug -j4 -- install

