node {
  name: "input_01"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 3
        }
        dim {
          size: 3
        }
        dim {
          size: 5
        }
      }
    }
  }
}
node {
  name: "input_02"
  op: "Placeholder"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 1
        }
        dim {
          size: 5
        }
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "input_01"
  input: "input_02"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
