set(PACKAGE_VERSION_EXACT FALSE)
set(PACKAGE_VERSION_COMPATIBLE FALSE)
set(PACKAGE_VERSION_UNSUITABLE TRUE)

if(NOT PACKAGE_FIND_VERSION)
  # This package works only when find_package(...) call has no EXACT option
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
  set(PACKAGE_VERSION_UNSUITABLE FALSE)
endif(NOT PACKAGE_FIND_VERSION)
