#!/bin/bash

# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
# Boradly speaking, the `postinst` is called after a package is unpacked.

set -e

/opt/one_compiler/bin/one-prepare-venv
