# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers

class BCQFullyConnectedOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBCQFullyConnectedOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BCQFullyConnectedOptions()
        x.Init(buf, n + offset)
        return x

    # BCQFullyConnectedOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BCQFullyConnectedOptions
    def WeightsHiddenSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BCQFullyConnectedOptions
    def FusedActivationFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def BCQFullyConnectedOptionsStart(builder): builder.StartObject(2)
def BCQFullyConnectedOptionsAddWeightsHiddenSize(builder, weightsHiddenSize): builder.PrependInt32Slot(0, weightsHiddenSize, 0)
def BCQFullyConnectedOptionsAddFusedActivationFunction(builder, fusedActivationFunction): builder.PrependInt8Slot(1, fusedActivationFunction, 0)
def BCQFullyConnectedOptionsEnd(builder): return builder.EndObject()
