# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

import flatbuffers

class InstanceNormOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInstanceNormOptions(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InstanceNormOptions()
        x.Init(buf, n + offset)
        return x

    # InstanceNormOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InstanceNormOptions
    def Epsilon(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # InstanceNormOptions
    def FusedActivationFunction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def InstanceNormOptionsStart(builder): builder.StartObject(2)
def InstanceNormOptionsAddEpsilon(builder, epsilon): builder.PrependFloat32Slot(0, epsilon, 0.0)
def InstanceNormOptionsAddFusedActivationFunction(builder, fusedActivationFunction): builder.PrependInt8Slot(1, fusedActivationFunction, 0)
def InstanceNormOptionsEnd(builder): return builder.EndObject()
