#!/bin/bash

import "build.configuration"

if [[ ! -d "${BUILD_PATH}" ]]; then
  echo "'${BUILD_PATH}' does not exist. Please run 'configure' first"
  exit 255
fi

# Require cmake version >= 3.15
cmake --install ${BUILD_PATH} "$@"
