# In this directory, *_generated.py is auto generated by flatc.
#
# (For devleopers) You could easily update *_generated.py using '_gen.py' in this folder.
#   $ pip3 install wget
#   $ python3 _gen.py
