# In this directory, *_generated.py is auto generated by flatc.
#
# * flatc version 23.5.26 is used
# * /ONE/nnpackage/schema/circle_schema.fbs is used
# * /ONE/runtime/libs/circle-schema/include/circle_traininfo.fbs is used
#
# ./flatc --python --gen-onefile --gen-object-api circle_schema.fbs
# ./flatc --python --gen-onefile --one-object-api cricle_traininfo.fbs
