#!/usr/bin/env groovy

pipeline {
  agent none

  options {
    timeout(time:2, unit: 'HOURS')
    skipDefaultCheckout true
  }

  stages {
    stage('format-check')
    {
      agent {
        docker {
          label 'checker'
          image 'nnfw/one-devtools:bionic'
        }
      }

      steps {
        checkout scm

        sh '''#!/bin/bash

        ./nnas format

        '''
        archiveArtifacts artifacts: "format.patch", onlyIfSuccessful: false, allowEmptyArchive: true
      }
    }
  }
  post {
    success {
      githubNotify context: "format-checker/test", status: "SUCCESS", description: "Passed"
    }
    failure {
      githubNotify context: "format-checker/test", status: "FAILURE", description: "Failed. Comment \"@nnfw-bot test format-checker\" if you want to rerun"
    }
  }
}
