/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __TFLITE_OP_CHEFS_H__
#define __TFLITE_OP_CHEFS_H__

// In alphabet order
#include "Op/include/Abs.h"
#include "Op/include/Add.h"
#include "Op/include/AddN.h"
#include "Op/include/ArgMax.h"
#include "Op/include/ArgMin.h"
#include "Op/include/AveragePool2D.h"
#include "Op/include/BatchMatMul.h"
#include "Op/include/BatchToSpaceND.h"
#include "Op/include/BidirectionalSequenceLSTM.h"
#include "Op/include/Cast.h"
#include "Op/include/Ceil.h"
#include "Op/include/Concatenation.h"
#include "Op/include/Conv2D.h"
#include "Op/include/Cos.h"
#include "Op/include/DepthToSpace.h"
#include "Op/include/DepthwiseConv2D.h"
#include "Op/include/Dequantize.h"
#include "Op/include/Div.h"
#include "Op/include/ELU.h"
#include "Op/include/Equal.h"
#include "Op/include/Exp.h"
#include "Op/include/ExpandDims.h"
#include "Op/include/FakeQuant.h"
#include "Op/include/Fill.h"
#include "Op/include/Floor.h"
#include "Op/include/FloorDiv.h"
#include "Op/include/FloorMod.h"
#include "Op/include/FullyConnected.h"
#include "Op/include/Gather.h"
#include "Op/include/GatherNd.h"
#include "Op/include/Gelu.h"
#include "Op/include/Greater.h"
#include "Op/include/GreaterEqual.h"
#include "Op/include/L2Normalize.h"
#include "Op/include/L2Pool2D.h"
#include "Op/include/LeakyRelu.h"
#include "Op/include/Less.h"
#include "Op/include/LessEqual.h"
#include "Op/include/LocalResponseNormalization.h"
#include "Op/include/Log.h"
#include "Op/include/LogicalAnd.h"
#include "Op/include/LogicalNot.h"
#include "Op/include/LogicalOr.h"
#include "Op/include/Logistic.h"
#include "Op/include/LogSoftmax.h"
#include "Op/include/MatrixDiag.h"
#include "Op/include/MatrixSetDiag.h"
#include "Op/include/Maximum.h"
#include "Op/include/MaxPool2D.h"
#include "Op/include/Mean.h"
#include "Op/include/Minimum.h"
#include "Op/include/MirrorPad.h"
#include "Op/include/Mul.h"
#include "Op/include/Neg.h"
#include "Op/include/NonMaxSuppressionV4.h"
#include "Op/include/NonMaxSuppressionV5.h"
#include "Op/include/NotEqual.h"
#include "Op/include/OneHot.h"
#include "Op/include/Pack.h"
#include "Op/include/Pad.h"
#include "Op/include/PadV2.h"
#include "Op/include/Pow.h"
#include "Op/include/PRelu.h"
#include "Op/include/Quantize.h"
#include "Op/include/Range.h"
#include "Op/include/Rank.h"
#include "Op/include/ReduceAny.h"
#include "Op/include/ReduceMax.h"
#include "Op/include/ReduceMin.h"
#include "Op/include/ReduceProd.h"
#include "Op/include/ReLU.h"
#include "Op/include/ReLU6.h"
#include "Op/include/ReLUN1To1.h"
#include "Op/include/Reshape.h"
#include "Op/include/ResizeBilinear.h"
#include "Op/include/ResizeNearestNeighbor.h"
#include "Op/include/ReverseSequence.h"
#include "Op/include/ReverseV2.h"
#include "Op/include/Round.h"
#include "Op/include/Rsqrt.h"
#include "Op/include/ScatterNd.h"
#include "Op/include/SegmentSum.h"
#include "Op/include/Select.h"
#include "Op/include/SelectV2.h"
#include "Op/include/Shape.h"
#include "Op/include/Sin.h"
#include "Op/include/Slice.h"
#include "Op/include/Softmax.h"
#include "Op/include/SpaceToBatchND.h"
#include "Op/include/SpaceToDepth.h"
#include "Op/include/SparseToDense.h"
#include "Op/include/Split.h"
#include "Op/include/SplitV.h"
#include "Op/include/Sqrt.h"
#include "Op/include/Square.h"
#include "Op/include/SquaredDifference.h"
#include "Op/include/Squeeze.h"
#include "Op/include/StridedSlice.h"
#include "Op/include/Sub.h"
#include "Op/include/Sum.h"
#include "Op/include/SVDF.h"
#include "Op/include/Tanh.h"
#include "Op/include/Tile.h"
#include "Op/include/TopKV2.h"
#include "Op/include/Transpose.h"
#include "Op/include/TransposeConv.h"
#include "Op/include/UnidirectionalSequenceLSTM.h"
#include "Op/include/Unique.h"
#include "Op/include/Unpack.h"
#include "Op/include/Where.h"
#include "Op/include/ZerosLike.h"

#endif // __TFLITE_OP_CHEFS_H__
