#!/bin/bash

# NOTE purpose of this file is static analysis only
#      new official preset will be added when new programs are ready

PRESET="20200630"

function preset_configure()
{
  REQUIRED_UNITS=()
  # Common Libraries
  REQUIRED_UNITS+=("angkor" "cwrap" "pepper-str" "pepper-strcast" "pp" "stdex")
  REQUIRED_UNITS+=("oops" "pepper-assert" "foder")
  REQUIRED_UNITS+=("souschef")
  REQUIRED_UNITS+=("safemain")
  # Hermes Logging Framework
  REQUIRED_UNITS+=("hermes" "hermes-std")
  # loco IR and related utilities
  REQUIRED_UNITS+=("loco" "locop" "locomotiv" "logo-core" "logo")
  # Flatbuffer I/O
  REQUIRED_UNITS+=("mio-tflite" "mio-circle")
  # Circle compiler library (.circle -> .circle)
  REQUIRED_UNITS+=("luci")
  # Tools
  REQUIRED_UNITS+=("tflite2circle" "circle2circle" "tflchef" "circlechef")
  REQUIRED_UNITS+=("tf2tfliteV2" "luci-interpreter" "circle-verify")
  REQUIRED_UNITS+=("record-minmax" "circle-quantizer")

  # TODO Use "nncc configure" and "nncc build"
  cmake \
    -DCMAKE_INSTALL_PREFIX="${NNCC_INSTALL_PREFIX}" \
    -DCMAKE_BUILD_TYPE=release \
    -DBUILD_WHITELIST=$(join_by ";" "${REQUIRED_UNITS[@]}") \
    ${EXTRA_OPTIONS[@]} \
    "${NNAS_PROJECT_PATH}/infra/nncc"
}

function preset_install()
{
  install -t "${NNPKG_INSTALL_PREFIX}/bin" -D \
    "${NNAS_PROJECT_PATH}/tools/nnpackage_tool/model2nnpkg/model2nnpkg.sh"

  # Install tf2nnpkg
  install -T -m 755 -D "${SCRIPT_PATH}/res/tf2nnpkg.${PRESET}" "${NNAS_INSTALL_PREFIX}/bin/tf2nnpkg"

  # Create python virtual enviornment
  python3 -m venv "${NNAS_INSTALL_PREFIX}/bin/venv"

  # Install tensorflow
  source "${NNAS_INSTALL_PREFIX}/bin/venv/bin/activate"
  python -m pip --default-timeout=1000 --trusted-host pypi.org --trusted-host files.pythonhost.org \
    install -U pip setuptools
  python -m pip --default-timeout=1000 --trusted-host pypi.org --trusted-host files.pythonhost.org \
    install tensorflow==2.2.0
}
