#!/bin/bash

function preset_configure()
{
  REQUIRED_UNITS=()
  # Common Libraries
  REQUIRED_UNITS+=("angkor" "bino" "cwrap" "fipe" "pepper-str" "pepper-strcast" "pp" "stdex")
  REQUIRED_UNITS+=("oops" "pepper-assert")
  # Hermes Logging Framework
  REQUIRED_UNITS+=("hermes" "hermes-std")
  # loco IR and related utilities
  REQUIRED_UNITS+=("loco" "locop" "locomotiv" "logo-core" "logo")
  # loco IR extension: Custom Op Support
  REQUIRED_UNITS+=("locoex-customop")
  # TensorFlow Libraries
  REQUIRED_UNITS+=("tfinfo" "plier-tf")
  # TensorFlow GraphDef I/O
  REQUIRED_UNITS+=("mio-tf")
  # TensorFlow Frontend (.pb/.pbtxt -> loco.caninical)
  REQUIRED_UNITS+=("moco-log" "moco" "moco-tf")
  # TensorFlow Lite/Circle Backend (loco.canonical -> .tflite, loco.circle -> .circle)
  REQUIRED_UNITS+=("exo")
  # Tools
  REQUIRED_UNITS+=("tf2nnpkg")

  NPROC=$(cat /proc/cpuinfo | grep -c processor)

  # TODO Use "nncc configure" and "nncc build"
  cmake \
    -G "MSYS Makefiles" \
    -DTF2NNPKG_FOR_WINDOWS=ON \
    -DUSE_PROTOBUF_LEGACY_IMPORT=ON \
    -DCMAKE_EXE_LINKER_FLAGS="-Wl,--allow-multiple-definition" \
    -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--allow-multiple-definition" \
    -DENABLE_TEST=OFF \
    -DDOWNLOAD_GTEST=OFF \
    -DBUILD_GTEST=OFF \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_INSTALL_PREFIX="${NNCC_INSTALL_PREFIX}" \
    -DCMAKE_BUILD_TYPE=release \
    -DBUILD_WHITELIST=$(join_by ";" "${REQUIRED_UNITS[@]}") \
    -DEXTERNALS_BUILD_THREADS=$((NPROC/2)) \
    ${EXTRA_OPTIONS[@]} \
    "${NNAS_PROJECT_PATH}/infra/nncc"
}

function preset_install()
{
  # Install libraries to bin/ for Windows release
  mv ${NNCC_INSTALL_PREFIX}/lib/*.dll ${NNCC_INSTALL_PREFIX}/bin
  rm -rf ${NNCC_INSTALL_PREFIX}/lib
}
