# automatically generated by the FlatBuffers compiler, do not modify

# namespace: onert_tflite


class SparseIndexVector(object):
    NONE = 0
    Int32Vector = 1
    Uint16Vector = 2
    Uint8Vector = 3
