# Network containing Shape node, which becomes Reshape's 'shape' input
# Note that this is a work-around to test Shape
#
#                (tensor)
#   Placeholder ---------- Reshape
#                        /
#     Const --- Shape ---
#                      (shape)
node {
  name: "Placeholder"
  op: "Placeholder"
  attr {
    key: "dtype"
    value { type: DT_FLOAT }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim { size: 6 }
      }
    }
  }
}
node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value { type: DT_FLOAT }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim { size: 2 }
          dim { size: 3 }
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "Shape"
  op: "Shape"
  input: "Const"
  attr {
    key: "T"
    value { type: DT_FLOAT }
  }
  attr {
    key: "out_type"
    value { type: DT_INT32 }
  }
}
node {
  name: "Reshape"
  op: "Reshape"
  input: "Placeholder"
  input: "Shape"
  attr {
    key: "T"
    value { type: DT_FLOAT }
  }
  attr {
    key: "Tshape"
    value { type: DT_INT32 }
  }
}
