name: Build and publish docker image for CI/CD infra
on:
  workflow_dispatch:

jobs:
  # TODO Add test job for each image before publishing
  publish-image:
    if: github.repository_owner == 'Samsung'
    strategy:
      matrix:
        version: [ 'android-sdk', 'focal', 'jammy', 'noble' ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          file: ./infra/docker/${{ matrix.version }}/Dockerfile
          push: true
          tags: nnfw/one-devtools:${{ matrix.version }}
