name: Build circle-interpreter

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Current develop version plus 0.0.1'
        required: true
        default: '1.30.1'

defaults:
  run:
    shell: bash

# Cancel previous running jobs when pull request is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  onecc-test:
    if: github.repository_owner == 'Samsung'
    strategy:
      matrix:
        ubuntu_code: [ focal, jammy ]
        include:
          - ubuntu_code: focal
            ubuntu_ver: 2004
          - ubuntu_code: jammy
            ubuntu_ver: 2204
    runs-on: ubuntu-latest
    container:
      image: nnfw/one-devtools:${{ matrix.ubuntu_code }}
      options: --user root
    name: circle-interpreter ubuntu ${{ matrix.ubuntu_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          path: 'code'

      - name: Build Debian package
        env:
          DEBEMAIL=nnfw@samsung.com
        run: |
          cd code
          mkdir -p debian
          cp -Rvf infra/debian/circle-interpreter/* ./debian/.

          # update version with ~YYMMDDHH
          release_semver=${{ inputs.version }}
          build_number=$(date +"%y%m%d%H")
          version="$release_semver~$build_number"
          dch -c ./debian/changelog -b -v "$version" "$version release"
          dch -c ./debian/changelog -r ""

          # build
          debuild -us -uc -b

      # NOTE Upload Artifact will be removed after testing
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: circle_intp_${{ matrix.ubuntu_ver }}
          retention-days: 2
          path: |
            ./circle-interpreter*.deb

      # TODO add publish to launchpad.net
