name: Build circle-interpreter debian package

on:
  # TODO turn on schedule
  #schedule:
  #  # 05:00 AM (KST, UTC+9:00) Mon-Fri
  #  - cron: '00 20 * * 0-4'
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Cancel previous running jobs when pull request is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  configure:
    if: github.repository_owner == 'Samsung'
    name: Set current date and time
    runs-on: ubuntu-latest
    steps:
      - name: Set date and time
        run: |
          echo "TODO: Setting date and time"

  debian-release:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Prepare, set distro versions
        run: |
          echo "TODO: Prepare and set distro versions"

      - name: Build without test
        run: |
          echo "TODO: Build without test

      - name: Gather files
        run: |
          echo "TODO: Gather files"

      - name: Upload Artifact
        run: |
          echo "TODO: Upload Artifact"

  create-pr-on-success:
    name: Create changelog update PR on success
    needs: debian-release
    runs-on: ubuntu-latest
    steps:
    - name: Create PR branch and commit changelog
      run: |
        echo "TODO: Create PR branch and commit changelog"
