name: Build docker image for Cirlce-MLIR CI/CD infra

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    if: github.repository_owner == 'Samsung'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'u2204' ]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          file: ./circle-mlir/infra/docker/${{ matrix.version }}/Dockerfile
          push: true
          tags: nnfw/circle-mlir-build-${{ matrix.version }}
