.TH ONE-INFER "1" "June 2022" "one-infer version 1.21.0" "User Commands"
.SH NAME
\fBone-infer\fR \- infer model file
.SH DESCRIPTION
usage: one\-infer [\-h] [\-v] [\-V] [\-C CONFIG] [\-b BACKEND | \-d DRIVER] [\-\-] [COMMANDS FOR BACKEND]
.PP
\fBone\-infer\fR is a command line tool to infer model.
.PP
[\-b BACKEND] and [\-d DRIVER] are mutually exclusive options.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-V\fR, \fB\-\-verbose\fR
output additional information to stdout or stderr
.TP
\fB\-C\fR CONFIG, \fB\-\-config\fR CONFIG
run with configuation file
.TP
\fB\-b\fR BACKEND, \fB\-\-backend\fR BACKEND
backend name to find \fIBACKEND\fR\-infer driver
.TP
\fB\-d\fR DRIVER, \fB\-\-driver\fR DRIVER
backend inference driver name to execute
.SH COPYRIGHT
Copyright \(co 2022 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-infer
is maintained as a Texinfo manual.  If the
.B info
and
.B one-infer
programs are properly installed at your site, the command
.IP
.B info one-infer
.PP
should give you access to the complete manual.
