.TH ONE-INIT "1" "May 2022" "one-init version 1.21.0" "User Commands"
.SH NAME
one-init \- init/create ONE config file
.SH DESCRIPTION
usage: one\-init [\-h] [\-v] [\-V] [\-t TEMPLATE_PATH] CFG_PATH
.PP
\fBone\-init\fR is a command line tool to init/create ONE config file.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-V\fR, \fB\-\-verbose\fR
output additional information to stdout or stderr
.TP
\fB\-t\fR TEMPLATE_PATH, \fB\-\-template_path\fR TEMPLATE_PATH
the template configuation file (onecc.template.cfg as default)
.TP
\fB CFG_PATH (as mandatory)
the cfg file name to init/create
.SH COPYRIGHT
Copyright \(co 2020\-2022 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-init
is maintained as a Texinfo manual.  If the
.B info
and
.B one-init
programs are properly installed at your site, the command
.IP
.B info one-init
.PP
should give you access to the complete manual.
