.TH ONE-PROFILE "1" "August 2021" "one-profile version 1.16.1" "User Commands"
.SH NAME
one-profile \- profile backend model file
.SH DESCRIPTION
usage: one\-profile [\-h] [\-v] [\-C CONFIG] [\-b BACKEND] [\-\-] [COMMANDS FOR BACKEND]
.PP
\fBone\-profile\fR is a command line tool for profiling backend model.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-C\fR CONFIG, \fB\-\-config\fR CONFIG
run with configuation file
.TP
\fB\-b\fR BACKEND, \fB\-\-backend\fR BACKEND
backend name to use
.SH COPYRIGHT
Copyright \(co 2021 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-profile
is maintained as a Texinfo manual.  If the
.B info
and
.B one-profile
programs are properly installed at your site, the command
.IP
.B info one-profile
.PP
should give you access to the complete manual.
