.TH ONE-INFER "1" "July 2024" "one-infer version 1.28.0" "User Commands"
.SH NAME
one-infer \- infer backend binary file
.SH DESCRIPTION
usage: one\-infer [\-h] [\-v] [\-C CONFIG] [\-d DRIVER | \fB\-b\fR BACKEND] [\-\-post\-process POST_PROCESS] [\-\-] [COMMANDS FOR BACKEND DRIVER]
.PP
command line tool to infer model
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-V\fR, \fB\-\-verbose\fR
output additional information to stdout or stderr
.TP
\fB\-C\fR CONFIG, \fB\-\-config\fR CONFIG
run with configuation file
.TP
\fB\-d\fR DRIVER, \fB\-\-driver\fR DRIVER
backend inference driver name to execute
.TP
\fB\-b\fR BACKEND, \fB\-\-backend\fR BACKEND
backend name to use
.TP
\fB\-\-post\-process\fR POST_PROCESS
post processing script to convert I/O data to standard
format
.SH COPYRIGHT
Copyright \(co 2020\-2024 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-infer
is maintained as a Texinfo manual.  If the
.B info
and
.B one-infer
programs are properly installed at your site, the command
.IP
.B info one-infer
.PP
should give you access to the complete manual.
