.TH ONE-PACK "1" "August 2021" "one-pack version 1.17.0" "User Commands"
.SH NAME
one-pack \- package circle and metadata into nnpackage
.SH DESCRIPTION
usage: one\-pack [\-h] [\-v] [\-V] [\-C CONFIG] [\-i INPUT_PATH] [\-o OUTPUT_PATH]
.PP
\fBone\-pack\fR is a command line tool to package circle and metadata into nnpackage.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-V\fR, \fB\-\-verbose\fR
output additional information to stdout or stderr
.TP
\fB\-C\fR CONFIG, \fB\-\-config\fR CONFIG
run with configuation file
.TP
\fB\-i\fR INPUT_PATH, \fB\-\-input_path\fR INPUT_PATH
full filepath of the input file
.TP
\fB\-o\fR OUTPUT_PATH, \fB\-\-output_path\fR OUTPUT_PATH
full filepath of the output file
.SH COPYRIGHT
Copyright \(co 2020\-2021 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-pack
is maintained as a Texinfo manual.  If the
.B info
and
.B one-pack
programs are properly installed at your site, the command
.IP
.B info one-pack
.PP
should give you access to the complete manual.
