.TH ONE-IMPORT "1" "August 2021" "one-import version 1.16.1" "User Commands"
.SH NAME
one-import \- convert various format to circle
.SH SYNOPSIS
usage: one\-import [\-h] [\-C CONFIG] [\-v] driver
.SH DESCRIPTION
\fBone\-import\fR is a command line tool to convert various format to circle.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit
.TP
\fB\-C\fR CONFIG, \fB\-\-config\fR CONFIG
run with configuation file
.TP
\fBdriver\fR driver name to run (supported: tf, tflite, bcq, onnx)
.SH COPYRIGHT
Copyright \(co 2020\-2021 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B one-import
is maintained as a Texinfo manual.  If the
.B info
and
.B one-import
programs are properly installed at your site, the command
.IP
.B info one-import
.PP
should give you access to the complete manual.
