.TH TFLITE-INFER "1" "August 2022" "tflite-profile version 1.17.0" "User Commands"
.SH NAME
tflite-infer \- infer tflite model file
.SH DESCRIPTION
usage: tflite\-infer [\-h] [\-l TFLITE MODEL] [\-\-input\-spec INPUT SPEC]
.PP
[\-\-dump\-input\-npy INPUT NPY NAME] [\-\-dump\-input\-h5 INPUT H5 NAME]
.PP
[\-\-dump\-output\-npy OUTPUT NPY NAME] [\-\-dump\-output\-h5 OUTPUT H5 NAME]
.PP
\fBtflite\-infer\fR is a command line tool to infer tflite model.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
.SH COPYRIGHT
Copyright \(co 2022 Samsung Electronics Co., Ltd. All Rights Reserved
Licensed under the Apache License, Version 2.0
https://github.com/Samsung/ONE
.SH "SEE ALSO"
The full documentation for
.B tflite-profile
is maintained as a Texinfo manual.  If the
.B info
and
.B tflite-profile
programs are properly installed at your site, the command
.IP
.B info tflite-profile
.PP
should give you access to the complete manual.
