#!/bin/bash

# Copyright (c) 2020 Samsung Electronics Co., Ltd. All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[[ "${BASH_SOURCE[0]}" != "${0}" ]] && echo "Please don't source ${BASH_SOURCE[0]}, execute it" && return

function Usage()
{
  echo "Usage: $0 [COMMAND] ..."
  echo "Command:"
  echo "  unittest"
  exit 255
}

DRIVER_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH=$DRIVER_PATH/../tests/scripts
export PATH=$DRIVER_PATH:$PATH

COMMAND=$1; shift
if [[ -z "${COMMAND}" ]]; then
  Usage
  exit 255
fi

# Parse command
case $COMMAND in
  '--help')
    usage
    ;;
  'unittest')
    source $SCRIPT_PATH/unittest.sh $@
    ;;
  *)
    echo "Unknown command: ${1}"
    exit 1
    ;;
esac

